### ISSUE TITLE
Message "Press any key to skip" does not skip always. 

### ISSUE THREAD

**Issue by mpjf01** [FrSkyRC/ETHOS-Feedback-Community#10]
ETHOS Simulator V16. Windows 7 64 bit version.

Opening screen, Error Message "Throttle Warning  Throttle not Idle" 

There's a box says "press any key to skip". Pressing any key does not skip every time. 

Close window box (top right x) does not close window, but pressing it locks the sim and it can only be closed using Task Manager.

**Comment by mpjf01** [comment]
Once I get to MDL/Telemetry screen I can't get back. RTN does nothing. I can back out of all the other functions referenced on the MODEL screen.

**Comment by mpjf01** [comment]
I'm trying to set up a standard AETR mix with 2 Aileron channels and 2 flap channels. Ail on Ch 1 and 5, flaps on 6 and 7. I can't make Ail on Ch 5.

**Comment by DaySpeed955i** [comment]
windows 8.1 here ETHOS V16.
No problems with "press any key to skip"

I did a free mix, when SD on, flap down with a curve, mix to Ail (ch1) and Ail(ch5), seam to work fine, Ails moves when changing curve or offset values.
Use Channels count to get 3 channels, Flap, Ail(ch1), Ail(ch5) or 4 is 2 servos for flaps.

**Comment by andika207** [comment]
the V16 simulator window is larger than the V15 sim one and cannot be resized for 17 inches TFT displays.

**Comment by bsongis-frsky** [comment]
"press any key to skip" => a simulator key? or your PC key?

**Comment by mpjf01** [comment]
Sim key. The group on the left - MDL, PGup... etc. Some work, some do not. Which keys fail seems to vary from one startup to another. Maybe it's an issue with my PC/mouse.

**Comment by bsongis-frsky** [comment]
Just PgUp/Dn won't work as it's used in case you have many warnings to fix and the window has scroll...

**Comment by bsongis-frsky** [comment]
If no scroll needed, PgUp/Dn will work as other keys
