### ISSUE TITLE
Global Variable

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#100]
Are you planning to implement global variables in Ethos?
It would be very helpful as programming with these variables would be easier.

**Comment by Peschi90** [comment]
+1

**Comment by dwheeld** [comment]
I would also like to see Global Variables added to Ethos. There are many uses for this feature and I miss it very much since moving over from OTX.

**Comment by centertrim** [comment]
I would like to get per-model global variables that can be persistent across shutdowns and model changes.  I am lazy, so a persistent variable used as a counter (incremented by a switch edge) is the only kind of flight counter I will bother using for each model.  So ideally they also need to be able to count to 1000+ in case it’s an exceptionally long-lived aircraft.

**Comment by Caledi** [comment]
I´d like to see global variables in ETHOS too.

**Comment by mawzthefinn** [comment]
VAR Mixes can replace most GVAR uses and can be selected by more than just Flight Modes, but does not address GVAR uses where you need to be able to persistently increment/decrement or adjust the current selected value.

**Comment by strgaltdel** [comment]
detailed (and very good) description of  possible GVar implementation:
/more a blue print

#779

**Comment by mawzthefinn** [comment]
Closing off this older requests in favour of #779 as it has more details and is assigned to a milestone.
