### ISSUE TITLE
Initialisation Issue with System Events

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1000]
I use the sticky throttle cut mechanism for my electric models, which works fine. In oder to signal the THROTTLE CUT status I use two dedicated sound files. Playing of these sound files is triggered by the two system events THROTTLE CUT and -THROTTLE CUT, respectively. Now when THROTTLE CUT is selected during power up (which is the normal case), then both sound files are played. This must be due to the initialisation of the THROTTLE CUT system state, which obviously results in a short period where no THROTTLE CUT is signalled, before the status correctly reflects the setting of the associated controls (i.e. throttle stick and TC switch).
The same happens upon selecting a different model, by the way.

As a workaround, I have disabled playing of these sound files on power-up, but the system should not react on any interim status caused by the initialisation process. Moreover, in the event that the throttle cut is not set at power-up, and the correcponding switch warning is ignored, the radio really should play the corresponding sound file, in order to warn that the motor is armed.

Radio is a Horus X10S Express with ETHOS 1.0.11.

**Comment by bsongis-frsky** [comment]
Good explanation and analysis of the issue, thanks!

**Comment by Hartinger** [comment]
I retested this problem with 1.0.12 RC1 and found that a residual problem still exists. If I change from a model that has no motor (and hence no throttle mix) to a model with a throttle mix, then the problem is still present. I.e. the sound file for motor activated is played, although the throttle cut switch is engaged.

On power-up, I could not see the problem anymore.
