### ISSUE TITLE
Model file corruption

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1002]
I had a helicopter model that I was finalizing and at some point I came up with model data that was not readable. I am trying to repro it, exactly, but I believe it is the "DIY" sensor. I was attempting to get an LCell sensor for my MLVSS like I have on OTX.   The model file attached cannot be read anymore.

[model02.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7230345/model02.zip)

**Comment by bsongis-frsky** [comment]
This model file seems OK, and it is an Airplane, not an Heli. Are you sure you attached the right file?

**Comment by guycnicholas** [comment]
Arggg. Since the filenames are generic it was just a guess based on the file date...I apparently guessed wrong and next time I will send in more model files. At this point I cannot recreate the issue so I will close it. If I can recreate it later, I will reopen it and attach correct files.
