### ISSUE TITLE
Flap to Elev mix fails to do anything

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1004]
Adding a flaps => Ele mix results in now elevator mixing. All other mixes, ele=>camber, rud=>ail, etc all immediately take effect just by adding the mix. the Flaps=>Ele however adds a mix that doesn't do anything.

**Comment by Nicholas-Luoyi** [comment]
You should enter the edit page of the Flaps => Ele mix to choose an input for it. Before it starts to work...

**Comment by guycnicholas** [comment]
Sorry, I should have been more clear. Here is an Ail => Rud mix, notice there is no, "source" because it is assumed to be the ailerons.
![image](https://user-images.githubusercontent.com/5494702/134911383-a54cbbb5-37cd-41a4-a26f-16411ab4f21f.png)
However the Ele=>Flaps mix requires a source. It seems to be the only custom mix to require one. All the others assume the first item in the mix name is the source.
![image](https://user-images.githubusercontent.com/5494702/134911607-e41f67d0-4224-4bda-9593-f1ed919dc999.png)

**Comment by bsongis-frsky** [comment]
In your comment you mention Ele => Flaps, but your screenshot is Flaps => Ele

**Comment by bsongis-frsky** [comment]
For Flaps => Ele you need a source. If you setup one does it work correctly?

**Comment by guycnicholas** [comment]
Sorry yes, I wrote it backwards in the comment. I guess then the question is why is this particular mix not automatically setup like the others?  I don't want to waste your time answering questions, so I am fine if you just want to close this.

**Comment by Nicholas-Luoyi** [comment]
No. They are not the same. Those two issues you just mentioned is about the slow value. The Flaps => Ele mix will allow you choose a source as an input. This is what  we designed.
