### ISSUE TITLE
low signal default warning

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1006]
Hello.

i suggest having active RSSI / low signal warnings on by default. even without discovering sensors, for 2 reasons:
1. its safer to always have the low signal / telem lost alerts enabled.
2. it will help many people migrating from Opentx to Ethos that are used to these alerts to be on by default.

**Comment by jreis1** [comment]
is it not active by default ? 
I think it is ! RSSI at least!

**Comment by i3dm** [comment]
> is it not active by default ?
> I think it is ! RSSI at least!

no its not

**Comment by loetefix** [comment]
i3dm is right, after binding and no sensor discover , there are no rssi warning. rssi sensor should be automaticly added to sensors if it is not in the list when  detecting a rssi value from a RX.

**Comment by i3dm** [comment]
> i3dm is right, after binding and no sensor discover , there are no rssi warning. rssi sensor should be automaticly added to sensors if it is not in the list when detecting a rssi value from a RX.

exactly
@bsongis-frsky

**Comment by loetefix** [comment]
btw it would be nice to pop up a window if a new sensor is detected like:

New Sensor detectet. Add to Sensors?
YES     NO     Dont ask again for that Sensor.

**Comment by bsongis-frsky** [comment]
RSSI / SWR is detected without the need of a sensor

**Comment by i3dm** [comment]
> RSSI / SWR is detected without the need of a sensor

is that a new feature?
it wasnt like that before.

**Comment by mawzthefinn** [comment]
Not sure when it was added, but it's definitely new in either 1.3.x or early 1.4

It's there now for sure, so closing this off as completed.
