### ISSUE TITLE
No automatic change of the model ID

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#101]
Horus x10 +isrm - Ethos V1.0.2
I have just programmed several models and I realize that they all use the 0 idea.
So I found 3 models that work together.
"X6R and X8R receiver"
Under OpenTx the idea changes automatically.
It is necessary to do the same thing with Ethos.
Thank you.

**Comment by BobCotsford** [comment]
Or perhaps a warning that the model ID# is already in use could be displayed?
