### ISSUE TITLE
Wizard ely

### ISSUE THREAD

**Issue by LProia** [FrSkyRC/ETHOS-Feedback-Community#1011]
Hello,
i am running ethos 1.0.11 on X20S, you can get the channel assignment request from the helicopter wizard. example: gas, rud, ail, elev, pitc on ch 1 or 2 or 3 etc.
now they start from channel 3 and i can't use 6 channel RX

**Comment by LProia** [comment]
The CYC is assigned to ch 5-6-7

**Comment by mawzthefinn** [comment]
You can work around this by disabling 'First Four Channels fixed' in System->Sticks

**Comment by mawzthefinn** [comment]
Duplicate of #999, closing in favour of that issue
