### ISSUE TITLE
LUA

### ISSUE THREAD

**Issue by seilfly** [FrSkyRC/ETHOS-Feedback-Community#1014]
What are the plans with LUA script support and possibly CRSF support ?

**Comment by loetefix** [comment]
There are already request for that. Please don't open new issue for that.

**Comment by MIKE-DAILEY** [comment]
Duplicate #202

**Comment by seilfly** [comment]
> There are already request for that. Please don't open new issue for that.

Sorry, did not see that.
Even though I did not get an answer to the question!
