### ISSUE TITLE
Problem with Subtrim

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#1015]
When I set my Servo middle point with subtrim, the end positions of the Servo are still the same.
It is possible that the end positions (+/-100%) change when I change my middle position with the Subtrim.
For example my Servo middle position is not ok, I have to put +5% Subtrim than is the position ok.
I wish me that die new end positions change to (-95/+105%). So I have the same Rate at both sides. When you look at the other systems they all make it this way.

**Comment by STC148** [comment]
duplicated #751
