### ISSUE TITLE
Critical rssi alert when the x20s is connected to 2 receivers.  

### ISSUE THREAD

**Issue by MeniLew** [FrSkyRC/ETHOS-Feedback-Community#1016]
When there is a dind to 2 different receivers.  The remote does not give an rssi critical alert even when the reception level drops below 32 db on the 2 receivers (it does give a low rssi alert).

**Comment by aalain8** [comment]
If it's an X20/s ??? 
There is a new RF firmware: TD 2.1.14
https://www.frsky-rc.com/tandem-x20s/

**Comment by MeniLew** [comment]
> There is a new RF firmware: TD 2.1.14 https://www.frsky-rc.com/tandem-x20s/

I checked it after updating to 2.1.14

**Comment by Adelaxie** [comment]
Can not repeated

**Comment by mawzthefinn** [comment]
Does this still occur on current TD-ISRM and Archer firmware?

**Comment by mawzthefinn** [comment]
Closing off as no additional information provided
