### ISSUE TITLE
Audio alert for 6poa switch should detect a second press? 

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#1018]
If you create a special function that plays an audio file on the 6pos switch, am exception occurs in that you only get the audio alert if you press the button when it's not active.

What this means is that if you press an active button, you have no way of knowing what flight mode you are using, until your exit the active mode.. Then return.

While this is no different to a 3 pos switch, it would be helpful in the case of the 6 pos to detect this event.

**Comment by bsongis-frsky** [comment]
I see no difference with a 3 Pos switch here. You will get the same behaviour if you assign your flight modes to a 3-POS switch, no?

**Comment by bsongis-frsky** [comment]
Instead I would see some options for this kind of switch. Here you need to play a file when the physical switch is pressed, no matter the 6-POS switch position is.

**Comment by robthomson** [comment]
Totally.. But with a 3pos you know which way its going by feel
  Not so when the 6pos.
