### ISSUE TITLE
chronos and functions

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#102]
rasquin robert (Email: rrasquin@voo.be) wrote:
hello , on ethos os, how to program a chrono which counts the second engine and another which start when this stops, the two chronos controlled by slide left for example? (for gilder with motor ) thank you for your response.

2) sorry but some functions are missing compared to opentx (x12 os1.0.1) ?? forget it?? (bistable-!-flanc...) not found.

3)not found a throttle cut ....?  ( function max-remplace)

GOOD GRAPHICS  ..... to see more!  thank you for this good work.

**Comment by mawzthefinn** [comment]
1. More information required, what's the stop condition for the first timer stopping

2. Please check on current version, you will find function parity with OpenTX for the most part

3. Please check out the Lock function in the Free Mixer for tihs.

**Comment by mawzthefinn** [comment]
Closing as stale. If the timer stop condition is the one reported in your other issue, it's fully supported in ETHOS today
