### ISSUE TITLE
Model wizard and para

### ISSUE THREAD

**Issue by przepka1985** [FrSkyRC/ETHOS-Feedback-Community#1020]
I got Horus X10 with ISRM and Para update.
First issue is on model wizard. I was able to create first model, but I  ot able to create second one through wizard. After selecting + I get (glider, airplane, heli, multirotor) but after select its not opening wizard anymore.
Second issue is para wireless module dont sending any bt signal (I was not able to find bt devices on my mobile phone)
Last issue (maybe not issue) I was get message about "please update tx firmware" or something like that. Where I can find firmware for isrm module for Horus X10 (td isrm and got separate file on ethos website)

**Comment by bsongis-frsky** [comment]
Where did you see "Please update TX firmware"? 
Which firmware did you flash?

**Comment by przepka1985** [comment]
Update sorted out, it was r9m 2019.
But still got no bluetooth from para wireless module and wizard dont work for mor than once.

**Comment by bsongis-frsky** [comment]
The wizard is started only on model creation

**Comment by bsongis-frsky** [comment]
Telemetry / Bluetooth is implemented in 1.0.12
