### ISSUE TITLE
RX Batt Reporting different on R9SX and R8Pro

### ISSUE THREAD

**Issue by Joetrin** [FrSkyRC/ETHOS-Feedback-Community#1021]
Hi All,

This is on the same plane, using a redundant power supply sharing the same power bus.  Both receivers are plugged into the same power source and it seems that they are both reporting different voltages.  I'm not sure if this is Ethos or Hardware, just posting it here.  TD Firmware 2.1.14 / Ethos Version 1.0.11

![image](https://user-images.githubusercontent.com/19473795/135716857-635f2b63-c739-4d2b-a395-a826595d83cf.png)

Also attached is the log file:

[-01-ARS-300-102-2021-09-26-13-24-29.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7271467/-01-ARS-300-102-2021-09-26-13-24-29.csv)

**Comment by Ceeb182** [comment]
There is a difference ΔV=7.68-7.55=0.13V between the two measurements.   
According to the logs, this ΔV is constant throughout the recording.  
If we estimate that the full scale is 10V (example for an "Archer R8 PRO" with an "Operating Voltage Range: 3.5-10V") then the error is 0.13/10=0.013=1.3%.  
It seems to me that an error of 1.3% is really very low for this kind of device.

**Comment by bsongis-frsky** [comment]
For sure it is not Ethos!

**Comment by bsongis-frsky** [comment]
Did you try to adjust the voltage in your sensor settings?
