### ISSUE TITLE
Logic switch 

### ISSUE THREAD

**Issue by przepka1985** [FrSkyRC/ETHOS-Feedback-Community#1022]
Horus X10 isrm update 
Logic switch not working
A<X when A its Rssi and x its 35db but not trigger even if Rssi its 0.  Not sure it's issue or my mistake in something. I was use that combination for trigger sound on opentx before without any problems.

**Comment by bsongis-frsky** [comment]
Would you please try with different values, not 35dB / 0dB (no telemetry?)
Rather 90dB / 80dB

**Comment by mawzthefinn** [comment]
@przepka1985 did this work when you tested with the values provided by @bsongis-frsky ?

**Comment by mawzthefinn** [comment]
Closing as Stale
