### ISSUE TITLE
Invalid model file ...again!

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1026]
I've just spent an hour setting up this model (model04.bin). It was all fine with no problems while I was working on it. I then started working on another model (model06.bin). Again all was fine. I wanted to try and copy some logical switches over, to save me repeating myself. On trying to switch back to the earlier model, I get the Invalid data error. Both model files are in this zip.

[models.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7272220/models.zip)

Cloning the model did retrieve some of the data. But not a lot remains. All seems to be gone except for the mixer, outputs, and one logical switch. Everything else is gone, including the home screen, timers, logical switches, and special functions.

This is happening too often. This is about the 4th time I've lost a model file like this. This is a genuine 32GB SanDisk Ultra SD card, bought directly from SanDisk's official Amazon store. So that should not be the problem.

## Info screen
- **Firmware** Ethos - X20S
- **Firmware Version** 1.0.11, FLEX #8bd25e73
- **Date** Sep 14 2021, 11:14:56

**Comment by bsongis-frsky** [comment]
Yes this issue has been raised earlier. But it's the first time the invalid model file is attached.
Obviously there is something with long logic switch names.
The good thing is that your model file is OK,

**Comment by MrD-RC** [comment]
Glad I could help identify the problem @bsongis-frsky

If the model04 file is ok, can you attach a working version here please. The file I have won’t work on the transmitter, and the cloned version is basically starting from the beginning too.

**Comment by bsongis-frsky** [comment]
Yes I will, as soon as the issue is nailed.

**Comment by MrD-RC** [comment]
Awesome. Thank you.

**Comment by bsongis-frsky** [comment]
This is this switch:
![image](https://user-images.githubusercontent.com/50834778/135810795-9076241b-a631-4b5a-9e04-7347613b8755.png)
It is stored with a 'A' at the end 'Th low, Arm posA' 
So the bug is in the TextEdit from libopenui I think

**Comment by bsongis-frsky** [comment]
Do you remember how you entered the name, I cannot succeed to go over the 15 chars, and obviously you did!

**Comment by bsongis-frsky** [comment]
Wow I just found it, you don't use the keyboard. I have succeeded to enter 18 chars.

**Comment by bsongis-frsky** [comment]
A way to reproduce:
- you enter 15 chars (the maximum allowed)
- you set the cursor at the end of the field
- you turn the wheel, it will do strange things

**Comment by MrD-RC** [comment]
@bsongis-frsky I’m sure that I used the keyboard for most of it. Only the jog wheel for special characters not yet on the keyboard or from a slip. 

One thing that I did notice is that one of the logical switches had an “e” character at the end that I didn’t add. When I tried to delete it, the “e” remained, but a character was trimmed from the end of the label.

**Comment by bsongis-frsky** [comment]
Yes, it is the same bug.

**Comment by bsongis-frsky** [comment]
[repaired04.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7276926/repaired04.bin.txt)

**Comment by MrD-RC** [comment]
@bsongis-frsky thank you so much for fixing that file. I really appreciate it.
