### ISSUE TITLE
channel sequenzer 6-8 channels and max 25s timing, Graphically programmable

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1027]
This function is still missing 
Channel sequencer for 6-8 channels
Graphically programmable

Since Ethos is graphically oriented, you could also set a ready-made sequencer for 6-8 channels with a timing of max 25s.
Then you don't need to use a ready made third party product from Jeti or other manufacturers.

**Comment by abelsingla** [comment]
I'm agree, I'm comming from Jeti and this is the only funktion missing for me right now.

**Comment by bsongis-frsky** [comment]
Duplicate of #657
