### ISSUE TITLE
SBUS input/output on DSC socket required

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1028]
SBUS input/output on DSC socket required

Archer receivers have no CPPM output anymore
but all receivers have SBUS.

If you also had SBUS In/Out at the DSC socket you could feed in up to 16 more channels with a SBus timing of 9/18ms.

So you have many possibilities e.g. more encoders,
analog or digital, Potis oder Switches
or also a wireless teacher/student system with SBUS in at DSC Teacher

Since Bleutooth PARA is too slow and causes servo shaking

**Comment by hrenz** [comment]
No its not Hardware, its only software like openTx has

**Comment by mawzthefinn** [comment]
Duplicate of #784, closing in favour of that issue
