### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#1029]
Good morning.
My new Horus X10Ex has been upgraded to Ethos and here are a list of bugs I found:
* Model images appear only rarely. They are on the right plac ein the SDcard and with the same size as the original ones.
*  Model images are with very very poor resolution, only in BMP format -not PNG). Plese instruct what characteristics should a user image have.
* the choice of actuators (3 pos switches) by moving them, does not work always and sometimes gets to stay on the wrong position.
* in some cases an extra offset of 30% appears from no where in the mixers.
* once I got a 'critical error' warning with some loud whistling, for no reason: instability.
Firmware Ethos X10 Express, version 1.0.11 8bd25e73 14th sept 2021

Thanks

**Comment by Malone76** [comment]
Bonjour, je constate le meme probleme que vous concernant les images de model version 1.0.11

**Comment by miksterr** [comment]
> Bonjour, je constate le meme probleme que vous concernant les images de model version 1.0.11

Hello - if someone posts in English please use a translator to keep in same language.

Bonjour - si quelqu'un publie en anglais, veuillez utiliser un traducteur pour rester dans la même langue.

**Comment by bsongis-frsky** [comment]
One issue per problem please!
1) Model bitmaps = already answered in another issue. The resolution will depend on your file, and the LCD resolution obviously.
2) 3 Pos switches, it's strange, please explain more, what is the delay of the MID-Position of your setup? Is it better if you lower it?
3) Extra Offset of 30%. I need more information about your setup
4) I don't know what you mean by Critical Error. If you were editing a name (logic switch / mix name / etc.) this bug has been fixed

**Comment by Billy60** [comment]
Thanks Bsongis
* 3 pos switches: it is almost constant , the delay on the mid position is already at 0. The choice of actuator either is made by going through a list or disrectly by moving the chosen actuator. Starting from the 1st position, If you want the 3rd pos of a 3 pos switch to be chosen, it stays on the mid one.
* The 30% offset is mainly on the Mixers: it comes on the Flap mix. It does not appear on the free mixes which I use now. Too bad ...
* The 'critical error' is a warning message which appeared with a loud alarm. I had to power off the Tx to get rid of it. It happened if I can remember properly when I was trying to select another model, going away from my current one.
* The model images which are delivered with the Horus have a small size (some 200 px) and a standard resolution (144 px/inch). They appear fine and detailed enough. If I find anothe rimage with this same weight and res, it appears whith only a few pixels, or is not chosen at all.
