### ISSUE TITLE
Model file corrupted after RB-20 sensor discovery using 2 receivers, one RXSR and one R9MM

### ISSUE THREAD

**Issue by greggibbons** [FrSkyRC/ETHOS-Feedback-Community#103]
After setting up a new airplane model using a X20 w/ETHOS V1.01, one RB-20 w/RB20_ACCESS_20200702.frk, one RXSR  w/RXSR-ACCESS_2.1.0.frk, and one R9MM OTA w/ACCESS V1.3.1 R9MINI_OTA_FCC.frk. Both receivers register and bind, all the servos work, discovering all the sensors works fine until the X20 is powered down and powered up again, an error message pops up saying- "Model data load, Invalid data". The X20 can no longer load file model04.bin. This was very frustrating after spending many hours creating a new model then loose it while learning ETHOS. So I created it again saving it many times, then once again after discovering the sensors and powering down the model file became corrupted, I reloaded it a third time to verify and again the file became corrupted after sensor discovery and power down. 

Attached are 2 model files, model05.bin was saved prior to sensor discovery and the corrupted model04.bin after sensor discover, hope that helps with discovering the issue.
[model files.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6344565/model.files.zip)

**Comment by centertrim** [comment]
Nicely done on the before & after model files Greg.  I'm sure that will be helpful for them to diagnose the issue.

I appreciate you taking a shot at this on a RB-20 2.4/900 setup... as that would be something similar to what I would do on a big gasser.  Hopefully they will get this issue fixed quickly.

**Comment by greggibbons** [comment]
This setup works well using an X10S Express with OpenTX on my 35% Extra 300. Looking forward to using the X20 once this bug is fixed.

Greg

**Comment by bsongis-frsky** [comment]
This one has been fixed in 1.0.2, it was an issue with too long names for the sensors, especially in Deutsch

**Comment by greggibbons** [comment]
Thank you, 1.0.2 took care of the problem.
