### ISSUE TITLE
probleme memoire flash horus 10 s express

### ISSUE THREAD

**Issue by Malone76** [FrSkyRC/ETHOS-Feedback-Community#1033]
Bonjour, impossible de lire la memoire flash de ma radio horus 10 s express lorsque que je suis en mode bootloader depuis l installatin de Ethos.

**Comment by bsongis-frsky** [comment]
Lire la mémoire flash ... c'est normal, elle n'est pas accessible. Vous ne devriez pas en avoir besoin, uniquement la SD est nécessaire

**Comment by Malone76** [comment]
Pourtant sur la version logiciel gros il y a un accès à la mémoire flash de la radio

Envoyé de mon iPhone
