### ISSUE TITLE
RF "freezes" for around 1 second during a flight randomly

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#1034]
Hi,
I am flying a 50cc Extra 260 equipped with the following:
- DA50 with CDI - far from Rx
- 2 LiPo 2S batteries 
- 2 FrSky NFC switch, one for each battery
- FrSky XACT servos
- R10 Pro as the main Rx (2.4GHz) - sbus in / servos conected here
- R9Slim as the redundancy Rx (900MHz) - sbus out
- Telemetry activated so I would hear the RF / RSSI alarms
- Tandem X20S (FCC)
--- First flight was with the FW version 1.0.10 and second flight with 1.0.11
--- RF FW version is TD 2.1.9

This setup went fine flying with my previous X10s (OpenTx) for around 5 to 7 flights. Then my X20S has arrived and I move the setup to the new radio.

In the first flight after a couple of minutes I noticed I have totally lost the control for around 1 second. The plane was not "receiving" my inputs from the sticks. It was frozen for around 1 second and no RSSI or telemetry lost alarm was triggered. The failsafe is configured to HOLD.
I was doing a turn and the plane was like in a knife edge position, far around 50 meters on my left. After that I landed and checked everything: setup, wiring, any kind of bad connection and I repeated many range tests with success. 
Well, after that I went flying more 8 to 10 times with no issues. 

Yesterday, the issue showed up again. The same behavior and the plane was almost at the same position: doing a turn, far around 50 meters on my left. The behavior was more clear yesterday because I was starting the roll (to a simple turn), but the system froze again for around 1 second, but now instead of holding the position the plane kept the rolling and the noose point down (I believe it kept rolling because failsafe is set to hold). After 1 second I managed to get the control back and landed the plane properly. 
No telemetry lost or RSSI low alarm was triggered again.

I really don't know what is causing this issue, but I believe there's something wrong maybe with the redundancy setup or the way the Ethos handles it.

I couldn't find any log in the SD card.

**Comment by bsongis-frsky** [comment]
First, please stop flying with this setup until we understand the issue.

You don't describe any Emergency reboot. I think there is none, the radio seems just working fine. If the mixer was "blocked" during > 500ms for whatever reason, you would switch to Emergency Mode.

1) Can you reproduce it on ground? 
2) It really looks like your plane doesn't receive anything. It would be interesting to know the RSSI level. 
3) Would you share here your model file?

**Comment by marciomc-github** [comment]
Correct, the radio did not went on Emergency mode, boot, or even any king of telemetry alarm (RSSI).

> 1. Can you reproduce it on ground?
> 2. It really looks like your plane doesn't receive anything. It would be interesting to know the RSSI level.
> 3. Would you share here your model file?

Hi,
1 - I tried many times to reproduce it on ground without "success".
2 - RSSI level is good, I believe, because I got no RSSI alarm during the flight.
3 - How can I post or e-mail the model file?

I figure out no logs were saved (there was no Log folder in the SD card). I just have it configured now and will try to reproduce the error on ground.

**Comment by marciomc-github** [comment]
Hi, please find attached the model file.

[model03.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7278403/model03.bin.zip)

**Comment by bsongis-frsky** [comment]
Would you please update to the latest TD-ISRM firmware version?

**Comment by marciomc-github** [comment]
> Would you please update to the latest TD-ISRM firmware version?

Sure. It is done. I will test again this weekend.

**Comment by PeterBeretta** [comment]
I had a similar issue this weekend with a 4m Salto glider with EDF. It has an RB20 with dual battery, an Archer R8 Pro and R9MX. I have my fail safe set to Crow Braking (Full flaps, negative aileron, kill throttle). Just after take off, my crow braking deployed for about 1 second, then went back, then a second time it deployed, then went back. Fortunately the throttle did not cut and I was able to keep climbing without stalling ($2000 glider excl radio gear). I have just updated the TD-ISRM to the latest firmware, but also added a 3rd receiver, an L9R plugged into the Archer R8 and bound to an external XJT module. I also moved my R9MX further down the inside of the fibreglass fuselage to ensure the carbon wings dont shield the signal. Both the 2.4GHz rx's are using an antenna mount that holds them at 90deg. Hope this solves the problem.

**Comment by marciomc-github** [comment]
Hi, 
Today I have done a couple of flights and the issue happened again, unfortunatelly without a log file, but I have some updates to share.

Before flying, here are the changes:
- I disconnected the R9Slim rx from the setup and removed the check for the second receiver (900Mhz) in the model configuration.
- TD-ISRM was updated to the latest (I had a small jitter on the rudder servo that has stoppped after this update)
- I noticed that RX version (R10 Pro) was not on the latest (v2.1.8) but I decided to keep the version (v2.1.6).

After the adjustments, the first flight went fine. I did a short and very conservative flight (around 4min).
I had a friend on my side looking at the RSSI telemetry on my X20S screen during all the flight and we noticed a drop to around 40dB at the point on my left where the issue usually happens.

- I changed the antennas position, but keeping the recommended practice of 90 degrees.

In the second flight, we noticed an increase on RSSI to around 50dB in worst case. After a couple of minutes, at the same place on my left, the issue happened again: 1 second "freeze", the plane kept rolling and the noose went down. I was aware, almost expecting to have it so I managed to correct after 1 second and had a safe landing.
Again, I did not get any kind of alarm (eg: RSSI low).

Unfortunately I forgot to record the flight log again. I do have the log for the first flight and will post it here.

After that, I moved the R10Pro Rx to a cheaper foamy plane, and made 2 flights: first I am not sure if I have issues, but the second with no issue at all. First was with the Rx in 2.1.6 firmware and second with 2.1.8 firmware.

So, it is important to bear in mind the adjusments I have made that checked out some possibilities:
- No RX2 was connected and  was removed from plane setup in the radio -- Redundancy is not the issue
- I was unable to replicate the error in a foamy

My list of possible causes of this issue:
- Batteries are too close to the iginition (it is not that close, but I would like to test moving the batteries away from ignition)
- Rx in version 2.1.6 - already upgraded it, but didn't test in a real flight
- Issue with R10 - my next test would be changing to a spare R8 (version 2.1.8)
- Issue with NFC switch (low probability because no rssi alarm was triggered during the flight)

Do you have any other clue?

4 files attached:
[Extra260-LEM-2021-10-04-09-27-38.csv] - 1st flight with 50cc Extra - no issues reported
[Tundra-2021-10-09-14-51-27.csv] - 1st flight with Foamy - Rx in v2.1.6
[Tundra-2021-10-09-15-11-16.csv] - 2nd flight with Foamy - Rx in 2.1.8
[model03.bin.zip] - updated Model file (Extra without redundancy - RX2)

[Tundra-2021-10-09-14-51-27.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7316383/Tundra-2021-10-09-14-51-27.csv)

[Tundra-2021-10-09-15-11-16.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7316384/Tundra-2021-10-09-15-11-16.csv)

[Extra260-LEM-2021-10-04-09-27-38.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7316382/Extra260-LEM-2021-10-04-09-27-38.csv)

[model03.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7316388/model03.bin.zip)

**Comment by PeterBeretta** [comment]
As a comparison of the flight logs with the same plane (4m Salto) using my original radio installation before I acquired the X20S with Archer receivers. This log file is of the plane using an RX8R-pro receiver running pre v2.x firmware. The 900MHz rx is a R9MM also with pre V2.x firmware. The TX is a Horus X12S running the latest version of OpenTX on that date (31st July 2021) with both internal external antenna. I am using an R9M module with super 8 antenna. My observation with all the upgraded technology is that range is is worse and because if this, more susceptible to interference. I have now ordered the FrSky 2.4GHz infinity external antenna and Moxon 868MHz antenna. Hopefully I will at least be able to get back to a similar level of RF stability that I had with the X12S.
[Salto_3-2021-07-31.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7319580/Salto_3-2021-07-31.csv)

**Comment by PeterBeretta** [comment]
Attached is a log file of two flights with the same Salto glider, but at an airfield which is on a farm, far away from houses, cell phone masts and other forms of radio interference sources. The Salto was aero towed for both flights and EDF+ESC removed. Only two receivers installed, the Archer R8 Pro and R9MX with the Tandem X20S tx. The 2.4GHz RSSI was acceptable and I only had a few "telemetry lost" notifications. 

Hence my conclusion is that Tandem/ACCESS performs fairly well in environments where there is little RF interference, but the 2.4GHz ISRM connection struggles in noisy RF environments. This may be due to poor performance of the internal antennas of the Tandem X20S when compared with the configuration I used on the X12S using both internal and external antennas.

One of our local pilots is an RF engineer and he is building some RF filters that we will experiment with to see if we can reduce the impact of the cellular interference caused by LTE operating at 2.3GHz. Each sector of the cellular base station transmits at an LTE signal on 2.3GHz at 20Watts. When we stood under the mast with a realtime spectrum analyser, we could see that there was RF noise spilling over into the 2.4GHz band and saturating some of the channels. 

[Salto-2021-09-26-12-43-58.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7320493/Salto-2021-09-26-12-43-58.csv)
s.

**Comment by PeterBeretta** [comment]
@bsongis-frsky The XJT module is plugged into the module bay at the back of the radio.

It could be a pulse race condition if there is some sort of harmonic happening with the LR12 protocol. The D16 and D8 protocols do not cause a problem.

The other option is that if the LR12 protocol transmits at a higher power, it could be swamping the 2.4GHz signal from the TD-ISRM. 

I have a 2.4GHz infinity antenna that I will attach and test again. The infinity antenna has a longer wave guide that enables it to be further away from the XJT module antenna.

**Comment by PeterBeretta** [comment]
Here is a link to the video where I test using the 2.4GHz Infinity antenna attached to output 1 on the Tandem X20S. The purpose to to separate the RF between the two modules. Indications are that the RF output from the XJT is not swamping the RF from the TD-ISRM. There is something that is directly related to the LR12 protocol and the TD-ISRM or the mixer in ETHOS as @bsongis-frsky mentioned.

https://youtu.be/d-4odsLWqyE

**Comment by PeterBeretta** [comment]
Thanks for the help from the guys on RCGROUPS, I think that the problem relates to the XJT swamping the telemetry link to the TD-ISRM. 

Video of the test: https://youtu.be/khaGwftVSXs

**Comment by marciomc-github** [comment]
After a long time and now with more experience I just realized what happened. I miss configured the R9 SX receiver without setting port 6 to SBUS. Probably the system was properly switching from 2.4 to 900 but there’s no sbus configured between to receivers. 
Pay attention to the wiring and test your system before flying switching on and off 2.4 and 900.
