### ISSUE TITLE
can not adjust vout2 on RB30 firmware 1.0.11

### ISSUE THREAD

**Issue by Tomnohr** [FrSkyRC/ETHOS-Feedback-Community#1035]
I have some trouble with the RB30 and x20. On x10 i have the opportunity to adjust Vout1 and Vout2. But on the x20 I only have Vout1 and Cur Calibr PW(78) when I measure the voltage on Vout2 it is the same as Vout1.
![243840195_10160056295927625_65251379016790510_n](https://user-images.githubusercontent.com/36129964/135765675-8d480c6c-9cb4-404a-a384-bd4c8e86e477.jpg)

**Comment by Jetman66** [comment]
Hello friends, I have got the same problem and I am waiting for a solution, too. Thanks in advance. Best regards from germany, Michael

**Comment by bsongis-frsky** [comment]
The label seems wrong. Or at least it's different from OpenTX, I don't know the reason.
- In OpenTX this field is named "VOut2(V)"
- In Ethos this field is named "Cur Calibr PW(78)"
But both fields have the same ID, so either OpenTX or Ethos is wrong. 

Given I have not seen this reported on OpenTX I will change Ethos now. Would you please check that if you change "Cur Calibr PW(78)" it does exactly what you need?" Thanks.

**Comment by Tomnohr** [comment]
If I try to adjust Cur Calibr PW(78) it jumps back to 5v. the output conectors have the same voltage and is the voltage of Vout1. so that has to be something wrong. 
the manual for rb30 say : The RB-30/RB-40 supports two SBEC outputs, DC 5-8.4V. The output voltage can be adjusted by the script or the Scroll button or the Freelink App. The supply voltage of CH1~CH24 and RX1~RX3 comes from the highest voltage.

**Comment by Jetman66** [comment]
Hello Bertrand, if I change cur callibration PW 78 it always jumps back to 5.0V if I push enter. Am I wright that the problem will be solved by editing ethos by yourself? It would be very important to have 2 different voltage outputs. Thank you in advance.Best regards from germanyMichael--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

 
  
  
 
 Am 04.10.21, 11:30 schrieb "Bertrand Songis @ FrSky" ***@***.***>:

   
  The label seems wrong. Or at least it's different from OpenTX, I don't know the reason. 
   
   In OpenTX this field is named "VOut2(V)" 
   In Ethos this field is named "Cur Calibr PW(78)" But both fields have the same ID, so either OpenTX or Ethos is wrong. 
   
  Given I have not seen this reported on OpenTX I will change Ethos now. Would you please check that if you change "Cur Calibr PW(78)" it does exactly what you need?" Thanks.

**Comment by DaySpeed955i** [comment]
This is were LUA script will help here. 2 different lua for 2 different firmware. So at this point ETHOS dev need to decide if they support legacy firmware or stick with the latest.

Depending on the firmware loaded on the RB-30/RB-40, Vout2  is either a calibration function of currant for ch1 to ch 8 and Vout1/Vout2 both have the same voltage control by Vout or for older firmware Vout1 and Vout2 can be adjusted independently.

LUA V1.02 has no Vout2 but Cur Calibr PW(78), 78 is the password to activate calibration.

Check FrSky site for versions.
