### ISSUE TITLE
Can't create model icon on X10s Express

### ISSUE THREAD

**Issue by SkyRaccoon** [FrSkyRC/ETHOS-Feedback-Community#1036]
Hello I want to create a model icons for Horus series (1.0.11).
I understand it's now BMP and not PNG anymore but I can't find the right format the BMP has to be to be recognized by the radio.
What's this BMP format and encoding ?
Thanks

**Comment by bsongis-frsky** [comment]
This is a place for issues, not questions, please use RCG, people will help you.
There are some bitmaps samples on the official SD, you could use exactly the same format
