### ISSUE TITLE
usb conection and power ON

### ISSUE THREAD

**Issue by Franjose1984** [FrSkyRC/ETHOS-Feedback-Community#1037]
Hello, it would be a good idea to enable the power on when the USB port is connected for charging or connected to the pc.
Let me explain, when the USB port is connected to charge or to the PC while the x20 is off it cannot be turned on, I must disconnect the USB, turn on the TX and then reconnect the USB.

Thanks.

**Comment by loetefix** [comment]
I think this is not possible, because the Microcontroller is in a special mode at this time. But lets see what the experts say.

**Comment by bsongis-frsky** [comment]
@loetefix right, the bootloader from ST doesn't allow that
