### ISSUE TITLE
Play track not seeing any files

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1039]
X20S.
tried both clean installs of V1.0.10 and V1.0.11.
file manager sees all voice files under audio/en (we put a bunch of voice files there), and playing through the file manager works fine.
but under "Play Track" special function it does not see any files at all.
this only happens with one X20S Tx locally, others are OK.
tried 2 SD cards and same result.

![IMG-20211005-WA0028](https://user-images.githubusercontent.com/8968780/136007418-08fd7594-c31b-44bd-8f7f-8a3c62a7e6ef.jpg)
any ideas?
thanks.

**Comment by Hobby4life** [comment]
you must place your own files directly in de /audio folder..

**Comment by i3dm** [comment]
oh right. not under en right?

**Comment by Hobby4life** [comment]
> oh right. not under en right?

no

**Comment by i3dm** [comment]
my mistake. thank you.
