### ISSUE TITLE
Simulator has no screenshot function

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#104]
Does the screenshot work under ETHOS Simulator
with klick on the camera symbol?

**Comment by bsongis-frsky** [comment]
yes

**Comment by hrenz** [comment]
and how?
because the screenshot directory is empty
Or can we use aspecial key at simulator for Screenshot?

**Comment by bsongis-frsky** [comment]
It will paste to the clipboard, far more practical!

**Comment by hrenz** [comment]
ok understand
