### ISSUE TITLE
X20S v1.0.1x Model Sorting issue

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#1042]
Among my models there is 1 model that stil does not want to sort properly.

Glider model "Thermy"
Model36.bin

[models.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7292587/models.zip)

**Comment by Hobby4life** [comment]
[radio.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7308798/radio.zip)

v1.0.11

**Comment by bsongis-frsky** [comment]
There is one space before the model name
