### ISSUE TITLE
Minimum rssi screen widget not correct. 

### ISSUE THREAD

**Issue by ghost** [FrSkyRC/ETHOS-Feedback-Community#1044]
1.0.11 set rssi screen widget to log minimum rssi & it always reads “1” because it starts logging when the radio is turned on & not after it has gained a stable radio connection to a receiver. 

It needs to wait & read “-“ until the radio link has been acquired for the first time, & only then it needs to start recording lowest rssi & not before. 

Otherwise it’s completely useless & you can’t tell how low your rssi went during that flight because of this error. Therefore you can’t debug your rx antenna positioning in the aircraft. 

Please correct.

**Comment by FLYN-001** [comment]
> Same issue than #1061, it will need a fix on TD-ISRM firmware

I’m not sure it is the same. The regular rssi display widget works perfectly & reads correct rssi during the flight & I have not ever observed a “receiver still connected” message when there was no rx present. 

I’m talking about the recorded minimum rssi for the flight widget, & not the current rssi readout.
