### ISSUE TITLE
RF Info correct ?

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#1057]
<img width="350" alt="Schermafbeelding 2021-10-09 om 19 08 48" src="https://user-images.githubusercontent.com/697422/136668029-9856af62-1e86-4e99-a6ae-c0ed00d670f8.png">

With only EU firmware installed, why does the internal module info show FLEX-915M ?

Also there's not enough space to show the info as it is truncated at the front.

**Comment by jbesse262** [comment]
Same here. 2.1.14 FCC displays 2.1.14 EU. Receivers are still bound and seem to be working fine.

**Comment by Tonio62** [comment]
Same for me.
X20 with last EU firmware and last internal module firmware

**Comment by jbesse262** [comment]
Reverted back to 1.0.11 and now shows correct version. Even power cycled a few times to verify.
