### ISSUE TITLE
Text overlapping in special functions

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#1059]
The text in the special functions overlaps with global functions.

Vers.:1.0.12 rc1
TX:X10S ISRM

![sf3](https://user-images.githubusercontent.com/64803366/136673871-6ddeab1b-0dfb-4b08-8d45-bb5a608f4a77.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/136762144-992808d0-b8b7-481d-a945-f8840a0ce6f0.png)
