### ISSUE TITLE
V1.0.12 Hebrew bugs thread

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1060]
V1.0.12 RC1 is missing the HE (hebrew) voice files.
you can find these files on the Hebrew mods thread here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/849

**Comment by i3dm** [comment]
Screen awakening options are covered by check boxes.
![20211010_184957](https://user-images.githubusercontent.com/8968780/136703402-0666f7fb-26a9-4ebb-99a8-622205872d20.jpg)

**Comment by i3dm** [comment]
Timer screen - all the columns should be crossed - right most should be left most, and vice versa.
![1](https://user-images.githubusercontent.com/8968780/136709382-f70ee16e-517a-4fae-8075-cd171b9c269c.png)

**Comment by i3dm** [comment]
Logic Switch screen text on right side is cut off
![LS](https://user-images.githubusercontent.com/8968780/136710158-427c0edb-1290-4f89-a5ef-22382d287d09.png)

**Comment by i3dm** [comment]
Sticks mode, number should be left of text
now its:
2 מוד סטיקים
should be
מוד סטיקים 2

![sticksmode](https://user-images.githubusercontent.com/8968780/136710214-82f5f3f3-8f1b-4923-b7d3-3920620750a9.PNG)

**Comment by i3dm** [comment]
Missing BIND button in D16 mod
![bind](https://user-images.githubusercontent.com/8968780/136710368-64f6cfd9-99e0-4efa-9844-899506d82902.png)
e

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/136744521-eb97e7b4-ffa6-4b99-8fd8-c6e2fb6e8e4e.png)

**Comment by i3dm** [comment]
> As stated here, the standard now is HE, it was IW some years ago Nobody uses HB AFAIK

ok so use HE. the point was not the name... but the missing voice files?

**Comment by bsongis-frsky** [comment]
is the grammar like english? otherwise I won't add it in this release, it's too much work to implement a new grammar

**Comment by bsongis-frsky** [comment]
Next RC will have a simulator

**Comment by bsongis-frsky** [comment]
> Logic Switch screen text on right side is cut off ![LS](https://user-images.githubusercontent.com/8968780/136710158-427c0edb-1290-4f89-a5ef-22382d287d09.png)
You will adapt your translation

**Comment by i3dm** [comment]
@bsongis-frsky 
BIND button is also missing from:
External module: D16, D8, LR12
Internal module ACCESS 900Mhz
