### ISSUE TITLE
1.0.12 RC1 X20S & RB20 Sensors and configuration widget.....

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#1063]
Strange behavior with RB20 and Ethos in X20S, during discovery of telemetry sensors of rb20 some data is missing:

RBCS and RBS is never discovered....? just like in OpenTx....
It would be nice to know the oveload moment or failsafe of wich RX

also the RB10/RB20 Widget seems to getting no data.... all is grayed out?

May I've been missing something?

![20211010_210226](https://user-images.githubusercontent.com/15903471/136709988-18c5016a-a2db-48fb-be80-4d2787c648d7.jpg)
![20211010_210229](https://user-images.githubusercontent.com/15903471/136709989-4a34bfcc-0a8d-49b9-a8bb-b70be8702fe0.jpg)
![20211010_210323](https://user-images.githubusercontent.com/15903471/136709990-aa88b9a6-b1a8-4673-9355-51692de73b95.jpg)
![20211010_210317](https://user-images.githubusercontent.com/15903471/136709992-f17d2f3b-5152-4c1e-ad3d-a23001e8931d.jpg)
![20211010_210254](https://user-images.githubusercontent.com/15903471/136709993-4622a753-60d3-4742-86e9-4db8eab1c1a3.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/137203093-81ad8081-fcde-4da7-bcab-e1adf7c89b31.png)

**Comment by bsongis** [comment]
Today Ethos can support 100 sensors. If you need more just tell me, it's more a protection than a limit, the Model Data has a static limit in OpenTX, while it's dynamic in Ethos (you can have as many timers / mixes / logic switches / functions / sensors as you want)
