### ISSUE TITLE
V1.0.12 TD-ISRM region read wrong

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1064]
X20
V1.0.12 RC1
TD-ISRM suddenly shows as "EU-LBT" instead of "FCC" which is is what it really is (FCC).
pics attached on 1.0.11 and then on 1.0.12RC1 of the same Tx
![20211010_222854](https://user-images.githubusercontent.com/8968780/136710677-47b50ea7-361f-4487-a854-3ce6d76b2285.jpg)
.
![20211010_223118](https://user-images.githubusercontent.com/8968780/136710680-8a283db1-3566-47b1-8d10-eab8ab5df4ca.jpg)

**Comment by i3dm** [comment]
Seems like a bug in internal module enumerator

**Comment by mgsanna** [comment]
Also mine instead of EU-LBT, I get KCC (Korean Firmware)....
![20211010_221107](https://user-images.githubusercontent.com/15903471/136711714-4398455f-a4ba-49ee-be74-bd4695a9f6cc.jpg)
.

**Comment by WismyYao** [comment]
the same as #1057
