### ISSUE TITLE
Clone overwrites previous clone

### ISSUE THREAD

**Issue by johnjoeallen** [FrSkyRC/ETHOS-Feedback-Community#1066]
I renamed a model file "APEdgeGas.bin", then I cloned it, it got a file "APEdgeGas01.bin", I used this model and changed the model image, setup the control surfaces etc....

Then I cloned the "APEdgeGas.bin" again to start on my Extra and it overwrote the "APEdgeGas01.bin"

**Comment by bsongis-frsky** [comment]
1.0.12RC3
