### ISSUE TITLE
functions,télémétrie,logs...

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#107]
- [X] it is not possible to play a file from a stick or slide ..... example ... L1 .... A <x .... gas ... 98% L2. ... A> X .... GAS ... 95%
- [x] Logic Switch: telemetry ..... a> x .... alti .... not possible to go over 100m ????
- [X] write logs .... where to find ..... record logs - alti, rssi, positions, in short all the sensors available ???
           => LOGS ARE WRITTEN IN THE LOGS DIRECTORY ON SD, YOU CAN CONFIGURE WHICH SENSOR IS LOGGED IN SENSOR  
                 SETTINGS
- [X] mathematical functions (is not true (!) Flank ....not found
           => MY FRENCH IS NOT GOOD ENOUGH TO UNDERSTAND WHAT YOU ARE SAYING
- [X] the throttle cut does not work correctly ..... restarting the engine. !!!!
           => DUPLICATE ISSUE, ALREADY FIXED FOR 1.0.3

Global functions, not sure they are really needed

**Comment by aeroplanebelg** [comment]
# 107.....Désolé....point 1) ......résolu
                                     3).......résolu

**Comment by aeroplanebelg** [comment]
thank you for your responces.
1)after loading os 1.0.2 on my x12s, i find that i still cannot program a logic inter as follows .... L01..A> x .... alt ... 250m. (in ethos max limit= 100m) 
2)yes for the mathematical functions it is necessary to look at the table of the true  (example..or and xor .... there is also the function flanc, bistable and  (!) ... if  ! L03 is not true) see in open tx.
With these functions, it is possible to program the chronos for example ... with gliders equipped with a motor need two chronos one for the engine duration and the other which starts when the chonos engine s 'stopped for the plane.
With open tx and the mathematical functions this is possible. For my part I not arrived with ethos!
it is possible?
Thank you very much for your work, I have been using open tx since 2014 and I really like ethos. thank you.

**Comment by bsongis-frsky** [comment]
Please try with 1.0.3

**Comment by aeroplanebelg** [comment]
Thank you for your reply, I switched to os 1.0.3
alti ok .., I don't know how to program the lap times as I would like. I do not understand why these times are not automatically included in ethos because all over the world, ALL gliders who use an engine use this (one stopwatch for the engine and one for the schedule) it is the minimum of the minimum! (programmable to their ideas) it's even better.

if you have the opportunity could you please look at my post # 120 on the logs. thanks in advance
