### ISSUE TITLE
Dutch (NL) translation v1.0.12 RC2

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#1073]
I have made the translation to Dutch.

I will create the soundpack files later on.

[nl.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7336600/nl.txt)

**Comment by bsongis-frsky** [comment]
as you wish, please test it with an available language of your choice on the radio, I won't have time to add a new grammar for Dutch!

**Comment by bsongis-frsky** [comment]
either a CSV file if you want the files are TTS generated, or audio files
