### ISSUE TITLE
MAC 

### ISSUE THREAD

**Issue by andrescuadrosjdc** [FrSkyRC/ETHOS-Feedback-Community#1078]
When I try to disconnect my Radio (in bootloader mode) from my MAC, try to close the 2 windows, they appear again, and again, and again, so when disconnect they appear the disc ejected incorrectly message:
Could be that a problem?

**Comment by pld74** [comment]
BTW this also happens randomly on Windows PC running Windows 10

**Comment by m0p3d** [comment]
Can you please rename the SDCards to individual names lets say SDCard and Flash ...
Would maybe solve another mac problem caused by  two drives having same name.
