### ISSUE TITLE
Scrolling problem with Ethos 1.0.12 rc2

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#1081]
With my X20, in a butterfly mix for example, or thermik mode I can't go all the way to the bottom of the mix with the dial.  It works in touch.

https://user-images.githubusercontent.com/89158034/137345311-fbe668ec-6947-4e94-ad2c-fb0c7f073a93.mp4

**Comment by bsongis-frsky** [comment]
It's strange, the same scrolling works on other screens like ailerons!
