### ISSUE TITLE
Request : annoucing the telemetry sensor values 

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#1085]
I would be interested if Ethos could announce loud the values it gets from the telemetry: altitude, Rx batt, ... Like in OTX, the telemtry sensors would appear in the list of devices the values of which  could be announced.
Thanks a lot, Ethos is great, mainly with a very fast SDCard !

**Comment by Tonio62** [comment]
Is here.... Go to special functions

**Comment by Billy60** [comment]
Sorry, nothing there ... I mean any sensors which are **not** Frsky's: that is OpenXsensors (used on OTX firmwares). I have five of them and they do not appear in the list of files values to be read. They do appear in the telemtry screens but cannot be announced. Since Bertrand Songis has created OTX he should know how to implement this. They are connected via the Sport of the Rx's.

**Comment by Billy60** [comment]
For instance, if I use a altimeter from OpenXsensor via the telemetry through the Sport, I get the altitude value available on the main screen I choose, ok.
If I want it to be read loud, I cannot find it on the list of values that can be read.
In OTX this appears as 'TelemAlt' in the said list.
So, yes, I cannot find them as a select possibility in the PlayValue list.

**Comment by bsongis-frsky** [comment]
Which sensors are displayed when you choose the Telemetry category? It should be there...

**Comment by bsongis-frsky** [comment]
No, it's a non sense to play Altitude. 
And Batt as well. Completely unuseful
We will remove Vario also in next release

**Comment by bsongis-frsky** [comment]
@Billy60 of course I was not serious. I think we are all confused by your request which is already implemented from Day-1 in Ethos... unless we understand nothing. If you are french, perhaps you could help by writing in french, I will understand better ;)

**Comment by bsongis-frsky** [comment]
:)
