### ISSUE TITLE
Manual RX selection with Range Check

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1090]
Hello Bertrand,

Can't find if this improvment has been requested !

With the Range Check RX option rx, with multiple RX installed, could it be possible to select manually which RX need
to be used for the range test instead of deconnecting physically the RX to change RX test ?

Tks

**Comment by jbesse262** [comment]
If you have them bound as RX1, RX2 etc. Then you can do separate range checks on each reciever. If they are s-busssed together, I dont see how thats possible.

**Comment by bsongis-frsky** [comment]
RANGE CHECK is sent with the channels, it's the same for all RX
