### ISSUE TITLE
Uneven servo travel using R9SX

### ISSUE THREAD

**Issue by Flygrc** [FrSkyRC/ETHOS-Feedback-Community#1091]
When using Access 2.1.14 and 1.0.11 or 1.0.12 rc3 EU or Flex 868 in X20S and 1.3.1or 1.3.3 in R9SX got uneven servotravel with frezze. It show up when Info side is open, when I closed that side it was even agin. (Has be seen erlier but cant reproduce that) Tested with direct battery connectet, two diffrent reciver and diffrent servo and still the same. Had also tested to connect with S bus a R8Pro on same channel, R8Pro gave even travel at same time R9SX was uneven.

https://youtu.be/_aUQcrjRX2I

**Comment by mawzthefinn** [comment]
There appears to be some oddities on the receiver side when they are being polled for firmware version info, which the Info screen does.

You can see this with the RSSI from the receiver, it will be unstable while Info is open. It's not a ETHOS issue though, so I will close off this Issue.
