### ISSUE TITLE
Doubled sensor using RB-30 and dual frequencies 2.4 GHz - 900 MHz (1.0.12 RC3)

### ISSUE THREAD

**Issue by federicobelfi** [FrSkyRC/ETHOS-Feedback-Community#1092]
I'm currentlly using an RB-30 coupled with an R8 PRO and an R9 Slim+.

The telemetry appear doubled, all the sensors are discovered twice. Each name of the doubled contain 900 at the end.

Usually th R8 is the first to connect and the telemetry is ok. If for some reason the trasmition is switched to the 900 the telemetry is trasmitted trough the R9 and al the value on my screens become red. As double check lookling in the telemetry page i can see the first set of data red (usually trasmitted trough R8 PRO), and the second set coming from the R9 black and updating.

Is it possible to let the Radio join these values eliminating the doubled names?

**Comment by i3dm** [comment]
great idea

**Comment by federicobelfi** [comment]
Any prevision on what version will be have this enhancement as milestone?

**Comment by bsongis-frsky** [comment]
1) I will remove the extension EXT / INT / 2.4G / 900M from the sensors, except from RSSI
2) All sensors, except RSSI will be merged. It means that all your sensors must have a different AppID and different PhysID, even when linked to 2 different receivers / modules (or they will be merged, which is exactly what you need here)

**Comment by federicobelfi** [comment]
Great, when you want i can test the beta.

**Comment by i3dm** [comment]
> 1. I will remove the extension EXT / INT / 2.4G / 900M from the sensors, except from RSSI
> 2. All sensors, except RSSI will be merged. It means that all your sensors must have a different AppID and different PhysID, even when linked to 2 different receivers / modules (or they will be merged, which is exactly what you need here)

you may want to leave any Rx specific sensors seperated:
RSSI
VFR
RxBt
and so on

makes no sense to merge VFR and not merge RSSI. these should be separated as they give you the link quality pre RF channel.

**Comment by Hobby4life** [comment]
@bsongis-frsky what do you exactly mean by "merged"?

For my understanding. 2 same sensors on 2 receivers. Will be combined as 1 sensor.
