### ISSUE TITLE
RB-30 Status value using only 2 radios (1.0.12 RC3)

### ISSUE THREAD

**Issue by federicobelfi** [FrSkyRC/ETHOS-Feedback-Community#1093]
I'm currentlly using an RB-30 coupled with an R8 PRO and an R9 Slim+.

Looking at the RB status value I expect to see "OK" in nominal condition, using only two radios the system report an anomaly (the third radio disconnected).

Can this be fixed on EthOS or the RB-30 NEED 3 receivers to work nominal?

**Comment by SmartTommy** [comment]
Set the Rx3 IN/SBUS OUT to SBUS out Mode , the Rx3 IN will output sbus, and then report normal.
