### ISSUE TITLE
X20s EU 1.0.12-RC4 random but persistent Emergency Mode

### ISSUE THREAD

**Issue by federicobelfi** [FrSkyRC/ETHOS-Feedback-Community#1099]
Using **X20S EU 1.0.12-RC4 + RB-30 (last firmware) + GAS Suite + R8 PRO (last firmware) + R9 Slim (last firmware)** continuosly getting **Emergency Mode**. Up now I have used 1.0.11 without any problem. Due to the ability to change the VBOX1 value greater than 10V I have switched to 1.0.12-RC2, RC3 and now RC4. From the switch I have experinced several EM waiting for the official release.

Is difficult to have more than 15 minutes without EM. Is not possible to reproduce the exact condition but the EM occurs without to much effort in 10-15 minutes of model setting. When the EM occurs some times the radios led, that usually is green, slighty blink of red. Never tried in flight but I can confirm that all the control surface work properly and also the stabilization function of RB-30 stay on.

I really don't have any hipotesys on the root cause. Can I send to you some usefull file for debugging?

Please find attached the model.
[model05.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7368654/model05.zip)

**Comment by bsongis-frsky** [comment]
The setup is complex, it would help to remove some elements from the equation, i.e. the RB-30 or GAS Suite?
This one is critical, it prevents us from releasing 1.0.12 final :(

**Comment by bsongis-frsky** [comment]
I have replicated it. It has to see with RB-30 new status sensor
