### ISSUE TITLE
Can't make a new model on X10S with ISRM Module

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#11]
ethos  0.0.1.16 on X10S with ISRM Module

It is as simple as I said in the title. I can't make a new model.

Setting up the first model Ethos frose when selecting aircraft type. There is no wisard to select wingtype,....

After doIng this I need to restart the transmitter. When restartiing booth screen freezes and next message is No SD card ( sdcard is present) 

I did the firmware istallation trough Compannion.
Sdcard wassen't formatted before new content.

**Comment by 00steven** [comment]
formatted sd card . sdcard files placed on card 
On startup error message : Error opening file Starting model wizard ... 

Model wizard doesen"t work. I can change model type. But I cant select it .

**Comment by bsongis-frsky** [comment]
"Page down" to go to the next page seems right to me, any other idea?
