### ISSUE TITLE
mixer Var need weight and offset or a curve

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#110]
mixer var need weigth and offset or a curve to use settign of a Poti to a free range

example
Poti setting from -100% / +100% to Range 0% to +100% 
need weigth 50% and offset 50% or selecting a curve

**Comment by centertrim** [comment]
When I add a "Free Mix" type mixer rule in Ethos I am able to adjust the weight and offset without any problem.  I can also assign a curve.

Are you trying to do this with one of the default Elevator/Aileron/Rudder/Throttle mixers?  If you edit one of those mixer types (or clone them) they will not have all of the options available with a Free Mix rule.

**Comment by hrenz** [comment]
I know  what a free mixer is, 
but at Var mixer I can select a Poti, and then I have to set the Potirange

MIN, MAX are fix Values and not variable Values
there weight is ok

**Comment by centertrim** [comment]
Discussion here:   https://www.rcgroups.com/forums/showthread.php?3703807-New-%C2%96-FrSky-X20-Tandem-and-ETHOS/page350#post46925897

**Comment by hrenz** [comment]
analog inputs are Possible
![grafik](https://user-images.githubusercontent.com/6217896/115914562-6739cb80-a472-11eb-9d08-4f09c5b3382f.png)

**Comment by centertrim** [comment]
What version of Ethos are you running?  My X20 with v1.0.2 does not have the functionality to select various inputs like yours does.

![Uploading DD9E619F-6276-4A09-8297-E7559AA5FED9.jpeg…]()

**Comment by centertrim** [comment]
Nevermind - I found it.  It is not intuitive to me, but if you hold down the enter button it pops up the source selection menu.  There does not seem to be a way to access the source selection from the touch interface.  

So yes, I agree with your assertion that the ability to manipulate the VAR input with weight and offset should be added.  It would be useful to prevent having to add additional mixer rules to perform this manipulation.

**Comment by hrenz** [comment]
Yes this is notr ok
you should see that there are more optinons, with a Symbol

there are a lot of other long press options  at other mixers too

**Comment by Nicholas-Luoyi** [comment]
Yes. It's quite hard to find the long press options. Good catch.
But for Var Mix. The source is not playing the role of input. It's just let the user could adjust the param with a source. So it won't be applied to any calculations.

**Comment by hrenz** [comment]
Yes but to adjust the parameter  to a free range you need weight AND Offset or a curve
Example: Poti P1 has a Range of -100% to +100%
with weight 50% and offset 50% you have canged the Range to 0% to 100%
or with a 2 point curve -100%/0%  +100%/100% same result.

Basic:ly to set an analogvalue to a free range you need allways both, weiht AND Offset or a Curve for precalculation

**Comment by bsongis-frsky** [comment]
VARS will be implemented soon
