### ISSUE TITLE
Battery Main Voltage [Confusing]

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#1101]
There is no indication that Battery Main Voltage is not just an readout - You can adjust / manipulate it.
Correct way to use it is to calibrate voltage reading of the radio vs voltage reading of (calibrated) multimeter- to improve accuracy.

I would suggest to rename it to something else which indicates this is adjustable and how much adjustment is already done
Battery Main Voltage Reading: [ResultValue] , Offset/Correction: [Value e.g.-0.3V]
Maybe colorise ? high correction values yellow/red?

Not sure if andybody else noticed - but very critical point which can result into radio turns of while flying.
Maybe double confirm via popup any adjustment or display warning

**Comment by czech66** [comment]
When the logic switch is set to low on-board voltage without using BEC. After creating a special undervoltage reporting function, the message is played back cyclically.
When the limit value is reached. There is no hysteresis.
This message does not affect the set speaking time.

**Comment by mawzthefinn** [comment]
The value box itself denotes that it is editable. Values in boxes are editable, non-editable values are displayed on the background colour. Compare the RTC voltage readout to the Main Voltage display.
