### ISSUE TITLE
Local language - EthOS

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1103]
I am translating EthOS system menues to Norwegian, but sometimes struggle with where the different menu-items (words) are located in the menu-system on the radio. Just so the translation (the menues) is informative and not just a direct translation of the individual word. 
Like now, on 1.0.12rc5, I find the word "Pattern" is added, but I don't know to wich menu-item it belongs...
I can ofcourse translate it, but I don't know if it gives a sense of contense for the user.
Would it be possible to add comments to the items in the language file?
Example: this word is at... Model/Trims or Model/Special Funcs or System/Alerts or System/Battery screen.
Then it would be much easier/faster to check the correct wording for the menues  :-)

**Comment by EngelMT** [comment]
That´s a real problem. I have had it too with German translation. But now I have fixed the most Terms to meaningful terms.

It was much easier to do for FROS in the past. For FROS we had a list with the terms and where this terms are used.

But I think it's too late to create such a list. I asked some people in our forum to test with me and post illogical terms.
