### ISSUE TITLE
1.0.12 RC5 Fade In switch Out

### ISSUE THREAD

**Issue by theoml** [FrSkyRC/ETHOS-Feedback-Community#1104]
Hi,

since 1.0.12RC 1 I try to use the Fade In/out. I´ve set both to 3 sec in every Phase and I see fading in and switching out by changing the Phases
Now in RC5 is the same.

I try to program a 4 Flaps Glider, Normal, Speed, Thermal. In the Mixes I select the Phase I want to use it and I hope to get a smoth moving f.E. from Thermal to Speed but it jumps to 0 and then it moves into the selcted Phase.

Whats wrong here ?

Reiner

**Comment by theoml** [comment]
1.1.0A4
Still the same

**Comment by mawzthefinn** [comment]
Are you still having this issue on current firmware?

**Comment by theoml** [comment]
Yes

**Comment by mawzthefinn** [comment]
OK, just doing a dive through the posted model.

Your core issue is the use of Logic Switches as Sources. Use Special->Maximum instead and the fading will work correctly for your 3 flight mode switches. What is happening is the deactivation of the source as you exit the FM is causing the reset to a '0' input before the FM exits, resulting in the reset of the control position before the fade in/out is processed

The Butterfly mix is active on switch position not Flight Mode and therefore won't fade.

**Comment by mawzthefinn** [comment]
Closing as answer provided
