### ISSUE TITLE
Updated Norwegian Translation 1.0.12rc5

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1105]
Updated Norwegian translation
[no.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7395785/no.txt)
.

**Comment by bsongis-frsky** [comment]
Would you please update to latest 1.1.0 files? There is too much merge which is difficult for me as I don't speak Norwegian

**Comment by mmasch** [comment]
Hello Bertrand. 

I have updated the No language file for 1.1.0 alpha9. I’ll upload it on GitHub as before. 
There are few words I would like to clarify: 

First is the word «PATTERN» right before the end of the translation file. 
Where/what is it linked to. There is a few word I can translate with, but with different meanings  ;-)

Also the word «AVERAGE» (Telemetry - RPM / Telemetry - Tubine RPM). 
What is the usage? Value is 1-5 samples.

B.r. Morten Masch, Norway.

**Comment by Hobby4life** [comment]
PATTERN is used for haptic patterns

**Comment by mmasch** [comment]
Thank’s Hobby4Life for the Haptic Pattern answer. 
The last thing I need an answer on to complete the alpha9 translation is the word «AVERAGE» (Telemetry - RPM / Telemetry - Tubine RPM). 
What is the usage? Value is 1-5 samples.

Best regards Morten Masch, Norway.
