### ISSUE TITLE
Valeur Debattement Mixage Libre

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1109]
![image](https://user-images.githubusercontent.com/27886942/138569625-3c2368fb-ad38-4773-ba47-9f2d39b54c26.png)

Bonsoir Bertrand,

With the Free Mixer, the min rate is 100% but the graphic shows -100%. The min rate should be -100% I think

@+

**Comment by bsongis-frsky** [comment]
@loetefix is right

1) in test mix, it's an absolute position : -100% to +100%
2) in free mix, it's a weight : 100% applied to -100% to 100% applied to +100% will give an absolute range of -100% to +100%
