### ISSUE TITLE
Implementing a servo balancer in Ethos

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#1115]
Hello

Would it be possible to implement a servo balancer in Ethos? Kind of like Jeti or Spektrum. For example, if you have 2 servos for a hinge surface this would make servo adjustment a lot easier.

Thank you and best regards

Enzo

**Comment by mawzthefinn** [comment]
This is a duplicate of #38, closing in favour of that Issue
