### ISSUE TITLE
Enhancement: Screenshot function

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#1116]
I use screenshot a lot.

Therefore I need te setup a screenshot function for every model.
Also it uses a condition to activate it, mostly coming from a switch.
Personally I dont want to use control inputs for these kind of operations.
This because I see Screenshot as a system related function rather then a model related function.

But if we can make the screenshot function as a system function instead of only Glovbal Special Function.

**Screenshot taken with longpress home system key**
Simply assign a homekey button in the system HARDWARE>Home Keymap

I have added a camera shutter sound when taking a screenshot.
This sound can also be implemented as a system sound.

Just an idea :-)

[shutter.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7409000/shutter.zip)

**Comment by mawzthefinn** [comment]
This would be really nice.

**Comment by mawzthefinn** [comment]
Unstale
