### ISSUE TITLE
Independent trims

### ISSUE THREAD

**Issue by jeffgrain** [FrSkyRC/ETHOS-Feedback-Community#1119]
Is it possible to use the " custom " aka " FS " switches as independent trims.. the X12S has the two extra trims that I use to balance my twin engine models. On my X20S I could do this using the sub trim.. but prefer to use and leave that for servo centering..  I could assign and use the sliders or pots.. but they could be moved or disturbed by other actions.. 

Request :   the master throttle trim with user configured sub trims outside of using the sub trim in the outputs screen..  screen shot from OpenTx of my twin engine trim setup..

![trim](https://user-images.githubusercontent.com/59795621/138785971-f8d547a9-b127-4e6b-ad63-127c0e17461a.JPG)

**Comment by mawzthefinn** [comment]
You could use a Trim Mixer to do this. 

In Edit Model, set Function switches to Momentary

Now create a Trim Mix, set Up as FSW1 by pressing FSW1
Set Down as FSW3 by pressing FSW3
Set the output channel as your desired channel to trim.

You can duplicate for the other engine by doing the same thing using FSW4 and FSW6 on a second trim mix.

The only trim function you miss here is per-Flight Mode values.

**Comment by jeffgrain** [comment]
thanks.. but I found that about a month ago while setting up another twin.. i am sure that option was not there back when I posted the original message

thanks

**Comment by mawzthefinn** [comment]
yes, I believe the functionality was added after your post, but the issue never got updated.

I’m closing this issue off as resolved.
