### ISSUE TITLE
Mixer "Weight" source selection possibility is not obvious in Ethos interface

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#112]
V1.0.3:

It is not obvious in the Ethos touch interface that there is a hidden source selection in the “Weight” field of the Mixer rules.  The “Weight” field is shown with only the single value, and no amount of tapping on it will bring up the source selection menu.  The only way to access that additional menu is by long pressing the enter button, and it is not obvious to the user that they should do that on that field.  In fact, long pressing the enter button on other value fields simply changes to the Outputs screen.  So the use of a long press on the enter button to access this menu is an odd design choice from the user's perspective.

This is the field being discussed:
![8E735758-5C0A-4F5F-B535-A2DE06F568F5](https://user-images.githubusercontent.com/81865495/115932271-38abf880-a452-11eb-8490-0831439caad0.jpeg)

This is it being selected in the touch interface:
![8193FF9A-C5C4-43A3-863D-B7A8234B7AC0](https://user-images.githubusercontent.com/81865495/115932303-4ceff580-a452-11eb-9d16-82d929411acc.jpeg)

There is no indication to the user that they should long press the enter button to access this menu.  There should be a symbol of some kind showing that it is possible to change to a source instead of a single weight.  Additionally, it should be possible to access this menu directly from the touch interface (but it is currently not).
![3026257F-FF8E-4885-9C12-3C36ECAD3923](https://user-images.githubusercontent.com/81865495/115932344-5ed19880-a452-11eb-8ea2-b6bc5c49e309.jpeg)

It is currently not intuitive to a new user that it is even possible to end up here in the interface view after creating a new mix (free mixes, Var mixes, etc):  ![194D801A-C162-4D4A-AACC-BD4C18B65CD4](https://user-images.githubusercontent.com/81865495/115932477-a6f0bb00-a452-11eb-9680-5d7c31687a4b.jpeg)

Recommended solution:  Add indication that a source selection screen is available, and add the ability to reach the selection menu directly from the touch interface.

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.10
