### ISSUE TITLE
Is it possible to trigger screens/functions from switches or pots

### ISSUE THREAD

**Issue by hancop** [FrSkyRC/ETHOS-Feedback-Community#1120]
Would like to be able for instance to bring the range check screen up directly from a pot.

thanks

**Comment by mawzthefinn** [comment]
Maybe a Quick Menu? As a Homekey option, can provide a menu that the user can populate with certain commonly used functions like Range Check.

I use a similar feature on my cameras to access useful options like card format that are too dangerous to activate in under 2 separate actions.
