### ISSUE TITLE
Preflight check-enhancement

### ISSUE THREAD

**Issue by hancop** [FrSkyRC/ETHOS-Feedback-Community#1121]
Would it be possible to add plane related checks or custom user checks that you can check off before allowing flight. Spektrum has some that asks about insuring the wing bolts are installed and another that aileron servos are plugged in. This would be very useful checks as people do forget these things.

thanks

**Comment by mawzthefinn** [comment]
#755 would address this. Designating as duplicate, please continue discussion under #755
