### ISSUE TITLE
screen sleep brightness setting

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1123]
i would like to be able to set the screen sleep brightness. on telemetry radios it does make sense not to shut off the screen completely during sleep in flight.

currently the only option is to keep it fuly awake with sticks = higher current draw.

thanks.

**Comment by bsongis-frsky** [comment]
Instead of "Shutdown LCD during sleep"

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/147468778-f7fb7f6a-0e7b-4a01-928b-1558c1935409.png)
