### ISSUE TITLE
Model file fails to open

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1126]
I am on v1.1.0-alpha 2, but this also happened with 1.0.14 (release) as well. I can select this model file and play with it, but if you restart it will not open and goes to the model wizard.
[esp-ethos_101.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7590595/esp-ethos_101.zip)

**Comment by EngelMT** [comment]
Did you previously install alpha 1 and also edit, clone etc. the model there? Then your model files are probably damaged and you have to use the data backup.

I have an X20 for testing and also had alpha 1 installed there. Then I tried a few things and also cloned models. This X20 also has problems with the alpha 2 with a few model memories.

Yesterday I also flashed my own X20S with alpha 2. There, everything works as it should.

So you have to assume that the alpha 1 has corrupted the data.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/143233038-8dbbd4ea-df02-4d80-8865-39a7ecb32d4f.png)

**Comment by bsongis-frsky** [comment]
@guycnicholas nice catch, I cannot reopen it once converted

**Comment by bsongis-frsky** [comment]
No. The bug is not there. Your model filename is too long (15 chars max). It should not be possible to load it.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/143234493-9eb5fed5-297c-417f-b230-0f4d84b9c515.png)

**Comment by guycnicholas** [comment]
Interesting, I tried this with both 1.0.14 and 1.1.0 and I never saw that dialog.

**Comment by bsongis-frsky** [comment]
I just added it, to avoid that the error is impossible to understand!
