### ISSUE TITLE
Please add Reload LUA in Simulator. 

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1127]
With a reload LUA button in the simulator it is better to test changes in a LUA script without restarting the Simulator everytime.

**Comment by i3dm** [comment]
@loetefix 
did you manage to load LUA in the X20 sim at all?
i cant seem to see any LUA widgets in my X20 sim V1.1.0a2.
any luck?

**Comment by Hobby4life** [comment]
start simulator with administrator mode

**Comment by i3dm** [comment]
> start simulator with administrator mode

please explain,
and where do you put the scripts folder to read it in the sim?

**Comment by Hobby4life** [comment]
> > start simulator with administrator mode
> 
> please explain, and where do you put the scripts folder to read it in the sim?

Scripts go here:
![image](https://user-images.githubusercontent.com/55426642/143256129-af64e73a-1a50-4dca-9669-b4ec4a4a83d6.png)

If no scripts are visible..
Right click the Ethos 1.1.0-alpha2 icon and **run as administrator**

**Comment by i3dm** [comment]
thank you.

@Hobby4life  do you know how to read trim position and telemetry values to my widget?

**Comment by Hobby4life** [comment]
You need to 

> 

Not sure if this already possible, features are added almost every day now.

But for telemetry if you can select it as a source then you can work with that source in lua.
![image](https://user-images.githubusercontent.com/55426642/143257566-5e8869e7-6f2d-4877-9d9b-b03feec1dd97.png)

**Comment by i3dm** [comment]
Not sure regarding telemetry (or trim) as a source.

**Comment by bsongis-frsky** [comment]
```
source = system.getSource("RSSI")
print(source.value())
```

**Comment by i3dm** [comment]
> ```lua
> source = system.getSource("RSSI")
> print(source.value())
> ```


so like so?
lcd.drawNumber(487,21,RSSI.value())

**Comment by loetefix** [comment]
ok and what about my question????
is it possible to reload a lua script without restarting the Simulator????

**Comment by i3dm** [comment]
> ```lua
> source = system.getSource("RSSI")
> print(source.value())
> ```

i tried:

	local Rssi = system.getSource("RSSI")
	lcd.drawNumber(487,21,Rssi.value())

it does not print any value at all.

**Comment by agibson2** [comment]
It is pretty quick to restart the simulator for me and get back to the LUA screen I was on.  About 5 seconds.  I spend much more time coding the scripts :).

**Comment by loetefix** [comment]
true, why easy when it can be complicated.

**Comment by Hobby4life** [comment]
Maybe just a reset button in the left top corner will do fine..
