### ISSUE TITLE
Logic switch text overlap

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1128]
The text in the Logical switch area can become overlapped if items are too long.

![PXL_20211123_194220501](https://user-images.githubusercontent.com/5494702/143092981-80e01ee7-26c4-4e0c-bd2a-d66a487c7dbc.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/147947546-e06a6a7c-9c66-4fa9-b129-6470488c0aaa.png)
