### ISSUE TITLE
Trims change with dual rates and Cannot disable trims on default control mixers

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#113]
First, the default Aileron / Elevator / Rudder / Throttle mixers have no option to disable trims.  The options available in these mixers (multiple weights/expos & differential) are not available in free mixes, so the use of these mixers is necessary for a clean configuration.

Second, trims are applied before Weight, so changing the Weight with a switch (like Dual Rate functionality for high/med/low rates) causes the trim position for that control surface to change.  This is the opposite of how a trim should work.  I realize that this is how the order of operations is performed for OpenTX mixers, but that works in OpenTX because most people use Inputs to adjust their rates (weights) and expo before the input ever arrives at the mixer rules.  Ethos has done away with Inputs and relies on specialized mixer rules for ail/ele/rud/thr, but now the application of Trim before weight makes no sense.  The servo position should not change with the stick centered if only the weight is changed.  As it is now the weight is applied to the Trim, so the servo moves.

Suggested solutions:
* Apply trims AFTER weights/curves/etc.
* Allow disabling of trims so that they can be added in a separate free mix for those channels.

**Comment by profilebroken** [comment]
Confirmed as described.  I hope this gets fixed pronto.

**Comment by centertrim** [comment]
Agreed.  I definitely won't put any of my larger 3D models in the air with the trims changing like this.  And any workarounds I have found like adding flight modes for the rates and using independent trims for each rate are too annoying to bother with in the air on expensive models like this.  Might as well just fly those models on my OpenTX radio until a fix is implemented for this issue.
