### ISSUE TITLE
lua: drawLine with clipping

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1131]
draws a line within fixed boundaries

lcd.drawLineWithClipping(x,y, minX,minY,maxX,maxY)

**Comment by bsongis-frsky** [comment]
But then you will ask for lcd.drawCircleWithClipping(...) etc.
Why not lcd.setClippingRect(...) then drawLine(...) then lcd.resetClippingRect(...)

**Comment by yaapu** [comment]
Love It!
Would it clip anything? Text as well?

**Comment by bsongis-frsky** [comment]
Why not :)

**Comment by yaapu** [comment]
great, that would allow scrolling text in confined rectangles :-)

**Comment by bsongis-frsky** [comment]
Sinus with clipping

![image](https://user-images.githubusercontent.com/50834778/145434904-aa250951-838b-46c0-8498-a8ace1e822bf.png)

![image](https://user-images.githubusercontent.com/50834778/145434964-4112587d-38bf-4a6d-82bf-9cdd0b54ea2d.png)

**Comment by bsongis-frsky** [comment]
Note:
`lcd.setClipping(nil)` will reset the clipping
