### ISSUE TITLE
lua: form.addListField

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1132]
adds a field of type drop down with multiple items and a single selection.
User should be able to specify a list of (value,label) pairs, label is only shown while value is passed to the widget

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/143455922-a0f0e7eb-c4da-4c6d-9294-6600225eba9a.png)

**Comment by bsongis-frsky** [comment]
```lua
-- Choice
line = form.addLine("Choice example")
local field = form.addChoiceField(line, form.getFieldSlots(line)[0], {{"Entry with value 3", 3}, {"Entry with value 1", 1}}, function() return widget.choice end, function(value) widget.choice = value end)
field:enable(false)
```
![image](https://user-images.githubusercontent.com/50834778/143457195-cc583992-b022-49c8-b5c6-4808a6373d09.png)

**Comment by yaapu** [comment]
@bsongis-frsky lovely
