### ISSUE TITLE
lua: form.addDecimalNumberField

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1133]
allow adding a decimal number as a widget parameter with extra parameters for increment and precision

form.addDecimalNumberField(
line	(FormLine): the line where the field should be added
rect	(Rect): the coordinates
min	(float): the min value
max	(float): the max value
increment(float): increment
precision(integer): number of decimals
getValue	(function): the function which will return the current value
setValue	(function): the function which will be called on value change
)

**Comment by bsongis-frsky** [comment]
I think I will implement it this way:

```lua
field = form.addNumberField(line, rect, min, max, getValue, setValue);
field.step(...)
field.precision(...) -- or field.decimals(...)
```

**Comment by yaapu** [comment]
yeah, that will work too, it's a one time setup function after all

field.step () will accept both integer and floats?

**Comment by bsongis-frsky** [comment]
it will accept number, yes

**Comment by bsongis-frsky** [comment]
someone else asks for

```lua
field.enable(false)
```

**Comment by yaapu** [comment]
@bsongis-frsky question: will multiple instances of the same widget be able to save a private config or config is shared?
I verified that lua context is shared among widgets so it's easy to pass stuff around but could not test multiple instances conf save

**Comment by yaapu** [comment]
> someone else asks for
> 
> ```lua
> field.enable(false)
> ```

that would help too, can't think of a use case, but I bet I'll find one :-)

**Comment by bsongis-frsky** [comment]
> @bsongis-frsky question: will multiple instances of the same widget be able to save a private config or config is shared? I verified that lua context is shared among widgets so it's easy to pass stuff around but could not test multiple instances conf save

@yaapu I think it will be possible out of the box, no? if you encounter an issue, please tell me

**Comment by bsongis-frsky** [comment]
field:enable(false) is working!
![image](https://user-images.githubusercontent.com/50834778/143423692-0acd862d-0575-4d82-8324-f13b4c36c3fd.png)

![image](https://user-images.githubusercontent.com/50834778/143423637-4fac5579-d693-401a-9e8c-f669db11ca97.png)

**Comment by bsongis-frsky** [comment]
- One disabled NumberEdit
- One NumberEdit with decimals = 1 `field:decimals(1)` and step = 2 `field:step(2)`

![image](https://user-images.githubusercontent.com/50834778/143425773-50a31f2d-0dc3-46e1-a873-e1d26969c383.png)

![image](https://user-images.githubusercontent.com/50834778/143425656-1174cb2d-f286-4164-9462-ffd5dc2f6171.png)

**Comment by bsongis-frsky** [comment]
Will be there in alpha3

**Comment by Hobby4life** [comment]
great work bertrand!, As always ;-)

**Comment by yaapu** [comment]
love it, thanks!
