### ISSUE TITLE
lua: sub second time source, 1/10th or 1/100th of a second

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1134]
os library only has time functions with a 1 sec resolution.
For good bg timing a higher resolution time reference is needed ideally 1/100th of a second

**Comment by bsongis-frsky** [comment]
even `os.clock()` ?

**Comment by yaapu** [comment]
os.clock() is 1 second resolution, at least on the simulator

**Comment by bsongis-frsky** [comment]
In 1.1.0-alpha3 `os.clock()` is the perfect way to test the emergency mode

**Comment by yaapu** [comment]
> In 1.1.0-alpha3 `os.clock()` is the perfect way to test the emergency mode

;-)

**Comment by bsongis-frsky** [comment]
in fact it's print(<float>) which has an issue, not os.clock()
I will track the issue tomorrow and hopefully release alpha4

**Comment by bsongis-frsky** [comment]
Fixed in alpha4
Please use `os.clock()` which will give you 1/100th of a second precision

**Comment by yaapu** [comment]
@bsongis-frsky os.clock() resolution on simulator is different from os.clock() on radio by a factor of 10
