### ISSUE TITLE
lua: widgets on the simulator fail to save settings

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1135]
Lua widgets do not save their state on disk, regular widgets work fine.
Tested with the provided gauge.lua widget

From the debug window I can see a call to 

009074 ModelData::write('/models/model01.bin')
009076 RAM backup written (size=1333)

and on subsequent load a call to

001122 ModelData::read('/models/model01.bin')
001123 RAM backup written (size=1333)

but the lua widget state is reset.

**Comment by bsongis-frsky** [comment]
Yes, already reported. See alpha3 which will be released tonight

**Comment by yaapu** [comment]
opps sorry for double reporting
