### ISSUE TITLE
lua: lcd.drawtext strange behaviour

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1136]
1. text size does not seem to have any effect on actual printed text size,:
for example: lcd.drawText(450,0,"RSSI"  ,**SMLSIZE**)

**Comment by i3dm** [comment]
at this point, if i enlarge the background image by even 1 pixel, it doesn't load at all.

**Comment by Hobby4life** [comment]
Please read the reference manual about fontsize,
A lot is different compared to otx lua.

https://manual.hobby4life.nl/en/ethos-lua

Check: setFont()


`    -- Demo of a text
    lcd.setFont(ITALIC)
    lcd.setColor(255,0,255)
    lcd.drawText(15, 10, "FONT")`

**Comment by i3dm** [comment]
where was this manual posted?

**Comment by i3dm** [comment]
thanks, got it to work.
