### ISSUE TITLE
lua: support for require removed from 1.1.0 alpha3

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1138]
1.1.0 alpha 2 had require support, now 1.1.0 alpha 3 no longer supports require to load module chanks

**Comment by yaapu** [comment]
this used to work in 1.1.alpha2
local lib = require "/path/to/lib"

**Comment by bsongis-frsky** [comment]
I removed by mistake the package lib
It will be there in alpha4
