### ISSUE TITLE
Flaps to elevator mix modify menu

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#114]
Ethos v1.0.3
X10s isrm
Could you please add a offset tab so the elevator movement at 10% would be 0 +10 +20, instead of -10 0 +10
Could you please add a slow up and slow down tab so we can have the elevator move at the same speed as the flaps.
Both of these functions are available in the free mixes please see photos
Photo 1 is flap to elevator mix
Photo 2 free mix
![20210424_013717](https://user-images.githubusercontent.com/81478751/115942113-82bbcb00-a4a0-11eb-942c-2af89e111c36.jpg)
![20210424_014428](https://user-images.githubusercontent.com/81478751/115942124-9109e700-a4a0-11eb-918d-7a80209df3ca.jpg)

**Comment by mawzthefinn** [comment]
For 1, add a curve to do this (but offset would be a great addition)

For 2, use the Flaps output as the source for the Flaps->Elevator mix, not the flaps input. Then all slow functions in the flaps mix will be replicated to the Flaps->Elevator mix. By setting the Flaps switch as your input, you are mixing SB to Elevators, not Flaps to Elevators.

**Comment by bsongis-frsky** [comment]
For 1 you should use the "Offset" mix.
