### ISSUE TITLE
lua: setTelemetryValue

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1141]
OpenTX like setTelemetryValue function to inject telemetry sensors

**Comment by bsongis-frsky** [comment]
What about this proposal?

```lua
local sensor = model.addSensor({name=translation("mySensor"), unit=UNIT_VOLTS, decimals=2})
sensor:value(20)
print(sensor:value())
```

**Comment by yaapu** [comment]
@bsongis-frsky any news on this one?

**Comment by yaapu** [comment]
@bsongis-frsky any updates on this one?

**Comment by Target0815** [comment]
> @bsongis-frsky any updates on this one?

I would like to join the question of Alex. Under OpenTX Alex has for example with his Script among other things VSpd as sensor added. It would be nice if there is this possibility also with Ethos.

**Comment by yaapu** [comment]
@Target0815 I solved this by using LUA Sources, please check my latest version on my github, wiki info is [here](https://github.com/yaapu/FrskyTelemetryScript/wiki/Ethos:-exporting-ArduPilot-sensors-as-LUA-Sources)
