### ISSUE TITLE
FR Trans 1.1.0 A3

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1144]
[fr.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7604926/fr.txt)

**Comment by bsongis-frsky** [comment]
Merci !
Ne pas hésiter à continuer mon travail de tri dans les catégories au fur et à mesure

**Comment by bsongis-frsky** [comment]
Parfait, j'ajoute juste un espace avant `!` (contrairement à l'anglais)
