### ISSUE TITLE
Lua: Voltages are not uniform throughout the system

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1145]
While reading voltages from sensors in lua, I noticed that voltages from various sources are not uniform.

VFAS 19.2v is denoted as 1920
System voltage of 7.5v is denoted as 75
That is a factor of 10 lower.

It would be better if we could read the voltages directly with decimals.

**Comment by bsongis-frsky** [comment]
Right. Sensor value() should be a Number, i.e. 7.5V
I propose to have those methods:
- `rawValue()` which return 75
- `decimals()` will return 1
- `value()` will return 7.5
- `unit()` will return UNIT_VOLTS
- `stringUnit()` will return "v"
- `stringValue()` will return "7.5v"

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/143592681-488c86c6-5159-4ba2-a7df-74f71003a36a.png)

**Comment by Hobby4life** [comment]
excellent!
