### ISSUE TITLE
lua: sport.telemetryPop

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1147]
add a method to access S.Port telemetry frames in an OpenTX compatible way i.e.:

push frame to LUA if either one is true:
- primid == 0x10 and dataId >= DIY_STREAM_FIRST_ID && dataId <= DIY_STREAM_LAST_ID
- primId == 0x32

#define DIY_STREAM_FIRST_ID       0x5000
#define DIY_STREAM_LAST_ID        0x50FF

**Comment by bsongis-frsky** [comment]
it won't be a compatible way, but it will work :)

**Comment by yaapu** [comment]
> it won't be a compatible way, but it will work :)

fair enough ;-)
