### ISSUE TITLE
Request: Turn off editable home screen

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1149]
Please make it possible to switch between editable and non-editable Homescreens. in my opinion it is enough if we can configure widget and screen in the Disp-menu. 

i think its even better for lua scripts with a touch reaction.

**Comment by Hobby4life** [comment]
I agree

Proposal:

Long press widget = Config options
Short press widget = (Lua) widget action

**Comment by yaapu** [comment]
agree

**Comment by bsongis-frsky** [comment]
What do you mean by "Non-editable Homescreens"? Why do you need them?

**Comment by loetefix** [comment]
I mean i want to switch off the ability to configure a widget by touching it in the homescreen.i mean it is enough to config it in the Disp menu. It is better for lua scripts that "catch" a touch. 

For example:
If i want to make a LUA script that changes the Display by every touch of it.

Or a script that display a timer. With a "long touch" i can reset that timer.

Sorry if i can not explain it very well. My English is not perfect.

**Comment by bsongis-frsky** [comment]
I tried this function, it does the job, no?

```lua
local function event(widget, category, value, x, y)
    print("Event received:", category, value, x, y)
    if category == EVT_KEY and value == KEY_ENTER then
        widget.timer:reset()
        return true
    elseif category == EVT_TOUCH then
        widget.timer:reset()
        return true
    else
        return false
    end
end
```

**Comment by bsongis-frsky** [comment]
Feel free to reopen if needed
