### ISSUE TITLE
lua: getColor(param) to access theme colors

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1150]
Add support for getting current theme colors.

lcd.getColor(<COLOR_INDEX>)

this mapping is extracted from EdgeTX Lua reference

COLOR_THEME_PRIMARY1
COLOR_THEME_PRIMARY2
COLOR_THEME_PRIMARY3
COLOR_THEME_SECONDARY1
COLOR_THEME_SECONDARY2
COLOR_THEME_SECONDARY3
COLOR_THEME_FOCUS
COLOR_THEME_EDIT
COLOR_THEME_ACTIVE
COLOR_THEME_WARNING
COLOR_THEME_DISABLED

**Comment by bsongis-frsky** [comment]
`lcd.themeColor(DEFAULT_COLOR, 200, 100, 100)`

![image](https://user-images.githubusercontent.com/50834778/145856296-e32dce33-bb44-4c5f-900a-8805c1e36ebb.png)
