### ISSUE TITLE
X20s V1.1.0 A2  Servotest funtion, Offset value has no funtion, no Curve possible

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1151]
Testing Servotest funktion

1.) Offset value has no function
only Weight up and Weight down  works

2) No Curve at Servotest possible

**Comment by Nicholas-Luoyi** [comment]
1. You will see the offset value when you set a delay mid.
2. Will the curve in channel configuration help you?

**Comment by hrenz** [comment]
A curve in the channel is possible but inflexible.
Curves, weights, offsets in the servo test mixer 
should be switchable
for really testing servos
for accuracy and repeatability,
not just run back and forth as now
