### ISSUE TITLE
V1.1.0a2 Error  at Mixer Throttel to Elevator

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1152]
Mixer Thr to elevor  has 2 Errors
a) with a simple curve and Weight 100%
b) with weight >50%

Error gas to height with simple 3-point curve  0, 10, 20
model20.bin uses a curve,
there you can see the error if you use a curve and set weighting 100%

model16.bin without curve, only with weighting, 20%.
But there is also only up to weighting 50% ok
with weighting 100% you see that only half the function works.

Thus the error comes central from the weighting, since no offset is considered.

Cant upload the 2 examples with *.bin
so rename *.bin.txt

[model16.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7609805/model16.bin.txt)
[model20.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7609806/model20.bin.txt)

**Comment by hrenz** [comment]
V1.1.0 A6 X20S
mixer testing
mixer throttel to elevator, same error as before, since weeks now
mixer throttel to rudder works fine, its ok with curve and with weight or both

this 2 mixers are not at cathegorie "gliders", 
e-motor glider need this mixers too, at least throttel to elevator

**Comment by hrenz** [comment]
Error at Mixer Thr to Elev
this is the kurve2 
![screenshot-2021-12-19-64224](https://user-images.githubusercontent.com/6217896/146968877-465c4895-2e1d-4d1b-8513-7f4cd56e033a.jpg)

this is the Result with kurve2 and weight 100%
![screenshot-2021-12-19-64307](https://user-images.githubusercontent.com/6217896/146969044-195e652d-5de3-4152-a30d-67e91ce05c43.jpg)

this ist the result  with no kurve but weight 100%
![screenshot-2021-12-19-64286](https://user-images.githubusercontent.com/6217896/146969191-9c66b384-21c6-4043-927e-30e6d21f0265.jpg)


the other mixter Thr to Rud  works well

**Comment by bsongis-frsky** [comment]
Fixed in alpha15 - will need your confirmation

**Comment by hrenz** [comment]
not fixed in Alpha 15 
but in 1.0.18 you write error in mix Thr to Rud
the error ist in mixer Thr to Elev

**Comment by hrenz** [comment]
ok works fine now

**Comment by bsongis-frsky** [comment]
This issue seems to me plain wrong and his fix has broken the mix.
I don't understand why hrenz uses Curve2, it makes the job 2 times and results in the truncated line

**Comment by bsongis-frsky** [comment]
I see only one issue with the original implementation: the weight was 20% when it should have been 10%

**Comment by bsongis-frsky** [comment]
This is the curve for 10%:
![image](https://user-images.githubusercontent.com/50834778/220900888-081cefc8-c1c7-4320-a216-415a513b1dae.png)

This is the curve for 100%:
![image](https://user-images.githubusercontent.com/50834778/220900976-6d154dfd-7561-4bf2-ac9a-e5dfae235337.png)

**Comment by bsongis-frsky** [comment]
Will be fixed in 1.4.8
