### ISSUE TITLE
Posso Installare ethos su una vecchia frsky horus x12?

### ISSUE THREAD

**Issue by benno771** [FrSkyRC/ETHOS-Feedback-Community#1154]
Buongiorno a tutti Volevo chiedervi se è possibile installare questo programma su una vecchia Horus x12 punto attualmente ha una vecchia versione di Open DX e volevo capire se potevo fare questo tipo di aggiornamento

**Comment by EngelMT** [comment]
No, devi prima convertirti al modulo RF ISRM. Solo allora ETHOS funzionerà sull'X12S.

Puoi scrivermi un'e-mail (service@engelmt.de). Perché una domanda del genere non appartiene qui.

Spero che la traduzione sia comprensibile. L'italiano non è il mio punto forte.

**Comment by benno771** [comment]
Come posso convertire il modulo? Esiste un kit?
--
Inviato da Libero Mail per Android sabato, 27 novembre 2021, 07:24AM +01:00 da Andreas Engel  ***@***.*** :

**Comment by jhammann13** [comment]
Ciao Benno,
La tua ultima domanda non appartiene a questo posto!
Si prega di scrivere un'e-mail a EngelMT.
Andreas Engel risponderà alle vostre domande

**Comment by benno771** [comment]
Potresti dirmi l'email?
--
Inviato da Libero Mail per Android sabato, 27 novembre 2021, 08:09AM +01:00 da jhammann13  ***@***.*** :

**Comment by jhammann13** [comment]
La domanda è seria?
Vedi il secondo post di EngelMT...


> No, devi prima convertirti al modulo RF ISRM. Solo allora ETHOS funzionerà sull'X12S.
> 
> Puoi scrivermi un'e-mail ([**service@engelmt.de**](mailto:service@engelmt.de)). Perché una domanda del genere non appartiene qui.
> 
> Spero che la traduzione sia comprensibile. L'italiano non è il mio punto forte.

**Comment by benno771** [comment]
Ok...scusami non capivo
--
Inviato da Libero Mail per Android sabato, 27 novembre 2021, 09:39AM +01:00 da jhammann13  ***@***.*** :

**Comment by jhammann13** [comment]
Tutto bene,
Chiedi lì cosa ti serve per ricostruire.

**Comment by bsongis-frsky** [comment]
I understand nothing in this issue except "Tutto bene", so I will close it :)
