### ISSUE TITLE
Ethos 1.1.0 alpha 4

### ISSUE THREAD

**Issue by jhammann13** [FrSkyRC/ETHOS-Feedback-Community#1155]
Hello,
is the X10/X10S and X12S not supported by alpha 3 / 4 ?
There are no files....

**Comment by mgsanna** [comment]
They re-start the Horus series ASAP..... see this link:
https://www.rcgroups.com/forums/showpost.php?p=48232033&postcount=12748

**Comment by jhammann13** [comment]
Thank you.

**Comment by bsongis-frsky** [comment]
I wondered if someone needed it ;)
