### ISSUE TITLE
lua lcd demo

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#1156]
if i change model the lua lcd demo don't stay installed in a model, i have to install it again each time i start my radio or if i get back to my model

**Comment by WismyYao** [comment]
Tested with the 1.1.0 alpha 4 ETHOS and did not find this problem. Could you try again ?

**Comment by bsongis-frsky** [comment]
Feel free to reopen if needed, it should work as Wismy said

**Comment by ronron84** [comment]
Sorry, i was busy today, it seems that it was a sd card issue. thanks
