### ISSUE TITLE
lua: lcd.drawNumber() add extra parameters for precision and alignment flags

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1157]
right now one would have to use string.format() and lcd.drawText() to display numbers with a fixed precision and specific text alignment.

my proposal:
lcd.drawNumber(x,y,num,unit,precision,flags)
where flags is the same as lcd.drawText() and precision is the number of decimals. (Precision should not just move the decimal separator as in OpenTX)

**Comment by bsongis-frsky** [comment]
Is it what you have in mind?

**OpenTX**
`lcd.drawNumber(121, PREC1)` ... "12.1"
`lcd.drawNumber(12.121, PREC1)` ... "1.2"

**Ethos**
`lcd.drawNumber(121, PREC1)` ... "121.0"
`lcd.drawNumber(12.121, PREC1)` ... "12.1"

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/145553743-3a723941-0c7e-4505-bbd5-98fda5456eb4.png)
![image](https://user-images.githubusercontent.com/50834778/145553788-9dba1754-523e-4c25-913f-2b6b9c5b4ba8.png)

**Comment by yaapu** [comment]
> [Is it what you have in mind?
> 
> OpenTX
> lcd.drawNumber(121, PREC1) ... "12.1"
> lcd.drawNumber(12.121, PREC1) ... "1.2"
> 
> Ethos
> lcd.drawNumber(121, PREC1) ... "121.0"
> lcd.drawNumber(12.121, PREC1) ... "12.1"](url)

yes! looks good to me!
