### ISSUE TITLE
LUA: problem with getSource

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1159]
X20 Ethos V1.1.0a4

Did anyone figure out how to print a telemetry sensor value to LUA widget?
im trying to read a telemetry value (RSSI) and print to LCD via LUA.
@bsongis-frsky  mentioned this method on another thread:

local Rssi = system.getSource("RSSI")
lcd.drawNumber(487,21,Rssi.value())

Actual result: nothing is printed on the LCD.
any ideas guys?

**Comment by Hobby4life** [comment]
what is the debug output in the windows console?

Run the simulator from a windows console.) so you can see simulator debug output

For example:
![image](https://user-images.githubusercontent.com/55426642/143686127-c62892cd-ffe7-4a1e-85a5-0f596448d347.png)

**Comment by i3dm** [comment]
how do i run it from console?

**Comment by i3dm** [comment]
![image](https://user-images.githubusercontent.com/8968780/143686330-ccb0e9cf-3622-49c4-a8dc-b30e6e55414b.png)

**Comment by Hobby4life** [comment]
Hmm, seems to be a bug in getSource()

**Comment by i3dm** [comment]
yes i think so too.
@bsongis-frsky your opinion?

**Comment by MiRe-CZ** [comment]
It seems to be the general issue with system.getSource in 1.1.0 alpha 4 (tested with RSSI, LiPo and RxBatt), it was ok in alpha 3.

**Comment by i3dm** [comment]
i will try to test on alpha3 as well

**Comment by i3dm** [comment]
downgraded to Alpha 3 and now:

![image](https://user-images.githubusercontent.com/8968780/143691487-8e919409-c6dd-48f5-a94e-809adcd435c2.png)

Lines:
89	local rssiVal =system.getSource("RSSI")
90	--lcd.drawNumber(487,21,Rssi)
91	lcd.drawNumber(487,21,rssiVal.value())

**Comment by i3dm** [comment]
> It seems to be the general issue with system.getSource in 1.1.0 alpha 4 (tested with RSSI, LiPo and RxBatt), it was ok in alpha 3.

with Ethos alpha3:
print(Rssi) returns "nil" on PC print,.

and on X20:
lcd.drawNumber(487,21,Rssi)
does not print anything, either on this line or following lines.

2 questions:
1. has anyone got to the point of displaying a telemetry parameter on the LUA screen yet?
2. is it possible to inject data into telemetry sensors on the sim to simulate incoming telemetry without testing on actual tx?

**Comment by i3dm** [comment]
managed to discover RSSI sensor on the sim - nice feature!
code:

88	local Rssi = system.getSource("RSSI")
89	print(Rssi)
90	print(Rssi.value())

prints:
Source: 0000000004ea7f58
020731 Lua::Widget::paint() error: /scripts/LZ_RDT.lua:90: bad argument #1 to 'value' (Source expected, got no value)

**Comment by MiRe-CZ** [comment]
RSSI = system.getSource ("RSSI")
These two lines are equal for printing the RSSI value as string:
lcd.drawText (X, Y, "RSSI= "..RSSI:value())
lcd.drawText (X, Y, "RSSI= "..RSSI:stringValue())

Or print the value as number:
lcd.drawNumber (X, Y, RSSI:value())

**Comment by i3dm** [comment]
Thank you !
Just tried this:

RSSI = system.getSource ("RSSI")
lcd.drawNumber (X, Y, RSSI:value())

and it works on X20, BUT only displays initial RSSI value (1dB) when radio is switched on, value stays stuck from there on on 1dB.

any ideas?

**Comment by agibson2** [comment]
The example script that is included with 1.1.0 alpha 4 doesn't work (rssi.lua) because of that error...

The debug output on the simulator shows this for this line in the rssi.lua script.

sensor = system.getSource("RSSI")

019930 Lua::Widget::wakeup() error: /scripts/rssi.lua:17: bad argument #-1 to 'getSource' (Source expected, got string)

I definitely have RSSI as a telemetry for my model in the Transmitter. I also have that as a Telemetry item in the model on the simulator.

**Comment by i3dm** [comment]
any ideas why on Alpha3 i can read telemetry data but it doesn't refresh?
