### ISSUE TITLE
Mixer Var shows no source, but it has at Var screen

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#116]
Mixer screen , Var mixer, shows no source
Var screen, source is set to analog

![grafik](https://user-images.githubusercontent.com/6217896/115947017-36cf4d00-a4c5-11eb-923c-20b97f73a912.png)

![grafik](https://user-images.githubusercontent.com/6217896/115946910-a55fdb00-a4c4-11eb-9931-0ceafaff01d2.png)

**Comment by bsongis-frsky** [comment]
I am not sure which will be the source there (or perhaps the current value?)

**Comment by hrenz** [comment]
wie can select MIN , MAX and an analog source
the analog has -100% to 100% 
bur for exakt setting die Poti value 
we need weigth and offset or a curve

**Comment by hrenz** [comment]
If you want to set a range that an encoder should sweep, you always need weighting and offset
OR a curve
Weighting alone does nothing, it is incomplete

Example:
Poti range has -100% to +100%
and should be rescaled from 0% to 30%.

**Comment by bsongis-frsky** [comment]
Already fixed
