### ISSUE TITLE
Emergency mode model is switched

### ISSUE THREAD

**Issue by mkdaw** [FrSkyRC/ETHOS-Feedback-Community#1162]
When creating a new model, the Horus 10 ismr goes into safe mode
When the model is switched, the Horus 10 ismr also switches to emergency mode
Used version Ethos 1.1.0 alpha 2

**Comment by EngelMT** [comment]
We have also received reports of this problem from customers.

**Comment by Hobby4life** [comment]
I have seen it once when running Alpha5 when it stil was available when switching to another model.
Rebooted radio, and selected again, no problem.
Until today I could not reproduce it.

**Comment by bsongis-frsky** [comment]
Reproduced and fixed for next alpha

**Comment by mkdaw** [comment]
Great .. Clever boy .. Just for fun, I'm sending you what she did on the link   https://www.youtube.com/watch?v=5kvciDZvd2o
thanks

**Comment by EngelMT** [comment]
@mkdaw Your comment sounds quite negative. If that's how it was meant, then I wonder why you write such comments? Bertrand and the other programmers do their best to do justice to every message here. And it should be clear that an "alpha" version can still have bugs. If they were sure that everything was OK, then they would release the final version.

**Comment by mkdaw** [comment]
I don't speak English that well and maybe I'm writing poorly. I appreciate the work of programmers and I praise their work
