### ISSUE TITLE
lua: storage.readNumber() returns 0.0 for non existent settings

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1166]
1.1.0 alpha 4

This prevents adding some logic to handle new settings between widget releses.

example:

local function read(widget)
    widget.conf1 = storage.readNumber()
    widget.conf1 = storage.readNumber()
    print(storage.readNumber())  <<< this one always return 0.0 but should return nil
end

local function write(widget)
    storage.writeNumber(widget.conf.1)
    storage.writeNumber(widget.conf2)
end

**Comment by bsongis-frsky** [comment]
Right, this is exactly what was expected, but it remains a bug. Will be fixed later today.
