### ISSUE TITLE
lua: model.createTimer() example needed

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1168]
need a code snippet on how to programatically create a new timer

**Comment by bsongis-frsky** [comment]
For example:
`model.createTimer({name="Test", countdown=true, start="60"})`

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/143822171-850c3114-841a-4749-bcb4-de4aa41142d1.png)

**Comment by yaapu** [comment]
@bsongis-frsky how do I start/stop a timer from LUA?
I guess I have to set an activeCondition like "Always On" and to stop it reset it to nil, but not sure how
