### ISSUE TITLE
simulator: no audio output

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1169]
1.1.0 alpha4

debug shows

003953 Stopping...
003954 REQUESTS task finished
003954 MIXER task finished
003956 playFile('/audio/en/system/bye.wav', flags=0, id=24)
003956 MENUS task finished
003958 AUDIO task finished

the file bye.wav exists but it's not played.

Also browsing using the simulator and hitting play does not work as well

![image](https://user-images.githubusercontent.com/30294218/143777434-3514b566-f72b-4346-96bd-ded9c68ff858.png)

**Comment by Hobby4life** [comment]
similar #1167

**Comment by bsongis-frsky** [comment]
Audio added in 1.1.0
