### ISSUE TITLE
lua: how to get debug output on real radio

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1170]
Is there a way to get some lua debug on real HW?

I have a complex widget that works in the SIM but not on actual HW so looking for a way to debug it.

**Comment by Hobby4life** [comment]
Would be nice if the USB port could act as usb-ttl serial device to debug.
Or bluetooth could act like a serial device.

**Comment by Ceeb182** [comment]
I like the idea of a monitor via USB or Bluetooth.

Here is another proposal. This proposal is to add a command line user interface (a kind of shell or command prompt) in a window that can be minimised or closed. In this window, there would be only text.
This has the advantage of being integrated into the Ethos interface (and thus also the simulator) and not requiring any technical knowledge of how to use a serial monitor. 

Some ideas about this kind of shell:
- this window is only activated if it is expressly pre-activated in a lua script: e.g. `shell(enable)`
- manual deactivation of the window takes precedence over shell commands by lua
- a checkbox on the window allows to set if the window should remain displayed after the ending of the script or disappear automatically
- this window can be minimized/maximized manually or by a lua instruction: for example `shell(minimize)` or `shell(maximize)`
- this window allows the display of the result of the type `print("something", dummy)`
- one or more LUA commands would allow to define the information displayed in the shell : all events like the current PC simulator, or only the events of the current script, or only the ETHOS OS events, or only the script errors, or only the interpretation of a part of the script bounded by `debug(on)` / `debug (off)` line by line, or nothing at all.
- to know who is returning the information to the shell, we could have a prompt mentioning the source like :
```
ScriptSinus> MyVar= 23.123
Ethos> 1425155 playFile('/audio/en/system/swr-warning.wav', flags=0, id=21) 
``` 
We can even imagine a display colour per source

**Comment by yaapu** [comment]
@bsongis-frsky this is a pretty important feature, lua radio debug is key for easy development
some more ideas, 
- a lua debug widget, a scrolling text window with an optional user defined filter (simplified version of @Ceeb182 idea)
- an OS option to enable LUA debug to the SD card (perhaps an option to enable per widget debug to SD card)
- print the error trace in the current widget window as default

**Comment by bsongis-frsky** [comment]
I am improving USB. Traces will be sent on USB / CDC when needed.

**Comment by Ceeb182** [comment]
Effective solution with the use of [Putty](https://www.putty.org/) software. :+1:
Once done, could you specify the "when needed" i.e. what are the conditions to activate this interface?

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/145022566-fee94e77-07f8-41de-bf12-0fac84f95d90.png)

**Comment by DucM1200S** [comment]
Hello @bsongis-frsky 
could you please provide information, how to connect to the radio via putty?

Thank you

**Comment by Hobby4life** [comment]
Open up a serial connection @ 115200bd.

**Comment by DucM1200S** [comment]
Thank you for your quick response @Hobby4life 

Somehow my computer wont talk to the radio.

![image](https://user-images.githubusercontent.com/88783368/145210755-8bb15cd6-3f59-4fbe-84e4-3e6fb67a1ec5.png)

Do you maybe know how to solve my issue?

**Comment by Hobby4life** [comment]
On my PC it worked directly, but I have a lot of STM tools running also.

I gues you need to install the STM VCP drivers. @bsongis-frsky ?
https://www.st.com/en/development-tools/stsw-stm32102.html ?

**Comment by DucM1200S** [comment]
Awesome! Thank you so much @Hobby4life  that worked!
