### ISSUE TITLE
Lua: put text into storage for config data

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1171]
I didn't see a way to store text using the storage functions.  It would be very useful to store text information into storage for configuration purposes.  Someone created a switch map script that shows a picture of the transmitter and puts text and lines to switches to show what switches do.  The text is hard coded though.  I was modifying it and creating the configure() section and got all the way to the read() and write() functions for actually storing text and realized we seem to only have storage.readNumber(), writeNumber(), readSource(), and writeSource().  It would be very useful to have a readText() and writeText().

**Comment by Hobby4life** [comment]
I suggest

**readString()**
**writeString()**

**Comment by agibson2** [comment]
There is already addTextField().  For consistency (assuming it is implemented), maybe text is better.
