### ISSUE TITLE
Feature Request: add to logical switch "a not switch"

### ISSUE THREAD

**Issue by HirezRa** [FrSkyRC/ETHOS-Feedback-Community#1172]
Is it possible to add to the logic switches **a not switch** 
  (ie !SA↓ or !L1 or !FM1 meaning **Not** SA↓, **Not** L1 and **Not** FM1 respectively)

For example in OpenTx
![image](https://user-images.githubusercontent.com/43018322/143788821-d6ac5f7c-da9a-4acf-bbd2-85f831287551.png)

This helps to shorten logic, for example in a 3-mode switch , if we are **not** in an 1 position, we will get **true** in the other 2 modes

**Comment by MIKE-DAILEY** [comment]
Exist now.  Whenever you see the small dot in the upper left of a field a long press in the filed offers options.
