### ISSUE TITLE
lua: model.createTimer() hangs the simulator

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1173]
this makes the simulator hang at the createTimer() line

local function create(widget)
	print("CREATE")
	if model.getTimer("Yaapu") == nil then
		model.createTimer({name="Yaapu", countdown=false, start="0"})
	end
end

**Comment by bsongis-frsky** [comment]
today it cannot be called in `create`!

**Comment by bsongis-frsky** [comment]
do you know if it hangs the radio too? it should, because mutexes are not recursive

**Comment by bsongis-frsky** [comment]
Mutexes are recursive now
