### ISSUE TITLE
lua simulator: allow telemetry feed via network socket

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1174]
To fully test widgets it would be great to allow telemetry frames to be injected via a socket, this would remove the need to integrate a telemetry emulator into the sim because users would be able to develop their own, sport and crossfire telemetry emulator would be pretty easy to write.

Telemetry push via socket might be worth considering as well

**Comment by Hobby4life** [comment]
STK compatability in the Simulator, so you could connect a real smartport device.
