### ISSUE TITLE
Lua: addChoiceField issue

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1175]
line = form.addLine("Choice")
form.addChoiceField(line, form.getFieldSlots(line)[0],
		{{"Test1", 1},{"Test2", 2},{"Test3", 3}}, 
		function() return widget.choice end,
		function(value) widget.choice = value
		end)
This return 1.0 / 2.0/ 3.0 at the first start instead of 1 / 2 / 3

BR

**Comment by agibson2** [comment]
addSwitchField() also does the same thing in Ethos 1.1.0 alpha 4.  I reported that also.  It would likely be helpful to always post what version you are running also.

**Comment by bsongis-frsky** [comment]
I am not sure of what you mean, here I just did a test and I get integer values: 

```lua
line = form.addLine("Test")
form.addChoiceField(line, nil, {{"Test3", 3}, {"Test1", 1}}, function() return widget.test end, function(value) print(value) widget.test = value end)
```

**Comment by bsongis-frsky** [comment]
I wonder if your issue doesn't come from readNumber, because readNumber will always return a number, not an integer

**Comment by bsongis-frsky** [comment]
`storage.readInteger(...)` and `storage.writeInteger(...)` added
