### ISSUE TITLE
Xact BUG: Travel setup is wrong

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1176]
When using the Xact configuration tool, setting up travel gives wrong output.

Setting: 90 = 120degree physical travel
Setting: 120 = 120degree physical travel
Setting: 180 = 90degree phyiscal travel

Servo's HV5611
Radio X20S / Alpha4

@WismyYao ?

**Comment by WismyYao** [comment]
Has your XACT firmware been updated to above 1.5.7?

**Comment by WismyYao** [comment]
Has your XACT firmware been updated to above 1.5.7?

**Comment by Hobby4life** [comment]
> Has your XACT firmware been updated to above 1.5.7?

Latest firmware version is: 1.5.1 on the download website.
This is what I use.

![image](https://user-images.githubusercontent.com/55426642/144369754-98b969d4-b7f4-4dd1-9866-e387a9a3737a.png)

**Comment by Hobby4life** [comment]
Latest version on download page is v1.5.1
This is what I use now.

https://www.frsky-rc.com/xact-hv5611/

**Comment by WismyYao** [comment]
[HV5611_12.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7640469/HV5611_12.zip)

This is the latest firmware

**Comment by Hobby4life** [comment]
Hi, I have flashed your firmware.
Strange is that with your firmware servos are not reacting, not moving, no telemetry.

When I download the latest file from the webstite (seems to be the same version) my servos work again.

No the most weird part.

When setting it to 180degrees, physical is 180degrees
When setting it to 90degrees, physical is 120degrees
When setting it to 120degrees, physical is 90degrees
