### ISSUE TITLE
lua: io.read("l") always returns an empty string

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1179]
1.1.0 alpha4

io.read() always returns an empty string

example:
```lua
  local file = io.open("/logs/sample.log")
  local line = file:read("l")
  print("READ", file, #line, line)
  io.close(file)
```
output
`READ    FILE*: 0000000004756830 0`

sample.log:
```
line1
line2
line3

```

**Comment by bsongis-frsky** [comment]
- added `read("l")`
- added `read("L")`
- added `read("a")`

**Comment by yaapu** [comment]
@bsongis-frsky tested io.read("l") works but on EOF returns an empty string instead of nil so not easy to catch EOF

**Comment by MiRe-CZ** [comment]
io.read("l") apparently keeps EOL, the same as io.read("L") does

**Comment by bsongis-frsky** [comment]
Tests done:
read("l") => returns the line without EOL
read("L") => returns the line with EOL
After reaching EOF, both return nil (it needed a fix)
