### ISSUE TITLE
Défaut de lecture de la carte SD sous windows 10   X12S ETHOS1.0.3

### ISSUE THREAD

**Issue by GIB2A** [FrSkyRC/ETHOS-Feedback-Community#118]
Bonjour .
La radio apparait bien dans Windows  dans le gestionnaire de périphériques sous frsky x12s joystik . 
Cependant il n'est plus possible de voir la racine de la carte sd  dans  l 'explorateur de fichier même après modifications des drivers via le gestionnaires de périphérique ou zadig .
Question:
Est il possible de crée un dossier  spécifique pour les ficher son utilisateur afin de garder une cohérence dans la carte SD
Cordialement 
Ps: félicitation pour le travail sur Ethos!!!!!!!! il est vraiment top !!!!! merci!!!! 
GIB2A

**Comment by MIKE-DAILEY** [comment]
Bootloader mode is used to access the SD card.  While holding the enter key down press power on.  Bootloader displays on Horus screen.  Connect Horus to Windows a PC with a data USB cable.  Windows File Explorer starts and displays SD card folders and files.

**Comment by GIB2A** [comment]
Thank you for your reply
I will rephrase my remark.
Would it be possible when connecting the usb cable to the radio to be able to choose between:
frsky joystik
frsky storage (sd card)
without going through the following manipulation which makes paidre in user-friendliness and simplicity of use
Bootloader mode is used to access the SD card. While holding the enter key down press power on. Bootloader displays on Horus screen. Connect Horus to Windows a PC with a data USB cable. Windows File Explorer starts and displays SD card folders and files

**Comment by bsongis-frsky** [comment]
On this radio the SD card is used for storing the models and system data, going into massstorage means you cannot read / write from the system, moreover you should re-read everything when USB is ubplugged (or reboot the radio as done in OpenTX)

Perhaps it's better to keep it as it is, it's not a too much complex scenario

**Comment by GIB2A** [comment]
Merci pour votre réponse  !! Ethos est vraiment un tres bon software !!!! Qui devrait enfin ravis  beaucoup de modeliste Cordialement Etienne Envoyé de mon Galaxy A5 2017 Orange
-------- Message d'origine --------De : "Bertrand Songis @ FrSky" ***@***.***> Date : 25/04/2021  09:53  (GMT+01:00) À : FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc : GIB2A ***@***.***>, Author ***@***.***> Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] Défaut de lecture de la carte SD sous windows 10   X12S ETHOS1.0.3 (#118) 
Closed #118.
