### ISSUE TITLE
FR 1.1.0 A4

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1180]
Avec quelques tris en cour
[fr.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7653604/fr.txt)

**Comment by bsongis-frsky** [comment]
Nouveau fichier maintenant : 
[fr.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7653650/fr.txt)
