### ISSUE TITLE
New feature: Last position option for new mix

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1181]
When creating a new mix, you get the option of **First Position**, followed by the current mixes in order. It would be great if there was and option after **First Position** for **Last Position**. This would add the new mix after the current last mix.

**Comment by Nicholas-Luoyi** [comment]
You could scroll to the last position of the menu. The new mix will be the last position

**Comment by MrD-RC** [comment]
> You could scroll to the last position of the menu. The new mix will be the last position

I know. But when you have quite a few things in the mixer, a convenient button at the top would be much more user friendly.

**Comment by bsongis-frsky** [comment]
Why not
