### ISSUE TITLE
Adjustment of Threshold for Throttle Warning

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1182]
I am using ETHOS 1.0.14 on a Horus X10S Express.

I realised the other day that in several models the threshold for the throttle warning in the checklist menu was not set to the default value, although I do not normally change this setting. I found that it is possible to change the threshold by just navigating to either of the two control fields for this setting and then moving the throttle stick, without pressing any button. The modified value is automatically stored upon navigating away from the adjustment fields. This behaviour is quite prone to inadvertant adjustment of the threshold (which I had obviously done in several cases). Note that it is always the throttle stick that adjusts the value, regardless of the input selected in the throttle mix, and this makes it even worse.
As this behaviour has potential safety implications, it should be changed such that a button must be pressed in order to be able to change the threshold for the throttle warning. In addition, this setting must only be possible with the control selected as input in the throttle mix. Alternatively (and preferrably from my perspective), changing the threshold by just moving the throttle control could be eliminated.

**Comment by bsongis-frsky** [comment]
oh it's true
