### ISSUE TITLE
lua: model.getInfo() to get current model name and bitmap

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1183]

**Comment by i3dm** [comment]
subscribing.. i need it as well

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/145418067-b3eb202f-c2fd-4cce-8dad-bc4e7ac6432c.png)

![image](https://user-images.githubusercontent.com/50834778/145418088-9fdb132e-7fcb-471e-b968-81e6f16a4fb5.png)

**Comment by i3dm** [comment]
> 

next release? :)
