### ISSUE TITLE
Release 1.1.0. Alpha 6  Bad intermittent sounds

### ISSUE THREAD

**Issue by mkdaw** [FrSkyRC/ETHOS-Feedback-Community#1186]
Horus 10 ismr. Intermittent system sounds. Could it be an overloaded processor?

**Comment by bsongis-frsky** [comment]
Rather an overloaded SD card, but I have an idea to improve this

**Comment by mkdaw** [comment]
It occurred to me too .. I'm trying to give another one .. Praise your work.

**Comment by mkdaw** [comment]
I tried another and it also does ... The system sound is chopping and the display is chopping .. Maybe it's just reading the SD card slowly ??

**Comment by bsongis-frsky** [comment]
Perhaps you could share your model?
Did you try another SD card? If it's too slow the audio will be cut and the display will be refreshed slowly. 
Only the mixer has a greater priority

**Comment by mkdaw** [comment]
Alpha 2  worked great. The same models. I also tried a new faster SDcard .. I don't know if you saw this video on youtube ?? https://www.youtube.com/watch?v=5kvciDZvd2o
Thanks and a lot of success at work

**Comment by mkdaw** [comment]
https://www.youtube.com/watch?v=5kvciDZvd2o

**Comment by bsongis** [comment]
I need your model to try it myself, thanks

**Comment by mkdaw** [comment]
I'm sending the entire contents of the SD card   https://www.uschovna.cz/zasilka/SUI5S6PMKGFC3NNE-E5F/

**Comment by bsongis-frsky** [comment]
Your model has 2 WriteLogs functions, one enabled, one disabled. We are testing a fix so that in this scenario we don't open / close logfiles at full speed. Have a look to your logs folder, you have some cleaning to do now ;)

**Comment by mkdaw** [comment]
Thanks. I'll look at model 2
I just want to add that the sound stutters even when starting on off Horus
Thanks for the advice

**Comment by mkdaw** [comment]
Succeeded. It works ... Your perfect work.
