### ISSUE TITLE
On Home keymap to include in long press to access direct to curves

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#1187]
It would be interesting to include on home keymap a quick access to long press to Curves Menu,  because in helicopter mode is very practical for configuration. Thanks

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/147467853-cc0a0f59-2af1-4ee4-b6d8-bab30f70ffce.png)
![image](https://user-images.githubusercontent.com/50834778/147467871-32451251-ad9a-45e6-981c-6027c426f629.png)

**Comment by Hobby4life** [comment]
Again Excellent implementation
