### ISSUE TITLE
V1.1.0 A6: Trainer part bug

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1188]
The implementation of "Not controlled by trainer" no clue what this does.

**1.** Only CH1, CH2 and CH3 you can set "Not controlled by trainer"
CH4 to CH16 not.

**2.** Even when this option is set.. Slave input is stil interacting with Master logic switches.

**Comment by bsongis-frsky** [comment]
Where do you use the new option?

**Comment by Hobby4life** [comment]
From my understanding as how I explained it to @Nicholas-Luoyi, is that when disabled.. slave should not interfere with any logic functions on Master transmitter.

This is my logic to detect stick interruption on master TX
![afbeelding](https://user-images.githubusercontent.com/55426642/145100963-862f0c81-6c04-4647-b25a-7fbface45e3f.png)
When I deflect one of the 3 sticks by 15%, Trainer is shut off

**Comment by Nicholas-Luoyi** [comment]
Please set the "Not controlled by trainer" option for the source of the LSW which you don't want it controlled by trainer.

**Comment by Hobby4life** [comment]
> Please set the "Not controlled by trainer" option for the source of the LSW which you don't want it controlled by trainer.

Ahh I undertand!, will test tonight.

This option is also available at Source input in Trainer menu.
Should not be there then right?

**Comment by Hobby4life** [comment]
Update: This works excellent! thanks for implementing this! :-)

**Comment by bsongis-frsky** [comment]
Luo is doing another modification to avoid the misunderstanding

**Comment by Hobby4life** [comment]
Ok, nice

If so, please take a look if a switch(source) can be assigned to turn on of channels in trainer menu.
So for example I can disable elevator trainer input during a session.

**Comment by bsongis-frsky** [comment]
No. This is a different topic.
