### ISSUE TITLE
V1.0.14 Logic switch based on volts range gets stored as percent

### ISSUE THREAD

**Issue by mikedkelly** [FrSkyRC/ETHOS-Feedback-Community#1189]
When I create a logic switch based on Lipo telemetry defined as range 10.30V to 10.50V, it looks correct in the edit screen, but on the Logic Switches list screen, it shows as 1030% to 1050% and it never triggers when the lipo voltage is the defined range. Since it does work correctly with A > X and A < X rules, I worked around this by creating separate lipo > 10.30V and lipo < 10.50V rules and ANDed them together as the final logic switch.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/145167335-e75ba088-f07b-4168-b74d-4959f43687ce.png)
