### ISSUE TITLE
add "rudder differential" for v-tail or dedicated v-tail mixer

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#119]
unfortunately, i can't see dedicated v-tail mixer in ethos 1.03.
so i've to deal with the ele/rud mixer which are created by choosing "v-tail" in the model properties.

What i'm missing is the possibility to compensate typical behaviour of v-tail models by applying rudder.
most of them go into a slight dive, some tends upwards.
This is compensated by rudder differentiation.

At the moment you have to use a free mixer, but imho that's not the to go nowadays.

attached you'll find some examples of competitors.

greetings
udo

![spektrum](https://user-images.githubusercontent.com/20392683/115986975-47f68780-a5b3-11eb-8bda-a533f82e9586.jpg)
![jeti](https://user-images.githubusercontent.com/20392683/115986980-4c22a500-a5b3-11eb-8e46-4c46ed61fdd4.jpg)

**Comment by strgaltdel** [comment]
Hi,

a little experimenting shows a variant, which would fullfill the requirements for a Vtail and shows how a V Tail mixer should work (imho)

If the Ailerons (Querruder) would be the rudder, all would be OK on channel 1 & 2

For user "convenience" i would suggest a dedicated Vtail mixer should combine these logic in one "pane of glass"

regards
![V-tail](https://user-images.githubusercontent.com/20392683/116005127-e4e21080-a605-11eb-9e0b-4434dd2212c5.jpg)

**Comment by Hartinger** [comment]
Hi All,
I second the requirement for a single V-Tail mixer, this is imho a MUST for a user friendly menu driven radio software.
Please see also my remarks in #57.

**Comment by strgaltdel** [comment]
Ich kehre zurück am 28.06.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] add "rudder differential" for v-tail or dedicated v-tail mixer
(#119)" gesendet am 14.06.2021 10:51:04.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by tflyerofrc** [comment]
The Rudder Differential for V-Tail Mixer is sorely needed.    As stated in earlier comments it is required in order to control pitch when applying rudder.  How do we get this to the top of the pile for implementation??

**Comment by yesyes2a** [comment]
Hi, I try to get a solution with copying "rudder" fonction in the mixages menu. 
The 1st one for only for the right rudder 
The 2nd one only for the left rudder;
So You can choose a curve for each rudder and have more travel down and less travel up. Inconvienant, you have to take the same curve (inverted). And if you want to change diff value, you have to change the 2 curves.

**Comment by tflyerofrc** [comment]
Very complicated given that a simple addition of Differential takes care of
it and does not interfere w/ any other inputs (eg Elevator).

I suppose I could also just set the throws to get diff in Rudder, then use
the existing Differential in Elevator VTail to rebalance the elevators.
 Terrible way to do it but its better than nothing.

Makes no sense to me that they added Differential to Elevators in VTail
mode, but not the Rudder.   You actually only need it on the Rudders.

**Comment by tflyerofrc** [comment]
To follow up I added two free mixes for the Rudder and put a curve for each
one and tested on a clone program and it works.   Thanks for the idea.  It
is the simplest resolution I have received to date.   Stll hopeful that an
enhancement if made to Ethos VTail menu adding the missing "differential"
for the Rudder.

**Comment by Hartinger** [comment]
You could also generate a mixer Rud -> Ele, which should have the same effect as Rud differential.

**Comment by jurajjurej** [comment]
The Rudder Differential for V-Tail Mixer is sorely needed. As stated in earlier comments it is required in order to control pitch when applying rudder.

**Comment by Hartinger** [comment]
As stated earlier, a mixer Rud -> Ele has exactly the same effect as Rud Differential.

**Comment by tflyerofrc** [comment]
Do not agree w/ that.    The difference is the the RUDDER stick is driving the differential, not the Elevator stick.   When applying Elevator I do not want any mixing between the channels.

**Comment by Hartinger** [comment]
When you have a Rud -> Ele mixer, applying Elevator does not generate any mixing, as the Rudder stick is the input of that mixer.

**Comment by tflyerofrc** [comment]
Exactly, which is why the Differential needs to be on the RUDDER stick.   Right not its on the Elevator stick input so the differential will only be applied w/ the Elevator stick.

**Comment by Hartinger** [comment]
The differential is not an attribute of the stick, but an attribute of the mixers.

If you generate a mix Rud -> Ele (in addition to the normal v-tail configuration), then the Elevator stick will behave exactly the same as without that mix. If you apply Rudder, then the v-tail flap going up will have a travel that is different to the one going down, due to the overlay of the normal Rudder function and the Rud -> Ele mix. This is what I call Rudder Differential. Through the sign of the weigth in the mix you can contol if the v-tail flap going up has the larger travel or the one going down.

**Comment by tflyerofrc** [comment]
Guess we are not speaking the same languge.  I am a user not a programmer.  The differential thru a mixer is driven by an input signal.  We want that signal to be the Rudder.

Not sure why this discussion is on work around plans?   

My input, and that from several other folks is the benefit/need of a differential rudder function so we can tune the pitch when rudder only is applied.    I fly VTails and found this very useful on the "other" brand equipment.   Frankly I am not sure why FrSky put differential on the Elevators to begin with.

**Comment by mawzthefinn** [comment]
Rudder differential on a V-tail is functionally equivalent to an input to the elevator function driven by the rudder input.  That’s why a Rud->Ele mix will work to give you differential in a V-tail. Unlike on a cross tail, you cannot separate the Rudder and Elevator functions on a V-tail, they work together. 

It’s not quite so simple as creating a Rud->Ele mix, but rather you will also need to add a custom curve to that mix, 3 points with your points being 100,0,100 to condition the rudder input so it’s always giving a positive value at full deflection. 

That said, we still do need a differential setting in the Rudder Mixer for V-tails, the workaround is somewhat non-obvious.

**Comment by mawzthefinn** [comment]
Quick walkthough on setting this up here:

https://www.rcgroups.com/forums/showthread.php?4252495-ETHOS-V-Tail-Differential-w-Live-adjustment

**Comment by 2xWhiskey** [comment]
A topic coming up on 2 years in age.  As a newcomer to Ethos with a TWIN X-Lite, I spent a couple of hours experimenting until I was able to figure out how to implement the rudder differential properly on my V-tail. A built-in rudder differential selection just like for a 2-servo aileron wing would be a nice feature to have...

**Comment by OberlinRC** [comment]
Please, add a V-Tail diff. Funktion on the Mixers. Its so uncomfortable not to have it.
We fly lots of Modells with V-Tail here and i can see how easy this feature is to achieve on other Tx Modells. Would be a good argument for Non-Ethos users to switch to Frsky.

**Comment by tflyerofrc** [comment]
Been trying to them this done for a long time now.

**Comment by bsongis-frsky** [comment]
It is coming!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9a74e1b6-e60e-461f-8b36-290f72e2fdc7)

**Comment by tflyerofrc** [comment]
Looking forward to seeing it.

**Comment by bsongis-frsky** [comment]
It will be pushed to nightlies tonight.

**Comment by tflyerofrc** [comment]
Great News!

**Comment by m0p3d** [comment]
Very nice to see progress ! Thanks

**Comment by tflyerofrc** [comment]
I assume this will be available with the 1.5.0 firmware update?

**Comment by tflyerofrc** [comment]
Did this ever get pushed out?    I have not seen it listed on any of the latest firmware versions?

**Comment by mawzthefinn** [comment]
It’s in the Nightlies for 1.5.0, as per the tag

**Comment by tflyerofrc** [comment]
OK.  I thought  it was earlier.  Thanks.
