### ISSUE TITLE
Inactivity alarm not working

### ISSUE THREAD

**Issue by FBarrao** [FrSkyRC/ETHOS-Feedback-Community#1190]
X20S 1.1.0 alpha 4 FLEX

Inactivity alarm set to 12 minutes, but doesn´t work. 
I have checked that time to time the brightness of the screen wake up by itself, without touching anything..  if fact, being 1 metter far from the radio..  maybe there are some kind of " auto inputs" that prevents to activate the inactivity alarm.

**Comment by bsongis-frsky** [comment]
Perhaps you could test with less than 12 minutes to be sure?

**Comment by FBarrao** [comment]
Tested. 
and I think that I know what is happenning. I have the screen brightness set to the central slider, and I think that the small flickering of the slider  woke up the system. I have to say that there is no noticiable flickering in the status bar of the slider, but..

Set inactivity to 1 minute, and screen sleep to 15 s. 
Most of the times, screen sleeps in 15 s, and inactivity sounds in 1 minute, ok. 
Sometimes, screen sleeps in 15 minutes, and some seconds later wakes up by itself Then, inactivity doesn´t sound in 1 minute, ( because the system has been woken up).
Sometimes even the screen doesn´t sleep in 15 seconds, as it should. 

I will try again with a fixed brightness, ( not assigned to the slider) and check if solves the problem.

**Comment by bsongis-frsky** [comment]
Feel free to reopen if needed, nobody else complained!
