### ISSUE TITLE
No info on dispay of sensors  (release 1.1.0 alpha 6), X20 EU

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1191]
Hello,
Since the last update, (release 1.1.0 alpha 6), X20 EU radio (rx X8R and R8 PRO), the sensors no longer give data (lipo; Amp; ..). I redid the discovery of the sensors, check the IDs (All different) ..
The Lipo sensor detects the number (well !! 1x / 2) of elements, but does not give any information on the tensions of each element of the lipo pac
![20211208_111546](https://user-images.githubusercontent.com/84312994/145201609-9357c18c-c640-4bdb-ab52-6904e5fc6bdc.jpg)
![20211208_111633](https://user-images.githubusercontent.com/84312994/145201615-1e7dd4dc-f9d7-4c76-9bec-d7422f713940.jpg)
![20211208_111734](https://user-images.githubusercontent.com/84312994/145201619-819a355c-cb22-4760-8025-f32c540e10e9.jpg)
![20211208_111806](https://user-images.githubusercontent.com/84312994/145201621-9480b2ac-bb4e-4efe-8d68-8f5d529af50c.jpg)
![20211208_111849](https://user-images.githubusercontent.com/84312994/145201623-1a1aa798-8a7a-4835-aae7-c993880b3fbe.jpg)
![20211208_112258](https://user-images.githubusercontent.com/84312994/145201624-2e677b71-c0cc-4e02-95aa-d4571c0b1289.jpg)
![20211208_121454](https://user-images.githubusercontent.com/84312994/145201626-3c40856c-bbcb-483a-8f7c-293963a75582.jpg)
![20211208_121431](https://user-images.githubusercontent.com/84312994/145201628-919acff3-e5c2-4804-8dc9-b15d569212ac.jpg)
k.

**Comment by bsongis-frsky** [comment]
If you deleted all your sensors, then in all widgets (and everywhere, logic switches, functions, etc.) the reference to those sensors are lost. 

Here after discovery, you have to select again your LiPo sensor in your LiPo widget. Don't forget that you may have many LiPo sensors connected and the widget needs to know what is its associated sensor.

**Comment by Mobidick1966** [comment]
This is what I did.
But no change.

**Comment by Mobidick1966** [comment]
For the lipo sensor (that of the photos), it detects the number of elements (3s or 6s) but gives no tension value. The same goes for the ampere meter (FAS100S). for the gps as I am in a cellar, I have no reception.

**Comment by bsongis-frsky** [comment]
Would you show me your Model / Telemetry screen, do you see your sensors (with blinking values)?

**Comment by Mobidick1966** [comment]
Hello again,
I found my problem, I programmed one of the 6 buttons to reset the telemetry, so I must choose another of the buttons to activate the telemetry.
My excuse for this request.
