### ISSUE TITLE
Request: Trainer seperate Active condition sources for each channel

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1193]
It would be great if a switch(source) can be assigned to seperate turn on each of 16 channels in trainer menu.
Next to the active condition. Now we only can turn on all or nothing.
So for example I can disable elevator trainer input during a session.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/145544704-c7fa7447-b83e-4452-82c8-9a8221101c9c.png)

**Comment by Hobby4life** [comment]
Awesome!
