### ISSUE TITLE
SxR calibration wizard typo

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1194]
The last page (before calibration complete) of the calibration wizard is incorrect. 

On the previous page, it tells you to have the receiver on it side, with the label facing you and legible. The pins on the right. This is all good.

On the page with the error, it tells you to have the receiver on it's side with the label facing you, with the text upside down. It then states that the pins will be on the right. They won't, the pins will be on the left with the receiver like this.

Not a big issue, but it is confusing.

**Comment by Hobby4life** [comment]
Keep in mind, the R9 Stab as exact the oposite labeling.
People tend to look more to a picuture then read text. I have got some questions in the past how to calibrate the R9 Stab.
They only looked at the picture.

**Comment by MrD-RC** [comment]
Regardless of whether the label is upside down or not, the pins can’t be on the right before and after rotating the receiver. They have to be on the left at some point.
