### ISSUE TITLE
lua: decimal point issue

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1195]
ADC4 value 8.28V is shown as 8.28001V with Draw Text.
this is on alpha 4.
https://www.youtube.com/watch?v=tl2LBsvaF7I

https://www.youtube.com/watch?v=VJkM_VJvJIA

i guess it should always be 1 or 2 chars after decimal point?

**Comment by bsongis-frsky** [comment]
What is your script? drawText draws a text, I guess the 001 don't come from nowhere

**Comment by i3dm** [comment]
EcuV = system.getSource ("ADC3") 
	if (EcuV == nil) then 
	lcd.setFont(S)
	lcd.drawText (540, 255, "ECU:     No ADC3") 
	else 
	EcuVValue = EcuV:value() 
	lcd.drawText (540, 255, "ECU:     "..(EcuVValue).."V") 
	end

**Comment by bsongis-frsky** [comment]
Please read about how float works on computers
Then you will try `string.format`

**Comment by i3dm** [comment]
what is string.format?
