### ISSUE TITLE
Request: LUA source list

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1196]
Please post a source list of all available sources for GetSource()

for example how to read:
1. trim values
2. Stick / slider values
3. Tx pack voltage
thanks.

**Comment by bsongis-frsky** [comment]
Everything seems already in the doc

![image](https://user-images.githubusercontent.com/50834778/145406050-d1ca68ef-7f40-4065-8209-89900a6dfd73.png)
![Uploading image.png…]()

**Comment by i3dm** [comment]
@bsongis-frsky  im not seeing a list of cource names anywhere in the docs.

whats the source name for Tx voltage / trims for exmaple?

**Comment by i3dm** [comment]
test1 = system.getSource({category=CATEGORY_TRIMS, member=1, options=0})
	testvalue1 = test1:value()
	lcd.drawNumber (400, 200, testvalue1)
	test2 = system.getSource({category=CATEGORY_TRIMS, member=2, options=0})
	testvalue2 = test2:value()
	lcd.drawNumber (400, 220, testvalue1)
	test3 = system.getSource({category=CATEGORY_TRIMS, member=3, options=0})
	testvalue3 = test3:value()
	lcd.drawNumber (400, 240, testvalue1)
	test4 = system.getSource({category=CATEGORY_TRIMS, member=4, options=0})
	testvalue4 = test4:value()
	lcd.drawNumber (400, 260, testvalue1)	

print on LCD is:
0
0
0
0
regardless of trim position.

how do we read the 4 trims?

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/145421625-d08f2da6-2a57-4f12-a87f-c4c638a24e1e.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/145421669-93a6eb2a-44b6-4351-bf80-4f10fc86a71f.png)

**Comment by i3dm** [comment]
I guess Tx voltage is inside ANALONGS?
but which number of analog? there are many analogs on the Tx.

**Comment by i3dm** [comment]
please advise how to read Tx Main Voltage
