### ISSUE TITLE
alpha 8 lua and simulator

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#1197]
hi,
on alpha 8 the simulator doesn't show lua script.
![image](https://user-images.githubusercontent.com/16739660/145478720-eb6626f2-61e8-4bcb-9b11-bec4a77f9ad5.png)

**Comment by Hobby4life** [comment]
check if you still have **setFont() and setColor()** this from now on is changed to **font() and color()**

**Comment by bsongis-frsky** [comment]
We need more info when you have a failing script!

**Comment by ronron84** [comment]
Ok i will check the lua file i didn't make any change that for sure the
problem i 'm going to modify all the file i have thanks

**Comment by ronron84** [comment]
You're right😄thanks
