### ISSUE TITLE
LUA: alpha8: model.name and model.bitmap not callable

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1199]
ModelName = model.name("Name")
ModelName = model.name()
ModelName = model.name("")

in all cases:
003803 paint() error: /scripts/LZ_RDT.lua:403: field 'name' is not callable (a nil value)

same goes for model.bitmap()

**Comment by bsongis-frsky** [comment]
my mistake, fixed in alpha9

**Comment by i3dm** [comment]
> my mistake, fixed in alpha9

alpha9 is showing on releases page since yesterday.. but with no assets.
