### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#120]
Hello,
os 1.0.3 x12s .... After a few seconds of recording logs, I already had 57 files? Why ? Normally all these files should be in an folder .........example folder: solius 250421-14h.
                               solius 250421-14h05 .. ect  (logs on / off on inter) it's much easier to find the recording you want to read.

~~2) How to read the log files on the radio ??? not found .... you would have a lua for that ??~~

~~3) How to delete  all  the log files on the radio ??? not found...? (one log yes but all ? not found)~~

Thank you for your response and good work.

**Comment by bsongis-frsky** [comment]
I cannot reproduce your problem.

Would you please tell us which switch you use to start the logs?

All logs come in the logs folder

About other requests I have written another issue, they are new features which will come later
