### ISSUE TITLE
Display sensor data from flight controllers over f.port/s.port via Yaapu script

### ISSUE THREAD

**Issue by mikedkelly** [FrSkyRC/ETHOS-Feedback-Community#1202]
As the Lua interpreter becomes available, my primary use will be to discover the sensors that are part of or connected to my flight controller and sent to my receiver over f.port and running the Yaapu script on my X20S. It would be great to have full Yaapu functionality in Ethos.

**Comment by bsongis-frsky** [comment]
This is rather for @Yaapu!
