### ISSUE TITLE
lua: io:read("l") returns also CR, it should not

### ISSUE THREAD

**Issue by MiRe-CZ** [FrSkyRC/ETHOS-Feedback-Community#1203]
Simulator 1.1.0 alpha 8
file:read("l") returns also Carriage return, it should be skipped
file:read("L") returns properly both Carriage return and Line feed

![image](https://user-images.githubusercontent.com/95141646/145629745-a83b4dc8-8e12-4b0d-be10-c62d690c113f.png)

The example shows outcome (number of characters, read string and its ASCII representation) from reading of the simple file with 3 lines:

line1
line2
line3

Related to: [#1179](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1179#issue-1071031013)

**Comment by bsongis-frsky** [comment]
FatFS doesn't support open files in text mode, you have to use files in Unix mode, no CRLF
