### ISSUE TITLE
LUA: model.bitmap() issue

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1208]
print(model.bitmap())
prints:  /bitmaps/user/easy2.png

but during init:
mdlimage2 = mdlimage2 = lcd.loadBitmap(model.bitmap())

and then in the code:
lcd.drawBitmap(34, 70, mdlimage2, 320, 125)
prints the system/defaultplane.png  on the LCD.

**Comment by bsongis-frsky** [comment]
perhaps because in init the model is not loaded
