### ISSUE TITLE
Ability to disable all telemetry except RSSI and Rx battery

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1209]
OpenTX has an FAI mode that allows us to very easily disable telemetry for some local f3k contests that allow telemetry sensors to be installed if they are disabled.  They allow link status type sensor data like RSSI and Rx battery.  Having a mode like this allows us to buy and install receivers with built in telemetry as well as extra sensors knowing that they can be disabled easily for some contests.

I am hoping something similar can be made available on Ethos.

**Comment by bsongis-frsky** [comment]
Do you mean a special firmware? OpenTX has an option and firmware are compiled on the fly...

**Comment by agibson2** [comment]
In OpenTX, If the option is enabled, It disables all telemetry except RSSI and battery levels.  To disable the mode, It requires disabling it using Companion (uncheck FAI enable) and then uploading the settings to the transmitter.
If Ethos had a special firmware version that did it, I think that would be best as it could be verified at the start of the event that you are running FAI mode firmware.

With already multiple versions of firmware for Ethos required, I can see that might not be something FrSky would want to support as it would double the amount of firmware versions needed (FCC, etc, etc).  If that isn't doable or wouldn't be approved to have a separate firmware version,  Even just a simple toggle in the system menu to disable/enable in Ethos would be helpful (without a special firmware version) as it is based on trust anyway as someone could connect their transmitter to a PC with OpenTX, or in case of separate firmware, just reflash their firmware at the field to enable it during a competition.

A system menu option to put the transmitter into FAI mode would suffice for my use case with local F3K competitions that I attend.

**Comment by bsongis-frsky** [comment]
@WismyYao The toggle option is the easiest way I can see

**Comment by agibson2** [comment]
If/when this gets implemented to disable sensors for fai mode, It would be great to expose this to Lua so that scripts that use sensors can detect this and either disable some parts of the script and/or let the user know why sensors are not being displayed.

**Comment by WismyYao** [comment]
You said disabling all telemetry, does the RF module no longer transmit telemetry, or is it just that ETHOS doesn't process telemetry data?

**Comment by federicobelfi** [comment]
The FAI mode should be also visible on the top bar or somewhere were is not possible to reproduce the same sign anyway.

**Comment by mawzthefinn** [comment]
It should be noted that FAI Mode is not FAI-legal for F3K, and most likely not for the other sailplane disciplines.

FAI legality currently requires the receiver capability be limited to only signal and voltage telemetry, based on a ruling just before the WC 2 cycles ago that left FrSky pilots scrambling to replace G-RX6's with RX4R and RX6R's on short notice.

FAI mode would still be useful for those flying lower-level contests without strict adherence to the FAI rulings.

**Comment by bsongis-frsky** [comment]
"Competition (only RSSI and Battery)" option added to next nightlies

**Comment by agibson2** [comment]
I just want to say thanks again for this mode.  It really makes it easy to disable all telemetry except RSSI and battery when needed.
