### ISSUE TITLE
chronos

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#121]
https://user-images.githubusercontent.com/82876308/115997088-1b0d9900-a5e2-11eb-9c28-4e99e89e8b72.mp4

Hello,x12s os 1.0.3
to illustrate my request, a small video.
The left slide controls the engine and the two chronos. SH a short press stop chronos (1 second) a second pulse (more than 2 seconds) for resetting
thank you
How to do this with ethos ???    all the gilders man around the world use these times (gilder with engine of course)

**Comment by bsongis-frsky** [comment]
Please show your opentx configuration for doing this, we will try to find the solution with Ethos

**Comment by aeroplanebelg** [comment]
[copie solius.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6378862/copie.solius.pdf)
[copie supra f5j valenta.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6378865/copie.supra.f5j.valenta.pdf)
Thank you for your interest in my requests.
you will find attached two models of glider with motor.One basic(solius) and another for compétitive f5j(supra)
you will see that the we use mathématical functions whitch are not in ethos....and the global variables(vg) super good
Youwill olso see that the recording of logs is conditionedby an inter..for regardiing this logs on the radio open tx allows via a little lua.....very easy....at home,the pc and companion.
so,thank you for everything...thank you in advance.

**Comment by mawzthefinn** [comment]
That timer logic is fully supported in current ETHOS versions
