### ISSUE TITLE
Lua: timer:activeCondition() not callable

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1210]
Ethos 1.1.0 alpha 9

Trying to use timer activeCondition() gives an error.  Also we need to know how to force activeCondition() to always be on or always be off for internal script timers that don't need switches, etc.

testtimer1 = model.createTimer()
testtimer1:activeCondition(widget.activesource)

005603 write() error: /scripts/timet.lua:33: method 'activeCondition' is not callable (a nil value)

**Comment by bsongis-frsky** [comment]
Fixed in alpha10
You will use the new constant `CATEGORY_ALWAYS_ON` as a category for your switch

**Comment by agibson2** [comment]
Thanks for the quick response.  We will be able to change it to something else to pause it?  Maybe set it to nil or something?  I assume default is nil.
