### ISSUE TITLE
Lua Bug  Alpha 9: color/lcd.drawLines() behaves strange

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1211]
After flashing to **Alpha 9**, most of my widgets that use **drawLines()** functions start to behave strange with their color.

Suggested to set **read/writeNumber** for color to **read/writeInteger** did not have effect.

**Comment by bsongis-frsky** [comment]
`drawLines()`, are you sure?
Do you encounter the same issue with the gauge widget from the examples?

**Comment by bsongis-frsky** [comment]
Note that the interface will change again in alpha10

**Comment by Hobby4life** [comment]
> `drawLines()`, are you sure? Do you encounter the same issue with the gauge widget from the examples?

Alle other draw functions behave normal.. only drawline.. check my example i sent you.

**Comment by bsongis-frsky** [comment]
You are right, I didn't realize that only `drawLine()` had this issue!
