### ISSUE TITLE
ETHOS and RB30

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1212]
There are issues with RB30.

1. Channel 17 - 24 only working if the Gyro is switched off in the config.
2. RX3 is working only if the RX3 is switched "OFF" in the config. If it is switched "ON" it is not working.

Issue 1. can be a RB firmware issue. I do not know. But issue 2. must be a ETHOS issue.

I reported it several weeks before to Liang and Bertrand and some days before to Adela. Of course, it is possible that this was lost in your work for Lua.

**Comment by bsongis-frsky** [comment]
Item 2 is fixed in 1.1.0 alpha 12

**Comment by bsongis-frsky** [comment]
Item 1 is not Ethos

**Comment by EngelMT** [comment]
O.k. then I will close it. Hope that Adela have a look on it to make an RB Update.
