### ISSUE TITLE
model.createTimer() returns nil

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1213]
Ethos 1.1.0 alpha 9 (no sim available for 10 yet)
Ethos 1.1.0 alpha 11 (also just tested that 12/17

I have this in the wakeup() just for testing.

local testtimer1 = model.createTimer()
testtimer1:start(60)
testtimer1:direction(-1)

002701 wakeup() error: /scripts/timet.lua:38: attempt to index a nil value (local 'testtimer1') 

Interestingly the bahavior is different if I move the local testtimer1 = model.createTimer() outside the wakeup call.  The simulator just crashes if I do that.

**Comment by WismyYao** [comment]
The maximum number of timers currently allowed to be created is 8. If you create a timer in wakeup, nil will be returned when the maximum number is exceeded

**Comment by agibson2** [comment]
I was not aware of that.  Thanks.  This can be closed.  Is that in the docs somewhere that I missed?  So the return value should always be checked and disable the stuff that uses that if the createTimer() returns nil.

**Comment by agibson2** [comment]
I have time to test this again and I am still getting nil.  Attached is an example script that shows the problem
[tttt1.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7738570/tttt1.zip)
.

**Comment by agibson2** [comment]
The issue with nil is that Lua is creating the timers but they are not being removed.  I for some reason assumed they were temporary and would be removed on shutdown of the simulator/transmitter.  You have to getTimer("timer name") and then create one only if getTimer didn't find a previous timer with that name (returned nil).

I think there is still a bug but it is in the getTimer(somenumber).  That seems to always return nil.  Using the text name like getTimer("timer name") does work.  I was looping through getTimer(0 through 8) to see if timers exist or not for debugging but they were always returning nil so I assumed it didn't see any timers.  I then discovered them in the GUI so I then realized there were a bunch of Test1 timers taking up all 8 timers.
