### ISSUE TITLE
Lua: add msgBox()

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1214]
Would be nice if we can call popup message boxes with confirmation buttons.

**msgBox()**

Will appear in center of screen.
- Adding text
- Adding multiple definable confirmation buttons.

**Comment by i3dm** [comment]
great idea

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/147452757-5060841a-fe32-469d-b438-00d3d4c5ed4e.png)

**Comment by Hobby4life** [comment]
Excellent bertrand!
