### ISSUE TITLE
Main screen not displayed upon selection of a particular model

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1215]
With ETHOS 1.0.14 on my Horus X10S Express I have a strange phenomenon with one of the models stored on the radio (model04.bin). Whenever I power up the radio with this model selected, the main screen is not displayed, but the model comes up with screen 2 (showing just the RSSI value in this case). If I then navigate to the main screen by pressing the PgUp/Dn button, power down the radio and then power it up again, the same happens (screen 2 displayed). The same can be observed if I do not power down the radio but select a different model and then reselect the problematic model.

I tried this maybe 15 times now and in a couple of cases the channel monitor did not show any signals.

I have attached the model file, which must be corrupted in some strange way, I guess. (.txt to be removed)
[model04.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7721185/model04.bin.txt)

**Comment by Nicholas-Luoyi** [comment]
Please go to the home page config. And set the screen 1 as the main screen.

**Comment by Hartinger** [comment]
Thanks for that. I did not see this option because the German translation of "Set main screen" is incorrect. I will let Andreas Engel know.
