### ISSUE TITLE
Telemetry sensor RPM unit wrong?

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1217]
I noticed that in "Model -> Telemetry" the RPM and the GasSuite? RPM is labelled r/m and it cannot be changed.
I think the correct would be rpm or RPM.

![Skjermbilde (1)](https://user-images.githubusercontent.com/87149917/146246262-9ae7f985-fd33-423a-8095-edf95cc030c2.png)

![Skjermbilde (2)](https://user-images.githubusercontent.com/87149917/146246257-41ecc1e5-d740-4f58-8db3-e5734349cdf2.png)

**Comment by mmasch** [comment]
Also in the RPM menu, I wonder what "Average" and "5 samples" means. It can be set to 1 to 5 samples.

**Comment by Hobby4life** [comment]
It does what it says..

It takes 5 samples.. and then calculate the average of these 5 samples. then shows it.

**Comment by mmasch** [comment]
RPM labelling fixed in 1.1.0 alpha11 :-)
