### ISSUE TITLE
LUA: Please allow a full screen widget

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1218]
Please allow a full screen widget like in Opentx, as it is at the moment with top and bottom bar (marked green) and a blank strip under the top bar, marked Yellow, the effective area for widgets is maximum about 60-70% of the screen, as can be seen in the photo.
![x20 screen](https://user-images.githubusercontent.com/8968780/146388034-78f04586-d553-42d2-b09e-a690467b72ba.PNG)

**Comment by Hobby4life** [comment]
Would indeed open up more oppertunities.

If this will be implementend we should also be able to have more touch options/functions, as top and bottom navigation is not possible anymore.

**Comment by i3dm** [comment]
> Would indeed open up more oppertunities.
> 
> If this will be implementend we should also be able to have more touch options/functions, as top and bottom navigation is not possible anymore.

not sure its needed as we can always go into the menus with the buttons?

**Comment by Hobby4life** [comment]
Well if you occupy the whole screen it would be nice to have touch features.. so we can create buttons or sliders. or whatever for our widgets

**Comment by i3dm** [comment]
> Well if you occupy the whole screen it would be nice to have touch features.. so we can create buttons or sliders. or whatever for our widgets

agreed.
but this could be a second stage enhancement :)
