### ISSUE TITLE
LUA: Problem with lcd.drawBitmap()

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1220]
X20 Ethos 1.1.0 Alpha11

_Issue number1:_
local function draw_Background(Me)
local w2, h2 = lcd.getWindowSize()
lcd.drawBitmap(0, 0, background, w2, h2) -- background
print(w2)
print(h2)
end

returns: 784, 316
**but any image above the size of  713x269 is not loading:**

001235 malloc size 772893 refused
001235 load_stb(/scripts/RDT/img/RDT_bg.jpg) failed: outofmem
001236 Load bitmap /scripts/RDT/img/RDT_bg.jpg failed!
001237 Lua::load('/scripts/LZ_RDTw.lua')
001272 malloc size 772893 refused
001272 load_stb(/scripts/RDT/img/RDT_bg.jpg) failed: outofmem
001273 Load bitmap /scripts/RDT/img/RDT_bg.jpg failed!

and wallpaper is blank (doesn't load).

_Issue number 2_
there might also seem to be another bug in DrawBitmap():

according to docs it says:

x | (number): X coordinate
y | (number): Y coordinate
bitmap | (Bitmap): bitmap
w | (number, default = 0): the width of the bitmap displayed
h | (number, default = 0): the height of the bitmap display

yet when you try to scale an image to fit in Ethos it always scales down using the original aspect ratio, according to height.
for example if your image is 100x100 pixels and you want to scale it down to 100x50, it will display as 50x50 which totally defeats the purpose of having 2 parameters (w,h) for scaling.

**Comment by Hobby4life** [comment]
add this jpg file

**Comment by i3dm** [comment]
attached
![RDT_bg](https://user-images.githubusercontent.com/8968780/146424031-2a0aaa42-0903-4a38-aaee-07198f958ec6.jpg)

**Comment by Hobby4life** [comment]
Can you try this one? i have converted it to 8 bit PNG.
I dont know if this is the case, but you can try it because it says it is out of memory.

[bitmap.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7729500/bitmap.zip)

**Comment by i3dm** [comment]
its the same size as mine so it does load. but if you scale it up to 101% it faults again. this time:
001185 malloc size 780751 refused
001185 load_stb(/scripts/RDT/img/bitmap.png) failed: no SOI
001186 Load bitmap /scripts/RDT/img/bitmap.png failed!

note: this photo is much smaller than screen size and should easily fit.

**Comment by i3dm** [comment]
btw you can easily test this on X20 PC sim (as i do) if you like. i really doubt the PC is out of memory when loading a small jpg

**Comment by i3dm** [comment]
there might also seem to be another bug in DrawBitmap():

according to docs it says:
x | (number): X coordinate
-- | --
y | (number): Y coordinate
bitmap | (Bitmap): bitmap
w | (number, default = 0): the width of the bitmap displayed
h | (number, default = 0): the height of the bitmap display

yet when you try to scale an image to fit in Ethos it always scales down using the original aspect ratio, according to height.
for example if your image is 100x100 pixels and you want to scale it down to 100x50, it will display as 50x50.

**Comment by bsongis-frsky** [comment]
I think your bitmaps are not correctly encoded. Especially when you deal with so big bitmaps.
The limit is the screen size, 16bits per pixel, you should not need more.
The PC simulates correctly the RAM limit here and it's nice.

**Comment by i3dm** [comment]
> I think your bitmaps are not correctly encoded. Especially when you deal with so big bitmaps. The limit is the screen size, 16bits per pixel, you should not need more. The PC simulates correctly the RAM limit here and it's nice.

i tried any possible encoding i could find with no joy.
perhaps you could share what is the correct encoding or provide an example before closing the issue?

**Comment by bsongis-frsky** [comment]
H4L gave you an example above if I am not mistaken.
This repo is for issues, not for questions, please use RCG for such questions

**Comment by i3dm** [comment]
H4L example does NOT work.
this is an issue. not a question.

**Comment by bsongis-frsky** [comment]
Don't use PNG for very big pictures. 
If it's a background you should use BMP format with 16bits (565) pixels.
Again this has been already discussed on RCG

**Comment by i3dm** [comment]
> 16bits (565) pixels.

reformatted the background image to 16 but bmp and now the whole image seems skewed:
![image](https://user-images.githubusercontent.com/8968780/146542562-ccc6c684-8c27-4807-95fa-070784a9fa1e.png)

1. can you please offer a simple bmp example of a full screen single color background?
2. 2. can you address the other issue with bitmap size (w,h)?
3. thanks.
