### ISSUE TITLE
lua: 1.1.0 alpha9 has a lot of clipping debug traces

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1221]
please remove the clipping debug traces from the simulator ot provide a command option to disable them

156751 AVANT 505 278 493 287
156751 CLIPPING 8-792 95-411
156751 APRES 505 278 493 287
156751
156751 AVANT 493 328 478 273
156751 CLIPPING 8-792 95-411
156751 APRES 493 328 478 273
156751
156751 AVANT 493 328 507 273
156751 CLIPPING 8-792 95-411
156751 APRES 493 328 507 273
156752
156752 AVANT 478 273 493 284
156752 CLIPPING 8-792 95-411
156752 APRES 478 273 493 284
156752
156752 AVANT 507 273 493 284
156752 CLIPPING 8-792 95-411
156752 APRES 507 273 493 284
156882
156882 AVANT 388 261 360 270
156882 CLIPPING 8-792 95-411
156882 APRES 388 261 360 270
156882
156882 AVANT 388 261 413 275
156882 CLIPPING 8-792 95-411
156882 APRES 388 261 413 275
156883
156883 AVANT 388 266 360 270
156883 CLIPPING 8-792 95-411
156883 APRES 388 266 360 270
156883
156883 AVANT 388 266 413 275
156883 CLIPPING 8-792 95-411
156883 APRES 388 266 413 275
156883
156883 AVANT 389 259 357 271
156883 CLIPPING 8-792 95-411
156883 APRES 389 259 357 271
156884
156884 AVANT 389 259 416 277
156884 CLIPPING 8-792 95-411
156884 APRES 389 259 416 277
156884
156884 AVANT 387 268 357 271
156884 CLIPPING 8-792 95-411
156885 APRES 387 268 357 271
156885
156885 AVANT 387 268 416 277
156885 CLIPPING 8-792 95-411
156885 APRES 387 268 416 277
156886
156886 AVANT 493 323 481 278
156886 CLIPPING 8-792 95-411
156886 APRES 493 323 481 278
156886
156886 AVANT 493 323 505 278
156886 CLIPPING 8-792 95-411
156886 APRES 493 323 505 278
156886
156886 AVANT 481 278 493 287
156886 CLIPPING 8-792 95-411
156887 APRES 481 278 493 287
156887
156887 AVANT 505 278 493 287
156887 CLIPPING 8-792 95-411
156887 APRES 505 278 493 287
156887
156887 AVANT 493 328 478 273
156887 CLIPPING 8-792 95-411
156887 APRES 493 328 478 273
156887
156887 AVANT 493 328 507 273
156887 CLIPPING 8-792 95-411
156888 APRES 493 328 507 273
156888
156888 AVANT 478 273 493 284
156888 CLIPPING 8-792 95-411
156888 APRES 478 273 493 284
156888
156888 AVANT 507 273 493 284
156888 CLIPPING 8-792 95-411
156888 APRES 507 273 493 284

**Comment by bsongis-frsky** [comment]
yes, already seen and fixed :)
