### ISSUE TITLE
LUA: draw Bitmap() aspect ratio issue

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1222]
This issue is present since 1.1.0 Alpha 1.
id like to use a full screen background image, on a widget with no title (for max screen size).
so i edited the lcddemo.lua as a simple exmaple:

-- Lua LCD Test widget

local bitmap, mask

local function paint(widget)

    -- Demo of a bitmap
    local w2, h2 = lcd.getWindowSize()
    lcd.drawBitmap(0,0, bitmap, w2, h2)
	print(w2)
	print(h2)
end

local function init()
    bitmap = lcd.loadBitmap("FLASH:/bitmaps/system/default_glider.png")
    mask = lcd.loadMask("FLASH:/bitmaps/system/mask_dot.png")
    system.registerWidget({key="lcddemo", name="Lua LCD Demo", paint=paint})
end

return {init=init}

i expect the image to start at 0,0 and to span both w and h to the size of the full LCD widget area.
the result on the screen is the image resized using the original aspect ratio to maximum height size, and width is not maximized on the screen (as can be seen by the 2 gray vertical bars on both sides):
![image](https://user-images.githubusercontent.com/8968780/146546562-62b18e1c-891c-4751-8e4f-f3c0a4328d8a.png)

if drawBitmap() does not change aspect ratio, then what is the point of having (w,h) parameters?

**Comment by i3dm** [comment]
> w and h are the size of the widget pane.. not whole lcd

check the photo i added.
the bitmap does NOT cover the width of the widget pane.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/146652660-5ea3a5d6-c0b4-4f9e-b711-e8d7cccf5657.png)

![image](https://user-images.githubusercontent.com/50834778/146652664-1526fd68-c4d7-4dc9-a394-96ac5b2b18b7.png)

**Comment by bsongis-frsky** [comment]
```lua
    -- Demo of a bitmap
    local w2, h2 = lcd.getWindowSize()
    lcd.drawBitmap(0, 0, bitmap, 0, h2)
```

**Comment by bsongis-frsky** [comment]
The bitmap to show the right encoding as already discussed earlier: BMP - 565

[background.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7739784/background.zip)
