### ISSUE TITLE
Lua: getTimer(0) returns nil even when Timer1 exists

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1223]
Ethos 1.1.0 Alpha 11

If you cycle through model.getTimer(0)  replacing 0 with 0 through 8, the return value is always nil.  Using a text name for a getTimer() does work.  Using an ID doesn't though.

```
local function paint(widget)
end

local function wakeup(widget)
	-- DEBUG loop through all timers to see if any exist
	local textoutput = ""
	for i=0,8 do
		local querytimer = model.getTimer(i)
		textoutput = textoutput .. " " .. i .. "=" .. type(querytimer)
	end
	print("TTTT2: TIMERS -" .. textoutput)
	
	local querytimer = model.getTimer("Timer1")
	print("TTTT2: Timer1=" .. type(querytimer))
end

local function init()
    system.registerWidget({key="tttt2", name="tttt2", paint=paint, wakeup=wakeup})
end

return {init=init}
```

Output is...
TTTT2: TIMERS - 0=nil 1=nil 2=nil 3=nil 4=nil 5=nil 6=nil 7=nil 8=nil
TTTT2: Timer1=userdata

Timers1, Timer2, and Timer3 exist so if timer ids start at 0 then 0, 1, and 2 should exist and return userdata instead of nil when cycling through ids 0 through 7.

**Comment by bsongis-frsky** [comment]
confirmed and fixed for alpha12

**Comment by agibson2** [comment]
Nice.  Thanks.  Do they start at 0 or 1?
