### ISSUE TITLE
Lua: lcd.GREY() error field 'grey' is not callable

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1225]
Ethos 1.1.0 Alpha 11

When trying to use lcd.GREY(), you get the error below...

lcd.GREY(128)

paint() error: /scripts/f3ktraining.lua:304: field 'GREY' is not callable (a nil value)

**Comment by bsongis-frsky** [comment]
Typo from me I wrote "GRAY" instead of "GREY". It will be GREY in alpha12
