### ISSUE TITLE
Training test between X20(alpha 11) and X12S... (BT. And cable)

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1226]
Hello
I tested the trainer mode (in Bluetooth) between my X20 (alpha 11) master and X12s (last FW openTX) student, it works But the operation is jerky (not pressed) of the X12s. The distance is very short between the 2 Radio (max 1.5m.) Before being disconnected.

In Wired mode, no operating problems. Just the X20 MUST have Bluetooth enabled, if not, no connection between the 2 radios. Is this normal ??

**Comment by hrenz** [comment]
This is due to the principle of bluetooth
because it is not suitable for real-time transmission.

Better and flawless with a small receiver that feeds its sum signal to the DSC socket. 

It would be even better to be able to feed an SBus signal to the DSC socket.
But ETHOS is not able to do this

**Comment by i3dm** [comment]
> This is due to the principle of bluetooth because it is not suitable for real-time transmission.
> 
> Better and flawless with a small receiver that feeds in its sum signal to the DSC socket.
> 
> It would be even better to be able to feed an SBus signal to the DSC socket. But ETHOS is not able to do this

also the DSC socket does not have a power socket, so its much harder to connect an external Rx.
older Futaba radios and similar also had power in the trainer port pins. then you could connect an Rx with just one cable.

**Comment by mawzthefinn** [comment]
The X12's BT trainer doesn't work terribly well, it was an early version of the functionality and FrSky improved it greatly with later implementations. I recommend using wired trainer unless you have a radio with the later PARA module.

BT enabled should not be necessary for wired trainer, please confirm if this still exists on current firmware
