### ISSUE TITLE
Lua: color picker not setting color properly

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1227]
If you set BLACK using mycolor=BLACK, that ends up being 0x0f00000.  If you use the colorpicker, black ends up being 0x00000000 and doesn't show up.  I assume the second nibble (f) in the value is a transparancy or something and it is setting it to transparent.  I think the color picker should be setting colors with 0x0f......

If you test the included gauge.lua, It will show the bug.  You will see that once you use color picker to change the color, it does not look like it draws the bar for the level.  I think it is drawing it but drawing it transparent.

FYI... d_wheel on rcgroups discovered this bug that the gauge doesn't work properly.

**Comment by Hobby4life** [comment]
What alpha version are you using?
Are you sure you use the gauge.lua from alpha11 with alpha 11 simulator? if not colors will do strange things, as the whole color system had a major makeover..

**Comment by dwheel** [comment]
I am using the alpha 11 sim, alpha 11 on my transmitter, and the 11 version of gauge lua. The color picker does not work correctly in the sim or on transmitter. It sets the color to gray regardless of which color is picked.

Here is the code. Is it correct?

-- Color
    line = form.addLine("Color")
    form.addColorField(line, nil, function() return widget.color end, function(color) widget.color = color end)

**Comment by Hobby4life** [comment]
> 

This is the proper way to setup..

In create you need to specify where to "geValue" the color you want to retreive while initializing the colorpicker color.

``lua
local function create()
  return {color=0}  
end


local function paint()
  
end

local function configure(widget)
  -- Color
  line = form.addLine("Color")
  form.addColorField(line, nil, function() return widget.color end, function(value) widget.color = value end)
end

local function init()
    system.registerWidget({key="color", name="Color Test", configure=configure, create=create, paint=paint})
end

return {init=init}``

**Comment by agibson2** [comment]
hobby4life, Did you test the default gauge.lua?  It shows the behavior where it doesn't work.  If you print out the values for the color if you set it manually vs setting it via the value that color picker returns, you will see the values differ for the simple black color.

**Comment by dwheel** [comment]
Thank you. This still does not work in the gauge.lua script. Can you please try the one included in the alpha11 download? There must be an error in the code that I can't find.

**Comment by Hobby4life** [comment]
> hobby4life, Did you test the default gauge.lua? It shows the behavior where it doesn't work. If you print out the values for the color if you set it manually vs setting it via the value that color picker returns, you will see the values differ for the simple black color.

You are correct, not seen this happening frist.. there is still an issue indeed.
