### ISSUE TITLE
Lua: getTime() for compatibility

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1228]
Any chance of a function like in OpenTX called getTime()?  That can be useful for some simple time based stuff without need or complexity of Timers when you just need to know how long ago something was done.  Is there already an equivalent of that that gives 'Number of 10ms ticks' since transmitter power on?

**Comment by yaapu** [comment]
you can use os.clock()

-- in the SIM
local function getTime()
 return os.clock()*100 -- 1/100th
end

-- real radio
local function getTime()
  return os.clock()*10  -- 1/100th
end

**Comment by agibson2** [comment]
Sweet!  That will work.

**Comment by bsongis-frsky** [comment]
OpenTX scripts are not compatible, I won't search to minimize the differences

**Comment by agibson2** [comment]
Understandable.  Thanks for response.  os.clock() will work.
