### ISSUE TITLE
Issue telemetry FrSky X20S / R8Pro Access / ETC 3.4 / Avian ESC

### ISSUE THREAD

**Issue by ralfv** [FrSkyRC/ETHOS-Feedback-Community#1230]
Issue using telemetry from Spektrum Avian via ETC from https://www.rclightsystems.com/product-page/esc-telemetry-converter

Telemetry is unstable with continuous 'sensor lost' messages when using FrSky following components:

- X20S FW 1.0.14 EU #8445e1b7
- RX R8Pro Access (Archer-X HW 2.2.0 FW 2.1.9)

The telemetry input components are:

- ETC FW 3.4 from https://www.rclightsystems.com/product-page/esc-telemetry-converter 
- Spektrum Avian in H9 Ultra Stick PNP (the yellow one)

Avian is working fine w/ETC in SBUS mode, Avian reverse also works. I configured the reverse in ESC to channel 8 as this is a 7 channel model T A E R A2 F1 F2 Rev.

Telemetry **using R8Pro Access receiver is very unstable**.

BTW telemetry works great **using an older RX RX8R Pro in ACCST** mode.

Some pictures from X20S (firmware and telemetry info) see attached.

I tried various RX settings like 25mw telemetry and changing from sport to fport and fport2. But nothing helps.

You can see below images - all sensors detected but mostly "sensor lost" audio alerts and very short periods where some sensors deliver data. Also screen showing FW of X20S.

I read through https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/357 which is Closed not sure what exactly was fixed for it to be closed.

![IMG_8006](https://user-images.githubusercontent.com/20543402/146689279-a5f03a1a-19be-4da0-9b2e-bdb40eec256e.jpg)

![IMG_8010](https://user-images.githubusercontent.com/20543402/146689483-f472fea1-d0d9-459c-8cab-472e94c695c8.jpg)

Thanks,
Ralf

**Comment by SmartTommy** [comment]
do you have a logic analysis? it should idle the SPORT line 400us before the Sensor replay the data to the Rx.

**Comment by ralfv** [comment]
> do you have a logic analysis? it should idle the SPORT line 400us before the Sensor replay the data to the Rx.

Pls help me out here for a moment: is this something I as regular user can generate a log from in the TX? Or is this a question for the ETC sensor developer?

**Comment by Hobby4life** [comment]
100% smartport protocol of ETC is not 100% compatible due timing issues, or invalid data.
I have the same issue with S32 loggers, from Jlog. these output smartport but the protocol is not 100%.
As the firmware in the old D16 receivers are more forgiving, Archers are not.. they expect strict timing in smartport protocol.
As for ETHOS it wont accept invalid smartport values..

Like opentx sends out negative current values for current sensors.. ETHOS/smartport wont allow this a will result in sensor lost warnings.

ETC like S32 have to fix their smartport compatability, and therefore it is not an ETHOS / Frsky issue

**Comment by ralfv** [comment]
> 100% smartport protocol of ETC is not 100% compatible due timing issues, or invalid data.

OK

> As the firmware in the old D16 receivers are more forgiving, Archers are not..

What's wrong with being more forgiving?

**Comment by simonwood** [comment]
I'll have a look at this tonight (I do have a logic analyser). Will let you know. 

(P.S. - I am the sensor developer).

**Comment by simonwood** [comment]
Ahh, I turn the message round in about 114uS, that would be the problem then. I'll add an async hold off on the reply. 

As an aside, 400uS seems a long turn around time, does your UART not provide a TX Idle interrupt? (that's what I use in my code for half duplex return to receive operation).

**Comment by simonwood** [comment]
All fixed, now running with back off between 410 and 520uS. Tested on X20S / R8Pro Access.

Thanks for the info, please close the issue.

**Comment by Hobby4life** [comment]
Altough this is closed.. @simonwood can you contact me? b.pasteuning@hobby4life.nl
