### ISSUE TITLE
lua: how to get lat/lon from GPS source

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1231]
Please provide an example on how to extract cordinates from a GPS source

**Comment by OldGazer** [comment]
What kind of  source are you talking about?

**Comment by Hobby4life** [comment]
system.getSource("GPS")

**Comment by yaapu** [comment]
or from the UI

![image](https://user-images.githubusercontent.com/30294218/146769613-246bae7c-135b-4490-8612-cd5cb707f38b.png)

**Comment by yaapu** [comment]
> What kind of source are you talking about? I just realized who you are. Perhaps we should be asking how we go about extracting data from an FPort/SPort telemetry data stream that contains data generated by a Pixhawk flight controller using the ArduCopter FRSky SPort Passthrough protocol.

that is already being worked on

**Comment by Hobby4life** [comment]
Would nice if there could be some examples how to parse source values in the reference manual. saves a whole lot of questions.

**Comment by bsongis-frsky** [comment]
@yaapu yes, they are already written, but still not public

**Comment by yaapu** [comment]
> @yaapu yes, they are already written, but still not public

I guessed and hoped so :-)

**Comment by bsongis-frsky** [comment]
Examples:
`system.getSource("RSSI")`
`system.getSource({name="GPS", options=LATITUDE})`
`system.getSource({category=CATEGORY_TIMER, member=1, options=0})`
`system.getSource({category=CATEGORY_SYSTEM, member=MAIN_VOLTAGE})`
`system.getSource({category=CATEGORY_SYSTEM_EVENT, member=RSSI_LOW})`

**Comment by yaapu** [comment]
@bsongis-frsky I still can't get lat/lon the way you suggested

what the SIM reports as "fake" gps position
![image](https://user-images.githubusercontent.com/30294218/147959605-e1e5cfb8-5235-46f1-8e3c-e39b07e9345d.png)

lua example

print("LAT", system.getSource({name="GPS", options=LATITUDE}):value())
print("LON", system.getSource({name="GPS", options=LONGITUDE}):value())

output

LAT     -242.8001
LON     242.8001

**Comment by bsongis-frsky** [comment]
Stupid mistake from me, it's fixed in alpha14:
![image](https://user-images.githubusercontent.com/50834778/147966597-8dc0dba2-6aad-43b5-b7a2-6ad4d328282e.png)

**Comment by strgaltdel** [comment]
hmm
terminator went through the code and told "i'll be back?"

running X20 Sim 1.3.2
GPS Coordinates in telemetry page are like mentioned above,

but 
   local lat = system.getSource({name="GPS", options=LATITUDE})
   local lon = system.getSource({name="GPS", options=LONGITUDE})
   print("LAT,LON", lat:value(), lon:value())"

outputs
   LAT,LON 242.8001        242.8001


![latlon](https://user-images.githubusercontent.com/20392683/191912370-6191d465-5e16-4cdf-bcae-018427367e8f.png)
