### ISSUE TITLE
Request: add more sources in OR & AND Logic switches

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1232]
I like to request the following.

In multiple models I use OR and AND logical switches.
Some of them are stacked OR's that means due the limitation of max 2 sources, i need to add multiple OR functions to create a or function for 4 sources.

What I like to request is:
Add the option in OR and AND function to select how many source inputs you want to use, with the default of 2.
Same principle as selecting Outputs in the mixer.

This can be applied for both OR & AND Logic switches.

**Comment by bsongis-frsky** [comment]
Not the highest priority, but it's a good idea

**Comment by loetefix** [comment]
Good idea
