### ISSUE TITLE
Timer reset not possible

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1233]
If you set only minutes and seconds the reset is working. If you set hours reset is not possible. First video show it with setting "down" and second video with setting "up".

https://user-images.githubusercontent.com/16795828/146916204-7c746017-f4b4-4dad-bf61-4b0cfd59dc28.mp4

https://user-images.githubusercontent.com/16795828/146916339-25c78f56-bf4a-4f43-84b2-b1cf64d8b1da.mp4

**Comment by bsongis-frsky** [comment]
What is the start value of your Timer, not 01:07:00?
