### ISSUE TITLE
CATEGORY_TELEMETRY  enum inconsistent

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1235]
RxBatt = system.getSource({category=CATEGORY_TELEMETRY, member=4}) --Rxbatt
On english sim returns 5.4V (RxBt)
On my X20 returns 0

RSSI = system.getSource({category=CATEGORY_TELEMETRY, member=0}) --RSSI
on sim returns 33 (actual RSSI)
on my X20 returns 0

upon investigation, it looks like  CATEGORY_TELEMETRY enum is determined by the order the sensors were discovered.  i think this is wrong and should be a permeant enumeration.

in any case we need a method to get.source of specific sensor in all languages radio - maybe according to sensor ID somehow else?
maybe assign global names for sensors and have them readable in all languages?

for example: 
if i use "RxBatt" in my widget, in the german radio its called "Empf.Bat." and is not read.
writing every widget with 10 language options is a huge headache, not to mention some fonts are very hard (such as CN version)

**Comment by bsongis-frsky** [comment]
member is the index of the sensor in the list, it won't be a permanent enumeration, it has no sense
using the appId is not terrible as well as it can be changed by the user
also please keep in mind that you may have 2 GPS, 2 RxBatt, etc.

**Comment by i3dm** [comment]
so what would you suggest as a solution?
making a widget with telemetry for multi language will be nearly impossible.

maybe allow some sort of generic sensor nsmes (the english ones?) that ethos will know to link to the right sensors in every language?

or simply leave sensor names in english for all languages?

**Comment by yaapu** [comment]
@i3dm perhaps never make assumptions and always force users to select sensors from the widget config menu?

**Comment by i3dm** [comment]
> @i3dm perhaps never make assumptions and always force users to select sensors from the widget config menu?

what do you mean force users to select from the widget config menu? how?

**Comment by Hobby4life** [comment]
![afbeelding](https://user-images.githubusercontent.com/55426642/146995033-c0b1076c-4ba5-4e52-9202-0a2903751a2a.png)

**Comment by i3dm** [comment]
im not  sure i understand why i need to force anybody to do anything.. can you explain?

**Comment by Hobby4life** [comment]
> 

What are the names of the sensors you use? a list?

**Comment by i3dm** [comment]
RSSI
RXbatt
RBOX V1
RBOX V2
RBOX A1
RBOX A2
RBOX C1
RBOX C2
RPM
Temp 1
Temp 2
ADC 2
ADC 3
ADC 4
0A10
0A20

i think these are all...

**Comment by Hobby4life** [comment]
![afbeelding](https://user-images.githubusercontent.com/55426642/146995860-8b8008dd-9e2e-4c14-9476-4fed1fd5e438.png)

**Comment by Hobby4life** [comment]
So user always configurates his widget correctly

**Comment by i3dm** [comment]
> ![afbeelding](https://user-images.githubusercontent.com/55426642/146995860-8b8008dd-9e2e-4c14-9476-4fed1fd5e438.png)

is that a drop down where the user picks each sensor from the list of currently available sensors in Ethos?

if so can you upload an example?

**Comment by Hobby4life** [comment]
> 

yes, check gauge.lua  source input

**Comment by i3dm** [comment]
Its a possibility, but a bit of a head ache for the user to be honest.

**Comment by agibson2** [comment]
It is a pain if you change the widget by mistake... maybe a dialog or something to keep the widget from changing would prevent most of those accidents (I did it once during my testing and was a paint to reconfigure things).

"Warning... changing Widget will reset widget config.  Change anyway? ENTER to confirm"

As much as configuration can be a pain for users, It really is necessary to also agree that having them specify sensors I think to make sure it is configured as the user expects.

**Comment by i3dm** [comment]
> It is a pain if you change the widget by mistake... maybe a dialog or something to keep the widget from changing would prevent most of those accidents (I did it once during my testing and was a pain to reconfigure things).
> 
> "Warning... changing to a different Widget will reset widget config. Change anyway? ENTER to confirm"
> 
> As much as configuration can be a pain for users, It really is necessary to also agree that having them specify sensors I think to make sure it is configured as the user expects.

I agree

**Comment by bsongis-frsky** [comment]
Examples:
`system.getSource("RSSI")`
`system.getSource({name="GPS", options=LATITUDE})`
`system.getSource({category=CATEGORY_TIMER, member=1, options=0})`
`system.getSource({category=CATEGORY_SYSTEM, member=MAIN_VOLTAGE})`
`system.getSource({category=CATEGORY_SYSTEM_EVENT, member=RSSI_LOW})`
`system.getSource({category=CATEGORY_TELEMETRY, appId=0x0F10})`
`system.getSource({category=CATEGORY_TELEMETRY, appIdStart=0x0F10, appIdEnd=0x0F1F})`

**Comment by i3dm** [comment]
> Examples: `system.getSource("RSSI")` `system.getSource({name="GPS", options=LATITUDE})` `system.getSource({category=CATEGORY_TIMER, member=1, options=0})` `system.getSource({category=CATEGORY_SYSTEM, member=MAIN_VOLTAGE})` `system.getSource({category=CATEGORY_SYSTEM_EVENT, member=RSSI_LOW})` `system.getSource({category=CATEGORY_TELEMETRY, appId=0x0F10})` `system.getSource({category=CATEGORY_TELEMETRY, appIdStart=0x0F10, appIdEnd=0x0F1F})`

sorry but your example is totally unclear to me.
can you explain it please?

**Comment by agibson2** [comment]
Can we put in a request for a dialog when changing the script if there are any config settings for the one already configured (assuming that can easily be found out... otherwise only prompt the first time the user makes a change before going out of the script selection)?  Mistakenly changing it can be a big problem trying to remember how you set it up if it has been a long time (or you have memory like mine :)).
