### ISSUE TITLE
MODEL IMAGE screen

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1237]
Hello,

The model image doesn't change the scale in different layout

![image](https://user-images.githubusercontent.com/27886942/147135917-e835f4e2-128b-4b16-987f-efee901bd84f.png)

**Comment by bsongis-frsky** [comment]
Yes it scales, but to the biggest factor X or Y, not the lowest. Then the bitmap is cropped

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/148570423-08ea0fe2-7de7-4e26-8aa4-0586486f28bb.png)

**Comment by aviat40** [comment]
What could be the best to fit as closest as possible with any layout ?

**Comment by bsongis-frsky** [comment]
you may change your bitmap to fit to your model bitmap widget
