### ISSUE TITLE
Make Custom Sensor discoverable by "discover new sensors"

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1238]
This is relevant for all version of Ethos:

1. Please allow discovery of custom sensors simply by clicking "Discover New Sensors" (like in Opentx).
as of now for example sensor 0A10, you have to go to "Create DIY Sensor" and "Auto-Detect" which makes no sense at all, as this is an s.port sensor just like any other, and should be discovered immediately.

2. when a custom sensor is discovered, please give it a proper unique name (best to use the ID as sensor name), right now if i have 0A10 and 0A20, they are both discovered as "DIY Sensor" which will create issues with LUA unless they are renamed manually. 
would be much better if they are automatically named "DIY Sensor 0A10" / "DIY Sensor 0A20" upon "Discover new sensors" or something like that.

**Comment by bsongis-frsky** [comment]
1. No. This sensor is not known and specified by FrSky, it's a custom sensor, you have to detect it and give it a name

2. It makes sense to me, only if the name has not been changed by the user before (default name)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/147220082-e6468955-3d24-4ed3-9935-235a64cea1b5.png)

**Comment by i3dm** [comment]
> ![image](https://user-images.githubusercontent.com/50834778/147220082-e6468955-3d24-4ed3-9935-235a64cea1b5.png)

thats much better.
now about #1 - if these sensors are clearly specified as "DIY Sensor XXXX" then why not discover them normally? clearly they are DIY :)
