### ISSUE TITLE
Telemetry: custom sensor value multiplication

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1239]
All X20 versions: Found a problem with the factor of custom sensors.

im using (and so do many other sensors on the market) 0x0A10 sensor for fuel quantity, a good maximum value for this sensor could be 10,000 ml as models dont typically use more than 10L of fuel.
In X10S / Opentx:
if sending a value of 345600 to s.port sensor 0x0A10, value on telemetry screen is 3456 ml (factor 1/100) or 3.456 Liters.

on Ethos / X20, send the same value, the display value on screen is 10000 (max protocol value for this sensor?)
in order to display the same value 3456ml as before i have to send the value 3456 (factor 1), rather than 345600 (factor 1/100) as before. This causes an issue with all existing telemetry systems who use custom sensors.

seems this issue is due to addressing this value as fuel % (1% = 0.01 of the quantity) vs. actual quantity (in ml). 
3 options to fix (according to preference):
1. match X20 / Ethos to the same factor as it had in X10 Otx (**best**), meaning 345600 shows as 3456 on telemetry (devide module fw report by 100).
2. allow a built in factor in ethos for custom sensor values, so that 345600 can automatically be divided by 100 to 3456.
3. increase protocol limit from 10k to 1M. that way we can divide by 100 in the lua, but sensors who dont use lua will still suffer from this issue in this option.

otherwise all telemetries who use this value have to be physically changed.

**Comment by i3dm** [comment]
i think this issue may be related:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/984

**Comment by bsongis-frsky** [comment]
0x0A10 is a DIY sensor, you have to configure everything, including the range in the DIY Sensor screen
It seems that you have to set the Protocol Precision / Unit to 0.00 ml
Again this is not the standard in S.Port spec, you should use the right appId, not 0x0A10

**Comment by i3dm** [comment]
> 0x0A10 is a DIY sensor, you have to configure everything, including the range in the DIY Sensor screen It seems that you have to set the Protocol Precision / Unit to 0.00 ml Again this is not the standard in S.Port spec, you should use the right appId, not 0x0A10

Youre right changed to 0.00 format and that fixed it.
can you make this the default for custom sensors? as to match older systems without having to manually configure.
that would be great.

**Comment by aviat40** [comment]
I think ETHOS must not change any info from the sensors.. The job has to be done in the Lua if you want any other format.
Or if necessary within the sensor option by the user.

**Comment by i3dm** [comment]
> I think ETHOS must not change any info from the sensors.. The job has to be done in the Lua if you want any other format. Or if necessary within the sensor option by the user.

its ok not to change value.
but default to 0.00 format to match past systems is a good thing.
