### ISSUE TITLE
Heli mix produce wrong walues.

### ISSUE THREAD

**Issue by prikrylm** [FrSkyRC/ETHOS-Feedback-Community#124]
ETHOS v1.0.3 on X12S.
The helicopter mix for the swhash plate makes a "square" instead of a "circle", ie ELE fully forward, AIL neutral gives a full deflection of the swash plate say 30 °, a full simple deflection to the right (AIL full right, ELE center) also gives a swash plate deflection of 30 °, but AIL full right and ELE full forward, ETHOS will produce a deflection of 1.41x greater (~ 42 °), the correct should be again those 30 °. It doesn't matter much with FBL units, they corrects the deflection themselves, but it's bad for mechanical (paddle) helicopters.

**Comment by prikrylm** [comment]
The same is -> https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/144

**Comment by Hobby4life** [comment]
I have noticed a weird thing too.. using the trims will trim all outputs the same direction.. pitch up or down..
Example if I trim elevator forwards, on a HR3 swash. only 2 front/back have should move the same way.. and the single one moves the opposite.. all now go the same way.

**Comment by mawzthefinn** [comment]
Is this behaviour still present on newer firmware? If so, I think #144 is probably the fix.

**Comment by prikrylm** [comment]
Did not check newer FW, but if Ringlimiter is presen in newew version, problem is probably solved.
