### ISSUE TITLE
Add examples to the Lua documentation

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#1240]
Please add examples to the Lua documentation.

For those of us who are not professional programmers, it is difficult to understand how to use the information supplied in the present Lua documentation. A simple example, one that is included in a working program, would be great.

An examples might look something like this
![docs-examples](https://user-images.githubusercontent.com/6865267/147259754-a3039e9e-17c9-4f90-88e0-131cef2ca6ee.jpg)
:

**Comment by Hobby4life** [comment]
I agree. For people that want to write lua scripts. Studying lua only is not enough. We need more simple examples.

**Comment by aviat40** [comment]
Agree also, need more details or exemples with some specifics uses

**Comment by i3dm** [comment]
totally agree

**Comment by bsongis-frsky** [comment]
More examples added. 
Full scripts added here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua
