### ISSUE TITLE
LUA - The DEFAULT selection in addNumberField() function is not working

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#1241]
How is DEFAULT selection used in the form.addNumberField() function? Its name would indicate it is used to return a preset default value when selected.

![edit bar](https://user-images.githubusercontent.com/6865267/147295972-e0232b36-3df7-43ce-b81d-6d2514d79eb9.jpg)

The initial value is entered as a variable which is used when the script is first ran.

local function create()
return {color=lcd.RGB(0xEA, 0x5E, 0x00), source=nil, min=-1024, max=1024, value=0, mlt=1, goColor = (GREEN), cautionColor = (YELLOW), stopColor = (RED), **warning = 39**, lowcutoff = 15}
end

However, if DEFAULT is touched in the edit bar, the value goes to 1, which was set as minimum.

-- warning value
line = form.addLine("Warning %")
form.addNumberField(line, nil,1, 100, function() return widget.warning end, function(value) widget.warning = value end);

How can I make this go to a default value of 39 when DEFAULT is selected?

**Comment by bsongis-frsky** [comment]
`default(...)` method added in alpha14
