### ISSUE TITLE
Request: LUA: please add example of individual cell voltages

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1243]
Reading individual cells voltages from mlvss ("Lipo") sensor is automatically in "Lipo" widget in X20.
but this widget code is not accessible as an example as its part of the Ethos OS.

im currently developing a "Cells" widget for Ethos and need to read these voltages in my LUA.
please add an example showing how to read individual cell voltages from "Lipo" sensor.
thanks.

**Comment by aviat40** [comment]
[main.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7775671/main.zip)

This was for X12s, so may be you can check and try to use it

**Comment by i3dm** [comment]
> [main.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7775671/main.zip)
> 
> This was for X12s, so may be you can check and try to use it

is that for Opentx?
i need an example of how to read these sensors on Ethos

**Comment by i3dm** [comment]
On the Sim:

LipoSensorVoltage   = system.getSource(LipoSensor)
	LipoSensorValue = LipoSensorVoltage:value()

returns 6.4V

LipoSensorVoltage   = system.getSource(LipoSensor[i])
	LipoSensorValue = LipoSensorVoltage:value()

returns 0.0V regardless of i value.

**Comment by bsongis-frsky** [comment]
Example added to the examples directory

![image](https://user-images.githubusercontent.com/50834778/148391955-59625c58-2ca7-49e5-b82f-b9f85cab2508.png)

**Comment by i3dm** [comment]
Just tested the example and got errors:

![image](https://user-images.githubusercontent.com/8968780/148766109-cca03722-d22e-4b67-8d18-eb7bfacecafd.png)
