### ISSUE TITLE
Able to leave a receiver turned on accidentally

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1244]
When the tx is connected to an rx, if you try to turn the tx off you get a warning that the'receiver is still on' so you can't accidentally leave a rx turned on. 
By contrast, switching to a new model (rx) gives no warning that the tx is already connected to a rx.
This seems an oversight and could leave a rx being left turn on by accident. 
I believe that if a new model (receiver) is selected while one is already connected, that a similar 'receiver is still on' message should be issued - which could be bypassed via a confirmation screen. 

This happens in latest release 1.0.14

**Comment by bsongis-frsky** [comment]
Fixed in alpha14
