### ISSUE TITLE
Similar long model names are impossible to distinguish between 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1245]
If you create two similarly named models, which only differ at the end of the name, it is impossible to distinguish between them from the model selection screen. 
 
This screen grab shows two models similarly named, 'thisisalongnam1' and 'thisisalongname2'  each name being 15 characters long, however only the first 13 chars are visible. 

All 15 chars of model names should be displayed. 

![image](https://user-images.githubusercontent.com/96293240/147466706-b4ab5d0a-ee33-41ca-8fd0-8cf278628443.png)

This is using the simulator 1.1.0-alpha2 and is also present on release 1.0.14

**Comment by agibson2** [comment]
I brought up the possibility of scrolling long names in another issue that dealt with long names.  Have it show what it can and then slowly scroll the long name to reveal the entire thing, and then go back to showing the first part.  Pause for a few seconds and then repeat.
As I mentioned in the other issue though.  This would likely not be trivial to implement and I have no idea how much load that would place on the CPU to do it.  It is easy to come up with ideas... can be much different to implement :).

**Comment by Jedsters** [comment]
As I see it, the problem here is that of trying to display an approx square image together with a long name. Opentx does this better with a smaller screen, managing to get 8 model names - albeit without proper images. I know we are all different, but I'd be happy with a small image if we could similarly have 8 models per page. If the selected model icon wasn't enlarged as above I reckon there is room for 10 images over 2 rows, with the name being below the image perhaps in a similar font to that used for 'Model Type Airplane'. 
An easy workaround would be to simply add the model name above Model Type Airplane in the same font - loads of room then!  Hopefully at a later stage more models could then be added to the single page. 

Opentx version
![image](https://user-images.githubusercontent.com/96293240/147818107-f7298513-97f0-4941-b469-5e20639c922c.png)

**Comment by Jedsters** [comment]
Unstale
