### ISSUE TITLE
Slowing transition between flight modes.

### ISSUE THREAD

**Issue by prikrylm** [FrSkyRC/ETHOS-Feedback-Community#125]
ETHOS v1.0.3 on X12S
A slow transition between flight modes is almost essential for helicopters. And without this feature, it is not a good transmitter today.

**Comment by aeroplanebelg** [comment]
A slow transition between flight modes is almost essential for helicopters , gilders and planes .I agree with you, it's essential !!!!
good see.!! x12s os1.0.3
thank you.

**Comment by PribylV** [comment]
I agree. I also consider this feature to be very important.

**Comment by bsongis-frsky** [comment]
Duplicate of #93

**Comment by seilfly** [comment]
![Flight Mode su_sd](https://user-images.githubusercontent.com/12104820/132693095-263797ef-761d-4c15-855d-5722717ed75c.png)

**Comment by seilfly** [comment]
Every time I request such a function, it is closed afterwards. Why?. There are many who want this !

**Comment by Adelaxie** [comment]
It's duplicated with #93 which as replied above.
Follow #93 for more progress, please!
@seilfly
