### ISSUE TITLE
Long logical switch names corrupt display

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1250]
When using long logical switch names, they over-write the Summary as below

Long name
![image](https://user-images.githubusercontent.com/96293240/147478205-702981f0-1183-490d-ab65-54dc462fec4d.png)

over-writes Summary
![image](https://user-images.githubusercontent.com/96293240/147478228-203c7a6f-48f2-4bf3-b3c9-7cfcafa5200d.png)

On release 1.0.14 and Simulator at 1.1.0-alpha2

**Comment by OldGazer** [comment]
Have you ever thought that perhaps the "issues" you are having are self inflicted because you are simply using too many characters?  Look at it this way.  We only so much display area/memory to use. What you are  trying to do is put 10 gallons of water into a 5 gallon bucket.

**Comment by Jedsters** [comment]
I've just noticed this looks like a duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1128

**Comment by agibson2** [comment]
It would be neat if it scrolled longer names.  Pause for a few seconds and then scroll them again repeatedly.  Probably not trivial to code such a thing though and I have no clue if that would consume too much CPU to do.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/147947525-56e7bc98-7104-4e03-8f0e-77a7e7b73f4b.png)
