### ISSUE TITLE
Unable to see Repeat Interval on SF while updating it

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1252]
Create a special function
Select Action of 'Play Track'
Scroll down to 'Repeat' 
once you select Repeat, the Min-Default+Max bar over-writes the repeat value so you can't see what the value is while you are changing it. See below. 
I am guessing that this bug crept in when a volume bar was added(?) below min-default+max. I suspect the easy solution is you move min-default+max to the left and move the volume bar to the right of it so you only need one row for both. 

Curiously, if you save the new SF and go back into edit the SF , when you then select the Repeat value, it moves up so you can then see what the value you are changing is, so this does appear to just be a problem at creation of a new SF.
Applies to 1.0.14 and Simulator 1.1.0-alpha2

![image](https://user-images.githubusercontent.com/96293240/147490197-ab04ca25-04cb-46b3-aa42-a777ac3a6786.png)

**Comment by bsongis-frsky** [comment]
Already fixed

**Comment by Jedsters** [comment]
Can you advise which release fixes this please?
Thanks.
