### ISSUE TITLE
Custom trim values may not report trim centre if not a power of 2

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1253]
Select Trims, then e.g. Trim Rudder and change the Trim Mode to Custom and select a value which is not a power of 2, e.g. 3. 
Increase the rudder trim until 'max reached' now decrease the trim keeping hold of it. The next report is 'min reached' and it is now impossible to determine where 'trim centre' is. This appears to be the case for all custom trim values which are not a power of 2 (i.e. not 2, 4, 8, 16 etc.).
I guess the 2 reasonable solutions are either to only make custom trim values which are a power of 2 available or detect trim centre when it is approached and select it in the same way as max and min are detected and selected so it can always be found and selected.
This is on 1.0.14.

**Comment by bsongis-frsky** [comment]
Fixed in 1.1.0 alpha14
