### ISSUE TITLE
Order of updates

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1254]
In what order should the latest updates be made?  First 1.0.15 and then 1.1.10 alpha 12 or vice versa or does it matter?

**Comment by Hobby4life** [comment]
1.0.15 is officicial release without Lua, and v1.1.0 is Alpha with Lua, but same fixes as v1.0.15 from what i have seen.

**Comment by EngelMT** [comment]
No, there differences. 1.0.15 has more bug fixes. For excample ail>rud mixer.

**Comment by Hobby4life** [comment]
> 

Hmm I dont know, but are these not already fixed in one of the Alpha releases?, And therefore not mentioned?

**Comment by ronron84** [comment]
i have to use  1.1 to keep my model when i put 1.0.15 l have a message to update the firmware and all my model are gone.

**Comment by bsongis-frsky** [comment]
> No, there differences. 1.0.15 has more bug fixes. For excample ail>rud mixer.

This is wrong, this fix comes from a previous alpha

**Comment by bsongis-frsky** [comment]
> i have to use 1.1 to keep my model when i put 1.0.15 l have a message to update the firmware and all my model are gone.

1.1.0-alphaX are alpha releases, just for testing, if you want / need to return to 1.0.15 you have to use the backup of your models
