### ISSUE TITLE
1.1.0 alpha12 X10-ISRM RTC Warning

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1255]
I get an RTC battery warning when I switch on, even though the voltage is at 3V and the alarm is switched off.

https://user-images.githubusercontent.com/85410070/147497600-3dc63918-7307-4bcd-b48f-38eedf99fc60.mp4

**Comment by Hobby4life** [comment]
Noticed on all radio's,  even simulator

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.16 / 1.1.0-alpha13
