### ISSUE TITLE
LUA - 1.1.0 alpha 12 simulator - storage.readInteger() and/or storage.writeInteger() not working

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#1257]
The read/write functions are no longer working in Ethos 1.1.0-alpha12 simulator. I have not tried in the transmitter.

In the following script, the color chosen by the color picker works normally but reverts back to the initial color of (0xEA, 0x00, 0x00) when the simulator is closed and then reopened. This indicates the color values are not being saved and/or read correctly when the sim is closed and then opened again. These functions worked normally in the alpha 11 simulator. 

-- Color2 widget

local translations = {en="Color2", fr="Couleur2"}
local function name(widget)
    local locale = system.getLocale()
    return translations[locale] or translations["en"]
end

local function create()
    return {color=lcd.RGB(0xEA, 0x00, 0x00), value=0}
end

local function paint(widget)
    local w, h = lcd.getWindowSize()

    -- Define positions
    if h < 50 then
        lcd.font(FONT_XS)
    elseif h < 80 then
        lcd.font(FONT_S)
    elseif h > 170 then
        lcd.font(FONT_XL)
    else
        lcd.font(FONT_STD)
    end

    local text_w, text_h = lcd.getTextSize("")
    local box_top, box_height = text_h, h - text_h - 4
    local box_left, box_width = 4, w - 8

    -- Color box
    lcd.color(widget.color)
    lcd.drawFilledRectangle(box_left, box_top, box_width, box_height)

    -- Color box frame outline
    lcd.color(RED)
    lcd.drawRectangle(box_left, box_top, box_width, box_height)

end

local function configure(widget)

    -- Color
    line = form.addLine("Color")
    form.addColorField(line, nil, function() return widget.color end, function(color) widget.color = color end)
end

local function read(widget)
    widget.color = storage.readInteger()
end

local function write(widget)
    storage.writeInteger(widget.color)
end

local function init()
    system.registerWidget({key="color2", name=name, create=create, paint=paint, wakeup=wakeup, configure=configure, read=read, write=write})
end

return {init=init}

**Comment by Hobby4life** [comment]
--[[
local function read(widget)
    widget.source_pitch = storage.readSource()
    widget.source_roll = storage.readSource()
    widget.pitch_min = storage.readNumber()
    widget.pitch_max = storage.readNumber()
    widget.roll_min = storage.readNumber()
    widget.roll_max = storage.readNumber()    
    widget.color = storage.readInteger()
    widget.hud_size_h = storage.readNumber()
    widget.hud_size_w = storage.readNumber()
end

local function write(widget)
    storage.writeSource(widget.source_pitch)
    storage.writeSource(widget.source_roll)
    storage.writeNumber(widget.pitch_min)
    storage.writeNumber(widget.pitch_max)
    storage.writeNumber(widget.roll_min)
    storage.writeNumber(widget.roll_max)    
    storage.writeInteger(widget.color)
    storage.writeNumber(widget.hud_size_h)
    storage.writeNumber(widget.hud_size_w)
end

--]]
local function read(widget)
    widget.source_pitch = storage.read("source_pitch")
    widget.source_roll = storage.read("source_roll")
    widget.pitch_min = storage.read("pitch_min")
    widget.pitch_max = storage.read("pitch_max")
    widget.roll_min = storage.read("roll_min")
    widget.roll_max = storage.read("roll_max")    
    widget.color = storage.read("color")
    widget.hud_size_h = storage.read("hud_size_h")
    widget.hud_size_w = storage.read("hud_size_w")
end

local function write(widget)
    storage.write("source_pitch",widget.source_pitch)
    storage.write("source_roll",widget.source_roll)
    storage.write("pitch_min",widget.pitch_min)
    storage.write("pitch_max",widget.pitch_max)
    storage.write("roll_min",widget.roll_min)
    storage.write("roll_max",widget.roll_max)    
    storage.write("color",widget.color)
    storage.write("hud_size_h",widget.hud_size_h)
    storage.write("hud_size_w",widget.hud_size_w)
end

**Comment by dwheel** [comment]
Thank you. Will close this issue.
