### ISSUE TITLE
RTC Battery Low Warning on new battery. 1.0.15

### ISSUE THREAD

**Issue by cperedamas** [FrSkyRC/ETHOS-Feedback-Community#1258]
I updated to 1.0.15.  I got the RTC battery low warning on the first boot after the update.  I changed the battery.  The RTC battery voltage now reads as 3.2 on the battery page.  However, I still get the warning, "RTC Battery Low" after each boot.

**Comment by greggibbons** [comment]
Same issue for me. After I loaded 1.0.15, I replaced the RTC battery with a CR1220. It now reads 3.2V but I get the low RTC battery warning. I turned the X20 and on and off several times, still get the warning on each power up.

**Comment by Jetxrc** [comment]
Same issue as above, replaced battery also still warning low voltage shows 3.2

**Comment by Hobby4life** [comment]
Duplicate #1255

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.16 / 1.1.0-alpha13

**Comment by Scout339** [comment]
Im getting this after a new firmware flash for my Taranis X-Lite. v2.2.2 (no issues) to v2.3.9.

**Comment by bsongis** [comment]
@Scout339 This repository is about Ethos, not OpenTX!

**Comment by Scout339** [comment]
Whoops! Disregard.
