### ISSUE TITLE
In 1.0.15 When I turn on the radio, it asks me to calibrate all the potentiometers and all the models disappear .

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#1259]
After to update to 1.0.15 When I turn on the radio , it asks me to calibrate all the potentiometers and all the model disappear. My radio is X20 in FLEX system

**Comment by WismyYao** [comment]
Is your previous version 1.0.14 ?

**Comment by bsongis-frsky** [comment]
Perhaps you installed 1.1.0-alphaX before?

**Comment by bsongis-frsky** [comment]
Duplicate of #1254 
Feel free to reopen if needed

**Comment by jasalca** [comment]
I understand what happened.My previous was 1.1 alpha 12 and I wanted to move on to 1.0.15. and I see that if you don't have a backup from 1.0.14 you can't. Thanks
