### ISSUE TITLE
Strange values of curve points.

### ISSUE THREAD

**Issue by prikrylm** [FrSkyRC/ETHOS-Feedback-Community#126]
ETHOS v1.0.3 on X12S
After turning the transmitter off and on or switching the model, strange values of curve points appear when editing existing curves. For a curve created as a three-point 100 - 0 - 100, I see points -157 - -256 - -156. The curve in the mixer works properly.

**Comment by bsongis-frsky** [comment]
Already fixed for 1.0.4
