### ISSUE TITLE
Limited model categories

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1261]
Please could we have more flexibility over model categories (similar to opentx). 

Abililty to move models between categories. 
Ability to rename categories. 

e.g. I neither fly helis nor multi, but I do fly electric gliders, so it would be useful to be able to repurpose helis for that and then to be able to copy an existing template into that category so I can modify it as a new template rather than having to start from scratch.

Thanks.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/149971965-f08ad30b-e643-48e9-8954-aa8eca7314d8.png)
