### ISSUE TITLE
Output channels always start on channel 1

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1262]
While editing mixers, it is possible to press and hold an output channel which takes you directly to the Outputs which is a useful feature. However it seems a little odd that if I select and hold e.g. Ch31 that I'm taken to the first output screen, wouldn't it make more sense to take me to the screen containing ch31?

Thanks

**Comment by bsongis-frsky** [comment]
Fixed in alpha14
