### ISSUE TITLE
Request: Adjustable PPM Centre

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1264]
On opentx it is possible to adjust the servo PPM centre as per image below. This changes the entire arm throw, e.g. a normal setup gives 1500microsecs as centre with min around 988 and max around 2012.  If the PPM centre is changed to 1520 then we get min around 1008 and max around 2032. 
By contrast, if subtrim is used, then this only changes the 1500 value. 

If this feature were made available, it would make it much easier for people to convert models from other tx (especially using opentx) if they use this approach together with curves for setting out outputs for control surfaces. 

![image](https://user-images.githubusercontent.com/96293240/147563486-a5060ee5-b983-499e-995c-8270d7445355.png)

Thanks

**Comment by agibson2** [comment]
Thanks for creating this.  I am hopeful the developers create this feature in the future after more pressing issues are fixed.  It also allows your endpoints to stay at +100% and -100% for easier reference of where the endpoints are at if you need to tweak them.  I use ppm center for servo centering and then endpoint adjust to move the endpoints in from there.  It makes it easy to get back to your original 100% -100% endpoints in case you need to change your endpoints later.  If you just use subtrim and move the endpoints to match, your endpoints are now not easy to calculate because they are not 100% -100%.  If you need to adjust servo center again, with subtrim only, you have to also adjust endpoints to match which is very error prone for me.

**Comment by guycnicholas** [comment]
@Jedsters I think you are slightly mistaken about how subtrim/PPM center work, here is a link to a page that describes the nuances of it: http://open-txu.org/home/undergraduate-courses/basic-airplane-set-up-with-taranis-2/servos-713/
Second, Ethos allows you to adjust the center and the throws.
Referring to the image below, if you want the red line behavior, go to the output page and change the Center/Subtrim setting. At this point the endpoints haven't moved, but the travel will be different on either side of the stick.
If instead you want to shift the center as in the green line, then you would first adjust the Center/Subtrim, then adjust the endpoints by the amount of the center shift. For example, if the center moved to 10% you would adjust the Max to 110% and the Min to 90%.  There is math involved, and perhaps something in the UI could be changed to make it better, but I believe it currently does everything you need it to do....of course, perhaps I am missing your point.

![image](https://user-images.githubusercontent.com/5494702/148094275-cc1e8da7-a572-42e6-877f-a5cca6824b49.png)

**Comment by agibson2** [comment]
The point is the math gets confusing if you ever need to go back and adjust things again.  When you setup your servo throws for physical limits,  I go back in and tweak min and max for the real throws that I want.  If I then go back later to adjust those min/max throws, I would lose reference to my physical limits and would need to keep track of that in a separate document.  PPM center would also simplify moving models from other transmitters that have a ppmcenter without needing to calculate offsets manually for min/max and subtrim.

With ppmcenter, your min/max stay  at 100% to reference physical limits when ppmcenter needs to be adjusted keeping everything linear (ppm center adjusts min/max).  You can then keep those physical limits separate from any tweaks on limits for the throws you really want.  If you want to later come back and tweak those throws, you can start back at 100% for min/max knowing that they are your real physical limits that were setup and adjusted by ppmcenter.

**Comment by Jedsters** [comment]
@guycnicholas I agree with everything you say, including the bit about maths involved. 
The benefit of being able to adjust the PPM centre directly is it avoids that and is more accurate.
e.g. if I'd reduced my max slightly so my centre was at 1500 with min at 1000 and max at 2000 and was to then adjust my PPM centre (opentx style) to e.g. change PPM centre to 1550 then it would take care of everything and I'd now have a min of 1050 and max of 2050.
As you suggest, currently I have to work out (1550-1500)/5.12 = 9.76% then -100+9.76 = -90.24, round up to 90% with a slight inaccuracy  etc. etc. 
When someone (like me) is converting from opentx to Ethos and has used PPM centres a lot it means they have to do that calculation for 6 - 8 curves (so 12 - 16 times) per model across more models than I care to admit to. 
It appears I am not alone in having taken advantage of this feature in optntx. 
Thanks

**Comment by Jedsters** [comment]
I should perhaps add that if someone has adjusted PPM centre and uses subtrim, then the calculation actually becomes quite horrible.

**Comment by oilytin** [comment]
I have always found the ppm centre useful for centering a servo after install when the splines on the horn dont quite line up.

**Comment by bsongis-frsky** [comment]
Done
