### ISSUE TITLE
1.0.16 Cannot adjust time of day

### ISSUE THREAD

**Issue by ajatmiddday** [FrSkyRC/ETHOS-Feedback-Community#1265]
1.0.16 trying to adjust the local time only the seconds can be selected, It looks like the time index is not being indexed because it takes 3 click of the right hand button to deselect the seconds position.

**Comment by hrenz** [comment]
since 1.0.14
it woks but  now only highlighted is the second position

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.17
