### ISSUE TITLE
system.getSource (nil) 	returns a source

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1267]
system.getSource (nil) 	returns a value, seems like the first telemetry sensor value? should return nil.

**Comment by aviat40** [comment]
Why using system.getsource(nil), nil is not a source !!

**Comment by i3dm** [comment]
> Why using system.getsource(nil), nil is not a source !!

of course its not, thats why it shouldnt return a value :)

**Comment by bsongis-frsky** [comment]
It will return a source with CATEGORY_NONE, which is written "---" in the firmware
