### ISSUE TITLE
lua: model.getSensor({appIdStart=XX, appIdEnd=YY}) does not filter based on appId range 

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1268]
local sensor = sport.getSensor({appIdStart=0x5000, appIdEnd=0x50FF})

sensor:popFrame() does not filter based on the provided appId range but returns pretty much anything.
Tested both on the sim and on a the X20.

physId:0x98 primId:0x10 appId:0x0D60 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0xF010 value:0x00000000
physId:0x98 primId:0x10 appId:0x0830 value:0x00005000
physId:0x98 primId:0x10 appId:0x0D20 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0301 value:0x64064060
physId:0x98 primId:0x10 appId:0x0210 value:0x00000320
physId:0x98 primId:0x10 appId:0x0D50 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0800 value:0x8457735F
physId:0x98 primId:0x10 appId:0xF104 value:0x00000068
physId:0x98 primId:0x10 appId:0x0850 value:0x12010500
physId:0x98 primId:0x10 appId:0x0D10 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0850 value:0x29080201
physId:0x98 primId:0x10 appId:0x0D10 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0300 value:0x64064020
physId:0x98 primId:0x10 appId:0xF103 value:0x00000168
physId:0x98 primId:0x10 appId:0x0E60 value:0x00000320
physId:0x98 primId:0x10 appId:0x0100 value:0x00000064
physId:0x98 primId:0x10 appId:0xF103 value:0x00000168
physId:0x98 primId:0x10 appId:0x0D50 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0301 value:0x64064062
physId:0x98 primId:0x10 appId:0x0D40 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0500 value:0x00000168
physId:0x98 primId:0x10 appId:0x0200 value:0x00000168
physId:0x98 primId:0x10 appId:0x0D50 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0D50 value:0xFFFFFFFF
physId:0x98 primId:0x10 appId:0x0D50 value:0xFFFFFFFF

**Comment by bsongis-frsky** [comment]
Fixed in alpha14

**Comment by centertrim** [comment]
@yaapu 
@bsongis-frsky 

Would either of you be able to provide an example of how to use sensor:popFrame() and sensor:pushFrame() please?

popFrame():
If I create a sensor and then do something like:   rxFrame = sensor:popFrame(), I can successfully receive a frame through my sensor filter (like 0x32 from Betaflight MSP).  But when I try to get values from it with  rxFrame:primId() or rxFrame:value() it says that I must pass it a value.  I've tried a few other things to pull the values out of the returned rxFrame and they didn't work either.  The documentation isn't much help here, as it says that the LuaSportFrame class can get & set with those functions and should return the requested value when called.  But I've had no luck actually getting that to work.

pushFrame():
Docs say "SPortFrame" (as opposed to LuaSportFrame for what popFrame() returns), but they don't define what an SPortFrame is actually supposed to entail.  If I pass it some limited subset of values like sensor:pushFrame({primId=0x10, value=0x10)} it doesn't give me an error, but I also can't tell that it's actually doing anything.

Any help / examples with these two functions would be much appreciated.  I've got the sensor part figured out, it's just the popFrame and pushFrame that are being quite annoying.

**Comment by yaapu** [comment]
@centertrim I've been only reading telemetry so far, what I do is

```
local frskySensor = sport.getSensor({appIdStart=0x800, appIdEnd=0x51FF})

local function sportTelemetryPop()
  local frame = frskySensor :popFrame()
  if frame == nil then
    return nil, nil, nil, nil
  end
  return frame:physId(), frame:primId(), frame:appId(), frame:value()
end

```

**Comment by centertrim** [comment]
@yaapu Excellent, thank you!  I don’t know why this wasn’t working for me before, as I had certainly tried something very similar.  Honestly I tried so many things that it’s possible I had a small mistake elsewhere and didn’t realize it at the time.  So thank you for this answer, it got me to double down my efforts in the correct direction.

I think I have just about got pushFrame() working, at least partially.  I can definitely get some packets to send, but I am still in the process of figuring out why other packets won’t send (it seems to happen when sensor:Idle() is false, but I’m not sure why it is changing yet).  Perhaps it is an timing error with something else using that sensor or how I am using it.  I am trying to figure it out, but the back and forth on serial debugging is tedious.

I will follow up on my pushFrame() results soon.

**Comment by savall21** [comment]
Can you share your code for pushframe().  I'm trying to send a simple numerical value to an Arduino board vis SBUS and just looking for a sample.
