### ISSUE TITLE
6-pos switch optinons 1.1.0 alpha12EU

### ISSUE THREAD

**Issue by Marco-seveneleven** [FrSkyRC/ETHOS-Feedback-Community#1269]
Hi, I noticed that in 1.1.0 Alpha12 under "Hardware" the setting options for the 6 pos switch are no longer available. In the 1.0.1RC2 there was the item function switch: "6-Pos with Off", "2x3-Pos"., "6x2-Pos", "toggle".

Can this option be found in another menu or is it missing?

**Comment by Hobby4life** [comment]
I can confirm

**Comment by MIKE-DAILEY** [comment]
It was moved to the bottom of the Edit Model screen so it can be set per model.

**Comment by Hobby4life** [comment]
Aha never noticed it lol, but indeed better place

**Comment by Marco-seveneleven** [comment]
Ok, I've found!
Thank you!
