### ISSUE TITLE
Timer corrupted when switching from count-down to count-up

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#1270]
X20 1.1.0 Alpha 11

1. Create a timer with mode=count down, and alarm = 00.00.10 
2. Edit the timer, set mode=count-up, alarm = 00.00.00
3. Start the timer

Expected: timer should start at 00.00.00
Actual: timer starts at 00.00.10

As an aside, I find the operation confusing, for example what is the meaning of alarm value in count-up mode? If it's not used, it should be greyed out.

**Comment by mawzthefinn** [comment]
This should be fixed in 1.4.4, I just checked.

Alarm in Up mode will count up to the alarm value, with time elapsed instead of time remaining, as of 1.4.5

**Comment by mawzthefinn** [comment]
This is fully addressed as of 1.4.5
