### ISSUE TITLE
Models cannot be recognized by their logical names in SD

### ISSUE THREAD

**Issue by tessler1015** [FrSkyRC/ETHOS-Feedback-Community#1271]
In order to manage (backup and restore) models on SD, we need to recognize the model by it's name rather than "Model01", "Model02" Etc...it would be nice to name the file using the logical model name *as it apear in the Transmitter*

**Comment by agibson2** [comment]
I look at the filename in the model select screen and then just manually rename it on the SD card.

**Comment by i3dm** [comment]
good idea

**Comment by 00steven** [comment]
> I look at the filename in the model select screen and then just manually rename it on the SD card.

That is a workaround but we want to help and create a user-friendly operating system. The right model name on the sd card shouldn't be something you need to do manually

**Comment by Hobby4life** [comment]
1. I think there is also a limit of characters on filenames in some areas of the filesystem.
2. I dont think we must mess with anything in the models folder at all. If things are done wrong there you complete model setups will be corrupted.

Better is a Import/Export function that allows you to Import custom named model files.
ETHOS will eventually place them in the right order in the models folder.
Same goes for Exporting.. Exports and Imports should go to a specific folder on the SD card.
These files you can backup on your PC.

**Comment by Robyorks** [comment]
Updated from .14 to .17, lost al my electric models. Weirdly kept all my ic/petrol powered stuff. They are al still on the memory card, just not available to choose from so an import option would be great!

PS: I have twenty three models on there.

**Comment by Billy60** [comment]
I had exactly the same issue, I had to reprogram all my power planes, it had kept only the (glider' category). they also were on the SD but not available. 
Then the upgrading: had to go back to 1.0.11 and then to 1.0.14 and finally to 1.0.17.  
there is indeed a problem here.

**Comment by mawzthefinn** [comment]
Fixed in 1.2.11 onwards

**Comment by bsongis-frsky** [comment]
In 1.4.4 when the user changes the Model Name. The Model Filename will be modified

Link with #1782
