### ISSUE TITLE
Improve releases page for non-techies

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1272]
For ETHOS downloads, the FrSky web site directs people to the releases page here. I totally understand why, as you guys have been releasing updates pretty quickly. I thank you for all your awesome work. 

However, a lot of people coming from FrSky’s site will have never seen GitHub before. Especially as the firmware is easy to use and is attracting people over from other manufacturers, like Spektrum and Futaba.

Initially, this wasn’t a problem, as the top version shown was the latest, stable release. However, now there is a 1.0.x stable release along side a 1.1.x alpha, pre-release. Either of which could be at the top of the page, depending on which has been released last. For people who have an idea about coding or use GitHub, that’s not a problem. But, there will be a higher percentage of people who don’t. A lot of these have downloaded 1.1.x, and have now tried updating with 1.0.17 and encountered problems. 

Is there any way to add a notice to the top of the releases page to tell people to only download the release with the green “Latest” label. It would be good to give some kind of instructions for people who don’t know GitHub. Having the pre-releases on GitHub is very useful. But I think more needs to be done to protect non-developers.

**Comment by aalain8** [comment]
I find your comment very relevant.

On the forums you find more and more people downloading 1.1.X alpha versions without even knowing what they are for.

As MrD-RC says you are doing a great job and normal users should not be able to download a 1.1.X Alpha version.

**Comment by bsongis-frsky** [comment]
1.1.0 alpha releases won't go in the releases section anymore

**Comment by jasalca** [comment]
And now what do we ´normal´ people do that we have already downloaded by mistake the alpha versions?
It's safe to fly????
I can no longer go back to a previous version other than alpha because I lose models

**Comment by bsongis-frsky** [comment]
you have to wait that the weather is nice again, and 1.1.0 is out
I hope we will have release candidates at the end of the week, but I don't want to promise anything
