### ISSUE TITLE
Touch: Adjustment of values can accidentally change step scale

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1273]
I have been accidentally tapping the step scale when trying to hit +, -, min, default, max when adjusting values with the touch interface.  It seems to happen at least a few times a session when trying to adjust some things.  Any chance to move the step/scale adjustment to the right and the +, -, min, default, max buttons to the left so that it would not be easy to accidentally press the wrong thing?  They could also be bigger which would also help.

I think the reason this happens more often for this specific touch areas than with other touch menus is that I am typically trying to keep an eye on the model or some other GUI thing while adjusting the numbers.

Or maybe make the step/scale adjustment a separate button entirely that brings up a menu to set scale?

![2021-12-31](https://user-images.githubusercontent.com/6733850/147805101-3ab8ab04-52b1-4b09-a258-34040d90352d.jpg)

Something like this...

![2021-12-31](https://user-images.githubusercontent.com/6733850/147805397-f2ae5a3d-1112-45ac-b711-edd814cfb2e5.png)

**Comment by Jedsters** [comment]
I agree with your suggestion having found the same. Although I have since found out that you can more easily adjust the 'volume' by using PageUp/Dn button and the Scroll wheel.

**Comment by agibson2** [comment]
I don't see this being needed anymore.  The input of numbers has changed for the better already.  Closing.  Thanks!

**Comment by hrenz** [comment]
V1.5.18
the number entries can still be optimised so that you need fewer clicks
Example attached

![image](https://github.com/user-attachments/assets/b4437147-5ace-4937-a0c2-10a2d831d0e7)

![image](https://github.com/user-attachments/assets/4402e5bd-d240-463a-a385-cff12d9601bc)
