### ISSUE TITLE
Data lost after Udate to 1.10 Alpha 17

### ISSUE THREAD

**Issue by theoml** [FrSkyRC/ETHOS-Feedback-Community#1274]
Stick calibriation had gone and only a few of Models were found from the X20S. I find them with the file.manager but can´t load them

Checked the SD.Card, but it is fine

What happend ?

Regards
Reiner

**Comment by Hobby4life** [comment]
There is no Alpha 17...

If you have switched from v1.1.0 Alpha 12 to v1.0.17 then yes models can be lost.
These are 2 whole different firmwares.

**Comment by theoml** [comment]
There is no Alpha 17...

That was my missunderstanding
