### ISSUE TITLE
Release files missing

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1276]
I would like to ask that releases contain all necessary files rather than just the updated ones.  A user, regardless of their current installed version, should be able to come here, click on the latest release and grab all the necessary files for their radio.  As it stands now, I have to fetch the firmware for my particular radio, and then go back release by release, looking for Flash and SD files until I either find them, or hit the version of software I currently have installed.
Also, I am not sure why there are releases with just the "source code" (which I find an odd name, considering it only contains the manual).  Your 1.1.0 alpha 13 is an example, it says, "coming soon" and only contains the two "source code" files.
My suggestion would be to have a build script setup so that when you want to publish a release, you give it a tag name and some notes, and it pulls together a full set of zip files and makes a commit.

**Comment by bsongis-frsky** [comment]
will be fixed when we have an app, today we have to use only the github way

**Comment by guycnicholas** [comment]
@bsongis-frsky Respectfully I disagree with that approach. One of the items that has plagued FrSky is update issues.  I have seen people get stuck and complain about updates gone wrong.  Now they release a new radio, that has a new and immature OS and this is the only place to get updated to the OS.
I really think asking you guys to just make your releases contain all files rather than just a changeset, is not a big ask, and it will save customers a lot of frustration.
