### ISSUE TITLE
Lua: os.clock() returns seconds on sim and tenths sec on radio

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1277]
I currently need to have a user option to specify if the user is on the sim or not because of the differences with os.clock on the sim vs the radio.

As an example... if 10 seconds after startup, you would get something like 10.123 on the sim.  The radio would return something like 101.234.  Is this because of a limitation with specs on os.clock() that it can't return precision to 0.xxxx?  Is this a bug or expected and if it can't be consistent, can there be a function to report what os.clock() returns?

This is related to an older issue but I reported that older one incorrectly and it was closed because I was reporting on a wrapper function that was created by a script author instead of realizing os.clock() is the native function and it also returns different results on sim vs radio.

**Comment by bsongis-frsky** [comment]
1.1.0 alpha14
