### ISSUE TITLE
XAct Menue faulty

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1283]
Range 90° has the largest travel at the servo. 120° and 180° have a significantly smaller travel. However, 120° and 180° have the same small travel.

It looks like 90° in the menu means 120° in reality. And 120° and 180° only mean 90° in reality. 180° does not exist at all.

**Comment by Hobby4life** [comment]
This is the same issue I have talked about to @WismyYao

**Comment by bsongis-frsky** [comment]
Duplicate of #1176 - Which is not an Ethos issue
