### ISSUE TITLE
Lua: timers... Option to set them to count down using voice

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1286]
I have created a few timers and they beep 11 times when counting down starting from 10... down to 0.  For competition tasks, I need them to use voice for count down.  Counting by beeps is problematic when out on the field so a voice countdown is really needed.

I didn't see any way to set the voice countdown for timers via lua.  Ideally 10 seconds would be adjustable if possible but 10 works well enough for my needs right now.

**Comment by bsongis-frsky** [comment]
You may write your own counting system using Lua:
- system.playNumber(...)
- system.playTone(...)
- system.playHaptic(...)

**Comment by agibson2** [comment]
I guess I am confused.  Timers have the ability to count down in the GUI.  I am only asking for that option to be exposed to Lua.  Maybe I am missing something not knowing how timers work internally.

**Comment by bsongis-frsky** [comment]
Function `audioMode(...)` added

**Comment by agibson2** [comment]
That will great.  Thanks!
