### ISSUE TITLE
Lua: lcd.drawNumber()  RIGHT flag doesn't work

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1287]
When I draw a number using lcd.drawNumber(100,100, 1234, RIGHT) , It draws it with left justification instead of RIGHT.

Example...
lcd.drawText(100,100, "TEST", LEFT)
lcd.drawNumber(100,100, 1234, RIGHT)

The text will be correctly LEFT justified (default it seems) but the number will be drawn LEFT justified and write over the Text.

Using RIGHT flag with lcd.drawNumber() also outputs a W after the number.  I don't know why it does that.

**Comment by bsongis-frsky** [comment]
It seems that writing the doc with examples is still not enough :(

![image](https://user-images.githubusercontent.com/50834778/148030219-113fc698-2f19-413f-bf90-4ecde53409d3.png)
