### ISSUE TITLE
Timers: Countdown beep to play different sound at 0

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1288]
Currently if you setup a countdown timer with the beep option, the beep sound is the same if it is at 5 seconds or 0 is reached.  It would be very helpful if the last beep at 0 would be a lower tone so that you would know when the exact moment it is reached.  If you are just listening to the tones and not counting the beeps, you have to wait an extra second or two until you don't hear the beep to know that the timer expired.

A different tone when the countdown reaches 0 would be very helpful to distinguish when the countdown timer set to use beeps gets to 0.

**Comment by i3dm** [comment]
i agree should be a default sound file like opentx "Timer x Elapsed"

**Comment by agibson2** [comment]
That would be good for voice mode.  Ideally that would be optional though so that you could play your own wave file if needed.
For beep mode though, I think it should just be a lower tone at expiration of the timer.

**Comment by agibson2** [comment]
It looks like opentx does a long beep at 0 instead of a different tone.  Anything to make it clear that 0 was reached for beep.

**Comment by bsongis-frsky** [comment]
"Timer x elapsed" seems to me a bad idea. If you remove Timer1, Timer2 will then become Timer1 and will force the user to rename his audio files

**Comment by i3dm** [comment]
> "Timer x elapsed" seems to me a bad idea. If you remove Timer1, Timer2 will then become Timer1 and will force the user to rename his audio files

thats no issue at all.
you should at least allow a voice file. leave it to the user to rename if needed

**Comment by agibson2** [comment]
This bug report is not about the voice alarm for timer but for the beep mode for timers.  The end beep sound should be distinguishable from the countdown beeps so that you know when it expires.  The end voice thing is a separate issue I think.

**Comment by i3dm** [comment]
> This bug report is not about the voice alarm for timer but for the beep mode for timers. The end beep sound should be distinguishable from the countdown beeps so that you know when it expires. The end voice thing is a separate issue I think.

its the same issue. for timer mode beeps and for timer mode voice.

**Comment by visioneerone** [comment]
> "Timer x elapsed" seems to me a bad idea. If you remove Timer1, Timer2 will then become Timer1 and will force the user to rename his audio files

I requested this exact feature way back in August - https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/821

as i3dm stated - it is silly that we need to add a logic switch & special function to each model memory just to get back a feature  which was "baked-in" to opentx.

**Comment by i3dm** [comment]
Agreed,
and i totally dont understand why timer 2 becomes timer 1 etc.

**Comment by bsongis-frsky** [comment]
@agibson2 Beep will be longer in 1.2.8
