### ISSUE TITLE
Timers: voice countdown from 30 seconds gets behind by a second

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1289]
If you set the countdown timer with voice enabled and set it to countdown for the last 30 seconds,  By the time it gets to 26, it starts getting behind.  Maybe the voice is longer than a second I assume.  By the time it is at 11, it is behind about a second or so.  It does catch up by the time it gets to 7 or so (counting speeds up faster than the timer from 10 to 7), but that really throws off your timing.

This is with English.  I don't know about other languages if that matters.
X20S radio

**Comment by bsongis-frsky** [comment]
OK but there won't be any perfect solution. I will make it play something only if the voice queue is empty, you will get some numbers skipped, unless you record your own voice and speak faster
