### ISSUE TITLE
Logic Switches Descriptions could accommodate more information

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1290]
The Logic Switches gives the name and summary on the left and a description on the right 
![image](https://user-images.githubusercontent.com/96293240/148051953-fb180875-f2fd-46b0-8f6b-62e9f6ac7f98.png)
many switches have a Min Duration which isn't reported on in the description and yet there appears to be room for it. This seems an omission.
Indeed, there even appears to be room for (part of?) the comment field
![image](https://user-images.githubusercontent.com/96293240/148052103-f335bb0c-0e49-48ae-a297-c813ec82b4cd.png)
It seems a shame to have wasted space on the screen when useful information could be presented there.

**Comment by bsongis-frsky** [comment]
it would be a shame to display a empty comment ;)

**Comment by bsongis-frsky** [comment]
1.1.0-alpha14

![image](https://user-images.githubusercontent.com/50834778/148054076-25c85ecf-567a-49a6-b1fa-075321eb0e8f.png)

**Comment by Jedsters** [comment]
Hasn't that simply replaces Delay before Inactive with Min Duration? Isn't it possible to have both?
Thanks
