### ISSUE TITLE
Edge of RSSI appears to be inverted

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1291]
If I create a simple LSW of 
AND RSSI
this becomes true when the RSSI is non-zero (i.e. a rx is connected). 

With another LSW of 
Function: Edge
Trigger ON condition: RSSI
Duration of 1.0s
(note this is still telemetry RSSI and not the name of the first LSW)
I would have assumed that the Edge condition is triggered when the rx is connected and the RSSI becomes TRUE.
However this doesn't appear to be the case. In order to get the LSW to trigger, I have to invert the Trigger ON condition to !RSSI. 
 Isn't this the wrong way around?

**Comment by bsongis-frsky** [comment]
What did you enter in the "During" line?
It should work with RSSI as it does with all physical switches

**Comment by Jedsters** [comment]
During was left untouched, i.e. 0.0s -  ---

**Comment by bsongis-frsky** [comment]
Are you sure, did you read the doc about Edge?

**Comment by Jedsters** [comment]
Maybe my understanding of EDGE is inverted!  (I'm not sure the doc helps hugely, but I agree that it is consistent with physical switches.) 
Apologies!
