### ISSUE TITLE
Lua: Timers. Expose countdownStart() and countdownStep()

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1294]
This would be useful from Lua to set times when you want additional times for the timer to announce the count just like the GUI.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/148180937-13c896c9-2fbe-41ee-83e8-55c5ec25fcdc.png)

**Comment by agibson2** [comment]
You are psychic and implement features before they are requested! :).  Thanks.
