### ISSUE TITLE
Lua: Timers.  alarm() function of timer doesn't appear to do anything

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1295]
1.1.0 alpha 12 (haven't tested alpha 14 yet as simulator isn't released yet)

I tried both a countdown and count up timer and set alarm to 18 but I didn't notice anything happen when the alarm time was reached.  Maybe I am misunderstanding the purpose of the alarm?  Does it generate an event or something?

alarm ()
   Get / set the time when the timer started to play the alarm.  More...

alarmString ()
    Return the time when the timer started to play the alarm as a string.

I tried looking at the LuaEvent document page to see if there was a timer alarm or something but the lua docs page for LuaEvent is empty.

**Comment by bsongis-frsky** [comment]
It will change this field:
![image](https://user-images.githubusercontent.com/50834778/148180139-1b2324fd-a4b3-4873-8442-ae7f774aa746.png)
