### ISSUE TITLE
Add Simulator directly with every release

### ISSUE THREAD

**Issue by DigiDiDoDoo** [FrSkyRC/ETHOS-Feedback-Community#1296]
It is always noticeable that with releases, there is never a simulator included immediately.
Especially with Lua scripting it is a very essential tool that is needed to be able to quickly debug scripts before running on a radio.
A new version of ETHOS with lua may be released, but without a simulator it's not much use.
Please add to every release of ETHOS from now on thank you!

Other than that, your developers are doing an excellent job! that has to be said too!

**Comment by bsongis-frsky** [comment]
Please avoid opening such issues, it doesn't help.
Simulators are long to create and upload and we do our possible

**Comment by DigiDiDoDoo** [comment]
It does help, I have got your attention ;-)

Despite it takes long to compile and upload, the Simulator is just as important for lua debugging as the firmware itself.
Maybe work the otherway arround, first compile simulator and upload, then the rest. ;-) it will avoid these questions in the future.

**Comment by Hobby4life** [comment]
I understand DigiDoDoo, I think too it is better to release the sim before other files.
This way people can prepare their scripts before the firmware itself is released.
This saves script writers a lot of questions on their side too.

**Comment by agibson2** [comment]
They have a workflow as mentioned on regroups of verifying that things work on the devices before the long compile of the simulator.  It sounds like the only option would be to not release anything until sim is compiled but I would rather get something than nothing.  If you need the sim, just wait to update your code until the sim is available?

**Comment by Hobby4life** [comment]
> 

Problem then is.. people start using older version based scripts on a newer release.
And specially now some things kept changing with almost every release.
It will also pre-debug a radio release firmware.

**Comment by agibson2** [comment]
This is an alpha version of Lua on Ethos.  The way I see it, this is alpha testing for lua development and breaking changes can be expected.  Users really shouldn't be trying to use Lua scripts right now.  The alpha is really meant for developers.  The releases are coming often too so I wouldn't expect any user to be trying to keep up with what alpha version works with what scripts.  I suspect it won't be as big of a deal once the a stable version of Ethos with lua is pushed to everyone.  Updates likely won't have so many breaking changes.  They are doing a great job IMO with getting feedback from lua developers and making breaking changes if needed freely during the alpha stage... without fear of making it difficult for users as there is no previous stable version with Lua yet.  This release isn't really meant for users yet.
