### ISSUE TITLE
Request: Wireless Trainer enhancements

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1297]
Feature request, which i hope is doable by OS on current HW:

Please add a PPM input (same as trainer cable) from a pin in the external module bay.
this would allow installation of an FrSky PPM Rx (i.e RXSR and similar) as a wireless trainer in the module bay to connect ANY frsky radio to X20 as a buddy box.
this would be a very useful feature.
thanks.

**Comment by Hobby4life** [comment]
+1 on this one.

But maybe SBUS is better as Hrenz said in a similar like request. #1028

There is less PPM(out) support nowadays with Archer receivers, sbus bus would be a better alternative.
But both systems would be awesome too :-)

**Comment by i3dm** [comment]
> +1 on this one.
> 
> But maybe SBUS is better as Hrenz said in a similar like request. #1028
> 
> There is less PPM(out) support nowadays with Archer receivers, sbus bus would be a better alternative. But both systems would be awesome too :-)

agreed.
i mentioned PPM to keep backwards compatibility to cable usage. but its true SBUS is more popular and would be just as good if not better.

**Comment by Hobby4life** [comment]
Agree, also we got power directly in the bay.

**Comment by i3dm** [comment]
> Agree, also we got power directly in the bay.

thats exactly the reason why :)

another good feature would be to allow an input from DSC port (sbus / ppm), but at thge same time allow SW control of the power of the DSC port when its used as a trainer input

**Comment by Target0815** [comment]
I am interested that in the module bay or DSC port SBUS Out works. This is not only important for trainers, but also to e.g. Dragonlink or RFDesign TXMod can operate reasonably on Ethos transmitters.

**Comment by rwijnhov** [comment]
As mentioned in #2477 DSC port: sbus / ppm input + power ON to DSC port is verry important to me. Only ppm for the fast implementation is fine too. I use module bay for MPM to controll plane so i need dsc port ppm for wireless trainer.

**Comment by mawzthefinn** [comment]
PPM and SBus from the module bay is in the latest Nightly for 1.5.0
