### ISSUE TITLE
LUA in subfolder doesnt work

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1298]
Alpha 14: [Lua] scripts can be put inside subfolders

On Alpha 14 X20 sim: Put my RDT.lua file into SD/scripts/RDT instead of SD/scripts.
widget is not visible to select from any menus.

**Comment by bsongis-frsky** [comment]
please look at the examples

**Comment by i3dm** [comment]
> please look at the examples

where are these exmaples?
not on the sim SD contents?

**Comment by Hobby4life** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua

**Comment by i3dm** [comment]
thanks

**Comment by agibson2** [comment]
Short answer,  like opentx, rename main script name to main.lua when in a sub folder.

**Comment by i3dm** [comment]
> Short answer, like opentx, rename main script name to main.lua when in a sub folder.

done and working, thanks
