### ISSUE TITLE
Lua: Opacity option for Draw functions

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1299]
As the title says.

Would be a very usefull option for overlay drawings or even masking.

**Comment by bsongis-frsky** [comment]
Yes, everything is ready, it will even work in some situations, but not everywhere so I won't communicate on it until it's ready

**Comment by bsongis-frsky** [comment]
It's still hidden, so please don't open any issue, but lcd.RGB accepts a 4th argument, optional, which is "alpha"

**Comment by i3dm** [comment]
> It's still hidden, so please don't open any issue, but lcd.RGB accepts a 4th argument, optional, which is "alpha"

just played with it with values 0 - 1, pretty darn cool ! :)

**Comment by Hobby4life** [comment]
![image](https://user-images.githubusercontent.com/55426642/148393738-2bc16150-3211-445d-8563-c2ca8a0cc405.png)

Love it!

**Comment by Hobby4life** [comment]
Not a question just a observation.

lcd.pen() has a "side" effect on Opacity.

**Comment by bsongis-frsky** [comment]
> Not a question just a observation.
> 
> lcd.pen() has a "side" effect on Opacity.

which side effect?

**Comment by Hobby4life** [comment]
it shows the pattern of the pen function.

**Comment by bsongis-frsky** [comment]
the pen is used also on filled forms

**Comment by bsongis-frsky** [comment]
well I will change it, later perhaps I will introduce a brush but no need today

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/148941724-847befdb-c9ba-4dc1-9c1c-cf3c38d5f102.png)
