### ISSUE TITLE
Elevon pre set mix in mixer.

### ISSUE THREAD

**Issue by Lefish63** [FrSkyRC/ETHOS-Feedback-Community#13]
Been tinkering with Ethos today for a friend of mine who is not very tech savvy.
Will there be a pre set Elevator Aileron mix in the mixer added as this is a very useful addition for a lot of non technical users who can't or don't want to edit from scratch or struggle with the model wizard programme.

Also putting the more common pre set mixes in the mixer field will make the whole system more appealing to a great many new and converted users from other systems, because they can simply see it and select the mix rather than programme it from scratch.
This is direct feed back I have had from Frsky users at the field that have used the Fros system and is the MAIN reason they don't use Opentx !
We just think it will make Ethis more appealing to use.
I await your comment.
Thanks Dave.

**Comment by bsongis-frsky** [comment]
Just answer to the questions in the wizard:
![image](https://user-images.githubusercontent.com/50834778/113150431-5cee2e00-9234-11eb-8681-a88d95be1f3d.png)
![image](https://user-images.githubusercontent.com/50834778/113150450-61b2e200-9234-11eb-8661-5744b6e77221.png)
![image](https://user-images.githubusercontent.com/50834778/113150458-65466900-9234-11eb-905b-f807474aa744.png)
![image](https://user-images.githubusercontent.com/50834778/113150474-6aa3b380-9234-11eb-8f6d-e75f3a5b66e0.png)

Here are the mixes which will be created:
![image](https://user-images.githubusercontent.com/50834778/113150508-73948500-9234-11eb-8e8b-32ab77d7770b.png)
