### ISSUE TITLE
Simulator: ability to install both X10 and X20 simulators each with own environment

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1300]
right now it appears the registry key is shared so there's no way to develop for both radios.

**Comment by EngelMT** [comment]
I install in separate folders (X10 and X20).  Then you always have to choose the language again and cancel the wizard, but you can use both Sims at the same time.

**Comment by yaapu** [comment]
You can install both but they share the environment, you can't have separate widgets or models, every time you switch between X10 and X20 all radio data is reset and you need to start the setup from scratch, not very "user friendly"

**Comment by EngelMT** [comment]
I agree. I did it this way to be able to check the German menu navigation in both sims. If it were easier, it would also save me time.

**Comment by Hobby4life** [comment]
I would like to add something.

It would also be nice if we could select to opt both enviroments to share the same \scripts folder
