### ISSUE TITLE
Lua: Timer... audioMode() AUDIO_VOICE not defined

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1301]
Ethos 1.1.0-alpha14 @ edb93f09

print( tostring(AUDIO_BEEP) .. " " .. tostring(AUDIO_VOICE) .. " " .. tostring(AUDIO_MUTE) )

the output is...
1 nil 0

AUDIO_BEEP and AUDIO_MUTE are defined but AUDIO_VOICE is not.

Per the docs...
Get / set the audio mode of the timer (AUDIO_MUTE, AUDIO_BEEP / AUDIO_VOICE)

**Comment by bsongis-frsky** [comment]
Typo, I wrote AUDIO_SPEECH
It will be AUDIO_VOICE in next alpha
