### ISSUE TITLE
[Lua] system.registerSource(...) request for comments

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#1303]
Here is what is ready for now. Constructive ;) comments welcome!

### The source script

```lua
-- Lua Source Example

local translations = {en="Lua Source", fr="Source Lua"}

local function name(widget)
  local locale = system.getLocale()
  return translations[locale] or translations["en"]
end

local function sourceInit(source)
  source:value(0.1)
  source:decimals(2)
  source:unit(UNIT_VOLT)
end

local function sourceWakeup(source)
  source:value(source:value() + 10)
end

local function init()
  system.registerSource({key="Example", name=name, init=sourceInit, wakeup=sourceWakeup})
end

return {init=init}
```

### Source activation within the current model
![image](https://user-images.githubusercontent.com/50834778/148360344-ccdd69a1-3bc5-4616-9403-2fd7c18a2ab9.png)

### Source usage
![image](https://user-images.githubusercontent.com/50834778/148360483-0099caae-76fc-4edc-a111-b7f07440b4f4.png)

### Result
![image](https://user-images.githubusercontent.com/50834778/148373527-473a0473-60ac-4bc1-a0fb-54ac4c7a75fd.png)

**Comment by Hobby4life** [comment]
Ow wow great work!

**Comment by agibson2** [comment]
How do you reference it from display or update functions?  Would something in sourceWakeup() pull changes from a global Lua variable you create?

**Comment by bsongis-frsky** [comment]
1) You reference it as any other sources

2) You may assign any value to it in sourceWakeup(), and of course you may calculate it from global variables or anything

**Comment by RueFrank** [comment]
this does not work with X10-ISRM. The value is constant at 0

**Comment by bsongis-frsky** [comment]
without your script it's difficult to help!
or perhaps ask on the dedicated room on RCG?
