### ISSUE TITLE
Lua: EVT_TOUCH add Pressed an d Released

### ISSUE THREAD

**Issue by st157322** [FrSkyRC/ETHOS-Feedback-Community#1304]
Hi,

it would be great, if you could add a Pressed and an Released functionality to the touch event like it is implementet for the EVT_KEY.

Thanks, Lukas

**Comment by bsongis-frsky** [comment]
`EVT_TOUCH` is already available
`TOUCH_END` is already available
`TOUCH_START` will be new in alpha15
