### ISSUE TITLE
ETHOS X20S update from V1.1.0.A12 to V1.1.0.A14  speech is always English, no German, no France, no Spain

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1305]
Problem with ETHOS X20S update from V1.1.0.A12 to V1.1.0.A14
I can select any language, the texts change, English, German, French, Spanish, that's ok
BUT the language is always and only in English, no German, no French, no Spanish

What to do?

**Comment by bsongis-frsky** [comment]
Perhaps don't open an issue when you just have to read the manual, voice has his own setting

**Comment by hrenz** [comment]
hy bertrand, only updated, no changes, now only english as speech

before all was ok,  I an changes to english, to french, to spain, to german
Texts changes and Speech changes, 

no speech is allwys english,
texts changes

**Comment by hrenz** [comment]
ok, found it, 
a second place 
at sounds&vibr.  change to speech.

**Comment by hrenz** [comment]
Menue Languages and Speech should be in the same menü
