### ISSUE TITLE
Erratic SF playing of RxBatt via LSW at model connection

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1306]
Consider the following:
Create a LSW Name=RxConn; Function=A>X; Source (A)= Telemetry RSSI; Value(X) = 0db   (llet LSW other values default)
Create a SF Action=Play Value; State=Enable; Active Condition = Logic Switch RxConn; Value = Telemetry RxBatt (let other SF values default)

When a rx connects to the tx it will trigger the LSW which should in turn trigger the SF to play the RxBatt voltage. However, this is erratic, sometimes it playes the RxBatt value and other times it is silent (or just plays telemetry recovered). It appears (I may be wrong) that if you turn off the rx and leave it for longer (e.g. 30s) rather than just a second or two, it makes it more likely that the voltage will not be played. 

I would like voltage read to me when I turn on my model so I can confirm that it is good enough to start flying, this behaviour makes it risky and also makes me wonder if it is always reporting warning low voltages to me in the air.

V1.0.14

**Comment by bsongis-frsky** [comment]
90% times, RSSI comes in first, then will come RxBatt
Then your RxBatt won't be ready when you request it to play
Just setup a delay on your LogicSwitch and it will work correctly, tested right now
