### ISSUE TITLE
Simulator: ability to change analog stick step from 20%

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1307]
I have a program that uses stick input for the menu system.  Depending on where the stick position is at, that scrolls the list of choices.  Throttle stick at bottom, the bottom menu item is at the center of the screen to be selected.  Stick at top, the top menu item is at the center of the screen to be selected.  The menu has about 16 items so 20% movement is not enough for me to be able to test all menu items using the num keypad up and down arrows.
Maybe a command line option or some config file way to adjust the stick movement step when pressing up and down for the throttle would be very helpful.  I currently have to keep moving my menu items in the code so that I can test them which is a bit of a pain :).

**Comment by agibson2** [comment]
Another idea would be to allow holding shift while pushing on up or down arrow (8 and 2 keys) on keyboard to adjust by 1%.  This would allow moving quickly with 20% by default but if you hold shift key, you could micro adjust it by 1%.

**Comment by dwheel** [comment]
I would prefer using a key to **toggle** between 20% and 1%. Press and release shift key and it changes to 1% for all inputs. Press and release shift again and it returns to 20%. This eliminates the necessity to hold 2 keys down if one needs to change aileron or elevator by 1%.
