### ISSUE TITLE
1.0.3 SXR calibration menu leaving is not logical

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#131]
To leave this menu after the calibration is ready done is little bit unnormal I think. You have to press the RTN button a little bit longer. It will be nice to have a info like "Calibration ready" (like we have it) and a button "Leave the menu".

**Comment by DaySpeed955i** [comment]
X12S Factory ISRM HW:1.1.0  FW:2.1.6FCC  ETHOS 1.0.4

I am unable to exit the SxR calibration menu, press short or long any buttons do nothing, radio is still working for control. 

The Button "Click when done" is not active, I must turn OFF radio.
![SxR-Menu](https://user-images.githubusercontent.com/62478798/116820875-4560d880-ab45-11eb-9d29-ff3d7beffa2d.jpg)

**Comment by EngelMT** [comment]
@DaySpeed955i It is not possible to leave it by press RTN for longer time? With X20 it works. But as I wrote in the top my wish will be to get button to leave the menu on the last page. This would also clearly indicate that the calibration process is complete.

**Comment by DaySpeed955i** [comment]
I pressed RTN up to 10 seconds, also the other buttons, I must turn OFF X12S to exit SxR Calibration screen.
"Click when done" button stay grayed out when calibration is done. Note that I can exit any time BEFORE calibration is done with short RTN, "Click when done" button as focus (is orange).

Focus need to be back on button, I would suggest to change the text from "Click when done" to Click to exit".

Also note that if Rx is way out of requested position ( more then ~60deg), there is no message saying it can not calibrate and just wait for requested position.

Thanks.
