### ISSUE TITLE
Style request: Remove toolbar gradient

### ISSUE THREAD

**Issue by froqstar** [FrSkyRC/ETHOS-Feedback-Community#1310]
First, thanks a lot for keeping ETHOS so open that we can modify the UI style ourselves (to some extent at least).
I like the visual style of ETHOS a lot, but what always hurts my eyes is the gradient in the toolbar. It just looks like 2010 to me and doesn't follow the overall "flat" style of ETHOS at all.
The Black/White style toolbar looks fine though (no gradient), so why not do it for the "black" styles as well?

I therefore propose to change the toolbar background to a solid color, preferably the same shade of grey as used for the icon background:
Current             |  Proposed change
:-------------------------:|:-------------------------:
![current](https://user-images.githubusercontent.com/1944754/148464108-255b23a1-849f-4949-ab9d-1785a490afd2.png) |  ![proposed change](https://user-images.githubusercontent.com/1944754/148464167-2e8641d5-dbde-43a7-9172-074b848c9db0.png)

**Comment by agibson2** [comment]
I think the gradient helps it pop.  I like it anyway.

**Comment by MIKE-DAILEY** [comment]
I like the gradient.

**Comment by bsongis-frsky** [comment]
Perhaps we could make it flat with some elevation

![image](https://user-images.githubusercontent.com/50834778/148514181-5d47ae69-5b17-426e-b443-4dd1df82d102.png)

**Comment by bsongis-frsky** [comment]
On 1.1.0 just remove the file "toolbar_background.png" and you will get this result:

![image](https://user-images.githubusercontent.com/50834778/150951839-e486ac81-0e3c-4d63-8d05-f292573d2506.png)

![image](https://user-images.githubusercontent.com/50834778/150951854-152126ca-4fc0-4137-843f-2a1d265ec474.png)
