### ISSUE TITLE
Sound and Screen menue

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1311]
Sometimes customers phone us because they had changed the language in the screen menue but the Voice announcements are in english.

That's why my idea is to put these two setting options in one menu. Either both in screens or both in sounds. Or we could add a new menu called Basic Settings, for example. What to add to all this would have to be discussed.

This is certainly not a topic that needs to be dealt with immediately. But maybe one thing that can be implemented in the future.

**Comment by hrenz** [comment]
yes, Language and Voice should be in ONE menue to select.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/151014941-4cc7bdf3-5f10-428f-9706-ecef65e93b8f.png)
