### ISSUE TITLE
Lua: Allow x,y coordinates to be read from an array

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1312]
If possible at all, it would be nice to have x,y coordinates for draw functions be read out of just 1 array

for example

Position_1 = {x,y}

drawText(Position_1,"Blabla",CENTERED)

**Comment by bsongis-frsky** [comment]
It would mean changing it everywhere, right?

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/148514431-6153da23-e45e-401f-903a-bc35762140dc.png)

Qt offers both solutions, but we have a lot of limitations, we have to choose one and stick to it

**Comment by Hobby4life** [comment]
I think in the end if Only 1 option is possible, working with an array will take more code space.
Or
if it would also possible when going for array types you can enter:

drawText({10,10},"BlaBla",CENTERED)
&
drawText(ARRAY,"Blabla",CENTERED)


Then there is "not much" to change in existing situations.

**Comment by bsongis-frsky** [comment]
What is the benefit of a such change?

**Comment by Hobby4life** [comment]
When working with multiple drawtext/number variables in a fixed grid on screen.
In the end Easier to relocate these.

**Comment by bsongis-frsky** [comment]
But Qt has kept x, y
Both are nice, and if we have to choose one I am not sure that the tuple is the best

**Comment by Hobby4life** [comment]
It is no big issue :-) lets close this and keep it the way it is.
