### ISSUE TITLE
Style request: Add ETHOS green style/style color picker

### ISSUE THREAD

**Issue by froqstar** [FrSkyRC/ETHOS-Feedback-Community#1313]
First: 
Is there a setting somewhere to change the highlight color in ETHOS? If not, that would be great to have so people don't swamp you with $theirfavoritecolor requests like I do :) 

On topic:
I think a Green/Black style would look very good, especially if it uses the same shade of green that is used by the ETHOS logo.

Yellow/Black            |  Green/Black
:-------------------------:|:-------------------------:
![ethosyellow](https://user-images.githubusercontent.com/1944754/148524574-e4aee9d6-41fb-4e40-90e7-8e57b2218a84.png) | ![ethosgreen](https://user-images.githubusercontent.com/1944754/148524617-0f527f04-cd03-4c39-a1ba-e6f0bf726091.png)

**Comment by Hobby4life** [comment]
Hmm a Style with ETHOS Green... not bad :-)

Color picker for masking color +1

**Comment by bsongis-frsky** [comment]
If I continue your idea, the UI style would have 2 settings:
1) dark mode (boolean)
2) highlight color

**Comment by froqstar** [comment]
Yes, that would be awesome to have!

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/150789058-3853ec35-e057-4650-a019-05ffb72aa537.png)

![image](https://user-images.githubusercontent.com/50834778/150789044-4c87194c-1bce-4971-b4a3-52407c834c20.png)
