### ISSUE TITLE
Enhancement: Allow custom mixer trim values in %

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1314]
Currently it appears that Mixer Trims are controlled with a resolution of 0.5micro-seconds. 
It occurs that if an option was available for them to be controlled in resolutions of 1% that would open up the use of Mixer Trims as counters which could then be tested via LSW etc.. Currently this doesn't work as 1% is 5.12micro-seconds so any custom trim value eventually stops being detected.

**Comment by hrenz** [comment]
No, we finally need the counter function in the special functions
for up, down, set, autoreset/set
So that you can count with every key click

**Comment by Jedsters** [comment]
While true, it would also be useful to allow trim values in % as currently to trim a model out we effectively do so in microseconds and yet to move that trim into curves we can only do so in percentages which don't exactly coincide with microseconds.  Different use case, but still a valid requirement.

**Comment by mawzthefinn** [comment]
Trim steps can now be set in %
