### ISSUE TITLE
Logic Switches display Timers as %

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1315]
If I create a LSW to test a timer

![image](https://user-images.githubusercontent.com/96293240/148538034-5414cab3-39b8-49a8-8416-69fa80012dbc.png)

then the summary value shows this as a percentage rather than a time

![image](https://user-images.githubusercontent.com/96293240/148538141-a8728448-5830-4508-869c-1da470b60a23.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/148569664-e489975b-2884-47c3-b9f9-08614584eb54.png)
