### ISSUE TITLE
from 1.0.11 to 1.0.17 : some models don't appear anymore !

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#1316]
Good evening.
I upgraded from 1.0.11 to 1.0.17 and I have lost 4 of my models.
They are present on the SD card but only one (out of 5) plane is available (the other don't appear in the list to be selected from) while all Gliders are present and available.
Should I downgrade to 1.0.14 ? or back to the 1.0.11 with which those models were programmed ?
What is the issue ?

Thanks a lot !

**Comment by Tonio62** [comment]
Back to 1.0.11 ( sd and flash ) and go to 1.0.14 ( sd and flash )
After you can go to 1.0.17 with only the firmware update

**Comment by Billy60** [comment]
Thanks but it didnot work. More, now all of my engine planes are gone (their category is not showing anymore), only remaining the gliders. I could not find the proper 1.0.11 fw so I tried with 1.0.12 which is still available.

**Comment by Billy60** [comment]
This TX is gradually becoming a wreck.
Now some of the gliders which were available are not anymore. I had 12 models on the TX, now only 2,3,5,10,11 can be chosen from the list.
All are on the list of Models, including the motor planes which category does not even show anymore.
This is so disappointing !

**Comment by Tonio62** [comment]
if your models were edited with version 1.0.11, they will work normally with this version.
firmware 1.0.17 is designed to work with version 1.0.14 ( sd and flash ), which is why your models are corrupted.
but normally they are still all in your sd card?
if this is the case you must absolutely return to version 1.0.11 to.recover them

**Comment by Billy60** [comment]
Thanks Tonio,
I had a message about the RTC battery being wek so I changed it. 
Now, 1.0.11 is not available anymore on the Github, so I tried with 1.0.12 and the same problem.
Do you know where I could download 1.0.11 from ?
It seems that the fw is not saved when one saves the SD content. and it is erased from the root of the SD where it is put so it installs.
Thanks for your answers !

**Comment by Hobby4life** [comment]
First, you can't just go back to an earlier version firmware without actually restoring a backup of the SD card that belongs to that previous version firmware.

Once you have upgraded to a new firmware version. all models have been adapted to that new firmware with new functions. If you go back to a previous version, it doesn't recognize all those new added features that are stored in your model, which is why it always goes wrong. and often results in model loss.this is why you should ALWAYS backup your SD card. especially radio.bin and the models folder.
[v1.0.11.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7833148/v1.0.11.zip)

**Comment by bsongis-frsky** [comment]
> I upgraded from 1.0.11 to 1.0.17 and I have lost 4 of my models.

Please attach here one of those models

**Comment by Billy60** [comment]
[model12.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7837958/model12.zip)
[model10.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7837959/model10.zip)
[model05.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7837960/model05.zip)
[model03.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7837961/model03.zip)
[model02.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7837962/model02.zip)

Good morning Mr Songis
Here are some of those models. Now I am back to 1.0.11 and I could reprogram the 4 missing models. I think it is difficult to consider upgrading because it is not safe: lost models, saving process is not complete and it is so difficult to go back.
Thanks if you can do something about it. Your job is fantastic but if I may suggest, spend perhaps more time on such ergonomical  issues and less on over sophisticated ones which are not often used or even mastered by users. This 'saving' and 'upgrading' process should not bring to such trouble, IMHO
Thanks again

**Comment by bsongis-frsky** [comment]
Would you please tell us which model has been lost from all those zips?

**Comment by bsongis-frsky** [comment]
In the first zip your model is a glider, did you check all model categories to find your lost models?

![image](https://user-images.githubusercontent.com/50834778/148748313-8e610f5e-122e-4211-8436-cdf8206dd3d0.png)

**Comment by Billy60** [comment]
Yes of course !
In fact one category has been lost completely: The airplanes were gone. 
When I tried to restore them from the saved file, one only appeared.
When I went on with trials this one disappeared too.
So I had to recreate them from scratch.
My SDCard is a 32 GB fast type. I tried also with a 8 GB Fast type: same problem.
Now, starting from my current 1.0.11 with all models existing and available, I went through a complete saving of the SDcard, checking every file in it. 
Then I upgraded to 1.0.12: success, all went well.
Then to 1.0.17 : seems successful, all is well apparently. All models available and complete.
So, the issue is now solved but a few suggestions:
* find a way so each firmware version can be identified differently: currently, all are named the same: 'firmware'. No way to distinguish between them.
* please don't let the currently installed firmware on the SDCard be erased (it is not anymore on the SD) after it was transfered to the TX. Would be very useful to have it staying there, to be reinjected just in case.
* I would advise also to make an upgrade possible from any version to any higher one without needing to go by steps (a cumulative upgrading).
* please check on the conversion process if the models need to be converted, let it be robust and fully working. In my case, one category was corrupted. also I would dream of having a converter which would allow to go back to previous versions.
Thanks for your help.
The files I uploaded for you : all gliders were ok, all motor planes were gone. sorry, there is no way to know what model number corresponds to which plane or category of models.
Normally the motor planes have the higher numbering between models
[model09.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7838828/model09.zip)
[model09 (2).zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7838830/model09.2.zip)
[model08.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7838831/model08.zip)
.

**Comment by bsongis-frsky** [comment]
I have no info about your issue / mistake then?

**Comment by Billy60** [comment]
Frankly speaking, I don't know either what had happened.
I could manage by restarting everything from scratch and going step by step, turning around the issues I found but not solving them.
All the points I mention made it more difficult than I expected.
Bertrand, keep the good work, what you are doing is outstanding and we users are very happy to be able to enjoy your work !

**Comment by bsongis-frsky** [comment]
I suggest that you store the firmware you download on a directory which you name right, it will avoid such mistakes

I am almost sure you flashed a wrong version of the firmware, which obviously is not able to read models with an upper version
