### ISSUE TITLE
Alpha versions: unable to eject USB

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1317]
Alpha 14 / 15 (same in several versions):
ejecting from right click / eject on two WINDOWS 10 machines, does not eject any drives.

**Comment by bsongis-frsky** [comment]
In bootloader? In firmware?
Somebody else confirms this issue on Windows, not reproductible here

**Comment by bsongis-frsky** [comment]
There is no alpha bootloader
And firmware has no massstorage until now, so ... eject what?

**Comment by i3dm** [comment]
> In bootloader? In firmware? Somebody else confirms this issue on Windows, not reproductible here

in bootloader

**Comment by bsongis-frsky** [comment]
There is no alpha14 nor alpha15 bootloader

**Comment by Hobby4life** [comment]
He is correct, with the latest alpha versions I get no "reaction" when eject the usb drive.

**Comment by i3dm** [comment]
im always correct.
yet my issues are always closed very quickly ;)

**Comment by i3dm** [comment]
> There is no alpha14 nor alpha15 bootloader

i never said it didnt start earlier... had it for a while now

**Comment by bsongis-frsky** [comment]
There has been no update on bootloader since very long, the firmware is not even started!

**Comment by i3dm** [comment]
> There has been no update on bootloader since very long, the firmware is not even started!

who said this was a fw issue?
so a BL issue then.

**Comment by i3dm** [comment]
> Try to clean your SD, perhaps something is wrong on it

what do you mean clean my SD?
