### ISSUE TITLE
Alpha 15: PNG model image does not load

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1318]
the attached image worked fin up to A12.
upgraded to A15 - image no longer loads on X20 but loads fine on simulator.

image attached:
![F16N](https://user-images.githubusercontent.com/8968780/148641183-ccd362f9-6f3f-4ee9-bd5b-7e83ed2d965c.png)

**Comment by Ceeb182** [comment]
To reduce the machine time required to process PNGs, prefer the BMP format with alpha channel support.
- You can find my converter of any type of image to BMP format used by Ethos here : **[Download link](https://bit.ly/3nzaJDN)**
- You will find a quick explanation of how it works here: **[Quick start of the BMP converter](https://www.rcgroups.com/forums/showpost.php?p=48196243&postcount=12552)**
- You can find more information here: **[Link to the full documentation](https://github.com/Ceeb182/ConvertToETHOSBMPformat)**

**Comment by i3dm** [comment]
thank you. will use bmp.
this image worked fine before on any version prior to alpha 15?
and still works on alpha 15 sim.

**Comment by bsongis-frsky** [comment]
Tests done today:
- Bitmap loaded as Model Bitmap and displayed in a Model Bitmap widget correctly.
- Bitmap loaded in a Lua script and displayed in the widget correctly

Please share your script

**Comment by i3dm** [comment]
how can i share it with you privately? i do not want to publicly post it yet.

**Comment by bsongis-frsky** [comment]
perhaps you can distillate your script with the very minimum which displays the bitmap
