### ISSUE TITLE
Alpha 15: disappearing menu icons

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1319]
This started happening from upgrading from Alpha12 (was OK) to Alpha 15.
menu icons are randomly disappearing:

https://youtu.be/YEPC9O6njco

**Comment by bsongis-frsky** [comment]
Perhaps your script does strange things? Try to reduce it to the minimum

**Comment by i3dm** [comment]
reduce what?
all scripts worked fine until alpha 12 and have not changed.

**Comment by bsongis-frsky** [comment]
Unless it's linked to #1326

Please reopen if needed in alpha16

**Comment by i3dm** [comment]
How do i reopen if needed?

**Comment by i3dm** [comment]
@bsongis-frsky 
issue still exists on Alpha 16
how do i repopen?
