### ISSUE TITLE
Throttle cut requires THR value under trigger value for shutdown (switch off).

### ISSUE THREAD

**Issue by prikrylm** [FrSkyRC/ETHOS-Feedback-Community#132]
v1.0.3 on X12S
Throttle cut requires that the THR input value be below "Trigger value" also for the shutdown action.
Requiring THR level below "Trigger value" is reasonable for switching on, but for switching off? Is that an intention?

**Comment by MIKE-DAILEY** [comment]
Yes, but the value can be adjusted.

**Comment by prikrylm** [comment]
Sure, activation behavior is OK. But is it OK if I am able to cut off throttle (deactivation) only if THR is below "trigger value"? Isn't it some kind of "emergency" switch, which must cut off engine in any situation?

**Comment by MIKE-DAILEY** [comment]
It is not an emergency cut.  If you need an emergency cut you can do it with a Free Mix below.

![screenshot-2021-04-26-47106](https://user-images.githubusercontent.com/11791852/116136641-8e75e000-a6a0-11eb-95e8-c6e728b887a2.jpg)

![screenshot-2021-04-26-47111](https://user-images.githubusercontent.com/11791852/116136653-92a1fd80-a6a0-11eb-8866-c6d05bda8aa0.jpg)

**Comment by prikrylm** [comment]
OK, if it is not emergnecy cut, probably works fine.
