### ISSUE TITLE
1.1.0 alpha15 X10s trim per flight mode missing

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1323]
In the X10 the dropdown menu which shows the values per FM is missing. It is present in the X20.

![Screenshot 2022-01-08 175449](https://user-images.githubusercontent.com/85410070/148652704-bb23ec95-3e1c-4f36-82c4-fee064ce2d2c.jpg)

**Comment by bsongis-frsky** [comment]
Will be done with #1382

**Comment by besser** [comment]
This issue still persists in version 1.4.11.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/890037/315a2e75-fcdf-4bb8-aec0-d6c1d21eac00)
