### ISSUE TITLE
GPS GMT offset not calculating correctly.

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#1325]
I live in the USA Central Time Zone which is -6 hours from GMT. My X20 is set to automatically adjust the time using GPS. It works perfectly until 6 PM, which is -6 hours from GMT. After 6 PM, the time is set to very odd times as shown in the pictures below. After midnight, and until 6 PM that day, it works normally again. 

I have attached a short video showing what happens at 6 PM. Note - In this video, I do not have my time set to be automatically set from GPS. It is showing the transmitter time, and the GPS time. You will see the odd GPS time after 6 PM. This is what the transmitter time would be set to if allowed.

Using firmware V1.1.0-15.

You will have to download the 50 oclock - Copy.wmv.txt file and delete '.txt' from the end to view it.

![gps4](https://user-images.githubusercontent.com/6865267/148661264-858ed8fe-575f-423b-ab0e-134cfa58cf22.jpg)
[50 oclock - Copy.wmv.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7834084/50.oclock.-.Copy.wmv.txt)

**Comment by MIKE-DAILEY** [comment]
Same issue with internal GPS in X12S.
