### ISSUE TITLE
Alpha 15: menu scroll overlay where not needed

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1326]
see video:
https://www.youtube.com/watch?v=bwIW5nC_-fI

**Comment by Hobby4life** [comment]
Yeah, still some issues only with fullscreen widget.

I have sent same issue to bertrand last week.

**Comment by bsongis** [comment]
Fixed in alpha16

**Comment by bsongis-frsky** [comment]
Fixed in alpha16
