### ISSUE TITLE
Trimm setting in Flight Mode Menu on HORUS X10

### ISSUE THREAD

**Issue by DeltaTango123** [FrSkyRC/ETHOS-Feedback-Community#1327]
On the HORUS X10S with ETHOS 1.0.17 in the Flight Mode Menu the Trimm Setting istn activatet
![screenshot-2022-01-08-54053](https://user-images.githubusercontent.com/97388762/148681237-464bf311-c2fe-46fb-90bc-d97ce1c2298f.jpg)
.

**Comment by bsongis-frsky** [comment]
Dumplicate of #1323
