### ISSUE TITLE
Throttle timers not working.

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1328]
I was helping a guy out and this model will not allow any throttle based timer actions to work. His goal was to use throttle percentage, but that doesn't work. I have also tried using Throttle Trigger, Throttle absolute, but nothing works. It is as if it doesn't know what channel the throttle is on.  I have stripped everything out of this model, leaving on a single timer, and a single throttle channel.
When I first looked at the file, I noticed he had set up multiple throttle channels, and my guess is that this had something to do with the problem. 
I have played with this setup for quite a while trying to figure out what is wrong, but have come up empty
[model99.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7836324/model99.zip)
.

**Comment by WismyYao** [comment]
The problem is in Preflight Checks.
