### ISSUE TITLE
Rudder Servo Speed in Mixer

### ISSUE THREAD

**Issue by danielcaceres1991** [FrSkyRC/ETHOS-Feedback-Community#1330]
Hi, it would be a great addition to Ethos if we were able to reduce servo speed for rudder in the mixer instead of in output. I fly F3A and use a slower servo speed during most of the flight, but certain maneuvers such as Snap Rolls require full servo speed. At the moment my solution is using virtual channels for this. But it would be a lot simpler if I could do it from the mixer.

**Comment by bsongis-frsky** [comment]
I would use a free mix for rudder then

**Comment by danielcaceres1991** [comment]
> I would use a free mix for rudder then

Maybe I was programming it incorrectly, but I use 8 different conditions (rates) for rudder for different maneuvers. I was unable to get the rudder trim to work the same for all rates since they use different rates. It was a nightmare trying to make it work. Perhaps you can point me in the right direction on how to make it work using free mix and trim

**Comment by bsongis-frsky** [comment]
Perhaps you should share your setting on RCG and discuss there, it would be an interesting use case!

**Comment by danielcaceres1991** [comment]
The issue is when I switch from the mixer with 0 slow up/down, to the one with 1 sec slow up/down. Sometimes I get up to full surface deflection before the output matches the stick position.
I want the transition from one mixer to another with the same output channel to be smooth, without sudden unwanted deflections

**Comment by mawzthefinn** [comment]
I'd also suggest sharing your setup on RCG. The full deflection sounds to me like there is a brief period where there's an invalid input being sent to the surface, possibly because you have a situation where no selected mixer is valid.

**Comment by mawzthefinn** [comment]
Closing off due to no updates
