### ISSUE TITLE
#alpha 16 Screen flickers when you go out of the clock setting

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1333]
Please check the video.

[20220112_093128.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7853135/20220112_093128.zip)

**Comment by bsongis-frsky** [comment]
which version?

**Comment by EngelMT** [comment]
As I wrote in the headline.  alpha 16.

**Comment by EngelMT** [comment]
It seems this issue only occurs with widgets built via Lua. The problem does not appear to occur with models without these widgets.  I tested this again and again today.

**Comment by bsongis-frsky** [comment]
It should be fixed now. Please reopen if needed in alpha17
