### ISSUE TITLE
Alpha 16: disappearing menus

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1336]
This started happening from upgrading from Alpha12 (was OK) to Alpha 15 (#1319 ). 
it also happens on Alpha 16.
menu icons are randomly disappearing:

https://youtu.be/YEPC9O6njco

**Comment by MIKE-DAILEY** [comment]
Not able to replicate on my X20S with Alpha 16.  Have you tried updating the icons on the Flash drive?

**Comment by i3dm** [comment]
just tested anoyther model memory with no widgets - same issue occurs.

**Comment by i3dm** [comment]
> Not able to replicate on my X20S with Alpha 16. Have you tried updating/rewriting the icons on the Flash drive?

just did now - same result - problem still occurs.

**Comment by hrenz** [comment]
no problem with A16 
all Menüs visible

**Comment by bsongis-frsky** [comment]
please remove all your Lua scripts from your SD and check everything works normally, then reintroduce them one by one to find which is the bad one

**Comment by i3dm** [comment]
> please remove all your Lua scripts from your SD and check everything works normally, then reintroduce them one by one to find which is the bad one

i have 4 self made widgets, all with background images and more.
any one of the first 2 i removed caused the radio to go back to normal. so its not a specific widget issue.

**Comment by bsongis-frsky** [comment]
perhaps all 3 self made widgets are wrong and take too much RAM, it will be difficult to check if you don't show the scripts

**Comment by Hobby4life** [comment]
Yeah I have tested it. loading too much widgets with large bitmaps will eat memory.

**Comment by bsongis-frsky** [comment]
ok, too much RAM used
