### ISSUE TITLE
X20 failing no output

### ISSUE THREAD

**Issue by Rondek** [FrSkyRC/ETHOS-Feedback-Community#1338]
I have X20 purchased sep 2022, with Ethos version 1.0.11. EU #8bd25e73. After setup my first model and bound to Rx SR8 Pro Archer it all worked. Stabilisation and mixers setup properly. All of a sudden there was no output on servos anymore. Had to delete model and set it up all over again. Same story, it worked properly, but after a few test again failing outputs. No error messages

**Comment by EngelMT** [comment]
You can be sure that it is not an ETHOS issue. So please contact your dealer for help. 

Here we report ETHOS issues. But your issue never reported with ETHOS. And we are now at the 1.0.18 or the 1.1.10 alpha 16.

**Comment by MIKE-DAILEY** [comment]
Not running the SR8 Pro self-test process could be the issue.

**Comment by guycnicholas** [comment]
It could also be that they ran self-check but did not move the sticks at the appropriate time, which then trains the control throw to 0.

**Comment by Rondek** [comment]
Thanks Guys, if this is not ETHOS issue, is there another thread/board to put my questions? I don't want to take too much time of you. Anyway as beginner (on FrSky) one more question. If it would be the selftest procedure, do I have to run this selftest(by flipping the switch) every time I power up the system? Because I didn't run this every time, however sometimes the "failure" occurred after 10 minutes (at that time I probably would be flying already).

**Comment by EngelMT** [comment]
@Rondek

I do not know where you come from. But you are welcome in our FrSky Forum here in Germany. https://frsky-forum.de/

In United Staates I can offer you the forum from Aloft Hobbies. https://forum.alofthobbies.com/

**Comment by Rondek** [comment]
Thanks. I am from the Netherlands

Op do 13 jan. 2022 10:12 schreef Andreas Engel ***@***.***>:

**Comment by Hobby4life** [comment]
Tijd voor een nederlands frsky forum 😉

**Comment by bsongis-frsky** [comment]
> Had to delete model and set it up all over again. Same story, it worked properly, but after a few test again failing outputs. No error messages

This is what is very strange. If you setup a new model, everything works correctly. Then when does come the issue?

**Comment by Rondek** [comment]
Like I said, it's strange indeed. Last Monday it worked, was fine tuning mixers and weights and stuff, for more than an hour. No problem. When I next day powered up again, after 10 minutes the issue came by, eg no output to 5 channels with servos, only on channel 4 small movements on servo only. Stabilising also not working anymore.
So just installed new SD card, Upgrading to te latest firmware 1.0.18, RF module 2.1-1.15 and receiver Archer-2.1.9 for my SR8 Pro. But receiver remained red led, no way to reset or so. Also registered/bind again, but no out put on servo channels 1,2,5 only small movements on 4. Thus took a brand new SR6 Pro from the box, went through whole procedure again and finally it worked good! Question now is how to reset the SR8 Pro, or should I consider this one as lost?

**Comment by Rondek** [comment]
SR8 reset, working fine now. Thanks for support guys.
