### ISSUE TITLE
Custom startup frsky logo color

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#1339]
Can we have the option to change the color for startup frsky logo? I have set to orange theme and just the startup logo is in yellow

**Comment by Hobby4life** [comment]
Not Possible it is fixed in the bootloader, not in ethos.

**Comment by bsongis-frsky** [comment]
The logo is official FrSky color. It is displayed at the very start of the firmware, before the SD card is initialized. So it's impossible to modify
