### ISSUE TITLE
After configuring an SxR receiver, the program does not terminate correctly.

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#134]
After configuring an SxR receiver, the program does not terminate correctly. It is necessary to turn off the transmitter.
Transmitter: x10S Ethos 1.0.3

**Comment by Nicholas-Luoyi** [comment]
We have tested it and the program terminated correctly. We don't understand exactly what do you want? Would you please give more information?

**Comment by Skippydi** [comment]
i think it is the same problem as issue #131
