### ISSUE TITLE
LUA: Cells exacmple is broken

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1341]
in continue to #1243 
cells example is broken, this is what i get when i run it on alpha 14:
![image](https://user-images.githubusercontent.com/8968780/149489008-673bfaca-c3ae-4c3e-be1b-0af1d3c703d7.png)

**Comment by bsongis-frsky** [comment]
Because this feature has been introduced in alpha15

**Comment by i3dm** [comment]
where can i find the latest simulator that supports this feature?
