### ISSUE TITLE
Lua: Add luac support

### ISSUE THREAD

**Issue by st157322** [FrSkyRC/ETHOS-Feedback-Community#1342]
Hi,

do you plan to support any kind of a pre compiled code for Lua scripting?
Or how would it be possible to publish a Lua Script which is not readable/changable by the user?
Would it be possible to save luascripts from beeing copied to multiple transmitters? For example: customer a buys a script and after he installed it on the first transmitter this script only works with this transmitter and would not work on another transmitter from customer b
Are there any Plans on this topic?

Thanks

**Comment by bsongis-frsky** [comment]
luac is available in Ethos 1.2.11 and above

**Comment by i3dm** [comment]
> luac is available in Ethos 1.2.11 and above

will ethos compile lua to luac on first run?
