### ISSUE TITLE
LUA forms:  Allow forms to be modified after initial creation

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#1349]
It seems that forms cannot be modified (lines added or removed, field values updated via the script, etc) outside of the create() function when being used in system widgets.

This request is to allow form lines to be added/deleted and the currently selected field value changed during runtime through the wakeup/event functions and button interactions (functions called by textButtons and buttons inside openDialog calls).

**Desired functions:**
- form.clear()  -- Clear all lines and fields from an existing form (allowed during runtime)
- form.addLine()  -- Same as it's current functionality, but allowed during runtime
- form.add…Field/Button() -- Same as their current functionality, but allowed during runtime
- field:updateValue(val)  -- Sets the currently displayed value for a NumberEdit/TextEdit/etc field to the passed "val" (could be integer or string depending on whether it's a number/switch/text field).  (Like getValue, but allowed during runtime).
- form.deleteLine(line)  -- Delete an existing line and associated field(s) from the form (allowed during runtime).  deleteLine is not 100% necessary since the form could just be cleared and recreated anyway.

This change would make forms a simple tool to use for building user interfaces for flight controllers, flybarless units, etc that have a large number of settings delivered over serial telemetry protocols.  The idea would be to use buttons to interact with the user (selecting and changing pages as an example), and then the script would clear and repopulate the form with new lines and fields.

Modifiable forms would be quite powerful when they're combined with painting temporary lcd overlays for cases where you're waiting for data returned from commands, saving, rebooting, etc.

**Comment by bsongis-frsky** [comment]
Those functions will be new in 1.1.0 alpha17:

`form.clear()`
`form.invalidate()`
`form.onWakeup(<function>)`

**Comment by bsongis-frsky** [comment]
Yes. `form.onWakeup` is deprecated, in favor of the normal `wakeup` handler
