### ISSUE TITLE
Add curves in mixer

### ISSUE THREAD

**Issue by wizan9z** [FrSkyRC/ETHOS-Feedback-Community#135]
Is it possible to add curve in the  dedicated control surfaces mixer similar to add weights? I am trying to program different expo rates for all the control surfaces. Currently only can be done by using flight modes but requires at least 2 set of mixers for each surfaces. It will be easier to just add curve and activate by switch in the outputs or pre set control surfaces mixer

**Comment by Nicholas-Luoyi** [comment]
It is coming soon in the next Release version. Thanks!

**Comment by Nicholas-Luoyi** [comment]
I'm sorry. This feature is finished. But I'm afraid that it has been delayed. Because of not being tested well. However, it won't let you all waiting for too long.

**Comment by marevalor** [comment]
> This feature is almost ready. It will be released once fully tested.

Are you sure if this improvement will come out in version 1.0.5?
Thanks, Marcelo.
