### ISSUE TITLE
FLVSS Setup X20S

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1350]
FLVSS View individual cell voltages

**Comment by ninodesposati** [comment]
#1
I’m having trouble figuring out how to set up using FLVSS Voltage sensor on my X20S. I’d like to see the following as I did on my X12S. 

1-Setup minCell voltage alarm on any cell that goes below 3.6V. from (1-12 Cells if you piggyback FLVSS sensors)

2-Display on the home page the current lowest cell in Voltage.

3-View all individual cells that are connected to the FLVSS. (Ex. A 6 cell would show all 6 cell current individual voltages.

**Comment by ninodesposati** [comment]
Got it Figured out
![image_2021_07_30T13_56_12_777Z](https://user-images.githubusercontent.com/46627889/149642367-5ed39b3b-bc2c-462c-a4cc-6d980d5fa7a0.png)
.

**Comment by MIKE-DAILEY** [comment]
Very good!
