### ISSUE TITLE
LUA EVT_KEY event:  Enter button is missing break event indication

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#1352]
1.1.0-alpha16 Simulator
LUA script:  servo/main.lua

Enter button does not give release (break) indication.  All other buttons give break indication properly.

Example result from enter button presses (short and long presses shown):
![image](https://user-images.githubusercontent.com/81865495/149639336-3f202a9e-88c5-414e-80a5-833dd4cae00f.png)

Expect to see value of 33 (KEY_ENTER_BREAK) on each release of the enter button:
![image](https://user-images.githubusercontent.com/81865495/149639305-0f269f66-b6a1-4107-9547-64a6a33b1740.png)

**Comment by WismyYao** [comment]
see line 44 of servo/main.lua , the code is used to kill KEY_ENTER_BREAK event

**Comment by WismyYao** [comment]
The KEY_ENTER_BREAK event is triggered by the number edit widget on the previous layer and will not be processed in this Lua script

**Comment by centertrim** [comment]
@WismyYao I think it is actually broken.  See results of a test script I wrote specifically for this:

![image](https://user-images.githubusercontent.com/81865495/150236171-73d3c048-bb0b-4736-86e3-cb3b388c0dd5.png)

Here's the script:

[EnterTest.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7901218/EnterTest.zip)

Perhaps there is something else capturing the enter_break event?  It would be very helpful to be able to get the enter_break event, as without it capturing short and long enter presses becomes a bit of a hack.
