### ISSUE TITLE
FLVSS min Cell Voltage Alarm Setup

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1353]
How to set up an alarm for FLVSS min Cell Volts (EX. 3.60V). If any individual cell goes below 3.6v I'd like to have sound or play a track. Thanks
![image_2021_07_30T13_56_12_777Z](https://user-images.githubusercontent.com/46627889/149644814-00d32e14-f1a3-4408-bd73-5227ccb2d087.png)

**Comment by MIKE-DAILEY** [comment]
You have answers to your question that you posted on RCG.   The FrSky GitHub is for reporting issues with ETHOS.
