### ISSUE TITLE
Request for a radio firmware update application.

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#1354]
Hello,
Is there any plan to develop an Ethos firmware update application for PC?
Ethos is really great and for Frsky, having an application that recognizes the radio, saves and offers the latest official or Beta firmware would make life easier for users.

**Comment by bsongis-frsky** [comment]
Already in progress, it won't help if you open more issues for requesting it, we just spend more time on sorting issues
