### ISSUE TITLE
Improving the inconsistent mixer configuration to more convenience and easier programming

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1356]
Hi Developer,

Today there are only 3 additional options to add for the Curves and the Wright/Rates. 
1. I would like to have more additional Curves and Wright/Rates to cover all my flight modes (max 10)
2. The name of a flight mode would be helpful in the label instead of a general label "Flight Mode n".
3. Alternatively/additional there should be an option to select in the curves like in the flight mode selection, the possibility to checkmark all the flight modes where a curve / wright/rate is valid for.
To have a better overview and make the programming better visible Option 1 an 2 are better from my point of view.
<img width="351" alt="Bildschirmfoto 2022-01-17 um 11 18 43" src="https://user-images.githubusercontent.com/86232280/149763600-f29381b6-bf67-4744-a2d5-c316821fec03.png">

<img width="373" alt="Bildschirmfoto 2022-01-17 um 11 19 19" src="https://user-images.githubusercontent.com/86232280/149763665-b3a4909c-e3d7-4e34-a4b2-c8f3d2285d2f.png">

<img width="345" alt="Bildschirmfoto 2022-01-17 um 11 18 59" src="https://user-images.githubusercontent.com/86232280/149763688-d95f1653-81b6-49c3-8fe4-37ecce191f30.png">

The idea behind this are a better overview, less Mixer programming effort and a faster programming in Ethos.
When I have more then 4 different curves, I need an additional mixer now. For my Models I use always at minimum 5 Flight mode for Helis and copter but for planes more depending on the model. 

Best Regards

Bernhard

**Comment by BernhardFe** [comment]
Dear Developer, 
with Version 1.0.19. the "Rates" are now extended to 9 choices, which I didn't recognized yesterday. This change is great. Taking this in consideration, the only remaining points are the Points 1 and 2 from above.
3 can be ignored.
Open: Curves additional 9 instead of 3, Flight-mode names instead of labels in the mixers.
Best Regards
Bernhard

**Comment by mawzthefinn** [comment]
Flight Mode names are now included in the labels as of 1.4.0

**Comment by BernhardFe** [comment]
Hi Developer,
Thank a lot for all the efforts.
Ethos is getting more and more perfect and I like it very much.
I like also that users feedback is really recognised.
Great work!
Best Regards
Bernhard

**Comment by BernhardFe** [comment]
I close this issue, because the change is done and the 3 additional curves are good enough. :-)
