### ISSUE TITLE
Single Lipo Cell and Capacity norming in Calculated Sensors

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1357]
Dear Developer,

In several models I fly 3S, 4S, 5S, 6S, 12S Lipo batteries. To use always the same values for voltage calculation in the logical switch  over all models, I would like to have a divider for the lipo cells in an additional calculated telemetry sensor for the Lipo voltage. Than I can use over all models the same boundaries to switch logical switches and I can to trigger values in the voice feedback.
(Battery not full, Battery empty...). Additional it is always difficult to have all the values and boundaries in mind. So it would be helpful to have the calculated cell also in the Telemetry screen. I know the values for one cell and it's boundary by heart but not for all variations I use.

Regarding the capacity it would be great to have a % calculated normed capacity. Then I can use always the same programming for the logical switches and mixers for all models. For this I need to put the maximum to consume capacity of a lipo once into the calculated sensor for a model. After this, the capacity can be reused in % at every point in the system similar to the voltage of one lipo cell above.

Best Regards
Bernhard

**Comment by bsongis-frsky** [comment]
Perhaps we could just add a new formula for calculated sensors which would be "Percent"?

**Comment by BernhardFe** [comment]
Hi, percent would work for the capacity. For the voltage a divider would be better to be able to configure to make it equal for all batteries in several models to the count one cell as an average of all cells.
So 2 additional calculated sensors are useful. 
The percentage can be used universal as an additional calculated sensor.
The divider can be implemented in the voltage sensor menu itself, if possible. :-)

**Comment by bsongis-frsky** [comment]
On all sensors you can already configure a min and a max limit, so a Percent sensor should be enough

**Comment by BernhardFe** [comment]
Ok, thanks a lot!

**Comment by bsongis-frsky** [comment]
Added the Percent calculated sensor
