### ISSUE TITLE
More Curves in Mixers

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1358]
With ETHOS 1.0.19 you can specify within a mixer up to nine weightings but only three curves.
It would be great if the number of curves could be increased to match the number of weightings.

In addition, it would be very useful if the customer names of the flight phases could be shown here.

**Comment by mikedkelly** [comment]
Yes, I use curves on the flight mode buttons to switch ArduPilot flight modes. It would be nice to put all 6 curves under one mix instead of having to break that function into two mixes.

**Comment by mawzthefinn** [comment]
@Hartinger -FM names are now shown.

@mikedkelly check out VAR Mixers, much better solution for your Ardupilot flight modes.

**Comment by mikedkelly** [comment]
Thanks @mawzthefinn. With a VAR mix I was able to get rid of the 6 curves and just define a single mix using weights - a much better solution.

**Comment by mawzthefinn** [comment]
More curves are still useful

**Comment by mawzthefinn** [comment]
1.5.0 brings the implementation to 6 curves.

**Comment by bsongis-frsky** [comment]
6 curves in 1.5.0
