### ISSUE TITLE
Sensor 4405/ FUEL 

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#1359]
when i search for the sensor again, it shows me a value of 100.  now I want to change the sensor so that it displays ml.  I just can't change the quantity.  how is that possible?  my volume should be 1500 ml.  I currently have version 1.0.18

**Comment by bsongis-frsky** [comment]
Which sensor?

**Comment by MichaelETHOS** [comment]
the telemetry adapter specifies % for the consumption.  is it possible to change the value so that it is displayed in ml in the tx.  and adjust the tank size.  if you don't want to use lua.

**Comment by bsongis-frsky** [comment]
Tour telemetry adapter should use the right S.Port spec, there is another ID for ml instead of %
