### ISSUE TITLE
Flaps slow down in mixer

### ISSUE THREAD

**Issue by wizan9z** [FrSkyRC/ETHOS-Feedback-Community#136]
Currently this only available in independent channels outputs. For gliders with 2 ailerons, the slow down in independent channels will also impact in mixer for camber mixing. Will be good if can have slow down in mixer instead of just in independent channels like those in FROS.

**Comment by pstasek** [comment]
As a workaround, you can use a free mix either as an input for Flaps mix: Set the output of slowed down free mix to an unused channel (64) and then set the source for flaps mix to that channel. But yes, slow down is a common requirement for a Flaps mix.

**Comment by mshagg** [comment]
This only occurs for a flaps mix which is created by the wizard.  If you create your own free mix on the flap channel the slow up/down settings are exposed.

It would be good to have the functionality included in the default mix created by the wizard - flap channel is probably the most common place where slow up/down is used.
