### ISSUE TITLE
Image Model Heli

### ISSUE THREAD

**Issue by Romad30** [FrSkyRC/ETHOS-Feedback-Community#1362]
Hello
Sorry for my bad english ! 
when I create a new model the helicopter image has disappeared. On the other hand for the other models no worries.
I use a X20S with last firmware.
Thank you.

**Comment by bsongis-frsky** [comment]
Would you check you have the latest pack for your FLASH / SD?

**Comment by Romad30** [comment]
Hello,
I take this pack : https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/release%2F1.0.18/X20S-EU.zip

**Comment by bsongis-frsky** [comment]
no, flash contents cannot go on SD, please check the manual from Mike on RCG, everything is very well explained

**Comment by Romad30** [comment]
So thank you ! I was so stupid ! Flash memory could be access on bootloader and plug USB cable. 
I change the flash model and all is good.
Thank you the team !
