### ISSUE TITLE
Clock time is a bit speedy

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#1363]
Using 1.0.19 latest firmware on my x20s. Noticed that time is a bit speedy. Have set the correct time and a week later is off by 5 minutes.

**Comment by Tonio62** [comment]
Same for me with my x20 1.0.19, but it's the same issue since the begining

**Comment by mmasch** [comment]
You'll find how to tune your RTC clock here: https://www.rcgroups.com/forums/showpost.php?p=48211421&postcount=12670

Hope this is helpful :-)
