### ISSUE TITLE
Alpha 16 - default weight down incorrect in Free mix

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#1364]
X20, Ethos Alpha 16 

To reproduce, 

- Select 'Other' tab
- Create a new model
- Create a free mix
- Open the free mix editor and examine default values

_Expected_: Weight up = weight down = 100%
_Actual_: Weight up = 100% but weight down = -100%

**Comment by bsongis-frsky** [comment]
Already fixed on 12 of January
