### ISSUE TITLE
1.1.0 alpha17 new model select screen 

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1367]
In the new model selection screen it is no longer possible to select a model by long press.

Furthermore, not all data is displayed correctly in the bottom line.

![Screenshot 2022-01-21 203445](https://user-images.githubusercontent.com/85410070/150589653-22cb1fb0-84e9-4f8b-ac3b-38e24d6489cc.jpg)

**Comment by bsongis-frsky** [comment]
DE translations will have to be shorter!

**Comment by bsongis-frsky** [comment]
Lin
