### ISSUE TITLE
1.1.0 alpha 17 categories disappeared

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#1369]
Hello, in the new selection screen there are no longer any categories for me with the alpha17.
The line below shows the category correctly.
There is also no way to create categories.
![screenshot-2022-01-21-75715](https://user-images.githubusercontent.com/64803366/150594362-966f8c14-3559-40ad-8f2d-18a9592b61c5.jpg)

TX: X10S

**Comment by STC148** [comment]
You can create a new Folder by long press PgUp/Dn

**Comment by MIKE-DAILEY** [comment]
Here is the Folders How To https://www.rcgroups.com/forums/showpost.php?p=48526993&postcount=14008

**Comment by Devil-IdT** [comment]
Oh, that was quick now.
Many thanks for your help.
