### ISSUE TITLE
allow mixer weight  > 100%

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#137]
There is always the occasional need to set more than 100% travel/weight in mixers.
This is especially true for functions that works with offsets or in case several mixers act on one output. 

According to my tests, the maximum allowed weight is 100%, which should be increased to at least 200%. 

Regards

**Comment by bsongis-frsky** [comment]
Why do you need at least 200%?

**Comment by Hartinger** [comment]
In an extreme case you may work with an offset of 100% (plus or minus is irrelevant here) for flaps.
This enables you to use the full servo travel for the Butterfly mix (at the expense of not being able to move the flaps up).
In this case you need 200% weight in the flap part of the Butterfly mixer, in order to reach the servo end position.

**Comment by bsongis-frsky** [comment]
Thanks @Hartinger it makes sense to me, even if I wouldn't fly myself with such settings :)

**Comment by RC-SOAR** [comment]
As of 1.0.9 the value of a mixer output still appear to be limited to +/-100%. Is this still to do?

**Comment by strgaltdel** [comment]
Ich kehre zurück am 28.06.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] allow mixer weight  > 100% (#137)" gesendet am 19.06.2021
19:59:27.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by RC-SOAR** [comment]
I see that this issue has been closed... however the fix works does not always work - it depends on the mixer order. I've raised a separate issue:
[https://github.com/FrSkyRC/ETHOS-TEST/issues/403](https://github.com/FrSkyRC/ETHOS-TEST/issues/403)

**Comment by strgaltdel** [comment]
Ich kehre zurück am 28.06.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] allow mixer weight  > 100% (#137)" gesendet am 21.06.2021
11:43:59.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.
