### ISSUE TITLE
1.1.0 Alpha 17 Logic Switches Options Inverted

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#1371]
Hello, flashed X20S from Alpha 15 to 17 and it seems in the logic switches the invertet option is not converted. 
I moved all Moells to custom Folders. Have not tested bevore moving the models to the new folder. 
I'm not 100% sure if happen from 15 to 17 or maybe from 14 to 15 but I#m pretty sure that the Inverted from the switch options are somewhere lost.

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1373

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/150731545-2cebb55e-357d-4f3d-be9b-a9abbefe2b99.png)

**Comment by bsongis-frsky** [comment]
It seems working correctly, please provide more information about the problem you have found!

**Comment by Cipta-de** [comment]
Yes it's working correctly but during o e of my last updates the inverted which was enabled in the models wS ignored and not present in the converted model.
As mentioned before I'm not sure if it was from alpha 14 to 16 or previous update

**Comment by bsongis-frsky** [comment]
There was no conversion there recently!

**Comment by Cipta-de** [comment]
Sorry Bertrand, may it was longer ago and just realized now.
Good work


Herzliche Grüße und einen schönen Tag noch wünscht


Roland Schäfer



Mobile:+49 17696614767

Mail:    ***@***.***



schau doch mal auf meiner Webseite nach neuen Fotos www.cipta.de


Bertrand Songis @ FrSky ***@***.***> schrieb am Mo., 24. Jan.
2022, 09:54:
