### ISSUE TITLE
Lua: Reset telemetry altimeter to 0 (like Special Function)

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1372]
I do not see a way to reset the FrSky vario altimeter to 0 feet using LUA.  There is a reset feature in Special Function to do it but we need a way to reset it programmatically in Lua.

I have a Lua script that show launch height but I need to reset the altimeter to 0 for the next launch to get around altimeter drift over time.

**Comment by bsongis-frsky** [comment]
Added `sensor:reset()` function
