### ISSUE TITLE
1.0.17 french manuel

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#1373]
hi, 

here is the french version
[X20 et Ethos1.0.17fr.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7918325/X20.et.Ethos1.0.17fr.zip)
.

**Comment by EthosUser** [comment]
> salut,
> 
> voici la version française [X20 et Ethos1.0.17fr.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7918325/X20.et.Ethos1.0.17fr.zip) .

Nickel !

**Comment by Ceeb182** [comment]
Thanks for sharing 👍

**Comment by Mobidick1966** [comment]
merci

**Comment by bsongis-frsky** [comment]
Repo updated with latest manuals, thanks!
