### ISSUE TITLE
Request: LUA: add support for PNG

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1375]
background image for lua 480x458 pixels:
bmp565 750 kB
PNG 376 kB

supporting PNG or JPG will help consume much less RAM as huge BMP files wont have to be loaded?
PNG attached:
![LZGASbgNoTitle](https://user-images.githubusercontent.com/8968780/150693455-a0646d95-bd2c-43f6-9e7b-2d4864af6736.png)

**Comment by bsongis-frsky** [comment]
I am sorry but 480x458 in 565 format shouldn't use 750kB

**Comment by bsongis-frsky** [comment]
Your PNG bitmap is 800x480, 32bits per pixel. Once it's uncompressed, it takes a LOT of RAM

**Comment by i3dm** [comment]
> Your PNG bitmap is 800x480, 32bits per pixel. Once it's uncompressed, it takes a LOT of RAM

so which format is needed to downsize it?

**Comment by i3dm** [comment]
can you convert this image to bmp565 proper format and note the file size?

**Comment by i3dm** [comment]
> I am sorry but 480x458 in 565 format shouldn't use 750kB

it maybe shouldnt. but it does and its a fact.
please offer a proper solution.
