### ISSUE TITLE
unwanted offset in rates

### ISSUE THREAD

**Issue by LProia** [FrSkyRC/ETHOS-Feedback-Community#1377]
Good morning,

I run Ethos1.018 on X20S.
I want to introduce the rates as a function of the gas position.
i made 4 logic switches, gas1 range -60 -20, gas2 range -20 +20, gas3 range +20 +60, gas4 range +60 +100.
From the aileron mixer menu I assigned a rate of 80% on gas logic switch condition 1. They try the throttle at -50, the logic switch is ok, the rate brings the curve to 80%, but an offset of 3% to the right intervenes. I didn't ask for this offset, because it exists
Tested on the ethos simulator it works, but on the radio it doesn't.

Thank you
LProia****

**Comment by mawzthefinn** [comment]
Is this still occurring on newer versions? I just tested on 1.4.3 and cannot duplicate.

**Comment by mawzthefinn** [comment]
Closing as stale, unable to duplicate
