### ISSUE TITLE
Enhancement: Alpha 17 new model select system thumbnails take too long to load.

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1378]
The new model select system is a great improvement thats for sure!
But if you have arround 10+ models in a catagory it takes a very long time to load all images.

Advice, auto generate small thumbnail images, when a image is selected in a model.
Or let us be able to create a thumbnail images. like:

image.bmp  + image_th.bmp

**Comment by bsongis-frsky** [comment]
SD card speed increased in next alpha
