### ISSUE TITLE
simulator 1.1.0alpha trojan warning from antivirus program

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1379]
I get multiple warnings from my antivirus program when I download the .exe of the alpha simulator.
With the release versions of the simulator I get no message.

![Screenshot 2022-01-24 123704](https://user-images.githubusercontent.com/85410070/150776771-afc3c449-803b-4a19-9aca-8118dd67d310.jpg)

**Comment by EngelMT** [comment]
Got also warnings. My Kasperski delete the download. So not not possible to install. I used all Sims in the past. Never had such issue. Only alpha 17 makes trouble.

**Comment by bsongis-frsky** [comment]
Did you check on VirusTotal?

![image](https://user-images.githubusercontent.com/50834778/150796018-2d2aac8f-7e10-4fee-a9e0-34fb931a2f02.png)

**Comment by EngelMT** [comment]
Here my reports out of Kaspersky. Tested with Google Chrome and Firefox.

![image](https://user-images.githubusercontent.com/16795828/150814810-65c3bfb0-6518-4998-b3a4-bc8fe6982131.png)

**Comment by andika207** [comment]
@EngelMT  my Avast antivirus also reported a trojan but it's actually my computer which is infected. LOL
the simulator alpha17 that caused your trouble has been removed, maybe you were right

**Comment by STC148** [comment]
As long as Kaspersky is running, I cannot install any of the alpha simulators, they are deleted immediately. Even if I add them as an exception or tell Kaspersky to ignore them..........no chance

**Comment by EngelMT** [comment]
It's the same with me. I hope Bertrand finds a way to solve the problem. I have now tried it from several computers. But no difference. All Sim files are either deleted immediately or later by Kaspersky.

**Comment by Hobby4life** [comment]
Are these warnings comimg from pre installed virus scanners that come with windows?

**Comment by EngelMT** [comment]
We use only Kaspersky in the company. But now we can read here that Avast Antivirus also has a problem with the sim. It worked without problems until alpha 16.

**Comment by Hobby4life** [comment]
Looks more like a virus definition update has come in several virus scanners. Which ensures that "possible" things are more likely to be seen as a threat.

I haven't seen it with ESET NOD32 yet.

**Comment by andika207** [comment]
@Hobby4life some users have also reported a trojan that came with the X20 SD card, that's because all the chinese software @Adelaxie is often full of malware and they probably have a computer infected.

**Comment by andika207** [comment]
@EngelMT I have downloaded the 1.0.18 simulator today and my Avast AV didn't pop up, so I can install it with no issues

**Comment by EngelMT** [comment]
Bertrand advised me to report the problem to Kaspersky. I did so and received the following reply.

Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Best regards, Roman Rybachek, Malware Analyst
39A/3 Leningradskoe Shosse, Moscow, 125212, Russia Tel./Fax: + 7 (495) 797 8700 http://www.kaspersky.com https://securelist.com https://opentip.kaspersky.com/ - get insights about suspicious files, hashes, URLs, IP addresses or domain names

__________________________________________

From:	a.engel@engelmt.de
Received:	1/31/2022 9:02:54 AM (UTC)
Sent:	1/31/2022 9:02:25 AM (UTC)
To:	newvirus@kaspersky.com
Subject:	Kaspersky Anti-virus Lab replies to your request [VD3] [FILE:2]

Client feedback, query 9AE5361F8566C152E3DC57BA772F96BAF1B09808A6A14DB739492A7BD57EE074, type [Hash], zone [Red], was sent with the following commentary:
This is no Malware. This is a normal Simulator for test radio controled firmware..

This message is generated automatically by OpenTIP.
With Best regards,
OpenTIP Team.

**Comment by STC148** [comment]
Thank you Andreas for your efforts, after a database update from Kaspersky the SIM can now be installed again.
