### ISSUE TITLE
Feature requests: trim enhancements

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#1382]
Ethos is lagging behind OTX with respect to trims and this means that some aspects of my OTX glider templates cannot be replicated in Ethos. Specifically, need to:

- Allow trims to be shared between a subset of flight modes. (As of Alpha 16, trims can be all independent, or all shared.)
- Allow trims to be disabled per flight mode, (As of Alpha 16, this can be done by setting Trim Mode='disabled', but it's applied to all flight modes.) 

Any plans to add these in a future release?

**Comment by bsongis-frsky** [comment]
Yes of course this will be added, once Lua is released!

**Comment by RC-SOAR** [comment]
That's great :-)

**Comment by loetefix** [comment]
And please also make the trim mixer possible to store one value for every flightmode.
Now we have to make 3 trim mixer for 3 flightmodes.The trim mixer is a nice feature to make digital pots.
i use it for helicopters to "store" my throttles for every flightmode. so i can adjust it easy in flight.but at the moment i need one trim mixer for every flightmode.

**Comment by mawzthefinn** [comment]
Also need an ability to disconnect trims from canned mixers without disabling them. I've been forced to move to Free Mixes for Throttle and Rudder to free trimmers.

Plus naming for Trims (and pots) should be aligned to the physical labels.

**Comment by mawzthefinn** [comment]
This is related to #215

Will leave open as it is a Milestone

**Comment by ululi1970** [comment]
I would like to add a request for trim inheritance, as it is currently implemented in OTX.

**Comment by mawzthefinn** [comment]
Issue #1725 is open for increasing the max trim step.

**Comment by i3dm** [comment]
> Issue #1725 is open for increasing the max trim step.

yes open for a long time. but no dev response.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/64787915-d8ac-47ea-adc5-df411bea3a94)

**Comment by bsongis-frsky** [comment]
The enhanced trims feature is now merged in our 1.5.0 branch and it is available in nightlies!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9df27c72-8705-4779-8964-ab331320df76)
