### ISSUE TITLE
LUA: single bmp565 background image memory usage

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1386]
Alpha18, using this printing:

local mem = {}
mem = system.getMemoryUsage()
print("Main Stack: "..mem["mainStackAvailable"])
print("RAM Avail: "..mem["ramAvailable"])
print("LUA RAM Avail: "..mem["luaRamAvailable"])
print("LUA BMP Avail: "..mem["luaBitmapsRamAvailable"])
print("=========================")

after loading a single BMP565 background image (800x480), these are the results:
![image](https://user-images.githubusercontent.com/8968780/151134267-c18524ec-fe3a-45c7-a193-d67a6b4318ff.png)

does this make sense? a single background image in the correct format consumes more than half of the available BMP RAM?

**Comment by bsongis-frsky** [comment]
800x480 x 2bytes per pixel = 768K over 2MB
I suspect you have other bitmaps loaded

**Comment by i3dm** [comment]
> 800x480 x 2bytes per pixel = 768K over 2MB I suspect you have other bitmaps loaded

Do you realise we have NO TOOL from you to check if format is corrent?
i went out of my way with the help of H4L and this is the best we could both achieve!
how the heck is anyone supposed to find this super special extra ordinare format?

**Comment by i3dm** [comment]
removed everything else but the background image, result is:
![image](https://user-images.githubusercontent.com/8968780/151141160-fbbcb684-0257-4774-8a1f-dd3771658c6b.png)

added model image print and got:
![image](https://user-images.githubusercontent.com/8968780/151141322-6348275c-cf77-4bbd-91a7-0630a50d41d4.png)


so 2 background images and model images are already passing the maximum of this OS - it is a huge limitation.

**Comment by i3dm** [comment]
running this simple widget:
![image](https://user-images.githubusercontent.com/8968780/151141598-743a0b16-56f4-4e16-820e-8ffa6dc35f65.png)

results:
![image](https://user-images.githubusercontent.com/8968780/151141652-f511f582-22f4-4cae-8ce7-e119193f077c.png)

more than half of the BMP RAM used.

**Comment by bsongis-frsky** [comment]
Before you ask somebody else how to delete a bitmap:
https://www.tutorialspoint.com/lua/lua_garbage_collection.htm

**Comment by bsongis-frsky** [comment]
2.5MB for bitmaps from next alpha:
=======================

3MB for the system
2MB for Lua scripts
2.5MB for Lua bitmaps

I don't see how I can do better on my end, perhaps you can save on your bitmaps, i.e. not load a full screen bitmap just for a texture

**Comment by i3dm** [comment]
> # 2.5MB for Lua bitmaps from next alpha:
> 3.5MB for the system 2MB for Lua scripts 2.5MB for Lua bitmaps
> 
> I don't see how I can do better on my end, perhaps you can save on your bitmaps, i.e. not load a full screen bitmap just for a texture

i went ahead and defined the same global var for all background images on all my different widgets, this loads just 1 image at a time to memory, and it did help!
