### ISSUE TITLE
1.1.0alpha18 Percent calculated sensor

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1387]
The sensor is great, thanks for that, but is there a way to make the sensor count backwards? For example, the used mAh counts up, but I would like the percentages to count down and show me the remaining capacity.

**Comment by bsongis-frsky** [comment]
it's never finished :)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/151322983-ebc3755e-c7dd-49e4-bd38-539be4ca2a9f.png)
