### ISSUE TITLE
Butterfly mixer: inproper Input handling & missing Parameter

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#139]
Hello,

hoping the title had not too hard words (-;
From a glider pilot's view, butterfly mixer still needs a little optimisation to become easy to use AND really practical.

1.)
The Butterfly function needs by definition an input that has a range from 0% to 100%.
0% ="retracted", i.e. no mixer calculation.
If you select an input, it is "passed through" 1:1, i.e. it has a control range from -100% to +100%.
(wrong offset, wrong scaling)
This behaviour is shown by software variants of several manufacturers and unfortunately often leads to the fact that users without being aware of the problem continue to create mixers for error compensation, which then do not work properly or they get "lost" in the Butterfly Config.
Very often I can see that additional elevator offsets are programmed (because "retracted position -100%" is wrongly mixed with elevator etc...).

**Imho it is urgently advisable to store an additional curve already in the butterfly mixer after selection of the input, which generates a value range of 0-100% with corresponding offset and scaling, WITHOUT the user having to worry about it.**

Ideally, the curve should have about 5% "deadband" so that the flaps do not extend if the user inadvertently moves the input only slightly.

There would be no compelling reason that a user can "see"or edit this curve, but it would be nice for the more experiences users.

This measure alone makes it much easier for the standard user to apply a practicable butterfly mixer.

2.)
The pitch up moment does not behave linearly over the mixder range.
In the beginning, for example, the pressure point and lift coefficient change greatly, whereas later on it is essentially only drag that increases.
Therefore, at the beginning, "elevator-down" is mixed in particularly strongly, while later the mixing remains almost stable.

**It is therefore necessary to also store a curve for the depth admixture.**

To simplify matters for the user, it would be advisable to store a typical curve (e.g. 7 point) directly in the mixer, which only requires fine adjustment.

3.)
When the butterfly is strongly extended with a high aileron position, you hardly get any aileron effect "out of the box" with the Ethos Butterfly Mixer.
This can be remedied by progressively countering the aileron differential.

**This requires an additional parameter for countering (percentage).**
(one parameter that refers to all ailerons should suffice for simplicity's sake).

Example:
the aileron differentiation is set to 30%. 
the counter value is set to 50% (refers to maximum butterfly deflection).

With 
BF=0%:       Diff = default value     = 30%
BF=50%:     Diff = 30%-0.5x50%    =   5%
BF=100%:   Diff=30%-50%            = -20%

This generates proportionally to the BF deflection considerably more aileron deflection downwards and considerably improved control possibilities around the longitudinal axis.

Regards

**Comment by strgaltdel** [comment]
4.)
only in V-tail configuration:

Imho it's unnecessary to set the elevator mixer-weight dedicated for left&right Vtail flap.

Makes things unnecessarily complicated, so not Ethos-like.

If V-tail is correctly parameterised, one value is sufficient, which is added to the "Input" path of the elevator.

**Comment by aalain8** [comment]
Hello,
I am a F5J glider pilot.
In the Butterfly or Camber function I also regret not having a curve for the elevator, for the ailerons and for the flaps.
I also use like most F5J competitors a "dead band" (see pictures)
I made a photo montage to show how I would like to have the curves.
To see if it is possible.
![af](https://user-images.githubusercontent.com/64332717/116229098-621c9b00-a756-11eb-88ed-3c3711682750.PNG)
![0](https://user-images.githubusercontent.com/64332717/116229108-65178b80-a756-11eb-924b-81bfe3abd3df.PNG)

**Comment by strgaltdel** [comment]
Hi Aalain,

totally agree, 
it seems there will be some progress:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/135

regards

**Comment by jfint** [comment]
It looks like my #296  could be merged with this one

**Comment by strgaltdel** [comment]
much time has passed since the issue was opened.

maybe this schematics show how a butterfly mixer which will satisfy most F3B / F3J etc pilots would have to be implemented in an actual Ethos Revision.
Obviously too much different mixers has to be used.
(all but aileron mixer)

regards 
Udo


![butterfly schematics](https://user-images.githubusercontent.com/20392683/144058647-7b5b9cec-692a-47f7-9f60-e5fc24693edb.png)

**Comment by stephan39** [comment]
It would be helpful, when in each mixer of the plan shown above, we can slow down the servo movement separately.

regards
Stephan

**Comment by strgaltdel** [comment]
Hi,

2 more month passed and we are short in getting lua support,
fine, i do appreciate this ! 

Maybe next step after final release 1.1 could be to work on older issues, which regularly restrict functionality ( definitely).
so i hope no one feels tackled cause i push this issue.

seaching in andreas engels' forum by "butterfly" i got several results which incorporate to the items mentioned above

maybe some extensions at the butterfly mixer could be done
 in the near future


thanks !


just a small selection :

![0but1](https://user-images.githubusercontent.com/20392683/151819764-42aacfeb-61b1-4aa0-9ea3-bd46c4fe81e7.png)

![0but2](https://user-images.githubusercontent.com/20392683/151819925-937b3766-a696-4659-be2f-6cb5f9f90f28.png)


...

**Comment by EngelMT** [comment]
I completely agree with the desire to optimise the finished mixers. ETHOS was once launched to allow easy programming of models. At the moment ETHOS is developing very well and can do more than many had expected in the past.

But if you don't want to have a "Super OpenTX", then it's time to get back to basics. And that certainly includes the finished mixers. The approaches are good and only need to be refined. I am not a glider pilot and cannot help much. But there are very good descriptions here in this thread alone of what is missing and what is wanted. And these are from users who fly such models. Sometimes even in competition.

Bertrand and Wismy, please take up the matter and work on it.

**Comment by strgaltdel** [comment]
Thanks for implementing  issue 1623,
so number (1)  out of (4) in the list above is fixed

**Comment by mawzthefinn** [comment]
Item 3 is also available today, add a 6th channel output to the Butterfly Mixer targeting a high channel, name the Channel 'Butterfly Diff', set the percentage to the desired differential value at max Butterfly, then in your aileron mixer set the Differential to Use a Source->'Butterfly Diff' channel.
