### ISSUE TITLE
X10S Express Failsafe not working

### ISSUE THREAD

**Issue by phHed** [FrSkyRC/ETHOS-Feedback-Community#1391]
I upgraded my Horus X10S Express from OpenTX to ETHOS 1.0.19 and proceeded to programme my Extreme Flight Gamebird, and finally set a custom failsafe. This is when I encountered a serious issue. To test the failsafe I switched the tx off, then switched it back on again. The failsafe did not engage and when the rx recovered the signal, the servos became extremely erratic and uncontrollable. I repeated the procedure and got the same result. I have now reflashed the tx back to OpenTX 2.3.14 and all is well.

Archer SR8 PRO rx
HV digital servos

**Comment by phHed** [comment]
No I did not wait 10 secs, thanks for the follow up.

Phil
________________________________

**Comment by bsongis-frsky** [comment]
Would you try it again to be sure? FS are transmitted every 10 seconds, the same on OpenTX

**Comment by phHed** [comment]
I have just reflashed to EdgeTx, will go back to Ethos in a couple of days then try again.

Phil
________________________________

**Comment by phHed** [comment]
Just tried again on Ethos, perfect no problem, sorry for the false alarm, I’ll make sure I’m more thorough before I post any issues in future.

Phil
________________________________
