### ISSUE TITLE
Alpha18: screen flickering when running a widget

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1392]
See video:
https://www.youtube.com/watch?v=bJNWuif7rbw&feature=youtu.be

**it is also reproduceable on X20 simulator**
this is the only widget loaded:
*file removed

**Comment by EngelMT** [comment]
Unfortunately I have to confirm that. I think the problem was already solved with the alpha 16. But I'm not sure.

**Comment by bsongis-frsky** [comment]
Reproduced, thanks for the example

**Comment by i3dm** [comment]
> Reproduced, thanks for the example

youre welcome
file rwmoved now (its not released to public yet)

**Comment by bsongis-frsky** [comment]
Your paint function which is very wrong, if you call invalidate and your paint function does nothing, it's normal that the radio will display only garbage

@EngelMT I suspect your radio was running this script?

**Comment by bsongis-frsky** [comment]
I am not a fan of the lazy "always invalidate my widget", it just destroys the radio performance for nothing

**Comment by i3dm** [comment]
> Your paint function which is very wrong, if you call invalidate and your paint function does nothing, it's normal that the radio will display only garbage
> 
> @EngelMT I suspect your radio was running this script?

my paint function in the widget does a lot of things.
