### ISSUE TITLE
Alpha 18, RSSI 1db display is back

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1393]
I am nearly sure that it was solved before. But with alpha 18 it is back.

**Comment by MIKE-DAILEY** [comment]
If you are referring to the RSSI displaying 1db on system startup that was fixed the ISRM firmware 2.1.15.

**Comment by bsongis-frsky** [comment]
The 1db is an ISRM issue. Please update your internal module.

**Comment by EngelMT** [comment]
Sorry guys, you are right. I have 3 X20 here for testing. And one was without update from TD2.1.14 to 2.1.15. So my fault.
