### ISSUE TITLE
Norwegian language, minor update, 1.1.0 alpha18

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1396]
[no.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7959015/no.txt)

**Comment by bsongis-frsky** [comment]
Why all the # everywhere in the Model Menu?

![image](https://user-images.githubusercontent.com/50834778/151578756-f5720383-cc91-4564-8d8f-fa00a6de8993.png)

**Comment by bsongis-frsky** [comment]
Removed
![image](https://user-images.githubusercontent.com/50834778/151578879-6317f245-f240-4fcb-9bd4-089353efc51f.png)

**Comment by mmasch** [comment]
Hi Bertrand. 

Thank you. 
I used the # to check that the correct menus has been sorted correctly in the language file. 
Forgot to remove them after pasting and checking. 
Trying to sort after main screen, sub screen and so on to easier locate items later  ;-)
It’s a work in progress...

Best regards, Morten Masch, Norway.
