### ISSUE TITLE
1.1.0-17 and 1.1.0-18 bug report. 

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#1399]
This morning I was doing some testing on the simulator with 1.1.0 Alpha 18 and noticed a problem.  As you can see in the picture below, logical switch 2 has been modified. It has been changed from INVERTED to normal  (the leading ! is missing). The top half of the picture is from Alpha 16, the bottom half from Alpha 18. I checked 2 more models and the exact same thing had happened to them. The resulting action of the logical switch is also wrong. Re programming it to the INVERTED condition corrected its actionss. 

I installed a backup of Alpha 17 and it had the same error. I then installed a backup of Alpha 16 and it was correct. 

After again installing Alpha 17, the INVERTED condition had been removed again resulting in an error with the logical switch. After changing it back to INVERTED, it once again operated normally. 

I then installed Alpha 18 and the INVERTED condition was again removed. I corrected this and the logical switch now works correctly

I then tested on the transmitter and the same error occurs.

![11018](https://user-images.githubusercontent.com/6865267/151623137-df001cf1-4a22-4d16-abfa-c2655df035fe.jpg)

**Comment by Nicholas-Luoyi** [comment]
It's a conversion issue indeed!
