### ISSUE TITLE
Sr6 gyro wont initialize self check

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#14]
Ethos version 0.0.16, isrm is version 2.1.6 reciever firmware is 2.1.6.
I re installed opentx 2.3.11 and self check initialized on reciever, but wouldn't in ethos.
Also when the sxr calibration lua finishes, it says calibration complete but it then freezes the only way of coming out of it is switching the tx off and on again.
Thanks scott

**Comment by Liverboy77** [comment]
I have fixed the issue where I couldn't turn off gyro.
But I still can't get it to do self check, throttle is -100 and I have cycle channel 12 3 pos switch though the centre position 3 times in 2 seconds but blue light on reciever dosnt flash.
Please help

**Comment by Liverboy77** [comment]
Just an update isrm is version 2.1.6 reciver firmware is 2.1.6.
I re installed opentx 2.3.11 and self check initialized on reciever, but wouldn't in ethos.
Could this please be fixed in version 0.0.17.
Thanks scott

**Comment by i3dm** [comment]
did you verify ch12 operation and throttle being at -100%?

**Comment by raydars** [comment]
If the outputs are correct on the radio monitor then it's likely Ethos at fault,   the channel 12 needs cycled furiously fast compared to SXR receivers

**Comment by i3dm** [comment]
if the monitor is correct its probably not ethos fault..?

**Comment by raydars** [comment]
> if the monitor is correct its probably not ethos fault..?

Sorry just off nightshift and completely forgot to add a "NOT" to the sentence,   edited to what it was supposed to read.

**Comment by Liverboy77** [comment]
Finally fixed it I had to go into system - hardware and then alter switch middle detect delay from 100ms to 0ms.

**Comment by i3dm** [comment]
makes sense

**Comment by janekx** [comment]
This is unaccaplable solution, on some RX it works and on some needs <30ms we need to make the change where all will work

**Comment by i3dm** [comment]
Im having the same issue with S8R and X20 Ethos V1.0.9, even with switch middle detect delay, and RF D16 set to ch1-ch16, gyro in Rx will not go into self test mode whtn toggling CH12.
any ideas guys?

**Comment by bsongis-frsky** [comment]
Do you send the 16 channels or only 8 (default because quicker frames period)

**Comment by i3dm** [comment]
Channel Range: CH1 - CH16

**Comment by i3dm** [comment]
BTW Tx restart does not reset the switch delay to 100, it stays at 0 in Ethos 1.0.9

**Comment by i3dm** [comment]
https://youtu.be/jHlhFQrVvms

**Comment by bsongis-frsky** [comment]
Why would a Tx restart change your settings?
And why do you need to change a switch delay? Because you use a switch middle position for this?

**Comment by i3dm** [comment]
yes because of the middle position.
any ideas bertrand?
