### ISSUE TITLE
System Volume Adjustable by special function 

### ISSUE THREAD

**Issue by Nerenye** [FrSkyRC/ETHOS-Feedback-Community#1400]
I really miss the possibility to change system and Vario Volum trough a special Funktion.
Depending on how noisy the surrounding area is , i need to adjust that quite often.
to have it on a potentiometer via global special function would be nice

Best regards

**Comment by STC148** [comment]
You can set the pots in the system menu

![Screenshot 2022-01-29 135414](https://user-images.githubusercontent.com/85410070/151661849-c7e7e920-8f09-45c4-8ac0-3e27828b7217.jpg)
