### ISSUE TITLE
Function switches undefined at startup

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#1401]
X20 1.1.0 Apha 17 

Function switches FSW1-6 behave collectively like 6-p switch. However, at startup, all function switches return False values - in effect, the state of the equivalent 6-p switch is undefined. This makes them not very good for applications such as selecting different elevator rates.

I would propose that FSW1 be designated the default. In other words, at startup, FSW1 is True and FSw2 - FSW6 are False. The indicator light for LSW1 would therefore also light at startup. (The TX16S works like this.)

**Comment by bsongis-frsky** [comment]
Did you see the Model / Edit expansion panel and all possible per-model configurations?

**Comment by RC-SOAR** [comment]
I wasn't aware of it.  However I have just checked, and the function switch option was set to '6-Pos', so I believe the issues is still valid - there should be a default switch which is on at startup.

**Comment by RC-SOAR** [comment]
Just to add: to determine the states of the function switches at startup, I created an array of logical switches 'FSWn AND AlwaysOn'.

**Comment by Jedsters** [comment]
@RC-SOAR 
Mike, I don't think it's quite that simple.  What you say is fine (and I agree) for your scenario of 6-Pos, however 
for 2x3 Pos presumably 2 of the FSW would need to be active (maybe 1 and 4?)
for 6 Pos with OFF it may not be unreasonable for all FSW to be off by default?
for 6x2 Pos again all FSW to be off by default seems reasonable?
for Momentary I think all FSW to be off by default is necessary! (Well, unless one of the FSW really is being pressed.)

**Comment by mawzthefinn** [comment]
@Jedsters I agree, somewhat.

It should be selectable for each type of activity. But @RC-SOAR is also right that it should have a sane default out of the box.

**Comment by Jedsters** [comment]
@mawzthefinn Absolutely, I was just trying to make the point that FSW1 True and FSW2-6 False wouldn't  always be a sane default other than for 6-Pos.  But yes, it should be sane out of the box.

**Comment by mikedkelly** [comment]
Agreed. I map mine to pwm values using curves and output through Ch. 8 in order to activate ArduPlane flight modes. When my X20 starts up, it sets the pwm value of Ch. 8 to 0, which is FSw4 even though that switch is in a false state. It would be great to have it default the startup value at startup instead.

**Comment by RC-SOAR** [comment]
@Jedsters  agreed. I raised the issue for the '6-pos' option, but it also applies to the '2 x 3 pos' option.

Just to summarise, this is how one might expect the startup states to work for each option. The options which don't conform are shown in **bold**.

- _6-Pos with Off_ - all off
- **_6-Pos_ - FSW1 on**
- **_2 x 3-pos_ - FSW1 and FSW4 on (one from each group)**
- _6 x 2-pos_ - all off
- _Momentary_ - all off

**Comment by mawzthefinn** [comment]
Just tested now, and while state is remembered through changes/reboots the default seems to be All off for all configurations until a state is selected.

**Comment by mikedkelly** [comment]
For my use case, since I now have these mapped to a VAR mix, I set the default weight to the value for manual flight mode so that the Tx always boots in that mode. Earlier, I was always nervous that I would forget and have it be in something crazy like take-off mode when I armed the model for taxi in the pit.
