### ISSUE TITLE
Scripts not saving data when simulator or transmitter turned off

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#1402]
The attached script was working correctly when it was first written about a month back. Not sure which Alpha version was in use at the time. It would count up each time a trigger condition was active and display the total. When the simulator or transmitter were turned off, and then back on, it would display the total from the previous session and count up from there. 

It does not save, and then recall the total value now, but instead returns to 0 each time the transmitter is turned on or simulator is started. I can force it to save the total by going into Configure Widget and changing one of the values. When this is done before exiting from the simulator (or turning the transmitter off), it will recall and  use the previous total on the next use of the transmitter or simulator. 

[counter.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7965176/counter.zip)

**Comment by bsongis-frsky** [comment]
You will have to register your widget as persistent, otherwise it will be saved only if a parameter is modified in its form (from configure function)

**Comment by bsongis-frsky** [comment]
`persistent` attribute added to `system.registerWidget(...)`

**Comment by dwheel** [comment]
> You will have to register your widget as persistent, otherwise it will be saved only if a parameter is modified in its form (from configure function)

What is the correct syntax for this? Can  you show me an example?

Will it be added to 1.1.0 rc2?
