### ISSUE TITLE
Unable to categorize models

### ISSUE THREAD

**Issue by KevinFairgrieve** [FrSkyRC/ETHOS-Feedback-Community#1404]
Horus X12S
HW ISRM 1.1.0 FW 2.1.6 EU-LBT
ETHOS 1.1.0 -RC1

I have updated the SD card contents and added the EN sound pack. I am lead to believe that there should be a small + to the top left next to the bar that says Uncatergorized, as you ca see from the attached image the + is not present.

![DSCF0277](https://user-images.githubusercontent.com/20424058/151709976-1adf4df8-8ba7-4918-92af-d4b2913ee093.JPG)

The image below is from RCGroups and shows the +

![screenshot-2022-01-17-39674](https://user-images.githubusercontent.com/20424058/151710010-31309adb-4d8c-40d1-b2fc-a9850b20f027.jpg)

**Comment by MIKE-DAILEY** [comment]
The lower screen is from a X20S.  The Horus systems work slightly different.  Long press the PgDn key to Rename Folder and Create Folder option.

**Comment by KevinFairgrieve** [comment]
> The lower screen is from a X20S. The Horus systems work slightly different. Long press the PgDn key to get Rename Folder or Create Folder options. I'll add a note to my RCG post.

Thanks, that works for me.
