### ISSUE TITLE
can’t play sound files in special functions menu

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#1405]
So i’m having a bit of an issue.
firmware is 1.0.19
and the sd card contents are from 1.0.18
earlier before i upgraded to 1.0.19 i had in the special functions added a “play track” to announce ignition on & off.
after the upgrade these options no longer work.
when i go into edit & scroll down to play file all that shows up us WAV & i cant select anything else.
i tried everything & even deleted the audio & bitmap files & downloaded the sd contents from 1.0.18 & unzipped audio & bitmaps onto the sd card all over again.
but nothing works. 
its as if the audio folder is inaccessible to the system entirely. bitmaps works perfectly & my images show up just fine

**Comment by bsongis-frsky** [comment]
which radio?

**Comment by bsongis-frsky** [comment]
if X20, did you do exactly as described in the manual, wav files on SD in the right directory, bitmaps on FLASH?

**Comment by ravikoth** [comment]
Hi.
This is the X20

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ravikoth** [comment]
Yes its the X20 & the SD card contents were unzipped & the resultant audio & bitmap files were installed on the SD card.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ravikoth** [comment]
Could you mail me the file directory instructions.
I'll try all over again.
This is what i am doing -

X20 Flash folder on github after unzipping yields a single bitmap file. This file i put on the internal memory of the radio

Then i download the SD card contents which when unzipped yields 2 files.
1) Audio
2) Bitmaps
These i put on the SD card on the top of the files structure.

Then i download the X20 FCC.zip folder.
Which when unzipped yields a firmware.bin file. This i put in the root of the SD card.

Then i unplug the usb cable & it writes the firmware. I then checked the release & i see 1.0.19 & all the sounds native to the radio work just fine & i also see & can play the wav files in file manager. But no wav file  options show up in the special functions menu. What am i doing wrong?

Regards
Ravi



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MIKE-DAILEY** [comment]
We answered your question that you posted on RCG.  But the file paths are also here on GitHub https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/ETHOS-File-Storage-and-Firmware-Flashing

Most likely you wrote over your user sound wav files when you installed the new sounds from GitHub.

**Comment by ravikoth** [comment]
thanks,
did a complete reinstall & out everything where it belongs & all is well.
thanks so much
ravi

Sent from my iPad

On 31-Jan-2022, at 7:26 AM, Jet_Flyer ***@***.***> wrote:

﻿

We answered your question that you posted on RCG. But the file paths are also here on GitHub https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/ETHOS-File-Storage-and-Firmware-Flashing

Most likely you wrote over your user sound wav files when you installed the new sounds from GitHub.
