### ISSUE TITLE
1.1.0rc1 System General Icon missing

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1407]
After flashing 1.1.0rc1 on two X20S radios, the Gear icon is missing in System -> General. 
OK in the simulator.

**Comment by MIKE-DAILEY** [comment]
Did you update the bitmaps?

**Comment by gernotw** [comment]
how to update?

**Comment by MIKE-DAILEY** [comment]
Download the Tandem_FLASH.zip from the RC1 release files.  Unzip the file.   Connect the X20S to your PC.  Copy the new bitmap files to the X20S flash drive.

**Comment by mmasch** [comment]
Hi. 

Forgot to mention I’m on X20S-EU.. 

Downloaded the X20S-EU firmware. 
Downloaded the TANDEM_SD.zip. This folder contains only one «user» folder with 6 model images and one «gps» folder with 1 image. 
Did an install. Icon missing.

Re-downloaded the TANDEM_SD file, removed my old «bitmap»folder and copied in the newly downloaded «bitmap»folder. 

Still missing the gear icon in System -> General screen.


B.r. Morten Masch.

**Comment by MIKE-DAILEY** [comment]
You need the Tandem_FLASH.zip.

**Comment by mmasch** [comment]
OK. Will try after dinner  :-)
Thanks.

Morten.

**Comment by MIKE-DAILEY** [comment]
Look here https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/testing/1.1.0-RC1  Tandem_FLASH.zip.

**Comment by mmasch** [comment]
Thank’s. 
Have fixed it. All OK now. 
Sorry to have risen the issue on GitHub...

Morten.
