### ISSUE TITLE
System Menu Change recommendations

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1408]
Upgraded to 1.1.0 RC1 and am very impressed overall with the re-organization in the System Menu, collapsing much on the General menu

I do have a couple suggestions to clean up some of the wasted space. 

1. Sticks menu should become a tab in Hardware, it's something you won't change regularly.
2. Wireless should become a section in General. It's a waste of a tile for a couple settings. 

That would allow System to become a single page, and leave a tile free for a future menu.

**Comment by bsongis-frsky** [comment]
1. Stick Menu. Agreed
2. Wireless is something on X20S

**Comment by bsongis-frsky** [comment]
You forget the custom tools from the Lua scripts

![image](https://user-images.githubusercontent.com/50834778/151856119-4268d82b-79d4-41f5-a6c9-e260647b36ac.png)

**Comment by mawzthefinn** [comment]
Interesting, I do not have those.

Upgraded from 1.0.19, the TANDEM_SD.zip for RC1 only contains the bitmaps folder

**Comment by bsongis-frsky** [comment]
Won't be changed now, we don't plan to reduce the count of items in the System Menu
