### ISSUE TITLE
S-Port telemetry assigned on pin5 R9MX not working 

### ISSUE THREAD

**Issue by ucakar** [FrSkyRC/ETHOS-Feedback-Community#1412]
Dear Sir or Madam,

I own X20, and when using my R9SX receiver, when i try to program pin5 to be used as S-port telemetry, I can define it, bit there is no data, when i connect telemetry sensor on pin5. If I use externap Sport connection the telemetry works.

I did the same with my Taranis X lite s with 900mhz tx and set pin5 to S-Port and telemetry worked fine.

I am using Ethos 1.019

http://www2.arnes.si/~aucaka1/modelarstvo/arduinopromini_GPS/r9sx.jpg

Thx

Andrej

**Comment by bsongis-frsky** [comment]
Not sure it's an ethos issue
