### ISSUE TITLE
Models disappear after adding new (incomplete) model

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#1413]
Bug

In RC 2, when adding a new (incomplete) model all other models disappear because a modelxx.bi is written instead of a modelxx.bin, models are still on the SD, but not shown in the model select window.

to recreate:
- Press +
- Press 'Other' and ->
- fill in name only and enter and press ->
- now go to model select, it shows blank and a modelxx.bi is written on your SD

To solve:
create a new model with name AND picture and all models return in the model select window.

**Comment by bsongis-frsky** [comment]
2 people did the test, we cannot reproduce your issue

**Comment by ahvink** [comment]
See attached video, bug is still present in latest release.

I start with 4 models, try to add one, but instead all models disappear from the screen.
After reboot, Ethos starts with model wizard, when completing the wizard all models return on the screen

[http://files.alfsoft.com/ethos_bug.mov](url)

**Comment by bsongis-frsky** [comment]
Reproduced, you forget to tell us the name of your models folder (which I think is long enough).

**Comment by ahvink** [comment]
> Reproduced, you forget to tell us the name of your models folder (which I think is long enough).

ALF's Models, which is shorter then Uncategorized ;-)

**Comment by bsongis-frsky** [comment]
Not exactly, "Uncategorized" is not a real folder on the SD card (and it is translated into the user language)
