### ISSUE TITLE
request : scroll between screens with scroll wheel

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1414]
by using the scrollwheel on homescreen we are scrolling through the widgets.
if the last widget is reached the screen switch to the next screen and so on.
i think its better to scroll through the screens instead of through the widgets.if you want to scroll to a widget on a screen you hit enter on that screen. now you can scrollonly through the widgets on that screen. when you hit RTN you switch back to "screen scroll mode"

**Comment by i3dm** [comment]
screen scroll is done by the page button

**Comment by loetefix** [comment]
I know that screen scroll is done. But its not realy comfortable. Page back is realy annoying.

**Comment by bsongis-frsky** [comment]
This is another way of scrolling which is different from current way. It's an easy change but I don't want to do have more users unhappy, I will keep what has been discussed and decided at the start of the project.

**Comment by loetefix** [comment]
And if you make it configurable in Home Keymap menu?
