### ISSUE TITLE
models with upper case filenames don't show up

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1415]
I would think I would name a model file using whatever case I would like, but that isn't the case. I had a template I pushed to my 1.1 RC2 radio with the name DLG.bin and it wouldn't show up in the model picker.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/152656173-15187718-1577-43f7-a698-d211245308c9.png)

**Comment by bsongis-frsky** [comment]
I cannot replicate it

**Comment by guycnicholas** [comment]
[models.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8009265/models.zip)

I have attached my models folder, and I dropped two models on there this time, one at the root named ABC.bin, and the other inside my templates folder named, DLG.bin, neither shows up on my 20S running RC2

**Comment by bsongis-frsky** [comment]
You may have your name in uppercase, but the extension must be .bin, not .BIN
