### ISSUE TITLE
RSSI Critical Alarm

### ISSUE THREAD

**Issue by wattscr1** [FrSkyRC/ETHOS-Feedback-Community#1416]
I fly a plane using FrSky receiver S6R.  With 1.0.18, there were no issues for me.  When I updated to 1.0.19, I started getting the RSSI Critical Warning.  I am flying my normal flight field and pattern.

**Comment by Nerenye** [comment]
I´m having a lot of rssi warnings with grx8 aswell. only like 75 meters away. rssi shows mostly 75+ but when i turn it sometimes dips for like 0.1 sec below 40 and triggers the warning. would be good to have a 0.5 or 1 sec duration delay before warning is triggert. some planes have a lot of carbon an therfore blocking reception during turns. there is no point on spamming the pilot with rssi low warnings. it would only result in the pilot ignoring the warnings and at some point loosing control

**Comment by Hobby4life** [comment]
> I´m having a lot of rssi warnings with grx8 aswell. only like 75 meters away. rssi shows mostly 75+ but when i turn it sometimes dips for like 0.1 sec below 40 and triggers the warning. would be good to have a 0.5 or 1 sec duration delay before warning is triggert. some planes have a lot of carbon an therfore blocking reception during turns. there is no point on spamming the pilot with rssi low warnings. it would only result in the pilot ignoring the warnings and at some point loosing control

Also after flashing to v1.1.0 Alpha 2?

**Comment by Nerenye** [comment]
Haven´t tested. Thread Opener is talking about 1.0.19 wich i´m on aswell.
and my suggestion is not bound to any version i guess?

**Comment by bsongis-frsky** [comment]
1.1.0 is more tolerant with small RSSI alarms

**Comment by bsongis-frsky** [comment]
Please check with 1.1.0 RC2

**Comment by Nerenye** [comment]
> 1.1.0 is more tolerant with small RSSI alarms

I thought we´re not supposed to fly with Release Candidates?

**Comment by i3dm** [comment]
1,1,0 has just been released, you can check.
@bsongis-frsky  we need a configurable time for sensor warnings, and sensor lost warnings - this will help.
i have another issue open about sensor lost occasional warnings - is this also dealt with on 1.1.0?
