### ISSUE TITLE
Models not able to copy on fresh v1.1.0 RC2 installation

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1417]
I am not able to copy my models:

From:
X20 v1.1.0 RC2

To freshly installed:
X10 Express v1.1.0 RC2

Getting error opening file, Starting model wizard.

Groups are visible, models not.

#1413 Related?

**Comment by bsongis-frsky** [comment]
I need your model file.

**Comment by bsongis-frsky** [comment]
I cannot replicate here with my current models

**Comment by Hobby4life** [comment]
What I did:

1. I delete models folder on x10
2. I copy the X20 models folder to X10
3. Start X10, get error, and model wizard starts.

Now I have done the follwoing

1. I delete models folder on x10 and restart radio.
2. Got error, and in starts model wizard.
3. There is model01.bin in models folder.
4. Now I copy X20 model folder to X10
5. in folder /models/drones/ there is model01.bin I rename this to for example model50.bin
6. Restart radio, and it starts in the default model01.bin but all other models are loaded too.

I gues X10 does not look in subfolders on first init for model01.bin only in root of /models

**Comment by bsongis-frsky** [comment]
As written on Skype if you delete your current model you will get the Wizard launched with an error, this is normal
