### ISSUE TITLE
1.1.0RC2: File manager scroll issue when running widgets

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1418]
X20 1.1.0RC2: this happens on a model with widgets loaded:
https://www.youtube.com/watch?v=kSDCxWHBXgw&feature=youtu.be
trying to go into the SD firmware TDISRM library, and it jumps to AR widget library.
model without widgets loaded worked fine.

**Comment by bsongis-frsky** [comment]
Limit for path size increased
