### ISSUE TITLE
Ethos v 1.1.0 horus sd folder

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#1419]
I can't find the horus sd folder for ethos v 1.1.0 do we take the folder from ethos v 1.0.18.

**Comment by KevinFairgrieve** [comment]
Likewise. I use my old TX12S to perform upgrades before applying them to my X20.
I also do not see an X12S Simulator.

**Comment by Hobby4life** [comment]
Yes use the RC2 content.
