### ISSUE TITLE
Add a "dedicated channel view" for analyzing mixer components of one channel

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#142]
Hi,

The topic is: clarity & comprehensibility of the channel behaviour when several mixers act on one output channel.

As long as one stays within the predefined mixer libraries and the number of mixers remains low, the configuration is still manageable very good and comprehensible, since usually only a maximum of two to three mixers with a simple sum function are routed to one channel.

Through a reasonably clever arrangement / sequence, you can quickly access the individual mixers and see their respective "output".
So far, so good !

However, as soon as you start to use free mixers, use a function other than adding, and do not pay attention to the optimal order of the mixers, you are walking on thin ice if you want to understand the result of the output (channel) later on.
 
There is no central "view" that specifically shows how the individual mixer components built the final result on a channel.

Can anyone of you roughly interpret how a result on channel 10 will come about?
Note: one mixer uses multiplication, another has a constant offset, two mixers are out of view range !
And my  grandson unfortunately dropped the crystal ball last week.

![Horus](https://user-images.githubusercontent.com/20392683/116364001-06a8e680-a804-11eb-9207-03957b461b26.jpg)

My suggestion, relatively spontaneous, without having checked other options, just as an idea:

The mixer menu should have another view (e.g. second page) where the user first choose a  channel output via scroll wheel.
Then the results are displayed, filtered to mixers that have defined this channel in the output.
The list should display other columns than in the "standard view" in order to show function (add, replace...), status (active=bold) and at least offset/weight for the mixer channel.
It would also make sense to show "value bars" and the output values of the respective mixers in a reduced size.

![proposal chview](https://user-images.githubusercontent.com/20392683/116364086-1c1e1080-a804-11eb-947f-cc220b598f9f.png)

**If the aim of Ethos is to enable the user to create models completely without PC support, GUI support for analyzing and debugging the settings is also a must.**
The above suggestion is just a rough idea, I don't expect it to be implemented in the short term, there are enough other urgent things.

**In the medium term, however, I consider such a "view" to be absolutely mandatory.** 

regards
Udo

**Comment by keiner0815** [comment]
I like the idea, would make life easier, especially when using more complex models.

Also like the suggestion how to make it visible!

**Comment by mawzthefinn** [comment]
This was added as 'View Per Channel' in v1.1.0
