### ISSUE TITLE
1.1.0: create "scripts" folder in SD content

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1420]
Just as the title says.
dont leave it to the user to do it.. create it as part of the SD content by default.
in fact dont leave ANY folders to be created by the user. it makes no sense.

**Comment by Hobby4life** [comment]
Predefinition of folders is a good idea.

**Comment by kakashi2018** [comment]
@i3dm  can you tell where to put the lua script files on sd card?

**Comment by i3dm** [comment]
> @i3dm can you tell where to put the lua script files on sd card?

SD/scripts
you need to create this folder

**Comment by bsongis-frsky** [comment]
Will be done on new radios
