### ISSUE TITLE
1.1.0 suggestion: scroll menu roll back

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1421]
Please make the menus scroll roll back, for example system menu, if you reach end of page 2 and keep scrolling, menu will go back to page 1.

**Comment by bsongis-frsky** [comment]
This is exactly the opposite which has been requested some months ago. At the time I asked many people which was the best choice

For those who have access to this old repository
https://github.com/FrSkyRC/ETHOS-TEST/issues/85
