### ISSUE TITLE
1.1.0 : logo and colour

### ISSUE THREAD

**Issue by EthosUser** [FrSkyRC/ETHOS-Feedback-Community#1422]
Hello,
In the system section, the General logo is not displayed.
By changing the highlighting colour, the scrollbars in the menus remain with the default colour (orange)

**Comment by Hobby4life** [comment]
I assume you are using a x20, did you update your x20 internal flash with the latest bitmaps?

TANDEM_FLASH.zip

**Comment by bsongis-frsky** [comment]
Did you upgrade all your bitmaps (flash on X20, SD on X10 Express)

**Comment by Nerenye** [comment]
Scrollbars remain orange even with updatef flash

**Comment by bsongis-frsky** [comment]
Ethos 1.1.1
![image](https://user-images.githubusercontent.com/50834778/152738878-aceb06ad-81c6-4b60-ab92-d38965574ad0.png)

**Comment by EthosUser** [comment]
> Avez-vous mis à jour tous vos bitmaps (flash sur X20, SD sur X10 Express)

yes and I just did it again but it's still the same thing, no ico
![Icon](https://user-images.githubusercontent.com/88803345/152823743-7f00ae47-a0d8-47d1-bb3c-4bb793f3489a.jpg)

**Comment by Hobby4life** [comment]
You need to use TANDEM-FLASH.zip to update the internal flash of your X20 not the SD card

**Comment by EthosUser** [comment]
> Vous devez utiliser TANDEM-FLASH.zip pour mettre à jour le flash interne de votre X20 et non la carte SD

I have used TANDEM_FLASH

**Comment by Hobby4life** [comment]
> 

When you hook up your radio to your pc.. you get too see 2 drives.
One drive only shows a bitmaps folder.. this is where you have unpack TANDEM-FLASH.zip

![image](https://user-images.githubusercontent.com/55426642/152854324-6ce1707a-cdf3-4a3c-ade0-798679ee0db9.png)
