### ISSUE TITLE
Installing lua files

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#1423]
Hi
X10s isrm
Ethos v1.1.0
I see there there are some lua files on this website under view codes tab, but I don't know how to download them can some one please help.
Thanks
Scott

**Comment by bsongis-frsky** [comment]
Just put them in your /scripts directory, at the same level than /bitmaps or /models

**Comment by Liverboy77** [comment]
How do I put them in the scripts folder, there is no download link and drag and drop doesn't work.
Thanks
