### ISSUE TITLE
1.1.0: slow image boot time

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1424]
1.1.0 release compared to RCx versions:
a single widget with one properly formatted BMP565 background image takes 6-7 seconds to load. was about 3 seconds for the same widget with RC1 / RC2. a definite slow down compared to former versions.
please check.

example widget attached
[GAS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8010580/GAS.zip)
.

**Comment by kakashi2018** [comment]
@i3dm can you tell how to use lua in x20 tx. I have copied them to scripts folder but dont know how they work?

**Comment by Hobby4life** [comment]
> 1.1.0 release compared to RCx versions: a single widget with one properly formatted BMP565 background image takes 6-7 seconds to load. was about 3 seconds for the same widget with RC1 / RC2. a definite slow down compared to former versions. please check.
> 
> example widget attached [GAS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8010580/GAS.zip) .

Your images are too big in filesize... they should be arround 750kb

Did you use my online converter?

Dont put in BMP565 images in the converter, they will come out scrambled ;-)

**Comment by i3dm** [comment]
> > 1.1.0 release compared to RCx versions: a single widget with one properly formatted BMP565 background image takes 6-7 seconds to load. was about 3 seconds for the same widget with RC1 / RC2. a definite slow down compared to former versions. please check.
> > example widget attached [GAS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8010580/GAS.zip) .
> 
> Your images are too big in filesize... they should be arround 750kb
> 
> Did you use my online converter?
> 
> Dont put in BMP565 images in the converter, they will come out scrambled ;-)

i did, will try again.

**Comment by i3dm** [comment]
> > 1.1.0 release compared to RCx versions: a single widget with one properly formatted BMP565 background image takes 6-7 seconds to load. was about 3 seconds for the same widget with RC1 / RC2. a definite slow down compared to former versions. please check.
> > example widget attached [GAS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8010580/GAS.zip) .
> 
> Your images are too big in filesize... they should be arround 750kb
> 
> Did you use my online converter?
> 
> Dont put in BMP565 images in the converter, they will come out scrambled ;-)

just converted them again to about 750kb.
no change at all. boot up time of the widget is still super slow.
attaching widget with new files.

[GAS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8010624/GAS.zip)

**Comment by i3dm** [comment]
i reconverted all images and it seems to run better now.
how could images from other widgets affect this? i load them on all widget outside of init. makes no sense.
will close issue until further investigation.

**Comment by i3dm** [comment]
another friend verified - RC2 is faster ro load images than 1.1.0 release.

**Comment by bsongis-frsky** [comment]
RC2 is exactly the same than 1.1.0 final
Please check all your scripts, if one script loads a big bitmap on init it will slow down the whole radio

**Comment by i3dm** [comment]
none of my scripts load anything on init.
there is a diff between the versions.
