### ISSUE TITLE
Archer RS and Xact servos - sensor lost

### ISSUE THREAD

**Issue by ZS-Man** [FrSkyRC/ETHOS-Feedback-Community#1425]
Hi
on Archer RS a 4x Xact 5701 connected by FBUS I get "Sensor lost" every few seconds. Servos works, all telemetry values seems OK, but radio still reports a problem about lost sensor....

X20S EU
Ethos: 1.1.0  (today released stable? https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases )
RF firmware: TD 2.2.0
Archer RS fw: 2.1.8
2x Xact 5701 and 2x Xact HV5701 fw:  v1.5.7

If I bind model to my X10S Experess with OTX 2.3.14, everything works fine, no sensor lost message.

Is this problem radio/RX/servo or my model misconfig?

Thanks.

**Comment by bsongis-frsky** [comment]
Which sensor raises this error? Try to delete all one after one to find it

**Comment by ZS-Man** [comment]
Hi,
I am not able find bad sensor..... :-(   Lost sensor is still there.
It looks like when I have  sensors on whatever one servo (all other deleted), "Sensor lost" will appear once every few minutes. 
If have sensors of two servos, sensor lost appear more often. With three servos, even more often. etc....

Any idea for better verification and finding problematic sensor?


If I initialy setup servos, I connect one by one to RX and manualy setup PhyID/AplID.
First servo 11/01, second servo 12/02, etc... Is it right?

Another strange situation:
On telemetry screen select one servo sensor (for example SRV3 Status), open Edit and see ID: 11 6801 (ISRM Rx0)
Then open Device config on same sensor and see randomly detected PhyID/AplID (11/01, 12/02, 13/03, 14/04). it's alright?

Is possible reconfigure one servo if all others are connected to RX? Or connect all new servos to the RX and then set them up?

**Comment by ZS-Man** [comment]
Testing continues.....
Another model, new RX (Archer RS), new servos. Same problem with Sensor lost.....

Change RX to Archer R4, and problem is gone. After 30min playing with radio, no problem with sensors.

On X10S Express + OTX,  both RX works fine, without sensor lost.

**Comment by KAID-YANG** [comment]
Hello, what is the Data Rate of your hv5701?

**Comment by ZS-Man** [comment]
Hi,
on all 4 servos I left default 1000 (ms ?)
