### ISSUE TITLE
Release 1.1.0 X10-ISRM bootloader

### ISSUE THREAD

**Issue by dunback** [FrSkyRC/ETHOS-Feedback-Community#1426]
The Release 1.1.0 X10-ISRM includes a new (larger) bootloader.bin file. Should this be installed prior to the firmware?

**Comment by bsongis-frsky** [comment]
It's not mandatory, both will work almost the same

**Comment by dunback** [comment]
Thanks. It is very much larger which I thought was strange.

**Comment by bsongis-frsky** [comment]
Good catch, I cannot explain it and I need to investigate further

**Comment by bsongis-frsky** [comment]
More functions have been added inside the new bootloader, but they are not used anywhere, bootloader in 1.1.1 won't have them and will return to the original size

**Comment by dunback** [comment]
Excellent! Thanks so much! Always good to have a complete explanation and closure. 

Keep up the great work!

Cheers for now!

George Coupar
