### ISSUE TITLE
Adding aircraft categories, suggestion.

### ISSUE THREAD

**Issue by DaySpeed955i** [FrSkyRC/ETHOS-Feedback-Community#143]
Categories are Airplanes, Glider, Multi and Other.

If I may suggest for the user to be able to create categories like Jets, Warbirds, UMX or whatever would be nice.

Thanks to the great development team of ETHOS!

**Comment by bsongis-frsky** [comment]
good idea, will try to add this feature when time allows

**Comment by IJK-CZ** [comment]
I would prefer to have categories as optional, not mandatrory. Alphabetical sort of models (without categories) may be better for some users.

**Comment by DaySpeed955i** [comment]
Just have 1 category then or none, I want to be able to create categories so I do not have to scroll through 60 or more aircrafts.
The beauty of ETHOS is that it's possible:)

Merci Bertrand!

**Comment by MrD-RC** [comment]
I agree with this. The categories on my X10S Express are really useful. It would be handy if they were alphabetically ordered, or could be manually ordered too.

**Comment by bsongis-frsky** [comment]
Linked to #224

**Comment by TWSreviews** [comment]
I have a lot of wings and was surprised there was no wing category with elevon mixes
