### ISSUE TITLE
Feature request: An option to create a new sensor that shows the lowest cell voltage from the lipo sensor

### ISSUE THREAD

**Issue by npirkes** [FrSkyRC/ETHOS-Feedback-Community#1430]
Hi, 

Before using the ETHOS OS, I use to set my flight alarm according to the lowest cell voltage when I used an electric aircraft.
I use to get this parameter by creating a new sensor just like the DIY or calculated creating sensor feature that the OS already have.

It may be wonderful if you could add this feature to the OS.

Thanks in advance,
Nimrod

**Comment by bsongis-frsky** [comment]
Perhaps you didn't search enough or you found Ethos so intuitive that there was no need to read the manual ;)
