### ISSUE TITLE
Request: make boot up photo changeable

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1431]
Please make the boot up photo (FR logo) changeable.
thanks.

**Comment by Hobby4life** [comment]
Its embedded in bootloader.

But option could be.

Remove logo from bootloader. And add it to ETHOS. In general menu selectable boot.bmp image.

**Comment by i3dm** [comment]
> Its embedded in bootloader.
> 
> But option could be.
> 
> Remove logo from bootloader. And add it to ETHOS.
> 
> Boot.bmp
> 
> (In general menu selectable boot image?)

thats exactly what i mean, make it a splash image that can be changed.

**Comment by bsongis-frsky** [comment]
The logo is displayed before the SD is initialized

**Comment by i3dm** [comment]
> The logo is displayed before the SD is initialized

cant you pull the logo from flash and allow it to be changed then?

**Comment by loetefix** [comment]
Is it realy needed? Ok switching off for faster boot would be useful. But changing logo?

**Comment by i3dm** [comment]
> Is it realy needed? Ok switching off for faster boot would be useful. But changing logo?

not changing logos but adding a splash screen is usefeul yes.
