### ISSUE TITLE
Thanks Again.

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1433]
Thanks again for all your work on firmware and LUA scripts.
If for certain LUA scripts, we could have the explanations for the programming, that would be great?? (lua gauge:  volt  ;  amp  ;..).

**Comment by bsongis-frsky** [comment]
We have written some documentation for all functions and provided examples in this repo. Please ask questions on the dedicated thread on RCG
