### ISSUE TITLE
X20 and XJT telemetry issue

### ISSUE THREAD

**Issue by kjfooks** [FrSkyRC/ETHOS-Feedback-Community#1434]
X20 running Ethos 1.0.19 with xjt lite module.  D8R-XP receiver with high precision vario.
Ethos telemetry screen shows RSSI, Rx, ADC1 and ADC2 from the D8R-XP receiver, but no vario.  Any help gladly received!

**Comment by mawzthefinn** [comment]
There was additional support for D series telemetry added in v1.4.3

@kjfooks did this update solve your issue?

**Comment by bsongis-frsky** [comment]
I am afraid no, I have only added a few sensors, not the vario. Will do in 1.4.4 as it should not be difficult anymore now

**Comment by bsongis-frsky** [comment]
Vario has been added today. 
So it will work in 1.4.5

**Comment by bsongis-frsky** [comment]
I think it is not an Ethos issue, but something in the XJT Lite

X12S (OpenTX) + Internal XJT Module + D8R-II + Vario (D-Telemetry)
=> Alt and VSpd sensors work well

I have tried this morning these setups:
XLite-Pro (OpenTX) + XJT-Lite External Module + D8R-II + Vario (D-Telemetry)
=> No Alt, no VSpd
