### ISSUE TITLE
New FLVSS Lua Wiget

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1435]
Anyway to be able to set the voltage per cell before the colors change? What are the parameters for the per-cell voltage changes before alarm? Thanks

![flvss](https://user-images.githubusercontent.com/46627889/152889392-6f73b36c-5c52-47b5-83a6-5919685f3fa9.jpg)

**Comment by i3dm** [comment]
is this widget a part of ethos?

**Comment by mmasch** [comment]
It is not installed automatically.
You can find it under the "code" tab (top left on this page).
Open the folder named "lua".
There you'll find the script "flvss"
Download and save it in your "scripts" folder on your SD card.
If the "scripts" folder is non existent, just create a new folder and name it scripts on the root of the SD card.

Hope this helps.

**Comment by wmayvis** [comment]
Great!! This is my created widget and it's not a part of Ethos :-)
[ninodesposati](https://github.com/ninodesposati) please contact me if you need help by your issue?

**Comment by wmayvis** [comment]
> is this widget a part of ethos?

No, I made it.
