### ISSUE TITLE
SRFF with more inputs

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1437]
Hello!
I am aware that ETHOS is not a wish concert. Nevertheless, I would like to express a wish.
I have built a kind of stepping mechanism from one SRFF and 2X AND links each in order to have a different telemetry value announced for each time a button with switch SH is pressed. With 9 values, this results in 27 logical switches. 
Now my wish: if the set input had 2 AND-linked inputs and the reset input had 2 OR-linked inputs, I could save the two ANDs for each announcement. Would something like this be possible?
Thank you for your patience

**Comment by Hobby4life** [comment]
#1232 related

**Comment by Wolepo** [comment]
But my wish relates to SRFF

**Comment by hrenz** [comment]
we need a counter funktion for steps functions

**Comment by mawzthefinn** [comment]
@RC-Soar solved this a while ago, details here:

https://www.rcgroups.com/forums/showpost.php?p=47585775&postcount=10088

**Comment by bsongis-frsky** [comment]
The AND with N inputs and OR with N inputs is available now.
