### ISSUE TITLE
Main Voltage displayed as % in LS

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1438]
The voltage is incorrectly shown as a % rather than V in 1.1.0

![image](https://user-images.githubusercontent.com/96293240/153032058-0a1e86da-a020-429a-8cad-0d1c8d0ed3eb.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/153153727-0016b264-e5d8-4fa3-957e-a2a08a1e009f.png)

![image](https://user-images.githubusercontent.com/50834778/153153758-df479804-4b33-48f6-b3f3-272a43dabbe7.png)
