### ISSUE TITLE
Were is the Ringlimiter for Heli and for Vectorcontrol

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#144]
I cant see a ringmixer for Heli
or no the ringmixer for jetmodell

**Comment by prikrylm** [comment]
== https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/124

**Comment by hrenz** [comment]
ring mixer in % of a circle for Heli and vectrocontrol

**Comment by hrenz** [comment]
example from Graupner Ringlimter
![image](https://user-images.githubusercontent.com/6217896/201394417-50cdbec3-414a-4542-b94c-423cd105d651.png)

**Comment by prikrylm** [comment]
Is there "ring limiter" in 1.5.x already?

**Comment by prikrylm** [comment]
According to OTX code, ring limiter is 10 rows of C++ code, ([here](https://github.com/opentx/opentx/blob/22e9e9a27dc5bb6cfe0a0ad6fa49e092e1586c39/radio/src/mixer.cpp#L590)). Please, it is not so difficult. :)
