### ISSUE TITLE
Have to confirm switch to a new model

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1444]
While it was possibly me who requested confirmation of switching to a new model while the tx was connected to the rx, it seems un-necessary to require this confirmation if the tx is not connected to an rx. 
Or maybe this could be a user specified option? (Obviously still with confirmation required if an rx is connected what-ever is selected).

**Comment by Tonio62** [comment]
Fully agree, there is one confirmation too many when the radio is not connected to any receiver i think
