### ISSUE TITLE
Lua Enhancement - Open and read simple text files

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#1445]
Please add a method to open and read simple text files with Ethos Lua. Text to be used as variables in the script for labels, messages, etc.

**Comment by Hobby4life** [comment]
Lua already has this function.

do()

**Comment by dwheel** [comment]
Have searched for it in the docs and can't find any information. Can you show me an example in a lua script?

**Comment by Hobby4life** [comment]
> Have searched for it in the docs and can't find any information. Can you show me an example in a lua script?

check my widget: https://github.com/Hobby4life/H4LGPSMAP

**Comment by guycnicholas** [comment]
@dwheel 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/5494702/153420193-588b0c18-c709-49c4-b63e-a7420fb22ad6.png">

**Comment by Hobby4life** [comment]
I think do() is more what he needs.

**Comment by guycnicholas** [comment]
That may work better for you, but what I was saying is that all the libraries listed in my screen grab are available to you from Ethos.  Here is a link to info about file operations: https://www.tutorialspoint.com/lua/lua_file_io.htm
