### ISSUE TITLE
Request new feature for the Wizard: Add an option to create a model with FrSky gyro

### ISSUE THREAD

**Issue by npirkes** [FrSkyRC/ETHOS-Feedback-Community#1447]
Hi, 

I came up with an idea that could be very useful for those who use a product with a gyro of FrSky (such as one of the gyro receivers or one of the RBs)

Since FrSky gyro correspond to specific channels such as ch9(gain) ch10(gyro mode) ch12(setup/panic), it may be really nice if a user could just check this option while creating a new model in the Wizard and it will add automatically these channels without assigning them a specific switch (just like Flaps)  

Thanks a lot.

**Comment by i3dm** [comment]
thats a great idea

**Comment by i3dm** [comment]
> ![image](https://user-images.githubusercontent.com/58321103/153836338-6eafe868-78ce-44d6-9401-04be7ac8274c.png)
> 
> Will a new type - Self-Stab RX in wizard be OK? It will help users create all the channels automatically. You just need to give the name and the bitmap to the model.

yes
i would add a default image in the menu that shows something like an airplane with stabilization arrows

**Comment by ninodesposati** [comment]
Very Cool!! Most of my planes add these types of receivers!

**Comment by npirkes** [comment]
Instead 

> ![image](https://user-images.githubusercontent.com/58321103/153836338-6eafe868-78ce-44d6-9401-04be7ac8274c.png)
> 
> Will a new type - Self-Stab RX in wizard be OK? It will help users create all the channels automatically. You just need to give the name and the bitmap to the model.

Instead of making a new category, you may just add a checkbox to present options and create those 3 channels without configuring a SW to each of them (just like how flaps configured after the Wizard)

I think it would be a much simpler way as well as you can add this option for both airplane and glider Wizards

**Comment by i3dm** [comment]
> Instead
> 
> > ![image](https://user-images.githubusercontent.com/58321103/153836338-6eafe868-78ce-44d6-9401-04be7ac8274c.png)
> > Will a new type - Self-Stab RX in wizard be OK? It will help users create all the channels automatically. You just need to give the name and the bitmap to the model.
> 
> Instead of making a new category, you may just add a checkbox to present options and create those 3 channels without configuring a SW to each of them (just like how flaps configured after the Wizard)
> 
> I think it would be a much simpler way as well as you can add this option for both airplane and glider Wizards

agreed, thats even better

**Comment by ninodesposati** [comment]
I'd like to add pre-programming Channel 9 for the GAIN. A premade curve for the POT (with 2 points) so that the pot has a full range from 0-100.

**Comment by Hobby4life** [comment]
> I'd like to add pre-programming Channel 9 for the GAIN. A premade curve for the POT (with 2 points) so that the pot has a full range from 0-100.

Also channel 10 thru 12.

There are 2 operation modes.

1. off + Stab + Level
2. off + Stab + Level + Hover + Knife edge

Would be nice if a user has an option to choose between these 2.

**Comment by NorbertHeli** [comment]
Thats a great idea and makes live easier

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/160175890-cdeecad8-d806-4ab9-bc11-6c9dc76781c6.png)

**Comment by bsongis-frsky** [comment]
Model / Edit Model

![image](https://user-images.githubusercontent.com/50834778/160175983-95ac6ec5-ec24-45a5-9799-f8e0aac6b37c.png)

**Comment by bsongis-frsky** [comment]
Mixes created by the Wizard

![image](https://user-images.githubusercontent.com/50834778/160176250-8a6fc2e9-d155-4392-bc3b-7841da784dac.png)

**Comment by i3dm** [comment]
> Mixes created by the Wizard
> 
> ![image](https://user-images.githubusercontent.com/50834778/160176250-8a6fc2e9-d155-4392-bc3b-7841da784dac.png)

gain adjust should span 0-100 by default. not -100 to 100

**Comment by ninodesposati** [comment]
This would be a great feature!!

**Comment by lthole** [comment]
The wizard should also take care of configuring CH5 and CH6. The most common is probably having Aileron Right on CH5, but there should be options for:
a) Aileron Right on CH5 (stabilised)
b) CH5 not stabilised
a) Elevator2 on CH6 (stabilised)
b) CH6 not stabilised

**Comment by lthole** [comment]
Note Mode switch 2 channel is only needed if not using Quick Mode. I suppose you can just delete it if not needed.

**Comment by hrenz** [comment]
don´t forget ch12 for Selftest with ACCST.Rx

**Comment by hrenz** [comment]
and Gain Poti with curve 0% to +100%

**Comment by mawzthefinn** [comment]
Would like to see this, perhaps in concert with the SxR mixer proposed in #1616

**Comment by EngelMT** [comment]
This Idea I post with #924 in the past. Will be very nice to have it. This would extremely improve the ease of use of the receivers with ETHOS.

**Comment by mawzthefinn** [comment]
This is now in 1.5.x Nightlies
