### ISSUE TITLE
Impossible to set RX options

### ISSUE THREAD

**Issue by LProia** [FrSkyRC/ETHOS-Feedback-Community#1449]
Hello
I run Ethos 1.1.0 on X20S. FCC mode
Receiver R9 SX Sw 1.3.3  I Register, bind, operation ok.
I go into settings to change Pin6 to Sbus out, but I don't ask for confirmation at the exit. 
SBus out on Pin 6 cannot be set.
No all changes can be saved.
Also tested in Ltb-eu Mode

**Comment by WismyYao** [comment]
It is recommended to use ETHOS V1.1.1
