### ISSUE TITLE
Upgrade to 1.0.3 EU, Fails/bricks X20

### ISSUE THREAD

**Issue by Moki38** [FrSkyRC/ETHOS-Feedback-Community#145]
![image](https://user-images.githubusercontent.com/6523846/116442468-d0468800-a852-11eb-9c39-aca5dd74b755.jpg)

After the upgrade to 1.0.3-EU, Device show this

![image0](https://user-images.githubusercontent.com/6523846/116442542-e5231b80-a852-11eb-86a8-341e216ef96f.jpeg)

Rebooting the device, gives this screen.

USB Drives won't connect to PC anymore. SD Card is still readable from PC.

**Comment by MIKE-DAILEY** [comment]
Would like to help but have some questions.  

1. Do you know the original firmware version listed on the INFO screen?
2. If the version was older that 1.0.1. did you flash the 1.0.1. bootloader.bin to the system?

**Comment by Moki38** [comment]
Original version was 1.0.1, only firmware.bin (1.0.3-EU) was placed on X20 (while in bootloader mode)

**Comment by MIKE-DAILEY** [comment]
After putting 1.0.3-EU firmware on the SD root and then disconnecting the USB cable did the flash progress bar display, show flash progress and then finish with the word "bootloder"?   If so what did you do next?

**Comment by Moki38** [comment]
Yes, system was on 1.0.1 (first power up)

Placed the firmware.bin in the SD root, Was unable to see anything after that (as the purple/green screen was shown, after that)

**Comment by MIKE-DAILEY** [comment]
So now it will no longer start in bootloader mode?

**Comment by Moki38** [comment]
As seen in the 2nd screen, it look like, it still boots in bootloader mode. When plugging in the USB cable, the drives (in my case E: and F: show in the file explorer, but are inaccessible.

**Comment by MIKE-DAILEY** [comment]
I think the first step is to get it to start in bootloader mode.  Do you know how to flash the bootloader.bin from your PC to the X20 with the X20 power off.  There are two apps that can be used.  DfuSe and OpenTX Companion.

**Comment by Moki38** [comment]
X20/1.0.1/X20-EU/X20-EU/bootloader.bin
=================================================================================
dfu-util 0.7

Copyright 2005-2008 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2012 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

Filter on vendor = 0x0483 product = 0xdf11
Opening DFU capable USB device... ID 0483:df11
Run-time device DFU version 011a
Found DFU: [0483:df11] devnum=0, cfg=1, intf=0, alt=0, name="@Internal Flash   /0x08000000/16*128Kg"
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 1024
DfuSe interface name: "Internal Flash   "
Downloading to address = 0x08000000, size = 74320
.........................................................................
File downloaded successfully
No valid DFU suffix signature
Warning: File has no DFU suffix

**Comment by Moki38** [comment]
No improvement, so either i did something wrong...

**Comment by MIKE-DAILEY** [comment]
If that app needs a dfu file you can download the 1.0.1. bootload.dfu from the bottom of the ETHOS website here https://ethos.frsky-rc.com/

**Comment by Moki38** [comment]
C:/Program Files (x86)/OpenTX/Companion 2.3/dfu-util.exe -a 0 --device 0483:df11  -DC:/Users/moki3/Desktop/FRSKY/X20/X20/bootloader.dfu
=================================================================================
dfu-util 0.7

Copyright 2005-2008 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2012 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

Filter on vendor = 0x0483 product = 0xdf11
Opening DFU capable USB device... ID 0483:df11
Run-time device DFU version 011a
Found DFU: [0483:df11] devnum=0, cfg=1, intf=0, alt=0, name="@Internal Flash   /0x08000000/16*128Kg"
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 1024
Dfu suffix version 11a
DfuSe interface name: "Internal Flash   "
file contains 1 DFU images
parsing DFU image 1
image for alternate setting 0, (1 elements, total size = 74328)
parsing element 1, address = 0x08000000, size = 74320
.........................................................................
done parsing DfuSe file
Warning: File product ID 0000 does not match device df11

=================================================================================

**Comment by Moki38** [comment]
Still no joy

**Comment by Moki38** [comment]
Using DfuSe Demo (3.0.6), X20 doesnt show in the "Available DFU devices" drop-down list

**Comment by MIKE-DAILEY** [comment]
Is STM32bootloader Windows USB driver showing when the the X20 USB is connected power off?

**Comment by Moki38** [comment]
![st](https://user-images.githubusercontent.com/6523846/116458588-1c9ac380-a865-11eb-8e01-3c581c99c958.png)

**Comment by MIKE-DAILEY** [comment]
OK so no STM32bootloader and that is good.  You are using DfuSe Demo with the X20 (power off) connected to your PC with a data USB cable, right.  There is a video on the ETHOS website.  Might want to check the part about installing and using DfuSe Demo.

**Comment by Moki38** [comment]
![2021-04-28 21_12_43-DfuSe Demo (v3 0 6)](https://user-images.githubusercontent.com/6523846/116459880-a4350200-a866-11eb-930b-c6c3bdbccc7b.png)
![2021-04-28 21_13_04-DfuSe Demo (v3 0 6)](https://user-images.githubusercontent.com/6523846/116459881-a4cd9880-a866-11eb-897b-47d8b873b9f5.png)

Uninstalled the STM32bootloader driver and re-flashed the bootloader.dfu

Still no joy (same screens as before)

**Comment by MIKE-DAILEY** [comment]
It looks like the bootloader is flashing OK.  The system should be able to start in bootloader mode at this point.  I think you will need to contact your FrSky dealer for support.

**Comment by Adelaxie** [comment]
@Moki38 Please contact with me . libo.xie@frsky-rc.com
for me , it seems more like wires broken for TFT. Need to check to have an answer.

**Comment by Ender1967** [comment]
Take the SD card out the radio. From your laptop /computer write in the root of SD card  a new firmware.bin (start with an old 1.0.1, if it works you can upgrade to 1.0.3 or 1.0.4 or even 1.0.5 later). Insert the SD card in  radio, start in bootloader mode, see if the writing of the firmware completes without error and report back here the result.

**Comment by Moki38** [comment]
Hi,

You asked to contact you.

Kind regards,
Eric van Dijken

Ps, also made a support call with Horusrc.

**Comment by Moki38** [comment]
Tried to install a new firmware, using a PC.
Both 1.0.1 and 1.0.3 to noavail.

As an IT guy, i think its hardware related.
Internal flash is “fried”, but than again... thats what it looks like to me. I am not a X20 expert.

**Comment by strgaltdel** [comment]
I'm still not convinced that stm bootloader is installed.
if my memory is correct, companion (which is using dfu-util) reported successful bootloader flashing in my first try, although stm driver wasn't installed and so Ethos bootloader was not flashed.
So i reinstalled the driver using zadig and everything went well.

unless you dont see the stm bootloader driver in the device manager, personally, i wouldn't be sure a new bootloader was flashed
 
do you really see this entry?


![bootloader](https://user-images.githubusercontent.com/20392683/116538505-ec483900-a8e7-11eb-8dc5-d019126e3634.jpg)

**Comment by Moki38** [comment]
![Uploading 2021-04-29 13_53_57-DFU in FS Mode Properties.png…]()

**Comment by Moki38** [comment]
Think the USB driver is fine

![2021-04-29 13_53_57-DFU in FS Mode Properties](https://user-images.githubusercontent.com/6523846/116547018-9fb62b00-a8f2-11eb-8bdd-f955330258f6.png)

**Comment by bsongis-frsky** [comment]
STM bootloader is there, it's in ROM.
It connects correctly to the PC and you are able to flash something obviously!
Please double check you upload the right bootloader file (not X10 or anything else)
Then you press [Enter] and keep it pressed while pressing the PWR button of the radio, and this X20 bootloader should start.

**Comment by bsongis-frsky** [comment]
If those steps fail then you have to contact your dealer, it shouldn't be an Ethos issue
Feel free to reopen if you think I said anything wrong.
