### ISSUE TITLE
long press / model select

### ISSUE THREAD

**Issue by gernotw** [FrSkyRC/ETHOS-Feedback-Community#1451]
with 1.1.1 EU on x20s long press (>2s) a model icon will switch to the model **without** confirming to do so. Touching the icon about 1 second will show the menu as usual.
is this on purpose?

**Comment by gernotw** [comment]
sorry, for my previous post. If receiver is connected, there will be a warning...

**Comment by bsongis-frsky** [comment]
Now we have no more confirmation, [Enter Long] in this screen should be removed, it saves no time
