### ISSUE TITLE
ETHOS + TD-MX GPS sensor discovery.

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1453]
I have attached a GPS sensor to my TD-MX receiver.

When discovering, ETHOS configures all GPS sensors, GPS, GPS Altitude, GPS Speed as 900mhz sensor.
Only GPS Course is not assigned to 900mhz.
I suppose this has to be assigned to 900mhz too.

![1644598498433](https://user-images.githubusercontent.com/55426642/153634318-89262e64-b3bd-4bae-bb24-0638383417a1.JPEG)

**Comment by bsongis-frsky** [comment]
No. Name would be too long

**Comment by Hobby4life** [comment]
ok check
