### ISSUE TITLE
ETHOS + TD-MX - Configure S.Port to  FBUS not working

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1454]
As Topic says.

When trying to set S.Port to FBUS in RX Settings, nothing happens.

ETHOS v1.1.1
TD-ISRM v2.2.0
TD-MX v1.07

**Comment by WismyYao** [comment]
Hi, do you know what version of your servo is ?

**Comment by Hobby4life** [comment]
V1.5.6 for bls540x

Working fine on receiver with access + fbus.

**Comment by Hobby4life** [comment]
@WismyYao 

Thanks for the Fix with new v2.0.1 Servo firmware! :-)
