### ISSUE TITLE
Roadmap for external protocols

### ISSUE THREAD

**Issue by dotlolz** [FrSkyRC/ETHOS-Feedback-Community#1455]
Hi
I am reopening this since 1.1 is out and Lua most likely working.
Not a duplicate of #5 as no proper answer has been provided yet.

I am kindly asking for a target date, or a roadmap for external protocols to be supported as requested by many.
Keep in mind that it was one of the features that was present on the original product description and is a major selling point for lot of us as Expresslrs and crossfire is widely present on the multirotor community, if not most of it.

Regards

**Comment by kakashi2018** [comment]
Yes, I agree. Just adding the crsf support will make a huge difference here.

**Comment by andika207** [comment]
>  Not a duplicate of #5 as no proper answer has been provided yet.

of course it's a duplicate because the other issue is still OPEN and its title has recently been changed by @bsongis-frsky 
please close it @Adelaxie

**Comment by dotlolz** [comment]
> > Not a duplicate of #5 as no proper answer has been provided yet.
> 
> of course it's a duplicate because the other issue is still OPEN and its title has recently been changed by @bsongis-frsky please close it @Adelaxie

By "recently updated " you mean : not added any details just ignore the questions?
This is still not a duplicate,  a proper answer is yet not provided. That's why Git can display Milestones : put an ETA in front of asked features,  which is not the case here.
It's one of the most asked features, and still no word on it after 10 months.
I would like to have a clear answer from FrSky on this : are you willing to let external protocols work with this TX, or are you deliberatly not . 
I think many are questionning too.

**Comment by andika207** [comment]
> I would like to have a clear answer from FrSky on this : are you willing to let external protocols work with this TX, or are you deliberatly not . 

I ask them to close this issue because you are unable to understand why the #5 is still open or why the title was edited a few weeks back.
if I was @bsongis-frsky I would write on the milestones page: ETA 2023 so you don't bother me for the next 10 months

**Comment by andika207** [comment]
>It's one of the most asked features, and still no word on it after 10 months.

if you can't wait for the official ETHOS support, you can simply give a try to the other OS alternative from @MikeBland

**Comment by dotlolz** [comment]
> > I would like to have a clear answer from FrSky on this : are you willing to let external protocols work with this TX, or are you deliberatly not .
> 
> I ask them to close this issue because you are unable to understand why the #5 is still open or why the title was edited a few weeks back. if I was @bsongis-frsky I would write on the milestones page: ETA 2023 so you don't bother me for the next 10 months

You can't blame people when they ask for a feature that was promise on the original product description flyer and disappeared right after it.  Thats not how marketing works.
If this case bother you , you can leave as, with no role on the ethos dev, you are useless here to make the subject go further. 

Just to be very clear: external protocols integration have been told to be available soon to ALL the reviewers who received the product and have been resuested to demonstrate it. 
I am not kindly asking to make us a favor by this, but asking the manufacturer of a product to respect his original product description as I bought the product because of this feature. It's a year now, wake up.

**Comment by bsongis-frsky** [comment]
No ETA as it's something we will do, but with less priority than other features which have been requested in this feedback repository

**Comment by dotlolz** [comment]
> No ETA as it's something we will do, but with less priority than other features which have been requested in this feedback repository

Like external protocols have been...  Even more on the RCG thread.
Seriously, I don't understand the position on this. It does not allow user to use anything else than Frsky (which is almost impossible to find, where is sold the TD MX rx in europe? Nowehere at this moment, but the system itself is called TANDEM dammit, it's the whole purpose of getting it...)
What is the goal of this ? Because I don't understand.

**Comment by KevinFairgrieve** [comment]
> 

https://www.t9hobbysport.com/frsky-td-mx-receiver

In Europe even if not in the EU!

**Comment by andika207** [comment]
@dotlolz I once was told the support for external receivers was a business decision unrelated to ETHOS issues https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/309#issuecomment-847546556

**Comment by andika207** [comment]
> Its a mess to import things from UK since months. I am talking about europe the Land.

@dotlolz  where are you from ?

**Comment by dotlolz** [comment]
> @dotlolz I once was told the support for external receivers was a business decision unrelated to ETHOS issues [#309 (comment)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/309#issuecomment-847546556)

I am simply here to not let FrSky forget that it was on the key features "soon supported " when the products have been announced. Yet still no support after a year. 
Too easy to let the selling goes and then tell it's not a priority, or if it will be someday !
Ethos as almost (if no more) than a year now, and still we can see pilots crashing their 3k+ jets using it, with no apparent reason.
So who is this désigned for ? If we can't count on the stability after one year at each release (search for the RCgroup "radio" forum, the most upcoming term when you are looking for X20S coming is " i reserve it for my small fomies as i have no trust yet in it" and cannot count on it for the futurproofness of supporting advanced and widely used technology as crsf Or expresslrs?
Who is it designed for really? Are we beta tester ? To serve what goal, if we can't even ask for our hardware to be supported ?!
I will not put to the trash all my existing- and trusty- gear for à system that put to the ground its user, not at this price.
Beautiful hardware, but still no lessons learnt from the FrOs fiasco.
Rude.

**Comment by andika207** [comment]
> Ethos as almost (if no more) than a year now, and still we can see pilots crashing their 3k+ jets using it, with no apparent reason. 

@dotlolz  interesting, can you share more details ? what receiver, what protocol, telemetry logs... ?
