### ISSUE TITLE
[UI] Wrap around in Model Select screen

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1457]
Hey guys,

I love the new layout in the model select screen. The only thing that I find a pain is that the new model button is at the end of the list. It would be much more usable if it was at the start. Whenever you enter the model select screen, no matter which model is loaded, you are always at the top of the screen. Therefore, it makes more sense to have the new model button as the first entry.

Also, while talking about models. What are the maximum filename lengths for model names? I can't find this information anywhere.

**Comment by Jedsters** [comment]
Hi Darren, I quite like it as it is, creating a new model is something I very rarely do, and even when I do buy a new model I normally just copy existing models or templates so don't really want the first model as something I never use.  

However, what would be very useful is if when you were on the first model and scrolled left with the wheel it took you to the last model - so wrap-around.  That would give you quick access to create a new model and also give me quick access to my last models.

Hoping you agree that's a good alternative?
(Jerry)
