### ISSUE TITLE
Serial connection doesn't seem to do anything

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1458]
With 1.1, a menu was added when you plug in the USB cable and the transmitter is powered on. The options are **Joystick** and **Serial**. I have not tested **Joystick** yet. But **Serial** appears to do nothing. I hear beeps on my PC to say that something has connected. But I don't see the flash drive or MicroSD card in Explorer. In fact, if it had not been for the beeps, it would be as if nothing had happened.

I guess the question is what is **Serial** supposed to do. As my thoughts for it's use must be wrong. Or it's not working.

**Comment by loetefix** [comment]
Serial is for things like debugging, not for flashdrive.
By the way it would be nice if had the possibility to have a flashdrive mode to select. And an option for every model what should be done when plugging usb cable.( for example in a simulator model you can select allways joystick)

**Comment by Hobby4life** [comment]
It is used for live lua debugging.

Use a terminal program like Putty, and set baudrate to 115200

**Comment by bsongis-frsky** [comment]
Will be added to the documentation
