### ISSUE TITLE
Beware: on 1.1.0 no new model creation

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#1459]
Hi all,
Bertrand, please note a small bug on 1.1.0 : it is not possible for me to create a new model anymore.
I can do it only by duplicating a former one.
horus X10 Exp with Ethos 1.1.0
Thanks for all the work !

**Comment by MIKE-DAILEY** [comment]
Not having that issue here.  Can you please explain where in the model creation process this issue manifests itself for you?

**Comment by Billy60** [comment]
Simple. I hit on the '+' box in the model list. Then I get to the screen for a choice 'plane' glider, heli ...'
I choose 'plane'.
The Tx freezes then. I have to hit on 'return' a few times to find myslef back to the last model I was using before I tried to make a new one.

What about reinstalling he firmware ?

**Comment by Hobby4life** [comment]
Tried to replicate the issue.. but no problems here.
X10 Express ETHOS v1.1.0

Try v1.1.1

**Comment by MIKE-DAILEY** [comment]
> Simple. I hit on the '+' box in the model list. Then I get to the screen for a choice 'plane' glider, heli ...' I choose 'plane'. The Tx freezes then. I have to hit on 'return' a few times to find myslef back to the last model I was using before I tried to make a new one.
> 
> What about reinstalling he firmware ?

The PgDn key function does not work after you select Airplane?

**Comment by Billy60** [comment]
Yes it does ! I had to reinject the first. I suppose something went wrong
on the first time...
Thanks again for the help!

Le dim. 13 févr. 2022 à 12:12, Jet_Flyer ***@***.***> a
écrit :

**Comment by Billy60** [comment]
Yes it is.
It seems the Frsky TX is very demanding on the quality of the usb cable. But obne just has to know it.
Bertrand, you creation is really outstanding. Keep on !
best regards to all
