### ISSUE TITLE
X20 1.0.3 -> 1.0.4 Broken Models

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#146]
I updated from 1.0.3 to 1.0.4 on my X20 and the attached models won't open anymore. I get an "Invalid data" error trying to switch to them.

[models.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6393966/models.zip)

**Comment by bsongis-frsky** [comment]
Which model is bad in your zip?

**Comment by bsongis-frsky** [comment]
model01.bin is bad, the RF Module data is bad (registrationID)

**Comment by rburrow87** [comment]
All 4 in the zip are the ones that won't open for me. model01 and model04 have been on the radio and flown since 1.0.1.

model06 was set up a couple days ago but so far I've only used it for testing redundancy receiver setups.

model07 was just for testing something, I forget what, but I noticed it won't open now either.

**Comment by Latitude58** [comment]
I had 3 models set up. 1.04 has broken 2 of them. Not sure if it's relevant but the 2 bad ones were using ACCST and the one that survived was using access although I had to re-do the timer setup.

**Comment by rburrow87** [comment]
3 of the 4 that broke for me were all on ACCESS for sure, can't remember what was in the test one.

**Comment by Beastyboy80** [comment]
My Modells broke  too

**Comment by bsongis-frsky** [comment]
OK it's late here, for now I have removed the release from the website, I will try to find a solution tomorrow

**Comment by OldGazer** [comment]
That's why we beta test.  Thanks for your hard work.

**Comment by marevalor** [comment]
> OK it's late here, for now I have removed the release from the website, I will try to find a solution tomorrow

Calm, we wait for your solution. Thanks for all the work !!!! Ethos is being fantastic.

**Comment by bsongis-frsky** [comment]
@rburrow87 where your 1.0.3 comes from? official release here on github?

**Comment by bsongis-frsky** [comment]
Problem found, thanks for the report
Your model model01.bin will be used in our internal non regression tests suite

**Comment by marevalor** [comment]
> Problem found, thanks for the report
> Your model model01.bin will be used in our internal non regression tests suite

Thanks

**Comment by rburrow87** [comment]
Cool, all my models work again with the updated 1.0.4 release.

Thank you all for fixing it so quickly!

**Comment by Latitude58** [comment]
Where is the working 1.04 download now? Thanks

**Comment by rburrow87** [comment]
It was pulled again as a precaution due to #148

**Comment by Latitude58** [comment]
> It was pulled again as a precaution due to #148

Ok, no prob, thanks for the info.
