### ISSUE TITLE
Request: Please can we have details of how issues are closed? 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1463]
Hi, we can see what issues have been addressed in each new release etc., however it's not aways obvious how they've been addressed. For example in issue 1428 it talks about moving uncategorised to be the last category and also about being able to change the order of the categories. Now, I no longer have any uncategorised models and can't see that I can move any categories so I'm not really sure what has been done.
Would it be possible to close each issue with a brief summary of what has changed. 
Ideally the manual would be updated to accommodate this information, but I appreciate things change too fast for the manual to be able to keep up. 
Thanks guys!!

**Comment by bsongis-frsky** [comment]
Categories are in alphabetical order. The same applies to models within each category. Only "Uncategorized" is the last folder, and its name is translated.
