### ISSUE TITLE
Request / Enhancement: Text Checklist

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1465]
With opentx it is possible to display a text checklist when a model is selected or when the tx is powered on (so the model is selected that way). Please could we have similar on Ethos?

I'm thinking that perhaps on the Ethos Checklist page we could have another twistie called perhaps  'Text' with options of 'Edit text', 'Display Text' (with a choice of Yes / No) and 'Delete Text'. Edit text would then create / edit a .txt file with an appropriate name (whether that be modelxx.txt or model name.txt - probably the former so the file can be kept in sync with the .bin file). When selected, 'Display Text' = Yes would cause the .txt file to be displayed as part of the model startup checklist, probably before the switch checks are done. Delete text would cause the .txt file to be deleted (probably with a confirmation screen).  I'd imagine it makes sense to clone a .txt when the 'CLONE' option is used for a model - otherwise it wouldn't be a true clone. 

The use case would be to remind the user that certain actions need to be taken when a given model is flown which are perhaps non-standard or even to remind the user what various switches do on a given model etc.. Currently I have some gyro receivers and I can never remember the sequence of events needed to calibrate the gyro, I have stored this in opentx in a checklist so I have a reminder. On other e-gliders models I have a reminder to reset a timer if a power battery has been changed between flights etc. etc..
Thanks!

**Comment by FireFlite88** [comment]
This would be very useful.

**Comment by pPRODEVEN** [comment]
Bonjour,
Je reviens sur le sujet de la Check Liste car ce n'est pas très pratique avec une feuille de papier sur le terrain et tous mes modèles avec chacun leur spécifité, quel accu 4S, 6S ou ? l'accu en 3000 Mah ou ect... ? quel inter qui commande quoi ? etc, etc, etc.
Parfois je prends ma X10S au lieu de ma Tandem X20S car au moins il est possible d'avoir mes informations nécessaire.
Merci d'avance

**Comment by Jedsters** [comment]
Also, I think the page should be scrollable rather than just a single page and maybe it could accommodate a bitmap to be displayed as an alternative?
Thanks

**Comment by pPRODEVEN** [comment]
Bonjour,
C'est dommage qu'une radio comme la X20S soit si performante et qu'il ne soit pas possible de rajouter juste une page texte par modele pour aider  le pilote et meme la sécurité avant le vol.
Merci de m'avoir entendu, et j'espere un jour que cette demande deviendra réalité
Bien cordialement

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/220612552-c5878498-b3c9-48a9-84a8-fbc77607940c.png)

**Comment by pPRODEVEN** [comment]
Bonjour Bertrand,

 

C'est bon pour la check-list ?

C’est une superbe bonne nouvelle,

 

Merci merci Bertrand.

Comment faire pour la mise à jour ?

 

Bonne journée

 

De : Bertrand Songis @ FrSky ***@***.***> 
Envoyé : mercredi 22 février 2023 12:53
À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc : pPRODEVEN ***@***.***>; Comment ***@***.***>
Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] Request / Enhancement: Text Checklist (Issue #1465)

 

 <https://user-images.githubusercontent.com/50834778/220612552-c5878498-b3c9-48a9-84a8-fbc77607940c.png>

**Comment by bsongis-frsky** [comment]
With Markdown support

![image](https://user-images.githubusercontent.com/50834778/222768416-1437dfa1-9aa7-4320-ba76-1d08fcf67248.png)

**Comment by Jedsters** [comment]
The markdown is very clever and will add to the usefulness.
Thanks!
