### ISSUE TITLE
search for a filepicker add to forms

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1468]
I try to select a file via addform, is there something like a file selector, similar to the color picker?
The aim is that I per lau e.g. want to play a selected file.
Many Thanks
Greetings Benno

**Comment by Benno00** [comment]
Hello,
can you please add the lua lfs library

**Comment by Hobby4life** [comment]
What do you want to do with the file picker? Like what files do you want to load with it?
Like lua files I think can not be loaded during operation because the are "compiled" during boot of transmitter.

**Comment by Benno00** [comment]
I want my widget e.g. assign sound files for certain functions

**Comment by dwheel** [comment]
I agree, we need a file picker that can navigate folders and pick a sound file or bitmap for use in the widget.

**Comment by bsongis-frsky** [comment]
2 new functions added:

`form.addFileField(line, nil, "/audio/en/system", "audio", function() return filename end, function(newValue) filename = newValue end)`

and

`form.addBitmapField(line, nil, "/bitmaps/models", function() return bitmap end, function(newValue) bitmap = newValue end)`
