### ISSUE TITLE
Bluetooth Audio 

### ISSUE THREAD

**Issue by Beastyboy80** [FrSkyRC/ETHOS-Feedback-Community#147]
Where is the Menue  to bind my Headset ? 
X20s

**Comment by bsongis-frsky** [comment]
The code for this feature has not been reviewed / accepted
It will be my next priority, we have been very busy with a lot of other requests

**Comment by Beastyboy80** [comment]
THX :-)

**Comment by deckard733** [comment]
Good morning, I have managed to connect the bluetooth but I can't get it to receive or send data. I have used a program like BLE scam, and although it connects, there is no data transfer. Could it be a software problem?
