### ISSUE TITLE
Tempo to resume to normal screen after touch

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1470]
Hello,

Could be great if after touching the widget, it could resume to normal colors without any other actions after 5s per exemple

![image](https://user-images.githubusercontent.com/27886942/153932101-eeeb3306-f2e7-4818-96af-022154555cbd.png)
Normal

![image](https://user-images.githubusercontent.com/27886942/153932183-b72fffa5-3842-47a2-a453-566f7d321469.png)
The screen remind like this until flip flop to another part

**Comment by bsongis-frsky** [comment]
This issue has been fixed since long, no?
