### ISSUE TITLE
Possibility to change widgets colours

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#1471]
Hi,
it would be nice to have the possibility to change the display color of the widgets.
For example, the voltage of the lipo in red, the chronometer in blue etc... 
This would make it easier to differentiate them and make it easier to read the information sought in flight ;)
Thanks for your job !

**Comment by danydu62** [comment]
Oui cest vrai ça serait bien .
En plus sil était possible de changer la couleur des écrans.  Autre chose que jaune et orange  ? Bleu clair ? Merci

**Comment by jurajjurej** [comment]
Lua script "Telpi"
![Screenshot_31](https://user-images.githubusercontent.com/85956904/205546349-2ac31845-0a10-41b5-9264-7385bd319956.jpg)

**Comment by Tonio62** [comment]
Great !!!!
Where can i have it ?

Thanks ;)
