### ISSUE TITLE
DIY Sensor can not show values and distinguish between different values with same address.

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1472]
Dear Developer,
Because of bandwidth reasons of the S.Port, Spirit System (they told me) Heli FBL sends 3 several different sensor values (A, V, mAh) via the same address 03 0B00 to the telemetry of Ethos. This works fine as you can see in the screenshot 1 and 2. 

![1 Showing V A mAh correct with 03 0B00](https://user-images.githubusercontent.com/86232280/154013813-9624eb7c-3342-430f-bc25-35633951b4e3.jpg)
![2 Showing V sensor detail](https://user-images.githubusercontent.com/86232280/154013811-007c3181-164a-4702-8bb5-464bc5f9a0c0.jpg)

But when I take the sensor address 03 0B00 into the  DIY sensor this is not working with the DIY sensor. The value jumps between different values randomly with a wrong range as you can see in screenshot 3. The values are also nonsense, so a calculation may fail because of this issue.

![3 Showing V on DIY sensor with 03 0B300](https://user-images.githubusercontent.com/86232280/154013810-704a5fe7-5cdc-4218-b3d3-d7b53f6435e1.jpg)

The automatic detection of the sensor address is also not working in the DIY sensor. 
I want to use the DIY sensor for a average cell voltage and % capacity of the battery as in other models. In this case it is not possible. 
Please can you fix this? 
Thanks in advance. Bernhard

**Comment by strgaltdel** [comment]
Hi Bernhard,

You are using the "reserved" Sensor ID from Redundancy boxes
There are no problems mentioned from users regarding compatibility issues
so it seems your sensor does not "emulate" the red.box sensor data in a correct way.

In other words: it's not a problem of ethos.

I would recommend you use "public" and not reserved Sensor ID's
You don't give hints about your sensor, most are based on Arduino HW

would advice to read some of the following links

https://github-wiki-see.page/m/yaapu/FrskyTelemetryScript/wiki/FrSky-SPort-protocol-specs
https://www.frsky-rc.com/wp-content/uploads/2017/07/Manual/FRSKY%20TELEMETRY%20PROTOCOL.PDF
https://www.rcgroups.com/forums/showthread.php?2245978-FrSky-S-Port-telemetry-library-easy-to-use-and-configurable

**Comment by BernhardFe** [comment]
Hi this is not a sensor build on my own. ;-) It is coming from the Spirit 2 FBL system with the FR-Sky integration. The idea was to use the DIY sensor to multiply down the value of the 12s battery to an average of one cell and to show it and use it in the warnings as a "normed" value independent if I have 3s,4s,6s or 12s. Of cause you are right, with the Fr-Sky Neuron it works perfect. So I will link your answer into the spirit forum for requesting a solution by Spirit system. Thanks a lot!
