### ISSUE TITLE
Switching dark mode moves screen display

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1476]
If I want to decide between General => Dark Mode => On or Off I want to toggle between the two to see which I prefer, however, each time I touch the On/Off option the screen scrolls back to the top which means I then have to scroll back down to find Dark Mode again. 
This is annoying and doesn't happen with the Digital Voltage and Digital RSSI options so would seem to be a minor bug.
Ethos 1.1.1 
Thanks

**Comment by bsongis-frsky** [comment]
I will see if we can do better, with low priority

**Comment by Jedsters** [comment]
Thanks, I quite agree, it's not the most important issue, low priority. Nice to fix one day.

**Comment by Jedsters** [comment]
Is it worth assigning to a future release to avoid keep becoming stale?

**Comment by tgott551** [comment]
I'm a relative newbee to Ethos and Github but what would be really nice relating to turning dark mode on/off would be the ability to assign a switch to do it similar to the way you can assign a pot to speaker volume and screen brightness. This would allow quick changes according to lighting conditions.

**Comment by Target0815** [comment]
> the ability to assign a switch

Yes, I had already suggested this in #1906. It would be enough if under Special Funcs a corresponding action can be selected ("Switch Darkmode) "and assigned to a switch.
