### ISSUE TITLE
Request: Display mixer type 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1479]
Would it be possible to display a mixer type when a mixer is selected please? It would be useful to know what sort of a mixer each mixer is after it has been created (and forgotten as to which mixer it is).
e.g. if in the following, how do I know what sort of mixer I used for Camber? Is it a Free Mix or did I use Camber etc.. 

It would be useful to know particularly when I am wanting to create another similar mixer but don't want to clone an existing mixer and inherit its settings. 
 
![image](https://user-images.githubusercontent.com/96293240/154112634-9ce96662-365c-46a6-bd09-b7526f2d01f3.png)
Thanks!

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/156758295-71f5ae69-5a9d-43c6-93df-27512b342973.png)
