### ISSUE TITLE
Screen turns off when trims are moved

### ISSUE THREAD

**Issue by marevalor** [FrSkyRC/ETHOS-Feedback-Community#148]
I update my x20 with the version 1.0.4 that they recently uploaded (FCC) and when moving the trims (any) the screen turns off and it does not let the radio turn off. I must remove the battery to turn off.

**Comment by bsongis-frsky** [comment]
on main screen? everywhere? at any moment?

**Comment by marevalor** [comment]
on main screen

**Comment by bsongis-frsky** [comment]
I cannot reproduce here, are you on a fresh model?

**Comment by marevalor** [comment]
https://www.youtube.com/watch?v=R-HUqBWfl6g

**Comment by marevalor** [comment]
> I cannot reproduce here, are you on a fresh model?

An old model, created with 1.0.3.

**Comment by bsongis** [comment]
would you send me:
- your radio.bin (radio settings)
- your model file
thanks!

**Comment by marevalor** [comment]
> would you send me:
> 
> * your radio.bin (radio settings)
> * your model file
>   thanks!


[error.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6399953/error.zip)

**Comment by bsongis-frsky** [comment]
thanks

**Comment by bsongis-frsky** [comment]
It works perfectly on X20S, I will try on X20 now

**Comment by Beastyboy80** [comment]
my X20s works fine with 1.004

**Comment by bsongis-frsky** [comment]
I have removed the bins for now, I want to understand this issue, it is serious

**Comment by marevalor** [comment]
> I have removed the bins for now, I want to understand this issue, it is serious

Thanks

**Comment by bsongis-frsky** [comment]
the same on X20, I cannot replicate!

**Comment by rburrow87** [comment]
I downloaded the updated 1.0.4 before it was pulled for this and I'm unable to replicate this issue either. I tried all the models I had set up on my X20.

I also backed up my SD card and used the radio.bin and models in error.zip and still can't reproduce.

**Comment by bsongis-frsky** [comment]
So ... until now only marevalor has the issue. 
And on his unit it seems very very reproductible
@marevalor would you please do a couple of checks to help me to reduce the scope of the issue:
- try to set the sound to OFF and trim
- try on a fresh model

**Comment by bsongis-frsky** [comment]
Reproduced, on the very old X20 I had in the shelf!
Is yours one of the first units?

**Comment by marevalor** [comment]
> So ... until now only marevalor has the issue.
> And on his unit it seems very very reproductible
> @marevalor would you please do a couple of checks to help me to reduce the scope of the issue:
> 
> * try to set the sound to OFF and trim
> * try on a fresh model

ok if I put the radio on it is silent the error does not happen.

**Comment by bsongis-frsky** [comment]
Thanks, now I am confident I will find where it is

**Comment by marevalor** [comment]
> Thanks, now I am confident I will find where it is

Thanks You guys are doing a great job !!!!

**Comment by bsongis-frsky** [comment]
I just found it, it's obvious now. Your hardware has no MUTE pin and this release is the first one which uses it (which should be skipped in your case)!
I will upload new binaries in a couple of minutes

**Comment by marevalor** [comment]
> I just found it, it's obvious now. Your hardware has no MUTE pin and this release is the first one which uses it (Mute / Unmute should be skipped in your case)!
> I will upload new binaries in a couple of minutes


Thanks Bertrand, You are doing a great job, and Ethos is great.

**Comment by marevalor** [comment]
OK, again updated and everything perfect.

Thanks
