### ISSUE TITLE
Ethos suite: please implement model backup&restore in the first step

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1482]
So mike posted a preview of the "Ethos suite" and requested feedback.
https://www.rcgroups.com/forums/showpost.php?p=48712215&postcount=14856

As far as i can read there shall be options to convert model & GPS-Map bitmaps.

What i'mmissing (but maybe it's planned in the first step) is a simple "read" and "write" of the complete model storage in order to perform backup and restore procedures in a simple way.
I'm aware that you can manually copy / paste files, but hey, the suite should emphasize user's comfort, shouldn't it ?

Maybe i'm old fashioned, but i do rate backup&restore functionality more over GPS mapping conversion routines.

regards

**Comment by ticdelaroo** [comment]
The simplified back up will bring many new users to Frsky IMO

**Comment by nimic01** [comment]
That is a great app, if you are searching tester, I would have fun to do that.

**Comment by bsongis-frsky** [comment]
Please use RCG for this, or it makes this whole repository pointless
