### ISSUE TITLE
When you create a widget ,pressing RTN with a long press for exit to main screen, it locks the buttons

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#1484]
When you create a widget ,pressing RTN with a long press for exit to main screen, the buttons are locked until you press on the screen on one of the widgets

If you press RTN in short presses until you reach the main screen, that does not happen.

I think is a bug

Watch the video

Thanks

**Comment by kakashi2018** [comment]
Yes, happening to my x20s as well.
