### ISSUE TITLE
how does work form.openDialog

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1486]
How does work form.openDialog?
The buttons are displayed to me, but how do I query which one was pressed?
Thanks very much
Greetings Benno

**Comment by Hobby4life** [comment]
Each button has it's "action"function.

```lua
local buttons = {
  {label="Button 3",
    action=function()
      -- Action 3
    end},
  {label="Button 2",
    action=function()
      -- Action 2
    end},
  {label="Button 1",
    action=function()
      -- Action 1
    end},
}
```

**Comment by Benno00** [comment]
Hi hobby4life, thank you very much, works great 
I was missing the info example system.playtone(x,y)
Thanks Benno
