### ISSUE TITLE
Lua: playTone() most of the time not working.

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#1487]
I am struggling with system.playTone()
Some of the time it works, and then of a sudden no tones are played anymore.

I know there where some issues in the past, But i figured they would be fixed by now.

Ethos v1.1.1
X20S

**Comment by dwheel** [comment]
Confirmed. Also, at times the tone will start but never stops. I have to exit the simulator to stop it.

**Comment by mawzthefinn** [comment]
Should be fixed in 1.4.3, can you confirm?
