### ISSUE TITLE
Feature request - flight data records (TD)

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#1488]
It would be nice to have the ability to assign a special function to a switch (on disarm, for example) that could automatically call the flight data logs from the tandem receivers to be displayed for review, without having to navigate through the menus

**Comment by bsongis-frsky** [comment]
It would be a ShowScreen function

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/42029df2-786e-4faa-8c70-e65f6eb6af77)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c55d669d-c749-4754-9fff-b6e62a3dc91e)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2f61fa7e-ee93-42c8-9d80-07829381f828)

**Comment by j-watkiss** [comment]
Awesome ! 👌

**Comment by bsongis-frsky** [comment]
Available in next 1.5.0 nightlies
