### ISSUE TITLE
update by  s- port

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#149]
Hello,
x12s os 1.0.3 ----- Could you please add the update by s-port? (firmware)
impossible for the moment only by OTA.
thank you .

I have a frsky g-x8r rx. Unfortunately, I made the wrong firmware when uploading, error message data.
since impossible to update it (fixed red led) you would have a solution ??? (unblock s-port)

**Comment by pld74** [comment]
@bsongis-frsky Thank you!

**Comment by bsongis-frsky** [comment]
The X12S has no S.PORT connector!

**Comment by bsongis-frsky** [comment]
Did you try to flash your RX as if you flashed your external module? Take care to the connection!
