### ISSUE TITLE
Switch names in Checklist selection

### ISSUE THREAD

**Issue by dunback** [FrSkyRC/ETHOS-Feedback-Community#1491]
In the Checklist the checked switch names are listed as "Switch A", "Switch B" etc. Why not the user identified names in the Hardware option? If it is necessary to keep the Frsky manual names, why not append the user identified name with the original Frsky designation?For example, user sets switch A as "Flaps", the system saves the setting as "Flaps-SA" or "SA-Flaps". This way the user has the flexibility but the physical switch label relative to the Frsky manual is not lost. Just a thought.

**Comment by bsongis-frsky** [comment]
This is a mistake

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/156576801-da1a965c-58b9-4ea0-b571-6ca8a4b535d7.png)
