### ISSUE TITLE
Add device config tool to change SmartPort sensor parameters.

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1492]
It would be great if there was a tool in the device config section to allow configuring of SmartPort sensors. Like how you can with the FreeLink app.

For example, you have two battery sensors and you want to change the ID of one of them. It would be great if you could just plug it in the SmartPort plug on the radio, open the SmartPort device config tool, and change the ID.

**Comment by ninodesposati** [comment]
That would be very cool.

**Comment by mawzthefinn** [comment]
Yes, that would be amazing.

**Comment by mawzthefinn** [comment]
This should be in the 1.5.0 Nightlies as of today.
