### ISSUE TITLE
how can I integrate a LUA script globally

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1498]
Hi there,

how can I integrate a LUA script globally in the ETHOS system, is there a way to do this? Possibly via a GLOBAL.LUA ?

Greetings Benno

**Comment by Benno00** [comment]
or possibly assign a lua script globally to a switch

**Comment by bsongis-frsky** [comment]
Which kind of script?

**Comment by Benno00** [comment]
e.g. for your own telemetry widget

**Comment by bsongis-frsky** [comment]
A telemetry widget? Global?

**Comment by Benno00** [comment]
Hello Bertrand,
I had thought of it as follows, provide a LUA via SYSTEM that can run by selection in the main screen and is valid for every model. But I think that's probably not possible? Therefore the topic can be closed here. Thanks very much.
Greetings Benno

**Comment by bsongis-frsky** [comment]
It would be indeed complex, because also the layout of the screen would have to be shared between models!
