### ISSUE TITLE
Change fixed switch off delay to configurable

### ISSUE THREAD

**Issue by onki69** [FrSkyRC/ETHOS-Feedback-Community#1499]
In OTX it is possible to define the delay time to switch of the transmitter.
In Ethos this is fixed to 4s.
Many users feel that as a pretty long time and are not that stupid to switch off the TX by accident.
It would add user friendliness to make the switch off delay more flexible be defining an individual delay.

**Comment by Hartinger** [comment]
May I suggest not to make it variable between 0,02 and 60s, as this would be a ridiculously useless change. If a variable delay is required, a reasonable range should be implemented, similar to OpenTx.
BTW, the delay is not 4s but approx. 2s, at least with my two ETHOS radios.

**Comment by bsongis-frsky** [comment]
Who will be satisfied with 60 seconds :)
