### ISSUE TITLE
Model channels glitch badly when model is powered up before TX warnings are cleared 

### ISSUE THREAD

**Issue by Webbsolution** [FrSkyRC/ETHOS-Feedback-Community#15]
TX X10S Express - Ethos 16 
RX Rx6R Access2.1 firmware 

Process to replicate issue: 

Create a 4 channel glider model (2 Ailerons, 1 rudder 1 elevator 
Create flight modes 
null - no source 
Thermal - 3 pos toggle down 
Cruise 3 pos toggle mid 
Speed 3 pos toggle up 
Landing  + 15% throttle stick deflection = logical switch = on , landing mode. 

Now power on the radio - note the warning for no failsafe and throttle not set to zero  - do not clear the warnings - 

Power up the model THEN clear the warning - watch the modes cycle through all available modes in like .75 seconds and the surfaces will go crazy...reboot the model - same behavior, reboot the radio - clear the warnings then star the model - no issues.

Edit - I have also managed to see this behavior without the model being powered on so my original assumption that this was triggered by some RF issue is wrong - its just appears to be a random unhappy boot and all the FM's cycle like mad.

**Comment by Nicholas-Luoyi** [comment]
Please share your model.bin here then I can take a look into it. Thanks!
