### ISSUE TITLE
how to properly use CATEGORY_SWITCH_POSITION

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1500]
how to properly use CATEGORY_SWITCH_POSITION
local sw=system.getSource({category=CATEGORY_SWITCH_POSITION}) give back nil
Thanks Benno

**Comment by Hobby4life** [comment]
For questions about how to work with ETHOS + Lua please use RCGROUPS.
This repository is only for tracking issues/problems regarding ETHOS :-)

https://www.rcgroups.com/forums/showthread.php?4018791-FrSky-ETHOS-Lua-Script-Programming

**Comment by Benno00** [comment]
ok Thanks
