### ISSUE TITLE
Feature request - hide unused channels in outputs

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#1501]
example - using the TDR18, channels 6 - 14. It would be nice to be able to hide the unused channels in outputs, to have the menu less cluttered and easily make changes.

**Comment by bsongis-frsky** [comment]
But those outputs can be used in the mixer as a temporary variable which can be used later in the mixing process

**Comment by j-watkiss** [comment]
![IMG20220303112645](https://user-images.githubusercontent.com/69600292/156555761-893e4086-4335-4ec9-9148-7bd0054dedd3.jpg)
![IMG20220303112635](https://user-images.githubusercontent.com/69600292/156555787-6a6f9602-149c-47ea-8983-cfb797ea737c.jpg)
![IMG20220227184911](https://user-images.githubusercontent.com/69600292/156555833-660f522e-6361-487e-afda-3bb7d212508b.jpg)


Using a receiver like this, model is set up but as you can see we have unused channels 1-5, we have used 6 - 14. It would be nice to be able remove these unused channel from view or see used channels as first in the list, purely to make set up and adjusments less cluttered

**Comment by Jedsters** [comment]
I guess the question is how do you define unused? 
If it has just been given a name, is it unused?
How about if any of the values have been changed? 
Or are you saying that it is unused if there is no output in 'Mixers etc.' to it?

**Comment by j-watkiss** [comment]
I mean, unused by mixers. So in most cases then not being used for any function

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mawzthefinn** [comment]
Note you can assign any channel to any port on the TD-R18 (and any channel port on a ACCESS receiver) so you can arrange the channels so no unused channels are on your display page.

There's no reason port 15 has to be Ch15, it could be ch6
