### ISSUE TITLE
Widget selection darkens some of the text (randomly?)

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1503]
video:
https://www.youtube.com/watch?v=TYygkp7Ds1E
Note: may releate to #1470 

4 issues:
1. why is text becoming dark when widget is selected? the popup menu is enough indication that a selection has been made.
2. if darkening the text, why does only part of the text go dark?
3. we shall consider adding a key to lock the screen from widgets selection during flight. if the screen gets pressed duriing flight by mistake all of the data becomes unreadable.
4. what is really the point in the first widget "selection" before opening the popup?

**Comment by bsongis-frsky** [comment]
Script bug. Please report to the author

**Comment by i3dm** [comment]
I am the author and all text fields are defined exactly the same. the fact that it behaves differently between text items shows its not a bug in the script.
