### ISSUE TITLE
Lua examples broken

### ISSUE THREAD

**Issue by jbienz** [FrSkyRC/ETHOS-Feedback-Community#1504]
Where can I find more information about LuaSource? #1429 is one of the only pages that shows up on Google and the LuaSource doc page is blank. LuaSource appears to be different from regular Source, and I'm hoping this is how I can create a Lua switch or analog. Thanks.

**Comment by Hobby4life** [comment]
I gues this is not ready yet.

**Comment by bsongis-frsky** [comment]
An example is there:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua

**Comment by Hobby4life** [comment]
it seems that some examples dont work any more in v1.1.1

Example does not increment, only stays at 0.

Servo example does nothing at all.

Something broken? :-(

**Comment by bsongis-frsky** [comment]
Example fixed in 1.1.2

**Comment by bsongis-frsky** [comment]
Issue title changed

**Comment by jbienz** [comment]
> An example is there:
> https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua

I don't mean to sound crass, but an example is where? If you search this repo for "LuaSource", no code appears at all:

![image](https://user-images.githubusercontent.com/2062886/156686510-664e11fc-5e24-4e52-af9e-f2b79be75192.png)

If I clone the repo and search the entire disk structure for any files containing "LuaSource", the only files are the docs pages.

![image](https://user-images.githubusercontent.com/2062886/156686922-c0fefd64-d74a-4bef-8ec9-2043abb9dec6.png)

I appreciate that there is now an issue to encompass the overall shortcomings with the examples, but I feel my original request for help with LuaSource has been lost.

To quote my original question:

> LuaSource appears to be different from regular Source, and I'm hoping this is how I can create a Lua switch or analog.

I would like to ask again if there is any way for a Lua script to behave as a source or a logical switch.

Thank you

**Comment by jbienz** [comment]
Doing further research into the examples, I think I now understand that doing:
 
`form.addSourceField`
 
Allows a Lua script to _import_ an existing source.
 
Conversely, doing:
 
`system.registerSource`
 
Appears to allow a Lua script to _export_ a new virtual source.
 
 
This was not clear to me. My confusion stemmed (stems?) from both samples referring simply to "source". In the examples, there doesn't appear to be a distinction between a source that is imported or a virtual one that is exported. 
 
Finally, the page for **LuaSource** in the [Lua Docs zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/main/testing/1.1.0-RC1/lua-doc.zip) is completely blank.

![image](https://user-images.githubusercontent.com/2062886/156696257-0f47781f-7693-401b-9a68-bb32a92562d3.png)

Thank you for working to improve both examples and documentation. I look forward to both learning and creating.

**Comment by bsongis-frsky** [comment]
LuaSource shouldn't be mentionned in the docs, it's a internal class inside Ethos. It will be hidden in 1.1.2

**Comment by bsongis-frsky** [comment]
The Source example ins the examples is fixed now (the problem was in 1.1.1)

**Comment by bsongis-frsky** [comment]
The Servo example has been tested and works correctly

**Comment by bsongis-frsky** [comment]
> I would like to ask again if there is any way for a Lua script to behave as a source or a logical switch.

The "Source" example does exactly what you need. Please wait for the fix in 1.1.2 to test it.
