### ISSUE TITLE
call  function write(widget) with code

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1506]
The function "local function write(widget)" is not called if I fill the widget.fields via source, is there a way to call the function via source code.
Thanks Benno

**Comment by Hobby4life** [comment]
Just call it i gues


write(widget)

**Comment by Benno00** [comment]
unfortunately it doesn't work, it throws the error "global 'write' is not callable (a nil value)"
for the field scrswitsch is not empty. i call  "write(widget.scrswitsch)"

**Comment by Benno00** [comment]
the same if i call "write(widget)"

**Comment by bsongis-frsky** [comment]
Please provide a very simple example of what you want to do. Write is not a global function, I wonder where you call write(widget.scrswitsch)!

**Comment by Benno00** [comment]
I would like to load default data into my widget and then save it immediately. At the moment I have to call up the configuration, change a value, only then is the configuration saved.

**Comment by bsongis-frsky** [comment]
The whole model data is saved, only when something has changed, why would you need to have something different?

**Comment by Benno00** [comment]
Yes, that's right, they are saved if something changes in the function configuration, but this function doesn't even notice if I e.g. assign a new value to the widget.switchx via lua. Only after I have called the configuration and change a value is it saved. Therefore I would like to call the function write(widget) with LUA, then my read default values would be saved.

**Comment by bsongis-frsky** [comment]
I understand you need to tell to the radio that the model data is dirty and needs to be saved when possible?

**Comment by bsongis-frsky** [comment]
In 1.1.2 I could add the function `model.dirty()` for your need

**Comment by Benno00** [comment]
Hello Bertrand, that would be great, thank you very much

**Comment by bsongis-frsky** [comment]
Done in 1.1.2

**Comment by Hobby4life** [comment]
Maybe another name like:

model.userdef()
model.userconf()
model.defconf()

are more apropriate?

**Comment by Benno00** [comment]
Hi Bertrand,
that's wonderful, thank you very much
