### ISSUE TITLE
Data is lost if wave file names have more than 31 characters

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1507]
A customer had the problem that when using "play track", model files were repeatedly destroyed. Data and images were lost. Especially if you have cloned a finished model.

After long tests, it can be reproduced that everything works as long as you do not use more than 31 characters including spaces for the file name. If you use 32 or more, there are problems.

**Comment by hrenz** [comment]
dont use more then 11-15 character for a name or for a filename 8.3
