### ISSUE TITLE
Use minimum and maximum values of sensor values

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#1509]
Currently using 1.1.1 EU Firmware on X20S
It would be very helpful to be able to use the minimum and maximum values of sensor values in the "Value" widget (just like in OTX)
In OTX, I use it to display for instance the maximum current drawn and the minimum RSSI encountered during the flight, or the maximum altitude reached for my gliders.

**Comment by MIKE-DAILEY** [comment]
Whenever you see the small square un the upper left corner of a cell it indicates more options with a long press, e.g. min, max.
