### ISSUE TITLE
No 2.4 Telemetrie if 868 MHz is set to 200/500 mW (TD R18)

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1511]
As stated in the title, increasing the output power to 200 or 500 mW turns off the telemetry for 868 MHz and 2.4 GHz. If you use two single receivers and operate the 868 MHz with 200/500 mW, the 2.4 GHz telemetry continues to work,

Maybe it's a bug in the TD R firmware. Of course, I cannot judge that.

**Comment by Adelaxie** [comment]
I will check that and please report the ETHOS only issue here because of that only ETHOS team would follow this repository.
Mail to the official mailbox frsky@frsky-rc.com about other requests, thanks.
