### ISSUE TITLE
'Telemetry Lost' when switching transmitter on for the first time

### ISSUE THREAD

**Issue by petermumford** [FrSkyRC/ETHOS-Feedback-Community#1512]
### Specs
- Transmitter: X20S
- Ethos Version: 1.1.1
- Internal Module:
  - HW: 1.4.0
  - FW: 2.1.1.4 (EU-LBT)

### Description
It doesn't make sense to send an alert saying 'Telemetry lost' when first switching the transmitter on. Should only send alerts after a signal is received.

**Comment by bsongis-frsky** [comment]
Which transmitter?
Everything is up to date, including the module?

**Comment by petermumford** [comment]
@bsongis-frsky - Updated first post with details
