### ISSUE TITLE
ELRS for x20 and x20s working with erskytx

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#1513]
those who need their x20 working with elrs modules can refer this link https://openrcforums.com/forum/viewtopic.php?f=7&t=13679  
Mike, this guy did it and we can even toggle between ethos and erskytx as well which is a cool feature. I really wish Ethos devs should add the support to crsf soon. Its already too late.....

**Comment by bsongis-frsky** [comment]
Duplicate of #5
