### ISSUE TITLE
lua: enhancement request, add option to disable page swipe

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#1514]
When using multiple widgets with fullsize bitmaps and live data. swiping is eating CPU.
Using Page button works fine, with a delay.. but works good.

Let us be able to have an option in Lua to disable / enable Page swipe for such scripts.

When swipe disabled.
It will only switch directly to the next widget, not scroll.

Or a system setting, disable/enable swipe.. just switch pages even with swipe action.

**Comment by loetefix** [comment]
or make swipes like a jump. if you swipe, then the screen jumps to next screen .

**Comment by Hobby4life** [comment]
Correct, thats what I meant with "switch pages" :-)

**Comment by loetefix** [comment]
oops, yes . it seems i did not read your request completely. sorry.

**Comment by Hobby4life** [comment]
No problem :-)

**Comment by i3dm** [comment]
Yes that will help #1502
