### ISSUE TITLE
Inverting Logical Switch member in member selection popup menu modifies wrong member

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1515]
Inverting a member on a Logical Switch AND (maybe others?) in the popup window where you can select a different member, Inverts the wrong member.  Hard to explain...
here is a video showing it.  (video is unlisted so only see it with the link)
https://www.youtube.com/watch?v=GMXYyM0IUJk

If you modify/invert the member from the main logical switch area (without going into the menu to select another member), it works properly.

**Comment by Nicholas-Luoyi** [comment]
It's truly an issue. Right now, please [LONG PRESS] on the value 1 after the pop up menu closed.
