### ISSUE TITLE
Ethos.  Mode 2 to mode 1 on sticks of x29

### ISSUE THREAD

**Issue by RcEddie** [FrSkyRC/ETHOS-Feedback-Community#1518]
Mode one with throttle on right stick.  Timer will not trigger with throttle.  Is there additiobal setups in sticks?  It triggers with left stick (elevator) when throttle trigger is selected.  Mode 1 is mot moving throttle trigger on timers to right stick?

**Comment by KAID-YANG** [comment]
Hi, what's your X20 version? Please provide the model file. Thank you

**Comment by bsongis-frsky** [comment]
It should work, please provide more information so that we can help

**Comment by RcEddie** [comment]
1.1.17 version.  
Need to go to 19.

**Comment by RcEddie** [comment]
When the throttle trigger is used to start timer it still responds to the left stick not the right stick when in mode 1 setup. Mode 1 throttle on right stick.  I pull the left stick full back which is elevator stick.  Then I center it the timer then starts count down.  It is set properly for throttle trigger    And sticks are configured mode 1.  There does not seem to be any other settings in stick configuration to assign the throttle trigger or throttle absolute. 
Regards
Ed Bailiff

**Comment by Nicholas-Luoyi** [comment]
I haven't met the situation that you described. Or you could post your model file here so we could see what's going wrong.

**Comment by RcEddie** [comment]
Will do.   Next few days. Got some other things going.  Thanks   Ed

**Comment by j-watkiss** [comment]
It works fine for me, on 1.1.1 and now 1.1.3
