### ISSUE TITLE
Sim/Lua: event handler always gets "Page_dn", no "Page_up" event 

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1519]
Using X20 Sim 1.1.0 (seems to be the latest)

Independent of area which is pressed on the page Button, event handler always gets "Page_dn" event.

[event.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8196079/event.zip)

**Comment by bsongis-frsky** [comment]
You have to kill the event in case of PAGE_UP

**Comment by strgaltdel** [comment]
Hi Bertrand,

thanks for the quick response,
maybe my description was not exactly, or i don't understand,

> You have to kill the event in case of PAGE_UP, you won't get the PAGE_DN then

**there is no pageUp event by using the sims (wouldn't rule out failure on me)**
please don't bother further

what i meant:
My X12 hardware does definitely "acknowlege" pageUp/value=97 and pageDown/value=96 to the event handler by pressing the dedicated buttons.
I would assume the "combined" button of Tandem & X10 transmitters does too, dependent wether you press upper or lower area.

But both simulators do only return 96/pageDown, at no time 97/pageUp no matter when and where you press

regards
udo

**Comment by strgaltdel** [comment]
just checking my older issues...
according to
#2066 
#2040 

there will  be a major change in handling these kind of key events within lua widgets, starting with 1.5.0

so i would propose to close this issue until we can test a new implementation, 
and, if needed, open new issues based on that functionality 

regards
udo
