### ISSUE TITLE
play track, special Function, no sound selection possible.

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#152]
play track, special Function, no sound selection possible. You can find your own sounds under audio / ...
Ethos 1.0.4 Horus 10s

**Comment by MIKE-DAILEY** [comment]
X10S ISRM and X10S Express SF "play track" working here.  Are you sure you have your user sound wav files on the SD card in the audio folder?  There are sub folders in audio but you want audio.

**Comment by Skippydi** [comment]
Yes it's right. If the sounds are under audio it works. But it would make more sense if the user sounds were under the corresponding country code. For example audio / de / ...

**Comment by MIKE-DAILEY** [comment]
They are under audio so that there does not need to be user sounds for each language.
