### ISSUE TITLE
LUA: bit32 library not implemented

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1520]
Hi,

Ethos Lua is based on rev 5.4.3, coming with several libs, but lacks the bit32 lib which is standard lua implementation since 5.2.

bit32 lib supports a lot of useful bit operations, so i would vote for implementation in ethos
https://developer.roblox.com/en-us/api-reference/lua-docs/bit32

Thanks & regards

Udo

**Comment by strgaltdel** [comment]
i would propose that this issue can be closed
(if Bertrand agrees)

some research showed that lua  5.3 introduced bitwise operators,
so i guess there is no need for bit32.lib any longer

https://www.lua.org/manual/5.3/manual.html#3.4.2

**Comment by bsongis-frsky** [comment]
Of course you are right, I have discovered it when writing the Lua scripts for ELRS
