### ISSUE TITLE
Using 2 separate channels/mixes for ailerons removes differential option

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#1521]
Using Ethos 1.1.1 on X20S
I tried configuring an SR8 Pro receiver on a model with 2 aileron servos that have been installed "mirrored".  
When using the Ailerons mix for 2 channels, due to the mirroring of the servos, I get aileron movement in the same direction on both sides.
I can inverse the channel in the Outputs page, but then the stabilization output is reversed too (tested in auto-level mode).  Differential is incorrect too.
I then made 2 separate Aileron mixes, one for channel 1 and one for channel 5.  When I tried to modify the differential, that option was gone from the mix page for these channels.
When I changed the mix for channel 1 to 2 channels again, and selected output 2 (instead of Output 1, to get the inverse movement), the Differential option was back.  This is not logical and incorrect behavior.
I think the differential option should remain visible with 1 or 2 channel outputs in the mix.  And it would be easier to configure the aileron mix for 2 channels for mirrored servos if you could invert any output channel from the mixer page, or at least line this inversion up with the stabilization function in the SR8.

**Comment by mawzthefinn** [comment]
Differential is only possible if outputting more than 1 channel. The Aileron mix assumes it is the only one and if configured to single channel it is assuming a single aileron servo or a Y cable is in use, rendering the differential option irrelevant. The differential setting is specifically applying two different rates on each side of the mix, but it applies them differently to each channel. This is standard behaviour for canned mixes on most radio systems. 

That said, this sounds like a setup logic issue. You're tripping over what the SR8 is doing vs what the radio is doing (easy to do, the documentation for the Stabilizers is poor).

You need to be inverting the second aileron channel in Device Configuration->SxR, and in the Outputs, never in the mix.

Use one mix and reverse servos only at the output or receiver stages of the chain.

And don't forget to self-check afterwards and go through the servo ranges. Otherwise your self-level will not have the differential you programmed. 

I just ran though this with an SR8 on the bench. After setting everything up I was able to fully configure stabilization and control, then Self-check to learn servo ranges (which taught the receiver all differential, which it respected in self-level)

**Comment by phaedra-tm** [comment]
I think that not doing the self check caused the erratic behavior that I saw.  I initially did exactly what you specify, inverting one channel in outputs and in the SxR setup, but then I saw the auto-level applying the wrong differential.  I didn't know that the self-check corrects this.
I will try this later today and report back.
Thanks!

**Comment by phaedra-tm** [comment]
Ok, some follow-up.
I tried your solution, and it works except for one detail: in auto-level, I'm not getting any differential on the ailerons.
What I configured:
1) aileron mix, channel 1 and channel 5, 50% differential
2) inverted channel 5 in output
3) inverted both aileron channels in SxR setup (!).  Is this logical?  Ailerons move in the correct direction in all modes.
4) did the self-check.  That was a hassle, as the definitions for "switch up", "switch mid" and "switch down" aren't respectively 100%, 0% and -100%.  Only after I swapped two of these in my mix for channel 12 I could enter the self check.  This is really very poorly, if at all, documented.  I had to find it by trial and error, the documentation only mentions up, down, mid.  And the switching between the 3 positions has to happen way more quickly then in 2 seconds, rather in 1 second.
After that, I started testing.
First thing that I noticed, was that I couldn't see any differential movement of ailerons, even though I initially set it to 50%.  Only after I changed that value, I got to see the effect.  (in manual movement of the ailerons).  I can't remember if I could see actual differential movement before the self-check.
Second thing: I don't seem to get differential in auto-level, which isn't really a big issue.  
Can this be reproduced on the bench?

**Comment by mawzthefinn** [comment]
First off, I recommend doing the following setup regarding Self-check.

1. Self-check mix assigned to a switch with no additional configuration added. Set the Active condition so this mix cannot be activated in flight (I tie it to Throttle Hold).
2. Self-level engagement on a separate mix, active when self-check is not.

I find this works very well.

When you did self-check, did you wait for the blue light to start flashing, then move all the channels with assignments to their full extent, then wait for the receiver to complete the self-check and exit?

I get differential in auto-level then. The receiver needs to see the differential in the self-check throw demonstration.

Note however that Auto-level operated based on the receiver's stored servo limits so if you have for example setup modes with and without differential, or flaperons which exceed the differential throw, you won't see differential in auto-level. 

And yes, this is really badly documented. Plus the manual is wrong in places (no self-check trigger in Device Configuration) and the SR's operate differently from the SxR's and R9 Stab.

**Comment by phaedra-tm** [comment]
First of all, the setting issues for initiating the self-check were caused by the bad documentation.  I assumed that "switch up" meant 100%, "switch mid" meant 0% etc.  When I programmed my switch like that, it was impossible to initiate self-test.  As soon as I swapped the up and mid value, it worked immediately.
The self-check went correctly, but I guess the differential wasn't working before the self-check, and thus these throw limits weren't detected by it.
The strange thing was that a differential value of 50% was set on ailerons, but it wasn't applied when I moved the ailerons.  I then modified the differential value by only a couple of %, and after that small change the differential did show in the movement.  I'm not sure how to reproduce this, but it was really the case.  I measured deflection up and down, and it was identical first (with the 50% value set).  After my modification of differential, it worked correctly.
Maybe the switching between 1 and 2 channels for the aileron mix caused the differential to not be applied correctly?

**Comment by mawzthefinn** [comment]
How do you have your self-check mix programmed?

It should be a Free Mix, with the source as a 3-position switch and the Output as Ch12, Active Condition should be set to something that prevents activation during flight (I use Throttle Hold). It will work correctly then so long as your Swicth middle detect delay is set to 0ms in System->Hardware->Switches Settings

**Comment by phaedra-tm** [comment]
First of all, the setting issues for initiating the self-check were caused by the bad documentation.  I assumed that "switch up" meant 100%, "switch mid" meant 0% etc.  When I programmed my switch like that, it was impossible to initiate self-test.  As soon as I swapped the up and mid value, it worked immediately.
The self-check went correctly, but I guess the differential wasn't working before the self-check, and thus these throw limits weren't detected by it.
The strange thing was that a differential value of 50% was set on ailerons, but it wasn't applied when I moved the ailerons.  I then modified the differential value by only a couple of %, and after that small change the differential did show in the movement.  I'm not sure how to reproduce this, but it was really the case.  I measured deflection up and down, and it was identical first (with the 50% value set).  After my modification of differential, it worked correctly.
Maybe the switching between 1 and 2 channels for the aileron mix caused the differential to not be applied correctly?

**Comment by phaedra-tm** [comment]
That delay was set to 100 msec; that might explain the difficulty somehow.  I set it to 0 now.
I changed the mix to a VAR mix and fixed values for the associated switch, and that worked too, as long as I associated 0% to switch up, 100% to mid position and -100 to down position.  When up was +100 and mid 0, it didn't work.

**Comment by mawzthefinn** [comment]
The delay is definitely part of the issue you were having. It really needs to be configurable on a per-switch basis.

Now that you have it set to 0, I do recommend re-doing your self-check mix to what I describe above. Using a VAR mix should work, but it's overly complicated and hard to troubleshoot.

**Comment by phaedra-tm** [comment]
OK, thanks
I will try to reproduce this scenario where the differential isn't showing in the movement.

**Comment by phaedra-tm** [comment]
I haven't been able to reproduce the issue about the differential so far.....

**Comment by mawzthefinn** [comment]
Has this re-occurred, or can this issue be closed off.
