### ISSUE TITLE
Silent Mode not Muting when system volume assigned to a source

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1522]
ETHOS 1.1.1 on Horus X12S

I've assigned system audio volume to L2, set all the way down, duplicated with other sources (Pot 1 as well as Special->Minimum)

Radio powers on and correctly indicates Silent mode in the startup warnings, but all callouts are audible, if quiet.

Sliders are recently calibrated, System->General audio volume showing minimum volume

Works correctly (silent mode warning and no audible callouts on startup) if the volume is set in the System->General menu instead of from a source, or if the Mode is set to Silent in System->General.

Works correctly with a Source on the X20 on 1.1.1

**Comment by bsongis-frsky** [comment]
Are you saying it's the same on X12S with Source = Special / Minimum?

**Comment by mawzthefinn** [comment]
Yes, it won't mute if any source is used on the X12, I tried Special->Minimum to ensure the issue wasn't calibration on my sliders.

only mutes if you are using the menu slider or set to Silent in the menu

**Comment by bsongis-frsky** [comment]
And only on radio startup? I mean not when another Model is selected?

**Comment by mawzthefinn** [comment]
Yes, only for sounds that trigger on startup. Anything triggered afterwards is silent, even without changing models. No callouts on a model change either.

In further investigation, it seems like the Mute is getting set late in the initialization of the radio.

**Comment by mawzthefinn** [comment]
Still a (minor) issue on 1.4.4
