### ISSUE TITLE
Implement mobdebug in Simulator

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#1523]
Add functions and modules to the simulator to enable usage of standard remote debuggers that are enclosed to Lua development environments (ZeroBrane Studio, IntelliJ IDEA). Modules contained in the Emulator that are not included in the hardware:

- ModDebug
- Debug

**Comment by bsongis-frsky** [comment]
I am afraid it's a lot of work, it means we have to display a Lua editor with the possibility of adding breakpoints etc.

**Comment by wmayvis** [comment]
You start the remote debug functionality in ZeroBraneStudio.
In your LUA script you add the following require module to establish the connection with the remote debugger.
require("mobdebug").start()

https://github.com/pkulchenko/MobDebug

https://studio.zerobrane.com/doc-remote-debugging

**Comment by wmayvis** [comment]
I just found out a workarround, but the simulator is missing the requirement coroutine. If this will be available, remote debugging should be worked. 
---------

1. Add mobdebug.lua in the scripts folder of the simulator (C:\Program Files (x86)\FrSky\Ethos\X20\scripts\flvss)
2. Start remote debugging in ZeroBrane Studio
3. Add following code line at te the top of your lua widget
 require("mobdebug").start("127.0.0.1") 
You can see the ipaddress or domain name to connect to in the Output window when you start debugger 
server: Debugger server started at <domain/ip>:8172.  

The following error occured: error: .\mobdebug.lua:12: module 'coroutine' not found 

![Screenshot 2022-03-09 094759](https://user-images.githubusercontent.com/7701921/157406817-469f2f3a-a778-4e10-8af1-4d9966e04fc8.png)

Hope that this will help to implement easily

**Comment by wmayvis** [comment]
What is the status?
