### ISSUE TITLE
Add Sbus Servo Channel Changer functionality to Device Configuration

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1524]
The FrSky Servo Channel changer device is often hard to find and is necessary for configuring SBus to PWM decoders, FrSky's old SBus servos and 3rd party Sbus servos.

It would be great if you could use the S.Port port on the transmitter for this via a Device Configuration menu item.

The ability to do Sbus servo testing (Ie send arbitrary values to the selected channel) would would also be nice, if implemented in the same menu item.

**Comment by Hobby4life** [comment]
I agree.

But not only for changing servo channels.

I have talked to Adela about this, **All** sensors and Xact servos should be configurable with the smartport output on the radio too.

**Comment by mawzthefinn** [comment]
I agree, but that would be two different changes. One is leveraging the current S.Port support on this output (which is what you are referring to) to be able to fully configure S.port devices in addition to FBus devices. 

The second adds Sbus out as an option, which is a bigger change on the backend as right now that port is only doing S.Port or Fbus.

**Comment by mawzthefinn** [comment]
Closing off, the long-term solution is FBus, XAct and the Servo Lua
