### ISSUE TITLE
Disabling trim doesn't disable trim options

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1525]
Apologies if I'm missing something, however when you disable a trim, the Extended trims and Independent Trim per Flight Mode options remain enabled. 
I can't help feel that once a trim is disabled that these options should be greyed out (and maybe their previous values left as is in case it is later re-enabled). 

Unless these options still do something when the trim is disabled?

![image](https://user-images.githubusercontent.com/96293240/157457894-045e002f-634e-467f-b8e7-34da7f137ee1.png)

**Comment by mawzthefinn** [comment]
I beleive those options still affect the trimmer as an input functionality, which can be used if the trim is disabled.

I do wish the labelling was more descriptive. Specifically the trims are labelled differently on the radio than in the OS, plus the control is not optional.

Frankly, this is why ETHOS needs an Inputs layer so we can configure the inputs directly, or use the trims as an input class, then configure trimmer behaviour somewhere else (Flight Mode configuration?)

Per-FM trim should be an FM setting, Extended Trims should only operate when the trimmer is being used as an axis trim and should be an input setting along with trim assignment. Trim steps should be separate from on/off and an input setting.

**Comment by hrenz** [comment]
It is a mistake that ETHOS has no INPUTS. 
OpenTx was later extended with INPUTS too, because this simplifies many things.

**Comment by Jedsters** [comment]
I guess it depends on what Disable is meant to disable. Since Disable does not set existing trim to zero (which seems reasonable, as it is more of a 'lock trim'), it appears to mean that you can't change the trim values using the trim switches. However changing the Extended trims or FM trims options even while Disable is selected could result in the trims being changed.

That feels wrong to me, although I can see that there is an argument which says you're already on the same screen so what's the point in forcing someone to Enable the trim to change an option if they are then going to Disable it again, however, if I was changing one of those options I'd be wanting to look at what effect it had before Disabling trim mode again.

**Comment by mawzthefinn** [comment]
And this is exactly why an Inputs layer is needed.

We need a way to disconnect trims from inputs, in cases where they are not used (throttle trim on electrics or sailplanes for example) so the trimmers and their FM-dependent values can be re-used for other things (mix adjustment, gain control, etc). 

But the current setup is not clear in terms of what the Trim settings actually do.

**Comment by mawzthefinn** [comment]
Disabling trim now clears the trim values, as per the fix for #1890
