### ISSUE TITLE
Request: Reset for Outputs

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1527]
Please can we have an option to Reset Outputs? 

Currently, it would appear the only way to get rid of an unwanted Output is to manually delete the name and change all the values back to their default. Of course it is not necessary to actually change all the values back to their default values, however by doing so, this reduces the likelihood of accidentally introducing a bug because you don't realise that a value isn't the default at some future point when you attempt to use the same output again.

Thanks.

**Comment by Jedsters** [comment]
Yes, I was having a moment of madness! I've edited the request to just be reset for outputs.
I did also wonder about Clone etc. but was less convinced by the need for that. 
Thanks for spotting that.

**Comment by mawzthefinn** [comment]
Cloning would be useful when setting up multiple channels with specific ranges, for example if you are doing a drop-in replacement of a Spektrum receiver you can set the Outputs to -78 to 78 and then your mix % values transfer right over from the Spektrum radio. Much easier to do once and clone the settings to multiple channels.

**Comment by Jedsters** [comment]
Please can someone advise how I can remove the stale label? (Or can I?)

**Comment by mawzthefinn** [comment]
Just commenting will negate the Stale tag.

**Comment by bsongis-frsky** [comment]
Included in next nightlies
