### ISSUE TITLE
Bug: DIY sensor value of Neuron telemetry jumps between value Volt and Ampere

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1531]
Hi Developer,
In my plane I'm using the DIY sensor to calculate the Volts from a 3s battery via Neuron 60S telemetry to an average cell value (33,3%). 
When the plane is flying and there is some current coming up, the value of the DIY sensor jumps between the correct value of the calculated battery cell and 10V. The current telemetry is on the same address. My assumption is that the DIY sensor can not distinguish between this different telemetry values. The regular telemetry values can do this.
Please can you fix this bug in the DIY sensor?
Best Regards
Bernhard

**Comment by Hartinger** [comment]
This is a (further) indication that there might be a problem with those Data IDs allocated to the transmission of two telemetry parameters in one S-Port package. AFAIK the Neuron uses Data ID 0x0B50 to transmit both voltage and current and apparently, ETHOS has a problem to separate these two values.

**Comment by bsongis-frsky** [comment]
It works very well on Neuron. And yes if you use 0x0B50 you have to transmit both current and voltage in the same frame (16 bits for each value)

**Comment by BernhardFe** [comment]
It works well on the sensor that is automatically read. But the DIY sensor has another behaviour. Since the new ETHOS version 1.1.2. I'm using the Physical ID 10 and the Application ID 0B50 as default. Now the DIY sensor shows 100V maximum or 100A.  Please reopen the task since it is not working any more at all.
![IMG_2797](https://user-images.githubusercontent.com/86232280/159645844-d273fe84-d97d-46dd-8810-6e2df458ac20.jpg)
![IMG_2798](https://user-images.githubusercontent.com/86232280/159645971-9a647efb-5979-4822-84d8-150623a05f6f.jpg)
![IMG_2799](https://user-images.githubusercontent.com/86232280/159646023-58fa856a-02f7-4c2b-bbc2-a063656fc08d.jpg)

**Comment by bsongis-frsky** [comment]
DIY sensors don't allow any use of a SubID (it would be complex, because there are a lot of ways to mix 2 values into 32 bits!)

DIY sensor should use their own ID, with only one value (32bits) transmitted in one frame.

**Comment by BernhardFe** [comment]
Deciding on the Value V or A the decision can be done indirect by assigning the first or second block to the selection of V or A. So I think that would be possible even if the first or second 16 bits are always fixed in the relation to Sub-ID. Its this can not done automatically assigned, it would be possible to select it as a selection Value by manual choice of the sub-ID.

If all this is not possible or to complicated, there would be another option. Since it is possible to take a ratio also in the default automatic sensor. Calculations can be done there as well. If you make an option to clone the automatic reader sensor Ee.G. Bat V, the original can stay as is and the clone can be configured. Since the ratio is limited to 10% the adjustments for the exactness and the coma shift would be needed to divide a voltage (or gear) by a higher value (12S Battery, Gear > 1:10...)

**Comment by BernhardFe** [comment]
Hi Bertrand,

please can you reopen the request? We should not forget this. :-)
It would be really a feature I can use in all my models in the telemetry.
It is much easier to look always to one Cell as to switch between all the different models with different critical Voltage for the several battery configurations.
this is also related, with the external sensors for Spirit FBL: #1472
Now I know, seems to be the same problem.
Best Regards

Bernhard

**Comment by bsongis-frsky** [comment]
Reopened to not forget to read the latest comments

**Comment by bsongis-frsky** [comment]
The spec says that both fields must be there. If you don't follow the spec, why do you reuse this ID? Just take any other ID!

**Comment by BernhardFe** [comment]
I assume that you talk about this case? 
If yes, my understanding is that the Physical ID defines the identifier for the receiver. 
The application IDs defines the addresses for all the value in ETHOS for one specific 32 bit data frame that contains 2 16bit values. 
In the Neuron there are several. In the case of Neuron ESC the A and the V have the same Application ID. 
If I choose in the DIY sensor another application ID or the physical ID, the value can not be identified any more, correct? Which ID should I change where then? 
I want to use the sensor hardware twice, once for showing the over all value of the battery (original Auto Sensor) and in parallel for the DIY sensor that shows me the same value divided by a factor to calculate one cell. If i would change the application ID in the DIY Sensor, the value can not be identified any more. Where is now my assumption wrong?  
That's why I talked about the tow options of cloning the original sensor make the fort or second half of the 32Bit frame selectable.
For me it sounds that I could not explain that I want to use the same sensor twice and you assume an additional hardware.
If there would be another hardware then you are right and it doesn't work. But using the same sensor twice would be the use case described here. That should be possible to have it once unchanged and once additionally calculated. Hopefully I could explain it more specific now.

**Comment by bsongis-frsky** [comment]
> If I choose in the DIY sensor another application ID or the physical ID, the value can not be identified any more, correct?

Correct

**Comment by bsongis-frsky** [comment]
In fact you can reuse any AppID as you wish. But today DIY sensors only accept 32bits values. It means that for sending 2 different values, your sensor will send 2 kind of frames, each one will have its own AppID.

**Comment by BernhardFe** [comment]
I want to use the same sensor double because showing 3,7V (DIY = one cell) and the other 11.1V original complete ESC Voltage telemetry.

For the Neuron the current and the voltage of the battery have the same Physical address and AppID by default and it works with the normal telemetry. 10 0B50 for both! 

The DIY can identify (blinking) but not separate between both values in the 32 bit even if I choose A or V. This functionality is missing / buggy compared to the regular telemetry in the ETHOS function for the DIY programming.

**Comment by EngelMT** [comment]
Hi Bertrand,

I understand what BernhardFe wants and it is not such an unusual request. Perhaps you will think about his suggestions again. Or maybe you have another idea that would make Bernhard's wish possible.

**Comment by bsongis-frsky** [comment]
As explained above, his sensor has to use 2 different AppIDs.

**Comment by BernhardFe** [comment]
Hi Bertrand,
want using the "**same**" sensor "**several times**" how can I give different AppIDs? 
I guess, that is a requirement you also can not fulfil too. ;-) But if yes, how?
Again, I use the same physical sensor twice in the telemetry and not two different hardware sensors on the same ID's.

**Comment by bsongis-frsky** [comment]
Indeed you can send 2 different frames using the same sensor. Just wait for the polling of the PhysId, one time you send AppID1, next time AppID2, etc.

**Comment by BernhardFe** [comment]
Please can you help me and give me an example how to do this with the Neuron? What are the steps to activate this? In Ethos? That would be very interesting.
