### ISSUE TITLE
Curve behavior

### ISSUE THREAD

**Issue by Amahoser** [FrSkyRC/ETHOS-Feedback-Community#1533]
Hello.  I browsed and cannot find a similar thread.  So hopefully this is new. 

I've created a 4 point curve as follows:
Point 1 -100
Point 2 +100
Point 3 +100
Point 4 -100

I set a slow up and down of 6 seconds for each. 

I add a source as a 3 pos switch.

I want the servo to start full down.  When I hit the switch to the middle position,  it should take 2 seconds to travel to the full up position.  If instead I go directly to the down position,  servo should go travel 2 seconds to the up position,  wait 2 seconds then take 2 seconds to travel to the down position. 

I've programmed this on open tx and edge tx and it works as expected.  On Ethos, moving the switch to the middle position,  it takes 6 seconds for the servo to move to the up position.  However,  if I instead flip the switch to the down position (bypassing the middle position), the servo does nothing.  Since it's already in the down position,  it stays there. I would like the servo to follow the curve and the slow.

Thanks
Jose Soriano

**Comment by Amahoser** [comment]
I've explored the problem a bit more and to add to my previous comment and for clarity: 

Using a switch seems to disregard curve.  It uses the curve to define end position at the point in which the switch position intersects the curve but adding the slow should make it follow the curve but it does not.  A good example of this:  create a 9 point or more curve.  Modify each point so it is max throw.... -100, +100, -100 etc. Assign a switch as the source.  When you hit the switch,  if at the switch position it is opposite throw,  it will move to the position with the slow rate that is defined.  It will not follow the up down up down curve. 

I posted this on rcgroups and got a work around by creating a free mix that just has the slow defined on a free mix on a dummy channel and using a switch as a source.  Then I use that channel as the source for the mix.  Worked essentially by using that dummy channel instead of a switch.

**Comment by mawzthefinn** [comment]
The switch behaviour in ETHOS is to switch between values rather than to transition between values. That prevents the curve from behaving as you expect.

I can think of a couple options to fix, but all require use of a second mix to condition the input.

**Comment by mawzthefinn** [comment]
Re-opening as another user has reported it

**Comment by bsongis-frsky** [comment]
Will be part of the big FreeMix refactoring which has started and which will be available in nightlies soon!

**Comment by bsongis-frsky** [comment]
Available in nightlies tomorrow
