### ISSUE TITLE
Offset and Ratio for all Senssors

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1535]
Please allow the use of offset and ratio in all sensors.

The measurement accuracy of most sensors is quite inaccurate. This is the case with the RBs. There is e.g. the current with same accumulators and same load around 0.5A between both inputs differently. This results in incorrect consumption values etc.

It is normal that a low-priced product like the RBs cannot be very accurate measuring devices. But then the customer must at least have the possibility to calibrate the sensors with offset and ratio.

**Comment by mawzthefinn** [comment]
This is a duplicate of your previous issue #955 and answers the question I posed there earlier. This should be closed off in favour of the previous issue.

**Comment by EngelMT** [comment]
I mean mainly voltage and current sensors. I can't say whether it makes sense to add ratio and offset to the vario height sensor, for example. Probably not because no one can check it exactly and therefore cannot adjust it via ratio and/or offset. With temperature sensors, for example, the situation is different. You might be able to use it there.

**Comment by mawzthefinn** [comment]
I agree, current makes sense given the accuracy drift between sensors and temperature too (temp sensors are really voltage sensors anyways, at least in how they are read)

Are you OK with closing this issue and continuing the discussion in #955 ?

**Comment by EngelMT** [comment]
Yes, I will do it.
