### ISSUE TITLE
Problem with Subtrim over 100%

### ISSUE THREAD

**Issue by Beastyboy80** [FrSkyRC/ETHOS-Feedback-Community#1536]
My f3j Plane need subtrim over 100% for the flaps .

It´s a very strange way to  put it over 100% .

frst Step : i adjust the Servo Endway under 100%  ,so the Subtrim  goes under 100% ,too.
Second Step : adjust the Servo Endway over 100%
Thirt Step: and now , is itpossible to adujust the Subtrim over 100%

**Comment by mawzthefinn** [comment]
Would strongly recommend using the new Offset mix instead to achieve this.

**Comment by mawzthefinn** [comment]
Closing as solution has been provided
