### ISSUE TITLE
1.1.1 Hebrew: missing Yes/No buttons on pop up

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1537]
This happens on most cases, but not all.
X20
V1.1.1 Hebrew
This popup says "are you sure you want to delete this mixer?" but confirmed this happened in several different menus.
pressing the knob does confirm the deletion, but no buttons show so cantt use the touch function here.

![yesno](https://user-images.githubusercontent.com/8968780/159284136-a4e21bc4-1054-4088-bb8d-e7c05facfa94.jpg)

**Comment by bsongis-frsky** [comment]
Related to this issue I notice that the text can be scrolled horizontally!

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/159515603-bbb78d89-4bf9-4715-a0dc-ac9879e7ed99.png)

**Comment by i3dm** [comment]
> Related to this issue I notice that the text can be scrolled horizontally!

what do you mean?
