### ISSUE TITLE
1.1.2 long press model select not possible

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#1539]
Model Select long press return no funktion

**Comment by bsongis-frsky** [comment]
Why do you need this shortcut, now we have removed the confirmation dialog, it makes the shortcut less quick than the normal operation (2 times [Enter])

**Comment by kakashi2018** [comment]
It is allowing us to select a model directly by long pressing on the touch display, So we are expecting the same behavior with the buttons as well.

**Comment by bsongis-frsky** [comment]
Without the confirmation (which has been asked for removal when no receiver bound to the model), I think it is very strange. I propose we remove both shortcuts, which are not shortcuts anymore, as you need more time to wait for the Long delay.

**Comment by Cipta-de** [comment]
Sorry its new for me that this behavior has changed. I'm not sooo the touch type - may I should change to use the touch more often. It's ok for me - just different to the used behaviour. 😉

**Comment by bsongis-frsky** [comment]
[Touch Long] shortcut removed

**Comment by centertrim** [comment]
My problem has always been that it’s too easy to accidentally touch the clone option instead of the select model option.  Which then clones the model and is very annoying.  This is the reason I preferred the long touch to select - no chance to accidentally clone the model.

**Comment by Hobby4life** [comment]
I agree, removing this option is a big drawback regarding touch functionality.
I was really happy with this method to switch de easily between models. 😒

**Comment by centertrim** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/945
