### ISSUE TITLE
X20 will not bild to any d16 rx

### ISSUE THREAD

**Issue by shaun-3d** [FrSkyRC/ETHOS-Feedback-Community#154]
Can not Bind up to  any d16 rx

**Comment by MIKE-DAILEY** [comment]
Does the D16 receiver have 2.1.0 or newer firmware that matches your system EU or FCC?

**Comment by shaun-3d** [comment]
Yes put  newer firmware on and still not binding

**Comment by shaun-3d** [comment]
Tried at three other receivers and all them will not bind to

**Comment by OldGazer** [comment]
Exactly which brand and model of receivers have you tired?

**Comment by WismyYao** [comment]
Could you share me your Ethos version  ?  EU or FCC ? Which receiver do you use ?

**Comment by shaun-3d** [comment]
I have tried x8r ‘ s6r ‘ s8r all will not Bind up

**Comment by bsongis-frsky** [comment]
@shaun-3d would you please tell us what is written in System / Information?
Which firmware did you flash on your receiver?

**Comment by OldGazer** [comment]
Just to tick all of the boxes, did you have the TD-IRSM in ACCST mode?

**Comment by shaun-3d** [comment]
The x29 radio has 1.0.3 firmware
And the x8r has v2.1.0

**Comment by shaun-3d** [comment]
![image](https://user-images.githubusercontent.com/83429798/116657075-b78abf00-a985-11eb-8fae-4970c4674325.jpg)

**Comment by shaun-3d** [comment]
![Uploading image.jpg…]()

**Comment by chubbrc** [comment]
I am having the same problem cand bind any receiver just put ethos on my horus x10s

**Comment by shaun-3d** [comment]
Update you receiver Firmware to 2.1 and fcc

**Comment by chubbrc** [comment]
I updated to 2.1 fcc and it still wont bind

**Comment by MIKE-DAILEY** [comment]
Please post an image of your INFO screen.  Press SYS and swipe over to INFO.

**Comment by chubbrc** [comment]
![16204236079688926161098105149691](https://user-images.githubusercontent.com/66145151/117511241-60738400-af5b-11eb-95e2-ce6c40ef9bdb.jpg)

**Comment by chubbrc** [comment]
The date is rong because my internal batt is dead

**Comment by chubbrc** [comment]
I just put the ethos on last night

**Comment by MIKE-DAILEY** [comment]
Your X10S internal ISRM RF module is not working. Is it a X10S Express or a X10S with the ISRM upgrade.

**Comment by MIKE-DAILEY** [comment]
What this update done?  https://www.frsky-rc.com/product/access-upgrade-module-kit-x10-x10s/ 

This is the ISRM https://www.horusrc.com/en/frsky-horus-x10-isrm-rf-module-new.html

**Comment by chubbrc** [comment]
No i got the radio new and put opentx on it. This is the first time i did anything with firmware

**Comment by chubbrc** [comment]
Thank you for all the help

**Comment by MIKE-DAILEY** [comment]
It is a X10S not a X10S Express, right?

**Comment by chubbrc** [comment]
Yes

**Comment by chubbrc** [comment]
With me putting ethos can i delete all the old stuff my sd card but leave the new ethos stuff on it and same with my internal sd???

**Comment by chubbrc** [comment]
Ok i put the new isrm in my radio and when i turn on my radio it states that i need to update my chip do i need to put opentx back on or how do i do it with ethos on my radio??

**Comment by MIKE-DAILEY** [comment]
Can you please post a picture of the screen.

**Comment by chubbrc** [comment]
![20210514_162153_HDR](https://user-images.githubusercontent.com/66145151/118324899-adfa6e80-b4d0-11eb-8149-4add19db5b9d.jpg)
![20210514_162136](https://user-images.githubusercontent.com/66145151/118324910-afc43200-b4d0-11eb-876a-887f5f12deae.jpg)
![20210514_162041](https://user-images.githubusercontent.com/66145151/118324922-b2268c00-b4d0-11eb-80c7-90360dac562d.jpg)

**Comment by MIKE-DAILEY** [comment]
OK the ISRM has old firmware.  Go to the Upgrade ISRM firmware download page here https://www.frsky-rc.com/access-upgrade-module-kit-x10-x10s/   Download the ISRM firmware 2.1.0. or the newest 1.1.6. and unzip the the file.  Copy the unzipped ISRM file to your SD card.  I have a firmware folder on my SD card where I put all my firmware I use for updating.  Start the system and using The ETHOS File Manager navigate to the ISRM firmware.  Click on it and select flash internal module.

**Comment by chubbrc** [comment]
Ok thank you

**Comment by bsongis-frsky** [comment]
Feel free to reopen if needed
