### ISSUE TITLE
1.1.2. How is the new sensor merging working?

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1540]
Relese Notes:
Sensors with the same AppID / PhysID (except receiver internal sensors) are now merged even if they come from a different receiver / band / module

Expectation after reading this: 
2 Neuron Sensors with the same ID will show:
Sum of the current (A), 
Sum of the consumption (mAh)
Lowest Voltage Values of all
Highest Temperature value of all.
Highest RPM.

Better:
By the way, for Neuron ESC it would be better to show only a merging of the consumption in mAh and the sum of the current in A. 
The other values should stay separate.

Result: 
2 Neurons with the same application ID and physical ID can not be identified in the telemetry. Same as in the past. Both must be different but than a merge is not possible.

**Comment by bsongis-frsky** [comment]
No, those sensors will be considered as the same. In your use case you need a different AppID and you need to use the calculated sensors.

**Comment by BernhardFe** [comment]
Calculated Sensors have no option to add several current sources or calculate then several consumptions. Only one source selection is possible and no multi source. As well the DIY sensor has no option for a sum for current or consumption from several sources as well. Or do I missed any function?
