### ISSUE TITLE
1.1.2- Improper Battery level indicator

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#1541]
The battery indicator on the top right corner has 4 bars when fully charged and when the voltage drops to even 7.5 volts it still has 4 bars which is a little misleading when show percentage is not used. Should be able to display right amount of bars based on the voltage. My suggestion is that for every 0.3 volt drop it should be 1 bar less displaying on the battery indicator.

**Comment by bsongis-frsky** [comment]
You can change the Min (0 bar) and the Max (4 bars) for the Voltage indicator, do you really need something else?

**Comment by kakashi2018** [comment]
that should be enough

**Comment by phaedra-tm** [comment]
The default settings for this indicator are way off.  You can have 4 bars indicated for a while, and shortly after you go to 3 bars, you get the low battery voltage warning.
It would make sense to change the defaults for Min and Max to something more reasonable.

**Comment by bsongis-frsky** [comment]
Which settings do you propose then?

**Comment by phaedra-tm** [comment]
Since it appears to be a 2S Lipo battery, I think the low battery warning at 7,2V is appropriate.
I set the display voltage range of my radio to 7,0V - 8,4V.  It should show 1 bar at 7,3V, before the low voltage warning kicks in at 7,2V.

**Comment by bsongis-frsky** [comment]
Then you are asking for numbers which are EXACTLY our defaults

![image](https://user-images.githubusercontent.com/50834778/160549964-f8ecae41-447a-4d7a-a021-3df74856339e.png)
