### ISSUE TITLE
X12S  freezes or goes into  emergency when deleting mixes 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#1543]
when deleting mixes in the mixer this it freezes on confirm delete or goes into  emergency  x12s have to pull the back off and bull the battery out

even new X12s with new SD card and i am getting this as well

this happens when Deleting files in MIXER its been doing it for some time in ethos on the X12S   1.0.14 to 1.1.2
when it freezes the receiver goes into fail safe   

this is one of the model bin i was working on with 1.1.1 

![20220322_123538](https://user
[model09.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8328124/model09.zip)

-images.githubusercontent.com/9161926/159579810-30875012-f82c-4fdb-a3eb-5fa8f89b96ec.jpg)
![20220322_144528](https://user-images.githubusercontent.com/9161926/159579904-9b05966a-b030-4d97-a5e8-5181ae5d873c.jpg)

![20220322_123538](https://user-images.githubusercontent.com/9161926/159582750-9b78f7fe-6671-41d5-ade2-03c8c69c54ed.jpg)

**Comment by MIKE-DAILEY** [comment]
Thanks for documenting.  Should be fixed in the just released 1.1.3.

**Comment by Cipta-de** [comment]
The same happened with X20S on 1.1.2
