### ISSUE TITLE
Implement Autotrim functionality

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#1545]
Is it an option to implement autotrim functionality?

For example: Due a maiden flight, you must do some trims. In this case I would like to trim down.
1. Turn on autotrim function, can be turned on by a logic switch.
2. Do the elevator stick more down and the trim will be automaticlly set.

After the flight, you can save the trim values from the auto trim.

**Comment by chenbevis** [comment]
This issue has been raised for a long time and it has not been resolved

**Comment by Farabos** [comment]
I've make a trim Mix enabled by pressing Fj switch, for the source of the trim command i've used 4 logic switch activated by the radio gyroscope , so pressing the Fj button and tilting the radio forward , backward, left side and right side i trim my plane in maiden flight without detach my thumbs from the sticks.
The only flaw is that the weight of the trims  are  not viewed in the trim  bargrafts on the main model screen.

**Comment by wmayvis** [comment]
Hi, can you share some screenprints?

**Comment by Farabos** [comment]
Ok, i'm out for work now, but as possible i'll share the screenprints.

**Comment by Farabos** [comment]
![DA81AA99-4591-4778-A735-E53A0E501E62](https://user-images.githubusercontent.com/104224710/164888907-7fad8ef3-cfa4-4756-888d-725def990bb4.jpeg)
![92E149F5-09C8-437F-8485-CC3B35E1CD34](https://user-images.githubusercontent.com/104224710/164888912-137664f2-2243-4a55-b355-52e6aee494f2.jpeg)
![34510DED-A212-47F9-904B-EEAAADE3A429](https://user-images.githubusercontent.com/104224710/164888915-704f75cf-ca9a-4ffc-9bfc-87f53b2086ec.jpeg)
![FE38B2EE-99BD-469A-BA55-117483B4B10D](https://user-images.githubusercontent.com/104224710/164888916-e27e9903-922e-49fd-8fe7-d8d18c812ef1.jpeg)
Hi Wmayvis, the Flip Flop is to make regular the cadence of Trim, i hope to be helpful..

**Comment by wmayvis** [comment]
Thanks for sharing. i've give it a try this afternoon and it work perfect.

**Comment by Farabos** [comment]
I'm glad I helped you 👍🏻

**Comment by mawzthefinn** [comment]
Closing this off as completed as a solution was provided and confirmed
