### ISSUE TITLE
Aileron differential does not work correctly when using 4 aileron servos

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#1546]
Using four aileron servos, two per wing. Differential attempts to move one servo per wing, rather than both, resulting in binding. 

setup - 
using ch 9 + 10 on left wing
using ch 11 + 12 on right wing

aileron differential moves channels 10 + 12 or 9 + 11. 

There doesn't seem to be a way to inform the mixer which channels to use out of the four when trying to add diff.

**Comment by bsongis-frsky** [comment]
You could change the order in your Ailerons mix channels, no?

**Comment by j-watkiss** [comment]
I will check this

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
