### ISSUE TITLE
1.1.3 LUA - cant read Lipo sensor cell count

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1547]
NumOfCells = widget.LipoSensor:stringValue(OPTION_CELL_COUNT)
print(NumOfCells)
prints "19.20V" on simulator intead of "6".

NumOfCells = widget.LipoSensor:stringValue()
print(NumOfCells)
still prints "19.20V" on simulator intead of "6".

this worked fine before on 1.1.0 and 1.1.1.

**Comment by bsongis-frsky** [comment]
Yes this was done on purpose and your code would need to be updated accordingly.
I think now it was not right and I have changed my mind for 1.1.4

**Comment by i3dm** [comment]
ok would be good if you could release .4 with this fix as it kills all existing lipo widgets which are very popular

**Comment by MiRe-CZ** [comment]
Will only the original sensor:value(OPTION_CELL_COUNT) valid in 1.1.4, or method, you suggested for 1.1.3 (source = system.getSource({name="LiPo", options=OPTION_CELL_COUNT})) will be valid as well?

I just updated my codes :-)

Related to #1544
