### ISSUE TITLE
Switch names in "checklists" don't use the custom names

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#1548]
Using 1.1.1 on X20S
I renamed some switches via the "Hardware" tile, to indicate their function in my setup.
When I go to the "Checklist" to define safe positions of switches, they are still referred to as SA, SB etc.  It is hard to keep track of the original switch names to configure these safe positions.
It would be handy and logical that the new names are used there too.

**Comment by bsongis-frsky** [comment]
Please update to latest release!
