### ISSUE TITLE
PNG PIC at Ethos Tandem 20x

### ISSUE THREAD

**Issue by wolverine202** [FrSkyRC/ETHOS-Feedback-Community#155]
Tandem x20 Ethos. Not all images can be used as model displays. Although all images are in the correct format 300x280 PNG.

**Comment by bsongis-frsky** [comment]
An example of unsupported bitmap please?

**Comment by wolverine202** [comment]
Here 2 dates I can't take as a model

Bertrand Songis @ FrSky ***@***.***> schrieb am Fr., 30. Apr.
2021, 08:10:

**Comment by wolverine202** [comment]
![Compass Chronos (4)](https://user-images.githubusercontent.com/83441184/116661613-0429c680-a995-11eb-828f-0a066c5896e5.png)

**Comment by wolverine202** [comment]
![DIATONE_ROMA_F5_fpv_drone](https://user-images.githubusercontent.com/83441184/116661653-1572d300-a995-11eb-813c-c9bdc439cfdd.png)

**Comment by wolverine202** [comment]
Doesn't anyone have a solution why not all PNG images are visible on the display?

**Comment by bsongis-frsky** [comment]
The 2 attached PNG are displayed OK now on X20

**Comment by wolverine202** [comment]
Ok I'll see if it works afterwards.Thank you

**Comment by wolverine202** [comment]
Why was it that some images are not displayed even though they were in the right size and converted to png

**Comment by wolverine202** [comment]
So the png images are not recognized
