### ISSUE TITLE
Telemetry connection between Frsky receiver and Kontronik Kolibri LV: no current data

### ISSUE THREAD

**Issue by BDebeuf** [FrSkyRC/ETHOS-Feedback-Community#1551]
Telemetry data between FRSKY receiver and Kontronik Kolibri LV shows the ESC temperature and consumption but not the real current.

**Comment by bsongis-frsky** [comment]
Which ID do they use? They have to follow the spec, or use dedicated DIY sensors IDs

**Comment by BDebeuf** [comment]
Hi,
ESC Temp: 0A 0B70
ESC Rpm: 0A 0B60
ESC Consumption: 0A 0B60

**Comment by Hobby4life** [comment]
How do you get temeletry from your kolibri to smartport?

**Comment by BDebeuf** [comment]
Communication port from the Kontronik  (chosen protocol: frsky protocol)  to Smartport of SR8
3 parameters are working, but the 'current 'parameter is not coming on the telemetry data.

**Comment by BernhardFe** [comment]
Here is the definition Bertrand mentioned: https://github.com/yaapu/FrskyTelemetryScript/wiki/FrSky-SPort-protocol-specs

**Comment by BDebeuf** [comment]
Update

Kontronik made an upgrade for the Kolibri (V3.0) end of March.  They changed the Frsky driver also.
Now, it's working perfect.
