### ISSUE TITLE
FW 1.1.3  chronos on throttle stick not working.

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1553]
Hello, on the new programmed models, the chronos do not work via the throttle stick commands. on the latest firmware version 1.1.3.
But with other older models, there are no problems.

**Comment by Mobidick1966** [comment]
My radio : X 20  eu.lbt  fw 1.1.3

**Comment by bsongis-frsky** [comment]
Duplicate of #1547

**Comment by Mobidick1966** [comment]
Still not working in 1.1.4  ...

**Comment by MIKE-DAILEY** [comment]
Working here too.  X20S FCC 1.1.4 using throttle absolute and count down.

**Comment by bsongis-frsky** [comment]
We need more info about this one, everything is working as expected too here.

**Comment by Mobidick1966** [comment]
Hello everyone.
Here I am in FW 1.2.1rc1, if I want the timer to work, I have to delete the model and reprogram it. On the older ones there are no problems.
In other words, it works.
Thank you ........

**Comment by mawzthefinn** [comment]
Are you still having issues on current firmware?
