### ISSUE TITLE
Flap wizard 

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1554]
Would like to see a flap wizard that’s does the following:

Asks for flap channel number.
Asks for switch selection.
Automatically sets a curve for 3 position switch at 0,50,100.
Sets speed of travel up and down at 2.0sec.

thanks

**Comment by mawzthefinn** [comment]
I like the idea of this, but the last two settings are correct for very few applications, particularly the throws which indicate improperly configured servos unless you are doing full-span ailerons.

plus elevator compensation should be in any Flaps wizard.

**Comment by ninodesposati** [comment]
Elevator Compensation is even better. Good idea!!

**Comment by mawzthefinn** [comment]
After some consideration, I don't think this will actually add much beyond switch selection, as the user can configure all of these items very simply in the Flaps mixer.

I would like Input selection in the Wizard though.
