### ISSUE TITLE
RB 10/20 Device configuration not available in 1.1.3 ?

### ISSUE THREAD

**Issue by fullmetalpacket** [FrSkyRC/ETHOS-Feedback-Community#1555]
Hi, sorry if this has been answered before, I couldn't find much information about it. After reading the manual I understand there should be scripts for RB 10/20 devices in Device Configuration but I can only see RB 30/40. I guess this is what I need to use for configuring my RB20 unit? Thanks in advance.

**Comment by enzo-molinari** [comment]
Hi fullmetallpacket

Nothing can be configured on the RB-10 and RB-20. They have no stabilized power supply and no stability function. Therefore there is no selection under "Device Configuration". Only the telemetry values can be set and this can be done under "Telemetry".

Greetings Enzo

**Comment by fullmetalpacket** [comment]
Awesome, thanks Enzo!
