### ISSUE TITLE
Feature request: Read out the current time

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1556]
It would be great if in the **Play Value** settings there was an option to read the current time. I guess the best category for it would be **System Value**.

**Comment by bsongis-frsky** [comment]
Understood, you need to be on time for dinner. We will add it.

**Comment by danydu62** [comment]
Il serait vraiment bien de pouvoir écouter l'heure qu'il est actuellement en appuyant sur un bouton plutôt que de quitter le planeur des yeux pour regarder sa montre ou la radio !
