### ISSUE TITLE
Low Cell voltage warning

### ISSUE THREAD

**Issue by jeffgrain** [FrSkyRC/ETHOS-Feedback-Community#1557]
X20S up to firmware version 1.0.9    I was able to read from the flvss independent cell voltages and set warnings. After 1.0.9 , anything that had been previously configured continued to work.. but unable to configure new ones. with the most recent firmware 1.1.3 I could configure a widget that would show me cell voltages , but unable to set warnings of a low cell.. in recent there has been a LUA that will read cell voltages and display a pretty picture.. but since I do student training,, it is unwise to take your eyes of the plane and I relied on that verbal warning for when the battery was getting close. as well it is a safety thing for me since a cell can drop voltage suddenly , and I would like to know that before it damages something or becomes a problem..

Since it seems that the cell voltages can be read.. could you put this feature back in , that was available in 1.0.9 since I have just found out that the wired training had a bug in version 1.0.9 and since corrected.. but lost the cell voltage warning..

**Comment by bsongis-frsky** [comment]
How was your warning configured in 1.0.9? I see no reason it's not possible in 1.1.x, but perhaps I am missing something?

**Comment by bsongis-frsky** [comment]
Check for source options. It should be explained in the Manual. Otherwise please ask for help on forums, this repo is dedicated to issues, not user questions.

**Comment by jeffgrain** [comment]
I was just going to retract my posts.. as I finally figured out the " long press enter " on the menu's .. unfortunately I can not now.. but it also does not seem to be documented either... and I have searched the forums..

regards jeff
