### ISSUE TITLE
Emergency Mode because of faulty telemetry data

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#1558]
Transmitter: Horus X12s
Firmware: 1.1.1

Last week I optimized the programming of my plane. I added an openXsensor (used several of them) with Vario and GPS.
Everything went well and was working.
Next step was to add the calculated "distance of flight" sensor where you can chosse the GPS sensor and the height sensor. Worked like a charm and I powered down the plane and transmitter.

At the weekend I went to the flying field, started the transmitter and powered up the plane. Got the peeps from the ESC/Motor and the moment the receiver was connected the transmitter went to emergency mode.

Tried it several times, the outcome was exactly the same. Just powering up the transmitter there was no emergency mode. The emergency mode kicked in as soon as i powered up the receiver.

I had a guess that the problem was caused by the calculated sensor, because the GPS signal is not available right away, but the height signal from the vario is. So there should be an arror when Ethos tries to calculate the sensor value.

So the solution was to power everything down, power up the transmitter, erase all sensors in the telementry menu, power up the receiver and let Ethos detect new sensors.

=> worked, no emergency mode anymore

So my gues is that the emergency mode was caused because the calculated sensor didi not have all sensor signals to calculate its value and so the calculation crashes and the transmitter goes to emergency mode.

**Comment by bsongis-frsky** [comment]
Is it the same with release 1.1.4?
I just checked everything and it seems to me that we are protected against this problem, I want to be sure that it is not an old issue
Thanks for your help at fighting this one!

**Comment by bsongis-frsky** [comment]
I think this bug has been fixed on 15th of September, 2021

**Comment by keiner0815** [comment]
Fortunately I didn't update just yet and tried to reproduce the problem again. 
But I couldn't do so.

I created the "distance" sensor again and used GPS sensor  as "GPS" and vario height sensor as "height" and I could't get the system to Mergency mode

So I tried everything I could think of to reproduce the situation as good as possible

- a also created the calculated "trip" sensor
- waited a minute so the GPS sensor needed more time to get the position
- powerd down the transmitter first so that old values are held till shutdown in the transmitter
- poweres transmitter and receiver simultaneously 
- added "trip" to the telemetry page 
- added "distance" to telemetry page

Don't know if I should be relieved or worried now 🙈 
So on one hand I don't have the (on the flying field repeatable!) error anymore on the other hand I don't know what else could have caused my transmitter to go into emergency mode

**Comment by bsongis-frsky** [comment]
I wonder if openXvario doesn't send something which is not correctly recognized by the radio. Perhaps exactly at the moment your GPS finds the satellites?

**Comment by keiner0815** [comment]
I let openXsensor send some GPS debug information as Accel sensors.
So it would make sense that one of those signals is sent at the same moment the GPS gets a connection to the satellites and produces an error. 
But what corruption of the sensor signal could have the effect to get the transmitter into emergency mode?

And I don't know why I can't repeat it at home when I get GPS signal there.
Maybe I will deactivate the debug signals in the future, just in case...

Or if anyone has an idea what i can try to get the error again, I will happily test that.

**Comment by bsongis-frsky** [comment]
Instead it would help if you could add more messages to reach saturation and see how it behaves. I have just added some more sanitization for 1.2.2-RC2 but I have not found anything in this area which could make the radio go to Emergency Mode

**Comment by keiner0815** [comment]
I could activate the internal vario of the G-RX8 receiver that would give me at least two more signals.

Maybe it was something that is only indirectly related to the telemetry signals.
For example showing values on the telemetry page. But the error did occur at the start screen after startup, nur while I was at the telemetry screen.
Or maybe the reset switch for one of the telemetry signals.

**Comment by keiner0815** [comment]
I tried it again with enabled vario of the G-RX8 receiver, but again I didn't get the transmitter into emergency mode

**Comment by keiner0815** [comment]
I think this issue can be closed, as I could not reproduce the error and I am on a never version of Ethos now
