### ISSUE TITLE
Feature request: Txt file reader

### ISSUE THREAD

**Issue by fullmetalpacket** [FrSkyRC/ETHOS-Feedback-Community#1559]
Hi, I think having the possibility to read .txt files within the File Manager would be great. Especially when organizing firmwares for many receivers and sensors. I like to keep the readme.txt file that comes with each firmwares so we can get more information about it directly in the radio. Thanks and great work with this OS, I really like it!!

**Comment by bsongis-frsky** [comment]
Same than #1571

**Comment by fullmetalpacket** [comment]
Still a good idea I think 😎

**Comment by mawzthefinn** [comment]
This is already in the nightlies for 1.5.0

Closing as completed
