### ISSUE TITLE
RB30/40 Config of Vout 2 is wrong for lastest firmware

### ISSUE THREAD

**Issue by DaySpeed955i** [FrSkyRC/ETHOS-Feedback-Community#156]
ETHOS V1.0.4

For RB30/40 in Base Config should not have Vout 2 option, in LUA V1.02 for firmware 20210201, it is replaced by:
"Cur Calibr PW(78)", VALUE, 0xB3, nil, 50, 84},

Thanks

**Comment by DaySpeed955i** [comment]
Is fixed in 1.0.5

Thanks!

**Comment by bsongis-frsky** [comment]
One less :)
