### ISSUE TITLE
Ethos Suite - Translation

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#1562]
How can we provide translation to ethos software? I saw .pak files with localisation but how to edit?
@bsongis @Adelaxie @WismyYao @MIKE-DAILEY

**Comment by mgsanna** [comment]
I'm already the italian translator of Ethos software

**Comment by bsongis-frsky** [comment]
We are still not ready with the Suite translations. We only have 3 translated strings in 1.2.1
