### ISSUE TITLE
Request: Simulators for MacOs

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#1564]
Is there a possibility to make the simulators that it will running under MacOs?

**Comment by ZeekWorld** [comment]
Yes please.

**Comment by wmayvis** [comment]
Is this feature request in process?

**Comment by BernhardFe** [comment]
Please, when do you plan to offer the Sim for MacOS too?

**Comment by wmayvis** [comment]
What's the current status of this request?

**Comment by BernhardFe** [comment]
Hi , I don't understand why the topic is closed... Please reopen.

**Comment by wmayvis** [comment]
Why is it closed?
