### ISSUE TITLE
1.2.0 Sim scrolling in the SXR menu not possible.

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1565]
The problem occurs in the X20 and X10 Sim.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/161010960-d5241087-6bc9-4679-88c1-cfa391dbb70f.png)

**Comment by EngelMT** [comment]
For me it is not possible to scroll down. For excample to check "self-test". It does not work with the scroll wheel of the mouse, not with the arrow keys, not in combination with scroll wheel and Ctrl. etc.. You can't move the red line with the mouse either. Or what am I doing wrong. This seems to be the same problem in other config menus.

**Comment by drummaker** [comment]
Solved in latest access receiver firmware

**Comment by EngelMT** [comment]
Yes, you are right. But do not working in the latest Sim.

**Comment by mawzthefinn** [comment]
Yes, confirmed even latest sim has this issue

**Comment by bsongis-frsky** [comment]
I think I have found a way to automatically solve all those scrolling issues when no field can accept the focus (without adding any code in each screen just for that case). It still needs some testing to be sure I have not broken anything.
