### ISSUE TITLE
ETHOS Suite Feature Request - SD Backup

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1567]
It make updating safer, this would be a configuration option which would place a copy of the radio SD card into a named & dated subfolder of a specified folder on the computer prior to updating the radio.

It should have a UI button as well, so users can easily backup their radio.

**Comment by Hobby4life** [comment]
I agree. Backupping is one of the most important things before upgrading.

**Comment by pstasek** [comment]
I'd like to suggest an automatic backup of bin files when flashing the Ethos version. A convenient location might be a backup folder on SD card and inside would be a dated structure. That way, nobody would forget to backup their crucial files for a potential downgrade for any reason.

**Comment by BernhardFe** [comment]
I do the backup manually before every update. I also would appreciate an automatic backup when I press the update button  and a button for manually backup in between. Please let me define the path (for win and mac) in the suite. Than I can decide on the folder on the SD card or on the pc/mac.

**Comment by BernhardFe** [comment]
Any plan for an integration of a backup?

**Comment by mawzthefinn** [comment]
Model folder backups are present as of 1.4.0

I'd still like to see a full SD backup option as well

**Comment by mawzthefinn** [comment]
Complete backup implemented in 1.4.3
