### ISSUE TITLE
Simulator support for 32-bit

### ISSUE THREAD

**Issue by andika207** [FrSkyRC/ETHOS-Feedback-Community#157]
I want to know why did you drop the support for Windows 32-bit systems ?

The 1.0.4 simulator does no longer run so you are actually scaring away many future customers.

**Comment by Speeedy-U** [comment]
Yes, please make two versions 32-bit & 64-bit. P.S. On may RC Laptop I use 32-bit. Thank you !

**Comment by timmybeetle** [comment]
Well, I ordered me this xmtr and now I installed the simulator and it doesn't work on my computer because its 32 bit. That's  a disappointment sadly. So make it also 32 bit.

**Comment by andika207** [comment]
I have downloaded the latest simulator release but it still doesn't support 32-bit OS
why did you self assign this issue @Nicholas-Luoyi ???
