### ISSUE TITLE
Model File Compatibility Issue

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#1570]
X20S Ethos Version 1.1.1
X10S Ethos Version 1.1.1

In Ethos version 1.1.0 I can create a model file on my X20S and copy it to my X10S Express (with the same version) and the file opens correctly on the X10S.  Starting with version 1.1.1 thru 1.1.4, when this procedure is done I get an “Invalid Data” error. 

However, copying a model file from the X10S to the S20S works correctly. I have repeated this several times with the same results.

![111](https://user-images.githubusercontent.com/81670152/161095443-4a86553a-fa41-4e55-8e3d-34982b6dbaf1.jpg)

**Comment by bsongis-frsky** [comment]
Please post your model here!

**Comment by df7320** [comment]
[model04.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8391634/model04.txt)

**Comment by wfield0455** [comment]
I have this issue too. Model files copied from X20S running V1.2.1 RC1 to X10S Express also running V1.2.1 RC1 can't be read and show invalid data pop up.
model01.txt

**Comment by wfield0455** [comment]
model01.txt

**Comment by bsongis-frsky** [comment]
It will be fixed in 1.2.2
