### ISSUE TITLE
Feature request: Model notes or comments

### ISSUE THREAD

**Issue by fullmetalpacket** [FrSkyRC/ETHOS-Feedback-Community#1571]
I think it would be useful to have a section when editing a model where you can type any comments or notes about this model. I would write the oil/gas mix ratio that this plane requires and that I always forget, or how many gas tank it drank so you can keep track of break in process, or anything else that is worth noting like flight time logs or CoG location. Thanks!

**Comment by Planetester** [comment]
Would be helpful, with 30 models, having a small notes screen knowing which switches control rates, timers, flaps, spoilers and the switch positions
