### ISSUE TITLE
Ethos Suite linux

### ISSUE THREAD

**Issue by Jamest95max** [FrSkyRC/ETHOS-Feedback-Community#1576]
Hi is there any possibility for someone to compile Ethos Suite Linux version as there has been for MacOS, so far it can not be run on WineHQ or PlayOnLinux which also uses wine and other components but with next to zero success, it will install but after fully installing it will refuse to start, errors are as follows although i am not sure it will help

[04/02/22 12:27:38] - Running wine- Ethos Suite.exe (Working directory : /home/james/.PlayOnLinux/wineprefix/ethosSUITE/drive_c/Program Files (x86)/FrSky/Ethos Suite)
0058:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

[87:0402/122739.225:ERROR:network_change_notifier_win.cc(226)] WSALookupServiceBegin failed with: 0
[87:0402/122741.545:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=49
[87:0402/122742.159:ERROR:platform_font_skia.cc(344)] Could not find any font: Tahoma, sans. Falling back to the default
[87:0402/122742.159:ERROR:crashpad_client_win.cc(814)] not connected

any Help would and will be much appreciated
Thanks James.

**Comment by Jamest95max** [comment]
is linux possible as i notice macOS was asked and happened overnight is linux harder or impossible?
still trying to run in emulators but no luck so far

**Comment by Jo-le-Papy** [comment]
Hi,
I would also like a linux .deb or .rpm version (ubuntu, mint, debian) it's difficult to find a Window$ computer each time.
Wine version not work.
Best regards,
Jo le Papy

**Comment by Jo-le-Papy** [comment]
So I conclude that it is not for soon... I'm crying

**Comment by Target0815** [comment]
> So I conclude that it is not for soon... I'm crying

The question about a Linux version has been asked several times. In #1726 Bertrand asked for which Linux ... If there are no reasonable answers with which one can plan, FrSky will probably not for 2-4% of the users for which this might come into question, also support several Linux distributions.

**Comment by oilytin** [comment]
Linux mint user here🙏

**Comment by victorllarena** [comment]
seria brutal no tener que depender de windows

**Comment by Jo-le-Papy** [comment]
> > So I conclude that it is not for soon... I'm crying
> 
> The question about a Linux version has been asked several times. In #1726 Bertrand asked for which Linux ... If there are no reasonable answers with which one can plan, FrSky will probably not for 2-4% of the users for which this might come into question, also support several Linux distributions.

If it works on linux it works on all or almost, a .deb package for Ubuntu is a good solution. I will like a lot ; and I am not alone ; be able to use this

**Comment by MrD-RC** [comment]
+2 for Linux here. Using Fedora.

**Comment by ZS-Man** [comment]
+1 for Linux  - Debian, Ubuntu or any universal AppImage . In a pinch a WineHQ friendly version would probably suffice, like ETHOS simulator.

**Comment by fBruckm** [comment]
+1 for Linux - AppImage or flatpak would be the best solution as these are distibution agnostic

**Comment by bsongis-frsky** [comment]
Added to #3440

**Comment by hwa59** [comment]
hi
is in the meantime a linux-version available ?
I would prefer an Appimage
or perhaps provide the source code so that the linux-user can compile it themself

**Comment by petegee** [comment]
would LOVE an debian based version (Pop_OS)

**Comment by etymotic** [comment]
This should be re-opened as there still isn't an Ethos Suite for Linux available.

**Comment by elliopitas** [comment]
I am using arch and fedora.
I have the tandem x20R
