### ISSUE TITLE
Landing Gear Sequencer?

### ISSUE THREAD

**Issue by Jamest95max** [FrSkyRC/ETHOS-Feedback-Community#1577]
Please add a landing gear and door sequencer to ease the set up of scale aircraft.
this has already been raised before but seems to have been put on enhancment and left origional post last report july last year

is this possible?
love all the work so far absolutely the best system & transmitter in my eyes
Thanks James

**Comment by hrenz** [comment]
there is an nice example for a gear/doorsequencer at RCG

**Comment by mmasch** [comment]
https://www.rcgroups.com/forums/showpost.php?p=46708519&postcount=3621

**Comment by Jamest95max** [comment]
Thankyou for the replies and yes seen the post a while back and after messing about i managed to do the same but i still feel to make this more inclusive to newbies or just people that love our radio but do not want to get into too much programming , for instance the sequencer on dx18 (which is the only thing i like) it has a programme option for door and gear timings, "the hardest part" then if you wish you can customise further

i will give an example of what i wish to do for myself and maybe there are easier options out there or something i missed
takeoff mode
full lights, high rates, 1/3 flaps,
flying mode
gear up, nav lights only, flaps retract, rates
landing mode
Full flaps, gear down, full light system, mid rates etc...etc..
now all these can be do seperately but not done and then programmed to work one after another say in logic switching

**Comment by mawzthefinn** [comment]
I think this would be a good opportunity for a Lua Sequencer. I personally think that adding too many canned menus just adds complexity vs the current situation, and an optional Lua script for things like this makes more sense.

That said, the described setup is exactly what Flight Modes are for. A sequencer is best used to handle the timing of the door and gear activation. Tying rates, channel status and position and such together is what Flight Modes do best.

**Comment by Jamest95max** [comment]
Hi thankyou for your replies, yes Lua Sequencer script pre-template would be great atleast until people like myself learn how to fully use LUA , at the moment it would be great if there was a lua template for a sequencer, and enen if there is say another door or retract, part of the script can be copied to add more, are there anyone out there willing to put this script together? would be very helpful to us scale flyers
thanks James.

**Comment by mawzthefinn** [comment]
I'm actually going to poke at one this week, starting with a channel sweeper script (ie a script which will run a channel from -100 to 100 over set period of time on switch activation, then the reverse on de-activation). That's the core component for a Sequencer on ETHOS, everything else is just UI for setup (curves, assigning channels, etc)

**Comment by Jamest95max** [comment]
that would be a great help if you don't mind sharing the said script when you're done please

**Comment by mawzthefinn** [comment]
I most certainly will share it if I'm able to get it up and running.

It'll be a good use of my Vacation this week since the weather gods seem to be saying there will be no flying.

**Comment by mawzthefinn** [comment]
Turns out you don't need a script, just a Free Mix to sweep the channel now that Slow is available.

That said, there is a previous request for a Sequencer, #657 so I'm closing this issue off as a duplicate and the older request will be tracked.
