### ISSUE TITLE
ETHOS 1.1.4 Stabilize Gain no longer adjustable for S6R ACCST

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1578]
With version 1.1.4 it is no longer possible to set the gains in the SXR menu for SXR ACCST receivers.

![1 1 4](https://user-images.githubusercontent.com/85410070/161387444-628ecb26-5a3d-4346-aaf2-1c10a4ecc90d.jpeg)

With version 1.1.0 it works without problems.

![1 1 0](https://user-images.githubusercontent.com/85410070/161387520-aa3cc933-3497-49cb-9642-7d43b9c1d6ca.jpeg)

**Comment by mawzthefinn** [comment]
This was affecting SR series as well, if those receivers weren't on 2.1.10 firmware. 

It looks like the change to support Self-Check in the SxR menu broke receivers running firmware without support for Self-Check in the SxR menu (ie all SxR receivers and SR's on 2.1.9 or earlier)

**Comment by Hermann62** [comment]
When will the problem be fixed?
Does anybody know that?

**Comment by tysonfromcanada** [comment]
Fixed in 1.2.11 for me
