### ISSUE TITLE
1.0.4 Hum after activating 868 MHz

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#158]
After switch the internal 868 MHz activ I hear a loud hum. If I switched inactiv and activ again this hum is gone. But after I switched off the radio and on again the hum is back. I can only stop this hum by switch inactiv and activ again.

**Comment by WismyYao** [comment]
Sorry, I didn't understand the question you said. Could you provide us with more information?  A video?

**Comment by EngelMT** [comment]
Please do the following

- create a new model
- go to RF System menu
- Click to internal modul
- Click State ON
- Click 868 MHz ON

Now you will hear a loud hum out off the speaker. If you switch 868 MHz off and on again the hum is gone. If you switch off and on the radio again you hear the hum again.

**Comment by EngelMT** [comment]
I am not sure. But the problem could still be related to the error that 868 MHz is set to 10mW on a new model. Because if I then set it to 25mW, the hum also seems to be gone.

**Comment by bsongis-frsky** [comment]
Please double check with 1.0.5, as we changed something for the default power value

**Comment by EngelMT** [comment]
Seems to be fixed with 1.0.5.
