### ISSUE TITLE
throttle cut minimum range

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1580]
i think this is in all ethos versions. i tested on 1.1.1.

throttle cut function in throttle mixer has a minimum range of -100%.
on a glow or gas engine, you set your outputs so that at minimum stick and center trim the engine will be running at idle.

then when you set -100% on the throttle cut, the engine remains at idle and unable to cut. seems like it sends a -100% mixer when it should really be -100% (or allow even a wider range) output.

in general, throttle cut in internal combustion engines, if imposed on the mixer, should probably allow up to -150%.

**Comment by i3dm** [comment]
I understand this could be solved by setting up throttle linkage with "throttle low position trim".
if this is the case i think the above should be default ON / enabling throttle cut to work properly by default.

**Comment by bsongis-frsky** [comment]
The current settings seem perfect for electric engines, no?

**Comment by i3dm** [comment]
> The current settings seem perfect for electric engines, no?

yes but quite confusing / not intuitive for nitro.

**Comment by i3dm** [comment]
using low position trim solves the issue, but again - not very intuitive as you can enable cut without low position trim making it essentially useless. 
maybe add a warning message on the screen when enabling throttle cut that low position trim shall be used and bottom throttle range adjusted accordingly?

**Comment by mawzthefinn** [comment]
Just ran across this.

Throttle cut works fine with gas/glow engines. The trick is how you approach idle. 

Set -100 in the mixer as full cut (use the output endpoints to cover  the physical setup), then when you set low-position trim, your default point  is around -85 and can readily be adjusted for desired idle. This gives you much better control over idle and working throttle cut on glow.

It is however different from how other OS’s approach this (Spektrum especially)
