### ISSUE TITLE
Gas Suite Reset Fuel Sensors

### ISSUE THREAD

**Issue by oleyur** [FrSkyRC/ETHOS-Feedback-Community#1582]
There is no possibility to reset fuel volume and fuel tank % sensor values manually in "Gas suite" device.

**Comment by bsongis-frsky** [comment]
Why don't you reset it in Model / Telemetry? Or using the Widget contextual menu?

![image](https://user-images.githubusercontent.com/50834778/161500506-7434de3b-c1da-4bbc-872b-57f0d36ed674.png)

**Comment by oleyur** [comment]
It does not works. Value does not reset with existing methods.

**Comment by oleyur** [comment]
see details:

https://frsky-forum.cz/viewtopic.php?f=25&t=427

**Comment by oleyur** [comment]
Do you have any success with this?

**Comment by bsongis-frsky** [comment]
The value is sent by the sensor, even if you reset it it will be sent again. I am not sure that I understand what you need!
