### ISSUE TITLE
Feature request: start/stop for line chart widget

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#1584]
The line chart widget is limited in how much data can be visualized in one window of time.  If I want to review telemetry data after a flight, by the time I get to the pits, the data of interest is already scrolled out of sight.
It would be very handy to have the possibility to start and stop the plotting of data through a switch, so that the line chart can be "frozen" after a flight.

**Comment by pstasek** [comment]
I second that! It could be hooked to the "Save logs to SD" special function for easy setup.

**Comment by mawzthefinn** [comment]
Yes, this would be a great improvement to the Line Chart.

**Comment by bsongis-frsky** [comment]
Ready in next nightlies
