### ISSUE TITLE
Feature request. Touch screen for Horus X12S

### ISSUE THREAD

**Issue by KevinFairgrieve** [FrSkyRC/ETHOS-Feedback-Community#1586]
Having converted an X12S to touch screen, it would be great if ETHOS could be run on it.

Probably a pie in the sky request but there it is.

https://www.youtube.com/watch?v=hiQ0qBhCax8

**Comment by enzo-molinari** [comment]
I am also in the process of upgrading my X12S to touchscreen, I also would be find great if ETHOS supported touchscreen function.

**Comment by Adelaxie** [comment]
Interesting mod！ It needs excellent DIY skills.
ETHOS supports the touchscreen function on products which has the touch screen.

**Comment by KevinFairgrieve** [comment]
Thank you, I shall try to convert this from Edge to ETHOS over the next week or so.

**Comment by bsongis-frsky** [comment]
The current X12S firmware doesn't support the touch screen right now! 
I think it's just a setting to change in project settings, but for sure it would need another firmware build!

**Comment by KevinFairgrieve** [comment]
> The current X12S firmware doesn't support the touch screen right now! I think it's just a setting to change in project settings, but for sure it would need another firmware build!

Thank you for that, saved me a whole lot of grief. Please bear it in mind for a future build.

**Comment by Lefish63** [comment]
Nearly a year since this was last commented on. 

There seems to be more of us doing the touch screen mod on the X12s and would prefer to use Ethos.
Here's keeping my fingers crossed..

**Comment by Lefish63** [comment]
Just been re visiting this
Is there any movement on touch for the Horus series at all ?

Due to a  hardware failure on a rotary encoder on my X12s that caused the RF to turn itself off while airbourne and cause a potential disastrious situation, touch would be a good thing to reduce wear on the rotary encoder extending the life of the radio, and win over more people to Ethos ?
