### ISSUE TITLE
SXR Script Problems with saving offset values

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1588]
The following problem occurs. Offset values (-1, -2, -3) are not saved but reset by one value after pressing the Enter key. See the attached video.

The problem does not seem to occur with the X10 ISRM and X10 Express, but only with the X20/X20S. I tested today with ETHOS V1.1.3, V1.1.4 and V1.2.1 RC1 and a SR8 Pro with firmware V2.1.1.0. The problem occurs with these versions.

https://user-images.githubusercontent.com/16795828/162152928-68efa6d4-6b2d-4832-b8ae-58413790465d.mp4

**Comment by drummaker** [comment]
Resolved in 1.2

**Comment by EngelMT** [comment]
Not solved with 1.2.1 RC1.

**Comment by drummaker** [comment]
Right I was mistaken 
I agree no values of  I think  -2 or -3 on any offset.  You set and then it just turn into a different value

**Comment by teamdavey** [comment]
This issue (or one just like it) has been around since before ACCESS and ETHOS - I had always assumed it was a receiver related issue as I do not see it on all my receivers. 

(Using Taranis both (9D + and now 2019)

**Comment by Adelaxie** [comment]
ISRM-2.2.2 fixed this one
