### ISSUE TITLE
Invalid telemetry on TD-R10 and TD-MX with BoomaRC ARXL and RDT on Ethos 1.1.4

### ISSUE THREAD

**Issue by phazeman** [FrSkyRC/ETHOS-Feedback-Community#1589]
**System:** BoomaRC ARXL
**Receivers:** TD-R10 (1.0.7) + TD-MX (1.0.7)
**TX:** FrSky X20S with Ethos 1.1.4, TD-ISRM 2.2.1
**Aditional Telemetry devices:** Zavionix RDT
**Connections:** TD-R10 to R1, TD-MX to R2, Telemetry to TD-R10 S.Port

When discovering sensors in the telemetry screen, only the standard sensors are working properly (like 2.4 RSSI, 900 RSII and so on). Some sensors from ARXL are discovered properly (RBOX A1, A2, V1, V2) and some are not discovered (RBOX C1, C2). RDT sensors are discovered partially as well. There are additional wrong sensors discovered that don't have any sense to me like Air Speed and GPS (there is no such sensor installed). After the sensor discovery finishes it's incorrect work there is sensor lost alarm about every second and all the sensors except the standard stop working for about 5-7 seconds, then come back for 2-3 seconds and so on.
Tried to disable telemetry to TD-MX - didn't help. Connecting the telemetry to TD-MX S.Port instead of TD-R10 - didn't help.
Here is a short video: https://youtube.com/shorts/BWyfTDuoyvY

When connected R8 Pro and R9SX instead of TD-R10 and TD-MX - everything works perfectly good without any problems at all.

**Comment by Jetman1** [comment]
I have this problem with TD-R10 in combination with RB30 (actual FW) and x20s running on FW 1.1.4. The internal sensors of the TD-R10 work flawlessly but after discovery of the sensors from the RB30 I got every few seconds the warning "sensor lost" and the values flicker red for a really short time. The default 5 seconds delay of the sensor warning does not affect the warnings at all although the red flickering lasts only max. 0.5 seconds. The values seem to be right, but I have to check it again.

**Comment by j-watkiss** [comment]
Did you update TD Module to 2.2.1?
There is a fix for telemetry issues in TD mode

**Comment by phazeman** [comment]
> Did you update TD Module to 2.2.1? There is a fix for telemetry issues in TD mode

No i didn't see that update. will upgrade and retest.

**Comment by j-watkiss** [comment]
Unsure if it will help your issue but its worth a shot

**Comment by phazeman** [comment]
Tested with a new firmware - problem still exists

**Comment by Jetman1** [comment]
I am running TD RF FW 2.2.1 and I have the telemetry problem on RB30 with sensor lost warnings.

**Comment by phazeman** [comment]
issue opened 21 days ago and still no response from the dev....

**Comment by mawzthefinn** [comment]
Sensor lost warnings with Zavionix RDT in the mix have been confirmed as the ADC4 sensor going out of valid range, see #2052 for details.

There were also issues around S.Port timing and the TD receivers, they are more particular about timing being in-spec than the older receivers. I believe BoomaRC has addressed those issues with firmware.

**Comment by Adelaxie** [comment]
We have strongly advised at Ethos page and dev union page that third parties should contact FrSky to obtain the relevant data protocol file authorization and at least provide their product test system compatibility(the system may not work reliably without the detailed protocol knowledge). What a pity, many systems release products without ever contacting us, and we would have to spend much time on the issues and advise such users to contact the corresponding manufacturer for help.

**Comment by bsongis-frsky** [comment]
I am not aware of any issues left in this area. 
As written in #2052 The RDT Sensor has some issues and doesn't fullfill the specification.
