### ISSUE TITLE
After binding S6R servos oscillate permanently

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#159]
After binding the S6R receiver, the servos oscillate permanently , see video
Ethos 1.0.4, X10S, Receiver Firmware ACCST FCC 2.1.0

https://drive.google.com/file/d/1dyfSsd66u4lAJM2y7cblNyikcqLLi7Kt/view?usp=sharing

**Comment by aalain8** [comment]
Horus X10 + ISRM  Ethos V1.0.4 (la dernière) récepteur S6R 2.1.0
De mon côté pas de problème.

**Comment by Skippydi** [comment]
Il s'est également produit dans la version 1.0.3 et peut être reproduit

**Comment by janekx** [comment]
Dont you have the test mix in mixes? if so delete it. 
Show what says outputs if the movements comes from radio.

**Comment by DaySpeed955i** [comment]
Tested with X12S on V1.0.4 and S8R v2.1.0FCC, work normally.

**Comment by Skippydi** [comment]
Ok, i've deleted completed model and create a new one. Now it works correctly. I will watch it.
