### ISSUE TITLE
Strange. Behavior registering and binding

### ISSUE THREAD

**Issue by drummaker** [FrSkyRC/ETHOS-Feedback-Community#1590]
Today this happened twice ethos 1.2.  Receiver firmware  2.1.10

I nearly always use redundant receivers, and if both are access then the only way i know to verify the redundancy is working is to unbind the master receiver.  
This is a little.confusing.  I generally reset the receiver.  
Today after some messing around I did reset receiver the green light didn't go out.  Also the receiver name went away, so it looked like I had disabled it, but it still worked.   I unplugged the 2nd receiver but the main was indeed still working.   
At some point neither receiver showed up as bound but both had green lights and were working

Any attempt to rebind failed, and registration failed .   I wound creating a new model to fix.   This eventually happened again, this time I changed the master receiver out, and it worked.   I suspect the problem to be in receiver fw 2.1.10

**Comment by KAID-YANG** [comment]
Did you update TD Module to 2.2.1?

**Comment by drummaker** [comment]
> Did you update TD Module to 2.2.1?

Yes, but I can't say for sure at what  point I did so.     I actually don't consider this

**Comment by KAID-YANG** [comment]
We did not reproduce this problem, which two receivers are you using?

**Comment by drummaker** [comment]
They are sr8

Sent from the all new AOL app for Android 
 
  On Sun, Apr 10, 2022 at 11:43 PM, ***@***.***> wrote:   


We did not reproduce this problem, which two receivers are you using?

**Comment by bsongis-frsky** [comment]
Please update your module and RX firmware to be sure. We cannot reproduce the issue.
