### ISSUE TITLE
Problems with x20s, RB30 and TD-R10 RX with Ethos FW 1.1......

### ISSUE THREAD

**Issue by Jetman1** [FrSkyRC/ETHOS-Feedback-Community#1591]
I have some problems with the above mentioned combination. TD RF FW 2.2.1, RB30 actual FW, TD-R10 FW 1.0.7

1. Sensor lost warnings every few seconds with different versions of 1.1... FW. Sensor warning delay of 5 sec does not have any effect although the values only flicker red for a part of a second. Occurs only with sensors from the RB30. The RX Sensors and my swiwin turbine sensors work correct.

2. RB30 setup via lua script does not work with FW 1.1.4. Self test and gain values are gray and not functional.

3. With an Archer R8 the problems do not appear. I hope someone can solve the problem.

**Comment by chenbevis** [comment]
RB30/RB40Firmware update is required, but no new firmware is available yet, Waiting for frsky to process

**Comment by Jetman1** [comment]
Thank you for the info but I am afraid it will take a long time because at the field of telemetry frsky needs often a lot of time to solve problems. Especially when major changes happen, for example Accst to Access, or Access to TD and so on.

**Comment by DaySpeed955i** [comment]
Did you solve your problem with last version of RB-30?

2022-04-21 | 20220412 
1. Supports two different modes (12CH and LUA) to enter the self-check mode.
2. Compatible with TANDEM receivers.
3. Fix the issue that CH17 to CH24 would not work under stabilization mode.

**Comment by Jetman1** [comment]
No, sorry, I have to check next week.

**Comment by mawzthefinn** [comment]
Did the update solve the issue?
