### ISSUE TITLE
False Flybarless Channels Helicopter

### ISSUE THREAD

**Issue by Sliderlucky** [FrSkyRC/ETHOS-Feedback-Community#1593]
Hi,
I have a question about the default channel assignment for programming a helicopter with a flybarless system. Why do you start with channel 3=gas ??? 5=ail, 6=ele???.......... It might be worth considering adapting this channel assignment here.
The flybarless with S-Bus systems have a fixed default here. 
1=ail
2=ele
3=gas
4=rudder
5=gyro
6=pitch
7=other
8=emergency
already fixed during programming. 
A switchable fixed value for the gyro sensitivity might also be very important.
Also for the gas (for E-Helis)

Mg Sliderlucky

**Comment by FrSky-GX** [comment]
We will fixed the 1-6 default channel assignment as your seggestions.  The next 2 channels might be defined with different functions，so maybe create 2 free mixer would be convenient？

**Comment by Sliderlucky** [comment]
That was be great.
And the gyro?? 
Mg Martin

**Comment by BernhardFe** [comment]
Hi,
attached you can see the default for the Mikado V-Bar and the Spirit if they are connected to an S-Bus.
Both are designed to receive 10 channels, but configurable.

As Sliderlucky mentioned the channel 1-6 will be used as described.
As the most FBS need only a fixed value for the Gyro for the initial setup and then using a fixed parameter for the tail and the rotor  gyros in a Bank selected by 3 fixed values.
7 seven should be then Gyro Gain.
Channel 9 and 10 should be named AUX (can be use for light, sound or other functions.
The complete configuration should be as follow as an example:

1=Aileron (Stick)
2=Elevation (Stick)
3=Gas (Fixed Value depending on flight mode or curves depending on flight modes and pitch)
4=Rudder (Stick)
5=Gyro Gain Tail (Fixed Value depending on flight mode or curves depending on flight modes and gas or during setup poti)
6=Pitch (Stick)
7=Bank Switch (Fixed value depending on a flight mode (-100,0,+100)
8=Rescue (Switch)
9=Aux1
10=Aux2
11-16=open

Using the first 16 channel for the S-Bus, the hardware PWM output for the Receiver (e.G. R8Pro) might be switched (configuration) to the PWM channels 9-16 or 17-24 to use them for additional features in the heli.

Important feature would be to have fixed values depending on the fight mode in the mixer, but this is not directly possible today.
Then combination of Gyro Gain and Bank can be directly defined on the flight mode if the governor is done by the ESC.
This allows in the Spirit a lot of options. Today several mixer or other work arounds needed for this fixed values.

Hopefully this additional wishes are not too much for this but it can help to make the setup for a heli easier.

Bernhard
![00_PC_Channels-s](https://user-images.githubusercontent.com/86232280/162893583-07d90b3a-6593-41c1-a999-12dad14be9a5.jpg)
![2_1en](https://user-images.githubusercontent.com/86232280/162893613-e6435950-013a-4b37-b197-37a4756146e8.png)

**Comment by mawzthefinn** [comment]
You can use VAR mix to do a mix of fixed and adjustable values output to a single channel, based on any selectable criteria (FM, LSW, FSW, Switch position). VAR Mix weights can Use a Source to be adjustable.

**Comment by BernhardFe** [comment]
That's true. I'm just using the VAR exactly for this use cases. Channel shift is also possible in the Pro receiver for the PWM output. In the meantime I'm use all this requested features above. The basic heli setup I didn't use. But the channel assignment can be changed manually easy. I guess, this issue can be closed.
