### ISSUE TITLE
Rtc clock can’t set correct time

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#1597]
I have an x20s running latest stable release 1.1.4. Have adjusted rtc speed and found that if I set -314 my radio's timer runs 5 to 6 seconds slower per day and if I set -315 it runs 5 to 6 secs speed per day so unable to have a correct time. Any way you can set this in OS level?

**Comment by WismyYao** [comment]
Do you have a GPS sensor ? You can try turning on the "Auto adjust from GPS" option.

**Comment by bsongis-frsky** [comment]
We cannot do better, the calibration value has the precision that ST offers!
