### ISSUE TITLE
Lipo sensor - min cell

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#1598]
When using Lipo sensor, It would be great to have a sensor on the telemetry list displaying the minimum cell in voltage. This is a great feature to set the alarm on low voltage in a safer and more accurate way.

**Comment by guycnicholas** [comment]
There is one. On the sensor, long press the hamburger icon on the left:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/5494702/162756566-149e11ac-6b43-4981-8e9e-020ae2e3c095.png">
And then choose "lowest"
<img width="308" alt="image" src="https://user-images.githubusercontent.com/5494702/162756683-511fee87-023e-4f03-b73d-1b48d36c299d.png">

**Comment by marciomc-github** [comment]
> There is one. On the sensor, long press the hamburger icon on the left:
> <img alt="image" width="363" src="https://user-images.githubusercontent.com/5494702/162756566-149e11ac-6b43-4981-8e9e-020ae2e3c095.png">
> And then choose "lowest"
> <img alt="image" width="308" src="https://user-images.githubusercontent.com/5494702/162756683-511fee87-023e-4f03-b73d-1b48d36c299d.png">

That works perfectly, thanks!
