### ISSUE TITLE
Feature request: Fixed Values 1-9 in Free Mixer in the Curve menu

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1599]
Hi,
I'm missing fixed values in mixers. It would be great, if I could put in the mixer menu, where I can take in 9 different curves maximum, also 9 different fixed values directly. 
This should be selected by flight modes, switches, values... same events as regular. 
This would be very useful for gyros. The preset value of a channel can then be set depending on the flight mode or condition. 
This is useful for the SRX recivers and helicopter gyros. 
This functionality would be also useful to simulate a step value switch for sound modules and light modules where values can trigger sound and light under conditions.
Today I need to use work arounds to make this happen in Ethos. But a functionality like this would be easy to setup and there is also a great overview given.
I would appreciate this functionality in the free mixer as fixed value very much.

**Comment by mawzthefinn** [comment]
A VAR mix does exactly this, and can be used as a source for other mixes as well

**Comment by BernhardFe** [comment]
Thanks a lot for the hint! This is really a great news!
