### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by marevalor** [FrSkyRC/ETHOS-Feedback-Community#160]
Bluetooth functions:
- [x] FreeLink telemetry support
- [x] Trainer / Trainee support
- [x] Share model settings through Bluetooth

**Comment by Hill2** [comment]
Wireless connection to the Free Link is accomplished with the X20 firmware 1.09. But reading or writing to receivers fails.

**Comment by Hill2** [comment]
The free link app doesn't recognise the X20 on a IPad or iPhone and vice versa.
 
I tried with the app version 3.0 en the ethos version 1.09. Also changed the local name of the transmitter in 'X20' so I can easily recognise it. But nothing shows up.
When searching for devices nothing shows up meanwhile several devices surrounding the transmitter have Bluetooth active and can easily be recognised.

**Comment by Hobby4life** [comment]
You will find a device called "Hello" why this is I dont know.

@bsongis-frsky 
There is another BUG, When searching for devices on a X20, X10, X12 it does not work directly.
Only valid procedure is:
- Start Search
- Directly press return
- Start search again
- withing 5 seconds you will find devices

This must be fixed to work directly without this procedure

**Comment by Hill2** [comment]
Okay, I can connect the free link app with the X20. First time it will come up as 'Hello' as mentioned. The second time it will come up with the name given in the transmitter.

But It is still not able to read or write to the receivers. Tried with S6R and S10R pro receivers.

**Comment by Hill2** [comment]
Your mentioned valid procedure like beneath doesn't work on my X20

Start Search
Directly press return
Start search again
withing 5 seconds you will find devices

**Comment by Hobby4life** [comment]
Strange, I dont have a X20 only have a X20S

But we have tested this on:
4x X20S
3x X10S Express
2x X10S ISRM mod
2x X12S ISRM mod

All same behaviour for searching devices

**Comment by OldGazer** [comment]
My X20 will not connect via Bluetooth.  This reminds me of the Bluetooth in my X9e.  Its there but you can't do anything with it.

**Comment by mawzthefinn** [comment]
BT Telemetry bug was discovered in 1.4.3 and will be fixed in 1.4.4

**Comment by Richrfl** [comment]
The free link app is not receiving telemetry data from Tandem X18 (Ethos 1.4.8 FCC). I have an SR10 Pro (2.1.10), GPS and LiPo sensor. The Bluetooth link is active. I have in my device list in the Free link (3.0) the following devices Archer SR10 Pro,Taranis X-Lite, GPS. ( I really don't know if that is important for the sake of monitoring though). I have the BT set to Telemetry. Do I have a config issue or something is wrong. I noticed there have been few people with the same problem.

**Comment by bsongis-frsky** [comment]
The latest point is now implemented. Available in 1.5.0 nightlies!

**Comment by Dsrenger** [comment]
Wait....means I can copy a model file from one transmitter to the other (eg. XE to X20) via Bluetooth without laptop?

If so, that's great.

Not sure if I understand correctly

**Comment by bsongis-frsky** [comment]
Yes you can copy a model file from one transmitter to the other, XE to X20 for example, with automatic conversions if needed (not the same release on both radios):

https://www.rcgroups.com/forums/showpost.php?p=51138779&postcount=24833

**Comment by Dsrenger** [comment]
That's a great feature.

Well done...

**Comment by marevalor** [comment]
Thanks !!!
