### ISSUE TITLE
Negative Weight/Rates-Ethos

### ISSUE THREAD

**Issue by DougRossSA** [FrSkyRC/ETHOS-Feedback-Community#1600]
I have setup a plane with Flaps and Elevator compensation. I found that it was necessary to use negative values to reduce the elevator throws and I am wanting to know if this is correct. I have attached pictures of the X20 screens.
![All Mixes](https://user-images.githubusercontent.com/103433261/163128208-de6e0cb2-f749-4a86-8174-18977f0d0173.jpg)
![Elevator Weight Rates](https://user-images.githubusercontent.com/103433261/163128720-9a05467c-9c7f-47f5-a00d-8c7bcb8cb2aa.jpg)
![Aileron Weight Rates](https://user-images.githubusercontent.com/103433261/163128980-ade05d91-66a3-4f58-86a9-bf2b4e7efcde.jpg)

**Comment by mawzthefinn** [comment]
Why are you setting your throws here?

Set them in outputs, where they will properly limit the channel outputs. If you set in the Mixer, another mix can over-drive the surface, setting throws in Outputs puts a hard limit on them.
