### ISSUE TITLE
Size of telemetry values too small and bad visibility during sunshine!

### ISSUE THREAD

**Issue by gueldi52** [FrSkyRC/ETHOS-Feedback-Community#1604]
I had some flights outside while sun was bright using my brandnew X20S.
But I noticed the characters of the telemetry values too bad visible because of **being too small.**
My HORUS X12S with FROS is much better in direct comparing! Also the display is brighter.
So I would prefer the **font size** to be adaptable also in **colour and indivdual background** of each choosen value box.
Depending on the built of the choosen display the box sizes mostly have a lot more of space to show larger fonts!
Otherwise realy large boxes are not to be used very reasonable showing only one and bad visible small value...
And highlighted characters will be better seen on one fast sight which makes sense for instance for remaining capacitiy and/or consumption!

**Comment by jurajjurej** [comment]
Missing for X20 "FONT_XL_BOLD", "FONT_XXL_BOLD" (lua scripts)

**Comment by gueldi52** [comment]
I am really very disappointed that nothing is changed or edited regarding the always noticeable too small and not adjustable in size and color font (especially in the telemetry issues)!
The color screen offers the best conditions to enable a much better recognizability by an adaptable color selection of the font and the background...
And if then a scaling of the font within the selectable telemetry windows would be possible, it could not be better!
All this should be relatively easy to do under the given conditions...
And again: It is not about the font in the menu guide, but mainly about the telemetry boxes!
There, for example, is already a color-switching on loss of individual telemetry values on red. And you can already highlite the background of a single field. Why then not specifically completely customizable???

**Comment by xbutz** [comment]
Is there any news on the topic of font size / readability?

**Comment by Richrfl** [comment]
I read the V 1.5.10 reports
More contrast on fields which have the focus (feature).
The problem is in fields that DO NOT have focus.
Is there a typo error in the Release note?
