### ISSUE TITLE
Assigning trim speech tracks

### ISSUE THREAD

**Issue by Jamest95max** [FrSkyRC/ETHOS-Feedback-Community#1606]
I have assigned voice tracks to accompany trim up down left right etc but not able to assign GLOBAL meaning having to redo all on each model see pictures and also can someone tell me what the L&G means in the last picture i think it is logging but not sure

thanks
reguards James

![IMG_20220416_164842](https://user-images.githubusercontent.com/76268710/163682783-09fb399d-e0f3-4813-8ca1-e186d053b992.jpg)
![IMG_20220416_164858](https://user-images.githubusercontent.com/76268710/163682807-9ad2cc96-dd10-4229-ae2f-d56bea2bd1e1.jpg)
![IMG_20220416_164940](https://user-images.githubusercontent.com/76268710/163682830-65aafc1f-ff2a-4652-a04f-150a7ed16aa7.jpg)
![IMG_20220416_165002](https://user-images.githubusercontent.com/76268710/163682931-9270f3b1-6cc4-43d3-b4d8-e9f60ecca65f.jpg)

**Comment by mawzthefinn** [comment]
Special Functions can only be Global if their Active Condition is also available globally. The trim positions are not since trims can be configured per-model

And yes LoG is a logging indicator.

**Comment by bsongis-frsky** [comment]
Do you mean that the LoG indicator is not enough explicit? If it is not then just a bigger dot will be OK?

**Comment by bsongis-frsky** [comment]
Trims are on per-model basis

**Comment by Jamest95max** [comment]
Yes trims per model is obvious but standing back it is simply 4 switches I only want to set a sound say up trim for every model not globalize the same trim for all models.

**Comment by mawzthefinn** [comment]
The thing is for trims (like for Function Switches), there's no global switch triggers for these switches.
