### ISSUE TITLE
TD-MX  telemetry issue

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#1607]
TD-MX with tandem x20s when configured to 1000mw shows low rssi on 900mhz. It was working good as far as it is set to 500mhz or lower. setting it to 1W makes the 900mhz rssi fall below 80 when only couple of feet away.

**Comment by andycee** [comment]
As far as I know, when you switch to 1W the power goes in automatic mode and will increase when rssi fall below critical value. What you see is 25mWt power and low (but not critical) rssi value.
