### ISSUE TITLE
copy file from X20 to X10 not working (invalid data)

### ISSUE THREAD

**Issue by hamelsveld** [FrSkyRC/ETHOS-Feedback-Community#1608]
I've noticed that if your copying a model.bin file from a X20S to a X10 the model does not load/work. It shows the plane in the model selector but when you want to select it it tells you "invalid data".

I've also seen that on the X10 there are no folders / categories to put your plane in and / or an option to make them like on the X20. 

So on the X10 they all go to the uncategorized folder. Version of both transmitters is the same 1.2.1

**Comment by mawzthefinn** [comment]
On the X12S (1.2.1 RC1), the same thing happened, except worse the previously used model file name will load with errors and activate the external antenna on the ISRM (which may or may not be attached).

You can do folder organization on the X10/X12, but you need to make folders in File Manager as subfolders of /Models rather than through the Model Select UI.

**Comment by hamelsveld** [comment]
> On the X12S (1.2.1 RC1), the same thing happened, except worse the previously used model file name will load with errors and activate the external antenna on the ISRM (which may or may not be attached).
> 
> You can do folder organization on the X10/X12, but you need to make folders in File Manager as subfolders of /Models rather than through the Model Select UI.

But then you also don't have the options to move one plane in to a categorie because that option is missing in the GUI

**Comment by Hobby4life** [comment]
I can confirm, unable to create catagories on X10S / X10 Express / X10 Simulator.
Indeed X20 Models are "broken" on X10 radio's

**Comment by mawzthefinn** [comment]
> But then you also don't have the options to move one plane in to a categorie because that option is missing in the GUI

The option to move models is in the contextual menu for each model (short-press access it) and works, it's just creating categories that's missing.

**Comment by STC148** [comment]
To create a new folder, you should press and hold the PgUp/Dn button in the Model Tab. It works for me on both the X10 and the simulator.

**Comment by bsongis-frsky** [comment]
Fixed as it is the same than #1570
