### ISSUE TITLE
Max GPS speed setting option 

### ISSUE THREAD

**Issue by Latitude58** [FrSkyRC/ETHOS-Feedback-Community#161]
Great work so far and I'm really enjoying Ethos.

Could we have a 'Max gps speed' setting under the GPS telemetry settings please?

**Comment by Liverboy77** [comment]
This is already implemented just long press on the setting to bring up a sub menu

**Comment by Latitude58** [comment]
> This is already implemented just long press on the setting to bring up a sub menu

Aaah! Thanks so much for that, much appreciated!
