### ISSUE TITLE
LUA : getflightmode()

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1611]
i miss a cammand in Lua to get the current Flightmode.

**Comment by bsongis-frsky** [comment]
Today you could already use a Source with category=23 and member=0
In 1.2.7 you will create a Source with category=CATEGORY_FLIGHT_VALUE and member=SOURCE_CURRENT_FLIGHT_MODE

**Comment by loetefix** [comment]
Thank you bertrand.

Where can i get a list/table of valid category's and members?


⁣BlueMail for Android herunterladen ​

Am 12. Mai 2022, 09:04, um 09:04, "Bertrand Songis @ FrSky" ***@***.***> schrieb:
>Closed #1611.
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1611#event-6595672597
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
