### ISSUE TITLE
ADD Offset to Flap -> Elevator Mix (Request)

### ISSUE THREAD

**Issue by Nerenye** [FrSkyRC/ETHOS-Feedback-Community#1612]
EDIT: Result of the Conversation is that we need the Offset Option in Flap To Elevator Mix Preset.

*Original Text*:
Flap mixes are usually used with slow movement to adapt the flight phase more smooth
Elevator compensation mix on the other hand does not have the option for slow up / down.
Resulting in slow Flap movement and over Compensation at the start and under compensation at the end of the movement.

Only way to solve that is to use a free channel and another mix to include slow Up/down and pipe it into the elevator mix.

It would be nice to just have the option directly in the compensation mix

x20 ETHOS 1.1.4

**Comment by mawzthefinn** [comment]
There is a way around this. But it does need to be fixed so the flap->elevator mix works correct.

Use a single free mix as your elevator compensation, set the Source as a flap channel, the output as your Elevator channel, and make sure your offset and both weights are identical (can be fixed, or a source so you can tune in flight, but all 3 must be the same, the offset is there to ensure that 'up' position doesn't compromise the elevator position.

**Comment by Nerenye** [comment]
Yea but it does not work correctly in the mix itself. I´ve a working workaround but it should be in the intended function anyways

**Comment by mawzthefinn** [comment]
> Yea but it does not work correctly in the mix itself. I´ve a working workaround but it should be in the intended function anyways

If the flap channel source is chosen, it works correctly in the mix. 

For a Flap mix, the Flaps output MUST be the source (otherwise you are mixing a switch to elevator, not the Flaps to Elevator)

**Comment by Nerenye** [comment]
well makes sense, but if i use the flap channel in the source of the Ele Comp mix i don´t have an offset. So its useless again

**Comment by mawzthefinn** [comment]
Use a curve to do the offset, a 2-point curve functions well as an offset control (as a general aside, with ETHOS the answer to a lot of questions like this is ‘use a curve’)

Offset should definitely be added to the Flap-Elevator mix to eliminate the need for a curve

**Comment by mawzthefinn** [comment]
Offset added as a separate mixer type for these requirements
