### ISSUE TITLE
Bootloader  Ver 1.2.1

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#1613]
It looks like Bootloader are different in some distribution package in 1.2.1 RC1
I am using X20S-EU but could not have the bootloader included in the corresponding distribution to function.
After placing it in Firmware folder there is no "FLASH BOOTLOADER" option

Replacing the bootloader file by the one found in FCC distribution solved the issue (thanks a lot to MAWZ on RCGroups for the help)
According to MAWZ file found in ISRM distribution does not have this option as well
Have not checked any other distribution

https://www.rcgroups.com/forums/showpost.php?p=49077577&postcount=16967

**Comment by bsongis-frsky** [comment]
It will be available in 1.2.6 which I hope will loose the RC suffix soon
