### ISSUE TITLE
lua: missing FONT_XL definition for horus series

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1614]
Hi,
on horus transmitters "FONT_XL" is missing its declaration

 print("******  Font Definitions   *****")
  print("FONT_XS  ",FONT_XS)
  print("FONT_S  ",FONT_S)
  print("FONT_STD",FONT_STD)
  print("FONT_L  ",FONT_L)
  print("FONT_XL ",FONT_XL)
  print("FONT_XXL",FONT_XXL)

(tested on 1.2.1)

**X20 result**

![X20 fonts](https://user-images.githubusercontent.com/20392683/165691876-470d1cb5-b0d6-4aeb-9b2f-fdcf27cc5c24.png)

**X12 result**

![horus fonts](https://user-images.githubusercontent.com/20392683/165691895-5c8146fc-0f36-4f3f-b83c-30438e5f9ace.png)

**Comment by strgaltdel** [comment]
Just checked on X10 Sim 1.4.0

FONT_XL still only available for tandem,
not declared for X10 series

**Comment by jurajjurej** [comment]
Missing for X20 "FONT_XL_BOLD", "FONT_XXL_BOLD"

**Comment by mawzthefinn** [comment]
Please check 1.4.5, there were some changes there for FONT_XL, at least on the X18/X-Lite

**Comment by strgaltdel** [comment]
regarding the original issue,
the constants now do work for the X12 too, so I will close the issue.

the other fonts mentioned above never had a definition / constant within the lua base class, so it's another type of problem

in case it's further of interest, i would propose to open a new issue
