### ISSUE TITLE
Please create an SxR Mixer type

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1616]
This would be a canned mixer for the SxR/SRx stabilizers

It would be a little more complex to setup, as underlying it would be several actual mixes.

It should have fixed outputs to ch9, 10, 11 and 12

It should be selectable between Quick Mode and Regular mode (ideally this should be learned from the receiver on mixer creation, but that's probably a step too far)

It should have sections to assign switch positions to each flight mode and self-check and an analog or trimmer to gain. 

Ideally, the SxR menu should be updated to be able to configure assignments for this mix as well, and the New Model Wizard should be able to create this mix if desired with default switch/knob assignments.

**Comment by mawzthefinn** [comment]
Definitely would still like to see this.

**Comment by PiotrSzukalski** [comment]
Definitely would still like to see this.
