### ISSUE TITLE
Request for Servo matching feature when using servo telemetry 

### ISSUE THREAD

**Issue by TalperRC** [FrSkyRC/ETHOS-Feedback-Community#1617]
The Frsky Xact servo provides useful telemetry data that can be quite useful when adjusting servo endpoints 

In the current interface 
Adjusting servo endpoint is being done in one screen (ch output screen) and monitoring servo current is being done in different screen (Telemetry screen) 

It could be very usful if you can provide a screen that allow servo endpoint calibration and display relevant servo current on the same screen

**Comment by mawzthefinn** [comment]
Variant of #38

Probably can be closed in favour of that issue, as an additional ask.

**Comment by mawzthefinn** [comment]
Closing in favour of #38
