### ISSUE TITLE
x20 questions

### ISSUE THREAD

**Issue by uh1b1** [FrSkyRC/ETHOS-Feedback-Community#1618]
Hi I am needing someone here to explain to me what firmware I need to download,I am not a computer geek.I just bought this radio about two weeks ago and I see it is running 1.0.9 firmware and since this one was made and sent out there have been 14 firmware updates so my question's are as follows.
1.what firmware do I need and when I download it will all the assets download with it or will I have to do those separate.

2.after downloading the firm ware were do I put it on the sd card,and will the transmitter flash it automaticaly .
I will be putting the sd card in my lap top.

3.I am not getting more than 300 ft in range before it loses signal it should get way more than that

4.when I turn on the radio I get a rtc battery warning saying it is low the transmitter is brand new it shouldnt have a bad battery all ready  

I would really like to get this radio usable so any help is appreciated 
thanks
Todd

**Comment by mawzthefinn** [comment]
You want Firmware 1.1.4 (latest Stable).
SD card assets are in the 1.1.1 section (You need the SD card zip for your radio, which goes on the SD card, the Flash zip for your radio which goes on the flash drive, and the Audio zip for your selected language, which also goes on the SD card.

If you put the firmware, named firmware.bin, on the root of  the SD card, it will flash automatically if  you boot  to Bootloader (holding down the enter button/rotary encoder)

3. What receiver? The X20  should do FAR better  than that, I’ve had mine out past 1KM on 2.4GHz receivers (G-RX6 running ACCESS and Archer R4)

4. There was an excessive RTC battery bug in the firmware that was fixed around 1.0.14, you will need to update and to replace the RTC battery with an CR2012 battery. Note  your radio is older stock given it came with 1.0.9, newer batches shipped with 1.1.1

**Comment by uh1b1** [comment]
Thank you for the info mawzthefinn I will try that,im useing the frsky sr10 pro receiver and I will replace the rtc battery
also.
im sure I will have more questions down the road.

thank you
todd

**Comment by bsongis-frsky** [comment]
Please use forums for such questions, we have already a lot of feature requests here!

**Comment by bsongis-frsky** [comment]
Not sure you really need to have a new RTC battery, especially if it's new, please just update your transmitter!
