### ISSUE TITLE
TD R10 and lipo sensor - no telemetry

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#1619]
There’s no Lipo telemetry when using TD R10 and lipo sensor (MLVSS).
Already update the sensor to the latest version, but it is still not appearing in the sensor list after Diacovery new sensors = ON

**Comment by EngelMT** [comment]
Do you have set SPort in receiver options?

**Comment by LeoCheung123** [comment]
Same issue encountered here.  SPORT set for relevant pin used to connect the lipo sensor (MLVSS).

**Comment by mawzthefinn** [comment]
This has come up elsewhere recently. S.Port or F.Bus needs to be assigned to a Pin in receiver options, the 4-pin connector currently only appears to do AIN2 and receiver updates.

**Comment by EngelMT** [comment]
I had already written about the pin assignment above on May 16th. FrSky confirmed a long time ago that the 4-pin connector is only for updates and AIN2.

**Comment by mawzthefinn** [comment]
@EngelMT Your comment on May 16th was unclear as to which common issue it applied to, the ‘S.port defaults to FBus and therefore doesn’t work’ issue on most ACCESS and later receivers or the TD R10 needing a Pin assigned to S.Port issue.

My comment addressed the latter specifically.

**Comment by mawzthefinn** [comment]
Closing off as no response from OP received.
