### ISSUE TITLE
Vario volume controlled by a Slider / Pot

### ISSUE THREAD

**Issue by GIB2A** [FrSkyRC/ETHOS-Feedback-Community#162]
Proposal to add functions to be used commonly used by aircraft and glider pilots.

Incrementation of the sounds for a knob or by the 6 position selector very useful to vary the volume sonnores in flight (general volume and volume of the vario)

Addition of an idle down in the throttle stick function. This makes it possible to have in flight a different engine idle and higher than the reference one. We simply shift the limit of the servo stroke. it is very useful in aerobatics or during landing phases.

Ethnos is really good !!!!! thank you !
Cordialy .
Gib2a

**Comment by Liverboy77** [comment]
These are already implemented idle down is in throttle mixer. 
Volume on a dial is possible by long pressing enter on the symbol next to the volume in the menu

**Comment by GIB2A** [comment]
Indeed this is possible for the main sound but not for that of the vario.
When has the function idle down in the throttle stick. The function locks the curve at a defined value. perfect as a safety function when moving or when starting up.
However, it is necessary to add a function allowing to vary the engine idle speed to have the posibility of having two idles.
low idle and high idle on the main throttle curve during flight
cordially

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128507968-3521de5e-90a7-4c58-a3fc-3471baad4b4a.png)
