### ISSUE TITLE
Azerty keyboard on x20s

### ISSUE THREAD

**Issue by floflolapin** [FrSkyRC/ETHOS-Feedback-Community#1620]
Hi,
Would it be possible to select AZERTY in ethos?
Also the caps key is strange. There should be a position to get 1 capital and one position to lock it, like a keyboard on Android.

Thanks

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/167413351-25d7770a-7250-4abd-85c3-1d3372befffb.png)

**Comment by floflolapin** [comment]
That's really nice!! 
But I have mine setup in english.
Hope it's not related to language?

**Comment by bsongis-frsky** [comment]
French UI => French keyboard. Because you need a french keyboard to write English?

**Comment by floflolapin** [comment]
Well I'm used to azerty keyboard, but my radio speaks English, as it's much 
easier to find information and tutorial in English on the web...
