### ISSUE TITLE
lua: set sensor idle mode seems not to work (at least on horus)

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1621]
tested on Horus X12 / 1.2.1 RC1:

Hi,
my understanding is, that i should be able to use this method to set a mode.
(or to get the sensor status in case no argument used,
assuming this method does something like activate/deactivate the sensor in order to ensure plausible data) 

But in case i try this method to "set" the mode by using boolean arguments the script returns an error.
getting the mode seems to work correct

Documentation:

> LuaSensor::idle()	
> Set / unset the S.Port Sensor IDLE mode.
> 
> Since
> 1.1.0
> Parameters
> state	(boolean
> Returns
> result (boolean)

example see screenshots

![sensorIdle src](https://user-images.githubusercontent.com/20392683/166240548-0d3197e9-5bd6-405d-add6-3a1411908c41.png)

result:

![sensorIdle bug](https://user-images.githubusercontent.com/20392683/166240568-2b8aba9d-5bab-4d86-a26f-6a84f3452094.png)

btw
i tried this method because i do poll some statistical data from sensors which are not visible as telemetry values
it seems that the continuous poll / reading every 0.4 seconds,
prevents display refresh from new data / starting the paint handler on a regular base.
so i wanted to deactivate the sensor for some time and omit polls to give the paint handler a chance to refresh data.
hoping my idea is correct

**Comment by bsongis-frsky** [comment]
Is this one fixed?

**Comment by strgaltdel** [comment]
sorry for the late answer, just read your request.

no, not fixed, just tested  by using an x8r / ethos 1.4.6 /
 x18 & x12
appid 0x0C20, (standard rx id)

rx returns true by calling sensor:idle(),
but changing mode by calling sensor:idle(false) still produces the error.

should this method work on every sensor?

btw
found this behavior by chance, and no further feedback from other users seems to indicate very low importance ..

**Comment by bsongis-frsky** [comment]
Try calling `sensor:idle(0)`
