### ISSUE TITLE
Butterfly Mixer - option to disable negative part of curve

### ISSUE THREAD

**Issue by Mucki** [FrSkyRC/ETHOS-Feedback-Community#1623]
Hello there,
i'd like to make the following proposal:

Last time i set up a butterfly mixer using a 3 position switch. The stock Butterfly mix has negative outputs withthe switch being in the negative position, zero output with the switch being in the middle position and positive outputs with the switch being in the lower position. Therefore you can't use the 3 position switch to add a 2 staged butterfly mix with stage one being output e.g. +15 and stage 2 being +30, without using a secon mix that is limiting the input from the switch to only positive values in middle and down position.

It would be nice to at least have the option in the butterfly menu to change the behaviour of the mixer from positive and negative outputs and the neutral position being the middle one to only negative outputs an the upper position being zero output.

I'd imagine, that that is the way most people use the butterfly mix. The stock mix seems counterintuitive to me.

**Comment by strgaltdel** [comment]
Yepp,

Butterfly mixer requests have a long history,

please look at #139 
1st point i mentioned:

"1.)
The Butterfly function needs by definition an input that has a range from 0% to 100%."
guess that's your request

issue  was raised a year ago, still open, so maybe some day we will get a more useable Mixer.

**Comment by Mucki** [comment]
Yep, didnt find that post, when i was searching for it, but that is exactly the same request.

**Comment by Hobby4life** [comment]
This indeed is a must have, as i now have programmed multiple butterfly configurations with different mechanical setups.

**Comment by bsongis-frsky** [comment]
> Therefore you can't use the 3 position switch to add a 2 staged butterfly mix with stage one being output e.g. +15 and stage 2 being +30

You may use a simple 2 points curve which will modify the input

**Comment by strgaltdel** [comment]
Ich kehre zurück am 27.06.2022.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[SPAM] Re:
[FrSkyRC/ETHOS-Feedback-Community] Butterfly Mixer - option to disable negative part of curve (Issue
#1623)" gesendet am 16.06.2022 13:32:13.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by bsongis-frsky** [comment]
Source range converted to 0 - 100% instead of -100% - 100%
You won't need the curve starting from 1.2.11

**Comment by strgaltdel** [comment]
Ich kehre zurück am 27.06.2022.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] Butterfly Mixer - option to disable negative part of curve (Issue
#1623)" gesendet am 16.06.2022 23:13:44.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by strgaltdel** [comment]
Ich kehre zurück am 27.06.2022.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] Butterfly Mixer - option to disable negative part of curve (Issue
#1623)" gesendet am 16.06.2022 23:13:45.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.
