### ISSUE TITLE
Option for minimum "trigger time" to play track

### ISSUE THREAD

**Issue by Mucki** [FrSkyRC/ETHOS-Feedback-Community#1626]
In the special Functions menu it would be helpful to be able to assign a minimum time for a switch to be in a position to play a track.
At the moment if you have a 3 position switch and have track 1 assigned to the middle position and track 2 assigned to the lower position it play bot tracks after eachother if you switch directly (meaning very quick) from the upper position to the lower position.

it would be grat to be able to specify a minimum time that the switch has toi be in the "trigger" positon to play the track.
That way you can specify that you only get track 1 played if you are in the middle positon for more than half a second. In this scenario it would only play track 2 if you switch directly to the lower position because the middle position isnt triggered long enough.

**Comment by Nerenye** [comment]
I´ll Back that. that would be a nice feature to prevent audio tracks stacking up while re configuring the plane for landing for example

**Comment by loetefix** [comment]
for that there is the 'Switch middle detect delay' in the menu : SYS/HARDWARE/SWITCH SETTINGS

**Comment by Mucki** [comment]
Thank you very much. That is exactly what i was looking for.
