### ISSUE TITLE
colorpicker wit own lua

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1627]
Hi Bertrand,
i miss a command in Lua to get the colorpicker.
I would like to call the color picker in my own screen
maybe like lcd.color(getcolorpicker())
is there a possibility?
Thank you very much Benno

**Comment by bsongis-frsky** [comment]
You can use `addColorField(...)` in your configuration form.

**Comment by Benno00** [comment]
Hi bsonigis-frsky,

this only works in the configure function but not in your own functions. I want to call the color picker in my own function.
e.g. lcd.drawText(10,10,"Choose color:") lcd.color(getpicker())
Thank you very much Benno

**Comment by bsongis** [comment]
but you have to create a form for this widget, like you would do to select a source, or a value, etc.

**Comment by Benno00** [comment]
Hi Bertrand,
alright, thank you, 
I wanted to do it without a form because I want to call up my own configuration by touch and also move and change the sensor settings by touch, such as font and color. Then just use the form.
With kind regards Benno

**Comment by bsongis-frsky** [comment]
I think it should be possible to add a button, or a menu entry in the contextual menu to display your form, but this is another topic. Today you have to create a form to display a ColorPicker.
