### ISSUE TITLE
Ability to set a specific receiver as preferred or default. ENHANCEMENT

### ISSUE THREAD

**Issue by Droptank** [FrSkyRC/ETHOS-Feedback-Community#1629]
I use SRX receivers as main and RS as backup.  The RS powers on faster than the SRX and thus the telemetry for the RS latches and any sensors on the SRX do not display unless the receivers switchover due to signal loss or power cycle the RS.  Makes the built in angle and accel sensors useless on multiple receiver setups if the other receiver takes over telemetry.  Same applies to AIN voltage as well as that sensor is built in also.  If Ethos could set a preferred RX this would fix this issue.  OR send the internal sensor data to the S.port line.

**Comment by bsongis-frsky** [comment]
Not an Ethos issue, I will forward it.

**Comment by Adelaxie** [comment]
Connecting the s.port from two receivers would have all external sensors displayed.
But not possible to have the embedded sensor always displayed for now.
