### ISSUE TITLE
Allow Mixer Active Conditions to have FM selected

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1630]
Yes, I know that you can select the Active FM's right below, but there is one use case where this doesn't work well.

If you have a mix tied to a single flight mode and you add a new flight mode, that mix is now active in both FM's until edited. This is an issue for example when using a Lock mix to lock a specific channel in a specific FM.

If you could offer FM as a valid Active Condition as well, this would not happen.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/168810846-d14520b5-96c5-4913-912e-282c80c49f0e.png)
