### ISSUE TITLE
Ethos Suite

### ISSUE THREAD

**Issue by CliffEvans** [FrSkyRC/ETHOS-Feedback-Community#1631]
Ethos Suite is telling me that the firmware on my X20 is out of date (1.12.1), but will not update it to the latest version (1.2.3 RC3)  When I click the update button I get an error
![Screenshot (177)](https://user-images.githubusercontent.com/18718856/166958307-d8d981d3-65cf-487d-a4ef-66a75e6a828b.png)

**Comment by mawzthefinn** [comment]
1.2.3 RC3 is X18-only right now.

That shows a bug on ETHOS Suite, it should only show releases that are valid for the connected radio.

**Comment by CliffEvans** [comment]
> 1.2.3 RC3 is X18-only right now.
> 
> That shows a bug on ETHOS Suite, it should only show releases that are valid for the connected radio.

Thanks, do I need to report it, or should it be picked up here?

**Comment by ETHOSWarrier** [comment]
I get the same with my x10 ISRM..I am on 1.1.4 EU LBT and it says up grade available(to the latest) but when I click it ,error just as above.

**Comment by CliffEvans** [comment]
Another update for X18 but nothing for X20, but Ethos Suite is still showing X20 needs updating!  Bug not fixe
![Screenshot (178)](https://user-images.githubusercontent.com/18718856/167287493-a4c478d3-a9ba-463e-b33a-ed384c8bbfa7.png)
d

**Comment by bsongis-frsky** [comment]
New Ethos Suite is coming, hopefully tonight
