### ISSUE TITLE
X18 Ethos 1.2.3 no scripts from NAND

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1632]
After upgrading X18 to latest 1.2.3 i can not view any scripts from NAND
i found the new file paths:
https://www.rcgroups.com/forums/showpost.php?p=49071685&postcount=58   (please add this to a release note somewhere!)

and can operate images and sound files but no scripts from NAND they will run only from SD option (despite being duplicated in SD/scripts or in NAND/scripts)

**Comment by MIKE-DAILEY** [comment]
I have the file system documented on the RCG X18 thread here https://www.rcgroups.com/forums/showpost.php?p=49071685&postcount=58

**Comment by i3dm** [comment]
yes i edited my original posy

**Comment by i3dm** [comment]
> OK. I'll update my RCG post when we get this sorted.

did you recreate the issue too?

**Comment by bsongis-frsky** [comment]
Lua scripts work fine from Nand

**Comment by i3dm** [comment]
> Lua scripts work fine from Nand

dont write useless information.
nand/scripts/LUAdir can not see any scripts in ethos!
works ok on SD.

**Comment by bsongis-frsky** [comment]
Someone else can confirm that my useless information is right or wrong?
@MIKE-DAILEY I remember from a post from an happy user on RCG?

**Comment by i3dm** [comment]
your should really take user reports more seriously. closing a report with complete discredit and 0 information is unproffesional and just plain rude.

**Comment by MIKE-DAILEY** [comment]
> 

Could there be a misunderstanding of the issue?  Are you reporting that scrips that you put in a "script" folder on the NAND cannot be executed because ETHOS cannot access them?  As if the Storge Location change on the System General section "Scrpts" control is not working for you when "Scripts" is set for Radio?

**Comment by i3dm** [comment]
> > 
> 
> Could there be a misunderstanding of the issue? Are you reporting that scrips that you put in a "scripst" folder on the NAND cannot be executed because ETHOS cannot access them? As if the Storge Location change on the System General section "Scrpts" control is not working for you when "Scripts" is set for Radio?

yes.
can not view any script files from nand.
files are in nand/scripts/Widgetname/Widgetname.lua

**Comment by MIKE-DAILEY** [comment]
This is the path that should be used Nand:/scripts/WidgetName/main.lua

**Comment by i3dm** [comment]
> This is the path that should be used Nand:/scripts/WidgetName/main.lua

this is exactly whatvi am using and no svripts are readable by ethos.

**Comment by i3dm** [comment]
for example my RDT script is:
Nand:/scripts/RDT/main.lua

**Comment by MIKE-DAILEY** [comment]
And you have Storge Location on the System General section "Scripts" set for Radio?

**Comment by i3dm** [comment]
yes

**Comment by bsongis-frsky** [comment]
Issue replicated. Scripts work, but only if they are in the /scripts directory, not subdirectories
Fixed in 1.2.6

**Comment by i3dm** [comment]
> Issue replicated. Scripts work, but only if they are in the /scripts directory, not subdirectories Fixed in 1.2.6

will you take reports more seriously next time?

**Comment by i3dm** [comment]
> All reports are taken seriously. You should take time and explain better. i.e.
> 
> * all scripts from Nand don't work => wrong, checked by me after your issue has been opened, checked by FrSky test team as well
> * files are in nand/scripts/Widgetname/Widgetname.lua => cannot work, looks like a user issue

i just read my original post and its describing the issue very clearly.
and if you think something is wrong from the user side (which is not the case) you should request information and not repeatedly dismiss / close a REAL issue without any explaination.
