### ISSUE TITLE
X20 possible switch de-bounce issue when playing audio tracks 

### ISSUE THREAD

**Issue by glider73** [FrSkyRC/ETHOS-Feedback-Community#1633]
Set up to play back ARM/Disarm audio tracks using Throttle Cut and special function setup to use switch SF. Randomly when switching from arm to disarm playback will repeat play the arm disarm tracks. Happens maybe 1 out of 20 cycles no pattern detected. Noticed on multiple models. Firmware version 1.2.1 FCC

**Comment by mawzthefinn** [comment]
Are you still seeing this? I can't duplicate, but if it's debounce related that doesn't mean it doesn't exist.

**Comment by mawzthefinn** [comment]
Closing due to no response.
