### ISSUE TITLE
no more pictures of the models. x20 fw1.2.5.

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1637]
I no longer have any pictures of the models. On the X20 FW 1.2.5. ... 
Since the 1.2.5 update, the images are still on the sd card, but are no longer displayed in the menus...

**Comment by mgsanna** [comment]
they have changed the name of the folder from USER to MODELS
if you change the directory name you will get again your model pictures
yesterday night I was trying and solved the issue

**Comment by Mobidick1966** [comment]
OK, thanks . it works .
