### ISSUE TITLE
Ethos Suite

### ISSUE THREAD

**Issue by NiclasHaraldsson** [FrSkyRC/ETHOS-Feedback-Community#1639]
Have bootloader 1.2.6 and tried to update my x20s.System Bitmaps & Audio did go well but firmware update brought the error message "missing driver", I updated the fw the oldschoolway but it could be nice to use the Suite prog

**Comment by MiRe-CZ** [comment]
The same here with x20. After manual update the Suite reports "Firmware Version: 1.2.6 EU Greater than latest release" :-)

**Comment by bsongis** [comment]
The text is very wrong, it's not "Missing driver", but "Missing drive" (SD or Nand)

**Comment by bsongis** [comment]
> The same here with x20. After manual update the Suite reports "Firmware Version: 1.2.6 EU Greater than latest release" :-)

Screenshot please!

**Comment by MiRe-CZ** [comment]
I do not know what helped, I had x20 switched off and the Suite closed in the meantime. Now the Suite tells "Firmware Version: 1.2.6 EU Up to date". Let's see if somebody else will report the issue

**Comment by NMO81** [comment]
Yes I also have the issue, it seems that there is only 1 USB drive mounted for the SD and not the FLASH but updating audio works, only firmware not. (in my screenshot the update was already done without the suite)

![Schermafbeelding 2022-05-11 012808](https://user-images.githubusercontent.com/85587485/167740910-1d208b68-e157-478a-b0a7-25f09f257bd1.jpg)

**Comment by ZeekWorld** [comment]
Same
![image](https://user-images.githubusercontent.com/16088952/167770956-9cccaf31-086c-4fc8-85e1-17107a0fc915.png)

**Comment by Peterbilt84** [comment]
In the German version the error message is "fehlender Treiber".
However, the message only appears with the firmware update.
The SD card and flash updates went through without problems.
