### ISSUE TITLE
No model pictures after 1.2.6 firmware and bootloader upgrade

### ISSUE THREAD

**Issue by ZeekWorld** [FrSkyRC/ETHOS-Feedback-Community#1641]
X20S Model pictures dissapeared after 1.2.6 upgrade.
The images are still on the SD under bitmaps/user/ but when editing the model and selecting Picture there are no images to choose.

**Comment by bsongis** [comment]
As written in the release note, your model bitmaps are now in `/bitmaps/models` instead of `/bitmaps/user`

**Comment by ZeekWorld** [comment]
Thank you, I overlooked that. Note: Wiki may need to be updated.

**Comment by bsongis-frsky** [comment]
Which Wiki? Ours?

**Comment by bsongis-frsky** [comment]
Ah true, I will do the adaptations
