### ISSUE TITLE
What is going on with the version numbers!?

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1642]
To be honest, the release of 1.2 has been a mess!

- Release candidates were marked as **latest** versions, when they should have been **pre-release**s. 
- The 3rd digit of the version number was incremented when increasing RC number. 
- Then the RC part was just dropped.

It’s a total mess. There should have been 1.2.0 RC 1, RC 2, RC 3, …etc; which are labelled as **pre-release**. Then when the firmware is ready, a 1.2.0 stable release should have been made available with the **latest** label. That is logical and easy to follow. 

Were no lessons learned from the 1.1 release? This has been confusing as to what’s actually going on for me. I hate to think what it had been like for folks who don’t understand that release candidates are not stable release and how versioning should work. Please try harder with 1.3!

**Comment by MrD-RC** [comment]
I think it's a fair critique, when it added so much confusion. I guess with ETHOS Suite, this will be less of an issue going forward, as GitHub will not be used for firmware updates.

**Comment by bsongis-frsky** [comment]
Fair enough. I consider github releases as less and less useable for the average user, we cannot provide 40+ binaries without loosing people!

**Comment by MrD-RC** [comment]
Very true. Hopefully the ETHOS Suite will be the answer. 

By the way. I did not mean this as offensive to the team. So I apologise if it came across that way. You are doing fantastic work.

But just for 100% clarification, 1.2.6 is a stable release?

**Comment by bsongis-frsky** [comment]
Yes it is. In fact 1.2.x have had no big issue from the beginning. We have just spent a lot of time to add X18 support, especially because of its Nand

**Comment by MrD-RC** [comment]
Thank you Bertrand
