### ISSUE TITLE
Ethos Suite 1.2.6 - driver missing message

### ISSUE THREAD

**Issue by wattscr1** [FrSkyRC/ETHOS-Feedback-Community#1643]
I loaded new x20 boot loader onto radio and installed boot loader on the  radio and then downloaded ethos-suite-setup 1.2.6.  Started Ethos 1.2.6 install.   Installation copied all the audio and other files.  When completed, I got a message that said ‘Driver Missing’ and then stopped. Any idea of what driver was missing for this update?

**Comment by mawzthefinn** [comment]
Same here, this occurs for any attempt to update firmware with ETHOS Suite 1.2.6 and my X20

Audio, SD and FLash updates fine when selected individually.

**Comment by NMO81** [comment]
This is already solved see: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1639

**Comment by wattscr1** [comment]
Will do.

Thanks
