### ISSUE TITLE
Request: X10S without upgraded ISRM module support

### ISSUE THREAD

**Issue by fullmetalpacket** [FrSkyRC/ETHOS-Feedback-Community#1644]
I am not sure how much work that would require so I am only asking if its not!

I think that would be nice to have Ethos support for X10S radios that are not upgraded with the ISRM module. Thanks!

**Comment by Adelaxie** [comment]
ETHOS only supports color screens with ACCESS protocol radios.
No plan to expand to older products.
Thanks for your understanding.
