### ISSUE TITLE
Version 1.2.6 Chinese sound bug

### ISSUE THREAD

**Issue by chenbevis** [FrSkyRC/ETHOS-Feedback-Community#1647]
The CN sound of version 1.2.6 cannot read numbers 1~9

**Comment by Hobby4life** [comment]
???

**Comment by chenbevis** [comment]
> ？？？

The CN sound of version 1.2.6 cannot read numbers 1~9

**Comment by chenbevis** [comment]
Countdown to find problems

**Comment by bsongis-frsky** [comment]
Sounds from 1 to 9 took > 1 second to play, which is not very good for Timer Countdown
