### ISSUE TITLE
Fixed channels are automatically assigned to the functions in the wizard

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#165]
Fixed channels are automatically assigned to the functions in the wizard. This does not make sense. Since it is very time-consuming and annoying to change them. In addition, the function names remain assigned to the channel, even if the channel is deleted. It's very irritating.
It would be better to get a channel recommendation in the wizard, but to be able to change it.

**Comment by Boroal** [comment]
I agree at the moment when you create a model with two aileron channels the wizard assigns the second aileron to channel 2 and bumps each of the following up by one eg with AETR as standard having channels 1,2,3,4.  Add a second aileron and elevator shifts to channel 3 throttle to 4 and rudder to 5. It would be far better to assign the second aileron to channel 5. This would leave the rest on their standard channels. Better still if the wizard made recommendations as the original poster suggested

**Comment by keiner0815** [comment]
I totally agree.
Some time ago I opened an issue with the same suggestion, but it has been closed:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/94

**Comment by IJK-CZ** [comment]
Related to issue 286 [https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/286](url)

**Comment by bsongis-frsky** [comment]
Already improved in 1.0.10

**Comment by bsongis-frsky** [comment]
Will be improved again with issue #552
