### ISSUE TITLE
[Ethos Suite] Interruption when copying audio pack

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#1650]
I updated my X12s to Ethos Version 1.2.6.

Updating via Ethos Suite worked great (updated bottloader first, then updated the software via Ethos Suite).

Audio language was pre-selected to english.
So I de-selected English, selected German and hit the start button. It failed two times already.

Downloading the audio pack worked, but the process freezes at different positions of the green status bar.

Then I have to close Ethos Suite, open it up again and restart the process.

P.S. After the third try it worked now

**Comment by bsongis-frsky** [comment]
Method changed in 1.2.7 please check it again
