### ISSUE TITLE
Italian Ethos Manual rev.0 [IT] X20 and Ethos User Manual_1.1.4_rev0

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#1657]
[[IT] X20 and Ethos User Manual_1.1.4_rev0.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8685468/IT.X20.and.Ethos.User.Manual_1.1.4_rev0.pdf)

**Comment by bsongis-frsky** [comment]
Thanks for your manual, I have added it to the repository
