### ISSUE TITLE
RB30+     4 aileron servos

### ISSUE THREAD

**Issue by LProia** [FrSkyRC/ETHOS-Feedback-Community#1659]
Good morning,

I run etho 1.2.6 on X20S.
On RB30 + with latest firmware, wing configuration 4 traditional aileron + tail servos and 2 elevator servos.
How can i connect 4 aileron servos, 2SX + 2DX and use the stable mode?
Is it possible to clone the stable mode on any output pin?
Thanks

**Comment by mawzthefinn** [comment]
All the FrSky Stabilizers are limited to 2 aileron channels, 2 elevator channels and 1 rudder channel for stabilization. This is a receiver-level limitation.

You should be able to assign the two stabilized aileron channels (ch1 & 5) to more than one receiver port on the RB-30 (and on the Archer SR receivers), but be aware that you lose independent control over each servo that way

**Comment by LProia** [comment]
good morning,
it would be useful to introduce the Aux 3 and Aux 4 functions.
If frsky wants he can definitely do it.
my problem is that with a new RB30 + I am forced to use it only as an energy divider.

thank you
