### ISSUE TITLE
Vario sensor entry misleading. (Vertical Speed)

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#166]
With the Vario (for example Archer GR6), the sensor entry Speed ​(Geschwindigkeit in german) ​appears for the vertical rate of climb.  VSpd would be correct. Otherwise it is misleading.

**Comment by bsongis-frsky** [comment]
It is "VSpeed" in english and "Geschwindigkeit Vario" in Deutsch, which is too long

**Comment by bsongis-frsky** [comment]
I change it to "VSpeed" again

**Comment by Skippydi** [comment]
Yes I know, but Vspd would be a good name.

Von meinem iPhone gesendet
