### ISSUE TITLE
Frsky X18 Ethos 1.2.6 don´t show any Model Picture

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#1660]
Hello,

i have a Problem, at my new X18 i don´t have any Picture of a Model.
I put my Models at the  ordner bitmaps/ models.

At every model i can put the right pitcure, but it don´t show it.

**Comment by EngelMT** [comment]
Do you use the right size? Maybe you should convert the photos in the ETHOS Suite.

**Comment by bsongis-frsky** [comment]
You have to check:
- that you use the correct disk (Nand or SD), depending on your radio settings
- that your models are in /bitmaps/models on this disk
- that your files format is correct, perhaps use Ethos Suite to be sure the format is correct
- that your files size is correct (width cannot be over LCD width and height cannot be over LCD height)

**Comment by AlwinHaas** [comment]
Hello, the Format was to big.
I don't have any problem.
