### ISSUE TITLE
X20S  latest ETHOS Missing Offset at lots of reday mixers, only range with offset will works fine

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1661]
Comparison openTx/Edge with ETHOS
X9E, X9D+2016, TX16S, X20S

i am pretty frustrated today,
set up large glider and fly it in
so far in OpenTx, new with X20S ETHOS

1 day on the airfield,
half day messed up because the ETHOS can't do anything right
I don't like to touch the X20 ETHOS anymore
rather sell it again

If you are used to OpenTx and Companion,
then ETHOS is a big step backwards

Since I have both I can compare directly

Not to mention the clear OpenTx programming on the PC.

ETHOS has a lot of ready to use mixers that can do a little bit of everything but nothing completely.

What is missing almost everywhere is the offset, there is always only weighting available but no offset.

This always leads to the fact that one must work awkwardly over an additional auxiliary mixer or with a curve.

The trim function is missing on the free mixer (which should be able to do everything).

The Varmixer, which is actually a fixed value mixer, but should also be variable via analog values
cannot limit the range of a potentiometer because it lacks offset, so again an auxiliary mixer is necessary.

The finished butterfly mixer is for nothing to use, only rudmentary available.
If you have a 4-6-8 flap glider with umpteen switchings and flight phases.

What is missing are the inputs, only wen you no longer have them, you realize how ingenious this is.

T

**Comment by keiner0815** [comment]
Agreed, I ran into the same problem that I need offsets for mixers!

**Comment by hrenz** [comment]
I am aware that from a programmer's point of view
weighting and curve is completely sufficient.
But a model pilot who comes from MPX, Spektrum or Graupner can not understand why there is no shift, no offset, and why he should use a curve with weighting, if he only wants to raise 2 rudders by 20%.

You must understand more the view of the operator, 
not just your programmer's view.

**Comment by bluelex73** [comment]
I can confirm that.
Offset values would be great and would simplify the setting of the models significantly. Etos is already great. Adding offset values to the mixers would definitely be a big improvement for Ethos.

**Comment by bsongis-frsky** [comment]
I cannot agree here. Offsets in all mixes will just break the logic of the mixers.

Issue 1: as a pilot, I want to be able to remove the butterfly mix at any moment
=> with the proposals I have received, when I remove the butterfly mix, the flap will go to a stupid position, this is not acceptable

Issue 2: now I want to use the same flaps for 2 functions, like butterfly or any other function mix
=> where would go the offset? butterfly or the other mix? 

It has no meaning: it simplifies the life (really? the offset needs to be configured anyhow), and kills the logic of the whole mixing

The big difference with OpenTX in this area is:
- only one Offset mix
- only one Aileron mix
- only one Butterfly mix
- only one function per mix

It simplifies things a lot compared to OpenTX

![image](https://user-images.githubusercontent.com/50834778/180050546-3567c8e5-cf97-4928-96cb-721000c8df51.png)

![image](https://user-images.githubusercontent.com/50834778/180050587-1f12ae8b-d58e-4f0e-95cc-0cc17e69c0e6.png)
