### ISSUE TITLE
FrSky X10 Express running ETHOS 1.1.1, Icon help

### ISSUE THREAD

**Issue by Planetester** [FrSkyRC/ETHOS-Feedback-Community#1663]
How do you create an model image in ETHOS 1.1.1 on an X10 Express, most say a .png at 320 x 280, the sample images on the SD card are bmp's at 180x160 32bit, ive tried saving a jpg as a bmp at 180x166 at 24 bit but it doesnt display on my TX

Thanks

**Comment by bsongis-frsky** [comment]
Perhaps you could try using Ethos Suite? It has a dedicated tool for bitmaps conversion

**Comment by Planetester** [comment]
Brilliant, thank you
