### ISSUE TITLE
Ethos 1.2.6. special functions and logical switches menu model clone instead of copy?

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#1664]
Tandem X20S , Ethos 1.2.6
since the Ethos update to 1.2.6. is in the special functions and the logical switches no longer copy but model clone. this is not so correct. can you please change it back to copy?
![LogischeSchalter](https://user-images.githubusercontent.com/84685639/168484429-e022c825-4927-410e-bfe5-8fe9b6445022.jpg)
![Spezialfunktionen](https://user-images.githubusercontent.com/84685639/168484458-9393bae1-9f01-4a5d-95bb-c9ee0163d0b6.jpg)

**Comment by hrenz** [comment]
Should be in german "Zeile kopieren" or "Zeile clonen"

**Comment by bsongis-frsky** [comment]
Bug introduced in DE translation. Will be fixed in 1.2.7
