### ISSUE TITLE
RXBatt Frsky Tandem X20 with Firmware 1.2.6

### ISSUE THREAD

**Issue by gomitologiallo** [FrSkyRC/ETHOS-Feedback-Community#1665]
Hi
After updating to Firmware 1.2.6 the RxBatt value does not correspond to the real value.
How to fix?
Greetings

**Comment by bsongis-frsky** [comment]
What is the real value, what is the displayed value? I cannot remember of any change on this topic

**Comment by gomitologiallo** [comment]
The displayed value is 4.96 and the real value 3.95 but the problem is that the value 4.96 always remains fixed and does not go down

**Comment by bsongis-frsky** [comment]
Perhaps a stupid question, but did you select any option like Maximum on the Source of your widget?

**Comment by gomitologiallo** [comment]
No, the problem came after the update.
I haven't changed anything in the widgets

**Comment by gomitologiallo** [comment]
no, the problem came after the update.
I haven't changed anything in the widgets

Inviato da iPad

**Comment by bsongis-frsky** [comment]
Please post a screenshot of your widget settings

**Comment by bsongis-frsky** [comment]
Also please try to remove and re-discover this sensor

**Comment by gomitologiallo** [comment]
I've already tried

Inviato da iPhone

> Il giorno 17 mag 2022, alle ore 08:37, Bertrand Songis @ FrSky ***@***.***> ha scritto:
> 
> Also please try to remove and re-discover this sensor
>

**Comment by Adelaxie** [comment]
@gomitologiallo which receiver please? Only to have a try here.

**Comment by gomitologiallo** [comment]
R9 mini OTA
Sr8Pro

Inviato da iPhone

**Comment by yequhuashiren** [comment]
https://user-images.githubusercontent.com/62365833/168940746-55ad725e-c050-4612-8686-d275c538c2c0.mp4

**Comment by gomitologiallo** [comment]
???

Inviato da iPhone

**Comment by gomitologiallo** [comment]
I can't view the fil

**Comment by Adelaxie** [comment]
The video shows Rxbat showed correctly with R8 PRO , ETHOS 1.2.6
So, cannot confirm here.
How did you use with R9 mini OTA & SR8Pro? under Redanduncy mode? same power source?
Please provide more info , video is better than words.

**Comment by gomitologiallo** [comment]
The two receivers are mounted on two different planes and both show wrong values.
But the most interesting thing is that the value is shown correctly in the FPV goggles.
Why not on the X20?
As soon as I have a bit of tpo I send you the video of the X20.
Regards
Inviato da iPhone

**Comment by mawzthefinn** [comment]
Do you have a BEC in the mix? What you are describing is what I'd expect if the battery is plugged into an FC or other device which is providing 5V to the connected items such as the VTX and Receiver.

**Comment by gomitologiallo** [comment]
On a plane yes
the other planes do not.
 But the problem is still the same.
Apparently the problem cannot be solved?
Regards
Inviato da iPhone

**Comment by mawzthefinn** [comment]
There is no problem on the plane then, this is expected behaviour with a BEC, as it regulates voltage. RxBatt is voltage at the receiver, not at the battery and with a BEC, should be stable regardless of battery voltage.

How are the others wired. The described behaviour indicates that there is some device between the battery and the receiver.

What is  providing the voltage information to the VTX?

**Comment by gomitologiallo** [comment]
the vtx information is correct

Inviato da iPhone

**Comment by mawzthefinn** [comment]
Where is the VTX getting the information from?

You almost assuredly don't have an issue with the receiver's voltage sensing or ETHOS, but do have either a regulator or a voltage booster in the mix somewhere.

To diagnose requires knowing every piece of equipment involved in the configuration and how they are wired. Unless the battery is plugged directly into the receiver, the receiver is unlikely to be getting direct battery voltage.

If you plug the battery (assuming 2S or 1S) directly into the receiver with nothing else connected, do you get correct RxBatt?

**Comment by Adelaxie** [comment]
@mawzthefinn thanks for your help. 
We here tried different combinations for the two receivers and they work as expected. @gomitologiallo

**Comment by gomitologiallo** [comment]
OK thank you.
I have another question: can Li-Po 2s 4000mah be replaced with a Li-ion?
If so, which one?

Regards

**Comment by mawzthefinn** [comment]
The battery compartment will fit 2 18650 LiIon cells wired in series (2S configuration).

**Comment by gomitologiallo** [comment]
Kapazität: 5000mAh
Wattstunden: 37wh
Spannung: 7.4 Volt
Zellen: 2x 21700 Li-Ion – 3.7V
Anschluss: JST-XH und XT30
Gewicht: 150 g
Größe: 72mm x 42mm x 22mm
Ladestrom: max 2A



this is not good?

Inviato da iPad

**Comment by mawzthefinn** [comment]
Won't fit, the X20 battery compartment dimensions are:

86mm x 42mm x 20mm

It's OK in 2 dimensions, but 2mm too tall.

**Comment by gomitologiallo** [comment]
The displayed value is 4.96 and the real value 3.95 but the problem is that the value 4.96 always remains fixed and does not go down.

Inviato da iPhone

**Comment by gomitologiallo** [comment]
OK! I got it.
so to get information, run also on the radio ethos, do I have to insert a current sensor?

Inviato da iPhone

> Il giorno 20 mag 2022, alle ore 13:33, mawzthefinn ***@***.***> ha scritto:
> 
> Where is the VTX getting the information from?
> 
> You almost assuredly don't have an issue with the receiver's voltage sensing or ETHOS, but do have either a regulator or a voltage booster in the mix somewhere.
> 
> To diagnose requires knowing every piece of equipment involved in the configuration and how they are wired. Unless the battery is plugged directly into the receiver, the receiver is unlikely to be getting direct battery voltage.
> 
> If you plug the battery (assuming 2S or 1S) directly into the receiver with nothing else connected, do you get correct RxBatt?
>

**Comment by mawzthefinn** [comment]
In order to troubleshoot we still need you to answer the questions above regarding how the VTX is getting the voltage data and how your receiver is wired.

This still appears to be a wiring issue giving correct but unexpected behaviour, not a receiver issue.

Please post a picture of your setup and attach your modelxx.bin file
