### ISSUE TITLE
[Enhancement] Changeable text size in ETHOS

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#1666]
I introduced ETHOS to a few senior members at the flying club with an X20s and they are very happy with it.

But the text size should be changeable to get bigger letters.

Especially in the Outputs Menu the names of the channels are very small.

So it woulb be great to have changeable text size.

**Comment by loetefix** [comment]
Agree. The testsize is realy realy small

**Comment by i3dm** [comment]
agree with you both

**Comment by bsongis-frsky** [comment]
> In particular, it would be very useful if the text size in the telemetry widget could be adapted to the size of the widget. At the moment, regardles of the widget size, the text size is always the same, which is kind of odd.

This is wrong, you will see that the text size autoadapts to the area. There are 3 possible sizes.

**Comment by Hartinger** [comment]
I have generated the following two screen shots from the X20 simulator, which contain widgets of different sizes. Clearly, the font size is the same in all the widgets shown. Am I missing something here, or is the simulator not representative in this regard?

![Widget1](https://user-images.githubusercontent.com/22352021/172671612-83395a01-31df-4d0f-bcc5-f087c099e628.png)
![Widget2](https://user-images.githubusercontent.com/22352021/172671636-a9f63df9-f2c8-45f3-bf34-2c4b32b5b855.png)

**Comment by bsongis-frsky** [comment]
Because this is the biggest font of the system

![image](https://user-images.githubusercontent.com/50834778/172673058-4997156f-0dc3-4c7b-846b-cd235c165835.png)

**Comment by Hartinger** [comment]
Ah, ok, but would it not make sense to introduce a bigger font for the widget that fills the entire screen? (I understand that the widget with half the size of the screen is mainly to show the model picture.)
But I agree it is not the most important thing to do at the moment.

**Comment by keiner0815** [comment]
And also please keep in mind that the text size on a X20(s) is "smaller" compared to a X12s, just because the resolution of the screens is different.
On the X20(s) reading the names at the channel overview for example is really hard.

I think this can be fixed pretty easy as it is a small text size in that screen that could be changed to a bigger one.

Maybe a faster fix in general would be to increase the text size by default in all screens.
For my initial request to make the textsize changeable the expense would be much higher as all screen layouts have to work with different text sizes.

**Comment by keiner0815** [comment]
Is there a possibility to add the "new" text size in the near future?
Maybe only on a few screens for a quick start. 
It is really hard to read the channels menu for example on the X20(s)

**Comment by bsongis-frsky** [comment]
You will be able to use this font (or your own fonts) in next release
![image](https://user-images.githubusercontent.com/50834778/180049383-ad609a63-8eb4-4de9-94b8-dd6918f31025.png)

**Comment by keiner0815** [comment]
Is it possible to use that font as system font or only for messages/telemetry screen?

**Comment by 3frcg** [comment]
> You will be able to use this font (or your own fonts) in next release:
> 
> ![image](https://user-images.githubusercontent.com/50834778/180049383-ad609a63-8eb4-4de9-94b8-dd6918f31025.png)

More info on how to proceed please.

**Comment by philippe-warnotte** [comment]
> > En particulier, il serait très utile que la taille du texte dans le widget de télémétrie puisse être adaptée à la taille du widget. Pour le moment, quelle que soit la taille du widget, la taille du texte est toujours la même, ce qui est plutôt étrange.
> 
> C'est faux, vous verrez que la taille du texte s'adapte automatiquement à la zone. Il y a 3 tailles possibles.

Hello, I really appreciate your update work. 
Improvements and Bug Fixes. 
Unfortunately, you didn't think about the poor pilots with glasses. 
It would be very interesting if the size of the letters and numbers were larger if we use a single widget in a single display. 
Example: ​​big fonts for chrono or telemetry values . 
THANKS YOU.
