### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by nillet** [FrSkyRC/ETHOS-Feedback-Community#1667]
Really enjoy the Ethos system. I prefer using the light theme (dark mode off) on my x20. It would be nice if you could change background color as well as highlight color

**Comment by T3chDad** [comment]
That capability for dark mode would be nice as well.

**Comment by bsongis-frsky** [comment]
I am not sure it is possible as we use gradients of black / gradients of white, and it won't be easy to adapt to all colours

**Comment by bsongis-frsky** [comment]
Unless you mean only the background colour of the main screen?

**Comment by T3chDad** [comment]
I'm not trying to speak on behalf of the OP, but that's what I had in mind.

![simulator_43JZK6ucns](https://user-images.githubusercontent.com/5139966/205059685-70b2427e-429f-4cf0-b839-215a20550069.png)
