### ISSUE TITLE
Ethos Suite 1.2.7 doesn't recognise X20S/X20 anymore

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#1668]
With 1.2.6 suite everything was working as usual, but after updating to 1.2.7 the radio even connect in any configuration is not recognised.... by the suite.... reinstalling 1.2.6 everything works again
so 1.2.7 is broken

**Comment by MIKE-DAILEY** [comment]
Working OK here with X20S and 1.2.7. FCC.
![1-2-7](https://user-images.githubusercontent.com/11791852/168704109-5295a3f1-9a87-4f05-9f18-c6512d36a65d.JPG)

Are you using 1.2.7. FCC?

**Comment by FireFlite88** [comment]
Super noob to Ehtos here,  I just downloaded the 1.2.7 and the new Suite.  If I want to update my radio,  do I just plug it in to Suite now?

Or do I have to manually transfer files to the radio using windows?

**Comment by Nicholas-Luoyi** [comment]
> Super noob to Ehtos here, I just downloaded the 1.2.7 and the new Suite. If I want to update my radio, do I just plug it in to Suite now?
> 
> Or do I have to manually transfer files to the radio using windows?

Please plug the radio to the computer with bootloader. Or plug the radio with ETHOS and then click the Start Bootloader in Suite. Then you can choose the ETHOS version in Suite and update it.

**Comment by mgsanna** [comment]
@MIKE-DAILEY I use FLEX, but as state before if I reinstall 1.2.6 suite everything works, with 1.2.7. Suite doesn't recognise the radio connected in any way...

**Comment by mgsanna** [comment]
Ok Solved it's a Window 11 driver problem,
I've reinstalled the whole Frsky X20 interface and everything works again....
