### ISSUE TITLE
lua: paint() handler stops looping after Ethos finished booting / activates RF Module

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1671]
Attached is a demo-widget that proves a problem of my description:

As far as i do understand, the paint handler is regularly & automatically executed in the background.
This behaviour can be observed during the boot phase of the transmitter.
(Counting up a timer in the debug window).

However, as soon as the warning messages of the transmitter are acknowledged & the RF module is activated, the paint handler is idle, which imho is a bug.

See picture, approx. 7 seconds after booting the transmitter and ack all hints, the loop of the paint handler stops counting.
so the display of the left widget "displ" can't get refreshed / is empty

![paint01](https://user-images.githubusercontent.com/20392683/168777547-e2e36a79-3c89-4fed-a8af-e0b18c9542b7.png)

The screen is no longer refreshed automatically, the paint handler must now be called manually, e.g. via wakeup handler.
(imho this is not intended system behaviour, as this can also have an effect on other screen refresh processes).

Only when you tap on a timer widget, for example, is the display of the widget refreshed.

![paint02](https://user-images.githubusercontent.com/20392683/168777589-32b5e4e0-df7c-4572-bb5e-ead10e68d52e.png)

`	

																			-- ************************************************
																			-- ***		     name widget					*** 
																			-- ************************************************
	local translations = {en="displ"}

		local function name(widget)					-- name script
		local locale = system.getLocale()
		return translations[locale] or translations["en"]
	end

																			-- ************************************************
																			-- ***		     yaapus getime workaround		*** 
																			-- ************************************************
	local function getTime()
		return os.clock()		 
	end

																			-- ************************************************
																			-- ***		     "paint handler"				*** 
																			-- ************************************************
																			
	local function paint(widget)

	local runTime = getTime()
	if getTime() > widget.nextWhite  then	
		lcd.font(FONT_S)
		for i = 0,5 do
			lcd.color(lcd.RGB(255,255,255))
			lcd.drawText(10, i*16, "Have Fun "..tostring(math.floor(runTime)))
		end
		widget.nextWhite = runTime + 3
	end
	print("debug: "..tostring(math.floor(runTime)))

	end

																			-- ************************************************
																			-- ***		    startup (onetime) handler		*** 
																			-- ***	         returns widget vars			*** 
																			-- ************************************************
	local function create()
		local nextCol=0																						-- timestamp color
		local nextWhite = 0																					-- timestamp bw
		return{nextCol=nextCol, nextWhite=nextWhite}
	end

																			-- ************************************************
																			-- ***		     configure widget				*** 
																			-- ************************************************
	local function configure(widget)
	
	end

																			-- ************************************************
																			-- ***		     "background loop"				*** 
																			-- ************************************************

	local function wakeup(widget)
		--lcd.invalidate()
		--paint(widget)
	end
																			-- ************************************************
																			-- ***		     monitor events		 	   		*** 
																			-- ************************************************
	local function event(widget, category, value, x, y)
		if category == EVT_KEY and value == KEY_EXIT_BREAK then
				print("BREAK")
		end
		return false
	end
																			-- ************************************************
																			-- ***		     init widget		 	   		*** 
																			-- ************************************************
	local function init()
	system.registerWidget({key="unow0Y", name=name, create=create, wakeup=wakeup, paint = paint, configure=configure, event=event})
	end
	
	return {init=init}
`

**Comment by bsongis-frsky** [comment]
> As far as i do understand, the paint handler is regularly & automatically executed in the background.

No. `paint()` is only called when a (partial / full) refresh of the widget is needed. You cannot assume that it will be executed regularly. The `wakeup()` function does what you need.

**Comment by strgaltdel** [comment]
Hello Bertrand, thank you for your quick reply,
I appreciate it very much!

_"paint() is only called when a (partial / full) update of the widget is required."_

That was my assumption a few days ago, but while brute-force / manually calling paint in wakeup(), I could see that changes caused by lcd.drawtext() etc were looping in paint, but the screen was not updated.
would have expected that a manual paint call with instructions for painting text would have initiated the refresh
I realized that I need to call lcd.invalidate(), not paint, to update the widget, which led to the wrong conclusion that something was wrong with paint().

By the way
great work from you and your team
