### ISSUE TITLE
TD mode EU LBT: 2.4GHz telemetry is not activated if 200/500mW selected for 900MHz

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#1673]
Tandem X20S
Ethos 1.2.7 EU (LBT)

Receiver: TD R18 (maybe same with other Rx?)  

If 900MHz is set to 200 or 500mW:  no telemetry signal received on 2.4GHz (also no telemetry on 900MHz which is correct at 200/500mW)
If 900MHz is set to 25mW all OK

(My understanding of  LBT EU regulation (I am not a specialist):

900MHz telemetry is limited to 25mW (excludes 200 and 500mW)
With telemetry set to 2.4GHz than 900MHz can emit with 500mW)

![Capture d’écran 2022-05-18 085411](https://user-images.githubusercontent.com/97453480/168976893-9cb37729-d8c2-4ed8-a7b1-6b509b7e6032.png)

![screenshot-2022-05-17-56911](https://user-images.githubusercontent.com/97453480/168977602-6a8334c9-59c9-4981-92de-e056b47258e5.jpeg)
![screenshot-2022-05-17-56879](https://user-images.githubusercontent.com/97453480/168977657-a382b5ef-a78d-4142-9078-67ba0e382e6a.jpeg)

**Comment by Eagleowl1** [comment]
This is my understanding as well.
My question: why is it not possible to receive telemetry in 2.4GHz while emitting at 900MHz at 500mW

Could please explain what FLEX means and implies? I cannot find any documentation about this point.

In case I would like to change for FLEX:  just replace the firmware? or more is requested.

Does Flex also have LBT?

Thanks

Silvio
________________________________
De : mgsanna ***@***.***>
Envoyé : mercredi, 18 mai 2022 11:55
À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc : Eagleowl1 ***@***.***>; Author ***@***.***>
Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] TD mode EU LBT: 2.4GHz telemetry is not activated if 200/500mW selected for 900MHz (Issue #1673)


In Europe telemetry could be used only in 25mw.... is not an hardware or software problem....it's a law/legislations matter...if you need you can install FLEX firmware that permit to use telemetry even with eu firmware and increased power.....

**Comment by mgsanna** [comment]
Silvio, the Eu legislation is strictly and annoying, since you have an apparel that is transmitting more than the "law" rules all telemetry is limited to 25mW
simply change to Flex and flash to flash also all 868/900 rx... to unlock the telemetry and max power of 868/900 to 1000mW adaptive. The radio continue to be eu LBT for the 2.4Ghz
Marco 
(probabilmente protrammo scriverci in ITALIANO) 
(sono il traduttore di ethos, ethos suite e manuale)

**Comment by mgsanna** [comment]
ps you can also check selecting options in your TD18 RX Menu to activate Telemetry....

**Comment by mgsanna** [comment]
Td rx firmware is one for all, adaptive to radio firmware.
FLEX FIRMWARE is a normal eu lbt firmware with the 900 mhz unlocked... it's on your responsability to use in accordance to the local laws. As far as I know all s.bus sensors are usable, but some has to be discovered and "programmed" as dyi sensors and raw data translated in a human redeable way.... and last but not least radio.bin is your personal setup is not the firmware.... so you have to backup your radio.bin and after installato the specific Flex firmware... that is called firmware.bin (put inside root directory of sdcard) and before that have you updated your internal rf module? You'll find the last one on frsky site not on github.....here you find only ethos.
For our records I speak and wrote Italian, French and a little german.... :-))

**Comment by Adelaxie** [comment]
>900MHz telemetry is limited to 25mW (excludes 200 and 500mW)
@Eagleowl1 yes, it's correct, and TD telemetry was sent back based on 900M datalink(except 2.4g RSSI & VFR).
