### ISSUE TITLE
RC 1.2.7 Error in Screen of X20S when connecting X20S to iMac with USB-C cable

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1677]
Hi developers,
I have updated to 1.2.7 manually via SD card my X20S. It works as expected. (latest Ethos suite for mac still missing)
Switching X20S on and then connecting the X20S to the iMac USB causes an Error.
The screen is then toggling fast between the main screen and the selection menu for the USB connection.
It doesn't help to press the selection button randomly. The toggling will not stop.
Wenn I do the same with a windows PC, the selection menu is stable shown. It seems to be an iMac specific connection error.
BR Bernhard

**Comment by BernhardFe** [comment]
Update: I got the hint to change the USB cable. Instead of using the original cable, I took an Amazon basic cable. This worked and the switching of the display has gone. FrSky suite was connecting also. Others have similar issues with USB cables, also with Windows computer and not with Mac. The question is now what ist the root cause? Hardware? Or timing in Firmware?
BR Bernhard

**Comment by bsongis-frsky** [comment]
I am not sure we can do anything if the USB cable is not good!
