### ISSUE TITLE
X20S simulator interface

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1679]
Is it possible to develop a X20S simulator interface that emulates the radio. This would be similar to the opentx simulator. Using the keyboard is kinda awkward and difficult to selector sticks and switch's without referencing the radio legend. Thanks.

**Comment by Joetrin** [comment]
It's called Ethos Suite and it exists already in the latest firmware.

**Comment by ninodesposati** [comment]
The current simulator does not emulate the knobs and switches except for letters on the keyboard. Having a graphical interface like the rotation of a knob for example is what I'm talking about. Perhaps I'm missing something.

**Comment by 3D-Cat** [comment]
> Is it possible to develop a X20S simulator interface that emulates the radio. This would be similar to the opentx simulator. Using the keyboard is kinda awkward and difficult to selector sticks and switch's without referencing the radio legend. Thanks.

hi, where did you get stick, switch, trim etc controls on keyboard? is there any documentation?

**Comment by loetefix** [comment]
https://www.rcgroups.com/forums/showpost.php?p=47748621&postcount=10729

**Comment by 3D-Cat** [comment]
THNX

**Comment by jurajjurej** [comment]
We need trimmer control, FS. Testing is very limited.
