### ISSUE TITLE
Output Min/Max +/-125% is to less

### ISSUE THREAD

**Issue by NorbertHeli** [FrSkyRC/ETHOS-Feedback-Community#168]
Only +/-125% in Servo Ouput Min/Max ist to less, because many servos are working for a wider range.
I use it often at butterfly and take the maximum travel of the servo to get  good resolution and torque.

When I fully use flaps at butterfly they are nearly 90° deflected and the servoarm is straight. So i´ve little tourque at the servo.

Also to manipulate GPS Triangle receiver from Rc electronics Snipe has a bigger range then +/-125%

**Comment by bsongis-frsky** [comment]
If I am not mistaken, the limit with ACCST / ACCESS will be around 133%
I will increase from 125% to 150%
