### ISSUE TITLE
Incomplete simulator documentation 

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1686]
Please could you include details about the keys used in the simulators. I have read somewhere that gimbals and switches can be operated via the keyboard. This information should really be included in https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/Ethos-simulators#keys

**Comment by loetefix** [comment]
https://www.rcgroups.com/forums/showpost.php?p=47748621&postcount=10729

**Comment by MrD-RC** [comment]
Perfect, if that was in the Wiki it would be great.

**Comment by bsongis-frsky** [comment]
Done here, thanks to Ceeb182

https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/Ethos-Simulator---Keyboard-Shortcuts
