### ISSUE TITLE
Request: Reverse Slider option.

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#1687]
Due my expectation that the physical movement should be the same on the X18 as on my X20.
It is physically reversed.

I ofcourse can change all my logic, and curves and directions in the mixer.
But this could be just done much simpeler in the hardware tab, just invert behaviour of the slider.
This way i can still swap my models between the X20 and X18.

**Comment by hrenz** [comment]
This is a pinout error at PCB 
has to inversed at ETHOS intern for X18

**Comment by Hobby4life** [comment]
Hmm besides a pinout error. A reverse option would stil be apreciated as others like to operate the slider the other way arround when using my models.

**Comment by mawzthefinn** [comment]
I’d like the invert option as well, because it would make the swapping of the 2-pos switches easier. If you do the 2 pos swap by swapping the slider pots as well, they invert.
