### ISSUE TITLE
request : force title off / disable title in config screen in the LUA script 

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1688]
In some cases it is nice if we can force title off in fullscreen in the LUA script. Please add a command to disable and force the  title switched off in the configuration.

something like 

config.forceTitle(OFF) in the configure function.

**Comment by bsongis-frsky** [comment]
Parameter `title` added to `system.registerWidget(...)` it can take value `true` (force title ON) or `false` (force title OFF)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/169881035-ad740058-40cd-427c-bef6-02fb937927a9.png)

**Comment by loetefix** [comment]
Perfect, thank you.
