### ISSUE TITLE
write in append mode doesn't work anymore

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1689]
Hello Bertrand,
the LUA function write in append mode no longer works always returns the following error
**wakeup() error: /scripts/telemetrie_org/main.lua:283: bad argument #1 to 'write' (FILE* expected, got nil)
Here the source
278 f = io.open(filePath.."test.lua", "w")
279 io.write(f,"test1")
280 io.close(f)
281
282 f = io.open(filePath.."test.lua", "a")    <-- Append mode will not work!
**283 io.write(f,Test2")**
284 io.close(f)

Thanks Benno

**Comment by bsongis-frsky** [comment]
Line 283, you miss a `"`?

**Comment by Benno00** [comment]
Hi Bertrand, 
no, the Funktion in Lua "io.open(f,"a")" <-- open File for Append is not working in Version 1.2.7 and 1.2.8
when i open a file for write it works but not for append the error is then 
***wakeup() error: /scripts/telemetrie_org/main.lua:283: bad argument https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1 to 'write' (FILE expected, got nil)**
This will work but it will overwrite the file
**278 f = io.open(filePath.."test.lua", "w")**
this has work in Version 1.2.4 but now not
282 f = io.open(filePath.."test.lua", "a") **<-- write to file for Append**

Thanks Benno

**Comment by Benno00** [comment]
now I have to read in the whole file, remember the lines and append the next line and write it again completely
io.open (filename [, mode])
This function opens a file, in the mode specified in the string mode. It returns a new file handle, or, in case of errors, nil plus an error message.

The mode string can be any of the following:

"r": read mode (the default);
"w": write mode;
"a": append mode;                                                                                              ** i wont open file for Apend**
"r+": update mode, all previous data is preserved;
"w+": update mode, all previous data is erased;
"a+": append update mode, previous data is preserved, writing is only allowed at the end of file.
The mode string can also have a 'b' at the end, which is needed in some systems to open the file in binary mode.

**Comment by bsongis-frsky** [comment]
Line 278 if should be:
```lua
local f = io.open(filePath.."test.lua", "w")
```

**Comment by bsongis-frsky** [comment]
Bug reproduced and fixed

**Comment by Benno00** [comment]
Hi Bertran, that is a write new file not for append file I will write a line into exiting fileThat has work in version 1.1.4 f=io. Open(file, "a") Great benno HalloFreundliche Grüße,Benno JurischBenno JurischSiedlung 5, 27624 GeestlandTelefon: +49 (0) 4708 707Mobil: +49 (0) 152 337 76 ***@***.***

**Comment by Benno00** [comment]
Thanks alot Bertrand,
