### ISSUE TITLE
Switching between flight modes freezes outputs

### ISSUE THREAD

**Issue by RoP09** [FrSkyRC/ETHOS-Feedback-Community#169]
I have configured 2 flight modes (for different expo + weight of ailerons). When switching between the 2 with the assigned switch SA (and the respective mixers therefore), the outputs are frozen for about a second which means the model is uncontrollable.

Caused a near crash situation lately on my maiden flight.

**Comment by MIKE-DAILEY** [comment]
Not able to replicate.  Can you please attach your model and radio file.

**Comment by RoP09** [comment]
Here's the model and radio file (renamed to txt otherwise it's blocked)

I have a X20 with FW 1.0.4

Could it be due to the .wav track I play in parallel to switching the FM (somehow blocking the TX)?

[model01.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6413315/model01.txt)
[radio.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6413317/radio.txt)
