### ISSUE TITLE
Custom Hello wav file doesn't override welcome to Ethoes sound

### ISSUE THREAD

**Issue by ajatmiddday** [FrSkyRC/ETHOS-Feedback-Community#1690]
With 1.2.8 my custom hello.wav file no longer plays on startup. It's in the same position it's always been (audio/en/system) and I can access it and play it. I hope the boring "Welcome to Ethoes sound "has not been hard wired in." Small issue, but one that was fun.

**Comment by MIKE-DAILEY** [comment]
Works for me OK with 1.2.8. but I did not update the sounds.   If I had it would have overwritten my custom system sounds and I would had to restore them.

**Comment by ajatmiddday** [comment]
I tried to find where the "Welcome to Etheos" voice file was located & could not find it. It should have been where my custom file is..

**Comment by MIKE-DAILEY** [comment]
My custom X20S/X20 hello.wav is on the SD card audio/en/system/hello.wav  One the NAND drive on the X18, same path.

**Comment by ajatmiddday** [comment]
I finally straightened this out. The update to 1.2.8 using the Suite was not a clean process for me & some how I wound up with two "audio" folders one inside the other. Once I deleted the redundant audio folder it appears to be working correctly now. At least my "You turned me on" (Female voice) startup followed by "You turned me off" shutdown sound makes me smile.
