### ISSUE TITLE
Suite 1.2.8 for mac Firmware upgrade bricked radio (warning)

### ISSUE THREAD

**Issue by ZeekWorld** [FrSkyRC/ETHOS-Feedback-Community#1692]
On Mac OS Monterrey Suite 1.2.8 does not finish the Firmware process.
It shows up the upgrade progress bar but doesn't do anything.
The Firmware upgrade gets stuck half way if the radio gets unplugged from the USB port and reconnects to the suite.

![image](https://user-images.githubusercontent.com/16088952/169560911-0c1adb1d-fa19-4d3b-a709-c21659f2168d.png)

Screen stuck on Firmware upgrade with progress bar half way.
Removed battery now radio doesn't start at all.

**Comment by ZeekWorld** [comment]
Brought the radio back alive by refreshing the bootloader.

**Comment by ZeekWorld** [comment]
This was the screen with the stuck progress bar

![IMG_20220520_092432](https://user-images.githubusercontent.com/16088952/169563132-1bf33946-b128-4fae-8fda-753b3912b2ba.jpg)

**Comment by camber2** [comment]
Had very similar problem LAST NIGHT!
Mac with 10.13.6 High Sierra - ETHOS SUITE 1.2.8
I have 2 X18 Tandem radios. The first one was a black and ETHOS SUITE was awesome. Updated everything.
Then plugged in the blue one (exact same firmware) and trouble. Started with hanging up same as your but maybe an 1/8 of the way only. Left it for 20 minutes and nothing. Shut down to un-mount drives. Pulled USB cable out. 

I'm still having issues with ejecting (un-mounting) both drives. They re-mount immediately.
After several times of having to shut down to unplug USB. I now get a ERROR OPENING FILE
STARTING MODEL WIZARD... (Is this a nand drive issue?)

ETHOS SUITE crashes each time I try to QUIT. Application not responding
![Screen Shot 2022-05-20 at 12 37 15 PM](https://user-images.githubusercontent.com/65172935/169573341-818dc0dd-b823-4de0-bf83-77b239cdd12d.png)
.

**Comment by camber2** [comment]
More testing to safely eject drives.
Mac 10.13.6 High Sierra
Ethos Suite 1.2.8
Cannot eject NAND, FLASH OR SD in X18 (FW 1.2.8)
From Ethos suite, click eject drives and system warning about not ejecting drives.
If viewing the X18 drives only from Mac (not SUITE) When I eject drives **they constantly re-mount.**
I have to shut down each time to safely unplug USB. Been on Mac for 20+ years and never had issue with removing a drive before.

**Comment by ahvink** [comment]
Same here.
With MacOS Suite 1.2.8 process halts at 'Writing firmware to flash'
Replugged the battery and re-entered the boot loader, at that time the firmware continued to flash and all was OK.
Did have to manually update the boot loader.

**Comment by Bowdean26** [comment]
Yep same thing happend to me and iam not on a mac.... for the error opeing files messed up all my throttle settings and lost all pics of models.. The files are on the sd card just the radio does not see them now

**Comment by ZeekWorld** [comment]
> Yep same thing happend to me and iam not on a mac.... for the error opeing files messed up all my throttle settings and lost all pics of models.. The files are on the sd card just the radio does not see them now

For the missing models pics check the new images path, it was changed on a previous release. I ran into it as well because I did not read the changelog, not sure if the WIKI has been updated with the new SD file structure yet, I haven't checked it.

**Comment by Bowdean26** [comment]
Thanks Zeek Appreciate that!

**Comment by bsongis-frsky** [comment]
For MacOS, please take care that your bootloader is updated to 1.2.8!

**Comment by camber2** [comment]
I’m on 1.2.8 and other x18 is bootloader 1.2.6
Ethos suite can’t eject. Ethos suite has to “force quit” EVERY TIME. Can’t eject from Mac (without using ethos suite)
All other drives easily get ejected. Only when I use x18. The SD, nand and flash reload within seconds of eject drives.

**Comment by bsongis-frsky** [comment]
Another post for OSX and this unmount / mount loop:
https://apple.stackexchange.com/questions/209992/os-x-cant-unmount-disk

**Comment by bsongis-frsky** [comment]
> I’m on 1.2.8 and other x18 is bootloader 1.2.6 Ethos suite can’t eject. Ethos suite has to “force quit” EVERY TIME. Can’t eject from Mac (without using ethos suite) All other drives easily get ejected. Only when I use x18. The SD, nand and flash reload within seconds of eject drives.

Yes. Reproduced. 
We have to find the work-around for OSX, I have seen somewhere a way to prevent OSX auto remount, but it was not obvious!

**Comment by bsongis-frsky** [comment]
You need 1.2.8 or you will have flash issues on OSX

**Comment by camber2** [comment]
I’m using latest SUITE. 
Bootloader 1.2.8 on blue x18 = crash and cannot eject drives (3) associated with x18

bootloader 1.2.6 on blacks x18 = crash and cannot eject drives (3) associated with x18

Mac 10.13.6 High Sierra
Ethos Suite 1.2.8

**Comment by camber2** [comment]
Yes. The black has no issues but I was recommended to use manual updates for all firmware and updates. But… each and every time I connect the x18 to Mac I shut down the CPU. Then remove USB. And reboot max system. 
So yes I still really like the radio (best I’ve had). Love the ethos OS on the radio. It’s beyond awesome (IMO). 
But suite is not doing its job ; )
Or my Mac is tired.

**Comment by bsongis-frsky** [comment]
Fix found, will be included in 1.2.9

**Comment by camber2** [comment]
Awesome!!!!
You guys (and gals) are on the ball. 
Did I mention I’m loving the X18 and love the way ethos thinks! Bravo on the OS
Will try tonight

**Comment by ZeekWorld** [comment]
> Fix found, will be included in 1.2.9

Fantastic!
