### ISSUE TITLE
[Ethos Suite] Ethos Suite lacks a check for update possibility

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#1693]
Either through a menu option, or at least a message  like  "There is a new Ethos Suite version available do you want to download.."
I'm on the MacOS version.

**Comment by mawzthefinn** [comment]
It checks automatically on application close.

**Comment by ahvink** [comment]
That doesn't make sense to me...
Wouldn't a check at application startup be more logical ?

**Comment by bsongis-frsky** [comment]
Today auto-updates are available on Windows only, we will work on auto-update for OSX later
