### ISSUE TITLE
Serial Debug with PC and X20

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1695]
which serial driver for PC debug with X20
![image](https://user-images.githubusercontent.com/97786547/169693295-293d36a0-7545-44de-abbd-37c9ff1323a2.png)

Thanks Benno

**Comment by strgaltdel** [comment]
Hi Benno,
my X12 is running on stm VCom driver / Win10.
drivers were already installed before i stepped into the ethos world
https://www.st.com/en/development-tools/stsw-stm32102.html

this may help,
but my understanding was that x20 is declaring an standard cdc device and so should use standard Win drivers,
i may be wrong.

**Comment by Benno00** [comment]
Hy Udo, 
thank you very much that worked

thanks Benno
