### ISSUE TITLE
1.2.8 Missing letter in the special characters on virtual keyboard

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1696]
In the new characters ä, Ä, ü, Ü and ö are present, but we also need the capital Ö

![Screenshot 2022-05-22 221433](https://user-images.githubusercontent.com/85410070/169714416-bdf9620d-ecae-4ee8-ba19-e90e92aa119e.jpg)

**Comment by bsongis-frsky** [comment]
Special chars reordered and Ö added

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/169764133-a7d488c0-e956-42a1-b3c4-d952340aef6d.png)

**Comment by hrenz** [comment]
and a "+" sign is missing
