### ISSUE TITLE
X20 V1.2.7  Error at Lipo lowest min  shows 0,0V insteed of the lowest cell  after Rest lipo or Reset all

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1699]
FLVSS or MLVSS with 4S Lipo
Error at Lipo lowest min
shows 0,0V insteed of die lowest cell value stored
after Rest lipo or Reset Telemetrie all

Only first time lipo lowest min is the correct value of lowest cell stored

After then, and/or after Reset it allways shows 0,0V

think its atiming problem after reset lipo, or rest telemetrie all,
and it schows the value of Cell 5 or Cell 6   its 0,0V at 4S lipo

these mistakes can be repeated exactly

**Comment by Nerenye** [comment]
try Lipo lowest without min. works for me

**Comment by hrenz** [comment]
This t  not the same:
lowest  without min shows only the aktuell lowest Value
but after motor-load is off, the Values rise again, thats ok.

lowest min has stored the lowest Cell value
this is importand, so you can see how far the battery is really empty 

and lowest min works only one time at the start well,
but not after reset Lipo or reset Telemetrie then it shows allways 0,0V
I think the secuence after reset did not read the correct lowest cell, it sets it to 0,0V

**Comment by bsongis-frsky** [comment]
Fixed for 1.2.11
