### ISSUE TITLE
Tandem X20 Change pathing for user audio files.

### ISSUE THREAD

**Issue by OldGazer** [FrSkyRC/ETHOS-Feedback-Community#17]
Currently user audio files must be placed in the audio folder.
If a user extracts the Amber sound pack to the audio folder and then creates a special function to play a track after homklm.wav (hotter.wav for example), the SF wizard will choose the wrong file.

If the user wants the SF to play hotter.wav, the wizard will choose "---" and no *.wav file will be selected.  If the user wants to play hrzn.wav, the wizard will choose 1cell.wav.

The attached .ZIP file contains the exact files I was using when I discovered this issue. 

To reproduce the issue simply extract the contents of Amber.zip to the audio folder of the SD card and then create a special function that will play hotter.wav or any file after hotter.wav

[Amber.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6226284/Amber.zip)

**Comment by mpjf01** [comment]
I'm guessing but it might depend on the number of sound files in the directory, in my case it stops selecting the correct file in the "F"s and reverts to files starting with A or 3.

**Comment by OldGazer** [comment]
Thanks for the feedback.  At least I know I am not the only one seeing this.

**Comment by bsongis-frsky** [comment]
The file index was stored as 8-bits, so 256 files max
It is fixed in 0.0.18
