### ISSUE TITLE
[Ethos Suite 1.2.8] freeze after installation of Audio

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1700]
Updating my X20S from 1.2.7 EU (LBT) to 1.2.8 EU (LBT) with Ethos Suite 1.2.8.
After selecting Audiopacks EN + NO I choose Update All.
It seems everything goes well, but Ethos Suite 1.2.8 freezes after the NO Audiopack reaches 100% competion.
Then I have to ForceQuit Ethos Suite... 
After unplugging and restarting the radio, the radio info-screen still displays Firmware 1.2.7!!! 

Don't know if it's related at all, but now I see that the date on the radio has changed from may 24. (today) to may 16! 
Previously the date has been correct as far as I am aware of :-/

![IMG_5573](https://user-images.githubusercontent.com/87149917/170121822-45d22dc6-bba5-4a02-8935-c7f70347de5c.jpg)

![IMG_5574](https://user-images.githubusercontent.com/87149917/170121848-de7420f9-04cd-47b5-a624-0f50d551291b.jpg)

**Comment by mmasch** [comment]
Tried to Flash once more with only EN Audiopack selected. All went well and the Info screen displays FW 1.2.8...

**Comment by Nicholas-Luoyi** [comment]
For the copying operation of Audio Pack. It is truly an issue. The reason for your radio's firmware version is still 1.2.7 is that the firmware updating will happen after the Audio Pack copying. It means that Suite hasn't updated the firmware at all.

**Comment by bsongis-frsky** [comment]
This date is the date of the release.
We are still working on the USB issues
