### ISSUE TITLE
Install Bootloader file from Ethos Suite?

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1702]
My X20S has Bootloader v1.2.6. Would like to update to v1.2.8. 
In Ethos Suite, the "First Use guide" says: Connect your radio "Power Off" to the computer with a USB cable. 
But I do not find any button or menu allowing me to update the Bootloader. 
I see the Bootloader for X20S is in the 1.2.8 file-pack on this page, and can download and install it from there, 
but it would be nice if you could install it directly from Ethos Suite???  ;-)

**Comment by Nicholas-Luoyi** [comment]
We will help you update Bootloader automatically later. But for now, please try following steps:
- Open the Suite firstly
- Connect your radio to the computer with radio powered off
- Click the "DFU Flasher" in the side nav
- Select your bootloader.frsk or bootloader.bin and flash it into your radio
Please notice that these operations require a DFU drive on your PC.

**Comment by hrenz** [comment]
simplest way
copy the booloader to SD-Card and flash it from there

**Comment by bsongis-frsky** [comment]
We are working on a full automatic update of the bootloader from Suite. Today either you use the FRSK tool (in firmware mode) or the DFU tool (ST bootloader)

**Comment by shobhitx20s** [comment]
Where can I get the latest version of the Bootloader for my Frsky X20S tx Please assist me in downloading the file

**Comment by Nicholas-Luoyi** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.4.15/X20S_BOOTLOADER.zip

**Comment by shobhitx20s** [comment]
Thanks a lot Mr Nicholas. Got the file and will try to load it on my Tx. Hopefully it should wake up and stop being dead.
Regards

**Comment by shobhitx20s** [comment]
Tried uploading it through the DFU uploader. Connected the Tx without powering on... it says DFU not detected.

Next tired the same with the TX in Bootloader mode. Tried flashing through the DFU Flasher. Again it says DFU not detected.

Guess now I need assistance to detect the DFU first.
Regards

![Image](https://github.com/user-attachments/assets/6eea3fe9-352f-41a6-8173-766a227b3156)

**Comment by shobhitx20s** [comment]
Maybe I also need the Ethos firmware suitable for Bootloader 1.4.2.  If someone could help me with that file please.

Regads

**Comment by Nicholas-Luoyi** [comment]
Please try to install the DFU driver with the following .exe.

[zadig-2.4.zip](https://github.com/user-attachments/files/22356247/zadig-2.4.zip)

**Comment by shobhitx20s** [comment]
Thanks a lot Nicolas-Luoyi.. Guess I need the STM32BOOTLOADER file and my computer reads this through Zadig

How to get the STM32BOOTLOADER on the Tx. Please assist

![Image](https://github.com/user-attachments/assets/142ce8c7-552e-4f9a-aab9-2e577a57ff07)
