### ISSUE TITLE
Model images loading slow

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#1703]
The model images in the Model Select screen are still loading very slow.
Is there a way to speed this up ?

**Comment by Planetester** [comment]
Are your BMP files too large, I had some 600kb ones that took ages, others were 47kb and load great

**Comment by Nerenye** [comment]
@Planetester that should not be relevant at all 600kb isn´t that much anyway

**Comment by Hobby4life** [comment]
600kb for a model image is way too big for ethos OS.
Dont compare image file sizes with other devices.. Ethos OS is totally different.
I have added a "Thumbnail" option in my online image converter.
If you dont need a big model image.. but only need them for the "gallery" resize them to small thumbnails.. everything will load appropriate.

https://ethosbmp.hobby4life.nl/

**Comment by Nerenye** [comment]
600kb is like nothing for the type of cpu used in our radios.
Thats quite possible some kind of optimization issue. 
Nothing important for sure. but that could be optimized .

**Comment by Planetester** [comment]
I do know that 600kb is a small file but I did witness that out of 30 models, 3 of them had 600kb .bmp's and the loading of the images paused on all 3

**Comment by bsongis-frsky** [comment]
With 600kb for each bitmap, your RAM will be 100% used very soon. We have 8MB for the whole system, including the fonts rendering, the system bitmaps etc.

**Comment by Nerenye** [comment]
@bsongis-frsky so all the default images are 300+ kb so half of 600 at least on x20. 
all my models are between 10kb and 70kb and still loading slow ... 10 models take about 7-10 seconds.
I´m usually not even close to 3 seconds in the model screen and would realy like to not be forced to read the names.

So what´s the solution? If your default is 4 times as big as my biggest image it should load way faster right?!...

**Comment by Nerenye** [comment]
Well thats with png... with the recomended .bmp format the files are at 329kb and its WAAAAYYYYY worse. like 15-20 sec for 10 models.

**Comment by ahvink** [comment]
I only have PNG files which are all smaller than 210 kb and still images are loading relatively slow.
When switching folder in the Model Select and returning gall the images are loading and so again the delay.  

By you @bsongis-frsky closing this issue does this mean there is no improvement possible ?

**Comment by Hobby4life** [comment]
I dont think so, as there is no external ram used.

**Comment by bsongis-frsky** [comment]
> I only have PNG files which are all smaller than 210 kb and still images are loading relatively slow. When switching folder in the Model Select and returning gall the images are loading and so again the delay.
> 
> By you @bsongis-frsky closing this issue does this mean there is no improvement possible ?

I think we can improve PNG loading by reducing the amout of RAM needed (progressive load). But it is more work because we have to change the library and debug the new one which is very slow for an unknown reason (less RAM needed, but slower)

**Comment by Nerenye** [comment]
Thanks for considering! It's really not a priority. Please focus on important stuff first but keep it in mind and some day... 😉

**Comment by ahvink** [comment]
Thanks for looking into this, much appreciated !
