### ISSUE TITLE
ETHOS 1.2.8 wont work with X18/x20 on ACCST using R9M Lite.

### ISSUE THREAD

**Issue by ETHOSWarrier** [FrSkyRC/ETHOS-Feedback-Community#1705]
Hello.I am using an FrSky R9M Lite module  with my x20 so that I can do ACCST 900mhz.The x20(and x18)does not seem to talk correctly to the module as when bind is selected,even though ETHOS says "binding" the red light wont flash and it thus wont bind to my R9 Stab receiver.
I have confirmed the receiver works ok by using my x10 IRSM on ETHOS and an External R9M module on ACCST and this binds fine with no issues at all.

I have tried EU,FCC and FLEX on both the tx module(R9M Lite) and rx(R9 Stab) to fully test it and it still wont bind at all...In comparison I have loaded the R9M with all three as well and this binds with the rx in all Protocols on my X10 IRSM running ETHOS 1.2.8 as well.

I suspect its an ETHOS issue from my extensive test...Thanks...Chris.T

**Comment by bsongis-frsky** [comment]
Have you updated your external module to the latest version?

**Comment by ETHOSWarrier** [comment]
Yes, R9M Lite  updated to 190117 ACCST and rx(R9Stab) to 200727 ACCST from Frsky website latest drivers.And for info my JR module  size  R9M(HORUS x10 IRSM has  EtHOS 1.2.8) has latest firmware of  190117 from Frsky website and this will bind fully with my R9Stab on 200727 firmware as stated above for reference...But my R9M Lite on version 190117 ACCST wont bind at all on any of the 3 protocols  ACCST EU LBT,FLEX or FCC (with the corresponding firmware  region ,fcc/eu/flex etc..on the R9 Stab rx) . And I have tried an X18 and X20 with the same results...red light does not flash for binding and thus wont bind even though ethos says "binding"

Again, for info, my R9M Lite works perfectly on ACCESS on both x18 and x20 with my R9 Stab flashed to ACCESS  v1.3.2

**Comment by us9001** [comment]
> Yes, R9M Lite updated to 190117 ACCST and rx(R9Stab) to 200727 ACCST from Frsky website latest drivers.And for info my JR module size R9M(HORUS x10 IRSM has EtHOS 1.2.8) has latest firmware of 190117 from Frsky website and this will bind fully with my R9Stab on 200727 firmware as stated above for reference...But my R9M Lite on version 190117 ACCST wont bind at all on any of the 3 protocols ACCST EU LBT,FLEX or FCC (with the corresponding firmware region ,fcc/eu/flex etc..on the R9 Stab rx) . And I have tried an X18 and X20 with the same results...red light does not flash for binding and thus wont bind even though ethos says "binding"
> 
> Again, for info, my R9M Lite works perfectly on ACCESS on both x18 and x20 with my R9 Stab flashed to ACCESS v1.3.2
I got a R9M lite too. I am looking for old ACCST firmware V.180625
Do you have a firmware R9M lite for 180625 ACCST?
I want to try my old ACCST receiver.
Thanks

**Comment by mawzthefinn** [comment]
1.4.3 has R9M Lite fixes, please see if this resolves your issue.

**Comment by ETHOSWarrier** [comment]
Thanks  Mawz...no still wont work.With the R9m Lite flashed to ACCST 190117 and either put in my x20,x18(on v1.4.3) or even my Jumper T16 with adapter(tried Opentx 2.3.15 and EDGE TX 2.7.1 and 2.8.0 RC4) ,it still wont flash red to bind with anything. All the software chirps/says binding but the R9M Lite red light just stays red and wont bind to anything)Ironically ETHOS 1.4.3 allows me to flash the R9M Lite with software now,but still wont correctly control the module and bind to anything...very frustrating as I have a few ACCST R9MM rx on ACCST that i want to use for my boats with the Jumper T16 as the TX(my boat tx)

My conclusion is that the R9M Lite  ACCST software does not work at all with the R9M Lite Module. As i said previously, the R9M Lite module works perfectly on ACCESS in my x18 and x20 Tandom TX...very un happy, just saying!

**Comment by bsongis-frsky** [comment]
It works now, including Telemetry

**Comment by ETHOSWarrier** [comment]
Super,was it an ETHOS at fault , or   the actual R9M Lite software, as the module behaves the same with OpenTx and EdgeTx when put in another radio(jumper T16) using a full size module adapter for the R9M Lite?
I could not get the module to go into bind mode with any radio/operating system etc..when on ACCST firmware you see...Chris.
