### ISSUE TITLE
Ethos 1.2.8 calculated sensor change the widget to max value not possible

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#1706]
Tandem X20S Release 1.2.8
I created a calculated sensor for the distance. Source for this is the GPS. On the screen I want to display the current distance and the maximum distance. for the calculated sensor I unfortunately do not have the possibility to change the widget to max value. usually this is possible if you press the widged for a long time. Would it be possible to make this option available for the calculated sensors as well?
![max value calculated sensor](https://user-images.githubusercontent.com/84685639/170541750-16725d4e-8ab2-44da-94da-5669fd97ffd8.jpeg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/173045663-da9bd239-c5c6-47a6-84fd-ecfcbab6e8d3.png)

![image](https://user-images.githubusercontent.com/50834778/173045585-2865eb94-e1b3-4a30-9346-75ba01de392d.png)

**Comment by bluelex73** [comment]
thank you for the quick implementation you do a great job
