### ISSUE TITLE
Trim mix result not showing in home screen

### ISSUE THREAD

**Issue by phaedradg** [FrSkyRC/ETHOS-Feedback-Community#1707]
When I use a trim mix to modify the elevator trim, I don't see the resulting trim change reflected on the trim side bar on the home screen.  The trim value on the home screen doesn't change either.

**Comment by Farabos** [comment]
…..so do i…

**Comment by mawzthefinn** [comment]
The trim display tracks the canned trimmer functions, not the Trim Mixers (which aren’t necessarily used as trims, they have multiple uses as persistent adjusters).

It would be nice if they could be configured, at least when the trim functions are disabled.
