### ISSUE TITLE
Feature request: The ability to create inputs

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#171]
I am using the simulator 1.0.2 to view ETHOS, so apologies if this has already been covered. I could not see anything in the issues.

Using OpenTX, I have found the use of inputs incredibly useful. As a simple example, when creating a pan and tilt setup, I create inputs for the pan and the tilt. Each input has 3 areas it gets the commands from:
- MAX set to 0 weight _this is to ensure a mid position when not in use_
- Trainer input for head tracker
- Slider for control on the transmitter _this is fallen down to if the head tracker is not connected_
Each of these can have their own curves to make sure that they work within physical limits. They could also have their own expos and speeds, to ensure a smooth operation. When it comes to the mixer, I just use the pan or tilt input. However, on the mix I can use a separate curve that sets the centre point and extreme limits of the servo. This system works great, and is highly configurable.

Another example would be the guy who wanted the 6 way buttons to act like the rotary pot. This could be done easily by creating an input, and wouldn't clutter up the mixer screen.

**Comment by bsongis-frsky** [comment]
You may do exactly the same with unused channels!

**Comment by bsongis-frsky** [comment]
Please explain the scenario you need so that we can find the best solution

**Comment by strgaltdel** [comment]
just my 2cents:

a distinction between inputs & mixers leads in some cases to a clearer / unique data flow

It's very useful whenever the "encoder" of a control function changes, 
or several curves / offsets etc are used, depending on switch positions,
or a single control function controls several mixers.
(Input "aileron" routed to >> aileron, butterfly and flaperon)

attached a sample, where Motor control changes between a switch and stick,
another example shows the use of different curves / offsets within on FP dependent on switch positions

regards
Udo


Motor;
![Motor](https://user-images.githubusercontent.com/20392683/117621940-64c5ba00-b172-11eb-9e73-b7f0d9c5172b.jpg)

Offsets/curves
![curves](https://user-images.githubusercontent.com/20392683/117621957-68594100-b172-11eb-8701-786445e69e28.jpg)

**Comment by bsongis-frsky** [comment]
you can do exactly the same with mixes
the trainer issue related above is fixed in 1.0.10

**Comment by strgaltdel** [comment]
Ich kehre zurück am 28.06.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] Feature request: The ability to create inputs (#171)" gesendet am
18.06.2021 15:53:02.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by bsongis-frsky** [comment]
Si ça continue je vais parler français ;)

**Comment by strgaltdel** [comment]
Ich kehre zurück am 28.06.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] Feature request: The ability to create inputs (#171)" gesendet am
18.06.2021 18:55:25.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by loetefix** [comment]
Arnold Schwarzenegger (terminator) say it too.....i will be back😂

**Comment by strgaltdel** [comment]
Ich kehre zurück am 28.06.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] Feature request: The ability to create inputs (#171)" gesendet am
18.06.2021 20:18:26.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.
