### ISSUE TITLE
Model Bitmap Widget

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#1711]
Hello Mr Songis.
Thank you to you and your whole team for your very good work on ethos.
I have a request. For the moment, when they have chosen the photo of the model in (models edition) it does not appear. It is a pity because the name of the model is often truncated due to lack of letters. not sure to select the right one. In addition, you can have two models with the same name but different colors....etc....in short, could you please show the photo of the selected model on this page? ? (It appears in file..models.....see attached photos.)
Thanks in advance, Robert R.
Sorry for my failing English.
![vue fichier](https://user-images.githubusercontent.com/82876308/170993016-5ad03c12-299d-4328-86f5-172e101f5d5e.jpg)
![editer mod](https://user-images.githubusercontent.com/82876308/170993082-f74bb31c-2e2a-4393-bb22-f8ee676e1dfa.jpg)

**Comment by JacJOW** [comment]
Dear mr Songis,
 I also agree to the request of Robert,
I think it's very interesting, would you please give a look to this ?
JacJOW

**Comment by CoyotteDundee** [comment]
Hello All,
I believe too this could help user to choose with better precision the picture they want for a model.
By the way, thanks for the phenomenal  work done with Ethos !

**Comment by aeroplanebelg** [comment]
![editer mod](https://user-images.githubusercontent.com/82876308/173097664-16eaf42d-e2a4-47e5-9e2e-59b31d9768c4.png)
here, it would look like this in model edition

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/173368373-8e45c16c-35ee-49dc-9330-22a5133bf209.png)

**Comment by bsongis-frsky** [comment]
Reused in Wizard:

![image](https://user-images.githubusercontent.com/50834778/173368645-da2f7e67-380d-48f2-b82d-4570fb911c6b.png)

**Comment by CoyotteDundee** [comment]
Woaw...
That's reactivity ! 
Thanks a lot Bertrand  !
