### ISSUE TITLE
Ethos SUITE 1.2.9 not quitting

### ISSUE THREAD

**Issue by camber2** [FrSkyRC/ETHOS-Feedback-Community#1712]
Mac 10.13.6 High Sierra
Ethos Suite 1.2.9

Was on Ethos Suite 1.2.8
Clicked on update all. Beginning of flash went well (I then saw the drives get **unmounted** by ethos suite). 
Just prior to flashing bootloader the Mac showed both discs not ejected properly. But it continued and flashed the bootloader. The X18 then showed USB icon on display. I unplugged the X18 and all good. **But still had to force quit Ethos 1.2.9**
I opened Ethos suite and then tried to QUIT and it won't. Had to force quit. Tried twice

**Update:** 
From Ethos Suite. Plugged in X18 bootloader. Clicked on eject drives and they do unmount from Mac. Ethos Suite stays hung up. X18 display shows **USB connected** (did not see USB icon this time). Waited 30 seconds and had to force quit Ethos suite again while USB connected. X18 display went to USB connected. No damage or disk not properly ejected.

**Comment by MIKE-DAILEY** [comment]
Latest Release: Release 1.2.9. .

Please see "In progress, please wait ..." on SUITE Update News screen.

**Comment by camber2** [comment]
Please see "In progress, please wait ..." on SUITE Update News screen.
Never clicked on UPDATE NEWS before. I'll try again tomorrow.
