### ISSUE TITLE
Read the hour value

### ISSUE THREAD

**Issue by GiorgioCirelli** [FrSkyRC/ETHOS-Feedback-Community#1713]
Go you think it is possible to add the current time to the system values ​​to be read by the radio using a function?

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/172893475-ac282a8a-4575-4835-9038-03093ef468d0.png)

**Comment by bsongis-frsky** [comment]
Adding a way to have:
- the clock displayed as a widget
- the clock read in PlayValue
- the clock comparaison in Logic Switches (so you can setup an alarm when it's time to return home)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/173007331-7259c700-8de6-49ce-b00a-8b51dcb3118d.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/173009342-ce511e93-96e7-4043-b280-e8f155c6659c.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/173009726-edb1f179-8b6d-4b76-82f0-21dc0278f70b.png)

**Comment by bsongis-frsky** [comment]
And the original request :)

![image](https://user-images.githubusercontent.com/50834778/173033856-8482d860-f581-4da3-a171-9081cf810b48.png)

**Comment by GiorgioCirelli** [comment]
You outdid yourself!
You have accomplished much more than I expected.
Thank you
