### ISSUE TITLE
Issue with TD Rx redundancy and telemetry

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1714]
This issue is not entirely ETHOS related, its on the line between TD and Ethos. but might be solvable in Ethos.
using X20S 1.2.8 and two TD MX Rxs fw 1.0.7.
Rx0 is connected via S.port to external telemetry sensors.
Rx1 is not connected to sensors.

regardless of Rx1 settin "Telemetry Disabled" (Yes/No), Ethos sometimes picks up telemetry from Rx1 (as indicated in telemetry menu Rx = 1) and then no external S,port sensors data are coming in.

how can we fix this?
1. is this an issue with TD fw (ISRM / Rx)?
2. perhaps Ethos can default to a certain predefined Rx?
3. if Rx1 is set to Telemetry off, why does Ethos try to grab telemetry from it sometimes? this does not make sense.
4. should the external S.port sensors be parallel connected to Rx0 S,port and Rx1 S,port?

please advise.
thanks.

**Comment by bsongis-frsky** [comment]
Not an Ethos issue

**Comment by i3dm** [comment]
> Not an Ethos issue. Forwarded to the RF team

thanks but lets say for example if Ethos had configurable Rx priority (or at least default) - how nice would that be? :)

**Comment by Adelaxie** [comment]
if Rx1 is set to Telemetry off, why does Ethos try to grab telemetry from it sometimes? this does not make sense.
---if one Rx is disabled, another one would be named rx0.
should the external S.port sensors be parallel connected to Rx0 S,port and Rx1 S,port?
---to connect the two s.port together can provide the external sensor always there. so yes for your usage.

**Comment by bsongis-frsky** [comment]
> 
> lets say for example if Ethos had configurable Rx priority (or at least default) - how nice would that be? :)

What would Ethos do with a Rx priority? 
Ethos just displays what is received from the module, nothing more.

**Comment by i3dm** [comment]
> > lets say for example if Ethos had configurable Rx priority (or at least default) - how nice would that be? :)
> 
> What would Ethos do with a Rx priority? Ethos just displays what is received from the module, nothing more.

i see.
so ethos is not exposed to Rx choice in any way?

**Comment by mawzthefinn** [comment]
That's correct, the RX choice is managed by the RF module and receiver.

**Comment by i3dm** [comment]
> That's correct, the RX choice is managed by the RF module and receiver.
> 
> FYI, this issue exists in ACCESS as well, and is present on FrOS, OpenTX, EdgeTX and ErskyTX as a result.

i disagree, i have dont it many times with ACCESS and ACCST successfully.
any time i used "telemetry off" in ACCESS that Rx would never send telemetry so the RF module never "caught" to it.
with TD seems like "telemetry off" setting does not work?

**Comment by mawzthefinn** [comment]
> > That's correct, the RX choice is managed by the RF module and receiver.
> > FYI, this issue exists in ACCESS as well, and is present on FrOS, OpenTX, EdgeTX and ErskyTX as a result.
> 
> i disagree, i have done it many times with ACCESS and ACCST successfully. any time i used "telemetry off" in ACCESS that Rx would never send telemetry so the RF module never "caught" to it. with TD seems like "telemetry off" setting does not work?

That’s not it working successfully, that’s you overriding telemetry failover by forcing your secondary RX to no telemetry, which TANDEM receivers do not appear to respect. ACCESS has a workaround for  the issue, TANDEM currently does not.

The issue with inconsistent primary telemetry receiver selection exists in ACCESS too, it doesn’t  in ACCST because ACCST does not support more than a single telemetry source so you HAVE to disable telemetry on the redundant receiver.

**Comment by i3dm** [comment]
now we are to the point.
tandem Rxs do not follow "telemetry off" setting

**Comment by i3dm** [comment]
> now we are to the point. tandem Rxs do not follow "telemetry off" setting

i found my buddy was using TDMX 1.0.6 
that may explain the issues. we will do further testing on 1.0.7

**Comment by i3dm** [comment]
v1.0.7 works as expected, closing the issue.
