### ISSUE TITLE
1.2.10 fw cant be picked in suite

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1715]
suite 1.2.10
X18 connected with 1.2.8 
i can not pick 1.2.10 from the menu, any other version picks fine, but clicking on 1.2.10 does not pick it (dot is greyed out).

![image](https://user-images.githubusercontent.com/8968780/171993020-a3a64838-de8c-40fd-9d90-9790e839b75d.png)

**Comment by EthosUser** [comment]
Same on x20

**Comment by OldGazer** [comment]
I had to do the update manually like before Suite was released.

**Comment by MIKE-DAILEY** [comment]
Should work now.  It was a system related issue not SUITE itself.

**Comment by MIKE-DAILEY** [comment]
> I had to do the update manually like before Suite was released.

1.2.10. has changes to the radio bootloader, firmware and SUITE.  Because all three were changed it is best to manually update the radio bootloader and firmware before using SUITE.

**Comment by Nerenye** [comment]
so suite is basically useless... why not doing a staged release? Release bootloader update to old suite after new bootloader is found pull suite update and rollout the fw over new suite. 
Releasing a new tool like suite and breaking it with BL changes is bad practice

**Comment by bsongis-frsky** [comment]
> so suite is basically useless... why not doing a staged release? Release bootloader update to old suite after new bootloader is found pull suite update and rollout the fw over new suite. Releasing a new tool like suite and breaking it with BL changes is bad practice

Suite will update all your components one by one automatically. In case of failure, it will help you to do it manually, but it should not be needed in 99% cases
