### ISSUE TITLE
German Customer Sounds with original ETHOS Voice

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1716]
The German sound files delivered with the ETHOS releases are very good in my opinion, as far as the sound quality goes. Andreas Engel told me that they are generated using the Google TTS API, so I used the Google demo to check and could indeed identify the voice used for the German ETHOS files. It is possible to register for a test version of the Google TTS API, but you have to enter your credit card number, even if it is not charged. For now, I don't want to do this.
Is there any chance to generate a list of customer defined phrases, for inclusion in future ETHOS releases as part of the German sound pack. That list could be populated with inputs from GitHub and maintained as part of the ETHOS configuration. I am aware that there would have to be some sort of control concerning the number of such sound files, in order to avoid that this grows into a monster. Furthermore, the same desire might arise for other languages, which would obviously further increase the effort.

**Comment by bsongis-frsky** [comment]
The service is not free for FrSky as well!

**Comment by bsongis-frsky** [comment]
The list of customer defined phrases will increase more & more, it will be never finished. Multiplied by the count of languages, it would cost too much to FrSky in time, energy and money.

I think you may use the demo from Google for free, and download the wav files from there. It should be enough to create all your needed custom prompts.
