### ISSUE TITLE
hebrew bug

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1717]
1.2.8 (and all versions)
in hebrew, bound Rx names dont appear.
only:
Rx1
Rx2
Rx3
appears. not no Rx names.
![image](https://user-images.githubusercontent.com/8968780/172176128-760deecc-832e-44b8-8a86-831634ba4cae.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/172563386-23063407-dfe5-4606-a631-acd4ff7a4898.png)

**Comment by i3dm** [comment]
looks good

**Comment by i3dm** [comment]
where can i find the hebrew file for 1.2.10? id like to update it

**Comment by i3dm** [comment]
for some reason im seeing the 3 Rxs in a staggered on the screen
![image](https://user-images.githubusercontent.com/8968780/176478219-33e354ff-07ad-4369-9bd3-ec7bb74bc20d.png)
