### ISSUE TITLE
FrSky MLVSS sporadically not working

### ISSUE THREAD

**Issue by RoP09** [FrSkyRC/ETHOS-Feedback-Community#1718]
The MLVSS LiPo sensor sporadically does not send any telemetry data. I have to plug it off/on several times to get it working finally.

Latest firmware in RX (S8R) and MLVSS + X20S 1.2.10 is installed.

Issue did not occur on OTX or older FW versions of Ethos.

**Comment by bsongis-frsky** [comment]
Forwarded. If you make it work again by pluging it off / on, it shouldn't be an Ethos issue

**Comment by Adelaxie** [comment]
How is the LED state on the sensor when connected but not working?
![image](https://user-images.githubusercontent.com/6251929/172573048-47513b2f-ac7d-40e7-b963-8f6a80ec0c02.png)

**Comment by j-watkiss** [comment]
Do you have a redundant receiver?
If so may be related to #1714
You can parallel your smart port sensors to both RX

**Comment by i3dm** [comment]
> Do you have a redundant receiver? If so may be related to #1714 You can parallel your smart port sensors to both RX

thats my bet as well

**Comment by mawzthefinn** [comment]
Are you still having issues on current firmware (1.4.3)?

**Comment by bsongis-frsky** [comment]
Please upgrade your FLVSS
