### ISSUE TITLE
Feature request: Global Variables

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#172]
I am using the simulator 1.0.2 to view ETHOS, so apologies if this has already been covered. I could not see anything in the issues.

Please add the ability to create global variables, and manipulate them with special functions. There are many programming tasks where these are extremely useful, if not a necessity.

**Comment by MIKE-DAILEY** [comment]
Global variables currently exist and are named "Var" in the Mixer Library.  There is a new 1.0.4. simulator here https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release%2F1.0.4

**Comment by MrD-RC** [comment]
There seems to be no way to manipulate the vars though. It would be great to get the ability to set the value as well as increase or decrease by a value.

**Comment by MIKE-DAILEY** [comment]
You can.

**Comment by hrenz** [comment]
Hy Mike, 
in Your Example 
this are NOT real Globel Variabels, this are kind of primitiv "Inputs" with variable sources settings
Nor more

**Comment by bsongis-frsky** [comment]
@hrenz @MrD-RC please explain the scenario you need, the way it is implemented in Ethos is even more flexible than in opentx, we should be able to provide a solution

**Comment by MrD-RC** [comment]
@bsongis-frsky I don’t think they are more flexible than OpenTX currently. For a start, you can’t specific a minimum or maximum value, and they only seem to be a -100 to 100 range. OpenTX has a range of -1024 to 1024. The -100 to 100 is fine if you only want to manipulate channels. But gvars are used for more than that. 

You also can’t set values to the gvars using special functions. It’s true you can go up and down with the gvars in the current implementation. I actually like how that works. However, there is no scope for setting an explicit value to jump to. It would be great to have the option to set the value of the gvar to X when switch X is activated. Whether this is through special functions, like in OpenTX or by another setting on the mixer page doesn’t really make much difference. The OTX method, you could have multiple switches altering the value. But if it was done in the mix, you’d just need to use logic to combine the switches in to a single logical switch.

**Comment by MrD-RC** [comment]
@bsongis-frsky This morning I had a look at global variables on my X20S, and can confirm that there is a fair bit of functionality missing, that I have used quite a lot on OpenTX. I created this video https://youtu.be/RlSibdYM3TQ

**Comment by MrD-RC** [comment]
@MIKE-DAILEY can you please re-open this issue, because it clearly has not been resolved. Or should I just create a new issue for Global Variables to be able to be used as variables?

**Comment by bsongis-frsky** [comment]
- FALSE => they only seem to be a -100 to 100 range
- FALSE, just use a REPLACE mix => there is no scope for setting an explicit value to jump to
- ALREADY POSSIBLE with a REPLACE MIX => It would be great to have the option to set the value of the gvar to X when switch X is activated
- ALREADY POSSIBLE (with the TRIM MIX => nor increase or decrease the value

I don't think Ethos can do less than OpenTX for those global variables

**Comment by loetefix** [comment]
The trim mix is realy nice except it isn't flightmode depent.

**Comment by MrD-RC** [comment]
Firstly, actually it’s TRUE

![E58F6F64-3BE8-40C6-91B2-811964292B5B](https://user-images.githubusercontent.com/17590174/120069845-eb89fa80-c07f-11eb-9ac2-b27ee64544be.jpeg)

The trim mix is also no good. It only increased or decreases the value by 1. I tried different trim modes, but they always adjust by 1. 

Having all these different trims to change what is supposed to be a variable is really unintuitive.  

But if everything can be done with ETHOS in it’s current state, I’d appreciate a video showing an example where:
- on power on the channel is set to -100
- trim up increased the channel by 10%
- trim down decreased the channel by 10%
I just can’t see where to do that anywhere. This was extremely simple in OpenTX.

**Comment by MrD-RC** [comment]
@MIKE-DAILEY care to reply to the above post. I've been playing with ETHOS to try and get this working all evening. But I can't get it to work with the current implementation.
