### ISSUE TITLE
Last Bootloader fail open drives in Linux ubuntu 18.04 on x20s eu 

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#1720]
I have update the bootloader but now when i connect the radio with the pc the sim snd the flash driver are not visibles.
Version 1.2.10, and relative bootloader file
Operating system Ubuntu 18.04
(in the Ubuntu 20.04 work properly)
Is possible to re-charge the old bootloader version 1.0? where can I find it?

**Comment by bsongis-frsky** [comment]
Here I always flash from Linux (Manjaro), and it's perfectly working. Also you mention it's OK on Ubuntu 20.04
I am not sure it's a problem in Ethos then, but rather something in your Ubuntu 18.04 (udev rules?)
Please paste here the result of `dmesg`, I will try to help

**Comment by carlogianneschi** [comment]
Hello Bertrand,

I don't have idea but now the connection work perfectly.

I think is a computer problem, this morning I have installed the new kernel!

**Comment by bsongis-frsky** [comment]
I think we are borderline with the consumption. I think that sometimes your computer decides to cut the line ...

**Comment by carlogianneschi** [comment]
Before writing the tread I tried on three different computers, two with 
ubuntu 18.04 and one with ubuntu 20.04.
On those with 18.04 it didn't work, then updated the kernel everything 
was fine.

Il 09/06/22 08:26, Bertrand Songis @ FrSky ha scritto:

**Comment by carlogianneschi** [comment]
Hello, few news: linux kernek new release and the problem is reopen.
see the dmesg log : 


[   24.243224] usb 1-4: new full-speed USB device number 5 using xhci_hcd
[   24.393273] usb 1-4: New USB device found, idVendor=0483, idProduct=5750, bcdDevice= 2.00
[   24.393282] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   24.393287] usb 1-4: Product: FrSky X20S Interface
[   24.393291] usb 1-4: Manufacturer: FrSky
[   24.393294] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[   24.397394] hid-generic 0003:0483:5750.0003: hiddev0,hidraw2: USB HID v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1
[   24.411530] usb-storage 1-4:1.0: USB Mass Storage device detected
[   24.411774] scsi host2: usb-storage 1-4:1.0
[   24.411934] usbcore: registered new interface driver usb-storage
[   24.414382] usbcore: registered new interface driver uas
[   25.416355] scsi 2:0:0:0: Direct-Access     FrSky    X20              0.01 PQ: 0 ANSI: 2
[   25.416763] scsi 2:0:0:1: Direct-Access     FrSky    X20              0.01 PQ: 0 ANSI: 2
[   25.417668] sd 2:0:0:0: Attached scsi generic sg1 type 0
[   25.418191] sd 2:0:0:0: [sdb] 2049 4096-byte logical blocks: (8.39 MB/8.00 MiB)
[   25.418434] sd 2:0:0:1: Attached scsi generic sg2 type 0
[   25.418450] sd 2:0:0:0: [sdb] Write Protect is off
[   25.418460] sd 2:0:0:0: [sdb] Mode Sense: 22 00 00 00
[   25.418975] sd 2:0:0:1: [sdc] 7864320 512-byte logical blocks: (4.03 GB/3.75 GiB)
[   25.419232] sd 2:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[   25.419526] sd 2:0:0:1: [sdc] Write Protect is off
[   25.419536] sd 2:0:0:1: [sdc] Mode Sense: 22 00 00 00
[   25.419774] sd 2:0:0:1: [sdc] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[   25.456110]  sdb: sdb1
[   25.462959]  sdc: sdc1
[   25.485707] sd 2:0:0:1: [sdc] Attached SCSI removable disk
[   25.486235] sd 2:0:0:0: [sdb] Attached SCSI removable disk
[   27.635611] FAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   28.706188] FAT-fs (sdc1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   75.475123] ACPI BIOS Error (bug): AE_AML_PACKAGE_LIMIT, Index (0x0000000FF) is beyond end of object (length 0xF) (20190816/exoparg2-396)
[   75.475146] No Local Variables are initialized for Method [GINF]
[   75.475148] Initialized Arguments for Method [GINF]:  (2 arguments defined for method invocation)
[   75.475148]   Arg0:   00000000dd7bf128 <Obj>           Integer 00000000000000FF
[   75.475152]   Arg1:   0000000001dbcfb6 <Obj>           Integer 0000000000000000
[   75.475157] ACPI Error: Aborting method \_SB.GINF due to previous error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475162] ACPI Error: Aborting method \_SB.GADR due to previous error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475166] ACPI Error: Aborting method \_SB.SGOV due to previous error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475171] ACPI Error: Aborting method \_SB.CGWR due to previous error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475175] ACPI Error: Aborting method \_SB.TBFP due to previous error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475179] ACPI Error: Aborting method \_SB.WMTF.WMTF due to previous error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.488559] blk_update_request: I/O error, dev sdb, sector 520 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.488565] Buffer I/O error on dev sdb1, logical block 2, lost async page write
[   75.565828] blk_update_request: I/O error, dev sdc, sector 8193 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565835] Buffer I/O error on dev sdc1, logical block 1, lost async page write
[   75.565845] blk_update_request: I/O error, dev sdc, sector 460352 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565847] Buffer I/O error on dev sdc1, logical block 452160, lost async page write
[   75.565866] blk_update_request: I/O error, dev sdc, sector 460429 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565869] Buffer I/O error on dev sdc1, logical block 452237, lost async page write
[   75.565876] blk_update_request: I/O error, dev sdc, sector 460440 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565877] Buffer I/O error on dev sdc1, logical block 452248, lost async page write
[   75.565883] blk_update_request: I/O error, dev sdc, sector 460444 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565885] Buffer I/O error on dev sdc1, logical block 452252, lost async page write
[   92.289083] usb 1-4: USB disconnect, device number 5
[   97.772926] usb 1-4: new full-speed USB device number 6 using xhci_hcd
[   97.923526] usb 1-4: New USB device found, idVendor=0483, idProduct=5750, bcdDevice= 2.00
[   97.923535] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   97.923540] usb 1-4: Product: FrSky X20S Interface
[   97.923544] usb 1-4: Manufacturer: FrSky
[   97.923547] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[   97.926148] usb-storage 1-4:1.0: USB Mass Storage device detected
[   97.926709] scsi host2: usb-storage 1-4:1.0
[   97.928424] hid-generic 0003:0483:5750.0004: hiddev0,hidraw2: USB HID v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1
[  207.087542] usb 1-4: USB disconnect, device number 6
[  215.920404] usb 1-4: new full-speed USB device number 7 using xhci_hcd
[  216.071138] usb 1-4: New USB device found, idVendor=0483, idProduct=5750, bcdDevice= 2.00
[  216.071147] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  216.071152] usb 1-4: Product: FrSky X20S Interface
[  216.071156] usb 1-4: Manufacturer: FrSky
[  216.071159] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[  216.073702] usb-storage 1-4:1.0: USB Mass Storage device detected
[  216.074198] scsi host2: usb-storage 1-4:1.0
[  216.076405] hid-generic 0003:0483:5750.0005: hiddev0,hidraw2: USB HID v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1
[  258.613766] usb 1-4: USB disconnect, device number 7
[  272.188837] usb 1-4: new full-speed USB device number 8 using xhci_hcd
[  272.339455] usb 1-4: New USB device found, idVendor=0483, idProduct=5750, bcdDevice= 2.00
[  272.339463] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  272.339468] usb 1-4: Product: FrSky X20S Interface
[  272.339472] usb 1-4: Manufacturer: FrSky
[  272.339475] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[  272.342092] usb-storage 1-4:1.0: USB Mass Storage device detected
[  272.343028] scsi host2: usb-storage 1-4:1.0
[  272.344981] hid-generic 0003:0483:5750.0006: hiddev0,hidraw2: USB HID v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1

**Comment by carlogianneschi** [comment]
New kenel and new problems.
Now the problem is come away.

See the latest dmesg


---------------------------


[   24.243224] usb 1-4: new full-speed USB device number 5 using xhci_hcd
[   24.393273] usb 1-4: New USB device found, idVendor=0483, 
idProduct=5750, bcdDevice= 2.00
[   24.393282] usb 1-4: New USB device strings: Mfr=1, Product=2, 
SerialNumber=3
[   24.393287] usb 1-4: Product: FrSky X20S Interface
[   24.393291] usb 1-4: Manufacturer: FrSky
[   24.393294] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[   24.397394] hid-generic 0003:0483:5750.0003: hiddev0,hidraw2: USB HID 
v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1
[   24.411530] usb-storage 1-4:1.0: USB Mass Storage device detected
[   24.411774] scsi host2: usb-storage 1-4:1.0
[   24.411934] usbcore: registered new interface driver usb-storage
[   24.414382] usbcore: registered new interface driver uas
[   25.416355] scsi 2:0:0:0: Direct-Access     FrSky X20              
0.01 PQ: 0 ANSI: 2
[   25.416763] scsi 2:0:0:1: Direct-Access     FrSky X20              
0.01 PQ: 0 ANSI: 2
[   25.417668] sd 2:0:0:0: Attached scsi generic sg1 type 0
[   25.418191] sd 2:0:0:0: [sdb] 2049 4096-byte logical blocks: (8.39 
MB/8.00 MiB)
[   25.418434] sd 2:0:0:1: Attached scsi generic sg2 type 0
[   25.418450] sd 2:0:0:0: [sdb] Write Protect is off
[   25.418460] sd 2:0:0:0: [sdb] Mode Sense: 22 00 00 00
[   25.418975] sd 2:0:0:1: [sdc] 7864320 512-byte logical blocks: (4.03 
GB/3.75 GiB)
[   25.419232] sd 2:0:0:0: [sdb] Write cache: disabled, read cache: 
enabled, doesn't support DPO or FUA
[   25.419526] sd 2:0:0:1: [sdc] Write Protect is off
[   25.419536] sd 2:0:0:1: [sdc] Mode Sense: 22 00 00 00
[   25.419774] sd 2:0:0:1: [sdc] Write cache: disabled, read cache: 
enabled, doesn't support DPO or FUA
[   25.456110]  sdb: sdb1
[   25.462959]  sdc: sdc1
[   25.485707] sd 2:0:0:1: [sdc] Attached SCSI removable disk
[   25.486235] sd 2:0:0:0: [sdb] Attached SCSI removable disk
[   27.635611] FAT-fs (sdb1): Volume was not properly unmounted. Some 
data may be corrupt. Please run fsck.
[   28.706188] FAT-fs (sdc1): Volume was not properly unmounted. Some 
data may be corrupt. Please run fsck.
[   75.475123] ACPI BIOS Error (bug): AE_AML_PACKAGE_LIMIT, Index 
(0x0000000FF) is beyond end of object (length 0xF) (20190816/exoparg2-396)
[   75.475146] No Local Variables are initialized for Method [GINF]
[   75.475148] Initialized Arguments for Method [GINF]:  (2 arguments 
defined for method invocation)
[   75.475148]   Arg0:   00000000dd7bf128 <Obj> Integer 00000000000000FF
[   75.475152]   Arg1:   0000000001dbcfb6 <Obj> Integer 0000000000000000
[   75.475157] ACPI Error: Aborting method \_SB.GINF due to previous 
error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475162] ACPI Error: Aborting method \_SB.GADR due to previous 
error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475166] ACPI Error: Aborting method \_SB.SGOV due to previous 
error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475171] ACPI Error: Aborting method \_SB.CGWR due to previous 
error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475175] ACPI Error: Aborting method \_SB.TBFP due to previous 
error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.475179] ACPI Error: Aborting method \_SB.WMTF.WMTF due to 
previous error (AE_AML_PACKAGE_LIMIT) (20190816/psparse-531)
[   75.488559] blk_update_request: I/O error, dev sdb, sector 520 op 
0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.488565] Buffer I/O error on dev sdb1, logical block 2, lost async 
page write
[   75.565828] blk_update_request: I/O error, dev sdc, sector 8193 op 
0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565835] Buffer I/O error on dev sdc1, logical block 1, lost async 
page write
[   75.565845] blk_update_request: I/O error, dev sdc, sector 460352 op 
0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565847] Buffer I/O error on dev sdc1, logical block 452160, lost 
async page write
[   75.565866] blk_update_request: I/O error, dev sdc, sector 460429 op 
0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565869] Buffer I/O error on dev sdc1, logical block 452237, lost 
async page write
[   75.565876] blk_update_request: I/O error, dev sdc, sector 460440 op 
0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565877] Buffer I/O error on dev sdc1, logical block 452248, lost 
async page write
[   75.565883] blk_update_request: I/O error, dev sdc, sector 460444 op 
0x1:(WRITE) flags 0x0 phys_seg 1 prio class 0
[   75.565885] Buffer I/O error on dev sdc1, logical block 452252, lost 
async page write
[   92.289083] usb 1-4: USB disconnect, device number 5
[   97.772926] usb 1-4: new full-speed USB device number 6 using xhci_hcd
[   97.923526] usb 1-4: New USB device found, idVendor=0483, 
idProduct=5750, bcdDevice= 2.00
[   97.923535] usb 1-4: New USB device strings: Mfr=1, Product=2, 
SerialNumber=3
[   97.923540] usb 1-4: Product: FrSky X20S Interface
[   97.923544] usb 1-4: Manufacturer: FrSky
[   97.923547] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[   97.926148] usb-storage 1-4:1.0: USB Mass Storage device detected
[   97.926709] scsi host2: usb-storage 1-4:1.0
[   97.928424] hid-generic 0003:0483:5750.0004: hiddev0,hidraw2: USB HID 
v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1
[  207.087542] usb 1-4: USB disconnect, device number 6
[  215.920404] usb 1-4: new full-speed USB device number 7 using xhci_hcd
[  216.071138] usb 1-4: New USB device found, idVendor=0483, 
idProduct=5750, bcdDevice= 2.00
[  216.071147] usb 1-4: New USB device strings: Mfr=1, Product=2, 
SerialNumber=3
[  216.071152] usb 1-4: Product: FrSky X20S Interface
[  216.071156] usb 1-4: Manufacturer: FrSky
[  216.071159] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[  216.073702] usb-storage 1-4:1.0: USB Mass Storage device detected
[  216.074198] scsi host2: usb-storage 1-4:1.0
[  216.076405] hid-generic 0003:0483:5750.0005: hiddev0,hidraw2: USB HID 
v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1
[  258.613766] usb 1-4: USB disconnect, device number 7
[  272.188837] usb 1-4: new full-speed USB device number 8 using xhci_hcd
[  272.339455] usb 1-4: New USB device found, idVendor=0483, 
idProduct=5750, bcdDevice= 2.00
[  272.339463] usb 1-4: New USB device strings: Mfr=1, Product=2, 
SerialNumber=3
[  272.339468] usb 1-4: Product: FrSky X20S Interface
[  272.339472] usb 1-4: Manufacturer: FrSky
[  272.339475] usb 1-4: SerialNumber: 㘳䄶㐳㔷ㄳ〳
[  272.342092] usb-storage 1-4:1.0: USB Mass Storage device detected
[  272.343028] scsi host2: usb-storage 1-4:1.0
[  272.344981] hid-generic 0003:0483:5750.0006: hiddev0,hidraw2: USB HID 
v1.11 Device [FrSky FrSky X20S Interface] on usb-0000:00:14.0-4/input1


-----------------------------------------------------------------

Il 08/06/22 08:28, Bertrand Songis @ FrSky ha scritto:
