### ISSUE TITLE
VFR Low warnings after upgrade

### ISSUE THREAD

**Issue by phazeman** [FrSkyRC/ETHOS-Feedback-Community#1721]
I started to get "Low VFR" warning after upgrading to 1.2.8
no changes were done to the setup on the planes but the warnings are coming from time to time
X20S

**Comment by bsongis-frsky** [comment]
I cannot see how it can be an Ethos issue, is it easy to reproduce on ground?

**Comment by bsongis-frsky** [comment]
Perhaps you upgraded your audio pack recently and the file was not there before?

**Comment by Adelaxie** [comment]
Can you try to flashback to the old version to see?
Radio firmware should not be related...
or to provide more info about your setup/planes, please?

**Comment by phazeman** [comment]
My setup is 
X20S (TD-ISRM 2.2.1), R8 Pro (FW 2.1.0), R9 Slim+ OTA, Archer RS
Archer  RS connected to R8 Pro that is connected to RX1 of AR SF16
R9 Slim+ OTA is connected to RX2 of AR SF16

1. no changes were made to the plane setup nor radio firmware upgrade. only Ethos upgrade
2. issue is easily reproduced on the ground and i am not the only one with it in our local air field (at least 3 more people) after the same upgrade
3. i've been flying with 1.1.4 for at least 1.5 months and never had that warning
4. this is my main TX and i fly all my jets and gas models with it so i would prefer not to play with the firmware on it so it stays stable as much as possible
5. about that sound file - this is possible and very easy to check. only have to check the EN audio folder for 1.1.4 to see if it's there

**Comment by phazeman** [comment]
Flight 1
![image](https://user-images.githubusercontent.com/55709534/172558859-9346a03e-17cd-4a40-8870-4c8255ef7815.png)

Flight 2
![image](https://user-images.githubusercontent.com/55709534/172559022-22a0298e-e8ff-40e0-92f6-dc01294cffa1.png)

As you can see - the only "hiccup"  as at the beginning of the first flight until receivers connected (as i understand)

**Comment by phazeman** [comment]
Here is another plane with TD-R10 in it in Tandem mode. looks like the 2.4 is dropping at the beginning until both are connected
![image](https://user-images.githubusercontent.com/55709534/172560197-69e747cc-4596-4b7d-8f42-366c046351bb.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/172566835-c34f27ea-164f-4c24-ac76-07cd1ff270e2.png)

**Comment by phazeman** [comment]
@bsongis-frsky exactly ! the question is - why is it happening now and wasn't happening before ?

**Comment by philandroid36** [comment]
I had this weekend the same problem just after the 2.1.8 update.  I did a reset of the receiver and I redid the bind and it was OK then.
X20s and receiver with Last version.

**Comment by Adelaxie** [comment]
> Flight 1 ![image](https://user-images.githubusercontent.com/55709534/172558859-9346a03e-17cd-4a40-8870-4c8255ef7815.png)
> 
> Flight 2 ![image](https://user-images.githubusercontent.com/55709534/172559022-22a0298e-e8ff-40e0-92f6-dc01294cffa1.png)
> 
> As you can see - the only "hiccup" as at the beginning of the first flight until receivers connected (as i understand) as i can see - the orange VFR graph is up to 200 since there are 2 receivers on 2.4 that are reporting (am i right ?)

Hi，@phazeman We are on your reported issue,  why are there VFR = 200 (more than 100%) in your graph? Did you make any changes to the log file?

**Comment by phazeman** [comment]
@Adelaxie looks like it happened because i chose "stacked" graph in excel. this is a regular line
![image](https://user-images.githubusercontent.com/55709534/172809598-69567c73-118b-4b39-a02d-4279f34ac469.png)

**Comment by agrifurb** [comment]
Has a fix been found for this yet?
I've just updated to 2.1.11 and now getting the low VFR warning now.
I have tried a reset of the receiver and I redid the bind and its still the same.
Brand new X20 and R10 Pro receiver with Last version.

**Comment by mawzthefinn** [comment]
Is this still occurring?

**Comment by i3dm** [comment]
> Is this still occurring?

yes it happens on Ethos 1.4.4 and TD-ISRM 2.2.2

**Comment by phazeman** [comment]
confirming - TDR10 happens as well with Ethos 1.4.4 and TD-ISRM 2.2.2
