### ISSUE TITLE
Ethos Suite and Localisation

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1723]
In continue to #1669   - is it possible to make the suite language files in TXT format as part of the Suite installation (like in Ethos)? this would make future updates much simpler.

**Comment by mgsanna** [comment]
I agree the json file is good but not the best way

**Comment by i3dm** [comment]
json is fine. but i dont see it included with every release per language.
so its not good if we need to update it.

**Comment by bsongis-frsky** [comment]
It will be available there, starting with 1.2.11

![image](https://user-images.githubusercontent.com/50834778/172830036-af6001dc-f43c-4721-bdf8-83487e2a447a.png)

**Comment by bsongis-frsky** [comment]
@mgsanna json are the standard for electron apps, we won't reinvent the wheel
