### ISSUE TITLE
1.2.10 Missing "vfr-low-warning.wav" in the german audio pack

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1724]
I noticed that the transmitter does not give a warning when the value falls below the set warning threshold.
When comparing the German audio pack with the English audio pack, I noticed that the file in the German audio pack is missing.

**Comment by bsongis-frsky** [comment]
How do you say that auf Deutsch?

**Comment by Nerenye** [comment]
@bsongis-frsky That would be something like
"vfr niedrig" = vfr low
or
"Achtung VFR Niedrig" = attention vfr low
or if you want a 1 to 1 translation (would never be used in german) that would be
"vfr niedrig warnung"

**Comment by EngelMT** [comment]
STC 148, thanks for help. I am in a hospital and con not work until late next week.
