### ISSUE TITLE
Ethos suite for linux

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#1726]
Hello, is possible to recompile the Ethos suite for linux?

**Comment by bsongis-frsky** [comment]
Which Linux?

**Comment by carlogianneschi** [comment]
Ubuntu

Il 10/06/22 15:31, Bertrand Songis @ FrSky ha scritto:

**Comment by Jamest95max** [comment]
And Linux mint if possible, app image would be the easiest for the user

**Comment by dystechnic** [comment]
Arch Linux please.
But an appimage will do also.

**Comment by CoyotteDundee** [comment]
Hello,
You can add me to the Linux User count...
As a long time OpenTx user, I cannot imagine switch to Ethos without a Linux version of the Ethos Suite :-)
(I just tried the Window$ version under Wine but it crashed at start)
Any version that could be run on latest Mint / Ubuntu will be fine.
Thanks by advance,

Coyotte

**Comment by darkernoise** [comment]
Another request for a deb package of the Ethos Suite.  Linux Mint user here.

**Comment by tysonfromcanada** [comment]
+1 for linux for suite + simulator for some lua scripting work

**Comment by Jamest95max** [comment]
Hello, is there any news on this, ethos suite on linux, are there any developments, unless i have missed something there seems to me no one willing to do this, will i get a reply i really would appreciate one
thanks.

**Comment by bsongis-frsky** [comment]
Duplicate of #1576

**Comment by bytedicer** [comment]
+1 Count me in!

**Comment by elliopitas** [comment]
I am using arch and fedora.
I have the tandem x20R
