### ISSUE TITLE
X20S V1.2.10  Airbreak mixer curve is wrong

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1727]
Mixer Airbrake
the curve is wrong
as it is a pure offset mixer the curve has to be horizontal, as horizontal lines
and not shown as a weighting curve

![2022-06-11_061531](https://user-images.githubusercontent.com/6217896/173172253-d775d3c4-392f-42ef-967f-5f13a764b0b4.jpg)

![2022-06-11_062214](https://user-images.githubusercontent.com/6217896/173172303-b74dff46-b2cd-4f5c-b91f-29a76e6114fd.jpg)

**Comment by hrenz** [comment]
The mixer name is also very confusing
the name is actually wrong
because it is a pure offset addition

and has little to do with an real airbrake mixer

correct would be Offset mixer

please change the name too

**Comment by mawzthefinn** [comment]
This has been addressed. The Airbrake mixer now has the curve display you note and a second version of the mixer has been created which is named Offset. 

This is a normal airbrake mixer for powered aircraft, a variable airbrake can be done with the Butterfly mix.
