### ISSUE TITLE
Request: Switch / Slider Remapping tool

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#1728]
It would be very useful if there were a tool in Ethos, with which you can easily re-map switches / sliders / potentiometers.

This means that everything that, for example, switch SA is attached to in ETHOS can be remapped instantly to, for example, SC, same for potentiometers / sliders.

**Comment by mawzthefinn** [comment]
Yes, this would be great extension of capability. You can get into situations where certain switches are assigned all over the place and that can be a real issue.

It can also be addressed by defensive programming (ie use the switch once for a VAR mix and drive everything off Var mix values) but that can itself get complex quickly.
