### ISSUE TITLE
Special Function, Logs, sticks/Switches//Logic sw turn ON or OFF with rotary or RTN

### ISSUE THREAD

**Issue by DaySpeed955i** [FrSkyRC/ETHOS-Feedback-Community#173]
X12S ETHOS 1.0.4

In Special function, when "Write logs" is selected, if you change the state of the options "Sticks/Pots/Sliders" with "enter" and use the rotary encoder to go down to "Switches", "Switches" will change state too, same with "Logic sw".

If you go down to "Logic sw" change the state of the option with "enter"  and use RTN, the state of "Sticks/Pots/Sliders" and "Switches" will change too.

The state of options should change only when "enter" is pushed.

Thanks.

**Comment by bsongis-frsky** [comment]
Right, a bad copy / paste
