### ISSUE TITLE
Can’t update the firmware of receivers

### ISSUE THREAD

**Issue by marsubilami** [FrSkyRC/ETHOS-Feedback-Community#1730]
https://user-images.githubusercontent.com/107339141/173217390-d2d9f6b5-fee4-4bbe-bb0a-4b696c09b863.mp4

Pls help! I have updated the firmware of my tandem X20S from 1.1.4 to 1.2

Once completed, I tried to update my receivers which are R9-SX and R-XSR but can not. I have tried using both external device (using cable) and OTA. Can someone tell me what is going on? Video is attached.

**Comment by bsongis-frsky** [comment]
You have to go to the System / File Manager, choose a file to flash and flash!

**Comment by marsubilami** [comment]
@bsongis-frsky sure, done that many times. But can not. You can see the vid

**Comment by bsongis-frsky** [comment]
I just checked, the Ethos Suite method + X20S as a proxy works perfectly

**Comment by bsongis-frsky** [comment]
I just checked, the flash from X20S (System / File Manager) works perfectly as well

**Comment by marsubilami** [comment]
Appreciate to check it. Don't know what happen.
Yesterday I tried with other Rx which is R9 Stab, normal to update. Back to R9 SX and R-XSR, failed again ("Data Refused")

**Comment by marsubilami** [comment]
@mawzthefinn No, I did not. That is the original wire from frsky. I did not change anything to it

**Comment by KAID-YANG** [comment]
Try replacing your SD card

**Comment by bsongis-frsky** [comment]
As I tried with another receiver, I now tried flashing one R9-SX and it worked perfectly as for other receivers. I don't think it's an Ethos issue.

**Comment by marsubilami** [comment]
@KAID-YANG I will give it a try and let you know the result. Thanks

**Comment by mawzthefinn** [comment]
@marsubilami Are you still having the issue?
