### ISSUE TITLE
Ethos Improvement of TRIM Mixer

### ISSUE THREAD

**Issue by Tassiesloper** [FrSkyRC/ETHOS-Feedback-Community#1731]
Hi,
New user here.  Hope I am in the right place and doing the right thing...
I recently made the plunge into Ethos, after being a long time user of OpenTx.  Main reason for taking so long to change is/was the lack of Global Variables.  

After much experimentation with Ethos mixers I have managed to reproduce most of the features I used GV's for and even improve some of them.  However I have found an issue, which if resolved would vastly improve the implementation of in-flight adjustments, which is the main thing I used GV's for.

The issue I have is the lack of an Independent Trim per Flight Mode option in the TRIM Mixer.  I feel this would be a relatively easy improvement to implement and request it be considered by the development team.

**Comment by loetefix** [comment]
Dublicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/577

**Comment by Hartinger** [comment]
Hi,
ETHOS 1.2.8 introduced the possibility to activate mixes (incl. the TRIM Mix) in a particular flight mode only. So you could create one TRIM mix per flight mode to fulfil your requirement.

**Comment by Tassiesloper** [comment]
> Dublicate of #577

Thanks, it is a duplicate of one of the five issues raised in #577 which has been active for 11 months.  I still would like to raise it again to get some feedback on whether it is likely to be implemented in the near future. 
 
Using the current Trim Mix to duplicate my OpenTx model setups will require 25 instances of Trim Mix versus 5 instances if the Trim Mix is upgraded to Independent Trim per Flight Mode.  Much simpler to write, debug and maintain.

However on further thought I can see a possible reason why this feature may be undesirable from a firmware programming point of view.  Using the available inbuilt Trims the number of trim values requiring storage in memory is limited and fairly predictable.  The upgraded Trim Mix could could produce a very large and unpredictable number of trim values and introduce problems with memory allocation.
