### ISSUE TITLE
X20S V1.2.10 telemetry option announcements without units.

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1732]
telemetry values please with an option 
Enable announcements without units.
i.e. announce only the numerical value,  no m/s or km/h and so on

**Comment by darkernoise** [comment]
It would be very nice to selectively turn off the units in the announcement of values in order to speed up the announcements.

**Comment by mawzthefinn** [comment]
Yes, this would make a nice change for quick callouts.

**Comment by bsongis-frsky** [comment]
Fixed with #3320
