### ISSUE TITLE
GPS V2 modulo sensor lost  message

### ISSUE THREAD

**Issue by Farabos** [FrSkyRC/ETHOS-Feedback-Community#1734]
Hi, i’ve an X20 with 1.1.1 Ethos FW ( last downliadable from Frsky Website ) TD 2.2.1 and X8R receiver with last FW.
when i attach a V2 GPS sensor e era few senconds sensor lost message appear, the sensor date and time gps have a red dot , hai can i fix it without disable the warning message?
there were other issue with the same problem but no one have a clear solution 
thank you so much for the developer work you are doing.

**Comment by bsongis-frsky** [comment]
You have to use the latest Ethos version which gives you the possibility:
- to configure the GPS data rate
- to configure the Warning delay
