### ISSUE TITLE
1.2.10 Lua title docs / example

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1735]
[Lua] Additional title parameter added when registering a widget to force the widget title ON or OFF

1.2.10 is missing the LUA doc and no example of the above feature - can you add an example? id like to implement that on my widgets.

**Comment by bsongis-frsky** [comment]
Lua doc uploaded to release 1.2.10

**Comment by i3dm** [comment]
![image](https://user-images.githubusercontent.com/8968780/173658633-0de7668e-f4bf-4318-86fe-4f0713d2916a.png)

where is the TITLE documentation?

**Comment by loetefix** [comment]
you only have to add title=false , or title=true in the registerWidget line like this:

system.registerWidget({key="blablabla", name="test", create=create, title=false , event=event, paint=paint, configure=configure, read=read, write=write, wakeup=wakeup})

**Comment by i3dm** [comment]
thank you
