### ISSUE TITLE
radio x10s not showing in ethos suite

### ISSUE THREAD

**Issue by Rinievb** [FrSkyRC/ETHOS-Feedback-Community#1737]
hi , i installed the latest version and bootloader for my radio , 1.2.10  , the radio will show after choosen frsky suite thye files as an usb drive, but in ethos suite the radio  can not be updated , or is not shown , stm driver is installed , it did it once, after that no more

**Comment by bsongis-frsky** [comment]
Which radio, X10S Express? or X10S + ISRM?

**Comment by Rinievb** [comment]
it was the x10s radio with isrm  module. did some investigation , repaired the driver with dfu  driver repair tool, after that it worked. thank you

**Comment by bsongis-frsky** [comment]
Tested here, it works very well with 1.2.11
