### ISSUE TITLE
TD10 telemetry issues with RB-20

### ISSUE THREAD

**Issue by flyboywbl** [FrSkyRC/ETHOS-Feedback-Community#1738]
I am running two TD10 RX's through my RB20 on my P-47.  With telemetry on,  the servos go all chattery and sound like they are trying to center.  They pulse at the same rate as the blue light on the RX's.

if I turn telemetry off on both RX's it goes away.

I pulled out another RB-20 to test. Same issues

I pulled out an RB-10 to test and there was NO issue with telemetry on.

So this leads me to believe that the RB-20 has issues with the TD-10'a telemetry.

I also set up the same RB-20 with an SR10 Pro with telemetry on and the servos were dead quiet. 

I will run telemetry off until fixed or go with R8 Pro and R9MX satellite 

Thanks

-Matt

**Comment by bsongis-frsky** [comment]
I think it's not an Ethos bug, I will forward to the right team

**Comment by flyboywbl** [comment]
Ok, thank you!

-Matt

**Comment by mawzthefinn** [comment]
Closing this old issue off as the bug has been sent over to the correct team now and is not for ETHOS
