### ISSUE TITLE
Include TD ISRM updating in the suite

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#1739]
Hi,
All is in the title ;)

**Comment by i3dm** [comment]
good idea

**Comment by mawzthefinn** [comment]
Still would love to see this in Suite

**Comment by mawzthefinn** [comment]
TD-ISRM updating is in Suite now, in FRSK Flasher. 

#1857 covers additional useful functionality, closing this off in favour of that issue (which covers auto-updating)
