### ISSUE TITLE
Models compatibility with Firmware

### ISSUE THREAD

**Issue by snowroro9x** [FrSkyRC/ETHOS-Feedback-Community#174]
Hello,
I have updated the firmware of my X20 (0.0.17 -> 1.0.4) with the SD-card content.
 but now it is impossible to open my models, a message "INVALID DATA" appears.

So I tried to come back the released FW, and there is a black screen when I try to load a model. (same with the simulator)

Anybody knows the solution please?

Romain,

**Comment by jhammann13** [comment]
Hi look at this:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/37

Please look at the closed issues bevor place an new issue.

**Comment by snowroro9x** [comment]
Ok...
thanks, -> re do all 

I searched before, but not find, maybe I don't use the good word.
