### ISSUE TITLE
RTC change during On and Off switching

### ISSUE THREAD

**Issue by capraf** [FrSkyRC/ETHOS-Feedback-Community#1740]
Firmware: Ethos 1.2.8 and 1.2.10, Hardware: Tandem X20S
The RTC time is reduced during switching on and off the transmitter.
When the transmitter is switched on and off 10 times, the RTC time about 6 seconds too late.
Without switching, the RTC runs correct.

**Comment by bsongis-frsky** [comment]
Did you close this issue on purpose? What was the problem?

**Comment by capraf** [comment]
Hi Bertrand, 

my friends told me, that the text was misleading, because no one
"changed" the RTC. 

The problem is that the RTC loses seconds, if you switch on and off the
Tandem X20 (about 6 seconds while switching the Tandem 10 times on and
off). This is a bug as a RTC should run continuously. 

I will open a clearer issue today. Is this ok for you? 

Thank you and best regards 

Friedhelm 

Am 2022-06-23 08:33, schrieb Bertrand Songis @ FrSky:

> Did you close this issue on purpose? What was the problem? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1740#issuecomment-1164007528
[2]

**Comment by bsongis** [comment]
it's ok
