### ISSUE TITLE
TD receiver not working after 1.2.10 EU update

### ISSUE THREAD

**Issue by 3D-Cat** [FrSkyRC/ETHOS-Feedback-Community#1741]
After updating from 1.2.8 EU to 1.2.10 EU over ETHOS Suite I had problem with TD-Mode. TD-MX and TD-R10 was showing 0 signal for both 2.4 & 900 and backside of the X20S start getting really hot. ACCESS Mode had absolutely no problem.
After downgrading to 1.2.8 both TD-MX and TD R10 worked well. First I did update to 1.2.10 EU with ETHOS Suite and had the same problem again, after manual update to 1.2.10 EU TD-Mode had no issues and worked well. At last I did run only the 1.2.10 EU firmware update from ETHOS Suite, TD-Mode and temperature problem seem to be solved.. 

RF FIRMWARE - TD Module: TD 2.2.1
TD-R10 firmware: v1.0.7
TD-MX firmware: v1.0.7

problem occurred after
- Bootloader updated manually to 1.2.10
- Update to 1.2.10 EU using ETHOS Suite (option: update outdated components) had no issues during update

**Comment by bsongis-frsky** [comment]
- 1.2.10 EU flashed with Suite (then from github) => KO
- 1.2.10 EU (from github) flashed manually => OK
- 1.2.10 EU (from frsky website) flashed manually => OK
Is it right?

**Comment by 3D-Cat** [comment]
I never did flash from FrSky website
I always use github or lately  the suite for my updates
even though successful register and bind what does hot backside of the transmitter (which I never experienced before) and 0 signal strength indicate?

**Comment by KAID-YANG** [comment]
How much power did you set for TD before upgrading?

**Comment by 3D-Cat** [comment]
what you mean by how much power?

**Comment by KAID-YANG** [comment]
I mean what is the power seting of your TD module

**Comment by 3D-Cat** [comment]
Sorry, It was 25mW

**Comment by Zwiebra** [comment]
Is this fixed? Even with the new firmware i can Register and Bind the Receivers but still zero signal.

**Comment by MIKE-DAILEY** [comment]
With a X20S on 1.3.0. FCC with TD-ISRM v2.2.2. testing with the following: 

1. TD-R10 RX on v1.0.7.
2. PWM servo
3. FBUS servo
4. FBUS GPS adv
5. S.port Vari adv

Everything working, control, telemetry, etc.   Geen LED on R-10 on and blinking blue LED. Kind of hard to see the green LED because the blue is so bright.

**Comment by Zwiebra** [comment]
It seemed to be a problem with EU LBT Firmware and old TD-ISRM versions. I couldnt see the new TD-ISRM because the frsky Website was down. I flashed it now and green LED is on and RSSI is 100/100. Thank you.

**Comment by mawzthefinn** [comment]
Closing as per last comment
