### ISSUE TITLE
X10S Express update

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#1742]
After updating from Open TX to Ethos release 1.1.4 than to 1.2.8 and connect radio to windows I show only 1 driver in explorer (SD card content) and no other driver to update my internal RF.

**Comment by MIKE-DAILEY** [comment]
Correct only uses the SD on the X10 and ETHOS. 

*Flashing X10-ISRM*

Copy X10-ISRM firmware to SD card Firmware folder.
Power on system and navigate to firmware file using File Manager.
Long press on firmware file for popup.
Click on "Flash Internal Module.
Flashing process starts with progress bar.
Wait for OK button and click.

**Comment by hershg21** [comment]
Thank You very much.
