### ISSUE TITLE
Virtual Airplane with Simulator

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1743]
Any Chance of adding a virtual airplane/Helo/Quad/Etc. The virtual aircraft would simulate the control surfaces with the programming and help visualize the movements, and then transfer it to the radio. Thanks

**Comment by mawzthefinn** [comment]
@RC-SOAR made the DevSim Lua script for this use

https://rc-soar.com/ethos/scripts/devsim/
