### ISSUE TITLE
Enhancement Request: Channel override special function

### ISSUE THREAD

**Issue by iflyforfood** [FrSkyRC/ETHOS-Feedback-Community#1744]
![image](https://user-images.githubusercontent.com/107880188/174652301-85354808-48f7-435a-9207-755feb73d079.png)

OTX had a simple way to setup, for example, a kill switch where if the switch was in a certain position it would command a fixed channel value (ie -100% on CH3 for throttle kill switch). Unless I'm missing something I'm not seeing an option to do this in ETHOS special functions. Attached screenshot is the OTX companion version example

**Comment by iflyforfood** [comment]
Yeah I did the throttle cut for now but miss the simpler way of doing it as in OTX.

**Comment by Hobby4life** [comment]
> 

You can do throttle cut directly in Throttle mixer.. no need for extra mix.

**Comment by iflyforfood** [comment]
> You can do throttle cut directly in Throttle mixer.. no need for extra mix.


Right, again, I was just using the throttle cut as an example. There's plenty other functions that the override function could be used for as implemented in OTX.

**Comment by i3dm** [comment]
i agree its useful.
the way i do it now is how i described above with REPLACE.

**Comment by i3dm** [comment]
> duplicate of #525

there is no solution to #525 either
