### ISSUE TITLE
no source returns "---" instead of nil

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1745]
1.2.8 LUA
in X20S:
Current = system.getSource (RDT_Currsource)
if no current sensor chosen, function returns nil

in X10S simulator,  if you dont select a source, it returns a string "---" instead of nil

**Comment by bsongis-frsky** [comment]
How is initialized your "RDT_Currsource"?

**Comment by i3dm** [comment]
local RDT_Currsource

at the beginning of the LUA

**Comment by bsongis-frsky** [comment]
Sure, it would be better to initialize your local vars.
Please attach a very minimal script so that we can help

**Comment by i3dm** [comment]
> Sure, it would be better to initialize your local vars. Please attach a very minimal script so that we can help

it would take a lot of work to do that, so unable to do it right now (can send my full widget privately if needed), im sure you can test it easily enough.
just use:

local RDT_Currsource
at the beginning of the LUA

Current = system.getSource (RDT_Currsource)

and do not choose a source. compare x20 to x10 behaviour.

**Comment by bsongis-frsky** [comment]
please initialize your local variables
then please print the category and member of the result of system.getSource(...)

**Comment by i3dm** [comment]
bump
