### ISSUE TITLE
Range Test - Tandem X20s versus R8 Pro

### ISSUE THREAD

**Issue by willianwcz** [FrSkyRC/ETHOS-Feedback-Community#1747]
I'm getting 35db after about 30 steps away from receiver in "range check" mode. I know when in this mode the tx power is reduced for testing. My question is if this value is a safe value obtained in range test.
My transmitter is a Tandem X20s and my receiver is a R8 Pro.
Thanks in advance

**Comment by EngelMT** [comment]
I think it is not o.k. Normal is 35db at round about 100 m. Then you can go mor far away with 35. Up to round about 250 m. FailSafe comes at 10db. This is around 400 m away.

Do you have flashed newest TD Firmware and receiver Firmware?

**Comment by willianwcz** [comment]
> I think it is not o.k. Normal is 35db at round about 100 m. Then you can go more far away with 35. Up to round about 250 m. Then the RSSI start to go down more and more. FailSafe comes at 10db. This is around 400 m away.
> 
> Do you have flashed newest TD Firmware and receiver Firmware?

Yes, I'm running with latest X20s and R8 firmwares. During my 3 flights yesterdays, I got three RSSI low warnings with signal below 32Db

**Comment by willianwcz** [comment]
This is my telemetry graph from my last flight
![25_06_22_Flight 2](https://user-images.githubusercontent.com/66046724/175823027-b705293c-97dd-4147-994c-1d1151ba106d.jpg)
t

**Comment by EngelMT** [comment]
A lot off people use this combi off hardware. Me too. That means it's your hardware. So it has nothing to do with ETHOS. That's why the problem is actually wrong here. I would discuss it with your dealer.

**Comment by willianwcz** [comment]
[Stick-30cc-2022-06-25-17-05-10.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/8996656/Stick-30cc-2022-06-25-17-05-10.csv)
This is my complete flight log

**Comment by willianwcz** [comment]
> Muitas pessoas usam esse hardware combinado. Eu também. Isso significa que é o seu hardware. Então não tem nada a ver com ETHOS. É por isso que o problema está realmente errado aqui. Eu discutiria isso com o seu revendedor.

I agree my problem should be a hardware problem. Hope there is a RX problem wich will be less traumatic than a TX problem

**Comment by Marisha62** [comment]
Yesterday I had the same experience. Short range on first walk test after adding R9-MX as redundancy to a GR8 receiver. Additionally the telemetry was lost.

My setup: TX is X20S, RX 1 is R9-MX and RX 0 is GR8 and sensors are ESC and GPS. There was an abrupt drop off in RSSI immediately prior to GR8 logs show it switched to be RX1 (already in use by R9-MX) and then tried to be RX2 before going back to be RX0 as it is configured. The logs show there was loss of telemetry from the both receivers and all sensors.

In your CSV at time mark 17:23:44 your reciver changes from 0 to 1, and then back again, and the time format changes. Do you know why that is?

Where to report this issue if this is not related to Ethos? I've flown with the GR8 without any issues before the incident.

**Comment by xiaoyigg** [comment]
> This is my complete flight log

How can I export this data?

My x20s+r8 pro ave the same problem as you

**Comment by willianwcz** [comment]
> In your CSV at time mark 17:23:44 your reciver changes from 0 to 1, and then back again, and the time format changes. Do you know why that is?
> 
Its just should be a rudder being commanded. This column show this parameter to us

**Comment by willianwcz** [comment]
@xiaoyigg you can go to a excel and go to the option "csv to text" then import the csv and make all changes you want, including graphs

**Comment by Marisha62** [comment]
> > In your CSV at time mark 17:23:44 your reciver changes from 0 to 1, and then back again, and the time format changes. Do you know why that is?
> 
> Its just should be a rudder being commanded. This column show this parameter to us

Maybe. The column I referenced has the heading "RX" and is (apparantly) linked to RX number in the TX. Out of the 4089 rows in your log there are only three of value 1. To my mind this is unexpected and I'm still wondering why the RX number is changed. My log shows a similar anomaly. I also lost telemetry from both RX's following the event.

Where do I report my observation so it can be investigated if it is not normal for the RX number to change, followed by loss of telemetry which is then recovered?
[2022-06-30-18-13-48.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9033110/2022-06-30-18-13-48.csv)

**Comment by willianwcz** [comment]
In this last weekend we could take a same model of R8 Pro Receiver from a friend of mine and install it in my plane for comparison. The results show there is a problem with my receiver (R8 Pro).
   Please, take a look on the 2 attached files. In the first file called "Jul_02_2022_Flight 1" I´m flew with my own receiver, note the many extreme low RSSI reports. 
   In the second file called "Jul_02_2022_Flight 2", I´m flew with a R8 Pro receiver of my friend. and I only got one minimum report of 34dB, very above the previous reports.
   In my opinion (and tests), I have a big problem with my receiver. This receiver has only one month since I buyed and never had worked well according to the telemetry.
![Jul_02_2022_Flight 1](https://user-images.githubusercontent.com/66046724/177233947-2d7429c8-1d7a-450d-b7b3-6264b859b6df.jpg)
![Jul_02_2022_Flight 3](https://user-images.githubusercontent.com/66046724/177233950-3d4ebeee-1d51-46fe-a5b7-9fd4cbd240d1.jpg)

**Comment by mawzthefinn** [comment]
I hope you have contacted your dealer or FrSky support to get your R8 Pro fixed or replaced. 

If not, please do so as you have a hardware issue best dealt with via warranty.

**Comment by willianwcz** [comment]
Unfortunately, the dealer told me this is not his business. Also told me I
should try direct contact with Frsky as rx manufacturer. In other words, I
loose my receiver...
I´m deeply disappointed with this case once I had always use a Spektrum
equipment and I was thinking in change all of my hardware to Frsky brand.
But now, i´m affraid with this post-sale service

Em seg., 14 de nov. de 2022 às 23:32, mawzthefinn ***@***.***>
escreveu:

**Comment by mawzthefinn** [comment]
I would definitely suggest contacting FrSKy service if the dealer will not assist

https://www.frsky-rc.com/service-center/

Dealer experience may vary with any brand unfortunately. I would recommend dealing in the future with a dealer that has a solid reputation for support, such as Engel Modelbau, T9 Hobbysport or Aloft Hobbies.

**Comment by willianwcz** [comment]
I did this. I had made contact with Frsky. But we still do not have authorized service here in Brazil, so I should send the rx to Frsky, in China, with my own money. But the shipment costs for this operation was almost the cost of the receiver. 
But I completly agree with you when you say about choose a good reputation dealer to buy.

**Comment by mawzthefinn** [comment]
Closing this off, as it's conclusively proven to be a bad receiver.
