### ISSUE TITLE
Real Time Clock bug

### ISSUE THREAD

**Issue by capraf** [FrSkyRC/ETHOS-Feedback-Community#1748]
If the Tandem X20S is switched on and off many times, the RTC loses a few seconds (e.g. losing 6 seconds after switching on and off 10 times).
This is a bug, as a RTC should run continuously regardless of power button activity.

Transmitter: Tandem X20S
Ethos: 1.2.10 EU

**Comment by bsongis-frsky** [comment]
Confirmed

**Comment by capraf** [comment]
Thank you for your perfect work!
