### ISSUE TITLE
Play Track

### ISSUE THREAD

**Issue by RudrigoMaciel** [FrSkyRC/ETHOS-Feedback-Community#1749]
Version X20s, 1.2.10:
1. Special functions
2. Play Track when a switch position change 
3. Problem: when you change the track A to a new track B, the radio doesn't save the new track B.  After You switch off the the, switch On the radio, the new track B wasn't saved, the radio plays A track.

**Comment by MIKE-DAILEY** [comment]
Not sure exactly what you are explaining.   With a X20S on 1.2.10. in Special Functions Play Track saves the switch positions or the File selected.

**Comment by RudrigoMaciel** [comment]
When you change the file sound A to B and you restart The radio, the file is A and not B.

**Comment by MIKE-DAILEY** [comment]
It is working for me.  Which system are you using?

**Comment by RudrigoMaciel** [comment]
I'll try to reproduce it and make a video in YouTube. 
Thank You.

**Comment by MIKE-DAILEY** [comment]
It might be a good idea to see if any changes made in other areas of the system are not saved.

**Comment by RudrigoMaciel** [comment]
Yes!
