### ISSUE TITLE
GR8 problème de son.

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#175]
Horus X10 isrm Ethos1.0.4 et récepteur archer GR8 v.2.1.6.
La découverte des capteurs est ok.
Je règle l'altitude et le son du vario sur un inter, ça fonctionne.
- [x] Le bip bip du vario change avec l'altitude, par contre la tonalité est très différente de celle d'OpenTX, Il est beaucoup trop aigu.
- [x] De plus dans "son et vibration" j'ai remarqué que la barre de volume ne fait pas varier le son du vario.

Ai-je mal fait quelque chose?
Merci.
Alain

**Comment by bsongis-frsky** [comment]
Voudriez-vous m'envoyer un email ? Je vous ferai parvenir un firmware corrigé pour test

**Comment by aalain8** [comment]
***@***.***
Merci
Alain
________________________________
De : Bertrand Songis @ FrSky ***@***.***>
Envoyé : jeudi 6 mai 2021 09:33
À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc : aalain8 ***@***.***>; Author ***@***.***>
Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] GR8 problème de son. (#175)


Voudriez-vous m'envoyer un email ? Je vous ferai parvenir un firmware corrigé pour test

**Comment by aalain8** [comment]
Je viens de tester la version V1.0.5
La barre de volume marche.
Par contre le bip du vario toujours pas "voir vidéo".
À noter avec deux récepteurs identiques le bip n'est pas le même.
J'ai aussi testé la version V 2.0.7 du récepteur GR8, ne marche pas.

https://user-images.githubusercontent.com/64332717/117567451-be6bad00-b0bc-11eb-9962-854dca5fc5fc.mp4
