### ISSUE TITLE
Ethos Suite not able to see online update after 1.2.11 update.

### ISSUE THREAD

**Issue by BHerde1** [FrSkyRC/ETHOS-Feedback-Community#1751]
When I opened Ethos Suite it saw the 1.2.11 update on line and promoted me to update Ethos Suite.  I updated the Suite to 1.2.11 and now Ethos Suite does not see the 1.2.11 update online.

**Comment by STC148** [comment]
same problem here

Ethos Suite 1.2.10:
![10](https://user-images.githubusercontent.com/85410070/176028541-8799e012-741d-4a54-8a05-3c145977096d.jpg)
![10 2](https://user-images.githubusercontent.com/85410070/176028566-694e7ebd-7460-4ccf-83e3-153243449e45.jpg)

Ethos Suite 1.2.11:
![11 2](https://user-images.githubusercontent.com/85410070/176028630-ee541a36-2adb-490d-be57-53d6a51add57.jpg)
![11](https://user-images.githubusercontent.com/85410070/176028658-0993b305-cfdc-496e-8f35-100b7d984573.jpg)

**Comment by OldGazer** [comment]
Make that three of us..

**Comment by bsongis-frsky** [comment]
For people who have been too quick, please re-download manually Suite 1.2.11, or wait until tomorrow when frsky website is updated!
