### ISSUE TITLE
how can i use the function [Lua].luac files (without source) support added

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1753]
Hello Bertrand,

how can i use the function
[Lua].luac files (without source) support added
to use?
Many Thanks

**Comment by bsongis-frsky** [comment]
just create an empty main.luac near main.lua
it will be overwritten each time the main.lua will be updated
then you can redistribute your luac file

**Comment by bsongis-frsky** [comment]
Doc updated

**Comment by Benno00** [comment]
Hello Bertrand,
that works very good, thank you very much
best regard Benno

**Comment by i3dm** [comment]
perhaps ethos can generate the luac file automatically without having to add it manually?
