### ISSUE TITLE
Provide description files for sound generation

### ISSUE THREAD

**Issue by patman13** [FrSkyRC/ETHOS-Feedback-Community#1758]
Is it possible that you could provide description files for sound generation like the "de-DE-taranis.csv" from OpenTX?
I would like to create own sound files and would like to re-generate the system files as well to have consistent voice.
I have a complete setup in MacOS to do this in a very simple way.

Regards,
Patman

**Comment by willianwcz** [comment]
Basically, you need a .WAV files, MONO channel, with a 32000Hz of bitrate. In OpenTX, there is a limit for 6 caracteres for the name of the file.

**Comment by patman13** [comment]
The settings for the wav files I have. Also a complete workflow for MacOS to generate them.
I would only need the list of the sound files. In OpenTX a csv file was included in the release so I knew when a new sound file was introduced an could do the generation again.

The cdv file is simple and of course the Ethos developer need something similar. Would be nice if they could share it here and include it in the release (e.g. inside audio folder) later.

Example (German):
Folder,FileName;Text

```
SOUNDS/de/SYSTEM;volt0.wav;Wolt
SOUNDS/de/SYSTEM;amp0.wav;Ampär
SOUNDS/de/SYSTEM;mamp0.wav;MilliAmpär
SOUNDS/de/SYSTEM;knot0.wav;Knoten
SOUNDS/de/SYSTEM;mps0.wav;Meter pro sekunde
SOUNDS/de/SYSTEM;fps0.wav;Fuss pro sekunde
SOUNDS/de/SYSTEM;kph0.wav;Kilometer pro stunde
SOUNDS/de/SYSTEM;mph0.wav;Meilen pro Stunde
```

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/Ethos-audio-sounds-generation
