### ISSUE TITLE
extend (now limited) weight of butterfly outputs

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1759]
Rev 1.2.11 disabled the negative part of the Butterfly Input, which is fine.
But in result the dependent outputs lost travel.

Previous Ethos revisions allowed an output range from -100%..+100% = 200%

Maximum "output" weight in Butterfly actually is 150%

i would propose to extend max weight at minimum to 200% ( or to same value as available in free mixers)
So one could use full servo travel for flaps who are configured with large offsets, which is common.

regards

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/176382797-9fde565d-f202-4e4c-8b42-d75226582c99.png)

**Comment by strgaltdel** [comment]
![image](https://user-images.githubusercontent.com/20392683/176388032-7f44e43b-0ee2-4138-8cb5-2bc667a55c0e.png)
