### ISSUE TITLE
Request Firmware FLEX - EU - LBT 

### ISSUE THREAD

**Issue by Sigee3** [FrSkyRC/ETHOS-Feedback-Community#176]
Please can we have EU LBT Flex firmware.
Thanks

**Comment by WismyYao** [comment]
It will be done in the future

**Comment by Sigee3** [comment]
Thank you.

**Comment by Sigee3** [comment]
I know your really busy but any idea when we can expect flex eu lbt ?.

**Comment by Adelaxie** [comment]
Please update internal TD module firmware to support 2.4g lbt mode with FLEX firmware.
