### ISSUE TITLE
Model name must include a low case character

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#1760]
Not sure this is a bug or intentional but could let you spend time to get through it.
Thanks Jet Flyer!

Using only UPPER CASE character to create a model, the said model will not show in "model select".
Howewer it will show in file manager.

If for some reason this is intentional, a mention should be added in the user manual.

**Comment by bsongis-frsky** [comment]
Are you sure?

**Comment by Eagleowl1** [comment]
Yes this was experimented several times
e.g. TEST is not OK
       TESt is OK

**Comment by jfint** [comment]
A number was also OK

**Comment by Hartinger** [comment]
I found that the length of the filename is also critical. I tested this with the X10S Express simulator and ETHOS 1.2.11. If the filename is longer than 11 characters, the model is not offered for selection. If a new model is created with a name longer than 11 characters, the filename reflects the model name, i.e. it is also longer than 11 characters. After selecting a different model it is not possible to reselect the newly created model.

**Comment by bsongis-frsky** [comment]
Checked here
![image](https://user-images.githubusercontent.com/50834778/180146702-9e6a3ecc-286f-469b-8524-943e0640896a.png)

**Comment by Hartinger** [comment]
Have you selected a different model and then reselected the one with the long name?
I have confirmed the problem also for the X20S simulator. If I create a new model and allocate a name with more than 11 characters, everything is initially fine. If I then select a different (existing) model, the new model is no longer available for selection in the model menu. If I then shorten the filename in the Windows Explorer, the model is found again (NB that the name does not reflect the shortened filename as it is stored in the model file).

**Comment by Hartinger** [comment]
Just one more thought. I am using sub-folders in the model directory, maybe the problem is related to that.

**Comment by Hartinger** [comment]
Something is fundamentally wrong here w.r.t. accessing the SD-card. I have a model with the following filename: MXS_3D.bin. In the X10S simulator 1.2.11 there is no problem with this model, i.e. it can be selected. The same file copied onto the real radio is not visible in the model menu. Even more strange: the filename in the radio data explorer is displayed as MXS_3D_BIn, i.e. the extension shows two capital case letters. N.B. that the simlator's data explorer shows the installation path of the programme.
