### ISSUE TITLE
butterfly slow down/up

### ISSUE THREAD

**Issue by JfkJet** [FrSkyRC/ETHOS-Feedback-Community#1763]
Hi,
Swich from opentx to Ethos. Crow mix (butterfly) missing a slow up/slow  down  possibility for Aileron and Elevator.  How to solve this in Ethos Mixer as it was possible in Opentx.  Radio used X10S Express.

**Comment by hrenz** [comment]
with  a flight phase you have what you need
Fade In Fade out as slow up/down

**Comment by JfkJet** [comment]
> with a flight phase you have what you need Fade In Fade out as slow up/down

Great that solved issue partially. Fade out is working but Fade In not efected.

**Comment by mawzthefinn** [comment]
What is your input? If enabling with Flight Modes, use Special->Maximum as your source and Fade IN/Fade Out will work correctly.
