### ISSUE TITLE
FRSKY X10S EXPRESS

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#1767]
After updating from open TX to ETHOS which update to use for the internal RF, ETHOS-ISRM or ETHOS update from FRSKY web site. I'm using (X10S EXPRESS).

**Comment by MIKE-DAILEY** [comment]
If your system is an original X10S Express, you use the ISRM firmware from here https://www.frsky-rc.com/horus-x10s-express/   From GitHub use ETHOS X10EXPRESS.zip firmware. 

If your system is an X10S with the upgrade ISRM you use the ISRM firmware from here https://www.frsky-rc.com/access-upgrade-module-kit-x10-x10s/ From GitHub use ETHOS X10-ISRM.zip firmware.
