### ISSUE TITLE
1.2.11 Ethos X20S - Sensor Conflict

### ISSUE THREAD

**Issue by Joetrin** [FrSkyRC/ETHOS-Feedback-Community#1768]
Prior to updating 1.2.8 to 1.2.11 all radio was working great.  Using Ethos Suite this person updated from 1.2.8 to 1.2.11
In the aircraft: SR10 Pro 
R9 SX as secondary RX

No sensors plugged into the aircraft but the radio is saying "Sensor Conflict".

We've unplugged all the sensors and "Deleted" sensors.
The only sensor left on the Telemetry Screen is 
RX Batt for the 2.4 
RX Batt for the 900

RX0 shows and RX1 both show an ID of : 18F101 which maybe why it's telling us there is a Sensor Conflict.

Note: Nothing was done other than upgrade from a previous version to 1.2 11

At this point I've told the customer to unregister both RX and Re-Register them one at a time to see if it fixes the issue.

Has anyone heard of this issue before?

Thank You

**Comment by phazeman** [comment]
> RX Batt for the 2.4
> RX Batt for the 900
Most likely both sensors have the same ID and therefore conflict one with each other
change the ID of one of the sensors and see if it changes

**Comment by Fpilih** [comment]
How do you change the I.D. on the receivers ?

**Comment by iflyforfood** [comment]
I've got this same problem too. Also dual RX setup. No changes other than updating to .11 from .10

**Comment by luiz525** [comment]
Had the same issue here.
To solve I’ve turned the 900 telemetry off,deleted all sensors and after all selected to discovery just the 2.4 sensors.

**Comment by jumppilot7** [comment]
Please add the option to turn off sensor warnings/ status alerts so the user can decide if these warnings are wanted or not. Some 3rd party sensors user id can  not  be changed and causes unwanted warnings such as sensor conflict

**Comment by bsongis-frsky** [comment]
This issue is already fixed, the fix will be included in 1.2.12

**Comment by Fpilih** [comment]
Thank You

**Comment by StandaVana** [comment]
when will the 1.2.12 update be? I have the problems described above - sensor error (same ID RX0 and RX1). I fly with a tow truck - great responsibility for the execution of the flight. Until the 1.2.11 update, a great system.
When updating back to 1.2.10, the system falls to factory settings + SD card not found.
Více o zdrojovém textu
