### ISSUE TITLE
Add button to show current value of "Adjustment modifier" and allow user to change common ranges

### ISSUE THREAD

**Issue by frskyrc-ben** [FrSkyRC/ETHOS-Feedback-Community#1769]
While adjusting the model the little 'adjustment value' slider across the bottom is very difficult to see and to use.

We should add an additional button to show the current 'value' of the adjustment modifier, as well as to allow the user to click it and select some common adjustment range, like 1, 5, 10, 25, 50, 100.

![image](https://user-images.githubusercontent.com/108486338/176784767-25aeee39-07b4-411f-9231-676a92b40451.png)

![image (1)](https://user-images.githubusercontent.com/108486338/176784772-5c8ccc34-0b0e-4fdb-9b09-73f91a7584a6.png)

The little slider at bottom is very hard to see and use and currently there is no indication of the selected "adjustment" value

If we can also add a button that will show the slider value, but also allow you to click the button to select a specific increment value like 1, 5, 10, 25, 50, 100, I think this will be a lot more convenient and easier to use.

Just let me know if you have any questions about the above.

**Comment by bsongis-frsky** [comment]
I don't like too much the design, but the idea is good for sure!

**Comment by loetefix** [comment]
i allready opened that request a long time ago. it was closed.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/635

**Comment by loetefix** [comment]
keep alive

**Comment by bsongis-frsky** [comment]
Discussion to be continued in #3908
