### ISSUE TITLE
Add curves in mixer

### ISSUE THREAD

**Issue by marevalor** [FrSkyRC/ETHOS-Feedback-Community#177]
This request, is in reports  #135  and  #139 , In request  #135 @Nicholas-Luoyi  says that being soon, would it be possible in version 1.0.5?

Thanks.

**Comment by bsongis-frsky** [comment]
Adding issues for the same request won't help to get things quicker

**Comment by marevalor** [comment]
> Adding issues for the same request won't help to get things quicker

OK sorry .
