### ISSUE TITLE
Emergency mode with 1.2.11 x20eu in sound files

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#1770]
When i scroll to fast my own bank sound in the files, my x20eu go on emergency mode...
My sd card is to slow perhaps ?

**Comment by bsongis-frsky** [comment]
Reproduced and fixed. If you succeed to reproduce very easily please send me an email with your firmware information (X20 EU ?) and I will send back a binary to check if the issue is 100% fixed

**Comment by Tonio62** [comment]
ok, thank you, I can't reproduce the bug on my side
