### ISSUE TITLE
Ethos X20S getting a sensor conflict oral warning

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1772]
Need help trying to figure out what this “Sensor Conflict verbal warning I’m getting. This happed right after I upgraded to 1.2.11.  I’m using at TD10R receiver and FLVSS sensor. Any suggestions what this is. Thanks

**Comment by Joetrin** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1768#issue-1290617803
