### ISSUE TITLE
Ethos X20S and Tandem TD R18 possible error in displaying RSSI and telemetry Lost.

### ISSUE THREAD

**Issue by Hennyvt** [FrSkyRC/ETHOS-Feedback-Community#1773]
My X20s is running v1.2.10 the TD R18 v1.0.7

In range check or normal operation mode while monitoring RSSI once 2.4g signal goes below 20db the 900 m signal also turns red on the screen indicating loss of communication. Even increasing the 900 m TX level to 200m watt the RSSI for 900 m stays red. some control remains even through the RSSI is still in the 60 db range for the 900 m signal. I'm wondering if the transmitter monitoring has not switch over to the still valid 900 m signal.

**Comment by mawzthefinn** [comment]
Is this still occurring with TD-ISRM 2.2.2 and ETHOS 1.4.2 or later?
