### ISSUE TITLE
Tandem TD R10 receiver does not transmit Lipo sensor information through SMARTPORT

### ISSUE THREAD

**Issue by LeoCheung123** [FrSkyRC/ETHOS-Feedback-Community#1774]
Problem:  After configuring a pinout to "SMARTPORT" and then attaching a voltage sensor to the pin, no "lipo sensor" appears under the "Discover new sensors" list.
Context: All other telemetry variables (VFR, RXBatt, etc) are showing nicely on the TX.   Servos connected to PWM channels work.  MinI Lipo Voltage Sensor works when used with an ACCESS SR10 receiver under another model.
Equipment Used: X20S, TD R10 in TD mode, Mini Lipo Voltage Sensor
Firmware: All current firmware dated 20220702.  ETHOS v.1.2.11 FLEX, TDISRM FW:2.2.1, TDR10 v.1.0.7 
Reproducible?  Every time.

**Comment by LeoCheung123** [comment]
No redundant receiver used.

**Comment by KAID-YANG** [comment]
Hello, is the sensor you use MLVSS?

**Comment by 00steven** [comment]
I had similar problems with the voltage sensors. FLVS
I get a "sensor conflict" warning when using two flvs sensors to monitor 12s lipo setup.

I think the problem is the redundancy bus  I use an RB20

X20 Firmware 1.2.11,eu
TD-ISRM HW 1.4.0  fw2.2.1(EU-LBT)

**Comment by i3dm** [comment]
> Problem: After configuring a pinout to "SMARTPORT" and then attaching a voltage sensor to the pin, no "lipo sensor" appears under the "Discover new sensors" list. Context: All other telemetry variables (VFR, RXBatt, etc) are showing nicely on the TX. Servos connected to PWM channels work. MinI Lipo Voltage Sensor works when used with an ACCESS SR10 receiver under another model. Equipment Used: X20S, TD R10 in TD mode, Mini Lipo Voltage Sensor Firmware: All current firmware dated 20220702. ETHOS v.1.2.11 FLEX, TDISRM FW:2.2.1, TDR10 v.1.0.7 Reproducible? Every time.
have you updated your sensor to latest fw?

**Comment by i3dm** [comment]
> Problem: After configuring a pinout to "SMARTPORT" and then attaching a voltage sensor to the pin, no "lipo sensor" appears under the "Discover new sensors" list. Context: All other telemetry variables (VFR, RXBatt, etc) are showing nicely on the TX. Servos connected to PWM channels work. MinI Lipo Voltage Sensor works when used with an ACCESS SR10 receiver under another model. Equipment Used: X20S, TD R10 in TD mode, Mini Lipo Voltage Sensor Firmware: All current firmware dated 20220702. ETHOS v.1.2.11 FLEX, TDISRM FW:2.2.1, TDR10 v.1.0.7 Reproducible? Every time.

update your lipo sensor to latest fw

**Comment by LeoCheung123** [comment]
> update your lipo sensor to latest fw

entirely possible. I didnt knwo sensors have firmware that require updating…

on a positive note. The FLVSS (voltage sensor w led display) works as is on my system. 👌🏽

**Comment by i3dm** [comment]
![image](https://user-images.githubusercontent.com/8968780/179490315-8f937d79-2e71-42e0-b2d1-20eb20e0f1a2.png)

**Comment by 00steven** [comment]
I think there is a problem with this update! I can't change the id of the sensor. Even not with the ID changer I don't know where I can mention this.

**Comment by mawzthefinn** [comment]
Please use the latest firmware, the AppID fix on 220630 should fix the ID of sensor issue you were having
