### ISSUE TITLE
Any Official Downgrade Path in Ethos within Major Version numbers?

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#1775]
Hello, just checking if there is an Official Downgrade Path within a major version of Ethos. 

With the recent found bug of #1772 #1770 #1768 or say something else and we wanted to downgrade to a previously known working version while continuing to fly safely or use a feature that was previously working. Example: From Ethos Version 1.2.12 down to 1.2.11

Thanks!

I feel this is an important topic and option for those of us that want to continue to fly while circumventing new found bugs and I hope I am not alone in this opinion and viewpoint.

**Comment by mmasch** [comment]
Jet_Flyer (Mike) states 'best practice' in his posts on RCGroups.com:

_Before starting a firmware update, backup the model.bin files and radio.bin file. ETHOS does model conversion from older releases to newer release but not from new to old. The backup files are needed to return to older builds._

**Comment by bsongis-frsky** [comment]
#1772 is duplicate of #1768 => just remove the audio file and you will be fine
#1770 is there since day 1 and is fixed in 1.2.12

In Ethos Suite just choose the version you want and reinstall your backuped models
