### ISSUE TITLE
Bug Found..x18 loss of telemetry when switching from an ACCESS model to an ACCST model. 

### ISSUE THREAD

**Issue by ETHOSWarrier** [FrSkyRC/ETHOS-Feedback-Community#1776]
I have confirmed today with 3 x18 tx and ACCESS and ACCST receivers..With telemetry working on both rx confirmed...When switching from an ACCESS plane to the ACCST plane ,the Telemetry is lost including the RSSI on the ACCST receiver.

Now if  I turn the tx off and on again with the ACCST plane ,telemetry is recovered..If i switch to another ACCST plane ,all is well that rx  is ok with telemetry..infact any ACCST to ACCST plane is fine...alll telemetry works.

If i change to an ACCESS model...fine,ACCESS telemetry works  ...if i then switch to an ACCST model without turning off the tx...telemetry is lost again..totally repeatable and confirmed on 3 x18 today....mine is on Firmwae 1.2.11  and the other two are on 1.2.10...all three do the same, ALL EU LBT .

As a comparison my x20 is fine on all swaps..ACCST to ACCST  and ACCESS to ACCST all perfect and no loss of Telemetry at all..Thats on EU LBT 1.2.11 as well...so its an x18 issue...Chris.

**Comment by KAID-YANG** [comment]
Which two receivers are you using? What is the firmware version?

**Comment by ETHOSWarrier** [comment]
I have tried over 10 rx ,Both ACCESS  GR6,GR8,R4,R6 (software 2.1.10) and ACCST (software V2.1 EU LBT) on X6R,X8R,X4R.Its Always when switching model memory from An ACCESS RX model to An ACCST model memory without switching off the tx.If i power cycle the tx ...all telemetry works.So if i fly with an ACCESS rx..switch to an ACCST model memory...no telemetry....but power cycle and the Telemetry all works..Then change model memory to another ACCST rx ...alll works without a power cycle......ACCST to ACCST = OK       ACCST to ACCESS = OK  but ACCESS to ACCST = No Telemetry.  .....Done with 3 Tandom x18 and 10 rx....Chris.

**Comment by WismyYao** [comment]
The next version software of the TD module will fix this issue

**Comment by ETHOSWarrier** [comment]
Update, this issue is still happening in ETHOS  V1.3 for info.Is it an ethos x18 issue or a TD RF module issue its a little unclear...Chris.

**Comment by bsongis-frsky** [comment]
But Wismy said it's a TD module issue, then Ethos cannot fix it!

**Comment by ETHOSWarrier** [comment]
Yes,thats part of the confusion..why was it put in as a completed issue in 1,3 .  If its a TD issue, its a TD issue related to the X18 as there is no issue with my x20 using the same TD 2.2.1 Firmware when switching from ACCESS to ACCST models.It seems as thought its how ETHOS talks to the TD RF module when switching model memories. I am no expert so I will leave it with you guys and look forward to a new TD firmware that works on x20 and x18...Chris.

**Comment by bsongis-frsky** [comment]
Right, this is not an Ethos issue and it should be fixed now
