### ISSUE TITLE
DIY sensor range minimum not showing in hebrew

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1779]
Please have a look at the photo, DIY sensor range - max ix showing but min is not.
not sure if this happens in other places as well.
thanks.,
![lowrange](https://user-images.githubusercontent.com/8968780/177181118-f6ba26f4-b07c-4651-93d0-6f8178dee6bc.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/179922894-835d9b8b-6451-447a-b333-a2d0600cb208.png)

**Comment by i3dm** [comment]
> The same here: ![image](https://user-images.githubusercontent.com/50834778/179922894-835d9b8b-6451-447a-b333-a2d0600cb208.png)

yes.. still missing the bottom range (0 - 100 dB, only shows the max 100dB range)

**Comment by bsongis-frsky** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/50834778/179924047-86be4656-ccdd-4783-b193-ed875983bca8.png)

![image](https://user-images.githubusercontent.com/50834778/179924254-10ad2b2c-ca42-4993-af09-658f3859ab53.png)

**Comment by i3dm** [comment]
perfect thanks
