### ISSUE TITLE
WAV Audio Cue

### ISSUE THREAD

**Issue by LaserAV-Calgary** [FrSkyRC/ETHOS-Feedback-Community#1780]
When I flip multiple switches (with wavs, like flaps up, motor armed...etc) and/or get multiple warnings/telemetry announcements it seems like every wav enters a cue.
So I don't get immediate feedback I have flipped the right switch etc.

It is not really a bug but more of an irritant :-)

I think there is an opportunity to cleanup the current audio system that just seems to cue wavs/messages.
I think the following priority system would add some interesting possibilities.
The -Override- and -Instant- have obvious uses.
The -Mix- would allow you to have a beep or tone play for one function and then overlap/mix words from a warning etc
These priorities would be on a menu below wherever there is a choice for a wav or sound.

Proposed Audio Priority levels descending

-Instant-
Instantly *cancels* all playing and cued wavs, then plays.

-Override-
*Pauses* all other wavs until complete.

-Mix-
Mixes with all waves with a Mix-Priority OR an already playing Wait-Priority-wav.

-Wait-
Waits until there are no other wavs playing.

**Comment by RudrigoMaciel** [comment]
That would be great!

**Comment by marciomc-github** [comment]
This should be combined with an embedded MP3 player to keep a track playing on background while flying.

**Comment by bsongis-frsky** [comment]
Good idea

**Comment by LaserAV-Calgary** [comment]
I would like to keep this alive.
A few other users of ethos (at the field) have had runaway audio from telemetry when the power off their planes.
Some attention to audio infrastructure would be appreciated!

Proposed Audio Priority levels descending

-Instant-
Instantly cancels all playing and cued wavs, then plays.

-Override-
Pauses all other wavs until complete.

-Mix-
Mixes with all waves with a Mix-Priority OR an already playing Wait-Priority-wav.

-Wait-
Waits until there are no other wavs playing.

**Comment by RudrigoMaciel** [comment]
Please, it's important.

________________________________
