### ISSUE TITLE
PNG model images not working on X18

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#1781]
I transferred the model images from my X20S to my X18, and none of them will load. The PNGs work fine on the X20S, but nothing on the X18. Here is an example image
![MiniAREthos](https://user-images.githubusercontent.com/17590174/177280709-2d54719b-370e-48bc-b848-70e70cd202ff.png)

The images are in the correct storage location and appear in the list of available images. Selecting one does not display the images.

Are PNG model images supported?
- If so: why are my PNGs not appearing? Do they need to be a different size for the X18, so that they are not scaled?
- If not: please filter the list so that they are not selectable

Whatever the answer. Why is this not in the documentation or Wiki somewhere?

**Comment by ETHOSWarrier** [comment]
I have an x20 and x18 and you have to resize the image for the x18 to see them...I use the Ethos Suite tool...

**Comment by MrD-RC** [comment]
Thanks @ETHOSWarrier
But what is the size for the PNGs for the X18? It should be documented somewhere. If composing the image with an image editor. I would rather set the size with that, rather than have is scaled in different software.

Its also strange how the bitmaps are 300x280 (X20 size) but work fine. So it only scales BMPs, not PNGs? What about the models screen where they need to be scaled further?

**Comment by ETHOSWarrier** [comment]
X18 sizes on here: 

https://www.rcgroups.com/forums/showpost.php?p=49071685&postcount=58

**Comment by bsongis-frsky** [comment]
We have set a limit as resources are not infinite: your bitmaps may not exceed the LCD size
X20: 800x600
X18: 480x320

**Comment by MrD-RC** [comment]
@bsongis-frsky thanks for the message. But my images do not exceed that size. I am trying to use a 300x280 pixel PNG. I took the image from my X20S, where it displays fine. But it doesn't work on the X18. The same size BMP works fine.

**Comment by Jo-le-Papy** [comment]
Try 180x166 pixe
![Capture d’écran 2022-07-15 à 22 35 11](https://user-images.githubusercontent.com/103277171/179306711-603fe30e-c2fb-4224-bb0f-2eeec80c3f47.png)
l

**Comment by mawzthefinn** [comment]
The real issue is that ETHOS on the X18 will resize 300x280 BMP's correctly to 180x166, so images in BMP format can be shared between X20 and X18/X10/X12, but PNG or JPG images are not resized and cannot be shared in the same fashion.

**Comment by bsongis-frsky** [comment]
Still valid?
