### ISSUE TITLE
Names in file manager > models

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1782]
Hello
If a model is created with the help of the wizard and given a name (e.g. ASW22), then this name appears in the Models menu and in File Manager > models. If you now clone this model and change its name (e.g. ASK), then this name is taken over in the Models menu. In the File Manager > models, however, ASW2201.bin is displayed instead of ASK.bin. Can this still be changed?
Thanks

**Comment by marciomc-github** [comment]
I believe there is a bug related to name a model with upper case only. 
mor should have at least one lowercase letter like ASk.

**Comment by bsongis-frsky** [comment]
In 1.4.4 when the user changes the Model Name. The Model Filename will be modified
