### ISSUE TITLE
Issue with Ethos suites seeing or connecting to my X10S radio on windows 11

### ISSUE THREAD

**Issue by VSchrepf** [FrSkyRC/ETHOS-Feedback-Community#1784]
I’ve run numerous experiment to see if the USB connections were the issue and now pretty sure they are not. What I did was a complete reinstall of windows 11, which wiped all my files and old drivers and reinstalled to a complete fresh state with nothing on the system but basic drivers needed to run the system. Also  turned off all windows antivirus systems just in case that they maybe to blame for no connecting. After the windows reinstall I installed Ethos suites and was sure that now the suites would see my radio, but to my surprise….. suites did not see the connected radio :-((. So I’m thinking and pretty sure it’s something else. Could the radio firmware install be an issue? Note that the computer file explorer does see the SD drive when i plug in the radio in bootloader mode and the screen switches to radio connected. So have to assume for some reason something in suites does not get triggered to connect. Could there be something that is written to windows registry during the suites install that may not be correct? I’m at a complete lost as to what the cause could be. 

Thanks

**Comment by bsongis-frsky** [comment]
Which version?

**Comment by VSchrepf** [comment]
[2022-07-07_09-39-34.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9064204/2022-07-07_09-39-34.pdf)
See attached PDF with the info. Thanks

**Comment by VSchrepf** [comment]
Was the information you required?

**Comment by VSchrepf** [comment]
> Which version?

information was sent on 7/7, is this what you needed?
