### ISSUE TITLE
X20S 6 F-Switch with blue LEDs are not bright enough outside in the sun.

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1786]
Hi,

is it possible to improve the brightness of the LED of the 6 function switches? 
Maybe Ethos can have a option to improve this like the screen brightness?
It looks for me that they are dimmed to a minimum light.
The problem is that in sunlight the blue LEDs are not really visible. You may not see it, if a functionality is on or off on the first look.
A deeper look is not possible during flying.

If the hardware doesn't allow this, another alternative would be to show them with dots or a dot matrix, or something similar in the status line of the Ethos screen.

A solution would be appreciated.

Best Regards

Bernhard

**Comment by BernhardFe** [comment]
Hi Bertrand, 
of cause, this is not a bug in Ethos, but a workaround would be to show the blue dots in the system screen where it fits. 
If the processor is driving the brightness of the LEDs (what I do not know, but it can be switched on/off by software) there might be also an option to use Ethos to increase the brightness of the LEDs.
If it is only hardware and not possible to change, then the display would be an option.
Best Regards Bernhard

**Comment by Adelaxie** [comment]
@BernhardFe I have reported to R&D to see if it can be improved on X20 and also future radios. thanks for your report.

**Comment by BernhardFe** [comment]
If there is no hardware solution for the switches, a display solution in Ethos would be useful to show the dots there. Thanks a lot for recognising and feed-back :-)

**Comment by bsongis-frsky** [comment]
Where do you want to display it?

**Comment by BernhardFe** [comment]
Hi Bertrand, thanks for asking. :-) I appreciate this very much!

I have 2 ideas in mind.
1. Basic display:
there is the lower line with Home, Plane, Screen, Setup and Clock, maybe there we can have an additional section to show 6 dots in a matrix. If possible 2 columns (1,4 2,5 3,6) and 3 rows, just like the hardware order. Or if to small, 3 columns (1,2,3 4,5,6) and 2 rows. When this is to mall as well, just Dots (1,2,3,4,5,6). 
Optional to 1:
Showing a grafic in a widget with 6 dots and maybe small text if there is enough space like F1 ... F6 in the dot.

Idea 2:
Additional, but can used in general:
Showing texts stings like for the flight modes via Special Function with e.G. 9 alternative text values and one default via special function. This means, if I have several logical switches, switches, f-switches, I can give them a name in the special function. The design might be similar to the VAR mixer, but this text string values can be used to show them in a widget. To avoid conflicts the widget should show the text value by the priority we have always in ETHOS by the mixers. This would be similar to fixed values var mixer and similar to speech special function, but in this case for text strings combining the method. 2 lines in the text with auto CR would be good to show it in a widget.

It's on you what would be the better design. You may try the options. I think 1 is a must, optional  would be a work around if 1 is not good enough and 3 would be the super function, but general useful for a lot of other cases. 

In case 3 for my use case (Scale Heli) I would give the f-switches a name and show the names in the Display. 1=Light & Sound, 2=Strong Light, 3=Landing light, 4=Position hold, 5=Return to home, 6=Auto Landing. Of cause this can be shown via widget and logical switch as well today, but then I would need 6 fields. And this is too much on the main display with other important parameter. In my Case above 2 values in parallel are good enough for 1-3 and 4-6. Other model flyers are using the flight mode to have a work around. I can not do this, because I use the flight modes for the basic steering of mixers and switches.

Hopefully this would help. What do you think?

Best Regards

Bernhard

**Comment by BernhardFe** [comment]
Any solution planned?

**Comment by bsongis-frsky** [comment]
Perhaps a Lua script?

**Comment by BernhardFe** [comment]
This is hardware specific. LUA might be an valid option. But I'm so sorry, I can not write LUA. :-(

**Comment by bsongis-frsky** [comment]
A Lua script will be needed if you want to display something else on the screen. We cannot make the led brighter as it is hardware
