### ISSUE TITLE
Bar widget in the screen should reflect the channel output value boundaries and adjust the bar.

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1787]
Hi Bertrand,
the default output channel is defined from -100% to +100%. Analog to this the bar widget in the screen shows -100% to +100% what is correct. 
But when I configure the output values of a channel form 0% to 100%. I would appreciate if the bar in the widget can also take over the boundary and as well the sub-trim value to show only the range of use.
This means, if the boundary value 20% is on the left and the 80% is on the right the bar should reflect the range instead of showing the full range like the default.

Why it is useful?
Then I can use the mixers and curves to produce a bar chart regarding the telemetry values for a lot of values like Accu Volt, Accu Capacity, Akku Current, Signals from 0 to 1... and a lot of other values that are always positive or in a range that can be spread. For example with 12S Akkus Voltage a bar from 44,4V to 50,4V shows from 0-100%. Than the bar chart widget of the channels can be used for showing a lot of values and telemetry values in an easy way as a graphic bar chart display. This might be better for a fast look as the values itself.
The change might be not very difficult but has a great impact.
Best Regards
Bernhard

**Comment by EngelMT** [comment]
I think it is a good point.

**Comment by BernhardFe** [comment]
This point should be not forgotten, not highest priority, but appreciated very much.
