### ISSUE TITLE
Please add ability to update XSR-SIM

### ISSUE THREAD

**Issue by huths0lo** [FrSkyRC/ETHOS-Feedback-Community#1788]
As title says, please add the ability to update the XSR-SIM USB Dongle through the ETHOS Desktop application.

**Comment by mawzthefinn** [comment]
The limiter on this is the device itself, not ETHOS Suite. It updates via S.Port like the receivers and not via USB. 

There would need to be a new device with USB-based firmware updating to accomplish this.
