### ISSUE TITLE
1.0.4 localisation do not change in Telemtrie menu

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#179]
If search english localisation and then you have a look to the Telemetrie menu and open "Speed" for setttings then you will see that the german localisation works in this area.

**Comment by bsongis-frsky** [comment]
I don't understand what you mean

**Comment by EngelMT** [comment]
On Thursday it was like this. I changed from german to english. All was fine but in menu Telemetry I found german language instead english.

But today I can not reproduce it. So I will close it for the moment.
