### ISSUE TITLE
150% servo limits is potentially dangerous

### ISSUE THREAD

**Issue by MikeBland** [FrSkyRC/ETHOS-Feedback-Community#1792]
When using a redundancy system involving SBUS, servo movements beyond about +/- 125% are not possible.
If using more than 125% on the main receiver driving PWM outputs, and this receiver enters failsafe, the servo positions then received from a redundant receiver via SBUS are limited to 125%.
In particular, if an output on the main receiver is beyond 125%, then at the point of switching to the redundant receiver, the output will change to 125%.
Possible solutions include:
1. Restrict extended servo limits to +/- 125%.
2. Add a setting to allow limits beyond 125%, but add a warning when this is set indicating this is incompatible with SBUS/redundancy use.
3. Add a warning when changing a limit beyond 125% indicating it is incompatible with SBUS/redundancy use.

**Comment by bsongis-frsky** [comment]
Right.
I think it's not possible to have the warning only when SBUS is used, because the whole transmission chain is not known at transmitter level.

1. Difficult, it has been done on purpose
2. Seems good
3. Seems even better because less work!

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/185924508-11968a23-6de1-4b53-9d36-d42dc212b61f.png)
