### ISSUE TITLE
Feature request - option for a source to switch aileron differential on and off 

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#1793]
We are currently flying a model on which we would like -5 percent aileron differential whilst in low rates, and no differential in high rates. While we can use a source to adjust differential up and down it would be nice to be able to switch between two values, as with rates and expo curves

**Comment by Wolepo** [comment]
You could use an auxiliary mixer in the differentiation to which you assign a curve
![Diff](https://user-images.githubusercontent.com/90325526/178539722-6e207072-4f8a-4b4c-b5f8-1809375203ee.jpg)
.

**Comment by mawzthefinn** [comment]
This is quite easy to do.

Create a VAR mixer on a high channel, say CH64

Name it Ail Diff, allow it to name the channel
Set the default value to what you want it to be in high rates.
Add a second line, with the Switch being the Low Rates position and the value being what you want the Differential to be in low rates

Now go back to your Aileron mixer, long-press the box with the Differential setting, select 'Use a Source' and then select Channels-> Ail Diff (Ch64)
