### ISSUE TITLE
x12s isrm

### ISSUE THREAD

**Issue by helikeith** [FrSkyRC/ETHOS-Feedback-Community#1794]
isrm update has stopped communication with isrm module. Firmware is a bin and will not flash.  current version !

**Comment by MIKE-DAILEY** [comment]
The X12S uses the update ISRM and the firmware from here. https://www.frsky-rc.com/access-upgrade-module-kit-x10-x10s/

 It is a frsk file,   ISRM-S-X10S.frsk
