### ISSUE TITLE
X20S Mixer Flightmode no Checkbox

### ISSUE THREAD

**Issue by MAES001** [FrSkyRC/ETHOS-Feedback-Community#1799]
Hallo,

In the Mixer Edit --> Flight Mode is no Checkbox to aktivate the Flight Mode.

Version (Firmware): 1.2.11,EU #8ca97f75
Show the Attach:

[No Checkbox.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9132738/No.Checkbox.pdf)

Greetings, Manfred

**Comment by STC148** [comment]
will be fixed with 1.2.12
#1765
