### ISSUE TITLE
Audio files do not update

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#1802]
Running Ethos Suite 1.2.11 on MacOS, the audio files do not update, or the suite gives a false 'outdated' warning.
Updated manually, still the 'outdated' message persists
Tried updating all and tried updated audio only, no result.

<img width="919" alt="Schermafbeelding 2022-07-19 om 16 24 09" src="https://user-images.githubusercontent.com/697422/179775009-67ad8450-920e-434b-b332-5aa75d601239.png">
.

**Comment by Nicholas-Luoyi** [comment]
Which language did you select?

**Comment by ahvink** [comment]
Thought I had selected English, but tried again today and this time it seemed to work although I had to manually disconnect and reconnect the X20S to get the 'Updated' message.
Thanks.
