### ISSUE TITLE
updated he.txt for Ethos 1.2.11

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1803]
Please use this file for future releases. its based on 1.2.11 he.txt.
also please **remove "hb.txt"** from sim releases, it has been replaced by "he.txt" long time ago.
thanks.
[he.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9147768/he.zip)

**Comment by bsongis-frsky** [comment]
Done
