### ISSUE TITLE
Ethos Suite image tool not correctly resizing images for X18/X18S even when size specified

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#1806]
Icons need to be 180px WIDE by 190px TALL. When you enter these sizes into the image tool on Ethos Suite it actually converts images to 180px WIDE by 167 TALL. have verified with Frsky and with MS Paint that the icon size for the X18 is indeed 180px WIDE by 190px TALL but for some reason the image tool is not sizing them correctly.

**Comment by Nicholas-Luoyi** [comment]
The conversion process of the image conversion tool will not destroy the aspect ratio of your original image

**Comment by mawzthefinn** [comment]
Closing as answer provided, original image aspect ratio is honored in the resize.
