### ISSUE TITLE
Helicopter setup skips Ch 1 and

### ISSUE THREAD

**Issue by kensterman** [FrSkyRC/ETHOS-Feedback-Community#1807]
When first four channels is set to fixed" is set to on.
When creating a helicopter CH 1 and 2 are skipped. works fine in airplane.
If they were not skipped the ch assignment would be good except make CH 5 gyro and 6 pitch.
So can we get this fixed where it will not skip Ch 1 and 2 when  first four channels is set to fixed" is set to on.
Does this with the X18 too
AETR is what I am using.  https://www.youtube.com/shorts/CZrG67LB1Jk

**Comment by mawzthefinn** [comment]
Duplicate of #999, closing in favour of that one
