### ISSUE TITLE
TD10  random telemetry call-outs in Ethos 1.2.11

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#1808]
Tandem X20
Ethos V 1.2.11
TDISRM v2.2.1
TD10 1.0.7

When flying there are constant callouts of "Telemetry lost" and "Sensor conflict", the receiver itself seems to work fine and the model never goes into failsafe.  This is in a large carbon glider that I would generally have 2 receivers in, this is an experiment to see how the tandem receivers work.  In the log I could seen the 2.3 rssi occasionally dropping but the 900 held beautifully.  These callouts did not happen in Ethos 1.2.10 and I believed that there was already a bug filed for similar issues with someone using the trio setup, but I cannot find it, please make duplicate if this is the case, its also possible that this was only described on RCG and the person never entered a bug.

**Comment by jfint** [comment]
[XPerience-2022-07-23-16-48-13.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9176312/XPerience-2022-07-23-16-48-13.csv)
Here is a log file from the offending flight

**Comment by bsongis-frsky** [comment]
Already reported and fixed for 1.2.12

**Comment by jfint** [comment]
Not Fixed #1818 #1827
