### ISSUE TITLE
Sensor Conflict announcement after 1.2.11

### ISSUE THREAD

**Issue by darkernoise** [FrSkyRC/ETHOS-Feedback-Community#1809]
I just upgraded an X20S to 1.2.11 FCC and now the radio announces, "Sensor Conflict", every 30 seconds.  This radio and same model have been working fine for about a year.  

The model in question is setup with:

- SR6
- R9MINI-O
- Neruon S60

All the above have been updated to latest firmware.  There are no other attached sensors.  I have tried deleting all the Telemetry and rediscovering.  I have watched and all the telemetry values are updating as normal.  I did notice that the "VFR" sensor has the same name on the 900M and the 2.4 modules as well.  Should those possible have default names to differentiate the two in logs as well?

**Comment by bsongis-frsky** [comment]
Already reported and fixed for 1.2.12

**Comment by jfint** [comment]
Not Fixed, #1818 #1827

**Comment by m0p3d** [comment]
Agree
