### ISSUE TITLE
Allow Same-Format Sources as Values in Logic Switches

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1813]
Currently if you select a Logic Switch Source (A) that has a format other than can be presented as a standard analog value, you can only compare to a fixed Value (X).

Please update so you can also compare to a same-format Source, ie compare 2 timers or compare 2 voltages.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/210571397-46fa4efc-34ba-4e87-9c2e-5da1a39c84fb.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/210582085-2ab9b7f4-f095-43bc-a636-1a599be18972.png)

**Comment by mawzthefinn** [comment]
Excellent!

**Comment by spoke2570** [comment]
🙏🙏🙏

**Comment by Dsrenger** [comment]
Hey @mawzthefinn 

As the request came from you.

I tested around with the implementation of this feature.

What are the cases that you had in mind?

First thing I thought about was, to compare two temperatures or voltages (of flight batteries) and giving a warning if they exceed a certain value.

Eg. Motor 1 is 10° Celsius (or Fahrenheit of you like :D) warmer than motor 2. Give a warning.

With the current implantation the warming would come off motor 1 is 0,0001° warmer than motor 2. Or let's say it in this way....I haven't found a way to do it.
I guess that's not what you had in mind.

Therefore I am curious what I can use it for...

**Comment by spoke2570** [comment]
I use it to record the best flight time for my DLGs.

**Comment by mawzthefinn** [comment]
I had a couple use cases, some of which would require other changes in the future to fully realize.

1. Comparing against AIN2 (ie against an arbitrary reference voltage). This is more a case where you might  be measuring one value and need a fixed value to compare against.

2. Comparing RPM for matching twin engine setups

3. Comparing timers -  have a set flight time pre-loaded by Lua into Timer 2, compare to it in timer 1.
