### ISSUE TITLE
1.3.0 invalid model data

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#1814]
After updating my x10s to version 1.3.0, two models no longer work.
[invalid models.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9213283/invalid.models.zip)

![IMG_20220728_200842258](https://user-images.githubusercontent.com/85410070/181612195-279ff063-f361-4aaf-9c52-25df803a7d1e.jpg)

**Comment by bsongis-frsky** [comment]
You have 2 consumption sensors, do you remember if there is another sensor just after those 2 consumption sensors?

**Comment by bsongis-frsky** [comment]
One sensor is badly imported (PercentSensor)

**Comment by bsongis-frsky** [comment]
I will remove this release and re-release tomorrow

**Comment by STC148** [comment]
After the calculated consumption sensor, I still have a calculated percentage sensor. If I delete this sensor, then the model can be selected.

![cal_%](https://user-images.githubusercontent.com/85410070/181624345-7bf917f8-3f77-4e6c-8908-b1691f598d6e.jpg)

**Comment by bsongis-frsky** [comment]
Import issue of all Calculated Sensors. Fixed for tomorrow
