### ISSUE TITLE
Multi Module or Ghost options not shown on external module list

### ISSUE THREAD

**Issue by vhuzalo** [FrSkyRC/ETHOS-Feedback-Community#1815]
1.3.0 release should added ghost and multi protocol options, but they don't appear on external module list. They need to be connected to apear on the list?

**Comment by MIKE-DAILEY** [comment]
Correct.  You need a user installed Lua script and it has not been uploaded yet. Should be soon.  Learn more here https://www.rcgroups.com/forums/showpost.php?p=49550649&postcount=18844

**Comment by bsongis-frsky** [comment]
They will be online tomorrow
