### ISSUE TITLE
[X12S] hangs at second boot..

### ISSUE THREAD

**Issue by nikwalnikwal** [FrSkyRC/ETHOS-Feedback-Community#1816]
The X12s  radio totally freezes at second boot if for example internal rf module is on..I have to remove battery to get it to boot one time again.. 

The "old" 1.3.0 that was up for like an hour , does'nt. But  to get that one working at all i have to rename fonts to something else or the text will be scrambled..

**Comment by MIKE-DAILEY** [comment]
Using the 1.3.0. posted after 11:30 AM today and it is rebooting OK.  ACCESS selected on the ISRM.

**Comment by nikwalnikwal** [comment]
Please try accst d16 too, I did'nt try access..  I did copy the new corresponding files over..

**Comment by nikwalnikwal** [comment]
ok ,,, now the old 1.3.0 hangs too ..  It was working a while ago..   ok.. I'll try the whole procedure again..

**Comment by bsongis-frsky** [comment]
It would be interesting to know what is the root cause, if it is random, or what... try a fresh SD?

**Comment by bsongis-frsky** [comment]
Is your bootloader up to date? It is important!

**Comment by nikwalnikwal** [comment]
bootloader is 1.2.11. It's been working perfectly with ethos suite is 1.2.11 (cant find a newer).

sorry about beeing noob about ethos , I thought since ethos suite said 1.3.0 after I copied the horus sd files it would be ok..

Can I really use ethos suite for this, seems every time I try I end up with an earlier version whatever I'm doing, confused now.

**Comment by nikwalnikwal** [comment]
so is it really  important to copy the files  beeing in bootloader mode .??..   I saw  ethos suite do that so I did that, we'll se if that did the trick..  well no, it worked like 6times then i froze, going back to 1.2.11 now to see if it also does that..

**Comment by bsongis-frsky** [comment]
When you disable RTC warning it hangs? That's very strange!

**Comment by nikwalnikwal** [comment]
it pretty random actually.  sometimes it just wont boot.   what actually causes it seems to be anything , just now i only changed model  and it froze at next boot.  but now changing model works fine.   what will trigger the freeze next time is impossible to say it seems..

**Comment by yak-54** [comment]
do you have any scripts in the script folder ?

**Comment by yak-54** [comment]
> bootloader is 1.2.11. It's been working perfectly with ethos suite is 1.2.11 (cant find a newer).
> 
> sorry about beeing noob about ethos , I thought since ethos suite said 1.3.0 after I copied the horus sd files it would be ok..
> 
> Can I really use ethos suite for this, seems every time I try I end up with an earlier version whatever I'm doing, confused now.

its not you i have the same issues using suite as well i have to do it manually only it worked was when it first came out

**Comment by bsongis-frsky** [comment]
Would you please try another SD card?

**Comment by bsongis-frsky** [comment]
@anyone who is able to reproduce this issue, please contact me by email so that I can add more logging to try to understand what happens

**Comment by yak-54** [comment]
> Would you please try another SD card? It seems that your issue is linked to modifications which will write to the SD Only on X12S

i have tried many today day alone i used 2 sd card 
what card do you recommend go get some new ones tomorrow

**Comment by nikwalnikwal** [comment]
yes I'm trying with a new 32gig fast sd card, but on 1.3.2.  so far it hasnt been hanging but i have to test more..  Is there a formatting function in the radio somewhere?

**Comment by bsongis-frsky** [comment]
It was a missing delay in SD Initialization, which was needed for some SD Cards
