### ISSUE TITLE
Logic Switches Value(X)

### ISSUE THREAD

**Issue by tessler1015** [FrSkyRC/ETHOS-Feedback-Community#1817]
**Bug:** Value (x) for [Telemetry>>LIpo] Value canot be edjusted... it jumps **directly** from 0.0 to 36,60

https://user-images.githubusercontent.com/58549413/181882922-477ef330-e773-4e5f-ae7b-c12d58ad9188.mp4

**Comment by hrenz** [comment]
if there is no Lipo , you have no voltage

**Comment by tessler1015** [comment]
Hi’

  1.  I do have lipo connected and fully function on the telemtry readoputs.
  2.  the functiuon doesn’t have to have access to Lipo while you program it

מאת: hrenz ***@***.***>
נשלח: Saturday, 30 July 2022 13:36
אל: FrSkyRC/ETHOS-Feedback-Community‏ ***@***.***>
עותק: tessler1015‏ ***@***.***>; Author‏ ***@***.***>
נושא: Re: [FrSkyRC/ETHOS-Feedback-Community] Logic Switches Value(X) (Issue #1817)


if there is no Lipo , you have no voltage

**Comment by tessler1015** [comment]
Everything was fully function until ver 1.3.0

**Comment by bsongis-frsky** [comment]
I think this one is fixed since, please open a new issue if I am wrong!
