### ISSUE TITLE
Editing a "special function" locks the transmitter!!

### ISSUE THREAD

**Issue by KevinFairgrieve** [FrSkyRC/ETHOS-Feedback-Community#1819]
Ethos V1.3.0
Bootloader V1.2.11

After upgrading to ETHOS V1.3.0 I was going through my models to check that everything was working as expected.

Adjusting one to suit how I now use this model would not allow me to edit a special function.

I have tried several other models and always the same result.

Once the screen is locked pressing any button has no functions. The power on/off switch does not work and the only way to regain control is by removing the battery.

I have also noticed on occasion that the icons are not fully displayed on screen when wanting to select "special functions" but pressing on where it should be will enter the selection.

https://youtu.be/oF6aDq75mG8

Video may help.

**Comment by mgsanna** [comment]
Here X20S 1.3.0 and 1.2.11 bootloader..... no problem at all, I'm unable to reproduce.....

**Comment by KevinFairgrieve** [comment]
So I just did a reflash of all components and even tried a second SD card!

No dice, still the same.

Gone back to 1.2.11 all working fine.

I will now try again to go from 1.2.2 to 1.3.0

**Comment by KevinFairgrieve** [comment]
Updated via Ethos suite exactly as per last time, and success.

Can only guess I got a bad update last time.

Closing this issue as resolved.

**Comment by KevinFairgrieve** [comment]
Found my model image had gone. So added that back to the model and out of curiosity tried a special function. Transmitter locked up!

**Comment by KevinFairgrieve** [comment]
Removed model image tried special function. Works as expected. Now to investigate the model image!

**Comment by KevinFairgrieve** [comment]
Added model image back in and locks up! Removed image and works as expected again
![Vulkan](https://user-images.githubusercontent.com/20424058/182022687-45d24754-edf8-4c98-9779-fdb76b429f22.png)
!

**Comment by KevinFairgrieve** [comment]
Going back to 1.2.11

**Comment by KevinFairgrieve** [comment]
[Desktop.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9228699/Desktop.zip)
model and radio bin in zip file.

**Comment by mgsanna** [comment]
I've tested your model.... it is corrupted... it make froze the radio.... maybe you have to remake all over... and if you have pass from old version of firmware it become corrupted....

**Comment by KevinFairgrieve** [comment]
So it must be getting corrupted from the conversion to 1.3.0 as it works fine in 1.2.11

I will also check it on my X12S which is my backup radio.

**Comment by KevinFairgrieve** [comment]
Works fine on my X12S.

Going to delete the model from the X20, update to 1.3.0 and start with a fresh model.

**Comment by KevinFairgrieve** [comment]
Updated to 1.3.0 (again), tried editing a different model`s special functions. Yep transmitter freezes.
Going back to 1.2.11 again.

**Comment by MIKE-DAILEY** [comment]
Try renaming the SD card /bitmaps/models/ to /bitmaps/x/ so the system cannot load your model images and see if it works.

**Comment by KevinFairgrieve** [comment]
> Try renaming the SD card /bitmaps/models/ to /bitmaps/x/ so the system cannot load your model images and see if it works.

Still crashes and locks up the TX

**Comment by KevinFairgrieve** [comment]
[model01.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9244964/model01.zip)
Could some one please take this model which is a 1.2.11 spec and import it into 1.3.0 and see if they get the same system crash that I get. Fully understand if any one does not wish to submit their TX to the strife of removing the battery every time it hangs.

Really want to get 1.3.0 to work as on the strength of it I have ordered a MM. Hoping at long last just to take one TX to the field with me.

**Comment by KevinFairgrieve** [comment]
Desperation was beginning to set in, and my patience was running out.

So I updated the RF Firmware to 2.2.2 Still the same.

Used ETHOS suite to update the bootloader via DFU. Success, well so far any way. 

I will close this issue once I am completely happy!!

**Comment by mgsanna** [comment]
> Desperation was beginning to set in, and my patience was running out.
> 
> So I updated the RF Firmware to 2.2.2 Still the same.
> 
> Used ETHOS suite to update the bootloader via DFU. Success, well so far any way.
> 
> I will close this issue once I am completely happy!!

don't desperate for so little problem,  I think that something is going wrong with some of your sd card or model file corrupted, once I had a strange issue, dued by my update/downgrade of the radio.... I think they will solve as soon as possible.... If you see all the implementation and bug solving in less than a year... It'sd astonishing fast solving and fast implementation, and as far as I know they mantain all the promise.... even the multimodule support .... so be a little bit more patient..
Only a stupid question ethos is working as a operating system and the rf is working even without ethos, why do you think that updating RF firmware could solve your problem?

**Comment by KevinFairgrieve** [comment]
why do you think that updating RF firmware could solve your problem?

I was clutching at straws.

**Comment by mgsanna** [comment]
Because Ethos and RF are separated... you don't have a RF problem, it's a Model problems, in any case you make a good choice to update TD ISRM, but only because all update are improving and correcting....
in your case I think there is problem with corruption of data maybe of the model file or sd card root... I had also a similar problem when I use a sdcard with mac os and then put inside a dji fpv drone... the filesystem was not perfect so all the recording become corrupted....

**Comment by KevinFairgrieve** [comment]
Happy to report that after the upgrade to 1.3.1 all works as expected.

Closing this issue.
