### ISSUE TITLE
telemetry input values do not work in the mixer.

### ISSUE THREAD

**Issue by JaroslavFalcon** [FrSkyRC/ETHOS-Feedback-Community#182]
for example: rssi is OK.
voltage, vario, does not work
it is probably necessary to have reference values of min max.
for example altitude 200m = 100%, 0m = 0% or speed 0km / h = -100%   200 km / h = 100%

**Comment by bsongis-frsky** [comment]
@Nicholas-Luoyi we would need a configurable limit min / limit max for each sensor
