### ISSUE TITLE
Lowercase "ü" missing

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1820]
Horus X10S Express
Hello, I can not find the lowercase "ü". this is already over several versions.

**Comment by Devil-IdT** [comment]
Hello, Horus X10S ISRM too.

**Comment by Wolepo** [comment]
I was already afraid that it was just me.

**Comment by Wolepo** [comment]
Hello,
Since the issue is still open, I'll bring it out again. The small "ü" has been missing for several versions.
For a given reason, I use EXT1 and 2 for stick switches. Since they are analogue inputs, the switch positions must be evaluated with the help of logical switches. For their designations, it makes sense to mark the switch positions with the usual arrows (↑, -, ↓). However, they are not offered in the selection.
Would it be possible to add these arrows?
Thank you for your understanding.

Translated with www.DeepL.com/Translator (free version)

**Comment by BernhardFe** [comment]
It would be also nice if you can add the arrow from left to right you are using in the mixer selection menu for some mixers. E.g.  QR-> SR, HR -> WLB, SR -> QR... I would like to use this arrows as well when I rename another mixer the the free mixer.

**Comment by bsongis-frsky** [comment]
Are you sure for the ü ?

![image](https://user-images.githubusercontent.com/50834778/206027365-236b69fd-f64c-4df1-8668-895abd8f813f.png)

**Comment by bsongis-frsky** [comment]
@BernhardFe You have to use 2 chars:  `=` and `>` to build this arrow

**Comment by bsongis-frsky** [comment]
@Wolepo ü is not accessible with the rotary encoder. It will be fixed in 1.4.5

**Comment by Target0815** [comment]
On the X18S, the small "ü" is present. In German, however, there is äöü and also ÄÖÜ. I also find the capital "Ö", but the rest?

On a smartphone keyboard, you can find these letters on the normal keys aou. It might also be good here if you can set a multiple assignment of a letter (aAäÄ etc.) via an extra button.

**Comment by BernhardFe** [comment]
I' didn't recognised the "ü" on the virtual keyboard, because there are so many letters didn't used for the the German language on the keyboard and I tried to use the wheel. That's my fault. ;-)
But to make it better, we have language dependent setups. Why not showing only the relevant letters for the language like on the PC key-board? This makes the overview better. The set of special characters may be setup together with the language file?

**Comment by BernhardFe** [comment]
@bsongis-frsky Yes, you are right. I'm just using the work around "->". 
But your arrow is much better readable in the listings and uses only one character. 
The arrow is just in the system today, why not showing it in the key-board? 
Of cause, it is a nice to to have, but it would be very nice to have this on the key-board and klick-wheel.

**Comment by bsongis-frsky** [comment]
My arrow is made of the 2 letters `=` and `>`!

**Comment by BernhardFe** [comment]
Please have a look in the Headline (NAME) of the screen. There you can see how it looks for me.
![screenshot-2022-12-07-31379](https://user-images.githubusercontent.com/86232280/206118417-b9bf4237-38fb-41b3-bb14-a0ac9860762c.jpg)

**Comment by bsongis-frsky** [comment]
I forgot you are from DE!
I need to find a solution then, you will give some electricity when we need ;)
