### ISSUE TITLE
Need documentation on MPP

### ISSUE THREAD

**Issue by huths0lo** [FrSkyRC/ETHOS-Feedback-Community#1824]
Just loaded version 3.0 on my X18.  Nothing has changed on the model RF system config.  I dont see any options for MPP or Serial.  Please provide a quick walkthrough on how to use it.  I've been waiting patiently for this update, specifically for MPP support.  I almost bought another radio today, just so I could use my Blade helis.

**Comment by MIKE-DAILEY** [comment]
This should help you https://www.rcgroups.com/forums/showpost.php?p=49550649&postcount=18844

**Comment by mawzthefinn** [comment]
Closing as solution provided
