### ISSUE TITLE
1.3.0: erratic behaviour due to inproper model names

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1825]
Inproper model names can result in faulty behaviour even in 1.3.0:

You are able to give a name longer than 11 chars and you can program your model,
but after changing to another model the "long name" model is no longer accessible

One user tried the name "Das ist ein TEZ" what caused all other models to vanish
(more detailed misbehaviour not given, but i can ask if requested)

It seems that the Input Field for model names doesn't catch all types of exceeded naming conventions.

**Comment by strgaltdel** [comment]
one user did some testing to replicate the issue in a systematic way:

(1) ensure you have an "own" category like "test"
(2) add model in category test an give it a name which exceeds naming conventions (15 Chars .. blanks etc..)
(3) navigate into other category (here "home" >> all models vanished )
(4) press page up / page down in category "home" >> models reappear
(5) navigate to category test >> "long name" model remains invisible

until you stay in the "long name" model-memory, you can edit parameters, even after reboot
After changing active model to an "old" one, you won't be able to get access to the "long name" model because it remains invisible in category test.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/182639137-19f20b6d-2b3b-4b2b-9ba2-ee4ca705e9eb.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/182639193-6cce87f2-0bef-42dc-89be-2d9a86ac89f2.png)
