### ISSUE TITLE
Sensor Conflict Remains in 1.3.0

### ISSUE THREAD

**Issue by darkernoise** [FrSkyRC/ETHOS-Feedback-Community#1827]
While the frequency of the "Sensor Conflict" warning has decreased, it still happens multiple times in a flight with fully upgraded 1.3.0 and firmware.  On this plane, I have no additional sensors installed either.  

Radio: X20S
RX1: SR6
RX2: R9MINI-O
ESC: Neron S 60

Would this warning be logged anywhere in order to see which sensor(s) the radio thinks are problematic?

**Comment by m0p3d** [comment]
Dididnt get the reason either, but can confirm ongoing issue

**Comment by WismyYao** [comment]
We haven't reproduced this phenomenon, can you try the following ?

**Comment by m0p3d** [comment]
[model07 - Copy.bin.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9244042/model07.-.Copy.bin.csv)
@WismyYao Renamed model to .bin.csv just remove the .csv

**Comment by darkernoise** [comment]
[Ultimate3D.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9244245/Ultimate3D.zip)
Sure.  Attached model.  Though, please note that this has no installed sensors beyond those built-in to the SR6, R9MINI-O, and the Neuron S 60.  The Neuron is connected via SPORT and the SR6 and R9MINI-O are connected via SBUS.

To clarify, I was receiving this message on startup and every 30 seconds.  Now, it happens about once every few minutes.  There were no other warnings during the flight.

Thank you!

**Comment by WismyYao** [comment]
Sorry, we still have no way to reproduce this issue.
Here is a beta firmware that records telemetry logs, can you use this firmware to test  ?

Below are the test steps:

**Comment by m0p3d** [comment]
@WismyYao  @bsongis-frsky  Here the requested logging - includes 3 times playing sensor conflict
[telemetry.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9265067/telemetry.log)

**Comment by WismyYao** [comment]
I do see data in the log that would cause a conflict.
It is convenient to repeat the operation again, and  open "Discover new sensors” in the telemetry interface,  then share with me the screenshot of the entire interface of telemetry?

**Comment by WismyYao** [comment]
> @WismyYao @bsongis-frsky Here the requested logging - includes 3 times playing sensor conflict [telemetry.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9265067/telemetry.log)

I do see data in the log that would cause a conflict.

You may used  GR8 receiver  + RB30/40 , they have some same telemetry data. 
It is recommended to modify the APPID of the RB30/40  to resolve .

**Comment by m0p3d** [comment]
Sm-modellbau unisense-e together with gr8 are used. Unisense working in the same configuration in every older version without issues.

Could you please give some additional info which sensor conflict exists /Id is overlapping?

**Comment by WismyYao** [comment]
> Sm-modellbau unisense-e together with gr8 are used. Unisense working in the same configuration in every older version without issues.
> 
> Could you please give some additional info which sensor conflict exists /Id is overlapping? @WismyYao ESC rpm 070B60 , ESC cons 070B60 rpm and consumed capacity are on same sensor Id (unisense telemetry) FRRSKY_ESC_RPM_CONS_FIRST_ID maybe thats the trigger. Check vs telemetry data protocol documentation -> thats normal

The same telemetry data (with same APPID) but from two different devices (different physical IDs), the program will default that the two data conflict, and one of the APPID needs to be modified

**Comment by m0p3d** [comment]
But isnt everything like it should be ?
Didnt get what needs to be changed and why it worked before updating ethos without any issues!

**Comment by darkernoise** [comment]
Just an update from me.  I took the plane out last weekend and confirmed that the sensor conflict happens every flight.  I have not had time to test custom firmware yet as my schedule is really busy.  Though, could you please confirm, did you all test with the FrSky components I listed?  Again, the error happens for me every time and is easily repeatable.  I would like to confirm that you all tested this hardware yourself before you ask me to start running custom firmware.  Please confirm:

Hardware again:

RX1: SR6
RX2: R9MINI-O
ESC: Neron S 60

**Comment by 00steven** [comment]
I have this setup to get the sensor conflict
Tandem x20 ethos version 1.3.0
x8r pro
Redundancy bus 20
2 x FrSky FLVS ADV Voltage Sensor (Without Screen) to monitor 10s 2p
When I discover the Redundancy bus there is no problem. As soon as I connect and discover the 2 FrSky FLVS ADV Voltage Sensors, the sensor conflict starts

The problem exists when connecting the sensors t receiver and when setup is done through redundancy bus. 
It worked before and stop working after the update to 1.2.8

**Comment by bsongis-frsky** [comment]
I will take this issue.
1) @00steven what are the 2 appID / physId for your 2 ADV Voltage Sensor, I want to be sure they are different each other
2) @darkernoise I will check it here
3) I am not sure that Sm-modellbau fullfills the protocol (different physId / appId), I will check 2) first and get back to you

**Comment by bsongis-frsky** [comment]
@darkernoise how do you connect the Neuron S60 on your setup? Would you also confirm that if you disconnect it there is no Conflict anymore?

**Comment by darkernoise** [comment]
Hello Bsongis.  I unwrapped the Kapton to verify the wiring.   

ESC VCC -> R9 VCC , ESC VCC -> SR6 VCC
Neuron GND -> R9 GND -> SR6 GND
Neuron SPORT: -> R9 Sport -> SR6 SPORT
R9 SBUS-OUT -> SR6 SBUS-IN 

To answer your question, if I disconnect the Neuron, there is no conflict.  Though, that would make sense she Neuron is the only SPORT sensor source.

Could the issue be that I have SPORT to both the R9 and the SR6?

I am really not keen on flashing test firmware on my only working radio.  

Thank you!

**Comment by bsongis-frsky** [comment]
Thanks, it should not be needed, we will try to replicate it with your exact setup

**Comment by m0p3d** [comment]
@bsongis-frsky Just wondering how to get the latest version of protocol docu for myself - just found very old versions .

Waiting for feedback if everything is implemented like u expect or not .thank you

**Comment by bsongis-frsky** [comment]
@darkernoise 

We don't recommend linking R9 SPORT and SR6 SPORT together, they work independently and out of sync, so wrong data will be detected by the radio and obviously conflicts may arise

**Comment by bsongis-frsky** [comment]
@m0p3d 

please give us all appId / physId which are sent by your device, we thing the mistake is there

**Comment by bsongis-frsky** [comment]
@00steven 

still waiting for your appId / physId

**Comment by bsongis-frsky** [comment]
I will keep the issue open until all answers received, but I will remove the milestone.
For now it seems there is no bug in Ethos in this area, which is good!

**Comment by michelkorthout** [comment]
Hello,

I am also using the combination UNISENS-E and Archer GR8:

I have tested this issue with 2 different versions of the UNISENS-E firmware (version 1.19 and 1.20)
I have set my UNISENS-E to use Physical I 0x83. (03)

Below the data that is detected when finding the sensors in ethos. (both versions are giving the sensor conflict every 30 seconds)

**V1.19**

rpm       	03 0500
Altitude 	03 0100
ADC4	03 0910
Fuel		03 0600
VFAS	03 0210
Current	03 0200
Vspeed	03 0110
VFR		03 F010

**V1.20**

RPM		03 0500
altitude	        03 0100
Fuel		        03 0600
VFAS		03 0210
current		03 0200
Vspeed		03 0110
		        03 0B60
esc consumption	03 0B60

Receiver is sending this telemetry data
Vspeed     1A 0110
Altitude    1A 0100

Seams that version 1.20 i using the applicationID 0B60 twices, which may indeed lead to sensor conflicts.

Then i guess that the issue with both versions, is the applicationID for altitude and Vspeed. Both the receiver as the UNISENS-e are using 0100 and 0110.

If this is the cause, then i do not understand the concept of this implementation... The combination of PsysicalID and applicationID will make a complete unique address e.g. 03 0100 and 18 0100 are then unique!
Then there is no need to change applicationID's when using multiple sensors of the same type.

Second question: can i change the applicationID's of the receiver (GR8)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/186422453-68a5b633-2ec6-4bd6-a6f1-b258f2688968.png)

What is the 2nd 03/0B60 sensor?

**Comment by bsongis-frsky** [comment]
Same AppID and different PhysID will produce a Sensor Conflict, except some special sensors like VFR, RSSI, ADC1, SWR, etc.

**Comment by bsongis-frsky** [comment]
Here VSpeed and Altitude are not good

**Comment by michelkorthout** [comment]
Hello,

When i use version 1.20 of the unisens-e firmware, an empty record is presented this is the address 0B60. 

But for me it still sounds difficult:
that means that:
030100
1A0100
Will cause a conflict, right? Even if they are on different PhysID's. 

Can i change the APPID of the receiver? 

ps. I also send a mail to sm-modellbau to look at this issue.

**Comment by m0p3d** [comment]
@bsongis-frsky @WismyYao  Wismy already uploaded for me special ethics release to produce logging files which are also available above - didn't this log contain all info you need regarding app phy IDs..... ? Thanks

**Comment by darkernoise** [comment]
> @darkernoise
> 
> We don't recommend linking R9 SPORT and SR6 SPORT together, they work independently and out of sync, so wrong data will be detected by the radio and obviously conflicts may arise

Ah, ok.  I have been running the SPORT sensors to both the R9 and the 2.4 receiver in order to receive telemetry on both bands.  It seemed to be working with the prior versions of Ethos.  At least I did not receive any warnings with this configuration previously.   Though, if you are saying the that the receivers don't prefix the protocol addresses, then that would make sense that the sensor addresses are duplicated.  Any way, I disconnected the SPORT from the R9 and can confirm after testing today that the problem is resolved.  There is no further sensor conflict warning.  

Thank you for the assistance!

**Comment by 00steven** [comment]
> I will take this issue.
> 
> 1. @00steven what are the 2 appID / physId for your 2 ADV Voltage Sensor, I want to be sure they are different each other
> 2. @darkernoise I will check it here
> 3. @m0p3d I am not sure that Sm-modellbau fullfills the protocol (different physId / appId), I will check 2) first and get back to you

@bsongis-frsky 

Yes even with two different Physical id's.


Now on version ethos  3.2 The problem has gotten worse.

I can discover the two different sensors  1 at a time 
when I change the id  none of them work anymore.

I don't have the time to check any further but maybe there is a problem with the telemetry of the RB20 and R8 pro and the sensors ?

**Comment by 00steven** [comment]
I was setting up a new model and tried this again.
Ethos 1.4.7 x20
The problem is still there 
Both FLVS ADV sensors work and send data that I receive. ( different physical ID's  17 ad 19 function ID 300) 
But the transmitter keeps warning for a sensor conflict.

**Comment by Storchy1** [comment]
I had a similar problem. I have two temperature sensors with the same appID but different physID. 
The sensors use the FBUS protocol.
I have made the appID different and no longer get sensor conflict warnings.

**Comment by craigywsm** [comment]
I am having this issue.
I have just migrated my  jet over to Ethos on the X20S
I am running ACCST v2 with two RX8R and the RB20.
When running on my X9D 2019 I did not have any issues but with my X20S on Ethos when I power the model I get an error mentioning sensor conflict.
If I remove the  Zavionics Telemetry adapter  via the Sport I do not get the warning 
I will provide the list of sensors later

**Comment by jogybaer0815** [comment]
what a waste on the display for the info about the module and no info about appID and physID.
And only the acoustic output via a sensor conflict without further information makes the search for it the content of the day.
Definitely improve here.
Luckily the acoustic sensor conflict output can be switched off...
