### ISSUE TITLE
request: LUA get the name of the current Flighmode

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1828]
please make it possible to get the Name of the current Flightmode.

**Comment by loetefix** [comment]
> Please try this:
> 
> `system.getSource({category=CATEGORY_FLIGHT_VALUE, member=CURRENT_FLIGHT_MODE}):stringValue()`

No, it only returns the Flightmode-number as a string, but not its name.

**Comment by bsongis-frsky** [comment]
The previous proposal will work in 1.4.5
