### ISSUE TITLE
Check Boxes missing for long press menu items in v1.3.0

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#1829]
Tandem X20
Ethos 1.3.0
Bootloader 1.2.11

All long press menu items are missing their check boxes and are hard to select and impossible to tell if they have been selected.
![screenshot-2022-08-02-73052](https://user-images.githubusercontent.com/16928210/182513019-0a211ea4-3774-45ae-9a0e-0d17830d09b1.jpg)

**Comment by m0p3d** [comment]
Confirmed - same here since 1.2.11 very confusing. At least there should be highlighting of the selection - checkboxes have been doing the job!

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/182621610-b08330a8-eb88-44b6-ac39-8c7aeaa52f1f.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/182621686-71e75e19-badb-493c-8be9-de960ecf295c.png)

**Comment by bsongis-frsky** [comment]
This was missing in all places where we allow Options for a Source
