### ISSUE TITLE
Models name on SD card  FW.1.3.0 -  X20

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1830]
Hello,
would it be possible to change the name of the models in the "models" file of the SD card of the radio, automatically for the models created in the past. the last model I created, the exact name is displayed in the list, but the others still not.
Thank.
![20220803_092859](https://user-images.githubusercontent.com/84312994/182549876-35811779-0604-4a67-9d80-197810ba979f.jpg)

**Comment by Mobidick1966** [comment]
I tried to change the name of the models via the radio, in the "edited model" page but nothing changes.

**Comment by Wolepo** [comment]
This cannot be done in the transmitter, but the name can be changed on the PC.

**Comment by Mobidick1966** [comment]
I have more than 40 models registered in the radio.
In different folders.
Which are in random order.
Not easy to find the right model on the PC.
The latest model created is the aptly named Slick 580, which is last on the list, but not in the radio directory.

**Comment by Wolepo** [comment]
Open the corresponding model file with Notepad++. The name of the model is in the first line. You can then use this for the renaming.

**Comment by Mobidick1966** [comment]
Thanks .
It is done .
