### ISSUE TITLE
VAR Mix - only default weight can exceed +/-100

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1832]
When creating a VAR mix on 1.3.0, the default weight can be +/-200, but any additional weights are limited to +/-100

All selectable weights should have the same range.

**Comment by strgaltdel** [comment]
can fully support this request
would like to see this extension too

**Comment by mawzthefinn** [comment]
Note that when using a source as an weight, +/-200 is possible on the additional weights, only manually set weights are limited to +/-100

**Comment by mawzthefinn** [comment]
THis is still an issue

**Comment by strgaltdel** [comment]
"keepalive"
would like to see this "extension"
