### ISSUE TITLE
Entering numbers with one decimal place

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1833]
Hello
For telemetry announcements I have created a ring counter with free mixers. With the buttons SH short I switch to the next value and with SH long one step back. The resulting channel values are evaluated with logical switches and thus triggered value announcements.
Now to my problem: In the mixers I can enter values only in whole percent (e.g. 10%). But the value of a channel is displayed in the servo monitor with one digit after the decimal point. The more steps are used or the smaller the step size is, the greater the deviations caused by rounding. The function A ~ X can no longer compensate for this, since its snap range becomes too small. 
Is it possible to use the values Offset and Weightings in the mixers as well as the value(X) in the logical switches with one decimal place?
Thanks for the interest

**Comment by hrenz** [comment]
There is a real counter missing at Special Funktions since one year
like OTX has

**Comment by Wolepo** [comment]
Hello,
I have also tried a trim mixer. This has the advantage that it can count up and down. Also, you can set the step size in 1µs steps. Thus each step size is feasible and I would have saved 3 auxiliary mixers.
But it lacks the crucial feature that you can preset a self determined value. So this possibility is unfortunately ruled out.

**Comment by mawzthefinn** [comment]
If you are testing on the channel, you can use a VAR mixer or Offset mix to inject a preset value to the channel.

**Comment by Wolepo** [comment]
Neither the one nor the other works, because the trim mixer stores its value and thus the channel is set accordingly. What is missing here is a way to make the trim value externally adjustable with a fixed value. Preferably for both directions.
