### ISSUE TITLE
at Logical Switch using LiPo Sensor Value only 0V or 33,60V possible Ethos 1.3.0 X20S

### ISSUE THREAD

**Issue by NorbertHeli** [FrSkyRC/ETHOS-Feedback-Community#1834]
It´s nearly he same Problem as Issue 1013 - only now 0V or 33,60V can be adjusted.

**Comment by Hartinger** [comment]
Norbert has used 4 cells, whereas I had used 3 when raising the previous issue.
So it seems that 8,4V x number of cells is the only value that can be set.

**Comment by NorbertHeli** [comment]
I tried it now with 3S and 6S - same result - 0V or 33,6V
I think its about the new Sensor FLVS ADV - that has the ability to habdle 8S = 33,6V
Thats not the problem in Telemetrie Sensors.
The problem is, I can´t adjust the value at logical switch - so I can´t make warning, when the Lipo is to low.
Also at Cell low. 
I can let tell me by switch the values, or by display see Lipo total or cell value - but no warning.

**Comment by Wolepo** [comment]
Hello
The error lies in the default setting of the "step size selection bar". It is preset to the largest possible step size. If you set it to the beginning, you can set the values normally again.

**Comment by Hartinger** [comment]
Unfortunately, the change of the step size is not saved. When you leave the logical switch menu and then reenter, the problem is exactly the same as before.

**Comment by mawzthefinn** [comment]
This should be fixed in newer firmware, please confirm on 1.4.3
