### ISSUE TITLE
Sensor RPM not Divided

### ISSUE THREAD

**Issue by erti74** [FrSkyRC/ETHOS-Feedback-Community#1835]
Hallo Team ,

helicopter speed is not divided by two propellers. RPM is displayed double high.

Telemetrie Jlog 2.6 ,Hobbywing 80V4 ,1.3.0 Ethos

**Comment by mawzthefinn** [comment]
Set the RPM Telemetry mode to Gear, then adjust maingear and pinion teeth to suit.

This works for general electric RPM as well, by setting maingear to 1/2 motor pole count and pinion to 100

It is non-intuitive and needs work.

**Comment by bsongis-frsky** [comment]
Do you mean we should add blades for helicopters too?
