### ISSUE TITLE
Cannot have 2 sensors FLVSS linked to a single Rx

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#1836]
Context:
X20S 1.3.0
R-10-Pro
FLVSS (2x)

Issue:
Cannot link 2pces FLVSS to a single Rx R10-Pro (to be used for 12 cells packs)
Conflicting IDs cannot be avoided by configuring both FLVSS

Last configured ID Physical and ID Application) are applied to both sensors (1 sensor being disconnected from Rx at time of config.)

Result: no sensor is functionning

**Comment by phaedra-tm** [comment]
From RCgroups:
"You cannot jump between the Edit/Device Config screens of the two sensors with only one sensor connected.

Before you even try to discover both sensors you must use this process:
1. Discover sensor 1 and write down the Physical and Application IDs.
2. Unplug sensor 1.
3. Discover sensor 2, go into Device Config and change both the Physical and Application IDs, taking care that both are unique in your sensor system. Please refer to the Smart Port Telemetry section of the manual for a table of default IDs.
4. Plug in sensor 1 again.
5. Repeat Discover Sensors. You should now have both sensors working correctly.

If you want to make changes in Device Config, only have the relevant sensor connected. At least until both have been discovered with unique IDs."

**Comment by Eagleowl1** [comment]
Answer to the above in RC Group

Thanks for your patience, let me try to clarify:
First of all, before starting as I am a newbie with telemetry I read the user manual (V1.2.10 rev3 page 111 and following) and I think I followed all the steps you are kindly describing.
Nevertheless, yesterday I did not manage to get to the right settings.

For unknown reason, today it went OK, using the same material and the same model.
For me it is solved and I cannot even reproduce this issue anymore...
I have no idea why I had this before and I also do not believe Gremlins exist.

Only if of any interest, the video https://1drv.ms/u/s!ArIOwubNi2uzwXxl...01jQM?e=OgfDa5 is showing what happend yesterday (many times) during above described step 3
steps 1 and 2 performed with no issue

Status after step 2 and before starting step 3.
Discover sensors : OFF
"Lipo" sensor unplugged
"Lipo2" sensor plugged in

Description of the screen
1. Screen shows unplugged sensor "Lipo" in red (which is OK)
2. Checking ID values of "Lipo" 02 / 0303 (no change made)
3. Move to "Lipo2" and go to configuration
4. Noticed "Lipo2" has same IDs values as "Lipo" 02 / 0303 (was discovered while unplugged "Lipo")
5. Change of "Lipo2" both IDs to 01 / 300
6, While no action from user "Lipo" (still unplugged) becomes also active together with "Lipo2" (white dot blinking)
7. Go to "Lipo" again and just check ID values in configuration 01 / 300 --> both IDs of "Lipo" were automatically! copied from "Lipo2"
8. Both sensors are "blocked" and must be deleted to restart the separate discoveries

**Comment by WismyYao** [comment]
> 

Have you tried discovering new sensor?

**Comment by Eagleowl1** [comment]
Yes I also had a current sensor (150A) daisy chained and no issue with current sensor

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bsongis-frsky** [comment]
I think it has been fixed since in FLVSS firmware, right?

**Comment by Eagleowl1** [comment]
For obscure reasons, the issue solved by itself.  Magic!
All firmware up to date from day one.
In the mean time I have dropped the MLVSS (not safe enough in my view).
Also I have not acquired any of the new FLVSS ADV, so cannot say for these.
No new element appeared.
Can be closed.
