### ISSUE TITLE
1.3.0 GPS speed in kmh is wrong by a factor of 1.8

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#1838]
Hello since the update of my Tandem X20S to Ethos 1.3.0 is again the same problem with the GPS speed. Km/h is not correct by a factor of 1.8. With version 1.2.10 the speed was still correct.
Same problem as with #740
Greeting bluelex73

**Comment by WismyYao** [comment]
Sorry，Sorry, we haven't found any problems after many tests .
Can you see if the unit settings are correct? Or can you share your model file to us ？

**Comment by bluelex73** [comment]
hello, attached the desired model file-
I need the unit for the GPS speed in kmh. I have also set it that way.
With version 1.2.10, the speed in kmh was also output correctly. After the update to 1.3.0 the output is no longer correct. I suspect it was swapped kn with kmh. You had already solved the problem once see #740. With the version 1.3.0 the error was again there.
Greetings bluele
[model02.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9307091/model02.zip)
![screenshot-2022-06-11-54221](https://user-images.githubusercontent.com/84685639/184089122-2f260c5b-5974-44fc-a38c-02dee2f90c47.jpg)
x

**Comment by bluelex73** [comment]
Hello
I have tested again today extensively.I have deleted all telemetry data and searched the sensors again.
The GPS speed is now correct!
Please excuse the wrong message
Greeting bluelex

**Comment by bluelex73** [comment]
I deleted all telemetry data and had the sensors searched again.
The error was probably with me the GPS speed in kmh is now correct.
Please excuse the wrong message 
Greeting bluelex
