### ISSUE TITLE
X18s 1.3.0 top bar icons on top eachother

### ISSUE THREAD

**Issue by bennytel** [FrSkyRC/ETHOS-Feedback-Community#1839]
X18s 1.3.0 when display show volt + RSSI- unreadable fonts ontop explanatio
![WhatsApp Image 2022-08-06 at 18 13 15 (1)](https://user-images.githubusercontent.com/110733310/183255214-c872d4be-1dd3-4304-8104-45ac72a10eb4.jpeg)

**Comment by yak-54** [comment]
My Horus was the same till i updated the system fonts as well to new version 1.3.0 fonts

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/210602356-a5fec31c-4f32-4aa8-bab6-7f3c5ac22b82.png)
