### ISSUE TITLE
Special Function no “PlayVario” on Ethos

### ISSUE THREAD

**Issue by wizan9z** [FrSkyRC/ETHOS-Feedback-Community#184]
For glider pilots the rise and fall of the vspeed beeping of the vario onboard GR6 or GR8, chasing thermal is important. The latest Ethos firmware is not able to play the beeping under special functions like “PlayVario” in FROS special function.

**Comment by WismyYao** [comment]
PlayVario can be setted in model-telemetry screen if you have discovery data "vario speed".
