### ISSUE TITLE
X12S Fonts not legible

### ISSUE THREAD

**Issue by myfivezees** [FrSkyRC/ETHOS-Feedback-Community#1840]
I recently (within the past week) had my X12s updated to ETHOS by Aloft Hobbies. Several menus are not functioning properly and the script is not legible. I have attached a few photos illustrating this.
.
![IMG-2124](https://user-images.githubusercontent.com/110739813/183279839-0cc05146-249c-4adc-8d52-1ca45758a3b5.jpg)

![IMG-2122](https://user-images.githubusercontent.com/110739813/183279849-46c947e5-d446-451f-be92-49c227dc6267.jpg)

![IMG-2121](https://user-images.githubusercontent.com/110739813/183279862-6977d491-1399-4244-9b81-bc2d7b219c67.jpg)

**Comment by MIKE-DAILEY** [comment]
A good solution would be to install ETHOS SUITT on your PC and have it check your system and update anything needed including the fonts.  You can download ETHOS SUITE from here https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.2.11

**Comment by myfivezees** [comment]
Thanks so much for the reply. I actually have ETHOS SUITE installed on my
PC. I hesitate to do as advised given that Aloft Hobbies installed ETHOS on
July 29th. I suppose it's possible that they did not do it properly. The
reason I sent it and paid them to do the install is because I wasn't
confident to do it myself. Very frustrating to say the least.

Thanks again and I may try as you suggest.

**Comment by MIKE-DAILEY** [comment]
Did they install ETHOS version 1.3.0. ?  It was available on the 29th.

**Comment by myfivezees** [comment]
Yes they did.

**Comment by MIKE-DAILEY** [comment]
Looks like the fonts are missing then.  ETHOS SUITE can fixit.

**Comment by myfivezees** [comment]
Which files should I download to fix this issue ?

**Comment by MIKE-DAILEY** [comment]
After the X12S is connected to ETHOS SUITE 1.2.11. select update bitmaps.   The font folder and font files are part on the bitmaps folder.

**Comment by myfivezees** [comment]
How do I initiate the update ? I am connected to Ethos Suite and have
selected the bitmaps folder.

**Comment by MIKE-DAILEY** [comment]
If it is displaying "UPDATE SYTEM BITMAPS" in the green box at the bottom of the SUITE window like my posted screen click the down arrow at the right side of the green black.

**Comment by myfivezees** [comment]
I can't tell you how much I appreciate your help and patience. When my
screen shows "Bootloader" it does not show a version number in the upper
right hand corner as I believe it should.

**Comment by MIKE-DAILEY** [comment]
So ETHOS SUITE will not work, right?

**Comment by myfivezees** [comment]
Correct.

**Comment by MIKE-DAILEY** [comment]
OK.  Lucky you have 1.3.0. on the X12S and you can flash the bootloader from the X12S.   Need to download the 1.2.11. bootloader for the X12S from here and unzip it. https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.2.11 With the X12S connected to your PC in bootloader mode copy the bootloader to the X12S.  Root of the SD would be OK.  

1. Eject the X12S drive from your PC.
2. Power off and on the X12S.  
3. Go to SYS/File Manager and navigate to wherever you put the bootloader.frsk file
4. Click on it and select flash.  When done click OK.
5. Reboot the X12S and reconnect to your PC in bootloader mode. Note 1.2.11. on X12S screen. 
6. Now use ETHOS SUITE to update the X12S.

**Comment by myfivezees** [comment]
I will try that.

**Comment by myfivezees** [comment]
THANK YOU...THANK YOU !!!!!!!! It is working now.

**Comment by MIKE-DAILEY** [comment]
Good news!  Don't know what happened at Aloft.  They are known to be very excellent.  

Now than you can use ETHOS SUITE updates will be very easy.

**Comment by myfivezees** [comment]
What I don't understand is it worked fine for about 15 minutes before this
happened.
