### ISSUE TITLE
Lua: make model-UID  available

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1843]
sometimes one have same model names for different models,
or even more often one have several "programs" / "configs" for the same model.

You can't rule out that a user defined several "programs" under the same name.
So it would be helpful under certain conditions, that lua would get access to models unique ID in order to identify which "program" is actually used
There are some situations where scripts can have different "flows" dependent on it's UID.

(method could be something like model.getUID)

thanks in advance

Udo

**Comment by bsongis-frsky** [comment]
It will be `model.id()` and it will return 2 values, one per module
