### ISSUE TITLE
1.3.0 Emergency Mode through the special function Screenshot

### ISSUE THREAD

**Issue by Peterbilt84** [FrSkyRC/ETHOS-Feedback-Community#1846]
When triggering the special function screenshot, the transmitter goes into emergency mode. The function is triggered by the SH button. But this error also occurs with the other switches.

The other special functions such as value announcements or track playback work with the SH button.

Replacing the SD card did not help.

**Comment by mawzthefinn** [comment]
Working fine on my X20, possibly a hardware issue with the SD reader?

**Comment by Peterbilt84** [comment]
By deleting unused Lua scripts the problem could be solved
