### ISSUE TITLE
Feature Request: QWERTZ Keyboard

### ISSUE THREAD

**Issue by stefanfluck** [FrSkyRC/ETHOS-Feedback-Community#1848]
A QWERTZ keyboard option would be nice for non-US users.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/185920842-d708613d-85e2-46ee-9ad5-2cb9ad130b22.png)

![image](https://user-images.githubusercontent.com/50834778/185920945-02eb0472-a1dd-4e7b-b774-2d614cde646a.png)
