### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by hamelsveld** [FrSkyRC/ETHOS-Feedback-Community#1849]
I would be great if FrSky would be compatible with Powerbox telemetry. there are a lot of planes using powerbox hardware for redundancy.

**Comment by mawzthefinn** [comment]
That would require PowerBox supporting S.Port or FBus telemetry as they do for other telemetry protocols. The limitation here is on PowerBox's side, not FrSky's. 

PowerBox current supports the following telemetry protocols: PowerBox P²BUS, Futaba S.BUS2, Jeti Ex-BUS, Spektrum SRXL2, Multiplex M-Link, JR X-BUS and Graupner HoTT

Most of these are much less common than S.Port, I would recommend requesting S.Port and/or FBus support from PowerBox.
