### ISSUE TITLE
Improves - touch control, show digital rssi

### ISSUE THREAD

**Issue by JaroslavFalcon** [FrSkyRC/ETHOS-Feedback-Community#185]
Text and numeric values can only be entered with the rotary encoder.
Create a virtual keyboard to enter texts.
Create a numeric keypad to enter a numeric value.

Touch the clock and the battery icon to open the appropriate control panel

Add an option for the RSSI icon to show the digital value as it is for the battery icon

**Comment by loetefix** [comment]
+1

**Comment by Chandrayaan-git** [comment]
+1

**Comment by bsongis-frsky** [comment]
Please open one issue per request, otherwise it's difficult to follow

**Comment by bsongis-frsky** [comment]
Virtual keyboard = #189

**Comment by bsongis-frsky** [comment]
#190 and #191 for the 2 other requests
