### ISSUE TITLE
Feature request: alternative model selection menu

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1850]
Please add an alternative Model selection menu with no Pictures. just a list like openTX has on Taranis.
for every category a list.
maybe a checkbox in the system menu named --> alternative model menu <-- to activate it

i think this is clearer and faster for some people.

**Comment by MIKE-DAILEY** [comment]
With ETHOS You can create your own custom screen and select it as the default start up screen.

**Comment by loetefix** [comment]
I mean the menu where you select a Model

**Comment by mawzthefinn** [comment]
Any such menu would be generally incompatible with touch UI best practices. Text line selection is slower than the current touch icons, and would really require the use of the selector wheel to be able to interact with reasonably. Plus with the screen layout you'd likely get less models listed onscreen than the 10 you do now, requiring more scrolling or screen shuffling.

There's very good UX design reasons why the list selection is limited to the old B&W radios with their small and low-res screens on OpenTX and EdgeTX.

**Comment by loetefix** [comment]
Slower then it is now ? No way.

**Comment by mawzthefinn** [comment]
> Slower then it is now ? No way.

Most definitely. Have you timed how fast model selection actually takes? (it's VERY fast if you use the long-press shortcuts currently present). I've measured less than 5 seconds from main model screen to getting the checklist for the new model for models, using both touch and the selector and the long-press short cuts.

Ignoring the image load time (which is irrelevant to model selection, you can select and load models before the images load today), you're going to go from 10 models on the screen to 7 based on the other screens with text lists. That means that unless you have 7 or less models per tab, you will have to jump screens more with the list to cover the same number of models, which means slower selection. 

Plus given general touch accuracy, the smaller names in a list require more precise touching to select. 

The only part of the current model selection process that is slow is population of model images. That needs work.

**Comment by loetefix** [comment]
How we could live all the time without touch, lol.

**Comment by bsongis-frsky** [comment]
The bitmaps are loaded in the background, you may go very fast to select your model, before its bitmap is loaded!
