### ISSUE TITLE
1.3.0 Rpm telemetry range max zero

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#1851]
X20S - Neuron esc
I'm not able to change the max range value from rpm telemetry. It's set to zero and therefore 0 allways is displayed.

**Comment by Wolepo** [comment]
Correct, does not work with my X10Express either. Furthermore ESC rpm (10 0B60 (ISRM Rx0) is not found. If it is present from previous versions, it does not provide any data. 
*** Translated with www.DeepL.com/Translator (free version) ***

**Comment by bsongis-frsky** [comment]
Already fixed in 1.3.3. Checked just now with a Neuron 80
