### ISSUE TITLE
X20S Logical Switch Bug

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#1855]
I use the MLVSS sensor for Lipo Voltage. Whit the logical switch I have write a Low battery alert and use a Logical switch to activate it ad one precise voltage. Whit the last release 1.3.0 the voltage value is not settable. only 0 or max value. In the old version this value is editable for select the preferrer voltage.
Need an upgrade in the new release please!
Is very important!

**Comment by Wolepo** [comment]
Good luck!
The value can be adjusted by setting the step size back to the first step.

![Schrittweite2](https://user-images.githubusercontent.com/90325526/184621655-3dcbb7f0-a67e-4b8d-965b-b355f3165903.jpg)

The error is known

**Comment by carlogianneschi** [comment]
Now is not changeable. 0.00 or 33.60v

**Comment by Wolepo** [comment]
Highlight the telemeric value > Press and hold the PgUp/Dn key > Turn the scroll wheel to the left and reduce the bar, possibly all the way to the left > Release the PgUp/Dn key and use the scroll wheel to adjust the value.
In picture seven the value is changed from 10.2V to 8.5V.
![Schrittweite3](https://user-images.githubusercontent.com/90325526/184627915-890ef011-1d5b-4c94-bc4f-0c58c2c866d5.jpg)

**Comment by carlogianneschi** [comment]
On the radio not in the Suite
I use Linux and the suite don't work.
I need to change the value directly on the radio

**Comment by Wolepo** [comment]
Yes, this is done at the station. You do not need a suite for this.
