### ISSUE TITLE
after updating 1.3.0  picture issue 

### ISSUE THREAD

**Issue by Njerre** [FrSkyRC/ETHOS-Feedback-Community#1856]
After update from release 1.3.0,
model bitmap are not loaded while they are still in the map bitmap/user folder. 
Or has something changed in the pixels format that has become unreadable?

**Comment by Wolepo** [comment]
You need to rename the [user] folder to [models].

**Comment by Njerre** [comment]
Wolepo,
Thanks, I made it.
Too bad that not all models load automatically!
I have to do half of the models manually.

**Comment by bsongis-frsky** [comment]
Request already opened in Ethos Suite
