### ISSUE TITLE
Ethos Suite - feature request - include version check and upgrade of TD-ISRM

### ISSUE THREAD

**Issue by applewood** [FrSkyRC/ETHOS-Feedback-Community#1857]
Would be a nice feature, appreciate TD-ISRM doesn't frequently get updated, but still would be a nice feature in include in the suite.  To make it the one stop tool for all software upgrades on ETHOS systems.

**Comment by CliffEvans** [comment]
Makes sense!

**Comment by CliffEvans** [comment]
I am surprised that this has not been looked at yet.

**Comment by mawzthefinn** [comment]
ETHOS Suite now does let you update the TD-ISRM via the FRSK Flasher tool and lists all available firmware, but does not include automatic updates with the rest of the radio. 

Automatic updating would be a nice extension of this capability

**Comment by CliffEvans** [comment]
Yes, auto update would be the way to go.

**Comment by craigywsm** [comment]
This would be a good feature

**Comment by bsongis-frsky** [comment]
Still valid

**Comment by mawzthefinn** [comment]
Version check is now in ETHOS Suite 1.4.12
