### ISSUE TITLE
Model in file manager, but not selectable in Model Select. File corrupt?

### ISSUE THREAD

**Issue by stefanfluck** [FrSkyRC/ETHOS-Feedback-Community#1859]
Ethos - X18
Firmware 1.3.0 EU
Internal Module N1.0.1 FW 2.2.1 (EU-LBT)
Updated to this after purchase.

I programmed a F3K glider, which was stored in Nand. As I did not find [these ](https://www.rcgroups.com/forums/showpost.php?p=49071685&postcount=58)SD instructions readily, I proceeded on my own. I inserted a fresh formatted 32GB SD card (FAT32), added a empty "models" folder on it, and put it into the Tx while off. Then switched it on and changed the Storage Location to SD card in General for everything. 
This led to the model (which was selected and set as active at that time) being not shown in the Model Select menu. The snipechstrong.bin is still present in the File Manager. I copied it to the PC as backup. I tried to move the model around in the File Manager, but it did not reappear. I went ahead and updated all elements of the X18 (but it showed all up to date), but that also did nothing. Is my model recoverable? I read about models not showing up because incompatibilities, but until I lost the model in the selection screen I did not change the FW configuration.

[snipechstrong.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9353175/snipechstrong.zip)
)

I dont manage to reproduce this behavior. No problem to do the reprogramming, but I am worried that it might happen again some day. Is the above linked SD instructions valid?

Thank you for having a look!

**Comment by Nicholas-Luoyi** [comment]
It's truly a bug somewhere. But for now please try to switch the model storage location in System - General menu. Or select Radio/ SD Card in the file manager before entering the model select page.

**Comment by stefanfluck** [comment]
Hi Nicholas!

I was able to reproduce the behavior. It happened again after creating a model called "Snipe CH Strong", and it disappeared again. This string has 2 whitespices compared to models called "test 1" etc, so I thought 2 whitespaces were the problem and filmed it. It's probably not due to 2 whitespaces though, as it works most of the times. See video here: https://youtu.be/y9BAmzi8VG0?t=91

**Comment by Nicholas-Luoyi** [comment]
Ah... That makes sense. It's due to the bug of length limit for model name. It will be fixed in the next release.

**Comment by stefanfluck** [comment]
Yeah a shorter filename solves it. Thanks!
