### ISSUE TITLE
touch keyboard screen for faster inputs of names and valuesis is missung

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#186]
The input of names and numbers must be greatly improved
A keyboard image for fast and easier input is missing
in format of  QWERTY or QWERTZ
not in format ABCDEF

rotary encoder for letters searching selecting ist from yesterday

**Comment by bsongis-frsky** [comment]
Duplicated of many remarks, I have opened #189 for this
