### ISSUE TITLE
Ethos 1.3.0 - output names dissappear

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#1863]
This problem has been occuring while building a glider template using free mixers and VAR mixes, similar to my other templates. 

After assigning names to several outputs, some of the output names simply dissappear (they are replaced by empty strings). The names dissappear from both the Outputs menu, and the Mixers menu where they are referenced. I can't see a definitive pattern, but it seems to happen when switching from the Outputs menu to some other menu e.g. Mixers screen.

Several outputs are affected each time (but not all).

This has happened three times now on the same setup. A little frustrating as there arround 30 outputs which need to be defined.

Configuration:
- X20
- ETHOS 1.3.0

**Comment by Nicholas-Luoyi** [comment]
I cannot reproduce here. Would you please confirm you choose the correct selection after switching the output channel?

**Comment by RC-SOAR** [comment]
Not sure I understand the question, but just to clarify:

1. I enter the Outputs menu, 
2. I enter names for several outputs
3. I go to the Mixers screen to define a few mixers
4. At some stage, while editing the mixers, I notice that some of the output names in the mixer list are blank.
5. I go back to the Outputs screen, and confirm that some of the output names have been reset to an empty string.

This is a procedure which I've used successfully many times before.

I will try to reproduce the issue when next week.

**Comment by bsongis-frsky** [comment]
@Nicholas-Luoyi He is right, I just checked, I had a model fully configured. I removed all mixes and now all outputs names are empty.
