### ISSUE TITLE
Multiprotocole and Blade Mcpx

### ISSUE THREAD

**Issue by Dirana28** [FrSkyRC/ETHOS-Feedback-Community#1866]
The Blade Mcpx is in DSM DSM2 and CH1 CH6  . In the 1.3.0 it is not possible to have CH6   the minimum is CH8

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/185870564-998433f8-10c2-47de-91e1-009d81806f0a.png)

**Comment by bsongis-frsky** [comment]
`registerMultimodule()` will have a different signature in 1.3.1, it will be possible to define a minimum / maximum channels count:

![image](https://user-images.githubusercontent.com/50834778/185896453-5e9f1597-26e2-48b4-b5e9-85127f76849c.png)

Moreover some protocols need a fixed channels count, and it will be possible: 

![image](https://user-images.githubusercontent.com/50834778/185896590-da32d53a-4bf7-4fbb-a813-889f3c751510.png)
