### ISSUE TITLE
Inverting the Throttle Control does not invert the associated Trim

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1867]
As the title already says, if the input to the throttle mixer is inverted, i.e. idle position is with throttle stick in forward position, the throttle trim is not inverted but remains as is. Tested with Horus X10S Express and ETHOS 1.3.0.

**Comment by jbesse262** [comment]
Who flies like that!?

**Comment by Hartinger** [comment]
Not me, I have raised this issue on  behalf of someone else. But this is irrelevant; if there is the option to reverse the throttle, the trim needs to match the reversed behaviour.

By the way, I beleive it is quite common for Heli pilots to fly like this.

**Comment by MIKE-DAILEY** [comment]
The trim on the channel inverts as expected with the inverted input.  The direction of the trim lever movement does not change for low high trim.

**Comment by Hartinger** [comment]
That's correct, the title of the issue is not fully precise. The desire is that the direction of the trim leaver movement is also reversed when the input is inverted.

**Comment by guycnicholas** [comment]
Trims and Sticks are independent. If I was going to reverse the throttle, I would make a mix assigned to an unused channel and use that as the throttle. If I also wanted to reverse the trim, I would do the same thing with it.  I would sort of argue it works as expected.

Not answering the question, and I know it's irrelevant, but as a long time heli flyer in the US, I can say that I have never seen anyone fly with a reversed throttle.

**Comment by jbesse262** [comment]
> By the way, I believe it is quite common for Heli pilots to fly like this.

No, it really isn't.

**Comment by EngelMT** [comment]
Here in Europe I know several pilots who use inverted trottle stick. So Hartinger is right when he think that thrim must be inverted too. To make such walkaround is possible but contradicts the DNA of ETHOS to be an easy-to-use system.

**Comment by hrenz** [comment]
It works for the elevator
Invert elevator then automatically inverts the trim
