### ISSUE TITLE
When TD protocol is selected the 2.4 Ghz RSSI fluctuates wildly when Info screen is selected.

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#1868]
Hello

X20S
ETHOS: 1.3.0 FLEX
HF FW: 2.2.2
TDMX: 1.0.7

See attached video.

There is no fluctuation under Access.

Enzo

https://user-images.githubusercontent.com/87656206/185896266-8db64edf-6266-49f2-bbb5-e6b3315096d3.mp4

**Comment by mawzthefinn** [comment]
I’ve noticed the same for 2.4GHz RSSI and VFR on my TD-R10

ACCESS is rock solid, 900MHz is rock sol
