### ISSUE TITLE
problem with racing mode

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#1870]
On x20, with last firmware.
Racing mode, once enabled for a model, is shown as not supported on radio restart
On Sr6 or sr8 receivers with last firmware too

**Comment by MrD-RC** [comment]
You can't use `always on` as the receiver isn't connected when the model loads. It doesn't know if Racing Mode is supported, until it has bound to the receiver.

This will get it working every time.
