### ISSUE TITLE
ETHOS X20 V1.3.0 Simulator keys F1 to F6

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1872]
where are the keys F1 to F6 in the simulator
should  be Key 1 to 6

![2022-08-25_071056](https://user-images.githubusercontent.com/6217896/186580661-43396d26-efcc-4533-aa7f-2e5b11a56a90.jpg)

**Comment by STC148** [comment]
Besides the function buttons I also miss the trim buttons in the simulator.

**Comment by jurajjurej** [comment]
Yes. Without trimmers, testing is very limited.

**Comment by bsongis-frsky** [comment]
Function Switches support added for 1.5.0

**Comment by jurajjurej** [comment]
Which keys control the function switches?

**Comment by hrenz** [comment]
normal 1,2,3,4,5,6

**Comment by jurajjurej** [comment]
Is there any overview of all the simulator control capabilities?

**Comment by STC148** [comment]
My simulator controls don't seem to work properly anymore. I can only move the elevator and throttle stick in one direction. The trim buttons are only available for the left stick. The function buttons are only available for 5 and 6.

https://user-images.githubusercontent.com/85410070/224133666-537cda26-24be-4cbc-bec4-cbfd4a6e01c3.mp4

**Comment by jurajjurej** [comment]
They don't work properly for me either.
