### ISSUE TITLE
Improment : Request SLOW UP and DOWN with Mixer Flaps to Elevator

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#1873]
Hi Bertrand,

I didn't remeber if this request has been done !

Thanks

**Comment by mawzthefinn** [comment]
Use the Flaps mixer output as the input for the Flap->Elevator mixer and this will work correctly, and also not require you to adjust slow in 2 spots every time you change something.

If you use the Flaps source instead, you are skipping all the Flaps processing.
