### ISSUE TITLE
LUA Funktion form.addFileField not wok in Ethos Simulator 1.2.11

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1874]
Hi Bertrand, 
the Lua Function 
form.addFileField(line, nil, "/audio/en/system", "any", function() return filename end, function(newValue) filename = newValue end) 
and  
form.addFileField(line, nil, "/audio/en/system", "audio", function() return filename end, function(newValue) filename = newValue end)
will not work 
the LUA Function 
form.addBitmapField(line, nil, "/bitmaps/models", function() return bitmap end, function(newValue) bitmap = newValue end) 
works very well.
Here my LUA code
print("Load file")
widget.filename=nil
line = form.addLine("Datei")	
form.addFileField(line, nil, "/audio/en/system", "audio", function() return filename end, function(newValue) filename = newValue end)__
the Error Message in debug screen 
    **Load file
    terminate called after throwing an instance of 'std::logic_error'
    what():  basic_string::_M_construct null not valid
    QObject::~QObject: Timers cannot be stopped from another thread**

what is wrong?
Many Thanks

**Comment by bsongis-frsky** [comment]
Is it possible you share your full script (or you reduce it as much as possible) so that we can check & fix it quicker?

**Comment by Benno00** [comment]
Hi Bertrand, 
I took your FLSS LUA and added configure to test it. The error message is
terminate called after throwing an instance of 'std::logic_error'
   what(): basic_string::_M_construct null not valid
QObject::~QObject: Timers cannot be stopped from another thread
here the adjusted LUA flvss
`
local function create()
  local sensor = system.getSource("LiPo")
  return {sensor=sensor, value=nil}
end

local function paint(widget)
  if widget.sensor ~= nil then
    lcd.font(FONT_L)
    local y = 10
    lcd.drawText(10, y, "Total = " .. widget.sensor:stringValue() .. " (" .. widget.sensor:stringValue(OPTION_CELL_COUNT) .. " cells)")
    y = y + 30
    for i = 1, widget.sensor:value(OPTION_CELL_COUNT) do
      lcd.drawText(10, y, "Cell[" .. i .."] = " .. widget.sensor:stringValue(OPTION_CELL_INDEX(i)))
      y = y + 30
    end
  end
end

local function configure(widget)

	 line = form.addLine("LOAD FILE")	
	 form.addFileField(line, nil, "/audio/en/system", "audio", function() return filename end, function(newValue) filename = newValue end)   -- will not work
	-- form.addFileField(line, nil, "/audio/en/system", "any", function() return filename end, function(newValue) filename = newValue end)   -- will not work	
	-- form.addBitmapField(line, nil, "/bitmaps/models", function() return bitmap end, function(newValue) bitmap = newValue end)             -- work fine

end

local function wakeup(widget)
  local newValue = nil
  if widget.sensor == nil then
    widget.sensor = system.getSource("LiPo")
  end
  if widget.sensor ~= nil then
    newValue = widget.sensor:stringValue()
  end
  if widget.value ~= newValue then
    widget.value = newValue
    lcd.invalidate()
  end
end

local function init()
  system.registerWidget({key="flvss", name="LUA flvss", create=create, configure=configure, paint=paint, wakeup=wakeup})
end

return {init=init}`

**Comment by bsongis-frsky** [comment]
* your latest comment is modified to have the code coloration right

**Comment by bsongis-frsky** [comment]
Fixed in 1.3.2

![image](https://user-images.githubusercontent.com/50834778/187144991-fdb1efa9-62c7-4ff7-a6ba-750388ffbf16.png)

**Comment by Benno00** [comment]
Hello Bertrand,
that was really quick, thank you very much

Best regards Benno
