### ISSUE TITLE
FLVS ADV LiPo Voltage Sensor with Zavionix cells widget.  X20S. Ethos 1.3.0

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#1875]
Ethos 1.3.0 I tried using the Zavionix cells widget with the FLVS ADV Lipo sensor. The widget failed to consistently display the lipo information as per the pictures.   
I have 2 X20S units and the second one is on Ethos 1.2.11, I bound that one up and tried again. This time the widget displayed 100% correctly. I tried this by power cycling the TX & RX each time with three different lipo 4s batteries. 
I then rebound the first TX on 1.3.0 and tried again doing the same power on /off cycle each time.  The problem returned. I have had communication with Lior Zahavi and he asked me to log this on Github.

![IMG_0671](https://user-images.githubusercontent.com/96422592/186647723-92748222-e132-46b8-aeee-e0fd17a330f2.JPG)
![IMG_0669](https://user-images.githubusercontent.com/96422592/186647745-0b488a89-b2fd-4763-aa21-fb0d28805dc9.JPG)
![IMG_0668](https://user-images.githubusercontent.com/96422592/186647756-debf86fd-a29f-486d-ab7c-ff8fc6f1792f.JPG)
n

**Comment by bsongis-frsky** [comment]
We cannot support users scripts. The author should contact us here if there is an issue.

**Comment by i3dm** [comment]
> We cannot support users scripts. The author should contact us here if there is an issue.

why is the issue closed before we get to the fault?

im here and happy to answer any questions.
have not yet investigated this issue.
just can confirm there.were no issues until and including 1.2.11
has anything changed in LUA from 1.2.11 to 1.3.0? the release notes have no info about such changes.
