### ISSUE TITLE
IMPROMENT : Flight mode and trim

### ISSUE THREAD

**Issue by zeblade64** [FrSkyRC/ETHOS-Feedback-Community#1876]
hi,

Is it possible to add function in flight mode and separate trim like opentx : 

In Ethos there are two options : same trim for all flight mode or separate trim.
In opentx there are three options for each trim/flight mode combination:

    ':n' means 'use trim value from flight mode n'. This option provides a mechanism for sharing a trim between multiple flight modes.
    '+n' means add this trim to the trim from another flight mode.
    '--' disables the trim.

**Comment by mawzthefinn** [comment]
This is a duplicate of part of #215 I'm closing this duplicate and any further discussion can continue under that issue
