### ISSUE TITLE
Values in 'View per Channel' view are incorrectly shown clipped to +/-100%

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#1877]
It seems that in 'View per Channel' view only, the value of the mixer stack is shown clipped to +/-100%. This is incorrect since the mixer stack values are no longer truncated, and it's also inconsistent with (a) 'Table' view and (b) the green bar in the mixer editor.

To reproduce:

1. Create a channel with a single Free Mix
2. Assign one input, and one output to the mix.
3. Set the mix parameters so that the mixer output varies between, say, -30% and +130% depending on the input.

In both the mixer editor and 'Table' view, the full range of mixer values is displayed, that is: -30% to +130%
However, in 'View per Channel' view, values greater than 100% are shown clipped, that is: -30% to +100%

Ethos 1.3.0, FCC
X20

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/187209586-faa0e2ff-7f0b-41fb-bdd5-7c5f23b05414.png)
