### ISSUE TITLE
USB connection is not working

### ISSUE THREAD

**Issue by KissmanCZ** [FrSkyRC/ETHOS-Feedback-Community#1879]
Hi, if I try to use USB connection with X20S in powered ON state, connection dialog is just blinking on the screen. Video on this link: https://www.youtube.com/watch?v=QPhWY4CruIk

Tried with 6 different cables (4x USB-A to USB-C and 2x USB-C to USB-C including Apple certified cables). With connected power supply to my laptop and also without. With other 2 USB-A to USB-C cables (different from previous one) it is doing completely nothing.

Ports I am using on my laptop are hi-amperage ports (I can charge another laptop from my laptop with USB-C cable).

Interesting is, that this is not happening on my desktop (with all same cables), so I know that they are all working). **BUT** I tried on 4 laptops with exactly same result.

In bootloader mode, it is something simillar... no drives will open and **Bootlader** and **USB plugged** notifications looping very quickly.

Win 11 Pro 21H2
Tandem X20S
Bootlader 1.2.11
Ethos 1.3.0 EU
TD-ISRM 2.2.2

**Comment by Beastyboy80** [comment]
The output power is too low.
The laptop needs a control signal to bring high power

**Comment by KissmanCZ** [comment]
USB is a standard... so problem is on the side of the X20S. And to be honest, if X20S is powered only from USB when it is connected to the computer for data trasnfer, it is pretty stupid HW design.

> The output power is too low. The laptop needs a control signal to bring high power

So you are saying, that X20S is incopatible with USB standard.

**Comment by MIKE-DAILEY** [comment]
Working OK here with a Samsung laptop.

**Comment by bsongis-frsky** [comment]
> And to be honest, if X20S is powered only from USB when it is connected to the computer for data trasnfer, it is pretty stupid HW design.

It is not

**Comment by KissmanCZ** [comment]
> It is not powered by USB when connected in bootloader / firmware mode
Glad to hear! So it cant be a problem with power supply via USB port... so what now? It is possible that my unit is faulty in some crazy way? Or can I help somehow to debug this issue?

**Comment by MIKE-DAILEY** [comment]
You can try fully charging the X20S and then see if the USB connection works. With the X20S power off fully charge until the power LED goes off.

**Comment by KissmanCZ** [comment]
> You can try fully charging the X20S and then see if the USB connection works. With the X20S power off fully charge until the power LED goes off.

I didn't mention it in my original post, but of course I tried that too. Unfortunately no change.

**Comment by MIKE-DAILEY** [comment]
Did you charge until the power LED went off?

**Comment by KissmanCZ** [comment]
> Did you charge until the power LED went off?

Yes, as I wrote...

**Comment by marciomc-github** [comment]
Try changing the cable to other with better quality. I got sorted here by changing the cable and changing the USB port.

**Comment by KissmanCZ** [comment]
> Try changing the cable to other with better quality. I got sorted here by changing the cable and changing the USB port.

Apple, Belkin, Vention, Baseus, Choetech.... what better cable I can try?

So now I understand this is by design, but it would be great to identify what is causing this and maybe FrSky will update their USB board in X20S in new revisions.

**Comment by marciomc-github** [comment]
> > Try changing the cable to other with better quality. I got sorted here by changing the cable and changing the USB port.
> 
> Apple, Belkin, Vention, Baseus, Choetech.... what better cable I can try?
> 
> So now I understand this is by design, but it would be great to identify what is causing this and maybe FrSky will update their USB board in X20S in new revisions.

any of those you mentioned should do the job. Try changing the USB port as well.

**Comment by KissmanCZ** [comment]
> any of those you mentioned should do the job. Try changing the USB port as well.

None of them work. It looks like you didn't read my original post... More laptops and USB-A to C and USB-C to C means more USB ports and devices.

**Comment by marciomc-github** [comment]
> > any of those you mentioned should do the job. Try changing the USB port as well.
> 
> None of them work. It looks like you didn't read my original post... More laptops and USB-A to C and USB-C to C means more USB ports and devices.

I did, but you did not mentioned all those brands. 
Well I got sorted by changing the cable.. good luck.

**Comment by KissmanCZ** [comment]
So I bought another USB high quality cable with 56k resistor and X20S is not responding to that cable at all. No USB connection popup message on the screen after connection to the laptop. Any comments from FrSky team pls?

**Comment by ManicMiner-Es** [comment]
near two years passed and i'm still suffering same error

**Comment by aguilerabr** [comment]
@ManicMiner-Es @KissmanCZ looking for usb connections problems I reach this post. I have the same issue with my X20S. It so frustrating. I'm gonna try this: cut the power wire from USB connector. I'll post results here.
