### ISSUE TITLE
Rpm 

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#188]
Please could we have an option for adding poles/blade numbers etc to obtain correct RPM data.

**Comment by islandflight** [comment]
Found device config screen for RPM  although can't seem to edit the data in this will experiment a bit further and re-open if it continues to be a problem

**Comment by Hobby4life** [comment]
You should open this case because there is nothing to edit at all.

I have a S32 Logger that outputs RPM data, only I can not set Blades/Poles and Multiplier.

The RPM Device config is for the Frsky Sensor itself.

**Comment by islandflight** [comment]
Hi I opened a new issue 're this #192. There needs to be an option for selecting the no of poles on the esc when selecting the esc rpm. This issue has been assigned but not yet resolved.
