### ISSUE TITLE
Deleting last mix goes to Emergency Mode on X20S

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#1880]
I am on 1.3.1, and I am not sure if the issue existed prior to this or not. 
I have a model (attached) and when I delete the last mixer the radio goes into emergency mode.

[model01.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9438280/model01.zip)

**Comment by yak-54** [comment]
what radio you using ?

**Comment by yak-54** [comment]
yep had the same issue on X12S some time ago and it was fix some time ago i hope its no back
can you  reproduce it on an another model ?

**Comment by guycnicholas** [comment]
Yeah, I just created a brand new model, deleted the 4 default mixes and went into emergency mode.

**Comment by STC148** [comment]
I can confirm, the same problem also exists with the X10S
