### ISSUE TITLE
SR10Pro looked out / FAILSAFE with GAS engine

### ISSUE THREAD

**Issue by timmybeetle** [FrSkyRC/ETHOS-Feedback-Community#1882]
Pilots

SR10Pro looked out, no response to radio control, maybe going into failsafe.
While landing the plane, distance plane-pilot 100 meter the plane nosed in.
At the plane no movement of surfaces was noted, toughing the surfaces you could feel the servo motors where under voltage.
Sadly user did not enter failsafe in his Radio and also did not activate log.
He is new to Tandem and I'm helping him with this.

1. ETHOS version 1.0.11, EU
2. TD-ISRM HW;1.4.0 FW;2.1.9(EU)
3. Archer Receiver HW:1.3.0 FW:2.1.5

5. Plane is a gas engine with electronic ignition.
6. dual power redundancy 

Frsky mentioning on there website that this receiver is designed also for gas engines airplane!
ps if you look at Frsky regarding this receiver they claim following

ACCESS protocol with Over The Air (OTA)
Built-in 3-axis gyroscope and 3-axis accelerometer sensor
Multiple flight modes and configuration methods (LUA & Freelink)
Supports signal redundancy (SBUS In)
Supports power redundancy (Dual battery ports)
Full control range with telemetry
S.Port / F.Port / FBUS

Anti-interference in spark-ignition
Anti-Vibration

External battery / device voltage detection 
![aa99c01d-bf5e-4702-9472-6ae132a753ea](https://user-images.githubusercontent.com/84274019/187061635-9c1ab423-3ce7-44fa-9ae4-60bf414581ec.JPG)
![b47a8a11-c4ef-4579-abb3-60e23fc06855](https://user-images.githubusercontent.com/84274019/187292231-69946da7-85e2-438e-9887-019addef5a49.JPG)

**Comment by mgsanna** [comment]
all the components are outdated about firmware and also RF.... you are using one of the old firmware of the radio.... now firmware is 1.3.1. .....
but it's so strange because I've used the same firmware and same receiver and same setup with gas engine.... on august/september of last year (made some 15/20 flights without any issue....) then moved on, on new firmware release....
I think that is important to upgrade radio and TD ISRM firmware, making the radio updated and upgrade also every rx firmware..

**Comment by Joetrin** [comment]
There is an update for the sr10 pro that addresses this.  Go to the frsky website and flash to latest sr10 firmware

**Comment by timmybeetle** [comment]
> There is an update for the sr10 pro that addresses this. Go to the frsky website and flash to latest sr10 firmware

So you telling me that when he bought this receiver, Frsky did make a receiver not fully tested and has a bug, no no no.
I'm not for testing there stuff and crash my 2000$ plane, sorry now way that this is normal operation.

**Comment by timmybeetle** [comment]
> all the components are outdated about firmware and also RF.... you are using one of the old firmware of the radio.... now firmware is 1.3.1. ..... but it's so strange because I've used the same firmware and same receiver and same setup with gas engine.... on august/september of last year (made some 15/20 flights without any issue....) then moved on, on new firmware release.... I think that is important to upgrade radio and TD ISRM firmware, making the radio updated and upgrade also every rx firmware.. It seem more a power issue... or servo stalling....

Hi
Ethos version and fw version should be save to fly a plane of several dollars, so if I fly now with the latest version and I do not update this for the next year after a year you telling me it was not safe to fly with this Ethos en FW version. makes no sense to me at all.
I know that sometimes a bug is reported and that FW ore Ethos is updated, but a system should be save to fly. 
About power issue, he has a dual power redundancy system in his plane.
After the crash we tested al servo's and did range test no issues where found there, we will do a test again in future with running motor, but this is something that should not happening with a receiver in a 2000$ plane, is my humble opinion.

**Comment by Joetrin** [comment]
> 

I'm not telling you anything, you can assume what you like.  The firmware for the SR10 has been around since 2021.

**Comment by timmybeetle** [comment]
> As stated immediately, I have flown my gasser even more pricey than 2K$ with the same configuration last year for almost 1 month or something like......without any kind of issue, but as you are using an upgradable system you "must" be aware and give a chance to get the best software/firmware.... but In any case Ethos is more than sure and RF LINK is one of the most robust..... so your complaint are childish because the system is working in a bullet proof way...... no body said that the system is not sure after a year.... maybe you have not understood as me other thousand of user get the same firmware and the same config as you... and nothing happened...
> 
> Nobody say that you affirm... so

Hello

thanks for yours reply and I understand an upgrading system, It's a friend who has this issue and I'm helping him with it.
I told him to update his Radio and receiver FW to the latest version, sadly he is new to Tandem (frsky) coming from Mulitplex Radio, so it's understandable that he needs some time to get used to this system.
Its good to read that you had no issues with ETHOS and receiver, but did you use de SR10Pro ore de R10Pro, just to be sure we talking about the same hardware.
Sadly I found on RCGRoups that there where pilots who had some issues with this specify receiver, SR10Pro in relation to GAS engine powered planes.
here is reference:
https://www.rcgroups.com/forums/showpost.php?p=46788189&postcount=594

https://www.rcgroups.com/forums/showpost.php?p=46607265&postcount=575

https://www.rcgroups.com/forums/showpost.php?p=46047823&postcount=416

I hope that I will be able to test again and when there is an issue that I can duplicate it, but now I will have Log enabled and I have set fail safe active, custom setting.
Regards Hans

**Comment by mgsanna** [comment]
> > As stated immediately, I have flown my gasser even more pricey than 2K$ with the same configuration last year for almost 1 month or something like......without any kind of issue, but as you are using an upgradable system you "must" be aware and give a chance to get the best software/firmware.... but In any case Ethos is more than sure and RF LINK is one of the most robust..... so your complaint are childish because the system is working in a bullet proof way...... no body said that the system is not sure after a year.... maybe you have not understood as me other thousand of user get the same firmware and the same config as you... and nothing happened...
> > Nobody say that you affirm... so
> 
> Hello
> 
> thanks for yours reply and I understand an upgrading system, It's a friend who has this issue and I'm helping him with it. I told him to update his Radio and receiver FW to the latest version, sadly he is new to Tandem (frsky) coming from Mulitplex Radio, so it's understandable that he needs some time to get used to this system. Its good to read that you had no issues with ETHOS and receiver, but did you use de SR10Pro ore de R10Pro, just to be sure we talking about the same hardware. Sadly I found on RCGRoups that there where pilots who had some issues with this specify receiver, SR10Pro in relation to GAS engine powered planes. here is reference: https://www.rcgroups.com/forums/showpost.php?p=46788189&postcount=594
> 
> https://www.rcgroups.com/forums/showpost.php?p=46607265&postcount=575
> 
> https://www.rcgroups.com/forums/showpost.php?p=46047823&postcount=416
> 
> I hope that I will be able to test again and when there is an issue that I can duplicate it, but now I will have Log enabled and I have set fail safe active, custom setting. Regards Hans

Yes we are talking about the same hardware, used with dle 111 gas with and without gyro, lot of people don't do a proper calibration and self-check and lot of people accuse New hardware instead being honest about the lack of notice reading (not your case obiusly) .
Seriously frsky access protocol and even more TD protocol are almost bullet-proof system....

**Comment by timmybeetle** [comment]
Updated my first comment,
Added HW and FW of receiver 

Hans

**Comment by Joetrin** [comment]
> Updated my first comment, Added HW and FW of receiver
> 
> Hans

Your rx firmware is from 2020, the 2.1.9 and 2.1.10 addresses the issue.

**Comment by timmybeetle** [comment]
> > Updated my first comment, Added HW and FW of receiver
> > Hans
> 
> Your rx firmware is from 2020, the 2.1.9 and 2.1.10 addresses the issue.

Sir

So if I understand this right what you are saying!
If I flew this plane in this configuration in 2020, and I had this failure it was bad luck for me to use this system in my plane?
In all due respect it sounds to me like the problem in the Boeing 737 MAX.
So Frksy sold me a product with a malfunction in it which may occur in our case!
Regards Hans

**Comment by timmybeetle** [comment]
To Bsongis-Frsky

I know it is not an issue in ETHOS but I mentioned it here that users are aware that we had this issue.
Maybe other users had similar experience with this Radio X20 ore X20S.
On RCGroups I found some info about this.
It seems that with FW updates this issue is solved, but I have to test first with old setup if I can duplicate issue and than I will update system to newest FW versions and test again.
A remark I have is, I as customer must be able to trust a system for 100% to use in my RC-plane?

Regards Hans

**Comment by Joetrin** [comment]
> > > Updated my first comment, Added HW and FW of receiver
> > > Hans
> > 
> > 
> > Your rx firmware is from 2020, the 2.1.9 and 2.1.10 addresses the issue.
> 
> Sir
> 
> So if I understand this right what you are saying! If I flew this plane in this configuration in 2020, and I had this failure it was bad luck for me to use this system in my plane? In all due respect it sounds to me like the problem in the Boeing 737 MAX. So Frksy sold me a product with a malfunction in it which may occur in our case! Regards Hans

I'm not saying or implying anything other than that there is firmware available. You are completely free to make up any story you want.  Enjoy!!!

**Comment by pstasek** [comment]
From my previous experience with stabilized SxR receivers, I'm very cautious when using them. Apart from regular receivers, stabilized receivers "boot up" significantly longer with no PWM signal on outputs. Any short-term voltage drop caused by a bad battery connection or servo stalling can force a reboot of about 5-10 seconds long, sometimes following full servo deflection, no matter, how the failsafe is set. The Quick mode makes the delay shorter but still significant. This issue is not a fault of the receiver, as it's always a problem with installation but with regular receivers, it's usually not noticeable or maybe a short glitch, while the stabilized receivers result in a fatal crash. Also, the vibrations of a gasser engine can cause more stress on power-hungry servos, which may cause voltage drops followed by reboots. It's important to dimension the power system well.
