### ISSUE TITLE
Multimodule tuning option does not give full range

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1883]
Ethos 1.3.1

The Multimodule tuning option does not give the full range of -127 to +127.

According to Pascal Langer’s Multimodule GitHub, the FrskyD protocol requires the tuning option. I added the option to my module/main.lua for FrskyD, and tried to tune a V8R4 receiver. It continues working with tuning values of 0 to 43. The parameter maxes out at +127, however if I try to go negative it goes to +255 and then +127. I don’t get any negative values. 

If bit 7 indicates a negative value, I would still expect to see from 128 to 255.

**Comment by bsongis-frsky** [comment]
I think the range has 255 values, from -128 to 127
