### ISSUE TITLE
1.3.1 Telemetry max Range for RPM 10000

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#1887]
RPM with 1.3.1 after remove and discover new works but the range is limited to 10000

**Comment by bsongis-frsky** [comment]
Are you sure?

![image](https://user-images.githubusercontent.com/50834778/187599808-48d18475-445f-4544-95d5-aa62743edf88.png)

**Comment by Cipta-de** [comment]
Neuron esc, don't know what's wrong. Strange will try 1.3.2 and report 
![IMG_20220831_200128](https://user-images.githubusercontent.com/78207054/187748100-e4276056-82ea-4c3e-9d9a-67e7bb6cdf66.jpg)
![IMG_20220831_200020](https://user-images.githubusercontent.com/78207054/187748156-152d265c-8c7b-4eaf-baf9-22b970b0af53.jpg)

**Comment by Cipta-de** [comment]
Same with 1.3.2
Delete all and discover all Neuron Telemetry.  At the Rpm Sensor no Name  automatically is added. The Sensor works but the max range is limited to 10000.
