### ISSUE TITLE
Var mix only allows +/-100% when adding extra weights

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1889]
Ethos 1.3.1

The Var mix only allows +/-100% when adding extra weights. The default weight correctly allows values of +/-200%.

**Comment by mawzthefinn** [comment]
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1832

**Comment by lthole** [comment]
Oops
