### ISSUE TITLE
Trims should be reset when disabling a trim

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1890]
Ethos 1.3.1

Trims should be reset when disabling a trim, otherwise you could get a fixed offset that is not obvious because this behaviour is unexpected. If a trim is disabled you would not expect it to be acting on a channel. If you want a fixed offset the Offset mix should be used instead. 

This behaviour is mentioned in the thread of issue #1525.

**Comment by bsongis-frsky** [comment]
Trims Disabled means "No Trims". The Trim value will be fixed and 0 in this case.
