### ISSUE TITLE
Suite Enhancement: Change "Update News" to "Updates News / History"

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1894]
Hi Developers,
you are doing a great job and I'm impressed how fast and agil you are doing changes on the ETHOS system even if there are so many request from a big user group. 
To show this in a better way, it would be great when you show all the releases and the done changes in the "Update News" section with the release date in the suite. The section can be renamed then in "Update News / History" showing the latest update above all others and allow to scroll through the history into the past.
Of cause, this is a nice to have and I can see this also in Github, but ist makes your done changes more transparent and all users can have a look when what was implemented.
Best Regards
Bernhard

**Comment by bsongis-frsky** [comment]
This issue has been fixed already. But please check with Andreas that the translation is right Auf Deutsch?

**Comment by BernhardFe** [comment]
Hi Bertrand,
since all the release notes on github are in english and to keep it simple, we should let it be in english as is. If someone can not understand the notes he/she may use the google translator. So I propose to close this issue as ready. The upper part of the text is already in german language. This is from my point of view good enough.
Thanks a lot for your effort!
Best Regards
Bernhard
