### ISSUE TITLE
improvement proposal: select "Flight modes" and "Logic switch" with "Analog" source

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#1895]
Context: FW 1.3.2 doest not allow to select analog sources for flight mode and logic switches.
Although it is sometimes possible to overcome this "issue" by using additional mixers and flight modes, in some cases it is not possible (or I have not discoverd the how to)

Exemples:
 Flight modes: in a "Landing mode" as the throtle is lowered to a given level, it would allow to switch to a different flight mode in which ailerons rate is increased.

 Logic switch: it would allow to define a range inside or outside it a different flight mode is (de)selected

**Comment by bsongis-frsky** [comment]
Just create a Logic Switch A < X with A = Throttle and X = 20%
Then you give this Switch a name and you can use it everywhere

**Comment by Eagleowl1** [comment]
OK got it, perfectly clear but not obvious for a non professional programmer or OTX specialist...or an "average" user...

Please explain briefly reasons preventing Analog source to be selected for Flight mode or Logic switch.
(aside from requiring an additional field to define the switching point).
