### ISSUE TITLE
Standard Flaps mixer still has +/- 100% limits

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1897]
Ethos 1.3.2

In the standard Flaps mix, the maximum Weight for each channel is still 100%. If you want to use this in combination with the Offset mix, you will probably need a weight greater than 100%

**Comment by hrenz** [comment]
its not a Problem, you don´t need a Offset
use a single curve und you will get 0% to 200%

**Comment by bsongis-frsky** [comment]
It should be changed to +/-200% to be consistent with the Butterfly mix

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/187886500-79365be1-b982-41f0-b142-b6b3d43a62f5.png)
