### ISSUE TITLE
X20S EU 1.3.2 external multimodule submenu disabled 

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#1898]
Hello,
the submenu for select the protocols is disabled in 1.3.1 and 1.3.2 versions.
in the version 1.3.0 the AFHDS protocol don't bid the receiver (whit a old multiprotocol module with bind button this work properly)

Radio x20s
version 1.3.1 and 1.3.2

**Comment by bsongis-frsky** [comment]
Please use the latest multimodule script as an example, it has changed in 1.3.1

**Comment by carlogianneschi** [comment]
Sorry, a little explanation
Where can I find the script?
how should it be used?

**Comment by MIKE-DAILEY** [comment]
Instructions are here https://www.rcgroups.com/forums/showpost.php?p=49550649&postcount=18844

**Comment by carlogianneschi** [comment]
I have resolved!
The original memory card is partially burned.
Using the backup card all work properly
