### ISSUE TITLE
Error in telemetry at speed from neuron and trip

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1899]
Hello!
Version 1.3.2 / X10Express
The speed range of the Neuron cannot be set. The maximum speed remains at 0rpm and therefore does not provide any values.
Also Trip is limited to 10km. But a normal glider flight can take it to much more distance.

**Comment by mawzthefinn** [comment]
For Neuron RPM you have to edit the ESC RPM sensor, set the mode to Gear, Maingear teeth to 1/2 motor poles and Pinion Teeth to 100.

**Comment by Wolepo** [comment]
Hello,
can you take a picture? I can not understand it.
This is how it looks to me:
![U pro min](https://user-images.githubusercontent.com/90325526/188261061-e3ef01c6-fd5b-49ac-9379-4b0fa4d61ddf.jpg)

**Comment by Wolepo** [comment]
Completely it looks like this:
![ESC U pro min](https://user-images.githubusercontent.com/90325526/188261362-2967f57b-0157-404f-9e36-b39a558632b0.jpg)

**Comment by mawzthefinn** [comment]
In your second screenshot, Zahnezahl Hauptzahnrad is 1/2 motor poles (on my Power46, which is a 14 pole motor, this is set to 7) and Zahnezahl Ritzel should be 100

You have mode set correctly.
