### ISSUE TITLE
The scroll wheel on the X10S Express does not work anymore with ETHOS 0.0.17

### ISSUE THREAD

**Issue by Fridolin1981** [FrSkyRC/ETHOS-Feedback-Community#19]
With the new pre-released ETHOS 0.0.17 the scroll wheel is not working anymore. Flashing the 0.0.16 again, the scroll wheel works fine again.

**Comment by mpjf01** [comment]
Just for info it does work on the non-Express X10S.

**Comment by Fridolin1981** [comment]
apparently something went wrong during the flashing process with 0.0.17. I went back to 0.0.16 and flashed again 0.0.17 and now the scroll wheel works fine. 

Sorry for the inconveniences.
