### ISSUE TITLE
 Edit mixer section

### ISSUE THREAD

**Issue by GiorgioCirelli** [FrSkyRC/ETHOS-Feedback-Community#1901]
Would it be possible to modify the mixer section by inserting the possibility of adding differentials 
(+ Add a new Differential) with the possibility of having a switch for their activation condition?
Thank you

![screenshot-2022-08-29-70649](https://user-images.githubusercontent.com/42900080/188288640-33afcbd7-2851-4443-acc0-c172fe2893bf.jpg)

**New mixer section**

![screenshot-2022-08-29-70663](https://user-images.githubusercontent.com/42900080/188288625-6990ee83-c56f-4eb0-a6b6-17e00ba7a8c0.jpg)

**Comment by mawzthefinn** [comment]
Note you can have selectable differential today using a VAR mix output to a high channel and then using that channel as the Source for  the Differential setting.

I wrote up a quick walk though on this exact use case here:

https://www.rcgroups.com/forums/showthread.php?4174941-Var-Mixes-and-Aileron-Differential

The ETHOS developers seem to have gone for ‘if it’s basic, it’s in the Mix, if it’s not, you can use a source and do it outside the mix’

**Comment by GiorgioCirelli** [comment]
Your proposed solution works well!
Only if all the basic settings are in the same mixer, everything is much simpler and more intuitive.
Anyway thanks

**Comment by WOODY1958UK** [comment]
HI - PLEASE EXCUSE CAPS - BUT I AM PARTIALLY SIGHTED - BUTTERFLY MIX - CAN YOU ADD AN 'OFFSET' TO FLAPS LINE - MAYBE EASIER TO ADD TO ALL LINES - SO I CAN EASILY PROGRAM FLAPS FROM -85% - SO FROM SAY 1000 - RATHER THAN 1500 AT THE MOMENT - HOPE THAT MAKES SENSE ??? - THANKS - LOVE ETHOS - JUST MOVING EVERYTHING THERE SLOWLY - CATCH YOU LATER - TAKE CARE - HAPPY FLYING - WOODY1958UK

**Comment by WOODY1958UK** [comment]
HI - REGARDING DIFFERENTIAL - GREAT IDEA - I HAVE CREATED 5 AILERON MIXES - AND PUT THEM INTO MY 5 FLIGHT MODES - CRUISE - THERMAL - SPEED - LAUNCH - LANDING - WORKS - IF THAT'S ANY HELP - WOODY1958UK

**Comment by WOODY1958UK** [comment]
HI - IN CREATING A BUTTERFLY MIX - CHANNEL ONE HAS SUDDENLY NOW HAS FLAPS DESCRIPTION - EVEN THOUGH STILL AILERONS - CHANNEL 2 IS NOW AILERONS - NOT ELEVATOR - JUST THE DESCRIPTION - AND SO ON - MAYBE BECAUSE I ADDED FLAPS TO MODEL - RATHER THAN PUTTING IT INITIAL BUILD ??? - WOODY1958UK

**Comment by WOODY1958UK** [comment]
HI - HA- ONLY FALLS DOWN WHEN YOU ADD TO MODEL WITH MIXERS ALREADY PROGRAMMED - SO DONM'T D ANOTHER PLAY - WORKS FINE IF YOU MAKE SURE YOU HAVE EVERYTHING IN INITIAL SETUP - SO DON'T WORRY GUYS - AM WORKING ON  A TEMPLATE FOR ALL MY MODELS - BASIC SETUP - 2 x AILERON - CH 1 + CH 5 - ELEVATOR - CH 2 - THROTTLE - C- CH 12H 3 - RUDDER - CH 4 - FLAPS - CH 6 + 7 - GYRO - CH 8 - COVERS MOST MODELS - ONLY NEED TO ADD AIRBRAKES TO BIG SCALE SHIPS - CH 9 + 10 - RETRACT - CH 11 - TOW RELEASE - CH 12 - HOPE THAT ALL MAKES SENSE - KEEP UP THE GOOD WORK - CATCH YOU LATER - TAKE CARE - HAPPY FLYING - WOODY1958UK

**Comment by WOODY1958UK** [comment]
HI - YES ME AGAIN - HAVE DISCOVERED AND PLAYED WITH OFFSET IN MIXERS - BUT MUCH QUICKER AND EASIER TO ADD OFFSET LINE TO EACH OUTPUT - FOE EXAMPLE - I USE THROTTLE TO CONTROL BOTH CAMBER AND REFLEX - AND RUN IT SO WHEN SWITCHED IN I CONTROL IT FROM THROTTLE STICK - SO WITH THROTTLE AT BOTTOM WANT ALL SURFACES TO BE AT 1500 - AND AS I OPEN THROTTLE FLAPS AND AILERONS COME IN WITH CORRESPONDING ELEVATOR COMPENSATION - BY OFFSETTING IN MIX - MAKES LIFE EASIER THAN WRITING ANOTHER MIX WITH JUST OFFSET - I DO SAME FOR SPEED - REFLEX - WITH EVERYTHING AT 1500 WHEN THROTTLE IS AT -100% - AGAIN - HOPE THAT MAKES SENSE - ALSO FOR AN AIRBRAKE MIX - AIRBRAKE 1 / AIRBRAKE 2 / ELEVATOR - BUT THIS TIME ONLY NEED OFFEST ON ELEVATOR - THANKS GUYS - ETHOS IS NEARLY PERFECT !!! - CATCH YOU LATER - TAKE CARE - HAPPY FLYING - WOODY1958UK

**Comment by mawzthefinn** [comment]
Closing off this resolved issue
