### ISSUE TITLE
X20S Updating bitmaps using ethos suite fails with "Missing Drive please refer to faq" 

### ISSUE THREAD

**Issue by vasyly71** [FrSkyRC/ETHOS-Feedback-Community#1902]
Update system bitmaps using ethos suite fails:

![image](https://user-images.githubusercontent.com/25940239/188293823-2f00ee27-7820-4e47-a320-7be50da2c506.png)

Content of e:/bitmaps/system/bitmaps.version value 1.2.6

Please advise if additional information needed.

**Comment by bsongis-frsky** [comment]
Still valid issue? Nobody else complained

**Comment by vasyly71** [comment]
I haven't tried any updates since, but it still was an issue.

I see there are a couple of new releases added after I submitted an issue,
will try to upgrade in a week or so and will update github accordingly.

Thank You
Vasyl Yarmamedov

**Comment by Nicholas-Luoyi** [comment]
Have you deleted the hidden file sdcard.cpuid or flash.cpuid manually? Or would you please check if there is a flash.cpuid in your radio flash?

**Comment by vasyly71** [comment]
No i did not delete anything manually, and i still have files you mentioned (sdcard.cpuid and flash.cpiud) on corresponding drives:
![image](https://user-images.githubusercontent.com/25940239/197541387-a83355c5-d5a5-4df4-bbd5-32644e1422fc.png)
