### ISSUE TITLE
Virtual keyboard does not follow setting for lowercase letters

### ISSUE THREAD

**Issue by MiRe-CZ** [FrSkyRC/ETHOS-Feedback-Community#1904]
1.3.2 both simulator and X20

Virtual keyboard does not follow setting for lowercase letters in 2nd and further edition of the same string and uses capital letters. Example for edition of model name : change of the original "Glider" started with adding "1st" with the keyboard set to lowercase letters, then continued with adding "a", however system used "A".

The same is valid e.g. for names of timers, so it seems to be general error

![image](https://user-images.githubusercontent.com/95141646/189153694-89b3736e-d48e-475f-9b2d-99d7d494c14a.png)

**Comment by hrenz** [comment]
there is no automatik for lower uper letters

**Comment by MiRe-CZ** [comment]
Well, I do not ask for any automation, but for fixing the bug as at this moment system does not follow keyboard lowercase configuration, when you jump on another place of the string which you are editing. It isn't for sure critical, but annoying as you need to switch the keyboard to uppercase letters and then to lowercase ones.

**Comment by bsongis-frsky** [comment]
Fixed for next release
