### ISSUE TITLE
Corrupted name of Throttle stick

### ISSUE THREAD

**Issue by mikeschuster** [FrSkyRC/ETHOS-Feedback-Community#1905]
Firmware Ethos - X20S, Firmware version 1.3.2, FCC #ab77ed31

In System > Sticks > Throttle stick name field, I changed the name from "Throttle" to "Brake".

After power cycling the radio, the Throttle stick name is reset to " ra".

I changed the name back to "Brake", power cycle, and the name again is reset to " ra".

This problem continues, any change to the name is lost by a power cycle.

Attached is the "radio.bin" file that exhibits the problem.

My workaround is install a backup copy of "radio.bin". Doing so fixes this problem.

I am unable to reproduce this problem.

[radio.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9537328/radio.bin.zip)

**Comment by bsongis-frsky** [comment]
The name was not saved on due time after modification. If you change the stick mode (and revert your modification) just after the stick name change, then it's saved properly.

Fixed for next release
