### ISSUE TITLE
Screen visibility

### ISSUE THREAD

**Issue by Tomppy** [FrSkyRC/ETHOS-Feedback-Community#1906]
It would be great to have a very hight contrasted mode like a basic and very strong  B/W mode for the field. Programming at home is great but on the sunlight the screen is usually hard to read. (X18 user)
Thanks

**Comment by andika207** [comment]
that was done deliberately just so you have to buy the X18SE

**Comment by Target0815** [comment]
Besides the normal or dark mode, a B/W mode would be desirable. In sunlight, I can read my X18S best in normal mode, but that could certainly be improved with B/W.

If you have set the dark mode, it is hardly possible to select the normal mode in sunlight. It would be great if you could switch the display directly via button/switch.

**Comment by builda1** [comment]
I find simply adding a matte finish screen protector made all the difference in the world-they are dirt cheap too and cut the glare that makes the screen hard to see.

**Comment by i3dm** [comment]
> I find simply adding a matte finish screen protector made all the difference in the world-they are dirt cheap too and cut the glare that makes the screen hard to see.

got a link to one that fits?

**Comment by builda1** [comment]
> > I find simply adding a matte finish screen protector made all the difference in the world-they are dirt cheap too and cut the glare that makes the screen hard to see.
> 
> 
> 
> got a link to one that fits?

Certainly have!! They make them for all radios/phones/ICE screens etc-these are the "ducks nuts" when it comes to frsky glass screen protectors-and yes, they do matte ones too! 

https://www.protectionfilms24.com/
