### ISSUE TITLE
ACCESS Range check not possible to pass in 1.3.2

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#1908]
Tandem X20
Ethos 1.3.2
TDISRM Upddated

Tried with Archer R8Pro, Archer R6 and Archer RS

Upon perform the range check with a new airplane, a known good airplane, and a receiver in freespace on a camera tripod, all 3 had the same results.  The Range check fails for VFR after about 10m, RSSI is still above 40dB

**Comment by jfint** [comment]
Further testing this morning shows that range check on an ACCST RX is just fine, so this seems to be limited to ACCESS.

**Comment by jfint** [comment]
This appearsnon first test to be fixed in 1.3.3

**Comment by mawzthefinn** [comment]
Closing this off as it was resolved in 1.3.3
