### ISSUE TITLE
Announce system clock time?

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1911]
Hello,
If you want to have the system clock time announced, the wording is output, for example, 13 hours 22 minutes 55 seconds.
In German, however, it must read 13 clock 22 minutes 55 seconds.
Can this be changed?

**Comment by m0p3d** [comment]
Create .wav file containing  Speech: "Uhr" and name it  "hours.wav" (german. "Stunden.wav" ? ) - overwrite the existing file

But this could cause counters like flight time 2Hours german 2 Stunden to say 2 Uhr which is wrong.

**Comment by Wolepo** [comment]
Hello,
That's how I did it as a temporary solution.
However, I would like this change to be made in ETHOS for the time announcement (not for the stopwatches) and not by the user.

**Comment by bsongis-frsky** [comment]
uhr.wav will be used in 1.4.3 for System Time

**Comment by Wolepo** [comment]
The system clock time can be set according to summer or standard time. And this should be announced.
