### ISSUE TITLE
main.lua multimodule file directory

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#1913]
the main.lua multimodule must be directly in the script directory to work unlike others main lua script wich are in their own subdirectory .

**Comment by MIKE-DAILEY** [comment]
Instructions https://www.rcgroups.com/forums/showpost.php?p=49550649&postcount=18844

**Comment by ronron84** [comment]
![screenshot2](https://user-images.githubusercontent.com/16739660/189998720-ae617663-34b9-4324-ad6b-115a6e5244ae.jpg)

**Comment by ronron84** [comment]
![MPM1](https://user-images.githubusercontent.com/16739660/189999334-bee16fa4-41b9-45f1-9965-eea9dd8b9628.jpg)

this one with main lua directly under scripts directory

**Comment by MIKE-DAILEY** [comment]
It works here as the instructions show.  Can you please post some screen shots of your SD card when viewed with Windows File Explorer.  Need the SD root view and the scrips folder.

**Comment by ronron84** [comment]
![file](https://user-images.githubusercontent.com/16739660/190001416-9159b3eb-91e4-4789-a6e2-80f9a3835f26.jpg)

**Comment by MIKE-DAILEY** [comment]
Need the scripts folder view and the module folder too.

**Comment by ronron84** [comment]
![f2](https://user-images.githubusercontent.com/16739660/190001857-a650ced8-86d8-44ab-98bc-feb29e66680c.jpg)

**Comment by ronron84** [comment]
![p3](https://user-images.githubusercontent.com/16739660/190002624-99f82cd6-b2a5-4844-aafa-a2d832141244.jpg)

**Comment by MIKE-DAILEY** [comment]
I take it you renamed main.old and it was main.lua  It works here as the instructions show.

**Comment by ronron84** [comment]
same issue
i put your file and erase main.old  and main.lua in script directory. if i put your file in script it's ok like my file wich is more bigger

**Comment by ronron84** [comment]
windows 11 and ethos 1.3.2

**Comment by MIKE-DAILEY** [comment]
And the FrSky radio is?

**Comment by ronron84** [comment]
sorry tandem x20

**Comment by ronron84** [comment]
i'm going install 1.3.2 again and see what appened

**Comment by MIKE-DAILEY** [comment]
Using the ETHOS File Manager on the X20 are you able to navigate to the modules folder and see the main.lua file there?

**Comment by ronron84** [comment]
no main Lua in the scripts\modules folder, if i put in the file in it won't work, if i put the file in the scripts folder directly it works.
i reinstall ethos 1.3.2 and same issue

**Comment by ronron84** [comment]
hi,
i found it ! i 've just erase the ersky directory file and everything run good now thanks for your help and the time you've spent !
