### ISSUE TITLE
check list in x10 express

### ISSUE THREAD

**Issue by bennykroitoro** [FrSkyRC/ETHOS-Feedback-Community#1914]
it would be nice to have a picture of the radio with the check list when starting the radio and can see which switch is not in place like in the tandam x20

**Comment by mawzthefinn** [comment]
This is a screen resolution issue, in ETHOS there's a low-res (Horus, X18) layout and a High Res (X20) layout, the low-res screens lose some of the nice extras that the high-res version gets.

**Comment by bsongis-frsky** [comment]
Yes it has been done this way on purpose
