### ISSUE TITLE
lua source: playTone results in crash

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1915]
at this moment i do see 3 kind of scripts:
widget / system and source scripts

when i want to create a "background" script which doesn't need a widget, "source script"  is the only way to go.

shortly after i started to create a script i ran into a problem:
calling system.playTone(1600,120) let the sim crash (sim 1.2.11 & 1.3.2, didn't try it on a tx)
don't know if it's intended or a bug

So i would propose:
 - extend source scripts with more methods, so that they could be used as background scripts
 - or define a new kind of script like mixer scripts which allow this functionality

regards
udo

edit:
just tested playNumber, which seems to work, so i guess it's a bug in the playtone implementation and it was intended one can use source scripts as background scripts.

``

[main.lua.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9581889/main.lua.txt)

**Comment by strgaltdel** [comment]
just to prevent misunderstandings

#1915 is purely about sim problems, at this time i couldn't crosscheck on a tandem
#2045 is about the transmitter not producing sounds either

but maybe same root cause

**Comment by bsongis-frsky** [comment]
2 bugs fixed in this area
