### ISSUE TITLE
Frsky X20 and SR8 pro and SR6 

### ISSUE THREAD

**Issue by rud3dog** [FrSkyRC/ETHOS-Feedback-Community#1916]
I’m having a issue when I power up my plane the elevator servo moves 90deg them back to center. It’s over extending my elevator and bending the plastic servo horn. Everything is working correctly. Configuration and self check was done correctly. It also does it with the SR6. It doesn’t do it with a S8R I pulled from another plane.is there a fix for it?

**Comment by Fpilih** [comment]
Had the same issue. Re bind your receivers. Issue was resolved.

**Comment by rud3dog** [comment]
I have rebound receivers multiple times with the same issue

**Comment by yak-54** [comment]
i have seen this  on one of mine all i did was set the throws in TX to the max i needed and redo selfcheck

**Comment by rud3dog** [comment]
> i have seen this on one of mine all i did was set the throws in TX to the max i needed and redo selfcheck

I just tried it and it didnt work. i set the elevator min and max to 50 and it still went 100 percent and back to center 
im really at a loss here

**Comment by mawzthefinn** [comment]
There are several potential sources of this, most  have already been suggested.

It’s worth setting custom failsafe for these channels as well.

**Comment by pstasek** [comment]
If this is a basic analogue servo, this is quite normal. The servo is powered and moves before there's a valid PWM signal resulting in an unpredictable movement to the limit in the first moment. You need to fix the setup mechanically, so the servo/surfaces are not over-stressed on limits. Digital servos usually have delayed start-up and won't obey an invalid PWM signal out of range.

**Comment by bsongis-frsky** [comment]
Please confirm with a Digital servo

**Comment by rud3dog** [comment]
> Please confirm with a Digital servo

Ok, I checked OMP'S website and they say they are digital. I did plug in a older analogue servo and it didn't move. The crazy thing is it only happens on the elevator output on both SR8 and SR6. Maybe a issue with Digital servos. Or maybe OMP'S servos.

**Comment by rud3dog** [comment]
> If this is a basic analogue servo, this is quite normal. The servo is powered and moves before there's a valid PWM signal resulting in an unpredictable movement to the limit in the first moment. You need to fix the setup mechanically, so the servo/surfaces are not over-stressed on limits. Digital servos usually have delayed start-up and won't obey an invalid PWM signal out of range.

It's actually a digital servo However I plugged an old analogue servo, and it didn't move. maybe a signal or crappy servos. but i haven't heard or seen anything on these servos being faulty.

**Comment by Wolepo** [comment]
Did you switch on the transmitter first and then the receiver?

**Comment by rud3dog** [comment]
> Did you switch on the transmitter first and then the receiver?

yes, I did.

**Comment by rud3dog** [comment]
Ok so I ordered some freewing digital servos and it didn't have the problem. I still think there is some kind of issue with the receiver firmware on channel 2. That was the only channel I had an issue with the stock OMP servos. I just swapped the elevator servo
