### ISSUE TITLE
Power Calculated Sensor added 1.3.1

### ISSUE THREAD

**Issue by timmybeetle** [FrSkyRC/ETHOS-Feedback-Community#1917]
Thanks for adding this, only question I have is it possible to add future of the option off MAX reading.
Like we have for other telemetry readings Min/Max.

Thanks for making it possible.

Hans

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/191072263-03d48ca4-428f-4005-af07-abeb84cab8b4.png)

**Comment by bsongis-frsky** [comment]
It will be available in 1.4.0, but not 1.3.x
