### ISSUE TITLE
X10S locked up when switching catagories

### ISSUE THREAD

**Issue by mortehoe** [FrSkyRC/ETHOS-Feedback-Community#1919]
On my Frsky X10S isrm I set up four model categories then I cloned a model and tried to move to another folder the radio locked up showing only the catagory headings with no models present.
I could not change from the locked screen or power off the transmitter without disconnecting the battery ,which is NOT very good,having to unscew the back cover! 
Currently running Ethos 1.3.2 with everything updated from Ethos Suite.

**Comment by mortehoe** [comment]
As requested attached zip files (I hope)[X10S_Ethos.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9595022/X10S_Ethos.zip)

**Comment by mortehoe** [comment]
I can reproduce another issue in folders which may be related.
If I clone a model in my glider folder then copy the clone to my template folder sometimes it either does not copy or copies but disappears when I return to the folder!

**Comment by mortehoe** [comment]
[https://youtu.be/8LpciJynG94](url)
video showing clone being created but disappearing either after move clone to another folder or when reselecting model.

**Comment by bsongis-frsky** [comment]
The other issue is not related, your model name is long and it is another issue which has already been fixed

**Comment by bsongis-frsky** [comment]
I wonder if the first issue could not be the same, would you try with a model whose name is shorter, not "model templatexxx"?

**Comment by mortehoe** [comment]
Do you mean in file manager/models/glider folder which is named plane template.bin ,if so how do I change the name ? 
In the model folders there is no longer name on models or template folder.

**Comment by mortehoe** [comment]
As an aside how can you change the name of a catagory or delete the catagory?

**Comment by mortehoe** [comment]
I deleted the number of cloned models (which did not show up in the catagory folder)with the longer names and that appears to have resolved the issue.
Many thanks however it is slightly concerning that you can lock up the radio by being allowed to put longer names in the files.Perhaps it could be limited as it is in OpenTX.

**Comment by bsongis-frsky** [comment]
The names are limited, but it was wrong in your version, it will be fixed in next release.
Thanks for the confirmation
