### ISSUE TITLE
RPM telemetry

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#192]
Tested using both neuron esc  and 3rd party sensor. Selecting RPM on the telemetry page does not allow you to change poles etc. Using the neuron rec it takes you to the esc config page  and using a 3rd part device does not allow you to change poles.

**Comment by islandflight** [comment]
Please could this be looked at. It would seem the rpm sensor in the device config is for the frsky rpm sensor. Currently there is no way of setting the number of poles/blades/multiplier when using a telemetry esc. Thanks

**Comment by bsongis-frsky** [comment]
From another PR
===========

Heli Gear ratio:
Maingear teeth / motor pinion teeth = ratio
motor rpm / ratio = headspeed

So extra RPM options will be:
- Blade / Pole count (default 1)
- Maingear teeth (default 1)
- Pinion teeth (default 1)

**Comment by islandflight** [comment]
Great thank you just what is needed
