### ISSUE TITLE
Issue: Telemetry and LUA use of Logic Switches

### ISSUE THREAD

**Issue by mikeschuster** [FrSkyRC/ETHOS-Feedback-Community#1920]
Ethos - X20S, 1.3.2 FCC

Telemetry > Altitude > Reset set to a logic switch.

Add a new logic switch, move the new logic switch up to the top of the list.

Telemetry > Altitude > Reset now refers to a different logic switch.

Typically, logic switch list rearrangements don't impact logic switch clients (eg Flight Modes, Mixers, Timers, Special Funcs, etc)

Telemetry and also LUA configurations appear to be exceptions.

**Comment by bsongis-frsky** [comment]
> Telemetry > Altitude > Reset now refers to a different logic switch.

This is a bug which is fixed in 1.3.3

> Typically, logic switch list rearrangements don't impact logic switch clients (eg Flight Modes, Mixers, Timers, Special Funcs, etc)

Please confirm, this should be wrong and it is a major difference with OpenTX!
