### ISSUE TITLE
Feature request: Rudder differential for V-tail

### ISSUE THREAD

**Issue by mikeschuster** [FrSkyRC/ETHOS-Feedback-Community#1921]
Ethos - X20S, 1.3.2 FCC.

Of course rudder differential is not typically needed for traditional tail, but it can be used to reduce pitch excursions on V-tail.

I was able to implement rudder differential using Free Mixes, but I found doing so a bit complex.

Ethos support would be nice to have.

**Comment by mawzthefinn** [comment]
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/119
