### ISSUE TITLE
RxBatt still active after disconnecting battery

### ISSUE THREAD

**Issue by mortehoe** [FrSkyRC/ETHOS-Feedback-Community#1923]
After discovering sensors on S6R for telemetry the RxBatt sensor is still flashing as active despite the receiver battery having been disconnected (which means the telemetry fed signal value does not turn red)
Running on latest software from Ethos suite on Frsky X10S ISRM.

**Comment by mortehoe** [comment]
![20220919_210609](https://user-images.githubusercontent.com/3820551/191108179-af21e4fb-0e71-410f-be58-e3d10a87fdcf.jpg)
![20220919_210556](https://user-images.githubusercontent.com/3820551/191108187-c9933b32-9904-461c-9d38-099a8af75c4f.jpg)
Attached photos when receiver battery disconnected.

**Comment by bsongis-frsky** [comment]
Have you updated your ISRM to the latest version?

**Comment by mortehoe** [comment]
My apologies,I have just updated (1 version out) and the problem is now resolved ;although there was no mention of this fix in the latest release'Update to work with Archer RS 2.1.6 racing mode'.
