### ISSUE TITLE
Sensor conflict warning

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#1924]
Ethos 1.3.2
I upgraded from ethos 1.2.7 to 1.3.2 and now I get a sensor conflict warning about every 30 seconds.
I have 2 flvss sensors on my model but they have different id's
Both sensors are working correctly, just get the sensor conflict waning

**Comment by Liverboy77** [comment]
I have fixed it for some reason after the update both flvss sensor changed to the same id I have now changed 1 of the id's

**Comment by bsongis-frsky** [comment]
No issue then :)
