### ISSUE TITLE
Sharing the Portuguese-Brazilian (Pt-Br) translation - 1st release

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#1929]
Hi FrSky Ethos team!
As the admin from one of the top FrSky enthsiats group here in Brazil with more than 250 members / owners, I would like to share the 1st version of the translated file to Brazilian-portuguese. 

[br_v1.01.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9641906/br_v1.01.txt)

Portuguese spoken in Portugal is slitghtely different from the Portuguese we speak here. 

I´m not sure I am sharing the file with the right version. Please correct me if I made any mistake by posting it here. 
Our Brazilian community can not look forward to see Ethos in our local language.

Best and warm regards from Brazil!
Marcio Costa

**Comment by bsongis-frsky** [comment]
What about this?

```
TRANSLATION_NAME          "Brazilian Português"
TRANSLATION_KEY              "pb"
```

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/192322279-d9427ea0-d923-4281-9b89-c472d218ab7f.png)

**Comment by marciomc-github** [comment]
> What about this?
> 
> ```
> TRANSLATION_NAME          "Brazilian Português"
> TRANSLATION_KEY           "pb"
> ```

I believe this is best represented in Portuguese like this:
TRANSLATION_NAME          "Português Brasileiro"

**Comment by marciomc-github** [comment]
For future releases, may I post here the updates / corrections to the pb.txt file?

**Comment by bsongis-frsky** [comment]
It's better to open a new issue if needed, because I think you cannot reopen this one once closed.
If you can reopen it's better of course

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/192449200-730ab302-c28e-4ebc-9186-008f6577cf1f.png)
