### ISSUE TITLE
Setting a voltage alarm with value from  FLVS ADV 

### ISSUE THREAD

**Issue by hamelsveld** [FrSkyRC/ETHOS-Feedback-Community#1930]
I have a FLVS ADV sensor from FrSky to measure voltage from the receiver lipo, in the telemetry I can also find it where it shows the correct voltage of the lipo, however if I want to set an alarm level in logic switches I only have but choice in the values 0 and 33.6V, and nothing in between.

Steps taken:
Logic switch -> function A < X -> Source A "Lipo" -> source X (my value I want to use)

does anyone know how to set the Volt value just like a current sensor??

**Comment by bsongis-frsky** [comment]
Already fixed in 1.3.3
Checked just now with ADV FLVS

**Comment by hamelsveld** [comment]
Thanks that temp solution worked :-)
