### ISSUE TITLE
LUA: X10 lcd.font() broken on ETHOS 1.3.2

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1935]
lcd.font() on X10 seems broken on 1.3.2, works in 1.2.11

1.2.11
![image](https://user-images.githubusercontent.com/30294218/192898636-ef112dd3-c265-4467-b42b-61d28cbcbebc.png)

1.3.2
![image](https://user-images.githubusercontent.com/30294218/192897657-ec3bead2-9d02-4e27-b5bf-271b4adc10f7.png)

```
local function paint(widget)
    -- Demo of a text
    lcd.color(lcd.RGB(255,0,0))

    lcd.font(FONT_XS)
    lcd.drawText(15, 10, string.format("FONT_XS %d",FONT_XS))

    lcd.font(FONT_ITALIC)
    lcd.drawText(15, 40, string.format("FONT_ITALIC %d",FONT_ITALIC))

    lcd.font(FONT_L)
    lcd.drawText(15, 70, string.format("FONT_L %d",FONT_L))

    lcd.font(FONT_XXL)
    lcd.drawText(15, 100, string.format("FONT_XXL %d",FONT_XXL))

end

local function init()
    system.registerWidget({key="lcddemo", name="Lua LCD Demo", paint=paint})
end

return {init=init}
```

**Comment by mawzthefinn** [comment]
Quick question, are you using the same SD contents for both versions? because X10 fonts were moved to the SD card with 1.3.0

**Comment by bsongis-frsky** [comment]
I see that the widget title "Lua LCD Demo" uses the STD font (it's not the same size than 1.2.11), so I also wonder if you have the fonts on your SD

**Comment by yaapu** [comment]
I apologize, you're right, I was missing the HORUS_SD.zip content, I'm closing this, thanks for the prompt feedback
