### ISSUE TITLE
Problems with Airbrake mix

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#1936]
**X20, Ethos 1.3.3**

In the glider tab, I create a new glider model with elevator, flaps and ailerons
I add an Airbrake mix, with appropriate outputs.

However:

- None of the controls on the transmitter affect the outputs.
- Looking at the graph, the 'offset' field adjust the weight instead of adding an offset.

It seems that the mix is broken, or have I missed something?

**Comment by bsongis-frsky** [comment]
I also see "Differential" as the title of this dialog!

![image](https://user-images.githubusercontent.com/50834778/193254238-3bcfa6ba-3f4b-4cd0-a947-29f24a046e39.png)

**Comment by bsongis-frsky** [comment]
Except this label which is wrong I see no issue, it works correctly, it is just an offset!

**Comment by bsongis-frsky** [comment]
The curve is not good. I will fix it like this:

![image](https://user-images.githubusercontent.com/50834778/193255925-55026217-8a86-436c-96ac-07a6ea3eaea0.png)

**Comment by RC-SOAR** [comment]
So this just applies an offset to each output? Like the new Offsets mix, but with offsets individually adjustable?
