### ISSUE TITLE
Battery voltage incorrect by fw 1.3.3 EU

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#1937]
After updating to new fw 1.3.3. EU. The values of the battery are incorrect.
See screenshot.

![incorrectBatteryVoltage1 3 3](https://user-images.githubusercontent.com/7701921/193233217-5d213953-206d-489e-8a79-d00688f2516e.png)

**Comment by bsongis-frsky** [comment]
Aybody else confirms this issue?

**Comment by MIKE-DAILEY** [comment]
> After updating to new fw 1.3.3. EU. The values of the battery are incorrect. See screenshot.
> 
> ![incorrectBatteryVoltage1 3 3](https://user-images.githubusercontent.com/7701921/193233217-5d213953-206d-489e-8a79-d00688f2516e.png)

Are you able to edit the 35.5v voltage display down to the 8v range?

**Comment by wmayvis** [comment]
After a couple of times turned off the radio the issue doesn't appear.

**Comment by Wolepo** [comment]
Displays are correct. X10S Express
![Batterie](https://user-images.githubusercontent.com/90325526/193415080-db1a0eb9-bf96-40fa-86be-d1902fd8479d.jpg)
