### ISSUE TITLE
X20 some cannot delete existing logic switches

### ISSUE THREAD

**Issue by dehigama** [FrSkyRC/ETHOS-Feedback-Community#1939]
On some occasions it’s seems to be impossible to delete an existing logic switch. Long press over doesn’t open up the available options. 

1.3.3 EU

**Comment by mawzthefinn** [comment]
A fast tap gives the contextual menu, long-press should go directly to Edit.

**Comment by dehigama** [comment]
Thanks @mawzthefinn , yes that was my issue. I long pressed instead of short press/tap. all good now
