### ISSUE TITLE
CZ translation numbers one and two not called

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#1943]
In Czech translation since 1.2.11 (work on inflections), some numbers are not called in stopwatch callouts.

It's number one and two (for example minute, minutes). 

There's a wav file 1-minute.wav and 2-minutes.wav that should be called instead of minute.wav and minutes.wav in case of time calls. 

The same applies to seconds in count-down, and the value of 2 thousand, where 1.wav and 2.wav are not played.

**Comment by bsongis-frsky** [comment]
Where have you seen "1-minute.wav", "2-minutes.wav", "1.wav" and "2.wav", those prompts should not exist in CS

**Comment by janekx** [comment]
provided video
