### ISSUE TITLE
Reading out sensor data in the Sensor Config menu is not possible properly

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1949]
Hello,
The sensors Neuron (SBEC), FLVSS, Vario, GPS and RPM are installed in my models.
ETHOS 1.3.3 on X10S Express, RX=SR8Pro.
By chance, I noticed the following: in the Sensor Config menu, the settings of only a few sensors can be read out. Only SBEC, SxR and SxR Calibration work. If data does appear after several attempts, it is incomplete. However, these can then be changed and saved.
![Übersicht](https://user-images.githubusercontent.com/90325526/193528997-8b906fc4-ef0a-4212-bec3-84cb365046d8.jpg)

![SBEC](https://user-images.githubusercontent.com/90325526/193529050-b51802fd-ac7d-41aa-9bb8-135141d47364.jpg)

![Umin](https://user-images.githubusercontent.com/90325526/193529106-20bfdb9f-4b57-42e8-be81-b4b624184d59.jpg)

![Vario](https://user-images.githubusercontent.com/90325526/193529136-8875b3e8-dd95-453b-ba34-a0d93fb7259e.jpg)

**Comment by mawzthefinn** [comment]
Note the sensors which read out data here are the ones where that data is needed for setup through those menus.

Most sensor configuration is done in the Model->telemetry menu

**Comment by Wolepo** [comment]
If the menus are present in Sensor Config, they should also work, e.g. to change the ID

**Comment by bsongis-frsky** [comment]
Are you saying that you connect a variometer (which one)? And it is not configurable in Sensors Config?

**Comment by Wolepo** [comment]
Yes, that is so, neither with ACCST (on an S8R), nor with ACCESS (SR8 Pro).

**Comment by bsongis-frsky** [comment]
What is your variometer?

**Comment by Wolepo** [comment]
Nachtrag: SP Vario Sensor hochpräzise oder Vari AVD

**Comment by Wolepo** [comment]
Addendum: SP Vario Sensor high precision or Vari AVD

**Comment by jokabre** [comment]
I have the same problem with the sensor VARI AVD, but an elder one named  Frsky VARIOMETER SENSOR it`s running  normally.By the way, my X20S FW will be  1.3.2

**Comment by Wolepo** [comment]
I also found a vario sensor high precision in a glider that was several years old. Here all files are read in immediately RX= S6R

**Comment by bsongis-frsky** [comment]
May I assume that all your sensors have the latest firmware?

**Comment by Wolepo** [comment]
No, they were not. 
Vari AVD updated to 1.5 > works.
For Vari-H (SP Vario Sensor high precision) the last version is from 2014-10-10. Reinstalled > does not work.

**Comment by Wolepo** [comment]
In this context, I miss the possibility to update sensors via OTA.

**Comment by bsongis-frsky** [comment]
> In this context, I miss the possibility to update sensors via OTA.

This is very different, and I think that some new receivers will allow it in a very near future

> Vari-H (SP Vario Sensor high precision) the last version is from 2014-10-10. Reinstalled

It's not an Ethos issue then

**Comment by bsongis-frsky** [comment]
> Information for MLVSS are shown only when you repeat opening of its config screen. When you open some other sensor screen (in this case Vari-H) no info is updated for MLVSS next time - in this case also delivery of telemetry from MLVSS stops and only resetting of the sensor helps

I reproduce it, I will forward it to the team in charge of MLVSS

**Comment by Wolepo** [comment]
If the FW of the sensors is now changed, would it not then be possible to also display the FW version?
