### ISSUE TITLE
Wrong highlighting in mixer menu

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#195]
In the mixer menu there is a bug in highlighting active mixers.

Here is a short Video

https://youtu.be/YcevJIqYRvs

**Comment by DaySpeed955i** [comment]
similar to #77

**Comment by DaySpeed955i** [comment]
here is mine.
Thanks.
[model03.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6448938/model03.txt)
