### ISSUE TITLE
lua: completely wrong data returned by requesting coordinates (lat = lon)

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1950]
Hi,

by requesting GPS coordinates within lua i'm getting invalid data
Lat value = Lon value = something but has nothing to do with "my" coordinates 
running Ethos 1.3.3 under Horus X12

my source script contains following lines:
	local lat= system.getSource({name="GPS", options=LATITUDE})
	local lon= system.getSource({name="GPS", options=LONGITUDE})
	print("Lat:",lat:value(), "LON:  ",lon:value())

Horus shows these coordinates

![horus coord](https://user-images.githubusercontent.com/20392683/193537845-30c0a5ee-e1c7-4684-8419-3a06ab7147d3.png)

lua reports this position

![output](https://user-images.githubusercontent.com/20392683/193537896-2cc507f1-5aa6-40e2-ab0c-e13619a18277.png)

thanks & regards

**Comment by bsongis-frsky** [comment]
This is strange, the script from @Hobby4Life wouldn't work for you?

![image](https://user-images.githubusercontent.com/50834778/194009080-25e4e2fd-a58a-4733-8d89-9a74ea735d9c.png)

**Comment by strgaltdel** [comment]
i'll check this evening.
(as mentioned in #1231 , actual sim shows similar behaviour: lat=lon)

dont't have a tandem tx to crosscheck, so i can't say if it's a horus specific thing.

luckily i was able to find hobby4lifes widget under the "new" account
https://github.com/PD5DJ

you may know that H4Life main actor Björn quitted RC hobby some weeks ago and so no more development/support for his widgets:

_"As you have noticed, I have been less to less active with the hobby and the website for the last few months.
This has everything to do with the fact that I have found an old passion again, and want to continue with it.
Since that also takes up a lot of my time, I decided to quit the modeling hobby."
https://hobby4life.nl/bjorn-verlaat-het-hobby4life-team/

**Comment by strgaltdel** [comment]
Thanks for your hint,
pointed me into the right direction

I used constants LATITUDE / LONGITUDE like they were mentioned in #1231, dec 2021
But times has changed, and by using "OPTION_LATITUDE / OPTION_LONGITUDE" it worked like a charm (-;

thanks & regards
Udo
