### ISSUE TITLE
Full programmability of Neuron ESC

### ISSUE THREAD

**Issue by CliffEvans** [FrSkyRC/ETHOS-Feedback-Community#1952]
Feature request: Full programmability of Neuron ESC's.  Make it possible to activate brake and all other functions through Ethos

**Comment by pstasek** [comment]
That would be nice but the ESC part with BLHeli32 firmware doesn't work that way. It needs to be connected directly via PWM channel and there's no PWM port on radio or any way to read/program the ESC via receiver.

**Comment by CliffEvans** [comment]
That is a great shame.
