### ISSUE TITLE
POSSIBLE ERROR IN FREE MIX - WEIGHT DOWN

### ISSUE THREAD

**Issue by WOODY1958UK** [FrSkyRC/ETHOS-Feedback-Community#1953]
HI - FIRST PLEASE EXCUSE CAPS - BUT I AM PARTIALLY SIGHTED AND IT HELPS
SO IF I AM CORRECT THE WEIGHT DOWN IN FREE MIX SHOULD DEFAULT TO -100% WHICH SHOULD BE AT BOTTOM OF GRAPH - AT THE MOMENT 100% IS AT BOTTOM OF GRAPH AND -100% AT TOP - I THINK IT SHOULD BE OTHER WAY ROUND - HOPE THAT'S RIGHT - OUTPUT SCREEN SHOWS -100% WHEN FREE MIX WEIGHT DOWN SHOW 100% - THANKS - CATCH YOU LATER - TAKE CARE - HAPPY FLYING - WOODY1958UK

**Comment by mawzthefinn** [comment]
You are misunderstanding how the weight works. You are setting the rate multiplier, not the position when you set the weight.

So 100% down weight will give -100 when given -100 as an input (100% weight x -100 input = -100 output)

-100% down weight x -100 input = 100 output (the negatives cancel out).

100% gives you the standard output for that input. -100% gives you an inverted output.

What you seem to be expecting is the setting of values for a given input, you do that with a Curve, not a weight. -100 on the curve at the -100 input position will give -100 output, because curves define the output value for a given input, not a percentage multipler.

**Comment by bsongis-frsky** [comment]
@WOODY1958UK Perhaps you could ask on forums like RCG for such questions? We have already so many open requests, and it takes a lot of time to sort!

@mawzthefinn thanks for the help since yesterday!

**Comment by WOODY1958UK** [comment]
HI OKAY I UNDERSTAND I WAS LOOKING AT IT AS AN AVERAGE AERMODELLER MIGHT LOOK AT IT AND THAT WEIGHT DOWN WOULD BE -100% AND AS YOU ADD IT GOES FROM - TO + SO HOPEFULLY YOU MIGHT BE ABLE TO HELP ME WITH NEXT AND MUCH BIGGER ISSUE I HAVE OR WOULD YOU LIKE ME TO POST IT ON FORUMS ?? I WOULD LIKE TO RUN IT BY YOU QUICKLY I FLY BIG THERMAL ELECTRIC GLIDERS TO 2 X AILERON - ELEVATOR - MOTOR - RUDDER - 2 X FLAPS AND USE FLIGHT MODES - SO LAUNCH - CRUISE - SPEED - THERMAL - LANDING AND ON LDER RADIOS WOULD HAVE THROTTLE ON THROTTLE STICK IN LAUNCH MODE THEN SWITCH IT OFF IN THERMAL / CRUISE / SPEED MODES - WHEN THE THROTTLE STICK WOULD CONTROL FLAPS / AILERONS / ELEVATOR - AND THEN BUTTERFLY / CROW ON LANDING MODE I CAN SWITCH EVERYTHING ON VIA FLIGHT MODE SWITCHES - BUT I CAN'T TURN THINGS OFF SO WHEN I SWITCH FROM LAUNCH MODE TO CRUISE - THE THROTTLE GOES TO 0% - NOW I COULD RIGHT A MIX FOR EVERY POSITION TO TURN THE MOTOR OFF - BUT THIS IS A VERY CLUMBSY WAY OF DOING IT - INSTEAD OF TURNING MOTOR OFF WHEN I TURN CRUISE OR ANY OF THE OTHER FLIGHT MODES ON THIS ALLOWS ME TO CONCENTRATE ON THE MODEL AND ONLY HAVING TO USE 2 SWITCHES - I LIKE THE LARGE 3 POSITION SWITCHES TO SELECT FLIGHT MODES NOW AM I BEING STUPID - AND MISSING SOMETHING ??? - PROBABLY - OR HAVE I COME ACROSS SOMETHING ETHOS CAN'T DO - YET ??? I CAN DO THIS ON MY EDGE TX TARANIS - BUT REALLY STRUGGLING ON ETHOS THANKS KEEP UP THE GOOD WORK ETHOS IS SUCH A GREAT LEAP FORWARD - AND GREAT FOR MY NORMAL PLANES BUT CAN'T USE IT ON MY COMPETITION STUFF CATCH YOU LATER TAKE CARE HAPPY FLYING DAVID - WOODY1958UK      DAVID BRIAN HOMEWOOD FLAT 32, MARGARET HOUSE LEALANDS DRIVE UCKFIELD EAST SUSSEX TN22 1FH   TEL :- 01825 765690 MOB :- 07759 517 323 E-MAIL :- ***@***.***  

On 05-Oct-2022 01:40:56 +0200, ***@***.*** wrote: 

You are misunderstanding how the weight works. You are setting the rate multiplier, not the position when you set the weight. 

So 100% down weight will give -100 when given -100 as an input (100% weight x -100 input = -100 output) 

-100% down weight x -100 input = 100 output (the negatives cancel out). 

100% gives you the standard output for that input. -100% gives you an inverted output. 

What you seem to be expecting is the setting of values for a given input, you do that with a Curve, not a weight. -100 on the curve at the -100 input position will give -100 output, because curves define the output value for a given input, not a percentage multipler.

**Comment by mawzthefinn** [comment]
ETHOS behaves identically to all other major radio systems with weights. Down and Up /left and right are always 100%/100% for full normal behaviour. Negative weight inverts the output. 

For your sailplanes, my recommendation is exactly the same one I'd give for OpenTX or EdgeTX, go to rc-soar.com and get one of Mike Shellim's templates to start with. He's published an ETHOS version of his superb E-Soar plus F5J Template

There's several ways to do what you want, and most are the same as on EdgeTX, every mix can be activated/deactivated by Flight Modes. The easiest way to do the Throttle side is to have a default throttle curve with 2 points, both set to -100 and add a second throttle curve that's active on Launch mode only with 2 points, set to -100 and 100. That will disable the throttle mix when you are not in Launch mode. just remember, if disabling a mix, you do need something else giving the setting unless you want it to be at '0'.

I do recommend going over to the RCGroups radio forum and asking these questions there, there's a lot of folks who rarely come in to Github who can help you, including Mike Shellim. 

Also note caps lock makes your posts much more difficult to read for the rest of us. I'd suggest using scaling fonts instead to make it more readable for you (and easier for us too). The Accessibility options on your device should support larger display fonts.

Finally, you probably should not put your contact info in a publicly visible spot like this, spammers and telemarketers will grab that info.

**Comment by WOODY1958UK** [comment]
HI AFTER SPENDING THE DAY PRESSING SCREENS AND SWEARING AT MISTAKES I THINK I HAVE CRACKED MY PROGRAMMING ISSUES AND GIVEN ANOTHER COUPLE OF DAYS TO MAKE SURE EVERYTHING IS WORKING WOULD YOU LIKE SOME BIN FILES OF MODELS ??? OR EVEN JUST A SUMMARY OF WHAT I HAVE DONE - TO PASS ON TO OTHER FLYERS ??? MUCH THANKS FOR YOUR HELP CATCH YOU LATER TAKE CARE HAPPY FLYING DAVID - WOODY1958UK      DAVID BRIAN HOMEWOOD FLAT 32, MARGARET HOUSE LEALANDS DRIVE UCKFIELD EAST SUSSEX TN22 1FH   TEL :- 01825 765690 MOB :- 07759 517 323 E-MAIL :- ***@***.***  

On 05-Oct-2022 16:49:09 +0200, ***@***.*** wrote: 

ETHOS behaves identically to all other major radio systems with weights. Down and Up /left and right are always 100%/100% for full normal behaviour. Negative weight inverts the output. 

For your sailplanes, my recommendation is exactly the same one I'd give for OpenTX or EdgeTX, go to rc-soar.com and get one of Mike Shellim's templates to start with. He's published an ETHOS version of his superb E-Soar plus F5J Template 

There's several ways to do what you want, and most are the same as on EdgeTX, every mix can be activated/deactivated by Flight Modes. The easiest way to do the Throttle side is to have a default throttle curve with 2 points, both set to -100 and add a second throttle curve that's active on Launch mode only with 2 points, set to -100 and 100. That will disable the throttle mix when you are not in Launch mode. just remember, if disabling a mix, you do need something else giving the setting unless you want it to be at '0'. 

I do recommend going over to the RCGroups radio forum and asking these questions there, there's a lot of folks who rarely come in to Github who can help you, including Mike Shellim. 

Also note caps lock makes your posts much more difficult to read for the rest of us. I'd suggest using scaling fonts instead to make it more readable for you (and easier for us too). The Accessibility options on your device should support larger display fonts. 

Finally, you probably should not put your contact info in a publicly visible spot like this, spammers and telemarketers will grab that info.

**Comment by bsongis-frsky** [comment]
I have hidden the personal information you are leaking here, TAKE CARE!

**Comment by WOODY1958UK** [comment]
HI THANKS FOR YOUR WONDERFOUL REPLY - I AM NEW TO ETHOS AND THERE IS ALREADY SO MUCH STUFF OUT THERE - IT'S HARD TO KNOW WHERE TO LOOK WHEN WHAT I AM AFTER CAN BE BURIED AWAY IN ONE LITTLE FILE SO THANK YOU SO MUCH FOR PUTTING ME IN THE RIGHT DIRECTION AND HOPEFULLY IF IT SOLVES MY ISSUES - THEN SAVING UP FOR NEXT TD20S !!! THANKS CATCH YOU LATER TAKE CARE HAPPY FLYING DAVID - WOODY1958UK      DAVID BRIAN HOMEWOOD FLAT 32, MARGARET HOUSE LEALANDS DRIVE UCKFIELD EAST SUSSEX TN22 1FH   TEL :- 01825 765690 MOB :- 07759 517 323 E-MAIL :- ***@***.***  

On 05-Oct-2022 16:49:09 +0200, ***@***.*** wrote: 

ETHOS behaves identically to all other major radio systems with weights. Down and Up /left and right are always 100%/100% for full normal behaviour. Negative weight inverts the output. 

For your sailplanes, my recommendation is exactly the same one I'd give for OpenTX or EdgeTX, go to rc-soar.com and get one of Mike Shellim's templates to start with. He's published an ETHOS version of his superb E-Soar plus F5J Template 

There's several ways to do what you want, and most are the same as on EdgeTX, every mix can be activated/deactivated by Flight Modes. The easiest way to do the Throttle side is to have a default throttle curve with 2 points, both set to -100 and add a second throttle curve that's active on Launch mode only with 2 points, set to -100 and 100. That will disable the throttle mix when you are not in Launch mode. just remember, if disabling a mix, you do need something else giving the setting unless you want it to be at '0'. 

I do recommend going over to the RCGroups radio forum and asking these questions there, there's a lot of folks who rarely come in to Github who can help you, including Mike Shellim. 

Also note caps lock makes your posts much more difficult to read for the rest of us. I'd suggest using scaling fonts instead to make it more readable for you (and easier for us too). The Accessibility options on your device should support larger display fonts. 

Finally, you probably should not put your contact info in a publicly visible spot like this, spammers and telemarketers will grab that info.

**Comment by WOODY1958UK** [comment]
HI HAVE NOW SPENT MORE TIME WITH ETHOS AND CAN NOW SAY - WOW !!!! - AT LAST A TRANSMITTER SINCE MY MULTIPLEX 3030 YTHAT I CAN DO EVERYTHING I WANT ON AWESOME SO HUGE THANKS GUYS YOU ARE GOING DOWN A REALLY GOOD ROAD - COMPARED TO THE OPPOSITION !!!! PLEASE KEEP UP THE GOOD WORK AND HAVE NOW SEEN THE NEW TRAY VERSION THE GERMANS / EUROPEANS ARE GOING TO LOVE IT HAVE ADDED IT TO MY BUCKET LIST THANKS CATCH YOU LATER TAKE CARE HAPPY FLYING DAVID   

On 05-Oct-2022 22:46:07 +0200, ***@***.*** wrote: 

I have hidden the personal information you are leaking here, TAKE CARE!

**Comment by WOODY1958UK** [comment]
HI BERTRAND I HAVE FINALLY CRACKED THE PROGRAMMING I WANTED TO DO ON ETHOS AND MORE !!!!! AND JUST WANTED TO SAY A BIG THANKYOU FOR ALL YOUR HARD WORK -ETHOS IS JUST AWESOME !!! I AM NOW SAVING FOR A TDX20S FOR THE SPRING AND THE TRAY VERSION LOOKS STUDDING - THE EUROPEANS ARE GOING TO LOVE IT HOPEFULLY MIKE SHELLIM ON RC-SOARING WILL POST IT ON HIS WEBSITE - HE IS BEING VERY HELPFUL WITH FEEDBACK I HOPE FRSKY ARE PAYING YOU WELL YOU DESERVE IT - AWESOME CONCEPT KEEP UP THE GOOD WORK CAN'T WAIT TO SEE WHAT YOU ARE PLANNING NEXT CATCH YOU LATER TAKE CARE HAPPY FLYING OH AND QUESTION WHAT DO YOU FLY ??? ANYTHING SPECIAL OR JUST A BIT OF EVERYTHING DAVID      DAVID BRIAN HOMEWOOD FLAT 32, MARGARET HOUSE LEALANDS DRIVE UCKFIELD EAST SUSSEX TN22 1FH   TEL :- 01825 765690 MOB :- 07759 517 323 E-MAIL :- ***@***.***  

On 05-Oct-2022 07:30:01 +0200, ***@***.*** wrote: 

Closed #1953 as completed.
