### ISSUE TITLE
Feature Request: 900MHz transmitting power to telemetry in ACCESS mode 

### ISSUE THREAD

**Issue by phazeman** [FrSkyRC/ETHOS-Feedback-Community#1954]
Can we have a 900MHz signal strength (transmitting power) as a telemetry as it was in the openTX for X10S for example ?

**Comment by bsongis-frsky** [comment]
Do you mean that OpenTX has this (with the same module)? 
Because it should only depend on what the module sends or not!

**Comment by bsongis-frsky** [comment]
Understood. But the module doesn't send the information yet, so Ethos cannot display it!

**Comment by phazeman** [comment]
Ohh I understand...
Thanks for the clarification !

**Comment by i3dm** [comment]
@bsongis-frsky please ask the RF tem ao implement this same way as it was on R9M

**Comment by bsongis-frsky** [comment]
Forwarded :)

**Comment by i3dm** [comment]
@bsongis-frsky  can you please update if this is being addressed?

**Comment by i3dm** [comment]
is this issue being addressed?

**Comment by mawzthefinn** [comment]
It's not an ETHOS issue, the data is not passed from the RF module so ETHOS has nothing to display.

**Comment by i3dm** [comment]
> It's not an ETHOS issue, the data is not passed from the RF module so ETHOS has nothing to display.

yes but we have no way to address the RF team unless through here
