### ISSUE TITLE
Ethos FrSky X18 bootloader update not working

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#1955]
I have an X18 with bootloader 1.2.2. and cannot update through DFU. (receiving error: A valid DFU suffix will be required in a future dfu-util release Cannot open DFU device 0483:df11 found on devnum 17 (LIBUSB_ERROR_NOT_SUPPORTED)No DFU capable USB device available).
Can I get some help to have the radio going, please? Pleas, someone give me fool proof instructions. I just got the radio with Ethos and this is just one of the two first problems I found.

**Comment by MIKE-DAILEY** [comment]
The simple solution is to download the firmware for the X18 from here https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.3.3  and the bootloader for your system from here https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.2.11 

1. Unzip it.  
2. With the X18 in bootloader mode connect to your PC with a data USB cable.  File explorer windows open. 
3. copy the firmware and bootloader to the NAND drive root.
4. Eject drives and disconnect the USB. 
5. The X18 flashes firmware with progress bar.
6. When flash complete power system OFF/ON
7. Using the ETHOS File Manager navigate the bootloader and long press on it.  Select flash bootloader and bootloader flashes.
8. Power X18 off and start in bootloader mode.  
9. Start ETHOS SUITE and connect X18 to PC.
10. Follow ETHOS SUITE update instructions and you are done.

**Comment by Richrfl** [comment]
Great!! Thank you very much. I am almost in business.

**Comment by MIKE-DAILEY** [comment]
Good that it is working for you now.  Your original 1.2.2. bootloader although older should have worked with ETHOS SUITE so it could have updated everything for you including to bootloader 1.2.11.

**Comment by Edlightenme** [comment]
what about for twin x lite s controller bootloader??
