### ISSUE TITLE
Model pictures not shown in the model or editor. FrSky X18

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#1956]
I have the bmp files in the SD/bitmaps/user folder, and I can see the pictures when I use the files tab, but the model screen doesn't show any model.
![IMG_20221005_134121100_HDR](https://user-images.githubusercontent.com/9392774/194128061-8cdc5ca1-ef59-4dec-9501-5e6be6e0093c.jpg)
![IMG_20221005_134044020_HDR](https://user-images.githubusercontent.com/9392774/194128171-53bf3f86-983d-48f8-a21c-5e0e70cbb887.jpg)

**Comment by MIKE-DAILEY** [comment]
They should not be in bitmap/models.  Change user to models.  See here https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/ETHOS-File-Storage-and-Firmware-Flashing

**Comment by Richrfl** [comment]
Thank you Mike. you hit the nail. One down, one to go. (bootloader issue)
