### ISSUE TITLE
Cross trim bug

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#1957]
I want to report a bug in the cross-trim feature: Sticks and Trims are reversed. Meaning that where you read Stick you are really looking at the Trim and vice versa.
This is what is going on. My radio is configured as AERT. The other picture shows the cross-trim configuration. With that setup
![screenshot-2022-10-07-33736](https://user-images.githubusercontent.com/9392774/194590355-7db119b8-20ce-4599-b717-f374d1e7537b.jpg)
![IMG_20221007_112332932](https://user-images.githubusercontent.com/9392774/194591134-131f1260-b561-4309-a6cc-c0b73b93b529.jpg)
With this configuration, when you move the throttle trim the elevator offset changes. When you move the elevator trim, the throttle is controlled. When you move the aileron trim, the throttle is controlled.
This issue also implies (and I tested) that trims T5 and T6 do not connect to any stick.

**Comment by mawzthefinn** [comment]
That's not a bug, that's just poor language (which should be corrected)

The behaviour is correct, but should say Trim where it says Stick, as you are assigning the cross trims there, not sticks.

And yes, T5 & T6 are independent trimmers not mapped to any standard trim function.

**Comment by Richrfl** [comment]
Thank you, guys.
