### ISSUE TITLE
ETHOS V1.3..3   possibility of another source for AETR, but only as an option.

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1959]
It should be possible for Throttle, Alieron, Elevator, Rudder to select another encoder source, signal source. 
But only as option
There would be important and practical for the function modelers

**Comment by bsongis-frsky** [comment]
The source would have the option "Without Trim"

**Comment by hrenz** [comment]
V1.3.3 
No, Throttle mixer doesn´t allow this, no change of source

**Comment by mawzthefinn** [comment]
It does on myX20 running 1.3.3

![screenshot-2022-10-09-56187](https://user-images.githubusercontent.com/34381975/194775052-7be468a8-85dd-4165-ae17-9230b7a5e631.jpg)


It's named as Input there, unlike other mixers which designate this as Source.

**Comment by hrenz** [comment]
V1.3.3 
ah!  source select


![image](https://user-images.githubusercontent.com/6217896/194851290-d16bff23-dcdb-49ec-8192-f23a92ad4a4e.png)

**Comment by mawzthefinn** [comment]
Removing stale again, we still want this.

**Comment by mawzthefinn** [comment]
Removing stake yet again, this is still wanted.

**Comment by hrenz** [comment]
can be closed
