### ISSUE TITLE
feature request : Logical switch impuls : << in second during parameter 

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#196]
Please add the << value on the second parameter in during on impuls logical switch like in openTX.

now it is not possible to get an impuls if a switch is only longer than x seconds in on position. ( now it is only if longer than x and shorter than y).

Thanks

**Comment by Hartinger** [comment]
I guess you mean what I have already raised in #89.

**Comment by loetefix** [comment]
Yes.

**Comment by MIKE-DAILEY** [comment]
Duplicate of #89
