### ISSUE TITLE
Feature request. Save pot-sliders position to checklist

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#1960]
Given that same as trims, pots or sliders are frequently used to fine-adjust other parameters like gain, steering etc on the go, it is important that those settings to be stored in the checklist, so that they do not need to be re-adjusted each time the model is selected. I noticed that you can load the settings, but that implies remembering before powering off the transmitter to reload after each adjustment of the positions. From the practical point of view for those that fly frequently, this load should be automatic during the powering off process.

**Comment by mawzthefinn** [comment]
The current behaviour is deliberate and correct, you don’t want any old position automatically saved as the analogs may get bumped or adjusted out of the desired default position from the point of adjustment until power off/model change.

Note that the use of trimmers does behave this way, but they are also harder to bump out of position than a pot or slider. I recommend use of trimmers for gain where possible for this reason.

**Comment by Richrfl** [comment]
Although the use of T5 or T6 is an acceptable solution to the problem. but not too happy about it, as these trims can be used for other purposes, like for example independent trim for dual channel elevators, canards, flaps, etc., I do not fully agree with you about accidentally bumping the pots, particularly S1 or S2, which are located in a pretty much hard area to access while flying. With that said, I have to ask another question: Which is the purpose of S1 and S2? I could take that you can use one of them to control the volume, but you have the LS and RS available for that and in a very comfortable place to move them while flying. I think that storing the position of S1 and S2 is safe and useful, especially considering releasing T5 andT6 for functions that otherwise cannot be achieved.

**Comment by Richrfl** [comment]
This is a very important feature. I would like to be sure before setting it to stale that the item will be addressed sooner rather than later. The use of gyros' gain control in all new receivers requires the knobs S1 and S2 position to be stored the same way the trims are. Although only one of the knobs is needed, both should be stored for those users that prefer left or right-hand use.

**Comment by bsongis-frsky** [comment]
I don't understand the request here, pots / sliders have a mechanical position, the firmware cannot store another position, yes?

**Comment by Richrfl** [comment]
No. 
Well, Bertrand, I did not "invent" this feature. FrSky legacy transmitters running either OpenTX or EdgeTX, have that feature.
Now, I am not a software developer, but I have been working too closely with them. The way I see it is that usually, a slider position is reflected (mechanical to electrical conversion) as a voltage, which, to be used in a computer environment is converted to digital data, which usually is stored in a memory location. 
With that said, I think it is redundant for me to say that if in the power-off process, that data is saved in the plane definition area (like the positions of the switches, which, BTW, are also mechanical positions) when you select the plane and have the checklist for the knobs as the last position, (like the switches position, which is some representation of a voltage), you can move the switch until the converted voltage equalizes the stored value, and have the position like the last time you flew that plane.
Again, a quick look at previous FrSky firmware will confirm this request is not out of the thin air.

**Comment by Dsrenger** [comment]
I still dont get it.

You want to save the position of the sliders and pots saved to the checklist during power off automatically?
During the next power on of the transmitter the checklist should give a message if the slider is not in position it was during power off?
Is that right?

Just summarizing my understand in other words to make sure we understand what you want.

If thats the case, i think thats totally against the meaning of the checklist feature.  (doesnt mean it makes no sense)

The checklist checks the position of the sliders, switches ect. against a predefined position. Not against the power off position.

**Comment by Richrfl** [comment]
That would be great!!. Thanks a lot!!. Let me know if there is anything I can do to help.

**Comment by Richrfl** [comment]
The issue is addressed in rev 1.4.4.
