### ISSUE TITLE
Special function Global option selection grayed (restricted use?)

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#1962]
I am running the latest FW and set up a plane with Special Functions. Out of 7 SFs, only two allowed me to set the Global option ON. The rest are greyed. Is there any restriction to that effect?
Here are the screen shots of two very similar SFs, one with Global active, the other greyed (disabled?). When I scroll from Active condition it jumps to Value.
![screenshot-2022-10-09-59196](https://user-images.githubusercontent.com/9392774/194949325-c550de1e-3143-4c28-9dfd-dbb6075268cd.jpg)
![screenshot-2022-10-09-59225](https://user-images.githubusercontent.com/9392774/194949338-e565f6ef-c8f1-4677-95f1-24b2724aa456.jpg)

**Comment by mawzthefinn** [comment]
One is calling a telemetry value that depends on an external sensor and thus is not present on all models.

**Comment by Richrfl** [comment]
Understood. That makes sense. Thank you.
