### ISSUE TITLE
Show source in curve edit from mix

### ISSUE THREAD

**Issue by janekx** [FrSkyRC/ETHOS-Feedback-Community#1964]
If we have some mix and add the curve we can edit the curve from that mix. But we see only source position in mixer and not in edited curve. 
Would be nice if we edit curve from some mix to see the source allready in curve editor.

**Comment by janekx** [comment]
yes i mean show source only of the mix from where is curve edited

**Comment by mawzthefinn** [comment]
Duplicate of #24, closing off in favour of that issue
