### ISSUE TITLE
Some model not showing in the model folder

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#1966]
I have a weird situation where the model folder is showing two models: One actual model and another I created and either Edited or Deleted (Can't remember). However, I have two models, meaning that one of them is not showing in the model folder, or is showing with the wrong name. 
![screenshot-2022-10-12-44625](https://user-images.githubusercontent.com/9392774/195400005-c430b5c9-fe2f-4bf7-9127-5e6c902fbd49.jpg)
![screenshot-2022-10-12-44598](https://user-images.githubusercontent.com/9392774/195400008-b0ee0413-38fc-4c1c-9e8b-79579947509b.jpg)

**Comment by Richrfl** [comment]
More information. Most probably this model was Edited from another called test2. Problem is that the file name was not updated to the current model name. If you clone the file it will use the same original name with a number at the end. Normally, after cloning the model, you adopt a new name. It would be too difficult to update the file name to the corresponding model name?

**Comment by mawzthefinn** [comment]
Model Select shows the Model Name from Model->Edit Model, which may or may not match the filename

You can see the filename for the model listed in the info display along the bottom. So test2.bin is the model named PC-9

**Comment by Richrfl** [comment]
Yes, I saw that, but that is not a solution. I may agree that renaming a model is not a usual thing, but in my view, not updating the name is not right. If I back up the models and I have to restore them, then I will not have a clue of which model am I restoring unless I write a table with a cross-reference, I keep that one somewhere where I will hopefully find it in a couple of months. 
However, given that I do not like to have the development team running from one end to the other, I would like to ask you a question: Can I just rename the file from my windows explorer? That would solve the problem.

**Comment by mawzthefinn** [comment]
Yes, you can just rename the file from Explorer.

The model names matching file names is a relatively new feature (introduced with 1.2.11, prior to that the files were always named modelxx.bin) and there's still some issues with it. I do agree that a model name change should update the file name.

**Comment by Richrfl** [comment]
Thank you for your response. While the issue is addressed, I'll manually rename the file. Hopefully I will never need to do any restore anyways. (I already had to do one, one week after receiving the transmitter).
