### ISSUE TITLE
Feature request logical switch lowest cell voltage.

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#197]
Please would you be able to add a logical switch or similar for the lowest cell voltage.  Useful for identifying a failing cell in a battery pack or for voltage alarm.

**Comment by islandflight** [comment]
The lowest cell voltage from the telemetry please

**Comment by Nicholas-Luoyi** [comment]
Please try the steps below:
1. Select the normal voltage from the source choice
2. Keep the focus on the source choice and long press the enter
3. Choose the max/min tag
![IMG_8528](https://user-images.githubusercontent.com/58321103/117913909-d9385e80-b314-11eb-80f3-0dbaa827a432.PNG)

**Comment by Nicholas-Luoyi** [comment]
I'll take a look into it.

**Comment by islandflight** [comment]
Hi, I have been experimenting further. To confirm the played values for lowest cell volume on a repeat cycle only play the initial value and does not change the call out as the voltage drops.

When viewing the minimum cell voltage data from the flvss sensor and using a 4 cell Lipo two cell values seem to show correctly whilst the other two read zero volts. They then read correctly if the value is reset. Suggesting some issue with the initial data reading zero as a minimum value when first connected and thus storing as a minimal value. I've tried several lipos.

It would seem when using ACCST the minimum total cell voltage setting does not indicate the individual cell minimum voltage only the minimum total cell voltage hence why was reading 7.7 volts as it was only detecting 2 of the 4 cells until the data reset as above.

Using access R8 Pro the lowest cell vale is reported when the telemetry data is reset to show correct minimum values for all cells. Hope this helps a bit. Thanks

**Comment by Nicholas-Luoyi** [comment]
Please see #377 for details.
