### ISSUE TITLE
ETHOS Sensor Discovery does not find all Sensors

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1971]
I have programmed a MSB / S-Port converter, in order to use MSB capable sensors with a FrSky Rx. In doing so, I have found that sensors with an Application ID 0x0A10 to 0x0A1F (Fuel in ml) are not found by the ETHOS 'Discover new sensors' feature. I need to create a DIY sensor and use the 'Auto detect' option in order to detect such a sensor.
I beleive ETHOS should find all sensors transmitting valid S-Port data pakets when 'Discover new sensors' is selected.

I have used a Tandem X20S with ETHOS 1.3.3 for these tests.

**Comment by bsongis-frsky** [comment]
There is no 0x0A10 in my S.Port documentation!
Fuel is 0x0600 to 0x060F

**Comment by Hartinger** [comment]
I have taken these IDs from the OpenTx source code, assuming they would be the same in ETHOS.

#define FUEL_QTY_FIRST_ID         0x0A10
#define FUEL_QTY_LAST_ID          0x0A1F

**Comment by bsongis-frsky** [comment]
The reference is rather the S.Port documentation

**Comment by Hartinger** [comment]
OK, no problem; thanks for the feedback.
