### ISSUE TITLE
Option to select the model at power on event

### ISSUE THREAD

**Issue by rafaelbiriba** [FrSkyRC/ETHOS-Feedback-Community#1972]
Is there anyway to make ethos (x20s) asking me which model i am going to fly, on the power on?

This could be a configuration under system settings.

Usually i fly model 1, model 2, model 3, repeat. Is a bit annoying have to turn on and them change the model all the time, instead of having the radio asking me what I am going to fly now.

**Comment by Wolepo** [comment]
You can change the content of hello.wav.
But you still have to change the model manually.

**Comment by rafaelbiriba** [comment]
> But you still have to change the model manually.

That is my suggestion here!

Power on and stop on the model selection screen!

**Comment by mawzthefinn** [comment]
I don't see a lot of point to this. 

It's saving a single button press and nothing more (just long-press MDL after power on to get what you want).

**Comment by rafaelbiriba** [comment]
This is why I believe it should be a flag over the configuration.

The feedback comes from me and other 2 pilots from my loca field.

Turning the radio on, it simple get ready for a model that you are not going to fly. That also means scripts will run, audio settings will start speaking.

At least for some of my helicopters, when you select the model, it tells me which switch is in the wrong position and that is different from another model.

So it is not just `press the model button`, but on the power on, I have to or ignore the switch warning or fix the switch, change the model and switch it back.

**Comment by enzo-molinari** [comment]
I don't see a lot of point to this too.

**Comment by rafaelbiriba** [comment]
Just passing the feedback of 3 pilots together along! If it does not work for you, it does work for people that requires a model selection before the radio full initialise with all scripts and callbacks for no reason (due to the wrong model selected)

**Comment by rafaelbiriba** [comment]
Model 1: Switch warning is: all switchs to the top
Model 2: Switch warning is: all switch to the bottom.

If you are going to fly model 2, and the radio starts on model 1, you are going to receive annoying warnings for the switchs, and the first action will be ignore the switch warning in order to change model.

This could already cause human mistake, because the model 1 is pre-selected, the switch warning got ignored, and if you decide to fly model 1 now, there will be an accident due to the wrong position of the switches.

But, let's go back to the happy path... Ignored the switch warnings, now we have custom scripts and custom sounds playing on the back ground... second anoying thing... until we finally get to the model menu and switch to model 2.

Does that looks ok for you all??

And yes, it was unanimous from all FRSKY users of my club (3 out of 100, 😆 ) that the feature is important!

I will not waste my time explaning again and again! If there is no point, feel free to close the issue!

Just trying to make ethos better OS.

**Comment by enzo-molinari** [comment]
It is not necessary to set the switches correctly. You can skip the checklist with the enter button.

For this reason I don't see a lot of point to this.

**Comment by rafaelbiriba** [comment]
That is the sad part of ETHOS X OpenTX!

I am not able to make a proper pull request or even run a custom version with the changes that fulfil my needs!

So far I collected feedback, spoke with different people, reported what could be done to improve here, and I have to extend myself and explain in details the whys!

>Most want to turn on the transmitter and d'ont want to select a model every time.
>That would annoy me.

That is why it should be `an option`, you can enable or not :) 

> Precisely, because you can skip the checklist, 
Should you? The checklist make the radio safe for the selected model. If you skip the checklist and do not switch model, you have a very unsafe radio! Congrats!

**Comment by Wolepo** [comment]
Somehow everything is far-fetched. How is the transmitter supposed to know which model the pilot wants to fly?
 The only thing I could imagine is the option that the transmitter asks after switching on and before loading the active model whether it should load the last active model or another model. But that would still have to be selected manually.

**Comment by rafaelbiriba** [comment]
@Wolepo that is exactly the use case here.
After power on, the radio will wait for the model selection. (similar to the switch warning screen).

The use case is pretty solid, especially for people that have many numbers of models and the chance to fly same model twice is almost none.

**Comment by bsongis-frsky** [comment]
I don't have so many models, but it makes sense to me. It would be a setting in System / General

**Comment by bsongis-frsky** [comment]
Another request in the same area is #1925

**Comment by rafaelbiriba** [comment]
:(

**Comment by rafaelbiriba** [comment]
that is the difference between ethos and opentx (private vs opensource) , I don't have voice and I don't even have the opportunity to implement it myself!
Strong considering to move back to opentx after this. Which is a shame, since I spend many posts talking positive on ethos... but this unilateral decisions hurts!

**Comment by mawzthefinn** [comment]
You do have a voice, that is why  this issue existed in the first place. As a participant in this issue, you would have received a notification 5 days ago that the issue was stale and would be closed if not commented on. Nobody commented and so it was closed. 

Not a unilateral decision, simply a cleanup process that notified you.

This has been re-opened.

**Comment by rafaelbiriba** [comment]
@mawzthefinn thanks for coming back!
I am not having a great day and the closed notification did not help! Sorry for the extra pepper on my message!

**Comment by mawzthefinn** [comment]
No worries, I can understand that.

**Comment by bsongis-frsky** [comment]
This feature is assigned to 1.5.0 and it is even ready for merge

**Comment by rafaelbiriba** [comment]
WOW! 👯

**Comment by rafaelbiriba** [comment]
Count on me for the BETA tester!

**Comment by bsongis-frsky** [comment]
Merged

**Comment by rafaelbiriba** [comment]
WOW 🍰
