### ISSUE TITLE
Configuration of Crossfire or ELRS in 1.4.0 PR - new LUA script required?

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#1975]
Hi,

in the PR of 1.4.0 there is no selection for Crossfire or ELRS with the CRSF protocol. Is a new LUA script needed for this (like for the multimodules)?

It is possible to select the TwinLite Pro module with the ELRS "protocol", but an ELRS module does not respond. And the TwinLite Pro module should still be quite rare ...

**Comment by MIKE-DAILEY** [comment]
Not all of the 1.4.0. components are released yet.   It takes time for it to all get posted on GitHub.  Sandby awhile.

**Comment by bsongis-frsky** [comment]
The ELRS script is online. But still very incomplete, I will continue working on it when time allows. Here is the status as of today:

![image](https://user-images.githubusercontent.com/50834778/196715968-8834eed7-06b9-4f7d-882f-177380f034e4.png)

**Comment by Target0815** [comment]
Are these settings solely a matter of the external, disclosed LUA script or is this programmed internally in Ethos?

I ask because with ELRS and an Arduplane FC also an entry for "Arduplane" appears. It would be interesting for me to write a script for it, for example to change parameters. However, I currently have no idea how the context is with these things ...

**Comment by Target0815** [comment]
Under System / Info, "Unknown" currently appears under External Module if an ELRS module is configured. However, the module name ("HM ES24TX") is known in the Model Setup / RF System.
