### ISSUE TITLE
'Backup your radio' in Suite 1.4.0 is misleading

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1977]
Ethos 1.4.0 pre-release

On the new Model Manager page the option to 'Backup your radio' is misleading. I would read this as backing up the whole radio, but the Release Note lists the feature to 'Add model file backup and restore'.

So the label at the top should read 'Model file backup and restore' and the two Buttons 'Backup to PC' and 'Restore from PC'

**Comment by glipski50** [comment]
Images and user audio files should be included to the backup as well

**Comment by drummaker** [comment]
Instead of this, how about just actually backing up the whole radio.  Like in my case someone stole my whole radio and though I had most models backed up it still took a while to get all my icons and sounds back

**Comment by mawzthefinn** [comment]
The backup your models only functionality is quite useful and should not be changed. It's very useful for syncing models between radios and addressing firmware rollback issues.

Backup of whole radio needs to be a second option. It's equally valuable, but doesn't need to happen as often, really only when you make a change to audio, images or scripts.

**Comment by mawzthefinn** [comment]
Suite 1.4.3 now backs up the whole radio. Categories are selectable so the behaviour I wanted kept (Models only) is also available.

**Comment by mawzthefinn** [comment]
Closing off as this is completed
