### ISSUE TITLE
Two buttons labelled Ethos in Suite

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1978]
Suite 1.4.0 pre-release

Under Radio in the explorer bar the button marked Ethos should better be labelled Updates to avoid confusion with the button marked Start Ethos in the Bootloader mode tab. 
<img width="1222" alt="03 x20" src="https://user-images.githubusercontent.com/26259987/196674168-ec0fa203-6ea9-4ac7-8322-9c39e9baf181.png">

**Comment by mawzthefinn** [comment]
Seems pretty clear to me. One is the tab for managing ETHOS (it does more than just update the radio), the other is the one to click when you want to Start ETHOS on the radio.

If both buttons were just named Ethos, I'd agree.

That said, the button on the left should be capitalized to match the ETHOS branding used elsewhere.
