### ISSUE TITLE
CRSF: LUA crossfire.popFrame() issue

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#1979]
in my wakeup() I have a for loop that invokes crossfire.popFrame() many times per wakeup() call.
I print to the serial console the values of command and data and in my setup the call returns nil,nil for a couple seconds and then dumps the incoming queue with all the sensor data it has accumulated in those 2 seconds, than nothing again for 2/3 seconds and another dump of all the data accumulated.

This behaviour can be observed also in the telemetry sensor page where all CRSF native sensors are refreshed at a very high rate (many times per second) while sensor telemetry from the RX (connected to ardupilot) is refreshed every 2 or 3 seconds

I suspect the crossfire telemetry queue is dropping packets, the number of packets I receive is inferior to the packets I send

**Comment by bsongis-frsky** [comment]
How many packets are received per second?
