### ISSUE TITLE
x12s  os 1.0.5

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#198]
Hello the frsky team. x 12s os1.0.5
I see that on this version, none of the three points that I submitted to you have been resolved !!
1) the logs are not structured correctly. With opentx each time you start a log recording, you create a folder that contains the logs .... very handy to find what you are looking for .... by date or time .... more , a lua allows these files to be viewed on the radio. # 120
2) the chronos .... for the moment, impossible to start or stop a chrono via any actuator example the left slide ..... etc .... # 121
3) Still impossible to update an x8r via the s-port ..... only ota ..... # 149
thank you for showing interest in this.

**Comment by bsongis-frsky** [comment]
If the issues are already opened, why do you open a new one?
