### ISSUE TITLE
Bluetooth transmission

### ISSUE THREAD

**Issue by chenbevis** [FrSkyRC/ETHOS-Feedback-Community#1981]
Is it possible to use the bluetooth of the mobile phone to transmit the pictures and sound files of the plane? I often use the mobile phone to take pictures of the plane model and then modify the pixel size. Finally, I take out the SD card of the X20S and connect it to the mobile phone to copy the pictures into it. It is a bit troublesome to do so.

**Comment by mawzthefinn** [comment]
Not currently.

If you have a USB-C OTG cable, you may be able to just plug the phone directly into the radio and save the pictures without doing the card shuffle.

**Comment by chenbevis** [comment]
It doesn't work when I use the USB-C OTG cable

**Comment by mawzthefinn** [comment]
Select FrSky Suite when connecting and you should be able to mount the SD/NAND
