### ISSUE TITLE
Italian Translation Update Ethos 1.4.0 

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#1982]
[it.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9824618/it.txt)

Can You also provide me the json file of the new ethos suite to get new things translated... thank you in advance
@bsongis @Adelaxie @MIKE-DAILEY @WismyYao

**Comment by bsongis-frsky** [comment]
Please look at the wiki for Suite translations!

**Comment by mgsanna** [comment]
> Please look at the wiki for Suite translations!

I didn't find anything about ethos suite localisation, on wiki..... can you explain me better?
thanks in advance

**Comment by bsongis-frsky** [comment]
Oh god I am sure I have written how to do this somewhere and I cannot remember where
