### ISSUE TITLE
Better directory names for modules

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#1983]
IMHO the directory names for modules are chosen a bit unfortunate ... Current it is so:

\scripts\modules <= main.lua for Multimodules
\scripts\elrs <= main.lua for ELRS modules

It would be better and more sustainable that way:

\scripts\modules = Collective directory for modules
\scripts\modules\multi = Multimodules
\scripts\modules\elrs = ELRS modules
\scripts\modules\crossfire = Crossfire modules

**Comment by bsongis-frsky** [comment]
We don't recurse subdirectories on radio startup, it would take too long!

You may change the names of those directories as you wish, they are just examples, the name is not important.

But you are right and I will change the names of the examples like this:
scripts/multi
scripts/elrs
scripts/ghost
scripts/crossfire
