### ISSUE TITLE
Minor changes to displaying the Custom Sensor operators

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1985]
Ethos 1.4.0 pre-release

It would be more consistent with conventions to display:

Subtract(-) instead of Minus(-) [Subtraction is the process of subtracting a number from another while minus is a symbol. We are also not saying Plus(+)]. 

Multiply(*) instead of Multiply(x) [in expressions (x) can be confused with the variable x]

![operators](https://user-images.githubusercontent.com/26259987/197099257-d4e46cba-0f2b-4add-a1b9-40d4c8b85e45.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/197151206-27de54bd-a876-49b7-87bc-3621a240ec52.png)
