### ISSUE TITLE
Is there a instant trim function

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1987]
Is there an instant trim function yet on Ethos? If so how to use?

**Comment by mawzthefinn** [comment]
Duplicate of #295 

It’s been requested, but not implemented.

**Comment by bsongis-frsky** [comment]
Duplicate. Too much to do!

**Comment by robertoalmeida** [comment]
> Is there an instant trim function yet on Ethos? If so how to use?

Will it be implemented?
