### ISSUE TITLE
Ethos on X20 does not find all available telemetry values from G-RX8

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#199]
Examples are:
Alt+ and Alt-

These were available on my X10s running OpenTX

**Comment by MIKE-DAILEY** [comment]
They are supported in ETHOS too.  Once you have selected Alt somewhere for use (on one of the screen cells for and example) long press enter on the Alt name to get the popup.  On the popup select Min or Max.

**Comment by KenLong51** [comment]
Many thanks Mike - Sorted
