### ISSUE TITLE
Odd behaviour after flashing 1.4.1

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#1991]
Saw this on both my X18 and X20, after flashing 1.4.1 via ETHOS Suite and having the radio reboot into Firmware mode with ETHOS Suite connected

RTC Battery warning, not RTC battery data displayed in System->Battery, no volume control (still correctly configured, just the radio was ignoring it)

In both cases a power cycle with USB disconnected resolved the issues.

**Comment by bsongis-frsky** [comment]
Is it easily reproductible? 
Never met in earlier versions?

**Comment by aalain8** [comment]
Hello?
I can confirm the problem.
X20S updated from ethos 1.3.3 to 1.4.1.
The voltage of the radio goes to 86.3 V and the RTC battery to 58.9 V.
Also the sound is back by default.
I reconnected the radio to Etos-suite, redid the 1.4.1 update "of all components" everything is back to normal.

**Comment by mawzthefinn** [comment]
Yes, does not occur in previous versions (including 1.4.0)

I was able to reproduce by reflashing 1.4.1 firmware, the errors occurred again on disconnecting the radio from USB, cleared again by restarting the radio. 

Note I also noted this time that main radio voltage is 0.0 on my X18 when I do this.

**Comment by bsongis-frsky** [comment]
All ADC then. It is strange that it didn't happen before 1.4.1

**Comment by mawzthefinn** [comment]
Seems to be fixed with 1.4.2
