### ISSUE TITLE
X20s gimbals will not work

### ISSUE THREAD

**Issue by antlerhanger** [FrSkyRC/ETHOS-Feedback-Community#1992]
After flashing to the latest fw the gimbals will not work ..The rudder will move 50% . Switches all work . Any ideas ? I Have 20 models in the radio and they are all the same

Thanks

**Comment by yak-54** [comment]
sounds like the radio bin file got updated you may  need to redo menu system/Hardware/Analogs calibration

**Comment by bsongis-frsky** [comment]
It would be interesting if you could attach your file radio.bin
What was the installed version before the update?

**Comment by antlerhanger** [comment]
The version was 1.3.3 before update . 1.41 after update . I can't do a
calibration as the gimbals will not move on the screen .

Thanks
Allen

**Comment by antlerhanger** [comment]
Here is the file
