### ISSUE TITLE
MSH FCU integration

### ISSUE THREAD

**Issue by RO-ULT527** [FrSkyRC/ETHOS-Feedback-Community#1994]
I heard from Rik 1.4.0 did not work with MSH luac. I loaded public release 1.4.1 a few seconds ago and it does not work either.

**Comment by bsongis-frsky** [comment]
Please open an issue on the MSH project, I will be happy to help but we don't have the source code of the MSH Lua scripts!
Perhaps it's related to the other issue with sport sensors and it will be fixed in the same time? I will look at it closely on monday.

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1996
