### ISSUE TITLE
Lost tune facility on latest Multimodule LUA

### ISSUE THREAD

**Issue by KevinFairgrieve** [FrSkyRC/ETHOS-Feedback-Community#1995]
Updated to 1.4.1
Made the new structure for external modules.

scripts/multi
scripts/elrs
scripts/ghost
scripts/crossfire

Copied the main.lua to scripts/multi

Allows me to select multimodule and Frsky V. Bind no problem, but the option for RF tune has gone.

Same on my X12S

**Comment by Target0815** [comment]
Multi uses a new main.lua. Did you take this one?

**Comment by KevinFairgrieve** [comment]
> 

Yes, the latest from [https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua/multi](url)

**Comment by Zebble** [comment]
I can confirm the same issue.

**Comment by bsongis-frsky** [comment]
RF Tune on which protocol?

**Comment by bsongis-frsky** [comment]
I see that only OMP has this option enabled, if you need it in another script you may modify by yourself

**Comment by KevinFairgrieve** [comment]
Was also available on Frsky V and D on a previous version. Possibly others but I do not have the means to test.
Regressing back to 1.3.3 and using the old lua it shows.
![1](https://user-images.githubusercontent.com/20424058/197356009-822d17ee-4ac1-4323-a230-177a7a1839cd.jpg)
![2](https://user-images.githubusercontent.com/20424058/197356016-a1c64ccb-2462-48b3-8c49-ea37d6dd65ee.jpg)
![3](https://user-images.githubusercontent.com/20424058/197356027-0fccc252-5b57-49e2-92c4-42c2a7c973a2.jpg)

Top image shows a comparison X12S running 1.4.1 X2o running 1.3.3 (I went back to 1.3.3)

Middle image shows RF tune as available
Bottom image shows no such option.

**Comment by KevinFairgrieve** [comment]
> I see that only OMP has this option enabled, if you need it in another script you may modify by yourself

I am no programmer, how would one go about adding this option?

**Comment by KevinFairgrieve** [comment]
> I can confirm the same issue.

I have now I think sorted this. 

You can try my file below if you wish.
Rename the file to main.lua


[main.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9846074/main.txt)

Can you confirm if this works for you (it works for me) and if it does I can close the issue

**Comment by bsongis-frsky** [comment]
Don't hesitate to fork and send a PR ;)

Le dim. 23 oct. 2022 à 11:01, Kevin Fairgrieve ***@***.***> a
écrit :

**Comment by bsongis-frsky** [comment]
I have pushed your changes to the repository
