### ISSUE TITLE
lua: ethos 1.4 changed something in sport / sensor class

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#1996]
Hi,

by release of Ethos 1.4.x something has changed in the behaviour of the sport / sensor class

Until now i polled data using code like this:

```
local APP_ID <const>		= 0x0C20
local ditem 			= 0x0DFF

sensor={} 																	-- SPORT sensor
sensor = sport.getSensor({appId=APP_ID});
sensor:idle()

widget.sensor:pushFrame({primId=0x30, appId=APP_ID,value= dItem })
```

This doesn't work any longer, pushFrame method returns false !

i managed to poll data by inserting the (optional) parameters like: band, rxIdx & physId
**at least physId seems to be mandatory now**

i couldn't find any changelog or adopted lua docs, so it might be a inadvertent side effect of something else.
Would appreciate the "older" way because it gives some more flexibility, if not applicable please update lua docs

thanks & regards

Udo

**Comment by bsongis-frsky** [comment]
If pushFrame returns false, it means that the queue is already filled, it shouldn't depend on any parameters!

**Comment by bsongis-frsky** [comment]
The module is very important

**Comment by bsongis-frsky** [comment]
You are right, something has changed: it was not possible to send any frame on the external port
I will set the module=0 as default, because there is no default module right now, and your frame is never sent
