### ISSUE TITLE
Consumption calculations Problem 

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#1997]
Hi all,
the calculation of the (battery) consumption does not work.  The display stays at 0.0 mAh.  
Ethos 1.4.1 
Horus 10xs  ISRM 
current sensor FrSky 40A

![99D2987D-1DF4-4F74-BD1E-BFBD146547F5](https://user-images.githubusercontent.com/68751162/197338278-5213df19-7995-4678-8b09-c5140d8daaee.jpeg)

![41BE46E0-9B69-4301-AA4C-C21B458DFF45](https://user-images.githubusercontent.com/68751162/197338261-18376662-562b-4180-91e6-5d90debde819.jpeg)

**Comment by Tonio62** [comment]
Same for me, x20 1.4.1

**Comment by bsongis-frsky** [comment]
Confirmed
There is a regression in units conversion
