### ISSUE TITLE
Emergency Mode with external module configuration

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#1998]
Hi,

Call the configuration of an external module and press the RTN button while the bar on the right is still moving upwards. It does not happen every time, but the Emergency Mode can be provoked this way.

Tested with ELRS (HM ES24TX) and Crossfire Nano TX.

Ethos 1.4.1 / Tandem X18S

**Comment by bsongis-frsky** [comment]
Press RTN while the screen is not fully populated, right?

**Comment by Target0815** [comment]
Yes.

**Comment by bsongis-frsky** [comment]
Reproduced on simulator too

**Comment by kakashi2018** [comment]
@Target0815  I have ethos 1.4.0 installed currently but in the external module selection I don't see elrs or crossfire. Do we need to add anything else to use crossfire modules?
