### ISSUE TITLE
F.Port selection option missing quadcopter model/r9MX

### ISSUE THREAD

**Issue by RyanMacaluso2211** [FrSkyRC/ETHOS-Feedback-Community#2]
No F.Port check box to choose to use F.port on reciever options for bound reciever.  Tested on x20 with r9MX.

**Comment by Adelaxie** [comment]
fixed

**Comment by RyanMacaluso2211** [comment]
Awesome! I?ll get some quads setup on the Tandem and continue reporting anything I find. I know I?m probably the only one doing quads with the Tandem/ETHOS right now.On Wed, Mar 17, 2021 at 8:36 PM Adela ***@***.***> wrote:
fixed

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Ryan Macaluso aka MacaluciferFPV|| FrSky-RC_US || Marketing Director & Sales+1 717 385 0009

**Comment by RyanMacaluso2211** [comment]
Do you know when a new update will be released with this fixed?
