### ISSUE TITLE
Ethos on X20 - Is it possible for the vario to only sound when climbing?

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#200]
No sound means I'm not climbing.
I guess just silent when not going up, or down, would also be OK.
These are options on X10s (OpenTX)

**Comment by bsongis-frsky** [comment]
Link to #223

**Comment by bactisme** [comment]
I think this issue is marked closed but, pardon me, I don't think the will to have an option for vario only announcing up is taken into account.
