### ISSUE TITLE
X12S with external Module RFD TX mod rebooting Radio

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2001]
X12S with external Module ( rfd TXmod ) goes into Emergency mode then reboots will not power off have to remove battery 

https://youtu.be/jAjmlPD6hEU

**Comment by Target0815** [comment]
Except for the transmitter, this is like the bug in #1998.

Also there the emergency mode can not be switched off or the transmitter can not be switched off. 10 sec button press would probably be good to turn off the transmitter. Pulling the battery is a bit cumbersome.

**Comment by yak-54** [comment]
> Except for the transmitter, this is like the bug in #1998.
> 
> Also there the transmitter can not be switched off. 10 sec button press would probably be good to turn off the transmitter. Pulling the battery is a bit cumbersome.

i have tried 10 sec 30 sec 40 sec no go just urns back on

**Comment by Target0815** [comment]
Yes, that doesn't work with the 10 seconds but would be good if it did ... ;-)

**Comment by bsongis-frsky** [comment]
@yak-54 did it work previously?

**Comment by yak-54** [comment]
never tried it till 1.4.1 but the module works fine on Opentx 
but i did notices if i power on the radio with out a receiver  powered on it does not crash in to emergency mode
to it looks like as soon as there is a receiver power on and it starts sending sport data it goes into emergency mode

**Comment by yak-54** [comment]
just doing some testing i found if i turn off telemetry in the  receiver and put in PPM mode 
the ppm side works fine

**Comment by bsongis-frsky** [comment]
What is the format of the telemetry? S.Port?

**Comment by bsongis-frsky** [comment]
If you set your radio in PPM mode, then you shutdown it / restart it, and only then you plug the module, does the radio reboot? I am sorry, I cannot do this test myself, I don't own this module.

**Comment by Target0815** [comment]
> What is the format of the telemetry? S.Port?

The RFDesign TXMod provides S.Port passthrough telemetry (for the Yaapu script).

I still have to test myself if it really works. Currently it is unclear whether we can feed S.Port Passthrough in the module bay or at the external S.Port connector on the top of the transmitter.

BTW, it would be good if we could turn off the transmitter despite Emergency Mode. Always pull the battery is quite annoying ...

**Comment by yak-54** [comment]
> If you set your radio in PPM mode, then you shutdown it / restart it, and only then you plug the module, does the radio reboot? I am sorry, I cannot do this test myself, I don't own this module.

its fine in PPM mode plug it in turn off and turn on and power on and off ran it for 5 mins 
but as soon as i power  on the receiver and it starts sending S.Port Passthrough the radio goes into Emergency mode
and it will not power off try to power it off as soon as you let go of the power button it restarts in Emergency mode again

**Comment by bsongis-frsky** [comment]
So. You start the radio and acknowledge the warnings. No problem. Now you plug the module and the radio reboots.
No action in the menus, right?
Is your bootloader / firmware up to date?
I ask because if you do exactly this, the telemetry port is not even initialized (at least it should not) and it's strange that the radio reboots

**Comment by bsongis-frsky** [comment]
bug because it should not reboot
enhancement because you need something which doesn't exist

**Comment by yak-54** [comment]
> So. You start the radio and acknowledge the warnings. No problem. Now you plug the module and the radio reboots. No action in the menus, right? Is your bootloader / firmware up to date? I ask because if you do exactly this, the telemetry port is not even initialized (at least it should not) and it's strange that the radio reboots

up to date ethos 1.4.2 bootloader 1.4.2

if i power the radio on the plug the module in it works fine with out an receiver powered on
but if i power on the receiver first in the plane then power on the radio and plug the module in  it goes into Emergency mode and i cant power it off

and if i bind the  receiver with out telemetry so there in no S-port data   PPM works fine i get control inputs  to flight controller 
but as soon as i bind it with telemetry i get Emergency mode and the radio will not power off

**Comment by yak-54** [comment]
i even tried to turn the module off in the menu and then power the radio back on plugged the module back in  then power on the module on in the menu its fine if there in no sport data or telemetry

**Comment by bsongis-frsky** [comment]
How is it with OpenTX with the same radio?

**Comment by yak-54** [comment]
> How is it with OpenTX with the same radio?

no i works fine with opentx i even put opentx back on this  radio just make shaw it was ok and it is

**Comment by yak-54** [comment]
#2144
