### ISSUE TITLE
Suite Developer Mode indication is misleading

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2002]
Suite 1.4.0

In Suite Settings, the Suite Developer Mode indication is very misleading.

The green indicator says 'Developer Mode Enable' leading you to believe that it is not enabled yet, and that the green indicator is in fact a button. Please note that 'enable' is a verb, but 'enabled' is the correct adjective.

It would be better to move the green indicator up and into the middle, and to change the label to read 'Developer Mode Enabled' or 'Developer Mode Active'. The fact that the indicator is at the bottom right adds to the illusion that it is a button.

**Comment by Nicholas-Luoyi** [comment]
I will change that. Thanks
