### ISSUE TITLE
Storage location - incorrect storage

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2004]
Hi,

I have placed the storage location for logs and screenshots on the SD card according to the configuration:

![ethos_screenshot](https://user-images.githubusercontent.com/31627548/197377145-7b56424a-f695-40eb-9cbe-c2c185aa2f5e.jpg)

Nevertheless, the logs and screenshots are stored on the NAND drive.

Ethos 1.4.1 / Tandem X18S

**Comment by bsongis-frsky** [comment]
We have checked it today and we have seen no issue, would you please double check?
Or somebody else can have a try as well?

**Comment by Target0815** [comment]
I have the setting as in the screenshot and the screenshots, including this one, are stored on the NAND drive. 

But I can gladly reset later and test again.

**Comment by Target0815** [comment]
@bsongis-frsky New test: set to "Save to Radio", restart transmitter. Screenshot is stored on the radio / NAND. Change to "Save to SD Card", restart transmitter. Screenshot is stored on the radio / NAND again. So still wrong.

Originally I got the transmitter with 1.3.2 and changed there. Since the filing on the SD card worked. With 1.3.3 I do not know it anymore, with 1.4.0 and now 1.4.1 only the radio / NAND drive is addressed.

**Comment by bsongis-frsky** [comment]
I have done the test myself on X18. No issue.

What is the label "Save to Radio" that you are describing?

Please note that the setting doesn't automatically move your directory from Nand to SD, and you don't mention you have enabled the Logs or Screenshot feature!

**Comment by Target0815** [comment]
Label "Save to Radio" according to screenshot above, storage either on radio or SD Card.

In the last test, I only set the screenshots to the SD card. But the storage is still on the radio.

For logs and screenshots, I have the directories on both Radio and SD Card. Maybe this is not the case for you?

**Comment by bsongis-frsky** [comment]
I don't see any "Save to Radio" on your screenshot, is it possible you explain a little bit?

**Comment by Target0815** [comment]
I currently have this setting:

![ethos_screenshot_1](https://user-images.githubusercontent.com/31627548/197576057-0a503742-c962-4f35-9581-f0cc078e3308.jpg)

Both screenshots are on the radio:

![ethos_screenshot_2](https://user-images.githubusercontent.com/31627548/197576222-af66c9e6-f0a4-4aae-b763-9a0f608026e5.jpg)

**Comment by Target0815** [comment]
I wanted to take a screenshot of the empty "screenshot" directory on the SD Card and click on SD Card in the File Manager. And take a screenshot ... and this one screenshot is actually stored on the SD Card ...

Looks to me like the SD Card is not always recognized. The card itself is new, 4 GB in size and was formatted before use. Ethos has also created the two directories "screenshot" and "logs" independently there after I first wanted to store the logs and screenshot there.

**Comment by Target0815** [comment]
This is also the case with the new SD card. It is now 16 GB and empty. In the File Manager I selected SD Card and made a screenshot. Then tap on radio and again on SD Card and the directory "screenshots" was created and the screenshot is also there.

Now turned off the radio, restarted and again made a screenshot. And this is again wrong on the radio.

This is definitely a bug ...

**Comment by bsongis-frsky** [comment]
It has been confirmed by Mike, so you must be right. I will find it.
