### ISSUE TITLE
ELRS with CRSF - missing telemetry sensors/values

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2005]
Hi,

Ethos 1.4.1 / Tandem X18S

I am missing values for telemetry sensors with ELRS. I use ArduPlane 4.3.0 with an ELRS Rx which provides the data via CRSF. I use the same backend for a comparison with OpenTX.

![ethos_elrs_telemery_1](https://user-images.githubusercontent.com/31627548/197406057-d32f465b-c6cd-4328-9f2f-ab8f07ec50f7.jpg)
Rx RSSI1 returns no value, Rx RSSI2 0db. Under OTX 1RSS returns a db value > 0 and 2RSS nothing because the RX is not a diversity.

![ethos_elrs_telemery_2](https://user-images.githubusercontent.com/31627548/197406059-94e00858-e662-45d2-9c5e-4e3c78d40b16.jpg)
Tx RSSI does not provide a value.

![ethos_elrs_telemery_3](https://user-images.githubusercontent.com/31627548/197406060-f4cef0e2-ea9e-4059-9996-09d055f0f4c8.jpg)
Rx Batt does not provide a value. Under OTX the voltage of the flight battery is displayed here.

![ethos_elrs_telemery_4](https://user-images.githubusercontent.com/31627548/197406451-dbd90776-0716-465e-81f3-e087a50a31ca.jpg)
The GPS position should better be displayed decimally.

**Comment by r1000ru** [comment]
Confirm this problems. If use diversity RX, rxrssi1 and rxrssi2 has no values, but must be <0.
