### ISSUE TITLE
1.4.1 Telemetry sensor RPM Neuron ESC Range 0-0

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#2009]
Hello - again problems with RPM telemetry from ESC Neuron - same I had with 1.3.0
![image](https://user-images.githubusercontent.com/78207054/197579453-6e3dc5bd-cf2a-4329-a1e3-2dda9d5b2789.png)
The range is 0-0 and not to adjust. The screenshot is from simulator 1.4. at the X20s it is 0-0 set for the range. 
It was solved with 1.3.3

**Comment by WismyYao** [comment]
Fixed in 1.4.2
![image](https://user-images.githubusercontent.com/16497598/197665701-0abea25d-0380-48ea-b736-45d891e27201.png)
