### ISSUE TITLE
1.4.1 minor flight mode name UI issue

### ISSUE THREAD

**Issue by mikeschuster** [FrSkyRC/ETHOS-Feedback-Community#2010]
1.4.1 FCC X20S

- Create a flight mode with a long name (eg "Slow Thermal").

- Create a Special func to play a track on this flight mode, choose any .wav file to play.

- In the Special funcs list, note that the Condition text "FM# (Slow Thermal)" overlays the Value text (name of track to play)

**Comment by bsongis-frsky** [comment]
Before
====
![image](https://user-images.githubusercontent.com/50834778/197846337-2a23db91-3406-4fec-af2c-2be7c908290a.png)

After
====
![image](https://user-images.githubusercontent.com/50834778/197847210-d70d4a26-1d48-4935-bc8c-25366b90f587.png)
