### ISSUE TITLE
Per log. Switch no reset is possible in some calculating sensors

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2011]
Hello, 
In 1.4.2 there is now the possibility to reset also calculating sensors via log. Switch to perform a reset. However, this does not yet work for all sensors:
1. consumption SBEC
2. trip
3. distance 2D (without altitude)
4. distance 3D (with altitude)
Unfortunately, I cannot check other sensors.

Thanks for the interest.

**Comment by bsongis-frsky** [comment]
I missed it!

**Comment by Wolepo** [comment]
Thank you
