### ISSUE TITLE
1.4.2 X20s Pot.3 Checklist warning at startup and switch Model

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#2012]
![image](https://user-images.githubusercontent.com/78207054/197830656-1defc437-f1a1-431a-841f-e1dc3ef9bcc3.png)

Hello - I guess I wasn't precise enough in my last description of the issue of Pot.3. Now its visible in the Checklist but still not visible in Checklist Warning at startup an chang to another model. 
Wouldn't it be nice to have more a warning picture like the checklist at the Startup warning? To know at which position the knob should be.. 
![image](https://user-images.githubusercontent.com/78207054/197831606-c689f911-adeb-45c9-a31b-a542f7dce6ff.png)

When I get the warning message at start I have to remember where the knob for each model should be or to move the knob and watch to disappear the warning. But You have to move the knob very slow because the right point is very narrow and easy to miss. In my opinion it should be a little wider, the right position to catch. It*s like a little puzzle 😀

**Comment by bsongis-frsky** [comment]
Fixed the bug part. The enhancement you propose seems a good idea
