### ISSUE TITLE
lua servo

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#2016]
Hi,
i'm trying to use the servo lua and i can't make it work. thanks

**Comment by Dsrenger** [comment]
GitHub is a development platform.

What should a developer do with your issue here?

Which steps are you doing? 
What is the transmitters behaviour? 
What is not working?

If you want a dev to look at your issue you should invest some effort...

**Comment by ronron84** [comment]
> GitHub is a development platform.
> I know, I know...
> What should a developer do with your issue here?
> "If there are any mistakes, please feel free to tell us!".The file is in the download section... so it can be interesting to put a working script in it ! or get rid of it
> Which steps are you doing? What is the transmitters behaviour? What is not working?
> i put it in in my x20 script sub directory and the file doesn't appear in the widget selection file, if you test the file you will see ! if i knew what's not working i won't ask...!
> If you want a dev to look at your issue you should invest some effort...
i already spent few hours to find out witch term or command have been changed/modify.
Did you try the script ? is it working for you ?
