### ISSUE TITLE
Where to save lua files in sd card

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#2017]

**Comment by kakashi2018** [comment]
I’m on ethos 1.4.0 x20hd. I have saved all folders inside lua to scripts folder inside sd card. But I don’t see ghost elrs or crossfire external module names in the list where we select external module. I can see twin lite module and all others though

**Comment by Target0815** [comment]
The directory for ELRS is e.g. \scripts\elrs. In there comes the main.lua [from this Github directory](https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua/elrs).

If you do this, ELRS will appear in the selection of external modules.

**Comment by kakashi2018** [comment]
I can see that all other lua files are accepted but not elrs and crossfire. It might be the 1.4.0 version that x20Hd shipped with is not suitable for elrs.

**Comment by Target0815** [comment]
X20HD? Doesn't it come with version 1.2.7? ELRS/Crossfire does not work there yet either.

In version 1.4.3, the X20HD should also be fully supported. Can only take a few days ...

**Comment by kakashi2018** [comment]
I got mine Yesterday, it is a new batch with minor changes. Hope we get an update to elrs quickly as I have installed elrs rx on all my quads

**Comment by mawzthefinn** [comment]
The scripts require 1.4.1 or later for the current ones on the Github.

**Comment by kakashi2018** [comment]
I was able to work it out using old lua of elrs uploaded first time in here. Now I have modified few things copying the new lua into old one and now my x20hd is running elrs module. Only thing missing is the telemtry. I don’t get bat voltage or adc4 values

**Comment by us9001** [comment]
The directory for ELRS is e.g. \scripts\elrs. In there comes the main.lua 
(https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua/elrs).
I am on Ethos 1.4.2. X20s show Type Express LRS/ Options Configure
When I press Configure.
ELRS Configuration got a blank page. Nothing happens. 
How do Ethos to show Config page.
Thanks

**Comment by us9001** [comment]
The directory for ELRS is e.g. \scripts\elrs. In there comes the main.lua 
(https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua/elrs).
I am on Ethos 1.4.2. X20s show Type Express LRS/ Options Configure
When I press Configure.
ELRS Configuration got a blank page. Nothing happens. 
How do Ethos to show Config page.
Thanks

**Comment by mawzthefinn** [comment]
Which module, what ELRS version loaded?

That fully populates for me with a HappyModel ES24TX Slim Pro on ELRS 3.0.0

**Comment by us9001** [comment]
> Which module, what ELRS version loaded?
> 
> That fully populates for me with a HappyModel ES24TX Slim Pro on ELRS 3.0.0

BetaFPV ELRS 915Mhz Nano RF Module
Thank you for quick reply

**Comment by magixfly** [comment]
have the same issue with nano crsf module -> Crossfire Configuration got a blank page. Nothing happens.

**Comment by mawzthefinn** [comment]
Please verify you have the latest version of the Lua in question. I know there have been updates since the original ELRS and Crossfire releases

**Comment by magixfly** [comment]
Hi! thanks for information. i forgot to inform, that my crsf module doenst fit very well into the x20(s) . so there was (is) a connection problem to the pins.  x18 - there is no problem, it fits very well and i can use the small crsf mount and the original antenna mount. in x20 there is no room for the antenna, i have to change position, because in original the antenna show direct to the 868 antenna from the x20

**Comment by mawzthefinn** [comment]
There's some known physical design issues with the TBS 'Nano' modules that cause issues on the X20 as well as the older X9 Lite. One such issue is interference with the handle on the X20, but also some TBS module cases exceed the width available and foul the sides of the modules slot on the X20 and X9 Lite.

**Comment by mawzthefinn** [comment]
@US9001 - what ELRS version is loaded on your module? The provided script is ELRS 3.0, a different script would be needed for v2.5.1 or earlier

**Comment by kakashi2018** [comment]
Its all good now. This issue can be closed
