### ISSUE TITLE
Elrs / crsf

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#2018]
Hi is it possible to add elrs configuration to crsf module as when I select elrs with my x20 I can configure and set crsf module and rx through elrs configurator 
But this is not present in crsf module selection under rf module

**Comment by Target0815** [comment]
Please ... CRSF is a protocol which is used by ELRS and Crossfire, both products. Your question will not be more understandable if you mix up the terms ...

For Crossfire, the main.lua is currently not complete. Take the main.lua from ELRS and change the init call at the very end to system.registerCrossfireModule(). Then also the Crossfire configuration runs with Ethos.
