### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#202]

**Comment by strgaltdel** [comment]
![2tu](https://user-images.githubusercontent.com/20392683/117641965-12db5f00-b187-11eb-879d-d706c90564bc.png)

**Comment by Hobby4life** [comment]
+1

**Comment by DaySpeed955i** [comment]
Fantastic!

**Comment by loetefix** [comment]
+1

**Comment by marevalor** [comment]
+1

**Comment by CliffEvans** [comment]
Is Lua active on X20 - X20s yet?
Cheers

**Comment by loetefix** [comment]
I hope the LUA will be as good as well as in OTX with possibilities to create mixers, change servo limits, create flightmode ....... So we can create own model wizards.

**Comment by tysonfromcanada** [comment]
This is the only thing preventing me from upgrading to X20, as I use spirit flybarless flight controllers that utilize lua for configuration

**Comment by loetefix** [comment]
Same here
