### ISSUE TITLE
Ethos 1.4.2 still sensor conflict

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2020]
Ethos 1.4.2, Archer R6 and Unilog 2 from sm-modellbau, I am still getting the message sensor conflict and also sensor lost. Seems still the same problem as reported in earlier Ethos versions.

**Comment by Wolepo** [comment]
This is probably not due to Ethos, but to the FW of UniLog. There is already another FW for UniSens-E and the message no longer appears.
