### ISSUE TITLE
Suite 1.4.0 - updated HE json file

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2021]
[he.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9878774/he.zip)

attached updated suite HE file for 1.4.0
please use it.

**Comment by bsongis-frsky** [comment]
I have taken your file, but I think what you have done for LatestRelease is not good:

![image](https://user-images.githubusercontent.com/50834778/198517177-e2addbe3-badd-43ab-b8bd-5ff1ab5183f5.png)

**Comment by i3dm** [comment]
> I have taken your file, but I think what you have done for LatestRelease is not good:
> 
> ![image](https://user-images.githubusercontent.com/50834778/198517177-e2addbe3-badd-43ab-b8bd-5ff1ab5183f5.png)

why is it not good? looks fine to me and hasnt changed from last one.
