### ISSUE TITLE
TD Receivers 900MHZ Telemetry interference

### ISSUE THREAD

**Issue by arshish1612** [FrSkyRC/ETHOS-Feedback-Community#2023]
The 900MHZ Telemetry is causing servo interference and Jitter. This seems to be a known issue and I was advised on rcGroups to keep the Antennae as far away from the Servo and servo wires. As you can see from the picture even with the servo and Antanae completely separated and stretched apart, the servo twitching persists.

Can we get a feature to selectively enable / disable Telemetry for 2.4Ghz & 900Mhz? Alternatively, what is the solution for this the issue persists with Futaba, Hitech, Emax, Turnigy & Hobbybking Servos.

NOTE: Keep Speakers and Audio ON for the Attached Video

![WhatsApp Image 2022-10-28 at 1 45 04 AM](https://user-images.githubusercontent.com/8477844/198392429-3efc8503-0565-45ff-a10c-577005b6972d.jpeg)

https://user-images.githubusercontent.com/8477844/198393876-8e59ebff-2771-4a67-a3b5-5c881567e35f.mp4

**Comment by andika207** [comment]
> The 900MHZ Telemetry is causing servo interference and Jitter.
>Strangely during my testing even with Telemetry OFF I get a very minor twitch occasionally

Yes but No...

**Comment by arshish1612** [comment]
I've been testing this for the last hour now. Every time I put the telemetry ON the issue shows up again

**Comment by andika207** [comment]
> Every time I put the telemetry ON the issue shows up again

Are you performing the tests outddoor away from internet routers or other WiFi devices ?
If you can't disable telemetry on the 900 Mhz side the only possible solution by now would be to swap the T-antenna

**Comment by arshish1612** [comment]
> Keep the antenna far from each other. Specially the T antenna for 900MHz

I've already tried that. Infact if you look at the photograph ive attached, the antennae cannot be kept any further apart.

**Comment by arshish1612** [comment]
> > Every time I put the telemetry ON the issue shows up again
> 
> Are you performing the tests outddoor away from internet routers or other WiFi devices ? If you can't disable telemetry on the 900 Mhz side the only possible solution by now would be to swap the T-antenna

No the test is at home, not outside but there is very little wifi interference here. If I were to swap the T- antenna what would I have to change it to? is there something else I can use?

I dropped this issue here hoping the disabling of 900Mhz Telemetry independently instead of complete telemetry would be taken up as an enhancement

**Comment by andika207** [comment]
> If I were to swap the T- antenna what would I have to change it to? is there something else I can use?

if I only knew the answer... hope it helps https://oscarliang.com/mini-immortal-antenna/
