### ISSUE TITLE
Include Physical and Application IDs in Sensor List

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#2025]
Hi,
when ETHOS reports a sensor conflict, it is not always obvious which sensor pair causes this. Depending on the number of sensors, and which sensors are used, it can be a lengthy process to find that out. It would be a great help if the sensor list in the telemetry menu did include the Physical and Application IDs for all sensors shown. NB that this information is already displayed in the menu containing the details for a particular sensor.
It would be perfect if the conflicting sensors could be highlighted.

**Comment by Kreisflieger** [comment]
This would be a very user friendly enhancement !

**Comment by ltdorn** [comment]
Concur!  this Sensor conflict with my RB30 and the Swiwin turbine ECU is killling me.... I think its the Vspeed sensor causing conflicts and i cant change either one in any tool, LUA, STK, or the Airlink....

**Comment by Hartinger** [comment]
So my comment is that it is still a reasonable request to include the Physical and Application IDs in the list of sensors, not just in the details for each sensor.

**Comment by i3dm** [comment]
Good idea
