### ISSUE TITLE
mode buttons wont set rates

### ISSUE THREAD

**Issue by drummaker** [FrSkyRC/ETHOS-Feedback-Community#2026]
I never use modes because I want all trims to stay in all rates 
so 
I thought it might be cool to assign three of the mode buttons to switch between rates in the mix.

this just doesn't work at all.... 

Why?

**Comment by mawzthefinn** [comment]
You can disable per-flight mode trims in the Trims menu, then use flight modes.

You should be able to select rates  with the Function Switches (mode buttons), they are labelled FSW in the menus. I’ll test when I  get home.

**Comment by mawzthefinn** [comment]
Finally managed to check this, Mode buttons (Function Switches as they are called in the UI) are fully supported for Weight/rates selection already.

**Comment by drummaker** [comment]
ok I did find out about the trim per flight mode thanks

the program indeed will let you assign mode buttons, but in my environment though I can assign them and the proper rate highlights, the control surfaces don't operate properly.   don't look any closer for now. I will  set this up again and video what is going on.   if I can repeat.   age is catching up to me and sometimes it seems like I was tripping on occasion.  it seems these
buttons are convenient but building 3 mixes is inconvenient if this requires 3 modes to do,, 
putting all rates in the same mix is one of the best thing u did

**Comment by mawzthefinn** [comment]
Any more info on your issue here?

**Comment by drummaker** [comment]
I am afraid I forgot as I set this up using multiple modes, and f ound I like my old switch better

**Comment by mawzthefinn** [comment]
Are we OK to close then?

**Comment by drummaker** [comment]
I will recheck this yet today

**Comment by drummaker** [comment]
Yes this works fine.  I don't know what happened the first time

**Comment by mawzthefinn** [comment]
Glad to hear it’s working correctly, I’ll close off the issue as completed
