### ISSUE TITLE
Label for VAR Mixer weights / sort lines

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2027]
It would be great to add a label to each weight. I use VAR for flightmodes for S6R or Betaflight and a label would be great to remember what each value was

**Comment by jasc76** [comment]
And a possibility to sort weight lines would be great. The highest line has prio, so when having like 5 flight modes some need to have prio over others and if you mix it up, its cumbersome

**Comment by mawzthefinn** [comment]
Agreed on both.

Labels make things clearer, and any case where there is a priority function should have re-ordering supported

**Comment by jasc76** [comment]
I still would find it useful. Like I said, its a good thing to use for FLightmodes in INAV or Betaflight and it would help to to able to document what each value represents

**Comment by jasc76** [comment]
I would appreciate Ethos developers close feature suggestions they are not planning to implement and not the bot. Like this it just gets deleted and forgotten without a decision

**Comment by mawzthefinn** [comment]
All of the issues closed as stale are updated 5 days in advance to allow you to flag an issue as still relevant.

**Comment by jasc76** [comment]
Still useful 🤷🏼‍♂️
