### ISSUE TITLE
Simulator - support needed for different tx's!

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2028]
Ethos 1.4.1

In order to develop Lua scripts and templates, it's essential that the Ethos simulator support _all_ transmitters. Aside from the obvious reasons (different controls and screen resolutions), it's also useful to see what breaks when moving templates between tx's, and also for debugging issues for users who don't have the X20.

Any chance, then, that support can be added for the Twin, XE, X18 - and also new tx's as they are released?

**Comment by Storchy1** [comment]
Is there a chance to get a Simulator for XE(S)
Thanks a lot for your work

**Comment by bsongis-frsky** [comment]
XES Simulator is online
