### ISSUE TITLE
LUA to determine all sensor IDs

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#2029]
Hello Bertrand,
is it possible to read the colliding sensors via LUA,
I already have a script to read out all sensors, but it cannot be used to determine the colliding sensors because they cannot be. contained/read.

Greetings Benno
[main.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9895775/main.txt)

**Comment by bsongis-frsky** [comment]
I think it is possible to do so, you have to receive all S.Port frames and compare with the existing sensors. If you have 2 sensors with a different PhysID and the same AppID then you will find the colliding sensors. There are a few exceptions with RSSI, VFR and so.

**Comment by Benno00** [comment]
Hello Bertrand,

 

I created a LUA that reads all available sensors into a table and compares them with the previous table. If there is a sensor with the same APPID and a different PHSYID, it would write out the displays and as a file. Unfortunately, it seems that when the message comes up, "Sensor conflict", this sensor cannot be queried in the system.

I read in all sensors as follows, but the sensor is not found.

 

                for i=0, 65535,1 do

                               so = system.getSource({category=CATEGORY_TELEMETRY, appId=i})

                               if so~=nil then

                                               source = system.getSource({name=so:name()})

                                               if source~=nil then

                                                               zahl= format_num(source:value(),2)

                                                               -- remove Exp.

                                                               if string.find(zahl,"e")~=nil then

                                                                               zahl=string.sub(zahl,1,string.find(zahl,"%.")+2)

                                                               end

                                                               -- change dezimalpoint to komma

                                                               zahl=string.gsub(zahl, "%.", ",")

                                                               

                                                               tx=tx..source:name().. ";"..source:module()..";" .. source:band() .. ";" .. string.format("%#x", source:appId()) .. ";" .. string.format("%#x", source:physId())..";"..zahl.."\n"

                                                               zz=zz+1

                                                               sensor_list[zz] = { name = source:name(), appid = source:appId(), physid= source:physId(),}

                                                               

                                                               -- Aktivate a konflikt This work in Simulator

                                                               --if zz==5 then

                                                               --            sensor_list[zz].appid=sensor_list[4].appid

                                                               --            sensor_list[zz].physid=sensor_list[4].physid+1

                                                               --            print("sensor:4"..sensor_list[4].name.."  "..sensor_list[4].appid.."  "..sensor_list[4].physid)

                                                               --            print("sensor:5"..sensor_list[5].name.."  "..sensor_list[5].appid.."  "..sensor_list[5].physid)

                                                               --end

                                               end

                               end

                end        

Mit freundliche Grüßen,
Benno Jurisch

Benno Jurisch
Siedlung 5, 27624 Geestland
Telefon: +49 (0) 4708 707
Mobil: +49 (0) 152 337 76 727
***@***.***

 

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Mittwoch, 2. November 2022 10:17
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno00 ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] LUA to determine all sensor IDs (Issue #2029)

 

I think it is possible to do so, you have to receive all S.Port frames and compare with the existing sensors. If you have 2 sensors with a different PhysID and the same AppID then you will find the colliding sensors. There are a few exceptions with RSSI, VFR and so.
