### ISSUE TITLE
SWR Warnings when SWR is 0

### ISSUE THREAD

**Issue by Sigee3** [FrSkyRC/ETHOS-Feedback-Community#203]
I have found an issue with the swr telemetry.
It would seem that any model with swr available on the telemetry screen gives an swr warning when switching to that model.This happens no matter what the swr reading or what antenna is selected,although it only happens 90% of the time.Any model that lacks swr when sensors are discovered will not give an swr warning.Any model that has the swr sensor deleted also doesn't give a warning

**Comment by bsongis-frsky** [comment]
If we receive nothing, we will get 0 and 0 => no warning
Needs to be investigated more, it's not normal

**Comment by Sigee3** [comment]
I am still getting SWR warnings after updating to 1.0.6.
If swr is on the telemetry list I get the warning even if swr shows as 0.
If swr is not on the telemetry list I get no warnings even if swr is high.

**Comment by Sigee3** [comment]
Still getting this with the 2.1.7 update

**Comment by bsongis-frsky** [comment]
You will need Ethos 1.0.7 once released

**Comment by Sigee3** [comment]
Ok thank you

**Comment by Sigee3** [comment]
Fixed on 1.0.7 thank you.
