### ISSUE TITLE
Lost connection to my R9M lite module

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#2030]
Just updated my X20 to 1.4.2 & immediately lost the connection to my R9M Lite Module plugged into the back of my X20 transmitter.
When i select the R9M lite access option on my external module, i get "waiting for module" then no connection 
worked absolutely fine till last evening, till before i updated the radio. 
The Module lights up red as normal, but no connection
Wonder whats going on?

**Comment by Target0815** [comment]
I can confirm this. When pressing "Set" first "Waiting for module..." and then "No response from module!

Ethos 1.4.2 / Tandem X18S / R9M Lite with current ACCESS firmware.

**Comment by ravikoth** [comment]
Yep, Problem remains as is.
Have tried Re-Updating the firmware on the module but it has made no difference.
Looks to me like an issue with the newest update. 

> I can confirm this. When pressing "Set" first "Waiting for module..." and then "No response from module!
> 
> Ethos 1.4.2 / Tandem X18S / R9M Lite with current ACCESS firmware.

**Comment by bsongis-frsky** [comment]
Do you have channels? Telemetry?

**Comment by ravikoth** [comment]
Hello Bertrand,

The recvr bind/registration option is inaccessible.
When i press “settings “ the screen says module not reachable.

i have attached screenshots here.
Did rollback the firmware & everything was working normally. The R9M lite module worked perfectly & i was able to bind to the 900 recvrs as normal. Unfortunately i couldn’t reload my existing models back on the System. (Is there a way of doing this) 

Something’s not right with the current firmware, it doesnt allow the R9M lite module to be installed. 

Hope this is resolved soon. i have a flying session i need the X20 for over the weekend.

thanks 
![1717EEF6-2C35-41B7-BE57-41A0F8CAAB78](https://user-images.githubusercontent.com/87301909/199152067-e5f7b0d0-f050-4375-8c34-5a2b0e64905d.jpeg)
![755BC317-AE4A-474B-99A8-AE9E814CAE44](https://user-images.githubusercontent.com/87301909/199152071-6652e801-3dea-4ffd-902b-ee3d41d82e9f.jpeg)
![0453E811-BC6B-40E6-806F-296273B2B60B](https://user-images.githubusercontent.com/87301909/199152072-1ea54f57-de32-42f1-b83f-6117d21dbc42.jpeg)
![FC30B20C-D50F-4E87-942C-AF88BE95D64C](https://user-images.githubusercontent.com/87301909/199152076-3b6a91d7-860b-4d70-9572-626aab9264cc.jpeg)

**Comment by ravikoth** [comment]
> Do you have channels? Telemetry?

Hi,
is there any chance this will be resolved  soon.
i am stuck currently.

The only version which works is the 13.3, but when i roll back to 13.3 i cannot restore my saved models by ethos suite or by manually pasting the models file onto my sd card.
Needless to say i’m going to be waiting for the dust to settle on any new updates.
this was a truly unexpected bump on the road.

**Comment by bsongis-frsky** [comment]
Bug found, it was just a typo ...

**Comment by ravikoth** [comment]
Great, When will it be available as a download?
________________________________
