### ISSUE TITLE
Trainer function - no wireless selection possible

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2031]
Hi,

in the trainer menu you can not select wireless (disabled).

Ethos 1.4.2 / Tandem X18S

**Comment by Target0815** [comment]
Under System / Wireless wireless must first be switched on, so that you can activate it in the trainer menu. IMHO this is not user friendly. If the option could be selected in the trainer menu, it would be more logical.

**Comment by drummaker** [comment]
Ditto
