### ISSUE TITLE
I would like clarification 

### ISSUE THREAD

**Issue by drummaker** [FrSkyRC/ETHOS-Feedback-Community#2032]
Why does td mode not behave like a 2.4 and a 900 receiver.  I thought I would be able to use   my x 10 to connect to the 2.4 part of my td receiver.  Not clear on why this won't work  is b it still using access as a link protocol?

**Comment by MIKE-DAILEY** [comment]
TD Mode is unique to itself in the way it uses the 2.4 and 900m RF paths to reduce latency and increase range.  The mode cannot be replicated without the TD ISRM and the TD receivers can only be used with the TD ISRM.

**Comment by drummaker** [comment]
Thanks for the response.  My background is network communications,  so protocols are my field of expertise
 For me your answer is restating the obvious, this is not a jab at you, it is just that my expected level of understanding than most.  

I find it frusting that it is so difficult to gain real info on all of this rc link stuff.  When I was working my job, if a vendor was using a proprietary protocol and I asked they would put me in touch with an engineer who would break it down to bit level for me.
I cannot get real info how they negotiate 
frequency   hopping etc.    Worse yet I have long been trying to get info on what info can be put on a SBUS link.   Is there regular error checking like crc.  Or is there a way to indicatedistant  end LOS? 

Sorry about the rant I really do understand what an amazing thing you guys are doing,

**Comment by MIKE-DAILEY** [comment]
Because of the way the RC world is with technology nowadays FrSky has to be careful about what they share about their IP, but they do have a formal program for mutual collaboration with other manufactures and individuals that would like to make their product integrate with the ETHOS ecosystem.  Read about it here https://ethos.frsky-rc.com/
