### ISSUE TITLE
Order of calling storage.read() and write() is significant

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2033]
1.4.1, X20

Not sure if this is a bug or if I've misunderstood. Best illustrated with this code fragment:
```
local function writewidget (widget)
  storage.write ('A', widget.A)
  storage.write ('B', widget.B)
end

local function readwidget (widget)
  widget.A = storage.read ('A')
  widget.B = storage.read ('B')
end
```
The A and B values are correctly assigned as long as the order is the same in read() and write().

However, if the order of assignments is changed in read() :
```
  widget.B = storage.read ('B')
  widget.A = storage.read ('A')
```
... then widget.A = 'B' and widget.B = 'A'

I assumed that each value is identified by the _label_ parameter, in which case the order would not be significant. Have I missed something or is this a bug? Thanks!

**Comment by bsongis-frsky** [comment]
Yes it is significant with our current design. The label is completely ignored today, but it will be useful in next releases when we will use the JSON format to store them
