### ISSUE TITLE
not supporting the fas-100 sensor.

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2036]
I just bought an x20s and am porting my planes over from an x10s open-tx.  I have a lot of the fas-100 ( the one that plugs into the altimeter) sensors. I really need it to support this sensor like open-tx and edge-tx did. A lot of work and cost to replace all of the old sensors. I probably have 10 of them.

**Comment by bsongis-frsky** [comment]
It should work out of the box, it is a S.Port sensor, no?

**Comment by williajgr** [comment]
Kind of.  It plugs into the altitude sensor and that plugs into the sport.  It works fine on my open tx radios and even the older fros. Sent from my iPhoneOn Nov 2, 2022, at 5:11 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
It should work out of the box, it is a S.Port sensor, no?

**Comment by mawzthefinn** [comment]
It's an old D series sensor. The S.Port vario's could act as a D series to S.Port bridge with certain sensors.

**Comment by williajgr** [comment]
Is there any chance that this issue will get fixed?

**Comment by bsongis-frsky** [comment]
I will do my possible. But I cannot promise it will work until I have tried myself. I have found an old FAS-100 (with DATA IN and DATA OUT), and also an old Variometer Sensor (with S.PORT, Data Out and Data In). 

Would you explain how you wired everything? I will try to replicate it. I didn't know that the Variometer would possibly act as a bridge!

**Comment by williajgr** [comment]
Here is the setup. The fas100 has to have power to work.      Thanks for the help         JoeSent from my iPhoneOn Nov 8, 2022, at 5:05 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
I will do my possible. But I cannot promise it will work until I have tried myself. I have found an old FAS-100 (with DATA IN and DATA OUT), and also an old Variometer Sensor (with S.PORT, Data Out and Data In).
Would you explain how you wired everything? I will try to replicate it. I didn't know that the Variometer would possibly act as a bridge!

**Comment by mawzthefinn** [comment]
It's in the manual for the old Vario

https://www.frsky-rc.com/wp-content/uploads/2017/07/Manual/Variometer%20Sensor.pdf

Essentially you connect the FAS to the Data In port of the Vario, as if it was a Sensor Hub

**Comment by bsongis-frsky** [comment]
Thanks @mawzthefinn I have succeed to connect mine and I receive telemetry. Now implementing the old D protocol into Ethos.

**Comment by jasc76** [comment]
Today I flew a G-RX8 (access) with GPS and FAS-100. Worked fine as I could tell

**Comment by mawzthefinn** [comment]
This should be corrected in 1.4.3 @williajgr 

Please confirm if it is working for you

**Comment by williajgr** [comment]
Sorry not working in either ACCST or access mode. Bet he has Fas-100sSent from my iPhoneOn Nov 13, 2022, at 8:24 PM, mawzthefinn ***@***.***> wrote:﻿
This should be corrected in 1.4.3 @williajgr
Please confirm if it is working for you

**Comment by bsongis-frsky** [comment]
What is your receiver @williajgr ?

**Comment by williajgr** [comment]
Tried it with 2 receivers Access R10proRXR8 ACCSTBoth worked on my open-tx Horus x10sSent from my iPhoneOn Nov 14, 2022, at 12:52 PM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
What is your receiver @williajgr ?

**Comment by williajgr** [comment]
I have a question.  Trying to set up one of my deltas on ethos.  I need to have offsets to match my open-tx setup.  There are no offsets if one uses elevator as the mix.  If one uses center/sub trim in outputs one doesn’t get symmetrical throws.  If I use free-mix and trim on the elevator I can get it to work, but that is very complicated.  Figure I am doing something wrong.  Can you straighten me out.   Thanks          JoeSent from my iPhoneOn Nov 14, 2022, at 4:06 PM, George Williams ***@***.***> wrote:﻿Tried it with 2 receivers Access R10proRXR8 ACCSTBoth worked on my open-tx Horus x10sSent from my iPhoneOn Nov 14, 2022, at 12:52 PM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
What is your receiver @williajgr ?

**Comment by williajgr** [comment]
i loaded up the new release with the ethos suite.  The FAS-100 still doesn't work. hope this can be fixed

**Comment by williajgr** [comment]
any progress on this issue ? would really like it to work

**Comment by bsongis-frsky** [comment]
Tonight I have tested X20 with internal module in ACCST mode, bound to X4R.
The X4R is connected by S.Port with the FrSky Vario which is a proxy to FAS-100
Everything works as expected

**Comment by bsongis-frsky** [comment]
I am using 1.4.5

**Comment by williajgr** [comment]
It does read the sensor now but gets the wrong value
25input  12.6 volt  reading               1.1 amp input      1.8 reading
20           10.5                                    2.1                        2.8            
15             7.9
12             6.3

get the correct readings on my open-tx transmitter

**Comment by bsongis-frsky** [comment]
Oh shame, I have done tests with a FAS-100 which is a prototype and has different resistor values!
I forgot to remove the ifdef!

![image](https://user-images.githubusercontent.com/50834778/210136473-377544e8-08e6-47f9-9a04-a7ded795ebda.png)
