### ISSUE TITLE
Timers pause 

### ISSUE THREAD

**Issue by janekx** [FrSkyRC/ETHOS-Feedback-Community#2039]
Enhancement 
Sometimes  user needs make setup percentage throttle timer and need to pause it but work with throttle. 
Add pause switch to timers?

**Comment by mawzthefinn** [comment]
That's a good idea.

Would make sense to separate the Active Condition for the timers from the Source condition, so a timer could be enabled/disabled while still using one of the canned sources (or an alternate one like throttle channel)

**Comment by bsongis-frsky** [comment]
We have introduced a Pause Condition. But I wonder if it doesn't complexify the Timer UI for nothing and I prefer @mawzthefinn proposal which just introduces a more powerful method for counting, depending on a Source (not only the Throttle Stick position):

1) We keep the "Active Condition"
2) We introduce a "Stop when inactive" choice (it will replace the Throttle Trigger)
3) We introduce a "Counting Source", which could be the Throttle Stick or even the Throttle Channel

Would if fix your original issue @janekx ?

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/236607675-b6b1abe6-c736-4345-b686-7727621d25da.png)
