### ISSUE TITLE
lose control while Sensor lost alarm in 1.0.4

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#204]
Last weekend i crashed my SAB Fireball with 1.0.4. Suddenly i lose control of the Helicopter.

The Problem ist that sometimes my TX say : Sensor lost. ok that is not a big deal. But in Ethos there seems to be a critical bug that freeze the commands to the HF in this moment. How can it be that i lose control when there is a telemetry Problem?
In 1.0.5 it seems to be ok. But i think it is better to show the problem in a videolink

https://youtu.be/7L2ghj78g_Q

**Comment by loetefix** [comment]
Then you better take the v1.0.4 away from download section


⁣BlueMail for Android herunterladen ​

**Comment by bsongis-frsky** [comment]
Done

**Comment by loetefix** [comment]
Thanks
