### ISSUE TITLE
lua: rotary right/left completely useless for widget application

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2040]
Within a Lua widget, it is practically impossible to use the "Rotary_Right/Left" functionality:

For example, if you want to change values inside a widget & the widget is in focus, its event handler can detect and evaluate encoder events.
But it seems to be completely useless because there is a prioritised ethos event handler that triggers on appropriate encoder events and sets focus on the previous or next widget with the second closest encoder event.
This invalidates the "local" event handler of the previously active widget.
If you rotate more, the "widget focus" will fly through the configured widgets (across multiple pages, depending on the individual widget/page layout),
but you will never be able to use the rotate input for anything within a particular widget. 
(Unless your widget is the only one configured for the entire model).

I suspect that "scrolling" through the widgets using encoder rotation may be necessary to navigate in a non-touch environment.
On the other hand, changing values or navigating within a widget using the encoder would be a typical application.

Therefore, I would suggest introducing a Lua method so that Lua developers can disable/enable the default ethos handling if they need the rotation functionality in their script.

regards

Udo

**Comment by bsongis-frsky** [comment]
It would be easier to introduce an EDIT mode, where all events are sent to the widget:
1) this EDIT mode would be reached when the user presses [Enter] or [Enter Long] on the widget which has the focus, provided this widget allows it in `registerWidget`
2) this EDIT mode would be stopped on an event which is common to the whole system: [Exit] or [Exit Long]
If we decide to use [Enter Long] + [Exit Long], then events like [Enter] and [Exit] can be passed normally.

**Comment by bsongis-frsky** [comment]
About the rotary encoder events, the OP is right, they are completely useless and they should not be passed in the current implementation.

**Comment by bsongis-frsky** [comment]
This one is working since 1.5.0!
