### ISSUE TITLE
ETHOS Stable Version for the General Public

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#2042]
Not sure where else to post this so posted it here...

Hello, a few have commented to me and some on the RCGROUPS forum that there should be a stable final version for the general public and I think that this is great suggestion. The general public are not the ones religiously following this site or forums or updating monthly so they just want an OS version which they can install, fly and forget. Understanding this community adds value to ETHOS within the areas of improvements, general enhancements, new support and bug fixes but at what point can someone install firmware version "X.X.X" and fly safely without worry or concern? It goes without saying that not upgrading doesn't provide them with new features but these users aren't wanting the latest or greatest and just want radio control stability, functionality and telemetry. These users also aren't aware of GitHub or the like and simply visit the manufacturer website. Maybe establish what is the "stable" version and have that posted on the FrSky Website.

This is an area that warrants serious consideration.

**Comment by jasc76** [comment]
just stick to what is shipped ....
But whatever is done, please dont slow down development.

**Comment by carlogianneschi** [comment]
If possible a LTR (long time release) is a good idea

**Comment by Target0815** [comment]
Actually, you can generally use the latest version of the previous development branch.  We currently have 1.4.2, so the last previous version would be 1.3.3.

LTR versions are something completely different. Here a version is "frozen" and only provided with security updates for a longer period of time. This makes no sense for a transmitter OS and is more useful for Linux derivatives or TYPO3 or similar.

**Comment by mawzthefinn** [comment]
I think what might work is doing what Target0815 suggests, but ensuring that version is what is posted on the FrSky-rc.com download pages (right now I think they have 1.2.7 posted). 

That would keep a relatively stable version available and a simple place to get it.

That said, there should be a matching Latest/Stable selection in ETHOS Suite as well, so users know what to flash (that could be a Suite setting). Stable gives last release on previous branch, Latest gives current latest release.

**Comment by pld74** [comment]
That's what I am saying, use the FrSky/ETHOS Suite as the place holder for the Stable version.

**Comment by pstasek** [comment]
I think it's not necessary. Just stick to the general public rule "don't touch the running machine" unless you run into an issue such as a missing feature or something that doesn't work. Unlike computer operating systems, Ethos is a single piece of software, so introducing forking may only bring confusion. Ethos Suite is on the right track being simple to use and letting the user decide according to the changelog if the version is worth updating or not.
