### ISSUE TITLE
Possible Issue with Timers

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#2043]
One of the items to deal with on my model setup was the Motor run timer and flight timer. The timers start by using the “Throttle trigger” option. On this model I realised that the timers did not start until I opened the throttle to 100%. Anything below 100% throttle will not activate the timers.
The motor run timer is used to automatically disable the motor after 30s.  Other logic is used to disable the motor if a preset height has been reached before 30s.
I cloned the model and started removing all the mixes and logic switches. (Thinking this problem was down to something I had done in the programming). Even with the minimum of mixes and no LSWs the throttle trigger will only activate the timers at 100% throttle.
I am using the left rotary slider as the throttle and the throttle stick activates the brakes.
[joy.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9935101/joy.bin.zip)

**Comment by Wolepo** [comment]
And the use of the slider is the mistake. The release is not through the throttle channel (that would be correct), but through the throttle stick. Bertrand should please think about this problem.

**Comment by kramgrand** [comment]
Not sure about that, as it is using the throttle channel mix that has all the throttle bits like throttle Hold, Sticky, etc.  But with the source set to the rotary slider instead of the stick. Also, all my other E Gliders have the same throttle trigger to start the timers.  This is the first glider I have setup since updating to Ethos 1.4.2.   
BTW I setup a new e-glider as a test, using the slider as the throttle source and throttle trigger for the timer and it worked.    At the moment, It only appears to be connected with this particular glider file. 
I have also copied the .bin file onto my other X20S.   The issue remained the same on that one.

**Comment by kramgrand** [comment]
Hi, Please find attached test22.bin. Throttle trigger timers work as soon as you move the left slider.
test22.bin.zip

**Comment by kramgrand** [comment]
Hi, Problem found!  It was a setting in the CHECKLIST that caused it.   
I had the throttle check set at < 97%.  Anything other than "No Check"  causes a problem with triggering the timers.    Shame it took me to totally create the model program again to find it.  Appears there is interaction with the throttle stick if the configured throttle control is the slider.
