### ISSUE TITLE
NAND Memory size X18 (S), Twin X-Lite (S), XE

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2046]
Hi,

not directly an issue but a question:

My X18S is advertised with a NAND memory size of "4G". Occasionally it also says that it is 512 MB (MByte). "4G" rather suggests that the transmitter should have 4 GB (GBytes) of NAND memory, which is incorrect.

However, when I look at the storage on the drive, there is only a good 370 MBytes total. With a memory expansion of 512 MByte and a FAT file system, I find this a bit strange, because I would rather expect 480-500 MByte here. 

Is the size of the NAND memory correct for the following transmitters?
X18 - 128 MByte
X18S - 512 MByte
Twin X-Lite - 128 MByte
Twin X-Lite S - 512 MByte
XE - 1024 MByte

Thanks in advance for more information ...

**Comment by Adelaxie** [comment]
>Is the size of the NAND memory correct for the following transmitters?
X18 - 128 MByte
X18S - 512 MByte
Twin X-Lite - 128 MByte
Twin X-Lite S - 512 MByte
XE - 1024 MByte

YES

**Comment by bsongis-frsky** [comment]
4GB seems rather 4 giga bits, not 4 giga bytes

**Comment by Adelaxie** [comment]
>My X18S is advertised with a NAND memory size of "4G". Occasionally it also says that it is 512 MB (MByte). "4G" rather suggests that the transmitter should have 4 GB (GBytes) of NAND memory, which is incorrect.

Modified, thanks.

**Comment by Target0815** [comment]
> However, when I look at the storage on the drive, there is only a good 370 MBytes total. With a memory expansion of 512 MByte and a FAT file system, I find this a bit strange, because I would rather expect 480-500 MByte here.

Is there any (technical information) on this yet? The NAND drives only have 75% of the gross capacity available as net. However, a (old) USB stick with comparable capacity has around 90% with a FAT16 file system.

NAND drives are already checked for defective memory locations during manufacture and these are marked accordingly by the manufacturer. However, the gross capacity is achieved in any case, otherwise it would be scrap. 

I now wonder why only a total of about 370-380 MBytes are available in an X18S, but it should be about 460 MBytes ...
