### ISSUE TITLE
Lua: make gyro available as source

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2049]
Hi,

based on the given lua documentation i wasn't able to retrieve gyro values from X20s  "directly"

tried following, based on menue syntax / opentx naming / "a shot in the dark",
but nothing worked

```
	local val1	= system.getSource({name="Gyro X Axis"}):value()
	local val2	= system.getSource({name="gyrx"}):value()
	local val3	= system.getSource({category=CATEGORY_GYRO, member = 1}):value()

```
a workaround by using channels as a source may work, but would appreciate more direct way

thanks in advance & regards

Udo

**Comment by bsongis-frsky** [comment]
Constant `CATEGORY_GYRO` added.
In the meantime you could use `system.getSource({category=17, member = 1}):value()`

**Comment by strgaltdel** [comment]
Hi Bertrand,

thanks a lot for this exceptional service,
even on a sunday !

category=17 works  ((-:

thanks & regards

Udo
