### ISSUE TITLE
R6, R9mini and Vario -> Sensor Conflict and wrong Log Data

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2050]
I have configured an Archer R6 with an R9 mini for redundancy and a Frsky vario adv as sensor.
X20 with Ethos 1.4.3, receivers and vario run the actual firmware.
R9 mini s-bus out -> Archer R6 s-bus in, s.port all connected.

I get every 2-4 min. the message _**Sensor conflict**_ and also sometimes the message _**Sensor Lost**_

The logfile shows completely wrong data, see attached screenshots

![Redundancy Telemetry](https://user-images.githubusercontent.com/116186946/200159692-2b62f02e-7f9e-448d-9160-c5a24133e72d.jpg)

![screenshot-2022-11-05-78398](https://user-images.githubusercontent.com/116186946/200159778-aea5cb5e-658c-41df-bc64-42f603bb0281.jpg)

**Comment by Dsrenger** [comment]
Regarding the wrong data in the logfile.

Seems like the file is comma separated.

The issue is the RSSI 2,4ghz(db)

It would be in one column but as it's comma separated it gets imported into 2 column. Therefore everything else gets moved be 1 column.

To test, you could modify the cab data.
Replace the 2,4 by 24 or 2.4

Then the Log should look good.

**Comment by mawzthefinn** [comment]
Looks like a localization issue. Logs should use the US-style 2.4 instead of the EU-style 2,4 to avoid conflicts with the separator on a CSV file.

**Comment by glipski50** [comment]
@ Dsrenger: changed 2,4 to 2.4, works fine
@ mawzthefinn:  this is the original logfile as it is created on the X20. Where and which setting would I have to change for the US notation. In General Setting I changed language, keyboard and audio to English but the logfiles that I created after the change still shows 2,4 GHz.

The column with the header 2,4 GHz is only created when beside the 2.4 GHz receiver also a 900 MHz is used. With only 2.4 GHz receivers no problem. For me it looks like a bug of the localization.

**Comment by mawzthefinn** [comment]
@glipski50 I think Bertrand will need to make the change, not you. I suspect it's an untested localization issue in ETHOS not a setting on your part.

**Comment by glipski50** [comment]
Thanks.

I hope he also looks into the first topic I mentioned above. Sensor Conflict message in a redundancy configuration with 2.4 GHz and 900 MHz receiver.

**Comment by glipski50** [comment]
Here are two log files. The version ....corrected.csv has the correct notation 2.4 GHz in the header.

Configuration as mentioned above
I have configured an Archer R6 with an R9 mini for redundancy and a Frsky vario adv as sensor.
X20 with Ethos 1.4.3, receivers and vario run the actual firmware.
R9 mini s-bus out -> Archer R6 s-bus in, s.port all connected.


[Archiv.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9950270/Archiv.zip)

**Comment by WismyYao** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1827

**Comment by EngelMT** [comment]
Only for Info. German localization is my part. So my issue. Yesterday I was in contact with Bertrand. He corrected it for the next update.

**Comment by bsongis-frsky** [comment]
> s.port all connected

Do you connect the 2 receiver sport lines together? Is it explained somewhere in the documentation? I wonder how it could work.

**Comment by glipski50** [comment]
Yes, 2 receiver s.port and vario s.port

![IMG_0851 (1)](https://user-images.githubusercontent.com/116186946/200509420-5806cc07-74f3-4bde-9d36-2427ee53d204.jpeg)

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi3qcnljp77AhVgQvEDHVmDBjgQFnoECDQQAQ&url=https%3A%2F%2Fwww.frsky-rc.com%2Ffrsky-advanced-communication-control-elevated-spread-spectrum-access-protocol-release%2F&usg=AOvVaw1v7CW_u2yZPsb8UPfbBg_t

**Comment by bsongis-frsky** [comment]
Right, but this is for receivers on the same band! I am not sure you are allowed to mix receivers from 2.4G and 900M

**Comment by glipski50** [comment]
That's from RCG Jet_Flyer. I can't open the web page the mentioned web page at the moment

![Bildschirm­foto 2022-11-08 um 09 23 25](https://user-images.githubusercontent.com/116186946/200512697-858938fa-5b17-4a3d-b327-ead8582dd224.jpeg)

**Comment by bsongis-frsky** [comment]
Confirmed. You cannot link a 2.4G and a 900M receiver. You can do it with TD receivers, or ACCESS receivers within the same band.

**Comment by EngelMT** [comment]
And if you use a RB30 with two 2.4 and one 868? This is possible and I never read that it is not allowed.

**Comment by mawzthefinn** [comment]
> What with on TD receiver and one 900 MHz?

That's not a permitted config. ACCESS or TD, not both as currently implemented.

**Comment by bsongis-frsky** [comment]
@EngelMT I should ask for confirmation about RB30, but I think yes it is allowed. But it is off topic here, no RBxx is mentionned.
