### ISSUE TITLE
trigger an event when the transmitter is turned off 

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#2051]
Hello Bertrand,
I've written a LUA tool that shows transmitter runtime and a reset time (e.g. last battery charge).
Is there a way to trigger an event when the transmitter is turned off so I can save the data?
Many Thanks
Benno

![image](https://user-images.githubusercontent.com/97786547/200189516-afe3f713-0d5b-4925-8910-3479df101c1d.png)

[main.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9948820/main.txt)

or as Widget
![image](https://user-images.githubusercontent.com/97786547/200655393-e7e0c868-61b5-49b7-bf96-94c67f7d9313.png)

[Senderzeit.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9964467/Senderzeit.zip)

**Comment by Benno00** [comment]
Hello Bertrand,
is there any hope that it will be implemented?
Many Thanks
Greet's Benno

**Comment by azaz44** [comment]
I wonder if what you're trying to achieve could be done with a persistent timer.

But I have to say it happened to me, that I needed such feature, like "execute lua function when transmitter shuts down", in the past. It was writing of flight data to the file when flight was finished. Flight end was detected by lost telemetry (disconnected model battery), while motor was off. And everything worked except of 2 cases, where data was not written
- user powered off the radio without disconnecting model battery (trusting its failsafe)
- user triggered radio "power off", then radio showed warning "receiver still connected". Then powering down the model was causing automatic radio shutdown (normal OpenTx functionality), but without logging anything.

So I think it would be useful addition.

**Comment by Benno00** [comment]
Hello,
it's not about logging the flight. it's about recording the usage of the transmitter.
therefore an event is needed to save the channel usage when the channel is switched off.
Greetings benno

**Comment by Benno00** [comment]
Hello Bertrand,
will the event come in 1.5.0?
Thank you Benno

**Comment by bsongis-frsky** [comment]
```lua
-- Lua Task Example

local function taskInit()
  print("Task Init ...")
end

local function taskWakeup()
  print("Task Wakeup ...")
end

local function taskEvent(event)
  print("Task Event", event)
end  

local function init()
  system.registerTask({key="LuaTask", name="Lua Task", init=taskInit, wakeup=taskWakeup, event=taskEvent})
end

return {init=init}
```

**Comment by bsongis-frsky** [comment]
With the traces:

![image](https://user-images.githubusercontent.com/50834778/223103246-315739a6-162e-45c1-b5e8-caf7b3b6f32b.png)

**Comment by Benno00** [comment]
Hello Bertrand,
thank you very much for the quick implementation
Greetings Benno
