### ISSUE TITLE
missing wireless buttons in hebrew

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2053]
this is on 1.4.2
English has 2 buttons at the bottom of "wireless" menu.
Hebrew has only one (reset module)
Text in this button in hebrew is also flipped, will work on fixing HE file.

![20221106_233559](https://user-images.githubusercontent.com/8968780/200196644-e73ca797-ed62-4818-bb48-3820ccfce9db.jpg)
![20221106_233540](https://user-images.githubusercontent.com/8968780/200196620-bde8110d-f4b8-4b34-8c0f-bb6b6184305d.jpg)

**Comment by i3dm** [comment]
Also in the trainer menu itself in English this line says "CH1 - CH8" with two configurable buttons.

in hebrew only "CH8" button:
![image](https://user-images.githubusercontent.com/8968780/200196788-b8029041-88ae-478e-9b44-d97ad2747a0b.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/200257679-f122fb7d-4878-4600-be02-e4e6e6920ea5.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/200258413-a3d24719-8041-4729-a9b9-7c9891688480.png)

**Comment by i3dm** [comment]
looks good. thanks.
