### ISSUE TITLE
updated HE.txt file for ethos 1.4.x

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2054]
see attached, please use it for future releases.

[he.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9946948/he.zip)

Also, i think its possible to remove HB.txt from the simulator package, as its no longer used. 
seems like only HE.txt is used.

**Comment by bsongis-frsky** [comment]
I think hb.txt is on your computer, you should remove it by yourself

**Comment by i3dm** [comment]
got it. thankn you.
