### ISSUE TITLE
Simulators Mac

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#2055]
A couple of months already create the request to support simulators on MacOs.
Can you create simulators for Mac?

**Comment by BernhardFe** [comment]
I would appreciate it very much.

**Comment by wmayvis** [comment]
Is it already addressed to a team member?

**Comment by chaoscrack** [comment]
It's sad to see there is no interest to solve this need.

**Comment by wmayvis** [comment]
Any progress on this?

**Comment by chaoscrack** [comment]
@Nicholas-Luoyi 
Do you have any information to this stagnant request?

**Comment by chaoscrack** [comment]
@Nicholas-Luoyi 
still waiting for any information...

**Comment by wmayvis** [comment]
@bsongis-frsky @Nicholas-Luoyi when will release this request?

**Comment by chaoscrack** [comment]
@bsongis-frsky @Nicholas-Luoyi 
It's so sad to see there is nobody out there who is willing to give a simple answer to this request.

**Comment by bsongis-frsky** [comment]
Added to #3440
