### ISSUE TITLE
issue 2035 and 2036

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2057]
are these 2 issues already dead. I don't see any action on them.

**Comment by mawzthefinn** [comment]
Typically what happens here is the discussion is mostly from users unless the FrSky team needs more input. The team will evaluate items and put them on their to-do list, then update here when they’re done.

To my understanding right now the focus is on 1.4.3 and getting X20HD support fully merged into the main release.

**Comment by bsongis-frsky** [comment]
open issues like you do just slows down the development process

**Comment by williajgr** [comment]
I wanted to know if the issues were going to be addressed in time for me to return the transmitter, as replacing all of my FAS-100 sensors will be more expensive than the radio.  I have a nice horus x10s express running open-tx that has a lot less bugs than ethos on my tandem x20s.  I opened 2 valid issues that were never addressed and I get this kind of response
"open issues like you do just slows down the development process".  what is "like you do" suppose to mean???
