### ISSUE TITLE
MSH FCU telemetry problem

### ISSUE THREAD

**Issue by RO-ULT527** [FrSkyRC/ETHOS-Feedback-Community#2058]
Bonjour Bertrand,
I think we have an ESC telemetry issue with the MSH FCU when hooked to a FrSky receiver using FBUS. So far I tested a TD R6, TD MX and Archer R6, all with latest fw. ETHOS is 1.4.2 and I used HW ESC V4 80-120-130 and YGE 90HV opto also with latest fw. I opened a case with MSH and Liang asked to post on Github after I sent a bunch of screenshots and csv files from the FCU log. In all tests, the telemetry cable from ESC was hooked to pin 5 of 4-5-6 legacy connector on the MSH FCU when connected. After a while (around 1 minute into the flight with YGE and closer to 6 with HW and it varies) the FCU bricks causing complete loss of control and a crash. On the video, I was flying very low and then it fell to the ground after the motor cut off, no damage & sheer luck. I noted on a different heli with YGE that the daisy-chained GPS ADV also on FBUS was still updating the widgets on the X20. Integration works and when I disconnect pin 5, disabling telemetry from the ESC, the FCU won't crash and all flights end normally. Powering off and on after, the FCU works normally until a certain amount of time depending on which ESC is used and then it freezes. 
Yesterday I hooked up an R6 to a mini Brain2 FCU using f.port and did 7 flights of 7 minutes each without a single issue with pin 5 connected. Telemetry works perfectly but of course, no integration since the luac won't work with s.port or f.port. 
merci
romeo
https://youtu.be/buFoM1Nlir4

**Comment by bsongis-frsky** [comment]
I read in your description that the FCU bricks. What makes you think that it bricks? And then why do you open an issue here?

**Comment by RO-ULT527** [comment]
Sorry I will check with Liang.

**Comment by enzo-molinari** [comment]
Hi

With MSH Brain I have problems too. I have uncontrolled pitch movements with FBUS. I use the TDMX receiver with tandem protocol. My clubmate has the same problems with FBUS. He uses the R4 ACCESS receiver. Both receivers work with the latest FrSky firmware. The Brain2 works with the latest Firmware too. If we go back to F.Port everything works fine again.

Enzo

**Comment by enzo-molinari** [comment]
Hi

With MSH Brain I have problems too. I have uncontrolled pitch movements with FBUS. I use the TDMX receiver with tandem protocol. My clubmate has the same problems with FBUS. He uses the R4 ACCESS receiver. Both receivers work with the latest FrSky firmware. The Brain2 works with the latest Firmware too. If we go back to F.Port everything works fine again.

Enzo

https://user-images.githubusercontent.com/87656206/200505409-d18a92a2-0a4e-4247-90cb-17278c69f58a.mp4

**Comment by bsongis-frsky** [comment]
I would need some input from MSH Brain here to understand on which side (Module / Receiver / FSH) is the issue. One sure thing is that Ethos doesn't control anything on FBUS except the configuration parameters. The protocol is implemented inside both the receiver and the module

**Comment by RO-ULT527** [comment]
Why if it's a hardware problem, integration works perfectly in OTX and it does NOT in ETHOS with s.port and f.port protocols? Why do we crash when using FBUS with ETHOS when the telemetry cable from the ESC is connected to the FCU? Why saying issue 2058 has no business here? Stop asking for input from MSH and just cooperate with MSH.

**Comment by bsongis-frsky** [comment]
Nobody has said it's a hardware problem. It would be interesting to know if it works with OpenTX (of course on FBUS)

I could be wrong of course, but from your description (works with S.Port / F.Port), I consider it's not an Ethos (the firmware on radio) issue, but rather either a problem in module, or in receiver. And if you are really sure that MSH bricks, there is a problem there as well!

**Comment by RO-ULT527** [comment]
There is a problem and it has to be fixed. That's all I ask. It's been dragging for months.

**Comment by m0p3d** [comment]
Reading this and have already seen various sensor (sensor conflict , loss ) problems doesn't let me believe everything is alright regarding archer or Ethos.

**Comment by bsongis-frsky** [comment]
I have just asked for news about this issue, and it seems solved (fix in MSH script).
Please tell me if I am wrong
