### ISSUE TITLE
Failsafe settings not getting saved

### ISSUE THREAD

**Issue by dehigama** [FrSkyRC/ETHOS-Feedback-Community#2059]
Ethos - X20
Firmware - 1.3.3, EU

Im trying to set failsafe on my heli, especially on the throttle, however, it seems that any value I set does not get saved, here's how I consistently reproduced the issue: 

Existing model 
Navigate to:
1. RF system
2. Failsafe = Custom and set Throttle to -100% or any other channel to say +5% just for the sake of testing. 
3. Exit the screen and wait 10-12 seconds.
4. Switch OFF Tx and test - all good servos move to set points as expected. 
5. Switch on Tx go back to the failsafe screen and all settings are lost. 
6. Switch off Tx and the Throttle channel goes to 0% (starts spinning the motor), and the other channel also gets updated as 0%. 

Tried cloning the same model and tested changes and the issue is reproducible, the only way I seem to get around this is to create a totally new model. 

During my tests I even saw the failsafe mode change from receiver to custom, it seems that it's always trying to set it to Custom mode no matter what. 

All other settings/changes such as within the mixer (Curves, expo..) are all good. 

So it looks like an issue specific to a model i have would be great to know what caused it so. that further models don't get the same behavior

**Comment by mawzthefinn** [comment]
What Receiver/firmware?

**Comment by dehigama** [comment]
@mawzthefinn  an x8r flashed with the latest v2 firmware.

**Comment by dehigama** [comment]
I’m just thinking if it’s a file / model corruption why would it only cause an issue with failsafe settings.  Creating a new model and setting failsafe to what ever mode or values gets saved permanently.

**Comment by bsongis-frsky** [comment]
Would you please attach your model file?

**Comment by dehigama** [comment]
I think I found the issue and it's user config based, while I was going through the special functions I had one as failsafe -> reset 'internal module'. the value 'internal module' gets added automatically by default. removing this function preserves the failsafe mode and configured channel values. 

But why would it always override failsafe to 'custom' and with channels values to 0%?

I'll do more tests and get back, also attach the model file.

**Comment by bsongis-frsky** [comment]
The "Reset" label was not right, I have changed to "Module"
![image](https://user-images.githubusercontent.com/50834778/200515716-1cd1b479-e704-43fe-bb2a-2125dea55fa7.png)

This Special Function sets your failsafes to the current value, so it depends on your current stick position etc.
