### ISSUE TITLE
Multiprotocol Telemetry

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2061]
Please enable MPM Telemetry. I used an IrangeX with OMP protocol and don’t get telemetry. (works on ETX/OTX)

**Comment by krelt** [comment]
Doesn't work for D8 or accst V 1.x either but it does work with the XJT lite.

**Comment by arshish1612** [comment]
Yes - Request this be enabled please.

**Comment by KevinFairgrieve** [comment]
Please keep open. Something that is needed.

**Comment by jasc76** [comment]
> Please keep open. Something that is needed.

+1

**Comment by Luznatural** [comment]
This is an essential fix for most of us, in order to keep compatibility with our already existing receivers.
Please, move forward on this issue.
Thanks in advance.

**Comment by 2xWhiskey** [comment]
I too wish to see this resolved.  I just spent several hours programming my new radio (TWIN XLite) to run into this issue as a roadblock to flying a new airframe (E-Flite Habu SS 50mm).  Guess I will have to program yet another model on my EdgeTX radio for now...

**Comment by Quaxbruch** [comment]
Looking really forward to this in order to reuse flysky AFHDS2A receiver and telemetry senors with the IRX4 Lite on my ETHOS Tandem X18s.

**Comment by jollsnj** [comment]
Also looking forward to this so I can use my X20S  to get telemetry with iRX4 Lite on my legacy models.

**Comment by Luznatural** [comment]
Please, move it forward.
Thanks in advance

**Comment by bsongis-frsky** [comment]
D8 / S.Port / FlySky / DSMX telemetry added to the 1.5.0 nightlies

**Comment by krelt** [comment]
Awesome about nightly inclusion! OMP is one of the protocols on multimodule. It's difficult because it wasn't originally on any of the native multimodule chip but instead is an emulation. Little helicopters I think.

**Comment by bsongis-frsky** [comment]
I am searching for OMP telemetry information. The Multiprotocol document says "Telemetry: No" ...

**Comment by krelt** [comment]
Would this help?
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/a8ae0a2bd1224b6f2600ef30f02702b4a1cdd47a/Protocols_Details.md?plain=1#L1196

**Comment by bsongis-frsky** [comment]
I will wait for someone who has some OMP telemetry on OpenTX, then I will send a special firmware which dumps the Telemetry stream

**Comment by mortehoe** [comment]
Is telemetry for Hitec supported in this release ?

**Comment by jasc76** [comment]
> I will wait for someone who has some OMP telemetry on OpenTX, then I will send a special firmware which dumps the Telemetry stream
@bsongis 
I could do that !

**Comment by mortehoe** [comment]
Would that dump the telemtry stream for OMP or will it include the telemetry stream for all the capable protocols including Hitec?

**Comment by 2xWhiskey** [comment]
> D8 / S.Port / FlySky / DSMX telemetry added to the 1.5.0 nightlies

I loaded the 1.5.0 nightly, 1.5.0, FCC #74ee924c to try out the telemetry.  But right away I've noticed that this firmware doesn't support CRSF/ELRS external modules...

**Comment by 2xWhiskey** [comment]
> > D8 / S.Port / FlySky / DSMX telemetry added to the 1.5.0 nightlies
> 
> I loaded the 1.5.0 nightly, 1.5.0, FCC #74ee924c to try out the telemetry. But right away I've noticed that this firmware doesn't support CRSF/ELRS external modules...

So I decided to go back from the nightly build to the latest stable release, 1.4.9, and that erased about half of my saved models.  Words of caution to everyone else, backup you models first to avoid numerous hours of programming lost.

**Comment by AlexEger** [comment]
> D8 / S.Port / FlySky / DSMX telemetry added to the 1.5.0 nightlies

It would be great to have telemtry for the Graupner HOTT protocol too, as I have a bunch of receivers I would like to use. I would appreciate it also very much to have the Graupner HoTT.lua for OpenTX rewritten for Ethos.

Cheers, Alex

**Comment by krajue** [comment]
Please insert Graupner Hott telemetry, also the luas. Big thanks
