### ISSUE TITLE
Negative Rate alarm

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#2064]
Hi,
Last week we have a crash in our field due to a miss configuration of Rate. A colleague created a kind of dual rate based on a switch to change between a smaller and a greater rate. The point is he miss configured it and create a negative rate that inverted the aileron surface. 

The crash could be avoided by just testing the sticks output before flying, but it would be good if Ethos could warn the user if the Rate reach zero or negative value by an alert saying that negative rate will invert the output command. If user decide to proceed just click ok and keep decreasing the value. 

Again, this is not a bug, we understand ethos is working as designed.

**Comment by bsongis-frsky** [comment]
Should we use an alarm everywhere a function can be used wrongly? I am afraid it would become very annoying!

**Comment by robertoalmeida** [comment]
I believe that in this case where you mess with an important configuration function and in a few cases you should use negative weight then an alert would not be a problem.
This alert could prevent a crash.

**Comment by marciomc-github** [comment]
Hi,
This negative rate is not commonly used and it is not present in other radio systems (they stopped at zero and you can invert servo in the output). Although Ethos brought this flexibility that is very welcome! I believe due to the rare condition when you need a negative rate and based on the risk of an accident a warning should be displayed. 
Maybe you can disable this alarm on Alarm tab.
