### ISSUE TITLE
Brazilian Portuguese special characters 

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#2065]
Hi,
Some of the Portuguese  Brazilian chars are not displayed properly although they are present on the txt language file. 
Please consider the following chars:

á é í ó ú ã õ â ê ô ç

**Comment by bsongis** [comment]
I have fixed an issue with `Á` which is not in your list!

**Comment by bsongis** [comment]
![image](https://user-images.githubusercontent.com/5603504/201924497-98d59308-ada1-4662-9fca-479e86ad6659.png)

**Comment by bsongis-frsky** [comment]
Still those chars to fix, I think everything else works correctly: `À` `â`, `Ê`
