### ISSUE TITLE
Wrong font size in the X10-ISRM  

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2068]
Hello dear Ethos team
With an x10-ISRM, various font sizes and font styles are not as they should be. The fonts are also wrong in the X10 simulator. Can this be changed?
Version Ethos 1.4.2
Attached are a few pictures
![Modellübersicht](https://user-images.githubusercontent.com/90325526/200911569-222df913-8620-43d1-97b3-ef733ef8bfd7.jpg)
![Startbildschirm](https://user-images.githubusercontent.com/90325526/200911573-538db8cb-7a9c-4f76-8b1c-b248712033be.jpg)
![Telemetriescreen](https://user-images.githubusercontent.com/90325526/200911575-655eb11a-0637-49d9-ac43-89d2958a36ef.jpg)

**Comment by bsongis-frsky** [comment]
Obviously you have always the same font everywhere. I think you haven't written the fonts on SD. You can write them with your computer by copying the files, or use the Ethos Suite to do it automatically.

**Comment by Wolepo** [comment]
Thanks, the tip helped.
I added this folder to the simulator for the X10. Now the fonts are also displayed correctly.
