### ISSUE TITLE
1.0.5 The timer control apparently uses the stick position and not the curve.

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#207]
Customers use -100 to 0 for Butterfly and 0-100 for Trottle. For this they create curves. But the timer control via Trottle followed not this curves. So the timer starts if you move the stick in the area of butterfly and not if the motor will be on.

**Comment by EngelMT** [comment]
@DaySpeed955i This can be a way. But better will be if the timer control works with the curves and not with the stick position. 

Our goal with ETHOS was and hopefully still is to ensure that it is as easy to use as possible. It should not be necessary to programme a logical switch for such a simple function.

**Comment by DaySpeed955i** [comment]
Yes, I agree ETHOS need to be simple and allow complex setup too. It was just a suggestion in the mean time a simple and effective solution is implemented.

I guess then "timer" need an extra trigger setup like "Throttle Curve" added to the list of triggers.
I would still like to have "throttle abs" with option % throttle trigger to be included too.

**Comment by centertrim** [comment]
See the linked issue for more info on throttle timer changes:  https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/98

**Comment by mawzthefinn** [comment]
This appears to be solved now, Timer obeys Throttle curves in current ETHOS
