### ISSUE TITLE
System sounds Brazilian Portuguese

### ISSUE THREAD

**Issue by robertoalmeida** [FrSkyRC/ETHOS-Feedback-Community#2070]
I would like to share the file for generating audios in Brazilian Portuguese for Google Cloud Text To Speech.

    "pb": {
        "engine": "google",
        "voice": "pt-BR-Wavenet-A",
    },

[audio_pb.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9980508/audio_pb.csv)

**Comment by bsongis-frsky** [comment]
Is it exactly the same grammar as `pt`?

**Comment by robertoalmeida** [comment]
> Is it exactly the same grammar as `pt`?

Brazilian Portuguese uses grammar similar to pt. The pronunciation is different.

**Comment by marciomc-github** [comment]
> Is it exactly the same grammar as `pt`?

Yes! It should work exactly as PT.
