### ISSUE TITLE
Forms API (Lua): no function to expand/collapse lines

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2073]
1.4.2

The forms API is nice, but it appears to lack a function to expand/collapse lines [like this (as raised by 'storchy' on RCG)](https://www.rcgroups.com/forums/showpost.php?p=50061101&postcount=489) 

Does such a function already exist? If not. can it be added?

Thanks!

**Comment by bsongis-frsky** [comment]
Perhaps `form.beginExpansionPanel()` could return the ExpansionPanel widget, and you would call `panel:open()` or `panel:close()`? Would it be OK?

**Comment by strgaltdel** [comment]
i've a rough idea how it would work, seems to be OK for me,
but (at least for me) a tiny example would be useful in order to minimize "trial & error" effort

**Comment by bsongis-frsky** [comment]
I could even allow this:
```lua
line = form.addLine("Line1 before panel")
-- ...

line = form.addLine("Line2 before panel")
-- ...

panel = form.addExpansionPanel("Line1")
line = form.addLine("Line1 inside panel", panel)
-- ...
line = form.addLine("Line1 inside panel", panel)
-- ...
panel:open()
panel:close()

line = form.addLine("Line1 after panel")
-- ...
```

**Comment by RC-SOAR** [comment]
Looks good, but could you explain a bit more:
- There are two uses of 'panel' in the example, one as variable ('panel=form'...) and one as object '(panel:open())' ?
- What do panel:open() and panel:close() do?

**Comment by bsongis-frsky** [comment]
Implementation is ready for 1.5.0
I have modified a little bit my example, and added a comment so that you can better understand

**Comment by RC-SOAR** [comment]
Thanks, that's clear now.
