### ISSUE TITLE
Flight modes inherit trim settings

### ISSUE THREAD

**Issue by radlouni** [FrSkyRC/ETHOS-Feedback-Community#2075]
Hello, this is not a bug, but a feature request. Would it be possible to make the flight modes configurable in such a way that they inherit trim settings from each other ?

**Comment by mawzthefinn** [comment]
It is possible to do, but requires use of multiple trim mixes, 

This area does need further work, but the request is a duplicate of part of #215 so I will close in favour of continuing discussion under that Issue.

**Comment by radlouni** [comment]
> It is possible to do, but requires use of multiple trim mixes,
> 
> This area does need further work, but the request is a duplicate of part of #215 so I will close in favour of continuing discussion under that Issue.

Would you please guide me, or point me in the direction of how I can use multiple mixes to do this. I was an open TX user, and then migrated to Ethos, but this feature is one i heavily used when i had open TX

**Comment by mawzthefinn** [comment]
I wrote up a basic guide here:

https://www.rcgroups.com/forums/showthread.php?4215761-ETHOS-Relative-Trims-Are-Possible%21#post49891333

**Comment by radlouni** [comment]
> I wrote up a basic guide here:
> 
> https://www.rcgroups.com/forums/showthread.php?4215761-ETHOS-Relative-Trims-Are-Possible%21#post49891333

Thanks
