### ISSUE TITLE
TWIN Lite Pro Module installed, when enabled the radio shows fluctuating TW signal strength indicator only when in the 'Info' screen

### ISSUE THREAD

**Issue by applewood** [FrSkyRC/ETHOS-Feedback-Community#2076]
ETHOS 1.4.2
X18 OR X20
TWIN MODULE 1.0.1

The external 4-bar indicator positioned at the top right of screen varies when on the 'info' screen.  Visibly cycles from 1 bar to 4 and back again.  When moving off the 'info' screen all 4 bars return.

Happens on both X18 and X20 radios.

https://user-images.githubusercontent.com/19472501/201474988-26213825-1c6c-4efa-9c8f-bdfc3015eabd.mp4

**Comment by mawzthefinn** [comment]
Interesting, #1868 seems to show the same behaviour on TD mode with the internal module.

**Comment by applewood** [comment]
> Interesting, #1868 seems to show the same behaviour on TD mode with the internal module.

Glad you confirmed the problem too.  Appreciate its not going to effect performance, because you wouldn't want to be on the 'info' screen while flying, but nice to fix.   

What happens next, does this get passed to RF ream?

**Comment by mawzthefinn** [comment]
Yes, this would be a pass on to RF team item. I'll confirm with @Adelaxie 

Note I was also able to confirm this behaviour with my TWIN Lite Pro module with numeric RSSI showing.

**Comment by Adelaxie** [comment]
When under the INFO page, the radio is rapidly asking for replies from the internal module so it may make the control not stable.
It might be somehow improved I think. 
Don't fly under the INFO page, however.

**Comment by applewood** [comment]
Should it have a warning or pop when going to the info screen 'Do not fly while on the INFO page'.    I think the chances of someone flying when on the info page is very limited anyway.

**Comment by bsongis-frsky** [comment]
I think Ethos should send less requests to the receiver then, no need to refresh very quickly. It can be done only once every 10 seconds.

**Comment by mawzthefinn** [comment]
That would make sense, there’s no way receiver version is fast changing, the only way it should change at all is if you power on a receiver while in the Info page.

**Comment by bsongis-frsky** [comment]
Timeout increased by factor 20 to be sure
