### ISSUE TITLE
1.4.3 X20S Pot warning doesn't disapear 

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#2077]
Hello Precious Team:-)
just had a short look at 1.4.3 - the Pot Warning at Start looks good - nice work - but it does **not** **disapear** after all pots are in right position. 
greetings

**Comment by m0p3d** [comment]
Same seems like even if everything is positioned like it should be the warning has to be confirmed to start. Not sure if this is the new concept or if something is not working.

At least I can tell it's different from previous releases.

**Comment by bsongis-frsky** [comment]
The concept has not changed. It should just display the correct Pot Position instead of the Current Position.

**Comment by bsongis-frsky** [comment]
While trying to reproduce this issue I have found a problem, the Warning is not displayed if only Pots are in wrong position. I guess it comes from the same problem.
