### ISSUE TITLE
Disk error

### ISSUE THREAD

**Issue by Tomppy** [FrSkyRC/ETHOS-Feedback-Community#2079]
Hello, I tried to update my X18 with Ethos Suite but it failed and now I can't even copy the bootloader file manually in the NAND file (Windows said there is an error). Ethos doesn't recognise my Model files anymore. (I have models and radio.bin files backuped)

If I try to select a model Ethos said "error opening file" and if I go in a other menu and come back, it doesn't find the models, whereas they are well presents in the file manager.

How can I fix it please?

![IMG_20221113_023211](https://user-images.githubusercontent.com/108630413/201501292-aa1f27c2-3589-4d43-ad22-61038d5724ac.jpg)
![IMG_20221113_022536](https://user-images.githubusercontent.com/108630413/201501297-1f59e2ee-d1cc-4b8f-ad02-e39cb0f2dce2.jpg)
![IMG_20221113_022552](https://user-images.githubusercontent.com/108630413/201501299-c898c137-40e4-4b78-a96d-9517bb084aec.jpg)
![IMG_20221113_022606](https://user-images.githubusercontent.com/108630413/201501302-ca2f93fa-1b5e-4df9-bdfd-f7932790ca28.jpg)

**Comment by Tomppy** [comment]
fixed by put the last bootloader on SD card and run it in the radio, then I used the repair tool on Ethos Suite

**Comment by mawzthefinn** [comment]
Glad to hear you got it fixed.
