### ISSUE TITLE
multiprotocole

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#2081]
Hello.
 Thanks for the answers .
but the directory link is missing.

Ext. Module Multi protocole not fond on Radio X20 FW 1.4.3. #2080

[bsongis-frsky](https://github.com/bsongis-frsky) commented [20 minutes ago](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2080#issuecomment-1313262106)
You need the latest script from this repository

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua
