### ISSUE TITLE
1.4.3 - Widget Selection or marking

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2083]
Hi,

the scroll wheel can be used to select a widget element (Altitude, type "Value"):

![ethos_widget_1](https://user-images.githubusercontent.com/31627548/202014871-5428c3c7-3c5d-46ea-950c-dc41a9985025.jpg)

However, if the element is of type "Line Chart", this does not work:

![ethos_widget_2](https://user-images.githubusercontent.com/31627548/202015026-bdd55d18-aec0-434d-9d9d-4d21e8ff1f30.jpg)

Here, the marker should actually be on GPSAltitude to visually indicate which element is active. It is only about the marking, a change with Return or Tap is possible at any time.

Ethos 1.4.3
Tandem X18S

**Comment by bsongis-frsky** [comment]
It's strange, here I get this:
![image](https://user-images.githubusercontent.com/50834778/202114684-026f5a86-ac1b-43e4-a8c0-0cd21bb7d931.png)

**Comment by Target0815** [comment]
Is it perhaps because you are creating a new model, while I have added a widget to an existing model that already has other widgets?

**Comment by bsongis-frsky** [comment]
I try to reproduce something, only after you changed the widget.
But if you press [Enter] then you scoll with the mousewheel, you will see the yellow rectangle, right?

**Comment by Target0815** [comment]
I have it ... If Auto Range is enabled, then the frame does not appear. With Auto Range set to Off it looks the same as yours.

**Comment by bsongis-frsky** [comment]
You are right, this information helps a lot!

**Comment by bsongis-frsky** [comment]
To be exact ... Auto Range with no value, we stop painting to avoid a zero division. And we forget the border.
