### ISSUE TITLE
Display Bug in Sim Trim Mixer

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2085]
There is a litte display bug  in simulator by trim mixer
the mixer is defined by switch A up/down and in the mixer list is displayed switch A up/up

![Ethos Mixer](https://user-images.githubusercontent.com/26022422/202386776-e9174fdf-ba27-482c-9b3b-a4442190b021.png)
![Ethos Mixerlist](https://user-images.githubusercontent.com/26022422/202386794-b2ecff36-0324-46c7-a2ad-eff91961f65e.png)

**Comment by bsongis-frsky** [comment]
Which version? This should be fixed since August

**Comment by Storchy1** [comment]
1.1.0-RC2 simulators
