### ISSUE TITLE
No BLE telemetry with CRSF

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2087]
Than use external Crossfire/ExpressELRS module, BLE service 0xFFF0 charasteristic 0xFFF6 is silent.

I would really like to see notify of CSRF frames: 0x02 (GPS), 0x07(Vario), 0x08 (Battery), 0x09 (Baro altitude), 0x14(Radio Link), 0x1E (Attitude), 0x21 (Flight mode), 0x80 (Ardupilot stream)
Tested on Tandem X20 (Ethos 1.4.3)

**Comment by mawzthefinn** [comment]
Are you using the BLE from the module or trying to mirror over the BT connection in the radio, set to Telemetry?

**Comment by r1000ru** [comment]
I am try use Tandem x20 bluetooth as telemetry mirror and look notices in nRF Connect

**Comment by r1000ru** [comment]
mail@r1000.ru

**Comment by Target0815** [comment]
I can't find the setting where CRSF can be enabled as a telemetry value via Bluetooth. Is this already present in 1.4.4?

**Comment by mawzthefinn** [comment]
@Target0815 You should get all active telemetry mirrored in 1.4.4 if BT is set to Telemetry
