### ISSUE TITLE
Feature request: Use switch/analogue input to change volume

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#209]
Version 1.0.5
X20S

It would be great if on the sound system screen, there was an option to assign an analogue input to change the sound volume. I guess even a switch or channel could be used too. 

I have always assigned the volume to pot S2 in the past. I find it really useful on the slopes for adjusting the vario. Or just in general flight, where I still want to hear feedback. But turn it down to not annoy others. This is good on an input, as it is easy to perform in flight. Going through the menu when you’re flying, not so much.

**Comment by MIKE-DAILEY** [comment]
It is there.  Long press the enter key on the volume control bar for control popup.

**Comment by MrD-RC** [comment]
That’s not very intuitive. I tried long pressing the screen with my finger on the icon to the left of the volume slider but it did nothing.

**Comment by MIKE-DAILEY** [comment]
There are quite a few places in ETHOS where long press enter provides popups for options.

**Comment by MrD-RC** [comment]
I understand that @MIKE-DAILEY. But most of the options I’ve have just been copy, clear, paste, and invert. 

I guess it’s just something to get used to. But for main functionality, like assigning a volume controller. The long press doesn’t seem that intuitive. I wouldn’t have thought to long press there at all as I wouldn’t have thought of the minimum and maximum shortcuts. What is there does work really well, when you know it’s there. But I still think I’d have preferred the dropdown on the left of the volume slider to always be there, and default to “value” or “always on”, which enables the slider. 

It does make me wonder what other useful features are hidden away behind the long press.
