### ISSUE TITLE
how to get a list of csv log files in a lua script

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2091]
I use simulator 1.4.0
I am writing a lua script for viewing log files like in OpenTX by RealTadango.
I need to know the count and the names of log files
i use at the moment the form addFileField but this is not very smart and i have to go always in configure mode.
Is there a possibility to get a list of file, a dir cmd perhaps
If not, will you implement something like io.popen() to get a table of files in the future?

**Comment by bsongis-frsky** [comment]
`io.popen()` executes a command, it won't be possible to add it, I think I will add a new function to list all files inside a directory

**Comment by bsongis-frsky** [comment]
`system.listFiles(...)` will do the job in 1.5.0

**Comment by Storchy1** [comment]
Thanks a lot
