### ISSUE TITLE
Elrs telemetry issues

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#2092]
Hi, I’m using 1.4.3 on x20s hd and using latest lua script files. I have found that rx batt is showing the battery connected to flight controller but it is only a one decimal (4.2,3.8 like this) even I change the decimal to 2 by editing the telemetry I get the same. Can you please change this to display the actual value that the elrs rx is sending? And one more thing we don’t get any telemetry in regards to battery voltage or rssi values if using an spi based elrs rx( like if the elrs is built in the flight controller) can you also look into this please?

**Comment by bsongis-frsky** [comment]
The CRSF specification says 1 digit. I don't know where you find 2 digits.

**Comment by bsongis-frsky** [comment]
From X20 / Ethos it should be no difference if you use a SPI based ELRS. Please provide more details as we don't have this hardware at hand!

**Comment by r1000ru** [comment]
CRSF battery frame have 0.1V precision
INAV
`
crsfSerialize16(dst, getBatteryVoltage() / 10); // vbat is in units of 0.01V
`

ELRS
`
typedef struct crsf_sensor_battery_s
{
    unsigned voltage : 16;  // mv * 100
    unsigned current : 16;  // ma * 100
    unsigned capacity : 24; // mah
    unsigned remaining : 8; // %
} PACKED crsf_sensor_battery_s;
`

 voltage = value * 100 (look comment) /  1000 (from mV to V)

**Comment by bsongis-frsky** [comment]
Thanks @r1000ru 
Do you know about the other question (ELRS SPI RX)?

**Comment by r1000ru** [comment]
Wrong rssi values: #2086
RxBt must work correctly, if telemetry enabled in betaflight

**Comment by kakashi2018** [comment]
@bsongis-frsky  It is my bad that I didn't enable telemetry in my spi based elrs flight controller, now it's only the battery voltage that needs to be taken care as the rssi is in #2086

**Comment by mawzthefinn** [comment]
As noted above, the battery telemetry is correct as per the CRSF spec. Only one decimal precision is supported in the CRSF spec.
