### ISSUE TITLE
X20 hd video component update issue

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#2094]
Hi, I have tried updating my new x20HD video component using ethos suite and the update failed using the auto-update feature now my radio doesn't display anything just a black screen. Tried updating again with the provided jumper pin now the updater says the my version of the hardware is not compatible with that firmware. just a note I see the video component version as version 2 when my radio got shipped last month. now the radio is in the unusable state as it displays a black screen. tried re-updating all the bootloader and firmware but still no use? can you provide a solution to it please?

**Comment by MIKE-DAILEY** [comment]
ETHOS SUITE will update everything for you.  Here is a HD help post on RCG https://www.rcgroups.com/forums/showpost.php?p=49484097&postcount=18651

**Comment by bsongis-frsky** [comment]
Are you sure your hardware is V2?

**Comment by kakashi2018** [comment]
Yes, video component version is 2 in the info tab when the radio got
shipped with 1.4.0

**Comment by kakashi2018** [comment]
"Auto flashing doesn't start successfully. Please flash the .frsk manually by following the steps" after this the radio is stuck at screen that is diplaying updating video component popup, and wont come out of it, So I had to pull out the battery as even the power button wont work

**Comment by kakashi2018** [comment]
I really dont remember the color of the light, now the radio turns on or off and I guess all the actions except it doesn't display anything. not even the boot screen or the bootlader screen where it shows bootloader version, every where its just a black screen

**Comment by bsongis-frsky** [comment]
Yes, because you have removed the power in the middle of flashing!

**Comment by bsongis-frsky** [comment]
You have to wait on Monday when the person in charge of that component can answer.

**Comment by kakashi2018** [comment]
@bsongis-frsky thank you for your help, I have used the provided jumper pin and flashed version 2 of the video component firmware and after the same pop up shown again "Auto flashing doesn't start successfully" I have unplugged and removed the jumper pin and it started working normally. However the suite doesn't flash the video firmware directly when the radio is on and USB is connected, it either shows an error pop-up saying this version of firmware is not suitable for the radio or a message showing no radio connected. I had to press the right center button and power button to get into bootloader mode and then click the flash button then the suite is flipping the radio mode and then starting the firmware update. The only thing that is missing now is the video component version is showing as unknown. 3 suggestions from me
1) fix the suite so it will flash the video component directly when the radio is turned on and usb is connected
2) make sure that jumper pin is not needed always to update the firmware properly
3)make the video component version appear in the info tab so people like me won't flash different version.

**Comment by kamilvlk** [comment]
Hello, i have the same issue (Auto flashing doesn't start successfully ...) , i have the video component version 1 most probably (there is no port for recovery mode). The radio has now the blank screen at all.

Is there any way how to flash it? FW in radio is 1.4.3.

**Comment by EngelMT** [comment]
Here the same with to radios. One HD and one HD upkit.

**Comment by kakashi2018** [comment]
Not really sure if it works without the jumper pin as of now but I’m pretty sure tht they are going to fix it soon

**Comment by bsongis-frsky** [comment]
I know EngetMT radios are repaired. We have had to use special files to repair. If anyone encounters an issue, please contact me directly and I will send everything needed to repair.

**Comment by austinpowers1977** [comment]
hi i have a X20HD and its missing video component and cant update is. the HDzero works but cant see osd!

**Comment by kakashi2018** [comment]
Yeah. They just sell the radio and never released an update to that
expensive hardware. Don’t worry, I found a way that you can get osd from
betaflight. The trick is osd in that radio works only with analog setting
in betaflight osd. So try avoiding hd settings and use pal for better
layout in osd tab. There might be a chance that osd comes in first boot and
dissappears from the next time. In this case you need to compile the
betaflight firmware by unticking the hd osd option and add your flight
controller related hardware manually of your gyro and acc don’t work. This
way osd remains.

**Comment by austinpowers1977** [comment]
Still no joys sadly.

**Comment by austinpowers1977** [comment]
Also says in beta video tranmitter page its not supported or something. i accidently reset the model it was wokring before i did this just dont know how to fix the issue.

**Comment by kakashi2018** [comment]
Didn’t quite understood what your issue is? Can you explain a little more
detail?

**Comment by austinpowers1977** [comment]
It's OK bud I'm sending back my mobula6 but my X20HD won't show osd.

**Comment by kakashi2018** [comment]
I can send some more tips when i get home. As far as I remember there is
one of the menu button that will toggle osd on and off from the x20hd. I
have the mob6 hdzero version as well and I get osd no problem if you follow
above mentioned steps that is if you set thr betaflight osd with analog
setup.

**Comment by austinpowers1977** [comment]
Finally got the Component V2 release and tried to flash handset got a black screen and can not see anything. Anyway to fix this issue?

**Comment by kakashi2018** [comment]
Where did you get the v2 firmware from?

**Comment by austinpowers1977** [comment]
hi i get it from ethos but its now a black screen and i cant undo it. how did you fix yours?

**Comment by austinpowers1977** [comment]
> I know EngetMT radios are repaired. We have had to use special files to repair. If anyone encounters an issue, please contact me directly and I will send everything needed to repair.

hi mines gone wrong while updating its now black screen can you help?

**Comment by kakashi2018** [comment]
Hey. Now I got the black screen as well. And the fix from last time isn’t
working now. The thing is ethos suite always failing to auto update the
video component and so getting the black screen. I will try if anything
else can be done. If nothing workd we definitely need help from @bsongis

**Comment by austinpowers1977** [comment]
Yes this is way beyond a joke frsky! This shouldn't be happening. I'm now
stuck without a transmitter. To top this off I was charging my handset and
it fell backwards onto my desk and snapped off the antenna bracket. Made of
cheap plastic. Not impressed with this handset at all. Not like it a cheapo
tranas is it, £550 and it doesn't work as it should.

**Comment by kakashi2018** [comment]
@austinpowers1977  I have made it to work. if you have the jumper pin that came with the radio, please insert it to the radio. it will be next to the hdmi pin. turnoff the radio. push the right bootloader button and then power button, this will put your radio to bootloader mode. now plug in the radio with usb to your pc. from the ethos suite where you tried updating the video component download the v2 component and use the manual mode to flash. the suite will flip the radio mode from bootloader mode. always select the v2 version from the popup if you have the jumper pin. after few seconds you get a popup saying auto flash didnt work. now just disconnect the usb and wait for few minutes. you will see the power button blinking( this will take sometime). after a beep and the blinking stops you can remove the jumper pin. now your radio will work as usual

**Comment by austinpowers1977** [comment]
done that but comes up with "radio returned unexpected error" is that normal? i have flashed it and its sat on desk black screen no beeps and on icon is blue ish in colour.

**Comment by kakashi2018** [comment]
Is your radio v2? And where are you seeing that error?

**Comment by austinpowers1977** [comment]
its dev a V2 as i have small hdmi and 2 pin above for jumper. its showing error when i try to install. comes up with it straight away when uploading to handset

**Comment by kakashi2018** [comment]
Can you try with a different usb? Plug in the jumper pinand  you need to
connect your radio only after pressing the the right  side select button
and pressing the power button. And then from the suite select v2 version
from popup and then manual update the video component by selecting the
downloaded file. Once the popup comes that says auto update failed just
unplug the usb and wait for atleast 5 minutes. You will hear a beep. After
that you can remove the jumper pin and the radio will show the display.

**Comment by austinpowers1977** [comment]
it beeps when i comes up with the error but i unplug usb and ill wait for 5 mins. Just want it to be working. so frustrated with this

**Comment by austinpowers1977** [comment]
OK if it doesn't work ill do a video.

**Comment by kakashi2018** [comment]
I have faced similar situation on the first time. Couldn’t get much help
and had to do trial and error. Just post me the video that you are doing.
Might be something you are missing.

**Comment by austinpowers1977** [comment]
Maybe bud. Just very odd. I'll post it on YouTube and send you a link
shortly.

**Comment by austinpowers1977** [comment]
https://youtu.be/XslKAdLC_uw

have a look see what you think bud

**Comment by kakashi2018** [comment]
Says video is private.

**Comment by austinpowers1977** [comment]
let me change that now bud

**Comment by austinpowers1977** [comment]
just waiting on it to fully upload

**Comment by kakashi2018** [comment]
2 things I need to confirm. The first one is the jumper pin. Can you use
the other jumper pin. The one shown in video seems to be short or broken
and hence no continuity. The second thing is disconnect the usb as soon as
the popup appears showing auto update failed and wait there for 5 minutes
dont turn off. Although nothing seems to be happening it is installing the
video component in the background and it will take quite some time. You
will notice blue blinking led after some time and there will be a beep
after flashing is complete. And only remove the jumper pin after the beep
and power led stops blinking. Also flash the firmware from the video
components tab.

**Comment by austinpowers1977** [comment]
I'll give it a try but not holding out much hope. I've done this 10 times
now. I'll leave it on till led flashes or I hear a beep. Get back to you
once this happens.

**Comment by austinpowers1977** [comment]
This thing is badly broken. I can't get it to work. Is there a way to
factory reset it?

**Comment by kakashi2018** [comment]
Sadly Only frsky team can help now.

**Comment by austinpowers1977** [comment]
Can't get them to reply. Lazy fuckers so fed up with frsky. Make crap
products that they don't support properly. Seriously had enough of them.
This is all coz frsky won't explain the hdzero set up. Firmware is a joke!
I'm done with this crap!

**Comment by kakashi2018** [comment]
You will definitely get sone help. Just open a new thread and explain the
issue. It’s just that frsky community is somewhat small that delays are
expected from support, but they will help you
