### ISSUE TITLE
Ethos Suite 1.4.3 will not update bitmaps

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2097]
i Have X12s will not update bitmaps in ethos suite i think ethos is looking for the files on github cant find them ?
![Untitled](https://user-images.githubusercontent.com/9161926/202822884-8a38f8f5-6591-45af-8612-c96be4df5548.png)

**Comment by jbesse262** [comment]
I have the same issue. I had to manually update firmware and bootloader.

**Comment by bsongis-frsky** [comment]
I had forgotten Horus Bitmaps! It should be good now after you restart Ethos Suite
