### ISSUE TITLE
Move Range Check button down next to Failsafe

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2098]
Ethos 1.4.3

It does not make sense to have the Range Check button next to the Register button, because it should be the last thing you do before flying. Having it before Bind makes no sense.

I propose you split the Failsafe line into two, and move the Range Check button to the RHS. These two logically belong together because they are safety related.

**Comment by lthole** [comment]
The proposed change creates a more logical workflow by moving the Range Check button after the Bind etc.

**Comment by bsongis-frsky** [comment]
I propose these changes:
1) Move "Register" above Model ID / Channel Range / Racing Mode

![image](https://user-images.githubusercontent.com/50834778/211381254-8113dd1c-6ef1-4b72-a338-c7983aff875a.png)

2) Keep Failsafe in his own line as it is already possible to have a "Set" button there

3) Add a new line for "Range Check"

![image](https://user-images.githubusercontent.com/50834778/211381374-5f3f8e5c-cd3c-43e1-9e49-50ff088fa49f.png)
