### ISSUE TITLE
Ethos suite 1.4.3 does not down load on 2 PCs

### ISSUE THREAD

**Issue by ajatmiddday** [FrSkyRC/ETHOS-Feedback-Community#2099]
With suite 1.2.11 installed I get the notification that the new 1.4.3 suite is downloading in the background. Quitting the suite & reopening
1.2.11 is present,1.4.3 is not. Waiting minutes for the download did not help. I can see no indication of a down load it the download folder. I  turned off my security application still no joy. Finally I downloaded the 1.4.3 .Exe file & updated that way This has happened on 2 Win 10 PCs. One PC I have not updated manually. . I noticed there is a 1.4.3 suite.dmg file do I need this file also?

**Comment by ajatmiddday** [comment]
Ok I found out the .dmg is an Apple file

**Comment by Dsrenger** [comment]
Can confirm.

Had the same behavior.

The message for a new Suite popped up. But nothing happend. Waiting, closing and reopening the Suite didnt help.

Ended up in installing the suite manually.

That said, my PC always identifys the Suite file as not thrustworthy and ich have to confirm several messages to get it. (more information, really accept the file ect.)

@ajatmiddday: the DMG is for MAC/Apple

**Comment by dap35** [comment]
I saw this on both my Windows 10 PC and my Mac (13.0.1).   I manually downloaded the files and ran the install without issues.

**Comment by 4qr1hu9n7** [comment]
Delete 1.4.2 manually. Download and install 1.4.3. manually. Then install

**Comment by yak-54** [comment]
> I saw this on both my Windows 10 PC and my Mac (13.0.1). I manually downloaded the files and ran the install without issues.

where are the bitmap files for X12S ?

**Comment by yak-54** [comment]
looks like some just add the Horus SD card 3 hours ago

**Comment by yak-54** [comment]
all good now works fine with Ethos suite after someone add the horus sd card
