### ISSUE TITLE
0.17 Firmware causing display tearing.

### ISSUE THREAD

**Issue by OldGazer** [FrSkyRC/ETHOS-Feedback-Community#21]
Shortly after updating from 0.16 to 0.17 I noticed the lower 1/3 of the display was glitching and tearing every 1 to 3 seconds.
This behavior was most noticeable on the "home" screen, but all screens were affected to some degree.

Reverting back to 0.16 resolves the issue.

**Comment by bsongis-frsky** [comment]
Please install the BL from 0.17 with the FW from 0.17, and reopen the issue if it doesn't fix your problem

**Comment by OldGazer** [comment]
Done.  Issue persists.
