### ISSUE TITLE
Button text entry options

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#210]
Just some feedback on the text entry using the standard transmitter controls.

Firstly, would it be possible to change the case inverter to a lock? I think that would be a lot more useful than having to invert every character. For example: **Roll**
Current:
- Find **R**
- Press _Enter_
- Find **O**
- Press _MDL_
- Press _Enter_
- Find **L**
- Press _MDL_
- Press _Enter_
- Find **L**
- Press _MDL_
- Press _RET_

Suggested:
- Find **R**
- Press _Enter_
- Find **O**
- Press _MDL_
- Press _Enter_
- Find **l**
- Press _Enter_
- Find **l**
- Press _RET_

I’m sure you can appreciate that with longer words, the 2nd approach would be more useful.

My other suggestion would be changing the button that activates the functions. My first thought for changing the case was the _Page_ button. I’m used to pressing for _Page Up_ and long pressing for _Page Down_. So that button seemed like the natural choice for changing the case.

The _Page_ button actually performs a delete operation. If _Page_ is used for case, I’d recommend moving the delete to the _DISP_ button. The first character is a *D*, so it would be easy to associate _DISP_ with delete.

**Comment by bsongis-frsky** [comment]
This is interesting, I did it yesterday, exactly the way you proposed :)
