### ISSUE TITLE
Incorrect Bootloader flashed for 1.4.3

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2101]
macOS Suite 1.4.3

When updating to 1.4.3, my previously generic bootloader was identified as EU instead of FCC, so the 1.4.3 EU boot loader was incorrectly flashed.

After downloading X20_BOOTLOADER.ZIP, noting there are no individual EU or FCC versions, copying to the radio and flashing from there, it still says version EU. 

![bl](https://user-images.githubusercontent.com/26259987/202885823-0dd8f77b-1fdb-4380-b536-9440b2b63cd0.png)

**Comment by Nicholas-Luoyi** [comment]
Where did you download the X20_BOOTLOADER.zip. I found there isn't such a file on the GitHub at all.

**Comment by Nicholas-Luoyi** [comment]
It's a display issue. I will fix it.

**Comment by WA6LTV** [comment]
Thanks I had the same problem.
Chuck
