### ISSUE TITLE
1.4.3 X20 Checklist screen 'radio' image missing

### ISSUE THREAD

**Issue by applewood** [FrSkyRC/ETHOS-Feedback-Community#2102]
I've updated my x20 to 1.4.3.  The checklist radio image is now missing.

I've reapplied all the firmware and software via ethos suite.

![20221120_120403.jpg](https://user-images.githubusercontent.com/19472501/202900940-4cc5e28f-d249-4fe4-896f-440015091e0e.jpg)

![20221120_120335.jpg](https://user-images.githubusercontent.com/19472501/202900943-0f562ec7-5a11-4354-be3f-478e4758f179.jpg)

**Comment by applewood** [comment]
![20221120_121055.jpg](https://user-images.githubusercontent.com/19472501/202901108-bb03405a-697a-4908-b099-1a63cd5bfbbf.jpg)

**Comment by STC148** [comment]
I can confirm, there is also something wrong with the X20S
![IMG_20221120_132008868_HDR](https://user-images.githubusercontent.com/85410070/202901744-4db68550-f688-4c08-a938-27ec49805987.jpg)

**Comment by applewood** [comment]
Ok thank you.  I've just tried rolling back to 1.4.2, the checklist screen is fine on that version.  Then update again to 1.4.3 and same problem again with the missing image.

**Comment by kramgrand** [comment]
I have had the same result.  Also on about half my models, (Strangely gliders) When you go through the check list to set the correct switch positions for that particular model, the screen does not change and it still prompts to "Press any key". When I believe it should go to the Home Screen of the model.    On my gliders I frequently use the left and right sliders. The sliders do not show on the checklist.  I have rolled back to 1.4.2 and the boot loader that goes with it for safety and peace of mind.
![IMG_0850](https://user-images.githubusercontent.com/96422592/202902286-c04be2d5-0842-425e-9a60-7c951b2c82a5.JPG)

**Comment by bsongis-frsky** [comment]
Have you installed the 1.4.3 bitmaps with Suite?

**Comment by applewood** [comment]
Hi, yes just used the ethos suite 'upgrade all'  to upgrade components from 1.4.2 to 1.4.3 .     I tried rolling back to 1.4.2 and the bitmaps was displayed correctly.  Upgrading again to 1.4.3 still had the bitmap issue

**Comment by bsongis-frsky** [comment]
The bitmap is SD:/bitmaps/system/X20_check_background.png

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/203007876-c40b8e5c-2fd6-4385-a9ae-c332ffec4f9a.png)

**Comment by bsongis-frsky** [comment]
Please force update the bitmaps to be sure. It should be 1.4.3

**Comment by applewood** [comment]
In the office today, will try later and report back.

**Comment by Dsrenger** [comment]
Its working for me now as well.

Quite strange. I made the update to 1.4.3 a couple of days ago. Suite showed me that everything was updated. (with the label). I am very sure that every entry showed that its the newest version.

Today I reattached the TX to the Suite and it showed me, that the Bitmaps are outdated. 
I updated it and its working now. No idea what happend. 

But seems like, I was not the only one.

**Comment by applewood** [comment]
Your right I've started ethos suite today and now it says bitmaps are out of date.   Strange as I restarted suite a few times before.

![20221121_175148.jpg](https://user-images.githubusercontent.com/19472501/203127655-7ee302fa-70c3-4b0e-b50b-0f6b06806d4f.jpg)

![20221121_175544.jpg](https://user-images.githubusercontent.com/19472501/203127671-660b4a60-38d1-470b-8211-a046b2835522.jpg)

![20221121_175724.jpg](https://user-images.githubusercontent.com/19472501/203127687-3e48dca4-4c8a-4d1b-96c2-560745e226af.jpg)

**Comment by applewood** [comment]
I can send an upload of the slow startup video if you provide me an email.  Can't seem to add large files here

**Comment by applewood** [comment]
Found the issue with the slow startup it was to do with new model images I've added.  Must be something to do.with the file size.   I noticed it slow rendering the image when changing models.   Removing the images made it quick starting up again

**Comment by applewood** [comment]
My slow startup confirmed with overly large image file.  I've correctly resized it and it's fine now.  

So both the checklist bitmap issue and the slow startup is resolved.  Happy for it to be closed

**Comment by kramgrand** [comment]
Hello,  I have reloaded the latest 1.4.3 back onto one of my transmitters and now I have the correct display on the checklist. If the switches are already in the correct position it continues and loads the model Home page/display.  But If any of the switches are in the wrong position and I correct them, the display then shows all the switches in the correct position and the "Press any key to skip" prompt.  Where as up to this update the model Home Screen would appear.  Again this only appears to be the case with my gliders. With power models, when you correct the switch positions the home page appears.
![IMG_0853](https://user-images.githubusercontent.com/96422592/203299233-019a0cc9-a24f-496d-bfaa-70360b3f44b5.jpeg)

**Comment by mawzthefinn** [comment]
Glad to hear you have it all sorted
