### ISSUE TITLE
Add -copy to the cloned model name

### ISSUE THREAD

**Issue by GiorgioCirelli** [FrSkyRC/ETHOS-Feedback-Community#2104]
When you clone a model, the copy gets the same name causing confusion as the model id is different so the radio is not binded.
it would be useful if **-copy** is automatically added to the model name

**Comment by i3dm** [comment]
perhaps a better way is:
model
model(1)
model(2)
model(3)
etc

**Comment by GiorgioCirelli** [comment]
> forse un modo migliore è: modello modello(1) modello(2) modello(3) ecc

Yes
