### ISSUE TITLE
Calculated Sensor Not working

### ISSUE THREAD

**Issue by chenbevis** [FrSkyRC/ETHOS-Feedback-Community#2105]
firmware 1.4.2 1.4.3
Use FAS100 ADV create Calculated Sensor Not working 
battery capacity and power Not working

**Comment by bsongis-frsky** [comment]
Please explain a little bit, have you discovered the sensor? Do you see Voltage / Current? Then it will be possible to create a Power or a Consumption Sensor, using the FAS100 ADV as source for this calculated sensor.

**Comment by chenbevis** [comment]
> 請解釋一下，你發現傳感器了嗎？你看到電壓/電流了嗎？然後可以使用 FAS100 ADV 作為此計算傳感器的來源來創建功率或消耗傳感器。

It is found that the sensor also displays voltage and current, but the created power sensor and capacity sensor do not work

**Comment by bsongis-frsky** [comment]
Please share a screenshot of the configuration of your Calculated Sensors so that I can try to help.

**Comment by chenbevis** [comment]
> 請分享您的計算傳感器配置的屏幕截圖，以便我可以提供幫助。

I don't know why, today it worked and I didn't make any changes
