### ISSUE TITLE
lua: introduce method to reset timers

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2106]
When you create a timer, you can set a "start time" for down-counting timers.
You can even set a reset condition, based on "physical" or "logical" switching states.

But in Lua there is no method to trigger a reset "directly", you would have to "emulate" the previously set "reset condition".
So it is not possible to trigger a reset directly from a "lua-defined condition".

I would suggest introducing a "reset" method for timers. like

local tmr = model.getTimer(tmrNum)
tmr:reset()

(of course you can set the value to zero for up-counting timers, so this is a rare situation and has low priority). 

Regards

Udo

**Comment by bsongis-frsky** [comment]
needed

**Comment by strgaltdel** [comment]
.. still needed
