### ISSUE TITLE
Ethos simulator keyboard shortcuts not suitable for all PCs

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2108]
The ethos simulator assumes that you have a numeric keypad, which not all PCs do. This makes it's use problematic for those PCs without numeric keyboard.
I concede it is difficult to decide which keys you would use in such circumstances so maybe they could be made user assignable?
Is it perhaps possible to have a couple of virtual joysticks which could be moved with mouse/ touchpad, with each axis sticky or not?
Thanks

**Comment by Dsrenger** [comment]
You could use the virtual keyboard of you OS. That works fine for me.

**Comment by bsongis-frsky** [comment]
Numeric keys without numeric keyboard are used for trims
