### ISSUE TITLE
Change the order of the announcements during the station start sequence.

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2109]
Hello dear developers,
at the moment it is the case that during the start-up of the transmitter (or a model change) first the announcements from the special functions and then the warnings from the checklist are output, even before a correction of the switches etc. has taken place. However, this is somewhat confusing. Therefore I suggest the following:
1. the model name should be moved from the special functions to the model config. So another line must be inserted under the model photo, which makes the *.wav selectable for the model name.
2. now the warnings from the checklist could be output first.
3. only when the checklist has been processed, all other announcements should follow.
I wonder if it could be set up this way, it would look much more pleasing in its processing.
Thank you for the understanding

**Comment by bsongis-frsky** [comment]
At least Point 3 makes sense to me

**Comment by Wolepo** [comment]
Now the model name is immediately displayed in the status bar of the "Edit model" menu. Why can't the model name be announced before the announcements from the checklist? In addition, a special function would be avoided in this context.

I wish you a Merry Christmas and a Happy New Year.
