### ISSUE TITLE
GR8 sound problem.

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#211]
Horus x10 isrm ethos 1.0.5 The vario still has a sound problem.
See last message:  #175
Thanks

**Comment by KenLong51** [comment]
I am getting the same promlem with an X20 (v1.0.5) and a G-RX8. The vario sound hardly changes with movement, but does when using my X10s.

**Comment by bsongis-frsky** [comment]
Link to #223
