### ISSUE TITLE
Previous Updates

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#2111]
Hello;

This is more of a question then an issue. I am currently running release 1.3.3. This release is functioning perfectly for me, right now. I am concerned with all of these new releases; my current settings and setup may not function properly after an update. Do "new" updates replace properly functioning programs in order to have other areas of improperly functioning programs to work?

**Comment by Target0815** [comment]
> I am concerned with all of these new releases; my current settings and setup may not function properly after an update.

No, from 1.3.3 to 1.4.3 this is not to be feared. Make a backup before and you are safe.

**Comment by mawzthefinn** [comment]
No, they do not.

However the behaviour of certain mixers may change over time to address concerns which have been raised. The same for Lua scripts and telemetry data. The changes will be listed in the Changelog for the release.

If you are in 1.3.3 there's only two changes which might affect you from going to 1.4.3:

1. The location of the Multiprotocol module changed with 1.4.1 (from scripts/modules to scripts/multi) and IRC Ghost now has its own script
2. The throttle trimmer now inverts when you invert the Throttle mix. Check this if you Invert your throttle mix.

**Comment by 4qr1hu9n7** [comment]
Thanks everyone. Unlike Microsoft. Their operating system updates cause, in some cases, more problems. Performing updates always requires the end user to carefully evaluate to pros and cons.
