### ISSUE TITLE
Ethos Suite - localization (Brazilian Portuguese)

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#2112]
Hi!
I would like to help translating Ethos Suite to Brazilian Portuguese. Is there any file or procedure to help me doing that?

Best,
Marcio

**Comment by Nicholas-Luoyi** [comment]
You can find the JSON file in the /i18n of the Suite's root directory. Please post the JSON file here after translating.
