### ISSUE TITLE
Tandem XE touch screen response slow

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#2114]
The response time from the bottom touch screen on the Tandem XE is very slow.  Typing a name on the virtual keyboard has a delay approaching 1 second per character, for instance.
Selecting an active condition, when moving a switch from up to down position, through the middle position, takes 2 attempts before the correct switch position is being registered.

**Comment by bsongis-frsky** [comment]
Which firmware version?

**Comment by phaedra-tm** [comment]
Update succeeded now (did it step by step, instead of "update all"), response is much better now.

**Comment by mawzthefinn** [comment]
Glad to hear that the update solved this.
