### ISSUE TITLE
Tandem XE top screen widget is global

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#2115]
The top screen widget settings are global, meaning they are the same for all models.
If I want to display telemetry values on the top screen, I have to reconfigure it each time that I switch models? (not all my models have the same telemetry parameters)

**Comment by bsongis-frsky** [comment]
Are you sure?

**Comment by Tonio62** [comment]
In my case, no problem, each model has its own parameters for the top screen, like for the main screen

**Comment by phaedra-tm** [comment]
Was finally able to update firmware to 1.4.3 (didn't work first), and that solved the issue.
Can be closed
