### ISSUE TITLE
Screen backlight and hiss speaker during charging

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#2116]
Just for information, on my new Tandem XE is it normal for the screen backlight to come on and for there to be a slight hiss from the speaker during charging?

1.4.3 firmware

Thanks,

![IMG_20221123_144013](https://user-images.githubusercontent.com/89158034/203561146-60ad8c59-8233-46c4-8bb8-d2420d5742d6.jpg)

**Comment by mawzthefinn** [comment]
The backlight on while charging is also an X18 behaviour, so I would not worry about it.

**Comment by Target0815** [comment]
> The backlight on while charging is also an X18 behaviour

This is not the case with my X18S. However, this may also be due to the settings.

**Comment by adammaas-softchoice** [comment]
It wasn't noticeable with my X18 screen (same as S), but I have the SE screen/backlight fitted now and it's noticeable.

**Comment by mawzthefinn** [comment]
And another oops, wrong GitHub account.
