### ISSUE TITLE
Ethos Suite - should it auto update?

### ISSUE THREAD

**Issue by applewood** [FrSkyRC/ETHOS-Feedback-Community#2117]
I noticed my Ethos Suite doesn't auto update it's own software anymore.  I'm fairly sure it used to update itself.  The Suite downloads correct radio firmware.

A few noticed the same on RCG:
https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-Tandem-24-Channels-with-ETHOS/page1424

Would be a nice feature for the Suite to check if its on the latest version and give an option to upgrade.  Thanks :)

**Comment by Target0815** [comment]
The suite had already updated itself once when you closed it. But I can't say which version that was.

Basically there should be a hint at startup when there is a new version.

**Comment by bsongis-frsky** [comment]
Yes this version had a problem. Next won't!

**Comment by applewood** [comment]
Thank you for responding, that's great.
