### ISSUE TITLE
Commenting on old issues

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2118]
Hi,

wouldn't it be better/simpler if old issues are closed automatically if nothing has happened there for 6 months?

Any bugs that were reported in old Ethos versions or requests only from a single user actually only inflate the list.

**Comment by adammaas-softchoice** [comment]
@bsongis implemented a new procedure that is tagging items as stale after 30 days with no comment, then closing 5 days later unless the stale tag is removed. 

I'm working through the older issues slowly and closing off anything I can confirm as fixed, while giving the reporters a chance to comment if it's not. I am also trying to ensure that old unsolved issues get addressed if not confirmed as fixed.

I'm leaving anything that is obviously still a valid outstanding request for now. I was asked to help with managing the issues in Github when I was brought on as a Beta tester.

**Comment by mawzthefinn** [comment]
Oops, the above commenter is me, posted from wrong Github account.

**Comment by Target0815** [comment]
I thought that this is the case ... If you now comment on old issues, they are always at the top, if you sort the issues by the date of the last comment. Personally, I'm only interested in current Issues, but current for me is nothing that was months ago.

IMHO it would make more sense if you don't comment and the automatic process goes through stale / close unless the issue starter reports itself. Because he should be interested in pushing the issue, if it still exists.

**Comment by mawzthefinn** [comment]
That's the end goal, but the cleanup only runs when issues hit the 30 day mark, so the current set of old issues is not being addressed by the new process.

As we get things cleaned up, it should work the way you describe long-term.
