### ISSUE TITLE
X20S Check List ERROR -  When you are using Left  Or  Right sliders or both sliders at same time

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#2124]
Hi,  I use the left and right sliders on most of my gliders, typically for throttle control on the left and camber control on the right.
As the left one is always throttle on my electric gliders I include it in the Check List.
Since upgrading to 1.4.3 I have found that both L &R  sliders have a check list problem, in that the only way for the check list to complete and load the model "Home" Screen is for everything to be in the correct position right from the start of loading the model......     As in, if ALL the switches and sliders just HAPPEN to be in the correct positions when you load the model, it proceeds through the check list and loads the model Home Screen.

I have discovered that if you have any switch in an Unsafe position, you are as expected, prompted to move it to a safe position to continue.   When you have made that switch "Safe". You then expect the model Home Screen to appear. But instead, (If you are using sliders) You are presented with the "Press any key to skip" Message and at the same time a screen showing EVERYTHING in the correct position. Including the sliders in a safe positions.   I have found there are two ways to continue. 
1. You press any key to skip,  As per the message. (Previous versions of Ethos do not behave this way when everything is correct)
2a If you are using both sliders, you move BOTH of them to UNSAFE positions.. (The Home Screen then loads).  
2b.If you are only using ONE slider. Move that one to an Unsafe position    (Again the Home Screen loads).

E.G.   _While "Press any key to skip" is displayed._
If you are using both sliders and they are in the "Safe" positions, the check list screen shows them as SAFE...  If you move Both of them to an Unsafe position, the Home Screen will then appear.  

More worryingly, I have found that you can power on the transmitter and have ALL the switches in the correct positions to start with, but with both sliders in UNSAFE positions and it will load up to the model Home Screen. If one slider is safe and one unsafe it presents the "Press any key to skip".

**Comment by mawzthefinn** [comment]
Identified for pots in #2120 

Should be fixed in 1.4.4

**Comment by mawzthefinn** [comment]
Confirmed fixed in 1.4.4
