### ISSUE TITLE
Tandem XE, the top screen layout of the model don't stay in place

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#2125]
When you change the model, the layout of the top screen does not stay in place....
if you have for example programmed 4 windows on the top screen for an X model and you change the model, when you come back to it the configuration has changed and is back to 2 windows

Firmware 1.4.3

**Comment by phaedra-tm** [comment]
Confirm this.
I changed the layout of the top display to 4 panels/widgets.  When I switched off the radio, then on again, the top screen was reset to just 1 panel/widget.
Also, why aren't the different layout options shown on the right side, when "top screen" is selected in the layout page?  That would make the logic for configuring the top screen the same as for the bottom screen.
