### ISSUE TITLE
Unable to update Firmware X18

### ISSUE THREAD

**Issue by northcave** [FrSkyRC/ETHOS-Feedback-Community#2127]
I'm using a Max with the latest Ethos Suite. I have updated the Bootloader on the X18 to 1.4.3.

When following the instructions for fireware updates then the suite does no detect the x18. I cannot copy files to NAND as the computer doesn't see that either when plugged into USB. In Ethos Suite it also says "If your radio cannot read from NAND or the settings cannot be saved. Please connect to Suite with radio power on. Then try this tool." The repair button is not available.

Is it possible to copy the fireware to an SD and update it from the Ethos file manager on the x18 itself?

**Comment by northcave** [comment]
**UPDATE: Solution found.** 
I copied the firmware.bin file to the SD card on my computer. Then in Ethos on the x18 copied the firmware.bin file to radio.bin on NAND. Turned off the x18 and started it in Bootloader mode. This updated the x18 to the lastest firmware, bypassing Ethos Suite.

**Comment by mawzthefinn** [comment]
Closing this off as you found a solution
