### ISSUE TITLE
Tandem XE

### ISSUE THREAD

**Issue by miksterr** [FrSkyRC/ETHOS-Feedback-Community#2128]
There is noise whilst charging - like a hiss/white noise. Not sure if a software/firmware issue? Others have said the LCD backlight also is on during all of the charge time.

Second issue - during ANY trim change, button press , voice callout there is noise prior, during and also just after the intended sound.

**Comment by Tonio62** [comment]
Same issues for me.....
Backlight on and hiss during charge....
Also noise prior....
Can you check if your top screen is polarized sunglasses friendly like the bottom screen ?
In my case it's not :/
Some others owner have not these problems, only the hiss during charge and noise prior
Thanks

**Comment by mawzthefinn** [comment]
#2038 seems to be the same as your second issue

**Comment by miksterr** [comment]
Tonio62 - my top screen is fine with polarised glasses. I did get emergency mode when I tried to delete a global voice callout. I had never used before. Imported all my planes from X20s to XE and started checking them - every time I deleted the setting with a global it went to emergency. Have decided to delete all and start fresh with the XE.

**Comment by bsongis-frsky** [comment]
"Every time I deleted the setting with a global", what do you mean?

**Comment by miksterr** [comment]
I meant " Global" under Play Track. I had a track that was global, when I tried to delete the whole line it went to emergency mode.

**Comment by bsongis-frsky** [comment]
The first part of your issue is the same as #2038 
The other part is a bug which is present in all radios and will be fixed in 1.4.4
