### ISSUE TITLE
Ethos timer start point

### ISSUE THREAD

**Issue by Asafsol** [FrSkyRC/ETHOS-Feedback-Community#2129]
Would like to have the option to set the start point from with the timer will begin in relate to the throttle stick position, an option that is usually available in other tx's
In todays status, it began the count 1 click above min position.

**Comment by mawzthefinn** [comment]
You can do  this today so long as you are using just timer on/off functionality.

Use a Logic Switch of A > X type, on the Throttle channel (not Analogs->Throttle) and use that Logic Switch to engage the timer. Any Logic Switches you can think up can be used to start/stop the timer.

**Comment by Asafsol** [comment]
Like this?Asaf‫ב-27 בנוב׳ 2022, בשעה 16:30, ‏‏mawzthefinn ***@***.***> כתב/ה:‬﻿
You can do  this today so long as you are using just timer on/off functionality.
Use a Logic Switch of A > X type, on the Throttle channel (not Analogs->Throttle) and use that Logic Switch to engage the timer. Any Logic Switches you can think up can be used to start/stop the timer.

**Comment by mawzthefinn** [comment]
You didn't include anything other than text in your response, as you replied to the email.

I recommend use the 'view it on Github' link and updating in the web interface if you want to add screenshots.

**Comment by mawzthefinn** [comment]
Are you still having the issue?

**Comment by Asafsol** [comment]
Issue solvedThank youWish is was simplerAsaf‫ב-30 בנוב׳ 2022, בשעה 16:10, ‏‏mawzthefinn ***@***.***> כתב/ה:‬﻿
Are you still having the issue?
