### ISSUE TITLE
Deleting a custom curve breaks mixer curve settings

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#213]
Tried searching for this issue and I couldn't find a post.

This happened on my X20 running 1.0.5 and I am able to replicate it in the simulator.

If you delete a custom curve, everything in Mixer gets assigned to "???" for the curve. This happens even if there is no curve assigned to the mix.

When the curve is "???" in the mixer and you click/tap Edit, it crashes. But that's probably not really a problem since the curve shouldn't be "???" in the first place.

**Comment by KenLong51** [comment]
I also found this today - exactly as rburrow87 states.

I also have an X20 on 1.0.5.

This cost me a lot of time until I realised what it was doing.

**Comment by pld74** [comment]
Yes, same outcome encountered here running 1.0.5 on X20 and X12S
