### ISSUE TITLE
feature request: create more sound files to improve user friendliness 

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2133]
Hi,

please add some "user friendly" soundfiles and place them in a language dependent subdirectory (same folder level as "system")

This feature request is based on my personal experience with my club buddies.
clearly, an IT affine user has no problems by generating his own wav files by using a tts tool.
But most of the club members are not "computer biased", and so they struggle to generate sound files.
And i'm afraid this is not the only one club...
even in case i try to explain the "how to" several times, mostly it ends that i have to create a sound file and mail it to the buddy.
personally, i wouldn't publish these files in order not to violate license agreements.
It's my understanding that FrSky has such license agreements, and so it can publish more sounds.

Most requested feature is acoustic feedback in case one wants to activate / deactivate a mixer, switching a flight mode, or change some stati during flight.

Ethos supports an easy to use interface to play files by using its special functionalities.
Unfortunately it lacks the "typical" requested soundfiles.

I guess it would improve user experience if Ethos would support some kind of "standard waves"

I would propose to add a new folder for these "not system" files, so it would be easier to differentiate between Frsky files [in subfolder like ../audio/en/...) and user created waves (../audio/en)]  
maybe a folder called "jbos" // "just a bunch of sounds" (../audio/en/jbos)

So the "play track" function would have to search in this additional folder too

i can only speak for glider pilots, these are the most wanted files:

:: Flaps,Mixers & functions
dual rate on
dual rate off
Expo on
Expo off
flaperon on
flaperon off
snapflap on
snapflap off
crow on
crow off
spoiler on
spoiler off
strak
gear down
gear up
Vario
Vario on
Vario off
Vario compensated

::warnings
warn altitude
warn distance
warn throttle

:: Gyro/Stabi
stabi on
stabi off
stabi horizon
stabi autolevel

::Flight Modes
reflex
standard
speed
thermal
start
acro
landing

:: timer
timer1
timer2
timer3

:: reset
reset altimeter
reset gps
reset telemetry
reset timer1
reset timer2
reset timer3

:: Div
on
off
armed
motor armed
set
go
normal
reset
full
trim
differential
max
min

regards

Udo

**Comment by 4qr1hu9n7** [comment]
This person has a series of tutorials on Ethos. Easy to follow and understand.
https://www.youtube.com/@MrD

**Comment by bsongis-frsky** [comment]
This list will fit to your own needs, but then we will need more prompts for someone else. You may create your own sounds using Google Text To Speech.

**Comment by strgaltdel** [comment]
just for the the archives / the ones who are interested :

personally i do prefer  ttsautomate (open source)
https://github.com/CaffeineAU/TTSAutomate

(you can easily manage lists of different translations, one click batch operation...)

it was may impression that the majority (at least in my club) are not the ones who are capable to easily learn or want to learn the "How Tos", independent if the source is written or a video , they even rarely use the  internet as an information source,
but maybe to much old school guys in my club, and so i'm wrong...

thanks for your time

**Comment by 4qr1hu9n7** [comment]
Well. You could learn how to create these files than, if you were willing, could teach the rest of your club members. I'm sure they would appreciate that.

**Comment by mawzthefinn** [comment]
@strgaltdel For those for whom creating a custom sound set is impractical, OpenTX 2.2 compatible sound packs work VERY well in ETHOS and can be dropped directly into /audio

English-speakers often use the well known Amber soundpack this way, I've been recommending it for a long time for ETHOS users needing a basic sound pack.
