### ISSUE TITLE
No line number in LUA error prints

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2134]
Hello,
X20S 1.4.2 FCC

managed to generate an error in one of my LUA scripts.
to investigate it i connected X20 to serial port, and this is the print;
![image](https://user-images.githubusercontent.com/8968780/204455983-9ca8cf28-31ed-44f6-bc1f-0613169a946c.png)

seems the print is missing the row number?

**Comment by i3dm** [comment]
Just tested 1.4.3
same result

**Comment by i3dm** [comment]
This is the same on the sim:
![image](https://user-images.githubusercontent.com/8968780/204461891-f2b33069-1075-4d71-8eb4-0adf3563a9ad.png)

**Comment by bsongis-frsky** [comment]
May I assume you don't run luac files?

**Comment by i3dm** [comment]
> May I assume you don't run luac files?

i do run luac.

**Comment by bsongis-frsky** [comment]
luac are stripped, they don't contain any debugging information, i.e. vars names and lines numbers are lost
you have to debug your script before compiling it to luac

**Comment by i3dm** [comment]
@bsongis-frsky  please stop closing issues before they are resolved.
the lua is also in the folder, and compiles fine.
the issue i had in the lua was that the status table in a switch case (ECU_status[x]) got a float instead of int, and was cauing the error, and the bad print with no line indication.

this is totally not related to LUAC.

**Comment by bsongis-frsky** [comment]
which issue is not resolved?

**Comment by i3dm** [comment]
> which issue is not resolved?

the printing with no line number. its unclear why this happens.
both lua and luac are in the folder.

**Comment by bsongis-frsky** [comment]
> > which issue is not resolved?
> 
> the printing with no line number. its unclear why this happens. both lua and luac are in the folder.

yes it is very clear and it is why I consider I can close the issue

**Comment by i3dm** [comment]
its not clear, as if i deliberately imposed another error, it would print fine with a line number.

**Comment by strgaltdel** [comment]
@ i3dm:
may i suggest that ypou rename your .luac into .luaX so that the script is enforced "to be sourced" definitely from the .lua file ?

I don't know exactly how it works, but i guess all .lua files are subject to a syntax check by starting the script, so this kind of error would be exposed with line numbers.

**Comment by i3dm** [comment]
> @ i3dm: may i suggest that you rename your .luac into .luaX so that the script is enforced "to be sourced" definitely from the .lua file ?
> 
> I don't know exactly how it works, but i guess all .lua files are subject to a syntax check by starting the script, so this kind of error would be exposed with line numbers.
> 
> furtheron (at least at 2nd start after compiling without changing the source) the script will be started from the compiled version, so logical (type mismatch) errors can't be exposed with line numbers. without existence of a luac file you should see all errors with line number included
> 
> would this work in your case ?
> 
> regards

thank you for the sound advice. its a good idea.
