### ISSUE TITLE
Tandem Xe Dark mode/Light mode And brightness ajustement on top screen

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#2135]
Hello,

When you switch from dark mode to light mode and vice versa, you must turn the radio off and on again for the top screen to take the mode change into account.  
I don't know if it's normal, but the brightness adjustment is inoperative on the top screen

1.4.3

**Comment by bsongis-frsky** [comment]
How do you want to adjust the brightness of the top screen? It's already at maximum

**Comment by Tonio62** [comment]
Ok, that was just an observation, because the top screen is less bright than the bottom one.

**Comment by bsongis-frsky** [comment]
It is fixed, at maximum already. I am not sure it's needed to add a brightness setting as it cannot be brighter

**Comment by Adelaxie** [comment]
The small size display has a limited number of backlight beads, and the brightness will be lower when compared. However, we continue to improve on-screen visibility such as removing the designed cover and so on.

**Comment by bsongis-frsky** [comment]
The top screen will be adjusted in 1.4.4

**Comment by miksterr** [comment]
> 

Does this mean future (or later) XE will be different and brighter?
