### ISSUE TITLE
function to jump to a certain screen

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2136]
I am looking for a way to change the active screen via LUA
For instance, switch to a certain screen when the engine is armed, but
it's important not to switch back and forth between competing wakeup routines. Perhaps one should introduce a time limit of 1-2 seconds in this new class/function, then one would have at least the security then one does not consume the system resources.
Perhaps one can think about it whether such a function would be meaningful

**Comment by mawzthefinn** [comment]
This is the Lua equivalent of #652 

Closing this off as a Duplicate, but please continue discussion under that Issue, it would be a great feature, Lua or SF.
