### ISSUE TITLE
Vrx backpack doesn’t work with tbs fusion module

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#2137]
Using 1.4.3 on x20 hd, tbs fusion module with back pack installed and happymodel es24tx pro nano module with backpack installed. When ever i click the send vtx button inside ELRS Configuration it kind of freezes the happymodel module not only the backpack doesn’t work but after that button is clicked if we go back and come to the elrs configuration the happymodel module disappears  in that menu. I had to restart the radio for it to popup again.

**Comment by bsongis-frsky** [comment]
If your HappyModule freezes why don't you ask them the reason?

**Comment by Target0815** [comment]
Ethos 1.4.3 / Tandem X18S

This is what happens in the serial monitor when I do as described by @kakashi2018:

`
Device: HM ES24TX Pro
Device: HM ES24TX Pro
Device: HM ES24TX Pro
lue: D500(-104dBm)
Choice Value: F500(-104dBm)
Choice Value: F1000(-104dBm)
Field: Telem Ratio, Type: 9
Choice Value: Std
Choice Value: Off
Choice Value: 1:128
Choice Value: 1:64
Choice Value: 1:32
Choice Value: 1:16
Choice Value: 1:8
Choice Value: 1:4
Choice Value: 1:2
Choice Value: Race
Field: Switch Mode, Type: 9
Choice Value: 8ch
Choice Value: 16ch Rate/2
Choice Value: 12ch Mixed
Field: Model Match, Type: 9
Choice Value: Off
Choice Value: On
Field: TX Power (25mW Dyn), Type: 11
Field: Max Power, Type: 9
Choice Value: 25
Choice Value: 50
Choice Value: 100
Choice Value: 250
Choice Value: 500
Choice Value: 1000
Field: Dynamic, Type: 9
Choice Value: Off
Choice Value: Dyn
Choice Value: AUX9
Choice Value: AUX10
Choice Value: AUX11
Choice Value: AUX12
Field: Fan Thresh, Type: 9
Choice Value: 10mW
Choice Value: 25mW
Choice Value: 50mW
Choice Value: 100mW
Choice Value: 250mW
Choice Value: 500mW
Choice Value: 1000mW
Choice Value: 2000mW
Choice Value: Never
Field: VTX Administrator, Type: 11
Field: Band, Type: 9
Choice Value: Off
Choice Value: A
Choice Value: B
Choice Value: E
Choice Value: F
Choice Value: R
Choice Value: L
Field: Channel, Type: Value: 5
Choice Value: 6
Choice Value: 7
Choice Value: 8
e Value: AUX5▒
Choice Value: AUX6▒
Choice Value: AUX6▒
Choice Value: AUX7▒
Choice Value: AUX7▒
Choice Value: AUX8▒
Choice Value: AUX8▒
Choice Value: AUX9▒
Choice Value: AUX9▒
Choice Value: AUX10▒
Choice Value: AUX10▒
Field: Send VTx, Type: 13
Status: 0, Info:
Field: WiFi Connectivity, Type: 11
Field: Enable WiFi, Type: 13
Status: 0, Info:
Field: Enable Rx WiFi, Type: 13
Status: 0, Info:
Field: Enable Backpack WiFi, Type: 13
Status: 0, Info:
Field: Enable VRx WiFi, Type: 13
Status: 0, Info:
Field: Backpack, Type: 11
Value: AUX6
Choice Value: !AUX6
Choice Value: AUX7
Choice Value: !AUX7
Choice Value: AUX8
Choice Value: !AUX8
Choice Value: AUX9
Choice Value: !AUX9
Choice Value: AUX10
Choice Value: !AUX10
Field: DVR Srt Dly, Type: 9
Choice Value: 0s
Choice Value: 5s
Choice Value: 15s
Choice Value: 30s
Choice Value: 45s
Choice Value: 1min
Choice Value: 2min
Field: DVR Stp Dly, Type: 9
Choice Value: 0s
Choice Value: 5s
Choice Value: 15s
Choice Value: 30s
Choice Value: 45s
Choice Value: 1min
Choice Value: 2min
Field: BLE Joystick, Type: 13
Status: 0, Info:
Field: Bind, Type: 13
Status: 0, Info:
Field: Bad/Good, Type: 12
Field: 3.0.1 ISM2G4, Type: 12
Field: Send VTx, Type: 13
Status: 2, Info: Sending...
timeout 200 status 2
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
Field: Send VTx, Type: 13
Status: 0, Info:
timeout 200 status 0
timeout 200 status 0
195590 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
195649 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
195709 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
195764 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
195819 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
195875 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
195930 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196002 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196056 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196109 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196162 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196216 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196273 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196328 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196383 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196436 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196490 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196544 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196600 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196654 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196709 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196764 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196823 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196877 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196932 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
196986 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197040 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197094 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197149 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197202 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197256 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197310 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197368 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197422 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197477 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197531 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197585 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197640 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197694 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197749 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197805 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197860 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197919 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
197974 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198049 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198103 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198157 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198209 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198262 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198316 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198369 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198424 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198483 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198537 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198592 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198646 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198701 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198756 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198811 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198866 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198921 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
198976 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199034 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199090 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199146 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199202 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199257 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199313 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199369 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199424 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199480 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199535 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199594 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199650 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199707 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199762 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199817 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199873 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199929 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
199984 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200059 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200116 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200170 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200225 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200278 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200331 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200385 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200439 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200493 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200548 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200603 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200657 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200717 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200773 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200828 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200882 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200938 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
200993 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201047 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201102 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201156 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201210 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201272 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201326 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201383 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201437 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201493 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201548 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201603 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201657 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201712 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201766 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201824 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201879 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201935 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
201989 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202066 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202120 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202172 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202225 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202278 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202336 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202389 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202442 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202497 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202551 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202605 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202658 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202711 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202764 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202816 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202874 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202928 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
202982 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203036 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203089 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203141 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203195 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203248 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203301 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203353 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203412 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203466 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203519 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203573 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203625 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203679 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203733 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203788 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203841 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203896 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
203954 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
204008 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
204086 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
204139 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
204193 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
204247 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)
204301 wakeup() error: RADIO:/scripts/elrs/main.lua:246: bad argument #-1 to 'pushFrame' (number expected, got nil)

`

**Comment by bsongis-frsky** [comment]
Thanks for the investigation @Target0815 

I have made a fix in the script on github, would you please check it?

**Comment by kakashi2018** [comment]
@bsongis-frsky , @Target0815 I don't see that issue now with new lua script. however it still doesnt change the channel on the tbs fusion module. I don't have any other modules to test as of now. but can you please check on your end if the send vtx is doing exactly what it is supposed to do. I can confirm and update here this once I get the new radiomaster ranger module which doesnt require the lua for backpack.

**Comment by Target0815** [comment]
> I have made a fix in the script on github, would you please check it?

@bsongis-frsky with the new script the error message does not come any more. Whether the backpack works, I can not test at the moment. But it is probably not an Ethos problem.

**Comment by kakashi2018** [comment]
@Target0815  yes this might not be an ethos issue as the backpack is able to change the channels in the vtx its not working for just the vrx. But I will update here once I get my other backpack module. Thank you for the quick responses.

**Comment by bsongis-frsky** [comment]
Ok, please reopen if needed, I consider everything is OK here
