### ISSUE TITLE
Screen scrolling should be extended to Carousel behavior

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#2138]
Scrolling through the screes over the last screen would be interesting. 
If I'm on the last screen and swipe to the left, nothing happens. Here the screes should switch to the first one and the other way around like a carousel.

**Comment by bsongis-frsky** [comment]
libopenui handles the 2 methods internally (wrapping or no wrapping), so it should be very easy to change.
This question had been discussed in the early days of Ethos, and we reached the consensus around the current way it works!
I am not sure there is wrapping on Android and iOS too, yes?
Perhaps you are used to OpenTX?

**Comment by BernhardFe** [comment]
Independently from IOS (has no carousel), Android or Open TX it came into my mind because in some models I have several (up to 5) screens. If I want to go from the first to the last I need to swipe through all the others and the same way back. If it would be possible to swipe into the other direction from the first to the last directly, it is much less swiping and faster. That was the idea behind. I understand that there are different opinions about it. Finding "blind" the first screen is not possible any more with a carousel. You may decide what the best user experience is. :-) I think the modern style is like it is today in ETHOS.

**Comment by bsongis-frsky** [comment]
Ah you meant about the Home screen? 
My answer was about all Ethos screens

**Comment by Target0815** [comment]
@BernhardFe probably means the widgets on the homescreen. And there you can easily get from the first to the last widget if you hold down the middle button on the left for a longer time ... But this is not possible via swipe gesture.

**Comment by BernhardFe** [comment]
@bsongis-frsky sorry, yes, I mean the home screen. It is exactly what @Target0815 mentioned, but with a swipe. From first home to last home and from last home to first home is missing with a gesture. Maybe this is not a big effort to make it happen. ;-) 
The described feature by you first time would be also very very nice idea (swiping between mixers or logical switches horizontally), but this is, I guess, more effort and a new issue worth. Because open a mixer to look for values, close it open the next one, change, ... is also very laborious. So this is a great and comfortable idea as well.
@Target0815 Thanks for the hint, I didn't recognised this, I will use the middle button as a work around! :-)

**Comment by i3dm** [comment]
i too would like to see screens as a carousel when swiping.
actually using the page button works like a carousel anyway.
