### ISSUE TITLE
External module XJT not working with X12S

### ISSUE THREAD

**Issue by DaySpeed955i** [FrSkyRC/ETHOS-Feedback-Community#214]
X12S ISRM ETHOS 1.0.5

You can select external XJT with D16, it will not bind unless you use the button in the back (use for PPM binding).
There is no control possible.
Setting up in PPM gives the same results, it is binding only with using the back button on the XJT but no control.

If you go to INFO, you will see that the external module is not recognized, "Unknown"

Thanks

**Comment by MIKE-DAILEY** [comment]
Working OK here.  X12S ISRM 1.0.5.and external XJT module.
