### ISSUE TITLE
r9m module in access mode

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2141]
no register mode for the r9m module on my ethos x12s transmitter.  works fine on my open-tx x10s express.

**Comment by mawzthefinn** [comment]
That's correct, the X12S hardware does not support external modules in ACCESS mode (the same issue exists on a ACCST X10).

The X10S Express has a new module interface capable of running the R9M in ACCESS mode.

**Comment by mawzthefinn** [comment]
The ACCESS Upgrade for the X12S and X10 only affects the internal module, not the external module interface.

**Comment by williajgr** [comment]
Ok thanks,  can I use the module in accst mode or do I have to reload the firmware on the r9m?Sent from my iPhoneOn Nov 30, 2022, at 10:37 AM, mawzthefinn ***@***.***> wrote:﻿
The ACCESS Upgrade for the X12S and X10 only affects the internal module, not the external module interface.

**Comment by williajgr** [comment]
Thanks,  that’s what I thought.  Sent from my iPhoneOn Nov 30, 2022, at 10:56 AM, mawzthefinn ***@***.***> wrote:﻿
You need to load ACCST firmware to the module to get ACCST mode on it.

**Comment by mawzthefinn** [comment]
With the question answered, I will close this issue off.

**Comment by williajgr** [comment]
I did close the issue.  I have a question on the Isrm board for the x12s. Installed it, uploaded 2.1.6.  Everything looked good, I had the options for access and accst. Couldn’t bind accst(didn’t even say(audio)) bind and wouldn’t register an access receiver. Everything works fine on my x10s and x20s.  I have probably done something wrong, but can’t figure out what. Any help would be appreciated.     JoeSent from my iPhoneOn Nov 30, 2022, at 12:04 PM, mawzthefinn ***@***.***> wrote:﻿
With the question answered, I will close this issue off.

**Comment by mawzthefinn** [comment]
In System->Info, what does the Internal Module section say?

**Comment by williajgr** [comment]
It said unknown.  That doesn’t sound good.Sent from my iPhoneOn Nov 30, 2022, at 10:30 PM, mawzthefinn ***@***.***> wrote:﻿
In System->Info, what does the Internal Module section say?

**Comment by williajgr** [comment]
I noticed that when I put in an external xjt module (which works) it also says unknown Sent from my iPhoneOn Dec 1, 2022, at 5:57 AM, George Williams ***@***.***> wrote:﻿It said unknown.  That doesn’t sound good.Sent from my iPhoneOn Nov 30, 2022, at 10:30 PM, mawzthefinn ***@***.***> wrote:﻿
In System->Info, what does the Internal Module section say?

**Comment by mawzthefinn** [comment]
There’s something wrong with the module. An ACCESS or TANDEM module should report the hardware version, firmware version and whether or not it’s FCC or EU. If it’s showing unknown, the radio can’t talk to the module.

other modules, including the XJT, show unknown as they either don’t report version info or you have to get that info via a script.

**Comment by williajgr** [comment]
This is on my x12sSent from my iPhoneOn Dec 1, 2022, at 8:12 AM, mawzthefinn ***@***.***> wrote:﻿
There’s something wrong with the module. An ACCESS or TANDEM module should report the hardware version, firmware version and whether or not it’s FCC or EU. If it’s showing unknown, the radio can’t talk to the module.
other modules, including the XJT, show unknown as they either don’t report version info or you have to get that info via a script.

**Comment by mawzthefinn** [comment]
Yes, I was comparing to my X12S with the ISRM Upgrade fitted and an external XJT module installed. 

The ISRM Upgrade should report hardware and firmware versions on the info screen as long as the module is turned on in RF System for that model. 

The XJT will never report version, because that ability was only added with ACCESS.

**Comment by williajgr** [comment]
I think the board is rev 2.0 with three antenna connections.  I do have a second board i will try.  Kind of a pain in the x12s.Sent from my iPhoneOn Dec 1, 2022, at 9:42 AM, mawzthefinn ***@***.***> wrote:﻿
Yes, I was comparing to my X12S with the ISRM Upgrade fitted and an external XJT module installed.
The ISRM Upgrade should report hardware and firmware versions on the info screen as long as the module is turned on in RF System for that model.
The XJT will never report version, because that ability was only added with ACCESS.

**Comment by mawzthefinn** [comment]
Yes, the ISRM Upgrade board is labelled as an iXJT Rev 2.0 on the board (that was the original name for the board)

**Comment by mawzthefinn** [comment]
Can you post a picture of your install?

The X12S install can be a pain because you need to install a second internal antenna (or steal the BT antenna)

**Comment by williajgr** [comment]
Think I will try the board in my x10s.  Do you think that is worth a try?Sent from my iPhoneOn Dec 1, 2022, at 12:08 PM, George Williams ***@***.***> wrote:﻿I did install a 2nd antenna.. I used an antenna from extra receiver antennas I had..Sent from my iPhoneOn Dec 1, 2022, at 11:24 AM, mawzthefinn ***@***.***> wrote:﻿
Can you post a picture of your install?
The X12S install can be a pain because you need to install a second internal antenna (or steal the BT antenna)

**Comment by williajgr** [comment]
Ok I put it into x10s and it didn’t work.  Is the x12s killing it or did I just get a bad board?  Where do you suggest I get a new board?  Sent from my iPhoneOn Dec 1, 2022, at 2:16 PM, mawzthefinn ***@***.***> wrote:﻿
It certainly won't hurt to try in the X10S.

**Comment by MIKE-DAILEY** [comment]
If you have a X10 ISRM purchased separately from a X10 then it should be the upgrade ISRM bord.  They usually are marked with felt tip pen with an A or some other making.  If you flash them with the X10 ISRM firmware they will not work.  They need the upgrade ISRM firmware from here [ ](https://www.frsky-rc.com/product/access-upgrade-module-kit-x10-x10s/)

**Comment by williajgr** [comment]
Thank you.  That solved my problem. Really appreciate the help.     JoeSent from my iPhoneOn Dec 1, 2022, at 5:10 PM, Jet_Flyer ***@***.***> wrote:﻿
If you have a X10 ISRM purchased separately from a X10 then it should be the upgrade ISRM bord.  They usually are marked with felt tip pen with an A or some other making.  If you flash them with the X10 ISRM firmware they will not work.  They need the upgrade ISRM firmware from here
