### ISSUE TITLE
Up counting timer correct speech 

### ISSUE THREAD

**Issue by sharonfridman** [FrSkyRC/ETHOS-Feedback-Community#2143]
Hi,

On an up timer, its says the remaining time to the count end. E.g. on 10 minutes up timer it says 9 after the first minute, then  its says 8 after the second minute... And so on.

I want it to say the corrent passing time. 1 after one minute, 2 after two minutes and so on....

Any ideas?

Thanx

**Comment by mawzthefinn** [comment]
If you set Sound to Speech, it should count out on the minute for an Up timer.

**Comment by sharonfridman** [comment]
Well, its count the remaining time to the end

**Comment by bsongis-frsky** [comment]
Perhaps we miss a setting for that

**Comment by i3dm** [comment]
> Perhaps we miss a setting for that

dont think a setting is needed. timer should read out the numbers on the timer display.

**Comment by mawzthefinn** [comment]
Removed duplicate, this is not the same request as the other count up callout issue.

**Comment by jurajjurej** [comment]
Stopwatch function.
The stopwatch only counts down the minutes from the alarm value. (5min-4min-3min...)
How to set them to report 1min-2min-3min...... up to the alarm value?

**Comment by bsongis-frsky** [comment]
I will just make it speak the current value.
In 1.4.5

**Comment by bsongis-frsky** [comment]
Change made. EN prompts have been updated so that they are a little bit quicker. Otherwise the voice was late over the timer counting.
