### ISSUE TITLE
Elevators and Rudders mixer should allow 'reverse' on outputs, for V-Tail planes

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2145]
The Elevators and Rudders mixers doesn't really accommodate V-Tail gliders and planes. 
If you have more than one elevator and rudder channel as you would with a V-Tail plane with elevator and rudder controls, there is no option to reverse specific channels so that a single Elevators or Rudder mixer can output to both halves of the V-Tail. e.g. 

![image](https://user-images.githubusercontent.com/96293240/205346419-b0a3c76a-e400-4e06-8156-6bb08fb5e9ce.png)

by contrast the Free Mix mixer does 

![image](https://user-images.githubusercontent.com/96293240/205346549-4c2c138f-71fd-4790-811a-e44194db77d7.png)

It is possible to work around this by using multiple mixers etc., but it would be so much easier if the Elevators and Rudders also had the option to reverse output channels.

(I can see there could be a discussion regarding whether it is really needed when there is an odd number of output channels, but I suspect the simplest solution is just to always provide it.)

Thanks

**Comment by Jedsters** [comment]
Update: as I say, the Free Mix does allow reverse, however that doesn't work with the respective trims so couldn't be considered a solution.

**Comment by mawzthefinn** [comment]
If you pick V-Tail as a tail type, the mixers come pre-configured to handle this application. You should not need any reversing other than the one in Outputs to make it work. The key is that the lower numbered channel should always be the left one.

You do need to set V-Tail as your tail type for V-tail mixing to work correctly, otherwise you get dual rudder mixing.

**Comment by Jedsters** [comment]
Thanks, I confess I'd set up an X tail and progressed to V-tail, I should have gone back to the start - although that would mean loosing all my setup and having to start from scratch.

**Comment by mawzthefinn** [comment]
And that's why we need templates ;-)

**Comment by mawzthefinn** [comment]
Are you good to close this one off?

**Comment by Jedsters** [comment]
Yes thanks!
