### ISSUE TITLE
Tandem XE Top Screen Sleep Option

### ISSUE THREAD

**Issue by MIKE-DAILEY** [FrSkyRC/ETHOS-Feedback-Community#2147]
Add Tandem XE top screen sleep option for screen ON/OFF in sleep mode.  

Note:  The top screen does not have a dim option so when in sleep it will turn OFF.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/205718736-1509be95-a4a1-49ea-9f5f-edbeba28e0d8.png)
