### ISSUE TITLE
X20 crsf module

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#2148]
Hi updated crsf lua and x20 but still no alt only gps alt and after a while gps speed stops everything else keeps working

**Comment by mawzthefinn** [comment]
What version of ETHOS are you on?

**Comment by Target0815** [comment]
Alt (Baro Alt) is not a normal sensor in the Crossfire CRSF stream, but defined in the ELRS CRSF stream.

As long as @stubugs does not write which equipment (Crossfire or ELRS, which flight controller, which firmware etc.) he is using, there is not much to say about this issue ...

**Comment by stubugs** [comment]
Hi in the title I thought I put crsf module 
Here's other details all crsf running 6.19
Matek 405 wte tried inav 5.01 and inav 6 neither have barometer altitude only gps alt 
 yet when I plug module into another tx barometer altitude is in sensors and works fine 
also with same module in other tx gps speed does not disappear 
X20 running 1.4
And latest crsf lua script

**Comment by Target0815** [comment]
> Hi in the title I thought I put crsf module

I have seen that. CRSF is not a product, but a protocol which is used by Crossfire (the product!) and recently also by ExpressLRS (ELRS). So it is better if you name the equipment correctly. Thanks.

> Matek 405 wte tried inav 5.01 and inav 6 neither have barometer altitude only gps alt

There is no data field for Barometer Attitude in Crossfire's CRSF. Baro Alt is a "unilateral" of ExpressLRS. Probably that is why INAV does not output it.

> when I plug module into another tx barometer altitude is in sensors and works fine

Which other TX?

**Comment by stubugs** [comment]
It's a crsf 868 module other tx is t16s running edge tx

**Comment by Target0815** [comment]
> It's a crsf 868 module other tx is t16s running edge tx

By chance with the Yaapu Script? Then stop this once and read the sensors again ...

**Comment by bsongis-frsky** [comment]
Ethos 1.4.4?

**Comment by Target0815** [comment]
> Ethos 1.4.4?

I have just checked the alt sensor:
Ethos 1.4.4 - missing
OpenTX  2.3.15 - available
EdgeTX 2.8.0 - available

**Comment by stubugs** [comment]
Yes it's 1.4.4
Just tried and experiment
If I disable gps on ifc with inav
Delete sensors and re discover sensors alt sensor  disappears 
The same thing happens with x20 and t16s 
So I think you are correct that barometer alt is not picked up by crsf 868
But x20 calls gps alt 
And t16s calls it alt 
But I suspect they are both gps alt and mislabelled with t16s which causes some confusion
