### ISSUE TITLE
Feature request: More options for trims per flight mode

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#215]
Currently, the only option is for independent trims. However, it would be beneficial to have more control.
![image](https://user-images.githubusercontent.com/17590174/117879352-c7b46f80-b29e-11eb-8867-ba66150fcb38.png)
- Firstly, I'd like to see the + option. With this, the trim in flight mode 1 would be based on the trim of the default flight mode. This would be really useful for things like flaps. You could trim the plane in the default flight mode, deploying flaps goes to flight mode 1, then you could add the extra trim required to keep the plane level with the flaps down.
- Next, it would be great to add an option for flight controllers, that disables and zeros the trims. This would be ideal for stabilised flight modes, where any trim is seen as control input. This also means the trim switches could be repurposed for other functions.

I'm sure there are plenty of other examples. These are just the two that I can currently think of. I think the ability to repurpose trims is a good one. They are used to great effect in models like the e-soar glider setups.

**Comment by MrD-RC** [comment]
@MIKE-DAILEY the second request is not there. The trims screen only allows you to have independent trims per flight mode. This is not the same as setting the trims to 0 and unlatching the trim switch, so that it can be repurposed.

**Comment by MIKE-DAILEY** [comment]
Click Trim mode and then select Disable.

**Comment by MrD-RC** [comment]
@MIKE-DAILEY surely that disables it everywhere, not per flight mode.

**Comment by MrD-RC** [comment]
I was thinking something like this
![ETHOS Trims](https://user-images.githubusercontent.com/17590174/117931732-76849a00-b2f7-11eb-8253-9a4825ba358a.png)
Having this would mean that the **Independent Trim per Flight Mode** could be removed from the **Trims** screen.

I've shown a different option per trim here. Of course, there could be more options.
- **Flight Mode** would be the default setting and set to the default flight mode. This would work as a standard setup currently does. However, this is more flexible than the current _Independent Trim per Flight Mode_ option, as you can select which flight mode to use for the trim.
- **Flight Mode +** takes the trim of the chosen flight mode, and adds the trim of the current flight mode to it as an offset. Any flight mode can be selected, other than the flight mode you're editing. This would cover the first request in my initial post.
- **Value** would allow you to set a value for the trim. Long enter press on this option would allow you to select between: 
1. a value
2. a channel, to allow the use of global variables
3. disabled, to disassociate the trim switch, so that it can be used for other functions
- **Value & Disable** This lets you set a static value for the trim and disassociate the trim switch with the axis; so that the trim can't be altered and the trim switch can be used for different functions

**Comment by bsongis-frsky** [comment]
I would rather see those 3 parameters:

## The trim scope
- **Global** would be the default, it means that this trim value is the model global trim
- **FlightMode** means that the trim is stored into the flight mode, each flight mode can have a different value
- **Global+FlightMode** means that the trim is the global trim + the flight mode trim offset (it means that some flight mode uses - or used - the global trim or it is of no use)

## The trim source
- **Normal** would be the default setting, it means that the trim value is changed by the trim buttons
- **Value** means that the value is defined in the 3rd parameter, the trim buttons are not used, they can be repurposed

## The trim value
- When trim source is "Normal", it is the current trim value (which is disabled)
- When trim source is "Value", you may configure the trim value, it can be a hardcoded value or a channel, or a pot, or any source

**Comment by MrD-RC** [comment]
That sounds awesome @bsongis-frsky

**Comment by mbtohme** [comment]
Why not use something found at Futaba radios?
At each flight mode you can choose if the trim is combined or not. For example: 3 flight modes, low, medium and 3D rates. You want to use the same aileron and elevator trims to all flight modes, but a hi idle at 3D flight mode. You will choose "combined" throttle trim to low and medium flight modes and "separate" to 3d mode. Or a "separate" elevator and aileron trims at flap flight mode to compensate bad tendencies with low flaps and so on....

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/129156295-15847033-61fa-4a38-81c8-2c7114283864.png)

**Comment by loetefix** [comment]
Please also add this in trim mixer

**Comment by MrD-RC** [comment]
I still think this would be better set in the flight modes themselves. For example, if all but one flight mode you want to use the default flight mode’s trim, or in a single flight mode you want to disable the throttle and rudder trim completely for example. This still seems to be a global setting.

**Comment by Ceeb182** [comment]
I suggest that one solution is to consider trims as special Global Variables.

This allows to go even further than the OpenTx functionality :  
- benefit from a wizard to set the basic behavior (Global or FlightMode)
- link or not the trims to "FlightModes" 
- link or not the trims behavior to specific conditions
- customize trim behavior for each case (independent, offset, value, unplugged)
- customize the source of the trim (crossed trims and other atypical operations are then possible)
- customize the trim scale (simple or extended)
- customize the trim step
- set the trim direction
- use a single user interface for trims and global variables

Concerning the user interface, I made some proposals in issue #779.
Watch preferably the videos of the issue #779 on Youtube : ["Special parameters" - Proposal for a new UI to manage Trim and GV](https://youtube.com/playlist?list=PLz2-8nAnjYQBT_i-yPy3jW4Z6QD38jU-f)  

![SP Page 1+2 for SP:Trim](https://zupimages.net/up/21/32/ar4h.gif "SP Page Definition et States for SP:Trim")

**Comment by MrD-RC** [comment]
Is there any movement on this?

Not having the ability to disable trims per flight mode is really starting to hold me back, This is a pretty important feature for FPV, where you don't want any trims sent to the flight controller in stabilised modes. This also frees up the trims for functions like in-flight PID tuning while in stabilised modes.

**Comment by yufasa** [comment]
Hopefully this is not getting stale - as is mentioned we need to be able to disable trims for flight modes where the stabilizer is doing its thing but I want to be able to use the trims when the stabilizer is in "Normal Mode" and I want to trim the control surfaces.

This will free up the trims in the stabilized modes to be used for things like adjusting the Gyro gain. 

If you want to know how I do that in Ethos:
1. Set up your flight modes Normal, Stabilized, Self Level. (currently just using a switch for this but can link to flight modes)
2. Go to Model->Trims and set all the trims to disabled (This is where the problem comes in as it is global and not flight mode specific)
3. Create a Trim Mix (Select Mixer, tap any entry and select "add mix" (or use small “+”), select "Trim" and add after last mix in list)
4. Name it Gyro Stabilized
5. Set "Active condition" to Flight Mode->Stabilized
6. Set the following:
    1. Up = any of the now unused trim switches 
    2. Down = the opposite direction of the trim switch above
    3. Range = 100%
    4. Step = Initially use Custom and set 2-5%, once you get close you can change to “course” to make smaller changes
    5. Set Output1 to your channel that is mapped to Gyro channel to FBL

**Comment by radlouni** [comment]
There has been no update for quite some time now. is the inherited trim feature still being worked on or in the pipeline for 1.5 ?

**Comment by fhpage** [comment]
VAR mixes in 1.5 provides the needed functionality....

**Comment by fhpage** [comment]
Works, just have to  plan carefully because order is key...
Example:

Values              5%
FM1      Equal   5%
sb-       Offset   2%  =>  7%
FM3     Offset   -1%  =>  4%
sc-        Equal     5%
FM4      Normal   -8%
FM5      Unplugged   
FM6      Offset   -2%  =>  -10%   (going to know to skip "unplugged")

**Comment by bsongis-frsky** [comment]
You can choose the "Reference line" where the offset will be applied

**Comment by bsongis-frsky** [comment]
Merged today

**Comment by Ceeb182** [comment]
Interesting!
