### ISSUE TITLE
when displaying channel outputs greater than 6 on the x12s one looses data (no channel name or output percentage)on the screen

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2150]
when displaying channel outputs greater than 6 on the x12s ethos one looses data (no channel name or output percentage) on the screen

**Comment by mawzthefinn** [comment]
Does the channel have a name & mix assigned? Can you take a screenshot and upload (there is a special function which will create screenshots). A screenshot of the Output edit screen, then the display screen would suffice


Tested on 1.4.3 and 1.4.4 on X12S, we are unable to replicate.

**Comment by williajgr** [comment]
one with 5 and one with 6
![IMG_2083](https://user-images.githubusercontent.com/56521075/205455626-7a1f8a75-3bb0-4b6e-b45e-db9127ebb62f.jpg)
![IMG_2084](https://user-images.githubusercontent.com/56521075/205455633-bb7e6370-e03b-4e7f-a219-639f498dcd8b.jpg)

**Comment by mawzthefinn** [comment]
This should work correctly with up to 6 channels, it will run out of screen real estate with 7 or more and just display bars.

It appears your Fonts are out of date. Please use ETHOS Suite to make sure you have the latest SD card and flash contents loaded on your radio.

**Comment by mawzthefinn** [comment]
This is what you should see with the correct fonts loaded:

![image](https://user-images.githubusercontent.com/34381975/205459492-754fb93b-f297-42b8-8cc5-683dafae835a.png)

**Comment by williajgr** [comment]
I have the latest as far as the suite is concerned.  but i know the fonts are not on the sd card they are on the internal flash.  where can i get that font file?

**Comment by williajgr** [comment]
found new fonts.  6 works now but not 7 or 8

**Comment by mawzthefinn** [comment]
Yes, that's correct behaviour as I noted above. For more than 6 channels there's not enough room to fit in the text and bars at the same time without adding an extra-small and unreadable font.

**Comment by williajgr** [comment]
I assume it would be the same on my x10s?  Open-Tx can put 11 on a side.Sent from my iPhoneOn Dec 3, 2022, at 6:50 PM, mawzthefinn ***@***.***> wrote:﻿
Yes, that's correct behaviour as I noted above. For more than 6 channels there's not enough room to fit in the text and bars at the same time without adding an extra-small and unreadable font.

**Comment by mawzthefinn** [comment]
Yes, the X10S has the same screen layout limitations.

**Comment by williajgr** [comment]
it is what it is
