### ISSUE TITLE
Recoloring/Replacing System Bitmaps...

### ISSUE THREAD

**Issue by T3chDad** [FrSkyRC/ETHOS-Feedback-Community#2151]
I have been trying to replace a few of the stock system bitmaps so they better match my selected accent color.

Examples from /sdcard/bitmaps/system:
- usb_suite.png
- sxr_calibration_ok.png
- icon_ethos.png
- gyro_calibration_check.png
- toolbar_background.png

The replaced files have only been recolored...resolution, bitness, etc. are all the same. The files seem to copy and replace fine, but after you turn off the Tx and back on, they're all back to the originals. Tried for both \flash\bitmaps\system and \sd\bitmaps\system. Behavior is consistent between an X20S and X10S Express with Ethos 1.4.3.

![icon_ethos](https://user-images.githubusercontent.com/5139966/205412895-bf9fa27e-9231-44bf-97c9-71775955eb28.png)
![sxr_calibration_ok](https://user-images.githubusercontent.com/5139966/205412896-76d11c44-cf7f-417a-8b8b-e33e9aa38bf0.png)
![usb_suite](https://user-images.githubusercontent.com/5139966/205412897-9a730fed-3ce0-44b7-8372-162893655e97.png)

**Comment by MrD-RC** [comment]
Yep. I've notice this too. It sucks as I wanted to use a custom ETHOS logo.

**Comment by mawzthefinn** [comment]
This will work if you update the files while connected in Bootloader mode. When ETHOS is running it seems to be caching the files and updates them on shutdown.

I tested through multiple reboot cycles.

**Comment by T3chDad** [comment]
Confirmed.  Thank you Mawz.

**Comment by MrD-RC** [comment]
Nice find 👍🏻

**Comment by bsongis-frsky** [comment]
> This will work if you update the files while connected in Bootloader mode. When ETHOS is running it seems to be caching the files and updates them on shutdown.
> 
> I tested through multiple reboot cycles.

Not exactly! This disk is read-only. Firmware is run from flash and it is not possible to write, while we execute code from it!
