### ISSUE TITLE
Unreal sensor lost 

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2152]
Hello, @bsongis-frsky 

I'm glad you noticed the error and reopened #2086 issue, but i saw a strange behavior of telemetry, which can not be.

The yaw sensor was lost. At the same time, Pitch and Roll sensors were updated without delay.
This is not possible, since all three sensors come in one package. I'm not sure if this is a CRSF problem. 

When using R9, I also often heard about lost sensors, but I didn't have the opportunity to see which one.
![screenshot-2022-12-03-16545](https://user-images.githubusercontent.com/1244228/205416689-bf69c429-72b5-461a-95c1-0f0870ebfe8f.png)

Tandem X20 (Ethos 1.4.4 Flex, Elrs module 2.4, 500 framerate, 1:2 telemetry ratio)

**Comment by Target0815** [comment]
Can you set your ELRS module / RX to version 3.x? I do not have your Yaw problem with it.

Also the Flight Mode is displayed correctly with me (Arduplane 4.3.1).

**Comment by r1000ru** [comment]
@Target0815, i am use 3.0.0 elrs firmware. Flight mode is correct, becouse my FC (inav 6-rc1) for testing does not have calibrated accelerometer at screenshot moment.

Receiver was connected to tx about 30min, before this bug showed itself.

**Comment by mawzthefinn** [comment]
Hmm, if the yaw sensor exceeded the bounds of the sensor definition, it could be lost (invalid data = lost sensor). That is consistent with the screenshot showing a much larger value than the other two sensors.

The displayed value is 179.9 degrees, is it possible that the sensor is sending data in a format with a value > 180 degrees. The max valid Yaw is almost assuredly +/-180 degrees.

**Comment by bsongis-frsky** [comment]
I have assumed that a correct value should be inside the range [-180°:+180°], isn't it true?

**Comment by Target0815** [comment]
I was about to ask why the value is given in radians. Then I see that you can switch to degrees. But if the decimal places are set to 0 or 1, the output is always 0 degrees. 

This should also be a bug ...

**Comment by bsongis-frsky** [comment]
The value is given in radians by the sensor, with 4 digits

**Comment by Target0815** [comment]
> The value is given in radians by the sensor, with 4 digits

Yes, that is correct. Now please try the following:
- sensor edit
- change to degress, 0 or 1 decimals

The displayed value is not correct.

Now change the sensor to radians again. The 4 decimals that were there before cannot be entered anymore, only max. 3 digits are possible.

This is already 2 errors.

The display in radians may be because the value is transferred in this way, but tell me honestly, can you immediately imagine something under the value 3.1416rad? Not me, for me 180° would be logical and immediately clear.

**Comment by bsongis-frsky** [comment]
My mistake, I implemented the conversion the wrong way

![image](https://user-images.githubusercontent.com/50834778/205906137-5c758dd8-d74e-43c7-b6a3-066d7f9bf321.png)

**Comment by bsongis-frsky** [comment]
4 digits precision allowed everywhere (the maximum was 3 before)

![image](https://user-images.githubusercontent.com/50834778/205908805-ae595e16-f853-4c8b-9a82-ab5bb87030b0.png)

**Comment by bsongis-frsky** [comment]
Degrees with 1 digit used as default unit for the 3 attitude sensors:

![image](https://user-images.githubusercontent.com/50834778/206026860-b8f9723c-ab15-47a9-a6fe-027b9d9118de.png)
