### ISSUE TITLE
x20 to x18

### ISSUE THREAD

**Issue by EthosUser** [FrSkyRC/ETHOS-Feedback-Community#2153]
Hello,
I have an X20, if I buy an X18, is it possible to copy my model files from the X20 to the X18 and keep my model settings?
Thank you in advance for your help.

**Comment by Dsrenger** [comment]
Yes, that's possible.

Be aware that you need to remap functions, if you use an input, that is not available on the other radio.

E.g. the red slider ob the X20 or the trim T5 and T6 that are only on the X18.

I am not a Frsky dev, but my guess is, that the developers prefer questions like this on the different forums (e.g. rcgroups or the Engel forum)

GitHub is usually for issues, bugs and enhancements.

**Comment by EthosUser** [comment]
Thank you for your information and sorry for my question.
I didn't know which forum to ask it to.

**Comment by mawzthefinn** [comment]
Usage questions are best asked on the RCG and Engel forums, bigs, odd behaviours and feature requests are best asked here.

You can swap model files between any ETHOS radio, so long as the radio you are copying to has the same or newer version of ETHOS on it. You do need to check your model afterwards to ensure that any control differences are addressed (X20 lacks T5/T6, X18 lacks the front slider, and so forth).
