### ISSUE TITLE
TD-R18 servos not working when in HF-settings output 1 - 18 is selected

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#2154]
The transmitter is a X20s with firmware 2.2.2 and Ethos 1.4.2, the receiver is a TD-R18 with firmware 1.0.7

In the HF-settings I set the servo output from channel 1 - 18 (as it is a 18ch Receiver) and bound the receiver without any error.

Telemetry is working, I can see full bars on 2.4 Ghz and 868 Mhz in the top right corner of the display and the receiver is in normal operation mode according to the LEDs.

But I can connect a servo to whatever servo output and it won't even move a bit, not even when plugged in.
Voltage is fine on the servorail on both sides.

Now comes the interesting part, I did a reset of the receiver and made another new fresh model and I can use a servo just like it should be on channel 1.
If I change servo output from 1 - 17 everything works fine too, but if I chosse output 1 - 18 in HF-settings NONE of the servo ouputs work.
This problem also occurs for 1 - 19/20/21/22/23! When it comes to 1 - 24 it works again.

**Comment by mawzthefinn** [comment]
I'm not sure those settings should even be available for ACCESS/TD/TW

the only channel range settings of value are 1-8 (1 frame for all channels), 1-16 (2 frames for all channels) and 1-24 (3 frames for all channels).

Note the TD R18 is an 18 port receiver, it listens on all 24 channels.

**Comment by bsongis-frsky** [comment]
Only 8/16/24 will be allowed in 1.4.5
