### ISSUE TITLE
Bluetooth - Selection of Trainer or Audio mode in general settings - why not in model settings and why only one possible

### ISSUE THREAD

**Issue by onki69** [FrSkyRC/ETHOS-Feedback-Community#2157]
Hi,

I am using Bluetooth often in audio mode that is using a different module than the trainer feature.
If I wish to use Audio I have to enable this in the general (wireless) menu.
AFAIK this is a general parameter. Why can't I select the BT option in the model?
Is there a technical reason why Bluetooth can only be used either for Trainer or audio.
There are some situations that I need both (trainer and audio) in a model as I want to connect a wireless trainer through BT as well as my BT headset.

Regards Onki

**Comment by Target0815** [comment]
Normally, Bluetooth can only actively transfer data for one connection. It is probably also the case that a different Bluetooth profile is used for the two possibilities,

**Comment by Dsrenger** [comment]
But isn't the trainer Bluetooth module separate from the audio module?

The X20 has the trainer module but not audio.
The x20s has additionally the audio module. So I assume they are 2 different pieces of hardware.

**Comment by Target0815** [comment]
> So I assume they are 2 different pieces of hardware.

That could be, just as well it would be possible that only one Bluetooth module is installed, which has both options.

**Comment by onki69** [comment]
The X20 was the first FrSky transmitter that could do BT audio at all. Therefore a separate BT module is used. This is why a X20 and a X20s is available as the S-suffix indicates the BT audio capability. Same with the XE and the Twin Lite.
This is why I don't understand that only one selection is possible.
From my understanding there is no technical limitation to support both at the same time. It might just be a legacy thing as this was not possible with older transmitters.

The only thing I don't know is what kind of signal the BT audio module gets from the µC. The easy but poor solution is an analog audio signal. The technical better solution would be a digital audio signal to get better quality and lower latency as an additional coding/conversion is not required.

**Comment by bsongis-frsky** [comment]
Refactoring has been done on Bluetooth. There is no choice in Radio / System / Wireless. Instead we have moved it to screens where Bluetooth can be used (Trainer / Telemetry / Audio). It avoids to force the user to open 2 different menus just for enable a Bluetooth function. Also it will be possible to have BT Telemetry on one model, BT Trainer on another and BT audio on a third one.

On Hardware side the Bluetooth functions are exclusive. Ethos cannot change that.
