### ISSUE TITLE
feature request : trim mixer with 3 values or flightmode dependent

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#216]
The mixer trim is a realy nice feature. i use it as an digital potentiometer for throttle (rpm) and gyro value on my helicopter.
i use 3 of them (for every flightmode one). it would be nice if the trim mixer can store 3 values that can be selected per switch. or if it can store one value per flightmode. a checkbox to select flightmode dependent would be nice.

**Comment by pld74** [comment]
Check in 1.0.6. They added some of the functionality you're recommending.

**Comment by loetefix** [comment]
No, there are only changes in the "normal" / default trims. I mean the MIXER called trim. These are mixer lines that work like a digital potentiometer wich can be dec and inc by an attached switch/logical switch . I use it for throttle value on helicopter. At the moment i have to use 3 of them . For every flightmode one line that "store" one value. If the line were flightmode depend i only need one line.

**Comment by loetefix** [comment]
Will a flight phase dependent trim-mixer come in the future?

**Comment by bsongis-frsky** [comment]
Merged into #577
