### ISSUE TITLE
X12S Emergency mode when using lua scripts on the external Modules

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2160]
External modules in X12S the XJT and R9M and RFD900 TXMOD.
And i can bind and use with servo output and with rssi and Smart Port Lipo Voltage Sensor working find with all modules

but as soon i just added some scripts yaapu passthrough all the scripts work fine with the internal isrm 2.4

but if i turn the internal isrm off and power on the external R9M or XJT radio goes in to emergency mode

its like when the scripts start poll the sport it goes to emergency mode
i did some testing with this script which shows the Lua Sinus with some simple polling for sensors still goes to emergency mode on all external modules but if i turn off the external and turn on the isrm internal module it works fine with all scripts

here is a simple lua script that poll for Sport sensors  
[yaaputest.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10149774/yaaputest.zip)

**Comment by Target0815** [comment]
I have tested the script with a R9M Lite Pro module. It runs without problems on an X18S with Ethos 1.4.4.

**Comment by bsongis-frsky** [comment]
Reproduced

**Comment by bsongis-frsky** [comment]
Fix found
