### ISSUE TITLE
X18s: bug in Gyro calibration menu prevents user from "right" calibration

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2161]
Hi,

I received my X18 this weekend and assume that a "new" user would not be able to calibrate the gyro:

As soon as you enter the calibration menu, you are prompted to hold the transmitter in a certain position and confirm "the button".

The focus is already on the next button
Alternatively, there is the Previous button.

The user now will hold the corresponding position and confirm "Next" until the complete routine is finished.

As a result, no calibration has taken place.
The system seems to use standard values so that at least a range of about +/-30 degrees around each axis can be used.
The user without experience thinks that this is inherent in the system, the error is not noticeable for him. 

**You can "cheat" the procedure with knowledge of the X20 operation.**
As soon as you are asked to take place a position and press the button:
Deactivate the Next button via the rotary "Back ONCE",
 so that no button appears to be active (under the X20 the "confirm operation" button would now be in focus).
Now confirm with Enter, move the rotary forward once (focus now on Next) and confirm.

**Only this "hidden functionality" allows you to read the necessary calibration value and match to the corresponding position !**

Repeat this procedure until the end and you can use the transmitter IMU up to the vertical.

It seems as if the "confirm" button of the X20 menu was omitted, but its functionality was retained in the procedure.

Personally, I would prefer to combine the "readout" procedure (via confirmation button) and the jumping to the next menu (via "next" button).
Even in X20 Menue
In my opinion, the user expects a "one step"/"one click" procedure per transmitter position,so readoutshoul be initiated by pressing next.

regards
Udo

**Comment by bsongis-frsky** [comment]
> "As a result, no calibration has taken place"

Are you sure?

**Comment by strgaltdel** [comment]
Yes, it doesn't matter if you move the tx or not:
you can leave the Tx on the desk in "level" attitude, pressing "next" all the time, same result:

Gyro is available between +/- 30 degree, so you get some sort of gyro application even in case user don't perform calibration.
you have the same result in case you move tx in the ordered attitudes. (Ethos 1.4.3),
 **it doesn't change anything if you move your tx or not !**
You're getting a Gyro range between +/- 30 degree.
(and so most users won't recognize it's a bug)

In case you want gyro range between a greater range you'll need the "special" procedure  

I have a X18se but don't think it makes a difference to an X18s

**Comment by bsongis-frsky** [comment]
Agreed, it is not obvious and very practical. I would also prefer pressing "Next ... Next ... Next ... Next ... Confirm"

**Comment by bsongis-frsky** [comment]
Done for 1.4.5
