### ISSUE TITLE
How to add/create a sensor using LUA

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2162]
Under OpenTx i created a Sensor with
local LipoNr = 6
setTelemetryValue(0x5100, 0, 17, LipoNr, UNIT_RAW, 0, 'LiNr')

and i updated always with
setTelemetryValue(0x5100, 0, 17, LipoNr)
i need this because i want to log this value in the log-file

how can i do this under Ethos

is there something like the suggestion in issue [https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1141](url)

local sensor = model.addSensor({name=translation("mySensor"), unit=UNIT_VOLTS, decimals=2})
sensor:value(20)
print(sensor:value())

Thanks a lot

**Comment by bsongis-frsky** [comment]
Right. This is in our roadmap. We will use the same way to create a sensor than `createTimer()` and `createCurve()`

**Comment by Storchy1** [comment]
It Is important, do not close
