### ISSUE TITLE
Brazilian Portuguese audio are not available in 1.4.4 to download from Ethos Suite

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#2164]
Hi,
Release 1.4.4 is now available to have Brazilian Portuguese audio language, but Ethos Suite v1.4.4 does not display the option to download them to the radio.

**Comment by bsongis-frsky** [comment]
pb audio pack is available in github downloads now, and it will be proposed automatically in Ethos Suite 1.4.5

**Comment by robertoalmeida** [comment]
Where can I find this pb audio pack download?
I searched and didn't find it.

Supposed to appear here? https://github.com/FrSkyRC/ETHOS-Feedback-Community/milestone/42

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.4.4
