### ISSUE TITLE
Ethos Suite 1.4.4 issue, blank app window

### ISSUE THREAD

**Issue by mikeschuster** [FrSkyRC/ETHOS-Feedback-Community#2166]
Ethos Suite 1.4.4
macOS 12.6.1
iMac (24 inch, M1, 2021)

I installed and launched Ethos Suite 1.4.4.

The app's window is completely blank.

I reverted to 1.4.3.

**Comment by yak-54** [comment]
what radio ?

**Comment by mikeschuster** [comment]
I have an X20S.

Radio was not connected via USB when I installed and launched 1.4.4.

IMO it seems radio is not relevant to the problem.

**Comment by mikeschuster** [comment]
Maybe the fact that no radio was connected is the source of the problem?

Note when I use Audio Tool to create .wav no radio is connected.

**Comment by Nicholas-Luoyi** [comment]
Sorry. There is something wrong in the installer for Mac.

**Comment by Nicholas-Luoyi** [comment]
A new installer has been uploaded. Please retry and close the issue if it is OK now.

**Comment by mikeschuster** [comment]
Yes, problem solved, thank you!
