### ISSUE TITLE
Radio Connection is not detected

### ISSUE THREAD

**Issue by radlouni** [FrSkyRC/ETHOS-Feedback-Community#2167]
I have been always able to connect my X20S to Ethos Suite on my windows 11 PC, but suddenly after updating from 1.4.3 to 1.4.4 i cannot connect anymore. When i plug in the X20S, i am prompted on the X20 for the connection type and i chose Ethos Suite, the my PC sees both, the flash and the SD card, but there is no connection to the Ethos suite. I am on bootloader 1.4.3 and firmware 1.4.4. I have windows 11 with latest updates. Any suggestions ?

**Comment by Wolepo** [comment]
Try switching on the transmitter by holding down the Enter key. This will bring you into the Boorloader mode. Then connect the transmitter to the PC with the USB cable.

**Comment by radlouni** [comment]
> Try switching on the transmitter by holding down the Enter key. This will bring you into the Boorloader mode. Then connect the transmitter to the PC with the USB cable.

Same thing, I tried that, and the suite is non responsive at all.

**Comment by radlouni** [comment]
> Did you run windows updates recently? This could be a case of Windows updates breaking drivers.
> 
> Re-installing Suite manually in that case should solve.

I did reinstall the suite, did not help. I do suspect its a windows update breaking drivers. Where can i get a fresh driver to install ?

**Comment by mawzthefinn** [comment]
Re-installing Suite should reset any broken drivers. Not sure what could be the problem then.

**Comment by strgaltdel** [comment]
any messages in device manager which points towards a specific driver ?

**Comment by radlouni** [comment]
> any messages in device manager which points towards a specific driver ?

in device manager, I can see the X20s recognized as a libk device

**Comment by strgaltdel** [comment]
How did you install libusbk , via zadig ?
Then i would  suggest to repeat the driver installation

**Comment by mawzthefinn** [comment]
Reinstall with Zadig, Zadig-installed drivers regularly get broken by Windows Updates

**Comment by radlouni** [comment]
> 

Thanks for the help guys, but reinstalling the drive through Zadig did not help. I just dont know what the issue is, i even used a different cable. The suite is totally non responsive. When I Launch the suite without the TX connected, I can see the "Ethos" and "Model Manager" tabs under radio showing "Radio Connection Not Detected" message. Then I would connect the TX and nothing changes at all, its like the suite is non responsive at all. Windows explorer detects the SD card and the flash drive. Could this be an issue with the suite ?

**Comment by mawzthefinn** [comment]
I just checked Device Manager and I do not have libusbk drivers anywhere.

The X20 shows up as a USB Composite Device and that's all.

Perhaps the libusbk drivers are stealing the X20's connection and preventing ETHOS from seeing it

**Comment by radlouni** [comment]
> 

how to install USB composite driver ?

**Comment by mawzthefinn** [comment]
The USB Composite Driver is a built-in Windows driver that is installed if another driver doesn't bind to the device.

**Comment by yak-54** [comment]
yep its windows has been replacing drivers had the same issue this week after an update by windows

**Comment by yak-54** [comment]
> ![image](https://user-images.githubusercontent.com/33883068/206000382-83b58c04-55c4-4f13-82ee-a89dee61775b.png)

thats the wrong driver it should be mass storage device
i had this issue this week with X12S
![2Untitled](https://user-images.githubusercontent.com/9161926/206084551-24148fd0-4c72-4648-aec9-fe6bf9daa681.jpg)

**Comment by radlouni** [comment]
was able to fix it, i selected the driver manually, the correct driver was "USB Input Device"
