### ISSUE TITLE
Request New Layout for Horus...

### ISSUE THREAD

**Issue by T3chDad** [FrSkyRC/ETHOS-Feedback-Community#2169]
Please add another layout that has trims displayed, but with both sides being large widgets.  Example screenshot attached.

![layout_request](https://user-images.githubusercontent.com/5139966/206041547-bc0224ad-7fee-4cdb-b9e4-f4bfd2e95a06.jpg)

**Comment by yak-54** [comment]
yes i do miss this one on my X12S 
but with all trims and 6 positions pot and sliders
![Untitled](https://user-images.githubusercontent.com/9161926/206081178-a4e4cb24-b8cc-4c2b-82a6-e9609bac60e6.jpg)

**Comment by koakumaping** [comment]
need +1

**Comment by yak-54** [comment]
if you cant get it to fit just delete bottom menu its waist of screen space
![screenshot-2022-12-07-67084](https://user-images.githubusercontent.com/9161926/206119451-7af5e35c-ae4e-45cc-b26f-7e697fcff79e.jpg)

**Comment by T3chDad** [comment]
@yak-54 - Please open new issues for your requests.  Other than being a general UI, they are separate and unrelated to the original issue/feature request.

**Comment by bsongis-frsky** [comment]
This one?
![image](https://user-images.githubusercontent.com/50834778/206525092-b8a7ccc4-8a46-41ff-9019-cbcd6483966a.png)
![image](https://user-images.githubusercontent.com/50834778/206525128-52538d78-62bb-46f4-8a43-dd321a34354d.png)

**Comment by T3chDad** [comment]
Yes please.
