### ISSUE TITLE
X20 v1.0.5 - The 'us' values of the 4 channels from the 2 pots are constantly fluttering up and down.

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#217]
This is only on the Throttle / Rudder and Aileron / Elevator controls.

These values on my X10s are stable.

Because I use the throttle stick to invoke 'Landing mode' this intermitantly causes the TX to call out "Landing - Cruise - Landing - Cruise over and over again.

Is this likely to be faulty pots, or a software issue please?

**Comment by bsongis-frsky** [comment]
What are the values you can see when the stick is centered?

**Comment by KenLong51** [comment]
The values fluctuate between 1499 and about 1501 - not a lot, but as I say the X10 does not do it.

If if I change the landing mode to switch SA it does not do the constant mode name callouts - My theory is the gimbals are faulty.

I have a 16 seconf video, but at 29mb it is too big to attach. Is there any other way that I can get it to you please?

**Comment by bsongis-frsky** [comment]
I don't need a video
The range 1499 - 1501 is not so big, I doubt that your servo moves!

**Comment by KenLong51** [comment]
It is not a servo that is moving - the throttle stick position is used to trigger a logic switch whch is used to enter landing mode.

As you will note from my previous comment, if I use switch SA, instead of the throttle stick, to trigger the Logic Switch it works fine.

**Comment by bsongis-frsky** [comment]
If you are at -0.01% it's < 0% ...

**Comment by KenLong51** [comment]
My comparison is <80%.
I have done yet another calibration and I am wondering if it has helped - I will keep you informed.

**Comment by KenLong51** [comment]
No re calibrating didn't help, it did it's alternating call-outs again this morning.

NEW INFO: It is only the call-outs that are alternating NOT the actual flight modes! The flight mode text stays as Landing and there is no other movement in the controls screen - the X20 just plays Landing... Cruise... Landing.. Cruise...  several times which is coming from Special Functions to Play a Track when a Flight Mode is 1, 2 or 3

It does seem worse if you slowly pull the throttle stick down to invoke landing.

**Comment by bsongis-frsky** [comment]
I think your flight mode is also always changing.
But you cannot see it on screen, the LCD refreshes at a lower speed than the mixer (and channels)
You should not compare an analog to 0% it moves very fast from -0.001% to +0.001% ...
