### ISSUE TITLE
FP2CH8 - FP2CH6 - FP2CH4 lua script for X20S

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#2170]
Hello 
I have a problem to configure a FP2CH6 with a micro receiver (R-XSR) using A X20S transmitter.
1.4.4 Firmware and Last for the receiver.
Trasmitter and receiver are connected properly.
Now in RF SYSTEM -> SET I need to assign the channels in the DP2CH6 extender but is not possible.
Any suggestions?
Thanks

**Comment by mawzthefinn** [comment]
As far as I'm aware, these are just FBus/S.Port hubs, not programmable at all and not PWM converters.

They're intended to chain FBus servos and ADV sensors, so you can't assign channels on them, channels are assigned on the Servo side.

**Comment by mawzthefinn** [comment]
Closing off, these are not programmable devices
