### ISSUE TITLE
Corrupted Display of Switch Positions

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#2171]
With my Horus X10S Express and ETHOS 1.4.4 I observed some strange behaviour in the logical switch menu, w.r.t. the indication of switch positions.

Here is a simple LS, which is FALSE (NB the top left corner of the first screenshot).
![screenshot-2022-12-07-43333](https://user-images.githubusercontent.com/22352021/206165326-ef483f34-6946-446c-9590-a3ecd93b4124.png)
![screenshot-2022-12-07-43356](https://user-images.githubusercontent.com/22352021/206165697-244b456e-1780-4239-ac42-ff90101422c7.png)

The same switch when TRUE.
![screenshot-2022-12-07-43346](https://user-images.githubusercontent.com/22352021/206165555-5c7473ad-4db2-49fb-8fc8-15b6e14d6218.png)
![screenshot-2022-12-07-43425](https://user-images.githubusercontent.com/22352021/206165806-f7b4126d-c935-4561-9820-ecf4e39850d6.png)

**Comment by Wolepo** [comment]
A further error from a converted file from X20 to X10S Express:
![LS](https://user-images.githubusercontent.com/90325526/206172881-ee19ee6f-920f-49ed-9a2f-5c9904de4a52.jpg)

**Comment by Hartinger** [comment]
In my case the file had not been converted, it was rather generated on the X10S Express.

**Comment by Wolepo** [comment]
In my own models, the displays in the overview (x10S Express) are clean. If you open an LS, the number is followed by a -. In the overview, the ~ is displayed as ≥.
![Übersicht](https://user-images.githubusercontent.com/90325526/206178379-80d6bd7a-116b-4a15-8eb5-c6910adb78bd.jpg)

**Comment by mawzthefinn** [comment]
I'm seeing the same behaviour, X20 converted file on X12S-ISRM

**Comment by kenumis** [comment]
Probably the same problem with displaying symbols and characters on my X10. Happened after updating to 1.4.4
(red world in pictures are in the correct format)

![A](https://user-images.githubusercontent.com/70693571/206283933-6cc03ebb-85f4-4381-9460-1d04b7573d2f.png)
![B](https://user-images.githubusercontent.com/70693571/206283936-314a73ec-28e6-4b23-8dcb-5affcb61c5ca.png)
![C](https://user-images.githubusercontent.com/70693571/206283938-9014ae0e-6b47-4947-8977-4fb04907f6e3.png)

**Comment by bsongis-frsky** [comment]
I think it is the font!

**Comment by bsongis-frsky** [comment]
[Uploading fonts.zip…]()

**Comment by STC148** [comment]
with the fonts the problem seems to be solved

**Comment by bsongis-frsky** [comment]
Ok then I need to update the uploads from 1.4.4

**Comment by Hartinger** [comment]
I can confirm that the problem is fixed with the new fonts.

**Comment by bsongis-frsky** [comment]
I have added the fonts to the 1.4.4 release, you may update with Suite now
