### ISSUE TITLE
GMT offset for system clock off with Ethos 1.4.4

### ISSUE THREAD

**Issue by dap35** [FrSkyRC/ETHOS-Feedback-Community#2173]
I have an X20S running 1.4.4 and a GPS-ADV attached to an SR6 (both with Current FW as of today).
I am in US EST timezone which should be GMT-5.  If I have the option set on the system clock to "Auto Adjust from GPS", the system clock is off significantly unless I change the TimeZone to GMT-11.    

In checking the GPS Clock under telemetry, the correct time is displayed.

![IMG_3908](https://user-images.githubusercontent.com/19751814/206270190-b42bf761-5610-4497-816f-42848ec1ce82.jpeg)

**Comment by bsongis-frsky** [comment]
At which time have you done the test? Your photo shows 13:49, is it right?

**Comment by bsongis-frsky** [comment]
In 1.4.5 only the timezones defined here will be allowed:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
And I have learnt it goes up to +14:00, the maximum was +12:00 before

**Comment by dap35** [comment]
The time is correct in the photo, but I had to change the GMT offset to -11 hours instead of the -5 hours that it should be.
When I look at the telemetry output from the GPS Clock, it is always correct (13:49 in this case) and is not impacted by what I put in as GMT offset.

**Comment by bsongis-frsky** [comment]
This is strange, the display of GPS Clock uses the timezone! Would you mind check it again?

**Comment by dap35** [comment]
I was inside at the time, but it looked like I was getting GPS clock.  But I will take the plane outside and retest today.

**Comment by dap35** [comment]
I moved outside and verified that I am getting GPS signal and confirmed that the clock display and GPS Clock telemetry do use the same system setting for GMT offset.   It is still off by two hours if I use the correct GMT offset (-5) for my timezone (US East).  So if I change the offset to -3 hours it appears to be correct.
I took this at 11:27am:  
![IMG_3919](https://user-images.githubusercontent.com/19751814/206512255-d298f87d-eccd-409a-94eb-1e07a295f812.jpeg)
![IMG_3921](https://user-images.githubusercontent.com/19751814/206512320-35949c2b-c445-433e-9052-afcdb4de45dd.jpeg)
Then I changed the GMT offset to -3 and powercycled both the RX and TX.
![IMG_3922](https://user-images.githubusercontent.com/19751814/206512699-7691d8c1-6639-4de1-b84d-dbfbd4d9ed70.jpeg)
![IMG_3923](https://user-images.githubusercontent.com/19751814/206512872-359490b4-8ec3-4d1d-b555-583588ee3dcb.jpeg)

**Comment by bsongis-frsky** [comment]
What is your GPS Sensor?

**Comment by dap35** [comment]
I am using the FrSKY GPS-ADV, flashed with GPS_ADV_1.7.frsk.  The RX is the Archer SR6 flashed with 2.1.10 and the telemetry port is configured as s.port.  I have also tried F.Port and FBUS, but that doesn't seem to make a difference.

**Comment by bsongis-frsky** [comment]
After loosing hair on this one, it seems it's rather a problem inside the GPS. The Old S.Port GPS is OK.
I forward the issue to the right team.

**Comment by FrSky-GX** [comment]
@dap35     Have you disabled the SXR function of SR6? If not, can you try again with this function setting off.

**Comment by dap35** [comment]
I did retest today by disabling the SXR function as well as flashing the GPS-ADV back down to v1.6.  Neither seemed to resolve the issue.
