### ISSUE TITLE
Special characters missing 1.4.4

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2174]
Special characters missing

TANDEM X20S, TANDEM XE
Version: 1.4.4.EU
Keyboard: QWERTZ

Problem:
?123 keyboard level special characters missing

Ä - missing (upper case letter)
Ü - missing (upper case letter)
ä - missing (lower case letter)
ö - missing (lower case letter)

Best regards Eugen

**Comment by bsongis-frsky** [comment]
You may reach them with the rotary encoder! Some were missing and have been added to 1.4.5
