### ISSUE TITLE
Request New Screen Layout for Horus X10 X12

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2175]
Can we Add new screen that show S1 S2 LS RS trims 

![Untitled](https://user-images.githubusercontent.com/9161926/206310385-4589ff7c-b6a0-4d49-877f-a0f55c741eee.jpg)

![3Untitled](https://user-images.githubusercontent.com/9161926/206310461-215285ce-2c99-4f3e-b0b9-8aac458dafe8.jpg)

If need to make room on the screen delete bottom screen menu as the Horus does not support Touch screen

![screenshot-2022-12-07-67084](https://user-images.githubusercontent.com/9161926/206304407-e21cbe3b-d31d-4f49-9025-f8cef6fc6c2c.jpg)

**Comment by bsongis-frsky** [comment]
Delete stale
