### ISSUE TITLE
lua: missing FONT_XL definition on X18

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2176]
Hi,

X18: FONT_XL returns nil,
so we have a big gap between "large" and "XXL" fontsize, especially on the smaller X18 display i do miss the size

X20 is OK !

	lcd.font(FONT_XS)
	lcd.drawText(10, 1, "lcd.font(FONT_XS)    "..tostring(FONT_XS)	)
	lcd.font(FONT_S)
	lcd.drawText(10, 18, "lcd.font(FONT_S)   "..tostring(FONT_S)	)	
	lcd.font(FONT_STD)
	lcd.drawText(10, 40, "lcd.font(FONT_STD)   "..tostring(FONT_STD))
	lcd.font(FONT_L)
	lcd.drawText(10, 70, "lcd.font(FONT_L)   "..tostring(FONT_L)	)
	lcd.font(FONT_XL)
	lcd.drawText(10, 105, "lcd.font(FONT_XL)   "..tostring(FONT_XL))
	lcd.font(FONT_XXL)
	lcd.drawText(10, 150, "lcd.font(FONT_XXL)   "..tostring(FONT_XXL))

![xl](https://user-images.githubusercontent.com/20392683/206405779-e2425dd2-3f3c-48cc-8b63-27dc9ae0fc35.png)

**Comment by bsongis-frsky** [comment]
You may load any font in the firmware. But you are missing a tool to build a font, it should be part of Ethos Suite soon!

**Comment by bsongis-frsky** [comment]
In addition, XL font will be standard in 1.4.5
