### ISSUE TITLE
Yaapu gets stuck on data screen

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2177]
Not sure if this is a yaapu or ethos x20s issue. .  when I use the scroll up on the yaapu screen to see the line data it won't scroll down.  even if i switch models and come back, it is still stuck in the data screen. the only way to get it to return to the main screen is to shut the transmitter off and turn it back on.

**Comment by yaapu** [comment]
hi, not sure I understand what the line data is.
...but to switch from main screen to status text screen you need to tap on botton half screen, same to switch back

**Comment by williajgr** [comment]
solved
