### ISSUE TITLE
° Symbol Displays as ↓ in FONT_L

### ISSUE THREAD

**Issue by T3chDad** [FrSkyRC/ETHOS-Feedback-Community#2178]
The degree symbol ° is shown as ↓ when using FONT_L in LUA.  All other fonts appear to display the symbol properly.  It does not matter if the symbol is defined explicitly in a literal LUA string or if you're using the Source:stringUnit() method established in the sensor config.  This only happens on my X10S Express hardware. Does not happen in the simulator.  I copied the font files just to make sure.

**Comment by mawzthefinn** [comment]
Try with the new font set posted in #2171

**Comment by T3chDad** [comment]
Confirmed! Thank you.
