### ISSUE TITLE
X 20 - Virus, Worm and Trojan detected on supplied SD card!

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#218]
The first time I connected my new X20 to my PC to load v1.0.5 my PC highlighted the following on the SD card and took action against them.

Trojan:INF/Ramnit.A in D:\autorun.inf
Virus:Win32/Ramnit.A
Worm:Win32/Ramnit.A

Very concerning.

Although the X20 seems OK now, I plan to use a new SD card and downlowd all content again.

**Comment by bsongis-frsky** [comment]
Please look at the zip, there is no such file!

**Comment by KenLong51** [comment]
*** These files did not come from the ZIP file - They were on the supplied SD card within the X2o.
