### ISSUE TITLE
Running EU 1.4.4 not able to rebind my Tinyhawk2 or 3 anymore wit XJT lite 2.1.0

### ISSUE THREAD

**Issue by krokusvej** [FrSkyRC/ETHOS-Feedback-Community#2180]
I was flying with my Tinyhawk 2 last sunday then I updated to 1.4.4 EU x20s it was working on 1.4.3 last sunday, but I bind it lang before can't remenber what version I had wen I did. I let it out and bind it to and Open TX with multimodule. Start this week I got the Tinyhawk 3 and could not bind that to my XJT 2.1.0 with D8 I tryed also rebinding the Tinyhawk 2 and that did also not work. Tryed down grading XJT to 1.1.0 that did also not help. Any ideer why ? I can bind both to the open tx with multi irx4 with D8.

Hope it's a small ups to sort out or explane why it was working earlyer and not now.

**Comment by bsongis-frsky** [comment]
If you downgrade Ethos to 1.4.3 it works again?

**Comment by krokusvej** [comment]
I have tryed with 1.4.1 and 1.4.3 It can't bind to my XJT lite module in back of my X20S

but I bind it lang before can't remenber what version I had when I did.

**Comment by krokusvej** [comment]
What Kind of info do you need more than what I have mentioned.

Haw can I help? Video of sequence of binding if so where should I have focus.

**Comment by krokusvej** [comment]
I have now tryed installing the 1.4.5 Flex firmware and I am still not able to bind neather of the Tinyhawks 2 or 3. could it be that I need to downgrade firmware in radio to a version before Lua was introduced or before multi module was introduced. I'm eager to go flying with the quads.. Please anyone have an ideer to solve this?

**Comment by krokusvej** [comment]
Just received IRx4 multi modul and that binds fine to the quads on the X20sS V1.4.5 Flex. So why it's not working on the Frsky XJT modul I can't say but for now I have solved my problem with the binding.
