### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2183]
To fine-tune the sound a little, it would be better to add the Trebles and Bass settings.
![tr-bs](https://user-images.githubusercontent.com/85956904/206647898-72d13f61-8e83-4e39-9233-75c88638e396.png)

**Comment by bsongis-frsky** [comment]
I am not sure it's a good idea to do signal processing on audio, it takes a lot of resources on the transmitter! Why don't you work on your files on the PC so that they are perfect when copied to the radio?

**Comment by alm-nl** [comment]
You can use Audacity to process all sounds by using a macro, that makes it easy and quick to process several audio files at once.

**Comment by jurajjurej** [comment]
> 

If it's problematic, then nothing. It would just be a nice addition.
