### ISSUE TITLE
Firmware releases in Suite are greyed out

### ISSUE THREAD

**Issue by Dsrenger** [FrSkyRC/ETHOS-Feedback-Community#2184]
Hello,

I am trying to update my XE-S with the Ethos Suite 1.4.4

- Started the TX in bootloader mode

As you can see on the Screenshot, the firmware releases are greyed out and I cannot start the update.

Is that a Suite issue? 

No idea what I can do. Tested 2 different laptops, mit several USB slots and two different cables. Always the same behaviour.
Interesting that the XE-S thumbnail is broken as well (top right)

My X20s ist working just fine.

![Screenshot 2022-12-08 195843](https://user-images.githubusercontent.com/51758752/206725609-b2ee812c-84da-444c-aef9-263db9119559.png)

**Comment by DanielBo** [comment]
Works fine in 1.4.4
Start radio in normal mode, suite will put radio in bootloader mode.

Once it says "USB Connected" unplug usb, und put back in.
Works fine.

**Comment by Dsrenger** [comment]
Tested several ways. It was always greyed out. My X20s works fine.

Hmmmmm, strange

**Comment by Dsrenger** [comment]
Btw, just recognized that the suite shows as max Version for the TD module 2.2.2

The version showed on the Frsky website (and installed on my XE) is 2.2.4

**Comment by Target0815** [comment]
Download the suite again (under Assets in the Releases section) and install it. Before doing so, exit the previous version.

**Comment by Dsrenger** [comment]
Already did.
 Installed as well the suite on a laptop where it was never installed before.

Thought about updating everything by hand on the XE to potentially fix the problem, but only found the bootloader, firmware and audio files.

My X20S need as well the SD files (yeah I know the XE has no SD) and flash files.

Not sure where I can find a list of all files needed to update manually.

**Comment by Target0815** [comment]
Then set the suite to developer mode and try again. Always start the transmitter in bootloader mode so that you have a consistent start.

**Comment by Dsrenger** [comment]
Tried the developer mode. Same behaviour.

Perhaps I just wait and hope its working with one of the next releases.

No idea, if it is a bug in the suite or if theres something wrong with my XE.

The X20s is working fine with the suite. So I dont think it is a laptop or cable issue.

**Comment by Target0815** [comment]
Instead of the repair tool, you can also try a CHKDSK x: /F in the command line (x: = your drive). I also test a lot and must therefore occasionally pull the battery and get then just also errors displayed. The repair tool does somehow "strange" things, I've tried only 1x.

**Comment by Dsrenger** [comment]
CHKDSK cannot find any issues.

Perhaps one of the Devs knows, whats happening. Will try with the next version of Ethos and if it doesnt work, I will return the TX.

Just to give the complete picture, this is the coneten of my TX drives:

![image](https://user-images.githubusercontent.com/51758752/206842340-66cf3153-76ae-4cf0-b1f9-e998ade30d8c.png)
![image](https://user-images.githubusercontent.com/51758752/206842349-79b7afb0-aee0-4ab1-9122-cb0b837336dd.png)

**Comment by Target0815** [comment]
It's strange ... The error messages look like the suite has no write permission which would be normal in ProgramFiles. Only if your X20S works with the same suite without problems, it must be the XE.

Maybe @bsongis-frsky has a tip ...

**Comment by ola-aberg** [comment]
I have the same problem with my XE-S. Tried with Ethos Suite 1.4.4 and 1.4.3  the firmware releases are greyed out and I cannot start the update. I have updated Firmware to version 1.4.4 EU and Bootloader version 1.4.4. Downloaded them and used the local file option in Ethos Suite.

**Comment by Dsrenger** [comment]
Good to hear, that I am not the only one :)

I have heard rumors that it will/could be fixed next version.

I guess, let's wait and see :)

**Comment by Nicholas-Luoyi** [comment]
Sorry that I haven't noticed this this issue. It will be fixed in the next release.

**Comment by bsongis-frsky** [comment]
There is a typo in XES vs XE-S in 1.4.4 and it will be fixed in 1.4.5 (later this week we hope)
