### ISSUE TITLE
Sensor Conflict Issue in 1.4.4 and 1.4.3 With Unisense and Archer GR8

### ISSUE THREAD

**Issue by DanielBo** [FrSkyRC/ETHOS-Feedback-Community#2185]
Hey there
I am running Ehtos 1.4.4 and was trying to setup an Unisense-e with latest firmware on a GR8 Receiver.

When i discovered sensors it would tell me "Sensor Conflict" - Thats how i got here. And I ended up messing around with the app id in the unisense tool. Set it to different values. One of which was 27(i think). Then the annoying audio message would dissappear. However - then I'd actually have an issue with the Altitude jumping between 0 and -100.

Every other value 28-20 (for the appId) was fine, judging by the telemetry values i received. However remote kept annoying me with "Sensor Conflict".

I kinda got the feeling that the Condition for the "Sensor Conflict" audio warning might be reversed. As it didnt appear when i actually had an issue, and was silent when everything worked fine.

In addition my screen is flickering, which is annoying by itself... And my First Tandem ejecting its lower display on me didnt help either.

Switched to 1.4.3 => Sensor Conflict issue still exists.

To Reproduce:
- Setup new model.
- Register Receiver
- Bind receiver to rx1
- turn modell off, plugin unisense in s-port
- powerup
- go to telemetry (still empty as never been here before)
- discover new sensor on
- > Sensor Conflict Warnung

Altitude and VSpeed show up twice, both showing reasonable values.

**Comment by Target0815** [comment]
> an Unisense-e with latest firmware

The last version is IMHO a beta version, which comes on request by mail. Do you have this installed?

**Comment by mawzthefinn** [comment]
Yes, I believe you need the latest beta release to be able to set a non-conflicting address properly for the Unisens-E, that should be one of the fixes in that release

**Comment by DanielBo** [comment]
Sooo - what do i need to do?
For now i just renamed the "Sensor Conflict" wav to shut up the system...

The Latest Unisense Beta would be 1.20? 1.21?

**Comment by mawzthefinn** [comment]
Get the latest firmware for your Unisens-E

Once you have it, change the physical ID and App ID of the Alt and VSpd sensors of the Unisense-E to a different one than the GR8 internal sensors use.

**Comment by phaedra-tm** [comment]
Go to the website of SM Modellbau, and fill out the contact form to send an email to Stefan, he will send you the beta version.

**Comment by mawzthefinn** [comment]
Were you able to obtain the current firmware for the Unisens-E?
