### ISSUE TITLE
1.4.4 update on X20 startup check list issue

### ISSUE THREAD

**Issue by FireFlite88** [FrSkyRC/ETHOS-Feedback-Community#2186]
After updating to 1.4.4 through Ethos Suite my startup checklist shows all switched red.  When they are moved into the correct position for startup they stay red but the system does acknowledge that they are in their "safe' Startup positions.  So technically working but the visuals are off and it isn't very pleasant.

**Comment by mawzthefinn** [comment]
Is your Highlight Color (in System->General) set to Red?

The checklist will change from red to the highlight color as they pass, if you are using red as a highlight color the change will be impossible to see.

**Comment by mawzthefinn** [comment]
Did you check with a non-red highlight colour?

**Comment by mawzthefinn** [comment]
Closing as no info received.
