### ISSUE TITLE
XE - menu, scrolling etc was very slow

### ISSUE THREAD

**Issue by miksterr** [FrSkyRC/ETHOS-Feedback-Community#2187]
XE - 1.4.4, FCC / TD-ISRM HW: 1.0.6 FW: 2.2.4 FCC

Went for a fly today and 1 out of the 6 or so flights the transmitter was slow.

By this I mean, I flew an F5J glider, new model and had to make adjustments for flap/ele compensation  - so landed and went into the menu. The scrolling between the mixer was slow - took 4-5 seconds between each part.

Radio was fine - (RF never lost ect) restarted TX and was fine.

Have had an X20s since start and it has never done this.

**Comment by bsongis-frsky** [comment]
Perhaps a problem in communication with the eMMC for the storage? It would result in Write timeouts ...
Your last change would be lost.
It's strange though, have you tried to reproduce it on ground?

**Comment by HolgerJr** [comment]
Hello Miksterr,
do you use LUA?
I have similar problems using different LUA. The effects are a slowed down system, errors in the visual display in the LUA widgets and the emergency mode.

**Comment by mawzthefinn** [comment]
Is this still occurring?

**Comment by HolgerJr** [comment]
With ETHOS 1.4.5 on XEs, yes. Memory is still lost when using lua and when memory is low then the error occurs.
On my X20s also, but I do not have update it. X20s works with ETHOS 1.4.4.
