### ISSUE TITLE
Logical Switch with source Clock not working

### ISSUE THREAD

**Issue by FlipAirboost** [FrSkyRC/ETHOS-Feedback-Community#2189]
Tx  Ethos X18  firmware version 1.4.3, EU #2f35065f

logic SW1  A~X
source   Clock
Value (X)     2039-09-21  10:32:28    ( value max)
Always On
DBA     0.0
DBI      0.0
Min D  0.0

The Value (X) can only be changed second by second.
Moreover if we could modify it as for the chronos, the logical switch would be valid only once, since it takes into account the year, the month and the day?

Special Fonction      Play Value
state                        Enable
Active condition      LSW1
Value                        Clock
Repeat                     Once
Skip on startup        On

Regards
Flip

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/207310958-abe718fd-6674-4d32-98f5-fed8e9faf22f.png)

**Comment by bsongis-frsky** [comment]
You have to change the step if you want to modify the value quicker

**Comment by bsongis-frsky** [comment]
Issue replicated: the logic switch value is badly calculated (integer overflow)

**Comment by bsongis-frsky** [comment]
After the fix

![image](https://user-images.githubusercontent.com/50834778/207316021-3cb89b61-78eb-46fa-a86a-2b57ecb3768a.png)

![image](https://user-images.githubusercontent.com/50834778/207316073-54070d1a-59e2-4c9f-a192-0fdaddebcbda.png)

**Comment by bsongis-frsky** [comment]
I am not sure I have correctly understood this:
> Moreover if we could modify it as for the chronos, the logical switch would be valid only once, since it takes into account the year, the month and the day?

I am not sure you have seen the options symbol which allows entering only a Time, not Date&Time

![image](https://user-images.githubusercontent.com/50834778/207394282-dc7f7bac-4192-4b8b-9f2c-135fffc199ca.png)

![image](https://user-images.githubusercontent.com/50834778/207394400-03eb1db4-82ff-47dd-a93a-b8c9a25caed1.png)

**Comment by FlipAirboost** [comment]
Hi Bertrand,
The radio screen is probably a little too low, I couldn't see the first pixel of the step adjustment.
How do you access the option symbol to select date time ?
Regards 
Flip

**Comment by mawzthefinn** [comment]
Long-press the Source value box (note the 'hamburger' icon in the upper left of it, indicating long-press options exist)

**Comment by FlipAirboost** [comment]
Hi All,
Problem solved.
It's when none of the boxes are checked that the display is weird.
Thanks
