### ISSUE TITLE
X20 v1.0.5 Charging light never goes off.

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#219]

**Comment by bsongis-frsky** [comment]
This led is not driven by Ethos

**Comment by MIKE-DAILEY** [comment]
Try using the system some so the battery voltage gets down to around 7.5v and they try charging again.  The USB power source should have 2amp capability.

**Comment by KenLong51** [comment]
According to the instructions, the green power light should go off when charging is complete. However I have left it plugged in to a 3amp usb for many hours and it has not gone of yet.

Does anyone know how long it should take to complete a chanrge from about 3 bars in indicator please?

**Comment by KenLong51** [comment]
Mike, I have taken the system down to about 2 bars, put it on charge for hours (I then have 4 bars) but still the charge light is on.

If something is suspect I am dubious about leaving it on all night un-attended.

**Comment by MIKE-DAILEY** [comment]
My system acted like that the first few times I charged it.  After I let the battery voltage get low the charge cycle seems to work fine now. It takes a few hours to charge depending how low the battery voltage is.  Keep in mind that the green LED is also an indication of a USB connection, but if it is actually in battery charge mode the LED will turn off when fully charged.

**Comment by KenLong51** [comment]
OK Mike, I'll give it a go - Many thanks.

**Comment by rburrow87** [comment]
I started noticing this happening to mine as well and discharging it to ~7.4v first fixed it. Thanks!
