### ISSUE TITLE
trainer mode problem

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2192]
when i setup trainer mode.  x20s master x12s slave.  everything works great.  then i turn the transmitters off and when i turn the x12s back on i get       Model data load
                              Invalid data
                             Starting model wizard
                                                              OK
  Not sure what i am doing wrong

**Comment by mawzthefinn** [comment]
Sounds like an SD problem, model is not properly saving.

If you switch models on the X12S, can you switch back to this one? Does the model fail to load on reboot if you switch models before powering off?

**Comment by williajgr** [comment]
No, once it is bad it stays bad.  And switching models before shutting it off doesn’t solve the problem. Only time I have a problem is when I put it into trainer mode. Then that model is bad.  Thanks for the help Sent from my iPhoneOn Dec 10, 2022, at 8:01 PM, mawzthefinn ***@***.***> wrote:﻿
Sounds like an SD problem, model is not properly saving.
If you switch models on the X12S, can you switch back to this one? Does the model fail to load on reboot if you switch models before powering off?

**Comment by bsongis-frsky** [comment]
I cannot reproduce this issue here.
Please paste your corrupted model here so that I can have a look!

**Comment by williajgr** [comment]
It works perfictly on my taranis or x10s both open-tx.  but not on my x12s.  every model i put into trainer mode comes out corrupted when i turn the transmitter off. it works fine until i turn the transmitter off.
[rover.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10218738/rover.zip)

**Comment by bsongis-frsky** [comment]
Your model is saved with an external module stored as TW Lite, which cannot work. If you create a new model, or just reload this one with the previous firmware, then you change its type to XJT or whatever, it will work correctly.

From 1.4.5 it is impossible to choose TW Lite anymore

**Comment by williajgr** [comment]
Thanks for the help.  I see it was set to tw lite.  But the external Rf was set to off.  I guess it got set that way because I copied the .bin files from my x20 to the x12.  Guess I shouldn’t have done it that way.Is there a better way to move models over from the x20 to the x12.  Thanks again for the help    JoeSent from my iPhoneOn Dec 13, 2022, at 12:58 PM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Closed #2192 as completed.

**Comment by bsongis-frsky** [comment]
Ah it makes sense now! Yes even if it is OFF, your settings are saved and they mean nothing on X12S, I have to deal with it in 1.4.5. Reopening the issue...

**Comment by williajgr** [comment]
This is a different question but I don’t want it to be an official issue,  any way to turn off the speakers when one uses Bluetooth audio? Would be nice.Sent from my iPhoneOn Dec 13, 2022, at 1:20 PM, George Williams ***@***.***> wrote:﻿Thanks for the help.  I see it was set to tw lite.  But the external Rf was set to off.  I guess it got set that way because I copied the .bin files from my x20 to the x12.  Guess I shouldn’t have done it that way.Is there a better way to move models over from the x20 to the x12.  Thanks again for the help    JoeSent from my iPhoneOn Dec 13, 2022, at 12:58 PM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Closed #2192 as completed.

**Comment by mawzthefinn** [comment]
BT and Muting is reported under #1370

**Comment by williajgr** [comment]
I am probably doing something wrong, but when i tell it to connect to the last device it does nothing.

**Comment by williajgr** [comment]
by the way your solution fixed the problem for me.  thanks for help

**Comment by bsongis-frsky** [comment]
In 1.4.5 if you replicate a model on a radio which doesn't allow a module type, the module data will be reset
