### ISSUE TITLE
this is not an issue but something really cool with trainer mode.

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2193]
I have an x20s ethos master and a horus x10s express open-tx slave.  they work perfectly with each other in trainer mode.

**Comment by mawzthefinn** [comment]
Yes, both use the Para trainer module. All the Para-equipped radios play well with each other.

**Comment by williajgr** [comment]
Yep, even my taranis 2019 para works.  But it did have to have the latest firmware update.    ThanksSent from my iPhoneOn Dec 10, 2022, at 8:00 PM, mawzthefinn ***@***.***> wrote:﻿
Closed #2193 as completed.
