### ISSUE TITLE
X12 : Unable to flash from S.port

### ISSUE THREAD

**Issue by excalibur46** [FrSkyRC/ETHOS-Feedback-Community#2197]
On my X12S ISRM after updating from 1.1.1 to 1.4.4, I can no longer flash any receiver or sensor from the S.port.
On radio I have the message "Device reset", the red led blink once on the receiver, but then I have the message "Device not responding".
I tried with S6R, X8R, RX8R receivers ,and  Xm+, FLVSS, MLVSS sensors.

**Comment by jbesse262** [comment]
I have also discovered this today. Could not update rx6r via pins in Jr bay. Same error as OP. OTA fails also. Updating with X20 is uneventful.

X12-isrm 2.1.6
Ethos 1.4.4
Rx6r 2.1.0 - 2.1.7

**Comment by yak-54** [comment]
Yep cant update R9 firmware as well
X12-isrm 2.1.6
Ethos 1.4.4
access 1.3.0 R9 Firmware

**Comment by bsongis-frsky** [comment]
It worked in 1.1.1?

**Comment by yak-54** [comment]
> It worked in 1.1.1?

cant help with that one so long ago lol
only tried on 1.4.4

**Comment by excalibur46** [comment]
Yes, it worked in 1.1.1!

**Comment by bsongis-frsky** [comment]
I have nailed it

**Comment by jbesse262** [comment]
What did you find was the issue?

**Comment by yak-54** [comment]
> What did you find was the issue?

i bet it was 0101000011100111100000 error

**Comment by bsongis-frsky** [comment]
No ... even more stupid: the port was set as INPUT instead of OUTPUT ...

**Comment by yak-54** [comment]
> 

been there done that before with an a program i did for ESP 32 module i got the TX and RX pin numbers crossed took me a week be a buddy found it in my script 👍

**Comment by Andreaflyer** [comment]
Salve, anche io ho il solito problema, non so come risolvere. Solito errore. Funziona tuttoa non posso flashare sia moduli che riceventi.

**Comment by yak-54** [comment]
> Salve, anche io ho il solito problema, non so come risolvere. Solito errore. Funziona tuttoa non posso flashare sia moduli che riceventi.

you cant fix it upto bsongis-frsky or one of the team members  to fix it which has been done have to wait till next update

**Comment by bsongis-frsky** [comment]
Wait for Christmas then ;)

**Comment by Andreaflyer** [comment]
Grazie, attenderò con pazienza. Siete grandi bel lavoro.

**Comment by Andreaflyer** [comment]
Now it's ok!!! Thanks
