### ISSUE TITLE
Re-Opening "0.17 Firmware causing display tearing."

### ISSUE THREAD

**Issue by OldGazer** [FrSkyRC/ETHOS-Feedback-Community#22]
Shortly after updating from 0.16 to 0.17 I noticed the lower 1/3 of the display was glitching and tearing every 1 to 3 seconds.
This behavior was most noticeable on the "home" screen, but all screens were affected to some degree.

Reverting back to 0.16 resolves the issue.

Flashed 0.17 bootloader and firmware.  Issue returned.  

Link to short video:  https://youtu.be/ra_aWn0zmZU

**Comment by bsongis-frsky** [comment]
Please make sure you really flash the bootloader 0.0.17 as well, not just the firmware
