### ISSUE TITLE
Emergency mode with widgets since 1.4.x

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2200]
Hello,

seems like since 1.4.3 or 1.4.4 (not sure if earlier), running the same Zavionix widgets as before, some folks are getting occasional emergency mode. i have experienced it once myself and have a log but im not sure that helps.

my Zavionix widgets have ran flewlessly in hundreds of radios for months with not a single emergency mode instance, and these started happening lately after V1.4.x updates. so far i have 4 cases reported.
2 out of the 4 reported this happening when switching to or from a model thats running the widget.

how can this be investigated? what do you need me to provide?
has the allocated memory for LUA been lowererd / changed in 1.4.x?

**Comment by i3dm** [comment]
2 widgets attached.
[scripts.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10205245/scripts.zip)

**Comment by mgsanna** [comment]
I have documenti the issue

**Comment by mgsanna** [comment]
It happen also to me documented by video

https://user-images.githubusercontent.com/15903471/206986076-09a17a20-5d6b-40cb-8e1a-fefb5bb9dffd.mp4

**Comment by bsongis-frsky** [comment]
Sending luac scripts doesn't help a lot as it is impossible to debug / understand.
Do you keep a variable on the widget and try to access it from this variable (even if the widget is destroyed)?

**Comment by bsongis-frsky** [comment]
Would you please check the RAM which is consumed with the USB in Serial Mode, and using the Lua functions provided?

**Comment by bsongis-frsky** [comment]
I cannot see the source code but I am really curious why your script loads 3 times the same bitmap, which is a full screen bitmap

![image](https://user-images.githubusercontent.com/50834778/207013953-97d3ef56-e291-48e4-ab7a-c520804746f1.png)

**Comment by i3dm** [comment]
can i send you the .lua privately? email or skype?

**Comment by bsongis-frsky** [comment]
I have seen this battery widget already, I even received a SD Card from Andreas with this script. He was complaining his radio was too slow. At the time I just removed the scripts to make the radio work correctly. I wouldn't say it works flawlessly.

**Comment by bsongis-frsky** [comment]
That's saidn it should not enter in E.M. whatever the reason. I have introduced RAM limits, and it should work even if a script makes the radio very slow.

**Comment by i3dm** [comment]
> Perhaps check the RAM before.

please write me how to check exactly. ill gladly check.

**Comment by i3dm** [comment]
> I have seen this battery widget already, I even received a SD Card from Andreas with this script. He was complaining his radio was too slow. At the time I just removed the scripts to make the radio work correctly. I wouldn't say it works flawlessly.

latest versions have improved months ago and hundreds ran well before v1.4

**Comment by bsongis-frsky** [comment]
I have tried your script (attached above) on my radio. The whole UI is extremely slow. After calling 2 times Model / Model Select it enters into E.M.

**Comment by bsongis-frsky** [comment]
The same bitmaps are loaded multiple times, I even guess they could be shared between the 2 scripts...

**Comment by i3dm** [comment]
> I have tried your script (attached above) on my radio. The whole UI is extremely slow. After calling 2 times Model / Model Select it enters into E.M.
> 
> RAM is 100% full

ok. i will check the bitmaps loading.
are you checking the E.M? i thought RAM limit should take care of that (it did work great before v1.4)

**Comment by i3dm** [comment]
> The same bitmaps are loaded multiple times, I even guess they could be shared between the 2 scripts...

sharing is impossible as some people use either and not both

**Comment by ColbertDitarso** [comment]
> It happen also to me documented by video
> 
>  Video.senza.titolo.1.mp4

This fact happened to me yesterday! when changing the model and trying to apply one that used ZAVIONIX, the radio went into Emergence mode. My TANDEM is on 1.4.4 and 2.2.2.

**Comment by bsongis-frsky** [comment]
This script uses the whole RAM available (and the major part just for a texture background). The whole radio seems difficult to use once this script runs (3 seconds to switch to another screen), as it is always loading this background bitmap from SD.

And once you go to Model / ModelSelect, it's impossible to load the model bitmaps which a so small amount of available RAM.

I have to find a way to reduce the load of Lua scripts and avoid this state. For now I recommend not using this script in flight.

**Comment by i3dm** [comment]
> This script uses the whole RAM available (and the major part just for a texture background). The whole radio seems difficult to use once this script runs (3 seconds to switch to another screen), as it is always loading this background bitmap from SD.
> 
> And once you go to Model / ModelSelect, it's impossible to load the model bitmaps which a so small amount of available RAM.
> 
> I have to find a way to reduce the load of Lua scripts and avoid this state. For now I recommend not using this script in flight.

1. the script only loads the background image once:
001340 Lua::loadBitmap('/scripts/RDT/img/red/5.png')
001341 Lua::loadBitmap('/scripts/RDT/img/red/6.png')
001341 Lua::loadBitmap('/scripts/RDT/img/red/7.png')
001342 Lua::loadBitmap('/scripts/RDT/img/red/8.png')
001343 Lua::loadBitmap('/scripts/RDT/img/red/9.png')
001344 Lua::loadBitmap('/scripts/RDT/img/red/nil.png')
001345 Lua::loadBitmap('/scripts/RDT/img/red/col.png')
001345 Lua::loadBitmap('/scripts/RDT/img/trim-c.png')
001346 Lua::loadBitmap('/scripts/RDT/img/trim-u.png')
001347 Lua::loadBitmap('/scripts/RDT/img/trim-d.png')
001347 Lua::loadBitmap('/scripts/RDT/img/trim-l.png')
001348 Lua::loadBitmap('/scripts/RDT/img/trim-r.png')
001349 Lua::loadBitmap('/scripts/RDT/img/trimRed.png')
001350 Lua::loadBitmap('/scripts/RDT/img/trimGreen.png')
001354 Lua::load('/scripts/REE/main.luac')
001356 Lua::load('/scripts/rssi.lua')
001358 Lua::load('/scripts/sinus.lua')
001359 Lua::load('/scripts/test.lua')
001359 Lua::loadBitmap('/bitmaps/system/default_glider.png')
001366 ModelData::read('/models/model05.bin')
001369 RAM backup written (size=1625)
001369 playHaptic(duration=10, strength=0)
001370 playFile('/audio/he/system/hello.wav', flags=0, id=5)
001371 Home::doPreflightChecks()
001376 playFile('/audio/he/system/throttle-warning.wav', flags=0, id=9)
001381 Lua::loadBitmap('/bitmaps/models/f16L2.jpg')
INIT DONE
001388 Lua::loadBitmap('/scripts/RDT/img/LZX20RDTbgNoTitle.bmp')

2. why has this never caused EM in v1.2 and v1.3 and only happns on v.1.4? what changed?
3. is it not possible to load a single full background image anymore?

**Comment by i3dm** [comment]
> That's said it should not enter into E.M. whatever the reason. I have introduced RAM limits, and it should work even if a script makes the radio very slow.

in that case there is still an issue to be fixed with E.M, right?

**Comment by bsongis-frsky** [comment]
Yes I am adding a better limitation to avoid a Lua script to use everything

**Comment by bsongis-frsky** [comment]
Your script loads and reloads the background bitmap again and again, I really wonder why, just try to switch to another screen and go back...

**Comment by i3dm** [comment]
OK, what is your suggestion to remove script RAM load, while still allowing full background image?

**Comment by i3dm** [comment]
> Your script loads and reloads the background bitmap again and again, I really wonder why, just try to switch to another screen and go back...

what do you mean the script reloads the background again and again? yes if you switch screens it does, but if you dont it never loads again.

**Comment by i3dm** [comment]
im running 3 widgets:
RDT
AR
GAS

all with full background image.
here is a video of the memory usage:
https://www.youtube.com/watch?v=QXibRqpj0mc

as you can see. every time a widget is opened, out of 2MB available. 1.3MB rtemains available.
when you scroll between widgets, another image is loaded ONCE so goes down to 0.6MB available and then back to 1.3MB available.

under no circumstances the memory is 100% used, not even close.

**Comment by i3dm** [comment]
one widget open:
=========================
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1734149
LUA BMP Avail: **1349918**
=========================
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1730610
LUA BMP Avail: **1349918**
=========================

second widget open:
751393 Lua::loadBitmap('/scripts/GAS/img/LZX20GASbgNoTitle.bmp')
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1728701
LUA BMP Avail: **581918**
=========================
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1726869
LUA BMP Avail: **581918**
=========================

after about 2 seconds goes back to same condition as 1 widget open.

**Comment by i3dm** [comment]
one widget open:
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1734149
LUA BMP Avail: 1349918
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1730610
LUA BMP Avail: 1349918
second widget open:
751393 Lua::loadBitmap('/scripts/GAS/img/LZX20GASbgNoTitle.bmp')
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1728701
LUA BMP Avail: 581918
Main Stack: 1000000
RAM Avail: 1000000
LUA RAM Avail: 1726869
LUA BMP Avail: 581918
after about 2 seconds goes back to same condition as 1 widget open.

**Comment by bsongis-frsky** [comment]
You forget that you are running Lua, and you don't force the garbage collector. Here are some traces from your scripts in case it remains some doubts:

![image](https://user-images.githubusercontent.com/50834778/207118828-e4794750-84f0-4cad-b1d1-8c3ad4882154.png)

So at some moments your script uses half the available RAM on the radio, which in my opinion is very bad. You don't even display a dynamic GPS Map, just a texture!

**Comment by i3dm** [comment]
> You forget that you are running Lua, and you don't force the garbage collector. Here are some traces from your scripts in case it remains some doubts:
> 
> ![image](https://user-images.githubusercontent.com/50834778/207118828-e4794750-84f0-4cad-b1d1-8c3ad4882154.png)
> 
> So at some moments your script uses half the available RAM on the radio, which in my opinion is very bad. You don't even display a dynamic GPS Map, just a texture!

1. will LUA work better than LUAC? please explain this point,
2. why does 50% of the available RAM is an issue? you mentioned 100% before.. now its 50%. 50% should not cause emergency mode.
3. again, all this worked great prior to v1.4.x - can you please explain why?

**Comment by bsongis-frsky** [comment]
1. Bitmaps loaded by luac use exactly the same size than lua, only the ram used by the script itself will be lower, but your script is not very big

2. 50% of the available RAM is used by your script. But the system loads fonts and bitmaps and needs RAM too. At the end 100% of the RAM is used and it's not possible to do anything.

3. Perhaps because we add more & more features, bitmaps, and special chars, which all take more RAM

4. I have added some traces for your understanding. You can see that at some moments 3 full screen bitmaps are loaded in the same time, which should be avoided

**Comment by i3dm** [comment]
1. ok.
2. script uses around 1/3 of the available 2MB RAM, not total system 4MB RAM. generally speaking a single script with background image uses about 0.6MB.
3. ok. has the allocated RAM for LUA (2MB) changed?
4. im happy to hear your advice about how to load background images more efficiently, i think this will greatly improve the widget performance, and being extremely popular, the entire FrSky community will appreciate it im sure.

**Comment by i3dm** [comment]
Just checked and an average full screen BMP565 for X20 size full screen is about 750Kb while PNG is about 170Kb.

**Comment by bsongis-frsky** [comment]
You haven't seen that your bitmap is loaded 3 times at some moments? It means 2.5MB. 
![image](https://user-images.githubusercontent.com/50834778/207257535-01ffafa2-5c4f-4eb3-88e1-9afdf21a2968.png)

Your background texture should be reduced to less than 50x50 pixels, it could be even a mask. Then your trims could be written with the right font, not a bitmap (disabled trims could be hidden). Trims could also be centered perfectly. The logo with the jet and the "RDT" letters  could be a mask. The Bars diagram shouldn't need a bitmap.

**Comment by bsongis-frsky** [comment]
Also please learn about the `collectgarbage` function, it won't make your script run smoothly, but it will help avoiding having 3 times the same bitmap in RAM.

**Comment by i3dm** [comment]
> You haven't seen that your bitmap is loaded 3 times at some moments? It means 2.5MB. ![image](https://user-images.githubusercontent.com/50834778/207257535-01ffafa2-5c4f-4eb3-88e1-9afdf21a2968.png)
> 
> Your background texture should be reduced to less than 50x50 pixels, it could be even a mask. Then your trims could be written with the right font, not a bitmap (disabled trims could be hidden). Trims could also be centered perfectly. The logo with the jet and the "RDT" letters could be a mask. The Bars diagram shouldn't need a bitmap.

no. my bitmap is only loaded once. i checked that several times. no widget ever consumes 2.5mb ram.

background texture is the main issue with memory usage. how would you make it under 50x50 pixels and still cover 800x480 screen? not sure i understand

**Comment by bsongis-frsky** [comment]
While you are working on your widget here are the changes I have made in Ethos to avoid the E.M.
1) Below 500K available RAM the model bitmaps won't be loaded anymore, it will avoid we run out of memory for current UI operations
2) The RAM check when loading bitmaps will be more serious, here the 3rd fullscreen bitmap loaded (as shown in my logs above) will be rejected
3) Some RAM has been freed (audio buffers, fonts)

**Comment by i3dm** [comment]
ok im happy to test it on 1.4.5.
of course i expect ethos to reject widgets if RAM is missing and not go into EM. thia was the case prior ro 1.4.
how much RAM were you able to free up?

**Comment by i3dm** [comment]
> Also please learn about the `collectgarbage` function, it won't make your script run smoothly, but it will help avoiding having 3 times the same bitmap in RAM.

i am already using 1 global variable for the bitmap and added Background = nil every time a widget is changed on the screen, in order to avoid loading more than 1 image at any time.
i can see RAM freeing up 2-3s after the widget starts running. can you explain this?

**Comment by mawzthefinn** [comment]
Collectgarbage() is part of the standard Lua 5.1 and later library, references and examples can be found on the main page for the Lua language at https://www.lua.org/

**Comment by i3dm** [comment]
> Collectgarbage()

i went through that but am still unable to get it to run in my script.
are you able to help with a 2 line example code please?

**Comment by i3dm** [comment]
i have rewritten all the graphics in my widgets.
no more full screen BMPs, just a small image of the texture multiplied, and using masks.
result is very little RAM usage, and a much faster system! here is the X20S running 5 (!) full screen widgets:
https://www.youtube.com/watch?v=l5GtK7wvOj8

**Comment by ColbertDitarso** [comment]
Thank you very much for the feedback on the cause of the problem! I
believe that in a short time, everything will be back to normal! The
FrSky team is fantastic and that's why I migrated from a famous brand
to FrSky, which today serves me with quality and confidence! Thank you
very much!


Em seg., 12 de dez. de 2022 às 11:04, Bertrand Songis @ FrSky <
***@***.***> escreveu:
