### ISSUE TITLE
TW Lite pro module on Horus X10 express?  

### ISSUE THREAD

**Issue by chiaradubaldi** [FrSkyRC/ETHOS-Feedback-Community#2203]
In the last update (1.4.4) on Horus radio, the choice TW Lite Pro disappeared from the menu for External modules. 

I know the Horus X10 doesn't have the Lite attachment, however wasn't it possible to use an adaptor? (for example Beta FPV)
Is it "just" a software problem or is it a hardware problem too? 

In the case it's a limitation regarding the last software update, will it be possible in the future to add this choice again? 
(or will FrSky add a TW Pro with JR module case in the future?)

Thanks!

**Comment by mawzthefinn** [comment]
No, the adapter only works for modules that are electrically a JR module in a lite format. That means it works for most 3rd party 'Lite' modules but not necessarily for FrSky ones which take advantage of the extra features of the Lite Bay

The Lite bay has 3 extra connectors than a regular JR bay does and also is designed to allow for higher-speed interconnects than a upgraded Horus (X12S or non-Express X10) allow for.

**Comment by bsongis-frsky** [comment]
The serial port on the Horus radios doesn't have the full Tx / Rx serial connection. It is impossible to make it work!
