### ISSUE TITLE
Crossed binding recivers on different models

### ISSUE THREAD

**Issue by sharonfridman** [FrSkyRC/ETHOS-Feedback-Community#2205]
Hi,

Two different models, one bind with RD6 reciver the other bind with RD10.

The transmitter shows the correct reciver for each model.

Didn't made copy to create the other model.

The x20s transmitter controls them both at the same time on both of the models.

I tried reset, registering again and it's the same.

I thought that binding receiver to a specific model is to prevent accidentaly flying the wrong model and to prevent what I just described.

Thanx,

Sharon

**Comment by GiorgioCirelli** [comment]
X20 - The same thing happens to me too

**Comment by bsongis-frsky** [comment]
Do you have a different ModelId for each model?

**Comment by sharonfridman** [comment]
2 different models in the transmitter, each one bind with only one reciver

**Comment by Target0815** [comment]
> 2 different models in the transmitter, each one bind with only one reciver

@bsongis-frsky asked if the **model ID** is different ... If this is the same, then both receivers will respond to the transmitter, regardless of which model you have selected.

**Comment by sharonfridman** [comment]
Where can I find this modelid parameter? Isn't it suppose to be assigned automatically different by the transmitter

**Comment by mgsanna** [comment]
> X20 - The same thing happens to me too

you have to modify your model ID
![Immagine 2022-12-14 112414](https://user-images.githubusercontent.com/15903471/207570455-17a73b7b-4ab4-4518-91e9-2808b2574d8d.png)

**Comment by mawzthefinn** [comment]
Register links the receiver to the Owner Registration ID (which can be shared across multiple radios owned by the same person).

Bind links the receiver to the specific Radio,  Model ID and UID. Model ID can be shared across multiple model memories (very common for quads) and UID just denotes which receiver slot (of 3) is in use. 

Automatic assignment of unique Model ID's is a patent-protected Spektrum feature, which is why there is only semi-automatic assignment in ETHOS (and other systems).

**Comment by sharonfridman** [comment]
Thank you for this detailed answer, I appreciate it!

בתאריך יום ד׳, 14 בדצמ׳ 2022, 17:37, מאת mawzthefinn ‏<
***@***.***>:

**Comment by mawzthefinn** [comment]
Can we close this off as complete now?

**Comment by sharonfridman** [comment]
A friend has the x18 transmitter and he doesn't have this problem. Each model and binding controling one airplane

**Comment by mawzthefinn** [comment]
What model ID is assigned to a given model by default depends on how you created the specific model in question. 

If you set unique model ID's and rebind the issue will be resolved

**Comment by sharonfridman** [comment]
I understand that but why its working different on my friend transmitter?

בתאריך יום ד׳, 14 בדצמ׳ 2022, 19:18, מאת mawzthefinn ‏<
***@***.***>:

**Comment by mawzthefinn** [comment]
It's almost assuredly not working differently on your friends transmitter, if you rebind with a unique model ID on one of the models, you will solve the issue for both models.

When you create a new model, then go and enable Internal RF, you should see a model ID that's incremented by two from the last model created.

**Comment by sharonfridman** [comment]
I will do that. My friend did not enter this number for sure.

A unique number is any number at the model id field?



בתאריך יום ד׳, 14 בדצמ׳ 2022, 20:24, מאת mawzthefinn ‏<
***@***.***>:

**Comment by mawzthefinn** [comment]
Any number in Model Id that is not used for another model. Note that the radio will list the model ID at the lower right of the screen if you tap on a model in the Model Select menu.

The radio tries to assign a model ID that's higher by 2 for each model created and RF enabled, but firmware updates and other items can force a reset of the counter. It's best to always verify you are getting a unique ID (and yes that can be difficult, there's an open issue to generate a list of used model ID's to make this easier to manage)

**Comment by sharonfridman** [comment]
Many thanks for your patience

בתאריך יום ד׳, 14 בדצמ׳ 2022, 20:40, מאת mawzthefinn ‏<
***@***.***>:
