### ISSUE TITLE
MultiModule option does not exist on 1.4.4

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2206]
X20S
iRX4 lite module installed.
running the "Modules" folder with LUA on the SD.

RF system menu:
with V1.3 the "MultiModule" was an option under external module - type.
with V1.4.4 this option does not exist in the menu.

**Comment by mawzthefinn** [comment]
The location and script were changed for 1.4.1

Use the current posted version of the script and place in /scripts/multi

**Comment by i3dm** [comment]
where is it posted?

**Comment by mawzthefinn** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua

**Comment by mawzthefinn** [comment]
Are we good to close this off?

**Comment by i3dm** [comment]
Yes thanks,
where is information like this posted for future reference?

**Comment by mawzthefinn** [comment]
The best info for external module support is posted here and updated to reflect any changes:

https://www.rcgroups.com/forums/showpost.php?p=49550649&postcount=18844
