### ISSUE TITLE
module type missing in hebrew

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2207]
X20S V1.4.4
RF menu missing the module type as can be seen in the photo.

![HE](https://user-images.githubusercontent.com/8968780/207684922-246f5eb1-aaa3-40d9-87f3-54f1e55854d4.jpg)
![EN](https://user-images.githubusercontent.com/8968780/207684934-a918712b-91a2-48c1-8162-623a6c12a842.jpg)

**Comment by i3dm** [comment]
@bsongis-frsky any way to check this generally? we keep finding missing fields in Hebrew, 1 by 1.
please try to think about a solution.

**Comment by bsongis-frsky** [comment]
Nobody in our team speaks Hebrew and writes from Right to Left.
Module Type / Subtype is not something very new, it's there since Day-1. Perhaps you could have noticed / reported it before?

**Comment by i3dm** [comment]
i never used external module so far.
a sanity test about the amount of fields can be done well even without speaking Hebrew,

**Comment by bsongis-frsky** [comment]
We cannot test all our radios in all languages and I am sorry for that.
Other translators check their screens, at least to see if the text fits or not.

![image](https://user-images.githubusercontent.com/50834778/207815373-8f9c1c0c-8eca-4b76-b18b-9969ba1338d0.png)
