### ISSUE TITLE
Open Source the code

### ISSUE THREAD

**Issue by datamafia** [FrSkyRC/ETHOS-Feedback-Community#221]
Am I missing something or did you abandon Open source OpenTX for a closed system?

All I see is bloat, again.  What's the problem?

**Comment by bsongis-frsky** [comment]
No, Ethos is the replacement project for FrOS which is End Of Life.

Also, as of this date, FrSky has decided not to give the X20 schematics to open source projects like OpenTX or ErskyTX.
Previous experience has shown that it is too easy for the competitors to copy the whole radio design.

**Comment by andika207** [comment]
@datamafia it's just a matter of time until any skilled person breaks X20's copy protection.
https://www.rcgroups.com/forums/showpost.php?p=47120633&postcount=10261
