### ISSUE TITLE
Two different expo values on the same curve

### ISSUE THREAD

**Issue by sharonfridman** [FrSkyRC/ETHOS-Feedback-Community#2211]
Is there a way to do different expo values for each side of the channel on the same curve without adding a second curve?

i.e., one expo value for the up elevator and a different value for the down elevator

**Comment by mawzthefinn** [comment]
Yes, I wrote this up for aileron differential, but the exact same technique works for Expo

https://www.rcgroups.com/forums/showthread.php?4174941-Var-Mixes-and-Aileron-Differential

**Comment by sharonfridman** [comment]
I think that you misunderstood me.

I want a different expo for the up elevator of 30% and 40% for down elevator in the same curve. 

I don't want to change it by switch or to have different expo's for different flight conditions.

**Comment by mawzthefinn** [comment]
No, I didn't misunderstand you. The solution I provided can do exactly what you are requesting.

You need a logic switch that differentiates between up elevator and down elevator. Doesn't matter which way, just use the A > X function and Analogs->Elevator as the source, triggered at '0'. 

You need a VAR mix with the two weights you want, one as default, one selected by the Logic Switch you just created. This VAR mix outputs to a high channel (like Ch64)

Then you set your Expo to 'Use a Source' by long-pressing the Expo box, and use the output channel of the VAR mix as the Source. 

Now you have two Expo settings, adjustable in the VAR mix, which are selected by the Logic switch based on whether or not you have up elevator or down elevator currently commanded.

**Comment by sharonfridman** [comment]
I hope i will manage to succeed.

Thanx

**Comment by EngelMT** [comment]
Maybe I didn't understand everything correctly.  But I would just generate my own curve and all will be o.k.

**Comment by mawzthefinn** [comment]
@EngelMT He's looking to have two different expo values active, one for Elevator Up, the other for Elevator Down. 

You can do this with a custom curve, and you only need one, but that requires a lot of tuning of the curve. The solution I provided switches between the two Expo values depending on stick position, so it's much easier to implement.

**Comment by i3dm** [comment]
> @EngelMT He's looking to have two different expo values active, one for Elevator Up, the other for Elevator Down.
> 
> You can do this with a custom curve, and you only need one, but that requires a lot of tuning of the curve. The solution I provided switches between the two Expo values depending on stick position, so it's much easier to implement.

your solution is also a bit complex, especially for a new ethos user.
tbh i never needed different expo per side, but if people do, it may be better to implement it on the expo curve menus.

**Comment by mawzthefinn** [comment]
It’s a complex request that’s an edge case. Far better to use a single generic solution that also applies in the other similar cases than do multiple 1-off fixes that complicate the UI.

I’ve had this basic request asked for with regards to differential and rates as well. This is teh third time I’ve written up this basic solution for a completely different field. 

My solution is quite simple to implement once you’ve done it once and is applicable to all similar requests. Adding an extra field in Expo would complicate the UI for most users and still not address the other cases where such per-side values are required.

**Comment by mawzthefinn** [comment]
Closing off as an answer has been provided
