### ISSUE TITLE
RD6 only one 2.4ghz antenna

### ISSUE THREAD

**Issue by sharonfridman** [FrSkyRC/ETHOS-Feedback-Community#2212]
Why the RD6 has only one 2.4ghz antenna? We always told that 2.4ghz needs 2 antennas to cover different angles of the model for better reception?

Frsky has also other TD recivers with two 2.4ghz antenna.

Isn't it like loosing one step of redundecy?

Does the 900mhz antenna uses also as the second antenna for the 2.4ghz frequency?

**Comment by mawzthefinn** [comment]
This is not an ETHOS question, so not really the right place.

That said - The TD R6 is a smaller, more basic receiver than the TD R10 or TD R18 and intended for smaller and more cramped installations where you may not have as many options for antenna installation. The single 2.4G antenna does not cost you redundancy ( you still have 2 RF sections listening on 2 bands) but does mean your 2.4G section will be more sensitive to antenna orientation.

FrSky gives you different options to meet different needs. If you want the dual 2.4G antennas, the other 3 TD receivers offer that.

**Comment by sharonfridman** [comment]
The other 3 receivers are the TD10, TD18 and the TDMX that have the same range capability?

**Comment by mawzthefinn** [comment]
Yes, those are the other 3 TD receivers. The range is the same for all 4 receivers.

**Comment by sharonfridman** [comment]
Thank you!
