### ISSUE TITLE
[Feature Request] Percentage Consumed with mAh vs Entered Battery Capacity... Calculated Sensor

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#2213]
Something that would be very useful would be a percentage remaining sensor when using mAh telemetry.  Basically, allow the user to enter the nominal capacity of the battery (or perhaps the tested real capacity) and compare that with the mAh consumed, and calculate a percentage left.  Most people fly to 20% remaining (some more conservatively fly to 30% remaining, etc) and it is much easier to do than just a direct mAh consumed logic switch and value playback function.

For example, on my 380 size heli, I have a 1800mAh battery and normally fly to 25% with a first alarm to land soon, then 20% to land now.  That corresponds to 1350mAh consumed then 1440mAh consumed.  It's much easier to understand "25% remaining" than "1350mAh" or etc readouts.  Yeah you could memorize the numbers, but it'd be better to just have a percentage readout.  Radios such as Vbar Control do just this - alarm you at predetermined percentage remaining by using the known capacity of the battery and the consumed value.

In my past experience with OpenTX radios, someone created a Lua script widget that does just that... you tell it your nominal capacity in the widget settings, then it uses that combined with the consumed mAh (select a source also in widget settings) to alarm you at 25% and 20% as well as display a proportional bar from 0% to 100%.  

But I think Lua is a bit overkill, and this could easily become a calculated sensor and would not require a Lua script to be downloaded and run.  It's a very simple calculation that a calculated sensor should easily be able to do.  (1350/1800)*100 = 75% consumed.  Then subtract that from 100 to give 25% remaining.  Maybe an option in the calculated sensor settings to either be percentage consumed OR percentage remaining.  Allowing it to go below 0% would be useful, so you could know how much you overdischarged your pack if you accidentally flew past the alarms ;)

I've tried "percentage" calculated and DIY sensors, but without being able to tell it what the nominal capacity is, it's as good as useless.  Unless I'm missing/not seeing an available parameter to set?

**Comment by STC148** [comment]
Small workaround, create a consumption sensor where you store the desired mah, and then create a percentage sensor where you use the consumption sensor as a sensor. If you want the percent to count down, then set invert to on.

![1](https://user-images.githubusercontent.com/85410070/208264365-9fb55658-af98-4411-b7dc-09e6814552e3.jpg)

![2](https://user-images.githubusercontent.com/85410070/208264371-9ae03da6-b815-4bf7-ac82-f9c9e4c0bfd2.jpg)

![3](https://user-images.githubusercontent.com/85410070/208264375-4d6423e0-cec4-4776-8d68-e5912af70d84.jpg)

**Comment by BladeScraper-Designs** [comment]
Yeah, that does work.  Nice.  Once I saw you set the actual range in the mAh sensor (I didn't know you can do that), that inspired me to try it using an existing mAh sensor (instead of a calculated one) from a flight controller (Brain2) and it seems to work also, once I set the range in the mAh sensor.  

The only concern is what it will do when you exceed 100% used, as it seems to simply stay at 0%.  Which is totally fair, though I think it would be nice to allow over 100% consumed (and thus negative % remaining) using a dedicated "remaining/consumed percentage" sensor, or simply a checkbox with "allow extended range" or something that allowed it to use negative percentages in the percentage.  

I'm not sure if allowing the range on percentage sensor to be say -50% to 100% would do the same, or if that would screw with the ratio calculation from mAh to %.

**Comment by STC148** [comment]
The problem with the existing mah sensor is that it does not count beyond the set limit. So you don't know afterwards how much mah was really consumed. For this reason, I have additionally created the calculated sensor.

**Comment by BladeScraper-Designs** [comment]
Oh I see, so, the calculated sensor will go below 0% if such overconsumption occurs?  Good to know.  I suppose one can pick whichever they prefer.

**Comment by STC148** [comment]
I don't know if I have expressed myself clearly. I use the percentage sensor for the usable capacity, which means with a 5000 battery I enter 4000 mah in the consumption sensor. If I now consume something more, the sensor does not show that, because at 4000 mah stops counting.

But if you enter the complete capacity of the battery, then you could also easily use the existing Mah sensor.

**Comment by BladeScraper-Designs** [comment]
I see.  You entered 4000 because it is 80% of your 5000mAh pack.  I assumed you meant a 4000mAh pack, not 5000mAh.

Makes sense.  I don't use VBAR but I believe that is what they do also.  In the past, I've entered my true capacity and landed when it says 20%.  On Vbar it offsets this and when it says 0% it is actually at 20% (you can also change this to 30% etc).  

I understand how the system works now.  I guess it's really more of me not understanding Ethos (or OpenTX for that matter) and not really a feature request.  I apologize that this ended up mostly being me using this GitHub feedback page for just getting help with Ethos.  You can feel free to close this issue/request.

**Comment by mawzthefinn** [comment]
I’ll close this off.

Note that there is an excellent community for support of ETHOS on RCGroups, if you haven’t already found it, check out the X20/ETHOS thread in Radios. That’s a good starting point when you  have a question about ETHOS that may not be an issue
