### ISSUE TITLE
ethos / yappu "play value" not working from yappu lua source

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2214]
not sure weather this is a ethos issue or a yappu issue.  I have a pixhawk connected to the telemetry port.  I get all of the telemetry data in the yappu screen (works great)  but in the ethos telemetry  i only get the gps coordinates.  running open-tx i got all of the telemetry.  speed,altitude battery voltage current usage, etc. mostly i need the altitude as i am wearing googles and can't look at the screen. i need it to read out the altitude.

**Comment by Target0815** [comment]
https://github.com/yaapu/FrskyTelemetryScript/wiki/Ethos:-exporting-ArduPilot-sensors-as-LUA-Sources

**Comment by williajgr** [comment]
that got me halfway there.  i can now display the telemetry but cannot "play value".
 for the telemetry.  another small issue is that it doesn't display the same units that are displayed on yappu.  ie . yappu displays ft and the telemetry is in meters,  thanks for the help

**Comment by OldGazer** [comment]
What you want is not a function provided by your radio.

Telemetry data is provided to your goggles by an OSD (On Screen Display).  This device takes mavlink data from a serial port and combines it with the video signal from your FPV camera and then feeds that signal to the video transmitter.  I have 3 Pixhawk drones.  They all have FPV cameras and OSDs,  I also run Yaapu on ETHOS, OpenTX and EdgeTX.

**Comment by williajgr** [comment]
The data is fed to the radio via the Lua source.  I can display the data on a telemetry screen, but I can’t play the value through the speakers for some reason. I have the old setup but switched to using the DJI goggles and air unit. Much better video. DJI doesn’t support osd from pixhawk. Didn’t have this problem on my x10s running open-tx.Sent from my iPhoneOn Dec 18, 2022, at 12:39 AM, Clifton Hipsher ***@***.***> wrote:﻿
What you want is not a function provided by your radio.
Telemetry data is provided to your goggles by an OSD (On Screen Display).  This device takes mavlink data from a serial port and combines it with the video signal from your FPV camera and then feeds that signal to the video transmitter.  I have 3 Pixhawk drones.  They all have FPV cameras and OSDs,  I also run Yaapu on ETHOS, OpenTX and EdgeTX.

**Comment by Target0815** [comment]
> DJI doesn’t support osd from pixhawk.

Of course ... https://fpv.wtf/

**Comment by williajgr** [comment]
Guess you didn’t read my last comments before you replied.Sent from my iPhoneOn Dec 18, 2022, at 10:45 AM, Target0815 ***@***.***> wrote:﻿

DJI doesn’t support osd from pixhawk.

Of course ... https://fpv.wtf/

**Comment by williajgr** [comment]
Why is it not an issue?  I can display the telemetry but can’t “play value” for the same telemetry.Sent from my iPhoneOn Dec 20, 2022, at 9:51 AM, Alessandro Apostoli ***@***.***> wrote:﻿

that got me halfway there. i can now display the telemetry but cannot "play value". for the telemetry. another small issue is that it doesn't display the same units that are displayed on yappu. ie . yappu displays ft and the telemetry is in meters, thanks for the help

Hi @williajgr  this is not an actual issue, you should close it here and ask for support on RC Groups (Ethos) or on my github

**Comment by yaapu** [comment]
Hi because

> Why is it not an issue?  I can display the telemetry but can’t “play value” for the same telemetry.Sent from my iPhoneOn Dec 20, 2022, at 9:51 AM, Alessandro Apostoli ***@***.***> wrote:﻿ that got me halfway there. i can now display the telemetry but cannot "play value". for the telemetry. another small issue is that it doesn't display the same units that are displayed on yappu. ie . yappu displays ft and the telemetry is in meters, thanks for the help Hi @williajgr this is not an actual issue, you should close it here and ask for support on RC Groups (Ethos) or on my github —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi, didn't mean to be rude sorry, perhaps I did not understand your issue.

Did you create a model special func to periodically play the value of a LUA source and it did not work or you don't know how to do it?

**Comment by williajgr** [comment]
yes i have a switch which when turned on I want the altitude to be played.  all i get is silence, but i can see the value on one of my telemetry screens in addition to the yappu screen. but it is interesting that the two telemetry screens read out in different units.

**Comment by yaapu** [comment]
> yes i have a switch which when turned on I want the altitude to be played. all i get is silence, but i can see the value on one of my telemetry screens in addition to the yappu screen. but it is interesting that the two telemetry screens read out in different units.

ok, excuse me again so I guess you need to opne/reopen it and change the title to somethink specific to the play issue, @bsongis-frsky should @williajgr open a new issue or better to reopen this one?

**Comment by bsongis-frsky** [comment]
You may change the unit in the sensor, no?
Why you cannot select the sensor in PlayValue?

@williajgr please change the title of the issue if it has nothing to see with yaapu (2*a, 1*p)!

**Comment by yaapu** [comment]
@williajgr this is not a yaapu issue, please remove it from the title.

@bsongis-frsky I tried enabling play value in a special func by using the provided "LUA Source" script and it fails as well (no sound)
![image](https://user-images.githubusercontent.com/30294218/209148448-93ee3421-0f61-45a8-9ddc-d2fa51054cc4.png)
![image](https://user-images.githubusercontent.com/30294218/209148648-f12e4b56-4314-481d-83d2-4771fac3eb79.png)

As soon as i switch to another source such as RSSI I get sound as expected

**Comment by williajgr** [comment]
Yo can change the units in the yaapu widget but one doesn’t see it in the list of sensors in the telemetry app.  One only sees the sensors in Lua sources.Sent from my iPhoneOn Dec 22, 2022, at 8:53 AM, Alessandro Apostoli ***@***.***> wrote:﻿
@williajgr this is not a yaapu issue, please remove it from the title.
@bsongis-frsky I tried enabling play value in a special func by using the provided "LUA Source" script and it fails as well (no sound)


As soon as i switch to another source such as RSSI I get sound as expected

**Comment by williajgr** [comment]
anyone working on this issue
