### ISSUE TITLE
Screens for Widgets

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2216]
Chýbajú Hlavné obrazovky.
![Screenshot_82](https://user-images.githubusercontent.com/85956904/208380100-93c0b872-7f92-4c19-a8d9-60d9aa166e3e.jpg)
Chce to viacej obrazoviek. Napríklad, stlpce pre 6S. LIPO.
![Screenshot_81](https://user-images.githubusercontent.com/85956904/208378260-9636590e-2ebb-4983-ba25-80bdee8736a8.jpg)
![Screenshot_83](https://user-images.githubusercontent.com/85956904/208381764-c8642e7d-d72d-4c0e-a014-0314d865bb61.jpg)
![Screenshot_83](https://user-images.githubusercontent.com/85956904/208384101-682f6760-0f83-4f25-88ea-3c8158bd08e1.jpg)

**Comment by jurajjurej** [comment]
Please add some main screens with 4 rows to the right, or 6 windows.
![Screenshot_255](https://user-images.githubusercontent.com/85956904/226284048-86c9b01d-9914-45bf-8aca-7f30348d5d9f.jpg)

**Comment by jurajjurej** [comment]
We want more splash screens.

**Comment by bsongis-frsky** [comment]
Someone can translate?

**Comment by jurajjurej** [comment]
What not to understand?
