### ISSUE TITLE
Timer Active Condition fails

### ISSUE THREAD

**Issue by weixelgeist** [FrSkyRC/ETHOS-Feedback-Community#2217]
The Timer Active Condition "Throttle Trigger" fails on my Tandem X20S with release 1.4.4
The timer starts when the transmitter is switched on without the throttle being actuated.

**Comment by mawzthefinn** [comment]
Can you post the bin file for the model in question?

It is working correctly on my X20 on 1.4.4

Please also make sure your throttle mixer is at -100 when you turn on the radio, if it's anything else you will get a phantom activation.

**Comment by weixelgeist** [comment]
Hi
it is the same with all my models
Gerhard

Am Mo., 19. Dez. 2022 um 15:22 Uhr schrieb mawzthefinn <
***@***.***>:

**Comment by weixelgeist** [comment]
Am Mo., 19. Dez. 2022 um 17:03 Uhr schrieb mawzthefinn <
***@***.***>:

**Comment by weixelgeist** [comment]
Am Mo., 19. Dez. 2022 um 17:13 Uhr schrieb Gerhard Weixelbaumer <
***@***.***>:

**Comment by weixelgeist** [comment]
Am Mo., 19. Dez. 2022 um 17:14 Uhr schrieb Gerhard Weixelbaumer <
***@***.***>:

**Comment by weixelgeist** [comment]
Am Mo., 19. Dez. 2022 um 17:14 Uhr schrieb Gerhard Weixelbaumer <
***@***.***>:

**Comment by weixelgeist** [comment]
I send it as *.gif
Please rename it to *.bin
![astir 6s](https://user-images.githubusercontent.com/57415068/208471534-c0b1d82f-620a-45c7-a421-319fe3e9b513.gif)
![funray](https://user-images.githubusercontent.com/57415068/208471535-7ceec340-52b8-49a0-9b64-c0e5d38a3fa8.gif)
![ka6 6s](https://user-images.githubusercontent.com/57415068/208471537-8d8526f6-28fc-4102-a005-2000c4638358.gif)
![oricon 6s](https://user-images.githubusercontent.com/57415068/208471540-30c3cb16-58a1-4231-9c26-7849e9237beb.gif)

**Comment by mawzthefinn** [comment]
Yes, I've got it this time.

Will test it and get back to you.

**Comment by mawzthefinn** [comment]
I just checked your 'Piper 8s' model and 'Prime Tundra 3S' model

Both are working correctly on my radio, the timer does not start until I raise the throttle.

Can you confirm you are seeing -100.0 on your throttle channel when your throttle stick is all the way down? 

If it's any higher, you should recalibrate your sticks.

**Comment by weixelgeist** [comment]
The throttle channel is -100 because I have a Throttle Cut Switch with -100%
The problem only occurs when the transmitter is turned on.
If you switch from one model to another, the timer does not run.
I have one more timer, the Motor timer with Active Condition "Throttle absolute"
This timer is showing 1 second when I turn on the transmitter.
Maybe this is the problem?

[Pictures.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10261592/Pictures.zip)

**Comment by mawzthefinn** [comment]
But is your stick down (no throttle cut) also at -100? 

When I repeat your test, I do not get 1 second elapsed, but rather 0.

**Comment by weixelgeist** [comment]
without throttle cut the stick is at -99.8 %

**Comment by mawzthefinn** [comment]
That's your issue, recalibrate the sticks, use a '+' pattern and only gently move the stick to the ends.

Once calibrated you should see -100.0 on the stick.

**Comment by weixelgeist** [comment]
I did the recalibration. Now I have -100% at 1 tooth before the end of the throttle stick.
The problem persists.

**Comment by weixelgeist** [comment]
If I start the Transmitter, the Motor Timer shows 1 second and the Gesamt Timer is running.
When I switch to another plane all timers are at 0

**Comment by weixelgeist** [comment]
I think the timers should stop at -99 ?

**Comment by weixelgeist** [comment]
And the Throttle Cut Switch should also work

**Comment by mawzthefinn** [comment]
As I noted, this is working correctly on my X20 on 1.4.4, I'm seeing neither behaviour with your model files.

Your throttle calibration should have corrected the issue, I'm not sure what could be causing it otherwise.

@bsongis-frsky any ideas?

**Comment by weixelgeist** [comment]
I have now found out that it has nothing to do with the throttle stick.
I created a new model. 
With this model, it doesn't matter where the throttle stick stands when the transmitter is started. 
It is sufficient to set the throttle cut to -100.

[xTester.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10261896/xTester.zip)

**Comment by mawzthefinn** [comment]
That's interesting that a new model works correctly for you, as the old models work correctly on my radio.

**Comment by Hartinger** [comment]
The problem could be related to the initialisation process. I had a similar problem where a timer that was triggered by a logical switch randomly started running on power-on or model change. I added a 0,1s delay to the logical switch and the problem disappeared. The logical switch compared a channel value with a constant of-50% and considering the throttle-cut, this switch should not become true on power-up. But apparently it does for a short period, and my guess is that the channel values are initialised with 0 before the throttle-cut kicks in. This then incorrectly triggers the logical switch.

We had similar issues in the past, which were partly fixed, but I think there is still a flaw in the initialisation process. The processing of any parameters in logical switches, or those related to the timer start options, needs to be suspended until the radio is fully initialised and settings like throttle-cut have been activated.

**Comment by Hartinger** [comment]
[This was the previous issue I mentioned above.](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1000)

**Comment by weixelgeist** [comment]
_"We had similar issues in the past, which were partly fixed, but I think there is still a flaw in the initialisation process. The processing of any parameters in logical switches, or those related to the timer start options, needs to be suspended until the radio is fully initialised and settings like throttle-cut have been activated."_

I think that is the problem

**Comment by Hartinger** [comment]
Maybe you add a delay, as I did, and check if the problem goes away.

**Comment by Hartinger** [comment]
Has a fix for this issue been implemented in the meantime? I am asking because I consider using the Throttle Trigger option for some models.
