### ISSUE TITLE
Helicopter Swash Types Menu Update/Change Request

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#2218]
Fairly simple and low priority, but I have some suggestions to update the heli menu to be a bit more intuitive and easy to understand, as well as add more options for more swashplate types.

From what I've gathered the only currently available options assume a 120deg swashplate.  However there are other helicopter swash types that require different mix ratios, such as 135deg and 140deg layouts.  I do not know off-hand what the ratio changes would be, but they should be options for those who are flying flybarred models and need these mixes pre-defined.  The 135 and 140 are pretty common for older models like Thunder Tiger.  

The selections should also be laid out in numerical order.  Once/if added, these options should be clearly labeled for each deg setting.  Like:

H-1 90°
H-3 120°
H-3 135°
H-3 140°
HR-3 120°
HR-3 135°
HR-3 140°
H-4 90°
H-4X 45°

Another suggestion, because most Flybarless gyro units all take a H-1 90° input (usually via S.Bus, but can also be done over individual cables), there is really no need for a separate selection specifically for Flybarless helicopters (currently Fly bar less).  Instead, simply changing the H-1 selection to say "H-1 90° (Flybarless)" should be sufficient. 

"Swashplate" is one word (that comes down to the EN translation of Ethos I suppose), and I think the menu should read "Swashplate Type" instead of "Swash Plate".

Finally, an option for "H-4X", where the swashplate servos are laid out in an X pattern 45deg out of phase should be added.  These are not very common but occasionally you'll see them on scale helicopters.

![image](https://user-images.githubusercontent.com/40482965/208511290-89e64da9-0bd7-4402-92a7-073219233794.png)

I've created a mock-up of what this would look like:
![image](https://user-images.githubusercontent.com/40482965/208510125-eedea9fb-f142-473f-824f-e05c8dbc3c41.png)
![image](https://user-images.githubusercontent.com/40482965/208511231-b6ff354d-521a-4364-8498-734f363e4b82.png)

**Comment by LuHaGH** [comment]
It would be great when it would be done like this.

**Comment by rtsx1cr** [comment]
what is the difference in the H-3 120 and the HR-3 120. i got a old flybar helicopter i want to set up again. a little unsure which swash plate to choice. i know it a 120.

**Comment by BladeScraper-Designs** [comment]
> what is the difference in the H-3 120 and the HR-3 120. i got a old flybar helicopter i want to set up again. a little unsure which swash plate to choice. i know it a 120.

It's the difference between having the center servo in front or in back.

**Comment by LuHaGH** [comment]
But be careful, some names are wrong or the mixers are working in the wrong SW Type
