### ISSUE TITLE
Request. Option to turn off telemetry only for 900 Mhz and only have telemetry on 2.4Ghz on TD receivers.

### ISSUE THREAD

**Issue by ola-aberg** [FrSkyRC/ETHOS-Feedback-Community#2220]
The servos in some of my airplanes where it is crowded are disturbed by the 900Mhz part in the TD receivers. It is not possible to select telemetry only for 2.4Ghz and have it off for the 900Mhz part. If possible, I would like to be able to turn off telemetry for only the 900Mhz part.

**Comment by arshish1612** [comment]
+1 on this

**Comment by mawzthefinn** [comment]
The latest TD receiver firmware (1.0.8 for TD R10 and TD R18, 1.0.9 for TDMX and TD R6) adds a 25mW Telemetry setting that resolves the servo jitter issues in my testing without requiring a full disabling of telemetry on 900M

**Comment by mawzthefinn** [comment]
Closing off, alternate mitigation has been implemented in latest TD receiver firmware
