### ISSUE TITLE
LUA: memory leak in forms handling code

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#2221]
Ethos 1.4.4

Hi,
I suspect a memory leak in the lua forms handling code, this is a variation of the servo sample lua.

LUA memory at startup
![image](https://user-images.githubusercontent.com/30294218/208648535-2503b92f-fc31-4652-8706-064997253da2.png)

LUA memory after a couple minutes
![image](https://user-images.githubusercontent.com/30294218/208648665-a88d0b5c-3999-42b7-b822-874f65adc2d0.png)

[leaktest.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10267659/leaktest.zip)

**Comment by bsongis-frsky** [comment]
And you didn't exit the screen between the 2 screenshots?

**Comment by yaapu** [comment]
I simply left it running

**Comment by bsongis-frsky** [comment]
I have checked popFrame(...) but it is not even called by this script. May I assume that no other script is running in the background?

**Comment by bsongis-frsky** [comment]
No doubt with the simulator, you are right

**Comment by bsongis-frsky** [comment]
If I remove the whole form I still see the memory leak

**Comment by bsongis-frsky** [comment]
The memory leak is freed when exiting / reentering the screen, so it's not exactly a memory leak

**Comment by yaapu** [comment]
ok, but if you wait long enough you eventually get the wakeup() not enough memory error

**Comment by bsongis-frsky** [comment]
I haven't said it is normal :)

**Comment by bsongis-frsky** [comment]
You have done the test on simulator only? or also on the radio?
On the simulator the gc runs far less often than on the radio!

**Comment by bsongis-frsky** [comment]
You will notice that on the simulator when you run your script the Clock is very very slow!

**Comment by bsongis-frsky** [comment]
These 2 problems (clock and Lua GC not running quick enough) are fixed if the 10ms timer runs in its own thread

**Comment by yaapu** [comment]
I have a much more complicated script which gave the not enough memory message and managed to kill the radio, so I made a progressively lighter version to detect the leak and the script I pasted is the result.
Same result on real hw

**Comment by yaapu** [comment]
> These 2 problems (clock and Lua GC not running quick enough) are fixed if the 10ms timer runs in its own thread

priority

**Comment by bsongis-frsky** [comment]
> I have a much more complicated script which gave the not enough memory message and managed to kill the radio, so I made a progressively lighter version to detect the leak and the script I pasted is the result. Same result on real hw

So my fix shouldn't be enough

**Comment by bsongis-frsky** [comment]
It is less obvious now on simulator but the fact is the number keeps decreasing little after litle, so there is something bad

**Comment by bsongis-frsky** [comment]
I have just made this script working. It needs the debug Lua lib though, but it worked on 2nd attempt

**Comment by bsongis-frsky** [comment]
It was a real memory leak, thanks for the report and script distillation, it helped a lot!

**Comment by yaapu** [comment]
> It was a real memory leak, thanks for the report and script distillation, it helped a lot!
You're welcome Bertrand, thank you for the quick feedback and fix!

**Comment by HolgerJr** [comment]
Hello,
I'm also having trouble running LUA. The LUA used does not show any errors either in the simulator in debugging mode or on the X20s and XEs transmitters when the transmitters are connected to the PC and checked with a terminal program. Not a single error message when using the LUA. But if I open a mixer and it stays open for a long time, the emergency mode comes on after 20 to 25 minutes on both the X20s and the XEs.
You don't even have to work in the mixer.

Greeting Holger
