### ISSUE TITLE
LUA: Button in form.openDialog does not close the pop-up window

### ISSUE THREAD

**Issue by MiRe-CZ** [FrSkyRC/ETHOS-Feedback-Community#2224]
X20 - Ethos 1.4.3, Sim - 1.4.4
The dialog window isn't closed after clicking on the button. It was running well in previous versions (not sure till which one)

local OK = {
	{label="OK", action=function() end}
}

local function Help_Button ()
	form.openDialog("Help", "XXXX", OK)
end

**Comment by bsongis-frsky** [comment]
you have to return True / False in your OK button

**Comment by bsongis-frsky** [comment]
Lua doc updated with an example

**Comment by MiRe-CZ** [comment]
Can you please publish the updated LUA doc?

Thank you
