### ISSUE TITLE
"Reset flight" does not perform checks

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2225]
It seems to be a bug. Invoking "Reset flight" does not check switches and pot positions. It just seems to reset timers and maybe telemetry, but does not execute preflight checks.

Expectation:
Radio state after "Reset flight" should be same like after "power on". So it should come with throttle waning if needed, invalid pot / switches positions etc.

**Comment by mawzthefinn** [comment]
This is the same behaviour as OpenTX has.

Reset flight clears all in-flight items (telemetry & timers) but does not reset pre-flight items.

**Comment by azaz44** [comment]
> This is the same behaviour as OpenTX has.
> 
> Reset flight clears all in-flight items (telemetry & timers) but does not reset pre-flight items.

This is not correct. Reset flight requires preflight checks again. This is how it works in OpenTX, EdgeTX, but also other radio brands like Spektrum. See here:

![Recording](https://user-images.githubusercontent.com/42830563/208871358-c52cd391-ca50-4e14-afd8-a6d688b39b42.gif)

In my opinion the rank of this issue is actually CRITICAL, because it is about safety. Starting a flight with wrong switch setup can lead to problems. The only way to make it right with Ethos is to turn off + turn on the radio before each flight.

**Comment by bsongis-frsky** [comment]
It needs to be checked

**Comment by mawzthefinn** [comment]
I stand corrected on that.
