### ISSUE TITLE
Invalid flight mode setup after reordering

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2228]
This is a small issue, it isn't very critical.

It is possible to get to invalid flight mode setup with following steps:
1. Create a new flight mode at the end of the list
2. Assign a switch to it as "Active Condition"
3. Reorder modes, so this newly create flight mode becomes the first one in the list
4. Now you end up in a problematic situation
   - The first flight mode has "active condition" which you can see on the list (which normally should not be possible)
   - if you "Edit" this flight mode, you don't see this active condition, so you have no way co clear it

Cheers..

**Comment by bsongis-frsky** [comment]
Right, good catch :)
I propose that we keep the Active Condition stored in the Flight Mode, but it is not used.

**Comment by azaz44** [comment]
> Right, good catch :) I propose that we keep the Active Condition stored in the Flight Mode, but it is not used, and not displayed

There's one catch with this solution, if user
- gets into the situation above, where first FM has "active condition" attached, but it's not visible nor used
- user reorders modes again, but after a year or sth
- then the first mode, moved to lower position will suddenly show an unexpected condition, which nobody remembered it was there

It's not crazy wrong, but maybe removing this condition when FM becomes the first one would be safer?
