### ISSUE TITLE
Vario tone is wrong - at sinking also interrupted only slower

### ISSUE THREAD

**Issue by NorbertHeli** [FrSkyRC/ETHOS-Feedback-Community#223]
Vario tone at sinking should be continuously to detect the difference to climbing. 

But the tone at sinking become deeper  (thats right ) but is also interrupted ( slower as climbing )

**Comment by aalain8** [comment]
I just tested.
horus X10 isrm + Ethos v1.0.7  
GR8 v2.1.7 receiver with unusable vario sound + sound delay.
GR8 receiver v2.1.5 very bad vario sound + sound delay.

horus X10 isrm + OpenTX 2.3.11
GR8 receiver v2.1.7 sound delay and does not cut at O.
GR8 receiver v2.1.5 very good.
V1.0.6 not tested.
alain

**Comment by NorbertHeli** [comment]
I tested with different Vario sources

- SM-GPS Logger
- FrSky HD Vario
- OSensor Vario

Today I got my X12S - I will test again. I had no dealay and fine resolution. Only at sinking NOT  a continously tone, also interupted as at climbing is, only slower.

**Comment by Hobby4life** [comment]
I can confirm the vario tone is not the same I am used too like OTX.
Slow and delayed.

**Comment by NorbertHeli** [comment]
I tested now with X20S 1.06 - it´s worse then my X12S. The vario tone is chopped up  ( suspend vor ~ 0,5sec )   and delayed. It´s really bad. I know the variotone from different  Sources ( fullscale Glider, rcelectronic GPS Trangle Racing, OTx and X20S Variotone  is so bad, I didn´t like to fly 10 min - but I often fly for hours in thermik.

So please - lift the tone to a good level.

**Comment by Hobby4life** [comment]
Flown again today with 3 different gliders. one has a better continues tone "pulse" then the other.. One model gives me only 2 beeps, then 1 second delay.. then 2 new beeps. Vario needs major fix,

**Comment by bsongis-frsky** [comment]
Fixed in the same time than #364
