### ISSUE TITLE
Twin X Lite S unable to update Ethos

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#2230]
Received my EU/LBT Twin X Lite S today and thougt I'd update to Ethos 1.4.4. It shipped with 1.4.3.
Connected it to Ethos Suite v.1.4.4 on PC and the radio was recognised in the menu on the left. However there was no icon displayed. 
Under Ethos/Update Your Radio, I could not select any radiobuttons in the update/release menu. 
Tried to connect my X20S and all firmware releases can be selected as normal...
---
Tried again to connect the Twin X Lite S to Ethos Suite and this time I got the option to update... 
However the update failed... Have had several attempts.
Maybe it can be looked into for 1.4.5 release???
![IMG_5918](https://user-images.githubusercontent.com/87149917/208922300-be62617b-5c0f-48bb-9c8e-68c4aefb2de6.jpg)
![IMG_5919](https://user-images.githubusercontent.com/87149917/208922305-87ccf9ae-2e58-4752-92d5-44aa9acbb0fb.jpg)

**Comment by mmasch** [comment]
After restarting the Twin X Lite and Ethos Suite, no possibility to select any firmware  :-(
![IMG_5920](https://user-images.githubusercontent.com/87149917/208923856-3855d576-958c-4577-932f-d1cd2142158a.jpg)

**Comment by Nicholas-Luoyi** [comment]
Will be fixed in the next release
