### ISSUE TITLE
BLE/USB telemetry - sending channels and RxID 

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2233]
Hello.

I think would be great send in BLE/USB telemetry:
 - packets with channels (maybe every 1/10s)
 - receiver identificator (maybe every second).
 
This would allow the following functionality to be implemented in phone/desctop app:
- change telemetry views use transmitter switches
- change telemetry views depending on the model
- use channels values for some analytics (for example, a graph of the dependence of the current (amperage) on the throttle position)

**Comment by mawzthefinn** [comment]
Receiver ID should be in the telemetry, it's currently exposed in S.Port telemetry on the radio.

As to channel data, S.port does not support channel data, but adding Fbus mirroring as an alternate option to S.Port may be a possibility in the future.
