### ISSUE TITLE
CRSF TxPower sensor range max value

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2234]
Hello.

Tandem X20, Ethos 1.4.5, ELRS 2.4 (25-1000mW).

CRSF TxPower sensor range has max value is limited on 100mW.
If select unit in Watt, range Min = 0, range Max = 0

**Comment by bsongis-frsky** [comment]
I have to upload again 1.4.5 so it will be fixed in a couple of hours
