### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by ola-aberg** [FrSkyRC/ETHOS-Feedback-Community#2236]
My Tandem XE-S could not be updated to 1.5.5 it went into emergency mode. Managed to flash back to 1.4.4.

The picture shows the status after I flashed back to 1.4.4.

/ Ola 
![fw 1 4 4](https://user-images.githubusercontent.com/57330785/209224003-a7143928-9403-49d1-bb5b-574594374374.png)

**Comment by Nicholas-Luoyi** [comment]
You mean you cannot find the 1.4.5 release?

**Comment by yak-54** [comment]
thats because its a Pre-release / beta so its not marked as stable for Ethos suite to use

**Comment by bsongis-frsky** [comment]
I wonder why your bootloader is 1.4.4, the right bootloader should be 1.4.3

**Comment by Dsrenger** [comment]
Hi Bertrand,

It is the same with my bootloader.

It is a XE-S. The bootloader in the 1.4.3 was not correct. Have a look at the size. 381bytes instead of ~43kb.

Therefore 1.4.4 got a new bootloader for the XE-S. I think, Andreas Engel found this issue.

I updated through the developer mode in the suite my XE-S from 1.4.4 to 1.4.5 l. But had to update every component individual as the update of the bootloader fails.
The suite is showing "greater than latest release" for the bootloader. But I think that's wrong. 1.4.4 is the latest bootloader for the XE-S.

**Comment by bsongis-frsky** [comment]
Are you sure that your bootloader is correct? Check the version in the top right corner

**Comment by Dsrenger** [comment]
1.4.4 in the top right.

Flashed manually from the GitHub release 1.4.4.

**Comment by Dsrenger** [comment]
Used this file

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.4.4/XES_BOOTLOADER.zip

**Comment by Nicholas-Luoyi** [comment]
Something wrong with our version file. We have fixed it. Please enable the dev mode and try Release 1.4.5 with "Update Outdated" or "Update All".

**Comment by Dsrenger** [comment]
Well test once I am at home from work.

Will get back to you.

**Comment by ola-aberg** [comment]
Fatal error occured
![fatal error](https://user-images.githubusercontent.com/57330785/209321707-cf19f0b6-b5a2-410f-b1ea-914f24982b96.png)
uploading crash file

[crash-2022-12-23.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10294367/crash-2022-12-23.txt)

The transmitters system did a reset and all was lost but i have a backup. 

When i try to restore the backup i get Fatal error occured again.
Restarted Ethos Suite, tried again same Fatal error occured
uploding new crash file
[crash-2022-12-23.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10294435/crash-2022-12-23.txt)

**Comment by ola-aberg** [comment]
Tried to use the Repair Tool ang got another error
![repair error](https://user-images.githubusercontent.com/57330785/209324682-2c755753-9709-4175-91c8-4708b659a0d4.png)
Uploading the crash file
[crash-2022-12-23.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10294518/crash-2022-12-23.txt)

**Comment by ola-aberg** [comment]
When i restarted the transmitter the system restored to default.
Men i utforskaren i min pc visade ingen radio enhet men en standard usb enhet visades med en models folder. Jag döpte om den till RADIO. Where does Ethos Suite store the backups?

**Comment by ola-aberg** [comment]
I managed to manually recreate models etc. from the backup.

**Comment by bsongis-frsky** [comment]
Would you send me an email? To be sure my fix is good before I release it again!
