### ISSUE TITLE
1.4.5 - Trim Mixer Issue

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2237]
> Trims now have a configurable range (not only 25% and 100%), and the Custom Step uses percent as step unit

When the Custom Step is set to 100, a) the Mixer value will only change by 1%. And b) only maximal plus/minus 1%.

**Comment by STC148** [comment]
Yes, there is something wrong with the trimmer, for example, if you set the range for T6 to 100 and the steps to 25 in the trimmer menu, and then select T6 as input in a free mixer, the output jumps to 100% at the first click.
![1](https://user-images.githubusercontent.com/85410070/209234857-319a92ca-3bd7-4934-8085-1d2ebc9d5eb6.jpg)

https://user-images.githubusercontent.com/85410070/209234909-1967b191-1600-41a2-8401-d951a34328b0.mp4

**Comment by Target0815** [comment]
@STC148 : I write about the Trim Mixer, you mean the Trim Menu ... Can be that there is also something wrong, but a new issue for it would be better.

**Comment by Target0815** [comment]
The existing trim mixers may also be running incorrectly. Could be critical ...

**Comment by bsongis-frsky** [comment]
I have been said that this bug is fixed in the same shot than the previous one, maybe you can help with a test before I release it?

**Comment by Target0815** [comment]
> maybe you can help with a test before I release it?

I'll be happy to, need the files for an X18S.

**Comment by bsongis-frsky** [comment]
Uploading files in 1.4.5 pre-release in a couple of minutes...

**Comment by Target0815** [comment]
> Uploading files in 1.4.5 pre-release in a couple of minutes...

Is there something wrong with the upload? After your message I checked regularly, but so far the new files are not visible. Therefore a test is not possible.

**Comment by Target0815** [comment]
The Trim Mixer is now working almost correctly. I have a problem with the following settings, but maybe just a comprehension problem:

![ethos_trim_mixer_1](https://user-images.githubusercontent.com/31627548/209718976-08ef0b87-820d-4e50-b675-6f41bfd93f48.jpg)

Step here is set to Custom with 10% (it's percent, isn't it?). If I do only one step, the output should be -82,5% (-75% plus 10%). But the output looks like this:

![ethos_trim_mixer_2](https://user-images.githubusercontent.com/31627548/209719164-6f33ddb2-55e5-44ca-9677-7c1553ad867a.jpg)

That is only 3,33% ...

**Comment by bsongis-frsky** [comment]
The % unit was missing, I have added it right now.
10% of 25% is 2.5% of the channel range, so it will move from -75% to -77.5%
