### ISSUE TITLE
Feature Request Ability to move models.

### ISSUE THREAD

**Issue by Sigee3** [FrSkyRC/ETHOS-Feedback-Community#224]
Can we please have the option to move a model from one category to another.
It would be useful if we could move or copy and paste a model from say "Airplane" to "Glider" or "Multi"

Thanks

**Comment by KevinFairgrieve** [comment]
Can I second this please.

In addition.
I.C.
Electric

**Comment by greggibbons** [comment]
Yes that would be great.
In addition.
Airplane to Heli

**Comment by bsongis-frsky** [comment]
Today a model has one fixed type (plane / glider / heli / multi / other)
Here you ask that categories are not linked to this type.
We could have subdirectories inside the Models root directory and allow to move models from one subdirectory to another

**Comment by bsongis-frsky** [comment]
i.e. a person with only planes could have "Indoor" and "Outdoor" directories

**Comment by Sigee3** [comment]
I am not asking for models to not be linked.
All I want is the ability to move them to a different catagory.
A simple "cut" and "paste" option is all thats needed.

**Comment by bsongis-frsky** [comment]
Today the type is written inside the model, and it is a very important information, as mixes / etc. are allowed or not, depending on this model type!

**Comment by bsongis-frsky** [comment]
If you want to move a plane to the heli category, you will have to change its type in Model / Edit

**Comment by Sigee3** [comment]
If I could move the model by editing it,that would be great. Unfortunately when I do move a model by editing it ALL mixes are reset.
If I could move them without resting the mixes that would be perfect.

**Comment by IJK-CZ** [comment]
> 
> 
> Today a model has one fixed type (plane / glider / heli / multi / other)
> Here you ask that categories are not linked to this type.

This would be exactly the best solution. Keep model type - plane/glider/ ... (which is bound with mixer options etc.) unchanged, but allow to sort them on display into user defined categories (like mentioned example Indoor /Outdoor) .

**Comment by bsongis-frsky** [comment]
@Sigee3 no we will have to move the mixes, you should know from the very beginning what is the type of your model, no?

**Comment by Sigee3** [comment]
As long as I can move them I dont mind how its done.

**Comment by TWSreviews** [comment]
I spent hours setting up a delta wing only to discover I was in gliders. Changed model type then lost all mixes. 
Why not just keep mixes as they are when changing model type? 
When I spend ages getting the first model correct I simply clone for the rest. 

No delta wing category for elevon mixing?

**Comment by AndyH56** [comment]
I would also like to change model categories on an existing model.   Why not add an option to **not** reset mixers when changing categories ?  There is already a warning message.
