### ISSUE TITLE
1.4.5 X20 EU some value conversion mistakes

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#2240]
![image](https://user-images.githubusercontent.com/78207054/209349937-b76868bf-dffc-4be4-a6b2-cdb1fa8b2fc6.png)
![image](https://user-images.githubusercontent.com/78207054/209350054-4c308798-8aa7-44ac-a3d8-88f7e95b2176.png)
![image](https://user-images.githubusercontent.com/78207054/209350895-0d4d38c3-570d-408f-9e37-19288554c25c.png)

it seems not all modells from Version 1.4.4 have this conversion issue and I'm not sure if I have already used all Modells in 1.4.4 - my previous version was 1.4.4 pre release
after some testing and  set the value to my old numbers it seems that all negative values will be set to some odd high positive values after each restart or change of modell. 
Merry Christmas

**Comment by yak55** [comment]
I can confirm this.
Have performed the update on X20S and XE.

Aileron differentiation -30% became +266%.

Am back to 1.4.4.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
I am afraid that all negative values are lost. I will remove all bins, it's critical!

**Comment by bsongis-frsky** [comment]
One of you send me an email with his setup? i.e. XES-FCC? I have fixed the 2 major issues of 1.4.5 and I would need one more test, because nobody met the issue, except me.

**Comment by yak55** [comment]
Hello, sent the data from my XE this morning.

The VAR mixer is the source for the differentiation!
