### ISSUE TITLE
Special Charaters msissing

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2242]
Special characters missing
TANDEM X20S, TANDEM XE Version: 1.4.5 EU Keyboard: QWERTZ
Language: GERMAN!!
Not accessible via keyboard

No improvement in 1.4.5 compared to 1.4.4

Problem should be fixed in 1.4.5!
NO IMPROVEMENT!

Grüsse Eugen

**Comment by mawzthefinn** [comment]
Which characters are missing?

**Comment by yak55** [comment]
Hi,
language is German.
Keyboard is QWERTZ.
Special letters in German:
Large: Ä Ö Ü
Small: ä ö ü
Attached:
4 photos ( 2 photos configuration ETHOS,  2 photos Smartphone keyboard german  with large and small letters )
Missing in ETHOS german: ä  -Ä Ö Ü
Best regards 

![IMG_5250](https://user-images.githubusercontent.com/85737356/209969683-f41d3898-508d-4e40-a092-5edc41a3e6b6.JPG)
![IMG_5251](https://user-images.githubusercontent.com/85737356/209969722-a7c4f31a-0643-4e2f-88ac-a8069a4d4db5.JPG)
![IMG_5252](https://user-images.githubusercontent.com/85737356/209969748-3deb5f3c-9f16-4048-a8c3-ef19efeed3e6.JPG)
![IMG_5448](https://user-images.githubusercontent.com/85737356/209969773-3a3485b5-9eb5-4202-ae74-e7998acf2b61.PNG)
![IMG_5449](https://user-images.githubusercontent.com/85737356/209969789-181dd89e-1c78-4a7a-abcb-c8b9613fe7e2.PNG)
