### ISSUE TITLE
[REQUEST] Implement file iterator function for lua

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#2243]
I want to adapt my LView log file viewer to ETHOS but there is no function to retrieve all log files. I want an option in LUA to itterate all files in a folder for the user to select. something like the dir function in EdgeTX would be great.

The alternative i use for OpenTX to check all possible log files for the current model does not work because of the time component in the log file.

**Comment by lthole** [comment]
Please prioritise this request. Having LView would be a huge advantage, giving the ability to view logs at the flying field without taking laptops etc!

**Comment by Storchy1** [comment]
I hhink it will be solved in 1.5.0 with the cmd system.listFiles(...)
see #2091

**Comment by bsongis-frsky** [comment]
Duplicate of #2091
