### ISSUE TITLE
No Frsky Passthrough on external module bay X12S 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2245]
No Frsky Sport Passthrough on external module bay X12S 

the internal ISRM 2.4 works Great with frsky Passthrough 
![access](https://user-images.githubusercontent.com/9161926/209418515-b867485b-9bda-4966-a069-f657b71dab57.jpg)

but on the external bay with R9M no sport data
i cant get any Sensors 

![R9M](https://user-images.githubusercontent.com/9161926/209418727-c0c31cb4-ebe5-45b0-965a-beccf212e692.jpg)

But the same setup with R9m i tested  with openTX as well  its just to check the hardware was working 

this all the sensors i get

![screenshot-2022-12-24-37860](https://user-images.githubusercontent.com/9161926/209418788-2a99c714-1bc8-434b-a599-0916914e99f9.jpg)

**Comment by bsongis-frsky** [comment]
Closed on purpose?

**Comment by yak-54** [comment]
I though after opening the issues it it may of been an script error on my behalf 
so there is no passthrough external module ?

**Comment by bsongis-frsky** [comment]
Yes it has been implemented in 1.4.5
I have just forgotten to write it in the News

**Comment by yak-54** [comment]
Thanks Again Bertrand

**Comment by yak-54** [comment]
it this in the latest pre release 27/12/22 ?

**Comment by bsongis-frsky** [comment]
Yes, it should

**Comment by yak-54** [comment]
still no joy 
this is the same radio on edgetx same hardware works fine
![20221229_085228](https://user-images.githubusercontent.com/9161926/209880755-d5f082db-a629-4bf9-97b0-5b421ea96430.jpg)

**Comment by yak-54** [comment]
i have test it on 2 X12S and it does not work i tested it all hardware under edgetx works fine 
with a  R9M and R9 receiver ethos 1.4.5 not working
XJT and RX8R not working 
but if i turn off the extural module bay to on the ISRM in D16 the RX8R works fine
![screenshot-2023-01-01-36441](https://user-images.githubusercontent.com/9161926/210157284-3ed8cb0b-1cc5-4c76-bf1f-c127f3ce0cd6.jpg)

**Comment by hyperion11** [comment]
same problem with Twin X Lite and R9M Lite Pro Access. Have try with R9Slim+OTA and R9mm receivers. No telemetry.
TW MX and R-XSR telemetry working
![photo_2023-03-30_23-22-27](https://user-images.githubusercontent.com/13326299/229024769-c6ee42d8-e672-45e1-98f5-8fe3f86d02cc.jpg)
![photo_2023-03-30_23-22-27 (2)](https://user-images.githubusercontent.com/13326299/229024776-dd9bc355-5f9e-4d6e-8fa6-2cae920bcfc4.jpg)
![photo_2023-03-31_09-00-20](https://user-images.githubusercontent.com/13326299/229024778-d48ca599-97c4-4f1c-925d-cbd0f6b15738.jpg)
![photo_2023-03-31_09-00-20 (2)](https://user-images.githubusercontent.com/13326299/229024780-a493561b-5883-4ef3-8470-7d8597440694.jpg)

**Comment by yak-54** [comment]
yep not working on 1.4.7 on X12s as well yet

**Comment by hyperion11** [comment]
@bsongis-frsky Is there any information about when this feature will work? Very necessary.

**Comment by bsongis-frsky** [comment]
Email sent to Yaapu

**Comment by hyperion11** [comment]
internal module work with Yaapu in TW and access X modes

**Comment by yak-54** [comment]
> internal module work with Yaapu in TW and access X modes

yep it works with 2.4 internal ISRM module fine
just not with any module in the module bay
tried R9M 2019 and R9M accst fcc and flex R9 fcc and flex on accst and and XJT module with an rx8r

**Comment by hyperion11** [comment]
hello @bsongis-frsky any news about this problem?

**Comment by Zadrob** [comment]
Hello, I confirm the same behavior on Tandem XE. Yaapu script works fine on internal module. No telemetry (passthrough) from external module. I can see any other sensors from external module (rssi, voltage, Li-Po (FLVSS), even GPS which comes from Ardupilot). Yaapu script can see RSSI, LiPo voltage, but no passthrough data. 
I am thinking to try temporary solution - maybe adding 2.4G receiver just for telemetry link a linking it to internal module.

**Comment by hyperion11** [comment]
@bsongis-frsky when you fix this problem?

**Comment by nightfury24** [comment]
Well that’s interesting. Few days ago I open the issue and the developer closed it, stating report to yappu, it’s a lua script issue.

**Comment by hyperion11** [comment]
when if will be fixed?

**Comment by martan223** [comment]
i have the same problem on Horus X10 express, iternal module + X8r works flawlessly, r9m + r9 slim does not (stock sport telemetry works tho). i even tried modify the lua script to have ability to change temeletry source to "external sport", no success.

**Comment by hyperion11** [comment]
https://github.com/yaapu/FrskyTelemetryScript/issues/222#issuecomment-1796188990
so this is not ethos issue

**Comment by yak-54** [comment]
this issues is on the way to be fixed have tested works with R9m on flex on ethos 1.4.13
this is not ethos issue
