### ISSUE TITLE
1.4.5 pre-release was Emergency mode on X20S 

### ISSUE THREAD

**Issue by MixerFightingFalcon** [FrSkyRC/ETHOS-Feedback-Community#2249]
The Emergency mode show on screen when turn on X20S

**Comment by bsongis-frsky** [comment]
It should be good now, please update again!

**Comment by MixerFightingFalcon** [comment]
Thank you very much

ในวันที่ พ. 28 ธ.ค. 2022 16:47 น. Bertrand Songis @ FrSky <
***@***.***> เขียนว่า:
