### ISSUE TITLE
X20S - Bluetooth doesn't remember paired devices headphones

### ISSUE THREAD

**Issue by TWSreviews** [FrSkyRC/ETHOS-Feedback-Community#225]
Paired earbuds and was great having telemetery feedback in my ear but when you turn off and back on you have to pair it all over again. 
Shame.....

**Comment by MIKE-DAILEY** [comment]
Release 1.0.6. will have a X10S firmware version that solves the issue.

**Comment by TWSreviews** [comment]
> Release 1.0.6. will have a X10S firmware version that solves the issue.

I am looking for X20S

**Comment by MIKE-DAILEY** [comment]
Typo, yes X20S.
