### ISSUE TITLE
Twin X Lite S not reading model files on SD card

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#2250]
Have just received the Twin X Lite S, I would like to copy my model files to the SD card in the transmitter. 
Have gone into "System/General/" and sat "Storage location" to "SD Card".
All my model categoris and models from my X20S has been placed on the SD card, but when I go to "Model/Model Select", all I see is my categories (Glider/Indoor/Planes/Sim) but they have no contents. 
If I go to "System/File Manager" and choose SD Card I see the folder "Models". I click that and see my categories, and if I click "Glider" I find my three glider models that I have programmed.

Twin X Lite S, Ethos 1.4.3 EU.

**Comment by mawzthefinn** [comment]
What version of ETHOS is your X20S on?

You will need to update your TWIN X-Lite if your X20S is on 1.4.4 or later

**Comment by mmasch** [comment]
Thanks for reply Mawz. That may explain the problem.
I have now X20 Ethos 1.4.4 and Twin X Lite Ethos 1.4.3.
Will try to update both to 1.4.5 when it is publicly released.
Hopefully model files can be interchangable between X20 and X Lite...

**Comment by mawzthefinn** [comment]
I can confirm that once you have everything on the same version, it will work. I pre-loaded my X-Lite with models from my X20 and X18 with no issues beyond needing to adjust switch layout. All radios were on 1.4.4.

NB the importing radio must be on the same or later version than the exporting radio.

**Comment by mmasch** [comment]
1.4.5 is live. 
Updated both radios, and I'm able to select all the models copied from X20S from the SD card.
Thank's maws  :-)
