### ISSUE TITLE
Enhancement: Free S-BUS Channel configuration/assignment

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#2252]
In a function model I will use the Archer SR8 with PWM outputs (with Stability mode) for servos and the S-Bus for a sound module with a lot of sounds. 
Using an Archer SR8 Pro Receiver, several channels for the stability mode are predefined and not possible to change. 
If I use now the S-BUS, Channel 1-16 are predefined as well and overlapping. So I loose a lot of free channels on the S-BUS.
Changing to 24 CH mode doesn't help, because the channel 17-24 can not be used. 
I would like to be able to assign any of the ETHOS channels free to the S-BUS channels. Using the 24CH mode then, I can use then much more free channels via S-BUS. The configuration might be done in the same way as the assignment from the channels to the PWM-hardware Outputs.
This function might be useful also for many other use cases. 
The S-BUS is then not fixed and limited to CH1-16 any more.
Making this possible would be great:
Best Regards
Bernhard

**Comment by mawzthefinn** [comment]
This would be a Receiver firmware change.

**Comment by BernhardFe** [comment]
Ok, you are right. Looking deeper it is clear, because the S-Bus gets also the signals from the stability correction. 
Nevertheless this would be useful. Then all the 64 channels might be able to map to the s-Bus signal and not only the fixed 1-16. It would be great if this can be forwarded to FrSky firmware developers. :-)

**Comment by Target0815** [comment]
SBUS and the channels 1-16 are a manufacturer-independent standard. It is better **not** to change this. 

The problem is rather the preassignment of the channels in FrSky's Stabi receivers. There this belongs freely configurable and would upgrade the Stabi receivers considerably.

**Comment by BernhardFe** [comment]
You are right, it might be better to make the Stabi outputs configurable if S-Bus is seen as a standard.
