### ISSUE TITLE
Twin X-Lite S Display Sleep Mode

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#2253]
On the twin x-lite S, the display does not enter sleep mode with the screen in the up position. Unsure if this is intentional or not but it would be beneficial if it would

**Comment by mawzthefinn** [comment]
I believe it's intentional, there's a switch detecting the screen position which enables sleep in the retracted position.

That said, I'd like to see Sleep available in both modes and the position detection used for wakeup rather than locking out sleep.

**Comment by mawzthefinn** [comment]
1.4.6 will allow the display to sleep in both positions

**Comment by bsongis-frsky** [comment]
In 1.4.6 the system won't worry about the state of this LCD (open = closed = no impact on inactivity / sleep)
In 1.5.0 we will add a setting
