### ISSUE TITLE
SR10 PRO does not execute self test

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2257]
Having issue #2255 resolved, Now hitting the self-test switch three or more times (momentary switch) still the unit does not enter in the self-test routine (channel 12). I guess I am missing something. I followed the video https://www.youtube.com/watch?v=rUKIBQdmvIY&ab_channel=Mr.D-Fallingwithstyle in detail, but I cannot have the RX to do the self-check.

**Comment by mawzthefinn** [comment]
This is correct behaviour. 

Self-check was moved to the SxR menu with the 2.1.10 receiver firmware. Please check the current published SR10 manual for the full procedure (there are other changes as well)

**Comment by Richrfl** [comment]
I understand, and actually, I didn't even know that self-check could be set in any way other than through the SxR menu. As you can see in the attached I have it on and still got nothing. Now, here is the interesting thing that tells me that something is wrong, and I don't mean the code or hardware, but the question is: if I set the self-test on, why does when I recycle power in the receiver the SxR menu show me that self-test is off? 
![screenshot-2022-12-29-37837](https://user-images.githubusercontent.com/9392774/209967337-b630267a-3a3b-4e75-b83e-5aff6e31858b.jpg)

![screenshot-2022-12-29-36522](https://user-images.githubusercontent.com/9392774/209967339-389b63bb-6b27-4950-b0e2-34ce48b86eda.jpg)
![screenshot-2022-12-29-36554](https://user-images.githubusercontent.com/9392774/209967341-6e7435e9-c7a5-421c-a58f-a6bdbdbe9f00.jpg)
![screenshot-2022-12-29-36557](https://user-images.githubusercontent.com/9392774/209967342-df8df5c1-09a4-45d1-a6f8-adfee5c908b1.jpg)
![screenshot-2022-12-29-37577](https://user-images.githubusercontent.com/9392774/209967343-c58613b6-e19e-48e9-84f1-081168fcdff5.jpg)

**Comment by mawzthefinn** [comment]
The initial self-test state is read from the receiver. That's why it flips off when you power cycle the receiver.

Ch3/Throttle needs to be at -100 for self-test to engage as well as the self-test switch being set to on in the SxR menu

Ch12 does not do anything related to self test on v2.1.10 and later.

**Comment by Richrfl** [comment]
On Thu, Dec 29, 2022, 9:49 AM mawzthefinn ***@***.***> wrote:

> The initial self-test state is read from the receiver. That's why it flips
> off when you power cycle the receiver.
>

Ok, if I got it right, first thing I have to do when I power up the
receiver is to go to SxR menu and switch self-test to on, then, run the
self-test and go from there. Is that right?

> Ch3/Throttle needs to be at -100 for self-test to engage as well as the
> self-test switch being set to on in the SxR menu
>
> Yes. I always have the ch3??? Oh, pup!!!!! When I created the model I set
throttle in ch4, and rudder to ch3 as I usually do. Not surprising, when I
move the rudder to -100 everything works fine.

>
> Ch12 does not do anything related to self test on v2.1.10 and later.
>
I don't understand this one, but the issue is solved.

**Comment by Richrfl** [comment]
My mistake. Assigned the throttle to the wrong channel. It seems the code uses Channel 3 to block/enable self-test. 
Issue is soved.

**Comment by mawzthefinn** [comment]
1. Yes that's exactly correct.

2. The FrSky stabilized receivers require that you use AETR channel mapping, you cannot use alternate channel mappings and have stabilization work. note you can re-assign the pins on the receiver so you plug your servos in as you normally do (Pin assignment is downstream of stabilization), so long as the radio is sending AETR for the first 4 channels and ch9-12 are also assigned for stabilizer control or unused.


3. You can delete all your self-check mixes on Ch12, they won't do anything.

**Comment by Richrfl** [comment]
OK. Actually, I like how the self-test works. Still, CH 12 can be used for the "PANIC" button. That works fine. I guess I am pretty RTF with all these issues solved.
Thank you for your help.
