### ISSUE TITLE
Sensor A4 (capacity) for non-Frsky not working

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#226]
Hello,

at the moment it is not possible to use non-Frsky telemetry sensor **A4** (capacity) to show used mAh. 

Please try to fix it.

Thanks a lot 🙂

**Comment by islandflight** [comment]
The capacity used sensor does not display for YGE esc as well as the sm modelbau sensors. The YGE reports as percentage fuel rather than mah. I don't understand how the address system works but the YGE is at port 0600 whereas the neuron esc capacity sensor is at 0B60.

**Comment by combat-marcus** [comment]
So the sensor manufacturer of mine has to update the sensor adress?

**Comment by islandflight** [comment]
Possibly I'm not sure I'm not a programmer. Open tx had a calculated consumption sensor so receiving consumption data directly from the sensor was not necessary although probably not as accurate as receiving the consumption data directly from the receiver as you are relying on the frequency of the transmitted current value for a calculated sensor. Unfortunately ethos does not have a calculated consumption sensor but this has been requested so hopefully will happen soon. I have emailed YGE to see ifvthey will investigate from.their end but not yet had a reply.
