### ISSUE TITLE
Analog filter On/Off should be model specific and not a System setting

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#2260]
For people that fly models with and without a flight controller, it would be better if the setting was model specific. Currently it is in System / Settings consequently when you switch from say a quad/INAV model to a conventional plane you need to remember to change the ON/OFF Filter in settings.

**Comment by Target0815** [comment]
> it would be better if the setting was model specific.

Why? What advantages would ADC on or off have with or without flight controllers?

**Comment by miggy1952** [comment]
It’s recommended to turn ADC filter off for multirotors to reduce control latency. However it’s a useful feature for wings and planes as it smooths out servo commands and jitters.

**Comment by miggy1952** [comment]
Early versions of EdgeTX ADC filter used to be a global option, it affects all models. But EdgeTX 2.7 fixed that problem.

In EdgeTX 2.7, ADC filter is now an option in the Model Setup page. You can now set it to “Global”, “Off” and “On”.

This is great news if you fly both quads and wings and use different model profiles for them.
