### ISSUE TITLE
Suite feature request - csv viewer 

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#2263]
It would be good to have the ability to view log file .csv displayed in a chart (similar to OTX Companion) within ethos suite. Something where you can select your variables from the list within the .csv to plot a graph so the data is more easily interpreted. (here is an example - https://www.csvplot.com/ ). If ethos suite could convert the GPS logs into the format required to view a trace on google earth that would also be useful. (KML? Issue #1708 relates).

The ability to manage log files, delete or download through suite would be nice too.

It occurs to me that many people who might want to view logs may not be easily able to deal with the .csv format. A nice viewer option in the toolbar of ethos suite would be a great addition.

**Comment by BladeScraper-Designs** [comment]
+1 to this

**Comment by koakumaping** [comment]
+1 to this
