### ISSUE TITLE
Show all options in the Active Condition category list, but grey out non-available categories

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#2264]
### Allow logical switches for active condition of trainer
Currently, if being the master transmitter. The only way we can activate the trainer function (student has control) is by using one of the following categories:
- `---`
- `Always On`
- Switch Positions
- Function Switches
- Trim positions
- System Event

It would be very useful to be able to use **Logical Switches** here. The you could set up situations like *Activate student control with a momentary switch. Take back control by moving a gimbal* or simply using a sticky on a momentary switch. To be honest, I think **Logical Switch** activation would be far more useful than **System Event**.

## New request
Using logical switches is possible in the trainer for the **Active Condition**. The issue is, if you don't have any logical switches set up, the option is removed from the category list. This can lead to believing the option is not available. I think a better solution would be to show the option. But, grey it out an not allow it to be selected. This way, you can always see which options can be used, if they have been set up.

**Comment by mawzthefinn** [comment]
I just checked and Logic Switches work just fine for engaging Trainer functionality. Tested on 1.4.5 on an X20

Note they have to exist already on the model or the Logic Switch option will not show up.

**Comment by mawzthefinn** [comment]
Closing off as this does work correctly.

**Comment by MrD-RC** [comment]
Ah that sucks. It would be more useful if the option was still in the list. It was just greyed out so you couldn't select it. At least then you would know it was available.

**Comment by mawzthefinn** [comment]
That’s a good idea. I’m re-opening so you can change it

**Comment by bsongis-frsky** [comment]
In this widget (roller / multi-column roller), we only show the available choices!
