### ISSUE TITLE
 the fas-100 sensor is now supported but gets the wrong value #2036 

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2265]
1.4.5 now reads the sensor but gets the wrong values.
i put the discrepancy for voltage and current  in issue #2036
 almost there.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/210136481-4bb3138a-1e17-4765-8a51-f01827d706bf.png)
