### ISSUE TITLE
Digits should rather be monospaced in font files

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2266]
Ethos uses proportional (non-monospace) fonts, which is great.
However the weird thing is, digits also differ in width. See here:

![image](https://user-images.githubusercontent.com/42830563/210116641-6073567e-d405-40fc-b24f-0e2ed0874cd8.png)
![image](https://user-images.githubusercontent.com/42830563/210116880-890f055a-dc63-461c-84f7-4f6d49f6566c.png)

Which makes it super hard to make nice formatting with numbers. See here (double-colons not aligned):

![image](https://user-images.githubusercontent.com/42830563/210116687-b715d715-d767-4099-9312-6bf2f9c62474.png)

While this is used in some specific fonts, it is super rare. You only use it in some very specific, artistic fonts, for applications which have nothing to do with numbers. All typical fonts avoid having digits in different widths, because this causes a lot of trouble. See here:

![Recording](https://user-images.githubusercontent.com/42830563/210116772-466f375d-e444-40f7-b446-175d1231434a.gif)

Life would be so much easier, if digits were all same width...

**Comment by azaz44** [comment]
By looking at screenshots I made, I started to wonder if this is not a problem if a font itself, but if this is a drawing issue, or if font was processed / generated with some errors on the way. If you look at this image:

![image](https://user-images.githubusercontent.com/42830563/210117111-e737e917-e537-4981-9157-6a3d1d5a3367.png)

It looks weird. It doesn't make any sense, that `1` is same width as `8`, but `0` and `7` are much wider.

**Comment by bsongis-frsky** [comment]
It looks weird indeed, I will check it carefully

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/210319844-3d8eef40-a7da-474f-9490-7558f0668073.png)

**Comment by bsongis-frsky** [comment]
In 1.4.6, all numbers will have the same width

**Comment by azaz44** [comment]
Great to see this, thanks 👍
