### ISSUE TITLE
X20S cant  update via Suite (V1.4.5)  the X20S from V1.4.4  to V1.4.5

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#2269]
Suite tells me that  a X20S with V1.4.4. ist  up to date

cant update the X20S from V1.4.4 to V1.4.5 with the Suite

 
![image](https://user-images.githubusercontent.com/6217896/210207059-8a10eb88-402d-4bad-b480-40dcdbf39aaf.png)

**Comment by bsongis-frsky** [comment]
Have you restarted Ethos Suite before or after release 1.4.5 is out?

**Comment by hrenz** [comment]
Have deinstalled the Suite V1.4.5 and then new installed the Suite V1.4.5 again
PC restart
Now its ok,

Issue can be closed
