### ISSUE TITLE
écolage x12s os 1.0.5

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#227]
hello frsky.
x12s os 1.0.5.
Why did you limit the training to four ways?
How to make try are big model to a buddy in double control with four ways?
thank you for your responce.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/118647550-c07eeb80-b7e1-11eb-8aa1-9c1d96c9039c.png)

**Comment by bsongis-frsky** [comment]
You may use any trainer channel as a source
