### ISSUE TITLE
memory leak when using LUA and open mixer

### ISSUE THREAD

**Issue by HolgerJr** [FrSkyRC/ETHOS-Feedback-Community#2272]
Hello,

there is a memory leak when using LUA and leaving a mixer open for a long time. You don't even have to work on the mixer. It's enough if it's open.
I have the following test environments:
the LUA is the Pistenking Kingpad
transmitter X20s with ETHOS 1.4.4
XEs with ETHOS 1.4.5

the LUA does not show a single error in the X20 simulator in debug mode
there is also no error when monitoring the transmitter with a serial connection to the PC and using a terminal program for monitoring

if no mixer is open, I haven't been able to detect any memory loss

if a mixer is opened and remains open, ETHOS 1.4.4 goes into emergency mode after about 25 minutes
sometimes it is faster or takes longer

with the XEs and ETHOS 1.4.5 there was no more emergency mode, but after a long time (over an hour to hours with the mixer open) the LUA crashes, the widgets of the LUA are only gray (without content) and the LUA is logged off in the model config
In addition, the transmitter's user interface becomes extremely slow, sometimes to the point of being unusable

if you switch the transmitter off and on again, everything is back to normal

since I could not see any errors when monitoring the transmitter or in the simulator in debug mode, I integrated write commands for the memory allocation into the LUA

if a mixer stays open for a long time and if you go back to the LUA widget, you can see that the memory is getting less

see following pictures

**Comment by HolgerJr** [comment]
the pictures
![screenshot-2022-12-30-3047](https://user-images.githubusercontent.com/121034000/210281428-2c7d962d-2277-4a2e-9751-85844f6b99ec.jpg)
![screenshot-2022-12-30-3075](https://user-images.githubusercontent.com/121034000/210281436-3c6b3855-49d1-4669-8fea-2cf65955a5c8.jpg)
![screenshot-2022-12-30-4818](https://user-images.githubusercontent.com/121034000/210281443-136c1309-3a52-422b-805f-2510eb8414b5.jpg)
![screenshot-2022-12-30-5274](https://user-images.githubusercontent.com/121034000/210281449-95d27e2f-2bd4-4aa3-b2eb-9da6170ca284.jpg)
![screenshot-2022-12-30-16226](https://user-images.githubusercontent.com/121034000/210281461-dbdefe77-7cc2-4048-b6fa-508c05c64418.jpg)
![screenshot-2022-12-30-16236](https://user-images.githubusercontent.com/121034000/210281470-a480ae3d-2adb-4445-aae0-29c55b861f0c.jpg)
![screenshot-2022-12-30-18477](https://user-images.githubusercontent.com/121034000/210281479-f72e2f22-122e-4e42-b18a-7fead9a5d075.jpg)
![screenshot-2022-12-30-18584](https://user-images.githubusercontent.com/121034000/210281490-f01b93c3-e8b8-4533-96fb-b6202d2b4cad.jpg)
![screenshot-2022-12-30-18590](https://user-images.githubusercontent.com/121034000/210281499-1a0d6038-739f-4ed2-a2bf-c08fc6232efa.jpg)
![screenshot-2022-12-30-18595](https://user-images.githubusercontent.com/121034000/210281507-28ffd4aa-cd0a-41d8-a2d9-f0983da39d90.jpg)

the last 3 pictures were taken after restarting the transmitter

best regards
Holger

**Comment by HolgerJr** [comment]
unfortunately, I was not able to get the moment when the memory is almost zero, but only the moment when nothing is displayed in the LUA widgets

then there is no longer any output of the memory values

**Comment by HolgerJr** [comment]
here is the LUA used

[Smart Kingpad V0.4.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10333636/Smart.Kingpad.V0.4.zip)

**Comment by HolgerJr** [comment]
If no mixer is open, there is no memory loss
see picture 4 and 6, not even for hours (see time in the display)

**Comment by bsongis-frsky** [comment]
Would you please try with the latest 1.4.5?
Yappu reported the same issue and it has been fixed in 1.4.5

**Comment by bsongis-frsky** [comment]
In your script the colors may be just a global, no need to return it in the create function

**Comment by HolgerJr** [comment]
The documented test (pictures) was done with Ethos 1.4.5 on the XEs

I didn't create the LUA myself. I only use them. I'll look for the create function.
Should I delete the relevant lines?

**Comment by HolgerJr** [comment]
Another hint:
If the mixer is only opened briefly, no memory is lost.

**Comment by Benno00** [comment]
Hello Bertrand,
I have now made a recording as well as logged the memory.
here two screens from the simulator once smaller <0 KB.
and also like this is OK >0 KB.
In the "mem.csv" log you can see exactly how the memory keeps falling below 0 KB.
In the approx. 3 minutes, the LUA memory was <0 340 times.

Greetings Benno

Log Datei 
[mem.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10343092/mem.csv)

Memory ok
![memory ok](https://user-images.githubusercontent.com/97786547/210532844-2cda31ab-1dbd-406d-93ae-dad63d0d56e5.png)

Memory low
![memory low](https://user-images.githubusercontent.com/97786547/210532859-c87413ec-4727-4a06-937d-f78043877ff5.png)

**Comment by Benno00** [comment]
Problem no longer occurs with newer versions, can be closed
Thanks very much
Best regards , Benno

**Comment by mawzthefinn** [comment]
Closing as fixed
