### ISSUE TITLE
CRSF/ELRS Rx Curr and Cons sensor range maximums too low

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#2273]
FrSky X18 with Ethos 1.4.5
Happymodel ES24TX Slim Pro with ELRS 3.1.2

1. Maximum range for the `Rx Curr` sensor is only 10.0A and can not be set higher.
2. Maximum range for the `RX Cons` sensor is only 2,000mAh and can not be set higher.

I am not sure what the maximum for `Rx Batt` _should_ be for CRSF/ELRS, but at least it will go up to 50.4v. I imagine it should be able to accommodate 14S at 58.8v? Or even higher than that for headroom with poorly calibrated voltage sensors?

I have already tried deleting and rediscovering the sensors since updating to Ethos 1.4.5.

**Comment by bsongis-frsky** [comment]
In 1.4.6 limits will be 100.0A and 20,000mAh

**Comment by rburrow87** [comment]
Thank you!

If possible, 300 or even 400.0A would be better. Larger electric airplanes and helicopters easily hit 200A.

**Comment by bsongis-frsky** [comment]
Done
