### ISSUE TITLE
Preflight checks are not cleared by 'Press any key to skip'

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2274]
Ethos 1.4.5

After Issue #2231 'Better confirmation of preflight checks' was implemented, the alert to 'Press any key to skip' must be changed to 'Press OK or RTN to skip'.

**Comment by bsongis-frsky** [comment]
I think that just an "OK" button would be enough, and consistent with other Dialog Boxes

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/210324337-1be6921e-966e-43f2-a455-19899bec27fa.png)
