### ISSUE TITLE
Github "Stale Bot" is a very frustrating process for contributors. Kindly please improve the backlog process.

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#2275]
Hello developers,

the new "stale" bot closes a lot of issues that have been not touched the last 30 days. 

For me it is frustrating even if the response or problem solving is often not given/possible in this time frame. Of cause, there are a lot of issues in the backlog, and I understand that this all can not be done in a short time but more on long term. Therefore we have the backlog to keep issue that should not be forgotten.

There are several working styles but maybe the following easy process make it better as today?
1. Collect all issues and mark them as open ore reject when they com in within 30 Days.
2. If issues open, assign them to a very rough release plan. 
3. On short term decide on priorities with your team and take the priority open issues in the next release and adjust the over all release plan if needed. Take them out of the backlog and close them not before they are accepted and checked by the contributors. A bot can close released issues when there is 30 days no feed-back.
4. Close an issue if this is implemented only, otherwise reject.
5. Please switch off the stale-bot, because I as a requestor have no chance to take the stale label away or to adjust any label. 

The behaviour to close issues by a bot without reject/open/feedback or discuss them is very frustrating for contributors like me. This can happen also when a issue is just under discussion.
To keep contributors motivated to get a continuous improved product and a great contributing community, please think about your process in the sense of GitHub behavior.

This just a kindly hint, because I was not able to find a general address to write this 2 cents personally.

Best Regards
Bernhard

**Comment by bsongis-frsky** [comment]
I do agree it is too quick. Delays increased (90 days + 30 days)
I review all stale issues as I receive an email each time it happens something on this repository.

**Comment by BernhardFe** [comment]
Maybe also a little change of your process playing with the status: new, open, in work, closed, reject. Maybe it helps you to get all easier organised. Then you need no stale bot. 
If you really need this, the bot may take the label "stale" away if there is a response.

**Comment by mawzthefinn** [comment]
Note the bot already removes the stale label after a response, it happens the next day though.

**Comment by BernhardFe** [comment]
Ok, now I saw it on older issues, but what happens if it is once added and removed and then discussed? You may add a condition that this is not taken to Stale, if it is waiting for beeing resolved in future. Coming back to my hint above. You may need some more status as a Label to organise the backlog.

This might be a proposal that is also used in projects I know:
New: all coming in and untouched.
Open: Under discussion and commented once at a minimum.
Reject: Will be not done
In Work: Ready for a release and assigned
Done: Proposed by a release
Closed: Work is done and issue solved and tested

In consequence a stale Bot should touch New issues and may reject after a while the New issue.
Additionally it can close a "Done" issue after a while when nothing happens automatically.

In this backlog there is for me not clear what status an issue has and if it is planned for a release anyhow or not and when.
Maybe you use for development internally more status I can not see. But more logic and transparence might help to have a better impression what's going on.

Is there any description how the workflow is defined in this backlog to have a better understanding?
