### ISSUE TITLE
Suite - Choice of sound pack 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2277]
It appears that when upgrading from 1.4.3 to 1.4.5 a new 'english' sound pack has been used (not sure if 1.4.4 or 1.4.5 introduced that). However this appears to be an American sound pack. 
If default sound packs are going to be changed, please can the Suite give us an option as to what sound pack we want, whether that be the old English sound pack or the new American one.
Thanks

**Comment by bsongis-frsky** [comment]
The sound packs are build with the latest Google TTS
https://cloud.google.com/text-to-speech
Please tell me which sound pack would be OK there. The old EN sound pack is generated from another tool and numbers are not quick enough to allow the countdown feature

**Comment by Jedsters** [comment]
Thanks, would I be right in guessing that you are using you are using one of the English (United States) locale voices? (Sorry, I replaced the voices on my tx with the previous ones so can't easily check.)  There is an English (Great Britain) locale and the en-GB-Neural2-A seems to be similarly quick and female so hopefully also avoids the problem you mention? 
I guess some may prefer the US voice so maybe a choice would be possible?

**Comment by pld74** [comment]
@Jedsters Thanks for referencing my post. Looks like we both noticed the changes in voices with 1.4.5 and you'd also like consistancy plus options. Let's see what FrSky comes back with.

**Comment by Jedsters** [comment]
There is also another option here!
Looking at the sound packs that @bsongis-frsky mentions 
![image](https://user-images.githubusercontent.com/96293240/211145273-84f312f6-833f-4e68-bd2e-8b214519ade7.png)
there is a 'Speed' option. 
If the reason the old sound pack was changed is that the numbers are not quick enough, then if the numbers in the English(Great Britain) locale I referenced above also aren't quick enough then the numbers could be generated on their own with the Speed option increased so that they are fast enough? The rest of the sound pack could then be generated at a speed of 1.0 using the same sound pack for consistency.

**Comment by pld74** [comment]
Can the Google TTS handle a batch or have to do it one by one? I’d One by One that’s a lot of time to spend to create them. It’s 

That’s why I select the Google TTS in Automate. I found all the files were the shortest versus the other TTS sources. 

I’ll test the voice files I created on the countdown and I’ll report back. Are we referring to countdown as in the last 10 seconds of the timer as an example?

**Comment by pld74** [comment]
Update: I tested the countdown and it works perfectly.

**Comment by bsongis-frsky** [comment]
The previous sound pack was not generated using this TTS engine and the speed was too slow and not configurable

**Comment by Jedsters** [comment]
Apologies if my previous comment wasn't clear. 
I understood when you said previously that the sound pack was generated using a different TTS engine. What I was trying to get at was that I wasn't totally confident that my proposal with your new engine would be fast enough 'out of the box' so I was suggesting that if the numbers weren't quick enough, then your new engine at least gives the option to speed up the numbers alone which would get around the problem. 
Many thanks for assigning to 1.5.0.

**Comment by pld74** [comment]
> Apologies if my previous comment wasn't clear. I understood when you said previously that the sound pack was generated using a different TTS engine. What I was trying to get at was that I wasn't totally confident that my proposal with your new engine would be fast enough 'out of the box' so I was suggesting that if the numbers weren't quick enough, then your new engine at least gives the option to speed up the numbers alone which would get around the problem. Many thanks for assigning to 1.5.0.

PSS - After some further testing the number callout audio files tracks have been modified to be max. 0.9 seconds for proper countdown or count up playback radio callouts.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2287

**Comment by pld74** [comment]
> If a .psv file was included with the releases we could mix and match all kinds of things and avoid issue like the countdown while still having the bulk of our track be pleasing or clear in a specific environment.

I agree!

**Comment by bsongis-frsky** [comment]
The next nightlies will have the Multi Voices support added.

@Jedsters Do you confirm that this voice could be used for a GB voice?

![image](https://user-images.githubusercontent.com/50834778/222525372-fb47b443-d13d-44d0-a325-a6e426848814.png)

**Comment by krelt** [comment]
Perfect!

**Comment by Jedsters** [comment]
> The next nightlies will have the Multi Voices support added.
> 
> @Jedsters Do you confirm that this voice could be used for a GB voice?
> 
> ![image](https://user-images.githubusercontent.com/50834778/222525372-fb47b443-d13d-44d0-a325-a6e426848814.png)

Yes, the English Great Britain is perfect for those of us in England / GB / UK. 
Thanks

**Comment by bsongis-frsky** [comment]
2 audio packs (us and gb) included in the next nightlies 1.5.0
