### ISSUE TITLE
Request:  Option to Play Channel Mixer value or Channel value

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2278]
Currently Special Functions allow us to Play Value for a channel, however this appears to be the percentage value for the Channel Value. 
However, often the channel is not being used directly to e.g. a control surface, but rather is being used as input to another mixer and it would be more useful to be able to play the Mixer value instead. 
In this example:
![image](https://user-images.githubusercontent.com/96293240/210353092-12c38b98-2859-48dd-adfe-c6cffdfd589f.png)
instead of 50% being played, to play 0% instead. 
I guess this could be implemented by adding another Option to Value so as well as Negative we have a choice of Channel or Mixer?
![image](https://user-images.githubusercontent.com/96293240/210353714-8cccadb5-b81d-4cbe-bdc6-e96889c488ec.png)

Thanks

**Comment by Jedsters** [comment]
Update, I am aware of a work-around whereby the channel can be output to another mixer / channel and that value adjusted and played, but this can necessitate using an extra channel for each Mixer value you want play if multiple mixers are active at the same time.

**Comment by bsongis-frsky** [comment]
In your example, what are the Channel settings (screenshot)?

**Comment by Jedsters** [comment]
The use of VARs with 1.5.0 seems to largely remove the need for this (for my purposes anyway).
