### ISSUE TITLE
LUA drawing does not use AA / smoothing

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2283]
Please not this is not super high priority. But maybe a simple change.

It looks like Ethos is using anti aliasing when drawing its own UI. But drawing in LUA has AA off.

Affected shapes:
- circles
- lines
- arcs

`drawText` is not affected. It does AA.

Ethos screen:

![image](https://user-images.githubusercontent.com/42830563/210510770-aea8c665-9a2c-4203-9b47-5c325f6553b3.png)

LUA script:

![image](https://user-images.githubusercontent.com/42830563/210510845-93ecacf5-ebb5-4026-b200-908377658ead.png)

Test shapes (zoomed in)

![image](https://user-images.githubusercontent.com/42830563/210511064-84e39da0-ff81-4456-82a8-a3bc69ce750d.png)

**Comment by azaz44** [comment]
Update: I think `lcd.drawBitmap` is affected too.

**Comment by bsongis-frsky** [comment]
Not high priority, but very interesting!
There is no AA in Ethos drawing primitives, but it is present in Ethos fonts / bitmaps (the circles you show are bitmaps).
Do you have a simple algorithm at hand that I can study?

**Comment by bsongis-frsky** [comment]
> Update: I think `lcd.drawBitmap` is affected too (when scaling bitmap to non native size)

Right. I am afraid it will be more difficult!

**Comment by azaz44** [comment]
Oh, I see. Then it's significantly more difficult and will come with some performance penalty. Drawing with AA is always slower, because it draws more pixels and also takes existing pixel values into account.

For AA line this algorithm is great and fast: https://en.wikipedia.org/wiki/Xiaolin_Wu's_line_algorithm
But I don't know about other shapes.

But I think this is then way to complex to implement. I thought Ethos does support AA, and it's just a matter of enabling it in LUA, but this isn't the case.

I'm fine closing this issue. It would be great to have but it's rather something for 2025...

BTW I was able to solve my problems using masks included in Ethos, so you helped me here:
![image](https://user-images.githubusercontent.com/42830563/210533563-70d32836-27d2-4ec6-aaa2-753f6b5abbf9.png)

**Comment by azaz44** [comment]
It's stale and I'm closing, as I don't think it makes sense to implement at all.
