### ISSUE TITLE
LUA / drawing masks with scaling

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2284]
To make our LUA scripts look in "Ethos style" like here:

![image](https://user-images.githubusercontent.com/42830563/210512647-4486a2fa-6ed0-4389-aaea-9dec84e29b69.png)

we need to be able to draw masks with scale. This will allow to:
- draw icons with proper colors, so they match the theme
- icons will scale properly for different radios with different LCD resolutions

Ethos already has this feature implemented for `lcd.drawBitmap`

![image](https://user-images.githubusercontent.com/42830563/210513308-58326141-f1c2-4b09-81af-b0a44e99af46.png)

I think we just need a similar thing for `lcd.drawMask`

![image](https://user-images.githubusercontent.com/42830563/210513435-c32b0237-2c5f-4f35-ad6f-7a536dd6bd01.png)

**Comment by azaz44** [comment]
Update: example of what I'm trying to achieve. I replicated Ethos-style navigation, icons can be drawn with proper color depending on theme (selected screen has black icon, others have white). But I can't scale it to the right size depending on screen resolution.
![image](https://user-images.githubusercontent.com/42830563/210513954-54017571-0100-4810-a18a-c4f5f5bcbeed.png)

**Comment by bsongis-frsky** [comment]
It seems an interesting feature, but why don't you provide one icon pack per screen size?

**Comment by azaz44** [comment]
> It seems an interesting feature, but why don't you provide one icon pack per screen size?

Yes, this is an option too. But this means you need to consider all FrSky radios (or at least screen resolutions), and any future radio might have problems with your script just because it introduced new screen resolution. I think for FrSky it's also an advantage that they can invent new radios with new weird LCD resolutions, knowing that well written scripts will still work instead of crashing because of *I don't have icon for this resolution*.

Also, with LUA we very likely don't develop stuff for other people, but rather for ourselves. We write scripts to solve our problems. And then we share it with others, so they can gain advantage to. And anything that makes it easier for our scripts to work for others increases the chance, that we share them instead of just using on our own, which is better for community.

And also, this is quite an advantage of Ethos (over OpenTX) that in many areas it allows to write universal scripts that will work on all radios. Things like scaled bitmaps, different font sizes (for example standard font is smaller screens on x10 than it is on x20, which means you don't need to do `if x10 then use_this_font else use_other_font end`). We even got `lcd.measureText` - all of this makes it possible to not use hacks like *for this radio draw it like this, for other radio draw it like that*. It's just that `lcd.drawMask` does not follow.

Sorry for long post, was trying to convince you :)

**Comment by bsongis-frsky** [comment]
No bother! The problem will remain with small icons / bitmaps, the scaling won't work very well (I think it's the reason for .ico files which include many bitmaps inside one file, i.e. 16x16 32x32 64x64 128x128)

**Comment by azaz44** [comment]
You might be right. I thought Ethos supports AA (which we discussed in #2283 ), but if this is not the case, scaled masks could look ugly. I tested bitmap scaling, and it doesn't do any interpolation, so they do look ugly when small.

Hmm, I'll try to revert to use different icons based on resolution.

I'm fine closing this story..
