### ISSUE TITLE
Custom Trim Steps do not use percent as step unit as doc says they should.

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2285]
1.4.5 has an update so that 'Trims now have a configurable range (not only 25% and 100%), and the Custom Step uses percent as step unit'

However, this doesn't appear to be the case. I have a Trim Mixer with a Range of 100% and Step of custom 10. One would therefore expect to see steps of 10%.
However, when adjusting this mixer, if I first go down to -100% and increase by steps of 10%  I can see in the output channel values of 
-100%, -90%, -80.1%, -70.1%, -60.2%, -50.2%, -40.2%, -30.3%, -20.3%, -10.4%, -0.4%, 9.6%, 19.5%, 29.5%, 39.5%, 49.4%, 59.4%, 69.3%, 79.3%, 89.3%, 99.2%, 100%  
which aren't exactly 10%.
This also gets slighty messy in that if I now start stepping down, I don't get the same values, e.g. below 100% isn't 99.2%, then 89.3% it is now 90% then 80.1%. 
It is also noted that the center trim value of 0% is never hit. 

My guess is that microsec values are being used and the percentage calculated, rather than percentage being used and the microsec value being calculated. If this is correct, would it not be more appropriate to take the percentage value and calculate the microsec value? That would not only give exact percentage values as documented should happen, but the microsec values would be the same going up and down after hitting the limit. Care would need to be taken for steps which don't have 100 as a multiple correctly though, e.g. steps of 3 would take you down to -99 and then -100, so increasing from -100 should be -99 then -96 etc. which also fixes the problem of not passing through exactly 0%. 

I raised #2276 yesterday, so there is a possibility this may have been addressed by the fix to #2276.

Thanks

**Comment by Wolepo** [comment]
Hallo
I have already addressed a similar problem in [#1833](#https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1833)

**Comment by hrenz** [comment]
this is normal, 
because the internal calculation is always in us 
512us / 100%  =   5,12us per 1% Step

or 100% / 512us = 0,1953125 
so 10% should be 19,5325us, but the calculation soluton is only 1,00us Steps
and this is the general Problem you see


steps are: 
extra fine = 1us
fine = 2us
medium = 4us
course = 8us
so you can trim in very very fine steps
exponential

new should be now in percent

**Comment by bsongis-frsky** [comment]
This problem is fixed in the latest nightlies. If nobody reports an issue I will backport the fix to 1.4.7

**Comment by bsongis-frsky** [comment]
Backported to 1.4.7
