### ISSUE TITLE
Radio Clock as LSW source appears largely unusable?

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2286]
With 1.4.5 Logical Switches can have the Radio Clock as a source, however it's not clear how this can be used. 

e.g. creating a LSW with a source of Clock we are then presented with a Value of a date and time in 2009. There is no evidence of a slider to enable this to be changed by anything other than 1sec at a time. Trying to change this date to be current would take too long to be usable. It would be better if each segment can be adjusted at a time, e.g. year, then mon, then day, then hour, then min then sec. 

If one were to select a Delta  function e.g. delta > X with X of the date in 2009, then the LSW appears to briefly come active once per second, but it's not clear why. What does it mean a delta of more than the X value - since when? Since the model was selected?

If you select Range for the function then the two dates displayed in the Range are too long for the display and you can't see the start of either date

I'm guessing the person who requested this had some use cases? It would be interesting to document what they are as I struggle to see how this can be used beyond alerting when a date / time has been passed 
Thanks

**Comment by Wolepo** [comment]
Hello
The step size of the setting can be adjusted with the time highlighted by holding down the PGUp/Dn key and turning the rotary wheel.
However, implausible values are also offered, see picture.
![Uhr](https://user-images.githubusercontent.com/90325526/210556619-767f34e2-f707-40ae-9652-f3e2a54566a2.jpg)

**Comment by bsongis-frsky** [comment]
What do you want to do exactly?

**Comment by Wolepo** [comment]
So far I have only used the system clock time for an announcement. Due to the above request, I merely tried it out and came across the time of 2So far I have only used the system clock time for an announcement. Due to the above request, I merely tried it out and came across the time of **_28_**:35:55. However, there must not be more than 23:59:59.

**Comment by Jedsters** [comment]
I have wanted something for a while (but not felt important enough to request).
I fly electric assist gliders, normally I'm able to fly on a slope without motor and can fly all day on one battery so I only take one battery. However, if I need the motor I can only get maybe 4mins of full motor run which may be aross multiple flights. 
I therefore have to remember to reset the persistent countdown timer to track motor use. 
I was hoping the new Radio Clock as a LSW would enable me to somehow automate resetting the countdown timer after e.g. 12 hours or at midnight. I couldn't see a way of doing this but was curious what could be done with the new function - but struggled to find much use for it so was interested to see if I could learn what could be done by seeing what the original requester had in mind. 
Thanks

**Comment by azaz44** [comment]
> I have wanted something for a while (but not felt important enough to request). I fly electric assist gliders, normally I'm able to fly on a slope without motor and can fly all day on one battery so I only take one battery. However, if I need the motor I can only get maybe 4mins of full motor run which may be aross multiple flights. I therefore have to remember to reset the persistent countdown timer to track motor use. I was hoping the new Radio Clock as a LSW would enable me to somehow automate resetting the countdown timer after e.g. 12 hours or at midnight. I couldn't see a way of doing this but was curious what could be done with the new function - but struggled to find much use for it so was interested to see if I could learn what could be done by seeing what the original requester had in mind. Thanks

I think this could be easily done with LUA.

I thought for long on any application for RTC in LSW and I couldn't find any.
Only things that came to my mind were different behaviors of the model depending on time of year (winter vs. summer) or time of day (when it is getting dark), but this would need way more complexity than current implementation, and I think all of that is better done in LUA.

For example, it would be possible to write a LUA scipts which gives true/false depending on if it's dark or not, and then do whatever you want with that. But trying to expand the system to make it without LUA would be super complex.

**Comment by Jedsters** [comment]
The best I came up with for use of RTC in LSW was you could setup a LSW so that it triggers after a certain date, that way you could perhaps be alerted when your RTC battery was 2yrs old and maybe needed replacing - although you'd have to update the LSW each time. Or maybe alert at 5pm so that you can pack up and leave the car park before it closes?

The delta function has potential, although I don't understand how it is supposed to work. e.g. could you setup a LSW so that it alerts when you have been flying for an hour without the need for a timer? 

The problem with my use case is that it needs a value to be stored while the tx is turned off. I'd thought maybe have a LSW so that it resets a countdown timer if it is the first flight of the day (last flight time was more than 12 hours past or a different day number). But you need to store the date / time of the last flight somewhere. As you suggest LUA may be necessary for my want. Not a huge deal, but I'm interested to learn how it can be used.

**Comment by azaz44** [comment]
LUA can store things, this is not a problem. There's even `storage` for doing that, but I wasn't able to get it working on non-widgets yet. But if not this, it's possible to write and read files - no problem.

But how do you power your service, is it same battery? If not, how is it charged?

**Comment by Jedsters** [comment]
> LUA can store things, this is not a problem. There's even `storage` for doing that, but I wasn't able to get it working on non-widgets yet. But if not this, it's possible to write and read files - no problem.
> 
> But how do you power your service, is it same battery? If not, how is it charged?

It would be a fully charged battery every day - I was just looking to 'automate' resetting the countdown timer each day as I habit of forgetting.

**Comment by azaz44** [comment]
> > LUA can store things, this is not a problem. There's even `storage` for doing that, but I wasn't able to get it working on non-widgets yet. But if not this, it's possible to write and read files - no problem.
> > But how do you power your service, is it same battery? If not, how is it charged?
> 
> It would be a fully charged battery every day - I was just looking to 'automate' resetting the countdown timer each day as I habit of forgetting.

Sorry, I made a typo. I meant "How do you power your servos". Because if for servos ane electronics you use same battery, or you maybe use a different one but also one-per-day, then there's an easy solution. Just reset the timer when RxBatt telemetry is high. You should have RxBatt from almost every recent receiver, even if you don't have ESC telemetry.

**Comment by Jedsters** [comment]
Ah thanks. No, I use a 6S LiPo and ESC with BEC so it just provides a continuous 5v (or whatever).
I do have a FLVSS, so if I remember to connect that I can monitor the LiPo, but it gets swapped between models so sometimes ends up in the wrong model.
On my horus with opentx I had a checklist file which flashed up and reminded me to reset the timer, but ethos doesn't seem to have that.

**Comment by azaz44** [comment]
> Ah thanks. No, I use a 6S LiPo and ESC with BEC so it just provides a continuous 5v (or whatever). I do have a FLVSS, so if I remember to connect that I can monitor the LiPo, but it gets swapped between models so sometimes ends up in the wrong model. On my horus with opentx I had a checklist file which flashed up and reminded me to reset the timer, but ethos doesn't seem to have that.

I tried to bake a small script to solve your problem. I needed to get familiar with LUA sources, so took this small problem as an example. Can you see if it works for you?

It creates a new LUA source "Last Use" which gives you number of hours, which passed since you last used your model (or actually, number of hours since you last activated your model in the radio). And it's only evaluated once, when you power on the radio, or select this model. You could easily use it to create an LSW (for example "Last Use" > 8) and SF to reset the timer.

It needs to be extracted to "scripts" and then enabled in "Edit Model".
[LastUseTime.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10373135/LastUseTime.zip)

**Comment by Jedsters** [comment]
Thanks! I'll give that a go.
