### ISSUE TITLE
Ethos Full English Audio and System Tracks

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#2287]
@bsongis-frsky 

Hello, so my OCD finally got to me as I couldn't take all the different voices in Ethos so I took the time and created the following english track and system files using TTSAutomate with the TTS provider as Google and selected voice English (American Samoa). I than used Audacity to Clip and Increase the volume levels. I have included both PSV files for TTSAutomate. 

PS - For Files with Z01 and Z01, etc., remove the ".zip" extension as I could not upload it if it wasn't a compatible GitHub supported file.

PSS - After some further testing the number callout audio files tracks have been modified to be max. 0.9 seconds for proper countdown or count up playback radio callouts.

I do have some questions:
Who can validate the nomenclature and audio track length is fully compatible with Ethos?
Should a file not be correctly named or missing, how does Ethos behave?

Thanks!

[Ethos Audio Files (EN).z01.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369158/Ethos.Audio.Files.EN.z01.zip)
[Ethos Audio Files (EN).z02.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369159/Ethos.Audio.Files.EN.z02.zip)
[Ethos Audio Files (EN).z03.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369160/Ethos.Audio.Files.EN.z03.zip)
[Ethos Audio Files (EN).z04.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369161/Ethos.Audio.Files.EN.z04.zip)
[Ethos Audio Files (EN).z05.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369162/Ethos.Audio.Files.EN.z05.zip)
[Ethos Audio Files (EN).z06.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369163/Ethos.Audio.Files.EN.z06.zip)
[Ethos Audio Files (EN).zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369164/Ethos.Audio.Files.EN.zip)

**Comment by Jedsters** [comment]
Also see #2277 where I have hopefully identified how the software which is being used for Ethos TTS can be used to generate an English (Great Britain) voice. If so then all that should be needed is to add an extra Suite option so we have English (US) or English (GB).

**Comment by pld74** [comment]
> Also see #2277 where I have hopefully identified how the software which is being used for Ethos TTS can be used to generate an English (Great Britain) voice. If so then all that should be needed is to add an extra Suite option so we have English (US) or English (GB).

Thank you! Let's see what FrSky comes back with...

**Comment by pld74** [comment]
Issue Closed - See https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2277
