### ISSUE TITLE
Tainer mode feature proposal

### ISSUE THREAD

**Issue by Ze-baloo** [FrSkyRC/ETHOS-Feedback-Community#2288]
Hello.

As i'm learning to fly to my son, i had time to discover that the basic activation with a momentary switch like the SH switch could become a bit boring, especially when the pupil is becoming more and more autonomous ;-)

The first solution is to program a sticky momentary switch but i don't like it that much, i don't find it secure enough.

A colleague of my RC Club, who is quite active on OpenTX in france (He's known as Lapinfou)  has programed a sticky momentary switch that is deactevated by any movement on any of the 4 main gimbals axis. It's really cool to use.

I've learned recently that this feature exists as standard on spektrum radios.

Hereunder is the link to the detailed program on OpenTX in case it could help :
https://opentx-doc.fr/wiki/ecolage-sans-maintenir-le-bouton-appuye

Laurent

**Comment by Dsrenger** [comment]
That would be a great enhancement.

Just set up my trainer setup (XE and X20S) and missed that functionality.

Giving the pupil control by a momentary switch and getting it back simply by moving the sticks.

**Comment by Mcrocknz** [comment]
Yes a good feature

**Comment by Ze-baloo** [comment]
Is this proposal still of any interest?
Laurent 😉

**Comment by Ze-baloo** [comment]
Just to remove the stale 😉

**Comment by doppleganger53** [comment]
Could we look at reopening this feature request? I recently used this on a spektrum radio and it was a huge benefit. As the trainer it allowed more safety margin as taking over control is effectively instantaneous, its surprising how much lag the added step of releasing or flipping a switch causes as its not a natural reaction.

I can replicate this functionality in ETHOS, but it takes 5 logic switches and a var to do so. This can be a bit of a pain if trying to set up new models as trainers or an impromptu trainer setup while at the field.

It would be nice to configure as a per-channel activation option (e.g. !Master Input) or as a mode (e.g. OFF/Add/Replace/MasterOverride).
