### ISSUE TITLE
Gyro calibration help images not showing

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2289]
Ethos 1.4.5

When I perform the Gyro Calibration, the gyro calibration help images are not showing. I have checked that the 1.4.3 gyro*.png bitmaps are present in the flash bitmaps folder.

**Comment by bsongis-frsky** [comment]
Which radio?

**Comment by lthole** [comment]
X20

**Comment by mgsanna** [comment]
Checked right now I've the same issue on 2 X20S - Firmware Flex the 1° one and EU-LBT the second one...
No images from gyro calibration and all is updated
