### ISSUE TITLE
Feature request : turn off sensor lost alarm 

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#229]
with my Flybarless system there is often a sensor lost alarm because it sends only values if the value changes.also while changing settings by lua script (on otx) the sensor emulation from the fbl stops and a warning of sensor lost will trigger. So it would be nice if you make it possible to deactivate the warning.

Thanks

**Comment by Hobby4life** [comment]
if so, Enable/Disable warning **per sensor** tick box
