### ISSUE TITLE
Charge light remains green when fully charged

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2290]
I'm not sure if I there is a problem with Ethos or my tx / battery. 
The last couple of times I've charged my tx (including overnight for 10 hours) the green charge light was still on afterwards. The voltage was showing 8.6V after the charge. According to the leaflet which comes with the X20S the green light goes off once charging is complete. 
I obviously can't tell if the problem may be the light not going off, or if the light is not only going off but it is still attempting to charge as well (or a problem with my tx).

Thanks

**Comment by bsongis-frsky** [comment]
If the radio is OFF when charging, Ethos doesn't run!

**Comment by Wolepo** [comment]
Charger cannot supply the charging current because it is too weak?

**Comment by Jedsters** [comment]
Thanks for the comments. I'll close this as a local problem.

**Comment by Dsrenger** [comment]
As I have a similar Problem with my X20 would love if you can write a solution here, If you have one. (sorry, as its not a ETHOS issue, but couldnt write a message directly to Jedsters)

**Comment by Jedsters** [comment]
> As I have a similar Problem with my X20 would love if you can write a solution here, If you have one. (sorry, as its not a ETHOS issue, but couldnt write a message directly to Jedsters)

I can only guess that Wolepo is right. I am going to try charging with my PCs power supply which is USB-C and 65W! If that doesn't charge it then there must be a battery or tx problem.

**Comment by Wolepo** [comment]
The power supply is supposed to be able to deliver 2.4A at 5V. I had this problem with my X10 Express. The balancing didn't work properly and the 2 cells ran apart and charging took forever. At the same time, the power-on LED started flashing after a long time. Since I use a more powerful USB charger (2.5A), all these effects have disappeared.
