### ISSUE TITLE
Cross trim should have disconnect as an option

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2291]
It is quite common (e.g. on Mike Shellim's templates) for trims (e.g. the rudder trim and throttle trim in particular) to be repurposed. In this example, Mike uses the rudder trim for differential adjustment which can then be done on a per flight mode basis. 
However, in order to do this you can't use the predefined Rudders Mixer. When using the predefined Rudders Mixer you either have the option to Disable the trim which means it can't be repurposed or Select a trim mode which  means you again can't repurpose it as any adjustment will affect the rudder. The current solution to this is to use e.g. a Free Mix for the Rudder etc., although this then means you can't use additional predefined Mixers such as Rudder=>Ail

What would be most useful is to have an option to select a trim mode, but then for cross trim to be able to select e.g. Disconnect. The intention would be that the trim doesn't affect the rudder, but the rudder trim can still be repurposed on a per flight mode basis.

Edited to change to Disconnect

**Comment by Jedsters** [comment]
Thinking about terminology, maybe Trim Disconnect makes more sense - give more a sense of we're disconnecting it from the control surface but not actually disabling it.

**Comment by mawzthefinn** [comment]
That's a good point, that makes more sense than disable

**Comment by mawzthefinn** [comment]
Re-opened, we still need trim disconnect

**Comment by spiky1** [comment]
I still need this!

**Comment by mawzthefinn** [comment]
Trim disconnect is now in the canned mixers for 1.5.0 nightlies. Applied at the mixer, not the trimmer level.

**Comment by mawzthefinn** [comment]
Closing as this is now implemented in 1.5.0
