### ISSUE TITLE
LUA: rotary left / right not working for "system tool"

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2292]
There's already #2040 (closed), but it focuses on widgets.
There's also #2066, but it mentions very many problems, and focuses on widgets, which I think is a reason why it is postponed for later.

Which I think makes one problem, which is critical for LUA, go unnoticed.

The problem is, that in LUA apps, which register as a system tool, rotary doesn't work. And for these type of apps it's critical to have input (while for widget it might be lower priority).

My findings are:
- X20 simulator - rotary do now work at all (no events coming to the script)
- X10 simulator - rotary right works, rotary left does not
- X10s real radio - rotary right works, rotary left does not (same like sim)

**Comment by bsongis-frsky** [comment]
In 1.5.0 I will add a function like `startForm(...)` to avoid that in your case a form is created as it gets the focus and most of events when it is not wanted

Meanwhile perhaps you could try not to give a `create` function to `registerSystemTool(...)`

**Comment by azaz44** [comment]
> In 1.5.0 I will add a function like `startForm(...)` to avoid that in your case a form is created as it gets the focus and most of events when it is not wanted
> 
> Meanwhile perhaps you could try not to give a `create` function to `registerSystemTool(...)`

Great news.
Not giving `create` and making initialization in first `wakeup` instead did the trick, thanks!

As for forms, does it mean that forms in "system tools" will work in 1.5.0?
As of now, I have some problems with them. I do get the form if I do `form.add...`, but then later, if I do `form.clear()` my app is not get any events, and this includes SYS, TELE/DISP, RET etc. Like if form would intercept them. I didn't create an issue about it yet, because I'm trying to trace what is actually going on.

**Comment by bsongis-frsky** [comment]
When you have a form inside a Tool, then the navigation inside this form will use intercept all events, even if the form has nothing inside!

So you will also need something like `form.delete()`

**Comment by azaz44** [comment]
`form.start` and `form.delete` (or similar) would be perfect 👍

**Comment by azaz44** [comment]
I don't know if this is fixed, but if not - this is of course needed. Maybe it gets fixed with new `form` improvements?

**Comment by bsongis-frsky** [comment]
Everything should be fixed here in 1.5.0
