### ISSUE TITLE
Horus X10 Express ethos bootloader update issue 

### ISSUE THREAD

**Issue by billhove2** [FrSkyRC/ETHOS-Feedback-Community#2293]
![x10ver](https://user-images.githubusercontent.com/121931225/210826751-0bf29090-6be6-4343-a863-02357cba24a6.jpg)
![bootloader](https://user-images.githubusercontent.com/121931225/210826812-1483936a-1ce7-4888-ac8c-7e40063e4998.jpg)
I have an X10 Express using Ethos version 1.0.11 Dated Sep 14 2021
This version is not compatible with Ethos suite, and must be upgraded manually. I am having difficulty finding easy to follow instructions for this manual upgrade. I have downloaded what i believe are the correct files onto a formatted sdcard, that can be read by both my x10 express and my computer. I can copy the bootloader.frsk to a different spot on the radio, but i can't find instructions that tell me where <specifically> to copy it to on the radio.

**Comment by mawzthefinn** [comment]
I wrote a quick procedure here back when ETHOS Suite was released. The same procedure works but use current firmware instead of 1.2.6

https://www.rcgroups.com/forums/showthread.php?4130423-Updating-ETHOS

You need to be on later firmware than you are to flash the bootloader, but your current bootloader can flash the 1.4.5 firmware manually and then 1.4.5 can flash the bootloader

**Comment by billhove2** [comment]
> I wrote a quick procedure here back when ETHOS Suite was released. The same procedure works but use current firmware instead of 1.2.6
> 
> https://www.rcgroups.com/forums/showthread.php?4130423-Updating-ETHOS
> 
> You need to be on later firmware than you are to flash the bootloader, but your current bootloader can flash the 1.4.5 firmware manually and then 1.4.5 can flash the bootloader

Awesome, 
Thanks! I'll try as soon as I get home!

**Comment by billhove2** [comment]
That was it,
I didn't have the firmware file in the root of the sd card. 

Thank You very much
