### ISSUE TITLE
Ethos 1.4.5 Tandem X20S Problem with the widget configuration min max

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#2296]
Tandem X20S Ethos 1.4.5 I have a problem configuring the widgets with the screen 3x3. The representation of the outer windows is too small. The buttons to select the Min Max value display are not displayed.  Am I doing something wrong here? With the earlier versions of Ethos this worked.
![Widged_config_min_max](https://user-images.githubusercontent.com/84685639/211054441-4520c2fb-4876-4d87-a7b0-76e7a9ccf957.png)

**Comment by mawzthefinn** [comment]
If you go into Configure widget, you can set from there. 

That said, this is a bug in the layout, the right side boxes are not rendering full size.

**Comment by bsongis-frsky** [comment]
Layout bug fixed

![image](https://user-images.githubusercontent.com/50834778/211319551-3ab32c9d-58a3-4456-a0fd-ba2f1ac55383.png)

**Comment by bluelex73** [comment]
Thank you👍
