### ISSUE TITLE
ethos suite freeze

### ISSUE THREAD

**Issue by FlipAirboost** [FrSkyRC/ETHOS-Feedback-Community#2297]
Hi all
Installed ethos 1.4.4 a month ago, everything works fine multiple times.

Today, I launch of ethos suite 1.4.4.
Upgrade request to ethos suite 1.4.5. Clic OK
Launch of ethos suite 1.4.5.
Ethos suite 1.4.5 not responding, popup "do you want to close the program or wait".
I close the program.
Retry and fail.

Uninstallation of ethos suite 1.4.5 
Try a direct download ethos suite 1.4.5 from the Frsky site.
Install and launch ethos suite 1.4.5 ( admin mode)
Ethos suite does not respond, pop up do you want to close the program or wait, I close the program.
I close the program.
Retry and fail.
Uninstallation of ethos suite 1.4.5.

Reinstall  and launch ethos 1.4.4. ( administrator mode)
Ethos suite 1.4.4 not responding, popup "do you want to close the program or wait".
I close the program.
Retry and relaunch of ethos suite 1.4.4 and ethos responds and  requests a upgrade , clic OK
Install and launch ethos suite 1.4.5 ( administrator mode)
Ethos suite 1.4.5 does not respond, pop up do you want to close the program or wait.
I close the program.
Retry and fail.

What to do to break this circle?

Windows 10  64 bits  21H2

Thanks for the help
![ethos ne repond pas](https://user-images.githubusercontent.com/29504813/211084070-615a0991-05e7-44d2-bebc-71daed7e934e.JPG)

**Comment by yak-54** [comment]
did you run as administrator ?

**Comment by FlipAirboost** [comment]
Yes, of course.

**Comment by yak-54** [comment]
try this turn off internet and wifi 
turn off internet security 
reinstall ethos suite as administrator 
after install run as administrator as well see how it goes i had heap issues windows and the virus protection stopping it last week

**Comment by FlipAirboost** [comment]
I reinstall as administrator.
I run as administrator.
Same issue.
I try compatibility with windows 8 and Vista .
Same issue.

![ethos suite 1 4 5](https://user-images.githubusercontent.com/29504813/211143498-c7b2a088-7bf5-49f0-9e94-06871e5cdb1c.JPG)

**Comment by FlipAirboost** [comment]
A little better now.
I stop and restart PC.
Have to wait perhaps 10 minutes to establish connection with TX.
But ethos freezes when I use the mouse.
![ethos crash](https://user-images.githubusercontent.com/29504813/211145591-6a4a3a7b-563e-46fe-9e70-bbec12d589c9.JPG)

**Comment by FlipAirboost** [comment]
Latest news, two hours later.......
I did not change anything. I did not stop restart the pc
I just launched ethos suite which started almost instantly. ( both in administrator and normally)
Plugged in the radio and ethos suite displayed it directly.
And I upgraded the firmware and files with no problem.
Really incomprehensible?
