### ISSUE TITLE
Individual volume settings for speaker and headphone

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2299]
My headphone is very loud compared to the speaker compared on my new TWIN X-Lite S. It would be helpful to have the possibility to set different volumes for both in the settings.  Actually using Ethos 1.4.5

**Comment by NilsRo** [comment]
Still like it, :-) Ping to avoid automatic closing.

**Comment by mawzthefinn** [comment]
Not sure if the hardware supports this. IIRC it's one amp with two output paths.
