### ISSUE TITLE
0.0.17 wont load models from 0.0.16

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#23]
X10s isrm v2.16.
After updating my x10s isrm from ethos 0.0.16 to 0.0.17 I can't open my models that I created in 0.0.16 the images are there but when you select a model it says invalid data. Please see image.
Thanks scott
![20210401_011814](https://user-images.githubusercontent.com/81478751/113226700-b122fd80-9288-11eb-9530-cdd0decb9402.jpg)

**Comment by Hartinger** [comment]
Same problem here.
I am therefore hesitating to enter more than a couple of models, given the risk that I have to redo them when V18 comes out.

A somehow related question: Can I simply rename the model binary files to avoid gaps in the numbering?
Obviously, if I rename the active model, ETHOS will not find it upon start-up, but other than that, are there any hidden implications from doing this?

Thanks
Reinhardt

**Comment by bsongis-frsky** [comment]
Conversions are still not ready, we are still in Pre-Release state. But of course it will be done soon.
You may rename your models filenames, but then you have to reload them from ModelSelect, no hidden implication
