### ISSUE TITLE
Stick in the simulator

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#230]
Hello, I am missing the sticks in the simulator to test a programming.
Are you planning to integrate the sticks like in "Companion"?
Best regards, Micha

**Comment by bsongis-frsky** [comment]
Please try your keyboard when using the simulator, A, B, C, D... and keybad, with Ctrl keys

**Comment by hrenz** [comment]
And how?
 there is no  ducemtation of keayboard funktions for Switches up/mid down, or Analog

**Comment by Devil-IdT** [comment]
The "a" key switches the "SA" switch in the simulator. But I cannot generate an analog value from the sticks via the keyboard.
