### ISSUE TITLE
MLVSS not detected 

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2300]
I am using Ethos V 1.4.5., Archer SR10 Pro receiver Ver 2.1.10 and I updated the MLVSS to version 220630. However, when I go to Discover new sensors the device does not show (I have it connected to the balance connector of the battery). I tried two sensors, but none of them shows up. I have the reading coming from the receiver but nothing else. Sensor is connected to the SBUS port and LED is blinking. I am sure I am missing something but can't figure out what, or the MLVSS is not compatible with the rest of the setup.
![screenshot-2023-01-07-32285](https://user-images.githubusercontent.com/9392774/211151403-7912150f-99c7-4e52-b1b1-f067973da21a.jpg)

Help please!!!

**Comment by 4qr1hu9n7** [comment]
Check the address of the sensor.

**Comment by mawzthefinn** [comment]
Sensor needs to be connected to the S.Port connector (4-pin), not SBus connector.

**Comment by Richrfl** [comment]
Is that the molex connector labeled AIN2?

**Comment by mawzthefinn** [comment]
Yes, note the other pins are labelled =, - and the s.port logo. the pre-wired harness for it can have the servo connector plugged into the sensor

**Comment by Richrfl** [comment]
I should have known better, given that I used that connector to update the FW to the latest version. However for the sake of dummies like me, somewhere in the manual it should be indicated that this is the SPort connector.
Thank you very much for your help
