### ISSUE TITLE
1.4.5 - Corrupts current model / Restore not working

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2301]
Hi

I made the update to 1.4.5 and it corrupted the current model. It says:
i Model Data load
Invalid Data

Trying to restore the backup says:
![grafik](https://user-images.githubusercontent.com/42022027/211155521-5b4334b9-28ae-47b2-a70e-0a36b1cff1ab.png)

Here is the crash file
[crash-2023-01-07.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10366477/crash-2023-01-07.txt)

What is more unexpected: Starting in Bootloader and manually copying the file to the radio results in the same error loading the model !!!!!!!!!!!!!!!!!!!!

model file also attached
[inav.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10366480/inav.zip)

**Comment by jasc76** [comment]
Flashing back to 1.4.4 and the model works again.

**Comment by mawzthefinn** [comment]
Note you should have a copy of the radio settings in your backup zip file, which can manually be restored.

**Comment by jasc76** [comment]
> Note you should have a copy of the radio settings in your backup zip file, which can manually be restored.
thats true, didnt test that.

What came to my mind as a hint maybe: The model depends on a crossfire module which was not present. Maybe this lead to the issues with the model file. Other crossfire models are fine but they where not selected when doing the update.

**Comment by bsongis-frsky** [comment]
This model will work again in 1.4.6 (issue with Vario Configuration)
