### ISSUE TITLE
symmetric curves 

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2302]
It would be very nice to have a "symmetric" curve option also. This will make it easier to setup e.g. 3D heli pitch curves have not be aligned manually between both side. This will also avoid errors if the pitch curve it forgotten to be adjusted.

![2023-01-08 184607](https://user-images.githubusercontent.com/51311453/211211033-e263dc7a-f779-4f3c-906e-be2022eb634f.png)
Mirrored and inverted mirrored would be nice...

**Comment by STC148** [comment]
Hallo, nimm statt der "Benutzer" die "Expo" Kurve, wenn du dort Expo auf null stellst, kannst du mit Gewichtung die Kurve symetrisch verstellen. Und wenn du die Gewichtung auch auf null stellst, dann kannst du mit Offset die Höhe verstellen, also eine 1-Punkt Kurve
![1](https://user-images.githubusercontent.com/85410070/211200191-af82d0ff-ac37-4a22-9cbd-ef2b223737d3.jpg)
![2](https://user-images.githubusercontent.com/85410070/211200201-2d39cbf4-97e4-4373-aa14-8c1b92a2dd02.jpg)
![3](https://user-images.githubusercontent.com/85410070/211200206-3935b3c7-5780-4a30-aedc-5e599c59f01b.jpg)

**Comment by NilsRo** [comment]
Moin, 

gute Idee, wenn auch sehr versteckt. Das Bild war leider ein falsches, die Antwort passt zu https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2303

Very good idea but a little hidden within "Expo". But working fine. The original issue found here, posted the wrong picture. Picture is updated and topic is still open.

**Comment by NilsRo** [comment]
Still like it, :-) Ping to avoid automatic closing.

**Comment by NilsRo** [comment]
Ping

**Comment by NilsRo** [comment]
PIng
