### ISSUE TITLE
offset curve / 1-point curve

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2303]
To setup my heli governor I use 2-point curves to assign fixed values per flight mode. It would be nice to get an 1-point curve or an offset function that the curves (e.g. the 2-point curve) could be moved up and down. This would make it easier to setup the gov. as only one setting has to be changed. 

![2023-01-08 131816](https://user-images.githubusercontent.com/51311453/211196192-5a7825a2-358d-4a6a-9c4c-a0a2a5a393ca.png)

**Comment by mawzthefinn** [comment]
Use a VAR mixer or Offset mixer instead. Both sends arbitrary values to a channel. VAR mixer should be used when it's the only source on the channel, Offset when you are stacking mixers.

**Comment by NilsRo** [comment]
Followed the official guide (for X20) to Setup an electric heli. There also the 2-point curve is used to have motor off for security. I also uses that to have a main switch as offset mixer is a new mixer instead.

So still seems to me that a additional offset (Trimable) per curve could be a nice option to save changing 2 points and also have safety functions in place.

**Comment by NilsRo** [comment]
Offset mixers and Free Mix mixers broke with Throttle Hold security feature. The servo output is changed even if in Throttle Hold according the offset. So the build-in mixer has to be used or a custom setup instead. With 1 Offset and 1 Free (Lock) mixer it should be fine.

From my personal point of view the best practice should be a standard mixer everytime as that the standard is made for. :-) But the two custom mixers combined would be a good setup for Electric Helicopters with governor as well. 

The guide so you have not to search for it if you like to change it there:
![image](https://user-images.githubusercontent.com/51311453/211381881-dc005e95-40e1-4d6f-8ade-311f767e1cc0.png)

**Comment by NilsRo** [comment]
Talking about an ETHOS enhancement a trimable Offset would optimise the setup process (a little ;-) and also makes it possible to change RPM of the gov without changing a flight mode. 

I do not use the spool up curve by myself but it looks like a good point.

**Comment by mawzthefinn** [comment]
Offsets can usually be trimmed via 'Use a Source' functionality if they are numeric offsets.

**Comment by NilsRo** [comment]
Sorry for being unprecise in my comment, its not my natural tongue....I think about the Curve Offset enhancement to have the option to move the Curve up and down. Could be nice in general also for other topics.

**Comment by Eagleowl1** [comment]
> Sorry for being unprecise in my comment, its not my natural tongue....I think about the Curve Offset enhancement to have the option to move the Curve up and down. Could be nice in general also for other topics.

Fully agree, would be a nice enhancement

**Comment by chaos3oe** [comment]
Pick expo as your curve type, weight zero, and the offset then does exactly this 1 point to adjust

**Comment by bsongis-frsky** [comment]
A 1-point curve is an offset, in 1.5.0 you can even have the offset driven by a Var:
![image](https://user-images.githubusercontent.com/50834778/220559822-f4aad23d-9cfe-4439-97f7-a22a046bf9f2.png)

**Comment by bsongis-frsky** [comment]
Curve with Type "Function" will also have an Offset, possibly driven by a Var:

![image](https://user-images.githubusercontent.com/50834778/220560947-b7fc643a-bcb3-40e6-ba30-23d2cc9fc91c.png)

**Comment by bsongis-frsky** [comment]
And Curve with type "Custom" will have the same Offset, and all points can be driven by a Var!

![image](https://user-images.githubusercontent.com/50834778/220562145-512526f1-4391-4ba0-8717-973eb9fcef9b.png)

**Comment by NilsRo** [comment]
> And Curve with type "Custom" will have the same Offset, and all points can be driven by a Var!
> 
> ![image](https://user-images.githubusercontent.com/50834778/220570240-b8cddaa6-b428-409e-8c5c-09c6fc3981a9.png)

Started yesterday with a LUA implementation (my first steps with LUA) ....you are very fast! Looks good, many thanks!

**Comment by jurajjurej** [comment]
Excellent.
Offset in default Mix also with curve control.
