### ISSUE TITLE
Some information is not fully shown in TWIN X-Lite S

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2304]
Using Ethos 1.4.5 some texts are cut. It would be nice if that texts get a line break or scrolls over the screen. Mostly the case for German translation 8 use but also found some texts in English language but not as many as in German. 

![2023-01-08 131828](https://user-images.githubusercontent.com/51311453/211196536-62fe9358-0eda-4fe3-a89c-d2e29f44b67c.png)
![2023-01-08 131834](https://user-images.githubusercontent.com/51311453/211196538-c0eb3e75-646e-412d-8602-06c440dcc798.png)
![2023-01-08 131826](https://user-images.githubusercontent.com/51311453/211196542-5c5453d0-9202-4a99-816e-146b6b8ae744.png)

**Comment by bsongis-frsky** [comment]
Please check with Andreas @ EngelMT for those translations, translations must take care of the space available, or they will be cut!

English reference:

![image](https://user-images.githubusercontent.com/50834778/211327164-be5da62e-0b8a-48c2-be5d-9082d921dc74.png)

![image](https://user-images.githubusercontent.com/50834778/211327363-a0d346bf-9010-4c49-9b8d-b3e5fd4291ac.png)

System Information after the fix (HW was not rendered correctly):

![image](https://user-images.githubusercontent.com/50834778/211328471-fd044756-2828-4cb8-a24c-33f238c66e1a.png)

**Comment by NilsRo** [comment]
Informed the the team of Andreas about it. Many thanks!
