### ISSUE TITLE
System Audio Files

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#2305]
Hello.
Can system audio files be edited ?

**Comment by pld74** [comment]
Yes but what is it your after? 

BTW 2 other discussions are going on about this same subject. Maybe best to follow them.
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2287
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2277

**Comment by mawzthefinn** [comment]
Yes, they can be replaced as needed. 

Note they will update automatically with ETHOS Suite, so you will need to either manually tell Suite to not update Audio or restore your audio files after updating.

**Comment by mawzthefinn** [comment]
closing as the question has been answered.
