### ISSUE TITLE
Curve point change in flight

### ISSUE THREAD

**Issue by Roman73737** [FrSkyRC/ETHOS-Feedback-Community#2306]
Hello,
In ethos it is currently not possible to change a specific point in a curve in flight via a controller
Is it possible to add this function in one of the next versions?

**Comment by hrenz** [comment]
No, not now

**Comment by NilsRo** [comment]
Would be very helpful to optimize the pitch curve for helicopters like max/min or hover

**Comment by strgaltdel** [comment]
Curve Points are accessible via lua,
So there may be solutions in the future

**Comment by mawzthefinn** [comment]
This would require a 3rd party Lua, similar to what Mike Shellim wrote for OpenTX.

**Comment by strgaltdel** [comment]
I'm programming something similar

![crv](https://user-images.githubusercontent.com/20392683/211511795-f82fd00c-da23-43f0-88ff-bbc41cdc015a.png)

you'll be able to choose the point by a switch (i.e. "SH") and modifiy it on its y-axis by a pod.
you get acoustic feedback when your input "reaches the area" of the active point.
(vertical grey bar)
So there is no need to look onto your display

the widget is using mixers as an Input for the curve 
'Cause there are canned mixers with fixed Inputs, in this case you'll have to "duplicate" this into another channel...


need some weeks to finish


regards

**Comment by bsongis-frsky** [comment]
Implemented as a part of #2303
