### ISSUE TITLE
Trims Dialog:  name for "Stick Throttle" seems wrong for Heli models

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2307]
I am a new user of Ethos and some small stuff confused me...one is the Throttle trim for helicopter models.

According the crosstrim menu the trim should influence "Stick Throttle" but Pitch is not influenced. So not "Stick Throttle" but "the Throttle Mixer" is trimmed. So perhaps "Stick" should be removed as the target for trimming is the mixer not the stick itself. And with the Heli model it should be set to the name of the mixer...in my example "Gas". 

For electric helicopters it is common to set flat throttle curves so the Throttle Stick is used for Pitch only...

[t-rex450.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10369045/t-rex450.zip)
![2023-01-08 182840](https://user-images.githubusercontent.com/51311453/211210246-d55e25c5-cea8-4151-b7d9-28b1658db523.png)
![2023-01-08 182927](https://user-images.githubusercontent.com/51311453/211210247-93f256eb-3a7d-408d-981b-124cfefa9fd4.png)

**Comment by mawzthefinn** [comment]
Stick throttle indicates the location of the trimmer (next to the throttle stick), the function affected is ‘Trim throttle’.

This is one I’ve discussed with @bsongis because I dislike it as well, but any other solution quickly falls down on the need to accommodate the 4 stick modes cleanly without making model files mode-specific.

**Comment by NilsRo** [comment]
From my "Newby" point of view it is perhaps easy to solve...

I assign a function to a physical trim as you wrote. So simply name all physical  trims like written on the transmitter. So "Stick Throttle" should be named T3 and so on. For me it would be much easier to understand. You can also rename the trim function "T5" and "T6" to "Trim T5" and "Trim T6" which would be more consistent.

In this example I assigned  "T5" trim function  to "Stick Elevator" physical trim (which is T3 in real live) and "Trim Elevator" function to T5 physical trim. It is still not easy to read. :-)

![image](https://user-images.githubusercontent.com/51311453/211637096-f3c68c32-0661-4e15-ae46-0b92ceaf36eb.png)

Changing names would be:
In this example I assigned  "Trim T5" function  to "T3" physical trim and "Trim Elevator" function to "T5" physical trim. 
Much easier to read. :-)

**Comment by mawzthefinn** [comment]
The issue is that Stick Throttle is T3 only in Modes 2 & 4, it's T1 in Modes 1 & 3

Same goes for all the other 3 core trims, they change to match the radio mode set.

If this wasn't the case, renaming as you state would be the correct option.

**Comment by NilsRo** [comment]
An simple option would be to put name as a postfix in brackets. Stick Rudder (T1) or in-front sorted....

T1 (Stick Rudder)
and different mode
T4 (Stick Rudder) at position 4

Important for me is the link between the label on the case and the trim button a function is assigned to.

**Comment by mawzthefinn** [comment]
The current system denotes the physical location relative to each stick function. 

Anything which has the T1-T4 labels runs into problems where the text and order has to change relative to the stick modes.

**Comment by NilsRo** [comment]
Because of that the labels should be updated according the stick mode. Simple case statement.
