### ISSUE TITLE
Some LUA scripts from here cannot render texts with TWIN X-Lite S

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2308]
Some of the provided LUA scripts could not render text with TWIN X-Lite S and Ethos 1.4.5

It looks like this. On X20 simulator everything is fine. Tested Gauge and RSSI which both showing this behavior.
![2023-01-08 194731](https://user-images.githubusercontent.com/51311453/211213419-a49bf8ff-cfe9-4f9b-84b8-6c81415a3086.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/211336886-a8c537aa-4aa8-49b7-8e6d-e81ac9727edb.png)
