### ISSUE TITLE
Show battery status during charging with help of the 4 blue button-leds - TWIN X-Lite S

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2309]
Actually it is not possible to see how is the charge or if charging is finished if display closed. It would be cool if the charging percentage is visible on the 4 button leds (function buttons are not used if transmitter is off) - 4-leds 100% charge, 2-leds 50% charge,... if possible. So charging state will be also visible if display is closed and with more information. 

![2023-01-08 195834](https://user-images.githubusercontent.com/51311453/211213871-85fabadd-dbbb-447a-b3e6-d25605ab4092.png)

Actually they still show up if the On-Button is pressed shortly but I do not know what they shows. It is not the battery but would be also nice...

https://youtu.be/_anMygynhLA

**Comment by mawzthefinn** [comment]
Those buttons indicate which one(s) are active, they are the Function Switches and you set the layout in Model->Edit Model.

They can be set as a 4-pos, 4-pos with off, 4 x 2-pos or momentaries

**Comment by NilsRo** [comment]
Yes, this Buttons I am think of. You can have a look in the video, 3 of 4 flash's up if the powerbutton is pressed shortly before the transmitter is on. But they does not change if battery is full or empty and could be also on during charging for showing the charge.

**Comment by mawzthefinn** [comment]
Thats because the lights on the buttons indicate the position of the buttons, if they were giving other information you would have no feedback as to what the buttons are doing, since  they do not provide physical feedback unlike switches and are not dedicated momentaries either.

**Comment by NilsRo** [comment]
Yes, if the Transmitter is active...but the strange flash of 3 button lights happens before the transmitter is active...if you like I can take another video for a better clarification. 

Also in this state the button do nothing (or should) so can be used to show the actual charge.

**Comment by NilsRo** [comment]
PIng

**Comment by mawzthefinn** [comment]
As per #2654 the necessary hardware for the main radio to detect charge state while powered off is not present

**Comment by NilsRo** [comment]
Is the hardware missing for charge percentage or also for fully loaded information? The main switch changes color if the battery loading is finished.  Only to be sure as also the LED flicker is external power is connected...

**Comment by mawzthefinn** [comment]
Charge percentage, the radio knows ‘Charger circuit is active’ and ‘charger circuit is not active’
