### ISSUE TITLE
Info request: File formats

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#231]
I've had a look through the manual, but couldn't find any information. What file types are supported for bitmaps and audio? Also, what are the filename requirements (max characters?) Are the audio files still 32,000Hz, 16 bit wavs?

**Comment by bsongis-frsky** [comment]
Lothar will add this info to the manual:
WAV: 16kHz or 32kHz PCM linear 16 bits or alaw (EU) 8 bits or mulaw (US) 8bits

Bitmaps:
PNG / BMP / JPG
But not all flavors are allowed
And reasonable sizes, we have limited RAM

**Comment by andika207** [comment]
@bsongis-frsky how much RAM ?
