### ISSUE TITLE
LUA / `lcd.unRGB` would be useful

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2314]
We have `lcd.RGB(r, g, b, a)` which can convert r/g/b/a values into a "color", which is some internal representation of this color.

It would be useful to have a reverse function, `lcd.unRGB` or `lcd.getRGB` or whatever, which would take the color as an argument, and return r/g/b/a.

This would allow to construct new colors which are theme based (for example THEME_DEFAULT_COLOR) by modifying "opacity". So basically a way to make a theme color semi-transparent.

I baked something like this for myself, but this is not really elegant solution, because it relies on internal color encoding of specific hardware.

```lua
function lcd.unRGB(rgba)
  -- BEWARE, this might be hardware specific
  return
    ((rgba & 0x0000f800) >> 11) * 8,
    ((rgba & 0x000007e0) >> 5) * 4,
    ((rgba & 0x0000001f) >> 0) * 8,
    ((rgba & 0x0f000000) >> 24) * 16
end
```

**Comment by azaz44** [comment]
I thought I give an example what could be done with that:

Simple way to created "greyed out" text:
```lua
local color = lcd.themColor(THEME_DEFAULT_COLOR)
local r, g, b, a = lcd.unRGB(color)   -- missing bit in API
a = 0.5  -- semi-transparent
color = lcd.RGB(r, g, b, a)
lcd.color(color)
lcd.drawText(....)
```

**Comment by koakumaping** [comment]
you can use this code to change alpha
```lua
local alphaList = {0x1000000, 0x2000000, 0x3000000, 0x4000000, 0x5000000, 0x6000000, 0x7000000, 0x8000000, 0x9000000, 0xA000000, 0xB000000, 0xD000000, 0xE000000, 0xF000000}
lcd.color(string.format("%#x", lcd.RGB(204,0,0)) - alphaList[1])
```

**Comment by azaz44** [comment]
> you can use this code to change alpha
> 
> ```lua
> local alphaList = {0x1000000, 0x2000000, 0x3000000, 0x4000000, 0x5000000, 0x6000000, 0x7000000, 0x8000000, 0x9000000, 0xA000000, 0xB000000, 0xD000000, 0xE000000, 0xF000000}
> lcd.color(string.format("%#x", lcd.RGB(204,0,0)) - alphaList[1])
> ```

Yes, nice trick.
But it shares same disadvantages as solution above. You need to know details of how color is encoded, and it might get hardware specific at any point of time.

**Comment by azaz44** [comment]
no stale

**Comment by azaz44** [comment]
Still needed, although not high prio
