### ISSUE TITLE
LUA / Need some way to uniquely identify a source

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2316]
Short story:

The specific problem I'm trying to solve is:
- let user select some source
- store information, which identifies this source, in a file
- read this information later (after radio reboot)
- find and access the source from this information
- and have this working, even if user has renamed this source, deleted some other sources in same category, reordered things etc. (Ethos way)
- all of this in LUA

But how to identify the source?

Longer story below.

----

Ethos seems to have some nice way to uniquely identify sources. For example, if I do this:
- create LSW1
- create LSW2
- create SF, which has active condition = LSW2
- delete LSW1
- now SF will have active condition of LSW1, so the same LSW which user selected
- which is great. See animation:

![Recording](https://user-images.githubusercontent.com/42830563/211371301-e8b763f4-2992-48c6-84d3-439358ee452a.gif)

In a similar way it works with timers. If you
- create SF to reset timer
- you can later reorder timers, rename them, do whatever
- but SF is still referencing the right timer - the one which user selected. Like here:

![Recording2](https://user-images.githubusercontent.com/42830563/211372490-6f627d41-f484-4a5d-9361-8c6ecd973c14.gif)

Can we have anything like this in LUA?

What we have at the moment, is:
- `source:name()`, but name changes as soon as user renames a timer, or a channel
- `source:category()` and `source:member()` - but `member` is changed when items are reordered. For example, a member of `LSW2` will become different, if `LSW1` is deleted

I think we maybe need `key` - which is something we need to specify in `system.registerSource` and maybe all source have it. But `Source` class in LUA does not give us the key.

**Comment by bsongis-frsky** [comment]
What is the scenario you have in mind, where you need this?

**Comment by bsongis-frsky** [comment]
In Ethos, internally each component is able to give the list of Source it uses:

```cpp
class ElevatorMix: public StickMix<MAX_ELEVATOR_CHANNELS, STICK_ELEVATOR, MIXER_FUNCTION_ELEVATORS>
  public:
    std::list<SourceBase *> getSourceReferences() override
```

Yeah for thos who are still not convinced it's a little bit different from OpenTX ;)

It means that all scripts should also be able to return the references to all source it uses. Then it should work the same way.

I am afraid that the problems will come with details

**Comment by azaz44** [comment]
You confused me, as I don't know neither OpenTX not Ethos source code.

But how does it work in Ethos. If I have a SF, which references LSW2, and user deletes LSW1 (which cause LSW2 to become LSW1)
- is then Ethos updating each and every thing which is using LSW2, to now use LSW1
- or is SF just referencing some object or ID, related to LSW2, and if LSW2 becomes LSW1, SF just works?

**Comment by azaz44** [comment]
> * is then Ethos updating each and every thing which is using LSW2, to now use LSW1
> 
> => Right

Ok, then what I ask for is not possible.
Is `storage` solving such issues? I mean, if some script stores a source in the storage, will Ethos update it when needed?

**Comment by strgaltdel** [comment]
> What we have at the moment, is:
> source:name(), but name changes as soon as user renames a timer, or a channel

.. to make it even more worse:
let's say you provide a script & a corresponding model template which should work
even in case you use a standard name like "CH30" for channel-source, AND the user doesn't change anything,
the user may run into an error because these are language dependent labels,
i.e. the user configured "language=german" in his  transmitter, so label changes into "K30"  !
(english "Channel" = german "Kanal")

**Comment by bsongis-frsky** [comment]
@azaz44 I have to come with a solution on the "gauge" example. I am not sure it will be easy.

**Comment by azaz44** [comment]
> @azaz44 I have to come with a solution on the "gauge" example. I am not sure it will be easy.

Great, thx.

@strgaltdel In this case you could use "category" and "member", it will be better than the name.
But it will not solve problems with deleting / reordering timers, logic switches etc.

**Comment by strgaltdel** [comment]
> You start from a very bad example, if the script really needs CH30, it is not the best option

Yepp, it was my intention to show that not only user activity can mess up such "queries".

similar problem:
you have a "form.addSourceField " in your config page and want to store this "value".
i do assume the return value is something like a pointer / address, nevertheless you can't write this single value because it's "dynamic":
rudder will return a different source "value" on every (sim) restart.
so i don't know another way as to "parse" the source into category & member (or name) and save two values for one entry.

an UID would make it easier (-;

regards

**Comment by bsongis-frsky** [comment]
![lua_widget_sources](https://user-images.githubusercontent.com/50834778/211611327-8ecb3873-bdcb-445a-88c4-2396a05804ba.gif)

**Comment by bsongis-frsky** [comment]
I think I have been lucky this time!
