### ISSUE TITLE
Servo delay up and down

### ISSUE THREAD

**Issue by stealdesk** [FrSkyRC/ETHOS-Feedback-Community#2317]
Add a servo delay up and down in the mixer. I know there is a delay function in the logic switch but when you have many gear doors like a F18 it's much easier to set a delay in the mixer instead of fiddling with logics.

**Comment by mawzthefinn** [comment]
This has been requested in the past, such as in #2089

Delay is only in logic switches in order to clearly differentiate between control logic and mixing. This will not be changed as the current solution solves more problems than it creates.
