### ISSUE TITLE
Image generated in Ethos Suite is rendered distorted

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2319]
**Ethos 1.4.5
Ethos Suite 1.4.5
X20 simulator and transmitter**

An image which I created in Ethos Suite is rendered incorrectly in Ethos.

Original image:
![2022-12-13_132802](https://user-images.githubusercontent.com/6317479/211854021-cbdea011-3582-4c48-8f78-b5cc7f212b35.png)

Ethos suite settings:
![2023-01-11_160539](https://user-images.githubusercontent.com/6317479/211856217-b29dfb97-9c2a-4edf-b882-476c037b166e.png)

The exported (.BMP) image displays fine in my image viewer. However, it is rendered incorrectly in the transmitter and simulator:
![2023-01-11_155430](https://user-images.githubusercontent.com/6317479/211853872-283817db-5cea-4582-87f3-73aa50e4db48.png)

**Comment by Nicholas-Luoyi** [comment]
There is something wrong with the transcoding. Please try to add the Transparent option while transcoding. I think it will be fine

**Comment by RC-SOAR** [comment]
Yes, with Transparent option it displays correctly!

Just for extra info, the problem image was .PNG.  I converted a different JPEG image, and it displays correctly even without the transparent option.

**Comment by bsongis-frsky** [comment]
The resulting bitmap is 711x480
711 is an odd number, I think the issue is in Ethos

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/212424927-d43410d3-26db-4bc1-8d42-e185c7df9b7b.png)
