### ISSUE TITLE
Special functions trigger unexpectedly at startup when using '800 x 400' model images

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2321]
A user of my [E-Soar Plus template](https://rc-soar.com/ethos/templates/esoarplus/) raised this issue, and I can reproduce it. 

1. Create a .BMP image in Image tool, using '800 x 480' option
2. Assign image to setup, and display in full screen view
3. Power cycle the transmitter

On restarting the transmitter, several .WAV tracks are played in sequence, even though they should remain silent.

The conclusion is that the special functions are being triggered prematurely, which suggests that the logical switches are not being initialised correctly.  Since it only happens with the 800 x 480 pixel option, perhaps it's a timing issue due to the extra loading time? 

Either way this should not happen.

**_X20 transmitter
Ethos 1.4.5
Ethos suite / Image tool 1.4.5_**

**Comment by bsongis-frsky** [comment]
Why those WAV tracks should remain silent?

**Comment by RC-SOAR** [comment]
The corresponding SF's have 'skip on Startup' ticked. 

I attach the .bin file, and the 800 x 400 image used. 

[sf-bug.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10401247/sf-bug.zip)

Start conditions are SA-down, throttle stick fully up. First screen must be changed to full screen layout, to show model image.

With a 800 x 480 image, three tracks play at startup (unexpected behaviour)
With no image or small image, no tracks are played (expected).

**Comment by bsongis-frsky** [comment]
Then it's the same issue than #2320

**Comment by mawzthefinn** [comment]
#2320 is not a bug I think. It's a documentation issue (ie it's not clear how things initialize and could use a sentence in the manual)

Edge triggers for a !LSW condition trigger on initialization of the model as the LSW's go from undefined to false.

**Comment by RC-SOAR** [comment]
Reference to #2320 is confusing the issue. It's an SF problem. 

Just to re-iterate: SF's are *sometimes* triggered at startup even though 'skip at startup' is checked. 

The LS logic has not changed - the only thing that's changed are the pixel dimensions of the model bitmap. If it's a documentation issue, then it would help to have the necessary documentation. If it's an underlying LS/timing issue, then either a fix or some advice as to a workaround would be useful.

**Comment by mawzthefinn** [comment]
I don't believe #2320 is related and #2320 is fundamentally a documentation issue, not this issue.

I agree that this issue is a SF issue, and triggered specifically by large images loading at startup

**Comment by bsongis-frsky** [comment]
I have deleted all references to the other issue from this one
