### ISSUE TITLE
Cannot run LUA script

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2324]
I am sure I am missing something, but there is not info in the manual and there is not reference in the Aloft Forum, therefore I have to come here. 
I am using Tandem X18, SR10 Pro and GPS Adv. all of them updated yesterday to the latest versions.
I am trying to run the map1.lua to locate the GPS in the map. I verified that the GPS telemetry coordinates are within the map's range.
I think that the problem is that I do not have the LUA script running.
I noticed that there is a Lua source in the model config, but I have nothing there.
What am I missing, please?
![screenshot-2023-01-12-35604](https://user-images.githubusercontent.com/9392774/212081113-ed4fb2eb-bff2-4acd-a904-f5a7a563ebd4.jpg)
![screenshot-2023-01-12-35663](https://user-images.githubusercontent.com/9392774/212081142-974fae72-0d2f-47e0-9f34-86f3cc12abcf.jpg)

**Comment by mawzthefinn** [comment]
Where did  you get this script?

**Comment by bsongis-frsky** [comment]
And does your script register a Source?
I guess no. In 1.4.6 you won't see the line "Lua Sources", because there is none on your system. It will avoid the empty popup...

**Comment by mawzthefinn** [comment]
That script is a Widget script. You need to add a Widget to the screen you want and then select the script from the Widget list for that Widget.

**Comment by Richrfl** [comment]
Bsongis. I would appreciate some help. I am not meaning that there is a bug, But the lack of information on how to run the lua doesn't let me with other sources of knowledge, and you guys know Ethos better than anyone else, and it seems you are the only source to help.

**Comment by Richrfl** [comment]
Mawz, I read something about what you are referring to, and I tried and again it should be a pull-down including the list of luas, but I got nothing again. I guess here I am doing something wrong. I assigned a screen with the map. Do you mean that on that same screen, I have to create a widget where I assign the lua, because if that is the case, I don't know how to do that.

**Comment by Richrfl** [comment]
Actually, even in a new screen I don't have an option to select a lua.

**Comment by mawzthefinn** [comment]
This is where I'd recommend heading over to RCGroups. The long-running X20 thread and the ETHOS Lua thread are the best place to get help with usage issues like this. 

WHen you tap 'Change Widget' the Map Lua should be listed there if it's a valid ETHOS Lua.

I just checked the site, and the Map1.lua is not an ETHOS Lua at all, it's not going to work. It looks like it's just an add-on for another Lua to call.

**Comment by Richrfl** [comment]
I appreciate the RCGroups lead. I will check the Change Widget clue.
This may be interesting, as I got the link from a video and this guy was running Ethos. Here is the link if you want to take a look at it. https://www.youtube.com/watch?v=1ME0GxYA3WA&ab_channel=GiuseppePanzieri
Maybe you will find something I missed in the video.

**Comment by Richrfl** [comment]
And no, I cannot get the LUA in the config Widget. I moved the lua straight to the scrips folder and it doesn't show either.

**Comment by mawzthefinn** [comment]
That specific lua is not an ETHOS lua and will not work, it's an add-on for another Lua from Hobby4Life, I'm not sure which one.

**Comment by Richrfl** [comment]
I was looking into the RCG forums and back last November, on the How to Maps they end up sending you to the hoby4life site. However, the guy never talked about a lua. From what I am figuring out, in the GPS map screen, you select the GPS, the bmp map, and the coordinates range of the map, and I have to assume that when you select the GPS the program should put a dot in the GPS coordinates. Therefore, either there is some manipulation of the GPS coordinates that put the GPS out of the screen or the creation of the point is not working. Honestly, I don't know if I am making any sense. I guess I will use a world map and see if the point appears somewhere at all. Will let you know.

**Comment by Richrfl** [comment]
Well, the point is nowhere to be seen. Maybe my assumption is wrong and something else must be set up.

**Comment by Richrfl** [comment]
BTW about your comment on the lua, are you making reference to the one shown in the web screen or the one zipped with the map? I have not installed a lua compiler to compare them, but they clearly say the one in the screen is for different app.

**Comment by Richrfl** [comment]
Certainly, that did not come from FrSky download page. At this point, I am convinced that this is not a lua thing. Will keep investigating and if I don't find the solution I will open another issue pointing to the map/gps location. Will check about maps in the Aloft forum.
Have a good one and thank you very much for trying to get me out of this mystery.
