### ISSUE TITLE
X20S Micro S.D.Card

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#2325]
Hello;
Could someone tell me what the "maximum" size of micro s.d. card this transmitter will accept ?

thanks

**Comment by mawzthefinn** [comment]
32GB, and don't use a UHS-1 card, there have been some issues (not all UHS-1 cards properly work on non-UHS-1 slots)

**Comment by bsongis-frsky** [comment]
It's not the right place to ask this!

**Comment by 4qr1hu9n7** [comment]
I'm sorry. I don't live on this forum like some do. If it's too difficult for you to answer. Than don't !
