### ISSUE TITLE
Smooth Curves can result in movement in wrong direction

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2326]
As per the description and this image

![image](https://user-images.githubusercontent.com/96293240/212341419-0ef8640c-0845-42e4-a1b5-ab7b8e64e62d.png)

although points 1 and 2 are both -50% it can be seen from the graph that values will go below -50% between points 1 and 2. It seems wrong that smoothing should cause extreme values to be exceeded. This can result in control surfaces moving in the wrong direction and possibly exceeding physical restrictions.
Please can smoothing be adjusted so that values between points always have percentages which are also between the point values.
Edit: of course the work-arounds are to not smooth or to adjust point 2 to e.g. -48%, but neither seem ideal.
Thanks

**Comment by mawzthefinn** [comment]
This is standard behaviour in every smoothing/curve fitting algorithm I've seen, across multiple non-RC applications 

You get smooth transitions, but can have value excursions and have to be careful when there are abrupt changes in curve direction. 

The curve presented shouldn't require smoothing anyways, all it is adding is the two bumps on either side of point 2 that are causing your issue.

**Comment by Jedsters** [comment]
Just had a quick google and found http://paulbourke.net/miscellaneous/interpolation/ and the Cosine curve seems ideal (although that may be a consequence of the data points?). 

![image](https://user-images.githubusercontent.com/96293240/212371730-04e87142-989e-4ee0-9891-08ece65a4eda.png)

No idea if that can be used??

**Comment by mawzthefinn** [comment]
You can see the value excursions on that curve, the  point location and relative change in direction determine if the value excursion you ran into actually happens. If points 1 or 3 were level with 2 and 4, you would see the same behaviour there as you do on your curve.

I wouldn't be surprised if Cosine is what is actually used on ETHOS.

**Comment by strgaltdel** [comment]
jedster, please look at the formulas !

cosine interpolation means that your curve will have a slope of zero at EVERY point of a defined coordinate, so it would be complete nonsense for our purpose.

B-spline is a common  algorithm, lean and effective, but as every polynom based interpolation you never will get a straight line between two points of identical y values

there is no algorithm which would satisfy your needs without the tradeoff of very  ressource consuming calcs.
even in case you would switch to cubic splines and dampen them exponential you will run into oscillation problems in case of very near coordinates.

your example shows very slight deviation between an ideal line from p1 to p2 despite the fact that p3 has a "hard" increase
i dont see a problem for control surfaces, but in case you think its a nogo for your application the only acceptable mathemetical solution would be to renounce interpolation and to use straight lines between points

**Comment by mawzthefinn** [comment]
I’m closing this off as the current behaviour is correct for the curve smoothing algorithm.
