### ISSUE TITLE
PWM Center, not PPM Center

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2329]
Hi,

in the outputs it should be "PWM Center" and not "PPM Center", right?

(PWM = output one channel, PPM = many channels)

**Comment by mawzthefinn** [comment]
PWM center is correct, but PPM Center is what users coming from EdgeTX/OpenTX will expect.

**Comment by LuHaGH** [comment]
You will keep an error cause users are expecting it?

**Comment by mawzthefinn** [comment]
In the case where it has no impact on radio operation, merely UX, then yes. This is a name that is not technically correct but was requested for the setting, rather than an error or bug.

**Comment by Target0815** [comment]
The term is wrong and should be corrected. There is nothing to discuss or gloss over. Besides, what do Ethos users care what terms OpenTX users expect to be wrong? What kind of reasoning is that?

**Comment by bsongis-frsky** [comment]
I think that @Target0815 is right, it should be "PWM Center", I see this term in many other projects.
It's true that I named it PPM Center in OpenTX but we can fix it :)
