### ISSUE TITLE
CHECK LISTE

### ISSUE THREAD

**Issue by pPRODEVEN** [FrSkyRC/ETHOS-Feedback-Community#233]
Une notice en Français serait vraiment un plus comme le fait Futaba, Jeti, Spektrum.

Très pratique, pour chaque modele, par exemple AVION CARBON CUB
a l'ouverture du modele, de pourvoir visualiser la batterie de cet avion 4S 2200 Mah
Hélice 13x8 E etc.....

**Comment by bsongis-frsky** [comment]
What do you mean? You already opened another issue for the french manual, what do you mean with the battery, propeller, etc.
Just a text displayed on model startup? Any design idea for this screen?

**Comment by pPRODEVEN** [comment]
Bonjour,

 

Lorsque la radio est allumée, on choisit par exemple son modèle d’avion ou d’hélicoptère avec lequel on va voler, il y a une page qui s’affiche et chacun met ses informations essentielles par exemple l’accu que l’on met dans ce modèle 4S 2200 mAh, hélice 12x6E, un rappel de certains interrupteurs qui servent pour ce modèle.

Et cela c’est très bien, avec OpenTx, c’est possible.

 

Merci de me m’informer si ce pense bête ou checklist pourra être dans la TANDEM ETHOS X20S.

 

Bonne journée

 

De : Bertrand Songis @ FrSky ***@***.***> 
Envoyé : vendredi 14 mai 2021 08:34
À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc : pPRODEVEN ***@***.***>; Author ***@***.***>
Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] CHECK LISTE (#233)

 

What do you mean? You already opened another issue for the french manual, what do you mean with the battery, propeller, etc.
Just a text displayed on model startup? Any design idea for this screen?

**Comment by centertrim** [comment]
I agree.  Having a “checklist” page that can be populated with useful information and manual check-offs before flying a model would be very helpful.

Sometimes one of my models may sit on the shelf for a year since the last time I flew it, and it would be very nice to be able to store in the model checklist the things I need to remember about it’s specific setup before putting it into the air.

it would also be useful as a place to add reminders to myself on things I need to eventually get around to fixing on a model but haven’t yet.

**Comment by pPRODEVEN** [comment]
Bonjour,

 

C’est vraiment utile pour chaque modèle, on note les choses essentielles dont on ne se souvient pas.

Déjà par exemple le modèle de batterie qu’il faut pour ce modèle, une 3S, une 4S……

Merci pour ce développement qui est vraiment nécessaire.

 

Bonne journée 

 

De : centertrim ***@***.***> 
Envoyé : dimanche 16 mai 2021 11:47
À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc : pPRODEVEN ***@***.***>; Author ***@***.***>
Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] CHECK LISTE (#233)

 

I agree. Having a “checklist” page that can be populated with useful information and manual check-offs before flying a model would be very helpful.

Sometimes one of my models may sit on the shelf for a year since the last time I flew it, and it would be very nice to be able to store in the model checklist the things I need to remember about it’s specific setup before putting it into the air.

it would also be useful as a place to add reminders to myself on things I need to eventually get around to fixing on a model but haven’t yet.

**Comment by bsongis-frsky** [comment]
Duplicate of #790
