### ISSUE TITLE
Using LUA sources in mixers causes the value to by downscaled by 10.24

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2331]
If LUA source has a value X, it will be displayed properly as X, but mixers will use X * 100 / 1024 instead. In OpenTX mixing scripts were supposed to use -1024..1024 range and it was mapped to -100..100, but I think this is not true for Ethos. Otherwise the display would be wrong.

Example script:
```lua
local function sourceInit(source)
  source:unit(UNIT_PERCENT)
end

local function sourceWakeup(source)
  source:value(60)
end

local function init()
  system.registerSource({key = "Ksd287", name = "Test 2", init = sourceInit, wakeup = sourceWakeup })
end

return {init = init}
```

Resulting animation with value 5.9% instead of 60%:

![Recording](https://user-images.githubusercontent.com/42830563/212548171-c5345848-d38e-4c55-aafd-b3d3447a7141.gif)

**Comment by mawzthefinn** [comment]
It looks to me like ETHOS is requiring -1024 to 1024 from the source and mapping to the -100 to 100 range for the source in the mixer, but the display widget  is respecting your cast to percentage in the value declaration.

5.9%  is what I’d expect for a value of 60 on the -1024 to 1024 range, mapped to -100 to 100.

**Comment by azaz44** [comment]
Yes, it looks like mixer expects -1024..1024, but this doesn't make any sense in Ethos.

In OpenTX this kind of made sense, because outputs of mixing scripts were supposed to be something like "channel values" and be in specific range and with 10-bit precision. Although still it would be way easier, if LUA in OpenTX could just return -100..100 and OpenTX would handle multiplying on its own.

But in Ethos, it's not -100..100 or -1024..1024 output anymore, but a new source, with any unit, any range and any precision. It might be a 25V, or 300A, or RPM, or 19000 RPM. This part is better than it was in OpenTX. Like here:

![image](https://user-images.githubusercontent.com/42830563/212552912-f05afc70-2f97-4dda-8061-8b3752f12c1e.png)

So it looks to me that the display widget behaves correct, and the mixer behaves wrong, but I don't know the internals.

BTW, removing this line does not change anything:
```lua
source:unit(UNIT_PERCENT)
```
besides of course % sign not being there anymore. Widget still shows 60, mixer still outputs 5.9%. So it doesn't depend on the unit. Also changing source "decimals" does not change anything.

**Comment by bsongis-frsky** [comment]
Perhaps I can change this:
- if unit is % then 100% means 1024
- if unit is None, then 100 means 100

**Comment by bsongis-frsky** [comment]
It will be in 1.4.6 release (not pre-release)
