### ISSUE TITLE
Vario: make optional  "input" available

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2335]
this idea came up during a discussion about Lua sources and has low priority:

Mostly it is known that there are two types of varios:

- the "classic" one, which is implemented
- the "compensated" one, you need a pitot tube to compute the energy compensated sensor, a few pilots use this, the computation should be done "in real time", so "onboard" in the sensors. 

but in recent years the idea of so-called "integrating", "differentiating", or "averaging" variants has been increasingly discussed.
The goal is to provide "proof of climb" in very low thermals, when climb and sink are almost identical and one has difficulty determining if one is really gaining altitude during 1..3 circles

there was a requirement to produce an audio signal based on the altitude difference during a period of time (10..40 or more seconds).
Some people called it "integrating", because it would sum up the variosamples over time
some called it "differentiating", "based" on the altitude difference
and some called it "averaging" because it represents the average vertical velocity over a longer period of time....
I guess it's a "non-official" vario type that comes from us RC glider pilots
personally i guess "averaging" would be most intuitiv.

You could easily calculate such a value using the altitude differences in a source script.
Parameters would be the time period and a "factor" (due to low values)  which increases the averaged "m/s" value, so that the vario sound will be more sensitive.
But creating the audio signal would require a bit more work and would not be comparable to the standard vario sound.

It would be much easier to use the existing "ethos vario telemetry", but then you would need a second, alternative input/source in its configuration
(switchable, so that the user can choose the type inflight).
The source could be a script provided by the community.

(of course a full implementation would be more professional, but I think there are more important issues / requirements).

Maybe there are even more use cases (for acoustic feedback purpose), where vario sound, based on another Input/value, would make sense.

greetings
Udo

**Comment by NorbertHeli** [comment]
A selectable input for the vario signal would be very interesting. Since I operate GPS gliding (OLC), the deviation from the take-off altitude on the final approach is very interesting. You could do that very well with the Varioton (is possible with Jeti). Likewise, the deviation in a given direction could be excellently shown via the vario tone.

**Comment by NorbertHeli** [comment]
Does the label stale have consequences for editing? It is intended for 1.5.0?

**Comment by strgaltdel** [comment]
still hoping we'll see it in 1.5

**Comment by NorbertHeli** [comment]
A additional point: At the new TD-SR18 is a Vario integrated. I can`t it deactivate. 
I can change the adress of the SM-GPS Logger and his Vario ( need  for GPS OLC Contest )
BUT: Then can´t choose a different Vario for my Vario tone.

Or is there a different possibility ( I don´t know one ) I can solve the Problem?

**Comment by agibson2** [comment]
Could this new feature be used to monitor RPM for autorotations in a heli?  I want to have realtime audio of the blade speed to know if I am keeping the blades going fast enough.  I realize a sensor monitoring the blades and not the motor would be needed as most helis have a autorotation hub that allows the blades to freewheel when the motor turns off.  A vario type tone for other inputs might open up new ideas and possibilities.

**Comment by NorbertHeli** [comment]
Yes, sensing RPM via Blade speed by variotone where possible by this feature. Thats the target to make telemetrie Data audioable. The variotone is much more faster than announcements and is parallel.
I need it to "hear" how high or fast is my glider during the last few seconds,  before i reach the target.

**Comment by WhiskeyGolf** [comment]
That would actually be very helpful, I have used it in the past for the approach speed with a modified airspeed sensor

**Comment by bsongis-frsky** [comment]
Any sensor with m/s as a unit will be available in Vario sources

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/95f2baee-026d-4df0-9d14-6af419d2410c)

**Comment by strgaltdel** [comment]
Yepp, working very well
thanks a lot !

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/f27b3470-a931-4f0b-ba55-2aae7ba21b6a)
