### ISSUE TITLE
1.4.6 - Gyro calibration in update process?

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2336]
Hi

Update from 1.4.5 to 1.4.6 Pre-Release, X18S

Update All switches to firmware just before the end and the gyro calibration starts on the transmitter (X18S). Promptly an error is displayed in the suite. This error disappears when the gyro calibration is done, but it is irritating when this happens in the middle of the update.

**Comment by bsongis-frsky** [comment]
Calibration should not be requested when connected to Suite

**Comment by bsongis-frsky** [comment]
Analogs Calibration / Gyros Calibration / Model Wizard / Checklist / Popups removed when Ethos Suite makes the radio switch to firmware mode
