### ISSUE TITLE
Discussion / LUA / writing "mixing scripts" for Ethos is complex

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2338]
I'd like to raise this topic for discussion, and maybe there would be some ideas, or maybe issues as a follow-up of this discussion.

The key topic is: **writing *mixing scripts* (how they used to be called in OpenTX) for Ethos is complex work to do**

I'm porting some of my LUA scripts for OpenTX to Ethos, and just spent the Sunday on one of them. This was a mixing script, which is configured like this:

![image](https://user-images.githubusercontent.com/42830563/212845439-0e7d4b97-0633-435a-8bd4-e4bf8fb5333e.png)

The script is a training tool, which makes learning to fly in the simulator faster and is dedicated to RC helicopters. It's not really relevant what it is doing (I could explain details if really needed).

Key points are:
- it has a number of inputs, which are configuration values, and there is one "source" too (set to logical switch 12 in my case)
- it generates 4 outputs, which are to be used in the mixes or for logic switches
- it does work in the background and provides new values all the time
- settings are persistent "per model" (standard thing in OpenTX)
- this script is just one example, but many mixing scripts I have follow a similar pattern.

The way I found to port it to Ethos is a combination of 4 sources (`system.registerSource`)

![image](https://user-images.githubusercontent.com/42830563/212847458-c70261c7-1b28-4028-ac5d-8ff49a9af367.png)

and a configuration tool (`system.registerSystemTool`):

![image](https://user-images.githubusercontent.com/42830563/212847695-2be60a27-c603-4e69-9c8e-e7675a90f729.png)
![image](https://user-images.githubusercontent.com/42830563/212847746-76ce961a-b71c-4b42-8a82-fc96bc1f56fc.png)

The way it's written is:
- "system tool" obviously uses `form` to let user configure stuff
- settings are stored (by the system tool) to a file on SD card with a custom object serializer
- settings are retrieved at script startup, so everything (including sources) can use them
- "source" scripts additionally monitor the "source" which is used ("Repeat switch") and persist configuration if anything has changed (with help of #2316 added to 1.4.6 preview)

And at the end it all works. One thing I have to say is, the end result is super nice to use. Having settings in a form, with nice long labels, drop downs, and accessible from the system menu (instead of script settings) is very very nice. Great job with forms 👍

However it is much, much more complex script than the OpenTX version, more lines of code, and it wasn't easy to develop. I believe this makes a "barrier", which will make it very hard for people to develop "mixing scripts" either for public use or for themselves, unless they are really super simple scripts, which have no configuration at all and output just one value.

Some mixing scripts can contain something like 10 lines of code and do a useful thing. But to allow for configuration of this script you need to add another 200.

This is a list of main obstacles I faced:
1. Neither "source" nor "system tool" scripts have any persisted configuration
  - It means we have to organize everything on our own, both UI to configure stuff (the form) + the persistence
  - I happened to have all necessary infrastructure to persist data to / from files, but this is very challenging in general
  - Storing stuff to files on our own has some disadvantages:
    - I'm not sure how we could store data "per model". One could create a file based on model name, but model name might change
    - We have all kinds of questions like "where to put thiese files", "how to make it so backups made in Ethos Suite take them into account" etc.
2. Each source has its own "wakeup" loop, while in the case of this script (and many others) we need one "wakeup" loop, which updates values of multiple sources
3. Icons for system tools are radio dependent
  - my end solution registers a number of sources and one system tool, which is using a form. All of this is 100% hardware independent - it will work on any Ethos radio
  - however the missing bit is the icon for the system tool - and here it is impossible to create an icon which would display on all radios
  - this has an issue already #2247

I was able to solve all problems (except of 3), but as I wrote before, there's quite a "barrier" when trying to create a source script. Even something very very simple becomes an enormous task if it just any input or configuration.

Open for discussion, any ideas?

**Comment by bsongis-frsky** [comment]
Today we can only select if a Lua Source is used or not in a model. Perhaps we could change this:

For each source:
- A Slide Toggle ... used / not used
- If used, call the `source:configure` method to show the Lua form associated to this source

**Comment by strgaltdel** [comment]
i'm sorry to say i don't have a clue where you want to show the sliders, 

in addition of the checkboxes, so the slider in state "used"triggers the config handler and opens the form ,
and in case you exit the form the slider automatically is on state "unused" ?

that would  be a nice solution, but the standard user could be a little uncertain in case you don't support the handler in your code and nothing happens by activating the slider.
So something like  a "no config available" popup if the script doesn't support forms / no config handler exists, would be helpful
(imho)


btw
is there a chance to get access to var mixers by source scripts, so that i would be able to change it's values?

**Comment by azaz44** [comment]
@bsongis-frsky Do you mean something like this

![image](https://user-images.githubusercontent.com/42830563/212924584-0df2282c-d2f3-4527-8a5f-13881ee064b0.png)

And long press on the selector would open menu with "Configure" option?

**Comment by bsongis-frsky** [comment]
Exactly.
I think that "Configure" would be a button next to the Choice Used / Not used

**Comment by azaz44** [comment]
> Exactly. I think that "Configure" would be a button next to the Choice Used / Not used

In such case we could just have a switch to enable on /off, like here? I thought the reason to use something else is because this something else can have additional menu (3 bars).

![image](https://user-images.githubusercontent.com/42830563/212972626-6d27828a-cd86-4da0-968a-b675a520b032.png)

**Comment by azaz44** [comment]
And what do you think about that we enable individual sources on/off, instead of the whole "mixing script", which outputs multiple sources?

I think, that it is very common, that we will need just one logic to calculate stuff (one wakeup function), instead of one per each source. And now, if we get configuration, we will need just one configuration for the whole group.

As an example, let's imagine RC helicopter mixing for "flybar" helis. (I know Ethos has this probably built-in, but just imagine we would rather make it in LUA). Then we need:
- 2 inputs (aileron, elevator)
- 4 outputs - servo positions (although most setups need just 3)
- 1 configuration for everything (servo layout, spacing between servos etc.)

As you can imagine, the calculation logic and also the configuration is rather attached to the whole thing, and not to any individual source the script registers.

Maybe this could be improved by a new call, like this:

```lua
system.registerSourceGroup(
  {
    name = "My heli mix",    -- name of the group for display, so we can switch or configure the whole thing
    key = "MyHeli",          -- key of the whole group, needed or not?
    sources = {              -- all sources in this group
      { key="Src1", name="Servo 1" }, 
      { key="Src2", name="Servo 2" }, 
      { key="Src3", name="Servo 3" }, 
      { key="Src4", name="Servo 4" }, 
    },
    init = ...,
    wakeup = ...,
    configure = ...,
    read = ...,
    write = ...
  })
```

?

**Comment by azaz44** [comment]
One more thing. I find it very useful sometimes, to have a "mixing" script, which does not generate any output at all, but rather makes some action. For example it logs data to a file after flight is over.

In OpenTX this would be a mixing script, with some parameters, which has no outputs.

In Ethos this is tricky to do, because *source* scripts are the only one which can perform such tasks, but they need to create a source always. Could this be improved?

Maybe above function `registerSourceGroup` could accept empty list of sources? Of course UI would need to allow enabling this script for a model.

Then such fuction could have some better name, like `registerBackgroundTask` or whatever describes its purpose better.

**Comment by bsongis-frsky** [comment]
`registerBackgroundTask` makes sense to me, and it should be possible to enable / disable it on a per model basis, perhaps with some argument (like the other proposal for Lua Sources)

**Comment by bsongis-frsky** [comment]
I am under the impression that the same `registerXXX` should be used to solve issue #2051

**Comment by bsongis-frsky** [comment]
What about this?

```
- Lua Task Example

local function taskInit()
  print("Task Init ...")
end

local function taskWakeup()
  print("Task Wakeup ...")
end

local function taskEvent(event)
  print("Task Event", event)
end  

local function init()
  system.registerTask({key="LuaTask", name="Lua Task", init=taskInit, wakeup=taskWakeup, event=taskEvent})
end

return {init=init}
```

**Comment by azaz44** [comment]
@bsongis-frsky Yes, this looks good. But I think configuration would also be very useful (configure, read, write).

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/231829622-24bb313f-a3f2-4ed3-8c71-afae10690ea0.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/231829693-dcdb637e-fe15-45dd-856a-4742e055c166.png)

**Comment by bsongis-frsky** [comment]
Lua will have its own page.
Lua Tasks and Lua Sources will be enabled on a per model basis, they will have a configuration form, plus read and write methods

**Comment by azaz44** [comment]
This is so great to hear, thx for all the effort 👍
