### ISSUE TITLE
model.createCurve() fails in  lua create() routine

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2340]
local function create()
  local VolName = "VolTestCreate"
  local curve = model.getCurve(VolName)
  if curve == nil then 
    curve = model.createCurve() 
    if curve ~= nil then
      curve:name(VolName)
    end
  end
end

this code fails, but if you try it in wakeup() the code works.
Is it not allowed to use createCurve in lua function create()

**Comment by strgaltdel** [comment]
Hi Joerg,
Bertrand may say something related to this special use case,

but my experience is:
there are always some situations, where (especially display related) methods won't work within create handler, like evaluate display size...

"my" solution is to flag something like a "widget.runonce" bool in create, so that i can call another "one time" function on the very first run of the wakeup handler to determine this kind of widget wide variables.
it seems, when wakeup handler is ready," the complete lua environment too".

**Comment by Storchy1** [comment]
Of cource i can do this, but the wakeup Handler is called the first time
if all other loaded lua scripts are finished with their own-create() routines. if i need the curve in other lua scripts so i have to implement in all lua script a flag widget.runonce. Thats not pretty smart i think, but for the moment i will do it this way
Thanks you for your help!

**Comment by bsongis-frsky** [comment]
In `create()` of which object? A source? A widget?

**Comment by bsongis-frsky** [comment]
I have tried it in 1.4.6 and I see no problem, the curve is created. Would you please try 1.4.6 (pre-release) or attach your whole script?

**Comment by Storchy1** [comment]
I forgot to say that so code works in X20 Simulator, but not on the XE Transmitter, sorry for that.
There is no XE Simulator to Test, but i think that would make no difference.
Is there a change to get an XE(s) simulator?
I will try the 1.4.6 and will inform you
Thanks a lot

**Comment by Storchy1** [comment]
I have seen that there is a XES Simulator thanks a lot for that

**Comment by Storchy1** [comment]
i have tested the script with Pre 1.4.6
load the script curve in screen 1
open the curves folder and you see the new curve **_CurveCreate_**
delete the curve 
reboot the XE transmitter
The transmitter fails to start. i have to disconnect the battery and the next start in bootloader mode.
i delete the lua script and then i can start the transmitter in normal mode
the script works fine in the XES-simulator.

Thanks a lot for your help

[Curve.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10444412/Curve.zip)

**Comment by Storchy1** [comment]
[Curve.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10445530/Curve.zip)
I have forgot the screenshot of Info  XE
