### ISSUE TITLE
Is there a way to start a lua script from the file browsers for a certain extension?

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#2342]
I want to port my LView to ETHOS and one way of selecting the files could be to browse to the log files and have an option to open that file with my lua. Can you resgister a tool for a certain extension?

**Comment by azaz44** [comment]
This sounds like an interesting feature to me. So we would be able to register handlers to view or edit certain types of files with lua scripts - very useful.

**Comment by loetefix** [comment]
Btw a log viewer should be the minimum that comes built in to ethos.

**Comment by RealTadango** [comment]
> Btw a log viewer should be the minimum that comes built in to ethos.

This is one of the features that almost made me switch to Jeti. I don't see why you would have such a nice logging option without any option to view it in the transmitter itself. They put all kinds of stuff in the os that hardly anyone uses but they never took a start at a log file viewer..... TO bad ETHOS changed things with the log files so it is now impossible to adapt LView.

**Comment by azaz44** [comment]
> > Btw a log viewer should be the minimum that comes built in to ethos.
> 
> This is one of the features that almost made me switch to Jeti. I don't see why you would have such a nice logging option without any option to view it in the transmitter itself. They put all kinds of stuff in the os that hardly anyone uses but they never took a look at a log file viewer..... TO bad ETHOS changed things with the log files so it is now impossible to adapt LView.

Hey, we use all these features, I don't see anything in Ethos which I wouldn't use :)

What did they change in logging, file naming?

**Comment by azaz44** [comment]
BTW, I agree that loggig in Ethos, without scripts, would be the best solution.

**Comment by RealTadango** [comment]
> > > Btw a log viewer should be the minimum that comes built in to ethos.
> > 
> > 
> > This is one of the features that almost made me switch to Jeti. I don't see why you would have such a nice logging option without any option to view it in the transmitter itself. They put all kinds of stuff in the os that hardly anyone uses but they never took a look at a log file viewer..... TO bad ETHOS changed things with the log files so it is now impossible to adapt LView.
> 
> Hey, we use all these features, I don't see anything in Ethos which I wouldn't use :)
> 
> What did they change in logging, file naming?

OpenTX uses 1 file per day. ETHOS uses a time stamp in the file name. For OpenTX i could test for all filenames in the last 600 days because i know what they would be. With the time component this is not doable.

To have a file selection in EHTOS we would need a lua function to itterate all files with a certain namen OR an option to open LView and passing a filename using the file broweser.

**Comment by azaz44** [comment]
Ahh, I see. Yes, I know your solution with selecting the date and just testing if file is there, I was using your script.

I think all things would be useful - ability to enumerate files (it was really missing in OpenTX, as well as more complete io library). But having LUAs for handling files sounds great too. And built-in log viewer sounds great too.

**Comment by mmasch** [comment]
This would be a nice addition to check Ethos logs on the field without a PC. 
The script is allready there from RealTadango...
Please add this :-)

Br. Morten Masch, Norway.
