### ISSUE TITLE
Countdown timer feedback incorrect based on setting

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#2345]
If I set a countdown timer with the following settings:

**Start:** 00:03:00
**Countdown Start:** 01:00
**Countdown Step:** 60s

A voice feedback is given at 2 minutes. This is not excepted as the countdown start is set at 1 minute.

**Comment by mawzthefinn** [comment]
Minute callouts are enabled for timers if voice is selected, regardless of the countdown settings.

**Comment by MrD-RC** [comment]
That doesn't make sense when you can specify when you want the countdown to start. To me, that is when you want the callouts to begin. 

You should at least have the option to have callouts every minute or not. To be honest, I like having the voice, but with a 5 minute timer, I don't care about times until I reach the last minute.

**Comment by Pfeffery** [comment]
Agreed. At least an opt out option would be appreciated.

**Comment by mawzthefinn** [comment]
I would agree that disabling minute callouts should be an option. It is in OpenTX and should be in ETHOS as well. 

The function is separate from countdown (which is intended to give you more fine-grained callouts at the end of your elapsed time)

**Comment by Dsrenger** [comment]
Yeah, the minute call outs are annoying.

Just as workaround tip for the others. I have a usual timer that I see. In your case 3min start. This timer is configurated silent without call outs.

Then I have second timer in the background starting with 1min countdown. This timer has the voice feedback. Start condition is a logical switch that gets active when timer 1 is at 1min.

Both timers get reset with the same switch.

So timer 1 shows the time on the screen and is muted.
Timer 1 starts a timer 2 at 1min left. Timer 2 has call outs.

Workaround,but perhaps a solution for you until something gets added to ethos.

**Comment by mawzthefinn** [comment]
No, separate functions.

Countdown is intended to do things like 5s callouts for the last 30-60 seconds of the flight (important for glider guiders at the end of a window), while Minute calls are general 'you are here' calls.

I think a fair bit of how this functionality behaves has been driven by the needs of sailplane pilots, who need both functions for practice.

**Comment by MrD-RC** [comment]
Sounds like there should be a **minute countdown start**, as well as the **countdown start** and **countdown step** for the precise setting for the end of the timer. I've also heard from people on YouTube that would like the option of disabling the 10 second countdown.

**Comment by pal-john** [comment]
I have the same Issue. It did work in FROS. As a gas flyer I found it very useful Flight time set to 15 min. Countdown begin at 5 min. This was an indication of prepare to land. As now it is annoying to me and more importantly annoying to pilots near me.

**Comment by pal-john** [comment]
As Drenger commented there is a workaround using Logic switch, unfortunately beyond my capability. Took me two days to find out why it would not work LOL.

**Comment by mawzthefinn** [comment]
This is corrected in 1.5.0 latest Nightlies. Minute calls are no longer baked in.
