### ISSUE TITLE
Ethos Suite update failure on MacOS 13.1

### ISSUE THREAD

**Issue by dap35** [FrSkyRC/ETHOS-Feedback-Community#2347]
I get the popup when I launch Ethos Suite 1.4.4 to download the update.  As soon as I get the popup to download the updated installer, I select OK and immediately get an error.   - Crash log attached.
[crash-2023-01-18.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10451279/crash-2023-01-18.txt)

**Comment by Nicholas-Luoyi** [comment]
There was something missing on the server. It has been uploaded. Please try again.

**Comment by dap35** [comment]
Unfortunately, I have already downloaded and run the installer manually.   Hopefully someone can confirm it works.  My Windows10 system updated fine.

**Comment by dap35** [comment]
I went ahead and removed 1.4.6, installed 1.4.4.  Upon start, it downloaded and updated without issue.  Thanks!
