### ISSUE TITLE
X12S navigation buttons have to be double press to navigate menus on 1.4.6

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2348]
have an issue have to double press to navigate menus on 1.4.6
on all buttons on 2  off my X12s rolled one back to 1.4.5 and its fine

PgUp & PgDn & MLD & SYS & TELE & RTN all have to be double press to move through menus 
some times its 3 or 5 press to move

https://youtu.be/yrybLD7yipk

**Comment by bsongis-frsky** [comment]
I wonder if your gyro works correctly. Let's imagine I2C is too slow, it will make the radio almost unuseable. Then it should be detected and gyro disabled.

**Comment by yak-54** [comment]
working on it

**Comment by strgaltdel** [comment]
would assume its a very specific / hw problem
just to add anothers feedback:
today,  my x12 update worked like a charme,
gyro works precise,
not any problem

**Comment by yak-54** [comment]
> would assume its a very specific / hw problem just to add anothers feedback: today, my x12 update worked like a charme, gyro works precise, not any problem

one  x12s would say yes hardware  on one but not on 2 off them
i am beginning think it was ethos suite and windows issues i did do manual update on them and the seam ok now
