### ISSUE TITLE
Enhancement: Logic switches screen font wheight of  numbring

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#2349]
Firmware 1.4.4 and before
On the Twin Xlite the numbering is too close to the lsw name. There is no space between numbering and name.
 I think the font of the logic switch numbering should be very small. It will improve readability on this screen.

 It would be good for every transmitter.

**Comment by bsongis-frsky** [comment]
On this screen?
![image](https://user-images.githubusercontent.com/50834778/213438795-7728b942-9ce3-4d83-b442-f7311b541a0e.png)

**Comment by 00steven** [comment]
Yes that screen no spacing between LSW17Test

**Comment by bsongis-frsky** [comment]
It would help to use "LS" instead of "LSW"

![image](https://user-images.githubusercontent.com/50834778/213449505-2302c393-8249-494b-92a9-ccd720c1f6ce.png)

**Comment by bsongis-frsky** [comment]
Also the screen title doesn't need the ellipsis:

![image](https://user-images.githubusercontent.com/50834778/213450016-2ffa0f48-678a-4173-a7ff-a6963a6a4a22.png)

**Comment by mawzthefinn** [comment]
This update has been released. It's on 1.4.7 for sure.
