### ISSUE TITLE
Low Power Mode

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#235]
Feature request:

Please add a Low Power Mode. To be used during long periods of programming or flying indoors. This will place less stress on the battery and power output section. It would be similar to "range check mode" without the constant warning, and allow the user to operate the transmitter normally (programming or flying). The transmitter would issue a "Low Power Mode" warning upon first turning on, or could be made necessary to turn on each time the user wants to use it.

**Comment by froqstar** [comment]
Is there really a need for this? I would expect radio battery to last multiple hours already when actively working on model programming. Do we know how much power is consumed by the RF logic in comparison to the screen and processor etc.?

I think the security risk of accidentally leaving this mode enabled when flying is not worth the risk, but maybe there is a smart way to disable low power mode in time. For example when RSSI gets too low or something.

**Comment by janekx** [comment]
I am affriad we will see some users forget change power. Some can use it for healthy resons, but will crash, can be source of bad reports about distance and other unwanted issues
