### ISSUE TITLE
Sensor adjustment

### ISSUE THREAD

**Issue by stealdesk** [FrSkyRC/ETHOS-Feedback-Community#2350]
There needs to be a way to adjust any sensor to make the values read correctly. EX. AccZ reads .845g while at rest, ASS-100 sensor reads 12MPH while at rest.

**Comment by mawzthefinn** [comment]
This is requested as part of #955 , closing off as a duplicate, please continue the conversation under that issue

**Comment by stealdesk** [comment]
Will there be a possibility to adjust sensors that read slightly off?
