### ISSUE TITLE
Adding / to model name appears to delete the model

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2352]
I renamed a model to a new name which included a / in the updated name and when I went to select another model, the model I'd just renamed appeared to have disappeared and I was now in the + model folder. I could not find the renamed model in any folder.

I then tried to create a new model called PROB/ and again when I went back to model select there was no model called PROB/ in any folder!

It's not clear whether I now have orphan .bin model files so if this is a problem a way to locate any orphans would be appreciated.

(Fortunately the model I was trying to rename was a clone.)

(Ethos 1.4.5)

**Comment by mawzthefinn** [comment]
/ is an invalid character for a file name, which is why you had the issue.

It probably should be disallowed for model name entry

**Comment by Jedsters** [comment]
Yes, disallowing would be fine. The main problem is that it can be selected with undesirable results.
Thanks

**Comment by mawzthefinn** [comment]
This is corrected in 1.4.7
