### ISSUE TITLE
Sticky logic switch is triggered during startup

### ISSUE THREAD

**Issue by TypTypensen** [FrSkyRC/ETHOS-Feedback-Community#2356]
When the transmitter (Tandem X20S) is started, a sticky logic switch (LSW2), which is triggered by the output of CH3, will be high.
I want to use this LSW to control a flight time timer, so that the timer is constantly running until it's reset manually after landing. The LSW2 gets triggered by LSW1 which is high when CH3 is above a certain value.
When the transmitter is booted, timer 1, which is controlled by LSW1, counted down 1 second already and timer 2, which is controlled by LSW2, is running.
A workaround is to use a switch as an active condition for LSW2 so that during the startup sequence LSW2 is disabled. But this is not useful as I know that I will forget to turn on the logic switch after startup at some point or forget to disable it before booting.
However a "delay before active" setting for LSW2 does not help. So even when this setting is set to 6 seconds
and CH3 is always at "-100%", LSW2 will be hight after 6 seconds after booting.

I programmed my LSWs like this:

![LSW-Overview](https://user-images.githubusercontent.com/123247882/213868713-108fec06-ed08-4611-ba95-da29a57abb98.jpg)
![LSW1](https://user-images.githubusercontent.com/123247882/213868719-5f5cb865-918b-430c-b7c5-a7c39ad6c275.jpg)
![LSW2](https://user-images.githubusercontent.com/123247882/213868720-9f181c0c-3ec1-4353-b087-da7a61bf3537.jpg)

**Comment by mawzthefinn** [comment]
Channels initialize at 0 then go to the assigned position. This initialization is what's triggering your issue.

If you set T-POS to a 10 trigger instead of -80, it will work as you expect.

I'm working a fix through my head. Note that Active Condition does NOT prevent a sticky from activating, it simply forces the output to false while the Active Condition is not true.

**Comment by TypTypensen** [comment]
Thanks for your fast reply!
Setting T-POS to a 10 trigger works good enough for me, so I'll close this issue.
