### ISSUE TITLE
Maximum mixer value 200% or 100%

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2357]
Hello,
I know that this topic will be difficult.
Functional modellers heavily criticise that mixers can run up to 200%. But they need a maximum of 100%, because the range between 100% and 200% leads to idle times and endangers the model.
Now my question: is it possible either in the basic model settings to limit the mixers generally as an option to 100% or to build in individual mixers in the mixer itself the limit.
Thank you for your understanding.

Translated with www.DeepL.com/Translator (free version)

**Comment by Target0815** [comment]
An option in the model setting would be the most sensible solution because it is just necessary or not depending on the model division.

**Comment by uj-berlin** [comment]
Hello,
that would be extremely useful for functional modelling especially for recursive mixers used for a hydraulic servo mode, cruise control or a step switch (for example....)
All that was functional before changing to mixer range above 100%

**Comment by hrenz** [comment]
much better solution:
you got an special rekursions Mixer typ, an integral Mixer,  for that
wich all the free paramteres you need

for hydraulic cylinder, gimbal, etc.

**Comment by hrenz** [comment]
The extension to 200% is nice but not thought through to the end
Therefore an improvement in the free mixer.
One needs an option for the range limit, 
as they are already present in the trim mixer.
With this you can limit a range / make clipping as you need it.
and has thereby also the range monitoring for the recursion mixer and/or the integral mixer already ready.

**Comment by bsongis-frsky** [comment]
Default maximum is +100% 
I don't understand why it could be an issue to allow bigger values in case the user really needs it

**Comment by uj-berlin** [comment]
Hello Bertrand,
as a functional modeller i have need of a hydraulic simulation or a step switch. I realize these with recursive mixers. And therefor it is a problem when the mixer goes over 100%. Then you have to do a workaround with logical switches to stop the mixer at 100% Better would be the possibility to set the mixer max to 100%
Best Regards
Uwe

**Comment by Wolepo** [comment]
Let me make it understandable with a picture:
![Überlauf](https://user-images.githubusercontent.com/90325526/235878363-02474d36-f7a2-46a9-bbf5-5bcc62ce3884.jpg)
When using a recursive mixer, the 100% limit is exceeded at some point. This should be adjustable in this case: Limit =100% or 200%.
