### ISSUE TITLE
 In the TD mode the 2.4 Ghz RSSI fluctuates wildly when Info screen is selected.

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#2359]
Hello

X20S
ETHOS: 1.4.6 FLEX
HF FW: 2.2.2

See attached video.

There is no fluctuation under Access.

Enzo

https://user-images.githubusercontent.com/87656206/213895814-5ec3dcda-1785-4d80-add6-24d4aa57fa23.mp4

**Comment by Vincent70700** [comment]
Bonsoir,
J'ai le meme probléme mais en bien pire. 
sur la page info toutes les 2s il perd complettement le 2.4 et le 900 en meme temps.
j'ai 2 Rx TD R 10. sur l'unnca fait juste comme vous et sur l'autre je perd tout. je cherche la cause d'un crash par perte de liaison radio alors je m'interroge la dessus. moi non plus en ACCESS pas de fluctuation.
Je fini par me demander si je vais remonter le prochain avion en tandem ! 
jamais aucuns problèmes en access. 
Si quelqu'un a une idée sur la question et pourquoi c'est si differant entre 2 Rx ayant la meme mise a jour 
Bonne soirée

**Comment by bsongis-frsky** [comment]
@Vincent70700 Le problème est toujours valide ?

**Comment by bsongis-frsky** [comment]
La liaison radio est perdue également ? Ou c'est juste la télémétrie ?

**Comment by Vincent70700** [comment]
Je n'ai pas fait la mise a jour 1.4.9 pour l'instant donc pas pu contrôler. 
Peu être qu'une autre personne pourra mieux répondre que moi.

**Comment by bsongis-frsky** [comment]
Ce serait intéressant de savoir, mais je ne pense pas que 1.4.9 apporte une amélioration là dessus, cela ressemble plus à un problème côté RX (surtout s'ils ont un comportement différent). J'ai poussé à l'équipe RF.

**Comment by mawzthefinn** [comment]
There is a fix for this listed in TD ISRM v2.2.6 and TD ISRM PRO v1.1.12
