### ISSUE TITLE
min /max / live telemetry data displayed 

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#236]
Hello,

it would be awesome to get min, max and live telemetry data displayed on the screen under Ethos. At the moment it is just the live data. Would be nice like under OpenTx to have the choice between all three datas or just on or to of them.

**Comment by islandflight** [comment]
Hi you can. You need to long press the enter button when the telemetry value is highlighted in the screen set up page

**Comment by Testname84** [comment]
I tried like explained in the #236 and it doesn't work. please check again.
