### ISSUE TITLE
XES simulator: top screen doesn't display widget

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2360]
**XES 1.4.6 simulator**

After I assign a 'Channels' widget to the top screen, it is not displayed (the display area remains white).

I've tried with a couple of other widgets, same result.

**Comment by uj-berlin** [comment]
I have the same behaviour.

**Comment by bsongis-frsky** [comment]
You are right, it's strange because I have used this simulator during the whole development stage
