### ISSUE TITLE
In the hardware section the image of switch is above the name of switch 

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#2361]
Send photo

![IMG_2928 2](https://user-images.githubusercontent.com/87758703/213912114-c3289fb1-f6f0-4edc-b0f5-4db71dd5792e.jpg)

The solution would be to move the switch image to the right.

**Comment by Target0815** [comment]
Which transmitter? Which Ethos version? Tried test with English language?

Sorry, but such a photo without further details is not worth much ...

**Comment by jasalca** [comment]
FRSky X20 Tandem in Blue color in Ethos 1.4.6. In English language is perfect but  in other languages they have to take it into account also because It can have longer words.
In the photo you can see perfectly that the switch icon is above the word switch in spanish "Interruptor"

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/214010826-a89ca59c-6b83-436d-b5d4-900caf69d4e1.png)

**Comment by spoke2570** [comment]
Should we assume that the spelling error (interruttore) in the solution image has also been addressed?

**Comment by bsongis-frsky** [comment]
I don't speak this italian and it has not been reported.
Which is the right word?

**Comment by spoke2570** [comment]
If your screen grab is in Italian then the spelling is good. The OP had used a Spanish screen grab.

**Comment by jasalca** [comment]
Everything is correct in both Spanish and Italian. The case can be closed. Thanks you Bsongis-Frsky
