### ISSUE TITLE
Checklist display (and setup) can be confusing

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2362]
Considering electric gliders they commonly use the left stick (mode 2) Y axis for butterfly. The throttle is then assigned elsewhere, e.g. a pot or slider (some of the F5J guys even use a 3 pos switch for repeatability of knowing exactly how much power they'll get).

Things can become confusing on selection of a model on the checklist screen. If I e.g. reassign the motor to Pot3 (because I have butterfly on the left stick) then if Pot3 is e.g. in the central position (half throttle) it is still the left stick on the graphic which indicates I have half throttle instead of Pot3 at checklist display! But Pot3 can also display it is not at it's predefined position. I therefore have two alerts that my throttle is half open and no alert that my butterfly is not fully closed.  

I also question whether the use of the word Throttle on the Checklist setup is optimal, since this appears to be being used to display the position of the Left Stick Y axis, why isn't the name I've given the left stick Y axis in the General, Sticks screen used here?

The good news is that the Throttle Not Idle text does correspond to how I have setup my throttle rather than the left stick. 

Thanks

**Comment by mawzthefinn** [comment]
Throttle is using the input designated by the Throttle mixer, if present. So text is correct.

The image is technically incorrect.
