### ISSUE TITLE
Enhancement - Display any bitmap in widget

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2363]
Currently we have a Model Bitmap widget which displays the image selected in Edit Model, Picture. It is (AFAIK) only possible to display this one image. 

Maybe we could have another similar Widget called simply Bitmap which allows us to select from any of our bitmaps so we have the option to display more than one image per model.

Thanks

**Comment by strgaltdel** [comment]
Imho such an extension should be addressed to the community, not to Ethos development.
Developing a small Lua widget for additional image uploads is not a big deal.
If there is a real need, I'm sure a Lua hobby developer would be interested in it themselves and would code and release it. 

Maybe that's even the motivation for you to start with Lua.
Such an uploader would be a good beginner task. 

I don't know exactly how much such a widget would "consume",
but an "ethos-integrated" solution would permanently consume resources,
regardless of whether the current user has a demand or not.

regards

udo

**Comment by mawzthefinn** [comment]
Agreed, that's an easy Lua to write and is best addressed as such.

**Comment by azaz44** [comment]
Yes, that's what we have LUA for.

**Comment by Jedsters** [comment]
Ok, I've not really played with LUA, but if it is likely to consume resources needlessly an can be addressed via LUA I'll close. It just seemed like a quick win to me, you can display one image, so displaying a different second one seemed a small change.
