### ISSUE TITLE
Ethos code regressions in Model id area?

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2365]
Re  No automatic change of the model ID #101 as far as I can tell this was closed as completed and yet I've just created 3 new models all of which have been given a default model id of 0. Has this fix been regressed?  Giving new models the same model id is obviously far from ideal. Allowing models to have the same model id if the user specifies such is perhaps acceptable, but should come with a warning when the dupicate model id is accepted.

Re #326 this suggests that the display should show the model id for each model on the model select screen. Again, as far as I can tell this is no longer available even for the models I've just created. I don't believe this would be an issue if Ethos allowed a way to automatically pick a spare model id, but so long as there is no easy way to check which model ids are spare it is more an issue as finding a spare model id involves trawling through every model / model id etc.. (I suspect it was removed when the Select model display was changed to allow display of more models and I'd rather keep that and loose the model id display if those are the choices).

Also cloning models appears to give the cloned model a 'random' but not necessarily unique model id! I had a template with model id 63 and cloned it 3 times, the model ids given were 2, 4, 6 - despite all of those already being in use by existing models. 

(All tests with ACCST D16)

Thanks

**Comment by mawzthefinn** [comment]
Model ID's are assigned based on incrementing by 2 starting at 2 from power on. This is the same behaviour that has been present for a while.

There is no randomness, it's a simple increment by 2 function for all models created/cloned in a given session.

Unfortunately full-automated unique ID assignment is limited by 2 things.

1. The Horizon patent on Model Match
2. Limitations on protocols and model ID (especially for MPM users).

**Comment by Jedsters** [comment]
In which case we urgently need a way to see which model ids are assigned to which models and where any duplicates lie (and hopefully what the free numbers are). Perhaps a complete table of 0 - 63 with model names against each id.

**Comment by Jedsters** [comment]
I'm not sure what this patent on model match is, but find it hard to believe that should stop you (although I can understand the relucatance). Surely all you are doing is selecting the next free entry in a list, the purpose is not important. I was doing that in the late 80's when I was writing code professionally so I don't see how anyone can claim it is in any way unique or novel.
If you can't do that, maybe you can allow us to scroll through the list of model-ids and highlight those which aren't in use. Or as you suggest, alert if a model id is in use.  

I can understand why there have been few complaints, most of the time people select the right model and there is no problem. It is only a problem if someone selects the wrong model (or fails to select another model) which happens to have a duplicate id and it is not different enough to be noticed immediately. The problem is when there is a significant difference e.g. in landing mode causing e.g. a flap to be over-driven to the point it locks or the wiper gets caught and won't retract,  then the consequences are a model loss!

**Comment by mawzthefinn** [comment]
I'm closing this off for now, the long term solution will be #326 when it arrives, and possibly an alert as well.

The patent covers automated selection of a unique GUID+ID for binding. It's probably beatable in court but is far too easy to work around with semi-automated solutions like the current situation to make a potential lawsuit viable, especially as it nears expiry in a few years.
