### ISSUE TITLE
X20S update V1.4.5 to V1.4.6 some things don´t work now

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#2367]
X20S Update from V1.4.5 to V1.4.6 
What do you do all the time with the updates?
Things that worked so far do not work after an update again

Reduce brightness after 90s no longer works, 
(only switches and sticks monitored)

Inactivity after 5 min does not work anymore

That is very convenient

**Comment by hrenz** [comment]
after the update to V1.4.6 all general parameters and alarm parameters 
are seem to be the same, at least they are displayed that way.
Screen dark mode after 90s
inactivity alarm after 5min
but nothing happens at all!
no screen darkmode, no inactivity alarm
nothing what should come there.

then parameters changed,
Darkmode time changed to 80s
Inactivity alarm changed to 3min
screen changed from light to dark

From now on everything works as it should.

It looks like after the update a few things that have to do with the clock were no longer activated.

**Comment by hrenz** [comment]
X20S update from V1.4.5 to V1.4.6

Power off, power on, create new model, etc.
Old models are also there, so far everything seems ok.

Main settings not changed, but!
Screen dark after 90s, no!
Inactivity alarm after 5min, No!
Both do not work!

BUT:
All settings have the same setting after general and alarm screen as before,
everything stayed the same, nothing was changed, everything was taken over.
Activation by switch and stick, no gyro activated, etc.

Screen does not go dark, inactivity alarm does not come!

Then played around a bit in the parameters:
Values changed to 60s and 3min,
Screen view from dark to light to dark
Activation all on, all off, only switch and stick activated
Silent mode On, Off

 
And from now on it always works as it should!
Screen dark after 60s, inactivity alarm after 3min.

Result:
There seems to be something that must be triggered with the clock not active.
The parameters are all there, but are apparently only displayed in the screen, but are not active.
Only when one changes them, they are taken over again and activated.

Further persons (in the Engel forum) had this problem
the solution has now been fixed by other people like this

**Comment by bsongis-frsky** [comment]
Is your gyro correctly calibrated?

**Comment by bsongis-frsky** [comment]
I am not sure I understand your message correctly, someone with good english can reproduce / explain it better?

**Comment by bsongis-frsky** [comment]
No other report?

**Comment by Jedsters** [comment]
> I am not sure I understand your message correctly, someone with good english can reproduce / explain it better?

I am guessing that what @bsongis-frsky is getting at is that when you upgrade to 1.4.6 you have to calibrate the tx internal gyro and he is questioning whether this has been done. IIRC I was forced to calibrate it, so unless you had the above problem immediately after you upgraded and you hadn't turned the tx off that you will also have been forced to? As I recall, the first time I turned on the tx after upgrade to 1.4.6 it went into the gyro calibrate dialog. Apologies if I've misunderstood.

**Comment by bsongis-frsky** [comment]
Closing this issue as nothing seems confirmed
