### ISSUE TITLE
Mixer graph confusing on slower resolution LCDs

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2368]
I'm using Horus X10 but see same problem on X18. Mixer graph does not have labels, but it does scale automatically the Y axis for proper range. This is super confusing, for example in these 2 cases which produce same graph, but very different results.

![image](https://user-images.githubusercontent.com/42830563/214168450-3652514a-d08a-4033-877d-2e8f9b280787.png)

![image](https://user-images.githubusercontent.com/42830563/214168511-83f9a070-0abb-4754-9034-db3470b4ad29.png)

I did exactly such curve to scale a pot from -100..100 to 0..100 and was really confused. I assume other users will be as well.

What I see in sumulator, is that X20 has solution for this - it shows labels:

![image](https://user-images.githubusercontent.com/42830563/214169479-03ffd760-674c-4715-bd2e-2daec98977e8.png)

Which makes you aware, that the graph Y axis is not in -100..100 range anymore.

#### Suggestion

Could show labels on 480 LCDs too. And if this is not possible, how about fixing graph to -100..100 (no auto range on Y axis) on such radios?

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/215527894-a44a1ed7-1e08-4225-8313-703e07e075eb.png)
