### ISSUE TITLE
Suite Eject Drives option

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2369]
Please can we have a Suite option to Eject Drives

Thanks

**Comment by strgaltdel** [comment]
for what reason,
what should be the purpose of an "eject" button?

standard win setting is a deactivated usb cache,
introduced as a policy since w10 v1809
app. 4 years ago

**Comment by yak-54** [comment]
When was it removed ?

**Comment by MIKE-DAILEY** [comment]
And it is still there today!

**Comment by Wolepo** [comment]
Is present
![Auswerfen](https://user-images.githubusercontent.com/90325526/214293886-ba6d5ef0-0555-4800-8f12-9f991d03e40a.jpg)

**Comment by Jedsters** [comment]
Apologies, I was being blind!
