### ISSUE TITLE
Organize Global Special Function Outside of a Model

### ISSUE THREAD

**Issue by arshish1612** [FrSkyRC/ETHOS-Feedback-Community#2371]
1. Would it make sense to have Global Special Functions created outside of the models scope? Currently if you delete the model you loose the Global Special Function. Having a separate section for Global Special Function under General would make them truly Global.

2. Would be useful to have an option to convert a Global Special Function to Local and in effect make a local copy of the Global Special Function under each model and then delete the Global one.

**Comment by mawzthefinn** [comment]
1. Once a global function is saved, it is truly global, you do not lose it on deletion of the model in question (just tested this on 1.4.6). MOdel files are saved on model change, so you must do this first.

2. That would make it WAY too easy to accidentally pollute all models with a bunch of random local functions.

**Comment by mawzthefinn** [comment]
Global functions are all listed at the top of the Special Functions page, and editable from there. You can edit a Global Function from any active model. 

They however are NOT created on all models, they exist in the radio configuration when set to global and the individual model file when local (this is an important distinction).

**Comment by Benno00** [comment]
Where should these be set under special functions? If I select Global in the SIM X20 Vers. 1.4.6, these apply to all models! If I set this to INACTIVE in one model, the function is INACTIVE in all models!
The GLOBAL and INACTIVE/ACTIVE switches appear to have the same function or not work as intended.

**Comment by mawzthefinn** [comment]
They're under special functions because they are special functions. They can be either global (apply to all models) or local (apply to the active model).

Global sets whether a function is global or local
Active/Inactive sets whether a function is active/inactive

If you set a global function to Inactive, it's inactive on every model because it's global. There is no way to currently de-activate a global function for only one model.

**Comment by Benno00** [comment]
Ah ok, understood, thanks

**Comment by arshish1612** [comment]
I still feel atleast having the Global Functions created / managed under a separate menu under the radio rather than the model would be better.

**Comment by bsongis-frsky** [comment]
The opposite was said in OpenTX :)
