### ISSUE TITLE
FrSky Tandem X20 HD streaming information

### ISSUE THREAD

**Issue by Cristian-wp** [FrSkyRC/ETHOS-Feedback-Community#2373]
Hello, this is not a feedback but a question before purchase this awesome radiotrasmitter.
On my drone I have a camera that stream the video on my PC, on my PC I run a self made program to identify some objects realtime on the video.
Is possible to send the "modified" video from my PC to the FrSky Tandem X20 HD screen in someway?
I have see that there is a HDMI port but is identified as output port, someone can tell me if is really only for output?
Thanks in advance!

**Comment by mawzthefinn** [comment]
The HDMI port is output from the HD Zero video unit in the radio.

To stream to the X20HD's display, you would need to send your video stream from the PC over a HDZero compatible VTX to the radio.

**Comment by Cristian-wp** [comment]
Hi @mawzthefinn thank you for your answer. 
Have you already do something like that?

Another question, is possible to switch the video input from the  X20HD? (If my PC die, I would like to change the display input source from my PC to the drone)

Have you any experience about streaming from long distance? Same question about the command send to my drone. 
I think my missions will be in a range of ~2/2.5Km, on the manual they say that the radio can transmit upon 50/100Km, is true?

**Comment by mawzthefinn** [comment]
That depends on the VTX used on your aircraft. It must be HD Zero to be compatible with the X20 HD

As to control range, the 900M section on the X20 is capable of very long ranges at full (1W) power. >50Km has been proved by others.

I don't personally fly Long Range, there's no legal way to do it in my country as a hobbyist.

**Comment by mawzthefinn** [comment]
Closing off as the core question ahs been answered. I would suggest asking further on the X20 thread on RCgroups, there's more HD users active there.
