### ISSUE TITLE
Unhide input curve and make it editable in Butterfly mix, also add curve to Elevator 

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2375]
Ethos 1.4.6

Please unhide the input curve and make it editable in the Butterfly mix, as was discussed and agreed in issue #1764. This is needed so you can define a deadband at the start.

In addition, also add the ability to assign a curve to the Elevator output, also discussed in issue #1764. The compensation needs be be non-linear, so the majority of users will want to assign a compensation curve.

**Comment by aalain8** [comment]
Hello,
I still hope to see this request succeed.
Considering the number of people who ask for this on the forums, I am surprised not to see more opinions, too bad!

**Comment by lightbulbjim** [comment]
Unstale.

**Comment by mirko91** [comment]
Hopefully this feature will be added on 1.5.0. It's absolutely needed for any serious glider setup

**Comment by lightbulbjim** [comment]
I ended up just creating my own butterfly mixes like in OpenTX. I initially did so as a stopgap but actually prefer it to the built in butterfly mix now. I find the built in mix confusing and I always have to think carefully how it works before making any changes. Might just be me 🙂 .

**Comment by lthole** [comment]
Good news, this will be addressed in 1.5.0 in a better way: as soon as you define your own curve the internal ‘offset’ curve is switched off. 

Refer to #2579 for details.
