### ISSUE TITLE
Line Chart y-axis numbers are cut

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2376]
With ethos 1.4.5 the numbers of the line chart widget are cut with RPM telemetry sensors on TWIN Lite S. The unit should be shown above or under the axis and not with every value. 

![image](https://user-images.githubusercontent.com/51311453/214946873-42d7cf43-253b-43e2-b0ab-7c764451591c.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/215507607-375c9de4-49ed-4637-a268-7447da43b2a7.png)

![image](https://user-images.githubusercontent.com/50834778/215508372-a3a3ef0a-19b0-4471-9723-0967312688b6.png)

**Comment by NilsRo** [comment]
Hi.

Is the legend width static or dynamic? Could be an issue with voltage to be aligned in a 2 widget Layout or in German translation as the unit is longer: u/min

Cheers
Nils
