### ISSUE TITLE
Ethos v1.0.6 no files

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#238]
When you click on v1.0.6 it only displays 2 assets.
Please see photo
![Screenshot_20210514-171936_Chrome](https://user-images.githubusercontent.com/81478751/118299669-f158db00-b4d8-11eb-98a9-e59ad5951823.jpg)

**Comment by MIKE-DAILEY** [comment]
Will be posted soon.

**Comment by Liverboy77** [comment]
Ok thanks
