### ISSUE TITLE
1.4.6 - Ethos on X18S internal module with Flex option

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2382]
Hi,

would have to with this configuration ...

![ethos_flex868m](https://user-images.githubusercontent.com/31627548/215866291-72fa4f27-cd78-4e0e-81a8-4c9068567d07.jpg)

... the FLEX868M option is not further below 900M?

**Comment by enzo-molinari** [comment]
Hi

No, because with 868MHz or 915MHz you also determine whether you are transmitting EU-LBT or FCC with 2.4 GHz.

Greetings Enzo

**Comment by bsongis-frsky** [comment]
But it seems it goes against the certificate rules!
