### ISSUE TITLE
Loss of telemetry (!??)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2383]
Apologies, but this makes no sense to me and I'm strugging to find a common factor but could it be ethos?
All tests using ACCST D16 channels 1-8 with telemetry On
The following is as best I recall.

I was at 1.4.5 on X20S working on my template but noticed when I used this template in a model with an RX6R that I had no telemetry (RSSI, RxBatt, vario, VFLVSS, GPS) although otherwise the rx controlled the model.
Rebinding made no difference.
I upgraded to 1.4.6 just in case but this made no difference.
I assumed the rx must be bad, so I swapped it out and put a different RX6R in and bound it. 
I had telemetry. I navigated to the telemetry screen to check and could see useful figures for both RSSI and RxBatt only to watch one disappear quickly followed by the other! I rebound but still no difference or telemetry.
I took the original RX6R and bound it to an X10 (ACCST) running opentx. I had both RSSI and RxBatt telemetry! This suggests the RX is not the problem?
I bound an S8R to the X20S and had telemetry which seems to still be fine after a while, so hopefully there is nothing electrically wrong with the X20S.
I created a new minimal model but the telemetry was the same, i.e. no telemetry with RX6R but works with S8R, so I don't think the template can be a problem. When I add the Vario and GPS sensor to the Rx these are not picked up with S8R with Discover On.)
Using the RX6R I deleted the sensors and turned on Discover. The tx found RSSI and RX however there are no values for either of them.
Using the S8R I deleted the sensors and turned on Discover, The tx found RSSI (100db), RX (0) and RxBatt (6.52v). I added Vario and GPS to the rx but these could not be discovered.
I note that RSSI and RX are discovered even without the RX connected.

**Comment by bsongis-frsky** [comment]
Very strange.
Does your RX have the latest firmware?

**Comment by strgaltdel** [comment]
- "The tx found RSSI (100db)"
- " only to watch one disappear quickly followed by the other! "
Could this be a swamping problem?

Did you try the units farther apart ?

**Comment by Jedsters** [comment]
> * "The tx found RSSI (100db)"
> 
>     * " only to watch one disappear quickly followed by the other! "
>       Could this be a swamping problem?
> 
> 
> Did you try the units farther apart ?

Yes. I have just tried further apart (maybe 7m plus a brick wall) S8R was showing around 85db and RX6R still shows nothing.

**Comment by Jedsters** [comment]
FWIW I've just tried an R10 Pro and that works perfectly, bound, picked up a handful of sensors, when I added vario, GPS and FLVSS it picked those up too and gave meaningful values (aside the GPS, but that takes a while and I was indoors so it would always struggle anyway).
Hopefully that gives the tx hardware a clean bill of health?

**Comment by Jedsters** [comment]
The obvious next question is what happens when you flash ACCESS 2.1.7 onto the above RX6R?
The answer is it works perfectly! It detected the 3 built in sensors and then when I connected vario, GPS and FLVSS it detected them too (although as above, no GPS signal indoors and no FLVSS voltge as it wasn't connected to a battery balance port.

This seems to me to suggest there is no problem with the Tx or Rx hardware and seems to suggest some form of incompatibility or similar between ACCST Rx and Ethos (on X20S). 

(The above isn't exactly an acceptable work-around, as I still have problems with SxR Rx.

I'm sure this used to work as I've successfully setup LSW and Special Functions for various alerts and playing vario etc.. in my template, but that was most likely using a lower version of ethos.

Thanks

**Comment by strgaltdel** [comment]
And what happens in case you flash the actual ACCST 2.1.7 on your Rx?

I do have one Rx4R, very similar, and never had any issues 
(at first running ACCST 2.1.7 LBT and now UNI Fw)
Pretty sure your problems have nothing to do with Ethos.

I had one more idea, perhaps you would have issues caused by broken antennas, or the RF section of the Rx's got damaged due to EMP
(i think telemetry is send via one/everytime the same antenna)

But your last post would largely dispose this

**Comment by Jedsters** [comment]
2.1.1 is the last version of ACCST available (that I'm aware of). I believe I was already on that (if not then 2.1.0).

I can understand why you are suggesting hardware on the ACCST side of things, it is something I've been considering myself, but if it was hardware why can I bind an S8R ACCST D16 and get the 3 internal sensors (RxBatt, Rx and RSSI) with valid values but am not able to discover extra sensors (vario, GPS).   Also getting 85db at 7m and through a brick wall suggests that signal is fairly normal so would eliminate antennae etc.? 

None of this makes any sense, probably as I don't have enough understanding to know what is happening where.

**Comment by strgaltdel** [comment]
All i can say is
I'm running several X8R, Rx8R & one Rx4R with the latest ACCST LBT Firmware with Ethos without Problems
(mostly using oXs GPS/Vario)
There is a big community which is using their ACCST stuff too, so i tend to rule out a systematic Ethos issue.

are you running LBT or FCC ?
did you try to reflash the accst Rx Firmware ?

**Comment by Jedsters** [comment]
I'm running LBT. What version of Ethos are you using?
Yes, I reflashed the RX6R to ACCST V2.1.1 but still the same.

**Comment by strgaltdel** [comment]
At this moment i'm running Ethos 1.4.6 /LBT on both Systems, X12s & X18se (without issues on X8R)
Last time i used the R4R with FrSky's FW (even without problems) is app. 9month ago,
then i "switched" the unit to UNI FW

btw
most of my Rx's are running access
maybe this issue should be discussed on RCG or Engelmt, with a broader range of accst users.

**Comment by mawzthefinn** [comment]
What you are running into with the S8R and external sensors is a known issue with the S8R. 

The RX6R issue is pretty clearly a receiver-level issue (bad receiver or some sort of bug in the ACCST v2 firmware for the RX6R)

I would reach out to your local service center for the RX6R.

**Comment by Jedsters** [comment]
@mawzthefinn do you have a link to the S8R problem please? I was only able to find one person complaining of similar on google with no discussion on it.

I don't belive the RX6R problem is a bad receiver as it works fine with my X10 and is a problem with more than one RX6R. If it is a firmware problem then to me that's just another part of FrSky, so would you be able liaise with them as I have a feeling if I try to report a problem they're just going to say it can't be a firmware problem because it works fine on my X10. As above, the problem appears to be an incompatibility between the old rx firmware and the new ethos for both the RX6R and S8R.

I tried another test with an X6R. I am able to discover RSSI, RX, RxBatt, LiPo, Altitude, VSpeed, GPS Clock, GPS, GPS Speed, GPS Alt however, I only get data for RSSI, RX (0), RxBatt, LiPo, Altitude, VSpeed. I am not getting any data from the GPS (none of the circles on the left are flashing either).

If I then use the sensors I discovered with the X6R but on the S8R, I get RSSI, Rx and RxBatt data, but I do not get data from the other external sensors even though they are there. 

So, there could be a problem with numerous Rx, there could be a problem with multiple rx firmwares, or there could be a problem with just ethos. To me this just says all my hardware is fine, the problem is bewteen FrSky Rx ACCST firmware and Ethos in the telemetry. I'm not sure how anything else would explain why I'm getting different bits of telemetry with different Rx. 
I'm not sure there could be a problem with my X20 given that it works to differing degrees with different rx - if it didn't work in the same way with all ACCST rx I'd believe that. 

At a push I could live with the RX6R not working by upgrading it to Access, but I have a number of S8R and numerous X6R which don't work properly with ethos.  I can't afford to spend over £1000 replacing all of those. 

Please can you see if you can replicate and investigate incompatibilities between ethos and ACCST telemetry, with assistance from those who maintain the rx firmware if needed.

Thanks

**Comment by mawzthefinn** [comment]
There was some discussion about the S8R and external sensors on the long running S6R thread on RC Groups. 

I personally no longer fly ACCST except for one Whoop, so I'm not in a position to test external sensors there. I abandoned ACCST for ACCESS ages ago to get away from the firmware challenges resulting from the multiple D16 variations.

**Comment by Jedsters** [comment]
I know what you mean, FrSky's constant fiddling with protocols makes me wish I'd bought another make. I don't believe it should be incumbant on those who bought into FrSky years ago to contantly replace all their rx just becuase FrSky keep changing the goal posts. 
I guess the other option is to sell the X20S and just stick with the X10 for as long as possible and avoid FrSky when it eventually stops working, but ideally, the telemetry problems can be fixed.
Thanks

**Comment by mawzthefinn** [comment]
To be frank, ACCESS pretty much solved all the issues in that regard. D16 was hit by some regulatory issues (forcing LBT to exist) as well as a edge case bug in the error correction (USM bug) and forced the release of V2.

ACCESS had some early teething challenges, but has been pretty much a stable target since then and has several features designed specifically to address the challenges users had with D16, namely firmware version reporting, universal receiver firmware (FCC/LBT auto-detection), OTA updates and receiver Options menu (no jumpers required). 

FrSky does support every receiver they have introduced since 2013 on current radios with one exception, the XMR can only do ACCST D16 v1 due to hardware limitations.

If we can nail down what's causing the issues on the X6R's telemetry, that should be fixable. I simply don't have any X6R's left to test with anymore.

**Comment by Jedsters** [comment]
Thanks. Yes, the only reason I bought the X20S was because it supported ACCST D16 so I could continue to use all my existing rx. If it hadn't I wouldn't have bought it, a £400 tx I could afford, over £1400 for new tx plus dozens of new rx was a no go. 
I don't suppose you live in the UK do you?

**Comment by mawzthefinn** [comment]
I’m in Canada :-)

**Comment by Jedsters** [comment]
ok, that idea isn't going to work. Which rx do you have in the whoop?

**Comment by mawzthefinn** [comment]
It’s a classic Whoop with one of those on-board SPI receivers, that’s the only reason I run it on ACCST, it’s not got a separate receiver or I’d have put an M+ or RS on it.

**Comment by Jedsters** [comment]
I posted a qn on RCG and notice that someone has reported 'the same issue with my x20s and a sr8 pro on access - only way i can get it to work, is go into rf settings, select the receiverand select "set" then options ( i think from memory) then the telemetry "wakes up" and reports as normal ( rpm, temp, etc from a gas suite sensor hub) i have to do this evertime i power the receiver / radio on.......bit of a pain, but might work for you? '   
Of course there is no equivlent in ACCST, but this does suggests that telelemtry isn't even reliable within ACCESS. Even if I could afford to, it appears that upgading all my rx to ACCESS wouldn't help totally.

Does another dev have rx which they could test the problems with XnR, SnR and RXnR running ACCST with?

**Comment by Jedsters** [comment]
I suddenly had a thought. It occurred to me that in my first post I mentioned I was missing telemetry, and yet I'd managed to create a template which included FLVSS, Vario and GPS. I later commented that an RX6R worked but only if I used ACCESS mode. But that was the first time I'd ever used ACCESS. So how had I created my template with discovered telemetry? 
I smell a rat!!
Clearly at some point in the past I have had most likely an X6R with working telemetry (inc FLVSS, Vario and GPS).

If you want you can close this and I'll open a new issue (I'll cross reference this), detailing which version of Ethos, X6R telemetry worked with and which version it stopped working with. Hopefully that will help you determine where the bug is in Ethos.
Thanks
