### ISSUE TITLE
Set FSW to be correct on model selection

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2384]
On the X20 etc. the FSW buttons feel like momentary buttons and not like 2 position buttons. I believe this is confirmed by being able to have different FSW settings on different models at load - it seems to recall what was last used rather than the any button position.

If this is the case then surely it should be possible to have an option in the checklist to automatically set the FSW to be correct on model selection since there is no physically correct button position.

I would suggest that the user is given the choice of whether 'set to be correct' or 'reload last used FSW' positions is applied at model load - I guess some may want to be warned of something without it actually needing to be changed.

Thanks

**Comment by Jedsters** [comment]
Still believe this is valid.

**Comment by Jedsters** [comment]
Rather than me keep bumping this, would it be possible to either accept it for action at some point or rejecting it? I still think that so long as it should be possible to setup the FSW to be 'correct' for each model when it is selected then there is no reason not to either do so or at least give us the option of it being done.
Thanks

**Comment by Jedsters** [comment]
Bump

**Comment by Jedsters** [comment]
Bump

**Comment by bsongis-frsky** [comment]
Duplicate of #4161 which is fixed in current 1.5.10 nightlies!
