### ISSUE TITLE
lua: lcd.getWindowSize() returns data from wrong widget (in very special cases)

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2388]
This "bug" was found per chance (caused by my own failure):
(Sim X20 1.4.6)

Typically I read the widget size in the first "loops" of the display handler.
If the display is active, lcd.getWindowSize() returns the frame size and I can "adopt" the placement of some objects depending on the Tx type.

Otherwise, I am used to force the display to be refreshed by the wakeup handler to get "real-time" updates of the display.

This time:
- erratically, I tried to use a "paint(widget)" call in wakeup instead of lcd.invalidate()
- my widget was placed on a second page, so that this page is not active when Tx is booted
- result: the widget's output was placed on a slightly smaller area than the widget would run on the first page, because the widget had determined its size as if a title was displayed (which was not configured)

It turned out that the cause was a widget on the first page (Gauge) that had "title" set.
Due to the fact that I called paint(widget) in a script that was placed on a non-active page, its paint handler was executed and tried to determine (and was able to!) the size of the widget, even though it was running in the "background"

Strangely, the (last) widget on the active page (page configured with two widget frames) returned its size.
This behavior changes as soon as you configure a non-lua widget in those frame on the first page.

Honestly, I don't know if it's a real bug, since I've realized (by now) that a paint(widget) call is a NoGo,
but maybe this problem shows that there are possible, unintended, side effects between different widgets....

**Comment by bsongis-frsky** [comment]
In 1.4.7 `lcd.getWindowSize()` will be available in all Lua functions for your widget, not only in `paint`.
