### ISSUE TITLE
Use internal flash for setting and model storage

### ISSUE THREAD

**Issue by janekx** [FrSkyRC/ETHOS-Feedback-Community#239]
SD is not secure memory to store radio setting and models. 
During years i have seen many issues with SD cards, customers lost models and must set new ones. Even we use good brands like Adata, Kingston, cards dies. Usualy after 2y cards die and make troubles. 
SD cards are not safe memory, cards die self or can be demaged by handling. As well SD cards are slot memory, bad contact, oxidation all happend and make memory troubles

**Comment by bsongis-frsky** [comment]
Actually there is a very big probability to buy a fake SD if you buy brands like Kingston, Samsung, Sandisk ...
All bad SD that I have seen where just fake SD cards.

**Comment by bsongis-frsky** [comment]
H2testw is the right tool to detect a bad SD
It should report 0 error

**Comment by janekx** [comment]
I not but SD cards in China, i buy from local computer warehouse what is official distributor of that brands. 
SD cards die, if are brand later if fake earlier but die.

**Comment by centertrim** [comment]
Adata and Kingston are not quality SD cards.  They are consumer SD cards.  Industrial MLC SD cards sourced through a reputable supplier (like Mouser, Digikey, etc) are a better long-term choice for this task.

https://mou.sr/3ojkULa

**Comment by janekx** [comment]
Anyway SD cards are not good for storing models and settings. 
Today email from custopmer X10 2018 sold weith opentx, lost models from SD card. 
do we risk it will harm ETHOS as well in future or will change it?

**Comment by loetefix** [comment]
Where is the problem to make a backup? In 6 years opentx i never had a problem the sd card.

**Comment by mawzthefinn** [comment]
With Backups now implemented in ETHOS Suite and newer TANDEM radios coming with onboard storage in addition to the SD card slot, I believe this issue has adequately been addressed

**Comment by mawzthefinn** [comment]
Closing this off as the newer radio designs address this with larger internal storage.
