### ISSUE TITLE
Limits in line diagram not saved if telemetry is set as source

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2391]
Changing the limits in a line diagram is not possible as they are not saved. 

https://youtube.com/shorts/_CIWVTJm-kE?feature=share

Ethos 1.4.5
TWIN Lite S

**Comment by strgaltdel** [comment]
inho, the headline is somewhat misleading.

in general i dont have any issues to save the limits,
only in case i do configure telemetry values as source,
they are not saved
