### ISSUE TITLE
Black screen if powerbutton is released too early

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2392]
The boot is sometimes cancelled if the powerbutton is released too early. It would be nice if the boot will finish and is not cancelled. Alternatively the monitor not show anything that you know the powerbutton must still be pressed.

https://youtube.com/shorts/JXQuipFVSp0?feature=share

Ethos 1.4.5
TWIN Lite S

**Comment by mawzthefinn** [comment]
This is deliberate to prevent accidental power-ons.

**Comment by NilsRo** [comment]
Hi. Please check the video. You describe the behavior I would expect but that is not the case. It seems that the timer between both are count differently...

**Comment by mawzthefinn** [comment]
I'm describing the behaviour I see on my X-Lite on 1.4.6

**Comment by NilsRo** [comment]
Ok, not the old X-Lite. ;-) 

I updated to 1.4.6 and it is much better. But in lesser situations I have a black screen now with active backlight and also active transmitter (welcome message and lighted powerbutton).

![IMG_1478](https://user-images.githubusercontent.com/51311453/216829092-b6b84249-c8e8-4259-af7e-d11c708ec28e.JPG)

**Comment by mawzthefinn** [comment]
I was able to duplicate for the first time yesterday, boot but no display. 1.4.7 FCC 

Cannot reliably generate it though.

**Comment by kakashi2018** [comment]
some thing similar is happening in x20 lineup as well. I have the x20HD and when power button early it either goes in to white screen(hapens most of the time when a slower memory card is used) or into emergency mode, this is happening even I'm using a good memory card now

**Comment by lthole** [comment]
I have also seen it on X20. It refused to boot until I held the power button for much longer than normal.

**Comment by bsongis-frsky** [comment]
I could not reproduce it on Twin XLite. But I succeeded on X20S and X20PRO and on both radios the problem is fixed.

**Comment by bsongis-frsky** [comment]
Obviously my fix is not good at all for the Twin X Lite and X18

**Comment by bsongis-frsky** [comment]
I really cannot reproduce it on 1.4.11 / Twin XLite

**Comment by kakashi2018** [comment]
Can you please post your sd card so we can use the same?

**Comment by NilsRo** [comment]
> Obviously my fix is not good at all for the Twin X Lite and X18

How do you come to this conclusion if you cannot reproduce it? Can try it also if my Twin X Lite is back from service.

**Comment by kakashi2018** [comment]
I’m able to reproduce this on x20 radio. Trick is you need to release the button between when the lcd starts lighting up and the frsky logo appear

**Comment by mawzthefinn** [comment]
> > Obviously my fix is not good at all for the Twin X Lite and X18
> 
> How do you come to this conclusion if you cannot reproduce it? Can try it also if my Twin X Lite is back from service.

The fix in question made the issue occur 100% of the time.

**Comment by NilsRo** [comment]
Cannot reproduce it with my Twin Lite S and 1.4.11. Small unbranded 2Gb SD card inserted. The radio is booting faster than before...

**Comment by kakashi2018** [comment]
Yes. Even on x20hd with new 1.4.11 I’m not seeing this issue now.
