### ISSUE TITLE
special mixers for functional modelers

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#2393]
One request: 
Do not forget the functional modelers
for excavators, trucks, cranes, dozers, wheel loaders, Pistenbully etc.

They all need some special but ready mixers
for hydraulics, cylinders, cruise control, speed control, etc.
without the need for additional log switches and further mixers. 
This is a big new market for the XE.

And don't forget the touchscrenn with function switches.

and multiswitch functions

**Comment by bsongis-frsky** [comment]
Too many requests in one issue, without any precise information
