### ISSUE TITLE
Translation files split from firmware

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#2394]
It will allow us to release the firmware without needing the translations, they will be released later, one by one once ready!

**Comment by bsongis-frsky** [comment]
For those who want to test the nightlies, just create an i18n directory in your flash and put the i18n files there

**Comment by mgsanna** [comment]
And for us translator how can we generate new (future) i18n files? should we use always the simulator? or use some particular program?
I saw that is a "normal" text file with some special characters
Please let us know...
