### ISSUE TITLE
lua: make TRIM_POSITIONS  & FUNCTION_SWITCHES accessible via category

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2396]
Within lua we have the possibility to query switch values and positions via the corresponding categories "CATEGORY_SWITCH" as well as "CATEGORY_SWITCH_POSITION" as a source value.

Unfortunately there is no equivalent to retrieve the position of trim and function switches.
There is only a detour by using logical switches.

In Ethos there are corresponding categories.

![trimPros](https://user-images.githubusercontent.com/20392683/216935752-29fb35c5-1bec-4152-99bd-b8777f4e7430.png)

![Fsw](https://user-images.githubusercontent.com/20392683/216935767-807877ee-88ac-45ca-95da-5113a1240b19.png)

It would be nice to get them accessible within LUA.
(like "CATEGORY_TRIM_POSITIONS", "CATEGORY_FSW")

thanks & regards

**Comment by bsongis-frsky** [comment]
CATEGORY_TRIM_POSITION and CATEGORY_FUNCTION_SWITCH added

**Comment by gmilleok0612** [comment]
What are the member names? I'm trying to access trim values but can't get anywhere trying to use them as a source value.

**Comment by bsongis** [comment]
Just give an index

**Comment by gmilleok0612** [comment]
I've tried every way I can think of to do that without success-if there is any way you could give me a quick example how to grab the value of trim position I would be very grateful. I could then take it from there.
