### ISSUE TITLE
TWIN X-Lite no Variotone wirh ext. ELRS

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2398]
TWIN X-Lite Ethos 1.4.6 with ext. ELRS-Module and Matek receiver, VSpeed is transmitted correctly, displays sink and rise and VSpeed setup can be edited in telemetry setup. Switch to activate vario tone can be defined. But no vario tone is generated.

With a X20 Ethos 1.4.6, same module, same receiver and same setup vario tone is generated successfully.

**Comment by bsongis-frsky** [comment]
Perhaps a stupid question, but are your settings right in this screen?

![image](https://user-images.githubusercontent.com/50834778/217173004-688dce74-f438-40f1-b282-fb32e46ec4aa.png)

**Comment by glipski50** [comment]
Good morning Bertrand,It´s not a stupid question but it is my stupid mistake 😩. I thought I have double checked and compared all settings but I have not checked the vario volume in the General page. Stupid me.Sorry for the confusion.I like my new TWIN X-Lite and Ethos, keep on the excellent work.GerhardAm 07.02.2023 um 08:11 schrieb Bertrand Songis @ FrSky ***@***.***>:﻿
Perhaps a stupid question, but are your settings right in this screen?

**Comment by miggy1952** [comment]
Thanks Mawz but this is not the fix, I have another Matek ELRS that is playing the vario perfectly. Are you saying that this is an ELRS problem and NOT ETHOS related.
