### ISSUE TITLE
No cursor displaying when creating any Custom Curve.

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#24]
Radio- X10S Express
F/W- 0.0.17

There is no cursor showing to let you know where the stick position is so adjustments can be made.  All custom curves selected from the Mixer Menu are affected by this.  If you were creating a custom throttle curve then it would be beneficial for setting up a twin engine gas plane to be able to see the position of the stick in relation to the points on the curve.  This feature was added to OTX 2.3.10 and corrected in 2.3.11.  It would be nice to have it on Ethos also.

Create the Curve:
Select Mixer
Select any Mixer, “Throttle” for a throttle curve”
Select “Edit”
Select the drop down “Curve”
Select “Add Curve”

Give the curve a name
Select “Type”
Select “Custom”
Select “Points Config”
Change each point to create a slope

Work the throttle up and down. No display is shown for the control movement.

**Comment by df7320** [comment]
Hello, any chance that issue will be soon be looked at?
Thanks

**Comment by andreavi90** [comment]
Any news?

**Comment by df7320** [comment]
No, unfortunately the one feature I really need seems to be of low priority.  Every other radio system I have used has this feature, Futaba and Spectrum. It's even a feature in the latest Opentx.  April 1st will be a whole year.Sent from my Galaxy
-------- Original message --------From: andreavi90 ***@***.***> Date: 3/22/22  6:45 PM  (GMT-05:00) To: FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc: df7320 ***@***.***>, Author ***@***.***> Subject: Re: [FrSkyRC/ETHOS-Feedback-Community] No cursor displaying when
  creating any Custom Curve. (#24) 
Any news?

**Comment by bsongis-frsky** [comment]
It is not possible to know which is the source for Curve Point X position. But there are some special cases where it is possible to know (when the curve is only used one time in the model).

**Comment by robertobrazill** [comment]
It's a shame that this topic seems to have no relevance to FRSKY. Those of us who have giant planes, who need to perform servo balance, it would be essential for the graph to have this functionality. All radios on the market have it, only FRSKY does not. Frustrating.

**Comment by bsongis-frsky** [comment]
It HAS relevance, we just have a lot of requests, and everybody thinks that his issue is the most important, that it's a shame if not implemented on due time etc.

**Comment by robertobrazill** [comment]
> It HAS relevance, we just have a lot of requests, and everybody thinks that his issue is the most important, that it's a shame if not implemented on due time etc.

I am deeply grateful for your return. In fact, it is essential that the graph can be checked when we are doing servo balancing, or even setting a simple curve.

TKS

**Comment by mortehoe** [comment]
Will this request be implemented as it has been  active since 2021 and would be really useful when adjusting points on a curve.

**Comment by jasalca** [comment]
The truth is that this idea has been tried for several years now, and yet other much less important and much more recent ideas have already been carried out.

**Comment by jasalca** [comment]
And the funny thing is that on other screens where you don't see the points of the curve, you do see the position of the stick, so it shouldn't be very complicated to do it.

**Comment by robertobrazill** [comment]
> E o engraçado é que em outras telas onde você não vê os pontos da curva, você vê a posição do stick, então não deve ser muito complicado fazer isso.

Sim, é algo que está quase pronto, como vocês mesmo disse, em outras telas onde você não vê os pontos da curva, você vê a posição do stick, então não deve ser muito complicado fazer isso.

Por favor TIME FRSKY, olhem com carinho para esta solicitação.

**Comment by mortehoe** [comment]
April 2021 issue opened and still would like a resolution

**Comment by robertobrazill** [comment]
It seems that the developers don't care about this important functionality.

**Comment by jasalca** [comment]
I think it's the only radio brand on the market that doesn't have this feature. I still don't understand how it can be so complicated to do this function, when the other radios on the market with less software complications do this.

**Comment by robertobrazill** [comment]
I'm migrating to the Jetti, I'm tired of waiting for a function that any radio from 10 years ago already has, and FRSKY made a big mistake on this one.

**Comment by robertobrazill** [comment]
How do you reactivate this demand?

**Comment by RealTadango** [comment]
I always wondered why there was no cursor... If you edit it from the mixer screen this would be possible and really help :)

**Comment by robertobrazill** [comment]
@bsongis-frsky @Nicholas-Luoyi I would like to thank you for your kindness in including the activation of this important feature as a real project. As an example, you could look at how it is done in Jetti, which I consider the best Balance Servo feature of all time.

**Comment by bsongis-frsky** [comment]
The balance servo feature is in progress right now. FrSky X20 has a 800x480 display which should make it far better than what you have in mind.

**Comment by robertobrazill** [comment]
incredible @bsongis-frsky

**Comment by robertobrazill** [comment]
Some friends are commenting that this feature exists in the 20pro, can you confirm? @bsongis-frsky

**Comment by jasalca** [comment]
I have a radio x20 pro AW and I can assure you that it does not have this function.

**Comment by bsongis-frsky** [comment]
No this feature doesn't exist yet. But I can assure you that it will exist soon :)

**Comment by bsongis-frsky** [comment]
#2790 is the issue for the servo balance feature

**Comment by bsongis-frsky** [comment]
Working on this chapter. Now the curves points have a far better precision (1 digit on Y, 1 digit on offset). We have a virtual keyboard on radios which have a touch screen, and the cursor is displayed to show the current position on the curve.

Now we also need 2 functions, which are not related to the servo balance function: 

1) Automatically select point which is near the current position

2) Lock the point X (so that the user can release the stick and adjust the position with more precision)

![image](https://github.com/user-attachments/assets/00aa3a07-5a61-4555-8ba5-230bd144ea3b)

Here a first UI proposal, still not working. But I am still not sure about the way to reach those buttons, especially on radios which don't have a touch screen. Any idea is welcome!

**Comment by jasalca** [comment]
I think that an idea could be with the page button, a short press goes from "auto " to "Lock" and vice versa ,when what you are interested in is selected a long press with that same button
![IMG_4671](https://github.com/user-attachments/assets/bb3f6d12-25fa-4fd0-8ffe-d8fcf6d8b231)

**Comment by robertobrazill** [comment]
A opção do @jasalca é um bom caminho, mas óbivio, a tela sensível ao toque ajuda muito. @bsongis-frsky

**Comment by bsongis-frsky** [comment]
> I think that an idea could be with the page button, a short press goes from "auto " to "Lock" and vice versa ,when what you are interested in is selected a long press with that same button ![IMG_4671](https://private-user-images.githubusercontent.com/87758703/362723050-bb3f6d12-25fa-4fd0-8ffe-d8fcf6d8b231.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDI2MzQsIm5iZiI6MTcyNTAwMjMzNCwicGF0aCI6Ii84Nzc1ODcwMy8zNjI3MjMwNTAtYmIzZjZkMTItMjVmYS00ZmQwLThmZmUtZDhmY2Y2ZDhiMjMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA3MTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNmMwY2NhNzY2NDEwMTRmNjkzZjM1NjI4NjVjODdiZWY2ZGFiYzUyYTE2ZmE2OWZmODAxOWE5MjRmZGMwNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUHZJxlRbrSlu303rX3JsyYdVLQJeSHPoT74JiI28qY)

Good idea, I think we want to "Lock" / unlock very easily. And enable / disable "Auto" very easily too!

**Comment by bsongis-frsky** [comment]
But wait, they are 2 different concepts, we need 2 keys!

**Comment by jasalca** [comment]
No need , all the same key, a short press changes between “auto”and “lock”, and a  long press in the same key selects the action.

**Comment by andreavi90** [comment]
It can be activated by default the AUTO function, press the PAGE button for enter into the LOCK function. With another pressing of PAGE button, you return in AUTO.

Can it work?

**Comment by bsongis-frsky** [comment]
No. In the current concept "Auto" will set the focus on one point Y, the one which is nearest the current position. If you want to edit manually another point, or the other curves settings, then you need to disable Auto ...

Unless I consider that the Curve is a "Form field" which can take the focus too ... it is still not clear in my head!

**Comment by jasalca** [comment]
Maybe I'm not understanding you, because if you have selected “Auto” with short press  and enabled “Auto” with long press , if you want to disable it then you do another long press.(“page button”)

**Comment by jasalca** [comment]
I got it, you were replying to Andreavi90. Excuse me

**Comment by WhiskeyGolf** [comment]
Wouldn't it be a good idea to create a new point in the curve that is at the cursor when you press the enter key. Then you can simply call it up and edit it

**Comment by bsongis-frsky** [comment]
Available in latest 1.5.16 nightlies
