### ISSUE TITLE
Display of min/max telemetry values (actual flight) on the main screens

### ISSUE THREAD

**Issue by Testname84** [FrSkyRC/ETHOS-Feedback-Community#240]
I'm hardly missing the possibility to display the min/max altitude or velocity for example of the actual flight on the main screens.

**Comment by Testname84** [comment]
Using Ethos 1.0.6 on X12S

**Comment by MIKE-DAILEY** [comment]
Duplicate of #236

**Comment by Testname84** [comment]
Why did you close this issue? I tried like explained in the #236 and it doesn't work. please check again.

**Comment by MIKE-DAILEY** [comment]
Working for me X12S ISRM.

**Comment by Testname84** [comment]
It doesn’t work for me. What am I doing wrong? In screen setup I try long press, in telemetry value I try long press nothing happens...

**Comment by Testname84** [comment]
> Working for me X12S ISRM. After you add telemetry item to cell, Press to edit and then long press on item for popup.

Long press doesn't work. When I release after multiple seconds I enter the sensor edit screen. There you can set the min/max value which the sensor recognizes but not the min/max (altitude) of the actual flight session.

**Comment by Testname84** [comment]
I found the problem. It is nessecary to have the model powered on to do this.

**Comment by MIKE-DAILEY** [comment]
Only to discover the sensors.

**Comment by Testname84** [comment]
A hint displayed in the menu would be great.
