### ISSUE TITLE
1.5.0 nightly: Unexpected GVAR behaviour with 'Add' and 'Subtract' actions 

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2401]
Just checking out the GVAR implementation. 

So far, I've tested three scenarios for 'add' and 'subtract' actions, all result in undesirable behaviour.

1. **'Add' action triggered by SI↓**. The increment is triggered continuously while SI is pressed. It would be better if acted like a trim, that is: trigger once, then repeat at intervals.
2. **'Add' action triggered by SI↓ with rising edge modifier**. This does not work at all - pressing SI has no effect on the output channel.
3. **'Add' action triggered by logical switch _LSW = RisingEdge (SI), duration = 0.2 seconds_**. This works, but is triggered multiple times as in (1) above, resulting in a much larger increment than intended. Presumably this is because it triggers continuously for the 0.2 sec duration.

**Comment by RC-SOAR** [comment]
[As an aside, the 'Repurpose' action works really nicely! I've tested it by repurposing the elevator trim to act as a mix adjuster.]

**Comment by bsongis-frsky** [comment]
Thanks for this test!
The bug is in 2. and it will be fixed in the next nightlies!

**Comment by RC-SOAR** [comment]
Ah great, thanks!
