### ISSUE TITLE
CRSF: GPS Heading, Speed, Alt, Sats malfunction

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2403]
Hello.
On Tandem X20, Ethos 1.4.6, CRSF(Elrs), next sensor is malfunction:
- GPS Speed - has limit 0.0 - 20.0 km/h, decimals 10. Correct value = uint16_t / 100 = 0-655.35 km/h, decimals 100.
- GPS Heading - has limits 0.000 - 0.360 deg, decimals 1000. Correct value = uint16_t / 100 = 0.00 - 359.99 (655.35), decimals 100.
- GPS Altitude - has limits -100 - 1000m, decimals 0. Correct value = uint16_t - 1000m = -1000 - 64535m, decimals 0.
- GPS Sats - has limits 0-360, decimals 0, Correct value = uint8_t = 0-255, decimals 0

**Comment by bsongis-frsky** [comment]
Ethos has 2 kind of limits:
- sensor limits
- user modifiable limits

It seems you have mixed those 2 kind of limits in your request, here are my remarks:
- GPS Speed: range agreed, but both OpenTX and EdgeTX have only 1 decimal (protocol).
- GPS Heading: range agreed, but both OpenTX and EdgeTX have 3 decimals (protocol), which is very strange (2 bytes are not enough)
- GPS Altitude: this is a user limit, you may change it.
- GPS Sats: agreed

**Comment by r1000ru** [comment]
@bsongis-frsky 

1. UBLOX protocol [return struct](http://docs.ros.org/en/noetic/api/ublox_msgs/html/msg/NavVELNED.html), then ground_speed in sm/s and heading value scale to  deg/1e-5. 
For sample take speed 12m/s and course 90 degrees. In ublox struct it will be 12*100 = 1200 (sm/h) and 90/1e-5 = 90/ 0.00001 = 90 * 100 000 = 9 000 000
2. When parsing , INAV makes [transformations](https://github.com/iNavFlight/inav/blob/9c32094f5ec469bcb387a7c0cd7559fde9eda1d3/src/main/io/gps_ublox.c#L629):
```
gpsSol.groundSpeed = _buffer.velned.speed_2d;    // cm/s
gpsSol.groundCourse = (uint16_t) (_buffer.velned.heading_2d / 10000);     // Heading 2D deg * 100000 rescaled to deg * 10
```
3. Then INAV [make CRSF GPS](https://github.com/iNavFlight/inav/blob/9c32094f5ec469bcb387a7c0cd7559fde9eda1d3/src/main/telemetry/crsf.c#L200) frame use next scales:
 - speed cm/m to km/h * 10 = speed(sm/h) * 3600(s in h) / 100000 (sm in km) * 10 = speed * 36 / 100;
 -  heading deg * 10 to deg * 100 = heading * 10;
```
#define DECIDEGREES_TO_CENTIDEGREES(angle) ((angle) * 10)
crsfSerialize16(dst, (gpsSol.groundSpeed * 36 + 50) / 100); // gpsSol.groundSpeed is in cm/s
crsfSerialize16(dst, DECIDEGREES_TO_CENTIDEGREES(gpsSol.groundCourse)); // gpsSol.groundCourse is 0.1 degrees, need 0.01 deg
```
These transformations correspond to a document that TBS forbids publishing, called **crsf rev07.pdf**
![crsf_gps](https://user-images.githubusercontent.com/1244228/218064563-d5317646-998b-42ca-8305-ab1c5674ec2a.png)

**Comment by bsongis-frsky** [comment]
Thanks for the reference to the documentation.

Changes made for 1.4.7:
1) GPS Speed: 2 decimals, max = 650.00km/h
2) GPS Heading: 2 decimals, max = 360.00°
3) GPS Alt: max = 65000m
4) GPS Sats: max = 255 sattellites
