### ISSUE TITLE
Zero byte after CRSF frame

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2404]
Hello.
Tandem X20, Ethos 1.4.6 after every CRSF frame transmit byte 0x00
![tandem_x20-ethos_1 4 6_crsf](https://user-images.githubusercontent.com/1244228/218027953-21aa9914-9c71-4592-9be6-f93df2e10b67.png)
Attached ZIP file has data from logic analyser DSView
[tandem_x20-ethos_1.4.6-crsf_from_tx.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10704681/tandem_x20-ethos_1.4.6-crsf_from_tx.zip)

**Comment by bsongis-frsky** [comment]
The signal just returns high, no?

**Comment by mawzthefinn** [comment]
That logic analyzer seems to be misdirecting a high idle as an additional 0x00 byte, based on the screenshot shown.

**Comment by mawzthefinn** [comment]
Closing off, based on data provided this is a bug in the logic analyzer's frame detection.
