### ISSUE TITLE
Write logs after first throttle move

### ISSUE THREAD

**Issue by robertoalmeida** [FrSkyRC/ETHOS-Feedback-Community#2405]
I would like to know if it is possible to write logs after the first time I accelerate the model and keep recording.
Another way I thought would be a momentary switch to start and stop recording.
I know there are ways to condition the key (2,3 positions) but I don't want to use one for that.

**Comment by mawzthefinn** [comment]
Yes, you can do this.

It requires two Logic switches.


The first is a A > X with source as the throttle channel and a value for -95% or so
The second is a Sticky switch with the on condition as the the first LSW, clear the Off condition

Then use the Sticky switch as the Active Condition of the logging Special Function.

**Comment by robertoalmeida** [comment]
Perfect,. 

Thanks
