### ISSUE TITLE
twinxlite pro no update trough s port?

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#2406]
ethos lbt 1.4.6
When I try to update a receiver through s port there is no option to o this
![screenshot-2023-02-10-63228](https://user-images.githubusercontent.com/12456410/218144761-2586e134-1534-4671-b908-0d327a74f242.jpg)
ion to do this.

**Comment by mawzthefinn** [comment]
Flash External Device is the setting to flash via S.Port
