### ISSUE TITLE
twin Xlite No flashing trough sport

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#2407]
![screenshot-2023-02-10-63228](https://user-images.githubusercontent.com/12456410/218178158-2e12cb75-3b9c-40bd-8b38-1729cb3361c6.jpg)
No option to flash trough S port

version 1.4.6 eu LBT

**Comment by mawzthefinn** [comment]
This was answered in the previous one you opened. Flash External Device (the top option) will flash through S.Port

**Comment by 00steven** [comment]
oops sorry
