### ISSUE TITLE
X12S Nightly Possible.

### ISSUE THREAD

**Issue by KevinFairgrieve** [FrSkyRC/ETHOS-Feedback-Community#2409]
Not really an issue, so please delete if not appropriate.

I understand it may be a lot of work, but would it be possible to release nightly for the X12S?

I would be happy to use my "spare" X12S for bench testing but fly using my X20.

**Comment by mawzthefinn** [comment]
Right now Nightlies for the Horus radios are not practical to do.

**Comment by KevinFairgrieve** [comment]
Thank you for responding. I will close this now

I suspected that would be the case.
