### ISSUE TITLE
Emergency Mode when changing models 

### ISSUE THREAD

**Issue by Peterbilt84** [FrSkyRC/ETHOS-Feedback-Community#2410]
With firmware 1.5.0, the X20 goes into emergency mode as soon as you want to change the model or when you click into the HF system menu.

**Comment by mawzthefinn** [comment]
Which 1.5.0 build were you using?

**Comment by Peterbilt84** [comment]
The version that was uploaded 12 hours ago.

**Comment by jbesse262** [comment]
🤔

**Comment by mawzthefinn** [comment]
Thanks, now I know which build I need to test.

**Comment by mawzthefinn** [comment]
Just tested on my X20 with that build, unable to duplicate either item.

Do you have another SD card to test with? model change at least requires SD and a bad or failing SD card can cause Emergency Modes on model changes.
