### ISSUE TITLE
simulator save and restore switches

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2411]
An addition to the simulator would be very helpful. If when you exit the simulator all switch settings SA - SN would be saved and automatically reloaded in the position the next time you start the simulator. 
Thanks a lot

**Comment by jurajjurej** [comment]
Yes. Useful

**Comment by Storchy1** [comment]
still desired

**Comment by Storchy1** [comment]
still desired

**Comment by bsongis-frsky** [comment]
Added to #3440
