### ISSUE TITLE
Bitmap and Text Home widgets

### ISSUE THREAD

**Issue by EthosUser** [FrSkyRC/ETHOS-Feedback-Community#2412]
Hello,
When I want to put a '800x480' full screen image on a screen, I can't choose another image than the one of the model which is not in '800x480' resolution.

It would be possible to choose another image than the one of the model?

**Comment by mawzthefinn** [comment]
It is possible, but would require a custom Lua to do so. Should be a fairly simple lua for somebody to write.

**Comment by EthosUser** [comment]
Thank you,
but wouldn't it be possible to choose in the menu another image than the one of the model, an image that would be natively in 800x480 and that we would have downloaded on the SD card?

**Comment by mawzthefinn** [comment]
Any image can be chosen today, provided it's 800x480 or smaller and in the right folder (/bitmaps/models), but the built-in widget only displays the one selected in Edit Model as the model image.

A Lua script would allow what you want.

**Comment by bsongis-frsky** [comment]
We think about adding 2 new widgets in 1.5.0:
1) A widget which displays a bitmap which can be chosen by the user
2) A widget which displays Markdown

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/233196523-cf647684-7fb0-421d-a4e6-436d65d3bf7b.png)

**Comment by bsongis-frsky** [comment]
Done.
Also Markdown now supports the special chars
