### ISSUE TITLE
Simulator X20S 1.5.0

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2413]
Hello,
after installing the simulator the following files are not found:
libwinptread-1.dll, libgcc_s_seh-1.dll, libstc++-6.dll and libgcc_s_seh-1.dll

Is this due to my PC?

**Comment by Skippydi** [comment]
Bei mir der gleiche Fehler. Win 10 pro

**Comment by Wolepo** [comment]
After installing the new version I got the same error message. All 4 files are not found
Win11 Pro

**Comment by fhpage** [comment]
Same error message with Win11 pro and 3 different computers with  windows 10.

**Comment by strgaltdel** [comment]
Just for info,
not only german localized windows is affected:

![grafik](https://user-images.githubusercontent.com/20392683/220633849-97b74f0a-3ca0-447b-92f7-b60b7a9ce194.png)


regards
Udo

**Comment by strgaltdel** [comment]
.. found some similar problems by using the minGW environment:

https://stackoverflow.com/questions/18138635/mingw-exe-requires-a-few-gcc-dlls-regardless-of-the-code

**Comment by mawzthefinn** [comment]
This is fixed for the X20S simulator on Nightlies, the other ones should be up in a few hours

**Comment by strgaltdel** [comment]
i can confirm, 
X20 sim 1.5 now is running without problems !

**Comment by Wolepo** [comment]
And what is that?
Win 11 Pro
![Var1 5](https://user-images.githubusercontent.com/90325526/222465154-7bc6d558-21ae-43cc-a38c-a26e6905c027.jpg)

**Comment by strgaltdel** [comment]
var mixer was converted to the same functionality as in 1.4
... go to the second page of the model configuration, 
there is a new section "vars" with all extensions you are looking for

**Comment by dean5378** [comment]
Can someone give me a like to find a simulator.  I am a newbie and can't seem to find one for my TD20R
.  I need the one for Mac.

**Comment by dean5378** [comment]
EDIT: Can someone give me a link to find the simulator. I am a newbie and can't seem to find one for my TD20R
. I need the one for Mac.
