### ISSUE TITLE
Calculating sensor calculates incorrectly

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2416]
Task: The single-cell voltage average of a four-cell battery is to be determined.
For this purpose, I have created a calculating sensor with the source Lipo and the second source divided by the number of Lipos. With a measured voltage of 15.01V divided by 4 cells, this should result in a value of 3.7525V. However, 37.5V is displayed.
Is this an error or am I doing something wrong?

![Durchschnitt](https://user-images.githubusercontent.com/90325526/218448432-97492325-44f6-456c-ba05-3b520b1f62cd.jpg)

Translated with www.DeepL.com/Translator (free version)

**Comment by bsongis-frsky** [comment]
You have to setup 2 decimals, or divide by 10 (constant) again
