### ISSUE TITLE
Ethos Suite Pre-Release 1.4.7 for TWIN X-Lite cannot be selected

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2417]
With Ethos Suite 1.4.6 in developer mode and TWIN X-Lite connected the pre-release 1.4.7 is shown under receiver update and the release information can be displayed. But 1.4.7 it cannot be selected for update. Only the actual release 1.4.6 an previous firmware versiuon can be selected fpr update.

**Comment by Nicholas-Luoyi** [comment]
It should be OK now
