### ISSUE TITLE
TWIN X-Lite after update still shows version 1.4.6

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2418]
After issue #2417 has been resolved I could select version 1.4.7 in Ethos to update the TWIN X-Lite. Close to the end of the update process I get the message "**_Auto flashing doesn't start successfully.  Please finish it manually by following the steps_**" .

After unpluging USB, reconnecting and clicking on Finish I get the message **_successful update_** . But Ethos Suite still shows  again version " 1.4.6 outdated" in the status. Also the info menue page of the TWIN X-Lite shows 1.4.6 . Also after disconnecting USB TWIN X-Lite goes into emergency mode = still is 1.4.6

![Ethos Suite TWIN X-Lite](https://user-images.githubusercontent.com/116186946/218820532-390610b9-969c-4066-9c70-34224e188fed.jpg)

**Comment by mawzthefinn** [comment]
Please try with Suite 1.4.7

**Comment by glipski50** [comment]
Still does does work correctly. I selected **_Branch Pre-Release_** and **_Version Release 1.4.7_**

When I select **_Flash Firmware_** I still get the message to manually finish the update process and still no 1.4.7 is installed.

When I select **_Prepare All Components_** I get the error message below. Several attemts, always ends up with the error message.

![Etrhos Suite error](https://user-images.githubusercontent.com/116186946/218968069-cee9345b-e04c-4a7f-9791-4ab4e31aab59.jpg)

**Comment by mawzthefinn** [comment]
A new build of Suite was posted a couple hours after your last comment with some bug fixes.

**Comment by glipski50** [comment]
Still doesn't work. After starting the update process files are downloaded and it shows **_Writing Firmware to Flash_**. Then for less than a seconds the message is shown that the process cannot be ended, that I should disconnect and reconnect USB and that I should press finish. This message disappears automatically after less than a second so that I cannot press the Finish button. No further message are then shown like update successful or so. Firmware is still 1.4.6.

Ethos Suite than does not show the status of the internal disk with the language files as normal, see below. Just to be sure  I also did a Windows Scan and Repair of the flash but no failiures has been detected.

![Screenshot 2023-02-15 161828](https://user-images.githubusercontent.com/116186946/219070317-6d2410a7-d980-4aa0-90db-9bfe7ecb6298.jpg)

**Comment by mawzthefinn** [comment]
Thanks for the additional data, I will pass it along immediately.

**Comment by Nicholas-Luoyi** [comment]
Would you please try to flash 1.4.6 or some other version of firmware via "FLASH FIRMWARE" and tell me the result?

**Comment by glipski50** [comment]
I installed Ethos Suite 1.4.6 and I flashed firmware 1.4.5 successfully. Then I wanted to flash 1.4.6, firmware is downloaded and the the message says **_writing firmware to flash_**. After some time I get the message that autoflash doesn't start automatically, see screenshot below. After unplugging the USB cable the flash process dos NOT start, the screen of the TWIN X-Lite just shows **_Bootloader_**.

![Screenshot 2023-02-16 091202](https://user-images.githubusercontent.com/116186946/219310699-eff31261-b782-4555-af0b-16a0382bc27e.jpg)

Same with Ethos Suite 1.4.7.

**Comment by glipski50** [comment]
I copied the firmware file 1.4.6 **_firmware.bin_** to the root of the disk **_RADIO_** and started the TWIN X-Lite in bootloader mode. Flashing starts as normal and is successful. Same with 1.4.7. Copying the **_firmware.bin_** to the disk RADIO and starting bootloader mode flashing of 1.4.7 is successful. Using ETHOS Suite 1.4.7 always same errors as mentioned above.

I always flash / try to flash the EU version of the firmware.

**Comment by Nicholas-Luoyi** [comment]
Understood. Thanks for your information.

**Comment by mawzthefinn** [comment]
Is this still occurring with Suite 1.4.8?

**Comment by glipski50** [comment]
Still the same error with Ethos Suite 1.4.8. I had to flash the TWIN X-Lite manually. Just testet several times again.

**Comment by glipski50** [comment]
Any update on this issue?

**Comment by bsongis-frsky** [comment]
Do you have the latest bootloader?

**Comment by bsongis-frsky** [comment]
We cannot replicate this issue, anybody else can?

**Comment by glipski50** [comment]
Yes, I have the latest bootloader. I have tried and tested it several times again the last days on three different pc‘s and laptop, no sucess. After the failure accured, I also had to repair / format flashdrive RADIO, sine I got windows error message. This happened three times during my tests the last days.

I also have a Tandem X20. Same pc‘s / laptop and same USB-C cable, no problem , copies firmware to disk, switches to bootloader and flashes firmware successfully without any problems at all.

I will call the vendor today since if he has similar expereience.  Maybe there is a defect flash drive. I have still warrenty on the TWIN X-Lite.

**Comment by glipski50** [comment]
Had the TWIN X-Lite sent to the German distributor. He checked and could flash different firmware versions using the Ethos Suite without any problems. So the issue must be on my site. Will check after receiving the TWIN X-Lite back. 

Issue could be closed I guess.

**Comment by glipski50** [comment]
Hello, one more information. The German distributor did the flashing with Windows 10. I than did try a computer with windows 10 and the flashing with Ethos Suite did work perfect. With my three different Windows 11 computer the problem still exists and flashig does nor work. Seems to be an issue when using Windows 11.

**Comment by NilsRo** [comment]
See the same error using Windows 11 but do not have an old version available. Any updates about this @bsongis-frsky ?

Cheers,
Nils
