### ISSUE TITLE
Question: backwards compatibility with nightly releases

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2419]
I like to to test out new features in the nightlies (currently I have 1.5 nightly installed).

However, I have only one X20 transmitter, which is also used to develop my sailplane templates. 

Can I be reassured that the templates developed using the nightlies will be readable/convertable in the production firmware? Or should I revert to the most recent production firmware for template development?

**Comment by mawzthefinn** [comment]
There's no backwards compatibility with model files, only forwards. anything you build on the nightlies should work on 1.5.0 release, but not on 1.4.x or earlier. 

I would recommend reverting to 1.4.6 for any published templates until 1.5.0 hits stable release.

**Comment by RC-SOAR** [comment]
Okay, thanks. I'll revert to 1.4.6 for template development, then any 1.5 dependent features can be added later.
