### ISSUE TITLE
Trims per Flt Mode

### ISSUE THREAD

**Issue by RonRob61** [FrSkyRC/ETHOS-Feedback-Community#2421]
Im very new to ETHOS and my FrSky X18SE but for the most part comfortable with the new to me interface.  Perhaps Im missing it but it appears to me that I cant do somthing that ws super easy to do in OpenTX and I find it hard to believe its not possible.  I use a very high end AUTO PILOT.  I have my radio set up with 4 modes.  AIDED, WAYPOINT, LANDING and MANUAL.  The only Mode I need to trim is manual as manual mode on my auto pilot is a direct pass through, plane flies as if there is no autopilot installed at all so trims act normally.  In any other mode the trims are seen as inputs by the auto pilot and will casue it to react in unwanted ways.  A good exapmple of this would be airspeed.  When in AIDED, WAYPOINT OR LANDING MODES the right stick, elevator is use to increase or decrease air speed.  But in Manual mode it does the normal elevator up and down.  So If I trim down into it while in Manual mode then switch to AIDED the plane will see the trim as forward on the elevator and casue the plane to fly faster then normal.  In Open-TX it was simple to set up, In Flight Modes "NO TRIM"  The result was zero trim ans the trim buttons are actually non functional in the mode.  Then For MANUAL MODE I set up "OWN TRIM" Again this is done at the Mode setup screen.  So basically Maiden Flights I launch in Manual Mode, trim the plane and once I see that manual flight seems good I switch to AIDED and start testing the AutoPilot.  The trims dont carry into the Aided Mode so the auto pilot is getting no inputs.   Ive played with it quite a bit but it appears to me that TRIMS are more global in ETHOS.  Is there any way to make it so I can just set up trims for one FLIGHT MODE and have all the others disabled and default to ZERO TRIM?

**Comment by mawzthefinn** [comment]
Yes, but it's not obvious. Right now trims are either common (1 trim setting for all flight modes) or per-FM (one trim value per flight mode). There are workarounds though using either free mixers or the trim mixer. In your use case a trim mixer is the easiest

Disable elevator trim in the trims menu, add a trim mixer  an active condition of the flight mode you want it active, The Up is trim RVU and Down is Trim RVD (LVU and LVD for Mode 1) and the output is the elevator channel. This will function as an elevator trim that's only active on the one flight mode.

**Comment by RonRob61** [comment]
Thank You Mawz!  Ill give that a try.   
Have you noticed in Ethos Suite that when you look at the Models Tab each model has an Edit button in the bottom right corner?  Its still greyed out but im hoping thats a hint that soon we will have a Companion Like alternative for programming.

**Comment by mawzthefinn** [comment]
Yes, the ability to edit models in Suite is coming. It's still a ways away right now though.

**Comment by RonRob61** [comment]
Well thats good to hear.  I found a simpler way to actually get an exceptable solution to my particular trim issue.  Mt aircraft is actually a flying wing so the only 2 trims I needed are Aileron and Elevator.  So in the trims setting tab i turned off all of the others.  It still allows for elevator and rudder to be trimed across all of the modes but then I found that the way it copies trims is dependent on the order in which the modes are listed when you look at them on the Modes Tab.  So origionally I had default, aided, waypoint, landing, manual.  Im never in default and when I would adjust trims in Manual they would carry over to the others when I switched.  I found that reordering them......currently   default, manual, aided, waypoint, landing (so manual moved from last to FM1).  I dont understand the logic but now if I change trims in MANUAL MODE and switch to any other they are still at 0.  THe trims still work in the other modes but I know not to use them

**Comment by strgaltdel** [comment]
Just in addition,
i guess there is at least one more possibility by using the GVar additions in the upcoming 1.5
Some days ago i played with the new additions, 
and  i guess one is able to activate the "repurpose" activity under several conditions.
(At least you could define a LSW which represents the conditions you need)
This repurpose condition will deactivate the trim activity of the corresponding main function  

so you would be able to use the trim only under situations you want.
(hoping i do remember right)

**Comment by mawzthefinn** [comment]
Closing this off as the immediate need has been addressed, and the long-term fix is already open under another issue

**Comment by RonRob61** [comment]
Thanks for your help
