### ISSUE TITLE
Usage of pull request instead of Issues ....

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2423]
I'm no Github expert by any means. But currently everything is handeled in issues and there are multiple issues for GVAR for example that are more of a functional discussion. Wouldnt't it be better to do it like most projects do and work with Pull Requests? 
Could tidy up the clutter within the issues. Also it would be better possible to track changes within the releases ....

But if you are fine like it is. Go for it :-)

**Comment by mawzthefinn** [comment]
Pull Requests are for changes in code in a branch, not for tracking development tasks. That's why they are largely unused here, aside from the Lua scripts (where @Target0815 has submitted some really nice work)

**Comment by mawzthefinn** [comment]
Closing this off as the question has been answered
