### ISSUE TITLE
Radio Battery Low Warning scrolls mixer display if no mixer selected

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2424]
I was on the Mixer selection screen, I had scrolled half way down my mixers (using touch screen) although no mixer had been selected (none highlighted). 
I then received a 'radio battery low warning'. After I'd acknowledged this by touch selecting OK, the screen scrolled to the top and first mixer was then displayed and selected.

If a mixer is selected then this doesn't appear to happen(?).

I can't help wonder whether this may also affect other screens too when an item is not selected whether the first item will become selected. 

This is at least annoying and if flying when this happens could be slightly more problematic. One may e.g be trying to adjust a Crow curve when this happens.

I also notice that if you are in the process of changing a value (in my case I was editing  the value for a point on a curve, but again, I suspect this could relate to other items) then after acknowledging the radio battery low warning with OK, the item I was editing is no longer being edited - the scroll wheel obviously changes where you are on the screen rather than continuing to edit the item.

I also wonder what would happen if a LUA script was running to e.g. help change in flight values when the warning was given? 

It seems to me that after the Radio Batter Low OK screen is displayed, that once cleared by selecting OK you should be exactly where you were before the warning.

Thanks

**Comment by Jedsters** [comment]
Bump

**Comment by Jedsters** [comment]
Bump

**Comment by Jedsters** [comment]
Bump

**Comment by bsongis-frsky** [comment]
Checked today. It doesn't happen anymore in 1.5.10 nightlies
