### ISSUE TITLE
Trainer Port Input DSC (master) not activated

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2428]
Ok, at first I thought it works, but no. (see #2427 )
Ver 1.4.6 and 1.4.7
after reboot I cannot connect to the trainer port via cable. I need to set wireless mode to Trainer, then disable wireless in trainer menu and then DSC port works as expected including  voice alerts

**Comment by Fernandolewandowski** [comment]
after updating to 1.4.7 I can't use the dsc port to train in realfligt

**Comment by jasc76** [comment]
> after updating to 1.4.7 I can't use the dsc port to train in realfligt

Try what worked for me....

**Comment by kramgrand** [comment]
I discovered that I have the same problem when doing training earlier today. I am one of my clubs trainers.
I could only get it working by alternating between using the cable for one flight and bluetooth for the next and then back to cable.  Also while using bluetooth it would not auto connect.   Please can this be looked into as it is a right pain and does not install confidence.

**Comment by kramgrand** [comment]
I seem to have resolved the problem I had with it intermittently working with a cable. I am not 100% sure how though.  I changed the switch function of switch. SI from momentary to two position and went through the settings of Master / Slave on both units again.  As I said,  It seem to be ok now.
