### ISSUE TITLE
free mix.

### ISSUE THREAD

**Issue by drummaker** [FrSkyRC/ETHOS-Feedback-Community#2429]
I think the pre programmed mixes are cool, but rarely do I ever need Just what they offer... Today I spent hours playing with butterfly, and as many have pointed out. this just isn't exactly right and no way to fix it.

I nearly always use free mix, but today I found other issues.... the problem here is that your idea of having all mixing capabilities under on umbrella is cool. but.... in order to make things flexable enough for me and others I think free mix should have all capabilities....

example 1.   My mechanical setup for flaps for aileron and flaps are nearly never perfect... usually if you set max and min on the outputs so they are the same everything seems to work pretty well.... but not always.

today my flaps were the problem, and i would up messing around in butterfly for a while. and realized I really needed to be able  set max and min on each flap on each channel   or have a seperate curve for each channel...
 Also on butterfly you don't permit changing offset so it can try and operate ail down and flap up  which is mechanically impossible
Offsets should be able to  be set everywhere.

I  wound up using 3 mixes for butterfly.  

1 for the ailerons which are mechanically right and operate seeming identically and added the left flap here I was able to do left flap here too.
2 for flap R because it had to change its excursion to match  the left flap
3  elevator cause it only needs slight operation of flap or  butterfly changes in general

the solution for me could be forget about all the pre made mixes and produce a free mix which actually is free.... give us access to percent up or down on each channel... or maybe a seperate curve for each.... or both.... let us pick a trim button for any mix.   
this would be awesome.... I know  this is OTX ish, but I would say most of us using Ethos are otx guys anyway.....

thanks for all you do for us

**Comment by miksterr** [comment]
Yes - agree 100% . While I love the 'canned' mixes their lack of further tweaking makes some of them, butterfly eg fairly useless.

**Comment by drummaker** [comment]
Thanks  Here is another thing I have learned... I didn't know there was a curve capability on the output.sometimes you guys make me feel silly.   It seems even though got things done with OTX I evidently did things differently in than intended.... Likely because of the freedom they liked to provide

Thank YOU
    On Monday, February 20, 2023 at 08:22:49 AM EST, mawzthefinn ***@***.***> wrote:  
 
 


For example 1, if you match your flap travel by setting up curves in outputs as per the excellent calibration method recommended by @RC-SOAR on his site rc-soar.com you will not have the issue. The key here is to use a 5 point curve at te output on one surface to match at more than just endpoints and center so you address any non-linear behaviours. It works very well.

You generally want to use Outputs for surface matching and max travel adjustment to avoid having to tweak mixer weights excessively
   
   -    
Offset is deliberately not contained in the flaps mix, as only one Offset setting should be needed (the one that sets your default flap position) and multiple mixes may be affecting those channels. The Offset mix was introduced for this reason, allowing a single offset for your flaps channels. It works very well if your flaps are matched in outputs

   -    
The best way to address OTX style mixing and Free mixes is to go all the way and use per-channel Free mixers in true OTX style. Using the ability of a free mix to target multiple output channels limits you when trying to mix OTX style.

**Comment by drummaker** [comment]
Boy I feel smarter now.... everything works and I am using the  butterfly mix as designed... Sorry for making you do tech support....I feel bad
    On Monday, February 20, 2023 at 12:20:06 PM EST, ***@***.*** ***@***.***> wrote:  
 
  Thanks  Here is another thing I have learned... I didn't know there was a curve capability on the output.sometimes you guys make me feel silly.   It seems even though got things done with OTX I evidently did things differently in than intended.... Likely because of the freedom they liked to provide

Thank YOU
    On Monday, February 20, 2023 at 08:22:49 AM EST, mawzthefinn ***@***.***> wrote:  
 
 


For example 1, if you match your flap travel by setting up curves in outputs as per the excellent calibration method recommended by @RC-SOAR on his site rc-soar.com you will not have the issue. The key here is to use a 5 point curve at te output on one surface to match at more than just endpoints and center so you address any non-linear behaviours. It works very well.

You generally want to use Outputs for surface matching and max travel adjustment to avoid having to tweak mixer weights excessively
   
   -    
Offset is deliberately not contained in the flaps mix, as only one Offset setting should be needed (the one that sets your default flap position) and multiple mixes may be affecting those channels. The Offset mix was introduced for this reason, allowing a single offset for your flaps channels. It works very well if your flaps are matched in outputs

   -    
The best way to address OTX style mixing and Free mixes is to go all the way and use per-channel Free mixers in true OTX style. Using the ability of a free mix to target multiple output channels limits you when trying to mix OTX style.

**Comment by mawzthefinn** [comment]
@drummaker - Glad you got it sorted out and don't feel bad or stupid at all.

These are advanced techniques that guys like @RC-SOAR and I teach, to make more complex setups work better. That you didn't know of these methods until now is perfectly OK. You had an issue, asked and got yourself some working answers. Absolutely nothing wrong with what you've done.

**Comment by mawzthefinn** [comment]
Closing this off as the questions have been answered.

Note there are active Issues open for both additional improvements for Butterfly mixing #266 and for free mixes #809 so these requests will not be forgotten
