### ISSUE TITLE
Request multiple expo settings within a mix

### ISSUE THREAD

**Issue by X20S** [FrSkyRC/ETHOS-Feedback-Community#243]
Within a mix, there is the ability to select different switch assigned weights ie rate switches, but only one expo setting which applies to all the rates. For fixed wing planes, particularly 3D, on high (3D) rates the pilot will typically want much higher expo than on low rates. This can currently be achieved using multiple mixers, but not on a single mixer page. So on a mixer page, next to the facility for switch assigned rates, can you include an expo setting for each weight?

**Comment by MIKE-DAILEY** [comment]
I think what you are asking for is Included in Release 1.0.6. https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release%2F1.0.6

**Comment by X20S** [comment]
Thanks Mike, sorry I jumped the gun on that one. Now running 1.0.6 and the feature is there exactly as I wished. Pity that basic rate/expo setting isn’t part of the wizard - would make the radio far more appealing to the average flyer technophobes. I’m sure you have already thought of that though. Cheers
