### ISSUE TITLE
1.5.0 pre / Var Mix: Range limits inactive by using trims (in certain conditions)

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2430]
In certain conditions range limits of (G)Vars are not taken into account, even in case user configured trim buttons to change the values. 
This seems to be another root cause then #2415 (another behaviour)

Example:
Configure trim buttons with edge function, so that you will change the value "one time by one click"
This will work until you process with "single klick" events.
(however, range limits will be "overshooted" by 1 unit)

BUT in case you hold the trim button, the value change will rapidly increase/decrease and limits are NOT taken into account, 
counter will only stop until value reaches -100/100

**Comment by bsongis-frsky** [comment]
Fixed in latest nightlies
