### ISSUE TITLE
Issue #47 is back

### ISSUE THREAD

**Issue by GWCTas** [FrSkyRC/ETHOS-Feedback-Community#2435]
The problem with throttle to elevator mix referred to in issue #47 is back.
![screenshot-2023-02-23-56735](https://user-images.githubusercontent.com/21648982/220858134-c7c7dc3e-ad8b-4052-bdee-b6151c63ea5a.jpg)

**Comment by bsongis-frsky** [comment]
It has changed when fixing #1152
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1152

**Comment by bsongis-frsky** [comment]
See the comments I have added to #1152
