### ISSUE TITLE
Programmable counter is urgently needed

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#2436]
Programmable counter is urgently needed
For the function modelers is urgently missing a freely programmable counter as a special function or lg switch 
Because they need for the many special functions 
impulse packages with different number of impulses

This can be ideally solved with a counter function
Set, Preset, Steps, Up, down, Autoreset, etc.
as it is already available in OTX.

Many function modelers are now switching to ETHOS XE.

**Comment by mawzthefinn** [comment]
This is part of the improved VAR functionality being added in 1.5.0 with #779
