### ISSUE TITLE
Mix throttle to elevator

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2437]
Add deceleration to the mix (throttle to elevator)
This is needed to tune the throttle response.

**Comment by mawzthefinn** [comment]
Why not use a curve? the behaviour is normally of a non-linear function than a delayed effect function. Curves are supported for that reason.

**Comment by bsongis-frsky** [comment]
Right it is exactly why we have curves there!
