### ISSUE TITLE
Count Up timer speech affected by Count Down values.

### ISSUE THREAD

**Issue by 3frcg** [FrSkyRC/ETHOS-Feedback-Community#2438]
Why count up timer is affected by countdown start and countdown step values ?

**Comment by mawzthefinn** [comment]
You can count up to a given time as well as count down to one. The start and step values affect any case when you have a set timer span.

**Comment by 3frcg** [comment]
I need a motor count UP timer for F5J . Alarm set to 30secs. Speech only ten seconds from 20 to 30 secs. There is no option to change this interval. Ok. I can adapt to.
But surprised when setting Countdown step to lets say 5 secs and have speech at 5 secs, 10 etc.. 
Naming this behaviour "countdown step"  is for me strange.

**Comment by mawzthefinn** [comment]
The naming is historical, we only really enabled count-up timers recently so that functionality originally only applied to countdown.

**Comment by 3frcg** [comment]
Thank you Mawzthefinn.

It's what I supposed. I suggest redoing the interface to avoid possible confusion. And update the documentation.
And please, if possible, symmetrize the capabilities up and down

**Comment by bsongis-frsky** [comment]
Timer Audio Actions have been completely rewritten recently. Please have a look to the latest nightlies!

**Comment by lthole** [comment]
This should not be closed, the behaviour for UP counting timer is not correct.
Test case:
1. Mode = Up
2. Alarm value = 00:01:10
3. Start condition = SD up
4. Stop condition = default
5. Reset = SJ down
6. Audio actions:
i) Play value: Start 00:00:30 Step 10s
ii) Play file: Start 01:10 file = time.wav

Test results:
1. At 00:30:00 the value is played, but never repeated at Steps of 10s
2. At 00:01:10 the file is played, which is correct, but the Timer in the main page widget does not go red after the Alarm value has been exceeded.
