### ISSUE TITLE
Telemetry sensor "channel"

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2439]
For logging, it would be good to record channels on the receiver (e.g. max 8 channels)
Is it not possible to add a custom sensor "channel" (RxCH)?

![Screenshot_174](https://user-images.githubusercontent.com/85956904/221017676-613ae7ad-e539-4e7b-ba27-62db1b076d8f.jpg)

![Screenshot_173](https://user-images.githubusercontent.com/85956904/220978641-567facd5-cbe1-4a11-855d-1dfa13081120.png)

**Comment by mawzthefinn** [comment]
The receiver does not transmit channels to the transmitter. 

The ability to log channels sent to the RF module will be added, in the next nightly most likely.

**Comment by bsongis-frsky** [comment]
Channels can be logged in 1.5.0 (tonight nightlies)
