### ISSUE TITLE
Incomplete SD card contents?

### ISSUE THREAD

**Issue by gjvo** [FrSkyRC/ETHOS-Feedback-Community#244]
Hi, i received my Tandem X20.
I saw i had to update the firmware so i checked how to do it in the video on the Ethos site.
I think i am missing some folders on the card.
I saw on the video the folders: Audio, Bitmaps, Models, Firmware, Logs and in the root firmware.bin
On my card there is only Audio, Bitmaps and Models and in the root radio.bin

What should be the content of the card?
I made a folder firmware myself to flash the receivers, that works, but i think the folders should be there already?

**Comment by bbdmarch** [comment]
I just created the missing folders on the card in Windows..... working fine

**Comment by loetefix** [comment]
the folder logs will be created by the transmitter itself when there are logs

**Comment by gjvo** [comment]
OK, i did not use logging yet.
And Firmware you just make it by yourself, like i already did?
Would be easier if they would write that somewhere or mention it in the instructionvideo.
Or just put it already in the contents.

**Comment by jbesse262** [comment]
Firmware.bin goes in the root and is deleted automatically after the radio updates. You have all the required folders already

**Comment by Jammo1** [comment]
Hi Just managed to delete my SD card contents for Tandem X20. Where can I download a refresh?
Thanks
