### ISSUE TITLE
CRC incorrecte ???  X20 

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#2440]
Bonjour,  juste pour info .

J'ai installé la dernière version du FW , qui c'est passé sans problème via ETHO suite .

Au démarrage de la radio X20 , le model qui était actif au moment de la mise à jour , ne s'ouvrait plus , message d' erreur  était 
" CRC incorrecte"  .
Heureusement c'était un model assez basique , je l'ais reprogrammé .

**Comment by bsongis-frsky** [comment]
Il faudrait attacher le fichier en question pour que je puisse regarder !

**Comment by Mobidick1966** [comment]
Le fichier a été supprimé .
Merci quand même pour la réponse.
