### ISSUE TITLE
System Tables Overview

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#2442]
Hello Bertrand,
Is there a system tables overview or the possibility to list them via LUA, possibly a Lua example
Thanks very much
Greetings Benno

**Comment by Benno00** [comment]
Hello Bertrand,
I mean e.g. whether there is a system table for the fonts ect. there, currently I'm making my own table using the BASE constants if there were a queryable table I wouldn't have to adapt the LUA if your e.g. add new writings.

Greetings Benno.

**Comment by bsongis-frsky** [comment]
I understand you need a new Lua function, would you tell me which would be its name and its expected result? I am not sure I fully understand what you need and the issue has disappeared below a ton of other issues
