### ISSUE TITLE
POP-UP Widget

### ISSUE THREAD

**Issue by Lars-Braun** [FrSkyRC/ETHOS-Feedback-Community#2443]
Hi!

It would be very helpful if there is a "pop-up widget/screen" feature.

Example: When switching on, or after selecting a model, there is a "temporary screen" in which information can be displayed that is only necessary when calling up the model. Info about the model, switch assignment etc.. By pressing a button or moving any input, the screen disappears.

Would be very helpful if you have many models to fly... ;-)

Greetings Lars

**Comment by mawzthefinn** [comment]
This will be in 1.5.0, the checklist feature has been extended to display arbitrary text
