### ISSUE TITLE
Model page may benefit from the ability to re order model order into personal choice, i.e., most popular, etc., and load without photos, to speed up the loading time, and font size.

### ISSUE THREAD

**Issue by Robynhud** [FrSkyRC/ETHOS-Feedback-Community#2446]
While there are folders for electric, etc, the model page is static in the order the models appear. I would like to be able to re-order the my models to my preference. Also, as the model page is slow to load, and as an old git, quite small, so the choice of just a list with larger characters, and no pictures, would be appreciated. This may also help from the point of view of being able to re-order the page, say by selecting a model, and then being able to move the model up or down.

**Comment by strgaltdel** [comment]
No, i'm pretty shure it's not static,
order is determined by alpha-sort of filename,
assuming filename = modelname you are able to set an individual order by indizes as a prefix. 

![image](https://user-images.githubusercontent.com/20392683/221373970-819e7cd9-132f-4014-b62d-48f06a94015f.png)

**Comment by keiner0815** [comment]
I am fine with the order of models, but I also think that the screen to select models is extremely slow to load. I tried to fix it with a fast micro sd card, but it is still slow.

**Comment by loetefix** [comment]
it would be nice, if we had an option to change the modelselect-style to a list with only names.(how it is on taranis)

**Comment by Robynhud** [comment]
> No, i'm pretty shure it's not static, order is determined by alpha-sort of filename, assuming filename = modelname you are able to set an individual order by indizes as a prefix.
> 
> ![image](https://user-images.githubusercontent.com/20392683/221373970-819e7cd9-132f-4014-b62d-48f06a94015f.png)

There is still the issue of font size, more important again on the X18, as the screen is half that of the X20. Also, you’d have to keep a paper chart of prefixes, to keep track of a dynamic list.

**Comment by pstasek** [comment]
The loading speed can be improved by using jpg files instead of bmps. Smaller files load faster. Make sure to create the jpg files in size 300x280px  to fit the widget and avoid resizing. Currently, I'm using PowerToys to batch resize my photos. Ethos Suite functionality is requested: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2522

**Comment by Robynhud** [comment]
Is that your personal preference?Robert Sloan On 6 Mar 2023, at 11:12, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
It's sorted in alphabetical order without case
