### ISSUE TITLE
Mixer Wizard: Elevon mix requests

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#2447]
Hey guys, I was recording a video today, and think that the output from the new model wizard could be improved, when setting up an elevon mix.

Steps to take on the wizard:
- 1 engine
- 2 (or 4) Ailerons
- No tail

When you go to the mixer, the setup isn't as expected. You have
```
Aileron  | 1, 5 (, 6, 7)
Elevator | 1, 5 (, 6, 7)
Throttle | 3
```
There's no reason not to use **Channel 2**, as the elevator function is part of an elevon. Also, if using 4 elevons, why also skip **Channel 4**, as there is no rudder. Ideally, I would like to see a mixer created by that wizard set as
```
Aileron  | 1, 2 (, 4, 5)
Elevator | 1, 2 (, 4, 5)
Throttle | 3
```
Otherwise, you need to re-order, so as not to have channel gaps. **Channel 3** in this instance needs to be kept for the motor. But if no motor is added, I don't see why Channel 3 should not be used for the next control surface either.

Also, less important, but a nice to have. Could the outputs be labelled as **Elevon1** etc, instead of **Aileron1**... The same is also true of a v-tail mix, as far as the naming goes. Both outputs are labelled as **ElevatorX** when they should be **RuddervatorX**.

**Comment by dap35** [comment]
I would add the option for 1 or 2 rudders as well.

**Comment by mawzthefinn** [comment]
This is a legacy of the 'first four channels fixed' setting. If you disable that setting, you will get the second mapping.

**Comment by MrD-RC** [comment]
If the first 4 channels fixed is disabled. Is the channel mapping still used as a guide? I remember before, if you had a standard plane with 2 ailerons, they would end up on ch1 and ch2. Where you still want them on ch1 and ch5.

**Comment by mawzthefinn** [comment]
Yes, the channel mapping still guides, but functions double up on channels (so  you would get AAETR for a dual-aileron conventional setup).

The current Delta logic treats them as ailerons with elevators dropped on top of them.

There’s wizard channel assignment changes coming in 1.5.0, which should help address this
