### ISSUE TITLE
BOOTLOADER - USB

### ISSUE THREAD

**Issue by WOODY1958UK** [FrSkyRC/ETHOS-Feedback-Community#2449]
HI - FIRST PLEASE EXCUSE CAPS - BUT I AM PARTIALLY SIGHTED AND IT HELPS - SO I HAVE A TX18 - WHEN I PUT IT INTO BOOTLOADER MODE - THEN CONNECT USB - I DON'T GET A VERSION NUMBER - JUST - 'USB CONNECTED

**Comment by OldGazer** [comment]
WHEN I  PUT MY X20 INTO BOOTLOADER MODE THE BOOTLOADER VERSION NUMBER IS IN THE UPPER RIGHT HAND CORNER OF THE DISPLAY.

**Comment by WOODY1958UK** [comment]
HI - YES  SORRY - ME NOT LOOKING HARD ENOUGH - BECAUSE I AM PARTIALLY SIGHTED SO ISSUE SOLVED THANKS CATCH YOU LATER TAKE CARE HAPPY FLYING DAVID    DAVID BRIAN HOMEWOOD FLAT 32, MARGARET HOUSE LEALANDS DRIVE UCKFIELD EAST SUSSEX TN22 1FH   TEL :- 01825 765690 MOB :- 07759 517 323 E-MAIL :- ***@***.***  

On 28-Feb-2023 04:29:59 +0100, ***@***.*** wrote: 

WHEN I PUT MY X20 INTO BOOTLOADER MODE THE BOOTLOADER VERSION NUMBER IS IN THE UPPER RIGHT HAND CORNER OF THE DISPLAY.
