### ISSUE TITLE
Feature request:Bluetooth Audio speaker on/off

### ISSUE THREAD

**Issue by Beastyboy80** [FrSkyRC/ETHOS-Feedback-Community#245]
Internal speaker  on/off with a switch

**Comment by WismyYao** [comment]
Do you mean a switch to turn on/off the speaker of bluetooth audio ?

**Comment by MrD-RC** [comment]
There is an option in the Bluetooth settings to turn off audio on the transmitter (Speaker mute). However, it would be nice if it would re-enable transmitter audio when the Bluetooth device is not connected.

![image](https://user-images.githubusercontent.com/17590174/118536092-33855500-b743-11eb-9c31-13a944bbc4b4.png)

**Comment by bsongis-frsky** [comment]
@MrD-RC the issue you mention is fixed now in 1.0.7

**Comment by bsongis-frsky** [comment]
We will add a switch later to change the setting in flight

**Comment by IJK-CZ** [comment]
The 'Audio' BT option is not visible in X10 simulator.  This feature is not available for X10S ?
 
![BT_options](https://user-images.githubusercontent.com/44742963/118795134-95a49e00-b89a-11eb-8c04-b0a00f5dc95d.jpg)

**Comment by bsongis-frsky** [comment]
No. Only X20S

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/119990277-6db6e800-bfc8-11eb-8c3d-52605e04570c.png)
