### ISSUE TITLE
display text on screen

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#2450]
it's possible to play audio file when switching Sa, Sb ,,,Sx, it's perfect so
but is it possible to generate a text displayed on screen depending of the switch position? like RTH or ANGLE MODE or HORIZON or whatever you need?

**Comment by mawzthefinn** [comment]
Use of Flight modes will display the Flight Mode name when selected.

This can be combined with the use of a VAR mix to control the receiver/FC flight mode, with weights selected by  transmitter flight mode.

**Comment by bsongis-frsky** [comment]
Or use a Lua script to display your own text
