### ISSUE TITLE
ETHOS Suite Cannot read my X18

### ISSUE THREAD

**Issue by chrisca70** [FrSkyRC/ETHOS-Feedback-Community#2451]
Fellow Pilots, just got an X18 with a GR6 Rx. Having issues connecting my X18 to the Ethos Suite on my computer.  Below are the key facts to see if I can sort this out with some help... Thank you!

- Transmitter works fine, binds fine, etc.
-  I am on Windows 10 Enterprise x64 
- My PC has the latest EHTOS Suite version 1.4.7
- Transmitter has the latest Bootloader 1.2.11
- Have tried with different USB cables and USB ports on the PC, I have a really high quality cable, issue remains regardless of cable/port.
- When connecting the Transmitter via the USB-C port to my PC, my PC can detect the NAND and FLASH drives but Ethos keeps showing "Reading version..." like it cannot fully communicate with the X18 (see pic attached).
- On Model Manager, Models show up but cannot be edited, the Edit button is greyed (see pic).
- From a couple hours of online digging, this may be related to the DFU driver, I tried the ImpulseRC Driver Fixer and nothing happened, is there a way to install a DFU driver if this could be the issue?

![Capture](https://user-images.githubusercontent.com/126706912/222219262-1ad5bcc8-db5e-427d-8837-49be5d8aa900.JPG)
![Capture2](https://user-images.githubusercontent.com/126706912/222219280-af969ad9-f1b1-4d6f-b404-77040188f773.JPG)

**Comment by 3frcg** [comment]
Model edition is not yet supported.

**Comment by bsongis-frsky** [comment]
It's strange that it shows "Reading Version", with a version displayed!

**Comment by Nicholas-Luoyi** [comment]
"Reading Version" means Suite is getting the remote version for comparison. Would you please check your network or permission for Suite. And try to switch the server location in the Suite settings. In the main while, I will check if it's truly a bug on my side.

**Comment by Nicholas-Luoyi** [comment]
Or if you could find some crash logs by opening the crash log in Suite settings. You could send them here.

**Comment by chrisca70** [comment]
I uninstalled the Suite and reinstalled and things improved a bit. 

- Bootloader mode window now shows the buttons in green and seemingly it can read the version successfully.
- Still there is a communication issue, Update News window is empty, DFU flasher window is no active like I have seen from other users' posts
- @Nicholas-Luoyi Nicholas-Luoyi How can I "check your network or permission for Suite"?
- @Nicholas-Luoyi Nicholas-Luoyi No crash logs appear in Suite settings

![Capture1](https://user-images.githubusercontent.com/126706912/222729022-72992765-85be-4d9c-9e9d-abc4d72d4946.JPG)

![Capture](https://user-images.githubusercontent.com/126706912/222729045-ac3358d6-092e-4d85-bcf2-d901796ade21.JPG)

![Capture0](https://user-images.githubusercontent.com/126706912/222729299-c2f8ad98-0c33-4556-b32c-fdd05bc61fb7.JPG)

**Comment by Nicholas-Luoyi** [comment]
To use DFU Flasher. Radio should be connected to your PC after the Suite is started. Or Suite won't detect the radio.

**Comment by chrisca70** [comment]
> "Reading Version" means Suite is getting the remote version for comparison. Would you please check your network or permission for Suite. And try to switch the server location in the Suite settings. In the main while, I will check if it's truly a bug on my side.

You were right. I was using my corporate network and switch to a different network (wifi) and now it is all working perfect! thank you very much

**Comment by mawzthefinn** [comment]
Closing as issue was resolved
