### ISSUE TITLE
1.5 nightly: TWIN X-Lite S simulator fails loading 1.4.6 / X20 setup

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2452]
I have a simple setup created in the X20 simulator (V1.4.6). I want to test in the TWIN X-Lite S simulator (V1.5 nightly). 

However the data conversion in the sim appears to fail. Steps:

1. Copy the X20 model file to the \models folder of the TWIN X Lite S simulator.
2. Start the TWIN X Lite S simulator, and the model is visible
3. Highlight the model and select 'Set Current Model'.

_Expected_ the model data should be converted, and loaded
_Actual_ : fails with 'Invalid Data'

Running TWIN X-Lite S simulator
![2023-03-02_171457](https://user-images.githubusercontent.com/6317479/222505628-dad922e8-5b7d-491a-8b65-630823524dbb.png)

**Comment by RC-SOAR** [comment]
@bsongis-frsky  here it is, as created in the simulator 1.4.6 for X20: [simple.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10874968/simple.bin.txt)

**Comment by STC148** [comment]
When I clone an imported model, I can open it but a blank screen is displayed.

![1](https://user-images.githubusercontent.com/85410070/222553185-b61fc13f-699d-4aa7-b4e5-2975aabad677.jpg)

**Comment by mawzthefinn** [comment]
This happens on my X20 as well, in general the nightlies don't do model conversion yet
