### ISSUE TITLE
XJT Lite Telemetry values are off

### ISSUE THREAD

**Issue by krelt** [FrSkyRC/ETHOS-Feedback-Community#2453]
ADC 1 and 2 report incorrect voltages. Can be somewhat cured by offset but doesn't seem to respond consistently. Ethos 1.4.7, X18. Observed on D8 and D16 V1 receivers.

**Comment by bsongis-frsky** [comment]
Have you plugged something to ADC1 and ADC2?

**Comment by krelt** [comment]
Yes. My primary use is ADC1 for receiver voltage. It's a little difficult to connect a meter and set the offset correctly. The same receivers usually connect and send the proper voltage with no adjustment. So I have receiver and some servos plugged in. Most concerning is it does not seem to be linear. The offset for a 1s lipo is different than the offset for a 4s Nimh. That makes me think I can't trust this measurement. This is critical for F3K running a single lipo cell.

**Comment by krelt** [comment]
Same module in X9 lite running Opentx reports correctly with no adjustment. I just checked that again.

**Comment by WismyYao** [comment]
![image](https://user-images.githubusercontent.com/16497598/223310811-f21ebf87-d400-4ed0-b303-e2b48b3aa26a.png)

Have you tried changing the ratio? 
Receivers of different protocols have different ratios

**Comment by krelt** [comment]
I have adjusted ratio as well as offset. The closest I think I'm getting for linearity is with both. It's hard for me to measure across the discharge of a battery without test equipment. I'm trying to get it to read correctly at full charge and near where I want alarms to go off.

**Comment by krelt** [comment]
XJT Lite telemetry still cannot be trusted without a meter and corrections.

**Comment by krelt** [comment]
No worries. I thought it might be as simple as changing something back so that it always worked as it had. I have been told that the XJT Lite is old and should be abandoned.
