### ISSUE TITLE
Add mix icon.

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2454]
The "+" add mix icon is too small. We would like a larger one, please, in the color of the "Highlight Color" option, such as in the picture.
.
![Sceenshot_189](https://user-images.githubusercontent.com/85956904/222642473-d3416185-409c-4af8-82d4-594b25037c41.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/222792261-9b8f4676-10ef-45b3-9118-ef0a824c8158.png)

**Comment by jurajjurej** [comment]
All add "+" icons need to be improved to make them more visible. We thank you.
![Screenshot_210](https://user-images.githubusercontent.com/85956904/223724735-a771952e-bdb3-4ba4-ab76-95cb601bd908.jpg)
![Screenshot_209](https://user-images.githubusercontent.com/85956904/223724788-da17e18c-5548-48ba-b437-0fe566484e00.jpg)

**Comment by bsongis-frsky** [comment]
Done for the next nightlies

**Comment by jurajjurej** [comment]
Excellent, it will liven up and clear the environment a bit.
Well thank you.
