### ISSUE TITLE
Flaps => Ele mixer is missing needed options

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#2461]
Mixer Flaps => Ele is missing an offset and slow options. Without offset you cannot have a 0% to 5% flap compensation for example which is very common. Slow is very usefull to have the same speed for the compensation mixer as for the flaps itself.

Without these options a free mixer will always be needed for flap compensation

**Comment by mawzthefinn** [comment]
Slow is not missing, it's deliberately not there to ensure you set that in the flaps mixer and the elevator always tracks flaps.

Use the output channel of the flaps mixer as the input and the Flap->ELe mixer will track the slow settings in the flaps mixer

you can easily address the offset issue with a 2-point curve, but this is an issue like #2435 and needs addressing

**Comment by RealTadango** [comment]
> Slow is not missing, it's deliberately not there to ensure you set that in the flaps mixer and the elevator always tracks flaps.
> 
> Use the output channel of the flaps mixer as the input and the Flap->ELe mixer will track the slow settings in the flaps mixer
> 
> you can easily address the offset issue with a 2-point curve, but this is an issue like #2435 and needs addressing

Does not feel right to use a flap output channel as input, but I can see that as a work around for now. Still would like to have slow in here natively. Even better would be to have elevator compensation in the flap mixer. Or have the flap => ele use the flap mixer as input, not a flap channel (would work the same but would be save from channel changes...) If ethos want pre defined mixers like other systems they have to work better together ;)

**Comment by mawzthefinn** [comment]
You are fundamentally mixing the flaps to the elevator here. That means you want the full output of the flaps channel, not one specific mixer's output. 

Remember you might be doing other things to the flaps which need to be respected (Offset, butterfly, etc) by the flaps=ele mix

**Comment by RealTadango** [comment]
Butterfly has it's own elevator compensation. It makes sense to use the flap input for me, not the flap channel. Offset is REALLY neded in any case. Slow is only needed if you use the flap input and not the channel. Without offset this mixer always needs a curve even for the simple setups

**Comment by mawzthefinn** [comment]
I don't use the elevator comp in Butterfly because you can't assign a separate curve to it.

I do agree that the flaps->ele mixer does effectively require a curve in most situations, but I don't like the use of an offset to get around that, personally I'd rather just use a 2-point curve which can be more precisely dialed in.

**Comment by mawzthefinn** [comment]
It's worth noting that several mixers exist only so it's obvious to non-technical users.

The Airbrake mixer in particular is literally the Offset mixer with a different name.

**Comment by RealTadango** [comment]
I get that but without an offset this flaps ele mixers is not usable for normal models, only gliders maybe. Adding this would help non technical users ;)

**Comment by mawzthefinn** [comment]
Offset is a poor way to address that because the value of the offset is conditional on the rest of the mixer settings. You adjust the weight, or use multiple weights and you need different offsets. 

A 0-100 or 0-(-100) 2point curve works today and only one needs to be added.

**Comment by RealTadango** [comment]
Still a lot easier then creating a curve right?

**Comment by mawzthefinn** [comment]
> Still a lot easier then creating a curve right?

No, decidedly harder than adding a curve. No math required on the curve, add curve, set type custom, set to 2 points, set the second point to 100. Done. 

Zero math required for the curve, and you can re-use that conditioning curve elsewhere in your programming (it is the same one you use for any 0-100 input conditioning, like gains). 

The offset has to be 50% of the weight of the mixer to get 0->xx weighting, so you have to recalculate every time you adjust the weight (and if you set up an adjustable weight? Get ready for some fun or proxying via a mix to get it auto-calculating)

**Comment by RealTadango** [comment]
10% mix needs 10% offset. Not that difficult :) I will keep using free mixers for now because slow is needed also, and I don't use the flap channel as source but the flap slider.

**Comment by mawzthefinn** [comment]
> 10% mix needs 10% offset. Not that difficult :) I will keep using free mixers for now because slow is needed also, and I don't use the flap channel as source but the flap slider.

If you're using the slider, you aren't mixing flaps=>ele in the first place, you're mixing LS or RS to Elevator. Free mix is correct when mixing an input to a surface. Flaps=>Ele exists to mix the flaps to the elevator, not an input. 

And you've set up a situation for yourself where you have to adjust the same thing in 2 places every time you change it, vs in 1 place. That's more work, every single time vs using a curve you do once, the same way, every single time.

**Comment by RealTadango** [comment]
An option for an auto offset (only down compensation for example, not both ways) would still be very welcome.

**Comment by RealTadango** [comment]
Still a welcome feature
