### ISSUE TITLE
Global Variables - issues

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2463]
I tested Global Variables a bit in todays nightly. Creating a new issue, as the previous one is closed now: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/779

- I know this idea was abandoned, but I really see it useful to have "slow up / down" possibility, or "fade in / out" here. This would be very useful.
- There's a problem if you defined an `Add` action, that it happens very very fast. Not controllable at all. Maybe slow up / down (above) would help
- I tried to make "Add" work with "Edge sources". For example, to Add +1 on "Edge of SA switch" (long press on a source and select "Edge"). But there's a bug: instead of adding +1 it adds some random number between 1 and 10, just at one switch usage. Probably based on some timing.

Overall it's a great feature.

**Comment by azaz44** [comment]
BTW, all models become invalid when using this nightly.

**Comment by mawzthefinn** [comment]
1. This is a mixer action, do this at the mix or flight mode level. VAR's are for values, mixers are how you manipulate inputs to outputs. 
2. Yes, known issue with add/subtract/multiply/divide
3. Hmm, that is interesting. I'd not tried this way yet

And yes, we are aware that the nightlies do not convert older models yet.

**Comment by azaz44** [comment]
Well, point 1 was just another try 🙂

As for p. 2, it could be (partly) solved with 'Time Generator' in 'Logic Switches'. Just make a time generator LS with desired times, active when some switch is on, and then use this LS rising edge to increase or decrease the var at the rate you want. But bug from p. 3 block this possibility ATM.

**Comment by bsongis-frsky** [comment]
Bugs fixed
For point 2 we could add a "Repeat" parameter. Like:
Repeat ... [100/s | 10/s | 1/s]

**Comment by loetefix** [comment]
better only repeat after holding at least a second..

**Comment by Peterbilt84** [comment]
Unfortunately, the issue was closed without a satisfactory solution.
At the moment, the buttons on the VARS mixer cannot be used because no exact value can be reached by pressing the button.

**Comment by mawzthefinn** [comment]
This functionality is in Nightlies. Not all items that have been addressed are in the posted nightly builds yet.

Nightlies are test builds only.
