### ISSUE TITLE
1.5.0 n: value widget doesn't display vars member

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2466]
as mentioned,
by creating a value widget and configure a vars member as source, the display field remains empty

not even a "zero" is displayed
tested with nightly from 04032023

btw
in #2108 you mentioned
"Numeric keys without numeric keyboard are used for trims"

.. seems not to work,
at least in my config with an external  usb-KB connected to a notebook without numeric keyboard

**Comment by bsongis-frsky** [comment]
Fixed in next nightlies
