### ISSUE TITLE
v1.4.7 Can not loadFont

### ISSUE THREAD

**Issue by koakumaping** [FrSkyRC/ETHOS-Feedback-Community#2467]
![image](https://user-images.githubusercontent.com/4099388/223010940-eedd7158-f1d2-46af-b885-8577268d2b38.png)
![image](https://user-images.githubusercontent.com/4099388/223010953-666a2ed8-e300-4113-8e12-553925cc3b5c.png)
```
lcd.loadFont('SmileySans.ttf')
```

**Comment by bsongis-frsky** [comment]
It is only able to load the .fnt files from Ethos
We will have some work on the font converter inside Ethos Suite

**Comment by koakumaping** [comment]
Can provide a converter？I convert it by FontForge, still can not use it.
