### ISSUE TITLE
X12S ethos 1.4.7 Gas suite issues

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2469]
i have 3 planes all running  Gas suite telemetry  under 1.4.6 working fine update to 1.4.7 

and some boots the gass suite does not show at all 

using X12S on 1.4.7 with 2 x Access R8 Pro on firmware Archer-X_2.1.12 

not the only things working is gas rpm gas temp 1 gas temp 2 

gass Res Vol done not move stays at full tank 1457  ml
gass flow stays on 0ml/m
gass Res % stays on 97%
gass Avg flow stays on 24ml/m

all the same on all 3 planes

**Comment by bsongis-frsky** [comment]
Now wondering if this issue is not linked to the other one (RSSI, 2 planes bound to the same radio)

**Comment by yak-54** [comment]
look like it is linked but i have never bound my radio to his plane or receiver

**Comment by yak-54** [comment]
[](url)

**Comment by yak-54** [comment]
linked to his issue #2470
