### ISSUE TITLE
TD-ISRM - Cannot bind LBT ACCST receiver with FLEX firmware

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#247]
X20S flashed with X20S FLEX firmware v1.0.6

S8R receiver flashed with ACCST V2.1.2 LBT from the X20S

Settings on RF System page
**Internal Module**
- **State** ON
- **Type** ACCST D16 - FLEX868M
- **2.4G** ON
- **Antenna** Internal
- **Model ID** 1
- **Channel Range** CH1 - CH8
- **Failsafe** Custom

When I select Bind, choose the correct telemetry setting, and it says "Binding". I put the receiver in binding mode, but nothing happens. The transmitter will say "Binding" forever, and the receiver shows no changes. Clicking OK and testing the bind shows that is has not bound.

**Info Screen**
- **Firmware** Ethos - X20S
- **Firmware Version** - 1.0.6 FLEX #8f7a9990
- **Date** May 14 2021 17:40:29
- **Storage Version** 0.0.4
- **Sticks**ADC
- **Internal Module** TD-ISRM - HW:1.4.0 - 2.1.6 (FCC) <-- that could be the problem
- **External Module** OFF

If the FCC FW in the FLEX is the issue, I guess this means there needs to be a FLEX FCC and FLEX LBT firmware?

**Comment by MrD-RC** [comment]
After flashing the EU firmware, I can confirm that this is the problem. Please can we have an LBT FLEX firmware. After all, FLEX was first introduced as a workaround for the folks in the EU.

Since the binding works, I have another couple of related suggestions:

**Comment by b14ckyy** [comment]
@MrD-RC Flex is not supposed to work with LBT or FCC. That was always the case with R9. 
Flex does not mean that it does allow you to switch between EU and FCC rules. IF you use FLEX on 868MHz it still does not use LBT feature and still allows telemetry at more than 25mW power. 

So either all receivers are flex or all are on LBT/FCC to work with the radio.

**Comment by MrD-RC** [comment]
@b14ckyy you're thinking of pure R9 here. With this transmitter the firmware contains both 900MHz and 2.4GHz. If I install the FLEX firmware, it sets the 2.4GHz to FCC. There needs to be an LBT (EU) FLEX firmware to allow the 900MHz side to use FLEX, but have the 2.4GHz side using LBT. There aren't separate firmwares for the 900MHz and 2.4GHz parts.

**Comment by b14ckyy** [comment]
Ahhh thanks. Now I get what you mean.

**Comment by bsongis-frsky** [comment]
@MrD-RC It will be fixed in the next TD-ISRM firmware. Issue not related to Ethos, I will mark it as RF

**Comment by MrD-RC** [comment]
Hi all. I have now updated the ISRM to 2.1.8, which is supposed to fix this issue. However, nothing appears to have changed. I have a short video showing what is happening.

https://youtu.be/TOknarQRtC4

**Info Screen**

- **Firmware** Ethos - X20S
- **Firmware Version** 1.0.10 FLEX #03f394e2
- **Date** Jul1 2021 11:49:34
- **Storage Version** 0.0.7
- **Sticks** ADC
- **Internal Module** TD-ISRM - HW:1.4.0 - 2.1.8 (FCC)
- **External Module** OFF

**Comment by Adelaxie** [comment]
2.1.9 updated，please check.
