### ISSUE TITLE
X12S Ethos 1.4.7 radio says Receiver still powered on and its not

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2470]
radio says Receiver still powered on and its not

i turn the model off  first then picked up the tx went power off i got a warring RX is still on

![20230306_155537](https://user-images.githubusercontent.com/9161926/223048948-5ca2e89c-e8e8-433c-a638-d94705d99f76.jpg)
![20230306_155541](https://user-images.githubusercontent.com/9161926/223048980-5d795a61-354e-48d8-9b49-0de9ee5663c1.jpg)

**Comment by bsongis-frsky** [comment]
On your picture I see RSSI = 65dB. When the RX is OFF it should return to 0dB

**Comment by yak-54** [comment]
> On your picture I see RSSI = 65dB. When the RX is OFF it should return to 0dB

yep the plane is powered off that is why gass suite is red 8i have on clue why rssi still shows 
the only thing i think it may of been is my buddy was standing 20 meters away just about to take off with X20 with a plane that has access  M+

**Comment by yak-54** [comment]
i just ran a test i have his plane in my car after todays flying 

i power on TX then i powered  on his plane and the i powered on my my plane 
i had look at my planes bound receivers i have 2 x R8 pro  FW-Archer-2.1.12 bound to my radio 

![20230306_200045](https://user-images.githubusercontent.com/9161926/223066203-d155f060-7671-4cde-8feb-97a02f1aadc3.jpg)

so i went into my tx info Gee look at what i found receiver number 3 his plane 

this explains why my plane  Glitching Problems today i just about crashed it  i had no control then it stop came good my mate 
now come to think of it he just landed when i plane came good 

do you see what i see in on the info page all three revivers 
![20230306_200000](https://user-images.githubusercontent.com/9161926/223068169-fb68c28b-9612-4cb9-82d4-f85330c2dd88.jpg)

**Comment by bsongis-frsky** [comment]
What's that, you are bound to 2 planes in the same time? The same REGISTER code is used, same ModelID?

**Comment by yak-54** [comment]
the only thing in common is that all the receivers FW-Archer-2.1.12   
to me it looks like FW-Archer-2.1.12 has broke model Match ID or 1.4.7 has

**Comment by bsongis-frsky** [comment]
You use the same REGISTER code on the 2 transmitters?
What is the ModelID for the 2 planes?

**Comment by yak-54** [comment]
i cant tell i don't have his transmitter i will call him 
but under access he had to register and bind the receiver  to his X20 why would the the radio id be the same ?
or is it when he binds to his plane and the ModelID is the same as my tx thats not good

my model id is 10 
just called him his wife said be home in 15 min

**Comment by yak-54** [comment]
His plane ModelID 10

REGISTER code TRvrwutw

**Comment by yak-54** [comment]
Fixed 
I deleted all bound receivers to that model  re register each one with  different UID and re bound them and issues look like its gone
