### ISSUE TITLE
1.5.0 Widget forms: y-offset from title is not taken into account

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2473]
just startet a quick test of the form functionalities within widgets (#1411)

in case you activate the widget title, it's Y-offset is not taken into account when you want to edit the field
(tested with form.addNumberField method)

the screenshot shows a number field placed with Y-Position = 0

![widgetform](https://user-images.githubusercontent.com/20392683/223064493-25f8d285-54d6-45d7-a419-cb663009a735.png)

maybe another issue, don't know if its "by design", vertical alignment:

attached you can see a number field with position settings:
x=20, y=0,  w=70, h=24

it's my understanding that h=24 gives enough headroom to display the numbers.
it seems that the "baseline" for the number is placed below the field margin which leads to an "offset" on top and a "cut" at the bottom

![image](https://user-images.githubusercontent.com/20392683/223070672-d2a0da15-115c-41ca-ae5a-624c067407d6.png)

regards
Udo

**Comment by bsongis-frsky** [comment]
I don't understand your request, please attach a minimal script which produces your screenshot?

**Comment by strgaltdel** [comment]
[main.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10896802/main.zip)


sorry for my bad explanation.

this example should provide both issues:

(1)
you'll have to touch ABOVE and not "WITHIN" the number area to get into edit mode with title enabled
(app. in line of title)

(2)
you can only see upper half of number


![image](https://user-images.githubusercontent.com/20392683/223080445-73a551e2-400e-4cf9-ab00-ff248e244a7b.png)

**Comment by bsongis-frsky** [comment]
Next nightlies will prevent from the mistake in your script

![image](https://user-images.githubusercontent.com/50834778/223087100-65fc111a-7328-4b53-9818-cd0744941915.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/223088942-7dda788e-41a1-497a-b9fe-8794e23f7109.png)

![image](https://user-images.githubusercontent.com/50834778/223088991-54aa4e83-46dd-4231-b01c-893830144276.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/223089076-2516dd2f-0ba8-486e-80d5-55eed0e879c5.png)
