### ISSUE TITLE
(Feature Request) Special Function to switch pages

### ISSUE THREAD

**Issue by craigywsm** [FrSkyRC/ETHOS-Feedback-Community#2475]
Could there be a special function option to scroll to the next page(s).
e.g. 
With multiple pages setup 
Page 1 having alot of sensors listed
Page 2 having Zavionics Lua Turbine telemetry 

Then the buttons on the back of the radio could navigate back and fourth between the pages

**Comment by mawzthefinn** [comment]
This is a duplicate of #652 

Please continue discussion under that issue.

**Comment by craigywsm** [comment]
Sorry @mawzthefinn I did try to find a ticket already open. Thank You
