### ISSUE TITLE
Make possible to switch on sport so we can take 5v from it to use an cppm rx als trainer module

### ISSUE THREAD

**Issue by rwijnhov** [FrSkyRC/ETHOS-Feedback-Community#2477]
Make possible to switch on sport so we can take 5v from it to use an cppm rx als trainer module

**Comment by mawzthefinn** [comment]
#1297 is probably a better solution for this, putting the external receiver in the module bay and supporting Sbus as well

**Comment by rwijnhov** [comment]
Actually not sure. Since ppm in from the module bay probably requires a lot  more work then just to be able to switch on 5v on the s port since ppm in is already implemented on the disc port.

**Comment by RealTadango** [comment]
Module bay should not be used for this because this will be needed for MPM modules at the same time as PPM trainer signal input.

**Comment by rwijnhov** [comment]
I agree totaly

**Comment by jasc76** [comment]
Would be handy for head trackers...

**Comment by rwijnhov** [comment]
Can we pls have this feature? Should be really easy to implement?

**Comment by rwijnhov** [comment]
I still very much want this feature.

**Comment by RealTadango** [comment]
Still needed

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/3e3494bf-1a80-44ee-8ef3-442381112f54)

**Comment by RealTadango** [comment]
@bsongis-frsky i tried this on my new X20RS but it is not working. The output is not activated. Can you check with a X20RS?
