### ISSUE TITLE
x18 internal nand storage

### ISSUE THREAD

**Issue by shanebiffin** [FrSkyRC/ETHOS-Feedback-Community#2478]
Im new to this radio and want to put a lua script into the "scripts" section of the internal storage,but their is no scripts section on my radio,only models,audio,radio bin etc.I believe their should also be logs,but also doesnt appear ? Can i download something to get all the pieces together?

**Comment by mawzthefinn** [comment]
You can simply create a new folder named scripts, from the drive window that pops up when you connect the radio to your computer.

Logs will be automatically created when logging is turned on
