### ISSUE TITLE
Allow integer value entry in LSW

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2479]
As suggested by mikedkelly on rcg, allow integer value entry for X in LSW‘s so that LSW’s can be set up to detect Lua Sensors giving discrete integer values. For example, the Lua Flightmode sensor from Ardupilot passes int values between 1 and 25.

**Comment by bsongis-frsky** [comment]
Which function for the LS?

**Comment by lthole** [comment]
For the A = X function

**Comment by bsongis-frsky** [comment]
Current behavior

![image](https://user-images.githubusercontent.com/50834778/223692235-68334153-8696-47bb-af59-bac5aa6ee17f.png)

![image](https://user-images.githubusercontent.com/50834778/223692257-2eb35faf-afaf-465b-a622-a7b95d943fdb.png)

**Comment by bsongis-frsky** [comment]
Starting with next nightlies. Lua source has 1 decimal.

![image](https://user-images.githubusercontent.com/50834778/223702964-464b6142-7b5e-4323-b422-3dd975ead1cd.png)

![image](https://user-images.githubusercontent.com/50834778/223702995-cd469e0c-9c85-4d10-8827-25682a7f3267.png)

![image](https://user-images.githubusercontent.com/50834778/223703034-2d9979f0-da16-445c-9016-cc8f904208a5.png)

**Comment by bsongis-frsky** [comment]
Starting with next nightlies (Lua Source has 0 decimals, and no unit): 

![image](https://user-images.githubusercontent.com/50834778/223703400-9d15d58b-678b-4f26-bcbd-8204de28f565.png)

![image](https://user-images.githubusercontent.com/50834778/223703424-552e29fb-9b14-4f47-8139-c9bea47d05a2.png)

![image](https://user-images.githubusercontent.com/50834778/223703452-b6545189-8d8f-4f22-aae6-680a76613cfc.png)
