### ISSUE TITLE
Cross Trim - does not work on throttle channel

### ISSUE THREAD

**Issue by leckert123** [FrSkyRC/ETHOS-Feedback-Community#248]
BUG in Cross Trims

Radio: X10S with ISRM
FW: Radio 1.06, RX: ACCESS 2.1.7 on RX6R

I set up a simple 4 channel Kaos 40.

1. With normal trim configuration, all (4) trims (A, E, T, R) work fine. All the surfaces and idle trim work fine. The Output screen verifies the change in uSec output.
2. With cross trims set-up, A, E, R work fine on the surfaces and Output screen. However, Throttle idle trim does not respond, and the Output screen show zero change in the uSec output as well.
3. I made zero other changes. I can repeatedly turn this issue on/off by changing to and from cross trims.

Note: I did not check this functionality on an aircraft when cross-trims were first implemented, so I don't know if it ever worked, or if the latest code broke it. The throttle servo is reversed (or "inverted" in Ethos-speak) but so is the elevator servo, which cross-trims just fine.

Cross trims are useless at the moment since idle trim cannot be set.

**Comment by mawzthefinn** [comment]
Just tested this issue and it is resolved.

**Comment by mawzthefinn** [comment]
Closing this issue as it is resolved.
