### ISSUE TITLE
SCALE function in the telemetry sensor surface

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#2480]
Hello FrSky Ethos Team,
Is it possible for Ethos to add a new function called SCALE to the telemetry sensor interface (above OFFSET), especially for the DIY sensors?
The background is the transmission of the parameters as integers and not as decimals. A function with Scale could divide or multiply the values ​​received using the SCALE function.
For example: 1/1000, 1/100, 1/10, 1 , 10/1, 100/1 to 1000/1
Greetings to the entire development team.

**Comment by mawzthefinn** [comment]
This is a duplicate of #955 Please continue discussion under that issue

The ratio setting is the setting you want added.
