### ISSUE TITLE
Reset "vertical speed"

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2485]
I have a widget value "vertical speed"
Vertical speed reset in special functions via the switch does not work. Probably a bug. (v 1.4.7, v 1.5.0)

**Comment by bsongis-frsky** [comment]
It willl reset, but as soon as your sensor will send a new value, your widget will again show this value

**Comment by jurajjurej** [comment]
Well thank you. I just don't get 0 m/s.
But 0.02 m/s is probably normal.

**Comment by bsongis-frsky** [comment]
Yes it is, a better accuracy will be difficult to achieve (and it doesn't come from Ethos but the sensor itself)
