### ISSUE TITLE
3 positions switches on TWIN XLITE

### ISSUE THREAD

**Issue by floflolapin** [FrSkyRC/ETHOS-Feedback-Community#2488]
Hi,
I would like to change SC and SD switches on a TWIN XliteS for some 3 postitions switches.

But the option isn't available in the firmware.
Would it be possible to change that?

Thanks
Florian

**Comment by bsongis-frsky** [comment]
The radio would miss a pin for those switches, 3-pos switches need 3 pins when 2-pos need 2

**Comment by floflolapin** [comment]
Are you sure it's the case?
The switches are soldered to a separate board like the original xlite was.
And this one had 3 pins for each switch so I was able to change them for 3 pos switches.
Isn't it the same for the Twin?
