### ISSUE TITLE
Ethos Suite Image Tool: Lockup when folder doesn't exist

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#2489]
While not something most users are likely to experience often, I think this is an area that could see a small change to improve functionality. 
 Basically, if you had a folder that you set the Image Tool to export to once converting was done, and at some point later you delete that folder, if you try to convert images later on it does not detect that the folder isn't there, and after pressing convert it just hangs and sits there, never completing because the folder it's trying to export to no longer exists.  The only way to bypass it is by closing the program and reopening.

As far as a solution, I believe the easiest solution would be that if Suite detects the folder it was previously set to is no longer available, it simply resets and has no selection, requiring you to make a new folder selection before allowing you to press Convert.  This check to see if the folder exists could occur on program start, or upon clicking on the Image Tool tab.

**Comment by Wolepo** [comment]
Or issues a message that the folder no longer exists.
