### ISSUE TITLE
Binding procedure (ACCST)

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#249]
Please note, this is my observations for ACCST. Some may also be applicable to ACCESS, though I have not bound an ACCESS receiver yet, so can't say for sure.

The current process is that you click the bind button. The transmitter says "binding" and you wait. You have to notice the change on the receiver to _OK_ the binding. Is there any way for the transmitter to detect when a bind is successful and automatically exit the binding sequence and show Bind Successful? This may have to entail a periodic fetch of telemetry sensors , I'm not sure. But there must be some way for the transmitter to know that a link has been established. I think it would be a really cool and helpful feature.

**Comment by bsongis-frsky** [comment]
ACCESS does it the way you describe

**Comment by MrD-RC** [comment]
What about ACCST? That was the main target of the issue.

**Comment by bsongis-frsky** [comment]
ACCST is old now, there is no plan to add new features to ACCST!

**Comment by MrD-RC** [comment]
Of course, if ACCST needed updating to do this, it wouldn't warrant it. I was just wondering if the binding process could be nicer.

I agree it's sort of old. But it is still a very widely used protocol. So I hope FrSky continue to support those pilots for a long time to come.

**Comment by bsongis-frsky** [comment]
Of course ACCST is supported, but no new feature will be added, there is already enough work with ACCESS
