### ISSUE TITLE
LSW doesn't respect LUA source unit [sec]

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2490]
I have a LUA source which has a unit of [sec].
When using it in a LSW, Ethos uses the [%] instead of the source unit in the `Value` field.

Problems are:
- displayed unit is wrong
- precision cannot be set. I can't set Value to be `0.5` for example
- comparison also does not work properly:
  - using `A = 0` and Value set to `0` it actually makes the LSW on with values below 0.5 (but non-zero)
  - using `A > X` and Value set to `0` it makes switch off with values below 0.5

![image](https://user-images.githubusercontent.com/42830563/224272449-25a8cf9c-4654-4e33-b3d6-56b7bf1a765d.png)

![image](https://user-images.githubusercontent.com/42830563/224272515-0a6fc7a1-487f-4402-93fb-5a8c3ec862de.png)

![image](https://user-images.githubusercontent.com/42830563/224272564-189b7bc8-590d-45dd-a8ba-163e9d0f17e6.png)

**Comment by bsongis-frsky** [comment]
Please check 1.5.0 because I have fixed this issue already there

**Comment by azaz44** [comment]
Oh, we have simulators in the nightly - great 👍 Yes, tested - issue fixed there.

**Comment by bsongis-frsky** [comment]
Also the decimals are taken into account

**Comment by azaz44** [comment]
> Also the decimals are taken into account

Yes I saw, I could set to a 100th of a second.
