### ISSUE TITLE
[1.5 nightly] Value of VAR can exceed valid range

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2491]
Steps to reproduce

1. Create a VAR, range -50% to +50%, Repurpose Elevator Trim (Always On)
2. Apply trim continuously

_Expected_: VAR value should be constrained to range -50% to +50%
_Actual_: VAR value can exceed range.

X20
1.5 nightly #a26b0d3f

**Comment by bsongis-frsky** [comment]
Thanks for removing the extra comment, I think it would have been difficult to do!

**Comment by bsongis-frsky** [comment]
Fixed in next nightlies
