### ISSUE TITLE
1.5.0 nightly for Horus 12S

### ISSUE THREAD

**Issue by Habasek** [FrSkyRC/ETHOS-Feedback-Community#2493]
HI, will 1.5.0 nightly releases for Horus 12S be available soon?

**Comment by KevinFairgrieve** [comment]
I asked the same a little while ago. See issue #2409 
As I suspected it would have been a lot of work. Would still like to be able to test on my X12S leaving my X20 for flying.

**Comment by mawzthefinn** [comment]
Unfortunately the same answer still applies, 1.5.0 Nightlies for the Horus radios are not planned at this time
