### ISSUE TITLE
TW-XLITES 1.4.7 internal Erls telemetry issue 

### ISSUE THREAD

**Issue by xbutz** [FrSkyRC/ETHOS-Feedback-Community#2495]
Hello

I have successfully bound my TW-XliteS with the Betafpv Elrs lite receiver v2.4.
Telemetry is enabled in Betaflight and everything works so far .

Unfortunately, only 10 sensor data are found. 
1RSSI 2RSSI Lq ect.
Why are no voltage sensors found? The Rssi display at the top right of the display also does not work. 

Best regards

**Comment by mawzthefinn** [comment]
The ELRS compatibility mode on the TWIN radios and modules is limited in features, including telemetry.

**Comment by xbutz** [comment]
thanks for the answer... I almost thought so
