### ISSUE TITLE
Tandem X20s grafic telemetri rssi 900M

### ISSUE THREAD

**Issue by osnimette** [FrSkyRC/ETHOS-Feedback-Community#2496]
hello

I'm using a graphic type screen with a telemetry source from rssi 900m, however when I turn off the TD R10 the graphic is in full, not showing the loss of signal, since the 2.4 works perfectly. Is there anything to fix this?

att. Osni.

**Comment by mawzthefinn** [comment]
Just tested on mine and cannot duplicate. The 900M drops from full to none as soon as the loss of telemetry registers.

2.4G does decline, but I'm so close to the receiver that a decline in 900M signal strength would not be noticed before it clears completely

**Comment by bsongis-frsky** [comment]
All modules / receivers are up to date? Do you use the TD Mode? Some screenshots?

**Comment by osnimette** [comment]
Yes, all in the latest version, radio and receiver.

https://user-images.githubusercontent.com/127549283/225970976-e0b8b878-e6e1-4c46-a7a8-006b0c1442dd.mp4

**Comment by mawzthefinn** [comment]
Two notes on that.

1. 2.4G is not working properly. It dropped a bit but did not zero.
2. The graph is still graphing the value recorded, if you check telemetry, the value would be red with the last received value reported. The RSSI indicators on the top bar are reporting correctly.

**Comment by osnimette** [comment]
Yep, that's right, I hadn't noticed.
