### ISSUE TITLE
Emergency mode with 1.5.0 nightly

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2497]
I used the suite to download and install the i18n files, soundpack and manually copied the system bitmaps from github. I then flashed the firmware to 1.5.0. 
This all appeared to work.
Ethos showed as 1.5.0 on the Tx.
I went into Mixers, selected a Var mixer to Edit
All the weights were numbers (selected by switch SG position). 
I selected one and selected Use a source. I then seleted Var.
The tx immediately went into Emergency mode.
I repeated and exactly the same happened.
I've restored back to 1.4.7.

Maybe I got something wrong with the install of 1.5.0? Maybe worth a check in case not. (See my next comment which suggests it wasn't my install which was the problem.)

Thanks

**Comment by Jedsters** [comment]
I've just tried similar with the 1.5.0 simulator with a basic gider created using the wizard - 2 ail, 2 flap, traditional tail.
I tried editing the Ail mixer, changing the weight to a source, selected Var and the sim crashed.

**Comment by bsongis-frsky** [comment]
It should be fixed now
