### ISSUE TITLE
x18发射机配置tdr10通道1为sbus out ，px4飞控无法识别

### ISSUE THREAD

**Issue by tonight123** [FrSkyRC/ETHOS-Feedback-Community#2498]
你好，我用x18配置tdr10对频，配置混控输出正常，pwm模式下10个引脚都工作正常，但是pin1配置为sbus out，px4飞控无法识别。请问是固件问题么

**Comment by koakumaping** [comment]
老外看不懂中文哦

**Comment by FrSky-GX** [comment]
还要检查接收机SBUS输出是否被配置成SBUS-24模式  市面上的设备一般都不兼容  需要配成SBUS-16模式

**Comment by tonight123** [comment]
要么协议输出和标准有出入，要么硬件没加反向器。

**Comment by bsongis-frsky** [comment]
everything good? it's difficult for me to understand ;)
