### ISSUE TITLE
Switching off the transmitter while connected to a receiver

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#250]
The current flow is:
- Hold the power button
- A warning is spoken that a receiver is connected
- The transmitter powers down anyway

What I'd like to see happen is:
- Hold the power button
- A warning is spoken that a receiver is connected
- Once the 4 second hold is complete, a box is presented on screen with the options to cancel shutdown or shutdown anyway. You can also ignore the box and leave it on screen
- If you click cancel, the radio returns to normal operation
- If you click shutdown anyway, the radio completes shutting down
- If you remove the battery from the model while the box is on screen, the radio completes shutting down

With OTX transmitters, I find it really useful to shut down the radio, leave it on the warning screen, then proceed to fetch the model and pull the battery. As it is, just shutting down with a connected receiver is pretty bad. It would cause the receiver to go in to failsafe; which on some flight controller setups could start the model trying to return home.

**Comment by loetefix** [comment]
+1

**Comment by jreis1** [comment]
yup! I've also missed this !
+1
