### ISSUE TITLE
Basic configuration models area

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#2500]
Hello, for new ethos users i suggest to build a little area for external contributors with the commercial models configuration.
Is not for the cliassical 4chanells models but for gliders or big models.
A simple txt document with the Flight modes, mixer, logic swithces and special functions configuration and suggestion to use sensors etc.

**Comment by mawzthefinn** [comment]
External contributors can share model files on https://ethos.frsky-rc.com/

Users can then download anything they want or need from there.
