### ISSUE TITLE
problem with function storage.write

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#2501]
Hello Bertrand,
I have a problem when saving configuration data with the function storage.write("string", sw_position[i][3]).
I try to write an identifier for each switch of the X20, but this fails, up to a certain point it works without any problems, then the memory seems to run out, can that be?
num_switch_pos = 50
for i=0,num_switch_pos,1 do
storage.write("string", sw_position[i][3])
end
Greetings Benno
![write error](https://user-images.githubusercontent.com/97786547/224942788-04d4020f-2e92-4066-b154-173b916587bf.png)

**Comment by strgaltdel** [comment]
Hi Benno,
personally i've written much more then 8 parameters into a config,
so i wouldn't assume there is any mem / cache problem.

Shure your identifier doesn't contain any "problematic" character which isn't handled correctly, did you try another "simple text" ?

greetings
Udo

**Comment by Benno00** [comment]
Hello Udo,
the data is ok, but more than 100 entries are written,
is there a maximum?
Greetings Benno

**Comment by strgaltdel** [comment]
"the data is ok, but more than 100 entries are written,
is there a maximum?"

maybe 128 ?

.. Let's wait for Bertrand

**Comment by bsongis-frsky** [comment]
What are you trying to save? Widget data?

**Comment by bsongis-frsky** [comment]
Today only 256 bytes are allowed

**Comment by Benno00** [comment]
Hello Bertrand,

yes widget.data, 256 bytes ok that explains it.
I have now solved it with one file.
So it can be closed.

Greetings Benno

**Comment by Benno00** [comment]
256 bytes ok that explains it.
