### ISSUE TITLE
Sicurezza rx SR10

### ISSUE THREAD

**Issue by LProia** [FrSkyRC/ETHOS-Feedback-Community#2502]
Buongiorno,
Per aumentare la sicurezza è possibile lasciare disattivato per default da firmware il modo stabile alle RX Stab.
Un mio amico al campo ha distrutto l'aereo al decollo perché inavvertitamente ha montato una RX Stab, senza fare la calibrazione.
Sarebbe anche opportuno se possibile avere un feedback telemetrico quando il modo stabile è inserito.
Grazie

**Comment by carlogianneschi** [comment]
Ti rispondo per il feedback telemetrico:
Devi creare una Special Function collegata allo stesso interruttore che usi per attivare la stabilizzazione -> Play Track -> il suono che desideri.
Sarebbe meglio anche attivare la checklist con le corrette posizioni degli interruttori e dei Pot o slider che regolano la quantità di stabilizzazione
Per quanto riguarda il tuo amico... ma vale per tutti, quando si utilizzano riceventi particolari come quelle stabilizzate, le prove a terra sono obbligatorie, non necessarie o opzionali.
Sorry for all non Italian people but for me is easy reply in the same language.

**Comment by bsongis-frsky** [comment]
English please, or write in a italian forum for questions?

**Comment by mgsanna** [comment]
And only for your information : @LProia  this is not a forum, where you can say thing just like sitting in a bar with friends... here you can open ticket and issue for being solved by dev team.... it's not difficult to understand...... and last but not least there is included in any rx a instruction doc that is there for learning how to use a product and there is also a free 300 pages translated manual that you can read, study or use to ignite the stove or use as igienic paper... before posting. Thank you

per @LProia  guarda che questo non è un forum dove ognuno scrive ciò che gli pare, è una repository dove si aprono segnalazioni per il team di sviluppo, poi riguardo ai "crash" degli amici al campo esiste una documentazione allegata con ogni rx oltre che un manuale di oltre 300 pagine tradotto in Italiano.... dal sottoscritto, da leggere, studiare..... poi alla peggio ci si puo pure accendere la stufa o usarlo come carta igienica.....
