### ISSUE TITLE
swasplate mixer shows wrong icon / is mixinig wrong

### ISSUE THREAD

**Issue by LuHaGH** [FrSkyRC/ETHOS-Feedback-Community#2508]
The Icons and Mixes of H-3 120deg and HR-3 120deg are not OK. One is a 140deg Mixer and Icon.

![221198975-97b94745-8df3-4a9d-8e1c-7a958d6302c4](https://user-images.githubusercontent.com/93262335/225591484-0a7d20bf-fc27-4965-974e-75184a49a843.jpg)

![221198980-5ee70ce0-b27d-4ebe-8276-0c7aa339f637](https://user-images.githubusercontent.com/93262335/225591589-05c75290-b255-42d1-b770-639c34805059.jpg)

And there is an error in mixing that cloud cause crashes.

**Comment by LuHaGH** [comment]
The problem is still up to date.

**Comment by LuHaGH** [comment]
The problem is still up to date! It is ridiculous that is it still not fixed!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/39604090-7f79-48c6-af20-a71f7cf484d4)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1b4c6d95-2ef1-4302-a870-7147dc23cf67)

**Comment by LuHaGH** [comment]
Name and image is OK now. The mixing I have to check at the simulator or in Hardware.
