### ISSUE TITLE
Frsky´s Trio Control with ACCESS receivers

### ISSUE THREAD

**Issue by Devil-67** [FrSkyRC/ETHOS-Feedback-Community#251]
Adding RSSI, VFR and RxBt from each connected receiver in redundancy mode.
Important to determine a good antenna installation under difficult conditions in complex, expensive models.
Like it, Trio Control is just a grandiose name and useless
And today it is simply part of it, other manufacturers even transfer the quality of each individual antenna.
Frsky would like to stand out from the competition but is far away.

**Comment by centertrim** [comment]
Agreed on all points.  I want every bit of information available on every piece of the RF link.  I can then setup my own logical switches to alarm me when any part of the link is not functioning properly for more than a few seconds, that way I can investigate and fix the issue.  Redundancy is no good if you can’t be 100% sure it work when you need it to.

I especially agree with your point on reporting the RSSI for the diversity antennas on each receiver.  Ideally the receiver should report back the overall RSSI, and then a pair of RSSI1 / RSSI2 values that give the values for each antenna.  Even if these were sent at slower update rates they would be useful for verifying the integrity of the antenna connections as well as optimizing antenna placement.

**Comment by bsongis-frsky** [comment]
This repos is rather for Ethos issues ;)

**Comment by Devil-67** [comment]
Concerns ethos

**Comment by bsongis-frsky** [comment]
No :) But I have forwarded to the right team!

**Comment by Devil-67** [comment]
Ok and thanks Bertrand ;)

gives the other right team then also answer here or shares the solution ?

**Comment by bsongis-frsky** [comment]
We discussed a possible solution. In theory it should work, but it needs some time to be implemented and tested on RF side. On Ethos the design is ready for this feature, we have other topics to improve anyhow...

**Comment by Devil-67** [comment]
That sounds good so far, only that it takes a long time is not so good.
But I still thank you for your commitment that I appreciate.

**Comment by mawzthefinn** [comment]
This is with the RF team for now. Will close off as 'Not an ETHOS issue' if there is no further discussion.

**Comment by mawzthefinn** [comment]
Closing as per last comment
