### ISSUE TITLE
1.5.0 VARS should include LSW in Actions and FM in Values

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2510]
Forgive me if I'm misunderstanding how the new VARs are intended to work.

Similarly VALUES can have a physical switch to select them, but not a FM. This seems odd given that very often (but not always) a FM is selected from a physical switch. So I could choose a VAR value for my Sport, Normal and Thermal FM (all on SA), however not for Landing which is implemented when the throttle is less than 90%. 

Unless there is a particular reason the above has been omitted?

Thanks

**Comment by strgaltdel** [comment]
sorry,
i don't see your point.

did you really tried the xVars on the sim/your tx ?

`Currently it seems that VARs can only use trim positions, FSW or physical switches e.g. SI/SJ to increase / decrease one value but not LSW i.e. a combination of physical switches `

i do see gvars etc not only in the value, but even in the action section.

**Comment by Jedsters** [comment]
Apologies! That's what happens when you create a model from scratch - of course there are no LSW so not having LSW as an option makes sense. I've removed that from the issue.

I notice that FM is also available, once you have created more than one FM! Again, that makes sense...

Thanks.
