### ISSUE TITLE
1.5.0 Wizard Channel Assignment options not honoured

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2511]
In 1.5.0 I use the Wizard (on the Sim) to create a Glider, 2xAil, 2xFlap, Traditional tail.
I change the channel assignment to 
Ail1 Ch1
Ail2 Ch2
Ele Ch3
Rud Ch4
Flaps1 Ch5
Flaps2 Ch6

![image](https://user-images.githubusercontent.com/96293240/225688638-c375e029-4170-4b02-975e-db02be1fcdbd.png)

![image](https://user-images.githubusercontent.com/96293240/225688871-34c5f233-f2e4-441b-be0e-011abff359ec.png)

I then click on next (bottom right arrow)

![image](https://user-images.githubusercontent.com/96293240/225689121-4904f496-741a-480b-943a-c345beafd187.png)

and then back (bottom left arrow) 

and the channels I entered have been ignored showing me the default assignment

![image](https://user-images.githubusercontent.com/96293240/225689778-ae803e03-6c7f-46ec-8ead-d63ef4eb7695.png)

If I do assign a model name etc. and then look at the mixers then this also shows the default channel assignment has been used. 

(I'm assuming the same applies on the tx rather than the sim but haven't checked.)
Thanks

**Comment by mawzthefinn** [comment]
Fixed in latest nightly, at least on the X20
