### ISSUE TITLE
Mixer issue firmware 1.47 for Xlites

### ISSUE THREAD

**Issue by Mcrocknz** [FrSkyRC/ETHOS-Feedback-Community#2514]
![Ethos](https://user-images.githubusercontent.com/19835226/225770976-d8a6784e-5685-4c11-9da0-da756b541387.PNG)

When I try do do a mix in the mixer .. the sticks dialog keeps reporting the original stick mapping and not the actual mix which is some what frustrating ..

**Comment by mawzthefinn** [comment]
More information please? Screenshot of what you are seeing?

**Comment by mawzthefinn** [comment]
No information provided, closing as issue not defined
