### ISSUE TITLE
Sensor conflict 

### ISSUE THREAD

**Issue by Fanman1961** [FrSkyRC/ETHOS-Feedback-Community#2515]
I just updated the X20 and uploaded firmware to the sr-10 receivers both now say sensor conflict they will not operate at all I checked all the other receivers I have didn't update their firmware on any of the receivers and they work all just fine

**Comment by Fanman1961** [comment]
I updated the radios using ethosuite to the latest version 1.47 I believe only after I flashed new firmware to the sr-10 pro receivers did this happen none of my other receivers have this problem and I did not update any of the firmware on those receivers either

**Comment by yak-54** [comment]
are you using 2  lipo sensors ?

**Comment by Fanman1961** [comment]
No. I completely took the receiver out of the jet re registered re bound it
still nothing. Try to even configure the stabilization couldn't even do that

**Comment by strgaltdel** [comment]
Sounds a bit like the RX firmware got messed up.
Would try flashing and rebinding with a newly downloaded firmware file

**Comment by Fanman1961** [comment]
Yeah that's my assumption I reflashed firmware three different times with
three different files and still nothing that's why I'm wondering what is
going on I don't believe I have two bad sr-10 Pro receivers but I guess it
may be possible

**Comment by strgaltdel** [comment]
but you are able to bind and rssi is showing a value?

then i would assume a kind of misconfiguration.

dont have experience via ota configuration,
typically i'm using stk sticks,
my procedure roughly would be

- check if you are running sport or fport on your rx, set sport 
- connect to stk and config sr without stab functionality, 
- check if its running
- if yes, reconfig to stab functionality & process acc calibration (if no you really have serious problems)
- process self check (i guess without this you dont get any servo deflection)

**Comment by Fanman1961** [comment]
Thanks to everybody from all the help it steered me in the right direction believe it or not one of the ribbons inside the the receiver came loose it happened when I was trying to get it off the velcro then it came apart and I didn't realize I pulled the ribbon and but thanks for everybody I knew it had to be the receiver and so I took it to a buddy he looked at it he does electronics and he showed me what was up and it's fixed and good to go
