### ISSUE TITLE
SR6 calibration fails

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2516]
X20S
Ethos 1.4.7 FCC
TDISRM 2.2.2
Access 2.1.12 on SR6

SxR calibration gets stuck on first step and will not continue no matter what.
![20230317_091230](https://user-images.githubusercontent.com/8968780/225838094-1f9b8d8b-8564-4317-823a-fc9d32a9ce48.jpg)
![20230317_091223](https://user-images.githubusercontent.com/8968780/225838098-bd4af9bd-5718-40d8-9bfb-c43f3631794d.jpg)

**Comment by i3dm** [comment]
anything at all about this issue?

**Comment by mawzthefinn** [comment]
Looks like a bad SR6. Had a couple users report the same thing elsewhere, it was solved by replacing the SR6.

**Comment by mawzthefinn** [comment]
Closing this off, It's bad hardware, not ETHOS. 

Seen now on a handful of SR6's and a couple of SR8 Pro's and SR10 Pro's. Hardware replacement solves every time.

**Comment by i3dm** [comment]
i dont think so. this never occured pre ethos

**Comment by mawzthefinn** [comment]
Did the same receiver calibrate on OTX? 

Because it all seems tied to a handful of failures on what looks like the last batch of Archer SR's produced. It didn't happen on ETHOS either with older SR's. The failures are all tied to SR's purchased in the last 6 months or so.

**Comment by i3dm** [comment]
ill have to check otx. cant atm.
mine is much older than 6 monyhs though.
