### ISSUE TITLE
S6R setup failled

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#252]
my first model with s8r accst-2.1.0 and ethos 1.0.5 the gyro works and could also be controlled via channel 10 and channel 12.
the next day update ethos 1.0.6 I had to change the switch so that the gyro works properly again. is ok because this has been changed.
today new model created with s6r and ethos 1.0.6 the gyro is always on. is not possibility to control the gyro via channels 10 and 12
then i copied my first model with s8r and bind the new model with the s6r and the gyro works perfectly again.
I hope I was able to explain the problem correctly.

**Comment by bsongis-frsky** [comment]
Right the switch value has changed, -100% and +100% are swapped

**Comment by bsongis-frsky** [comment]
Would you check that your outputs behave the same with your 2 models?

**Comment by bsongis-frsky** [comment]
Also take care that you send 16 channels to your receiver, not 8 (default)!

**Comment by MichaelETHOS** [comment]
oh yes it was my mistake. showed me only 8 channels when i bind. when i switch to channel k1-k16 the gyro is active. thanks for the help and sorry for the failure. issue closed
