### ISSUE TITLE
Convert images to JPG rather than BMP in Ethos Suite

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#2522]
I noticed that the model image loads much faster if I use JPG files instead of Ethos Suite-converted BMPs. Probably due to the larger file size.  This can be quite annoying when loading more model images in the Model select menu. 

Is it possible to add an option to convert to JPG?

**Comment by mawzthefinn** [comment]
BMP's are used because image scaling in ETHOS works properly with them and not with JPG or PNG. JPEG's are faster if optimized, but BMP's can be shared between all ETHOS radios without resizing manually.

**Comment by jurajjurej** [comment]
It makes sense, only radios have slow processors!

**Comment by pstasek** [comment]
> BMP's are used because image scaling in ETHOS works properly with them and not with JPG or PNG. JPEG's are faster if optimized, but BMP's can be shared between all ETHOS radios without resizing manually.

Understood, makes sense. Still, having the possibility to choose would be nice. I'm using Windows Power Toys to resize my model images to fit my XE and X20S instead as the loading speed is more crucial than compatibility with X18 or Horuses which I don't have.

**Comment by jurajjurej** [comment]
Of course. Choosing png, jpg or bmp would be better.

**Comment by jurajjurej** [comment]
Please expand the preset options.
![Screenshot_264](https://user-images.githubusercontent.com/85956904/227119851-6f7b5670-b9e4-4d80-82ba-d00b5675380c.jpg)

**Comment by jasc76** [comment]
+1 for jpg
Ethos Suite could just use the info of radio connected or offer a selection box.
