### ISSUE TITLE
X18SE FCC cannot update to firmware 1.4

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2524]
As per the title, running latest ETHOS Suite and cannot update X18SE to latest 1.4.7. Ant help please?

Thanks

**Comment by salibaj2** [comment]
Ok. Changed PC and update went through. What was happening it was waiting for ejecting disks, although Tx was ejected, and connected again. Do not know what happened there but did not had this problem with same laptop when I updated last time.

**Comment by mawzthefinn** [comment]
Glad you got it sorted, ejecting disks are an endemic issue with both Windows and Mac OS (and not just for Suite)
