### ISSUE TITLE
Changing the main image

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2525]
Using a "special function" one could change my picture on the main screen.
![Screenshot_258](https://user-images.githubusercontent.com/85956904/226293158-5c64e6ff-642a-4337-a7d6-bc8ee5005ea6.jpg)

**Comment by bsongis-frsky** [comment]
Which picture?

**Comment by jurajjurej** [comment]
Image of the model
![Screenshot_259](https://user-images.githubusercontent.com/85956904/226295878-359e52d5-6e09-4f32-80b3-0635dd4434c3.jpg)

**Comment by jurajjurej** [comment]
![Screenshot_260](https://user-images.githubusercontent.com/85956904/226296298-72dba1a0-cf10-4d1b-a70a-55189c2c8632.jpg)

**Comment by jurajjurej** [comment]
For example, the image of my model would change depending on the flight mode.

**Comment by jurajjurej** [comment]
![Uploading extraP.png…]()

**Comment by bsongis-frsky** [comment]
I wonder if it is the right way to do this. I would rather see a Lua script honestly!

**Comment by jurajjurej** [comment]
It could be given as a special function.
The switch would activate the selected image.
