### ISSUE TITLE
LSW Function  |Delta|>X  doesn't work as expected (possibly just 1.5.0)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2526]
I have created a VAR as follows

![image](https://user-images.githubusercontent.com/96293240/226357570-e4a08088-fb0f-4d52-a8bf-c96cfd03314a.png)

which as expected changes by 5% each time SI or SJ is depressed.

I have then created a LSW as follows:

![image](https://user-images.githubusercontent.com/96293240/226358064-02e5d981-16f6-45ae-a277-2f4e5063cfec.png)

![image](https://user-images.githubusercontent.com/96293240/226358174-80a48941-78cd-4d17-a9be-1c005d4f1d33.png)

My assumption was that if Flaperon Wt changes by at least 1% within 100ms then the LSW would trigger. However even though Flaperon Wt is changing by 5% the LSW doesn't trigger. 
If I change Value (X) to 0% then the LSW does trigger. 

Maybe I'm misunderstanding how this is intended to work, but the manual does say 'The condition is True if the change in value 'd' (i.e. delta) of the selected source ‘A’ is greater than or equal to the user defined value 'X', within the 'Check interval'.'  

If I'm honest, I'm not convinced this works correctly in 1.4.7 but it's not so easy to increase a similar value by more than 1% without VARs, but as far as I can tell testing on TRIM Mixer output channels doesn't seem to trigger the switch unless Value X is 0%.

While I'm writing, may I challenge the wording in the manual? This says greater than or equal to, however the sign is simply > i.e. greater than. Also the 'equal to'  bit doesn't make a lot of sense if the value is 0% - if that was the case surely the trigger would be permanently true?

Thanks

**Comment by mawzthefinn** [comment]
Just working through this now.

I assigned a pot as a second weight and it detects correctly. Looks like new value assignments don't detect as delta's.

Note I also found that the Set action is not correctly functioning if you set it with 'Use a Source'
