### ISSUE TITLE
Aileron differential on flying wing / elevons setup

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#2527]
I cannot get aileron differential working properly, I think it might be a bug. As I lower/increase the amount to maximum in either direction one aileron is not moving at all, neither up or down with full left or right aileron input when only the down throw should be changing.

**Comment by mawzthefinn** [comment]
Please provide a model file so we can test. 

As I noted on RCGroups, I have tested and cannot duplicate what you are seeing

**Comment by miggy1952** [comment]
m60.bin

I provided the model file in RC groups yesterday too

**Comment by mawzthefinn** [comment]
My apologies, I missed that post. I have it now and am checking it

**Comment by miggy1952** [comment]
Many thanks for your help and insight

**Comment by mawzthefinn** [comment]
It's not working because no delta mixing is configured in the radio. It appears you set delta mixing in the receiver.

As configured, differential is not possible because the receiver does not support it. This is not an ETHOS issue but a receiver limitation.
