### ISSUE TITLE
LSW Logical fn Values to not allow VARS with 1.5.0 which seems an omission?

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2528]
I have created a VAR which can be adjusted via e.g. SI and SJ. However I'd also like a SF to play the value of the VAR when I start pressing SI/SJ and when I stop pressing SI/SJ (i.e. initial and final values).

To do this I'd create a LSW with an OR fn, Value1 of EDGE the VAR name and Value2 of EDGE NOT the VAR name.

A SF could then be triggered when this LSW is true to play the VAR value (which is possible). 

It seems an omission that VARS can't be included in VALUEx on Logical LSW.

Is there a reason this has not been included? If not, perhaps it could be included?
(It is not lost on me that similar for CHANNELs is not included.)

Thanks

**Comment by mawzthefinn** [comment]
VAR's have a value range, not a boolean state, so there's no such thing as an edge of them. 

Edge is for when a boolean value transitions between true and false. This is the same reason Channels don't have them

**Comment by Jedsters** [comment]
Yeah, I get what you're saying, although I suspect you can see why an EDGE to a value (i.e. a change in VALUE) is desirable.

**Comment by mawzthefinn** [comment]
That would be a delta, not an edge in that case. 

You don't want an edge for that or you will end up with hysteresis issues if there's any wiggles in the value.

**Comment by bsongis-frsky** [comment]
You will have to use the Delta function.
