### ISSUE TITLE
1.5.0 lua: initializing sequence of handler changed in comparison to 1.4.6

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2530]
mostly i use the read handler together with the widget environment variables,
so it's defined as 

**local function read(widget)**

of course, widget vars are defined during create
but now i realize that init sequence changed, read handler is  "called" before "create" on boot, which can generate failures.

screenshots on start of sim
same widget,
outputs a value during read handler:

**Ethos 1.4.6:**

![1 4 6](https://user-images.githubusercontent.com/20392683/226626701-f57f442c-60dd-4c00-b692-e42a7e073398.png)

**actual nightly 21.march**

![00be6b99](https://user-images.githubusercontent.com/20392683/226626661-fc8b6d3a-5318-4148-87f3-54109588d5db.png)

[main.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11029013/main.zip)

btw
regarding #2494
closed, but not solved yet !

**Comment by bsongis-frsky** [comment]
You are right. I think it's a side effect. Working on it...
