### ISSUE TITLE
Shortcuts for voice files

### ISSUE THREAD

**Issue by miksterr** [FrSkyRC/ETHOS-Feedback-Community#2532]
Wondering if a mini keyboard like attached could be implemented for the searching of audio files?

Can be a lot of scrolling to say get to the end files. If the below keyboard could be used at the bottom of the page.

Please excuse the very amateur job - hopefully get the idea.
![Screenshot 2023-03-22 at 09 15 43](https://user-images.githubusercontent.com/85661910/226754269-dceb66f7-c8c7-4aae-8892-9305d65d8d31.png)

**Comment by dap35** [comment]
Great idea!  Might keep me from wearing out the rotary dial so quickly.

**Comment by kramgrand** [comment]
Hi. On a much earlier version of Ethos, I can't remember which version. When you were scrolling through the sound files I found that you could swipe the screen and the file names would zoom through more than one page at a time, that saved a lot of clicking on the rotary. I have really missed that feature. It would be great to have a way of getting to the file you want without dialling the rotary to death.

**Comment by jurajjurej** [comment]
Same for image search?
