### ISSUE TITLE
Proposal for enhancement of the future "sequential play of values or speeches"

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#2537]
In RCgroup, Jetflyer posted a preview of the sequencial play to be released in V.1.5
This a great enhancement and have lots of potential uses cases for it.

I suggest to add the possibility to play the sequence one at a time (e.g. by pressing the same switch as many time as the number of "tracks" included in a given sequence.

Examples of two use cases:
a) to play a check list sequence before or after flight
b) to play an IMAC (or other) aerobatic sequence while training and no caller/helper available.

Thanks

**Comment by bsongis-frsky** [comment]
Like this?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8c3e30b4-8af8-495a-b5f2-508b49fc7ffc)

**Comment by Eagleowl1** [comment]
l'idée est qu'à chaque impulsion donnée par un inter, (de préférence SH) seul un pas, d'une séquence préalablement enregistrée, est jouée.
(Aucune interaction avec la télémetrie, seulement lecture de la check list point par point après réception d'une impulsion)
par exemple:

SH+ --> play "décollage"
SH+ --> play "3 boucles tirées"
SH+ --> play " renversement"
...

Même idée pour une check list: (exemple hypothétique)

SH+ --> Play "plein carburant fait"
SH+ --> Play "Allumage ON"
SH+ --> Play "Choke ON"
SH+ --> Play "inter train en position sorti"
SH+ --> Play "Volets sur cran 1"
SH+ --> Play "Etat de vol sur décollage"
...

J'espère que celà clarifie

**Comment by bsongis-frsky** [comment]
Oui c'est exactement ce que je montre dans mon screenshot !

**Comment by Eagleowl1** [comment]
Désolé, je ne suis qu'un utilisateur qui ne comprend pas tout.

J'utilise "sequence caller.lua" qui fonctionne très bien pour moi.

https://www.rcgroups.com/forums/showthread.php?4018791-FrSky-ETHOS-Lua-Script-Programming/page16#post48540783

Pour revenir au sujet: 
Est-ce que la ligne 5 pourrait être: Play "train sorti" ? 
ou faut-il copier les pas 2 et 3 pour jouer la prochaine annonce?

Dans le premier cas tout est parfait.
Dans le second j'avais en tête:
Dans l'écran principal de définition de la séquence:
-  sélection: séquence "pas par pas" ou "continue"
- définition de l'inter d'avance d'un pas de séquence.
- définition de l'inter de reset (repart au début) pourrait être le même mais actif durant 1 Sec.
- définition de l'inter pas -1
- liste à jouer pas à pas.

Je n'ai aucune connaissance en programation et ne peut pas estimer l'effort requis. Ceci reste une suggestion.
Encore navré de ne pas savoir exprimer ma pensée en termes plus professionnel.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ca916ece-71f6-493b-a314-d5ed227c536c)

**Comment by pstasek** [comment]
I didn't find the Wait condition in the Sequence in 1.5.0 RC1. Has it been omitted? It's essential to be able to use the Play Audio sequence as maneuver calling on pattern flying or checklist confirmation on pre-flight.
