### ISSUE TITLE
delay when switching flight modes

### ISSUE THREAD

**Issue by victorllarena** [FrSkyRC/ETHOS-Feedback-Community#2538]
For helicopter flights, in the pitch and in the engine, there should be a delay to smooth the sudden change from one mode to another flight mode, delay when changing flight modes

**Comment by bsongis-frsky** [comment]
You can use a logic switch with a delay, no?

**Comment by mawzthefinn** [comment]
Use fade in/fade out on the flight modes to get a delay when switching transmitter flight modes. This will smooth the transitions of all values selected directly by the flight mode.

**Comment by victorllarena** [comment]
thank you very much, i will look at it

**Comment by mawzthefinn** [comment]
Answer provided, so closing off
