### ISSUE TITLE
lua cosmetics: erase debug code for some telemetry readouts

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2540]
in case i read GPS Speed some debug Code is printed to the console and fills the window

![image](https://user-images.githubusercontent.com/20392683/227477683-a24eeba0-19d1-486e-8616-b1630fbfc7fd.png)

at least prio zero on scale from 1..10 (-;

**Comment by bsongis-frsky** [comment]
Done
