### ISSUE TITLE
Audio setup with 1.5.0 seems odd

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2542]
I have downloaded the latest Audio pack using the Suite nightly (which now seems to work - thanks), so have
/audio/en/gb/system/
/audio/en/system/
/audio/en/us/system/

all of which (at first glance) contain files with the same names (as expected), but the 1st one is GB accent and the last 2 with US accent (as expected).

If I set Voice1 to system Voice2,3 to GB then I appear to loose all voices
If I set Voice1,2,3 to GB then I get GB voices, however, if I then setup a SF Play Sequence with a Voice of Voice1 - GB, then the Play File list of files is empty!

I'm not clear on how this is supposed to be setup, but something doesn't appear to be right. Surely I should be able to select a GB file of low-battery.wav etc.?
It feels like the lowest /system/ directory shouldn't be there and the files therein should be in subdirs GB and US?

(Is it possible that my file structure may have become incorrect from when I was copying the audio files manually as the suite wasn't working for a while with this - although it appears that the suite is downloading the directories and correcting things?)

Thanks

**Comment by mawzthefinn** [comment]
Custom audio tracks the voices. If you want to use the GB voice for your custom audio play track, you need to put custom audio files into /audio/en/gb

The voices work both as multiple voices and as multiple sound packs.

**Comment by Jedsters** [comment]
I'm not talking about the custom audio tracks, tracks such as low-battery are supplied in audio/en/gb/system/ 
How should I setup the General Voices to be able to select those in SF Play Tracks?
Thanks

**Comment by mawzthefinn** [comment]
> I'm not talking about the custom audio tracks, tracks such as low-battery are supplied in audio/en/gb/system/
> How should I setup the General Voices to be able to select those in SF Play Tracks?
> Thanks

You can't call System audio (anything in ../system) in ETHOS using Play Track. That's never been supported and has not changed in the nightly.

If you want to use those files with Play track, copy to the voice/audio root directory, just like on 1.4.x and earlier.

**Comment by Jedsters** [comment]
Thanks, it appears at some point all the files I had in the audio root directory have been deleted (not sure if that was me or the Suite at one point).
