### ISSUE TITLE
Helicopter  enhancement

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2548]
Hi all,

I am new to FrSky and ETHOS. So far so good, but I think that helicopter programming can be enhanced. Let's say that we are using a 3-servo swashplate: -

1. Let's say I am flying scale and need -4deg,  6deg and 11deg, but I have -6, 4 and 9 deg. I cannot find a way to offset all 3-servos together so I can increase all range by 2 deg.

2. Adding to the above, lets say that bottom of stick and top of stick is correct, i.e.: - -4 and 11, but mid-stick is off by 2deg, i.e.: - 4 deg. I did not find where or how to change only the mid-point.

3. For gyro gain I added a freemix.  A 3-pos switch will then move along the three points across the curve that will represent the gain. Simple! But, if I opted to make a helicopter with ETHOS, this freemix should be already there, named GYRO. Leave the ability to change name if need be, but I think it will be more professional this way. Same goes for GOVERNOR or banks. In other words, this could be an initial template which can be altered by the end user.

4. Hovering pitch and hovering throttle. I tried to find something on the internet how this can be done, but it is missing. I came across a curve assigned to a pot on the internet, but the method used will alter the whole pitch / throttle range, not just the mid stick. Imagine a 3-point curve, with the pot is required to only change the mid point.

Regarding point 1 and point 2, maybe it can be done servo by servo, but who is jumping ships to join FrSky ETHOS, these should be standard for helis, and be at hand upon switching ON the Tx in helicopter setup.  

Apologies if the above issues has been already mentioned elsewhere in this forum.

Regards

Joe

**Comment by OldGazer** [comment]
#1 Can be solved by adjusting the lengths of the linkages between the servos and the swash plate. 
#2 Can be changed with a Pitch curve.
#3 Can be solved by a Curve on the Gyro channel
#4 Can be solved with Pitch and Throttle curves.

This is how we did it back in the Nitro days when I started flying .60 Miniature Aircraft X-Cells and Schluter Superiors.

**Comment by mawzthefinn** [comment]
#1 as @OldGazer reported, this is a mechanical setup issue. You can use Outputs to work around that, but that can cause issues elsewhere.

For #2 and #4, curves are the right answer. 3 point curves and adjust the midpoint on each curve to get what you want. A trim mixer can also assist with #4 (NB - a trim mixer can output to multiple channels, so it applies a predictable and adjustable offset to the channel centres of those channels)

NB - the addition of VAR's in v1.5.0 will make #2 in particular much easier as you can use a VAR to adjust curve points, and either the adjustor or the VAR itself can be common between multiple curves. 

ETHOS does not pre-populate Gyro mixes for any model type, because the correct setup varies too much. Adding a Free mix and configuring it to match your needs is the correct setup.

**Comment by salibaj2** [comment]
Herman,

Thank you for your response. 

Ok. Drop the GYRO pre populated mixer. I can understand that.

I am aware that with a flybarless controller all settings I am asking for are within the controller. However, as I stated in my first post, if I am setting for instance, a scale VARIO helicopter, which usually use an, if I am not mistaken, H4X, you first centre the servos, then setup linkages mechanically so there are no servo under stress, and then, if I want to alter say HOVERING PITCH or END POINTS, these are done with all 4 servos together, so there is no linkage binding. 

This is an enhancement to the ETHOS. I already tried setting up a model this way, and is very frustrating to remove linkages, especially on models in a fuselage, and the damage you do to a servo and mechanics because of this lack in software, because you cannot say alter a CENTRE value with 10 on 1 servo and then move to the other 3 to change similar values without stressing the servos and mechanics.

Another thing missing, and you can see it in the swash plate selection menu, is the lack of channel numbers beside the swashplate image, I.e. CH1 etc..

So I came with what I have in mind. If only I can write a LUA script then I would not be here asking for this enhancement. However I know writing in BASIC language and I hope that you can understand what I am asking for.

**Comment by salibaj2** [comment]
![Suggested layout](https://user-images.githubusercontent.com/68815554/232250350-4e6e7fea-c9a6-41aa-b154-ebaa287564c3.jpg)

**Comment by salibaj2** [comment]
The above is an idea of what it could be done.

Hover trim: - Where you can change only the hovering position and not the endpoints of all servos together.

Pitch trim: - Where you can trim the pitch in the entire range, i.e.: - if I have for example a range between -6 deg. min. and +8 deg. max, adjusting pitch trim along it's range will go, i.e.: - -4 deg. min. to +10 deg. max.

Hover Trim: - Only CENTRE is adjusted and end points remain same, i.e.: - If min. is -4 deg., hover +4 deg., max +10 deg., adjusting hover trim will leave min. to -4 deg., max. to +10 deg, and hover can be adjusted to +6 deg.

Next post is some code as an idea.

**Comment by salibaj2** [comment]
' Assuming that alll servos are running normal not reversed
 '==================================================================================================
 '*******************
 '* Pitch END point *
 '*******************

 ' If stick is in the up position, and upper yellow bar is pressed: -

  if servo1_rev <> true then
    servo1_max++
  else if servo1_rev = true then
    servo1_max--

  if servo2_rev <> true then
    servo2_max++
  else if servo2_rev = true then
    servo2_max--

  if servo3_rev <> true then
    servo3_max++
  else if servo3_rev = true then
    servo3_max--


  ' If stick is in the down position, and lower yellow bar is pressed: -

  if servo1_rev <> true then
    servo1_min--
  else if servo1_rev = true servo1_min++

  if servo2_rev <> true then
    servo2_min--
  else if servo2_rev = true then
    servo2_min++

  if servo3_rev <> true then
    servo3_min--
  else if servo3_rev = true then
    servo3_min++

 '==================================================================================================
 '**************
 '* Pitch Trim *
 '**************

 ' This is used to trim the entire pitch range; i.e. reduce negative and increase positive

 ' If RED upper bar is pressed: -

 if servo1_rev <> true then
    Servo1_Centre++
    servo1_max++
    servo1_Min++
 else if servo1_rev = true then
       Servo1_Centre--
       servo1_max--
       servo1_Min--

 if servo2_rev <> true then
    Servo2_Centre++
    servo2_max++
    servo2_Min++
 else if servo2_rev = true then
       Servo2_Centre--
       servo2_max--
       servo2_Min--

 if servo3_rev <> true then
    Servo3_Centre++
    servo3_max++
    servo3_Min++
 else if servo3_rev = true then
       Servo3_Centre--
       servo3_max--
       servo3_Min--

 ' If RED lower bar is pressed: -

 if servo1_rev <> true then
    Servo1_Centre--
    servo1_max--
    servo1_Min--
 else if servo1_rev = true then
       Servo1_Centre++
       servo1_max++
       servo1_Min++

 if servo2_rev <> true then
    Servo2_Centre--
    servo2_max--
    servo2_Min--
 else if servo2_rev = true then
       Servo2_Centre++
       servo2_max++
       servo2_Min++

 if servo3_rev <> true then
    Servo3_Centre--
    servo3_max--
    servo3_Min--
 else if servo3_rev = true then
       Servo3_Centre++
       servo3_max++
       servo3_Min++

 '==================================================================================================
 '**************
 '* HOVER TRIM *
 '**************

 ' This is simillar to PITCH TRIM but only the center is affected

 ' If PURPLE upper bar is pressed: -

 if servo1_rev <> true then
    Servo1_Centre++
    servo1_max--
    servo1_Min--
 else if servo1_rev = true then
       Servo1_Centre--
       servo1_max++
       servo1_Min++

 if servo2_rev <> true then
    Servo2_Centre++
    servo2_max--
    servo2_Min--
 else if servo2_rev = true then
       Servo2_Centre--
       servo2_max++
       servo2_Min++

 if servo3_rev <> true then
    Servo3_Centre++
    servo3_max--
    servo3_Min--
 else if servo3_rev = true then
       Servo3_Centre--
       servo3_max++
       servo3_Min++

 ' If PURPLE lower bar is pressed: -

 if servo1_rev <> true then
    Servo1_Centre--
    servo1_max++
    servo1_Min++
 else if servo1_rev = true then
       Servo1_Centre++
       servo1_max--
       servo1_Min--

 if servo2_rev <> true then
    Servo2_Centre--
    servo2_max++
    servo2_Min++
 else if servo2_rev = true then
       Servo2_Centre++
       servo2_max--
       servo2_Min--

 if servo3_rev <> true then
    Servo3_Centre--
    servo3_max++
    servo3_Min++
 else if servo3_rev = true then
       Servo3_Centre++
       servo3_max--
       servo3_Min--

 '==================================================================================================
