### ISSUE TITLE
DIY telemetry help

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2549]
I would like to build some sensors myself, however I do not make use of MCU's listed [here](https://www.rcgroups.com/forums/showpost.php?p=29439177&postcount=1) and neither I use C++ as programing language.

Currently trying S-PORT with an SR10 PRO receiver. I would like the following: -

1. Baud rate
2. What header is sent to request data from sensor
3. Data format from sensor
4. CRC, I cannot get my head around this

Also, I know that I can switch from S-PORT, F-PORT or F-BUS from Tx, but cannot find where to enter to make such changes.

Thank you

Joe

**Comment by mawzthefinn** [comment]
Telemetry protocol is set in Model->RF System->Receiver->Set->Options.

The other info is available from FrSky under NDA if you sign up to the Developers Union. 3rd party documentation for S.Port is on RCGroups in the DIY Forum and Radio forum.

**Comment by RealTadango** [comment]
Check my library: https://www.rcgroups.com/forums/showthread.php?3448129-FrSky-Arduino-sensors-and-new-SPort-library

**Comment by salibaj2** [comment]
Thank you

 

Very kind of you.

 

Regards

 

Joseph
