### ISSUE TITLE
Taranis X9D Plus transmiter don't turn off system!

### ISSUE THREAD

**Issue by letruong6006** [FrSkyRC/ETHOS-Feedback-Community#2550]
hello everybody .i am using taranis X9D plus controller, i have problem to power off the controller but the system can't do that, the screen is always on and off continuously. i have updated to the latest firmware but problem still happens. can you help me to fix the problem? thank all

**Comment by strgaltdel** [comment]
Hi,
this is a place to discuss Ethos OS related issues,

I suspect you have posted here by error,
would recommend to discuss such questions at rcg

regards

**Comment by mawzthefinn** [comment]
Please contact FrSky Support, this Github is for ETHOS and related issues.
