### ISSUE TITLE
Enhancement request for VARs on 1.5.0

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#2553]
Please consider adding a Switch to the Actions of Vars. This would permit the use of the same Category/Member in multiple Vars with independent changes.
Example:
Var1: Actions:
SC↑  Trim LVU   Add(+)  [1]
SC↑  Trim LVD   Subtract(-) [1]

Var2: Actions:
SC↓ Trim LVU   Add(+)  [1]
SC↓ Trim LVD   Subtract(-) [1]

**Comment by mawzthefinn** [comment]
You can do that right now already.

VAR1
SC↑ Repurpose trim trim throttle

VAR2
SC↓ Repurpose trim trim throttle

Or just use a LS of type AND with SC↓ and Trim LVU/D, you don't need two active conditions for one action. 

There is a known bug right now with repeat that is causing repurpose trim to work incorrectly. It will be fixed.
