### ISSUE TITLE
Fading trims cause problems, I believe an option to disable is needed (demonstration)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2554]
I recently opened #2546 which was closed before I had chance to demonstrate the problem. 

I have been through my model  (1.5.0 definition - note some curves are screwy as per my other issue, but I don't believe this is relevant in this case).
[2a2f2b xeg v1.5.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11081448/2a2f2b.xeg.v1.5.zip)
and I believe I have removed all explicit references to FM. FM are selected via LSW and those same LSW are then used to select other VAR values, Mixers etc. etc. to ensure consistency. 

To demonstrate the problem I have created 2 almost identical Mixers (both named Camber), the first outputs to CH7, 8, 2, 1, 5 while the second outputs to CH27, 28, 22, 21, 25. The only difference between the 2 mixers is that the former uses -Trim Throttle for its weight while the latter uses the same weight (20) but converted to a value. 
 
With left stick fully forward (to diable butterly) look at the output channels 2 and 22 and switch between SA middle (FM Normal) and SA down (FM Thermal). You will see that when switching from SA middle to SA down, CH2 jumps from 0% to around -30% before fading back to -15%. By contrast CH22 jumps between 0% and -15% with no fading. 

I can see no way that this can be happening other than CH2 uses the Throttle Mixer as its weight and this is fading. I therefore still believe that we need to be able to disable fading on trims.

I sincerely apologise if I am doing something wrong, but I hope you can understand from the above why it appears to me like fading trim is the problem.

Thanks

**Comment by Jedsters** [comment]
Very many thanks for taking the time to look into that and reply. 
It seems you're saying that really we shouldn't be using any physical trim value for a weight directly, but rather to use the trim switch as input to e.g. a VAR? I guess at least with 1.5.0 this can be different for different FM, with lower levels that would become a right pain. 
Thanks

**Comment by mawzthefinn** [comment]
I'd put it as 'be very careful when you combine multiple levels of abstraction'. That setup would work fine if the source hadn't been abstracted first or if both source and weight adjuster are abstracted. 

And don't use fade unless it's needed, it can be interesting to troubleshoot. The usual fade issue I've seen is with accidentally and briefly getting the input into an undefined state on FM change.

**Comment by Jedsters** [comment]
Thanks, I don't think I'd realised until very recently that the trim was directly fading, I'd assumed fading was only done at the channel level. I'm not sure if it were done that way, that would also avoid the problem.

**Comment by Jedsters** [comment]
Thanks
