### ISSUE TITLE
widget lua only run when it is in active screen

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#2555]
Hello Bertrand,
is there a way to stop lua scripts and only run them when the screen is active? I noticed that all Lua widgets are always started immediately when the transmitter is switched on, although the corresponding widget screen is not active at all, since Lua is then running in the background. Wouldn't it make sense to give luas a way to run these only when they are currently displayed, this should save resources and reduce memory requirements.

Greetings Benno

**Comment by Benno00** [comment]
Hello Udo,

Yes, you are right, I probably didn't express myself correctly.
Each LUA is started once when switched on, if it is stored as a widget for the model, it is also started.
Yes, Paint runs once when the widget is active
Yes, wakeup is carried out if it is stored for the model and repeated approx. every 500ms, but unfortunately also if the widget does not have the active screen, i.e. in the background.
Since I query the switches and pots with a lua swmap, I only need the wakeup as long as the weidget has the active screen. Then it can rest until it has the active screen again.
The current side effect is when the lua runs as an inactive widget in the background or in the foreground, and you e.g. wants to change the model, e.g. the model images are displayed extremely slowly.
If the wakeup is not executed in the lua, these model images are displayed significantly faster.
And yes you are right that we should be careful with expansion ideas. Unfortunately I haven't found a solution for the swmap yet, how I could let the lua rest. But maybe you have a possibility to end the wakeup as long as the widget doesn't have the active screen?
It would be enough for me if wakeup is not executed as long as the widget does not have the current screen.

Greetings Benno

**Comment by bsongis-frsky** [comment]
Perhaps just add a method so you can exit from `wakeup()` very quickly if the widget is not visible on screen

**Comment by bsongis-frsky** [comment]
Look at the gauge widget, here is the `wakeup` function, you could improve it by checking if the widget is visible on screen, like this:

```lua
local function wakeup(widget)
    if not lcd.isVisible() then
        return
    endif
    if widget.source then
        local newValue = widget.source:value()
        if widget.value ~= newValue then
            widget.value = newValue
            lcd.invalidate()
        end
    end
end
```

**Comment by Benno00** [comment]
Hello Bertrand,
that does not work! isVisible doesn't seem to exist.
Thanks anyway.
The error isVisible' is not callabl is reported
  error: /scripts/swmap/main.lua:1122: field 'isVisible' is not callable (a nil value)←[0m

1121 local function wakeup(widget)
1122 if not lcd.isVisible() then
1123 return
1124 end
1125 lcd.invalidate()
1126 end

But I found out that "local function paint(widget)" is not called if the widget is not visible on the screen
that helps me.
Thanks very much

Greetings Benno

**Comment by bsongis-frsky** [comment]
I have set the 1.5.0 milestone!

**Comment by Benno00** [comment]
Hello Bertrand,
Thank you, it's always nice how quickly you respond
Thank you very much
With kind regards
Benno
