### ISSUE TITLE
Flex  Firmware 900mhz get disconnect when go in info sectio 

### ISSUE THREAD

**Issue by munzoorf95** [FrSkyRC/ETHOS-Feedback-Community#2556]
While connected to the Receivers when you go to info section on Tandem X20S. 900mhz gets disconnect from the receiver. 

TANDEM X20S 1.4.7 Flex
TD-ISRM 2.4.4
R9SX 1.3.3 Flex

**Comment by bobojh** [comment]
I have the same problem wth :
Twin X lite S,TW ISRM HW:1.01 FW 1.0.2 EU-LBT Ethos 1.4.7
TW GR6 HW:1.2.0 FW: 1.0.3

**Comment by RealTadango** [comment]
Since telemetry is received over 900Mhz with Tandem i suspect the TX needs to switch to read the info from all receivers.

**Comment by SmartTommy** [comment]
@bobojh ，as @RealTadango  said, when you go to info section, Tx needs to swith to all receicers, so,some times it will lost the rssi. don't worry about that.

**Comment by bobojh** [comment]
OK Thank you.
