### ISSUE TITLE
VARs on X axis of curve behave badly and inconsistently

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2558]
Consider the following Custom (not Easy mode) curve

![image](https://user-images.githubusercontent.com/96293240/228522119-4678d7c2-8ba7-4dc4-8998-89df9637ea09.png)

with VAR1 as point3 X axis

With VAR1 X value of around -6% all is well. 

However as VAR1 X value goes below -50% (i.e. point 2 X axis) this starts to appear odd.

![image](https://user-images.githubusercontent.com/96293240/228523585-279fb3b4-a04b-4f61-ab94-16c09726f093.png)

I'd question whether point3 on the X axis should even be allowed to go below point 2 or above point 4 on the X axis.  I can understand that it may be difficult to prevent this at source (i.e. to stop VAR1 <-50 or >50 in this example), however I feel it would be appropriate to stop this at the curve level.  Of course the downside of doing this is that VAR1 could be -100 and increasing it would initially have no effect until it exceeds in this case -50 etc., but then it would have had no effect when reducing it below -50 either, maybe an alert ping or something would be useful here too?

As above, when VAR1 goes to e.g. -90% you can see that the 3rd leg of the curve continues to follow the trajectory from point 4 to where point 3 would be if it were valid, which doesn't seem desirable given that point 3 is now at an invalid location, i.e. before point2. 

However, things get worse when we increase VAR1, in this case point4 gets ignored!

![image](https://user-images.githubusercontent.com/96293240/228523178-0bf93f30-6217-48d5-912e-118b68727662.png)

The behaviour is inconsistent and I believe undesirable. 

I can see why being able to adjust the X axis for a point via e.g. a variable can be useful, however I believe the bounds of where it can be adjusted to need to be set and enforced so as to not exceed adjacent X axis points. 

Thanks

**Comment by mawzthefinn** [comment]
What you are running into is that the X value of a given point is limited by the X value of the two points on either side. 

Remember, the VAR doesn't know where it is being used, so you cannot bounds limit the VAR based on the Curve, because it doesn't know what those bounds are. You need to either use the range setting in the VAR to set bounds or accept that the VAR value can overrun the limits of where you are using it.

**Comment by Jedsters** [comment]
I agree, but would a pragmatic approach to help the unwary avoid shooting themselves in the foot be to automatically adjust the range settings for a VAR when it is setup in a curve or when a curve containing VARs is adjusted?
Thanks

**Comment by Jedsters** [comment]
Leaving aside that I disagree, I still think that at least the behaviour should be consistent at either end, i.e. either ignore points 2 and 4 in my example or use the trajectory method for points 2 to 3 and 4 to 3.  Unless there is some reason to be inconsistent?
Thanks

**Comment by mawzthefinn** [comment]
The behaviour IS consistent. When there's a conflict in the position of 2 points, the Left-hand point's position is always the limiter and determines what the right-hand point's minimum value can be.

**Comment by strgaltdel** [comment]
´That said, I do think that there is one fix here and that's that the point under adjustment's X position should always be limited by the current values of both neighbouring points (it should not push the right-hand point)"

I've the feeling that this kind of user misconfig is a little bit tricky, because the root cause ("excessive VAR value") is not directly "connected" to it's use case (x coordinate) within the mixer and so it's hard to perform plausibility checks in the mixer where the problem started.

Question is:
how far should ethos compensate such kind of "user induced failures" automatically.
I'm pretty shure there will occur a lot of possibilities how a user can, let's say "cheat the system".
In case there is consens that every kind of user failure should be intercepted there will be a HUGH time component what will be used to check if these errors are present (and in 99.9999% they won't) and that will permanently compromize the overall performance of the system.

And IF Ethos development would decide to intercept nearly each kind of user error which was mentioned there could be debates which strategy would be the right one.
(in this case, you even could completely ignore the wrong customized points because don't know what the original intention was)

One of the standard rules after editing a model config is to check all of the functionality on ground,
and so this kind of "misuse" would become obvious.

**Comment by Jedsters** [comment]
My thoughts for what they are worth...
I do agree that to make Ethos foolproof is impossible, as Douglas Adams said “A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.”
My thoughts are it comes down to user expectation. What would the average user expect to happen if... because even with a modest model definition there are too many combinations of switches, stick positions, adjustable vars etc. to check every possibility to all of the extremes. Will the average user in this case simply test that the point moves left and right a little bit and they get the expected outcome and be happy, or will they really carry on going left and right as far as they can while at the same time actuating whatever is controlled by the curve to see what happens and notice the difference in behaviour between one extreme and the other? Will the average user not even consider that the variable point is able to move beyond adjacent points?

In honesty, while I have a use for adjustable VARs on the Y axis, I don't on the X axis. I just happened to notice it was possible and after a while it dawned on me  that there was potential for problems and then it surprised me it was even there. Maybe as Mawz says because I'm mucking around with advanced stuff, which is what prompted me to see what did happen - and it wasn't what I expected! I wouldn't have a problem if the option to have e.g. VARs on the X points was removed, although I don't know if it was asked for. That seems the safest option IMHO unless someone does have a use case. Actually, slight caveat, I can see a potential for its use on a 3 point curve where  X for point 2 can therefore never exceed adjacent positions. Beyond that I agree, someone is doing some weird voodoo. Maybe they are trying to adjust a midpoint for butterfly curve in both X and Y axis?

**Comment by bsongis-frsky** [comment]
The rule in curves will be very simple:
`X(N) >= X(N-1)`
It will be consistent everywhere

**Comment by bsongis-frsky** [comment]
But what if X(N+1) is driven also by a Var? It is mandatory to have a rule which is clear!

**Comment by Jedsters** [comment]
It would be like adjusting a non-easy curve normally, you can't increase X(N) beyond X(N+1) unless you first increase X(N+1) or reduce X(N+1) below X(N) without first decreasing X(N).
It is all a bit messy isn't it. It would need a VAR to check if it is used in any curve as an X value before it can be adjusted. I guess that could be done with a flag or similar against a VAR indicating if it is used in a curve and if so, which curve and point it is used in? Then it could check the adjacent points, but if they are VARs it does get messy. 
Was there a requirement for VARs on X axis points?

**Comment by bsongis-frsky** [comment]
Then what will happen if all your points are driven with VAR? I am not fan of fixing problems which don't exist. Here the rull will be super simple: 

`X(N) >= X(N-1)`

**Comment by Jedsters** [comment]
Ah, I think I understand at last! So if X(N) >=X(N-1) then that also means X(N+1)>=X(N)  so if X(N) is a VAR you will ensure it doesn't gobelow X(N-1) but also that it doesn't go above X(N+1) otherwise it breaks the rule! Sorry, I was being slow there and concentrating too much on X(N)!

**Comment by Jedsters** [comment]
Hmmm, I guess that means that if both X(N) and X(N+1) are VARs then increasing X(N) could result in the X(N+1) VAR being increased? Which will mean checking that X(N+1) doesn't exceed it's bounds and potentially for X(N+2) if that is also a VAR etc. etc.. That's horrible!

**Comment by bsongis-frsky** [comment]
I am not sure there is a use case for that!
We could also say that all X cannot be driven by a GVAR
Seriously when people need this level of complexity for their model, they will avoid doing it wrong, I prefer give the maximum of flexibility but ensure Ethos doesn't crash / is not consistent in case of user mistake.

**Comment by bsongis-frsky** [comment]
I can improve a little bit the formula:

```
X(N-1) <= X(N) <= X(Next fixed point after N)
```

**Comment by Jedsters** [comment]
I think that would be useful. 

I can see that there is an argument that if a user has 2 adjacent variable X points then it is their responsibility to ensure they remain valid. 

For what it's worth, IMHO, when X(N) = X(N-1) and X(N) tries to decrease further, I think that X(N) should be stopped from decreasing rather than force X(N-1) to start decreasing as well (and then possibly X(N-2) to decrease etc.. But it may be worth asking others on that, I just found it surprising that adjusting X(N) could also adjust adjacent points. Similarly for X(N) not forcing X(next fixed point after N) to increase.

Thanks
