### ISSUE TITLE
perte radio x20s

### ISSUE THREAD

**Issue by Vincent70700** [FrSkyRC/ETHOS-Feedback-Community#2561]
Bonjour,
Hier il m'est arrivé un problème de perte de radio avec un extra de 2m60.
L'avion est détruit suite au crash.

Maintenant viens le temps d'investigations pour comprendre ce qui c'est passé pour éviter de le reproduire.

Ma radio est une x20s
J'avais 2 rx TD R 10 dans l'avion.
Il avait environ 500 vols dans cette configuration.

La semaine dernière je me rend compte q'un bout d'antenne avait disparue.

Après analyse c'était dû aux vibrations. La partie active de l'antenne c'est coupé a la base du blindage cuivre. C'est la partie plus épaisse de l'antenne avec une gaine thermo autour.

Il me restait 3 antennes et j'ai continué de voler comme ça sans problème en attendant mes 4 nouvelle antennes de remplacement.

Une fois reçu j'ai donc installé 4 antennes 2.4 neuves.
De marque frsky aussi mais de 60 cm de long (il ne restait que ça en magasin.)

De retour au terrain je fait un teste de portée.

Le signal faible arrive à environ 20m mais la perte de contrôle de mes gouverne arrive à 70m.

Il me semble que c'est beaucoup plus court que le 1er teste de portée que j'ai fait quand les rx était neuf mais bon.
Je me dit que 70m pour un teste de portée c'est déjà bien.
Je précise que c'est moteur tournant. (Essence)

Je prépare l'avion pour décoller.

Des l'avion en l'air il part à gauche puis à droit puis sur le dos puis crash ...

J'ai eu la sensation que les gouvernes réagissait avec beaucoup de retard comme en teste de portée juste avant de perdre le signal.

Après démontage et investigation j'ai fait des testes avec les rx.

Ça m'a fait des réactions bizarre lorsque j'entrais dans le menu option où on gere l'affectation des pins.
Je perdais la liaison et puis ça revenait puis repartait... Pas très rassurant.

Dans enregistrement des donnes j'ai vu rx reset case.
Il y avait plusieurs lignes avec soit indiqué reset soit ok

Cette ordre changeait entre plusieurs allumage du Rx
Des fois j'avais un seul reset et le reste sur ok
Et des fois j'avais 4 reset.

Dans mini maxi VFR 2.4 et 900 j'avais de 0 a 100%  alors que j'ai essayé avec d'autre rx je suis entre mini 98 et max 100%.

Mes rx TD R10 était dans leur 1er firmware la 1.0.7
Mon module est en version 2.2.2
version logiciel 1.4.7

Si quelqu'un avait une petite idée de se qu'il s'est passé je serai très intéressé.

Bonne journée
Vincent

**Comment by Skippydi** [comment]
Salut Vicent, ce n'est pas l'endroit pour ce genre de problème. C'est une question d'éthos.
Je pourrais le poster sur le forum Frsky chez Engel Modelltechnik

salutation
willy

**Comment by Vincent70700** [comment]
Bonsoir,
Je peux vous répondre sur ce mail ?

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment]
Oui mais il vaut mieux utiliser l'issue directement, l'échange de messages sera plus propre

**Comment by Vincent70700** [comment]
Bonjour
Je crois avoir trouvé la cause de Crash.

J'avais mis des antennes longues parce que les courtes n'était plus en stock.

Pour que ça soit jolie je les ai rangé un peut comme sur la photo avec les fils bien enrouler et spiralée.
Vous pensez que ça a pu causer la perte de fréquence ?
Merci
Bonne journée
Vincent

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment]
Vous pouvez envoyer la photo ? 
Quels sont les réglages RF faits sur l'émetteur ?

**Comment by Vincent70700** [comment]
L'image est en pièce jointe

J'avais 2 rx TD R10
Chaqu'un commandait l'a moitier de l'avion
Un rx pour la droite et un rx pour la gauche .

Mon tx est un x20s frsky
Version module 2.2.2
Version ethos 1.4.7

Version RX 1.0.7 la 1ere je crois

Un rx avec télémétrie activé sur les deux



Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment]
Vous écrivez à un robot qui alimente l'issue. Les pièces jointes sont perdues.

**Comment by bsongis-frsky** [comment]
Les 4 antennes enroulées ensemble autour du même cercle ? Je ne suis pas un spécialiste, mais à mon avis c'est très loin d'être idéal. Je pense également que ce n'est pas les bonnes antennes. Je peux avoir la référence de ces antennes ? Un lien vers le site où vous les avez achetées ?

**Comment by Vincent70700** [comment]
https://www.intermodel.fr/accessoires-recepteurs/775-antenne-60cm-recepteur-24-frsky-frsky-24ghz-antenne-frsky-antenne-24.html

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by samsab1** [comment]
pas un spécialiste non plus, mais l'idée est assez déconcertante. je ne serais pas étonné que l'origine soit précisément ici

**Comment by Vincent70700** [comment]
Hé oui ... Drôle d'idée que j'ai eu !
1000 vols avant ça sans problème
Après le changement d'antennes crash direct ...

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment]
Sur ce récepteur il faut des antennes 2.4GHz + 900MHz. J'envoie toutes ces infos pour analyse, mais je ne pense pas qu'il faille chercher trop loin ;)

**Comment by Vincent70700** [comment]
La chose que je ne comprends pas c'est pourquoi le 900 justement n'a pas pris le relais.
C'était juste les 4 antennes de 2.4 qui était entouré pas les 900 celle là je ne les avais pas changé.

Merci pour l'analyse c'est sympa
Bonne soirée

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by samsab1** [comment]
j'avoue que ta question est pertinente... dommage de ne pas avoir ta photo sous les yeux.
pas moyen de mettre un lien vers ta photo?

**Comment by Vincent70700** [comment]
J'ai même une vidéo de l'avion juste après le crash on vois bien les récepteurs et antennes.
Mais en pièce jointe ça ne fonctionne pas apparemment comment puis je faire ?
Et chose étrange aussi :
Lors du crash mes batterie de réception ce sont débranché du au fuselage coupé en 2.
Je les juste rebrancher pour faire un teste et les led était verte ! Sauf erreur c'est le mode Bind le vert ça devrait être bleu clingotant et léger vert en normal ou rouge en failsafe mais pas vert fixe.
Et j'ai aussi eu des choses étranges sur l'un des 2 rx lors des essai après crash.
Lorsque je réinitialisais le rx pour que la radio le supprime je pouvais toujours bouger les servos et la led restait bleu clignotant alors qu'elle devait être rouge.
Et par contre après difficulté à re binder le rx l'enregistrement était bon mais le bind ne fonctionne plus. J'ai recommencer 5 fois pour que ça fonctionne.

Autre choses quand je vais dans enregistrement des donné du Rx
La liste de reset case variait. J'avais 2 reset et le reste ok et des fois j'avais 4 reset et le reste en ok.

Et les valeurs de vfr en 2.4 et 900 était sur mini a 0 et sur max a 100%

Sur le 2eme rx le mini était a 98 et le max a 100.


Encore un truc après avoir retiré les rx de l'avion
Ça fait beaucoup d'infos mais voilà ce que j'ai pu constater que aucune vois ne faisait bouger les servos que j'avais mis sur le 1er rx alors que le 2em tout bougeait normalement.

Ça fait beaucoup d'infos.

J'avoue que je ne suis pas totalement rassurer de mettre le même montage sur mon prochain avion. Même avec les antennes pas enroulé bien sûr.

Merci pour votre aide.

Vincent





Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vincent70700** [comment]
J'ai mis la vidéo sur YouTube :
https://youtu.be/x1KlzsYHebI


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment]
> Le signal faible arrive à environ 20m mais la perte de contrôle de mes gouverne arrive à 70m.

Cela devrait être 100m pour RSSI Low, pas 20m ! Quelque chose ne tourne pas rond avec les nouvelles antennes, est-ce possible de réessayer le Range Test avec les antennes originales ?

**Comment by samsab1** [comment]
hello, c'est assez curieux qu'un modéliste aguerri comme toi ait fait ce choix quant à la gestion des antennes. les 2 antennes en 2.4 sont traditionnellement placées à 90° l'une de l'autre pour augmenter les chances d'une bonne réception quelle que doit la position de l'avion. si j'interprète correctement la video, il semble que tu as rassemblé et mis en // les antennes 2.4.
ceci étant ça n'explique pas la perte globale de réception  puisque le tandem aurait du basculer sur le 900.

**Comment by Vincent70700** [comment]
Oui je me demande encore pourquoi j'ai fait une telle bourde !
Mais pour les antennes la partie réceptrice était bien a 90° les une des autres
Les 4 a 90° le support a cassé lors du Crash donc on voit pas bien mais c'est juste la partie rallonge qui était enrouler.

Donc j'avais bien un problème même lors du teste de porté alors ! J'ai mal fait mon teste de porté du coup...
Ça aurait pu sauver l'avion dommage.


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vincent70700** [comment]
Malheureusement je ne peux pas tester les anciennes antennes je les ai jeté mais ça vaudrait le coup d'en racheter pour tester

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
