### ISSUE TITLE
RB30+ on Ethos does not keep constant voltage output

### ISSUE THREAD

**Issue by pandjarov** [FrSkyRC/ETHOS-Feedback-Community#2564]
After my previous ticket I have successfully calibrated the RB30+ and dry-fitted my plane electronics on the bench. I have configured one of the becs at 7.4 volts and the other to 6.6. Measured everything, everything worked fine. However, after a power cycle, voltages on both oututs went down by a 0.4 volt. Configured them again, power cycled again- down to 6.8 and 6 volts respectively. I am doing a power cycle using the NFC power switch. 

I am using two Archer R8 Pro receivers at the latest firmware v2.1.12 and a RB30+ unit on the latest firmware 20220412 Ethos is updated to the latest version too. Radio is X12S ISRM

**Comment by Kreisflieger** [comment]
I can confirm the problem with the power cycle voltage drop of the VOut1 and VOut2 BEC servo supply voltage, but this happens with the already on the FrSky webside end of January 2023 deleted Firmware RB30+_20220917.frsk.

This issue  is clearly independant of the transmitter firmware, whether OpenTx, EdgeTx or Ethos, as I did many tests with all three systems.

With the currently latest Firmware on the FrSky download webside: RB30_20220412.frk the current measurement of the servo channels 1 to 8 are showing approx. just 1/3 of the actually flowing current. This was several times tested and compared to a external current meter.
There is a long dicscussion in the German Engel Modellbau Technik forum about these issues regarding the current accuracy.
For me there is no indication that they will solve the problem.

Kind regards  Stephan

**Comment by Kreisflieger** [comment]
Can someone please recommend where to address this issue correctly to FrSky.

Thanks in advance   Stephan

**Comment by bsongis-frsky** [comment]
I have done already

**Comment by Kreisflieger** [comment]
Thanks a lot Bertrand :-)

**Comment by SmartTommy** [comment]
Please try this firmware:

**Comment by SmartTommy** [comment]
[RB30+_TEST_20230406.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11169824/RB30%2B_TEST_20230406.zip)

please test the new firmware

**Comment by pandjarov** [comment]
Issue is mitigated but not fixed. Here is a video of the fluctuations in voltage and stored valie that continue.

https://youtu.be/KaiTJU33n4s

**Comment by pandjarov** [comment]
Update: not sure why but the issue seems to be with the 7.4 value. It keeps going to 7.5. However if set to 7.5 it stays super constant and stable at 7.55. Some threshold or rounding issue maybe?

**Comment by Kreisflieger** [comment]
After watching your video I did some more testing with different voltages.

I used just one 3S-LiIon battery on battery input 1:  Vout2 set to 5.0 V constant:

                                             a       b         c         d          e           f          g       h         i           j         k         l         m
Voltage VOut1 set to:        5.0     5.5       6.0       6.5       6.8        7.0       7.2     7.4      7.6      7.8      8.0      8.2     8.4
Receiver voltage:               5.07   5.59     5.9      6.31      6.62     6.83     7.04   7.24    7.45   7.76     7.97   8.17    8.38

This gives the impression that the voltage set is not linear to the output voltage 
But the voltage is stable at different current loads.

**Comment by SmartTommy** [comment]
new firmware
[RB30+_20230407.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11176910/RB30%2B_20230407.zip)

**Comment by Kreisflieger** [comment]
[Here are my results testing the new FW.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11177981/Here.are.my.results.testing.the.new.FW.pdf)

**Comment by pandjarov** [comment]
I have just tested the new firmware.

1. Voltage reported in the RxBatt telemetry is 0.10-0.15 higher than the actual settings.
2. Actual voltage output is lower than the configuration setting with 0.1 volts
3. After the first power cycle after the flash voltage drops a bit. After that it remains constant.

So when I config V1 to 7.4 volts and V2 to 6.6 the telemetry shows RXBatt at 7.55 and the actual values are 7.28-7.3.

If I configure the unit at 7.5 and 6.7 volts I get the voltage I actually need at the channels. That voltage is constant through power cycles. Check out my video, it is a bit longer and I am sorry but it is difficult to film and measure at the same time :(

https://youtu.be/PDx0AHKTvnY

**Comment by Kreisflieger** [comment]
The telemetry of the RxBat voltage is send by the receiver, not by the RB30+. So better to just compare the value of the external voltmeter to the voltage set for VOut1 and VOut2.

In my test setup I am using a RX8Rpro and X18SE with ACCST.  The voltage between the set voltage, the RxBatt voltage
and the external measured voltage are always within  0.1 V accuracy.
I did not find an initial voltage reduction after the first power cycle.

By using a different receiver ( S8R ) I get a voltage ready difference of  another 0.1V. 
So it seems that different receivers are accurate within +/- 0.1V for the RxBatt voltage

Stephan

**Comment by pandjarov** [comment]
How come that voltage is higher than the supplied to the receiver? It gets power from the RB30+ unit?

**Comment by Kreisflieger** [comment]
@SmartTommy :

Please explain, how to do the current calibration in the Base config,   line  **Cur Calibr PW(78)**  
What voltage value should I dial in ?  The same voltage as VOut1 or VOut2 ? 

Thanks in advance for a clear instruction.

Stephan

**Comment by SmartTommy** [comment]
> @SmartTommy :
> 
> Please explain, how to do the current calibration in the Base config, line **Cur Calibr PW(78)** What voltage value should I dial in ? The same voltage as VOut1 or VOut2 ?
> 
> Thanks in advance for a clear instruction.
> 
> Stephan

just power on your RB30+, connect the receivers , disconnect the device such as servo on channel 1~8, and then run the Base config lua, press the button  Cur Calibr PW(78), wait 2 seconds.

**Comment by Kreisflieger** [comment]
**@SmartTommy** 

Thanks for your speedy reply and the FW updates.

From my point of view, the RB30+ is working quite nicely now.

Will this new FW also work in the RB30 and RB40, as I am in contact with some German users, who currently have similar problems with their devices.

Kind regards  Stephan

**Comment by pandjarov** [comment]
Ok so I tested it for an hour with a number of power cycles, one battery, two batteries, etc. I think with the latest firmware it is working just fine. Thanks for your assistance. 

Please let me know if you are going to release an official firmware and if it has some further improvements or other changes so I can flash and test it again.

**Comment by SmartTommy** [comment]
> 

this is only for RB30+, we will release the new firmware for RB30/40

**Comment by Kreisflieger** [comment]
Perfect !!

thanks a lot for your efforts. 
I am sure, many users of the RB30, RB30+ and RB40 will enjoy the full functionallity now.

Kind regards   Stephan

**Comment by pandjarov** [comment]
Any update on this, there isn't an official Firmware update on the FrSky site yet?

**Comment by SmartTommy** [comment]
> Any update on this, there isn't an official Firmware update on the FrSky site yet?

The firmware release version has been submitted and tested, and it is expected to be released on the website next Monday

**Comment by pandjarov** [comment]
Awesome, thanks for the great support!

**Comment by pandjarov** [comment]
Thank you! The fw is live on the site: https://www.frsky-rc.com/rb-30-plus/

**Comment by Kreisflieger** [comment]
To all who were involved in correcting the RB30+ firmware.

Thank you very much for solving the issues.

It shows that FrSky listens to the users and thereby solves problems.

I already communicated the availability of the new version in the German  FrSky forum.

Many regards

Stephan
