### ISSUE TITLE
Sound problem with Tandem X20S and XE

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#2567]
Hi,
Sometimes I no longer have any sound coming out of the radio.  I programmed automatic voice alerts, and other manual ones.  I noticed that this happened if 2 voice announcements overlapped.  For example, if the radio automatically announces the capacity of the lipo to me and I activate the landing gear, ( radio say "gear out" )this produces a phenomenon which cuts off all voice announcements for the rest of the flight... This also occurs sporadically without  there has been no voice announcement before.
I have to restart the radio for it to work again

Tandem Xe 1.4.7

**Comment by bsongis-frsky** [comment]
It's strange that nobody reported it on other radios. I wonder if the problem is not in the eMMC then, XE is the only radio with an eMMC ... 

When it happens again, would you check if you can still access the eMMC (in System / File Manager)?

**Comment by Tonio62** [comment]
ok i will look at that, thanks

**Comment by phaedra-tm** [comment]
I've been experiencing loss of audio too, Tandem XE, Ethos 1.4.7.  Haven't found any logic behind the phenomenon yet.
Had it on my first flight last Tuesday, and it didn't reoccur on the next 3 flights, which were a copy of the first flight really.

**Comment by bsongis-frsky** [comment]
I try it since this morning and I have just found a way to reproduce the issue:
- Enable logs (always)
- Screenshot
- Play Value + Play Track

**Comment by bsongis-frsky** [comment]
The sound is still working. I hear the beeps

**Comment by bsongis-frsky** [comment]
File Manager says "No SD Card"

**Comment by bsongis-frsky** [comment]
I think I have found the problem. I cannot reproduce it anymore.
