### ISSUE TITLE
servo limited travel

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#2568]
Hi,
I have a plane on which I tested the gyro on the tailerons (flying wing configuration in the settings of my sr8 receiver), when I wanted to return to the normal configuration (gyro on the ailerons) I no longer had  the maximum deflections at the elevator.. only 68%.  From 68% to 100% travel, there is a dead zone, where the stick no longer acts on the control.  I have this phenomenon on 2 planes and can't find a way to restore the maximum throw.  I have however reconnected everything as originally, and I have the impression that the receiver has kept in memory the flying wing function which limits the deflections

Tandem xe 1.4.7 with sr8 last firmware

**Comment by RealTadango** [comment]
Did you recalibrate the gyro? It learns the max throws (limits) during calibration.

**Comment by Tonio62** [comment]
yes, I will try to recalibrate it or rebind it
Thanks

**Comment by mawzthefinn** [comment]
Don't rebind, do a self-check.

This is a symptom of a bad self-check. 

You need to run the self-check every time you make significant changes to the servo setup or orientation of the receiver. The procedure sets hard endpoints for servo travel and the level setting for the receiver.

**Comment by Tonio62** [comment]
Ok tkany you, i'll try it ;)

**Comment by Tonio62** [comment]
> Don't rebind, do a self-check.
> 
> This is a symptom of a bad self-check.
> 
> You need to run the self-check every time you make significant changes to the servo setup or orientation of the receiver. The procedure sets hard endpoints for servo travel and the level setting for the receiver.

Ok, it's work
Self check must be done with the gyro in desactivated position on the switch
