### ISSUE TITLE
X20S Simulator Ver.1.5.0 compared to Ver.1.4.6

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#2573]
Hello frsky team,
I installed Ethos X20S Simulator Ver.1.5.0 on Windows 10 today and I noticed a few things compared to Ethos X20 Simulator Ver.1.4.6.
If I use a LUA widget (Pistenking Kingpad Ver0.4) which consists of several (2) screens with 12 functions each, a screen for a specific function (light or functions)
selected, this setting will be discarded each time the simulator is restarted.
The light screen is always displayed to me on both screens.
Furthermore, the last opened screen of a widget is also opened after restarting the simulator, in contrast to simulator version 1.4.6, where the first screen is always displayed.
With the X20S simulator versions 1.4.8 and 1.5.0 I cannot set any other language for display and voice apart from English.
br,
Torsten

**Comment by Satcomix** [comment]
Hello,
Since an innovation was published five hours ago,
I just reinstalled the X20S Simulator Ver.1.4.8(stable) again. Now everything works to my satisfaction!
In nightly Version 1.5.0 I can now choose between English and German for the AUDIO, the DISPLAY is only available in English.
**Saving the selected screen still doesn't work.** **Only the first (light, kingpad) function is always displayed, after a restart.**
After a reboot, at least the first page of a widget appears again.
Thank you for your work and effort.
br,
Torsten

**Comment by Satcomix** [comment]
Hello Bertrand,
Up to X20S Simulator version 1.4.8 everything works as it should.
I use a LUA widget from Pistenking (KingPadV0.4) to switch functions.
If I activate the function for the title light in the created screen in Nightly Version 1.5.0 and activate the title function on the second screen, Ethos loses this setting after a restart and both KingPad screens appear as light screens. This means that the title setting for the required screen function is lost after each restart.
Furthermore, I noticed that when reinstalling version 1.4.8, version 1.5.0 is overwritten.
br,
Torsten

**Comment by Satcomix** [comment]
![20230411_125316](https://user-images.githubusercontent.com/120665528/231139466-d6e7d858-622c-4031-b390-5313db554114.jpg)

Kingpad Level:  funktion is lost after restart.

**Comment by Satcomix** [comment]
![20230413_083950](https://user-images.githubusercontent.com/120665528/231677073-98eccce6-8571-4f1f-a7de-e66c11a6a695.jpg)

**Comment by bsongis-frsky** [comment]
Fixed in next nighties
