### ISSUE TITLE
Twin X-Lite S ELRS Ver?

### ISSUE THREAD

**Issue by Cadsbury** [FrSkyRC/ETHOS-Feedback-Community#2574]
Hello,  I just got a Twin X-Lite S with ETHOS, it's different but can stumble through most of it.  I've found how to set the Internal Module to ELRS and see a bunch of familiar setting to change.  But, how can I find the Version of ELRS and how can I update it?  It won't bind with any of my models that are on a certain version and I believe they are different.

Thank for any help you can offer me!

Chris

**Comment by mawzthefinn** [comment]
The TWIN gear’s ELRS compatibility mode is compatible with ELRS 2.3. 

It is not feature-complete (bind phrases in particular are not suppported) but it will work with any ELRS 2.x receiver that allows for manual binding.

If you want to use a different version, you will need an actual ELRS module.
