### ISSUE TITLE
horus x10 

### ISSUE THREAD

**Issue by victorllarena** [FrSkyRC/ETHOS-Feedback-Community#2577]
modulo interno desconocido

**Comment by bsongis-frsky** [comment]
?

**Comment by mawzthefinn** [comment]
Is the X10 fitted with an ACCESS ISRM module? This is expected behaviour on ETHOS if the X10 has the older ACCST iXJT internal module which is not supported by ETHOS

**Comment by victorllarena** [comment]
so? It is not compatible with the horus x10, and on the ETHOS page it says yes, I don't understand it?

**Comment by victorllarena** [comment]
What solution could you give to make it work with the ACCST module?

**Comment by strgaltdel** [comment]
> It is not compatible with the horus x10

of course, the isrm module IS compatible with the X10,
https://www.frsky-rc.com/product/access-upgrade-module-kit-x10-x10s/

You do only need to retrofit the ISRM Module, unless you want para functionality.
The only caveat, i think, is that it doesn't support the old D8 protocol.

There are a lot of reports from users on rcg who did the upgrade on X10/x12, no big deal.  

some examples
https://www.rcgroups.com/forums/showthread.php?2922046-FrSky-Horus-X10-X10S-and-Express
https://www.rcgroups.com/forums/showthread.php?3986279-Frsky-Horus-X10S-ISRM-update#post47928627

**Comment by mawzthefinn** [comment]
@strgaltdel is correct, to  get internal RF on an X10 you need an ISRM Upgrade module fitted. 

the iXJT is not supported, a non-upgraded X10 can still be used with ETHOS but would need to be used with an external module. Note the external XJT module is supported in ETHOS, I ran my X12S for some time with an external XJT module until I fitted the ISRM Upgrade.

**Comment by victorllarena** [comment]
muchas gracias soy los mejores
