### ISSUE TITLE
X12 : Pb Alarm RSSI for ACCESS mode

### ISSUE THREAD

**Issue by excalibur46** [FrSkyRC/ETHOS-Feedback-Community#2578]
First time using an RX Access (Archer R6), and have a problem with RSSI alarm on my X12 (v1.48)
I use 32dB for the critical value , but the alert always still triggers for 42dB.
In fact this value is not taken into account for value <42dB because whatever  entered a value below, the alert is always triggered for this value. (ACCST default value??). The values >42dB are taken account.
Same thing for the ACCST, but as theoretically we don't have to go below this value for this mode, the problem is not seen.

**Comment by bsongis-frsky** [comment]
What are your internal module settings?
Do you have the same issue if you create a new model from scratch?

**Comment by FrSky-GX** [comment]
Tried 1.4.7 and 1.4.8, haven't reproduce the issue. The warining always triggered at 32 and 35 which are default values.

**Comment by excalibur46** [comment]
I have created one from scratch and it works!. So it's OK.
The previous model that has problem, was created in ACCST mode, and after I changed it to ACCESS.
Pehraps it was the problem.
