### ISSUE TITLE
Output lines in mixer overlapping text

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#258]
X10s isrm 
Ethos 1.0.6
Text overlapping in output section of mixer.
Please see photo
![20210517_090454](https://user-images.githubusercontent.com/81478751/118462075-360d8d80-b6f6-11eb-8def-00eaadddc839.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/118653353-b9f37280-b7e7-11eb-8e4e-b941a21e4415.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/118654123-82d19100-b7e8-11eb-8a3c-2d1b92e037c5.png)
