### ISSUE TITLE
X12, SJ and SI not displayed in Hardware Test

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#2580]
Mounted sticks with 2-Pos push-button switches. Switches are selectable in Mixer and we can see that the are working in Output.

But not displayed in Hardware Test. The switches are of course connected to the two connectors on the main board.

**Comment by yak-54** [comment]
can confirm this and little joy stick and the enter button as well

**Comment by bsongis-frsky** [comment]
The little joystick is completely unused

**Comment by bsongis-frsky** [comment]
[ENTER] Key will be fixed in 1.4.10

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5a2aa6f8-9c0d-4a7d-9711-24c7bda6e262)

**Comment by bsongis-frsky** [comment]
Some bitmaps are missing from the current bitmaps/system pack.
If you want to fix this issue before 1.4.10 is released you have to copy those bitmaps from the X18 pack on your X12S SD Card:
- mask_dot_s.png
- rear_switch_background.png
