### ISSUE TITLE
X12S Haptic not working  on critical warnings

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2581]
Under ETHOS 1.4.8 no Haptic on critical warnings 
like VFR and RSSI warnings 
if volume turned turn off you get no other warnings 
which i did because of lipo sensor  conflict  on that plane so never heard the rssi waring 
i think the Haptic and flashing screen should happen

**Comment by pandjarov** [comment]
In addition, even though Ethos is in silent mode, there's a loud Welcome to Ethos sound which is not muted. IMO all sounds should be replaced with haptics when in silent mode.

**Comment by mawzthefinn** [comment]
> In addition, even though Ethos is in silent mode, there's a loud Welcome to Ethos sound which is not muted. IMO all sounds should be replaced with haptics when in silent mode.

That’s a known issue, reported by  me a good while back. The mute doesn’t initialize on the X12S right away when booting, so  you get welcome to ethos, but everything afterwards is muted

**Comment by mawzthefinn** [comment]
#1522 is where I reported the muting issue

**Comment by yak-54** [comment]
its not good if i turn down the volume i don't get any warning as i found out the hard way this is plane i had scratch built over the last 4 years  and on it maiden  last week 
![20230404_210102](https://user-images.githubusercontent.com/9161926/233256331-81a355dd-880d-498e-947f-88b028d4b938.jpg)

**Comment by bsongis-frsky** [comment]
Still valid? If yes it needs to be investigated

**Comment by yak-54** [comment]
i have not test it of late but i will today

**Comment by yak-54** [comment]
Can confirm still not working on 1.4.9

**Comment by bsongis-frsky** [comment]
Fixed for 1.4.12

**Comment by yak-54** [comment]
Thanks Bertrand
