### ISSUE TITLE
Posibility to eliminate the 10 seconds countdown in timer with speech

### ISSUE THREAD

**Issue by FBarrao** [FrSkyRC/ETHOS-Feedback-Community#2582]
X20S 1.4.5 EU
With the timer in the speech mode, the minute call is very useful, but the final 10 seconds countdown, very anoying, and overrides the air speed calls in the landing if you are landing when occurs. 
Should be nice can choose if you want 10 seconds countdown or not.

**Comment by koakumaping** [comment]
agree

**Comment by T3chDad** [comment]
Please!

**Comment by Szonu** [comment]
Should have an option to remove or change countdown

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/e5080c0a-fe6b-4a99-ac28-b0badeb21e2a)

**Comment by bsongis-frsky** [comment]
It will be part of the next nightlies

**Comment by FBarrao** [comment]
Great, thank you!
