### ISSUE TITLE
Audio Conversion Tool not working in Ethos Suite 1.4.8

### ISSUE THREAD

**Issue by woltervdberg** [FrSkyRC/ETHOS-Feedback-Community#2583]
When using the audio conversion tool in Ethos Suite 1.4.8, I get the message that the destination path does not exist. (Doesn't matter what destination path I select).

Downgraded to 1.4.7 and it is working fine.

**Comment by mawzthefinn** [comment]
Re-install 1.4.8, the build was updated as that bug existed in the original 1.4.8 build, and was fixed for the image tool at least.

**Comment by woltervdberg** [comment]
Thanks, re-installing did the trick as you said. 
Guess that's on me for being impatient and using a pre-release version.
