### ISSUE TITLE
Buttons locked after accessing and editing one curve

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#2585]
When you access to menu Mixer to edit a curve and access the points of the curve, returning to the main screen , locks all buttons until the touch screen is touched.
My radio Tandem X20  ver 1.4.8

https://user-images.githubusercontent.com/87758703/232726821-18a359ec-b49b-47a7-b224-f06f2b398267.mp4

**Comment by bsongis-frsky** [comment]
What are the widgets displayed on your Home screen?
Do you replicate this issue with a fresh model without modified Home screen?

**Comment by mawzthefinn** [comment]
Tested with the standard Home Screen, unable to duplicate issue

**Comment by jasalca** [comment]
It only happens when editing a throttle curve or pitch curve

**Comment by jasalca** [comment]
I have done exactly the same thing in the Ethos Simulador 1.4.8 and the same bug is also reproduced

**Comment by jasalca** [comment]
https://user-images.githubusercontent.com/87758703/232832567-e2438562-9dcb-4bea-b00c-2a4741ebe242.mp4

**Comment by bsongis-frsky** [comment]
Reproduced. I didn't understand that you pressed [EXIT LONG] to return directly to the Home Screen

**Comment by jasalca** [comment]
Yes ,of course, it was with EXIT LONG . Perfect then.The truth is that you do an exceptional job. Congratulations and thank you.
