### ISSUE TITLE
Table 'lcd' is not protected against hacking in the X20S simulator.

### ISSUE THREAD

**Issue by Tedesc0** [FrSkyRC/ETHOS-Feedback-Community#2586]
I accidentally changed the function call 'lcd.color(WHITE)' to 'lcd.color = WHITE'.

In this situation LUA did not detect any compilation errors and ETHOS did not detect any runtime errors either.

The result of executing the incorrect statement is that the function that changes the color in ETHOS was deleted from the system and it was necessary to restart the simulator for it to come back into existence.

Is this behavior by design or does 'lcd' need to be changed to not accept this type of programmer error?

Thank you very much in advance for your answer.

*** simulator used is Ethos-X20S, firmware 1.4.8, FCC #1b0eeaab.

Tedesco.

**Comment by bsongis-frsky** [comment]
I think it is allowed by Lua, you may change all the functions if you like, no hacking there, you are just breaking the branch of the tree where you are sitting :)
