### ISSUE TITLE
Annulation de choix dans les menu ?

### ISSUE THREAD

**Issue by simonPaul25** [FrSkyRC/ETHOS-Feedback-Community#2588]
Bonjour,
Je viens de m'apercevoir en faisant une erreur qu'il est impossible d'inhiber certain choix. 
Par exemple  ici il est possible de revenir en arrière est d'annuler notre choix grâce au trois petit trait.
![Courbe](https://user-images.githubusercontent.com/115720988/233082166-69771deb-e8d1-4197-b201-7be0bf515404.jpg)
Par contre là impossible.
![Differentiel](https://user-images.githubusercontent.com/115720988/233082580-254178f8-b30e-40be-a895-bb31d9577c50.jpg)
IL y a beaucoup  de menu ainsi, ou qu'il est impossible d'annuler le choix. Du coup pas droit à l'erreur.
Est ce normal? Ou bien je n'est pas compris comment faire?

**Comment by mawzthefinn** [comment]
In the second case, a value MUST be present for that value. You can press RTN to back out without selecting an option.

The '---' selection is only available when the setting is only active if an optional setting is selected.

**Comment by mawzthefinn** [comment]
Closing as answer provided.

FYI - if you accidentally select minimum or maximum and want to go back, select ‘Use a source’, back out, then do it again and select ‘convert to value’ which will reset the selection. Or just edit the value (Maximum and minimum just pre-load 100% or -100% as the value, you can still adjust)
