### ISSUE TITLE
Texts cut off in special functions

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#259]
X10s isrm 
Ethos 1.0.6
Texts cut off in special functions.
Please see photo
Sf15 and sf17

![20210517_073417](https://user-images.githubusercontent.com/81478751/118462581-baf8a700-b6f6-11eb-8f81-079a58269a76.jpg)

**Comment by Liverboy77** [comment]
Hi this has not been fix in ethos 1.0.7
Thanks

**Comment by bsongis-frsky** [comment]
Which screen, would you have a photo?

**Comment by Liverboy77** [comment]
![20210517_073417](https://user-images.githubusercontent.com/81478751/119402463-e0784880-bcd4-11eb-8e78-2df7d118f589.jpg)

**Comment by Liverboy77** [comment]
Please see sf15 and sf17.
Thanks
