### ISSUE TITLE
1.5n new widget forms: documentation incomplete after some changes

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2591]
After taking a bit of a break from Lua development, I noticed that an earlier 1.5 widget that used form methods was no longer running as expected.
When I looked in the current documentation, I found that there had been a major redesign.

Now it seems that after creating a form, you have to declare a line and then use the "form.addXYZ" method, referencing to this line, to specify its use.
(Which is more similar to the old "configuration forms").

The problem is:
The documentation is incomplete

- in all these "add" methods, a "rect" parameter is mentioned to declare the "field size" or "position", but it is not described where to enter it in the parameter list
- 
![image](https://user-images.githubusercontent.com/20392683/233357681-a08e0a0b-3693-4b78-9545-906bdfb55259.png)

- form.create is mentiond without parameter, but this seems to lead into "error: no window".
- and so the method addLine  leads to "error: no form". 

Please give a simple example of how the new form methods should be used in widgets
(like create a simple form, one static text or number field)

Thanks in advance

udo

**Comment by MiRe-CZ** [comment]
I can confirm, form.create() now gives "error: no window", it was OK couple of days ago. Additionally issues reported in #2473 have not been fixed yet

**Comment by mawzthefinn** [comment]
1.5.0 is still in Nightlies, incomplete documentation is expected for now as it’s a fast-moving target.

**Comment by strgaltdel** [comment]
documentation still lacks "rect" explanation
(7. Aug.23)

**Comment by bsongis-frsky** [comment]
Where do you calll form.create? It doesn't expect any parameter.

**Comment by bsongis-frsky** [comment]
More examples added to addTextField

**Comment by MiRe-CZ** [comment]
The issue is but with form.create(), it gives "error: no window" since April. I call it from the create function, exactly as it was suggested:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/95141646/f5858b8f-0e82-4eae-8e69-7fbc18cdc4dc)

BR, Milan

**Comment by strgaltdel** [comment]
Yepp, can confirm, problem still exists (since end of march i guess), just checked.
as soon as a form.clear() is called the error message is prompted

my failure was that i saw the unnecessary, added parameters  in the form.clear docu (maybe "copy paste" failure) and interpreted them as new required variables.

basically, form.clear() crashes since four month

**Comment by MiRe-CZ** [comment]
One correction to be absolutely clear - it is form.create(), not form.clear()

**Comment by strgaltdel** [comment]
.. got no coffee this morning (-;
