### ISSUE TITLE
ETHOS Suite (macOS version) Cannot read my brand new X20S

### ISSUE THREAD

**Issue by Drumskies** [FrSkyRC/ETHOS-Feedback-Community#2593]
Hi!

I got my new radio transmitter few days ago, the FrSky Tandem X20S. I have not had a FrSky radio before. So the topic is new to me...

I also immediately installed the ETHOS Suite for Mac (**Ethos-Suite-Setup-1.4.8.dmg**) to check for radio updates and update that radio to the latest software version. 

Ethos suite showed that my radio contains:
Firmware version 1.4.0.EU
Bootloader Version 1.4.0

After both, the gray bar says "Reading version..."
See the attached screenshot.
![First situation](https://user-images.githubusercontent.com/131333218/233447350-e43b3b63-acbd-485d-ace1-1531dcbb0b4a.png)

So here is "Reading version..." but nothing ever happens. There will be no orange "Out of date" or green "Up to date" buttons with which I could update the Firmware or Bootloader. The "Update your radio" list does not appear either.

My Mac is PowerBook Pro and maOS is Ventura (13.3.1). See screenshot of my Mac infos.
![My Mac](https://user-images.githubusercontent.com/131333218/233447497-ca438209-5cf5-41f9-bca9-24f47254bb3e.png)

I also have a VMware Fusion platform on my Mac where I run a Windows 10 system. So I then installed Ethos Suite on Windows 10 (**Ethos-Suite-Windows-1.4.8.exe**) and everything worked fine and I was able to get all the updates to the X20S radio. So radio software version are now:
Firmware version 1.4.8.EU
Bootloader Version 1.4.3

See the attached screenshot.

![Ethos Suite 1 4 8 Windows 10](https://user-images.githubusercontent.com/131333218/233447546-2bf8f8da-401d-45d2-b974-626ed5e041c2.png)

However, after the update, the situation in the Mac version of Ethos Suite is still the same. Does not work in my Mac. 

If necessary, I can provide more screenshots of my Mac, its settings, etc. Ask!

I have been using Apple Mac computers at work and in my free time for more than 30 years, so Windows is not an option for me. I hope that this ETHOS Suite can also be made to work on the Mac platform.

**Comment by Nicholas-Luoyi** [comment]
This is obviously a net work problem. Can the Suite get the releases detail in the Update News page? Also please try to switch the Server Location in the Suite Settings page. And if there are crash logs from Suite Settings -> Open crash log. You could post them here.

**Comment by Drumskies** [comment]
1. No, the Suite can't get the releases detail in the Update News page. It's empty page. Can't see latest release list.
2. Changing the server location in the Suite Settings page does not help.
3. When I click "Open crash log" it opens folder from Finder. Folder name is "Crashpad" and content of this folder is empty.
4. Attached my Firewall settings from WithSecure Elements (former F-Secure). Is there something wrong with the firewall settings?

![WithSecure Elements, Firewall settings](https://user-images.githubusercontent.com/131333218/233539347-40f3bfa4-2e1f-4d72-b336-77a16e9de7bf.png)

**Comment by mawzthefinn** [comment]
Disable WithSecure Firewall and try again. I would bet that is the issue.

**Comment by J-charles-C** [comment]
Hi,

try this.


Go to settings, "privacy and security", then "files and folders".
You authorize access to volumes external to ETHOS.

So it works for me.

**Comment by Drumskies** [comment]
I already did this as soon as I installed Ethos Suite, so that's not the problem.

**Comment by Drumskies** [comment]
Now that I have tested things, and connected the X20S radio to the Mac many times, I have noticed that the X20S screen does not always show a selection:

**USB**
- Joystick
- Ethos Suite
- Serial

I have to unplug and plug the USB-C cable into the radio two or three times, then I see those options on the X20S screen and I can go forward.

Does anyone else have this problem?

**Comment by Drumskies** [comment]
I tried with a brand new Apple USB-C cable. Same phenomenon. It's probably not a cable fault...

**Comment by Drumskies** [comment]
However, I would like to keep WithSecure's protections on. Can anyone tell me from **which address connections should be allowed** for Ethos Suite to work?

**Comment by Drumskies** [comment]
![identifiers](https://user-images.githubusercontent.com/131333218/234344436-93feab25-038c-49ba-bf98-4667a87cb979.jpg)

See the creenshot: Things like this should be sorted out…
From which address should connections be allowed?
Is it this?:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases

**Comment by Drumskies** [comment]
### Solved!

Originally, the WithSecure firewall allowed:
"Production certificates only"

We changed it to:
"Production and development certificates"

Now it work very fine.

**Comment by mawzthefinn** [comment]
Glad you got it sorted. Closing off as it is fixed.
