### ISSUE TITLE
Suggestion : Flex Firmware - Live Power Output As Telematery. 

### ISSUE THREAD

**Issue by munzoorf95** [FrSkyRC/ETHOS-Feedback-Community#2595]
Dear Tech Guys, Hope are all doing well. Its not an issue but a suggestion. As we all know that in Flex Firmware if we select 915mhz power to 1000mw, its auto select the output power based on RSSI. I think there shoud be an option to show live Power display on the display screen, so we can know that how much power is being transmitted. Right now its a blind trust on this feature. but if it is possible to show the power output then it will be an awesome feature in Flex.

**Comment by i3dm** [comment]
it has been asked before, i agree its important.

**Comment by MrD-RC** [comment]
+1

It would also be great if this was sent in the SmartPort and FPORT protocols to a flight controller for display on in the OSD. Also, please stop sending RSSI over channel 16. It's in the protocol, so not needed on a channel.

**Comment by mawzthefinn** [comment]
RSSI on Ch16  is a receiver firmware item, not an ETHOS item.

The rest I certainly agree with.

**Comment by i3dm** [comment]
still needed..

**Comment by MrD-RC** [comment]
Naughty stalebot.

**Comment by MrD-RC** [comment]
I think I have seen this now. But it would be great if it could be confirmed.

**Comment by i3dm** [comment]
I think this is already implemented

**Comment by bsongis-frsky** [comment]
Thanks @i3dm
