### ISSUE TITLE
Trim Mix: Option to disable the audio

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#2596]
It would be great if there was an option to disable the beeps, **Min reached** and **Max reached** audio feedback. This feature will work well for anything that needs increments. But for this, it needs the option to turn off the default feedback. Especially when you just want to use your own specific feedback messages for the exact function it is performing.

**Comment by strgaltdel** [comment]
.. and it would be great if "dis-/enable" audio feedback could be customized on a "per trim" base, 
not as a "global" parameter in the model config.

So dedicated trims (e.g. throttle or rudder) could be used for special functions

**Comment by MrD-RC** [comment]
Any thoughts on this from someone in the FrSKY camp? I am actually working on a model right now where I need the default feedback gone.

**Comment by MrD-RC** [comment]
> .. and it would be great if "dis-/enable" audio feedback could be customized on a "per trim" base, 
> 
> not as a "global" parameter in the model config.
> 
> 
> 
> So dedicated trims (e.g. throttle or rudder) could be used for special functions

100%. Sorry if it wasn't clear in my original request. But yes, this would need to be per trim. Even better, if the trims can be altered pre flight mode. It should be per trim, per flight mode.

**Comment by MrD-RC** [comment]
Stale bot is annoying.

**Comment by MrD-RC** [comment]
Afaik, this has not been resolved.

**Comment by MrD-RC** [comment]
Go away stale bot!! This issue still exists.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b6ee7c54-8893-4b8a-8b5e-69254e9740da)
