### ISSUE TITLE
Beep with vario

### ISSUE THREAD

**Issue by danydu62** [FrSkyRC/ETHOS-Feedback-Community#2597]
Hi. Since 1.4.8 , i don't have anymore beep using the vario. Can you help me with this issue please? Thanks

**Comment by mawzthefinn** [comment]
Please make sure your radio is fully updated with suite. 

Also please provide the model bin file so it can be checked for any conversion issues.

**Comment by jeromeboutte** [comment]
radio file up to date 1.4.8 with the suite, up to date gr8 receiver up to date 2.1.12 it does not work.

**Comment by danydu62** [comment]
Hi. Even with everything updated,  nomore beep can be ear.  Any other idea?
Thanks
Dany

Le lun. 24 avr. 2023 à 14:44, mawzthefinn ***@***.***> a
écrit :

**Comment by mawzthefinn** [comment]
Tested with Archer GR6 - ETHOS 1.4.8, TD-ISRM 2.2.2, GR6 2.1.10 - works fine. Tested with GR6 2.1.12 and it works correctly as well.

**Comment by jeromeboutte** [comment]
Hi, Tested with Archer GR8- ETHOS 1.4.8, TD-ISRM 2.2.2, GR8 2.1.12  it does not work.

**Comment by jeromeboutte** [comment]
I don't understand what's going on? None of my varios work anymore, everything is up to date! I'm on an EU LBT version on my x20s

**Comment by mawzthefinn** [comment]
Which receivers/sensors? Aside from the GR8 that is.

As of right now we cannot duplicate.

**Comment by jeromeboutte** [comment]
hello, the problem is solved,
 I had to put back a previous version 1.4.4 and then put back the 1.4.8 is the miracle the variometer works again.
