### ISSUE TITLE
X20HD video rx update to support BF 4.4 and latest hdzero vtx updates

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#2598]
Hi,

With the latest betaflight hd osd support and the latest hdzero vtx updates the osd is completely missing on x20HD transmitter and would be nice if you could get an update to support them

**Comment by kakashi2018** [comment]
Hi @mawzthefinn  any comments on this please?

**Comment by mawzthefinn** [comment]
None from me, but I don't use that hardware myself.

This would have to come from @Adelaxie or one of the other FrSky reps here.
