### ISSUE TITLE
Expo menu cuts off screen 0.0.17

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#26]
X10s isrm v2.16.
When selecting expo in the mixer screen, the expo menu is cut of screen, but when selecting a curve the curve menu is OK.
Please see photos

Thanks scott 

![20210401_143629](https://user-images.githubusercontent.com/81478751/113302767-4ad5c380-92f8-11eb-9748-e6112c9c6374.jpg)
![20210401_143657](https://user-images.githubusercontent.com/81478751/113302782-4f01e100-92f8-11eb-89e5-5f8ec1b17f7d.jpg)

**Comment by bsongis-frsky** [comment]
Fixed in 0.0.18
