### ISSUE TITLE
Using trim 5 for steerable front wheel

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#260]
X10s isrm
Ethos v1.0.6

I have my steerable front wheel on a separate channel to my rudder, is there away I can assign trim 5 switch to the steerable front wheel? So the rudder trim just does the rudder.
Thanks

**Comment by hrenz** [comment]
take the trimmmixer for a free trimm

**Comment by Liverboy77** [comment]
There are no switches on the back of the horus x10s

**Comment by mawzthefinn** [comment]
T5 is selectable as an input for a Free Mix, which can be used to trim your front wheel.

Alternatively you can use T5 Up and T5 Down as the Up and Down conditions for a Trim Mix to do the same thing. 

Note you need to use the Analogs->Rudder as the input for the nosewheel mixer so you don’t get trim added.

**Comment by mawzthefinn** [comment]
Closing issue as answer has been provided.
