### ISSUE TITLE
Inactivity, sleep mode not working with stick enabled.

### ISSUE THREAD

**Issue by pmullen503** [FrSkyRC/ETHOS-Feedback-Community#2600]
I'm having an issue with my Inactivity Alert not working on my X20S.

For Sleep Mode, if sticks are selected as trigger it nevers goes to sleep mode. If switches and/or gyro are selected, sleep still works as expected so I wondered if stick noise could be the problem affecting Inactivity Alert.

Checking ADC shows the last digit of all pot and slicks are bouncing around but would that be enough to prevent the inactivity alert?

I checked that the inactivity.wav file is good and is in the /audio/en/system folder. Hardware and gyro recalibrated.

I'm running firmware  1.4.8

**Comment by pandjarov** [comment]
That bounce is preventing it fro going to sleep. Calibrate your pots and sticks. On my radio sleep / wake with sticks works fine.

**Comment by pmullen503** [comment]
As stated above, the sticks, pots and gyro were recalibrated. 

The bounce is around 0.1% of the ADC value. That may be too sensitive. I think a change equivalent to say 1% ADC would be sensitive enough for pots and sticks to bring the radio out of sleep and still allow the inactivity alarm to function.

This not an unprecedented problem. I've found several reports on various forums about this same issue.

**Comment by Fordster39** [comment]
Same issue, x20 running 1.4.8. My work around was to pick gyro. It will now wake when I pick up radio after going into sleep mode .

**Comment by pmullen503** [comment]
Sleep and wake up works fine (as long as sticks aren't set) but what I really want is for the inactivity alert to work.
