### ISSUE TITLE
RPM sensor not displaying temp correctly

### ISSUE THREAD

**Issue by DanPesonen** [FrSkyRC/ETHOS-Feedback-Community#2601]
I swapped to EthOS from OTX, and put a RB25 in my Gasser. Previously has RB20. Using the RPM sensor with 2 temp sensors.  This worked correctly in OTX, but the temps do not display correctly now.  Sensor was 150F getting reading of 80F  And changing to C barely changed value  60F changing to C displays 53C   Sport to XR8R then to the RB25

**Comment by DanPesonen** [comment]
No info on this at all?

**Comment by bsongis-frsky** [comment]
I would like to be sure that this problem has been fixed in 1.4.11
There was a problem in °C / °F conversion ...

**Comment by bsongis-frsky** [comment]
I close it again and I assign it to 1.4.11, feel free to tell me if I need to reopen it
