### ISSUE TITLE
X20 with 1.5 Nightlies - Emergency mode when switching on ext module port (PPM mode)

### ISSUE THREAD

**Issue by onki69** [FrSkyRC/ETHOS-Feedback-Community#2602]
I am testing the 1.5 nightlies with my x20.
The x20 (using X20S firmware due to an upgraded BT-module) goes to emergency mode when I was opening several models.

The reason for this is most likely the fact that these modes are using the external module (Jeti module in lite housing).
If I disable the external module the error is gone. But as soon as I activate the ext. module in RF settings the X20 crashes again to emergency mode.
So there is soemthing wrong with external module support (my ext.port is set to PPM).
It seems that PPM setting is causing the problem as with other settings predefined it works.
Only when selecting PPM on the activated ext. module the trouble starts.
It still happens on the latest nightly #856b98ad

**Comment by bsongis-frsky** [comment]
Reproduced. Obviously there is a problem with PPM / Ext. Module

**Comment by bsongis-frsky** [comment]
Fixed just now. It will be part of the next nightlies
