### ISSUE TITLE
X20S with 1.5.x Nightly Telemetry Sensors

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#2603]
Hello FrSky Ethos Team,
I just downloaded the latest Nightly version and installed it on my X20S.
I noticed that the telemetry sensors are displayed on my main screen, as set up by me, but no sensor appears in the Telemetry menu. Only after I press Create DIY Sensor and search new Sensors do all the sensors appear on the screen at once. After that, I always have to delete the DIY sensor first so that everything appears as usual.
But if you now leave the Telemtry page, all sensors have disappeared again, they are only always displayed on my main display.
And if you switch back to the Telemetry page, you first have to create a new DIY sensor and then delete it.
Greeting,
Torsten

**Comment by mawzthefinn** [comment]
Confirmed on my X20.

**Comment by Satcomix** [comment]
Small feedback:
Just installed the latest Nightly and **everything is working again with the Telemetry**, as far as I can see.
Thank you for the work!
br,
Torsten
