### ISSUE TITLE
Free mix differential 

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2604]
Would it be possible to have a differential option in free mixes? I know there’s the Weight Up and Weight Down options, but they are not so simple to assign to a source as a single differential option would be. 

Free mixes are needed to work around restrictions in the built-in mixes, but the lack of a differential option hampers their use.

**Comment by mawzthefinn** [comment]
The problem with Differential in Free mixes is pretty simple, are you doing Ailerons/V-Tail or Elevator/Rudder style dual channel. The logic must allow for both if it's provided. In the first you functionally have each pair of output channels getting opposite output, but the second is the same output for all channels assigned. 

I would address applications that need differential by using paired Free mixes instead for the first use case. The second is already addressed by Weight Up/Weight down (you only need one for differential). 

Long-term, the right answer is per-output curves in free mixes so the differences between the two applications can be addressed downstream of the base weights.

**Comment by lightbulbjim** [comment]
Yes, I see what you mean. Using two free mixes works, but managing the differential value becomes unintuitive. From a functional point of view of course there's no difference between the OpenTX style of weight + differential vs the EthOS style of up weight up and weight down, but the generally expected way to set differential is with a single percentage value.

Some alternatives which could maybe be considered:

Add differential to the rudder mix (it really needs to be there for v-tail setups anyway) and then allow specifying a source in aileron and rudder mixes. This would allow adding "aileron-style" or "rudder-style" mixes anywhere. Actually I think something like this is already needed, for example with v-tail RE[SF]? gliders. It's pretty common for mode 2 pilots to put the rudder on the right stick, or even both sticks (I like using the left stick for launch and the right stick once off the line).

Another option would be to add per-channel differential to the _output_ section of free mix. This would make free mixes much more useful as general purpose tools.

With both of these ideas I'm trying to avoid the "add another mix to drive a high channel" approach. That works, but can really clutter up the mixer page and make it hard to separate "scaffolding" from aircraft logic and parameters.

(On that note, I'd also like to be able to specify multiple input sources for free mixes, so all of the logic for one function could be contained within one mix. This would be a blend of OpenTX and EthOS styles, and would avoid top level mixer soup when you want to add trims and multiplex controls. But that's a topic for another time!)

**Comment by mawzthefinn** [comment]
When VAR's arrive in 1.5.0 managing both settings will become easier.

V-tail differential has been requested a LONG time ago. We're waiting (V-Tail has the same issue as Free Mix, how do you tell which Differential algorithm is needed. In this case there is an answer but requires the Rudder mixer essentially be an aileron mixer when V-tail is selected)

Curve on the Free mixer output mapping essentially is the same as a differential setting, jsut implemented in a more ETHOS style (ie if in doubt, use a curve).

**Comment by lightbulbjim** [comment]
> In this case there is an answer but requires the Rudder mixer essentially be an aileron mixer when V-tail is selected

That's why I think the best overall solution is supercharge free mixes:

- Differential per output channel.
- Multiple weights selectable by condition.
- _Maybe_ multiple sources allowed, so trims can be folded in without extra fluff.

Then free mixes would be truly general purpose.

> Curve on the Free mixer output mapping essentially is the same as a differential setting, jsut implemented in a more ETHOS style (ie if in doubt, use a curve).

Differential is pretty common though, and it would be far easier to have a single diff value to feed into a mixer than reinventing it with curves. It feels like I'm having to fight the system to accomplish a basic task.
