### ISSUE TITLE
Request / Enhancement: Continuous Timer Once Started....

### ISSUE THREAD

**Issue by T3chDad** [FrSkyRC/ETHOS-Feedback-Community#2606]
Request an option be added on the timer edit screen to allow the timer to keep running once it has started.  "Continuous once started".   I have done this with a sticky logical switch personally, but believe non-nerd/new-to-FrSky users that are coming from other systems would really appreciate such an option.

Thank you.

**Comment by Nicholas-Luoyi** [comment]
Is this a feature that Persistent selection will implement?

**Comment by T3chDad** [comment]
> Is this a feature that Persistent selection will implement?

No

**Comment by mawzthefinn** [comment]
No, this is equivalent to the 'Throttle trg' active condition, but using any trigger, not just the throttle stick position.

**Comment by T3chDad** [comment]
> No, this is equivalent to the 'Throttle trg' active condition, but using any Active Condition, not just the throttle stick position.
> 
> ie Active Condition starts the timer in the session, but the Active Condition going false does not stop the timer.

Couldn't have said it better!  Thanks.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/236607707-c55c666a-7ff6-4fd4-a236-76d4603891d3.png)

**Comment by T3chDad** [comment]
Thank you. Much appreciated!
