### ISSUE TITLE
Font Size too small in X18 and TWIN transmitters

### ISSUE THREAD

**Issue by chrisca70** [FrSkyRC/ETHOS-Feedback-Community#2607]
Font Size is too small in the Ethos OS in the X18 and TWIN transmitters. I have heard this complain from multiple users in online forums and experienced it with my personal transmitter. PLEASE INCREASE FONT SIZE FOR LEGIBILITY AND EASE OF NAVIGATION.

**Comment by Szonu** [comment]
Agree it’s like x18 is using x20 fonts and not allowing for the  smaller screen 
Every one I showed my x18 to said the fonts are tiny and some  couldn’t read it  
Some where going to buy until they looked at the screen. 
And full screen widgets only use small amount of the screen 
Smallest font I’ve seen on any tx

**Comment by andika207** [comment]
>  Smallest font I’ve seen on any tx

@Szonu When it come to the visual style, most requests are likely to be ignored I know this by experience.
Bear in mind the screen resolution is lower than the X20 one and @bsongis-frsky will want to keep up as much info as possible on the screen.
Not only the fonts size but I truly belive other bits could have been done differently

**Comment by Szonu** [comment]
If not changed then they are loosing sales as everyone I showed it to who was interested in the x18 said fonts to small 
Yes screen resolution is higher  and has  a larger screen on the x20 so we’re the x20 fonts just used for x18 without allowing for screen being smaller.

**Comment by andika207** [comment]
> If not changed then they are loosing sales 

@Szonu This is exactly what @bsongis-frsky said in this topic https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/232#issuecomment-942058046
I can't tell if it's the font size or the screen quality overall (X18SE is better) that makes people to put it up for sale so often on the second hand market

**Comment by Szonu** [comment]
Not one person I have showed x18 to said they would buy it if the txt is so small. 
I see it  has been added to enhancement and milestones 
So does that mean it’s being changed 
If so would make this tx awesome

**Comment by andika207** [comment]
@Szonu Where are you from ?

**Comment by Szonu** [comment]
I am from England 
What about you.

**Comment by bsongis-frsky** [comment]
All small fonts, including the default font will be increased by 2px in next release 1.4.9

**Comment by andika207** [comment]
@bsongis-frsky the bot closed this related issue the same day https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1906

**Comment by lightbulbjim** [comment]
Unfortunately just increasing the font size across the board means that some strings now overflow their bounds.

Some examples (not exhaustive):

<img width="486" alt="Screenshot 2023-05-14 at 10 02 01" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4312404/2a149e26-e518-4756-960a-2cb766e5c198">

<img width="486" alt="Screenshot 2023-05-14 at 09 58 56" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4312404/f890e17d-7308-462d-be7c-7b7220547ce1">

**Comment by dsolaray** [comment]
> Looks good 

Take a close-up look at the newly released X18RS fonts which look smaller than the fonts displayed on the old X18 
This is getting worse LOL

![screen](https://github.com/user-attachments/assets/013efcab-db20-4ee6-9c30-2abc614a784c)
