### ISSUE TITLE
USB default mode preselection

### ISSUE THREAD

**Issue by jogybaer0815** [FrSkyRC/ETHOS-Feedback-Community#2608]
please integrate in geneal menu a preselection for default USB mode for USB connections:
1) Joystick
2 ) Ethos Suite 
3) Serial

**Comment by T3chDad** [comment]
That is an awesome idea!

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/235877019-741c791b-278d-4d5d-a0fa-c9fd3d3c071a.png)
