### ISSUE TITLE
"Channels" widgets shows "real output" values instead of mixers

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2611]
"Channels" widget seems to show real output values of channels, including subtrims, inversion etc. I think this is not correct, because
- color of the bar (green) suggests it should rather show mixes (convention accross Ethos is "green = mixes", "yellow = real values")
- show a numeric value of a channel (with "Value" widget) shows mixer value, like expected
- output values seem to be irrelevant in such place

So we need this widget to show "mixer" values. Or have an option to switch between the two.

**Comment by mawzthefinn** [comment]
This is as expected, it’s an output monitor widget (equivalent to the Outputs display page in Monitor or the Monitor page in Airware).

NB: Green is consistently Channel outputs, yellow is mixers in ETHOS (I just checked both the Mixer page and Outputs page displays, they consistently work this way)

If you want mixer values, use Channels as a source for the value  widget, this uses the output of  the mixer stack for each channel.

**Comment by mawzthefinn** [comment]
The Channels widget should get renamed Outputs to be consistent though

**Comment by RealTadango** [comment]
Why not add an option to make it show either?

**Comment by azaz44** [comment]
I think mixers are better. I'm scratching my head on why would you see outputs on a widget?
I would risk saying, that in 95% of cases you are interested in mixer values, as this is what shows if your programming is correct.
But if there are doubts, I think a simple switch would solve the problem.

As for colors, hmm - I have it different. My outputs show mixes in green, and outputs in yellow. And the widget shows outputs, but shows them in green. Or actually bars => green, numbers (if shown) => yellow. Do you have it different?

![image](https://user-images.githubusercontent.com/42830563/235292459-e755ad78-c17d-4308-af81-52c4bd5b51d8.png)

![image](https://user-images.githubusercontent.com/42830563/235292532-c63efbc5-85f9-437e-9664-637037a6d420.png)

BTW. This isn't by any means a high priority thing, just a wish.

**Comment by mawzthefinn** [comment]
Outputs shows what I’m sending to the aircraft. That’s usually what I want to see. I only need to see Mixer outputs when I’m debugging a programming issue vs checking the aircraft state and/or a surface condition.

**Comment by azaz44** [comment]
Then I think renaming to "Outputs" could help, and maybe fixing color problem.
I still think such widget for mixes would be very useful, but at least it should be possible to develop such thing in LUA.
