### ISSUE TITLE
[Minor] System tells "Telemetry Recovered" even after flight was reset

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2613]
This can be seen in video I posted in #2612 at [0:40]

Steps to reproduce
- power on the radio
- power on the model and get telemetry running
- power off the model and get "telemetry lost" message
- do "Reset Flight"
- power on the model again
- system tells "Telemetry Recovered" although we are on a new flight

So behavior when radio is "powered on" is not same as when we do "Reset Flight".

I marked it as minor, as there are no real issues with that.

**Comment by bsongis-frsky** [comment]
Can be tested in next nightly builds for 1.5.0
Ported to 1.4.9
