### ISSUE TITLE
Add a low value warning for RxBatt

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2614]
Several telemetry values like RSSI, VFR etc have baked in warnings with a configurable threshold. It would be nice to have a similar baked in warning for RxBatt (and maybe other sensors, where it makes sense). As it is I end up creating a logic switch and special function to warn of low RxBatt on every model.

**Comment by pstasek** [comment]
This is hard to determine what threshold this should be baked in. It's based on the battery chemistry used to power the receiver. The receiver can easily operate at 4.8V running from 4 cell NiMH but a 2S Li-Po is dead at this voltage. This can be different on each model so it's good it's not baked-in.

**Comment by lightbulbjim** [comment]
I understand, but it would be nice to at least have the alarm functionality built in (“receiver battery low” or similar). The threshold could be set by the user depending on the battery chemistry.
