### ISSUE TITLE
User manual link in Suite is out of date

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2615]
The EthOS manual is a great reference guide, however the only version available via the download link in Suite is 1.3.2.

**Comment by lightbulbjim** [comment]
Correction: I have Suite 1.4.8 installed, and the link to the manual says 1.3.2. But when I click the link I actually get the manual for 1.4.6. An extra layer of confusion!

**Comment by mawzthefinn** [comment]
Fixed as of Suite 1.4.13
