### ISSUE TITLE
Show plus and minus values in widget screen

### ISSUE THREAD

**Issue by Szonu** [FrSkyRC/ETHOS-Feedback-Community#2616]
Showing the lowest and highest values iof telemetry sensors in the widget screen would be useful

**Comment by Wolepo** [comment]
Hello,
Long press on the sensor in the widget. The options for selection are shown. The transmitter and receiver must be in operation.

**Comment by Szonu** [comment]
Tried that can’t see anything to select  plus or minus like rxbt - or lipo - or amps +
Have you a picture of settings

**Comment by Wolepo** [comment]
I like to do that:
![Optionen](https://user-images.githubusercontent.com/90325526/235341290-396620d1-970c-4a40-ba3a-7ecdcce9cd33.jpg)
![Ansicht1](https://user-images.githubusercontent.com/90325526/235341301-c12476a4-71b0-4f30-8b7a-bc2e2c7cdbd9.jpg)
![Ansicht2](https://user-images.githubusercontent.com/90325526/235341302-b2aae678-9a18-485d-8201-2abfe7052257.jpg)

**Comment by Szonu** [comment]
Thanks 
I have done it by long press on sensor source in widgets

**Comment by mawzthefinn** [comment]
As explained, this is already present via long-press and select min or max, once the desired telemetry value has been selected.
