### ISSUE TITLE
Telemetry Calculated sensor miscalculates multiplication of percentages

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2617]
I think this is a bug, but I'm not entirely sure how it's supposed to work.

Problem:
- applies to Telemetry "Calculated Sensor"
- I "Multiply" a number by a value of some channel
- I would expect, that multiplication by 100% (in this channel) does not change the value
- However it multiplies the value by 1024 instead
- Plus it adds some rounding errors. Multiplying by 10% actually multiples by 102 (and not 102.4)

Below are more details and explanation what I'm trying to do.

----
What I'm trying to do is have a counter for "battery capacity left", and be able to select different batteries, with different capacities with a switch. I baked an example in the simulator (not real world but close).

Idea is simple:
- define capacities of multiple batteries with a VAR mixer, selectable by a switch
- create "Calculated sensor" in telemetry which makes a useful number out of it
- at the end, substract "mah consumed" from that (`RBOX C1` in my case), so we know "capacity left" or "battery left"

Batteries are selected with a VAR mixer. Here just 3 values with SA switch.
As VAR only allows to have percentages (and not mAh), number defines "percentage of 1000 mAh".

![image](https://user-images.githubusercontent.com/42830563/235342502-1e270890-5140-4445-a120-068178d712b3.png)

Then I create a "Calculated Sensor" in "Telemetry".

![image](https://user-images.githubusercontent.com/42830563/235342583-d3142014-04ed-43e2-bb7a-96b6aa880637.png)

In this counter I multiply 1000 mAh by battery percentage.
Next step would be to substract real consumption at the end, but I can't do this in simulator.

Results I'm getting - if channel is 100%, I get 1024000 mAh
(expected: 1000 mAh)

![image](https://user-images.githubusercontent.com/42830563/235342617-f994f604-773c-4357-beef-c2dc32b156ba.png)

For 50% - 512000 (expected 500 mAh)

![image](https://user-images.githubusercontent.com/42830563/235342632-d3ecfec1-147f-4b66-a326-6a5381c821ae.png)

For 10% - 102000 mAh (expected 100 mAh)
Here it also introduces some rounding error.
![image](https://user-images.githubusercontent.com/42830563/235342636-9a948bb9-8a88-4a77-bc14-6833c07845d3.png)

As I say, I'm not sure how this is supposed to work. But I think results are not what user would expect and depend on internals of how Ethos is coded. Internally 100% means 1024 for Ethos, but for user 1024 doesn't really mean much.

Also, above example is just for simulator. In reality this would use function switch, different capacities, and packs would not vary in capacity that much.

**Comment by azaz44** [comment]
One more problem, not sure if related. 
I want to divide battery voltage by 14 to get single cell avg. voltage. Both counters are of unit 'V' and with 2-digits decimal precision. 

Why do I need to divide by 140 instead of 14?

![20230507_124121](https://user-images.githubusercontent.com/42830563/236677649-1e7ec1c7-72fd-4de1-ab42-3aa3b869e48c.jpg)

![20230507_124136](https://user-images.githubusercontent.com/42830563/236677655-c88a825f-d64d-4988-b886-14db47340c87.jpg)

**Comment by azaz44** [comment]
Unstale pls

**Comment by azaz44** [comment]
Still needed, unless solved in 1.5?

**Comment by bsongis-frsky** [comment]
Yes. Solved in 1.5.0 RC4
