### ISSUE TITLE
Limited FreeMix Offset range + Offset/Wight order

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2618]
I'm trying to transfer this mix from OpenTX to Ethos:
![image](https://user-images.githubusercontent.com/42830563/235434495-dc622e47-6f63-43b5-b2a0-e6aee8887fc0.png)

using "Free Mix". And I struggle, because "Offset" in "Free Mix" in Ethos is limited to -100..100 range. Is there any reason for this?
In OpenTX it was -500..500 range.

Besides that, it seems that Ethos is applying "Weight" first, and then "Offset" (tested). Exactly like on OpenTX.
However the order on screen is different, which I find confusing. It suggests, that Ethos would apply "offset" first, and then "weight", which isn't the case:

![image](https://user-images.githubusercontent.com/42830563/235434830-178bc30d-8ef0-477e-b4f9-2782f75a4404.png)

**Comment by mawzthefinn** [comment]
In 1.5.0 Offset is limited to 200% and weight to 500% in Free Mixes.
