### ISSUE TITLE
Ethos model Memory compatibility

### ISSUE THREAD

**Issue by Ze-baloo** [FrSkyRC/ETHOS-Feedback-Community#2619]
Hi,

I've bought a multiplex multiplex lentus to a friend that has a X20S.

He hasn't updated the radio firmware so i assume he has the 1.0.12 firmware.

Is his model memory compatible with my X18 updated to the latest Ethos version?

Thanks for your replies.

Best regards

Laurent

**Comment by mawzthefinn** [comment]
Yes, it is.

**Comment by Ze-baloo** [comment]
> Yes, it is.

Many thanks for your quick reply 😉
