### ISSUE TITLE
Adjust mixer settings via potentiometer in flight

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#262]
As far as I know, only Multiplex remote controls can currently set mixer adjustments comfortably in flight.

Graupner/SJ is currently working on this. Other manufacturers do not know this function at present.

ETHOS can already do this in principle. You can do this by creating a second weighting in the mixers and selecting a potentiometer as the source.

The only problem with the potentiometer is that it works from -100 to +100 percent. So the user can reverse the direction of rotation of the function. This is of course very dangerous in flight.

I thought I could change this via a special curve. But that doesn't seem to work.

So a curve that only goes from +10 to +100 would be desirable. Whether +10 is right has to be considered. The user must not be able to switch off a function completely. And he must not have the option of reversing the function.

The better option would of course be a digital encoder like the Multiplex has. You can turn it endlessly and when you switch off the RC system the value is saved. Maybe you could use the scroll wheel for the idea I suggested. Because that should be a digital encoder.

**Comment by bsongis-frsky** [comment]
I think Ethos has already everything to do the limitation you need.
On your mixer setting select an unused channel, let's say CH64
Then on CH64 add a Free Mix where source is a POT1, with weight-up = +100% and weight-down = -10%

**Comment by EngelMT** [comment]
Will test it. But -10 to +100 means that the direction of rotation is changed. At least I think so. But I will try that.

**Comment by bsongis-frsky** [comment]
You may invert the source as well if needed, add expo, change the center, etc.
