### ISSUE TITLE
"Value" widget can't show min - max values for calculated telemetry counters

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2620]
Not sure if it's a problem with the 'Value' widget or telemetry counters?

For most telemetry values I can show min or max value, like here:
![20230501_163255](https://user-images.githubusercontent.com/42830563/235469451-08635bb1-bdbe-4cfa-9a20-f66085fcfa51.jpg)

However for calculated counters these options don't show up, nor 'three bars' (hamburger menu) indicator:

![20230501_163318](https://user-images.githubusercontent.com/42830563/235469600-78c2d552-e0d9-4938-8cb6-ed3583f7545a.jpg)

Teemetry counter is defined like this (divides battery voltage by 12 to get average cell voltage)

![20230501_163412](https://user-images.githubusercontent.com/42830563/235469728-0996ef0e-b9c3-4c22-93a2-a8dc68b5868f.jpg)

![20230501_163423](https://user-images.githubusercontent.com/42830563/235469755-44f7403c-7fbb-4efa-9500-4db717f626c7.jpg)

Not sure why this is, and if by design, but I think it's super useful to have min and max for those. Or is there some other way to do this?

**Comment by Peschi90** [comment]
Yes that would be rly great!

**Comment by azaz44** [comment]
unstale please

**Comment by azaz44** [comment]
Absolutely needed feature.

**Comment by azaz44** [comment]
Great, can't wait to test it 👍
