### ISSUE TITLE
Pre-programmed mixes overwrite channel names

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2622]
When a pre-programmed mix is added, it names the default output channel after itself. For example, if I add an elevator mix then one of my output channels gets (re)named to "Elevators".

When creating a model I usually start by naming all of the output channels, so it's annoying when mixes overwrite my channel names (often the wrong channel, too). A mix should only name a channel if the channel does not already have a name.

Here is my proposal:

```mermaid
flowchart LR
    A[Run model creation wizard] --> B[Auto populate mixes based on template]
    B --> C[Auto populate output names based on mix names]

    D[Create mix in an existing model] --> E{Does the default output\nalready have a name?}
    subgraph 1[For each mix output]
    E -- Yes --> F[Don't rename output]
    E -- No --> G[Rename output following the mix template]
    end
```

**Comment by lightbulbjim** [comment]
I maybe didn't explain the situation very well. 

Here I have named my channels as I want them:

![screenshot-2023-05-02-70562](https://user-images.githubusercontent.com/4312404/235634373-6bbd557a-ff2c-411d-9931-42900190d4ef.png)

I created a pre-programmed aileron mix. I was not prompted for any channel named and I have not touched any settings in the mix (channel 1 and 2 were assigned be default):

![screenshot-2023-05-02-70664](https://user-images.githubusercontent.com/4312404/235634606-d6d6b16e-5843-4080-86d7-2590c338e4f1.png)

Simply creating the mix renamed my channels like this:

![screenshot-2023-05-02-70683](https://user-images.githubusercontent.com/4312404/235634718-307522ed-f72a-41d1-be3c-216f59baae68.png)

**Comment by mawzthefinn** [comment]
The pre-programmed mixes are normally created as part of the model creation process. It’s rare that you should be adding one after you have had a chance to name your channels. 

Channel assignment for these mixes is based on your set channel mapping and whether or not you have ‘first four channels fixed’ set in your Sticks menu.

@Wolepo - The base canned surface mixes do overwrite channel names when created, I tested. The rest of the canned mixes do not

**Comment by Wolepo** [comment]
OK. I had added new mixers. I think it is logical that when a new model is created, the channels are named according to the default settings.

**Comment by lightbulbjim** [comment]
> The pre-programmed mixes are normally created as part of the model creation process. It’s rare that you should be adding one after you have had a chance to name your channels.

I disagree. If the system is designed for flexibility then it should be possible to add any mix at any time without surprising side effects. Added to that, whenever there is a slightly more complex setup (a four servo wing in this example) I’ve found that the stock mixes are insufficient. 

I’m happy to do a deep dive into setting up a four servo wing (for example) as a user story type of thing, but that probably needs its own topic. I don’t want to distract from this issue. 

> Channel assignment for these mixes is based on your set channel mapping and whether or not you have ‘first four channels fixed’ set in your Sticks menu.

The channel mapping options don’t cover all variations. For example, all of my four servo wings have channel arrangements as seen in my first screenshot. Am I “holding it wrong”? Maybe, but instead of prescribing how a system may be used, why not allow for flexibility? Again, I’m happy to dig into this as part of a separate topic if you like. 

Regardless of all that, if a human has named something then a machine should not rename it without asking. It violates the principle of least surprise.

**Comment by mawzthefinn** [comment]
> I disagree. If the system is designed for flexibility then it should be possible to add any mix at any time without surprising side effects. Added to that, whenever there is a slightly more complex setup (a four servo wing in this example) I’ve found that the stock mixes are insufficient.
> 

But are they surprising side effects? I disagree. The mixers are very predictable in how they work. 

> I’m happy to do a deep dive into setting up a four servo wing (for example) as a user story type of thing, but that probably needs its own topic. I don’t want to distract from this issue.
> 

The stock mixers work fine for a four servo wing, you don't need to add a second until you want to exceed a 4 servo setup (where you would have to add a second mixer or chain a free mix to each side of the base mixer to expand). I'd be curious as to where you are running into issues with 4 servo wings. 

> 
> The channel mapping options don’t cover all variations. For example, all of my four servo wings have channel arrangements as seen in my first screenshot. Am I “holding it wrong”? Maybe, but instead of prescribing how a system may be used, why not allow for flexibility? Again, I’m happy to dig into this as part of a separate topic if you like.
> 

If you'd picked a 4 servo wing on the creation wizard and then remapped in the mixer to suit your desired output it would be fine and you never would have seen the issue. Canned mixers like the base surface mixers are a balance between usability and flexibility. Thus they default to a predictable standard layout that most users expect and can be remapped extremely easily for those users who want something else. I for example use a non-standard AAFFERT mapping for my sailplanes.

The current setup is what I'd consider a good balance. It in no way blocks you and assigns channels very predictably and you can trivially remap the outputs afterwards if you don't like the default setup

> Regardless of all that, if a human has named something then a machine should not rename it without asking. It violates the principle of least surprise.

Channels in ETHOS are generally named when assigned in the mixer. Adding a canned surface mixer will only rename a channel if that channel has no mixer assigned to it, because on creation they self-assign to the next available empty channel(s) once they get past ch4 (the first 4 are dictated by the Sticks menu settings)

What you've run into is an edge case due to your model creation workflow. This is not one that most users would ever encounter because they have the stock mixers created before they ever see the Outputs menu in the normal model creation flow.

I'm not saying this can't be addressed, but it's really an edge case at best.

**Comment by lightbulbjim** [comment]
> But are they surprising side effects?

I would argue that silently overwriting my channel names is a surprising side effect, yes.

As far as predictability goes, as you pointed out:

> The base canned surface mixes do overwrite channel names when created, I tested. The rest of the canned mixes do not

When choosing a mix to add there is no distinction between a "base" mix and "the rest". They all look the same, but some override your channel names and some don't.

> Channels in ETHOS are generally named when assigned in the mixer. Adding a canned surface mixer will only rename a channel if that channel has no mixer assigned to it, because on creation they self-assign to the next available empty channel(s) once they get past ch4 (the first 4 are dictated by the Sticks menu settings)
> 
> What you've run into is an edge case due to your model creation workflow. This is not one that most users would ever encounter because they have the stock mixers created before they ever see the Outputs menu in the normal model creation flow.

I understand what you're saying, but I would be disappointed if EthOS went down the road of blessed workflows. I don't want it to end up like the old JR/Futaba style systems, where if the template matches your use case then everything just works, but if you want to deviate from the standard path then you have to fight the system.

<hr />

> I'd be curious as to where you are running into issues with 4 servo wings.

This maybe belongs somewhere else, but ok, you asked! 😵‍💫

Full span ailerons are where I've come adrift. What I want to achieve is:

1. Aileron stick (plus trim) moves the ailerons and flaps.
2. The flap travel is a fraction of the ailerons, say 30% as an example. I want to assign that weight in one place (with the ability to change it per flight mode).
3. I want one place to set the aileron rates and expo, and changing those values should trickle down to the flap channel. For example, say my aileron travel is 100% and my flap (ailerap?) travel is 30%. Flipping into 50% rates should drop my aileron travel to 50% and my flap travel to 15%.
4. Aileron differential should also trickle down to the flaps (I usually put aileron differential on a per-flight mode trim).

So, how to accomplish this?

The first approach I tried is using the default aileron mix plus the canned ail -> flap mix[^1]. This works, but since the aileron _stick_ is used as the input to the mix, flap weights must be calculated and configured for each aileron rate you want to use. In other words it's no different to creating a second canned aileron mix which outputs to the flap channels.

Expo must also be configured in both the aileron and ail -> flap (or second aileron) mixes, but since it is common across ailerons and flaps it can at least be extracted into a single var.

Another approach would be to create a free mix for each flap, using each corresponding aileron output as the input. This obviously won't work, since the aileron output also includes camber (plus crow travel, but that can be isolated via a "landing" flight mode).

I think this is what I'm going to end up doing:

1. Use a canned aileron mix to capture the stick and trim and send it to two high channels, one for the left wing and one for the right. Rates, expo and differential are configured in this mix.
2. Create a var (channel as of 1.4.8, real var once 1.5.0 lands) representing the flap:aileron ratio for full span ailerons. Can be switchable per flight mode and have a weight of zero to disable the whole shebang.
3. Create a free mix for the left aileron surface. Input is the left high channel from step one. Output is the left aileron channel. Weight is 100%.
4. Create a free mix for the left flap surface. Input is the left high channel from step one. Output is the left flap channel. Weight is the var from step two.
5. Create two more free mixes for the right flap and aileron, similar to those for the left. 

I think that's as neat as I can get it without creating too much mixer soup. I'll probably use it as a template for all my full house gliders. And the result isn't terrible, but hopefully it explains why the stock mixes are not enough. If I'm missing a simple trick please clue me in!

Things that would allow this to be simplified are adding a real inputs layer and allowing differential in free mixes[^2]. Note that a wing setup like this is trivial to achieve in OpenTX 😉[^3].

[^1]: There's a bug with the ail -> flap mix BTW. If you don't already have a canned "flap" mix present then it complains about "no base mix" and won't let you add it. But you can create a canned "flap" mix, create an "ail -> flap" mix, then _delete_ the canned "flap" mix and the ail -> flap mix continues to work. In other words the "no base mix" error is unnecessary.

[^2]: Per output, as previously discussed.

[^3]: Although in fairness I must admit that I've settled on similar cascading mixer setup in my OpenTX models for all the non-aileron functions of a glider wing like flap offset, camber, snap flap and crow. I have one common mixer for all flap surfaces and one for all aileron surfaces, which each feed into the servo output channels along with the += aileron input and a := calibration mix.

**Comment by mawzthefinn** [comment]
I'll break into 2 responses

> > But are they surprising side effects?
> 
> I would argue that silently overwriting my channel names is a surprising side effect, yes.
> 

It should be very rare that you are adding any of these mixes, and they always target channels with no other mixers attached when created after model creation. That's really an edge case

> As far as predictability goes, as you pointed out:
> 
> > The base canned surface mixes do overwrite channel names when created, I tested. The rest of the canned mixes do not
> 
> When choosing a mix to add there is no distinction between a "base" mix and "the rest". They all look the same, but some override your channel names and some don't.

Ah, but there is a difference. The base mixes are normally created during model creation, the others are added by the user afterwards


> 
> > Channels in ETHOS are generally named when assigned in the mixer. Adding a canned surface mixer will only rename a channel if that channel has no mixer assigned to it, because on creation they self-assign to the next available empty channel(s) once they get past ch4 (the first 4 are dictated by the Sticks menu settings)
> > What you've run into is an edge case due to your model creation workflow. This is not one that most users would ever encounter because they have the stock mixers created before they ever see the Outputs menu in the normal model creation flow.
> 
> I understand what you're saying, but I would be disappointed if EthOS went down the road of blessed workflows. I don't want it to end up like the old JR/Futaba style systems, where if the template matches your use case then everything just works, but if you want to deviate from the standard path then you have to fight the system.
> 

Normally I'd agree with you, but in this case the 'blessed workflow' is the model creation function. There's no blessed workflow afterwards. 

Also regarding the Aileron=>Flaps mixer, there's no bug, it needs the flaps function to exist to know where to map the outputs. It's the Aileron function to Flaps function mix so both must exist for it to be valid on creation. Once created, it has output channels assigned so it doesn't need flaps anymore.

**Comment by mawzthefinn** [comment]
OK, now to address the 4 servo wing.

Use 4ch aileron mixer, aileron 1 and 2 directly assigned to the Aileron channels, remap the third and 4th aileron channel to high channels, then mix down with a pair of Free mixes (1 per side) targeting flaps. That will maintain all Aileron configuration and the ratio is your rates. 

It's essentially your solution, but with two less Free mixes (as the 100% mixes to ailerons aren't doing anything useful ) The VAR is only needed if you really want to synchronize the two Flap mix weights (I'd skip it on 1.4.8, but might do it on 1.5.0 so I can live adjust the full span mixing weight)

**Comment by mawzthefinn** [comment]
Also, FYI - in 1.5.0 you get to pick mixer channel mappings on model creation. It's the last page of the new wizard

**Comment by mawzthefinn** [comment]
Alternate method for Aileron to flap mixing.

Use the standard method (Aileron mixer, Aileron=>Flaps mixer)

Create 1 VAR mixer, use it to set rates for Ailerons
Create a second Free mix, input is the VAR mixer, output is a high channel, weight is the Aileron:Flaps ratio, use it to control Aileron=>Flaps weight

Differential on a trimmer, assigned to both mixes.

**Comment by lightbulbjim** [comment]
> The base mixes are normally created during model creation, the others are added by the user afterwards

Sure, but when choosing a mix to add there is no way to differentiate these "base mixes" from other mixes.

I feel like we are getting into the weeds. Here is my proposal:

```mermaid
flowchart LR
    A[Run model creation wizard] --> B[Auto populate mixes based on template]
    B --> C[Auto populate output names based on mix names]

    D[Create mix in an existing model] --> E{Does the default output\nalready have a name?}
    subgraph 1[For each mix output]
    E -- Yes --> F[Don't rename output]
    E -- No --> G[Rename output following the mix template]
    end
```

I'll put a copy of the diagram in the OP so the issue is easy to grok without reading all my waffle.

<hr />

> Also regarding the Aileron=>Flaps mixer, there's no bug, it needs the flaps function to exist to know where to map the outputs. It's the Aileron function to Flaps function mix so both must exist for it to be valid on creation. Once created, it has output channels assigned so it doesn't need flaps anymore.

Interesting, seems it's really no different from the aileron mixer then other than the default outputs.

> Use 4ch aileron mixer, aileron 1 and 2 directly assigned to the Aileron channels, remap the third and 4th aileron channel to high channels, then mix down with a pair of Free mixes (1 per side) targeting flaps. That will maintain all Aileron configuration and the ratio is your rates.

> Alternate method for Aileron to flap mixing.

Thanks for these ideas, out of the two I prefer the first one. Having the full cascading setup as I described is still a bit nicer to me, as it's very obvious what is happening at each step in the chain. I might end up going with your idea to trim down on the number of mixes required though.

<hr />

All in all, I hope EthOS retains its OpenTX roots. I know there are those who wanted to use FrSky hardware but didn't like OpenTX, so there is a push to make EthOS more user friendly. And it _is_ more user friendly! You can name stuff properly, reorder flight modes, the outputs page is combined with the channel monitor etc...

But there are also those (including myself) who started using the hardware _because_ of OpenTX. Now in order to stay in the hardware platform we're forced to switch to EthOS.

That means EthOS has a hard job - it needs to be easier to use than OpenTX to attract one user segment, while being at least as flexible and usable as OpenTX to retain another.
