### ISSUE TITLE
Request to disable „Sensor Conflict Message“ for individual sensor value

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2623]
When using third party sensors under certain conditions a sensor conflict message is generated from time to time. The vendor of the third party sensor may not be able to provide an updated firmware. Having an option in the sensor value configuration page of the telemetry menue to disable a sensor conflict message, similar to the option to delay Sensor lost message, might be helpful. Of course one should know what he would do using this option and it would be on his own risk.

**Comment by bsongis-frsky** [comment]
A sensor conflict is not good for the whole telemetry system. It's possible to disable the alarm, but only globally. Disable the conflict for just one sensor has no sense, because obviously it is detected by many sensors!
