### ISSUE TITLE
Flight controller integration scripts don't work over S.PORT

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2628]
Most flybarless flight controllers for helicopters deliver integration + telemetry scripts. They allow to run a script and setup flight controller parameters directly from the radio. One example is Spirit FBL which I'm using. Another one is MSH Brain / Ikon. I guess in drones world there must be same problem.

Typically there are 3 ways how you can connect FrSky RX to the controller (besides PWM)
1. S.BUS + S.PORT
2. F.PORT or F.PORT 2
3. F.BUS

All of them allow integration to work.

However, in Ethos, scripts don't work if you use "S.PORT" (no 1).
I don't know what is the limiting factor, but FBL guys claim this is a limitation of Ethos.
Surely problem is not in hardware, as in OpenTX things work (of course LUA scripts are different for OTX and Ethos).

What is the reason?
Can this be fixed?

For some of use this is a huge downgrade when coming from OpenTX.

**Comment by mawzthefinn** [comment]
Given the RB's configure over SBus+S.Port and FBus, there's no reason I can think of on the FrSky side why the FBL's can't also configure that way. It's the same electrical interface and same pair of protocols.

I'd suggest the FBL vendors take a look at the RB25S & RB35S scripts to see what FrSky is doing differently in the Lua, if anything.

**Comment by azaz44** [comment]
> Given the RB's configure over SBus+S.Port and FBus, there's no reason I can think of on the FrSky side why the FBL's can't also configure that way. It's the same electrical interface and same pair of protocols.
> 
> I'd suggest the FBL vendors take a look at the RB25S & RB35S scripts to see what FrSky is doing differently in the Lua, if anything.

I'm researching this. So far I figured out that OpenTX scripts of Spirit were using `sportTelemetryPush` and `sportTelemetryPop` to read / write parameters, by writing s.port frames directly.

Ethos script is using newer API, `LuaSensor:requestParameter`, `LuaSensor:getParameter`, `LuaSensor:writeParameter`. This seems to work over F.Port, but not over S.Port. Is this how it's supposed to be?

I see we can also use `pushFrame` and `popFrame` in Ethos, I'm trying to figure out if this would work.

**Comment by azaz44** [comment]
Let me close this. I didn't fine time to check deeply, but as of now it looks like problem is on flight controller side.
