### ISSUE TITLE
X20  fw 1.4.8.  Ne trouve plus les anciens modules de télémétrie. 

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#2630]
Bonjour, 

Depuis la dernière mise à jour 1.4.8. , la radio X20 eu.lbt ne reconnaît plus les anciens modules de télémétrie. 

FAS100S , LIPO VOLTAGE SENSOR , AMPÈRE METRE 150 A ....

**Comment by Mobidick1966** [comment]
Good morning,

Since the last update 1.4.8. , the X20 eu.lbt radio no longer recognizes old telemetry modules.
I have the problem with several RX on different planes.

LIPO VOLTAGE SENSOR FLVSS, AMPERE METER FAS150S; FAS100S; ....

when the FAS150S module is connected, the small led is red .

Tested with another X20S fw 1.4.8 Eu.LBT radio and everything works. (the LED is green).

**Comment by Mobidick1966** [comment]
Oui bien sûr... mais rien ne change.

**Comment by andika207** [comment]
> when the FAS150S module is connected, the small led is red .
>
> Tested with another X20S fw 1.4.8 Eu.LBT radio and everything works. (the LED is green).

êtes-vous sûr que les paramètres sont identiques entre les deux radios depuis le flashage vers 1.4.8 ?

**Comment by Mobidick1966** [comment]
Ma rdio est la X20 et l'autre X20S ....
Et oui avec l'autre radio cela fonctionnait .

**Comment by Mobidick1966** [comment]
> Are you saying that the same telemetry sensors work when connected to another radio (same firmware etc.) and not when connected to your radio?

yes

**Comment by Mobidick1966** [comment]
J'ai testé avec le capteur RPM et sonde températures, qui n'est pas reconnu .
Parcontre le capteur FLVS ADV lui fonctionne très bien .

**Comment by Mobidick1966** [comment]
I tested with the RPM sensor and temperature probe, which is not recognized.
However, the FLVS ADV sensor works very well.

**Comment by Mobidick1966** [comment]
Hello, good news.
I reflash the FW 1.4.8 (X20) directly on the SD card, without going through Ethos Suite, and everything works again.

Thanks for research. :)
