### ISSUE TITLE
Connectivity trouble with macOS version of ethos suite

### ISSUE THREAD

**Issue by Jeffe001** [FrSkyRC/ETHOS-Feedback-Community#2631]
Hi,
I am trying to connect my new X20 HD tx to my Mac. 

I've got bootloader version 1.4.4 so it’s up to date and when I enter bootloader mode it says on the transmitter that I am there. The tx is on firmware version 1.4.8. I then plug in the USB cord and the screen says that I am connected to the computer. The computer also sees the transmitter. Unfortunately, the ethos suite does not. I was wondering if anyone knew anything about this kind of issue? 

Thanks, Jefe

**Comment by mawzthefinn** [comment]
Most likely you have something on the Mac blocking access to the DFU capability. This is probably a Security setting, although 3rd party firewalls are notorious for causing problems as well for Mac users.

**Comment by mawzthefinn** [comment]
Glad you got it sorted
