### ISSUE TITLE
GPS Problems (Time Etc)

### ISSUE THREAD

**Issue by LaserAV-Calgary** [FrSkyRC/ETHOS-Feedback-Community#2632]
The GPS module reports back the time incorrectly.
I watched it change 5 times within 10s.
+/- 4 hours!

Time should be the most stable data of any GPS.

(X20s Latest Firmware. I had the GPS powered for 5m.)

**Comment by bsongis-frsky** [comment]
What kind of change? Only hours (perhaps a timeshift issue)? Or it is very different when it changes (hours / minutes / seconds)?

**Comment by JC-YYC** [comment]
I have the same issue with 2 New GPS-ADV sensors. The time is out by more than a day and the location coordinates are off by 1 Km.
FrSky X20S FW 1.4.7 FCC
TD-ISRM HW:1.4.0 FW 2.2.1 FCC

Rx
TDMX HW:1.5.0 FW1.08

GPS-ADV Loaded latest FW:1.8

jc

**Comment by dap35** [comment]
@LaserAV-Calgary Is it just the hour value that is off?   I did some testing with both the previous GPS and the Adv-GPS across multiple FW releases.  For me the TimeZone offset did not seem accurate or consistent with the GPS Adv.

**Comment by Szonu** [comment]
Looking at using this sensor just need the speed value for now. 
Is the speed correct.

**Comment by doloebig** [comment]
GPS correction off Transmitter Clock ist not working

TX X20S 1.4.8 RX SR10 lastets Firmware GPS Sensor oXt on RP2040.
Time, Pos, HDG usw correct dispayed in telemtrie

**Comment by jasc76** [comment]
> GPS correction off Transmitter Clock ist not working
> 
> TX X20S 1.4.8 RX SR10 lastets Firmware GPS Sensor oXt on RP2040. Time, Pos, HDG usw correct dispayed in telemtrie

Do you have GPS data within the log file ?

**Comment by dap35** [comment]
While this file is from last year, I have both the GPS-ADV and GPS in the same file, same flight.  The GPS-ADV is the first GPS, the previous model GPS is labeled as GPS2.   You can see the hour value is way off on the GPS-ADV.
[Air-Tractor-2022-11-01-20-44-50.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11565588/Air-Tractor-2022-11-01-20-44-50.csv)

**Comment by jasc76** [comment]
[FUNJET-2023-05-20-19-07-06.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11724067/FUNJET-2023-05-20-19-07-06.csv)
Here I found a log. First date is correct, then there is a gap and suddenly date is wrong

**Comment by JC-YYC** [comment]
The issue still persists with the GPS coordinates being off by almost 1 Km and the time not in sync.

**Comment by LaserAV-Calgary** [comment]
Still no fix from frsky!
Be warned! DO NOT BUY!
