### ISSUE TITLE
[Question] Would switch touch events be technically possible? Like Spektrum has

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#2633]
I discovered a very nice feature on a Spektrum TX of a buddy: Switch touch indicators. When he touches a switch on his TX he hears the function and current position of this switch. I switched from a X12S to a X20S and the gear switch is much harder to reach / find when i am flying. A system that would say the function of the switch you are touching would be very helpful for me. It would add a lot of possibilities also. So i wonder how they did this and if this would technically be possible on FrSky transmitters? If not possible at all please make a not of it when you design the next generation :)

**Comment by mawzthefinn** [comment]
That requires additional hardware in the transmitter. 

There are sensors on the iX20 and iX14 specifically for this feature, and it's flaky as all get out (lots of reports of issues with this, especially on the 2-pos switches). 

Spektrum even dropped the feature from the NX20 (which did not ship with it even though the prototypes had it)

**Comment by RealTadango** [comment]
Interesting.... still very nice feature when it works but i can see the issue with high powered RF nearby.

**Comment by bsongis-frsky** [comment]
Idea sent to the electronics team, not sure it will be accepted, it's very difficult to do it perfectly!
