### ISSUE TITLE
Keys blocked when leaving curve editing

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2634]
Found a weird problem. If entering "curve editor" from a mix, and then leaving the menu be long-pressing "RET" all keys stop working. Using touch screen fixes the problem.

Video: https://youtube.com/shorts/9_FqrCnre0U?feature=share

Sorry for "youtube short", stupid YT created a "short" and does not allow to upload it in any other way.

**Comment by mawzthefinn** [comment]
Duplicated on X18 1.4.8

**Comment by bsongis-frsky** [comment]
Duplicate of #2585
