### ISSUE TITLE
Suggestion: unit of "Percent" calculated sensor

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#2635]
As it is implemented now, the unit of the "Percent" calculated sensor is %
This is very confusing, as you then see a range for the sensor from 0% to 100%.
My suggestion would be to automatically change the unit to the unit of the selected input sensor.
So for instance, when I select the VFAS sensor, the unit would automatically change to "V", and then the range would be shown in V instead of %, which is a lot less confusing.

**Comment by mawzthefinn** [comment]
OK, that's good to note.

I'll close off the issue
