### ISSUE TITLE
CRC mismatch on model file (not usable anymore)

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#2636]
I have an RC heli model that I was setting up.  I created it previously but was going to modify it so that it would play a wav filea audio file when rescue is enabled.  I realized a sound wav file for that wasn't there so i backed out of the menu for creating the SF (SF was still there... just disabled and not linked to any wav file). I then created the sound files on my PC using TTSAutomate and put the radio in Ethos Suite mode and mistakenly copied mp3 files to the audio directory. I don't think that caused it though. I did rename the mp3 files on the PC using file explorer in the directory of the mounted storage on the radio. I renamed them to have an 'a' in front of them to make them easier to find. I then ejected the drives from the PC, and then unplugged the USB-C cable and the radio showed a CRC error with the model file immediately. It then went into add the new model wizard automatically with the same name it seems. I backed out to keep it from overwriting the model and not sure if it did or not.

I am not sure what actually caused it but the model file is not usable anymore.  I was going to maiden the heli this weekend too.  Any chance to look at the model to see why the CRC is making it corrupt?  I should have backed it up, but it wasn't completed yet so didn't think to do it (oops).  I didn't copy any model files or put any model files from the PC on the mounted drive of the radio so it wasn't that it was modified on the PC side.  I only copied files into the audio directory.

I am using the latest Ethos version as of this time on my X20S.

I attached the model file.
[m4.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11466676/m4.zip)

**Comment by Wolepo** [comment]
[m5.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11470080/m5.zip)

**Comment by agibson2** [comment]
Thanks.  I appreciate the help on the CRC error for that model.
