### ISSUE TITLE
Failsafe 'custom' not working with f.bus on Archer RS

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#2637]
I have a Helicopter setup with Spirit GT flybarless controller that is working fine except that it sees hold positions from the Rx when the Archer RS loses radio signal from my X20S (turned it off) instead of sending the 'custom' failsafe settings that I programmed in my X20S radio Rx settings.

I am using an Archer RS and things are working except failsafe. If I go into the failsafe settings on the Archer RS Rx on my X20S, I set it to custom and set aileron and elevator to go to 0 and motor to go to -100 (and then exit out back to the main menu). When I hold aileron and elevator to the top left stick position and turn off the radio, red light turns on on the Rx but the flybarless seems to see the last positions and throttle stays in hold also so motor would keep running. When I turn the radio back on (with aileron and elevator centered), Spirit GT sees whatever the current positions are again.

 I am using the lastest Archer RS firmware (updated it today after I got the Rx) and latest Ethos firmware.

I found a post by someone else having similar issues a few months ago with another flybarless system.

**Comment by mawzthefinn** [comment]
Generally when setting failsafe using serial busses, it’s best practice to set the failsafe behaviour on the FC/FBL/Stab as Sbus and FBus both have a failsafe flag that the FC/FBL/STab may listen to instead of any preset failsafe.

**Comment by agibson2** [comment]
Thanks for the info.  That option is there for Spirit to handle failsafe and that does work if I set failsafe on the radio to 'No pulses'.  The Rx has better configurability for that though (per channel failsafe settings to hold or set specific positions).  I would have preferred to have some channels hold and others go to certain positions so I was surprised it didn't work.  So is this expected behavior for Archer RS to not support failsafe or is it some kind of limitation with Spirit f.bus and Archer RS or Ethos or something else?  I didn't catch that in the manual of the Archer RS.

I was reading and some of the recommendations on forums were to set the flybarless to do failsafe if communication with the Rx and Flybarless gets disconnected,etc and to also set failsafe on the radio/tx for better configurability.

There is a note in the Spirit manual that mentions this...

> "For a PPM, Futaba S-BUS, Spektrum DSM2/X, Jeti EX Bus, SRXL/SUMD receiver types you can set the Failsafe directly in the unit. Channel values are stored immediately after clicking the Set failsafe button. In case that the signal is lost for more than 1 second it will set the values automatically in the flight."

Maybe f.bus is also expected to be the same for whatever reason and they just didn't add it.  Someone in the article problem post that I mentioned that had similar problem to me said that the Archer RS did work in f.port mode for failsafe on the radio, but f.bus did not work.  They had to go back to f.port to get the radio failsafe to work. I might actually have to abandon f.bus for this model too because I really want the per channel settings.  (Assuming his info is correct)

So is this expected behavior with failsafe not working with f.bus itself or is it some kind of issue/implementation issue between Spirit and the Archer RS (or Ethos) with f.bus?

**Comment by azaz44** [comment]
I don't know solution to your problem nor I use F.Bus. But I use Archer RS and Spirit in many models, running over F.Port.

Best configuration I found is to set Failsafe to "No Pulses" in RX, and configure failsafe properly in Spirit. This means you have failsafe configured in one place only.

Note that if you want to set 'custom' failsafe in receiver, you still need to configure failsafe in FBL despite of that. This is for cases where communication between RX and FBL goes wrong. So failsafe in FBL you need in any case. I find it a hassle to configure failsafe in two places (although I used it for a long time).

Also note, that best failesafe setup is
- zero in rudder, ail, ele, pitch
- "thr hold" level in throttle channel (not zero, typically sth between 20-40% depending on your ESC)
- some normal values in other channels (like gyro)

You don't want throttle set to zero. Otherwise, if you recover from failsafe, you motor will initiate a slow spool up instead of bailout, which is not what you want to have while in air.

Besides that, F.Bus in Spirit is there for 2 months only. Honestly I would wait a bit at this point, especially considering how big problems Brain/Ikon devs have with F.Bus implementation.

**Comment by agibson2** [comment]
The first part is understood.  I was hoping to have the best of both worlds and have both set and have that option to have a mix of failsafe settings per channel.  I do understand that you must set Spirit failsafe for the cable connection between Spirit/Rx regardless.  You wouldn't want to only do the Rx/radio failsafe.  I have failsafe set on Spirit.

A big thanks for the rest of that information.  I was curious how to handle bailout from auto but didn't think through that it would also affect loss of signal and recovery.  I incorrectly have throttle hold set to 0% (I think actually -3%).  I will research that and find best practice because I also want throttle to be zero before a flight for slow spool-up.  Is that normally a 3 position switch for throttle hold (that is what I am using)?  Current setting is down is middle and up are both -3%.  Do some people set is so that down is off, middle is 20% (ESC dependent setting) and up is 0% (or -3%)?  Or do most people have a separate switch for 0%?

**Comment by agibson2** [comment]
Looks like the ESC that I have doesn't support bailout mode.  It is always in heli slow startup mode.  No need to worry about throttle hold vs throttle cut.

Back to the subject of this report though.  I still didn't see an answer to if the Archer RS supports 'custom' for failsafe with f.bus mode or not (which protocols do support it?).  Does s.bus, f.port, f.bus support 'custom' failsafe or is that feature just considered not needed?  If f.bus does support it then it must be some interaction between the Rx, Spirit, or Ethos for Archer RS on f.bus.

**Comment by agibson2** [comment]
Someone in a forum mentioned that the Spirit GT flybarless might see a failsafe flag and ignore the Rx (using the flybarless's failsafe settings instead) so maybe that is what is happening.  I can't find any kind of f.bus troubleshooting device (show output from f.bus) between Rx and flybarless so I have no way of confirming that.

It would be good to know if it is supposed to work or not though on the Archer RS.  I haven't found any information that would say it doesn't so maybe I should assume it does work and the flybarless is ignoring it because it is getting a failsafe flag in the protocol form the Rx.
