### ISSUE TITLE
No sound after radio reboot - Version 1.4.8

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#2638]
Version 1.4.8

Sound is empty after resetting the radio when  configuring a special function to play track. 
the configuration went fine, but if you turn off and on the radio the value became blank and no sound is played. 

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84532808/91ef0d1e-e814-48d6-b830-90e6fe1b374f

**Comment by mawzthefinn** [comment]
Try a different SD card? That looks like a failure to write the model configuration on shutdown.

**Comment by mawzthefinn** [comment]
@strgaltdel If the files were located in the wrong location, they would not play before the reboot.

The issue presented is the model loading without the files being selected in the Special Function, the most likely reason for this is the model file not being properly saved on reboot, which is usually a card issue.

**Comment by bsongis-frsky** [comment]
The function is global, there is a bug in this case!
