### ISSUE TITLE
get RxBat of secondary access reciever

### ISSUE THREAD

**Issue by Nerenye** [FrSkyRC/ETHOS-Feedback-Community#2639]
I tried to get the RxBat voltage of a second access reciever on the same model but with different power source.

it just shows only rxbat from rx0 wich is what ever turns on first

am i missing something?

**Comment by mawzthefinn** [comment]
You only get internal sensor data from the receiver actively sending telemetry. Only external sensors fail over between receivers (if wired correctly)

**Comment by Nerenye** [comment]
Why is only one RX transmitting? you bind all of them with telemetry enabled so i thougt all of them would send data.
more so since they are not failover connected via sbus .... both of them are absolutely independent

**Comment by mawzthefinn** [comment]
The telemetry system in ACCESS/TANDEM/TWIN is designed for redundancy across up to 3 receivers and one telemetry bus, not multiple independent receiver sets sending telemetry. As such, only the current primary receiver is sending at any given point.

**Comment by mawzthefinn** [comment]
Closing this off as the observed function is as per the ACCESS documentation.
