### ISSUE TITLE
x12s 1.0.6 écolage with cable

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#264]
hello frsky,
in ethos 1.0.6  cable schooling is possible?
I tried with a friend but without success ..... impossible to see the 4 student channels on my radio in master mode ??
in student mode no more success! 
thank you for your information .

**Comment by bsongis-frsky** [comment]
I will check it, it should work

**Comment by bsongis-frsky** [comment]
Link with #227

**Comment by bsongis-frsky** [comment]
Both modes fixed & tested today on X12S
