### ISSUE TITLE
SR8 PRO + R9SX

### ISSUE THREAD

**Issue by SebskiJsy** [FrSkyRC/ETHOS-Feedback-Community#2640]
Trying to figure out weird glitches on my plane,

see attached simulated logs (at home) when 2.4 goes out of range (low RSSI) it changes RX UID is this correct behaviour ???

tested on Tandem Xe and X20s - same happening

![unnamed](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/92789456/215cd6e2-5dd9-42df-8e89-b483abf05695)

**Comment by yak-54** [comment]
how old is the SR8 PRO ?
