### ISSUE TITLE
LUA / possibility to get telemetry min / max value

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2641]
I wrote a script to log each flight to a file together with values of selected sources. But I can't find any way to read minimum or maximum values of telemetry counters in LUA. I tried things like
```lua
system.getSource("RSSI-")
```

which used to work in OpenTX, but this doesn't work. Values must be there, because built-in `Value` widget can display them.

It seems to me that `Source` could have methods for it, so besides `value`, `stringValue`, `rawValue` it would have `valueMin`, `stringValueMin`, `rawValueMin`, `valueMax` etc.

Or is there any other way to get this value? I think it is super useful things for widgets too.

**Comment by Storchy1** [comment]
try this for min:
source = system.getSource({name="RSSI",options=2})
and for max:
source = system.getSource({name="RSSI",options=4})

**Comment by azaz44** [comment]
> try this for min: source = system.getSource({name="RSSI",options=2}) and for max: source = system.getSource({name="RSSI",options=4})

It works! Great, thanks.

@devs: I think then this story could be just about updating the doc and / or including constants for these values. They are not defined ATM or maybe just undocumented:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/0cf07d46-79ba-495e-9b49-dbeb967f681f)

**Comment by bsongis-frsky** [comment]
Good guess @Storchy1 :)

**Comment by bsongis-frsky** [comment]
It will be `OPTION_SENSOR_MIN` and `OPTION_SENSOR_MAX` in 1.4.9
