### ISSUE TITLE
Configure menu does not work for ELRS LUA on Twin Xlite

### ISSUE THREAD

**Issue by ChrisW401** [FrSkyRC/ETHOS-Feedback-Community#2646]
After loading the ELRS LUA onto my Twin Xlite, when I select Configure in Options, I'm taken to a blank screen. I'm using a Happymodel 2.4g ExpressLRS ES24TX Slim Pro module.

**Comment by mawzthefinn** [comment]
What firmware on the module? The script is for ELRS 3.x

Just tested on my TWIN X-Lite running 1.4.8 and ES24TX Slim Pro running 3.2.0 and all is working correctly.

**Comment by ChrisW401** [comment]
I have 3.2.1 installed on both the module and receiver. The TWIN X-Lite is on 1.4.8, as well.

**Comment by ChrisW401** [comment]
Could it be the way I'm getting the script onto my radio? Currently, I'm creating a LUA script in VSCode and pasting the code from here into it. Then, I put it in a folder titled 'elrs' and put that folder in another folder called 'scripts' which is on my radio. I have the module switched on which allows me to access the option to configure ELRS, but I just get an unpopulated screen.

**Comment by mawzthefinn** [comment]
That could be, I'd suggest just downloading the whole code package from Code->Download Zip on the main GitHub page, then copying the elrs directory over to your scripts folder.

**Comment by ChrisW401** [comment]
Just tried that, and the issue remains. For good measure, I also put crossfire and multi on the radio, and it looks like multi works fine, but crossfire is having the same problem.

**Comment by ChrisW401** [comment]
Just to make sure, in my radio’s memory, I should have radio/scripts/elrs/main.lua? I also tried putting the scripts folder in flash memory with no success.

**Comment by mawzthefinn** [comment]
Yes, that's the correct location. Won't work on flash.
![screenshot-2023-05-18-31188 Small](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/34381975/d441f904-c165-4f9a-95e9-aace442e41a1)
![screenshot-2023-05-18-31194 Small](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/34381975/27dc1386-d05a-4e52-80ec-2a62b146bc69)
![screenshot-2023-05-18-31198 Small](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/34381975/238cdb75-2050-4189-9021-e4db1a3c066b)
![screenshot-2023-05-18-31206 Small](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/34381975/5084620b-8430-40b7-bb5b-13973227bdad)
![screenshot-2023-05-18-31210 Small](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/34381975/8b27fe11-1e92-46ab-ab32-130fb411d233)

**Comment by mawzthefinn** [comment]
Yes, bind is controlled by the bind phrase, so should still work.

There's one minor difference, I'm running 3.2.0 on my module, not 3.2.1

**Comment by ChrisW401** [comment]
Forgot to mention that I reflashed to 3.2.0 on both the Rx and module.

**Comment by ChrisW401** [comment]
Here's what I have for my receiver and module respectively:
<img width="397" alt="Screen Shot 2023-05-19 at 1 43 42 AM" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/119383991/d307dd86-7051-44c0-bb52-afd2832ea8c1">

<img width="380" alt="Screen Shot 2023-05-19 at 1 45 19 AM" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/119383991/f10c1b25-d463-412f-980a-f205257543c5">

And here is what I'm getting for the module with the LUA script
![screenshot-2023-05-18-46416](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/119383991/87622bf4-442f-48f8-a6b5-7c1c6eeaab99)

![screenshot-2023-05-18-46420](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/119383991/2601fee8-b577-4352-a892-120672e2e5d8)

**Comment by mawzthefinn** [comment]
What light activity do you see on the module?

**Comment by ChrisW401** [comment]
It starts with a rainbow briefly, flashes orange for a bit, and then flashes green and yellow and then fades out and flashes green and yellow again.

**Comment by ChrisW401** [comment]
It’s seated fully. I’m hoping it’s nothing wrong with something inside the module as I don’t have a screwdriver long enough to open it up.

**Comment by ChrisW401** [comment]
My radio has randomly stopped turning on. I guess there’s nothing I can do now. Thanks for all the help!

**Comment by mawzthefinn** [comment]
I'm very sorry to hear that. FrSky service is quite good and I'm sure they'll get you sorted.

Given the radio is having issues, I suspect that's the cause of this problem as well.
