### ISSUE TITLE
GPS Time Correction

### ISSUE THREAD

**Issue by doloebig** [FrSkyRC/ETHOS-Feedback-Community#2647]
PS correction off Transmitter Clock ist not working

TX X20S 1.4.8 RX SR10 lastets Firmware GPS Sensor oXt on RP2040.
Time, Pos, HDG usw correct dispayed in telemtrie

**Comment by FlyDennis** [comment]
I have the same issue on my X20

**Comment by jasc76** [comment]
I'm also affected ....

**Comment by jasc76** [comment]
Any news on this ?
