### ISSUE TITLE
[wish] Play Value without unit

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2648]
This relates a bit to https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2397 in a sense that it tries to make stream of voice messages more manageable.

I would love the possibility to remove units in "Play Value" special function. So when it's reading altitude, it would just say "70" instead of "70 meters". It would be best if it's an option of each individual SF.

**Comment by bsongis-frsky** [comment]
Duplicate of #3320
