### ISSUE TITLE
Internal Battery Discharge to Storage Voltage Function

### ISSUE THREAD

**Issue by 2xWhiskey** [FrSkyRC/ETHOS-Feedback-Community#2649]
The TWIN X Lite comes with a LiPo battery that has an unconventional connector which prevents users from easily maintaining their battery with external charging hardware.  I would like to to see a user-initiated radio function that prepares the radio for long periods of storage by discharging the battery to storage level which would prolong good battery health and avoid premature degradation.

For example:  It is the end of the flying season and I will not be using the radio until the next flying season.  I could then go into the radio's System menu and initiate the storage function.  The radio would then proceed to either discharge or charge the internal battery to the recommended storage voltage and then automatically power off.

As it is, the internal battery fits with no spacing tolerance to allow for puffing of the cells.  Improper care of lithium polymer cells, such as extended storage periods at full charge, can cause them to expand.  What would happen first?  The cells will pop or the radio itself will break apart to make room for the expanding gases.

**Comment by koakumaping** [comment]
low c lipo, no problem

**Comment by 2xWhiskey** [comment]
Thank you, I was unaware of this.
