### ISSUE TITLE
ergonomics, reasoning

### ISSUE THREAD

**Issue by JaroslavFalcon** [FrSkyRC/ETHOS-Feedback-Community#265]
Digital rssi, it's nice even that the frequency is displayed. Thank you
Please, you need to think about the use and practice.
It is necessary to take into account pilots with poorer eyesight.
There are a lot of places in the top line. The information could be side by side and would be beautifully legible.
The same is true when displaying usec on the monitor.
The difference is LCD PC monitor vs display on the radio.
The title of Ethos is very large, and it is completely useless information.
The logo can be maximal with animation at boot and consequently not needed.

**Comment by MrD-RC** [comment]
If you want it really big, you can set it on the home screen.

![image](https://user-images.githubusercontent.com/17590174/118536364-94ad2880-b743-11eb-9f3f-681e2b2b24e3.png)

**Comment by JaroslavFalcon** [comment]
:-)
I exchange that I can.
If we approach it this way, then they didn't have to add anything.

it's about that, so that the top bar is used efficiently

**Comment by Nicholas-Luoyi** [comment]
Do you mean you want this?
![image](https://user-images.githubusercontent.com/58321103/118579307-6a4d8080-b7c0-11eb-9e8a-46e17b96e598.png)

**Comment by JaroslavFalcon** [comment]
Yes
this is nice.
but the pictures attached here are from a PC, where it is large and easy to read.
I wanted to point out in general
the display on a PC on a large monitor is different than it actually is on a small LCD

some texts are too small
it is necessary to use the space to the maximum

**Comment by JaroslavFalcon** [comment]
![frsky](https://user-images.githubusercontent.com/42203764/118613453-0f675980-b7bf-11eb-8f9e-33b9f55daf52.jpg)

here is a photo of the fact.
you see the difference
the physical display is even smaller

**Comment by JaroslavFalcon** [comment]
for example
1) rssi and frequency would be side by side and and not below each other (beneath me)
2) I would narrow the bars on the output monitor and enlarge the text on the bottoms

_sorry my english is not the best_

**Comment by bsongis-frsky** [comment]
You should update the bitmaps on your SD, you seem to have the old ones

**Comment by JaroslavFalcon** [comment]
I have now updated the bitmaps.
There are only pictures of the model. users folder.
This is probably not related to that.
I don't understand exactly why bitmaps are updating

**Comment by MrD-RC** [comment]
The bitmaps on the flash drive I’m guessing. They are in the X20-FLASH.zip file, and the need to be put on the USB device with less than 8MB.

**Comment by bsongis-frsky** [comment]
There will be an alternative UI available later with bigger text
