### ISSUE TITLE
Telemetry screens controlling switches

### ISSUE THREAD

**Issue by miksterr** [FrSkyRC/ETHOS-Feedback-Community#2650]
![IMG_2008](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85661910/d43bbfb8-0886-43d8-b56c-68ccb8eac8b3)
See pic as may make it clearer.

XE
1.4.8

I am using Lothar's script to really highlight toe action of one of the 6 pushbuttons) Inav use for me...

Wondering if there is a way to make a second page with another 6 settings selected by the same 6 switches?

So the action is page specific.

Thank you.

**Comment by strgaltdel** [comment]
thats not an Ethos- git-issue, 
you can apply the typical lua related methods:

-copy script folder
-change RegKey and name of the widget in the source

so you've cloned the widget.
in case it has a "clean" code without misuse of globals you can run it in another "instance"
if not, contact the author

regards

**Comment by miksterr** [comment]
> thats not an Ethos- git-issue, you can apply the typical lua related methods:
> 
> -copy script folder -change RegKey and name of the widget in the source
> 
> so you've cloned the widget. in case it has a "clean" code without misuse of globals you can run it in another "instance" if not, contact the author
> 
> regards

Hi. I understand I can make another screen however will the 6 buttons be able to control these 'shortcuts" or just have 6 options?

**Comment by strgaltdel** [comment]
it would be possible to enable a complete another function setup of the buttons with some tuning in the source and FN button config.
for example
in case one make use of a source script as a "middleware" so that the widgets could propagate which one is active
...

**Comment by miksterr** [comment]
> it would be possible to enable a complete another function setup of the buttons with some tuning in the source and FN button config.
> for example
> in case one make use of a source script as a "middleware" so that the widgets could propagate which one is active
> ...

Hi. I have no idea how to do this - (Hence why I am asking) so you are saying it is possible to make a second screen with 6 more "buttons" with other functions?

**Comment by strgaltdel** [comment]
In principle, Ethos already offers this possibility as of 1.5

As roughly described:

In order for the function keys to be able to trigger different "tasks" depending on the situation, both the switching state and the information of an "operating mode" of the respective active widgets are required.

For this purpose, an LSW can be defined with the switching state and state of a "Lua source variable".

In addition, a corresponding lua source script is needed that "supplies" this variable.

The variable could be set by the respective active script.
Requirement ethos 1.5
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2555

As far as I understand the purpose of the issues on git, this discussion misses the point of the issues, as it is not an Ethos bug or an extension request.

I therefore suggest moving the whole thing to rcg and close this issue.
The best thing to do is to contact the author of the widget and refer to this issue.
i'm sure FrSky doesn't see need for any action

maybe it is also a trigger to deal with the lua programming by yourself

regards
udo

**Comment by bsongis-frsky** [comment]
This enhancement will be possible using your Lua scripts on 1.5.0. Perhaps you could check if everything works correctly in the latest 1.5.0 nightlies?
