### ISSUE TITLE
No logs written (ver 1.4.8)

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2651]
Hi

I use a global function bound to my arming switch to record logs. Today I had the bad experience that not all flights were recorded. I can't say why, just that a lot of files are missing :-(
Some were recorded, some not. There is no pattern I could recognize....

**Comment by bsongis-frsky** [comment]
Are you sure that your SD is good? What happens when you say that files are missing, the SD doesn't work anymore?

**Comment by jasc76** [comment]
The SD doesnt show any signs of issues. Its a Sandisc.
But back to the issue itself: The radio just didn't record log files for some flights. I have a global function tied to my arming switch, so I dont need to set it up for every model. The models in question already created log files some time ago but not this weekend.

**Comment by bsongis-frsky** [comment]
Perhaps the global flag is not correctly taken into account? Perhaps a model change with the switch enabled?

**Comment by jasc76** [comment]
Hmm I dont know and can only test on the weekend.... I have this global function for some time now and never noticed an issue. I also cannot relate it to 1.4.8 because I only look sporadically into the logs. But I'm certain the model that is missing created logs before and after this weekend I didnt have any log from this model. In fact it happend with 2 of my models. But 2 others worked.....

Model change with switch enabled is not possible because its my arming switch and its included in the preflight checks.

**Comment by jasc76** [comment]
Today again.... This time I have a log but with 0kb .. The first flight logged fine, the second flight nope .....
Other models/flights in between, before and after worked fine. At the same time its not only one model causing issues.... Very strange.... I still try to find a pattern

**Comment by jasc76** [comment]
Argh …

i got hit by the oXs GPS time issue

it reset my clock to 2015 :-(

**Comment by mawzthefinn** [comment]
Closing this one off as it's been identified and the logs were written
