### ISSUE TITLE
[wish]XE use internal 2.4G antenna

### ISSUE THREAD

**Issue by koakumaping** [FrSkyRC/ETHOS-Feedback-Community#2652]
Frsky XE used the x18 rf board, and connect the antenna to the extranl port.
Can add an option to change to internal 2.4G antenna, then user can add an extra antenna to get more stable 2.4G singal ?

**Comment by bsongis-frsky** [comment]
But it means we will offer a new option which will be unuseable by 99.99% of XE users. 
To do it correctly we should:
1) add an option in System / Hardware: "RF board replaced by X18 RF board"
2) offer the option you are missing, only if the board is replaced
Do I understand correctly?

**Comment by koakumaping** [comment]
> 

The selled XE is already installed the X18 rf board.
Only need add an option in Model / RF menu
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4099388/a61bc8a0-3520-4de7-83c7-5fae2c15714c)

**Comment by Adelaxie** [comment]
as we discussed it's not only about the ETHOS menu, the RF module is different from X18 RF even though they share the same PCB board.
Not suggesting doing so and hope you understand.

**Comment by koakumaping** [comment]
en, the boss tolded me by wechat.
