### ISSUE TITLE
Possibility of calibrating sensor FLVS

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#2653]
I would like if it were possible to can correct the voltage of each cell independently because there are some sensor FLVS thatcome wrong factory calibrates and does not match the voltage they indicate with the one that really has

**Comment by Wolepo** [comment]
Shouldn't the individual cells already be added to the telemetry menu? Then they would be editable.

**Comment by Wolepo** [comment]
Didn't Bertrand promise a long time ago that the individual cells would be listed in the telemetry menu?

**Comment by Wolepo** [comment]
In the widget, you can view but not edit each individual cell. It is not possible to create a weighting and an offset for each cell to compensate for the measurement errors of the sensor.
