### ISSUE TITLE
[wish] Better control over LCD display per model

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2659]
Ethos allows to use sources for "LCD Brightness" and "LCD Sleep Brightness":

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/3e513fda-3b19-4823-9284-79e84f2541d4)

I use this feature, to control brightness with channels. Thanks to this, I can control brightness per model, and depending on situation. So
- in "simulator" model my brightness is low (because it is used indoor), and "sleep brightness" is completely black, so screen is mostly off
- for outdoor models mu brightness is maximum, and "sleep brightness" is black, so screen goes off
- unless model is powered on (RSSI > 0), then "sleep brightness" is maximum. This way when model is on power, screen is always on

It's a great feature of Ethos and can be used in many creative ways.

However there's one problem.
- if you set both "Brightness" and "Sleep Brightness" to maximum, display is always on. But radio still goes to "sleep" mode (although this is not visible to the user)
- as a consequence, pressing a button doesn't do anything. Because radio is in sleep mode, so first button press will "wake it up" first.
- this feels weird, because you try to switch the screen during flight, and it doesn't work. Moreover you never know, if it's in sleep or not, so you never know if you need to press the button once or twice.

### Proposed solutions

There are many ways to possibly fix this problem
- quick one: don't enter sleep mode, if "sleep brightness" >= "normal brightness"
- another one, make keys work always, even if radio is in sleep (like on a PC. We all learned to wake up the screen with mouse or shift key or sth similar and it works fine). Maybe an option for that would be nice.
- more clean one: allow to control "entering sleep" with a source. So we could bind some channel, and if channel > 0% --> enter sleep mode (still with some timer, so user can't mess the system and not recover)
- maybe even better -- add another option "Source" to this menu, so we would be able to keep radio awake over some channel
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/7c501897-7479-47f5-b105-afb6eab01ffc)

**Comment by builda1** [comment]
I have my screen brightness set up on a slider so i can turn the brightness up or down just like the volume-then when you don't need to look at it, you can turn it off without looking at it to turn off!

**Comment by azaz44** [comment]
> I have my screen brightness set up on a slider so i can turn the brightness up or down just like the volume-then when you don't need to look at it, you can turn it off without looking at it to turn off!

Yes, it can work like that. But I want to fully automate it - one less thing to think about, plus you don't reach sliders easily while flying helicopters.

@devs
I just realized there's another way - have a "Special Function" to override LCD. This is something what OpenTX has.

But I think a super simple fix - don't enter (or leave) sleep mode, if sleep brightness is not smaller than normal brightness - will do.

**Comment by azaz44** [comment]
no stale, and a really needed feature

**Comment by azaz44** [comment]
Please unstale, this still need solution.

**Comment by builda1** [comment]
Why don't you just set the screen brightness up on a slider like I do then you can have it on all the time or you can turn it off?? Doesn't have to be complicated with a special piece of code written-realistically, when people are flying, they are not looking at the radio, There is enough buttons and sliders to be able to set something up. as I said before, I personally use a slider for the screen brightness and I use one for the volume as well. I've never run into a situation where the screen turns off on me, or I haven't been able to see it when I need to, especially with the screen on a slider because I can tell it to stay on all the time or I can turn it down. You could always program something, so that stick movements will make the screen come on as well. In fact, I think that option is already in Ethos, so you don't have to worry about an extra button push!! Geez we have it so hard these days don't we, worrying about having to press a button twice to get the screen to come on lol, it was only 20 or 30 years ago. We were lucky if we had a screen at all lol. That's just my $.10 anyway, based on what I do for my own situation, you may find you can sort it out with a combination of a simple logical switch and thoughtful use of the special functions and also the radio menu🤷‍♂️ 👍

**Comment by builda1** [comment]
> > Why don't you just
> 
> 
> 
> Yes, you can adjust your volume, screen brightness, trims, calibrate analogs, reset timers, switch telemetry screen and bind receiver before every flight, but you know, it's 2023 :) Maybe for you programming is an obstacle, but some of us want and love Ethos to do exactly that, programming, not to avoid it. If I think about programming things in radio and then never having to think about screen brightness or volume for next 5 years, or - like you propose - messing with sliders for next 5 years, then my choice is so obvious.

Well, it wasn't supposed to stimulate such a hostile response , I guess to answer your initial request at the beginning of this post, you've just answered it yourself-you love programming stuff so go program that's the joy of logical switches and everything else there's always a way. 

Sometimes, I wonder how people ever managed to get by when there was no such thing as the remote control for the Tv, let alone email or cell phones! Just think when this hobby started most radios only had one stick, and if you were lucky you had a switch! How on earth did those people ever manage to get through a day flying? No disrespect, but you've answered your own question in your response to me-you love programming things, so go for it! No need to be hostile!! Hope you get it sorted👍

**Comment by azaz44** [comment]
> Sometimes, I wonder how people ever managed to get by when there was no such thing as the remote control for the Tv, let alone email or cell phones! Just think when this hobby started most radios only had one stick, and if you were lucky you had a switch! How on earth did those people ever manage to get through a day flying? No disrespect, but

I think you're missing the point a bit. You seem to assume that if somebody wants a remove for TV, he's unable to operate the TV without it. This isn't the case. Remote just makes life easier. With such arguments we can stop all innovation because most things can be done "old" way. Certainly neither Ethos nor OpenTX would not be needed in such case.

**Comment by bsongis-frsky** [comment]
Added to 1.5.0 RC4:
If brightness(backlightON) == brightness(backlightOFF) then backlight is ON and the touch is active
