### ISSUE TITLE
Butterfly offset/curve per channel

### ISSUE THREAD

**Issue by bbdmarch** [FrSkyRC/ETHOS-Feedback-Community#266]
I've been looking at the butterfly mixer on an x20s and noticed a couple of issues...or at least for  the way I prefer to do butterfly mixing.

When I deploy butterfly, on a glider, using either a switch or slider, I want to achieve the following results, flaps only until 50% of the slider or middle switch position, then the ailerons deploy.

I can achieve this using a couple of free mixes but not using the butterfly mix, as there is no means to, either, use an offset or apply different curves to the individual outputs to stop the ailerons from deploying before 50%. 

The only option on the butterfly mixer is a global curve for all the outputs, there is no option for a offset in the mix, either globally or individually. 

Lastly can a means of slowing the outputs, individually, be added too??

**Comment by bbdmarch** [comment]
I've been thinking about how to implement this and came up with the following...

Current layout
Name                            Butterfly
Active Condition.         Always On
-----------------------------------------------------
Input.                             - - 
Curve.                            - -
         +Add new Curve
 -----------------------------------------------------
Channel Count.              5
-----------------------------------------------------
Weight.                          10%
Output.                           CH4 (Aileron)
               Mixer line graph
               Output line graph
-------------------------------------------------------
Et Al.  



Proposed layout
Name                            Butterfly
Active Condition.         Always On
-----------------------------------------------------
Input.                             - - 
Curve.        Aileron.      - -
       +Add new Curve
                   Flaps.         - -
        +Add new Curve                      
                   Elevator.     - -
       +Add new Curve

Slow.          Aileron.      - -
                   Flaps.         - -
                   Elevator.     - -

Differential Aileron.    - -

Trim.                             - -
 -----------------------------------------------------
Channel Count.              5
-----------------------------------------------------
Weight.                          10%
Output.                           CH4 (Aileron)
               Mixer line graph
               Output line graph
-------------------------------------------------------
Et Al.  

I've added a + curve under the initial curve for each of the Aileron, Elevator, Flaps incase you want to add expo over and above the curve, not sure if it's needed.....

With the slow function it shouldn't interfere with the functioning of the ailerons/elevator when they are being used  via the gimbal input, to retain control of the plane 

Wasn't sure about the differential being needed in the mix, as it should be in the Aileron mix. 

Trim I was thinking of a check box to either allow the trim to be applied to the mix or not..... So the aileron/elevator trims don't effect the function of the mix.

I'm not sure if what I'm suggesting is even possible.....

**Comment by bbdmarch** [comment]
Formatting looks wrong on the post so I've added a word document with it in too
[Butterfly mix.docx](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6564100/Butterfly.mix.docx)

**Comment by jfint** [comment]
Since this one has been assigned, maybe it could be combined with #296 ?

**Comment by jfint** [comment]
At a minimum butterfly mix needs to have a separate curve for the elevator. It's great that you can do the elevator in this one mix but currently it's not terribly useful since it must follow the curve that the flaps follow and the elevator on most airplanes/gliders needs a different curve, one that we would traditionally call negative exponential.

**Comment by jfint** [comment]
Bump for this.

**Comment by jfint** [comment]
How can you post that "Butterfly mix is fixed" without this?
