### ISSUE TITLE
X-Lite Twin: elrs telemetry

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2660]
Hello.

Please add telemetry support in elrs-compatible mode. But better, make support 3.x.x elrs-compatible mode.

Or just release a Twin/2 receivers: without GFSK-tranceiver, and two anthenna variants:
 - smd (for woops)
 - 2 anthenna switch diversity with PA+LNA (for 5+ inch quads and airplanes)
 Thanks

**Comment by r1000ru** [comment]
Can anyone say about the prospects of solving this issue?

**Comment by EDFjetRC** [comment]
I agree with  r1000ru 100%. We need long range diversity antenas in LORA mode only. Or at least telemetry support in elrs-compatible mode.
