### ISSUE TITLE
extended trims

### ISSUE THREAD

**Issue by jeromeboutte** [FrSkyRC/ETHOS-Feedback-Community#2662]
hello to all,
 extended trims are no longer in the latest version 1.4.8 I no longer have options in my x20s?

**Comment by mawzthefinn** [comment]
Extended trims became the Range setting, and are now fully configurable (instead of on/off).

Set your Range to 100% on the trimmer in question in the Trims menu for the same behaviour.

**Comment by mawzthefinn** [comment]
Closing, answer provided
