### ISSUE TITLE
SxR lua self check not working on frsky X10S

### ISSUE THREAD

**Issue by slopingoff** [FrSkyRC/ETHOS-Feedback-Community#2664]
The self check function in the SXR widget is unable to be activated (just skips past on scrolling)on my X10S running Ethos version 1.4.8.The only way to activate is to setup channel 12 on a switch.

**Comment by mawzthefinn** [comment]
Self-Check on the SxR menu only works with Archer SR’s on firmware 2.1.10 and later, and Archer Plus receivers. If you are running an ACCST SxR, R9 Stab or an older firmware on an Archer SR, you use Ch12.

NB- the receivers that can use Self-Check in the menu will not self-check off Ch12. So if your receiver does that it’s either an older unit or an older firmware without support for that feature.
