### ISSUE TITLE
X10s after update to 1.4.8 not binding 

### ISSUE THREAD

**Issue by hamelsveld** [FrSkyRC/ETHOS-Feedback-Community#2665]
Hi,

I've updated my x10S to Ethos  X10EXPRESS version 1.4.8 #23c0d292 and now the radio is not able to bind anymore. I've also updated the ISRM module to ISRM-S-X10E_2.1.6 and that did not solve the issue. Once I go to 

RF System > Internal module> "set" I get "no response from module.

Trying to bind a R8 Pro on access protocol. 

Please advice, 

Greetings

**Comment by mawzthefinn** [comment]
Do you have an X10S or an X10S Express? 

That behaviour sounds like an ISRM-upgraded X10S flashed with the wrong firmware. The ISRM Upgrade does not use the same firmware as the X10S Express ISRM.

**Comment by hamelsveld** [comment]
Hi,

Well it's a transmitter I got from a friend to see if I can get it up and running again and have no idea if it's an express or not. is there anyway I can see that in the software? because on the outside of the transmitter it does not say much just
HORUS X01/x10s
X10SFCC:xYFX10CSP
and on the front is says X10S

**Comment by mawzthefinn** [comment]
Does it say ACCST or ACCESS on the front?

If it says ACCST it's not an express. Then you need to verify you have an Internal ISRM module (since you didn't do the upgrade yourself, it may have the original iXJT module which is not supported in ETHOS)_

**Comment by har1fr** [comment]
Bonjour j'ai le même problème avec x12s ISRM ETHOS installé sans aucun problème, mais aucun de mes récepteurs ne se connecte avec la radio, le module ISRM ne répond pas, j'ai le même message que HAMELSVELD

**Comment by yak-54** [comment]
have you update the receivers as well ?
they need to be on ACCST D16 v2.1.0+

**Comment by yak-54** [comment]
I have  3 X12s all with ISRM and on ethos i do use X6R and X8R and S6R with out issues they are all on FCC firmware
you know you have to bind in D16 mode 
are you using FCC or LBT 
you know if you put the wrong version firmware  on it it will stuff it ?

to me sounds like your mixing up firmware FCC or LBT

**Comment by har1fr** [comment]
@yak-54 
si vous avez le firmware en FCC et LBT si possible de me les envoyez merci

**Comment by yak-54** [comment]
on lets try to update the firmware on ISRM use this firmware up zip it put on the SD card

[ISRM-v2.1.6.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11611763/ISRM-v2.1.6.zip)

**Comment by har1fr** [comment]
Merci, j'ai ce firmware, mais le module ne répond pas pour la mise a jour @yak-54

**Comment by bsongis-frsky** [comment]
@har1fr c'est quelle radio exactement ? j'ai peur que vous y ayez installé un firmware non compatible

**Comment by har1fr** [comment]
x12s @bsongis-frsky

**Comment by har1fr** [comment]
j'ai bien installé le firmware opentx internalaccess-eu avant d'installer ethos @bsongis-frsky

**Comment by yak-54** [comment]
did you fit the module your self or did you buy from horus rc already with the ISRM installed ?

**Comment by yak-54** [comment]
i have 3 x12s with ISRM 2 i did install my self and that came from horus rc that had it installed the one i got from horus rc take diffract firmware

**Comment by har1fr** [comment]
Installer moi-même, il y a une étiquette EU LBT sur le module @yak-54

**Comment by yak-54** [comment]
This the warring  on the Horus rc site about firmware 
FrSky ACCESS Upgrade ISRM RF Module for ACCST Horus X10/X10S/X12S
 $49.99


Important note: We've already upgrade the ISRM firmware to the latest version,there's no need to uprade any ISRM firmware!!! The module might be damaged if you upgrade the ISRM with the wrong firmware.

if you tried to update it with the wrong firmware will lock it up

**Comment by har1fr** [comment]
oui j'ai lu la note et parler au téléphone avec le vendeur avant d'acheter le module j'ai pris toutes mes précautions avant l'installation j'ai même enlevé la pile RTC avant l'installation  @yak-54

**Comment by yak-54** [comment]
does it say REV 1.1.0 or 2.0 ?

**Comment by yak-54** [comment]
and have you checked to see if the ISRM Module pins line up with the adaptor board

**Comment by yak-54** [comment]
i have seen people to this by mistake
![PXL_20210223_163617337](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/74474d83-d6e0-43a1-9829-c6cbd3bb1d8f)

**Comment by yak-54** [comment]
In ethos can you tell me how are trying to up the module ?

**Comment by hamelsveld** [comment]
sure,

I've put the file on the SD card and go to "system" -> file explorer -> select the file and select "update internal module"

then is does a module reset and then I get the msg module not responding.

**Comment by yak-54** [comment]
I just did a test and put wrong firmware on my Isrm module I put isrm x10 express  and after it Finnish i try to bind not working then I put [FW-X10S-ISRM-S-X10S_v2.1.6.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11611819/FW-X10S-ISRM-S-X10S_v2.1.6.zip) and it started to work

**Comment by har1fr** [comment]
J'ai renvoyé le module aujourd'hui à HorusRC-eu en France, je dois recevoir un nouveau la semaine prochaine
