### ISSUE TITLE
Quadroflaps

### ISSUE THREAD

**Issue by danydu62** [FrSkyRC/ETHOS-Feedback-Community#2666]
Bonjour . Depuis la dernière mise à jour de ma x20, je n'ai plus le mixage ailerons->volets pour coupler les volets avec les ailerons(fullspan). 
J'ai vu un nouveau mixage Quadroflaps. Est celui que je dois utiliser ? Si oui j'ai essayé mais j'ai un message d'erreur : " mixage de base absent ".
Pouvez vous m'aider svp?
Merci à vous tous .

**Comment by bsongis-frsky** [comment]
Oui c'est le même mixage, juste renommé

**Comment by bsongis-frsky** [comment]
Voila les conditions pour qu'il soit utilisable :
- avion ou planeur
- au moins 2 sorties flaps
- un mixage de type flaps
