### ISSUE TITLE
X18 top status bar icons too small or too close together 

### ISSUE THREAD

**Issue by FireflyJar** [FrSkyRC/ETHOS-Feedback-Community#2667]
few things could be done to improve this,  add space between the icons?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17463234/61ead086-06b4-4696-9480-c6626bfae477)
 
probably can't make icons bigger height-wise but what about wider?   so we can see a space between the bars.

**Comment by Szonu** [comment]
I find every thing to small 
Even full screen telemetry  and other parts only use a small part of the screen 
Sure it all can be done but needs redoing instead of just using fonts of another radio. 
Looks like font size is being increased in next update but don’t know when as complete percent has gone down

**Comment by bsongis-frsky** [comment]
The room for the top bar icons is not that large!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/14a676f6-2c64-4dd9-ac49-905a0b5dba99)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/02e0c515-278e-44c6-96de-e6774e9d8983)

**Comment by Wolepo** [comment]
Why does "ETHOS" always have to be displayed? This wastes important space. We know that Ethos is good.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/f142eaa3-67a3-498a-8009-1ab0acc188a7)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ebb3d160-84aa-4279-acf4-b9c44cdd12fa)

**Comment by Wolepo** [comment]
> 
Yes, you could, but the space that is freed up will still not be used.

**Comment by FireflyJar** [comment]
> 

exactly!

**Comment by bsongis-frsky** [comment]
The bitmap will be hidden if no more room left, like it is the case in this screen:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/3c7d413c-f7ee-4ef4-b73c-526100ef5f1d)

**Comment by FireflyJar** [comment]
nice!
