### ISSUE TITLE
Self-test in the SxR

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2668]
Hello, 
If you want to do a self-test with a gyro receiver, observing the blue LED in the Rx is not a problem if you can see it. However, it becomes problematic if the receiver is installed under the wings and cannot be seen.
After about 5 seconds the blue LED starts flashing and you have to move the control sticks to the end position. but you can't see the flashing in this installation position. 
Therefore my question: Is it possible to set in SxR that the OFF/ON switch returns to the home position when the flashing starts? That would make it easier to handle when performing the self-test.
Personally, I count every second from 21 to 26 and then move the sticks, but I still have a bad feeling about it.

![Selbsttest](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/7f074d70-b73f-4f60-b26b-ae8c15bee3ec)
Translated with www.DeepL.com/Translator (free version)

**Comment by bsongis-frsky** [comment]
I will check if I can do that within Ethos, it depends if some feedback is provided by the receiver when it's started / finished

**Comment by bsongis-frsky** [comment]
Today there is no feedback. Waiting for the RF team to provide one.

**Comment by SmartTommy** [comment]
thank you for your suggestion and it will be added next firmware version.

**Comment by Wolepo** [comment]
Great, that would make it much easier to handle.

**Comment by strgaltdel** [comment]
signalling status based on rx feedback data would be the "gold standard" but implies imho new rx firmwares.

maybe a simple, pragmatic "adhoc" solution would be time based "screening"
my experience is, that at least my sxr's show similar timing behavior.
lets say 4.x seconds for flight attitude learning and 5.x seconds for learning max rudder positions.

so, even without "rf feedback",
the user could get the info "dont touch this"
(m.c. hammer retro)
for 5 seconds

and "now move rudders to Xtreme posi and wait for finish signal" for 4 seconds

i guess this would fulfill user expectation in more then 95% of all cases

... just a suggestion to get a simple solution
