### ISSUE TITLE
RB25s 

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#2669]
why isn't the rb25s built into ethos like the old rb why do you need an extra lua....i use the rb25s and two tdrx...then i lost sensor and can't use the lua of the rb25s anymore

**Comment by bsongis-frsky** [comment]
This Lua has been written to avoid release Ethos just for one sensor. It will be integrated into the firmware soon.
I am not sure it will solve your issue of lost sensor etc. as it is something different (if the communication between the radio and the device is broken, it won't work better inside Ethos)

**Comment by mawzthefinn** [comment]
Gyro functionality is not dependent on the sensors, all control is via the channels. It's only programming of the gyro that depends on sensors.
