### ISSUE TITLE
Expo values not showing in outputs

### ISSUE THREAD

**Issue by Dads-RC-Hangar** [FrSkyRC/ETHOS-Feedback-Community#267]
X20s Ver1.06

I am not sure if it's me but when I add expo activated by flight modes in say Ailerons Mix, you will see it working in the graph. But when you goto outputs, you do not see. I am sure in Ver1.05 you could. 
![image](https://user-images.githubusercontent.com/80551405/118552988-9bde3180-b757-11eb-8a05-cd28c73a0ee2.jpeg)

![image](https://user-images.githubusercontent.com/80551405/118552777-4d309780-b757-11eb-979d-a80e821ca266.jpeg)

**Comment by WismyYao** [comment]
Can you provide us with more information? Like video?

**Comment by bsongis-frsky** [comment]
No, expo is not visible in outputs, we have no such curve graphs in the outputs screen!

**Comment by Dads-RC-Hangar** [comment]
I thought the Orange bar resembled Expo. 

Chris
