### ISSUE TITLE
Change the name of the images folder

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2670]
Isn't it better to rename the images folder "models" to "images" It's annoying to have two folders with the same name. (bitmaps/images)
It doesn't always have to be just a model.
.
![Screenshot_399](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/fb2e458d-60eb-42bf-822d-1ce1f50bf587)

**Comment by mawzthefinn** [comment]
That folder is specific to the model images function in Edit model. So it is correctly named.

**Comment by jurajjurej** [comment]
It's OK
I mean, but the folder name.

![Screenshot_405](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/64e6d426-8527-44f3-8003-9b2608f60866)
Rename here:
![Screenshot_404](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/8324c29a-3c4c-4404-8e43-d6978cbf6bdf)
![Screenshot_404](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/69300a3a-8a20-43df-8d47-1336e9f5b169)

**Comment by jurajjurej** [comment]
> Tento priečinok je špecifický pre funkciu obrázkov modelu v Edit model. Takže je to správne pomenované.
