### ISSUE TITLE
Center signaling

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#2671]
Center signaling analogues. (lever, potentiometers, sliders)
In the middle position of the potentiometer, the slider beeps Tx.
.
![Screenshot_400](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/c562b716-b014-4d4a-9e0c-b0b75116a306)
.
Excellent for sliders.

The screen is an illustration only.

**Comment by jurajjurej** [comment]
Excellent for sledders

**Comment by Wolepo** [comment]
What does this have to do with signalling the centre position?
What do you want to tell us with that?

**Comment by Tonio62** [comment]
Hi,
How did you do that ? I can't find the way ;)
Thanks

**Comment by jurajjurej** [comment]
> Ahoj, ako si to urobil? Neviem nájsť cestu ;) Ďakujem
This is just a suggestion (picture)
It doesn't exist in reality.

**Comment by Wolepo** [comment]
Then you have to write that down. Then there would have been no confusion.

**Comment by Tonio62** [comment]
https://youtu.be/7KYpVo0u6Po

**Comment by jurajjurej** [comment]
> Potom si to musíte zapísať. Potom by nenastal zmätok.

I'm sorry, but worse communication for a Slovak.

**Comment by jurajjurej** [comment]
> https://youtu.be/7KYpVo0u6Po

LSW is OK for one controller.
A feature for all pot/sliders would be nice. That's on X20 5x LSW.

**Comment by LeoCheung123** [comment]
Would love that feature - was in opentx too.  Now we have to do a convoluted logic switch and live with a >100ms lag.

**Comment by jurajjurej** [comment]
We want that creep "Beep Centers"
