### ISSUE TITLE
T5 for nose wheel

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#2672]
Hi
Just wondering how I setup my model with a steerable nose wheel as t5 for the trim on my x18.
The rudder is on ch 4 and
The nose wheel is on ch 7
But the rudder trim works both, I can't see an option to change it
Thanks
Scott

**Comment by mawzthefinn** [comment]
Remove your current mixing for Ch7

Add a free mix, input is analogs->Rudder, output is Ch7 (this is your new Nose wheel mix, without rudder trim)
Add a second free mix, input is Trims->T5, weight is 25% Up, 25% down, output is ch7 - This is your trim (25% weight to match the default trim configuration)

**Comment by Liverboy77** [comment]
Thanks
