### ISSUE TITLE
Wireless trainer no reconnect

### ISSUE THREAD

**Issue by riga23** [FrSkyRC/ETHOS-Feedback-Community#2674]
No automatic reconnect trainer after turn off and turn on the radio (X20S Master & X18S Slave) 1.4.8 togheter. After a restart, always click "reconnect" to restart the connection. After thisoperation the function return to operate like programmed.

**Comment by mawzthefinn** [comment]
This is a duplicate of #1583 

Please continue the discussion under that issue
