### ISSUE TITLE
End point adjustment

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2675]
Hi,

Is it possible to add a highlighter of text when setting Min and Max endpoint adjustment?

For example, if I want to set endpoint to left rudder, when I slightly move rudder to left I will know by highlighting of text, (or a change in colour), if it's Min or Max the value I should tamper.

**Comment by salibaj2** [comment]
Thank you, understood.

**Comment by bsongis-frsky** [comment]
Another user has asked for this change during the week-end. I have seen some places where this should be nice / useful. I will show some screenshots later today

**Comment by salibaj2** [comment]
That is great news bsonigs. Although mawzthefinn suggestion is good, I still feel there is room for improvement here to be more user friendly.

Joe

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/27a62dea-6e69-4ae6-ad61-8213dce3a401)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2ffa4c12-2649-435b-ab0e-eaf4615b2fca)

Plus the same behaviour in Free Mixes ...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/475a508d-6529-4e7c-bca8-9dd5350640c1)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/09ab6b89-1f75-4ad7-9bd8-7e48855eaeea)

**Comment by salibaj2** [comment]
That is super. Thank you.
