### ISSUE TITLE
RF FIRMWARE - TD Module

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#2677]
questions. is the firmware from 2022-11-30 TD 2.2.4 Added the support for Tandem XE. also valid for the X20? is it available for download? on the frsky site.
![Frsky](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84266308/fd568b01-2c4c-4137-b01f-f60033f7fcd9)

**Comment by mawzthefinn** [comment]
No changes for the older radios, it's just adding XE support. 

That does bring up a good point, the listed Firmware updates are out of date in Suite, as the TWIN modules 1.0.4 is missing and needs to be added as that does have necessary updates (TW R8/GR8 support
