### ISSUE TITLE
Teaching the position in the room during the self-test (SR8Pro, V2.1.12)

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2679]
Hello,
The acceleration sensors were calibrated on a flat surface according to the instructions.
 Then the receiver was installed in the model and the self-test was carried out. However, the receiver is never 100% horizontal in its installation position or in the normal flight position.
 I know it so that after the self-test and subsequent switching to automatic mode, the control surfaces remain in its aligned position. But this is no longer the case. If I switch to automatic mode, there is a deflection on aileron and elevator. If I place the receiver on the table where it is exactly horizontal, there is no deflection in automatic mode after the self-test.
Has the teaching of the position in the room been removed?

**Comment by pstasek** [comment]
During the gyro calibration, you teach the receiver level position of the receiver, so it doesn't drift. During the self-check, you teach the receiver level flight attitude which takes into account the mounting position of the receiver in the model.

**Comment by Wolepo** [comment]
I made a comparison with an S8R. Beforehand, I deliberately placed the RX at a slight angle on the sofa plane. After the self-test, the rudders remained in neutral position in automatic mode. Here the teaching of the installation position works.
With an SR8Pro, however, I have to set an offset of -3 for the elevator in order to achieve no reaction when switching. 
Setting an offset works. The error was due to my operation.

**Comment by Kreisflieger** [comment]
Hello all,

I confirm the above described behaviour by Wolepo,  that after selftest, the elevator and aileron servo deflect a few degrees, when switching in automatic mode.

Transmitter: X18SE, Ethos 1.4.9
Receiver: SR10Pro v2.1.12

As this is for the Ethos Feedback I worry if this will be adressed to the FrSky-Receiver development team from here.
Or is there a better way to contact the FrSky-receiver developers directly ? Any recommendations ?

Kind regards   Stephan

**Comment by SmartTommy** [comment]
thank you for your feedback, we fixed this and will release when finish internal testing.
[Archer-X_2.1.15_TEST.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12326945/Archer-X_2.1.15_TEST.zip)

**Comment by Wolepo** [comment]
Tested, the rudders now remain in their taught position in automatic mode after the self-test. The position in space is now also taught. In this respect, the update is a complete success, thank you.
Now in Ethos only the switch in the LUA, which triggers the self-test, must go back to its home position after the self-test.
