### ISSUE TITLE
Redundancy R9MX Receiver not working at 25mw

### ISSUE THREAD

**Issue by Toolroom1** [FrSkyRC/ETHOS-Feedback-Community#268]
I have an SR6 and an R9MX for redundancy in my aircraft, if I set the POWER setting of the R9MX to 25mw as it should be in my region and then switch the 2.4 transmitter off, the model surfaces will move to my custom HOLD settings giving me no redundancy. If I now repeat this with the R9MX set at a POWER setting of 200mw when I switch off the 2.4 transmitter I do not loose control, I only loose telemetry which is fine. Also the Icon for the R9MX does not light up.
X20s-Firmware 1.0.6 EU-SR6-R9MX
Internal Module TD-ISRM
HW:1.4.0 FW:2.1.6 (EU)
Receiver 1 Archer X 
HW: 1.2.0 FW: 2.1.7
Receiver 2 R9MX
HW: 1.1.1 FW: 1.3.1

Keep up your good work

**Comment by WismyYao** [comment]
Did you re-bind the R9MX when you switched the power ?

**Comment by WismyYao** [comment]
How about TD-ISRM firmware 2.1.7 ?

**Comment by Toolroom1** [comment]
Here is what happens.
1. X20S and aircraft switched on and set to 200mw SR6 LED GREEN R9 GREEN
2. Click on the 25mw setting for R9 and the R9 LED glows RED
3. Switch off Aircraft and X20S
4. Switch on X20S and aircraft, SR6 LED glows GREEN R9 LED glows RED
5. Click on R9 BIND, result, SR6 LED glows RED, R9 glows RED, the X20S
screen shows the BIND banner "waiting for receiver" but it never gets a
signal
the only way out is for me to switch both X20S and aircraft off and go back
to 200mw.

NOTE: I also tried binding R9 with 2.4 switched off but still got the same
result.

**Comment by WismyYao** [comment]
When you change the power from 200mw to 25mw, you should re-bind the R9MX.

**Comment by Toolroom1** [comment]
Please show a link pointing to download.
TD-ISRM firmware 2.1.7

**Comment by WismyYao** [comment]
https://www.frsky-rc.com/wp-content/uploads/Downloads/Firmware/X20X20S/FW-X20X20S-TD_v2.1.7.zip

**Comment by Toolroom1** [comment]
Thank you, I had managed to find it before your post. I have updated it but the problem is still the same sadly.

**Comment by WismyYao** [comment]
> Thank you, I had managed to find it before your post. I have updated it but the problem is still the same sadly.

You should rebind the R9MX when you change the power from 200mw to 25mw, did you do it ?

**Comment by WismyYao** [comment]
We tried many times and haven't reproduced it. Can you share a video about it  ?

**Comment by Toolroom1** [comment]
This video shows the system working at 200mw I then change to 25mw then switch off 2.4 and try to Rebind to R9, the X20S never gets the signal. Video to large for your server please see link below.
https://youtu.be/9ozoZl2Suuk

**Comment by Toolroom1** [comment]
I have Just manager to get in to work at 25mw, I think what I did was with every thing running and the RM at 200mw I then switched off 2.4 then change RM to 25mw, then powered down the aircraft, then powered up again and selected RM bind which then offered me to bind SR or RM I chose RM then switched off 2.4 and found RM was still in control. I must apologize for wasting your valuable time, I must have been trying in the wrong sequence, I did post a video earlier but deleted it as I now have it working. Thanks for all your help.

**Comment by Toolroom1** [comment]
Please read my last comment first.
Something that is bothering me is when I power the system up all the servos move hard over for a second or so, I only ask as I have just had an aileron servo stop working, I'm wondering if this is due to being strained on each powerup. Should I start another thread for this?

**Comment by FrSky-GX** [comment]
Would you record a video of servo hard moving？

**Comment by Toolroom1** [comment]
The side with no wing is where the servo has stopped working.

https://user-images.githubusercontent.com/28987442/119220149-f9200d00-bae0-11eb-9fab-9ef80775632a.mov

**Comment by Toolroom1** [comment]
Video uploaded to GitHub page.

**Comment by Toolroom1** [comment]
Please can you fix this problem, I'm worried about damaging another servo.

**Comment by Toolroom1** [comment]
I took the servo apart and it smelt of burning inside.

**Comment by FrSky-GX** [comment]
When the receiver is powered on, we don't find any abnormal waveform on the oscilloscope. You can remove the signal wire of the servo from the plug and only connect the power supply and ground to see if this phenomenon still exists. Or do you use other types of receivers without such phenomenon？

**Comment by Toolroom1** [comment]
This problem surely must be the X20S and SR6 as all I have done is replace my Powerbox receiver with the SR6 receiver, I'm leaving Powerbox as I think ETHOS is a better programming system, BUT this unwanted servo movement never once happened with the Powerbox receiver. 
![My Powerbox Receiver](https://user-images.githubusercontent.com/28987442/119629305-cd18ca80-be05-11eb-89ef-18bebd3722eb.jpg)

**Comment by Toolroom1** [comment]
I have replaced the servo that had burnt out, and noticed that the other three servos lock over but the new one does not, this leads me to believe it is more a problem with the three, NEW POWER XL-17HMB servos. This does not answer why they did not ever lock over with the Powerbox system.
