### ISSUE TITLE
How long can a timer be?

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2682]
Apologies, I've not been able to test this myself, but please can you ensure that timers can be really long? I use a persistent timer to see how much use my models get used, this number can therefore be very large. One of the problems with opentx is that large timers start to produce garbage (e.g. 40H23). 
Thanks

**Comment by bsongis-frsky** [comment]
You should open the issue to opentx repo then. Here is Ethos and timers are very different.
