### ISSUE TITLE
Emergency mode

### ISSUE THREAD

**Issue by Morizioo** [FrSkyRC/ETHOS-Feedback-Community#2683]
Hello, my X20 (EU, all updated) entered emergency mode just after pressing the button to turn it on, and I could not turn it off, I was forced to remove the battery. Knowing that the last model used was in D8 on an XJT Lite module, with a D4R II receiver. The receiver was powered before the radio. I didn't have control over the receiver. I tried to reproduce the exact same situation but it didn't happen again. Any idea to find out why?

**Comment by Morizioo** [comment]
Hope this can not happen in flight any more, like the guy with the Yak 55 who crashed !

**Comment by bsongis-frsky** [comment]
It would be interesting to reproduce this problem. Perhaps some telemetry which is not correctly protected, especially on radio startup?

**Comment by Morizioo** [comment]
no telemetry on this rx, and "découverte des capteurs" was OFF, no mix except snapflap, I don't know !

**Comment by NMO81** [comment]
I have bought 2 weeks back a TRangeX iRX4 lite module and during one of my initial tests with a new blank model and just linked to an old ACCST V1, I also got this emergency mode just after powering on the transmitter. I also needed to remove the battery. Unfortunately I could not reproduce it.

**Comment by Richrfl** [comment]
> I have bought 2 weeks back a IRangeX iRX4 lite module for my X20 EU V1.4.8 and during one of my initial tests with a new blank model and just linked to an old ACCST V1 (D8), I also got this emergency mode just after powering on the transmitter. I also needed to remove the battery. Unfortunately I could not reproduce it.

I am not the wisest but as far as I know Ethos requires ACCST V2. I had to update all my RXs.

**Comment by Morizioo** [comment]
Yes but the modules xjt lite or irx4 are compatible with d8 or accst v1. I have flown with d8 and access since, and no problem at all. No problem in flight for the moment, only this bug one time while powering on the radio.

**Comment by Richrfl** [comment]
> Yes but the modules xjt lite or irx4 are compatible with D8 or accst v1. I have flown with D8, LR12 and access since, and no problem at all. No problem in flight for the moment, only this bug one time while powering on the radio.

Thank you for the info.
