### ISSUE TITLE
Updating to latest nightly breaks timer and custom sound

### ISSUE THREAD

**Issue by yufasa** [FrSkyRC/ETHOS-Feedback-Community#2685]
Updating from a previous nightly ~ 2 weeks old to Jun 11 breaks timer and sound.
The timer is most likely due to the change in time countdown but the default values inserted to existing models are way off and have to be manually changed - I would suggest a default of 1 minute and step of 10 seconds but others may have input here.

I use custom voices and after the update the selected voice for models reset to the first voice (English) and I had to update all my models to use my custom created voice. Not a big deal...

**Comment by bsongis-frsky** [comment]
I have changed my mind many times and the conversions between the nightlies may have been broken one day
If you reuse a model created from 1.4.8 is it correctly converted?
