### ISSUE TITLE
missing lua script for digital switches

### ISSUE THREAD

**Issue by Peterbilt84** [FrSkyRC/ETHOS-Feedback-Community#2686]
the addition of digital switches in version 1.5.0 is very good, but unusable at the moment.
If the whole thing has to be done via a Lua script, then this script should also be installed automatically with the firmware update.

**Comment by bsongis-frsky** [comment]
I will add a Lua script in this repository so that you have an example

**Comment by Peterbilt84** [comment]
thank you.

Desire for the range of functions
-Naming
-Color of the background
-Memory on/off
-Possibility to add an image of a symbol

Sript to be used as source / activated for mixer

**Comment by bsongis-frsky** [comment]
Script added to this repo.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/28ee2920-ee25-4a88-9574-a04f41b7318a)

**Comment by bsongis-frsky** [comment]
> Unfortunately, the lua solution has one major drawback. You can't use the switches as a source for the mixers?

Ah?

> and if these switches are needed for multiple mixers, then the memory will reach its limits. 18 digital switches and more would be needed in the end

Have you tried to create 18 switches?

> Would it not be better to solve the whole thing via widget? Then no one needs to install an extra lua script.

The widget will fit to nobody as everyone will need something different

**Comment by Peterbilt84** [comment]
I have only created one switch. I could not set anything on this one.
At config widget was only the name of the script (lua Script Form)

**Comment by uj-berlin** [comment]
Hello,
a lua based solution is not very useful. For each virtual switch you have to define a separate lua source. A better solution would be a widget based solution similar to the channel monitor widget. It should be possible to set the following:
number of switches
type of switch (push button, latching switch)
colour of the switch 
name of the switch 
and which virtual switch serves as output (VS1 - VS24)

In addition, you need an additional class VS (Virtual Switch) like LS or Switches as a source for the mixers.

Then everybody could use it. Not all modellers are programmers :-)

**Comment by Peterbilt84** [comment]
I have installed the Lua script. Unfortunately, you can not set anything on the transmitter. Neither the color nor the text. Also, you can not assign an output to the switch,
The uj-berlin solution is much simpler. Very few can rewrite Lua scripts.
![Screenshot 2023-06-13 231407](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/86299248/8d3ad800-9c51-4d8e-899a-98b868e1b6c0)
![Screenshot 2023-06-13 231510](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/86299248/fb2e2438-fd98-4b95-99e1-9e2842076a3a)
