### ISSUE TITLE
Global Logic Switches

### ISSUE THREAD

**Issue by s-corlett** [FrSkyRC/ETHOS-Feedback-Community#2687]
Using Ethos 1.4.8, tandem x18/x20 
When I set up training for a master, I create 5 logic switches to control it (3 for stick movement, 1 "OR" to combine them, then one sticky to turn on with a toggle switch and then off with the "OR'd" stick movement).  Works super, except I have to do it over again every time I add training to a model.  It would be great to be able to make a set of global logical switches or a way to copy parts (logic's or even mixes) from one model to another.

**Comment by Wolepo** [comment]
Logical switches can be copied into one model and pasted into another model, but you can only transfer one at a time. It is not possible to transfer several logical switches at once.
