### ISSUE TITLE
1.5.0 Vars

### ISSUE THREAD

**Issue by JimB40** [FrSkyRC/ETHOS-Feedback-Community#2690]
Had a little time to sneak peek nightly.
I like Vars concept as they can serve for various tasks like calculating values based on sensor values.
Got questions then.
1. Wil range be limited to -100,100
2. Will operands be integer only.
3. Did little test to transpose Throttle stick position into 0-100 range, but var still gets -100,100 values (work in progress?)
 
![IMG_0338](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/f06a202c-261f-43b9-b4a1-2394fe5ae119)
![IMG_0339](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/b5e0dd5b-c613-4e28-8c8f-ef72bcd811a3)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a778621b-1890-4634-a052-463f19af52b3)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2ca641bd-e662-49b2-af67-64f158e22699)

**Comment by bsongis-frsky** [comment]
Tomorrow nighlies:
1) Range increased to +/-500%
2) Actions will allow one decimal

**Comment by bsongis-frsky** [comment]
Throttle at Max => +100%
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/3ef5c923-ef1d-4104-a061-3764bfee3c61)

Throttle at Min => 0%
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/538a0edb-c7b3-410a-81e2-127b97233952)

**Comment by bsongis-frsky** [comment]
Plus one example of use in a Custom Curve

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b997b212-a691-473c-9666-228b0acc0626)

**Comment by BladeScraper-Designs** [comment]
Would it be possible to increase the range of the Var when using a range of 0% to x?  For example, it's -500% to 500%, but if 0% is used as the lower limit, then the upper range can be allowed up to 1000%?
