### ISSUE TITLE
Bluetooth device name can't be changed from 'hello'

### ISSUE THREAD

**Issue by PatrykSokol** [FrSkyRC/ETHOS-Feedback-Community#2698]
Changing name of BT device in radio options, when using it for telemetry, doesn't change device name seen in my BT receiver (Android phone). BT device name stays at 'Hello' regardles of name chosen in 'Local name' field in wireless menu

Radio: Tandem X20s
Firmware 1.4.8 FLEX

**Comment by bsongis-frsky** [comment]
Yes, reproduced here

**Comment by bsongis-frsky** [comment]
It seems a problem in the BT firmware, not Ethos
