### ISSUE TITLE
Predefined mixes - cannot change source

### ISSUE THREAD

**Issue by alesstimec** [FrSkyRC/ETHOS-Feedback-Community#27]
Hi,

Today i tried out the 0.17 build of ETHOS, created a glider model from template. All went well, but am a bit frustrated by the fact, that i cannot change the source for the predefined mixes. 

E.g. 
 - on i'd like to use the throttle stick to control air brakes
 - i'd like the throttle source to be one of the pots.

I do know that i could use a "free mix", but it's such a small change that would make predefined mixes a lot more usable.

Thanks,
   Ales

**Comment by Hartinger** [comment]
I have another example where this would be very useful.
I normally fly Mode 1 (ailerons on right stick).
However, for models with no ailerons I have the rudder on the right stick.
The easiest way to achieve this would be to change the source of the rudder mixer.
With the current implementation I have to use the Combimix or a free mixer.
Neither of the includes the trim, so I have to add a further free mixer to just add the trim for the rudder.

Regards
Reinhardt

**Comment by bsongis-frsky** [comment]
Throttle will have a configurable input in 0.0.18

**Comment by alesstimec** [comment]
It's not just about the throttle.. What about having the rudder take input from the aileron stick (e.g. when flying a RES glider). I think this is a general issue that needs to be addressed.
