### ISSUE TITLE
Click at end of sound playback

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#270]
I am getting a strange click sound at the end of any user track. The clicks are not there if I listen to the sound on my PC, nor were they there on OpenTX (where I originally used these sounds). The are all 32KHz 16bit wav files. ETHOS 1.0.6 X20S

https://youtu.be/JumlWqP2SOs

**Comment by Nicholas-Luoyi** [comment]
Please post your wav file here and we will take a look into it.

**Comment by bsongis-frsky** [comment]
I am pretty sure there is a DATA (TEXT) section at the end of your wav file. It would be played just as if it was AUDIO data.
Please share here one of those files, we will check if we can handle this section properly, thanks!

**Comment by MrD-RC** [comment]
There is data on the audio file with the artist (sound pack name) and title (description of the sound). These were added due to the Crappy 6 character limit in OpenTX. 

It would be great if ETHOS could use the title in the audio file, if present. It would make selecting sound files much easier. 

They can be downloaded here https://inavfixedwinggroup.com/guides/opentx-model/opentx-sound-pack/

**Comment by bsongis-frsky** [comment]
OpenTX has to work with an EEPROM, which is very short in size compared to the SDCard
Opening all files to retrieve the DATA information is not costless!

**Comment by bsongis-frsky** [comment]
The issue with the end of file is fixed in 1.0.7

**Comment by MrD-RC** [comment]
Apologies for the crappy comment. What I really should have said is that 6 characters aren’t really user friendly for picking sound files. 

Yes I can understand that opening all the files could have a pretty big overhead, especially with the size of packs like Amber. It’s a shame as it could make sound selection much more friendly.
