### ISSUE TITLE
X18 Text Clipping in 1.4.9

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2700]
A few places where I've noticed text clipping since the font size was bumped:

<img width="484" alt="Screenshot 2023-06-22 at 16 56 34" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4312404/bcff77bc-2b4a-4325-b5ab-32c1f540bc5b">

<img width="482" alt="Screenshot 2023-06-22 at 16 56 44" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4312404/af60f8f0-b697-4f71-91ca-c1630a9d98a7">

<img width="484" alt="Screenshot 2023-06-22 at 16 57 16" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4312404/f16072d0-44ca-4ee1-a69f-c98719271622">

<img width="485" alt="Screenshot 2023-06-22 at 16 58 38" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4312404/4307c280-ed41-45fb-a01a-e07b544efc5a">

<img width="483" alt="Screenshot 2023-06-22 at 17 01 22" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4312404/704672e9-e1fb-4aa1-b49a-7ba170d4ec8c">

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/3f980730-1406-4b7d-807e-f74c8ec0b952)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8124a6ff-b01a-40c7-a1f0-d3544c7911ae)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b1e6d68c-3b2e-46ab-97cf-1ce7a0c31316)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d64e41b5-4bc1-4489-afea-53aae6c5cfa3)
