### ISSUE TITLE
automatic Refreshing radio information after update is done doesn't work anymore r1.4.9

### ISSUE THREAD

**Issue by 3D-Cat** [FrSkyRC/ETHOS-Feedback-Community#2702]
X20S Bootloader Mode ethos suite
TD Module v2.2.2
Firmware Version: 1.4.8 EU
Bootloader Version: 1.4.3
SD Card: (29.8GB): Audio English 1.4.5
Flash: (8.0MB): System Bitmaps 1.4.8

after update, the popup window "Refreshing radio information ..." keep running > 5 min. and does not end
closing Ethos Suite and disconnecting the USB Cable TX display shows the firmware update progress and the update is done properly 

reconnect in bootloader mode shows in ethos suite:
Firmware Version: 1.4.9 EU Up to date
Bootloader Version: 1.4.3 Up to date
SD Card: (29.8GB): Audio English 1.4.5 Up to date
Flash: (8.0MB): System Bitmaps 1.4.8 Up to date

did not have the problem with 1.4.8

**Comment by mawzthefinn** [comment]
Worked correctly for me, X18 FCC on WIn11

**Comment by 3D-Cat** [comment]
there was recently an update "2023-06 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5027231)" 
could be the reason

**Comment by Nicholas-Luoyi** [comment]
If you don't press the "WRITE OUTDATED COMPONENTS". Just press the "Refresh radio info.". Will you wait endlessly?

**Comment by 3D-Cat** [comment]
push button reacts just less then a second, no pop up window (I guess as designed) appears.

I don't know if this is related to my described problem but I recognized that 
- After pushing Eject Drives the drives remain visible in File Explorer but not accessible (usb cable still connected)  
- in task manager you'll find multiple Ethos Background processes even though Ethos App is closed
