### ISSUE TITLE
Ghost RC receiver telemetry not working on Ethos

### ISSUE THREAD

**Issue by dk7xe** [FrSkyRC/ETHOS-Feedback-Community#2703]
HW: Tandem X20S with IRC Ghost 
Ethos OS version: X20S 1.4.8, EU #23c0d292
Ghost FW version: 1.0.8.0

When using IRC Ghost external modul telemetry is available from the TX module only.
No RX telemetry is showing up.
Just the telemetry data from the TX module is shown
![20230619_052233.jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/f0cbbb1d-f208-4c98-bafa-9e64e990005e)

The same receiver connected to a Ghost / Taranis / EdgeTX setup is showing full RX telemetry data.
![20230619_052529.jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/af7d4994-06e8-42e8-862c-edddae581252)

**Comment by J-charles-C** [comment]
I,

Telemetry for external module come with 1.5.0 firmware.

Best

**Comment by mawzthefinn** [comment]
> I,
> 
> Telemetry for external module come with 1.5.0 firmware.
> 
> Best

Telemetry support is present for IRC Ghost, TBS Crossfire/Tracer and ELRS modules in 1.4 and earlier. 1.5 will bring MPM module telemetry support.

The OP is getting telemetry from the module, but only the module’s own telemetry, not the receiver telemetry relayed by the module.

**Comment by bsongis-frsky** [comment]
I wonder what are those 2 sensors in your screenshot?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/37d853f4-c8f8-439e-96f2-eaeea18488c9)

Would you give me their ID (you have to enter the page). Also would you raise the limits allowed for the --- one, perhaps the limits I have setup are not enough.

**Comment by bsongis-frsky** [comment]
Once that's said, I have implemented only 7 sensors for Ghost RC. And you show 7 in your screenshots. I will add more sensors in 1.4.10. Would you please send me an email to get a test firmware, unless you check the nightlies? I don't have the sensors to test myself.

**Comment by bsongis-frsky** [comment]
The 2 first sensors will be added to 1.4.10
The "Pack" sensors will be added to 1.4.10
The "VTX" sensors will be added to 1.5.0 (we miss the MHz unit in 1.4.X)
The "GPS" sensors .... I will see tomorrow what I can do
As said above I don't have the hardware to test all those sensors.

**Comment by dk7xe** [comment]
Hi Bertrand, 
strange thing is that both sensor lines with no lable have the same ID
![screenshot-2023-06-27-81528](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/7aa09efa-fc8b-4815-99d2-330f538bd738)
![screenshot-2023-06-27-81544](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/7d3d374a-802f-4336-a9f4-916fdbfcab4c)
![screenshot-2023-06-27-81584](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/63702a79-b4c3-4aa8-b9e4-b0808b7e588d)

As a reference for the GHOST sensor ID's with label the YAML file of the same model from the Taranis running EdgeTX
[model00.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11887290/model00.zip)
That's all the sensors a Ghost system sends by default.

**Comment by dk7xe** [comment]
@bsongis-frsky i'm willing to test nightlies whenever required. Please let me know.

**Comment by bsongis-frsky** [comment]
The 2 first sensors will be added to 1.4.10
The "Pack" sensors will be added to 1.4.10
The "VTX" sensors will be added to 1.5.0 (we miss the MHz unit in 1.4.X)
The "GPS" sensors will be added to 1.4.10
Tests needed, it will be in the next nightlies, thanks a lot!

**Comment by dk7xe** [comment]
Moved to nightly now and will update every day if needed

**Comment by dk7xe** [comment]
Thank you @bsongis !
Looks good with nightly of this afternoon.

![screenshot-2023-06-29-77492](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/395c761d-57e7-4008-8f25-15d5f5ed657d)
![screenshot-2023-06-29-77504](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/34e49e6b-3d11-4211-b877-409f0a94187b)
![screenshot-2023-06-29-77521](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3907200/8ff638e3-dc89-4ce9-bb0e-cf7be14a4a30)
