### ISSUE TITLE
radio wont bind when I switch from a 900MHZ model to a 2.4GHZ moddle

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2704]
when I have a 900MHZ model running then I switch to a 2.4GHZ model, it won't bind until I turn the radio off.  2.4 to 2.4 model is no problem.  haven't tried td mode to or from anything else. as I recal l2.4 to 900 works.

1.4.8 frsky 20S

**Comment by williajgr** [comment]
anyone going to comment on this issue?

**Comment by bsongis-frsky** [comment]
It has been pushed yesterday to the RF Team. Checks are needed, you will get an answer when available

**Comment by williajgr** [comment]
seems like this is a dead issue??  seams like it could still be an ethos issue to me.

**Comment by williajgr** [comment]
I still think this is an Ethos issue. it is not getting looked at.  anyone going to fix it????

**Comment by williajgr** [comment]
Do i have to open a new issue to get someone to look at this?

**Comment by mawzthefinn** [comment]
@bsongis-frsky confirmed the issue is on the RF side, not ETHOS. It's pending an update from the RF team.

**Comment by williajgr** [comment]
Thanks, this will just be a firmware update to the isrm module correct?Sent from my iPhoneOn Jul 27, 2023, at 5:00 AM, LiNan ***@***.***> wrote:﻿
Hi, thank you for your feedback. we have fixed this, and will post the release version after internal testing. There is a test version for you:
TD-ISRM_2.2.5_TEST_20230727.zip

**Comment by williajgr** [comment]
that did the trick, thanks

**Comment by kaiqueqds** [comment]
On the FrSky site the last version still the 2.2.4, the testing of the firmware is done?

**Comment by mawzthefinn** [comment]
TD ISRM V2.2.6 and TD ISRM PRO v1.1.12 have been released witha  fix for this issue
