### ISSUE TITLE
Problem with TD receiver

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#2705]
Strange problem with TD receiver (maybe no problem with Ethos)
I unpacked and registered my new(!) TD R6, R10, R18 receiver and bound it to an existing model. It worked, BUT no action on any servochannel. 
No change after trying for a long time. (Receiver full reset, registation again, binding again)
Then deleted ALL mixers from the model, re-registered and bound receivers. Created a new mixer and lo and behold, the servo works.
After that, re-registered and bound the receiver to another existing model and everything works.
This has happened to the TD R6, TD R10 and TD R18 so far.
ALL receivers have been flashed with the latest firmware.
This problem only occurs with TD receivers, other receivers work perfectly.

Transmitter Tandem X20s and Tandem XE
Firmware Ethos 1.4.8 EU and 1.4.9 EU

**Comment by bsongis-frsky** [comment]
Very strange issue indeed! Does it occur just when they are new?

**Comment by SmartTommy** [comment]
Can you repeat this fault phenomenon？please tell us if you can.

**Comment by SmartTommy** [comment]
> I can only find the problem on new TD receivers. Once they are registered and bound, and then work, the error no longer occurs. Even if you completely reset the receiver in the transmitter. However, we have found that if the receiver is set to 7us when binding, the problem does not occur.

what is mean"the receiver is set to **7us** when binding, the problem does not occur"?

**Comment by Skippydi** [comment]
I mean the HS-PWM rate. (Option)
When set to 7ms all channels work, at 21ms they don't.

**Comment by Skippydi** [comment]
Someone just posted on Facebook that the error also occurred on an Archer SR6.
He fixed it by removing all mixers and then re-registering and binding.

**Comment by bsongis-frsky** [comment]
The problem is fixed?
