### ISSUE TITLE
ETHOS Suite drive EJect

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2706]
just up dated 3 of my X12S to ethos 1.4.9 with ethos suite 1.4.8
when Finnish i Ejected the drive  removed usb cable and it just froze on the usb screen pic 1
bugger no buttons or the power switch worked.
so went out side to get an screw driver to remove the battery when i came back 3 min later  it had this pic up pic 2 
and buttons and power button worked so i power it off and back on and its seams ok

so went on to number 2 so i used my laptop just in case its driver issues 
same thing it froze after 3 min i was able to power it off and on it was ok.

so number 3 radio i did it manually did not use ethos suite all good no issues
 
![20230626_101154](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/1b750f13-cb70-4713-a241-441fc44b8107)
![20230626_092137](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/33cba3d5-f2aa-4c22-b0af-27f253d4f8f5)
![20230626_092218](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/8481ed6d-a228-4b18-8607-a3ed29b69f58)

**Comment by strgaltdel** [comment]
maybe it would be an important info for the devs to know which OS / release / update version you're using.

for example: win10 / update 1903 changed "internal" USB settings, so no cache is used.
(less transfer performance but more stable  disconnect)

regards

**Comment by Nicholas-Luoyi** [comment]
Does this happen after you click the "Eject Drives" or unplug the USB directly?

**Comment by yak-54** [comment]
on one of the X12s i just used windows to Eject drive window said safe to remove hardware still froze

**Comment by Nicholas-Luoyi** [comment]
Is there any crash logs that you can share? In Suite-Setting-Open crash log

**Comment by yak-54** [comment]
> Is there any crash logs that you can share? In Suite-Setting-Open crash log

nop just looked no logs

**Comment by yak-54** [comment]
Ethos suite is not freezing its the radio  if i use ethos suite to eject the drives

**Comment by yak-54** [comment]
i did one of my x12s manually did not used ethos suite and worked fine

**Comment by Nicholas-Luoyi** [comment]
Would you please help to check that if you flash the X12S back to 1.4.8. Does the freeze is still there?

**Comment by yak-54** [comment]
ok did as you asked 

not all the time 2 out 4
 i flashed it 4 times 1.4.8 to 1.4.9 back to 1.4.8 on the 2 times  after the drives where ejected in ethos suite it froze on unplugging  cable 

i did it 4 times manually  not using ethos suit worked  fine

**Comment by Nicholas-Luoyi** [comment]
So it happens no matter it's a upgrade or a downgrade, right?

**Comment by yak-54** [comment]
yes

**Comment by yak-54** [comment]
i dont think its an firmware issue i think its the ethos suite talks to windows issue

**Comment by yak-54** [comment]
its like the radio is waiting for an reboot / reload firmware

**Comment by yak-54** [comment]
if remember  right it did do on ethos suite 1.4.5 and not on 1.4.6 or 1.4.7 from memory

**Comment by yak-54** [comment]
or fixed

**Comment by bsongis-frsky** [comment]
Duplicate of #3346

**Comment by yak-54** [comment]
will give it a go fingers crossed

**Comment by yak-54** [comment]
update ethos suite to from 1.5.0 nightlies it crashed 
log file 
[crash-20240130.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14094932/crash-20240130.txt)

**Comment by yak-54** [comment]
so i restarted an next time  clicked on  update firmware to 1.5.0 rc1 went ok it updated eject drive then the radio went into black screen of death so as always had to pull the back off
![20240130_202314](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/6eff26a3-991b-4c0e-a38c-9c1abc8474ed)
