### ISSUE TITLE
Trim problem on Tandem EX

### ISSUE THREAD

**Issue by BoSoendergaard** [FrSkyRC/ETHOS-Feedback-Community#2708]
Hello

3 weeks ago I got a Tandem XE
I have a problem, the Trim function does not work
When I adjust the trim, the trim changes well enough in the display, but the signal does not come out to the servo

The Firmware is 1.4.8 EU #23c0d292

All my mixes are Free Mix as I use it for boats

Option in trim menu
Range - 25%
Step – Fine
Independet ... - OFF

What am I doing wrong

Best Regards
Bo

**Comment by mawzthefinn** [comment]
Free mixes do not have trim applied unless you create a second free mix with the trimmer as a source, with the same output.

Trims are only automatically applied to surface/throttle mixes.

**Comment by Skippydi** [comment]
But that is very unusual. If I use a free mixer for a channel, the trimming function should also take effect without having to create a second free mixer for trimming.

**Comment by mawzthefinn** [comment]
No, it's not unusual. A trim mixer is just that, free. You do not get any functionality in a Free mixer that you do not explicitly assign. 

The trim functions need a way of associating with a specific function. That association is tied to the specific functions (NOT the analog inputs). 

If you want trim assigned by default, you must use a function mix with a trim function associated.

**Comment by mawzthefinn** [comment]
Closing as answer provided
