### ISSUE TITLE
Switch SB Glitchy. Hardware or Software?

### ISSUE THREAD

**Issue by Dads-RC-Hangar** [FrSkyRC/ETHOS-Feedback-Community#271]
I have attached a video, As you can see from SB low to SB mid the graph glitches, I switch to SA switch and it works fine. It seems only this switch. 

https://youtu.be/n5gvwMiRBeY

**Comment by bsongis-frsky** [comment]
You are right, I noticed it the other day and I completely forgot to spend some time on it!
I will take it

**Comment by bsongis-frsky** [comment]
I cannot reproduce it anymore!

**Comment by bsongis-frsky** [comment]
May I ask you to send me an email? I will answer with the current firmware we are working on. I want to be sure it's a firmware issue (which would have been fixed since then)

**Comment by loetefix** [comment]
I tested with 1.0.6 and there is no problem on my x20.

**Comment by Dads-RC-Hangar** [comment]
> May I ask you to send me an email? I will answer with the current firmware we are working on. I want to be sure it's a firmware issue (which would have been fixed since then)

What email should i contact you, you can send me an email chris@dadsrchangar.co.uk

**Comment by bsongis-frsky** [comment]
I sent you a firmware (1.0.7 preview)
If the problem is still there, please attach your model file and radio.bin file
Thanks

**Comment by Dads-RC-Hangar** [comment]
> I sent you a firmware (1.0.7 preview)
> 
> If the problem is still there, please attach your model file and radio.bin file
> 
> Thanks

I am on the train home, will test some more, incase it's something I have done. 👍🏻

**Comment by bsongis-frsky** [comment]
Yes, I need your radio.bin and your model file (from the models directory)

**Comment by bsongis-frsky** [comment]
Reproduced with your model file, thanks!

**Comment by Dads-RC-Hangar** [comment]
> Reproduced with your model file, thanks!

That's good in a way 🤓

**Comment by bsongis-frsky** [comment]
Problem found, testing... a new firmware is coming in a few minutes

**Comment by Dads-RC-Hangar** [comment]
> Hey,
> 
> 
> 
> Just to let know I've also detected a glitch using SB switch to swap between rates (weights). 
> 
> Not sure if is the same issue reported here since the YT video is not online anymore. 
> 
> 
> 
> I've done some debugging, and the issue is only visible when using "SB". 
> 
> Version: Ethos 1.0.6, platform: X20
> 
> 
> 
> Please let me know if any extra help/ info is needed. 

Yup I deleted the video, no need to have that hanging around in the web. This has been fixed in the next update 👍🏻
