### ISSUE TITLE
Trim beep is delayed when audio system goes to sleep

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2710]
On my X18SE with Ethos 1.4.9, the first press of a trim results in a delay before the beep sounds. Subsequent beeps have no delay, until there are no sounds played for a few seconds. Then, the next press has a delayed beep again.

I'm guessing the audio system is going to sleep to save power. Is there some way to disable this? The delay is very annoying and makes the radio feel unresponsive. My old X7 running OpenTX has no such delay, and trims are much more pleasant to use as a result.

Technically this applies to more than just the trims (eg if you configure a special function to play a sound when a switch is flipped), but the trims are where it's really irritating.

**Comment by bsongis-frsky** [comment]
This delay is only needed on very early X20(S). But not on other boards. I will get rid of it in 1.4.10

**Comment by lightbulbjim** [comment]
Fantastic, thanks!
