### ISSUE TITLE
Logical switches

### ISSUE THREAD

**Issue by spvwrx** [FrSkyRC/ETHOS-Feedback-Community#2711]
When I create a Logical switch using "A<X" or "A>X", the"Min Duration" function does not disable the LS after set time. at the moment it functions the same as "Delay before inactive"
Thanks

**Comment by bsongis-frsky** [comment]
What is your Active condition. If you just care the start of the condition and you need a duration, then you should perhaps use the Edge option on your Active condition?

**Comment by spvwrx** [comment]
Hi,My previous experience with OpenTx I use another Ls to make condition active, then it stays active for eg: 0.4sec. So far I have not figured out how to do this with Ethos.Best Regards SimonOn 28 Jun 2023, at 22:08, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
What is your Active condition. If you just care the start of the condition and you need a duration, then you should perhaps use the Edge option on your Active condition?

**Comment by spvwrx** [comment]
I will try Egde the Edge trigger.Best Regards SimonOn 28 Jun 2023, at 22:08, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
What is your Active condition. If you just care the start of the condition and you need a duration, then you should perhaps use the Edge option on your Active condition?

**Comment by spvwrx** [comment]
I tried Edge but it triggers when I release the stick. I need the mix to bump the throttle for about .04 of a sec on a down line snap only when the throttle is all the way back. I trigger this a preset snap condition.Best regards,Simon VentevogelOn 28 Jun 2023, at 11:09 pm, Simon Ventevogel ***@***.***> wrote:﻿I will try Egde the Edge trigger.Best Regards SimonOn 28 Jun 2023, at 22:08, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
What is your Active condition. If you just care the start of the condition and you need a duration, then you should perhaps use the Edge option on your Active condition?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/60131f52-8650-497f-a4c4-c28f53561347)

**Comment by bsongis-frsky** [comment]
In 1.5.0 you will get a new attribute "Max duration" in logic switches, you will save one Logic switch. Screenshot:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c23d2bc4-ad78-46f0-ad07-d0bdd2874603)

**Comment by spvwrx** [comment]
Thank you, awesome..Best Regards SimonOn 29 Jun 2023, at 20:21, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Closed #2711 as completed.
