### ISSUE TITLE
Failsafe with TWIN Lite Pro module and TW GR6 receiver does not work in Custom mode.

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#2712]
Failsafe will not turn on in Custom mode even if I turn the radio off.
I have not tested the Hold and No pulses and Receiver modes.

Configuration: X20S
Firmware: 1.4.9, EU
Module: Twin Lite Pro (v1.0.4 firmware)
Receiver: TW GR6 (v1.0.4 firmware)

Servos are connected via D5701 and F-Bus.

The failsafe is turned on (Custom) and the channel excursions are set, but nothing happens when I turn the radio off to test. The steering wheels stay in the given position. As if "Hold" is on.

My other plane is fitted with an ARCHER GR6 receiver and in the same way F-BUS connected to the D5701 servos, everything works fine!

**Comment by bsongis-frsky** [comment]
Failsafe settings are sent every 10 seconds to the receiver. Are you sure you have waited for 10 seconds in your tests?

**Comment by jufelap** [comment]
yes

**Comment by SmartTommy** [comment]
> Failsafe will not turn on in Custom mode even if I turn the radio off. I have not tested the Hold and No pulses and Receiver modes.
> 
> Configuration: X20S Firmware: 1.4.9, EU Module: Twin Lite Pro (v1.0.4 firmware) Receiver: TW GR6 (v1.0.4 firmware)
> 
> Servos are connected via D5701 and F-Bus.
> 
> The failsafe is turned on (Custom) and the channel excursions are set, but nothing happens when I turn the radio off to test. The steering wheels stay in the given position. As if "Hold" is on.
> 
> My other plane is fitted with an ARCHER GR6 receiver and in the same way F-BUS connected to the D5701 servos, everything works fine!

TEST: X20 Firmware: 1.4.9, EU Module: Twin Lite Pro (v1.0.4 firmware) Receiver: TW GR6 (v1.0.4 firmware)  Servo:HV5701

it works fine here. could you show us a video?

**Comment by jufelap** [comment]
The problem has been solved. I updated everything again and re-registered the receiver unit and everything works fine.
I must have done something wrong before, I apologize.
