### ISSUE TITLE
RF FIRMWARE - TD Module (X20S) update over home page and Ethos Suite FRSK Flasher has version differences

### ISSUE THREAD

**Issue by 3D-Cat** [FrSkyRC/ETHOS-Feedback-Community#2713]
- FrSky Home Page -> Download RF FIRMWARE - TD Module (X20S) newest version is TD 2.2.4
- Ethos Suite FRSK Flasher (TD Module (X20/ X20S/ X20HD/ X20HD Upkit)) the latest version is v2.2.2

**Comment by Nicholas-Luoyi** [comment]
It has been updated now.
