### ISSUE TITLE
More timer conditions

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2714]
Can we get more options for timer active conditions? Flight modes especially would be handy in the 1.4.9 list of active conditions.

The nightlies currently only allow always on, switch positions and system events as start/stop conditions, but I assume timers are still a work in progress there.

Thanks!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/7524140f-2ab2-4b3e-ba5c-661fd91d77f5)

**Comment by bsongis-frsky** [comment]
Timers are considered as ready in 1.5.0, if anything else is needed please ask!

**Comment by lightbulbjim** [comment]
I think logic switches would be good to have as well.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d4a979f8-e583-4604-8d6a-671e7cbbe955)

**Comment by lightbulbjim** [comment]
Thanks!
