### ISSUE TITLE
Options Switch selection incomplete / wrong

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2715]
Options Switch selection incomplete
Conversion: wrong

Edge selection missing
Icon: correct
Edge selection: missing

![Bild 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/9e226940-ab2c-446b-ad96-8b69fd42b762)
![Bild2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/510339cb-27fe-4190-b857-91aca847a3e0)
![Bild 3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/ed64efd7-5bfb-49fe-961e-9557c3439bbe)

Gruß Eugen

**Comment by bsongis-frsky** [comment]
You are right, there is a regression in this area :(

**Comment by yak55** [comment]
Hello Problem currently fixed only in the special functions.

Tested logical switches and mixers - still wrong.

I have not tested other menus.

Photo of the example logical switches I have attached.

Greetings Eugen
![Bild 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/af7e0428-f87a-48f2-8af0-1995df8f2efb)
![Bild2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/1335d0ac-e94c-4027-b9b4-9f60986f27c2)
