### ISSUE TITLE
Czech translation of Gear Mode in RPM sensor

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#2716]
Hi, there's a wrong Czech translation of the Mode: Gear when setting the RPM telemetry sensor.

There's "Podvozek" which actually means "Landing Gear" and I'd suggest it to be "Převodový poměr" to make sense.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/b24b09f1-60cf-42e7-8cce-4aa6f8cfd844)

**Comment by janekx** [comment]
I will look on it and make corrections incl rest of the translations. This sugestion is right if mode is like the rate between two wheel teeth

**Comment by bsongis-frsky** [comment]
Is it good now?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4fa40447-14be-476a-aa27-322269c5e8af)
