### ISSUE TITLE
Kya script pass through telemetry -ardupilot

### ISSUE THREAD

**Issue by nightfury24** [FrSkyRC/ETHOS-Feedback-Community#2717]
Hello,

Thought let you know guys.
Seems Ardupilot yappu lua script does not work with external RM9 module if using Ethos.
Even if use on x20. As per ardupilot community it only works with inbuilt module only.
I am using Horus x10s express with ethos.(recently moved from openTX)

**Comment by mawzthefinn** [comment]
This should be reported as a bug to Yaapu

**Comment by nightfury24** [comment]
Ohh. I thought it’s a ethos bug. You can remove or closed this issue.
________________________________
