### ISSUE TITLE
Cannot Register Receivers

### ISSUE THREAD

**Issue by Panot-Triroj** [FrSkyRC/ETHOS-Feedback-Community#2719]
Need help with my new X18 with already Fireware 1.4.9 cannot preceed to register receiver (tried with R9 STAB and TD R6). After pressing Register, the screen continues showing "waiting for receiver ..." and keeps saying "register ... register ... register ..."

Just wonder if it is because I replaced the pop-up Owner Registration ID (when first got after pressing RF System) with another name?

Thanks.

**Comment by strgaltdel** [comment]
please describe how did you put the receivers into register mode

do the receivers indicate that they're in regMode?

**Comment by Panot-Triroj** [comment]
For 9R STAB, I first pressed RF System, then type Owner Registration ID with 8 characters, selected Internal Mode, turned Stage ON, Type ACCESS, 900M ON, Antenna Internal, Power 200mW, then press Register +++ put power to the receiver, press the button on the receiver.

**Comment by Panot-Triroj** [comment]
When put power into the receiver, there is Red LED on.

**Comment by Panot-Triroj** [comment]
For 9R STAB, I first pressed RF System, then type Owner Registration ID with 8 characters, selected Internal Mode, turned Stage ON, Type ACCESS, 900M ON, Antenna Internal, Power 200mW, then press Register +++ supplied power to the receiver, there is RED LED on, then press the button on the receiver, but the registration could not be completed.

**Comment by Panot-Triroj** [comment]
For TD R6, did the same as I did with R9, the only difference is Type TD Model, did not work as well. the RED LED keeps blinking slowly (slower than the R9).

**Comment by Panot-Triroj** [comment]
For Owner Registration ID, I can type any 8 characters in, right?

**Comment by strgaltdel** [comment]
your receivers didn't enter regMode

please press button on receiver(and hold) before apply power, then power on
release after tx shows rx identification 

as described in manual
2. Connect the battery to the receiver while holding the button on the receiver.

**Comment by Panot-Triroj** [comment]
Wow you are great, can register and bind now. Many many thanks.
