### ISSUE TITLE
Displaying telemetry maximum and minimum value in the widget

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#272]
I didn't find a possibility to display a maximum or minimum value in the widget (useful for review after a flight). Only the actual value is available.

I'd suggest long-press on a value widget would allow selecting a current, maximum and minimum value for a session along with the possibility to reset. 

Or possibly selecting <value>+/- from the list, like in OpenTX, whatever is more convenient.

**Comment by Liverboy77** [comment]
This is already available when you select the widget long press and it will give you the option of min an max

**Comment by pstasek** [comment]
> This is already available when you select the widget long press and it will give you the option of min an max

Awesome, it works, only on a different screen.

**Comment by Hobby4life** [comment]
I like te request to reopen this issue.

Just creating 2 widgets, both GPS ALT, only 1 widget has to show max values. ok this works.
But both widgets show GPS ALT, I like to change the text to GPS ALT MAX for the one that is checked with max option.
There is no way to change the display widget text.
