### ISSUE TITLE
Ethos Suite Backup Fails with OSX Ventura 13.4.1

### ISSUE THREAD

**Issue by LeoCheung123** [FrSkyRC/ETHOS-Feedback-Community#2720]
Repeatable Problem:
In Ethose Suite, Backup initiates but does not complete after clicking backup.  App hangs and nothing is saved in the backup folder.  Screenshots attached.
<img width="1728" alt="Screenshot 2023-07-02 at 4 55 03 PM" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15016301/c90dddae-f240-4be6-a9cf-475acfa78101">
<img width="1728" alt="Screenshot 2023-07-02 at 5 02 56 PM" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15016301/ed59ebef-69a1-488b-8f2c-473d50978152">

Ethos Suite version 1.4.9
Versions: Ethos Suite  by Ventura 13.4.1

**Comment by lightbulbjim** [comment]
Hmm, mine is working fine on 13.4.1.

**Comment by Nicholas-Luoyi** [comment]
Does your X20S flash firmware correctly? If so would you please check if there are any crash logs (In setting - open crash log)

**Comment by LeoCheung123** [comment]
No crash log detected on any of the SD cards or Frisky flash directories.  The X20S firmware (1.4.9flex) seems to be working just fine as per screenshot in my first post here.

**Comment by LeoCheung123** [comment]
New finding, the problem goes away if I limit the items to be backed up to just "Models" and "logs".  Even if "scripts" are included, the backup does not finish.

**Comment by Nicholas-Luoyi** [comment]
Would you please try to only back up scripts. And post your scrips folder zip here? It seems to be something wrong with sub directories.
