### ISSUE TITLE
Characters not displayed properly

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2721]
X18SE,
Running latest update 1.4.9.

In telemetry, RPM, range is listed between 0r/m to 250000r/m.

250000r/m does not fit in text box.

Joe

**Comment by bsongis-frsky** [comment]
So the font is too big?
#2718

**Comment by bsongis-frsky** [comment]
Perhaps you use a too small text box? I wonder in which screen you are, you haven't pasted a screenshot

**Comment by salibaj2** [comment]
Text box is in telemetry page, under RPM telemetry.

Telemetry range fir rpm, on one box is 0 r/m, which is fine, in the other text box 250000r/m.

The 2 is half visible. 

Replying from mobile. Will take a photo and send it once at my pc.

**Comment by salibaj2** [comment]
The issue is in the telemetry sensor, RPM.

Thank You

![Telemetry RPM Sensor](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68815554/89add8a1-4853-47e8-834d-29e3ba43d82f)

**Comment by salibaj2** [comment]
One more question please, delete if not in the correct place. I am displaying RPM in a widget box and I would like to rename this box: - RPM *100. 

But the character * or / is missing from the keyboard. Is there is any chance that characters are included for widget box names?

Thank you

Joseph

**Comment by salibaj2** [comment]
Hi Bertrand,

 

Just posted in Github with picture of issue.

 

Thank you

 

Joseph

**Comment by bsongis-frsky** [comment]
Ethos 1.4.10

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b4cb7b24-39ba-4a4a-89d1-3f9b2e3216ab)

**Comment by i3dm** [comment]
tbh, no need to display the units in the range max field, as the unit is listed right above in Unit field.

**Comment by bsongis-frsky** [comment]
good idea, I willl change again if needed
