### ISSUE TITLE
[Question]How to use lua reset all telemetry?

### ISSUE THREAD

**Issue by koakumaping** [FrSkyRC/ETHOS-Feedback-Community#2722]
As I konw. Special Funtion can do this ation. But how lua ?
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4099388/9ee11839-2e4d-4360-8b59-9bd2109fdaaa)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c38a93de-044d-4ff3-be94-627d3b3263b0)

**Comment by bsongis-frsky** [comment]
It will be available in next nightlies
