### ISSUE TITLE
[CRSF] What are the default threshold values

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#2723]
Questions for Crossfire users...
1) which is the sensor  which is like the FrSky RSSI sensor on a CRSF setup, is it "Rx Quality" like on Ghost setups?
2) what are the values for Critical / Warning alerts

**Comment by Target0815** [comment]
Rx RSSI = RSSI
RX Quality = LQ

Warnings see page 62: https://www.team-blacksheep.com/media/files/tbs-crossfire-manual.pdf

**Comment by bsongis-frsky** [comment]
Thanks for this information. It is also similar to Ghost. RSSI in the top bar will be shown by using the LQ (and if displayed as digital value the unit will be %)

**Comment by lightbulbjim** [comment]
RQly is the VFR/LQ field for ExpressLRS and should be used as the primary metric (EdgeTX does this now). See https://www.expresslrs.org/info/signal-health/

**Comment by bsongis** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5603504/a617997b-78b5-4f6b-be58-e5cfc4b70135)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/464e359e-29be-4e27-ba20-48928e69925f)

**Comment by JimB40** [comment]
@Target0815 almost right :)
As you can see there is no RSSI sensor. 

![Screenshot 2023-09-15 at 10 25 23](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/0d94a59b-6fea-4fe4-a444-a2309f37215c)

Just tested 1.4.11 and it tries to use non existing RSSI sensor.

@bsongis-frsky here is how it works both on Crossfire and ELRS (that uses CRSF protocol):
- There are two RSSI sensors called 1RSS & 2RSS
- if reciever is NOT diversity both sensors gets same value -> RSSI = 1RSS = 2RSS
- if rereciever is diversity each sensor gets it's own value -> RSSI = max(1RSS, 2RSS)

So if you want to keep in system RSSI sensor for CRSF it should be calcuolated.

I confirm also "RQly" sensor is more important as it gets percentage of recieved packets so you can check well if RC Link (telemetry steam) is still valid.

I don't know what you use to check RC Link telemetry stream validation (CRSF) but in 1.4.11 when telemetry stream is gone all RX sensors still shows as active (blinking dot)

**Comment by JimB40** [comment]
Here are defaults for Crit/Warn  I use in my app:
Crossfire:
![screenshot_tx16s_23-09-15_10-45-53](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/7accab2a-f679-4a4e-948f-e84b0a6d64ec)

ELRS:
![screenshot_tx16s_23-09-15_10-46-36](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/bff7f41f-caf7-43fa-b27a-3a371a1ed991)

**Comment by JimB40** [comment]
If you need further testing just ping me. :)
![IMG_0687](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/b3c6cea3-f214-43ef-a050-12e9740b9005)
