### ISSUE TITLE
Sim X10 Express status bar

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2724]
Hello, in the sim for the X10Express the status bar is either not high enough or the font is too big.
See picture.
![Statusleiste X10Express](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/17cacfdf-8065-408a-9abb-665c4f7c188d)

**Comment by bsongis-frsky** [comment]
You miss some fonts. Even the font used on trim bars is not right

**Comment by Wolepo** [comment]
Does the sim not bring the fonts?

**Comment by bsongis-frsky** [comment]
Which version?

**Comment by Wolepo** [comment]
ETHOS 1.3.9 X10 Express

**Comment by bsongis-frsky** [comment]
I have forgotten to include the fonts directory in the installer. If you create the directory manually and add all the fonts, it will work again.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/59cd2ddb-0ea5-478b-bec4-e20a5ecb2262)

Fixing the simulator installer now...

**Comment by Wolepo** [comment]
The funds seem to be missing from all simulators.

**Comment by bsongis-frsky** [comment]
Exact, but they are only really needed on Horus radios, because they are not embedded inside the firmware (not enough space on flash).

**Comment by Wolepo** [comment]
Thank you for the quick repair.  I have reloaded and installed the sim. Now it fits.
