### ISSUE TITLE
Ethos Suite Automatic update

### ISSUE THREAD

**Issue by LeoCheung123** [FrSkyRC/ETHOS-Feedback-Community#2727]
When Ethos Suite detects an available update, it tries to download a zip file, even when we are running OSX.

OS: Ventura 13.4.1

**Comment by mawzthefinn** [comment]
And here.

I believe the latest-mac.yml file needs an update to correctly point at the DMG

**Comment by Nicholas-Luoyi** [comment]
Yes. It does download the zip. If you are running installation manually, you should download the DMG. If the Suite helps to auto update, it will download the zip. It's correct.

**Comment by mawzthefinn** [comment]
Suite doesn’T appear to be doing the auto-update on Mac though. It downloads the zip but does not copy the app to teh Applications folder

**Comment by ZeekWorld** [comment]
Same issue on Mac OS Sonoma 14.0

**Comment by LeoCheung123** [comment]
Same issue on Mac OS Sonoma 14.0.

If you have a Mac OSX version - it makes no sense for ethos to download zip automatically.  C'mon guys.

**Comment by mawzthefinn** [comment]
Suite update works cleanly now, form 1.4.13 to 1.4.14 on Sonoma.

**Comment by miggy1952** [comment]
But not on Big Sur

**Comment by mawzthefinn** [comment]
Big Sur is not a current OS and is out of support from Apple. Support ended on September 26, 2023
