### ISSUE TITLE
x18 tandem

### ISSUE THREAD

**Issue by Angelo1945** [FrSkyRC/ETHOS-Feedback-Community#2728]
Non si vede l'uscita radiofrequenza a 2.4 e 900 in alto sullo schermo come mai?

**Comment by mawzthefinn** [comment]
Note also you don’t get any telemetry if 900M power is set over 25mW with EU compliant firmware.

**Comment by Angelo1945** [comment]
Quindi il segnale in alto dello schermo è solo il ritorno dalla ricevente telemetrica e non la potenza di uscita del trasmettitore ....io avrei preferito poter vedere se il tx trasmette e con che potenza anche se la medesima si puo regolare dalle impostazioni....grazie delle info Angelo.

**Comment by Angelo1945** [comment]
Ti ringrazio adesso è tutto chiaro solo una domanda tutti i ricevitori TD mandano l'informazione attivando la telemetria? non vorrei tediarti con altre domande questa è l'ultima rinnovo i ringraziamenti.....Angelo.

**Comment by mawzthefinn** [comment]
Yes, Telemetry is the path for all information coming from the receiver.
