### ISSUE TITLE
Helicopter Swash Types Menu for flybar helicopter

### ISSUE THREAD

**Issue by rtsx1cr** [FrSkyRC/ETHOS-Feedback-Community#2729]
what the difference  in H-3 120 and HR-3 120. i got a old flybar helicopter i want to set up on my x20s running ETHOS  just a little unsure which one to pick. i know it is a 120 degree helicopter.  again this is a FLYBARED helicopter thanks for any help you can offer me.

**Comment by pld74** [comment]
Have a look here, it explains them and gives you a visual for reference. 

https://ardupilot.org/copter/docs/traditional-helicopter-swashplate-setup.html

**Comment by mawzthefinn** [comment]
Closing off as answer provided
