### ISSUE TITLE
sound making FR documentation needed

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#273]
I am french, i like the sounds you make for FR langage, the voice sound great and fluid. I would like to harmonize my personnal sounds to have the same result. Please could you share in documentation the way you make the soudtrack in order to allow users to use the same if it in open source... Which caracteristics and wich vocal narrator.

Ps: i discover my new X20 and ethos now. I would like to THANKS for your job and the way you follow ethos. It is really great to see there somebody to support it. Carry on and i am sure it will become a fantastic operating system either for "geek" users coming from OTX or usual plug and play...

**Comment by bsongis-frsky** [comment]
Thanks for your feedback!
We use Google Text-to-Speech:
https://cloud.google.com/text-to-speech?hl=fr
