### ISSUE TITLE
Info about ticket #2715 incomplete switch selection options (ticket was closed)

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2730]
ticket was closed
Info as of 07.07.2023

Edges are only available for special functions and stopwatches.

Logical switches, telemetry and mixers currently still incomplete.

Gruß Eugen

![Version](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/29e6c10a-854d-4b3d-bb79-ec581e8fce73)
![Flugphasen](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/2d70f3d2-febf-4a00-b429-c4ccb8544d58)
![Vario](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/3fa19089-f970-4391-9165-a856e81cebd5)
![Mischer](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/afb0c1d1-0aac-4c54-a93e-2c00c7bc64bd)
![logische Schalter](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/1f7445a1-6f1e-4c21-9bc7-c2860475dcda)

**Comment by bsongis-frsky** [comment]
Flight modes =>I don't see any use case where a Edge is needed there!

**Comment by yak55** [comment]
Hello Bertrand,I only looked, what was possible in 1.49 and  doesn’t work now.I am programmer  and think update’s shouldn’t stop working things.Same is vario.Don’t use Edge in both, but could do so in 1.49Best regards EugenDiese Nachricht einschließlich aller Anhänge kann vertrauliche und/oder rechtlich geschützte oder sonst relevante Informationen enthalten. Wenn Sie nicht der beabsichtigte Empfänger sind, sind Sie nicht zur Verwendung oder Weitergabe der Informationen befugt. Bitte benachrichtigen Sie uns sofort über den irrtümlichen Empfang und löschen Sie dann die Nachricht.Am 10.07.2023 um 08:28 schrieb Bertrand Songis @ FrSky ***@***.***>:﻿
Flight modes =>I don't see any use case where a Edge is needed there!

**Comment by yak55** [comment]
Hello,I absolutely need it for logical switches and special functions.Rest not necessary.EugenE. BleuelDiese Nachricht einschließlich aller Anhänge kann vertrauliche und/oder rechtlich geschützte oder sonst relevante Informationen enthalten. Wenn Sie nicht der beabsichtigte Empfänger sind, sind Sie nicht zur Verwendung oder Weitergabe der Informationen befugt. Bitte benachrichtigen Sie uns sofort über den irrtümlichen Empfang und löschen Sie dann die Nachricht.Am 10.07.2023 um 08:33 schrieb Eugen Bleuel ***@***.***>:﻿Hello Bertrand,I only looked, what was possible in 1.49 and  doesn’t work now.I am programmer  and think update’s shouldn’t stop working things.Same is vario.Don’t use Edge in both, but could do so in 1.49Best regards EugenDiese Nachricht einschließlich aller Anhänge kann vertrauliche und/oder rechtlich geschützte oder sonst relevante Informationen enthalten. Wenn Sie nicht der beabsichtigte Empfänger sind, sind Sie nicht zur Verwendung oder Weitergabe der Informationen befugt. Bitte benachrichtigen Sie uns sofort über den irrtümlichen Empfang und löschen Sie dann die Nachricht.Am 10.07.2023 um 08:28 schrieb Bertrand Songis @ FrSky ***@***.***>:﻿
Flight modes =>I don't see any use case where a Edge is needed there!

**Comment by bsongis-frsky** [comment]
I wonder if it really works in 1.4.9!

1.5.0 introduces the concept of 2 different sort of switched:
1) SwitchChoice
     - when it is true, it is solid true
     - it has no trigger option as it means nothing
2) TriggerChoice
     - when it is true, it works like a trim which is pushed, slow at the beginning, quicker then
     - it has a trigger option

**Comment by bsongis-frsky** [comment]
Where do you need TriggerChoice (in addition to current state) ?

**Comment by yak55** [comment]
Yes, it works in 1.4.9 on the X20.

 

What do I use the logical switch for?

 

3 steps switch

 

bottom: all off

 

from bottom to middle: edge query drive battery voltage 

 

from middle to top: Edge resets telemetry to zero also the vario!

motor is activated

 

 

When switching back from top to center, or to bottom

Motor is deactivated

Telemetry is not reset

Drive battery is no longer polled

 

For this I use the edges

 

Greetings Eugen

 

Diese Nachricht einschließlich aller Anhänge kann vertrauliche und/oder rechtlich geschützte oder sonst relevante Informationen enthalten. Wenn Sie nicht der beabsichtigte Empfänger sind, sind Sie nicht zur Verwendung oder Weitergabe der Informationen befugt. Bitte benachrichtigen Sie uns sofort über den irrtümlichen Empfang und löschen Sie dann die Nachricht.

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Montag, 10. Juli 2023 10:03
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: yak55 ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Info about ticket #2715 incomplete switch selection options (ticket was closed) (Issue #2730)

 

Where do you need TriggerChoice (in addition to current state) ?

**Comment by bsongis-frsky** [comment]
Would you paste a screenshot of your logic switches / special functions from 1.4.9?
Or your model binary file?

**Comment by yak55** [comment]
Hello Bertrand, with pleasure, here from an electric glider Temporal and an electric aerobatic model Yak 55.

 

Both version: 1.4.9

 

Thanks for the effort and good work.

 

Greetings Eugen

 

 

 

Gruß Eugen

 

 

Greetings Eugen

 

Diese Nachricht einschließlich aller Anhänge kann vertrauliche und/oder rechtlich geschützte oder sonst relevante Informationen enthalten. Wenn Sie nicht der beabsichtigte Empfänger sind, sind Sie nicht zur Verwendung oder Weitergabe der Informationen befugt. Bitte benachrichtigen Sie uns sofort über den irrtümlichen Empfang und löschen Sie dann die Nachricht.

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Montag, 10. Juli 2023 20:08
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: yak55 ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Info about ticket #2715 incomplete switch selection options (ticket was closed) (Issue #2730)

 

Would you paste a screenshot of your logic switches / special functions from 1.4.9?
Or your model binary file?

**Comment by bsongis-frsky** [comment]
Thanks, but you have to use github to attach files, or they won't be included in the issue!

**Comment by yak55** [comment]
Hello Bertrand,
here both files.
.bin is changed to .png

Eugen
![yak 220 gelb](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/eaa3a2f8-fd71-4010-89e8-c896bcf2356a)
![temporal gelb](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/5b250a73-ee90-4f24-ad17-c09b45ebca5f)

**Comment by bsongis-frsky** [comment]
In my opinion your Logic Switch "Akku voll" doesn't need it. It's used in a "Play audio" function which repeats only once.
Where else do you need this Edge option?

**Comment by bsongis-frsky** [comment]
I think we can close this issue, feel free to reopen a new one if you think the Edge option is needed in another place
