### ISSUE TITLE
Joystick mode for Twin X-Lite S... some switches and sliders don't work

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#2731]
When connecting the Twin X-Lite S (TXLS) to Windows (11) the following switches/sliders don't show any movement in the Windows Joystick properties.

SB
SC
L1
L2

I was hoping to use those for Realflight simulator but Windows joystick properties don't show any movement for them.

The buttons work and show up as Sliders in the Windows joystick properties and the other switches work as well as the stick axis.

**Comment by mawzthefinn** [comment]
Do you have mixes for the missing controls? The Joystick driver maps channels to Joystick controls, not the switches/sliders themself.

**Comment by agibson2** [comment]
I was not aware of that.  Thanks.  I assumed the radio somehow mapped them in some static order.  That makes total sense that it would be completely configurable per the mixes.  I checked and the ones that work are controlling channel mixes it seems.  I will close this.

Thanks again!
