### ISSUE TITLE
Cant bind to sr10 pro after failed firmware update

### ISSUE THREAD

**Issue by NLKanoka5566** [FrSkyRC/ETHOS-Feedback-Community#2733]
hello, since today i am the owner of a tandem x18, i upgraded the firmware of the transmitter to the latest using the ethos suite.
after that i downloaded the latest firmware from the frsky website for my sr10 pro.. i tried updating the firmware using the sport but somehow it prompted emergency mode.

now i can only register the receiver but not bind, i also tried updating the firmware using the stk tool. this also did not work as it seems that the reciever isn't able to talk.

and help or guidance would be greatly appreciated

**Comment by mawzthefinn** [comment]
If it won't respond to the STK, there's something wrong with the receiver.

I would contact support directly.

**Comment by mawzthefinn** [comment]
Closing off as this is a receiver issue for FrSky Support to address
