### ISSUE TITLE
Unable to open list of Wav files in special functions

### ISSUE THREAD

**Issue by MPI8808** [FrSkyRC/ETHOS-Feedback-Community#2734]
Evening I'm having issues trying to add wav files in special functions on my x20s i have updated all to the latest firmware but when trying to assign an audio file to a toggle switch i click on the tab for wav files but none are displayed

**Comment by MPI8808** [comment]
![20230708_211150](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/139012222/5c63238b-4eb0-4519-a754-81c9d74ec81e)
![20230708_211109](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/139012222/0be33af4-9899-4038-9fdc-d6844b66c0d5)

**Comment by mawzthefinn** [comment]
Do you have any WAV files loaded in /audio?

You will not get any wav file options for special functions unless you have a sound pack loaded in /audio/

**Comment by strgaltdel** [comment]
mawz, you gave some valuable infos here,
i guess that's all the info someone need

https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-X20-Pro-Tandem-24-Channels-with-ETHOS/page1545#post50681843

**Comment by mawzthefinn** [comment]
Closing off as answer provided
