### ISSUE TITLE
LUA - RB25S Stab, missing channel functions

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#2736]
In the RB25S Stab LUA, the ability to configure channels 7, 8 and 9 between and 'aux' channel or the 'stabilised' channel is missing.
Try to set up a model with dual rudders and RUD2 on ch9 is not working as a stabilised channel, but cannot see the option to change this anywhere

**Comment by mawzthefinn** [comment]
Treat the RB25S as having two sets of Stabilizers, that program essentially the same way.

The first set has CH1,2 & 4 always on When Stabilizer is enabled on Page 1 of the Lua, then Ch 5 & 6 can be set to Aux or AIL2/ELE2

The second set has CH 7,8, & 9 always on when stabilizer is enabled on PAGE 2 of the lua, then Ch 10 & 11 can be set to Aux or AIL4/ELE4

NB - you have to turn the second set of channels on with the Stabilizer setting on Page 2 of the Lua to get Rudder 2 stabilized on Ch9

**Comment by thomaspember1990** [comment]
> Treat the RB25S as having two sets of Stabilizers, that program essentially the same way.
> 
> 
> 
> The first set has CH1,2 & 4 always on When Stabilizer is enabled on Page 1 of the Lua, then Ch 5 & 6 can be set to Aux or AIL2/ELE2
> 
> 
> 
> The second set has CH 7,8, & 9 always on when stabilizer is enabled on PAGE 2 of the lua, then Ch 10 & 11 can be set to Aux or AIL4/ELE4
> 
> 
> 
> NB - you have to turn the second set of channels on with the Stabilizer setting on Page 2 of the Lua to get Rudder 2 stabilized on Ch9

This worked, just note there is 2 self checks one on each page which is what made it look like RUD2 wasn't being picked up on self check when running it in page one

**Comment by mawzthefinn** [comment]
That's a good point, while mode & gain settings from ch 13-16 are common, each stab section has its own self-check

**Comment by thomaspember1990** [comment]
> That's a good point, while mode & gain settings from ch 13-16 are common, each stab section has its own self-check

If I had 2 aileron servos on 1 surface then used a curve to match the movements of both to be perfectly in align with each other would gyro use this curve? I think not which limits the gyro's use in larger models

**Comment by mawzthefinn** [comment]
WHen you do a self-check, the gyro will learn endpoints and midpoint, but not anything else.

The Advanced Stabilization system on the RB25S, RB35S, TD SR18, TD SR12 and TW SR12 will be more configurable when running in Advanced mode. Only Basic mode is currently available on these gyros, the Advanced programming app is under development
