### ISSUE TITLE
[bug] Inconsistent behavior of sticky LS in "Reset Flight" / "Reset Model" / "Power on"

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2742]
Ethos 1.4.9.

I have a sticky defined like this:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/880d7430-2501-4ba6-ad9b-239c9525a8da)

and `SI` is a momentary switch.

This makes "LS" change state when momentary button is pressed and released.

But the initial state is not consistent:
- after power on LS is "on"
- after model switch it is "on"
- after "reset flight" it is "off" (which I think is correct).

Note: I'm not sure if this is the right way of defining such a switch. I tried to avoiding create multiple LSes. But in any case, I think it should be consistent about the state in these 3 situations.

Video (I changed `SI` to be momentary, it seems normally it isn't in XE)

![Recording](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/2b9accad-ca85-48ee-8671-1a1742e752b6)

**Comment by bsongis-frsky** [comment]
I am not sure what should be done. Avoid the Edge on startup. Or Generate an Edge on Model Reset

**Comment by azaz44** [comment]
Thanks for explanation, I at least understand more on how it works now.
I think the right solution would be to not generate edge events at startup. It looks like this is internal way on how Ethos is initializing switches. But from user perspective nothing changed around switches, so the event is unexpected.

**Comment by bsongis-frsky** [comment]
It seems working perfectly in nightlies, am I right?

**Comment by azaz44** [comment]
> It seems working perfectly in nightlies, am I right?

Hm, testing, but I don't get "Edge" option there. Am I missing sth? Testing X18S simulator from nightlies.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/47dba502-536f-4db4-b14f-7270308694ea)

**Comment by bsongis-frsky** [comment]
Test tomorrow :)

**Comment by azaz44** [comment]
I tested today on X18 simulator from the night. Now the LS is on after boot, model change or flight reset.
If this is correct - I don't know. It's a bit of surprise at first for the user, that switch edge is triggered and needs a bit of understanding. But it is consistent.
