### ISSUE TITLE
Programmed Model Profiles Lost After Updating

### ISSUE THREAD

**Issue by 2xWhiskey** [FrSkyRC/ETHOS-Feedback-Community#2747]
I am experiencing lost model profiles when flashing between firmware versions.

Initially I flashed from 1.4.8 stable to the 1.5.0 nightly build and I lost a few profiles.  Flashing from 1.5.0 nightly to 1.4.9 yielded no change, and flashing from 1.4.9 to 1.4.8 resulted in more losses of model profiles.

Some of the profiles can be found in radio's internal memory, but they cannot be restored to functionality within the Ethos OS.

Attached is a sample .bin file of one of the profiles that is no longer being picked up by the OS.  I changed the .bin extension to .txt so that it could be uploaded.
[ec-1500.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12045503/ec-1500.txt)

**Comment by mawzthefinn** [comment]
Models are not backwards compatible (ie a model edited or created in a newer ETHOS version will not work in an older ETHOS version), and nightlies may break models (and other data) at any time.

You cannot use a model edited in 1.4.9 on 1.4.8. 

I recommend updating back to 1.4.9, that should make the models which don't work under 1.4.8 but did prior to the downgrade work again. The ones broken by the nightlies are likely corrupted.

**Comment by 2xWhiskey** [comment]
> Models are not backwards compatible (ie a model edited or created in a newer ETHOS version will not work in an older ETHOS version), and nightlies may break models (and other data) at any time.
> 
> You cannot use a model edited in 1.4.9 on 1.4.8.
> 
> I recommend updating back to 1.4.9, that should make the models which don't work under 1.4.8 but did prior to the downgrade work again. The ones broken by the nightlies are likely corrupted.

The models never had a chance to be edited.  Some were lost when moving from 1.4.9 to the nightly.  Then, also have never been edited under the nightly, more models were lost moving back from the 1.4.9 to 1.4.8.

Is there an editing program that I can use to perhaps copy the old data from the corrupted .bin to a new .bin profile?

**Comment by mawzthefinn** [comment]
If you loaded them and did anything that might trigger a save, that is an edit. Any time the model gets  saved it is written with the current format. Older versions will not read the current format. 

You cannot downgrade ETHOS versions and expect the models on the SD or internal storage to continue to work if you have touched them in any regard. 

The  models that were ‘lost’ going from 1.4.9 to 1.4.8 should work fine once you go back to 1.4.9

The only way  to reliably ensure you have usable models after a version downgrade is to do a radio backup before the upgrade and then use that  to restore the older model files after downgrading. This should also be done before ever loading a NIghtly.

**Comment by mawzthefinn** [comment]
If you didn't load them, how do you know at which step they were lost?

**Comment by 2xWhiskey** [comment]
Because I opened the model select menu to load up another profile, but the profiles I wanted were no longer showing.  Plugging the radio back into the PC showed the profiles in question as present still on the radio.

And no, they never came back as available.

**Comment by bsongis-frsky** [comment]
If a model has been loaded to 1.5.0, it has been converted already
Please attach one of them if you need I check its format
