### ISSUE TITLE
Improve mixing speed

### ISSUE THREAD

**Issue by mirko91** [FrSkyRC/ETHOS-Feedback-Community#2749]
It will be a great improvement to speed up the mixers. I have a 4 wing servo glider with 4 identical digital servos, G-RX8 with latest Access FW, high speed PWM and 8 channels mode. If I move the stick fast enough there's a lag between flaps and ailerons. Can the loop speed be increased? Back in the years I had the same issue with a Futaba T9CP which had terrible 120° CCPM mixing speed. I think it can be addressed via software

**Comment by mawzthefinn** [comment]
Please attach the model.bin file for the model.

The mixer runs each full pass in less than 4ms, as that is the fastest supported frame rate (ACCESS/TANDEM in Race mode). Unless you’ve either found a bug or have something unusual configured, it’s virtually impossible for visible lag to be incurred by the mixer. Most likely there’s  an issue somewhere in the model programming.

**Comment by mirko91** [comment]
Hi Mawz, here is the model file. Have a look and let me know. The radio is an X18SE. Thank you
[heron.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12062788/heron.bin.zip)

**Comment by mawzthefinn** [comment]
IN testing I see nothing that would generate any lag, nor can I duplicate lag on the Outputs screen even when moving the sticks as fast as possible.

**Comment by mirko91** [comment]
Me neither, I can't see any noticeable lag on the screen outputs. Might be the receiver. I don't know

**Comment by mawzthefinn** [comment]
The outputs are downstream from the mixer, so any mixer speed issues would show there.

IIRC the G-RX8 only supports high speed/high precision on outputs 1-6, so it may be a receiver-side issue. Ch7 & 8 are a little odd on that receiver. You might try swapping in a GR8 and seeing if the issue persists. NB you also have some very different ranges, so I'd actually expect the flaps to move faster from the ail->flp mix as they have greatly reduced throws vs the ailerons.

**Comment by bsongis-frsky** [comment]
All channels outputs are calcultated simultaneously, if some channel seems late, I don't think it's a problem on the radio
