### ISSUE TITLE
Request for Clone of flight mode

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2750]
Currently ' when adding a new flight mode to a model  ... the new flight mode will by default be active in all mixes using flight modes.'

Often it is the case that a new FM is required which will be very similar to an existing FM but triggered slightly differently and maybe with a minor difference in mixes etc.. It is currently tedious and error prone to check and modify every mixer etc. for the new FM.

Given that we can have 100 FM there is great potential for their use, please can we have an option to Clone a flight mode such that the new FM will be a clone of an existing FM. Then it would be easy to rename the new FM, change the active condition and make any minor adjustments for the new FM. I would suggest the new clone should be added as the last FM so that it can't interfere with any existing FM.

Thanks.

**Comment by bsongis-frsky** [comment]
Function added
