### ISSUE TITLE
Conflicting values for Main Voltage

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2751]
I appear to have two different values for main voltage, 8.2V top right and 8.1V bottom left. 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/0206028e-6560-4d6a-afe0-786ab98517f4)

This remained like this for a little while after I initially noticed it before top right eventually dropped to 8.1V

Is it really possible that the refresh time for one value is so much slower than for the other?

(Version 1.5.0 from Mar 23)

Thanks

**Comment by mawzthefinn** [comment]
Have you tried a recent nightly? V1.5.0 from March 23 is an ancient alpha build.

**Comment by Jedsters** [comment]
I've not tried a recent nightly, nor could I see any evidence of it having been reported / fixed before. Am I missing something?

**Comment by mawzthefinn** [comment]
The nightly code base is constantly changing and there is a lot of testing going on which is not reported via Github (all the internal and beta team testers including Bertrand himself). 

A bug report on a 4 month old Nightly build is not meaningful. The current builds are significantly different.

**Comment by bsongis-frsky** [comment]
There is an algorithm to avoid flicker on the top bar.
And perhaps it is not present in the widget on the home screen
But it would need some testing on the latest 1.5.0, not 4 months old!

**Comment by Jedsters** [comment]
I've just tested on the most recent nightly and the top bar dropped from 8 to 7.9v while a widget flickered for some time between 7.9 and 8v which suggests the widget isn't updated.
