### ISSUE TITLE
New Archer Plus rx don't show up in the Info screen.

### ISSUE THREAD

**Issue by ETHOSWarrier** [FrSkyRC/ETHOS-Feedback-Community#2752]
As per title.The new Archer Plus receivers ,both GR6+ and GR8+ when bound to my X20 on 1.4.6 EU don't appear in the info screen telling me what the rx is and software version is. My normal GR6 and GR8 do appear there as normal.

They all work normally, features wise, but don't seem to report their firmware to ETHOS on the info screen.

Anyone else noticed this?

EW

**Comment by mawzthefinn** [comment]
Do they work correctly on current ETHOS?

**Comment by mawzthefinn** [comment]
Just tested on X18 on 1.4.9 FCC with TD-ISRM 2.2.2 and an Archer R6 on 1.0.4

Info screen shows correct info with RX bound to current active model.

**Comment by ETHOSWarrier** [comment]
> Do they work correctly on current ETHOS?

They work normally on 1.4.6 but don't report their firmware on the info screen.I haven't tried 1.4.9 as I was sticking with 1.4.6 for now..do you think that the 1.4.9 has improved the comms with these receivers then Mawz?

I will double check again as i have an x20 and x20s both on 1.4.6 EU ..

**Comment by mawzthefinn** [comment]
TD-ISRM 2.2.4 is the same as 2.2.2, just with XE support

And yes, I suspect that additional support for the Archer Plus series was added in 1.4.8 as the 'new RX support'

**Comment by ETHOSWarrier** [comment]
> TD-ISRM 2.2.4 is the same as 2.2.2, just with XE support
> 
> And yes, I suspect that additional support for the Archer Plus series was added in 1.4.8 as the 'new RX support'

Correct again Mawz.....I put 1.4.9 on and it reports back ok......Phew!          says HW:1.1.0FW:1.0.4

I found 1.4.6 stable..is 1.4.9 as stable?,should I stay on that to fly?

**Comment by bsongis-frsky** [comment]
Branch 1.4.X is stable with minor fixes
Branch 1.5.0 is still very active, nightlies change everyday
