### ISSUE TITLE
Set vario data rate for GR receivers

### ISSUE THREAD

**Issue by mirko91** [FrSkyRC/ETHOS-Feedback-Community#2753]
Currently it is possible to change the data rate of the Vari ADV through the device config menu, but it's not possible to do it on a receiver with integrated vario. It will be a good feature to have, because the standard 0.3 seconds data rate is way to slow. The GRX8 has a standard setting of 0.1 sec which makes it super sensitive, whereas the new ones, including the Archer Plus GR8 are all laggy

**Comment by jasc76** [comment]
+1

**Comment by SmartTommy** [comment]
will shorter the laggy less than 100ms next version

**Comment by SmartTommy** [comment]
[Archer_Plus_SGR_8CH_1.0.8_BETA.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12065499/Archer_Plus_SGR_8CH_1.0.8_BETA.zip)

**Comment by mirko91** [comment]
> [Archer_Plus_SGR_8CH_1.0.8_BETA.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12065499/Archer_Plus_SGR_8CH_1.0.8_BETA.zip) please test if it works as expect

Is it just for Plus receivers or does it work on standard Archer GR?

**Comment by mirko91** [comment]
Bench tested on a Plus GR8 and it's responsive as a GRX8. Is this FW safe to fly?

**Comment by SmartTommy** [comment]
> > [Archer_Plus_SGR_8CH_1.0.8_BETA.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12065499/Archer_Plus_SGR_8CH_1.0.8_BETA.zip) please test if it works as expect
> 
> Is it just for Plus receivers or does it work on standard Archer GR?
it is only for the Archer GR8 Plus.

[Archer-X_2.1.14_Beta.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12066613/Archer-X_2.1.14_Beta.zip)
This is for Arhcer GR8 and GR6.

**Comment by SmartTommy** [comment]
> > [Archer_Plus_SGR_8CH_1.0.8_BETA.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12065499/Archer_Plus_SGR_8CH_1.0.8_BETA.zip) please test if it works as expect
> 
> Is it just for Plus receivers or does it work on standard Archer GR?

It is only for the Archer GR8 PLUS

**Comment by SmartTommy** [comment]
> Bench tested on a Plus GR8 and it's responsive as a GRX8. Is this FW safe to fly?

plese do test and range check before fly

**Comment by bsongis-frsky** [comment]
Then no need to make it configurable :)

**Comment by mirko91** [comment]
It will be nice to have the FW for the standard Archers as well if possible please

**Comment by SmartTommy** [comment]
> It will be nice to have the FW for the standard Archers as well if possible please

[Archer-X_2.1.14_Beta.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12066934/Archer-X_2.1.14_Beta.zip)
Test it carefully!
