### ISSUE TITLE
Multiprotocol telemetry for Graupner HoTT

### ISSUE THREAD

**Issue by AlexEger** [FrSkyRC/ETHOS-Feedback-Community#2755]
referring to issue #2061 

It would be great to have telemetry for the Graupner HoTT protocol too, as I have a bunch of receivers I would like to use. I would appreciate it also very much to have the Graupner HoTT.lua for OpenTX rewritten for Ethos.

Cheers, Alex

**Comment by Fordster39** [comment]
I too would very much need this protocol. I am migrating from Graupner to Frsky and keeping my Graupner gyro receivers and need the Hott.lua for the receiver configuration. 
thanks , Gil

**Comment by bsongis-frsky** [comment]
Duplicate of #2745

**Comment by edgeflyer30** [comment]
I need it too
