### ISSUE TITLE
X20 EthOS 1.0.6: TD-ISRM upgraded to 2.1.7 and the "Spectrum" entry is gone

### ISSUE THREAD

**Issue by Ender1967** [FrSkyRC/ETHOS-Feedback-Community#276]
Where we can find the old firmware versions for TD-ISRM module?
Why the "Spectrum" entry is lost?

**Comment by MIKE-DAILEY** [comment]
The TD-ISRM has never supported the Spectrum Analyzer.

**Comment by Ender1967** [comment]
Never supported ...but it was working before the upgrade to 2.1.7 (probably with the 2.1.5 from factory).
I still want an answer to my question: where we can find the previous versions of TD-ISRM firmware (2.1.5 and 2.16)?

**Comment by bsongis-frsky** [comment]
No, I can confirm. Never supported on TD-ISRM

**Comment by bsongis-frsky** [comment]
Perhaps you could have a look to your SD card, there is not even an icon for a spectrum analyser ...
