### ISSUE TITLE
Using a VAR as an aileron EXPO value produces garbage in 1.5 nightly

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2761]
Using 1.5 nightly of 15 Jul 23

Create a new model glider, select all the default values in the wizard and give the model a name.

Create a simple VAR as below

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/63f9e53a-8f2d-4e31-8d0c-f2a1301dff71)

Edit the predefined Ailerons mixer and select an EXPO curve and give it a value of 50% which produces a a graph as expected

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/fa73ba2a-1a8c-4dc8-acbf-0b0efe17f7cb)

now change the the EXPO value from 50% selecting a SOURCE of the above VAR which has the same 50% value

this now produces a graph which looks like garbage

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/a40c7a5b-13f7-4389-9961-d127397def10)

edit: this worked as expected in my previously nightly from Mar 23 and in the simulator from the same time 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/eb09a6df-ea0e-4a41-a745-7d02177a42a4)

**Comment by mawzthefinn** [comment]
Scaling issue, I'm seeing the same thing in Weights. Scaling is 10x what it should be

**Comment by bsongis-frsky** [comment]
Fixed now. I was in the middle of a big refactoring / simplification around sources and their scaling!
