### ISSUE TITLE
RB25s calibration fails on second step

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#2762]
I got a new RB25s today and I tried to valibrate it. 
According to the manual it should be similar to calibration an SxR receiver.

So I downloaded the Rb25s lua Scripts and installed Ethos 1.4.9.
I started the calibration lua and set the first orientation. At the second orientation (upside down) it always waits and does not recognize the orientation.

Tried to restart receiver and transmitter (R8 Pro, X20s) and restartet the calibration prcess multiple times, but the outcome is always the same.

**Comment by keiner0815** [comment]
Tried it another uncountable times. Got it till step 4 one time, but not till step 6 to complete the process. Sometimes i got to step 3, sometimes to step 2. At the moment it does not even get step one done.

Using an R8 pro via SBUS to RX2 and S.Port to RX1. 
Also tried to configure telemetry on the R8 Pro to FBUS and just copnnect it to RX1, which results in the RB25s not getting any channels from the transmitter.

**Comment by mawzthefinn** [comment]
Are you getting it flat in the second orientation? I found with the RB35S that it really wants to be flat.

I did my setup entirely with a TDMX wired for FBus.

**Comment by keiner0815** [comment]
After it failed I made a frame where I can level it easily in different orientations. But that did not help. 
The faster I do it the farther I come. So if I do it just handheld on the different orientations but I do it fast, it works for most points (but not all so I can't finish the calibration)
If I take my time and level it exactly I do not come past step 2.

I will use the RB25s with two TDMX that I already have, but it needs soldering so I wanted to calibrate it with an "plug and play" receiver that I had at hand.

**Comment by keiner0815** [comment]
Ok, now my problem changed from bad to worse! 😳 

First of all I managed to get the RB25s calibrated. I changed the R8 Pro (brand new out of the box) on Access with an X8R. Connection was the same. SBUS out to RX2 and Telemetry S.Port to RX1.
Calibration worked on the first try through all steps. 

But things got worse after that. First I was happy and secured the RB25s in the plane. After that connected all servos and powered up the RB25s. Now the aileron servos started to move erratically! I emmediately unplugged the battery and retried. Same thing happened. So I unplugged both aileron servos and tried again. Moved the rudder servo and it also started to move erratically.

Tried it with X8R and R8 pro, tried with connected S.Port and without. Tried with FBUS again on the R8 Pro. TEnabled and disabled the stabilisation, changed the value of channel 16 (emergency mode) to -100. Was the same every time.

So I unplugged all servos and detached the RB25s. Tried it with another analog servo that I had laying around. It did not have the erratic movement, or I was not able to see it as it was too short of impulses. 
But I tried to move it from one direction to the other. One direction worked as intended, on the other direction it seemed that it had full servo deflection at around 70% of stick movement. From stick movement 70% to 100% the servo changed direction and went back!?

I double checked the settings in X20s. The erratic deflections are not visible at channel monitor, so it does not get commanded.
The commands ranged from ~ 1900ms to 1050ms, so no extreme values there.

What could that be? To be honest I lost trust in the RB25s completely.

**Comment by mawzthefinn** [comment]
What do you have Signal Period set to in the RB25/25S Config Lua?

For analog servos it should be 20ms (assuming it has the same two settings as my RB35S)

**Comment by keiner0815** [comment]
It is Set to 20ms.

The range variation happens in manual mode and with ~ 1100 to 1900 ms

**Comment by keiner0815** [comment]
Update to the situation:

I had two problems:
- calibration not working past step 2
- erratic movement of all servos when connected to RB25s, no erratic movement when connected to receiver alone (e.g. R8Pro)

- The first problem could be solved by using an X8R receiver instead of an R8Pro
- the second problem could only be solved by replacing all servos

I bought the same servos again (there is a newer version V8 of the KST DS589MG) and they are working perfectly fine with the RB25s.

I don't know why the calibration procedure worked with the old X8R receiver but not with the R8Pro. 

But for me it is **solved** as the calibration process only has to be done once.
