### ISSUE TITLE
Logical switch with function range only works in positive range

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2764]
Hello, by chance I have found that the Range function only works with positive values. For example, if I want to monitor the range <0% in a channel, the LS does not activate when this range is reached. >0% it works.
X10S Express, Ethos 1.4.9

**Comment by jokabre** [comment]
I have same problems, my range  will be  between  -1 and  -5  for normal situation  and  - 6 and -100 for down situation. This doesn`t work.  With positive values the LS will be acticated but this i don`t need.
X20S, Ethos 1.4.9

**Comment by bsongis-frsky** [comment]
I have checked and I see no problem. In your range, is Min < Max?

**Comment by bsongis-frsky** [comment]
First screenshot, your range is wrong, it should be [-100% : -2%], not [-2% : -100%]

**Comment by Wolepo** [comment]
I was barking up the wrong tree. Thank you, it works now.
It can be closed.
