### ISSUE TITLE
SF play sequence haptic default is suboptimal

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2767]
With SF Play Sequence, each item in the sequence has a default of haptic on. This seems suboptimal as by default, the haptic plays again and again for the same active condition for every item in the sequence. I'd suggest that haptic should have a default of off. Alternatively, maybe the haptic option could be removed from the play file and play value sequence items and moved to be a Type of its own, i.e. types of Play file, Play value, Play haptic (with a choice of what the haptic sequence should be),  Wait condition and Wait duration. Maybe Haptic would also then be removed as a SF Action as it is available under Play sequence? (I'm guessing that most of the time people play a haptic they will also want some form of value played so then know what is going on, e.g. if haptic is played because low rx battery wouldn't most also play the rx battery voltage?)

I also notice that the SF Actions include Play Value but not Play File and Play File doesn't include a haptic option. I'm guessing that Play File was removed as it can be actioned by Play Sequence, so surely Play Value is also redundant and can equally be removed.

If Play Value and Haptic were removed as SF Actions, it would be nice if Play Sequence was then renamed, but I'm struggling to think of an alternative, but along the lines of Play Value(s)  Is there a generic term for file, value and haptic which could be used with a (s) to indicate it is for single or multiple play actions?

Ethos 1.5  Jul15th 23 nightly

**Comment by bsongis-frsky** [comment]
Haptic will be OFF by default on PlayValue and PlayFile, but it is needed so that the Haptic is started exactly in the same time than the action

**Comment by bsongis-frsky** [comment]
Play Value will be converted to Play Sequence in the next nightlies

**Comment by bsongis-frsky** [comment]
I don't like Play Sequence too much, but now it could be renamed just to "Play"
