### ISSUE TITLE
Request Self Check for SxR

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2771]
Currently we have under Device config, SxR and SxR calibration. Judging by the comments I've seen of people having trouble entering self-check, it would be useful to have a SxR self check option too. 
This would appear to involve sweeping channel 12, three times in 3 secs, then sweeping channels 1, 2, 4, 5, 6 through the range allowed in Outputs (including any curve limits). 
I'm not sure how appropriate it would be to lock channe 3 (Throttle) at -100% to prevent motor run or whether this could be reversed somewhere, possibly safest to just leave this untouched which will presumably be a throttle off when the user enters the self-check.
If possible, perhaps you could also add a check that the rx channel range is set to ch1 - ch16 since ch9-12 are required and issue a warning message if not. (I suspect I'm not the only person who has spend a while scratching their head why they can't get the SxR working because I've only selected 8 channels.)

Thanks

**Comment by mawzthefinn** [comment]
This would require an update to the S6R and S8R receivers to support the self-check trigger over telemetry as the newer receivers do.

**Comment by Jedsters** [comment]
I don't believe so, I've already 'programmed it' using standard Ethos features (mixes, LS, SF) and had it working. Unfortunately the upgrade to the Jul version of 1.5 wouldn't accept my previous model programs (Mar 1.5) so I'm having to reprogram everything.  

(Of course I could continue to do the above, but given it can be done and the rest of the SxR bits are available it seems sensible to include that too, given that the above is a tad involved.)

Give me a day or two and I'll paste the relevant bits of my setup or possibly create a minimal model def.
Thanks

**Comment by mawzthefinn** [comment]
Self-check is triggered in the SxR menu for Archer SR receivers on 2.1.10 and later.

It’s not for S6R/S8R as this functionality is not present. You have to trigger self-check on Ch12 via mixer onfigurations.

**Comment by Jedsters** [comment]
Please see the attached which is a minimal model definition setup purely to demonstrate how to get an SxR rx into self check mode, put ch3 (throttle) to minimum and sweep channels 1,2,4,5 to get their throws.
It is triggered (for this simple example) with SH down, no further user input is required. 

SH down triggers Sticky LS1 Gyro self chk
LS1 enables the dedicated Gyro self check mode (FM1)
FM1 forces Ch3 (Throttle) to -100% as a safety feature (but see my comment above)
LS1 also triggers LS2 Gyro SC ch12. 
LS2 Gyro SC ch12 is the active condition fo mix Gryo SC ch12 which sweeps ch12 fast for 3secs which will get the blue light on the rx on.
When LS2 turns off, this enables LS3 Gyro SC sweep which is the active condition for mix Gyro SC sweep which sweeps ch 1,2,4,5 fairly quickly to enable the SxR to learn the throws for those channels for 6secs.
After 6sec LS3 disables which in turn disables LS1 which disables the Gyro self check flight mode.

This provides the self check for SxR ACCST receivers. I've no doubt this could be put into a lua or similar and enabled similarly under Device Config. Obviously doing this would save setting all the above up for any models using SxR ACCST rx or trying to do the above manually (which many often struggle with).

[sxr self check.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12139618/sxr.self.check.zip)

Thanks

**Comment by Jedsters** [comment]
Bump

**Comment by mustangzang** [comment]
Is there a way to change direction of correction in Ethos without having to use the STK tool?
