### ISSUE TITLE
Temp Sensor Wrong Reading

### ISSUE THREAD

**Issue by ethos2023** [FrSkyRC/ETHOS-Feedback-Community#2772]
My Temp sensor are giving wrong reading now. I've updated to the newest firmware. Example--- it can be 90 degrees outside but my Temp reading would 54 degrees. After flying the Temp reading may go up to 60 degrees. I also have current sensor on the same planes and they work correctly. Please help if possible.

**Comment by bsongis-frsky** [comment]
Which is your sensor?

**Comment by ethos2023** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/131558524/a491426a-6f20-4f62-975e-8b962b662389)

**Comment by ethos2023** [comment]
this is sensor reading on my radio hopefully this the info you're needing
