### ISSUE TITLE
Sensor lost 

### ISSUE THREAD

**Issue by Minos74** [FrSkyRC/ETHOS-Feedback-Community#2773]
Hi,
I have a X20s on 1.4.9 with Archer R4 and openXsensor.

With a model it works perfectly fine, same config on another model and I have plenty sensor lost alarms on diverse sensors

Attached the log of today's flight

[KRAKEN-700-2023-07-23-08-48-31.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12138459/KRAKEN-700-2023-07-23-08-48-31.csv)

Thank you for your help
Minos

**Comment by mawzthefinn** [comment]
Based on those logs, the sensor lost calls are legit. The Lipo1 sensor is dropping offline constantly in those logs and both RPM and Current are also intermittent. 

I would check the sensor hardware and wiring.

**Comment by Minos74** [comment]
Thank you, I will double check all wires and soldering

Regards
Minos

**Comment by Minos74** [comment]
Went out to the field. Issue closed
Thanks again !

**Comment by mawzthefinn** [comment]
Glad it's sorted
