### ISSUE TITLE
Transfer model settings between TANDEM/ETHOS radios using Wifi connection.

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2775]
Hi guys, im sure this may have popped up before so apologies if it has but is there ever likely to be the functionality to "Send" a model file from one TX to another so we can be lazy and program one radio then Bluetooth or Wifi it to our other radio instead of really painful process of copying over using the PC from one radio to the other lol?? 

If its already been mentioned before @mawzthefinn accept my apologies but would be real handy cause then i can set up both radio's at once at the field. 

Cheers

**Comment by mawzthefinn** [comment]
It's in the nightlies for 1.5 using Bluetooth, so will come with 1.5 release

**Comment by bsongis-frsky** [comment]
It seems that @builda1 likes when we add some fancy function for him, but not so much for other people ;)

**Comment by builda1** [comment]
See this is where you've got everything completely wrong. You ask for feedback and constructive criticism so I'll give you feedback and constructive criticism and then I get attacked for it. 

Maybe some of the people attacking me should try having 40 aircraft set up all the same way based on the very good system that you had implemented and then have every single one of their files get corrupted because of a change. Don't worry Bertrand I won't waste your time, I can think of more constructive people to speak to in China on this topic. For the record I have not "COMPLAINED" about anything I have merely raised an issue which is what you ask us to do, but it seems if I raise an issue that in itself as an issue so forget it case closed

**Comment by builda1** [comment]
> 1

Hi @mawzthefinn hope all is well, thanks for commenting but I will be staying put in 1.4.17 land unfortunately...just means I will have to manually copy over the models instead of use that bluetooth feature i was looking forward to seeing rolled out. 

Long story.....old news now, just wanted to acknowledge you took the time to respond to me last night👍 

Cheers
