### ISSUE TITLE
100% adjustments for Stabi receiver calibration need to be enabled - wrong behaviour?

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#2776]
When a stabi receiver is calibrated, the sticks have to be moved to find the maximum value for the stabilisation system.
But there is a risk. If the sticks are combined with curve in a mixer and they will not send 100% of the output, the receiver learns the wrong value. 
It can happen then that there is a limit in the stabilization that should not be there, because the calibration took not the servo way from the Output. This is a different behaviour compared with receiver without any stabilisation. I would recommend to change this behaviour. The stabi receiver should take over the limits from the definition of the outputs and not from the sticks.
Example: The elevation is limited to 60% with the sticks. Then you add a value for butterfly as a default and together this will be 100%. When you now calibrate the stabilisation, by moving around the sticks, the elevation will be limited to 60% and you will not have enough travel way to cover the butterfly and the sticks travel together. This can be critical.
That’s why I asked for another solution where the output boundary counts and not the sticks output.
I covered that by having a special flight phase, but this is only a work around. The pity is, that not only the stabilisation is limited, but the complete output value as well.

**Comment by mawzthefinn** [comment]
Agreed, I'd really prefer the Stab learn the output settings for endpoints and neutral, not from stick movement. 

It's not just this use case, but users regularly mess up their endpoints trying to self-check and not properly cycling the surfaces even on simple models. 

The old method does need to stick around, for OTX users (unless a new Lua was written for the procedure)

**Comment by BernhardFe** [comment]
Above improvement would be a big step to make it easier. 
But a better way would be (if possible), whenever the boundaries for the output changed, the value will be send automatically to the stabi receiver for a take over without changing the levelling. If this happens automatically, the calibration might be only needed in case of new levelling any more.
But I’m not sure if this may needs a firmware change on the receiver. ;-)

**Comment by Wolepo** [comment]
The receiver can only process what it is offered during the self-test. If you limit the outputs to prevent the servo from blocking, logically only this value may be taught in as the maximum. Therefore, the corresponding flight phase that requires these values must also be selected during the self-test.

**Comment by BernhardFe** [comment]
The corresponding values created during the self test by the sticks can be substituted by the output level of the corresponding channels to reach in any case the full signal that is needed. If the output level of elevation is 95% during the self test, this should be the value to take over for elevation automatically. Then a stick movement is not necessary any more. Only levelling need to be considered.
