### ISSUE TITLE
sensor max value not working correctly

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#278]
Hi! 

Under 1.05 the max value of current jumps back to -0,1A although the current is higher.

Thank you

**Comment by bsongis-frsky** [comment]
Would you please check with the latest release 1.0.6 ? 
Thanks

**Comment by combat-marcus** [comment]
Is there a Telemetry update in 1.06?

**Comment by bsongis-frsky** [comment]
yes

**Comment by combat-marcus** [comment]
No not working either, max Vspd was 1m/s, displayed 1m/s, but "memoried" - 0,1m/s 😳🤔

**Comment by combat-marcus** [comment]
Also the same issue with frsky vario. - 0,01m/s

Not a Problem with Sensors in the plane. 
![Uploading 20210519_181612.jpg…]()

**Comment by jreis1** [comment]
Hey, 

I can also confirm that Vspd (Max) and (Min) is not being stored as expected. It is always showing -0.01m/s, as in the pictures above. 
Ethos v1.0.6, platform:X20, Rx: Archer GRX8.  

Cheers,

**Comment by jfint** [comment]
Also confirming that vertical speed is not working the same as altitude, RSSI, etc for min/max in a bench test with Ethos 1.0.6 and a GR6 with ACCST
![20210519_134125](https://user-images.githubusercontent.com/16928210/118882269-dc00f980-b8a8-11eb-8f26-01ab680a919d.jpg)

**Comment by Nicholas-Luoyi** [comment]
Confirmed here. We will check it...

**Comment by islandflight** [comment]
Same issue with the min/max individual cell voltage- some of cells record 0v

**Comment by combat-marcus** [comment]
Has the max value Bug been fixed in 1.0.7?
