### ISSUE TITLE
Editable model export fairly important for nightlies

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2780]
I have been doing some testing with the 1.5 nightlies, however it seems that it doesn't take much to make one model definition unreadable by the next nightly. This means that models have to be redefined from scratch which is obviously very time consuming (and if I'm honest stops me doing much testing). 
I believe it has been requested more generally, but it would be really useful to be able to export a model definition to some mark-up format which can then be imported if needed by the next nightly, sooner rather than later. 

I accept that even then it may not always work if things get deleted or renamed, but hopefully it would help much of the time when I suspect a change which makes a model unreadable is probably very minor.

Edit: The reason I'm thinking editable is so that a log could possible be created which identifies when mark-up changes are made so that we could perhaps delete an offending line or rename it and import into a later nightly - but that would require a log so that we know what needs changing.

Thanks

**Comment by bsongis-frsky** [comment]
There has been one regression (in Vars) last week, it shouldn't happen. But it's difficult because I have reverted some changes etc.

**Comment by bsongis-frsky** [comment]
The exportable format will be done later, there is another issue for this request, but it's a big one!

**Comment by Jedsters** [comment]
It sounds like I got unlucky.
Thx
