### ISSUE TITLE
instalation irx4 multi

### ISSUE THREAD

**Issue by tboyer95** [FrSkyRC/ETHOS-Feedback-Community#2782]
bonjour,

je decouvre tout l'nvironement lier a ethos donc j'ai reussi a faire la mise a jour de la radio X18 FRSKY mais concernant le module IRX4je suis perdu

merci pour votre aide

**Comment by mawzthefinn** [comment]
Follow the instructions in this video:

https://www.youtube.com/watch?v=ClQQw2238q4&t=2s

**Comment by andika207** [comment]
@tboyer95 https://frskytaranis.forumactif.org/t13083-multi-module

**Comment by tboyer95** [comment]
merci

si par hasard un francophone pouvait me donner les deux trois instruction et francais avec les image j'ai un peu de mal

**Comment by tboyer95** [comment]
en faite je n'est pas tout les répertoires qui sont sure la video ou dans les explication

**Comment by andika207** [comment]
you can close this issue as there's nothing to solve here.
