### ISSUE TITLE
Sensor Conflict

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#2783]
When I power up I get this message.
Using
Archer GR8 Rx running 2..1.14 firmware
FAS 40 ADV current sensor
X18S running 1.4.9 EU

Started getting this message when I started to use the FAS 40 ADV

**Comment by mawzthefinn** [comment]
Check your sensor ID's, it sounds like the FAS40 is using the same ID as the GR8.

**Comment by miggy1952** [comment]
Thanks MAWS, Both the current sensor and VFAS have the same ID 02 0200 (ISRM Rx0)
and it doesn't look like I can edit/change either IDs

**Comment by mawzthefinn** [comment]
You should be able to change the physical ID of the current sensor from Device Config->Current

If not, you can do so with an STK or Freelink and a PC.

**Comment by miggy1952** [comment]
Not possible, all "Greyed out" in Device Config

**Comment by mawzthefinn** [comment]
Either try and set that sensor up with another receiver (that isn't a GR series), or you will need to use an STK or Freelink to program the sensor.

**Comment by miggy1952** [comment]
Should it work in device config and is a bug?

**Comment by mawzthefinn** [comment]
The conflict might be blocking it.

**Comment by miggy1952** [comment]
I only have GR8s, maybe if I can borrow something else I will give it a try.

Not very logical for FrSky products to use the identical ID on their products?

**Comment by miggy1952** [comment]
Found a different rx and changed the ID

**Comment by mawzthefinn** [comment]
Glad you got it sorted. I will pass the feedback on to FrSky so they can potentially assign a different ID to the FAS sensors at the factory.

**Comment by miggy1952** [comment]
Thanks for your help, much appreciated!
