### ISSUE TITLE
Read logs on radio screen

### ISSUE THREAD

**Issue by Jo-le-Papy** [FrSkyRC/ETHOS-Feedback-Community#2785]
I would like to be able to read the csv logs from the radio screen or by default with the Ethos suite.
M$ Excel or Libre Office Calc are not "visual".
Thank's

**Comment by mawzthefinn** [comment]
A graphing log viewer is available in the 1.5.0 Nightlies, it will release with 1.5.0

**Comment by loetefix** [comment]
A very good question. !

**Comment by robertoalmeida** [comment]
They should add this functionality of reading logs on the radio screen in a version before 1.5.0 because it seems to be just a promise.
