### ISSUE TITLE
Tandem X18 started to show very long response time to panel controls

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2787]
For some unknown reason at the field today it took forever to have a response to either the touch panel or either round controllers (bottom left and right). Plus, the power-off sequence is also abnormal
I checked the battery voltages and the Main battery was at 7.6 and the internal was at 3.0 Volts. 

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/2cbb26d8-716d-41f0-b8ff-ebad7ebfeb5c

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/a9e12028-b7ab-44a4-bf4c-36be4986802a

I feel unsafe to use this transmitter until I have a solution to this issue.

**Comment by Richrfl** [comment]
Problem sold (to be validated by the developers) I had 11 MB of screenshots and a couple of hundred logs. After a cleanup of those folders, the transmitter went back to normal. If that is the real problem I would expect a low-memory warning.

**Comment by Richrfl** [comment]
Actually, the X18 does not use an SD card.

**Comment by bsongis** [comment]
Sorry I meant the Nand / eMMC which is used for storage

**Comment by Richrfl** [comment]
Well, it seems that that was the case. I actually had two active actions that used a lot of memory. The log, which for practical reasons I cannot disable, although I will have to clean it up periodically, and the screenshot, which was assigned to SI and was accidentally touched zillion times (I found 11MB of pictures), which is unnecessary and although I keep it, I have it now disabled and will enable it back when I really need a screenshot.
