### ISSUE TITLE
Possible Bug with Clock speed on TANDEM Radios

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2789]
Has anyone else noticed the clock keeps gaining time over the course of a few days? Seems like every time i turn the X20S or X18SE on the clock is fast. @mawzthefinn if this is already Identified please feel free to close the issue. Am running latest release (1.4.9) and it was fine with last release. 
Cheers

**Comment by mawzthefinn** [comment]
You can tweak the RTC speed in System->Date&Time to address this.

It's an inherent issue with RTC clocks that aren't syncing time from an external source (like GPS)

**Comment by bsongis-frsky** [comment]
Problem fixed with the setting?

**Comment by builda1** [comment]
.

**Comment by mawzthefinn** [comment]
The RTC drift is unit-specific, thus the calibration setting. Please try addressing using that setting, it's there for your exact issue.

**Comment by builda1** [comment]
.

**Comment by builda1** [comment]
.

**Comment by hrenz** [comment]
For Example:
My RTC Clock was toooo fast
I had to set the RTC clock correcting to -385 
now the error is les then 1-3s per a week

**Comment by builda1** [comment]
.

**Comment by builda1** [comment]
.

**Comment by mawzthefinn** [comment]
Have you adjusted the calibration setting yet?

It exists to address exactly what you are seeing.

**Comment by builda1** [comment]
.

**Comment by builda1** [comment]
> For Example:
> 
> My RTC Clock was toooo fast
> 
> I had to set the RTC clock correcting to -385 
> 
> now the error is les then 1-3s per a week
> 
> 
> 
>

**Comment by Jedsters** [comment]
Mine is set to -314 and looses 1-2sec per month. It's now the most accurate tx clock I've ever owned. Given I have to change the clock twice a year anyway, a 10sec or so drift I can live with. It needs a bit of patience and playing around to get it very accurate, but you get there in the end.

**Comment by builda1** [comment]
> Problem fixed with the setting?

Yes, I've adjusted RTC setting @bsongis-frsky to about -355 on all 3 of my radios and its within 30 seconds over a couple of weeks so i have left it there-just odd as i never had the issue at all until i first raised this issue! 

Cheers

**Comment by mawzthefinn** [comment]
Closing off as the calibration has addressed the issue
