### ISSUE TITLE
Graphic of curve displayed not correctly

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#279]
Hi! 

This curve looks okay

![20210519_192642_compress24](https://user-images.githubusercontent.com/39466112/118858163-200bf280-b8d9-11eb-817a-0708142571b7.jpg)

In the mixer menu the preview of the curve looks like this:

![20210519_192811](https://user-images.githubusercontent.com/39466112/118858201-2d28e180-b8d9-11eb-8517-659402b95e6f.jpg)

**Comment by Nicholas-Luoyi** [comment]
I don't see this situation here. Would you please confirm that you didn't set any weights or offsets in this Mixer
