### ISSUE TITLE
Receiver SR10+ Black-Box function not available

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2794]
Receiver SR10+ Black-Box function not available
Firmware: 1.08

Transmitter: X20S
Firmware: 1.49

Problem: Menu black box not available

attached screenshots transmitter and receiver

Eugen

![SR10+ Sender Info](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/5e2e0535-ac67-4b34-abc9-43f2c7027d96)

![SR10+](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/67c60b7c-b51c-488a-9dfa-14a5af09ff4e)
![10+ ohne blackbox](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/93403888-fefa-4a71-862c-6ff6a6d8246b)

**Comment by bsongis-frsky** [comment]
Black Box is still not available for this receiver, it will be implemented soon (RF Team, not Ethos)
