### ISSUE TITLE
TD SR12 black box battery 2 missing

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2795]
Transmitter: Tandem X20
Version: 1.49

Receiver: TD SR12
Version: 1.0.6

Problem: Battery 2 is not displayed in the blackbox

Eugen

![TD SR12 Info](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/fbd09d39-f2ca-4d99-a66a-b3229401a29f)
![TD SR12 2 Akkus](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/76b26021-b700-46d5-a367-7c5a1dfc1310)
![TD SR12 Batterie 2 fehlt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/e68b3b2b-a33a-47aa-8f49-3dee606b594a)

**Comment by glipski50** [comment]
Same with TW R8

**Comment by mawzthefinn** [comment]
Just tested with mine, on 1.0.6 firmware. Same behaviour

**Comment by bsongis-frsky** [comment]
The second voltage cannot be displayed, because it is not available on this receiver. We will change the behaviour of this page, so that it doesn't display this unuseful expansion panel.
