### ISSUE TITLE
SR10+ calibration fails on second step

### ISSUE THREAD

**Issue by BoltTed** [FrSkyRC/ETHOS-Feedback-Community#2797]
I have a new SR10+, with all latest firmware update (X20S Firmware TD2.2.4) (SR10+ firmware 1.0.8) (LUA V2.05).

I started the LUA SRX Calibration and set the 1st orientation, ok. Then 2nd orientation (upside down) and it just wait and stay there and doesn't recognize the orientation..

Anyone have this issue, could it be I have a faulty SR10+.

**Comment by Wolepo** [comment]
The 2nd step means font down: Do you have it like this ?

**Comment by keiner0815** [comment]
Is it similar to this issue?
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2762

I could change the receiver as input and it worked.
But you dont have that option. 

Do you also get a "sensor lost" message when entering the calibration mode?

**Comment by BoltTed** [comment]
> The 2nd step means font down: Do you have it like this ?

Yes I have it font down.. and it wait on that screen and never move to next orientation..
![IMG_4836](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/114795245/b70f876d-103c-4e0c-8ab7-21e63d0caf61)

**Comment by keiner0815** [comment]
I couks solve it by using an X8R receiver instead of an R8pro.
But hat is because the RB25s is a Power system and dies neues a receiver.
In your case it IS the receiver. You cant change it.

**Comment by ethos2023** [comment]
I was having issues until I cut page 2  and everything fell in place gyro working great. the instruction hard for me to understand. I went to YouTube and gentleman. the Name of his channel  is 8 hrs to go. hope this will help some one. I was about pull all my hair out--LOL.

**Comment by bsongis-frsky** [comment]
Fixed? I haven't understood the solution!

**Comment by BoltTed** [comment]
Found out if you select Stabilizing to ON in the LUA script SRX Stable, then go back and do the calibration will be ok and won't stuck at orientation screen 2. So that fixe it.

**Comment by keiner0815** [comment]
Could you turn Stabilizing to OFF in the LUA script SRX Stable and try again to calibrate it.
Will it fail again?

**Comment by Wolepo** [comment]
But that has always been the case. If the gyro is switched off (not Stabi off) then it is not addressed and all inputs are passed through to the outputs. This is not an error in the RX, but once again due to the superficial instructions from FrSky.
