### ISSUE TITLE
Include Trim in Free Mix

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#2798]
I would like to see an option to include trim in the Free Mix. I feel it should be included in a line just below the mix source. Something like: Include Trim Yes/No, If Yes a dropdown menu for Trim Source, and a weight for that trim. 

Currently I am using 1.4.9 on an X20S 

It is not currently possible to recreate the canned mixes like the Elevator mix or Aileron in the Free Mix category. One must add a second Free Mix with the trim set as source to accomplish this.

**Comment by hrenz** [comment]
Yes should be trimm select option
T1,T2,T3,T4,T5,T6, or another Analogpoti  with a range

**Comment by fhpage** [comment]
Suggest using Ail, Elevator, Rudder, etc mix.

**Comment by spoke2570** [comment]
@fhpage Those canned mixes don't have output reversing built in. If they did I would be using them. As it is to mimic a canned rudder mix using free mix it requires that there are 2 used. 1 free mix handles input from the stick, and one handles input from the trim tab.  It seems cumbersome when there is already a drop-down menu available on the input line. If it was really cool it would decide to allow a trim inclusion based on whether the input was a switch or an analog.

**Comment by bsongis-frsky** [comment]
Why don't you reverse the output direction in channels?

**Comment by spoke2570** [comment]
@bsongis-frsky I would then have to rework the system of mixes that govern the neutral position of those control surfaces.

**Comment by bsongis-frsky** [comment]
I don't think it is a big work, yes? It would allow you to play with canned mixes without too much effort

**Comment by spoke2570** [comment]
It'd be a lot less work if the canned mixes had reversing switches on their output lines. Right now the easiest way is to add a second free mix to every mix that needs a trim tab. The other way that would make this really easy would be to add an "include trim" button to the dropdown menu on the input line of the "free mix," which would truly set them free.

**Comment by mawzthefinn** [comment]
This is address in the Free Mix refactor in 1.5.0 via Offset action with Trimmer assigned

**Comment by spoke2570** [comment]
Absolutely! ..and so much more! I commented my thanks on the RCGroups as well. I actually will whine a little until there is a PC interface for editing. I have even kept a Windows side open on my Mac in case one or the other is unsupported. 🍿 munch munch 👀
