### ISSUE TITLE
Include Output Reversing in Canned Mixes

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#2799]
I am using 1.4.9 on an X20S

Currently canned mixes like Elevator and Aileron do not allow for output reversal in the mix. This becomes an issue with models using 2 or more servos controlling any one set of surfaces. I would like to see output reversal switches implemented like they are in  the Free Mix category.

**Comment by bsongis-frsky** [comment]
Why don't you reverse the channel in Model / Outputs?

**Comment by spoke2570** [comment]
If I reverse a servo, I would have to rework all the mixes that use that servo. So, right now Aileron and V-tail rudders are set so that they only work correctly if the servos for one side of the plane are reversed or the servo mountings are not mirrored left to right. Also, the model building wizard builds the models so that all of the surfaces (aileron or rudder) move the same direction (all up  or all down) if mounted in the traditional way. 

When this software was new, before many of these mixes had been refined I built most of my fleet, and I really don't want to re-do all of them. If I reverse a servo to use the canned aileron mix then I have to rework all my camber, flap and snap-flap mixes, as well.  The current patch is to add a Free Mix line that Is the trim tab for each control surface set that uses a Free Mix for the main control.

**Comment by mawzthefinn** [comment]
I don't think this is really an issue for most setups. These will be correct for new model setups unless you really get ahead of yourself on programming before the model is ready, and if you are already using Free Mixes, you'd only run into this if both not following the standard direction convention for servos in ETHOS and reworking mixes.

It would clutter up the canned mixes as well, which I tend to be against (they should be deliberately simple IMHO, to make them easier for newer users. Free mixes are the power user's best friend)

**Comment by spoke2570** [comment]
..also it means that the wizard should reverse half the servo outputs dedicated to ailerons or v-tails.

**Comment by mawzthefinn** [comment]
> ..also it means that the wizard should reverse half the servo outputs dedicated to ailerons or v-tails.

The canned mixer does that, it applies a second mirrored curve to the even outputs for dual/quad ailerons and v-tails.
