### ISSUE TITLE
Bind Problem with X12S and S8R ACCST Receiver

### ISSUE THREAD

**Issue by Testname84** [FrSkyRC/ETHOS-Feedback-Community#280]
Access Receivers are working fine but S8R with ACCST are not bindable.

Ethos Version 1.0.6
ISRM Firmware: 2.1.6 EU
S8R Firmware: 2.1.0 LBT

Is the ACCST function not working right now with Ethos?

**Comment by jreis1** [comment]
I was having the same issue, until I updated all my ACCST receivers (X8R and RX8R PRO) to the latest version.

**Comment by Testname84** [comment]
Are you using the last Firmware? It is FCC not LBT.

**Comment by bsongis-frsky** [comment]
Duplicate of #247

**Comment by Testname84** [comment]
It works now. I rolled back a firmware version on the S8R and then flashed the latest LBT firmware again. Receiver bound and everything works.
