### ISSUE TITLE
When selecting a new model it is far too easy to clone instead of selecting the model you want

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#2800]
Especially when using the touch screen.

**Comment by ahvink** [comment]
agree

**Comment by bsongis-frsky** [comment]
And what do you propose?

**Comment by miggy1952** [comment]
As "Select Current Model" would be the most frequently used command, I would suggest that a relatively simple solution might be to add a blank, inactive text box below "Select Current Model"

**Comment by Dsrenger** [comment]
When you want to change the model you can just long press on the model you want to load.

Ethos will directly switch to the model without the need to go through the menu.

The solution ist already there...

**Comment by miggy1952** [comment]
Indeed that works but if you did a short press by mistake as I often can, I sometimes end up with a clone by mistake

**Comment by ahvink** [comment]
I too suffer from 'thick finger syndrome' and have had several occasions where clones were added while trying to select a model.
No fault or bug in Ethos, just something that tends to happen.
So a blank menu item below 'Set Current Model' would also be welcomed by me ;-)

**Comment by BladeScraper-Designs** [comment]
I agree with this.  I have cloned many a models lol.  I think a simple "Confirm Clone model?" dialog after tapping clone would be a good solution.

**Comment by horifaydo81** [comment]
I also find it scary that the options tab appears when double-tap..... I think that the model program should be loaded on a double touch, and the options tab should appear on a long touch.

**Comment by Target0815** [comment]
> And what do you propose?

A simple query box if a clone of the model is desired.

I don't have "fat" fingers, but too often a clone happens without me wanting it to.

**Comment by jasc76** [comment]
+1 
but will try to change my brain to long-press :-)

**Comment by Toffs** [comment]
How about this as an enhancement - instead of just doing the ‘are you sure you want to clone’ popup,  it’s ‘what do you want to name the clone’ text input field + have a ‘cancel’ option. You press cancel to go back.

The reason for this ‘name the clone’ popup is once you’ve cloned a model, it’s got the same name as the original and the very first thing you must do is rename it before things go awry. Most UX don’t let you have 2 files/models with same name, so this would solve both issues with 1 popup.

**Comment by Toffs** [comment]
I still strongly believe it’s important to ensure any new model Clone is renamed immediately upon creation / it shouldn’t be possibly to have 2 models with the same name.
So the solution or some variant mentioned above should be considered, which will also help mitigate accidental clone and model management mistakes in general.

**Comment by spoke2570** [comment]
Ya the totally identical name when cloning is super annoying. Af fresh clone needs a whole new name like 'Clone 1-originalmodelname'. I also think that cloning should get all the UI protection deleting (models) would get as discussed in #3710 .
