### ISSUE TITLE
Radiomaster ER8GV no ability to play vario

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#2801]
access to "play vario" in the telemetry sensor menu as in the second screen shot
No

TX hardware: FrSky X18S firmware 1.4.9, EU
RX hardware: Radiomaster ER8GV running v 3.3.0
Handset model:
OpenTX version (including nightly number)
ExpressLRS version (TX & RX MUST MATCH):
Packet Rate: 100Hz Full
Telemetry Ratio: 1:16
![screenshot-2023-08-08-45772](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/88764415/692f4b9b-ae23-43ce-b4cc-86cfd19c1711)
![screenshot-2023-08-08-45737](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/88764415/b07d4837-8753-4653-bbf5-2337bff72d19)

**Comment by miggy1952** [comment]
Apparently it works fine with OpenTx and EdgeTX so I assume this to be ETHOS specific?

**Comment by mawzthefinn** [comment]
See the suggested fix in #2398

**Comment by miggy1952** [comment]
Thanks Mawz but this is not the fix, I have another Matek ELRS that is playing the vario perfectly. Are you saying that this is an ELRS problem and NOT ETHOS related.

**Comment by miggy1952** [comment]
[pkendall64](https://github.com/pkendall64) thinks this is an ETHOS issue

**Comment by mawzthefinn** [comment]
I think @bsongis probably needs to add that new ID as a valid Vario sensor.

**Comment by miggy1952** [comment]
Super thanks for your help Adam

**Comment by miggy1952** [comment]
CapnBry says, The VSpd is sent as part of the "Baro Alt / Vario" telemetry package. This was added to EdgeTX almost a year ago so it is likely ETHOS doesn't support it?

ExpressLRS doesn't send just the bare VSpd because splitting Altitude and VSpd into their individual telemetry types would double the number of packets required to send them, which would reduce the vario update rate to 1/4 (best case, but likely even less when you count missing packets).

**Comment by mawzthefinn** [comment]
If CapnBry was correct, no ELRS vario would be working. The Vario functionality in ELRS has been supported for a while in ETHOS.

**Comment by miggy1952** [comment]
For the fix, will we have to wait for the next ETHOS release? Is there anything I can do meanwhile?

**Comment by mawzthefinn** [comment]
The only thing you could do now is change the sensor ID that the receiver is sending.

**Comment by miggy1952** [comment]
The sensor ID fields are "Greyed Out" and not available to edit

**Comment by mawzthefinn** [comment]
> The sensor ID fields are "Greyed Out" and not available to edit

YOu need to change it on the receiver, not on the radio. That’s an ERLS thing and I can’t advise how to do so.

**Comment by miggy1952** [comment]
[pkendall64](https://github.com/pkendall64) tells me that.

"If we change it ETHOS then we break EdgeTX. I think EdgeTX has a much bigger community. Perhaps a bug report for ETHOS is a better place to start."

**Comment by mawzthefinn** [comment]
That’s wrong on 2 levels.

1. It won’t break EdgeTX at all. The only thing that would happen is that the RM receiver would be using the same vario sensor ID as the Matek receiver. EdgeTX understands both already, ETHOS only knows the Matek ID. 

2. You’ve already submitted the bug report. You were asking for an interim fix until ETHOS gets updated. Changing the RM sensor ID to match the Matek one is the interim fix. It shouldn’t break anything since you aren’t going to have both active at the same time.

**Comment by miggy1952** [comment]
He says to us,

So, my stance is it's still an ETHOS issue. The ER8GV has a barometer and we send the values as CRSF packet 9 which has both Altitude and Vertical Speed.
This EdgeTX code show the parsing of the 0x09 packet.
https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/crossfire.cpp#L146-L163
And this shows the 0x07 packet.
https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/crossfire.cpp#L126-L128

Trying to cajole devs into making changes by saying the system is inflexible is not a way to get things moving.
By saying that ELRS is inflexible because it can't be configured to put the data on a different packet id, cuts both ways.
Is ETHOS so inflexible that it can't configure which packet it gets the data from?

**Comment by miggy1952** [comment]
And he has closed the issue as a completed item.

Looks like I need to buy more Matek in future for my F5J fun!

**Comment by mawzthefinn** [comment]
OK, that's a different sort of ID than sensor ID's (which are just bus ID's and should be assignable).

They're talking about data type ID's, which do require an ETHOS update, not a simple ID change.

This is mostly a misunderstanding, sensor ID seems to mean 2 different things in the two systems.

**Comment by miggy1952** [comment]
Thanks Adam, looks like we are making some progress.
Question: If you were me and knowing what you know, how should I best proceed?
I want to use a vario, switching RXs in my F5J glider is a big faff, not much room. I like the form factor of the ER8GV it fits perfectly. Your best guess, will a fix be months, or weeks. So that I know if it is worth reinstalling the Matek.

**Comment by m0p3d** [comment]
Confirmed same here. the ELRS / ER8GV implementation is state of the art and results into ID 09 in Ethos which isnt capable of played as vaio sound

**Comment by bsongis-frsky** [comment]
It should be there in 1.5.0 nightlies
