### ISSUE TITLE
Setting ELRS Failsafe 

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#2802]
Failsafe is easily set via the ELRSv3 Lua script on EdgeTx. You just select Other devices, choose the receiver, and then Set failsafe. I can't see how you do this with ETHOS

**Comment by mawzthefinn** [comment]
Is the setting not available in the receiver options menu (which is the ELRS Lua in this case)?

If not, then the ELRS Lua would need an update to account for this setting. That's a community-maintained Lua.

**Comment by miggy1952** [comment]
No it is not available in the receiver options menu in ETHOS in EdgeTX and OpenTx it is working fines

**Comment by mawzthefinn** [comment]
Then the ELRS Lua needs an update. This isn't baked into ETHOS.

**Comment by miggy1952** [comment]
Thanks Adam, so if I understand correctly, you mean that the Lua script here needs updating? https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua

**Comment by miggy1952** [comment]
[pkendall64](https://github.com/pkendall64) thinks this is an ETHOS issue

**Comment by mawzthefinn** [comment]
> Thanks Adam, so if I understand correctly, you mean that the Lua script here needs updating? https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua

Yes, or an adaptation of that Lua by someone in the community. That is a reference Lua that was provided and may be updated by the community. 



> [pkendall64](https://github.com/pkendall64) thinks this is an ETHOS issue

I disagree, ETHOS is just passing through the data to the configuration Lua It needs to know how to present it

This is NOT an ELRS project maintained Lua, just to be clear.

**Comment by miggy1952** [comment]
Found it, my stupidity sorry!
