### ISSUE TITLE
"invalid data" when opening a model that was used with a former 1.5 nightly

### ISSUE THREAD

**Issue by onki69** [FrSkyRC/ETHOS-Feedback-Community#2803]
I am having trouble with model data, that causes an error when opening the model.
The model was already used with a former nightly version of Ethos 1.5.
When I try to open that model with a later nightly versio I do get an "invalid data" message and cannot use this model anymore.
It needs to be defined from scratch which is not very convenient.
It happend already on four of my models.

Is there such a big difference in the model data file between the different nightly version that cause the problem?
Migration of older models after installing the first ntghtly was no problem in the past.

**Comment by mawzthefinn** [comment]
Yes, this is an issue that can and will crop up periodically with nightlies as the data format changes and conversion may or may not be present from an old nightly to a new nightly. 

Any model file opened on nightlies should be considered as a test-only model and may be rendered unusable in the future.
