### ISSUE TITLE
VFR low warning on startup

### ISSUE THREAD

**Issue by rFlightFPV** [FrSkyRC/ETHOS-Feedback-Community#2804]
I quite often get a "VFR low warning" once when plugging in my aircraft. It seems the radio is quicker on detecting low/zero VFR before telemetry is established. Setup: X20S on latest firmware (the issue also was present on earlier firmwares), ACCESS receivers on latest 2.1.8 firmware (issue also present on earlier rx firmwares). Will check if I can also get this warning when using a GR6 on 2.1.14. I think it also happens on my few ACCST receivers.

**Comment by rFlightFPV** [comment]
Thank you Bertrand!

**Comment by pstasek** [comment]
The same applies to the Logical switches based on telemetry values which are sometimes triggered before the correct value is stabilized after powering the model. Not a big deal but getting a bunch of false alarm warnings in about 50% of cases when the model is powered up can lead to ignoring the actual problem.
