### ISSUE TITLE
Request: Idle up function in throttle mix

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#2805]
Since there is Throttle cut and hold in the Throttle mix, it would be nice to have an Idle up function. Other transmitters offer this so it would be nice to see it in Ethos. I currently do it by applying a custom curve that just raises the bottom by a few percent.

It is beneficial for gasoline engines so that you can have a slightly higher idle while flying so that it won't die during high energy maneuvers, but only requires flipping a switch to drop to a landing/taxiing idle. I also run them on all my electric planes because the throttle response from is much better if the motor never stops.

The curve method gets awkward when you actually need a curve to help make the throttle more linear, but also want to run an idle up. And having to bump the trim up and down is not ideal either, though I know some do that instead.

**Comment by mawzthefinn** [comment]
The curve is how I do it today. 

This will be trivial to accomplish with a VAR in 1.5.0, as you can assign VAR values to a given curve point. Use a VAR for the left point of the curve, with two values (idle up and idle down). It will even be adjustable via VAR actions. That will let you have 1 curve with 2 idle points (and full adjustability of the idle points)

**Comment by rburrow87** [comment]
Playing around with that in 1.5.0 simulator now--pretty cool! But to be honest, that and the current curve solution seem like an over-complicated way to do something that is as easy as picking a switch and telling it how much extra + or - throttle trim to add in other radios. It just feels like something that should be a dedicated function like throttle hold and cut, at least in my opinion.

**Comment by enzo-molinari** [comment]
An idle-up function would be a useful enhancement.

**Comment by pstasek** [comment]
I'm currently using Flight mode with separate trims to achieve this. That way I'm able to set my landing idle trim and acro idle trim but it's not as optimal as it eats up flight modes for this task. 

Another option is to use the linearization throttle curve inside for the Throttle servo output and use the elevated idle as a 2-point linear curve for the throttle mix.

Having elevated idle as an option in throttle mix would save some tinkering for sure as this feature is common for any gasser I have.

**Comment by mawzthefinn** [comment]
With the new trim system in 1.5, you can now use a switch to select between trim values without wasting flight modes. This makes idle up even easier to do

**Comment by rburrow87** [comment]
> With the new trim system in 1.5, you can now use a switch to select between trim values without wasting flight modes. This makes idle up even easier to do

Well that's pretty nice! Don't really need this idle up thing then since this is all it would be doing anyways :)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1323809/72f2789b-e8d4-464f-937e-ba15ed305d9a)

**Comment by mawzthefinn** [comment]
Will close off the issue then. 1.5 is going to be really nice for stuff like this.
