### ISSUE TITLE
Error in function Logical switches

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2808]
Error in function Logical switches

Functions are incorrectly labeled

Greetings Eugen

![Version](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/255bb8af-1b50-4e05-aeff-86f21dbed220)
![Log1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/763d8255-44d2-441e-9318-c1233d2badf4)
![Log2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/2bfe0c75-2ac5-4b14-8366-57f7b80c39a2)

**Comment by mawzthefinn** [comment]
Everything is displaying correcting on my X20, Aug 11 Nightly.

**Comment by yak55** [comment]
Hello, have tried 2x with update from 1.4.9 to this version.

Please set once the language to GERMAN and then try again.

With me it is always the same wrong in GERMAN.

Greetings Eugen

**Comment by yak55** [comment]
So, just now the possibility to test.
If you change the language from German to English, everything is immediately ok.

If you switch back to German, everything is wrong again.

Hope that helps.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
This problem will be fixed in 1.5.0
Translations will be made from CSV files, it has been completely rewritten
