### ISSUE TITLE
Feature request: Checklist, invert throttle check for greater than 95

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#281]
In 1.0.6 you cannot invert the throttle setting of the checklist, only disable it.  Gliders that use the throttle for camber would be the main reason for this added feature.  It prevents fragile molded flaps from being smashed into the ground by servos on power-on.

**Comment by Nicholas-Luoyi** [comment]
Hello there. You could scroll directly up to 95% rather than scroll to -95% and enable an invert. Does this work for you?

**Comment by jfint** [comment]
Precisely, that would complete the feature.

**Comment by Nicholas-Luoyi** [comment]
Thanks for your feedback!
