### ISSUE TITLE
X20S 1.5.0 simulator interprets wrongly "7" and "8" keys

### ISSUE THREAD

**Issue by MiRe-CZ** [FrSkyRC/ETHOS-Feedback-Community#2811]
As reported already in #2579, created in the mid of April, there is issue with X20S 1.5.0 simulator - both "7" and "Ctrl 7" are interpreted as FS5 and both "8" and "Ctrl 8" are interpreted as FS6

**Comment by bsongis-frsky** [comment]
This is strange the function keys of the computer should be moving the function switches of the radio, not the numeric keys. Does anyone else reproduce this issue?

**Comment by bsongis-frsky** [comment]
This is strange the function keys of the computer should be moving the function switches of the radio, not the numeric keys. Does anyone else reproduce this issue?

**Comment by bsongis-frsky** [comment]
This is strange, the function keys of the computer should be moving the function switches of the simulator, not the numeric keys (they are used for trims). Does anyone else reproduce this issue?

**Comment by bsongis-frsky** [comment]
This is strange, the function keys of the computer should be moving the function switches of the simulator, not the numeric keys (they are used for trims). Does anyone else reproduce this issue?

**Comment by bsongis-frsky** [comment]
This is strange the function keys of the computer should be moving the function switches of the radio, not the numeric keys. Does anyone else reproduce this issue?

**Comment by bsongis-frsky** [comment]
The calibration is not possible with the simulator!

**Comment by Wolepo** [comment]
This is correct, but this should only be an example for the display. You can still see this in the Hardware test menu.

**Comment by Wolepo** [comment]
A little video. Only the numeric keypad is used.
[Tastatur.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12338019/Tastatur.zip)

**Comment by MiRe-CZ** [comment]
Thanks for video. I originally discovered this with the throttle and elevator "sticks" up (Ctrl Num 8 and Num 8). During test it turned out Ctrl Num 7 and Num 7 have similar issue.
Issue with the throttle reported also Hartinger in frame of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2579

**Comment by bsongis-frsky** [comment]
I have changed the detection method for function keys. Please check the next nightlies, because I cannot reproduce this problem with my keyboard, thanks!

**Comment by MiRe-CZ** [comment]
In the X20S sim published today (2023-08-25) are movements related to Ctrl Num 8, Num 8, Ctrl Num 7 and Num 7 fully OK. 
I but discovered another issue - all controls related to Num 1-3 and Ctrl Num 1-3 goes to 0% when "pushed" to/below -100%. When are then moved up, they jump to 80%

**Comment by Wolepo** [comment]
Keys 2, 4, 6 and 8 still work as shown in the video. Keyboard QWETZ, but is not different with the other options.

**Comment by MiRe-CZ** [comment]
OK, small correction - Num 1, 2, 3, 4 and Ctrl Num 1, 2, 3, 4 keys behave wrongly and controls go to 0% when "pushed" to -100%. When are then moved up by a relevant key (e.g. Num 7, 8, 9 or 6), they jump to -80% after first push
