### ISSUE TITLE
Emergency Mode

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2813]
Hi,

Today I did a flight, and a s soon as I finished the flight, the Tx, (X18SE), went into emergency both. 

ETHOS 1.4.9. 

Replacing SD card just in case it was the SD card.

One question. If the Tx went into emergency mode in flight, do I still have control of the aircraft?

**Comment by bsongis-frsky** [comment]
Did you do anything special? Or just land?

**Comment by salibaj2** [comment]
I was flying a Goosky S2.

Landed, picked up heli in one hand, X18SE in the other hand.

All of a sudden it begin beeping, thought I hit a switch or something, placed helu on table, and when I looked at Tx it was in emergency mode.

Since then I changed SD card. 

A question. Is it better to store models on SD card, or Tx NAND?

If for example I have a mix for landing gear, and model is saved on SD card, and this emergency mode kicks in, does the landing gear activates or just sticks do work?

I am thinking of using this Tx in some expensive models but this scared me.

**Comment by mawzthefinn** [comment]
Generally NAND is preferred. SD card quality is quite variable and there's a lot of counterfeit ones out there. 

I don't use SD on any of my NAND-equipped radios.

**Comment by bsongis-frsky** [comment]
Is it possible you attach your Model settings (the .bin) file here? I would like to check everything. It's not normal to enter EM even if all controls remain working.

**Comment by salibaj2** [comment]
Sorry for the late reply. I missed your reply.

Attached model file as requested.

[goosky s2.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12506389/goosky.s2.zip)
