### ISSUE TITLE
Request for version info of the LUA scripts

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2814]
Since there are now different versions of the scripts, it would be helpful the version would be displayed with.

Please both in the script overview and when the script is open.
This concerns all scripts, but especially the SxR scripts.

I have attached a sample of FrSky and "angel scripts".
Please like "Fa. Engel" already does it.

Greetings Eugen

![Seite 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/f42a632b-d876-4381-a059-810979bfa6c7)
![FrSky Lua](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/02483ea7-8be6-4ece-9dcb-6a1b9815687b)
![Engel Lua](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/c709ec33-94f4-4eed-a036-014e5ae1b7bb)

**Comment by bsongis-frsky** [comment]
It is the script responsability, not Ethos!
