### ISSUE TITLE
Archer SR10 Pro and SR 10 PLUS stop working

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2816]
I don't know exactly when this happen, but the fact is that the SR10 Pro started to behave weirdly. When I first installed the unit, I was requested to add an SXR LUA, and everything worked just fine, but shortly ago, after I added the SR10 Plus to my stock when I went to check the gyro operation in the Pro, I found out the problems. Attached are the FW revisions I have installed and the FW available in my folder. All the latest versions are installed.
Here is what happens:
The gyro does not work at all.
In the Model>Device Config>SXR, if I set the SXR to ON, I lose all controls.
The System>SXR Stable screen is all greyed.
It seems clear to me that there is some incompatibility between some FW I have. I checked at FRSKY LUA download to see if there shows an updated SXR LUA, but I found nothing there.
The same happens with the PLUS, with the exception that in this case is the System>SXP Stable screen the one that has the control.
![FW 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/86a76ae0-f259-4fab-8a80-17b0f9a61e90)

![FW 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/8342bb1b-a0de-421a-be03-8d54dea333cd)
![screenshot-2023-08-16-37059](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/44da979d-9a26-4379-94c6-a3093d90057d)
![Controls working](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/35e95855-ed77-4a41-9238-aa608d23449b)
![Pro System LUA](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/3d7e16b9-7a8f-4163-becb-63a48ec468c7)

**Comment by Richrfl** [comment]
Quite right! It happened that I run the self-check without moving the sticks at all, and that caused the unit to set the range to 0.
I still have a problem though. Both planes have some trimming applied to the aileron and elevator, I was trying to adjust the auto level offset to match the position of the surfaces in auto level mode to their trimmed position in normal mode, but when I change to auto mode, the surfaces stay in the centered position disregarding which value do I set between -20 and +20 for the offset. Why should that happen? I run the self test with the unit in normal mode, level flying attitude.
![Trims](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/96999441-27f9-4e01-a17a-3a15d9c43295)

**Comment by mawzthefinn** [comment]
I’ve always found the need to tweak the offset settings to ensure the aircraft flies in teh desired attitude.

**Comment by Richrfl** [comment]
And were you successful? How did you it? because otherwise, it seems to me that the auto-level feature is pretty much useless. I think that the whole calibration system should not only record the plane attitude but also the position of the controls in usec, as it seems it is assumed that all controls are centered in 1500usec, which is very unrealistic in the real world.

**Comment by Richrfl** [comment]
Anyways, what is that offset setting for?

**Comment by mawzthefinn** [comment]
I've been very successful with the use of offset.

It's there to adjust for minor installation errors and to dial in desired attitude (you very rarely want the aircraft flying truly level, as that's actually a mild descent on most aircraft, you need positive angle of attack to fly)

I've also used it to turn self-level into a launch mode, with a little extra up dialled in, and sometimes a bit of roll to counteract torque on launch. I use this on my hand-launch EDF's.

**Comment by Richrfl** [comment]
OK. I understand the idea. Makes a lot of sense, since the calibration process is done on the bench. Therefore, is there any way to adjust for the trims offset? Shouldn't that be the job of the self-test procedure?

**Comment by mawzthefinn** [comment]
That's a good question. There's two basic zero functions, one is stick detection (which it definitely is learning), the second is neutral point of the surfaces, which doesn't seem to be learned well.

**Comment by Richrfl** [comment]
Well, I do not have it clear what you call basic zero functions, as the receiver cannot see the stick positions. It seems to read the range, and assume what I guess you call neutral point is in the center of the range, instead of reading the center stick pulse width.
![Mixer Trims](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/e317cb2f-4f7a-41b1-a0d1-04a178faf6d8)

**Comment by Richrfl** [comment]
I closing this issue, and opening a new one requesting an update to read the center points.
