### ISSUE TITLE
Audio not working and no logging in 1.4.9

### ISSUE THREAD

**Issue by phaedradg** [FrSkyRC/ETHOS-Feedback-Community#2817]
On the 6th flight of the day, I had the audio cut out completely early in the flight.  Audio was working before takeoff, as I heard the callouts for throttle cut off and flaps.  After a short while, I noticed that I didn't get any more callouts, not from telemetry, nor from my timer.
When I check the log file for that flight, it is completely empty.
The flights before that one, everything was normal and telemetry was logged.
On the next restart of the radio, everything was back to normal again.
This is the same sort of symptoms as we had before 1.4.9.
I am using a Tandem XE radio.

**Comment by bsongis-frsky** [comment]
Which radio? Is the SD Card reliable?

**Comment by phaedradg** [comment]
As mentioned, radio is Tandem XE
SD card is Sandisk, worked perfectly before this incident/issue, with hundreds of log files on it.  After radio off/on, audio was back.

**Comment by kvak1** [comment]
Me nerly the same as Phaedradg. 13th this month, radio X20, firmware 1.4.9 - EU. After restart all correct.

**Comment by kvak1** [comment]
...addition. Before radio stop speaking I some time called sound information from current sensor and vario with short pauses..

**Comment by mawzthefinn** [comment]
Is this still occurring under current 1.4.12 or 1.4.13 firmware?

**Comment by mawzthefinn** [comment]
Closing off due to no response to last query
