### ISSUE TITLE
rpm temp senors not working in ehtos x20s 

### ISSUE THREAD

**Issue by mkeigwin12** [FrSkyRC/ETHOS-Feedback-Community#2822]
i have been trying to setup the temps senors on the telem page for deg f , when i put the -4  +482  the temps are not showing the correct temps , when i use edge tx all works as should.

**Comment by bsongis-frsky** [comment]
Please attach a screenshot of your config, we are missing some information here!
Unless it's the °C / °F conversion which has been fixed for 1.4.11?

**Comment by mkeigwin12** [comment]
![IMG_4485](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91027750/136866e7-78ed-4112-8c32-19072d8d5b14)
![IMG_4486](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91027750/72d37467-b13d-470f-8e39-46e98c42e6b0)

**Comment by mkeigwin12** [comment]
![IMG_4484](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91027750/5d7f7e6b-e2a5-4728-8e09-0b1f7d2403b2)
![IMG_4483](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91027750/7cc2a054-6219-4411-b19a-e8a504dcc0b9)

**Comment by mkeigwin12** [comment]
i was still on stable ver 1.4.9 up dated to 1.4.11 & all is working now thanks
