### ISSUE TITLE
TRAINER MODE min button is max

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#2823]
Hi,
 When i touch  the Min button on my  x20 i've got 131%  and 125% when i touch the max button on every student channel, 125 % is not enough  for specktrum radio and in fact i have to select 131% to get the full travel  of a student mode spektrum radio  stick. i have a question beside the fact that min value is wrong, why a max value of 131%?
It would be great to have different trainer model mode and channel assignment in memory for one model (eg : student  mode 2 spektrum teatcher mode 1) and perhaps global too

Thanks

**Comment by mawzthefinn** [comment]
Turn the range up on the Spektrum side to 125%

Spektrum 100% is only 78% in ETHOS or OpenTX, so you are scaling in ETHOS to try and match the lack of range in Spektrum. 

125% is the normal limit because 125% on top of regular ETHOS 100% is the limit for SBus channel data.

**Comment by ronron84** [comment]
hi mawz,
thanks, The spektrum transmitter i use is an old lp6dsm, and there is no way to turn the range up, but it works like this with 131% (76% of ETHOS).

**Comment by mawzthefinn** [comment]
In that case you will need to live with the issue, because the 125% limit is for safety reasons, and really you are scaling to address the fact the student transmitter never gives you full range due to the default Spektrum range being smaller

**Comment by bsongis-frsky** [comment]
Min should be -125
Max shoult be +125
