### ISSUE TITLE
RB25S LUA- AIL3 and ELE3 enable/disable missing

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2824]
Hello,
i can find enable disable for AIL2/ELE2 and AIL4/ELE4 but AIL3/ELE3 seems to be missing from the menu.
X18S Ethos 1.4.9with latest RB25S LUA downloaded today.

thanks.

**Comment by mawzthefinn** [comment]
They’re controlled by the on/off for stab 2.

the new system in Basic Mode functions as two semi-independent stabilizer sets, of 5 channels each, sharing only the gain and mode channels

**Comment by bsongis-frsky** [comment]
This Lua script will be soon included inside the firmware, and localized

**Comment by i3dm** [comment]
> They’re controlled by the on/off for stab 2.
> 
> the new system in Basic Mode functions as two semi-independent stabilizer sets, of 5 channels each, sharing only the gain and mode channels.
> 
> you can only independently enable/disable the second aileron and elevator channels in each set

So ail3 and Elev3 cant not be AUX channels?

**Comment by mawzthefinn** [comment]
> 
> So ail3 and Elev3 can not be AUX channels?

They can be Aux channels only if you disable the second stab set (limiting you to 5 channels of stabilization).

**Comment by LeoCheung123** [comment]
That's a shame. Rudder2 is useful for any plane that has nosewheel steering, but most planes will need flaps, gear, brakes, brakes and airbrakes before they meed ail3!!

**Comment by mawzthefinn** [comment]
Do you actually stabilize the nosewheel channel? I normally run mine unstabilized even when I have a channel available to stabilize it.

**Comment by mawzthefinn** [comment]
Also as RBMixer is now released, this can be configured as desired with the RB25S IMU set to ADV MOde and programmed with RBMixer. Basic mode is more basic in configuration for those who do not have more complex setups

**Comment by LeoCheung123** [comment]
> Do you actually stabilize the nosewheel channel? I normally run mine unstabilized even when I have a channel available to stabilize it.

Yes i do on every plane. I fly off a nice concrete runway with some uneven surfaces with gusty crosswinds. Without nosewheel and rudder gyro correction, the plane feels like it is skating on slippers, with a lot of gyro gain it feels like it is on rails. For me, the stab on this channel is probably more important than ail/elev.
