### ISSUE TITLE
Archer SR10 Pro not reading the surfaces center point

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2825]
Situation: When you have trimmed your aircraft, after the self-check procedure, when you set the receiver to Autolevel, the surfaces do not go to the position of normal flight defined by the trims, but either to the standard 1500usec or the center of the measured range. This makes the Autolevel completely useless, considering that 99% of the planes require trims that can even change over time.
Not being an expert in coding I dare to suggest reading the model center position in the first stage of the self-check process (light steady blue) and setting those values for the auto-level mode.
Here is a screenshot example of a trimming case I have.
The SR10 Pro has installed FW 2.1.14.
![Mixer Trims](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/c43ea2cb-df55-4dca-8a39-1db1155a9476)

**Comment by 4qr1hu9n7** [comment]
Recalibrate your transmitter. Also check your aileron trims.

**Comment by 4qr1hu9n7** [comment]
Also. I found that the 2.1.14 firmware is defective. I was not unable to setup auto level. I rolled back the firmware and everything works just fine. Just because their is a new release does "not" make things better !

**Comment by Richrfl** [comment]
Well, why I am not surprised a code update fixes some things and mess some other that used to work? After all I have been using Windows forever, therefore, I am used to this kind of problem. The difference is that the developers of Ethos are much better than those from MS, and they take their job more seriously. I will step back to the previous version and see what I get, but I am sure version 2.1.10 works, as that was my previous version.
Thank you for the lead.

**Comment by 4qr1hu9n7** [comment]
You're welcome. The previous release is fine.

 

4qr1hu9n7

**Comment by Richrfl** [comment]
I'll go for it. Thank you.

**Comment by bsongis-frsky** [comment]
NanLi just told me that he has sent a test firmware. Waiting for feedback.

**Comment by bsongis-frsky** [comment]
Duplicated of #2679
