### ISSUE TITLE
Simulator X18S released 23-6-18 weird behavior

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2826]
I was able to successfully dump my models to the simulator, but for some weird reason there is one model that consistently gives me an error "Invalid data" when I want to set it up to work with it. Also, when I try to delete it, it disappears from the screen but then reappears back again. I noticed that in this case the reason to show up again is because in the delete process the model is not deleted from the model's folder.
I would be happy to share the model bin but I don't know how to send it in.

**Comment by Wolepo** [comment]
Tip: kloon het model dat defect is en activeer het. Nu zou het moeten werken.

**Comment by Richrfl** [comment]
Brilliant Tip!!!! Thank you
