### ISSUE TITLE
Red linear slider mapping / naming changed from X20S to X20S Pro

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2827]
Hello,

trying to investigate a new issue that rose when testing X20S Pro:

1. When copying a model which has a mix associated to Pot3 (red linear slider), the mix source changes to Ext1, and the function doesnt work until the mix is manually changed to Pot3.

2. on my RDT LUA, im reading the red slider source value and displaying it graphically on the screen, this works great on X20S and does not work with X20S Pro (slider does not move on graphical display).
Here is how i read the red slider:
Analog6 = system.getSource({category=CATEGORY_ANALOG, member=6, options=0}) -- red slider
Analogvalue6 = Analog6:value()

im sure both issues are related to something in the red slider source name / mapping being different from X20S to X20S Pro.
is it possible that Analog 6 is now mapped to Ext1 (whatever that is) instead of Pot3 and this is whats causing the mix up??

The expected behaviour is: Anything related to the Red Slider will not change when transioning from X20S to X20S Pro.
thanks for looking.

**Comment by i3dm** [comment]
Looking at the ADC inspector i found the issue:
on X20S The red slider is analog 7 (in sw Analog6 since counting from 0)
on X20S Pro The red slider is analog 9 (in sw i guess Analog8 since counting from 0) and analog7 and 8 are saved for external.

@bsongis-frsky 
Wouldnt it make more sense to keep all analog numbering identical to X20S and then have the final 2 as spares for external? this will keep full backwards compatibility.

**Comment by bsongis-frsky** [comment]
A dedicated conversion is needed between all radios.
It still remains a TODO for X20PRO and it must be fixed for final 1.4.11

**Comment by bsongis-frsky** [comment]
POT3 won't change. The conversion will convert POT3 (X20S) to POT3 (X20PRO). Today I believe that POT3 (X20S) is converted to something else on X20PRO, perhaps EXT1 like you wrote in the first post above.

**Comment by i3dm** [comment]
the conversion is not the issue.
the issue is that Pot3 on X20S is analog 7 and on X20S Pro is analog 9.

so any mixer or LUA script that uses Pot3 (analog7) now goes to Analog 9 on X20S Pro.

if you change only the conversion - what about LUA analog reading? there will be no backwards compatibility.

**Comment by bsongis-frsky** [comment]
Switches / Analogs conversions implemented on X20PRO for final 1.4.11

**Comment by i3dm** [comment]
> This code is wrong if your script targets all boards in one shot
> 
> ```
> system.getSource({category=CATEGORY_ANALOG, member=6, options=0})
> ```
> 
> I suggest
> 
> ```
> system.getSource({category=CATEGORY_ANALOG, member=ANALOG_FIRST_SLIDER, options=0})
> ```

Thank you.
is ANALOG_FIRST_SLIDER the red slider in both X20S and X20S Pro?
