### ISSUE TITLE
Folder audio > en

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2828]
Hello,
Simulator 1.5.0 has the folder "en" in the sound folder. This folder contains the folders "gb" and "us".
If you want to generate announcements in English, this does not work because there are no .wav files in the folder "en", but two other folders. The folders "gb" and "us" have to be set as independent languages, which means that the folders "us" and "gb" have to be moved to the folder audio.
Thanks for the patience

Translated with www.DeepL.com/Translator (free version)

**Comment by bsongis-frsky** [comment]
You have to choose a voice (or multiple voices) in System / General. Voices concept has been introduced in 1.5.0

**Comment by Wolepo** [comment]
Thank you, I could not imagine Voice 1... nothing imagine.
