### ISSUE TITLE
New interface for device config

### ISSUE THREAD

**Issue by Nicholas-Luoyi** [FrSkyRC/ETHOS-Feedback-Community#2829]
Hello everyone, we are in the process of designing a new page to list all supported and configurable devices. Devices on this page will be categorized and specified down to the individual model. Some features that were previously implemented using LUA will also be incorporated into ETHOS this time. Additionally, devices will be accompanied by images to assist you identifying the specific model of your owned device (possibly only supported on larger screens). This page and all related features are still under development, and we welcome your feedback and suggestions.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/a5a4970e-56eb-4412-831e-820a02fb5340)

**Comment by dap35** [comment]
This looks like a great start.  If we could get rid of the page 1 / 2 screens for configuring the two sets of stabilized channels, and make it a check box on the first page, that would be much clearer.  Currently, it is far from obvious that you need to navigate to a second page to disable (or enable) the second set of channels.  Assuming that all 10 channels need to be stabilzed by default causes major problems on a plane with flaps.

**Comment by bsongis-frsky** [comment]
> Assuming that all 10 channels need to be stabilzed by default causes major problems on a plane with flaps.

Agree with that. It could be dangerous. We will push it to the RF team

**Comment by yak55** [comment]
Hi Bertrand, that's a good idea.
Improvement: Please do it the way "Jeti" does it in the device manager.
There the connected devices are displayed automatically.
An error by wrong selection is thus impossible.

Grüsse Eugen

**Comment by Nicholas-Luoyi** [comment]
I was planning to do such a feature. But we may need to make a choice here. For example FAS 40S, FAS 100S, FAS 150S share the same application ID. So ETHOS cannot tell which FAS is online accurately. Or we don't distinguish the models for one kind of sensor. Like we just put a FAS selection here.

**Comment by Nicholas-Luoyi** [comment]
I was planning to do such a feature. But we may need to make a choice here. For example FAS 40S, FAS 100S, FAS 150S share the same application ID. So ETHOS cannot tell which FAS is online accurately. Or we don't distinguish the models for one kind of sensor. Like we just put a FAS selection here.

**Comment by yak55** [comment]
Sorry, I have little experience with FrSky sensors.
Use here mostly third-party suppliers.

But if the receivers, Stabis and RB boxes are automatically detected, that is already very good.

Then of course automatically activate the correct scripts for the sticks, please.

With the other sensors I have to pass.

Greetings Eugen

**Comment by yak55** [comment]
Please then also enter a quick access to the black box.

Is cumbersome at the moment.

Greetings Eugen

**Comment by MiRe-CZ** [comment]
Such interface for management of all supported and configurable devices would be excellent. My only concern is related to maintaining of devices scope - if a new device emerges on market, it should not mean a new version of Ethos will be published. There should be some other way, e.g. only update of a list of supported devices with relevant information.

BR, Milan

**Comment by pstasek** [comment]
Great idea. I'd also suggest to allow a Lua script to populate this, in case when a new device pops up between Ethos versions. Today the temporary LUA scripts that are planned to exist in later versions populate a different menu, so it creates confusion with less tech-savvy users.

**Comment by mawzthefinn** [comment]
This is completed as of 1.6.0
