### ISSUE TITLE
Model Invalid data

### ISSUE THREAD

**Issue by yufasa** [FrSkyRC/ETHOS-Feedback-Community#2834]
This is purely a question and as I don't know where else to ask I am doing so here.
How do you handle the "Invalid data" error for models after updating to a newer nightly for testing?
This is going from one nightly, I did some testing before going on vacation in July, to a new nightly August 22. I have however seen this before and just rolled a new model to get over it. 

The thing is that my test model has become quite a bit complicated - hey you want to test as much as possible :)

Sorry if this is way out of line here...

**Comment by yufasa** [comment]
[models.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12423990/models.zip)
Here is the model file incase someone is interested

**Comment by bsongis-frsky** [comment]
I try to avoid this "Invalid Data", but I have changed my mind many times and sometimes I have reverted some commit, so perhaps your model is using code which has been removed in the meantime.

It's now more stable (Vars seem to work very well). At least I hope!
