### ISSUE TITLE
Ethos Suite hangs during updating to 1.4.11 installer

### ISSUE THREAD

**Issue by NilsRo** [FrSkyRC/ETHOS-Feedback-Community#2835]
My Ethos suite hangs during the update to 1.4.11 installer. Done a fresh install of 1.4.9 Suite and it directly asks to update. If I ignore the update dialog everything is fine. Updated my Twin Lite S via a firmware-file manually via Suite.

Using Windows 11.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51311453/526deb49-141a-4ec6-95d4-bd3bc4238f1a)

**Comment by Nicholas-Luoyi** [comment]
Sorry. Suite 1.4.11 hasn't been officially released. It will be fixed in the next release. (You may experience the fix when you update from 1.4.11 to 1.4.12)

**Comment by NilsRo** [comment]
It should not be rolled out if not finished...could bring in other problems as well if somebody using pre-release version without knowing...

**Comment by Nicholas-Luoyi** [comment]
I have noticed that and roll back the update detector. Thanks.
