### ISSUE TITLE
RB25s not working as expected

### ISSUE THREAD

**Issue by ftc2629** [FrSkyRC/ETHOS-Feedback-Community#2836]
Hi
I want to setup a RB25s. TX is X10s express, RX an Archer R8 pro with newest firmware.
The RB25s was flashed with the firmware from frsky-rc.com, Version 2023-07-05 | 20230509. 
I installed the 3 LUA-Scripts 2023-04-26 | v1.0 | First release.
I can find the LUA-Scripts in the system directory.
The LUA scripts are working. I can calibrate the RB25s (Manual is not really  informative!).What means Pins up?  The screw tabs?
Selftest is working too.
The stabilization is working, but I cannot assign channel 13 for gyro-gain and  I cannot assign channel 14 a switch to use quick mode with Off, stabilization, Autolevel.
I tried to use channel 9-16 for other functions, but all these channels do not react on input.
I makes no difference if I use Stab system 1 or 2 or both.
I my opinion something is not working properly with the RB25s firmware.

**Comment by Wolepo** [comment]
Bound the receiver with channel1 to 16?

**Comment by mawzthefinn** [comment]
The pin end is the end opposite the XT30 power connectors.

please attach your ETHOS model file

**Comment by ftc2629** [comment]
> The pin end is the end opposite the XT30 power connectors.
> 
> please attach your ETHOS model file

Here the model file.
[model06.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12429769/model06.pdf)
Please rename PDF to BIN.
