### ISSUE TITLE
VAR Range ignored (Nightly 23Aug23)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2839]
If I create a Var with a Range of 0% to 70% and for the initial value click on Max it gives that a value of 500%. This seems perverse when the Upper range limit is 70%. (Similarly for Min). I do note that the value used is as per the range, so even if 500% is assigned only 70% is used.

Surely when Max or Min is selected the value assigned should be the Current Range Upper or lower limits?
If the Range limits were honored then being able to quickly select that via Max or Min would be useful, currently they are usually going to be rather pointless if they are always going to be -500% or 500%
I'm not suggesting that you shouldn't be able to exceed the Range - although do slightly question it. 
(Edited to change Max and Min to Upper and lower limits to make clearer)

**Comment by Jedsters** [comment]
In the line under Range you have Values with a value of 0% with a burger icon. That value. But to be honest it's the same for any additional values I add too.

**Comment by Wolepo** [comment]
Although you can set 500% under [Values], the range is maintained under [Value].

**Comment by Jedsters** [comment]
As above, I recognise that the value used is correctly limited by the Range values, it seems to make no sense to have a range of e.g. 0% to 100% and for Max to set it to 500%. If the Max range is 100% surely Max should set it to 100% and if I later change Max Range to 200% and reclick Max then it should then set it to 200%. Surely Max should reflect the current 'valid' Max (and Min etc.) 
As above, why is clicking Max and getting 500% useful when in most cases the Max wanted will be nothing like that?

**Comment by Wolepo** [comment]
With regard to the mathematical functions multiply and divide it makes sense to allow this value input of 500%. I could even imagine that this value could be completely deactivated.
I think that the Vars are a powerful tool, the functionality of which probably needs a detailed description with corresponding examples.

**Comment by Jedsters** [comment]
Indeed, I have no real concern with 500% being allowed, although if it is limited to a lower value of e.g. 100% by the range then setting it to 500% via Max seems odd. 

Totally agree that a detailed description would be really useful.

For now a lot of my playing has been using VARs to set Expo, Weights of control surfaces or mixes (e.g. aileron to rudder) etc. hence so far tending to be in the 0% to around 100% range.

For some reason multiplying and dividing make me nervous, I'd rather see them as percentages - but that's probably just me and I can't exactly explain why either - although the prospect of accidentally dividing by 0 isn't ideal. Also dividing is non-linear, i.e. 100/1 = 100, 100/2=50, 100/3=33.3 each time you increase the divisor it has less effect. I guess you could argue 1% to 2% is a doubling while 2% to 3% is only 50% increase, but at least it is only the same increase in real terms? 
I'm not saying multiply and divide shouldn't be done, but I can't currently imagine I'll use it. Each to their own on that. It just feels like there be dragons there...
