### ISSUE TITLE
Logs feature enhancements

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#284]
- [x] Add an icon in the top bar when the radio is writing logs
- [x] Add a simple Logs viewer
- [x] Add a simple way to clean all files from the Logs folder (a contextual menu only in this folder?)

**Comment by franz4949** [comment]
Assuming that log is shown as X-Y-graph. Please make selectable 
 - which data is shown from the log and
 - the time-frame for X-axis scale, so that a time-section can be picked.

**Comment by pstasek** [comment]
A nice Log viewer LUA script for OpenTX is here: https://github.com/RealTadango/FrSky/tree/master/OpenTX/LView

Maybe that can be used as an inspiration for functionality.  💡

**Comment by Nicholas-Luoyi** [comment]
![IMG_8866](https://user-images.githubusercontent.com/58321103/124528406-af924400-de3a-11eb-9094-0780d5141dd7.PNG)

**Comment by federicobelfi** [comment]
> There may be more cosmetics in the future.
> 
> ![IMG_8866](https://user-images.githubusercontent.com/58321103/124528406-af924400-de3a-11eb-9094-0780d5141dd7.PNG)

Please, tell me how this can be done.

**Comment by loetefix** [comment]
Its not available yet.

**Comment by Hobby4life** [comment]
Would be nice to have this as a live viewer too, not only to view logs afterwards.

**Comment by pld74** [comment]
Any update to this? ETA?

**Comment by Peschi90** [comment]
I also want to know when this will be available? :)

**Comment by Hobby4life** [comment]
> I also want to know when this will be available? :)

it is available in [v1.0.11 RC2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release%2F1.0.11-candidate2)

**Comment by STC148** [comment]
is there anything new about the log viewer release? 🙈❤

**Comment by Peschi90** [comment]
I hope it comes as fast as possible :)

**Comment by Peschi90** [comment]
Hi, what about the logviewer function?  Is it inplemented yet? It would ve really nice for sailplanes.

**Comment by loetefix** [comment]
Any news on that? One year after showing first picture of the log viewer and still not ready? Seriously 😳?

**Comment by Fernandolewandowski** [comment]
I look forward to being able to read my files and csv log on my x20s screen please make this update soon

**Comment by Fernandolewandowski** [comment]
![IMG-20220806-WA0007](https://user-images.githubusercontent.com/108271349/183249286-e64ebf2c-21c9-431e-9901-c6f553398383.jpg)
Um exemplo a ser seguido que tal

**Comment by Fernandolewandowski** [comment]
![Uploading IMG-20220806-WA0006.jpg…]()

**Comment by Fernandolewandowski** [comment]
![IMG-20220806-WA0006](https://user-images.githubusercontent.com/108271349/183249383-f3462c00-6fcb-4f63-9b1a-71de5ec5cfd0.jpg)

**Comment by STC148** [comment]
any news?

**Comment by loetefix** [comment]
For me one of the most important Features.

**Comment by mawzthefinn** [comment]
Log viewer will be in the Feb 16th 2023 nightly for 1.5.0

**Comment by Peschi90** [comment]
> Log viewer will be in the Feb 16th 2023 nightly for 1.5.0

I love you Dude! Best news of today! 👍😁

**Comment by mawzthefinn** [comment]
Thank @bsongis-frsky - He did all the work, I'm just delivering the good news.

**Comment by Peschi90** [comment]
> Thank @bsongis-frsky - He did all the work, I'm just delivering the good news.

As the saying goes, the messenger is always killed first, so why not praise him?  😅

Thanks a lot that we See progress to this Feature @bsongis-frsky

**Comment by bsongis-frsky** [comment]
The logs viewer is pushed to the nightlies

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/219582298-3b0f3e3f-30ea-4ae8-9c40-cf84f2223da0.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/219582514-e956e366-52f0-4284-a7a1-7082ceda51ab.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/219582590-5bc39cd4-8e2b-42bd-b008-9de0aca64160.png)

**Comment by Peschi90** [comment]
Thanks it is looking awesome.

**Comment by STC148** [comment]
Great!  I've been waiting for this feature for a long time, thanks for that.
But there are 2 things I noticed:
-The first 3 parameters are always shown automatically, I would prefer to start with a blank graphic.
-It would be very helpful if the zooming in would take place at the point of the cursor.

**Comment by bsongis-frsky** [comment]
The screen with only a "+" button is not very nice. I will change it so that only the RSSI curve is displayed by default

**Comment by bsongis-frsky** [comment]
The Zoom will center the screen around the cursor.
Those 2 changes will be included in the next nightlies

**Comment by Peteb43** [comment]
hi is this released yet and if so how do i enable it on my x18? thanks in advance

**Comment by Peschi90** [comment]
> hi is this released yet and if so how do i enable it on my x18? thanks in advance

As you can read above, its part of release 1.5.0

**Comment by Peteb43** [comment]
th

> > hi is this released yet and if so how do i enable it on my x18? thanks in advance
> 
> As you can read above, its part of release 1.5.0

thank you for the reply i missed that

**Comment by agibson2** [comment]
It would be great if you could set what the default should be when bringing up the log viewer (yea... give a little and they just want more :) ).  You can never satisfy these people! ;)

**Comment by robertoalmeida** [comment]
When will the version with logviewer be released?

**Comment by loetefix** [comment]
It would be great if we could move the cursorline by pressing the DISP button and rotate the scrollwheel.
