### ISSUE TITLE
Values initially assigned to VAR range aren't the default (Nightly 23Aug23) 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2840]
If I create a new VAR and then select the lower range value (-100%) I can select Min, Default or Max. If I select Default that changes the value to 0%. If I select the higher (100%) range and select Default then a value of 0.1% is assigned. 
I'm guessing that Min, and Max are always -500%, 500% and Default is 0%, but question whether defaults of 0% for the Min, 100% for the Max may be more appropriate?

**Comment by mawzthefinn** [comment]
Default is the default value for the function you are editing, not the field you are editing. 

This is consistent across ETHOS.

**Comment by Jedsters** [comment]
As of 1.5 RC0 Default seems to have been removed as an option.
Selecting Values field and Min or Max seems to work as expected.
Closing.

**Comment by bsongis-frsky** [comment]
This issue is fixed now, right?

**Comment by Jedsters** [comment]
Thought I'd closed on 27Dec.I must have hit comment instead.
Apologies.
Closing!
