### ISSUE TITLE
SF: Turn off screen

### ISSUE THREAD

**Issue by rFlightFPV** [FrSkyRC/ETHOS-Feedback-Community#2844]
When flying in the dusk or in the dark the glow of the screen on the X20S is irritating. It would be great if the brightness setting of the screen could be adjusted via special functions, including turning the screen off. Many thanks.

**Comment by Wolepo** [comment]
The brightness can be set under [Genaral] with an encoder.
![Helligkeit](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/f02f5593-d787-43df-a19d-db88d8b0eb1a)

**Comment by rFlightFPV** [comment]
Unfortunately this is global and I do not want to turn off the screen for my daytime models or adjust the brightness with the pot when switching between night and day. I'd like to turn on/off the screen for my night flying models with my arm switch, independently from the sleep mode brightness.

**Comment by mawzthefinn** [comment]
You can assign to a Channel (mixer channels, not outputs), and control that channel independently any way you like in each model. It does not require assignment to any specific physical control.

If you assign to say Ch32, then setup a VAR mix on each model for that channel, which can be setup as desired for that model (VAR's can provide fixed values and/or a selectable source)

**Comment by rFlightFPV** [comment]
@mawzthefinn I'm still not quite there, I can't get the screen to go dark immediately. I've assigned a channel to "Brightness" and used the VAR mix as described. It works, but the screen does not got out completely, it waits for the sleep mode to engage. So I've in addition assigned the channel to the "Sleep Mode Brightness", the screen still does not directly go out via VAR mix, it waits for the sleep timer to run down as well. Assigning the channel only to "Sleep Mode Brightness" does - as expected - also wait for the sleep timer. I do not want to set the sleep timer to a few seconds. Unless I am missing something the screen cannot be switched off immediately which is something that should be possible imo. Adding "screen off" to the brightness slider is probably not a good idea, but how about turning the screen off if the assigned channel/VAR mix provides a value less than -100 to "Brightness"?
