### ISSUE TITLE
Request: Allow Flaps mixer to have elevator as an output channel

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2846]
Currently the Flaps mixer only appears to allow as many output channels as you have Ail and Flaps.
By contrast the Camber mixer allows you more so that you can include e.g. output to the Elevator with a weight taken e.g. from the Thr trim for elevator compensation. 
It would be useful if the Flaps mixer also permitted output to the elevator channels to also allow for elevator compensation.
Of course I can use the Camber mixer, however then I miss out on the Slow up and slow down options.
If this was done, whether there continues to be a need for the Camber mixer is another question as it would then behave the same as the flaps mixer with zero values for slow up and down (I assume).
Unless I'm missing the distinction between Flaps and Camber?
Thanks

**Comment by mawzthefinn** [comment]
The flaps to elevator mixer exists for this reason. Use a flaps channel as a source to get elevator to track flaps speed settings.

**Comment by mawzthefinn** [comment]
Closing as the requested functionality is already present as the Flaps to Elevator mixer
