### ISSUE TITLE
Ethos suite 1.4.9 crash on model manager  backup 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2847]
Ethos suite 1.4.9 crash on model manager  backup trying to backup X12S on 1.4.11 and windows 10 PC

![Untitled](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/24ba9baf-6ba6-40a5-9076-b0b9f7575aba)

[crash-logs.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12444946/crash-logs.zip)

**Comment by Nicholas-Luoyi** [comment]
Does is happen on your clicking the backup button? Or on your entering the Model Manager page?

**Comment by Nicholas-Luoyi** [comment]
Does is happen on your clicking the backup button? Or on your entering the Model Manager page?

**Comment by yak-54** [comment]
Hi Nicholas 
its on entering Model Manager page

**Comment by Nicholas-Luoyi** [comment]
Have you even renamed the file of the backup zip?

**Comment by Nicholas-Luoyi** [comment]
Never mind. It will be fixed when Suite 1.4.11 is released.

**Comment by yak-54** [comment]
> 

no

**Comment by yak-54** [comment]
> Have you even renamed the file of the backup zip?

No
