### ISSUE TITLE
Neuron II 80A ESC Cant Disable Brake

### ISSUE THREAD

**Issue by LaserAV-Calgary** [FrSkyRC/ETHOS-Feedback-Community#2849]
FrSky Neuron II 80A ESC.

*****There is NO way to turn off the brake!*****

I am running the latest firmware.
Telemetry and setting from X20S work.
Missing option to turn off the brake.

**Comment by mawzthefinn** [comment]
This is a Neuron2 firmware limitation, not an ETHOS bug. 

Still needs to be addressed

**Comment by mirko91** [comment]
Could this be fixed? I need to use the esc without the brake

**Comment by mirko91** [comment]
Any news on firmware update?
