### ISSUE TITLE
TD-SR12 Stabilizer and Advance mode dont work

### ISSUE THREAD

**Issue by LaserAV-Calgary** [FrSkyRC/ETHOS-Feedback-Community#2850]
There appears to be NO software to program advanced mode. Where is it?
I bought the USB adapter and 2 TD-SR12s.
They don't even work properly in basic mode (with 2 aileron servos)!
The FC is completely broken software and does not work.

When will FrSky fix this?

**Comment by mawzthefinn** [comment]
The Advanced mode software is still under development.

What issue are you having with Basic Mode? It's working fine for me on TD SR12, RB35S and Archer Plus SR10+
