### ISSUE TITLE
Play audio sequence doesn't always work correctly Nightly 23rdAug

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2852]
I've created a SF to Play audio, Enabled, upon an active condition. 
The sequence is a file followed by a value. 
When the active condition is triggered the file is played but the value is ignored.
If I move the value above the file then the value and file are played as expected.
(The value played is however incorrect playing as e.g. 700% instead of 70%, but I seem to recall seeing that someone has already reported that problem.)
Edit: more details below.

**Comment by Wolepo** [comment]
Yes, in[ #2843](url)

**Comment by Wolepo** [comment]
Yes, in #2843

**Comment by Jedsters** [comment]
My active condition was the SJ button and I've just noticed that if I briefly press SJ then I get the problem as above, however if I press and hold the SJ button then both values are played as expected. After playing around a bit it appears the above value is only played if the active condition is still active after the file has been played. e.g. if the file takes 1sec to play then the active condition needs to remain active for more than 1sec.

**Comment by Wolepo** [comment]
Yes and no, I have specified a time of 0.1s for triggering the announcements with a logical switch (LS). If a text was programmed first and then a value, only the text is announced. If the value is first and then the text, they are both announced in sequence. If I now set a pulse duration of 1.3s (the exact value can be shorter or longer) in the LS, both variants work.
In connection with this, however, I have another suggestion: 
Until now, I have always had the name of the sensor (only 1X) and then its value announced at intervals. Unfortunately, this is not possible here, as the distance applies globally to this Var. It would be better if the time setting could be set individually for each sequence.
This could then look like this, for example:
![Sequenz](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/bd2d18a8-d3a2-4226-91d0-8eb68b0b14ce)

**Comment by Jedsters** [comment]
That sounds exactly like what I'm finding, if the Active condition ends before the first play is complete then the next sequence isn't played. You are right that durations can fix this, but some play files are very brief while others may be longer so it would mean finding the minimum duration for each play file and using at least that - very tedious, or using a delay of e.g. 2sec and accepting a delay between file and value for some sequences. 
I had also considered your suggestion but held off from requesting it, but I'll certainly support it! I'm doing exactly the same, playing a file to let me know which value it is (which I only need once per press thanks) and then playing the value more than once per press.  
Thanks!

**Comment by bsongis-frsky** [comment]
When the condition is False, the play function is stopped. It sounds to me normal.

**Comment by bsongis-frsky** [comment]
The decimals issue is something else, and it will be fixed in the next nightlies

**Comment by Jedsters** [comment]
> When the condition is False, the play function is stopped. It sounds to me normal.

That means that whether the second condition plays depends on how long it takes to play the first item in the sequence which makes no sense as we can't know how long it will take to play a file etc.. 
If the first condition plays very quickly (e.g. a quick beep) then the second condition plays but if the first condition plays a file which takes a couple of seconds then the second condition won't play.

Currently it appears that the entire sequence is not played depending on the active condition at the start but rather depending on the state of the active condition when the sequence makes it as far as each item in the sequence.

If that is the intention then I'd suggest we need a new action of play entire audio sequence which will play all sequences once an action becomes true, even if it is only very briefly true.

**Comment by Wolepo** [comment]
Nevertheless, I wonder why both sequences (first the value and second the .wav) are played even with a start time of 0.1s. Conversely, however, only the .wav. I have just tested it again.

**Comment by Wolepo** [comment]
The value is now correctly reproduced. Thank you for that.
Now I am still waiting to see if my suggestion above (post 4) can be implemented.
Because of the decimal places in the LS I will open a new issue later.

**Comment by mawzthefinn** [comment]
Set the minimum duration time on the logic switch which is triggering the sequence so the LSW stays active long enough to play the full sequence.

**Comment by Wolepo** [comment]
You can do that and it works. But why is the sequence value > sensor name played back completely with a short activation pulse, but vice versa only the name and no value? Only in this way does it make sense.

**Comment by Jedsters** [comment]
If we need to set a minimum duration on the logic switch then that creates a problem. Suppose I want to announce '5 seconds left' the first value is a countdown value and the second an audio file.  If I understand correctly, the proposal is that I set the trigger for as long as it takes to say '5 seconds'?  However the time may vary, suppose it is 15 seconds, or 25 seconds or 2 minutes and 57 seconds left or any other value - I'm expected to know how long it takes to say the longest possible value which could be said for every condition. Where is this information? This is an unviable proposal.

**Comment by Jedsters** [comment]
Correction, the problem occurs only when the first value is an audio file so my example above is wrong. However the problem still remains e.g. if I want to play 'Time left' followed by the countdown timer which is triggered by SH down, the proposal is I'd need to hold SH down for long enough to say 'Time left'. There are no doubt many other triggers which similarly can't be controlled, e.g. RSSI < 50, I may want 'RSSI' followed by the value, but the RSSI would need to be below 50 continuously for as long as it takes to play RSSI. Maybe not the best example, but it explains the problem.
Thanks

**Comment by Jedsters** [comment]
Hmm, let's try again, I think the active condition of 'RSSI low' is what I was meaning, it would require the RSSI to be low for as long as it takes to say 'RSSI'.

**Comment by Wolepo** [comment]
Consequently, one must test how long the total duration of the message lasts. This must then be determined for each individual message. This works, but it is tedious to test everything. If you want to receive a message every 10 seconds, for example, you have to activate it permanently anyway.
At the moment I just don't understand why a short activation impulse plays the sequence Value > Track completely, but Track > Value only brings the track and ignores the value.

**Comment by Jedsters** [comment]
I agree Wolepo however if the active condition is e.g. RSSI low we can't know how long that will last as it will vary so we can't know if it will last long enough to play the audio file. In order to use that we'd have to create a LS for RSSI low with a minimum duration, despite the option of having RSSI low as a direct active condition.

**Comment by Jedsters** [comment]
Surely the sensible option here is to add another Action of Check Trigger so for those who don't want the entire sequence played they can control how much is played, otherwise the entire sequence is played?

**Comment by bsongis-frsky** [comment]
I will keep only "Play File" and "Play Value" as parts of "Play Sequence". It will allow to play all the parts in the same shot.

**Comment by Jedsters** [comment]
I believe this has been fixed now that we have Play Audio with multiple lines. Thanks!
