### ISSUE TITLE
X10 trim per flight mode is missing on v1.4.11

### ISSUE THREAD

**Issue by besser** [FrSkyRC/ETHOS-Feedback-Community#2853]
The dropdown menu which shows the values per FM is missing on X10 model. It is present in another models.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/890037/24b66258-65ec-4371-bea7-577a5f729256)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/890037/2c5e9701-760d-4f0c-a580-8ada7c9d07ee)

**Comment by Wolepo** [comment]
With the X10 Express, the trim has never been present.

**Comment by besser** [comment]
And why not include this in X10?

**Comment by bsongis-frsky** [comment]
Because I was too lazy to handle the scroll correctly!

**Comment by bsongis-frsky** [comment]
Now libopenui deals with the scroll very nicely, I may add the trims without further work. Will be there in 1.4.12

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5bf3f33c-7bd5-4a34-9933-852cac27e1b5)

**Comment by besser** [comment]
Thanks!!
