### ISSUE TITLE
LS Value remains in bold when it shouldn't be. Nightly 23rdAug23 and 1.5.0 Simulator 26Aug23

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2855]
Consider the following setup

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/b51d5e61-aa26-4c84-9fd1-d4bcc11b477a)

it can be seen that Invert Edge SA Up and Invert Edge SA Down are both displayed in bold and yet the LS36 is (correctly) displayed in red showing that none of the OR conditions are actually true.
Obviously as SA is variously changed between Up and Down the Values in bold change, but at least one always seems to remain in bold long after the Edge condition has finished being true. 
Note: I haven't tweaked any durations to force the LS to false. 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/424614bf-6f60-4a55-9cb3-3aadabd1eff8)

**Comment by Wolepo** [comment]
Yes, I noticed that too. You could interpret it to mean that the source is active. But since the Edge option is switched on, the source should not be marked bold. 
Suggestion: for better observation, the display could change **from** bold to normal after a certain time.

**Comment by Jedsters** [comment]
It certainly has potential to cause confusion, e.g. trying to work out why a LS is unexpectedly true and seeing that some of the values are bold - you don't know which is the potential cause. 
It needs to be on for more than one cycle otherwise we wouldn't be able to see if it was ever coming true, but leaving it on for a length of time is also not ideal. I often mark my LS which are only briefly going to be true to have a min duration of 0.2s which I find quick enough for my purposes but slow enough to be able to see. Something in the 0.1 to 0.3s range seems reasonable to me.

**Comment by Wolepo** [comment]
You can only tell by the bold font. It also irritated me at first.
