### ISSUE TITLE
SF Play audio missing strength and pattern for haptic Nightly 23rdAug23

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2857]
When adding a sequence to the play audio SF there is no way to specify strength or pattern for the haptic as is currently the case. 

Currently (this is 1.4.6 simulator but I'm assuming it to still be valid) we have 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/5b06d168-8012-4362-8033-4c4f0be5ff07)

while with 1.5.0 nightly which introduces sequences we have 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/766825bc-968c-49e6-bff8-e22d63483532)

**Comment by bsongis-frsky** [comment]
The Haptic special function is still there!

**Comment by Jedsters** [comment]
What am I missing? Looking at that second screen grab the only choice is to enable haptic or not. How do choose which pattern and strength you want for that sequence? 
I was assuming the sequence would have something like the first screen grab.
