### ISSUE TITLE
Feature Request :  BlueTooth file transfer

### ISSUE THREAD

**Issue by dap35** [FrSkyRC/ETHOS-Feedback-Community#2858]
It would be really helpful to be able to xfer files to/from the transmitter so we can download telemetry files or upload firmware/images without requiring a USB connected laptop.  Especially when we are at the field.

**Comment by strgaltdel** [comment]
addressed in 1.5

https://www.rcgroups.com/forums/showpost.php?p=51138779&postcount=24833

**Comment by Luznatural** [comment]
Are you able to transmit model files between radios in 1.5?

**Comment by mawzthefinn** [comment]
> Are you able to transmit model files between radios in 1.5?

Yes, you are

**Comment by arshish1612** [comment]
Does this also copy Global Spl functions? How would I get those across from one radio to another? X20S -> X18SE

**Comment by Luznatural** [comment]
P,léase, do not close it until the release of 1.5.
Thanks in advance

**Comment by bsongis-frsky** [comment]
Done in 1.5.0 and available in RC0 and RC1 already
