### ISSUE TITLE
Cloned Curve has no name Nightly 23rdAug23

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2859]
When I clone a curve the resultant curve has no name. Is this intentional for some reason?
I can understand that you don't want 2 curves with the same name, but there would seem to be better ways around that (e.g. change the last char or similar).
It's just mildly annoying when cloning e.g. R Aileron to L Aileron to have to reenter the name when only the first char really needs changing.
Hardly the end of the world, but in case this wasn't done deliberately...

**Comment by bsongis-frsky** [comment]
It will have the same name in tomorrow nightlies
