### ISSUE TITLE
Rotary not working counter-clockwise "Left"

### ISSUE THREAD

**Issue by ZeekWorld** [FrSkyRC/ETHOS-Feedback-Community#2860]
Hello, I noticed I can't go left on any menu with the rotary spinning it counter clockwise. Clockwise works just fine and when counter-clockwise, the selection continue to move clockwise or "Right", never left.
Tried everything, no go.
I am on latest Firmware Version: 1.4.11 FCC
Bootloader Version: 1.4.3

Appreciate any help, thanks!

**Comment by mawzthefinn** [comment]
Just checked on one of my radios running 1.4.11 FCC and left is working fine. That's an X18. Which radio do you have?

Does it work if you downgrade back to 1.4.9? This sounds more like a possible hardware issue.

**Comment by ZeekWorld** [comment]
X20S
Downgraded to 1.4.7, same issue.

**Comment by mawzthefinn** [comment]
Then it's likely a physical issue with the encoder.

**Comment by ZeekWorld** [comment]
Strange, It's fairly new, I am still trying to wrap my head around the encoder moving in one direction only... It has to be a software issue IMO.

**Comment by bsongis-frsky** [comment]
why do you say it's a software issue?

**Comment by ZeekWorld** [comment]
Thanks, makes sense, the reason I first thought it was a SW issue it's because I literally had the Radio in the case for the past year and the only thing I did was bootloader and FW upgrades, I did not use it at all.
I am going to open it up and check the physical encoder.

**Comment by ZeekWorld** [comment]
Reporting back, the issue was the x20s motherboard which includes the rotary encoder.
Ordered a new motherboard, replaced it and issue resolved.
Thank you all for the help.
