### ISSUE TITLE
Javascript error with ETHOS Suite 1.4.11

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#2861]
Since updating to ETHOS Suite 1.4.11. I get the following error when opening ETHOS Suite.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17590174/5437c881-d754-45d0-a45d-308dc16e47be)

ETHOS tab only reports the current firmware and bootloader versions (no images, sounds).
Model manager shows no models and I can't perform a backup.

I've not risked attempting an update.

This is on Windows 11. ETHOS Suite performed the update.

**Comment by Nicholas-Luoyi** [comment]
Every time you open Suite. The error will be raised up?

**Comment by bbuttonlint** [comment]
I get exact same error every time I launch 1.4.11 (Window 11 as well).
