### ISSUE TITLE
Min and Max in Wars reversed. (V1.5.0)

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2865]
Hello,
If I want to use min or max to set a value in the V
ars, the wrong values are entered. Instead of +100% for max, -100% is entered and for -100% +100% is entered. This is not a big deal, but it should be changed.
![min_max](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/6793ed26-c56d-4696-9ca9-405acdbb9952)
Result:
![max](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/398245f3-c12d-4d8c-8e5f-71d334c66720)

**Comment by mawzthefinn** [comment]
Corrected in current nightly
