### ISSUE TITLE
Copy Trims to Output subtrim #368 - Long press option has no visual cue

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2866]
Copy Trims to Output subtrim #368

Hello Bertrand, you wrote that this function was implemented 14 days ago.

I just can't find it - what am I doing wrong?
Where do I have to look?

Thanks greetings Eugen

**Comment by MIKE-DAILEY** [comment]
Info here https://www.rcgroups.com/forums/showpost.php?p=51378337&postcount=25321

Mike

**Comment by yak55** [comment]
Hello, thank you for the answer.
I know this post, but can not find it in the simulator for the Tandem XE.

Under Outputs it is not present.
Is it because of the simulator?

I can't find it.

Greetings Eugen

**Comment by yak55** [comment]
Hello Jetflyer, I didn’t give up.
Now I have found it.
Pressing enter long opens menu.
Would be good to have a reference to that.
Icon in display output would be good, so just like switches, that there is another option.
So it is not logically.

greetings 
Eugen

**Comment by mawzthefinn** [comment]
Would update this to 'Subtim value box needs long-press icon added'

**Comment by yak55** [comment]
Yes, that`s a good idea.
greetings
Eugen

**Comment by bsongis-frsky** [comment]
Fixed in 1.5.0 RC3 now
