### ISSUE TITLE
Feature request: Add Lua for AS3X programming with Multi Module

### ISSUE THREAD

**Issue by J-charles-C** [FrSkyRC/ETHOS-Feedback-Community#2868]
I,

On GitHub of [pascallanger]/[DIY-Multiprotocol-TX-Module](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module), you have some Lua for Open-Tx.

One of them is for program the DSM receiver with AS3X and control gain.

The developer does not have a radio with ETHOS. Could one of you transpose, under ETHOS, these LUAs?

There are some for other brands of receivers as well

thanks

**Comment by mawzthefinn** [comment]
The ETHOS Lua API is published, a community developer would need to pick this up and proceed with it.
