### ISSUE TITLE
Timer with throttle % control / throttle lock

### ISSUE THREAD

**Issue by IJK-CZ** [FrSkyRC/ETHOS-Feedback-Community#287]
If the timer is controlled by throttle %, it ignore throttle lock. The % value should be controlled by real % output on throttle assigned chanel output, not only gimbal position. The lock (and any possible mixer, which modify throttle output) has real impact to throttle output, and should have the same impact to timer.
The Thr% timer is often used for a simple battery capacity control (in case of no voltage / capacity telemetry) and the % setting reflects less battery usage, when power is limited. With active throttle lock, no power is consumed, so the timer should keep value (be stopped) regardless of throttle control (gimbal, switch etc) position.

**Comment by centertrim** [comment]
Repeat of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/98
