### ISSUE TITLE
X12s Locking up in model category selection

### ISSUE THREAD

**Issue by Lefish63** [FrSkyRC/ETHOS-Feedback-Community#2870]
Been creating model catagories and have noticed if I long press the down button in an empty category on the plus symbol it gives me the options
When I long press the down button on a category that has a model already in it, it only gives me the options if the highlighter is on a pre existing model, if the highlighter is on the plus symbol in a category with models already in it and I long press the down button it totally locks up the radio and I have to take the back off and disconnect the battery.
I've confirmed this several times.
Has anybody else noticed this ?
Dave

**Comment by bsongis-frsky** [comment]
Reproduced on simulator of X18

**Comment by Lefish63** [comment]
Thank you.
