### ISSUE TITLE
X18S Simulator model does not show

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2871]
Normally I was able to dump my models in the X18 Transmitter (1.4.11 FCC) into the Simulator's models folder and I was able to see the model in the simulator screen. Now, for some reason I can not have the Simulator to show me the model to be selected. I tried with other models and still was not able to see any of them. I think the problem started when I updated the Simulator to 1.4.11. Any idea besides un-installing the sim and go back to a previous version?
![Active folder](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/1ea9ec77-d686-4aa9-a5df-0bdbf76cf539)
![Simulator](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/e3872426-746c-488c-8577-4b0cfa99740b)

**Comment by Richrfl** [comment]
Sure, here are two of them
[dhc-6 new.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12541225/dhc-6.new.zip)

**Comment by bsongis-frsky** [comment]
PC-21 JIM seems OK
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/757e9fb4-745a-4c23-989f-67edba620b92)

**Comment by bsongis-frsky** [comment]
It seems to me that for DHC-6 you are missing some Lua scripts

**Comment by bsongis-frsky** [comment]
The problem comes from the missing Lua script for sources used in your model (Y_ROLL and Y_PTCH)
But 1.4.12 will bring a fix. The sources won't be loaded (because it is not possible), but the rest of the model will be read correctly.

**Comment by Richrfl** [comment]
Got it. I guess you are making reference to LUAs that I am using as model-specific to present text in one of the model screens. They are working on models that I had from the previous version of the sim. This is just FYI. I am not trying to be a smart "one".
![LUA](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/bc472713-3c40-4668-9511-df7c55562ad2)

**Comment by bsongis-frsky** [comment]
If you remove the use of those sources in Model / Edit, your model should be opened correctly in simulator. And in 1.4.12 it will be always opened correctly.
