### ISSUE TITLE
gas channel mixing disturbed by a curve

### ISSUE THREAD

**Issue by mipel85** [FrSkyRC/ETHOS-Feedback-Community#2873]
Yesterday, I upgraded to version 1.4.11 on my X20S and today I noticed an uncontrollable movement of the throttle channel servo on my extra 300 thermal.
In the middle of the stick travel, the servo wriggles continuously and varies the engine speed. The servo is stable when the stick is down and up but not in between.
For several months, I have been using a personalized 5-point curve to control the gas mixing and this is the first time that this anomaly has occurred.
I haven't noticed anything abnormal on the other channels which only use an "Expo" type curve.
I replaced the servo but the new one reacts the same way.
So I then removed the curve on the mix and the servo started working normally then I put the curve back and everything seems to be normal now.
Is the consideration of a custom curve in a mixer affected by this latest version?
Michael

**Comment by bsongis-frsky** [comment]
It should not. Do you have kept a copy of your model file? Do you remember if the Gaz channel output was always moving also on screen?

**Comment by mipel85** [comment]
Hello,
At the time, I thought it was coming from the engine adjustment but then I noticed the very visible movement on the throttle servo, in the form of an increase then a decrease without thinking of looking on the screen on the output channel .
I'm attaching my latest backup for all of my models if that helps.
I would do a test tomorrow with the same configuration and I will add a comment if necessary.

[ETHOS_05-09-2023,_10-18-35.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12551895/ETHOS_05-09-2023._10-18-35.zip)

**Comment by bsongis-frsky** [comment]
Excellent, thanks for your help on this investigation!

**Comment by bsongis-frsky** [comment]
I see no mistake on your model file, the Throttle seems OK

**Comment by mipel85** [comment]
yes, perhaps a problem due to poor adjustment of my engine. Yesterday, everything seemed ok but I need to test my other models so I'm keeping this issue open for the moment.
Thank you for all the work done on Ethos

**Comment by mipel85** [comment]
Hello,
In the end, I couldn't see anything more. I think it comes from the carburetor adjustment and so I close this issue.
