### ISSUE TITLE
Comments on issue  #2871

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2874]
Bert. I don't get it. The DHC-6 is fitted with an X8R receiver, therefore there are no Pitch or Roll parameters or LUA required to run that receiver.
For the PC-21, the receiver is an SP10 Pro, in which case there are Pitch and Roll data, However, for this one and all sensors (GPS, Vario, and AIrspeed) the LUAs seem to be there.
Please double-check as you may be missing something.
What I just noticed there are missing are the LUAs for the SP10 Plus, which I have in another model.
Thanks a lot.

**Comment by bsongis-frsky** [comment]
Please continue the discussion in #2871!

**Comment by Richrfl** [comment]
Sorry, I opened a new issue given that you closed #2871
