### ISSUE TITLE
How to with an R8 Plus receiver, Use S.port sensor and Xact servo telemetry at the same time?

### ISSUE THREAD

**Issue by horifaydo1981** [FrSkyRC/ETHOS-Feedback-Community#2875]
How to with an R8 Plus receiver,
Use S.port sensor and Xact servo telemetry at the same time?

I have an ESC that provides telemetry data with an S.port sensor, and I have several Xact servos for which I would also like to see the servo telemetry data.

**Comment by mawzthefinn** [comment]
Set one channel port to S.Port for the sensor. Set the servo ports to FBus for the XACT servos.

**Comment by horifaydo81** [comment]
it is not possible to set this, even though the R8 plus receiver has the latest firmware.  (and also on the X20S transmitter 1.4.11.)

**Comment by mawzthefinn** [comment]
Interesting, I was not aware the R8 Plus was setup that way. I'd suggest using an R10+ instead then, as it can have the channel ports assigned to S.Port or FBus independently.

**Comment by horifaydo81** [comment]
and I read somewhere that the "R8 pro" is not, but the R8 plus will already be able to set FBUS or S. port for its PINs.  like the R10 pro receiver.

**Comment by mawzthefinn** [comment]
That was my understanding as well, but from checking the manual, it doesn't appear to be the case. NB - The R10+ is the direct replacement for the R8 Pro (same footprint)

**Comment by horifaydo81** [comment]
this can really be true...
thanks...

**Comment by mawzthefinn** [comment]
After digging in on this, the only way to achieve what you want is to use a S2FPORT 2.0 adapter to convert S.Port and SBus Out from the receiver to FBus for the servos.

https://www.frsky-rc.com/product/s2f-port-2-0/

Then y-cable the S.Port sensor into the chain. 

F.Port 2.0 is the original name for FBus.

**Comment by mawzthefinn** [comment]
Closing this off, as the receiver in question lacks the capability to output both S.Port and Fbus at the same time.
