### ISSUE TITLE
Show timer script lua

### ISSUE THREAD

**Issue by robertoalmeida** [FrSkyRC/ETHOS-Feedback-Community#2879]
How to show timer by lua script in mask hh:mm:ss?

I tried using the code:

```
timer = system.getSource({category=CATEGORY_TIMER, member=0, options=0})
lcd.drawText(320,40,timer:value())
```

but only show timer in seconds.

![timer1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4574415/a791d0a2-fc97-43f0-8896-425587e70a42)
![timer2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4574415/dd5d88af-52b5-492f-9840-ef6fb2f97d09)

**Comment by strgaltdel** [comment]
i call this function to convert / format the timer val into a string:

`
local function timer2strg(val)
&emsp; local hour 		= math.floor(val/3600)	
&emsp; local minute 	= math.floor((val -hour * 3600)/60)
&emsp; local second	= val-hour * 3600 - minute * 60	
&emsp; local timerStrg  = string.format("%02d:%02d:%02d",hour,minute,second)				-- format decimals

&emsp; return timerStrg
end

`
