### ISSUE TITLE
Change models from model bitmap

### ISSUE THREAD

**Issue by yufasa** [FrSkyRC/ETHOS-Feedback-Community#2880]
Feature request:
I would like to be able to tap the bitmap of the current active model (surely we all have that on first page :)).
Tapping on the bitmap would bring up a list of favorite models or the last 5 models flown so you can easily tap on that.
The standard “cannot switch while receiver active” obviously still apply but I think this will make it fast and easy to switch.

Fire away :)

**Comment by mawzthefinn** [comment]
It's just a widget, so sounds like an opportunity for a Lua developer.

**Comment by yufasa** [comment]
Sure it can be a widget other than the model bitmap...did not consider that. 
Still think it would be nice to have that as standard but a LUA widget can fill that gap in the meantime.
Time to learn LUA scripting
