### ISSUE TITLE
Haptic doesn't work for Play Audio (Nightly 9thSept23)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2881]
I have created a new Play Audio SF to play a value with haptic however while the value is played, the haptic doesn't work.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/778cf7e1-157e-42c1-ada3-85775d8b909e)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/3754f3f9-af6d-4145-955c-a8e611d55a44)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/89cd71eb-f32e-400b-a224-0e66c66ea64b)

Thanks

**Comment by bsongis-frsky** [comment]
This one should have been fixed in 1.5.0 nightlies now
