### ISSUE TITLE
Model bitmap file not found (Nightly 9Sep23)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2882]
In the configure screen menu, if I select the default left Bitmap widget, the widget is displayed as Bitmap, the bitmap is dislpayed as Model bitmap however the Bitmap file is unselectable. 

If I go to the File Manager, SD card, bitmaps, models I can see all my bitmaps and the image is displayed when selected.

I'm not sure if this is a bug or whether the location for the model bitmaps has moved with 1.5 and not been moved automatically due to this being nightly.

Thanks

**Comment by mawzthefinn** [comment]
User bitmaps are in the /bitmaps/user folder to differentiate from model bitmaps in /bitmaps/models

**Comment by Jedsters** [comment]
Thanks, moving all my model images from models to user works but please can you explain what, if anything, should be left in the models folder, or is this now redundant?
