### ISSUE TITLE
1.5.0 Model Invalid Data

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#2883]
Can not select Models which use ext. ELRS Module
(Switched (models from ACCESS to ELRS previous, cloned the originals - originals with internal Module ACCESS still working. All Models using ELRS, Model ID Match activated show Error msg if selected)
Uploaded model file but renamed bin to jpg
See pictures- Module Configgure Entry missing (norm. bellow Channel range)
![elrsxplorernanbin](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87205694/0bf18251-7e54-42bd-b886-a0167baa0040)
![PXL_20230910_052248576_copy_1228x1632](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87205694/27c3af3a-94d5-467b-99cc-0e3fbd85cf70)

![PXL_20230910_052446677_copy_1228x1632](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87205694/35a8b033-6333-4281-bdc6-55343a290b2c)

**Comment by m0p3d** [comment]
Like to add even new created models do not work if ELRS Module is selected and on - Configure Button also missing

**Comment by mawzthefinn** [comment]
Invalid Data may simply be an old model not converting correctly (this is a regular occurrence with Nightlies as they change the model format faster than conversion updates happen). 

With a new model setup for ELRS I am seeing no configuration script access.
