### ISSUE TITLE
X20 pro wont read hello and bye after  PC connection

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2884]
Hello,

X20 Pro, both 1.4.10 and 1.4.11 after i copy some files to internal memory via PC, on the next boot the radio will be silent and not play the "hello" or "bye" wav files.
after a restart it starts playing correctly.
Minor issue but a bit annoying.
this happend with only 1 factory installed test model memory, after copying some files over to "Radio" drive.

**Comment by Nicholas-Luoyi** [comment]
You mean this only happend once since you receive the X20 Pro

**Comment by i3dm** [comment]
no. every time i performed actions on the internal memory it happened afterwards.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Nicholas-Luoyi** [comment]
Would you please help to check something?
Adjust all the trim values to 0.
Try to reproduce the silent issue.
To check all trim values are 0 or not.
