### ISSUE TITLE
RTN button does not work on Outputs screen

### ISSUE THREAD

**Issue by yufasa** [FrSkyRC/ETHOS-Feedback-Community#2885]
Nightly Firmware from September 8.
Method to replicate:
1) From Model menu select outputs submenu
2) Try to use RTN button on left circular hard buttons
3) Nothing happens

**Comment by Wolepo** [comment]
I can confirm that this is also the case in the Sim.

**Comment by mawzthefinn** [comment]
Page is also not working in Outputs on Sept 14th build.
