### ISSUE TITLE
GPS Map Widget cursor highlights wrong text (Nightly 9Sep23)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2886]
In the GPS Map Widget, when editing the longitude and latitude if any of the degrees are 0-9 then the cursor highlights the wrong characters e.g. this is how I'd expect it to be

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/3b732d18-8af7-4e1e-bd54-0ff8a1f33377)

but if the degrees are reduced to a single character then the degree symbol also gets highlighted...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/98decf17-7fa5-49d9-a3b7-caee6ee5c81b)

this then throws out the highighting for the rest of the entry...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/f307b5df-2bd8-41ed-b572-1ef125ca8e9c)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/9b360918-aa96-4107-92a0-f8542c03d374)

It appears the cursor highlighting assume that the degrees will always have at least two characters. 

Maybe the simplest approach is to change single chars to be preceeded by a 0, i.e. 09 degrees etc.?

Thanks

**Comment by bsongis-frsky** [comment]
Then there will be the same problem with 180?

**Comment by Jedsters** [comment]
No, 180 appears to be correct.
I changed my initial post from always have 2 chars to be always have at least 2 chars after I thought about that and checked it.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/eead63b6-2fdc-476a-8541-48f0caa4d783)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/72440f80-abd0-46f4-89d9-2af54157efe0)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/58e68941-feb1-434f-80e5-bd6d7677caca)

**Comment by bsongis-frsky** [comment]
It will be fixed in 1.4.12

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5b3cfd8d-7784-4350-9b6b-2d3c589f69d3)
