### ISSUE TITLE
Compiling to LUA bytecode *.luac

### ISSUE THREAD

**Issue by JimB40** [FrSkyRC/ETHOS-Feedback-Community#2887]
Testing LUA efficiency on ETHOS and I wonder how to compile *.lua to *.luac bytecode.
@bsongis-frsky Bertrand is LUA compiler part of ETHOS FW?

**Comment by Benno00** [comment]
Moin, einfach ein leeres main.luac anlegen. beim nächsten start ist es gewandelt

**Comment by bsongis-frsky** [comment]
https://www.frsky-rc.com/wp-content/uploads/Downloads/EthosSuite/LuaDoc/index.html

**Comment by JimB40** [comment]
Thank you guys. 
Seems obvious but I will confitm. Since my app is using 50+ lua files loaded on demand during runtime, the only way is to create empty *.luac for every single one. Right?
Or there is LUA command to force compilation before executing?

**Comment by Benno00** [comment]
Hi Robert,
All you need to do is create 50 empty main.luacs and then start the simulator then all *.luacs are created

**Comment by Benno00** [comment]
Hello Bertrand,

 

how can I save files from a LUA script on the SD card or in the transmitter?

Unfortunately I didn't find anything about it

 

Greetings Benno

 

Mit freundlichem Gruss 

Benno Jurisch

 

Benno Jurisch
Siedlung 5, 27624 Geestland
Telefon: +49 (0) 4708 707
Mobil: +49 (0) 152 337 76 727
 ***@***.***> ***@***.***

 

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Dienstag, 12. September 2023 11:25
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Comment ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Compiling to LUA bytecode *.luac (Issue #2887)

 

Closed #2887 <https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2887>  as completed.
