### ISSUE TITLE
XES Simulator cannot Load model files since Rel 1.4.11

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2888]
Since 1.4.11 there is no way to load model files which are created on XE-Transmitter.
if i copy radio.bin from the transmitter to the simulator i get a message:
Storage error, default system settings restored Starting calibration ...
![Monosnap Ethos Simulator 2023-09-10 13 14 48 (1)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26022422/4c04114a-5f89-4787-9b13-e2191aff1c0f)

**Comment by Wolepo** [comment]
The sim,ulator has the FCC version. Is it possible that the models created with the EU version are not displayed?

**Comment by Storchy1** [comment]
All my models are EU Version. 
In 1.4.9 i never had a problem to load my EU models. 
Is there a EU Version of the simulator?

**Comment by Storchy1** [comment]
I download the 1.5.0 nightly XES-Simulator and there is no problem to load the model.bin files.
I think rheree was a little error in the 1.4.11 Sim.
Cloesd
