### ISSUE TITLE
Trims: Assignable trim switch channels (feature request)

### ISSUE THREAD

**Issue by rFlightFPV** [FrSkyRC/ETHOS-Feedback-Community#2889]
Hi,

Aircraft with nose wheel steering (NWS) use the rudder stick for directional control on ground. Usually pilots separate the rudder and nose wheel channels because one does not want rudder trim influencing nose wheel trim and vice versa. 

Therefore it would be great if one could freely assign the trim switches to a channel, per flight mode. Example: In a "gear down" flight mode rudder trim switch would be assigned to the NWS channel. As soon as the gear is retracted (flight mode change) the trim switch would change and be assigned to the rudder channel.

If I am not mistaken there is currently no way to assign the trim switches to a channel. I have (temporarily) solved the NWS trimming by adding a mixer using Pot2, but this is ugly as other aircraft use Pot2 for other things and trim will always be adjusted after flying a different model.

Thanks.

**Comment by mawzthefinn** [comment]
Trims are never assigned to a channel. That's contrary to how the input/mixer flow works in ETHOS.

They can be assigned to a mixer stack (via Free Mix or Trim Mix using them as an input) or used directly in one of the core surface mixes. 

With 1.5.0 you can leverage a VAR to do trim overrides, where you can steal a trimmer from a function when a specific condition is true. That would be able to use this function and a VAR as a mixer source to do what you want.

**Comment by bsongis-frsky** [comment]
Answer provided
