### ISSUE TITLE
GPS data logged 5 seconds late

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2890]
This issue was one already treated in the good old OpenTx. The GPS data rate is pretty much useless with the current delay of 5 seconds. Such a delay unless your model is a slow mover. Is there any way to have the GPS send back information to the transmitter closer to real-time?
Can these data delays be adjusted in this screen?
![GPS Config](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/144a26b8-6d79-42a3-99ff-94e9c64b4287)

**Comment by Quickfixforlife** [comment]
I was thinking the same thing, frsky GPS is just isn't good option. there are other gps options for your aircraft, meanwhile I measure top speed with it.

**Comment by Richrfl** [comment]
> I was thinking the same thing, Frsky's GPS just isn't a good option. there are other GPS options for your aircraft, meanwhile, I measure top speed with it.

I tend to agree with you about "other GPS options" I had this same problem back when I was using OpenTX, and ended up building an Arduino-driven GPS. However, this time I was not able to find the code to run that setup, as FrSky did some changes in the telemetry, and, for example, "GPSs with OpenTX version" do not work with the Ethos version. And all other sensors have to be updated to work in the Ethos environment. Anyway, I would appreciate that if you have a lead on compatible GPS, you could share that information.

**Comment by Quickfixforlife** [comment]
I don't have enough experience with that kind of stuff to be honest. there is a guy with a good knowledge about EDF jets on YouTube, and he's flying with frsky as well. he uses GPS logger 3.

**Comment by Richrfl** [comment]
> I don't have enough experience with that kind of stuff to be honest. there is a guy with good knowledge about EDF jets on YouTube, and he's flying with frsky as well. he uses GPS logger 3.

OK, Thankyou

**Comment by bsongis-frsky** [comment]
@Richrfl Why do you say this "This issue was one already treated in the good old OpenTx". This problem has nothing to do with the radio firmware, unless I am missing something?

**Comment by Richrfl** [comment]
I apologize for the confusion. I was answering to Quick. That is why I quoted his response. It was not my intention to reopen this issue on this thread. I guess I missed to "close with comment". Sorry.
