### ISSUE TITLE
Binding x20 with XJT lite AND Frsky V8Fr II

### ISSUE THREAD

**Issue by danydu62** [FrSkyRC/ETHOS-Feedback-Community#2891]
Hello . I have a X20 with XJT lite module and I want to bind a Frsky V8Fr II receiver . Can anyone help me step by step ( maybe with photo or wideo) to bind them please ? I can’t find any video ont YouTube with ethos . Many thanks for those who will help me .

**Comment by mawzthefinn** [comment]
Put the XJT Lite in D8 Mode, follow the D8/Telemetry bind procedure in the V8FR-II manual.

I'd suggest taking further questions over to the RCGroups thread 

https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-X20-Pro-Tandem-24-Channels-with-ETHOS

The Github is more for radio issues, not accessory use guides.
