### ISSUE TITLE
cant add lua to my tandem x20hd

### ISSUE THREAD

**Issue by skychen8022** [FrSkyRC/ETHOS-Feedback-Community#2893]
i try to add the lua to my tandem x20d but it does not show out in my external module...pls advise

**Comment by bsongis-frsky** [comment]
Which lua script? Where do you copy it?

**Comment by skychen8022** [comment]
Erls and Muti module lua  and i copy it to x20hd SD card but it doesn't show in the external module..

**Comment by mawzthefinn** [comment]
What are the paths, most likely issue is the files are in the wrong folder

**Comment by skychen8022** [comment]
Ok  try to solve it...thank for you advise...Good day my friend. 

Sent from Yahoo Mail on Android 
 
  On Fri, 15 Sept 2023 at 20:11, ***@***.***> wrote:   


What are the paths, most likely issue is the files are in the wrong folder

**Comment by skychen8022** [comment]
still got problem add ERLS and other LUA to my tandem x20hd.......i follow all the step my SD card show the LUA i download but my external module just did not show any LUA that i added...

**Comment by MIKE-DAILEY** [comment]
Here are some instructions for using third party modules with ETHOS systems https://www.rcgroups.com/forums/showpost.php?p=49550649&postcount=18844

ELRS is working OK here on a X20 Pro with ETHOS 1.4.11.

**Comment by skychen8022** [comment]
ok thanks my friend i will try it hopefully will work.....get frustrated and cant find solution....

**Comment by bsongis-frsky** [comment]
Is this issue still valid?

**Comment by skychen8022** [comment]
Yes my friend the problemdtill valid.....anyway I had email to the service center and send back my x20hd to China and hopefully they will rectify the problem...thank you very much for your follow-up with my query...

Sent from Yahoo Mail on Android 
 
  On Thu, 5 Oct 2023 at 23:52, Bertrand Songis @ ***@***.***> wrote:   


Is this issue still valid?
