### ISSUE TITLE
Sensor conflict

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2898]
Not sure if it is only me.

I  build my own sensors, and since I updated to 1.4.11, selecting feet in altitude, being for GPS or for the other altitude, Tx keeps saying: - _"Sensor conflict"_.

Left my Tx in meters for an hour ON and it did not had that warning.

Again, could be something I am doing wrong but same code worked ok with 1.4.09.

Thank you

**Comment by bsongis-frsky** [comment]
"Sensor conflict" should have nothing to do with the sensor unit!

**Comment by bsongis-frsky** [comment]
Are you sure it's related? You set again "feet" and you directly get this "Sensor conflict"?

**Comment by salibaj2** [comment]
I am going to close this issue until I try further things to see what is going on.

Thanks
