### ISSUE TITLE
Reopening Issue #21.

### ISSUE THREAD

**Issue by OldGazer** [FrSkyRC/ETHOS-Feedback-Community#29]
I have flashed the 0.17 boot loader and firmware.  I created a new model.  When I enable the 2.4gHz internal TX module the display glitches and tears. 

This behavior does not occur with FW and BL 0.16

Link to video:
https://drive.google.com/file/d/1ClCFlX4euJK24wXm5h3nSX65Os0pr1u9/view?usp=sharing

**Comment by bsongis-frsky** [comment]
Did you update your bootloader to 0.0.17?

**Comment by OldGazer** [comment]
Yes.

**Comment by OldGazer** [comment]
Fixed in 0.18 firmware.

Closing.
