### ISSUE TITLE
Voltage sensors: add voltage and multiplier

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#290]
Tandem X20
Ethos 1.0.6
TD-ISRM 2.1.7
Archer R8 Pro on 2.1.7

I have connected AIN2 on the Archer R8 Pro receiver to the positive of a 2-cell lithium battery at 8.13V, the Receiver is then powered though a regulator (Zepsus switch).

I wanted to use AIN2 to know the battery voltage.  the pico-blade connector has ground and AIN2 populated, power comes in though servo 7 connector

When you enter the telemetry screen you cannot change the offset or multiplier for that value, which is probably correct since it is supposed to be known, but the voltage value reads 5.7V

![20210520_125743](https://user-images.githubusercontent.com/16928210/119041444-7cb7ed80-b96b-11eb-84d4-e2e09bb5a911.jpg)
![20210520_125725](https://user-images.githubusercontent.com/16928210/119041448-7e81b100-b96b-11eb-91ae-7a8b0ed0d3f6.jpg)

**Comment by jfint** [comment]
I should say that I also have ground connected on the pico-blade connector, along with the AIN2 line.

**Comment by jfint** [comment]
Verified that this is still an Issue with Ethos 1.0.7 and TD-ISRM 2.1.8

It is Telemetry ID: 1A F103

**Comment by nicomo77** [comment]
Same issue on Ethos 1.0.7 and TD-ISRM2.1.8 EU
RX tested is an X4R (ACCST 2.1.0) and 3S Lipo on a FBVS01 sensor
![IMG_1170](https://user-images.githubusercontent.com/83173741/120109681-bc9c8300-c16a-11eb-9445-104a99182b1a.png)

**Comment by jfint** [comment]
![Uploading 20210608_173337.jpg…]()
