### ISSUE TITLE
Ethos suite from 1.4.9 to 1.4.11 "hangs" when trying to update.

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2900]
Please delete if this has already been mentioned Computer is 64-bit windows 10. suite will tell me a new version is available and ask if I want to download it. I click on yes, and then a blank white rectangle comes up over the download progress bar and it just sits there. Don't know if anybody else has had this problem I won't obviously be updating ethos. I'm wondering if I need to uninstall it and install from scratch.?

**Comment by mawzthefinn** [comment]
See the release notes for 1.4.11

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.4.11

**Comment by builda1** [comment]
.
