### ISSUE TITLE
form.openDialog has limited space for options

### ISSUE THREAD

**Issue by MiRe-CZ** [FrSkyRC/ETHOS-Feedback-Community#2902]
form.openDialog opens window with the fixed width. That limits possible number of options and in a case options have variable size it can even mean some options are unexpectedly hidden. As example the code below does not show "C6" and "OK" items:

local buttons = {
  {label="C7", action=function() system.playTone(2093,250) end},
  {label="H", action=function() system.playTone(1975,250) end},
  {label="A", action=function() system.playTone(1760,250) end},
  {label="G", action=function() system.playTone(1567,250) end},
  {label="F", action=function() system.playTone(1396,250) end},
  {label="E", action=function() system.playTone(1318,250) end},
  {label="D", action=function() system.playTone(1174,250) end},
  {label="C6", action=function() system.playTone(1046,250) end},
  {label="OK", action=function() return true end}
}

local function Help_Button ()
  form.openDialog("Help", "Play tone ...", buttons)
end

<img width="218" alt="image" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/95141646/5f495947-7fc4-4b1d-8eec-ff1bc148623e">

Would it be possible -
a) to open dialog window fitting to provided options, or better:
b) to allow scrolling options to right and left

Thank you

**Comment by MiRe-CZ** [comment]
Thinking about it, it would be perhaps best to solve this issue by standard vertical selection list, which is used in many places in Ethos

**Comment by MiRe-CZ** [comment]
@bsongis - hello Bertrand, can you please include this ticket into next 1.5.x development plan? I hope a fix will not be so complicated if my suggestion will be accepted (standard vertical selection list)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/38f34e52-a431-4629-8568-449434dcbdac)

```lua
form.openDialog({
                width=790,
                title="Help",
                message="Increase D, P, I in order until each wobbles,\nthen back off.\nSet F for a good response in full\nstick flips and rolls.\nIf necessary, tweak P:D ratio\nto set response damping to your liking.\nIncrease O until wobbles occur\nwhen jabbing elevator at full collective, back off a bit.\nIncrease B if you want sharper response.\nIncrease D, P, I in order until each wobbles,\nthen back off.\nSet F for a good response in full\nstick flips and rolls.\nIf necessary, tweak P:D ratio\nto set response damping to your liking.\nIncrease O until wobbles occur\nwhen jabbing elevator at full collective, back off a bit.\nIncrease B if you want sharper response.", 
                buttons={
                  {label="C7", action=function() system.playTone(2093,250) end},
                  {label="H", action=function() system.playTone(1975,250) end},
                  {label="A", action=function() system.playTone(1760,250) end},
                  {label="G", action=function() system.playTone(1567,250) end},
                  {label="F", action=function() system.playTone(1396,250) end},
                  {label="E", action=function() system.playTone(1318,250) end},
                  {label="D", action=function() system.playTone(1174,250) end},
                  {label="C6", action=function() system.playTone(1046,250) end},
                  {label="OK", action=function() return true end}}, 
                wakeup=function()
                         lcd.invalidate()
                       end,  
                paint=function() 
                        local w, h = lcd.getWindowSize()
                        local left = w * 0.75 - 10
                        local top = 10
                        w = w / 4
                        h = h / 4
                        lcd.drawLine(left, top + h/2, left+w, top + h/2)
                        lcd.color(YELLOW)
                        for i = 0,w do
                            local val = math.sin(i*math.pi/(w/2))
                            lcd.drawPoint(left + i, top + val*h/2+h/2)
                        end

                      end,
                options=TEXT_LEFT
            })
```

**Comment by MiRe-CZ** [comment]
@bsongis - hello Bertrand, possibility to control width of the window sure helps, but only in some cases. What if there is more items for selection and/or their labels are not only one character? In such case even full screen is not enough and some buttons will not be displayed. That's why I suggested to use the standard vertical selection list, which is used in many places in Ethos
