### ISSUE TITLE
X20 Pro trim T5 + T6 influence each other - unusable!

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2903]
X20 Pro trim T5 + T6 influence each other - unusable!
Version: 1.4.11
Bootloader: 1.4.12

![IMG_4465](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/2ad0a106-4aa1-4e92-a47e-33d6353a9dc2)

System/Hardware/Hardware Test - New Model!

![IMG_4461](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/d168cc6f-a444-4145-a2cf-63028ec75313)
Photo 1: Push T5 down
Trim T5 moves down ( correct) T6 moves automatically up (wrong)

![IMG_4462](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/ea41bc67-19a9-4e2f-b349-606d419dc11b)
Photo 2: Press T6 upwards
Trim T6 moves up (correct) T5 moves automatically down (wrong)

![IMG_4463](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/0b70fd11-8c1b-4c9e-99dc-441a0994405e)
Photo 3: Press T5 upwards
Trim T5 moves up ( correct) T6 doesn`t move

![IMG_4464](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/52882a07-8510-4554-ad9a-52c16fdb642d)
Photo 4: Pressures T6 downwards
Trim T6 moves down (correct) T5 doesn`t move 

Please look at arrows of Trim 5 and 6 in display
Radio was delivered today, mistake was immediately.

Greetings
Eugen

**Comment by yak-54** [comment]
have you tested the trims on channel output it may be just hardware test page that has the issue ?

**Comment by mawzthefinn** [comment]
Just tested on my X20PRO and I see no such interaction. 1.4.11 FCC

**Comment by yak55** [comment]
noticed the behavior on screen #1.
(Orginal Ethos with new model).
The display of the trims has changed at the same time.
Please use the complete trim paths to test.
As I said, a new model.
After that, I ran the hardware test.

Greetings Eugen

**Comment by yak55** [comment]
Ich habe versucht noch 2 Videos zu machen.

Video 1:
Power ein

Trim 5 ist maximum
Dann Trim 5 nach unten bis minimum keep key hold on until end.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/db317f64-48e6-4cc4-865a-6992c94f149e




Video 2
Trim 6 ist minimum
Dann Trim 6 nach oben bis maximum, keep key  hold on until end.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/63c2ee0f-4a0f-4b6a-9fb0-712229938acd


Trim keys keep hold on until end.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
It seems like a hardware issue, the 2 lines are adjacent, there may be residual tin balls between the pads.

**Comment by enzo-molinari** [comment]
Just tested on my X20PRO and I see no such interaction. 1.4.11 FLEX.
