### ISSUE TITLE
Feature request: Multiple active conditions for flight modes

### ISSUE THREAD

**Issue by pandjarov** [FrSkyRC/ETHOS-Feedback-Community#2907]
I would request a feature that I believe many will appreciate - multiple conditions for the Flight Modes. 

Right now, if I want to have separate modes for the combination of Flaps and Gear conditions, I need to create a number of logical switches and use them to activate the appropriate flight mode so I can trim my plane in all cases - flaps middle + gear up, flaps down + gar up, flaps up + gear up and again for gear down. So that's 3x2 and if there's any other variable, that multiples. 

I believe it would be much better if we can have a number of active conditions per flight mode. That will eliminate the need of many logical switches and generally make it easier and more straight forward.

**Comment by mawzthefinn** [comment]
I would suggest taking a closer look at priority stacking of your flight modes to simplify things, but Logical switches are the correct answer here. All multiple active conditions would be doing is complicating the UI by duplicating Logical switch functionality in the Flight Mode II, with more limitations due to space

**Comment by Jedsters** [comment]
You may find that VARS in 1.5.0 will help. You can e.g. have a VAR which can have different (in flight adjustable) values according to relevant conditions. You don't say what you are trying to trim, but let's guess elevator. 
Have a VAR which has different values for each of your 3x2 criteria (I'm guessing you'd want 6 LS to identify those and use those to select the value). 

(Just to give you an idea of what this looks like and nothing else
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/8020b35b-a580-489c-b2a9-e25dd98625e6)
)

Then you can have an action which can adjust each of the VALUEs in flight, e.g. SI / SJ to increment / decrement each of the VAR values independently. 

(again, purely so you can see what it looks like and this is for a different VAR but shows the actions
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/0e0d6610-1b2a-4af9-9425-9cd9f089cb82)
)

Finally you can select the VAR in a mixer to add / multiply or whatever the Ele channel. 

I appreciate that may not be clear if you've not played with 1.5.0 (hopefully mawz understands), but maybe make a note and review this when you install 1.5.0. 

(Unless I've misunderstood something, in which case I suspect mawz will correct me.)

HTH

**Comment by Jedsters** [comment]
@mawzthefinn Doesn't that leave the op with the same problem, he'd need numerous FM one for each condition as T5/T6 are per FM?

**Comment by mawzthefinn** [comment]
No, he's just have the regular flap position triggered FM's, with T5 or T6 as the source to a mix that's enabled if gear are down.

That way he'd get elevator trim on T2 or T3 (depending on mode) when flaps are down, and T5/T6 adds to that when gear is also down, with one value per flap position, for a total of 6 values (Flaps up, Flaps mid, Flaps down. Flaps up/Gear down, Flaps mid/gear down and Flaps down/gear down)

**Comment by pandjarov** [comment]
This is a workaround that overcomplicates things even more. Purpose of trims is these adjustments are saved and next time you don’t have to do them again. Changing values with sliders doesn’t really cover this case.

Multiple active conditions will not clutter the interface but will save tens if mixes and logical switches.

**Comment by pandjarov** [comment]
I don't think VAR mixes are solution for the simple need of separate trimming. I will continue using logical switches for this. Thanks for all the ideas and assistance!

**Comment by Jedsters** [comment]
If you've not tried 1.5.0 yet I'd suggest having a play with VARs when you do install it. I found with VARs I was able to simplify my programming a lot.
Otherwise fair enough.
