### ISSUE TITLE
Updating Firmware on External Modules on Ethos Radios

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2908]
Hi everyone, i have a TWIN LITE PRO module in my X20S and i notice there is a firmware update for both my Twin-Lite S radio ISRM internal module and also for the External TWIN module. 

I cant seem to find any way to "Flash External Module" on any of my Radios, only Internal modules-so am i missing something?? 

I have tried it also via Ethos suite and still no joy. @bsongis-frsky and @mawzthefinn am I missing something? There's nothing  in "device config" to flash external modules, or under the RF menu so im a bit lost?? Am running latest version ethos (11) on all my radios. 

NOTE-when i went to update the TD-ISRM module @bsongis-frsky via Suite i got a warning that my X20S was running the wrong firmware, or was the wrong radio (I can't remember which) and terminated the flash, so I had to do it the oldschool way, but it worked fine on my X18SE. 

Thanks for your help guys as always @mawzthefinn please delete if and when this has been dealt with or if it has been mentioned and refer me to where I need to go if possible please👍

**Comment by builda1** [comment]
.

**Comment by mawzthefinn** [comment]
If the firmware is for an external module, it should show 'Flash External Module' as the first option when you tap it in System->File Manager

I just checked with the TW-Lite Pro_1.0.4 file and it shows correctly on my X20PRO on 1.4.11

**Comment by builda1** [comment]
.

**Comment by mawzthefinn** [comment]
All ISRM modules are internal modules, so you will never see an option to install to an external module with one of those firmware files

The TWIN Lite Pro module needs its own specific firmware, the latest is named TW-Lite Pro_1.0.5.frsk

**Comment by Luznatural** [comment]
Sorry to reopen this issue.
I have a X20S radio with Ethos firmware 1.4.13 and a multiprotocol IRX4 Lite module in the back, with all the Lua files already installed, and working perfectly.
I am trying to update the firmware of the external IRX4 Lite module from 1.3.3.20 to 1.3.3.33 without success.
Despite that I have copied the correct firmware in the correct folder of the SD card, when I select the firmware with the file manager, I do not get the option to flash the external module. I only get copy, move or delete options.
If necessary I could provide a video of the issue, but I think is clearly reproduceable.
I offer myself for testing as necessary.
I hope this can be fixed.
Thanks in advance

**Comment by mawzthefinn** [comment]
External flashing of non-FrSky modules is not currently supported in ETHOS.

**Comment by Luznatural** [comment]
No?
It is a real pity. I guess I will have to use Edgetx to update it.
Mostly everyone in my club is using this module for compatibility with other old owned receivers with the x20,s (and it works perfectly once you install the Lua script).
I recommend reconsidering this posture.
Best regards

**Comment by mawzthefinn** [comment]
You don't need a radio to update the IRX4 lite, it can be updated directly from a computer using the USB port on the module.

There's an open request to add the feature, #1861 which likely will be addressed sometime in the future

This issue is for FrSky module updating, not 3rd party

**Comment by Luznatural** [comment]
Thanks for the information.
I have finally updated the firmware of my IRX4 Lite directly in the field, directly using an 8 years old X9D+ Taranis (with OpenTx 2.3) from a friend. He had a cheap adaptor that transformed the standard JR connector in the back to the mini one of the IRX4 Lite. A matter of one minute.
It is curious to me that a Taranis does things in the field that a far newer Tandem X20S cannot do.
