### ISSUE TITLE
Simulator X20S 1.4.12 

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2909]
Hello, The sensors RSSI and Empf. have the same ID 18F101. That's why there is always a "sensor conflict"?

**Comment by bsongis-frsky** [comment]
Would you explain what is the problem? There is no simulator 1.4.12 as of today!

**Comment by bsongis-frsky** [comment]
0xF101 is RSSI
I don't know what is "Empf."

**Comment by Wolepo** [comment]
Attached is a screen video
[Uploading Sim 1.4.12.zip…]()

**Comment by bsongis-frsky** [comment]
I cannot reproduce it. What are your RF settings?

**Comment by bsongis-frsky** [comment]
"EMPF." is "RX". It is the same sensor ID than RSSI. 
The problem is elsewhere.

**Comment by Wolepo** [comment]
After I have created a new model in the simulation, the model shown above is no longer found.
Nevertheless, the message "Sensor conflict" continues to appear for other models, although there is no flashing of the sensors.

**Comment by Wolepo** [comment]
Here is the requested model file
Thank you for the interest.
[l60 brigadyr.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12700544/l60.brigadyr.zip)

**Comment by Wolepo** [comment]
To be on the safe side, I went a different way:
Transmitter X10S Express Ehos 1.4.12 and loaded the models into the simmulator of the X10S Express. Even in the converted models, there is always a "sensor conflict".
[MODELS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12700611/MODELS.zip)

**Comment by bsongis-frsky** [comment]
Those conflics have no meaning in simulation mode. They will be removed in the official 1.4.12
