### ISSUE TITLE
20 Pro with TW GR6 receiver shows no black box recordings.

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#2910]
20 Pro with TW GR6 receiver shows no black box recordings.

X20 Pro: 1.4.11 Flex
HF: FW: 1.0.11
TW GR6 FW: 1.O.5

As can be seen from the pictures:
The black box shows nothing.
Strangely the black box has 2.4Ghz RSSI and VFR listed and instead of Lora it has 868MHz RSSI and VFR listed.

Thanks Enzo

![20230920_224713](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/c70bc922-a4e5-48e6-8046-7ebafc1c3788)
![20230920_224732](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/adfb39d8-3590-4341-a4b7-6c7fbaba5601)

**Comment by mawzthefinn** [comment]
This is a known issue with the receiver firmware
