### ISSUE TITLE
Request: Ability to copy user files from tx to simulator

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2911]
Currently to play with tx models in the simulator you have to copy the model from the tx to e.g.  C:\Users\<name>\.ethosX20S\models but that only gives the model, you also have to copy any user images, audio, scripts etc. from the tx into C:\Program Files (x86)\FrSky\Ethos\X20S\audio or bitmaps etc. or scripts etc.. to get it all correctly simulated.

Please can we have a facility to copy files from the tx into the correct folders? I'm guessing this may have to be a simulator feature as different simulators use different folders so you couldn't know where to copy it otherwise. Maybe a suite backup file could be selected as input?

Thanks

**Comment by strgaltdel** [comment]
you are reffering to two different "targets"

1. model configs, stored within windows in "user environment"
2.  "tx data content", stored under the sim's data directory

i guess your proposal lacks two points
- users could spread tx data content between several media (tx specific)
- user could have installed several (different) sims simultanous
of course, could be omplemented but makes it a little bit more complex

why not using existing synch tools like  puresync, allsync, freefilesxnc etc..

works like a charme, 
can be used for a lot of more use cases
some are freeware,
easy to use,
can be individually configured,
doesn't bind any valuable dev ressources

greetings

**Comment by Jedsters** [comment]
Thanks for the suggestion, but it's not really going to work.
I'm not sure how those sync tools work, however I do not want an automatic sync, I just want to occasionally copy tx files to be able to use them on the sim.
You are right that the problem with sync tools is that I then have no control over which sim the tx files are copied to. This is why I was considering being able to start a sim and in that be able to ask it to copy tx files into the appropriate directories for that sim while leaving other sims alone. Sometimes I run e.g.  a 1.4.12 sim while another a 1.5.0 sim. I wouldn't want tx files from 1.5.0 to be copied into the 1.4.12 sim. I may however want 1.4.12 tx into either 1.4.12 sim or 1.5.0 sim. This should be fairly easy if it is a 'pull' issued by the sim to copy from the tx to the sim. Sync tools don't know what I want to do this time.
A valid alternative may be for me to be able to copy from a suite backup of my choice into the current sim, again performed from the sim.

**Comment by Jedsters** [comment]
bump

**Comment by bsongis-frsky** [comment]
Added to #3440
