### ISSUE TITLE
1.4.12 Display HF - external module last line missing

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2912]
1.4.12 Display HF - external module last line missing

X20S
External module ELRS VANTAC
Function: ok
Language: German

HF-System/Ext.HF-Module
Last line Configure and button missing

If you scroll to the end and press the Enter button, the menu opens and configuration is possible.

ELRS Lua works

Enclosed 2 pictures

Image 1 = 1.4.11
![IMG_6055](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/164c32d0-92fd-4554-86c0-54e7d888df38)

Picture 2 = 1.4.12
![IMG_6054](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/ff45a0f0-3cc5-4153-98e5-3b022735735f)

**Comment by bsongis-frsky** [comment]
Good catch, just in time!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d70e3d03-c064-4b7e-bdec-3c3f7010a04f)
