### ISSUE TITLE
Has anybody got ELRS Backpack working using ETHOS

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#2913]
EP82 is running latest 1.3.0 backpack firmware 

VTX control is working fine but I can’t get the HappyModel EP82 VRX Rapidfire Backpack to work, EP82 appears to bind OK but that is it!

**Comment by mawzthefinn** [comment]
This is more a question for the RCGroups thread than for Github. I'd suggest asking there (where you will have a larger user population) or on the Facebook groups.

I don't fly anything using the Backpack functionality, so I cannot test myself.

**Comment by miggy1952** [comment]
Thanks Adam. I have posted the same question to RC groups and Facebook as you suggested.

On EdgeTx, everything is working fine using the same EP82 on the same Rapid-fire module and using the same ELRS tx module. The only difference is if I plug in the ELRS tx into my Ethos transmitter or my EdgeTx transmitter. Backpack is working as expected with EdgeTx but not when using the same components with Ethos. This made me think it might be an Ethos issue.

I am a bit lost here, maybe you can help me?  You closed this as not being an Ethos issue yet you have never tested it yourself. I would genuinely appreciate your guidance.

**Comment by mawzthefinn** [comment]
This issue remains open, but is currently flagged as 'Not a bug in ETHOS' as this is an ELRS functionality issue. 

That is likely a Lua script matter, not an ETHOS issue.

**Comment by miggy1952** [comment]
Thanks Adam, I am reliably informed that keeping the ELRS Lua updated is a Frsky responsibility. How where can I make this input to those that can fix it?

**Comment by m0p3d** [comment]
@bsongis-frsky

**Comment by bsongis-frsky** [comment]
I don't have the needed hardware to work on this. 
The ELRS Lua scripts are public, they are a good start and should be easy to understand.
Don't hesitate to modify them if needed!

**Comment by mawzthefinn** [comment]
> Thanks Adam, I am reliably informed that keeping the ELRS Lua updated is a Frsky responsibility. How where can I make this input to those that can fix it?

Where did you hear that? It's contrary to what I've been told which is the Lua's provided by FrSky are examples for the various communities to use as a base for ongoing support, not scripts actively maintained by FrSky

**Comment by miggy1952** [comment]
[JyeSmith](https://github.com/JyeSmith)

**Comment by mawzthefinn** [comment]
Jye speaks for the ELRS Project, not for FrSky. 

As I note above, it's up for the community to take up support of the ETHOS ELRS module script going forward. The current script is an example provided by FrSky as a starting point.

There's no obligation for the ELRS project to support this script.

**Comment by miggy1952** [comment]
Any news/developments on this please?

**Comment by bsongis-frsky** [comment]
Without the hardware it will be difficult to go further!

**Comment by miggy1952** [comment]
Did you want me to mail you the Rapid-fire module with the EP82 installed?

**Comment by TB2185** [comment]
FRsky wont support Newer Elrs lua updates. they do this to try to lock you into there system..
