### ISSUE TITLE
Norwegian translation Ethos 1.5.0 Nightly

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#2914]
Norwegian translation Ethos 1.5.0 Nightly.

[no.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12704748/no.txt)

**Comment by bsongis-frsky** [comment]
But translations are CSV files in 1.5.0!

**Comment by mmasch** [comment]
Translated into CSV file  :-)
Hope this works.
[no.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12860635/no.csv)
