### ISSUE TITLE
Sensor lost" message

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2916]
Hello,
the message "Sensor lost" is still present. This can only be switched off by deactivating this message in each individual sensor. I could not select a single sensor.
X10S Express 1.4.12; RX SR8 Pro

**Comment by bsongis-frsky** [comment]
Ready for the next nightlies and 1.6.7

**Comment by BompaBert** [comment]
It would be great to see a different color, for example yellow because red is already used for the sensor conflict. When you have both in telemetry showing - which is what...
