### ISSUE TITLE
Downloading Ethos updates take forever (from 1.4.11 to 1.4.12)

### ISSUE THREAD

**Issue by Luznatural** [FrSkyRC/ETHOS-Feedback-Community#2918]
This is the second time this situation happens to me.
First time was updating Ethos to 1.4.11, and is happening again now with Ethos 1.4.12 update.
When you try updating Ethos using the automatic update feature (when you start Ethos, the suite tells you that there is a new update, and ask you to download it) downloading the latest upgrade of Ethos takes forever.
Downloading speed never overpass 30 Kb/s, as indicated by the suite, so it takes almost 45 minutes to download the update before you may continue.
This issue happens with different computers, different radios, and checked in different locations.
I have at home a wide band fiber optics connection, that with other programs and downloads works very fast, with real downloading speeds of 15-25Mb/s, and uploads of 5-8 Mb/s (checked with software speedmeters).
It is my understanding that this situation normally happens when you try downloading files from a server connected to a poor low speed connection, or when the server has lots of simultaneous downloads at the same time.
Would you be so kind to check if there is a way to improve that speed?
Thanks in advance.

**Comment by mszulen** [comment]
It's github so it's not Frsky's own hosting. I do not have such issues and download is lightning fast. I'm in NL on a 1GB glass fibre.

**Comment by MiRe-CZ** [comment]
Well, I noted the same problem. Downloading via Suite is terribly slow as @Luznatural indicated, moreover it ended in some strange status, see below. Direct downloading went fast, so it does not seem to be GitHub issue.

<img width="415" alt="image" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/95141646/6164da0f-ec94-44ec-9d44-b54b49321005">

**Comment by sjorger** [comment]
Same problem for me with an error announcement after several hours of downloading.

**Comment by Wolepo** [comment]
I downloaded it directly and installed it manually. Everything quickly and without problems.

**Comment by Luznatural** [comment]
I thought also in doing that, but then I asked myself: will I loose the previous backups I did to my radio? Why do we have that option if it doesn't work? I suppose it's better trying to fix the problem, if exists.

**Comment by Nicholas-Luoyi** [comment]
Would you please try to switch the download server in Suite settings and use the check updates to start the updaing.

**Comment by Nicholas-Luoyi** [comment]
> Well, I noted the same problem. Downloading via Suite is terribly slow as @Luznatural indicated, moreover it ended in some strange status, see below. Direct downloading went fast, so it does not seem to be GitHub issue.
> 
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/95141646/270392275-6164da0f-ec94-44ec-9d44-b54b49321005.png">

For this display issue. Please try adjusting the size of the Suite's window

**Comment by MiRe-CZ** [comment]
> Would you please try to switch the download server location in Suite settings and use the check updates to start the updating.

You suggest to change the server location from Github to FrSky Server - is your server the primary source, so we can keep that configuration? I have installed the last Suite version manually in the meantime, so we will see during next update, but response for check update seems to be much faster than with Github

**Comment by Nicholas-Luoyi** [comment]
Suite will save your configuration of course. Github is almost unusable here in CN. But I don't know your situations. So I give the two available selection. Please try to switch it each time you meet a network problem.

**Comment by Luznatural** [comment]
Frsky server is a little faster than Github, but the problem persist. I think it's a problem from the code of the suit. For giving additional data: with my connection, the 110 Mb of the file downloads directly in 4 seconds. The download from the suit took 47 minutes, and the checkup prior to the update took 17 minutes more, before starting the upgrade.
My computer is a Windows 11 with I7 processor and 32 Gb RAM.
On the other side, installing the direct download is very fast, and doesn't request you to perform unistall on the previous version. And you do not loose any of the backups of your radio.

**Comment by GiacomoGaleotti** [comment]
i've fixed disinstlling and reinstalling from new, then the procedure of updare worked smootly in seconds
the checkup prior never worked even after long time so that's why i decided to reinstall from new
the task noticed that file was already downloaded and this time the checkup took no longer than 2 seconds
hope it helps.

**Comment by Nicholas-Luoyi** [comment]
I will be fixed in Release 1.4.13. Since the fix is in 1.4.13. So it will work when you update from 1.4.13 to a new version

**Comment by Luznatural** [comment]
Nicholas,
For your information, downloading Ethos update form 1.6.0 to 1.6.1 is taking far too long again.

**Comment by Nicholas-Luoyi** [comment]
Have you check the server location? It has been reset since 1.6.0. And are you talking about Ethos firmware or Suite update?
