### ISSUE TITLE
Ethos Suite 1.4.12 on MacOS

### ISSUE THREAD

**Issue by sjorger** [FrSkyRC/ETHOS-Feedback-Community#2919]
Ethos suite 1.4.12 does not work under macOS
The application refuses to get started.
My MacOS version is 11.7.10

**Comment by mawzthefinn** [comment]
Runs fine on MacOS 13.5.2 on my MacBook Pro M1

**Comment by mszulen** [comment]
1.4.12 runs fine on M1 MacOS 14 (Sonoma). Could be, you need to approve it in the security settings?

**Comment by sjorger** [comment]
I manage to approve in the security setting but then the application stops

**Comment by mszulen** [comment]
Any chance you would upgrade to a newer OS? Or, for some reason you don't want/can't do that?

**Comment by sjorger** [comment]
My 2014 MacBookAir no longer accepts updates beyond 2.11

**Comment by mawzthefinn** [comment]
Mac OS 11 (Big Sur) is exiting support now with the pending release of 14 (Sonoma) and many applications are either now no longer supported or just posting the last supported version.

**Comment by Jepelisa** [comment]
Idem for me: open Ethos suite 1.4.12 is impossible on my MacBook Air.My MacOS version is 11.7.10
I have this error msg
Last login: Mon Sep 25 20:21:46 on ttys000
/Applications/Ethos\ Suite.app/Contents/MacOS/Ethos\ Suite ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Air-de-Pierre-yves-2:~ pierre-yvesjeanmaire$ /Applications/Ethos\ Suite.app/Contents/MacOS/Ethos\ Suite ; exit;
updating HID devices...
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

**Comment by mawzthefinn** [comment]
That error looks like it's dying on USB issues (HID is mostly USB devices).

**Comment by Nicholas-Luoyi** [comment]
Have your Suite before version 1.4.12 being able to start?

**Comment by sjorger** [comment]
Until version 1.4.11 everything worked correctly.

**Comment by Nicholas-Luoyi** [comment]
Is there any way that I can send you a test version and we can try to figure out the resaon

**Comment by Nicholas-Luoyi** [comment]
It's impossible to upload it here because it's too big. Maybe your e-mail?

**Comment by sjorger** [comment]
> It's impossible to upload it here because it's too big. Maybe your e-mail?

serge@jorger.be

**Comment by Nicholas-Luoyi** [comment]
Sent. If you see some warnings pop up. Please post them to me

**Comment by sjorger** [comment]
> Sent. If you see some warnings pop up. Please post them to me

The sent version does not work either

![Capture d’écran 2023-09-26 à 11 09 01](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/30471263/dbc1acb9-6233-4a53-b461-fef3c662acff)

**Comment by Nicholas-Luoyi** [comment]
Nothing different against the release version?

**Comment by sjorger** [comment]
> Nothing different against the release version?

Identical to the release version

**Comment by Nicholas-Luoyi** [comment]
I will take some time to find it. You could use 1.4.11 temporary.

**Comment by GWCTas** [comment]
I have the same issue. Sadly my $A4500 MB Pro is redundant because I cannot update beyond Big Sur for the same reasons as above. As much as I love my Mac, returning to Windows may be the solution to Apple's forced redundancy marketing.

**Comment by mawzthefinn** [comment]
> I have the same issue. Sadly my $A4500 MB Pro is redundant because I cannot update beyond Big Sur for the same reasons as above. As much as I love my Mac, returning to Windows may be the solution to Apple's forced redundancy marketing.

Windows isn't necessarily a solution, MS forcibly obsoleted pre-2017 systems when Win11 launched and does the same thing periodically (and is much worse about documenting what's supported)

Apple has very predictable aging out of systems from support as time goes by. A system which cannot be updated to at least MacOS12 is nearing a decade old at this point and that's a pretty good run for any computer.

**Comment by packetpilot** [comment]
This is also true for a (nearly decade-old) MacBook Air running macOS Big Sur 11.7.10.

Here is some output that may be helpful.

```
┌─[dc@exhaust] - [~] - [2024-01-12 01:52:03]
└─[0] <> ~/Applications/Ethos\ Suite.app/Contents/MacOS/Ethos\ Suite
[13881:0112/135213.990741:ERROR:node_bindings.cc(143)] Fatal error in V8: v8::Template::Set Invalid value, must be a primitive or a Template
[1]    13881 segmentation fault  ~/Applications/Ethos\ Suite.app/Contents/MacOS/Ethos\ Suite
```
