### ISSUE TITLE
X20S - Twin Lite Pro module, Twin GR-6 receiver, SBUS servos sensor conflict error

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#2921]
The latest updates are up and a continuous sensor conflict error is being reported by the radio for the servos. If I remove the servo telemetry there is no error. So the problem is with the servo telemetry.
With the 1.4.11 and 1.0.4 Twin receiver and the 1.0.4 Twin Lite module, there is no sensor conflict error.

On X20Pro radios since there is no update of the internal module! 
There is also sensor conflict error message constantly plus the servos move choppy, stuttered!

![381453379_999096351306738_8735259505321346802_n](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84585992/bbfdb05d-dde0-4720-8b00-603faf2e157d)

**Comment by mawzthefinn** [comment]
Which servos? TWIN doesn't support Sbus servo telemetry.

FBus/XAct servo telemetry requires each servo after the first to have its physical and AppID's changed to avoid a conflict.

**Comment by jufelap** [comment]
Servo type D5701.
I don't know why you write that it doesn't support telemetry? :-)
Here it seems to be described (overwiew) that it supports.
https://www.frsky-rc.com/product/tw-gr6/

But you were right, unfortunately the Application ID was set to 6800 for all servos. Only the Physical ID was different. I set different Application IDs for the servos and the error message disappeared. Thanks for the help. :-)

Only one error remains. The X20PRO radio did not get the Twin 1.0.5 update, so the servos are still moving stutteringly and jerkily.

I'm waiting for the update because it didn't arrive with 1.0.12.

**Comment by mawzthefinn** [comment]
Glad you got it sorted.

The AXct D5701's are FBus telemetry servos, not Sbus telemetry servos. There is a significant difference between FBus and Sbus and FrSky doesn't support servo telemetry with Sbus telemetry servos, only control, while FBus has all the features.

**Comment by mawzthefinn** [comment]
Closing this one off as the sensor conflict is sorted and the jerky servos are going also reported in your issue #2952
