### ISSUE TITLE
Enhancement - System Event for Trainer state

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#2923]
Trainer Active/Trainer Inactive would be a useful system event to have, to better support use of VAR Mixes as selectors to allow replacement of switches with trainer channels when controlling multi-surface mixes controlled by switches. 

This would make the VAR mix use safer as then it would only activate when the Trainer is active, and not potentially with bad data when the trainer switch is flipped with no student connected.

**Comment by bsongis-frsky** [comment]
Available in next nightlies
