### ISSUE TITLE
Ext. Module configuration missing 1.4.12

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#2925]
After updating to 1.4.12 Ethos - Configuration button for external Module missing in the RF Tab(ELRS)

Already configured models still working
Same in #2883

**Comment by bsongis-frsky** [comment]
When do you have downloaded the 1.4.12? This issue has been fixed after it was pre-released

**Comment by m0p3d** [comment]
Thanks - I installed while still labeled as pre release. For me it was not obvious that release is modified. Will retest later today

**Comment by m0p3d** [comment]
Fixed after pre release - final build of 1.4.12 ok
