### ISSUE TITLE
edit model from PC

### ISSUE THREAD

**Issue by GiacomoGaleotti** [FrSkyRC/ETHOS-Feedback-Community#2926]
is there a way to edit models from PC and perform testing of logical swithches or special functions?
in the model list from ethos suite the edit buttons in each model shown are always grey

even with ethos simulator is not possible to work on things because is not possible to toggle switches with keyboard or with transmitter connected as a joistick.

and also (may need another topic) in my pc and flight simulator i can not program any of the sliders or buttons or else.. only the sticks seems to work.

**Comment by mawzthefinn** [comment]
There’s no current PC model editing beyond the simulator. It is planned as a future enhancement for Suite

**Comment by Luznatural** [comment]
This issue should not be marked as completed, but at least assigned to a future release.
