### ISSUE TITLE
Suite Wont complete update to v 1.4.12 plus other observations.

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2927]
Hi everyone, 

1)Did anybody else find The "auto update" for Suite from 1.4.11 (that I had to get direct from Github) to 1.4.12 would not complete and it would hang while "verifying update"? 
I ended up downloading it again direct from Suite. 

2)I updated my X18SE first ok, then I did my TWIN lite-S, then my X20S ok. 
EVERY TIME it was downloading the firmware for each Radio the message on screen said "downloading i18n firmware" regardless of the radio connected. 

Each one appeared to update ok @bsongis-frsky and @mawzthefinn but just thought I would mention it. 

3)Question - forgive me if i answer this myself here, but the "Lua" downloads from the Frsky-rc.com website are just for OTX based systems yes? Cheers

**Comment by mawzthefinn** [comment]
Slow download for updating Suite to 1.4.12 has been widely reported. 


There are ETHOS Lua available for the new SR series receivers (Plus, TANDEM & TW), the RB-25/35, the NeuronII ESC's and the Power Switch. They are shown in a labelled section of the download page for the product in question. OpenTX Lua downloads are separately categorized. If it is for an older product, it would be OpenTX Lua.

**Comment by Szonu** [comment]
My ethos suite won’t complete update to 1.4.1.2 on 2 computers.

**Comment by builda1** [comment]
.
