### ISSUE TITLE
Mac OS Sonoma 14.0 "Missing Drive!" Can't update firmware or bootloader via Suite

### ISSUE THREAD

**Issue by ZeekWorld** [FrSkyRC/ETHOS-Feedback-Community#2928]
After moving to the new Mac OS Sonoma 14.0, the OS will load only one drive from X20S.
When trying to update Firmware or Bootloader is unsuccessful with the following message (see screenshots attached).
Tested with the last three Ethos Suites Versions.
Mac Studio M2 and MacBook Pro M1, same behavior.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16088952/909041b0-8326-41b2-bc11-d78ed5f23248)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16088952/61a092ad-f10e-40ec-bc50-f7d7538457c1)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16088952/cb648fa7-eb99-4efc-867e-fa8d16b51114)

**Comment by mawzthefinn** [comment]
Working fine on Sonoma on my X18.

Try a manual update of the bootloader on your X18, the only difference I see between my setup and yours is bootloader version, I was already on bootloader 1.4.12

**Comment by ZeekWorld** [comment]
Mine it's a x20s.
Already manually upgrade bl and fw.
Will continue to test and report back.

**Comment by ZeekWorld** [comment]
Issue continue to exist on the latest BT/FW 1.4.12

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16088952/0e11ae9e-2a38-4dc3-adec-c2215891330e)

**Comment by mawzthefinn** [comment]
Does the drive show in Finder? This could be MacOS USB Security not letting Suite access the drives.

**Comment by ZeekWorld** [comment]
Only one drive shows on finder. I believe this is the issue, there should be a second drive.
Security looks good
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16088952/77a4d9ba-ee78-4b9c-9e20-17f6a890b070)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16088952/4335f10b-c9ea-4544-ba1a-628f414ec5d9)

**Comment by mawzthefinn** [comment]
No a suite issue then. Your SD card is not mounting at the OS level (it's the internal flash drive which is mounting).

That's most likely a MacOS issue, but possibly a bootloader issue. I'd pull the SD card, mount it in a reader, copy the latest bootloader over (1.4.12), update manually and try again.

**Comment by ZeekWorld** [comment]
If you look at my screenshots above, it's what I've already done.

**Comment by ZeekWorld** [comment]
Well, my Mac Studio M2 updated to 14.1 Beta and the issue is now resolved.
Now both drives show up on the Suite and Update passes.... very interesting... I guess this issue can be tagged as resolved.... for now.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16088952/eec47dfb-0612-4871-96b0-727427bf1b3c)

**Comment by bsongis-frsky** [comment]
You shouldn't fly with Mac OS nightlies, it seems not safe!

**Comment by tobydz** [comment]
I'm running into this issue now too.... I'm on 14.2.1.
