### ISSUE TITLE
Ethos (Tandem X20) via headphones is killing my ears

### ISSUE THREAD

**Issue by Muenze** [FrSkyRC/ETHOS-Feedback-Community#2929]
Hello,

Since my speakers have gone fishing and my radio was silent I had to use headphones. I used the std apple headphones. 
Bad decision, now my ear is seriously hurting. Even on the lowest level it's enough to chase away submarines.
Can you please tell me what I can do to get a loudness level that is acceptable and which will not put my ears in any more risks?

**Comment by Muenze** [comment]
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3731435/9c266459-f36c-476d-a320-c5b157999d8f)
This is a screen from my ethos suite

**Comment by Muenze** [comment]
Used the Headphones Plug, sound is working again ... I think this is now a problem for customer service

**Comment by kramgrand** [comment]
Go into settings for setting the speaker volume and select the centre slider (The one with the red knob) As source for the volume control.

**Comment by bsongis-frsky** [comment]
Right, it's a good idea to assign the volume level to a slider
