### ISSUE TITLE
Connection loss x20s / R8

### ISSUE THREAD

**Issue by Beastyboy80** [FrSkyRC/ETHOS-Feedback-Community#293]
I had connection loss .

This was at the high start  .F3j Plane 

See my log 

Firmware is up to date 

Transmitter x20s .Receiver R8

![Screenshot_20210520-233143_Chrome](https://user-images.githubusercontent.com/64907700/119056181-8c1a5380-b9ca-11eb-9fd9-1ce76678f44a.jpg)

**Comment by Beastyboy80** [comment]
Failsave active for 3 seconds 

No problems with power

Distanz only 30 Meter

**Comment by SmartTommy** [comment]
> Failsave active for 3 seconds
> 
> No problems with power
> 
> Distanz only 30 Meter

Hi，Could you reproduce that?

**Comment by Beastyboy80** [comment]
![logg2](https://user-images.githubusercontent.com/64907700/119107089-39b75200-ba1f-11eb-932a-ca54ef2e56f7.jpg)

The Same with GR8 Receiver

**Comment by SmartTommy** [comment]
Thanks! i will check that.
do you have a Access Tx such as ISRM or others? could you help test if the it does the same as the TD-ISRM? 

Thanks!

**Comment by SmartTommy** [comment]
> ![logg2](https://user-images.githubusercontent.com/64907700/119107089-39b75200-ba1f-11eb-932a-ca54ef2e56f7.jpg)
> 
> The Same with GR8 Receiver

Thanks! i will check that.
do you have a Access Tx such as ISRM or others? could you help test if  it does the same as the TD-ISRM.

Thanks!

**Comment by Beastyboy80** [comment]
> > Failsave active for 3 seconds
> > No problems with power
> > Distanz only 30 Meter
> 
> Hi，Could you reproduce that?

Yes 
[Neues--Modell-2021-05-21-19-45-52.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6524430/Neues--Modell-2021-05-21-19-45-52.csv)
![Logg54](https://user-images.githubusercontent.com/64907700/119182311-09010800-ba73-11eb-8532-ae94addb52ee.jpg)

![20210521_132321_autoscaled](https://user-images.githubusercontent.com/64907700/119182386-1ddd9b80-ba73-11eb-9267-5e1c0441af09.jpg)

Test setup next to my table.

GR8 receiver with servo and flag.

Transmitter on and failsafe position createtd.

Wait and Wait and Wait and suddenly .

See my Log

**Comment by SmartTommy** [comment]
> > > Failsave active for 3 seconds
> > > No problems with power
> > > Distanz only 30 Meter
> > 
> > 
> > Hi，Could you reproduce that?
> 
> Yes
> [Neues--Modell-2021-05-21-19-45-52.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6524430/Neues--Modell-2021-05-21-19-45-52.csv)
> ![Logg54](https://user-images.githubusercontent.com/64907700/119182311-09010800-ba73-11eb-8532-ae94addb52ee.jpg)
> 
> ![20210521_132321_autoscaled](https://user-images.githubusercontent.com/64907700/119182386-1ddd9b80-ba73-11eb-9267-5e1c0441af09.jpg)
> 
> Test setup next to my table.
> 
> GR8 receiver with servo and flag.
> 
> Transmitter on and failsafe position createtd.
> 
> Wait and Wait and Wait and suddenly .
> 
> See my Log

Thank you! we have find the problem and will update the firmware, thanks for help!

**Comment by pld74** [comment]
Nice Found @Beastyboy80!!!

@SmartTommy, is this a TX Firmware or RX Firmware revision?

**Comment by rburrow87** [comment]
Is this specific to the X20S or non-FCC firmware? Wondering if I should hold off on using my X20 until this is fixed or we get more info on what combinations this effects. I use several Archer receivers - R10 Pro, R8 Pro, SR8 Pro, and SR6. Also have a couple R9 SX.

**Comment by SmartTommy** [comment]
> Nice Found @Beastyboy80!!!
> 
> @SmartTommy, is this a TX Firmware or RX Firmware revision?

Tx Firmware revision will update

**Comment by Beastyboy80** [comment]
> Is this specific to the X20S or non-FCC firmware? Wondering if I should hold off on using my X20 until this is fixed or we get more info on what combinations this effects. I use several Archer receivers - R10 Pro, R8 Pro, SR8 Pro, and SR6. Also have a couple R9 SX.

My R8 and GR8  had both the Problem 

R10 Will be tested

**Comment by Beastyboy80** [comment]
![R10Pro](https://user-images.githubusercontent.com/64907700/119389604-27157500-bccc-11eb-9c8f-1424145a66de.jpg)
 
R10 Pro had the Same Problem

**Comment by SmartTommy** [comment]
> > Is this specific to the X20S or non-FCC firmware? Wondering if I should hold off on using my X20 until this is fixed or we get more info on what combinations this effects. I use several Archer receivers - R10 Pro, R8 Pro, SR8 Pro, and SR6. Also have a couple R9 SX.
> 
> My R8 and GR8 had both the Problem
> 
> R10 Will be tested
> 
> This is a GR8 Test
> ![looooog](https://user-images.githubusercontent.com/64907700/119386376-b9ffe080-bcc7-11eb-98f2-ea84320367e9.jpg)

The new TD-ISRM firmware has been updated,Thank you for your test.

**Comment by Joetrin** [comment]
@SmartTommy where can the new firmware be downloaded, please?

**Comment by SmartTommy** [comment]
> @SmartTommy where can the new firmware be downloaded, please?

@Adelaxie will post the new firmware.

**Comment by Adelaxie** [comment]
[TD-ISRM_2.1.8-Beta.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6535941/TD-ISRM_2.1.8-Beta.zip)
Beta version ， please confirm.

**Comment by pld74** [comment]
> [TD-ISRM_2.1.8-Beta.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6535941/TD-ISRM_2.1.8-Beta.zip)
> Beta version ， please confirm.

Thank you!

**Comment by MichaelETHOS** [comment]
@Adelaxie is the beta version eu-lbt or fcc. or for both?

**Comment by MichaelETHOS** [comment]
@Adelaxie 
x20 1.0.7 s8r 2.1.0
I had a failsafe but can't see anything in the logs. I only know because I use the rescue mode from the receiver as a failsafe. i'm flying and suddenly the model is in level position at the enigine stops. it only took 1-2 seconds. I see that in the logs that the engine stop the U/min falls to 0. I load the log file maybe you recognize something
[Viper-2021-05-24-15-20-14.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6537110/Viper-2021-05-24-15-20-14.zip)

>

**Comment by SmartTommy** [comment]
> @Adelaxie
> x20 1.0.7 s8r 2.1.0 TD-ISRM 2.1.7
> I had a failsafe but can't see anything in the logs. I only know because I use the rescue mode from the receiver as a failsafe. i'm flying and suddenly the model is in level position at the enigine stops. it only took 1-2 seconds. I see that in the logs that the engine stop the U/min falls to 0. I load the log file maybe you recognize something
> [Viper-2021-05-24-15-20-14.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6537110/Viper-2021-05-24-15-20-14.zip)
> 
> >

please test the TD-ISRM_2.1.8 Beta, it is for lbt/fcc/flex, thanks!

**Comment by Sigee3** [comment]
Your beta firmware didnt solve the issue and I just lost a plane to it.
NOT HAPPY

**Comment by Joetrin** [comment]
Tested for 2 different cycles on ACCST, each 15 minutes long, on RX8RPro.  No issues, I'll upload the logs tonight.

@pld74 tested on ACCESS using R8 Pro for 4 hours yesterday, no issues or RSSI drop off registered.

**Comment by franz4949** [comment]
@Joetrin  Did you notice that FCC probably was and is not affected? It's obviously a matter of LBT firmware.

**Comment by Joetrin** [comment]
> @Joetrin Did you notice that FCC probably was and is not affected? It's obviously a matter of LBT firmware.

Correct,  it's never bad to run a test of the firmware for Fcc also, you never know the outcomes until it is tested.

**Comment by franz4949** [comment]
You are absolutely right.

**Comment by pld74** [comment]
New FW works great! My logs files from my various tests. No loss of signal. Each from a different location around my home. Cheers...

[Logs.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6555351/Logs.zip)

**Comment by MichaelETHOS** [comment]
@pld74 
EU LBT?

**Comment by pld74** [comment]
> @pld74
> EU LBT?

FCC - Sorry I didn't identify in my original post

**Comment by pld74** [comment]
> > @pld74
> > EU LBT?
> 
> FCC - Sorry I didn't identify in my original post

If there is a way to flash it EU LBT and also for my R8 Pro and afterwards back to FCC, i'll gladly test today and report. Let me know.

**Comment by pld74** [comment]
> > > @pld74
> > > EU LBT?
> > 
> > 
> > FCC - Sorry I didn't identify in my original post
> 
> If there is a way to flash it EU LBT and also for my R8 Pro and afterwards back to FCC, i'll gladly test today and report. Let me know.

I am testing with EU LBT now... Logs to follow...

**Comment by pld74** [comment]
@MichaelETHOS Testing with EU BLT now... I'll post Log Files later on

**Comment by pld74** [comment]
@MichaelETHOS Here you go.... X20; Ethos: v1.0.7 EU BLT; ISRM: v2.1.8; R8 Pro v2.1.7; Protocol: ACCESS - No loss of connection

[EU BLT Log Files.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6555990/EU.BLT.Log.Files.zip)

**Comment by bsongis-frsky** [comment]
@Sigee3 I am not part of the RF team, but perhaps I could give a hand. As of today, all tests seem good on the new firmware and they cannot explain your crash. Would you please contact me on my email bsongis@gmail.com. Thanks

**Comment by Sigee3** [comment]
Email sent. Thanks

**Comment by Hobby4life** [comment]
Flown today from 9 am till 6pm, 20+ flight on 2 planes.. SR8 and R9 Pro, 0 failsaves.
I think they tackled and fixed the issue.

**Comment by pld74** [comment]
> Flown today from 9 am till 6pm, 20+ flight on 2 planes.. SR8 and R9 Pro, 0 failsaves.
> I think they tackled and fixed the issue.

That’s good news! Have a great weekend all!

**Comment by KevinFairgrieve** [comment]
> Flown today from 9 am till 6pm, 20+ flight on 2 planes.. SR8 and R8 Pro, 0 failsaves.
> I think they tackled and fixed the issue.

That is really good to hear.

May now go ahead and do the upgrade.

**Comment by KevinFairgrieve** [comment]
So I did the upgrade.

Three perfectly normal trouble free flights this morning.
