### ISSUE TITLE
X20S Pro - 2.4G FSK default power major bug

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2933]
New X20 Pro
Ethos 1.4.11 FCC
Stock TD-ISRM Pro HS 1.0.3, TD-ISRM Pro fw 1.011

first 4 flights today on an EDF model resulted a 1-2s lockout in each flight, unfortunately forgot to turn on logs. this model has flown 100+flights on X20S with ZERO events.
tested X20S/X20 Pro against the same model on the ground, on 3m distance the X20S showed RSSI 85db and X20 Pro ~72-75db.

so went to check RF settings - on ACCESS mode the 2.4 FSK Power showed 10mw (while menu options are 25mw / 100mw) - this is surely a bug that a non existent option was the default. maybe a trace of something old but it seems i have flown on the 10mw settings today.

also, **i believe the X20S 2.4 power is 100mw, therefore the default RF power for 2.4 FSK should also be 100mw.**
the default values should always be backwards compatible or otherwise need to warn the user that he is flying on 1/10 - 1/4 of the RF power of his former radio (about 1/2 the range or less).

here is some photographic documentation: 
10mw option was default, despite menu only allowing 25/100mw:
![10mw_menu](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/39922395-3840-42f9-a1e1-57d4c49b0a4b)

10mw RSSI at 3 meters is 72db (lower than what i am used to):
![10mw_72db](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/8221a9ff-04bd-4735-a307-7b1da69c2c82)

25mw RSSI at3 meters is 76db (lower than what i am used to):
![25mw](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/f142e8ae-6bc9-42e6-b7aa-e3d8ded2951d)

100mw RSSI at 3 meters is 85db (same as X20S):
![100mw84db](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/a4dbe2b5-7c83-4743-851a-e07ad784df52)

@bsongis-frsky

**Comment by mawzthefinn** [comment]
What are you getting on 1.4.12? A number of minor X20 Pro issues are addressed in 1.4.12

**Comment by i3dm** [comment]
1. I havent tried 1.4.12.
2. Once manually picked 25 or 100, the 10mw can no lo ger be picked.
3. When changing protocols to TD and back to access, the default reverts back to 25mw instead of 100mw. That is on 1.4.11.

**Comment by kramgrand** [comment]
I received my x20pro a couple of weeks ago and very quickly found on launching a f5j I had critical rssi messages sounding off almost as soon as it left my hand. Caused great concern.  Powered off motor and landed straight away. On looking through the RF section noticed it was at 10mW and of course corrected it to 100mW on all models switched over to 20pro.  
Apologies, didn't think to message it on GitHub.  If it is corrected on 1.4.12 Great! . But if all 20pros out of the box default to 10mW that could easily cause major issues.

**Comment by bsongis-frsky** [comment]
There is a bug: the power should be 100mW on 2.4G band after conversion from X20S

**Comment by bsongis-frsky** [comment]
Fixed in 1.4.13

**Comment by i3dm** [comment]
Good thanks. Is 100mw the default of any newly created model as well?

**Comment by bsongis-frsky** [comment]
Yes

**Comment by i3dm** [comment]
Agree. Dont see why it was needed.

**Comment by kramgrand** [comment]
Agreed. Unnecessary option with potential serious ramifications.

On 16 Oct 2023, at 09:55, i3dm ***@***.***> wrote:



Agree. Dont see why it was needed.
