### ISSUE TITLE
LUA sources and widgets should reset at model switch or "reset flight"

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2935]
LUA sources and widgets should reset their data when flight is reset, either by using "Reset Flight" or selecting a different model.

If reloading scripts is hard or impossible, maybe we could have a function which gets called in case of reset, like this:

```lua
  system.registerSource({
    key = GEAR_SOURCE_KEY,
    name = GEAR_SOURCE_NAME,
    init = sourceInit,
    wakeup = sourceWakeup,
    reset = sourceReset   -- NEW
  })
```

If we go with such function, then I think it might be useful for `registerSystemSource` too.

**Comment by azaz44** [comment]
Update: I found today, that selecting a different model does call `sourceInit` again, at least with "registerSource" scripts. So selecting a model is not a problem.

There's only a problem with "Reset Flight". Could "Reset Flight" initialize sources just like selecting a model does? This would solve issues. 

I didn't check widgets.

**Comment by bsongis-frsky** [comment]
"Reset Flight" will now call the `init` method of all Lua sources used by the model
