### ISSUE TITLE
addExpansionPanel works not correct in XES simulator 1.5.0 nightly

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2936]
I have tried the function addExpansionPanel in the XES-Sim 1.5.0 nightly.
I think it works not correct.
if i try only one ExpansionPanel it works, 
but if you add another the simulator crash.

line = form.addLine("Line1 before panel")
-- ...

line = form.addLine("Line2 before panel")
-- ...

panel = form.addExpansionPanel("Panel1")
line = form.addLine("Line1 inside panel", panel)
-- ...
line = form.addLine("Line1 inside panel", panel)
-- ...
panel:open(false) -- by default the panel is open, let's keep it closed!

line = form.addLine("Line1 after panel")
-- ...

The line "Line1 after panel" is in the panel included!
panel = form.addExpansionPanel("Panel2")

after this the XES-sim crashes.
Thanks for your help
Storchy

**Comment by bsongis** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5603504/b89ec299-9915-4d20-9c84-20107e15635a)

**Comment by bsongis-frsky** [comment]
Fixed in next nightlies
