### ISSUE TITLE
X20S Pro and TD10 problems

### ISSUE THREAD

**Issue by pandjarov** [FrSkyRC/ETHOS-Feedback-Community#2937]
I am trying to configure my TD10 to work with a Hobbywing A3 Super 4 gyro. Initially, I configured the receiver to use Port 9 as SBUS and everything worked. Up until the moment I tried to configure Port 1 for Sport and Port 2 for channel 13 for my retracts which do not go through the gyro. Receiver didn't accept the configuration. Radio is on 1.4.12 receiver is on 1.0.9 which I even reflashed.

When I make any change, the receiver starts blinking solid blue or green and these changes are not saved. Once in 10 tries it says something is saved. However, SBUS Out on port 1 now says is working but it is not - the gyro doesn't get any signals and blinks red in failsafe. 

Not sure what more information I can provide or if there's something I am doing wrong but to me it seems that something happened to the radio and it started crashing the configuration procedure.

https://www.youtube.com/watch?v=mNSPX7iNVWw

**Comment by mawzthefinn** [comment]
Set your SBus mode to SBus-16, you have it set to SBus-24 in the video, which the gyro will not understand

**Comment by pandjarov** [comment]
OK, I will do that but I am not sure that the receiver accepts the changes. Are there any extra criteria to make such changes? Like no cables to be linked to it or something else?

**Comment by pandjarov** [comment]
This solved the issue. It seems that when SBUS out is configured and set to 24 ports this causes a bug. New option changes cannot be saved. I removed everything from the servo but a power supply, reconfigured it the way I want and the changes were saved. Maybe the gyro was causing some software problems preventing it from receiving new settings and breaking the connection. 

Although it is solved, this feels like a workaround and I think it should be investigated why SBUS out set to 24 channels would prevent the receiver from functioning properly.

**Comment by mawzthefinn** [comment]
Something was identified today which suggests this might work if you set SBus-24 and use a channel range of 1-21

Can you confirm?

**Comment by mawzthefinn** [comment]
TD ISRM PRO 1.1.12 has been released and should solve this issue.
