### ISSUE TITLE
"Line Chart" widget / freeze and unfreeze graph depending on source

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2939]
If I setup the graph to show RSSI, I can check it after flight. However it continues to record data and erases old data after flight.
There is an option to "Pause" but it's a manual operation which needs to be done for every graph.

It would be great to specify a source (`LS`) typically, so the graph is recording only when LS is true.

Another alternative --> tie the graph to some timer. Then the graph could only record data if timer is moving. And it could event use timer values as labels on the time axis. Timer could be moving both up or down.

**Comment by bsongis-frsky** [comment]
Why don't you select "!Telemetry active" as Pause condition?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6ddc696e-d195-4a38-b0ba-be33b76bb89f)

**Comment by azaz44** [comment]
@bsongis-frsky This is exactly what I need. But I don't have such option, is it some recent addition? I'm on 1.4.11.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/ba20e7d9-e8fd-4d3e-88c7-23b03512beac)

**Comment by bsongis-frsky** [comment]
Already available in 1.5.0 nightlies!
