### ISSUE TITLE
Struggling to update to new firmware 

### ISSUE THREAD

**Issue by William2800** [FrSkyRC/ETHOS-Feedback-Community#294]
> I recently got a x20 controller and have been trying to update the firmware but seem to be having no luck. 
I am a Mac user to when I plug the transmitter in while in bootcamp mode I cannot seem to get it to show up on my Mac 

Is there an easy way of updating firmware ???

**Comment by bsongis-frsky** [comment]
you may just use the SD card, write your firmware on the root of the SD card, but named "firmware.bin"
then you insert the card, start in bootloader, it will directly detect the file and flash the radio
