### ISSUE TITLE
X20S adding telemetry sensor crash model memory

### ISSUE THREAD

**Issue by sharonfridman** [FrSkyRC/ETHOS-Feedback-Community#2942]
Hi,

I encountered a problem with telemetry sensors programing.

A working airplane model crash after I'm adding only one sensor.

For example, I'm adding consumption sensor, naming it consumption1 and when I'm restarting the transmitter I get a "model data load - invalid data" massage.

If I'm making the same sensor leaving the name blank then its working.

I found that when I'm naming it by entering directly from one of the home screen square its working.

At this stage I can add more sensors without crashing the model memory.

X20S+TDR10+TDMX+RB35.

**Comment by bsongis-frsky** [comment]
Is it always reproductible? Perhaps even in simulator?

**Comment by bsongis-frsky** [comment]
I think I have reproduced it in nightlies, with a very long sensor name
Are you on 1.4.X?

**Comment by bsongis-frsky** [comment]
Bug found, a custom sensor allowed 16 chars instead of 15 available!

**Comment by bsongis-frsky** [comment]
Fixed for 1.4.13

**Comment by sharonfridman** [comment]
Thanx for the quick response
