### ISSUE TITLE
X20 Pro - VFR on 900M should not be 0% when used with ACCST D16

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2944]
1.5.0 latest nightly

On X20 Pro a redundant 900M receiver can be used with an ACCST D16 main receiver. 
With an S8R rx on ACCST and an R9MINI-O rx on 900M, when doing a range check the VFR for 900M should not be 0. Please refer to the attached screenshot below:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/92627a9c-e6dd-4bd0-bef4-a0a099722d6d)

When the R9 is used with an ACCESS rx, the VFR reports correctly:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/0597ab50-fd20-4483-ba70-af336bc93e19)

**Comment by mawzthefinn** [comment]
X20 PRO TD ISRM PRO firmware 1.1.12 has been released and addresses R9 telemetry issues.

**Comment by lthole** [comment]
Keep alive

**Comment by bsongis-frsky** [comment]
Is this one fixed?

**Comment by lthole** [comment]
Using an X6R on ACCST and an R9 mini on 900M, we now get RSSI and VFR for 900M. However, there is a line for 2.4G VFR = 0% which is not true, there is no VFR for ACCST.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/1bb52251-6db3-4fb6-9bb6-831bcea3a9b1)

**Comment by mawzthefinn** [comment]
> Using an X6R on ACCST and an R9 mini on 900M, we now get RSSI and VFR for 900M. However, there is a line for 2.4G VFR = 0% which is not true, there is no VFR for ACCST.
> 
)

Receivers running Mike Blandford's UNi-FW return VFR on ACCST D16, standard FrSky firmware does not.
