### ISSUE TITLE
Sliding beam overruns and underruns

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2945]
Hello, since 1.4.12 the move bar overflows or underflows when moving logical sliders and special functions.
Attached is a video.
[Ashampoo_Snap_Mittwoch, 4. Oktober 2023_13h29m35s_002_.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12802769/Ashampoo_Snap_Mittwoch.4.Oktober.2023_13h29m35s_002_.zip)

**Comment by bsongis-frsky** [comment]
It seems to me that you miss the bitmap for the move arrows: mask_move_up.png

**Comment by Wolepo** [comment]
Not only are the direction arrows missing, but also the horizontal bar, which disappears under the header. This has only been the case since 1.4.12.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/471c8fbb-8814-4f50-94a5-70a9e38b9482)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/69ad7b56-3d3f-4b0b-977e-a5465e95a99d)
