### ISSUE TITLE
Potential dangerous issue with OTA updates of receivers in Electric Prop planes

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2946]
Hi guys, quick Reminder here to REMOVE PROPS FROM ELECTRIC AIRCRAFT AT ALL TIMES WHEN WORKING ON THEM REGARDLESS OF THROTTLE CUT SWITCH-I HAD 11 STITCHES THE ONE TIME I MADE A MISTAKE! 

Ok onto the issue.

Just lately @bsongis-frsky and @mawzthefinn I've been starting the tedious task of updating all my receivers as a number of them have very old firmware on them (in the case of R8 PRO/SR8 PRO many were the initial release). 

I recently updated all of my spare receivers that are brand-new out of the aircraft using OTA Updates from my X20S with no issues. This was a mix of "Archer SR8/R8/R10"(not Archer +) , TDR6 and TD12, GR8, and a pair of TWIN ones. In every case process was the same-bind RX, find firmware on Radio, flash using internal module and the only thing connected to each RX was a power supply to the RX. All worked flawlessly. 

Last night (Local time) I decided that I would Quickly update the receivers in the aircraft I'm taking flying today as I got the aircraft out of my rack and put them in the van etc. Long story short I tried to update an R8 PRO using the same method used with success a dozen times a couple of nights ago (bind Rx, then update RX using internal module),anyway bound first plane,made sure prop cut switch active so throttle locked out, find firmware in RX, and soon as I hit the update RX from internal module button the receiver appeared to lose bind, the 15x9 prop fired up at about 25% power and grazed my leg, and the radio sat there with "waiting for RX" on the screen, so shocked cut and a bit puzzled I quickly hit "RTN", and just like that the RX appeared to Re-Bind and the motor stopped. 

At that point i decided it could wait until friday when i unload everything and i would look at it then.

After coming to bed and thinking about it (and talking to a friend in Europe who has been using ETHOS longer than me) I learned a couple of things and decided to raise this issue:

1)my friend has done them in GAS planes not electric with no issues.

2)The ONLY difference to the process when I flashed Various RX out of the plane was no S-PORT sensors or Servos were connected to the ones out the plane 

Question-Anyone else experienced anything similar of have I found a bug?? I will update all prop plane RX's now with Prop off and prob unplug any S-Port sensors.

RX I was Flashing: ARCHER R8 PRO
Firmware version: 2.1.14 (2023-07-21)

Radio used: X20S running 1.4.12 (or whatever latest version is)

Connected to RX via S-Port:FAS100Adv, MLVSS,VARI sensor. 

Curious to know your thoughts - is this a bug?

Cheers

**Comment by mawzthefinn** [comment]
Not a bug, you got the sequence out of order that time and unfortunately it happened in the worst possible case. 

Sequence for OTA updates is to initiate Update from the TX, then power on the receiver, select receiver once detected and update.

The TX goes from control mode to OTA mode, which breaks control link. Your receiver failsafed (and seems to have had unsafe settings). It will sit in 'Waiting for RX' until an RX powers on or you cancel, which drops it back to control mode.

**Comment by builda1** [comment]
.
