### ISSUE TITLE
FWTM lite x20 x20 pro not working 

### ISSUE THREAD

**Issue by Pablovse** [FrSkyRC/ETHOS-Feedback-Community#2947]
Hello, I’m trying to get FWTM lite to work with x20 pro, I have a taranis 9x  as student and I’m using it to give command  to 2 Channels only to the x20 to , this way I can  fly with a pedal system  since I have a disability 

any help appreciated

**Comment by bsongis-frsky** [comment]
It is ready only in 'nigthtlies' for now!

**Comment by Pablovse** [comment]
> It is ready only in 'nigthtlies' for now!

What this mean? A beta version? If so , can you. Provide the link  and instructions to load it into the x20 pro
