### ISSUE TITLE
SBUS limit 125% to 150%

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#2948]
For better compatibility with jeti components (Speed controller, etc.) and new digital servos (Kingmax digital etc.) is required the 150% settings in the Output max and min values.
If i use one redundancy tool (RB-10 or RB12 etc.) the max and min value is 125%.
Have suggestion to bypass the problem?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b64939ea-21fc-46f7-9e6a-9605a004b745)

**Comment by carlogianneschi** [comment]
It's not so easy.
Via SBUS the limit is 125%
even if you set 150% the maximum value remains 125%

**Comment by bsongis-frsky** [comment]
But we reach the limit of SBUS (11 bits per channel)

**Comment by carlogianneschi** [comment]
thanks.
I bypassed the channel I need at 150% by connecting directly to an ACCESS receiver.
If I use a TANDEM receiver the max or min value is limited to 125%.

**Comment by carlogianneschi** [comment]
Yes, X20S with two different receiver (and bind) in the same model.
Archer plus GR8 and TDR10

**Comment by bsongis-frsky** [comment]
Are you sure it's Ethos, and you bind the receivers the same way? Because both kind or receivers use the same way to transmit channels ...

**Comment by bsongis-frsky** [comment]
I will forward the issue to the RF team. Perhaps there is something inside the receiver which adds some limit

**Comment by carlogianneschi** [comment]
> I will forward the issue to the RF team. Perhaps there is something inside the receiver which adds some limit

Is possible

**Comment by carlogianneschi** [comment]
> You are sure that it is no TD SR10? We had such issue here too with this type. There you have to set 150 percent in the radio before you do the self check.

It is not a stabilized receiver. It's a TD R10.
On the transmitter you can go above 125% and get to 150% but the servos go up to 125% and don't go beyond that.
With the Archer plus GR8 they reach 150%

**Comment by hrenz** [comment]
Ethos X20S and receiver current status

You can set a maximum of +/-150% on the transmitter and the us values also fit
But where are the 150% to the recipient Servpin at RX
Not even 125% of the SBus comes out properly.
tested with different receivers regardless of whether ACCST or ACCESS

This should be possible at the Servopins
+/-100% = 1500us +/- 512us = 988us bis 2012us
+/-125% = 1500us +/- 640us = 860us bis 2140us (SBus-Definition)
+/-150% = 1500us +/- 768us = 732us bis 2268us
