### ISSUE TITLE
Horus transmitter and 1.5.0

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2949]
Hello, for some time now I have been missing the Horus transmitters in 1.5.0. Will there be no 1.5.0 for these transmitters?

**Comment by loetefix** [comment]
It seems as if 1.5 will never be released. A lifetime nightly....lol

**Comment by Wolepo** [comment]
Wrong, it will come

**Comment by loetefix** [comment]
i hope so. sometimes dreams come true. BUT WHEN?

**Comment by Wolepo** [comment]
Kommt Zeit, kommt rat

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b0467e0f-da98-4b36-8063-42b4d27f3e93)

**Comment by KevinFairgrieve** [comment]
I would love to test 1.5.0 on my X12S, but alas it is missing from the list. All other TX seem to be available.

Not prepared to risk my X20 as it is my daily flyer.

**Comment by bsongis-frsky** [comment]
Duplicated of #3197. Firmware will be uploaded during next nightlies
