### ISSUE TITLE
Feature request: Insta-trim

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#295]
A special function to set trims according to the current stick position by triggering a momentary switch, such as in OpenTX would be useful.

**Comment by centertrim** [comment]
I think this is the same as https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/41

**Comment by konvice56** [comment]
### extend the trim values by a decimal place  
 0.0% for min,max,trim
![Channel](https://user-images.githubusercontent.com/84669311/119268675-4b9e1e00-bbf4-11eb-8391-93b6da1c3e5f.jpg)

![output](https://user-images.githubusercontent.com/84669311/119268692-653f6580-bbf4-11eb-8496-ac40f55a9884.jpg)

**Comment by FLYN-001** [comment]
Would love this too! Vital on a maiden flight. Instant trim FYW. Please implement 😊

**Comment by giaffone** [comment]
Any update on this feature?
Right now,  LUA support and this are the only things I miss from OpenTX

**Comment by FLYN-001** [comment]
> Any update on this feature?
> Right now, LUA support and this are the only things I miss from OpenTX

There is a “cross trim” feature in the trim menu but it’s not anywhere the same as instant trim. 

Please dev team, do an instant trim function, it’s what everyone wants!

**Comment by chenbevis** [comment]
no progress

**Comment by ululi1970** [comment]
Yes, please add Instant Trim. It has been a day saver in a few occasions when maidening a plane that for whatever reason was badly out of trim.

**Comment by alexestevezfpv** [comment]
> Sí, agregue Instant Trim. Ha sido un salvavidas en algunas ocasiones al hacer limpieza de un avión que, por alguna razón, estaba muy mal ajustado

I really liked the ethos, but it does not have the instatrim or autotrim option, which is in open TX and Edge TX, but it is not in ethos, please add that option

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/226723382-9925ea56-2c88-4a24-a6d1-b5360ddba104.png)

**Comment by daisser** [comment]
when will it be implanted in version 1.5.0??
