### ISSUE TITLE
FWTM x20 pro

### ISSUE THREAD

**Issue by Pablovse** [FrSkyRC/ETHOS-Feedback-Community#2950]
What this mean? A beta version? If so , can you. Provide the link and instructions to load it into the x20 pro. 

If I can’t use a radio to  connect a previous version the system is then not capable of doing what it was doing in the past  version? 

Where is the right place to ask for support 

thanks

**Comment by bsongis-frsky** [comment]
This repository is not dedicated to user questions. Please use RCG / Discord / Other forums for them!
... or someone will again tell us that we will never succeed to fullfill the 1.5.0 milestone ;)
