### ISSUE TITLE
1.5.0 nightly from 10/4 trashed all the programs

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#2951]
All the programs have been corrupted.
Some say invalid data, or  wrong file size.
Only one that is  close is  current model, but Var mixes are gone...

**Comment by mawzthefinn** [comment]
This is a regular occurrence with Nightlies, as the features get updated, there isn’t always conversion from older Nightlies.

**Comment by bsongis-frsky** [comment]
It happened when I worked on the Vars, I changed my mind many times and it broke the conversions. It should be OK now

**Comment by fhpage** [comment]
That’s crazy!  No one can assist in testing if you have to recreate your model after every up date. But… is fixed.

**Comment by mawzthefinn** [comment]
It's not every update, just whenever something has changed enough to break conversion from older nightlies.
