### ISSUE TITLE
After updating the TWIN GR6 receiver 1.0.5 using the internal RF module of the X20PRO radio, the servos move in a jerky manner.

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#2952]
TWIN GR6 receiver updated to version 1.0.5. 
It is indicated that the RF module also needs to be updated.
After upgrade, the X20PRO (software version 1.4.12) radio has a jerky servo movement.

With the external Twin Xlite Pro module (updated to version 1.0.5) the servos move perfectly, but with the internal module the servos move jerkily.
If I reset the receiver to version 1.0.4, the X20PRO is perfect with the internal module.
So the X20PRO radio should have a 1.0.5 update for the internal module.
But I can't find this anywhere and the X20PRO is updated to the latest version 1.4.12.

**Comment by mawzthefinn** [comment]
The fix would be new TD-ISRM Pro firmware, not ETHOS firmware, 1.0.11 is the current version

**Comment by jufelap** [comment]
Yes, I also have version 1.0.11 on my X20PRO radio.
But with this version (1.0.5) the Twin GR6 receiver does not work well with the X20PRO radio. It works fine with version 1.0.4.
Then maybe you should update the version of the X20PRO internal module.
Or am I wrong?
Because it doesn't work that way.
![x20PRO ethos suite](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84585992/dc91a7bb-4625-4989-9369-1999066e5efe)

**Comment by mawzthefinn** [comment]
Yes, it sounds like a TD-ISRM Pro update is needed to match the changes in TW 1.0.5 firmware.

**Comment by jufelap** [comment]
I understand, but who should I write to in order to start the development?

**Comment by mawzthefinn** [comment]
Posting here should be enough. I've passed the message on to my contacts within FrSky as well.

**Comment by jufelap** [comment]
thanks :-)

**Comment by mawzthefinn** [comment]
Confirmed there is a new RF firmware on its way.

**Comment by Boxxxer64** [comment]
Hope so!

**Comment by bsongis-frsky** [comment]
I have asked right now, the new firmware is ready, and it is in testing phase. It will be released as soon as properly tested. It should be next week.

**Comment by Boxxxer64** [comment]
Thanks Bertrant

**Comment by mawzthefinn** [comment]
New firmware for all TW receivers was just posted
'

**Comment by Boxxxer64** [comment]
The x20pro dont need Hf Firmware Update?

**Comment by Boxxxer64** [comment]
I have now tested 1.06 on the TwGr6. rssi 30db worse than with 1.05 or 1.03. the servos still don't run smoothly.

**Comment by mawzthefinn** [comment]
TD ISRM PRO v1.1.12 has been released. Please try this version

**Comment by Boxxxer64** [comment]
I sent my transmitter back. It is an impudence for frsky to throw something like this onto the market. If you want to pee with the big ones you also have to deliver. This also includes Hf firmware! which the customer does not have to test first. I have the greatest respect for you when you develop your ethos, it's great what you've achieved in such a short time. Maybe frsky will wake up again before they throw 10 more transmitter onto the market that aren't ready.

**Comment by jufelap** [comment]
> Megjelent a TD ISRM PRO v1.1.12. Kérjük, próbálja ki ezt a verziót

Thanks, I tested it, it's fine, the movement of the servos is no longer jerky.

**Comment by jufelap** [comment]
> Visszaküldtem a jeladómat. Pimaszság az frsky számára, hogy ilyesmit dobjon a piacra. Ha a nagyokkal akarsz pisilni, akkor szállítani is kell. Ebben benne van a Hf firmware is! amelyet az ügyfélnek nem kell először tesztelnie. Nagyon tisztelem önt, amikor fejleszti a szellemiségét, nagyszerű, amit ilyen rövid idő alatt elért. Lehet, hogy az frsky újra felébred, mielőtt még 10 olyan adót dobnak piacra, amelyek még nincsenek készen.

Unfortunately, I have to agree with you on this. :-(
That was just a small problem. There are many more and more serious problems than this. But don't think that this doesn't happen with other types of radios. It happens to almost everyone, it just doesn't get so public on the internet. In my opinion, even the Jeti is no exception to this. However, it is likely that such problems are much less there. Although it is a completely different price category. But the cheaper price does not exempt FrSky. And now FrSky can no longer be called a cheap category.
However, its development is outstanding, the fact is that the users are the test subjects :-(
