### ISSUE TITLE
X20 / Ethos with ext. ELRS module PWM error

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2957]
During setup of a glider with X20 and ext ELRS module I found a strange PWM behavior 

X20 Ethos 1.4.12 
Vantac ELRS module ELRS 3.3.0
Radiomaster ER8G ELRS 3.3.0
ELRS 3.3.0 LUA
Switch configuration 100 Hz Full Res 8 CH

For servo setup the CRSF extended limit is -120% to 120% with 885 µs to 2115 µs.

When I setup the channel range to -120% to 120% the measured PWM timing looks correct, also down to -121.2% the PWN signal stays at 883 µs with a certain measurement tolerance (see picture 1).

When I set the channel range to -121.3% the  PWM signal suddenly changes from 885 µs to 2120 µs , from the min. PWM to the max PWM (see picture 2). This behavior is reproducable. I also have the same behavior with different components,  external ELRS module BetaFPV nano TX and BetaFPV receiver SuperP 14CH.

Using the same components tx module and receiver with a Radiomaster TX16S this behavior does NOT come up and the PWM signal stays stable within the CRSF extended limits. Thus it looks like to be a X20 / Ethos issue.

![PWM -121-2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/50028fbb-8209-4f80-bf0d-2eb0ba384001)

![PWM -121-3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/2e9f63e1-6d1f-4673-b789-a0c21820d68d)

**Comment by bsongis-frsky** [comment]
Overflow in calculations!
