### ISSUE TITLE
Proposal to have a lock screen function

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#2958]
As proposed on RCgroup thread it would be nice to have the possibility to lock the touch screen and/or the programming buttons.

Personally while flying, I change screens by pressing the "change page" button and it happens I hit accidentally MDL or SYS or DISP.

One proposal would be to have a freely selectable input to activate deactivate the lock function.

Second possibility could be pressing simultaneously the "Change page" and "Confirm" button for approx. 1 Sec.
Disabling the lock achieved the same.

Advantages:
First one: flexibility of user by model or global.
Second one: global and no need to program

Why not having the two options available?

**Comment by Lefish63** [comment]
Good idea.
Gets my vote. 

Dave

**Comment by i3dm** [comment]
good idea

**Comment by aalain8** [comment]
The same thing as:  https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/947

I am obviously in favour.

**Comment by bsongis-frsky** [comment]
There will be 2 methods to lock the touch screen:
1) Press simultaneously on [ENTER] and [PAGE] during 1 second on the Home screen
2) Use the Special Function "Lock". This special function can be global (provided the chosen condition can be global)
Both cases the small "lock" icon will be displayed in the Top bar

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/675039d0-4daf-4670-b506-9fefb4362ed4)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c6777741-4aeb-4455-9f07-e4d1dbc05fda)

**Comment by bsongis-frsky** [comment]
Thanks @Eagleowl1 for giving the idea of the double system ;)

**Comment by Eagleowl1** [comment]
Thanks Bertrand for this very quick and nice implementation.

Just to make sure: in locked state, would it still be possible to browse the different screens by pressing the "PAGE" button or possibly by sweeping the screen as today?
