### ISSUE TITLE
With glider template Thr=>Ele mix does not use Source from Throttle Mix

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#2963]
X10S on 1.4.12  
Changed Source to LS on Throttle mix.
Added The=>Ele mix. The Source is Throttle stick, not the Source of the Throttle mix. With  no way to change the Source, this mix is unusable.

**Comment by bsongis-frsky** [comment]
Fixed with #3195 in 1.5.0
