### ISSUE TITLE
Logical switches with one decimal place, Ethos 1.5.0

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2964]
Hello,
The basic arithmetic method of dividing results in values with at least one decimal place at the corresponding point as well as in the mixers and in the telemetry. Unfortunately, logical switches can only evaluate integers. Especially with the function A = X, only integers can be evaluated. If necessary, one has to fall back on A ~ X, whereby the accuracy is completely lost. It is therefore time to be able to set values with at least one decimal place.

**Comment by azaz44** [comment]
I think comparing floating point numbers (or real numbers) with equality is always a problem. It can really only work with integers.

For real numbers, like in your case, "Range" should be the answer. Does "Range" allow to give real numbers with more precision?

**Comment by Wolepo** [comment]
A logical switch with the function A = X does not calculate anything, but only becomes TRUE if the conditions match. I cannot imagine that this can cause problems.

**Comment by strgaltdel** [comment]
Hmm,

maybe i dont get your point

A=X allows decimals
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/49f27610-39de-43f3-a456-216aab28bf6c)

would say it depends on the number of decimals "configured" in the source

**Comment by Wolepo** [comment]
Let's look at the pictures:
from Wars:
![Wert1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/243d140f-ba00-440b-a667-7215e75fc697)
![Wert2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/6d9e35d5-470c-4b41-b1f7-86caea40cd84)

From Mixer:
![Mischer1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/a02b67e3-46b2-4477-a9fe-05d57e273656)
![Mischer2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/d46b1cba-3930-4aa3-a56d-2e813670f8c4)

**Comment by azaz44** [comment]
> A logical switch with the function A = X does not calculate anything, but only becomes TRUE if the conditions match. I cannot imagine that this can cause problems.

Actually this always causes problems. But in this case with limited decimal places it will work fine. And It looks like you have the point, there are some issues in Ethos to fix.

**Comment by Wolepo** [comment]
Although already 90 days old, the problem is still not solved. A logical switch with the function A=X still cannot process the decimal place in the VARS.

**Comment by Wolepo** [comment]
Hello,
the logical switches with the functions A<X, A=X and A>X in 1.5.0 pre-release still can't handle the commas in the vars. only whole numbers can be selected.
