### ISSUE TITLE
Channel order per model instead of global

### ISSUE THREAD

**Issue by mszulen** [FrSkyRC/ETHOS-Feedback-Community#2967]
Currently, the channel order (RETA, AETR etc) is defined in the STICKS menu and is global.
It would make it more flexible, if this could be setup on "per model" basis too (like override option for example).
I've found this inconvenience when setting up a model with FlySky receiver, where I can't change it's pre-defined channel order.

**Comment by mawzthefinn** [comment]
The 1.5.x Wizard allows you to override the channel layout on model creation, for all functions, not just the 4 base ones.

**Comment by mszulen** [comment]
That's a great news! Thank you! :)
Can't wait for the more stable release of 1.5 then.
