### ISSUE TITLE
Pitch and roll offset

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2968]
I have an Archer SR 10 Pro and an SR10 Plus. After running calibration, apparently because of a slight misalignment with the axis of the plane, they are showing Pitch and Roll about one degree off. I was looking for some way to offset those values, but I was not successful. Using the Aileron and Elevator Offset is kind of a guesstimate to make what it should be something simple. Am I missing something?

**Comment by Wolepo** [comment]
You can set an Ofset for each axis and gyro state. For me it is the aileron in automatic mode. Unfortunately, the installation position is currently not saved correctly during the self-test. However, FrSky is supposed to be working on this.

**Comment by Richrfl** [comment]
Thank you for your response, but as I said seems to me like a guestimate approach. I will create a new telemetry DYI device offsetting the P and R and use them as my references. Is there a request for the developers to fix that issue?

**Comment by mawzthefinn** [comment]
This seems to be the same issue you opened as #2975 

That has more detail, so I'm closing this off in favour of that one.
