### ISSUE TITLE
x20 pro 900 mhz telemetry not working correctly

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2970]
I recently got a x20 pro great hardware.  I am not getting any telemetry (900mhz) other than rssi and rxbatt. same model works fine on my x20s.  tried everything i could think of, reset receiver, reset bind, share.  
  receiver                   R9 sx
   telemetry sensors  gps
                                  fas 100

**Comment by williajgr** [comment]
firmware 1.4.12

**Comment by bsongis-frsky** [comment]
Sent to the tests team, it's strange

**Comment by FrSky-GX** [comment]
It is a bug of RF fw, we will update the internal module fw soon.

**Comment by williajgr** [comment]
any update on when this fix will be in the RF firmware update.?  can't use the new radio on some of my models until this is fixed.

**Comment by williajgr** [comment]
any update on when this fix will be in the RF firmware update.?  can't use the new radio on some of my models until this is fixed.

**Comment by williajgr** [comment]
well soon is long past  any possibility this will ever get fixed?  this is a fairly big bug.

**Comment by mawzthefinn** [comment]
TS ISRM Pro v1.0.12 was released at the end of last week.

**Comment by williajgr** [comment]
TSent from my iPhoneOn Nov 20, 2023, at 2:05 PM, mawzthefinn ***@***.***> wrote:﻿
TS ISRM Pro v1.0.12 was released at the end of last week.

**Comment by williajgr** [comment]
Thanks, that did the trick. Don’t know how I would have known it was fixed if I didn’t hear from you.Sent from my iPhoneOn Nov 20, 2023, at 2:05 PM, mawzthefinn ***@***.***> wrote:﻿
TS ISRM Pro v1.0.12 was released at the end of last week.

**Comment by mawzthefinn** [comment]
Glad to hear it's sorted
