### ISSUE TITLE
New x20 Pro text to spesch not working correctly

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2971]
If i want it to say lights off   i have to type in lightsoff other wise it says lights  o  f  f

**Comment by BladeScraper-Designs** [comment]
Are you capitalizing everything?  It is my understanding that it reads all caps (e.g. OFF) as individual letters like an acronym, and lower case it reads as the word.

**Comment by williajgr** [comment]
firmware 1.4.12

**Comment by williajgr** [comment]
thanks ,ok first word can all be  all caps but after that it has to be nocaps to have multiple words. keyboard kind of forces you into caps if one is not paying attention.  and if one doesn't leave any spaces with caps it will make up sentences.  i think it is a little odd.
if one wants individual letters than leaving spaces would make more sense.

**Comment by BladeScraper-Designs** [comment]
Yes the keyboard behavior is a bit odd I agree.  But now that you know, as long as you pay attention, I believe the TTS should work correctly.

**Comment by williajgr** [comment]
Yes it does work now. I will close it. Thanks for the help.Sent from my iPhoneOn Oct 13, 2023, at 7:10 PM, Keith ***@***.***> wrote:﻿
Yes the keyboard behavior is a bit odd I agree.  But now that you know, as long as you pay attention, I believe the TTS should work correctly.

**Comment by williajgr** [comment]
this is a solution to the problem but i think some more work needs to be done on text to speach

**Comment by bsongis-frsky** [comment]
FIY it is a dedicated chip which does the TTS. Ethos can do nothing to improve!
