### ISSUE TITLE
Flight modes fade times coming from a source

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2974]
Could we have Fade-in and fade-out values come from a 'source'?

Where it would be useful is RC Helis, where a very slow change between modes (and including RPM) is used as an artistic effect. Having a switch to change the fade time between slow and high would be beneficial.

![20231014_093407](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/618146e3-c4f3-44c6-bf97-f548d6301495)

**Comment by bsongis-frsky** [comment]
Available in nightlies tomorrow
