### ISSUE TITLE
SR10 pro and SR10 plus incorrect Pitch and Roll readings after self check

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2975]
Gents, these two parameters that can be used for different functionalities, are quite off (the sr10 plus indicates a 12degrees roll when leveled, and the pro makes it about 6). Please, have them corrected, or otherwise add a P and R offset parameter, or have the transmitter create a telemetry calculated sensor where a number can be inserted in a Custom function.
Thanks a lot, and if I am missing some parameters to correct this issue, please, let me know.

**Comment by Wolepo** [comment]
This will not work! After the self-test, you have to set the offset separately for each model. Something like this is unsuitable as a template.
I proceed as follows: after aligning the model, I carry out the self-test. Without touching the model, I then switch to automatic mode and check which rudder is moving. I then set an offset for these rudders in small steps until nothing moves when I switch over.
![Offset](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/33443303-712e-4a2c-9698-dd40ac4a6a2a)

**Comment by Richrfl** [comment]
I do not clearly understand what you mean by "this will not work", nor what do you call "model", considering that each aircraft model has it own receiver, and therefore it is obvious that each model will have different settings. About the "will not work", if you mean setting an offset parameter, that is something that any off-the-shelf gyro has that capability, and that works. Anyhow, you are addressing the walk-around that I am not interested in, considering that I need P and R for other purposes than Auto-level. On this particular issue, I will come back to this thread hopefully next weekend after I do some field tests because I think that the way the auto-check works is to record the accelerometers values and use them as a reference to correct the attitude of the plane while in Auto.
