### ISSUE TITLE
Replace Neuron Blheli32 setup on browser with Device Config

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#2981]
Enhancement Request

Replace the Neuron Blheli32 setup normally done on a browser with a Device Config setup form so that it can be configured on the radio. You don’t want to lug a pc to the field for this.

**Comment by mawzthefinn** [comment]
BLHeli32 firmware doesn’t allow for this IIRC, once it seems any control signal it blocks out configure. It also configures over the pwm/s.port wire.

I beleive this is a major reason why FrSky abandoned use of BLHeli32 on the Neuron2’s.
