### ISSUE TITLE
ls and rs directions opposite x20s.

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2982]
ls and rs directions opposite x20s. this is confusing when i go from the 20s to the 20 pro

**Comment by mawzthefinn** [comment]
Each are setup for the long lever's default position being up for 100 and down for -100, but the X20/X20S have the long lever facing towards the radio's frontface, while the X20 PRO has the levers facing the opposite direction (long to the back) by default. 

Definitely can be confusing. This does seem to keep changing (the X18 is different as well)

**Comment by williajgr** [comment]
I would rather they were all the same.  With access it is very easy to Switch radios quickly, and I do switch often. Forget which radio controls which plane.      Joe Sent from my iPhoneOn Oct 18, 2023, at 2:19 PM, mawzthefinn ***@***.***> wrote:﻿
Each are setup for the long lever's default position being up for 100 and down for -100, but the X20/X20S have the long lever facing towards the radio's frontface, while the X20 PRO has the levers facing the opposite direction (long to the back) by default.
Definitely can be confusing. This does seem to keep changing (the X18 is different as well)

**Comment by bsongis-frsky** [comment]
Yes obviously this option is needed

**Comment by williajgr** [comment]
That sounds like a good idea. If they don’t do something like that I will probably rewire the pot on my pro.Sent from my iPhoneOn Oct 19, 2023, at 8:45 AM, mawzthefinn ***@***.***> wrote:﻿
Agreed, I move between different radios so much that it gets me regularly. I actually did a hardware mod on my X18 to address, but a similar mod on my PRO is a bridge too far.
I'd love to have a 'reverse slider direction' setting in System->Hardware

**Comment by LTabora** [comment]
I was asking about this today as I switched my side slider levers from the back to the front on my X20 Pro. Like you have all noted, this requires the direction of the input to be reversed, which can be a PIA when you're switching between an X20S and the X20Pro. 

I think there should be an option to change this via software, as it can lead to significant failure if overlooked when swapping radios.

**Comment by mawzthefinn** [comment]
The option is in system->hardware->pot/sliders settings as of 1.4.14
