### ISSUE TITLE
XE Upper Display Issue After Updating to 1.4.13

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#2983]
I have the upper display showing the Throttle Analog Position. After updating my XE to 1.4.13 the bottom half of the upper display flashes from light grey to dark gray with "Dark Mode" Off.  With "Dark Mode" On, the bottom half of the display flashes green.

**Comment by bsongis** [comment]
If you return to 1.4.12 everything becomes OK again? I have no change in mind which could explain that difference!

**Comment by df7320** [comment]
Yes, Going back to 1.4.12 and corrects the issue.  I downloaded the again and installed 1.4.13 and the flashes/flickers starts up.  If I put a picture in the upper display then it is fine.  It only seems to happen when I select "Analogs" and a stick  and then operate the stick thru it's range.

**Comment by bsongis-frsky** [comment]
Would you please share your model file? We are not able to reproduce your issue!

**Comment by df7320** [comment]
[ov10a01.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13043414/ov10a01.bin.txt)

**Comment by df7320** [comment]
This the same issue as,  upper display flickers, XEs #2271

**Comment by bsongis-frsky** [comment]
Again I cannot replicate it :(

**Comment by bsongis-frsky** [comment]
Yes I can reproduce it!

**Comment by bsongis-frsky** [comment]
Fixed. Please have a look to the Nightlies 1.4
For now it is almost the only fix above 1.4.13
