### ISSUE TITLE
Hf Firmware Problem X20pro 

### ISSUE THREAD

**Issue by Boxxxer64** [FrSkyRC/ETHOS-Feedback-Community#2985]
Receiver TWGr6 with 1.05 firmware servos run jerkily. With firmware 1.03 everything works normally. transmitter x20pro. No newer HF firmware available for x20pro.

**Comment by Boxxxer64** [comment]
Look like same here #2952

**Comment by mawzthefinn** [comment]
Yes, duplicate of #2952 

Please continue discussion there
