### ISSUE TITLE
V-Tail configuration change implies deleting all mixers

### ISSUE THREAD

**Issue by 3frcg** [FrSkyRC/ETHOS-Feedback-Community#2986]
I need to clone a very complicated F5J glider model with V tail to another classic tail configuration.  Changing the tail configuration leads to delete all mixers. Maybe maintaining the V-tail selection and cheating the outputs would be a way to circumvent the problem. 

I'm wondering if another solution would be possible, including the ability to change the tail mode settings without losing the mixers in a new release.

Thank you

**Comment by mawzthefinn** [comment]
If it's a classic single-servo tail, just edit the Elevator and Rudder mixers to be 1 output and ignore the Edit Model settings.

You only really need to reset mixers if moving from a V-tail to a dual-channel rudder setup because of the difference in how the second rudder channel is applied.

**Comment by 3frcg** [comment]
I just did it this way. Thank you.

**Comment by 3frcg** [comment]
Anaycase I suggest the enhancement option of clone separately Filght Modes, and Mixers, not only the complete model. Refer to : https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2750

**Comment by mawzthefinn** [comment]
#2750 is referring to being able to clone a single FM like you can a Mixer. 

I believe what you are asking for is to make a model which clones only FM and mixers, not the rest of the model.

**Comment by 3frcg** [comment]
Correct. Only FM and/or Mixers
