### ISSUE TITLE
Ethos suite fails to update

### ISSUE THREAD

**Issue by CliffEvans** [FrSkyRC/ETHOS-Feedback-Community#2989]
Have tried several times now but Ethos Suite keeps failing to update to the latest version.

![Screenshot (41)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/18718856/ba90d4fc-ac4a-42a5-8a92-02cf7d0f2f95)
![Screenshot (40)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/18718856/85bffb84-837b-42dd-9557-8490f290a4b2)

**Comment by jbule1980** [comment]
Same thing here! Failed to update the suite! 
![Captura de pantalla 2023-10-20 185519](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81538757/b26ee6ac-3101-48fc-86cb-889d8f988d7e)

![Captura de pantalla 2023-10-20 185532](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81538757/c79c8608-abcb-47ec-aec2-6c9e5c471883)

I though that I was the only one experiencing this problem!

**Comment by kramgrand** [comment]
Likewise I tried to do the update and very quickly quit it as extremely slow.  
Instead I downloaded the Ethos Suite package .dmg  Image for Mac and installed the s/w again.  Took seconds..
Am guessing anyone running Windows can do the equivalent and run the .exe

**Comment by Nicholas-Luoyi** [comment]
- As written in the description of 1.4.13. The fix will work when you update from 1.4.13 to a new version.
- For now. Please try to cancel the update on the App start up. And switch the server location to Github then manually click the button "Check for updates" in Suite settings.
