### ISSUE TITLE
Firmware won't update from 1.4.12 to 1.4.13

### ISSUE THREAD

**Issue by Jammo1** [FrSkyRC/ETHOS-Feedback-Community#2990]
Computer Screen goes to waiting for disk, then Missing Drive look at the FAQs.

Updates used to be easy now they are a pain in the butt.

**Comment by Jammo1** [comment]
Tried to update after updating Ethos Suite. Seems you need to close Ethos after the update and then it will see the radio.

**Comment by JoseAltea** [comment]
Hello, good evening, this happens to me too. ism and it doesn't let me update, it keeps waiting for the disk and gives an error, my computer is a Mac updated to the latest version.

![Imagen 27-10-23 a las 21 07](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/123797860/d10b81f5-abb8-46a7-9cee-92ed4e29c6ab)

**Comment by robertoalmeida** [comment]
I'm also having the same problem. My ethos suite is on version 1.4.13 and the radio is on 1.4.12.

<img width="944" alt="erro_x20" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4574415/7e44cbfa-e29d-473e-8bb8-5a7904b41ed6">
