### ISSUE TITLE
X18s ethos elrs module and lua

### ISSUE THREAD

**Issue by Holypug** [FrSkyRC/ETHOS-Feedback-Community#2991]
Hi. I bought a gemini tx elrs module.
Anyone here that use the same?
will it work correctly? 
thanks

**Comment by m0p3d** [comment]
Did some experiments with dual Rx flashed to tx (Super D betafpv+ stepdown Module for power) connected as external module.

In Gemini Mode disconnects occured- reconnect took long or was not possible . Some took more then 40min wait time. In combination with the tx16 the same setup worked without the disconnects.

I can not answer your question but would suggest to ground test your setup for several hours before flying.

**Comment by Holypug** [comment]
I hope developers will work on elrs lua to improve it in the good way

**Comment by mawzthefinn** [comment]
The ELRS Lua is an example provided by FrSky for the community to extend and develop as needed. While bugs will be addressed by the developers, extending capabilities really requires a group in the community to undertake developing the scripts further.
