### ISSUE TITLE
"Cross Trim" incomplete/improvements

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#2993]
Trims are actually an additional source to a mix such as Aileron, Elevator, Rudder, not an adjustment to the stick associated with the mix.
So, change the naming from "Stick Rudder" to "Rudder", etc.
Changing the source of a Throttle mix, breaks trim.
Cross trims only work when exchanging trims. For example; Elevator=>Trim Rudder and Rudder=>Trim Elevator.
Permit the assignment of a trim to Flaps
This key for sailplanes that typically put flaps on throttle stick and motor on left slider.

**Comment by mawzthefinn** [comment]
Stick Rudder et al denote which switch is in use (the one next to that stick). This is used because these are determined by radio mode setting + physical location, not by physical location. Otherwise they'd just be named T1-T4. This has been discussed in the past.

Cross trims work fine. The example you are showing works correctly when I test it. 
You can even assign two controls to one trim function and have both work. 
Please describe exactly what you are seeing that isn't what you expect. Cross trims is specifically for exchanging trims, but the ETHOS implementation is more flexible than most implementations and can assign any trimmer to any trim function. Unlike OTX, Low position trim works correctly with cross trims.

Throttle Trim is broken if another source is used - I've opened #2995 for that issue. 

Please define exactly what you want trim in flaps to do? It's not there largely because nobody has defined a use case for it than isn't better achieved by adjusting a VAR for position. Everybody who does use trim for flaps does it a little differently and the current solutions allow you to build your own implementation.

**Comment by fhpage** [comment]
What did you use to test?


On Sun, Oct 22, 2023, at 12:57 PM, mawzthefinn wrote:
> 
> 
> Stick Rudder et al denote which switch is in use (the one next to that stick). This is used because these are determined by radio mode setting + physical location, not by physical location. Otherwise they'd just be named T1-T4. This has been discussed in the past. *My point was to clarify whether trims are associated with stick or mix. The throttle stick can be used as source for flaps. Should the throttle trim follow the throttle stick or the throttle mix?*
> 
> 
> Cross trims work fine. The example you are showing works correctly when I test it.
> You can even assign two controls to one trim function and have both work.
> Please describe exactly what you are seeing that isn't what you expect.
> *Example 1:**
*
> *Stick Rudder    Trim Rudder**
*
> *Stick Elevator   Trim Elevator**
*
> *Result: Neither trim works.**
*
> 
*Example 2. **
*
*Stick Rudder  T5**
*
*Stick Elevator  Trim Throttle**
*
*Stick Throttle   T6**
*
*Stick Aileron   Trim Rudder**
*
*T5                 T5**
*
*T6                  T6   (these two make no sense)**
*
*Result: Nothing works!**
*
*This is with an X10S 1.4.12**
*

**Comment by mawzthefinn** [comment]
I just setup the example you provided.

Radio is Mode 2, Default model (2 ail, 1 ele, 1 thr, 1 rud, 0 flaps), Free mix with Source T5 out to channel 6, second withs Source T6 out to channel 6. Low position trim enabled for Throttle mixer (but default input on Throttle)

Going through line by line. Remember left side of the screen is the switch, right is the trim function it's assigned to. 

Stick rudder (T4 in Mode 2) assigned to trim function T5 -> Adjusts Channel 6 as expected
Stick Elevator (T2) assigned to trim function throttle -> Adjusts throttle as expected (this would not work with an alt throttle source selected as discussed)
Stick Throttle (T3) assigned to trim function T6 -> adjusts Ch7 as expected
Stick Aileron (T1) assigned to trim function Rudder -> Adjusts rudder as expected
T5 assigned to trim function T5 ->  Adjusts Ch6 as expected
T6 assigned to trim function T6 -> Adjusts Ch7 as expected.

**Comment by fhpage** [comment]
You explanation clears up some of my confusion:
"Stick Rudder" means the default trim switch associated with the Rudder stick...yes?
So, a cross trim, "Stick Throttle" => "Trim Elevator" means  T3 trims Elevator.  .. (mode 2) yes?
Would be helpful if could un-assign a trim switch.
"Stick Elevator =>   "---"
Thank you...

Did your test with ETHOS 1.4.x or a 1.5 nightly?
I set up the model you described on 1.4.12 with X10S.
You have two free mixes on channels 6 and 7.
I have never seen Trims work on a Free Mix. And your example did not work for me:
"Stick Throttle (T3) assigned to trim function T6 -> adjusts Ch7 as expected"  - did not work
"Stick rudder (T4 in Mode 2) assigned to trim function T5 -> Adjusts Channel 6 as expected"  - did not work.
Another example on a simple model with no cross trims, create a Free Mix with source Ail, there is no trim...
I have always added a Trim Mix to same channel as Free Mix to enable trims.

**Comment by mawzthefinn** [comment]
Yes, Stick rudder means the default trim switch associated with rudder, so T4 trims elevator  (T3 is the default throttle trim)

You can unassign Trim functions in 1.5, but not in 1.4. This is done in the mixer, not the Trims setup.

My free mixes use Trim->T5 and Trim->T6 as the source for the two mixes. Y

ou can trim a free mix in recent ETHOS versions, but that's done by setting the Offset to Use a Source then assigning the trim function as the source (ie Trim->T5). 

My normal method of adding a trim to a Free mix has been to use a second Free mix with the trimmer as the source. but the Offset function getting Use a Source as an option has made that obsolete. 

I only used Trim mixes when I needed to use T1-T4 and am using Canned mixers, as disabling those mixes in 1.4 and earlier disables the function entirely, so you need an alternate function which the Trim Mix supplies.

**Comment by fhpage** [comment]
With regards to the "information needed":
I was looking for a method to easily add trim to flaps using just the mixes provided with the "sailplane" type (FLAP, CAMBER, etc). 
If trim was available with the "Flaps" mix. One could set the camber values with Camber mix and be able to make minor changes in flap position with trim for each flight mode. I realize one could just add a trim mix to get the job done. But that's not the objective of my request. 
Clearly one can do a comprehensive F5J or F3J program (when 1.5 is released...) using just the basic mixes: Free Mix, Trims, Offset, Throttle, and 1.5 VARs.

**Comment by mawzthefinn** [comment]
You can already do that today. 

Add a Camber mix with a trim function as the source (such as T5). Set that trim function to Flight mode specific and you will be able to use it to adjust camber per flight mode. Then add a second Camber mix with a variable input for the flight modes you want to be able to adjust camber with a slider.

**Comment by fhpage** [comment]
Tried your suggestion.  You can set the one Camber mix with T5 as the source to be active with multiple flight modes. For example can use as primary adjustment for modes like launch and speed, plus minor adjustment for cruise. Any major adjustment to the flaps for neutral can be done with an Offset mix. Many pilots like to use LS on Thermal Mode...
But, if you add aileron and elevator outputs to the Camber mix things fall apart. T5 is adjusting everything. Not just the flaps. 
I was trying to come up with a way to trim flaps in multiple flight modes without using a Trim Mix. This is not something I need. Was looking for a way to minimize work for those not familiar with the OpenTX, Ethos Free Mix paradigm. 
Need to revisit Camber mix and Flaps mix.

**Comment by mawzthefinn** [comment]
There's a selectable number of outputs for the Camber mix. Set it to 2 Outputs and the two outputs being the flaps channels if you just want to adjust the flaps. 

Or just use a second Flaps mix setup the same way, with a trimmer as a source.
