### ISSUE TITLE
Free mixer 1.5.0 +........add is partially missing

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2994]
Free mixer 1.5.0 +........add is partially missing

+............add is only possible with weighting and curve.

With differentiate, offset or slow the possibility is missing.

Greetings Eugen

![Info](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/5ef967d6-83d7-4e1a-9176-1e88815a7552)

![Gewichtung](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/a2dc4244-fb23-414f-bf6d-abec7341caf7)

![Kurve](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/085e37a4-8446-4b0b-ac40-82ac403c2d17)

![Differenzieren](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/ccbfedfc-2518-44f2-8a9e-1db0e8eaeeac)

![Offset](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/0d642190-7d4d-40a7-9a1c-d00d78d802b3)

![Slow](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/3989129d-7792-4319-bafe-5256885921d4)

**Comment by mawzthefinn** [comment]
Yes, this is normal, and is to generally simplify things. It's consistent with the older implementation

If you want multiple selectable Differential, Offset or Slow settings, assign a VAR via 'Use a source'.

**Comment by yak55** [comment]
To me, this is illogical.
Why make something complicated when it can also be simple?

The way via VAR is a possibility - but in this case sometimes awkward!

Greetings Eugen

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6a4e742b-4f86-4f6f-bed7-e4ce751a664b)

**Comment by bsongis-frsky** [comment]
This flaw is fixed in the next nightlies
