### ISSUE TITLE
Throttle Trim Breaks with Alternate Source

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#2995]
Throttle trim is ignored, and Low-Position trim does not adjust the low idle position if enabled, when a source other than Analog->Throttle is chosen

This is an issue as there are some uses when an alternate source is useful for throttle while trim is still needed (some older ESC throttle cuts and also if setting up an old timer for virtualized no-throttle operation)

**Comment by bsongis-frsky** [comment]
Today we apply the trim associated to the chosen stick if the input is a stick. But there is no trim if the input is something else than a stick.

I think that the best option is to add a Trim selection to the Throttle Mix.

Only in 1.5.0 then.

**Comment by bsongis-frsky** [comment]
Default Trim setup
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/da626288-7edf-4a62-955a-21da2e8005b2)

Slider right + Throttle Trim setup
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ed8748f5-d780-4c42-9e6a-5031aa24c8e2)

Slider right + Extra Trim setup
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a3a046ad-fae8-4de6-8378-bde944aeb0c5)
