### ISSUE TITLE
Tandem XE, assign an audio track to a switch

### ISSUE THREAD

**Issue by JoseAltea** [FrSkyRC/ETHOS-Feedback-Community#2996]
Hello good morning. I have a Tandem XE, I installed the latest firmware, 1.4.12 EU. I am trying to assign an audio track to a switch from the special functions menu but when I go to search for the file the SD car does not detect it, the only option that appears when searching for the file is “—-“, I have a 32 GB sed car inserted into the slot. What should I do to detect it and assign the sound?
Thank you for your attention and cordial greetings.

**Comment by mawzthefinn** [comment]
Put the sound file in the correct location, which is directly in the /audio folder.

note for custom audio, you must load a set of sounds, the radio does not come pre-loaded with custom audio. An OpenTX sound pack will work if put in the correct location

**Comment by mawzthefinn** [comment]
I'm honestly not sure about the maximum supported size

However I recommend strongly to keep WAV files short, as the playing file will block further announcements until it is completed.
