### ISSUE TITLE
Emergency Mode when long pressing return while editing a curve

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#2997]
X18SE with Ethos 1.4.13

It only seems to happen when you edit a curve through a mixer, and only when you're trying to edit one of the additional curves in the mixer, not the first one. I am able to recreate it with any existing or new model.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1323809/a3c24cf3-5211-418b-909d-39bd516f91e8

**Comment by bsongis-frsky** [comment]
Reproduced and fixed
