### ISSUE TITLE
Special functions: Lock inputs

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#2998]
Hello.
It would be great to make a special function to lock all sticks, pots and switches, except the one to which this function is assigned.
This is necessary so that INav does not stop the autolauch process (by the movement of the stick), since at the time of the throw, the equipment can rotate on the strap, touching the sticks.
To solve this problem, usually the transmitter is placed on the ground. But winter is coming...

**Comment by mawzthefinn** [comment]
Make a lock type free mixer with the input and output the same, activated by the assigned function. DO this on each channel you want to lock.

**Comment by bsongis-frsky** [comment]
Yes. I don't like too much to add such mixer functions inside the special functions.
The lock is there for this reason
