### ISSUE TITLE
Ethos Suite failed to format X20 Pro

### ISSUE THREAD

**Issue by gordonchenyx** [FrSkyRC/ETHOS-Feedback-Community#2999]
Tried restarting the computer, reinstalling ethos suite, and changing the usb port and cable, none of them solve the problem.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/70631110/ad3b9334-35d3-420b-9927-dc43423fb2a5)

edit:

Also it is unable to switch to bootloader in repair tool tab (but it can in the ethos tab).
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/70631110/4318fc3f-a57f-4d1e-b9cc-5612c69c1c7d)

edit2:

I am unable to copy any audios or lua scripts, nor deleting the unwanted stuff from or to the radio storage. Please fix this issue soon as the radio is pretty much at an unsuable stage.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/70631110/3d09a67c-26f6-4c24-86fa-8cbeaf77c57d)

**Comment by bsongis-frsky** [comment]
It is a bug in X20 Pro bootloader
