### ISSUE TITLE
OpenTX-like visual style 

### ISSUE THREAD

**Issue by andika207** [FrSkyRC/ETHOS-Feedback-Community#3]
I am tired of the uncolored icons ! if openTX is not supported why did you copy the same boring visual style ?
I have tried to change the color of some icon bitmaps but it doesn't make any effect on the simulator.
So I suspect I would need to get access to the source code to achieve this.
Hopefully the final release of ETHOS comes out with nice color icons or a color palette for manual selection

<a href='https://postimg.cc/FkyMzyq1' target='_blank'><img src='https://i.postimg.cc/FkyMzyq1/screenshot-4.png' border='0' alt='screenshot-4'/></a>

**Comment by brainbubblersbest** [comment]
Because it's opentx under the hood. It just uses another pcb Layout. Im sure.

**Comment by Adelaxie** [comment]
@brainbubblersbest Im sure you are not sure! happy flying.

**Comment by bsongis-frsky** [comment]
We have a new UI in mind, but it won't look like your screenshot which is just horrible :)

**Comment by andika207** [comment]
@bsongis-frsky j'ai pris quelques couleurs aléatoires, mais c'est bien mieux que d' avoir des icones moches du style W10 où l'on perd plus de temps à trouver ce que l'on souhaite.  

à propos du style, le fait d'avoir des menus cachés partout sous une flèche blanche bin ça devient agassant et c'est pas trop pratique

il suffit de jeter un coup d'oeil sur Futaba avec des écrans à resolution plus petite ils ont réuissit à tout afficher dans une même fenêtre et c'est bcp plus intuitif avec des ''templates'' en miniature

dailleurs sur ETHOS il y a quelques pages avec des menus avec des gros buttons-rectangles du style Futaba et j' aime bien

facebook utilise un nouveau design depuis quelques mois et putain de bordèle, c'est un vrai casse tête et je ne trouve pas le moyen de m'habituer.

je sais que vous êtes capable de tout faire, il faut juste prendre le bon choix.
