### ISSUE TITLE
La fonction Airbrake ou Camber est difficile voire impossible à implémenter 

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#30]
Horus X10 + ISRM  -  Ethos 0.0.17
La fonction Airbrake ou Camber est difficile voire impossible à implémenter 

Exemple : Si avec camber on souhaite programmer une fonction de courbure -ailerons + volets + compensation à la profondeur-  
                   actionné par un slider ou inter on est bloqué par une courbe unique et le subtrim de 80 % sur les volets n'aide pas.

Bien sûr, j'arrive à faire cela avec des entrées séparées à l'aide de mix libre, mais à quoi serviraient les mixeurs prédéfinis ?

Dans le mixeur Airbrake ou Camber il est possible de régler indépendamment des débattements maxi en % sur chaque sortie voir photo 1.
Un appui long sur cette zone permet aussi de choisir une source.... Mais ne résoud pas mon problème.

Si cela est possible : il serait plus facile d'avoir à la place de la valeur unique, 3 cases pour rentrer les débattements :
                                    - haut - moyen - bas - pour chaque sortie, voir montage photo 2.

Cela créerait des courbes dédiées sur les sorties et surtout les réglages de tous les débattements seraient sur la même page,
cela simplifierait la fonction pour l'utilisateur.

PS. Premier vol effectué ce weekend avec un avion mousse et un archer S8R pro tout s'est bien passé.

Merci. Alain
![Ethos1](https://user-images.githubusercontent.com/64332717/113558292-ad340a00-95ff-11eb-8400-9b88ba27290d.jpg)
![Ethos2](https://user-images.githubusercontent.com/64332717/113558297-b1602780-95ff-11eb-8409-f453bc6f4773.jpg)

**Comment by mawzthefinn** [comment]
Are these issues still being encountered with the introduction of the Offset mix and changes to Butterfly/Crow mixers in 1.3.0 and later?

**Comment by aalain8** [comment]
I am now in 1.4.3 

The Offset and Airbrake mix are very good.
In my opinion Airbrake should have another no ex: offset plus

To be able to use only one "Camber" mix I still miss a separate curve for ailerons and flaps.

My way of programming has evolved since 1.3.0 but I prefer to use the predefined mixes.

**Comment by mawzthefinn** [comment]
Can you describe what you mean by 'Offset plus', do you mean multiple offset positions?

You can do that today via setting the Offset to Use a Source and reading offset values from a VAR mixer.

I agree with having separate curves for ailerons & flaps in Camber, that would be a nice improvement.

**Comment by aalain8** [comment]
Sorry but I use "Deedl translation".

Offset and airbrake are both offsets, airbrake has additional options.
I mean the non Airbrake is wrong because in French Airbrake can be confused with Butterfly .

**Comment by mawzthefinn** [comment]
Ah, I understand. It's a localization issue, because Aerofrein can be read both ways.

I'm assuming here that Papillon is not generally used for Butterfly or Crow mixing by many French pilots (it sounds to me like a direct translation of the English term rather than a proper localization)
