### ISSUE TITLE
DATA IDs

### ISSUE THREAD

**Issue by robertoalmeida** [FrSkyRC/ETHOS-Feedback-Community#3000]
In discover new sensors I already saw that the sensors have different ids, example:
0x0300 - FLVSS_CELL_DATA_ID
0x0A00 - ASS_SPEED_DATA_ID
0x0200 - FCS_CURR_DATA_ID

Where can I get a list of all ethos standard "data ids"?

**Comment by glipski50** [comment]
Ethos Manual -> Smart Port Telemetry -> Physical ID

**Comment by robertoalmeida** [comment]
> Ethos Manual -> Smart Port Telemetry -> Physical ID

What is the website for this Ethos manual?

**Comment by strgaltdel** [comment]
i'm pretty sure Ethos use same IDs like oTx,
so you could look into it's code on git

would search for the frsky telemetry related code file
