### ISSUE TITLE
Inactivity alarm not working

### ISSUE THREAD

**Issue by isfield9** [FrSkyRC/ETHOS-Feedback-Community#3001]
The inactivity alarm on my X20S is very intermittent in working. With the time set to 1m rarely activates. With the screen sleep set to 15s and keys only, it dims the screen but when sticks are selected it wakes up frequently. I have calibrated the sticks and gyro several times and the problem still persists. I have checked the ADC and the outputs flutter less than 10 on the last digits. It appears to be the flutter from the analogues that prevent the inactivity alarm from activating, could you make the wake-up threshold larger. firmware is 1.4.13 EU

**Comment by bsongis-frsky** [comment]
Will do

**Comment by bsongis-frsky** [comment]
Available in next nightlies

**Comment by isfield9** [comment]
Thanks for sorting this out.

**Comment by FlipAirboost** [comment]
The bug is still there on my x18.
Ethos 1.5.7.
Read the message only once.
No possibility to adjust the waiting time between replays.
A really useless thing if you're not there at the time of the callback!
