### ISSUE TITLE
Write logs on switch bug

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#3002]
A friend of mine gave me his X20S to add different weights on ailerons to a specific switch.

I did this but was baffled why after I toggle this switch, ailerons this not respond for about a second.

Then I discovered that this switch was being used to activate the write logs.

To don't mislead, I did not had the receiver, with me to check real hardware, but the mixer screen definitely froze.

Attached model file. 
[Model Backup.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13185641/Model.Backup.zip)

**Comment by bsongis-frsky** [comment]
The UI is updated in the same task than the logs are written. If your SD is slow, then your UI won't be updated as quickly as you would like.

Instead the Mixer is in another task and of course it will be far quicker, even if your SD is slow.

I would still try with another SD to see if it is better
