### ISSUE TITLE
Helicopter Pitch Curves can't be easily match correct degrees

### ISSUE THREAD

**Issue by ManicMiner-Es** [FrSkyRC/ETHOS-Feedback-Community#3003]
Abstract
======
As all helicopter pilots know, once the pitch curve is linked with a pitch channel input, using a blade pitch meter, it's needed to reassign the ordinate axis value to the corresponding abcissa axis, in order to achieve the correct angle of blade attack.

Issue
====
Once selected the number of curve's point, in the "easy mode" the values of each point's "ordinate axis value" is precalculated, and pilot should provide any valid "abcissa axis value"; because it's a mechanical adjust, it's needed to move the "pitch stick" to the corresponding "abcissa value", in order to get the blade moved to the current position. Once moved, and reading the value of the blade pitch with the refered "blade pitch meter", the pilot change the "ordinate value" until get the correct value.

In the way "curve editing" is designed, there is no way to move the stick to any arbitrary possition, reading at any screen position the "input source value"; of course, as courves are source or channel independent -can be used in any way-, the ordinate and abcisse values are just source-independent values. 

But in some situations, as the described, it's mandatory to fix the source -pitch stick- in the correct abcisse position, and therefore, it's needed to have any linking way in the curve editor ...

Propossals
=========
1) Add a "Reference Input" value in the curve editor, so any source can be used to move a "cross" over the curve chart in order to have a real reference of source postion -showing ordinat and abcisse values at any editing screen place-; of course, this "reference" is only valid for editing and in any way will be related with the mixing using that curve.

2) Add a new "status bar" in the mixer editor showing the "Input value" -now, only "channel" and "mixing" values are shown at the very bottom; this way will be more tedious, forcing the user to set the input position, exiting from mixin edit and moving to the curve editor for each point .... but better that tha nothing

**Comment by mawzthefinn** [comment]
This is technically a duplicate of #24 but with some good guidance on possible solutions.

**Comment by df7320** [comment]
Just a suggestion,  it would be nice to add at least one of these old issues to each new release being put out. That way these old issues would not be forgotten about. Thanks
