### ISSUE TITLE
1.5 nightly - cannot recover saved model file

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#3004]
Per Jet_Flyer's (RCGroups) suggestion, attaching model file from 1.5 nighty that I cannot recover.
[ETHOS_10-22-2023,_2-39-17 PM.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13188531/ETHOS_10-22-2023._2-39-17.PM.zip)

**Comment by bsongis-frsky** [comment]
Which model, there are 6 models in this zip!

**Comment by bsongis-frsky** [comment]
[repaired.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13209891/repaired.zip)

**Comment by bsongis-frsky** [comment]
The 6 repaired models are included in this zip
