### ISSUE TITLE
v1.5 nightly: incorrect action stack when migrating a mix from 1.4.12

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3007]
In 1.4.12, I have a setup with the following free mix

```
Curve=CV1
Weight-up= CH58
Weight-down=CH57
Offset=0%
```

_This what I would expect after migrating to v1.5:_
```
Always on: curve=CV1
Positive: weight=CH58
!Positive: weight=CH57
Always on: offset=0%
```
_This is the actual translation:_
```
Positive: weight=CH58
Always on: offset: 0%
!Positive: weight=CH57
Always on: weight=100%
```

So, the order of actions is not as expected, the curve is missing, and the last line ('weight=100%') is I think unecessary.

Also, the _Positive_  and _!Positive_ actions are not highlighted while they are active.

**Comment by bsongis-frsky** [comment]
Positive / !Positive are not highlighted because it's a special condition, a part of a curve may be using Positive while the other part may be using !Positive

Or perhaps Positive / !Positive should both be always highlighted?

**Comment by RC-SOAR** [comment]
Maybe I've misunderstood what Positive means: I thought:

_Positve_: input_value > 0
_!Positive_: input_value <= 0

**Comment by bsongis-frsky** [comment]
Yes you have understood correctly. If you look at the curve in this screen, you will see that both conditions are used to draw the same curve. Instead of a "normal" condition, where it's a different curve which is drawn, depending of this condition.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4669dffb-4f87-4bfe-af3b-1e03deab1156)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ca75885f-ae0a-42b5-9688-5fb3aa72c60b)

**Comment by RC-SOAR** [comment]
I think I must be missing something as I'm still not clear on three points:
1. if _Positive_ is the same as _input > 0_, shouldn't the action be active - and highlighted - only if the input source is actually greater than zero? 
2. What happens if the mixer has just one action: a weight with a Positive condition? Should the negative side of the curve be y=0?
3. Does Positive compare the input source, or just the result of the stack to that point?
