### ISSUE TITLE
Number size in Ethos

### ISSUE THREAD

**Issue by yolopinto** [FrSkyRC/ETHOS-Feedback-Community#3009]
Hello, no matter how much I search, I can't find a way to put the largest numbers in the timer widget, is this not possible? Despite using a large window, this is not possible?

**Comment by Wolepo** [comment]
The font sizes are fixed.

**Comment by yolopinto** [comment]
It's a shame, since flying Jets is not an easy read, I don't know if there is at least a Lua that allows it.
