### ISSUE TITLE
Make Range Check screen more user friendly

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#301]
X20 Ethos 1.0.6

Please make the Range Check screen more user friendly. There only only 2 parameters per receiver, but the current screen is difficult to decipher, especially when the values are fluctuating. It will be worse with 3 receivers, or even 4 if redundancy is used, so perhaps make it into a table?

![screenshot-2020-05-19-40999](https://user-images.githubusercontent.com/26259987/119210966-9df51700-baee-11eb-8e1c-3644188dafa7.png)

**Comment by MIKE-DAILEY** [comment]
> X20 Ethos 1.0.6
> 
> It will be worse with 3 receivers, or even 4 if redundancy is used, so perhaps make it into a table?
> 
> )

Currently ACCESS in range check mode provides range check data for one receiver at a time on the 2.4 link and one receiver at a time on the 900m link.

**Comment by jfint** [comment]
There is only one range check button so are you saying that only receiver #1 can be put into range check?

**Comment by MIKE-DAILEY** [comment]
If you have three 2.4. receivers registered and bound as RX 1, 2 and 3.  One of the receivers will be the active telemetry receiver and its number will be displayed by the RX sensor as 0, 1, or 2.  That will be the receiver that is sending the RSSI and VFR info.  If you turn off that receiver the next receiver will become the active telemetry receiver in a priority of 0. 1. and then 2.

**Comment by jfint** [comment]
Ahh, thank you for the clarification

**Comment by MrD-RC** [comment]
The only problem I see on that screen is that **900M RX : 1** should be on a new line. It’s been tacked on the end of **2.4G RSSI : 42dB** which is confusing.

**Comment by Nicholas-Luoyi** [comment]
@MrD-RC Agree with you. This should be fixed.

**Comment by mawzthefinn** [comment]
The display error was fixed some time ago.
