### ISSUE TITLE
Frequent sensor lost warnings with ELRS

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#3010]
I'm getting a lot of sensor lost warnings with ELRS (v3.3.0). I have the telemetry rate set to standard. I do see the sensors turning red at different intervals. So it looks like not all sensors are send back over the same packet. In #2465 it was suggested that a bad flash could cause the issues. I re-flashed the transmitter and receiver. But the sensor losses are still occurring. It seems to me that there is not enough time before the sensor lost warning is issues. All the sensors come back. It just appears to me that it's potentially how the telemetry is sent, that is causing these unnecessary warnings. Maybe an option could be added to turn off the sensor lost warning, and only have telemetry lost. Or even a way of just extending the time out. The sensor lost time should really be based on the telemetry rate, if it's not already.

**Comment by salibaj2** [comment]
Noticed this with 1.4.12 and 1.4.13, not only for ELRS.

Yesterday I updated an X20S of a friend of mine from 1.4.09 to 1.4.13. Only sensor attached is a GPS sensor and occasionally it says sensor lost.

**Comment by Wolepo** [comment]
GPS Alt is the culprit. I had to deactivate the message. All other sensors that come from the GPS are scanned cleanly.

**Comment by MrD-RC** [comment]
Not for me. I can see groups of sensors being lost, then come back. At other times, other sensors are lost. It’s not only GPS Alt.

**Comment by yak-54** [comment]
same on X12S sensors being lost, then come back and the radio does not stop she whines about all the time
and the last i turn her down i lost an plane

**Comment by bsongis-frsky** [comment]
@yak-54 do you speak about ELRS? I mean an ELRS external module?

**Comment by bsongis-frsky** [comment]
@MrD-RC Which radio, which module?

**Comment by bsongis-frsky** [comment]
@salibaj2 Same question, which radio, which module?

**Comment by bsongis-frsky** [comment]
@Wolepo Do you know what is the interval between 2 samples of GPS Altitude?

**Comment by Wolepo** [comment]
Here is a short log. 
1st setting with signalling delay 2s and rudder to minus.
2nd setting with reporting delay 1s and rudder to plus. 
Updating is probably only done when the altitude is changed. this is best seen in the last third. I walked up and down the slope a bit.
[Sunny-Bird-2023-11-06-13-19-38.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13266558/Sunny-Bird-2023-11-06-13-19-38.csv)

**Comment by salibaj2** [comment]
X18SE and X20S

**Comment by yak-54** [comment]
> @yak-54 do you speak about ELRS? I mean an ELRS external module?

no elrs is not supported on the X12s  R9m on flex with Rr9

**Comment by MrD-RC** [comment]
> X18SE and X20S with inside modules. Till now I never used external modules.

The X18 and X200 don't have and ELRS internal module.
