### ISSUE TITLE
Impossible to update to 1.4.13 with Mac

### ISSUE THREAD

**Issue by JoseAltea** [FrSkyRC/ETHOS-Feedback-Community#3011]
Hello, good morning. I have a Tandem XE with firmware 1.4.12, my operating system is IOS, I have a Macbook pro, I'm trying to update to 1.4.13 but it won't let me, the message comes out that the disk is not detected and does not update. When I connect it to the computer and the radio I have it in USB mode I can access both the radio and the micfro SD without problems, when I try to update again I get the same message again.Thanks and best regards
![Imagen 27-10-23 a las 21 07](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/123797860/d7dd8516-de0a-4020-9092-578790f701b3)

**Comment by mawzthefinn** [comment]
I've seen similar reports elsewhere. Opening Suite after plugging in the radio can help in some cases.

**Comment by JoseAltea** [comment]
Thank you, I followed your instructions and finally updated the firmware.
Best Regards

**Comment by Nicholas-Luoyi** [comment]
Have you removed some of the hidden files in the flash or radio internal storage? The file ends with '.cpuid'

**Comment by kramgrand** [comment]
Hi, I had the same results but persisted and eventually the Mac identified the 20 pro and 20s storage. Then proceeded to to perform backups and firmware updates without further problems.   As per instructions above from mawzthefinn, opening suite after plugging in the TX did the trick.

**Comment by EmanuelStassar** [comment]
I have a similar issue with 1.4.13 suite on both windows and Mac. It won't do any updates on my Horus X12s. Its looking or a disc and then timing out. I can see the disc in the file explorer. I just installed 1.4.12 suite and it works just fine. Must be something wrong in 1.4.13 suite with Horus.
