### ISSUE TITLE
Handling of Registration ID

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#3012]
I have found that the handling of the Registration ID in ETHOS can be quite confusing, as described below.

If the 'Owner Registration ID' is changed in any model, then this change is reflected in all other models, as it actually is a global setting. So far, so good. However, such a change leads to the following behaviour.

In the very model in which the change was made, the actual Registration ID used for binding is also changed. This ID is only visible if the registration dialogue is initiated, as it is the default value for the Registration ID when a new registration is performed (unless it is a brand new model, in which case the 'Owner Registration ID' is used as default). This implies that binding with a previously registered Rx is no longer possible and moreover, the reason for this is not readily visible.

In all other models, the new 'Owner Registration ID' is also displayed, but no change of the actual Registration ID used for binding takes place (which is good). Hence, binding with any of the previously registered Rx's is still possible. However, it is no longer visible which ID ist actually used for binding, unless a new registration process is triggered.

To overcome the above 'anomalies' it is recommended to distinguish more clearly between the default Registration ID for new models, and the actual Registration IDs used in the models for the binding process. To this end, the 'Owner Registration ID' should be made part of the system settings, e.g. in the menu for General Settings. I would also rename it to something like 'Owner ID' or 'Default Registration ID'. The 'Owner Registration ID' in each model should be renamed to just 'Registration ID' and should be associated with the ID actually used by that model for the binding process. It should be possible to change this ID without the need to perform an actual registration (as it is now even if this is not immediately obvious). When a change is made, a warning should be displayed indicating that previously registered Rx's cannot be bound anymore. The default for new models should still be the global 'Owner ID', as per the current design.

NB: Changing the Registration ID for a particular model, without the need to perform a new registration, is a very useful feature and should be maintained.

**Comment by Hartinger** [comment]
No response at all after 3 months?

**Comment by Target0815** [comment]
We had another lengthy discussion on this topic in the local forum today. It was actually triggered by the German translation of "Owner Registration ID" as "Individuelle Registrations ID". Some users enter something without knowing what the context is and then complain that Ethos only causes frustration.

It would be good if the changes mentioned by @Hartinger were implemented. That would save a lot of support work.

**Comment by Hartinger** [comment]
It puzzles me a bit that there is still no reaction on this issue.

**Comment by Hartinger** [comment]
We had another big discussion in the german FrSky forum triggered by the very confusing handling of the registration ID in ETHOS. So why is there no intention to change this, at least to move the ID to the global settings where it belongs
