### ISSUE TITLE
sr8 pro 

### ISSUE THREAD

**Issue by creepyflyer** [FrSkyRC/ETHOS-Feedback-Community#3016]
hey guys all this is pretty new to me so please be patient
i have tryed to set up a sr8 pro with stabilization and all was working until i did a self test after that the servo's no longer did any movement only the throttle channel was still working After that i thought maybe a firmware update will solve this but after updating still the same problem (its nothing in the transmitter another receiver bound to the same model file everything works)so i'm now stuck with a brand new unusable sr8pro .ive tried to go back to the old firmware via ota and now even that doesnt work anymore 
even another sr! i have wont firmware update with ota 
any help would be appreciated

**Comment by kramgrand** [comment]
Around the self check point you have to move the control sticks for maximum throws.  Please find attached YouTube.  Go to 18 minutes into video.
https://www.youtube.com/watch?v=rUKIBQdmvIY

**Comment by creepyflyer** [comment]
> Around the self check point you have to move the control sticks for maximum throws. Please find attached YouTube. Go to 18 minutes into video. https://www.youtube.com/watch?v=rUKIBQdmvIY

thank you
