### ISSUE TITLE
special function move position changes on reboot.

### ISSUE THREAD

**Issue by mortehoe** [FrSkyRC/ETHOS-Feedback-Community#3017]
If  I create a special function then move it to the first position SF1 (for model name annoucement on power on) after reboot the position changes back to original position,however the position holds correctly when changing to another model and back again.
Horus X10s isrm running Ethos 1.4.13

**Comment by mawzthefinn** [comment]
Can you try another SD card? A really slow card will have this issue as the radio shuts off faster than the card writes in that case

**Comment by mawzthefinn** [comment]
Those should definitely be fast enough. Something else is going on with your radio

**Comment by mawzthefinn** [comment]
Can you post the model file this is occuring on?

**Comment by mortehoe** [comment]
I have attached both models that I setup with model announcements and both behave the same i.e move to SF1 and changes back to SF4 on re-boot.
I have just noticed that SF1-3 were setup as global functions for rates;could that have something to do with the issue?
[plane02.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13243838/plane02.zip)

**Comment by mortehoe** [comment]
Any further forward on this one?
