### ISSUE TITLE
Adding protocol to LUA script for iRangeX iRx4 lite multimodule

### ISSUE THREAD

**Issue by fhu667** [FrSkyRC/ETHOS-Feedback-Community#3018]
I have an X20s running 1.4.13.  I also have an iRangeX iRx4 lite running 1.3.3.33.  I bought a little plane called a QIDI-550 that is supposed to work on the multimodule using protocol FX/9630.  This option is not available on the LUA script.  There is an FX option, but when I choose FX from the protocol menu it selects "Fly Sky AFHDS 2A".  When I look at the LUA script package for the multimodule I see the following in MultiChan.txt

58,0,FX,816,1
58,1,FX,620,1
58,2,FX,9630,1,Rate,Gyro,TrimR,TrimA,TrimE

Is this something that can be easily added to the Ethos LUA script?  I tried adding those lines to main.lua, but it didn't work.

**Comment by mawzthefinn** [comment]
There's a typo in the current Lua,

try this one. I've corrected the typo that was selecting AFHDS 2A instead and added 9630 as an option. Not sure how to address the remaining 5 settings on that line though.

[multi.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13257112/multi.zip)

**Comment by fhu667** [comment]
That fixed it!  Thank you for your help.  I'm not sure what the remaining 5 settings do.  The instructions are pretty vague on the model.
