### ISSUE TITLE
Radiomaster ER8GV no possibility to play vario #2801 and 2864 (ELRS)

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3019]
Radiomaster ER8GV no possibility to play vario
#2801 and 2864 (ELRS)

Test today with X20S and latest 1.5.0
Sensor is displayed in telemetry.
Activation of Varioton still not possible!

Greetings Eugen

**Comment by yak55** [comment]
Sorry, was of course update from 1.4.13 to 1.5.0

**Comment by bsongis-frsky** [comment]
This issue should be fixed in 1.5.0 by using the new Play Vario functioon
