### ISSUE TITLE
X20 V1.0.6 Main display middle 3 analogbars not ok

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#302]
X20 V1.0.6 Main display (screen1)
the middle analog sliders are not displayed or ony one
(all three are calibrated and working)
after i created a model and created 2 more screens
before it was ok

**Comment by bsongis-frsky** [comment]
all screens don't show these sliders!

**Comment by bsongis-frsky** [comment]
which screen type do you have?

**Comment by hrenz** [comment]
its at the masterscreen, the main screen, with the 3 bars in the middle
I got the x20s yesterday with V1.0.6
S1, S2 ist not moving as bars at the screen1, die red slider in the middle is ok at the screen1 and moving 

S1, S2 are ok at Hardwaretest
S1,S2 are ok as source at mixer

In the basic model from yesterday everything was ok.
This effect occurred only when I had created 5-6 more screens. 
Since then, on screen 1 is only the red slider  
S1 and S2 do not move anymore at this screen1

**Comment by hrenz** [comment]
now I deleted  my model
flashed V1.0.7  
made a new simple modell
and at mainscreen S1, S2, S3 are all 3 bars ok
