### ISSUE TITLE
Data invalid - all screens deleted ELRS

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3020]
Data invalid - all screens deleted ELRS

X20S 1.4.3 with ELRS and screens with ELRS telemetry values
Update to current 1.5.0

Message: Model data invalid - model cannot be loaded
Model cloned - opening the cloned model possible
All screens are deleted

Effect as in #2942

Setting up screens afterwards is possible!

Greetings Eugen

**Comment by yak55** [comment]
Sorry, was of course update from 1.4.13 to 1.5.0

**Comment by bsongis-frsky** [comment]
This one is fixed, no?
