### ISSUE TITLE
v1.5 Nov 3 nightly: in mixer, an Offset line shows 'When Active' value, even when line is inactive.

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3021]
Just been checking out the latest version of the Free mix - very cool! 

I think there may be a UI bug, though - see screen shots below.

Also wondering if there's a way to show the Offset line as 'half active' when inactive, since it is still contributing to the stack.

Active: positive offset
![2023-11-04_153841a](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/020e9734-bba0-40bd-a761-14ce35b50413)

Inactive: negative offset, but displays active value
![2023-11-04_153829a](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/3c183728-e555-4488-944f-2860c04c98c6)

**Comment by bsongis-frsky** [comment]
As a user I think that an offset applied when "inactive" should be bold, and the current offset displayed. I will try to do it now.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d8d242f9-5ea3-4987-9556-4601e0e29277)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2b9d12c4-9d9e-4dba-828a-821c22cffaa7)
