### ISSUE TITLE
there is no variable limiter at throttle mixer ETHOS V1.4.12

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3022]
The throttle mixer still lacks a variable adjustable limiter
so that you don't have to do this with 2 extra mixers
just like Jeti or Graupner have it

**Comment by mawzthefinn** [comment]
What do you mean? I don’t understand at all what is missing?

**Comment by martinfly-1959** [comment]
I'll give you an example.
[Gasvorwahl.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13260346/Gasvorwahl.bin.txt)
without .txt

**Comment by mawzthefinn** [comment]
Ah, I understand now. You have a variable max throttle where you can use the adjuster to live adjust the max between 0 and +100 when active ie limit the throttle range to 50% through 100% via the slider)

This is already addressed in 1.5.0 with the new curve functionality allowing points to be assigned to a source, you can simply have an adjuster which moves the right point of the throttle curve between 0 and 100. You still need a Free mix to condition the slider to the 0-100 range though.

**Comment by bsongis-frsky** [comment]
Ready in 1.5.0
