### ISSUE TITLE
X20HDzero mising video component

### ISSUE THREAD

**Issue by austinpowers1977** [FrSkyRC/ETHOS-Feedback-Community#3023]
Hi i have a X20HDzero. The video works but i cant get OSD to work. Go to ethos and its now showing the video component stuff. Just blank. It asks me if its V1 or V2. mine is V2 has HDMI port (large) and a jumper slot. I cant seem to get it to update. Help!

**Comment by Nicholas-Luoyi** [comment]
I have updated the frsk list. You may find the firmware for video component in Suite - FRSK Flasher - Video Component. The flashing will take a long time. Please be paticent during the flashing.

**Comment by austinpowers1977** [comment]
I only see collection V1. My handset is a V2. I've had this issue since I
bought it.

**Comment by austinpowers1977** [comment]
Can't get ethos suite to update. Downloads 1.14.13 but refused to update.
How can this be fixed? I need to update so I can update video section. This
problem has been going on for a long time and no one at frsky is helping to
sort this!

**Comment by austinpowers1977** [comment]
so i have version 2.2.4 on my handset but how do i find the version on the
mobula 6 to i can match the firmware for the osd?

**Comment by austinpowers1977** [comment]
hi ihave just tried to put the component V2 onto handset now i have a black
screen and nothing on the display all.

**Comment by austinpowers1977** [comment]
Got this error and now a black screen

**Comment by bsongis-frsky** [comment]
Please share your error with the Web interface of github, because bitmaps coming from emails are not visible. I tell you so that tomorrow @Nicholas-Luoyi can have a look and try to help you.

**Comment by Nicholas-Luoyi** [comment]
What version is your firmware? And did you abort the video component flashing progress?

**Comment by austinpowers1977** [comment]
I left it to flash the handset froze up and did nothing. Could turn it off
and I unplugged the battery. But it said it had completed. That's another
issue. It said download 1.4.13 which it installed on handset but every time
I plug in it says download 1.4.13. Wouldn't start auto update. Something
wrong with the software.

**Comment by Nicholas-Luoyi** [comment]
Please ignore the 1.4.13 firstly. I think the most important thing is to make your screen display again.

**Comment by Nicholas-Luoyi** [comment]
Make sure you radio could be connected to Suite in bootloader mode (Press ENTER and POWER at the same time)
Press Switch to Ethos in Suite
Flash Video Collection V2 in FRSK Flasher.
Remember it will take a long time. Nearly 10min

**Comment by Nicholas-Luoyi** [comment]
BTW. Do you remember your firmware verison of ETHOS?

**Comment by austinpowers1977** [comment]
OK I'll give it a try now but I'm not sure how to tell if its worked

**Comment by Nicholas-Luoyi** [comment]
It will restore the display function if it works

**Comment by austinpowers1977** [comment]
1.4.12 but won't let me update it to latest for some reason.

**Comment by Nicholas-Luoyi** [comment]
Maybe you can post some screenshot of the Suite during the flashing. I can see if it works correctly

**Comment by austinpowers1977** [comment]
So if I do it correctly will the handset make any noises? Do I need to have
the jumper in the side of handset next to hdmi port?

**Comment by austinpowers1977** [comment]
Do I need to put the jumper plug in the handset?

**Comment by austinpowers1977** [comment]
Keep getting this error all the time. Did this first time that's when it
didn't work and I unpowered the radio

**Comment by austinpowers1977** [comment]
Can someone please tell me if i need to put the Jumper plug into the handset to fix this or is it not needed. It comes back with auto update didnt work error then it asks me to finsih or cancel. I am at a lose. i cant see the screen to see if its doing anything at all. 

thanks

**Comment by Nicholas-Luoyi** [comment]
It seems failed. Please wait and I will find ways to help

**Comment by austinpowers1977** [comment]
ok can you remote into the handset via pc? im not sure if im doing it right. will give it a go with jumper in the side.

**Comment by austinpowers1977** [comment]
![20231107_092114](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/27560822/32b23094-17a4-41d5-8fd1-4f9fd0fbe382)
![20231107_092121](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/27560822/e7c6a20b-19b8-44db-874e-937ed58f7b9f)

This is what i get with jumper plugged into the side of handset

**Comment by LiangAndrea** [comment]
![ec764df52ba84917673abd27b26f3e4](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/28148078/d0c71cdd-570c-4ec2-8570-95b7d0449b28)
Did you find this?

> Can someone please tell me if i need to put the Jumper plug into the handset to fix this or is it not needed. It comes back with auto update didnt work error then it asks me to finsih or cancel. I am at a lose. i cant see the screen to see if its doing anything at all.
> 
> thanks

Try this jump cap only when the flash of the Video Transmission firmware is failed.

**Comment by austinpowers1977** [comment]
Yes I found that downloaded it and flashed it. It's sat on my desk and I've
left it to update if its actually updating. Will it make any noises when
it's finished?

**Comment by bsongis-frsky** [comment]
Do you see a progress bar with a percentage?

**Comment by austinpowers1977** [comment]
I can't see anything black handset screen.

**Comment by bsongis-frsky** [comment]
There are 2 steps in the flashing process: 
1) the file is uploaded to your SD card (no percentage)
2) the file from SD is flashed to the video component of your radio (here you should see a percentage)

**Comment by bsongis-frsky** [comment]
I meant on Ethos Suite

**Comment by bsongis-frsky** [comment]
The first screenshot you have attached above makes us think that the file is not copied to your SD

**Comment by austinpowers1977** [comment]
can i copy the files directly to SD card?

**Comment by austinpowers1977** [comment]
copies onto handset ok but where on the SD would the file go?

**Comment by bsongis-frsky** [comment]
When Suite requests the radio to update one of its internal components (or module / receiver / sensor / etc.) it creates a device.frsk file at the root of your SD

**Comment by austinpowers1977** [comment]
it tries to update suite to 1.14.13 but the auto update doesnt work. Where should i put the Component V2 file?

**Comment by bsongis-frsky** [comment]
Please try to download this file:
https://www.frsky-rc.com/wp-content/uploads/Downloads/EthosSuite/Devices/VideoComponent/collection_V2.frsk

Then you write it at the root of your SD in a file named "device.frsk"

**Comment by bsongis-frsky** [comment]
Precision: you have to be running Ethos to check if the copy succeeds and to know how much time it takes.

**Comment by austinpowers1977** [comment]
I don't understand what your saying. Do you want me to copy the file I
downloaded (component V2) to the sd card. I did that but hasn't made any
chances to handset. I copy the file to root of sd card. Saw percentage go
from 0 to 100%. I'm asking is there certain place on the sd card the file
has to go to?

**Comment by austinpowers1977** [comment]
OK I understand now

**Comment by bsongis-frsky** [comment]
It won't do anything. I am just trying to ensure that your SD Card works correctly and that Ethos allows you to copy such a file.
It must be in the root of your SD and its name should be "device.frsk"

**Comment by bsongis-frsky** [comment]
Then we will have a second step to force Suite to flash the file. In fact I am not sure what goes wrong. Perhaps we will have to build a special Ethos Suite with more traces for you. Oh we didn't ask if you have some error in Ethos Suite logs? 

@Nicholas-Luoyi would you help him to find where are the error logs of Suite? Perhaps we will see something interesting?

**Comment by austinpowers1977** [comment]
i dont have device.frsk i only have Flash or USB drive E

**Comment by bsongis-frsky** [comment]
You have to:
1) download the file from the website
2) run Ethos
3) plug USB and choose "Ethos Suite" so that drives appear on your computer
4) copy the file from the website to the new drive (the one for SD, not the one for FLASH), at the root of this drive
5) name it "device.frsk"

This is what Ethos Suite should automatically do for you, then it requests the file to be flashed

I explain the process so that you can understand what is hidden behind Suite button ...

**Comment by austinpowers1977** [comment]
ok i have found the device.frsk i have flashed it again i still come back with the error auto update fail and then handset returned an unexpected error.

**Comment by bsongis-frsky** [comment]
It's difficult to help you as you don't answer the questions. We are not flashing, we are just copying a file to the SD. If this first step doesn't work, it is a nonsense to try to continue.

So ... does the copy work, does the rename work. How much time does it take?

**Comment by austinpowers1977** [comment]
yes i followed your guide to the letter did exactly as you asked and the file is now on the SD card root. but nothing has changed it wont work.

**Comment by bsongis-frsky** [comment]
Perhaps my english is not good, maybe omebody else could help me here to explain what I need?

My question is "Does the copy work, does the rename work. How much time does it take?"

**Comment by austinpowers1977** [comment]
yes its copied to the SD card fine. it went onto SD quickly like tops 5 seconds. sorry i must of missed something as i meant to change the file name?

**Comment by Nicholas-Luoyi** [comment]
There is a button to open crash logs in Settings page

**Comment by bsongis-frsky** [comment]
@austinpowers1977 please stop trying to flash from Suite your video component as crazy, you will only brick your board ; be sure you follow the process correctly, here we are not trying to flash anything, just copy a file on the SD, with the right name, on the right place, and be sure the file is perfect

**Comment by bsongis-frsky** [comment]
@austinpowers1977 please paste the crash logs here so that we can check if there is any valuable information inside

**Comment by austinpowers1977** [comment]
yes i have copied the file from download put it at the root of SD and changed its name to Device.frsk as you asked. i havent flashed anything at all.

**Comment by austinpowers1977** [comment]
i have removed and reinstalled ethos suite so ive lost crash files sadly.

**Comment by austinpowers1977** [comment]
![Uploading 20231107_105139.jpg…]()

**Comment by bsongis-frsky** [comment]
I cannot remember somebody asked you to remove everything from Suite so that now we have lost any valuable information

**Comment by austinpowers1977** [comment]
OK I'm flashing with jumper installed. I get same error auto flash did not
start successfully. Please flash the .frsk manually by following the steps.
I heard 1 beep from radio light on handset is blue and nothing is
happening. Do I just leave it to do it's thing?

**Comment by austinpowers1977** [comment]
It says at the bottom to finsih  or cancel....

**Comment by bsongis-frsky** [comment]
If you have an error it's finished. Please paste your error log file here and let's hope there is something valuable inside!

**Comment by austinpowers1977** [comment]
OK well it's currently sat saying finish or cancel which do I do?

**Comment by austinpowers1977** [comment]
ive clicked finsihed nothing has changed do i unplug usb or leave it plugged in?

**Comment by Nicholas-Luoyi** [comment]
Cancel it. Then go to settings tab. Click the Open Crash Log button. And paste the recent log here

**Comment by austinpowers1977** [comment]
it didnt crash at all which is weird. This system must be dead or something. i can hear the audio but i cant get video at all no matter what i do. Where would i send it to be repaired? im in the UK. Just going round and around getting nowhere. Just so frusrating.

**Comment by austinpowers1977** [comment]
just had a crash log now. but its stuck doing audio restore so im stuck waiting for that to clear and then ill send the log...

**Comment by austinpowers1977** [comment]
god sake it said there was a log and went to get it and nothing there. what is going on?

**Comment by bsongis-frsky** [comment]
"audio restore"? what do you mean?

**Comment by bsongis-frsky** [comment]
now you uninstalled again ethos? or ethos suite? 

please have in mind that if you have a black screen in bootloader, it's not ethos, but your video component which is in a bad state, ethos cannot do anything except help you to flash it again

**Comment by Nicholas-Luoyi** [comment]
Where did you buy it?

**Comment by austinpowers1977** [comment]
No I'm asking you if there is a way to factory reset handset coz no matter
what we do it won't work.

**Comment by austinpowers1977** [comment]
Hobbyrc in the UK

**Comment by austinpowers1977** [comment]
so what am i meant to do now? this whole issue is from the handset not showing a component versioin since i bought it from new. Is there no way you can link to my computer and the handset to fix this issue?

**Comment by bsongis-frsky** [comment]
> god sake it said there was a log and went to get it and nothing there. what is going on?

Please paste the screenshot that you have done at this moment

**Comment by bsongis-frsky** [comment]
> god sake it said there was a log and went to get it and nothing there. what is going on?

Screenshot please

**Comment by austinpowers1977** [comment]
There is nothing in the folder at all. Just says log file created but
nothing in the folder. There is something seriously wrong with this
handset.

**Comment by bsongis-frsky** [comment]
Please contact your seller. I am almost sure it's possible to repair but we need somebody who is serious for this kind of job.

**Comment by austinpowers1977** [comment]
I have spoke to Mike at hobbyrc. Waiting to know what to do.

**Comment by bsongis-frsky** [comment]
He can contact me directly if needed.

**Comment by austinpowers1977** [comment]
OK send me your email address I'll pass it onto him.

**Comment by bsongis-frsky** [comment]
He will find it

**Comment by austinpowers1977** [comment]
Mike is saying to carry on talking with you to try and fix it. Again can no
one remote into my pc and go from there? I'm no expect.

**Comment by bsongis-frsky** [comment]
I can try with Teamviewer. Please contact me on Discord

**Comment by austinpowers1977** [comment]
I have discord but what's your name there or do you have a link?

**Comment by austinpowers1977** [comment]
Can you send me a link to your discord?

**Comment by AJames141** [comment]
Yeah, where did the video components go?
