### ISSUE TITLE
[lua] how i can get the state of the receiver

### ISSUE THREAD

**Issue by koakumaping** [FrSkyRC/ETHOS-Feedback-Community#3026]
1. the system know the reciver is connected or disconnected, but i cant get the receiver state throght lua, also dont know the protocl.
2. also cant reset the whole telemetry by lua.

pls add the two api.
thx.

**Comment by mawzthefinn** [comment]
1.5.0 adds Telemetry Active as a System value, that should be readable by Lua.

**Comment by koakumaping** [comment]
> 1.5.0 adds Telemetry Active as a System value, that should be readable by Lua.

always said the 1.5.0, its a joke?
