### ISSUE TITLE
Timer offset for counting up 

### ISSUE THREAD

**Issue by janekx** [FrSkyRC/ETHOS-Feedback-Community#3031]
Some competitions have landing in time in a sec time frame. 
When we set timers to UP so goes from 0:00:00 but you start after start signaling and switch it can take 1sec to react start timer. 
after that you must land in a sec but your timer is 1 sec delayed from starting delay. 
Fix can be make timer offset to start from 0:00:01 not from 00

**Comment by mawzthefinn** [comment]
Are you sure there's a delay? It takes 1 second for the timer to register 1 second on the count from initiation when working correctly. 

Generally a countdown is used for competition for this reason, as it allows a proper countdown in the landing window.

**Comment by janekx** [comment]
It is not system delay, but person hear signal and his reaction is delay what he like to compensate. So easily able to set from what point will be timer up count up.
