### ISSUE TITLE
SD card does not show up in Filemanager

### ISSUE THREAD

**Issue by yufasa** [FrSkyRC/ETHOS-Feedback-Community#3032]
Was trying to use logs on the SD card but logs are not written and in the process of faultfinding that I found that I am unable to select the SD card from the Filemanager on the Radio (X20 Pro)

I can toggle between FLASH and RADIO but no SD.

Could be I am doing something wrong and if so I am happy to test if you have any suggestions :)

**Comment by mawzthefinn** [comment]
Tested on my X20 Pro FCC, same behaviour.

Same 4GB card works correctly on my X18

**Comment by mawzthefinn** [comment]
One quick question, are you inserting the card before powering on the radio?

**Comment by yufasa** [comment]
Yes, I have not removed the card since I installed it after I received the radio

**Comment by mawzthefinn** [comment]
What are the card specs?

I was able to duplicate your issue, but further testing with a 4GB FAT32 card showed that it would mount if inserted before boot, but not if inserted after boot.

**Comment by yufasa** [comment]
It’s a 32GB. Yes I know it is large but it is what I had. Can you even buy 4GB anymore?
I will reformat and try again. Note that I can copy to the card from my Mac so it mounted fine

**Comment by bsongis-frsky** [comment]
Fix confirmed by @mawzthefinn today

**Comment by yufasa** [comment]
To clarify here: The radio only work with 4GB cards?
I don't understand as the hardware clearly support 32GB cards as I can see the SD when the radio is connected to my Mac.
I have done a fresh format to Fat32 and made sure the radio is off before inserting the card and ...nothing. The radio will not see the card in Filemanager
I then inserted a 1GB card that was in my old Graupner and boom it works. Switch back to 32GB and nothing...
