### ISSUE TITLE
ETHOS XES ITALIAN TRANSLATION 1.4.13

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3036]
here is provided the italian missing translation for XE/XES Ethos, only few terms for the top display
[it XE.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13272749/it.XE.zip)

**Comment by bsongis-frsky** [comment]
But it is exactly the file that we have today!

**Comment by bsongis-frsky** [comment]
Everything is up to date then :)

**Comment by mgsanna** [comment]
[it.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13276917/it.txt)
sorry I put the wrong file
here is the good one

**Comment by bsongis-frsky** [comment]
Perfect now, thanks!
