### ISSUE TITLE
X18: Bad readability in logical switches

### ISSUE THREAD

**Issue by patman13** [FrSkyRC/ETHOS-Feedback-Community#3039]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3024691/5d1e8bda-0645-45fb-9b32-706a565ded96)

The readability is bad, because the is no space between number and condition.
Characters are wasted to display "Log sw" (I don't know exact englisch term, because I use German) in every line. This should be clear from the headline and displaying the number should be enough.
Use the won characters to add a space between number and condition, please.

**Comment by bsongis-frsky** [comment]
Changed to "LS.1" instead of "LSch.1"
