### ISSUE TITLE
Servo/Channel Names shouldn't automatically change or erase

### ISSUE THREAD

**Issue by Testname84** [FrSkyRC/ETHOS-Feedback-Community#304]
Ethos Version: 1.0.6
Tx: X12S

I expected several times during programming of a glider with 20 Servos the phenomenon that channel names have been erased or renamed in the "outputs" menu when I changed the number of ailerons or flaps in the "edit model" menu. Same with motor number.

Regarding to the fact that you do the basic servo configuration like sub trim, servo travel etc. in the "outputs" menu It makes sense to fix the channel names which are assigned in "outputs" menu.

**Comment by GoodyearBiff** [comment]
I can verify this activity on my radio as well.

**Comment by mawzthefinn** [comment]
This appears to have been corrected at this point.

The number of channels assigned in Edit Model no longer has any affect after model creation, you have to add channels in the mixer itself and assign them. Channel renaming is now an asked-for item when swapping channel assignments.

**Comment by mawzthefinn** [comment]
Closing as this behaviour has been corrected with newer firmware
