### ISSUE TITLE
Function button settings

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#3043]
Function button settings under Model Config, why not under Hardware like all switches.

**Comment by Wolepo** [comment]
If the setting were made in hardware, it would apply globally to all models. Personally, I wouldn't think that's a good thing.

**Comment by bsongis-frsky** [comment]
Indeed. It has been a request

**Comment by EngelMT** [comment]
@Wolepo I hadn't thought of that. You're right. We just keep getting customer enquiries about where to find the settings for the 6 function switches. And in fact, you probably don't look for them in the model config.

@bsongis-frsky Wouldn't it be possible to make the settings under Hardware and create the option "Global YES/NO" there?

**Comment by Wolepo** [comment]
But if "No" is set, where can you find the setting?

**Comment by EngelMT** [comment]
You're right again. What looks simple and logical at first glance is sometimes much more complicated. OK, then let's leave it as it is. A good manual would be a good thing. Unfortunately, that doesn't exist and with the speed of development of ETHOS, I've given up on writing a German manual.

**Comment by lthole** [comment]
@EngelMT The function buttons are described in the English manual, which is at 1.4.11 at the moment. There is a link in the Feedback GitHub.

The manual for 1.5.0 is already at an advanced stage, please refer to post 26043 in the X20 thread on rcgroups for a link and a list of changes.

**Comment by EngelMT** [comment]
@lthole Many thanks for this info.

**Comment by lthole** [comment]
@EngelMT you can submit a complete PDF document such as the manual to Google Translate. I would be interested to hear your comments about how usable this would be to German readers. The translation may not be good enough. 

I used this to translate the manual for the Zeller X-Dream to English. I got a better understanding of some points by reading both versions.

**Comment by EngelMT** [comment]
@lthole We use the deepl translater for some translations. This gives you better results. But you still have to check everything. Because there are often problems with the translation. German is a difficult language. LOL!
