### ISSUE TITLE
Etos 1.5.0 Free mixer curve and slow

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3045]
Curve and slowly into a free mixer (curved curve [-100% to +100%]), does this work in 1.5.0? According to my observations, the processing of the curve starts at 0% and only in a straight line.
Here is a model with only one throttle mixer and LS1 which is activated with switch SB- and evaluates the throttle stick position. At throttle >90 and a delay of 1.5s, it becomes active and initiates the acceleration of the throttle channel. 
However, this procedure only works once and not again. It only works again after restarting the sim.
[gas verzögert.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13298624/gas.verzogert.zip)

**Comment by mawzthefinn** [comment]
The slow doesn't take effect until it is active, at which point your throttle is already maxed. Plus you have it after the curve, which means the cruve is never processed (as it only ever sees the -100 and 100 values)

I can get it to consistently accellerate along the curve by moving the slow up before the curve and setting the slow to Always On.

**Comment by bsongis-frsky** [comment]
Yes, @mawzthefinn is right!
