### ISSUE TITLE
Can't configure "packed" sensor values (2 16bit values in 32bit address data)

### ISSUE THREAD

**Issue by patman13** [FrSkyRC/ETHOS-Feedback-Community#3047]
I use a Unisens-E telemetry sensor. According to the information from developer it uses one address 0x0B60 to transmit speed and capacity.
When using sensor detection (don't know the exact English term, because using German version), everything works fine.
If I create sensor manually (DIY sensor) with exact the same parameter I doesn't work.

Maybe not everything from the sensor protocol is reflected in the UI.

**Comment by bsongis-frsky** [comment]
Packed DIY sensors are still not implemented, and it won't be easy to do. I can see a solution with Lua custom sensors

**Comment by bsongis-frsky** [comment]
I don't understand why you need a DIY sensor for that?

**Comment by bsongis-frsky** [comment]
This will be a new feature introduced when working on #2503
