### ISSUE TITLE
RB-40

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#3049]
Transmitter: - X18SE

I am setting up an RB-40 for a friend of mine. So far I was able to connect receivers and had output through the channels.

Since I looked for a LUA script for this unit, and found nothing, I asked on forums from where I can get this LUA script. Everyone told me that it is already implemented in ETHOS.

It is true, but only for connected receivers and failsafe.

Within the Tx, In Device Config, I can see the RB 30/40, SxR, and SxR Calibration.

To calibrate the RB-40, should I use this SxR calibration?

If yes, wouldn't it be better for ETHOS to change for proper pictures for calibrating according to the connected gyro?

Could the title shows what the type name of the connected gyro, and greyed out if no gyro is not connected?

What I really need urgent please an answer if I can still use the SxR calibration menu and SxR menu for orientation etc..

Thank you

Joe

**Comment by mawzthefinn** [comment]
The RB-40 has an Archer SR stabilizer internally and uses the SxR and SxR Calibration menus like all the other pre-2023 FrSky Stabilizers.

**Comment by mawzthefinn** [comment]
Note a redesign for Device config is already occurring under #2829 which addresses the other matters you raise.
