### ISSUE TITLE
Update to EthOS 1.0.7 on X20 and X10Express - after upgrade still shows 1.0.6 in SYS-Info 

### ISSUE THREAD

**Issue by Ender1967** [FrSkyRC/ETHOS-Feedback-Community#305]
Update to EthOS 1.0.7 on X20 and X10Express - after upgrade still shows 1.0.6 in SYS-Info #e6c22468 (this build number is different form previous version #8f7a9990)

**Comment by bsongis-frsky** [comment]
oops, I will reupload new files, just for this revision
