### ISSUE TITLE
Sticky message in the throttle mixer.

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3050]
If sticky is active in the throttle mixer (throttle stick is not at -100% and engine is released), you may wonder why the throttle does not work. Only when the throttle stick is returned is the sticky function cancelled. That is all correct. However, there is no message for the locked state.
Is it possible to insert a WAV file into the system that sounds when the throttle is locked via the sticky? This could then be something like: "Gas is not zero".

**Comment by mawzthefinn** [comment]
You should be able to do that with a couple logic switches. Test for analog->throttle over -95 AND throttle channel below -95 with the active condition of the AND LS as throttle cut off

**Comment by Wolepo** [comment]
Yes, that's how it works. But I'm wasting 3 logical switches and a special function. But if it was already built in according to my suggestion, nobody would have to worry about it.

**Comment by lthole** [comment]
I agree with Wolepo, it should be built in, because the Sticky is built in..

**Comment by bsongis-frsky** [comment]
You have the system event "Throttle Cut" available exactly for that purpose, you may use it in a special function to play the file you need

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/48601bd9-d8c8-4abf-9648-d89910eb0e5c)

**Comment by Wolepo** [comment]
Thank you
