### ISSUE TITLE
Dangerous throttle setting after update

### ISSUE THREAD

**Issue by slopingoff** [FrSkyRC/ETHOS-Feedback-Community#3051]
On Horus x10S ISRM running Ethos 1.4.13 all my power models have throttle setting defaulted to 0 to100 percent NOT -100 to +100 percent.

**Comment by Wolepo** [comment]
What is dangerous about it?

**Comment by slopingoff** [comment]
If i would have plugged my electric plane it would have started the prop at 50 percent not -100 at throttle lower position,fortunately I was setting up a SR6 receiver which needs -100 to activate when I noticed the problem.
I have just edited my original post to make it clearer....I hope.

**Comment by bsongis-frsky** [comment]
We are at 1.4.14
From which release have you converted your model, and to which release?

**Comment by bsongis-frsky** [comment]
Would you explain what exactly has changed?

**Comment by slopingoff** [comment]
I am on version 1.4.13 as 1.4.14 has only just been released I have not updated to this version yet and no reference to the issue in the update.
I hope the attached photos show the issue of throttle down output should be -100 however it is 0 (50 percent throttle)
![Throttle1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/77887013/0aa936ad-d5af-434d-96a5-b479866d40f4)
![Throttle](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/77887013/a4ea6288-102d-4cbc-9848-b2d0243714a3)

**Comment by bsongis-frsky** [comment]
You don't answer my question. I asked on which version were you BEFORE the update. Also I don't see what is wrong. Your throttle stick seems at the middle position (are you using Mode 1)?

**Comment by slopingoff** [comment]
I updated from 1.4.12 although I had not checked that version as I mainly fly unpowered gliders and only discovered this issue when I could not activate self test on my S6R receiver because throttle could no longer go to -100 as it had previously.
I am on mode 2 ,throttle left hand side as shown in the photo.
So,in short,my throttle when down does not go to -100.

**Comment by bsongis-frsky** [comment]
I don't understand why you cannot reach -100%, on the graph you can see that the current input position is 0. When you move your throttle stick (so left stick if mode 2) do you see that this point moves? If yes what is the range (X axis)?

**Comment by slopingoff** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/77887013/38c9b998-e8a8-409a-ba09-855e44f2e05a


https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/77887013/9db4e27f-5684-4fcf-a2d5-877f7310f39a


https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/77887013/30f7d9c5-7005-445e-87cf-157a2f220966

The point moves from 0  to + 100 not from -100 to +100 which is what I would expect.

**Comment by bsongis-frsky** [comment]
Would you do a quick check in System / Hardware that your throttle stick moves correctly?

**Comment by slopingoff** [comment]
Good idea,and you are correct it does not move the full amount.why would that change? do I have a faulty gimbal or does it just need recalibrating and if so,why did it change that much.

**Comment by slopingoff** [comment]
Re-calibrating worked.
Still unsure why it went off by such an amount,especially by an exact amount (50%)
Should we  recalibrate everytime there is a firmware update?
Thank you for your help.

**Comment by bsongis-frsky** [comment]
Calibration is not needed each time there is an update!
As @Wolepo suggest, I also suspect you have never done the calibration properly ;)

**Comment by slopingoff** [comment]
The calibration have been done properly to be able to setup all my S6R receivers which have all been okay up until recent update/s,so still unsure what has caused this and the only thing that has changed has been software updates.
I will be checking the hardware tab on future updates just to make sure.
Many thanks
