### ISSUE TITLE
Please release audio information as a .csv file along side sound pack.

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#3052]
[audio_en.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13334509/audio_en.csv)

Please can you release the audio txt/sound file adjacent to the audio files you release?

This makes it allow easier to create a custom sound file using alternative sapi voice packs.

**Comment by bsongis-frsky** [comment]
It is done this way, starting with 1.5 releases.
