### ISSUE TITLE
Frsky TD-R18 and MKS 777 A+ Servos shaking

### ISSUE THREAD

**Issue by willianwcz** [FrSkyRC/ETHOS-Feedback-Community#3053]
Hi Folks,
   I´m trying to configure a Frsky system on my Extra 35% EF but when I connect all servos in the RX, some surfaces like elevator and rudder are shaking without any action in the TX sticks. Please see the video attached or below:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/66046724/17382cba-dda3-4b41-bd74-10dfb426024f

  
[https://youtube.com/shorts/_Jlj0PEsssI?feature=share](url) 

Any help will be wellcome.

RX Frsky TD-R18
TX FrSky X20-S
Servos MKS 777 A+
Servo extensions 22 AWG
Battery 2 x Pulse LiPo 2S 5000mAh each one

**Comment by Dsrenger** [comment]
Just for testing purposes try to disable the telemetry in the RX settings.

If it stops then (like it did for me) the telemetry antenna signals going into the signal line of the servos should be the issue.

Setting the telemetry output power to 25mw can be helpful then. Seperating the antennas and the servo cables can help. And if not possible, then aluminium foil  around the servo cables can help.

But first try to disable the telemetry (important: disable the telemetry and then go back out of the RX menu)  to see if the telemetry is the issue...

**Comment by kramgrand** [comment]
Yes I agree, turn off the telemetry and I believe the jitter will stop.  Some servos are susceptible to it.  I have always got round it by replacing what are usually older servos for newer ones.  Those MKS ones are a tad expensive though.  I have never tried screening the cables as suggested Dsrenger.

**Comment by willianwcz** [comment]
It seems like a some MKS servo spec. I have tested the same TD R18 in another plane wit JR 8711 servos and have no problem. Apparently, MKS servos has some incompatibility with FrSky receivers.

**Comment by keiner0815** [comment]
I had pretty much the same issue here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2762

The second issue besides the calibration issue seems exactly like that.
I had the problem with RB25s and also tested it with TD-R18 with the same result.

In the end I had to change all servos I had in that plane. Interesting that it seems to occur not only with that KST servos but also witch (some) MKS servos.

Would be really interesting what causes the problem.

Could you try to use another receiver like an R8 Pro and have a look if it behaves the same?

**Comment by willianwcz** [comment]
> 
> Could you try to use another receiver like an R8 Pro and have a look if it behaves the same?

Excellent idea. I will try it.
I will also try to change the extensions wires for 20AWG. Currently, I´m using 22AWG and I have heard that it can solve the problem.

I´ll keep you updated

**Comment by willianwcz** [comment]
Hello firends, 
I have changed servo extensions for 20 AWG wires but has no sucess with this issue.
As suggested by @Dsrenger and @kramgrand, I have disabled telemetry and the servos becames calm and quiet. It seems like someing with telemetry transmition is causing any interference with MKS servos.
Some reports in another forums are saying there is some incompatibility with MKS anda TANDEM protocol. I will make more tests with R8 receivers wich are only 2.4Ghz.

**Comment by willianwcz** [comment]
Can @bsongis-frsky help us in this issue? Please...

**Comment by Dsrenger** [comment]
Did you test already all of this?

Setting the telemetry output power to 25mw can be helpful then. Seperating the antennas and the servo cables can help. And if not possible, then aluminium foil around the servo cables can help.

**Comment by willianwcz** [comment]
> Did you test already all of this?
> 
> Setting the telemetry output power to 25mw can be helpful then. Seperating the antennas and the servo cables can help. And if not possible, then aluminium foil around the servo cables can help.
> 
> That's the main reason for the 25mW telemetry power option in the receiver options.

Yeah I did this....the issue reduces but dont goes away definitely

**Comment by kramgrand** [comment]
You have two options really. Turn off the telemetry, or change the servos. For your info, every time I have put a new servo in,the problem has gone away. Cheap or expensive servos, the problem has gone away. 
Just a guess,I think there is better rf noise filtering on more modern servos. About the only old servos I have that are not affected are old Futaba ones.

**Comment by willianwcz** [comment]
> You have two options really. Turn off the telemetry, or change the servos. For your info, every time I have put a new servo in,the problem has gone away. Cheap or expensive servos, the problem has gone away. Just a guess,I think there is better rf noise filtering on more modern servos. About the only old servos I have that are not affected are old Futaba ones.

JR 8711 also were tested and no issues...And they are a old servos too. In fact, MKS servos seems not work well with RF noise generated....The 900mhz antenna pointing (or no) to MKS servos cables changes their action...Is some antenna positions, the issue is gone away but, to be honest, I can´t trust enough to fly with this combination
