### ISSUE TITLE
After inserting a new mixer, Simulator crashes and the model is no longer visible

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3054]
I added a new mixer in the sim of X18S and Ethos 1.5.0 and wanted to edit it. Then it was suddenly gone and the model was no longer "available".
I am attaching it. Maybe the error can be found.

[gas verzögert.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13338201/gas.verzogert.zip)

**Comment by bsongis-frsky** [comment]
Can you reproduce it with a "fresh" model? The datamodel has changed a lot with the refactoring of Var and Trim...

**Comment by Wolepo** [comment]
Hello,
unfortunately I don't have a copy of the model because the simulator has never crashed. So I recreated it from memory. The error did not occur again. This is how it should be with the last mixer:
[gas verzoegert.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13348890/gas.verzoegert.zip)
