### ISSUE TITLE
XES Simulator too large for smaller screen resolution

### ISSUE THREAD

**Issue by Digitalkaschi** [FrSkyRC/ETHOS-Feedback-Community#3055]
Hello to the developers of Ethos Simulator,

it would be good if the XES Simulator would be scalable, so that you can work with it with a lower screen resolution under Windows.

If it is not possible to scale it, it would be good if it had a size of 1280 x 720 px so that there are no problems on good and older devices. 

At the moment it is not really usable.
I have attached a screenshot.
The image shows XES Simulator 1.4.13 at a screen resolution of 1366 x 768 px.
![SIM_1413_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/150395104/11ae183b-b1d8-45c6-8c07-a765b00499d7)

This applies to all versions from 1.4.9 which I have tested.

A function to print out the respective model settings or programming would also be useful, as in the OTX Companion.

I hope that this will be implemented soon.

Thank you very much.

**Comment by bsongis-frsky** [comment]
Added to #3440
