### ISSUE TITLE
Missing logic switch function (suggestion)

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3059]
Here is something annoying....
I want to create a logic switch based on a telemetry value that is not alive. 
For example, I want to create a logical switch that will turn on when GPS is not getting signal.
But you can't do "a>x" or "a<x" on a null value. For example, in my house - there is no GPS signal.
I think ethos should add "is null" or "is empty" to the available logic operations.
The workaround for now is to create a custom sensor, take the null GPS altitude, and multiply it by 10000. I get ZERO. Perfect, now I have a number I can work with. Then I do "if altitude is less than 1ft, GPS fail" etc etc....

**Comment by Nicholas-Luoyi** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/51de17ed-6c59-4d13-b900-cc91da9d34dd)

You don't need to create a logic switch. Just go to the place where you want to use the "GPS is alive" logic. Select GPS in category Telemetry which will implement this logic. And add the Invert flag if it is needed.

**Comment by bsongis-frsky** [comment]
And you may also use this same condition inside a Logic Switch if you need.
