### ISSUE TITLE
Flash process from 1.0.6 to 1.0.7 doesn't work on X12S

### ISSUE THREAD

**Issue by Testname84** [FrSkyRC/ETHOS-Feedback-Community#306]
starting up into boot loader mode
copy firmware file into main folder
disconnect usb
Tx shows progress bar flashing
restart radio
getting directly on main screen
in the "info" menu is shown Version 1.0.6

**Comment by Ender1967** [comment]
relax...no big deal...they forgot to increase the FW version string (but the build # is different compared to 1.0.6)

**Comment by Testname84** [comment]
ok, thx
