### ISSUE TITLE
X20 with TWLite Pro RSSI Warning if Info Menue is open

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#3061]
During tests with the X20 and the TWXlite RF module, we noticed that the RSSI value goes back to zero when you switch to the Info menu. Then, of course, there are also warnings.

I seem to remember that we already had such an error in the early days of ETHOS with ACCESS.

**Comment by mawzthefinn** [comment]
Duplicate of #2359, it was only partially solved in the past
