### ISSUE TITLE
 x20 pro 900 mhz telemetry not working correctly #2970 never getting looked at

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3063]
x20 pro 900 mhz telemetry not working correctly #2970 never getting looked at.
had to put a new issue on this one as no one is working on it.  the team said it would be updated soon over a month ago

**Comment by mawzthefinn** [comment]
Duplicate, closing in favour of #2970

**Comment by williajgr** [comment]
Does that mean no one will ever fix the problem?  My telemetry will never work on my 900 mhz receivers on the. X20 pro Sent from my iPhoneOn Nov 15, 2023, at 8:49 AM, mawzthefinn ***@***.***> wrote:﻿
Closed #3063 as not planned.

**Comment by mawzthefinn** [comment]
No, it means to continue the discussion under the issue you already have open.

Opening additional issues for the same matter does absolutely nothing except clutter up github.

**Comment by williajgr** [comment]
I have been trying to get a response for about a month and wasn’t getting any responses. Like not doing it. Or a date to expect the update.Sent from my iPhoneOn Nov 15, 2023, at 10:50 AM, mawzthefinn ***@***.***> wrote:﻿
No, it means to continue the discussion under the issue you already have open.
Opening additional issues for the same matter does absolutely nothing except clutter up github.

**Comment by williajgr** [comment]
What other course of action should I have done to get someone to look at the problem?Sent from my iPhoneOn Nov 15, 2023, at 11:18 AM, George Williams ***@***.***> wrote:﻿I have been trying to get a response for about a month and wasn’t getting any responses. Like not doing it. Or a date to expect the update.Sent from my iPhoneOn Nov 15, 2023, at 10:50 AM, mawzthefinn ***@***.***> wrote:﻿
No, it means to continue the discussion under the issue you already have open.
Opening additional issues for the same matter does absolutely nothing except clutter up github.
