### ISSUE TITLE
How many "Issues" are actual "Issues" as opposed to "wants, Needs, or screw ups by user"

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#3064]
Hi guys just curious really how many "issues" are indeed issues as opposed to "User error" (And im guilty of that in the past too) vs how many are actually SERIOUS issues, or just individual user requests?

I just wondered cause I always check the "issues" about a week after each release before updating and quite often I see things that are really not an issue at all (as in my case at least on one occasion) and instead are "wants" as a "stop gap" to save an individual making the same mistake over and over lol. 

Not looking to press anyone's buttons (no pun intended) just genuinely curious because I've often wondered how many of the things listed here are actually covered in the manual if people would just sit down and read it(we all get lazy, its called "Human nature" lol).

Anyway, thanks @mawzthefinn and @bsongis and the other devs behind-the-scenes for all the hard work you do. 

One last question, Do we have an ETA for this magical 1.5 update or will this 1.4 version go up closer to 1.4.19 before this major update that is 1.5.0 because we seem to be getting a lot of updates lately which is great but I am hoping I can update it at 1.5 and leave it there for at least six months before needing to update anything👍👍

**Comment by bsongis-frsky** [comment]
It's not the right place for such a discussion, it would be better to use the "Discussions" in github or discuss this in forums!

I am not sure of the answer, but so far you will find:
- user questions
- user requests
- bugs on the current 1.5.0 branch which is on active development, still not released (RC3 right now, RC4 I hope tonight)
- bugs on the current stable branch (1.4.X), but they are very rare

We try to add a tag to all issues, but it takes time, so we do our best not to loose too much time on issues and actually make Ethos go forward!
