### ISSUE TITLE
Found bug with internal RSSI 2.4 and RSSI 900

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3065]
X20pro with TDR6.
Telemetry - discover new sensors.
Delete RSSI 2.4 (I did by accident - that's how I discovered the bug)
Ok no problem - discover new sensors again.
It won't find it.
After about 1 hour of investigation here is some things I found.
Not all sensors are unrecoverable after deleting. If you delete RxBatt, discover new sensors will find it again.
The only way to get RSSI 2.4 back is to delete ALL sensors associated with the TDR6. In my case, I had to carefully sift through because I had many RB35S sensors carefully organized and labeled, so "delete all" was not an option.

PS - further discovery. The RSSI 2.4 depends on RX (2.4).
So if you delete RSSI 2.4 you also have to delete RX (2.4) then discover new sensor will bring both back.
They come in pairs 🙂 same probably applies to RSSI 900 if deleted by accident.

**Comment by robertoalmeida** [comment]
It would be great if we could choose which band the sensor will communicate (2.4 or 900) in the case of RX TD. The scanned sensors only show as 900M.

How difficult is it to add this choice option?

**Comment by robertoalmeida** [comment]
Are the answers gone?
