### ISSUE TITLE
Suggesting UI improvements

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3066]
Sorry I don't mean to be picky. This FrSky is the best most amazing system EVER!

1) If you try to rename something that ends with a thin letter such as lower case "L" or a 1 or an i or an I
To get your finger to touch precisely between the edit icon and to the right of the thin letter takes at least 10 tries.
Because if I want to delete the last letter, especially if thin, I have to place the cursor to the right side of the last character.

I suggest you add some dead space between last letter and edit icon to give room for finger.

I understand I can click somewhere in the middle click right with the bottom right wheel of my X20Pro.

2) swiping right and left between pages of "Home, Model, System" requires the swipe to more than 50% of the width of the screen.
All of our touchscreen experience with iphone or android teach us a different behavior. If I swipe only 20% of the screen from left to right, but at a high speed, it should allow the next screen to be displayed. 

![ui issue](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/149995415/3b87af18-f15f-46c8-b08f-6dc18640bef9)

**Comment by LeoCheung123** [comment]
Oh yes...we kind of got used to the 10 attempts thing over the years.  But this would be an amazing improvement.

**Comment by chenbevis** [comment]
Perhaps adding cursor left and right movement keys <- -> on the keyboard.

**Comment by Toffs** [comment]
Point 1 - Are you aware that you can use the bottom left ‘menu’ buttons (SYS and DISP) to move the cursor left and right?  I believe this solution is sufficient for granular control.

Point 2 - Yes, swiping more than 50% isn’t typical menu scrolling behaviour and a ‘nice to have’ would be as you suggest, 20-30%

**Comment by Toffs** [comment]
I believe there’s still a desire for the screen horizontal scrolling to be enhanced (OP’s point 2).
Is this something that could be added for a future release (maybe 1.6.0)?

**Comment by Toffs** [comment]
Hi,
I see this has been closed as complete. Part 1 might have been done, but the excellent Part 2 suggestion, allowing for much quicker/slicker/more modern swiping between screens, has not yet.

How might I re-open this?
