### ISSUE TITLE
lua / 1.5n: form.create() still request "window" parameter or generates not expected form

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3067]
..paused for some time on 1.5 testing, so:

as mentioned in #2591 , which was closed:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/3bbe4139-776b-441e-af38-229731861e3e)

actual situation,
code creates form by form.create without parameter:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/a096a811-8b30-4057-8c3c-61c88ad0d73a)

error message:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/ac32c25f-1772-4dc4-b125-8ebe6e34991d)
.. even lcd.getWindowSize() returns nil,nil in create handler...

so i tested form.create in wakeup handler
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/0a0819e8-f6b5-4659-b963-fcb1ca2b0a7e)

looks a little bit messed up to me:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/46b685b6-8a52-47b9-82d0-e61167111ca8)

my personal understanding:
- the "rect" parameter in "form.addNumberField" determines the relative positioning to the "label", created in "addline"
- "addline" lacks positioning parameters (only an optional expansion panel is supported), so the line was attached beyond the bottom of the widget area
-  we should be able to declare forms on initializing in create handler 

.. but maybe i've overseen something ?

[formtst.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13390738/formtst.zip)

**Comment by bsongis-frsky** [comment]
An example is there:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/nightlies/lua/form/main.lua

**Comment by strgaltdel** [comment]
I finally found time to test my widget,
Bug fixed,

Many thanks to you!
