### ISSUE TITLE
Lost sensor keeping last known values

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3072]
If I don't have my ASS70 plugged in, In telemetry it shows "---" in red.
If I plug it in, it shows my airspeed.
If I unplug it while my RX is on, I simulate lost sensor.
But the airspeed turns red, but remains in the very last mph position.

I feel there should be an option for each telemetry sensor:

On telemetry loss OR if sensor not existent during boot:

a) keep last known value (that's what it's doing now)
b) set value to:
       1) null (---)
       2) user defined value

So if I don't have my ASS70 plugged in during RX boot, I can make it read 0mph (sure it's ok if it's red to show me it's not even reading it)

**Comment by koakumaping** [comment]
need +1

**Comment by bsongis-frsky** [comment]
You can use the sensor as a switch, if this switch is ON, it means that the value is fresh!
