### ISSUE TITLE
Suite is not showing new Firmware releases

### ISSUE THREAD

**Issue by Dsrenger** [FrSkyRC/ETHOS-Feedback-Community#3073]
Since 23-11-17 there is a new firmware for the TD-ISRM hardware (X18/X20/XE)

I expected the Suite to know these to be able to flash them from the menu.

Is it by design, that new versions of the firmwares in the FRSK flasher only comes with a new version of the Suite?
Or is it a bug?

Somehow I expected that the suite is looking into a database with the firmwares, the moment I click on the menu.

So not sure if this is a bug or not.

Regards
Dennis

**Comment by Dsrenger** [comment]
Additionally, i guess its connected to the fact, that the suite doesnt know the 2.2.6 firmware:

I have just flashed my TX manually to 2.2.6. In the Info screen it is showing 2.2.6

But the Suite still shows 2.2.4.

**Comment by Dsrenger** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/3727e636-b948-4017-a575-363e43628cf5)

**Comment by Nicholas-Luoyi** [comment]
> Since 23-11-17 there is a new firmware for the TD-ISRM hardware (X18/X20/XE)
> 
> I expected the Suite to know these to be able to flash them from the menu.
> 
> Is it by design, that new versions of the firmwares in the FRSK flasher only comes with a new version of the Suite? Or is it a bug?
> 
> Somehow I expected that the suite is looking into a database with the firmwares, the moment I click on the menu.
> 
> So not sure if this is a bug or not.
> 
> Regards Dennis

The "Up to date" indicator is under development. It will come soon.

**Comment by Nicholas-Luoyi** [comment]
> Additionally, i guess its connected to the fact, that the suite doesnt know the 2.2.6 firmware:
> 
> I have just flashed my TX manually to 2.2.6. In the Info screen it is showing 2.2.6
> 
> But the Suite still shows 2.2.4.

The module version should be refreshed once the radio is restarted.

**Comment by kvak1** [comment]
In my TX20 after manual refreshing the same problem. 

After restarting of radio and Suite Suite still shows old 2.2.4 information. Transmiter shows right 2.2.6.

Karel

**Comment by mawzthefinn** [comment]
Suite 1.4.15 has the latest firmware files listed.
