### ISSUE TITLE
X20HD Video RX Update to support new Freestyle V2

### ISSUE THREAD

**Issue by carguy84** [FrSkyRC/ETHOS-Feedback-Community#3076]
Hello, it appears the X20HD needs an update to support the new Freestyle V2.  Not sure what changed, but it doesn't work with the x20HD.

**Comment by carguy84** [comment]
Just to follow up on this, I figured out that the Nano Cam 90 is what is not compatible.  The Freestyle V2 works no problem however if you buy the HDZero kit, you have to swap out the camera.

**Comment by kakashi2018** [comment]
Regardless oh vtx 2, they should support the new hd osd from betaflight. This is frustrating as my goggles support hd osd and my x20s hd only support old ntsc or pal format
