### ISSUE TITLE
Priority of RX order - REQUEST FEATURE

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3078]
if we have 2 TDMX hooked up to RB35S for example.
RF0 = TDMX1 (telemetry on)
RF1 = TDMX2 (telemetry off)

If TDMX1 signal drops, then TDMX2 will automatically become the primary RX and telemetry is lost.

But once TDMX1 becomes available again, it doesn't switch back to TDMX1. It stays on TDMX2 forever. Even future flights.

The only way to force TDMX1 to be the PRIMARY rx is to boot up while TDMX2 is unplugged.

I think you should have "priority"
RF0 = highest priority
RF1 = medium priority
RF2 = low priority.

It should always switch back to higher priority RX when available and signal health is good.

Then we can put RF0 with telemetry and the rest without telemetry.

**Comment by mawzthefinn** [comment]
If you have both TDMX's wired via FBus or both wired with SBus+S.port and Telemetry Enabled on both, this will not occur. 

Both TDMX's should be set Telemetry Enabled when used with an RB.

Telemetry Disabled on a second receiver with RB's should only be used when you are splitting bands (an ACCESS 2.4G or TWIN receiver + an R9 receiver) or when using a receiver with internal sensors (SR or GR) with a second redundant receiver.

**Comment by noamkrief** [comment]
@mawzthefinn 
I apologize I used a bad example. Yes, in my case I don't have any issues because both my RX have telemetry enabled and telemetry redundancy works.

But in the case of a TDR18 with a TDMX as a backup, the feature of priority would be very good.
Because if primary signal switches to TDMX you lose all telemetry. And that's ok if TDR18 signal is very poor momentarily.
But then it should automatically switch back to the TDR18 once the signal health is restored.

**Comment by mawzthefinn** [comment]
You don't lose all telemetry, only internal sensors from the TD R18 in that case. External sensors should be y-cabled between the TD R18 and TDMX and will fail back and forth.

That is a solid use case for telemetry priority or being able to put receiver internal sensors onto the S.Port/Fbus bus. I'd actually prefer the latter because then you wouldn't lose important receiver info when that receiver drops connections.

**Comment by noamkrief** [comment]
@mawzthefinn that's right. You will only lose the built-in telemetry sensors to the TDR18
