### ISSUE TITLE
Stick - dead zone setting

### ISSUE THREAD

**Issue by phil2626** [FrSkyRC/ETHOS-Feedback-Community#308]
Sender X20 - 1.06 firmware

Hello, unfortunately there is no possibility of setting the dead zone for the transmitter sticks, the potentiometers are already shaking in the 1-3 us range, which cannot be eliminated via calibration. You can also see this in the ADC value range monitor.

You need a dead zone setting for the control sticks.

**Comment by loetefix** [comment]
or a better adc noise filter at least for showing values and bars on the display.

**Comment by aalain8** [comment]
The problem is the same on the X10.
Alain

**Comment by FLYRAPTOR** [comment]
when approx is released the firmware 1.0.11 that resolve the problem of dead band zone stick  ?

**Comment by bsongis-frsky** [comment]
when it will be ready and after the release candidates cycle

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128888007-83f7de9a-0558-402c-a301-f63204e24773.png)
