### ISSUE TITLE
X20 PRO - Impossible to get +/-100% on analog inputs (sticks, sliders, pots) despite calibration

### ISSUE THREAD

**Issue by Didier-L** [FrSkyRC/ETHOS-Feedback-Community#3081]
I have an issue with my X20 PRO (fw 1.4.14).
I performed the hardware calibration many times without any improvment. When i set a mixer (whatever the mixer), the value of the analog input (ie elevator stick) never goes to 100% (or -100%). Depending maybe on temperature (very minor variation), I get between 99.2% and 99.8% but never100%. I even get (from time to time) 98.8%.
I use a slider to adjust the gain of the SR10 (mixer with 50 / 50 / 50) and at the lower position, I never get 0%.
It should be maybe necessary to "filter" the min and max by giving 100% to a analog physical input value between 99% and 100%.
I never seen this behaviour on my X10S and good old Tanaris B.
Didier

**Comment by mawzthefinn** [comment]
When calibrating sticks, use a '+' pattern and do not push the stick at all, cycle it gently until it brushes the end of its travel.

If you use any force, or a circular pattern, what you are seeing will result.

**Comment by Tonio62** [comment]
Pareil pour moi, sur tandem XE, il faut forcer un peu sur les commandes pour obtenir 100%

**Comment by Didier-L** [comment]
> When calibrating sticks, use a '+' pattern and do not push the stick at all, cycle it gently until it brushes the end of its travel.
> 
> If you use any force, or a circular pattern, what you are seeing will result.

Sorry but at 1000€+ transmiter, I am expecting it to work at least like my 60% less X10S or even lower Taranis B... And the problem exists also for sliders and pots and I do not force at all, I tried also single patterns without any success ! There is a filtering for center positions, something has to be added for end positions for all analog "physical" inputs.
It is quite simple to put a filter that takes only 98% or 99% of travel stick/sliders/pots during calibration to output 100% and the remaining 1% or 2% are "flat" at 100%.

**Comment by Didier-L** [comment]
> Pareil pour moi, sur tandem XE, il faut forcer un peu sur les commandes pour obtenir 100%

Même en forçant, je n'arrive pas à 100%.

**Comment by bsongis-frsky** [comment]
Il faut calibrer en faisant un + , pas un x
Il y a toujours un peu de dérive dans les coins

**Comment by Didier-L** [comment]
> Il faut calibrer en faisant un + , pas un x Il y a toujours un peu de dérive dans les coins

J'ai déjà essayé cette méthode mais cela ne change absolument rien et ne résout pas le problème avec les potentiomètres latéraux ou je n'ai pas non plus +/- 100%.
Sur une marque qui semble prétendre rivaliser avec Jeti (par exemple), on ne peut pas baser une calibration correcte sur la seule dextérité du pilote, cela fait un peu "bricolage". Il faut une procédure robuste, fiable et répétitive qui absorbe ces dérives, ce qui n'est pas le cas à ce jour. Une des façons d'absorber ces dérives est la solution que je propose (il y en a peut-être d'autre). Je me répète, le problème ne se limite pas qu'aux manches. Merci.

**Comment by bsongis-frsky** [comment]
> It is quite simple to put a filter that takes only 98% or 99% of travel stick/sliders/pots during calibration to output 100% and the remaining 1% or 2% are "flat" at 100%.

Done. With 0.5% it's perfect here
Will be applied in 1.4.15

**Comment by Didier-L** [comment]
Merci pour le filtrage mais ce n'est pas suffisant sur mon émetteur (version 1.4.15). Avant, je ne dépassais pas 99.2% à 99.5%, maintenant, je ne dépasse pas les 99.7% ou 99.8%. J'ai refait la calibration très doucement comme indiqué et cela plusieurs fois => même résultat. Les 0.5% ne suffisent peut-être pas avec tous les hardwares.

**Comment by Tonio62** [comment]
Pareil de mon côté, je ne pense pas que ça ait une incidence dans la réalité, mais c'est tout de même plaisant de voir tout à 100%, et de ressentir ce sentiment de précision ;)
