### ISSUE TITLE
CRSF

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#3083]
after updating to 1.5.0 on x20 crsf config under ext rf unit  no longer works shows tx module and reciever but when  you click on tx module all that is shown is bind no other configuration

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1d4d8279-9ffd-42e7-a2e7-f155409b19ca)

**Comment by bsongis-frsky** [comment]
Script updated, you have to use the one in the 'nightlies' branch

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/nightlies/lua/crossfire
