### ISSUE TITLE
Registering a TD rx with custom channel assignments resets the rx

### ISSUE THREAD

**Issue by Joey3dee** [FrSkyRC/ETHOS-Feedback-Community#3084]
I frequently register my planes to either my x20s or my x20pro depending on the application or who is flying the plane. Unfortunately; the tdr18s I use reset when re-registering. This is very problematic with some outputs set as f-port, sbus or changed from default pwm outputs. I think that the RX should retain these settings and perhaps there could be a reset option when registering the rx.

**Comment by mawzthefinn** [comment]
Registering is functionally a reset, but so long as you use the same Owner Registration ID on all transmitters and rebind or the Share feature, you should never need to re-register to move between radios.

I move models between my various ETHOS radios all the time and never re-register.
