### ISSUE TITLE
[lua] how to get both 2.4g and 900m VFR

### ISSUE THREAD

**Issue by koakumaping** [FrSkyRC/ETHOS-Feedback-Community#3085]
both in telemetory is VFR
Q: the `system.getSource('VFR')` is the 2.4G or 900M?

**Comment by bsongis-frsky** [comment]
In Ethos 1.5.0 you will be able to differenciate the 2 bands this way:
`system.getSource({name='VFR', band=0)`
or even:
`system.getSource({name="VFR", module=0, band=0})`
