### ISSUE TITLE
Probleme enregistrement et bind twgr8

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#3087]
Bonjour,
Je viens d'acquerir un récepteur twgr8, mais je n'arrive pas à l'enregistrer...

Sur ma tandem xe avec le dernier Firmware, je ne trouve pas le mode TW comme indiqué dans la notice du récepteur. ( uniquement access, accst d16 et td )
Ai je loupé quelque chose ?
Merci d'avance ;)
Antoine

**Comment by bsongis-frsky** [comment]
La XE est une radio TD, pas TW !

**Comment by Tonio62** [comment]
Ah ok....
J'ai mal compris le principe....
Erreur de ma part.....
