### ISSUE TITLE
CRSF LUA

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#3088]
added nightly crsf lua on ethos 1.5.0 on x20 tx module settings works fine but try alter rx through lua x20 goes into emergency mode

**Comment by bsongis-frsky** [comment]
I have reproduced a crash on simulator, which I have fixed just now, I would appreciate if you can check the next nightlies (they will start in 1 hour and will be finished tomorrow morning, FR time)

I keep the issue open, waiting for your feedback

**Comment by stubugs** [comment]
ill try tomoz thankyou

**Comment by stubugs** [comment]
working all good now thankyou very much
