### ISSUE TITLE
TELEM MIRROR

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#3089]
would it be possible to select int bluetooth on x20 to mirror telemetry to telemetry viewer on android phone

**Comment by mawzthefinn** [comment]
Yes, that's already possible to do now. In System->Wireless set your Bluetooth mode to Telemetry.

The main holdup is there's no really good Android app for displaying telemetry. The FrSky app is basic but functional

iOS users have the excellent (but paid) iMSB FrSky app.

**Comment by stubugs** [comment]
on my x20 there is no wirless selection under system 1.5 nightly

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1ede22f5-888d-449d-a3d1-f406b50b629c)

**Comment by stubugs** [comment]
cheers which part is mirror or is it mirror because its under telemetry

**Comment by stubugs** [comment]
working with telemtry viewer
![Screenshot_20231125_172406_Gallery](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/34194921/29430d46-a0c8-4344-a0e1-8d77c0eb966b)
