### ISSUE TITLE
support for Hitec receivers

### ISSUE THREAD

**Issue by andika207** [FrSkyRC/ETHOS-Feedback-Community#309]
I want to know if the X20 could just support Hitec receivers with a firmware update

https://www.rcgroups.com/forums/showpost.php?p=46766305&postcount=3976

**Comment by andika207** [comment]
this thread got closed without any reply from ETHOS devs ? @bsongis-frsky

**Comment by skyfly74** [comment]
Stay serious please dont waste the time of the devs! ETHOS is not made for mutliprotocol support. It is FRSKY and i will be glad it work perfectly with frsky receiver that's all.

**Comment by andika207** [comment]
@skyfly74 did you read the RCG link content ? 

Vantac and Delta are genuine Frsky products https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/7

**Comment by bsongis-frsky** [comment]
@andika207 this is a question for the RF team, not Ethos

FrSky will keep focus on his own products, there is a nice amount of time to spend on ACCESS if we want it benefits from possible new interesting features.

**Comment by andika207** [comment]
Not sure why should I have to request this elsewhere because it concerns a firmware update according to the RCG link. 
The X20 is backward compatible with ACCST D16 so I am pretty much convinced it might also support Hitec receivers if you want it to. @bsongis-frsky

**Comment by andika207** [comment]
> ETHOS is not made for mutliprotocol support.

you were wrong as usual https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1455#issuecomment-1038193008

**Comment by andika207** [comment]
>ETHOS is not made for mutliprotocol support.

@skyfly74 you were wrong as usual https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1455#issuecomment-1038193008

**Comment by bsongis-frsky** [comment]
Hitec will be supported when #5 (Multi) will be addded
