### ISSUE TITLE
Gyro improvement request

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3090]
Not specific to RB35S (but that's what I have)

I'd like to control gain per control surface while flying.
Currently the main gain knob controls all 3 (elevator, aileron, rudder).

Maybe we can have a field in the LUA:
Master gain controls:
1) all
2) elevator only
3) rudder only
4) aileron only

Then I can do a total of 3 flights, and fine tune the gain individually on each surface. 
The method is for example:
Increase rudder gain until the tail starts to "fishtail/oscillate" then reduce a bit for buffer.

So what I'm talking about is isolating each gain from the others.

Then, it would be amazing if in telemetry we can capture what the gyro is doing, per control surface.
If I see a roll moment/bank angle change with no gyro input & no stick input, I know it's wind/turbulence.
Then 10ms later, I can see the gyro aileron correction via telemetry and see the result bank angle. Ideally, returning to original bank angle.
If it overcorrected, or under corrected, the data will show it. So that would be a scientific approach to adjust the gain.

Thanks

Further thoughts:
Gyro oscillation is dependent on airspeed. Ideally to be mixed with pitot. But it's a dangerous situation since if a bee blocks the pitot, it will read 0knots and max out the gains.

Therefore gain settings should be set per configuration.
Overall philosophy, "max gain without oscillations"

I would have 3 total gains depending on flaps which directly correlate with maximum speed (realistically)
- With flaps up, the highest speed is at full throttle in a dive. The gain should be maximum without oscillation.
- With flaps approach, there is a certain speed I don't usually exceed. There will be gains for that.
- With flaps land, there is a certain speed I don't usually exceed. There will be gains for that.

**Comment by kitchenman** [comment]
NICE. I agree. One knob for all gains is elementary.  Ability to set different gins to different buttons,  especially the 6 ones on the lower front would be most excellent
