### ISSUE TITLE
Is there LUA playText() for X20Pro

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3092]
In the reference I see playNumber() playFile() etc...

Is there playText() for X20Pro?

If so, it's too bad it cannot be tested with the ethos simulator because the simulator is X20S and cannot to text-to-speech.
Thanks

**Comment by bsongis-frsky** [comment]
`playText(...)` added to Lua now
It cannot be simulated as it uses an hardware chip on X20 PRO

**Comment by noamkrief** [comment]
@bsongis-frsky YOU ARE THE BEST! Closing ticket.
