### ISSUE TITLE
Butterfly slow down/up for single Channels (ailerons, flaps, elevator).

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#3094]
TX Hardware: Tandem Frsky X20S
TX Firmware: Ethos 1.4.14 FLEX, TD-ISRM 2.2.6
As reference see ticket  #1763 the was closed.

In the Butterfly Mix you can change ONLY the weight for single channels. In some glider (F5J) you need to set a the speed, mainly the slow down in the ailerons  & Flaps to set the correct paths during the butterfly mode, This was possible in the openTX fw...

I know that you can set it, as I did, with three different mixers, two with ailerons & flaps with the slow down/up and one for the elevator without and slow down/up.

It will be nice to have as well in others predefined  mixer as Camber used for thermal  conditions.

Please let me know if you need other details

Franco

**Comment by mawzthefinn** [comment]
Butterfly is intended for an analog input, normally your spoiler stick.

 You should never need speed set in an F5J setup, butterfly should be on your spoiler stick. Paths will be correct if the flaps are balanced in Outputs

Camber is normally linked to flight modes and uses the flight mode fade in/out for slowing application.

**Comment by fdapport** [comment]
Thanks for your quick feedback, I use, as you say, the stick for the butterfly but sometime if I use it to fast the glider for aerodynamic force on flaps/ ailerons /elevator  still move the nose up depending on the speed down of the stick. For good pilots that could be not a problem if they are able to use the stick with the same speed down, theoretical you are right!!. Consider that the best  adaptive firmware that I have used (openTX) have this  feature.  In additional of that  other brands ( ess Futaba) have this parameters on butterfly (see Futaba manual of 12FG page 94) and also in other  predefined mixes. For the Camber I will tray  additional test because the delay happen only for same sequence flight modes, probably I need to change the priority of the flight modes to set it. As I say it is same think that could be nice to have, if you will not implement it I will use free mixes to have this features and the predefined mixes will be not used.

Thanks again for your answer,

Franco

**Comment by mawzthefinn** [comment]
The answer to a fast application of butterfly/crow is an elevator curve, not slow. The reason for this is that the pitch input from flaps is non-linear (there's more in the early flap deployment) and so you need a curved elevator compensation to properly dial it out. Using slow is just putting a patch on the issue by slowing it down enough that you can compensate manually for the pitch input from the flaps.

A good elevator curve will address the pitch up under rapid deployment. Note that curves can be tuned in flight in 1.5.0 using VAR's, so it will be very possible to dial in exactly and tune that pitch moment.

**Comment by fdapport** [comment]
Thanks for your answer, I will follow your suggestions and wait the 1.5.0 version e try to set up it in flight. 
Franco
