### ISSUE TITLE
S8R RECIEVER d16

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#3095]
using x20 s binding to s8r in d16 mode int rf  lua for adjusting setting up works great 
trying multi module on newest firware binds to d16 s8r and gets telemetry but 
the lua does not talk to s8r for adjustments

**Comment by mawzthefinn** [comment]
You should not use the Lua for setting up an S8R, only the Device Config SxR menu.

multi-module is not supported for setting up these receivers, use internal RF.
