### ISSUE TITLE
RB35S and Swiwin ECU telemetry bug

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3096]
I can confirm the following issue exists on RB35S
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2629

TDMX or TDR6 connected to RB35S via FBUS mode
RB35S S.Port out to Swiwin ECU on Ch24

Swiwin ECU telemetry items going in and out. (turning red, then back to white) About every 5 seconds or so...

The temporary fix is:
TDMX or TDR6 connected to RB35S via SBUS mode. In SBUS mode, the telemetry items are 100% reliable and NEVER drop off.

**Comment by bsongis-frsky** [comment]
Related to https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3099?

**Comment by bsongis-frsky** [comment]
I forward it to the right team then, it doesn't look like related to Ethos

**Comment by noamkrief** [comment]
For some reason TDMX v1.0.11 + X20pro TD Pro 1.1.12 I cannot replicate this issue.
I just tested and Swiwin ECU is working perfect even in FBUS mode now!
Thanks! Closing ticket.
