### ISSUE TITLE
Frsky ESC and telemetry doesn’t work for neuron II 80a after update.

### ISSUE THREAD

**Issue by Eduardoesteban1694** [FrSkyRC/ETHOS-Feedback-Community#3098]
I updated tx x18s to ethos 1.4.14 and rx TD-R10 to the latest firmware and the lua tool for Frsky ESC stopped working. Telemetry also stopped working, only works for a few seconds and o get “sensor lost” alarm. 
I downgraded the rx to 1.0.9 and telemetry seems to work, but when I open Frsky ESC lua app I got “sensor lost” again and telemetry never recover until I disconnect and connect the battery.

**Comment by mawzthefinn** [comment]
Did you update your TD ISRM to 2.2.6?

The latest TD receiver firmware wants the latest TD ISRM Firmware.

**Comment by Eduardoesteban1694** [comment]
Yes, I updated but it worked worst so I downgraded it to 2.2.2 and it worked, not correctly, but better than with the latest version. 

Another issue that I found is that with version 2.2.6, when discovering sensors, some appear even when the receiver is turned off, for example one appears to me that says "R9M power" and a value of 10db

**Comment by mawzthefinn** [comment]
R9M power is telemetry from the RF Module and should be present whenever the 900M section is powered on.

**Comment by Eduardoesteban1694** [comment]
@mawzthefinn thanks, I updated TD-ISRM to 2.2.6 and TD-R10 to 1.0.11, telemetry worked, but I still have the issue that I only can enter to Frsky ESC lua once. If I go out and re enter to the app, I can´t configure nothing and also if I enter to Frsky ESC lua I automatically lost all sensors of Neuron ESC, I have to unplugg and plugg de battery to recover sensors because it doesn´t recover.
It doesn´t happen before the update so I don´t remember what versions I had, only remembrer that I have never update TD-ISRM firmware so I assume that I had 2.2.2

**Comment by Eduardoesteban1694** [comment]
@mawzthefinn Could it be that it is an incompatibility error of the Frsky ESC script?

**Comment by mawzthefinn** [comment]
There's an updated script here:

https://www.rcgroups.com/forums/showatt.php?attachmentid=17838339&d=1701765481

And a recommendation to update to ETHOS 1.4.15 as well

**Comment by Eduardoesteban1694** [comment]
@mawzthefinn Thanks!, It works perfect. Problem Solved!
