### ISSUE TITLE
"Sensor Conflict" when plugging in FAS40

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3099]
After some testing, I'm 100% certain it has something to do with the Swiwin ECU(V3).

The FAS40 has 2 sensors: VFAS "02 0210" and CURRENT "02 0200".

The Swiwin also has VFAS "04 0210" and CURRENT "04 0200"

The conflict is not do to same names. I renamed, and still get "sensor conflict".

I know I can just delete the "wav" file to make it stop alerting me. But that's not a great solution :)

My setup:
X20Pro
TDMX  to RB35S Sbus mode
RB35S ch24 set to S.Port
Ch24 -> FAS40 -> Swiwin ECU

I'm happy to help troubleshoot.
Cheers!
Noam

**Comment by MAX767300ER** [comment]
> You have to change the AppID either on the VFAS or in the Swiwin ECU Because you are not allowed to have AppID = 0x0210 and 0x0200 on 2 different devices. Just choose 0x0211 and 0x0201 on one

Hi, apologies for reopening!
Can I get to know how the above is done? Running on ethos 1.6

Thanks!
