### ISSUE TITLE
Mixer name not showing up on the Outputs

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#31]
Radio- X10S Express
F/W- 0.0.17

After adding a “Free Mix” the title for the mix does not display in the “Outputs”. Aileron, Elevator, Rudder, Throttle Flaps 1 and 2 do display correctly.

![20210405_105107](https://user-images.githubusercontent.com/81670152/113596300-1fa8e800-9608-11eb-8778-17abe8440f0f.jpg)

![20210405_105152](https://user-images.githubusercontent.com/81670152/113596863-e624ac80-9608-11eb-8c50-945da1cf986d.jpg)

**Comment by Liverboy77** [comment]
For free mixes you have to click on the output channel and name the mix.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/114012351-81ff2400-9866-11eb-98ce-93388479cce5.png)
