### ISSUE TITLE
Aileron Differential Source Channels 

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#310]
x20S 1.0.7
Channel as source is not working 
istead of channel mixer value is used

**Comment by MIKE-DAILEY** [comment]
Working OK here.  To test I created a free mix with a switch as a source and CH6 as the output.  Then I went to the Aileron differential and long pressed the the differential to get the selection popup and selected CH6.  The Free Mix switch changes the Aileron differential as expected.

**Comment by Cipta-de** [comment]
I have used a var mix
source pot 3 output ch21
in ch 21 I reduced min max to 30
in Aileron mix er source for differential ch21 
when I move the slider i still have -100 to 100 value

**Comment by MIKE-DAILEY** [comment]
Sorry I don't understand.  Could you please post the Var screen and your Aileron mixer screen.

**Comment by loetefix** [comment]
You have to use a free mixer instead a var and reduce the the weight there to 30. the limit in output is only for servo-outputs.When The ch21 source selection in differential is taken before the servo limit-settings.

**Comment by Cipta-de** [comment]
Thank you verry much for the fast response :-)
I know its possible with a free mixer but in my understanding if I use chanel for a var input it should use the chanel output. 
I mean in the output it is shown the green Mixer and the yellow Chanal - more logical for me would be to use the outputs
anyway - why do I have to go around the corner and first occupy a channel if I had a var mixer in which I could adjust everything?
Or if I wanted to avoid it - the input can already be set in OTX.
Just thoughts and ideas - there are some better solutions in Ethos than OTX - I like Ethos and your work.

**Comment by loetefix** [comment]
The output adustment is only for limit adaption of servo or FC i think. so you can adapt 100% mixer is allways 100% servo or FC.But i agree in var mixer there should be a weight position.

**Comment by Cipta-de** [comment]
Ok -thanks for explaining
may we should rename the isue or open a new one for integration of a limit to VAR Mix.

**Comment by hrenz** [comment]
Weight alone is too less
2 things always belong together
Weight and Offse
or 
a curve

**Comment by Cipta-de** [comment]
Thats correct - thanks
maybe there should also the possibility to select flight mode like in other mixers

**Comment by MIKE-DAILEY** [comment]
> Ok -thanks for explaining
> may we should rename the isue or open a new one for integration of a limit to VAR Mix.

Will close this issue.  There are other VAR issues saved here that you can review.
