### ISSUE TITLE
usb issue on twin x lite

### ISSUE THREAD

**Issue by philippe91580** [FrSkyRC/ETHOS-Feedback-Community#3100]
When I connect a twin x lite radio via usb in "bootloader" mode, the text on the radio's screen flashes from "bootloader" to "usb connected". If I connect the radio via USB when it is on, the connection menu appears then disappears without stopping. With an X20S, it works!

**Comment by mawzthefinn** [comment]
That sounds like a hardware issue with the USB port on your radio. I would contact your local FrSky service department

The Bootloader and ETHOS are separate and it's doing the same thing on both, so it's unlikely to be a firmware issue.

**Comment by mawzthefinn** [comment]
Closing off, radio needs a trip to the service department

**Comment by Edlightenme** [comment]
so i am currently trying to update the bootloader, i already updated the firmware. when i try the dfcu flasher and follow the step my controller just stays on "usb connected" its like on a soft freeze that i cant get out of.
