### ISSUE TITLE
1.5.0 Trim mixer

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3102]
Hello, there is no trim mixer in 1.5.0. Is a replacement planned?
Wolfgang

**Comment by mawzthefinn** [comment]
Replacement is already present. You can now add additional Trim functions in the Trims menu. They can be applied as a source in a Free Mixer line for direct duplication, or as an Offset if you want to add trimming to a free mix which already has a source.

VAR mixes are similarly replaced by VARs + Free mixes (or multiple Offset lines in a Free mix)

**Comment by Wolepo** [comment]
Thanks for the explanation
