### ISSUE TITLE
X20 system icons

### ISSUE THREAD

**Issue by Bleroodes** [FrSkyRC/ETHOS-Feedback-Community#3104]
Not everyone uses the X20 for aircraft.  Specifically, I will handle a crawler loader with it.  The second icon at the bottom of the display is an airplane.  If I open it, the 3rd icon on the top line is also flying.  If I do custom settings on the x20, why can't I choose custom icons.  There are only flying vehicle icons in the system itself, but not everyone uses the x20 to control planes.  There could be a choice, e.g.  water vehicles, land vehicles (car, truck, wheeled and tracked loader or excavator...) So whoever chooses what, an icon will appear at the bottom of the display and in the menu.  I don't speak English, so if the description is confusing, I'm sorry.
This development would be a huge step forward for those who have more than just an airplane!

**Comment by strgaltdel** [comment]
As mentioned on rcg, 
actually you can design your own icons and you can exchange this for the standard (files),
Your goal can therefore easily be achieved through your own actions

**Comment by Bleroodes** [comment]
Ok, thanks, I'll do it if there's a way.  Where can I find the description?

**Comment by Bleroodes** [comment]
> Ahogy az rcg-n is említettük, tulajdonképpen megtervezheti sajá

**Comment by strgaltdel** [comment]
i would download the simulator and practise it this way:
- by installing sim it creates all neccessary  subfolders of the sdcard / internal storage
- look into / bitmaps folder and select the icon you want to change (and make backup copy)
- design a new bitmap (png format), equal resolution, using same filename
- restart

**Comment by strgaltdel** [comment]
ah, sorry,
rcg = short form of the "rcgroups forum"

i guess we discussed your request here
https://www.rcgroups.com/forums/showthread.php?4061129-FrSky-Tandem-X18/page58

**Comment by Bleroodes** [comment]
> ah, elnézést, rcg = az "rcgroups fórum" rövid formája
> 
> azt hiszem itt megbeszéltük a kérését: https://www.rcgroups.com/forums/showthread.php?4061129-FrSky-Tandem-X18/page58

These are my questions on rcg.  I didn't see the new post, I was last there before yesterday.  Thanks.
