### ISSUE TITLE
M-Link multiplex Telemetry

### ISSUE THREAD

**Issue by olivierpo44** [FrSkyRC/ETHOS-Feedback-Community#3105]
Hello,

I using a lot of multiplex M-Link receiver.
Will Telemetry bé available with this protocol in 1.5.0?
Thanks

**Comment by bsongis-frsky** [comment]
Someone is sending me a Multiplex receiver so that unless something goes wrong, it will be available in 1.5.0

**Comment by bsongis-frsky** [comment]
Multiplex receiver received.
I will add to 1.5.0
- iRX4 firmware update
- multiplex telemetry

**Comment by olivierpo44** [comment]
I’m glad to be of help.
Thanks you for the very good job done!

**Comment by bsongis-frsky** [comment]
#1861 is included in 1.5.0, so my multimodule is up to date :)

**Comment by bsongis-frsky** [comment]
![screenshot-multiplex](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/44b5011e-fc6e-4966-ae3a-04ec354c1d0b)

**Comment by olivierpo44** [comment]
Thanks you. Good job!

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by olivierpo44** [comment]
hello,
there is no failsafe available on m-link via multimodule. on 1.5.0 rc1 eu
![PXL_20240127_223639722](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/147919601/a3926081-8630-4c8d-b72d-231d8aeba460)

how can i send failsafe information to the receiver?
thanks
