### ISSUE TITLE
Eject Drives not appearing in ETHOS Suite 1.4.14 (MAC)

### ISSUE THREAD

**Issue by GWCTas** [FrSkyRC/ETHOS-Feedback-Community#3116]
The option to Eject Drives no longer appears in ETHOS Suite 1.4.14. I have to eject via Finder.
<img width="1190" alt="Screenshot 2023-12-03 at 3 16 09 pm" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/21648982/5814cc32-fbd0-402b-b643-64cd9f3e38e4">

**Comment by mawzthefinn** [comment]
Your drives are not detected by Suite in that screenshot. 

If you do not have SD version and Audio version reported, Suite has not detected the drives (and thus won't show the option to eject).

Restart Suite with the radio still plugged in and it should work.

**Comment by bsongis-frsky** [comment]
Are the drives available in your Finder?

**Comment by Nicholas-Luoyi** [comment]
Is there any way for me to stably reproduce it? I cannot get it here

**Comment by mawzthefinn** [comment]
MacBook Pro M1 on latest Mac OS 14 Sonoma and if Suite is open when I plug the radio in, I get the screen above. When I plug the radio, then open Suite, it works beautifully.

**Comment by Nicholas-Luoyi** [comment]
Oh. Would it be a differences because of the CPU? Because I only have a Intel chip for my Mackbook pro. Mac OS is Ventura 13.5.2

**Comment by mawzthefinn** [comment]
CPU or OS, there's USB and drive detection changes in Sonoma as far as I'm aware.

**Comment by Nicholas-Luoyi** [comment]
I will make a upgrade for the side packages of Suite to see if it will go better.

**Comment by mawzthefinn** [comment]
Yes, 1.4.15 Suite seems tobe detecting correctly now when the radio is plugged in after Suite is opened
