### ISSUE TITLE
Tandem X20S

### ISSUE THREAD

**Issue by przepka1985** [FrSkyRC/ETHOS-Feedback-Community#3118]
Why im not able to use my model images after update to 1.4.15 (1.4.14 as well)? 
My radio its Frsky Tandem x20S up to date fw, bootloader, isrm sd card content (audio and images)
Image size 300x280 bmp less than 11 haracters long, and bmp file extension
Bidmaps are located like before update //sd/bitmaps/user
When im clicking on model image, it's no images names shown anymore (not even factory stock ones) just 3 dots (...) 
![02933_x20](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25909232/a63489cf-086a-4874-8130-fde67be67838)
![02509_x20](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25909232/0d8dff47-853a-4772-af6d-6bf5d4fff58e)
![Zrzut ekranu 2023-12-05 144052](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25909232/11bcae64-3cb3-415a-904b-65f849481905)
![Zrzut ekranu 2023-12-05 144104](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25909232/2639a8d6-b04c-4923-8a44-57e0e3040788)
![Zrzut ekranu 2023-12-05 144148](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25909232/f4a72d50-5cac-4ac6-9843-55ccab395d1d)
![20231205_144221](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25909232/f1bd1da1-b0fa-4cc6-a416-6930af741ad2)
![20231205_144239](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25909232/0d0bc60e-7dca-49bb-9161-7bdb919efc1a)

**Comment by mawzthefinn** [comment]
Model image files have been in /bitmaps/models/ since v1.2.6

Please move them to the correct location.
