### ISSUE TITLE
Emergency Mode ?

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#3119]
X20Pro with 1.4.15.   While working on a configuration for a long time, the radio popped up with a "Battery Low" message on the screen with a greyed out "OK" button .   There was no response from the radio as I tried to click the OK button.  
As nothing was happening I tried clicking the screen behind the message a few times.  At this point, it went into Emergency Mode and bleeped at me.  
Should I have just stopped what I was doing and switched the radio off to recharge?
Or should I have been able to OK the message and continue ?

Thanks for all the great work you are doing.

**Comment by mawzthefinn** [comment]
Sounds like the battery is fully drained. Recharge it.

**Comment by kramgrand** [comment]
Hmmm not sure about that.   My unit is setup to warn of a low TX battery at 7.5v. = 3.75v per cell.   Well within limits and approx 25% remaining charge.

**Comment by bsongis-frsky** [comment]
In which screen were you when the popup raised?

**Comment by kramgrand** [comment]
I was in the mixers screen.

**Comment by kramgrand** [comment]
Hi, I will put it on charge again and get back to you on that.   
Thanks.

**Comment by kramgrand** [comment]
Hi, After charging the voltage display registered 8.4v at switch on.

**Comment by kramgrand** [comment]
I let the battery run down and this time the "Low Battery"  Functioned correctly.  I was able to OK the message and carry on.
I am wondering if it just had a wobbly moment before as I was in the mixer configuration menu at the time changing values etc.    
If you guys are not too concerned about it, please close it off.

**Comment by kramgrand** [comment]
Seemed to have been a one off occurrence.
