### ISSUE TITLE
Expo position in each dual rate position. 

### ISSUE THREAD

**Issue by Abdalla737** [FrSkyRC/ETHOS-Feedback-Community#312]
I’m trying to set exponential in each dual rate position (3), but in the mixer page i have curve for 3 positions not for each one!

**Comment by MIKE-DAILEY** [comment]
X20S ETHOS 1.0.7.  Is this what you want? 

![screenshot-2021-05-22-76918](https://user-images.githubusercontent.com/11791852/119245055-189c5180-bb44-11eb-9368-faedf15f3a02.jpg)

**Comment by Abdalla737** [comment]
Yes, this is possible only in the latest atualization? And do you know how to setup delta wing on it?

**Comment by MIKE-DAILEY** [comment]
See #311 delta wing.
