### ISSUE TITLE
TW SR12 won't go to self check

### ISSUE THREAD

**Issue by BoltTed** [FrSkyRC/ETHOS-Feedback-Community#3120]
For FrSky TW SR12 and X20 Pro, anyone had success setting Self Check to "Enable" in LUA SRX Stab.  For me, cannot enable self check.

I have AETR (CH1-4) and I have GAIN setup to CH13, Modes to CH14. Ran LUA SRX Calib to successful calibration. My throttle is check at -100, When start the Lua SRX Stable, turn on Stabilizing, set self check to enable, but it won't let me.. it goes back to disable right away. Is there something I missed. Thanks.

I already update everything with latest ..
TWSR12 firmware 1.0.6,
X20 Pro to 1.4.15, ISRM 1.1.12.
using Lua 2.0.6.

**Comment by mawzthefinn** [comment]
What is the LED doing on the radio. The Self-Check switch in the Lua is effectively a momentary, it doesn't stay there, just triggers self-check.

**Comment by BoltTed** [comment]
I'm using the Lua script. It does NOT flip to enable, as it stayed with disable.. but was able to see the light flickering, then I moved the sticks around, then after the light stop flickering, it does it self checking.. then solid light.

It could be that Self-Check displayed "Enable" to quick to see .. or FrSky made it that way..

**Comment by BoltTed** [comment]
Yes, thank you.
But you should report it as minor issue. Either FrSky need to update the manual to say so and tell user to don't expect to see the enable appeared otherwise, or update the SW to display enable until after the test is done.. otherwise user will get lost.
