### ISSUE TITLE
1.5n: model conversion from 1.4.15 fails (FREE mixer is using VAR mix for up/down weight)

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3121]
in case a free mixer is using VAR mixer channels for up or down weighting the conversion fails

screenshot of a 1.4.15 free mix using ch61 & ch62 VAR-Mix outputs for weighting:

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/54fb9d0e-b2b2-4198-9ed9-4a24fb9cba37)

1.5 correctly adds new GVAR items instead of var mixers and deletes the "VAR" mixers,
but the corresponding up/down entries in the free mixer are not "routed" to the new GVAR items but stay on the now "deleted" channel outputs.

**So we've the value ZERO for weighting which "neutralizes" the free mixers
This could be very harmful for main functions**

proposal:
(1)
in case the migration process finds VAR mixers and migrate them to GVARS, all entries with reference to VAR channels have to updated to the corrrsponding GVARs

or, in case this  implementation will be too complex:
(2)
add GVARS for every VAR mixers as has beeen done now, but don't delete the var Mixers and let the user change the corresponding entries to the GVARS, so the model template will stay plausible / in function after migration

attached a sample of a simple 1.4.15 model

the problem occured on sim & X18s firmware 
dated 12.05.2023
i didn't test for more failures of this kind, but i'm pretty sure the problem exists not only on up/down "Var Mix" weighting

[convert.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13578874/convert.zip)

**Comment by bsongis-frsky** [comment]
Won't do. It's too complex and almost to do it right in all cases. 
Instead a warning will be added to the release notes

**Comment by Dsrenger** [comment]
WTF

This will destroy most of my model programs.

Routing vars to channels and then to mixers was always the communicated way to use.
Good luck repairing gliders programs with a lot servos and flight modes.

Guess my transmitters will never leave 1.4.xx

**Comment by strgaltdel** [comment]
I can feel the pain&frustation & understand the 1.5 aversion under the given circumstandes,

i'm more the guy with an "make the best out of it" attitude,
and so i'll start to migrate manually, the new "gvars" offers plenty of possibilities.


What i would like to see is a sort of "understatement" that an existing and functional 1.5n template file won't be definitive unusable by a newer nightly or release candidate.
There may be cases where a new nightly might "break" a model file, but it should be possible to reuse the (backup) file in one of the successor nightlies, so that all the work won't be trash...
