### ISSUE TITLE
Single Lipo cells value 

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#3123]
Hardware:X20S
Ethos Version: 1.1.15
Hardware Sensors: OpenXsensor 

I found in the telemetry screen all the sensors (GPS, altitude, etc), include Lipo total value (6s) but I am not able to set, as I did in OPENTX, the single lipo cells. I do not see any information on the manual. Please help.
Thanks,
Franco

**Comment by fdapport** [comment]
Unfortunately I try but without success, when I do long  press on LIPO in the telemetry screen I see the value of the Sensor, as the attached picture. The ID look like correct according to the Ethos manual.

![20231207_122027](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/622694b6-0b40-4511-b5de-bcd411c24ac1)

**Comment by mawzthefinn** [comment]
Long press the LiPo entry once selected in the display widget or other function using it, not in Telemetry.

**Comment by fdapport** [comment]
I have found it... super great!!!!!! ...thanks, Franco
