### ISSUE TITLE
Issue between TRIM "integrated function" and TRIM mixes

### ISSUE THREAD

**Issue by Didier-L** [FrSkyRC/ETHOS-Feedback-Community#3124]
When I set my 1st model, I did it without using the templates but more like opentx with only free mixers.
Moving the trims (ie aileron) made the bip noise, the "trim centered" message when centered and the trim value changing on the main screen. But no effect on the outputs.
I then added a TRIM mix to get the output moving according to the trim input. The side effect was that from time to time I am now getting twice the message "trim centered" and specific beep with a small offset, one when the trim is exactly at 0 and again when I have around +/- 0.7%. Sometime I get twice the message and twice the center bip, other is one message and 2 center bips.
In order to remove this side effect, I desactivated the trim in the TRIM function => it works, no more double message but I do not have anymore the trim value updating on main screen nor the trim graphic bar moving.

Ethos 1.4.14 and 1.4.15 => same issue

**Comment by mawzthefinn** [comment]
Delete the trim mix, set the Offset in your Aileron free mix to 'Use a Source' then set the source to Trim->Aileron

Then go set your aileron trim to something other than disabled. 

The trim mixes go away in 1.5 anyways, replaced by the ability to create custom Trim Functions in Model->Trims
