### ISSUE TITLE
[Request] Ability to use Function Switches as a Source in Mixers etc

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#3125]
Since these function essentially the same way as any other switches on the radio (Momentary mode acts just like SI and SJ, and any other mode just acts as a 2 or 3pos switch), it should be possible to use them as regular source/inputs in a Mixer.

Currently the only way I've found that it can be done is using a Var mixer, which is fine, but I see no reason to restrict other types of mixers from using them.

I have looked through the GH and did not see other Issues about this but if I missed one and this is a duplicate I can close it.

**Comment by mawzthefinn** [comment]
They function more like LSW's than switches.

But the logic is the same, I can use an LSW as a source now, An FSW should be treated the same.
