### ISSUE TITLE
Performance degradation after update to 1.5

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3128]
After playing around with 1.5 for a while, I had the feeling that the GUI was reacting a bit slower.

So I did a kind of performance test.

The check was done with a "heavily" configured template
(was one of my first, I wanted to build a "one rules it all" template for gliders with up to 8 flaps and several individual functions, which in this configuration should never see the real world, but represents a so called "fat client")

A Lua widget simulates a bit more load by calculating SQR values in  "big loops" in wakeup and paint handler

The widget calculates the average cycle time of the widget (or the number of "calls per second")
and 
average wakeup runtime
and
average paint runtime

The values can be reset by pulling SH to eliminate startup delays or update the calculation

So I ran this combination on 1.4.15, the results can be seen here:

![Perf_1 4 15](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/c72dd97c-5985-4b47-b506-92ffe662d129)

Now I update to 1.5, values :

![Perf_1 5](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/b1662116-8aa1-429d-869b-347d91520177)

All values increased by 50..80 percent !

I don't know if 
(1) this behavior is an accepted side effect due to the more complex functionality of 1.5, or
(2) if it's some kind of "glitch" that can be compensated for.

If (1), please feel free to close the issue and take it as a hint.

attached you'll find the template (1.4.15) and the script

Kind regards
Udo

[PerfCheck.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13613320/PerfCheck.zip)

**Comment by bsongis-frsky** [comment]
Thanks for reporting, I have just found a bug which made the mixer run 10 times more than needed, which dramistically increased the CPU consumption with your model.

After fixing it I notice that the values have lowered by 50%, which is excellent!
