### ISSUE TITLE
Var Persistent not working (Ethos 1.5)

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3129]
Variables do not remember the value present when transmitter (or simulator) is turned off. On my transmitter, it does not matter what the value was when transmitter was turned off, the value always shows 53% when transmitter is turned on. On the simulator, value is always 11% when it is restarted. If I remember correctly, these were the values present the first time transmitter (or sim) was turned off after programming the Var.

**Comment by mawzthefinn** [comment]
Just tested this. Repurpose trim is saving correctly, the triggered operators (addition/subtraction et al) are not saving.
