### ISSUE TITLE
Logic Switch Issue 1.5.0 Nightlies 12/7/23

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#3130]
While trying out a few things on 1.5.0 I noticed that one of the logic switches that I usually use was not working.  It seems that any logic switch I try that uses a Switch as a source does not function.  If I use an Analog or a VAR source then it works.  I then tried a version dated on 11/22/23 and it also did not work.  The only other older version I had was from 6/13/23 and tried it and it worked as it does on 1.4.15.  Also, I get the same results using an XE with the same version. Thanks

**My current version info:**
![screenshot-2023-12-09-28696](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/30ca6f77-549d-42e5-810e-9705a825ffde)

**The logic switch:**
![screenshot-2023-12-09-28064](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/c1cf372c-0b97-4c7e-8c80-53063a90cfc7)

**Using a Var as an alternate source:**
![screenshot-2023-12-09-28114](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/9f5869c1-5519-422a-af2e-0da4db1017be)

The final results using a source other then a switch:
![screenshot-2023-12-09-28150](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/36df36c5-8726-4bf6-b009-bde4fd1c9c48)

**Comment by Wolepo** [comment]
Here is a short video: With ~ the LS works, but the value is divided by 10. With = there is no reaction.

[LS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13623590/LS.zip)

**Comment by Wolepo** [comment]
Model file cannot be reopened after using this LS (v12.12.23)

**Comment by df7320** [comment]
I can confirm something similar.  Every model I bring in from 1.4.15 will open, but when closed and reopened I get the "Invalid Data" error. This is using the version dated for 12/12.

**Comment by df7320** [comment]
Same as #3139
