### ISSUE TITLE
X18 fas40 lost sensor after update

### ISSUE THREAD

**Issue by sharonfridman** [FrSkyRC/ETHOS-Feedback-Community#3132]
Hi,

X18 with tdr10 and fas40 all working.

After x18 ethos update and tdr10 firmware update to the latest versions fas40 sensor lost.

Deleted all sensors and then could not discover fas40 sensors any more.

Your help please

**Comment by sharonfridman** [comment]
Opened a new model, bind the receiver and manage to discover the fas40 sensors for a few seconds until they were lost again. 

Got back to the original model and the same story, discoverd the sensors for a few seconds until they were lost again. 

I manage to see that the adc2 sensor is also lost from time to time

**Comment by mawzthefinn** [comment]
Did you update the TD ISRM on your X18 to the latest? There are telemetry issues if running latest TD R10 firmware and TD ISRM 2.2.4 or 2.2.2 on the radio.
