### ISSUE TITLE
Full NAND (from saving logs) can cause Ethos to slow down significantly

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#3134]
The other day i was holding an X18S in my hands that all of a sudden got extremely slow to respond to menus / voice read out etc. voice was very slow and choppy and could barely switch radio off, it was very slow.
nothing i did could fix it until i connected it to the PC and noticed the NAND got 100% full due to saving logs (radio was set to record logs always).

this issue needs to be avoided in software,  i think this could be a potential major issue.
maybe wrap around the memory before it gets full? or alert the user when memory is 90% full etc on every powerup?

thanks.

**Comment by bsongis-frsky** [comment]
1.4.16 will avoid to attempt to write if the disk is full
1.5.0 will add a new Preflight Check
