### ISSUE TITLE
repo issue: "unstale bot" broken ?

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3135]
hmm,

#2625

- on 5th Nov. the issue was marked stale
- three weeks ago i posted a keepalive to "unstale", but nothing happened (edited post some times, nothing changed)
- 4 days ago i added another posting

the issue remains on status "stale"

something wrong with the bot ?

**Comment by bsongis-frsky** [comment]
It should be good now
