### ISSUE TITLE
Free Mix - not 100% Free.

### ISSUE THREAD

**Issue by Bleroodes** [FrSkyRC/ETHOS-Feedback-Community#3137]
Frsky's remote controls, specifically the X20, are also optimized for aircraft.  I don't use the X20 for an aircraft, but for a crawler loader.  There is a left and right drive.  In the free mixes, logic switches and everything else, it is noticeable that somewhere in the background it interferes with the outputs.  I have found that the settings do not affect the outputs of the right and left sticks equally.  For example, I set up a logic switch function.  The switch itself works perfectly.  But if I specify this as an active condition separately for the right and left channels, it does not modify the outputs equally.  Something is modifying it in the background.  So it would be good to make the Free Mode 100% independent of the basic functions of aircraft.  Thanks.

**Comment by strgaltdel** [comment]
90% of my model templates are based on free mixers (several dozen) and I could never tell.
I'm pretty sure you have another mixer (or output curve, etc) affecting your channels, or,
more likely,
the calibration wasn't done well and you created different "response curves" from your sticks

I would assume you create an empty free mixer with a "higher" unused channel.
 Assign a stick input and check that the output range is between -100% / +100%.
Check all stick inputs.

If they are ok >> do you have some "parasitic" mixers / curves or so affecting your "base channels"
if not >> recalibrate

**Comment by Bleroodes** [comment]
I've tried calibrating several times, I think it's fine.  I made a new model without any curves.  The difference is especially noticeable when I send two inputs (tracks) to one output (sound module).  With a logic switch, I set the higher signal to determine the signal level of the output.  When I test the logic switch, it works as I set it.  Reality is perfect in Forward.  Reverse in :.  when i pull the right lever there is no output signal.  When I pull the left lever, there is no output signal.  If I pull the right lever to 50% and the left lever to 80%, the output signal is only 50%.  So the right lever determines the value of the output signal, but only if I pull the left lever as well.  If I pull the left lever to 50% and then pull the right lever to 30%, the output signal is only 30%.  If I pull the left lever to 50% and then pull the right lever to 70%, the output signal is only 50%.  So it's total chaos in reverse.  I've been suffering with it for days, but to no avail.  My original remote control, which has approx.  Its value is €50, it had much fewer options than the X20, but there were no such problems.

**Comment by Bleroodes** [comment]
> 90% of my model templates are based on free mixers (several dozen) and I could never tell. I'm pretty sure you have another mixer (or output curve, etc) affecting your channels, or, more likely, the calibration wasn't done well and you created different "response curves" from your sticks
> 
> I would assume you create an empty free mixer with a "higher" unused channel. Assign a stick input and check that the output range is between -100% / +100%. Check all stick inputs.
> 
> If they are ok >> do you have some "parasitic" mixers / curves or so affecting your "base channels" if not >> recalibrate

I've tried calibrating several times, I think it's fine. I made a new model without any curves. The difference is especially noticeable when I send two inputs (tracks) to one output (sound module). With a logic switch, I set the higher signal to determine the signal level of the output. When I test the logic switch, it works as I set it. Reality is perfect in Forward. Reverse in :. when i pull the right lever there is no output signal. When I pull the left lever, there is no output signal. If I pull the right lever to 50% and the left lever to 80%, the output signal is only 50%. So the right lever determines the value of the output signal, but only if I pull the left lever as well. If I pull the left lever to 50% and then pull the right lever to 30%, the output signal is only 30%. If I pull the left lever to 50% and then pull the right lever to 70%, the output signal is only 50%. So it's total chaos in reverse. I've been suffering with it for days, but to no avail. My original remote control, which has approx. Its value is €50, it had much fewer options than the X20, but there were no such problems.

**Comment by Bleroodes** [comment]
> 90% of my model templates are based on free mixers (several dozen) and I could never tell. I'm pretty sure you have another mixer (or output curve, etc) affecting your channels, or, more likely, the calibration wasn't done well and you created different "response curves" from your sticks
> 
> I would assume you create an empty free mixer with a "higher" unused channel. Assign a stick input and check that the output range is between -100% / +100%. Check all stick inputs.
> 
> If they are ok >> do you have some "parasitic" mixers / curves or so affecting your "base channels" if not >> recalibrate

Okay, you beat me.  I'll close the issue, but first, please, make a mix mekem.  Left stick forward - backward - left track.  Right stick forward - backward - right track.  So two channels, 4 signals.  Left channel positive/negative, right channel positive/negative.  One output - sound module.  The requirement is that the highest signal always determines the signal level of the comment. 
So here are a couple of examples:
+30/+40 = 40
+70/+10 = 70
-30/+50 = 50 or -50
-40/-40 = -40
-60/-10 = -60
-10/+40 = 40 or -40

**Comment by mawzthefinn** [comment]
What you are looking for is not mixing (which adds, subtracts, multiplies or divides values for all the mixer lines affecting a single channel). I gave you an answer on RCGroups as a starting point. Pay close attention to the Function of each Free Mix, that tells you what it will do with its output and the output of the stack of mixer lines above it for the same channel. 

You need to use Logic Switches to determine which input is the one you want, and select that input's mixer line as the one giving the output.

I would recommend reading Mike Shellim's introduction to how the mixing engine in ETHOS works

https://rc-soar.com/ethos/basics/keyconcepts/

**Comment by Bleroodes** [comment]
> What you are looking for is not mixing (which adds, subtracts, multiplies or divides values for all the mixer lines affecting a single channel). I gave you an answer on RCGroups as a starting point. Pay close attention to the Function of each Free Mix, that tells you what it will do with its output and the output of the stack of mixer lines above it for the same channel.
> 
> You need to use Logic Switches to determine which input is the one you want, and select that input's mixer line as the one giving the output.
> 
> I would recommend reading Mike Shellim's introduction to how the mixing engine in ETHOS works
> 
> https://rc-soar.com/ethos/basics/keyconcepts/

Thanks, I read it, but it didn't get me any closer to solving my problem.

**Comment by mawzthefinn** [comment]
Referring to the RCGroups post, here is the answer for Zero-based selection.

That logic appears to be that you always want the mixer with the higher source channel absolute value determining the output channel value, rather than mixing the two together.

This is quite doable.

You need 1 Logic Switch, 1 Curve and three free mixes to do it.

Lets assume Ch1 is the first source value (Left) and Ch2 is the second source value (Right). The output channel to the sound system is Ch3 (you will change these to match your model)

From Model->Curve, add a new curve, type custom, 3 points, points are 100, 0, 100. Name the Curve 'Absolute Value'

Add a Free Mix, Call it Left ABS, Source is Ch1, assign the Absolute Value curve in the curve section, set the output to Ch64 (so it doesn't take up an RF channel). This converts Ch1's value to its absolute value, so we can compare magnitudes (since there is a |A| > X LS function, but not an |A| > |X| LS function)

Next lets create a Logic Switch, I'll call it Sound Mixer

Function is |A| > X
Source (A) is Ch2 (Right)
Value (X) has to be long-pressed, select 'Use a Source', then select Channels->Ch64 (Left ABS).

You can test this, it will go Active/Green when Ch2 is higher than Ch1, and inactive/Red when Ch1 is higher than Ch2

Now create a Free Mix
Name is 'Sound Left', Source is Ch1 (Left), Output is Ch3 (Sound)

Create another Free Mix
Name is 'Sound Right', Active Condition is Logic Switches->Sound Mixer, Source is Ch2 (Right), Function Type is Replace, Output is Ch3 (Sound)

How this works -> The Sound Left mix always sends Ch1's value to Ch3, but the logic switch goes active when Ch2's Absolute Value is higher than Ch1 (by testing against CH64, which is the Absolute value of Ch1), enabling the 'Sound Right' mixer, which replaces the output value sent to Ch3 with Ch2's value if Ch2's absolute value is higher than Ch1's absolute value.

**Comment by Bleroodes** [comment]
> Az RCGroups bejegyzésre hivatkozva itt a válasz a nulla alapú kiválasztásra.
> 
> Ez a logika úgy tűnik, hogy mindig a magasabb forráscsatorna abszolút értékkel rendelkező keverőt szeretné meghatározni a kimeneti csatorna értékének meghatározásához, nem pedig a kettőt összekeverni.
> 
> Ez eléggé kivitelezhető.
> 
> Ehhez 1 logikai kapcsolóra, 1 görbére és három ingyenes mixre van szüksége.
> 
> Tegyük fel, hogy Ch1 az első forrásérték (balra), a Ch2 pedig a második forrásérték (jobbra). A hangrendszer kimeneti csatornája Ch3 (ezt módosítani kell, hogy megfeleljen a modellnek)
> 
> A Modell->Görbe menüpontban adjon hozzá egy új görbét, írja be a custom, 3 pontot, a pontok 100, 0, 100. Nevezze el a görbét "Abszolút érték"
> 
> Adjunk hozzá egy Free Mixet, hívjuk baloldali ABS-nek, a forrás Ch1, a görbe szakaszban rendeljük hozzá az Abszolút érték görbét, állítsuk a kimenetet Ch64-re (így nem vesz fel RF csatornát). Ez átalakítja a Ch1 értékét az abszolút értékre, így össze tudjuk hasonlítani a magnitúdókat (mivel létezik |A| > X LS függvény, de |A| > |X| LS függvény nincs)
> 
> Ezután hozzunk létre egy logikai kapcsolót, nevezem Sound Mixernek
> 
> A funkció |A| > X Forrás (A) a Ch2 (jobb oldali) Az (X) értéket hosszan le kell nyomni, válassza ki a „Forrás használata”, majd válassza a Csatornák->Ch64 (bal oldali ABS) lehetőséget.
> 
> Ezt tesztelheti, aktív/zöld lesz, ha a Ch2 nagyobb, mint Ch1, és inaktív/piros, ha a Ch1 nagyobb, mint a Ch2
> 
> Most hozzon létre egy ingyenes mixet , amelynek neve 'Bal hang', forrás Ch1 (bal), kimenet Ch3 (hang)
> 
> Hozzon létre egy másik ingyenes keverési nevet: „Sound Right”, Aktív feltétel: Logikai kapcsolók-> Hangkeverő, Forrás Ch2 (jobb), Funkciótípus Csere, Kimenet: Ch3 (Hang)
> 
> Hogyan működik ez -> A Sound Left mix mindig elküldi a Ch1 értékét a Ch3-nak, de a logikai kapcsoló aktívvá válik, ha a Ch2 abszolút értéke magasabb, mint a Ch1 (a CH64-el szembeni teszteléssel, amely a Ch1 abszolút értéke), engedélyezve a 'Sound Right ' mixer, amely lecseréli a Ch3-nak küldött kimeneti értéket a Ch2 értékére, ha a Ch2 abszolút értéke nagyobb, mint a Ch1 abszolút értéke.

I'm about to try.  Thanks.
But as I wrote, 4 signals go to one output. 
Ch1 - positive/negative Ch2 - positive/negative.  Ch1 positive is sometimes mixed with Ch2 negative, in the same way Ch2 positive and Ch1 negative are also mixed if one stick is in the forward position and the other is in the backward position.

**Comment by Bleroodes** [comment]
> Referring to the RCGroups post, here is the answer for Zero-based selection.
> 
> That logic appears to be that you always want the mixer with the higher source channel absolute value determining the output channel value, rather than mixing the two together.
> 
> This is quite doable.
> 
> You need 1 Logic Switch, 1 Curve and three free mixes to do it.
> 
> Lets assume Ch1 is the first source value (Left) and Ch2 is the second source value (Right). The output channel to the sound system is Ch3 (you will change these to match your model)
> 
> From Model->Curve, add a new curve, type custom, 3 points, points are 100, 0, 100. Name the Curve 'Absolute Value'
> 
> Add a Free Mix, Call it Left ABS, Source is Ch1, assign the Absolute Value curve in the curve section, set the output to Ch64 (so it doesn't take up an RF channel). This converts Ch1's value to its absolute value, so we can compare magnitudes (since there is a |A| > X LS function, but not an |A| > |X| LS function)
> 
> Next lets create a Logic Switch, I'll call it Sound Mixer
> 
> Function is |A| > X Source (A) is Ch2 (Right) Value (X) has to be long-pressed, select 'Use a Source', then select Channels->Ch64 (Left ABS).
> 
> You can test this, it will go Active/Green when Ch2 is higher than Ch1, and inactive/Red when Ch1 is higher than Ch2
> 
> Now create a Free Mix Name is 'Sound Left', Source is Ch1 (Left), Output is Ch3 (Sound)
> 
> Create another Free Mix Name is 'Sound Right', Active Condition is Logic Switches->Sound Mixer, Source is Ch2 (Right), Function Type is Replace, Output is Ch3 (Sound)
> 
> How this works -> The Sound Left mix always sends Ch1's value to Ch3, but the logic switch goes active when Ch2's Absolute Value is higher than Ch1 (by testing against CH64, which is the Absolute value of Ch1), enabling the 'Sound Right' mixer, which replaces the output value sent to Ch3 with Ch2's value if Ch2's absolute value is higher than Ch1's absolute value.

Not really good.  Let's look at the left side forward 50% ok, meanwhile the right side is forward and when it is on the same level as the right side, then the 3Ch jumps up approx.  up to 100%.  Now we look at the right side forward to 50%, ch3 follows proportionally, now I move the left side up and ch3 also rises.  The right side is still at 50% though.  I continue to raise the left side approx.  to 25%, ch3 is already at 75%.  I continue to charge the left side to 50%, in which case ch3 is already up to 100%.  As soon as ch3 reaches 100%, it jumps back to 50%, exactly where the right and left channels are.  So forward direction is not good.  It behaves the same way in reverse.

**Comment by Bleroodes** [comment]
> Az RCGroups bejegyzésre hivatkozva itt a válasz a nulla alapú kiválasztásra.
> 
> Ez a logika úgy tűnik, hogy mindig a magasabb forráscsatorna abszolút értékkel rendelkező keverőt szeretné meghatározni a kimeneti csatorna értékének meghatározásához, nem pedig a kettőt összekeverni.
> 
> Ez eléggé kivitelezhető.
> 
> Ehhez 1 logikai kapcsolóra, 1 görbére és három ingyenes mixre van szüksége.
> 
> Tegyük fel, hogy Ch1 az első forrásérték (balra), a Ch2 pedig a második forrásérték (jobbra). A hangrendszer kimeneti csatornája Ch3 (ezt módosítani kell, hogy megfeleljen a modellnek)
> 
> A Modell->Görbe menüpontban adjon hozzá egy új görbét, írja be a custom, 3 pontot, a pontok 100, 0, 100. Nevezze el a görbét "Abszolút érték"
> 
> Adjunk hozzá egy Free Mixet, hívjuk baloldali ABS-nek, a forrás Ch1, a görbe szakaszban rendeljük hozzá az Abszolút érték görbét, állítsuk a kimenetet Ch64-re (így nem vesz fel RF csatornát). Ez átalakítja a Ch1 értékét az abszolút értékre, így össze tudjuk hasonlítani a magnitúdókat (mivel létezik |A| > X LS függvény, de |A| > |X| LS függvény nincs)
> 
> Ezután hozzunk létre egy logikai kapcsolót, nevezem Sound Mixernek
> 
> A funkció |A| > X Forrás (A) a Ch2 (jobb oldali) Az (X) értéket hosszan le kell nyomni, válassza ki a „Forrás használata”, majd válassza a Csatornák->Ch64 (bal oldali ABS) lehetőséget.
> 
> Ezt tesztelheti, aktív/zöld lesz, ha a Ch2 nagyobb, mint Ch1, és inaktív/piros, ha a Ch1 nagyobb, mint a Ch2
> 
> Most hozzon létre egy ingyenes mixet , amelynek neve 'Bal hang', forrás Ch1 (bal), kimenet Ch3 (hang)
> 
> Hozzon létre egy másik ingyenes keverési nevet: „Sound Right”, Aktív feltétel: Logikai kapcsolók-> Hangkeverő, Forrás Ch2 (jobb), Funkciótípus Csere, Kimenet: Ch3 (Hang)
> 
> Hogyan működik ez -> A Sound Left mix mindig elküldi a Ch1 értékét a Ch3-nak, de a logikai kapcsoló aktívvá válik, ha a Ch2 abszolút értéke magasabb, mint a Ch1 (a CH64-el szembeni teszteléssel, amely a Ch1 abszolút értéke), engedélyezve a 'Sound Right ' mixer, amely lecseréli a Ch3-nak küldött kimeneti értéket a Ch2 értékére, ha a Ch2 abszolút értéke nagyobb, mint a Ch1 abszolút értéke.

It seems to work.  I'll test it and report back.

**Comment by Bleroodes** [comment]
> Referring to the RCGroups post, here is the answer for Zero-based selection.
> 
> That logic appears to be that you always want the mixer with the higher source channel absolute value determining the output channel value, rather than mixing the two together.
> 
> This is quite doable.
> 
> You need 1 Logic Switch, 1 Curve and three free mixes to do it.
> 
> Lets assume Ch1 is the first source value (Left) and Ch2 is the second source value (Right). The output channel to the sound system is Ch3 (you will change these to match your model)
> 
> From Model->Curve, add a new curve, type custom, 3 points, points are 100, 0, 100. Name the Curve 'Absolute Value'
> 
> Add a Free Mix, Call it Left ABS, Source is Ch1, assign the Absolute Value curve in the curve section, set the output to Ch64 (so it doesn't take up an RF channel). This converts Ch1's value to its absolute value, so we can compare magnitudes (since there is a |A| > X LS function, but not an |A| > |X| LS function)
> 
> Next lets create a Logic Switch, I'll call it Sound Mixer
> 
> Function is |A| > X Source (A) is Ch2 (Right) Value (X) has to be long-pressed, select 'Use a Source', then select Channels->Ch64 (Left ABS).
> 
> You can test this, it will go Active/Green when Ch2 is higher than Ch1, and inactive/Red when Ch1 is higher than Ch2
> 
> Now create a Free Mix Name is 'Sound Left', Source is Ch1 (Left), Output is Ch3 (Sound)
> 
> Create another Free Mix Name is 'Sound Right', Active Condition is Logic Switches->Sound Mixer, Source is Ch2 (Right), Function Type is Replace, Output is Ch3 (Sound)
> 
> How this works -> The Sound Left mix always sends Ch1's value to Ch3, but the logic switch goes active when Ch2's Absolute Value is higher than Ch1 (by testing against CH64, which is the Absolute value of Ch1), enabling the 'Sound Right' mixer, which replaces the output value sent to Ch3 with Ch2's value if Ch2's absolute value is higher than Ch1's absolute value.

Working perfectly!  I don't know how to thank you.  I have been suffering from this problem for 3-4 days now.  I was close to the solution, I just left that curve out of the project and the 64 spoon.  Is it so important to be at the end of the channel list?  Please help me with something else.  I would also like to add hydraulics to the project.  The 3 channels with 6 signals.  2 channels on the sticks (right and left sticks) and 1 channel on the right slider.  Just tell me what to do and I'll do it.  The hydraulics will only handle 10-15% of the sound module, so this is secondary mixing.  The primary one (the signal level of which overrides the signal of the hydraulics) is the drive.  Can this be solved?  Unfortunately, I still can't see the situation, I've only had my X20 for 1 week.

**Comment by mawzthefinn** [comment]
Glad you got it sorted. 

The channel used for the extra mixer is not important, so long as it's 25 or higher so you don't waste RF channels (only channels 1-24 get sent to the receiver). I always start at 64 and count downwards, because it's easier to select on the screen (scroll 1 click up to get 64 instead of 1 click down to get to channel 1).

As to hydraulics mixing, I know it's been figured out how to emulate hydraulics, but I don't know the specifics. That's worth a question on the RCGroups X20 or XE threads with specifics as to what you are trying to achieve. There's a number of folks doing hydraulics emulation on X20's.

**Comment by Bleroodes** [comment]
Problem solved.  Thanks for the help.
