### ISSUE TITLE
1.5 model conversion: mixer curve is "lost" in case standard crv assignment was left empty

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3138]
I don't know how foolproof the 15 conversion is supposed to be:

If the first entry for the curve in a (at least free) mixer is not filled, the system does not check whether another entry exists.
As a result, the curve in the example is not assigned after the conversion

1.4
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/4e0b4859-9a5a-43ff-92de-c5051c04b8e3)

1.5
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/644d3d95-ffdd-4925-92ca-1c8e19f4417f)

Version 1.5 will definitely be a major upgrade, to which an extensive list of notes must be added
Imho a warning that empty entries are interpreted as "user errors" is sufficient and a check for corresponding situations before the conversion is mandatory.
at least it would put the responsibility on the users side

...or just take it into account in the converter

[model01.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13648750/model01.zip)

**Comment by bsongis-frsky** [comment]
It will be impossible to reproduce 100% the way 1.4.X works. For this use case a warning will be needed

**Comment by bsongis-frsky** [comment]
Well this exact scenario seems easy to fix though
