### ISSUE TITLE
Can't find ethos simulator

### ISSUE THREAD

**Issue by alessandroame** [FrSkyRC/ETHOS-Feedback-Community#3140]
I can't find ethos simulator (maybe because I'm a newbie):
from https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/Ethos-simulators I go to this page https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/simulators but here I found 2 archive that doesn't contain the sim.

**Comment by mawzthefinn** [comment]
Simulator installers can be found in the Releases section, 1.4.14 has all but the XE, there's only a couple updated ones in 1.4.15

**Comment by mawzthefinn** [comment]
Closing as answer provided
