### ISSUE TITLE
lcd.invalidate() coordinates not working

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3143]
The x y coordinates work. On simulator 14.8 Haven't tested on actual radio

But the w/h are always "everything".

So if you do: lcd.invalidate(0,0,10,10) it refreshes entire window.
It's the same as lcd.invalidate(0,0,100000,100000)

Also if you do lcd.invalidate(50,50,10,10) the 50,50 works, but the 10,10 acts like 10000000,100000000

**Comment by strgaltdel** [comment]
strange,
have widgets myself (>1.4.11) that are heavily based on lcd.invalidate frames.
did exactly what it was supposed to do,
unless the problem was between my ears

it might be helpful to post example code here

**Comment by bsongis-frsky** [comment]
Missing info here to reproduce the issue, a minimal script?

**Comment by noamkrief** [comment]
@bsongis-frsky 
Ok sorry.
lcd.invalidate(1,1,1,1) will refresh the entire widget window on the simulator.
It SHOULD only refresh 1 pixel at the top left.

**Comment by noamkrief** [comment]
@bsongis-frsky That's the only lcd.invalidate I have for testing.
On the actual radio it seems to work just fine.

**Comment by bsongis-frsky** [comment]
If it works fine on the radio I will try not to break it ;)
