### ISSUE TITLE
V1.50 Test Mixer and Flightphases

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3144]
the V1.5.0 free mixer has no flightphases
all other mixers has

**Comment by bsongis-frsky** [comment]
??

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/40e9bd7a-95a2-4453-aeb9-5f89ccc22091)

**Comment by hrenz** [comment]
ok and were is D

**Comment by bsongis-frsky** [comment]
is this question serious? 
it seems that this whole issue makes us loose our time
is it possible that you opened this issue after just looking at screenshots from a forum?
meanwhile we cannot work on other features, like #3105 or #2745
