### ISSUE TITLE
1.5 nightly: Reference to Var mix incorrectly migrated

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3148]
I have a sailplane template created in 1.3.3 with a number of Var mixes. These are used like this:

```
Var mix: CH37:Rate = 10%
Freemix: Source=aileron, Weight=CH37:Rate
```

After migrating to 1.5 (nightly), the Var mix is converted to a VAR variable, so the fragment should look like this:

```
VAR1:Rate = 10%
Freemix Source=aileron, Weight=VAR1:Rate
```

However, what actually occurs is:

```
VAR1:Rate = 10% [good]
Freemix Source=aileron, Weight=CH37:Rate  [bad]
```
Problem: the mixer definition refers to the inactive Var channel instead of the new VAR variable.

Version 1.5.0 nightly (Dec 15)

**Comment by Dsrenger** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3121

Works as it should...

**Comment by RC-SOAR** [comment]
Unless a solution can be found which minimises (if not eliminates) manual changes, I foresee that the only option for some users will be not to migrate to 1.5. The amount of manual work involved would be just too much. And starting afresh with a 1.5-compatible template would not be an option either, if it means losing all their model settings - it can take weeks to fully trim out an F3X sailplane.

Udo's (strgaltdel) suggestion 'b' [ in #3121 ](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3121#issue-2028095693) would have been a good solution, but I am guessing it's not possible since VAR mixes are no longer supported. 
As an alternative migration option, would this be possible?:
Convert:
```
Var mix:Rate Weight = wt%, Output=CH37
Freemix: Source=aileron, Weight=CH37
```
To
```
GVAR1:Rate Weight = wt%
FreeMix:RateAlias Source=GVAR1, Output=CH37
Freemix: Source=aileron, Weight=CH37:RateAlias
```
That way, it will not be necessary to alter any existing mixers. The only downside I can see is the extra 'Alias' mix which could cause the mixer limits to be exceeded.

**Comment by strgaltdel** [comment]
Hi Mike,
I also believe that the current procedure will cause some resentment among users,
and give the ethos critics a tailwind.

Ultimately, it's up to frsky to make a decision 
i would also be satisfied with a commitment if, for time reasons, there is no migration path in the first publication, but this would be submitted shortly afterwards...

in any case, an urgent note is obligatory

I can imagine that the conversion of mixers already represents a certain effort.
but there are also possibilities to use vars in curves etc... which multiplies the effort.
if such a conversion within an ethos transmitter would be too resource intensive, perhaps frsky could outsource the conversion of complex models into the suite ?

regards
udo

**Comment by RC-SOAR** [comment]
Hi Udo, just to put some figures on this: my F3F setup has 25 vars holding configuration variables. Most of these are referenced in mixers weights. I have maybe five setups like this. And other models which use Vars in a similar way.

Do I want to spend a couple of days updating all these references, just to end up where I started? 

And what about users who use a third party setup and don't have the confidence to make these changes? The only option for them will be to stick with 1.4, or start afresh with a 1.5 compliant setup which will mean trashing their settings.

Don't want to sound negative, but this will be a major headache. 

> your conversions calculated the right GVAR values ?

I'm also getting 1/10 of the correct value.

**Comment by Dsrenger** [comment]
Fully agree...

I fly GPS Triangle airplanes.

8 Servos only in the wing and in total 7 flight modes.

I will just stay an 1.4.xx

I was already upset when the butterfly mixer was changed several times, where I had to correct my models, but if this really comes reality...
It is just a NoGo

**Comment by strgaltdel** [comment]
.. Thank you very much for taking this into account !

**Comment by bsongis-frsky** [comment]
> Unless a solution can be found which minimises (if not eliminates) manual changes, I foresee that the only option for some users will be not to migrate to 1.5. The amount of manual work involved would be just too much. And starting afresh with a 1.5-compatible template would not be an option either, if it means losing all their model settings - it can take weeks to fully trim out an F3X sailplane.
> 
> Udo's (strgaltdel) suggestion 'b' [ in #3121 ](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3121#issue-2028095693) would have been a good solution, but I am guessing it's not possible since VAR mixes are no longer supported. As an alternative migration option, would this be possible?: Convert:
> 
> ```
> Var mix:Rate Weight = wt%, Output=CH37
> Freemix: Source=aileron, Weight=CH37
> ```
> 
> To
> 
> ```
> GVAR1:Rate Weight = wt%
> FreeMix:Rate Source=GVAR1, Output=CH37
> Freemix: Source=aileron, Weight=CH37:Rate
> ```
> 
> That way, it will not be necessary to alter any existing mixers. The only downside I can see is the extra mix in line 2, which could cause the mixer limits to be exceeded.

This is the solution which will be implemented. The simple solution doesn't 100% work.
