### ISSUE TITLE
No internal elrs for twin x lite s

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#3150]
With all the latest firmware from ethis and the internal rf module I dont see anything happening when I select internal elrs option. If this support is removed completely can you remove the elrs option to select from the internal module option? 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/5da11265-73d7-4586-864b-59d79b89f6d9)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/d62d8900-c871-4414-9099-712b70ddb703)

**Comment by mawzthefinn** [comment]
What are you missing? That's pretty much identical an RF display to my TWIN X-Lite S on 1.4.12 and TW-ISRM 1.0.2

The ELRS compatibility mode is VERY basic and not really configurable.

**Comment by kakashi2018** [comment]
It does not show the signal strength in the top tool bar. When i click access or any other protocol it does show up in 2.4 ghz icon
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/20e0123a-426a-4beb-a2dc-af5193fde747)

**Comment by mawzthefinn** [comment]
Yep, the built-in ELRS compatibility is pretty limited in functionality. It's most useful for old BF4.3 Whoops. If you need full-on ELRS you should look at a module.

**Comment by mawzthefinn** [comment]
As per #2660 there is no telemetry support in the ELRS compatibility mode.
