### ISSUE TITLE
Gas Channel (Simulator)

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#3151]
In simulator 
![Screenshot_2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/84090dc7-d64a-45a0-b23c-0d088cfdefe9)
1.5.0, throttle channel (CH3) when pulled to "-100" will move to "0"

**Comment by strgaltdel** [comment]
doublette from
#2811
#3147

**Comment by Wolepo** [comment]
But it's been done since yesterday. The simulators are running again and the sticks work as they did in 1.4. Only the trim button for the bottom right (Mode 1, QR) and the function keys cannot be operated yet.

**Comment by jurajjurej** [comment]
Fixed in the latest version.
