### ISSUE TITLE
Audio file sometimes fails to play (X20, 1.5 nightly Dec 19)

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3153]
I have a simple setup consisting of 

- three flight modes on 3-pos switch SA
- each flight mode has a special function to play a sound file.

_Expected behaviour:_ moving SA to a new position should play the sound file. 

_Actual behaviour:_ sometimes moving SA results in silence. The fm and special functions activate as expected, but the sound file doesn't play.  The problem is intermittent. Changing 'Switch middle delay detect' does not impact the problem.

Attached is the model setup and sound files. To reproduce the issue, go to the Special Functions menu, and move SA. It  may take several switch operations to reproduce the issue.

[SoundfileIssue.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13733588/SoundfileIssue.zip)

**X20, Ethos 1.5.0 Dec 19, 22:12:13**

**Comment by bsongis-frsky** [comment]
I cannot reproduce it with the current source code. Woud you please double check after next nightlies?

**Comment by RC-SOAR** [comment]
Yes I will check it out.

**Comment by RC-SOAR** [comment]
Works fine in 1.5 nightly (17 Jan)
