### ISSUE TITLE
Value of switches (Simulator)

### ISSUE THREAD

**Issue by jurajjurej** [FrSkyRC/ETHOS-Feedback-Community#3154]
The value 
![Screenshot_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/848ffff5-5513-463b-b6e3-2e8093a7cd21)
of the switches at the input is not "-100, 0, 100" But only "-10, 0, 10" %

**Comment by hpennw** [comment]
Same behaviour of switches not only in simulator but also on real transmitters like X20.
Switches used as input in the mixer types flaps, butterfly and camber have a value range limited to only +/-10%. Free mixer seems not to be affected, switch has full input range of +/- 100%.
