### ISSUE TITLE
#3136 doesn't fix problem as best I can see

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3155]
I see #3136 has been marked as closed. 
I checked for suite updates but it says I'm running the latest version. 

The i18n files still show as reading version.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/5089a6d3-3260-4af5-bfa6-9946a8878613)

Trying to update e.g. audio files still gives 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/fbf1fad7-0c4c-4db6-8e5c-611cfbdb83d7)

I can't tell if the final problem in #3136 has been addressed yet.

Either I'm doing something wrong or #3136 does nothing?

**Comment by mawzthefinn** [comment]
ETHOS Suite hasn't had an update released since you opened the previous ticket. The fix will be in the next version.

**Comment by Jedsters** [comment]
Does that apply to all of it including not being able to download corresponding components? Is it therefore the case that no-one can update ethos audio and bitmaps until the next version of suite is updated?
(I can undertand the suite update being required for the other bits.)
