### ISSUE TITLE
Can you please make this into a widget? RB35S

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3156]
The RB35S lua stab config has these lines:

  {"AIL Stab Gain", createNumberField, 0x44, 2, nil, 0, 200, "%"},
  {"ELE Stab Gain", createNumberField, 0x44, 3, nil, 0, 200, "%"},
  {"RUD Stab Gain", createNumberField, 0x45, 1, nil, 0, 200, "%"},

Can you convert it to a widget that runs in the background that we can adjust these gains via individual knobs on the radio?
Thanks

**Comment by FireFlite88** [comment]
I second this

**Comment by noamkrief** [comment]
I feel like i'm so close!
Seems like to make Aileron 0% gain is "widget.sensor:writeParameter(68, 12976383)"
But it's not working.
Here is my complete code:


-- Lua RSSI widget

local function create()
	-- return {value=nil}
	local sensor = sport.getSensor({appIdStart=0xF00, appIdEnd=0xF0F});
	return {sensor=sensor}
end


local myvar = 0;
local function paint(widget)

	lcd.drawText(5, 0, myvar)
	if myvar == 150 then
		if widget.sensor:writeParameter(68, 12976383) == true then
			lcd.drawText(20, 20, "success")
		else
			lcd.drawText(20, 20, "fail")
		end
	end	


end





local function wakeupnow(widget)
	
	myvar = myvar + 1
	lcd.invalidate()
			
	
	
end





local function init()
    system.registerWidget({key="Gyro", name="Gyro", create=create, paint=paint, wakeup=wakeupnow})
end

return {init=init}

**Comment by noamkrief** [comment]
@FireFlite88 I have some prototype widget working already :) if you want it, maybe you can try to find me on facebook?
So far I can control aileron gain with the left slider. It's working 100% perfect.
It will be easy to add functionality also for separate elevator and rudder gains on different knobs or slider.

**Comment by FireFlite88** [comment]
> @FireFlite88 I have some prototype widget working already :) if you want it, maybe you can try to find me on facebook? So far I can control aileron gain with the left slider. It's working 100% perfect. It will be easy to add functionality also for separate elevator and rudder gains on different knobs or slider.

This is Dan.
