### ISSUE TITLE
Ethos Suite 1.5.0 writes old bootloader with 1.5.0 Nightlies

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3157]
I downgraded my tx to Stable 1.4.15 and wrote all components.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/202f22b5-b9ff-4a09-85cb-106a1149b992)

Everything aside i18n 1.5.0 files appeared up to date. 

I then changed to Testing Version and did the same

It flashed the bootloader to an out of date version 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/4f60659d-bc8b-4088-90a0-d1ad69cc4abc)

and  was unable to find either audio or bitmap components.

Note this is using the latest Ethos Suite 1.5.0 updated 4 hours ago on 21st Dec.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/67a472f2-48c6-4aa0-b60b-6a4e08831b8c)

**Comment by bsongis-frsky** [comment]
1.5.0 is still not uploaded
the bootloader issue will be fixed in next nightlies
