### ISSUE TITLE
CORRECT BOOTLOADER FOR X18SE

### ISSUE THREAD

**Issue by Eduardoesteban1694** [FrSkyRC/ETHOS-Feedback-Community#3158]
Hi, what´s the correct bootloader and firmware for an Frsky Tandem X18SE, is the bootloader made for x18 or the x18s?

**Comment by mawzthefinn** [comment]
X18S bootloader. The SE is an S with a different screen and the two screen options are completely interchangeable.

**Comment by Eduardoesteban1694** [comment]
@mawzthefinn Thanks!
