### ISSUE TITLE
Timer with Logical SW and TH%

### ISSUE THREAD

**Issue by arnabraha** [FrSkyRC/ETHOS-Feedback-Community#3159]
Running Ethos Ver 1.4.15
X20S

I have a logical switch (LSW1) for RPM > 1000 for a gas plane (Engine running indication).  I want Timer 1 to run when LSW1 is true AND run at Throttle %.  This will allow for better fuel left estimation.

As of now, it either runs when LSW1 is true or it can run at TH%. 

I run edgeTX on my old X9D+ and this is possible and the feature works great.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/047b01ea-b1f1-44d2-8fbf-969c66bb73a2)
