### ISSUE TITLE
Improvement of the X20 functions

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#316]
Improvement of the X20 functions
the X20 has a serious flaw
it does not have 2 free trimmers like the X10, X12
But this can be reproduced with an autorepeat function like the trimmers has
for selection at the switchsetting at hardware

and with the special functions counter
with inc, dec, Steps, Range

**Comment by loetefix** [comment]
with the mixer trim you can add so many trims you want.

**Comment by hrenz** [comment]
when I have free switches with middle off

**Comment by loetefix** [comment]
Or you use one 3POS switch with logical AND combination to the 6 buttons. so you can set 6 trims with one switch.

**Comment by hrenz** [comment]
you can do all this 
it just a crutch because 2-3 basic things are missing at X20

**Comment by hrenz** [comment]
Or the same dynamik timing  the real trim switches has

**Comment by mawzthefinn** [comment]
I believe #577 covers the first request better and either of #779 or #1602 the increment/decrement special functions (for either a GVAR implementation or extending the VAR mixer for full GVAR equivalency)

I am labelling this particular issue as a Duplicate, please continue discussions under the linked issues. These do need to get addressed and not forgotten.
