### ISSUE TITLE
V1.5.0 Vars testing  with simulator

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3161]
I use an Analog Input  (form -100% to +100% )  an a recalculated Range from -25% to+50%
its normal a setting of weight 37,5% , offset 12,5%  or with a extra curve

-----------------------
At Vars I use Range  from -25% to +50% and throttlestick as Analog source
I use this Vars als Sourve at a mixer

--------------------------------
At mixer-curves I see a hard limit at -25% and +50%
At mixer and kanal output I see  Output from  +125% to -100% and a Jump to 0%

![2023-12-22_113205 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/2325e1b8-15f1-4e25-8391-eecde5124e02)

**Comment by bsongis-frsky** [comment]
I think you misuse the Var function, but anyhow here is a possibility that you can use in next nightlies

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4da29c01-f0bb-4a7a-8245-318d1381fbe7)

**Comment by hrenz** [comment]
thanks, 
will try it next nightly
