### ISSUE TITLE
Suite 1.5 Model backup 

### ISSUE THREAD

**Issue by jimmy6616** [FrSkyRC/ETHOS-Feedback-Community#3162]
When I try Model backup with 1.5 I get the attached. Win11, S20S
![IMG_0438](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58522146/37b3d7b5-1186-4315-b054-ff3f0c78019f)

**Comment by mszulen** [comment]
Same here.

**Comment by jimmy6616** [comment]
Nicholas what does completed mean ? No feedback ?

**Comment by mgsanna** [comment]
> Nicholas what does completed mean ? No feedback ?

It mean that the issue is solved…. Next update will be good
