### ISSUE TITLE
Testing trims and flight phases in V1.5.0

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3163]
Testing trims and flight phases in V1.5.0
Although universal, it is too complicated for the normal user

in V1.5.0 the default should be like V1.4.15
First of all, each flight phase with its own trim should be standard,
and thus already pre-assigned.

You can only expand it if you want something different

90% of users are “normal users” and not professionals

**Comment by bsongis-frsky** [comment]
And?

**Comment by bsongis-frsky** [comment]
Given the previous issue you have opened, you try to use a Var when it is not needed.
90% users won't need the Vars, 90% users won't need the Flight Modes, 90% users won't need the Curves.
Should we remove all those features, just because some people don't understand how to use them properly?

**Comment by hrenz** [comment]
Don't misunderstand Bertrand
It's about simple setting and selection

V1.5.0 Simulator

During the automatic changeover
from V1.4.1.5 to V1.5.0 should be in the trims
The behavior is the same as in V1.4.15
"All flight phases have their own trims"
Then you don't have to do anything extra in the first step.

With e.g.
Otherwise I would have to insert 32 lines
on an RC glider with 8FP and 4 trims

Or is this already stored as standard but not visible anymore

**Comment by bsongis-frsky** [comment]
Add a configuration mode for Trims:
1) Simple - one value for the whole model
2) One value per flight mode
3) Custom - as many values as needed and enhanced actions

**Comment by hrenz** [comment]
Yes good idea
 so each can use what he need, simple, or normal or extended
for normal user and expert user
Better as all others RC systems
