### ISSUE TITLE
LBT - R9MX - FCC (868MHz)

### ISSUE THREAD

**Issue by frobert0** [FrSkyRC/ETHOS-Feedback-Community#3164]
Good day
I had the following question: Why is telemetry disabled in LBT mode (868MHz - R9 Mx) from 100mW upwards and works in FCC mode?
1. Technically not possible: please define
2. Legislation: ...
3. Other reason: please define

**Comment by mgsanna** [comment]
EU-LBT firmware are European law compliant, since that telemetry cannot be more than 25mW so if you try to force them telemetry will be disabled, this not an issue and this a well documented subject… nothing to share with ethos, nor hardware, nor GitHub

**Comment by bsongis-frsky** [comment]
Just because of the law...
