### ISSUE TITLE
Error in special functions Announce values

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3165]
Error in special functions Announce values 1.5.0

1. the option to announce values is missing.
2. when converting from 1.4.15, the functions Announce values are converted to play audio sequence!

![aktion](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/827c5ed0-63d9-4d9e-aa63-97b673830dec)

Gruß Eugen

**Comment by mawzthefinn** [comment]
This is not an error, value is a category of play audio sequence in 1.5

The Play Audio SF replays  both Play Track and Play Value.

**Comment by yak55** [comment]
Hello, yes, I am aware of that.

But nevertheless it is:

1. illogical and cumbersome

2. incorrect when converting from 1.4.15 to 1.5.0

It must not be the case that the announcement of a value is converted as the playback of an audio sequence after the update.

The former value is no longer announced.

Please check the incorrect conversion!

Greetings Eugen

**Comment by yak55** [comment]
Hello, yes, I am aware of that.

But nevertheless it is:

1. illogical and cumbersome

2. incorrect when converting from 1.4.15 to 1.5.0

It must not be the case that the announcement of a value is converted as the playback of an audio sequence after the update.

The former value is no longer announced.

Please check the incorrect conversion!

Greetings EugenAm 24.12.2023 um 00:36 schrieb mawzthefinn ***@***.***>:﻿
This is not an error, value is a category of play audio sequence in 1.5
The Play Audio SF replays  both Play Track and Play Value.

**Comment by mawzthefinn** [comment]
1. It's the correct conversion, Play Audio unifies all SF's that Play Audio. There is no Play Value SF in 1.5, nor is there a Play Track SF or the Play Text SF (for X20 Pro), only Play audio. 

2. If the actual bug is that the Play Value line is not added to the Play Audi SF during conversion, that is a different issue than what you reported above.

**Comment by mawzthefinn** [comment]
Note I just tested conversion on one of my old model files and it correctly converted Play value to a Play Value line in the Play Audio SF.
