### ISSUE TITLE
Error in logical switches with inactive status --- 1.5.0

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3166]
Error in logical switches with inactive status ---

An inactive logical switch is still evaluated and set to yes, for example.

![log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/af8a736e-edb7-4932-ac3f-e1b8b450a920)

![Log 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/fcfa22c8-6fc5-40a7-ba8e-37e7ec739c51)

Gruß Eugen

**Comment by Nicholas-Luoyi** [comment]
What is the value of SR now?

**Comment by yak55** [comment]
The value of the rudder is correct.
The logic switch itself works correctly.
The value was 0.

But if there is a NO in the activated line, it should not become high!

Example: I use the logic switch to monitor the receiver voltage.

If I now have a receiver without this sensor, I only want to deactivate the logic switch so that no alarms are triggered.

What other purpose would the - - - - have?

**Comment by Nicholas-Luoyi** [comment]
Understood.
