### ISSUE TITLE
Possible RF Module update problem

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3167]
I tried to use the new RF Module update in the Suite to update from 2.2.0 to 2.2.6. The suite reported success however the version still showed as 2.2.0 in the RF module manager. 
I'm not sure if it is relevant that RF was turned off for the model which had been selected prior to connecting the tx to the PC.
Thanks

**Comment by jimmy6616** [comment]
I had the same issue but when I repeated the upgrade a second time it appeared to work
