### ISSUE TITLE
[Question] Ethos 1.5.0 RC "Edit model -> Receiver selector"

### ISSUE THREAD

**Issue by mszulen** [FrSkyRC/ETHOS-Feedback-Community#3169]
This is not mentioned in the draft1 version of the manual.
On the Edit model page, there's a Receiver selector.
What's the function of it? Is it connected with the receivers from RF system page?
![receiver](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6932464/0146aae8-90be-40c7-9302-cf69ffb96d0e)

**Comment by mawzthefinn** [comment]
It’s connected to the wizard, which now will create mixes for the FrSky stabilizers

**Comment by mszulen** [comment]
All clear! Thanks!
