### ISSUE TITLE
BatLow Lsw  Total cell  not possible to set.

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#317]
hello,
I try to set the voltage for a pack of 6S lipo , for an LSW , but the total voltage does not exceed 4,20 volts .
![20210523_140105](https://user-images.githubusercontent.com/84312994/119260126-b12ce300-bbd1-11eb-8eb3-f5ad67c141c2.jpg)

**Comment by MIKE-DAILEY** [comment]
Go to the Telemetry sensor screen and on the sensor for that voltage check its range setting.
