### ISSUE TITLE
[documentation] Mixers overview in 1.5.0 draft1 manual describes VAR & TRIM mixes

### ISSUE THREAD

**Issue by mszulen** [FrSkyRC/ETHOS-Feedback-Community#3170]
Those mixes are not available in the (airplane) Mixes library screen of 1.5.0 RC

**Comment by mawzthefinn** [comment]
This is a leftover from older builds, it will be addressed

**Comment by mszulen** [comment]
That's what I thought. Thanks for confirmation!
