### ISSUE TITLE
1.5 RC0 Range values are allowed to be reversed but don't work

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3174]
Range values are allowed to be 'reversed' but when they are they don't work.

Create a LSW with a Range using the Source Main Voltage and a range of 5V - 10V. This is as expected 'True' 
Now reverse the Range so it is 10V - 5V. The LSW no longer indicates this is True. 

Ethos either needs to accept an increasing or decreasing range or not allow the range to be decreasing. If this was setup for Rx voltage and a decreasing range was used it could result in the loss of a model.  

Thanks

**Comment by Nicholas-Luoyi** [comment]
The reverse of the range
```
5V - 10V
```
is
```
value < 5V or value > 10V
```

**Comment by Jedsters** [comment]
Forgive my poor semantics. I'll close this and open another issue with improved semantics.
