### ISSUE TITLE
Ethos Suite 1.5.0 RC0  Model management freezes

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#3175]
Attempt to backup models with X18SE - Ethos Suite freezes.
Only option is to kill app.

**Comment by Nicholas-Luoyi** [comment]
What's the version of the ETHOS firmware on radio?

**Comment by fhpage** [comment]
firmware on radio is 1.5.0 RC0
Where do I find the crash log??

**Comment by Nicholas-Luoyi** [comment]
In Suite settings tab. You can find open logs directory button

**Comment by fhpage** [comment]
[crash-20231227.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13782016/crash-20231227.txt)
![Ethos Suite 1 5](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/22982973/1809118b-c037-4b5a-9404-bbc6c1dd8af2)

**Comment by Nicholas-Luoyi** [comment]
Replicate with #3162 and fixed
