### ISSUE TITLE
Hitec telemetry for Multiprotocol module

### ISSUE THREAD

**Issue by mortehoe** [FrSkyRC/ETHOS-Feedback-Community#3176]
Please can you add the above hitec telemetry for Horus, if possible, as I understand (although not officially from Frsky) that firmware version 1.5.x will not be available for Horus.

**Comment by RealTadango** [comment]
Would be nice to have the latest version for the original X12S ect...

**Comment by bsongis-frsky** [comment]
Many duplicates for this issue. Hitec Telemetry is on the way

**Comment by mortehoe** [comment]
I have tried contacting Frsky with no response.The duplicate is for 1.4.x specifically.
Please can you answer if Hitec Telemetry will be available for Horus in 1.5.x or will there be a version for 1.4.x ?
