### ISSUE TITLE
1.5.0 RC0 When LSW Range values are in descending order, they will never be true

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3177]
LSW Range values can be specified in either ascending or descending order. However when they are specified in descending order they will never be true.

e.g. Create a LSW with a Range using the Source Main Voltage and a range of 5V to 10V. This is as expected 'True' as the Tx voltage is between 5V and 10V.
Now swap the range values around so the range shows as 10V to 5V. The LSW no longer indicates this is True even though the Tx voltage is still between 10V and 5V. No matter what values you specify, if the first range value is higher than the second range value the LSW will not be true.

Ethos either needs to accept range values in ascending or descending orders or not allow the second range value to be less than the first. If this was setup for Rx voltage etc. and the second range value was less than the first it could result in the loss of a model as the LSW would never be true and a user wouldn't even realise that they had specified something which could never be true.

Thanks

**Comment by Nicholas-Luoyi** [comment]
This does make sense. You are right

**Comment by Jedsters** [comment]
Now works either way around - should keep everyone happy. Perfect.
Thanks
