### ISSUE TITLE
1.5 RC0 Cloning a Free Mix doesn't clone the FM correctly

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3178]
To recreate: create a Free Mix, deselect some of the default flight mode assignments and save. 
Now clone the above Mix and it can be seen that all flight modes are assigned to it. 
I've tested cloning a few (but not all) other mixes and they appear to clone the FM assignments so there is something odd and inconsistent about cloning free mixes.

**Comment by bsongis-frsky** [comment]
Fixed for RC1
