### ISSUE TITLE
1.5 RC0 Haptic doesn't play with Play Audio Sequence

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3179]
To recreate:
Create a SF
Action: Play Audio
State: Enable
Active condition: SI down
Voice: of your choice

Add a new line in Sequence
Play File
File: of your choice
Haptic: On

Save

If you depress SI the audio file is played however the haptic is not played. 

Additionally, there is no option to select what haptic sequence should be played or with what strength, I'm not sure if this could be part of the problem?

**Comment by Nicholas-Luoyi** [comment]
I tried as well. I get the haptic played. But it's very weak at the very begining of the SF.

**Comment by Jedsters** [comment]
Interesting, I have added another OR condition e.g. SA Up to my LS and even when I put SA up I can see the SF go and stay green, but there is no haptic. The haptic certainly works on my tx at other times.

**Comment by Jedsters** [comment]
I have uploaded a file to dropbox demonstrate which hopefully you can access. 
At the start you can see SF1 is off. You can also see that SF1 has a play sequence which includes haptic (I've just realised I had the volume is down so you can't hear the file play). You can hear me flick a switch and see that SF1 changes colour (just about see it, sorry, not the best video) but you can hear no haptic. 
I then turn the switch off and SF1 changes colour back to off.
I then flick a switch to make SF2 active which has a haptic action and this time you can hear the haptic.
[https://www.dropbox.com/s/igaxevnl96l72vs/VID_20231228_100641.mp4?dl=0](url)

Hope that helps.
Thanks

**Comment by bsongis-frsky** [comment]
Play Audio Sequence uses the default Haptic settings from your Radio settings

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/cad424ba-452e-4811-ad58-bdd4b96d8368)

**Comment by bsongis-frsky** [comment]
I reproduce it here. Searching ...

**Comment by Jedsters** [comment]
I'm not sure if this may be related to #2852 
Is the audio paying before the haptic so if the trigger is very short then the haptic doesn't play?
I believe that once a trigger has triggered, then everything in a play sequence should play, not just those bits in the sequence while the trigger is active.

**Comment by bsongis-frsky** [comment]
Fix ready for RC1
