### ISSUE TITLE
Error: create/copy new model fails

### ISSUE THREAD

**Issue by mherke** [FrSkyRC/ETHOS-Feedback-Community#318]
Hello all,

- Tandem X20S
- Ethos 1.07 EU

when trying to create a new model or copy the only existing one (model0z.bin), I get the message "Model copy failed" or "Model creation failed" when saving. I created and set up a model this morning. After switching on the transmitter again, an error message greeted me "Error opening file Starting model wizard...". The whole thing is quite irritating to me now.

Question:

- how can the error be fixed?
- how can i do a complete reset to factory settings?

many greetings and many thanks

with kind regards

Michael

**Comment by MIKE-DAILEY** [comment]
You have a "z" in the model name? 

You can reset all the system settings and models by deleting the "radio" file on the root of the SD card and all the "model" files in the SD model folder.  After deleting and then starting the system it will take you though system calibration and a new model creation.

**Comment by hrenz** [comment]
yes genertes "0z" and not "01"
