### ISSUE TITLE
1.5 RC0 SF Skip on startup is not always honoured

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3180]
To recreate...

Create a LS with a name
Function OR
Value1 <Edge><Not>SI
Value2 <Edge><Not>SJ
Min duration 0.1s (just so you can see when it is activated)

Create a SF
Action Play Audio
State Enable
Active condition - the name used for the above LS
Voice as desired
Skip on startup On 
Sequence
Play file
File of your choice

If you press SI, SJ the file will be played as expected.

However, now switch to a different model and then switch back to this one. After any switch warnings etc. if plays the SF audio file even though Skip on startup is On and SI, SJ have not been pressed.

For info, I am using SI, SJ in combination with other LSW to increment / decrement VAR values and want the final value played when I release SI, SJ hence the <Edge><Not> SI/SJ.  To have a sequence of VAR values played at startup is very annoying when I have asked for them to be skipped on startup.

Thanks

**Comment by mawzthefinn** [comment]
That's because the LS goes true on startup (when the switch states are momentarily high on initialization), but stays true past startup due to the min duration setting.

The SF fires after startup, because the LS is still true for 0.1s

**Comment by Jedsters** [comment]
Thanks Mawz, that makes sense. 
I think I've managed to work around the problem.
