### ISSUE TITLE
Missing Icons and audio on twin x lite s with 1.5.0 rc0

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#3181]
With the new 1.5.0 firmware update, I see that few of the icons are missing from Model menu like the mixes, vars and lua. Also I have custom startup and switch off audio that was working after the upgrade but after changing language-> voice 1 to system and reverting back made all my system audio to not work.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/2e292e04-0752-4c34-84d7-b902c49912af)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/b01e8e0d-a502-466d-af78-744d1addd67d)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/22673b2c-b6d7-4f98-816a-18d93e5a4d36)

**Comment by mawzthefinn** [comment]
1. Make sure you have updated your System Bitmaps, you are missing icons because you have an old version

2. You need to use the new Audio folder structure, it's changed from 1.4 and your issues are because you still have the v1.4 layout. Make a folder called en in /audio, move all your current audio files into that folder (including any folders like system), then select 'en' as your voice 1 in system->General

**Comment by kakashi2018** [comment]
@mawzthefinn  audio is already in correct directory. It was working even after updating to 1.5 but after toggling voice 1, it stopped working all together.

which flash shall I pick for bitmaps. I don’t see flash package for twin lite s. Ethos suite shows it is latest that I have.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/283d1ffb-efc0-4783-8edc-59eb2940008f)

**Comment by mawzthefinn** [comment]
1. User the X18-flash.zip package, X18 and TWIN X-Lite flash is identical.

2. Sorry, I made a mistake in my instructions, the base folder path you need to use is in /audio/en, not /audio/

So system should be in /audio/en/en/system or /audio/en/us/system 9f you wnat voice 1 named US

The voices are in the folders in /audio/en

**Comment by kakashi2018** [comment]
@mawzthefinn  audio is working now after moving to suggested directory. Still no luck with bitmaps even after copying x18 flash from 1.5.0 rc0

**Comment by mawzthefinn** [comment]
Did you put the X18 flash on your flash drive? It goes there, not on NAND with your audio.

**Comment by kakashi2018** [comment]
Yes, I have copied it to flash drive only. Replaced with old ones.

**Comment by mawzthefinn** [comment]
Did you reboot after? These are loaded on boot.

**Comment by kakashi2018** [comment]
Yes, I did.

**Comment by mawzthefinn** [comment]
Try updating with ETHOS Suite, I just tested with my TWIN X-Lite and it installed the correct icons.

**Comment by kakashi2018** [comment]
I have tried with ethos suite, restarted, tried deleting flash bitmaps and
fonts copied fresh folders again from x18 flash still those icons are
missing. Anything have to do with twin xlite s model? I see there are
different lcd for normal and s models.

**Comment by mawzthefinn** [comment]
I tested on an S model actually. The only difference is the screen finish and brightness, it's the same resolution and layout, and the two screens are completely interchangeable (I've done the swap on my X18)

**Comment by kakashi2018** [comment]
any chance you can share me flash folder to my email?

**Comment by Nicholas-Luoyi** [comment]
You mean you only miss the icon for Mixer?

**Comment by kakashi2018** [comment]
Mixes, lua and var

**Comment by Nicholas-Luoyi** [comment]
I cleared my flash and NAND then reinstalled all the components. It works fine. BTW here is the bitmaps package I use.
[bitmaps.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13782848/bitmaps.zip)

**Comment by kakashi2018** [comment]
Copying in ethos suite mode and restarting didn’t fix the issue but Copying bitmaps while in bootloader mode solved the issue. Same I have identified on x20radio. This issue can be marked resolved as I got it working now.
