### ISSUE TITLE
1.5 RC0 problem with Trims, Behaviour, Mode name assignments

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3185]
When Trim Behaviour Active conditions are changed, the Equal and Offset names are not always updated correctly.

To recreate:

Add an extra trim
Add a new behaviour with Active Condition FM0 ('Normal' in my case) and mode Default which displays as 'Normal'
Add another new behaviour with Active Condition FM3 ('Thermal' in my case) and mode Offset + FM0 ('Normal') which displays as Offset

Now swap the Active conditions around so the first one is FM3 ('Thermal') and the second one is FM0 ('Normal').
Now select Offset against the second active condition FM0 ('Normal') and you will see it has a mode displayed of Offset + FM0 (Normal) when it surely should now be Offset + FM3 (Thermal). It will be noted that the line above is also incorrect in that it says Equal FM0 (Normal) instead of Equal FM3 (Thermal)

**Comment by bsongis-frsky** [comment]
Fix ready for RC1
