### ISSUE TITLE
Twin lite s program buttons lit up during startup

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#3187]
Hi,

I’m not sure if this can be done via firmware or bootloader. The thing is I see that out of 4 programmable buttons on the twin lite s radio 3 of them lit up along with power button light when starting up the radio, is there a way to prevent that happening. I know it is just for couple of seconds but it is a little irritating for me to watch them lit up during startup

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/34996ba2-8ac9-4e3c-95e0-377cd08c187d

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/829059c4-95ff-4215-8713-ba3078abbf38)

**Comment by bsongis-frsky** [comment]
Which is the version of your bootloader?

**Comment by kakashi2018** [comment]
@bsongis-frsky  using 1.4.15. Again this is not a serious issue. It’s just that when ever we click the power button for starting the radio, the three buttons out of 4 programmable buttons lit up for a second. Is there a way to prevent that behavior?

**Comment by Karaya1978** [comment]
It´s much better, but the second button counting from the left side, still lights up.

**Comment by kakashi2018** [comment]
Yup, it still lits up for a sec and they tell that is is some hardware
related issue. The second button led is some home tied up with the power
button. Instead of this irregular thing, I think it will be good if we have
all the four led lit up at same time. What do you say?
