### ISSUE TITLE
Elrs configuration- seeing only few settings in 1.5.0 RC0

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#3189]
After 1.5.0 rco update, I’m only seeing few things in elrs configuration. Please see the image attachment. This I observed in x20hd radio and using radiomaster ranger module. It was showing all configuration settings before update.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/610b78b7-2c4f-4f87-9786-bfb35854e062)

**Comment by bsongis-frsky** [comment]
Have you copied the Lua scripts from the branch '1.5'? Because there are a few differences with the branch 'main'.
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5

**Comment by kakashi2018** [comment]
> Have you copied the Lua scripts from the branch '1.5'? Because there are a few differences with the branch 'main'. https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5

Will try the new lua thank you

**Comment by kakashi2018** [comment]
with new lua everything is working as expected, Thank you
