### ISSUE TITLE
lcd.invalidate while swiping

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3190]
My lcd.invalidate is very well respected and taken seriously.
I only do every 0.1 per second for fast frefresh items (RPM etc)
And only 1/second for slow items (battery % etc)

Also for the "fast items" I detect changes in values before I call lcd.invalidate and I also use parameters to refresh ONLY the area needed.

But when I swipe to screen #2, everything seems to be ignored. The refresh rate goes as fast as possible.

Here is a simple widget to demonstrate. It ticks every 1 second. lcd.invalidate() is called only 1/sec.

But as you scroll to Screen 2, very slowly, you can see the os.clock running at maximum refresh rate ignoring the 1/sec rule of the widget.

So basically, every well written widgets can get VERY slow during a screen switch :(

------------------------------------------------------------------------------

local function create()
    return {value=nil}
end

local myclock = 0
local tempclock = 0

local function paint(widget)
	
	lcd.drawText(5, 10, "clock: ".. myclock)
	
	
	lcd.drawText(5, 40, "Some stuff here")

end

local function wakeupnow()
	
	myclock = os.clock()
	
	if myclock > tempclock + 1 then
		--print(myclock..":"..tempclock)
		lcd.invalidate(8,8,200,45)
		tempclock = myclock
	end
	
	
end

local function init()
    system.registerWidget({key="test1", name="test1", create=create, paint=paint, wakeup=wakeupnow})
end

return {init=init}

------------------------------------------------------------------------------

**Comment by i3dm** [comment]
Video demo of the above
https://youtu.be/RNeWganLkRQ?si=xNzKRMEz7aTpiC7i

This explains the swiping slowness I encountered with my widget's.

**Comment by bsongis-frsky** [comment]
No choice, when you swipe between 2 screens, the whole LCD needs to be drawn many times. If you want to improve this speed, you need to write on a temporary virtual bitmap, and only the copy of this bitmap will be done on paint instead of your complex paint function.

**Comment by i3dm** [comment]
@bsongis-frsky can you lower the refresh rate while swiping? It's really not important to refresh so fast while swiping.

**Comment by noamkrief** [comment]
@bsongis-frsky is there an easy way to know when a swipe is happening, so I can draw that temporary screen?
Thanks :)
