### ISSUE TITLE
1.5 RC0 Test Mix disables output channels even when not active, but its FM is active

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3193]
It appear that Test Mix disables output channels whenever its FM is active regardless of whether the Test Mix Active Condition is true.

To recreate:

Create a basic 4 channel model.
Give it two flight modes, e.g Default and FM2 active when SA down
Add a new Test Mix, Active Condition SB Up and active only in Default FM and Range of -100% to 100% - accepting all other default values.

Put switch SA down to go into FM2. Look at the channel outputs.
Operate the ailerons and elevator and you will see the 3 channels operate normally.
Now move SA up to go into Default flight mode, ensure SB is NOT Up so that the Test Mix is not active.
Again move the Ailerons/Ele and you will see that channels 1/2 do not move!

Go to Mixes and you will see that Test Mix is not bold so is not active. Now View per channel and again operate Ail. Now you will see that where it says Ch1 RAlieron the bar does not move, however if you expand the twistie to view the mixers which make up  Ch1 it shows Ailerons and Test Mix. Again operate the ailerons and you will see the Ailerons line moves but again the Ch1 RAileron line  does not move - this is no doubt because it is being over-riden by the Test Mix line even though it is inactive and greyed out. 

Move SB up while in Default FM and you will see the ailerons etc. do their sweep.

So long as there is a test mix people may use some contrived combination of switches etc. to ensure it can not be accidentally used while a model is in use, I do not believe it is appropriate that just activating its flight mode(s) should disable the outputs.

Thanks

**Comment by yak55** [comment]
An inactive test mixer already blocks the servo outputs in 1.4.15.
I have therefore always deleted it immediately after use.

Greetings Eugen

**Comment by Jedsters** [comment]
That's a good idea, although given that Free Mix operates as expected with Replace I'd expect Test Mix to as well.
In my case I actually use Free Mix to calibrate a gyro servo since that does a nice job of sweeping the relevant control surfaces and although it's control by a contorted mix of switches I'd rather not risk it ever disabling control surfaces should I forget to delete it / remove all FM from it.
