### ISSUE TITLE
1.5.0 RC0 bricked my X18S

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#3194]
X18S on 1.4.14
downloaded X18S_FCC 1.5.0 RC0, flashed it, radio wont turn on at all, only in boot loader mode. and gets stuck when connecting to USB sometimes.

did i miss a step anywhere? does 1.5.0 require a special bootloader? i didnt see any indication to that.

unbricked the Tx by manually flashing to 1.4.15.

**Comment by Dsrenger** [comment]
Read the Patchnotes for 1.4.15

X18/S]
The bootloader was not able to start the latest 1.5.0 nightlies

**Comment by i3dm** [comment]
so bootloader has to be 1.4.15? ok thanks

**Comment by mawzthefinn** [comment]
Yes, bootloader must be 1.4.15 for the x18 series to run 1.5.0 Nightlies or rc0
