### ISSUE TITLE
Ethos Suite

### ISSUE THREAD

**Issue by spvwrx** [FrSkyRC/ETHOS-Feedback-Community#3196]
Ethos suite will not open after install on macOS Big Sur Ver.11.6.8 after suite version 1.4.11..

**Comment by kramgrand** [comment]
Hello, I run a Mac and have had no problems. Have you tried doing a fresh install of the Ethos Suite for the version of Ethos you are using?    Also you say you have installed Big Sur, that came out in November 2020. Sonoma is the latest OSX version Sept 2023.   I think the only issue I have run into was being unable to do an UPDATE of Ethos Suite a short while ago. Again I got round that by running a fresh install for the version of Ethos being used.    Regards. Mark

**Comment by spvwrx** [comment]
Thanks for the reply, I will try your suggestion.Best regards,Simon VentevogelOn 31 Dec 2023, at 8:44 pm, kramgrand ***@***.***> wrote:﻿
Hello, I run a Mac and have had no problems. Have you tried doing a fresh install of the Ethos Suite for the version of Ethos you are using?    Also you say you have installed Big Sur, that came out in November 2020. Sonoma is the latest OSX version Sept 2023.   I think the only issue I have run into was being unable to do an UPDATE of Ethos Suite a short while ago. Again I got round that by running a fresh install for the version of Ethos being used.    Regards. Mark

**Comment by mawzthefinn** [comment]
Yes, the USB system was re-written in 1.4.12 to work better on current versions of Mac OS and no longer works with legacy versions. 

Big Sur is no longer supported by Apple (having exited support in September 2023, around the same time Suite 1.4.12 was released), you should update to an OS which still receives patches from the manufacturer. You will find a lot of other new software likewise no longer works (including any MS Office updates after Oct 1, 2023 for example)

**Comment by spvwrx** [comment]
Thank you for your response. Will try upgrading OS..Best regards,Simon VentevogelOn 1 Jan 2024, at 11:39 am, mawzthefinn ***@***.***> wrote:﻿
Yes, the USB system was re-written in 1.4.12 to work better on current versions of Mac OS and no longer works with legacy versions.
Big Sur is no longer supported by Apple (having exited support in September 2023, around the same time Suite 1.4.12 was released), you should update to an OS which still receives patches from the manufacturer. You will find a lot of other new software likewise no longer works (including any MS Office updates after Oct 1, 2023 for example)

**Comment by spvwrx** [comment]
Thanks, problem solved, i updated the OS as suggested and all is good. thank you..
