### ISSUE TITLE
X12s

### ISSUE THREAD

**Issue by spvwrx** [FrSkyRC/ETHOS-Feedback-Community#3197]
Will there be a test version of Ethos 1.5 for Horus X12S.? Thanks.

**Comment by RealTadango** [comment]
Would be great to have a recent Ethos for my X12S :)

**Comment by KevinFairgrieve** [comment]
> Would be great to have a recent Ethos for my X12S :)

1.4.15 is the most recent for the X12S. I have it running on one of mine.

I too hope that 1.5 can be made to work on X12S.

I suspect due to hardware limitations that this is the end of the line for ETHOS on the X12S and X10.

**Comment by RealTadango** [comment]
Yes, i forgot they did not support the original RF module, only the upgrade... So i keep it on OpenTX for now.

**Comment by bsongis-frsky** [comment]
Next nightlies will include updates for all Horus

**Comment by spvwrx** [comment]
Fantastic, thank you.Best Regards SimonOn 9 Jan 2024, at 18:46, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Next nightlies will include updates for all Horus

**Comment by digitalonkel** [comment]
X10 ISRM is still missing. I would appreciate to get this variant.
Regards Rainer

**Comment by spvwrx** [comment]
I have been reliably informed it will be in the next nightly release.  I want it for my x12s..Best Regards SimonOn 14 Jan 2024, at 22:15, digitalonkel ***@***.***> wrote:﻿
X10 ISRM is still missing. I would appreciate to get this variant.
Regards Rainer
