### ISSUE TITLE
1.5 RC0 Deleting or moving a curve can cause curve reassignment in mixes!

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3199]
I've not been able to establish exactly when this happens, but can recreate the problem on both my tx and the 1.5 Simulator with my model definition which I am attaching. 
[temp1.5rc11.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13801014/temp1.5rc11.zip)

If you view the Mixer Ail-Rud you will see it has an action of Always on, Curve, 0 to 100 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/08a93193-d1a1-4c8f-b1dd-317beeff868b)

Now if you delete the Curve FixFlap you will see it does so without warning that the curve is in use elsewhere (which I don't believe it is as I am consoldating curves, which is why I am deleting it).

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/947b64ee-fb4a-4c66-814c-cdd95ca043ea)

Now if you look at Mixer Ail-Rud again you will see it has an action of Always on, Curve, 0 to -100 which is the curve below 0 to 100 (ignore the highlighting of another curve).

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/c5f0eae3-e1ca-44c0-b04d-020a36611925)

It appears that curve numbers are being used to select curves but are not always updated when curves are deleted, no doubt most occurences in the code are updated but at least one was missed. What is rather concerning is that some time back I reported a very similar problem with FM where they could be reassigned when a FM was deleted. It appears that the strategy of using numbers to assign things is prone to causing major problems and I question whether a different strategy may be found to prevent similar problems in future?

**Comment by Jedsters** [comment]
Update, the problem is worse than reported above and can be recreated more simply.

If you create a Free Mix (which the above Ail-Rud is) and have an Action which includes a Curve then even reordering curves up and down can change the curve assigment as well as deleting curves.

e.g. Have 5 curves A, B, C, D, E in that order on the Curves screen

Assign Curve C to a Free Mix Action

Now move curve D above B and you will see the Curve assignment change to B as that is now the third curve.

**Comment by Jedsters** [comment]
It appears that the problem is specific to Free Mixes - although I may be wrong.

**Comment by bsongis-frsky** [comment]
You are right, the fix is ready for RC1
