### ISSUE TITLE
Sounds deactivated after speed flight

### ISSUE THREAD

**Issue by Testname84** [FrSkyRC/ETHOS-Feedback-Community#320]
Today I expected the following issue:

Coming down from 150m above
vario was doing it's thing
but after the speed flight only vario worked
no flight mode sounds or trim sound where given out anymore

Tx: X12S
Ethos: 1.0.7

**Comment by MIKE-DAILEY** [comment]
Just tested a few times with 1.0.7. and it is working OK for me https://www.rcgroups.com/forums/showpost.php?p=47126973&postcount=6985

**Comment by jfint** [comment]
do you have a switch to turn Vario off?  Did you try turning it off?  I have seen radios where the vario ends up buffering loads of sounds, and effectively preventing others from playing.  You mention a zoon down, Vario is also working OK for me, but I haven't down a multi second descent yet.

**Comment by Testname84** [comment]
Yes I use a switch. I tried to switch Vario off but still no sounds. Curious is, if the Vario ist switched off and I do a fast flight the sounds also stop working. Maybe there's a problem how the data is handled.

**Comment by bsongis-frsky** [comment]
Fixed in the same time than #364
