### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#3200]
Hi,
first Happy new year!
i've installed 1.5 after loosing all my sounds files when i did a bad choice  in ethos suite, i put the sounds files back in the folder:
sd/audio/fr/fr/system
sd/audio/fr/mes sons
and made changes in General system menu.
If i put system sound directly under audio/fr/fr it doesn't work (no warning sound when i start the radio) i have to put it under another sub directory named system and it's working BUT when i want to select a file to read in a timer i only get --- until i put a file under audio/fr/fr sub directory, it doesn't read "system" sub directory or "mes sons" custom subdirectory, (including system general value) is it normal or it is suppose to use one of the directory selected in the general menu?

Thanks

**Comment by mawzthefinn** [comment]
If you have 'Fr' selected as your main voice, it will read system sounds from /audio/fr/fr/system and custom sounds from /audio/fr/fr/

/audio/fr/mes sons must be set as the second or third voice in System->General and then you can read custom sounds from there by selecting that voice. If you want a second set of system sounds, you need to put them in /audio/fr/mes sons/system and then select that  voice for the callout.

**Comment by ronron84** [comment]
i know that but the timer sound choice is not available if you don't put file in audio /fr/fr instead of System or second voices directory

**Comment by mawzthefinn** [comment]
Timer sound shows up for the voice selected for the timer.

I just tested, and Play File is correctly populated for the secondary voice so long as it's the voice selected for the timer.

**Comment by ronron84** [comment]
voice appear in chrono now it is running good thanks mawz
