### ISSUE TITLE
Mixage visual separator

### ISSUE THREAD

**Issue by GiPaEthos** [FrSkyRC/ETHOS-Feedback-Community#3202]
On models with many outputs (scale sailplane for example) I use a lot of Mixage. 
I order to sort them and allow me to easily find them I use to create empty mixage to separate the model mixages per groups (tail mix, winf mix, motor mix, ...).
Is it possible to add in Ethos Mixage page a new function 'Separator' in order to visualy separate the Model Mixage by Function?
It could be a new box into the Mixage list with the ability to only name it and with a specific visual aspect (color).
What would be ideal is to automicly move the Model Mixage under a 'Separator' like done by a 'Tabulation'.

Thank you.

French translation :
Lors de la programmation de modèles complexes nous devons gérer plusieurs dizaines de mixages. Afin de faciliter l'organisation de tous ces mixages j'ai pour habitude de les regrouper par fonction (Empennage, Ailes, Moteur, Autres...) et d'insérer un mixage libre vierge entre chacun de ces groupes de mixages. 
Serait-il possible d'ajouter sur la page Ethos avec la liste des Mixages une nouvelle boîte du type  'Mix Groupe' ou 'Charter Separator' qui aurait pour effet de créer une ligne dans la liste des mixages pour laquelle seul le nom serait modifiable ? Afin de mieux visualiser les chapitres cette nouvelle ligne aurait une couleur spécifique.
Dans l'idéal tous les mixages situés sous un 'Separator' serait décalés vers la droite à la façon d'une tabulation.

Merci,

![1704203538788](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/155453239/1de62a49-bc2f-423e-82ae-31083c5dd3a3)

**Comment by strgaltdel** [comment]
how about this idea ?
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1900

**Comment by noamkrief** [comment]
Need same for logic switches. So we can organize without big clutter.

**Comment by bsongis-frsky** [comment]
Duplicate of #1900
