### ISSUE TITLE
1.5 RC0: GVAR trim action "add" doesn't distinct which kind of source is used, so it doesnt fulllfill expected behavior in some cases

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3203]
i asked users in a german forum what they would expect by this config, in case switch SF would have been activated
(in this example trim channel was configured to deliver +/- 10%)

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/f9d629ab-8a46-4b3f-8435-dfe6680a260d)

4 users answered but no one gave the result what Ethos is doing now,
so i would say the actual implementation doesn't make it right..

What do we have in RC0?
as soon as the SF switch activates the "add" action, Ethos adds the 8% and sets -77% as the value of the GVAR.
So far, so good.

Shortly afterwards (approx. <1/10 second), the calculation loop starts again and 8% is added once more.

However, since the limit of -75% now applies, the GVar remains at -75%.

If I had set the limit differently, e.g. to +20%, this value would have been reached in much less than a second!

The value of the "trim channel" therefore only varies the speed at which the set limits are reached.

As soon as the trim channel is not equal to 0%, the previously defined limits are "approached".

I don't see any sensible use case for this (except possibly in functional models), most users will want to trim to a previously GVAR value within the limits.

**Status Quo:**
There is no distinction made between the use of trim buttons, which change a value per pulse, and "analog sources" which deliver constant values.

**Proposal in case "analog sources" are used for trimming:**
Imho, as soon as the "action" becomes active, the base value must be temporarily stored as a "temporary-constant" and the value coming from the source ( here "channel value") has to be added.
That's what the users (and me) would have expected

please, do not calculate iteratively for each loop in case user declared an "analog" source

regards
udo

**Comment by bsongis-frsky** [comment]
I will add more functions in 1.5.1
Perhaps
- Add and Store (as done today)
- Add only

**Comment by bsongis-frsky** [comment]
All Vars enhancements merged to #3821
