### ISSUE TITLE
Odd LS summary display / behaviour

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3206]
I've not been able to recreate this so far, but something isn't right as far as I can see.
1.5 RC0
Please see the attached model
[temp1.5rc0.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13821128/temp1.5rc0.zip)
Looking at the LS I have just created LS 63-67, using some cloning (not sure if relevant)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/d48f84ca-a3a2-4ace-8e22-3aeaaf34f348)

Looking at LS66 (and 67) the Summary is LIFE, RxBatt >= 6V and yet looking to the right we can see the function is A<X which it should be, so why is the summary >=  ?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/365b97c3-bdb7-481a-a8d2-f791eda70f9c)

Somehow, LS65-67 are all function A<X  and yet the summary for 66,67 is incorrectly A >= X

At a total guess, maybe I cloned 64 to 66 and in the act of removing the Max and changing the function from A>X to A<X something has gone wrong. I most likely cloned 66 to 67 before noticing the problem too.

Obviously if I manage to work out how to recreate I'll update this, but you can see from the attached model def something is wrong.

Thanks

**Comment by Nicholas-Luoyi** [comment]
You choose the < function and open the Inverted switch. So it's >=

**Comment by bsongis-frsky** [comment]
The "Inverted" flag is missing in the right column obviously!

**Comment by Jedsters** [comment]
I notice this  scenario now shows as A<X Inverted
Thanks
