### ISSUE TITLE
Sr6 Mini stabilization not working 

### ISSUE THREAD

**Issue by nickdoebbi** [FrSkyRC/ETHOS-Feedback-Community#3207]
If you open the device tap and calibrate the rx you’re not able to switch on stability modes. Radio will switch it of immediately. Radio X20 on 1.5 RC0

**Comment by mgsanna** [comment]
SR6 MINI with correct Lua Script works as supposed... X20S RC0 1.5.0 Flex Firmware

**Comment by mawzthefinn** [comment]
You need the Lua, available from Frsky-rc.com, Device Config->SxR does not support the new stabilizers at the moment
