### ISSUE TITLE
1.5:  Add an "Invert" option for repurpose trim "sources"

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3208]
the current repurpose action does not allow any options
this can lead to non-logical/ not-intuitive behavior for users
two examples:

(1)
using horizontal trims
the user wants to adjust aileron weighting and differentiation (setup via GVAR) simultaneously via horizontal trims
e.g. weighting on the aileron trim leads to GREATER deflection / effect on "trim right direction" with standard setting (push trim into right direction >> greater GVAR value >> more deflection)
but
changing Differentiation using rudder trim leads to increased differentiation and therefore LESS deflection/ effect on the aileron by using same trim direction

(2)
using vertical trims:
typically negative values are used for "elevator push down" and positive values for a "pull up" effects
Accordingly, a curve for adding an "elev. down" component to mixers looks something like this (here Butterfly compensation curve):
![elevtrim](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/ecbf08d6-5fc4-4f82-b166-67703e748290)

If you want to use "repurpose" to adjust a Y-curve point using a vertical trim, the effect is exactly the opposite of the classic control:
"trim down" would cause more positive elev. deflection ("pull up" movement)

proposal:
The contradiction could be resolved by adding an "invert" option to the repurpose action, e.g. via the hamburger menu,
see here:

![repurp](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/36d921dd-6ea1-4256-85bf-ae908eb6aff4)

in addition, this "hamburger" solution could be used for further improvements in later releases, like setting options for individual trim step-width during a "repurpose session"
as far as i know by now only a standard setting used, configs from the trimmer menues are not applied in "repurpose mode"

btw
I am aware that the problem can be circumvented by using double inversion
(both in the GVARs and in the mixers), but I think this is not an intuitive approach and will irritate some users

**Comment by bsongis-frsky** [comment]
Fixed with #3696
