### ISSUE TITLE
FW 1.0.7 Bluetooth headphones issue

### ISSUE THREAD

**Issue by TWSreviews** [FrSkyRC/ETHOS-Feedback-Community#321]
I have paired headphones and works first time pair but after shutdown doesn't work. 
Shut down radio and headphones. 
Restarted radio then powered up headphones and the radio saw a device and listed a code but didn't reconnect and work as audio device.
Tried two types of headphones

**Comment by MIKE-DAILEY** [comment]
Just tested a few times again with 1.0.7. and it is OK for me https://www.rcgroups.com/forums/showpost.php?p=47126973&postcount=6985

**Comment by TWSreviews** [comment]
I have tried it with my ear buds and Sony headphones and no joy. Only works the first setup and never again after.
Tried all steps several times with both headphones.

**Comment by MIKE-DAILEY** [comment]
The New Bee connects pretty fast but others can be slow to connect.  Did you give it a min or two connect?

**Comment by TWSreviews** [comment]
> The New Bee connects pretty fast but others can be slow to connect. Did you give it a min or two connect?

I did.....was programming and was still wearing headphones for about 5 minutes until my wife started complaining about the beeping. checked wireless tab and it saw a device code but wasn't the headphone name showing and didn't work. Sony or ender headphones.
