### ISSUE TITLE
1.5 nightly sim: Setting weight in one mix incorrectly propagates to other mixers

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3211]
I have two identical free mixes, both output to CH1

```
MIX1: source=MAX, action=weight/100%/always on, function=ADD
MIX2: source=MAX, action=weight/100%/always on, function=ADD
```

I edit MIX1 only, changing the weight from 100% to 50%

_expected_ the weight MIX1 should be 50%, MIX2 should remain at 100%
_actual_ the weight changes to 50% in both MIX1 and MIX2

The same happens if the source of one mix is change to, say, Rudder.

It works as expected if the mixes output to different channels. 

**Ethos X20S sim, v1.5 16 December**

**Comment by bsongis-frsky** [comment]
This one has been fixed since some time, no? Why don't you work on RC0?

**Comment by bsongis-frsky** [comment]
I will start again the nightlies tonight, then you can check if the bug is gone

**Comment by Wolepo** [comment]
Ich habe das gleiche Szenario in einem Modell simuliert. Wenn ich eines der Gewichte ändere, ändert sich kein Wert im anderen. Letzte Nightlies/Sim X18SIch habe das gleiche Szenario in einem Modell simuliert. Wenn ich eines der Gewichte ändere, ändert sich kein Wert im anderen. Letzte Nightlies/Sim X18S

**Comment by strgaltdel** [comment]
tried this with the lates X20 nightly on Sim (rev 21.dec):

- add a freemix,  "Max/Add/100%/alwaysOn/output Ch1"
- clone this freemix 
- change 1st mix weight to 85%

result is as expected, without error
freemix 2 remains on a 100% weighting.
(same result as wolfgang/ "wolepo" got)

**Comment by bsongis-frsky** [comment]
Yes, I remember this issue had been reported and fixed very quickly
