### ISSUE TITLE
An inverted FS displays as negative instead of exclamation mark

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3212]
Noticed in 1.5 RC0

When creating a LS which uses a FS, if you invert the FS it displays as **-FS**   Elsewhere inverting is displayed with a ! rather than  - so surely this should be displayed as **!FS**

See below from the sim which shows 2 inverted conditions which display as -FS1 and !SA

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/5f5b0c4a-e830-4008-b146-9bc9b4075f46)

I've not tested if this applies to FS used outside of LS or not.

Thanks

**Comment by bsongis-frsky** [comment]
Thanks for this testing work, some of your issues are there since long!

**Comment by Jedsters** [comment]
Thanks! 
Actually, with the introduction of VARs etc., I've decided to recreate my template from scratch and simplify it as far as I can, so it's more a case of noticing issues as I go along than actually doing deliberate testing. But I'll take the thanks either way. ;)

**Comment by bsongis-frsky** [comment]
:)

**Comment by Jedsters** [comment]
Thanks
