### ISSUE TITLE
[Feature Request] Add Serial port profile to bluetooth for streaming of telemetry and control input data

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#3214]
A great feature would be to have an option to use the bluetooth module as a serial port allowing for the streaming of data such as telemetry values, stick and switch positions, and system events, etc.  This would allow for 3rd party integration with IOS/Android applications to create things such as ground stations, data loggers, external remote id, etc.

**Comment by bsongis-frsky** [comment]
It should already work this way for Telemetry. Have you tried?
Perhaps we could also setup another way of forwarding Telemetry, not only S.Port mirror.

**Comment by fdm225** [comment]
thanks, I see that in the manual but do not see any info about the serial connection itself; not to mention that it's specific to the FreeLink App.  Does this only stream telemetry or is there information for things like input changes (switch, stick, slider, etc)?  I ask as telemetry information is great but knowledge of the switch change events, throttle position, etc would make this amazing.  Also, is there any documentation on the serial port setup (baud rate, stop bits, etc)?

thank you for the reply!
dave

**Comment by mawzthefinn** [comment]
It streams telemetry. The format is well documented (it's standard S.Port serial signalling). 

The radio does not directly report any of the other items you mention, only channel positions in the logs.

**Comment by fdm225** [comment]
Thank you for the information
