### ISSUE TITLE
1.5.0 ELRS Vario cannot be activated

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3217]
1.5.0 ELRS Varioton cannot be activated

Vario is found in the sensors.
Varioton and settings are not possible.
Programming mask is incomplete.

Greetings Eugen

![Bild 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/01c26421-9e8d-4459-ac86-7cadc52ee25a)

![Bild 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/f47a0a94-f6b6-4d29-b643-b72c063a072d)

![Bild 3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/a77223a3-c70b-4898-80d2-c8e2fd7243f8)

**Comment by bsongis-frsky** [comment]
Fixed in the same shot than #2335
