### ISSUE TITLE
Ethos lua dor inav

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#3218]
When is it possible for Ethos to have a lua for inav?  I get a value in degrees from the flight controller, for example for satellites.  or is it possible to adjust the sensor so that I get a number sats
![IMG_20240105_114946](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84266308/19ea912f-b103-4215-b762-bc8c197baf60)

**Comment by mawzthefinn** [comment]
Should probably ask the iNav team that question, everything is in place for them to develop one should they choose to

https://github.com/iNavFlight

**Comment by mawzthefinn** [comment]
Closing as answer provided.
