### ISSUE TITLE
(1.5 RC0) "Flight mode" Mixer Only 10% Range each way when using Switch as Input

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#3219]
As per title.  

It's normal to have the flight mode on a switch.  However, when a switch is assigned to the Flight mode mixer, it only gets around 10% each direction, which isn't enough to work for most flight controllers to trigger each different mode, including FrSky's own SRx series receivers.  When a pot is assigned, it can go the full range -100 to +100.

**Comment by bsongis-frsky** [comment]
Which mix do you use? FreeMix? And what is the Input of your mix?

**Comment by bsongis-frsky** [comment]
Would you also ensure that this problem hasn't been fixed since RC0 (in latest nightlies which are more recent)?

**Comment by BladeScraper-Designs** [comment]
I used the canned "Flight mode mix".  I just installed the nightly (#b2ae59a4) and now the canned mix for flight mode, gyro are gone entirely from the "add mix" menu.  However, when creating a Heli model, the flight mode mix is made still, and the original issue persists.  Switch maxes at +-10%, Pot or other analog has full +-100%.

**Comment by BladeScraper-Designs** [comment]
Switch on input.  Full switch travel range, Mixer output is +- 10%.
![20240109_114002](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40482965/d8ed4ffb-0b25-4791-8de5-3ccc560c704e)

Analog (Pot1) on input.  Full pot travel range, Mixer output is +- 100%.
![20240109_114036](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40482965/c3a15692-752d-4247-8f31-eec807d1cdce)

**Comment by bsongis-frsky** [comment]
Ready for RC1
