### ISSUE TITLE
1.5 RC0 free mixes - user cannot set default values for actions 

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3220]
In 1.5 free mixes, the default value for weight is 100%, and the user cannot change this because there is no priority system for actions (all actions are considered).

This has some negative implications. For example, if the desired default weight is 15% and the user has say 5 flight modes - if just one flight mode is 20%, the user must create one action for each flight mode.  even though there are only two values.

```
Action weight, 15%, FM1
Action weight, 15%, FM2
Action weight, 15%, FM3
Action weight, 15%, FM4
Action weight, 20%, FM5
...
```
Worse, if the user forgets to specify a condition, then the full 100% will be applied perhaps leading to a crash.

Suggestion: a solution might be to add a special '_All other_' condition for free mixes. It would be active _if there is no match for the action in any of the items above that position in the stack_.  When is positioned after the last line for an action, it will act as a default. Example:

```
Action weight, 20%, FM5
Action weight, 15%, 'all other'
...

**Comment by fhpage** [comment]
Another option is:
Action Always on, weight, 15%
Action weight, 133%, FM5  (Which gives ~ 20%)

Or (as you know) use a VAR.

**Comment by RC-SOAR** [comment]
The first workaround - specifying 'action weight 133%' to achieve a 20% rate - is not very readable and would be even less so with more than two distinct values. 

The second workaround - 'Action !FM5, weight, 15%' - is okay for this particular example, but in the general case would required ever more complex logical switches.

Yes, you could do it via a VAR. But it would also mean setting up a VAR for every weight which _might_ require multiple values in the future.

The 'all other' proposal would keep everything in one mix. As I described it, it would not require a lookahead down the action stack so I'm guessing it should not be too complex to implement.

**Comment by Jedsters** [comment]
Isn't this what VARs were designed to address?  e.g. I use a weight of Ail Rates which is a VAR Source

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/8a79ce8f-6cae-472e-abaa-c4140fe52a30)

and then the VAR can specify as many options as needed with a default of your choice

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/875c30c2-eea0-449c-b326-0b00797e2622)

in this case SG - and SG up with the default controlling every other eventuality. OK, in this case there is only one other eventuality but the Values could have specified just SG Up with the default handling the 2 other values.

**Comment by Jedsters** [comment]
This may have been more useful for your specific example

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/a71b3731-9f08-45ae-8f88-a776eff7efda)

**Comment by RC-SOAR** [comment]
So how would you pass a default _curve_ using a VAR? 

I don't believe you can.

The proposal is not just for actions of type weight. It would apply to any type of action. Curve, slow, expo etc.

**Comment by Jedsters** [comment]
Isn't the Action of Always On the default?
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/df96e02d-6989-4c2c-af23-567f08662944)

**Comment by bsongis** [comment]
I would say here you should use a VAR. The same for Slow / Expo.
For Curves I would use one condition per Curve, possibly using a Logic Switch as condition.

**Comment by RC-SOAR** [comment]
Just one final push to try and sell the benefits of a default 'all other' condition.

Here are three ways of achieving the same thing. First, using the OTX/Ethos 1.4 method, then Ethos 1.5, then with 'All Other'

**OpenTX/Ethos 1.4**
```
FreeMix cvA 10% FM1 
FreeMix cvB 10% FM2 
FreeMix cvC 10% FM3 
FreeMix cvB 15% FM4 

```
**Ethos 1.5**

```
VAR1:
10% (default)
15%  FM4

LSW1: FM2 or FM4

FreeMix
Action curve CvA FM1
Action curve CvB LSW1
Action curve CvC FM3
Action weight VAR1
```
This is not easy to validate or extend. 

**Ethos 1.5 with 'All Other' proposal**
```
FreeMix
Action curve CvA FM1
Action curve CvC FM3
Action curve CvB AllOther
Action weight FM4 10%
Action weight AllOther 15%
```
Easy to validate and extend - important for complex setups and templates.

At least we still have the option to use the 1.4 method, but it seems a shame given the potential power of 1.5.

**Comment by bsongis** [comment]
I don't understand, this works on Ethos 1.5 too, no?

```
FreeMix cvA 10% FM1 
FreeMix cvB 10% FM2 
FreeMix cvC 10% FM3 
FreeMix cvB 15% FM4 
```

Or even

```
FreeMix 
 - cvA 10% FM1 
 - cvB 10% FM2 
 - cvC 10% FM3 
 - cvB 15% FM4 
```

The proposed way in your post above is not clear enough for me, it looks like an `else` but you are not sure to which `if` it belongs

**Comment by Jedsters** [comment]
Is this the sort of idea you are after Mike?
Your comments did get me thinking and I can see this could be useful. Apologies if not.
It has all the options of a Free Mix with Sources for each so everything can be combined into a single mixer.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/be121049-3e11-4cb6-9815-a4703c815013)

**Comment by RC-SOAR** [comment]
Bertrand, just to clarify first, the problem is to implement the following states for four FMs:

Curve= CVA, weight=10% ActiveCondition = FM1
Curve = cvB weight=10% ActiveCondition = FM2 
Curve = cvC weight = 10% Active Condition = FM3 
Curve = CvB weight= 5% ActiveCondition = FM4 

You mentioned this could be implemented in a single mix in 1.5:
> 
> ```
> FreeMix 
>  - cvA 10% FM1 
>  - cvB 10% FM2 
>  - cvC 10% FM3 
>  - cvB 15% FM4 
> ```

Maybe I've misunderstood, but I don't how this can be done in a single mix. 

> The proposed way in your post above is not clear enough for me, it looks like an `else` but you are not sure to which `if` it belongs

Sorry if it wasn't clear... ALL_OTHER is not an if/else mechanism. It's a way of catching actions which are not matched, that is, provide a default value. 

Consider a Free mix with three actions for weight:

```
FreeMix
Action1 =Weight, Value=X, ActiveCondition=FM1
Action2 =Weight, Value=Y, ActiveCondition=FM2
Action3 = Weight, Value = Z, ActiveCondition = 'ALL_OTHER'
```
If FM1 or FM2 are active, Action 3 would _not_ be mached, since there is already a match above this line.
If any other FM is active, Action3 is applied, since there is no match above this line.

_Each action (Slow, Curve, Weight etc.) would maintain its own ALL_OTHER state._

To keep the algorithm simple, ALL_OTHER would only consider lines above it in the stack. Any subsequent lines would be handled in the normal way. Therefore, to act as a true default, ALL_OTHER must be the last condition for a particular action. Which is fine, IMO.

The benefits are: 

- Provides a safety net, since it is no longer necessary to cover every single possible condition with a dedicated action.
- Avoids the need for complex logical switches

**Comment by RC-SOAR** [comment]
> Is this the sort of idea you are after Mike? Your comments did get me thinking and I can see this could be useful. 
> Apologies if not. It has all the options of a Free Mix with Sources for each so everything can be combined into a single mixer.

The proposal is just a mod to the existing 'action' mechanism, It would not involve a radical redesign.

IMO actions are really cool, but it should be possible to define default values.

**Comment by fhpage** [comment]
My concern is this is an attempt to implement yet another way to do a job that already can be done with multiple free mixes, which just delays 1.5 going to production even longer.  Does it really make a big difference if the logic is in one mix or multiple mixes?

**Comment by Jedsters** [comment]
If I'm understanding, I guess another work-around for your example above

FreeMix
Action curve CvA FM1
Action curve CvC FM3
Action curve CvB AllOther
Action weight 10% FM4 
Action weight 15% AllOther 

Would be one LSW for each of Curve, Weight etc. i.e.

LSW FMxCurves
OR FM1, FM3

LSW FMxWeights
OR FM4 

FreeMix
Action curve CvA FM1
Action curve CvC FM3
Action curve CvB !FMxCurves
Action weight 10% FM4 
Action weight 15% !FMxWeights

Which I think would give the safety net you're after, but slightly messy that you have to keep the LSWs in sync with the Free Mix.

**Comment by RC-SOAR** [comment]
> but slightly messy that you have to keep the LSWs in sync with the Free Mix.

Exactly.

**Comment by fhpage** [comment]
How about a priority like Inputs in OpenTX.
First true line in the list is used. Rest are ignored. 
Action Always would be your default, last in the list.
No confusion...

**Comment by Jedsters** [comment]
> So how would you pass a default _curve_ using a VAR?
> 
> I don't believe you can.
> 
> The proposal is not just for actions of type weight. It would apply to any type of action. Curve, slow, expo etc.

I've just noticed the following in the manual

> With the Free Mix and some other mixes, you can specify up to 6 curves, each with a condition. If more than one condition is true, the curve higher in the list prevails.
So a last curve Always On would be a default.

But the others, Weight, Differential, Offset and Slow could all be done with VARs.

**Comment by Jedsters** [comment]
Although my testing suggests the curve lower in the list prevails. I've raised #3241 for that apparent contradiction.

**Comment by bsongis-frsky** [comment]
Proposal

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ab203f65-4ff6-4bf2-9ce5-7b8a03d4f63d)

**Comment by bsongis-frsky** [comment]
If the proposal above fits your needs, I would extend it to the `Curve` and `Offset` actions. I don't believe it's needed for the other actions.

**Comment by bsongis-frsky** [comment]
Or this one ...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4e83f950-b892-4139-8e9b-e8b0f81dac0d)

**Comment by RC-SOAR** [comment]
Yes , 'Otherwise' looks great, and it preserves the UI :-))

Can we have it for other actions as well as weight? For example, consider a set of Curve actions. There are 5 FMs. FM1 uses curvce CV1, all other FMS default to CV2. With 'otherwise' the curves would be just be two lines. 

Also I think 'otherwise' should also be optional or default to 'passthru'. So for example, with curves, you might 'passthru' (no curve) to be the default. Again, same applies to slow, diff etc.

I think with these mods, it would be perfect.

**Comment by bsongis-frsky** [comment]
@Jedsters I have checked, curves can be stacked and are used in order. Example:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/cccabe49-7f70-488a-93f3-d1362b0f975b)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/91a27da5-3e44-460d-bb83-e751fdb65cfb)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ffcd09e9-d446-4faa-8f72-07614decf3da)

**Comment by Jedsters** [comment]
It looks like things have moved on a fair bit since my previous post, I tested at 1.5 RC0 and it didn't look right, I've just redone the same test using the latest nightly (shows as Jan 4 2024 on Info) and agree both curves are being used.
Thanks

**Comment by bsongis-frsky** [comment]
Perfect! Also latest nightlies are already old, I will try to launch them tonight again.

**Comment by bsongis-frsky** [comment]
The same for curves ...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6955f12c-3bbb-4024-a311-4fc2ddbfca00)

**Comment by bsongis-frsky** [comment]
Ready for RC1

**Comment by RC-SOAR** [comment]
Just testing the 'Everything else' condition with 19 Jan nightly - looks really good.
