### ISSUE TITLE
Timer triggers need to have an edge condition available 1.5 RCO

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3221]
Radio: FrSky X20S running on 1.5 RCO

There used to be  inverse and edge options available for the reset fields in the 'Timer edit' screen in  1.4.x. The edge option is now gone in 1.5 RC0 and with the introduction of start and stop conditions being used instead of an active condition should be added to the long-press menus in the start and stop condition fields as well. 

In previous releases I used logical switch named 'Flight Timer' to be the active condition for the timer and the reset trigger was the edge condition of that logical switch. That way the timer would zero when I launched. Now the edge option is not available. Pictured is a timer that made the transition with the edge condition still in tact, and working (others did not), and a timer that is freshly built showing that there is no edge option available. 
![IMG_0475](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/579a931b-00dd-40ae-89fc-ad3ef2f5a151)
![IMG_0476](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/ea4799cb-5596-44ae-b94e-d9b6dcc8a8ac)

**Comment by spoke2570** [comment]
I now have one model where the edge condition was intact and working after the migration to 1.5 RC0. I have 1 that the edge condition  does not  work but the edge symbol won't go away unless I choose a different switch type (ae. physical vs logical).  Seems the timer reset field has some issues.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/51a539e0-037d-46aa-b71e-4ecbf48c828c)
