### ISSUE TITLE
Lua timer functions removed in 1.5.0 RC0

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#3222]
I need to adjust the audioMode via Lua.  timer:audioMode() doesn't seem to exist in 1.5.0 anymore.

I also need to be able to adjust the timer:countdownStart() and timer:countdownStep().  It appears those were removed in 1.5.0 RC0 too.

Where they moved somewhere else in lua?  I can't seem to find them in the 1.5.0 RC0 lua_docs.

I am trying to make sure my F3K_Training lua script is functional on 1.5.0 when it is released but is if failing on this code that used to work.

**Comment by bsongis-frsky** [comment]
```lua
timer:audioActions({
        {type=COUNTDOWN_VALUE, start=10, step=30},
        {type=COUNTDOWN_BEEP, start=11, step=31},
        {type=PLAY_FILE, start=12, step=32, filename="test.wav"},
        {type=PLAY_VALUE, start=13, step=30},
    })
```

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/e326cc5f-a2eb-44a6-85ef-f0e4c3e32d7f)

**Comment by agibson2** [comment]
I know you are busy so maybe someone else can show an example of how to set them, change existing ones, and remove them, etc.

Is it as simple as overwriting it to change it if I only need 1 action?
timer:audioActions = { {type=COUNTDOWN_VALUE, start=10, step=30} }

And then later

timer:audioActions = {type=COUNTDOWN_VALUE, start=20, step=30}

**Comment by agibson2** [comment]
This doesn't appear to be working.  I am running the latest nightly.
```
        model.createTimer("f3kOne")
        timer = model.getTimer("f3kOne")
        timer:audioActions({type=COUNTDOWN_VALUE, start=540, step=60},
                           {type-COUNTDOWN_VALUE, start=15, step=1})
```

It does not set any actions for the timer.

**Comment by bsongis-frsky** [comment]
Yaapu also told me yesterday that something is broken around `createTimer`

**Comment by bsongis-frsky** [comment]
> model.createTimer("f3kOne")
>         timer = model.getTimer("f3kOne")
>         timer:name("f3kOne")
>         timer:startCondition( system.getSource(nil) )
>         timer:audioActions({type=COUNTDOWN_VALUE, start=540, step=60},
>                            {type-COUNTDOWN_VALUE, start=15, step=1})

2 mistakes  in your code:
- createTimer doesn't take a "name", parameter so your getTimer will return nothing
- audioActions takes a table as parameter (and there is only one parameter)

Here the fixed code:

```lua
timer = model.createTimer()
timer:name("f3kOne")
timer:startCondition(system.getSource(nil))
timer:audioActions({
    {type=COUNTDOWN_VALUE, start=540, step=60},
    {type-COUNTDOWN_VALUE, start=15, step=1})
})
```

**Comment by bsongis-frsky** [comment]
Yaapu had another problem, he used the API from 1.4 and there are differences with 1.5

**Comment by agibson2** [comment]
Sorry... i copied the wrong code.  Thanks for the info and help.  I am initializing the timer correctly  it seems as that is being created.  This is what I had.  Removing the code for checks on nulls, etc and such.

timerId = "f3kOne"
timer = model.createTimer()
timer:name(timerId)
timer:startCondition( system.getSource(nil) )
timer:audioActions({type=COUNTDOWN_BEEP, start=beepstart, step=60},
                             {type=COUNTDOWN_BEEP, start=15, step=1})

Looking at your example, it looks like you have a extra line that shouldn't be there "})"
I changed the bottom line of my code to...
timer:audioActions({ {type=COUNTDOWN_BEEP, start=beepstart, step=60},
                              {type=COUNTDOWN_BEEP, start=15, step=1} })
                           
Still the same result.  No actions when looking at the timer in the GUI.  It is creating the timer.  Just no actions.

I don't see any errors in the debug console output on the simulator.

**Comment by bsongis-frsky** [comment]
I have tested it again this morning:

```lua
timer = model.createTimer()
timer:name("f3kOne")
timer:startCondition(system.getSource(nil))
timer:audioActions({
    {type=COUNTDOWN_VALUE, start=540, step=60},
    {type-COUNTDOWN_VALUE, start=15, step=1})
})
```

`audioActions ` takes an array of audio actions, this is the reason of the double `{`

**Comment by agibson2** [comment]
Thanks for taking the time to kick my brain into gear.  The problem was the code for actions wasn't being hit because of my coding error in the check around that section of my code.  Sorry for wasting your time on this.  I am sure once I get that corrected, It will start working.

**Comment by agibson2** [comment]
Worked just fine.  Thanks again for the help.

**Comment by agibson2** [comment]
I can't figure out how to remove actions.  I need to remove the actions at some point.

I tried both of the ways below and...

This one doesn't appear to change any of them that are already there.
timer:audioActions(nil)

This one seems to set the timer to 2:00 count down with a 30 second step.
timer:audioActions({ {nil, nil, nil} })
