### ISSUE TITLE
Ethos telemetry 

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#3223]
Firmware 1.4.8
HW 1.4.0 FW 2.2.6

Error in the telemetry transmission from inav to Ethos. the sensor temp1 and temp2 in my case I use the German interface.  But inav sends the value temp1 and temp2 and a four-digit number must be displayed, not in degrees. Please fix it.
![IMG_20240106_092600](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84266308/5f2aefc1-85fc-4204-9ba3-98bdd82f1627)
![Screenshot_2024-01-06-10-56-48-123_com android chrome](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84266308/262731a8-2153-417f-af54-9fd94429f7ee)

**Comment by mawzthefinn** [comment]
This appears to be an iNav issue at first glance, if the sensor ID for the value indicates it is a temp sensor, it is going to get displayed as such, which means degrees not an unformatted.

it looks like iNav is trying to stuff their data into an improper data format.

**Comment by bsongis-frsky** [comment]
Indeed
