### ISSUE TITLE
A Cloned Throttle mixer give different channel output

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3224]
Please see the attached model 
[odd prob 1.5rc0.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13849167/odd.prob.1.5rc0.zip) which was created using 1.5 RC0. 
Now go into Edit on the Throttle Mix and look at Output1 
I noticed that as I move the Throttle Stick (left stick) throughout its range that the Channel % did not follow the Mixer % which I couldn't understand.
I therefore Cloned the Throttle Mix and changed the Output channel to 15 in the cloned mixer with a view to experimenting with this new mixer to understand what was happening.
Now go to the second page of Outputs so you can view Ch14 and Ch15 and move the throttle stick throughout its range and you will notice that the Channel % does not behave consistently for ch14/15.
At this point I simplified my original model (deleting lots of mixes, deleting the landing FM, removing Throttle Triggers and changing VARs to Value etc.) to try and pin down the problem and the above model is a copy of that slimmed down model. 

I believe that Ch15 behaves correctly but can not explain Ch14 behaviour.
For both channels the Curve has a dead band from -100 to -50 so as you increase the throttle stick nothing happens at first, when you reach -50 on the throttle stick the mixer starts to increase, however it is not until you increase the throttle stick to around -25 that the output starts to increase. I notice that -25 on the throttle stick also corresponds to -50 on the mixer so it feels like the output is applying the curve to the mixer rather than the throttle stick. But that wouldn't explain why the cloned mixer appears to work as expected.

I am obviously aware of #3199 and #3213 and have moved curves and vars around while the original Throttle mixer was defined but I'm not sure that explains this problem as the curve I am using is the one I want, i.e. Motor.

I guess my problem could be a hang over from one of the above problems, but if that is the case then anyone who has created a model before these were fixed probably needs to take some action, although it's not clear what. Possibly just clone the Throttle mixer and delete the original??? Or is the problem more widespread than that?

Thanks

**Comment by bsongis-frsky** [comment]
I cannot reproduce the issue on current code base, I guess it has been fixed recently. Feel free to reopen if it occurs again from next nightlies!

**Comment by Jedsters** [comment]
I wondered if you were able to get any clues from the model.bin to see what the difference was between the original and cloned, but I guess if you can't even reproduce then as you say, it must have been fixed. 
I'll download the nightly later this week) to check I can't reproduce either.
Thanks

**Comment by mawzthefinn** [comment]
Adding the answer here too.

You have applied the Motor curve in both the mixer and the output for Ch14.

**Comment by Jedsters** [comment]
Many apologies.
Thanks for your help.
