### ISSUE TITLE
X18 french display improvement

### ISSUE THREAD

**Issue by Ze-baloo** [FrSkyRC/ETHOS-Feedback-Community#3227]
Hi all 😁

While updating a bunch of x8r for a friend with my x18, i noticed that the display could be confusing, we can't read the complet sentence. 

I suggest to shorten it this way :
- Mettre à jour le périphérique externe becomes
MAJ Périph. externe
- Mettre à jour le module externe becomes
MAJ Module externe

Thanks
Laurent

![IMG_20240107_144042](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15279917/5b5ce5e4-0ec8-4780-87dd-f232e6413da9)
![IMG_20240107_144108](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15279917/2dc13870-8711-4547-b86d-3aec2e856d8a)

**Comment by Ze-baloo** [comment]
Sorry, i forgot to mention that i'm under ethos 1.4.15 😉

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2d25445d-ebb0-46e6-88ae-4ad16c91bc5a)

**Comment by Ze-baloo** [comment]
Thanks for all the hard work 😉

**Comment by bsongis-frsky** [comment]
In the same shot this screen will be improved too:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d5534e08-8e6a-4665-af1b-6050c4ffa5bc)
