### ISSUE TITLE
Request: VARs to have Ranges which can be other VARs

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3229]
I confess I don't know how possible this is and whether it could be too problematic, however it would be nice if VARs could have Ranges which could also be SOURCE, VAR values so that one VAR becomes dependant / limited by 2 other VARs. 

Thanks

**Comment by Wolepo** [comment]
Arvoissa voidaan kuitenkin valita lähteeksi VAR, jolloin voidaan saavuttaa oletusasetus.
![VARS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/e7d7e259-9c10-41f7-bcb6-d64e4a090d38)

**Comment by Jedsters** [comment]
Indeed, although not what I'm after. 

An example may be that VAR1, 2, 3 are X or Y values on a curve and I want to ensure that VAR2 always remains between VAR1 and 3 as I adjust it via an Action. If I could specify VAR1 and VAR3 in the Range values that would do it, without having to adjust all 3 VARs and their respective ranges.

**Comment by Wolepo** [comment]
Yes, it would be an advantage to be able to select an external source

**Comment by bsongis-frsky** [comment]
Ready for 1.5.0 RC1
