### ISSUE TITLE
Some Curves which are in use can be deleted without notification while others receive notification

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3230]
Tested in 1.5 RC0 
If you attempt to delete a curve which is in use by mixers you receive a warning message, e.g. 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/cd5702c6-850a-4af2-aef9-87dfd57cf42d)

however it you attempt to delete a curve which is in use by a Channel e.g. Curve  R Aileron

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/e0cd1b96-ae43-41a7-aa9f-50a0c332028e)

then no notification is given that the Curve is actually in use. This could give the incorrect impression that the curve is not in use and can be safely deleted. 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/7ef13c93-dbae-4885-bc8b-86f1ff377d09)

Please can we have notification as to when curves are in use by anything.

Thanks

**Comment by Jedsters** [comment]
Please can you check curves in the Throttle area too? I thought I deleted a curve used by Throttle or Throttle to Ele or similar mixer without warning, but when I tried to recreate this I failed so it may be my mistake - I was actually doing something else at the time so wasn't paying as much attention to this as I should have been.
Thanks

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/95a4a4be-e085-4596-b93d-951a0b902c08)
