### ISSUE TITLE
Purple text and line highlighting

### ISSUE THREAD

**Issue by KardashIvan** [FrSkyRC/ETHOS-Feedback-Community#3236]
Hello! After updating to the latest version of my FrSky x20s transmitter, I got an ugly purple screen and badly drawn fonts.
Repeated changes to the software did not help((( Can you help me? I'm desperate.

Here is a link to the video:
https://drive.google.com/file/d/1XWmLtlADMDxyVqPjqaZw8NosCVssXmVt/view?usp=sharing

**Comment by bsongis-frsky** [comment]
I guess you have changed the foreground color which is yellow by default
To be sure you could remove the radio.bin file and start again the calibration, you will restore all the original settings

**Comment by KardashIvan** [comment]
> Я припускаю, що ви змінили колір переднього плану, який за замовчуванням є жовтим. Щоб бути впевненим, що ви можете видалити файл radio.bin і почати калібрування знову, ви відновите всі початкові налаштування

I deleted the file radio.bin , but nothing changed(
Could you tell me how to reset all the settings to the factory settings?
