### ISSUE TITLE
1.5 RC0 Request: VAR Actions should include VARs as a Category

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3238]
With 1.5 RC0 it is possible to specify a Value Source with a Category of VARs and specify an alternative member

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/39c8f997-0ee3-4481-a459-0690301ca549)

however for Actions VARs are not an available category

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/5d3116df-7eb0-4614-9ed9-ce54e5464538)

I'm not sure if there is a reason for this, but on the face of it, it seems it could be useful.

Thanks

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d0782675-408d-40c8-9ae1-efa7345ecfa2)
