### ISSUE TITLE
Purple text and line highlighting 

### ISSUE THREAD

**Issue by KardashIvan** [FrSkyRC/ETHOS-Feedback-Community#3239]
Hello! After updating to the latest version of my FrSky x20s transmitter, I got an ugly purple screen and badly drawn fonts.
Repeated changes to the software did not help((( Can you help me? I'm desperate.

I deleted the file radio.bin , but nothing changed(
Could you tell me how to reset all the settings to the factory settings?

Here is a link to the video:
https://drive.google.com/file/d/1XWmLtlADMDxyVqPjqaZw8NosCVssXmVt/view?usp=sharing

**Comment by bsongis-frsky** [comment]
After more seriously reviewing the video, it looks to me very weird!

**Comment by KardashIvan** [comment]
> Після більш серйозного перегляду відео воно виглядає мені дуже дивним!

Returning to previous firmware versions did not change anything.
Everything was fine before. I don't even know what to do now.

**Comment by strgaltdel** [comment]
did you try to flash your x20 one more time, maybe using a new download ?

so, at least, you could rule out a bad download file

**Comment by KardashIvan** [comment]
> did you try to flash your x20 one more time, maybe using a new download ?
> 
> so, at least, you could rule out a bad download file edit: crossposting, so my advice is useless

I did a lot of downloads. It didn't work out.

**Comment by KardashIvan** [comment]
If anyone needs additional photos or videos, I'll do it, just let me know!

**Comment by strgaltdel** [comment]
what i would do:

- check, if a colorpicker menu (like screenshot above) would show any false colors & report "false" colors, maybe one can see some systematic errors
- test, if deactivation of darkmode would show proper layout

- disconnect battery over night and check if problem stays next day

**Comment by KardashIvan** [comment]
check, if a colorpicker menu (like screenshot above) would show any false colors & report "false" colors, maybe one can see some systematic errors
**- Nothing has changed**

test, if deactivation of darkmode would show proper layout
**Nothing has changed**

program an screenshot SpecialFunction and perfom a screenshot on a problematic screen, look into file what colors are used there
**Nothing has changed**

**Comment by strgaltdel** [comment]
mysterious

"check, if a colorpicker menu (like screenshot above) would show any false colors & report "false" colors, maybe one can see some systematic errors
- Nothing has changed"

what does that mean ("nothing has changed") ??
so the colors the from colorpicker didn't change according to the (OK) screenshot above, mentioned by jedster ? 
 
i would have expected changes at least in the "grey" colors, which should be colours from the lines rendered purple on your screen.
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/0df60e40-c2e5-4818-87ff-364abf02cb18)


when is select a grey color in the "highlight color" option (e.g. 5th from the left) it's decoded 88;92;88,
again, "Nothing has changed"", so its's the same decoding on your screen and it's grey ?




maybe you could post your screenshot here

**Comment by KardashIvan** [comment]
> таємничий
> 
> "перевірте, якщо меню вибору кольорів (як на знімку екрана вище) буде показувати будь-які хибні кольори та повідомляти про "хибні" кольори, можливо, можна побачити деякі систематичні помилки
> 
> * Нічого не змінилось"
> 
> що це означає ("нічого не змінилося")?? тож кольори з вибору кольорів не змінилися відповідно до (ОК) знімка екрана вище, згаданого jedster?
> 
> я б очікував змін принаймні в «сірих» кольорах, які мають бути кольорами ліній, відтворених фіолетовими на вашому екрані. ![графіка](https://private-user-images.githubusercontent.com/20392683/295528182-0df60e40-c2e5-4818-87ff-364abf02cb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODMzNjQsIm5iZiI6MTcwNDg4MzA2NCwicGF0aCI6Ii8yMDM5MjY4My8yOTU1MjgxODItMGRmNjBlNDAtYzJlNS00ODE4LTg3ZmYtMzY0YWJmMDJjYjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDM0ZjI3NTkzODA3NDdhYWIzYjI3NGJkM2FjYzExZTkwZjg2NDRhNTRlNzZiNzBiOGY2YWE1Y2QxYjlkZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJif5cIJHEFDjgRdK0yIn_znENE0Yk3HffTYanTsxD0)
> 
> коли я вибираю сірий колір у параметрі «колір підсвічування» (наприклад, 5-й зліва), він декодується 88;92;88, знову ж таки, «Нічого не змінилося»», отже, це те саме декодування на вашому екрані, і він сірий?
> 
> можливо, ви можете опублікувати тут свій скріншот

The problem is that no matter what color you choose, there is still a purple backlight. You can see this in the video I linked to.

**Comment by KardashIvan** [comment]
> > таємничий
> > "перевірте, якщо меню вибору кольорів (як на екрані знімка вище) буде показувати будь-які гібні кольори та додати про "гібні" кольори, можливо, можна побачити деякі систематичні помилки
> > 
> > * Нічого не змінилось"
> > 
> > що це означає ("нічого не змінилося")?? тож кольори з вибору кольорів не змінилися відповідно до (ОК) знімка екрана вище, зібраного jedster?
> > я б очікував зміни принаймні в «сірих» кольорах, які мають бути кольорами ліній, відтворених фіолетовими на вашому екрані.![графіка](https://private-user-images.githubusercontent.com/20392683/295528182-0df60e40-c2e5-4818-87ff-364abf02cb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODMzNjQsIm5iZiI6MTcwNDg4MzA2NCwicGF0aCI6Ii8yMDM5MjY4My8yOTU1MjgxODItMGRmNjBlNDAtYzJlNS00ODE4LTg3ZmYtMzY0YWJmMDJjYjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDM0ZjI3NTkzODA3NDdhYWIzYjI3NGJkM2FjYzExZTkwZjg2NDRhNTRlNzZiNzBiOGY2YWE1Y2QxYjlkZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJif5cIJHEFDjgRdK0yIn_znENE0Yk3HffTYanTsxD0)
> > коли я вибираю сірий колір у параметрі «колір підсвічування» (наприклад, 5-й злива), він декодується 88;92;88, знову ж таки, «Нічого не змінилося»», отже, це саме декодування на вашому екрані, і він сірий?
> > можливо, ви можете опублікувати тут свій скріншот
> 
> Проблема в тому, що який би колір ви не вибрали, підсвічування фіолетового кольору все одно залишається. Ви можете побачити це у відео, на яке я посилався.

Attached is a screenshot 
![Screenshot_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/322589fe-7689-46cb-9ecb-a2b5c41475d8)
Attached is a photo taken with my phone
![Foto](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/cc57f6c8-827a-4187-ac3e-0277523f6386)
I understand that the problem of the technical aspect((
What do you think I can do?

**Comment by KardashIvan** [comment]
> Після більш серйозного перегляду відео воно виглядає мені дуже дивним!

I take it this is a technical problem? What can I do about it?

**Comment by strgaltdel** [comment]
... if the tx is like new (and only a few months old) I would send it to the dealer as a warranty claim.
but wait:

looking at your photo and compare it with an identical color setting 112,112,112 i was wondering that my image was much darker:
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/d2ab1bb7-00bb-4579-beb7-381bd41c3289)


so i increased brightness and got
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/f1e2896d-cb19-4dd6-881d-55037c8cb85e)

**i would strongly recommend to reduce brightness below 50% and check if something changed**

i've the feeling that great brightness settings are causing "color overflows"
at least on the sim

**Comment by KardashIvan** [comment]
> ...якщо tx новий (і йому лише кілька місяців), я б відправив його дилеру як претензію по гарантії. але почекай:
> 
> дивлячись на вашу фотографію та порівнюючи її з ідентичним налаштуванням кольору 112,112,112 мені було цікаво, що моє зображення було набагато темнішим: ![графіка](https://private-user-images.githubusercontent.com/20392683/295598544-d2ab1bb7-00bb-4579-beb7-381bd41c3289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTgxNjAsIm5iZiI6MTcwNDg5Nzg2MCwicGF0aCI6Ii8yMDM5MjY4My8yOTU1OTg1NDQtZDJhYjFiYjctMDBiYi00NTc5LWJlYjctMzgxYmQ0MWMzMjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0NDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYzcwYWRlY2Q4NDExMDNhMmE3NGExOGU3MDEzNTQwMjJmOGRmZjY1NDkxNDdjNTdmNGE4MTEzZTllNDBlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5BURP9o0Bk7zSaKdyORnnmwRFVb1BZAlr96uEV7Rg64)
> 
> тому я збільшив яскравість і отримав ![графіка](https://private-user-images.githubusercontent.com/20392683/295598759-f1e2896d-cb19-4dd6-881d-55037c8cb85e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTgxNjAsIm5iZiI6MTcwNDg5Nzg2MCwicGF0aCI6Ii8yMDM5MjY4My8yOTU1OTg3NTktZjFlMjg5NmQtY2IxOS00ZGQ2LTg4MWQtNTUwMzdjOGNiODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0NDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MWZjM2Y4MDI4NWY3OWI2Y2Y5MjM2MmI3NTg3NzY0ZWEyZTJkM2EyM2NiYmVhZDE1MzEzZTdkMTRhMmIyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._K5wceo7rt1Suu9rfrrxLVlzgU0eh9jRRxc2o0cuAxg)
> 
> **Я настійно рекомендую зменшити яскравість нижче 50% і перевірити, чи щось змінилося**
> 
> У мене таке відчуття, що чудові налаштування яскравості спричиняють «перелив кольорів» принаймні на SIM-карті

Reducing the screen brightness did not help. The color remains unchanged. It is problematic for me to send it to a dealer( I am in Ukraine.

**Comment by strgaltdel** [comment]
hmm, sorry, was my last "guess",
but i'm only a user, maybe someone from FrSky has another idea, 
or it's worth to open a request in the "big" X20 thread on rcg 

https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-X20-Pro-Tandem-24-Channels-with-ETHOS/page1830

the only one idea i have is to built a "new system" from scatch by using a complete new, fresh sd-card
(guess your "working" on sd-card, right?

don't use any file from existing card.
never tested, but i guess you should be able to built a complete "new system" by using the Ethos suite when it detects an empty card.

**Comment by KardashIvan** [comment]
I'll try to use a new memory card, that's also my last thought. I tried to write to technical support but never got a response. The customer support is very bad.
I really miss not buying a Futaba or Jeti DS. I don't want to think about why my transmitter doesn't work, I want to make models...
I am very grateful for your help!

**Comment by KardashIvan** [comment]
> hmm, sorry, was my last "guess", but i'm only a user, maybe someone from FrSky has another idea, or it's worth to open a request in the "big" X20 thread on rcg
> 
> https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-X20-Pro-Tandem-24-Channels-with-ETHOS/page1830
> 
> the only one idea i have is to built a "new system" from scatch by using a complete new, fresh sd-card (guess your "working" on sd-card, right?
> 
> don't use any file from existing card. never tested, but i guess you should be able to built a complete "new system" by using the Ethos suite when it detects an empty card.

I'll try to use a new memory card, that's also my last thought. I tried to write to technical support but never got a response. The customer support is very bad.
I really miss not buying a Futaba or Jeti DS. I don't want to think about why my transmitter doesn't work, I want to make models...
I am very grateful for your help!

**Comment by KardashIvan** [comment]
Replacing the memory card and creating new files did not work.

**Comment by bsongis-frsky** [comment]
Would you show what is displayed in Radio / Information? Just to be sure you are using the right firmware on your X20S

**Comment by bsongis-frsky** [comment]
I wonder if there is a problem with the display connection (16 lines for the 16bits per pixel), it seems that some bits are missing, I wonder if some lines have been damaged.

**Comment by bsongis-frsky** [comment]
I would check the LCD connector to be sure there is nothing obvious.

**Comment by KardashIvan** [comment]
> Чи не могли б ви показати, що відображається в радіо/інформації? Просто переконайтеся, що ви використовуєте правильне мікропрограмне забезпечення на вашому X20S

Yes, of course! Adding information
![Знімок екрана 2024-01-10 о 21 46 43](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/1c96d872-3797-40ee-bee5-17259a2efdca)
![Знімок екрана 2024-01-10 о 21 44 34](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/df49152d-3e20-4ea4-97a2-518bdc74fb32)

**Comment by KardashIvan** [comment]
> Я б перевірив роз’єм РК-дисплея, щоб переконатися, що немає нічого очевидного.

The transmitter was not used in the field. It was constantly in the case and turned on 20 times. It has never been dropped anywhere. It is very strange for me to think that the cause is still in the display cable.

**Comment by KardashIvan** [comment]
> Мені цікаво, чи є проблема з підключенням дисплея (16 рядків для 16 біт на піксель), здається, що деякі біти відсутні, мені цікаво, чи деякі рядки були пошкоджені.

I don't want to disassemble the transmitter to avoid breaking it. This transmitter is not cheap. I have a helicopter model that costs $2,300. I don't want to lose the model and the transmitter if something goes wrong with it.
![IMG_8716](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/14ffe978-d951-4cb9-8e96-62ce313df408)

**Comment by bsongis-frsky** [comment]
After further investigation it seems obvious that it is a hardware issue. Maybe the LCD connector which is not correctly plugged. It's rather easy to check, but if you don't want to do it by yourself, you could ask to RCStudio to do it for you?

**Comment by KardashIvan** [comment]
> After further investigation it seems obvious that it is a hardware issue. Maybe the LCD connector which is not correctly plugged. It's rather easy to check, but if you don't want to do it by yourself, you could ask to RCStudio to do it for you?

Unfortunately, I do not have this opportunity. I am in Ukraine... There is nothing wrong with the supply, but there are problems with the shipment.

**Comment by bsongis** [comment]
Then I would contact RCStudio to get some assistance for opening the radio.
It's not that complex!
Otherwise wait for the end of that stupid war

**Comment by KardashIvan** [comment]
> Then I would contact RCStudio to get some assistance for opening the radio. It's not that complex! Otherwise wait for the end of that stupid war

Thank you very much for your help!
I will try to disassemble the transmitter to fix the display cable. 
I will have time on Saturday. After the repair, I will write the report of my work.

**Comment by strgaltdel** [comment]
a good video how to disassemble the X20
https://www.youtube.com/watch?v=M14r5qYM8yM


your work should be done until app 7:30, then you'll have access to the lcd cable:

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/326cbb13-1d4d-449e-b854-9fca8088cef1)

**Comment by KardashIvan** [comment]
> a good video how to disassemble the X20 https://www.youtube.com/watch?v=M14r5qYM8yM
> 
> your work should be done until app 7:30, then you'll have access to the lcd cable:
> 
> ![grafik](https://private-user-images.githubusercontent.com/20392683/295901377-326cbb13-1d4d-449e-b854-9fca8088cef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzQyNTcsIm5iZiI6MTcwNDk3Mzk1NywicGF0aCI6Ii8yMDM5MjY4My8yOTU5MDEzNzctMzI2Y2JiMTMtMWQ0ZC00NDllLWI4NTQtOWZjYTgwODhjZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDExNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzFiZDU0ZWYzZTNlYmI5ZmMwYzU5ZDJiZmI0YzY1NjA4ZjNiNWI4YzExZDNmOGYxZGJlZmI5NTJmODY2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3A_qyWriHkiDNhsf0N6Bi14iu2Rh9I9APXC__eGEtvE)

The display has four connection cables. I feel like I need to check all the connections to be sure that I have fixed it.

**Comment by KardashIvan** [comment]
Today I had some free time to find out the cause of the problem.
I have two pieces of news) One is good and the other is bad.
I managed to fix my transmitter and now the screen looks great.
![IMG_8737](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/81f52564-8e29-4aea-96fc-8139681447b1)
The problem was in this connection.
![IMG_8738](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/eec46fcd-e4b3-4589-b8e7-1e3c567481a0)
After completing the work, I fixed the connection of the antennas.
![IMG_8736](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/aa5d12d1-beda-42a0-95d0-fc45b4cde4a8)

**And now the second bad news. I was badly surprised by the quality of assembly at the factory.**
1. There were fingerprints on the boards. I was working in medical gloves.
![IMG_8740](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/34d5507a-c844-477f-b534-4e199d09afc1)
![IMG_8739](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/faf97042-9fa1-4bac-a055-f50d3efbbafc)
![IMG_8745](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/5bb87304-8613-4aa5-9660-9f839532c6af)
2. A piece of glue was found on the display board.
![IMG_8743](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/0bf3f2c4-9a79-4104-9274-9dc0778d2d6d)
3. Two fixing screws were missing.
![IMG_8742](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/0cd16331-8693-4a21-8a15-a0a725eb355f)
4. Remnants of unflushed flux were found on the boards.
![IMG_8744](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/cf2905d0-bd29-4f4f-86fa-280103cad56c)
5. Parts of solder were found on the display cable.
![IMG_8741](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/14314177/d95d8e7d-8dbb-421b-98de-862a415e49fd)

I am very upset with the purchase of this transmitter. And it all cost me 630 dollars. I had to repair everything myself and spend time on things that were not worth it.

**Comment by strgaltdel** [comment]
great that you were successful.

definitely doesn't look like the usual quality standard

I wonder if the radio has any kind of "history",

rcstudio, the Czech distri, where the system is from, is very serious & friendly.

what I would do:
I would ask him nicely, stating the serial number, if there is an explanation.
otherwise he may forward this to frsky

maybe also a link to the issue here

**Comment by KardashIvan** [comment]
Yes, of course, I will write to them. I wrote letters to the CM, but I didn't get a response.
I am buying the transmitter as a gift for myself for the New Year 2023. We are at war in our country, so flying large models is prohibited. I used the transmitter only a few times on the simulators. That's the whole story of it.
I am grateful for your support!
With your help, I was able to repair the transmitter.

**Comment by bsongis-frsky** [comment]
Issue fixed. Nothing on Ethos side, which is fine :)

**Comment by janekx** [comment]
Hello, i was noticed about this issue what happend, we are sorry that there was issue with the radio, but it is not common as we believe the customers will contact seller with the issue, but we not experience such issues. Usualy we help to learn or to update radio not issue with HW.

**Comment by janekx** [comment]
Hello, i was noticed about this issue, we are sorry that there was issue with the radio, but it is not common as we believe the customers will contact seller with the issue, but we not experience such issues. Usualy we help to learn system or to update radio not issue with HW.     
You can be 100% sure we sell only new radios what comes from Frsky. Before sell, we take radio out of the box, flash lattest ETHOS, calibrate sticks and pack back, we are sure radio is working. Only when we open radio is when customer ask for Mode1 then we change mode on gimbals but it is only main back cover open and switch screws on gimbals and we never and not need to disassemble radio more. This we do on every radio sold, customer is sure all is updated and he can start use radio right after delivery and not jump in to flash madness what are for some users stresfull mainly when comes to new ETHOS world. As well we are sure radio is working and without demage.

If you will need some assistence feel free to contact us.

**Comment by KardashIvan** [comment]
> Hello, i was noticed about this issue, we are sorry that there was issue with the radio, but it is not common as we believe the customers will contact seller with the issue, but we not experience such issues. Usualy we help to learn system or to update radio not issue with HW. You can be 100% sure we sell only new radios what comes from Frsky. Before sell, we take radio out of the box, flash lattest ETHOS, calibrate sticks and pack back, we are sure radio is working. Only when we open radio is when customer ask for Mode1 then we change mode on gimbals but it is only main back cover open and switch screws on gimbals and we never and not need to disassemble radio more. This we do on every radio sold, customer is sure all is updated and he can start use radio right after delivery and not jump in to flash madness what are for some users stresfull mainly when comes to new ETHOS world. As well we are sure radio is working and without demage.
> 
> If you will need some assistence feel free to contact us.

How can a new transmitter be of such poor quality? It's very disappointing for me.

**Comment by janekx** [comment]
Your radio is one year old, there can be some dust or small parts in. For design or construction you must contact FrSky.

**Comment by KardashIvan** [comment]
> Your radio is one year old, there can be some dust or small parts in. For design or construction you must contact FrSky.

It seems that the main thing is to sell the goods. No one is interested in further problems.

**Comment by KardashIvan** [comment]
> Hello, i was noticed about this issue, we are sorry that there was issue with the radio, but it is not common as we believe the customers will contact seller with the issue, but we not experience such issues. Usualy we help to learn system or to update radio not issue with HW. You can be 100% sure we sell only new radios what comes from Frsky. Before sell, we take radio out of the box, flash lattest ETHOS, calibrate sticks and pack back, we are sure radio is working. Only when we open radio is when customer ask for Mode1 then we change mode on gimbals but it is only main back cover open and switch screws on gimbals and we never and not need to disassemble radio more. This we do on every radio sold, customer is sure all is updated and he can start use radio right after delivery and not jump in to flash madness what are for some users stresfull mainly when comes to new ETHOS world. As well we are sure radio is working and without demage.
> 
> If you will need some assistence feel free to contact us.

So the store is not responsible for the quality of the products? Do I have to solve the issue with the factory myself?

**Comment by janekx** [comment]
I think you missundestand who is reponsible for what. You had some issue, why you didnt send radio for warranty repair? Or contact dealer for fix or help? You goes the way you try to fix radio self. OK now you have radio fixed. We keep warranty 2y in EU so each our customer can be sure we will fix the broken item,   
But you ask for quality and construction, we are not designers, we are not developers and we didnt mount the radio, radio was mounted in FrSky factory. 
To be clear we are for support and warranty, we report issues to factory and consult issues, but if you want to talk about the quality, construction, design or manufacture issue you must ask FrSky for statement.

**Comment by KardashIvan** [comment]
> I think you missundestand who is reponsible for what. You had some issue, why you didnt send radio for warranty repair? Or contact dealer for fix or help? You goes the way you try to fix radio self. OK now you have radio fixed. We keep warranty 2y in EU so each our customer can be sure we will fix the broken item, But you ask for quality and construction, we are not designers, we are not developers and we didnt mount the radio, radio was mounted in FrSky factory. To be clear we are for support and warranty, we report issues to factory and consult issues, but if you want to talk about the quality, construction, design or manufacture issue you must ask FrSky for statement.

I started repairing the radio myself because it would have been quite expensive to send it to you.
I would spend $200 to send it to you. This cost would include shipping and a tax on receipt of 20% of the value of the radio.
I sent letters to the FrSky factory, but I never received a response.
So I was left with the choice of repairing it myself and being upset about the quality of the assembly at the factory.
