### ISSUE TITLE
Request: Channel override Special Function

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#324]
I am on sim v1.02, correct me if this is already implemented in newer FW, I can not check myself until later this week.

I like to request a Channel **Override Special function**.
In OTX this was mandatory to some of my models to be absolutely sure some output states where in their right position.

**Comment by MIKE-DAILEY** [comment]
The override function is done is done with a Free Mix with ETHOS using the Function Type Replace.

**Comment by Hobby4life** [comment]
Thru but too complicated for such a simple function. makes the mixer page more messy.

**Comment by bsongis-frsky** [comment]
It's something which should be done in the mixer. How would you understand the mixer if something is done in a special function?

**Comment by i3dm** [comment]
i agree a simple override function needs to be added, perhaps in the mixer instead of "replace" make a simpler "override" function, with the difference being that override simply sends the channel to a constant user defined output value?
