### ISSUE TITLE
programmable button led lit up with power button for twin xlite s -1.4.16 

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#3240]
Hi,
this is reported in 1.4.15, that when clicking the power button 3 leds on the programmable buttons lit up. I was told to use the 14.16 bootloader to fix that. even after the latest 1.4.16 bootloader and 1.4.16 firmware I still see the second button led lits up during the start up.  Can you please fix that as well. Or make them lit like a timer in a sequence during the start up like a counter.

**Comment by bsongis-frsky** [comment]
Do you confirm that even in DFU mode you encounter the same issue?
If yes, I can do nothing, it's hardware

**Comment by kakashi2018** [comment]
@bsongis-frsky  by dfu mode, do you mean connect radio to pc while turned off and press power button and check if the programmable button led is lit?

**Comment by bsongis-frsky** [comment]
I mean you connect your radio to USB. At this moment, the 2nd led should turn on very quickly

**Comment by kakashi2018** [comment]
Yes, the led lits up connecting the usb with the radio turned off.

**Comment by bsongis-frsky** [comment]
Then it's hardware, I have done the best I can do on bootloader / firmware side
