### ISSUE TITLE
 system.registerSource can KILL model file

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3243]
if you use  system.registerSource({key="mysrc", name="mysrc"}) and select mysrc in "edit mode".
Then if you comment out the line system.registerSource.... It crashes the model file and after reboot of the sim or radio, it prompts "new model wizard"

**Comment by strgaltdel** [comment]
what if you activate the line again and restart the sim,
can you select the "old" model file ?
maybe it wont be available because the configured src script is not registered.

do you see any "hints" in case you start the sim in debug mode?

**Comment by bsongis-frsky** [comment]
Which is your firmware version? Normally it should not show "Invalid data", but your model should be loaded without the missing Lua source.

**Comment by bsongis-frsky** [comment]
Is it possible you try with a more recent version?

**Comment by noamkrief** [comment]
@bsongis-frsky 
absolutely. I'm happy to.
Can you send me a link to version you want me to try?

**Comment by bsongis-frsky** [comment]
You may flash it with Ethos Suite, you take the latest stable version which is 1.4.16 as of today.

**Comment by noamkrief** [comment]
@bsongis-frsky I'm sorry. How do I flash simulator.exe with Ethos Suite?
Can you send me a link to instructions or documentation?
Sorry again for not knowing.

**Comment by mawzthefinn** [comment]
With Simulator, you upgrade by downloading & installing the latest release, available here:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.4.15/X20S-Simulator.exe

**Comment by noamkrief** [comment]
@bsongis-frsky 
Latest version of simulator.exe does not have this issue. 
Also - the X20Pro does not have this issue either.
Thank you - closing ticket.
