### ISSUE TITLE
Aileron to flap mix: Basic mixer missing

### ISSUE THREAD

**Issue by ewikran** [FrSkyRC/ETHOS-Feedback-Community#3244]
I am trying to set up a F3X-plan and end in a snag. When trying to add the “aileron to flap” mix it reports an error message “Missing basic mixer”. Any other mix is added without any problems, but this one would not activate. Please refer to the added photos. Updated with ethos suite today to firmware 1.1.4.16 with no change in behaviour in relations to 1.1.4.xx and 1.1.4.15.

Can’t find any solutions and very few reports online and suspect it to be an error in Ethos.

![20240109_172341456_iOS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156121420/83ec0e8d-4592-4a1b-b691-e4b78f3a9154)
![20240109_172406000_iOS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156121420/81a0da36-0017-41da-bf33-f1c0e7c92f67)
![20240109_172417195_iOS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156121420/7373b43f-12c7-44f5-a7d7-30944acf3389)
![20240109_172430666_iOS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156121420/4f204c6c-d5f2-4e56-90bb-dd4a9c2b5c32)
![20240109_172634239_iOS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156121420/2972aaa9-f338-4ce5-8f11-eb4eb889e775)

**Comment by mawzthefinn** [comment]
You need to have a flaps mixer present for any mixer with 'flaps' in the name to create correctly.

That's because it configures based on the configuration of the flaps mixer (and also the ailerons mixer in the case of the Ail => flaps mixer)

**Comment by ewikran** [comment]
Yes, it works when adding the flap-mix. I do however struggle with the logic.

Activating the flap mix made it possible to activate the aileron to flap mix. However, the aileron to flap mix functions just fine after the flap mix has been deleted again. It seems just as a software hurdle that has no practical meaning.

I have also several other mixes that uses flap, as the crow and camber mix, and neither of them require the flap mix to be activated.

**Comment by mawzthefinn** [comment]
The limitation is on mix creation, the Ail=> Flaps mixer needs to know what the flap channels are when it provisions the mix. It learns those channels from the Flaps mixer. 

Once provisioned, you do not need the flaps mixer any more for the Ail=>flaps mix to work.
