### ISSUE TITLE
Translation Norwegian for 1.5.0

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#3246]
Hello.
Here are norwegian translation for Ethos system menus + updated AUDIO.csv list.
Looking forward to 1.5  :-)

[System menus from 1.5.0 Nightly.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13879891/System.menus.from.1.5.0.Nightly.zip)
[audio from 1.5.0 Nightly.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13879892/audio.from.1.5.0.Nightly.zip)

**Comment by bsongis-frsky** [comment]
The audio CSV file is OK
The translations CSV file has some issues, which I will fix:
- the encoding is not good, it should be UTF-8 (not Windows-1252)
- the translations keys should not be inside `"` (moreover the `,` was included inside the string, I wonder which editor does that!)

**Comment by bsongis-frsky** [comment]
Translation for VARS is "Var", no plural?

**Comment by bsongis-frsky** [comment]
The symbol `…` is not allowed, you have to use `...` (3 chars)

**Comment by bsongis-frsky** [comment]
I think this translation is wrong:
TEMPERATURE_UNIT,"Temperatur °C"
Because the value is °C / °F / ...

**Comment by bsongis-frsky** [comment]
Pushed for next nightlies
