### ISSUE TITLE
A Cloned Throttle mixer give different channel output with 9/1/24 nightly

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3249]
I'm afraid I can't see how to reopen #3224 (or possibly don't have authority) however I have just upgraded my tx with the latest nightly and the problem remains. 

Here is a link to a video showing what I am seeing https://www.dropbox.com/s/6crfygw9qdj68ob/VID_20240110_103953.mp4?dl=0
you can see how the channel output is different for ch14 and ch15 despite ch15 being a clone of ch14 and as I best I can understand the ch15 output is the correct output but I can't see why ch14 is behaving as it is. Hopefully you can see a difference in the two mixer definitions which may give a clue. I may be able to explain / recreate if I know what the difference is as I can remember some of the things I did in setting up this model which may be relevant. 
I could just delete ch14 and use ch15 but that makes me nervous if there is a bug which hasn't been identified and fixed and which may cause me trouble later on.

Please see the attached model
[odd prob 1.5rc0.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/13849167/odd.prob.1.5rc0.zip) which was created using 1.5 RC0.
Now go into Edit on the Throttle Mix and look at Output1
I noticed that as I move the Throttle Stick (left stick) throughout its range that the Channel % did not follow the Mixer % which I couldn't understand.
I therefore Cloned the Throttle Mix and changed the Output channel to 15 in the cloned mixer with a view to experimenting with this new mixer to understand what was happening.
Now go to the second page of Outputs so you can view Ch14 and Ch15 and move the throttle stick throughout its range and you will notice that the Channel % does not behave consistently for ch14/15.
At this point I simplified my original model (deleting lots of mixes, deleting the landing FM, removing Throttle Triggers and changing VARs to Value etc.) to try and pin down the problem and the above model is a copy of that slimmed down model.

I believe that Ch15 behaves correctly but can not explain Ch14 behaviour.
For both channels the Curve has a dead band from -100 to -50 so as you increase the throttle stick nothing happens at first, when you reach -50 on the throttle stick the mixer starts to increase, however it is not until you increase the throttle stick to around -25 that the output starts to increase. I notice that -25 on the throttle stick also corresponds to -50 on the mixer so it feels like the output is applying the curve to the mixer rather than the throttle stick. But that wouldn't explain why the cloned mixer appears to work as expected.

Thanks

**Comment by Jedsters** [comment]
Not sure if I was too quick off the mark? My Firmware shows with a date of Jan 4 2024.

**Comment by mawzthefinn** [comment]
This is a programming error, not an ETHOS issue.. You have the same curve assigned on the Output for Ch14 as on the Throttle mixer. That means you are running the inputs through the curve twice, once with the stick output and again with the mixer output.

Removing the curve from the Ch14 Output results in correct behaviour.

**Comment by Jedsters** [comment]
Many thanks and apologies Mawz.
What's annoying is that the Throttle was originally on Ch9 when I had the problem so I moved it to Ch14 in case there were any odd setting on Ch9 - I must have specified to copy channel settings across too!
My bad.
