### ISSUE TITLE
Bluetooth telemetry reverts to off after power off in version 1.5

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#3251]
In the version 1.5 nightlies the bluetooth telemetry always reverts to off after a power cycle of the unit.  Please give a persistent option to have this always on as it makes it difficult to use ground stations having to constantly change the setting every time a model is selected or the unit is powered off.

**Comment by bsongis-frsky** [comment]
Ready for RC1
