### ISSUE TITLE
1.5 RC0 XE (FCC) Trims not showing correctly on Ailerons and Rudders

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#3252]
Not a big deal, but when using mixes Ailerons or Rudders the graph on the right side does not change but the Outputs do when adjusting the trims.  However when using Elevators and Throttle the graph and Outputs both show the changes. On 1.4.15, Ailerons, Rudders, Elevators and Throttle all display correctly.
Thanks

**Using a generic model plane for this example, trims are at 0:**
![screenshot-2024-01-10-73184](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/8307cf8b-6cf0-4dc1-a9a5-d8fe8042ee3b)

**With full trims:**
![screenshot-2024-01-10-73198](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/35b3924d-c75d-440e-b741-9496acb5eab4)

**Elevators example with full trim:**
![screenshot-2024-01-10-74767](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/92a2927e-963f-4a61-abba-7ca256122e64)

**Comment by bsongis-frsky** [comment]
Ready for RC1
