### ISSUE TITLE
enhancement - lua read/write text files

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3253]
Please add the ability to read/write text files to lua.

**Comment by bsongis-frsky** [comment]
What do you mean:
- Read / write text files from a Lua script?
- View the Lua files from the File Manager?

**Comment by dwheeld** [comment]
Read / write text files from a Lua script

**Comment by bsongis-frsky** [comment]
It works out of the box!

```lua
local file = io.open("main.lua", "r")
while true do
      line = file:read("*line")
      if not line then break end
      print(line)
end
file:close()
```

**Comment by dwheeld** [comment]
Thanks for the example.
