### ISSUE TITLE
Hide files whose names begin with ._

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#3254]
Can these be hidden in UI selection? 

These are hidden files that are created by MacOS and just add a lot of clutter, particularly in the audio files. They should not ve visible/selectable anywhere other than File Manager (and hiding there would be fine too)

**Comment by packetpilot** [comment]
This would be easily sated in the build pipeline, but it's hard to tell whether one exists or not. If it does, it's certainly not in this repo, sadly. If it did, I'd love to "jaml" on that yaml.
