### ISSUE TITLE
1.5 RC0 XE (FCC) Ailerons mixer allows for differential input with only one channel.

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#3255]
I'm not sure if this is intended to operate this way.  In previous versions with only 1 channel count (in Ailerons), the Differential field was not active.
Thanks

**I'm using a generic model for this example with 0% Differential and 1 channel count:**
![screenshot-2024-01-11-37247](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/f7839db9-1428-4dee-bfc7-59b2ff085fef)

**Changing the Differential amount to 50% and there is no change:**
![screenshot-2024-01-11-37262](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/04740a9f-fc19-438a-acbb-db8b88873132)

**Changing the channel count to 2 and now Differential is working:**
![screenshot-2024-01-11-37272](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/81670152/a9e104b0-bfe0-4d18-bb05-e80b27120a17)

**Comment by bsongis-frsky** [comment]
Ready for RC1
