### ISSUE TITLE
In 1.5 only getting 10% movement in flaps

### ISSUE THREAD

**Issue by LanceGebert** [FrSkyRC/ETHOS-Feedback-Community#3257]
Set up new plane in 1.5 with 2 flaps. Went to mixer and changed default 30% to 100%, Assigned flaps to switch A. Only getting 10% movement each side of 0.

**Comment by bsongis-frsky** [comment]
I think this one is fixed in latest nightlies, would you double check?

**Comment by LanceGebert** [comment]
Sorry not sure were to look in nightly. But i just put 1.5 on tx yesterday morning.

**Comment by strgaltdel** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/nightly15


(..enter the release section and scroll down until nightly assets are available)

**Comment by mgsanna** [comment]
I confirm that it is fixed with the last nightly of tomorrow (4-5 hours ago)

**Comment by LanceGebert** [comment]
Thank You sir!
