### ISSUE TITLE
TD-SR18 servo output limited to 2012 us, change in Ethos does not affect servo output

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#3258]
I was helping a friend to convert his last plane from Multiplex to FrSky. 

In this plane there is a light system which needs specified servo deflection to switch the lights on and off.

He has the same light system in another plane with a TD-R18 which works perfectly.

The problem is that the max servo output is limited to 2012 us somehow. So even if i change output in Ethos above 100%, I can see the bar going above 100% but the servo output does not change.

I confirmed that on another channel and with a servo. The servo dies not move when I set max output above 100% (tested up until 150%).

It works on other receivers and on servo testers, just not on the TD-R18 receiver.

I hope someone can help.

P.S.: Is it possible that the TD receivers with gyro are limited?

**Comment by mawzthefinn** [comment]
You need to do the self-check to re-learn the endpoints when using a Gyro equipped receiver like a TD SR18

The Stabilized receivers learn endpoints and prevent anything from exceeding the learned endpoints.

**Comment by Wolepo** [comment]
Even the exits that are not affected by the roundabout? That can't be the case.

**Comment by mawzthefinn** [comment]
Yes, that is the case if the stabilizer is active. This is how all the FrSky stabilizers work.

You can easily test, disable the Stabilizer function in the SRx Stab lua and it will not limit endpoints.

**Comment by bsongis-frsky** [comment]
User error?

**Comment by keiner0815** [comment]
I can try it today after work and will report.

**Comment by keiner0815** [comment]
You were right, after extending the servo throw to 125% and performing the self check, it did work and the output was at 125%.

So I will close this issue.
