### ISSUE TITLE
Show a table of Model-ID and there Models

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#326]
it would be nice if there is a table that shows which model is attched to every Model-ID

**Comment by centertrim** [comment]
Agreed.  Maybe have a button in the model select window that opens the Model ID list showing the associated models for each Model ID?

Bonus points if you can select and activate a model from this new Model ID table!

**Comment by jreis1** [comment]
I've suggested this a while ago in OpenTX as I believe is a very important feature.  This way, we can see which model ID is being used /paired and which ones are still free to get a new bind :)
 
+1

**Comment by jreis1** [comment]
In addition to this request, It would be nice to have the receiver ID listed in the main model selection screen as highlighted in the picture. 

![8755DBF6-4FA5-4133-A1AB-D65576397265](https://user-images.githubusercontent.com/25162166/119728812-cae95700-be6b-11eb-9c57-64c3cf3330bb.jpeg)

**Comment by bsongis-frsky** [comment]
Request of @jreis1 done in 1.0.8, as it was the easiest

**Comment by bsongis-frsky** [comment]
Only the models written by releases 1.0.8 and later will have their modelId displayed (because this information is missing in the file header for models written before)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/119829819-f2880000-befb-11eb-9ee1-e38b50130602.png)

**Comment by jreis1** [comment]
You rock guys :) thanks

**Comment by mawzthefinn** [comment]
Just touching this to reset stale counter, would be awesome to get a list of all used model ID's and associated models
