### ISSUE TITLE
Version 1.5 RC1 breaks lua script using form.beginExpansionPanel

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#3260]
Ethos 1.5 (with the new form.addExpansionPanel) breaks existing lua scripts that use beginExpansionPanel, please keep legacy api calls so ask to maintain existing lua scripts.

**Comment by bsongis-frsky** [comment]
There are not a lot of differences in the Lua API between 1.4 and 1.5 but here the way forms are created / used has been changed and your script will need some small adaptations.

I will check the demo widget from 1.5 nightlies later today.

**Comment by bsongis-frsky** [comment]
Fixed for next nightlies

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/eb943ed8-8964-4207-82d6-63e1432b312b)
