### ISSUE TITLE
1.5 RC0 XE (FCC) Tone in the audio

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#3261]
When tracks play there is a tone in the background that you can hear quite clearly.  I'm hearing this on the stock .wav files along with all of my custom audio files.  In previous XE versions there is no background tone during the playback.  I have checked for this on my X20S and the tones are not there.  It's something like an audio test tone, say around 1khz.  You can still hear the track play.  As soon as the track ends the tone stops also.  It's not super important, just annoying.
Thanks

**Comment by bsongis-frsky** [comment]
Are you sure you don't hear the RF? Do you hear the same noise during beeps?

**Comment by df7320** [comment]
The RF state is "Off".  I do hear the noise with the trim beeps.

**Comment by bsongis-frsky** [comment]
I think it's the backlight. I revert it to the original value in 1.4.17
