### ISSUE TITLE
"inactivity for long time" => "Prolonged inactivity"

### ISSUE THREAD

**Issue by packetpilot** [FrSkyRC/ETHOS-Feedback-Community#3264]
lol, _seriously_?

Can the pre-baked TTS get some sort of cleanup? If this repo were an actual repo, I'd do it myself, but...

**Comment by bsongis-frsky** [comment]
What is the problem?
The TTS text for all Ethos prompts are included in this repository. You have to follow the wiki.

**Comment by mawzthefinn** [comment]
It's not a proper english phrase. In fact it's a stereotypical 'Chinglish' sentence.

'Inactivity Alert' or 'Inactive for a long time' would be more correct.

**Comment by packetpilot** [comment]
I get more than my fair share of Chinglish from my wife, so I do apologize if I hear so much of it that I'm incorrectly attributing that label to this phraseology, which is poor irrespective of which flavor of distortion lens the meaning passes through.

Perhaps my standards need adjusting for a handheld radio's equivalent to what are CAS messages in manned aviation (cabin alert system). Concision is paramount: deliver the point in the fewest number of syllables.

Perhaps I'll fork this and make some tweaks, hopefully not to have a PR declined, but imho "prolonged inactivity" is the "correct" amount of syllables for this message -- I'm still undecided on whether it's the "right" phrase in my mind.

**Comment by mawzthefinn** [comment]
Prolonged Inactivity is a good phrase, I like that.

**Comment by bsongis-frsky** [comment]
It cannot be chinglish as I know only about 2 chinese words ;)
I am OK with "Prolonged inactivity", the first post of this issue "lol, seriously" doesn't help to improve my english ;)
Now perhaps we could continue in french so that I can laugh myself?

**Comment by bsongis-frsky** [comment]
Ready for 1.4.17 and next 1.5.0 nightlies
