### ISSUE TITLE
Repo description needs work from a repo owner

### ISSUE THREAD

**Issue by packetpilot** [FrSkyRC/ETHOS-Feedback-Community#3266]
(or maybe editor depending on how you have it configured -- been a while since I did corp github admin)

what is presently this:
>Feedbacks & suggestion are very appreciated on ETHOS of FrSky

...ought* to be this
>Feedback & suggestions are welcomed here for ETHOS by FrSky

Such a change might help people take FrSky a bit more seriously.

*I use the word "ought" loosely here because I'm rather certain that a close read of GitHub's acceptable use policy would indicate this is a misuse of the platform. It's not a platform for crowdsourcing feedback & suggestions, but for open source development. I know you folks do know what that actually is! 😄

**Comment by mawzthefinn** [comment]
I would suggest reviewing the AUP and Terms of Service.

There is exactly zero Open Source requirement, it's simply a collaborative platform for development work. It supports Open Source development, but projects are in no way, shape or form required to be Open Source. 

Note Github is owned and operated by the best known closed source development company on the planet, Microsoft.

**Comment by bsongis-frsky** [comment]
@packetpilot FYI FrSky pays github for his repository, including a plan for running the non regression tests ...

**Comment by bsongis-frsky** [comment]
Description modified

**Comment by packetpilot** [comment]
> collaborative platform for development work

The limited view this repo affords doesn't seem to offer much room for actual/substantive "collaborative development work": [QED](https://github.com/FrSkyRC/ETHOS-Feedback-Community/pulls?q=is%3Apr)

You are correct though, I should've said "It's not a platform for crowdsourcing feedback & suggestions, but for collaborative development."

I'd sincerely love to roll up my sleeves and do some actual _development work on_ things I notice and could potentially sort out myself and submit through a PR. It seems the opportunity to do this is severely restricted, but perhaps I'm missing something.

Should it _not_ be possible to do so in the foreseeable future, I'd love to understand where I can look for the (presumably embedded) code such that I can do the work to port the absolutely perfect & sane LCD backlight behavior of ETHOS over to edgeTX, as this shortcoming of edgeTX/OTX is precisely why I'm backed into an ETHOS corner in order to use my X10S without sensory issues.

**Comment by mawzthefinn** [comment]
You're mistaking 'collaborative platform for development work' and 'collaborative platform for open source development work'. 

ETHOS is not an Open Source OS. Github is not an Open Source-only platform.  

The code repo for ETHOS's source code is not publicly available and will not be, the publicly available portion of the repo is for the freely provided example scripts (Lua), Documentation and user bug/enhancement reporting and interaction.

**Comment by bsongis-frsky** [comment]
The  LCD backlight behaviour of ETHOS? Hm. Ok :) 
There are some other differences which are more complex to port! 
https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/1.5/doc/Comparison%20Ethos%20OpenTX.pdf

**Comment by packetpilot** [comment]
I'm a corner-case for sure but truly the proper handling of the backlight
is the sole reason I'm using ethos on this radio at present. ETX doesn't
dim nearly low enough, and afaict it also can't put the display to a 0lux
sleep state either.

I'd imagine the code at play in ethos to drive the backlight is probably
not too different from vendor-provided code examples (bitbake if I'm
lucky), but I wouldn't enjoy gutting the radio just to but a scope (micro,
maybe oscilo too for giggles) up to the panel assembly's butt, especially
if that'd involve desoldering it from the assy board.

I think the better solve for me might just be an inline resistor on the
Vsupply wire for the display board -- a good reason to dust off my 60s-era
decade resistor.

**Comment by packetpilot** [comment]
epilogue: I sorted it out on the etx side of things with a [tiny edit](https://github.com/EdgeTX/edgetx/pull/4539/files).

Sorry to've been a pain in your butt! Sometimes it's only after it's over that I realize sensory disturbances (and trying to solve issues that cause them) can turn me into a bit of a pain.

**Comment by packetpilot** [comment]
> You're mistaking 'collaborative platform for development work' and 'collaborative platform for open source development work'.

What makes a person a developer? Surely it's not just reporting issues.

If I drive up to a fast foot drive-through window and order a hamburger, and five minutes later have a hamburger in my hand, did I participate in collaborative cooking?

I'm a thick-headed moron admittedly, so there's likely something I'm actually missing, but this repo does not seem to involve collaboration any more than the drive-through windows at fast food restaurants. That said, I'm sure there's heaps of actual collaborative dev work in the private repos.

I'll take my ball and go play somewhere else now, but should ask one more question first, likely in a discussion & not here.

**Comment by bsongis-frsky** [comment]
1) many issues in this repo help us for tracking bugs, improving the software design, bringing new UI sketches, etc. and that's definitely collaborative work!

2) `MIN=1` is good on X10Express. Good luck on EdgeTX :)
