### ISSUE TITLE
enhancement - add method to stop updates from overwriting custom audio files

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3268]
It is a simple matter to replace any system audio prompt to whatever you desire. The only problem is that when an update is performed, all of your replacements are overwritten by the canned versions. It would be nice if there was a way to mark these files so that they would not be overwritten during future updates.

**Comment by mawzthefinn** [comment]
This should be solved in 1.5 via the multi voice feature

Set your main voice folder to one named something other than a default pack, it won't get updated.

**Comment by bsongis-frsky** [comment]
True! 
This feature hasn't been introduced for that reason, but it does the job!

**Comment by dwheeld** [comment]
That is, indeed, great to know. :) Thank you!
