### ISSUE TITLE
macOS Ethos Suite build artifact is incorrectly named

### ISSUE THREAD

**Issue by packetpilot** [FrSkyRC/ETHOS-Feedback-Community#3269]
It's been a while since Apple referred to their OS as OS X. The suggestion would be to replace the characters for this arifact from `OSX` to `macOS` per Apple's own (case-sensitive) standard -- no space, no capital M.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1474054/0691eefd-b171-4e2b-aa37-21e5273f32af)

**Comment by bsongis-frsky** [comment]
It shouldn't break the automatic updates though!

**Comment by packetpilot** [comment]
> It shouldn't break the automatic updates though!

💯 ... and hopefully wouldn't involve any duplicate artifacts as a transitional band-aid -- perhaps symlinks would be a more appealing band-aid but still far from an elegant approach. Hard to tell without insights into the yaml for the builds (which could conceivably be less hidden away without also unhiding actual source code).
