### ISSUE TITLE
V1.5.0 Test freemix Range setting at Simulator X20

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3272]
V1.5.0. nightly simulator X20
free mixer, testing range setting to 125% or 150%

But
at freemix range setting only 100% possible to set
and range at mixer is set to 500%

![2024-01-13_171957](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/1224cae8-8b29-4670-a982-a5445586acce)

![2024-01-13_172037](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/56afd05d-f9eb-4d9f-a2aa-d959716161c7)

**Comment by bsongis-frsky** [comment]
Right. It's the same issue than #3298 which is ready for RC1

@hrenz I cannot find the issue you opened with Flight Modes and Trim values. But it is ready in the nightlies which have been uploaded this morning, I will appreciate your test&review!
