### ISSUE TITLE
1.5 Nightly Missing Basic Mix Ali=>Flaps

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3274]
I've just done a Write All Components for 1.5 using the latest nightly however when I try to add an Ail=>Flaps mix I get Missing Basic Mix error.
Not sure if this could be a problem with my tx which I have done a lot of testing of 1.5 with but I assume that the Write All Components should fix that.
But see #3275 
Thanks

**Comment by mawzthefinn** [comment]
You are either missing a flaps mixer or an ailerons mixer (or both). The Ail=>Flaps mixer requires a mixer of each of those types to exist in order for it to create.

Free mixes of the same name do not replace the canned mixers for this.

**Comment by Jedsters** [comment]
Thanks, of course you are right, I've been playing around too much! Although perhaps the message could give a little more assistance?
Thanks
