### ISSUE TITLE
Question re Mixes 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3275]
I notice that in 1.5 there are a number of almost identical mixes and question whether they are actually necessary or would be better simplified? 
It appears that all the x => y mixes are essentially the same. Sure, they all have a predefined output and some also have a predefined input while others have selectable input, but aside that are they the same? 
Would they be better and possibly allow more flexibility if there was instead a single Source=>Output mix which had
Name, Active Condition, FM, Input, Curves, Channels count, Weight, Output

(updated to correct mistake, now Source=>Output)

Just a thought.

**Comment by Jedsters** [comment]
Example: I could suggest that we are missing a Gain Mix for stab rx, however in reality this is just another variant of a Source=>Output mix

**Comment by mawzthefinn** [comment]
These mixes exist for users who want more traditional canned mixer functionality. Several are exactly the same mix with different names (Airbrake and Offset for example are completely identical), for users who just want to select mixes by desired functionality. 

The single Source=>output mix already exists, it's called a Free Mix.
