### ISSUE TITLE
1.5 Using Wizard with self stab rx can create meaningless Action for FM and missing FM

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3276]
To recreate:
Use the Wizrd to create a Glider, select a self-stab rx, e.g. S8R, select defaults up to the Assign input sources page.
For FM1, select the respective line and move e.g SA Up
For FM2, select the respective line and move e.g. SA middle
For emergency select the respective line and move SA Down.

However you can see that in each case they are simply selected with SA with no indication of the position of the switch. 
Surely switch positions should be honoured?

Also, if you then touch and hold the respective lines you have the negative option which will then display as -SA although it's not clear what this means.

Moving SA into the various positions I'd then expect either FM1, 2 or Emergency lines to highlight, but this doesn't happen suggesting that SA does in fact mean nothing.

Again, looking at the mixes, we can see FM1, FM2 and Emergency each with SA (or -SA) but moving the SA switch doesn't actually select any of them.

I would also then expect to see under Flight Modes 4 FM, however I only see FM0 Default so the extra FM specified in the wizard are in any case ignored. 

Tested at 1.5 10Dec24 Nightly.

Thanks

**Comment by mawzthefinn** [comment]
FM1 is FM on channel 10, FM2 is FM on channel 11, Emergency is the Panic function on ch12.

The wizard assigns correctly, flight modes are selected by a 3 pos on ch10 and a 3-pos on ch11. check the Flight mode tables in the receiver manual for more details.

Note that Quick mode only needs FM1/ch10 assigned a switch

**Comment by Jedsters** [comment]
Thanks for the clarification Maws. 
I do however feel that the Wizard is confusing as one naturally assumes Ethos FM, however it's difficult as I notice the SxR instructions refer to flight modes which isn't ideal. To me they are perhaps Rx Modes or Rx FM - but you can't stray far from what the instructions say otherwise that in itself becomes confusing. 
I struggle to think how this could be improved to enhance clarity, while being consistent with the instructions, as to what is going on.

Some random thoughts:

Flight Modes1/2  (note the plural)
Rx Flight Mode 1/2
Flight Modes Ch10/11  
Stab Flight Modes 1/2

Obviously this would apply to the Mixes too.

Emergency seems fair enough although I notice the SxR instructions use the word Urgent.

As for the switch positions not being honoured I can see why. Maybe the above random thoughts should have 'Switch' after them to clarify that it is being done at a Switch level rather than a switch position level which FM are typically done at. This could avoid any given switch being incorrectly overloaded.

Thanks
