### ISSUE TITLE
1.5.0 Fehler im logischen Schalter A < X und A > X Funktion

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3279]
1.5.0 Fehler im logischen Schalter A < X und A > X Funktion

Bei Wert X ist keine Eingabe größer 10.24 möglich.

Sensor: Spannung Bereich 0.00 - 52.00 Volt

Zusammenfassung des logischen Schalters ist auch falsch.

Grüße Eugen

![IMG_6287](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/9639026a-0028-4bd9-b319-d3d5c0ff5e02)

![IMG_6283](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/084cc961-f14a-4d63-a02c-881bca64ed6b)

![IMG_6288](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/3e7f7176-2621-44fa-88d1-a338fa723e00)

![IMG_6281](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/5376488c-6661-405e-a449-78ae05d94c68)

![IMG_6284](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/96a166dc-45e4-4943-b465-3d99a77033e3)

**Comment by bsongis-frsky** [comment]
In english?

**Comment by Dsrenger** [comment]
Just your friendly translation machine :)  (meaning, i just have some time and understand german, so I thought i translate it...did not test anything, just translated)

1.5.0 Error in logic switch A<X and A>X function

Value X doesnt allow values bigger than 10.24

Sensor: Voltage range 0.00 - 52.00 Volt

Summary of logical switch is wrong too

**Comment by strgaltdel** [comment]
yepp,
his main issue is, values in "a<x" and "a>x" functions can't exceed a value greater then 10.24,
even in case telemetry range is much higher

second issue / last picture:
the "summary"  aka "Bedingungen" column is wrong:

value was entered as x < 10.24V, but display says x< 42.00 Volt

**Comment by yak55** [comment]
Sorry, Google has translated my text into German. Greetings Eugen

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8115c3e8-0655-4e79-bc7e-544bb9cec6f1)

**Comment by bsongis-frsky** [comment]
From 1.5.0, pressing "Default" here will select the current sensor value instead of "0.00V"
