### ISSUE TITLE
Add source option to predefined Rudder mix (similar at Throttle)

### ISSUE THREAD

**Issue by IJK-CZ** [FrSkyRC/ETHOS-Feedback-Community#328]
This idea was alreany mentioned in #27  . For simple models without aleirons, the AIL sticker is used to control rudder. OpenTX as well as FrOs had an option to define INPUTS (sources) for model functions. Therefore one model had source for Rudder J1, other model J3 and all worked fine.
Ethos omitted the INPUTS from settings. It would be fine, in case we could change source directly in mixes. But it is now possible only in Throttle mix. The same thing should be possible at least in Rudder mix.

**Comment by mawzthefinn** [comment]
Set the output of the Aileron mixer to the rudder channel, rename the mixer as Rudder.

You can consider the stock Aileron, Rudder and Elevator mixers as Inputs with mixing capability.
