### ISSUE TITLE
issue flaps

### ISSUE THREAD

**Issue by neew1** [FrSkyRC/ETHOS-Feedback-Community#3281]
Hy 

if I create a model with flaps and assign a switch to them (channel 6,7), e.g. SC is the displayed path +/- 10% of the servo travel. if I program the flaps afterwards and select the mix flaps, it's the same. Only if I select a free mix and then switch the channels (6/7) with the SC switch, the travel goes from -100 to +100%. Why is this? 

greetings

**Comment by LanceGebert** [comment]
I had same issue. Was told this was fixed in a nightly a few days ago.

**Comment by bsongis-frsky** [comment]
Fixed already

**Comment by neew1** [comment]
Ok, Thanks for information.
