### ISSUE TITLE
1.5.n: Audio sequence in Special Functions does not always play to the end

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3282]
It's my understanding that, once triggered, a sequence should always be completely played.

What we have now is:
in case the next audio modul should be played, but the SF got deactivated interims, the next part is not started.
This results in played fragments.

Example:
we have a rx- voltage shortfall for 7 seconds, this should trigger a acoustic warning
(typically we have some "noise" on the voltage line, so you have to deal with the circumstand that voltage will can "come back" a little bit in case battery gets low) 
even with some defined delay, lets say 4 seconds in order to suppress false flags, an lsw will get active and triggers the LSW to announce a warning.

Now we have audio sequencing and users can "assemble" warnings from multiple elements
Example:

![issue_sequence](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/a121f94b-54d2-4136-bce3-ed33586357b3)

If the voltage drop disappears while the "chime" is playing, the warning file "Rx_Bat" will not play/start.

I guess that most user scenarios need to play the complete sequence as soon as it is triggered

regards

**Comment by Wolepo** [comment]
Yes, I criticised this behaviour a long time ago.

**Comment by Jedsters** [comment]
Please see #2852 in particular the last comment

'Surely the sensible option here is to add another Action of Check Trigger, so those who don't want the entire sequence played  can control how much is played, otherwise the entire sequence is played?'

**Comment by strgaltdel** [comment]
I am a friend of the Pareto principle

I am sure that more than 80% of users want to hear the complete sequence due to a short trigger (e.g. LSW).

For reasons of user-friendliness, I think it would be good if it would be implemented in this way.

Some users would probably not think so far as to assign a (individual) "duration time" to the trigger LSW.
In some cases, they might not even want to.

The solution presented should therefore satisfy the vast majority of users.

If there really are special cases, an ad hoc "stop" could still be customized via a "persistence switch" option,  if necessary  
This should be decided by bertrand, or you wait for user requests after RC0 to see if it is necessary

**Comment by strgaltdel** [comment]
apart from that:

1.5 is a huge step in many areas with many new possibilities
(imho more a version 2.0)

this release will cover most of the enhancement requests of the last 2 years, many users will need some time to learn the new possibilities and implement them in existing templates.

I don't think it is necessary to include all the small additional features that came to mind after working with 1.5RC0 or nightlies in the first release.
It is more important to invest resources in known bug fixes.
If you want to implement all these additional ideas resulting from the working RC0 / the nightlies immediatly, we may not see a release until 2025...

I think it would be good to focus on a foreseeable release date first, and not want to implement all the little things immediately
(I'm already taking a step back with wishes and ideas, but I don't always succeed) 

It might also be a good idea to start with a "user commodity" initiative after the release,
getting mor response from the field, and then focus on making the new possibilities easier to use instead of adding even more features.

**Comment by Jedsters** [comment]
I agree that most users will expect to hear an entire sequence and that will satisfy my needs. 
However, I do recognise that sometimes a change is easier to be included while you are working in an area of code than to come back to it later so include the suggestion in case it is a quick win now which may save more effort later on. I also recognise that the current implementation of only playing files / values so long as the trigger remains true may have been done due to some request or reason which I'm unaware of, not least as Bertrand mentioned in #2852 that he thought that the playing should stop when the trigger stops, no doubt for good reason, so my suggestion was to give both camps what they felt appropriate.
The Devs are of course best placed to decide what should be included with 1.5.0, what can wait until 1.5.1 etc..
