### ISSUE TITLE
TD SR10 Options not working and won't calibrate

### ISSUE THREAD

**Issue by RogerRamjet21** [FrSkyRC/ETHOS-Feedback-Community#3285]
Just received new TD SR10. If RF/SET/OPTIONS the only thing you can assign a pin to is a channel. SBUS/FBUS/SPORT do not show as options.

Also, I installed the newest SRx scripts (base, cali, stab) and the receiver will not calibrate.
I have a TD SR12 receiver and all this works fine.

**Comment by bsongis-frsky** [comment]
It's already fixed in 1.4.17 pre-release
