### ISSUE TITLE
ISRM 2.2.6 breaks voltage sensor function.

### ISSUE THREAD

**Issue by RogerRamjet21** [FrSkyRC/ETHOS-Feedback-Community#3286]
I updated the ISRM from 2.2.4 to 2.26 in my X18S.

When I fired up my RV8 airplane with TD R10 and a voltage sensor on the SPORT (port 12 configured for SPORT), the voltage sensor showed all 6 cells at 3.8 storage value which is correct. The Transmitter however showed 3.8 for some, 0 for some and 0 for overall. Also, the transmitter kept saying sensor lost.

I deleted sensor data and rediscovered, but this did not change the symptoms described above.

I reverted to ISRM 2.2.4 and everything works properly again.

**Comment by mawzthefinn** [comment]
Did you also update the receiver to 1.0.11? The updates are paired and telemetry is flaky if only one side is updated.

**Comment by RogerRamjet21** [comment]
Thanks Mawz, that was it. Sorry I didn't think of that. This can be closed.
