### ISSUE TITLE
TIMER Log

### ISSUE THREAD

**Issue by xSuperflyx** [FrSkyRC/ETHOS-Feedback-Community#329]
I am using the X20S for F3K, it is important to record flight times as there are several target times to achieve during each round of competition.  I have set up the spring loaded switch to launch and also reset the flight timer to zero, I can clearly see the actual time of my flight, what I need is a log of flight timer times.  Once the spring loaded switch is pulled to launch and reset the flight timer it would also record the previous flight time upto that point it had been reset.
It would also be good to reset the log of flight time so to start again, the preference would be to see a log of 10 or more flight times before they start to rewrite or reset.

**Comment by bsongis-frsky** [comment]
I understand you need a "Write Logs" (ON / OFF) parameter for each timer?

**Comment by xSuperflyx** [comment]
For the 'Flight Timer' which is the time I launch to the time I land, or catch the model.
Pull the switch to reset the timer to zero (ON)
Release the switch to start the timer (OFF)
I need to log the flight time at the same point as I reset the timer by pulling the spring switch (ON)

It would be good to have a display of the flight times in order on the left box of all the recorded flight times....
There would also need to be a way of resetting the recorded times in the list all back to zero.

**Comment by xSuperflyx** [comment]
Here is a visual representation created using Microsoft Word of desired look...

![FLIGHT TIMER LOG](https://user-images.githubusercontent.com/84725136/119507239-92ac2080-bd66-11eb-8366-60eadcf2524a.jpg)

**Comment by xSuperflyx** [comment]
Can you please provide an update on this?

Will this be included in the next firmware update or will you send me the files directly??

Many thanks
Neil

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121354126-e144e780-c92e-11eb-9777-1b1516d550ba.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121354205-f3268a80-c92e-11eb-9860-a26411741306.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121354253-fe79b600-c92e-11eb-987e-509a36cc3257.png)

**Comment by xSuperflyx** [comment]
Wow, thank you this looks great!!

**Comment by 3Dholic** [comment]
Is there a way to get the log persistent ? They disappear every time I switch off and on the transmitter...
