### ISSUE TITLE
DUPLIQUER UN MODELE

### ISSUE THREAD

**Issue by KLOSTRO** [FrSkyRC/ETHOS-Feedback-Community#3292]
Bonjour,

J'aimerais savoir si c'est normal ou s'il y a matière à améliorer car j'ai voulu dupliquer une aile volante, ce que j'ai fais avec une programmation standard mais avec un mixage libre en plus afin de piloter de la même manière une aile volante qu'un avion qui a une dérive.
La programmation fonctionne correctement.
Mais en faisant dupliquer le modèle, cela n'a pas conserver mon mixage libre, donc uniquement le standard ???????

Voila ma question 

Merci pour votre réponse ou modification à y apporter

**Comment by KLOSTRO** [comment]
Version 1.4.15 EU
 
Envoyé depuis l'application Mail Orange
----------------De : "Bertrand Songis @ FrSky" ***@***.***>Envoyé : mercredi 17 janvier 2024 11:02À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>Cc : KLOSTRO ***@***.***>; Author ***@***.***>Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] DUPLIQUER UN MODELE (Issue #3292)
Quelle version ? Sauf bug les mixages libres devraient être copiés intégralement

**Comment by bsongis-frsky** [comment]
Reproductible en 1.4.17 ?

**Comment by KLOSTRO** [comment]
Je n'ai pas trouvé de version 1.4.17 ??????
