### ISSUE TITLE
Ethos Backup does not backup all files

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#3294]
My lua scripts are writing settings to files under scripts/<name>/.
If you think there's a better place let me know. But as far as I know, there isn't any standard for that. And of course we want this to be a part of the backup.

So I end up having files like config.dat in script folder, or subfolders.

Ethos has "scripts" option in "Backup", which is cool.
However it seems to only backup some extensions, like .lua, .png.
I think just taking all files would be much safer.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/f160bcbb-3313-49bd-a378-ced0fb693cbc)

**Comment by Nicholas-Luoyi** [comment]
Sorry. I missed the last one. It's fixed this time.
