### ISSUE TITLE
Limit of fuel sensor over 100%

### ISSUE THREAD

**Issue by mhrfabio87** [FrSkyRC/ETHOS-Feedback-Community#3296]
Hi, I need the fuel sensor to exceed the 100% threshold on ethos. This is because I use a flybarless unit (Brain 2) which sends the vibration value on that channel exceeding the 100% limit (it can go up to 1000%). Can it be implemented in the next update?

**Comment by bsongis-frsky** [comment]
If the flybarless unit needs to send custom value which don't fullfill the S.Port specification, they have to use different IDs.

You could also discover this sensor as a DIY sensor and changed its settings manually
