### ISSUE TITLE
1.5 Free Mix Action Weight displayed incorrectly

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3298]
I have defined the following Free Mix Action

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/cdead5c8-c93a-48a5-9d9d-52fdda3af83b)

with a weight of -100%

and yet it displays with a weight of -101%

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/cdfb97fd-5124-4772-88f3-2c359208a6ed)

I seem to be able to recreate as follows:
Create a Free Mix
Edit the default action Weight and change it to -100%
This will display correctly as -100%
However, if you now edit the weight again and try to reduce it further with an anti-clockwise click on the jog wheel you discover that -100% is indeed the minimum so it doesn't go any lower, however if you now return to the Free Mix screen you'll see that the weight displayed is in fact -101% 

The same applies to 100% which can be made to dislpay as 101% if you try to increase it beyond 100%.

Thanks

1.5 Nightly 10Jan24

**Comment by hrenz** [comment]
at simulator
Free  mix  weight set to +100%
Action is then set to +500%

**Comment by bsongis-frsky** [comment]
Fix ready for RC1
