### ISSUE TITLE
Model templates

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#33]
Hi all!
I’m still waiting for upgrade module kit to try ethos, but have few ideas about ethos.
Biggest issue with opentx is bad wizzard...
Before I had multiplex radio, that had few very interesting options, one is model templates.
I like the way you added nice model wizzard, but it would be even better if you make model templates like sub menues when selecting type of model: plane-> basic, acrobatic, delta ( flying wing), jet,...
Glider-> basic, V-tail, 4 servo wing glider,...
Multiplex radio manual page from 95 up for reference.
https://www.multiplex-rc.de/Downloads/Multiplex/Bedienungsanleitungen/1-00096-bedienungsanleitung-royal-sx-16-elegance--en.pdf
What is best with templates is that once you set model with template, all switches, special functions are same for all new models createt with same template, just like making copy of model and edit it for new one.
Hope not asking too much...
Best regards,
Kristjan Crnoja

**Comment by mawzthefinn** [comment]
You can do this now using categories and creating template models then cloning.

The addition of categories makes this much more viable.
