### ISSUE TITLE
Aileron trim error?

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#330]
X20 v 1.0.7

I have setup anF5j type glider including the use of the Ail => Flaps Mix so that the flaps have about half the travel of the ailerons.

I'm not sure if I have done something wrong, or found a fault, but basically when I apply aileron trim the flaps move much more than the ailerons.

**Comment by KenLong51** [comment]
A bit more info... When applying aileron trim, it is the side with the down going surfaces where the flap travels more tha it should.

Normally up going surfaces travel more.

Hope that makes sense?

**Comment by Nicholas-Luoyi** [comment]
I have tried it by following your steps. I can only see that when the Aileron trim is applied. The aileron and flap output the same value. But flap doesn't travel more than aileron. May be a video to show? Thanks.

**Comment by KenLong51** [comment]
Hi Nicholas, 
If you paste the link below into your browser it will take you to a video stored on Dropbox.

It's worth noting that any Rates applied to ailerons do not get parsed to the Flaps via the Aileron to Flap mix - so you have to create the separately.

https://www.dropbox.com/preview/Public/X20%20Trim%20Problem.mp4?role=personal

**Comment by Nicholas-Luoyi** [comment]
I'm sorry I cannot see the video. But we do know the question. We will look into it. Thanks for your feedback.

**Comment by bsongis-frsky** [comment]
Today the Ail=>Flaps mix uses the ailerons trim. There is still no checkbox to disable the trim there.
Also the trim weight doesn't depend on the dual rate.
I think that for this mix we should:
1) Rename "Weight/Rates" to "Rates" only. Rates are applied on the input
2) Add a parameter "Trim" to enable / disable it
3) Add a parameter "Weight", which is applied at the end of the mixing. We could even have one weight per channel

**Comment by jfint** [comment]
This is actually very much related to #752

**Comment by bsongis-frsky** [comment]
Exact, this one will be fixed in the same time than #752 (see last remark for the trim %)
