### ISSUE TITLE
1.5 N (19 Jan) simulator:  There is no '---' option for Active condition in mixer actions

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3300]
The new Actions with 'Everything else' are very nice indeed. 

However there is no '---' (false) option for the Active condition of an action. It's useful sometimes to disable an action when debugging (as is possible with mixers).

Tested in X20S sim.

![2024-01-19_003822](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/1c9252b9-1dcb-4e01-9121-59cae156c67a)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8af7e0a8-de50-422f-a70e-1e00fa1ceea4)
