### ISSUE TITLE
1.5 N (18 Jan) simulator: +/- keys in numpad no longer function

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3301]
I've noticed  this in the last couple of 1.5 nightlies - the numeric + and - keys no longer function in the simulator.

In previous versions, they could be used to increment/decrement numeric values.

_Using:_
X20 Sim
1.5N (18 Jan)
Microsoft keyboard, UK layout with integrated numpad

**Comment by bsongis-frsky** [comment]
Ready for RC1
