### ISSUE TITLE
V150 Simulator  ADC Test only pos bars

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3302]
ADC shows only the pos bars

and only the calculatets Values -1014 to +1024 not the reals AD Value now

![2024-01-19_082747 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/f6898967-bfb6-42c4-9d65-affc1192e9d5)

**Comment by Wolepo** [comment]
I can't say that, all values are positive. X10S Express 1.5 N 10.1.24 
![ADC](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/b3db521a-22f9-4646-9574-bdd45bf2fe14)

**Comment by bsongis-frsky** [comment]
What do you mean by "AD Value"?

**Comment by hrenz** [comment]
V150 X20 Simulator  Date 17.01.204 

shows values only from -1024 to +1024
but the bar ist self its only from right side to positiv 
![2024-01-19_122606 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/03dc173e-feb2-451c-9b50-ecea5c540757)

**Comment by bsongis-frsky** [comment]
This tool is only needed on real hardware (to show the ADC values, before calibration)
I will fix it on simulator, where the calibration step is not needed. The range is 0-4096

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/96f9d2be-0606-4087-a57d-ec59da069310)

Fix ready for 1.5.0 RC1
