### ISSUE TITLE
V150 Nightly 19.01.2024  X20 Simulator Weight at mixers only max set to 100% now

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3304]
At V1.4.15 at TX I can set the weight at mixers to max 150%

but
V150 Nightly 19.01.2024  X20 Simulator 
Weight at mixers only max set to 100% now
![2024-01-19_163222](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/1ba2b613-2710-4df3-b993-a12ee6d908dd)

**Comment by bsongis-frsky** [comment]
This one has been fixed today, it will be part of the NEXT nightlies!
