### ISSUE TITLE
Irx4  Multimodule Futaba Fasstest or Fasst compatibility

### ISSUE THREAD

**Issue by toganalper** [FrSkyRC/ETHOS-Feedback-Community#3307]
After installing the "multi" lua on my X20S and attempting to find the Fasst option to bind my Futaba receivers, I encountered an issue where only FHSS appears on the screen. Can someone please help me understand how I can get it working? All my recievers are R7014sb and such working with Fasst or Fassstest

**Comment by mawzthefinn** [comment]
FASST and FASSTest are not supported by the Multimodule, and not expected to ever be supported as they require custom IC's for such support. 

The MPM only supports the Futaba S-FHSS protocol. 

Protocols supported by the MPM are here:

https://www.multi-module.org/basics/supported-protocols
