### ISSUE TITLE
Can't cancel log viewer loading file.  It blocks everything including powering off

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#3308]
1.5.0 nightly 1/19.  I don't know if the behavior is the same for previous versions.

I was going to see the RSSI of a flight.  I have pretty long sessiosn and record at 200ms.  I clicked on the file to view it from the File Manager screen.  It shows the progress bar but it was only increasing 1% every 5 or 6 seconds.  At that rate it would have taken about 10 minutes or so to finish loading.  There is a close button but it is not active so I couldn't click on it to cancel the loading. 

I tried to power off using the power button when it was about 10% loaded but that didn't stop the loading either.  It interestingly seemed to cause the progress bar to stop increasing while I was pressing the power button but the progress bar resumed when I let go of the power button.

It eventually got to about 66% and then stopped progressing.  I am not sure if it hit a memory limit or if trying to power it off 6 minutes ago was affecting it.  I finally unplugged the battery to restart the radio and that worked.

So there are 2 issues that I see.  One is that you can't cancel loading a log file and you are stuck until it finishes.
The second is that for some reason it stopped progressing at 66%.  Memory limit or something else?

**Comment by agibson2** [comment]
Attaching the example log file that takes a long time to load and stops around 66%.  I tried it loading from an SD card (4GB fat32) and it had the same problem there.

No way to stop the load and it stops around 66%.

**Comment by bsongis-frsky** [comment]
Today there is no way to stop the load before it is finished. Searching for a solution ...

**Comment by bsongis-frsky** [comment]
A native viewer is far quicker than a Lua viewer!

**Comment by agibson2** [comment]
It sounds like you figured out a way.  Thanks regardless for looking into it.
