### ISSUE TITLE
Logical switches: Comment line 1.5.0 Nightly

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3309]
Logical switches: Comment line 1.5.0 Nightly
If the comment line covers more than the visible line, I cannot find a way to scroll to the beginning of the line.
I cannot make a correction in the non-displayed left line area.
The text must be shortened first.

Is there a trick to get to the left?

Greetings Eugen

![IMG_6295](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/f1f173f8-ad27-4cd8-89b2-57f4de136feb)

**Comment by hrenz** [comment]
V1.5.0. NIghtly 20.01.24
Comment delete works well 
with X and cursor setting
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/6ceacaf9-da17-40c8-b850-a243c678b748)

**Comment by yak55** [comment]
Hello Helmut, please give me a tip on how you achieved the number 1 in the photos.
I can't get it right.

X20 Po

Greetings Eugen

![IMG_6296](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/51f923d4-356f-4a89-ae41-d8e46ba3687e)
![IMG_6297](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/fd0f0338-f6c3-494c-8178-540607188fcf)

**Comment by hrenz** [comment]
ok habe dein Probelm verstanden
reichen die 60 Zeichen den nicht als Kommentar
recht oben werden eh nur wenige Zeichen dargestellt

**Comment by yak55** [comment]
Hello Hellmut, I have now reached the limits in 1.5.0.

If you use an X20 S, a Pro and an XE, you have to work with a logical switch on the X20S so that the comfort of the Pro and XE remains accessible.

One trimmer controls 4 different VARS on the X20S - depending on the flight status etc.

In this case, a comment may be a little longer.

The presentation in the summary is different if spaces are used in the text.
Then there are also sensible line breaks.

Greetings Eugen
