### ISSUE TITLE
Model Select in Ethos

### ISSUE THREAD

**Issue by ianda217** [FrSkyRC/ETHOS-Feedback-Community#331]
Is there any way to rearrange the order of models in the radio? I like to have my models arranged alphabetically but I haven't been able to do this in Ethos.

At the present time I have loaded 18 models into the system and they present themselves in no particular order in the list.

**Comment by Cipta-de** [comment]
hello,
the modells are sorted numeric model01 - model02 .....
so rename the models with a file manager will change the order

**Comment by ianda217** [comment]
Thanks for this.   Actually very logical.   I did try this before but when I restarted the X20S, I got a data missing message.   I now realise that was because I had renumbered the current model so the TX couldn't find it.   Not realising my mistake, I restored the original numbering.

**Comment by Cipta-de** [comment]
It could be also good to use the RX model number for the file-name. 
In the simulator I have tested to rename the model file to the model name - it works!
The models in the selection screen are sorted alphabetically. So I will rename my models like: 10_Edge; 11_ADXL ..
or if you want to sort alphabetically you can put the numers at the end of the name. 
greetings

**Comment by ianda217** [comment]
Cipta,

I had actually numbered my receivers in the order that I wanted the 
models in but that obviously didn't work.   I used your proposal to 
simply change the model numbers using Windows file manager in the 
bootloader mode.   That worked perfectly.   All my models are now in 
alphabetic order.

All I need now is some good weather to get out and fly them!

Regards,

Ian Dawson

------ Original Message ------
From: "Cipta-de" ***@***.***>
To: "FrSkyRC/ETHOS-Feedback-Community" 
***@***.***>
Cc: "ianda217" ***@***.***>; "State change" 
***@***.***>
Sent: Thursday, 27 May, 21 At 11:34
Subject: Re: [FrSkyRC/ETHOS-Feedback-Community] Model Select in Ethos 
(#331)


It could be also good to use the RX model number for the file-name.
  In the simulator I have tested to rename the model file to the model 
name - it works!
  The models in the selection screen are sorted alphabetically. So I 
will rename my models like: 10_Edge; 11_ADXL ..
  or if you want to sort alphabetically you can put the numers at the 
end of the name.
  greetings
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub 
<https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/331#issuecomment-849524412> 
, or unsubscribe

**Comment by Cipta-de** [comment]
A small suplement
I have experienced that renamed model files cannot be copied in the model select menue if the don`t have the name "model##"
If you try to clone a renamed modell the error massage "Model copy failed!" will appear. It`s possible to copy in the PC file manager and as far as I know - everything works.
