### ISSUE TITLE
ESC telemetry (Scorpion Tribunus / Castle Creations)

### ISSUE THREAD

**Issue by Holiday256** [FrSkyRC/ETHOS-Feedback-Community#3311]
It would be nice to have support for ESC telemetry for the Scorpion Tribunus II ESC line as well as Castle Creations without requiring a third party box to translate the signal.

**Comment by mawzthefinn** [comment]
I would suggest reaching out to those vendors and asking them for S.Port or FBus support. That is how this would be achieved.

**Comment by Holiday256** [comment]
Thanks MAWZ. I contacted both vendors today.

**Comment by Holiday256** [comment]
Castle Creations: "We are dependent on support from the radio manufacturers to support the Castle Link Live Protocol that communicates with the Telemetry Links. At this time Futaba and Spektrum are the only companies that have worked with us. It is possible in the future with cooperation from other radio manufacturers "

**Comment by mawzthefinn** [comment]
That's an odd response for Castle, as they provide their own adapter to both Spektrum X-Bus and Futaba SBus2 telemetry protocols. Both are done via documentation provided by the radio vendor, similar to what FrSky provides for both S.Port and FBus

If Castle Creations contacts FrSky, they can get the full documentation needed to produce a Telemetry Link unit for S.Port or FBus.

**Comment by Holiday256** [comment]
To be fair, that was from the FAQ page and appeared to be a couple years old. I have not received an updated replybto my inquiry. In August Scorpion was working on a solution. I requested an update on their progress.

**Comment by Holiday256** [comment]
Castle Creations update today: "Our telemetry is open source for any manufacturers to use, but just spektrum and futaba decided to implement it. The device I listed above should get you covered however."

Provided a link to a third party option in UK.

**Comment by mawzthefinn** [comment]
Which is hilarious since neither Futaba nor Spektrum have implemented CC telemetry. CC designed their own converters for both systems which speak those system's telemetry protocol

**Comment by bsongis-frsky** [comment]
It's needed for the sensors to speak the same protocol than the receiver! Other manufacturers have implemented S.Port / F.Port / FBUS onn their sensors to be compatible with the FrSky receivers.

**Comment by Holiday256** [comment]
Here's a link to our castle link live protocol. That's what they need. https://www.castlecreations.com/castle-link-live

**Comment by BladeScraper-Designs** [comment]
Yep there needs to be some sort of adapter from Castle and Scorpion for such a connection to be possible.  YGE makes one for their ESCs, called TeXy, which supports FrSky S.Port, as well as a few other radio mfg telemetry systems.  Castle and Scorpion would need to make something similar... FrSky won't add someone else's protocol to their own radio system.

**Comment by mawzthefinn** [comment]
Closing off, as the ESC manufacturer's need to take action on this.
