### ISSUE TITLE
GAS SUITE LUA SCRIPT NOT WORK 1.4.15 ETHOS

### ISSUE THREAD

**Issue by eliasmoby** [FrSkyRC/ETHOS-Feedback-Community#3313]
I cant update any parameter in ethos 1.4.15 with Gas suite, only have the 3 OK Buttons available

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/124819212/a7258e49-e1be-4795-bcd3-e8df83a1db47

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/124819212/ce07dcbe-a31b-430d-9634-bee398f54dd2

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/124819212/bbc737d9-1e2a-4f82-a48d-376ea56f2eb0

**Comment by bsongis-frsky** [comment]
It seems like your connection to gas suite is not good, when fields are greyed out, it means that the values are not received (only default values are displayed)

**Comment by bsongis-frsky** [comment]
Do you receive telemetry from the gas suite?

**Comment by eliasmoby** [comment]
I change the cable and dont work any way, also i have telemetry from the gas suite rpm, temp1, temp2 and flow gas!!!

**Comment by eliasmoby** [comment]
Also i uograde to 1.4.17 ethos, downgrade to 1.4.10, 1.4.13, 1.4.15 and not working but i have telemetry readings, i update the fw for gaa suite by s.port and still not working i change the protocol for Fbus and not get telemetry i use the port 10 as smart port on td10R

**Comment by eliasmoby** [comment]
I connect vario and lipo sensor with sports in parallel and works fine, then connect the gas suite in the left s.port in paralell and gas suite nor work, just the lipo and variometer sensors.  Regards in advancw

**Comment by mawzthefinn** [comment]
Gas Suite requires S.Port to be selected on the receiver Channel Port.

Note receiver and TD-ISRM firmware matter. If running firmware 1.0.11 or later on TD R10, you NEED to have your TD-ISRM on 2.2.6 (or if running older TD R10 firmware, you need to be on TD ISRM 2.2.2 or 2.2.4)

**Comment by eliasmoby** [comment]
Gas Suite requires S.Port to be selected on the receiver Channel Port.
A=> I have Port 10 as Smart Port, so i have telemetry reads correct.

Note receiver and TD-ISRM firmware matter. If running firmware 1.0.11 or later on TD R10, you NEED to have your TD-ISRM on 2.2.6 (or if running older TD R10 firmware, you need to be on TD ISRM 2.2.2 or 2.2.4)
A=> Receiver is 1.0.11
        ETHOS = 1.4.17
        ISRM = 2.2.6 

If you see the last video you can see those info in the INFO tab.

Regards in advance

**Comment by eliasmoby** [comment]
UPGRADE NEWS!!!!!

I get another gas suite and works good, so my other Gas suite is broken, i will try to reinstall the FW and hope that works

Wait for more news!

**Comment by bsongis-frsky** [comment]
Confirmed good
