### ISSUE TITLE
1.5n: activate title in widgets with forms produces misplacement

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3314]
In case a widget title is activated, two bugs are induced:
(probably one cause)

(1)	touch area to enter edit mode of a field is miscalculated by title height
![touch area](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/af269b38-5835-44c1-99a3-ee46c871c0a1)

(2) in Form edit mode, the field is misplaced by title height
![place](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/f71de0bb-7949-45e7-a299-29e1392f7075)

could be a reincarnation of #3044
tested on nightly 17.Jan
Sim X18

regards 
Udo

[main.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14020063/main.zip)

**Comment by bsongis-frsky** [comment]
Reproduced

**Comment by bsongis-frsky** [comment]
Fix ready for RC1
