### ISSUE TITLE
more then 10 log switch, then not readible

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#332]
as soon  as the number of logical switches exceeds 9, the display becomes illegible.

![2021-05-25_131917](https://user-images.githubusercontent.com/6217896/119489638-2c220500-bd5c-11eb-92e5-d3f081204a89.jpg)

**Comment by bsongis-frsky** [comment]
@EngelMT

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/119494851-0b5cae00-bd62-11eb-9b86-5783e1a671a1.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/119494920-20394180-bd62-11eb-8152-542dfeb4dc1d.png)

**Comment by bsongis-frsky** [comment]
It's good in EN and FR

**Comment by EngelMT** [comment]
What can we do for 1.0.8? Shorter strings? Or will you modifite ETHOS like it works with longer strings here?
