### ISSUE TITLE
V1.5.0 Nightly improvement Play Value without Unit

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3320]
You should be able to choose whether a value is announced with or without a unit
Sometimes the announcement of the value with the unit takes far too long

**Comment by bsongis-frsky** [comment]
Plus in next nightlies

**Comment by hrenz** [comment]
Fine thanks

**Comment by azaz44** [comment]
There's another situation when this will be handy. I have my radio play the clock (RTC) if I flip the switch. It says it like it would be a timer "nineteen hours twenty three minutes" which is incorrect. I assume disabling the unit will fix this too.

**Comment by bsongis-frsky** [comment]
@azaz44 what would be correct in that case?

**Comment by bsongis-frsky** [comment]
You will reopen an issue if there is a problem with the RTC Time, I don't know how it should be played without the units

**Comment by azaz44** [comment]
> @azaz44 what would be correct in that case?

I think 'nineteen twenty three' would be correct, but I wonder what about US and UK which have AM and PM. But I would first check how it will be without units, and then wait until somebody raises a ticket. I might be the only one who made radio play the clock.
