### ISSUE TITLE
Ethos 1.5.0 User Manual ITALIAN Translation (rev 0 Draft 1)

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3321]
[X20 & Ethos Manuale utente_1.5.0 draft1 (Italiano).zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14058584/X20.Ethos.Manuale.utente_1.5.0.draft1.Italiano.zip)

I hope that you maintain also the old version of manual translation just like the English version....

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5/doc

Thanks!
