### ISSUE TITLE
1.5.0 RC01 X20 Pro EMERGENCY MODE being model change and receiver switched on

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3323]
1.5.0 RC01 X20 Pro Model change with receiver switched on

Model change started - (receiver of active model is still on)

Message: Receiver still ON, are you sure you want to change the model?

Confirmed with Yes

Checklist info is flash in displayed

Then : EMERGENY MODE

Press and hold ON / OFF - transmitter goes off

Transmitter switched on again - model change as desired!

Checklist info is displayed

Test receiver is SR10+ with current software

Problem occurs when checklist warning becomes active!

If all switches are correct and there is no checklist warning, there is no ERROR!

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Are you able to reproduce this issue?

**Comment by yak55** [comment]
Yes, it is reproducible.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Would you paste your checklist file? I cannot reproduce, but perhaps I have understood wrongly the issue?

**Comment by yak55** [comment]
Hi Bertrand, this is the backup file of the X20 Pro.
Model folder used: 1.5.0

The error occurs when switching from Acro - SxR 1.5 to Glider SxR 1.5 with the receiver switched on.

Both models have different checklists.

Receiver: SR10+
Sensors: Unisens - E.

Greetings Eugen

[Uploading ETHOS_20240126-1606.zip…]()

**Comment by bsongis-frsky** [comment]
Thanks for your continuous support! I will have check it now

**Comment by yak55** [comment]
Here is a new attempt
[Uploading ETHOS_20240126-1606.zip…]()

**Comment by bsongis-frsky** [comment]
Still not good :(
Perhaps you can use my email, I think you have it somewhere!

**Comment by yak55** [comment]
And here without model pictures, 6MB smaller
[Uploading ETHOS_20240126-1711.zip…]()

**Comment by bsongis-frsky** [comment]
Still not good

**Comment by bsongis-frsky** [comment]
Perhaps I only need your md files

**Comment by yak55** [comment]
Here the folder models and the bin file, because I use some global SF.

Greetings Eugen
[radio.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14067263/radio.zip)

**Comment by bsongis-frsky** [comment]
Good!

**Comment by bsongis-frsky** [comment]
Reproduced on simulator

**Comment by bsongis-frsky** [comment]
Your GoTo Page is executed before the Home screen is filled with all the pages ...

**Comment by bsongis-frsky** [comment]
Fix ready for RC2
