### ISSUE TITLE
1.5 Should VAR Action Percents be able to exceed 100% given Range can?

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3324]
I notice that in 1.5, VARs can have RANGE up to 500% however the ACTION of PERCENT can only go up to 100%. 
Is this intentional / desirable? 
It seems reasonable that PERCENT should also be able to go up to 500%

I notice that the MULTIPLY action can exceed 1.0 so allowing the output value to exceed 100% (subject to Range), so this suggests that an output value exceeding 100% is not unreasonable.

Thanks

**Comment by mawzthefinn** [comment]
Fixed in #3868
