### ISSUE TITLE
cosmetical issue on lua dev tool window

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3327]
I do really appreciate the new inbuilt "lua dev tool" functionality of the suite

nevertheless, i've the feeling that presentation in the putty window could be slightly improved

(1)
focus of the window remains on top, so you'll have to scroll to the bottom manually to read newest messages, 
it would be nice to have an automated focus on newest lines (scoll functionality) like in putty

(2)
tab & CRLF is not (or not always) put into account,
see attached screenshot suite debug window vs putty

![putty vs3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/26d8d8d4-b6ae-495b-a844-0b779edf7ddd)

(3)
timestamp is a nice to have feature, but sometimes it's "too much" info and make the window harder to read.
so a checkbox to deactivate the timestamp would be nice

again,
it's cosmetical,
no need for short-term implementation
release 1.5 imho has priority

thanks & regards
Udo

**Comment by salibaj2** [comment]
From where I can download this lua dev tool please?

**Comment by Nicholas-Luoyi** [comment]
> From where I can download this lua dev tool please?

You can have it on Suite 1.5.0
