### ISSUE TITLE
Problem with latest Suite

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3328]
Suite error message and error log.

Transmitter - X20
firmware version 1.5.0, FCC #6f032396
Jan 16 2024, 22:08:36

![Suite error message](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/7997610/51db42e1-aa3d-4bea-8aba-032c2551adf1)

[crash-20240126.txt.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14066146/crash-20240126.txt.log)

**Comment by bsongis-frsky** [comment]
Please check with RC1

**Comment by spoke2570** [comment]
It did that for my first plug in to suite with RC1 but not subsequently.

**Comment by bsongis-frsky** [comment]
I believe it happens only with nightlies, it will be fixed next week

**Comment by dwheeld** [comment]
Sorry, was off line for a couple of days.

Tried again with RC1 and received same fatal error message. 

[crash-20240128.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14076597/crash-20240128.txt)
