### ISSUE TITLE
Play Audio Tracks 1.0.7

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#333]
I was testing Ethos 1.0.7 and there is no audio playback for tracks. I can confirm that the Logic and Special Function are working as they highlight themselves as the variable is met. Is this just not implemented yet?

**Comment by MIKE-DAILEY** [comment]
Play Track from SF is working.  Make sure you have your user sounds on the SD card in the "audio" folder.  There are sub folders there but the user sounds go in audio.

**Comment by pld74** [comment]
Perfect, thank you. Now all working.
