### ISSUE TITLE
Lau scripts on Mac.....

### ISSUE THREAD

**Issue by BobX20s** [FrSkyRC/ETHOS-Feedback-Community#3331]
I am trying to program a new Neuron II 80amp with a Mac......everything is geared to PC. I cant load the Lua scripts or get the STK tool to load. 

I need someone who has succesfully programed the Neuron on a Mac to walk me through the process...please. 

Using X20S and TD R 10

**Comment by strgaltdel** [comment]
the lua configuration tool must run on your tx
it has nothing to do with
"mac or pc environment"

in case you dont know how to install luas or how to use them i would suggest to adress your problem on rcg,

like here
https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-X20-Pro-Tandem-24-Channels-with-ETHOS/page1846
or
https://www.rcgroups.com/frsky-877/

not sure this here is the the right place for this kind of issue

**Comment by bsongis-frsky** [comment]
It would be better on RCG / Discord

**Comment by BobX20s** [comment]
I don't know how to install the Lua script, and it does make a diffrence where you upload the Lua script from....There is no clear path to upload from a Mac.


Both links you sent me are NOT about Loa scripts. 

Also I am not familiar with RCG / Discord, what is that and where can I access?

I need help  please,,,,,

**Comment by BobX20s** [comment]
Why has this been closed? I still have not received any help.....I have been referred to a tread that has 1846 pages and no search......Please reopen.
