### ISSUE TITLE
Model Manager Issue 1.5 RC1

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3332]
Models become unrecognized by Suite once they have been loaded by the radio (set as current model). The models still work on the radio. Note the disappearance of the yellow and purple plane in the attached photos. 

![IMG_0502](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/b265e9b9-9d41-498c-9cff-2004aa1bc9b8)
![IMG_0503](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/f55cb8c8-bc52-4caf-a412-e0d247537a44)

**Comment by fdm225** [comment]
Out of curiosity, what is function of the model manager?  I have seen it in the previous releases of Ethos Suite but the edit button is disabled, is this intended for future functionality or is there something I am missing?

**Comment by spoke2570** [comment]
Theoretically, It will allow building, tweaking, testing and of model files without turning on the radio like OpenTX. Distribution of model files will be easier, too. One day...

**Comment by fdm225** [comment]
that would be amazing!  with 1.5 coming out I feel like that is one of the only major things missing.

**Comment by spoke2570** [comment]
Ya Ethos is has become very capable. I really can't wait to see those 'edit' buttons become functional.

**Comment by Nicholas-Luoyi** [comment]
I just want to check. How did you do the "Set as current model" operation with radio connecting to Suite?

**Comment by spoke2570** [comment]
It is not connected. Once the model is opened in the radio like to operate it. Suite no longer sees it correctly. 
Between the first and second pictures the radio has been disconnected turned on and the model selected for operation. Outputs checked for life. Turned off and reconnected to Suite.
