### ISSUE TITLE
Restore Function Broken 1.5 RC1

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3333]
Restore function is broken in both Windows and Mac versions. See image. The restore function locks up suite once it is started and  does no restoring. 

![IMG_0504](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/4607be41-dbcd-46f1-a4fc-f35d359cd30c)

**Comment by mgsanna** [comment]
<img width="891" alt="Screenshot 2024-01-27 114904" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/97c2bb80-4a29-483c-9a6f-2cd7033a1c1d">
<img width="954" alt="Screenshot 2024-01-27 114957" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/9166b997-69e0-42fa-9a9f-09b54d942f0e">

Windows 11 Ethos 1.5.0 rc1 Suite is workin on my side

**Comment by spoke2570** [comment]
@mgsanna: The backup function appears to work as you have depicted. Did you try the restore function? That definitely does not work on either my Windows 11 or my Mac Monterey machines. I'd like to say that the backup function is working as there is no evidence to say it is not, but  I can't believe it is until one is used in a successful restore session.

**Comment by mgsanna** [comment]
@spoke2570 also restore works

**Comment by spoke2570** [comment]
OK. I just loaded completely fresh installations of Suite 1.5.0 from the RC1 assets. Behavior for both Windows and Mac machines is as depicted in the original post.

**Comment by spoke2570** [comment]
1.4.15 is the last release of Suite that the restore function is working for my Mac and Windows computers.

**Comment by Nicholas-Luoyi** [comment]
It is a bug. Restore function doesn't work correctly.
