### ISSUE TITLE
Program Neuron II on Mac....

### ISSUE THREAD

**Issue by BobX20s** [FrSkyRC/ETHOS-Feedback-Community#3334]
This was closed out without any help, reposting.  I need help please. 

I am trying to program a new Neuron II 80amp with a Mac......everything is geared to PC. I cant load the Lua scripts or get the STK tool to load.

I need someone who has succesfully programed the Neuron on a Mac to walk me through the process...please.

Using X20S and TD R 10

**Comment by dap35** [comment]
Download the LUA scripts from your MAC to your transmitter.  After rebooting the TX, you should be able to launch the LUA script from the systems menu page on your TX.

FrSky ESC Tool Scripts for ETHOS 
---------------------------------------------------------

How to use the script tools?
1. Make sure the ETHOS and firmware on your devices are up to date;
2. Put the Scripts folder in the root dictionary of the SD card or Radio's storage;
3. Reboot the radio, the script tools can be found under the System menu page.

**Comment by bsongis-frsky** [comment]
I closed the previous issue, because such user requests should be done on forums, like RCG (but there are a lot of other forums in all languages). Here is the place for enhancement requests / new ideas / bug reports!
