### ISSUE TITLE
PROBLEME DE SAUVEGARDE

### ISSUE THREAD

**Issue by KLOSTRO** [FrSkyRC/ETHOS-Feedback-Community#3335]
Bonsoir, sur ma dernière version d'ETHOS SUITE 1.5.0, on ne peux plus faire la sauvegarde, il semblerait que ce soit un bug car cela reste bloqué.

**Comment by bsongis-frsky** [comment]
Duplicate of #3333

**Comment by KLOSTRO** [comment]
Ok
Merci Bertrand
 
Envoyé depuis l'application Mail Orange
----------------De : "Bertrand Songis @ FrSky" ***@***.***>Envoyé : samedi 27 janvier 2024 10:12À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>Cc : KLOSTRO ***@***.***>; Author ***@***.***>Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] PROBLEME DE SAUVEGARDE (Issue #3335)
Duplicate of #3333
