### ISSUE TITLE
V1.5.0 RC1: MPM not working on X10s ISRM

### ISSUE THREAD

**Issue by digitalonkel** [FrSkyRC/ETHOS-Feedback-Community#3338]
Green LED turns on, Red LED is flashing slow, means no input from TX. Irange iRX4 module
Works with versions 1.4.x but for sure w/o telemetry.

**Comment by bsongis-frsky** [comment]
Strange, it had been confirmed as working in nightlies :(

**Comment by digitalonkel** [comment]
In the 1.5 nightlies I don't see a version for X10 ISRM, so I cannot test it.

**Comment by mgsanna** [comment]
On my X10S Express work as supposed

![IMG_7155(1)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/760646b2-b024-42bc-8e0d-0bcadcb1fe1b)
![IMG_7156(1)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/abe413ff-7e64-47aa-abb6-0358c1406ddf)

**Comment by digitalonkel** [comment]
Great, then it should not be a big issue for the x10 ISRM.
Is telemetry also working? That is the reason, I am looking forward to 1.5.

**Comment by bsongis-frsky** [comment]
Can you choose the multimodule in Model / RF?

**Comment by digitalonkel** [comment]
Yes and I can choose different protocols as well. Tested with FrSky and Spektrum.

**Comment by bsongis-frsky** [comment]
Reproduced and fixed on X10S
- [X] X10S
- [ ] X10Express
- [ ] X12S

**Comment by digitalonkel** [comment]
Great, Thanks! Is there a download, that I can test?

**Comment by digitalonkel** [comment]
Tested the nightly from jan 31st. MPM works incl. telemetry.
Thanks for promt solution.
