### ISSUE TITLE
F.port2 and SBUS output servo handling error.

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#334]
ETHOS version: 1.0.7
Radio: X20S
Receiver: ARCHER GR6

F.port2 the receiver detects servos, configurable via radio.
I configured them one by one. 1; 2; 3; 4;
Physical ID: 01
Application ID: 01
Chanel:: CH1
(Ph.ID: 02; Ap.ID: 02; Chanel CH2 and so on up to 04)  
Model is a simple glider, two ailerons (CH1; CH2), elevatosr CH3, rudders CH4
Fport2 connected to a common rail with 4 servos working perfectly.
When connected to the SBUS output, the CH2 channel does not work.
CH1; CH3; CH4 channel works perfectly.

Why is this? What is the problem?

Previous: I connected the old ACCST G-RX6 receiver (receiver updated to the latest software) 
According to the description it works in both ACCST D16 and ACCES mode. 
However, ETHOS in ACCES mode is not recognized! 
I was able to connect it in ACCST D16 mode.

Question why it does not recognize in ACCES mode?

In ACCST D16 mode it recognises, they are connected, but the S.port does not become S.port2! 
So it does not recognize the servo connected to it. It cannot be configured.
No problem, I thought, the servo is configured and connected to the SBUS output.
Then I noticed that the CH2 channel was not working.
I accept that there will be no F.port2, but everything should work on the SBUS output.
It does work, except CH2.

Back to the first problem.
Everything works on the F.port2 output of the ARCHER GR6, but not CH2 on the SBUS output.

What am I setting wrong?

**Comment by janekx** [comment]
Are all servos updated with lattest firmware from Frsky page?
Fport2 is only present at ACCESS RX

**Comment by jufelap** [comment]
YES, all servos have been updated, but I will update again and post the result.

**Comment by jufelap** [comment]
Indeed, there is a problem with the servo. :-( 
It cannot be updated.
Works from F.port2 and works from PWM
Only not from SBUS :-( 
When updating I get the following messages.
device not respoding
version request failed

What can I do with the servo?
100% I have updated all of them and they all ran ok.

If I switch to F.port2, it sees the server and its parameters.
So it works, but you still can't update :-( 
What can I do?

**Comment by jufelap** [comment]
Hi Jan!

 

I posted (jufelap) my 5701 servo problem on github.com, which you replied to.

So the problem is that the servo won't let itself update.

It sees F.port2 and works in PWM mode, but not on SBUS :-( 

The error I described there:

 

device not respoding

version request failed

 

What can I do to make it work?

 

Best regards,

Ferenc Juhász

**Comment by janekx** [comment]
Sometimes it needs more tries to get updated. Strange it is working but not possible to update @Adelaxie any idea about the servo update please?
