### ISSUE TITLE
1.5 RC1 Emergency mode after setting up a Play audio sequence SF

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3340]
I tried to setup a sequence of audio files to call the IMAC maneuvers.

Added 10 lines of audio files in the sequence and used the momentary switch as an Active condition.

When trying to access the Special functions menu, the radio goes to Emergency mode since then.

Also, the momentary button only plays the first file of the sequence, not advancing to the others.

The audio files for reference are here: 
[sp2024.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14075655/sp2024.zip)
Files go to Audio/cs folder

X20S Model file with the issue is here: 
[rb test.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14075664/rb.test.zip)

**Comment by Wolepo** [comment]
Hello,
I have created a new model and always added a new announcement. I can confirm that only the first announcement is played.  Up to 7 files everything works, at the 8th announcement the emergency mode comes up.
X10SExpress 1.5.0 RC1
The attached file can be opened in the transmitter, but as soon as you enter the SF menu, the emergency mode appears. The model does not appear in the simulators.

**Comment by dwheeld** [comment]
The model from rb test.zip does not work in my sim.  I placed the unzipped  file 'rb test.bin' in the models folder, but it does not show up when attempting to change models.

**Comment by bsongis-frsky** [comment]
Reproduced

**Comment by bsongis-frsky** [comment]
Stupid  mistake from me. The description of this SF with a lot of actions is too long.

**Comment by pstasek** [comment]
No worries, that's what the pre-release testing is for ;-)
