### ISSUE TITLE
V1.5.0. N    CPPM and SBus at extern modul socket and DSC socket

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3341]
At which pin of the external connector of the X20 can CPPM and SBUs be fed in?

Does the SBUS signal also work on the DSC socket?

and which parameters are needed for CPPM at 8ch and 16Ch?

**Comment by bsongis-frsky** [comment]
PXX_IN from the external bay

**Comment by hrenz** [comment]
thanks will test it
