### ISSUE TITLE
1.5.0 RC1 - ETHOS SUITE drive eject issue X12S ISRM

### ISSUE THREAD

**Issue by Prop3r** [FrSkyRC/ETHOS-Feedback-Community#3346]
Radio: X12S First production series. 
TX board: ISRM S X10S
HW: 1.1.0 FW: 2.1.6 (EU-LBT)
Ethos suite V1.5
Ethos 1.5.0-RC1

After upgrading the X12S in Bootloader mode from 1.4.8 to 1.5.0 RC1, closed Ethos Suite, pulled the USB cable, X12S is bricked in USB mode.

Horus X12S shows a USB Icon, does not turn off.
Reconnecting the USB cable, and connecting it to a PC, does nothing.
Long press the power button does nothing. 
Solution: open up the case and pull the battery.

The bug is repeatable.

**Comment by yak-54** [comment]
i have had this issue from ethos suite  1.4.8 firmware and 1.4.9 ethos 
now i only way i update from sdcard only no usb to the pc
with out pc 
it  always works 100% pull the sd card put in a sd card reader  
and put the firmware refit and sd then power on the radio into bootloader mode let it update 
i have pulled the back off so much its stuffed the screw holes on the radio 

ETHOS Suite drive EJect #2706

**Comment by bsongis-frsky** [comment]
We have uploaded the latest Ethos Suite in the 1.5.0 nightlies and Mike has told us it works perfectly now. 
Would you please double check with this Ethos Suite version? Thanks!

**Comment by yak-54** [comment]
i did install Ethos Suite in the 1.5.0 nightlies
it crashes as soon as it starts

[crash-20240130.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14111178/crash-20240130.txt)
![300744791-86c5029c-9ebb-497c-a73e-6747d09a931f](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/a46dc906-118b-49b0-9257-49acc06a1bbd)

**Comment by yak-54** [comment]
so i restarted an next time clicked ok and update firmware to 1.5.0 rc1 went ok it updated eject drive then the radio went into black screen of death so as always had to pull the back off
![300750291-6eff26a3-991b-4c0e-a38c-9c1abc8474ed](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/3c71d706-f689-4484-8499-bfe089762e89)

**Comment by Prop3r** [comment]
Radio: X12S First production series.
TX board: ISRM S X10S
HW: 1.1.0 FW: 2.1.6 (EU-LBT)
Ethos suite V1.5 Nightly 29-01-2024
Ethos 1.5.0-RC1 Nightlies
Bootloader 1.4.3

Upgraded the X12S in Bootloader mode to the latest 1.5.0 RC1 nightlies. 
Succesfully able to eject drives and switch to Ethos using the buttons in Ethos suite. 
Pulled the USB cable while in Ethos, X12S is bricked in USB mode.

Horus X12S shows a USB Icon, does not turn off.
Reconnecting the USB cable, and connecting it to a PC, does nothing.
Ethos suite doesn't recognize the bricked X12S. (No radio connected)
Long press the power button does nothing.
Solution: open up the case and pull the battery.

Tried out some more.

If I do NOT switch to Ethos, but stay in Bootloader, disconnect the USB cable, the X12S stays in bootloader mode, and can be successfully turned off. 

It does not turn back on, however. Black screen, just like Yak-54 in the post above.

Best regards,

Vincent

**Comment by Prop3r** [comment]
To be very short: Nothing works in 1.5.0 RC1 with X12S.

Just reverted back to Ethos suite 1.4.15: 
Restoring works as it should. 
No black screens.
No USB bricks.

**Comment by Prop3r** [comment]
Ethos suite 1.4.15 in combination with Ethos 1.5.0 RC1 runs fine.

**Comment by Prop3r** [comment]
Quite sure it's the 1.5 Suite causing problems writing stuff, bricking/freezing/not working.
Suite 1.4 works without any problems
Ethos 1.5 RC1 also works without problems.

**Comment by Nicholas-Luoyi** [comment]
If you only switch between firmware and bootloader with Suite. Will the radio get freeze? (Unplug the USB in firmware mode)

**Comment by Prop3r** [comment]
In Ethos Suite 1.5 RC1, connected to Ethos 1.5 RC1 with USB in bootloader mode, switching between Bootloader and Ethos with the buttons in Suite, does not result in freezing.

**Comment by Nicholas-Luoyi** [comment]
So it only freezes after flashing the firmware in bootloader?

**Comment by Prop3r** [comment]
Ethos Suite 1.5 RC1, connected to Ethos 1.5 RC1 with USB in Bootloader mode, works without freezing.
Ethos Suite 1.5 RC1, connected to Ethos 1.5 RC1 with USB in Ethos mode, results in freezing in USB mode after unplugging. 
Ethos Suite 1.5 RC1 nightly, connected to Ethos 1.5 RC1 nighly with USB in Ethos mode, results in freezing in USB mode after unplugging. 
Ethos Suite 1.5 RC1 nightly, with Ethos 1.5 RC1 nighly, will freeze after reboot. (black screen)
Ethos Suite 1.5 RC1 nightly, with Ethos 1.5 RC1 nighly, will sometimes show NO SD CARD after 1 minute black screen.
Ethos Suite 1.5 RC1 nightly, with Ethos 1.5 RC1 nighly, will not startup Ethos.

**Comment by Prop3r** [comment]
For RC1 it's pretty much the same as 1.4.7: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2468

**Comment by spoke2570** [comment]
The most recent nightly version  of suite sorted this out for me.

**Comment by bsongis-frsky** [comment]
I reproduce the same kind of issue.

1) I am in bootloader, my SD is clean
2) I flash the latest firmware (I guess any firmware will do the same?)
3) After flash success, I eject the drives and unplug USB
4) When I plug again the USB, the drive needs to be repaired

So:
- either there is a problem in the bootloader
- or there is a problem in Suite (drives not properly ejected)

**Comment by spoke2570** [comment]
X20S RC4, Mac OS 12.7
ETHOS requires to be forced to quit once in a while, but I am unable to brick my SD card using Bertrand's steps. Actually, I have not been able to even doing blatantly stupid things.

**Comment by bsongis-frsky** [comment]
I have just found the problem, which is very old!
It will be fixed in 1.4 branch

**Comment by yak-54** [comment]
still not right but is better the radio dose not freeze i can power it off with out pulling the battery
but when i eject drives i get this on the screen
![20240222_094716](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/d9e529b4-08a5-41e6-92ea-0f7ceeb88351)
