### ISSUE TITLE
1.5.0 RC1 - ETHOS SUITE  X12S ISRM module not recognized

### ISSUE THREAD

**Issue by Prop3r** [FrSkyRC/ETHOS-Feedback-Community#3347]
Radio: X12S First production series.
TX board: ISRM S X10S
HW: 1.1.0 FW: 2.1.6 (EU-LBT)
Ethos suite V1.5
Ethos 1.5.0-RC1

**"RF Module"** shows **"unkown internal module"**.
**"Module firmware list"** is empty

Firmware V2.1.10 is adviced, but after selecting "Flash module" a warning appears that the internal module could not be recognized, and the firmware might be the wrong one.

**Comment by bsongis-frsky** [comment]
This is only available on Tandem radios. It will be hidden in next Ethos Suite when connected to Horus systems.
