### ISSUE TITLE
ELRS LUA Module Config not working correctly 1.5 RC1

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#3348]
Module HM ES24TX Slim Pro, latest ELRS 3.3.2, X20S - 1.5 RC1

Setup page now only show the first four options. Packet Rate, Telemetry Ratio, Switch Mode, and Model Match. At times these are delayed to load. The remainder of options no longer load at all.

Same module confirmed to work when switch to 1.4.17 radio. (TW xLite)

**Comment by yak55** [comment]
Please load the current LUA for ELRS from the 1.5 branch.
Then it will work on the 1.5

Greetings Eugen

**Comment by j-watkiss** [comment]
Many thanks, i had not seen the updated LUA
