### ISSUE TITLE
X10/12S model translation to X20 bug.

### ISSUE THREAD

**Issue by BobCotsford** [FrSkyRC/ETHOS-Feedback-Community#335]
Currently any attempt to transfer a model between Tx models fails with an 'Invalid Code' message if the model definition references the 6 position switch/ 6 buttons.  
Could either:
The 6 positions 1-6 on the X10/12S rotary switch be mapped to buttons 1-6 on the X20
or
Could the offending reference be changed to '---' and an error message displayed with the modified model then being loaded as current to allow it to be edited?
Or will this functionality need to wait for the desktop application?

**Comment by WismyYao** [comment]
Translation between X10/X12S and X20 model are not  supported currently

**Comment by bsongis-frsky** [comment]
Where did you use the 6POS switch?

At least in logic switches, AND function, it works:
![image](https://user-images.githubusercontent.com/50834778/119611001-62ae5d00-bdfa-11eb-8a97-d40a141c59f2.png)
![image](https://user-images.githubusercontent.com/50834778/119610906-401c4400-bdfa-11eb-9e29-6855b832ea6d.png)

**Comment by bsongis-frsky** [comment]
In flight modes:

![image](https://user-images.githubusercontent.com/50834778/119611445-ff70fa80-bdfa-11eb-9392-1a2e2d3a9bc5.png)

![image](https://user-images.githubusercontent.com/50834778/119611491-0ac42600-bdfb-11eb-84b3-14fa01d83106.png)

**Comment by BobCotsford** [comment]
Hi Bertrand, I habitually use P1 as throttle cut so I set it up in the throttle mixer as the active condition for throttle cut and in special functions to Play Track 'disarmed' Pos1 and 'armed' !Pos1.  Copying 5 models using this on my X10S  to the X20 resulted in 'Invalid Code' (iirc) when trying to select these models.  When I swapped the Pot1 references to SF the models copied across ok.  This was on v1.0.7.

Bob Cotsford 
    On Wednesday, 26 May 2021, 07:19:28 BST, Bertrand Songis @ FrSky ***@***.***> wrote:  
 
 


In flight modes:

**Comment by bsongis-frsky** [comment]
I have just made the test, I see nothing wrong in the conversion. Would you please attach your model file to this issue? Or send by email? Thanks

**Comment by BobCotsford** [comment]
I can't attach .bin files so I'll email two that work on an X10S but not on an X20.  Oddly one model did load, changing the invalid switch selections to '---'

**Comment by bsongis-frsky** [comment]
Yes, thanks!

**Comment by bsongis-frsky** [comment]
model03.bin
=> it's too old, written before release 1.0.0

**Comment by bsongis-frsky** [comment]
model08.bin (VRoc)
=> it's recent enough, import has worked, but we miss a protection, it uses a pot which is over the number of pots of the X20

**Comment by BobCotsford** [comment]
Thanks Bertrand, I'll try that.
