### ISSUE TITLE
No startup sound when "Select model at power on" is enabled

### ISSUE THREAD

**Issue by andytransonic** [FrSkyRC/ETHOS-Feedback-Community#3353]
Ethos 1.5.0 RC1, Tandem X20S. ISRM 2.2.6. Volume set to high, but no Startup or Shutdown sound.  Hello and Bye both play when selected from SD card. Audio  files in correct structure.

**Comment by hrenz** [comment]
Only no  Startup or no sounds at all?

**Comment by bsongis-frsky** [comment]
Strange...

**Comment by bsongis-frsky** [comment]
How is your audio structure?

**Comment by mawzthefinn** [comment]
Are these files correctly located? The file structure changes for 1.5 so a correct layout for 1.4 will not work

For a Main voice named 'test' and english language selected

Custom audio is in /audio/en/test
System audio is in /audio/en.test/system

Main voice is selected in System->General.

**Comment by andytransonic** [comment]
My Main voice is US.
Custom audio is in /audio/en/us
System audio is in /audio/en/us/system
Key press beeps are audible.
Volume is set to max on pot3
I hear the bye.wav on shutdown.
But no startup audio.
Also set Inactivity alarm to a low timeout, but no audible warning..
All this may have been caused by a bad flash.
Shall try again.

**Comment by andytransonic** [comment]
Reinstalled 1.5.0RCI.
Still no startup sound.
Under General, -- Select model at power on  was switched to ON.
Switched it to OFF.
Restarted Tx and Startup sound is audible.
Again switched it to ON , and again no startup sound.
Switched to OFF and all good, including Inactivity Alarm.

**Comment by bsongis-frsky** [comment]
Interesting, so it is linked to the "Select model at power on" feature!

**Comment by bsongis-frsky** [comment]
Reproduced

**Comment by bsongis-frsky** [comment]
Fix ready for next nightlies & RC2

**Comment by andytransonic** [comment]
Thank you
