### ISSUE TITLE
Hardware check

### ISSUE THREAD

**Issue by andytransonic** [FrSkyRC/ETHOS-Feedback-Community#3354]
Ethos 1.5.0 RC1. Tandem X20S. ISRM 2.2.6.
On the Hardware Check page the switches light up on extreme positions, but do not do so in the middle position.
The Switch Middle Delay shows an absurd figure of 2750 ms. Touching that immediately populates it with 200 ms and the switch middle positions are visible.
On altering the value progressively from 200 to 0 ms, the coloured ramp graph at the bottom does not change.
After reboot the switch position indicators on the Hardware check page work as they should.

**Comment by bsongis-frsky** [comment]
It seems like a bad conversion of the Radio Settings, have you kept your original files (before the conversion)?

**Comment by andytransonic** [comment]
Shall reinstall and try
