### ISSUE TITLE
Instant Trim

### ISSUE THREAD

**Issue by andytransonic** [FrSkyRC/ETHOS-Feedback-Community#3355]
Ethos 1.5.0RC1. Tandem X20S. ISRM 2.2.6. Mode 2.
On activating Instant Trim, The Elevator and Rudder Channels respond as desired.
However, nothing happens on the Aileron Channel.

**Comment by bsongis-frsky** [comment]
Would you share your model? 
Instant Trim will only work on Elevator / Rudder / Ailerons mixes. 
Not Free Mixes.

**Comment by andytransonic** [comment]
Had Free mix. Reverting to Elevator/Rudder/Aileron all good.
