### ISSUE TITLE
Twin Lite Pro does not run properly on 1.5 RC1

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3356]
I use a Twin Lite Pro module with an X20pro.  Firmware TW Lite Pro is 1.0.5 with 1.5 RC1 LBT on x20pro.  It seems that the transmitter is not communicating with the module.  The module does not go into bind mode and does not appear under the Info Screen.  The module is powered and the LED on the back lights up.

**Comment by bsongis-frsky** [comment]
Is it something which worked in latest 1.4?

**Comment by WhiskeyGolf** [comment]
It seems to work with 1.4

**Comment by bsongis-frsky** [comment]
Any news about this issue?

**Comment by WhiskeyGolf** [comment]
Just tested again, it seems to work with 1.5.2.

**Comment by WhiskeyGolf** [comment]
And with the 1.0.6 on the Modul

**Comment by bsongis-frsky** [comment]
Thanks for the feedback
