### ISSUE TITLE
Ethos Suite doesn't recognize my X20S

### ISSUE THREAD

**Issue by grzegorzheldt** [FrSkyRC/ETHOS-Feedback-Community#3357]
Hello.

I tried to connect two ways:
1. power on the transmitter, connect USB, and select Frsky Suite
2. power up the transmitter by holding enter button, enter the bootloader (1.4.3), then connect the USB

In both cases, I can see the LED color changed from blue to turquoise after connection, two drives were mounted, and the name of the device in the device manager is FrSky X20 USB Device. I can see the content of both drives too.

But Ethos Suite 1.4.14 says "Radio connection not detected!"

My PC is running Windows 11 Pro, 23H2, Ryzen 5950X

Could you please help me get this running ?

**Comment by Nicholas-Luoyi** [comment]
There may be a api issue in Suite. Please try opening the Suite app after connecting the radio and choosing Suite mode.

**Comment by rayzor120** [comment]
I agree with Nicholas,
when you plug in your radio there should be a box the opens on your radio's screen that gives you 3 options to select from and you should choose Ethos Suite.

**Comment by grzegorzheldt** [comment]
I tried starting Ethos suite after radio is already connected to USB. It didn't help. I tried several times. 

Today I have update to Suite to 1.5.0 RC1, and it just worked, both with bootloader and from main application.

As i'm not very familiar with windows, it is hard to explain this to me.

Thank you for your help.

**Comment by avkis** [comment]
Hello.
I have the same issue. The Ethos Suite doesn't recognize my Tandem X20. My Bootloader is not corresponds minimal requirements. 
Is there a way to upgrade a bootloader without using the Ethos Suite?
