### ISSUE TITLE
Rx powered down, but Receiver Still On message persists

### ISSUE THREAD

**Issue by andytransonic** [FrSkyRC/ETHOS-Feedback-Community#3360]
Ethos 1.5.0RC1. Tandem X20S. ISRM 2.2.6. RX1 TDR6 frsk 1.0.12. RX2 TDR10 frsk 1.0.12.

After OTA flashing both receivers, powered them down by disconnecting the Rx batteries.

When Tx is attempted to be powered off, the message " Receiver Still connected' is announced.

After waiting for some time and re attempting, the same situation, even though no batt is connected to Rx.

Have to override and force shutdown Tx.

**Comment by bsongis-frsky** [comment]
Would you go in Model / Telemetry an see you receive RSSI? Receiving RSSI means that the receiver is alive ....

**Comment by andytransonic** [comment]
Cannot replicate on same setup. Now working fine.
