### ISSUE TITLE
Restore function not working 1.5.0 RCO, RC1, Nightly

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3361]
Mac OS 12.7.3, Windows 10
I raised this once before, and it has only partially resolved. The restore tab now shows the correct information about the restore packages available to use, but when it is asked to restore the radio the window shows "restore in progress" but no Information about what it is doing (writing audio... etc). It can run for a long time. This time I ejected the drives via my computer's OS with no warnings about drive in use after about 45 minutes. There was no change in any file on my radio. Suite 1.4.5 is the last one that restores correctly.

**Comment by bsongis-frsky** [comment]
Have you checked the latest nightly? There is a new Ethos Suite there, ready for RC2!

**Comment by spoke2570** [comment]
Yes, I tried the latest nightly Mac image that was put up last night.

**Comment by spoke2570** [comment]
Would it be a good idea to put a bit in the instruction manual about how to handle this moving of files manually, like with desktop file manager?
