### ISSUE TITLE
OR LS with Two Edge FS is always true

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3362]
To recreate:

Create an LS, Function OR
Value 1  Edge FS1
Value 2 Invert Edge FS1

I would therefore expect the VAR to briefly become true when I press FS1.
The problem is that the LS is always true.

**Comment by mawzthefinn** [comment]
This is exactly as expected, inverted edge is true whenever no edge is detected, whenever it is not true, Edge will be true.

You set an Or to conditions which are A OR !A

That will always be true.

**Comment by bsongis-frsky** [comment]
Time for the week-end :)

**Comment by Jedsters** [comment]
Although if that is the case, wouldn't you expect an SF with an Active condition of Edge FS1 to play whenever FS1 is pressed rather than just when it is pressed to become on?

**Comment by Jedsters** [comment]
I believe there is a problem here. Doing the above and pressing FS1 you can see either VALUE1 or VALUE2 go bold / highlight, but even with neither bold the LS remains true.  We therefore have a true OR condition when neither of the VALUEs are true.

**Comment by Jedsters** [comment]
Best leave this as closed, I've now worked out the underlying problem and raised #3368 
Thanks
