### ISSUE TITLE
LS becomes true incorrectly

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3363]
Difficult to describe the scenario. Please see the attached

[prob wt.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14144257/prob.wt.zip)

To recreate, move SC Up and select the model and make sure the volume is up.

Navigate to the LS screen and monitor LS6/LS7

If you move LVU or LVD LS6 should briefly become active and the VAR value REF WT should be played.
However you will notice that LS6 AND LS7 briefly become active and both REF WT and SF WT are played.

Now if you move LVU or LVD again everything behaves as expected with just one LS becoming true and value being played.

Now move SC to middle position.

Again move LVU or LVD, again both LS6 and LS7 become active etc. when only LS7 should become active.

Each time you move SC between Up and Middle, the next time you use LVU/LVD both values are played when only one should be played.

If you move SC Down and then LVU/LVD even though none of LS1-LS4 become active LS5 and LS7 become true when only LS5 should become true.

If you navigate to VARs and do the above you can see that when VAR1/2 do not change LS6/LS7 may play even though the function of |delta| >1% is not true.

Thanks

**Comment by bsongis-frsky** [comment]
Fix ready for next nightlies

**Comment by Jedsters** [comment]
This doesn't appear to have been completely fixed as of RC3. 
I am finding that once I load the model with SC Up, then the first time of LVU both LS6 and LS7 become true when LS7 should not become true. If I then move SC middle and LVU again LS6 and LS7 become true when LS6 should not become true. 
Curiously after this it all works correctly.
