### ISSUE TITLE
Instant Trim on X12S - Emergency

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#3367]
X12S on 1.5.0 -RC1 #0c08de86

 stop working after setting up instant trim and exit trim menu to test it out the radio made cracking noise screen went black and receiver
went into fail safe 
![20240203_082056](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/4c6266d2-9abe-496e-adc2-3176df7c8d38)

**Comment by bsongis-frsky** [comment]
Reproductible?

**Comment by yak-54** [comment]
not all the time but did do 3 times in a row and i cant get the instant trim to work as well 
i was just about to flash it with Pre-Release 1.5.0 RC1 to see how it goes

**Comment by bsongis-frsky** [comment]
I see no problem, but would you paste your model file here? Perhaps I am missing something!

**Comment by yak-54** [comment]
i update it to Pre-Release 1.5.0 RC1 seams ok now on the same model 
it may of been bad flash
i will close it and reopen it if comes back
