### ISSUE TITLE
LSW Ignores Edge for FS

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3368]
If you create a LSW with an EDGE FS condition, it ignores the EDGE condition and just treats it as a FS.

Here FS1 is off and the LSW is false
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/c4cca85e-30f8-41c0-ae76-101240d841a7)

Here FS1 is on and the LSW is true even though you can see I'm not pressing FS1 so the EDGE FS1 condition shouldn't be true. 
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/bfccbd06-902b-4324-b3f4-f65f2bd0bc7a)

This is essentially the same as #3362 but I hadn't at that stage worked out the underlying problem.

Thanks

**Comment by bsongis-frsky** [comment]
Edge not only for FS, but all switches
