### ISSUE TITLE
Ethos 1.5.0 RC1  X20S mis alignment of some translated text

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3369]
Is it possible to give some space between "always on" and actions menu in freemix, other wise i need to change the translation of "always on" but it could be misunderstanding...
I enclose a screenshot of the "problem".pls let me know if it is possible or I'll update the translations
![screenshot-2024-02-03-51081](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/bf372374-35fe-4a2e-92c9-3f145725c7f3)

**Comment by bsongis-frsky** [comment]
How can I improve it? If I increase the first column width, then the last column won't be nice, and it is important!

**Comment by mgsanna** [comment]
Ok I think that I'll change or shorten the translation ... I think that instead of Always On / Sempre Attivo I'll change to S.Attivo or only Attivo, or Sempre On (assuming that most people are aware of what on/off means Internationally...

So today I'll post you a new translations file with some update, and I'll also update the 1.5.0 manual as consequence.
Thanks

**Comment by mgsanna** [comment]
[it.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14178042/it.zip)
 new italian translation with correction From (sempre attivo) to (attivo)

**Comment by bsongis-frsky** [comment]
I have just merged the translations from the other issue, I hope it's good!

**Comment by mgsanna** [comment]
yes it was a reductant upload... sorry
