### ISSUE TITLE
1.5 VARs missing confirmation for deletion of Actions

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3370]
Tested on 3/2/24 from latest nightly

With VARs if I delete a Value I am presented with a confirmation screen.
However if I delete an Action it deletes without confirmation.

This seems inconsistent. Most places we are asked for confirmation for a deletion, I believe we should have that for Var Actions too.

Thanks

**Comment by bsongis-frsky** [comment]
Ready for the next nightlies
