### ISSUE TITLE
1.5.0 Nightly summary of logical switches

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3374]
1.5.0 Nightly summary of logical switches

Both logical switches use operation < less than X. (voltage).

One is displayed correctly in the summary, the other incorrectly.

Greetings Eugen

![IMG_6322](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/164c2451-d120-4474-aa98-bcb2b8ea8af2)

![IMG_6320](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/ca581f31-7f8a-44ee-9e10-fc61f6f390f1)

![IMG_6321](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/fe6fb860-ea54-4ca5-b56c-5e25c34070ef)

**Comment by hrenz** [comment]
There is no ERROR

Durch das "Invertiert"  in der Funktion A<X selbst
wird aus der Abfrage nach A<X  ein Abfrage nach A>=X  was logisch korrekt ist
und in der Zusammenfassung wird das auch so dargestellt wird

Das gilt  für jede Zeile die in der Funktion selbst schon invertiert wird.

Logik Regeln nach De-Morgan
