### ISSUE TITLE
Long timer names corrupt Mode Name

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3376]
Long timer names corrupt Mode name

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/3ec3c0d5-648b-40be-a7ca-aa8602c668bc)

Thanks

**Comment by bsongis-frsky** [comment]
I thought of a memory overflow, it's rather a column overflow here!

**Comment by Jedsters** [comment]
Yes, I realised that my original title wasn't great and changed it quickly, however realise that you may not see that easily. Although now you say it I can see that the updated title could have been clearer to say it was just a formatting problem. Apologies for any confusion. I'm sure you quickly worked out what was going on from the photo though.  ;)

Thanks.
