### ISSUE TITLE
Feature Request: lua Timer status of running or target hit

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#3377]
It would be very handy to have a bool for if the timer is still running or hit it's target time (0 for count down or target time for count up).

Something like...
timer:running
or
timer:ended
or
timer:done

**Comment by bsongis-frsky** [comment]
```c++
/**
   * @brief Return the running state of the timer
   * @since 1.5.0
   * @return running (boolean)
   */
LUA_FUNC(running)
```

**Comment by agibson2** [comment]
Big thanks!  That will simplify my code.
