### ISSUE TITLE
Ethos 1.5.0. Italian Manual Update (new terms and revised content)

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3378]
[X20 & Ethos Manuale utente_1.5.0 draft1 (Italiano).pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14178174/X20.Ethos.Manuale.utente_1.5.0.draft1.Italiano.pdf)

**Comment by bsongis-frsky** [comment]
Doc uploaded

**Comment by bsongis-frsky** [comment]
Thanks!

**Comment by mgsanna** [comment]
thanks
