### ISSUE TITLE
VAR with slider as source becomes very jerky after change of Action

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3380]
I was testing out Assigning a Slider to a VAR as an Action and noticed that the VAR output initially becomes very jerky when the Action is changed to this assignment and this jerky motion seems to get transferred to an output channel too.

Please see the attached demo model

[var glitchy.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14177949/var.glitchy.zip)

I have created 2 Actions in Var FLAPS: SA Up which Assigns RS (i.e. real world usage) and SA Down which uses a Test Mix with slow up / down purely for demonstration purposes. The result is the same but it is far easier for you to see what is going on with a smooth Test Mix output than to try and watch my fingers on a slider and the channel output at the same time.

To see the problem, look at Mixes, Flaps, Outut channels (as per the video below) 

https://www.dropbox.com/s/jvmqspyn0qi3sxd/VID_20240206_095904.mp4?dl=0

You can see how the output moves very smoothly with SA Down, then when I switch SA Middle the output stops moving (as expected), however when I switch SA Down again the output is initially very jerky settling down after a few seconds. This becomes a problem in the real world scenario, with SA Middle again the output is fixed, but if you move SA Up and move RS smoothly you can see the output is very jerky for a few seconds before settling down. This would result in very jerky servo output.

Thanks

**Comment by bsongis-frsky** [comment]
The vars are not calculated in the Mixer task, but in the main task, which is far slower

**Comment by bsongis-frsky** [comment]
I understand it! It's not glitchy, it's just that it works like a trim:
- when press SA
- after 0.5s
- after 0.7s
- after 0.8s
- after 0.85s
- etc. after a certain time, it's every 10ms

**Comment by bsongis-frsky** [comment]
For PLUS / MINUS / MULTIPLY / DIVIDE / PERCENT working as a trim makes sense, otherwise the operation is done at full speed, which is bad

For SET // MIN / MAX it makes no sense. MIN and MAX are already good today. I willl change SET

**Comment by bsongis-frsky** [comment]
Ready for the next nightlies
