### ISSUE TITLE
Trim to Subtrim

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3382]
If you go to the Outputs menu and accidentally press [Enter] for too long, the corresponding position in Subtrim is adopted without a confirmation prompt in the marked line and the message "Trim centred" is played 5 times, regardless of how long you press. This is dangerous, as not only the trim is adopted, but the entire channel value is shifted accordingly. This can lead to model loss!
X10SExpress Ethos 1.5.0 Nightlies (latest).

**Comment by bsongis-frsky** [comment]
I do agree that a confirmation should be needed

**Comment by bsongis-frsky** [comment]
Another user suggested to move this option to the Trims menu. It makes sense to me. With the confirmation.

**Comment by bsongis-frsky** [comment]
The prompt is played 4 times for a simple reason, you have 4 trims set to Zero :)
It will be played only 1 time in the next nightlies

**Comment by Wolepo** [comment]
Thank you for the change.
