### ISSUE TITLE
V1.5.0. Nighlys only in Englisch for the TX  ?

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3386]
The problem in the i18n German is that some texts are too long, or

The numerical value is too far to the left as a fixed position, although there is still space on the right

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/736f9a4d-5ee6-40f4-b3b5-4f75b4de762e)

**Comment by bsongis-frsky** [comment]
It won't be easy, this screen has become more complex than before, and here I propose you find some way to shorten "differenziere", look at this screen, the numbers are very important and we cannot shorten the last column!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2b79f9ad-3f1d-4d1c-89db-a05d90c3ed8e)

**Comment by hrenz** [comment]
ok we will solve it
