### ISSUE TITLE
Ethos 1.5.0 rc1 8/2/24 Nightly Italian Translations update

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3387]
Due to the new functions placement of move trims and confirmation and warning here is the update translation

[it.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14207794/it.csv)

**Comment by bsongis-frsky** [comment]
We give you some work everyday :)
RC2 soon, I hope things will calm down!

**Comment by mgsanna** [comment]
It's so nice to be part of the future of rc world! and it's a pleasure to see ours nametag on about section of ethos suite!!!!
