### ISSUE TITLE
ETHOS 1.4.17 X20 pro sensor conflict 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#3388]
X20 pro on 1.4.17 Flex #c72d38c8 with TD-ISRM pro 1.1.12 and TD 18R receiver on firmware 1.0.12

getting lots of sensor conflict messages when used with ardupilot frsky passthrough sensors

**Comment by bsongis-frsky** [comment]
Well. What are the IDs from ardupilot ... Not sure it's an Ethos issue there! You may silent those warnings if needed, you will mimic OpenTX which doesn't care the sensor conflicts (sensors not fullfilling the specification)

**Comment by bsongis-frsky** [comment]
Unless it's related to #3373 which remains to investigate

**Comment by yak-54** [comment]
it may be an RF or TD 18 issue
i did test  same model but i used  ACCESS R8 PRO it does not do it at all
 it may be conflict extra sensors  of the TD 18 receiver

**Comment by yak-54** [comment]
i get sensor conflict warring from every 33 sec and some times it 93 sec

**Comment by yak-54** [comment]
just tested it with new TD R6 on 1.0.12 firmware all good

**Comment by yak-54** [comment]
so its looks like the issues is when i use the TD 18

**Comment by dWoolridge** [comment]
May be similar to my Issue FrSkyRC/ETHOS-Feedback-Community#3614.
