### ISSUE TITLE
Special functions, Play audio, can play multiple sequences. 

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3389]
I have Special functions, Play audio sequence set up for 3 different sequences by using switch A up for one sequence, switch A mid for the second, and switch A down for the third. All 3 use the same trigger switch (switch I) to advance to the next audio file. When the sim is first started, only the sequence pointed to by switch A plays when switch I is pressed. However, if I move switch A to the other 2 positions and then back to up position, all 3 sequences play each time I press switch I. I have only tried this on the sim and do not know if the same is true for transmitter. Please note: Audio defaults to off on video. Needs to be switched on to hear issue.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/7997610/fcc8fb22-5913-4778-9fa4-167b6215a185

**Comment by bsongis-frsky** [comment]
This is done on purpose, people didn't want that their sequence was cut when the Active condition became false.

In your use case, for SF3 you could use "SA(up) INVERTED" as a Reset condition, is that OK?

**Comment by dwheeld** [comment]
Yes. Using an inverted Active Condition for Reset on each sequence works. Plus it saves a switch, that would have been used for reset, to be used for something else. If one still wanted a dedicated reset switch, 3 logic switches could be created, using the inverted Active Condition OR their desired reset switch.

Is there any chance of increasing the maximum number of entries in the sequence list? Many of the IMAC 'maneuvers' consists of 3 or more sub maneuvers. I have divided these into separate audio files, which means I need an average of 30 for each major sequence. Having to insert a wait condition between each would require a list 60 slots long. That's why I need 3 sequence lists now.

**Comment by bsongis-frsky** [comment]
Changed to MAX=100 lines 
But not in RC2 as you asked for it too late, it's compiling right now!

**Comment by dwheeld** [comment]
Thanks!!!
