### ISSUE TITLE
Sensor Id 600 

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#339]
Sensor I'd 600 displays as % fuel. Should this not be mah consumed?

**Comment by islandflight** [comment]
Yes but display as a % rather than actual mah consumed

**Comment by bsongis-frsky** [comment]
Fuel unit in mAh? I must be missing something

**Comment by islandflight** [comment]
I'm using a yge esc and it's meant to be reporting mah consumed to that address, maybe it's a yge issue. As it's reporting percentage fuel used is there a way of entering the starting capacity e.g. 2500 may or is that info meant to be sent from the sensor?Sent from my Galaxy
-------- Original message --------From: "Bertrand Songis @ FrSky" ***@***.***> Date: 26/05/2021  10:01  (GMT+00:00) To: FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc: islandflight ***@***.***>, Author ***@***.***> Subject: Re: [FrSkyRC/ETHOS-Feedback-Community] Sensor Id 600  (#339) 
Fuel unit in mAh? I must be missing something
