### ISSUE TITLE
Error in Trim to Subtrim 1.5.0 RC1 Nightly - Trim value is NOT added or subtracted from the existing subtrim

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3390]
Error in Trim to Subtrim 1.5.0 RC1 Nightly

Trim value is NOT added or subtracted from the existing subtrim.
Trim value REPLACES the existing subtrim on first press.
On the 2nd press, the sub-trim becomes 0, as the trims are set to 0 before the 2nd press.

Greetings Eugen

**Comment by bsongis** [comment]
Good catch! I will shift the RC2 tomorrow to fix it

**Comment by bsongis-frsky** [comment]
Fix ready for RC2
