### ISSUE TITLE
File transfer from XE to X20 Pro 1.5 RC01

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3393]
File transfer from XE to X20 Pro / X20S 1.5 RC01

Even a completely new empty model cannot be opened.
Message: Data invalid!

Model cloned: Loading now possible
BUT: HF system is now off!
Then: HF system switched on - BUT data incorrect!
Model ID is incorrect, 
Type TD mode has become ACCES/ACCST D16
 
I could not test whether programmed receiver options e.g. channel mapping are still there!

Model config / radio switch: 
Buttons (XE) have become 6-pos X20 Pro / X20 S!

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Reproduced
