### ISSUE TITLE
Trims to Sub-trim transfer

### ISSUE THREAD

**Issue by Hennyvt** [FrSkyRC/ETHOS-Feedback-Community#3394]
In Open TX it was possible to transfer Stick Trims to Sub-trims, which then zeroed the trims.  I have not found this function in Ethos, maybe its already there???

**Comment by Wolepo** [comment]
Hello,
Since the last nightlies 1.5.0 RC1 it can be found in the trimmer menu.
Wolfgang

**Comment by bsongis-frsky** [comment]
@Wolepo is right. It is already present in nightlies (with a bug though) and it will be done correctly in RC2 (later today)

**Comment by Hennyvt** [comment]
Thank you everyone.

 

Henny
