### ISSUE TITLE
A nice to have.

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#3395]
This is a “Would be a nice to have”
Full house gliders.
Using + Glider for adding a new electric glider.

When you go through the process of setting up a glider with an engine.E.g. (Electric glider) . The throttle is automatically assigned to the throttle stick. The first thing I do is go into the throttle mixer and change the source of the throttle to the left slider, as the throttle stick is later to be used as the source for the Crow brake or spoilers. 
At the end of the setup I then go to complete the checklist.  It is ok setting up the start position of the left slider ( throttle)  typically  <-95% , but setting the start position of the throttle stick becomes a problem because the checklist is semi fixed with the throttle stick as the throttle control and there is now some interaction between the stick position and throttle slider position.

You cannot get the check list accept the start positions of the left slider as essentially -100% and the start position of the throttle stick as + 100%  at the same time.

It would be helpful (Not essential) to be able to have the option in the checklist to accept the throttle stick at +100% when the throttle source has been changed away to another source.
If I have missed a trick somewhere, please let me know and I will close this off.

**Comment by spoke2570** [comment]
It’s take a couple logic switches, but a single throttle mix line will definitely manage your left stick like that.

**Comment by spoke2570** [comment]
I just checked in my X20S and I can definitely set the throttle failsafe to +100%

I used the tilde (~) option and set the value to 100% in the 'Throttle' line of the 'Checklist' menu.

I am on ETHOS 1.5

**Comment by spoke2570** [comment]
I guess that I don't quite understand why you are looking for. My X20S on 1.5 will test for whatever stick position I choose regardless of the purpose of the stick. 

The Throttle line gives options for greater than, less than, and approximately (>, <, ~) and has a value that can be set from -100% to +100% and an option for 'do not check'. It does not appear to test the output, but only the stick position.

**Comment by kramgrand** [comment]
Hi many thanks for your reply.
If 1.5.0 gives you the options that is great and this can be closed.  But  I am not using 1.5.0 because it is not the official latest release.    I am using 1.4.17  Flex on X20Pro and X20S.

But If you would like to see some interaction in the checklist,

**With the throttle source set to the left slider in the throttle mix.**

Move the throttle stick to the top (+100%)-- = Crow / Spoiler off.

In the Checklist
1.  With the left slider set to <-95% and throttle stick to  ~ 100% .  Move the left slider from -100% to +100%  and you will see the stick symbol go from red to white at 100% left slider.
2. With the left slider set to <-95% and throttle to  either > or <95%    Move the left slider from -100 to + 100 again and you will see the stick symbol change from red to white. That leaves you with the option of No check on the throttle stick.
I've also tried ~ -100% left slider and ~ +100% throttle stick.   same happens at 100% left slider,  red to white on the throttle stick.
I can use a freemix for the throttle left slider and I would be able to set the throttle stick to ~ +100% and it works,  
except that I loose the inbuilt mixer safety features of throttle cut and sticky.   OK yes I can create that with a few logic switches and a couple of curves, but it would be more convenient / neater if that was not necessary.   As I said in the beginning, it would be a nice to have and is definitely NOT a serious problem for me.  I am looking forward to 1.5.0.

**Comment by kramgrand** [comment]
Hello

I have just picked up my emails so apologies for not replying earlier.  I replied on GitHub a short while ago.

If that is sorted in 1.5 that's great.

Thanks for your interest.

Regards. Mark

On 9 Feb 2024, at 12:04, spoke2570 ***@***.***> wrote:



It’s take a couple logic switches, but a single throttle mix line will definitely manage your left stick like that.

**Comment by spoke2570** [comment]
I just checked your schemes in 1.5 and they work as expected.

**Comment by kramgrand** [comment]
Hello.  I have loaded 1.5.0 on one of my TXs.  
The electric glider safe start positions required are:       Note:  Just for the moment have NO throttle mix in the model library

1. Set the Throttle stick, which is now the Crow brake and is set at +100%   and   ~100% in the checklist
2. Left slider which is going to be the Glider Throttle control is set at -100%.   and  -100% in the checklist
These positions are configurable as safe and give you TWO WHITE DOTS In the check list.

If you then ADD a throttle mix (Or you have chosen one in the initial model setup menu) and select the LEFT slider as the throttle, the  WHITE DOT on the  Crow brake STICK in the checklist goes to RED. (Not safe) Although it is still in the correct start position.    In this configuration, the only time you see a white dot on the stick is when you move the left slider to 100%.

You can alter the safe start parameters around  eg. < > ~ and none of them will give you what is wanted as in 1 and 2 above.

The issue is not fixed in 1.5.0

**Comment by spoke2570** [comment]
Yes, I had not added the slider as a source for a throttle mix. My apologies.

It looks like the throttle line in the checklist tests whatever input is chosen as the input for a throttle mix and applies the result to the throttle stick that was chosen in the sticks menu. The result from the left slider is applied to the throttle stick, and overrides the actual position of that stick.

**Comment by spoke2570** [comment]
I certainly would be more in favor of the sticks menu choices being used only by the new model wizard to set up default mixes. I feel like the concept of stick mode should have died with analog transmitters.

**Comment by kramgrand** [comment]
Yes that is exactly what it does.    It is not a show stopper, just an annoyance. It is an issue with the menu throttle mix as if you create the throttle mix using a freemix you do not run into the problem.  Not quite as safe though until logic is built around it. I.e.  Throttle cut and Sticky.

**Comment by kramgrand** [comment]
Think I'll close this off and create a new issue.

**Comment by kramgrand** [comment]
Closing this and opening a new issue with a better description.
