### ISSUE TITLE
(Desired) Special function screenshot

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3396]
Hello,
I have added the camera sound as a 2nd SF for creating screenshots. It would be nice if this could also be played directly as a track in the Screenshot SF function.
Thank you for your understanding

**Comment by Wolepo** [comment]
I've had a look at all the SF functions. In principle, you could use "Play Track" everywhere in addition to the existing functions.
At the moment, the functions in Play Sequence are quite limited.
![Sequenz](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/43b6249f-59bc-41d9-aa78-946b939f9f4b)

If you were to allow all SF functions here, you wouldn't need to insert it individually in each SF.

**Comment by bsongis-frsky** [comment]
I am not sure it's a good idea. Play a file, then take a screnshot, then send the Failsafe ... it seems like mixing potatoes and roast beaf

**Comment by Wolepo** [comment]
If you overdo it, you could do it like this. But you always have a choice about what you set up.
