### ISSUE TITLE
Sensor Conflict X20HD upkit, TD SR18 and RB40 with many sensors

### ISSUE THREAD

**Issue by rayzor120** [FrSkyRC/ETHOS-Feedback-Community#3397]
Hi,
I have updated below items to latest firmware and LUA as of 07FEB24:
- X20HD with Upkit
- TD SR18
- RB40
Items not updated to latest firmware if there is anything to update
-FAS 150 ADV  (qty 2)
-FLVSS (qty 4)

Once all items are hooked together and powered there are are sensor conflicts.

What my setup looks like without the 7s batteries and their sensors. Picture attached.

Pin 1 - SBUS from RX to RB40 RX1 IN
Pin 2 - SPORT form RX to RB40 RX1 SP

So far servos all servos are working.

![Servos and Accessories](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/159553705/f865e703-37fe-4a3e-a88e-b824ef2f5579)

![UFXN2965](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/159553705/3fb00619-947e-40d8-9847-86c8c4c678fc)

**Comment by mawzthefinn** [comment]
Have you changed the sensor id’s on your duplicated sensors? Each FAS150 and FVLS must have a unique application ID and physical ID or you will get conflicts

**Comment by rayzor120** [comment]
I was not aware that could be an issue but I will look into it. Are there any videos floating on the internet about how to discover and change ID's? Just an FYI, I pulled all the sensors off and was left with the receiver and RB40 and still had sensor issues(conflicts). Should I delete all and re-find sensors on the Telemetry page and add one sensor at a time?

**Comment by rayzor120** [comment]
Removed all sensors and no sensor conflict between RB-40 and TD SR18.
I moved the receiver's S.bus and S.Port from pin 1 and pin 2 to pin 17 and pin 18.
Soon as I add 1 current sensor, the conflicts start.

**Comment by bsongis-frsky** [comment]
I close this issue in favor of #3373 which seems similar.
