### ISSUE TITLE
Hard to see inactive mixes/LS/SF in the sun (they are very dark)

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#3398]
When out in the sun even with the S models with brighter screens, It can be hard to see the mixes to select them for editing when they are inactive.  It seems like having them only a little dimmer than the active ones would make it easier.  Maybe make them another color so they would still be bright instead of making them darker?

I have experienced this quite often where I want to make a change and have to remove sunglasses and shade the display because i can't find the right mix to edit because they are greyed out and very dark.

**Comment by bsongis-frsky** [comment]
Do you use the dark theme or the light theme?

**Comment by agibson2** [comment]
I have 'dark mode' set if that is what you mean.

**Comment by agibson2** [comment]
I am still hoping something can be done in the future for this.  The disabled mixers in the mixers list page are just too hard to see with the dark theme.

**Comment by agibson2** [comment]
And still hoping for this enhancement.  It is very hard to see inactive mixed and special functions because the text is too dark for them in daylight.

**Comment by bsongis-frsky** [comment]
To be tested in the next nightlies

**Comment by robthomson** [comment]
In the 'sunlies'
