### ISSUE TITLE
1.5.0  RC2 plays part of welcome audio at full volume

### ISSUE THREAD

**Issue by mikedkelly** [FrSkyRC/ETHOS-Feedback-Community#3399]
I have pot3 on my X20S set to control main volume. When I boot my TX with Ethos 1.5.0 RC2, it plays "Welcome to Eth..." at nearly full volume even if the pot is turned all the way down. It then plays the remaining "os" at the volume setting of the pot. All remaining sounds after boot play at the controlled volume.

**Comment by Wolepo** [comment]
I can confirm that, it was the same in the last nightlies. It seems to be due to the initialisation sequence. The volume should therefore be set beforehand.

**Comment by DaySpeed955i** [comment]
I also confirm however, only for more complex model, it does not happen with simple models. Same with all pots and slider.
