### ISSUE TITLE
Throttle mixer stops working

### ISSUE THREAD

**Issue by JuhaAlmqvist** [FrSkyRC/ETHOS-Feedback-Community#34]
I have Ethos 0.0.16B in my X10s Express. When i create a new model from scratch, everything works just fine,
but after restarting the radio, the throttle mixer stops working. This happens every time. I have tried version 0.0.17B
but it is too unstable to use in my radio.

**Comment by Nicholas-Luoyi** [comment]
Would you please post your model.bin here. Thanks

**Comment by JuhaAlmqvist** [comment]
Unfortunately i dont have it anymore, because i already flashed OpenTX back to the transmitter. It was a helicopter model
made from the other template, and i used the throttle mixer to make 3 different throttlecurves and a hold function.

**Comment by bsongis-frsky** [comment]
Please reopen this issue when you are ready to explain a little bit more what happened, i.e. are your mixes there when you start your radio (not correctly saved?)
Then you will post your model file here.
