### ISSUE TITLE
Block binding or warning on new model if ever used model id selected

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#340]
I use to copy model to create a new one and dont have to do all programmations again.
When you bind in this case there is no random model id attribution, i change model id manualy.

With a GRX 8 in accst the binding procedure works but after i have no controls. but the outputs show it works...
I have lost one hour to try binding again with another receipter mode, change every mixers to realize that this were only because the model id was ever use....

We should have a warning when same id is use and being unable to launch binding

Thanks.

**Comment by jreis1** [comment]
+1
