### ISSUE TITLE
1.5 RC2 Formatting problem in Mix Actions - Action name overwrites 'Weight'

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3401]
1.5 RC2 
See below where the Action name overwrites 'Weight'

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/75f7a9ce-face-4ce6-994e-dbb3741e94e9)

Hopefully less confusion this time.  ;)

Thanks

**Comment by bsongis-frsky** [comment]
Introduce a new method to be able to display either the short version of a Source, or the long version.
Here the short version is needed

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c9be3d34-7002-4857-bef0-91813647eb74)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0a3df4df-1ccd-4004-aa58-5267951e7241)
