### ISSUE TITLE
1.5.0 RC2: Where are the timer triggers for throttle?

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#3403]
In 1.4.17 i always trigger the timer by throttle absolute (as active condition) but after flashing 1.5.0 RC2 the timer started running directly. I don't see these throttle options anymore in the timer start conditions menu. Have they been removed?

**Comment by mgsanna** [comment]
Here are the solutions to your issue, simply re-arrangement of assignment menus

![IMG_7304](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/0f5e66e3-3dbf-45ba-8ee7-51a005f2fc1d)
![IMG_7305](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/28e12642-ed6d-47a5-bcc3-23635d68d4bb)
![IMG_7306](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/5d2995a4-d23b-48fd-af7c-e03d1150bbf2)

**Comment by mgsanna** [comment]
so you can close the issue that is a non issue

**Comment by RealTadango** [comment]
Should be converted correctly so still an issue.

**Comment by Dsrenger** [comment]
I agree.

The conversion of the timers is weired. Havent figured out, what really happens in the timer conversion, but it results in not working timers.

PErhapt Bertrand can test the conversion and knows why non functional timers are converted.

**Comment by mgsanna** [comment]
Yes you are right!

**Comment by RealTadango** [comment]
@bsongis don't forget this one for the next RC. I (and probably everyone) won't be happy if we need to modify all throttle timers for all models ;)
