### ISSUE TITLE
1.5.0 RC2: Spektrum telemetry through Multimodule is incomplete

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#3404]
I have an E-flite D18 that provides flight pack voltage over telemetry but when i discover sensors i only get the standard from MPM, like antenna fades, holds en RX voltage. Where is the rest of the sensors?

**Comment by mawzthefinn** [comment]
Duplicate of #3326 

Please continue the conversation there
