### ISSUE TITLE
1.5.0 RC2: NFC Remote not binding

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#3405]
Using an ACCESS receiver i am trying to bind my NFC Power switch. I have updated the firmware in the NFC module but i cannot bind it? I always get this error: Failed to bind the NFC with the module! Do you need a newer hardware revision for it? They list just the NFC module as a new product but since that firmware works in the older NFC modules i would expect them to be able to bind also or do i need to buy all new NFC modules?

**Comment by Dsrenger** [comment]
You mean the Remote NFC Panel?
https://www.frsky-rc.com/product/remotenfc-panel/

The old panel ist not that same then the new one. The new has additional hardware (a wireless module with an antenna) Not just a new firmware.

**Comment by RealTadango** [comment]
Thanks for confirming. I will order the newer ones.
