### ISSUE TITLE
V1.5.0 RC2  Curve with Offset and analog source for offset wrong calculation

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3406]
V1.5.0 RC2
Curve with offset in %
analog source for offset % 
wrong calculation 

think factor 10 to mutch

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/e3bda877-2309-453d-bace-37491175deda)

**Comment by bsongis-frsky** [comment]
But you have missed the same issue in Expo curves (expo + weight)!
