### ISSUE TITLE
1.5 RC2 Formatting problem in Timers with very long FM name

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3407]
When a Timer uses an Active Condition of a FM with a long name it overwrites the Reset condition - I suspect because FMx is prepended to the FM name 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/86b92699-853f-4d9c-90b6-f5c21cc619a5)

Thanks

**Comment by bsongis-frsky** [comment]
Use the short name there as well

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/65bfe986-8423-4088-bd84-d2cfb36e25b6)
