### ISSUE TITLE
[Suite] Not possible to update RF Module, Incorrect version reported in suite.

### ISSUE THREAD

**Issue by grzegorzheldt** [FrSkyRC/ETHOS-Feedback-Community#3409]
I tried to do full update of my x20S with ethos suite (1.5.0RC1).
Most components have been updated without any issue, but i'm not able to update RF Module.

<img width="886" alt="image" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/23026436/c39a5a74-22cf-4663-9da6-8d4c23b5874e">

The radio itself reports RF Module firmware version as 2.2.0

<img width="901" alt="image" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/23026436/d3163d64-8cd2-4130-a13b-1a2f34317bb6">

Could you please help me get this updated ?

**Comment by mawzthefinn** [comment]
Update Suite first, there's a newer build in 1.5.0 Nightlies which fixes some updating.

Also don't update your RF section until the rest of the radio is updated to 1.5.0, as the RF Module menu is going to expect ETHOS 1.5 on the radio (alternatively, use FRSK Flasher tool on Suite 1.4.17 if you don't plan on running a test version of 1.5 on your radio)
