### ISSUE TITLE
MPM: no setup/options for failsafe settings

### ISSUE THREAD

**Issue by digitalonkel** [FrSkyRC/ETHOS-Feedback-Community#3411]
The failsafe line is missing for MPM (in V1.4.x as well as in V1.5.0RC2)

**Comment by mawzthefinn** [comment]
For which protocol? Not all protocols in the MPM support that setting (DSMX for example does not)

**Comment by digitalonkel** [comment]
It is missing for all protocols except FlySky AFHDS 2A. (Mayby I missed to check the one or other subprotocol)
I need it at least for FrSky X2

**Comment by digitalonkel** [comment]
Fixed by myself: just added in line 39 the feature failsafe
("FrskyX2", 64, {variants={"CH_16", "CH_8", "EU_16", "EU_8", "Cloned", "Cloned_8"}, features=FAILSAFE+TELEMETRY, options={RF_TUNE_OPTION}})
Could be used maybe for other protocols with failsafe capability as well

**Comment by bsongis-frsky** [comment]
Don't hesite to bring your PR with your update, it could be useful for others!

**Comment by digitalonkel** [comment]
[multi.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14277398/multi.zip)
here you are
