### ISSUE TITLE
Suggestion: Bypass swap channel settings message with press and hold of new channel number

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3412]
Currently when swapping channels in mixes we are presented with the option of swapping channel settings which is very useful. 

However when trying to swap a couple of channels e.g. 3 and 4 to 5 and 6 and the original 5 and 6 to 3 and 4 in a number of mixes we can do so via an intermediate channel (to keep track of channels), but we only need to swap the channel settings for the first mix for each channel swap, so it would be useful if a press and hold of a new channel number bypassed the message asking if we wanted to swap channel settings.

Thanks

**Comment by bsongis-frsky** [comment]
But for people who press a little bit too long on the button, there will be no confirmation? I am not sure it's a good idea!

**Comment by Jedsters** [comment]
You may well be right. I can think of alternative suggestions (e.g. press and hold if the new channel name isn't blank), but they can similarly be countered.

Is this something which could be better and more safely addressed by a lua script or similar? (Not very familiar with lua, I only briefly played with it once so not quite sure what it can do.)

In my case I wanted to swap channel 3 with 5 and then 4 with 6 (rx a nightmare to access and I'd wired it up differently many years ago). The actual channel settings, (name, etc.) would be swapped and then all references in the mixes to 3 would change to 5 and those to 5 change to 3 etc.. Actually, that may be safer as there may be other references to channels in LS which could also be taken care of, fortunately I don't have any of those (hmmm, at least I don't think I do!)

Another feature which would be nice to have one day to help users, but certainly less important than 1.5.0 etc..

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6ee82a0b-1d32-42b8-bf23-cf2dd204eafd)

**Comment by ja-jaa-org-uk** [comment]
I have never understood why there is not a simple channel mapping between
the "output" of the Output stage and "input" of the RF stage.
A 8/16/24 byte array could be used with a default one to one mapping.
Templates would then be more widely applicable.
I must be missing something!
