### ISSUE TITLE
1.5 RC2 Extra trims not working correctly

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3413]
Please see the following setup

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/28c9df8b-f1ac-49fd-83d7-ed24a9ccde24)e

and note that the Range on the Rudder trim is set to 0% and Step to Disable so that should not be having an effect here.

When I select LHR or LHL the trim adjusts by varying amounts, usually around 40% or so.

If I hold LHR or LHL then it changes by 30% or so and increments by 10% as expected.

Thanks

**Comment by Jedsters** [comment]
Update: the problem is more widespread than initially thought. 
If you create a VAR with actions of Trim LHR/LHL and Add / Subtract of 10.0 then when you LHR/LHL that also increases / decreases the Value by far more than it should.
I wondered if the problem was Trim LHR/LHL itself, but that seems to work fine when use as a Rudder trim within Trims.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/14dc59a6-81f4-45af-8418-2cdaeac06157)

**Comment by bsongis-frsky** [comment]
"OFF" mode added

**Comment by Jedsters** [comment]
Just an observation, I've just tested this with RC3 and it now works and LHR/LHL increment / decrement as expected in my first 2 examples.
This was without changing any trims to the new OFF mode. 
I'm guessing OFF mode was added here but required elsewhere.
