### ISSUE TITLE
Wizard and "Flight phases"

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3414]
Hello
in the wizard, switches or analogue encoders can be set for the gyro modes (flight phases 1 and 2). But I can't do anything with that. What are the flight phases supposed to do?
Thank you

**Comment by Dsrenger** [comment]
The gyro flight mode switches in the wizard do create correct mixers to the correct output chanels based on the choosen RX.
The mixers are there to switch between Quick mode, Auto Level mode, hover, knife edge and off.
 
In my tests that worked fine.

**Comment by mawzthefinn** [comment]
Dsrenger is correct, the Wizard is setting up the inputs and mixers for the Stabilizer Mode channels on the FrSky Stabilized receivers. 

I've also tested and they work fine and properly populate for the receiver selected.
