### ISSUE TITLE
Vario parameters missing in new 'Play vario' SF - 1.5.0 RC2

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3416]
Ethos 1.5.0 RC2

The Vario parameters 'Range' and 'Centre' that were moved from the VSpeed sensor are missing in the new 'Play vario' SF.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/3b786347-03de-44db-acd5-7882809a3a70)

**Comment by bsongis-frsky** [comment]
Have you selected a Source for your Vario?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/15f9b5f3-bf35-4b3d-a45a-6921b1efa902)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/43533a35-bde8-46ac-9b45-308ea7c3a5b6)

**Comment by lthole** [comment]
I thought I had checked that, but I may be mistaken. The Range and Centre appear once you have selected the source.
