### ISSUE TITLE
Welcome to Ethos message ignores volume control

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3417]
1.5.0 RC2

The 'Welcome to Ethos' message ignores audio volume control settings. I have volume on the middle slider, and with the volume al the way down the audio is only muted half way through the word 'Welcome'.

**Comment by RealTadango** [comment]
Duplicate of #3399

**Comment by bsongis-frsky** [comment]
Duplicate
