### ISSUE TITLE
Output Invert doesn't appear to work as described in the manual

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3418]
According to the manual Output Invert 'Will Invert the channel output, typically to reverse servo direction.' 

It doesn't seem to me that this is actually what is happening. If I have a curve e.g. -100,-100 : 0,0 : 100,50 which is applied to a channel then when the mixer is -100 the output is -100 and when the mixer is 100 the output is 50 as expected.
However if I were to Invert the channel to reverse the servo I'd expect that a mixer of -100 would give an output of 100 and a mixer of 100 would give an output of -50 which would indeed be reversing the servo direction. 

Instead what appears to be happening is that it is silently reversing the mixer so although it shows -100 it is actually 100 but gives a servo output as if it were 100. 

FWIW I believe Ehos does not operate the same way as opentx which does appear to give output of 100 instead of -100 when the channel is inverted instead of the Ethos output of 50 when the channel is inverted.

Thanks

**Comment by strgaltdel** [comment]
Hi Jeddy,

to be honest,
I don't quite understand your description.

After inversion, the output shows exactly the expected values.

Input -100  ->  Mixer -100 -> Ch Output +100
Input +100 ->  Mixer +50 ->  Ch Output -50

??

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/9f7873f4-5e45-4227-ad88-0b8dec32b7a9)


![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/2143b589-ab90-4656-b551-cf9357e96232)

**Comment by Jedsters** [comment]
Hi Udo,
Sorry, let me try a different approach.
Let's change the curve to a 3 point curve -100,-100 : -50,-100 : 100,100
When the output channel is not inverted as you start increasing the input from -100 initially nothing happens until we get to input -50% at which point the output increases.
However, if we invert the output channel as you start increasing the input from -100 the output immediately starts to increase and continues increasing until you get to input 50% and which the output stops increasing.  
This seems reversed rather than inverted.

To contrast the behaviour to opentx (using my original example above)

This is what Ethos does top line -100 input and +100 input second line inverted

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/8a79f78e-d21e-4c14-9e5e-3b6cd99adccc)

contrast this with what opentx does

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/5ae4cf06-9bb4-46cd-bbb4-8f3a09db7713)

I take your point about hard stop points, but playing around with curves and inverting them is all part of the setup when we're trying to ensure that linkages are good and we're not exceeding any physical limits.

Is it really intentional that Ethos should differ in its behaviour to opentx? Is that what people will expect?

Thanks (sorry about the rather average quality photos)

**Comment by mawzthefinn** [comment]
Curves on the Output apply to the Output. You're inverting the input from the channels.

The ETHOS result is exactly what I'd expect. In fact IMHO it's more correct than the OpenTX behaviour (the curve is being applied to the Output value, not to the input value then inverted).

**Comment by strgaltdel** [comment]
Hello Jeddy,
thanks for the clarification.

as mawz said, the order of signal processing is a little bit different to oTx, and you've spotted the result/difference (-;

i agree with mawz, would say ethos is the way it should work,
maybe the term "reverse" would have been more unique

regards
udo

**Comment by mawzthefinn** [comment]
One note,

Since curves are one way to set endpoints, you really don't want them flipping as you mess with mixers, as you can seriously mess up servo setups in unbalanced applications (such as flaps or throttle servos).

**Comment by bsongis-frsky** [comment]
@lthole for you then?

**Comment by Jedsters** [comment]
As well as doc would it make sense to change the second row of the Output to Reverse, then Normal, Reversed ?

**Comment by lthole** [comment]
I agree with Jedsters, the second row should be renamed Normal / Reversed. You normally talk about reversing servos, not inverting servos.

All agree that Ethos is working correctly. 

I will clarify this part of the manual to emphasize that reversing here only reverses the output, and has no impact on the mixers. The min and max parameters remain the same, and are not reversed.

**Comment by lthole** [comment]
#3470 has been actioned in 1.5.0, so this issue can be closed.
