### ISSUE TITLE
Changing from Traditional Tail to V-Tail should not reset all mixers

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3419]
I've spent ages creating a template for a traditional tail glider and now need to convert it to V-Tail for my V-Tail gliders. Unfortunately editing it to get the right Ele/Rudder mixers resets all the mixers. 

I don't believe this should be necessary. Surely it should be possible to just reset / recreate the Ele and Rudder mixers using the same channels as a starting point. e.g. if I have ele on ch3 and rudder on ch4 then the new mixers should have 2 channels and should be able to work out I am using ch3 and 4 for each? The channels could then also be given new names of Elevator1/2. Failing that then it should be possible to create Ele1 with Ch3 and Ele2 with Ch4 - or even with no channels assigned would be easier than now.
  
As an aside this seems a bit of a misnomer for a V-Tail, surely the V-Tail channels should be called V-Tail1/2 ?

I am aware that this has been partly discussed in #3358 but that's more referring to the channel names. 

I wish I'd created my initial template as a V-Tail as at least V-Tail to Traditional would have been pretty painless to just delete one channel from each mix. 

Pretty please.  😃 

Thanks

**Comment by mawzthefinn** [comment]
This is exactly what #3358 is talking about, not just channel names but mixers themselves.

Please continue the discussion there.

**Comment by Jedsters** [comment]
Fair enough, although the description 'Reset Mix should not reset output names' sounded rather more niche, although the discussion has widened. So long as we're talking about the same thing I'm happy.
