### ISSUE TITLE
EthOS 1.5.0 RC2 French language not available for texts on X18

### ISSUE THREAD

**Issue by amaury10** [FrSkyRC/ETHOS-Feedback-Community#3420]
Hello,

I install the new release on my X18. French voice is working, but I can't select french texts.

Regards,

Amaury LAURENT 
![20240212_221405](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5411296/95cd1d75-5116-4924-aebf-7ba313d3ada3)

**Comment by amaury10** [comment]
I precise that the file fr.i18n is well installed on disk.

**Comment by bsongis-frsky** [comment]
Have you installed the latest i18n files? They are modified on each release

**Comment by bsongis-frsky** [comment]
It's strange that you have everything but french!

**Comment by amaury10** [comment]
Indeed, that's why I open an issue.
I installed the files twice : one by EthOS Suite 1.5.0 RC1 and one manually, to make several tests, but I never get French in the list, while I have French voice working fine. Is there a list of supported languages somewhere in the radio or is it listing available files in the directory ? Maybe the french file is corrupted ? I tried to have a look inside using Notepad but it's binary.

**Comment by amaury10** [comment]
If you want me to do further testing or if you need infos from my radio, just let me know.

**Comment by bsongis-frsky** [comment]
Perhaps the latest nightlies? They have been uploaded 3 hours ago...

**Comment by amaury10** [comment]
Ok, I'll test it the evening (French time ;-) ) and I'll let you know.

**Comment by samsab1** [comment]
hello
same thing here: on my x20s, with 1.5.0 RC2: only english is available, no other language

**Comment by samsab1** [comment]
![IMG_20240213_101201](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6443591/0d6ce913-bd0a-4736-835c-051f32c35af8)
here is the screen

**Comment by bsongis-frsky** [comment]
Reproduced. The i18n files are available on github. They are not present on my flash. So ... bug in Ethos Suite it seems!

**Comment by samsab1** [comment]
where should be installed the  i18n files?

**Comment by bsongis-frsky** [comment]
on your radio flash, in the i18n directory, I think it is empty right now

**Comment by samsab1** [comment]
> on your radio flash, in the i18n directory, I think it is empty right now

what is the name of i18n directory ? simply i18n?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d8463acb-6c46-46a4-ac38-615c5045a5d1)

**Comment by samsab1** [comment]
2 things:
1. error screen
2. no i180 menu in ethos 1.5

![2024-02-13_11h02_27](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6443591/9c364d7c-5d07-4f88-acaf-5e41b5f140e9)
![2024-02-13_11h02_46](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6443591/6a9193cd-5c7c-4b35-9e7b-c8c7d57e3542)

**Comment by bsongis-frsky** [comment]
You have to select the right branch, here not "Stable"

**Comment by samsab1** [comment]
solved!
thanks a lot

**Comment by amaury10** [comment]
Here is the content of my radio. It seems the fr file is really smaller than the others
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5411296/3ec85865-2587-45f2-a4a2-e42e2efd824a)

**Comment by amaury10** [comment]
The fr file in the nightly is also 4ko for X18. Whereas for the X20 it's 19ko. I believe the problem is here : @bsongis-frsky can you reopen the issue please, samsab problem doesn't seem to be the same ?

**Comment by bsongis-frsky** [comment]
Agreed, there is a problem

**Comment by amaury10** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5411296/79b5b586-dfc2-4074-bda7-2cc1741f30a9)
Even the simulator doesn't list the language. I open the csv source file to have a look : it seems correct. I copy the english csv, changing its name, the TRANSLATION_NAME and TRANSLATION_KEY : still no french texts in the menu.

**Comment by bsongis-frsky** [comment]
There are commas missing here and there, trying to generate a new X18S-FCC nightly right now

**Comment by bsongis-frsky** [comment]
Found it. It will be fixed in RC3 - Tonight ...

**Comment by amaury10** [comment]
Nice ! Congratulations :)

**Comment by amaury10** [comment]
I confirm that it has been fixed in RC3 :-)

**Comment by Majestic63** [comment]
I install the new release on my XE TAMDEM today. French voice is working, but I can't select french in laguage menu, it doesn't appear.

 firmware 1-5-1
bootloader 1.4.15
rf module 2.2.6
audio english & french 1.5.0


thanks

**Comment by bsongis-frsky** [comment]
Have you selected and installed the FR i18n pack (left panel)?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/eaa36967-27f0-4f3e-a43a-096b4696f602)

**Comment by Majestic63** [comment]
yes, of course

**Comment by Majestic63** [comment]
On the other hand, i check the i18n folder on FLASH, it is empty

i tried also to install spanish language, it is the same, only english avaliable  in the drop-down menu

it works well for audio
