### ISSUE TITLE
V1.5.0. RC2 latest Nightls,  range and steps at sourve VAR, ExtraTrim,  are differnet at mixer and output

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3424]
compare VAR  and Extra Trim

Each Steps with 5%  up, down per hand or per TimerGenerator

VAR Range +/-100%,  output ch17 to look at the us and %
Trim Range +/-50%   output Ch18 to look at the  us and %  <-- think this is the problem for the mixer output  at ch18

Test with  free mixer ch17, ch18  weight 100%
Source Var7       at Ch17   Mixer Output Steps are 5%    are Steps 26us
Source EtraTrim1 at Ch18 Mixer Output Steps are 2,5% are Steps 13us

Think 5 % Step should be 5%Stepd  and not depending of the Range  at Var or Trim

With 5% steps in the source (VAR or EXTRA Trim), 5% steps must also come out in the output via the mixer

regardless of the range of the source

![2024-02-13_135403 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/a9965060-5450-46bf-a93c-00be8481467f)
![2024-02-13_135328 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/ee9b7343-d6c4-42cc-8437-f045518a0ade)
![2024-02-13_135300 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/78ecf9f4-35f5-467b-ae66-8fbe76b9d1d6)
![2024-02-13_135223 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/e7ad9b02-4b68-467d-9c07-27e37ce91e92)

**Comment by bsongis-frsky** [comment]
Do you mean that "Custom ... 5%" for Trims should not take care of the range?
We need more precision, if I am not mistaken, we have smaller steps than 1% (the default range is 25%)

**Comment by hrenz** [comment]
If you set a range of 50%, i.e. from -50% to +50%
and set a step of 5%
then only +10 steps and -10 steps may be possible as a result.
and not converted steps depending on the range 

Why is that even converted to the set of range
so that the same number of steps always comes out? 

Example Range  10%  i.e. -10% to +10%
Steps 5%
This results in a total of 5 possible steps  -10 -5  0 +5 +10
and not 50 steps

**Comment by bsongis-frsky** [comment]
How do you do if you want Range=25% with 100 steps?

**Comment by hrenz** [comment]
Range 25% i.e. -25% to +25%
50/100Step are 0,5%

but you have programmed automatik so you got allways 100Steps depending of the Range, 
or not?

What will you do with Range 5%
i.e. -5% to+5% = 10%  / 100 = 0,1%  would be ok

**Comment by hrenz** [comment]
the other hand are the fix  us 0.5, 1, 2, 4, 8us

but selected Custom Steps are Custom Step in % 
or much better direkt in us

because  1us is 1us m its exakt 1us not more or less
 
but 1% is 5,12us,  and 0,1% is 0,512us

**Comment by bsongis-frsky** [comment]
Still needed?
