### ISSUE TITLE
Increase the numerical values ​​in the Ethos telemetry sensor menu

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#3425]
Hello FrSky team,
I own an X20S and a Pro and would like to receive number data via a DIY sensor using the telemetry function.
Now I have the problem that the value in the Telemetry Sensor menu is limited to 1,000,000,000. 
**Is it possible to increase this value** either by one decimal place (0) to 10,000,000,000.
I would like to transmit a **16x2bit (32bit) value** as a telemetry sensor value.

Thank you for your excellent work.
Best regards,
Torsten

**Comment by bsongis-frsky** [comment]
You need more than 4 bytes to send "10.000.000.000"!
Perhaps you could send 2 telemetry fields (from the same DIY sensor)?

**Comment by Satcomix** [comment]
> You need more than 4 bytes to send "10.000.000.000"! Perhaps you could send 2 telemetry fields (from the same DIY sensor)?

Hello Bertrand,
Thank you for your quick reply.
Unfortunately, it is not possible to cut the 16x2bit into 2x 8x2bit and transfer them individually as 2x DIY sensors, otherwise I would have already tried this attempt.
It depends on a decimal place 32bit = max.8,000,000,000
But I only get the display to a maximum of 1,000,000,000
Thank you for your excellent work, I am thrilled with Ethos and the X20Pro No.20
Best regards,
Torsten

**Comment by bsongis-frsky** [comment]
May I know the reason why it is not possible to send 2 different telemetry values?
Otherwise I see another solution, but it will need the dev of another feature (custom DIY with many sub-values)

**Comment by Satcomix** [comment]
> May I know the reason why it is not possible to send 2 different telemetry values? Otherwise I see another solution, but it will need the dev of another feature (custom DIY with many sub-values)

Hello Bertrand,
We consulted with the programmer again and came to a different solution to the problem. We have chosen a different bit sequence and now only need 24 bits, so 1,000,000,000 are of course sufficient.
FYI:
The background is the transmission of a telemetry value that contains precise information about the status of 16 switchable analog or PWM outputs. This value is used in a 32 button LUA to display the status of the buttons so that the user receives a concrete answer about the status in the model for security-relevant tasks.
Thank you for your work.
Best regards,
Torsten
