### ISSUE TITLE
VAR Actions don't seem ideal and could cause major problems

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3426]
I notice that if you have a VAR Action of e.g. Add 1% then so long as that condition is true the Value continues incrementing until it reaches the range limit. 
On the face of it that makes sense, however I'm not sure that we want that in practice.

For momentary type conditions of SI, SJ, LVU/LVD etc. or Edge conditions on LS this probably makes sense.

However there is nothing stopping a user speficying a persistent condition Action of a FM an LS or FS (without edge) etc.. 

However if the Function is Assign, then the reverse is true, I want a value assigned so long as I'm in a FM or while an LS or FM is true, however  Assigning a value to a momentary event such as SI/SJ, LVU/LVD or Edge Switches / FM is probably mostly useless.

I fear there is a significant chance users are not always going to get what they expect which could cause major problems.

Thanks

**Comment by Jedsters** [comment]
I notice there is a similar situation in Trims, although some actions such as FM have been removed there are many events which could result in a continual increase or decrease in the trim value, things such as 
Always On (when could this ever be needed), switch positions, FS and system events. 

Again, someone could easily think they could use e.g. FS1 for up trim and FS2 for down trim only to find that as soon as they press FS1 their trim reaches the limit before they have time to work out what is going on and how to stop and fix it. But again, we don't want them all removed, it just they need to test on Edge conditions, e.g. Edge FS1 etc.

**Comment by mawzthefinn** [comment]
I get your first item, the repeat behaviour is potentially dangerous when paired with a condition that is non-momentary, as it will quickly increment/decrement to the end of the range in that case. However this is pretty much inherent, so it's up to the user to use an appropriate condition for their goal. 

The second, for assign, I disagree with entirely. Assigning values does exactly that, it doesn't make the value that value so long as the condition is true (that is done by regular VAR values), it assigns the value listed to the currently active VAR line when it triggers. It's as much or more valuable with a momentary condition as with a continuously true condition. 


As to FS1/2/3, you would set your FSW's to Momentary if you want to use them as trimmers.

**Comment by Jedsters** [comment]
ok, point taken on the Assign. I was thinking more of if we Assign when e.g. SA is Up it's taking the value continuously from there so long as SA is up, but you could equally look at it as taking it just once when the condition becomes true.

So long as there is danger to non-momentary conditions could the user be protected?

Similar with my update re trims though, a user could easily think that pressing FS1 will give them one click of up trim rather than full up trim.

**Comment by mawzthefinn** [comment]
The way you were thinking of Assign is the functionality of a VAR Value line, not of a VAR Action. Actions are always persistent adjustments to the currently active Value Line. If you want a condition to provide a specific value only when held, that's a VAR Value, not an Action. 

The problem is how do you differentiate between somebody holding down a momentary switch to get continuous adjustment vs somebody incorrectly assigned a switch.

The FSW's for example can be either momentary (for a press = 1 click) or on/off (a press = ON) depending on your configuration in Edit model. FS1 can be configured so that a quick press gives 1 click of up trim.

**Comment by Jedsters** [comment]
Off the top of my head, you can check the model configuration to see if it configured for the FS to be momentary or on/off. 
Is there any justification for always on as an Action?

**Comment by bsongis-frsky** [comment]
Perhaps I read a little bit too fast the issue, but there are use cases where a VAR is used to setup a value and modify it like you do with a trim, using a switch. Actions are executed at the speed of trims, slow at the beginning, then faster & faster.

There is one issue open (for 1.5.1) which would add more functions
- functions which do maths but which don't modify the current stored value (only the result is different)
- functions which modify the current stored value

This willl allow more flexibility

**Comment by bsongis-frsky** [comment]
#3203

**Comment by JimB40** [comment]
Don't know if it is good for rising bug here but in 1.5 RC2 below given example behaves like that:
- when you short press trim (FIRST event) - value is increased or  decreased by some random value between 3 and 7
- when you press and hold trim (REPT event) - value is continually increased or decreased by 1 (proper behavior)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/8be2a0f6-1257-4ace-bbff-cdb1373462e4)

**Comment by bsongis-frsky** [comment]
@JimB40 I am a little bit annoyed. Your comment is right (it has been fixed the next day), but it is a little bit out of topic here!

**Comment by bsongis-frsky** [comment]
@JimB40 The comment added in #3427 would perfectly fit here, or better in #3203!

**Comment by bsongis-frsky** [comment]
RC3 is coming in a few hours. The server has worked the whole night and is compiling the simulators right now

**Comment by Jedsters** [comment]
The more I think about this the more I think that Actions, which are presumably designed to allow a user to change values while flying, should only change the value while a users finger is on the trigger/switch. Something which will immediately stop changing when a user notices they are loosing control and stop doing what they are doing.

I struggle to see a benefit for SA to SG as triggers. 
The momentary SH, SI, SJ, T1/2/3/4(/5/6) make sense.
FS only make sense if they are setup as momentary. 

S1/2/3, LS/RS as triggers, as pointed out above should only really be in the Value section rather than Actions (but fair game for assign values).

All other non-momentary conditions (Always on, LS, System Events etc.) as triggers are fraught with danger for the unwary.

However, things can't be as simple as that. All momentary switch triggers would need to be allowed to have an AND condition so that they can be overloaded. 
e.g. LSx is true AND SI makes sense as a trigger,
FSx  (when not a momentary) AND LVU makes sense. I suspect that e.g. FSx even as a momentary and LVU is not very useful, but is at least harmless.

**Comment by Toffs** [comment]
I understand Jedsters view, and can see the logic. However, I also don’t agree that we should remove the functionality as being suggested.
The ‘risk/danger’ for unaware users around non-momentary functions isn’t that big since if the Vars output is “continuously calculating” it’s very obvious to see / test, no?  The danger would be if it was hidden, but that’s not the case.


> There is one issue open (for 1.5.1) which would add more functions
> 
> * functions which do maths but which don't modify the current stored value (only the result is different)
> * functions which modify the current stored value

@bsongis-frsky 
I struggle with Repurpose Trims or using a custom trim mix in Vars because the adjust value is always tiny 0.1% increments. I don’t understand why this is, and have to always create a second Vars that multiplies the first by x10.  Is the above in 1.5.1 going to allow that multiplying factor inside the first Vars instead?

Better yet, could the Custom Trims be made to work with the adjustment values set to Corse or Custom to allow for trim adjustments in Vars of 1% (or larger) than 0.1% increments.  I can raise a new request if preferred :)
Many Thanks

**Comment by Jedsters** [comment]
Thx @Toffs my concern is that with a non-momentary action the range limit would be reached almost instantly exactly because it is always being recalculated. The good news is that we do have range limits which will hopefully limit any damage. 

My concern was further compounded in that I couldn't see any benefit to allowing non-momentary actions, maybe I'm missing something, is there a use case? When would you want a non-momentary switch to repeatedly perform an addition, multiplication etc. until it reaches the limit?

However, I do accept that the first 1.5.1 bullet condition mentioned does change things, there is now  a use case where e.g SA Down takes the output to 80% but doesn't modify the current stored value. If I'm understanding that correctly rather than an output of  100%  going down to 1% almost immediately it will just go to 80% and remain there, this could be useful. 

Although it does still leave the problem of non-momentary actions hitting the range limit very quickly for no benefit that I can see, for functions which do modify the currently stored value. As I see it, we know which conditions are momentary and which are not so this could be addressed (as above).

You are right in that we should all be testing before flying, but there are now too many permutations between triggers in mixes, Vars, Var Actions, LS to possibly be able to test every combination so at some point someone is going to miss something, flick a switch and end up with an unflyable model. 

I possibly don't understand your final paragraph, but Trims can be set as I understand you say, e.g. a Trim can be set to Custom e.g. 10% and each time it is triggered the trim will change by 10% of the Range, so if you have a Range of 100% then you will get jumps of 10% but if your range is 30% then jumps will be 3%. Apologies if I've misunderstood, no doubt Bertrand can assist.

**Comment by Toffs** [comment]
@Jedsters
> My concern was further compounded in that I couldn't see any benefit to allowing non-momentary actions, maybe I'm missing something, is there a use case? When would you want a non-momentary switch to repeatedly perform an addition, multiplication etc. until it reaches the limit?

I've thought about this over the last week.  I'm now convinced, you are spot on.  This functionality is confusing in it's end-goal purpose, potentially risky, and I cannot see when/why a user could benefit from these.  I'd love someone to give an example where non-momentary actions in a Var would be any use (because they calculate infinitely).

---

Separately:  Custom Trim in Vars having tiny 0.1% increments - I see you've actually raised this as a new issue, nice one!

**Comment by Jedsters** [comment]
@Toffs I believe the answer to your question lies in 1.5.1, as Bertrand describes above 
'functions which do maths but which don't modify the current stored value (only the result is different)' 
Here e.g. a multiplication on a non-momentary action would simply maintain a modified output value without interatively changing it.

However, IMHO I feel that non-momentary actions which do modify the current stored value can be identified and calculations should not be performed iteratively on them - there be dragons there. I suspect it wouldn't be too difficult to devise a not unrealistic scenario to demonstrate the pitfall. Sure, users need to test and make sure they don't do anything dumb in the programming of a model, but by the same token if you can see a potential pitfall, why not protect users from themselves. Ethos is now so powerful that there is no way I could test every combination in my model template. If everything works as I expect it to I believe I'm fine, it's just things like the above which are going to catch me out. 

Random example for the first paragraph:
You want an adjustable dual rate which you store in a VAR. This may start as 100% and then using an action of SG down you may multiply this by 0.8 to give 80% so long as SG is down - you don't store this just use it. I guess you could then use SI/SJ to adjust this 0.8 which is why you may want it in the actions section.
Forgive me, not the best example, just a theoritical example off the top of my head.

At least, that's my understanding of the 1.5.1. proposal.  ;)

**Comment by Jedsters** [comment]
I have an idea / proposal which I believe not only addresses my concerns above, but could actually be useful for the implementation of the  _1.5.1 proposal_ 'functions which do maths but which don't modify the current stored value'. It may not be perfect, but it appears at worst to be harmless.

As I see it, we have: 

- momentary conditions which integrate well with the _1.5.0 setup_ 'functions which modify the current stored value', but which would appear to have no useful function which I can think of in the _1.5.1 proposal_ 
- persistent conditions which are necessary for the  _1.5.1 proposal_ but would appear to have (almost) no useful function which I can think of in the _1.5.0 setup_ and indeed could cause major problems.  

It strikes me that this therefore drives the solution.

With the addition of the  _1.5.1 proposal_ there is going to have to be a way to distinguish between
- functions which do maths but which don't modify the current stored value 
- functions which modify the current stored value
in the VAR Actions.

So, if a user creates a VAR Action which is momentary, more of which below, then the action which is created for them is automatically assigned as a _1.5.0 setup_ action.
If a user creates a VAR Action which is persistent, then the action which is created for them is automatically assigned as a _1.5.1 proposal_ action.

Obviously if a user changes the type of action then it will have to be reassigned automatically.

This just leaves the question of what are momentary conditions and what are persistent conditions.

Momentary conditions:
- All actions which are defined with the Action Edge option
- SI, SJ
- FS1-FS6 when defined as momentary
- Trim positions 

Persistent conditions:
- Switch positions for SA - SH
- FS when not defined as momentary
- All LS which are not defined with the Action Edge option
- Flight modes
- System Events

Note: I don't believe SH can be regarded as momentary as how long it lasts depends on the user, it could also be very useful as for testing, e.g. to test a Persistent condition knowing that it will stop as soon as you release it.

I recognise that some LS may in fact be momentary even if not defined with the Action Edge option. If also defined with the Action Edge option then they should simply work as expected. If not defined with the Action Edge option then this is where there is a minor problem as they would be assigned to Persistent condition but in reality only last momentarily. One would hope that this would be identified when a user is testing their model setup, but failing that then the result should be harmless - a user would very briefly get what they expect (probably too quickly to even notice if it only lasts for 1 cycle), so it would at least be a benign problem of something having no effect rather than something having an unexpected effect. 

There is also the situation where an LS may not be defined with the Action Edge option but may be driven by a repeating condition, e.g. SI, SJ, T1-T6 etc.. I don't know enough about the internals of the code here, but my guess is that even these events would only last 1 cycle so not last long enough or repeat quickly enough for a user to notice, so also be benign. I guess the worst case is when there is a LS which is not defined with the Action Edge option but is driven by a repeating condition and has a minimum duration of e.g. 0.1s set. In this case the user would notice a VAR value which very quickly alternates between two values. But even here one would imagine that the user would very quickly release the switch and the problem would stop. I guess a similar situation could occur when a LS is somehow triggered by another LS which for some other reason repeats.  

I guess the last concern is how this integrates with 1.5.0. My  best thought so far (not ideal) is that if a user creates a Persistent condition that the action created is in some way assigned as a dummy 1.5.1 action so has no effect.

Of course all of this would need to be explained in the manual together with why it's being done. 

If you believe I've missed something, please let me know so I can see if I can assist with a solution. I've tried to consider all eventualities, but the disclaimer is of course that I may have missed something.

**Comment by Skippydi** [comment]
I think it is problematic to automatically increase a value if, for example, a switch is used as a trigger. A button may be useful for trimming, but I want to be able to influence the value of a variable with certainty. An example would be the possibility of changing the variable to adjust the GAIN value on a TD SR8 depending on the flight speed.

**Comment by hrenz** [comment]
V1.5.1 its like this now
its a Autorepeat  if there is no source at Value
No Autorepeat if there is a analog source at Value, you can reskale it.

[Var mit und ohne Autorepeat 001.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14513931/Var.mit.und.ohne.Autorepeat.001.pdf)

**Comment by hrenz** [comment]
but what we need is one time Preset Value for Start the Var
or preset with a sytem event startsytem

**Comment by mawzthefinn** [comment]
> but what we need is one time Preset Value for Start the Var or preset with a sytem event startsytem

Assign action with an edge trigger should do that.
