### ISSUE TITLE
Old model file doesn't convert on 1.5.0 nightly but does on 1.4.15

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#3428]
Armsoar youtube channel has a model template that they provide for DLG use.  They created it a long time ago and it loads into 1.4.15 simulator (last version of 1.4.x simulator available) without problems.  Trying to load it into nightly gives an error.

I rename the file to AS-DLG.bin for a shorter filename and then start the simulator to load the model.

On the screen:
Model load
invalid data

I don't see any differences in the debug log for 1.4.15 and 1.5.0 nightly.  The RFModule check failed likely is expected as both do that.

011145 ModelData::read('/models/DLG/AS-DLG.bin')
011145 ModelData version will be converted from version 0.0.9 to 0.0.51    (Note: on nightly, it says 0.0.9 to 0.1.11)
011145 ModelData will be converted from radio X10 to Twin XLite S
011145 Sentinel(RFModule) check failed

[AS-DLG.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14270333/AS-DLG.zip)

**Comment by agibson2** [comment]
It does load on the TWXLITES simulator on 1.4.15.
It does load on the X20S simulator on 1.4.15.

It does not load (invalid data) on either nightly simulator.

**Comment by bsongis-frsky** [comment]
We drop support of older versions, which is the date for this template? It would be good to update it!

**Comment by agibson2** [comment]
I got it from here...
https://www.youtube.com/watch?v=USNN0d6yIaQ

I guess I can post to their youtube that they need to load it into 1.4.15, save it(make a change), and then post it again.

**Comment by agibson2** [comment]
What is the oldest version of Ethos that will still convert?  Ideally he would import it into that in case someone is running an older Ethos and be more likely to work for a user (maybe they get a new radio that has been on the shelf for awhile and hasn't updated Ethos yet).

**Comment by bsongis** [comment]
I would post a file for 1.4.15 which will be supported in later versions

**Comment by LuHaGH** [comment]
> We drop support of older versions, which is the date for this template? It would be good to update it!

This is a really bad idea, cause there are many people who only update major releases.
There MUST be a way to fix the models after the upgrade to 1.5.X

**Comment by bsongis** [comment]
There is a way. Those (very old) models can be loaded in any 1.4.X version, or simulator.

**Comment by agibson2** [comment]
Clarifying how old might help ease the concerns.  How far back in 1.4.x can still be converted?  The model I had was created back in 2021 which was a very old version of firmware.

**Comment by bsongis** [comment]
Yes, very old. We don't discuss about 1.4.X here but rather 1.0.X ...
