### ISSUE TITLE
Minor bug: block bind when module state is off

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#343]
I was experiencing some issues when binding my accst receiver although I was pretty sure I was doing everything right.  When I realize, I was performing the binding with the tx module state set to OFF. This should not be possible as it is contradictory. 

![19BB2F7A-559A-45AD-8865-56F3C0211478](https://user-images.githubusercontent.com/25162166/119728283-3121aa00-be6b-11eb-90a4-ed153093cc3f.jpeg)

**Comment by Devil-IdT** [comment]
That has already happened to me. It would be nice to receive a corresponding message if you want to bind when the module is switched off.

**Comment by Hobby4life** [comment]
Or just not be able to bind if rf state is off.

**Comment by Devil-IdT** [comment]
Many roads lead to rome, you only have to walk one. ;)

**Comment by bsongis-frsky** [comment]
All buttons are now disabled when the module is OFF
