### ISSUE TITLE
Update of V1.5.0. RC2 Nightly  (12.02.) by hand does not work with the menu languages, only english possible

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3430]
Update of V1.5.0. RC2 Nightly (12.02.)
by hand does not work with the menu languages
X20S
The nightly download is a *.zip 
with firmware.bin  and all i18n languages.
copied the 4 menu languages into the Flash i18n (delete the old 4 languages before)
de.i18n fr.i18n, it.i18n, es.i18n
the firmware is copied to the root of the SD card

Then flash and boot, works
Announcement sounds are in German, works, ok
But now only the English menu language works, no other to select.

were is the Problem?
there are alle the lastest Files Firmware.bin and i18n

**Comment by mgsanna** [comment]
Hi Hrenz, if you look inside the Flash partition there is also a folder called i18n, to copy the files on it you have to power on your radio in bootloader mode... then it will copy to the partition.... 
instead when you install with suite and not manually, suite provide to install in sdcard or Nand and also in Flash automatically

**Comment by bsongis-frsky** [comment]
Let's wait for RC3 before closing this one, there is a fix, but rather for French, not German.

i18n files are associated to one and only one firmware

**Comment by hrenz** [comment]
Yes I know, I did it 
both drives Flash and Sdcard/Nand need the i18 folder and the *.i18n files inside
at Sdcard are all i18n Languages

Yes  I know, did it
inside the Flash partition there is also a folder called i18n, to copy the files on it
there I have only 3 or 4 Language I need de es fr it

and this are alle the same i18n files form the *.zip with the firmware.bin

After boot is sonly english possible
------------------------

But:
When I update the firmware and the 4 languages per Suite it works
the suite does exakt the same
copies all i18n to the sdcard
copies the same  4 i18n to the flash
copies the Frimware to the root for flashing and boot

---------------------
I checked the differences:
I think the Suite first delete both subdir at Sdcard and at Flash
and I only delete the file at i18n subdirs , but not the subdir itself

This could be the solution ??

**Comment by bsongis-frsky** [comment]
RC3 is online, please would you confirm there is an issue?

**Comment by hrenz** [comment]
Will test it tonight

**Comment by hrenz** [comment]
ok works , can be closed
