### ISSUE TITLE
ETHOS 1.5 ERROR SCREEN with X20S 1.5.0 RC2

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#3431]
hello
impossible to upgrade to 1.5.0 RC3

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6443591/52f15e09-04da-422d-8c83-759d8517e066

**Comment by bsongis-frsky** [comment]
I know you are all waiting after RC3 but please be patient, the server is still working on it!

**Comment by samsab1** [comment]
do you mean it's just a question of time?
