### ISSUE TITLE
Message "Sensor lost" after switching off the receiver voltage

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3432]
Hello, 
when I switch off the receiver, the message "Sensor lost" is displayed for all sensors in turn. However, this happens for each sensor individually. At the moment it is 16 times. I was not used to this before, when the message was only displayed once.
X10S Express 1.5.0 latest Nitgtlies

**Comment by bsongis-frsky** [comment]
But do you receive RSSI? If you receive RSSI the telemetry link is considered as alive

**Comment by bsongis-frsky** [comment]
RSSI is considered as lost after 2s of inactivity.
Perhaps your sensor has a longer delay?

**Comment by bsongis-frsky** [comment]
In RC4 it will be played only one time. But theorically it should be played 0 time!

**Comment by Wolepo** [comment]
I am currently looking for sporastic "sensor lost" messages. To do this, I have deactivated all message delays and, after a long wait, have switched on a sensor with a delay of 1 second. Yesterday evening I switched off the receiver and the many messages appeared. This can be reproduced.

**Comment by JimB40** [comment]
Agree agree. In quads' world we fly 4-5 minutest and replug pack.
 1 out of 5-6 times at that point I was getting 'Sensor lost' several times for each sensor.
 Seems there is no option to silence all of them.
 
 I can use old OpenTX trick and renamed wav for sensor lost warning but then in planes that fly long it will not work.
 
 BTW what is added value for user to inform that sensor is lost if I dont't know which one is faulty? :)

**Comment by bsongis-frsky** [comment]
Perhaps we could find a trick on the UI to show what is the last faulty sensor

**Comment by Wolepo** [comment]
Yes, that would be a good way to localise these sensors in sequence and adjust them accordingly

**Comment by Wolepo** [comment]
In RC4, all sensors are reported as lost one after the other (16 times) when the receiver voltage is switched off.
X10 S Express

**Comment by Wolepo** [comment]
Hello,
even in 1.5.0 Pre-Release, 16 sensors are still reported as lost when the receiver voltage is switched off. All sensors appear with --- in red.

**Comment by bsongis-frsky** [comment]
But how is the RSSI?

**Comment by bsongis-frsky** [comment]
Stopping the release process, this audio message should be played only one time, even if the RSSI is not lost.

**Comment by Wolepo** [comment]
Thank you.
