### ISSUE TITLE
Transferring the failsave setting for the SR6mini

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3433]
Hello,
I realised by chance that the failsave settings are not transferred in the new model with an SR6 mini. Although CH3 is set to -100%, the motor ran at half power. Here is a picture of the settings:
![screenshot-2024-02-14-36515](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/50c80eb4-d860-4f86-8fae-a9188da12d7d)

**Comment by bsongis-frsky** [comment]
Failsafe are sent every 10 seconds to the receiver, how much time have you been waiting?

**Comment by Wolepo** [comment]
Half a day

**Comment by Wolepo** [comment]
Sorry, I found the error myself. The setting was missing and so it was at 0%.
