### ISSUE TITLE
Bug 1.5.0 RC3 in the Curvature mix

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#3436]
the curvature mix of my glider models in 1.4.15 no longer works in 1.5.0 RC2 and RC3

To reproduce the problem: create a 2-aileron / 2-flap / T-tail glider on the simulator or X20S. 

Create a Curvature mix, assign an SD inter, move the inter, the visual of the curve on the right is bad.

This was not the case in 1.4.15.
PS: the Flaps mix behaves normally.

**Comment by mgsanna** [comment]
I can replicate as well it affect camber mix, butterfly with a switch assignment
the ouput is only 1% instead of the full possible
<img width="807" alt="Screenshot 2024-02-14 210830" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/79ebf5e8-c0e1-4af7-9c39-bde2af135eee">

**Comment by spoke2570** [comment]
I have to say that I am using vars as a source for my camber positions in a free mix. One mixer line per pair of servos. The conditional actions part even handles the slow up/down motion for various flight modes like flaps or butterfly. This tactic still beats the canned mixers in performance and low mixer line count.

**Comment by bsongis-frsky** [comment]
Good catch!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a5230d41-fd49-4a23-94ba-d87d7a6f72aa)
