### ISSUE TITLE
Trims not working.

### ISSUE THREAD

**Issue by grzegorzheldt** [FrSkyRC/ETHOS-Feedback-Community#3437]
Hi, 

I'm on 1.4.17 release on X20S.

I have discovered, that on one of my models, some trims are not working.
This model has rather easy configuration, which i'm attaching.

There are two channels and are driven by two mixers from Aileron and Elevator sticks.
In this configuration, trims are not working for both Elevator and Ailerons, while trim for Throttle is working as expected.

[airwingpro.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14285783/airwingpro.zip)

**Comment by mawzthefinn** [comment]
You don't have Aileron and Elevator Mixes, but 2 free mixes. Trims are applied via the stock surface mixers (Aileron, Elevator, Rudder & Throttle). Free Mixes do not include any trim function.

You need to apply Trims to each channel, or use the stock mixes properly configured and they will get added to the mix.
