### ISSUE TITLE
Models with Express LRS in 1.4.17 don't work with 1.5.0 RC3

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#3438]
I just get "Invalid data" errors with all of my models that were using Express LRS external module in 1.4.17 when trying 1.5.0 RC3. I have updated the ELRS LUA with the 1.5 branch version.

This is one of my models that gets the error: [m4 max.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14292231/m4.max.zip)

**Comment by bsongis-frsky** [comment]
Not sure it is linked to the external module

**Comment by bsongis-frsky** [comment]
It was the RSSI sensor. Fixed for RC4 which I will release later today
