### ISSUE TITLE
lua: method to change a var-value

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3439]
i'm really happy about all the enhancements & implementations of 1.5
The only thing i'm missing (apart from the already announced "companion") is a way to change vars by lua,
so that one could built a kind of UI to manage a bigger bunch of vars by a simple app.

i think it would be perfectly fine to read & write a var in  simple, straight way,
the value should only be applied to  the actual FM
(same like in otx)

.. something like this:

gvar = system.getSource({category=CATEGORY_VARS, name="v_expo"})
gvar:value(42)

"the value" should  be checked for plausibility, so that in case it exceeds configured limits it will be changed to the max/min allowed value

maybe something for 1.5.1 ?

thanks & regards
udo

**Comment by bsongis-frsky** [comment]
Let's be honest, Companion is a big one! If you compare OpenTX Firmware LOC with OpenTX Companion LOC, you will have an idea of the amount of work needed. Once that's said we won't use Qt / C++ but a more modern Web framework.

**Comment by strgaltdel** [comment]
... yepp,
and personally I would expect a "simpler companion" with more or less basic functionality at the beginning, 
that grows over time, as Ethos has done in recent years,
and a product progress that is restricted by limited development capacity on the one hand 
and the boundless craziness of users on the other (-;

So I thought I'd add my second most important request before the development team goes into indefinite "companion" retreat, only to surprise us at Christmas with the results of their efforts (-;

I am sure that sooner or later you will overwhelm us with a PC front end...
I don't want you to rush this in any way

but perhaps a small "var method" can be expected sooner ((-:

**Comment by bsongis-frsky** [comment]
Ready for RC4

**Comment by strgaltdel** [comment]
wow!

I really didn't think you would realize it so quickly!


merci beaucoup!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/19ddb05e-1909-486b-b82d-5a97998818f7)
