### ISSUE TITLE
Feature request:  Play Backround Music

### ISSUE THREAD

**Issue by Lenny970** [FrSkyRC/ETHOS-Feedback-Community#344]
In my OTX programs I use the "Play Backround Music" special function extensively for custom timers for sailplane competitions.
Can we get this special function added to Ethos also please??

Thanks,
Lenny

**Comment by mawzthefinn** [comment]
Yes, this would be a nice improvement for sailplane and pattern/F3A/IMAC use, as well as for fun

**Comment by mawzthefinn** [comment]
Also in #773 which has more discussion. Closing this request in favour of the more active issue
