### ISSUE TITLE
LS |delta|>X no longer works with Delay before Active > 0.0s in 1.5 RC3

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3441]
LS |delta|>X no longer works with 1.5 RC3

Create an LS e.g. 
Fn |delta|>X
Source Pot1
Value 5% 
Check interval 500ms
Min duration 0.1s (just so we can see it)

Now move Pot1 quickly by more than 5% which should trigger the LS, but it doesn't.
Slightly curious - I think the first time I did this and moved the LS the LS did very briefly go green, but after that it doesn't.

Thanks

**Comment by bsongis-frsky** [comment]
Are you sure? I am on RC4 but I haven't changed anything in this area!

**Comment by Jedsters** [comment]
Ah, I thought I'd included all the necessary elements, try adding Delay before active of 0.1s
Apologies for the omission - I try to recreate with the minimum necessary options but overdid it!
This used to work but doesn't now.

**Comment by agibson2** [comment]
I am using this for DLGs to disable zoom mode when I push over at the top.  That is still working for me in RC3.

This is triggering for me.

LS
Fn: |A| > X
Source: Elevator
Value: 10%
Min duration 0.1s
Delay before active 0.1s

**Comment by bsongis-frsky** [comment]
I wondered why there would be a difference between 1.4 and 1.5 on this topic and I don't see much difference. Try to setup a 0.2s delay on 1.4 and you will get exactly the same result

**Comment by Jedsters** [comment]
Something is very odd here. I just tested 0.2s on RC3 using exactly the same as above and the LS did not trigger. So I tried 0.1s and still it did not trigger, so I tried 0s and still it did not trigger, i.e. my original description!! 
The only thing which has changed is that I charged my tx over night!!!

What I am trying to achieve is I want the tx to play the value of  e.g. S1 after I have moved S1 more than a trivial amount, however I don't want the tx to play the value of S1 if the VAR (the examples above are simplified) changes only as a result of a FM change or a switch change. Hence the need for a delay - so it doesn't pick up when the change is just due to a change of FM.

**Comment by bsongis-frsky** [comment]
Testing done: delay=0.2s, then delay=0.1s, then no delay. 
It works perfectly here!

**Comment by Jedsters** [comment]
So why doesn't this trigger? 
https://www.dropbox.com/s/cki4manawpkb23x/VID_20240216_100903.mp4?dl=0

**Comment by bsongis-frsky** [comment]
A part of the solution for you?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d07cc7ff-3b44-4a9f-83a2-5f06030aad00)

**Comment by Jedsters** [comment]
But having charged my tx (which I struggle to think explains the problem) I can no longer even get |delta|>X to work regardless of delay as per the video.

**Comment by bsongis** [comment]
I have checked your video. I have replicated the same here and  my Logic Switch works.
Where do you use this Logic Switch, here it is linked to nothing

**Comment by bsongis** [comment]
Now I have linked it to a PlayAudio function. It still works perfectly, my file is played on due time

**Comment by Jedsters** [comment]
OK, I am back to the updated problem with it not working with delay of 0.1s  - it now works with delay of 0s. The same as reproduced by @agibson2 I really shouldn't play around late at night! Ignore the video. I'd forgotten I'd been playing late last eve.

You are right that I could possibly (I've not checked) bypass part the problem by means of additional LS, however I already have over 60 LS defined and I'd rather not waste more and have to add another LS for each time I want a |delta|>X condition.
It used to work with a delay of 0.1s in my template, it was after upgrading to RC3 and retesting various things that I found that it was no longer working. 
However what it won't help with it when I turn on the tx or load a model it will read out the value of every |delta|>X or similar type condition which is very indesirable.

**Comment by bsongis-frsky** [comment]
The delay of 0.1s will work at random, depending on how quick you will turn on S1. Not reliable at all. Because if the condition is not met at any moment during the delay, the logic switch won't become True

**Comment by Wolepo** [comment]
Hello,
I have found it.
See picture for my settings. Source(A) is a Vars, which can be increased in 1. If the function is set to normal, LS does not become active when the value is changed. Only when I set the function to inverted does the LS work as expected.
![LS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/4eb5f7b8-1363-4a41-b749-b51b5729ad4b)

**Comment by Jedsters** [comment]
Good spot. When you invert the function the LS becomes true, however if I then move my pot the LS briefly becomes not true. 
This gives a possible workaround of using Invert and then testing on !LSx but of course this indicates that there is a problem as Invert and !LSx should not work differently to Normal and LSx.

**Comment by Wolepo** [comment]
I also used potentiometer 3 as a source, and the LS only becomes active with the reverse when it is turned.

**Comment by bsongis-frsky** [comment]
I still see no problem when setting Min duration correctly

**Comment by Wolepo** [comment]
Min. and Max is probably due to the gear ratio
I always used maximum running time to achieve an active time of 0.2s. This has probably changed now. I now use min running time =0.2s and normally an active time of 0.2s is achieved. 
This solves the problem.

**Comment by Jedsters** [comment]
I am pretty confident that something has changed, however I'm starting to consider that in fixing another bug you may have changed and corrected the way this works. This caused my template to stop working as before so I may need to change it but that in itself isn't a problem. I've possibly been too fixated on my template not working assuming that something has broken rather than been fixed!
I've now spent too much time thinking about this and have confused myself so need to take a break from it to give my brain time to process all the information. Please can you leave this open for a few days while I try to convince that everything is actually
working correctly - albeit differently from before.
Thanks!

**Comment by Jedsters** [comment]
Although my testing is somewhat hindered because I'm getting erroneous messages as I don't believe #3363 has been completely fixed. I've updated that accordingly and believe it needs to be reopened.
Thanks

**Comment by Wolepo** [comment]
Setting the minimum runtime also corresponds to the logic of the designations. The changeover to this therefore requires some work.

**Comment by Wolepo** [comment]
Hello,
I have had another look at the comparative functions in the RC4 sim (transmitter connected to the charger). With the exception of |Δ|>X, a setting of "max. runtime" always results in a correspondingly long pulse. Only with |Δ|>X does it only work with min. runtime. It should therefore be decided what is correct. According to my current understanding, the Max. Running time setting limits the length of the active time, but what should Min. running time do?

**Comment by Jedsters** [comment]
Min Duration
Once the Logic Switch becomes True, it will remain True for the duration specified. If the duration is the default 0.0s, the logic switch will only become True for one mixer processing cycle, which is too short to see, so the LSW line will not go bold.

Although I suspect that should really say 'for at least the duration specified'

**Comment by Jedsters** [comment]
@bsongis maybe this partially comes down to me not fully understanding how this combination of conditions should work? If I explain my thinking, perhaps you could correct me?

With |delta|>X, Pot1, 10%, 500ms, Always on, Delay before active 0.1s, Min duration 0.1s

I'm reading that as if Pot1 changes by more than 10% within 500ms, then after that has continued to happen for 0.1s the LS should become true for at least 0.1s.
So if I rotate Pot1 from -100% to 100% smoothly taking ~1s to do so the LS should become active, but it doesn't. 

What adds to the confusion is if I now invert this I would read this as if Pot1 changes by less than or exactly 10% within 500ms, then after that has continued to happen for 0.1s the LS should become true for at least 0.1s. Now in this case with pot1 not moving the LS is mostly going to be true, it will only become false if pot1 moves by more than 10% within 500ms for at least 0.1s and in this case it does briefly become false as you rotate the pot! 

I know above you said that the delay of 0.1s could cause problems, so remove this to give 
|delta|>X, Pot1, 10%, 500ms, Always on, Delay before active 0.1s
I'm reading that as if Pot1 changes by more than 10% within 500ms, then the LS should become true for at least 0.1s. However that's not what happens, if you rotate pot1 very slowly the LS becomes true every 10% regardless of the 500ms. 
To aid understanding what I did was configure a screen to show Pot1 and LS2, that way I can see exactly what percentage I'm at and when the LS becomes true so I can see that for the second and third examples above the switch changes every 10%  apparently ignoring the check interval. 

Many thanks for your patience on this one!
