### ISSUE TITLE
Voltage sensor limits too low

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#3444]
Ethos 1.4.17. Have not checked 1.5.0-RC3 yet.

The maximum voltage for ISRM sensor ID `0A 0B50` is only 50.00v, which causes problems with a fully charged 12S LiHV setup (and sometimes even full charged 12S LiPo).

Same issue with the CRSF/ELRS Rx Batt voltage sensor (ID `08` in my models), except it is limited to 50.4v.

These limits should be at least 61 volts to accommodate up to 14S LiHv. Probably slightly higher for sensors that are not calibrated perfectly. I see some other voltage sensor IDs have 65v and 100v as limits.

**Comment by bsongis-frsky** [comment]
RBOX did already allow 65.0V
Now RBOX and ESC will share the same constant = 65.0V
Ready for 1.5.0 RC5
