### ISSUE TITLE
[1.5 RC3] TELEMETRY_ACTIVE Source do not get updated?

### ISSUE THREAD

**Issue by JimB40** [FrSkyRC/ETHOS-Feedback-Community#3445]
Doing some mor LUA tests.

X18S with ELRS module

1. Telemetery stream not present (EXT 0%)
![IMG_1412](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/3ebda1e7-3690-4758-ba10-17dbd443c2cc)
2. Telemetry stream present (EXT 100%)
![IMG_1413](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/7e9524d3-ba65-4b0b-92e1-8cd157c93bda)

Can I check in LUA if RC link is active (telemetry stream available)?
Source value reading from LUA for CATEGORY_SYSTEM_EVENT,TELEMETRY_ACTIVE is not updated to my test?

Although in ETHOS UI same event (System event, Telemetry active) gets highligted when telemetry stream shows.

BTW shouldn it be boolen (false/true)?
Strange readings anyway.
member (suppose to be int8) is 3.0 
decimal is 0 but value is 0.0 with one decimal.

**Comment by bsongis-frsky** [comment]
X16S? Should I understand X18S?

**Comment by bsongis-frsky** [comment]
I have a doubt, is your screen refreshed? 

(Perhaps you are used to OpenTX / EdgeTX where the screen is ALWAYS refreshed, which is already a problem on X12S, but which becomes even worst with the bigger resolution LCDs!)

Perhaps you could share your script (or parts of it) so that I can try to help if I find spare time?

**Comment by bsongis-frsky** [comment]
As a first test, and because your script doesn't look too much complex, I would call lcd.invalidate() in the wakeup() method, to mimic OpenTX behaviour.

**Comment by bsongis-frsky** [comment]
> member (suppose to be int8) is 3.0

Fixed (ready for 1.5.0 RC5), it should be an integer. Doc updated.

> decimal is 0 but value is 0.0 with one decimal.

Value is a number. 0.0 = 0 = False

**Comment by JimB40** [comment]
Invalidated. Printed also on console via serial port and value=0.0 all the time

**Comment by bsongis-frsky** [comment]
Bug. It should return +100 or -100

**Comment by bsongis-frsky** [comment]
Fix ready for 1.5.0 RC5

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/66d14051-f035-4481-8256-a133164384d4)
