### ISSUE TITLE
X20Pro Elrs Lua wrong Packet Rate

### ISSUE THREAD

**Issue by xbutz** [FrSkyRC/ETHOS-Feedback-Community#3449]
I have the following problem:

If the packet rate is set to 500 Hz or F500 / F1000, the script does not accept the value. 
If you go back one step, the packet rate D250 is displayed. 

Transmitter X20Pro Ethos 1.4.17 Eu 
Elrs Modul Happymodel Es24tx Slim Pro V3.3.2 Eu Lbt

**Comment by bsongis-frsky** [comment]
Problem in the script or Ethos?

**Comment by xbutz** [comment]
Hello Bertrand,
unfortunately I can't say that. 
Ethos 1.4.17 otherwise runs error-free.  
The Multumodul+script also runs error-free with my Irange irx4lite. So it doesn't seem to be a matter of ethos per se. 
Is the baud rate of the module interface possibly limited?  With EdgeTx there was an option under hardware to increase the baud rate.  

The script seems to start properly, if you go into the module setup and change the packet rate from 250 Hz to f1000, the value is not adopted and D250 is displayed. 
A new script download and reinstallation on the X20Pro was unsuccessful.

**Comment by Target0815** [comment]
@bsongis-frsky 

The LUA script is IMHO ok. All packet rates can be selected/set on an X18S with the same ELRS TX module.

Could it be that the serial interface of the X20 Pro is slower than on the X18S?

**Comment by xbutz** [comment]
Are there any findings yet?

**Comment by xbutz** [comment]
@bsongis bsongis-frsky

Hello, is there any news about the problem?

**Comment by bsongis-frsky** [comment]
You will have the possibility to switch to 921K instead of 400K for the ELRS baudrate
But it has been implemented / tested on 1.5.1

**Comment by xbutz** [comment]
@bsongis 
After updating to 1.5.1 and installing the new Lua script, the maximum packet rate is D250. 

How do you switch to 921k?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ec90863b-d3d5-4a9e-b80b-3b0f379f1dde)
