### ISSUE TITLE
Slow down/up function with Flap to Elev mixe

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#345]
EThos 1.07 with X20

Set a 3 switches position with flaps output and slow down and up for about 3s to slow down realistic flaps.
With the FLAP - ELEV ,  the mix do not use the slow down / up for the ELEV position and so we could not change
the Elec position within the same time

Thanks

**Comment by mawzthefinn** [comment]
USe the Flaps output as the source of your flaps->Elevator mix and it will work correctly

Using any other source isn't mixing flaps to elevator, but another input to elevator and therefore lacks all the Flaps processing,
