### ISSUE TITLE
no LUA scripts on tandemXE

### ISSUE THREAD

**Issue by robertnijhuis** [FrSkyRC/ETHOS-Feedback-Community#3450]
I'm having a problem installing lua scripts on my Tandem XE. I have an SR10+ and want to install the LUA scripts. Now I have followed the instructions of the TXT file and installed the files on the SD card, but when I restart the transmitter I do not see the scripts in the system menu.

**Comment by strgaltdel** [comment]
did you install the ethos scripts ?
can the scripts be found in a subfolder of /scripts ?

btw
.. the most common error in the german forum is, that the user didn't enter the second system page (-;

**Comment by robertnijhuis** [comment]
I copied it into the scripts folder. I also looked at several pages, but after info in the system menu there is nothing, I only have two pages there.

**Comment by strgaltdel** [comment]
the script path can be configured on radio or sdcard
( system settings)
this was set properly ? 

the ethos  lua scripts were these?
https://www.frsky-rc.com/archer-plus-sr10/

**Comment by robertnijhuis** [comment]
The scripts come from the FRsky download page. I also tried putting the scripts in multiple directories

Uploading WhatsApp Video 2024-02-15 at 16.33.00.mp4…

**Comment by robertnijhuis** [comment]
![WhatsApp Image 2024-02-16 at 19 30 16 (1)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/5885fde8-afe3-42d0-ab98-2f9158be88ec)
![WhatsApp Image 2024-02-16 at 19 30 16 (2)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/cc000e15-5a13-4a32-a077-1937c31851d1)
![WhatsApp Image 2024-02-16 at 19 30 16](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/6ad7ba59-6d0e-47b8-a026-29eb03f7bf69)

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/6d632ba3-c180-4fa4-aeba-7f007fdb53aa

**Comment by strgaltdel** [comment]
i dont have the xe, but suggest its the same like x18s..

your files are copied to the wrong storage!
there is a flash and a nand storage

please add a /scripts folder in nand storage
(in case you connect the tx in bootloader mode, you'll see two volumes, the nand one contains the most folders...)

then copy the sxr_ folders with the main.lua into the scripts folder of the nand storage

reboot the tx, so that the luas can be registered at boot

**Comment by robertnijhuis** [comment]
Ok, so in my file manager in the XE I see Radio and flash. When I connect it to the Ethos suite, I see 3 storage folders: Flash, SD and Radio. The folder with the most folders is the radio folder. When I put it in there I can't see them either. I have now tried the folder on all three storage types but can't see anything.
![WhatsApp Image 2024-02-16 at 19 54 02](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/db92731b-7439-4196-b4f8-1587b82c6ae8)
![WhatsApp Image 2024-02-16 at 19 56 12](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/22a822c2-a7ba-4538-9be5-f164b095b63b)
![WhatsApp Image 2024-02-16 at 19 56 39](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/3be27d9a-dc1a-44d2-9949-9ed271bef535)

**Comment by strgaltdel** [comment]
ok,
so "radio" is the nand, and "sd" sdcard storage
i dont see any scripts folder on "sd" !?

so please ensure, that scripts are configured to "radio" as mentioned above
(you didnt made a screenshot of this config item)

did you ensure that there is a main.lua within the folders?

**Comment by robertnijhuis** [comment]
just a current screen shot, now a script folder on each storage and you can now also see that the main lua folder is also there, but no result
![WhatsApp Image 2024-02-16 at 20 43 03](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/73497333/5d8ef143-9b37-46b9-9328-0994d3cddaec)

**Comment by robertnijhuis** [comment]
problem solved thanks to a member on Facebook. This is the solution;
_**`Had this issue with my X18 after an update. It read scripts from the wrong location. Go to settings, general, storage location, scripts - this should be set to «radio».`**_
Arvid Bjerre thanks

**Comment by strgaltdel** [comment]
glad you sorted it out,

.. but i told you twice to cross-check this parameter setting and send a screenshot (-;

.. happy flying
