### ISSUE TITLE
SD card not formatted in Windows - X10S Express

### ISSUE THREAD

**Issue by steffku** [FrSkyRC/ETHOS-Feedback-Community#3452]
When i connect my X10S Express to my laptop (Win11, USB 3.0) in Ethos suite mode, i cannot access the sdcard. Windows doesn't recognize a valid file system (sdcard not formatted). So Ethos suite doesn't work either. Same behaviour in bootloader mode.

I read that this may be caused by a driver issue on Windows. I tried several potential fixes, but none of them fixed it.
I also tried another laptop running Win10 with USB 2.0. Same problem here.
When i use EdgeTX on my X10S Express i can access the files without problem.
Is there a fix that solves this problem finally?

**Comment by bsongis-frsky** [comment]
Which version?

**Comment by steffku** [comment]
All versions that i tried. Which means at least all 1.5.0-RC versions and the latest stable version. Maybe it ist really a Windows driver issue. But i have no such issues with EdgeTX.

**Comment by steffku** [comment]
Maybe this also related to this issue: #2113. But for me none of the suggested solutions worked out.

**Comment by steffku** [comment]
Just want to provide some more information:
If i connect my X10S Express to my PC in Ethos Suite mode i get the additional devices marked yellow in the attached image.

![X10S Express devices](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/71893041/a7a81039-9080-4a14-8af0-900180beb9c8)

The composite device contains the input device and the mass storage device.
The input device is needed from Ethos Suite to detect the X10S Express.
The mass storage device provides the sd card.
The drivers used for mass storage and sd card are the same as used with EdgeTX.
Ethos suite recognizes the X10S Express but it cannot acces files on sd card.

![Ethos suite](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/71893041/fffb0647-cb91-4d00-89d2-3fb3eacef48d)

![Ethos suite missing drive](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/71893041/32dc9e73-3114-46f7-9656-d76196bf3e2e)

**Comment by steffku** [comment]
That's what it looks like in usbdeview.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/71893041/b898c85b-114e-4815-9290-c4cce51e74f5)

**Comment by strgaltdel** [comment]
is this a win home or a pro edition?
i've the feeling that there are significant more issues from "home" users, 
just an idea ...

any specific entries in the win system log?

did you try to start suite in admin mode?

**Comment by steffku** [comment]
It is Win11 Pro.
I also tried to start suite in admin mode without success.

How can i find those entries in the system log?

The problem is that the SD card appears as not formatted in Windows. So i cannot access files via file explorer either.

There are some guys that used the Zadig tool and replaced the driver with libusbk or winusb driver. But in my case this doesn't help. Don't know if i used the tool correctly.

**Comment by steffku** [comment]
I forgot to mention that i also tried an older Notebook running win 10. Same problem here. Could this be a hardware defect in the X10S? But the X10S itself works without problems. And with EdgeTX i can access the files on the sd card in Windows.

**Comment by steffku** [comment]
Hmm, no solution here? It seems that nobody else has this problem. It's really strange.

**Comment by strgaltdel** [comment]
" And with EdgeTX i can access the files on the sd card in Windows."


the only idea i have would be to make a backup,
format the sdcard 
and restore the data

did you try another card ?

btw
it seems it's a "singular event",
not an ethos issue in general
i do see a german UI,  it may be worth to discuss it in the "engel forum"

regards

**Comment by steffku** [comment]
I tried several cards. Some cards couldn't be read by the transmitter. But most of the cards could be read by the transmitter but not by windows when the transmitter is connected via USB.
I read that Kingston cards should be used. At the moment i don't have one.
Are there any specs for formatting the card? Filesystem, blocksize...?
Maybe at the end it is an hardware defect, but it is very strange, that everything works fine with EdgeTX.

So should i open a discussion at the engel forum?

**Comment by steffku** [comment]
Problem could bei solved. I was able to format the sd card placed in the X10S express and connected via USB in Ethos suite mode with this tool [klick](https://www.chip.de/downloads/SD-Formatter_72605634.html). Now, i See only 1GB when connected via Ethos suite mode nstead of 2 but that 's OK.
