### ISSUE TITLE
'Trims to sub trims' must take independent trims into account

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3453]
1.5.0 RC3

Test conditions:
Elevator trim mode = Independent per FM
Elevator sub trim = 0%
FM Normal - elevator trim = 0 (0%)
FM Flaps Half - elevator trim = -4 (-1%)
FM Flaps Full - elevator trim = -8 (-2%)
 
Activated ‘Trims to subtrims’ in FM Flaps Half. Resulting trims:
Elevator sub trim = -1%
FM Normal - elevator trim = 0 (0%) [This seems wrong, expected -1%]
FM Flaps Half - elevator trim = 0 (0%) [This looks correct, trim moved to sub trim]
FM Flaps Full - elevator trim = -8 (-2%) [This is wrong, expected -2% to change to -1%]

If you select Independent trims per flight mode, then if you activate ‘Trims to subtrims’ in one flight mode, then the independent trims in the other flight modes will be wrong. You have to compensate for the new subtrim setting in the other flight modes.

**Comment by bsongis-frsky** [comment]
Disagree here. If you really need this, your trims should be linked together.

Scenario : you have one FM for flying in the back and you want to have trims specific to this FM
=> when you trim the "Fly on the back" FM, you don't want to move the trims of the Default FM
=> when you trim the Default FM, you don't want to move the trims of "Fly on the back" FM

**Comment by bsongis-frsky** [comment]
Once that's said, I am not sure that with trims linked together, your scenario will behave properly, but this can be fixed.

**Comment by lthole** [comment]
With the new Custom trims with linked behaviours, I cannot see myself ever using the ‘Independent per FM’ mode. However, it should work correctly. 

If the independent trim in one FM is transferred to Subtrim, it is clear that the trim in all other FMs will be affected and therefore should be adjusted by the subtrim amount.

**Comment by lthole** [comment]
Maybe ‘Trims to sub trims’ should only by available in Easy mode.

**Comment by lthole** [comment]
This has actually been fixed.
