### ISSUE TITLE
Elevator has differential even with only one output channel.

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3454]
Ethos 1.5.0 RC3

The Elevator mix has the Differential parameter even with only one output channel.

**Comment by bsongis-frsky** [comment]
It is used for up / down weight.
The name is not perfect, could be changed in 1.5.1

**Comment by Jedsters** [comment]
So long as it is used for up/down weight, then a similar justification could be used to add a 'differential' line to the rudder mixer, especially for those models with a side hinged rudder. 
That would then make the Ele and Rudder mixers for V-Tail and T-Tail the 'same'.

Now that the V-Tail and T-Tail Ele and Rudder mixers are the 'same' that simplifies changing between V-Tail and T-Tail in the Edit model as you no longer need to change / reset any mixers, rather just 'inverting' one of the Rudder channels.

When changing from T-Tail to V-Tail all you need to do is add Output2 to Ele and assign the Rudder Output channel to it and then add Output 2 to Rudder, assign the Ele Output1 channel to it and 'invert' one of the channels (we can't know which as this depends on mechanical setup, so the user may have to swap this around however this is done).  When changing from V-Tail to T-Tail you can remove Output2 from the Ele mixer and Remove Output2 (the inverted one) from the Rudder mixer.

All done without resetting any mixers as mentioned in #3358 
Also see #3529

Thanks

**Comment by lthole** [comment]
I imagine there could be situations where you want asymetric travel, but I would use a curve in that situation.
