### ISSUE TITLE
1.4.17 not showing external CRSF TX unit

### ISSUE THREAD

**Issue by VinceHogg** [FrSkyRC/ETHOS-Feedback-Community#3457]
After updating from 1.4.13 to 1.4.17 the external CRSF unit does not show up in the config screen. If powered and connected the CRSF RX will show. Have tried flex and FCC versions and they are the same. Tried 1.5.0 and older versions and they are ok. All other firmware and lua on the radio are latest at this date.
My equipment-
X20s
CRSF micro tx on 6.19

Reason for updating was to try to resolve RC disconnecting issues.

**Comment by Target0815** [comment]
Das ist kein Problem mit 1.4.17. Ich kann damit Crossfire auf einer X18S problemlos nutzen.

Der OP schreibt [hier](https://discuss.ardupilot.org/t/crossfire-rx-disconnecting-non-dma-serial/113189/12), dass es wohl ein Hardware-Problem wäre.

**Comment by VinceHogg** [comment]
Yes, a few hours after this post the TX seems to have failed completely. I left it up because with all other firmware versions it was showing and selectable. Its quite strange that if it was beginning to fail over the previous few days it would connect with other versions.

**Comment by mawzthefinn** [comment]
Closing off as it appears to be a 3rd party hardware failure
