### ISSUE TITLE
LS become true incorrectly once after model load

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3458]
This is following on from #3363 which has been closed as fixed and although it is partly fixed it doesn't appear to be completely fixed as of RC4.

Please see the supplied model from #3363.

I am finding that once I load the model with SC Up, then the first time of LVU both LS6 and LS7 become true when LS7 should not become true. If I then move SC middle and LVU again LS6 and LS7 become true when LS6 should not become true.
Curiously after this it all works correctly until you reload the model.

Thanks

**Comment by mawzthefinn** [comment]
You aren’t accounting for indeterminate states on initialization. Edges for example will potentially fire on startup as the state goes from indeterminate to actual.

**Comment by Jedsters** [comment]
I've possibly not explained it as well as I could have. 
What I'm saying is that I can load the model with e.g. SC Up. I can wait 5 minutes and then LVU but LS6 and LS7 both still come true. This is well after initialisation. Also if I then SC Middle and LVU again it's wrong.
Unfortunately the reason LVU is even part of the picture is specifically to get around the indeterminate values during initialisation.

**Comment by Jedsters** [comment]
To assist understanding, please see 

https://www.dropbox.com/s/2xlk3lmyj7l26b5/VID_20240219_091046.mp4?dl=0

The checklist screen shows the model has just been loaded.
I then swipe to a screen which shows the current value for Trim Throttle of 10%
You can also see Ref Wt is 50% and SF Wt is -40%
All values are stable
On the right you can see the ADJ REF and ADJ SF  LS

Note SC is initially Up

When I initially click LVU Trim Throttle increases to 11%, Ref Wt increases to 52%, SF Wt remains constant at -40%, this is all as expected. 
However you can see that both ADJ REF and ADJ SF briefly become true (green).  ADJ SF should not become true as SF WT has not changed!
As I repeatedly LVU, REF WT increases and ADJ REF changes to green while ADJ SF remains red all as expected.

I then move SC middle and repeat, again the first time I LVU both ADJ REF and ADJ SF become true even though you can see REF WT does not change.

Thanks

**Comment by bsongis-frsky** [comment]
The reason is simple, the diff is only evaluated when the condition is true
When the trim is pressed, it is therefore evaluated and the difference to 0 (value on reset) is bigger than your threshold, so the LS becomes true

**Comment by Jedsters** [comment]
If I understand you, I don't think that works in all situations.

If I want to play a value (VAR/Channel) after it has changed by more than e.g. 10% then I need a LS |Delta|<10% probably with a check interval of ---

However, this is a weight which only applies to one FM with, in the above example SC Up, so although I could add skip audio on startup, the VAR would still play when I change to the FM even though I've not directly changed it. 

I therefore need to add another condition in relating to a physical change such as LVU/LVD in conjunction with the relevant e.g. FM (as LVU and LVD are overloaded). 

I therefore end up with all of |Delta|>10%, SC Up, LVU OR LVD and a FM in a VAR (not in the simple example).

I don't see which condition I can remove and retain this function which used to work. Certainly I can do this in opentx.

It seems if I remove any condition I'm going to end up with unwated alerts.

The above is of course just an example, what happens with other Delta conditions with other sources such as telemetry triggered only in a specific FM etc.?

Thanks

**Comment by mawzthefinn** [comment]
You need an On condition that cannot be true during initialization, but can be at any other point, and use that as active condition.

One possibility is Telemetry status (IIRC there is now a system event for it), I use RxBat > 3.5V for this on older versions. Then it will only play when the model is alive and linked.

**Comment by Jedsters** [comment]
Thx Mawz I'll have a look at that and see if that suits in all cases, I do already have an RSSI>0 LS for other purposes I could reuse. Although I can't help wonder if I'm going to get unwanted alerts after telemetry lost etc..
Although I still feel something has changed and it didn't use to be this messy.

**Comment by Jedsters** [comment]
I guess I must be missing something. 
It appears the On Condition needs to be in the |Delta| LS otherwise it doesn't work. 
But if the On condition is in the |Delta| LS then you can't use any other condition there. This means we trigger when we change FM as the value has changed. If I move the on condition further up the chain then it no longer makes any difference. 

As an aside I used an On condition of Sticky, Always on with no trigger off and a delay before active of 1s, which in itself does work and come active after the specified time (tested at 25s), it just doesn't help. Alternatively if you're happy to just have the condition active when a model is connected (not much good for testing) and sticky of RSSI would work.

**Comment by bsongis-frsky** [comment]
In 1.4.X the function was evaluated even if the condition was false
I will revert this behaviour in RC5 (tonight)
