### ISSUE TITLE
1.5.x New feature: Add a 'Repeat' switch to Special Functions Play audio sequence

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3459]
Sometimes a pilot needs replay the audio file that was just played in his sequence list, instead of going to the next one. It would be nice if there were a 'Repeat' button option that could be added to the function for this purpose.

**Comment by Wolepo** [comment]
Hello,
It would be better if the file could simply be played again by a further pulse at the "Activate" input.
Scenario: with two 3-step switches and the corresponding AND links, 9 switch positions can be detected. Each AND activates a specific block in the SF with the "Play track" function.  If it were now possible to play this activated block directly, regardless of the sequence, you could play any track across the board as required. But it would be even more ideal if you could set a repeat rate (1x, every 1...120s) in an active block with the functions "Play file" and "Announce value". This would be useful for announcing telemetry values and their names, for example. I had already mentioned something similar.
