### ISSUE TITLE
Tandem XE stopped to power ON

### ISSUE THREAD

**Issue by alexandermikh** [FrSkyRC/ETHOS-Feedback-Community#3460]
Suddenly, after 4 months use, mine purchased in Sep 2023  Tandem XE FW 1.4.7 transmitter suddenly stopped to power on. Keep pressing on/off button makes it lighting blue without starting transmitter, both screens are dead. Pressing Enter and on/off buttons brings main screen to alive and displaying Bootloader version 1.4.3. Then TX can be connected to PC and is visible there with 2 discs.
Then problem turned to be very strange.
Made:
- installed Ethos Suite Win 1.4.15
- downloaded FW 1.4.17 and Bootloader 1.4.15.
Ethos Suite was able to install FW 1.4.17 replacing factory FW 1.4.7.
However,  try to install bootloader was not successful. After correctly selecting downloaded bootloader file, DFU Flasher suddenly makes message "Radio connection not detected", while MS Explorer still shows both transmitter discs, i.e transmitter well connected to PC. Screen picture  attached. Manual update by disconnecting USB cable also works OK with firmvare update but bootloader stays same 1.4.3. Connection of TX to PC in current off mode initiates charging, but discs not visible on PC.  My suspicious is that transmitter cannot start and further connection to PC problems are due bootloader not functioning, but I cannot reinstall bootloader. Re-installation of Ethos Suite on PC  did not help.
Please kindly advise if you know similar cases solved  and if  there is any way around to fix transmitter which cannot be switched ON.
Thanks!
![20240217_190835](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/160355247/bbc6e7af-edff-413e-99ba-1b8bfbe411de)
![20240217_190835](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/160355247/fca00cbc-6282-42b1-8c1e-ce7c941b760d)

**Comment by mawzthefinn** [comment]
Contact FrSky support for this. It’s more likely a hardware issue than a bug

**Comment by alexandermikh** [comment]
Good morning,
Thanks for your advice!
Could you please kindly help a bit more?

FrSky support not responding with 2 addresses as per my email header to them attached below.
May be you can advise direct email address or phone number of English speaking department?
They also should consider guarantee period coverage.
I am at troubles entering  F3A flying competition season with not working radio.

From: MIKHRIN, ALEXANDER 
Sent: Sunday, 18 February, 2024 21:45
To: sales4tech@gmail.com; frsky@frsky-rc.com
Subject: FrSky Tandem XE not power ON
Importance: High

**Comment by bsongis-frsky** [comment]
Have you installed the DFU driver?

**Comment by alexandermikh** [comment]
Dear Bertrand,
Thanks for your reply.
Do I understand correctly that DFU driver is installed by Ethos Suite when downloaded to my PC?
Please see attached screenshot where DFU Flasher picks-up file bootloader.frsk 1.4.15 ( suitable for XE) from local disc F. When I press button FLASH on DFU Flasher screen, message "Radio connection not detected" pops up, while both discs of my radio still visible on Windows Explorer.
Re-installation of Ethos Suite Windows 1.4.15 was also done, but problem stays the same. 
Is there another way to re-install DFU driver? 

 Thanks and looking forward to your advice.

![20240217_190835](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/160355247/b6f449b3-f579-45bd-bff4-6cab2ee9749a)

**Comment by bsongis-frsky** [comment]
Ethos Suite doesn't install the DFU driver, you have to install it!

**Comment by bsongis-frsky** [comment]
Problem fixed?

**Comment by alexandermikh** [comment]
Dear Bertrand,
Thanks for follow-up.
My Tandem XE  was repaired at Service Center in Germany. Of course, it took long time for shipping to Germany and return.
Wishing you nice day.

Mit freundlichen Grüssen / With Best regards

Alexander Mikhrin

From: Bertrand Songis @ FrSky ***@***.***>
Sent: Monday, July 1, 2024 10:08 PM
To: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: MIKHRIN, ALEXANDER ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [FrSkyRC/ETHOS-Feedback-Community] Tandem XE stopped to power ON (Issue #3460)

CAUTION: This is an external email. Do not click any links or open any attachments unless you trust the sender and know the content is safe.


Problem fixed?
