### ISSUE TITLE
V1.5.0 RC4 latest Suite Modell-Manager error

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3461]
the latest suite from tonight
Modell-Manager shows Errors at Modellname and Picture
only one or two are correct

![2024-02-18_140037](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/67c75c98-be3e-43af-98e8-8439dc909a95)

**Comment by Wolepo** [comment]
I have not done this and the displays are clean. Suite from 11 hours ago.
![Suite](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/f5634f9d-bdb0-43f2-b6ae-3f7b1c45061c)
