### ISSUE TITLE
Screen locked without special function activated or startup hot keys used. bug RC4, X20S bug

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3464]
I just put RC4 on my X20S. I then added a screen lock SF. I left the state set to Disabled so I could hunt for an appropriate logical to run it, and the touch screen is locked. The lock icon is showing in the top bar, the touch screen is inactive. The special function for this is showing in red font. 

The screen lock occurs as soon as 'lock touchscreen' is selected in the SF action dropdown menu. The lock is applied. 

A bit more digging and I found that when the "lock touchscreen" SF has a true active state (SFxx in green font shows) and the touch screen becomes active. When the "lock touchscreen" SF has a false active state (SFxx in red font shows) and the touch screen becomes inactive. 

easy to work around, but confusing.

**Comment by spoke2570** [comment]
If an LS is in a "disabled" state ETHOS should ignore that switch, altogether. 
Once the LS is in an "enabled" state ETHOS should then look at the active condition and apply the result. 

Past that the problem is merely in nomenclature: Does a TRUE "Lock touchscreen" special function mean the screen is locked, or active?

**Comment by spoke2570** [comment]
Also, should a model special function supersede the system level function, or no? Currently if an SF is used for screen lock it has priority over the system's Press and hold for 1sec page + enter keys method. 

I would expect that the system level switch should have priority and the SF should only affect this once it is asking for the same state as the system switch. 

ae if the system switch is used to lock the screen the SF should call for a locked screen before it can be used to unlock the screen.

**Comment by bsongis-frsky** [comment]
The enable state is inverted!
