### ISSUE TITLE
Model data corrupted in Ethos Suite

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#3469]
In the latest Ethos Suite (RC4), MacOS version, the model data shows corrupted for most models while all seems well on the SD card and on my X20S.

<img width="1161" alt="Scherm­afbeelding 2024-02-19 om 10 32 22" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/697422/10c647c4-4739-42df-93ca-057cfecbb181">

**Comment by Nicholas-Luoyi** [comment]
What's your ETHOS version?

**Comment by ahvink** [comment]
1.5.0 RC4

**Comment by Nicholas-Luoyi** [comment]
Will upload a new version to fix this in a few minutes. Please help to check.

**Comment by ahvink** [comment]
Fixed !
That was quick. Well done.
