### ISSUE TITLE
Feature request: add ‘keys’ to wake up options

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#347]
As far as power saving is concerned, Ethos give the opportunity of waking up the screen by using ‘sticks’ and ‘keys’, among other options. 

Can you please also add the option of waking up with ‘keys’, being the keys the hard buttons on the bottom part of the radio ( see picture below pls)!?

In a practical point of view, waking up with switches doesn’t make much sense since when you are flying (and most certainly use switch’s to control expo and dual-rates) you are unnecessarily waking the screen. While with keys options, this won’t happen with such frequency. 

Thanks in advance 

![E9D470F9-3CF9-474B-8A21-51C095DF2612](https://user-images.githubusercontent.com/25162166/119888578-6c84ad00-bf2d-11eb-8482-fc064fdba2fb.jpeg)

**Comment by skyfly74** [comment]
+1 that will be a great way to have longer battery time of use.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/119986857-a8b71c80-bfc4-11eb-8bab-17d83930bd6a.png)
