### ISSUE TITLE
Rename Invert parameter in Outputs to Reverse

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3470]
In Outputs a common need is to reverse the servo direction, so it makes sense to rename the Invert parameter in Outputs to Reverse. The term Invert has caused confusion with what happens at the Mixer level, please refer to #3418

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5a1c2a35-9977-48cc-9474-962e0fa57e1f)

**Comment by bsongis-frsky** [comment]
Good?

**Comment by lthole** [comment]
Excellent!
