### ISSUE TITLE
text to speach problem

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3471]
when I type in start it said stop

**Comment by bsongis-frsky** [comment]
It's not Ethos but a dedicated chip which speaks only English and Chinese.
Someone suggested to write "Staaart" :)

**Comment by williajgr** [comment]
That did work.  ThanksSent from my iPhoneOn Feb 19, 2024, at 1:44 PM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
It's not Ethos but a dedicated chip which speaks only English and Chinese.
Someone suggested to write "Staaart" :)
