### ISSUE TITLE
X20s not binding with RX6R in ACCST

### ISSUE THREAD

**Issue by VinceHogg** [FrSkyRC/ETHOS-Feedback-Community#3475]
I have 2 RX6Rs. Both will bind with my X20s in ACCESS. Neither will bind in ACCST.
X20 in running 1.4.17.

Firmware tried on the RX6R
ACCST D16
2.1.1
2.1.9 

Needed ACCST due to this issue FPort issue-
https://github.com/ArduPilot/ardupilot/issues/25546

**Comment by mawzthefinn** [comment]
Did you match LBT/FCC versions? ACCST needs the receiver firmware to match the radio version on those receivers. ACCESS autodetects

**Comment by VinceHogg** [comment]
If I understand it correctly, the X20 ethos is ready for ACCST D16  if selected in the radio settings. The firmware (FW-RX4R-RX6R-v2.1.1.zip) was downloaded today for the FCC RX6R, flashed successfully as far as I can tell.

**Comment by strgaltdel** [comment]
and the transmitter was flashed with the corresponding FCC FW too?

can you rule out swamping ?

**Comment by mawzthefinn** [comment]
Flex is for both 915 and 868 bands on the 900M section. As far as I'm aware it's LBT for 2.4G (could be wrong, you will want to test that)

**Comment by VinceHogg** [comment]
Ok thanks. My point of all this was to try to get Fport telemetry working on my RX6R to prove my theory that I had a faulty CRSF TX. As I said Fport hangs in ACCESS but someone said it will work with ACCST so I tried all this. As it turns out the RX6R wont do Fport anyway so it was a waste of time. Have just ordered an Archer RX to try until I get the CSRF working. 
Thanks for help.
