### ISSUE TITLE
lua: can't read VAR in RC4

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3476]
Please excuse my ignorance,
as a follow-up to #3439

I am not able to declare a "gvar source" in X20Sim RC4 like described in the issue mentioned:

(1)
declare a GVar with label=name= "Var1"
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/2d57df9e-2230-4c01-a3c1-53316b29a0e4)

(2)
then tried to read the value:

	local varLabel = "Var1"

	-- local gvar = system.getSource({name=varLabel, category=CATEGORY_VARS})
	-- local gvar = system.getSource({name=varLabel, category=CATEGORY_VAR})
	local gvar = system.getSource({name=varLabel})

	print("Var Value:" ,gvar:value() )

**error:  attempt to index a nil value (local 'gvar')**

at least by using the (unique) name I would have expected the var to be declared as a source 
so I have the feeling that I am on a completely wrong track

please,
could you give a quick example of how it should work?

thanks&regards
Udo

**Comment by Nicholas-Luoyi** [comment]
I find that get var hasn't been implemented in ETHOS

**Comment by strgaltdel** [comment]
OK, no problem,
What did Sidney Youngblood sing?

"...My heart is burning, I'm ready to fly.
All we can do is to sit and wait"

(-;

regards
Udo
