### ISSUE TITLE
Remote NFC panel failed to bind in 1.5

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3477]
It is not possible to bind the remote NFC panel via the Lua script.  It was tested with RC3 and RC4.

**Comment by Nicholas-Luoyi** [comment]
Which script are you using? NFC bind should be done inside Ethos and I remember there is no script to do that.

**Comment by RealTadango** [comment]
Do you have a new one or an older.one that came with a power switch? They are not the same but look the same.

**Comment by WhiskeyGolf** [comment]
I bought the individual NFC switch panel.  It already has the latest firmware on it.  By script I meant the RemoteNFC Script in Device config on Ethos.  There you get the message fail to bind.  Should the NFC Switch already work, or only in the final 1.5?
![196014D5-50AF-43D8-9AD6-E849412ED399](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/e7d462d5-5d7e-4fbe-acc4-f3f63785a35a)

**Comment by WhiskeyGolf** [comment]
I asked the seller today.  Apparently the product description was wrong and I probably had the old version.  I still thank you for your help and apologize for the inconvenience.
