### ISSUE TITLE
[RC4] SystemTool X-axis offset

### ISSUE THREAD

**Issue by JimB40** [FrSkyRC/ETHOS-Feedback-Community#3478]
There is 5 pixel offset to the right on X-axis when displaying LUA in SystemTool mode.
lcd.drawText(0,0,"Top left corner)
wll place is ar 5,27 on physical LCD 

While Y-axis offset is to display ETHOS top-bar, X-axis offset seems like bug.
In Widget mode (without Title) same lcd.drawText(0,0,"Top left corner) in LUA will display it at 0,0 on physical LCD.

**Comment by bsongis-frsky** [comment]
Ready for RC6
