### ISSUE TITLE
Radio freezes when unplugging USB, SD card corrupt

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#348]
I have noticed several times the following issue.

When connected to the PC in bootloader mode.
After disconnecting the USB cable from the pc.
Display keeps saying "usb plugged in" and freezes.. power button does not work.
Only thing to do is discconnect battery, and reconnect.
Now the radio wont boot, stays with Frsky Logo.
And not able to turn off again. Battery disconnect.
Also not possible to turn the radio into bootloader.
SD card is corrupt, FAT table? or something else?

Luckily i make backups after every change.

Only solution is:

Take SD card out, format on PC
Put SD card back in.
Start bootloader (When I boot normally again Radio hangs again).
Plug in USB.
Now format the SD card while inserted in the radio via PC.
Copy all content back to the SD.
Safely disconnect, and unplug usb cable.
Turn off radio, and start radio again. all is ok again.

One mistake, and you are off doing all of the above again.

**Comment by bsongis-frsky** [comment]
Do you safely disconnect the device or do you unplug the cable (with the teeth)?

**Comment by Hobby4life** [comment]
> Do you safely disconnect the device or do you unplug the cable (with the teeth)?

Yes, in windows in taskbar -> usb devices -> safely remove usb drive

**Comment by bsongis-frsky** [comment]
ok

**Comment by bsongis-frsky** [comment]
Wait I know. It doesn't freeze. Wait a little bit longer, it will start flashing.

**Comment by Hobby4life** [comment]
What is the timeout set?

**Comment by bsongis-frsky** [comment]
Just USB plugged notification.

**Comment by Hobby4life** [comment]
Ok I will see next time it happens.

**Comment by bsongis-frsky** [comment]
You wait another 10 seconds, it should be enough. I have noticed this problem from time to time and I have fixed it on new radios. If you know how to flash a bootloader please send me an email I will send you a new bootloader with the fix

**Comment by Hobby4life** [comment]
Hi Bertrand, I think that should not be a problem.

Where can I find your email adress? otherwise sent to me: hobby4lifenl@gmail.com

Thanks in advance.
