### ISSUE TITLE
lua: get var method, minor bug ("factor 10")

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3484]
First of all, thank you very much for the quick implementation!

For the most part, the method definitely works as desired
(Switching the various "action-dependent" values, no value overflow...)
very nice !

The only issue is that the value is wrong by a factor of 10 when writing and reading:

Var:
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/4edbbe2e-c8b5-4893-a721-8da5b1e39e94)

Code:

	local function paint(widget)
		local val=widget.gvar:value()
		print("GV Value",val)
	end

	local function create()
		local gvar =system.getSource({name="TST", category=CATEGORY_VARS})
		local sw   =system.getSource({name="SA",  category=CATEGORY_SWITCHES})
		return ({gvar=gvar, sw=sw})
	end

Output:
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/f5b1e2e5-7462-4714-ba84-249d6be2ff66)

thanks & regards

Udo

**Comment by bsongis-frsky** [comment]
Ready for RC6
