### ISSUE TITLE
Ethos Suite 1.5 crashed with Pre-Release 1.5.0 RC6

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#3488]
impossible to go ahead

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6443591/2ae7b59c-325f-4922-bfdc-17ca668cf6b9

**Comment by Nicholas-Luoyi** [comment]
Would you please post the crash file here?

**Comment by samsab1** [comment]
here it is

**Comment by samsab1** [comment]
[crash-20240223.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14383687/crash-20240223.txt)

**Comment by samsab1** [comment]
same pb
[crash-20240223.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14385408/crash-20240223.txt)

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6443591/68aeb60b-cb36-48a0-b2c6-c18a1a604648

**Comment by Nicholas-Luoyi** [comment]
This is strang. Would you please give me your e-mail? I will send you another version. BTW was it good in RC4?

**Comment by samsab1** [comment]
sam.sab@laposte.net

**Comment by samsab1** [comment]
without X20S connected

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6443591/77bee84f-5ffa-4901-a2f4-4743c5f38cc3

**Comment by Nicholas-Luoyi** [comment]
I have sent to you. And will continue tomorrow.

**Comment by samsab1** [comment]
hello many thanks, on a other win 11 pc, it works  --> RC6 installed now
thanks again

**Comment by Nicholas-Luoyi** [comment]
But I still need to confirm that if it was good with RC4 on your former PC?
