### ISSUE TITLE
Changing BT Name corrupts radio settings

### ISSUE THREAD

**Issue by GoodyearBiff** [FrSkyRC/ETHOS-Feedback-Community#349]
Well, I just changed the name of the X20S in the Wireless tab because it shares the same factory Local Name as the bluetooth airlink device.  The name didn't take immediately, and after 1 try it took a new name but did nit broadcast it. so I powered the radio on and off. Ethos then proceeded to corrupt many model data settings and randomly reset several radio settings to factory defaults. Someone might want to check this out. Would appreciate any help from the Ethos team. please. Issues so far: 

- Stick positions, sliders, pots: randomly reset to non centered positions
- Gyro: needed recalibration
- Checklist settings: randomly reset
- Flight timers: reset, random timers added
- Hardware: all analog calibrations reset
- main volume control: source reset
- Trim modes: random changed from fine to medium
- Preflight checks: randomly reset
- Date and time: 24-hour time toggled on, seconds toggled on, date advanced by 1 day and 12 min 30 sec. What?
- Display settings: shut down LCD-changed, language reset on start up-radio asked for a language, brightness control reset, sleep setting changed to factory
- Top toolbar: settings reset

**Comment by bsongis-frsky** [comment]
Reproduced! The allowed name is 11 chars, it should be 10
