### ISSUE TITLE
1.5.0-RC6 LUA lcd.getWindowSize() returns different information from 1.4

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#3493]
X18SE

lcd.getWindowSize() in 1.4.17 returns `472     288`
lcd.getWindowSize() in 1.5.0-RC6 returns `16912384        -335614529`

Seems to be fine in RC4 and RC5, but broke with RC6. Or is this covered in the segfault fix coming in RC7?

**Comment by strgaltdel** [comment]
maybe you could give some more infos, example code , which handler is callind the method?


i just tested some page designs on my x18,  4 different frames and always got correct size in paint&wakeup handler

**Comment by rburrow87** [comment]
Hi, yes sorry, I suppose more info would help. I spotted this with the Rotorflight 2 LUA scripts which have been functional until RC6, so I am assuming it's an issue introduced between Ethos 1.5 RC5 and RC6.

It gets called in radios.lua and in 2 places in main.lua. I am not the developer of the scripts, but I have been checking the Ethos release candidates to make sure all my models convert properly and that this LUA script keeps working.
https://github.com/rotorflight/rotorflight-lua-ethos/releases/tag/snapshot%2F2.0.0-20240218

**Comment by strgaltdel** [comment]
can reproduce on rc6 with the rf system script,
but seems ok on rc7 

could you try rc7 ?

**Comment by rburrow87** [comment]
All good in RC7! 💯
