### ISSUE TITLE
Analog filter ON/OFF An improvement would be to have the filter model specific.

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#3495]
Currently a system setting.

Reason is that if you fly fixed wing you want the analog filter set to on but for models with a flight controller, Betaflight, INAV etc the filter should be set to OFF

**Comment by pstasek** [comment]
It is already model-specific. You can set it to Global/On/Off setting in the Edit Model menu.
