### ISSUE TITLE
Trim values are announced incorrectly.

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3496]
Hello, 
if trim values are announced from the trimmer menu, they do not match the value display, see picture.
Instead of 96%, "984" is announced. What value is this?
![Trimmungen](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/815c8b0c-925d-4551-9671-2174585f8a78)

**Comment by hrenz** [comment]
its not %  its us
96% are 984us

**Comment by bsongis-frsky** [comment]
It should still play % I think

**Comment by Wolepo** [comment]
Yes, it should play 96%.

**Comment by bsongis-frsky** [comment]
This one has been fixed, no?

**Comment by Wolepo** [comment]
Yes, it was fixed a long time ago
