### ISSUE TITLE
1.5.0 RC7 - Stabilization receiver wizard Gyro gain output settings

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3498]
Quote from manual:
Gyro gain adjustment of CH13: When the the value of CH13 is in the center, the gain is zero. The gain increases
as the value get bigger. Until the value is ±100%, the gain reaches maximum.

In my opinnion, the Gyro Gain channel should be configured to be from 0% to +100%, not -100% to 100% by default as it is right now. I'm setting these values in the Channel Output: "Min" is at 0%, "Max" is at 100%, "Center/Subtrim" is at 50%. 

Is this something that can be added to the Stabilization receiver wizard, please?

**Comment by 4qr1hu9n7** [comment]
Very nice idea. I personally got caught on one of my flights. I accidentally turned to dial down to -100 % and was wondering why is the plane totaly out of control on the elevator .It resulted in a crash. I learned my lesson. But you suggestion is totaly valid.

**Comment by hrenz** [comment]
You have to set at ch 9 or ch13 Gain 50% and Offset 50%
so you have 0 to100% Gain with the Poti

**Comment by 4qr1hu9n7** [comment]
Good morning. Oh.I didn't know that. Thanks 

⁣4qr1hu9n7​


-------- Original Message --------

**Comment by pstasek** [comment]
> You have to set at ch9 or ch13 Gain 50% and Offset 50% then you have 0 to100% Gain with the Poti and Potiposition middle ist 50% Gain for beginning

This is the other way to achieve the same... 

However, it would be nice if a wizard configured the model like that for us to avoid confusion ;-)

**Comment by hershg21** [comment]
Why not use your curve set it to 2 points 0 and 100. and you should not have any of those issues.
