### ISSUE TITLE
Throttle cut ( overide function)

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#35]
Horus x12s v0.0.18
No overide function in special functions.
Throttle cut is very basic and important function for all powered models (electric/gas). And easiest way is to do it with overide... Also overide function is important when using headtracker for fpv. With overide it simply sets input to fixed value.
Best regards,
Kristjan

**Comment by bsongis-frsky** [comment]
This should be done in the mixer. You can setup a mix in the last line with a REPLACE function, which will do exactly what you need. It will be better than having mixes in functions
