### ISSUE TITLE
Which RPM sensor to use for gasoline engines?

### ISSUE THREAD

**Issue by robertobrazill** [FrSkyRC/ETHOS-Feedback-Community#3500]
I use a dyi sensor but it fails very quickly. Does FRSKY have a specific product?

**Comment by yak-54** [comment]
Frsky gas suite 

https://www.frsky-rc.com/product/gas-suite/

**Comment by bsongis-frsky** [comment]
@robertobrazill Yes, the gas suite should do the job!

**Comment by yak-54** [comment]
if like me i just needed of ICE engine frsky rpm sensor will do 
just get one off theses https://www.frsky-rc.com/product/rpm/
have read here what did to get it to work

https://www.rcgroups.com/forums/showthread.php?2884780-IC-engine-and-FrSky-smartport-RPM-sensor-A-coil-works%21-A-capacitor-works-better%21

**Comment by robertobrazill** [comment]
> if like me i just needed of ICE engine frsky rpm sensor will do just get one off theses https://www.frsky-rc.com/product/rpm/ have read here what did to get it to work
> 
> https://www.rcgroups.com/forums/showthread.php?2884780-IC-engine-and-FrSky-smartport-RPM-sensor-A-coil-works%21-A-capacitor-works-better%21

Tks bro!
