### ISSUE TITLE
1.5.0 RC7 checklist completely wrong !!!

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3504]
1.5.0 RC7 checklist completely unusable if colorscheme is changed.
 photo hihglight color #C00040    R=192   G=0   B=64

If one switch is wrong, all switches are marked as wrong!!!

Tested on X20PRO and Tandem XE!

Greetings Eugen

Foto XE

![XE Schalter](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/aa258b0d-a1b7-4907-99eb-084bc746ed50)

**Comment by bsongis-frsky** [comment]
User mistake? Or bug?

**Comment by yak55** [comment]
Hi,Would like to answer, but issue is closed!Answer by Mail allowed or another possibility?EugenAm 25.02.2024 um 19:47 schrieb Bertrand Songis @ FrSky ***@***.***>:﻿
User mistake? Or bug?

**Comment by yak55** [comment]
Hello Bertrand, thank you for asking.

The problem is caused by changing the screen color from dark to light and a customized highlight color in red.

As soon as the highlight color is used towards red, the checklist is no longer usable.

Red highlight color and red error color are impractical!

Why did I try this?

I had dark background and yellow highlight color.

If you take a look at the menu outputs on the simulator and the Tandem XE, it's great.

On the X20S and X20 Pro everything is way too dark and poor contrast, especially on the airfield.

Can the X20 and Pro be switched like the simulator or the XE?

That would be great

Greetings EugenAm 25.02.2024 um 20:06 schrieb Eugen Bleuel ***@***.***>:﻿Hi,Would like to answer, but issue is closed!Answer by Mail allowed or another possibility?EugenAm 25.02.2024 um 19:47 schrieb Bertrand Songis @ FrSky ***@***.***>:﻿
User mistake? Or bug?
