### ISSUE TITLE
VFR-Value as DIY sensor

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3505]
Hello,
I use the VFR value as a DIY sensor. Unfortunately, in the range test this is then constantly displayed as 0% and does not change. However, it works in normal operation.
Thank you, Wolfgang

**Comment by Wolepo** [comment]
Hi, I use VFR as a DIY sensor because it shows the data loss. This is easier for me to understand.
In 1.4.xxx, the VFR value is also displayed correctly in the range test, but no longer in RC7 (the first time I used it for a range test). The value remains at 0. You can of course delete the DIY sensor and have it read in again as a normal telemetry sensor. But then all LS and SF must be reprocessed. This is not necessary.

**Comment by bsongis-frsky** [comment]
I also don't understand what brings the DIY sensor there, why not a "normal" sensor?

**Comment by Wolepo** [comment]
Hallo,
the normal sensor shows me the values of the valid frames (100% all valid, 10%=only 10% valid), but the DIY sensor does it the other way round and reports the invalid frames (0%=all valid, 90%=only 10% valid). This option has been available since DIY sensors have existed and I use it in this way. In 1.4xxx the VFR values are displayed correctly in the range test, only since 1.5.xxx does the value remain at 0 although it should increase with distance.
