### ISSUE TITLE
Trims to sub trims not adjusting other flight modes' trim values.

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3507]
1.5.0 RC7

'Trims to sub trims' is not considering trims in other flight modes and is not adjusting the other flight modes' trim values.

Test setup:
Default flight mode = Cruise
Added Speed and Thermal flight modes on switch SE.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/80dc5358-8266-4117-a916-b9b599d3aae8)

Manually added trims:
Speed = -1%
Thermal = +3.5%

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/0156f497-a86b-4160-a8c0-58ecdb847ee2)

With flight mode = Thermal, execute 'Move trim to sub trim'.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/fafbdfae-d293-4dd6-a725-d4b7ffe1cb23)

As can be see in the screenshot and in Outputs, the +3.5% trim in the Thermal flight mode was moved to Subtrim. The trim in Thermal is now 0% and the Subtrim is +3.5%. Now comes the problem: The trim for Speed is still -1%.

Now compare the channel values in Elevator Output.
**Before** due to sub trim = 0%
Cruise = 0%
Speed = -1%
Thermal = +3.5%

**After** 
Cruise = 3.5%
Speed = 2.5%
Thermal = 3.5%

After executing 'Move trim to sub trims' the plane should fly the same as before, so the expected 'After' values should be:
**After** due to sub trim = 3.5%
Cruise trim = -3.5% i.e. effective 0%
Speed trim = -4.5% i.e. effective -1%
Thermal trim = 0% i.e effective +3.5%

**Comment by bsongis-frsky** [comment]
Fixed for RC8
