### ISSUE TITLE
EthOS - hardened against file corruptions

### ISSUE THREAD

**Issue by Ender1967** [FrSkyRC/ETHOS-Feedback-Community#351]
A lot of information is stored in "radio.bin" in SD card root and sometimes the changes are quite often and with unpleasant effects (file corruption).
Please consider some ideas to help EthOS handle file corruption in "radio.bin":
- divide radio.bin in 2 or 3 files (one with changed less frequent "settings.bin" and one with frequent changes with no effect if they are lost...let's say "temporar.bin")
- keep also checksum (md5 or similar) and last change time information
- keep a second copy of files in a separate folder ("RESTORE") in SD card (an in shutdown sequencebackup these important files)
- for X20 you can consider also keeping a copy of "settings.bin" in the flash area. 
- - in RESTORE you can keep also a copy of model files and also a "manifest" (with checksums).

**Comment by bsongis-frsky** [comment]
No report of file corruption until now. We will just KISS.

**Comment by bsongis-frsky** [comment]
Setting up something more complex won't avoid the programmer mistakes. I would even say it's exactly the opposite!
#349 was a bug which I fixed this morning, it will be part of 1.0.8
