### ISSUE TITLE
Markdown formatting possibly doesn't work

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3511]
It's possible I'm doing something wrong here, however having read the 1.5 Rev3 manual I think this should work.

You can hopefully see that this is a text widget pointing to a file, but the markdown text appears to have no effect and appears in the actual presented text.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/ccf3f23b-dbf8-4c46-b9c4-f6ad029e1a4e)

1.5 RC7

Thanks

**Comment by strgaltdel** [comment]
Hi jedster,

md works

last time i checked,
most of the typical attributes were supported, but not all.

regards
udo

**Comment by hrenz** [comment]
only 3 or 4 md-attributes works

**Comment by mawzthefinn** [comment]
Yes, but Heading and Bold are among them. Jedsters example is showing supported attributes.

I'm doing some testing. I've confirmed so far that if the extension is .md then it works, if it's .txt it doesn't, at least in File Manager and Pre-flight.

Need to verify the file location for the widget. Not sure where it's looking.

**Comment by Jedsters** [comment]
My bad, it appears that I copied over the .txt files. It works when named .md both in the widget and checklist text.
Thanks
