### ISSUE TITLE
RC8 Suite boot mode

### ISSUE THREAD

**Issue by doloebig** [FrSkyRC/ETHOS-Feedback-Community#3514]
The RC8 Suite is not able to switch transmitter in boot mode. Works with manual switch to bootloader.
Windows 11
Suite RC8 
TX X20S

**Comment by strgaltdel** [comment]
Hi Doro,

for sure it worked on RC7 ?

One of my notebooks won't switch between "suite" and "serial" mode either.
(lua dev tool", i guess it started 2 or 3 RC'S before.

Another notebook worked flawlessy ( i guess last check was on RC5), so i thought it depends on Windows "level" or HW driver.

I could see some "Component Object Model"  App-Authorisation issues in the event log,
but had not time for further investigations.

(Suite was installed & executed in admin mode, newest bootloader on tx)

i'll check RC8 on the "OK" notebook when i finished work..

**Comment by DaySpeed955i** [comment]
RC8 suite works fine here on updated Win11 22h2 and X20S.

**Comment by strgaltdel** [comment]
At first i tried my "OK" notebook with suite RC8
Test is to change between serial and suite mode vice versa, triggered by suite in the lua dev tool

Rc8 worked with my X18se without problem

then i installed suite rc8 on the "problem" notebook
test failed.

Differences between these 2 win10 notebooks:
in eventlogs / system logs i can see following message on the "problem" notebook

The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user THINKER01\alldocube SID (S-1-5-21-3430943642-1644377318-3919441668-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.


on the "OK" notebook i can see that permissions were granted.

So i assume (at least in my case) the win config (the problem nb is a home edition) has to be adopted.
The "OK" notebook is a win-Pro edition..

regards
udo

**Comment by Nicholas-Luoyi** [comment]
What does radio show after being required to switch to bootloader mode by your "problem" notebook? The radio is turned off or successfully switched to bootloader mode, but Suite doesn't detect it?

**Comment by doloebig** [comment]
after reinstall and reboot, working for me
can be closed from my side
my be Udo need more support
THX for commends
Doro

**Comment by strgaltdel** [comment]
as mentioned, my testing on the " "problem" notebook" is: change mode by using lua dev tool.
in case i want to switch from "suite mode" to "serial",the Tx gets the command , it seems that app after 5 seconds the tx changes the mode .
Suite doesn't recognize the "switch over" and runs into a timeout demanding manual switching.

today i gave more permissions to the classID mentioned in the event viewer (changed all entries to full access) using regedit.
changed nothing

so i started the domcnfg and i'm wondering that the mentioned appID is not in dom records

MS support site mentioned the entry (eventID 100016) could be ignored, so i'm not sure i'm on the right track.

nevertheless, i've one notebook which runs OK and it's not a big problem for me,
issue can stay closed;
In case i find a solution (not spending mich time actually) i'll post
