### ISSUE TITLE
Ethos simulator for MAC?

### ISSUE THREAD

**Issue by T16-Pilot** [FrSkyRC/ETHOS-Feedback-Community#3515]
Hi, why is there no Ethos simulator for MAC?

There are a lot of MAC users around the world. 

We have Ethos Suite for MAC, but no Simulator...

**Comment by Boebe62** [comment]
Good point. Don't want to run Windows on my Macbook.

**Comment by T16-Pilot** [comment]
> Good point. Don't want to run Windows on my Macbook.

Windows on a Mac, that is not happening...!

I love my Mac and i get stressed every time i have to turn on my Windows thingy, i start shaking just thinking about it..

I really want a Ethos simulator for Mac, or even better at an app for my Ipad.

**Comment by WhiskeyGolf** [comment]
That would actually be very good, as there is currently no option to edit the models on Mac.  Editing on the suite doesn't currently work either

**Comment by chaoscrack** [comment]
I add this question long time ago at the issue #2055. Nothing happend and someone closed and add it to the issue #3440. New issue but nobody care!

**Comment by fdm225** [comment]
Another user throwing in for MACOS support of the simulator.  

Let's hope that they release this when they release a version of suite that is signed by a valid certificate so MACOS doesn't complain and the ability to edit models in suite as well.  Ethos 1.5 brought the system up to where it actually competes against the other players in the space, now lets hope that they put resources on the supporting software.

**Comment by Rotormouth** [comment]
+1 for a MacOS version of Simulator

**Comment by mszulen** [comment]
This "issue" is closed.. .so nobody cares or no Mac developers here?

**Comment by T16-Pilot** [comment]
I care, but the Ethos developers care more about Linux users than MAC users... i am sorry, but as a MAC user i am not happy that there is no simulator for MAC. 

There are also issues with the MAC version of the Suite. We are missing functions that are in Windows version. I am forced to use Windows to use Ethos at the moment. As a MAC user i don´t like that one bit!

The main focus for the Ethos developer team seems to be on what ever the "Super Users" want, not what "Average Joe" need. Remember it is "Average Joe" that is the majority user of the system... only difference is the super users are the loudest about what they want/need. Average Joe is more ore less quiet because we want to fly, not be nerdy with the radio software.

I am sorry for being so direct, but with 1.5.X forward there has been a 100% focus on the super users. Almost every thing is now more complicated than 1.4.X...

I am too invested in Frsky hardware for this system to leave....  i don´t like the direction Ethos is moving at the moment...

Best regards
Average Joe...

**Comment by Dsrenger** [comment]
I am not a developer or in any way connected to FrSky.

Just one thought that is quite funny reading your comment. 

Average joe uses Windows and not Mac. Mac has a market share of ~15%. If you are using Mac, you are not average joe ;)

I get your grain of salt though ;)

**Comment by T16-Pilot** [comment]
That´s a funny one  Dsrenger ;)

Well... i like to do every thing i do the K.I.S.S. way. In that regards a MAC is exactly that ;) I am still running my 2015 MACBook Pro, still doing what it needs to do...

Ethos 1.4.X was as close to K.I.S.S. as we could get with a radio system like this, Ethos 1.5.X is fare from K.I.S.S....

The fact that i want my radio to be simple to use, yet advanced enough to do most things we need, yes i am an average joe. Yes i do advanced stuff in this hobby, but i don´t want to spend a sh.. load of time reading the manual to do something if i don´t have to.

**Comment by Dsrenger** [comment]
What is the reason why you updated from 1.4.17

I still have a transmitter on 1.4.17 (and one on 1.5.13)
I love 1.5.13 and hope nobody at FrSky will listen to not introduce new functionalities. I can do things with 1.5 that really helps me to fly models my models (like the dependent trims). You are voting for Ethos that hold back functionalities. 

No step forward is a step backwards.

1.4.17 works fine. Use it.

**Comment by T16-Pilot** [comment]
@Dsrenger 

Staying on 1.4.17 is limiting in regards to stabilized receivers. And a lot of other things.

What i don´t like on 1.5.X is the way the new timers are made. Fore all of us that just want a timer with speech to count down/up we now need to program 4 action on top of programming the timers to get speech. That is silly because the timer in 1.4.X did not need that. It was quick an easy. I need to brake out the manual each time i need to program the timer in 1.5.X now because i can´t remember from time to time... getting older, i forget stuff because there is so much to understand and remember in 1.5.X.

Next, Freemix is now so advanced that i need to do a lot of pushing buttons to set up simple stuff. I do understand that the "new" Freemix is way more advanced and that is nice for the "super user" but not for "average joe" Can we please keep the new Freemix, and also get the old Freemix back?

In general, i am not against 1.5.X. I do like some of the new stuff, i just don´t like to do a lot more programming to do the same stuff as i did before with a lot less programming in 1.4.X.

So no, i am not asking to "down grade" 1.5.X, just make it more user friendly. Maybe do like in Betaflight configurator. Have a "Expert" button to press if or when we need the advanced stuff.

Most users just need a simple timer or a simple Freemix.

Again, i am a MAC  user, i like my user interface to be easy to understand and use, you know K.I.S.S. 

At the moment 1.5.X is not very user friendly compared to 1.4.17.

O and by the way, we now have 3 different SXR "lua´s" depending on what  type of gyro rx we use. Why for crying out load don´t they make 1 SXR "lua" and then inside that menu select what RX we use and then the "lua" show the settings for that exact RX? I am an instructor in my club and more than half of the active pilots in my club flies Ethos radios. I spend a lot of time with confused pilot because of the SXR and different lua´s depending on what rx.

For the record. I bought my first X20 radio 3 years ago, so i am not new to the system. I have been there since day 1.

My current radios are:

X20 Pro - 1.5.9
X14 - 1.5.13

**Comment by bob01** [comment]
+1 vote for Mac/OSX simulator build please

**Comment by wmayvis** [comment]
Can you please reopen this issue? I'm still waiting from 2022 for the Mac Ethos Simulator. Multiple issue registered, without any success. Why is't so difficult to port a nodejs app to the Mac? You did it successfully for the Suite as well.

**Comment by bsongis** [comment]
Perhaps because it's not a nodejs app?
