### ISSUE TITLE
HIGH Power output problem on my X20S

### ISSUE THREAD

**Issue by rschmid1967** [FrSkyRC/ETHOS-Feedback-Community#3518]
Hi, I hope someone can help me.
When i switch from 25mw to 200 or 500mw in my X20S, i don't have GPS en telemetry anymore, when i switch back to 25 it works again.
The receiver that i use is a TD SR12  all updates are the latest in radio and receiver and sensors.
Who knows how to resolve this problem ?
Regards Ron Schmid The Netherlands

**Comment by mawzthefinn** [comment]
EU regulations limit 900M telemetry to 25mW and below.

some of the TANDEM receiver’s recently got a firmware update that forces telemetry to 2.4G when 900M is over 25mW, but the TD SR12 hasn’t received that update yet as far as I’m aware

**Comment by rschmid1967** [comment]
Ok, and do you think it will work in the near future, i like to use this in my planes, and i dont know the range at a value of 25mw.
And do you know the max size of the sd card in a X20S because my radio is already a bit slow with startup en swiping on the screen of my radio

**Comment by mawzthefinn** [comment]
Just leave it at 25mW, which is enough for any line of sight operations. I would not recommend exceeding LOS range on a receiver without return to home functionality.

Note that telemetry is only 2.5-4km range on TANDEM’s 2.4G link anyways, so you are still limited to LOS and just beyond for telemetry in Europe

**Comment by mawzthefinn** [comment]
Max card size is 32GB, speed issues are usually too many lua active though

**Comment by rschmid1967** [comment]
Ok i will test it, and ok i think its maps and lua that makes my radio slow

**Comment by rschmid1967** [comment]
> Max card size is 32GB, speed issues are usually too many lua active though

Do i need a class 10-3 or 1 ? I attempt a 32 gig kingston hc class1 V10, but my radio says: No SDCARD when i put it inside the x20S

**Comment by mawzthefinn** [comment]
32GB cards, especially UHS-1 rated ones, can be problematic, the cheaper UHS-1's don't always fall back properly to the regular SD interface.

No SD card means the card is trying to talk UHS-1 only, or is formatted ExFAT. 

Any class 6 and up card should work fine. I'd suggest looking for a Class 10 card that isn't UHS-1 rated.

**Comment by rschmid1967** [comment]
> 32GB cards, especially UHS-1 rated ones, can be problematic, the cheaper UHS-1's don't always fall back properly to the regular SD interface.
> 
> No SD card means the card is trying to talk UHS-1 only, or is formatted ExFAT.
> 
> Any class 6 and up card should work fine. I'd suggest looking for a Class 10 card that isn't UHS-1 rated.

Thanks for you advise ;-)

**Comment by frobert0** [comment]
[@] mawzthefinn
Re: card size: use a 64GB Sandisk Extrem Pro with AOMEI Partition Managert formatted to 64GB (Fat32). Works ok.
Images now appear almost immediately.

With the original card, images were created very, very slowly.


(![Screenshot 2024-04-03 115135](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12582649/c1d07b64-4a67-4033-85bb-509a0ef325b0))

**Comment by mawzthefinn** [comment]
Note that configuration is out of spec for SD and may break unexpectedly in the future.

The SD spec does not permit FAT32 for cards of greater than 32GB capacity, they are required to be ExFAT. There are ways to format those cards as FAT32, but they are no longer SD card compliant once you do that.

**Comment by frobert0** [comment]
For years it has been used for work reasons (logs file) because hardware cannot/may not be replaced and no problems.
