### ISSUE TITLE
Clock error - On / Off seconds

### ISSUE THREAD

**Issue by JaroslavFalcon** [FrSkyRC/ETHOS-Feedback-Community#352]
In the clock setting,
when I turn off the display of seconds,
seconds stop, but are still displayed

**Comment by bsongis-frsky** [comment]
It will change within the next minute. You shouldn't change this parameter too often, yes?

**Comment by JaroslavFalcon** [comment]
Yes it's right.
after a minute change it's correct.
(not ideal - "amateur")
