### ISSUE TITLE
Zoom LOG

### ISSUE THREAD

**Issue by robertobrazill** [FrSkyRC/ETHOS-Feedback-Community#3520]
I'm unable to zoom in on the log. Is there any tutorial?

**Comment by mgsanna** [comment]
It's quite easy: 

- open log file
- select what you want to see
- touch inside the graph (you'll notice the yellow line with time stamp on bottom)
- push and stay pushed the grey center left button and rotate the rotary encoder

You get the zoom working !!!

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/f5f9b24e-5e08-4fbf-b3f2-67dfe4d289c5

**Comment by robertobrazill** [comment]
TKS Bro!

**Comment by mgsanna** [comment]
Close the issue!
