### ISSUE TITLE
Probleme assignation des interrupteurs 1.5.0 ( résolu )

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#3521]
Bonjour,
Je viens de passer à Ethos 1.5.0 sur ma Tandem Xe ( auparavant 1.4.17 ).
Depuis, seul l'inter n°1 fonctionne mais active aussi tout les autres qui ne fonctionnent pas individuellement....

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89158034/c679d2d1-3889-47fd-9d95-f179ecabcf1c

**Comment by Tonio62** [comment]
Je viens de trouver le problème...
Tout mes inters ont été modifiés en n°1 au passage à la version 1.5.0

**Comment by Tonio62** [comment]
![IMG_20240302_094331](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89158034/f958f361-0ed3-4f11-98e4-bc22d852f100)

**Comment by bsongis-frsky** [comment]
Duplicate of #3535 
It seems there is an issue there
