### ISSUE TITLE
(Enhancement) Assign a switch to Dark/White Mode

### ISSUE THREAD

**Issue by Quickfixforlife** [FrSkyRC/ETHOS-Feedback-Community#3522]
I'm on the latest firmware's, OS version 1.5.0, please consider making an update to address this matter

**Comment by hrenz** [comment]
or a selectoion of some color screen widgets

**Comment by Richrfl** [comment]
With all due respect, I don't think that the idea of assigning a button to enhance the greyed text is a good one. In my opinion, the available hardware in the transmitter is supposed to be intended to generate actions to control the aircraft. I agree though that there is a big problem to read shaded text on a sunny day, even in the shade. (Florida Sun). However, the proposed solutions on post #3876 seem to be a better approach
