### ISSUE TITLE
Inherited Trim Issue

### ISSUE THREAD

**Issue by radlouni** [FrSkyRC/ETHOS-Feedback-Community#3523]
Hello,

I created an inherited  Rudder trim config as follows:

1- First level trim is "Default"
2- Second level is "Offset + Default" tied to switch SC-
3- Third level is "Offset + SC-" tied to switch SC down

first and second level trims operate normally, but third level is erroneous and exhibits a very strange trim values.

I am on latest 1.5.0 version, all is updated to latest version using Ethos Suite

**Comment by bsongis-frsky** [comment]
~~"Offset + SC-"~~
~~So you mean Offset -100% since SC is down?~~

**Comment by radlouni** [comment]
> "Offset + SC-" So you mean Offset -100% since SC is down?

No, i mean when configuring the trim, i chose the option "Offset + SC-". This is the exact verbiage in Ethos when configuring inherited trims.

exact steps are:
1- Press Model icon
2- Press "Trims"
3- In rudder trim settings and under Mode, chose "custom"
4- Click on "Add a new behavior"
5- under behavior chose SC- as the switch and "offset+Default" under mode
6- repeat step # 4 and chose SC down as the switch and "Offset + SC-" under mode.

this way, first level trim is when SC switch is up, second level inherited trim is when SC switch is middle, and third level inherited trim is when SC switch is down.

first and second level trims work perfectly, third level trim gives erroneous trim values.

**Comment by radlouni** [comment]
Did anyone have the chance to look at this ?

**Comment by bsongis-frsky** [comment]
A screeenshot to be sure we are on the same configuration?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5e51d9c0-865f-4411-9f9c-e80f25912d34)

**Comment by bsongis-frsky** [comment]
You are right, something is not working when SC is down

**Comment by radlouni** [comment]
> A screeenshot to be sure we are on the same configuration?
> 
> ![image](https://private-user-images.githubusercontent.com/50834778/311213811-5e51d9c0-865f-4411-9f9c-e80f25912d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTY4ODksIm5iZiI6MTcwOTg5NjU4OSwicGF0aCI6Ii81MDgzNDc3OC8zMTEyMTM4MTEtNWU1MWQ5YzAtODY1Zi00NDExLTlmOWMtZTgwZjI1OTEyZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDExMTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNjRmZmQ0MWM2NDQzNzYwZWYzMjNkZDMxOWFhZmNjOTQ3N2E1MjNiN2Y4YzJlNzI2NjZjNWVhNzY5MTk1ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKwLEeZ8LpvzuMj4kfCPzqvqgonjJNXkm69UWZDos-w)

Yes exactly, its the same configuration, when SC is up, default trim, and when SC is middle, default trim + offset, and when SC is down, default trim + first offset + second offset.

second offset is not working, there is something wrong

**Comment by bsongis-frsky** [comment]
I have found it, stupid copy / paste issue which has not been noticed during RC!
