### ISSUE TITLE
La fonction ralenti ne fonctionne plus dans les mixages libres Ethos 1.5.0

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#3524]
Tandem xe 1.5.0
La fonction ralenti n'est plus opérante dans les mixages libres alors que tout fonctionnait sous Ethos 1.4.17.
J'ai tenté de réinitialiser le mixage en y rajoutant du ralenti; le ralenti n'opère qu'à la première tentative et ensuite il devient inopérant.

Merci ;)

**Comment by mgsanna** [comment]
Içi fonctionne parfaitement......

**Comment by Wolepo** [comment]
Have you followed the order of the entries?
![Reihenfoöge](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/b24b3ca5-47a0-41f9-a94b-bf2267eb3376)

**Comment by Tonio62** [comment]
Oui, j'ai bien respecté cet ordre....
Le ralenti fonctionne très bien sur la voie de base des volets, mais j'ai un mixage fullspan avec les ailerons.
Les ailerons sont sur un mixage libre, et le ralenti ne fonctionne pas avec eux

**Comment by Tonio62** [comment]
Uploading VID_20240302_155347.mp4…

**Comment by Tonio62** [comment]
Bon, ça fonctionne...
C'est assez complexe à expliquer, mais au lieu de faire un mixage ailerons en volets j'ai fait un mixage volets vers ailerons.... Pourtant avec la 1.4.17 celà fonctionnait.
Sûrement quelque chose dans les mixages qui a changé ;)

**Comment by bsongis-frsky** [comment]
Strange, there is another report for this problem in #3536
Discussion to be continued there
