### ISSUE TITLE
XES sim 1.5.0 missing switches in hardware check

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#3525]
The XE(S) has 2 x 3 switches on the top. The Simulator has only 2 x 2 switches.
![Monosnap Ethos Simulator 2024-03-02 15 42 41 (1)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26022422/4e1e8dbe-11d6-41ab-89b7-a1675a07b5df)

**Comment by hrenz** [comment]
and FS1 to FS6 doesnt work
and trim5 and trim6  doesnt work

**Comment by bsongis-frsky** [comment]
Are your switches correctly configured in System / Hardware?

**Comment by Storchy1** [comment]
You are right!. My switches was not correctly configured. My fault! Excuse me!
