### ISSUE TITLE
V1.5.0 stabil  no bootloaderfiles  in the release files

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3526]
for update only
first flash the bootloader to the latest Version

but at the V1.5.0 Release files there is no bootloader file
think, normal user need it

**Comment by mawzthefinn** [comment]
1.5 uses the most recent bootloaders (1.4.15 for most systems, 1.4.17 for X12S)

**Comment by bsongis-frsky** [comment]
We only release a bootloader when it is really needed. Ethos Suite shows the right version of all components, including the bootloader.
