### ISSUE TITLE
LS has max Range for RSSI of 100db which is 115db in RSSI Telemetry Sensor

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3527]
I notice that Telemetry RSSI has a range of 0db to 115db, however in LS the maximum range which can be specified for RSSI is 100db. 
This is obviously inconsistent.
115db seems more reasonable since I've seen in excess of 100db with some rx.

I can't imagine many are going to notice but should probably be made consistent at some point. 

1.5.0 Release
Thanks

**Comment by bsongis-frsky** [comment]
It works as it should: logic switches detect the maximum from the associated sensor

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5bc6612d-59d6-437d-99c1-e6299d968931)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4ec5e9d9-a10b-4bd6-a0b0-d29a4094c192)
