### ISSUE TITLE
New Model Wizard provides 4 output channels for just 2 channels for V-Tail

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3529]
If using the New Model Wizard to create a V-Tail, the Channels page(s) allows you to select which channel is used for e.g. 
Ail1/2
Ele1/2
Rudder1/2

I struggle to understand why both Ele1/2 and Rudder1/2 are required? Doesn't V-Tail1/2 make more sense with no duplication?

I can almost see a justification in terms of you may specify the same channel for Ele1 and Rudder 1 or Ele1 and Rudder2 etc., however at this stage are you going to know which you should specify? You may end up swapping the Output channels on the Rudder around anyway to get what is required for how you have set the model up mecahnically. 
This also interlaces with my comments in #3454 
Thanks

**Comment by mawzthefinn** [comment]
It allows you to map V-tail onto specific channels. For example if mixing an F-18, you would go for 4 elevators, 4 ailerons, 4 flaps and 2 rudders with V-tail. 

In that case, your 3rd & 4th Ailerons map to your 1st & 2nd elevators (tailerons) and your 3rd & 4th elevators map to your 2 rudder channels (pitch input on the angled vertical stabs). Your flaps are mapped 2 onto ailerons 1 & 2 and 2 onto inner flaps. 

That will replicate most of the control law for an F-18 (missing the speed brake functionality for the verticals)

**Comment by Jedsters** [comment]
Wow!
