### ISSUE TITLE
ethos suite 1.5.0 missing backup functionality

### ISSUE THREAD

**Issue by vasyly71** [FrSkyRC/ETHOS-Feedback-Community#3530]
I installed ethos suite 1.5.0 over 1.4.xx and update x20s transmitter to 1.5.0 release.
Ethos suite is missing backup take/restore functionality.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/3381c73c-e637-4784-b69f-4b4f69736d31)

Was it moved in different location
If this is a defect is there a workaround procedure how to backup all - models/images/sounds - what is structure of zip archive?  

Thank You

**Comment by mgsanna** [comment]
Maybe Reinstall you ethos suite because I can assure that everything is working right
<img width="889" alt="Screenshot 2024-03-02 201340" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/7dc926c3-403e-4720-87c7-4efd035ce7a7">

**Comment by mgsanna** [comment]
download it again from here: 
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.5.0

**Comment by vasyly71** [comment]
Fully uninstalled, removed all files from program, cleaned up entries in registries...
Installed from https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.5.0 to ensure setting up right app.
Still same result.
Just in case os info:
==================
Edition	Windows 10 Home
Version	22H2
Installed on	‎2022-‎09-‎09
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0
===================

I also have ethos suite on linux laptop installed in windows vm. Uninstalled 1.4.xx (plain uninstall "programs and features" ) there and installed new and it works. Definitely something environment specific.

**Comment by vasyly71** [comment]
Fully uninstalled, removed all files from program, cleaned up entries in registries...

 Installed from https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.5.0 to ensure setting up right app.
 Still same result.
 Just in case os info:

Edition	Windows 10 Home
Version	22H2
Installed on	‎2022-‎09-‎09
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0


I also have ethos suite on linux laptop installed in windows vm. Uninstalled 1.4.xx (plain uninstall "programs and features" ) there and installed new and it works. Definitely something environment specific.
