### ISSUE TITLE
Update 1.15.0

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#3531]
After updating My X20S, and my X10S Express, The special functions on the X20S was unable to recognize the loaded files in the audio and not working even though they were there. My X10S Express down loaded and updated to 1.15.0 the files and recognize wav.files fine. I had to revert back to 1.4.17 in my X20S in order for wav fills to be readable.

**Comment by mgsanna** [comment]
The audio files you want need to be in a specific folder/directory for them to be selectable.

https://docs.google.com/document/d/1paUtOzmq8U2BKiGnPeUnm5S2Sa0PvUrJtx4Y5sPww-U/edit?usp=sharing

**Comment by bsongis-frsky** [comment]
https://www.rcgroups.com/forums/showpost.php?p=50718883&postcount=23264

**Comment by hershg21** [comment]
Thank You for a fast response. Why my misunderstanding was because my XS Express had no issues with this.
Thanks
