### ISSUE TITLE
Should firmware update process also move non standard audio files in a new location? (update usability)

### ISSUE THREAD

**Issue by vasyly71** [FrSkyRC/ETHOS-Feedback-Community#3533]
I have some custom audio files. 
There was a question during installation "do you want to delete ...audio... folder, i did not pay attention and hit yes (did not care cause take backups regularly).

It would be nice if non standard files be moved to audio/us automatically by update process so that play back continuiew to work.
After i moved files manually custom playback for switches seems working fine

**Comment by bsongis-frsky** [comment]
Voices depend on the chosen language. For example in french we have "homme" and "femme". So it will be difficult to make everybody happy here

**Comment by strgaltdel** [comment]
perhaps a simple extension of the warning would be sufficient?
would be a simple solution

something like


attention: custom audio files will be deleted!
make sure you have made a backup copy

??

**Comment by vasyly71** [comment]
> Voices depend on the chosen language. For example in french we have "homme" and "femme". So it will be difficult to make everybody happy here

A question before upgrade would work, or perhaps current OS local with confirmation from user input.
I understand a complication: firmware distributed as pre-compiled binary and i'm asking to parameterize this binary...

So yes check lists for radio level settings and model level settings i need to verify post upgrade would work as well, perhaps distributes as a text file asset with every release (could be empty if there is no incompatibilities )

**Comment by ilioSS53** [comment]
My audio files manualy placed in us and geb folder can,t choose the files. No audio apart from the welcome message.

**Comment by pstasek** [comment]
Bear in mind that many of us are using quite heavily customized sound packs that need to be placed in a very specific folder in the 1.5.0. I agree the instructions and warnings are a bit vague in this case. I think a simple reminder pointing to a detailed description of the new voices folder structure would be the best way, letting the user to decide where to put his custom files and eventually sort them. The voices are so powerful and I'm sure there's a lot of ways how people are going to utilize them. A nice document has been shared in the Official Facebook Group: https://docs.google.com/document/d/1paUtOzmq8U2BKiGnPeUnm5S2Sa0PvUrJtx4Y5sPww-U/edit?fbclid=IwAR2JoWsFmCdC4Hz1oH2vOwzHYzA11N2eODOfYSTBk0pyUI-sBU91II83EaU

**Comment by bsongis-frsky** [comment]
I will add a new "default" voice folder to make the conversion easier = nothing to do for the end user who uses the standard audio packs

**Comment by bsongis-frsky** [comment]
Discussion in #3584
