### ISSUE TITLE
firmware update 1.4.x to 1.5.0 timers configuration changed for models and need to be manually updated 

### ISSUE THREAD

**Issue by vasyly71** [FrSkyRC/ETHOS-Feedback-Community#3534]
I typically setup my timer to start on sf1 up and beep every minute and  then every second during last 10 sec.
after update - 
1.  timer start changed to empty 
2. and audio action is "Beep countdown, start: 02:00 step 30s"

I understand possible complexity to migrate existing model to new configuration. 
It would be nice to have a well defined check list in release notes that would guide us through things to check for each model where incompatibility with 1.4.xx resulted it configuration change and can even slightly affect flying session.

**Comment by bsongis-frsky** [comment]
Please paste the configuration of your timer before the switch to 1.5.0
It should be automatically converted

**Comment by vasyly71** [comment]
> Please paste the configuration of your timer before the switch to 1.5.0 It should be automatically converted

that would be hard to do - already upgraded radio and updated my timers with new "actions". 
I should have backups form nov/december 2023. @bsongis-frsky any suggestions how i can extract this settings from model bin files from backups?

**Comment by agibson2** [comment]
Probably best to attach your backup model file to a post on this thread.

To see what the settings were without impacting your existing radio version,  You can always install a 1.4.15 simulator on your PC (last 1.4.x release with simulator), run it once to create directories, and then copy the model.bin from the backup into C:\Users\yourusername\.ethosTWXLITES\models\  for the TWXLITES simulator for example.  Replacing yourusername with whatever your windows username is.

**Comment by vasyly71** [comment]
@agibson2 thanks for recommendation i got the model in simulator. And yes i can confirm that timer action in 1.5.0 was setup same as timer was setup in 1.4.x:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/a453d0fd-1672-40c9-aba1-391481d90bc2)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/296e292c-a241-4d9d-bd22-4a051fb661f6)

Now problems that i think i observed:

1. "active condition" in 1.4.x seems was not transformed to "start condition" in 1.5
2. In 1.5 only one action was created - "countdown" which seems different from general time in 1.4.x behavior - no count down beeps every second during last 10 seconds - so i needed to add beep countdown action.

Here is my 1.4.model
[model1-4.TGZ](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14504603/model1-4.TGZ)

**Comment by bsongis-frsky** [comment]
You are right, the conversion should create 3 audio actions (you also miss the every minute callout), not only one
Fixing it for 1.5.2

**Comment by bsongis-frsky** [comment]
Here will be the result of the conversion in 1.5.2

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/999c198c-4f63-4596-ae15-9ff7b2baa0e9)
