### ISSUE TITLE
Tandem XE switch mapping reset after update to 1.5.0

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3535]
After upgrading to 1.5.0 all the switches are mapped from Switch 1 on Tandem XE radio.

![IMG_20240303_013304504_HDR](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/3ed97eef-051d-4a5a-abba-173bde128226)

**Comment by bsongis-frsky** [comment]
2 reports for this issue. I will check
