### ISSUE TITLE
Problem with slow action in mixes in ethos 1.5

### ISSUE THREAD

**Issue by Eduardoesteban1694** [FrSkyRC/ETHOS-Feedback-Community#3536]
Hi,

I use spoilers to land my plane. I have a problem with the mix when going to ethos 1.5, and that is that when I turn on the radio, the first time I activate the spoilers, they go up fine with the delay time that I have configured, but the other times they don't do it anymore , but it does it quickly.

**Comment by mawzthefinn** [comment]
I would recommend asking on RCgroups in the ETHOS thread. We would need to see your model file either way (post here, or on the ETHOS/X20 thread there).

No way to determine what's going on without seeing the model file

**Comment by kramgrand** [comment]
Just updated one set to 1.5 yesterday. I found a similar issue with one model. I worked out I could add additional actions within the mix. One of the actions was setting a time up and down function.  I believe the Actions have to placed in the correct order for it to work how you want it to, but I did get it to work.
Would really like a 1.5.0  updated Ethos manual.

**Comment by bsongis-frsky** [comment]
I need your previous model to check what goes wrong. The manual is updated.

**Comment by Eduardoesteban1694** [comment]
[big stick .40.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14474479/big.stick.40.zip)
@bsongis-frsky this is the model I use in ethos 1.4.17, I went back to ethos 1.4.17, so I don´t have a model updated to 1.5.

**Comment by Eduardoesteban1694** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/152110218/e8ebb6da-5710-4c8d-a0fb-a455af0471cd

This is the problem, is in a free mix.

**Comment by bsongis-frsky** [comment]
Screenshots of 1.4

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a968fecb-c3a2-433a-8ff3-a8ae94c378e6)
_Redundant active condition + flight mode_
_Source should be Max, not SE_

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d16fdf62-af82-48bf-bd10-200bf6976532)

**Comment by Eduardoesteban1694** [comment]
@bsongis-frsky 
Thanks, I will correct the source to max.
Regarding the flight mode, I have it that way because I have independent trims, initially I didn't have it that way and when I activated the spoilers the plane had a tendency to turn to one side, I don't remember which side it was.

**Comment by bsongis-frsky** [comment]
In 1.5.0 the slow is applied a little bit differently: the free mix works (and is calculated) only when its active condition is true, for this reason, the output is always the same, as it is not re-calculated when the condition is false.

I propose this:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ab4bc3a8-f830-4757-a05c-e320c5fb9b15)
