### ISSUE TITLE
Var Action overrides Special Values etc.

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3539]
I notice that a VAR Action overrides a Special value or other source and question if this is desirable.

e.g. Create a new VAR, change the initial Value of 0 to use a Source of Special 0.
Create an Action of Trim LVU Add 100

You'll notice that so long as you hold LVU the output Value is 100. 
The same is also true if you use another Source e.g. RS, it will increase the output value of this so long as the Action is true.

I guess this ultimately comes down to which should take precedence, a Special value / Other 'unchangeable' source or the Action?

On the one hand it would be nice if the 'unchangeable' value was honoured, as that could simplify LS. 
My scenario is I want an adjustable VAR to use as a weight in 2 FM.  
Currently I need to create an LS for FM1 OR FM2 Active Condition of LVU and similarly another LS for FM1 OR FM2 Active Condition of LVD and then feed these into VAR Actions so that the weight is only changed when I expect it to be changed, i.e. when FM1 or FM2 VAR Values are True.
If the unchangeable Value was honoured then I could get rid of these 2 LS and just use LVU and LVD directly in the VAR which would have a default Special Value 0 and Values for FM1/2 which would only be changed when true.

Of course then multiply this for a number of weights / LS.

One could argue that someone may want a testing value to temporarily override an unchangeable value, but I feel this would be a more niche use case.

1.5.0 Release
Thanks

**Comment by mawzthefinn** [comment]
Actions act on values.

this is the expected behaviour, 

you need to use active conditions & logical switches if you want to lock things out, not the VAR functions themselves

**Comment by Jedsters** [comment]
So long as this is intentional I'll close.
Thanks for the confirmation.

**Comment by Jedsters** [comment]
So long as this is intentional I'll close.
Thanks for the confirmation.
