### ISSUE TITLE
Feature request: Adding keyboard UI

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#354]
Is it possible to add a keyboard to the UI, so that the names of the models, functions etc. can be easily insert?

**Comment by Hobby4life** [comment]
And number pad, like entering values into Logic functions is taking ages with scroll wheel.

**Comment by bsongis-frsky** [comment]
Duplicate of #189

**Comment by hrenz** [comment]
And please not ABCDEFG keyborad
take QWERTZ or QWERTY form
