### ISSUE TITLE
Range in VSpeed Telemetry Sensor looks odd / wrong

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3540]
When you change the Range in the VSpeed Telemetry Sensor the range appears very inconsistent - it looks like somthing is the wrong way around.
e.g. a range of
mph -224 to 224
km/h - 360 to 360
seem reasonable
m/s of -100 to 100 also seem reasonable but doesn't convert to 
2m/min 

similarly 
328 ft/s doesn't convert to 5ft/min

I notice that e.g 5ft/s does ~correspond to 328ft/min etc..

It appears the calculations are being applied to the wrong units.

1.5.0 Release

Thanks

**Comment by bsongis-frsky** [comment]
VSpeed sensor from FrSky? I check here and I see no problem

**Comment by bsongis-frsky** [comment]
It seems there is a problem with the unit m/min, but not others, yes?

**Comment by bsongis-frsky** [comment]
I have written that 1m/min = 60m/s
Which is wrong

**Comment by Jedsters** [comment]
Not sure if you've fixed it now, but there was a problem with ft/s and ft/min too.
They appear to be the wrong way around 
the limits were 328 ft/s or 5ft/min which are very different, the former being extremely fast and the latter extremely slow. 
I'm guessing the limits should actually be 5ft/s and 328ft/min which are pretty comparable.
Thanks!
