### ISSUE TITLE
Location for Text files

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3542]
Just one question: where do the text files for the text widget have to be located?
X20s Transceiver
Thanks  for 1.5.0 Version, great job 👍👍👊

**Comment by mgsanna** [comment]
you need to add a folder in your sdcard

sdcard:/documents/   for normal docs and txt
sdcard:/documents/user/   for personal txt to be displayed on widget

you can use .txt or .md (markdown files)

**Comment by mgsanna** [comment]
and last but not least, for custom warning list with text, just make a .md file with the model name and .md extention 
and put it inside models folder

**Comment by Skippydi** [comment]
Sorry, it does't works
![20240303_203345](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/2e1a2a80-ff1e-45eb-b247-782bc695e4b4)
![20240303_203421](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/69fd948b-3198-44b9-844d-d2b47981ace1)

**Comment by mgsanna** [comment]
sorry but you wrote dokuments instead of **documents**
![scree](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/fb45ff93-c97a-4b51-9323-c2a202a70deb)

**Comment by Skippydi** [comment]
OK, sorry, now it works. Thanks a lot for Help👍👍

**Comment by mgsanna** [comment]
Ok I think you can close the issue
