### ISSUE TITLE
Ethos Feature Request for stabilized receivers:  Stick Priority or Stabilization Reduction (decay)

### ISSUE THREAD

**Issue by Joetrin** [FrSkyRC/ETHOS-Feedback-Community#3544]
On some stabilizers, there is a feature called "Stick Priority".  It's a variable that can be set to reduce the amount of stabilization the farther away from center.

Max stabilization at center, then the closer you move the sticks to the edge, the less stabilization you have.

This is particularly good for tumbling maneuvers on aircraft.

Example:
Stick Priority on elevator @ 60%
Action: When elevator stick is centered, there is max stabilization (100% = Whatever gain is set for that axis), the closer you get to 60% throw, the less the stabilization.  When the throw exceeds 60% on the stick, stabilization = 0

So the decay from center of stick to 60% is linear ending at zero at above 60% throw.

is this possible?

**Comment by RealTadango** [comment]
It has this already build with a fixed value. With the advanced editor (Windows PC) you have more control over this. A simple % per axis would be nice...

**Comment by LeoCheung123** [comment]
Agree w Op
That this should be a basic setting, not one requiring a PC. Hopefully this gets incorporated into the future "master stabilization lua".

**Comment by RealTadango** [comment]
It is not a lua thing, it needs to be changed in the firmware also. The PC software is used for the advanced programming and can do so many things more then the basic stab program can that is configurable using lua.

**Comment by pstasek** [comment]
The gain of the gyro is a channel. You could easily mix the stick inputs to reduce the gyro gain proportionally in the Mixer page.

**Comment by Joetrin** [comment]
Agreed, that's what I'm doing now.  But that affects all axis, what I'm trying to do is to set individual decay for each axis, because not all axis are set to the same level of decay.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Joetrin** [comment]
Thank you for putting this into the latest Firmware Update for the stabilized RX's.
