### ISSUE TITLE
Emergency mode - ETHOS 1.50

### ISSUE THREAD

**Issue by dkaehler681** [FrSkyRC/ETHOS-Feedback-Community#3545]
Horus X 10 Express ETHOS 1.50
If you want to go back in the mixer when viewing by channel, Emergency Mode always appears.

**Comment by strgaltdel** [comment]
could replicate by using a complex template 
dozens of mixers

"opened" an output channel which was used by 4 or 5 mixers,
exit generated em

no failure on a much more simple template 

we are discussing em issues in a german forum
one user gets em by editing a curve,
it seems he is using several luas

**Comment by strgaltdel** [comment]
seems to be a critical issue

 as soon as the em triggers
 the receiver loses the connection, failsafe initiated

**Comment by bsongis-frsky** [comment]
Would you attach a model which has the EM?

**Comment by bsongis-frsky** [comment]
Reproduced on simulator
