### ISSUE TITLE
Spektrum telemetry 1.5 

### ISSUE THREAD

**Issue by advancedtacmachine** [FrSkyRC/ETHOS-Feedback-Community#3546]
Updated to 1.5 but still cannot discover any telemetry from spektrum receivers dsmx-2 protocol. Reloaded multi lua just to be safe but still get no telemetry.

Please advise

**Comment by bsongis-frsky** [comment]
Which is the receiver?

**Comment by advancedtacmachine** [comment]
Spektrum AR630 also tested ar637ta no telemetry was discovered.

**Comment by bsongis-frsky** [comment]
On which radio?

**Comment by patty-cakess** [comment]
> On which radio?

I can confirm not working on X20 Pro.

**Comment by RealTadango** [comment]
What MPM modules do you use and which version? We tested with the iRange iRX4 with the latest firmware and older firmware and it works fine with DSMX telemetry with planes (Both BNF, UMX ultrix and D18 from E-flite).

**Comment by RealTadango** [comment]
And can you confirm you bind the plane in DSMX mode and not DSM2 mode? Some planes support both but telemetry only works in DSMX mode. Both in 1F and 2F.

**Comment by advancedtacmachine** [comment]
X18   went back and made sure they are both bound in dsmx 2f. I'm using the tbs multi module on latest firmware. Module gets telemetry on my radiomaster Zorro. 

Should I be running a different lua?

**Comment by advancedtacmachine** [comment]
Looks like irange irx4 uses same chipset as the TBS multi

**Comment by RealTadango** [comment]
> X18 went back and made sure they are both bound in dsmx 2f. I'm using the tbs multi module on latest firmware. Module gets telemetry on my radiomaster Zorro.
> 
> Should I be running a different lua?

No, lua has not changed in the 1.5 update.

**Comment by advancedtacmachine** [comment]
![20240304_165739](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/76758227/9680d7f2-a915-4553-8e82-bdbd3e18397b)

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/76758227/18b35daf-3ece-4602-88f7-7204735f2d3b

Just Incase anyone sees something I have done incorrectly

**Comment by RogerRamjet21** [comment]
Same issue, no telemetry. X18S IRange IRX4 Lite. Horizon Hobbies Cub S Bind and Fly (don't know what receiver these have, but SAFE capable).

**Comment by rickisound** [comment]
I tested the specktrum receivers ar6610T, ar8210T, ar637T, ar8360T, ar10100T, in all of them the integrated variometer and altimeter do not work, ethos does not detect these sensors during the search, the other integrated sensors work correctly.
furthermore the RSSi value is not displayed in the topbar

**Comment by RealTadango** [comment]
Rssi is known, vario is not implemented yet

**Comment by deeallcco** [comment]
> Rssi is known, vario is not implemented yet

any news on the 0db rssi from spektrum receivers showing in the top bar. Thanks

**Comment by Quimb0** [comment]
Hello.  I have the ethos and irx4 actions installed and several values are missing (mha, alt, vario, dual batt, etc...) tested with several latest generation receivers.  Do you think more complete DSMX telemetry is possible in the future?  Thanks

**Comment by NYskys** [comment]
Hello everyone.
I'm new here and this is my first contribution and I hope it helps. I just got X20S with 1.5.7 FW and installed IrangeX IRX4 lite. Also updated to the latest FW. I was wondering about the RSSI, so I started experimenting. I set up a TM1000 DSMX on a AR7110 receiver. and bonded them to the TX. First the RSSI was reading zero. I tried to do range check and it was giving me zero. but when I got to the telemetry widget and turned the sensor on, I started reading all the data including the RSSI. but it still showing zero on the top bar. what I can gather, is that the RSSI widget in the LUA script is not set to look for more than the internal modules. there should be two subroutines one to read the internal and if nothing on the internal then it should read the RSSI data from the external module.
I'm and engineer not a programmer or script or code writer. but my simple programing got me to this conclusion.
here is the LUA script command line that controls the RSSI widget.

local function wakeup(widget)
    local sensor = system.getSource("RSSI")
    local newValue = nil
    if sensor ~= nil then
        newValue = sensor:stringValue()
    end
    if widget.value ~= newValue then
        widget.value = newValue
        lcd.invalidate()
    end
end

**Comment by bsongis-frsky** [comment]
Voltage (0x01) added in 1.5.14
Temperature (0x02) added in 1.5.14
Current (0x03) added in 1.5.14

**Comment by bsongis-frsky** [comment]
Altitude (0x12) added in 1.5.14

**Comment by bsongis-frsky** [comment]
Vario (0x40) added in 1.5.14

**Comment by bsongis-frsky** [comment]
Dual Batt (0x34) added in 1.5.14

**Comment by Quimb0** [comment]
Tanks you @bsongis-frsky 

according to my tests, neither with version 1.5.14 nor with 1.5.15 can I see the aggregated telemetry values. I have tested with several receivers of various brands and different versions and functions.
I have updated everything I thought necessary, but I cannot get the aggregated data.
If I can help, I will be happy to help.

**Comment by rickisound** [comment]
I comfirm,I also tested with firmware 1.5.15, and receiver ar637T and ar8020T, the altitude sensor is still missing...

**Comment by bsongis-frsky** [comment]
@Quimb0 what do you mean by the "aggregated telemetry values"?

@rickisound do you know the ID of the sensor you are missing?

**Comment by rickisound** [comment]
I don't know the ID of the sensors, checking on the github spektrum page in fact the altimeter is (0x12) and the vario (0x40), but I think that these are the IDs of the sensors connected via Xbus, the latest generation receivers have the vario and the altimeter integrated, and they are not detected by the telemetry...

**Comment by bsongis-frsky** [comment]
Have you tried to delete all sensors and detect them again?

**Comment by rickisound** [comment]
yes certainly

**Comment by Quimb0** [comment]
Hello. If you perform several tests and it does not show data reception. Test with various AR20400T type and compatible receivers from HK and LemonRC

**Comment by bsongis-frsky** [comment]
> Hello. If you perform several tests and it does not show data reception. Test with various AR20400T type and compatible receivers from HK and LemonRC

More info needed about the missing sensors, I don't have the needed hardware to follow all brands ...

**Comment by Quimb0** [comment]
Ok, how can I send a video for review?

**Comment by Helischorsch** [comment]
Hi Bertrand,
also the Battery Current/Capacity (Dual Batteries) 0x34 (aka FlightPackSensor) is not found during the sensor search.
I tested it on my desk:

My Spektrum DX10T finds all sensors of the AR637T receiver and the FlightPackSensor connected via XBus
![grafik](https://github.com/user-attachments/assets/2fb9273b-4d79-4820-a75f-44c1cb7c2b9b)

My X20 with Ethos 1.5.15 EU doesn't find the FlightPackSensor (also after deleting all sensors and a new search)
![grafik](https://github.com/user-attachments/assets/80aa3ba7-15d4-43d5-b426-977092f5fa82)

![grafik](https://github.com/user-attachments/assets/15aff32a-f728-47e4-8c8b-8084f865fbc4)
![grafik](https://github.com/user-attachments/assets/7cc42946-8523-45a2-b768-7805291cb47b)
![grafik](https://github.com/user-attachments/assets/bfe1772a-415c-488f-8215-4fbf43279791)

Where the U/min, A3 and Temp.2 sensors come from is unclear to me but perhaps this are the three values of the first of the two channels in the FlightPackSensor:
![grafik](https://github.com/user-attachments/assets/e81fb457-f6a9-4209-9a1d-a6d4f8366fc2)

Also no RSSI value (only 0db Ext.) is shown on the top right of the screen.

Perhaps my infos will help to find the problems. 
If you need further assistance in analyzing the problem, I may be able to help.

BR

**Comment by bsongis-frsky** [comment]
It should be good in the next nightlies (not tonight, we are not ready yet!)

**Comment by Quimb0** [comment]
Do you plan to include this in the next version? What would be useful to help? Thanks

**Comment by bsongis-frsky** [comment]
Is it possible that somebody who has the hardware does some tests on the latest nightly so that we can be sure that Spektrum Telemetry works correctly now?

**Comment by rickisound** [comment]
I tested with the nightlies version, now the altimeter telemetry data also works, the RSSI value on the topbar is still missing and that would already be an excellent result.
![IMG_5645](https://github.com/user-attachments/assets/4ee128dd-3eac-41cc-9930-868799113546)

**Comment by bsongis-frsky** [comment]
Do you know what should be the units, low and high thresholds for this RSSI sensor?

**Comment by rickisound** [comment]
I don't know the real values, but doing range tests with the original spektrum radio, the RSSI value is scaled with a maximum value of 100% and as a minimum value I arrived at 6% by reducing the power and moving away about 30 meters, but I noticed that the frame loss started with the value below 30%.
with the multiprotocol module instead the maximum value detected is 31db, I think the sensor is the same, but with a scale for spektrum 0>100%, in the multiprotocol 0>31 db

**Comment by Helischorsch** [comment]
As soon as there is a X20-EU nightly available i can do some tests with my equipment.
