### ISSUE TITLE
after upgrade 1.5 - No choice for language display - Only english 

### ISSUE THREAD

**Issue by osegouin** [FrSkyRC/ETHOS-Feedback-Community#3548]
After upgrade on version 1.5.0, 
I've only seen the English menu in the language selection in display?
for audio messages, i've got my choice of language
Twin Xlite S

**Comment by Skippydi** [comment]
Did you update with the current Ethos Suite 1.5.0?

**Comment by osegouin** [comment]
No, i updated with Ethos Suite windows 1.4.15,  this is the only version available on https://ethos.frsky-rc.com/

**Comment by mgsanna** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.5.0/Ethos-Suite-Windows-1.5.0.exe


and please select i18n for the translations that you need

<img width="885" alt="Screenshot 2024-03-03 194011" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/43d3b159-5da6-4333-b767-76fe66029097">

**Comment by osegouin** [comment]
Thanks, after rewriting firmware with V1.5 all is ok.
A big up to Thierry and Marco !
