### ISSUE TITLE
Model data file cannot be loaded (corrupt)

### ISSUE THREAD

**Issue by miff69** [FrSkyRC/ETHOS-Feedback-Community#3549]
I have successfully transferred a model from an X20 Pro with BT (send model) to an X20S. When I load the model on the X20S, an error message is displayed (model data corrupt). Both transmitters are flashed with ETHOS 1.5 (release). The same problem also exists when I copy the model file manually (Windows Explorer) from one transmitter to the other. 
Attachment: zipped model BIN from X20 PRO.

[strega.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14474219/strega.zip)

**Comment by bsongis-frsky** [comment]
This model is loaded correctly on your X20PRO, right?

**Comment by bsongis-frsky** [comment]
Your model has PlayText which is impossible on X20S
It will be fixed in 1.5.1

**Comment by miff69** [comment]
You were quicker with the fix than I was with my answer🫡 Yes it's a X20 PRO model file and I'm using TTS for flight modes

**Comment by miff69** [comment]
With 1.5.1 it's working fine!
