### ISSUE TITLE
archer sr10plus servo output corrupted

### ISSUE THREAD

**Issue by ilioSS53** [FrSkyRC/ETHOS-Feedback-Community#3550]
Hello,

With the version 1.5.0 I wanted to make a new model plane.
Archer sp10plus bind. Ok. 
As I was configuring the gyro function stable and level flight mode i started the selftest.
The connected servo,s rotate standstil and where no longer able to move on command from transmitter. Only the channel 3 the throttle is possible to have a esc/servo operational.
I treid almost everything to reinstate the original function of the receiver,
S.a. reset, mede new model etc. Etc, etc. No succes.
It looms like the selftest by moving the servo,s demaged the receiver in one way or the other. My best gues burning the powersupply to the servo,c. But howe about the channel 3?
Very sat it cost my a receiver.
Kind regards, Theo.

**Comment by FrSky-GX** [comment]
Try to do the selfcheck when put the reciever in manual mode， it should work.

**Comment by Wolepo** [comment]
Did you also move the sticks at the right time during the self-test?

**Comment by ilioSS53** [comment]
Good morning,
So doing the selftest was not smart unknown about howe and why.
Resulted in freeze the outputs.
But the receiver is recovered and life and kicking.
What I did,
Firmware 1.5.0 removed from transmitter and installold version 1.4.15 eu
Flashed the receiver with the latest version HW 1.2.0  FW 1.0.10
Not possible via ota so via servo plug on top of receiver
Calibrated receiver.
Made new model
Set in script SRX Stable  Stabilizing off and quick mode off.
Output pins on receiver came to life.

Hope this helps to be awair howe to perform selftest.

Kind regards, Theo

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Nerenye** [comment]
what made the pins come to life is the last point in your list. switching stabilisation to off.

i guess you forgot to set the limits while self test was on. so the reciever thinks the limits are stick center resulting in no movement range.

happened to me several times. you need to start self test and then move EVERY output channel to its MAX and MIN values.
Usually by moving the sticks and sliders.
after a reciever restart everything should work fine

**Comment by ilioSS53** [comment]
@starting the selfcheck the servo s moved by themself. And stopped. No more control from stick possible.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
