### ISSUE TITLE
Radio dead when installing 1.5.0.  

### ISSUE THREAD

**Issue by Crunch69** [FrSkyRC/ETHOS-Feedback-Community#3552]
x20s Radio dead after installing 1.5.0.         1.5.0 updated all firmware and then stopped and froze on boot loader update radio stating there is no connection.  now will not power up. power button is dim blue if you press and hold it.  if you press enter and power screen will light dimly and says boot loader if you plug it into PC it switches to USB ethos program see it as a x20S but if you try to write boot loader it says there is no connection

**Comment by J-charles-C** [comment]
I, 

Unplug the battery before reconnect it. Test after.

Jc

**Comment by mgsanna** [comment]
Put the radio in bootloader mode revert to this specific version 1.4.15 to update the bootloader, turn on radio, it should be updated to 1.4.15.
Then update to 1.5.0, in your radio maybe was installed an “old” non-auto switching bootloader, so it get this kind of problem….

**Comment by bsongis-frsky** [comment]
Exact, next Ethos Suite won't allow the user to install 1.5.0 if his bootloader is not up to date
