### ISSUE TITLE
Mixed mode between TD-Mode and Access-Mode in Ethos possible?

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#3553]
As a security feature I'm using TD-Receiver in combination with my X20S. When I enhance the channels with a second or third receiver to separate circuits for Sound and Light and other functions, I like to use the easier Access receiver. But this is not possible, because there is only a general selection for the mode (TD Mode / Access Mode) and not individual per receiver in Ethos. 
Not knowing the technic in detail, others told me that the difference is too big between the types to make it happen, but a RX in combination with 2 Archer ist also possible. 
If there would be an option to make this happen it would be great. 
My preferred combination would be than a TD-Reciver as a main and 2 separate Archer for other functions / sound / light for an easy setup to have fully independent circuits. 
Best Regards
Bernhards

**Comment by SmartTommy** [comment]
Hi, 
The  TD_ISRM  transmitter (built-in X20S) can't run TD Mode and the Access Mode at the same time.

**Comment by BernhardFe** [comment]
Ok, thanks a lot for your fast answer.
