### ISSUE TITLE
VARS enhancement 

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#3554]
Running v1.5.0 on X18SE.

There is a cosmetic issue with VAR's on the X18SE, and a mathematical issue, (at least that what I am thinking).

1. Cosmetic issue. The attached picture shows that not all values are being shown in their respective boxes. This goes to all numerical values in the VAR page.
2.  There is, in my opinion , an issue with min and max. If I set the range -15% to +15%, and I set the source for VAR as POT1, I would expect that when the pot is fully counter clockwise, i.e. -100%, and fully clockwise, i.e. 100%, the output value should be -15% and 15% respectively, with middle 0%. However, slightly turning the POT will reach either -15% or 15%, and then there is no more output.

For 2 above, I found a very good use in helicopter, where I can set hovering pitch and hovering throttle by adding two, 3-point curves and the input for point 3 will have as a source this VAR.

However, I only wanted to have a 30% range, (-15% to 15%), with a pot from fully counter clockwise to fully clockwise.

Thank you for this great update! 

![VAR1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68815554/5fc8ac52-58f6-4066-80ce-6fa5b6fd1a34)

**Comment by Wolepo** [comment]
There is no automatic scaling. And that is correct. For your task, you will have to use an auxiliary mixer with the values source=pot1, weighting=15%.

**Comment by salibaj2** [comment]
Can you give me an example how to do it?

Adding a mixer and then select 2nd point on the curve to achieve what it was my intention doesn't look easy.

As I see it, VAR's would have this so much easy, but, not scaling the output doesn't make sense, in my opinion.

It looks awkward to set the min and max of VAR's to -15% to 15%, use the POT as source, and then you turn the POT 1mm and reach these 15%.

I am sorry, I do not agree with you that this is the way it works. Output should be scaled to the complete rotation of the POT.

**Comment by mawzthefinn** [comment]
The pot isn't the only way to adjust the Var, it's just one of many.

The min/max are clipping endpoints (same as they are in Outputs, where everything beyond -100% to 100% is clipped)

**Comment by salibaj2** [comment]
Adding to my last comment, every channel have `Weights'.

When these `Weights' are reduced, i.e. to 30% for example on aileron stick, it does not mean that the stick will only output to 30% of it's movement, but the 30% will then be distributed along the full throw of the stick, (scaled).

**Comment by salibaj2** [comment]
Sorry Maas, I was typing my message and now I saw yours.

The problem is that if I set the output to 15%, you only move the trim just about it's mechanical centre point. 

What I thought it would be that this would be scaled, and use it.... in my case, to adjust only by 15% the mid-point, (2nd point) out of 3 of a curve, and will be a 30% along all of the pot travel.

**Comment by WhiskeyGolf** [comment]
It would actually make things easier if you could add curves to the vars.  Currently you have to create an extra free mix, add a weight, add a curve, route the mix into a channel and then integrate the channel into the var.  this could all be done with a single curve

**Comment by salibaj2** [comment]
Radio Tx X18SE.

Updated to v1.5.2 and still, in VARS, is not displaying the full value.

Also, I am still begging to do scaling for when a POT is used for a VAR.

Thanks.

**Comment by bsongis-frsky** [comment]
I think that a new option applied to the Source (hidden behind the hamburger icon) will fit perfectly and will avoid to mess with more Vars.

Idea merged inside #3821 which I have just opened to list all Vars enhancements
