### ISSUE TITLE
ETHOS SUITE crashed allways after first update ETHOS Transmitter

### ISSUE THREAD

**Issue by NorbertHeli** [FrSkyRC/ETHOS-Feedback-Community#3555]
The problem is since a longer time, but during the different 1.5 RC1/2/3.....8   I installed the suite every time with the actual one.

When new installed, the suite recognized the transmitter ( X20S ) and updated it. During update the ETHOS version at the transmitter, the suite lost connection to the transmitter. The update at the transmitter was ok and I had the new version. This happend at both of my two X20S and also at twin X lite. Starting again the suite the same problem. 
When I installed a newer Suite Version all my transmitters are known again and I see my modells and so on. The same suite version installing doesn`t help.
After updated any one of my transmitter all transmitter are unknown at the suite.

Now I got the X20 pro and installed 1.5 Final. Also here the same behavier. The suite again crashed, told me that and I have the crashfile.

Till now I thought is a special problem of my computer, but now I read here the same problem: 
https://www.rcgroups.com/forums/showpost.php?p=52191657&postcount=28293

It seems its a problem for more people. Also we discussed at the Engel frsky forum about, with no result.

Latest when model editing at the suite is possible, the suite must run reliable to use it often with different transmitters.

**Comment by bsongis-frsky** [comment]
Perhaps you could attach the crash file here?

**Comment by NorbertHeli** [comment]
Here some more Infos: I allways have USB Connection, can read or write. Only Suite says no connection. Only when a newer suite is installed, suite works with transmitter together. When more infos neccercary - please ask.

Thank you for helping

![1 Flash](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/fa7fba29-d5fd-4f32-ad06-8a0b676c6416)
![2 FatError](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/2b8d3592-06ff-40ae-b5f6-284f1357f200)
![3 writeOS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/e2f9e12e-9e13-4062-a98a-e4372a979fe9)
![4 USB](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/d5f92b37-bac9-48e0-84ea-c86677c3294f)
[debug-20240229.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14482065/debug-20240229.txt)
[debug-20240302.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14482067/debug-20240302.txt)
[debug-20240303.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14482068/debug-20240303.txt)
[debug-20240304.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14482069/debug-20240304.txt)
