### ISSUE TITLE
up grades keep breaking things

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3556]
the last upgrade messed up sound files, curves.  and one of the previous upgrades messed up the telemetry stability.  It was fixable by a firmware upgrade on the receiver, but worked fine before with out the firmware upgrade.  always finding something that doesn't work after upgrades.  sometimes it is a while before i find the problems as i don't try the upgrades on all 50 devices i have.

**Comment by bsongis-frsky** [comment]
You are not forced to use 1.5.0 ;)
We try to do our best to fullfill users requests and 1.5.0 is a major release.

**Comment by williajgr** [comment]
I do like the features in 1.5Sent from my iPhoneOn Mar 4, 2024, at 9:11 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
You are not forced to use 1.5.0 ;)
We try to do our best to fullfill users requests and 1.5.0 is a major release.
