### ISSUE TITLE
System language

### ISSUE THREAD

**Issue by potapot** [FrSkyRC/ETHOS-Feedback-Community#3559]
I have a Frsky Tandem x20s. Yesterday, using Ethos Suite, I upgraded to the release 1.5.0. 
Everything works fine but the system language is only in English. I need Italian.
Today I upgraded to the release 1.5.1 but nothing changed.
The audio files are in several languages, but the system language only in English.

**Comment by mgsanna** [comment]
Allora nella suite di ethos.... devi selezionare l'italiano nella sezione i18n, poi riflash il firmware e i file i18n
se non riesci contattami direttamente via mail marcogsanna@gmail.com, sono il traduttore del software e della suite e del manuale
![WhatsApp Image 2024-03-03 at 12 29 43](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/3c321727-e7d6-4af4-8eb0-d75419968125)
come vedi a fianco della scritta aggiorna componenti obsoleti c'è un triangolino che apre un menu a tendina devi solo scegliere "**scrivi firmware e i18n**"

**Comment by potapot** [comment]
Ciao, grazie mille per la tua risposta. Quella schermata che hai tu, io non
l'avevo mai vista. Sono entrata ora nella suite Ethos e mi ha detto che
c'era un aggiornamento da fare. Ora finalmente vedo la tua schermata. Provo
a fare quello che mi hai detto e ti faccio sapere.
Grazie mille, gentilissimo.

Dolina

Il giorno lun 4 mar 2024 alle ore 18:03 Marco Gualtiero Sanna <
***@***.***> ha scritto:

**Comment by bsongis-frsky** [comment]
Tutto bene?

**Comment by mgsanna** [comment]
> Tutto bene?

Hi Bertrand, I've an issue with only one term translation on freemix ? the term is operation and his sub menu title....
Inside the i18n files of simulator and even inside the i18n of the radio I cannot find it....to update the translation....

**Comment by potapot** [comment]
Ho fatto come mi ha gentilmente  scritto mgsanna e finalmente ho il testo in italiano. Purtroppo però è sparito l'audio...
Grazie mille per l'aiuto e vedrò di risolvere anche questo.

**Comment by mgsanna** [comment]
l'audio va "aggiustata una piccola cosa sulla sdcard ti invio una serie di screenshot
![WhatsApp Image 2024-03-02 at 20 00 52](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/bdf7ec93-0cda-45df-9cbb-c5e954986069)
una volta messa a posto la directory seleziona la voce 1 con l'audio della radio
![WhatsApp Image 2024-03-02 at 20 02 28](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/92422903-bd2a-4958-ab83-d3df1775da7d)
come puoi vedere la struttura della directory va solo modificata ma funziona tutto, purtroppo non era possibile fare una procedura univoca per tutti (vista la quantità di file personali e cartelle personali utilizzabili)

**Comment by potapot** [comment]
Fantastico!!! Grazie mille. Risolto tutto.
Scaricato pure il manuale in italiano rev 4. Ottimo lavoro.
Grazie per il vostro prezioso aiuto e buona serata.
Dolina

**Comment by mgsanna** [comment]
A questo punto chiudi la issue ok?

**Comment by potapot** [comment]
Sì, grazie.
