### ISSUE TITLE
impossible simple glider programmation,

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#356]
Hello, actually it is really difficult to acheive programmation of a glider , 2 ailerons, 2 flaps without using a virtual channel use as an entry source. I see i am not the only one. I will try to resume what is missing for not being forced to use multiple mixer.

I think **in each mixer dedicate to glider** (ailerons, alieron to flaps, rudder, camber, butterfly) we sould always have:

-curves for **_expo and dual rate_** apply to the entry source. (or using entry like in OTX)

-**differential** 
-poosibilty to apply **weight, variation and/or curve on each output** channel to compensate the difference of travel between ailerons and flaps without loosing the effect of differential, expo and dual rate when it is done in an other mixer.

**Comment by hrenz** [comment]
Yes 
Weight and offset always belong together, then you can set everything
Offset start value = 0%

**Comment by mawzthefinn** [comment]
Offset has generally been addressed, and weight per output channel is available on the mixer types that target different surface types at the same time. 

There is still some room for improvement, especially in the Ail to Flaps case where aileron trim is applied.
