### ISSUE TITLE
Tandem XE and switches 1.50

### ISSUE THREAD

**Issue by Amahoser** [FrSkyRC/ETHOS-Feedback-Community#3561]
Updated to 1.50 on my Tandem XE.

Noticed that most of my switches stopped working. I was able to troubleshoot and figure out the problem. When I upgraded to 1.50,  it reverted all my switches to Switch 1. 
![20240304_102644](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/86579409/8cc2c072-ffb7-42fb-9253-8004f28b1dca)

I had to remap all my switches in SYS - HARDWARE - Switch Settings

Then all was good.

**Comment by Dsrenger** [comment]
Already fixed in 1.5.1
