### ISSUE TITLE
Ethos 1.5.0 Timer - Audio Action/Play file not working with other languages than US/GB

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#3562]
Frehly installed the new Ethos 1.5.0. Downloaded language DE + NO in addition to default US/GB.
Trying to set up a new Timer with the new Audio Action as per the new manual (rev.4). 
Have sucsessfully created and found working
1 - Audio Action 1: Countdown, Start 15 second, Step 2 and 
2 -  Audio Action 2: Beep countdown, Start 10 second, Step 1,
BUT
3 - Audio Action 3: Play file is not working with other languages than US/GB.
If General/Audio/Language is set to English and Voice 1 set to US/GB, the Play file meny in Timer is populated with selectable sounds.
BUT if General/Audio/Language is set to Norwegian or Deutch and Voice 1 set to "default" (the only selectable choice), the Play file meny in Timer is empty.

**Comment by bsongis-frsky** [comment]
Where have you installed your custom audio files? They should be in the corresponding voice directory ...

**Comment by mgsanna** [comment]
This is for Italian (as per deutch or Norwegian)the screenshot of directory
![Immagine WhatsApp 2024-03-02 ore 17 45 40_278667ac](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/68fdfd5a-ba21-4596-bc65-ad38d40ef7dc)

**Comment by mmasch** [comment]
Yep. I have the same file stucture as mgsanna. Located on the SD card. 
However,  have no custom sound files. Only the ones loaded from the Suite install.

**Comment by mgsanna** [comment]
> Yep. I have the same file stucture as mgsanna. Located on the SD card. However, have no custom sound files. Only the ones loaded from the Suite install.

You have to install your custom file, so you can play the sound file

**Comment by mmasch** [comment]
> You have to install your custom file, so you can play the sound file

Copied the WAV-file butterfly-off.wav from SD:/audio/en/us to SD:/audio/no/default
The file did then show up/was selectable in the Timer - Play Audio item. 
Thank's for the help  :-)  
I'm closing this post.
