### ISSUE TITLE
EthOS 1.5.1 French language not available for texts on XE TANDEM

### ISSUE THREAD

**Issue by Majestic63** [FrSkyRC/ETHOS-Feedback-Community#3563]
I install the new release on my XE TANDEM today. French voice is working, but I can't select french in laguage menu, it doesn't appear.

firmware 1-5-1
bootloader 1.4.15
rf module 2.2.6
audio english & french 1.5.0

thanks

**Comment by mgsanna** [comment]
Install the i18n file
<img width="885" alt="Screenshot 2024-03-03 194011" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/2001335e-8d8a-4ab9-9ccd-46a02ca6806c">
and then select write firmware & i18n

**Comment by strgaltdel** [comment]
could be same as #3572

**Comment by Majestic63** [comment]
Sure.
I have two friends, one with a xe tandem too, the other with a x20, they have the same problem since yesterday and the new update
