### ISSUE TITLE
Problème chevauchement de texte langue fr

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#3564]
Ethos 1.5.1 Tandem xe

![Screenshot_2024-03-04-21-09-16-869_com miui gallery](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89158034/0f480a42-d38b-4ed2-8feb-32b3eaf37635)

**Comment by bsongis-frsky** [comment]
On a décidé d'utiliser le mot "Course", plutôt que "Débattement"
Prêt pour 1.5.2
