### ISSUE TITLE
ETHOS suite crashes on update from 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#3566]
ETHOS suite crashes on update from 1.5.0 to 1.5.1 using ethos updater 

here is the crash log
[crash-20240305.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14490458/crash-20240305.txt)

**Comment by yak-54** [comment]
i download it from github install in manually it did not crash on install

**Comment by Crunch69** [comment]
yep had the same issue
