### ISSUE TITLE
X20 pro will not power on after updating from 1.5.0 to 1.5.1 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#3567]
X20 pro will not power on after updating from 1.5.0 to 1.5.1 using ethos suite 1.5.0
now when i plug the radio in windows ask to format storage before using

**Comment by yak-54** [comment]
now when i plug the radio in windows ask to format storage before using

**Comment by Crunch69** [comment]
yes had similar problem will it go into boot loader? if yes check what version of boot loader is installed then install firmware that is close to that version of the boot loader.   install manually by  put radio into boot loader mode drop the firmware into the root of the SD card the detach the radio from PC it should install the firmware after that allow window to scan the SD card to fix.  if your boot loader is not up to version 1.4.17 manly install the same way. after that is installed  you can run ethos suite to update to 1.5.1. might have to install the latest for the RF module manually

**Comment by yak-54** [comment]
yes it on version 1.4.15 boot loader
 i can get it to bootloader mode 
i did roll tx back to 1.4.17 working fine so i did update to 1.5.1 again same thing will not boot when i plug it to pc windows is asking to repair drive
to me  looks like its an ethos suite / windows driver issues 

so i used ethos repair tools to fix the drive and re install 1.5.1 using the old way putting firmware on the nad drive and booted into bootloader mode  let it write the firmware all good now the starts into 1.5.1

**Comment by yak-54** [comment]
ETHOS suite / WINDOWS driver issues do an manual update copy the firmware bin to nad  in bootloader mode works fine

**Comment by mrdhhall** [comment]
Where do you get the firmware from i have X18RS i can only boot into bootloader?
