### ISSUE TITLE
Ethos 1.5.1 Model Manager not functional (Windows 11)

### ISSUE THREAD

**Issue by Luznatural** [FrSkyRC/ETHOS-Feedback-Community#3568]
After upgrading Ethos to release 1.5.1, and the flex firmware on my X20S to the same, I found out that the model manager is not functional at all. You can select the folder where I had previous backups of my radio, but there is no way to perform any backup nor restore, as the screen doesn't show any button to perform the action. You cannot see either the models already existing on the radio.
Windows 11 23H2

**Comment by yak-54** [comment]
its  windows driver issue 
when you plug your radio in can you see the 2 drives
![Untitled](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/24dbf879-e4b2-4396-9bb4-7faa08a3c6ac)

**Comment by Luznatural** [comment]
Yes, I can see the drives without problem, and the suite detects and updates the radio without any problem. When you access the Model manager, you can select the folder where I have my previous backups, but I cannot do any other thing, as you cannot see the models, and there is no button to perform backups nor restore

**Comment by Nicholas-Luoyi** [comment]
Would you please post the screenshot of the model manager? The buttons should be there as it has already been reported and fixed in 1.5.0

**Comment by Luznatural** [comment]
Here you have it:

![ModelManagerScreen](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/43551716/6659a10d-e92a-47f1-ac72-69484a93439a)

**Comment by Luznatural** [comment]
I tried also performing a fresh instalation from scratch, and no luck. The screen is as the picture above.

**Comment by strgaltdel** [comment]
makes "starting suite with admin rights" any difference ?

could it be that it is a mix of of "suite & windows access things" and now the suite generates other file-ownerships then before ?
did you try to copy the Backup folder outside the "my documents" folder and inherit new rights (maybe full rights to "everyone") ?

do you see any events regarding (prohibited) access to the folder in the win event logs after you try to reach it by suite model manager ?

**Comment by Luznatural** [comment]
Finally Udo was right. Thank you very much
I selected another folder for the backup that was far closer to the rooth of the hard disk and adjusted the priviledges. Now everything appears to be normal and I could perform a backup.
Another lesson learned on Ethos.
Thanks again

**Comment by Luznatural** [comment]
Complementing information: the folder where you place the backups should not be placed too deep in sub-folders. Apparently, there might be a limit on the length of the path of the sub-folder. The problem was solved when I placed the backups in the folder C:\Backup.
I will tell you if I find the maximum length.

**Comment by dixi83** [comment]
Is there any info about when this will be re-implemented?
