### ISSUE TITLE
Vars problem

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3569]
Dear Ethos Team, I have discovered a problem in the VARS. If I set a fixed value and then want to change this value using a switch, this switch value is added up until 100% is reached. This doesn't happen if I set the fixed value using a pot or switch.
(see video)

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/84040ebf-67fe-4a11-9e64-2e93ac7e2f88

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/054d301e-9ed1-4135-8e4e-e8ece082077f

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/4e644b3c-75c3-4f8e-bfd7-a2505aa94809

**Comment by Jedsters** [comment]
@Skippydi could this be related to #3426  ?

**Comment by Skippydi** [comment]
> Könnte dies mit #3426 zusammenhängen?

Yes, this exactly the same.
I think it is problematic to automatically increase a value if, for example, a switch is used as a trigger. It might make sense for trimming, but for a variable I want to be able to influence the value with certainty. An example would be the possibility of changing the variable to adjust the GAIN value on a TD SR8 depending on the flight speed.

**Comment by Jedsters** [comment]
You may want to add coments to #3426 as that is still under discussion.

**Comment by hrenz** [comment]
Vars?
How can we preset a value at start/open/select of the Modell one time.
how can we init a one time impuls at log switches  at start/open/select of a Modell for that 

or with a system event one time start/open/select a Modell

and we need a curve

Autorepeat on/off   with   slow/fast/custom
