### ISSUE TITLE
When a folder contains larger number of files, accessing menu of files further down the list jumps to the first file.

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3570]
With the introduction of Log Viewer, I noticed that when the logs folder contains a larger number of files (mine is currently at 555 files after a season) when I try to access logs listed further down the folder, selecting it results in cursor jumping to the first file.

It should also be useful to put logs of each model into a separate folder, preventing the need to scroll down through a large amount of files.

Of course, I can delete the old logs so the priority is not too high here ;-)

**Comment by RealTadango** [comment]
Folder for reach model is what i suggested earlier. And sorting by date descending....
