### ISSUE TITLE
Ethos 1.5.1 problems with languages other than English (Text and Audio)

### ISSUE THREAD

**Issue by Luznatural** [FrSkyRC/ETHOS-Feedback-Community#3572]
This issue happens both in my X20S and in my X12S ISRM
With Ethos 1.5.1 firmware installed on both radios, you are no longer able to select any other language than English for the menus, despite the fact that you have loaded it during the firmware update (In my case Spanish, but I have tried German and French with the same behavior). No other option appears when you try to change it.
In the audio menu, when you select your language, no sound is reproduced. Not even the "welcome to Ethos". Only English is producing sound, and you can select British or US audio sound without problems.

**Comment by ahvink** [comment]
No problems with Dutch.....

**Comment by strgaltdel** [comment]
menu language:
maybe you didn't checkmark the language in the suite before starting the upgrade process ?

i think you can reflash by using suite, 
choose only fw&i18 component, 
checkmark the languages you want, 
and start the fw update only


sound:
there are several examples on rcg how to get sound working in case the setup is not ok

lutz sounds a little bit german like
in case you've access to german engelmt forum,
i've started dedicated threads for each "most common problems" during 1.5 update

can be found in "operation systems//ethos//problems
in case you have an account:
https://www.frsky-forum.de/forum/index.php?board/199-fehler-bugs-im-ethos-betriebssystem/

**Comment by mawzthefinn** [comment]
1.5 adds proper Internationalization support.

Make sure you installed the correct languages in Suite and they will be present in ETHOS.

**Comment by Luznatural** [comment]
I did check both En and ES before the upgrade. Same result. It simply doesn't show in the menu to be able to select it.

**Comment by philandroid36** [comment]
I had the same problem today with 1.5.1.
I had to start the update again by forcing "write all components" and then it was ok for me.
I was able to choose French.

Not succeeding would have been embarrassing because I am in the process of translating in french the ETHOS 1.5.1 documentation ;)

**Comment by Luznatural** [comment]
The same happens to me, as I am translating to Spanish the manual of 1.5.1. (I did the actual one already in the documentation)
By the way, would it be possible to get access via private to the file containing the graphics of the radios included into the initial pages on the EN version? In order to edit the labels I would love to have an editable version different than Pdf.
Thanks in advance

**Comment by philandroid36** [comment]
you simply have to copy and paste into an editor.
For example with Windows, I use the "Snipping Tool" to select the image, I copy it then paste it into our good "Paint" to modify the labels

**Comment by bsongis-frsky** [comment]
With the new "default" voice, everything should work as in 1.4, with more features

**Comment by bsongis-frsky** [comment]
@lthole I let you answer to the question about the original document, useful for translators?

**Comment by lthole** [comment]
@bsongis-frsky Please add the translators to the Skype 'Manual Check' room, then they can pick up the original .odt file of the manual, as well as the Ethos_changes.xslx tracking sheet.

**Comment by bsongis-frsky** [comment]
@Luznatural is your SkypeID "luznatural"? I would like to add you to the "Manual Check" Skype room.

**Comment by bsongis-frsky** [comment]
@philandroid36  is your SkypeID "philandroid"? I would like to add you to the "Manual Check" Skype room.

**Comment by Luznatural** [comment]
My Skype id is jaime_m_d
Thanks in advance



-------- Mensaje original --------
De: "Bertrand Songis @ FrSky" ***@***.***>
Fecha: 11/3/24 8:47 (GMT+01:00)
Para: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Luznatural ***@***.***>, Mention ***@***.***>
Asunto: Re: [FrSkyRC/ETHOS-Feedback-Community] Ethos 1.5.1 problems with languages other than English (Text and Audio) (Issue #3572)


@Luznatural<https://github.com/Luznatural> is your SkypeID "luznatural"? I would like to add you to the "Manual Check" Skype room.

**Comment by bsongis-frsky** [comment]
Would you ping me? I cannot find you!

**Comment by philandroid36** [comment]
Hi.I just create an account for Skype with philandroid. It's OK now.I can read and translate but i can't speak in english. Sorry.I am french.Le 11 mars 2024 08:48, "Bertrand Songis @ FrSky" ***@***.***> a écrit :
@philandroid36  is your SkypeID "philandroid"? I would like to add you to the "Manual Check" Skype room.

**Comment by Luznatural** [comment]
The sounds in ES are now reproduced well in Ethos 1.5.2, but the problem selecting the ES languaje in the menus of the radio continues. Only English is selectable. No other option appears, despite of selecting it in the suite settings, when updating.
In the i18n folder of the SD on the radios no file is present, despite I chose the option "write all files" when updating with the suite.
All the languaje *.json files are correctly present in the i18n folder of the suite.
