### ISSUE TITLE
Ethos Suite 1.5.1. Model Manager has no Model Backup

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#3573]
Ethos Suite 1.5.1 with TWIN X14, Ethos 1.5.1 has in the model manager option page no option "Models" so the backup does not contain any model.

![Ethos Suite ](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/f1795592-e51d-4275-a040-575b02e7c142)

**Comment by ahvink** [comment]
No issues on 1.5.1 on my X20S (MacOS version)

<img width="856" alt="Scherm­afbeelding 2024-03-05 om 12 39 46" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/697422/c5e1365f-ed32-4632-af40-dc37ad0f5b56">

**Comment by Wolepo** [comment]
The models are also available for selection at meinwer X10Express. It is therefore an error in connection with the X14.

**Comment by Luznatural** [comment]
Something similar happens to me. Already mentioned in #3568 X20S with Windows 11

**Comment by Nicholas-Luoyi** [comment]
Did you switch the model location to the SD card?

**Comment by glipski50** [comment]
> Did you switch the model location to the SD card?

No, it‘s on thr flash drive „Radio“.

**Comment by strgaltdel** [comment]
In case it's a windows access problem to the radios's model files a start of suite with admin rights could help

Gerhard,
are all of your model files really converted into 1.5?
Maybe there is a "suite filter" in case the models files are not persistent to the Tx-Ethos revision or something else ?

there is another issue where audio folder structure seems NOT to be adopted in a usual 1.5 way in the X10s Firmware,  
so i wouldn't rule out it's a specific X14 thing like Wolfgang mentioned
(but #3568 would speak against it)

regards
udo

**Comment by Luznatural** [comment]
How do you know if the models have been converted to 1.5.?
My radio didn't say anything about, but the planes are fully functional in the radio.
Would you mind to elaborate?
Thanks in advance

**Comment by spoke2570** [comment]
> How do you know if the models have been converted to 1.5.? My radio didn't say anything about, but the planes are fully functional in the radio. Would you mind to elaborate? Thanks in advance

The models convert when they are loaded (selected as current model) in the radio that has the 1.5.x firmware running on it.
