### ISSUE TITLE
Ethos Suite FRSK firmware update version incorrect

### ISSUE THREAD

**Issue by RobinS49** [FrSkyRC/ETHOS-Feedback-Community#3574]
On connecting my XE Tx to Ethos it showed my Internal Module firmware to be out-of-date at v2.2.4. I used Ethos Suite’s FRSK Flasher to download and update the firmware to v2.2.6 and confirmed it had completed it by checking the version on my Tx, however, Ethos Suite continues to show my firmware version as v2.2.4 i.e. it states it is out of date.

**Comment by mawzthefinn** [comment]
Which Suite version, this was a known issue with some later 1.4x versions of Suite.

**Comment by RobinS49** [comment]
I have just upgraded to version 1.5.1.

Robin

**Comment by erichabg** [comment]
Same problem on my side with X20S.
Ethos Version V1. 4.17,  Ethos Suite V1. 4.15 and also V1. 5.0.
Info on X20S shows right Version 2.2.6.

Am 5. März 2024 13:40:55 MEZ schrieb RobinS49 ***@***.***>:

**Comment by strgaltdel** [comment]
I could solve the problem by rebooting (cold start) my notebook (and tx)

Does your suite show the outdated Rev even after restart ?

**Comment by RobinS49** [comment]
I’ve rebooted both my laptop and XE Tx, and the problem still persists.

**Comment by RobinS49** [comment]
I’ve rebooted both my laptop and XE Tx, and the problem still persists.

**Comment by strgaltdel** [comment]
Too bad it didn't work for you
all in all it's a duplicate of #3528
