### ISSUE TITLE
X20S / X10S Express update 1.15.0/1.15.1

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#3575]
Unable to set timer with voice and throttle to start count down as with older version 1.4.17 and older.

**Comment by mawzthefinn** [comment]
You need to specify a Voice in System->General before you can set one in Timers and Special Functions. 

Timer functionality has changed significantly with 1.5, I would suggest reviewing the manual for 1.5.

**Comment by hershg21** [comment]
I have looked over the new manual many times. I feel there should be examples of what needs to be done since significant changes were made.

**Comment by bsongis-frsky** [comment]
The new "default" folder will be created for all languages, and selected by default, so that the behaviour will be exactly the same than 1.4
