### ISSUE TITLE
unable to play values

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#3577]
X18se, firmware 1.4.17, not able to get it to play values from the special functions. Have tried a number of  different values, 
battery, lipo voltage...Any ideas would be helpful.
Thanks again to the group,
Cheers

**Comment by mawzthefinn** [comment]
No voice or can't select values?

No voice usually means your audio file locations are messed up. For 1.4.17 and English those files need to be in /audio/en/system/

These locations change with 1.5, so if you have the 1.5 audio file locations, 1.4 won't play audio.

**Comment by Dsrenger** [comment]
The SF itself should look like this:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/dfd67795-2a54-432d-ae7e-51d10d4e165f)

**Comment by lotus1235** [comment]
I think my wav files are in the system file, not sure how to make sure they are located correctly. The wav files work when I have play a track selected. I can select the play VALUE, but no voice when i use the active switch.

**Comment by mawzthefinn** [comment]
> I think my wav files are in the system file, not sure how to make sure they are located correctly. The wav files work when I have play a track selected. I can select the play VALUE, but no voice when i use the active switch.

Play track plays files located in /audio
Play value depends on system sounds which should be in /audio/en/system for 1.4.17 with English selected.

**Comment by lotus1235** [comment]
Thank you, I'll check where the files are.BillSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: mawzthefinn ***@***.***> Date: 3/5/24  12:24 PM  (GMT-05:00) To: FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc: lotus1235 ***@***.***>, Author ***@***.***> Subject: Re: [FrSkyRC/ETHOS-Feedback-Community] unable to play values (Issue #3577) 

I think my wav files are in the system file, not sure how to make sure they are located correctly. The wav files work when I have play a track selected. I can select the play VALUE, but no voice when i use the active switch.

Play track plays tracks in /audio
Play value depends on system sounds which should be in /audio/en/system for 1.4.17 with English selected.

**Comment by bsongis-frsky** [comment]
Linked to #3584
