### ISSUE TITLE
Mix Graph doesn't reflect Trim setting

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3578]
When you turn Trim on or Off in a mixer the graph doesn't change. Surely the graph should reflect the trim status.

This is a basic model with plenty of trim and trim set on

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/7bdda53e-435d-4c17-bc76-3169da13711c)

but if you turn trim off the graph remains the same meaning that the points no longer reflect the channel outputs

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/62cfced8-791b-460f-800d-0aa8a8bada65)

1.5.1

Thanks

**Comment by bsongis-frsky** [comment]
Fix ready for 1.5.2
I will try to start the nightlies right now
