### ISSUE TITLE
Update 1.5.1 Horus X10S cannot find the audio files.

### ISSUE THREAD

**Issue by Hennyvt** [FrSkyRC/ETHOS-Feedback-Community#3582]
The X10S once upgraded from 1.4.17 does not play any audio tracks. I moved the audio tracks into the old file location and all works fine. I suspect the audio file pointer is still in the original location. Audio is fine when updating the X20S.

**Comment by strgaltdel** [comment]
There are two steps needed to let audio work correctly within 1.5

a) correct audio folder structure
b) declare at least language AND DEFAULT folder in system options

maybe this can be helpfull
https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-X20-Pro-Tandem-24-Channels-with-ETHOS/page1551#post50718883

**Comment by Hennyvt** [comment]
The X10S was fully operational with version 1.4.17. When using Ethos suite to upgrade the firmware to 1.5.1 it upgrades every folder which is out of date, orange color. All were green after the update however no audio was available. The issue was corrected by copying all audio files to the original folder. The chosen language was English. I believe Ethos suite is coping the audio files to the incorrect directory. This process works fine with X20S, only the X10S has this issue.

**Comment by strgaltdel** [comment]
strange,

**_"by copying all audio files to the original folder"_**

it is my understanding, that this folder shouldn't work within 1.5
maybe you're right, a specific X10  migration issue..

**Comment by Hennyvt** [comment]
When you use Ethos Suite it knows where to locate the different files etc.

**Comment by bsongis-frsky** [comment]
Discussion in #3584
