### ISSUE TITLE
Ethos 1.5.0 Italian manual Revision 5

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3583]
Update and some advice to install corectly everything.... (1.5.1)
[X20 & Ethos Manuale utente_1.5.0 rev5 (Italiano).pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14507960/X20.Ethos.Manuale.utente_1.5.0.rev5.Italiano.pdf)

**Comment by bsongis-frsky** [comment]
Thanks!
We have added your pseudo in Ethos Suite About, let me know if you want your firstname / lastname like for some others

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b5f10827-a4a3-4997-92fd-d426ed3fd1ed)

**Comment by mgsanna** [comment]
> Thanks! We have added your pseudo in Ethos Suite About, let me know if you want your firstname / lastname like for some others
> 
> ![image](https://private-user-images.githubusercontent.com/50834778/310817664-b5f10827-a4a3-4997-92fd-d426ed3fd1ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDU4MDMsIm5iZiI6MTcwOTgwNTUwMywicGF0aCI6Ii81MDgzNDc3OC8zMTA4MTc2NjQtYjVmMTA4MjctYTRhMy00OTk3LTkyZmQtZDQyNmVkM2ZkMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA5NTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NmQ4M2Y3MGY5MWZkZmZjYWIzM2YxMmE1ZTY5ZjhmNmMyOTM5Yjg0YjM1ZjFkYmE3MDdhMTAyNzQ0MmU1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3MYH01KcJ15m96nbkPX0JEzVL91XfST51Xd2hx6kzL8)

Hi Bertrand, if it is possible Marco (mgsanna) , something like Thierry...

**Comment by bsongis-frsky** [comment]
Done
