### ISSUE TITLE
Create a new System Event "Flight start" (fired on Model load / Flight reset)

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3585]
V1.5.1 The vars now have an autorepeat function
just like the trims.

Bt the range cannot be scaled automatically 
e.g. scaling a potentiometer from 100% to +100% to 0% to 50%, which is often necessary.

If you need this, you have to insert 2 actions in the VAR 
Multiplication 25% and addition 25%
This is a weighting of 25% and an offset of 25%

But now the autorepeat function takes effect and calculatts this again and again
and runs into the limits. 
So you can't use it to scale values, 

I think the autorepeat function here is wrong or you should be able to switch it off.

**Comment by strgaltdel** [comment]
Hi Helmut,

duplicate to  #3203 ?

**Comment by hrenz** [comment]
I found the solution and thats fine as it is,  if you know how it works
autorepeat depends of the Value you set als source
think its not in the manual

[Var mit und ohne Autorepeat 001.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14513938/Var.mit.und.ohne.Autorepeat.001.pdf)

**Comment by hrenz** [comment]
but what we need is a Preset value one time
for example preset = -60% as a startvalue
or as asystem event start

**Comment by hrenz** [comment]
Vars?
How can we preset a value at start/open/select of the Modell one time.
how can we init a one time impuls at log switches at start/open/select of a Modell for that

or with a system event one time at start/open/select a Modell

and we need a curve

Autorepeat on/off with slow/fast/custom

**Comment by WhiskeyGolf** [comment]
> Vars? How can we preset a value at start/open/select of the Modell one time. how can we init a one time impuls at log switches at start/open/select of a Modell for that
> 
> or with a system event one time at start/open/select a Modell
> 
> and we need a curve
> 
> Autorepeat on/off with slow/fast/custom

I agreed with that

**Comment by bsongis-frsky** [comment]
Agreed. I change the title of the issue. It's rather an enhancement (new System Event).

**Comment by bsongis-frsky** [comment]
Ready for next nightlies

**Comment by lthole** [comment]
I think this should be called ’Model start’ rather than ‘Flight start’. The term ‘Flight start’ implies flight.

**Comment by bsongis** [comment]
Not sure, as this event is fired when you select "Reset Flight"!

**Comment by lthole** [comment]
How about Flight Reset? To me Flight Start means something different.

**Comment by bsongis-frsky** [comment]
The name "Flight reset" is OK with me.

**Comment by bsongis-frsky** [comment]
Modification ready for the next nightlies

**Comment by lthole** [comment]
Great, thank you!
