### ISSUE TITLE
Spurious Throttle Warning with a Switch as Source in the Throttle Mix

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#3586]
Hello,

I have updated my Tandem X20S from ETHOS 1.4.17 to 1.5.1. Now I always get a throttle warning when I select a model (powered glider) that has a switch allocated as source in the throttle mix. This is independant of the actual switch position, and the warning cannot be removed by flipping any switch but must be accepted with OK.

For models with the throttle stick as source in the throttle mix no problem exists.

**Comment by bsongis-frsky** [comment]
Will be part of the next nightlies
