### ISSUE TITLE
Connecting to Suite 1.5.1

### ISSUE THREAD

**Issue by kvak1** [FrSkyRC/ETHOS-Feedback-Community#3587]
I can't connect to Suite 1.5.1 (on Windows) via USB from the radio (X20) with 1.5.1 firmware. By choosing "Ethos Suite" on connecting dialog in the radio Suite can't see the radio. Only with the radio switched to Bootloader Suite can see it. In Suite is not possible switch from "bootloader"  to "Ethos" - Suite (crash down) disappear instantly after this action. Before update from 1.4.15 Suite and 1.4.17 firmware everythig OK. Am I doing something wrong or overlook something? Thank you for help. Karel

**Comment by kvak1** [comment]
In addition Bootloader 1.4.15.

**Comment by pmullen503** [comment]
Check "Suite settings" (bottom of page) and make sure the file source is set to github not Frsky.

**Comment by kvak1** [comment]
Yes, it is set to GitHub, but my problem is connection between radio and application in PC... thanks

**Comment by kvak1** [comment]
I reinstaled Suite from scratch, firmare in the radio and still the same - Suite says "no radio connected". Then I swich off the radio, pull out usb, swich on the radio in bootloader mode, connect usb and Suite shows the radio... Coud you specify informations you need? Thank you very much. Karel

**Comment by Nicholas-Luoyi** [comment]
I'm still investigating it. I guess it's something related to the driver. I will ask if needed.

**Comment by Nicholas-Luoyi** [comment]
I'm still investigating it. I guess it's something related to the driver. I will ask if needed.

**Comment by Nicholas-Luoyi** [comment]
Can you open the debug mode and connect the radio in firmware and post the generated debug log here? In the mean while, can you see the disks of the radio in file explorer when you connect in firmware?
