### ISSUE TITLE
Ethos 1.5.0 French manual Rev4

### ISSUE THREAD

**Issue by philandroid36** [FrSkyRC/ETHOS-Feedback-Community#3588]
here is the French translation of the ethos 1.5.0 rev4.
[[FR] X20 and Ethos User Manual_1.5.0_rev4.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14514097/FR.X20.and.Ethos.User.Manual_1.5.0_rev4.pdf)

**Comment by bsongis-frsky** [comment]
Thanks!
May I add your name to the acknowledgments inside Ethos Suite?

**Comment by philandroid36** [comment]
Yes. Of course. Thanks.Le 7 mars 2024 09:59, "Bertrand Songis @ FrSky" ***@***.***> a écrit :
Thanks!
May I add your name to the acknowledgments inside Ethos Suite?
