### ISSUE TITLE
Speaker buzzing 

### ISSUE THREAD

**Issue by JJames1513** [FrSkyRC/ETHOS-Feedback-Community#3591]
Updated X20s to 1.5.1 
after update the speaker on my X20s is making a strange electrical interference buzzing sound just before and just after any sounds are made especialy system "beeps" but happens with all sounds including custom audio files.

**Comment by bsongis-frsky** [comment]
Are you sure it's linked to 1.5 ? 
If the RF is OFF is it better?

**Comment by JJames1513** [comment]
Well.
It wasn't doing it before I updated it.

**Comment by JJames1513** [comment]
> Are you sure it's linked to 1.5 ? If the RF is OFF is it better?

RF ON - RF OFF dosnt make a difference. 

If TX powered off for a few minutes and then back on it goes away for a little while and then comes back.  

Reflashed everything and seems to have gotten better but it's still there a little bit.

**Comment by bsongis-frsky** [comment]
You reflashed everythijng and it went better? That's difficult for me to understand, what has changed then? Since it was already up to date!

**Comment by JJames1513** [comment]
I have no idea how to explain it. I'm just reporting what happened.

Updated my Twin Xlite-S as well and didn't have any issues with it at all.

Could just be a glitch with my X20s. But it started after Update.

**Comment by raydars** [comment]
I also had  similar with X20 Pro and using vario on 1.5.1.    There was  a crackling/interference heard just before  the vario beeped.    next time out I will see if Ican hear and record/log it.

**Comment by SQB-Pilot** [comment]
I also had similar with X20 Pro AW on 1.5.1. and 1.5.2. There is a crackling/distortion heard with all sounds when volume above 25%. Also strange click sound when radio is switched on. Almost seems like a DC offset on speaker output.
