### ISSUE TITLE
main.lua issue

### ISSUE THREAD

**Issue by benwap** [FrSkyRC/ETHOS-Feedback-Community#3592]
Under Ethos 1.5.1. No settings are displayed in the configuration page of crossfire after opening RF system/configure. The setup tag doesn't open other parameter than "Bind" and "Set failsafe". The binding tag doesn't give anything.

**Comment by bsongis-frsky** [comment]
Have you updated your script? You have to use the new one from 1.5.1

**Comment by bsongis-frsky** [comment]
Any news? I have had confirmation from another user that it works correctly
