### ISSUE TITLE
V1.5.1 Suite X20s generates an error message when starting and querying the SD card.

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3593]
V1.5.1 Suite X20s generates an error message when starting and querying the SD card.

But the SD card has no errors, the system  X20 to PC needs simply 1s longer

I think the Suite simply does not wait long enough for the SD card to respond.

**Comment by Nicholas-Luoyi** [comment]
Would you please provide the crash log or the debug log? You can find the open directory button in the Settings page.

**Comment by hrenz** [comment]
ok can be closed
