### ISSUE TITLE
Bug in "Play audio"!?

### ISSUE THREAD

**Issue by PeterGraz** [FrSkyRC/ETHOS-Feedback-Community#3597]
Hi Folks,

i want to play the simple audio sequence illustrated in screenshot 2 (6 items, total playing time about 22 s) triggered by a logical switch, and want to repeat it every 30 s.

After the logical switch is turned on the sequence is played the first time (takes about 22 s), then there is a "delay" of 30 s and the sequence is played a second time. After that the sequence is played in a loop without a pause in between two consecutive sequence.

So, is this a bug or am I miss interpreting the option "Repeat"?

Keep up the good work, because I love Ethos!
Regards, Peter

![screenshot1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/126079166/d4eb723c-a3af-4ab3-9add-463ee0372342)
![screenshot2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/126079166/407d6066-23f1-455c-95f3-43f4fdaf4191)

**Comment by bsongis-frsky** [comment]
You are right, it seems that introducing a Wait Duration inside the Sequence breaks the Repeat behaviour

**Comment by bsongis-frsky** [comment]
To be tested seriously in the next nightlies!
