### ISSUE TITLE
Free Mixe Slow Up/ Down

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#360]
Hello,

Still playing with mixer. Just want to extend flaps in 5sec  and apply the mix to the elevator also in 5sec. 

The Slow UP / Down value is not taking account in a free Mix mixer.

Even if you set 5 Sec , it seems to be always around 2 sec

![image](https://user-images.githubusercontent.com/27886942/120059838-4a397f00-c054-11eb-817b-e4ddca88810b.png)

![image](https://user-images.githubusercontent.com/27886942/120059850-60dfd600-c054-11eb-8378-2f5499ad2ae6.png)

![image](https://user-images.githubusercontent.com/27886942/120059873-7c4ae100-c054-11eb-89cd-f85d2c8175ba.png)

![image](https://user-images.githubusercontent.com/27886942/120059881-879e0c80-c054-11eb-9ffe-861173a8ea56.png)

**Comment by Nicholas-Luoyi** [comment]
5s means that it needs 5s to go from 0% to (-)100%. If you set weight 30%. Then the time would be 5s * 30% equal to 1.5s :)

**Comment by aviat40** [comment]
Hello Nicholas,
Ok but it would be better to set from the weight.
If not, could you explain me to have the same delay extending the flaps and the mixer effect to the ELE ;-)

**Comment by Nicholas-Luoyi** [comment]
Good question. For now we cannot sync them in one shot. But maybe you could set the slow time to 5s / 30% approximately equal to 16.7s...

**Comment by aviat40** [comment]
In fact, the opposite, Flaps in 5s, and 16 s in Elevator Mixer

**Comment by mawzthefinn** [comment]
For this use, you can use the Flaps->Elevator mix with a flap channel as your source and it will follow the flaps slow settings correctly.

This works now that the Flaps mixer can have Slow set directly without requiring an Output setting.

There were issues with this in early versions of ETHOS but it has been addressed since.

**Comment by mawzthefinn** [comment]
Closing as completed.
