### ISSUE TITLE
Ethos Suite. Rename i18n label to avoid language confusion?

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#3600]
There is some confusion to get your local language on the menus on the radio.
As I initially thought, I don't need the i18n files, only the "Audi Language" files installed.
However... To select your local language you need the i18n.

Would it be more intuitive to relabel "i18n" to "Menu Languages" or "System Languages"?
It corresponds better with "Audio Languages" on the right  ;-)

Br. Morten Masch, Norway.

**Comment by hrenz** [comment]
i18n  FileTyp its ok and correct

i18next is an internationalization-framework written in and for JavaScript

**Comment by mmasch** [comment]
> i18n FileTyp its ok and correct
> i18next is an internationalization-framework written in and for JavaScript

But is it logical for the common end-user?

Br. Morten.

**Comment by Nicholas-Luoyi** [comment]
Your advice could be acceptable
