### ISSUE TITLE
Lua switch queries return a different result with 1.5 than with 1.4x

### ISSUE THREAD

**Issue by uj-berlin** [FrSkyRC/ETHOS-Feedback-Community#3601]
Unfortunately, Lua now has a different behavior when querying switches and logical switches:
Previously, switches were written to the variable with a result of -1024 or 1024, channel values also from -1024 - +1024.
With 1.51, logical switches now result in -100.0 or +100.0, but channel values still result in -1024 to 1024.
I'm not sure if this was the plan, at least I didn't read anything in the changes to 1.5. The distinction between switches and channel values is not easy for me to understand. 

Regards 
Uwe

**Comment by bsongis-frsky** [comment]
1.5.0 introduces source:minimum() and source.maximum()
1.5.2 fixes it as it was wrong for switches

**Comment by uj-berlin** [comment]
Hello,
with the 1.5.2 simulator i still have the wrong values....

Best Regards
Uwe
