### ISSUE TITLE
sticking throttle

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3602]
when i use the throttle position to "write Logs" it sticks at the the set position for .5 seconds.

**Comment by williajgr** [comment]
every other control sticks also

**Comment by bsongis-frsky** [comment]
I don't understand what you want to do, what is your Active condition for the WriteLogs function?

**Comment by williajgr** [comment]
Throttle greater than -95Sent from my iPhoneOn Mar 8, 2024, at 9:02 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
I don't understand what you want to do, what is your Active condition for the WriteLogs function?

**Comment by bsongis-frsky** [comment]
So you use a Logic Switch? Without maximum duration?

**Comment by williajgr** [comment]
Yes.  A<XSource Throttle Value -95%Active condition always onNo duration Sent from my iPhoneOn Mar 8, 2024, at 9:16 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
So you use a Logic Switch? Without maximum duration?

**Comment by bsongis-frsky** [comment]
If you change to -50% or even 0% does it work correctly? To remove the stick calibration from the equation ...

**Comment by williajgr** [comment]
no just moves the stick point to what ever i set it to
________________________________

**Comment by kramgrand** [comment]
I used a motor arm switch to start "Write logs" for a short while.  
I noticed there was a delay to the announcement. "Motor Armed" when the switch was moved.  I did not associated it for a while that the delay in the announcement was caused by starting the log.
