### ISSUE TITLE
Yaapu now goes crazy

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3603]
when one has yaapu as one of the telemetry screens. It continuously says yaapu telemetry ready over and over and over.

**Comment by williajgr** [comment]
1.5.0 x20s and x20 pro

**Comment by bsongis-frsky** [comment]
Perhaps it needs some adaptations to run on 1.5.0

**Comment by OldGazer** [comment]
I have the same problem with my X20.

**Comment by yak-54** [comment]
need to update the script to this 
[yaapu_telemetry_ethos_1.5.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14544355/yaapu_telemetry_ethos_1.5.zip)

**Comment by yak-54** [comment]
Did this fix your issues ?

**Comment by williajgr** [comment]
Yes the Yao update did the job.ThanksSent from my iPhoneOn Mar 12, 2024, at 5:50 PM, Colin ***@***.***> wrote:﻿
Did this fix your issues ?

**Comment by JahNix** [comment]
I had this problem and used the new 1.5 Yaapu which stopped the repeating "TelemetryReady"message but the telemetry is no longer being displayed, and when it does, it lags. Almost like it gets a pulse and then stops. Pixhawk 6C. When I randomly get a message, it comes through chopped up. It did work flawlessly (I think I was on 1.4.6 or thereabouts). Any suggestions?

**Comment by JahNix** [comment]
> I had this problem and used the new 1.5 Yaapu which stopped the repeating "TelemetryReady"message but the telemetry is no longer being displayed, and when it does, it lags. Almost like it gets a pulse and then stops. Pixhawk 6C. When I randomly get a message, it comes through chopped up. It did work flawlessly (I think I was on 1.4.6 or thereabouts). Any suggestions?

Sorry for this... I updated everything but the RX. Facepalm moment indeed!
