### ISSUE TITLE
Virus detected in X20S-Simulator.exe  v1.5.1

### ISSUE THREAD

**Issue by vasyly71** [FrSkyRC/ETHOS-Feedback-Community#3604]
Downloading 1.5.1 x20s simuator from https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.5.1/X20S-Simulator.exe and it is marked as contaminated

Downloaded for a test XES-Simulator.exe https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.5.1/XES-Simulator.exe - it looks good

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/70b68f6e-d8fa-4d00-916b-28bee2fca790)

Windows specs:

```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎10/‎2/‎2023
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0
```

Threat information:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/2151b0cc-30b9-4d06-afb4-eac73d1969b7)

**Comment by bsongis-frsky** [comment]
It seems completely random, due to some heuristic ...
It changes from one release to the next one, and not always the same simulator.
So the problem will be fixed on next release ... perhaps :)
You may check with VirusTotal to be sure there is no problem
