### ISSUE TITLE
Rudders mix appears to be still missing differential 1.5.1

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3605]
1.5.1

The Rudders mix appear to be still missing differential, which was added in 'add "rudder differential" for v-tail or dedicated v-tail mixer #119".

Promised screenshot from #119:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/f0fbbdb0-13ed-42a7-b33e-8f0ac7fc98ef)

Screenshot from 1.5.1:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/ae3025f8-7ccf-493d-a2d5-9dd6146ceed7)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/99ba198e-0619-4d39-8c71-f304131a1449)

**Comment by bsongis-frsky** [comment]
It's available only in V-Tail setups.

**Comment by lthole** [comment]
Ok I will amend the manual accordingly.
