### ISSUE TITLE
Ethos suite improvement suggestion

### ISSUE THREAD

**Issue by Fernandolewandowski** [FrSkyRC/ETHOS-Feedback-Community#3606]
Hello, I want to thank you for the excellent improvement of ethos suite 1.5.1, which is being able to update the internal module now to make it even better. I would like to be able to put the files to update the receivers via ethos too, is it possible?

**Comment by bsongis-frsky** [comment]
Yes it is

**Comment by bsongis-frsky** [comment]
Have you succeeded? Then we can close the issue
