### ISSUE TITLE
Ethos 1.5.2 missing term to translate.....  

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3607]
I cannot find the term for translate it... maybe it's coded inside firmware ? just like others terms for flashing firmware (that's in english) and I think it's inside the bootloader file....

<img width="811" alt="Screenshot 2024-03-09 143057" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/52e68641-121f-4717-8f96-40ca8a12b524">
<img width="797" alt="Screenshot 2024-03-09 143153" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/64991d1d-cbea-4ab2-ac0d-d8d223399d08">
obviously lot of user are complaining for this.... ;-)) 
the only untranslated term that is so similar in english or Italian
(operation / operazione). How can I solve for the next updates?
@bsongis

**Comment by bsongis-frsky** [comment]
This translation was missing. I have written
[en] Operation
[fr] Opération
[it] Operazione

**Comment by Luznatural** [comment]
Please, add also
[ES] Operación

**Comment by bsongis** [comment]
@Luznatural done :)
