### ISSUE TITLE
Free Mix action "Slow" on X20

### ISSUE THREAD

**Issue by kvak1** [FrSkyRC/ETHOS-Feedback-Community#3608]
In free mixes on X20 the action "Slow" doesn't work. Just randomly after change sequence of actions "Slow" work one time and then nothing like without this setting. Am I doing something wrong or overlook something? Thank you for help. Karel

**Comment by kvak1** [comment]
Addition: firmware 1.5.1..

**Comment by bsongis-frsky** [comment]
Would you show your mix? I think you are expecting a Slow, not on the right condition (it's the Action switch which is important)

**Comment by kvak1** [comment]
Here is my atempt. Thank you very much. Karel
![1_X20](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/66553590/0e468967-d1bd-4f3b-9496-a1a3759e5999)
![2_X20](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/66553590/9e6d44b6-691b-424d-891a-9965bda1b0ca)

**Comment by kvak1** [comment]
...
![3_X20 – kopie](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/66553590/9c869ea3-eed1-4378-bb07-75c6a582de9d)
 and third file. Klapky = Flaps

**Comment by strgaltdel** [comment]
look on your combination of source and active condition
this mixer is valid only in center position and as a result  outputs a static value (as long as curve doesnt change its shape).
more or less you apply slow on a static value

**Comment by kvak1** [comment]
Thank you, I will investigate. Just one question. What does mean the exlamation mark before Positive (!Positive) that appear after actualization of firmware and how is possible to make it (if it is important)? Karel

**Comment by strgaltdel** [comment]
you mean the difference between !SB- and SB- for example?

the "!" is the symbol for bool operator "not" (Ethos slang "inverse")
so !SB-  would mean "all positions but not center"

you can activate this by "press long enter" in fields marked with the tiny hamburger icon
(three small, horizontal lines)
then you will enter an options menu, 
checkmark "inverse"

**Comment by kvak1** [comment]
Ok thank you for explanation - it is it. Btw. I repaired "Slow". You were right. My Slow was based on a active condition. Thank you very much. Karel
