### ISSUE TITLE
r9 stab

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#361]
using flex firmware devic config sxr setup does not get any information from r9 stab on flex firmware and sxr calibration no response
bradnew reciever flashed with newest firware and x20 on 1.0.7

**Comment by WismyYao** [comment]
What is the version number of R9 stab ?

**Comment by stubugs** [comment]
it's the
FrSky R9 STAB OTA 868Mhz Receiver / Flight Controller

**Comment by WismyYao** [comment]
how about 1.0.10 c2 ?

**Comment by bsongis-frsky** [comment]
Feel free to reopen if needed

**Comment by Hobby4life** [comment]
If you have problems with calibrating a R9 STAB.
I gues you are stuck at the calibration point on its side?

The picture in ETHOS when you must calibrate when on its side. with the FRSKY logo facing normal.
It is wrong for the R9 STAB, it is reversed compared to a SRx receiver.

Best is to change the whole name of SRx config and calibration to **STAB**
And the picture of the side calibrations should not mention the logo, but the antenna wires with sbus ports.
This is a more universal aproach for both SRx and R9 Stab receivers.
