### ISSUE TITLE
 GMT time

### ISSUE THREAD

**Issue by OldGazer** [FrSkyRC/ETHOS-Feedback-Community#3612]

**Comment by Toffs** [comment]
Haha, what more information do you want mawz?  The OldGazer has clearly explained his issue and even recommend a possible fix…. 
can’t you read invisible sand script?   ;)

More seriously though, as a resident of that time zone I too am curious as to what was meant to follow in this post. Maybe something to do with British Summer Time (time change)?
The mystery continues

**Comment by bsongis-frsky** [comment]
What is happening here? 
I see no description, no link, just reference to an unknown time zone / planet / ISS?

**Comment by bsongis-frsky** [comment]
I close it, I don't understand what is said in this issue!
