### ISSUE TITLE
ft/min Range in VSpeed Telemetry Sensor is still wrong after #3540

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3613]
I believe that #3540 has only fixed part of the problem reported. 

Looking at VSpeed Telemetry, when the range is specified
in ft/s the range is 328ft/s which is approx 223mph
in ft/min the range is 5ft/min which is 0.05mph

It looks like something is being divided instead of multiplied (or the other way around) by 60 for the ft/min conversion.

1.5.2
Thanks

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ea951d4d-5fc1-4042-9602-e4c92bb904f3)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/149aaadc-f2dd-41d4-b10e-e9e5c26d6416)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d37cf106-6667-4625-b8d0-ffd7ebf2d365)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a16f073d-2940-48cc-9edb-0b0588d9f462)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/426fc33c-02f2-4614-bc3b-b7644529aa4e)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2de10db6-1e76-4a5a-8f2b-6188590009de)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4e26be6c-8430-489c-a70b-1a6929977ada)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/88633624-5cb4-4edb-815f-8f7ddaaebea3)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5326d719-e0fb-4c41-9459-92b3697aa2eb)

**Comment by bsongis-frsky** [comment]
Screenshots attached to this issue with all units
