### ISSUE TITLE
flysky telemetry

### ISSUE THREAD

**Issue by rickisound** [FrSkyRC/ETHOS-Feedback-Community#3618]
the flysky CAT-01 altimeter sensor is not detected by ethos during the search.
the CVT01 sensor works well, both connected via ibus to an fs-iA10B receiver

**Comment by bsongis-frsky** [comment]
Do you know which ID it is? 0x12?

**Comment by bsongis-frsky** [comment]
ID 0x12 added to 1.5.3

**Comment by rickisound** [comment]
thanks, I will test it as soon as version 1.5.3 is released.
