### ISSUE TITLE
Trim value announcements. 1.5.1 (1.5.2 Pre-release)

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3619]
Hello
Curious: I would like to have the trim values announced. The display shows 13%, but I was told several times "one hundred and twenty-eight zero per cent! 
But later only "one hundred and twenty-eight" is announced. So the real value times 10.
Greetings Wolfgang

**Comment by hrenz** [comment]
Problem 
its announced  not   not in% its  in us

**Comment by Wolepo** [comment]
But that doesn't help anyone. The displayed value must also be announced.

**Comment by strgaltdel** [comment]
there are several instances where "something" has changed after a 1.5 update by factor 10 (exactly 10.24)

until now most issues were solved, but may be there are still  some  unknown "glitches"
( i guess i found most  lua sources reporting percent values, but some still +/-1024, so not "normalized")

lets wait and see what Bertrand can do

**Comment by bsongis-frsky** [comment]
Fixed for 1.5.3
