### ISSUE TITLE
Tool to create voice files

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#362]
Is there a tool to create voice files (the same as the original voice) . In my case german.

**Comment by hrenz** [comment]
Take Balabolka or TTSAutomate

**Comment by Hobby4life** [comment]
I have made a TTS sound pack, its EN only but you can use it to make a german one: https://github.com/Hobby4life/ETHOS-OpenTX-Soundpacks-EN-NL

**Comment by loetefix** [comment]
Hi,
Thanks, but i want to know whats the voice from the pack of the sd content.

**Comment by Sigee3** [comment]
Download OpenTXspeaker

**Comment by Hobby4life** [comment]
> Hi,
> Thanks, but i want to know whats the voice from the pack of the sd content.

These are all the Ethos default System sounds.
You can select a german speaker, and fill in the german spoken text.
There are 2 Ethos Packs,, 1 with the default ethos sounds, and 1 with default sounds + my own sounds.

If you check it out yourself you will see :-)

**Comment by bsongis-frsky** [comment]
https://cloud.google.com/text-to-speech
