### ISSUE TITLE
French langage has disapear in 1.5.1

### ISSUE THREAD

**Issue by sertyutiop** [FrSkyRC/ETHOS-Feedback-Community#3620]
Hello
I just make the update to 1.5.1 and bootloder via ethos suite and when i restart the radio i see that langage has change to english.
And there is no optionnal langage in the radio... I have updated audio and bitmaps.
Is it coming back soon or should i do something else?

Thxs.

**Comment by J-charles-C** [comment]
Salut

https://frskytaranis.forumactif.org/t14117p25-ethos-1-5-version-stable#146554

A+

**Comment by sertyutiop** [comment]
Comment j'ai pu passer à côté...!???
En tout cas merci!

**Comment by sertyutiop** [comment]
Every thing OK just dont see the selection to do. In previous version the langage was already selected...
