### ISSUE TITLE
Play Text is not using a queue for playing audio.

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3621]
This could be related to issue #3589 but is slightly different.  I have found that Play Text does not seem to be using a queue. If I have Play Text messages programmed for multiple switches, and move 2 switches at the same time, only one will play. If I perform the same test using Play Audio, both messages always play from the queue. Also, if a telemetry alarm or system message plays while a play text is playing, both play over each other. It would seem to me that Play Text needs to use the same queue as other audio sources. A critical system alarm could be missed if a Play Text message plays at the same time.

**Comment by bsongis-frsky** [comment]
Will be fixed once #3589 is implemented
