### ISSUE TITLE
Checkliste Text Not displayed in x12s

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3623]
Unfortunately, the model-specific text for the checklist is not displayed on the X12s.  It doesn't matter whether it is an md or txt text.  Thank you for your excellent work👊
Model p51.bin
Text p51.md

Transceiver X12S
ETHOS 1.5.1

**Comment by bsongis-frsky** [comment]
MD is not supported on X12S, you will need to have the same filename, with the ".txt" extension.
So above, instead of "Text p51.md" you should have "Model p51.txt"
