### ISSUE TITLE
'Play value' not supported by Special Functions.

### ISSUE THREAD

**Issue by TomWEW** [FrSkyRC/ETHOS-Feedback-Community#3626]
'Play value' is not supported by Special Functions as stated by omission from the list of Supported Functions on pages 242/3 of Ethos v1.5.0 rev4 User Manual and found to be the case when editing the 'Action' parameter in 'Special Functions'.
This is a serious omission for users dependent upon playing the electric flight motor power supply LiPo voltage to safely determine when to land the aircraft.

**Comment by Jedsters** [comment]
Surely p243 mentions 'Play Audio' and then p245-p247 show how to setup a sequence which includes both a value and a file. 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/318aaaaf-9500-496d-a684-25aa29f3e6b5)

Play Value now comes under Play Audio. I am currently doing exactly as you request with 1.5.2, when a voltage gets too low it will play 'Low Battery' from a file and then say the LiPo voltage. I also have a setup for when a cell drops too low and it plays 'Low Cell' and the lowest LiPo cell voltage.

**Comment by bsongis-frsky** [comment]
Is it a documentation issue? Of course you can play a value!

**Comment by TomWEW** [comment]
Many thanks, the small change in terminology threw me off.
