### ISSUE TITLE
Ethos suite 1.5.2 Missing "update" buttons on radio screen

### ISSUE THREAD

**Issue by vasyly71** [FrSkyRC/ETHOS-Feedback-Community#3627]
There used to be buttons to update specific area/all outdated etc

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/4390838e-4b34-48bd-a6e1-766c3196be91)

**Comment by vasyly71** [comment]
Same after i switch to ethos from bootloader

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/6af98c69-5e07-43f2-b7eb-b5f3513a2fca)

Interesting but during the switch the drop-down-update-button" appears, but then it is gone.

Also keep in mind i'm running it in virtual box and need to  re-enable USB device after device (x20s) reset.

**Comment by spoke2570** [comment]
Suite 1.5.2 for Mac works well.

**Comment by Jedsters** [comment]
Like this on Windows with Suite 1.5.2
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/40350bd9-f0e1-4488-bcde-7e38516014b0)

**Comment by RealTadango** [comment]
Works fine on windows? Can you try another windows scaling?

**Comment by vasyly71** [comment]
Changing display settings (scale, resolution) did not help.
However behavior is sporadic and if i switch (using ethos suite) between bootloader and ethos several times i actually may get "update-drop-down-button". "Unrepresentative, inconclusive statistics" i have now is ~10% chance when i start ethos suite and have my x20s connected i will get "update-drop-down-button" and 90% not.

**_Important note:_** i'm running ethos in windows VM, under virtual box, hosted by ubuntu.
**_However_** Environment did not change between ethos suite 1.4.15 and 1.5.X. I did not have this problem prior to 1.5.X. I just reinstalled 1.4.15 and it works every time (100%) - i get the update button. 

Suite 1.5.2 does not work regardless whether i upgraded form suite 1.5.1 or uninstall old and freshly install new. 
And i just did another experiment none of 1.5.x suites deliver stable result.

**Comment by Nicholas-Luoyi** [comment]
Interesting. There is a check in Suite:

- If adio connection not detected => hide the button
- If firmware / audio / bitmaps disk not detected => hide the button
- If the connection lost is required by Suite => keep showing the button.

Your VM seems invert the result of the check function.

**Comment by vasyly71** [comment]
> Interesting. There is a check in Suite:
> 
> * If adio connection not detected => hide the button
> * If firmware / audio / bitmaps disk not detected => hide the button
> * If the connection lost is required by Suite => keep showing the button.
> 
> Your VM seems invert the result of the check function.

@Nicholas-Luoyi :
First question - are these checks something new introduced in suite 1.5.x - suite 1.4.x seems working without problem with 1.5.X firmware and same windows environment.

1. Could you please clarify audio connection it is trying to detect?

2. I do get this mounted in windows VM
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/7fb608b1-1dbb-4e80-a0ae-165c5080e886)

3. _If the connection lost is required by Suite_ - is this why i see button when switch from boot loader to ethos (or reverse direction) and then it disappears

Here is how device is seen by linux
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/25940239/4f0279c1-2c36-413b-b95f-1c01556e767a)

**Comment by Nicholas-Luoyi** [comment]
The is there since Release 1.5.0.

Yes to 2. and 3. That's why I think it's interesting.

I will optimize this check.

**Comment by Nicholas-Luoyi** [comment]
The is there since Release 1.5.0.

Yes to 2. and 3. That's why I think it's interesting.

I will optimize this check.

**Comment by vasyly71** [comment]
@Nicholas-Luoyi  let me know if you need more information or need me to test some sort of nightly build of suite in my vm.

Thank You

**Comment by kramgrand** [comment]
Just a thought,   You could try a new / different USB cable.  I have had a cable that seemed to go intermittent that caused a similar issue a while ago.

**Comment by vasyly71** [comment]
> Just a thought, You could try a new / different USB cable. I have had a cable that seemed to go intermittent that caused a similar issue a while ago.

Cable seems fine other cables exhibit similar behavior. Also keep in mind that mass storage is always working and i can see and move files.

In addition i have x10s-express that i just upgraded and "upgrade" button is always there  (there is no RF module on the side bar though ugraded to the latest using usual procedure)
