### ISSUE TITLE
Version 1.5.2 has many places where Chinese characters are missing or incorrect.

### ISSUE THREAD

**Issue by chenbevis** [FrSkyRC/ETHOS-Feedback-Community#3628]
![20240311_233915](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/88714382/336a2e31-a795-4c15-9af8-431c4b52e572)
![20240311_233624](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/88714382/576b3e50-5430-4e0a-b8a9-267480d7f0a1)
![20240311_232724](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/88714382/ea7ba1bf-02a4-436a-83f5-9ab5d249f8ab)
![20240311_233523](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/88714382/6f912c33-327b-4cd0-a556-d106c040e0ff)
![20240311_232757](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/88714382/9995dfde-9bcf-438c-a3d3-ef36fb0bead0)

**Comment by bsongis-frsky** [comment]
Fix ready for 1.5.3
