### ISSUE TITLE
Request: Automatically upgrade all models after release upgrade

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3629]
Following on from a discussion on RCGroups.

It seems that with each new release we need to select all models in order to upgrade them to the latest .bin format. 

Some of us have more models than we care to admit to and don't regularly fly all of them for various reasons. It would therefore not be difficult to get into a situation where you take a model to a site only to find you can't fly it as you last flew the model with e.g. 1.3.x and are now on 1.5.x. This is particularly true of e.g. models which require a specific slope and conditions to fly well so don't get out very often and which you may travel quite a distance in order to fly. (I have a 4M Fox for which the only good slope for flying and landing is an Easterly when the wind is blowing 20mph+ and which is 90mins drive away.)

To avoid wasted journeys and major frustration would it be possible for Ethos to automatically upgrade all .bin to the latest format as part of the release upgrade process please? 

I'd imagine that it would be useful to do something with release folders, e.g. have an extra folder under models corresponding to each new release and then upgrade into the new release folder
e.g. models/V140/modelX.bin etc
which all get upgraded into 
models/V150/modelX.bin etc.
and the current version of Ethos could just use the corresponding models/vrm/ subfolder so if a downgrade was ever needed all the models are already there. 

Thanks!

**Comment by bsongis-frsky** [comment]
Who said that?
Of course models are automatically converted.
I have only get rid of very old conversions, prior to 1.0.10!

**Comment by guycnicholas** [comment]
@bsongis-frsky https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-X20-Pro-Tandem-24-Channels-with-ETHOS/page1835#post51986839

**Comment by bsongis-frsky** [comment]
The models are automatically converted when they are loaded.
Only the very old conversions have been removed because they were too old.

**Comment by Jedsters** [comment]
That's good to hear, It appears to be a popular misconception. I wonder if this is because this was required with opentx so people assume that is the case here?
Could be worthy of a paragraph in the manual so at least people can check that to see what is required (i.e. nothing) and maybe a line in the opentx / ethos comparison doc too.

Edit: I realise the manual says that the upgrade can take place at a later date, but perhaps this could be improved to make it clearer that this is regardless of model version and new ethos version - unless perhaps explicitly stated in the release info.
Thanks

**Comment by bsongis** [comment]
The post from Mike is good. OpenTX does the same, I cannot see any other possibility, we cannot check all the models / backups / SD card etc. from the user to be sure there is nothing old to convert!

**Comment by Jedsters** [comment]
Thanks in my last post I was only suggesting a very minor doc update.
e.g. 
in the Rev4 manual on p61
'There is no need to select each model after an update because the conversion can take place at a later date when they are
selected.'
could become e.g.
'There is no need to select each model after an update because the conversion can take place at a later date, even with a later release of Ethos, when they are selected.'

I'm not aware that this very useful feature is documented elsewhere so some users seem to assume we may need to upgrade old models in stages, which you have helpfully explained is not the case.
Thanks

**Comment by spoke2570** [comment]
Could we get a button that updates all the models? I have one plane for instance that I've not flown for years. I open all my models after updates, so I know it is OK, but If I defaulted to letting this happen organically due to large inventory or a model at another venue some would slip through the cracks. I know this function would take a fair bit of time to run for folks that have a bunch of models, so it would be good to make the time investment a user choice.

**Comment by Jedsters** [comment]
@spoke2570 As I understand it, it's not necessary. I believe Bertrand is saying that if you have a model you last flew with 1.0.11 and selected it with e.g. 1.5.2, Ethos would just do all the conversions necessary when it is selected. So long as this is the case then there is no need for a process which updates all models. I was just thinking a few extra words in the manual to confirm this is what happens would help reassure people not to worry. 
I may be wrong, but IIRC opentx requires you to go through every intervening level, e.g. 1.1, 1.2, 1.3. etc. (although I'm not convinced that every level is actually necessary, more of a just in case) and since I suspect a lot of us are coming from opentx we still incorrectly assume that is the case.

**Comment by spoke2570** [comment]
I think I stopped updating my OTx box after the D4 protocol was killed. I only ever used a pretty basic model function on it and let my LUA scripts handle the rest. Anyway, that plane of mine will be unlikely to fly for another few years as I don't go to where I grew up often, It would be nice to have an optional update all models function.
