### ISSUE TITLE
Tandem X20S Telemetrie GPS Sensor Problem Speed km/h wrong

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#363]
I use the Tandem X20S with Firmware 2.1.8 beta / Ethos 1.7 /  Receiver Rx8pro 2.1.7
I suspect a problem with the GPS transmission value for the speed
the output kmh is wrong I suspect that the conversion is not correct and instead of kmh knots are used.
regards bluelex73

**Comment by Hobby4life** [comment]
I have experienced this today also. 

km/h gave me values of 10000x range

**Comment by bsongis-frsky** [comment]
I see meters per second in the source code, I have to check what it is in the S.PORT spec

**Comment by bluelex73** [comment]
Hallo Mr bsongis,

even with ethos 1.09 / 4 the GPS speed is not correct. meters per second and kilometers per hour are still interchanged in my opinion
