### ISSUE TITLE
X18S Simulator

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#3632]
Is there is a way to add some telemetry values to the simulator 1.5.2 or am I missing something?

v1.4.1 of the simulator had values for every sensor.

**Comment by bsongis-frsky** [comment]
You should have the same on 1.5.2 compared to 1.4.1
But perhaps you haven't started the RF?

**Comment by salibaj2** [comment]
You're the man bsongis, thank you!

I had the RF OFF. May I suggest to have RF ON as default?

One last question for now about the simulator. Is there a way to change a value in telemetry?

Thank you
