### ISSUE TITLE
EVT_SHUTDOWN doesn't work

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#3633]
Hello Bertrand,

unfortunately, the EVT_SHUTDOWN function as stated does not yet work in version 1.5.2 or cannot it be queried as follows?

```
local function event(widget, category, value, x, y)
print("Event: "..value.." cat: "..category)
if category == EVT_SHUTDOWN then
print("Switch off")
end
```
thank you
best regards Benno

**Comment by Storchy1** [comment]
Hello Benno00,
i have tried my script in 1.5.1 it works perfect, i have not yet updated to 1.5.2.
Perhaps you try it.

local function taskInit()
  print("Shutdown Task Init ...")
end

local function taskWakeup()
  print("ShutdownTask Wakeup ...")
end

local function taskEvent(event)
  print("Shutdown Task Event", event, EVT_SHUTDOWN)
  if (event == EVT_SHUTDOWN) then
    print("Shutdown in progress!")
    local txtfile = io.open("/scripts/AllModel/TxBat.txt","w")
    print("UpdateTxBat",txtfile)
    if txtfile ~= nil then
      print("txbat.lua open to file ok")
      local text
      text = string.format("%010d,%d,%010d Shutdown",math.floor(TxBatSec + os.clock()),math.floor(TxVoltage:value()*10),math.floor(TxGlobalSec + os.clock()) )
      print("txbat.lua write to file",text)
      io.write(txtfile,text)
      io.close(txtfile)
    else
      print("txbat.lua open to file failed")
    end
    
  end  
end  

local function init()
  system.registerTask({key="LuaTask", name="Shutdown Task", init=taskInit, wakeup=taskWakeup, event=taskEvent})
end

return {init=init}

**Comment by Storchy1** [comment]
Hello Benno00,
i have now updated to 1.5.2 and the script stil works
Have a look this is a script with **system.registerTask**(...)
Ciao
Jörg

**Comment by bsongis-frsky** [comment]
It should work

**Comment by bsongis-frsky** [comment]
@Benno00 please paste how you registered your task!

**Comment by Benno00** [comment]
Hello Bertrand,

sorry, I didn't use system.registerTask but rather system.registerSystemTool, my mistake.

can be closed

Many greetings, Benno

**Comment by Benno00** [comment]
it works

**Comment by Benno00** [comment]
Hello Bertrand,

 

the event "EVT_SHUTDOWN" works, but unfortunately it depends on the model, I was hoping that I could use it globally, e.g. for a LUA for transmitter use. Is there a way to use this globally without activating it under the model?

 

Thank you

Greetings Benno

 

 

 

Benno Jurisch
Siedlung 5, 27624 Geestland
Telefon: +49 (0) 4708 707
Mobil: +49 (0) 152 337 76 727
 ***@***.***> ***@***.***

 

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Dienstag, 12. März 2024 11:14
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Mention ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] EVT_SHUTDOWN doesn't work (Issue #3633)

 

@Benno00 <https://github.com/Benno00>  please paste how you registered your task!

**Comment by Storchy1** [comment]
That would be real progress!

Thanks a lot
Jörg
