### ISSUE TITLE
Lua page missing from Model screen

### ISSUE THREAD

**Issue by Ukhelinut** [FrSkyRC/ETHOS-Feedback-Community#3634]
Hi, Quite new to Fr sky, and purchased my X20 Pro during the change over to 1.5. I have noticed that the Lua tab on my model screen is not there.
What am I missing?
Thanks in advance.
![IMG_8543](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/80915050/82aaa977-e665-4c7f-ad2c-56b072aa5281)

**Comment by bsongis-frsky** [comment]
Perhaps you have no Lua script which registers a task or a source? Then the icon is not displayed because there is nothing to show!

**Comment by Ukhelinut** [comment]
Hi, thank you for the fast response.
I do have Lua for the external ix4 module in the scripts folder.
Also using SR18 rx’s
