### ISSUE TITLE
Throttle calibration incorrect. 

### ISSUE THREAD

**Issue by Fanman1961** [FrSkyRC/ETHOS-Feedback-Community#3635]
I've updated everything to currant as of 3/11/24.When I move throttle stick it doesn't show moving on outputs until I've reached about 25% of movement not even when Im calibrating it Than it moves in larger increments up to 50% than is normal increments after 50% throttle input.I tryed calibrating it ,even throttle trigger to 100%.I checked I beleive it SDC and it shows all movement so I ruled out bad pot.Any suggestions.This only happened after updating to 1.5.1 than again on 1. 5.2 just updated yesterday .Everything else is currant on ethos suit .I checked trims everything no curve nothing

**Comment by Fanman1961** [comment]
Sorry it's x20

**Comment by mawzthefinn** [comment]
What does it do on a completely fresh model?

**Comment by Fanman1961** [comment]
If I use my back up that I made before doing up date for x20 everything is ok

**Comment by mawzthefinn** [comment]
> If I use my back up that I made before doing up date for x20 everything is ok

But what does it do with a new model?

**Comment by Fanman1961** [comment]
I'll check on that when I get home

**Comment by Fanman1961** [comment]
Yes created new model and same issue

**Comment by bsongis-frsky** [comment]
I would check the System / Hardware screen, does your stick move correctly?

**Comment by Fanman1961** [comment]
No it doesn't that's where I did the calibrating also but when I go to ADC it does show the slightest movement.

**Comment by mawzthefinn** [comment]
If the ADC is barely moving, then it's possible a hardware issue. I'd open the back of the radio and check if the sensor board for the throttle axis has gotten loose.

**Comment by Fanman1961** [comment]
ADC is fine shows all movement of throttle stick

**Comment by Fanman1961** [comment]
It's when I look at outputs that it doesn't register movement until it's moved appropriately 30% even calibrating only shows movement after 30%

**Comment by mawzthefinn** [comment]
At this point I'd rename your radio.bin to radio.old and do a full new radio setup. The only thing I can think of is a corrupt radio.bin file which isn't saving the calibration. 

The calibration routing should set the endpoints for the throttle based on the ADC, so if the ADC is showing full movement, the calibration must be the issue. 

This will not affect your model files, but you will need to assign your voices again in System->general as well as configure any other radio level settings you might have customized.

**Comment by Fanman1961** [comment]
Did full new radio setup.Fixed problem that should of never happen. Liked frsky few yrs ago but now issues are popping up all over .I'm selling my x20 pro and keeping the x20 on older version when I didn't have any issues.
