### ISSUE TITLE
Ethos 1.5.2 Special functions: Play audio bug

### ISSUE THREAD

**Issue by PeterGraz** [FrSkyRC/ETHOS-Feedback-Community#3637]
Hi Folks,

it's me again.
When the special function "Play audio" becomes active and "Repeat" is set to "Once" it should play the audio sequence once. At least this is my understanding. This just works fine if the audio sequence consists of a single "Play File".
However, if it consists of a "Play File", a "Wait duration" and an other "Play File" (as in my case) the audio sequence is repeated over and over again.
Of course this problem can be fixed by an edge option, but I think it is an inconsistent behavior.
All the best to you, Peter

**Comment by DUFFORT** [comment]
FrSKY X14 with 1.5.2
with 1.5.2 impossible to create another plane!  Who knows why?
