### ISSUE TITLE
ETHOS Lua - Add Function to getDarkMode()

### ISSUE THREAD

**Issue by dWoolridge** [FrSkyRC/ETHOS-Feedback-Community#3638]
I just discovered that it would be nice to have my LUA Widget know if ETHOS is using "Dark Mode" or not.

Could a LUA system function be added to do this?  I don't think it would be necessary to set/unset the dark mode from LUA, just get the current setting.

For example:
system.getDarkMode() - [returns true/false]

I did some searching and didn't find this functionality listed in the Ethos Lua Reference Guide.

**Comment by bsongis-frsky** [comment]
`lcd.darkMode()`
