### ISSUE TITLE
Tandem X20S telemetrie Vario hang up, then no more telemetry announcements 

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#364]
With high sink or climb rates the vario sounds get very fast. 
Then you can hear a rustling. From this point  no further telemetry announcement can be heard. 
The transmitter must then be restarted so that the telemetry announcements can be heard again.
In addition, the vario with the interrupted sink tones is hardly usable

**Comment by jreis1** [comment]
It happened to me once but I has not able to recreate again. I had a switch to play altitude value that after a while stopped working. I was forced to restart the Tx to have again audible telemetry data.

**Comment by KenLong51** [comment]
Yes I had exactly the same this evening, After a lot of Vario actiivity all other announcments stopped untill I restarted the X20.

**Comment by combat-marcus** [comment]
Confirm! Got the same issue.

**Comment by bsongis-frsky** [comment]
It was very broken indeed.

**Comment by bluelex73** [comment]
Thanks for the fast feedback.

You are doing a great job. 

If there is a beta firmware version available to test 1.8 you are welcome to contact me.

 

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Mittwoch, 2. Juni 2021 15:27
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: bluelex73 ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Tandem X20S telemetrie Vario hang up, then no more telemetry announcements (#364)

 

It was very broken indeed.
