### ISSUE TITLE
Failsafe is missing on Multiprotocol

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3641]
The failsafe function is missing for many protocols in the external multiprotocoll module.  including FrSky protocols.  

-irangeXLite 
- Ethos 1.5.2 
- mm-arm-serial-application-v1.3.3.33

**Comment by digitalonkel** [comment]
Look into #3411 (closed)

Fixed by myself: just added in the main.lua in line 39 the feature failsafe
("FrskyX2", 64, {variants={"CH_16", "CH_8", "EU_16", "EU_8", "Cloned", "Cloned_8"}, features=FAILSAFE+TELEMETRY, options={RF_TUNE_OPTION}})

You can find my adjusted LUA as well in #3411

**Comment by bsongis-frsky** [comment]
Lua updated. You will find more options available in Spektrup and MLink lines, perhaps they can be applied to some other lines.
This script is just there as an example and it can be modified by the user.

**Comment by WhiskeyGolf** [comment]
Thank you very much for the quick help
