### ISSUE TITLE
Ethos 1.5.2, X20Pro: Checkbox does not work with the new multiprotocol functions.

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#3647]
Good evening

Ethos 1.5.2, X20Pro: Checkbox does not work with the new multiprotocol functions.

The latest LUA from today is used.

It just shows zero. If you change the number in one box, they change to the same number in the other box too.

Many thanks and kind regards

Enzo

![20240314_184730](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/bfb1bc39-9c92-4796-ba64-4120855373e4)

![20240314_184748](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/543723a0-6d8e-458c-a48c-e834358e6066)

![20240314_190154](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/37858773-bb53-4f7c-8592-b6ccdbcde358)

**Comment by bsongis-frsky** [comment]
You need the nightlies, this Lua is more recent than 1.5.2
