### ISSUE TITLE
Min/Avrg/Max values with integrated CSV Viewer

### ISSUE THREAD

**Issue by miff69** [FrSkyRC/ETHOS-Feedback-Community#3648]
I often use the internal CSV viewer of ETHOS 1.5.2. It would be a very helpful extension if the min/avrg/max values of a selected telemetry value were calculated and displayed. Under the line charts or in a table on a 2nd page?

**Comment by WhiskeyGolf** [comment]
That would really be a good addition to the CSV Viewer

**Comment by Jedsters** [comment]
Indeed, a similar suggestion.

**Comment by Richrfl** [comment]
This would be helpful, and probably the easiest way to go. Otherwise moving a vertical line across the graphic indicating the curve value I think it would be a little more difficult to implement
