### ISSUE TITLE
How to obtain GPS distance?

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#365]
I always use GPS distance in combination with Altitude, GPS Altitude or Vario Altitude.

How to obtain normal ground distance? and how to get line of sight distance with Altitude?

**Comment by Nicholas-Luoyi** [comment]
Calculated sensor is on the way

**Comment by Nicholas-Luoyi** [comment]
Please see #377 for details.
