### ISSUE TITLE
Trim option (Off/On) in Elevators mix is missing.

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#3650]
That option is there for Ailerons and Rudders. I would figure that it should be there for Elevators also, to be consistent. 
Thanks

**Comment by df7320** [comment]
XE
1.5.2

**Comment by mawzthefinn** [comment]
Confirmed on my X18 on 1.5.2

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a4bf36e5-5633-47fc-8c6d-9763f804b3a8)
