### ISSUE TITLE
impossible to play tracks

### ISSUE THREAD

**Issue by GiacomoGaleotti** [FrSkyRC/ETHOS-Feedback-Community#3651]
with last update is not longer possible to play tracks in special functions
if i enter the function and i try to modify values i can't see the list of waw files in the usual audio folder
the files were already in the radio and always worked
now i can't play or see anithing

in the list of special functions i see the value SF#, action, status, condition and value but when the function is trigged nothing happend.

if i modify one of the function to see what is happening and then i go back, the value to play disappear.
inside the function in the voice section i can only select from Voice1-default or Voice2- --- 
if, at the end of the page, i try to add a new line, no waw file is show! i can select nothing but the files are correctly located in the sd card inside audio folder and not inside other folders

**Comment by GiacomoGaleotti** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/44895913/95ac914f-8df6-4aeb-b044-c4073fc11e47)
The list of functions

**Comment by GiacomoGaleotti** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/44895913/a805165f-1ae9-4f86-b92b-899b16e40fc8)

**Comment by GiacomoGaleotti** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/44895913/e38a7b81-77e9-4008-8b50-3c28e65bd98d)
Files are in the radio and the name is still show

**Comment by GiacomoGaleotti** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/44895913/6ecc2c85-ae0e-474f-9831-d0b33395839f)
When selected, inside of the line I can not select anything, as you can see the only thing that appears is ---

**Comment by GiacomoGaleotti** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/44895913/02158cee-b1b9-4946-81db-c3b7d418794c)
And that's all my audio files in the directory. Play track function in this folder works fine

**Comment by mgsanna** [comment]
Non Voglio essere pesante ma esiste un manuale di ben 380 pagine che copre anche questo "problema" ..... che non è nient'altro che l'ostinazione di non volersi documentare.....
[addendum.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14621082/addendum.pdf)
[X20 & Ethos Manuale utente_1.5.0 rev5 (Italiano).pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14621084/X20.Ethos.Manuale.utente_1.5.0.rev5.Italiano.pdf)
![Immagine WhatsApp 2024-03-02 ore 17 45 39_3e7cf0da](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/d2a1bf40-ae96-4126-b9dc-304df10c289d)
![Immagine WhatsApp 2024-03-02 ore 17 45 55_d32578b6](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/68f865b2-f6fc-4733-a89e-565bdd09e7fe)

**Comment by mgsanna** [comment]
Devi spostare i tuoi file personali dentro la cartella audio/IT/ Tuoifile.wav....
ovviamente con l'introduzione delle lingue separate come audio e come file di traduzione, era ed è impossibile gestire automaticamente i file personali di ogni utente che talvolta il singolo utente butta dentro audio, talvolta li raccoglie in cartelle e sopratutto nomina ogni file come meglio crede.... quindi l'update non ha errori salvo la mancanza di informazione dell'utente singolo (tutto questo è stato ampiamente anticipato in quasi tutti i forum da alcuni mesi/settimane prima del lancio della 1.5.0.....
Quindi se risolvi (cosa che do per scontato) chiudi la issue....

**Comment by GiacomoGaleotti** [comment]
Molte grazie per la preziosa informazione.
Provvederò a spostare i file nella cartella corretta.
Giusto per condividere, ho utilizzato anche lo strumento implementato nel programma su pc per convertire e inserire i file nella memoria della radio dando per buono che li mettesse nella corretta posizione visto che non permette la selezione della destinazione.


Ho letto le 380 pagine di manuale appena presa la radio, dici che ad ogni release devo ricominciare da capo?

**Comment by mgsanna** [comment]
La release 1.5.0 cambia parecchie cose quindi, se credi sia divertente non documentarti …. Il solo fatto che tu abbia dato per scontato che non sia cambiato nulla ti ha portato alla segnalazione di un problema che non è un problema…..
Ps la suite per pc va aggiornata come anche la radio la suite attuale e’ alla 1.5.2, a breve uscirà la 1.5.3 che ha le ultime implementazioni anche di traduzione…. La destinazione è cambiabile come anche la lingua della suite (ma questo credo tu l’abbia già fatto) ….
