### ISSUE TITLE
Cannot download Ethos 1.5.2 into the X18 radio

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#3652]
I tried the upload/update from Ethos Suite 1.5.2 using the "Update outdated items" and also from my computer using the option at the bottom of the Suite. Even if I can get "Successful update" the Radio "Info" still shows me 1.5.1.

**Comment by strgaltdel** [comment]
Maybe you can provide more information,

is it really the basic x18 or the x18s
which bootloader
win / mac, which os rev.
was the suite started with admin or local user rights...
which suite rev.
Have you tried to do a "local" update by copying the firmware.bin file to the root directory?

All this can help to understand the problem and determine the cause.

**Comment by Richrfl** [comment]
Here I am answering your questions: It is the basic X18, although I know it has the gyro installed. However, the current FW loaded in the transmitter is for the basic X18. Bootloader 1.4.15 Windows 11. Suite 1.5.2. (I have been using Suite for over one year. I do not remember about the rights, but so far it was updating and working as expected). No, I have not tried to copy the FW into the root directory. I do not want to mess with the D drive. I never did that before. I hope this helps. If you want me to copy the FW into the root directory for the sake of the test, I will do that provided you tell me how to restore to 1.5.1 and I can do that by this time tomorrow.

**Comment by strgaltdel** [comment]
curious,
the environment is up to date and should be able to perform the update.

One option would be to start the suite in administrator mode
Right-click on the Suite icon and select "Run as administrator".

if the problem occurs again,
You could select the "manual" option

Download the x18 firmware file from the git repo and unzip 

Start the x18 in bootloader mode and connect it to the notebook,

Copy firmware.bin to the root directory of the Nand drive

Disconnect, the flash process will start immediately

After successful flashing, restart tx and try to reboot.    

update all other components using suite

**Comment by Richrfl** [comment]
This is what I get when I run the Suite as Admin:
![1 5 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/16b2224e-cc15-4cdb-ab06-2c51b40637f9)

**Comment by strgaltdel** [comment]
oh,
it seems that suite doesnt connect to the "right place" to look for newer software

from tx side everything seems to be ok

suite has a configuration page 
there you can set the source where it should look for new revisions

ensure that it's set to github, not linked to FrSky !

**Comment by Richrfl** [comment]
The Suite Settings indicate that the Server Location is pointing to GitHub.

**Comment by Richrfl** [comment]
However, these greyed options show only when I run Suite as admin. otherwise shows a normal screen but makes a "fake" update successful". Maybe something is wrong with the Suite itself? I guess that tomorrow, after doing the manual copy, we will know for sure.

**Comment by mawzthefinn** [comment]
Likely Suite itself. I successfully updated an X18 with Suite 1.5.2 a couple days ago.

**Comment by Richrfl** [comment]
Therefore would you suggest that the Suite SW may have been corrupted when I downloaded it, or in the installation process?

**Comment by mawzthefinn** [comment]
Probably after installation. I'd uninstall and re-install with a fresh download

**Comment by Richrfl** [comment]
Sounds good. I'll try it right away.

**Comment by Richrfl** [comment]
mawz, it didn't work I uninstalled Suite, Downloaded Ethos_suite_windows again from revision 1.5.2., ran the update outdated files, and received a Successful update, but the TX still shows 1.5.1. I will go now to manual mode as I said before.

**Comment by Richrfl** [comment]
Success!!!!! I noticed my E drive was overloaded, therefore I deleted 80% of the logs and tried again. This time I saw the update in the TX screen and on the info screen I saw the new rev was running. I hope this lead will help some other users. I will also review which data I want to collect to reduce the size of the logs. Happy St. Patrick guys!!
