### ISSUE TITLE
mpm up to date

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#3655]
I try to update my tmx5 lite MPM with the radio and i get a no sync! message. when i do it with my computer it's ok, i've just installed the new main.lua  for mpm too.

thanks

**Comment by mawzthefinn** [comment]
You cannot flash an MPM from ETHOS at this time. 

You need to update it via USB, or using an OTX/ETX radio.

**Comment by ronron84** [comment]
ha ok i thought it was possible, i flash it via USB with flash multi

thanks
mawz

Le sam. 16 mars 2024 à 20:09, mawzthefinn ***@***.***> a
écrit :

**Comment by digitalonkel** [comment]
> You cannot flash an MPM from ETHOS at this time.
> 
> You need to update it via USB, or using an OTX/ETX radio.

Strange, I was able to update MPM Lite with Tandem XES using ETHOS V1.5.2

**Comment by bsongis-frsky** [comment]
> You cannot flash an MPM from ETHOS at this time.
> 
> You need to update it via USB, or using an OTX/ETX radio.

Yes it is available. I have done it with an iRX4

**Comment by ronron84** [comment]
Ok so it didn't work with my module URUAV TMX5 Lite (with the good ship), i get a no sinc error message, The upgrade run with the soft flash multi

**Comment by ronron84** [comment]
Bauds rate perhaps ? mine is 155200
