### ISSUE TITLE
Upgrade firmware file not deleted 1.5.2

### ISSUE THREAD

**Issue by retarget** [FrSkyRC/ETHOS-Feedback-Community#3656]
Upgraded Horus 10S from 1.4.17 to 1.5.2 appeared to all go correctly. After upgrade attempted to enter bootloader mode manually and system was attempting a bootloader update looked at the system file list and saw the firmware.bin file still  in the root directory. From the windows Ethos app can switch between bootloader and app mode with no issues. Perhaps an install cleanup issue. Should also mention the date and timestamp of the firmware.bin matches the install date and time.

**Comment by bsongis-frsky** [comment]
Reproductible?
