### ISSUE TITLE
No display view in text widget or checklist on X10 

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3657]
The text display on the X10 does not work in the widget or in the checklist view. Regardless of whether it is a .txt or .md file.
The corresponding documents/user folder is created and the selection of the text file is also displayed, but the widget remains empty.

Ethos Version 1.5.2
Transmitter Horus X10s ISRM

thanks

**Comment by strgaltdel** [comment]
.. and #3640 couldn't help?

the other thing to mention is,
horus transmitters got no md support

https://www.rcgroups.com/forums/showpost.php?p=51958941&postcount=20547

... not enough hw ressources

**Comment by bsongis-frsky** [comment]
Please show your .txt file so that we can check what goes wrong on your transmitter

**Comment by Skippydi** [comment]
Hello Bertrand, this one
[ZELOS.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14692983/ZELOS.txt)
