### ISSUE TITLE
Checklist text problem on X12S

### ISSUE THREAD

**Issue by RA-100** [FrSkyRC/ETHOS-Feedback-Community#3658]
Text checklist (modelname.txt) on X12S have some issues:

1. You can only navigate via PgDn button. No smooth or line scroll, no PgUp. Only PgDn. 
2. You can see 7 lines of text. Pressing PgDn will skip 4 lines and show you lines from 12 to 18.
3. So lines number 8-11 are missing

Test:

![IMG_3193](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/78615063/7976ee77-7ed6-42b1-8830-87c815ef9dd6)
(PgDn)
![IMG_3194](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/78615063/ecd4e3ae-763b-439f-a96b-d42864bf9acc)

Just a side note: Too bad Horus didn't support Markdown at least for titles (orange text) and bold numbers. All other functions can be omitted, but these two would help a lot...

**Comment by bsongis-frsky** [comment]
We do our possible to keep Horus compatible with 1.5.X and be able to share the models with Tandem radios. But all the new functions have a price in flash and we cannot add all the nice functions which are available on Tandem!

**Comment by bsongis-frsky** [comment]
There is indeed a problem with the Page keys
