### ISSUE TITLE
Spanish translation missing

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#3659]
Tandem X18SE
Ethos 1.5.2 Spanish

![20240316_223946](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/b6641dc6-9992-442c-b2da-2693a1eb91f9)

Voice-->Voz
Play File--> Reproduce Fichero
Start--> Inicio
Are you sure you want to remove this acción? --> ¿Esta seguro de quitar esta acción?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/bf5f1f66-6582-406e-8aeb-4185795d728d)

Waiting for feedback from luznatural too

**Comment by Luznatural** [comment]
According to the same philosophy used in the rest of the translations, I would suggest:
¿Está seguro de eliminar esta acción?

**Comment by afdofdez** [comment]
Yes it is better.
"¿Está seguro de eliminar esta acción?"

**Comment by Luznatural** [comment]
Fernando, if you want I can send you the Es.json file for you to test if all the issues are fixed

**Comment by afdofdez** [comment]
ok, send it to me.

 

De: Luznatural ***@***.***> 
Enviado el: martes, 19 de marzo de 2024 19:07
Para: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
CC: Fernando Fernández ***@***.***>; Author ***@***.***>
Asunto: Re: [FrSkyRC/ETHOS-Feedback-Community] Spanish translation missing (Issue #3659)

 

Fernando, if you want I can send you the Es.json file for you to test if all the issues are fixed
