### ISSUE TITLE
Gps relative altitude

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#366]
Please could we have an option to display the GPS relative altitude to launch point ie  zero. If you press the reset telemetry option with long press enter it briefly goes to zero but then display the absolute altitude again. Thanks

**Comment by Hobby4life** [comment]
Hmm, can you check if "Whole telemetry" reset works?
Because I have flown today and a Whole reset did a correct 0 offset for me.

**Comment by islandflight** [comment]
Just tried reset whole telemetry and for me again it goes to zero briefly but then reverts to the absolute altitude when the trigger switch is released.

**Comment by Nicholas-Luoyi** [comment]
You mean a function which could switch relative altitude and absolute altitude?

**Comment by islandflight** [comment]
Not necessarily a function that switches between the two but yes the option to display the altitude as relative this could be a box to select within the GPS sensor page
