### ISSUE TITLE
LUA nightlies version, error Max instructions count reached

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#3661]
Hello Bertrand,
with the nightlies version I get the LUA script
the following message, "Max instructions count reached"
in 1.5.2. Release I don't get this message, there was a change in the LUA, even if I use the main.luac with release 1.5.2 I get the message in the nightlies.

Thank you
Greetings Benno

**Comment by bsongis-frsky** [comment]
Would you paste your script? Nightlies and 1.5.3 introduce a protection against infinite loops

**Comment by Benno00** [comment]
ok, her is the last version of swmap
[swmap 1.26.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14633204/swmap.1.26.zip)

**Comment by Benno00** [comment]
or do I have to make a new version of swmap?
I can't actually have an endless loop in it
![swmap screen](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/c1854e32-ae4a-491d-917d-0009c027cbd1)

**Comment by bsongis-frsky** [comment]
I have allowed more instructions, but I think you use far too many already

**Comment by Benno00** [comment]
Hello Bertrand,

 

What's the maximum? 

For me it gets off after 17 calls.

See here, the sw_pos table has 27 entries

 



 

 



 

Mit freundlichem Gruss 

Benno Jurisch

 

Benno Jurisch
Siedlung 5, 27624 Geestland
Telefon: +49 (0) 4708 707
Mobil: +49 (0) 152 337 76 727
 ***@***.***> ***@***.***

 

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Montag, 18. März 2024 17:08
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] LUA nightlies version, error Max instructions count reached (Issue #3661)

 

I have allowed more instructions, but I think you use far too many already
