### ISSUE TITLE
ethos suite 1.5.2 models edit button

### ISSUE THREAD

**Issue by Crunch69** [FrSkyRC/ETHOS-Feedback-Community#3662]
ethos suite  1.5.2 the models edit button is not working it is grayed out.   I really need this the screen, its to small for my fingers and my eyes.  Without a large PC  screen it is very difficult when you are learning ethos or trying to create models with complex programing.

**Comment by Richrfl** [comment]
I don't see a model edit in Ethos Suite. If you mean Ethos FW in the transmitter, I do not see that problem.
About a PC screen, you can use the Simulator. You can create most of the program and copy the file to the transmitter.

**Comment by Nicholas-Luoyi** [comment]
This part hasn't been finished yet
