### ISSUE TITLE
1.5.2 - Twin xlite s: external module not showing up signal bars at top notification bar

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#3663]
I have upgraded to 1.5.2 and have upgraded all lua folders and flash files. Upon connection I used to see signal bars EXT on top notification bar but it stopped showing now. Tried removing telemetry and selected discover new sensors at that time the signal bars showed up but after restarting the radio it stopped showing again. I have x20s hd radio as well and this works fine in that radio. I’m using happy model es24tx lite pro module.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/002e3729-bfe9-47a8-a7ff-9a3a1b239479)

**Comment by bsongis-frsky** [comment]
What is the protocol chosen?
Why RSSI is in RED?

**Comment by kakashi2018** [comment]
Have selected expresslrs protocol and this time taken picture when rx is still connected and you can see the signal is showing 0 bars
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/33295909/1ee6ec86-3651-42d3-9fe9-b3d5d917281b)

**Comment by kakashi2018** [comment]
Creating a new model fixed my issue. Dontknow whats wrong with my old model.
