### ISSUE TITLE
CHECKLIST

### ISSUE THREAD

**Issue by KLOSTRO** [FrSkyRC/ETHOS-Feedback-Community#3664]
Bonjour,
J’ai une X20S, et je voulais tout simplement poser une question au sujet de la checklist don’t il est possible de noter pour chacun de nos modèles des impératifs de vol.
Je ne comprends pas pourquoi c’est aussi compliqué d'ailleurs, je n'ai pas réussi à voir le rendu sur ma radio, sauf si je ne le fais pas au bon endroit mais ?????.
J’aurais plutôt vu quelque chose de plus fluide, comme par exemple pour chaque modèle y mettre comme un pense bête avant le vol du modèle, un rappel mémoire.
Donc une page que l’on ouvre sur le modèle souhaité ou nous pourrions mettre un petit texte et ce à partir du clavier de la radio directement, voila c’était tout.
On pourrait avoir disons une dizaine de lignes et y mettre le nom de l’avion, au dessous 3S 2200mAh, puis au dessous hélice 12x6, encore en dessous CG 90mm etc.....
Ce serait quand même plus simple que de mettre un fichier dans la radio en txt ou md ou déjà cela complique les choses et ceci pour chaque modèle mais d'ailleurs je nai pas réussi.
Merci pour votre retour

**Comment by bsongis-frsky** [comment]
Vous allez passer un temps fou à écrire ce fichier depuis la radio, c'est nettement plus simple avec un fichier .md édité depuis un ordinateur !

**Comment by KLOSTRO** [comment]
Bonjour,
Pour ma part, cela aurait été parfait mais si c'est la procédure, je m'y tiendrais.
Par contre pouvez vous m'indiquer clairement, le chemin, et l'endroit exact ou déposer les fichiers (bien sur sur le lecteur de la carte SD ).
Par contre, les fichiers md ????? je l'ai fais en txt
Merci
