### ISSUE TITLE
1.5 Play Sequence - Play Telemetry Values as Global Function

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#3665]
I played around with the new play sequencer and thought I could setup a global function reading the most common telemetry values and I don't have to set it up per model. Well, didnt work that great and it felt it doesn't use AppID or BusIDs but rather some kind of per model index?
Or maybe it was because I have a whole bunch of different telemetry setups (FrSky Sensors, oXs DIY sensors, BLheli32, Unisense) and it just doesnt match ....

Any clarification would bee great... :-)

**Comment by bsongis-frsky** [comment]
When there is one sensor inside a PlayAudio function, it should not be possible to make the function global
