### ISSUE TITLE
Edge in Vars does not work

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3666]
X10Express/Nightlies 1.5 from 16.3.24
Hello, I have an LS as source in Var1 in line 5, which is TRUE when the transmitter is in operation. This is to set a specific output value. Although nothing is marked as active, Edge is still permanently active and thus prevents the entire function of the var. In 1.5.2 this was still in order and only a pulse was created to set the basic value. 
Thank you
Wolfgang

![V ar1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/5386d5ac-2d59-4654-acb2-72e8fed16f28)

**Comment by Wolepo** [comment]
Will there still be a change here?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/33dd8578-df58-46f9-8e3e-574685e5e278)

Fix ready for next nightlies

**Comment by Wolepo** [comment]
Galvanic isolation from an LS is still not provided.
![TX EIN](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/5022e661-c4a2-4e4e-8186-4e5ef65e6596)
LS48 is permanently active after switching on and prevents further action in VAR1 despite Edge. See picture above
Thank you
Wolfgang

**Comment by bsongis-frsky** [comment]
Nightlies are online, please tell me if the problem is fixed?

**Comment by Wolepo** [comment]
Hello Bertrand 
The galvanic isolation through Edge also works very well with an LS. Because Edge is now also available with Always on, even the LS48 can be dispensed with.
Thanks for the good work.
Wolfgang
