### ISSUE TITLE
add maps to gps

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#3668]
I'm trying to add a map so when i am flying i can see where the sailplane is in relation to me. Any idea how this is done, not sure if its possible. Frsky x18se, 1.4.17.
Thanks to the group,
Bill

**Comment by strgaltdel** [comment]
try ethos gps map widget,
(descriptions available on rcg and youtube)
or hobby4life gps widget,
github


keep in mind
no widget can give you the "real relative position" because there is no gps (including "compass functionality") in your x18

they all show the model on a fixed position map

**Comment by lotus1235** [comment]
Thank you.
