### ISSUE TITLE
Play Track "Skip on startup" setting ignored when switching models

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#367]
When switching between models, the "Skip on startup" setting is ignored for the play track special function. Seems like it should skip for both startup and when switching between models. Or is this is intended?

**Comment by Hobby4life** [comment]
+1

I noticed it to, that there is no difference is turn it on and off.

**Comment by dwheel** [comment]
I was about to add this issue also. Very irritating!
