### ISSUE TITLE
Spanish translation missing

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#3672]
Tandem X18SE
Ethos 1.5.2 Spanish

![fallo1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/7301e847-803d-4bbe-b3aa-3445227ba7f1)

Are you sure you want to remove this screen?  --> ¿Estas seguro que quieres eliminar esta pantalla?

**Comment by afdofdez** [comment]
![Fotos3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/90b94944-8613-4d52-a76b-4821a6b13d1a)
![Foto5](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/ce271740-7015-440f-bcc8-b2439892b161)
![Foto4](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/d426dd5b-49ac-4030-8992-da58b3cee642)

**Comment by afdofdez** [comment]
![Foto6](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/c8a2295b-bad5-448a-aba7-1a84acccee7b)

**Comment by mgsanna** [comment]
maybe you are not aware that there is already a translator for Espaniol, and as new feature are implemented inside firmware, the translator is preparing almost of the time the new translation for the next minor release.... so you cannot expect that developer of software make also the translation may be you need to be in touch with the Spanish translator that is @LuzNatural here on GitHub....
<img width="937" alt="Screenshot 2024-03-19 alle 18 50 33" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/d766e9f8-711c-407b-b7ff-21488b162771">
as you can see in Ethos suite....

**Comment by Luznatural** [comment]
I think he is aware of it.
I appreciate his help as he is helping on detecting all the lacks of translations from the radio to make sure that we fix them in the next radio firmware. I already sent a new translation to @bsongis for inclusion into Ethos 1.5.3. Let's hope that all the issues are solved.
I found around 40 new corrections that I fixed in the translation to Es.

**Comment by mgsanna** [comment]
Ok, In this case I apologies myself... with @afdofdez, my intentions were only avoid "non-Issue" and double work...

**Comment by bsongis-frsky** [comment]
Please check the nightlies to be sure nothing has been forgotten!
