### ISSUE TITLE
Trims on Freemix

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3673]
It would be good to have the option to choose a trim in a freemix.
Thank you for 1.5!

**Comment by mawzthefinn** [comment]
Add them as a source to an Offset action.

**Comment by WhiskeyGolf** [comment]
I had the idea too, but then it's always 1% steps and not 0.2% no matter how I set the trims.  Is it possible to adjust the sensitivity of the offsets?

**Comment by bsongis-frsky** [comment]
Your Offset may be driven by a Trim

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1e603264-143d-4a0c-8011-223d0b2ef277)

**Comment by WhiskeyGolf** [comment]
Yes, but then the fine steps of the trim are not adopted (0.2%) but 1% is added per trim step.  This is too much.  The trim settings are fine (0.2%).

**Comment by mawzthefinn** [comment]
> Your Offset may be driven by a Trim
> )

I just tested and @WhiskeyGolf is correct.

You're limited to 5uS of resolution when using a trim via an Offset line, even if that trimmer is set to Extra Fine resolution. Regular trims are 1uS resolution at Fine.

**Comment by WhiskeyGolf** [comment]
I just found out that if you use a trim as a source for a freemix, the steps are 0.8% instead of 0.2%.  Should that be so ?

**Comment by bsongis-frsky** [comment]
The range of the trim was wrongly taken into account there. It will be fixed in the next nightlies.

**Comment by WhiskeyGolf** [comment]
Many thanks so far!

I also noticed that :

If you use repurpose trims in the vars, the steps are always 0.1%.  No matter how you set the trims.  

If you take a Var to set an offset, this can only be done in 1% steps, no matter how finely you have set the VAR steps.  

I don't know if this is part of the same error.

**Comment by bsongis-frsky** [comment]
Regression introduced when fixing this issue. It has been raised by #3724 

Regression test added:
 - old 1.4.X setup loaded ("Full Range" option applied to the Trim)
 - check that Elevator Trim on Max gives a value of 100%
