### ISSUE TITLE
Suite 1.5.2, Mac 12.7.4 Image manager has some problems

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3675]
I am attaching screenshots. One is the default window size and one is the full screen version. 

The layout of this window is having problems, and the 'Transcode' button never becomes active. 

The radio file viewer does not resize the content for the smaller window. 
The image selector does not resize the image to fit in the space provided. 

![Screen Shot 2024-03-20 at 8 39 11 AM](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/b12a0e5f-80c2-4a5c-9dc6-08cbb6c703cf)
^Default window size

![Screen Shot 2024-03-20 at 8 40 21 AM](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/12c32725-a2e1-40da-bde5-bb8fefad2994)
^Full screen

**Comment by Nicholas-Luoyi** [comment]
Suite will have a re-designed UI soon...

**Comment by spoke2570** [comment]
I look forward to it. The results have been impressive to date! As of now this image tool is broken mac users. ..and yes, I did just use a web app to sort out a model image.

**Comment by spoke2570** [comment]
Fixed in 1.5.3
