### ISSUE TITLE
The curve function 0<X produces incorrect values

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3676]
Hello dear Ethos team, thank you for your great work!
I think there is a bug in the curve functions. Channel 9 and Channel 10 are set up so that when positive values are generated with Pot 1, these values are only output on channel 9, in contrast when negative values are generated with Pot1, they are only output on channel 10. (see the screenshot).
This function x>0 works on CH9, but the function 0<x does not work on CH 10.

Ethos Version 1.5.2
Receiver Tandem X20s / Ethos Simulator 1.5.2

![L1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/556e3d6f-8da4-476c-aaf2-74654eaf0164)
![l2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/c67809fd-2cc7-4e81-8d3f-f8d4e5daf000)
![L3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/bf3e17be-7909-40fb-b808-b01533303fda)
![L4](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/e33ad37d-fbff-4798-a7b5-34283f652ccd)

**Comment by bsongis-frsky** [comment]
Why do you multiply by a negative value before applying your K7 curve?

**Comment by mawzthefinn** [comment]
Yep, -x* -10 = 10x

That should never work as programmed, because of the negative multiplication line.

**Comment by hrenz** [comment]
minus * minus = plus

**Comment by Skippydi** [comment]
> Warum multiplizieren Sie mit einem negativen Wert, bevor Sie Ihre K7-Kurve anwenden?

The issue has been closed, does this mean that the bug has been fixed?

**Comment by mawzthefinn** [comment]
> > Warum multiplizieren Sie mit einem negativen Wert, bevor Sie Ihre K7-Kurve anwenden?
> 
> The issue has been closed, does this mean that the bug has been fixed?

No, it means that there isn't a bug, at least as described.

I just tested this myself, and it worked exactly as I expected. As programmed, positive values on Pot1 output as negative values on Ch10, scaled to 10%. Negative values are zero, because they become positive before the curve is applied because of your -10% weight line. 

Your multiplier needs to be 10%, not -10% for this to work as you described. Or you need to put your curve before the weight if you are wanting to get +4 out from -40 in on that channel.

**Comment by Skippydi** [comment]
> > > Warum multiplizieren Sie mit einem negativen Wert, bevor Sie Ihre K7-Kurve anwenden?
> > 
> > 
> > Das Problem wurde geschlossen, bedeutet dies, dass der Fehler behoben wurde?
> 
> Oder Sie müssen Ihre Kurve vor das Gewicht stellen, wenn Sie +4 von -40 auf diesem Kanal erreichen wollen.
OK, that's how it works. Thank you.

**Comment by Skippydi** [comment]
> > > Warum multiplizieren Sie mit einem negativen Wert, bevor Sie Ihre K7-Kurve anwenden?
> > 
> > 
> > Das Problem wurde geschlossen, bedeutet dies, dass der Fehler behoben wurde?
> 
> Nein, es bedeutet, dass es keinen Fehler gibt, zumindest nicht wie beschrieben.
> 
> Ich habe das gerade selbst getestet, und es hat genau so funktioniert, wie ich es erwartet hatte. Wie programmiert, werden positive Werte auf Pot1 als negative Werte auf Ch10 ausgegeben, skaliert auf 10%. Negative Werte sind Null, da sie aufgrund der Gewichtungslinie von -10 % vor dem Anwenden der Kurve positiv werden.
> 
> Ihr Multiplikator muss 10 % betragen, nicht -10 %, damit dies wie von Ihnen beschrieben funktioniert. Oder Sie müssen Ihre Kurve vor das Gewicht stellen, wenn Sie +4 aus -40 in diesem Kanal erreichen wollen.

Hi, it works now, but I'm still of the opinion that the function is not a curve function, but a logical function with true and false. Then the expression would work properly. But anyway, thank you for your effort.
