### ISSUE TITLE
Last Nightlies 1.5 , Page Button inside widget don't work

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3679]
As per title, if you are inside a widget (like StaB TDSR 12 widget) "page" button doesn't work neither with single push or long push.... 
so you can not change page... it happen with TDSR lua scripts, RB25S and RB35S lua scripts..
Instead reverting to 1.5.2 everything work as supposed

**Comment by bsongis-frsky** [comment]
I have forgotten to include the "deprecated" constants in 1.5.3
Fixed for the next nightlies

**Comment by mgsanna** [comment]
thanks @bsongis-frsky @bsongis
