### ISSUE TITLE
Copy Trims to Output subtrim

### ISSUE THREAD

**Issue by commsart** [FrSkyRC/ETHOS-Feedback-Community#368]
Enable copying the current TX trim value to the Output subtrim. Channel by channel.
It is available in OpenTX and very useful.

Ethos on X20S, 1.0.7, FCC

![20210530_150003](https://user-images.githubusercontent.com/22880475/120092733-73dbce80-c158-11eb-9829-904aba7d8f04.jpg)

**Comment by Beereycalfs** [comment]
yes please what he said

**Comment by loetefix** [comment]
And copy limits to all channels. So all channel have the same limits( for Heli FBL)

**Comment by poge-st** [comment]
Totally agree that this feature is really necessary but I would even "improve" it compared to the opentx implementation .... copy trim to subtrim and then afterwards set the copied trim again to Zero - so no change in the output and full trim range available again. Or at least ask with a dialog if the copied trim shall be set to 0 also.

**Comment by Joetrin** [comment]
I'm wondering if this was ever implemented, I can't seem to find it in 1.0.10 RC4

Thank you

**Comment by pld74** [comment]
Ok so I see that this is a duplicate and closed. But is this being implemented?

**Comment by pld74** [comment]
@bsongis-frsky Any Idea when/if this is being implemented?

**Comment by commsart** [comment]
Any movement here? Pretty cumbersome to read signal micro-second (us) values, reset the trim and then by subtrim (%) adjust it to the recorded us.

**Comment by Hermann62** [comment]
Really frustrated !

It seems that the overview has been completely lost on the following issues:

#944, #368, #664, #1114, #41, #396, #513, #532, #1031, #295

all on the same topic (trim to subtrim). Again and again with cross-references to another issue, most of them are closed, but no outlook if / or when something else will be implemented here. 
You can open many new issues, but it won't help.
If you don't want to implement this feature, you can write that too, everything else is just unattractive.

**Comment by Hermann62** [comment]
Am i the only one who is interested in this basic feature ?

**Comment by poge-st** [comment]
@Hermann62  I am also still into this , you are not alone :)

Unfortunately it is a feature - not a "bug" ;)
Lets hope this topic gets some attention again, i would be very happy if someone of FrSky would work on this nice feature.
Guess for the moment there is a lot going on with the implementation of LUA.

by the way , happy new year and successful flying !

**Comment by FrankKoelma** [comment]
> Really frustrated !
> 
> It seems that the overview has been completely lost on the following issues:
> 
> #944, #368, #664, #1114, #41, #396, #513, #532, #1031, #295
> 
> all on the same topic (trim to subtrim). Again and again with cross-references to another issue, most of them are closed, but no outlook if / or when something else will be implemented here. You can open many new issues, but it won't help. If you don't want to implement this feature, you can write that too, everything else is just unattractive.

I am also looking for this feature. Used it a lot on my Horus OpenTX. Is it already there? I am also lost in all the closed items. Missing the explanation why items are closed ?!?

**Comment by commsart** [comment]
I have as feeling that the developers do not know how to implement it. It is one of the more advanced features that requires good knowledge of the system.Sent from my Galaxy
-------- Original message --------From: FrankKoelma ***@***.***> Date: 10/8/22  19:50  (GMT+10:00) To: FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc: commsart ***@***.***>, Author ***@***.***> Subject: Re: [FrSkyRC/ETHOS-Feedback-Community] Copy Trims to Output subtrim (#368) 

Really frustrated !
It seems that the overview has been completely lost on the following issues:
#944, #368, #664, #1114, #41, #396, #513, #532, #1031, #295
all on the same topic (trim to subtrim). Again and again with cross-references to another issue, most of them are closed, but no outlook if / or when something else will be implemented here. You can open many new issues, but it won't help. If you don't want to implement this feature, you can write that too, everything else is just unattractive.

I am also looking for this feature. Used it a lot on my Horus OpenTX. Is it already there? I am also lost in all the closed items. Missing the explanation why items are closed ?!?

**Comment by FrankKoelma** [comment]
How does this work. Can we vote for this fix (new feature)?
I even want to pay something for it.
regards,
Frank

**Comment by jasc76** [comment]
Please make it happen !

**Comment by robertoalmeida** [comment]
Has it been closed and will not be implemented?

This functionality is extremely important.
I believe that several people are rooting for you to make it happen.

**Comment by commsart** [comment]
Sometimes it means that it has been resolved and is about to be 
released. Is it the case?

Artur Uzieblo
+61 412 699 633

Notice of Confidentiality - WITHOUT PREJUDICE. This email message is for 
the sole use of the intended recipient and may contain confidential and 
privileged information. Any unauthorised review, use, disclosure or 
distribution is prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies of the 
original message.
-------------------------------------------------------------------------

**Comment by Hermann62** [comment]
Where should the solution be?
By setting each trim value individually by hand,
which takes at least as long as creating a new model.
No, sorry, but that is certainly not a solution.

**Comment by commsart** [comment]
I think that you misunderstood my comment. We do need the solution but 
the fact that it has been closed does not mean that it has been 
abandoned. A.

Artur Uzieblo
+61 412 699 633

Notice of Confidentiality - WITHOUT PREJUDICE. This email message is for 
the sole use of the intended recipient and may contain confidential and 
privileged information. Any unauthorised review, use, disclosure or 
distribution is prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies of the 
original message.
-------------------------------------------------------------------------

**Comment by Hermann62** [comment]
The solution is "copy trims to subtrims" with one button in the subtrim - menue.

**Comment by commsart** [comment]
Hermann, thanks, how to access this functionality? I have the latest 1.4.5 (on X20S) and I cant find it.

**Comment by Hermann62** [comment]
Hi Artur,
i have the german Version of ETHOS installed, try it in english:
**The solution should be:** Find it under Models / Trims.

**Comment by weixelgeist** [comment]
> Hi Artur, i have the german Version of ETHOS installed, try it in english: **The solution should be:** Find it under Models / Trims.

Is it working now or not?

**Comment by Hermann62** [comment]
No it is not working ! ... first it has to be programmed.

**Comment by weixelgeist** [comment]
> No it is not working ! ... first it has to be programmed.

maybe anyone can make a lua?

**Comment by jasc76** [comment]
I'm lost....
Has this been implemented or not ?!

**Comment by Hermann62** [comment]
No, it isn't.

**Comment by weixelgeist** [comment]
I can not understand why this important feature should not be realized? It would be a great help for fine tuning new models. I can't imagine that the programming effort for this would be very large. Maybe we can convince "bsongis-frysky" that this is necessary.

**Comment by GiorgioCirelli** [comment]
Today **30 July 2023** the function has **not** yet been inserted.
Or am I wrong?

**Comment by nightfury24** [comment]
Hello developers,
Well this is strange, I have switched from opentx to ethos and loved it and were trying to find how copy trims to subtrims and end up here replying to this post. What ? Ethos doesn’t have this function. ethos is developed by opentx developers ? Correct. Common frsky developers it is very important function.
2023 ending soon.
