### ISSUE TITLE
Multiprotocol wrong rssi warning values 

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3680]
I use an ACCST protocol via my multiprotocol module in my x20pro with 1.5.2.  In the RSSI Telemetry the default values ​​for low and critical are set at 35dB and 32dB.  Shouldn't these be 45dB and 42dB for ACCST?  Would it be possible to change these values ​​by default so that errors cannot occur?

**Comment by mawzthefinn** [comment]
The defaults are for the FrSky protocols on the main RF unit. 

You need to adjust as appropriate for the specific MPM protocol just like in OTX/ETX. The difference is that ETHOS's defaults are correct for TANDEM/TWIN/ACCESS and Archer Plus, while OTX/ETX's defaults are correct for older ACCST receivers.

**Comment by WhiskeyGolf** [comment]
But Ethos also recognizes ACCST protocols via the main module and then automatically sets 45dB and 42dB in the rssi.  Wouldn't this also work with the ID of sensors via the MPM?  With OTX/ETX you can simply make the settings for the warning on the Telemetry page without first discovering a sensor and only then setting the values ​​in the sensor type.  This is much clearer and cannot be overlooked.

**Comment by bsongis-frsky** [comment]
Which protocol ?
"FrskyX"?

**Comment by bsongis-frsky** [comment]
The RSSI threshold is dynamic in Ethos. 
The thresholds cannot not the same for ACCST / ACCESS / Crossfire / Ghost / ELRS.
Here the threshold will depend on the protocol setup for the Multimodule. 
So I will change them one by one to be sure there is no mistake.

**Comment by WhiskeyGolf** [comment]
I use the FrskyX2 protocol in clone mode so that I don't have to rebind all of my models.

**Comment by bsongis-frsky** [comment]
Those lines will use the ACCST RSSI thresholds:
- "FrskyX", 15
- "FrskyX2", 64
