### ISSUE TITLE
Slow function in the mixer does not work with switch or a logical switch 

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3683]
The slow function in the mixer does not work if, for example, a variable is specified as the source, and  activated with a switch or a logical switch.
Ethos 1.5.2
Receiver Tandem X20s / Sim

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/5432c068-6001-439e-899a-d1e08f5324ce

**Comment by bsongis-frsky** [comment]
Just put your condition on the slow, not on the whole mix

**Comment by WhiskeyGolf** [comment]
I have the same problem when I select a maximum as the source and some switch as active condition .  No matter where you use the condition, the slow doesn't work

**Comment by WhiskeyGolf** [comment]
Could it also be that the slow function works differently on the outputs than in the mixes?

**Comment by bsongis-frsky** [comment]
Here is the way to configure your mix:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/61e0d153-5aea-415f-99ac-0a79e3185fe1)

**Comment by bsongis-frsky** [comment]
Or if you need VAR1 as weight:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/3dba57b8-e9a1-457c-bc25-947204d8d584)
