### ISSUE TITLE
Counting in Spanish

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#3685]
When the show value function is executed to play a variable in audio, in my case height. It counts correctly from 1 to 100 but from 101 onwards it does so incorrectly, it says:

"cien uno" and I should say "**ciento** uno"
"cien dos" and I should say "**ciento** dos"
.....................
"cien cincuenta" and I should say "**ciento** cincuenta"
....................
"cien noventa y nueve" and I should say "**ciento** noventa y nueve"

**Comment by bsongis-frsky** [comment]
I propose that the next ES audio packs contain:
cien.wav "cien" (used only when 100 is not followed by anything)
100.wav "ciento" (all other cases)
Is that OK?

**Comment by afdofdez** [comment]
Is OK.

 

De: Bertrand Songis @ FrSky ***@***.***> 
Enviado el: lunes, 25 de marzo de 2024 10:29
Para: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
CC: Fernando Fernández ***@***.***>; Author ***@***.***>
Asunto: Re: [FrSkyRC/ETHOS-Feedback-Community] Counting in Spanish (Issue #3685)

 

I propose that the next ES audio packs contain:
cien.wav "cien" (used only when 100 is not followed by anything)
100.wav "ciento" (all other cases)
Is that OK?
