### ISSUE TITLE
XE. USB connection is unstable.

### ISSUE THREAD

**Issue by Beastyboy80** [FrSkyRC/ETHOS-Feedback-Community#3687]
XE. USB connection is unstable.
USB connection keeps breaking down. When copying many files via Explorer to the M drive.
The drive must then always be checked for errors

Tried different cables.
Tried USB2 and USB3

**Comment by mawzthefinn** [comment]
Which ETHOS and Firmware versions?

**Comment by robthomson** [comment]
I have seen this happen on most of the 1.5 releases - even on the X20.   Never been sure if its the system or the pc!

**Comment by Beastyboy80** [comment]
> Which ETHOS and Firmware versions?

The last Versions

**Comment by strgaltdel** [comment]
really?
compiler finished firmware files app. 1 hour before you opened this issue (-;

latest suite was released yesterday

**Comment by filduch** [comment]
Same problem as Beastyboy80
I'm using X20S (1.5.2) - WIndows 10 and its seem to work better on USB2
Worked fine on 1.4.x

**Comment by Dsrenger** [comment]
Can confirm on a X20s.

Ethos 1.5.3

Just copied 8 log files to the X20s. First try...directly got the error message. Windows lost the X20s drives complety (see screenshot...no SD or Flash drive in the explorer

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/612a98de-5340-43f7-83b4-ab2212175d30)

**Comment by strgaltdel** [comment]
win10 / usb2 / x18se / ethos 1.5.2 / target: NAND

1.
copied app 270 files , 20MB, without problem

2.
one 90MB file no problem,

**Comment by bsongis-frsky** [comment]
@Dsrenger I assume you did the copy in firmware mode? Because bootloader is still 1.4.X
It would mean:
- you can copy your logfiles in bootloader mode
- you CANNOT copy your logfiles in firmware mode
Am I right?

**Comment by bsongis-frsky** [comment]
For @strgaltdel it's even more complex, because he has X18SE, so 2 drives.
So ... 
- copy files on Nand in bootloader mode
- copy files on Nand in firmware mode
- copy files on SD in bootloader mode
- copy files on SDin firmware mode

**Comment by Dsrenger** [comment]
@bsongis-frsky 

I copied now 45 minutes files back and forth and cannot reproduce the behaviour I had yesterday.

X20s Ethos 1.5.3 with Bootloader 1.4.15

I can copy files back and forth in bootloader mode and firmware mode.

tbh, I have no idea where that problem was yesterday.

Perhaps Beastyboy or filbuch can reproduce. I cannot anymore.

🤷‍♀️

**Comment by bsongis-frsky** [comment]
Perhaps Ethos Suite is running in the background in one case and not in the other case?

**Comment by Dsrenger** [comment]
Tried that, even with different versions of the suite open in the background. I opened as well different versions of the simulator in the background

I have no idea what was different yesterday.

I give up. It works for me.

Perhaps another user can reproduce.

**Comment by strgaltdel** [comment]
Dennis,
is there any virus scan engine with scheduled tasks on your notebook?

i know that some can produce much io load
in case a scanner "detects" the mapped tx drive during a "complete scan" i wouldn't rule out bottlenecks or race conditions, especially in case the target is not the fastest.

at least it could explain that sometimes there are problems, and sometimes not,
even under same conditions

.. and both days you used same port and same usb cable?
