### ISSUE TITLE
X18SE TRIM: Adding a new behaviour-line does not show value field

### ISSUE THREAD

**Issue by Kreisflieger** [FrSkyRC/ETHOS-Feedback-Community#3688]
Trying to follow ´maws´ video on Idle Up Revisited on YouTube, I found, that on my X18SE Ethos 1.5.2. stable and also 1.5.2 Nightlies
that in the TRIM section by adding a Behavior line, the value column is not displayed.

Here are the relevant screenshots, to explain ( hopefully more clear than my writing )

![1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91411897/48d0a856-c479-4b0e-bd10-4c2750140c05)

![2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91411897/d604ed66-0bdb-4b47-8cf3-665613b209f1)

![3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91411897/1b4fbc06-dea5-4c9b-b44c-9388dcadeb2b)
Here you see the value nfield at right side

![4](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/91411897/196737c9-2ed7-418b-921d-7de2501bd2bb)
adding a new behaviour skips the value field, as the fields are too wide.

**Comment by mawzthefinn** [comment]
My X18 is doing this as well.

**Comment by Kreisflieger** [comment]
Thanks for your confirmation.

Best regards

Stephan

**Comment by bsongis-frsky** [comment]
oops! and nobody saw this problem before!

**Comment by bsongis-frsky** [comment]
Very visible here, the value is displayed, but offscreen ...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6dd10901-8f97-480c-bc0c-1df7ff847dcd)

**Comment by bsongis-frsky** [comment]
It will be available in 1.5.4

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/673d8d43-a753-4364-9c4b-90e6c5ac81b3)

**Comment by Kreisflieger** [comment]
perfect !Thanks a lot for your fantastic work.Many regards Stephangesendet von meinem Galaxy S24 UltraAm 25.03.2024 14:30 schrieb "Bertrand Songis @ FrSky" ***@***.***>:
It will be available in 1.5.4
image.png (view on web)
