### ISSUE TITLE
Screen Design improvements

### ISSUE THREAD

**Issue by commsart** [FrSkyRC/ETHOS-Feedback-Community#369]
Add Label widgets to screen design. It would allow setting teh widget Category to Label and changing the label value.

**Comment by bsongis-frsky** [comment]
I don't understand what you mean, which "Category" do you want to change?

**Comment by commsart** [comment]
Sorry, I made it sounds more complex that it is.

It is simply about adding a Label widget (as in OpenTX). Label would be a static text displayed, possibly with configurable font size.

When we configure the widget, it pops the Category window and within Categories list we would have a Label option.

The sequence as in the pics.

BTW, congratulations on Ethos (and OpenTX), great job! I mean it!

![Step 1](https://user-images.githubusercontent.com/22880475/120246964-304aa700-c2b5-11eb-8209-adce63746553.jpg)
![Step 2](https://user-images.githubusercontent.com/22880475/120246966-317bd400-c2b5-11eb-99b4-2421bab45fd0.jpg)
![Step  3](https://user-images.githubusercontent.com/22880475/120246968-32146a80-c2b5-11eb-95d2-c192aca84fa9.jpg)

**Comment by mawzthefinn** [comment]
This should be pretty straightforward to do with a Lua widget.
