### ISSUE TITLE
1.5.3 Pre-release X10S Express incorrect symbols

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3690]
Hello,
after running all nightlies of 1.5.3 I got some wrong icons. 
![Im Mischer](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/3c6161a3-0708-40e8-b332-194228b22586)
The arrows are displayed incorrectly here

![Im Namen](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/a85a78d3-b542-456f-8153-b50250f74e75)
The same applies to the name 

![Falsche Graddarstellung](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/a22496c9-b8a3-40d2-8466-403f926ec477)
Arrows are displayed instead of °.
These deviations do not exist in the 1.5.2 simulator.

![Impuls](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/5662bd3d-d44c-47ee-9f50-fdb4b5fda681)
In addition, galvanic isolation from the source is still missing here. See also #3666

**Comment by bsongis-frsky** [comment]
You are just missing the fonts, the display issue will happen on BOLD / Bigger fonts (all non default fonts)

**Comment by bsongis-frsky** [comment]
Fonts for 1.5.3 have been uploaded on the server. They are really needed for Horus systems.
