### ISSUE TITLE
1.5: Inverting left and right sliders in hardware menu is not possible anymore

### ISSUE THREAD

**Issue by Dsrenger** [FrSkyRC/ETHOS-Feedback-Community#3691]
In 1.4 it was possible to invert the left and right slider in case you mounted the angle adjustable sliders and moved them from facing upwards to downwards.

See screenshot von 1.4.15 simulator:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/997b4e98-39e0-45b3-bd2b-5d3b50a82391)

This possibility is not present anymore in 1.5

Is this intended or a bug?

It was a very practical feature when moving models between a XE ith sliders upwards and an X20 with sliders downwards (with the adjustable sliders)

Regards
Dennis

**Comment by bsongis-frsky** [comment]
You are right, the merge of this feature has been missed. It will be back in 1.5.4

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9dfba8ce-e293-4e4a-90b6-49e4760e963a)
