### ISSUE TITLE
Ethos Suite 1.5.3: Update of Tandem XE does not work

### ISSUE THREAD

**Issue by Dsrenger** [FrSkyRC/ETHOS-Feedback-Community#3692]
I just tried to update my Tandem XE from 1.4.14 to 1.5.3
First I installed the 1.4.15 bootloader what worked fine.

After that I wanted to update to 1.5.3 and clicked update all components.

The Suite gets stuck at "Waitung for drive"

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/108b51f2-c5f6-4511-9fb2-e7b4396d39c1)

After some time I get the message "Missung drive"

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/1f75cd70-6936-4466-8c1d-c354f75880cf)

There is no crash log in the crashpad folder (as I assume it is not counted as crash)

I tested to write a *.txt file to the XE drives using the windows explorer to confirm windows has access to the XE drives. That works fine.

I opened the suite as administator. That did not help.
As i was on 1.4.14 I tried to flash to 1.4.17 first, but that is not working with the same "missing drive" behaviour.

Interessting is, that my models are not shown under the model manager:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/1a1dc7a8-bd3f-4c66-9252-852a8fd7a7de)

My X20 update works fine with the same setup.

There are some users including Andreas Engel (main distrubutor in germany) stating in the german frsky forum that they have the same issues with the XE (just with the XE)

As per Andreas it helps to use the reparing tool in the suite, repower the XE and do the update afterwards. For sure with manual data backup ect.

So, it seems like a bug in conjunction with the XE. There are possibilities to update the XE, but that should not be neccessary.

I stayed on 1.4.14 to make sure a fix is working. If you need any further information, let me know.

Hope you have all information you need.

Regards
Dennis

**Comment by Nicholas-Luoyi** [comment]
It is obvious that Suite failed to read the internal flash (the 7.3G one). Would you please check:

- The radio.cpuid is there in internal flash? Should be hidden and readable
- Switch between firmware and bootloader to see if it's possible to read the internal flash.

If the internal flash is read by Sutie. The content version (audio version) should be shown in the info page.

**Comment by Nicholas-Luoyi** [comment]
Or if there is an emmc.cpuid file in internal flash. Please remove it

**Comment by Nicholas-Luoyi** [comment]
Oh. I find it...
For now, after updating to a 1.5.X firmware. Please modify something in system level to update the radio settings. Then Suite can read the internal flash disk.

**Comment by Dsrenger** [comment]
For testing purposes I just installed the Suite 1.4.14 as I know it worked there.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/0a6bd918-8896-475d-b08a-a9ac9ccdb930)

As you see on the Screenshot 1.4.14 can read the flash just fine. Everything works as expected (but I guess I should not flash Ethos 1.5.3 with the Suite 1.4.14)

Now I updated the suite through the internal update check to 1.5.2. (As the internal updater is not showing 1.5.3 Suite. This just as side note, shouldnt it show the 1.5.3 suite, as the suite is now a seperate item on the github release page?)

After the update the suite 1.5.2 the suite cannot read the XE flash anymore.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/e32784fd-38f7-4f29-8c5d-287896cc9802)

The radio.cpuid is readable
I can switch between firmware and bootloader. That works fine, but the suite still cannot read the flash.
There is no emmc.cpuid

As the Suite 1.4.14 can read the flash and the Suite 1.5.2 cannot, there clearly happend something inbetween that broke it for the (my) XE

"For now, after updating to a 1.5.X firmware. Please modify something in system level to update the radio settings. Then Suite can read the internal flash disk."

I dont get your point here. I cannot update the 1.5 firmware as the suite cannot access the flash. (I could by using the repair tool, but I dont want to....just kidding, I think it makes sense to stay in 1.4.X to confirm the fix in the suite (assuming it is a suite issue)

Hope that helps.
Regards
Dennis

**Comment by Dsrenger** [comment]
Just as additional hint:

I was curios with which version the issue came up.

Suite 1.5.1 worked fine.
Suite 1.5.2 is not working.

So somewhere in the code changes from 1.5.1 to 1.5.2 is the problem.
