### ISSUE TITLE
1.5.2: 'Repurpose trim' action: trim increment is only 0.1%

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3696]
To reproduce, 

1. Create a VAR 
2. Create a Repurpose trim action

_Expected_: trim increment = 1%
_Actual_: trim increment = 0.1% 

Unfortunately this makes the feature unusable in practice, which means I cannot emulate a feature that is possible in OpenTX.

**X20S, Ethos 1.5.2**

![2024-03-24_161237a](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/1f083dff-26e2-4217-8fae-31cb00d1ed7f)

**Comment by Toffs** [comment]
Hi RC-SOAR,

Yes, I’ve mentioned this also in recent, related posts in the last months. The solution I’ve done is to create a second VAR which multiplies the first by x10.
I’ve got 8+ mixes duplicated (so 16), but now kinda given up as it’s getting a bit silly.

I believe that there’s a new calculations type feature coming to VAR mixes which can deal with the x10 factoring needed here. I’m not sure which release - would be great if it was 1.6.0 (hint hint!).

But there are various solutions to solve this, doesn’t have to be a multiplier. I personally don’t know why typical users would want 0.1 increment factors, and have suggested they make it whole integers as default, and an option to do 0.1 increments if so desired.

**Comment by RC-SOAR** [comment]
I confirm your workaround works. Though as you say the workaround using two VARs is untidy.  Just to summarise the shortcomings of using two VARs:

- _Both_ VARs must be edited in order to change the range of the master VAR. It's easy to forget.
- it requires an extra VAR
- the extra VAR messes up the VAR list if you like to restrict VARs to genuine configuration parameters

So yes, please can we have a scaling facility!

**Comment by bsongis-frsky** [comment]
Why 1% and not 0.5% or 0.1%?
What people needing fine steps will say?

**Comment by bsongis-frsky** [comment]
Perhaps a "Decimals" setting would help you?
If Decimals = 0 then the trim step will be 1%

**Comment by RC-SOAR** [comment]
For me, yes, a 'decimals' setting would provide more flexibility.  I presume this will apply to all the VAR parameters (range, current value etc.)? For others, maybe a choice of step would be even better.

Some background - I am trying to emulate the OpenTX 'AdjustGV' special function, where a trim can be repurposed (according to a condition) so that it binds to a GV. With the OTX solution, the trim/GV steps are 1%, which is perfect for my application.

**Comment by Toffs** [comment]
> Why 1% and not 0.5% or 0.1%? What people needing fine steps will say?

Well, I think the proposal is for 200 values range; that’s quite a lot.  The current 2000 values is a bit mad, I can’t see why someone would really need that.

**Comment by lthole** [comment]
Why have different approach here? Since it is a trim, the normal trim parameters e.g. Step would be more consistent.

**Comment by Toffs** [comment]
Would you mind clarifying a little please.
Are you suggesting in the custom trim mix, utilising the ‘coarse, medium, fine, custom’ trim step functions to alter the step increase magnitude?

So keeping the 2000 values, but increasing the step from +/- 0.1 (call that fine), to +/- 1 (medium), or +/- 5 (coarse), and a custom value so the operator can specifically define the step magnitude.

**Comment by lthole** [comment]
Exactly. The Step options would give more flexibility than decimal decades.

**Comment by Toffs** [comment]
Great. Though probably coarse should be +/- 10 thinking about it…

What does our superstar Bertrand think.  Is this  more complicated to achieve, or perhaps it might conflict with other functionality?

**Comment by bsongis-frsky** [comment]
I do like the solution found for #3724
Perhaps it's possible to apply something similar here, need a night + coffee to be sure

**Comment by lthole** [comment]
One possibility might be to add extra trims which are then called up by the repurposing function in the Var. 

I tried it with an extra trim set to coarse but the step size remained 0.1% so some changes would be needed.

**Comment by bsongis-frsky** [comment]
Perhaps this solution well make everybody happy?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/97a7ab16-ce93-4963-ad30-a4da5f368145)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/f0a0e89a-64bc-4457-a8a7-d8c7a628ba03)

**Comment by lthole** [comment]
Works for me!

**Comment by RC-SOAR** [comment]
That looks cool! My only query is what happens if the range limits are not a multiple of the trim step. It's important that a given trim position always returns the same value before/after a limit is reached.

**Comment by bsongis-frsky** [comment]
Thanks for the reminder.

Var = Max ...
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6e99164a-2c26-4681-9eed-c6794bcb8d14)

Remove one step ...
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4711ab78-e95e-468e-8bd7-1af722943dc1)

Var = min ...
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/f01f19f0-6255-4d5b-8473-03d44ef04651)

Add one step ...
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/19ab851a-d066-4ffa-8513-39811ae8af38)

**Comment by RC-SOAR** [comment]
This is so cool! Many thanks for your hard work.

**Comment by Toffs** [comment]
Superb!  Thank you

**Comment by lthole** [comment]
1.5.5 nightly15 mar 30 18:00

The Step defaulted to 1.0 which is great. However, I get 'Max reached' and 'Trim centre' and 'Min reached' alerts almost immediately even when nowhere near the max or min.

**Comment by bsongis-frsky** [comment]
Would you paste your model here? I cannot reproduce it!
Perhaps you have several "Repurpose" and you didn't notice one reaches the min / max / center?

**Comment by lthole** [comment]
I have 4 logic switches Adaptivept2 - Adaptivept5 breaking flap travel into bands. The these 4 logic switches enable 4 Vars VAdjPt2 - VAdjPt5 to repurpose the throttle trim to adjust 4 points on the CrowComp curve.

Even though Adaptivept2 overlaps with Adaptivept3 and Adaptivept3 overlaps with Adaptivept4, during testing I made sure that the LSW's were not overlapped.

On the Vars home screen i checked the values and only 1 Var was changing at a time.

In flight two points can be adjusted simultaneously when the flap stick is in the middle between 2 points.

[ng 2m.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14815186/ng.2m.bin.zip)

**Comment by lthole** [comment]
Please note that the motor control (right slider) must be at -100 so that Power flight mode is not enabled. Landing mode becomes active when you pull the flap stick (throttle stick).
Edit: slider must be at -100

**Comment by lthole** [comment]
The problem may be due to a conversion issue.

I programmed the below example from scratch in 1.5.5 nightly15 mar 30 18:00, and it does not exhibit the issue. I have also attached the documentation, it is the new How To section in the upcoming manual.

[compcurveeg.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14835091/compcurveeg.bin.zip)

[[EN] X20 and Ethos User Manual_How To 10_rev2.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14835099/EN.X20.and.Ethos.User.Manual_How.To.10_rev2.pdf)

**Comment by bsongis-frsky** [comment]
So, do you have a model where you can replicate this problem?

**Comment by Toffs** [comment]
I tired the nightly last night and it works a treat for me. The Max/Centre/Min all good, though I’m starting out with near clean/fresh model so not much to convert from previous.

Thanks again for the work, really appreciate it :)

**Comment by lthole** [comment]
Yes the Ng 2m model I uploaded 3 days ago. 

Note right slider (motor) must be at -100 to avoid flight mode Power, or just disable Power FM. The flap stick (thr stick) is mapped to 4 LSW which enable 4 Var with repurposed thr trim. Described in the document I uploaded with the working model.

**Comment by lthole** [comment]
I just tried deleting the 4 repurposing VARs, and created a new one. The problem remains.

**Comment by lthole** [comment]
On my other radio X20, also on the same 1.5.5 nightly, I took an earlier version of the Ng 2m model without the repurposed VARs, and added just one repurposed Var. It has the same problem with min/max/center alerts. 

So this one did not have converted repurposed VARs. But obviously the model was updated to 1.5.5.

**Comment by lthole** [comment]
If I repurpose the Elevator trim, the Ng 2m model works as expected. Must have something to do with throttle?

**Comment by lthole** [comment]
I have located the problem: I had an extra trim defined using RVU and RVD to adjust motor compensation. The repurposed throttle trim does not disable this extra trim, only the standard throttle trim.
