### ISSUE TITLE
Feature request: Lua. DrawTriangle

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#3697]
Please add DrawTriangle and DrawFilledTriangle to Ethos Lua API. 
Thank you.

**Comment by bsongis-frsky** [comment]
`lcd.drawTriangle(...)` and `lcd.drawFilledTriangle(...)` implemented, with full transparency support

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1dbf71c0-0979-4f9c-9e29-abebca750f93)

**Comment by i3dm** [comment]
Thank you! Does it relay on coordinates or size and angle?

**Comment by bsongis-frsky** [comment]
```cpp
    /**
     * @brief Draw a triangle
     * @since 1.5.5
     * @param x1 (number): X1 coordinate
     * @param y1 (number): Y1 coordinate
     * @param x2 (number): X2 coordinate
     * @param y2 (number): Y2 coordinate
     * @param x3 (number): X3 coordinate
     * @param y3 (number): Y3 coordinate
     * @return None
     */
    LUA_FUNC(drawTriangle);

    /**
     * @brief Draw a filled triangle
     * @since 1.5.5
     * @param x1 (number): X1 coordinate
     * @param y1 (number): Y1 coordinate
     * @param x2 (number): X2 coordinate
     * @param y2 (number): Y2 coordinate
     * @param x3 (number): X3 coordinate
     * @param y3 (number): Y3 coordinate
     * @return None
     */
    LUA_FUNC(drawFilledTriangle);
```

**Comment by bsongis-frsky** [comment]
Non regression test added with `setClipping(...)` + `drawTriangle(...)` + `drawFilledTriangle(...)`

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/925aec11-4975-4ef6-9d89-2ab4ccf12ac8)
