### ISSUE TITLE
New Model Wizard - order of surfaces

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#3698]
Hi

i created a new model 2 aileron, 2 flap, VTail. In the next wizard screen I changed throttle to ch7 and put elev2 on ch3. All others were changed on channel down

now the mixes are not in the right order (surfaces left to right in flight direction). Eg Vtail Outputs corrected so elevator works, now I have to put in -50 as weight
Ailerons move correctly but now differential works reversed (I need to reduce upward travel in mixer screen so that ailerons move less down)

Demonstration:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42022027/e74b29f3-9d4d-4555-8d34-cdae5629c76e)

here the red line is the first channel (I assume, because when I set one channel, the red line stays) and its not inverted. 
But following the channel order it should be, because stick left goes negative, but the left aileron needs to move up for a left bank. The same applies to the V-mix

**Comment by bsongis-frsky** [comment]
Output1 must be the right aileron.
I will take the idea from your other issue and it will be named "Aileron Right" or something like that

**Comment by jasc76** [comment]
imho this is all a bit mixed.
The 'usual' order is from left to right in flight direction. An this is also the rule for SRX receivers when connecting the servos. 
I would strongly vote against a change of this rule because its just confusing :-( Ok I get old .... 
If in the second part of the model wizard its clearly stated like Aileron right, Aileron Left and so on, well then its at least manageble.

**Comment by bsongis-frsky** [comment]
It is not possible to change the rule without breaking all existing models, it is too dangerous!
Yes the names should be more explicit and this is the subject of your other issue

**Comment by jasc76** [comment]
Sorry to come back to this....
I dont think this breaks anything ! 
My focus is the new model wizard or in fact the "create new mix" templates. By changing these (aileron, V-Tail mixes) to obey the left to right rule, existing models are not broken.
