### ISSUE TITLE
Invalid model data after upgrade

### ISSUE THREAD

**Issue by alesstimec** [FrSkyRC/ETHOS-Feedback-Community#37]
After upgrade from 0.0.17 to 1.0.1 i was faced with the dreadful "Invalid model data" message and asked to redo all my model configurations.

Is there a plan to fix this in the future? Will firmware upgrades be less painful (model compatibility, an app to backup/restore models)?

Best regards,
   Ales

**Comment by bsongis-frsky** [comment]
We implement conversions from now. No conversion from unstable releases.
