### ISSUE TITLE
Allow Calculated Sensor value

### ISSUE THREAD

**Issue by commsart** [FrSkyRC/ETHOS-Feedback-Community#370]
Allow Calculated logical sensors for example Lowest cell voltage from the multi cell sensor.

**Comment by islandflight** [comment]
Please see #4  and #197. The minimum cell voltage displays the minimum total cell voltage anywhere is a big that does not display the minimum for all the cells. I think they are working on a telemetry update many issues to address

**Comment by Nicholas-Luoyi** [comment]
Please see #377 for details.
