### ISSUE TITLE
Mixer Screen - Explain the colors

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#3700]
Just a little thing

In the mixer screen there is no way to tell which channel is which color :-) Maybe add a little color item in the list of output channels or smth

**Comment by bsongis-frsky** [comment]
One colour per channel? To be chosen in Model / Outputs?

**Comment by jasc76** [comment]
No, I mean in the mixer edit page. 
You have no clue which channel has which color in the curve display. 
Maybe smth like this could be done
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42022027/b16af461-dc87-4b22-ac56-0e1c4f7c4415)

Or you change the color of the channel text "Output 1" in orange, "Output 2" in red an so on

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5baba145-9790-4e14-87c4-f61724e92ca8)
