### ISSUE TITLE
suite 1.5.3: lua debug window shows corrupted output

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3701]
Hi,

at first:

MUCH THANKS to Nicholas-Luoyi for implementing this functionality,
and
for 1.5.3 USB improvements !

Even my older notebook by now is able to switch over the tx between the different usb modes

well done!

However,
the suite lua-debug-window will not output all of the data/text which was send from the tx.

it's like putty would run with wrong speed or is not able to "cache" a larger text stream

example:
this is was putty will show:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/bd00635a-2fb2-4a3f-b11b-dd39e32fe3c2)

and this is was suite shows
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/5b0cef0d-20ae-44f6-8899-682d9a41f149)

.. a lot of lines & characters are suppressed

Putty was set to 115.2 kBaud
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/fe33af0d-7093-4000-8275-0bef10cd0e77)

thanks & regards

Udo

**Comment by Nicholas-Luoyi** [comment]
Is it possible that you share your lua script with all the traces open?

**Comment by strgaltdel** [comment]
Hi Nicholas,
sorry for the delay.

the widget is "under construction" and I needed some time to make it "minimally applicable" for others
(still under development)...

the widget requires some model settings (SF's / Vars)
i have attached a model file so you can start without "handling issues"

Use this model template and start with the SA and SD switches at -100% 

If you set SD to the middle position, you will enter the so-called "super mode" GVedit
this generates several debug outputs

if you remain in this mode, you can switch SA to several positions, which generates further outputs

If you switch SD to +100%, the "super mode" changes to Curve-edit

So if you play around with these switches, the mentioned problem should appear in the suite
I used putty to crosscheck the output

thanks & regards
Udo

[un_gvInflight.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14803082/un_gvInflight.zip)

**Comment by Nicholas-Luoyi** [comment]
Thanks. I just turn to this one
