### ISSUE TITLE
KAVAN V20

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#3702]
Hello everyone,

what does the KAVAN V20 show as FIWMWARE under SYSTEM/INFO?
Ethos - V20 or Ethos - X20?
or if I query the board via LUA?
sys = system.getVersion()
print("Borad:"..sys.board)

Greetings Benno

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d1e2c1b6-4340-4c98-94c5-55a3c75167a9)

```
lcdWidth        800
simulation      true
lcdHeight       480
serial  8799439955AA
revision        3
board   V20
suffix
version 1.5.3
minor   5
major   1
```
