### ISSUE TITLE
Cannot get PixHawk Telemetry to pass through TD R10 to X20S

### ISSUE THREAD

**Issue by rscarawa** [FrSkyRC/ETHOS-Feedback-Community#3707]
I cannot get Pixhawk telemetry, passed via Teensy translator, to transmit back to X20S via TD R10. The Rx is running 1.0.12 firmware.  My setup has a Teensy Translator connected to Serial 2 with option of Mavlink. I have SPort selected on pin CH9 to receive the signal. When I setup telemetry on the radio, it only discovers the telemetry of the Rx.  As a test, I flashed my old X8R with the latest firmware and bound it to the X20S. The Rx worked properly and also passed the Pixhawk telemetry back to the Tx as expected. Should the TD R10 be able to receive the same telemetry signals as the X8R? If so, then there is an issue with the 1.0.12 firmware on the TD R10. Any help on this issue would be appreciated.

**Comment by mawzthefinn** [comment]
There's two possible issues here.

1. You connected telemetry to the 4-pin header. On the TD R10 that's an Upgrade and AIN port only, you need to map a Channel Port to S.Port and connect there.

2. The Teensy translator is not following the S.Port spec closely enough for timing. The receivers with the ability to map S.Port & FBus to a Channel Port all require very close adherence to the S.Port spec for timing to work. Older receivers are looser and will allow out of spec devices to work. The TD R10 is one of the receivers which require close spec adherence.
