### ISSUE TITLE
X20 pro on 1.5.3 and Ethos suite 1.5.2 module manager not working

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#3708]
Ethos suite 1.5.2 module manager not working will not up date x20pro  td-isrm  module

**Comment by Nicholas-Luoyi** [comment]
Would you please try Suite 1.5.3?

**Comment by yak-54** [comment]
just did update to 1.5.3 the same will  module manger will not update module
and i ran it as admin

**Comment by yak-54** [comment]
looks like its an network access issue
