### ISSUE TITLE
No callouts for external Modul 1.5.3

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3712]
Since 1.5.3 there are no longer any colouts for the external module (multiprotocol) such as “Telemetry lost” or “rssi low warning”.  My system language is EN and the audio files for the system are available on the internal memory.  
For the internal module everything works.  

-X20pro 
-1.5.3 
- Multiprotocol (ACCSTX2)
- Language en

**Comment by rburrow87** [comment]
I also noticed this yesterday evening with X18SE 1.5.3 FCC and ExpressLRS external module. It does not announce "Telemetry lost" when unplugging the aircraft like it used to.

**Comment by WhiskeyGolf** [comment]
Is there anything new on this topic?  
I think that's a critical one.  
Thank you

**Comment by WhiskeyGolf** [comment]
?

**Comment by bsongis-frsky** [comment]
@rburrow87 Are you sure that it worked correctly before 1.5.3 on ELRS / CROSSFIRE?

@WhiskeyGolf Agreed that it has been changed for Multimodule

**Comment by rburrow87** [comment]
I know I used to hear it say telemetry lost after disconnecting the battery. But it has been a while since I posted that, so I am not 100% certain if it worked in 1.5.2 or if I was thinking of 1.4.x.

**Comment by bsongis-frsky** [comment]
Fixed. I have tested it with ELRS, is it possible that you check the next nightlies @rburrow87 @WhiskeyGolf

**Comment by WhiskeyGolf** [comment]
It seems to be working now.  However, it is very slow.  Sonsor lost callouts in the event of short voltage drops are ignored, even though the time is set to 1s.  This is not the case with the internal module.

**Comment by bsongis-frsky** [comment]
Sensor lost ? Or Low voltage?
Sensor lost has a configurable timeout, default timeout is 10s

**Comment by WhiskeyGolf** [comment]
I mean the sensor loss warning.  The warning is just as slow as the Telemetrylost warning, even though the Sensorlost warning is set to 1s.
Thank You
