### ISSUE TITLE
Problem with Global Special Functions

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#3714]
Tandem X18S
Ethos 1.5.3. Spanish

When an SE includes a "Show value" that cannot be global, the system automatically removes the Global condition.
 
This worked in version 5.1.2.

![FS Problem 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/ec9e27d1-5bbb-46e9-a76b-0bb7b1bd401b)
![FS Problem 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/89105997-72b8-483e-8f3f-384e79b21a46)

**Comment by bsongis-frsky** [comment]
It is a feature :)
If something cannot be global in a Function, then the whole function cannot be global!

**Comment by afdofdez** [comment]
In version 1.5.2.  if it worked.

**Comment by bsongis-frsky** [comment]
I think in 1.5.2 your play function played the sensor at a given position, not always the VFR sensor.
Which is a bug and it has been fixed in 1.5.3
