### ISSUE TITLE
New Norwegian translation Ethos + Ethos Suite

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#3715]
Please find the latest Norwegian translation-files attached :-)
[no.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14761735/no.csv)
[no.json](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14761737/no.json)

**Comment by bsongis-frsky** [comment]
Are you sure that units for BYTE / KB / MB are good? I think you used the "bit" unit, not "byte"

**Comment by bsongis-frsky** [comment]
Please check the translations in the next 1.5.5 nightlies
