### ISSUE TITLE
1.5.3 Offset action in free mix produces unexpected results (works in 1.5.2)

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3718]
I think this may be a critical bug introduced in 1.5.3.

To reproduce:

1. Create Free mix 
2. Set source = Minimum
3. Set offset = Maximum

Expected: Output = 0
Actual: Output = -90.2%

The same test in 1.5.2 works as expected.

**1.5.3 X20**

This is the test in 1.5.3 - incorrect!
![screenshot-2024-03-27-20401](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/09a25fe7-a812-4de7-9819-b256fe980bc5)

In 1.5.2 - correct
![2024-03-26_232538](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/3eba1ea4-1e18-4a90-8888-c90133c0a06b)

**Comment by bsongis-frsky** [comment]
Will be fixed in the next nightlies
