### ISSUE TITLE
[IMPROVMENT] Special fonction

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#372]
Will it be possible to add the "REPLACE" in the special function ?
Thanks

**Comment by jreis1** [comment]
I believe you meant “overwrite” !? I’ve also missed this. 

+1

**Comment by Hobby4life** [comment]
I gues he means "Override CHx"

I asked the same question earlier, now I am getting more used to Ethos, using a mixer that "replaces" the channel to a fixed value makes more sense after all.

#324

**Comment by aviat40** [comment]
Yes "Override CHx" with a Value

**Comment by Hobby4life** [comment]
As bertrand said in #324, Use a mixer for that with Replace function. Does exactly the same.

**Comment by aviat40** [comment]
OK but ETHOS want to be easier for common people. 
So a special function as THROTTLE CUT could be a very good improvment

**Comment by Hobby4life** [comment]
There is throttle Cut and Throttle hold in the throttle mixer. take a closer look.

Splitting out things, and give multiple options like in OpenTX doesnt always makes things easier.

**Comment by aviat40** [comment]
Oh!!!! I missed this one... so forget my message ;-)

**Comment by NALK85** [comment]
> There is throttle Cut and Throttle hold in the throttle mixer. take a closer look.
> 
> Splitting out things, and give multiple options like in OpenTX doesnt always makes things easier.

However not if the throttle is setup for an boot! 
Where the throttle is also used for forward (0-100) and reverse (0 - minus 100) which is activated by a switch.
Asfar as i know that is not possible/easy in Ethos.
For the throttlecut the value 0 must replace the value of the motor Chanel.

Mayby someone can explain how to set it up

Regards, Nic
