### ISSUE TITLE
Ethos 1.5.3 LUA -  lcd.setClipping() missing

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#3720]
seems like 1.5.3 removed lua support for window clipping, the method setClipping() is no longer supported (in the docs as well)

this makes drawing lines inside a rectangle impossible thus forcing the use of a full lua line clipping algo

error reported by terminal:
field 'setClipping' is not callable (a nil value)

**Comment by bsongis-frsky** [comment]
oops, I didn't remember why I added this function!
it will be back in 1.5.4

**Comment by bsongis-frsky** [comment]
Restored in 1.5.4

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/47e11643-dddc-46ac-b6bd-b86647343eea)

**Comment by bsongis-frsky** [comment]
Would you check in nightlies tomorrow?

**Comment by bsongis-frsky** [comment]
Unless I pre-release 1.5.4 tonight

**Comment by bsongis-frsky** [comment]
Non regression test added
