### ISSUE TITLE
filtering on getSource

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#3721]
Please can the ability be added in to filter results on the getSource dialog.

For example.. show only 'telemetry' 

or only switches

etc..

**Comment by bsongis-frsky** [comment]
`form.addSensorField(...)` added, with an optional filterValue handler:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1949fea9-b6d1-4749-981f-d3e4253ac136)

**Comment by robthomson** [comment]
That was quick!

**Comment by Alex00101** [comment]
Thanks was very much looking forward for it!
