### ISSUE TITLE
Archer gyroscope

### ISSUE THREAD

**Issue by Andreax20s** [FrSkyRC/ETHOS-Feedback-Community#3722]
with the new ethos 1.5.0 updates onwards, should the lua scripts of the tandem x20s and the rx archer with gyroscope also be updated? because from the radio it doesn't allow me to enable stabilization or self check, channel inversion etc.etc. Help, I'm a beginner, thanks

**Comment by mawzthefinn** [comment]
The Lua scripts work fine in 1.5.0

Be sure you are using them directly from the System Menu and not Device Config->SxR, which still only supports the older SxR, R9 and Archer/Archer Pro receivers. 

If you have the old receivers (SxR or Archer/Archer Pro, but not TD, TW or Archer Plus), use Device Config->SxR.

**Comment by Andreax20s** [comment]
thanks I will try

**Comment by Andreax20s** [comment]
do they need to be downloaded separately, or are they included in the update via ethos suite?

**Comment by mawzthefinn** [comment]
They are a separate download from FrSky-rc.com
