### ISSUE TITLE
NFC remote switch prompt

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#3723]
Hello,

i think its absolutely necessary for the NFC remote switch option to have a prompt when commanding power OFF to the model, like a pop up that says "are you sure you want to switch OFF the model?" with a Yes/No option.

thank you.

**Comment by Dsrenger** [comment]
Just program something by yourself.

I have logical switch setup where I need to hold a button for 5 seconds before it goes of. Like the transmitter itself has.

Or use a mechanical safety switch where you have to lift a ring before you can switch it.

Fix your NFC channel as long as you motor safety switch is off.

Just be creative. There are tons of ways to do it.

Don't make me acknowledge any message.
You don't have to acknowledge a message before the transmitter itself goes of.

These kind of messages are just annoying.

**Comment by bsongis-frsky** [comment]
We have worked on a new Logic Switch which raises a popup before changing its state.
It's currently in PR and will come when ready and tested.

**Comment by Dsrenger** [comment]
Ok, that's fine

As long as it is not mandatory for the NFC switch.

**Comment by bsongis-frsky** [comment]
No it's just some special Logic Switch which interacts with the user with a Confirmation Dialog. Which is not simple to implement, that's why it's still in PR state.

**Comment by raydars** [comment]
> Hello,
> 
> i think its absolutely necessary for the NFC remote switch option to have a prompt when commanding power OFF to the model, like a pop up that says "are you sure you want to switch OFF the model?" with a Yes/No option.
> 
> thank you.

I agree,  a two step verification should be required to switch a model on or off remotely.

**Comment by Toffs** [comment]
> No it's just some special Logic Switch which interacts with the user with a Confirmation Dialog. Which is not simple to implement, that's why it's still in PR state.

Superb, that’ll help in all sorts of situations including NFC switch off’s.
Nice one - brilliant idea!

**Comment by i3dm** [comment]
> No it's just some special Logic Switch which interacts with the user with a Confirmation Dialog. Which is not simple to implement, that's why it's still in PR state.

Thats great news. Thank you.

**Comment by bsongis-frsky** [comment]
This feature has been introduced in 1.5.8
