### ISSUE TITLE
1.5.3 when used as a source, trims have a range of +/-25% instead of +/-100% (new issue)

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3724]
This is a new problem in 1.5.3 (it works as expected in 1.5.2 and previous versions)

To reproduce
1. Create a new setup of type 'Other'
2. Create a Free mix, source=Rudder trim, outout=CH1

_Expected_: CH1 should swing between -100% and +100% as the trims are moved to their limits.
_Actual_: CH1 swings between -25% and +25%

Unfortunately, this breaks all my sailplane templates. In both OTX and previous versions of Ethos, trims have a range of +/-100% when used as a mixer source.

**X20S 1.5.3**

**Comment by bsongis-frsky** [comment]
Done on purpose to fix #3673 and keep consistency!

**Comment by RC-SOAR** [comment]
This is really a step backwards! 

It's going to break every setup which uses a trim as the source of a free mix... and it'll also be a problem going forward because +/-100% is needed to use a trim as a regular control (or as an adjuster).

The issue was reported to me by a user of my F3F templates who - after flashing 1.5.3 - had sufficient elevator compensation when using crow brakes (the trim is used to set the weight).  The new behaviour caused him problems when landing the model.  

Trying to be constructive... is there any way #3673 could be implemented without breaking this behaviour?

**Comment by spoke2570** [comment]
I can set the range and step for my trims in the trims section Of 1.5.3. They can still handle -100% to +100% at resolution of 0.1%.

**Comment by RC-SOAR** [comment]
Understood, and the new flexibility in the Trims section is welcome... 

However, _when used as the source of a mix_, a trim should still supply a +/- 100% swing. This has always been the case and allows the trim to be used as a regular control.

I don't think the two behaviours are incompatible.

**Comment by spoke2570** [comment]
![IMG_0649](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/30901925-8220-46ad-9116-942c70adc790)
![IMG_0650](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/2a499056-54c0-4ed1-b2ab-f6d7902aac73)

**Comment by spoke2570** [comment]
I don't think the two are incompatible either. In this instance I like letting the user be deliberate about if the tab will be a general input or a trim. Certainly for those who use the same tab for both then the 100% range is the way and scaling for the 25% trim range.

**Comment by RC-SOAR** [comment]
Sure, you can do a lot in the Trims section, that's not the issue. 

To summarise:

1.5.**2**: FreeMix, source = TrimRudder ==> **output swing = +/-100%** 
1.5.**3**: FreeMix, source = TrimRudder ==> **output swing = Trim range**

Since the default trim range is 25%, existing setups which make use of the 1.5.2 behaviour will break in 1.5.3 (as has happened). 

I cannot see a workaround within 1.5.3. You may want to use a trim as a regular trim (with 25% swing) in one flight mode, and as a mixer input in another with traditional 100% swing. And even if there is a workaround, it doesn't help people who aren't aware of the change.

The solution I would suggest is to restore the 1.5.2 behaviour _when trims are used as sources_, while keeping the new features (in the Trims menu) when trims are used as regular trims.

**Comment by spoke2570** [comment]
Frankly, I consider all my birds broken with every update, and mostly they are. Usually it is something like this that I find out about when something doesn't happen or my flight modes that have been rock solid forever now are trick. 

I think the trim in some flight mode can be handled by a free mix, trim as input and 25% scalar. Basically how I handled them when free mixes were the ticket for all the controls. 

or the tab could drive a Var line that handles the 100% range while leaving the default 25% range on the trim itself. 

Ethos automatically deciding that the input version of it is 100% would be easiest for the user.

**Comment by RC-SOAR** [comment]
IMO the devs have done a great job with backwards compatibility, this is the exception. 

Compatibility is important because things working in unexpected ways can cause incidents. Sure you and I can probably work around these issues, but not everyone who can be bothered, or should be bothered.

From a purely selfish perspective, I don't like having to post alerts to my users. While I love the features in 1.5, it's a real pain having to amend the glider templates and post alerts to [my support page](https://rc-soar.com/ethos/support/). It means less time developing templates (and flying!).

**Comment by spoke2570** [comment]
Ya, power to you for that page! I still have planes on OTx that I haven't had time to move  over.

**Comment by subhrabose** [comment]
Backward compatibility is important, especially for complex models.. and Ethos developers have done a fantastic job of providing backward compatibility while bringing new features into the OS - my birds are not broken from one version to the next and gives me confidence to fly without testing all the features across all models when a new version is released. A lot of the glider flyers would not switch to Ethos without Mike's (RC-SOAR) templates. My two cents will be to maintain the backward compatibility in this case without compromising the implementation for  #3673.

**Comment by bsongis-frsky** [comment]
I think that we should keep by default the trims settings here: if a trim has a 25% range it should keep the 25% range.

Now we have the compatibility problem and here is my proposal:

1) Add a contextual source option: if a source is a trim, we will get a new option "Full range" (or a better name if you have one)

2) Add a conversion. All models from 1.5.3 and before will have automatically this option set

This way Mike's templates will work out of the box and we will keep compatibility.

**Comment by strgaltdel** [comment]
So far, I have considered trimmers in three independent "categories"

1)
Use as a classic trimmer for fine adjustment of control elements

In this case, the travel is limited to e.g. 25%.
The anchor point is the predefined use in existing mixers


2)
Use as an input entity,
Here I would like to use a physical trim lever as an additional input analogous to slider / pots etc.

In this case, the travel should be able to reach +-100%, and may be limited by user config

Anchor point of the call via categories to specify a source


3)
not relevant here,
Use as (1)-0-(1) switch 


in this respect I would also, and especially for reasons of downward compatibility,
vote for the "old" procedure

Greetings
Udo

EDIT:
Ah,
i do see, 
"Add a contextual source option: if a source is a trim, we will get a new option "Full range""
seems to be congruent

**Comment by bsongis-frsky** [comment]
I think that we should keep by default the trims settings here: if a trim has a 25% range it should keep the 25% range.

Now we have the compatibility problem and here is my proposal:

1) Add a contextual source option: if a source is a trim, we will get a new option "Full range" (or a better name if you have one)

2) Add a conversion. All models from 1.5.3 and before will have automatically this option set

This way Mike's templates will work out of the box and we will keep compatibility.

**Comment by RC-SOAR** [comment]
The proposal for a contextual full range option sounds good! Thanks for quick response.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/785f2404-38d0-4eff-9c07-6372854a5908)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/adc1728c-f959-472d-b367-5325d9049b1a)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/48988b95-abe4-4c1f-8cfe-a588de4321d9)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b2dfcd75-27c4-4e85-97bd-34d16f1e94fa)

**Comment by RC-SOAR** [comment]
Looks good - I think the meaning is clear.

**Comment by subhrabose** [comment]
Excellent solution!

**Comment by spoke2570** [comment]
Love it!

**Comment by bsongis-frsky** [comment]
Regression test added:
- old 1.4.X setup loaded ("Full Range" option applied to the Trim)
- check that Elevator Trim on Max gives a value of 100%
