### ISSUE TITLE
Not enough memory on Log Viewer

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3725]
When looking through logs with the log viewer, it showed me that the memory was full.

**Comment by WhiskeyGolf** [comment]
![Uploading 42D03D16-9246-4FF6-8041-0CAC54C39DC0.jpeg…]()

**Comment by WhiskeyGolf** [comment]
![3036775B-5C54-4E5F-AADB-8923D50AF402](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/b426de66-13eb-434f-b47d-e5e5787d02f9)

**Comment by WhiskeyGolf** [comment]
![9FC3F2BA-F5AF-451A-BDEE-F9CBC3537217](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/a3c3b5ea-f42b-448f-bf15-d85c5d6ecf83)

**Comment by WhiskeyGolf** [comment]
ETHOS 1.5.3 
X20pro

**Comment by bsongis-frsky** [comment]
Ethos needs to keep some available RAM for its own useage, it cannot give everything to the Logs Viewer!

**Comment by WhiskeyGolf** [comment]
Okay, thank you for the answer.  Where is the limit?

**Comment by bsongis-frsky** [comment]
The limit comes from the SDRam
We could display it somewhere in System / Information, when we find some spare time :)

**Comment by bsongis-frsky** [comment]
Also don't forget that the Xicoy widget produces many errors (with memory leak on each error).
So perhaps it will be better with 1.5.4 as the memory leaks are gone
