### ISSUE TITLE
No response from reciver at 200/500mW

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3726]
-X20pro ISRM 1.1.1.3
-Ethos 1.5.3 eu 
-TD SR10 1.0.11 LBT

If you increase the transmission power of the 900 module from 25mW to 200mW or 500mW, you can no longer access the options menu of the receiver.  Not even after rebinding. If you switch back to 25mW it works again.  Is it normal that the 900 Rssi drops to 0dB when changing the power and you have to rebind every time?

**Comment by WhiskeyGolf** [comment]
![F7E72C4A-E452-48D8-9138-2639F2C15A1B](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/ff913091-6b8b-4978-bdee-4629401e7783)

**Comment by mgsanna** [comment]
It's a limitation of Telemetry on EU-LBT firmware, you can only use 25mW, it's not a bug. it's european law 
The transmission of rf link is working but no telemetry
I suggest you to use the Flex Firmware that allow you to use fullrange telemetry and increase output power of 868 mhz link without issue

**Comment by WhiskeyGolf** [comment]
Yes, I am aware of these circumstances (Long OpenTX user).  I can't currently use Flex firmware because the ACCST receivers don't work (other issue).  However, it should still be possible to continue configuring the receiver over the 2.4g band.  No matter how 900m is set.

**Comment by mawzthefinn** [comment]
> It's a limitation of Telemetry on EU-LBT firmware, you can only use 25mW, it's not a bug. it's european law The transmission of rf link is working but no telemetry I suggest you to use the Flex Firmware that allow you to use fullrange telemetry and increase output power of 868 mhz link without issue

Latest firmware for TD should force telemetry over to 2.4G for 900M power levels over 25mW, sidestepping this issue. That's the primary change in 1.0.11. Looks like it's not working 100%
