### ISSUE TITLE
ORDRE DES MODELES

### ISSUE THREAD

**Issue by KLOSTRO** [FrSkyRC/ETHOS-Feedback-Community#3729]
Pour éviter d’avoir la liste de mes modèles dans l’ordre alphabétique, ce serait bien comme avec OPENT TX et COMPANION de pouvoir sélectionner l’ordre de mes avions par exemple car je me sers plus souvent du moele M.... que du modéle C.....

**Comment by bsongis-frsky** [comment]
Duplicate of #3060
