### ISSUE TITLE
Sensor Scaling issue on X18

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#3730]
Wil developing this widget we have noticed a strange issue on the X18 when processing telemetry data.

https://github.com/robthomson/rf2status

On and around line 1680 we have had to do the maths differently for the X18.  For no good reason it seems to deliver the value on a different scale to the X20.

**Comment by bsongis-frsky** [comment]
I don't understand how it is possible!

**Comment by bsongis-frsky** [comment]
Pong
https://github.com/robthomson/rf2status/issues/1

**Comment by robthomson** [comment]
Using the changes suggested has resulted in this issue being resolved.
