### ISSUE TITLE
Ethos Suite 1.5.3 hangs on Windows PC

### ISSUE THREAD

**Issue by gflash01** [FrSkyRC/ETHOS-Feedback-Community#3732]
Windows update seems to have caused an issue for Ethos.  I had initially used v 1.5.2 without issue . . . .  yesterday it hung at startup with a blue circle and the top of the screen reported "not responding".  I uninstalled v 1.5.2 and installed v 1.5.3.  I am having the same issue.  I have uninstalled, rebooted and reinstalled with no change in behavior. Here is a screenshot of the system:

![Threadripper](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165298930/9915f30f-167a-43e5-8ed2-28b259f8e95b)

I am working around this by using a laptop for now, but this is my main computer.

**Comment by gflash01** [comment]
![Ethos hang](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165298930/20250be2-401f-48d8-8868-bca9799649cd)

**Comment by gflash01** [comment]
![Ethos not responding](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165298930/2d79e3e9-943e-4518-9f73-c5c208779bf7)

**Comment by gflash01** [comment]
FWIW I have 4 windows 11 machines , , , Ethos runs OK on three of them and will not run on the 4th.  The three that Ethos does run OK on  are all OS build 22631.3296 and Windows Experience 22687.1000.0.  The one it does not work on is OS build 22631.3374 and Windows Experience 22688.1000.0

**Comment by gflash01** [comment]
Also, I upgraded to 1.5.3 because 1.5.2 was also hanging.

**Comment by yak-54** [comment]
look i had this issue before all it was i had to run it as Admin
 all it is windows will not let it wright temp files on the system 
and some times it was virus software as well stopping from writing to the drive

i may be wrong but it fixed my issues

**Comment by gflash01** [comment]
My other tower style PC did an update this afternoon, it is now at the same OS build and Windows Experience as the machine where Ethos refuses to run (Threadripper), but Ethos works on this pc (Family) So something else is at play.  I have tried disabling Windows Virus protection, but it did not change anything.

![Family PCb](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165298930/c1122d9d-1be4-41cc-997e-c5e89d8757a0)
![Family PCa](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165298930/88a98127-f735-45fc-9a4c-a25c373bf539)

**Comment by bsongis-frsky** [comment]
Title changed, it should be:
"Ethos Suite 1.5.3 hangs on Windows PC"
Right?

**Comment by gflash01** [comment]
Yes, that is correct.  I have new information.  After posting this, my second tower style Windows PC did a Windows update, and is now at the same OS Build and Windows Experience as the machine where I am seeing the issue.  But Ethos runs fine.  This second PC has all the Windows Security set to defaults. 

![Family PCa](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165298930/a9591dea-fc4b-4d35-81e7-a493319315dc)
![Family PCb](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165298930/025dc005-1648-4528-b866-488b23e97b3a)

**Comment by gflash01** [comment]
Yes.

**Comment by Nicholas-Luoyi** [comment]
I cannot reproduce on my Win11 VM..

**Comment by gflash01** [comment]
I do not believe it is related to the version of windows, I have 4 Windows 11 machines and it works OK on 3 of them.  It is obviously hung trying do something, there is a blue circle and the message "not responding" in the top of the window.  I don't know where to go from here.  Is there some kind of logging mode where I can capture what it is stuck on? It started happening with 1.5.2, I thought an upgrade to 1.5.3 would fix it.

**Comment by Nicholas-Luoyi** [comment]
[zadig-2.8.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14830427/zadig-2.8.zip)

The USB lib has been changed in 1.5.3. Would you please try installing WCID driver with Zadig before running Suite?

**Comment by gflash01** [comment]
That makes me nervous, my ASROCK mobo has a lot of USB ports.  How do I know which one is being used when I plug in the radio?

**Comment by salibaj2** [comment]
gflash,

I used USBDeview.

Great software for USB. You can get it from here: - https://usbdeview.me/

It solved me quite a lot of problems when working with microcontrollers that have USB.
