### ISSUE TITLE
ELRS fan threshold not working

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#3733]
Setting doesn't turn the cooling fan on/off wherever I set the value.
1.5.4 EU firmware

**Comment by bsongis-frsky** [comment]
Are you sure it's the right project for this issue?

**Comment by miggy1952** [comment]
Same Tx module turns on/off the fan properly in EdgeTX

**Comment by robthomson** [comment]
What version of ethos are you using?


This setting is not really controlled by ethos - by  rather by the module.

I do however wonder if 'model match' is resulting in different settings being used by the tx of swapping the module between radios?

Ether way.. Have tested this on my end on latest ethos versions and not seen the same issue?

**Comment by miggy1952** [comment]
Thanks for this. Using the very latest ETHOS and ELRS versions. I no longer own a EdgeTx transmitter but I will try it out again on somebody’s Tx. It is possible that the fan isn’t working on my HappyModel ELRS Tx module I suppose

**Comment by miggy1952** [comment]
Fan works fine , it was a fault on the Tx module
