### ISSUE TITLE
1.5.3:  offset in freemix wrong by factor 10.24 

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3734]
Hi,

one more 10.24 easteregg:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/d3707c9e-54a8-4596-94ca-2a2944f46f2b)

output wrong by factor app 10

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4c528532-7a77-4015-872c-acc7c538dd63)

**Comment by bsongis-frsky** [comment]
Related to #3718

**Comment by bsongis-frsky** [comment]
Non regression test added
