### ISSUE TITLE
1.5.3 update hung

### ISSUE THREAD

**Issue by mccue520** [FrSkyRC/ETHOS-Feedback-Community#3736]
going through the process to update firmware to 1.5.3 on X18S. Everything went fine until "time to switch firmware." Got a message that perhaps the bootloader doesn't support switching firmware and instructions on how to do it manually. 

1. disconnect USB cable
2. turn off bootloader (can't turn off the TX at this point other than pull the battery)

So I tried to update to a new bootloader but my TX won't turn on except in bootloader mode. Now stuck in that loop.

**Comment by bsongis-frsky** [comment]
Your bootloader is working. You cannot update it as it is running.
You should start your radio in bootloader mode and update the firmware.

**Comment by mccue520** [comment]
I went through the firmware update process. It gets to here (attachment) and then I am stuck. Firmware won't complete update, TX can't be turned on or off (except to start in bootloader mode). 
![hung up](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165354502/b1136e75-2ebf-4f32-9826-19e94f069d5d)
![hung up](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165354502/a401c437-8217-4c43-b02c-e814b14134eb)

**Comment by Nicholas-Luoyi** [comment]
You could manually download the X18S_Bootloader.zip in tag 1.4.15 and flash it with the DFU Flasher in Suite
