### ISSUE TITLE
Ethos 1.5.4. firmware Italian Translation Update.

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3738]
[it 2.i18n.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14803095/it.2.i18n.zip)

**Comment by bsongis-frsky** [comment]
Obviously it's not the right file!

**Comment by mgsanna** [comment]
Yes but the csv file has. Not the missing terms…. About direction in freemix

**Comment by mgsanna** [comment]
[it.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14806327/it.csv)
@bsongis-frsky must I open a new issue for the file?
