### ISSUE TITLE
Suite 1.5.3 - Mac OS 12.7.4 - Suite Quit Unexpectedly after Quit.

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3739]
>I updated to 1.5.4
>Quit suite (right click sidebar icon - select quit) - seems to quit normally sidebar icon goes away, CMD + Tab doesn't show the open app.
>Ejected drives (right click disc icon - select eject)
>Few seconds and the unexpected problem report. 

![Screen Shot 2024-03-29 at 7 46 59 AM](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/8ca7b2c7-d31f-4f8b-88d4-bb5fd10fe464)

[1.5.3 Problem Report.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14803854/1.5.3.Problem.Report.txt)

**Comment by ftc2629** [comment]
Yes, have the same issue. Mac Mini Intel I7, OSX Sonoma.

**Comment by Nicholas-Luoyi** [comment]
Cannot reproduce here. With different ways to quit the app. Command + Q or right click on the side bar...

**Comment by Nicholas-Luoyi** [comment]
Would you please try running and quitting Suite without radio connection?

**Comment by spoke2570** [comment]
Open Suite
Flip the Debug mode switch in settings.
Close the Suite window (click on red dot).
Close suite (select 'Close Suite' from Suite menu in header bar.)
Error returned with the swiftness

[OS12.7.4_close_Suite_problem.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14823440/OS12.7.4_close_Suite_problem.txt)

**Comment by spoke2570** [comment]
Ya we have 'close window'
a) click red dot 
b) select 'close window' from header bar

'hide window':
a) Select hide ETHOS Suite' from header menus 
b) Right click side bar tile select 'hide'.

'Minimise window':
a) click yellow dot.
b) select 'minimize' from header.

'Quit Suite":
a) CMD + Q
b) Select Quit Suite from header bar.
c) right click side bar tile and select 'quit'.
d) use force quit: (CMD + OPTION + ESC) select 'Ethos' from list.

like 36 possible combinations to close the program.

**Comment by ftc2629** [comment]
On my MAC it's now working.
With and without radio connection (radio on version 1.5.4)

**Comment by Nicholas-Luoyi** [comment]
> On my MAC it's now working. With and without radio connection (radio on version 1.5.4)

So what has been changed on your side?

**Comment by spoke2570** [comment]
Update radio to test version 1.5.5
(Radio now in Bootloader mode)
Eject drives via Suite
Quit Suite (CMD + Q)
ERROR pops..

[OS12.7.4_close_Suite_problem_1.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14837294/OS12.7.4_close_Suite_problem_1.txt)

**Comment by Nicholas-Luoyi** [comment]
> > On my MAC it's now working. With and without radio connection (radio on version 1.5.4)
> 
> So what has been changed on your side?

I was mentioning @ftc2629 because the situation seems to be changed on his Mac

**Comment by spoke2570** [comment]
Yes I was just placing another sys report as the error occurred with some different sequence.
