### ISSUE TITLE
Possible bug | feature request: throttle cut using LSW >> Override Channel

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#374]
**Goal:** With Archer GRX8 receiver, use Altitude (from telemetry) to set throttle cut (e.g., stop motor when reaching 120m of height). This is extremely used in Thermal Glider (e.g. F5J). 

**Used method:** as the special function 'override CH' is not available in Ethos (this would be the easiest way to achieve this goal), I've set a Logic Switch with X>120, being X the altitude value.  Then, in the throttle mixer, I've attributed the respective LSW to the throttle cut. To confirm, I have also added a "Special function" to play a track and have audible confirmation that the LSW is being triggered. 

**Outcome:**  when reaching the 120m of height, the LSW is triggered by playing the track mentioned above. However, the motor never stops i.e. throttle is never cut.  Nevertheless, if I manually reduce the throttle to '0' (-100%) above the defined altitude threshold (120m of height), and try to increase it right after the throttle is cut. 

**Request:** Please add 'override CH' to  special functions as this it would help in cases like this. 

ETHOS V1.0.7

**Comment by hrenz** [comment]
the gas mixer has 3 main funktions
with Gas gimble
switch for  Motor Safty OFF
switch for Motor FIX Value

there you can set a switch (a log Schwitch)  you need for Motor Fix value -100%

**Comment by Hobby4life** [comment]
You need Throttle Hold, not Cut

**Comment by Jornor68** [comment]
Change triggervalue to +100 for it to cut at any stickposition.

**Comment by jreis1** [comment]
> the gas mixer has 3 main funktions
> with Gas gimble
> switch for Motor Safty OFF
> switch for Motor FIX Value
> 
> there you can set a switch (a log Schwitch) you need for Motor Fix value -100%

Thanks. I'll have a look, although I dont find very intuitive to set a "Gas mixer" in a electric motor plane :/ but it seems it will do the trick.

**Comment by jreis1** [comment]
> You need Throttle Hold, not Cut
I believe this is it :) as it allows to set a specific value. I'll test it tomorrow
