### ISSUE TITLE
Calculating sensor rpm

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3741]
First of all, thank you for your tireless work.
In the forum, the problem arose that a speed controller was only outputting 1/10 of the speed. So this had to be multiplied by 10. To do this, I created a calculating sensor with the unit of measurement rpm. I realised that the range can only be set up to a maximum of 10000 rpm. But that is not enough. Is it possible to increase this value to 100000? 
Thank you
Yours sincerely, Wolfgang
![Berechnet](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/41a3ac47-b8cf-46db-9384-da020f594175)

**Comment by WhiskeyGolf** [comment]
I'm also having a problem with the Calculate Sensor.  You cannot set the range negative.  This makes the sensor unusable for using sources with the Vario.  So it would be good if the range was larger and it was possible to make it negative

**Comment by robthomson** [comment]
For no use a dirty trick

Create a second calculated sensor that calculates off the first calculated sensor
