### ISSUE TITLE
Can we please add a "No" option for "Are you using a stabilized receiver?"

### ISSUE THREAD

**Issue by INFWG-Steve** [FrSkyRC/ETHOS-Feedback-Community#3744]

**Comment by INFWG-Steve** [comment]
When people are asked if they are using a stabilized receiver "No" isn't an option.  Just three dashes ---.   Some people who aren't as familiar with Ethos feel compelled to select something from the list of stabilized receivers.  They select a receiver that is the closest option to their non-stabilized receiver.  This could be fixed with a simple "No" option.   Thanks


![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85375572/c9d84492-9edd-4b4d-bc0b-53a7f0117cac)

**Comment by bsongis-frsky** [comment]
It would be better to propose "Non stabilized receiver", right?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5e92a9cc-4cde-4d4e-8127-0d9a1142fff9)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0b13d708-14b2-4ed0-96fb-eb4dbb37d7a4)

**Comment by bsongis-frsky** [comment]
Good?

**Comment by INFWG-Steve** [comment]
Yes, that's perfect, thank you!
