### ISSUE TITLE
 Ethos 1.5.4 X20 pro goes into emergency mode with  screen Title on

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#3745]
Ethos 1.5.4 X20 pro goes into emergency mode with  screen Title on

ethos 1.5.4 when i go through my screens this happens when i get to yaapu screen with the Title on
![20240330_075135](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/8f4ba244-a72e-473b-83b8-c9661ae98cdb)

**Comment by yak-54** [comment]
ok worked it out with 1.5.4 when you add yaapu  telemetry page remember to turn off screen Titles in your lua scripts if you leave it on go to that page the radio will crash

**Comment by Dsrenger** [comment]
Just Out of curiosity,

Does your model react in EM?

**Comment by yak-54** [comment]
yes but it take 3 to 4 seconds to get control back testing it on the ground

**Comment by bsongis-frsky** [comment]
The bug is produced by the lua function `lcd.setClipping(...)`
Which is a very practical function, but only used by yaapu

**Comment by yak-54** [comment]
Thank you Bertrand

**Comment by bsongis-frsky** [comment]
Non regression test added
