### ISSUE TITLE
Switching models

### ISSUE THREAD

**Issue by RomanX20PRO-CZE** [FrSkyRC/ETHOS-Feedback-Community#3746]
Hi, Bertrand @bsongis . I found a bug in the system. Once you use the special function to change the model, when you turn on the radio, everything is fine. But as soon as you switch to another one, immediately everything disconnects (receiver) and no more is caught. The radio has to be switched off and on.
Please fix, this makes this function unusable.

Dialog box: "Receiver is still on, are you sure about switching the model?"

Oh, and don't worry about the clock, I took the pictures at a different time
Thank you
![Messenger_creation_7173058717915951246](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/d36bfc82-904b-4379-83ac-32f0c4765d95)
![Messenger_creation_7173058717918618108](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/94ba84bb-456f-448d-89d9-b4f462b69508)
![Messenger_creation_7173058717920559015](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/ab923d7e-6e7c-436f-9c96-eab047c2e93b)

**Comment by bsongis-frsky** [comment]
Extra1 has RF ON ?
Would you please attach your 2 model files?

**Comment by RomanX20PRO-CZE** [comment]
When I turn on the transmitter, the Easy1 works normally. As soon as I use the special function on the two-position "switch model" switch, the model switches, but the RF module no longer works and does not connect to the Extra1 model.

**Comment by bsongis-frsky** [comment]
OK. Would you paste what is displayed in Model / RF when you have switched to Extra1?

**Comment by PengFrog** [comment]
i have the same problem, seems like the the receiver is not loaded when i use this special funktion.
in Model/RF the receivers is shown, but the connection is missing. when i want to display the options the receiver is being searched.

**Comment by RomanX20PRO-CZE** [comment]
> OK. Vložili byste to, co se zobrazuje v Model / RF, když jste přešli na Extra1?

Ok, but in the evening ;)

**Comment by RomanX20PRO-CZE** [comment]
Hi, @bsongis-frsky . I tried it again on the simulator and it's really unusable.
I turn on the radio with the active JOHN DEERE model, everything is fine. Switching the model in the classic way also works normally. In the RF system the internal odul is always on ACCESS for both.
However, as soon as I want to switch from FENDT to JOHN DEERE using a special function on the two-position switch, the model switches to JOHN DEERE, but the RF signal icon is gone and the connection to the model (according to others' experience) is gone too. In the model menu in the RF system everything seems normal. The icon only appears after turning the RF module off and back on in the menu. Switching back to FENDT doesn't change anything either, the model is no longer connected.

Pictures:
1) JOHN DEERE main screen
2) JOHN DEERE RF setup system
3) FENDT main screen
4) FENDT RF setup system
5) Model switching alert with special function
6) JOHN DEERE without RF icon in the top bar
7) JOHN DEERE without icon - RF setting system


![1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/93ef4520-a981-4eac-920d-323f8ebb02ab)
![2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/b1fcc433-5b29-402c-9fbc-e3fcb83533af)
![3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/32a4b907-4551-4a79-bd62-927aaefbfac3)
![4](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/affefdd8-4816-4c4a-9010-d0b2c5218e2e)
![5](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/f4b5a5d0-2a62-4ce4-b53b-eaa8ee9c69a6)
![6](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/523991fb-f444-45e1-bfd6-d588bf8127e2)
![7](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/162073542/0617a7ef-0df4-4a7c-a633-1838b8b7f3bb)

**Comment by RomanX20PRO-CZE** [comment]
> Extra1 has RF ON ? Would you please attach your 2 model files?

Sorry, luckily I haven't updated yet (learned my lesson from OpenTX) so I'm only using the simulator and I couldn't find the model files there :(

**Comment by PengFrog** [comment]
Hi Bertrand, do you need more information ?
i could provide screens, too from a x20s when still needed.

**Comment by RomanX20PRO-CZE** [comment]
So, what now? You can rename this problem to "ignore" ;)

**Comment by PengFrog** [comment]
i hope not :)

**Comment by bsongis** [comment]
This problem is fixed in latest pre-releases, right?

**Comment by bsongis-frsky** [comment]
Fendt and John Deere, controlled from a FrSky radio?
Mine is here, but there is no electronics inside :)
https://atr-agri.superforum.fr/t12497-renault-carraro-571-4

**Comment by PengFrog** [comment]
Hi,
in the nightly from from today it does not work, in the simulator 1.5.6 it does not work ether...
Greetings 
Markus

**Comment by bsongis-frsky** [comment]
Reproduced on simulator

**Comment by bsongis-frsky** [comment]
I see another bug: the Checklist is not displayed, it should!

**Comment by bsongis-frsky** [comment]
Fix ready for the next nightlies

**Comment by PengFrog** [comment]
After updaten to the latent nightly on my x20s the special function to Switch models works now. The hf modul is bring loaded. 

Thanks

**Comment by bsongis-frsky** [comment]
Thanks for the feedback

**Comment by RomanX20PRO-CZE** [comment]
> Po aktualizaci na latentní noční na mém x20 nyní funguje speciální funkce pro modely Switch. Vf modul je načten.
> 
> dík

What kind version? 1.5.6 night or...?

**Comment by PengFrog** [comment]
I've tested with the 1.5 nightlies...

**Comment by RomanX20PRO-CZE** [comment]
@bsongis  Hey Bertrand not working in 1.5.6 simulator? :)
By the way, nice tractor :)  Can we chat private anywhere? ;) About traktors, right :D

**Comment by bsongis-frsky** [comment]
This issue should be fixed, but in the nightlies, not 1.5.6
And it will be included in 1.5.7, but we have no major / critical issue for now, so I delay it a little bit to include as many minor fixes as possible.
I am on Discord, answering as many users as time allows!
You will find me easily from the "FrSky Ethos" rooms

**Comment by RomanX20PRO-CZE** [comment]
> Tento problém by měl být opraven, ale v nočních, ne 1.5.6 A bude zahrnut do 1.5.7, ale zatím nemáme žádný zásadní/kritický problém, takže to trochu zdržuji, abych zahrnul tolik drobných oprav, kolik je možný. Jsem na Discordu a odpovídám tolika uživatelům, jak mi čas dovolí! Najdete mě snadno z pokojů "FrSky Ethos".

Yeah but I didn't have account on discord. I have it but don't understand your "rooms"... It tolds i need some link for join to server...

**Comment by bsongis** [comment]
I think you may join it by searching the server "FrSky ETHOS"
