### ISSUE TITLE
SB switch only has mid and down.

### ISSUE THREAD

**Issue by Thoemse** [FrSkyRC/ETHOS-Feedback-Community#375]
My switch B has no UP position. Calibrating does not help. Any iseas what causes this? I am quite sure it worked normal at the beginning. Now up is down, and down is down. Mid position works.
Old firmware it worked.

https://youtu.be/1QESbPbLoXA

**Comment by hrenz** [comment]
lock at the Hardware setting  for B 
as 3pos switch not 2 pos switch

**Comment by Thoemse** [comment]
Itbis on 3 pos.

**Comment by hrenz** [comment]
look and test it at Hardware test screen
if not ok then Pin at Switch defect or kabel or socket, or Pin at controller

**Comment by jreis1** [comment]
Which firmware version are you using? update to 1.0.7 and try again :)

**Comment by Thoemse** [comment]
1.0.7 - maybe it simply went defective. 😞
Hrenz: the vid is from the test screen.

**Comment by bsongis-frsky** [comment]
@Thoemse please contact your seller, I think it is a hardware issue
