### ISSUE TITLE
Allow the user to test the Emergency Mode

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#3750]
- [x] Find a safe method to allow the user to test the EM. Perhaps a Lua script method? Once called this method would open a Confirmation Dialog, and the reboot would happen if the user confirms
- [x] Check if Lua enabled external modules are correctly initialized after an EM

**Comment by mgsanna** [comment]
Nice feature!

**Comment by bsongis-frsky** [comment]
The message "RAM backup error: Max size reached" will be a major error as it will make the EM model load slower (from SD instead of RTC backup RAM)

 ![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/eb74bcfa-cd45-4526-84fb-02f9f5d68ed2)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0d5a597d-c19a-498b-a8a8-209d78d5bb67)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8b6536c8-8eeb-43d2-aa60-44ca58c421ca)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/46358d66-c05e-4eef-b7c7-90c326f54308)

**Comment by spoke2570** [comment]
I cannot find this feature on my X20S. I am on the FCC Nightly 1.5.8 from 5/14  #33d7c6bc 
..nor in the May 15 version #6fd9f78e that I just loaded.
I am definitely looking in the place depicted above.

**Comment by bsongis** [comment]
You need the Lua script here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3750

**Comment by spoke2570** [comment]
Apologies, Bertrand. That #3750 links to this thread. I may be blind, but I cannot find the required script here. Should it have loaded with the nightly update? I did update all components.

**Comment by bsongis** [comment]
Sorry, here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5/lua/tool-emergency
