### ISSUE TITLE
Power cycle needed to reconnect to RX when developing

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#3753]
Not sure if this is a feature for safety - or a bug.

With FRSKY rx when developing and 'bound' to a receiver...

When you swich between serial and ethos mode you loose connection to the rx.   I expect this when in ethos mode.

But..

When it switches to serial,  the link never comes back.  So you have to power cycle.

**Comment by bsongis-frsky** [comment]
To be checked with the next nightlies
