### ISSUE TITLE
Thr => Ele mixer with switch as source input range +/-10%

### ISSUE THREAD

**Issue by miff69** [FrSkyRC/ETHOS-Feedback-Community#3754]
There's a bug with the The => Ele mixer when using a switch as THR input source.
In this case, the input range is just +/- 10%. When using an analog input source the input range is +/-100 % and the mixer is working correctly.
![screenshot-2024-03-30-60286](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4614361/aec43044-69e0-46ec-813d-de0e4e3bdec3)

ETHOS 1.5.4, THR switch SE

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6c018e89-f09b-41fc-981e-896cc0d16239)

**Comment by bsongis-frsky** [comment]
Non regression test added
