### ISSUE TITLE
X20 Pro AW Special Functions disappearing when coping models to radio.

### ISSUE THREAD

**Issue by SQB-Pilot** [FrSkyRC/ETHOS-Feedback-Community#3757]
When coping models from X20S to X20Pro AW all special Functions disappear. This also happens when the radio is backed up and then restored.

**Comment by bsongis-frsky** [comment]
I cannot reproduce it, would you please paste your model (from X20S)? Thanks!

**Comment by SQB-Pilot** [comment]
Thank you for response ,but Ive come right ,it worked the second time I tried . The only problem I have now is in my 4th flight the sound just stopped ,I have no sound at all not even from the trims , the sound was very distorted from the beginning when I loaded all my models and it seems like either the speaker or sound module has blown .

**Comment by bsongis-frsky** [comment]
And now after reboot you have still no sound?

**Comment by bsongis-frsky** [comment]
Unless you have some script / logging / etc. which uses the disk a little bit too much?
Do you use the internal Nand or the SD?

**Comment by SQB-Pilot** [comment]
After reboot ,after factory reset ,and system settings from Support @Horus still no sound ,Im not using SD Card

**Comment by bsongis-frsky** [comment]
Even the trims do no sound at all?

**Comment by SQB-Pilot** [comment]
Yes no sound form anything,
 trims, timer, even when you switch on the TX

**Comment by bsongis-frsky** [comment]
Have you sent your radio to be repaired? I think you have an hardware issue with audio!

**Comment by SQB-Pilot** [comment]
Horus RC are sending me a new speaker when it arrives here in South Africa
I will replace it ,if I put ear phones on the radio I have clear sound so
it does seem like a hardware problem
