### ISSUE TITLE
TD SR12 Mini S Port (the small 4 pin on the side) not working for telemetry

### ISSUE THREAD

**Issue by Whoisbhootru** [FrSkyRC/ETHOS-Feedback-Community#3758]
Hi all, need some help. Am on the latest FW on the X20S updated via ETHOS suite. And the latest 1.0.11 FW for the TD SR12.
Whenever I connect any sensors (FLVS ADV or GPS ADV) to the mini S port (the 4 wire small jst upgrade/ain port) on the side of the receiver, none of the telemetry sensors are recognized. They only work when I connect them to Channel 1-12 (and reconfigure that channel’s pin as S port or F Bus). The problem however is that I need all 12 channels and all 12 pin outs of the receiver for my servos. I have connected the correct colours (yellow wire signal, red wire positive, black wire negative). I am puzzled as to why this is the case…on my Archer SR12+ receivers, the mini s port all worked and recognized the telemetry sensors immediately. Please help! Thank you for your time. Ps. The firmware of the sensors have all been updated too. Please see the following picture which shows the port I am referring to.

**Comment by Whoisbhootru** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165516885/b5c182ef-68a9-4d38-bea1-ddeca0de2370)

**Comment by Whoisbhootru** [comment]
@
![IMG_0881](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165516885/44342479-bf60-4864-9c02-e067304c9b1e)

**Comment by Dsrenger** [comment]
As written on the receiver it is a upgrade und Ain Port.
No Sport 

If you need all 12 channels as pwm you just bought the wrong receiver.

Not a bug...

**Comment by Whoisbhootru** [comment]
> As written on the receiver it is a upgrade und Ain Port. No Sport
> 
> If you need all 12 channels as pwm you just bought the wrong receiver.
> 
> Not a bug...

Thanks for your reply, but the same port works on the Archer series receivers for telemetry. 

So if it was indeed restricted to being only an upgrade port, this should not be the case. 

Also the AIN is an analog-in input so then the port is theoretically capable of telemetry for batt voltage. (As per the ETHOS manual on this repository)

@bsongis-frsky if you could please clarify this for me, I would really appreciate it. Thanks!

**Comment by Dsrenger** [comment]
The equivalent archer was the SR10. Compare the housings to each other.

The SR10 was a 10 channel receiver with a separate sport on the white connector.

The Archer plus or TD SR12 has the same housing as the SR10 but 2 channels more, that need to be used as Sport if you need it.

This was exactly one of the changes from the old to the new receiver lines.
2 channels more, in sacrifice of the sport on the white connector.

**Comment by Whoisbhootru** [comment]
> The equivalent archer was the SR10. Compare the housings to each other.
> 
> The SR10 was a 10 channel receiver with a separate sport on the white connector.
> 
> The Archer plus or TD SR12 has the same housing as the SR10 but 2 channels more, that need to be used as Sport if you need it.
> 
> This was exactly one of the changes from the old to the new receiver lines. 2 channels more, in sacrifice of the sport on the white connector.

Yes I see it now! I don’t know how I missed it. Thank you for the patience and help.

ps. I am reading through the manual…would it be possible to connect an R9 mini as a slave (not purely redundant) receiver and use that to “expand” my number of ports for telemetry?

Thanks in advance for the help!
