### ISSUE TITLE
French sound files

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#376]
[system_french.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6566882/system_french.zip)

Bonsoir Bertrand

French system sound files.

**Comment by WismyYao** [comment]
Thanks for you help :)

**Comment by bsongis-frsky** [comment]
Thanks, but ... why such files? They are automatically generated from Google TextToSpeech

**Comment by aviat40** [comment]
It was more clear than TextToSpeech with this voice, but as you want, if you prefer Google TextToSpeech !

**Comment by aviat40** [comment]
Google TTS version, than you can choose which is the best for you
[French_googleTTS.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6568678/French_googleTTS.zip)

**Comment by bsongis-frsky** [comment]
The problem is the maintenance, we need automatic tools for all languages...

**Comment by aviat40** [comment]
OK, you are right, so use the french google_TTS file. If you need, i have done the PSV file for TTS automate.

**Comment by bsongis-frsky** [comment]
PSV? We have a CSV here for each language

**Comment by aviat40** [comment]
PSV is the native format for TTSAutomate.  But CSV could be imported within TTSAutomate.

**Comment by bsongis-frsky** [comment]
I use Google Cloud Text To Speech here, it's a little bit different, it has many voices and many languages (but it is not free).
