### ISSUE TITLE
Gps adv not correct 

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#3760]
I am using a Frsky GPS Adv sensor and I don't think it's accurate. It's showing about 600-800 feet off the actual location. Not sure what to do to get it to show the actual location on my display. Frsky X18s transmitter. 
Thank you.
Bill

**Comment by Wolepo** [comment]
I had a similar problem with the time in the past few days. There was a large deviation of several hours. The next day everything was correct again.  I would observe this over a longer period of time.

**Comment by strgaltdel** [comment]
.. a lot of gps jamming could be observed in europe this time
