### ISSUE TITLE
X14 Ethos 1.5.4 setup wizard page does not change page correctly in channel display

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#3764]
Setting up a new model on TW X14 Ethos 1.5.4 (problem also with earlier versions) with more than 5 channels. At the page for confirming or change channel allocation  

![screenshot-2024-03-31-43435](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/823a3a9e-5dd2-43d0-b7ae-95197cbebcfe)

Right-scrolling from the last channel on page one to the next channel the page does NOT change to the next page two and shows no channel selected

![screenshot-2024-03-31-43441](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/7f462a5b-10ab-4b5a-a972-4accdff2458e)

Pressing Enter now the next channel is selected blindly and can be modified, HR in this example

![screenshot-2024-03-31-43447](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/4a311834-5c75-4c68-a253-f9bfff700232)

With the next right-scroll the page changes now the next page and the second channel on this page, SR in this example, is highlighted / selected

![screenshot-2024-03-31-43452](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/80fa3f17-b30e-4ce5-8b0f-a1fa5426f4dd)

When left-scrolling now changes to the first page again and not to the first channel on the second page.

The first channel on the second page, HR in this example, can only be selected and modified blindly.

**Comment by bsongis-frsky** [comment]
Same problem on X18 / Horus
