### ISSUE TITLE
Ethos Suite 1.5.3 crashing upon opening

### ISSUE THREAD

**Issue by leowagen** [FrSkyRC/ETHOS-Feedback-Community#3766]
Suite 1.5.3 crashes immediately I try to open it. 
![ETHOS SUITE 1 5 3 ISSUE_WIN7](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/117116581/2b2756d5-36e9-4728-9ada-44bb85a912a1)

My computer setup is the following:
Windows 7 Professional
8 GB Ram
64 bits
Processor: Intel Core i5-4210M - CPU @ 2.60 Ghz

Until 1.5.1 it worked seamlessly....

**Comment by leowagen** [comment]
I went back to Suite 1.5.1 and runs, but: 

I updated my ISRM X10 bootloader to 1.5.3 in order to try going to 1.5.4 Ethos. Now Suite 1.5.1 doesn´t "see" the radio. 

So for having a safe version in my radio I need to go back all the way to 1.4.7 because I´m stuck with Ethos Suite 1.5.1 not recognizing my 1.5.3 boot loader / 1.5.1 firmware ISRM  X10.

**Comment by leowagen** [comment]
This is the last combination i tried and makes Suite recognize my radio:
Suite 1.5.2
Bootloader 1.4.17 
Ethos still 1.5.1

Next bootloader version is not recognized by Suite
Next Suite Version Crashes

**Comment by strgaltdel** [comment]
win7 is almost 15 years old
end of support was 2020

there is a high chance that some libs on your system wont support functionality needed by actual suite revisions 

did you try on a win10 or win11 system?

**Comment by leowagen** [comment]
Not yet. The other one I have is my work laptop and is packed with firewalls and admin limitations. 

Will give it a try in a friends computer.

**Comment by leowagen** [comment]
> win7 is almost 15 years old end of support was 2020
> 
> there is a high chance that some libs on your system wont support functionality needed by actual suite revisions
> 
> did you try on a win10 or win11 system?

Well, you are absolutely right. Tried in WIN10, and now it all works properly:

Suite 1.5.3 talks with bootloader 1.5.3, so I was able to update to Ethos 1.5.4

**Comment by leowagen** [comment]
My suggestion, state somewhere the minimum requirements for latest Suite version. 

If anyone with Win7 is reading, give up. You need Win10!

**Comment by bsongis-frsky** [comment]
Latest Electron libs don't work right on Windows 7, which is very old and not anymore supported!
