### ISSUE TITLE
[Request] CRSF sensor ratio and offset fields

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#3767]
I've realized that with FrSky voltage and temp telemetry sensors, you can adjust ratio and/or offset to calibrate the value coming from the device if it is incorrect. However, I don't see the ability to do this with the CRSF sensor equivalents. It would be very helpful to have all that adjustability added to the CRSF sensor counterparts.

I think it would actually be helpful to have both ratio and offset available for all voltage, temperature, current, and consumption sensors for situations where you cannot calibrate at the source. That way you don't clutter things up with calculated sensors to correct them.

Voltage sensor coming though with ACCESS:
![IMG_6439](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1323809/8ca4d281-c701-4d69-8e11-4ff8902bc723)

Equivalent voltage sensor coming through with ELRS/CRSF:
![IMG_6438](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1323809/c7a08688-e097-4ea5-b995-ed1d5e939674)

**Comment by robthomson** [comment]
10% agree.  This is a very useful feature to have

**Comment by flyingeek** [comment]
It would be nice to see this implemented

**Comment by mortehoe** [comment]
X10S running Ethos 1.5.18 .
After discovering telemetry from elrs receiver I need to adjust the voltage calibration however the Ratio and Offset buttons are missing from the screen (see attached)

![screenshot-2024-10-30-38500](https://github.com/user-attachments/assets/259f16a0-7eab-44b6-8789-1066d262c45f)
![screenshot-2024-10-30-38511](https://github.com/user-attachments/assets/a3412e98-0ead-4f4a-9a4a-5ca8dcbd1c3c)
![screenshot-2024-10-30-38524](https://github.com/user-attachments/assets/2c9c5e48-3298-42c1-b0be-eed89be8591b)

**Comment by mortehoe** [comment]
Please remove the stale notice and comment if this is likely to be implemented.

**Comment by bsongis-frsky** [comment]
Please check 1.6.0, it is implemented now.

**Comment by bsongis-frsky** [comment]
> 10% agree. This is a very useful feature to have

Only 10% we are good :)
