### ISSUE TITLE
Ethos 1.5.5 Italian Update

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3768]
[it.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14817246/it.csv)

**Comment by mgsanna** [comment]
@bsongis @bsongis-frsky can you add this update to 1.5.5 nightly or 1.5.5 release... thanks for your mega job!

**Comment by bsongis-frsky** [comment]
It is already present in nightlies, I even see yours is a little bit outdated (Repurpose vs Repurpose trim)

**Comment by mgsanna** [comment]
@bsongis-frsky @bsongis Infact this one was the update of the already included in nightly, that's why I ask you if you can insert the updated one....

**Comment by bsongis-frsky** [comment]
I think no, the file doesn't seem new!

**Comment by mgsanna** [comment]
ok I missed the last csv from nightly simulator sorry
