### ISSUE TITLE
[Enhancement] Calculated sensor

### ISSUE THREAD

**Issue by Nicholas-Luoyi** [FrSkyRC/ETHOS-Feedback-Community#377]
~~Addition~~
~~Multiply~~
~~Average~~
~~Totalize~~

- [x] Distance (from GPS longitude / latitude)
- [x] Trip (from speed sensors)
- [x] Consumption (from current sensors)

**Comment by DaySpeed955i** [comment]
Could you please add "trip" too, it can be based on consumption but using Air speed or GPS speed for calculation.
Units in meters, feet, km, miles.

Thanks

**Comment by Hobby4life** [comment]
I only think you can derrive trip information from GPS location measurement intervals. So you get some sort of trip distance.
Anyhow it would be fun to have not mandatory.

**Comment by DaySpeed955i** [comment]
You can already do it with OpenTX, use consumption and Gspd for sensor, it will give you mAh but in fact it will be in meters if you use kph for Gspd.

I create sensor “Gtrp” name, consumption, sensor Gspd, unit will be mAh, no log.
Then create “Trip” sensor, ADD, sensor Gtrip, unit meters.
You have a nice trip counter from kph.

Very precise for ground speed, would be even better with Air speed.

**Comment by islandflight** [comment]
Any ideas when the calculated sensors likely to be implemented. Not having these is really a barrier to be using the x20 at the moment and I'm sure many wkykd really appreciate this being addressed. Thanks

**Comment by Hobby4life** [comment]
I really hope it will be implemented soon too.

**Comment by AfterburnerRC** [comment]
The lowest cell and consumption (MAH) is the most important telem function.  Monitoring the lowest SINGLE cell (for example 3.5v) is a quick way to translate total voltage no matter how many cells you are running.  If all you fly is a 6S battery system then it's easy to remember that 25.2v is full and 21v you should be landing,  of course assuming Lipo.  Lately, I have been using consumption (MAH) which is MUCH more accurate as it's a true gas gauge vs estimated voltage as this can and WILL vary based on flying style.  The lowest single cell is important also as I can compare the two.  It's also nice to have as it can serve as an early warning to a possible cell going bad.

**Comment by bsongis-frsky** [comment]
The implementation of mAh is ready, it will be in release 1.0.10
But first 1.0.9 has to be released

**Comment by islandflight** [comment]
Please can you keep the multiply option e.g. to get power in watts need to multiply voltage and current.
