### ISSUE TITLE
lua script lcd.setWindowTitle function does not work

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#3770]
the lcd.setWindowTitle method doesn't seem to work, I tried to use it in two ways:

First:

When trying to call it in the paint method the title is not not changed.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1608096/eb83b4f7-c84f-4fd0-86b0-92d5512d26bb)

Second:

When calling in the create function the widget fails to load and defaults back to the blank widget.

**Comment by Storchy1** [comment]
Have you tried something like this:
windowTitle = windowTitle .."/".. widget.timer2.name
use .. instead of +

**Comment by bsongis-frsky** [comment]
`lcd.setWindowTitle(...)` is available on tools, not widgets

**Comment by bsongis-frsky** [comment]
You have to give the widget name in `registerWidget(...)`, it may be a function

**Comment by fdm225** [comment]
I look at the value widget and it's title is that of the, is there a way to change the widget's title then?  I ask as I re-wrote my code to make the name parameter in the registerWidget a function but it's only called once; not allowing for a change to the name once the user has changed the input of my script.

thanks,
Dave
