### ISSUE TITLE
Feature Request: Play fixed value

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#3771]
Hi

In the new (great I must say) voice system, could you add the possibility to say a fixed value, not as TTS, but with the standard system voice pack? Could be added to voice flows...
Yeah, its a minor.... I was too lazy to program a Thermal 2 so I just wanted to let it say Thermal and then a fixed 2 :-)

Just delete if not valuable :-)

**Comment by bsongis-frsky** [comment]
You can just copy the "2.wav" in your audio directory (not system), then you can access it easily

**Comment by jasc76** [comment]
:-)
