### ISSUE TITLE
No range setting possible in calculating sensor "Distance"

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3772]
Hello, 
In 1.5.4 X10S Express you cannot set the range <0m in the calculating sensor "Distance".
 
Yours sincerely, Wolfgang
![Anstand](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/ac38e404-0e1f-4e15-a74d-26d045c64804)

**Comment by bsongis-frsky** [comment]
I don't understand how a distance can be negative, it's the sum of 2 squared values

**Comment by Wolepo** [comment]
Both values must of course be adapted to the circumstances. Negative values are nonsense for the distance, but the maximum Wert cannot be setIt is fixed at 0m

**Comment by Wolepo** [comment]
Sorry, I have just realised that I have chosen the wrong symbol. It should of course be > 0m.

**Comment by bsongis-frsky** [comment]
Fixed in next nightlies
