### ISSUE TITLE
VARs can no longer be larger than +-100%

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3773]
1.5.5 nightly

VARs can no longer be larger than +-100%
In the manual I have +/- 500% so I am sure I would have tested that during the early 1.5.0 nightlies. 

On my flaps I have offset servo arms in order to get maximum travel for downward flaps movement. Now I am unable to use a Var to specify the 180% travel I need for the flaps. I can manually specify that weight in the butterfly mix, but I want to separate settings from mixes using VARs.

**Comment by lthole** [comment]
At the least I need +/- 200%

**Comment by strgaltdel** [comment]
yepp,
fully support +/- 200%, at least !

use case:
 a flap with an offset by 50% needs -150% weight to reach the endpoint.
so a worst case scenario would result in -200% var settings

don"t know anything about "functional models"  
maybe they need even more ?

**Comment by mgsanna** [comment]
maybe this one using 1.5.4

<img width="814" alt="Screenshot 2024-04-01 210641" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/1bb16a78-51a8-4163-a398-3bacbd8949ab">

**Comment by strgaltdel** [comment]
@mgsanna
the range values will cut the bigger entries in your example
so you won't be able to get anything exceeding +/-100% in a mixer

**Comment by mgsanna** [comment]
> @mgsanna the range values will cut the bigger entries in your example so you won't be able to get anything exceeding +/-100% in a mixer

Correct I was trying right now… @strgaltdel

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1d9ae898-315a-4ed7-9265-94d6338b00ab)
