### ISSUE TITLE
Message "Sensor lost" 

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3774]
Hello, yesterday I had the message "Sensor lost" several times. I have not been able to localise the culprit. Here are two log files:
Everything is connected to FBUS, Neuron II, FLV AVD, Vari AVD, GPS AVD, 2X servos XACT 5101 
[RamphorMax-2024-03-31-17-41-51.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14822734/RamphorMax-2024-03-31-17-41-51.csv)

All sensors connected to S.Port
[Thermy-3VLW-2024-03-31-16-25-53.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14822737/Thermy-3VLW-2024-03-31-16-25-53.csv)

X10S Express V1.5.4

Yours sincerely, Wolfgang

**Comment by glipski50** [comment]
Did you have those sensor lost messages also with earlier versions of Ethos? I have also sensor lost messages although I only have one sensor connected. With 1.4.17 I did not have senor lost.

**Comment by yak-54** [comment]
i am getting the same thing Sensor lost X20 pro on 1.5.4

**Comment by Wolepo** [comment]
The number of reports has always been there. Although they have become fewer, they are still present. The receivers are the SR8Pro (telemetry on the S.Port) and Archer Plus SR8 (telemetry on the FBUS).

**Comment by bsongis-frsky** [comment]
It would be interesting to know which is the "lost" sensor. Perhaps the GPS which sends a value a little bit late?

**Comment by glipski50** [comment]
In my case I use a TW X14 with 1.5.4 and a TW R8 receiver. I have ONLY ONE sensor connected, a unisense-e sensor that has the latest firmware update and the correct PhysID and AppID setup for S.Port. I get the semsor lost message already within the first 5 minutes after switching on transmitter / receiver. Sometimes the sensor lost message comes seconds after switching on the receiver. The message comes about every 5 minutes at least. Sometimes I also get a sensor conflict message although no other sensors are connected.

If needed I can report the individual AppID used in my setup.

**Comment by Wolepo** [comment]
If you look at the attached log files, RSSSI, Empf.Bat, the individual cells, ESC Voltage, Temp Motor and ESC Temp are all affected. All 0 values are in the same place.
Here is another log
[Thermy-3VLW-2024-03-31-16-25-53.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14833919/Thermy-3VLW-2024-03-31-16-25-53.csv)

**Comment by robertobrazill** [comment]
I don't receive this message, but I constantly face non-standard readings, as you can see in TEMP1 and TEMP2 of the file sent as an attachment. I use the RPM FrSky Smart Port to only take temperature readings.
[Uploading EDGE---540-T-2024-04-01-15-51-34.csv…]()

**Comment by Wolepo** [comment]
Please upload the *.csv file again

**Comment by robertobrazill** [comment]
[EDGE---540-T-2024-04-01-18-14-52.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14836447/EDGE---540-T-2024-04-01-18-14-52.csv)
[EDGE---540-T-2024-04-01-17-42-42.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14836448/EDGE---540-T-2024-04-01-17-42-42.csv)
[EDGE---540-T-2024-04-01-16-36-45.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14836450/EDGE---540-T-2024-04-01-16-36-45.csv)
[EDGE---540-T-2024-04-01-15-51-34.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14836451/EDGE---540-T-2024-04-01-15-51-34.csv)

**Comment by Wolepo** [comment]
Temp1 makes inexplicable jumps upwards. Could this be a wakel contact?

**Comment by robertobrazill** [comment]
It's not bad contact between the connectors, this also happens in some data, not just in TEMP and it bothers me.

**Comment by glipski50** [comment]
I have done some more tests with different sensors from different vendors and also a Frsky one. In all test runs I had only ONE sensor connected to S.Port

Frsky ESC Neuron 40
sm-modellbau Unisense-E
YGE 35 LVT with Texy
All are also sold in USA

Even with the Frsky ESC Neuron 40 I got a sensor conflict message after about 5-10 minutes. 

All three sensors use also a same AppID to transmit two different sensor values, propably to make best use of the bandwith. For example both the Frsky ESC Neuron 40 and the sm Unisense-E use
0B60 ESC U/min
0B60  ESC consumption

Can it be that Ethos is creating the message as there may be problems in handling stably one AppID transmitting two different sensor values?

Transmitter TW X14 with Ethos 1.5.4
Receiver TW R8 and Archer R6 with most actual firmware

**Comment by Wolepo** [comment]
Sensor losses are still present in the log. Ethos 1.5.9

**Comment by Richrfl** [comment]
I am getting the same problem (sensor lost) and Sensor conflict in 1.5.9 FCC
