### ISSUE TITLE
Calculated sensors do not run into negative

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3775]
Contrary to what is described in the manual, the custom sensors (when running in custom mode) do not go into the negative range and react strangely.  
This makes some important sensors unusable for me.  

Ethos 1.5.4 
X20pro

![0E526DEF-AFBD-4F77-9779-69EB419EBC82](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/089ad0e6-81bc-4da4-93df-c0c15e382dc3)

![9081D4C1-FD06-4465-9B3A-DE3F3E478655](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/c706b698-8f1b-4a7a-a652-7a96fd0d412d)
![E4C5A982-8F96-49C7-999B-534391504F34](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/872f0a28-988f-46cb-83d3-d6214d8acb33)
![D9B08296-F691-4454-9E84-65B6D8CE1577](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/53031f81-bee9-4fcf-9f17-750b6b190452)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2cf05020-ee24-4deb-9d52-0e18224cfb8c)
