### ISSUE TITLE
[Timer Issue] Throttle Hold sometimes enables "Throttle Active" and starts timer

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#3777]
Radio is X20 PRO.  Ethos 1.5.4 Release.   Haven't been able to figure out what's going on here, but I've got multiple models that behave this way.   But - not all of them, which makes it even more confusing.  

Basically, I have a timer that uses "Throttle Active" as the trigger.  With the throttle stick it works normally.  But, on some of my models, which as far as I can tell are configured identically to the others, when Throttle hold (in the Throttle mixer) is engaged, it makes Throttle Active become true, and starts the timer which continues to run regardless of the throttle position, until throttle hold is disengaged.

I've attached a .zip containing a few models:
60 Edge 540.bin - this one behaves incorrectly.  When throttle hold is engaged, the timer runs.  Hold is on SG.
73 Slick 360.bin - this one behaves as expected.  The timer runs only when hold is *not* engaged and when throttle stick is >0.  
Edge 603.bin - this one also behaves incorrectly.  It's a model I created on 1.5.4 just for testing.

The other two models are, I believe, conversions from 1.4.17, but I may be wrong about the Slick - I honestly can't remember because I had to restore a backup from another radio of that model when I experienced issue #3776 on it.
[Timer Issue.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14828699/Timer.Issue.zip)

Unless I'm misunderstanding throttle hold itself, this behavior doesn't make sense to me.  And even if that's the case, it's especially confusing that I have two different behaviors in (as far as I can tell) identical configurations.

**Comment by bsongis-frsky** [comment]
Would you please check if everything is working correctly for you in the next nightlies?

**Comment by BladeScraper-Designs** [comment]
I just updated to the latest nightly (1.5.5 FCC, #c2f659f8) , and still seems to have the same issue on both models that did in my original post, and the model that didn't have the issue still also does not.

Here are the files that updated to the nightly.
[nightly models.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14860314/nightly.models.zip)

**Comment by bsongis-frsky** [comment]
The nightlies are still not finished, they should be ready in a couple of hours.
