### ISSUE TITLE
1.5.4 Bizarre VAR behavior.

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#3778]
Create a new VAR.
Long press on Range/Max and select "Maximum. Returns a value of 100000000%
Change the Value to "Max" returns 500%
Add an action: "Always on", ADD,  "1" (actually any value will do).
Values starts increasing at more than 1% a second. Apparently on it's way to 100,000,000.
Me thinks it's a bug...

**Comment by bsongis-frsky** [comment]
Fix ready for 1.5.5

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/84920a15-4097-44bd-b8a3-741e983f570a)
