### ISSUE TITLE
Aggiorna tandem x20s

### ISSUE THREAD

**Issue by Andreax20s** [FrSkyRC/ETHOS-Feedback-Community#3780]

**Comment by mgsanna** [comment]
Come hai aggiornato la Radio?
con la suite? da che bootloader partivi? che firmware avevi?
 poi aprire 2 issue non serve

**Comment by mgsanna** [comment]
chiudi questa issue in italiano, GitHub usi inglese...

**Comment by Andreax20s** [comment]
Non so come chiudere questo

Il giorno mar 2 apr 2024 alle 12:30 Marco Gualtiero Sanna <
***@***.***> ha scritto:

**Comment by mgsanna** [comment]
![IMG_7595](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/8bad9d97-fd54-4be4-b8f4-5f2fe2c8670e)
Puoi chiudere le issue nei 3 pallini a dx in alto dovrebbe esserci l’opzione chiudi issue

**Comment by Andreax20s** [comment]
solved
