### ISSUE TITLE
1.5.5 Testing version doesn't show up in list in Suite 1.5.3

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3782]
Suite 1.5.3, OS 12.7.4 
The Testing version of the 1.5.5 Firmware package does not appear in the list on Suite. 

![Suite](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/5406925e-e606-4946-ae52-08ddb6e5d45d)

**Comment by bsongis-frsky** [comment]
Fixed
