### ISSUE TITLE
X20Pro Ext1 and Ext2 encoder display reversed in calibration menue

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#3783]
Hello Bertrand,
Transmitter: X20Pro
In ETHOS 1.5.4 in Hardware / Calibration of analog encoders, Ext1 and Ext2 are swapped. The encoder display is reversed.
Left encoder is shown at the bottom right and right encoder is shown at the bottom left.
The 3D gimbals with switch were properly installed by Engel MT before delivery of the X20Pro.
We had a similar problem at the very beginning when installing the 3D gimbals with switch and ETHOS 1.4.15.
Thank you for your work and effort.
Best regards,
Torsten

**Comment by yak55** [comment]
Hello Bertrand, I already reported the same error on February 25.
I also asked again but did not get an answer.
Issue #3503

Could you please also look for #3502?
Also reported on 25.02. (Copy error checklist Potis X20S 
About X20 Pro.

That would be great

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Am I right in saying that it is not only a problem of position on screen, but also the values given by EXT1 and EXT2 are swapped?

**Comment by bsongis-frsky** [comment]
EXT1 should be at the left
EXT2 should be at the right

**Comment by yak55** [comment]
Yes, Ext1 and Ext2 are swapped. Tandem XE is correctly, X20Pro ist wrong.
Correct would be: Ext1 left, Ext2 right.
Greetings Eugen

**Comment by bsongis-frsky** [comment]
They are swapped also for the values?
It looks like they are plugged the wrong way!

**Comment by yak55** [comment]
Hello Bertrand, wrong connection is ruled out, they are correctly soldered to the circuit board. (Weight as with the XE)

Greetings Eugen

**Comment by bsongis-frsky** [comment]
To be checked in the next nightlies

**Comment by bsongis-frsky** [comment]
The nightlies are online since 20 minutes, do you have some time to check that I did it well?
Thanks in advance!

**Comment by yak55** [comment]
Hi Bertrand, I have checked Ext1 and Ext2.
Had to recalibrate the encoders, then everything worked perfectly.
Now everything is correct.
Both in the hardware test and in the programming.

Many thanks for the good work

Kind regards Eugen
________________________________

**Comment by Satcomix** [comment]
Hello Bertrand,
First of all, thank you very much for your very quick help and solving the problem.
Unfortunately, I can't test the latest Nightlies on my X20Pro because I'm spending the next 4 weeks in a rehabilitation clinic and I only have the X20S with me.
But according to Eugen ( yak55), the problems have been fixed.
Thank you again.
Best regards,
Torsten
