### ISSUE TITLE
Ethos 1.5.4 - sliders inversion - wrong labels  CZ

### ISSUE THREAD

**Issue by kvak1** [FrSkyRC/ETHOS-Feedback-Community#3785]
In setup of pot/sliders are labels shorten. Instead of "Normál/Invertovat" is labeled just rest of it: "mál/Invertovat".  Thank you Karel
![20240403_132626](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/66553590/484e28dc-da78-4835-b193-8475e1e58280)

**Comment by bsongis-frsky** [comment]
Which radio?

**Comment by kvak1** [comment]
> Which radio?

X20. Thank you..

**Comment by bsongis-frsky** [comment]
Translation reduced to "Invert" on X18 / X14 / Horus

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/97723b7e-8b7f-43df-9c2a-15ce5e767f35)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/7b2f945f-5071-4a65-85b3-ef14bac785e6)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/47b93fe0-78b1-4eea-b3de-e42317bbde5a)

**Comment by kvak1** [comment]
Great. Thanks much :)
