### ISSUE TITLE
Strange behavior with LUA Source code.

### ISSUE THREAD

**Issue by stefe2** [FrSkyRC/ETHOS-Feedback-Community#3788]
I am sending different values with a LUA script I made when I press buttons on screen.  

I am using LUA Source example to send the values to a channel.  If I use "source:decimals(2)", I will need to send values between -10 and 10.  At "source:decimals(1)" it will be -100 to 100 and "source:decimals(0)" will be -1000 and 1000.  Back in version 1.4.17 I was at "source:decimals(2)" and sending values between -1000 and 1000.  

Is this normal ?

Thanks !

**Comment by bsongis-frsky** [comment]
I just checked with this example and everything seems to be working right, would you please attach your script here? Perhaps the problem is elsewhere!

```lua

-- Lua Source Example

local translations = {en="Lua Source", fr="Source Lua"}

local function name(widget)
  local locale = system.getLocale()
  return translations[locale] or translations["en"]
end

local function sourceInit(source)
  source:value(0.1)
  source:decimals(2)
  source:unit(UNIT_VOLT)
end

local function sourceWakeup(source)
  switch = system.getSource("SA")
  switchValue = switch:value()
  if switchValue > 0 then
    source:value(50)
  else  
    source:value(source:value() + 0.1)
  end  
end

local function init()
  system.registerSource({key="Example", name=name, init=sourceInit, wakeup=sourceWakeup})
end

return {init=init}

```

**Comment by stefe2** [comment]
local translations = {en="Kyberpad Source"}

local function name(widget)
  local locale = system.getLocale()
  return translations[locale] or translations["en"]
end

local function sourceInit(source)
  source:value(0)
  source:decimals(2)
end

local function init()
  system.registerSource({key="Kyber", name=name, init=sourceInit})
end

return {init=init}

**Comment by stefe2** [comment]
`local translations = {en="Kyberpad Source"}

local function name(widget)
  local locale = system.getLocale()
  return translations[locale] or translations["en"]
end

local function sourceInit(source)
  source:value(0)
  source:decimals(2)
end

local function init()
  system.registerSource({key="Kyber", name=name, init=sourceInit})
end

return {init=init}`

**Comment by bsongis-frsky** [comment]
But I see no call to `value` in your example, except in sourceInit

**Comment by stefe2** [comment]
This is how I call it in my main code...

        -- Compute Button Value to Send to the Channel
        if but > 0 then
			local value = 0
			if widget.but == 1 then value = -1020
				elseif widget.but == 2 then value =  -935
				elseif widget.but == 3 then value =  -850
				elseif widget.but == 4 then value =  -765
				elseif widget.but == 5 then value =  -680
				elseif widget.but == 6 then value =  -595
				elseif widget.but == 7 then value =  -510
				elseif widget.but == 8 then value =  -425
				elseif widget.but == 9 then value =  -340
				elseif widget.but == 10 then value = -255 
				elseif widget.but == 11 then value = -170
				elseif widget.but == 12 then value = -85
				elseif widget.but == 13 then value =  85
				elseif widget.but == 14 then value =  170
				elseif widget.but == 15 then value =  255
			end
			widget.PWMtext = value
			widget.highlight = 1
			widget.highlighttext = widget.highlight
			widget.source:value(value)
		end

**Comment by bsongis-frsky** [comment]
Now your code has a widget. I feel lost. 

Would you share the minimal code which doesn't work for you (but complete code) so that I can understand, I wonder if your issue is related or not with Lua sources!
