### ISSUE TITLE
L'ecran superieur n'affiche plus les données de télémétrie 

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#3789]
Tandem Xe 1.5.4 
Gr6 plus dernier firmware.

![IMG_20240404_105203](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89158034/ca5f0ea4-0769-4aee-9fd5-395d44311169)

Bonjour,
L'ecran superieur n'affiche plus les données de télémétrie et ne réagit plus au changement de widget, alors que sur l'écran du bas aucun problème

Edit:
Après vérification même chose sur mes autres modèles  avec d'autres récepteurs.

Merci ;)

**Comment by bsongis-frsky** [comment]
Voudriez-vous bien recharger cette 1.5.4
Ce problème a été vu à la dernière minute, et j'ai remplacé les binaires à la volée

**Comment by bsongis-frsky** [comment]
If confirmed, duplicate of #3743

**Comment by Tonio62** [comment]
Ok, ça fonctionne en rechargeant le firmware.
Merci Bertrand ;)
