### ISSUE TITLE
TD MX weird behavior

### ISSUE THREAD

**Issue by Vicent9389** [FrSkyRC/ETHOS-Feedback-Community#3790]
Hi Everyone ,

I am new to Frsky and I am switching from Futaba .

I have set up some planes with TD Mx recievers through sbus with cortex pro .

I notice one day that by mistake I turn a Viper Jet 1.8 on with  a diferent model selected in the radio , its suppose to happen nothing because each model its binded to their receivers with their model Id , BUT what hapen was that all servos goes to full deflection .

I made several test to try to know what happend I discard any  fault because of cortex fail safe or anything like that . I also Saw that in a plane set up like the viper  with a TD10 reciever this does not happen , its only with  TD MX.

I have to say that if you turn the correct model yo move every thing and you turn off the radios servos goes to Rx fail safe position perfectly .

I also discover that if the model Wrongly selected its not TD frecuency this dont happend also .

here you  have 2 videos .

in the first one you see how  if you turn on the plane without radio the servos goes to cortex fail safe with no  problem , but if its on with a wrng model goes to full deflecction.

[url]https://youtu.be/tgZg5Rx9fLI[/url]

in the second one you see how if the wrong model selectect its access set up this dont happend.

[url]https://youtu.be/_WiwD-PfHR0[/url]

for me its a Bug but I hope someone can tell if they have this problem .

Best regards

**Comment by bsongis-frsky** [comment]
It seems a problem on receiver side, I will forward the issue

**Comment by Vicent9389** [comment]
Thanks a lot , its a great reciever  , but this may cause damage in the plane if there is mechanical bindings at full defleccion .

Best regards.

**Comment by FrSky-GX** [comment]
Problem located. We will fix it in next relaese.

**Comment by Vicent9389** [comment]
Great !!! When do you think that will be that ?
