### ISSUE TITLE
Log switch has only the funktion Delta > X   but not a Delta < X

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3792]
think ist an Error since V1.5.x   at old V1.4.x was ok

I need a Log Switch funktion with  Delta < X -30%  250ms

How can I generate this one?

Delta > X -30%  250ms, no result its wrong
Invers Delta > +30%  250ms, no result its wrong
invers Delta > -30%  250ms, no result its wrong

![2024-04-05_101407 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/5ec5fac4-e0a1-4f8d-b4c2-a66711e7b44e)

we have  A>X and A<X but not a separat Delta <X

I think the simples way could be change the Funktion to Delta <>X   
and depending of Plus X% or Minus X%  it generats Delta < X oder Delta > X  itself

helle

**Comment by hrenz** [comment]
some tests from other members

Hello,
there is definitely a bug in the Delta LS !!!
Yesterday, based on Dirk's description, I went ahead and updated a transmitter to 1.5.4, although I actually wanted to wait.
In 1.4.17 the Delta LS with minus percentage values still works perfectly and as expected and only triggers when returning from 100% towards -100% if the specified % value is exceeded in the corresponding evaluation time.
In 1.5.4 it looks completely different! As soon as I set -% values for the detection, the [logical switch](https://www.frsky-forum.de/lexicon/index.php?entry/1936-logische-schalter/) is simply set without changing the value of the "encoder" to be evaluated and is cancelled again and again in succession. This results in a "flickering/flashing" of the LS without encoder actuation. If I now switch to LS inverse in the settings for the LS, the LS is constantly active. This is also strange, because with the above-mentioned behaviour it should actually also "flicker/flash", exactly inverse to before.
Now another effect: if I set the LS delay before inactive to at least 0.1s, the LS goes permanently on, although the encoder is not moved/changed. If I now move the encoder and the values for the evaluation are reached, the LS switches off briefly. If I also switch the function to invert, the LS remains permanently on, regardless of what I do with the encoder.
Something is going completely wrong for the -% evaluation!
As I said, 1.4.17 is running perfectly.
Greetings Holger

+30%, i.e. in the 30% setting, triggers the Delta LS when the sensor is actuated from -100% in the +100% direction if the set % values are exceeded within the set time, as it should be. Only with -% to evaluation in the opposite direction does the LS no longer function. How inverted it is does not matter! In other words: with invert on, the LS always remains on, regardless of what I do with the encoder when -% is set for evaluation. With +%, it remains permanently on with invert, regardless of what I do with the encoder.
So as soon as I activate invert, the LS is active, regardless of what is done with the encoder and regardless of whether + or - % is set for evaluation.
Supplement:
I have just played a little with the value Delay before inactive and set it from 0.1s to 0.0s, then with invert active the LS sporadically changed to off for a short time when the encoder was activated, but really absolutely sporadically and after a longer period of time no more of these short changes of state of the LS when the encoder was activated.
It looks like there are not only logical but also temporal problems/

further addition: The Delta LS is a pure game of chance as soon as invert comes into play and sporadically does what it wants. Now I also had the effect that without changing the encoder value, very rarely, sometime after a long time, the LS switches off "flashing" for a moment and goes to "red" (off). This is an absolute "needle pulse" after off, i.e. only a very brief red and then green again in the LS display.
In my opinion, this is not just a pure logic error, there is more to it and the error is much deeper!
Greetings Holger

**Comment by patman13** [comment]
I use a I Δ I  > x for comparing flight hight change. 
The same I use to compare remaining battery capacity. 
Both are no longer working in 1.5.4. 
TX: X18

**Comment by hrenz** [comment]
One solution could be this one
invert the source only
![2024-04-07_064013](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/943e9704-4f67-4237-9342-bc6d77687820)
![2024-04-07_083024](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/2383ef1d-5451-47c6-ae66-4f09195fdb1a)

**Comment by HolgerJr** [comment]
Hello,
I think the Delta LS is in 1.5.4 with the settings -% and still inverts an error. With these settings there is no correct evaluation. But in 1.4.17 it works perfectly.
Greetings Holger
