### ISSUE TITLE
I Δ I > x   Not working in logical switch

### ISSUE THREAD

**Issue by patman13** [FrSkyRC/ETHOS-Feedback-Community#3794]
I use a I Δ I > x for comparing flight hight change.
The same I use to compare remaining battery capacity.
Both are no longer working in 1.5.4.
TX: X18

**Comment by patman13** [comment]
No issue!

Close, please.

**Comment by patman13** [comment]
No issue!

**Comment by bsongis** [comment]
It works correctly?

**Comment by patman13** [comment]
Yes. I did conversion of modells from OpenTX to Ethos. In Ethos |Δ| > x  has a new parameter "Prüfintervall" (check interval?). I missed to set this to "---" to get the same behaviour then in OpenTX.
