### ISSUE TITLE
1.5.5 nightly: "Waiting" error when creating new model

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3795]
**Ethos 1.5.5 Build #81c6ae1f**

I got the attached error when pressing the '+' button to create a new model.
Hitting the Return key cleared the dialog and I was able to proceed normally.
This happened just once - I've not been able to reproduce the issue. 
Could it be caused to a Lua script running in the active model (before hitting the '+' button)?
![IMG_3298](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/d152dc73-d39c-4459-ab26-3b0e323d38bd)

**Comment by mgsanna** [comment]
maybe you mistype the touchscreen , this is the transfer of file message.....

in the same menu there is a "receive model"... that generate this message untill you send with another radio via bluetooth the model

**Comment by bsongis-frsky** [comment]
Exactly

**Comment by RC-SOAR** [comment]
Aha! Yes, I touched the wrong option :-)  It does look like a runtime error message though, may I suggest a more user friendly message like "Waiting to receive model".
BTW thank you for your hard work, 1.5.5 is looking good! VARS actions and trim behaviours are working together well.
