### ISSUE TITLE
Repurpose Trim is a misnomer

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3799]
I can't help feel that Repurpose Trim is a misnomer. 
Until this week I'd not played around with it because I didn't want to repurpose any trims beyond what I am already doing in Trims. However when talking to a friend I discovered that Repurpose Trim is actually very useful because it is really Repurpose Trim Switch and doesn't affect the existing Trim values. 

May I suggest that 'Repurpose Trim' should be renamed to 'Repurpose Trim Switch'?
I can see that this may cause a slight issue with fitting into existing fields, but even if it was displayed as 'Repurpose Trim Switch' in the list of Functions and just 'Repurpose Trim..' under Actions that may help? Or perhaps when Repurpose Trim is selected the two fields Repurpose Trim and e.g. Trim Rudder could be merged into Repurpose Trim Rudder?

Thanks

**Comment by bsongis-frsky** [comment]
In 1.5.5 it is renamed as "Repurpose"

**Comment by Jedsters** [comment]
Repurpose makes more sense. 
'Repurpose switch' possibly would have been better, but at least simple Repurpose avoids the confusion.
Thanks
