### ISSUE TITLE
PLAY VALUE

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#380]
Play Value function with Rxbatt is not playing the decimal value. same with TxBatt. Seems to be all decimal values

Exemple 6.4V is playing just 6V

Normal or not ?

**Comment by bsongis-frsky** [comment]
... en français

**Comment by bsongis-frsky** [comment]
I guess you miss some prompts. i.e. "virgule5.wav"

**Comment by aviat40** [comment]
Do you mean, that from EN to FR, some file's name has to be renamed ?
point5.wav to virgule5.wav / etc .... except the virgule ! other files ?
