### ISSUE TITLE
Logic type conditions are inconsistent when used as values

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3806]
It is possible to use an LS in various places as a number,  e.g. a weight. One such example could be on the Camber Mix where it is possible to specify Weight for each channel. 
This could be useful to enable a channel if an LS is true with it having a weight of 100% and if an LS is false for it to have a weight of 0% without having to use a VAR etc.. However when an LS is false the value used for the weight is -100% which gives a very undesirable weight. I believe conventionally a logic switch should have a value of 0 if false or 1 if true (1 would be interpreted as 100% in this case).
I struggle to think of a use case where an LS being false would want a weight of -100%.
May I suggest that this should be changed so that a false LS gives a weight of 0%?

By contrast in VARs, if an LS is used as a Source for Range then the value assigned is either -10% if false or 10% if true. Again, these seem very odd values, I can see an argument for -100% or 0% here, but not +-10%. 

For VAR Values the LS value once again becomes -100% or 100%. Possibly not unreasonable.

For VAR Actions if one specifies an Action of e.g. SJ down, Add, <an LS> then the value displayed to the right of the LS shows as -100 or +100 however in reality the value which takes effect is 9.8%!! If one converts the LS back to a value then it gets the value of 10.0. This appears to all be very confused. 

Have I missed any places where an LS can be used as a value? If so, those other places which LS are permitted similarly should be checked to ensure that they have a value  which makes sense.

I suspect there is an opportunity here to give a LS value which makes most sense in each scenario. For sure that would be 0% and 100% for Weights.  

If this is done it would be wise to make it clearly known in the release notes just in case anyone is relying on a value of -100% as a LS weight. It may even be worth a question on rcgroups as to what value an LS should have in each scenario, or whether an LS value should even be permitted in all of the above scenarios. 

Moving on to other logic type conditions, using a source of switch SA gives weights of -100%, 0% and 100% - possibly not unreasonable for a 3 pos switch, and a quick test of VAR Range with a source of switch SA gives values of -10%, 0% and 10% which appears to be wrong. 

Thanks

**Comment by mawzthefinn** [comment]
-100 is the correct value for a false LS, as it matches the output of a 2-pos switch, and all other true/false implementations when used as a value. '0' is the midpoint value for switches, not the Off value

The +/-10% in VAR's is another case of the 10x bug, and needs addressing.

**Comment by bsongis-frsky** [comment]
@mawzthefinn are you able to replicate this issue?

**Comment by Jedsters** [comment]
I'm happy with -100% for physical switches, but why does an LS which has no mid-point need to have a false value of -100% too?

If an LS had an false value of 0% then it could be used in various places without the need for extra VARs etc. Similar could also then be extended to FS and Virtual switches in 1.6

My testing above was at 1.5.2 so if the 10x problem has been addresses since then it may have been fixed already - I was waiting for 1.5.5 before upgrading again. 
Thanks

**Comment by Dsrenger** [comment]
A LS is nothing else then a software version of physical switch.

Having it 0% and 100% is just inconsistent.

Additionally it potentionally screws already existing model files.

**Comment by mawzthefinn** [comment]
> I'm happy with -100% for physical switches, but why does an LS which has no mid-point need to have a false value of -100% too?
> 
> If an LS had an false value of 0% then it could be used in various places without the need for extra VARs etc. Similar could also then be extended to FS and Virtual switches in 1.6
> 
> My testing above was at 1.5.2 so if the 10x problem has been addresses since then it may have been fixed already - I was waiting for 1.5.5 before upgrading again. Thanks

Because if LS's are 0%, they're inconsistent with everything else in the OS, including all other true/false declarations.

Everywhere in the OS, if you have a two position value, true is 100% and false is -100%

0% is only available in a 3-position value or when using a VAR, weight/offset combo or Curve on the value.

**Comment by Jedsters** [comment]
Ah, fair enough then. Would have simplified some things, but never mind.

**Comment by mawzthefinn** [comment]
> @mawzthefinn are you able to replicate this issue?

Fixed in 1.5.4 based on my testing

**Comment by bsongis-frsky** [comment]
I think that I could add an option "Half range" for:
- 2-POS Switches
- Logic Switches

When they are used as a Source (not as a Switch).
It would allow a range [0%-100%] instead of [-100%:+100%], which in many case could be helpful

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8c021f82-ac0a-4b25-92e2-58103aa7a821)

New option "Half range" introduced in 1.5.6

**Comment by Jedsters** [comment]
Very clever. Thanks
