### ISSUE TITLE
[Feature Request] Model Screen Templates System

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#3807]
I always set up sometimes fairly involved sets of screens on my models that are equipped with telemetry, sometimes totaling 25+ Value widgets across 5-6 screens.  Many of these screens are very well established (such as my RSSI/VFR screens, which are the same on all of my models).  The process of setting up all of these screens takes quite some time to complete,   With every new model, the process of setting up all of these screens must be repeated.  While the typical response is often "just clone the model", this is often not practical, due to large differences in mixer, curve, logic switch, special function, and other configuration as the end result is often having to delete much of the configuration and re-do it anyway.  Plus, by cloning, you lose out on the model wizard, which has improved as Ethos has evolved and is now, generally, quite pleasant to use.

Having the ability to save a screen layout globally, including the widget type and configuration (e.g. Value, RSSI, Min, Graphs, etc), and then being able to load that saved layout would be very handy.  Because sensor names can be changed, you'd probably have to use the sensor ID etc to keep track so that if the sensor is named differently on the new model it still picks up the correct sensor.  If the sensor previously used is not detected, it can just set the widget type, as well as the value type (e.g. min or max or current) and allow the user to re-select the sensor later.

I honestly don't have any suggestions on how this could be implemented on a technical or UI level, but it'd be awesome to see in Ethos and would be a huge time-saver.  What do you all think?

**Comment by frobert0** [comment]
I would like it too
