### ISSUE TITLE
Impossible to create a relative altitude calculated sensor

### ISSUE THREAD

**Issue by amaury10** [FrSkyRC/ETHOS-Feedback-Community#3808]
Hello,

For the first time I flew a glider with an X18 radio and an FrSky telemetry system. I search for hours how to setup a relative altitude sensor from a variometer absolute altitude value.

When I use the reset feature of the sensor, the altitude come back to the absolute value. Flying in mountain, it's not relevant to read 1000m of altitude while your model is on the ground.

Can you add the possibility to 0 a sensor (adding an offset while pressing a button) ?

Regards,

Amaury.

**Comment by Skippydi** [comment]
Du kannst den Sensor unter Telemetrie und dort unter dem entsprechenden Sensor zurücksetzen
![bild](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/e210625a-cab6-4f20-81d4-84e98cbaa998)

**Comment by dwheeld** [comment]
I'm having the opposite problem. The elevation where I fly is near 1800 feet. My gps is showing around 0 when on the ground. How can I get it to show the correct elevation?

**Comment by strgaltdel** [comment]
Amaury, could yopu tell us what kind of sensor you are using?
(manufacturer/ model type)

" I search for hours how to setup a relative altitude sensor from a variometer absolute altitude value."
typically a vario is not able to report absolute values,
it will always reference to 0m at start

So i would say you have an "atypical sensor" which includes GPS Altitude
But the typical Ethos-GPS Sensor-impementation  reports the relative , and not the  absolute altitude , so it seems to be a very unique case you are reporting, maybe done within a non standard "telemetry id"

nevertheless, in case you have "really" a vario it should also report the relative altitude in form of an own sensor value.
Shure you can't detect or see one more Alt sensor ?

**Comment by amaury10** [comment]
Hello, the vario is integrated into a TW GR6 receiver

**Comment by mawzthefinn** [comment]
> Hello,
> 
> For the first time I flew a glider with an X18 radio and an FrSky telemetry system. I search for hours how to setup a relative altitude sensor from a variometer absolute altitude value.
> 
> When I use the reset feature of the sensor, the altitude come back to the absolute value. Flying in mountain, it's not relevant to read 1000m of altitude while your model is on the ground.
> 
> Can you add the possibility to 0 a sensor (adding an offset while pressing a button) ?
> 
> Regards,
> 
> Amaury.

Reset your telemetry before the flight begins to get relative altitude from the sensor. The reset zero's out the altimeter.

**Comment by amaury10** [comment]
I try to reset the sensor using a switch, it doesn't do anything
