### ISSUE TITLE
i think need a new function   |delta| = RPM1 - rpm2   or  Temp1 - temp2  for twins or twin cylinder engines

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3810]
i think need a new function   |delta| = RPM1 - rpm2   or  Temp1 - temp2  for twins or twin cylinder engines.  
   i have a twin turbines and would like to know if one is not running as well as the other.
   i have a twin cylinder engines and would like to know if one cylinder is running hotter than the other.

**Comment by mawzthefinn** [comment]
Calculated sensor should suffice for the RPM/Temp delta, so this should be a new Calculated sensor type, not a new special function

**Comment by williajgr** [comment]
That does seem to work except for one problem.  RPM only goes to 10000 rpm.  I need at least 140000. Some jets are even higher.  Thanks a bunch for the help.   JoeSent from my iPhoneOn Apr 8, 2024, at 9:52 AM, mawzthefinn ***@***.***> wrote:﻿
Calculated sensor should suffice for the RPM/Temp delta, so this should be a new Calculated sensor type, not a new special function

**Comment by williajgr** [comment]
Had trouble with the FrSky pressure sensor. For some reason when I use the calculated sensor it comes up with 217000 on the top line. But the pressure is correct on the bottom line.  Thanks for any help.      Joe Sent from my iPhoneOn Apr 8, 2024, at 3:52 PM, George Williams ***@***.***> wrote:﻿That does seem to work except for one problem.  RPM only goes to 10000 rpm.  I need at least 140000. Some jets are even higher.  Thanks a bunch for the help.   JoeSent from my iPhoneOn Apr 8, 2024, at 9:52 AM, mawzthefinn ***@***.***> wrote:﻿
Calculated sensor should suffice for the RPM/Temp delta, so this should be a new Calculated sensor type, not a new special function

**Comment by williajgr** [comment]
having trouble when I use  a custom sensor to give me delta rpm .  the max on a delta rpm is only 10000.    and i need more like 150000.  and the decimal isn't right.    also having trouble using a custom sensor to convert frskys pressure sensor to take out the 15 psi  it can't read / and use the psi value.
