### ISSUE TITLE
Why can't I program a trim in my mixer anymore since 1.5.3

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#3811]
Where did the extra trim go that you could add to the mixer that used to be in there?? we put it back please it's there pretty much since the beginning so it seems a bit silly to take it out now I really needed it at the field the other day and couldn't find it. Thanks in advance

**Comment by bsongis-frsky** [comment]
Trims are in Model / Trims.
It's a better place!

**Comment by builda1** [comment]
That's good
