### ISSUE TITLE
lua: form.clear() call in widget leads to stucked script

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3812]
it seems that a form.clear call (e.g. called from wakeup handler) leads into a stucked script,
paint, event handler etc.. are not triggered anymore

all i can see is, that after form was cleared and some new fields were built, the script stucks.
This occurs only  when registered as a widget.

running the same script as a systemTool all is running as intended

attached a demo,

as soon as you enable form.clear in line 135 the script stucks at start
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/a17608bf-fca6-49ae-a43c-2f7caf771ca8)

changing "runAswidget" into false will register the script as a system tool and all is fine
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/026808fa-dd99-4ed6-8f6d-3ee67f1c5433)

tested in sim 1.5.5

regards

[FClear.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14902162/FClear.zip)

**Comment by bsongis-frsky** [comment]
The script is not stucked, but the window height is reduced to 0, so nothing is visible on screen.
The fix is ready, released in 1.5.6
