### ISSUE TITLE
lua: no frame shift when form fields at the bottom of the screen are in focus (systemTool only)

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3813]
declaring a form with fields at the bottom of the screen works fine on widgets

a) (idle) screen
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/9665b953-4136-4a17-a0d0-ac1e3986ca72)

b) and now focus on a "bottom field"
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/9e0e20bb-7c7a-4b4f-9ceb-a859261ec197)

you can see the widget frame was shifted upwards, so the context menue is available AND the field is visible

no running same code as a system tool:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/fe489243-6311-4692-95ef-e12855c5fe48)

frame not shifted, so context menue builts an overlay and hides the field

regards
udo

**Comment by bsongis-frsky** [comment]
May I ask to prepare a small lua file which shows the issue for me? I will use it to fix the problem, and also I will include it in our non regression tests

**Comment by strgaltdel** [comment]
attached the lua shown above,
a prototype, actually X18 display layout only

it's configured as a tool script, so you should be able to reproduce the issue out of the box by clicking on a "bottom field"

by changing "runaswidget" (first line) into true, it will run as a widget (and the issue will  "disappear"):

`local runAswidget = false` 

btw,
just installed sim 1.5.6
much thanks for quick solving of the "form.clear" issue,
and making the Sim restart more stable
 

[xVar.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14928941/xVar.zip)

**Comment by bsongis-frsky** [comment]
you were quick, I will try to work on it today

**Comment by bsongis-frsky** [comment]
We need to work together with the next nightlies
The example now works correctly (a fix is needed), but not your script

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/038986e4-881c-4caa-a40f-f2f77275b691)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/bebd544e-aff0-4cfe-85e2-899c06faebdd)

**Comment by strgaltdel** [comment]
hmmm strange,

I have reduced the script, compacted to reproduce issue,
so the code is lean

will wait for the nightlies


[frmTst2.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14933467/frmTst2.zip)

**Comment by bsongis-frsky** [comment]
Take care, it won't be included in current nightlies, but the next ones

**Comment by bsongis-frsky** [comment]
Too bad, the nightlies are still not ready, I have worked too late yesterday and introduced a typo which made it fail

**Comment by strgaltdel** [comment]
... take a break,
get some sleep,
play with the kids at the weekend 
and with the new proAW toy
and maybe get some time for the hobby ...

no need to rush
you've done enough great things in the last weeks !


![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/0c55847d-8cc6-4216-a4df-1007e17d4173)

**Comment by bsongis-frsky** [comment]
Thanks!
The nightlies will run again tonight. But take care there is a big refactoring hidden behind the Switches and their Edge option.

**Comment by bsongis-frsky** [comment]
Nightlies are online. And Lua examples are updated accordingly.

**Comment by strgaltdel** [comment]
Hi Bertrand,

works perfectly on the sim !
So i will close the issue

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/fa18f2f9-1a7d-406b-ba95-5eee5c58a126)


Thank you very much and have a more relaxed time !

Udo

**Comment by strgaltdel** [comment]
sorry, was too quick,
 in a hurry because of problkems in the company and so i mixed up tools vs widget behavior
parallel tasking is not as good as it was years before, getting older ))-:

should have done all tests (the magic word was "regression test", wasn't it ?  (-;  )

we have the same "issue" on system tools, which it was at the beginning
in widget mode is ok

no shifting as system tool (1.5.7 todays nightly):
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/b242e21a-b7cf-475c-b0e2-6d9478b7737d)

**Comment by bsongis-frsky** [comment]
Do you confirm that my examples do work correctly?

**Comment by strgaltdel** [comment]
did some tests

(1) your lua example did work in the latest nightlies (not in 1.5.6, last lines not shown)

(2) main difference between yours & my application is, that your lua generates the form within create handler, i do in wakeup

So i created my "first" page in create handler too which resulted in a correct behaviour
presumably form.create(which is not used in create handler) or the creation from wakeup itself is causing the issue ?

**Comment by bsongis-frsky** [comment]
Would you confirm that when you just add the "create" method to your script (even if the method is empty), there is no more problem?

**Comment by bsongis-frsky** [comment]
Fixed too, it will be in the 1.5.7 pre-release / release
