### ISSUE TITLE
Suite 1.5.4 Suite unable to detect the radio ( X20S )

### ISSUE THREAD

**Issue by NorbertHeli** [FrSkyRC/ETHOS-Feedback-Community#3814]
First time for  short ( ~ 30 sec ) the suite see the radio. It shows what is up to date or can be updated. Then it lost the connection and is unable to see the radio.
The suite started the second time immuduatly can´t see the radio

[main-20240408.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14907859/main-20240408.log)

**Comment by Nicholas-Luoyi** [comment]
Thanks. But I still cannot see the problem. Would you please help to place the file below into your directory: C:\Program Files\Ethos Suite 1.5\Ethos Suite\resources\. And then run the Suite again until you connect your radio. Then post the main-.log one more time?
[settings.json](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14912097/settings.json)

**Comment by NorbertHeli** [comment]
Same as yesterday - the suite can´t see the tx. 
[main-20240409.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14914666/main-20240409.log)

![dir](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/49641e48-9f13-40b0-9ce2-f65ff935fb6d)

**Comment by Nicholas-Luoyi** [comment]
This one is useful

**Comment by NorbertHeli** [comment]
Is there a newer Suite?
