### ISSUE TITLE
sorry I made a suggestion.

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#3815]
Deleted

**Comment by ETHOSWarrier** [comment]
I agree totally.I have 30 plus Moulded gliders and planes with complex setups too.Most of my gliders use the Mike Shellim templates and as I was curious with the new features of 1.5.x  so I tested a few models with a buddy and a spare transmitter.This was a disaster,all my existing setups are on 1.4.17 and work perfectly but I could be stuck on that version for the next 10yrs!
Now...... I moved from futaba 3 yrs ago or so and embraced the Frsky way with ETHOS at the forefront and enjoyed the telemetry features and simplicity of ETHOS and most importantly where it could lead us in the future.

Now After this 1.5.x so called upgrade...my future is stuck on 1.4.17 unless any future upgrades are  backwards compatible with all my setups and just extra features are added.Now before I hear everyone say "just leave the upgrade alone"...well that's not why I originally chose the Frsky route because of what it can do today...but also what it can do in the future...That was my dream but its looking a bit shaky recently.

I do appreciate everyone's work in developing this ETHOS but care has to be taken not to go too far and make it a nightmare for us loyal existing users.I am at the forefront of bringing Frsky and ETHOS to our club and many have followed but i feel let down now as I explain to my buddys..this could be where we stop: 1.4.17......such a shame and I hope this so called obsession with equalling  OpenTx is held at bay ...Ethos up to 1.4.17 is already 100 times more useable than Opentx for your average club flier....and I agree with the above again...its going to frighten away more newbies than recruit opentx users across if we are not careful....CT

**Comment by builda1** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/60620767/43884cb4-6916-4c9d-bab5-0d77d38cd093)


Here is an example of one of the hundreds of corruptions that was done in the models on my radios. You tell me why would I set a logical switch up to read the battery with the Rudder? Obviously I didn't, but I had exactly the same corruption on both radios and the same models in most cases. Only reason I updated was because I wanted to be able to send a model via Bluetooth from one radio to another-that's it. Instead I've got this monster that personally I'm not happy with and if I wanted something that was running "OpenTX" I would get rid of the tens of thousands of dollars worth of radio gear I've got and save myself a fortune and go and get a cheap radiomaster Tx16 or whatever it's called and buy myself $10 receivers. There's nothing wrong with developing a product but just like the other fellow has said it's almost as if there's this big drive to make Ethos "OpenTX 2.0" and to be honest it's enough to put people off wanting to touch the system because it's getting too complex-not to mention when it starts destroying peoples set ups. I honestly do not see the point of putting the receivers in the firmware of the radio especially with a company like Frsky who are constantly changing them every four months with a new series. if I could get a new version of 1.4.17 that had the functionality to transmit models between radios via Bluetooth (which was the only reason I updated) I would be perfectly happy and never need to update again however that's not the case which is why I make the suggestion @bsongis-frsky perhaps we do a "standard" version (none of the receivers added, but with the Bluetooth functionality that has been added in the recent updates and the occasional minor tweak that is necessary), and "ADVANCED" (for everybody that wants OpenTX 2.0 on steroids and only has to worry about one or two aircraft) 

I apologise for my blatant cursing initially however if you had spent as much time as I did finding out how much your radio had been screwed up only to get to the point where it's easier to roll it back as I had yesterday after losing a model as well because my battery telemetry wasn't working properly (unbeknown to me thanks to the corruption by the update) you might appreciate why I was a bit testy when I raised this issue. I definitely think something needs to be done because if the future for people like myself stops at 1.4.17 with the only answer being "just dont update it",  then I just as well go and buy Futaba and it's not going to do Frsky any favours at all because it's going to drive people away just like OpenTX did. 

Again I thank you @bsongis @bsongis-frsky and your team for your continued hard work to improve things but this latest jump has really pushed it way beyond where it needs to go IMO-when we get to the stage that we are nitpicking the way we set things up to justify an update and in the process screwing up peoples setup because the update version is different that's the time to stop doing updates! Would like to see what others think it's nice to know I'm not the only one that has been affected by this. Cheers 🙂

**Comment by bsongis-frsky** [comment]
Your setup should not be destroyed.
Would you please attach the backup model where you have one of those conversion issues (Lipo Warn / Rudder)?

**Comment by bsongis-frsky** [comment]
Should I close the 326 open issues (which are 99% requests) and tell the user, that ... sorry we stop there?

Rather than taking conclusions so quickly, perhaps you could first open an issue with a full description of your problem and we try first to find a solution (perhaps a bug fix)?

I understand you have had an issue with the conversion (I am almost sure that many of your models use the same template and the same issue raises everywhere, making you upset).

**Comment by builda1** [comment]
Hi @bsongis-frsky thanks first off for the reply, as stated before i hold great respect for all that you do for the community because i do not know of anyone else out there trying to please everyone with requests. 

With regard to my issue:
1) i have gone back to 1.4.17 (and even that wasn't perfect with the odd thing in the wrong place (im just doing the last 10 models at the moment-checking and verifying all settings and making 100% correct- then I will do another backup. 

2)when i get the last one finished I am happy to Email you the following zip files for de-bugging purposes (i DO NOT expect you to fix every single corrupted issue in the 1.5.4 conversion, am sending it just to help you with Debugging ok!

A) my ORIGINAL zip of 1.4.17
B) zip of 1.5.4 from my X18SE (identical setups, just diff radio-i use all the same buttons/switches etc on both my X20S and X18SE) so you can see the mess its made PARTLY due to change in firmware architecture and how those changes affected certain specific mixes (mostly trim mix due to it being removed from the mixer),and also went further and messed up/wiped out logical switches and special functions. 

Reasons i updated (before anyone asks:

-Wanted latest stable update with the bluetooth functionality so i can set up a plane one time then Bluetooth the model onto my second radio.

-Never really had any major issues in the past with any updates (normally i leave it 2-4 weeks to see if any bugs but this time i didnt. 

As for complexity, It does concern me greatly how complex ETHOS is getting, especially when i have well over US$10k in radio gear and   With 40 models in the hangar "a small change" for the guys with less than 10 models is a nuisance but no huge issue, but when you rely on it for over 30 models a "small pain" becomes a huge issue as I am sure you appriciate. It was an expensive shift for me from ACCST to ARCHER/TANDEM/TWIN and it took Petr Stasek (i think you know him) quite a while to talk me round, and i LOVED the ease compared to OTX, everything was so simple and 1/4 of the work. Now as we get closer to something as complex as its getting (as I Showed Petr) something i can do in 1.4.17 cant be done in the same way in 1.5.x (in fact I can't recreate the function in mind in 1.5.x the same as i can create it up to 1.4.17). 

If you can Email me at Johnnyspangle@hotmail.com I will send you a list too along with the 3 zip files so you can see what i cant seem to do anymore (i am sure its possible but with 40 models its a major change for me) 

Thanks again @bsongis-frsky and again I truly thank you for all your hard work, I am an engineer not a programmer like you so i couldnt even pretend to do your job, all the Devs work their asses off and for that I'm grateful but I do still feel it might be worth considering having a "basic" and "advanced" version in tandem but only if it's not a major headache of course, because not everybody needs all of the features and of course it needs to be kept relatively simple for Frsky to sell radios too. 

Thanks and I will await your email so I can send you the zip files and you can start having a look at your leisure ok👍

**Comment by bsongis-frsky** [comment]
I only need one model to understand what went wrong with the conversion which should have been automatically done.

Then we can discuss about the other points, where Ethos 1.5 has become more complex than 1.4 is something I really doubt. We have added more functions, but you are not forced to use them and the rest should be almost the same in both branches.

**Comment by bsongis-frsky** [comment]
Issue #3644 from the same user remained unanswered

**Comment by bsongis-frsky** [comment]
To be constructive you should attach a model file to your issues!

**Comment by builda1** [comment]
> I only need one model to understand what went wrong with the conversion which should have been automatically done.
> 
> 
> 
> Then we can discuss about the other points, where Ethos 1.5 has become more complex than 1.4 is something I really doubt. We have added more functions, but you are not forced to use them and the rest should be almost the same in both branches.

Forget it @bsongis-frsky you know what, I might ask you maybe two times a year, sometimes not even that, if I have a problem and yet this is the way I get spoken to. I will remember to tell them at Frsky when I get rid of my radio gear the reason I got rid of it was because of The response I got to a serious question and the fact I barely ask anyone for help and it is "Implied" that I'm only happy when it's something I think is a good idea which is complete bullshit. You tell me it should not have destroyed my complete set up, I could have posted 1000+ photos of the damage it did to the model files, it messed up everything but I'm just full of shit and don't know what I'm talking about so don't pay any attention. I will leave you to deal with the other person who seemed to report a similar issue maybe he's more patient with being spoken to like a two-year-old then I am but I don't think so because he hasn't been using the platform anywhere near as long as me but what would I know🤷‍♂️

**Comment by bsongis-frsky** [comment]
I don't ask for photos. I need the original file which was badly converted, so that I can reproduce the problem here and fix it. So far nobody has reported such a problem (a logic switch dealing with Telemetry in 1.4.X which now deals with Rudder in 1.5.X).

Also we have put in place non regression tests for this kind of conversion issue, to avoid it happens. So we need some real input (not photos) to be efficient.

For the rest, sorry if the words are not right, English is not our first language.

**Comment by builda1** [comment]
With All due respect Bertrand I offer to send you the complete zip file because every single model is corrupted but not every single model is corrupted exactly the same way, which is why I offered to send you complete zip file because you would not be able to tell entire problem From just one model file, but do not worry I will not bother. No need to apologise for not being your first language, I do not take very kindly to insults especially when I come to you with a problem and I am treated like a two-year-old child! I did not send model file before for my other radio because 1) I only use it for simulator, and 2) @mawzthefinn said that he had done the conversion as well on his radio the same without any issues so I did not see the need to waste your time looking at something that was quite possibly bad connection or something. Forgive me for wasting your time-petr always says to me when I have a problem to come here and I would rather sort things out myself than come here usually it really is last resort for me to come here but when I do and I give you detailed information.... honestly don't worry about it because you would need more than one file and it will take too much of your time. I will have to evaluate if I stay with the radio or if I go to Futaba. Only reason I stick with Frsky is because of friends in the company, but if getting help is a big problem then maybe not such a good idea I use that platform. Again thank you for your hard work that you have done (not many people seem to say that but I do every time) but I think this issue is finished. Enjoy your day sorry for all the trouble

**Comment by bsongis-frsky** [comment]
> With All due respect Bertrand I offer to send you the complete zip file

Please do, I will analyze it as I do each time someone reports a conversion issue. Please start with the model with the Logic Switch converted from Telemetry to Rudder. This one sounds me very very strange!

**Comment by builda1** [comment]
Again @bsongis I thank you for the Offer to now look at a Zip file of the Radio but must Kindly decline your offer of assistance. Only 1 other person seemed to have the same issue as me and thought the same so the Majority must have no issues, so bearing this in mind now I have a Plan to address the issue and try to convert it again (just one of my Radios initially), if it then fails again The Radio(s) will stay 1.4 branch now and no longer be updated (by me) as that does everything I "NEED" while I evaluate my next move (move to Futaba or stay in 1.4 land forever). Have to admit On the positive side I AM Glad I had not ordered the new X20S Aerowing last week now that I was looking at buying to replace my X20S whilst not certain about the Future. Thanks again for all your hard work over the years.

**Comment by builda1** [comment]
> > With All due respect Bertrand I offer to send you the complete zip file
> 
> 
> 
> Please do, I will analyze it as I do each time someone reports a conversion issue. Please start with the model with the Logic Switch converted from Telemetry to Rudder. This one sounds me very very strange!

All sorted now @bsongis ,thanks to you and the team for putting out a good manual it made life a lot easier. I AM not worried now if it corrupts again as I know how to fix it. It did take all week but at least I learned a lot. 

Regarding the new location for the "Trim" I will agree yes it does make more sense having it there BUT i still think it would not have hurt to leave the mix in the Mix menu-yes I had to set up the Trim and telemetry alert buttons again on 40 models (I wouldn't have had to if you had just left the trim mix in the mix menu), it doesn't matter though because I got to really go through 1.5.4 quite deeply. My X18SE is perfect again now and with 1.5.4 on, but my X20S has 1.4.17 on (and is also perfect again),so I will Update that over the next couple of days since I have not been sleeping. 

Keep up the good work-I will always thank someone for good work that I benefit from (and NEVER take it for granted like some might do out there-of course I could be wrong, but thanks anyway). 

You will NEVER get a request from me so thats one less person to think about. 

Cheers

**Comment by bsongis-frsky** [comment]
NEVER say NEVER :)

**Comment by builda1** [comment]
On the contrary @bsongis-frsky I hardly ever ask you as it is, I think I've only ever asked a question to you maybe five times maximum the other times Maws has been the one I have spoken to but in any case and all the years I have been registered as on github in some capacity I think I have only ever asked eight or nine maximum questions all up. I don't bother reporting issues if I come across any normally-I leave that to everybody else, I AM not going to Report anything,let alone suggest something of the programmers either, I will usually find my own solution before I resort to asking someone but thats a last resort, one that has been confirmed now. 

Keep up the good work-not on my account though, but for everyone asking you to add more features-so yes, "Never" will REALLY mean "Never" Bertrand lol, I will buy a complete new system before I lower myself to Ask anyone for help again now, let alone make any suggestions again (as I told my friends at Frsky too while I was talking with them this week) - I definitely wont get a new X20 Pro Aerowing now after all this carry on this week, cause I AM not so sure I Will stick with Frsky. Yes I will for the time being, but its no good not having any support that treats you with respect, let alone not having any support at all, hence Futaba (or Jeti) looks good right now. Time will tell. All the best for the future👍
