### ISSUE TITLE
special functions override

### ISSUE THREAD

**Issue by Tia2022** [FrSkyRC/ETHOS-Feedback-Community#3816]
Hello,

today I received an td r10 receiver. I have the latest firmware on it, also on my x20s. First it did bind and register but servo's didn't do anything. I deleted the model and made an new one and now everything is working. I made special functions for the model (sounds on switches) but now thes functions are on all of my models... also some switches I always use for every model plays the sounds 2 times for now instead of 1 time.  someone could help me?

**Comment by mawzthefinn** [comment]
You've set those Special Functions as global. Disable Global in each Special Function to make them only apply to the selected model

**Comment by mawzthefinn** [comment]
CLosing as answer provided
