### ISSUE TITLE
Suite update button seems not working

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#3817]
I found this issue in Suite 1.5.2 and now again in 1.5.4. In the Suite Setting tab, the update suite seems it's not working.
I am running W11, and downloaded the new version from github, and ran the exe file. It is not a big deal, but if it is there it would be nice to be able to use it.

**Comment by Nicholas-Luoyi** [comment]
Should be the result of spliting the Suite release from ETHOS release and not setting the Suite release as the latest in this repo.

**Comment by Richrfl** [comment]
Sorry, Nick. I may be a bit sleepy but I don't understand your comment. Could you please clarify? I am not sure if you meant that I did something wrong in the procedure to update the Suite.

**Comment by Nicholas-Luoyi** [comment]
No. It's the problem on our side

**Comment by Richrfl** [comment]
OK. Thank you

**Comment by Nicholas-Luoyi** [comment]
Merge to #3822
