### ISSUE TITLE
Bluetooth volume problem X20S

### ISSUE THREAD

**Issue by A3Brand** [FrSkyRC/ETHOS-Feedback-Community#3818]
Bluetooth volume problem X20S

The bluetooth volume is minimal and regulates along with the main volume and vario.
The sound on the phone jack and through the transmitter speaker is fine. Also through the manual I can't figure it out, and the volume in the Bluetooth menu can't be adjusted / set.
It would be nice that in that menu the volume level can be adjusted.
Are there more users with this problem?
Perhaps this wish can be included in the next firmware update ?

Bluetooth-Lautstärke problem X20S

Die Bluetooth-Lautstärke ist minimal und steuert zusammen mit der Hauptlautstärke und dem Vario.

Der Ton auf der Telefonbuchse und durch den Sender Lautsprecher ist in Ordnung. Selbst durch das Handbuch kann ich es nicht herausfinden, und die Lautstärke im Bluetooth-Menü kann nicht angepasst / eingestellt werden.

Es wäre schön, wenn die Lautstärke in diesem Menü eingestellt werden könnte.

Gibt es noch mehr Benutzer mit diesem Problem?

Vielleicht kann dieser Wunsch in das nächste Firmware-Update aufgenommen werden?

**Comment by frobert0** [comment]
I also have a big difference between speakers and Bluetooth

**Comment by Dsrenger** [comment]
Have the same "problem"

My bluetooth in ears headphones are much less loud than the transmitter speakers or a cable headphones.

If it is somehow possible to make bluetooth headphones louder on the Ethos software side i would appreciate it.

**Comment by ilioSS53** [comment]
Also noticed that volume is low, all seems to working as it should.
Received this measage also from a fellow club member.

**Comment by A3Brand** [comment]
Glad to hear it!

Op ma 15 apr 2024 20:37 schreef ilioSS53 ***@***.***>:

**Comment by Dsrenger** [comment]
Just as side note

In my case it shouldn't be the quality of the Bluetooth headphones.
The same pair of headphones connected to the smartphone can be extremely loud (using Spotify)

**Comment by ilioSS53** [comment]
This also my experience.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ahvink** [comment]
Same here......volume is too low on bluetooth.

**Comment by ilioSS53** [comment]
Hello , version 1.5.7 loaded.

I,am realy confused.
 Looking for the bluetooth to test the volume (in version 1.5.7 )on bluetooth from the vario I can not find the bluetooth apart from the trainer setup with bluetooth.
Is the bluetooth disappearred?

Or howe to find bluetooth for testing the volume for the vario. Strange earlies no problem to find.

Like to hear.
Regards
Theo

**Comment by ilioSS53** [comment]
Theo here again,
My fould not on the x18 bluetooth.
Tested on x20s after reading the faboulus manual RTFM but sound volume still on a disapointed low level in 1.5.7

Hope for the best

**Comment by iurycarlos** [comment]
same

**Comment by iurycarlos** [comment]
Yeah, i tried in at least 5 different devices. The sound is disappointing.

**Comment by iurycarlos** [comment]
I suppose it is due to legal restrictions of audio volume for earpads.
Maybe would be possible to add a checkbox or something like that to allow original file volume on bluetooth, since this feature is not always used for earpads. I, for example, use it to run sounds on a robot and it is very disappointing to work with too low volume. I used a big amplifier, adjusted the max gain in files using Audacity and still, not very good output.

**Comment by paulusbrand** [comment]
@bsongis-frsky Can you comment on this, I have the same problem with my X20S. Bluetooth is a nice feature but right now it's not often usable, a little noise from other pilots makes the sounds hard to hear. Noise cancelling is not really an option safety wise.
Is the bluetooth module a separate module like TTS where you have no control over?
Let me know if there is anything you want me to test.

**Comment by iurycarlos** [comment]
Still bad even with recent updates...

**Comment by ilioSS53** [comment]
Still the same low volume. Even no reaction from FrSKY?

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by A3Brand** [comment]
Voor mij is bluetooth een must, aangezien ik slechhorend ben. 
Ik heb speciaal de X20S daarvoor gekocht.
