### ISSUE TITLE
VAR Value incorrect when Values is numeric and there is an Action Add.

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#3819]
Create a new VAR10
Range: -500% 500%
set Value to 100%
Add Actions: Always on, Add(+), 1 (any value will do)
Value increases to 500% at about 2% per second.
Any negative value decreases Value until reaches -500%
Note: If the "Values" is a "Source" , like a switch or another Var, then the resultant Value is correct.

**Comment by fhpage** [comment]
This is with 1.5.5

**Comment by bsongis-frsky** [comment]
Merged into #3821 with all the next Vars enhancements
