### ISSUE TITLE
widget value flightmode

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#382]
It is not possible to show the current Flightmode in the widget. You can set a flightmode as a value, but this does not make sense.To show a flightmode on the screen? why? It makes more sense to show the current active flightmode.Ok when LUA will be available i can make my own widgets because so far the widgets aren't that great.

**Comment by bsongis-frsky** [comment]
We should have one more category for "Flight Value", like "System Value". I would see the "Flight Mode" there, written in plain text on the Widget
