### ISSUE TITLE
X18 updated to latest version. Locked up 

### ISSUE THREAD

**Issue by tripaceer** [FrSkyRC/ETHOS-Feedback-Community#3820]
This afternoon at 3:45 updated to latest version from a Clean X18. Meaning I had reformatted disk. Then restored last back up (1.4.17) At this point tried to upgrade to lates 1.5.4  No error message but said I needed to remove cable and shut down manually and restart ,  then plug in cable, then go back into Ethos Suite.
Radio would not shut down   Had to pull power,  plugged power cable back in but now radio will not power   Radio button lights as long as I hold button down 
HELP

**Comment by strgaltdel** [comment]
Google is your friend,

Update notes, when coming from 1.4.x:

https://www.rcgroups.com/forums/showthread.php?4513483-Ethos-1-5-Upgrade-notes-and-typical-issues-after-upgrade

pretty sure you didn't update bootloader at first,
so follow the troubleshooting steps/links  mentioned in

**"1) a very common effect is that the transmitter does not start after an update, only the bootloader can be called**

**Comment by tripaceer** [comment]
Thank you Very much for this information. It is now up and running on 1.4.17.I hardly ever go over to “RC Groups”  so had not seen this article Did read FrSky Steve article on Facebook.  As things become more useful for ME,  I will migrate up. I need the stabilization working for me,  Medical issues Blind in one eye.  I have been using FrSky products since they made RF modules and D8 receivers Again Thank you Paul Edmunds Sent from my iPadOn Apr 11, 2024, at 1:15 AM, Udo ***@***.***> wrote:﻿
Google is your friend,
Update notes, coming from 1.4.x:
https://www.rcgroups.com/forums/showthread.php?4513483-Ethos-1-5-Upgrade-notes-and-typical-issues-after-upgrade
pretty sure you didn't update bootloader at first,
so follow the troubleshooting steps/links  mentioned in
"1) a very common effect is that the transmitter does not start after an update, only the bootloader can be called

**Comment by strgaltdel** [comment]
Glad it worked for you,
remember to ensure to have the newest bootloader when updating to 1.5 next time

regards

**Comment by tripaceer** [comment]
Well   I guess I need your help again 

I purchased an X18 when they first were offered   That is the one I needed help with 

Now just a month ago I Purchased an X-18SE  just could not read the other screen in Daylight 

I always back up my Radios   so what I did was use the Backup for the Early PLAIN X18 to Restore my NEW X18SE  it gave me a warning when I did but since they were basically the same I pushed ahead and did it 

Well this morning I tried to Register and Bind an SR6 Rx and when I hit Register its ALL GRAYED OUT and says its waiting for RX   Both Registration IDs are the SAME.  What can I do to fix this???

Bye the  way updated to 1.5.6 and when you put in a New Aircraft SR6 is NOT in the list of Stabilized RX.  There is an SR6 min listed but not just plain SR6   Archer 

 

Paul Edmunds
