### ISSUE TITLE
Ethos Suite issues

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#3822]
I have received a new radio, X20PRO-AW. Not a prototype, but a production one, batteries included etc.
It will be used for flying, not debugging (well ...).

So, today I am in the end-user shoes ;)

- [x] I have an old Ethos Suite 1.5.2, it doesn't propose to update automatically, perhaps it's OK, but to be sure I go inside Others / Suite Settings and press "CHECK FOR UPDATE". The button does nothing. I would expect it says to me that it is up to date? Well there is Ethos Suite 1.5.4 on the github website in the releases section... I will do the job manually
   #3817 

- [x] I have had no issue during the upgrade, but I think that once firmware.bin is copied to the Nand, it should be read again by Suite to ensure it is correctly copied, before flashing it (or perhaps we should add a CRC somewhere that the bootloader would check before messing with the radio)
   #3791

- [x] "START / STOP DEBUG" mode is completely unuseable. Ethos Suite freezes after max 2 switches. I see no valuable trace in the logs directory

**Comment by bsongis-frsky** [comment]
It seems to me that the URL has a problem
1.5.4 is an Ethos release, not Ethos Suite

`2024-04-11T10:36:06.110Z ERROR Error: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.5.4/latest.yml): HttpError: 404 
"method: GET url: https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.5.4/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Thu, 11 Apr 2024 10:36:06 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "F370:2944CA:530173F:541C2A3:6617BD15"
}
`

**Comment by Nicholas-Luoyi** [comment]
All of the fix should be included in next release. I think it should be Suite 1.5.5
