### ISSUE TITLE
Option "Half source" 

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3823]
Option "Half source" introduced when using a 2-POS Switch or a Logic Switch as a source works only with LS not with 2 pos Switch

Ethos 1.5.6
X20s

**Comment by bsongis-frsky** [comment]
It doesn't work? Or it is not proposed?

**Comment by Devil-IdT** [comment]
![Screenshot 2024-04-11 214029](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/64803366/c2412d77-5734-4d2b-897a-06b013402362)
![Screenshot 2024-04-11 214351](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/64803366/fca07c04-08d9-4e98-9c10-152d2acf155e)
On my X10S it is only proposed for logical switches, not 2 pos switches.

**Comment by bsongis-frsky** [comment]
So ... no bug if it is not proposed :)

**Comment by bsongis-frsky** [comment]
I will change the release note, today it's only possible on logic switches

**Comment by bsongis-frsky** [comment]
I will be possible to do in the next nightlies

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6bf89d6b-977a-42f3-9c47-05796b00c61b)
