### ISSUE TITLE
problems with calculated sensors

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3826]
Having trouble when I use a custom sensor to give me delta rpm . The max on a delta rpm is only 10000. and i need more like 150000. and the decimal isn't right.   Also having trouble using a custom sensor to convert frskys pressure sensor to take out the 15 psi it can't read / and use the psi value.

turbines run form 25k to about 160k  if one is idling and the other is at full throttle delta should be 135k.

**Comment by aviat40** [comment]
we don't understand the problem
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/27886942/6fabb65b-105d-45f6-a22d-bc45df428fa6)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/27886942/0524bae0-15c7-42e4-964f-ec9058bd8c8d)

both can be more then 10000...

**Comment by williajgr** [comment]
i will send a picture
![IMG_2617](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56521075/3652a517-db9a-482a-8749-5696b4aa7846)

**Comment by aviat40** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/27886942/7e063097-6562-4f66-a2c7-f71a1ed5c6fa)

Tested with the lastest nightly

**Comment by williajgr** [comment]
will this be in 1.5.7?
