### ISSUE TITLE
"Forms" widgets: when scrolling through the fields, at the end the focus jumps to the next widget /home page 

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3828]
I have found a strange behavior in Forms,
I'm not sure if it's intentional or a bug

When "scrolling" through the fields of the widget, Ethos jumps to the next widget.
In case it's the last widget on the page, and you have multiple homepages defined, Ethos jumps to the next screen.
I would have expected the focus to jump back to the first field on the same screen (loop within the same widget)

vice versa,
Set the focus on another widget (e.g. to enter config handler) and scroll
the focus "scrolls" through the widgets, but when you enter the form widget, it jumps into the fields
I would have expected the focus to jump to the "full widget" so you can trigger the config menu.

Thinking about i tried the 1.5.6 X10 sim
On horus series transmitters, you wouldn't be able to enter widget config menues of these widgets which are using fields, directly from home screens because of this.
you'll have to enter the telemetry button to enter the corrrsponding widget menues

As said, maybe intentional for other reasons
at least a minor issue..
have attached a simple template (which uses the widget-form demoscript from git)

scroll further and you'll jump to next widget
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/31147b31-86f5-4448-8380-f50623096e79)
[tstfocus.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14955878/tstfocus.zip)

(tested with 1.5.6 )

**Comment by bsongis-frsky** [comment]
Yes it is intentional. So that the navigation is not broken by default!
