### ISSUE TITLE
LUA circuit receiver AIL3, ELE3  and RUD4 cannot be configured

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3829]
Hello, 
In the LUA SXR Stable, channels 7, 8 and 9 are not available on page 2. This means that AIL3, ELE3 and RUD4 are missing. This means that they cannot be set to AUX and are constantly occupied by the gyro.  This should be changed as soon as possible.
Thank you for your help
Wolfgang

**Comment by mawzthefinn** [comment]
They are disabled by setting the Stabilization to Off on Page 2. 

The new stabilizers function as two stab sets, with the base 3 channels enabled with the set, then the second AIL and ELE channel of the set being independently selectable as on/off. Each page's settings are independent, so turning stabilization off on page 2 does not affect the first stab set at all (and same for wing/tail type settings).

**Comment by Wolepo** [comment]
However, it is not possible to deactivate CH7, 8 and 9 individually. According to your description, this would only be possible as a whole.

**Comment by mawzthefinn** [comment]
> However, it is not possible to deactivate CH7, 8 and 9 individually. According to your description, this would only be possible as a whole.

That is correct, same as it's not possible to de-activate ch1,2 & 4 individually. 

Two stab sets, each functions the same way.

**Comment by Wolepo** [comment]
4 ailerons and one elevator can be considered normal. The remaining channels are then lost for other purposes.

**Comment by mawzthefinn** [comment]
> 4 ailerons and one elevator can be considered normal. The remaining channels are then lost for other purposes.

The channels are lost, but the ports/pins are not. You have 24ch to play with and very few applications use all 24ch. 

Only RF channel mapping is consumed with the stabilizer, you can remap higher channels (say 16/17 or 19/20) to ports 8 & 9, or if using a redundant receiver on Port1, then you remap ch1-7 to ports 2-8 and put ch16 or 19 on port 9.

**Comment by mawzthefinn** [comment]
As a note - I do want this changed, but it's a receiver firmware limitation, not an ETHOS or Lua limitation. Until the receivers support per-channel stabilization configuration for all channels, ETHOS and the Lua are limited to the current presentation

**Comment by Wolepo** [comment]
I realise that the receiver FW and the LUAs have to be adapted accordingly. Just wanted to report the discrepancies. 
Thank you
