### ISSUE TITLE
Log Viewer built into Ethos

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#383]
May I suggest that the Log Viewer get built into Ethos? This an enhancement that I beleive would help pilots worldwide do debug their aircraft at the field without having a PC on hand. By just selecting the log file, we could see if we have any issues within minutes. Takes the cumbersom out of removing the SD Card or bringing a PC to the field.

**Comment by loetefix** [comment]
I think its part of  https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/284
