### ISSUE TITLE
1.5.6 cross trims and flight modes

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#3832]
I do hope this is a false alarm, however decided to post as it could be critical.
Model set up (and tested to work properly) in 1.5.4.
3 flight modes (normal, take-off, landing)
Cross trims (I.e. elevator ch managed by throttle trim)
Each trim except elevator (which is now throttle channel) are in custom mode:
- Normal - default
- take-off- normal + offset
- landing - take-off + offset
All works as expected in 1.5.4. Say 0 trim in  normal, +2 clicks in take-off mode , + another 2 in landing. So getting perfect 0-2-4 sequence in all directions judging by Outputs screen.

Opened the same model after flashing 1.5.6 and instead of 0--2-4 getting random values ie 0-8-4. Differs depending on stick used, number of clicks etc. Couldn't figure the logic.
Created new model from scratch, same symptoms.
‐--------------
Now , when I stopped using cross trims, ie configured default mapping back, ie ele stick linked to default ele trim (mode 2 if it matters), everything works as expected. As soon as I configure criss trim,  everything goes haywire.

My apologies if I'm missing something obvious and it's my lack of experience but decided to post anyway.

**Comment by bsongis-frsky** [comment]
Are you really sure it works correctly in 1.5.4 and not in 1.5.6? It seems strange to me, there is no change in this area in 1.5.6!

**Comment by Alex00101** [comment]
I was stupid enough not to make a backup before flashing 1.5.4 but I am
positive it was working properly. I tested that multiple times as I wanted
this model to be a template.

Again apologies if I'm totally wrong about this.

**Comment by Alex00101** [comment]
It's X20Pro AW mode 2 if it matters

Update. Looks like I've managed to get it working equally on 1 5.4 and  on 1.5.6 but only by creating a new model from scratch , carefully setting all trims to custom (except T5 and 6) and only last setting the cross trim. Any deviation from that order seems to be causing issues.
I'll keep testing perhaps I can find a steady way of reproducing. Please feel free to close and I apologise for a potentially false alarm but TBH it feels like there something there.

**Comment by Alex00101** [comment]
Think I've figured it out, slightly confusing transition of trims assignment after crosstrim is configured.
