### ISSUE TITLE
Ethos Suite

### ISSUE THREAD

**Issue by ianshpprd** [FrSkyRC/ETHOS-Feedback-Community#3835]
I am trying to get Ethos Suite on to my macOS Big Sur Version 11.7.10 and it comes up this waring, (attached). Is there anyway around this please. In case you can't see it, it say 'Ethos Suite cannot be opened because developer cannot be verified.'

Ian

![Screen Shot 2024-04-13 at 9 03 03 PM](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166956380/ce51e024-e048-4742-9605-4cde277408d9)

**Comment by mawzthefinn** [comment]
That's a security setting.

That said, Big Sur is old and known to have issues with Suite later than 1.4.9 or so. As Big Sur is no longer a supported OS by Apple, it's now losing support in some of the libraries Suite relies on. 

You likely will need to update your Mac to a version still supported by Apple.

**Comment by ianshpprd** [comment]
Thanks for the reply.

It would cost $2,500 to $3,000 (NZ) to update my mac so I am not sure what
to do.

Ian

**Comment by spoke2570** [comment]
The security setting in in Monterey still requires manually approving the app in Settings>Security on the first open, if it is manually installed. Unless FrSky wants to bow to Apple this is not likely to change. 

OSX definitely fails to run Suite. I have not tried OS 11, but I will take Mawz's word for it.

If you manually approve the app in Settings>Security and it still won't run. You can use Bootcamp which came with your OS to run Windows on your Mac, or you could try Open Core Legacy Patcher which has worked very well for me in the past. It basically is a package of patches that lets you run a more current version of OS on your old Mac.

**Comment by ianshpprd** [comment]
Thanks for the tip!

Ian

**Comment by Nicholas-Luoyi** [comment]
> If you manually approve the app in Settings>Security and it still won't run.

I think this could make it work

**Comment by spoke2570** [comment]
It should.
