### ISSUE TITLE
Last plane flown when starting

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#3837]
I noticed that when starting ethos the main menu does NOT go to the last airplane used. Was this intended?

**Comment by Toffs** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3804

I believe it’s already sorted in nightly builds, scheduled for 1.5.7 release.  Feel free to try the nightly to test it’s as you’re expecting.

**Comment by ninodesposati** [comment]
thanks

**Comment by ninodesposati** [comment]
Found it in the General section
