### ISSUE TITLE
ETHOS SUITE

### ISSUE THREAD

**Issue by KLOSTRO** [FrSkyRC/ETHOS-Feedback-Community#3838]
Bonsoir,

Serai t il possible dans ETHOS SUITE, si je vais dans Nouveautés par exemple, la colonne de gauche en noire, ETHOS, Bienvenue, Guide de démarrage, Nouveautés, toute cette colonne est bien écris en Français, dans la colonne centrale en gris clair sur la droite, il est écrit Bienvenue dans Ethos suite, c'est toujours bien en Français, et en dessous, Ethos 1.5.5 pour le cité, Coming soon ... et All et tout le reste de la page est en Anglais et pas possible de le modifier ????????
C'est compliqué

Merci de voir si la traduction est possible !

**Comment by Nicholas-Luoyi** [comment]
You could manually change the translation string in "Ethos Suite/i18n/XX.json". Then restart Suite and it will reload your changes.

**Comment by KLOSTRO** [comment]
Bonsoir,
Je ne vois pas le chemin  i18n/XX.json ?????

**Comment by Nicholas-Luoyi** [comment]
If you are using French. You should look for i18n/fr.json. Or ask @bsongis-frsky to update the French translation

**Comment by KLOSTRO** [comment]
Non, c'est uniquement en Anglais

**Comment by KLOSTRO** [comment]
Donc, c'est un problème

**Comment by Nicholas-Luoyi** [comment]
Would you please modify the translation file of your language with the attached file below and share with us?

[i18n.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15031627/i18n.zip)

**Comment by KLOSTRO** [comment]
[i18n.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15036866/i18n.zip)

le fichier fr.json est impossible à vous envoyer

**Comment by KLOSTRO** [comment]
Bonjour 

 

Je n’arrive pas, si vous voulez on peut faire avec TeamViewer en direct car moi je n’y arrive pas ??????

 

De : FrSky-Luo ***@***.***> 
Envoyé : vendredi 19 avril 2024 02:18
À : FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc : KLOSTRO ***@***.***>; Author ***@***.***>
Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] ETHOS SUITE (Issue #3838)

 

Would you please modify the translation file of your language with the attached file below and share with us?

i18n.zip <https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15031627/i18n.zip>

**Comment by KLOSTRO** [comment]
Bonsoir,
Je ne comprends pas ce que je dois faire ???????????

**Comment by Nicholas-Luoyi** [comment]
So you have modified the fr.json and make it display correctly? BTW, would you please talk in English?

**Comment by KLOSTRO** [comment]
Bonjour,
Non, je n'ai rien modifié, je ne comprends pas ce que je dois faire.
Je ne parle pas Anglais, seulement le français, désolé.

**Comment by Nicholas-Luoyi** [comment]
OK. Please leave this with us

**Comment by KLOSTRO** [comment]
OK vous parlez en Anglais et moi en Français, cela marche comme cela pour vous ?

**Comment by samsab1** [comment]
au lieu de pleurer , passe par un traducteur
c'est pénible à la fin

**Comment by KLOSTRO** [comment]
A priori je ne t'ai rien demandé samsab1 donc si cela ne te convient pas, comme le dit la chanson passe ton chemin et merci

**Comment by bsongis-frsky** [comment]
Merci d'utiliser les forums pour se bagarrer

**Comment by samsab1** [comment]
entendu; mille excuses

**Comment by KLOSTRO** [comment]
OK ça marche j'accepte
