### ISSUE TITLE
A way to create oscillators ?

### ISSUE THREAD

**Issue by julienhogert** [FrSkyRC/ETHOS-Feedback-Community#3839]
Hello everyone,

 I'm working in a French special effects company and we use the X20s radio control with ethos. 
First of all, thank you for the great job you have done. The software is very nice and powerful. 
We use the RC a little bit outside the limits of traditional RC models and for an animatronic we make these days, we need to create automatic movements with oscillators.
I tried to find a way to do this in the software, but I couldn't. I tested it with a Lua script, but didn't manage to make it change in time, and make it usable outside of the Lua script.
I finally found a trick using an Arduino to send Sbus with the oscillations, but it's a pity because, except the period of the oscillation, everything is there to make any curves, adjusting the shape and the levels with the curve function. Did I miss anything in the vars or functions section?

As for the bus receiver, I used the module slot and the module RX pin, but had to set the trainee mode to "master". I thought because it was receiving that it should be in "Slave", but no. Is it a bug or something I don't understand about the trainee mode?
Thanks, 
Julien

**Comment by WhiskeyGolf** [comment]
You can use the “test mix” for an oscillation.

**Comment by WhiskeyGolf** [comment]
Or you can use the time generator in LS with a slow function on the mix

**Comment by strgaltdel** [comment]
I'm pretty sure you can achieve your goal, in the sense of the technical meaning of an oscillation v:
a somehow shaped curve with a fixed repetition time

first, as mentioned above, create an lsw that switches with the intended period time

this is the input for a free mixer
the mixer switches between +/-100% with the same period time

Design your curve, y-symmetrical and add it as an action to the mixer

set slow up/down action with 50% of the lsw period time

so that the input of the mixer "drives" the individual curve up and down.

Of course, you can also design more complex curves if you use separate mixers for "up" and "down" and your own curves.


this should work with fixed timebases
different (fixed ) timebases must be done with several "slow" actions and corresponding lsw's

[oszi.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14971829/oszi.zip)

**Comment by bsongis-frsky** [comment]
c'est tout bon @julienhogert ?
peut-on voir le résultat ? je n'ai pas bien compris comment est utilisée la radio :)

**Comment by julienhogert** [comment]
Bonjour, Hello everybody ! Thank you for your quick answer and your dedication ! I worked with test mix ! thank you very much ! I don't know why I didn't explore this ! In fact, it's maybe because the name don't make sens for me "test mix" what it supposed to be ? something more obvious like a "Oscillators" could be easier to find ;-) ! The only thing with this is that I can't control the time from a potentiometer. (Or still have to explore with var, I suppose) . I can't show any pictures but it's to make move the nose of an animal ! 
Thanks again for your dedication.

**Comment by pstasek** [comment]
Test mix is usually used to stress test servos for a period of time to ensure it's working well.

**Comment by mawzthefinn** [comment]
If you want a controllable oscillator, you can make one from a Free Mix and 3 Logical Switches.

Pick a channel, I'll use CHannel 7 in this case.

Create your first Logical Switch. I named it Top. 
Function is A > X
Source is Channel 7
Value is 99%

Create the second Logical Switch. I named it Bottom.
Create your first Logical Switch. I named it Top. 
Function is A < X
Source is Channel 7
Value is -99%

Create the third Logical Switch. I named it Oscillate
Function is Sticky
On is LS->Bottom
Off is LS->Top

Now create a Free Mix
I named it Oscillator
In order
Add a new action
Action is slow
Long press Slow up and select Use a Source
Pick the source, then twiddle the pot you want (Pot1 in my case)
Long press Slow down and select Use a Source
Pick the source, then twiddle the pot you want (Pot1 in my case)

Go back, Set your Output1 to Ch7
Set your Source to Logical Switch->Oscillate

Now you have an oscillating mix with speed selected but Pot1.

**Comment by julienhogert** [comment]
Hello [mawzthefinn](https://github.com/mawzthefinn). Thank you for your explanation. I'm stuck in the Free mix part. When I add a free mix, I don't have the option to "add a new action" but just a curve. and I don't know how to change the template. It still look a little bit complicated to me. Do you think it should be easier in a Lua, with the same option? (use the potentiometer to choose the speed and the In and Out position?  Thanks for your dedication. Julien

**Comment by mawzthefinn** [comment]
You need to be on current firmware to add actions to Free Mixes (1.5.0 and later).

**Comment by julienhogert** [comment]
It works perfectly ! thanks you for taking the time to explain it to me ! Julien
