### ISSUE TITLE
Problem updating Twin Xlite

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#3840]
Ethos suite 1.5.2
bootloader 1.4.16
firmware on twin xlite (was)1.5.5

Twin Xlite is recognised by suite when the update starts I get the image below although the transmitter displays  USB connected and when unplugging ( as asked ) it says bootloader mode update doesn't want to start.

I had "Ethos suit" mode set as default on the transmitter. When I changed it to "not set" update worked as expected

**Comment by mawzthefinn** [comment]
Update ETHOS Suite, that's an old version

**Comment by 00steven** [comment]
Strange no warning for the new version?  I checked and tried a manual update,there was no update on the GitHub server ( in the suit ). Now I  changed to the FRsky server then there was an update.

**Comment by mawzthefinn** [comment]
> Strange no warning for the new version? I checked and tried a manual update,there was no update on the GitHub server ( in the suit ). Now I changed to the FRsky server then there was an update.

Suite is now a separate release from ETHOS firmware, and the previous Suite release was still checking ETHOS releases for updated Suite, rather than Suite releases.

The latest release will look for updates in the correct spot for the future.

**Comment by Nicholas-Luoyi** [comment]
> I had "Ethos suit" mode set as default on the transmitter. When I changed it to "not set" update worked as expected

Seems like a radio issue?

**Comment by 00steven** [comment]
> > I had "Ethos suit" mode set as default on the transmitter. When I changed it to "not set" update worked as expected
> 
> Seems like a radio issue?

What info do you need?

**Comment by Nicholas-Luoyi** [comment]
We have USB mode preselection with Not set, Joystick, Ethos Suite and Serial. What do you mean by "default"?

**Comment by 00steven** [comment]
I meant "not set "
