### ISSUE TITLE
[Bug] Throttle active gets actived when throttle cut unlocks motor

### ISSUE THREAD

**Issue by Dsrenger** [FrSkyRC/ETHOS-Feedback-Community#3842]
I think I found a bug with the throttle active system event.

I created a timer that has "throttle active" as start condition and "custom" with no stop condition (so that it runs, once started)

Then, in the gas mixer I added a throttle cut condition.

Active condition is e.g. SA(down).

Now, when the active condition for the throttle cut goes from true to false, the timer starts to run.

All this is done with the throttle stick at -100%.

I didnt expect the event "throttle active" to activate for a short time, in case the throttle cut condition get false when the throttle stick is at -100%.
It's a little bit annoying when you deactivate the throttle cut and timers start to run.

Attached you will find a test model created on the 1.5.6 XES simulator, where this happens.

One side note:
On the real transmitter you can see the text "throttle active" go bold for a short amount of time.
You cannot see it in the simulator. I guess the simulator is just to fast. 

[model02.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14972024/model02.zip)

**Comment by T16-Pilot** [comment]
This is what happens in #3824 

This is what i am trying to explain to @bsongis

Best regards
Simon

**Comment by mgsanna** [comment]
Tryed right now, as you deactivate throttle cut the timer start... and the condition on timer become bold for a matter of millisecond...
X20S - X20PRO
Confirm by my side

**Comment by Dsrenger** [comment]
@T16-Pilot

Sorry, haven't seen your issue. Otherwise I would have posted it there.

I tested on a XES with 1.5.6 and in the simulator 1.5 .6 and the issue is still there.

**Comment by bsongis-frsky** [comment]
Reproduced, thanks for the explanation, it is clear now!

**Comment by bsongis-frsky** [comment]
Fix ready for next nightlies

**Comment by bsongis-frsky** [comment]
Nightlies are online, please tell me if the problem is fixed?

**Comment by mgsanna** [comment]
> Nightlies are online, please tell me if the problem is fixed?

It works !!! thanks

**Comment by T16-Pilot** [comment]
Hi, yes it is working now.

Thank you my friend.

Best regards
Simon

    På tirsdag 16. april 2024 kl. 13:57:44 CEST skrev Marco Gualtiero Sanna ***@***.***> følgende:  
 
 



Nightlies are online, please tell me if the problem is fixed?


It works !!! thanks
