### ISSUE TITLE
Request: Prevent smooth curves going in the 'wrong' direction

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3843]
The following is a typical butterfly / butterfly elevator compensation curve. The last 2 points are for a dead band.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/0ccae870-eb2f-46d4-a5ff-62ee9567dae2)

however note that between these points the Y value goes negative despite all of the Y values being zero / positive. This is of course undesirable. I feel it should be possible to have a smooth curve without this happening.

Thanks

**Comment by Dsrenger** [comment]
We had the discussion already here:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2326

Its just the behaviour of B Splines.

**Comment by hrenz** [comment]
its a spline-math and ok as it is.

use more points

**Comment by bsongis** [comment]
@Jedsters would you try to draw a curve which matches your request?

**Comment by Toffs** [comment]
I think Jedsters is suggesting the theoretical maths around the smoothing is fine, but that the practical application in RC can be undesirable in some circumstances.

For a butterfly (crow) flap deployment, you’d not want a value going in the opposite direction to the desired output.
I’m trying to think of a good UI method to overcome this. Perhaps the B-spline curve smoothing could be selectable between a range of points?  So in Jedsters example above, the last 2 points on the right don’t want the smoothing applied.

However, as hrenz & Mawz mention in the other thread referenced, making a few more static points would negate the need to have  any smoothing at all.
@Jedsters - whilst it might not look pretty, if you’re applying the butterfly through a slider or throttle manually I’d be surprised if one could spot the difference between a smooth curve, or one with 7+ points. What are your thoughts?

**Comment by Jedsters** [comment]
@bsongis I think that @Toffs has hit the nail on the head. There is nothing wrong with the curve aside that it goes below 0 between points 5 and 6. This means that instead of having zero elevator in my dead band between 5 and 6 (because I don't want to keep accidentally applying crow if I move the throttle a fraction) I would get a little up or down elevator in this dead band, also it means that as I start to apply crow intentionally I e.g. may get some up elevator before the down elevator kicks in - this makes matters worse as gliders very often balloon up when you start to apply crow and having a bit of up elevator before the down kicks in makes matters worse.  Ideally I'd want a gradual incline to the left of point 5, with the section between points 5 and 6 to be horizontal.

Of course - use more points is one argument - but then one could use that as an argument to say that smooth is not needed. 

To be fair, the suggestion of adding an extra point immediately to the right (in this case) of point 5 does appear to work and gives me what I want (Thanks) e.g.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/ec0512d2-baec-4ced-8c8d-05a4238a9c52)
so is this hinting at a solution? 

Is there a use case where in this type of curve one would want a curve to initially go in the 'wrong' direction? If not, is a solution to perhaps optionally ask the user if they want an extra point immediately to the side of an existing point when 'smooth' is selected and a curve may otherwise go beyond any Y values, to avoid it? I can however imagine that this only makes sense if it is the first two or last two points on the curve which have the same Y value. If an extra point was added, it would be ideal if all other points were retained and I guess the curve would have to be changed from 'Easy', if that was specified, as part of the action.

I guess the logic would be along the lines of for a curve with N points:

If the Y values of points 1 and 2 are the same or the Y values of point N-1 and point N are the same 
then if Smooth is selected
Ask the user if they want to 'Avoid over-run'
If they do then change the graph to have N+1 points or if both the Y values of points 1 and 2 are the same as well as the Y values of points N-1 and point N are the same then add 2 extra points
If Easy mode is selected, deselect it
If the Y value of points 1 and 2 are the same then insert a new point after point 1 with Y value the same as point 1 (and 2) and a X value 1 less than the Y value of point 2
If the Y value of points N-1 and point N are the same then insert a new point after point N-1, with Y value the same as point N (and N-1) and a X value 1 greater than the Y value of point N

(Hopefully that makes sense and I've got it right, but please shout if it isn't or something seems odd.)
    
(Edited the last bit of the logic to swap a couple of X and Y's around!! Oops!)

**Comment by Jedsters** [comment]
Just a thought, if there is no valid use case for an over-run then maybe the above could be done internally without any user involvement so they think they are still in easy mode and never even see the extra points? 

That would also simplify implementation as currently I can foresee it being slightly tricky if a user e.g. changes an existing curve so that point 2 has the same Y value point as point 1 - you'd need to ask the user the question - but they may only  be at the same Y value on their way to a value the other side. 
I can also see that this may only be valid so long as points 1, 2, N-1, N aren't derived from VARs and I'm not sure I'd want it being done while I'm flying if I was changing a VAR!

**Comment by bsongis** [comment]
The extra point idea is good. I am really afraid of breaking existing setups if I change something in this curve!

**Comment by Jedsters** [comment]
I guess the only way to avoid that is to make it optional somehow. An extra option on the graphs of Avoid Over-runs? with a default of No

**Comment by bsongis-frsky** [comment]
Perhaps change the checkbox to an "algorithm choice" (None / Smooth / Jedsters)
:)

**Comment by hrenz** [comment]
at the calculation of each Bezier-Spline 
you need 3 points at start
and 3 points  at end
for correct smooth curve and a horizontal line at start or at end
its math only
