### ISSUE TITLE
X20-PRO crack noise on startup

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#3844]

**Comment by bsongis-frsky** [comment]
Now I have the radio in hands, I need to investigate

**Comment by spoke2570** [comment]
My X20S on 1.5.6 does this as well.  It stutters the fist word of the 'hello' file.

**Comment by bsongis-frsky** [comment]
Strange, the crack on mine comes very early, before the logo is displayed, the "hello.wav" is played at least 2 seconds later!

**Comment by spoke2570** [comment]
Yours sounds more like some switching problem.

**Comment by bsongis-frsky** [comment]
Bad volume on startup. Fixed on mine now.
The fix will be included in the next nightlies.

**Comment by KevinFairgrieve** [comment]
> Bad volume on startup. Fixed on mine now. The fix will be included in the next nightlies.

So far this has been my only "complaint" with my X20PRO.

Thank you for sorting it. looking forward to the fix.

**Comment by bsongis-frsky** [comment]
Nightlies are online, please tell me if the problem is fixed for you too?

**Comment by spoke2570** [comment]
Mine picked up the crack at shut down with the nightly. 
The stutter is unchanged. It is like that start crack happens right with the 'hello.wav'. Mostly it sounds like I clipped a little too much off the front of the wav file. Once in a while it will stutter properly, repeating the first consonant once. Interestingly enough If the radio is in suite mode when it is disconnected the 'hello.wav' file plays perfect.

**Comment by KevinFairgrieve** [comment]
Fixed for me. 

> Nightlies are online, please tell me if the problem is fixed for you too?

**Comment by it-walter** [comment]
HI, the crack-sound on startup is in 1.5.7 very reduced but not complete removed, for me.
