### ISSUE TITLE
Italian translation of "VFR low Warning" msg 

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#3845]
Ethos Version1.4.17
Radio: X20S

When the VFR get lowest that 50% the radio play "VFR Low Warning " in English and NOT in the default language (Italian). I have checked in  the last version of the translation Excel file and the msg is not translate in Italian. I am not sure if this small error war resolved on the 1.5xx versions because I am not able to simulate and I didn’t find any issue in the database related to this small problem. The correct translation in Italian of the msg is “ VFR Valore Basso”.

**Comment by GiorgioCirelli** [comment]
It involves translating the terms added into the new versions.
I had translated them the other time.
Maybe I'll do it this time too?

**Comment by fdapport** [comment]
Great!!!... Thanks, Franco

**Comment by mgsanna** [comment]
> It involves translating the terms added into the new versions. I had translated them the other time. Maybe I'll do it this time too?

Hi @GiorgioCirelli, the audio package for Italian is yours? why not to collaborate in making a new audio packages with. more and more terms just like English version? I'm the translator of the manual and Ethos software and Ethos suite....
pls let me know if you like my idea.
marcogsanna@gmail.com - 3482681586 

Ciao Giorgio, i file audio sono opera tua? perche non collaboriamo nella realizzazione dei file audio nuovi con voci aggiuntive tipo la versione inglese? Sono il traduttore del manuale, del software Ethos e della Ethos suite....
fammi sapere se l'idea ti garba...
grazie Marco

**Comment by mgsanna** [comment]
@bsongis hello Bertrand, we need to update the whole italian audio packages getting more things just like english or french, to do so it'll suffice to provide you the updated it.csv (of audio pack of course) or do you need something more special? I think that they will be "transformed" with the correct tts voice by your team, or do you prefer the whole new package with audio wav files?
thank for your support

**Comment by bsongis-frsky** [comment]
The CSV are public, they are in this repository.
Soon I will make the TTS scripts public too, so that everybody should be able to generate its own prompts

**Comment by mgsanna** [comment]
> The CSV are public, they are in this repository. Soon I will make the TTS scripts public too, so that everybody should be able to generate its own prompts

@bsongis-frsky I know that they are public, the questions were:
Can I publish an updated it.csv (audio wav) including also all the system sound and new terms missing in ita audio pack? 
Shall I include also the wav for the next release of ethos?
thanks

**Comment by bsongis-frsky** [comment]
It seems I used the google TTS voice to generate the IT prompts, so you should not include any wav files, it will be done automatically:

```
"it/default": {
    "engine": "google",
    "voice": "it-IT-Wavenet-B",
},
```

**Comment by mgsanna** [comment]
Ok as the csv is finished I’ll upload thanks BertrandInviato da iPhoneIl giorno 16 apr 2024, alle ore 14:25, Bertrand Songis @ FrSky ***@***.***> ha scritto:﻿
It seems I used the google TTS voice to generate the IT prompts, so you should not include any wav files, it will be done automatically:
"it/default": {
    "engine": "google",
    "voice": "it-IT-Wavenet-B",
},

**Comment by GiorgioCirelli** [comment]
I have prepared the translated files for the Italian language.
The TTS1 (75) Wavenet-B - FEMALE was used as voice.
I hope the file is correct


[audio_it.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15014977/audio_it.csv)

**Comment by fdapport** [comment]
It is great!!! Thanks, Franco

**Comment by bsongis-frsky** [comment]
Done
