### ISSUE TITLE
1.5.6 "Skip on startup audio"

### ISSUE THREAD

**Issue by mirko91** [FrSkyRC/ETHOS-Feedback-Community#3846]
Hi guys, just updated from 1.4 to 1.5.6 because I needed the vars for the gliders but I found one small bug: when I turn on the radio the "skip on startup" audio functions the stay silent, but after a reset they play as if the function is not active. Am I missing something or is it a bug?

**Comment by bsongis-frsky** [comment]
What is your audio sequence? Because I have tried it with a minimal sequence and it seems to work perfectly!

**Comment by mirko91** [comment]
I have a plane with a switch set as enable/disable motor with audio confirmation. When the switch is in the "off" position it plays once "motor disabled". When I turn on the radio it stays silent but when I do a reset with a logic switch it plays "motor disabled"

**Comment by bsongis-frsky** [comment]
Ah understood

**Comment by bsongis-frsky** [comment]
Reproduced. Indeed I think it's not good. Do you confirm it was OK in 1.4?

**Comment by mirko91** [comment]
Yes, the latest 1.4 was good, had it going on every model. To work around that I use two reset functions, one for the telemetry and one for the timers and it doesn't play the audio

**Comment by bsongis-frsky** [comment]
Fix ready for the next nightlies

**Comment by mirko91** [comment]
Huge effort! Thank you, keep Ethos growing
