### ISSUE TITLE
Complete radio loss whith no telemetry warning X18 Ethos 1.4.17 TD r18 V1.0.11

### ISSUE THREAD

**Issue by Ze-baloo** [FrSkyRC/ETHOS-Feedback-Community#3847]
Hi.
This weekend i've lost my Timber 110 due to a complet radio loss while being in wireless trainer mode with my son.

He was flying the timber whith my taranis x9d+ se 2019 as a slave transmitter when the dle55 stopped running with no reason.

I've tried to take back the control on my transmitter with no stress has the plane was high and has an integrated electric starter.

But, i've never had any control back, and absolutely no telemtry warning even when the plane destroyed itself on the ground.

It's like the receiver was in failsafe mode but still connected to the transmitter.

If the blackbox function need to be activated, i'm sure it wasn't activated because i never needed it on all my frsky products.

I'd like a bit of help to understand from what came this radio loss, to know how to avoid it to happen again on another plane.

PS : it seems there was some radio disturbance as i had a vfr low warning on another plane with a Archer R10+ receiver on take off
(range checked just after with 50m befor alarms) - some friends with graupner radio gear had also quality signals warnings during the day and when i lost control of my plane.

Thanks in advance for any help.

Laurent

**Comment by bsongis-frsky** [comment]
No RSSI warning at all? Only VFR? (VFR Warning on take off is not normal!)
No Emergency Mode on the radio?

**Comment by Ze-baloo** [comment]
Nothing, no vfr warning, no rssi warning during the crash on the timber, the radio remained silent and apparently in working condition.

It remained on while i went finding all the parts in th field, while back i pluged again the batteries on my jeti switch, the receiver switched on normally, and when i disconnected the batteries the radio gave me the "telementry lost" warnin in less time than the fall of my plane has lasted.

For the VFR warning on take of on my toplite P47, the receiver was formerly in a Timber X night i had no issue at all.
I remaidened th P47 a few weeks ago at another field with absolutely no warning.

I didn't do any update on any of my transmitters or receivers since the 1.4.17 release.

**Comment by bsongis-frsky** [comment]
And the radio didn't even raise the RSSI warning when the plane was broken (and I suppose the battery disconnected from the receiver)? Then it raised it on the 2nd disconnection (when you did it on purpose)?

This sounds very strange to me right now!

**Comment by Ze-baloo** [comment]
I'm not 100% sure that the batteries where disconnected during crash, i didn't picked them myself, a friend did.
I was taking care of the engine.

what i'm 100% sure is that i had absolutely no VFR or RSSI warning between the engine loss and the crash and the time i left the radio on the ground to go and find the plane remnants.

**Comment by bsongis-frsky** [comment]
> It's like the receiver was in failsafe mode but still connected to the transmitter.

Yes. I will forward it to the RF team. I cannot see how Ethos could be involved at this moment.

**Comment by bsongis-frsky** [comment]
May I assume it's not a pilot mistake?

**Comment by Ze-baloo** [comment]
I would have loved to assume that it was a pilot mistake but i was unable to regain any control on the plane...
just the elevator would have been enough to save it.
I'm just willing to find an answer to stop having a doubt for further flights.
I'm on frsky gear since the first Taranis X9d and i had no issue on any plane ever since.

I must say that i found more clever to post it here than on a social media.
I was not really aware on where to ask as the issue is really odd even for me.

i just forgotten to mention this : The wireless training system is the only thing that was different from the former flights the same day with this plane.

**Comment by bsongis-frsky** [comment]
But the Taranis X9D was not sending RF.
Even if the cable is disconnected, the teacher has full control of the plane

**Comment by Ze-baloo** [comment]
Exactly, and i also had no warning like trainer transmitter lost.

**Comment by Ze-baloo** [comment]
I can't tell if it was before or during the loss, but ther was three felow pilots with graupner hott gear around me at the same time.

They all had quality signal warning during this flight.

Tell me if i'm wrong, if the 2.4ghz band could have been jammed, the receiver could have kept on working on 900mhz?

**Comment by bsongis-frsky** [comment]
Do you remember on which page of Ethos you were when flying? The "normal" Home page?
I ask to be sure you were not in System / Information, where the module and receivers are disturbed from time to time to send the version information

**Comment by Ze-baloo** [comment]
I remember having activated the trainer mode on this model before flying.
But as far as i remember i always exit any programmation menu before flying.
I may have forgotten this time, i can't be totally sure.

**Comment by Ze-baloo** [comment]
I also have the zavionix LUA for the TD R18 on this model.
As my HV servos are draining a lot of current, i always have the zavionx page widget to control the battery voltage.

**Comment by strgaltdel** [comment]
may i propose to attach the logfile if available?

some club members experienced a similar event when 3 models (different transmitter types) falled off the sky within minutes.
on one we could read the log.

RSSI seemed to be OK, but VFR dropped which pointed to a "rf contaminated atmosphere"

there was/is a large army training ground about 3km in distance

the club contacted their management, but, of course, they neglected to have played with any kind of electronic warfare components these days.

case was never solved

**Comment by Ze-baloo** [comment]
I'd loved to have activated the log file... Be sure that i'll do it on all models from now.

I've just asked to my friends if they have one, but i don't have much hope.

**Comment by bsongis-frsky** [comment]
When you came near the plane when he crashed, have you tried to move the sticks to see in which state was the receiver?

**Comment by Ze-baloo** [comment]
No, i left the radio to my friends at the pilot zone while seeking for the plane in the colza field.

Due to the shock there was nearly no servo left connected on the receiver.

I wasn't having in mind to test it but more to find it because it was out of sight after the crash.

**Comment by Ze-baloo** [comment]
I just can tell that on a bench at the field just after having recovered most of the parts, the telemetry warning where working as explained sooner and i used the towing servo on the aileron channel to check if the receiver was working in master mode or in trainer mode.
As you can imagine, it was working 🤔

**Comment by strgaltdel** [comment]
may I assume that "motor idle" or "motor cut" was set as the fail-safe position?

**Comment by Ze-baloo** [comment]
Normally yes, i'll check back home in 3h to be sure.

**Comment by Ze-baloo** [comment]
I'm looking for some info about the black box function.

Is it always activated?
Do i just need to switch on the receiver and the transmitter to acess the datas?
The manual is lacking of information.

**Comment by strgaltdel** [comment]
.. you should be able to evaluate the settings without Rx

enter the model / rf module,
the section "failsafe"
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/fae610b3-0d73-4dca-8f79-d89cac319c57)

depending what's set in the "global" setting,
you may see detailed infos when you click the set button in custom settings

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/98f324b1-6e13-4124-9cc1-ac196eab9fdd)


at least, in case "motor cut" was set,
the inflight motor shutdown could be the result of a failsafe situation.

**Comment by Ze-baloo** [comment]
On my warbirds the default failsafe parameter is 
gaz iddle
kill switch off
gear up
full flap

I assume that on the timber i've at least programmed gaz iddle and kill switch off, but just now i can't remember.

**Comment by Ze-baloo** [comment]
The kill switch is set to cut off and gaz to iddle if the receivers enter in failsafe mode.

The black box datas aren't showing anything odd, but i think that they are only showing the actual status of the receiver. 
![17132826904637002804409643267012](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15279917/01e656a2-6c0a-409f-ba4a-e6819fe9f2a9)
![17132827178776757723570532887521](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15279917/24ab76cb-84ee-4e89-822d-7dd73249411b)

**Comment by Ze-baloo** [comment]
Hi. I just had a testimony from another long time frsky user (former taranis x9d under opentx user) who has also destroyed a towplane while using a x18 and an access receiver.

Like me i didn't get any alarm during the crash and everything was working after the crash.

Unfortunately he has already sokd back the x18 to jump to futaba and has no ideaof the firmware or the ethos release he was using.

What information woulf you like to have to help finding a cause?

**Comment by bsongis-frsky** [comment]
I have forwarded the issue to the RF team. 
From your description above, I cannot see how Ethos can be involved, so it's difficult to me to find the cause!

**Comment by Ze-baloo** [comment]
Bertrand, i understand well. 
Many thanks for your help. 
Just tell me if i need to post this somwhere else more appropriate.

**Comment by bsongis-frsky** [comment]
The issue has been forwarded, please give them some time to try to understand.
Given that there is no logging at all it's even more difficult!

**Comment by Ze-baloo** [comment]
Ok, understood, i'll wait.

I've activated the log on all models now.
Have you thought of having it always activated, and the user choose to dectivate it or not? 

Have a nice day. 

Laurent

**Comment by Ze-baloo** [comment]
> And the radio didn't even raise the RSSI warning when the plane was broken (and I suppose the battery disconnected from the receiver)? Then it raised it on the 2nd disconnection (when you did it on purpose)?
> 
> This sounds very strange to me right now!

I had a dsicussion yesterday evening with the friend who helped me gathering all the bits of the plane.
he found the two receiver batteries disconnected on the ground.
