### ISSUE TITLE
Some LS become active for a short time at startup

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3848]
Hello
Since today's nightlies, some LS become active for a short time when the transmitter (model) is started and therefore trigger unwanted announcements.
Here are 2 examples:
![LS17](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/c9d82490-415b-4cf1-a850-0aec5fb3f4fd)
![LS58](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/b3d6dea9-41ac-4d67-bc42-a768ae7553b1)
 Thank you
Wolfgang

**Comment by bsongis-frsky** [comment]
Is the fix OK? No more issue in this area?

**Comment by Wolepo** [comment]
The *.bin for the X10S Express is still missing. In Sim (X10S Express) "---" is still available for selection and still causes the same error.
![TTS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/edfca2d5-f052-45d4-bb80-05026e682149)
