### ISSUE TITLE
Wiget Text can become corrupted

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3849]
Consider the following .md text 

```md
# Calibrations
Cal FM      - **Up Ele + Left Ail + SH**
Cal SxR     - **Up Ele + Right Ail + SH**

# Calibrations
Cal FM      - ** Up Ele + Left Ail + SH**
Cal SxR     - ** Up Ele + Right Ail + SH**
```

while I accept that the last 2 lines aren't coded in the correct way to give the intended output, they shouldn't give the unreadable result displayed below 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/6d4ebded-f5e7-4604-81d7-169a09df928f)

Thanks

Edit: Sorry, github seems to be formatting the text too. Hopefully you can see that the problem is generated by a space between the double aster and the start of the text with a double aster at the end of the lines.

**Comment by bsongis-frsky** [comment]
I have edited your description so that the code is properly displayed, is it right now?

**Comment by Jedsters** [comment]
Thanks yes, I should have pasted the following first time!
It appears to be when there is a space ' ' after the two asterisks '**'  rather than text that there is a problem 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/6803d91c-aabf-4507-ab61-1e24471b40fa)

(that's a cursor before the '#' so ignore that)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5238da0f-3550-41ea-9f21-b6ca1dcc70c1)
