### ISSUE TITLE
R9 Twitch and Pauses

### ISSUE THREAD

**Issue by TWSreviews** [FrSkyRC/ETHOS-Feedback-Community#385]
I have R9MX receivers and a 6Ch R9SX.

I have found that my quadcopter now has a twitch approx every 10 seconds when I was throwing it about
My AR wing was set up with another MX on a flight controller and flew very unpredictable.

I removed the receivers and set up one of the MX receivers with PWM and found the servos very notchy and approx every 10 seconds they would stall for a second on both channels tested.
I opened my other new MX receiver and that was exactly the same. Set all up on 25mW with telemetry but the same on 200mW.

To confirm it was the radio I bound the brand new R9SX and that was exactly the same.
I noted, that the monitor is not mirroring the pauses.

I did then did the same test binding to 2.4 receiver and all was ok, smooth and no pauses.

The R9 part of the transmitter is clearly the problem. Is there any other reported R9 issues or is it looking like a radio fault?

**Comment by OldGazer** [comment]
That's odd.  I just put a new R9 MX into my beater 250 FPV quad and spent the afternoon shredding the air.   Never missed a beat.

**Comment by TWSreviews** [comment]
Just updates the TD internal module FW v2.1.8 and it fixed the problem. Seems there is a FW issue causing this glitch

**Comment by TWSreviews** [comment]
> That's odd. I just put a new R9 MX into my beater 250 FPV quad and spent the afternoon shredding the air. Never missed a beat.

It was like a misfire. Fixed now with internal TD module FW update to v2.1.8

**Comment by bsongis-frsky** [comment]
Fixed then, ok?

**Comment by TWSreviews** [comment]
> Fixed then, ok?

Yes....thank you.....all fixed
