### ISSUE TITLE
ETHOS 1.5.6 Sensor Lost when displaying the system info

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#3851]
Hello Bertrand,
On mine X20S with ETHOS 1.5.6 I only get SENSOR LOST when the **System INFO** is displayed.
Further the RSSI display for 2.4GHz fluctuates very strongly from 66dBm to 100dBm while the 868MHz display stays still at 90dBm or more. We've had this problem with fluctuated RSSI in the past some versions before.
best regards,
Torsten

**Comment by bsongis-frsky** [comment]
Let me check with the RF team.

**Comment by Satcomix** [comment]
> Let me check with the RF team.

Thank you for your work and effort.
best regards,
Torsten

**Comment by SmartTommy** [comment]
when the System INFO page, the Tx will aways send the device info to the UI rather than sensor telemetry data. we will fix it next version

**Comment by raydars** [comment]
To add to this X20 Pro on 1.5.6 flex,   TW12 on 1.0.6,  R9 mini OTA on 1.3.1 when you go into system info redundant 900mhz receiver rssi is lost and telemetry warning given.
