### ISSUE TITLE
Problem with Vars (Ethos 1.5.6)

### ISSUE THREAD

**Issue by PeterGraz** [FrSkyRC/ETHOS-Feedback-Community#3852]
Hi folks,
I use a switch (with the edge option set) and the "Assign(=)" action in order to assign the value 0 to a "Var". Activating the switch the value is set properly. However, the switch acts as if the edge option was missing! (As long as the switch is set you can not change the value by any other action)
Regards, Peter

**Comment by Wolepo** [comment]
Has already been fixed in the next nightlies 1.5 (1.5.7).

**Comment by PeterGraz** [comment]
Thanks for the quick response, Peter

**Comment by bsongis-frsky** [comment]
Yes this one is fixed already
