### ISSUE TITLE
offer a standard user simple feedback when a lua script produces errors

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3853]
From forum posts, I gather that due to the first 1.5 revisions, quite a few users have "fears" or "uncertainties" about EMs, especially in the context of luas.

The usual Ethos users does only USE luas, if at all.
It's  a "black box" for him.
He can neither recognize errors in luas nor assess their quality or effects.

On the other hand, most people are aware that previous / old luas can (in rare cases) suddenly stop working properly due to Ethos updates or new extensions. 
However, the user does not always "see" this, as sometimes screen updates are still carried out and a lua appears to work at first glance.

Hardly anyone knows how to use the dev mode in the suite or start the sim in debug mode.

This causes uncertainty and even Ethos update reluctance for several users.

My suggestion would be the following extension, if easy to implement.

As soon as a lua produces an error, an additional icon appears in the header of the home screen

![lua error](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/7ec9eb7f-fe1d-440a-a61b-204abd0c7d5f)

This way the user recognizes that there is a problem in a lua script,

**even more important: it gives him the certainty that there is no Lua problem and that no "Lua-induced EMs" can occur if the alarm is not displayed.**

**Comment by bsongis-frsky** [comment]
Your icon seems a little bit too big ;)

**Comment by strgaltdel** [comment]
Please don't remind me of my advancing age,
last week I stopped the car in the middle of the road for 15 minutes to let a hedgehog cross the street. 
Then I realized it was a pinecone.

.. and i thought X24 will have a bigger screen ?
(-;

**Comment by lthole** [comment]
Great idea!

**Comment by bsongis-frsky** [comment]
I have asked to our UI designer to prepare some icons for this request, which is a good idea.
Also I will ask the whole text of the last error(s) in System / Information

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/70b429a3-c3d8-4c64-ab34-af60291dad1d)

**Comment by Target0815** [comment]
X18SE - Ethos 1.5.9

LUA errors are displayed, but it is unclear which LUA is affected .... How can the error messages be deleted?
