### ISSUE TITLE
Request for Counters

### ISSUE THREAD

**Issue by PeterGraz** [FrSkyRC/ETHOS-Feedback-Community#3854]
Hi folks,
as some others already suggested (e.g. hrenz) I would like to opt for "Counters".
"Counters" could be implemented with small modifications on the basis of "Timers" (Name,  Start Value, Value, Mode or INC/DEC, Reset , Persistent, Audio actions).
Like "Timers", "Counters" would also just keep track of something and therefore their use is limited. Nevertheless, I think the demand for "Counters" is as justified as for "Timers".
Regards, Peter

**Comment by bsongis-frsky** [comment]
I don't understand the request, what is the difference between what you call a "Counter" and Ethos Timers?

**Comment by PeterGraz** [comment]
Sorry, I was not specific enough!
A Counter would simply count non periodical events like number of flown laps, number of starts, number of low RSSI events, etc. A Counter would typically be inc/decremented by a physical of logical switch and not by the time passing by.

**Comment by mawzthefinn** [comment]
A VAR with an increment/decrement action can deliver counter functionality,

**Comment by PeterGraz** [comment]
Thanks for the hint!
I already tried it with a VAR, incremented/decremented it by 0.1% and used it as an input to a calculated sensor (Formula: Custom, Unit: ---, Decimals: 0, Range: 0 - 100000, Source: VAR) in order to get an integer value without unit. Yes it is somehow possible!
However, this is an awkward implementation for a simple issue wich relies very much on the current version of Ethos (e.g. the percentage in VAR is multiplied by 10 in the calculated sensor). Minor changes in Ethos will jeopardize such a solution.
Don´t get me wrong: I love Ethos with all the progressive updates!
