### ISSUE TITLE
Adjusting subtrim and servo endpoints with Vars.

### ISSUE THREAD

**Issue by BarryCole** [FrSkyRC/ETHOS-Feedback-Community#3856]
Firstly I am new to this, and this issue may have been reported by someone else.

Is it possible to enable the adjustment of subtrim and servo endpoints with Vars.  The same as it is with OTX and Edge.

Thank you for your help.

**Comment by bsongis-frsky** [comment]
Yes. It is almost ready. It will be there in 1.5.7

**Comment by BarryCole** [comment]
Thank you so much.

**Comment by bsongis-frsky** [comment]
5 new hamburgers in the next nightlies ...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/957c600f-3f29-4b05-b586-87bdf72c8612)
