### ISSUE TITLE
X20-HD video component update

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#3857]
Ligen from hd-zero had informed that he had given an updated firmware for x20-hd to support latest features, May I know when it will be made available to us?

**Comment by bsongis-frsky** [comment]
HD-Zero have updated the TX / RX firmware
We are testing on our hardware

**Comment by kakashi2018** [comment]
thank you for the update

**Comment by voegitech** [comment]
I am so curious what the update will bring, because I still have a problem that I only see the livestream on the X20HD screen, but no telemetry data. It works with my FPV goggles with their own HD-Zero receiver.

**Comment by kakashi2018** [comment]
I was told by ligen that he implemented support for hd osd, 90fps cam
support(only 60 on x20hd screen) narrow band and low band support. For your
issue as not getting osd, try building the betaflight firmware with just sd
osd and remove hd osd and in betaflight osd configuration set format to pal
you will now have osd displying on x20hd screen.
