### ISSUE TITLE
Ethos 1.5.7 (Nightly) firmware ITALIAN update & audio_it.csv update

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3859]
[it.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15015994/it.csv)

and from @giorgiocirelli the audio_it.csv file

[audio_it.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15027668/audio_it.csv)

@bsongis-frsky here is the last 1.5.7 italian firmware update, please note also that @GiorgioCirelli has posted a new Audio.csv in
#3845 (the same included here)

**Comment by fdapport** [comment]
I have seen that the customized audio files of EN (English) under gb & us  are vary useful. Could we have the same on the Italian audio?  Do I need to open another ticket for this request. Please let me know, Thanks,

![Audio](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/f61aeda2-cc3c-4ed4-b783-928f86b00b14)

**Comment by mgsanna** [comment]
@fdapport @giorgiocirelli

> I have seen that the customized audio files of EN (English) under gb & us are vary useful. Could we have the same on the Italian audio? Do I need to open another ticket for this request. Please let me know, Thanks,
> 

La tua Richiesta è gia stata soddisfatta è verra implementata nella prossima release.... se leggi invece di continuare a scrivere e chiedere le stesse cose è stata eseguita da Giorgio Cirelli e revisionata insieme a me esattamente ieri..... ok ?nella nuova release dell'audio ita ci saranno molte piu voci di prima tutte quelle presenti in inglese e in francese, compreso sgancio traino e roba simile.... quindi addirittura piu di quelle inglesi e francesi.... un attimo di pazienza e saranno pubblicate....

Your request is already taken in account and the new file of italian audio will be ready asap with the newest release of ethos... maybe 1.5.7. so it is not useful to clog this repository with double request and there is no urgence to obtain simple audio files...

**Comment by fdapport** [comment]
Ottimo, grazie...

**Comment by fdapport** [comment]
Buongiorno,
Scrivo in italiano per non essere mal interpretato. Il fatto che abbia richiesto gli audio customizzate tradotti in Italiano  come per la lingua inglese nella versione 1.5.6  non era chiaro nel testo di questo ticket, che avevo ovviamente letto!! In aggiunta avevo segnalato la mancanza di traduzione di un msg di sistema (#3845) e pensavo che questo release fosse relativa solamente ai messaggio di sistema tradotti in italiano. Cosi ho pensato di segnalarvi che potevano essere utili anche i msg aggiuntivi visto che questi sono molto utili. Solo aprendo il file csv si capisce  che ci sono moltissimi altri audio NON di sistema... Mi scuso per la confusione ovviamente e per l'interferenza al vostro lavoro che state facendo per migliorare il sistema... Se avete bisogno di qualcosa fatemelo sapere che posso aiutarvi nelle traduzioni, etc... Saluti, Franco Dapporto

**Comment by mgsanna** [comment]
Carissimo Franco direi che c’è stato anche da parte mia un misunderstanding riguardo il suo post! Nulla di personale ovviamente… Una cosa utile potrebbe sicuramente essere dare feedback magari leggendo il manuale attentamente di eventuali errori o frasi “mal interpretabili o termini non così chiari o traducibili in modo migliore. Questo sarebbe preziosissimo per me…. Anche nei menu della radio ci fossero incomprensioni….Le lascio la mia mail diretta e il mio ***@***.*** 3482681586Ps condividendo la stessa passione potremmo anche farci del tu! Io sono già grandicello (50)Inviato da iPhoneIl giorno 19 apr 2024, alle ore 12:13, fdapport ***@***.***> ha scritto:﻿
Buongiorno,
Scrivo in italiano per non essere mal interpretato. Il fatto che abbia richiesto gli audio customizzate tradotti in Italiano  come per la lingua inglese nella versione 1.5.6  non era chiaro nel testo di questo ticket, che avevo ovviamente letto!! In aggiunta avevo segnalato la mancanza di traduzione di un msg di sistema (#3845) e pensavo che questo release fosse relativa solamente ai messaggio di sistema tradotti in italiano. Cosi ho pensato di segnalarvi che potevano essere utili anche i msg aggiuntivi visto che questi sono molto utili. Solo aprendo il file csv si capisce  che ci sono moltissimi altri audio NON di sistema... Mi scuso per la confusione ovviamente e per l'interferenza al vostro lavoro che state facendo per migliorare il sistema... Se avete bisogno di qualcosa fatemelo sapere che posso aiutarvi nelle traduzioni, etc... Saluti, Franco Dapporto

**Comment by mgsanna** [comment]
@bsongis @bsongis-frsky hello Bertrand is there any new procedure to give you the translated csv ? I saw the new "repo" for audio and display csv... so to be taken in account to get in new release of the firmware?
also for the manual is there something to do for getting updated link for new version?
thank for your reply

**Comment by bsongis-frsky** [comment]
Done. You may try to open a PR next time? It should be even easier to review

**Comment by mgsanna** [comment]
> Done. You may try to open a PR next time? It should be even easier to review

Hi Bertrand, first of all thak you, sorry for my ignorance what is a PR?
I'm a dumbass you mean Pull Request isnt' it?
sorry
