### ISSUE TITLE
X20 Ethos 1.07 endpoint moves when editing curves

### ISSUE THREAD

**Issue by Joetrin** [FrSkyRC/ETHOS-Feedback-Community#386]
When setting a curve editing the 2nd point moves the end point.  Video attached.

This is an unlisted video.  It shows the editing of point 2 on a multi point curve.  End points should not change when editing curves.

Thank You

https://youtu.be/PyQoQNtG-6A

**Comment by bsongis-frsky** [comment]
You showed your curve, but what is your mix? what is the input (and its value)?

**Comment by Joetrin** [comment]
![1622544478469391111707203442105](https://user-images.githubusercontent.com/19473795/120311317-58320e80-c2a5-11eb-9bd6-31334da8b060.jpg)


![16225445110711624198997316273228](https://user-images.githubusercontent.com/19473795/120311391-6c760b80-c2a5-11eb-8036-b0986eb30e96.jpg)

![16225445554195034518500026555690](https://user-images.githubusercontent.com/19473795/120311475-84e62600-c2a5-11eb-81a7-079b39ecd959.jpg)

**Comment by Joetrin** [comment]
Please see the photos above.  This was discovered because I was setting up the gas engine idle, transferring the model from my x12s / OTX to this x20 and ethos.

When setting up the curve to make the gas engine more linear in throttle response its common to create a curve in order to achieve linear response.

When I changed the shape of the curve higher on position 2 , the idle went up when the throttle stick position was at the lowest (idle) trim center.  To compensate, I had to change the output value to lower the idle.

This occurs in all models, I have 3 gas aircraft on this radio.

Hope this helps.

**Comment by bsongis-frsky** [comment]
Does it happen when the trim is at low position?

**Comment by Joetrin** [comment]
> Does it happen when the trim is at low position?

In this case, the trim was in the center position, I will test it when I get back from the office this evening, and post back the result.

Thank You

**Comment by bsongis-frsky** [comment]
I think there is a mistake in the Throttle Mix, the trim is applied BEFORE weight and curve. It should be applied AFTER weight and curve, otherwise the curve interpolation is impossible to adjust

**Comment by bsongis-frsky** [comment]
Please send me an email, telling me which radio / country you have, I will send you a binary with a fix candidate. Thanks

**Comment by Joetrin** [comment]
> Please send me an email, telling me which radio / country you have, I will send you a binary with a fix candidate. Thanks

jtrin@hotmail.com / Canada (FCC), X20 Dev Edition 

Merci

**Comment by Joetrin** [comment]
Tested with extended trims in -400 position and the servo does not move when changing the number 2 curve.

**Comment by Joetrin** [comment]
Tested with the beta preview firmware and it solved the issue.  Curves can now be adjusted without affecting endpoint.

Merci
