### ISSUE TITLE
Improvements ETHOS V1.5.x  with  If Then Else and a Counter

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3862]
Improvements ETHOS V1.5.x

I think we need some kind of If Then Else
This would simplify a lot of things in the log switches or the VAR

Also a real counter in the log switch or VAR is missing
with set, reset, up, down, preset, autopreset, ring counter 

So far you have to do everything very cumbersome in the log switch and VAR

**Comment by bsongis-frsky** [comment]
What is cumbersome?

**Comment by hrenz** [comment]
cumbersome
slow or complicated and therefore inefficient.

**Comment by PeterGraz** [comment]
I definitely support the request for counters (see post below).
