### ISSUE TITLE
Distance flown calculation

### ISSUE THREAD

**Issue by BarryCole** [FrSkyRC/ETHOS-Feedback-Community#3863]
In OTX is is possible to to make a Calculated Consunption line using Gspd as the sensor.  Although the result says mAH, it is actually Meters flown. It just needs Gspd added to the sensor list.  Could we get this added to 1.5.7 maybe.

Thank you for your help.

**Comment by bsongis-frsky** [comment]
I think OpenTX is right in returing mAh to a Consumption sensor!
What seems wrong to me is the choice of the sensor, GSpd should not be added to this list.

**Comment by bsongis-frsky** [comment]
Now ... back to Ethos, if you need a Distance sensor, why do you create a Consumption sensor?

**Comment by BarryCole** [comment]
That was the way that was suggested to me, and it works OK.
Is there a way this can be done in Ethos??? as it is now.
I am new to Ethos, and still learning.

Just to be clear, this is not Distance from a point as I think the Distance Sensor is. This shows the calculates the distance flown by the plane during a flight or a session. My glider tug flies 30-40Km during a day's towing.

Hope that helps.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/98c64848-ffb6-42dd-9b07-5ca116b3e64f)

**Comment by bsongis-frsky** [comment]
As suggested in #3864 it would be nice to ask such questions in forums (they are plenty on the web). While we answer such issues, we cannot do anything else

**Comment by BarryCole** [comment]
OK, Sorry about that, I will go to Forums first in future.

The Trip calc looks ideal for what I need.
