### ISSUE TITLE
Distance calculated telemetry it does not show values in the units section

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#3864]
When I try to create a distance- calculated telemetry sensor, nothing to select appears in units. 
X20 1.5.2

**Comment by jasalca** [comment]
Sorry, I´ve seen that it´s corrected.

**Comment by bsongis-frsky** [comment]
???

**Comment by jasalca** [comment]
In the simulator it works well, then  when I update my radio and I will you confirm if my problem has been solved

**Comment by bsongis-frsky** [comment]
May I suggest that you ask on forums (they are plenty on the web) before asking for help here? Because we are not a big team and while we deal with the questions we cannot do anything else!
