### ISSUE TITLE
1.5.6 Invalid Model Data

### ISSUE THREAD

**Issue by Swiss-Inside** [FrSkyRC/ETHOS-Feedback-Community#3866]
I made a new Model from Scratch, worked on that for more than 12hours yesterday and today.

Today i wanted to charge my X20s and after a restart, my model was invalid and the model wizard started.

cloning the model worked, but all Spezial Functions were gone and the Startcreen was empty
after that, i reorganized all spezial function and checked everything again. all worked. so i shut down the x20s, charged it and again
after restarting, my model file was invalid.

May this happens because i disconnected the usb cable and restartet the transmitter to fast.

**Comment by bsongis-frsky** [comment]
Would you send me this model?
There is some validity checks on model load, and perhaps one is not right

**Comment by Swiss-Inside** [comment]
Zip of the broken modell attached

**Comment by bsongis-frsky** [comment]
I see a check around a Play TTS function fails

**Comment by bsongis-frsky** [comment]
What is your radio? X20S or X20-PRO?

**Comment by Swiss-Inside** [comment]
X20S

**Comment by bsongis-frsky** [comment]
It is strange, X20S has no TTS! Or you have a global function PlayText which comes from another radio?

**Comment by Swiss-Inside** [comment]
i have about 20 special functions. all play .wav files converted with ethos suit to the x20s.

there are also 2  Vario Functions. 
one is activate vario
and the other is.

Play Audio - Play Value - flight height that comes from the gr6 plus

thats maybe that tts what you see.
because i added the telemetry today 

and also after the second try

**Comment by bsongis-frsky** [comment]
I see exactly 22 functions:
1) PlayVario ... OK
2) PlaySequence ... OK
3) PlayText ... KO

This PlayText is strange. Perhaps the PlaySequence is not correctly written? Trying to search what are its elements ...

**Comment by Swiss-Inside** [comment]
yes, 20 soundfiles and the two varios

it must be the telemetry height value on the vario

i will check this when im back home

**Comment by bsongis-frsky** [comment]
You have created your model from scratch? Or it has been (partially) imported from a X20-PRO?

**Comment by Swiss-Inside** [comment]
all from scratch

**Comment by bsongis-frsky** [comment]
I notice this in the Functions menu, which is not very good, if you have selected it, you will go directly to your issue!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8a42d91d-0c8c-4a93-9d23-33f3cebcaa1b)

**Comment by Swiss-Inside** [comment]
yes, i had an empty function to separate parts that user can change. that causes the issue? :/

i will try that, thx

**Comment by bsongis-frsky** [comment]
Yes, so we have nailed it. It will be fixed in the next nightlies, no more "---" there (it is PlayText on radios which have the TTS hardware)

**Comment by chrisca70** [comment]
> Yes, so we have nailed it. It will be fixed in the next nightlies, no more "---" there (it is PlayText on radios which have the TTS hardware)

The bug is still present on 1.5.7 @bsongis-frsky 

I just got a brand new X14S, installed 1.5.7 fresh, all is up to date according to Ethos Suite. I inadvertently reproduced exactly this same bug after selecting the "---" in the Special Functions Action dropdown menu. After this, and selecting another model and then back to the original model, it won't load "Invalid data". Cloning it creates a model with no screens, SFs, no sound.

**Comment by miguelportilloyaluk** [comment]
Hello, I have a similar problem after updating to 1.5.7, i get the MODEL DATA INVALID warning and it will not load my model. I tried deleting all the special functions, but I still get the same error. Could you look at my file and tell what could be the problem?
[orion.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15249097/orion.zip)
