### ISSUE TITLE
No telemetry data from X8R receiver in ACCST D18 protocol

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#3867]
Radio: X20S
Radio Firmware: 1.5.6 Flex
RX: Frsky X8R 
RX Firmware: ACCST_2.1.0_FCC 

The receiver works  on ACCST D16  with telemetry data but telemetry values  (RSSI &RXBatt) NOT SHOWED on TX screen (see attached picture). When I bind the same receiver on OpenTX the telemetry works.

I have tested as well Archer R10+ (ACCESS), Archer R6+ (ACCSS) , Archer R8/GR8 (ACCESS) and RX6R (ACCST D16) and telemetry data are ok

 
![20240418_141644](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/847e2ab1-4aa4-4806-962c-319750ba577d)

**Comment by mawzthefinn** [comment]
Did you bind Telemetry Enabled? 

D16 allows you to bind telemetry disabled, which would cause this.

**Comment by fdapport** [comment]
Yes I did,, from 1-8ch  (first option) and as well from 9-16ch (third option), same result.
The interesting is that on RX6R on ACCST D16 protocol (same of X8R) works

**Comment by mawzthefinn** [comment]
The only other item I could suggest is deleting the sensors and rediscovering. That can fix issues where the discovered sensors are not the sensor ID's being sent (possible to happen if rebinding different receivers to one model file).

If the RX6R works, then ACCST telemetry is working.

**Comment by fdapport** [comment]
I try as well to delete the sensors, rebind it, discovery it again, test in other model, same result. let see if others have the same issue with the X8R receiver.

**Comment by mawzthefinn** [comment]
I'll try and pull my only X8R out of storage and test

**Comment by fdapport** [comment]
Thanks,,

**Comment by pmullen503** [comment]
I have many X8Rs (most on UNI firmware) but all telemetry works just fine. Strange that it works in OpenTX but not Ethos.

**Comment by fdapport** [comment]
Did you try to create a new model and bind the X8R in 1.5.6? My old models created in the 1.4.17 with a X8R the telemetry works.. It is some thinks that happen during the bind process or in the telemetry discovery sensor process. I cannot delete the sensors from the old model created in 1.4.17 to understand if it is the sensors discovery process that create some thinks wrong. I will tray later today to bind the same receive on X20s version 1.4.17 to see if it is works or not.

**Comment by fdapport** [comment]
I made additional test:
1) I have the same issues if I use the X8R with  FCC or LBL firmware (v2.1.0) and X20S Ethos 1.5.6. 
2) I have telemetry information if I bind X8R with Open TX  Ver 2.3.15

Good news: 
3) With another X8R the telemetry date are OK with X20S, so the issues look like related to the first receiver.

In additional I will try to bind with another X20S ver 1.4.17 to see if some thinks is changed in the 1.5xx version.

**Comment by fdapport** [comment]
Today I have tested the same X8R with another X20S with version 1.4.17, same result. The issues it is not related with the 1.5.xx update. All the other X8R that I have works well, only one  X8R has "strange" behavior, no telemetry data on Ethos but telemetry data shoved in Open TX!!! . Please close  the ticket because look like that happen only for a specific OLD receiver!!.
