### ISSUE TITLE
VARs Action Percent limited to 100%

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3868]
Is there a reason that the VAR Action Percent is limited to 100%?
It doesn't seem unreasonable to want to increase a value beyond 100% especially if the VAR is being derived from another VAR
Of course one can use MULTIPLY and e.g. 1.1 but that's obviously rather more coarse.
Thanks

**Comment by bsongis-frsky** [comment]
What would be needed?
Today the range for all operations is [-100.0:+100.0]

**Comment by Jedsters** [comment]
I thought you may ask that  :) 
I wish I had a good answer, hence it was more of a question as to whether there was a reason why. 

If there is no specific internal limitation, then for me personally, I'd be happy with perhaps 150% (for now), however would suggest that maybe 500% may be more appropriate as that then fits in with other limits in VARs (e.g. Range)

If someone were to want more than 500% then they could still use multiply and the difference between 5 and 5.1 now becomes small enough to not make much difference in most instances (i.e. 2% rather than 10%).

Thanks!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b230bd34-ba4a-407f-b971-b744bd097d62)

**Comment by Jedsters** [comment]
Many thanks as ever!!
