### ISSUE TITLE
Issue with Version 1.5.6 & 1.5.4- Stabilization bleed through on channels 7 and higher

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#3869]
Install Archer SR10plus receiver, setup via the wizard:

X20S Radio
Firmware 1.5.6

2 AIL Channel 1,5
1 ELE Channel 2
FLAP 1 Channel 6
FLAP 2 Channel 7
1 RUD Channel 4
1 THR Channel 3

Stabilization setup:
Quickmode
CH5 - AIL 2
CH6- AUX 2 (Flap 1)
CH14 Stab Mode
Ch13 Pot1
Ch 16 EMERG

When activating AUTO level CH14 pos 3 AIL, ELE, and RUDER work fine. Channel 7 and higher move with the auto-leveling. Troubleshooting various items changed flaps to other channels higher than 6,7 one flap moved with the auto-level.

Installed version 1.5.4 same thing
Installed version 1.5.3 problem solved.

Please look at this and advise.

**Comment by mawzthefinn** [comment]
How is your Stab setup on Page 2 of the Lua.

The ETHOS version has no influence on Stab functionality. What you described can only be triggered by the configuration of the second Stabilizer set, on page 2 of the Lua. Stab set 2 enables stabilization on Ch7-9 by default, and optionally on CH10 & 11 (AIL4 and ELE4)

**Comment by ninodesposati** [comment]
Thank you for the info. Much appreciated!! Works Great
