### ISSUE TITLE
Trottle warning with a bug?

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#387]
You get a new radio with mode 2. You create a plane. After this you change in software from mode 2 to mode 1. If you switch off an on the radio now you will get the gas warning. So far so good.

If you move the right stick (Gas) to lowest trottle you will see on the display that it works right. But the warning will be not deleded. For this you have to move the left stick Elevator.

So graphic is right but function fault.

If it is desired that models created with mode 2 may not be changed to mode 1, then the graphic should not be changed over either.

**Comment by aviat40** [comment]
I had the same issue. Just delete the model created with the mode2 and create a new one after mode1.

**Comment by EngelMT** [comment]
@aviat40 You are right. This is the only way in the moment.
