### ISSUE TITLE
LBT option on 900M offers 25, 200 and 500mW

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3873]
1.5.7 nightly

I have just flashed X20 LBT to check something. I notice that in the RF module under 900M you can select 25mW, 200mW and 500mW. I don’t believe the 200 and 500mW options fit with EU law. As far as I know it is 25mW with telemetry and 100mW without.

**Comment by lthole** [comment]
Mike Blandford reported something similar here [https://www.rcgroups.com/forums/showpost.php?p=51191177&postcount=24962](url)

**Comment by Dsrenger** [comment]
I am very sure EU LBT on 868Mhz allows 25mW with telemetry and 200/500mW without telemetry (on a smaller  frequency band)

255/200/500mW should be fine.

**Comment by mawzthefinn** [comment]
Is this in TD or R9 Mode?

The latest TD receiver firmware forces telemetry to the 2.4G section if you set 900M power over 25mW when in LBT mode, so it's EU compliant

R9 will bind non-telemetry if set over 25mW in LBT mode.

**Comment by Dsrenger** [comment]
I just had a look at the german authority. (sorry, the document is german)

https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Frequenzen/Allgemeinzuteilungen/FunkanlagenGeringerReichweite/2018_05_SRD_pdf.pdf?__blob=publicationFile&v=7

25mW and 500mW are correct for 868Mhz. 200mW falls unter the 500mW regulatories.

**Comment by rwijnhov** [comment]
Even with flex you don't get telemetry higher then 25mw. Also rssi and lqi are reported of the telemetry channel. So lqi 0 rssi 0 but still a lot of reception. Something is not working right I allready reported this. Also radio believes receiver is still on while it is off.

**Comment by mirko91** [comment]
Just use the power you wish and leave the other settings for the people who needs it. I don't feel cutting on settings will be a good option.

**Comment by mgsanna** [comment]
> Even with flex you don't get telemetry higher then 25mw. Also rssi and lqi are reported of the telemetry channel. So lqi 0 rssi 0 but still a lot of reception. Something is not working right I allready reported this. Also radio believes receiver is still on while it is off.
Try to reflash your TD ISRM (internal module to 2.2.6)  all work good after... @rwijnhov 
try it

**Comment by rwijnhov** [comment]
Hi i am already on 2.2.6 and this issue is on both my x20s and my x18 so that would mean that both radios 2.2.6 hasn't upgraded right. I don't believe that is the issue.

**Comment by lthole** [comment]
I think this can be closed.

As mawz pointed out “The latest TD receiver firmware forces telemetry to the 2.4G section if you set 900M power over 25mW when in LBT mode, so it's EU compliant

R9 will bind non-telemetry if set over 25mW in LBT mode.”
