### ISSUE TITLE
Simulator to support lua

### ISSUE THREAD

**Issue by craigywsm** [FrSkyRC/ETHOS-Feedback-Community#3874]
I am running x20S simulator version 1.5.4 
I have added the RDT Lua script into the scripts folder https://github.com/i3dm/Zavionix
into folder C:\Program Files (x86)\FrSky\Ethos\X20S\scripts\RDT

I get this on the page:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40343747/64014e3a-b8c8-49e5-819d-cebb943a23a6)

**Comment by strgaltdel** [comment]
from a user's point of view:
Unfortunately, you have not provided any supportive information.

Basically, the simulator also works very well for Luas,
i think lior spent most of his time with the sim when developing his scripts.

are you using a template that supports all the sensors you need, and the rf section is active so that sim can pass-trough the values ?

Could you start the sim from the command shell so that you can read error messages if existent?

regards

**Comment by craigywsm** [comment]
Thank you for your message. 
I assumed that it did not support lua as nothing was showing on the page. 
I am now confused on how my setup is not working. 
I gave the latest script from his website. 
I know he has not migrated to 1.5 yet and I wanted to check compatibility with his script and 1.5
Back to the drawing board

**Comment by i3dm** [comment]
I have migrated some of my radios to 1.5.x and the RDT script works perfectly on them (i do recommend latest version from git for minor adjustments made).

here is RDT running on X20S 1.5.4 sim:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/da06dda4-495a-40aa-9366-dbf4df4ffd53)

so you are definitely doing something wrong, maybe missing some files? here is how the RDT folder should look like when properly installed:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/b769685b-fc40-45bb-a87e-81214c2a1de8)

**Comment by i3dm** [comment]
i understand the issue after looking at your photos again.
RDT is designed to run on FULL SCREEN layout, and you are using a different layout.
choose the layout that says FULL SCREEN:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/89aa1bf9-06b0-4828-a3ab-18f997810406)

**Comment by craigywsm** [comment]
Thank you Lior it was the full screen issue. Thank you both for your help.
I could not find a ticket relating to the simulator running Lua so should help others now :)
