### ISSUE TITLE
How to deactivate a selected screen using LUA script

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#3875]
Hello Bertrand,
I'm in the process of writing a flight log, so far everything works on the touchscreen transmitter.
On the X10 I select the screen by pressing the scroll wheel.
But how can I leave a selected screen using a LUA script, without waiting until it is no longer selected?

Thank you
Benno

**Comment by robthomson** [comment]
How about using the events to detect the back button and moving around your navigation?

Are you using the forms system?

**Comment by Benno00** [comment]
Hello,
no, not a form, I use the normal widget screen, I solved it with the PgUp/Dn and RTN keys.
