### ISSUE TITLE
ETHOS V1.5.x  Play Audio Play File should be global possible with Log Switches

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3878]
Improvement V1.5.x at spezials funktions, 

Play Audio, Play File, Play Vario should be global possible with log Switch too

its all not safety-relevant

**Comment by bsongis-frsky** [comment]
1) Play File doesn't exist anymore
2) Play Audio can be global already, provided all his dependencies are global
3) Play Vario depends on a sensor which is only valid in one model, so NO
