### ISSUE TITLE
Request - Model Select under System tab...seems odd.... could it be under Model tab?

### ISSUE THREAD

**Issue by TWSreviews** [FrSkyRC/ETHOS-Feedback-Community#388]
Seem odd that the model select is under the System tab but all the model settings are under the model tab.
Would it be better if the 'select model' and 'create model' etc was under the model tab.

Would be more logical

**Comment by loetefix** [comment]
And pressing the MDL key long to open the model select page would be also nice.

**Comment by bsongis-frsky** [comment]
I will take your idea in 1.0.8
