### ISSUE TITLE
GPS logging info

### ISSUE THREAD

**Issue by BarryCole** [FrSkyRC/ETHOS-Feedback-Community#3881]
Is it possible to have the Lat and Long info in one column rather than two.  And titled GPS.
Just to be clear, this is so that I can use the OTX Logs, to get a flight plot on Google earth. (Unless there is another way.)
This is very imporant to me as i have to be able to prove where I have lflown.

**Comment by KevinFairgrieve** [comment]
> Is it possible to have the Lat and Long info in one column rather than two. And titled GPS. Just to be clear, this is so that I can use the OTX Logs, to get a flight plot on Google earth. (Unless there is another way.) This is very imporant to me as i have to be able to prove where I have lflown.

This in my opinion is a basic and should be included. Importing files into google is a very good way to see if you have for example  flown over "No Fly Zones" 

A feature I miss that I hope an ETHOS Suite will provide one day.

**Comment by Richrfl** [comment]
I agree with this one. Although it is not a big deal, if it does not take a big job, it would be convenient.

**Comment by BarryCole** [comment]
> I agree with this one. Although it is not a big deal, if it does not take a big job, it would be convenient.

It's a big deal for me.....

**Comment by Richrfl** [comment]
Understood Barry. I understand you have to "translate" every single Lat/Long to Google format to be able to create the flight plot, and that is a hell of a job. This is something nice we had in OTX companion. I guess that priority on this will depend on how many users have the same requirement as you requested.

**Comment by BarryCole** [comment]
Any movement on this??

**Comment by BarryCole** [comment]
Any movement on this issue.  GPS logging is pointless as it is. 

Please sort this out...

**Comment by BarryCole** [comment]
Is there any movement on this as it is stopping my purchase of an Ethos based Tx.

**Comment by BarryCole** [comment]
Bertrand,Thank you so much


Best RegardsBarry ColeHampshire UK07962013388
 

    On Tuesday, 18 June 2024 at 14:23:19 BST, Bertrand Songis @ FrSky ***@***.***> wrote:   

 


Closed #3881 as completed.
