### ISSUE TITLE
Show values in curves

### ISSUE THREAD

**Issue by mirko91** [FrSkyRC/ETHOS-Feedback-Community#3883]
Hello, I think it woukd be nice to show the values on a curve with vars as source, not just the var name, maybe on the left.
![IMG_20240420_181005](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6129016/bd619218-1352-404f-aa92-7bb3da202e96)
 See the picture

**Comment by robertobrazill** [comment]
Even better than that would be if the curve graph could move when moving the stick, so we would know exactly where to adjust.

**Comment by mirko91** [comment]
> Even better than that would be if the curve graph could move when moving the stick, so we would know exactly where to adjust.

That is a great feature as well

**Comment by pstasek** [comment]
The thing is, the same curve may be used in various different places throughout the model. Not sure if showing the position would be possible as there's no input specified for it.

**Comment by mawzthefinn** [comment]
> The thing is, the same curve may be used in various different places throughout the model. Not sure if showing the position would be possible as there's no input specified for it.

The complaint I believe is the VAR name instead of the value is displayed in the curve editor. Ideally both should be displayed.

**Comment by mirko91** [comment]
> > The thing is, the same curve may be used in various different places throughout the model. Not sure if showing the position would be possible as there's no input specified for it.
> 
> The complaint I believe is the VAR name instead of the value is displayed in the curve editor. Ideally both should be displayed.

Spot on,  because now in order to know the point of the curve value you need to go to the Var page

**Comment by robertobrazill** [comment]
I have several giant planes, and I do servo balance on all of them, and this feature is available on almost all radios on the market, and especially on the Jetti, this procedure is super user-friendly. If our FRSKY wants to gain market share, it will need to make these additions. I'm almost getting rid of my 20S to buy a Jetti, precisely because I really need this feature, and at my track, several pilots don't migrate to FRSKY due to the lack of this feature.

**Comment by strgaltdel** [comment]
the principle of combine the "X" values delivered by Inputs into a Graph in form of a moving bar or whatever and displaying the corresponding Y-values is merely possible in a situation where you have dedicated  "one by one" assignments between Inputs and curves.

Ethos allows a much more flexible way of curve usage

So we would run into problems in case curves are used by multiple inputs, which input should be choosen ?

First idea could be to establish several classes of curves
- curves used in canned mixer, a curve can only be assigned to one mixer, so we do fulfill the 1 by 1 requirement
- curves used in outputs for servo alignment, the summed up mixer output of a channel is the curve input
- free curves which can be used for several (free or whatever) mixers, no further visualization


i don't know if the majority of users would see the tradeoff between convenient curve visualization and increase of complexity as an advantage in sum.

at least i would say that an implementation that would combine ease of use and function is not "easy going"
