### ISSUE TITLE
curious UI-performance boost when using suite's devtools

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3884]
this weekend i wanted to migrate a model from oTx to Ethos
i did use a more "fat template" , configures with only one (beta) widget for quick Var adjustments

i'm used that a fat template can produce a sort of "slow" UI behavior together with luas
(specially when a lot of telemetry or source reading comes in play), you can hear a liitle bit stuttering in audio voices etc..

something was not completely OK in the script and so i decided to use dev-tools in an "in vitro" situation , which means model remained switched on .

I was very astonished when i realized that after switching into serial/debug mode the UI performance was much better on my X18.
i'd the feeling the transmitter was on steroid, got one more core or was overclocked (-;
i couldn't see any trade off, all functions seemed to work on my model.
Even after disconnect the tx, the performance remained the same.

Of course, after cold-boot of Ethos, the "old and slow" UI was back.
Effect is reproducable, so i made a video.

some notes:
(1) without any lua the UI response is very fast on a fat template, so "slow down" seems to have something to do with luas
(2) in this case the lua is not a big one, most load maybe caused by reading a bunch of Vars, but even after preventing creating sources or reading them, slow down could be recognized, i wasn't able to identify any "crude load " last evening, but of course never would rule out it's my bad coding (-; 
(3) it gives me the impression that cold boot of ethos and initiating / calling a widget causes a kind of glitch / not executed garbage collector / leave some needless background tasks which are "cleaned" by the suite's dev tools switch over

because i really have no idea what the "trigger" for the "slowdown" or the "dev tool boost" is, i decided to zip a representative sdcard content, including the model template "sharon42b"
i would be very pleased if the "boost" could become a standard feature 
(and forgive me for the noisy video, in parallel we had some database reorgs at the company that evening, was in a hurry)

regards
Udo 

video link
https://www.youtube.com/watch?v=UfdAjLogyiE

sdcard:
https://www.transfernow.net/dl/nand

**Comment by WhiskeyGolf** [comment]
I have the same problem that the UI becomes very slow on some Luas.

**Comment by bsongis-frsky** [comment]
Is it still valid with 1.5.12?

**Comment by strgaltdel** [comment]
.. just updated to 1.5.13,
and yes, still valid (-;

performance boost by using suite 1.5.9 dev tool ...

**Comment by bsongis-frsky** [comment]
This one is fixed in 1.5.19 already
