### ISSUE TITLE
after dev-tools commanded Tx restart, the channel values may temporarily gain undesired values

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3885]
as described i  the issue before, i used dev-tools in a situation where the model was switched on.
thought that during a short "rf inactive" situation failsafe config would prevent any suprises.

what you can see in the videolink happened app. in 30% of the cases (during switch over from suite to debug mode)
The motor is spinning up for a while !

didn't perform further investigations, i assume RF is activated before mixer loop was initiated, and so channels delivers 0% which means 50% throttle.
when mixer loop is ready motor is shut down

all the time in the video the tx-"motor kill switch" was enabled, and i didn't touch anything on the transmitter

regards  

video:
https://www.youtube.com/watch?v=aCt0GFU_r5k

proposal (at minimum)
- in case dev tools are not intendet to use them with model switched on, there should be a hint
- in case it should be allowed to use dev tools with an activated model AND the boot process cannot be changed, i would say that a warning message on the screen regarding short "unintentional signals during reboot" is a must have.

**Comment by bsongis-frsky** [comment]
Your channels are calculated from channels which are defined later.
For example if CH1 depends on CH20, on first mixer evalution, CH1 will be 0
