### ISSUE TITLE
Playing Audio does not work

### ISSUE THREAD

**Issue by radieserl** [FrSkyRC/ETHOS-Feedback-Community#3886]
Hello,
I have custom Audio (.wav) files to say "Engine ON" or "Engine OFF".
They worked in the past.
But with the new firmware versions I can't select a .wav-file in the special function "play audio"
-The audio storage location is set to "Radio" (SD card doesn't work too)
-In the file manager the .wav-file can be played.

Thanks for your help!

**Comment by Alex00101** [comment]
If you have upgraded to 1.5.n - have you set up voices in system settings?

**Comment by strgaltdel** [comment]
https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-(S-HD)-X20R-(RS)-X20-Pro-(AW)-Tandem-24-Channels-with-ETHOS/page1551#post50718883

would assume lothars 1.5 Ethos manual has infos too

**Comment by radieserl** [comment]
Thankyou for your help! That fixed the problem
