### ISSUE TITLE
RF Recommendation: Log Files and Range Check should Indicate Receiver by Unique Identifier

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#389]
It would be amazing if there is a way to have the Receiver (whatever information that may be) show in the log and also during range checks. This would help distinguish which receiver's log is being recorded should the redundant receiver become the main RF link at any specific time or for a moment.

This information would help greatly during Field Range Checks and also Log Reviews as it will be a clear indication of a failover to the redundant receiver or back to the main receiver. 

This would also assist in all sorts of RF troubleshooting scenarios.

Thanks!

**Comment by bsongis-frsky** [comment]
You may log the Rx sensor

**Comment by pld74** [comment]
> You may log the Rx sensor

So in the log, I can see which receiver is being logged including when the Redundant Receiver took over? How does that show? How does it indicate?
