### ISSUE TITLE
Text on focused block hard to read on Light Mode (text color invert)

### ISSUE THREAD

**Issue by FireflyJar** [FrSkyRC/ETHOS-Feedback-Community#3891]
Dark theme inverts the color but not the Light theme. see the last screen shot, you can't read the number when block is focused.   
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17463234/7ba7ca8e-dce5-423b-bb23-cb07c6552077)

**Comment by FireflyJar** [comment]
another invert issue
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17463234/9f7963be-f7f5-4633-b68f-184f4ee36419)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4c6eeb2a-47f0-4492-9832-52bd0bf3e78a)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/09888a7f-701c-4fa0-ace1-cb1999eba241)
