### ISSUE TITLE
X20PRO 1.5.7 Nightly announcements maximum volume too low!!!

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3892]
The announcement volume is too low with the current Nightly at full volume.
In the room ok, but on the airfield when you are no longer alone too quiet.

That was much better in 1.5.6.
Then please bring back the noise when switching on!

Greetings Eugen

**Comment by bsongis-frsky** [comment]
This one has been fixed this morning. It will be included in 1.5.7
