### ISSUE TITLE
Select model at power on interferes with Suite switching 

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3894]
Ethos 1.5.7

If I have 'Select model at power on' turned ON, it interferes with Suite switching to Ethos Mode. I think Suite does not get the expected response in time.

**Comment by bsongis-frsky** [comment]
What is the problem? I am trying to reproduce this problem and I see no real issue

**Comment by bsongis-frsky** [comment]
This issue seems gone. Tests done on 1.5.13
