### ISSUE TITLE
Suite 1.5.4 on Mac - English not shown as option in Display Language area as it is in the Audio Language area

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3896]
Obviously it drops as a default language. It would be nice and confidence inspiring to see the language sections have the same check boxes.

**Comment by Nicholas-Luoyi** [comment]
It's bug in release...

**Comment by bsongis-frsky** [comment]
English is not an option. It is included inside the firmware, it's the default language.
I do agree that it is confusing as it is right now. Another checkbox for English should be added, while being:
- checked
- disabled

**Comment by Nicholas-Luoyi** [comment]
Sorry that I misunderstood your problem. Now it has been changed like this

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/7a8b76c0-8473-4515-8195-ba7fe8524d67)

**Comment by spoke2570** [comment]
Thanks Nicholas, Bertrand. I appreciate your efforts.
