### ISSUE TITLE
Suite 1.5.4 on Mac 12.7.4 - Radio drives not registered in suite but show in OS

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3897]
I just updated to 1.5.7 
Ejected drives 
unplugged radio
(Did NOT quit Suite)
Plugged radio back in
Drives were not present in Suite but shown in Mac OS 

Flipping back and forth between Ethos and Bootloader modes did nothing

I am attaching the log file for today from Suite.

->It has now been many (5 to 10 ?) minutes and the drives are now visible in Suite right after I flip the Debug Mode switch in Suite/Settings. Maybe that one successfully asked for a connection? Attaching that file as well.

[main-20240423.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15077421/main-20240423.log)
[debug-20240423.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15077422/debug-20240423.txt)

**Comment by spoke2570** [comment]
The OS regarded Suite as quitting unexpectedly even though all best practices were used in quitting the app. Attaching that report from Mac OS.

[OS12.7.4_close_Suite_problem.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15077553/OS12.7.4_close_Suite_problem.txt)

**Comment by Nicholas-Luoyi** [comment]
Can you help to confirm the drives are missing, or the contents in the drive are missing?

**Comment by Nicholas-Luoyi** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/ae5a2cd8-2666-47b0-9320-91bbd6cc75ed)

This is the situation that drives are detected successfully but contents are missing.

**Comment by spoke2570** [comment]
Yes, like your image. Drives are present for Mac at this point.

**Comment by Nicholas-Luoyi** [comment]
OK. Then drives are successfully detect by Suite. But contents are missing. Suite searches the files which named as audio/bitmap.version to check the contents.

**Comment by spoke2570** [comment]
makes sense. The only operation that happened between the contents being seen and before was toggling the debug mode switch which also prompted the very brief file.

**Comment by Nicholas-Luoyi** [comment]
But if you can confirm the version file is there without any changes. It may be a bug that Suite didn't find the file.

**Comment by spoke2570** [comment]
Definitely. Suite noted that I had an X20S attached and the Firmware, Bootloader and Module versions were present (Green box) ... Hm weird The firmware version was green for this error after going to 1.5.7 It is orange now as greater than current....
SD Card and Flash were not present. (no color box nor text).

**Comment by spoke2570** [comment]
The radio storage and flash memory available lines were not shown as your picture. The screen was as if the drives have been ejected but the radio not unplugged.

**Comment by spoke2570** [comment]
It does take some time for SD and Flash to load normally. Maybe it took some time because of the update? More checks, etc?

**Comment by Nicholas-Luoyi** [comment]
How about the issues in 1.5.5?

**Comment by spoke2570** [comment]
So, far I have only loaded 1.5.5 up a couple times. The SD card took its own sweet time to register, but Suite responded an instant behind the OS. The flash drive loaded with the swiftness. It did do the quit unexpectedly even though the drives were not present and the radio was unplugged and then CMD+Q to quit. I mad late for work this morning (US EST), so I did not save a report on that part.

**Comment by Nicholas-Luoyi** [comment]
Thanks. Would you please close this one after using for a couple of times and being sure it has gone?

**Comment by spoke2570** [comment]
Yes. Tomorrow evening I will close or update this thread.

**Comment by spoke2570** [comment]
Working in 1.5.5
