### ISSUE TITLE
Calculated sensor Trip wrong source selection

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#3898]
TW X14 Ethos 1.5.6

When I try to define a calculated sensor for trip (I think that this is the distance flown)

![trip calculated](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/e1655638-11e5-4b46-a2b8-29d2f14a3144)

I do do get the wrong selection. I think I need GPS (thats available in EdgeTX for a calculated sensor for Trip)

![selection](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/df0c9ec4-44b9-4483-a6e5-17b16f4998b8)

**Comment by bsongis-frsky** [comment]
I think EdgeTX also uses the GPS speed to calculate the trip length

**Comment by glipski50** [comment]
Here's a screenshot from EdgeTX trip calculation, it's GPS. (EdgeTX v2.10.0-rc3)

![Trip EdgeTX](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/1b0e6f34-6d7c-4c2d-81f6-25968616ea54)

I'm assuming, Ethos uses the same formula as ETX to calculate trip lenght.

**Comment by mawzthefinn** [comment]
Distance traveled is speed over time. GPS Speed is ground speed, so is the correct value to be calculating from.

**Comment by glipski50** [comment]
Thanks

**Comment by bsongis** [comment]
EdgeTX uses the GPS, not the GPS speed. I wonder which method gives the best results.
~We could also do both in Ethos~
We do both in Ethos

**Comment by glipski50** [comment]
I will do some comparison the next days, driving a car, so I will have same distance.

**Comment by glipski50** [comment]
In preparing test i noticed that I have confused things. In Ethos the calculated sensors for distance (calculated from GPS) and trip (calculated GPS speed over time) work fine. In EdgeTX there is only a calculated sensor for distrance (calculated from GPS) but no calculated sensor for trip. Trip would need a lua script.

So things work fine in Ethos. Sorry for creating some confusion.
