### ISSUE TITLE
VAR1 returns value 0 at start

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3899]
Hello, 
i'm not sure if it's a mistake.
![VAR1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/2e8dc980-ba2f-4132-90b5-dbadf7781fbd)
When the transmitter or model is started, VAR1 should return the value 1.0 (see illustration). This causes the last action in Var1. It also does this if you check it again

![Wert0](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/6bedb038-11ff-4dff-aaf6-7d1705117849)
However, the effect occurs that at the very beginning not 1.0 is generated, but 0.0. Value0 generates the announcement "no sensor selected" and value1 the value of the height announcement. I am currently avoiding the value 0 by setting a delay time (see picture) of 0.1s. 
Now my question: is it correct that a VAR outputs the value 0.0 at the start in the first step and only then the set value?

**Comment by mawzthefinn** [comment]
VAR's are evaluated in the main task, not the mixer task. It looks like the VAR is initializing after the LSW initializes.

**Comment by Wolepo** [comment]
Do I understand correctly that the LSs are initialised first and then the VARs? Then why should the LS be active for a short time if it does not receive a unique value for evaluation? If this were really the case, then all 13 other LSs that have this VAR (0 to 14) would also have to be active. But it is only value0

**Comment by mawzthefinn** [comment]
The better description is that LS's may be initialized before the VAR's.

**Comment by mawzthefinn** [comment]
I've been corrected on my post above

VAR's are processed in the mixer task, but after LS's.

**Comment by bsongis-frsky** [comment]
Exact, the Vars are processed AFTER the LS

**Comment by Wolepo** [comment]
Ok. So I have to live with the delay.
