### ISSUE TITLE
1.5.7: as a follow up to #3813, background not shifted when formFields are...

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3900]
Hi,
just a tiny "glitch"

as a follow up to #3813 (closed)
Formfields are now shifted when needed, but not the background:

this is OK when script is a widget
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/7303511d-8c48-4aa8-b278-01c1b6d7fc01)

now as a systemTool:
the fields are shifted correct, but the background stays as before

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/46674d17-8bdf-4a14-8afd-4345c43f4544)

.. at the moment i can live with the situation, we reached 95% ((-:

more of interest would be to enable the speed boost mentioned in #3884 (-;
(if possible)

thanks & regards
udo

**Comment by bsongis-frsky** [comment]
Would you please have another check on latest 1.5.10 nightlies. This part has been mostly rewritten, perhaps the issue will be fixed in the same shot?

**Comment by strgaltdel** [comment]
Tested on sim, worked perfectly !

start screen:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/ee71d625-20d8-4672-bf15-7a7bd16fcc2f)



edit last row:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/07ba4e14-46dd-43f9-ae8b-fa7b5ffd6aad)



much thanks !!
