### ISSUE TITLE
form addition - numberSlider

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#3904]
Please look at adding an additional number slider element for lua devs to use.

See attached

![number-slider](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4599545/c9227c44-d475-4cbf-8dbc-6f6ba641fe57)

**Comment by bsongis-frsky** [comment]
The same screenshot that #3908, where does it come from?

What is the vertical line at thee right of the slider, it looks like a bad photoshop capture ;)

**Comment by bsongis-frsky** [comment]
Continue the discussion in #3908 as I have already given the url to our UI designer
