### ISSUE TITLE
Request predefined values on Number Value Slider

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3908]
We currently have an infinitely variable number value slider as below. 
While this is a very clever idea in theory, and hats off to whoever came up with that idea, in practice I don't find it works so well. 

Currently one can move the slider but it's a guessing game as to what the result will be and although it could help you get to your desired number more quickly I find it's usually just quicker to leave it on minimum and rotate the rotary coder for a few seconds, unless you have a range of e.g. +-500% or similar.

However, I believe it's use could be significantly enhanced. 

Rather than being infinitely variable, would it not be more useful to have predefined increments on it so that we can quickly select how much we want to increment the number by? My initial suggestion (without having been able to test it) would be where a number can be incremented by 0.1 then the increments could be e.g.
0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 25, 50. 
if a number can only be incremented by 1 then this could perhaps become
1, 2, 5, 10, 20, 25, 50, 100

I guess this depends on space and if space is short then some of the numbers could be dropped, perhaps the 0.2, 2, 20?

I may be asking the impossible, but it would also be nice if that increment could be remembered on a per use basis, e.g. if I select 2 for channels remember that for all channels etc. and if I select 5 for VARs remember that - although I have a feeling that it's not as simple as that, so I'm less concerned with this bit. 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/f97304cf-9e62-4fee-9197-9beb11309c39)

Thanks as ever.

**Comment by Jedsters** [comment]
Edit, as an aside, is there a minor inconsistency here? I notice that in some places we have a simple slider as above, while elsewhere we have more of a volume bar (triangle). If this suggestion is implemented I suspect that would however fix this. Not that it makes much odds, it just makes things more consistent. Thanks

**Comment by strgaltdel** [comment]
even by using a sim i don't catch the max or min setting in all cases.

i would go further and propose a
0.1,  0.5,  1,  5,  10 series

scrolling from -40 to +70 for example would be easy going with the scroll wheel and stepping 10.
The more precisely you can hit the desired increase rate, the better the user experience

from my point, 5 different steppings would be ok.
one should be able to reach the desired value with only 1, max 2 switch overs, so too much different rates wouldn't give an advantage, imho

**Comment by Jedsters** [comment]
I'd have no concerns with Udo's modification to my suggestion, although would suggest that where values can exceed 100 (e.g. VARs) then it would still be worth adding 50 to his list. Trying to go from -500 to +500 in increments of 10 would otherwise still be tiresome. 
As an aside, I've often considered whether there should be an option to make a value 'negative' which would help a lot in some circumstances, e.g. if you are at -500 and a change you've made means it needs to now be 500 it would be nice to have an option which does it in a couple of clicks, but I'm not sure if that would need to be a separate issue.

**Comment by bsongis-frsky** [comment]
What is the screenshot you have posted above? I am not sure it comes from Ethos

**Comment by bsongis-frsky** [comment]
If we have somebody good at Photoshop, don't hesitate to post some good screenshot showing the idea!

**Comment by Jedsters** [comment]
The image is from page 9 of the 1.5.5 manual under the header Number Value Controls. I assumed it to be correct, although now I check my tx at 1.5.6 I see that does have a triangular volume bar for the Channel Outputs, so my comment about inconsistencies is incorrect, please ignore that bit. I was just looking through the manual for a picture I could use to demonstrate the slider I was talking about and that was the first I found.   

I'm not the best at photoshop, however can probably cut and paste elements from the manual to give a crude indication for a couple of suggestions - although if Udo or anyone else is competent with photoshop please feel free to post suggestions!

Thanks

**Comment by Jedsters** [comment]
Just for clarity, this is the current state of play (taken from 1.5.6 sim which I should have used yesterday!)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/3f847e39-60b5-4e67-82ac-99c23b2fa9fd)

**Comment by Jedsters** [comment]
Initial thought (I'm sure it'd look better without the random white lines at the edge of my pasted numbers - seems to be an artefact of the s/w I'm using).
We have the width, why not use it?  Could be extended to the entire width I guess if needed for more fine control?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/2226dfe7-6c3b-4da6-9832-8051b0e79004)

If anyone has any thoughts, comments or feedback?

Or if we want the 50 option for when the numbers exceed +-100 then ...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/e9abdf99-123b-462e-b32d-8de4acacce15)

Obviously the numbers would be a gap in the slider where you can reliably touch to get the number and for those who like the current setup it gives an indication on the volume bar of roughtly where they need to touch to get e.g. 7.5 (naturally half way between 5 and 10).

In honesty, my initial suggestion of adding 0.2 etc would make it too cluttered, so I agree with Udo aside the possibly addition of 50. 

Thanks

**Comment by Jedsters** [comment]
Another possibility 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/a512e374-d0a3-4a48-aa87-40d52fecd22a)

**Comment by bsongis** [comment]
I see you have talents on Photoshop :)

**Comment by Jedsters** [comment]
I think I prefer the former as it's clearer what the numbers mean, although I accept that programmatically it would be harder and some may like the existing slider and not want it messed with - although I reserve the right to change my mind when I look at it later!  ;)    Maybe if the latter was used the Min Default Max could be moved to the left and a title given to the numbers of 'Fixed Adjustment' or similar?

**Comment by pstasek** [comment]
May I propose this? I think it would be fast and precise enough.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/c3d2c207-51c1-436c-937a-964c6ae83bc6)

**Comment by Jedsters** [comment]
I'd be happy with that, it's certainly simpler, I just didn't want to upset anyone who liked the volume bar.

**Comment by robthomson** [comment]
The resolution button bar works well - but I wonder if it will cause an issue if using the step parameter?

**Comment by frskyrc-ben** [comment]
Similar request to what is proposed #1769

**Comment by bsongis-frsky** [comment]
![a4e31c2afb655136c5cd990c796f616](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5782390e-d0df-449f-88cb-145f7dafad7a)

**Comment by Jedsters** [comment]
Looks good. Could that easily be lowered a bit and that section of the screen made smaller so more can be displayed above? 
Not a big deal, just trying to get the best we can have. 
But thanks, that will make changing values a lot easier.

**Comment by jurajjurej** [comment]
I would add a zero icon.
![Screenshot_11](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/a07102a8-56d3-4350-a20b-ff0714432eac)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/e53566b6-0bd9-4ad0-a346-baf00e85fe2d)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9e17cfeb-2ebd-490e-8e2d-3d370c46a621)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b36543b6-2edf-44d1-9781-22de5820195a)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d224dd17-2e69-406c-8d56-3068792a5649)

**Comment by bsongis-frsky** [comment]
> I would add a zero icon.

Default and Invert buttons added.
But if somebody has good photoshop talents, I will appreciate some help at finding some nice icons instead of Text buttons

**Comment by jurajjurej** [comment]
icons
[Uploading status-icons-set-by-iconleak.zip…]()

**Comment by bsongis-frsky** [comment]
It seems that the link is broken!

**Comment by jurajjurej** [comment]
icons
https://www.softicons.com/toolbar-icons/status-icons-set-by-iconleak

**Comment by jurajjurej** [comment]
+/- icon
![plus-2262604_1280](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/f56b809e-88b8-4c72-bbf9-caf6a164e443)

**Comment by jurajjurej** [comment]
+ and -
![Uploading plus-24572_1280.png…]()

**Comment by jurajjurej** [comment]
![plus-24572_1280](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/c1fce2d8-0e0c-4a70-9bd2-29ac8964fedb)

**Comment by jurajjurej** [comment]
![Screenshot_4](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/2e207af1-a271-4b94-b333-87890cd1bf54)

**Comment by jurajjurej** [comment]
![Screenshot_5](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85956904/d2b0bd72-beda-4518-ac70-97f7f0458e59)

**Comment by robthomson** [comment]
I worry those icons are not in the ethos style.. But I get the idea

**Comment by jurajjurej** [comment]
It's for inspiration

**Comment by bsongis-frsky** [comment]
Inspiration is already there, now I need someone with photoshop talents ;)

**Comment by Jedsters** [comment]
All looking good, love the +/- we need that! The number of times I've had to adjust a curve point from e.g. +80 to -75 or similar - wheee on the wheel!

Not quite sure what you're after format wise, however I quite like... 

https://iconduck.com/icons/296602/sign-plus-minus (open source)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/38933dde-9c30-4087-828f-5e230cd6487b)

or 

https://www.iconsdb.com/black-icons/plus-minus-2-icon.html (which I believe is free to use)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/11e1ad80-c865-45bd-9151-ae41e250dbc9)

both of which have + and - available in the same series for consistency. 

Does that help? If not I need more guidance.  

Thanks!!

**Comment by bsongis-frsky** [comment]
I come back with some new screenshots. Fewer buttons. More functions.

- Customizable step (with unit)
- Big + and - buttons
- A "More" button for more actions that you don't need so often

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9425a89d-31be-4769-aed1-3a4f25a51e06)

- Menu opened when pressing the "More" button

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/39b03118-b462-48d8-9e14-e36cc65e87d0)

- Slider input method (if you choose the "Toggle slider" in the Menu above)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/cda6d447-e58b-4232-ac4c-ac5d07634d7a)

**Comment by robthomson** [comment]
I think this is really shaping up well.  Give user allot of choice about how to enter stuff - and of course ties in well with the existing layouts.

Do you have a visual that also shows the 'help' text?

I wonder if the 'help text' could potentially have a max of 2 lines.. with the text box expanding upwards if required?

**Comment by Jedsters** [comment]
Looking like it will keep most people happy. It'll be interesting to see how it works.

**Comment by bsongis-frsky** [comment]
Help text? Like this?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0eb50cd8-d55c-4b74-9d3c-317ee5f91e8d)

**Comment by robthomson** [comment]
Perfect

**Comment by bsongis-frsky** [comment]
Because Rotorflight is so complex ... you will perhaps need multi-lines in the Help panel?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d792f352-6f9f-4aa5-bcd0-7313bbca04b8)

**Comment by hrenz** [comment]
compare a solution to #3080, and we have a touchscreen
V1.50 Input field not optimal improvement Steps #3080
optimal for touch-pen input, not for a slider
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/7f9fff57-3b0e-4d60-ad80-e8d84fedc3a4)

**Comment by robthomson** [comment]
I think in the end the lua input should have parameters to say..

- enable slider
- enable input
- enable both

Etc...

The end result is that you as a lua dev could choose the options that work best for your app. 

There will never be a 1 size fits all.

**Comment by frskyrc-ben** [comment]
Sorry to comment on this closed issue but would it be possible to set the default increment value to "1%" instead of "0.1%" ?

![image](https://github.com/user-attachments/assets/2ca08c2d-2a3e-4e64-ad03-4668f586307d)

Usually during operation we change the value by whole 1% values, so it would be more intuitive to make this the default value, then the user can change to 0.1% to gain finer value adjustments

**Comment by Jedsters** [comment]
Agree.

**Comment by bsongis-frsky** [comment]
Yes, but it should be another issue! I am forced to reopen this one which has so many comments!
