### ISSUE TITLE
rename tracks of the trainer mode

### ISSUE THREAD

**Issue by julienhogert** [FrSkyRC/ETHOS-Feedback-Community#3909]
Hello everyone, 
Thanks again for all the work you've done to develop Ethos. It's a very powerful tool for us. We use X20s radios for animatronics. Thanks to the possibility of sending the bus through the bay module on the back of the radio control, in the latest versions of the program we now use microcontrollers to send motion capture data directly to the radio control via the training mode. It works great, and we're very happy with it. But if there's room for improvement, what we'd like is to be able to rename each track in the trainer mode to make it easier to find our way around. One workaround has been to change the destination for an unused Output track, but this doesn't change the name in the assignment lists, and if the track is deactivated (because it's not being sent), the output remains grayed out with no change. That's it, I don't know if it's of any interest to others and if it can be done easily. I'm just suggesting the idea. Thanks for your time, 
Julien

**Comment by bsongis-frsky** [comment]
Today trainer channels cannot have a custom name. They are just localized. But since the translations are stored in a different file, I think there is already a possibility for you to rename them.

**Comment by bsongis-frsky** [comment]
> One workaround has been to change the destination for an unused Output track, but this doesn't change the name in the assignment lists, and if the track is deactivated (because it's not being sent), the output remains grayed out with no change.

I don't understand this part of your request!
