### ISSUE TITLE
[LUA] stringValue() with timer

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#3910]
hi Bertrand, to remind you

local timer = system.getSource({category = CATEGORY_TIMER, member = 0})
lcd.drawText(x, y, timer:stringValue())

should report the timer within format HH:MM:SS as a stringValue.

Tks

---

- [x] new function `timer:stringValue()`
- [x] fix for `source:stringValue()` which doesn't display the timers right

**Comment by bsongis-frsky** [comment]
Ready for the next nightlies
