### ISSUE TITLE
News  layouts

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#3911]
Would it be possible to define new layouts like those in the attached image?

![Layouts Ethos](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/2843d6ed-ff42-40c1-910a-3069edc75002)

**Comment by BladeScraper-Designs** [comment]
I agree.  And also 2 and 3 row, 4 column layouts (both with and without trims)

**Comment by WhiskeyGolf** [comment]
It would also be nice if you could set up the layout on the right and left independently of each other.  Then all layouts would be possible.

**Comment by FireflyJar** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17463234/455b07a0-d0af-4766-bee0-2de25f7c79d1)

I never look at the trim while flying, but  like a mix of sizes for status and line charts

**Comment by bsongis-frsky** [comment]
2 new layouts added (1.5.10)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6339f5c5-a13b-4967-adbc-e64dae798846)

**Comment by bsongis-frsky** [comment]
New lua function available so that you can register your layout as you wish:

```lua
-- Lua Layout example

local function init()
  system.registerLayout({key="XL+3", widgets={
    {x=8, y=95, w=784, h=248},
    {x=8, y=351, w=256, h=56},
    {x=272, y=351, w=256, h=56},
    {x=536, y=351, w=256, h=56}
  }})
end

return {init=init}
```

**Comment by frobert0** [comment]
Is it correct that currently only 4 can be parameterized???

**Comment by afdofdez** [comment]
I have seen the definition of the registerLayout function and I have doubts about the definition of the trims and potentiometers. Could you give me the example of the function for creating the attached layout?


![Layout](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/56766487/db1dbbb3-54b1-4fd3-a4e5-c88aec898f23)

**Comment by frobert0** [comment]
Up to 9 fields works perfectly, from 10 fields model file is damaged, after restart or disconnect usb


local function init()system.registerLayout({key="XL+3", widgets={{x=8,y=95,w=256,h=100},{x=8,y=203,w=256,h=70},{x=8,y=281,w=256,h=130},{x=272,y=95,w=256,h=70},{x=272,y=173,w=256,h=70},{x=272,y=251,w=256,h=70},{x=536,y=95,w=256,h=70},{x=536,y=173,w=256,h=70},{x=536,y=251,w=256,h=70}}})end  return {init=init}

**Comment by jozefdo** [comment]
That is true. Only 9 fields works perfectly. I need 12 fieds, but this not work.
local function init()
  system.registerLayout({key="12w", widgets={
	{x=8, y=75, w=190, h=99},
	{x=206, y=75, w=190, h=99},
	{x=404, y=75, w=190, h=99},
	{x=602, y=75, w=190, h=99},
	
	{x=8, y=182, w=190, h=99},
	{x=206, y=182, w=190, h=99},
	{x=404, y=182, w=190, h=99},
	{x=602, y=182, w=190, h=99},
	
	{x=8, y=289, w=190, h=99},
	--{x=206, y=289, w=190, h=99},
	--{x=404, y=289, w=190, h=99},
	--{x=602, y=289, w=190, h=99},
  }})
end

return {init=init}

**Comment by bsongis-frsky** [comment]
12 widgets will be allowed in 1.5.11

**Comment by frobert0** [comment]
Thank you, you are the best.

15?????

![Screenshot 2024-07-10 151949](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12582649/51bb8cc2-92a7-4d30-8e02-4cbae9e38088)
