### ISSUE TITLE
Suite 1.5.5 - Mac 12.7.4 Restore Function Fails

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3918]
The restore function ends quickly in a "File operation error! The operation has been aborted."  announcement. 
Main log attached. I tried each component individually, with same results. I tried restoring from packages backed up with older suite versions and this one, same.

[main-20240425.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15109626/main-20240425.log)

Sorry Nicholas..

**Comment by spoke2570** [comment]
My email thread shows a comment, here from Alex00101 recommending to point Suite at FrSky Server. That has the same result.

**Comment by Nicholas-Luoyi** [comment]
This one is critical. So I will re-upload the installer
