### ISSUE TITLE
Ethos 1.5.6 with ELRS wrong telemetry value for GPS Speed

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#3919]
TW X14, Ethos 1.5.6, ExpressLRS module and the most actual ELRS lua script 

For the three logs below I drove the same route for comparison.

Using a GPS module on my X14 with ELRS module / ELRS receiver I get a GPS speed that seems to be by factor 10 to low. 

![X14 - ELRS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/aa49339c-367d-4ac7-8c3c-131e4c7d49cb)

Using the same GPS module with X14 Ethos and a TW R8 receiver I get the correct GPS speed values

![X14 Ethos](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/bad5fb08-9733-4a12-ae8d-efbd5bd60911)

Using the same GPS module whith the same ELRS receiver above with a TX16S ELRS I also get the correct GPS speed values

![TX16S - ELRS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/eb00d6e1-033f-439f-add2-7299880b5cec)

All other values are ok as far I could check, it's only GPS speed, that's wrong.

**Comment by bsongis-frsky** [comment]
Fix ready for the next nightlies

**Comment by glipski50** [comment]
Thanks. Will test then.
