### ISSUE TITLE
X20 : JOYSTICK or USB 

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#392]
Hello,
I have checked all menus, probably misted the right one, but when i connect the X20 on USB windows 10,
the radio is recognized as X20 joystick.

Where is the menu to select from Joystick to USB as with my X12S ? To avoid removing the SD card at each update

Thanks

**Comment by MIKE-DAILEY** [comment]
*ETHOS Systems USB Connection To PC Modes*

1. ETHOS System power off USB connection to PC is DFU mode for flashing bootloader.
2. ETHOS System started with enter key held down then power on USB connection to PC is bootloader mode for reading and writing files to SD card and on the X20HD/X20S/X20 the flash memory.
3. ETHOS System power on USB connection to PC is joystick mode.

**Comment by aviat40** [comment]
Thanks
