### ISSUE TITLE
Changing Free Mix Action resets Active condition

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3920]
Tested in 1.5.6

To recreate:

Create a basic model
Create a LS called LS1 (contents not important)
Create a Curve called CV1 (contents not important)
Add a Free Mix
Edit the default Action (Always on Weight 100%) of the free mix 
Change the Active condition to LS LS1
Change the Action to Curve

You will now notice that the Active condition has been reset to Always on

Somewhat annoying...

Thanks

**Comment by bsongis-frsky** [comment]
There is one Active condition for the whole mix, plus one Active condition per action

**Comment by bsongis-frsky** [comment]
I am not sure that I have understood the problem correctly!

**Comment by Jedsters** [comment]
Please see this video (excuse the TV noise in the background). Note how I change the Active Condition to an LS but as soon as I change the Action to Curve it changes the Active Condition from LS back to Always on so I then have to change that to LS again. 

https://www.dropbox.com/scl/fi/7peviv1w8brqevokgu2c0/VID_20240425_180641.mp4?rlkey=w0ngdf3a2tfkegazr7rbu08gb&dl=0
