### ISSUE TITLE
XACT Servo Telemetry Issues With TDSR12 (8 Servo Configuration)

### ISSUE THREAD

**Issue by ChrisKhosravi** [FrSkyRC/ETHOS-Feedback-Community#3922]
I'm currently stumped on an issue I'm experiencing:
I have a total of 8 Xact servos in a jet, they all have different Physical IDs & Application IDs, however I can't seem to get telemetry from all of them at once (I continuously get "sensor lost").
They move correctly! They are set up using FBUS protocol.

Some more details:
Servo Model: S5455H
Servo Firmware: 2.0.1

Receiver: TDSR12
Receiver Firmware: 1.0.11

Internal Module Firmware: 2.2.6
ETHOS 1.4.17

Telemetry works fine if keeping them plugged in as smaller groups (unplugging the other groups). For example, telemetry works great for RH Aileron & Flap when they're the only ones plugged in, LH Aileron & Flap work together, 2X Elevators & Rudder work together.
Having Nose Steering while the 2X Elevators & Rudder plugged in DO NOT WORK. And obviously when all 8 are actively plugged in I only get telemetry from Servo 8 (Physical ID: 15, Application ID: 6809). All others push telemetry through for a split second at a time, but are primarily showing red on the telemetry screen.

Ports are assigned as FBUS for the 8 servos listed below:

Servo 1:
Physical ID: 0C
Application ID: 6801

Servo 2:
Physical ID: 0D
Application ID: 6802

Servo 3:
Physical ID: 0E
Application ID: 6804

Servo 4:
Physical ID: 0F
Application ID: 6805

Servo 5:
Physical ID: 11
Application ID: 6806

Servo 6:
Physical ID: 13
Application ID: 6807

Servo 7:
Physical ID: 14
Application ID: 6808

Servo 8:
Physical ID: 15
Application ID: 6809

**Comment by Wolepo** [comment]
Another problem is that you cannot configure a single servo in the group. This is only possible without the others.

**Comment by ChrisKhosravi** [comment]
@Wolepo I don't believe I have that problem, you can access the parameters through the telemetry screen (long press on any of the telemetry streams and it should get you into the XACT servo configurator).

**Comment by Wolepo** [comment]
Thanks, I'll have to try it.

**Comment by Wolepo** [comment]
Of course it's not true. No XAct servos can be configured in the telemetry menu. This is only possible in the sensor configuration in [XAct]. If several are connected, only the first one is called up. A selection is not possible.

**Comment by BladeScraper-Designs** [comment]
I regularly pick and edit a single servo settings with all servos connected by using the Telemetry screen.   Double Tap on any sensor from Srv1 and choose Device Config - opens Device Config for Servo 1.  Any sensor from Srv2 - opens Device Config for Servo 2.

**Comment by Wolepo** [comment]
I have to apologise, it's the first time I've seen the Sensor Config. menu today and you can also make settings. Thank you
![Sensor konfig](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/a7e061be-2acb-40e7-8f59-8648df311c92)

**Comment by spoke2570** [comment]
But be careful! You might wind up reconfiguring them all at once! Make sure the IDs are well nailed down, first.

**Comment by Wolepo** [comment]
You should set the ID for each servo individually before installing it in the model. Then it will work without any problems.

**Comment by spoke2570** [comment]
I changed the ID on one servo in the telemetry tab and it was back to setting the names individually. Fortunately I was just playing with a bench set.

**Comment by ChrisKhosravi** [comment]
Here is a log that I recorded during one of my flights on this setup.
As you can see, for the majority of the time, I do not get telemetry from all of the servos (especially servos 2-8). The only one that I get somewhat regular telemetry is Servo 1 (Nose Steering).
[Flight 5 - Dragon-2024-04-28-15-12-31.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15169196/Flight.5.-.Dragon-2024-04-28-15-12-31.csv)

**Comment by ChrisKhosravi** [comment]
I still do not have resolution to my problem  :(
