### ISSUE TITLE
Suite 1.5.5 - New Mac DMG is Corrupt  (ZIP is OK)

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3923]
The dreaded Error -36....

The Finder can’t complete the operation because some data in “Ethos Suite.app” can’t be read or written.
(Error code -36)

Both of the last 2 images work fine, but this one is not so good. Standard drag and drop using the shortcut in the mounted image, and manual drag and drop.

**Comment by Nicholas-Luoyi** [comment]
Sorry. I cannot understand this one

**Comment by mgsanna** [comment]
Same here on MacBook Pro intel, the .dmg is corrupted, 
<img width="705" alt="Screenshot 2024-04-26 alle 09 28 13" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/e0bfd5c8-65ab-48b1-88f7-6ae1807e8d34">
same error of @spoke2570 

But the zipped ethos suite works... installed manually....

<img width="819" alt="Screenshot 2024-04-26 alle 09 33 23" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/75bec365-63a0-4410-9560-b77a530e75ba">

**Comment by kramgrand** [comment]
Hello
Just for info, I usually install the latest using the .dmg download option rather than update. 
I loaded from the .dmg early yesterday morning without any issues.  MacBook Air M2
Regards Mark.

**Comment by LeoCheung123** [comment]
Same problem here.  Error -36.
MacBook Pro 2023 running Sonoma 14.4.1

It also removes the existing version of Ethos Suite (v.1.5.0 which was functioning fine).  Which is a little inconvenient.

**Comment by kramgrand** [comment]
Just for the shear hell of it, I downloaded it again to reinstall over the top of the existing.   It's broken...
<img width="1470" alt="Screenshot 2024-04-26 at 14 53 00" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96422592/4a4d3eac-c851-4208-8cf4-f8ed7afd65a2">

**Comment by kramgrand** [comment]
Thought you might be interested.  I restored my original download of the .dmg via Apple TimeMachine and it worked without error.     Could the copy on the server somehow become corrupted?

<img width="1470" alt="Screenshot 2024-04-26 at 15 04 25" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96422592/1d22a65d-bee8-495e-8499-f7d22ea917a2">

**Comment by spoke2570** [comment]
The zipped version works perfect. Restore is working. It takes a while for Suite to recognize the drives after the OS has them, but its working well.

**Comment by dap35** [comment]
I ran into the same issue with downloading the dmg file and attempting to install.  The zip file is fine.

**Comment by ghost** [comment]
same here, m2 air

**Comment by Vermaarp** [comment]
same issue in my mac m1

**Comment by Nicholas-Luoyi** [comment]
It may be a package issue. Would you please try the latest one?

**Comment by spoke2570** [comment]
The new package works.
Manual authorization of the app was not necessary.
Backup and Restore functions work correctly.
Model images seem to resize for the different window sizes better.
So far about 10 openings and closings with no weird "quit unexpectedly" warnings after the app has been closed using best practices. 
-> The install was a little notchy requiring to manually quit Suite, transfer the package to the Apps folder, open the app. (see image)

![Screen Shot 2024-04-30 at 6 44 51 AM](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/e698a1bc-4ae5-4380-bb9c-21f9043aa571)

-> It took a seriously long time for the package to move the package from the mounted disk image to the app folder. (several minutes)

Conclude: 1.5.6 seems to work correctly, but the best Suite Update experience still was going from 1.5.0 to 1.5.1. The update was announced by the app at open and the update was seamless with no manual operations required except to initiate the update from the alert window within the Suite app. 

I would love to see suites basic operation be a marriage of the solid operation that I have seen with Suite 1.5.6, the update speed of most previous versions, and the seamless update operation from the 1.5.0 to 1.5.1 update. 

I consider this issue closed, but I will let Nicholas close this thread.

**Comment by Nicholas-Luoyi** [comment]
Thanks for keeping testing and contacting! It seems that everyone has his/her preference. Because for me, I do like the update notification won't disturb me. So I think the best choice is to leave the choice to the user. I will add selection like "auto install / manual install"

**Comment by spoke2570** [comment]
The pictured result is sort of the worst of both worlds. I pressed the "install update" button and the downloaded image mounted, opened. Suite is still open behind this. So choosing the most obvious path of dropping the app on the provided shortcut results in failure because the Suite is still open. Ya I would close Suite first, but that is not what the screen is implying. 

It was nice not to manually approve the app.

I feel like the 3 options should be to download the package or install the package or cancel the operation. That way there is clear expectation of what happens when a user hits the button.
