### ISSUE TITLE
Use bigger fonts in telemetry screen

### ISSUE THREAD

**Issue by patman13** [FrSkyRC/ETHOS-Feedback-Community#3924]
If trying to read telemetry values with a very short view on the display the numbers are hard to read.

It would be good to use the available area and use bigger fonts to display the values (especially for a single value per page).

**Comment by philippe-warnotte** [comment]
Yes, the fonts size should be adjusted proportionally to the size of the widget.
Thank you.

**Comment by MikeActron** [comment]
Yes, the font should really be larger or adjustable in size. The X20 series in particular has such a high-resolution LCD and then such small fonts are used. Other manufacturers can do the same.

**Comment by philippe-warnotte** [comment]
[bsongis-frsky](https://github.com/bsongis-frsky) commented [last week](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4609#issuecomment-2404215903)
The font adapts to the widget size, but we would miss an extra font
