### ISSUE TITLE
1.5.7 pre release FW:  there is a definitive performance degration in 1.5.7

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3925]
Hi,

playing around with 1.5.7 for some days.
i've mostly 2..3 widgets running on a template
(one "fat" one needs app 15 seconds on startups compiling app 20 files)

i recognized slower UI and much worse handler cycle times
The widget above now needs app. 30 seconds to boot

downgraded to 1.5.6 for crosschecking, and effect is reproducable, much more speed after downgrade.
so i can rule out NAND problems.

even on the same model:
under 1.5.7, even with the "performance boost trick" using devtools, the UI performance is much slower then standard 1.5.6 performance without performance Boost.

i can recognize the issue by startup times, audio "hickups", UI performance, lua performance

had 2 EM'S during changing model, thinking it was the "target" had to be converted to 1.5.7 and something happened during this process. 

regards
Udo

**Comment by bsongis-frsky** [comment]
When you say "15 seconds", do you mean that Ethos needs 15 seconds to load your model? Or something else?

Because the maximum is 2 seconds, then the watchdog will stop the process and you will get an EM

2 seconds are already very long

**Comment by bsongis-frsky** [comment]
The conversion should be very quick, you shouldn't be able to notice it

**Comment by bsongis-frsky** [comment]
Which Lua do you have? Here is the process when reading a model which uses Lua scripts:
- for tasks, the `init` method is called
- for sources, the `init` and `read` methods are called
- for widgets, the `read` and `create` methods are called

If you have a lot of those scripts, and if you do heavy actions there, perhaps 2 seconds are too short

**Comment by strgaltdel** [comment]
no, model template is loaded "normal", 
but then the first widget is initiated, this widget loads a lot of lua files / libs depending on its configuration, i would say read handler is executed and finished correct.
i do assume these files which are loaded or triggered by create handler and in very first wakeup handler loop, has to be compiled (cpu load) every time on boot / starting the template, so the display starts app. 15 seconds after template was loaded.
i can see this, because a timer starts automatically on start so the "boot / compiling time" can be read immediatly after display is active

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/8d7318d1-e879-4d5d-aee1-b0eb1ad2f2b8)

1.5.6 needs 16 seconds until display becomes active on start screen,
1.5.7 app 28 seconds

even without this widget, .. which is a "worst case performance measurement tool"  (-;
performance is slow.

**Comment by bsongis-frsky** [comment]
The compilation will happen on radio startup, not when loading the model

**Comment by strgaltdel** [comment]
hmm,
even when "dofile" is called in create handler, or in wakeup ?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/83e9e461-9e4b-42a1-890d-00ebfe74ef5f)

my understanding:
as a widget, at least create - "dofiles" "loadfiles" would be compiled on radio startup
then, because the widget is configured in models homescreen, wakeuphandler is called and then the rest which is loaded in wakeup will be compiled

when this is finished, paint can be called , and this complete cascade needs app 15 seconds under 1.5.6, 28 seconds in 1.5.7


i've the impression that the performance issue has something to do with lua usage,
because when i deactivate all widgets, the 1.5.7 ui is fast as in 1.5.6

and yes, the widgets are supressing activities when not in foreground
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/252630c9-f510-4c73-9dd2-92638edc01ee)

**Comment by bsongis-frsky** [comment]
I wonder what you call "compilation", perhaps you only mean "load"? Because compilation is the process which creates the .luac files

**Comment by bsongis-frsky** [comment]
Would you please contact me on Discord, I will share a 1.5.7 with a small difference in the mixer. 
In case you heavily use the VARS, then I see a difference.

**Comment by strgaltdel** [comment]
i just send you a discord message

template
35...40 vars
70 LSWs
50 SFs

app 40 mixers,

the price for a "make it most flexible as possible" idea

maybe i'm trying too hard

and yes, thought every lua would be internaly compiled for performance reasons and stay in mem, 
only "main.luaC" as precompiled ones are saved when detected 

i saw there is a way to compile even more then main.lua, didn't find time for "how to.."

**Comment by bsongis-frsky** [comment]
Ah yes ... 40 VARS :)
Then perhaps I have the reason.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/7f26028b-8873-43f7-8bfa-2a9296282c59)

**Comment by bsongis-frsky** [comment]
It seems that 1.5.8 is 4 times faster than 1.5.7, and 2 times faster than 1.5.6

**Comment by Crunch69** [comment]
Where can I find information about the dev tool booster?
