### ISSUE TITLE
Wrong import of models when using renamed switches.

### ISSUE THREAD

**Issue by patman13** [FrSkyRC/ETHOS-Feedback-Community#3926]
1.5.6

I have renamed my hardware switches on one transmitter (X TWIN Light) to align the layout with my other transmitter (X18).
When I import a model a model from the transmitter with original names the model on the transmitter with changed names, Ethos does not keep the name, but does a change of the switch.
End effect: I have to change the switch in all uses to the desired name.

In my understanding this is a bug.

**Comment by mawzthefinn** [comment]
I don't understand the issue as described.

Do you mean that the custom name is not retained, or that the switch mapping is not adjusted to match your renamed switches.

Switches in the model file are by switch index. So if you import a file on the TWIN X-Lite that has SB (Switch 2) assigned on the X18, it will end up on Switch 2 on the TWIN X-Lite, even if you renamed Switch 2 to SC to match the X18 switch layout. 

You are always going to have to re-assign switches when importing from an X18 to a TWIN X-Lite if you want to maintain switch layout, the switch names are just labels, it's the switch indexes that matter and that is not configurable

**Comment by patman13** [comment]
Okay, so it seems it is not a bug - it's a feature. ;-)
