### ISSUE TITLE
RB-25S Update FW-RB25_RB25S_v20240314

### ISSUE THREAD

**Issue by 3wintro** [FrSkyRC/ETHOS-Feedback-Community#3929]
After the update was withdrawn by Frsky today, the RB-25S is no longer usable. RB-25S can no longer be reset to the old software version. Telemetry is no longer possible. No more access to the RB-25S.  Constant abort with error messages via Tandem XES. It worked with STK-Tool. Can it still be saved or is it scrap? It seems to me that the new update is not deleted. 
Will there be an update soon, otherwise I will send the RB-25S back as I still have warranty on it.

Translated with DeepL.com (free version)

**Comment by filduch** [comment]
Hello, did you try to load the old firmware directly with your transmitter (connecting it through the SPort interface) ?

**Comment by 3wintro** [comment]
Data cannot be invalidated via sender, the old file can only be transferred via STK-Tool. The problem is that there is no telemetry connection to the RB. If you get the new one where it was withdrawn you get telemetry but it is useless because you can't set anything. Most of the fields have ???. You can't set anything. You get a selection but nothing is saved. With CH most are CH1 or ???. About transmitter does not work at all more than 14% does not work, constantly invalid data. The RB is therefore unusable. It seems to me that not everything is overwritten when you use the STK tool. Is there a Uni software to delete the file so that the old software can be reinstalled.

**Comment by filduch** [comment]
I've no RB-25S but I read that that it has a SPort (RX1 in auto recognization). It's should be possible to try to use the SPort for upgrading the RB

**Comment by 3wintro** [comment]
The problem is not the SPort but if you go to the old software there is no possibility to receive telemetry. You have no access to telemetry. I think Frsky did not withdraw the update for nothing else. RB-25S can also transfer the old software via transmitter with SPort. I created a new model and it also went through. No more telemetry from the RB. If you take the withdrawn software telemetry is there but unusable.

Translated with DeepL.com (free version)

**Comment by filduch** [comment]
OK, if i were you, i would ask FrSky directly

**Comment by Kreisflieger** [comment]
@ filduch,

do you have a mail address to contact FrSky ?

Would like to push this issue as my RB25S is also dead after flashing the now withdrawn firmware.

**Comment by 3wintro** [comment]
Can be closed. As the update cannot be reset. The Rb is unusable and has been replaced with a new one.

**Comment by Kreisflieger** [comment]
Correct, my RB25S was also replaced by my German dealer Engel Modellbau.
