### ISSUE TITLE
Xact lua enhancement 

### ISSUE THREAD

**Issue by lpott6** [FrSkyRC/ETHOS-Feedback-Community#3930]
I mentioned this in another post, but thought it would be better as a new request.
Expand the Xact lua script to allow configuration of any servo connected via F-bus. This would be helpful once the servos are installed into a model. Right now it seems that only the servo on Pin 1 can be configured using the XACT script. It is difficult physically unplug each servo and move it to Pin 1 in the model for configuration. It would be great to be able to "select any F-bus Pin" and then configure the servo attached to that Pin.

**Comment by lpott6** [comment]
I just read another post about selecting the servo configuration from the Telemetry sensor screen. It works well.

**Comment by Wolepo** [comment]
Take a look here: [https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3922](url)
