### ISSUE TITLE
.md text mark up >  only displays | once  (minor)

### ISSUE THREAD

**Issue by FireflyJar** [FrSkyRC/ETHOS-Feedback-Community#3932]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17463234/6899304f-e246-45b0-bb76-71b931fc1c2a)

shows the following

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17463234/e2dcb96b-3478-49ee-a136-cf2969922fcf)

only shows |  on the first > but not the rest.

**Comment by FireflyJar** [comment]
I just found User Defined Text Checklist (enhanced) in  Ethos manual, and see the > was not listed, I just learned it from somewhere else.    It is nice to have indent, sort of works, but this is not important.
Sorry.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/e7d69900-1393-4cb0-bfeb-8d1eaca4af37)
