### ISSUE TITLE
X20 Pro Missing Remote Version on Ethos Suite 1.5.5

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#3933]
Just updated to ethos suite 1.5.5 and went to update my radio and am seeing "Missing Remote Version" in place of the available software versions.

<img width="1202" alt="image" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1608096/7c30d704-7031-404b-b1c1-9519a9f5484e">

**Comment by strgaltdel** [comment]
sure that the remote repository points to github ?

(suite setup >> server location)

**Comment by fdm225** [comment]
<img width="1205" alt="image" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/1608096/919a0b5b-323b-4d10-ab14-ba9df5ada1c5">

**Comment by strgaltdel** [comment]
strange, maybe a problem with the Mac version
on win10, everything was detected, correct versions without connection problems to git server / remote site

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/9a849404-3b9c-4562-b294-2e362fc25b5b)


today a mac user descibed problems by trying to update his XE to 1.5.6 (suite 1.5.5 too) on the german frsky forum
unfortunately a very vague error description.

but maybe the mac-suite 1.5.5 has an issue

**Comment by strgaltdel** [comment]
.. the mac user from the german forum postet this screenshot
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/158aa351-21b6-40b2-bfe5-9c44da48dab8)


he wrote that a java update didn"t change anything for him
.. seems to be two independent issues  for me

**Comment by Nicholas-Luoyi** [comment]
> Just updated to ethos suite 1.5.5 and went to update my radio and am seeing "Missing Remote Version" in place of the available software versions.
> 
> <img alt="image" width="1202" src="https://private-user-images.githubusercontent.com/1608096/326214919-7c30d704-7031-404b-b1c1-9519a9f5484e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzI1NjUsIm5iZiI6MTcxNDM3MjI2NSwicGF0aCI6Ii8xNjA4MDk2LzMyNjIxNDkxOS03YzMwZDcwNC03MDMxLTQwNGItYjFjMS05NTE5YTlmNTQ4NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDYzMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmRmYWJmZTViMDkwYjdiZjdjZmI4M2Y5NmE3Y2RiYzkwYmVjMTQ0NTIwNDczYTgzZDkwOWMzNmZjZmYxZWEwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZEnd45jqoXEU6oOq5a4zoiAmPSkgVuVG2aMKc4_8mPM">

This could be caused by the network. You may check your network or switch between the tabs on left to refresh the page

**Comment by fdm225** [comment]
Just updated to Ethos Suite 1.5.6 and now have remotes.
