### ISSUE TITLE
bug in inter logic x12s os 1.0.7

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#394]
hello mr Songis,
Thank you for your interest. In inter logic, it is not possible to program an alarm on total cells. Indeed, the setting value goes from 0 to 4.20v while it should go at least up to 12v in 3s ..... 24v in 6s .....
Thank you to you and see you soon

**Comment by Devil-IdT** [comment]
Hello, in my X10S I simply set the end range for cells total to 20 volts. Then I was able to monitor the total voltage in the logic switches.
Flying with 4S.

**Comment by WismyYao** [comment]
> Hello, in my X10S I simply set the end range for cells total to 20 volts. Then I was able to monitor the total voltage in the logic switches.
> Flying with 4S.
> ![tele](https://user-images.githubusercontent.com/64803366/120703167-4030d980-c4b5-11eb-8a7a-175bc8d6b1dd.jpg)
> ![logic](https://user-images.githubusercontent.com/64803366/120703180-43c46080-c4b5-11eb-8b5e-9a302d59a9ba.jpg)

Thank you for your enthusiastic answer ：）

**Comment by WismyYao** [comment]
> Hello, in my X10S I simply set the end range for cells total to 20 volts. Then I was able to monitor the total voltage in the logic switches.
> Flying with 4S.

Thank you for your enthusiastic answer ：）
