### ISSUE TITLE
X18 asking for gyro calibration after update to latest 1.5.6

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#3941]
Hi, 
Weird behavior since x18 does not have internal gyro, right?

![72307551-bb51-4739-8715-27f8c020ab2f](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84532808/20fdaac4-a275-4076-b0c2-852eae7c9a3c)

**Comment by mawzthefinn** [comment]
1st run X18's do have a gyro.

**Comment by bsongis-frsky** [comment]
Since 1.5.14 the gyro is detected, and if no gyro there will be no calibration.
