### ISSUE TITLE
suite 1.5.5 not able to write firmware file to transmitter

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#3942]
after ethos 1.5.7 got official status "stable", we had 5 messages from users in our german forum that they were not able to update the firmware (only firmware file is the issue, i18n update for example had no problem)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/91b85589-68bc-41fe-bfd5-42edb3e1c182)

could replicate the issue (x18s)
download seems finished OK, then message above is shown
(even without AV scanner activated, suite in admin mode)

flash from local file runs without problems

**Comment by mgsanna** [comment]
Same Error here X20S - X20PRO -X20HD - ETHOS SUITE 1.5.5

I think there something about server.... error
or something like this


with Ethos suite 1.5.4 everything works
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/32ea9fcd-c49c-47a5-b027-34333dc4f5b4)

**Comment by strgaltdel** [comment]
.. as mentioned, in case one want to update firmware, workarounds:

- you can download your firmware file from git & perform "flash via  local file"
- or downgrade to suite 1.54 & update firmware
- or manually copy firmware.bin into root of nand & reboot
- or wait until it's fixed (-;
