### ISSUE TITLE
Flightmodes do not seem to work on Vers. 1.5.7

### ISSUE THREAD

**Issue by martinwh99** [FrSkyRC/ETHOS-Feedback-Community#3943]
I have different flightmodes. Some are switches and some are logical switch. As long as i switch from FS1 to FS3, which are selected with SA it works. But when i switch to an other FM which is controlled by an other switch or locical switch the FM stays on FS1,2,or 3, the last selected. Here is my example:

FM0 BasisFlightmode 
FM1 Criuse SA- 
FM2 Thermal SA(upp)
FM3 Speed SA(down)
FM4 Breake Logical  Throttle<80% AND SB(down)

it worked perfect with version 1.5.6

FrSky X20S 
Ethos 1.5.7, EU #33968bb6

**Comment by mawzthefinn** [comment]
Flight modes will always go to the highest(lowest number, top of the stack) true FM that isn't FM0.

Since FM1, FM2 or FM3 is always true (all 3 position of SA), no flight mode below FM3 will ever be valid since one of those 3 will always be true

If it was working as described on 1.5.6, there was a bug that was fixed. But this should never have worked on any previous version of ETHOS (I have tested a similar setup as old as v1.0.10 and it works as I describe)

**Comment by bsongis-frsky** [comment]
M0 BasisFlightmode
FM1 `SA-` Criuse 
FM2 `SA↑` Thermal
FM3 `SA↓` Speed SA
FM4 Breake Logical Throttle<80% AND SB(down)

---

FM4 should never be active, as explained by @mawzthefinn

**Comment by martinwh99** [comment]
Sorry, but just for my understanding. If you right, and i have FM1-3 on a 3 position Switch the other FM will never become active and there condition is never shown on the model main window.

I`m coming from OpenTX which is still running on my x12s and EdgeTX on my Radiomaster and 2 weeks ago i bought the x20s ETHOS. And all of them (x20s vers. 1.5.6)  worked as i explained and the text of the active one is shown on model main page.
Models i have created in ver. 1.5.6 are working 'correctly' in 1.5.7. Models i created in 1.5.7 i neve get a chance to activate other flightmodes then FM1-3 not even FM0 because SA is always in one position and thus active.

I'm on OpenTX since over 7 years. So my question is how do i activate the other 16 flight modes? Have FM handling completely changed in ETHOS compared to OpenTX?

**Comment by Dsrenger** [comment]
In Ethos you have a very strict priority for the flight mode.

Top to bottom.

FM0 is the top priority. If no active condition is met at all, Ethos will fall into FM0. Thats why you cannot choose a active condition for FM0.

Then top to bottom. 
If one active condition is met. Its easy...the FM will be active

If 2 active conditions are met, the higher one in the list will be active. Somehow the system needs to know which of the 2 FMs to choose if 2 active conditions are true.

When your LS is active, 2 active conditions for the flight modes are active SA and the LS. So it chooses the higher one in the list. Thats why FM4 can never be activated as SA always activates one of FM1-3.

In this case I would exchange FM1 and FM4. So if the LS is active it chooses the FM1 and if not SA will define which FM is active.

Additionally I would be interessted in the 1.5.6 model file, where it worked. Can you attach it here? Im  am just curious, as I just tested it in the 1.5.6 simulator.

**Comment by martinwh99** [comment]
As I have already mentioned, the error was between my ears. In Ethos I simply hacked in my models from opentx. And everything was still in order. Then I created a new model in ethos 1.5.7 and started with the FM0-2 Cruise speed thermal. Without thinking I created the landing FM's 3-5 and and that was the mess. But now that i can move them around in ETHOS everything is fine. So, to come to an conclusion, there was never an error in ETHOS. I apologize again for my incompetence.

**Comment by mawzthefinn** [comment]
HI Martin, 

Chalk this one up as a learning experience, not incompetence. ETHOS is different from OpenTX, sometimes only in very subtle ways, and until you are really familiar with the differences, you will trip over things like this.
