### ISSUE TITLE
TrueType fonts with scalable size 

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#3945]
Hello Bertrand,
I would like to point out the CR 1666 (You will be able to use this font (or your own fonts) in next release:)  again,
Will it be possible to add larger fonts or even TrueType fonts with scalable size.
e.g. lcd.font(13.0) or lcd.font(ARIAL,13.0) like MS-Word fontname= "Arial" fontsize = 13.0

Thank you very much

Many greetings, Benno

**Comment by strgaltdel** [comment]
as some additional info

there were customers which complained about too small font sizes in telemetry screens
Benno offered a widget where a user could change size, color, background & font.

It was appreciated, but now the user wondered that
- even the biggest font size didn't fulfill their needs
- some combinations like XXL bold were missing

the idea rose to have a possibility to implement "own" fonts 
i remembered there were some hints it was in the pipe 

#1666
"You will be able to use this font (or your own fonts) in next release:"

#2176, 
"You may load any font in the firmware. But you are missing a tool to build a font, it should be part of Ethos Suite soon!" 

#2467
"We will have some work on the font converter inside Ethos Suite"


so i would say:
lcd.loadFont(file) can only applied to predefined Ethos fonts
there will be a tool to create / convert fonts, but no eta now

right ?
