### ISSUE TITLE
Suite: No way back when clicking changelog links

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3946]
Clicking on Issue number in Ethos Suite shows the correct GitHub page but there's no way to return to the main Ethos Suite screen. We're missing the return button. Only way back is to close Ethos Suite. Or am I missing something?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/5b83f6f9-02cf-48d0-ad0e-6539b481a248)

**Comment by frskyrc-ben** [comment]
tested / reproduced (ETHOS Suite 1.5.5)

When I press the "Back" navigation button on my mouse, it does go back, but it presents a blank "welcome" screen:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/108486338/1f439043-144d-4078-9d70-61df4559987f)

Pressing the "Back" navigation button on my mouse a 2nd time, it presents a blank "guidance" screen:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/108486338/cf523263-28aa-4a3e-97c3-512288095ca6)

**Comment by spoke2570** [comment]
Same on Mac 1.5.5
Must close active Suite window and open new Suite window to get back.
