### ISSUE TITLE
Ethos Suite error when checking Brazilian Portuguese 

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#3948]
Hi
This error is appearing when updating to 1.5.7 with latest Ethos Suite. 

![a5358484-13ab-4935-b9ba-0cd604581f0f](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84532808/e0b6a559-f9e0-47bf-a1c6-5c0ebad529ff)

![1a6813e2-791e-4806-a69a-be2313e87129](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84532808/8e010e5b-9df2-4b1f-8257-c9d35fc85454)

**Comment by Nicholas-Luoyi** [comment]
Should be fixed now. Please update to the latest Suite 1.5.6
