### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#395]
Hey,

@bsongis-frsky find attached translation to Portuguese (PT-pt). 
There are some expressions that might need to adjusted to the context. Is there any chance to test this before final release? That would be great. 

Cheers, 
[pt.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6594057/pt.txt)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/120765521-96cfff00-c519-11eb-8c9f-33847daae18e.png)

**Comment by bsongis-frsky** [comment]
Which radio do you have?

**Comment by jreis1** [comment]
> Which radio do you have?

X20

**Comment by bsongis-frsky** [comment]
I will release a simulator later today

**Comment by jreis1** [comment]
> I will release a simulator later today

looking forward to that
