### ISSUE TITLE
Ethos suite 1.5.6 update downloads but does not update

### ISSUE THREAD

**Issue by craigywsm** [FrSkyRC/ETHOS-Feedback-Community#3950]
when downloading update 1.5.6  it gets to 100% downloaded but does not initiate the installer  
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40343747/d028463f-d359-4f65-aa09-4d22fe9ba923)

**Comment by Nicholas-Luoyi** [comment]
Now it should be started manually.

**Comment by craigywsm** [comment]
> Now it should be started manually.

Why does it mention it will auto update from 1.5.5?
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40343747/038453bd-a93d-41f3-b446-d956e1ebf598)

**Comment by Nicholas-Luoyi** [comment]
I think it's a bad description from me. But I will add a selection to enable/disable auto run the installer.

**Comment by craigywsm** [comment]
@Nicholas-Luoyi I feel a better option would be once downloaded it asks the question to install Yes/No

**Comment by Nicholas-Luoyi** [comment]
> when downloading update 1.5.6 it gets to 100% downloaded but does not initiate the installer ![image](https://private-user-images.githubusercontent.com/40343747/326720496-d028463f-d359-4f65-aa09-4d22fe9ba923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjcxNjUsIm5iZiI6MTcxNDQ2Njg2NSwicGF0aCI6Ii80MDM0Mzc0Ny8zMjY3MjA0OTYtZDAyODQ2M2YtZDM1OS00ZjY1LWFhMDktNGQyMmZlOWJhOTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA4NDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MzU3NThjNmZiMGRlMzI2MGJmYjk3MDA2NzFlN2JkNTgwY2FjOTE5MGU5Yzk3ODhlODNjNTRmMjE2Y2E0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9zE3WYGHX3cKzqTLbRC3x9wd5b4xuE44DGqKibz93kU)

From your image I'm afraid it may be another bug. The layout should be changed and inform you to run the installer. You can find the downloaded installer in "Ethos Suite/Updater/"

**Comment by craigywsm** [comment]
@Nicholas-Luoyi 
It looks like there is no Updater directory.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40343747/9bfaedbd-6e4e-49d7-9556-4a91c3c0f762)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40343747/d26504df-f637-4ceb-bc6f-5cdd09ab85bf)



It looks like it is still in %temp% directory
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40343747/a3a5b0b3-a2d6-465f-812a-6894c1133df1)

**Comment by Nicholas-Luoyi** [comment]
It makes sense. The installer isn't saved successfully. Maybe have a try with admin mode?

**Comment by craigywsm** [comment]
@Nicholas-Luoyi Yes run as Administrator mode it works :)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/40343747/ca3a1126-62d9-45ed-90a6-43c2878b7c9b)

**Comment by spoke2570** [comment]
The Mac version gets to the install update button with no problem.

**Comment by craigywsm** [comment]
> The Mac version gets to the install update button with no problem.

Thanks @spoke2570 it looks like this is related to Windows permissions

**Comment by craigywsm** [comment]
This is fixed upgrading from 1.5.6 to 1.5.7

**Comment by craigywsm** [comment]
Sorry it still downloads and gets to 100% and does still does not prompt to update

**Comment by craigywsm** [comment]
@Nicholas-Luoyi can this one please be looked at for 1.5.8

**Comment by craigywsm** [comment]
This now works when updating from 1.5.7 to 1.5.8 awesome work @Nicholas-Luoyi
