### ISSUE TITLE
New ETHOS V 1.5.5 download on Mac

### ISSUE THREAD

**Issue by Bobbysonic** [FrSkyRC/ETHOS-Feedback-Community#3953]
I can`t seem to download the latest ETHOS suite  V1.5.5 to Mac.  I keep getting an error code-36 saying it can`t be read or written! Is this a "bug?

**Comment by kramgrand** [comment]
Hello, I believe there is an issue with the OS X   .dmg download of 1.5.5
My understanding is the 1.5.5 zip file downloads and works as it should.

**Comment by spoke2570** [comment]
Also Suite 1.5.6 is working. I tested update backup and restore on my mac.

**Comment by Bobbysonic** [comment]
Excellent, I`ll give it a try!

**Comment by mawzthefinn** [comment]
Closing off as Suite 1.5.6 fixes this known issue
