### ISSUE TITLE
Unable to update!!!!

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#3954]
I am trying to update to 1.5.7 from 1.5.6.

I installed latest release of ETHOS Suite, 1.5.6, but it is refusing to update.

ETHOS Suite hangs at `Writing firmware' and no writing firmware to the Tx is being done.

I tried old versions of ETHOS Suite to no avail.

Very, very, very frustrating indeed. I already wasted 3 hours on this. Am I stuck with v1.5.6 in Tx??

**Comment by fdapport** [comment]
Please try  to use Ethos suite 1.5.4, I have the same issue with 1.5.6, see my tichet #3944

**Comment by salibaj2** [comment]
fdapport,

Updating the transmitter with Ethos Suite 1.5.4 did the trick.

Now the question.

What are the implications on the TX ETHOS software if I do not update TX with latest ETHOS Suite?

As I can understand it, none, but would like to know that I am doing the updates correctly.

For the developers, v1.5.5 to v1.5.6 of ETHOS Suite are useless for me.

Either they report a missing drive, as I already opened in another ticket, or this one, it hangs on writing.

**Comment by franck76** [comment]
Same problem with my X12S (with bootloader up to date 1.5.3)

 I upgraded ethos suite, then I tried to update from Ethos 1.5.5 to 1.5.7.

Whichever the version of Ethos suite (1.5.5 or 1.5.6), when firmware is being copied to the radio, either the radio freezes or I get an error message "Erreur, l'action a été interrompue". 

On my last attempt, the radio froze but the firmware was actually copied on the SD card.
 I started in bootloader mode, then shut off the radio, then restarted normally and the update started automatically...

**Comment by Nicholas-Luoyi** [comment]
> fdapport,
> 
> Updating the transmitter with Ethos Suite 1.5.4 did the trick.
> 
> Now the question.
> 
> What are the implications on the TX ETHOS software if I do not update TX with latest ETHOS Suite?
> 
> As I can understand it, none, but would like to know that I am doing the updates correctly.
> 
> For the developers, v1.5.5 to v1.5.6 of ETHOS Suite are useless for me.
> 
> Either they report a missing drive, as I already opened in another ticket, or this one, it hangs on writing.

What is your radio?

**Comment by strgaltdel** [comment]
We just have an issue in A.Engels Forum, same error message,  which points to "radio/nand" storage which is running out of space
(less then 2MB free), 
after deleting old logs everything worked like a charme (-;

just an idea...

**Comment by strgaltdel** [comment]
this weekend i wanted to update 1.5.6 to 1.5.8n.
using mentioned suite 1.5.6, 
worked as intended

x18s / win10

**Comment by salibaj2** [comment]
> > fdapport,
> > Updating the transmitter with Ethos Suite 1.5.4 did the trick.
> > Now the question.
> > What are the implications on the TX ETHOS software if I do not update TX with latest ETHOS Suite?
> > As I can understand it, none, but would like to know that I am doing the updates correctly.
> > For the developers, v1.5.5 to v1.5.6 of ETHOS Suite are useless for me.
> > Either they report a missing drive, as I already opened in another ticket, or this one, it hangs on writing.
> 
> What is your radio?

X18SE
