### ISSUE TITLE
Error when adding Brazilian Portuguese in Ethos suite 

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#3956]
Error when selectin I18n Brazilian Portuguese when updating to 1.5.7 with latest ETHOS suite version. 

Error: 

![a5358484-13ab-4935-b9ba-0cd604581f0f](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84532808/3d4768ca-7533-4c64-8863-7433eb401256)
![1a6813e2-791e-4806-a69a-be2313e87129](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84532808/5d7f8534-c62b-4809-b58b-6ae220a63148)

**Comment by strgaltdel** [comment]
ît's a duplicate of several issues the last days,
please update to the actual suite, >> 1.5.6 
,
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/051adf1a-d5fe-4535-b9a3-946f466f39f9)
