### ISSUE TITLE
Version 1.5.7 EU  slow to load

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#3957]
Compared to previous iterations when you power up it is noticeably slower on x18s with complex "Mike Shellim" templates. On a simple model it is not too noticeable

**Comment by strgaltdel** [comment]
duplicate  of #3925

**Comment by bsongis-frsky** [comment]
Exact. And the fix has been already tested by @strgaltdel, 1.5.8 will be 4 times quicker than 1.5.7
