### ISSUE TITLE
affichage des noms de courbes

### ISSUE THREAD

**Issue by jjgracia** [FrSkyRC/ETHOS-Feedback-Community#3958]
Dans le menu "courbes" serai il possible d'élargir la colonne texte afin de voir la totalité des noms de courbes , merci ?

**Comment by bsongis-frsky** [comment]
Une copie d'écran ? Quelle radio ?

**Comment by jjgracia** [comment]
![IMG_20240503_191151 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/168630753/27d81505-f4a7-4017-848b-b1dfb59c9e6e)
ci-joint la photo

**Comment by jjgracia** [comment]
sur une X20S

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/3490aa9c-9874-46de-92da-71e24d3a10ac)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9cc847b5-0109-4c87-abda-5d86cc71df0c)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9c378b14-6c14-407a-9c25-057875b905b7)

**Comment by jjgracia** [comment]
super merci bonne journée

----- Mail original -----
De: "Bertrand Songis @ FrSky" ***@***.***>
À: "FrSkyRC/ETHOS-Feedback-Community" ***@***.***>
Cc: "jjgracia" ***@***.***>, "Author" ***@***.***>
Envoyé: Lundi 6 Mai 2024 15:19:39
Objet: Re: [FrSkyRC/ETHOS-Feedback-Community] affichage des noms de courbes (Issue #3958)





image.png (view on web)
