### ISSUE TITLE
% value in Outputs should not be rounded

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3959]
Ethos 1.5.7

Curves should should not do any rounding to the nearest %.

I used a test Var of 20.6 to adjust a curve point. Using the curve to adjust the mid point of 1500us I get an output value of 1607us which is not correct,  and the  % value says 21.0%. Calculation is 20.6% of 512us = 105.472 so output should be 1500 + 105.472 = 1605us not 1607us.

Please refer to ch6 in the screenshot below:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/344aa255-3506-4a9f-a39a-2c154e1b479d)

**Comment by Alex00101** [comment]
I agree, please also note that curve points editor also does not allow anything but whole percents, it'd be much better if curve points could have the same precision as vars

**Comment by Alex00101** [comment]
May I please bump this up? Would be very useful if implemented

**Comment by lthole** [comment]
As already argued:
In Outputs the min/max can be adjusted to within 0.1%. It is much more convenient to adjust the output using a curve, so in this case the curve should also be adjustable to within 0.1%. This is important on gliders with large control surfaces where you need to match for example the ailerons and flaps to align exactly.

**Comment by bsongis-frsky** [comment]
I will work on this now. But I will really like if I get help for tests in the next nightlies, because this sort of change is dangerous if not done properly!

**Comment by bsongis-frsky** [comment]
I think that Curve offset should also have one decimal to be consistent!

**Comment by robthomson** [comment]
@bsongis-frsky let me know what u need tested.. I have time to play tomorrow on this

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/33c2d6db-94f4-43a3-8d62-1012927605b1)

![image](https://github.com/user-attachments/assets/146e077e-74a9-47b9-a587-ff0e8bdca8b7)

![image](https://github.com/user-attachments/assets/f314b5a1-7a80-4013-ab4e-93003d9975c4)

**Comment by Alex00101** [comment]
Looks great and happy to test!

**Comment by bsongis-frsky** [comment]
Keyboard support added in Model / Curves screen. Much needed with 1 decimal!

![image](https://github.com/user-attachments/assets/37e1c2e0-d1d1-4cb8-bb5a-3b98fa46dc3d)

**Comment by bsongis-frsky** [comment]
1 decimal added to curves offset

![image](https://github.com/user-attachments/assets/d7768d10-180e-4642-ae43-d86c0fa6081b)

**Comment by spoke2570** [comment]
Has anyone tested the conversion process to make sure that the new precision is added the end of existing curve points, so point at 20% isn't converted to 2.0% when updating?

**Comment by bsongis** [comment]
Yes I have checked that myself. But tests are never enough as we have seen so much in the past!

**Comment by spoke2570** [comment]
Thanks for your diligence!
