### ISSUE TITLE
File Operation Error when updating Ethos Suite

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3960]
When trying to update the Ethos Suite from 1.5.5 to 1.5.6, it downloads to 100% and then ends up with a File Operation Error.

Since the Windows UAC popup is not appearing, it has to be running with Administrator rights to update correctly. This is not mentioned anywhere and may confuse less experienced users. Could this information be added to the Updater screen?

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/50e31e64-454b-4db1-8daf-24fca4696b12)

**Comment by pstasek** [comment]
Sorry, duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3950

**Comment by mawzthefinn** [comment]
Closing off as duplicate
