### ISSUE TITLE
no more sounds after updating

### ISSUE THREAD

**Issue by creepyflyer** [FrSkyRC/ETHOS-Feedback-Community#3963]
hey guys
I had to try and update my x18s 
Now i have no more sounds 
i have tryed to restore the sounds folder to a backup i did before i did the update
even after that still no sounds 
when i go to where u select in special functions the audio you want to play  where i says voice   there i can not select anything anymore it only says voice 1- default 
i sure hope someone can help me solve this 
when i connect my radio to the suite and look in the folders  in the nand folder there is a audio folder that has sound file's also in the usb station witch is my sd card i think there are the same audio file's

**Comment by strgaltdel** [comment]
could you give a more detailed info ?

this kind of problem, for example , happened after update 1.4 > 1.5 when user didn't  configure the new audio system / folders
i guess the new audio system is described in the manual

a lot of  "problem solving, how to" was descibed in several issues here and on rcg's x20 thread

if it's another case, you need to give more infos

**Comment by creepyflyer** [comment]
> could you give a more detailed info ?
> 
> this kind of problem, for example , happened after update 1.4 > 1.5 when user didn't configure the new audio system / folders i guess the new audio system is described in the manual
> 
> a lot of "problem solving, how to" was descibed in several issues here and on rcg's x20 thread
> 
> if it's another case, you need to give more infos

thanks for wanting to help  i did indeed go from 1.4 to 1.5 update can you please tell me where to find this info about the new audio system and what tho do when updating

**Comment by strgaltdel** [comment]
this post and the related links should cover most "popular user 1.5 issues"

https://www.rcgroups.com/forums/showthread.php?4513483-Ethos-1-5-Upgrade-notes-and-typical-issues-after-upgrade

1.5 manuals

https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5/doc

**Comment by creepyflyer** [comment]
> this post and the related links should cover most "popular user 1.5 issues"
> 
> https://www.rcgroups.com/forums/showthread.php?4513483-Ethos-1-5-Upgrade-notes-and-typical-issues-after-upgrade
> 
> 1.5 manuals
> 
> https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5/doc

Thanks very much its working now   it was a bit of a panic situation for me
