### ISSUE TITLE
Form choice box closing 

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#3966]
It's possible to open a choice box in the forms system.

It would be handy to be able to close it from outside of the button functions.

Essentially pass a parameter to it from the main loop to tell it to close.

**Comment by bsongis-frsky** [comment]
When do you want that the system closes the selection box for you?

**Comment by robthomson** [comment]
How about a prompt with a timeout?

Or displaying a message while a background task is happening?

**Comment by bsongis-frsky** [comment]
I see where a message / progress in a popup can be useful, but I cannot see why the system would close a Combo Box when you just opened it!

**Comment by robthomson** [comment]
I guess mostly I found it because I wanted a way at the time to do the progress box...   So that does duplicate.

But I do think it would be usefull at times.
