### ISSUE TITLE
Some icons are not displayed in firmware 1.5.7. ( X20S )

### ISSUE THREAD

**Issue by jsungho** [FrSkyRC/ETHOS-Feedback-Community#3967]
I am using X20S and X10 Express transmitters.
Some icon representations are missing in firmware 1.5.7.
It works fine on x10.
Icon display is missing only on x20s.

All displays work properly with firmware 1.4.17.

-------------------------------------------------
I registered the firmware using the file below.
-------------------------------------------------
X20S_BOOTLOADER_1.4.15
X20S-FCC_1.5.7
X20_FLASH
X20_SD

Please refer to the attached image.

![20240503_123122](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/30236335/d8cb283c-3012-4e66-966e-be9c3fd063fd)
![20240503_123106](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/30236335/ae8e33a4-5f59-4514-bdc6-1d3d6608361d)

**Comment by Wolepo** [comment]
Since the bitmaps are not available separately, I would install the simmulator of the X20S and copy the system bitmaps from the installation and paste them into the X20S.

**Comment by jsungho** [comment]
> 비트맵은 별도로 제공되지 않기 때문에 X20S의 시뮬레이터를 설치하고 설치에서 시스템 비트맵을 복사하여 X20S에 붙여 넣습니다.

I confirmed that the bitmap file exists.
Even though the file exists, it is not displayed.
There was no problem with firmware version 1.4.

**Comment by mawzthefinn** [comment]
Update your System Bitmaps via ETHOS Suite.

**Comment by bsongis-frsky** [comment]
You miss many system bitmaps if you have kept 1.4.17 ones!

**Comment by jsungho** [comment]
> You miss many system bitmaps if you have kept 1.4.17 ones!
All bitmap image files are newly installed.
There is no problem with the installation.

**Comment by jsungho** [comment]
> 업데이트하세요.
Thank you !!!
I updated the system bitmap via ETHOS SUITE and it works fine.
