### ISSUE TITLE
All  my screen settings for Telemetie are delete when telemetrie sensor delete and new search

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#397]
All my screensettings for Telemetrie are deleted

I would understand when my screen settings with the telemetrienames would show Zero or  NoData or OFF
but not compelete delete my setting.

When I Kopie my "Standardmodells"  its the same.

I have 3-4 Screens settings for Telemetrie and all work is away, each time 

sorry but  this is not only terrible, it's a mess

Telemetrie has fixed  names and i use this names and not a columenummer at telemscreen

later I  have calculated Telem-names, would be then the same?

You can not leave it like this

**Comment by Hobby4life** [comment]
Today turning on tx. Indeed one page completly empty. No sensor readout. Only blank boxes where the sensors where assigned. Had to reassign all the fields again.

**Comment by bluelex73** [comment]
I had the same problem after restarting the sensor search.
I had to reassign the telemetry announcements in the special functions and reconfigure the screens with the telemetry boxes.

**Comment by hrenz** [comment]
Yes that is all terrible and not a solution
they can´t leave it like this

all our settings are deleted

**Comment by bsongis-frsky** [comment]
If your sensors are deleted, I am sorry but I cannot see how we could display something?
In OpenTX it's another approach: you will get a random sensor, depending on the next discover order
The same for everything which will reuse this sensor. It is deleted, all references are reset.

**Comment by Hobby4life** [comment]
I did not deleted or searched for new sensors. A new start up of the radio cleared all telemetry fields. This issue should not be closed so quickly

**Comment by hrenz** [comment]
the fields at the widgets has names
if there is no values for this field, then the field is  OFF or Zero or Red
but not simple deleted

All Sensors has names,  I can use this names as I like 
if a sensor supply the field with a value then I got it at the screen

**Comment by Hobby4life** [comment]
The field where assigned the day before, next day I had to reassign them.. 

I know what you mean with no sensor data = nothing in these fields.
But mine where are set back to default again.. Assigned to use as a widget.. but had to reassign them with a sensor input again.

**Comment by hrenz** [comment]
Yes, one or I had this effekt too
1 or 2 times

**Comment by bsongis-frsky** [comment]
@hrenz no, those widgets have no name, they just display the sensor name and value

**Comment by bsongis-frsky** [comment]
@Hobby4life your issue is very different, if you didn't delete your sensors, they shouldn't be cleared in the home screen

**Comment by Hobby4life** [comment]
> @Hobby4life your issue is very different, if you didn't delete your sensors, they shouldn't be cleared in the home screen

That's correct, Untill now I can not reproduce the situation. will keep you posted.
