### ISSUE TITLE
Elargir la zone "nom" dans le menu mixage

### ISSUE THREAD

**Issue by jjgracia** [FrSkyRC/ETHOS-Feedback-Community#3970]
Dans le menu "mixage" serai il possible d'élargir la colonne "nom" afin de voir la totalité du texte des noms des mixages merci ?

**Comment by bsongis-frsky** [comment]
Quelle radio ?

**Comment by bsongis-frsky** [comment]
Une copie d'écran ?

**Comment by jjgracia** [comment]
bonjour sur une X20S

Cordialement

----- Mail original -----
De: "Bertrand Songis @ FrSky" ***@***.***>
À: "FrSkyRC/ETHOS-Feedback-Community" ***@***.***>
Cc: "jjgracia" ***@***.***>, "Author" ***@***.***>
Envoyé: Vendredi 3 Mai 2024 17:55:06
Objet: Re: [FrSkyRC/ETHOS-Feedback-Community] Elargir la zone "nom" dans le menu mixage (Issue #3970)





Quelle radio ?

**Comment by jjgracia** [comment]
![IMG_20240503_191049 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/168630753/9ebc1729-a68f-4fbf-bb36-a2b121ea6e93)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/98cb8ecf-779c-43dd-a8f6-c8b0955ac806)

**Comment by bsongis-frsky** [comment]
Je vous suggère d'éviter les majuscules dans vos noms de mixages, elles prennent plus de place
Je garderais également la même façon d'écrire partout pour les phases de vol, donc soit PV, soit PH VOL, ou plutôt rien du tout, uniquement garder l'information utile

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1da01989-2820-4dbd-86d0-89e38fb61c16)

**Comment by jjgracia** [comment]
Bonsoir compris merci
----- Mail d'origine -----
De: Bertrand Songis @ FrSky ***@***.***>
À: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: jjgracia ***@***.***>, Author ***@***.***>
Envoyé: Mon, 06 May 2024 19:13:11 +0200 (CEST)
Objet: Re: [FrSkyRC/ETHOS-Feedback-Community] Elargir la zone "nom" dans le menu mixage (Issue #3970)

Je vous suggère d'éviter les majuscules dans vos noms de mixages, elles prennent plus de place
Je garderais également la même façon d'écrire partout pour les phases de vol, donc soit PV, soit PH VOL, ou plutôt rien du tout, uniquement garder l'information utile
