### ISSUE TITLE
GPS speed has no relationship to actual 

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#3971]
Latest EU firmware, X18S, Matek GPS running latest INAV.

when I fly LOS I have speed set up on my Tx but it is totally random. Speed displayed on OSD is accurate and plausible

**Comment by miggy1952** [comment]
This may be the same thing as Ethos 1.5.6 with ELRS wrong telemetry value for GPS Speed #3919

**Comment by bsongis-frsky** [comment]
#3919 is after ELRS GPS Speed, do you use CRSF protocol (ELRS or Crossfire) with your latest INAV / Matek GPS?

**Comment by bsongis-frsky** [comment]
Perhaps you can have a quick check o the latest 1.5.8 nightlies to see if it fixes your problem?

**Comment by miggy1952** [comment]
Yes using ELRS CRSF into a flight controller running INAV

**Comment by bsongis-frsky** [comment]
Duplicate of #3919 then!
