### ISSUE TITLE
Version 1.5.7 mise a jour, display uniquement en Anglais

### ISSUE THREAD

**Issue by JeeFreeze** [FrSkyRC/ETHOS-Feedback-Community#3972]
Ce jour mise à jour réalisée de 1.5.6 vers 1.5.7
Le display de la radio est maintenant Anglais et non plus en Français et impossible de le changer le Français n'est pas dispo dans le choix du langage du Display, seul l'anglais est disponible

**Comment by bsongis-frsky** [comment]
Mise à jour sans doute pas faite correctement

**Comment by JeeFreeze** [comment]
Mise à jour réalisée depuis Ethos suite... et tout c'est bien passé pourtant... aucun message d'erreur à la fin de la mise à jour 

Ou y aurait-il eu un fausse manipulation ? Que puis-je faire pour corriger la situation ?

**Comment by bsongis-frsky** [comment]
Il faut mettre aussi à jours les traductions pour l'affichage

**Comment by JeeFreeze** [comment]
Pourriez-vous préciser votre propos ou expliquer et décrire précisément la manipulation à faire depuis Ethos suite s'il vous plaît ?
[edit] Après plusieurs tentatives depuis ethos suite 1.5.6 la mise à jour du display français est enfin passée ... c'est incompréhensible, je n'ai rien fait de plus que la manipulation initiale[/edit]

**Comment by J-charles-C** [comment]
Salut,

As tu, sous Ethos, après avoir coché voix et menu en français, tenté une mise à jour des composants installés ? (en lieu et place de composants mis à jour)

https://frskytaranis.forumactif.org/download?id=2511

Jc

**Comment by JeeFreeze** [comment]
Bonjour,

Oui j'ai bien fait cette manip aussi
Sans raison apparente tout s'est mis à jour correctement... désormais tout est OK

Jee
