### ISSUE TITLE
Creating new model on X10S Ethos v1.5.7

### ISSUE THREAD

**Issue by Hennyvt** [FrSkyRC/ETHOS-Feedback-Community#3973]
When using the Wizard on Ethos v1.5.7 on X10S selecting Model select hit the + key and select model type "Plane" am unable to progress further. What steps are required to setup the new model, or is there a bug.

**Comment by Alex00101** [comment]
Select Airplane then press PgUp/On to go forward, long press same button to go back

**Comment by Hennyvt** [comment]
Thank you

**Comment by mawzthefinn** [comment]
Closing as answer provided
