### ISSUE TITLE
Create model folder on X10S

### ISSUE THREAD

**Issue by steffku** [FrSkyRC/ETHOS-Feedback-Community#3975]
It's not possible to create a model folder on X10S. The '+' symbol is missing.

**Comment by Alex00101** [comment]
In model selection screen long press PgUp/Dn button

**Comment by mawzthefinn** [comment]
Closing as answer provided

**Comment by steffku** [comment]
Sorry for raising this issue, but how can i know this? I'm relying on the documentation that comes with the source code zip describing the x20. Is there a documentation for the X10S or Horus also? Or is there a common rule, like "if there's no button to select, long press PgUp/dn button"?
