### ISSUE TITLE
[Feature Request] add a push button on X20S

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#3979]
bonjour
j'aimerais remplacer sur une X20S un switch 3 positions, mal placé (peu ergonomique) par un bouton poussoir. est il possible que ETHOS puisse permettre la déclaration d'un tel bouton poussoir, et permettre un fonctionnement instable ou au contraire un mode toggle?
ce serait vraiment bien de pouvoir ainsi rajouter, au bon endroit un tel bouton poussoir

Good morning
I would like to replace a 3-position switch on an X20S, poorly placed (not very ergonomic) with a push button. Is it possible that ETHOS can allow the declaration of such a push button, and allow unstable operation or on the contrary a toggle mode?
it would be really good to be able to add such a push button in the right place

**Comment by J-charles-C** [comment]
Salut,

quand tu es dans le menu Matériel, tu va dans configurer potards / slider. Tu peux changer le type d'inter en 2, 3 positions ou poussoir.

ce n'est pas ce que tu veux ?

Jc

**Comment by 4qr1hu9n7** [comment]
Sure. Just identify the switch from 3 position to 2 position.

**Comment by samsab1** [comment]
sauf erreur de ma part, il me semble qu'on peut avoir poussoir comme option possible, mais sans possibilité de définir le mode de fonctionnement de ce poussoir (toggle ou pas toggle).
me trompe je?

**Comment by mawzthefinn** [comment]
You can do this today. If you wire in a Momentary Normally Open switch in place of the 3-pos, you will get middle and one of the two other positions as the active position (depending on how you wire the switch, Wire to middle wire and your choice of the other two wires)

**Comment by bsongis-frsky** [comment]
Utiliser les forums pour les questions. Ce repo est pour les demandes de nouvelles fonctions / remontées de bugs

**Comment by samsab1** [comment]
alors est il possible d'avoir, comme pour les 6 boutons natifs de la X20, le choix identique quant à l'usage de ce nouveau poussoir? c'est à dire pouvoir opter pour un comportement purement instable ou un comportement de type 'toggle"
