### ISSUE TITLE
Value Watt/min from SM Unilog not visible or possible?

### ISSUE THREAD

**Issue by gjvo** [FrSkyRC/ETHOS-Feedback-Community#398]
I tested a SM Unilog and it works in Ethos.
All the values come thru but in some competition classes we use Watt/min.
Some classes like F5B have a limiter and in F5B that is 1750 Watt/Min.
That is normally calculated in the transmitter.
In the Taranis and Horus OpenTX it works, in Ethos i dont see it so i think it is not available.
I would like that option and i think many people that fly F5B, F5F and F3E.

Gert

**Comment by bsongis-frsky** [comment]
Will come with DIY sensors
#459
