### ISSUE TITLE
Add frankiearzu / DSMTools to ethos multi module

### ISSUE THREAD

**Issue by Crunch69** [FrSkyRC/ETHOS-Feedback-Community#3980]
Set of tools that works through the multi module to configure bind and fly e-flite planes and ESC's

**Comment by mawzthefinn** [comment]
That would be up to @frankiearzu to port his tools over to ETHOS.

**Comment by frankiearzu** [comment]
Have no radio who runs Ethos.. but I can do a good part of the port with something equivalent to Companion.
When looking at some LUA code, seems very similar.

There has been a few changes in the telemetry firmware to support TextGen. I don't think that the source code of Ethos is available to check, but will collaborate with FrSky if they can help (needs access to equivalent "multibuffer").

**Comment by mawzthefinn** [comment]
@bsongis-frsky - Can you answer @frankiearzu's question regarding multibuffer equivalent support for MPM modules?

**Comment by robthomson** [comment]
Key thing really is to look at using ethos forms.

I have a good understanding of the forms..   @frankiearzu I am happy to work through with you to get a better understanding of the protocol inplimentation?

**Comment by frankiearzu** [comment]
Will start working on it soon.. just got an used FrSky X10S that can run Ethos.

**Comment by robthomson** [comment]
Great stuff.   For best effect you want to use ethos forms if possible.  Shout if you need any help in this regard.

**Comment by bsongis-frsky** [comment]
Working on it with @frankiearzu these days

**Comment by frankiearzu** [comment]
Tracking my port on this ticket.. Bertrand's team already provided what i needed in the firmware.
https://github.com/frankiearzu/DSMTools/issues/21
