### ISSUE TITLE
R9mx telemetry lost

### ISSUE THREAD

**Issue by Fernandolewandowski** [FrSkyRC/ETHOS-Feedback-Community#3981]
losing telemetry on the r9mx so I went to look for an update for it considering that there were several internal module updates regarding telemetry and its update is from 2020. I don't understand if this is the problem but I think it's very old compared to the internal module, another request is an update. from the r9mm to the ethos since I use it on the drone....

**Comment by raydars** [comment]
I use R9 mini/mm 1.3.1 flex with latest RF module internal firmware 1.1.13  X20 pro and it works perfectly fine with no telemetry drop outs.   Your post lacks detail.
