### ISSUE TITLE
Edit Model Menu, receiver list: TW serie  is missing exept TW SR12.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#3982]
Hello,
Edit Model Menu, receiver list: TW serie  is missing exept TW SR12.

**Comment by bsongis-frsky** [comment]
Which receiver are you missing? Only the stabilized receivers are in the list

**Comment by philippe-warnotte** [comment]
Hello, missing  receiver TWIN SERIE: TW SR8  
 My tx is Kavan V20.

**Comment by mawzthefinn** [comment]
> Which receiver are you missing? Only the stabilized receivers are in the list

Several receivers are missing from the list, including the TW SR8 and the Archer SR6, SR8 pro and SR10 Pro.

**Comment by Richrfl** [comment]
Found another one. SR10Pro does not show in the Stabilized receivers list in the Edit Model. 
Two questions bout this list: which is the objective of the list and how do I proceed to set up my SR10 Pro, until the model is included in the list?

**Comment by mawzthefinn** [comment]
> Found another one. SR10Pro does not show in the Stabilized receivers list in the Edit Model. Two questions bout this list: which is the objective of the list and how do I proceed to set up my SR10 Pro, until the model is included in the list?

1. The list allows you to select a receiver and populate the gain & flight mode mixes for that specific receiver
2. The SR10 Pro uses the same mix layout as the S6R and S8R

**Comment by Richrfl** [comment]
Thanks a lot mawzthefinn. Works excellent!!
