### ISSUE TITLE
Feature request: Function Switches LEDs controlled by a Special Function

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3983]
Would it be possible to have the FS LEDs status controlled by a Special function, please?

I have a logical switch controlled by a momentary FS press but it's only activated when the conditions are met. It would be nice to have the LED indicate that logical switch state instead of the button pressed state.

**Comment by strgaltdel** [comment]
I usually use FSWs to set logical switches in some way, and the current variant clearly shows their status,
I personally think this is the correct way todo

If the LEDs were given a different function, this status information would be lost.

If only certain FSWs were to be operated by the desired SF, the mix would quickly lead to misinterpretations of users
"non standard implementations highly raises failure rates"

A status display of LSWs should, in my opinion, rather be realized by a Lua widget. 
(kiss principle)

**Comment by pstasek** [comment]
ok, let me put it this way... I'd like to use the momentary FS6 to control the Remote NFC switch channel, which can be operated only under certain conditions, i.e. when the ignition is turned off and the FS6 is held at least for 2 seconds. A sticky logical switch does this. It would be nice if the LED signalised the logical switch's state rather than being lit when it's being held.

A Status display of LSW via widget takes up precious space on the display and being able to control the LEDs via a Special function would allow for displaying more binary values/statuses (only as an option, of course, not to break compatibility with current FSW users).
