### ISSUE TITLE
Scrollbar in the action management is missing

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#3984]
Hello,
there is a [Actions] section in a mixer. Up to 9 entries can be made in this section. The scroll bar is present and you can scroll up and down. 
![Action1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/79882fd2-0c59-40d7-9a09-5b77a56c1747)
If you leave this section and call it up again, there is no longer a scroll bar. If you scroll down, the selection disappears, but the remaining lines are not visible.
![Action2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/f01ee12e-f623-47d2-aea0-07d7d9bc47cd)
If you delete a line, the scroll bar becomes visible again and you can edit.
Please fix this error 
Thank you Wolfgang

**Comment by bsongis-frsky** [comment]
The fix is ready for the next nightlies
