### ISSUE TITLE
suite 1.5.6 not able toopen my transmitters

### ISSUE THREAD

**Issue by NorbertHeli** [FrSkyRC/ETHOS-Feedback-Community#3985]
Hello again,
Suite 1.5.5 could open my transmitter. All suite before couln´t  not open by bootloader 1.4.15
Now again not.
there my crashpay:

[main-20240505.log](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15213948/main-20240505.log)

**Comment by Nicholas-Luoyi** [comment]
What do you mean by not being able to open your transmitter?

**Comment by NorbertHeli** [comment]
That mean, ETHOS can´t open the transmitter.

1) Tx start at bootlader
2) Ethos staren
3) Tx connected at USB
4) Ethos no reaction, but explorer shows  drive e: and f:


![Ethos](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/3a4eed64-b310-4e70-b457-a6676d090c7c)
![Bootloader](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/228e33ed-05fe-4323-9477-04a9616e8a25)
![Connected](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/f1d56e4a-7ee8-4863-8356-c7908e1a7bff)

**Comment by Nicholas-Luoyi** [comment]
The log recorded nothing. Please attach the file below into the path "Ethos Suite/resources/" as the image shows. And then open Suite. Connect your radio until the file explorer shows the disks. Then the log should record something.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/0351e01b-9a13-4d86-8d8c-34edf175208a)
[settings.json](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15242361/settings.json)

**Comment by NorbertHeli** [comment]
Sorry, I´m late - was not at home, done
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/a679774c-cd32-43c7-a04b-723fd181a5bf)

Sorry, now it works. I Don´t understand, because no difference when I opend this issue???

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12676940/29531243-1513-4a85-ae3e-db8498c8c73f)

Also works with the pro - sorry, I don´t understand why?

Thank you

**Comment by Nicholas-Luoyi** [comment]
This may be an occasional bug. But please keep the method of capturing the traces. If it occurs again then you could share the traces.
