### ISSUE TITLE
Update request - Ethos Lua Reference guide needs updating

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3986]
Most items in the Lua Reference guide need more explicit/detailed descriptions of how they should be coded, including examples. The example below shows how all of the functions should be presented.

> audioActions()
> Timer::audioActions 	( 		) 	
> 
> Get / set the audio actions of the timer.
> timer = model.getTimer(0)
> timer:audioActions({
>     {type=COUNTDOWN_VALUE, start=10, step=30},
>     {type=COUNTDOWN_BEEP, start=11, step=31},
>     {type=PLAY_FILE, start=12, step=32, filename="test.wav"},
>     {type=PLAY_VALUE, start=13, step=30},
> })
> local audioActions = timer:audioActions()

An example of how cryptic and non-detailed the Reference guide is, is shown below. I am attempting to create a new timer with 'Always on' as the startCondition, but all that is shown is:

>  startCondition()
> Timer::startCondition 	( 		) 	
> Get / set the active condition of the timer.
> Since
>     1.1.0 
> Parameters
>     condition	(Source, optional)
> Returns
>     condition (Source) 

There is no way anyone could use this to set up a newly created timer with 'Always on' as the start condition.

**Comment by bsongis-frsky** [comment]
Examples added to the whole timer library
