### ISSUE TITLE
Bring back throttle trigger in timers

### ISSUE THREAD

**Issue by mirko91** [FrSkyRC/ETHOS-Feedback-Community#3987]
I don't get why a simple and functional way of triggering the timer with the throttle as been removed. It should be as easy as before without wasting time or logical switches to do so

**Comment by Dsrenger** [comment]
There's a event called "throttle active"

Choose that as Start condition. 
Then you have the same as "throttle on-off" before. The timer starts with the throttle sticks and stops when you idle the throttle stick again.

If you want to start the timer with the throttle stick and the timer should never stop, then choose additionally "custom" as stop condition and leave the field blank. 

Then "throttle active" will start the timer and out will never stop.

It's all there

**Comment by mgsanna** [comment]
what about a fast little reading of the manual? it's also localized to mitigate the "fatigue" of reading and translate.....

**Comment by mirko91** [comment]
That's not for you Dsrenger, but for a comment that has been removed. What about the model conversion didn't work, tried to set it as per manual and didn't work either, after a few tries doing the same thing it did his thing. No need to say I'm lazy or I need to translate..
