### ISSUE TITLE
Hesitation in playing 'Welcome to Ethos'

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3990]
1.5.8 nightly on X20

There is a hesitation in playing the 'Welcome to Ethos' wave file on startup, perhaps due to the new nightly build warning? The word Ethos has a pause in the middle. i.e ETH___OS.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/07c91c69-7afc-4cb1-869c-8ef08d676fcc)

**Comment by lthole** [comment]
Here is the model file I am using.
[fwexample.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15214931/fwexample.bin.zip)

**Comment by bsongis-frsky** [comment]
Does it happen if you don't enable logs in your model loaded on startup?

**Comment by lthole** [comment]
That was it! If I disable logs, I don't get the stutter.

**Comment by lthole** [comment]
However, the logging should perhaps not be started until after the startup processing.
