### ISSUE TITLE
Some Telemetry Statuses copied from currently active model instead of being given consistent values

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3991]
When a model is created it inherits the Comp Mode status of the currently active model

When a model is created it inherits the Bluetooth status of the currently active model

Given the above, are there any other similar statuses which are incorrectly being inherited?

Thanks

**Comment by bsongis-frsky** [comment]
It's already fixed in the next nightlies.

**Comment by Jedsters** [comment]
Thanks, I knew you'd done it for Comp Mode, I wasn't sure if you'd done it for Bluetooth too. 
All good.
