### ISSUE TITLE
When Competition mode is selected and rejected, comp mode is turned on however telemetry sensors remain and remain active. 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3992]
On the telemetry screen, if you select 'Competition' to turn it on you get a warning 'All the sensors will be removed. Are you sure you want to continue'  and select No, then the Competition switch on the screen is left in the On position, telemetry continues to function normally and the sensors are not removed.  I believe this is contrary to the purpose of the switch and leaves the screen in an inconsistent state. 

See https://www.dropbox.com/scl/fi/bfscwzd2os8wu0br1yj3x/VID_20240505_135411.mp4?rlkey=a505zxvh09da06yopqujvxk1g&e=2&st=astq53w0&dl=0

Thanks

**Comment by bsongis-frsky** [comment]
Fix ready for the next nightlies
