### ISSUE TITLE
Delete all (sensors) does not tidy up the screen

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3993]
If you have a number of sensors defined and then select Delete all from the telemetry screen then all the sensors are deleted as expected. However the list is not tidied up and you end up with a load of empty space below Name, Value, Source
(just a minor formatting problem really).
Thanks

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6d1f622d-c445-4877-9f8f-0b3e8bf59315)

**Comment by bsongis-frsky** [comment]
Fix ready for the next nightlies
