### ISSUE TITLE
Add FCC and LBT labels to Flex firmware protocol selection drop-down

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3994]
1.5.8 nightly

It is not apparent to users that the FLEX915M/FLEX868M protocol selection also switches between FCC and LBT protocols. I propose that the drop-down selection box labels become:

     FCC (915Mhz) FLEX
     LBT (868Mhz) FLEX

This is especially relevant is the user is only using 2.4G receivers, in which case the 915/868 is irrelevant.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/da6a9356-c115-4653-9ce0-e605fa63051c)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0bf5adc4-20bc-45bf-aeb6-f404ec9d99ed)
