### ISSUE TITLE
Issues #3947 and #3959

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#3995]
My apologies if I am out of line but is there any chance these 2 (especially #3947 - SF/LS startup sequence issue) can be considered for 1.5.8? I use both a lot so would appreciate if these can be evaluated. 

Apologies if I'm being inpatient and these are being processed in due order.

**Comment by Alex00101** [comment]
Suggesting bumping this up, still present in 1.5.11

**Comment by mawzthefinn** [comment]
Closing off this as a double duplicate. Please continue discussion in the referenced issues.
