### ISSUE TITLE
Camber Mixer Airplane, Not possible to set Slow up and slow down

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#3996]
On airplane, it's not possible to set "Slow up" and "slow down" in "Camber" Mixer !

**Comment by strgaltdel** [comment]
may I suggest using the flap mixer?

I think it is basically the camber mixer with additional slow function
You can rename it to "camber" if you wish

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/45473529-9283-443a-a76d-c8260e5debef)

**Comment by philippe-warnotte** [comment]
Thanks for the tip!
