### ISSUE TITLE
1.5.7 "Repeat" SF not triggered if "skip on startup" is selected

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#4000]
May be related to #3947 
1. Create Special Function: Always On, Repeat 5S (or anything), Action: Play Audio (file). Skip On Startup Off (Default.)
2. Load model (or start SIM).
3. SF is triggered./audio is played on startup then each 5S - as expected.
4. Edit SF and change Skip On Startup to On
5. Re-Load model (or restart SIM).
6. **SF is  not triggered./audio is not played.**. Expected - SF to be triggered/audio played after 5 S then repeat each 5S. 
7. Edit SF and make any change - i.e. disable then re-enable.
8. SF is triggered and repeats each 5S from this point onward.

**Comment by mawzthefinn** [comment]
This is expected, because the trigger to start playing is when the active condition goes true.

Do not combine Always On and Skip on Startup, the two options do not play well with each other. 

Editing forces the transition to True.
