### ISSUE TITLE
lua os.clock() function returns time sporadically

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#4001]
The code shown below should return the time since the widget was started, every 10 seconds. However, when in use it returns the time at random intervals. At times the interval will be normal, but most of the time it is 20 or more seconds, and at times takes over a minute. 

  widget.tm1value = math.tointeger(os.clock())
  if widget.tm1value > widget.oldtm1value + 9 then
    widget.oldtm1value = widget.tm1value
    paint(widget)
  end

If working properly it would allow a programmer to have a timing method that is not dependent on any of the normal timers, leaving them free for standard use. 

I have attached a short video showing what is happening, and the lua script used to produce it. Rename osdotclocktest.txt to  osdotclocktest.lua. Video has a normal timer with the lua script running below it. If working normally, the bottom timer would be the same as the top every 10 seconds. 

Tested on sim and x20 using 1.5.6

[osdotclocktest.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15242331/osdotclocktest.txt)

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/7997610/3d4420cc-fbb6-4abe-885e-45e4eaf39e43

**Comment by Alex00101** [comment]
I cannot comment on the precision of os.clock() - I'm using it extensively and have not spotted any major discrepancies.
However, one thing I noted in your widget is that you are not supposed to call paint() directly. paint() handler is called by Ethos, you should use lcd.invalidate(). May I suggest you try that and check if you have better outcome.

**Comment by dwheeld** [comment]
Thanks for the suggestion. Tried it with the same results. I added the line to call paint() to see if it would cure my problem, and forgot to delete it later. I'm sure it's the os.clock() call because of 2 things. First, if I replace the os.clock() line with:

widget.timer1 = model.getTimer("On")
widget.tm1value = widget.timer1:value() 

which pulls the time from a normal timer, it works as expected and updates the display every 10 seconds. 
Second, debug shows that the os.clock() call returns a nil value most of the time.

**Comment by Alex00101** [comment]
Hmm, working for me all the time. However os.clock() return a float for me i.e. 2.494 so I use it like
local function get_time()
    return  math.floor(os.clock()*1000)
end
Would you try that?

**Comment by strgaltdel** [comment]
... 
Hi dwheeld, hi alex, 
there are several "points of interest" , let's say not "lua intended" ideas in the script which can cause a disfunctional script

the topic/issue is not a lua or ethos bug
we have our discussion on rcg, let's continue there, 
i'll upload another lua sample which will address some of the misleading thoughts in dwheels source code

"unfortunately" we started our rcg diskussion "in the middle of a lua journey"
some basics are missing...

udo

**Comment by Alex00101** [comment]
> ... Hi dwheeld, hi alex, there are several "points of interest" , let's say not "lua intended" ideas in the script which can cause a disfunctional script
> 
> the topic/issue is not a lua or ethos bug we have our discussion on rcg, let's continue there, i'll upload another lua sample which will address some of the misleading thoughts in dwheels source code
> 
> "unfortunately" we started our rcg diskussion "in the middle of a lua journey" some basics are missing...
> 
> udo

I agree, I was just trying to establish this is not likely a lua (os.clock at least) bug. Propose this to be closed.

**Comment by strgaltdel** [comment]
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/d3541eeb-9e87-47f7-92e1-b1b8beec1a5d)


demo widget and comments / explanations added in rcg lua thread

**Comment by dwheeld** [comment]
Alex00101,  math.floor(os.clock()*1000) made it work. And by deleting the *1000, I now get seconds. Can't thank you enough! As for accuracy, I let it run for 45 minutes and it was perfectly synced with the normal timer display. That's close enough for me. ;)

I will close this "issue".

**Comment by dwheeld** [comment]
strgaltdel, I will look for the discussion you mentioned on rcgroups.

**Comment by dwheeld** [comment]
Closed.
