### ISSUE TITLE
Channel Swapping suggestion

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#4002]
Hi, I notice with 1.5.8 we'll be able to swap channels.

I can't help wonder if a trick has been missed? Would the easiest solution not have been to simply allow channels to be re-ordered like everything else can be reordered? I guess it would make things slightly more work if one only does want a direct swap between 2 channels, (e.g. swap 2 an 4), but in most other cases moving channels to their desired location would seem to be quick and easy?

Possibly too late to change now but maybe for a future release as an alternative?

Thanks

**Comment by strgaltdel** [comment]
imho swapping is the better method,
it's a unique method to ensure that output configuration is taken into account and "nothing is lost"

example: you want to exchange a receiver which requires a different mapping:
"simply" moving channels to a so called desired location, without moving output config, will cause inplausible templates in many situations, "shouting for desaster" when user wouldnt control servo directions etc..

moving incl. output config overwrites the "old" output config, so you have to "store" this on another channel, "and so we are in swapping mode"

**Comment by Jedsters** [comment]
At this stage I wasn't suggesting replacing swapping so much as adding the ability to reorder channels as an alternative. It's just a bit more consistent with how things are done elsewhere, e.g. ability to move LS, FS, Curves etc. (although in those cases obviously this is little more than cosmetic).

I'm not sure if I've not made myself clear what I was intending or if I'm not understanding you. When I was talking about the ability to move output channels. What I meant is that the first output channel is channel 1 always going to channel 1 on the rx etc.. e.g. if 
Output 1 is R. Aileron going to rx channel 1 
Output 2 is L. Aileron going to rx channel 2
and you move Output 2 above Output then then 
Output 1 is now L. Aileron going to rx channel 1 complete with all its definition and Output 2 is now R. Aileron going to rx channel 2 with all its definitions.
As well as doing this the mixer defs would need to be updated swapping all references to 1 to become 2 and all references to what was originally 2 to become 1. I don't think Output channel numbers are used anywhere else are they (unlike opentx).  
I don't think the end result is any different from swapping channels (I've not tested that yet), it's just another way to do the same thing which is more consistent.
