### ISSUE TITLE
Incorrect text formatting (curves)

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4006]
Incorrect text formatting (curves)
X20S, 1.5.8 Nightly 09.05.2024

Greetings Eugen

![Version](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/61b74466-81e2-4e7d-ae39-6c8b27c41f3b)

![Kurven](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/c0eb9f1a-16c7-4521-80a7-3bcb53fc7ac4)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/47ee2c88-b1ad-47d9-93b9-623af07d1e23)
