### ISSUE TITLE
1.5.7 Invalid Model Data

### ISSUE THREAD

**Issue by chrisca70** [FrSkyRC/ETHOS-Feedback-Community#4008]
The bug is still present on 1.5.7 @bsongis-frsky

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3866

I just got a brand new X14S, installed 1.5.7 fresh, all is up to date according to Ethos Suite. I inadvertently reproduced exactly this same bug after selecting the "---" in the Special Functions Action dropdown menu. After this, and selecting another model and then back to the original model, it won't load "Invalid data". Cloning it creates a model with no screens, SFs, no sound

**Comment by Nicholas-Luoyi** [comment]
We missed it in 1.5.7 for X14(S) and Horus (radios without touch screen). It should be removed in 1.5.8.
