### ISSUE TITLE
1.5.7 Trim doesn't work with new "other" model

### ISSUE THREAD

**Issue by samyp1978** [FrSkyRC/ETHOS-Feedback-Community#4009]
Trims are ON, the value change on the main screen but doesn't change the value on the outputs screen.

**Comment by Nicholas-Luoyi** [comment]
If you select the "other" model. The model doesn't have any mixer defaultly.

**Comment by samyp1978** [comment]
So do I have to make a mixer for the trim ?

**Comment by mawzthefinn** [comment]
> So do I have to make a mixer for the trim ?

No, if you are using a Free Mix, just add an Offset Action with the Trim Function as the source.
