### ISSUE TITLE
Archer Plus SR8 gyro won't reverse

### ISSUE THREAD

**Issue by wicksy5508** [FrSkyRC/ETHOS-Feedback-Community#4011]
Just changed over to FRSKY

Running 1.5.7 on my V20
Running 1.1.0 on the SR8

Cannot get the gyro to reverse direction. I go into device config - SxR 

Module - External Modules
Wing Type - Wing Rud+Ele+Ail
Mounting Type - Level
SXR Enable - On

Then trying to invert gyro axis I switch

Ali Inverted - On
Ele Inverted - On
Rud Inverted - On

Gyro doesn't change direction

Also tried 
Mounting Type - Level reversed, also not working.

The only way I can get the gyro to reverse is to rotate in 180deg horizontally and then the axis is correct.

Hoping someone can help 

Neil

**Comment by mawzthefinn** [comment]
You need to use the SRx Lua to configure, Device COnfig->SxR only works with the old SxR, R9 Stab and Archer SR6/SR8Pro/SR10Pro, not the new Archer Plus SR, TD SR and TW SR receivers
