### ISSUE TITLE
Unable to set "Reset / Flight Data" special function as global

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4014]
Version: 1.5.7

As in title, it isn't possible to set such thing as global. For some reason you can do this with "Reset / Timers":

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/21fba19e-9293-42cc-839d-5c2dd75aa673)

but not with "Flight Data" (options is greyed out):

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/b8e8c927-6532-4c2a-a02c-9429637dc4a7)

Is this a bug or by intention? Or is it some kind of protection?
I think protection is better enforced by additional options in this function instead: #4013 

Preventing it from being global just means that we have to make it for every model, which is just a lot of clicking.

**Comment by bsongis-frsky** [comment]
A function can be global if everything inside can be global.
Here "All timers" can be global, and "Flight data" cannot, it is something which can be easily changed.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/de9a2def-891e-4fef-b279-6efe902b9362)
