### ISSUE TITLE
Screen Brigtness Option

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#4020]
Hello Bertrand,

When selecting ALWAYS ON as DISPLAY WAKE UP option, the SLEEP option should be grey as not selectable.

Thanks

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/67108ec6-6330-4606-b378-d4686313b8aa)
