### ISSUE TITLE
X18 MULTI MODULE DON'T WORK

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#4021]
Hi, i'm using too multimodules one vantac and one ir4x, both module works on a x20 but they don't on the x18 when i try to bind a x8r eu v2 lbt receiver. i update the main lua with the last release. i also try to change the lua script directory on radio memory instead of sd card.

**Comment by bsongis-frsky** [comment]
Do you have the "Multimodule" choice?

**Comment by ronron84** [comment]
yes on both radio and both module

**Comment by ronron84** [comment]
![20240513_132245](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16739660/40f8b26a-c8ac-497d-aa58-66d447cf5a2b)

**Comment by ronron84** [comment]
one pin is broke....

**Comment by bsongis-frsky** [comment]
It can explain your problem!
