### ISSUE TITLE
spektrum bind problem with multi module

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#4022]
i try to bind an orange 9ch dsm 2 receiver and it doesn't work, the servo refresh line shows ??? instead of 11 when i'm choosing 11.

**Comment by bsongis-frsky** [comment]
Which radio? Which Ethos version? Latest multimodule Lua script?

**Comment by ronron84** [comment]
hi, 
x20 ethos 1.5.7 
[mm-stm-serial-aetr-lbt-v1.3.4.0 (7).zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15293529/mm-stm-serial-aetr-lbt-v1.3.4.0.7.zip)

**Comment by ronron84** [comment]
yes the latest
![20240513_132245](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16739660/41676bf2-31e8-40e8-83a8-b1d9203df3d0)

**Comment by ronron84** [comment]
![20240513_132731](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16739660/2f0bcf97-579c-473a-96fd-028eb03dae00)

**Comment by bsongis-frsky** [comment]
The Servo refresh rate showing "???" is a bug which will be fixed in 1.5.8

**Comment by ronron84** [comment]
Thanks
