### ISSUE TITLE
Ralenti temporairement actif alors que non programmé

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#4023]
Bonjour Bertrand,
J'ai un planeur équipé de quadroflaps, j'ai une phase de vol ou mes flaps sont mixés avec mes ailerons ( fullspan ).
Cependant quand j'allume ma radio et mon récepteur, durant environ une trentaine de secondes mes flaps ( en ailerons ) fonctionnent au ralenti alors que mes ailerons fonctionnent à la vitesse normale.
Celà revient ensuite à la normale.
J'avais déjà remarqué ce phénomène sur d'autres modèles.
Tandem Xe, dernières mises à jour ( 1.5.7 )
Bonne journée

**Comment by bsongis-frsky** [comment]
Il me faudrait le fichier du modèle, il doit y avoir quelque chose de pas catholique là dedans

**Comment by Tonio62** [comment]
Bonjour,
Voici le fichier du modèle ;)
[minivec.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15310221/minivec.zip)

**Comment by Tonio62** [comment]
Bonjour Bertrand,
Je profite de la re ouverture de ce post pour signaler le même phénomène sur mon Mirage 2000 Kero.
Tandem xe à jour, rb25s et 2x r10 plus.
A l'allumage du récepteur, mes ailerons fonctionnent au ralenti alors que ma profondeur à vitesse normale ( mixage delta ). Cela revient à la normale environ 10 secondes après.
Bonne journée,

**Comment by Tonio62** [comment]
Bonjour Bertrand,
Je viens de voir que certains servos kst avaient une fonction de démarrage lent....
Peut être une fonction qui laisse le temps au servo de chauffer et qui ralentit temporairement sa vitesse ?
Il s'avère que le phénomène survient sur des kst a12 t et kst x10....
Peut être pas un bug ;)
Bonne soirée

**Comment by Tonio62** [comment]
![IMG_20240924_193310](https://github.com/user-attachments/assets/9693b724-fca5-4492-82ba-04bc1684f4a3)

**Comment by bsongis-frsky** [comment]
Est-ce-que dans Model / Outputs, vous constatez également cette lenteur ? Si vous ne la constatez pas, vous pouvez fermer l'issue, je ne vais rien pouvoir faire, le problème se trouve sans doute au niveau du servo ...

**Comment by Tonio62** [comment]
Bonjour Bertrand,
Non aucune lenteur dans les sorties.....
Je suis maintenant persuadé que c'est un mode automatique des servos kst, qui n'atteignent pas instantanément leur pleine puissance.....
Je clos le sujet ;)
Bonne journée

**Comment by Tonio62** [comment]
Kst slow mode at startup
