### ISSUE TITLE
EM loads the model from SD if it cannot be loaded from RAM

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#4024]
What if the model in the "SD" card has and older version than the one used from "RAM" ? Why not have an option to "clone" the RAM contents to the SD card ? That way both memory sources are the same.

**Comment by bsongis-frsky** [comment]
If the model is loaded from RAM it has the same version => no conversion needed
If the model is loaded from SD it is possible that it is not the same version => the conversion is done
