### ISSUE TITLE
Show graph in Free Mix action sub-dialogs

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#4025]
1.5.7

One of the great features of Ethos is that the Mixer shows a graph of the mix on the RHS. However, when the new mix actions were added, that facility was lost. Now, when you add an Action, a sub-dialog opens without the vital graph.

There is room for the graph, so I propose that all mix actions show the graph in their dialog. For example, for the Weight action, see below. I also suggest that the Action should be in the first line, and that 'Active condition' should be indented so it is obvious we are talking about the active condition for the Action, not the active condition for the entire free mix.

![free_mix_action](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/fd17e6e8-1cb4-4700-8a38-bf1f1b7023d0)

And the main free mix view remains as before:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/c96a0b23-cfe5-438b-91fc-003a66521383)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/69d7e7c3-ac66-4661-b934-8b76b6a608dc)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/37f83844-07e3-495f-b051-2c0af851a206)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d0b33e65-ab65-49de-a3dc-646c3112e30d)
