### ISSUE TITLE
Ethos Nightly Update 1.5.8

### ISSUE THREAD

**Issue by robertobrazill** [FrSkyRC/ETHOS-Feedback-Community#4027]
Uthos Nightly Update 1.5.8

I updated my X20S and it says that the version is not stable and that I shouldn't fly, so I downgraded the firmware to 1.5.7 but now I can no longer check my previously configured models. I've tried several previous stable versions, but in all of them my models no longer appear.
Is anyone going through this? How can I solve?

**Comment by Alex00101** [comment]
As far as I've been told Ethos converts models from lower to upper version automatically but not in the opposite direction. That why Jet Flyer's instruction suggests backing up before the upgrade. I hope you do have backup.

**Comment by robertobrazill** [comment]
Yes, I have the backup, but it's not working.

**Comment by strgaltdel** [comment]
Yepp,

1st IT rule before doing anything with relevance :  make a backup
2nd rule:  make another backup
3nd rule: check if you 've at least one or two backups
4th rule: ensure your backup works
5th rule: Go for whatever you want

What kind of Backup do you have?
i never went the "suite backup road" but copied the model folder (and some other files)  dozends of time, 
some handfull restores worked every time, so there are two options:

your backup is a backup of your 1.5.8 release
your restored model files were stored in a wrong folder
(must been /models)

(btw , in case you didn't touch a model file/template within yout 1.5.8 session, it shouldnT have been converted, and so it would run..)


regards

**Comment by spoke2570** [comment]
The restore function isn't working, or you are having difficulty reinstalling an older version of ETHOS?

**Comment by robertobrazill** [comment]
> A função de restauração não está funcionando ou você está tendo dificuldades para reinstalar uma versão mais antiga do ETHOS?

Yes. :(

**Comment by spoke2570** [comment]
Can Suite see the folder where your backups are stored?

O Suite pode ver a pasta onde seus backups estão armazenados?

**Comment by robertobrazill** [comment]
![WhatsApp Image 2024-05-14 at 10 13 05](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/160497670/a3ca0802-3fd5-4156-aa1a-9151388b1d46)

Yes, I can perform the backup restore, but when I restart the radio it gives me this error.

**Comment by strgaltdel** [comment]
did you try further?
finish the wizard and try to switch to another model.

maybe the radio tries a to open the last opened (1.5.8 or so) template and cannot find, so it starts the wizard.

**Comment by robertobrazill** [comment]
I complete the wizard, but my templates saved in the same folder do not appear.

**Comment by Wolepo** [comment]
Are the models visible in the Models menu? If so, clone a model and then try to open it.

**Comment by strgaltdel** [comment]
for sure you have a 1.5.7 backup?
i would suggest to upload a model file from your backup and we will try..

btw
regarding 1.5.8 milestones:
we reached 100%, 

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/ec4a69f6-b9bf-4f42-ac90-7de2c1b2b57f)

(-;

**Comment by spoke2570** [comment]
I’ve had that a couple times after updating, but like only first try turning the tx on. 
I would reinstall ethos 1.5.7 using the ‘write all components’ option. And then restore models and user bitmaps (scripts and audio if you are using custom sounds or scripts) from a 1.5.7 or before back up, using the restore tool. 
If that fails then look at the file structure on your SD card. It is also possible that the SD card is toast.

**Comment by robertobrazill** [comment]
> com certeza você tem um backup 1.5.7? eu sugeriria fazer upload de um arquivo de modelo do seu backup e tentaremos.
> 
> aliás, em relação aos marcos 1.5.8: atingimos 100%,
> 
> ![imagem](https://private-user-images.githubusercontent.com/20392683/330552160-ec4a69f6-b9bf-4f42-ac90-7de2c1b2b57f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzMyNzEsIm5iZiI6MTcxNTc3Mjk3MSwicGF0aCI6Ii8yMDM5MjY4My8zMzA1NTIxNjAtZWM0YTY5ZjYtYjliZi00ZjQyLWFjOTAtN2RlMmMxYjJiNTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExMzYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2MyZTVjMWY0NWVlOWU4Mjc2MDBkMzdmMDQ3ODRlMzgzMjY1NTU3MWMzOTYyYzk4M2NkMmE2NjQ1MTcxZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cQUq7qlymNdQsWLl1ni8PzLVD3uzxSJxhZbH7CVQm8U)
> 
> (-;

Are you going to release the 100% stable version of 1.5.8 yet?

**Comment by strgaltdel** [comment]
just 4 info:
1.5.8 "latest" / "release" is available.
did you try ?
