### ISSUE TITLE
Suite 1.5.6 - Mac 12.7.4 - Suite takes a long time to recognize SD card

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#4030]
I was plugging in to install the latest nightly 1.5.8 firmware. The ethos drive was recognized right away but the SD card took many minutes to become visible. No errors were given by my OS, and the drives were both visible to my OS. The firmware installation went normally. 

![IMG_0752](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/71014ff5-1a11-4eb5-ab78-9466d274729b)
![IMG_0751](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/ebf61efb-10a4-414a-b12b-307bd486099a)

**Comment by spoke2570** [comment]
Here is Suite's debug file from the session. The main log was empty. 
The drives are shown mounted in Mac OS as 'NO NAME' and 'X20_SD' below the Suite screen.

[debug-20240515.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15321925/debug-20240515.txt)

**Comment by Nicholas-Luoyi** [comment]
Do you have another radio to have a try? Suite seems to having trouble with reading the SD card

**Comment by spoke2570** [comment]
I don't but it is the stock card from a long time ago. So, there ya go: I will ditch the card.
