### ISSUE TITLE
TD R10 registration and binding okay but no output

### ISSUE THREAD

**Issue by Bockfisch** [FrSkyRC/ETHOS-Feedback-Community#4031]
Got a X20 for a month and bought ist with an TD R10 and TD R6. Both are working fine.
Now I got another TD R10, registration and binding without issues but I can't get any output to my servo.
Have one servo connected on Cannel 1 and set it to the slider in the middle but I get no response.
X20 is on newest firmware and I updated the TD R10 to the latest firmware but no progress so far.

**Comment by Dsrenger** [comment]
When you go to the Rx options, what does it state for pin 1?

Additionally, your output menu is showing movement on channel 1?

**Comment by Bockfisch** [comment]
In the RX options for pin 1 is ch1 (Servo) and I got movement on the outputs but servo stands still without any power

**Comment by T16-Pilot** [comment]
Turn off the gyro function or do a "Selfcheck" that will give you output on all channels.

**Comment by mawzthefinn** [comment]
Servo has no power? Or no movement?

If it's no power, how are you powering the receiver?

**Comment by Bockfisch** [comment]
The receiver is getting power from 4AA cells on channel 8 and the servo is plugged on on channel 1. 
Normally when you plug in a servo it goes to a neutral position and holdes it but no signs of movement. Tested other servos and it was the same. 
The telemetry shows me the 4,88V.

**Comment by mawzthefinn** [comment]
4.88V from 4 AA's?

Charge or replace the pack. It's empty. Can't run without power.

**Comment by Dsrenger** [comment]
A mistake that happens to me before.

Check if you really plugged in the servo correctly. 

I had a similar issue years ago, and agreed hours of searching, I recognized that the servo plug we plugged in incorrectly. (Then minus and signal is changed and the servo will not move) 

Just as thought to doublecheck

**Comment by Bockfisch** [comment]
4,8 should be enough for 4 zells with 1,2v each but it should give some movement. 

The things I have done on the X20 

Got newest firmware 

Got iRX4 lite and added the main.lua for multimodule but not working at the moment (module says binding successfully but TX stays in binding mode and get no connection or output)

I don't know if I messed up something. So far the "older" R10 and R6 working fine.

**Comment by mawzthefinn** [comment]
4.8V on a 1.2V nominal cell is completely drained. That battery is empty and I would not expect anything to work like that. 

If that's an NiMH or NiCD pack, recharge it.

**Comment by Bockfisch** [comment]
After work I check the connection and recharge the NiHM pack.

**Comment by Bockfisch** [comment]
Checked the connection and it was correct connected. 
Batteries is now on the charger but I made some pictures of the problem. ![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/167879946/89877e4d-5e9b-4e4c-b248-97dd59555502)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/167879946/5d9c180f-3720-447e-a809-57493597403a)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/167879946/e51fc77e-afc9-475d-bfd6-b7a76e472c7a)
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/167879946/c3639266-2991-4518-9764-f4dda5fd02be

**Comment by Bockfisch** [comment]
I cloned one of my working models and binded the R10 but no output, only binding and telemetry is working.
Then I binded a working R6 with the test model and I got output.

Looks more like a bad RX

**Comment by Bockfisch** [comment]
Today I got a new R10 and went through the whole binding procedure but the same issue.

1. selected model on the TX
2. went to RF system, switched it on an set to TD Mode
3. clicked Register
4. plugged in batterie for the RX while holding down the button on the RX 
5. get Register successfully and switched of the RX
6. clicked on RX 1 to bind RX
7. repowered the RX and binding was success
8. went to Outputs an named CH1 with Servo
9. went to Mixes and created free mix
10. Source was set to Pot3 and output to CH1 (Servo)
11. Servo is not moving or showing signs of live 
12. in output I can see the bar changing while sliding Pot3

Info gives me this 
Internal module: TD-ISRM HW:1.4.0 FW: 2.2.6 (EU-LBT)

Receiver1: TD R10 HW:1.3.0 FW: 1.0.12

Have I somewhere made a mistake?
The green an LED is on and the blue is blinking so binding should be good.
Telemetry is also good and i get 5.2V on my batterie.

**Comment by Bockfisch** [comment]
somehow I got really bad luck
after testing two new servos (MG90) without luck, I used a third one and it works.
I should have switched servos earlier but now I got a spare R10 for a next model.
thanks for the help solving my issue.
