### ISSUE TITLE
Ethos 1.5.8 Italian Update

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#4035]
[it.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15335138/it.csv)

@bsongis @bsongis-frsky

**Comment by bsongis-frsky** [comment]
Done. Take care I have done some formatting job, and it should be nicely formatted now:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/1.5/translations/display/it.csv

**Comment by mgsanna** [comment]
Very nice now!!!Inviato da iPhoneIl giorno 16 mag 2024, alle ore 14:57, Bertrand Songis @ FrSky ***@***.***> ha scritto:﻿
Done. Take care I have done some formatting job, and it should be nicely formatted now:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/1.5/translations/display/it.csv
