### ISSUE TITLE
temporisation non compatible avec les courbes

### ISSUE THREAD

**Issue by YvesBaroux** [FrSkyRC/ETHOS-Feedback-Community#4039]
Avec la version 1.5.6 l'association d'une courbe et d'une temporisation comme dans l'exemple ci joint ne fonctionne plus.
https://www.youtube.com/watch?v=Jgf-yC-IKLo&t=1260s
j'ai essayé de toutes sortes de façon et aucune ne fonctionne.

**Comment by Eagleowl1** [comment]
Ceci fonctionne très bien

Dans l'exemple
Canal 6 : trappes
Canal 7 : train

Créer LSWn et LSWn+1
et un mixer TRAIN et un TRAPPES
selon illustration

Les mixers TRAPPES et TRAIN sont actionnés par un switch 2 positions 

![image_2024-05-17_191330182](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97453480/adb1f731-c937-42f8-b4f1-678067202cf7)

**Comment by YvesBaroux** [comment]
Sauf que dans ta démonstration il n'est pas fait usage d'une courbe. Ce qui m'intéresse ( de façon théorique) c'est la séquence concernant les trappes "les trappes s'ouvrent, restent ouvertes pendant que le train descend puis se referment". pour cela il faut introduire une courbe et une tempo et là ça ne marche pas.
Un exemple plus simple, à l'aide d'un inter 2 positions on active un déplacement suivant une courbe en "V" avec une temporisation. L'action sur cet inter fait passer d'une valeur extrême à l'autre sans tenir compte de la tempo ni en suivant la courbe.

**Comment by Eagleowl1** [comment]
En effet la refermeture des trappes n’est pas prise en considération dans la proposition.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YvesBaroux** [comment]
En fait je n'ai de train à faire fonctionner et si je devais en utiliser un je pourrai utiliser un séquenceur, mais ce qui me chagrine c'est de ne pas pouvoir faire suivre une courbe sur un temps donné à une fonction et ce d'autant plus que ça marchait sans problème sur d'anciennes versions. De plus je trouve dommage d'avoir différencié le mode de fonctionnement des sorties principales(ailerons, profondeur .........) de celles auxiliaires. Il me semble que c'était plus simple et aussi puissant avant Ethos 1.5.
En tous cas merci d'avoir regardé mais je pense que B Songis devrait se pencher sur la question.

**Comment by Eagleowl1** [comment]
Je ne connais pas ton application, mais à mon humble avis, il n'est pas nécessaire de passer par une courbe pour définir un trajet d'un extrême à un autre, sauf si tu souhaites avoir une vitesse variable lors du déplacement.
En utilisant les tempos des Inter Logiques, les fonctions EDGE, STICKY, TIME GENERATOR et OFFSET (version anglaise) tu devrais arriver à ton résultat.
(Je constate que les fonctions nommées ci-dessus ne sont, à mon avis, pas traduites en français de façon très parlante, en tout cas pour moi).

Néanmoins si quelque chose fonctionnait avant un update et ne le fait plus après une mise à jour, c'est le bon endroit pour en parler.

Je ne sais pas si tu le connais, mais le manuel en anglais LTHOLE est très bien réalisé, à jour et avec beaucoup d'exemples d'utilisation. (dispo sur Github). Au vu du nombre de mises à jour récentes la traduction française date un peu, mais reste très utile)

**Comment by YvesBaroux** [comment]
Tu vas me trouver un peu chiant. En fait je pratique essentiellement le F3A et la VGM et j'ai tout ce qu'il me faut avec 1.5.6, mais à temps perdu je joue les "Geek" et j'explore les possibilités du programme. Donc je pense à des applications comme celle du train avec trappes complexes ou sur un planeur un pylône rétractable avec trappes et moteur électrique .............
Je suis juste désolé que des possibilités simples à mettre en œuvre et géniales dans le principe ne fonctionnent plus.
Je te remercie pour LTHOLE que je ne connais pas et que je vais regarder.

**Comment by Eagleowl1** [comment]
Pas chiant du tout.
Je viens du même milieu et certainement aussi de Futaba. 😅
Ethos est super et bien plus puissant, mais il nécessite un temps d’adaptation après avoir utilisé un autre système

Comme tu es un « geek » ça ne devrait pas te poser de problème de découvrir les nouvelles possibilités offertes et aussi de ne pas utiliser les courbes quand de meilleures solutions existent.
Si tu lit l’anglais, le forum dédié à ethos sur RC Group est une mine d’enseignement avec quelques personnes très compétentes qui mettent leur expérience de programmeur à disposition.
Ethos nest pas encore parfait mais A mon avis il dépasse tous les challengers.

Je pense qu’on devrait voir une phase de stabilisation avec un accent mis sur la « usability » et l’ergonomie d’utilisation.
Sauf si tu attends une fonction particulière dans un mise à jour annoncée, je conseille d’attendre 2-3 mise à jour avant de la faire.
Les versions stables sont totalement debuggees.
Ça permet d’éviter les petites frustrations.
Les développeurs font un job magnifique, j’espère qu’ils ne se lasseront pas et continueront sur cette voie.


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
