### ISSUE TITLE
Track playback somethis keeps looping/toggling

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#404]
I have noticed that sometimes in "somekind?" condition, keeps toggling/looping 2 playback tracks over and over back and forth.. and never stops.

X20S fw: 1.07EU, TD-ISRM v2.18

**Comment by bsongis-frsky** [comment]
I think this issue is linked to #417 
I need to understand what is the logic switch used for the Play Track function
