### ISSUE TITLE
suite 1.5.6:  suite reports "up to date" when on nightly 1.5.8

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#4041]
Hi,

as described,

was on nightly (may, 8th) and suite wouldn't have indicated that a final release / "latest" would have been available:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/65bb522c-641f-4cfa-a0a3-ab39ceffef08)
(server location git)

of course, command "write firmware & 18n" flashed the latest. successfully
pretty sure a user who is using nightlies would / should have no problems, but who knows....

and many, many thanks to this 1.5.8 release !!!!!!

((-:
regards
udo

**Comment by mgsanna** [comment]
1.5.8 is stable now..... so you are updated.....
perhaps it's better to re-flash the stable 1.5.8
other thing maybe are display language ....

**Comment by strgaltdel** [comment]
sorry, don't got what you meant.

i was on 1.5.8 nightly, not stable!

expectation: suite should have detected new, stable rev. and should have displayed on screen

actual result: suite shows "up to date", altough newer / latest rev is available

workaround: trigger update via selection as described

**Comment by mgsanna** [comment]
Ok I misunderstood your point of view! Yes definitely suite should recognize the right version!Inviato da iPhoneIl giorno 18 mag 2024, alle ore 20:45, Udo ***@***.***> ha scritto:﻿
sorry, don't got what you meant.
i was on 1.5.8 nightly, not stable!
expectation: suite should have detected new, stable rev. and should have displayed on screen
actual result: suite shows "up to date", altough newer / latest rev is available
workaround: trigger update via selection as described

**Comment by spoke2570** [comment]
@strgaltdel 
Udo, I just checked on my X20S before (Mine showed as up to date, too) and after the installation of the full release using write all components and it is because the full release firmware is identical to the nightly. 
On mine 1.5.8 FCC nightly and full release both carry the release version identifier #4fb5edae.
Best 
Peter B

**Comment by strgaltdel** [comment]
Hi Peter,

i was on x18s eu, had
 #7fcd85a0, 8th may, from nightly builds 
which didn't trigger update flag

now its
#4fb5edae, 16th may, from latest built

so in my case  i wouldn't say both versions were identical

regards
udo

**Comment by spoke2570** [comment]
Duoh! looks like we keep checking the dates!

**Comment by Nicholas-Luoyi** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/c4132aaa-5ca4-4887-9682-3349a94b5957)
Suite should be able to recognize the "nightly" suffix. Maybe @bsongis forgot to add the suffix while compiling the firmware?

(What the image shows is the firmware compiled by myself)

**Comment by Nicholas-Luoyi** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/89c37fbd-9be9-4f06-ac46-d617ecf9456a)
Maybe I could add a tag like this?

**Comment by spoke2570** [comment]
I like that last one.

**Comment by strgaltdel** [comment]
imho: "Danger" has something negativ,
implicit a high crash rate , most likely very buggy....

what about
"Caution: nightly/ prerelease built / don't fly"

**Comment by Nicholas-Luoyi** [comment]
OK for "Caution"
