### ISSUE TITLE
[Kavan V20]  Telemetry Lost when entering System / Information

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4043]
Firmware 1.5.8  Kavan V20: Telemetry Loss  signal when I go to the INFO menu.

**Comment by FlipAirboost** [comment]
I don't have this problem with my upgraded x18, same version at the moment.

suite ethos 15.6,  ethos 1.5.8 stable, win 10

**Comment by FlipAirboost** [comment]
I'm now waiting for a new change of title !

**Comment by philippe-warnotte** [comment]
Hello, Kavan V20 not Kavan X20...

**Comment by andika207** [comment]
> Hello, Kavan V20 not Kavan X20...

LOL :satisfied: 
je suis convaincu de que ce projet ridicule va durer peu dans le temps comme la radio Eachine TX16.
Frsky vient de lancer la version X20R au même prix 
le modèle d'affaires chez Frsky est de vendre des pièces directement à ses utilisateurs
alors que KAVAN fonctionne avec un modèle obsolète et prehistorique qui oblige les utilisateurs à passer par leur SAV $$$$$$ 
¿¿ pourquoi enrichir une entreprise qui ne fait uniquement que vendre du matos chinois rebadgé ??
il vaut mieux acheter le produit ORIGINAL et pas lo clone au moins tu es sûr de trouver des pièces pour longtemps. :shipit:

**Comment by philippe-warnotte** [comment]
Thank you andika207 for your very nice opinion. In aeromodelling, we all have our little favorites when it comes to buying equipment. 
Who can judge whether it is good or bad? The main thing is to have fun!
I thank Frsky for supporting Kavan updates.

**Comment by bsongis-frsky** [comment]
Confirmed by Kavan this morning

**Comment by andika207** [comment]
> Confirmed by Kavan this morning

bizarre... donc vous devez contacter et résoudre des problemes pour Kavan sans avoir une radio V20 devant vous

**Comment by bsongis** [comment]
Vos suppositions sont censées apporter quelque chose ?

**Comment by andika207** [comment]
> Vos suppositions sont censées apporter quelque chose ?

par rapport au sujet non puisque je n'ai pas une radio V20 chez moi
mais je pensais vraiment que sur votre bureau vous aviez tout disponible pour faire les tests et je vois que non si vous devez appelez le SAV de Kavan pour vous renseigner.

même chose pour le module MPM 4-1 je croyais que Frsky vous fournissait tout pour votre tavail mais non, vous devez chercher ailleurs chez les modélistes...  c'est bizarre non ?

**Comment by bsongis** [comment]
Bien sûr que FrSky me fournit tout le matériel (de la marque bien entendu). Pour autant je n'ai que 2 bras et je suis content quand on peut m'apporter un peu d'aide.

**Comment by andika207** [comment]
>Pour autant je n'ai que 2 bras et je suis content quand on peut m'apporter un peu d'aide.

si vous êtes seul à tout faire ça va être plus lent et dur et ensuite les plaintes vont arriver ? LOL

![screenshot 62](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/47242117/d966aa35-9e44-415b-a62d-05f369f63b64)

**Comment by bsongis** [comment]
C'est une plainte ? J'appelle ça plutôt une demande / requête.

**Comment by bsongis** [comment]
Un exemple de ce qu'il est possible de faire avec 1.5.10

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5603504/aeeae80a-3aa9-44b2-a037-a21fe116b94a)

**Comment by andika207** [comment]
> Bien sûr que FrSky me fournit tout le matériel (de la marque bien entendu). 

vu que la radio V20 est un produit OEM je sais pas s' ils ont le droit de fournir quoique ce soit mais Kavan peut le faire de son côté.

**Comment by andika207** [comment]
> Un exemple de ce qu'il est possible de faire avec 1.5.10

OK. mais il en veut plus que ça sinon il aurait rien dit.

**Comment by bsongis** [comment]
Bon, c'est bientôt fini les conneries, il vous faut une photo de mon étagère à radios ou quoi ?

**Comment by andika207** [comment]
> Bon, c'est bientôt fini les conneries, il vous faut une photo de mon étagère à radios ou quoi ?

avec plasir.

**Comment by andika207** [comment]
> Il n'y a pas d'autre marque de radio où vous pouvez obtenir des mises à jour et améliorations aussi fréquentes. 

il y a bcp de gens qui ne veulent rien savoir des MSJ constantes pour des bonnes raisons.

**Comment by samsab1** [comment]
je me demandais quand ça allait partir en vrille...........
pas déçu.

**Comment by andika207** [comment]
> pas déçu.

moi nonplus https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3979

**Comment by SmartTommy** [comment]
This new firmware has fixed this issue and we will release it as soon as possible

[TW-ISRM_1.0.7_Beta.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15428038/TW-ISRM_1.0.7_Beta.zip)

**Comment by bsongis-frsky** [comment]
Someone can confirm? Then we can close the issue

**Comment by philippe-warnotte** [comment]
Impossible de télécharger ce fichier "TW-ISRM_1.0.7_Beta.zip"le lien ne fonctionne pas.
Cloturez si vous voulez, j'attendrai la publication officielle.

**Comment by bsongis-frsky** [comment]
Firmware above attached again
[TW-ISRM_1.0.7_Beta.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15428976/TW-ISRM_1.0.7_Beta.zip)

**Comment by philippe-warnotte** [comment]
Thank you Bertand , you can close the issue

**Comment by jiristasek** [comment]
Update fixed the problem. Thank you.

**Comment by bsongis-frsky** [comment]
Thanks for the confirmatioon @jiristasek
