### ISSUE TITLE
Multiple engines not available in the model wizard 

### ISSUE THREAD

**Issue by Mizzgvus1** [FrSkyRC/ETHOS-Feedback-Community#4044]
When I go into create model, select Airplane,  then reciever, everything is good up to that point. When you move forward to engine, the only options I have are 1 engine or no engine.

**Comment by mszulen** [comment]
What radio/system version?
In my case (1.5.8 on X20s) with non stabilised receiver it gives me no engine to 4 engines selection
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6932464/837ef2d3-c777-41eb-b077-16df65da7311)

However with stabilised receivers - I see same as you say - no engine or 1 engine only.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6932464/3c2702c6-51c4-4e5e-aa43-6d96dbbdec8e)

**Comment by Mizzgvus1** [comment]
Sorry for more context I am using the X20 Pro , I first noticed the issue a day or so ago. The software version was 1.5.7. Currently I am on 1.5.8 and still having the same issues.

**Comment by Mizzgvus1** [comment]
[
![17161247402288013850357503802182](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/137743060/42cdee7a-1e3b-4fde-827d-b729e4917576)
](url)

**Comment by Mizzgvus1** [comment]
> What radio/system version? In my case (1.5.8 on X20s) with non stabilised receiver it gives me no engine to 4 engines selection ![image](https://private-user-images.githubusercontent.com/6932464/331860331-837ef2d3-c777-41eb-b077-16df65da7311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjQ5NjEsIm5iZiI6MTcxNjEyNDY2MSwicGF0aCI6Ii82OTMyNDY0LzMzMTg2MDMzMS04MzdlZjJkMy1jNzc3LTQxZWItYjA3Ny0xNmRmNjVkYTczMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTMxNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGRhODM2MTYwMzA5NmMyODUxM2NlMmViM2YzZWFkZGE3NTFiOTc0NjlhNjc4NjRjZWM3MjA1NThkMjZhZTA2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2MsQaRsTiJ-_-oYCrmfn1c3GKsP72O1lDPqK9714TQo)
> 
> However with stabilised receivers - I see same as you say - no engine or 1 engine only. ![image](https://private-user-images.githubusercontent.com/6932464/331860520-3c2702c6-51c4-4e5e-aa43-6d96dbbdec8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjQ5NjEsIm5iZiI6MTcxNjEyNDY2MSwicGF0aCI6Ii82OTMyNDY0LzMzMTg2MDUyMC0zYzI3MDJjNi01MWM0LTRlNWUtYWE0My02ZDk2ZGJiZGVjOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTMxNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2UxMGIwYjZlNGU4NTIwZjZkYWNhOTYyZWMyNDIxZDAyMDMwMmVmZGJhZmFkMjE4YjJiM2RmZDhmYTU4ZGY3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LXcT8BnCS7fl7etyEXKWZR4oYxcJy5Cp373cMzvkfiM)

Yes , same thing. I just tried it without a stabilized reciever and all options are present.

**Comment by Chilie78** [comment]
Could it be that it lists only one engine because the manual for any of the stabilized receivers show channel three for throttle as the only channel available? The list of channels in the manuals don't show more than one engine being allowed. That being said, as you reconfigure any of other channels that you aren't using (ie, switching aileron 4 to aux 4) that you could then have more than one engine that won't interact with the stabilizer.

**Comment by pstasek** [comment]
That's correct as the stabilized receivers only have one dedicated channel for throttle (3).

If you want to make multi-engine setup with stabilized receiver, you'll need to derive the engine channels from the Throttle mix, keeping the channel 3 linear from -100% to +100% for the other features to work.

Create free mix with source from Channel 3 and outputs to different channels and plug your ESCs or Throttle servos to these channels, where the stabilization is off.

Please note, you can remap the receiver ports to different channels, so if you want to use the port number 3, simply remap it to whatever you're setting your throttle output to.

**Comment by mszulen** [comment]
> That's correct as the stabilized receivers only have one dedicated channel for throttle (3).
> 
> If you want to make multi-engine setup with stabilized receiver, you'll need to derive the engine channels from the Throttle mix, keeping the channel 3 linear from -100% to +100% for the other features to work.
> 
> Create free mix with source from Channel 3 and outputs to different channels and plug your ESCs or Throttle servos to these channels, where the stabilization is off.
> 


Sure, I know it's simple, but isn't the Wizard's purpose/role to do it for the user?
This is, exactly, what happens when you select the non-stabilised receiver.
You get the summary window where you can confirm the channels selection and then the mixer is created that outputs the throttle value to all those channels:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6932464/8b42d816-c470-4f80-b7c5-24fe6ec860ed)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6932464/8f2db1da-3ee3-4c04-8664-be76d48f5502)
