### ISSUE TITLE
ethos 1.5.8 icon emergency mode absent

### ISSUE THREAD

**Issue by FlipAirboost** [FrSkyRC/ETHOS-Feedback-Community#4046]
After updating my x18 from ethos 1.5.7 to ethos 1.5.8, I do not have the emergency test icon as shown in the manual.

Win 10 ,  suite ethos 1.5.6.

On the other hand, yet disconnected with the soft suite ethos, my radio went into emergency mode after USB disconnection.

**Comment by Dsrenger** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5/lua/tool-emergency

You Need this lua for it.
Doesnt make Sense to offer EM for the average User by Default who can barely Set Up a aileron Mix ;)

**Comment by FlipAirboost** [comment]
Thank you, if the menus are dynamic or adaptive, I appreciate it, perhaps to be noted in the user manual.
