### ISSUE TITLE
X20S changes to Emergency Mode after plug off USB-C Cable when Helicopter Profile is selected

### ISSUE THREAD

**Issue by drewsho** [FrSkyRC/ETHOS-Feedback-Community#4047]
After update to Ethos Release 1.5.8 latest via Ethos Suite 1.5.6 and MacOS, I've disconnected the USB-C cable. Then X20S switched to Emergency Mode. This Behavior is reproducible.
When I've selected a plane Modell, everything is ok.
As Attachment is one Helicopterprofile
[t-rex 601.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15368767/t-rex.601.bin.zip)

**Comment by mszulen** [comment]
I've had similar situation just after upgrading.
Re-flashing solved it. Perhaps you can try it too just for test?

**Comment by strgaltdel** [comment]
hi Holger
. and to mention additionally, as described in the forum:

even cloning the template results in EM

**Comment by drewsho** [comment]
> I've had similar situation just after upgrading. Re-flashing solved it. Perhaps you can try it too just for test?

I've refreshed all Components now with the suite, but still the same behavior.

**Comment by bsongis-frsky** [comment]
@strgaltdel you cannot clone a model anymore? or it's just after USB unplugged?

**Comment by drewsho** [comment]
I can clone a model, but the result is the same. Switches to Emergency Mode!

**Comment by bsongis-frsky** [comment]
Reproduced and fixed
