### ISSUE TITLE
X20S on 1.5.8 Throttle cut safety

### ISSUE THREAD

**Issue by mszulen** [FrSkyRC/ETHOS-Feedback-Community#4048]
I haven't found the way to do it or perhaps it's not implemented:
It's about the throttle cut safety.

Scenario:
1. Throttle is above 0 and motors are working
2. Throttle cut is engaged and motors are stopped
3. Throttle cut is disengaged (with throttle stick above 0) and motors are suddenly starting to spin

What I'm looking for is to ensure the throttle is back to 0 before disengaged throttle cut allows the motor to spin. It's like arming protection in Betaflight etc, where I can't arm if throttle is not 0.

So the desired scenario would be:

1. Throttle is above 0 and motors are working
2. Throttle cut is engaged and motors are stopped
3. Throttle cut is disengaged (with throttle stick above 0) and motors are still stopped
4. Throttle stick has to be moved back to 0 before motors will spin again.

**Comment by joy2417** [comment]
You can solve this with some logical switches:
![Bildschirmfoto zu 2024-05-19 17-07-42](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/167970749/4ab6b9f8-f8e2-4167-a3ed-b494018ceee9)
![Bildschirmfoto zu 2024-05-19 17-08-33](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/167970749/fd110c8e-c2ef-40c3-ba57-aeaf383eaa6d)

**Comment by mszulen** [comment]
Thank you! I'll play with it!

**Comment by raydars** [comment]
Pretty sure sticky throttle is in ethos and has been for a long time,  I use it.  It's the feature throttle hold in the picture above and no need for logical switches.

**Comment by lpott6** [comment]
The safety feature is part of throttle hold as stated. Your problem is that the "Trigger value" is set to 100%. Set it to -85 or -90 and it will work. Now, when you have the throttle above -85 and disarm nothing happens. Once the throttle is moved below -85 the disarm takes affect. It will not re-arm while the throttle is above -85.

**Comment by bsongis-frsky** [comment]
Feel free to reopen if needed. Or even discuss it on RCG / other forums.
