### ISSUE TITLE
thumbnail load extremely slow when selecting model on X20 Pro

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#4049]
When changing models on the X20 Pro the thumbnail pictures take between 1 minutes to load, can provide video if useful.

**Comment by WhiskeyGolf** [comment]
I have the same problem with the X20Pro on 1.5.8.  Very slow!

**Comment by RealTadango** [comment]
Feels like it was faster before on my X20S. Smaller files help though.

**Comment by WhiskeyGolf** [comment]
My files are very small because it is still the resolution of the X12.

**Comment by fdm225** [comment]
has anyone tried using an external SD card?  I am wondering if the internal flash is just super slow or if this is a software issue?

**Comment by fdm225** [comment]
afraid that this hasn't been acknowledge by the developers means that it's being ignored; any comment?  Does anyone know if there is a way to transfer a model from the internal storage to the sdcard?  I am willing to put one into the unit if this is due to the fact that the internal flash is slow, but I suspect that it's more code related than anything as I am using the correct file size and type.

**Comment by fdm225** [comment]
Just to keep this thread updated, I moved the images to a class 10 sdcard and the image load was as slow as the internal flash; anyone have any suggestions here.  would love to get a confirmation from development that they acknowledge this or that there is a configuration issue (e.g. wrong image size).  I am using BMP files (300x280) from skyracoon.com specifically for the X20.  Anyone got anything?

**Comment by RealTadango** [comment]
Have you tried removing the image and loading the model?

**Comment by fdm225** [comment]
I have a 1/4 screen tile where one of them is the image; it loads fine.  No lag and the image looks correct, it's just the model selection screen where you have all of the images of all the models in that folder that has the issue.

**Comment by RealTadango** [comment]
I think all images for all models are loaded, not just the ones in the folder you are viewing. Do you have a lot of models? Maybe one has a large image file and delays the rest?

**Comment by bsongis-frsky** [comment]
Would you attach a zip of your models directory + models bitmaps directory, so that I can have a try on mine?

**Comment by fdm225** [comment]
Hi Bertrand,
files attached.
[Radio.zip](https://github.com/user-attachments/files/15810965/Radio.zip)
thanks for looking at this.
dave

**Comment by fdm225** [comment]
Hi @bsongis-frsky ,
were you able to get the zip file that I attached?  anything else that I can provide to get this looked at?

thanks,
Dave

**Comment by fdm225** [comment]
Could I at least get a confirmation that you got the files and have the Information needed removed from the thread?  I really don't want this closed as it's super annoying.  I know it's a minor defect but so are a bunch of others that I see commented on daily; any help would be appreciated (not to mention that I am not the only one complaining of this issue).

dave

**Comment by fdm225** [comment]
hey all,
@bsongis-frsky  @bsongis  did I offend someone?  what do I have to do to even get a response back on this or are older issues not looked at? should I just duplicate this so it's at the front of the queue?  Seems like a nightmare for the development staff but I ask as this is an actual issue that has been opened for more than a month and I have had a single developer respond asking for information (which was provided) and I can't even get a confirmation that it was needed.  

I am sure glad I paid $1000 and switched from EdgeTX (where I could actually look at and fix this issue myself); gee it's great.  Seriously, if this is ethos then I may have to rethink my decision.

dave

**Comment by RealTadango** [comment]
Did you try to start from a clean setup and see if it happend again? Or remove models / images? You can so much more to pinpoint the issue....

**Comment by fdm225** [comment]
so the solution is wipe my radio and start clean?  I thought microsoft was bad in the 90's and 2000's when the standard was reboot daily, this is a whole new level.  to answer your questions, I have started new model files but since this is on the model selection screen. I do not see the relevance to creating a new model vs duplicating as the actual model thumbnail in the model itself loads fine (see in one of the above posts).  As to wiping everything, no I haven't. This is supposed to be a device where I don't regularly delete the very things that I am using several times a week and frankly that's only an option I would even consider doing unless asked specifically to do it by a developer (and even then it's like the nuclear option as it's not fixing the issue and just moving around it). 

FrSKY made this a closed source consumer product and not a project so it should be treated like one and actually deal with the issues.  If the answer is delete everything and start again then it says there is zero code stability on this product and it can't be trusted; is that what you are saying?

**Comment by RealTadango** [comment]
You make a backup and can restore after testing. You can do more to pinpoint what is causing the issue. The dev's have a lot to do so maybe an issue that only you are facing is not a priority.... sorry.

**Comment by fdm225** [comment]
this is a consumer grade product, not an open source project and if you contact FrSKY support they send you here.  I have the luxury of two CS degrees so I know what I am doing and no, I wouldn't backup and restore this without interaction.  And sorry, the line "the devs are busy" doesn't really fly as this is over 30 days old without any substantive comments from them other than to ask for info and not even remove the information needed tag.  if they had even acknowledge it and said "we are busy" I wouldn't be ranting here but instead I see @bsongis-frsky commenting on things that are clearly documented (see previous post about needing better api documentation) or other issues that are just as small.  Seriously, I am not asking for a fix, I am not asking for anything other than an acknowledgment that it's being looked and if there are further debugging steps that the devs want in order to support this then someone should post this as without any type of guide like "typical debugging steps" or source code to go by it's all guess work.  

dave

**Comment by bsongis-frsky** [comment]
Sorry if I didn't answer in due time. I receive hundreds of emails everyday and I try to do my best. I have had still no time to do a test with your zip file.

**Comment by bsongis-frsky** [comment]
> I think all images for all models are loaded, not just the ones in the folder you are viewing. Do you have a lot of models? Maybe one has a large image file and delays the rest?

This is not true. Only bitmaps which need to be displayed are loaded.

**Comment by bsongis-frsky** [comment]
And bitmaps are loaded in the background. So the UI is not freezed. This is very different from OpenTX. I don't know how it is implemented in EdgeTX

**Comment by bsongis-frsky** [comment]
Test done on X20S as it is the one I use for debug everyday, with bitmaps on SD. Speed is around 1 bitmap per second.

**Comment by bsongis-frsky** [comment]
Load a bitmap with STB lib instead of libopenui seems quicker. Around 200ms saved per bitmap.

**Comment by bsongis-frsky** [comment]
Working on this the whole day. It seems that for all your bitmaps I might be able to reduce by / 5 the loading time.
I am not sure I will include this change in 1.5.10 though as it will need more testing.

**Comment by bsongis-frsky** [comment]
Hm. no. The factor is rather 10: 100ms per bitmap instead of > 1s

**Comment by fdm225** [comment]
@bsongis-frsky I do appreciate the work that you do and understand the flood of emails.  Thank you for looking at this, was a misunderstanding on my part as to what the process is and will try to have more patients in the future.  If you need a beta tester I would be happy to backup my radio and test out whatever fix you may have for this.

**Comment by Nerenye** [comment]
is that maybe a fix for x20 aswell. the load times have been bad there too. there has been a ticket a while ago two

**Comment by fdm225** [comment]
if you would like me to modify and upload the example script to this issue I would be happy to do so.

dave

**Comment by Nerenye** [comment]
@bsongis-frsky  ist it possible to implement that for x20 too? our thumbnails are vell in exess of 1sec too. regardless of format and size.

see #1703

**Comment by RealTadango** [comment]
I did some testing and i now keep my thumbnails at 400x400 and about 10k max and they load very quickly. Anything about 100k makes it noticeably slower and above 500k becomes annoyingly slow.

**Comment by Nerenye** [comment]
edit: my comment was refferenced to the issue i refferenced earlier

**Comment by fdm225** [comment]
I am not sure that this has been released yet as it has a 1.5.12 on it and the issue has not been closed.  There is a different issue that references this fix as being released in 1.5.12 so I am hoping that the performance will increase in the next build.

dave

**Comment by bsongis-frsky** [comment]
Back to this issue which is still not finished.

**Comment by bsongis-frsky** [comment]
BMP load time inside Model / Select:

Before ...

```
011148 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 1054ms
012222 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 1043ms
013315 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 1060ms
014406 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 1048ms
015501 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 1041ms
016594 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 1059ms
017684 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 1047ms
018782 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 1055ms
019853 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 1042ms
020942 loadBitmap(SD:/bitmaps/models/fw_f16.bmp) took 1058ms
```

After ...

```
015177 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 122ms
015339 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 124ms
015492 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 120ms
015660 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 129ms
015820 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 119ms
015980 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 119ms
016138 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 119ms
016298 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 121ms
016457 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 120ms
016616 loadBitmap(SD:/bitmaps/models/fw_f16.bmp) took 121ms
```

**Comment by RealTadango** [comment]
PNG's and JPG's load much faster right? (With the current versions). How do they perform with this change? Do we need to convert to BMP's?

**Comment by bsongis-frsky** [comment]
PNG load time inside Model / Select:

Before ...

```
016034 loadBitmap(SD:/bitmaps/models/a4_skyhawk.png) took 340ms
016420 loadBitmap(SD:/bitmaps/models/a_gtundra.png) took 345ms
016783 loadBitmap(SD:/bitmaps/models/a_spitfire.png) took 323ms
017168 loadBitmap(SD:/bitmaps/models/avios_mig17.png) took 341ms
017549 loadBitmap(SD:/bitmaps/models/avios_mig17.png) took 339ms
017942 loadBitmap(SD:/bitmaps/models/avios_mig17.png) took 350ms
018314 loadBitmap(SD:/bitmaps/models/a4_skyhawk.png) took 329ms
018676 loadBitmap(SD:/bitmaps/models/a_spitfire.png) took 324ms
019063 loadBitmap(SD:/bitmaps/models/a_gtundra.png) took 347ms
019400 loadBitmap(SD:/bitmaps/models/fw_f16.png) took 300ms
```

After ...

```
024031 loadBitmap(SD:/bitmaps/models/a4_skyhawk.png) took 276ms
024363 loadBitmap(SD:/bitmaps/models/a_gtundra.png) took 293ms
024678 loadBitmap(SD:/bitmaps/models/a_spitfire.png) took 276ms
025034 loadBitmap(SD:/bitmaps/models/avios_mig17.png) took 319ms
025382 loadBitmap(SD:/bitmaps/models/avios_mig17.png) took 318ms
025733 loadBitmap(SD:/bitmaps/models/avios_mig17.png) took 319ms
026049 loadBitmap(SD:/bitmaps/models/a4_skyhawk.png) took 275ms
026366 loadBitmap(SD:/bitmaps/models/a_spitfire.png) took 276ms
026698 loadBitmap(SD:/bitmaps/models/a_gtundra.png) took 294ms
027009 loadBitmap(SD:/bitmaps/models/fw_f16.png) took 273ms
```

**Comment by Nerenye** [comment]
> BMP load time inside Model / Select:
> 
> Before ...
> 
> ```
> 011148 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 1054ms
> 012222 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 1043ms
> 013315 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 1060ms
> 014406 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 1048ms
> 015501 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 1041ms
> 016594 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 1059ms
> 017684 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 1047ms
> 018782 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 1055ms
> 019853 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 1042ms
> 020942 loadBitmap(SD:/bitmaps/models/fw_f16.bmp) took 1058ms
> ```
> 
> After ...
> 
> ```
> 015177 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 122ms
> 015339 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 124ms
> 015492 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 120ms
> 015660 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 129ms
> 015820 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 119ms
> 015980 loadBitmap(SD:/bitmaps/models/avios_mig17.bmp) took 119ms
> 016138 loadBitmap(SD:/bitmaps/models/a4_skyhawk.bmp) took 119ms
> 016298 loadBitmap(SD:/bitmaps/models/a_spitfire.bmp) took 121ms
> 016457 loadBitmap(SD:/bitmaps/models/a_gtundra.bmp) took 120ms
> 016616 loadBitmap(SD:/bitmaps/models/fw_f16.bmp) took 121ms
> ```
> 

Wow thats way way faster

**Comment by bsongis-frsky** [comment]
I am trying to switch to libspng instead of stb_image for PNG 
https://libspng.org/

**Comment by Nerenye** [comment]
can we help you somehow?

**Comment by bsongis-frsky** [comment]
No luck on PNG, we will remain on stb_image library :( as libspng seems 2 times slower, unless I have missed something of course!

https://github.com/randy408/libspng/issues/169#issuecomment-2237558278

**Comment by Nerenye** [comment]
but the new lib for bitmap is coming 1.5.12?

**Comment by RealTadango** [comment]
> No luck on PNG, we will remain on stb_image library :( as libspng seems 2 times slower, unless I have missed something of course!
> 
> [randy408/libspng#169 (comment)](https://github.com/randy408/libspng/issues/169#issuecomment-2237558278)

Okay, i will switch to bmp's because they will be much faster with the update.

**Comment by bsongis-frsky** [comment]
It will be ready in the next nightlies.
The BMP format is the quickest today

**Comment by fdm225** [comment]
@bsongis-frsky I am still seeing slow load times (~1 second per picture) on 1.5.14 in the model selection screen, is there a specific resolution, size, or bits per pixel that the files should be to get the load times that you mention above?

**Comment by RealTadango** [comment]
I just got a X20RS and with 1.5.13 i noticed 2 things:
 - Models popup slower in the model selection if the image is removed from the bitmap folder
 - Bitmaps created with other programs (paint.net for example) almost never work. I have to convert them through Ethos suite, why?

**Comment by bsongis-frsky** [comment]
@fdm225 Please attach one of those pictures. Have you converted them to the right format through Ethos Suite?

@RealTadango Ethos doesn't support all BMP formats, as they are a lot. Look at your favorite program to know which parameters suit. I am not sure that paint is the best!

**Comment by RealTadango** [comment]
@bsongis-frsky Not paint... Paint.Net ;) Completely different beast :) I will try some options but have not found the right ones yet....

**Comment by fdm225** [comment]
Hi all,
so all of my bmp files are from skyracoon I did as suggested and re-encoded them with the tools in the suite and I found that using a transparent background is super slow.  By just unchecking that I am probably seeing the improvement that @bsongis-frsky mentioned earlier in this thread.  It's not fast by any means but I am now down to a 30 second (or less) load time vs 2-3 minute (I have ~30 models on one screen).

**Comment by Nerenye** [comment]
Still realy slow compared to edgetx. He said it would be 0,1s per picture

**Comment by fdm225** [comment]
[new models.zip](https://github.com/user-attachments/files/16734821/new.models.zip)
here are the modified graphics that are faster, not super fast but better since I shut off the transparent background.

**Comment by fdm225** [comment]
@bsongis-frsky is it possible for you to post up the bmp files that you used for your testing?  I would like to compare the format to what I am using to see if I have the pictures encoded correctly as (it is faster after using the suite to encode the pictures) but it's still really feel slow on the loading.

**Comment by bsongis-frsky** [comment]
I have done all tests with your bitmaps, attached above. I have just checked them again and the speed is very good, I would say less than one second per bitmap.
