### ISSUE TITLE
Feature request multiple expo dual rate on pitch HELI

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#405]
Hello, i like to use dual rate and expo on the pitch on my heli. In the dedicated mixer "pitch HELI" there is no option to do it simply like in aileron mixer.
I would be useful to have the possibilty to add multiple curves and weights.

Thanks.

**Comment by Hobby4life** [comment]
You should use flight modes, it is designed for that purpose.
Every flight mode, a diffrerent set of curves and/or weights.
Is personally dont see any point to add expo and weight to curves.

In curves you create the expo and the weight.

**Comment by skyfly74** [comment]
I dont understand how you can add expo and weight in the mixer HELI PITCH with flight mode?How do you do to add in the same mixer an expo curve (ok) and a weight curves, i don't see where is the weight curves?
 And personnaly i use flight mode for other purpose , idlle up 1,2,3 or for differents flybarless setings And in each idlle or settings i want too have different expo and weight... so as you can unferstand it is impossible to do it with only flight mode... by definition you can't have 2 flight mode active in the same time so i dont really agree that flight mode are mades for that purpose...
I think it is really necessery to have this feature includes in the mixer heli pitch.
I agree it is always possible to do that with an other solution, i will do it now. But ethos is made for be simple and not to have to create complicated solution, in the aileron and elevator mixer it is perfect and simple to add multiple rate and expo avaibale in every flight mode.

May be i miss something with your use of flight modes... If you can detailed how you manage to have that with flight modes: 3 settings of gyro, 3 settings of idlle up, 3 settings of dual rate/expo each setting must be associated to each others so 3x3x3=27 configuration differents...

**Comment by Hobby4life** [comment]
You use Flight mode as Normal, idle1 , 2 ,3 etc. use Switch E for it for example.

In a mixer you tell it when that mixer is active in X flightmode.
And in a mixer you add curves to to conditions. use switch A to switch between these curves.

Curves = Weight + offset, all in one.. thats what a curve is. you draw weight and offset in a Curve.

I use flightmode the same way as you.. to select bankswitching, throttle and pitch curves.. but in the mixer itself you can define sub curves.

**Comment by skyfly74** [comment]
Thanks for reply. But you have not misunderstand what i say... or you confuse offset with EXPO (exponential)
I dont want an offset of the pitch curve. I want to be able to add EXPONENTIAL if i need on the pitch like i do on other channel. And that is impossible with a simple solution on mixer.... Try to create a curve expo and then another one with weight you will see they don't addi eachother.
For the weight, yes you can simply add the weight by adding multiple curves on a switch. But it is duplicate and can be a source of mistake as you also have the weight on the channel exit.... I think it will really more simple to have the same simple option like in aileron and elevator.
Actually the simple way to have this is to use the mixage "manche des gazs" and rename it for the pitch and here you can add EXPO and weights on switchs

**Comment by STC148** [comment]
1. add curve
![1](https://user-images.githubusercontent.com/85410070/120900407-ea833b00-c634-11eb-9d31-d1220d68e5c0.jpg)
2. add new curve (not EXPO)
![2](https://user-images.githubusercontent.com/85410070/120900467-4221a680-c635-11eb-9104-e6a51fbd18c4.jpg)
3. choose expo
![3](https://user-images.githubusercontent.com/85410070/120900530-6d0bfa80-c635-11eb-87e1-ad4d98a354ed.jpg)
4. here you can select expo and weight
![4](https://user-images.githubusercontent.com/85410070/120900557-8f9e1380-c635-11eb-9f13-bb57a1d46d71.jpg)

**Comment by skyfly74** [comment]
Perfect! that is what i was looking at! is it a recent change? i have look at this and don't see it in the editing curve... :(
I apologize. So it is not really necessery to have the same option like in aileron and elevator... It will be just usefull to have the same presentation!
Thanks for showing me that i just have under my eyes! I closed the issue

**Comment by Hobby4life** [comment]
Ahhh ok, I now understand :-)
