### ISSUE TITLE
Lua Add-On - Display Image in dialog box with close button / QR code

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4055]
So while thinking about how to add help to rotorflight it dawned on me that a really easy option exists.

QRcode.

It would be really handy to either generate them on the fly - to put in a popup dialog bog (with a web address in them)

Or..

allow an image to be added to a dislog box.

Or...

A custom dialog designed specifically for this purpose

Dirty image for reference attached...

![advdialog](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4599545/3c1b2408-bb0d-49cc-9837-ec8157251f3b)

**Comment by bsongis-frsky** [comment]
The new syntax for `form.openDialog()` now allows a `paint` handler which can be used to display a QR code, or even an animation.

**Comment by robthomson** [comment]
Great work as always.  Thank you
