### ISSUE TITLE
Lua / "require" functionality fails on real hardware

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4058]
Testing on Ethis 1.5.7, x20s.

Using `require` statements, and having `some_module.lua` in same folder as `main.lua`, `require` works perfectly when testing in simulator

```
require "some_module"
```

However, on real hardware the script (widget) doesn't show up. Replacing `require "some_module"` with `dofile("some_module")` makes it work. But of course `require` is much preferable.

BTW. I can't debug what is going on, because connecting serial for debugging needs radio running, but then scripts were already loaded. Is there a way to see the debug output while radio is booting up?

**Comment by bsongis-frsky** [comment]
Fixed in the next nightlies
