### ISSUE TITLE
Feature request: add info to screen when charging

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#406]
When charging, the power button becomes green, but it never changes color when fully charged. It would be great to add to the screen a way to see the progression of the charging process.

**Comment by MIKE-DAILEY** [comment]
The LED should go out when charged.  Are you using a 2amp USB power source?  Also may need to let the battery discharge down to below 7.5v.

**Comment by jreis1** [comment]
> The LED should go out when charged. Are you using a 2amp USB power source? Also may need to let the battery discharge down to below 7.5v.

I'm using a 3.1Amp phone charger, but I've noticed that my battery does not charge more than 7.9V/8.0V, so the the LED is always green. 

Just another quick note, the battery voltage is flickering very fast, not sure if this is already part of another ticket.

**Comment by MIKE-DAILEY** [comment]
The battery voltage can flicker some when it is in-between a voltage display. I think that was improved some with version 1.0.5. and newer firmware.  You might want to check the battery voltage directly at the battery plug and then on the battery screen you can adjust the displayed voltage by clicking on the Main Voltage and adjust its voltage.   Once you do that let the battery voltage drop down to near 7v and then try the charge again.  It can take a few hours to charge and my wall-wart near the end of the charge cycle can feel cool but still charging and the LED goes out.  ETHOS does not control the charging.

**Comment by skyfly74** [comment]
Yes make a voltage calibration at the end of the charge and let time running. The first time i have charge the X20 i was thinking it doesn't work... led never end! I was attempting a charge near 2 hours maximum with a 2>éamp charger and a 4000 mah lipo. But it is not the case, charging is very long, more than 3-4 hours for me. I think the charger integrated in the X20 is very slow to finish the balancing of the cell and secure the charging process.

**Comment by hrenz** [comment]
The usb power supply should deliver a real 2.5A.
The USB charging current is max 1.8A

**Comment by jreis1** [comment]
> Yes make a voltage calibration at the end of the charge and let time running. The first time i have charge the X20 i was thinking it doesn't work... led never end! I was attempting a charge near 2 hours maximum with a 2>éamp charger and a 4000 mah lipo. But it is not the case, charging is very long, more than 3-4 hours for me. I think the charger integrated in the X20 is very slow to finish the balancing of the cell and secure the charging process.

confirmed. I've to charge for +2h to charge the last 0.3V of my battery, so I can confirm it is very slow to finish the balancing the cells.  I'll mod my battery to charge it using a standard lipo charger.

**Comment by MrD-RC** [comment]
Just a suggestion, but could the LED not change as the charge progresses? So for example main charge below x volts it pulses green slowly, above x volts it pulses quicker, and during the final balance charge is it on constantly? The way there is some indication of progress.

**Comment by Hobby4life** [comment]
I almost 100% sure. Charging circuit is harfware fixed and can not be controlled by software at all. It is what it is.

**Comment by bsongis-frsky** [comment]
Right, nothing can be done in Ethos
