### ISSUE TITLE
allow lua to define a sensor

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4060]
Please can we have a function to allow lua to do the following:

s = system.getSource({category = CATEGORY_TELEMETRY_SENSOR, appId = 0x5450})

if s == nil then
    system.createSource({category = CATEGORY_TELEMETRY_SENSOR, appId = 0x5450},name,params)
end

This would be handy when releasing lua scripts that rely on DIY sensor id numbers.

**Comment by bsongis-frsky** [comment]
```lua
model.createSensor(...)
```
