### ISSUE TITLE
X20Pro AW Vibration while charging 

### ISSUE THREAD

**Issue by JJames1513** [FrSkyRC/ETHOS-Feedback-Community#4061]
New X20Pro AW . Firmware 1.5.8  , (also happened on 1.5.1  firmware that was on it when shipped to me ) 
when charger is plugged into the TX , there is a vibration that can be heard and felt. 
Only when charging.  tried multiple chargers and cords. 

not sure if tis is a warranty issue or a coding issue as it ONLY happens when charging.  it can be plugged in for updates or any other reason and its fine.

**Comment by bsongis-frsky** [comment]
If the Tx is OFF, then Ethos doesn't run!

**Comment by bsongis-frsky** [comment]
Would you contact after sales?
