### ISSUE TITLE
Deleting current model folder causes Ethos current stable 1.5.6 to panic

### ISSUE THREAD

**Issue by JoelFoner** [FrSkyRC/ETHOS-Feedback-Community#4062]
I accidentally created a model folder and decided to delete it, and after deleting it, now my radio always boots up immediately to Emergency Mode. It briefly flashes what looks like a model read error dialog, but before I can do anything it jumps to Emergency Mode.  As a way of getting things to boot, I used Ethos Suite Repair Tool to Restore Factory Settings.

**Comment by bsongis-frsky** [comment]
Rather 1.5.8? This problem has been fixed and it is ready for 1.5.9
