### ISSUE TITLE
Proposal to add a RANGE for differential in caned mixer "aileron"

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#4069]
(Note: if you want to go straight to the point just read the title or go directly to the last line.)

There are some discussion lately on the increasing complexity of ETHOS.
Eventhough I accomodated myself well to these changes, I must admit I will not make use of all the new functionnalities recently proposed.
I am flying DLG, 8 aileron servos glider with turbine, 1/3 aerobatic.
I like my models to fly reasonably "straight", but in my (very personal) view the pilot is driving a non perfect plane with his brain, inputing corrections whenever it is required.
I also have the priviledge to pilot a real size 3axis microlight, there is no electronic on board to add any correction on the rudder during a turn.
I am far from beiing a geek but I am often helpful to others on the field and so far never required any help to set up any of my planes.
I also fully respect pilots who have the patience to develop sophisticated set up for fine tuning their planes. It is also a part of this hobby, just not my preference.

As a long time high end Futaba Tx user, I am really amazed by the level achieved by ETHOS, so I already bought 2 Tx and am fully happy with these.

Coming back to the current debate about complexity: any system can be extremely complex, but its usage should be as user friendly as possible. A good example for me is the Iphone: nobody is using all its capabilities but everybody can use it, and keep learning new features on the go.
A system can satisfy an expert and also an "average Joe".

The recipe is easy in the words but so hard to achieve: aside from a technicaly achieved product, it is named "usability" and "ergonomy".

ETHOS is a fantastic system, its usability is already great, but this a never ending fight.
I know by my professional career, how dificult it is for an expert to fit in the suit of an average Joe: everything is so easy to understand for the expert he cannot understand others cannot get it.
Everyone is the average Joe of somebody.

Now I will take the challenge to ask for an enhancement which I know how to solve with a free mixer or a VARS. (maybe I am so Joe I did not find the easy way?)

One of the basic feature with a 2 ailerons model is to adjust the ailerons differential.
The canned mixer does this well offering to adjust it by a source, (or with a trim or with a 3 pos. switch, or....)
The most common Joe way is to adjust it via an analog source.
Currently, you get the full range of the pot -100 to 100 which is not reasonable.
OK you can use a VAR. easy does it? maybe not so obvious for some of us.
Again you are right there a great fully updated documentation available Thanks so much Lothar (fantastic....but tell me who is really reading it? for sure not the average Joe.

Finally my point: would it possible to add next to the source selection a field to select a range?

I promiss I want do this again.
Thanks again to developpers your are rocking!

**Comment by strgaltdel** [comment]
imho:
variant 1)
as mentioned, you can use a var, & configure its range,
its easy to do, you only have to learn it once in your live, no ethos enhancements needed, learned "var knowledge" can be used in a lot of more use cases, we have to wait for #3821 to get all features.

variant 2)
add a mixer, input pot,  configured with weight&offset , so that it fullfill your "range-needs", use it as diff value, possible since the first days of ethos.

variant 3)
as proposed, add additional fields, which will be used in only a small number of use cases, these users wont deal with vars in the future and so they will step into a next enhancemence request...


its just my opininion, i may be wrong, but the proposal seems to counterfight an "ease of use" paradigma to me, because it would add additional fields in a gui without adding addinitial features, so at the end it will be more complex....
imho, it does not correspond to the  "kiss" principle

regards

**Comment by Eagleowl1** [comment]
As previously mentioned, I have no issue in using Vars or mixer.
For this one, I just tried to fit my feet in average Joe shoes.
I am not an expert as you are yourself but have some understanding in “programming” a R/C model. As you understood already the proposal is not meant for my proper usage

Ergonomically speaking, I just don’t understand how the proposal: “adding a field” could disturb anyone and not just make it easier for most of us as this is a basic adjustment setting for any plane using 2 ailerons servos.

But this is just a matter of opinion and I highly respect yours.
I will not elaborate any further as I have been already much too long on this topic.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
