### ISSUE TITLE
x 12s os 1.0.7  sugestion mixer

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#407]
Hello mr Songis, my radio is in ADGP mode 1 and when I create a simple model, in mixer the result is .... aileron 1-2, rudder 3, gaz 4, elevator 5 .... Why this order? This forces us to correct this order for each model. It is long! it would be much more logical to find .... aileron 1, elevator 2, throttle 3, rudder 4, and in 5 aileron 2!
Too bad you left out the choice of channel in the design of the model (optx) it was quick and easy. yes we can change in mixer but for us it's a bit late .....
Well ..... we'll have to do well with ... unless ..... we can dream ...
If you could already change the order in (mixer)? we would already be satisfied.
Thank you for your attention and for your work in optx and ethos. Very good.

**Comment by MIKE-DAILEY** [comment]
Duplicate #286
