### ISSUE TITLE
Displaying markdown documents

### ISSUE THREAD

**Issue by m-rik-prog** [FrSkyRC/ETHOS-Feedback-Community#4073]
I take up a report I made in issue #4029 but wrote when issue #4029 had already been closed and was probably not taken into account for that reason.
There seems to be a very low limit of markdown lines (#, **, etc.) beyond which the text is no longer displayed. You probably need to increase the size of a buffer.
I attach the .md file whose display stops at line 32.

Still regarding the same issue #4029, but when displaying normal text files (.txt) instead, empty lines are now also displayed, unlike before. The problem is that now the line spacing (distance between one line of text and the next) has increased considerably and very little text is displayed (the same as in issue #4029 can be used as an example .txt file).
[Integrations_Help.md](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15436919/Integrations_Help.md)

**Comment by bsongis-frsky** [comment]
In 1.5.10 the limit for MD files is modified to 16K instead of 1K

**Comment by m-rik-prog** [comment]
Thanks!

 

Da: Bertrand Songis @ FrSky ***@***.***> 
Inviato: martedì 2 luglio 2024 14:32
A: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: m-rik-prog ***@***.***>; Author ***@***.***>
Oggetto: Re: [FrSkyRC/ETHOS-Feedback-Community] Displaying markdown documents (Issue #4073)

 

In 1.5.10 the limit for MD files is modified to 16K instead of 1K

**Comment by m-rik-prog** [comment]
I saw that the new version was released today, with which I updated the Tandem transmitters.
Now of the markdown file I had sent you you can see many more lines, but the display stops at the beginning of paragraph 8.

Paragraphs 8, 9 and 10 are not displayed.
I thought you would try the .md file I had sent you.
Or had you tried it but more than 16K cannot be allocated because that is the maximum memory limit available?

If so, you would at least have to fix the display of the .TXT text files, which at first did not display the blank separator lines but now display blank lines twice as tall as a single line.

[Integrations_Help.md](https://github.com/user-attachments/files/16116757/Integrations_Help.md)
[Integrations_Help.txt](https://github.com/user-attachments/files/16116758/Integrations_Help.txt)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/1c271972-56df-4485-bcf0-df3bc58ee1ce)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/6d3d4183-b272-49b2-95b7-37bb6de30bc2)

**Comment by m-rik-prog** [comment]
Thanks!
