### ISSUE TITLE
X20HD HDZero Freestyle V2

### ISSUE THREAD

**Issue by aepkolol** [FrSkyRC/ETHOS-Feedback-Community#4074]
Instructions for the X20HD and HDzero are extremely lacking. 

I bought this controller with the VTX assuming everything would work flawlessly, but clearly not the case. 

First issue was with the Freestyle V2. The Runcam 90 camera doesn't work with the X20HD. There is zero documentation on this except a random comment I found on google that linked to a comment in this repo. Everywhere online just says this controller supports ALL HDZero VTX's. Nothing about the cameras that come stock with them apparently. 

So another hundred dollars and a week wait to fly. Got the camera, and now I have a video feed. However the OSD will not work no matter what I do. The HDZero manual says this is a firmware mismatch. So I go to update the VTX firmware. Apparently you do this from the goggles, but I'm using a controller. Must be a way to update the VTX with the controller then, right? Nope. I need a special dongle that wasn't included with the $600 controller. 

So I order it. Another $30 and a week wait. 

The firmware is updated on the VTX, however the OSD STILL doesn't work. 

I have no clue what firmware the VRX inside the controller is, or if that's even the issue. No idea if I can update the firmware, or its built into ETHOS. No clue if the freestyle V2 is even supported. There is little to no documentation on this. I'm $1000 deep into a controller and VTX that is supposed to work together, and I'm no closer to flying after weeks of ordering new hardware to get them working together. 

Can someone shed some light onto this that I am missing? Or is this just abandonware already? 

X20HD
HDZero Freestyle V2
Ardupilot latest

**Comment by kakashi2018** [comment]
Ligen a dev from hdzero told me that he had given an updated firmware for x20hd radio for the vtx part and now frsky devs are testing it. Not sure what is taking so long but @bsongis told it will be made available soon to the users. And for the update, it will have support for 90hz camera and latest hd osd support( basically like the new hdzero monotor)

**Comment by ecarlesi** [comment]
I have the same hardware and the same problem :(

**Comment by aepkolol** [comment]
According to the HDZero discord:

> The following has been completed:
> lowband
> narrow band
> nano90 camera
> hd osd
> Now Frsky needs to modify some things to suit.

That was back in April. Yet my X20HD sits useless because I can't use the HDZero hardware with it still.

**Comment by kakashi2018** [comment]
Same feeling here. Hope they release it this year before hdzero 2.0
releases.😀

**Comment by gy1010496170** [comment]
Only the new X20 firmware is compatible with the Nano 90, you need to contact Frsky support and update it. For OSD, it is similar since the VTX firmware version is new.

**Comment by kakashi2018** [comment]
When you say new x20 firmware, do you mean the vrx related firmware or the
one that is ethos related? And did they tell you how to update the vrx
firmware?

**Comment by aepkolol** [comment]
I know the VTX firmware, I had to buy an HDZero USB dongle to be able to flash. Since the normal method is to attach the VTX to the goggles via the firmware cable, but the X20HD doesn't have this output. 

It seems like the VRX side that is built into the controller can only be updated via ethOS, but the documentation is super lacking. I don't see anything in the suite for flashing it.

**Comment by bsongis** [comment]
Would you have a link to their Discord? I will like to follow it

**Comment by kakashi2018** [comment]
https://discord.gg/3stu5Yes this is for hdzero and there is vrx-x20-frsky
channel about this

**Comment by bsongis-frsky** [comment]
This issue is fixed now!
