### ISSUE TITLE
Test Firmware HF Modul TW-ISRM_1.0.7_Beta on Kavan-V20

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4076]
Après installation du TW-ISRM_1.0.7_Beta, le capteur VFR2.4G n'indique plus de valeur: VFR2.4G "---"(voir photo).
Il faut alors refaire un scan des capteurs. VFR2.4G est alors affiché 2 fois: VFR2.4G 100%  et VFR2.4G "---"
Après avoir effacé celui qui n'indique pas de valeur, il faut alors reconfigurer les Widgets.
Il faut répéter cette opération pour chaque modèle!
![screenshot-2024-05-25-31071](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165813792/42d61906-095f-4e67-90ac-92b3a951df1d)
![screenshot-2024-05-25-35204](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165813792/cf2bb8f8-4437-47c9-8df3-968240a43fbd)

**Comment by bsongis-frsky** [comment]
Quel sont les IDs du capteur avant / après ?

**Comment by philippe-warnotte** [comment]
Avant (RSSi2.4G) id: 18F101
Après(Altitude)   id: 130100
Après un nouveau scan des capteurs (sans tout effacer) VFR2.4G id: 1AF010 change de place:
Avant ADC2: id  1AF103
Après Roulis: id  1A0730
Je n'ai pas noté l'id de VFR2.4G avant l'update de l'ISRM et j'ai malheureusement effacé la ligne dont la valeur ne s'affichait plus.
