### ISSUE TITLE
Very low" welcome sound" when you have enabled "select model at power on"

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#4077]
If you select "model at power on " turn on, when you turn  the radio back on the wellcome voice is hear very very low . My radio is X20 pro AW at 1.5.9 FLEX

**Comment by jasalca** [comment]
The problem is still there. I know there are other more important problems but this one should not be forgotten

**Comment by jasalca** [comment]
I see that in the end this problem is solved in quetion number #4880

**Comment by bsongis-frsky** [comment]
Indeed, fixed in #4880
