### ISSUE TITLE
flickering min and max values with analog filter in global or off mode

### ISSUE THREAD

**Issue by FBarrao** [FrSkyRC/ETHOS-Feedback-Community#4078]
X20S 
Firmware 1.5.9 EU
In output screen min and max values flickers with Analog filter on global or off position. Happends when subtrim is near 0
Check video. 
https://youtu.be/-EISQoO8IoM

**Comment by FBarrao** [comment]
Sorry, this is the video.
https://youtu.be/-EISQoO8IoM

**Comment by mawzthefinn** [comment]
That's a bit of ADC drift. It mostly happens around zero, but can happen at min/max too. Analog filters on will fix it (NB if happening when ANalog filters are set to global, your global setting is likely Off)
