### ISSUE TITLE
Full mixer library no available when creating models via Other.

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#4080]
A suggestion for improvement
It would be helpful if the full Mixer library was available when creating models via Other.

Thanks
![bild](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/930b24d2-6445-472a-bad6-dce48aaa4405)
![bild1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/4bdc93e8-d166-4166-a0f4-07f00d8620a8)

**Comment by mawzthefinn** [comment]
All the other mixes depend on functions which don't exist in Other, it exists for uses that do pre-provision specific airplane/sailplane/heli functions. 

If you want the function-based mixers, use a model that has those functions.

**Comment by loetefix** [comment]
I think it is better to have access to all mixers in OTHER model creation.

**Comment by mawzthefinn** [comment]
> I think it is better to have access to all mixers in OTHER model creation.

But the functions those mixers depend on don't exist n that model type. 'Other' lacks the surface functions entirely.

If the mixers were there, they would all be broken .

**Comment by bsongis-frsky** [comment]
As explained by @mawzthefinn all mixes would be broken, as almost all infos are missing
