### ISSUE TITLE
ETHOS Suite 1.5.4 not showing the availability of an update to Suite.

### ISSUE THREAD

**Issue by GWCTas** [FrSkyRC/ETHOS-Feedback-Community#4082]
I was using Ethos Suite 1.5.4 and I posted some discrepancies in the ETHOS manual relating to Image Manager to RCGroups. Lothar replied advising that the 1.5.4 changes were rolled back in later updates. I had checked for Updates to ETHOS Suite but none appeared, and even when selecting "Suite Settings>Check for Update", no notice of a new version appeared, despite there being 1.5.5 and 1.5.6 available. Lothar then suggested I post in Github.

**Comment by Nicholas-Luoyi** [comment]
Would you please manually download the latest Suite? We don't mantaince the outdated version

**Comment by mawzthefinn** [comment]
This issue was addressed in Suite 1.5.5
