### ISSUE TITLE
Pass-through telemetry hanging after startup

### ISSUE THREAD

**Issue by mikedkelly** [FrSkyRC/ETHOS-Feedback-Community#4084]
I am using the Yaapu Lua script on my X20S. When I initialize my flight controller, I see the first 2 or 3 status messages and then it halts, followed by an audio callout of "sensor lost." I can see on my PC that the flight controller continues to operate and inputs from my X20S are still executed on the FC. This started in Ethos 1.5.8 and is still present in 1.5.9. I am seeing this for my Frsky receivers (900Mhz and 2.4GHz) broadcasting telemetry to the internal RF module. I have an ELRS receiver broadcasting telemetry to an external module and I do not have the issue.

**Comment by robthomson** [comment]
Can you flag this up with Yapuu? Chances are he is already aware and has a code fix.

1.5.8 had allot of lua improvements for speed - so likely a small script change is needed.

**Comment by mikedkelly** [comment]
I will pass this along. It would be better if in the future, that lua api changes are versioned so that 3rd-party scripts do not break with new releases of Ethos. Yaapu already has versions for pre- and post- 1.5. He would now need to maintain a 3rd branch for 1.5.8 and above.

**Comment by mikedkelly** [comment]
This may be due to an upgrade path issue. After factory resets and wipes of my radio and flight controller, I have this working again.
