### ISSUE TITLE
Arrangement of "LOGS" and "screenshot" 

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4087]
Arrangement of "LOGS" and "screenshot" files: the most recent files should be at the top of the stack and not below.

**Comment by npirkes** [comment]
#4045

**Comment by pmullen503** [comment]
Yes. With the viewer now in Ethos 1.5.x I find I view logs at the field very often. The current way to organize files makes it hard to find the log you want to view. Putting most recent file at the top would be a big help.

**Comment by philippe-warnotte** [comment]
In the meantime, you can turn the multifunction knob counterclockwise and start viewing your most recent files.
