### ISSUE TITLE
twin x lite expresslrs

### ISSUE THREAD

**Issue by filipir** [FrSkyRC/ETHOS-Feedback-Community#4088]
Hello everyone. I have frsky twin x lite, I installed the Lua for expresslrs I loaded via wi fi and now it is binded with the receiver, the problem is that the gimbals and switches do not work.

Radio updated to the latest version on ethos
Phil

**Comment by mawzthefinn** [comment]
Have you programmed a model? Are your mixers setup? What shows up in the Outputs screen?

**Comment by filipir** [comment]
I always use the radio even with the crossfire module without any problem

**Comment by yak55** [comment]
This is the typical behavior when the Model ID is different between the sender and receiver.

Or, use is activated on the transmitter and the receiver is forgotten - or the other way around.

Telemetry still works, but control doesn't.

Greetings Eugen

**Comment by filipir** [comment]
How can I fix this?

**Comment by yak55** [comment]
I have attached 3 photos.
Photo 1 transmitter ID

![IMG_4836](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/31aa7f13-5b95-447a-a41c-21fb3c8fc0a0)

Photo 2 +3
Setup receiver on the PC
Question 1: ID used?
Question 2: which ID?

![Match 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/2952a29f-a601-4e52-8d20-f8ec3dccc257)
![Match 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/a6aa1cb8-afdf-4b5e-b506-bd10007e3f7d)


Greetings Eugen
