### ISSUE TITLE
Device Config SxR / SRx / SR6 / SR8 - Option for Failsave action / Offset not stored

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#409]
In LUA Script 2.0.2 "Added option to support setting whether or not gyro is enabled after failsafe."
this is currently not available in device config SxR.
Maybe if sometimes LUA in  ETHOS is possible the Device Config is no more needed?
Another little fail in the device config for SRx (or isn't it for SRx and just for SxR made?) If I want to use small amount of Offset for exampla Hover it will not be stored - it allways jump back to the last value. I want to set -2 or -3 for Ruder Hover Offset and it's not possible.

**Comment by Fpilih** [comment]
Hello. I found 2 of the 6 gyro calibration steps for the SR6 receiver  fail. The labeling is incorrect. Reversed the recommended procedures and was able to calibrate the gyro.

thanks.

**Comment by mawzthefinn** [comment]
Gyro enabled after failsafe can be set from Receiver Failsafe, set the desired channel position in failsafe to trigger gyro on/off/self-level

The small offset issue should also be fixed in current firmware. Please confirm

**Comment by mawzthefinn** [comment]
Confirmed, the small offset issue was an RF bug and fixed in TD-ISRM 2.2.2 and later.

Closing this off as completed
