### ISSUE TITLE
FlySky protocol expansion.

### ISSUE THREAD

**Issue by Bleroodes** [FrSkyRC/ETHOS-Feedback-Community#4090]
Hello. The RF system - Multimodule does not include FlySky AFHDS3 and FlySky ANT protocol. Will there be a solution to this? Thanks.

**Comment by mawzthefinn** [comment]
Neither protocol is supported by the MPM project at this time. 

AFHDS 3 is not possible as it depends on hardware not present in an MPM, ANT has not been reverse engineered, although it is being evaluated.

**Comment by Bleroodes** [comment]
> Neither protocol is supported by the MPM project at this time.
> 
> AFHDS 3 is not possible as it depends on hardware not present in an MPM, ANT has not been reverse engineered, although it is being evaluated.

Too bad AFHDS 3 can't be added. Is there any hope for ANT?
