### ISSUE TITLE
ExpressLRS - PWM RX, Channel mapping not possible

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#4092]
X18SE, Ethos 1.5.7, ExpressLRS 3.4.1

With EdgeTX 2.9.10, the channel mapping of ELRS PWM receivers can be changed via LUA script:

![screen-2024-05-28-095853](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/31627548/03f11d00-9480-4038-b59f-d840f34c75c0)

Ethos does not offer this option:

![screenshot-2024-05-28-35317](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/31627548/41e58bd9-ce21-4eff-836a-bb3b02da8e7d)

**Comment by bsongis-frsky** [comment]
It's strange, is it working in the same conditions? I see no Output Mapping in the first screenshot, and no Output Ch in the second screenshot

**Comment by mawzthefinn** [comment]
> It's strange, is it working in the same conditions? I see no Output Mapping in the first screenshot, and no Output Ch in the second screenshot

I can confirm it's real. I tested with the same module/receiver on my X9 Lite S and my X20 Pro and see exactly the same behaviour. It's not a show stopper since you can do this from WebUI too, but it would be an even better experience to get full setup functionality in ETHOS like in EdgeTX. 

Note I tested with 3.3.0/3.3.2, it's not related to whatever is giving the other weirdness with ELRS 3.4.x in #4010

**Comment by Target0815** [comment]
Bertrand means something else ... In the Web GUI, you can assign **PWM output** 8 to input channel 1, for example. This is also not possible with EdgeTX.

My screenshots show that with EdgeTX you can assign input channel 1 to output **channel** 8. However, this is not possible with Ethos because the functionality is not included in the LUA.

**Comment by mawzthefinn** [comment]
> Bertrand means something else ... In the Web GUI, you can assign **PWM output** 8 to input channel 1, for example. This is also not possible with EdgeTX.
> 
> My screenshots show that with EdgeTX you can assign input channel 1 to output **channel** 8. However, this is not possible with Ethos because the functionality is not included in the LUA.



> Bertrand means something else ... In the Web GUI, you can assign **PWM output** 8 to input channel 1, for example. This is also not possible with EdgeTX.
> 
> My screenshots show that with EdgeTX you can assign input channel 1 to output **channel** 8. However, this is not possible with Ethos because the functionality is not included in the LUA.

I'm pretty sure it's exactly the same functionality in both the WebUI and EdgeTX Lua , just poorly worded in the Lua.

ELRS does not currently have the ability to remap an input channel to another channel (this functionality has been asked for to sidestep some issues with Ch5 and SBus for fixed wing stabs where FM is sometimes hardcoded to ch5). 

This is actually just programming each PWM output to its RF channel, PWM refresh and inversion. The WebUI is simply better worded.

**Comment by Freshprinc84** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/discussions/4107

**Comment by bsongis-frsky** [comment]
@Target0815 I just want to understand why it is different in EdgeTX and Ethos. Those menus come from the ELRS device (this is why they are not translateable). So they should be exactly the same! In your screenshots, everything looks very different. Do I miss something?
