### ISSUE TITLE
TW SR8 receiver, channel rate does not go beyond 100%.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4093]
TW SR8 receiver, les canaux ne sont pas réglables au delà de 100% !

**Comment by npirkes** [comment]
After changing the rate beyond 100%, did you active the self check of the receiver so it could learn the new end points?

**Comment by philippe-warnotte** [comment]
Thank you for this information.
I had forgotten this important point.
You can close.
