### ISSUE TITLE
1.5.10 Nightly Keyboard Toogle Slider deactivation improve

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4094]
Hello Bertrand,
I have just tested the 1.5.10 Nightly.
The improved keyboard for numbers is great.

But I noticed that the button Standard does not deactivate the activated toggle slider!

You can only deactivate it by pressing Toggle Slider again.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
If you prefer the Slider, perhaps it's better if you keep it in the state before?

**Comment by yak55** [comment]
Hello Bertrand, I described that badly.

Tested on the simulator and the X20S

I choose the slider.
I use the slider.

I want to deactivate the slider again.
I press the Standard button.
This does NOT allow the slider to be deselected

Only when I press the Slider button again do I have the standard display again.

What is the function of the Standard button?

Greetings Eugen

**Comment by robthomson** [comment]
I think what you mean is:

- if slider is active, then text should read 'number mode' or 'turn off slider'
- if slider is not active, then text should read 'activate slider'

**Comment by yak55** [comment]
No, that's not what I mean.
There is a button called Standard.
It must have some kind of function.
For me, the following is simply logical:

The menu always starts in toggle mode - that is standard.
Now I activate the slider via the toggle button.

Now I want to go back to number mode, the default setting.

For me it was illogical that I should press the toggle button again to activate the standard number mode.

I would always want to do this using the standard button!

What is the Standard button for if it doesn't switch to the standard number mode?


Translated with DeepL.com (free version)
