### ISSUE TITLE
Play text function incorrect behaviour

### ISSUE THREAD

**Issue by pandjarov** [FrSkyRC/ETHOS-Feedback-Community#4095]
I have illustrated this in a video:

https://youtu.be/T0XTgt3W3Fo?si=f41VAOYFwBUeISNX

Basically if you switch fast a 3pos switch from pos1 to pos3 and you have 3 special play text functions assigned to switch states, it reads the second one and not the last function.

**Comment by T16-Pilot** [comment]
Hi, try this:

Go in to "Settings" then "Hardware, then "Switches settings" 

Then adjust "Switch middle detect delay" to 80ms.

Fore some reason it is set to zero by default in 1.5.X...

Hope it helps.

Best regards
Simon

**Comment by pandjarov** [comment]
Thanks! This solved the issue :)
