### ISSUE TITLE
1.5.9 - X20S Timers edge in the reset field is behaving inconsistently

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#4098]
My primary flight timer runs off of a logic switch. True timer runs/False timer stops. I use the same logic switch to reset this timer via the edge feature in the reset field. This does not consistently reset the timer when the timer starts. Sometimes it does some times it does not. there is no pattern I can discern, It may take a few (3-4) flips of the LS to get the timer to reset. It may work a couple (2-3).

I'd like this to work consistently, again. I use it on every model (and I hope a lot of other people do too).

**Comment by bsongis-frsky** [comment]
It will be fixed in the next nightlies

**Comment by spoke2570** [comment]
Works! Thank you!
