### ISSUE TITLE
Error layout selection - order shifted 1.5.10

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4102]
Desired layout: Image 1

![Layout 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/f7cb902c-e0e6-4504-b6f6-8c052e34df37)

Result after selection: Picture 2

![Layout 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/9fc64327-0a74-4515-82b0-86275aa3511b)

tested: 1.5.10 X20S and Simulator X20S

Greetings Eugen

**Comment by bsongis-frsky** [comment]
You are right. Thanks!
