### ISSUE TITLE
Feature request - Possibility to make use of the last used slider/pot position as a transmitter startup check

### ISSUE THREAD

**Issue by dehigama** [FrSkyRC/ETHOS-Feedback-Community#4104]
Possibility to make use of the last used slider/pot position as a Transmitter startup check. 

For example I have a slider to control a gain or some flight parameter during the flight, I adjust it and find the right value, I would like to save this value as the check value for the next time I fly the model.  Which means that for what every reason the slider moved during transport I will be getting the warning to move It back to the position I last set. Right now you can set a value >, < and ~.

**Comment by azaz44** [comment]
I think you have 'Load all pot positions' button for that. Do you miss this function for a single pot, or what do you miss?

**Comment by dehigama** [comment]
Would be super for all pots and sliders, yes 'Load all pot positions' is indeed what im using right now but the value is fixed in this case. of course I can go back to the checklist and click it again after every flight, but  Im sure I recall that we had this feature in OTX.

**Comment by azaz44** [comment]
Ah, so you're probably looking for a special function, to capture a pot value to the check.

**Comment by Richrfl** [comment]
I like the idea. the same way that trimmers are stored at power off, it should be nice to have the pots stored for the check-up. When you have several planes and you use the pots for Gyro gain for example, you have to remember to store pots before powering off, and that is a step most people will forget to do.
