### ISSUE TITLE
TD SR12 stabilizing too many channels

### ISSUE THREAD

**Issue by toganalper** [FrSkyRC/ETHOS-Feedback-Community#4105]
I am using the latest version of the ethos 1.5.8, latest of td-sr12 and the xrm. I programmed the basic stabilization. did the self check all channesl are working perfectly fine but with  little extra. Eventhough in my model setup I picked 1 elevator and 1 rudder. in the stab menu there is still ch6 mode, and I have to pick either elev 2 or aux2. I do not want to pick either. Since all my pmw channesl are full on my TD sr 12 flying a Corsair, I can not let any pins empty. So in stab mode it keeps moving either one of my four flaps based on my selection of elev 2 or aux 2 since they are connected to pin 6 and 8 consequetively. Is there a way to turn of channel 6 mode. The only solution I come up with is to tweak the sustem by assining the kill switch to that channel, which will not change with small adjustments made by the stab. but that is rather a tricj than a solution. 

Please help

**Comment by T16-Pilot** [comment]
Set ch6 to AUX in the SXR menu, it will act as a normal pwm channel. 

Or change output on pin 6 to another channel in the RF "set" menu. You know you can select what channel to go to what pin in the RF section...

**Comment by mawzthefinn** [comment]
Setting Ch6 to Aux turns off stabilization on the channel.

**Comment by toganalper** [comment]
the CH6 option only allows me to select either elev2 or aux. If I select aux it move the flap connected to pin number 8, if I select el3v2 it moves the other flap connected to pin 6. I also assumed that aux would stop the stabilization, but it did not I also didi self check afterwards with channel 3 throttle below 1000ms with sucsess but the pinout 6 or 8 always moves with the elevator ın the stabilazed mode.

**Comment by mawzthefinn** [comment]
Ch8 is Ele3 on Stabilization set 2. you need to go to the second page of the SRx Lua and disable Stabilization on that page to disable stabilization on Ch7-11.

As this is a receiver setup issue, I'd suggest you go here for assistance in setting them up:

https://www.rcgroups.com/forums/showthread.php?4272129-FrSky-New-Release-Advanced-Stabilization-Series-Units
