### ISSUE TITLE
Bluetooth telemetry reverts to off after power cycle or model change in version 1.5.9

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#4106]
Bluetooth telemetry was fixed in a previous version so that the on/off setting was remembered in the model; with version 1.5.9 it seems that the fix was removed as bluetooth always defaults to off on either a model change or a power cycle of the unit.  For reference this is on a X20 pro.

dave

**Comment by bsongis-frsky** [comment]
Reproduced
