### ISSUE TITLE
With an R9 MX (or RX Mini) attached to R8 Pro (in Access Mode) - Stays at 100% on X20 even after disconnecting!

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#411]
If you walk away from the receivers both 2.4 and 900 values go down. But even if you turn the receivers off the 900Mhz value stays at 100 - Very worrying.

Also with 900M running on X20 when you turn the X20 off it states the the receiver is still on, when it has been off for some time.

I'm on 1.0.7 on the X20 and have re-flashed the RX MX and Mini as well.

**Comment by jfint** [comment]
What isrm version?

**Comment by KenLong51** [comment]
Hi,
My ISRM version is:- HW: 1.4.0 FW: 2.1.8 (EU)
Regards

**Comment by combat-marcus** [comment]
@KenLong51 
confirm. Same problem with all latest firmwares

**Comment by raydars** [comment]
The radio displays last seen telemetry from rx, this is nothing new and one of the quirks of telemetry.

**Comment by bsongis-frsky** [comment]
I cannot replicate here!

**Comment by KenLong51** [comment]
> The radio displays last seen telemetry from rx, this is nothing new and one of the quirks of telemetry.

If that was the case it would make telemetry a wasye of time then. Also, if you asre correct, why doescthe 2.4Ghz link go to zero?

**Comment by KenLong51** [comment]
> I cannot replicate here!

Would you like me to post a video? But please consider that 'combat-marcus' has seen the same problem.

**Comment by bsongis-frsky** [comment]
I believe you :)
Do you see telemetry coming from the 900MHz receiver in Model / Telemetry, in the sensors list, the small point at the left?

**Comment by combat-marcus** [comment]
I got the same issue. I am going to take a video later too.

**Comment by KenLong51** [comment]
Here is a link to the video showing the 2.4 Ghz going off and the 900Mhz 'appearing' to stay on. Despite both receivers being powered Off, the X20 announces that the receiver is still on when I turn it off.

Sorry, but with all the problem I have had and the 400 posts on here, I just think the X20 is ready for market yet.

**Comment by MIKE-DAILEY** [comment]
There were some changes made in 1.0.8.  https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release%2F1.0.8

**Comment by bsongis-frsky** [comment]
@KenLong51 I did the test today. With Ethos 1.0.8 preview. No issue. Would you please install the latest release and tell me if the issue is gone or not.

**Comment by KenLong51** [comment]
Yay! V 1.0.8 has fixed it all.

Many thanks.

**Comment by KenLong51** [comment]
As this is fixed, I have marked it Closed - Hope that is OK
