### ISSUE TITLE
1.5.x issue with serial printing

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4110]
Hello,

im developing a new lua widget (with a bunch of graphical gauges) and it runs fine on the sim.
on the X20S 1.5.6 and 1.5.8 the widget doesnt refresh (maybe stuck on an error,, im not sure.)
i added some serial printing but im not getting any serial prints to my serial terminal on either 1.5.6 or 1.5.8.

i can supply the source LUA by email if needed. i will not publish it at this point, its far from ready.
thanks.
![RDTgauge2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/63502dfe-08f0-49ef-bade-79e403654b44)

**Comment by strgaltdel** [comment]
Hi,
What's your serial terminal:
Suite's DevTool terminal or putty ?

i'd similar issues with suites DevTool some Revs ago, when Tx was "heavy loaded", but this was fixed..
Putty was working O.K.

maybe a similar situation.
in case you're using devTool i would give putty a try and report back if issue stays

i'm wondering a little bit that you mention 1.5.6 & 1.5.8
i thought Bitmap rotation (especially for pointers in gauges) was introduced in 1.5.9
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/55739e15-4583-47f1-b6cb-a44fb8f56ba6)

maybe you are using complicated methods for "older" ethos revs which stresses the mpu?

regards
Udo

**Comment by i3dm** [comment]
I'm using arduino serial monitor. Similar to putty.

I'm not rotating any images in my Lua.

**Comment by strgaltdel** [comment]
strange,

print() has worked for me so far without any problems,
maybe the script does not reach the print statement, but then at least an error should be prompted.

**Comment by i3dm** [comment]
I'm printing os. Clock() in paint(widget).
Works well on the Sim but not on the Tx.

**Comment by i3dm** [comment]
i did notice thiswhen running the sim:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/4682cc3e-46bc-4a46-9ee7-742436d97473)

seems like thewidget keeps deleting theimages and reloading themfor some reason, every time i clickon the widget screen.

**Comment by i3dm** [comment]
some info about memory from the sim:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/add261ae-ab99-4db0-8bb5-c579635e8f5f)

**Comment by i3dm** [comment]
i have just witnessed that the LUA issue happens only when running both RDT and RDT widget together. will have to look into this further.

one i run only the new RDT gause LUA, the serial works as expected.
any ideas how to investigate this further?
this works well on the sim.

**Comment by strgaltdel** [comment]
the sim is a kind of machine with unlimited CPU & mem resources
the radio is not

The images can only be reloaded if the load method has been called repeatedly in the script.
The garbage collector may then take effect to eliminate duplicates, but this could still cause a memory leak.
In any case, unnecessary CPU and IO load

The first thing I would do is track down the cause of the reload and eliminate it


Are you sure that there are no globally declared variables that both widgets use?
Would also cause a cross effect

have a look at the rssi bitmap:

682054 bytes are used when loading
but only 603934 bytes are deleted
>> mem leak?

for all other bitmaps there are matching deletions

regards
Udo

**Comment by i3dm** [comment]
im closing this issue for now until further investigation on my end.
