### ISSUE TITLE
Add handler to expantion panel

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4112]
This handler:

panel = form.addExpansionPanel("Label")
panel:addLine("Label")
panel:open(false) -- by default the panel is open, let's keep it closed!

Please can we add a feature like:

panel:onopen()
panel:onclose()

This will enable us to run an even when the user expands the panel or closes the panel.

For example .. when you expand a section.. close all other sections.

**Comment by bsongis-frsky** [comment]
```lua
panel:event(
  function(event)
    if event == EVT_OPEN then 
      print("Expansion panel opened") 
    elseif event == EVT_CLOSE then 
      print("Expansion panel closed")
    end
  end
)
```
