### ISSUE TITLE
1.5.10 Nightly Create new model folder not possible!

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4113]
The keyboard overlays the layout window.
A new model folder cannot be created.

Test on the Sim and the X20S.

![Ordner](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/6a138323-25b7-4b91-8f96-0e321f375994)

Greetings Eugen

**Comment by philippe-warnotte** [comment]
Je n'ai pas ce problème avec windows 10  simulateur 1.5.10

**Comment by yak55** [comment]
Tested with Windows 11 and X20S.

Enclosed is a photo of the FST.

Greetings Eugen

![IMG_6439](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/df1ea5cc-9654-486f-83b9-938b1c36fbbc)

**Comment by bsongis-frsky** [comment]
I have reproduced it

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/e5ecb961-8571-451c-98ca-365c6dc7167c)
