### ISSUE TITLE
Simulator issues with X20 PRO

### ISSUE THREAD

**Issue by Didier-L** [FrSkyRC/ETHOS-Feedback-Community#4118]
There is only X20S simulator whatever the version of Ethos for the whole X20 family.
With Ethos 1.4.17, it is not possible to read a model with specific X20 PRO functions (ie play text). You get "invalid data".

With 1.5.10, it is a little better as you can read the model but all functions specific to X20 PRO are missing,
For example, if I have a special function using Play Text in my model, this special function is missing in the list of special functions in the simulated model.
I have not tried yet to see what hapen if I use one of the 2 back push buttons in a mixer ==> mixer line deleted in simulator ?

Not to speak about the RF system menu when using TW (you get ACCES instead) and info menu where I get 3 MX receivers ! And also the owner id is wrong.

Nothing catastophic but it limits the use of the simulator.

Didier

**Comment by bsongis-frsky** [comment]
X20PRO simulator added to the nightlies / releases
