### ISSUE TITLE
Can't play self created sounds

### ISSUE THREAD

**Issue by adfe1** [FrSkyRC/ETHOS-Feedback-Community#4119]
version 1.5.10 i cant use the self created sounds since the last two updates. i can't even select them.
transmitter X20s

**Comment by robthomson** [comment]
1.5.10 has not been made as an official release yet.

Are you sure this is the version you are using?

Or is this just in the simulator?

**Comment by adfe1** [comment]
Soory the version is the 1.5.9

**Comment by bsongis-frsky** [comment]
I think your sounds don't have the right format, how did you create them?

**Comment by bsongis-frsky** [comment]
Ethos Suite can convert them for you
