### ISSUE TITLE
No Bitmap Files available?

### ISSUE THREAD

**Issue by JustusJustJustus** [FrSkyRC/ETHOS-Feedback-Community#412]
Hi there.

I just installed the current ethos firmware version on my horus x10s express (v1.0.7). I wanted to place the icon bitmaps... into the folders told by the manual. But I cannot find any bitmaps, soundfiles.... to download. Where can I get them?

The firmware itself is running but looking a bit poor without bitmaps and is a bit quiet cause of no soundfiles.

Thanks in advance.

**Comment by Devil-IdT** [comment]
Have you downloaded this?
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/release%2F1.0.6/HORUS_SD.zip

**Comment by JustusJustJustus** [comment]
Thank you. Easier than expected ;-) I just loaded the current version v1.0.7 and there a several binaries but no sd contents. I did not expect them to be downloaded from previous versions. Thank you.
