### ISSUE TITLE
1.5.10 nightly - ELRS 'Enable WiFi' no longer works

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#4122]
1.5.10 nightly #9dcb0e37
X18SE and X20

The "Enable WiFi" button in the ELRS configuration LUA no longer works with this release.

**Comment by robthomson** [comment]
Hmmm
 What elrs version?

**Comment by rburrow87** [comment]
3.4 and 3.4.1. Is it working for you? The RX actually goes into wifi, but I don't get the dialog box saying that it's happening.

Thinking about the TX not going into wifi though, maybe it's because the dialog popup doesn't work? I believe it asks to confirm when you try to put the TX into wifi (maybe only when it's connected to an RX though).

**Comment by robthomson** [comment]
Will test it today and try replicate

**Comment by bsongis-frsky** [comment]
The fix will be in the next nightlies
