### ISSUE TITLE
Unable to run ethos suite since 1.5.2

### ISSUE THREAD

**Issue by rangecheck** [FrSkyRC/ETHOS-Feedback-Community#4123]
I'm using 64 bit Windows 7 . Ethos suite 1.5.2 installs and runs without problem.
I have installed all later versions since 1.5.2 They all fail to run with the same error which appears to be a javascript issue. I'm asking for help to solve this isssue.
This is the error:

![Ethos Suite 1 5 6 error](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/171475437/e0531088-3110-4add-a262-09dc59e42a8a)

Best regards
Robert

**Comment by Dsrenger** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3766

Windows 7 is 15 years old and out of support since several years. 

The suite libs got updated to versions, that just don't run on Win7 anymore. 

It will happen to more and more software in the future.

**Comment by rangecheck** [comment]
Thank you for your reply.
I was hoping for something more constructive. Can you tell me what versing of javascript ethos suite is expecting please?
Regards
Robert

**Comment by strgaltdel** [comment]
Bertrand pointed to the electron libs as root cause:

https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

**Comment by rangecheck** [comment]
Thank you for clarifying that I didn't recognise the link in Dsrenger's response.

**Comment by robthomson** [comment]
Yup.. Microsoft do not support it.   It's to all intents a doomed operating system and needs to be upgraded to windows 10 or higher.

**Comment by rangecheck** [comment]
I know that microsoft don’t support windows 7 anymore. However I have tried both windows 10 and 11 and found them unacceptable to me. 

For now I will continue to use windows 7 and Ethos suite 1.4.15. I was able to update my transmitter with that today so all is well.
