### ISSUE TITLE
Excess line in the mixer

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4126]
Hello,
If you insert a new action into a mixer, one line is left over. There is probably one line too many. If you close this mixer and open it again, the excess line is no longer displayed.
Ethos 1.5.9 and 1.5.10 in the sim and transmitter 
Best regards from Wolfgang

**Comment by bsongis-frsky** [comment]
@lthole told me about this issue, but he said it was only there in the 1.5.10 nightlies!

It has been fixed during the week-end and it will be part of the next nightlies

**Comment by Wolepo** [comment]
No, I don't mean anything else. I was surprised that the issue was still there.
