### ISSUE TITLE
1.5.8: prevent boot-"EM loops" in case of CRC errors 

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#4129]
Today on the slope, approx. 4 flights, fine trim necessary on the model.
(editing mixer)
When switching on the transmitter again, a short error message with EM appeared afterwards.
I couldn't get out of this “power on and go for EM" loop, at least i couldn't find a way to switch to another template (model selection on start not configured )

I needed 3 boot processes to identify the short-timed error message (CRC error)

The problem itself could be solved quickly via notebook & backup template, but not everyone has his notebook handy on vacation...

Suggestion:

- if possible, leave the error message for approx. 2-3 seconds on display, so it can be read without problems

- if a CRC error is detected at boot, jump to the “create model” workflow to be able to provide an operational system
(like when the last active template no longer exists)

- an almost “perfect” solution would keep a “shadow file” for each template, i.e. each change would have to be saved in two files. “Shadow files” are not visible during operation, but could possibly be used via a new “restore” function.
Alternatively, only write changes to the “current” file, and the shadow file is one “session” back (e.g. define “second last” version on shutdown)  

regards

**Comment by strgaltdel** [comment]
additional info:

- only nand is used

- from my side  no further investigation on model file needed,
but in case of interest, the corrupted file

[mtwister e.bin.zip](https://github.com/user-attachments/files/15538420/mtwister.e.bin.zip)

**Comment by bsongis-frsky** [comment]
Many changes have been done in 1.5.9 for Radio startup and I cannot reproduce this problem, here the message which is displayed:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4f42a6ac-1520-4148-a681-c9856fddc91b)

**Comment by bsongis-frsky** [comment]
Would you please try something:

0) you do a backup, just in case ...
1) you load a model, and you keep in mind the filename of this model
2) with the computer, you override this model with the twister attached to the issue
3) you start again the radio

What happens on 1.5.8?

What happens on 1.5.9?

There is nothing modified in 1.5.10 nightlies in this area. But perhaps it's preferrable to check it as well to be sure?

**Comment by strgaltdel** [comment]
tested again on 1.5.8, same result:
very short prompting of CRC error and running into EM


will test 1.5.9 on monday, after vacation
but when i look onto your screenshot, i suspect 1.5.9 has already implemented the wizard workflow as proposed.
if so, i'll close the issue after 1.5.9 testing...


thanks & regards
udo

**Comment by bsongis** [comment]
Excellent. I will check this myself to be sure.

**Comment by strgaltdel** [comment]
Hi,
just checked on 1.5.9,
worked as expected:

message "crc error" stays, and an option to start a wizard was given.
so you can built an empty template and the radio stays operative

when trying to select the broken template, message crc error was prompted too

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/641d90bd-b2f2-4f26-94bb-9622346871f5)
