### ISSUE TITLE
1.5.10 Nightly comment line logical switches

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4130]
Comment line (screen) behaves strangely when you end the text input with ENTER.

Photo is from the X20S

Greetings Eugen

![IMG_6440](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/9b8f16ec-318f-431b-b24d-be8b5d1985c8)

**Comment by bsongis-frsky** [comment]
I wonder if it is a regression from 1.5.10 or if it is the same since forever!

**Comment by yak55** [comment]
is already so strange in 1.5.9.

I do not have older versions

Greetings Eugen

**Comment by bsongis-frsky** [comment]
It will be fixed in the next nightlies
