### ISSUE TITLE
Add comments for VARS

### ISSUE THREAD

**Issue by pmullen503** [FrSkyRC/ETHOS-Feedback-Community#4131]
Comments for logical functions is very useful. I'm hoping we could add the same feature for VARS.

**Comment by bsongis-frsky** [comment]
Why not?

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/72761f0d-46e1-4746-a052-01a637a3db07)
