### ISSUE TITLE
[feature request] add channel output values to bluetooth telemetry data

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#4133]
Looking at the telemetry data streamed by bluetooth it seems that there is no way to get data channel along with the S.Port information so I am requesting that a new set of DATA IDs be created and the ppm value for the channels be streamed as a RAW data value.  This would allow for ground stations (or flight controllers) to do advanced calculations based on actual flight data.  

A suggestion would be to have a custom sensor that can be created allowing the user to pick the channels that they want (e.g. channel sensor 1 == ppm for channel 1, channel sensor 2 == ppm for channel 2, etc) so as to limit the streaming of data to only that is what needed.

As an example I am writing a ground station app where using my iPhone as a recorder to collect the bluetooth S.Port data for later analysis.  if the throttle values are present in the stream you can then do things like calculate voltage/current usage vs throttle (e.g. how many amps am I using in a punchout) and also gauge general battery health over time as you will be able to compare internal resistance and voltage sag using the same power system and throttle values.

**Comment by mawzthefinn** [comment]
The Bluetooth stream is S.Port, which cannot carry channel data.

It sounds like the use of FBus for the stream (which does carry channel data) would solve this, but would require additional work for whoever is consuming the data.

**Comment by fdm225** [comment]
Hi Mawzthefinn,
I would absolutely use FBus but when I set it up on my receiver I still received S.Port messages via bluetooth.  I have been unable to find any concrete documentation around FBus (not that there is much for S.Port) so if there is something I am missing I would love to know it.   I am guessing here, but I suspect that F-Bus still uses the S.Port messages and when the radio receives them it sends those messages via Bluetooth, but as I said that is just a guess as I don't have access to the source code.

Any help in this would be appreciated as I am not fixed on S.Bus, it just seems from my testing that is the only thing available via bluetooth.  I wish FrSKY would document this stuff better, seems like a lot of paranoia for a "feature" that you can enable in the radio.

**Comment by mawzthefinn** [comment]
@fdm225 The BT always runs in S.Port mode, as the FBus telemetry format is identical and you can send FBus telemetry over S.Port without losing any telemetry data.

However S.Port cannot send channel data, so the BT telemetry mirror function in ETHOS needs to have FBus support added to do what you want, not the receiver side. It would require the BT device consuming this data to also support FBus.

**Comment by fdm225** [comment]
@mawzthefinn Thank you for confirming my theories around this, hopefully the devs will pick this up and add it as it could open some really great possibilities for add on peripherals.

dave
