### ISSUE TITLE
In model manager, it doesn't allow me edit

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#4135]
In model manager it will not allow me to edit any of the models, not sure what I'm doing wrong. Any help would be great, 18se with all the new updates.

**Comment by Dsrenger** [comment]
You are doing nothing wrong. 

It's a future functionality that will be added in the future. Not added yet. 

No eta given so far

**Comment by mawzthefinn** [comment]
That's correct, this functionality has not yet been added to ETHOS Suite. It is coming.
