### ISSUE TITLE
X20R sound,not as rich and clear as x20/x20S

### ISSUE THREAD

**Issue by ETHOSWarrier** [FrSkyRC/ETHOS-Feedback-Community#4136]
Hi, Just bought an x20R and put ETHOS 1.5.9 EU on it.I was amazed how the sound was not as good as my x20 or x20s.Now ,they are still on 1.4.17 ETHOS EU for info. Sound files are the same ones used on x20s and x20R

Its not terrible for info, but not as rich or clear and distorts more at full volume.

Is this an ETHOS 1.5.9 issue or a radio hardware issue...does anyone know or noticed the same..EW

**Comment by bsongis-frsky** [comment]
I have to check, Rob told me that he uses a different sound pack on his X20-PRO with a better sample rate, and it gives a better result.

**Comment by ETHOSWarrier** [comment]
> I have to check, Rob told me that he uses a different sound pack on his X20-PRO with a better sample rate, and it gives a better result.

Yes,it might make a difference with a different sound pack but I am using exactly the same sounds,i copied the sounds folder so they are the same wav files for both  my x20s on 1,4,17 and x20R on 1.5.9. 
My question is why do they play the same wav file differently and is it ETHOS or just the new hardware in the x20R,and if so its disappointing really.Its really noticeable if you start them side by side at the same time..then they both welcome you on start up.

I cant put the X20R on 1.4.17 as there are no releases for it to see if its ETHOS doing this...or can I? Is there somewhere 1.4.17 for an x20R...thanks ...EW

**Comment by mawzthefinn** [comment]
> I have to check, Rob told me that he uses a different sound pack on his X20-PRO with a better sample rate, and it gives a better result.

The different case material on the PRO makes a huge difference in sound quality. The Pro really needs a seperate sound pack with compression settings and EQ optimized for the sound hardware because the Aluminum case doesn't transmit sound like a plastic case does. 

The R/RS may also need similar adjustments (they have a case more like the X20, but it seems there is still a difference)

**Comment by mawzthefinn** [comment]
> I cant put the X20R on 1.4.17 as there are no releases for it to see if its ETHOS doing this...or can I? Is there somewhere 1.4.17 for an x20R...thanks ...EW

X20R came out after the last 1.4 release, there's no 1.4 support for it.

**Comment by ETHOSWarrier** [comment]
> > I cant put the X20R on 1.4.17 as there are no releases for it to see if its ETHOS doing this...or can I? Is there somewhere 1.4.17 for an x20R...thanks ...EW
> 
> X20R came out after the last 1.4 release, there's no 1.4 support for it.

Fair enough I will stick with 1.5.9 then........But thats got me thinking ...can we have a graphic equaliser then for the sound...ok maybe a Trebble and bass then so I can fine tune as best i can.I have a 550 wav file sound pack and many special sounds so i dont think i would get an adjusted one,unless we can do that ourselves.

Is a sound "Fine Tuner" on Ethos a possibility Mawz/Bsongis? now that would make my super radio(x20r) fantastic...EW

Ps... the Vario has a  Pitch adjuster, so some sort of Equaliser should be possible.

BTW just tested the sound with my thumb over the speaker...a lot better. more like the x20S i have.

**Comment by ETHOSWarrier** [comment]
> > I have to check, Rob told me that he uses a different sound pack on his X20-PRO with a better sample rate, and it gives a better result.
> 
> The different case material on the PRO makes a huge difference in sound quality. The Pro really needs a seperate sound pack with compression settings and EQ optimized for the sound hardware because the Aluminum case doesn't transmit sound like a plastic case does.
> 
> The R/RS may also need similar adjustments (they have a case more like the X20, but it seems there is still a difference)

Mawz....For info i have a bit more in depth analysed the sound...The pitch of the beep when say moving the rotary dial around...It is significantly higher pitch on the x20R than my x20S.....this would explain a little of the tininess  i can hear too.

I am not musical but its a big, very noticeable difference in pitch...So a pitch changer might help, like the vario pitch changer..EW

EDIT: just playing with the trims and listening to the sound.....when reaching about 75% on the high side the high pitch starts to go weird..as if its too high for the amp/speaker etc....a bit gargled..happens on every trim so a lower pitch sound overall(like the x20S) might solve that too.

**Comment by robthomson** [comment]
Maybe try my sound pack..

https://github.com/robthomson/ETHOS-SOUND-CREATOR/tree/main/TTSCMD

Be interested to know of it's better on the rs?
