### ISSUE TITLE
1.5.9 Erreur d'affichage français "intensité" dans le menu des fichiers LOGS

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4138]
Dans 2 menus des fichiers logs, le mot "intensité" il y a un problème avec l'accent(voir screenshot)
![screenshot-2024-06-05-37077](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165813792/d6ae6178-aa94-4fe9-89b3-70eb3378fd61)
![screenshot-2024-06-05-37099](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165813792/a95e49df-4e6a-4ef7-a193-a0149daf0e97)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/916b2094-f4a5-4e7d-8002-78abcd5df570)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/25833c31-2020-4b1f-9f78-15e192748b5f)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c5606875-f9cd-40e2-84f4-84a386e11468)

**Comment by philippe-warnotte** [comment]
Merci beaucoup
