### ISSUE TITLE
1.5.10. Nightly display ELRS configuration unreadable

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4139]
Transmitter: X20S
Setup transmitter module: Line under Fan Thresh unreadable

![Anzeige](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/1a490d80-f5b1-4675-9234-958faafb3b72)

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Would you know which is the field which is hidden? Is it a text field?

**Comment by yak55** [comment]
there is a comment field

here is a picture of 1.5.9

![Admin](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/36eab8eb-14bf-4b33-9dad-d98f07485963)

**Comment by bsongis-frsky** [comment]
It's linked to 1.5.10 nightly?
The text seems "100mW CE LIMIT"

**Comment by bsongis-frsky** [comment]
Found it, it will be fixed in the next nightlies

**Comment by bsongis-frsky** [comment]
@yak55 I want to thank you for the 3 or 4 issues you have opened recently, I have done a lot of modifications in the Lua interface and you have found the regressions. I hope we will reach the perfect result soon!

**Comment by yak55** [comment]
Hello Bertrand, working with you is a great pleasure.

I was with a competitor for many years, but without any opportunity for communication.

That's why I switched to Ethos - it was the best thing that could have happened to me.

Many thanks for the hard work of you and your team.

Greetings Eugen
