### ISSUE TITLE
v1.08 Vario tone rate receiver dependent

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#414]
X20S v1.08 TD-ISRM fw 2.18

Receiver GR8

Vario system is still a mess.

No nice constant tone pulse, little and big pauses between beeps.
GR8 is the most worst, G-RX6 bit better, and R8 + external vario sensor best.

It has something to do with sensor update, there are gaps between sensor data update that cause the broken beep sequence.

Never seen that in OTX

**Comment by jreis1** [comment]
Which vario settings are you using? I'm with Archer GRX8 and 1.0.7 and my vario tones are working perfectly on my X20. 
In the vario settings, under vspeed, I've just changed the parameter (can't remember the name and I'm not with the radio) to -0.5 and +0.5, instead of -0.3/0.3. 

Can you please have a try?

**Comment by Hobby4life** [comment]
GR8
https://youtu.be/zbVvNuV1ce0

R8 + External Vario sensor
https://youtu.be/itdw6XhkBjs

G-RX6
https://youtu.be/t1jpHX_SC2E

**Comment by jreis1** [comment]
Try to change this 

![0E1EB142-FBBE-442E-8403-FCD7412EF5E1](https://user-images.githubusercontent.com/25162166/121064678-cb64e480-c7bf-11eb-83a5-7213ab68ada4.jpeg)
![2A5555F3-D696-4FD0-B4BC-C35D0410CC83](https://user-images.githubusercontent.com/25162166/121064690-cdc73e80-c7bf-11eb-8dfc-7bb89afe5f69.jpeg)

**Comment by Hobby4life** [comment]
Nope, did not work.

If you watch the first video, and pay attention to Vspeed, you don't see that sensor data constantly updating, there are pauses in between. you can hear this in the vario.
No idea where the problem lies. only I didn't have this problem with OpenTX on an X10S express

**Comment by jreis1** [comment]
Something is really not right with your configuration :/ 
Mine is working perfectly as I said. In sound tab what is your tones and update interval ?

**Comment by Hobby4life** [comment]
500mS

I am now 100% sure, the beep squence speed you hear is related to the amount of telemetry updates you get.
This should be 1 standard. even if the vario sensor is updating once per second you should hear these beeps at a 500mS, and if your sensor is updating with a rate of 100mS again you should hear it at 500mS.

Why else do we have the Repeat option??

**Comment by bsongis-frsky** [comment]
The 500ms parameter is for vertical speed = 0.
Of course it goes faster and slower, depending on your vertical speed.

**Comment by Hobby4life** [comment]
Look at the video's, specially the first one.. see VSPEED.. notice the dot is not constantly blinking.. there are gaps.
These "gaps" are translated to the bad audiable vario sound. no data = no sound.
The faster the update from the receiver the better the vario sound will be sound..
If the receiver is updating VSPEED at 250ms to the radio.. you will a 250mS constant vario beep.. not 500mS as set..

Ethos should always be updating at the set repeat time... from gathered vario receiver updates. this way whatever your receiver is updating, ethos always will give a clean (in this case) 500mS beep repeat frequency.

**Comment by Hobby4life** [comment]
There is serious something going on between the (TD-ISRM and Receiver) Frsky really has to dig into the GRx receiver firmware. I just got reports the GR6 is haveing the same problem.

Its more likely a problem in the receiver firmware.
Perhaps because the telemetry part in ethos may have been written differently and handles incoming telemetry data differently, this is now noticeable.

**Comment by bsongis-frsky** [comment]
Ethos updates the vario tones always at the same speed, it doesn't depend on the receiver

**Comment by bsongis-frsky** [comment]
Ah, yes, the value from the sensor has to be "fresh" and the threshold is 50ms! I will increase this threshold a little bit

**Comment by Hobby4life** [comment]
;-) hope it works

**Comment by Hobby4life** [comment]
Seems to be fixed bertrand, good job! :-)
