### ISSUE TITLE
widget: display 1 text for each postion of logical switch

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#4140]
hello

Is it possible to configure the widgets to have a separate display for a 2-state logic switch: for example: display "ARMED" at state 0, and display "DISARMED" at state 1?

est il possible de configurer les widget de manière à avoir un affichage distinct pour un interrupteur logique à 2 états: par exemple: afficher "ARMÉ" à l'état 0, et afficher "DESARMÉ" à l'état 1.

merci pour vos réponses

**Comment by bsongis-frsky** [comment]
I think a lua widget will do this very easily, no?

**Comment by samsab1** [comment]
alors là on arrive sur un espace temps inconnu de moi....une 4 em dimension en quelque sorte...
connais tu un lien permettant d'apprivoiser ce concept de lua?

**Comment by pmullen503** [comment]
There's a widget out there called "status" that does exactly that, you can even make it change colors. I ran across it on RCGroups.

**Comment by samsab1** [comment]
thanks for the answer; do you have a link to that thread on rcgroups?

**Comment by samsab1** [comment]
i va got it https://www.rcgroups.com/forums/showpost.php?p=48549449&postcount=236
by the way, such function should be offered natively to ethos, don't you think so?

**Comment by KevinFairgrieve** [comment]
I use this widget on all my electric models. Nice clear simple solution.
