### ISSUE TITLE
1.5.10 Nightly width of error field too narrow at baud rate

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4141]
Please widen the field, the 3rd digit from the right will be cut off.
Errors on X20 and XE since ELRS 3.4.0 are constantly in the range greater than 100 - immediately after switching on the transmitter.

![Werte](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/9f6c567d-4078-4a8f-ac97-546103425dbe)

**Comment by bsongis-frsky** [comment]
I have introduced this "error" field just for testing, and I forgot to remove it, as it was never displayed with the previous ELRS version. Now it is displayed, but it may be normal there are errors, depending on the module type / startup time / etc.

I will remove it right now.
