### ISSUE TITLE
VAR values not correctly referenced in Output Min/Max "Use a Source" menu.

### ISSUE THREAD

**Issue by ja-jaa-org-uk** [FrSkyRC/ETHOS-Feedback-Community#4142]
X20Pro Ethos 1.5.9 EU
Values defined by a VAR do not appear to get correctly transferred to an Output Max or Min value.
Fig1 shows the VAR which successfully switches between -99.9% and -25.1%
Fig2 shows the Output using the VAR as a source for Min. VAR=-25.1% gives -93.8%
Fig3 shows the Output with the VAR value switched to -99.9%, the Min is shown as -149.9%
![Fig1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17146097/11378c31-5c43-48eb-9f88-602fbfb8ba70)
![Fig2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17146097/09fabe14-a950-4679-af5b-53f9533f68f0)
![Fig3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/17146097/c3731a0a-b5c9-4466-b6d8-30e071d50617)

**Comment by bsongis-frsky** [comment]
This one is not exactly a bug!
1) Min(Channel) is in range [-150.0% : 0.0%]
2) Your Var has a range [-100.0% : +100.0%]
3) If your Var = -25% then it is 37.5% inside the range of this Var
4) 37.5% inside the range of your Min(Channel) gives -93.75%

**Comment by bsongis-frsky** [comment]
To have the right result, it would be good that the 2 ranges are the same. I.E. Your var should have a range [-150% : 0%]

**Comment by bsongis-frsky** [comment]
Or Ethos could have an option for the Var source (and perhaps other analogs where the result will be the same), so that the Range is not adapted. The value would be just copied.

**Comment by ja-jaa-org-uk** [comment]
Hmm - I would not have been able to suss that out!

The term "Range" seems to mean different things in the two context.
1. "VAR" Restricting the range to MIN > -150%, MAX < +150%, MAX > MIN
    MIN = +50%, MAX = +60% being a valid setting.

2. "Output" Essential a three point curve, -150% < MIN < 0%
                                                                  0% < MAX < +150%
Hence copying the VAR directly into the current Output parameters may be invalid.

I have always thought that the 3 points ( MIN, 0, MAX) in the "Output" is not always applicable.
(I realise that using a two point curve is a work around)
If there were an Option in the Output menu to just have MIN & MAX defined with no centre point then things would be
far more straight forward.
The gain across the full stick movement would be linear.
MIN = +50% and MAX = +60% would be a valid limitation on channel output.
No computation of (MIN + MAX)/2 would be needed.
Fewer curves in  mikeshellim's templates ??
A VAR could then be copied to the Output MAX/MIN with confidence.
The "correct" purpose of MIN & MAX in the Output would be retained
ie preventing damage to servos

An alternative would to have an option for the "Output"  "0%" value of (MIN+MAX)/2 but
this is not as elegant as the restriction of MIN < 0% and MAX > 0% would still be applicable.

In either case the direct copy of the VAR value to the "Output" MAX/MIN would be necessary.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/dd15e13c-8254-489e-8e60-7cd0210ec318)
