### ISSUE TITLE
TD SR10 issue (possibly RF issue?)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#4143]
I'm not sure if this is an RF issue (f/w) or something with the SRx Stable script

In the script you have the option for CH5 Mode and CH6 Mode of a surface or AUXn.  Selecting AUXn seems to stop the surface from responding to the gyro. This leads me to assume that CH5/6 can be used for other purposes other than the listed AIL2/ELE2 (e.g. flaps) which makes sense and is very useful.

On the second page we have similar options of CH10 Mode and CH11 Mode. Given that this is a 10 channel rx being able to reuse CH11 isn't very helpful! 
It would be useful to have CHn Aux Modes for other channels, particularly on the second page (CH6-10) for all these channels. It took a fair bit of head scratching to work out why my flap on CH8 was responding to the Gyro as it if was an elevator - because I'd not changed the gains to 0% for this channel. 

Thanks

**Comment by mgsanna** [comment]
Hello Jedsters, in the second page simply deactivate the stable functions.... so CH7-10 are normal assignable channel
The 2 page are indipendent... so page 1 ch1-ch6 (ch5&ch6 - aux1 aux2) page 2 ch7-ch10 indipendent use with or without stab functions
so you can use all 10 ch to be gyro controlled or only the first 5/6

![Screenshot 2024-06-06 185736](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/3fe66064-033e-4d5b-8bf5-33512c479d61)

**Comment by mawzthefinn** [comment]
The first 3 channels in each stabilizer set (Ail1, Ele1, Rud1 for Set 1, Ail3, Ele3, Rud2 for Set2) are treated as a block, and enabled/disabled with the set. The 4th & 5th channels in each set can be disabled/enabled independently. 

FYI - the SBus & FBus outputs are stabilized, you can use Sbus & Fbus outputs with SBus/FBus servos or channel expanders to get up to 21 usable channels out of the receiver (ch13-15 are reserved for the stabilization system)

**Comment by mgsanna** [comment]
@mawzthefinn but I don't think there is a "RF ISSUE", in descriptions of Jedsters, it seem that he has not disabled the page 2 stable functions..... not a rf issue...

**Comment by mawzthefinn** [comment]
> @mawzthefinn but I don't think there is a "RF ISSUE", in descriptions of Jedsters, it seem that he has not disabled the page 2 stable functions..... not a rf issue...

We generally tag anything that is a receiver-side behaviour as RF issue, even if it's not actually broken.

**Comment by mgsanna** [comment]
@mawzthefinn ok thanks for explanation!!

**Comment by Jedsters** [comment]
Yes, I realise I could disable staibilzation for ch6-10 as a group however that's not helpful in my case. I have a glider with 4 ail and 2 flaps, ele and rudder. I want all 4 ail to be acted on with the gyro (ch1, 5, 7, 10) but I do not want the flaps ch6 and ch8 to be controlled by the gyro, especially when ch8 responds as an elevator. 
Thanks for the clarification of ch11 still being stabilised via FBUS, but I'm using non FBUS servos etc. 
Thanks

**Comment by mawzthefinn** [comment]
You'll need to assign the second flaps channel to a channel other than Rud2 in that case. You can still use Port 8 of the receiver after re-assigning it to the unstabilized channel you picked for the mixer assignment, as the port assignment is independent of the stabilizer, it's only RF channel assignment that is fixed.

**Comment by Jedsters** [comment]
OK, this sounds interesting. So you are saying change the channel range to 1 - 24, change pins 6 and 8 to e.g. CH16 and CH17 and then change the mixes to move references to CH6 and 8 to CH16 and CH17? 
Thanks

**Comment by mawzthefinn** [comment]
> OK, this sounds interesting. So you are saying change the channel range to 1 - 24, change pins 6 and 8 to e.g. CH16 and CH17 and then change the mixes to move references to CH6 and 8 to CH16 and CH17? Thanks

Yes, that would work. But you only need to re-assign Ch8, so long as Ch6 is set to Aux you can leave it set that way and only re-assign Port 8 (I'd re-assign to Ch11 or Ch12, if ch11, you need to set Ch11 to Aux on Page 2 of the SRx Lua)

**Comment by Jedsters** [comment]
Ah, of course! Clever. 
Thanks Mawz!
