### ISSUE TITLE
TD SRX issue (possibly RF Issue)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#4144]
It's not clear to me if this is an Ethos issue or RF Issue.
If you turn on a tx, then power up a TD SR10 rx and then go into SRX Stable, the Stabilizing option will always show as OFF on both pages regardless of whether it is ON or OFF. It is not until you select OPEN that it corrects.

See this video. You can see the rx reception bars go up as the rx connects, however the Stabilizing option doesn't change until I select OPEN. Although this was done quickly to keep the size of the video small it remains the case even if you wait. 

https://www.dropbox.com/s/u8v5i3pc5tdpbnk/VID_20240606_175756.mp4?dl=0

It appears that if you select OPEN and then power the rx off and back on, then the Stabilizing option will show as ON. Knowing whether Stabilizing is on or off is very important given that turning it on or off can invert the servo output!

Thanks

**Comment by Wolepo** [comment]
Pressing [open] establishes the connection between the SXR Stable (LUA) in the transmitter and receiver and reads the data from the gyro. This is not an error but merely an additional step. This could provide additional security against unauthorised settings.
Wolfgang

**Comment by Jedsters** [comment]
OK, I guess the data is at least greyed out until you press OPEN so now I know what's going on I'll close
Thanks.
