### ISSUE TITLE
TD SR10 Altitude wrong (probably RF issue?)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#4146]
I have 2 x TD SR10 and on both of them the altitude doesn't reset to 0 after turning on. 

This is a video showing what happens with my first rx. 

https://www.dropbox.com/s/uomccm92syls29z/VID_20240605_151348.mp4?dl=0

where the altitude quickly jumps to 206'

The second rx isn't so bad in that it only jumps to 29' - although curiously when I first tested this a few days ago after I'd just received it, it reset to 0' correctly. 

Of course, in the short term I can setup a LS and SF to reset the altitude after a few seconds, but this shouldn't be necessary, I don't have this problem with any of my vario sensors.

Thanks

**Comment by kramgrand** [comment]
Hi, just as a by the way.   I have a fair number of GR8 receivers in my gliders. None of them power on at 0m.  I have always used a LS and SF that hold an altitude reset for a few seconds after plugging in.   Separate Vario sensors do not suffer from this, only the RXs with built in Varios.

**Comment by Jedsters** [comment]
Interesting, do you find that your built in varios increase altitude over a sec or two once powered up or do they jump straight to an specific altitude?
For me it's like something is going on in the rx after it powers up which causes the alt to gradually increase. Possibly the same thing which causes the 2.4G RSSI to gradually increase over a sec or two (but at least I want that to increase to 100!)

**Comment by hrenz** [comment]
All pressure sensors drift after power on for up to 1 min, this is normal.
They display completely incorrect values.

Remedy: e.g. reset height via switch pulse
with motor enable or start timer 
then everything fits

**Comment by Jedsters** [comment]
Why don't the external pressure sensors drift? Those seem to power on with a value and aside normal variation as pressure varies slightly don't drift much (a few feet rather than hundreds of feet.)

**Comment by hrenz** [comment]
They also drift, all pressure sensors drift
from all manufacturers
and from all vario manufacturers
but the software keeps them at zero for a long time, until they no longer drift

FrSky does not do this at all, you have to reset it yourself
that's the way it is

**Comment by Jedsters** [comment]
I've just tested with a FrSky VARI sensor and that's not what I'm seeing. Once the rx is powered up it displays an altitude close to 0' which then continuously changes rapidly (e.g. 2 times per sec) around 0'. There is no software which is keeping it at zero.
Some how the external sensor works as expected, so it should be possible for the built in sensor to work the same way.

**Comment by Jedsters** [comment]
Another quick little test. I put the rx  / VARI sensor on the floor, powered it up and it reported ~0' I immediately put them on a cabinet and they quickly showed ~6' as expected. I left them there and monitored for a few minutes (longer than it would take me to turn a glider on and throw it) and although it varied as expected with this type of sensor it never dropped below 3' or went above 9' and all jumps in pressure were as expected, i.e <1' per half sec or whatever the refresh rate is. Again, this suggests that the only reset is at power up. This is what should happen with built in sensors. 

If this can't be done for any reason in the f/w, then please can we have an option in the telemetry. I notice there is a Reset option already there, maybe this just needs a Timer added to it to reset x secs after power up?

**Comment by Richrfl** [comment]
Guys, if you have ever used a FrSky VARI ADV sensor, you will notice that the electronics have to stabilize for about one minute before generating a reading. Also, consider that the variometer is based on atmospheric pressure, which is not the same for the same place on different days. Therefore, as suggested in the thread, energize the receiver and before launching reset the telemetry or just the vario. Given that I also use other sensors, I use the reset telemetry function before taking off.
