### ISSUE TITLE
Multi module translates pins

### ISSUE THREAD

**Issue by drummaker** [FrSkyRC/ETHOS-Feedback-Community#4147]
I was testing a plane with Spektrum in it today.   I discovered that  either ethos or the multi module does pin translation so that the receiver counts like spektrum.    I find this behavior odd.     Channel 3 (throtle) operates Chan 1 on the receiver 
Chan 1 shows up on 2. And so on.  

Is this programming in ethos or in multi module?

**Comment by rburrow87** [comment]
That is being done by the multi-module firmware: https://www.multi-module.org/using-the-module/protocol-details/dsm

**Comment by pmullen503** [comment]
Multi module. Go to multi-module.org. You can choose firmware that doesn't reorder Spektrum.

**Comment by mawzthefinn** [comment]
Closing as this is covered in the MPM documentation
