### ISSUE TITLE
Flight altitude cannot be reset. 1.0.8

### ISSUE THREAD

**Issue by michifpv** [FrSkyRC/ETHOS-Feedback-Community#415]
With the update 1.0.7 you could reset the flight altitude to 0 meters before take-off.
With the update 1.0.8 the height changes briefly to 0m after the reset, then it shows the relative height again e.g. 337 meters. So I don't see my current altitude without the relative height.

**Comment by KenLong51** [comment]
Yep I have just upgraded and get same problem - will have to go back to 1.0.7.

**Comment by bsongis-frsky** [comment]
Flight altitude from which sensor?

**Comment by Hobby4life** [comment]
Altitude

**Comment by bsongis-frsky** [comment]
Not from GPS, right?

**Comment by michifpv** [comment]
Sorry, from the Archer GR8

**Comment by bsongis-frsky** [comment]
Seriously I just checked, I see no change relative to this sensor since 1.0.7!

**Comment by Hobby4life** [comment]
> Not from GPS, right?

No, Not from GPS..

Strange thing too is.. altitude starts at ridiculously negative altitudes +/-  -100m

**Comment by michifpv** [comment]
> 
> 
> Seriously I just checked, I see no change relative to this sensor since 1.0.7!

we flew it today before the update without any problems. After the flight I did the update and from then on it didn't work anymore. You can no longer set the height to 0.

**Comment by jfint** [comment]
I believe that they are describing and issue with the telemetry reset function.

**Comment by bsongis-frsky** [comment]
Yes Reset on the Altitude sensor. I am just afraid that the measure is not precise enough and it fluctuates a lot.
But 100m is very very big

**Comment by Hobby4life** [comment]
I made a video:

 https://youtu.be/7vbUMdvBfJs

**Comment by KenLong51** [comment]
And mine does it on a Accst G-RX8.

**Comment by jfint** [comment]
Also I verified that is also broken if you reset the whole telemetry, not just if you reset altitude.

**Comment by bsongis-frsky** [comment]
Wrong milestone, will be fixed in 1.0.9 which will be released later today

**Comment by islandflight** [comment]
Was this fix just for the barometric altimeter as it is still not possible to set the GPS altitude to zero? 1.09 candidate 2. X20s

**Comment by bsongis-frsky** [comment]
The feature for GPS altitude is ready, but still not merged, as it requires a new storage version
It will be for 1.0.10

**Comment by islandflight** [comment]
Thanks forvthe update
