### ISSUE TITLE
FrSky x20S firmware upgrade failed

### ISSUE THREAD

**Issue by ouselcot** [FrSkyRC/ETHOS-Feedback-Community#4154]
My X20s bootloader is version 1.4.3 I started to download the latest Ethos version for the transmitter. I got a message  to do this manually as the auto upgrade may not be working. Told to exit bootloader and star up transmitter as normal. when I went out of the bootloader mode that disappeared, but the screen stayed lit up but would not switch off or start as normal. To get a blank screen I had to disconnect the battery. When I re connected the battery all that I could do was to launch Bootloader. I could switch that off , but the transmitter still would not load as normal pressing the start button nothing. Please help.

**Comment by mawzthefinn** [comment]
Your bootloader is old. 

If you update with latest ETHOS Suite (1.5.6 or later), it will fix this.

Otherwise download the 1.4.15 Bootloader and 1.4.15 ETHOS for your X20S. Put both files (unzipped) on the SD card next to radio.bin Flash ETHOS 1.4.15 from the current old bootloader (it should flash automatically when booting in bootloader), ETHOS should now boot.

Then go to System->File Manager, select the Bootloader file and flash it to your radio. 

Once complete, you can update to latest ETHOS

**Comment by ouselcot** [comment]
Thanks for the reply I am stuck could you give step by step instructions I
tried to follow, but need more detail please sorry to be a pain thanks
Charles

**Comment by mawzthefinn** [comment]
I'm not sure what additional info could be added, that is a step by step description of the process.

**Comment by strgaltdel** [comment]
maybe these links can help ?

https://www.rcgroups.com/forums/showpost.php?p=52193291&postcount=1910
https://www.rcgroups.com/forums/showpost.php?p=52193173&postcount=1909

(of course, you'll have to use the x20s files (-;  )

**Comment by ouselcot** [comment]
Hi thanks, but what I really want is just how to first update the boot
loader then I will know how to proceed could you just give me instructions
for that. Thanks very much

**Comment by mawzthefinn** [comment]
> Hi thanks, but what I really want is just how to first update the boot loader then I will know how to proceed could you just give me instructions for that. Thanks very much

My first post has those instructions. 

You need to roll back ETHOS to a version your current boatloader can boot be able to easily update the bootloader.

**Comment by Minos74** [comment]
> Your bootloader is old.
> 
> If you update with latest ETHOS Suite (1.5.6 or later), it will fix this.
> 
> Otherwise download the 1.4.15 Bootloader and 1.4.15 ETHOS for your X20S. Put both files (unzipped) on the SD card next to radio.bin Flash ETHOS 1.4.15 from the current old bootloader (it should flash automatically when booting in bootloader), ETHOS should now boot.
> 
> Then go to System->File Manager, select the Bootloader file and flash it to your radio.
> 
> Once complete, you can update to latest ETHOS

Thank you ! This helped me a lot today !
Frederic
