### ISSUE TITLE
In the depth mix, the trim off box does not deactivate the trim.

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#4157]
Hello,
Radio X20S-Ethos 1.5.9 EU:  
In the elevator mix, when I set the trim OFF box, the trim does not deactivate and shows a strange behavior.
In the other mixes (ailerons - steering - motor) the trim is deactivated normally by checking the off box.
On a simple model I've just created, it's the same.
Not tested on the simulator.

**Comment by mawzthefinn** [comment]
Duplicated on my X20 Pro

**Comment by bsongis-frsky** [comment]
Fix ready in next 1.5.10 nightlies
