### ISSUE TITLE
Volume changing during flight

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#4158]
Using Mike Shellim E soar plus v2.0.0 (for Ethos 1.5). Call outs volume on timers, flight modes and Vario were sometimes almost inaudible for 10s and then returning to normal. This would happen about 5 times in a 10 min flight.

X18S
1.5.9, EU

**Comment by bsongis-frsky** [comment]
Perhaps because something else is being played in the same time? Then the audio mixer decreases the 1st prompt to give priority to the 2nd one?

**Comment by miggy1952** [comment]
I will test again on the ground but why would/would it then run silent for such a long time

**Comment by miggy1952** [comment]
Exactly the same settings/vario/timers and everything was working fine!

**Comment by miggy1952** [comment]
Yet again, everything is working fine, audio not fading in/out but nothing has changed, absolutely identical setup.
