### ISSUE TITLE
X20 RS T5/T4 and T6/T1 Trims Swapped

### ISSUE THREAD

**Issue by frskyrc-ben** [FrSkyRC/ETHOS-Feedback-Community#4159]
X20 RS
ETHOS 1.5.9
Bootloader X20RS 1.5.9

The T5 and T4 trims and T6 and T1 trims are swapped

For example: 
Pushing T4 trim will increase\decrease the "T5" trim under the Model Setup -> Trims
Pushing the T5 trim will increase\decrease the "Rudder" trim (T4) under the Model Setup -> Trims

The same behavior is noticed between T6 and T1 trims

For example:
Pushing T1 trim will increase\decrease the "T6" trim under the Model Setup -> Trims
Pushing T6 trim will increase\decrease the "Aileron" (T1) trim under the Model Setup -> Trims

Video demonstrating the issue : https://drive.google.com/file/d/11AmSa1JnNldy6J_RpwG_26AhQXcHxbnQ/view?usp=sharing

**Comment by Nicholas-Luoyi** [comment]
Would you please confirm it with the firmware on the Github. I just test this with 1.5.9 and 1.5.10. Both are good here.

**Comment by ETHOSWarrier** [comment]
Are you sure ben you are on ETHOS 1.5.9 ? My x20R came with ETHOS version 1.5.7 and had the trims swapped as yours does. I flashed ETHOS 1.5.9 onto it and all was fine.....EW

**Comment by bsongis-frsky** [comment]
Right, 1.5.9 fixes this problem!
Factory will flash 1.5.9 from tomorrow, as it is the oldest Ethos release we have seen in 2024 :)

**Comment by frskyrc-ben** [comment]
Okay I figured out the issue. Our first production batch demo units were shipped with X20 PRO AW bootloader and subsequently when updated via ETHOS Suite it flashed X20 PRO AW 1.5.9.

After downloading the correct X20 RS 1.5.9 and flashing manually it has resolved the issue. Thank you

**Comment by ETHOSWarrier** [comment]
> Okay I figured out the issue. Our first production batch demo units were shipped with X20 PRO AW bootloader and subsequently when updated via ETHOS Suite it flashed X20 PRO AW 1.5.9.
> 
> After downloading the correct X20 RS 1.5.9 and flashing manually it has resolved the issue. Thank you

That makes sense Ben...as I did a manual flash and didn't connect the radio to the ethos suite.Just checked,mine had bootloader 1.5 so I am assuming that's the Pro AW one.I have now flashed the correct X20R bootloader to my radio for future Suite use....EW
