### ISSUE TITLE
v1.08 EDGE instant function? where?

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#416]
X20S v1.08 TD-ISRM fw 2.18

in v1.08 the EDGE function would include the instant mode. do I miss something?

Rising Edge? and "---" ?

Neither do "instant" actions.

If I press SI for 1 second then that function should become active after 1 second press. regardless of whether I have still pressed the button or not.

**Comment by bsongis-frsky** [comment]
What is your "Duration"? If it's 0.0s it's normal, the LS will have a 0 duration.

**Comment by Hobby4life** [comment]
Duration 0.5s, just to be sure everything listening to this LSW is triggered.

The problem is that all the EDGE functions are being performed when I release the button. not while keeping the button pressed.

**Comment by bsongis-frsky** [comment]
You should use "Rising Edge", it should work, I just tested it!

**Comment by bsongis-frsky** [comment]
Also the new "Edge" option on all switches is on Rising Edge, it gives more possibilities...

**Comment by Hobby4life** [comment]
Not working here.. I have made a video:

What I want here,, that is when I press the SI switch down,, the LSW must be active after 5.3seconds,, and stay active for 1.0s second.
Even when I keep pressing the button.. 

Instead it is active just after a press and does not wait 5.3s

https://youtu.be/xMUYoicH070

**Comment by bsongis-frsky** [comment]
You are not using the right logic switch! You need rather a delay to do this! 5.3s is the duration for the condition to be active!

**Comment by bsongis-frsky** [comment]
I am releasing a 1.0.9 in a couple of minutes. With only bugfixes, I don't want to take any risk

**Comment by Hobby4life** [comment]
Function is now working as expected.. perfect!

**Comment by MrD-RC** [comment]
So is rising edge the same as instant? If not, what is it? I was looking for instant too.

**Comment by Hobby4life** [comment]
Correct.. Rising Edge
