### ISSUE TITLE
X20S can't map receiver output pin to sbus-out [Solved]

### ISSUE THREAD

**Issue by Dannel-Li** [FrSkyRC/ETHOS-Feedback-Community#4160]
X20S (ethos v1.5.9) bound with TD R10 receiver (firmware 1.0.12), in the receiver setting menu, pin-out  options listing just ch1-ch24,no sbus-out,sbus-in and smartport.
![ethos_issue_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/172580166/de02d2c8-4bf9-4b33-b9f7-134ea38ee551)
![ethos_issue_2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/172580166/930dec4f-8d5a-462f-ac44-8d5ed68829a7)

**Comment by Dannel-Li** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/172580166/ab6887be-45be-4b61-9cb0-3f312793e389

**Comment by Cavalon90** [comment]
Had same problem. Check the version of your receiver and or update to newest version.

**Comment by mawzthefinn** [comment]
Check the TD ISRM as well, should be on 2.2.6, as the receiver is on latest.

**Comment by Dannel-Li** [comment]
TD ISRM version 2.2.6, TD R10 firmware v1.0.12，both latest.

**Comment by Dannel-Li** [comment]
![x20s_info1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/172580166/2e268b45-96dd-42bc-a31f-793c574f116a)
![x20s_info2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/172580166/aa2db891-3468-41bb-bfdb-4fd31542ee38)

**Comment by Dannel-Li** [comment]
![x20s_info3](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/172580166/1a2f00f1-ed03-4664-86f1-05949d9e83a6)
There is indeed "sbus output" at the end of the option list. Sorry for not confirming it carefully. Thank you for your reply.
