### ISSUE TITLE
FS not reset when switching model with SF

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4161]
Ethos 1.5.9

I have SFs for resetting the model (Reset Flight) and for switching to another model. My FS is not persistent.
- "Reset Flight" now resets FS (which I think is correct)
- "Loading a model" with a SF does not reset FS state (which I think it should do)

**Comment by bsongis-frsky** [comment]
And Load a model from Model / Select does reset FS state? It doesn't seem logical if it is the case!

**Comment by bsongis-frsky** [comment]
From the source code it should be the same behaviour from Model / Select

**Comment by bsongis-frsky** [comment]
Fixed in next nightlies

**Comment by azaz44** [comment]
Yes, normal "Load Model" is affected to. I just happen to always use a special function now.
