### ISSUE TITLE
Nightly 12.06. X20PRO Special functions Emergency Mode

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4162]
For existing models there is an emergency mode when calling the special functions.

A newly created test model can be opened.

The simulator only crashes sporadically.
The X20PRO ALWAYS!

I have attached a model.

Greetings Eugen

[caelestia.zip](https://github.com/user-attachments/files/15827607/caelestia.zip)

**Comment by bsongis-frsky** [comment]
Aie

**Comment by bsongis-frsky** [comment]
Ah I have fixed it earlier today, I added many non regression tests and I found it. The Special function involved is "Play sequence".
