### ISSUE TITLE
Part of the LOG file name (time) is hidden by the ETHOS logo.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4163]
Part of the name (time) of the LOG file hidden by the ETHOS logo.
![Heure-cachée-par-ETHOS](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165813792/21a4b640-c0b7-4ffd-b71a-62408476b70d)

**Comment by philippe-warnotte** [comment]
Is it essential to have the ETHOS logo on all screens?

**Comment by Wolepo** [comment]
It's not that serious, but it can be hidden here if necessary.

**Comment by philippe-warnotte** [comment]
Ok. A bientôt pour la version 1.5.10

**Comment by bsongis-frsky** [comment]
Euh, si vous fermez les issues avant que je n'aie le temps de les traiter, vous prenez le risque qu'elles passent à la trappe ...

**Comment by philippe-warnotte** [comment]
Voilà,  j'ai rouvert. Bonne journée.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/7754781d-d0c0-4bcd-acfb-4e001bfbb56f)

**Comment by philippe-warnotte** [comment]
Superbe!

**Comment by bsongis-frsky** [comment]
Other bug fixed ... the buttons text is not correctly cut. Now the result:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/893c79d4-5c50-4316-b5e8-975c54d97e25)

**Comment by philippe-warnotte** [comment]
Perfection
