### ISSUE TITLE
Sounds on the SDCard

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#4165]
Good morning 
I am using 1.5.9 and all is well except a soung slight issue.
My Tx system (Horus X10 exp) uses a french language and the sounds are also in French.
Some sounds are missing (i.e StabLvl for inst.).
I can find them on the Sdcard 'files' index all right but they are not suggested as possibilities in the menus for Special functions.

So my question is: how to get to use those sounds which are on the Sdcard but don't appear ?

**Comment by spoke2570** [comment]
I recommend the [manual](https://raw.githubusercontent.com/FrSkyRC/ETHOS-Feedback-Community/1.5/doc/%5BEN%5D%20Ethos%20User%20Manual%201.5.8.pdf). it has very detailed information about this starting on page 37.
