### ISSUE TITLE
GPS alt sensor

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4169]
Hello Bertrand.
I have found a way to display the flight track in Google Earth. To do this, I load the log into an Excel file, merge the two entries latitude and longitude into "GPS" and remove the comma between the two coordinates. However, the GPS Alt sensor is set to 0m by default, i.e. to altitude above ground, e.g. 532 → 0m. However, this means that the flight track is drawn below the surface and is therefore not visible. If you delete this sensor and use a DIY sensor instead, the value is created above NN (normal zero) and everything is fine.
Now my request: is it possible to configure GPS Alt so that it normally outputs the value above NN, but when it is reset, it outputs the value above ground. So you have the choice between both sensors. Unfortunately, creating both values at the same time does not work.
Thank you very much for your interest
Wolfgang
 

*** Translated with www.DeepL.com/Translator (free version) ***

**Comment by bsongis-frsky** [comment]
1.5.10 logfiles will have only one column for GPS. They can be imported in Google Maps directly

**Comment by Wolepo** [comment]
What happens with GAlt? This must output the GPS altitude above sea level so that the flight track does not remain underground.

**Comment by noamkrief** [comment]
I wrote a simple php script to take the csv from the radio and create the kml file for google earth. If you want it in 3D and see the elevation, you must include ALT.

There is an even better software (payware) called tacview that can import a csv with more parameters such as roll / pitch angles and display your flight path + graphs.

**Comment by dwheeld** [comment]
I would like to see an option to have the GPS altitude either automatically offset to zero, or provide actual altitude above sea level.  Please consider this for future Ethos updates.

**Comment by Wolepo** [comment]
Is already finished and comes in 1.5.13. See https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4201

**Comment by bsongis-frsky** [comment]
Yes. Done in 1.5.14 as requested in #4201
