### ISSUE TITLE
v1.08 Sound and playback "once" is ignored more badly

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#417]
As I already mentioned,

If a logic state is set, and triggers a special function Playback Track.. the track will be triggerd over and over again while the logic state is set. the option playback once is ignored.

Unless the logic state is pulsing in software. not steady.

SF2 plays back "SD Logging ON" when set active.

https://youtu.be/Q3eQcpDGJhA

**Comment by bsongis-frsky** [comment]
What is your LSW3?

**Comment by Hobby4life** [comment]
Edge function.   SI down 1.0-20s

**Comment by bsongis-frsky** [comment]
Is it still KO in 1.0.9 candidate 1?

**Comment by Hobby4life** [comment]
> Is it still KO in 1.0.9 candidate 1?

Seems ok now.. I will have to test further to be sure.
