### ISSUE TITLE
X20 Pro AW with TW SR8   1.5.9 Telemetry display is faulty.  1.5.6 Correct display. Everything ok.

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#4170]
X20 Pro AW 

1.5.9 Telemetry display is faulty. 
Data constantly changes between value and three red minus signs, no altitude works with TW SR8. 
Constant message Sensor lost.

1.5.6 Correct display. Everything ok.

----------------------
Current firmware version on transmitter and receiver from FrSky Homepage
X20Pro AW:  2024-03-12 | TD Pro1.1.13 | 1.The first firmware for newly released products.

TWSR8:  2023-12-25 | v1.0.6 | 1.The first firmware for newly released products.

**Comment by bsongis-frsky** [comment]
Are you sure? Because I don't believe something has changed in Ethos between 1.5.6 and 1.5.9 in this area!

**Comment by hrenz** [comment]
Can be deleted
Colleague has the switch for telemetry reset permanently activated
Then the telemetry gets confused

**Comment by xfly21** [comment]
I own a tandem xe-s FCC with bluetools audio and trainer but I noticed two big problems.
1. the ethos suite does not recognize the XE-S tandem but only the XE.
2. by installing any XE-S firmware version the software language is only in English with no other choice. to have the language you want I only have to install firmware for XE losing the Bluetooth audio. you have to solve these problems.
