### ISSUE TITLE
V20  1.5.9 It is not possible to open a screenshot file in full screen

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4171]
V20  1.5.9 It is not possible to open a screenshot file in full screen. Currently, "open" is of no use.

**Comment by bsongis-frsky** [comment]
Until 1.5.9, "Open" does nothing.

Bitmaps will be open in 1.5.10, here the result

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a61fd929-7f33-4da8-99b4-2511ab601a4b)

**Comment by philippe-warnotte** [comment]
Beautiful! And the screenshots too?

**Comment by bsongis-frsky** [comment]
Yes. Just show a screenshot of a screenshot won't mean anything :)

**Comment by philippe-warnotte** [comment]
Ok, but then, what's the point of a screenshot if you don't know how to display it. except with a PC... ;)

**Comment by bsongis-frsky** [comment]
I said "Yes" ;)
