### ISSUE TITLE
 enable or disable special functions with a switch or logic switch.

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#4172]
I would like the ability to enable or disable special functions with a switch or logic switch.

On my competition gliders, I have set up various warnings, such as low or critical battery alerts. Sometimes, these warnings interfere with my timers, so I want to be able to turn the warnings off when I need to.

If this feature is introduced, I can use one switch or logic switch to disable a number of warnings without having to create numerous AND logic switches.

Kind regards,
Steven

**Comment by mawzthefinn** [comment]
Why not use the Active Conditions on the LSW's firing these Logical Switches to disable the LSW's instead of the SF's?

You can enable/disable processing of LSW's via Active Condition without affecting the logic portion of the LSW.

**Comment by 00steven** [comment]
true , brain fog today completley overlookt it

**Comment by Wolepo** [comment]
Why do warning messages interfere with the timers?

**Comment by mawzthefinn** [comment]
> Why do warning messages interfere with the timers?

Higher priority notifications will result in the timer voice playback being delayed.

**Comment by Wolepo** [comment]
Then the warning messages disturb the time announcements and not the running of the timers

**Comment by 00steven** [comment]
True, timers run but count down is disturbed

**Comment by spoke2570** [comment]
That topic is #2791 and definitely needs to happen.
