### ISSUE TITLE
Possibility to recognize Ext1/Ext2 analogs as 3-position switch

### ISSUE THREAD

**Issue by jiristasek** [FrSkyRC/ETHOS-Feedback-Community#4173]
Hello,
i am looking for possibility about connecting 3-position switch instead of an analogs Ext1/Ext2, example on diagram(Gimbal switches).
![Gimbal](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/49921905/d0e83b81-eb3a-4122-836d-8f56ef64b374)

Is there any possibility for Ethos to recognize analog ext1/ext2 as a switch? If not this could be a good feature.
This connection has a disadvantage - in middle position an input signal is not stable, a possible way to avoid this error would be to use an external voltage divider, but this is not very user-friendly (tolerance of resistors, etc.)

Thank you for your work and effort.
Jiri.

Ethos1.5.9 EU

**Comment by mawzthefinn** [comment]
Any Analog can be used as a 3-pos via s set of LSW's, but those would have to be created per model.

**Comment by Wolepo** [comment]
I have connected a resistor of 5 kiloohms between GND and ADC1, as well as ADC1 and VREF. This places the centre switch pin at a safe potential and there is no longer any noticeable delay. Nevertheless, it remains the same: 3 LS must be created for the switch positions.
