### ISSUE TITLE
TD SR10 does not recognize the MLVSS sensor

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4174]
I am not able to have the X18 Transmitter discover the MLVSS sensor using the new TD SR10 receiver. This sensor works without problems with the SR10 Plus, SR Pro, and the X8R receiver.
Please, help.

**Comment by FrSky-GX** [comment]
If you haven't update FW for the MLVSS after got it, it may ran the old FW which have problems with Tandem Rx. https://www.frsky-rc.com/mlvss/

**Comment by Richrfl** [comment]
Dear FrSky, in my post I indicated I am using an X18 transmitter. I apologize, I thought it would be assumed it is a Tandem series. I also mentioned the two stabilized receivers I was using the MLVSS with. I also assumed that it was understood (my wrong) that that fact indicated that the MLVSS FW was already updated to the latest version (two years ago). It is because of all that, that indicated that the problem is focused on the TD SR10 itself, or in some wrong configuration I did when I set it up. Later today I will hook up one FrSky GPS to have a better idea of the operation of the S.Port. Needless to say all servos and stabilization are in good working order. BTW, the X18 is running 1.5.9 and the TD SR version is 1.0.11

**Comment by mawzthefinn** [comment]
How are you wired in? The 4-pin port is upgrade/AIN, you need to assign a Channel Port to s.port and plug the MVLSS in to that channel port

**Comment by Richrfl** [comment]
I wired it to the 4 pin AIN. Will try to use a channel port as you
suggested. Can you explain what about the upgrade of the 4 pin connector. I
need the 10 ports to control servos.

**Comment by mawzthefinn** [comment]
Upgrade as in wired updating of the receiver firmware.

If you need all 10 ports for servos, plus a port for telemetry, you should be using a TD SR12 instead of the TD SR10. That has 12 channel ports available, leaving one extra. Only the 6 & 8 port receivers have active S.Port/FBus on the 4/6 pin header. 

With the 10 port and up receivers, they are ports, not channels. All in-aircraft functionality except AIN needs a port available. Most of the newer 10+ port receivers have the 4-pin port labelled as Upgrade for good reason.

**Comment by Richrfl** [comment]
Thank you for the clarification. As a side note, I think that the manual should clearly state that the 4 Pin is "Only for FW upgrade", given that the SR 10s have telemetry in the 4 pin port.
With that clarified, I assigned the S.Port to pin 9, the MLVSS LED shows it is connected to the port and the battery (slow flashing). However, the TX is still not discovering the sensor.
![IMG_20240619_102714650_HDR](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/b3b92bc9-bb84-41b3-9da4-05670e2e8520)
![IMG_20240619_103110769_HDR](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/98c94ff3-e6c8-473b-9018-3161a0c8bbac)
![IMG_20240619_101640105_HDR](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/aefdbef2-eec8-451b-a2c0-372e43d54b8b)
![IMG_20240619_101631237_HDR](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/8b63eda3-b0bf-4718-a910-c3755ae0e854)

**Comment by mawzthefinn** [comment]
Then you also have old firmware on the MVLSS, as the old firmware will behave in exactly that manner on a channel port assigned to SBus. It's a firmware bug on the MVLSS that only shows up when used on a channel port (because these receivers require stricter S.Port timing to work).

**Comment by Richrfl** [comment]
Thank you mawz. I checked that the GPS was working ok in this new setting, therefore, (even I cannot explain what kind of a mess I made, because I have only one MVLSS, and it was working with the other receivers), I updated the FW to the latest version and now it is working with the TD SR.
