### ISSUE TITLE
X20RS TTS don't work properly with capital letters

### ISSUE THREAD

**Issue by rafaelbiriba** [FrSkyRC/ETHOS-Feedback-Community#4175]
For example for the text "throttle cut" (all in capital letters) it reads as "throttle C - U - T", literally it reads C, and then U, and then T.

Video here: https://www.facebook.com/groups/frskyethos/posts/702312595320639/?comment_id=702318118653420&reply_comment_id=702372275314671

**Comment by mawzthefinn** [comment]
This is expected behaviour. Lower case reads the word, upper case treats it as an acronym
