### ISSUE TITLE
Simulator for Linux

### ISSUE THREAD

**Issue by MiANat** [FrSkyRC/ETHOS-Feedback-Community#4176]
I have installed the simulator for Linux for the X20S (Nightly 1.5.10) under Linux MX-23.3. There are problems with the authorizations. Obviously nothing can be saved as a standard user.
![linux_mx_simulator_storage_error](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/173248876/d9ebc7f1-9e67-4919-a0a9-047f7e4388f4)
Michael

**Comment by mawzthefinn** [comment]
You'll need to fix permissions for the selected storage folders.

**Comment by MiANat** [comment]
... folder /usr/share/ethos has already read and write permissions. Any folder else?

**Comment by MiANat** [comment]
On the subject of authorizations: The simulator must work after installation without any further adjustments, especially changes to the authorizations. :-)

**Comment by Merga189** [comment]
I would say, that after the installation of the *.deb package as 'root' (or 'sudo'), starting the SIM, configuration and saving and loading models should be possible as 'user'. Any modification of folder permission should not be necessary at all.

**Comment by bsongis-frsky** [comment]
I am not sure that it's a good idea to give R/W permissions to something in /usr

**Comment by MiANat** [comment]
That's my opinion too. The OTX Companion + OTX Simulator has also been running on my system for some time. Without special authorizations. I think the ETHOS simulator should also be able to function without unnecessary authorizations.

**Comment by Merga189** [comment]
> I am not sure that it's a good idea to give R/W permissions to something in /usr

Definitely NOT! I am still using on Debian OTX 2.3.15 and the *.deb package places the executable files companion23 and simulator23 in /usr/local/bin/. But all the necessary rest like Companion 2.3.conf, backups etc. is placed in /home/user/

NOT necessary, to change permissions. Just install the *.deb package as root or sudo.

With EdgeTX for me things are a bit easier as there is an appimage available, which can be placed as one likes ... /home/user/ or /opt/ ....

Offering an appimage would circumnavigate any problems.

br Karl

**Comment by bsongis-frsky** [comment]
I am fixing things properly in 1.5.10
Then I will read about appimage, which I don't know

**Comment by MiANat** [comment]
Installed the actual (2024-06-23) version of sim for x20s. Now it's possible to save some data. Installation was started from terminal with "sudo apt-install...".
Found directory "/home/<username>/.ethos", but why it is hidden? Copied some modell bins into the folder "./ethos/X20S/models". But where to put for example audio-files, scripts? There is still the directory "/usr/share/ethos/..." with only access for root. Should be possible to copy sounds + scripts without special rights.

**Comment by Merga189** [comment]
"/home/user/.ethos/" is totally normal for configuration files under Linux.

**Comment by MiANat** [comment]
Tested the actual version for x20pro today. There's only one thing left: where to put user defined soundfiles? At the moment they need to be in ./share/ethos/x20pro/audio/<language>/<dir name>/. This needs special permission....

**Comment by bsongis-frsky** [comment]
Right, it remains something to do for audio. I plan to create a folder .ethosXXX/audio, then for each language create a lot of dynamic links

I keep this issue open for 1.5.11

**Comment by MiANat** [comment]
That's fine. Looking forward to it ...

**Comment by bsongis-frsky** [comment]
Fixed for 1.5.10
