### ISSUE TITLE
Telemetry with smooth flite sixteen

### ISSUE THREAD

**Issue by andrescuadrosjdc** [FrSkyRC/ETHOS-Feedback-Community#4177]
Constantly sensor lost messages coming from the FS16
Basically from the voltage sensors
Anything is up to date
sF16, TDMX, TX
Using 2 TDMX with the sport linked
![IMG_5422](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/04e72062-d1f5-42b6-90bb-febb1f57303b)

**Comment by bsongis-frsky** [comment]
Which sensors are connected? Have you checked they have different appID / physID?

**Comment by andrescuadrosjdc** [comment]
Hello
This is what I have
X20pro on 1.1.13 and X20S on 2.2.6 (both with the same sensor lost problem)
2 TDMX 1.6 on 1.0.13

1 SF 16 on
1 GPS Adv
1 RDT Zavionics for KT turbine (last FW)

My connections are
RDT to GPS, GPS to SF16 and finally thru a Y cable to both SPort connectors:
Have checked and all are in different appIDs 
The problem persists, more with the SF16 connection

![IMG_5433](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/81274821-e696-47b0-9035-542d1e80ba89)
![IMG_5434](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/b8cf40e0-ef98-44b5-94df-3dd3226447e3)
![IMG_5437](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/c70c6364-be2a-4159-9214-3700aae47c93)
![IMG_5438](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/22e7d79a-0d0a-42c4-9f2d-65ff9aee901f)
![IMG_5439](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/21aa9b11-61a5-4bb9-999f-59880d13c775)
![IMG_5440](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/c084137f-ec44-42ae-ac56-faccb721c764)
![IMG_5441](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/53270018-2241-4e4c-96af-0a2479480b26)
![IMG_5442](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/81a7c643-02f5-4f55-b39c-329f60f70908)
![IMG_5443](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/0c458c3c-5f45-4d07-9ee8-cc49fb241449)
![IMG_5444](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/c0670246-23f4-4e9b-bcdf-982798d2cf72)

**Comment by andrescuadrosjdc** [comment]
> Constantly sensor lost messages coming from the FS16 Basically from the voltage sensors Anything is up to date sF16, TDMX, TX Using 2 TDMX with the sport linked ![IMG_5422](https://private-user-images.githubusercontent.com/89352761/341560593-04e72062-d1f5-42b6-90bb-febb1f57303b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzQ5OTQsIm5iZiI6MTcxOTc3NDY5NCwicGF0aCI6Ii84OTM1Mjc2MS8zNDE1NjA1OTMtMDRlNzIwNjItZDFmNS00MmI2LTkwYmItZmViYjFmNTczMDNiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxOTExMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDEzZjcxMDUzNGQ1YjQxZWJhN2YxYTk5NDYzNDYyMzg2YjRkMzlhMWU0NGI1ZDY0ODc1YzY5NGRmNTZjZmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2dL_FoKw_QyR94yLbrR1t4f_2TkpsVvlns5FmrGxaoY)

This is the info I have
regards
