### ISSUE TITLE
Receiver can be bound by all transmitters in sharing mode

### ISSUE THREAD

**Issue by Peterbilt84** [FrSkyRC/ETHOS-Feedback-Community#4178]
If the Share button is clicked for a receiver, the receiver can also be bound by transmitters that have a different registration ID and by transmitters that have not even been registered with the receiver before. The receiver can thus be bound by any sender. The test was carried out with an SR10+ receiver.

It is therefore not possible to specify which sender may or may not take over the receiver in share mode.

**Comment by Dsrenger** [comment]
Isn't that exactly how the share button is supposed to work? 
The clou of the share button is, that you can share with every transmitter regardless of the reg ID.

That's my understanding

**Comment by strgaltdel** [comment]
As far as I can remember, the first description of the share function was on rcg. 
The process described a "hand over" from one transmitter to another. 
Lothar's description reads the same way ("Radio A >> Radio B"), at least for me. 

maybe there was some "loss in translation / communication" between RF engineers and other people from very first day?
I guess this topic came up the last days by the group of "functional models builder" in the german forum too

It is understandable to me that the user would utilize this function with the expectation that the model would then only be controlled by the target transmitter. The big question is, what were the FrSky RF technicians aiming to achieve? 
So, in my opinion, either the documentation should be adjusted or the share functionality...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/e7d629af-3a05-4a8d-922a-99abafb2940d)

**Comment by pmullen503** [comment]
It looks like you have to have TX A put the receiver in share mode and TX B bind to it. It's not like just any TX can grab control once it's bound to TX B, or is that not the case?

**Comment by Peterbilt84** [comment]
In my opinion, it is still dangerous that all transmitters can bind a receiver in share mode. If that was the intention, then it would be nice if the "option" was added to only be able to bind receivers with the same Reg ID in share mode.

Example from the field of functional model making. At an event, the members of a club display their models in share mode. The vehicles then wait in standby mode for a colleague to take over the vehicle. Now it would be important that only colleagues of the club can bind the model and not all other people at the event. I hope you understand why the share mode is too dangerous at the moment.

**Comment by pmullen503** [comment]
How is the share process any different from systems that don't have registration/bind steps? When you put a receiver into bind mode, any TX can bind it.  Once bound, no other TX can take it over.

**Comment by Peterbilt84** [comment]
With other systems, for example, you have to set a jumper to be able to bind the receiver. Or you press the bind button on the receiver. So you have to be directly at the model to be able to bind it. That is the big advantage of share mode. You can hand over the model without having to touch it. The only thing missing now is the security that no one else can take over the model.

**Comment by robthomson** [comment]
Even with sharing you have a 2 step bind.

Share only says that the rx in question is 'allowed to bind'

**Comment by mawzthefinn** [comment]
Closing as this function is as designed.

Note that if you want to control which transmitter can bind the receiver, use a normal bind method and maintain the same Owner Registration ID on both transmitters. Without engaging Share, the receiver will bind only to a transmitter with an Owner Registration ID it knows when bind is triggered. I use this regularly to share models between my transmitters.
