### ISSUE TITLE
Enhancement: Timer Play Value add steps for 2 minutes and 5 minutes

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#4179]
As an enhancement is it possible to add steps to the Timer->Audio Action->Play Value for 2 minutes and 5 minutes, maybe even 10 minutes. This is helpfull to announce flight times with longer intervalls at longer thermal flights. 60 second steps are too short.
 
![Fluguhr 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/87366576-c157-4c7f-a53b-2d06ee2e9413)

![Fluguhr 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/8e77f520-6869-445b-b4e5-3abcb0407b9d)

**Comment by bsongis-frsky** [comment]
Perhaps you can just create more actions, like on this screenshot:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0369c9a9-b5af-42e4-8b06-fc5414c4f951)

**Comment by glipski50** [comment]
Thanks for your response. Maybe my explanation was missleading. Your suggestion just defines a start time for the timer.

I want to setup a timer starting at 00:00:00 and counting up. For longer thermal flights this timer should play the timer value every 5 minutes to the full minutes, like 5 minutes, 10 minutes, 15 minutes ….. 1 hour 5 minutes and so on until the timer is stopped. There is no max time defined, just counting up. 

I thought the step function of the play value action would be the easiest way if it would have steps defined for 2 minutes, 5 minutes. With a spezial functio the repeat time is max 2 minutes (120 seconds).

**Comment by bsongis-frsky** [comment]
I defined a start time for the callout, not the timer!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9ad7952e-b524-4748-abc2-74a8857e5079)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/45dffde0-25d8-4f8b-be12-e67d4a327b18)

**Comment by bsongis-frsky** [comment]
Maximum is set to 10 minutes.
The same change is applied to Model / Functions:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/55d39a9c-d8e5-4c65-84b9-3756311eadb6)

**Comment by glipski50** [comment]
Perfect. Thanks Bertrand.
