### ISSUE TITLE
V 1.0.8 Play Value Channels now is ms instead of %

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#418]
in V 1.0.7 the value for Channels were played %...

**Comment by bsongis-frsky** [comment]
I just checked, I have % as unit! Which is your language, perhaps your prompt is not right?

**Comment by bsongis-frsky** [comment]
```
038362 [en] playNumber(0, unit=%, precision=0)
038362 playFile('/audio/en/system/0.wav', flags=0, id=0)
038362 playFile('/audio/en/system/percents.wav', flags=0, id=0)
```

**Comment by bsongis-frsky** [comment]
In DE:
```
152531 [de] playNumber(0, unit=%, precision=0)
152531 playFile('/audio/de/system/0.wav', flags=0, id=0)
152531 playFile('/audio/de/system/percent.wav', flags=0, id=0)
```

**Comment by Cipta-de** [comment]
Hello Bertrand,
I have X20S English.
What do you mean with prompt?


Herzliche Grüße und einen schönen Tag noch wünscht


Roland Schäfer



Mobile:+49 17696614767

Mail:    ***@***.***



schau doch mal auf meiner Webseite nach neuen Fotos www.cipta.de


Bertrand Songis @ FrSky ***@***.***> schrieb am Mo., 7. Juni
2021, 20:03:

**Comment by Cipta-de** [comment]
sorry sorry sorry my foult with the gyro - at the calibration you have to go back each time to the "click when done" button - I just confirmed with next :

**Comment by bsongis-frsky** [comment]
Perfect. I am releasing a 1.0.9 in a couple of minutes. With only bugfixes, I don't want to take any risk
