### ISSUE TITLE
arrow ↑ and down arrow ↓ cannot be displayed with lcd.drawText under 1.5.10

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#4180]
Up arrow ↑ and down arrow ↓ cannot be displayed with lcd.drawText under 1.5.10

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/7b1a9dee-beb1-408c-931a-0384f5781e3b)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/b09046f8-f808-4357-8257-4ced764645ef)

**Comment by Benno00** [comment]
under 1.5.6 it still worked
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/4d44b903-154f-463f-a7e9-ec487e408eb1)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/7f9caf6d-17fe-460d-a09d-554334c6b078)

**Comment by bsongis-frsky** [comment]
Do you know which release broke it?

**Comment by bsongis-frsky** [comment]
Would you please paste the code which you use to display these special chars?

**Comment by Benno00** [comment]
the problem exists between 1.5.7 and 1.5.8

in this version works fine
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/21f143fd-c404-4555-85ae-e0eb623e38f5)


I show the switch name that is read from the system, in debug mode
SAÃ, SA- and SA╔ are delivered, I read it with

        me = system.getSource({category=CATEGORY_SWITCH_POSITION, member=1})
	print("Source Name:",me:name())
	me = system.getSource({category=CATEGORY_SWITCH_POSITION, member=2})
	print("Source Name:",me:name())
	me = system.getSource({category=CATEGORY_SWITCH_POSITION, member=3})
	print("Source Name:",me:name())

from the Debug Screen
Source Name:    SA-
Source Name:    SA╔
Source Name:    SBÃ

it works in ths Version 
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/6bcc76b8-e6ab-414c-9acd-3b801cd2246e)
in this version will it not work
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/a1e47d4c-d085-4e59-b4c5-b472171107f5)

**Comment by Benno00** [comment]
on my transmitter X20S it no longer works with version 1.5.9 #046c37fe from 22.05.2024

**Comment by Benno00** [comment]
Hi,
her is my source 
```lua
-- Lua LCD demo widget

local bitmap, mask
local sys=system.getVersion ()
local function paint(widget)
    local w, h = lcd.getWindowSize()
	lcd.color(COLOR_WHITE)
	lcd.font(FONT_STD)
	
	lcd.drawText(10,1,"Bord: "..sys.board.." Version: "..	sys.version)
	for i=0,8,1 do 
		source=system.getSource({category=CATEGORY_SWITCH_POSITION, member=i})
		
		print("source name:",source:name(), "state:",source:state(), "value:",source:value())
		if source:state()~=nil then 
			if source:state()==true then 
				me=system.getSource({name=string.sub(source:name(),1,2)})
				tx=source:name().."  Aktiv".."  value: "..me:stringValue ()
				if string.sub(source:name(),1,2)=="SA" then 
					lcd.drawText(10,30,tx)
				end
				if string.sub(source:name(),1,2)=="SB" then 
					lcd.drawText(10,60,tx)
				end
				if string.sub(source:name(),1,2)=="SC" then 
					lcd.drawText(10,90,tx)
				end
			end
		end
	end	
end

local function wakeup(widget)
	if lcd.isVisible()==false then
		return true
	else
		lcd.invalidate()
	end
end

local function init()
    bitmap = lcd.loadBitmap("FLASH:/bitmaps/system/Archer+SR12+.png")
    mask = lcd.loadMask("FLASH:/bitmaps/system/mask_dot.png")
    system.registerWidget({key="lcddemo", name="Lua LCD Demo", paint=paint, wakeup=wakeup})
end

return {init=init}
```

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/3663deaa-555b-4e29-a8ad-6362d882f635)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/dc2538a5-42d1-45ff-8de3-45e31a50ad3f)


![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/b58fc11e-9f39-48d7-8c08-86fc9c7d3f81)

**Comment by Benno00** [comment]
here as ZIP file
[lcddemo.zip](https://github.com/user-attachments/files/15935743/lcddemo.zip)

**Comment by bsongis-frsky** [comment]
It should be fixed in current nightlies, please confirm when you can!

**Comment by Benno00** [comment]
Hi Bertrand,
the new X20S simulator is not running, it can no longer load scripts
here is the error message:
001100 f_opendir(C:/Users/benno/.ethosX20S/scripts) = error 2 (No such file or directory)
001100 WD suspended
001100 ModelData::read('/models/Heli/model06.bin')
←[31m001101 Lua widget key 'BJ' not found←[0m
←[31m001101 Lua widget key 'swmap' not found←[0m
←[31m001103 Lua widget key 'CO-WERT' not found←[0m
←[31m001103 Lua widget key 'CO-WERT' not found←[0m
←[31m001103 Lua widget key 'B1' not found←[0m
←[31m001103 Lua widget key 'BJLOG' not found←[0m

this is what it looked like so far
001108 Lua::load('/scripts/Schalter/main.lua')
001110 Lua::load('/scripts/Sendernutzung/main.luac')
001111 Lua::load('/scripts/shutdown/main.lua')
001113 Lua::load('/scripts/swmap/main.luac')
SWMAP RADIO:X20

**Comment by Benno00** [comment]
Hi Bertrand,

the new X20S simulator is not running, it can no longer load scripts
here is the error message:

001100 f_opendir(C:/Users/benno/.ethosX20S/scripts) = error 2 (No such file or directory)
001100 WD suspended
001100 ModelData::read('/models/Heli/model06.bin')
←[31m001101 Lua widget key 'BJ' not found←[0m
←[31m001101 Lua widget key 'swmap' not found←[0m
←[31m001103 Lua widget key 'CO-WERT' not found←[0m
←[31m001103 Lua widget key 'CO-WERT' not found←[0m
←[31m001103 Lua widget key 'B1' not found←[0m
←[31m001103 Lua widget key 'BJLOG' not found←[0m
 

this is what it looked like so far
001108 Lua::load('/scripts/Schalter/main.lua')
001110 Lua::load('/scripts/Sendernutzung/main.luac')
001111 Lua::load('/scripts/shutdown/main.lua')
001113 Lua::load('/scripts/swmap/main.luac')


Kind regards

Benno Jurisch

 

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Donnerstag, 27. Juni 2024 08:28
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] arrow ↑ and down arrow ↓ cannot be displayed with lcd.drawText under 1.5.10 (Issue #4180)

 

It should be fixed in current nightlies, please confirm when you can!

**Comment by bsongis** [comment]
`001100 f_opendir(C:/Users/benno/.ethosX20S/scripts) = error 2 (No such file or directory)`

You have removed your scripts directory?

**Comment by Benno00** [comment]
Hi Bertrand,

 

no I haven't moved or deleted anything, the scripts still run under this version

 



 

 

 

Von: Bertrand Songis ***@***.***> 
Gesendet: Donnerstag, 27. Juni 2024 12:00
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] arrow ↑ and down arrow ↓ cannot be displayed with lcd.drawText under 1.5.10 (Issue #4180)

 

001100 f_opendir(C:/Users/benno/.ethosX20S/scripts) = error 2 (No such file or directory)

You have removed your scripts directory?

**Comment by Benno00** [comment]
Hi Bertrand,

 

problem found the scripts must now be under User, but the arrows are still not displayed

 



 



 



 

 

 

 

Von: Bertrand Songis ***@***.***> 
Gesendet: Donnerstag, 27. Juni 2024 12:00
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] arrow ↑ and down arrow ↓ cannot be displayed with lcd.drawText under 1.5.10 (Issue #4180)

 

001100 f_opendir(C:/Users/benno/.ethosX20S/scripts) = error 2 (No such file or directory)

You have removed your scripts directory?

**Comment by bsongis-frsky** [comment]
Do you confirm you tried Ethos 1.5.10, the latest nightly?

**Comment by Benno00** [comment]
Hi Bertrand,sorry no, the Version from 24.06.2024 works, so i think it ist broken beetwen 24. and 26.06.I have Download Yesterday that Version Had have the thame error Message of today  Von: Bertrand Songis @ FrSky ***@***.***>Gesendet: Donnerstag, Juni 27, 2024 6:59:38 PMAn: FrSkyRC/ETHOS-Feedback-Community ***@***.***>Cc: Benno Jurisch ***@***.***>; Author ***@***.***>Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] arrow ↑ and down arrow ↓ cannot be displayed with lcd.drawText under 1.5.10 (Issue #4180)
Reopened #4180.

**Comment by bsongis-frsky** [comment]
It will be fixed for sure in the next nightlies:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/00df0be6-0170-48a1-81e8-6a17a4be9800)

**Comment by bsongis-frsky** [comment]
The print on console are good too now:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8deb5420-2785-476b-badb-c349b71f8025)

**Comment by Benno00** [comment]
Hi Bertrand,

that looks good, Thank you

 

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Freitag, 28. Juni 2024 09:45
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] arrow ↑ and down arrow ↓ cannot be displayed with lcd.drawText under 1.5.10 (Issue #4180)

 

The print on console are good too now:

image.png (view on web) <https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8deb5420-2785-476b-badb-c349b71f8025>

**Comment by Benno00** [comment]
Hello Bertrand,
i was able to test it successfully today with the X20PRO Simulator
Thank you very much

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/672e2bea-d375-40e5-9dd4-cca4b6befc06)
