### ISSUE TITLE
V20 1.5.9 library Mixes

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4181]
Library Mixes: The mixes that use ailerons+Flaps+Elevator (Airbrake, Butterfly, Camber, Free Mix) do not have the "Slow up, Slow Down" function.
Only the FLAPS mixer can be used to slow down the mixer.

**Comment by mawzthefinn** [comment]
This is as expected, butterfly and camber are intended to be used with an analog input (spoiler stick or a slider)

free mix does have slow available, it must be added as an action.

airbrake is simply an offset mix renamed.

**Comment by philippe-warnotte** [comment]
Sorry, ok for "Free Mixer", I forgot "Action". 
For a Jet plane, I use a 3-position switch for the flaps or flaperon(camber). Easier than a slider. If the flaps down quickly, they are torn off!.

**Comment by mawzthefinn** [comment]
Use a second flaps mixer for Flaperons. Camber is intended as a fine camber control mixer for sailplanes

**Comment by philippe-warnotte** [comment]
Thanks you
