### ISSUE TITLE
Different names for each of the distributed and downloadable lua apps.

### ISSUE THREAD

**Issue by m-rik-prog** [FrSkyRC/ETHOS-Feedback-Community#4182]
With the X18 and X20 transmitters in our possession, the apps work whether they are in the Scripts folder with their own specific name (EG: mickeymouse.lua) or whether they are inside a subfolder but all renamed main.lua (for precompilation).
Therefore, in order to differentiate them from the others, we give to the precompiled version a specific name by telling users to upload them to the Scripts folder.
Some users who are in possession of the 'RS' versions of the transmitters (X20RS) report to us that with the ETHOS version of their transmitters, precompiled apps uploaded directly into the 'Scripts' folder with a specific name of their own DO NOT WORK, but only work if they are moved into a sub-folder and renamed 'main.lua' (as must be done for app precompilation).
It therefore seems that the ETHOS versions for "RS" transmitters have this problem, which prevents the precompiled apps from being distributed with their own specific name but forces them all to be distributed with the exact same name "main.lua" with the high risk that they can be interchanged and confused with each other since they all have the same name.
We don't know how the firmware of the other countless ETHOS versions ('R', 'S', 'HD', 'PRO', 'PRO AW', 'XE', etc.) behave.

**Comment by bsongis-frsky** [comment]
Why don't you distribute a ZIP file to your customers?
All radios work the same

**Comment by m-rik-prog** [comment]
I already now distribute a Zip file containing the LUA app, its image, the pdf manual, the release notes and the help markdown file (which are not completely displayed but stop halfway through as explained here in another thread).
The problem is to distribute and install completely different applications on the transmitter which all have to be called with the same name "main.lua" and cannot be distinguished from each other by the name with the risk of great confusion and misuse by users and which, only with the ETHOS versions for X20RS no longer work if uploaded to the root /scripts  as can be done with the ETHOS version for X18 and X20 but have to be placed in a folder.

As I explained at the beginning and as can easily be verified, the behaviour of the ETHOS versions for X20RS is different from the ETHOS versions for X18 and X20.
If you do not want to fix the ETHOS version for X20RS to work like ETHOS for X18 and X20, then you will have to fix the ETHOS versions for X18 and X20 so that they also work like ETHOS for X20RS.
