### ISSUE TITLE
Problem with firmware for Tandem XE-S FCC:

### ISSUE THREAD

**Issue by xfly21** [FrSkyRC/ETHOS-Feedback-Community#4184]
I own a tandem xe-s FCC with bluetools audio and trainer but I noticed two big problems.
1. the ethos suite does not recognize the XE-S tandem but only the XE.
2. by installing any XE-S firmware version the software language is only in English with no other choice. to have the language you want I only have to install firmware for XE losing the Bluetooth audio. you have to solve these problems.
Paolo paolo_pi@alice.it

**Comment by mawzthefinn** [comment]
1. Radio is recognized by the bootloader installed. Flash the XE-S Bootloader (it's in the 1.4.15 assets) and it should be recognized correctly.

**Comment by xfly21** [comment]
I always install firmware from bootloder but the software remains only in English only with XE-S FCC firmware while with XE FCC firmware it is multi language software why this problem please PaoloInviato da iPhoneIl giorno 23 giu 2024, alle ore 01:50, mawzthefinn ***@***.***> ha scritto:﻿

Radio is recognized by the bootloader installed. Flash the XE-S Bootloader (it's in the 1.4.15 assets) and it should be recognized correctly.

**Comment by xfly21** [comment]
I always install firmware from bootloder but the software remains only in English only with XE-S FCC firmware while with XE FCC firmware it is multi language software why this problem please 
Paolo

**Comment by gmarconi2** [comment]
This is the screenshot of Paolo's Ethos Suite from XE-E
![Screenshot 2024-06-23 135729](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8461317/f1d35fd0-0ca2-4c47-9164-694cd03eb0a0)

**Comment by mawzthefinn** [comment]
> I always install firmware from bootloder but the software remains only in English only with XE-S FCC firmware while with XE FCC firmware it is multi language software why this problem please PaoloInviato da iPhoneIl giorno 23 giu 2024, alle ore 01:50, mawzthefinn ***@***.***> ha scritto:﻿ Radio is recognized by the bootloader installed. Flash the XE-S Bootloader (it's in the 1.4.15 assets) and it should be recognized correctly. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

You have the XE bootloader installed, so the radio detects as an XE, you need to install the XE-S bootloader to get Suite to recognize the radio as an XE-S

**Comment by xfly21** [comment]
I solved the problem of the Tandem XE-S that the software is only in English. the problem thanks to Marco who helped me is neither the firmware nor the bootloder but the ethos suite which when you update obsolete files wants you to select and update all the languages ​​and not just the desired ones because the default suite sets only English instead when selecting all the languages everything works with desired software language and chosen audio.

**Comment by xfly21** [comment]
I solved the problem of the Tandem XE-S that the software is only in English. the problem thanks to Marco who helped me is neither the firmware nor the bootloder but the ethos suite which when you update obsolete files wants you to select and update all the languages ​​and not just the desired ones because the default suite sets only English instead when selecting all the languages everything works with desired software language and chosen audio.Inviato da iPhoneIl giorno 23 giu 2024, alle ore 15:44, mawzthefinn ***@***.***> ha scritto:﻿

I always install firmware from bootloder but the software remains only in English only with XE-S FCC firmware while with XE FCC firmware it is multi language software why this problem please PaoloInviato da iPhoneIl giorno 23 giu 2024, alle ore 01:50, mawzthefinn @.> ha scritto:﻿ Radio is recognized by the bootloader installed. Flash the XE-S Bootloader (it's in the 1.4.15 assets) and it should be recognized correctly. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

You have the XE bootloader installed, so the radio detects as an XE, you need to install the XE-S bootloader to get Suite to recognize the radio as an XE-S

**Comment by mgsanna** [comment]
Since we solved the problem we can close the issue

**Comment by mgsanna** [comment]
Solved by me in a phone call

**Comment by xfly21** [comment]
Yes Close the issue thanks very much Inviato da iPhoneIl giorno 23 giu 2024, alle ore 19:30, Marco Gualtiero Sanna ***@***.***> ha scritto:﻿
Solved by me in a phone call
