### ISSUE TITLE
Invalid Data with some models when sending the bin file to other transmitter (x20s to x20s)

### ISSUE THREAD

**Issue by michelkorthout** [FrSkyRC/ETHOS-Feedback-Community#4185]
Hello,

The following issue i face:

I have some models on my X20S (latest firmware), now i want to use those models on another X20S transmitter (latest firmware)
I transferred the files using the Bluetooth option, this all works fine, but as soon as the file transfer is over, an error pops up: INVALID DATA.

This happens with most models, but when i create a new model from scratch, i can transmit it to the other transmitter.
I never used a nightly version, always the official releases.

Attached 2 models that will not load on another transmitter, but work perfectly on my transmitter, i can clone them and use them without issue.

Any ideas?

[model issues.zip](https://github.com/user-attachments/files/15943895/model.issues.zip)

**Comment by michelkorthout** [comment]
[fokker d7m.zip](https://github.com/user-attachments/files/15959274/fokker.d7m.zip)
Attached a new model i created on my X20S running latest software.
I tried loading this into the FRSKY ETHOS Simulator, here the same issue. The file will not load.

I did not program anything special, but i cannot use it on another Transmitter.... really frustrating.. How can i debug the bin file, or understand what is wrong.?

**Comment by michelkorthout** [comment]
Guys, sorry.

Seems my Ethos simulator was not the latest version, now here al is fine. will check if the other x20s has really the same version. 
If this is the case then i would recommend have a better error message when a newer file is loaded on an older release. "Invalid Data" is not a clear message. Or do a pre-check wen sending models over bluetooth.

**Comment by bsongis-frsky** [comment]
Difficult to know what is wrong when you receive a bad file!
