### ISSUE TITLE
Simulator External HF module ELRS not available

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4186]
If you transfer the models from the transmitter to the simulator, there is no entry for the models with external RF module and ELRS.
Consequence: Error message - no failsafe activated.

If the models are copied back to the transmitter, the ELRS entry for the external HF module is of course also missing.

Can this be included in the simulator?

Thank you, regards Eugen

**Comment by mawzthefinn** [comment]
Do you have the ELRS Lua installed in the simulator?

**Comment by yak55** [comment]
Hello, I used the simuator on the X20PRO for the first time today.
That's when I noticed it.

I had also installed the script folder with the ELRS script.

I'll check again this evening to see if it's the same with the X20S or XE.

Maybe I made a mistake when copying the scripts.

I'll get back to you this evening.

Greetings Eugen

**Comment by yak55** [comment]
Hello, I have just checked.
All 3 simulators X20S, X20PRO and XE no longer load the scripts.
Affects all scripts, the Layout / Info window remains empty.

Script folders and scripts are available.

Greetings Eugen

**Comment by yak55** [comment]
When I copy the scripts to the Users folder, they are loaded and everything works as before.

Is that what you want?

Greetings Eugen

**Comment by mawzthefinn** [comment]
I asked because the Lua must always be present and loaded to get ELRS as an RF option

**Comment by yak55** [comment]
Hallo, kurz zur Erklärung,

Ich arbeite bisher immer mit dem Simulator X20S und Xe.
Dort waren bis gestern die Script Ordner immer unter Windows/Programme.

Seit Sonntag wurden keine Scripte mehr geladen.

Dann habe ich zum Testen den Scriptordner nach Benutzer/Ethos...
Kopiert, den gleichen Ordner, in dem auch die radio.bin und der Modellordner ist.

Und jetzt werden auch alle Scripte wieder geladen - auch ELRS, auch bei der X20PRO.

Damit hatte ich nicht gerechnet - aber Hauptsache es lädt jetzt wieder.

Grüße Eugen

**Comment by bsongis-frsky** [comment]
Still an issue in this area? I have been so serious with Deutsch when I was young that I have forgotten about everything.

**Comment by yak55** [comment]
Hello, sorry, I always translate from German to English with DeepL.
But sometimes the browser automatically translates back to German.

I solved my problem by copying the script folder into the user directory.

I have not tested whether it now works as before.

Greetings Eugen
