### ISSUE TITLE
X20Pro Nightly outputs Error max greater than 125%

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4187]
If the input exceeds max. 125%, a confirmation prompt appears.

Confirm with Yes: everything ok

Confirm with No: 1. the min value now becomes POSITIVE!
                                     2. the subtrim, formerly 0 is now 125%!

Tested with a new model and different channels!!!

Greetings Eugen

Figure 1: Initial situation
Fig. 2: Security prompt confirmed with YES! Correct
Figure 3: Security prompt confirmed with NO! FALSE

![IMG_6460](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/10570e3e-af80-45fb-b571-c6c7cad06174)
![IMG_6461](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/28b7a119-8ca8-46f0-ac1f-6d398ae5998f)
![IMG_6462](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/7f81ff5d-39d0-4023-ae50-215ceb2b8369)

**Comment by mgsanna** [comment]
I can replicate even in simulator, with X20PRO for sure

**Comment by yak55** [comment]
I have just tested it again on the X20S.
There is the same error.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Regression introduced just in the nightly. It will be fixed in the next ones. Thanks!
