### ISSUE TITLE
failure to open a log

### ISSUE THREAD

**Issue by chrols95** [FrSkyRC/ETHOS-Feedback-Community#4189]
almost every log i have made that is over 20minutes, wont open. i have tried having the write interval at 100ms, 250ms and 500ms.
files usually around 2 to 5 mb. 

i see the log, i try to open it inn the radio, and then it freezes. only option to do anything is to take out the battery.

radio is X20
firmware 1.5.9

**Comment by bsongis-frsky** [comment]
5MB will be impossible to load. The radio has limited resources!

**Comment by bsongis-frsky** [comment]
It's strange you should get a message "Not enough memory" when the memory comes too high. The radio should not freeze.

**Comment by chrols95** [comment]
The strange thing is that its never over 5mb, i believe the biggest was 4.3. I can send you the files and picture if you want to. Just tought it was somethin you wanted to know

Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment]
Yes please send the file, if possible

**Comment by bsongis-frsky** [comment]
Meanwhile I found that the "Close" button was not obeying touch actions. This will be fixed in the next nightlies
