### ISSUE TITLE
1.0.8 ADC2 no longer works

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#419]
Hello, with 1.0.7 I could still monitor the voltage at ADC2 of my R6 with logic switches (ADC2 <10.5V). Now I can no longer select a value in the logic switch. The value that is written there can no longer be changed. X10S with ISRM.

**Comment by bsongis-frsky** [comment]
What is the range of your ADC2 in Model / Telemetry?

**Comment by Devil-IdT** [comment]
Hello Bertrand, i think it is more than 4MV:
![screenshot-2021-06-07-81277](https://user-images.githubusercontent.com/64803366/121085085-b8fba280-c7e1-11eb-9fdf-75be23ae899d.jpg)

**Comment by Devil-IdT** [comment]
Now i have choose 2 "Nachkommastellen" and it has changed to 15,00V and i can adjust it to 18V (4S).
![screenshot-2021-06-07-81613](https://user-images.githubusercontent.com/64803366/121086062-fca2dc00-c7e2-11eb-9177-31c7fc31f5ef.jpg)

Unfortunately, you still cannot monitor the value in the logic switch, the 0.00 remains there and cannot be changed.
![screenshot-2021-06-07-81714](https://user-images.githubusercontent.com/64803366/121086244-34118880-c7e3-11eb-9f66-23ecd8e36210.jpg)

**Comment by jfint** [comment]
It does seem to work for me...In that it is totally broken and displays the wrong value.  It does however still display a value with 1.0.9 FCC

**Comment by Devil-IdT** [comment]
Ok, i will test it this afternoon with the 1.0.9 PR and will report.

**Comment by bsongis-frsky** [comment]
The range is not correct. Fixing it now

**Comment by bsongis-frsky** [comment]
Did you install 1.0.9 candidate 2 ?
Did you rediscover your sensor ADC2?

**Comment by Devil-IdT** [comment]
No, it there was only RC1.
Now i have RC2 and will test it.
Also i will rebind and rediscover sensors.

**Comment by Devil-IdT** [comment]
Ok, it works very well with the RC2.
After I re-bound the receiver and deleted all sensors, the sensors were re-searched.
The end range was immediately at 25V, much better than 4 megavolts.
![telem](https://user-images.githubusercontent.com/64803366/121241743-0f2d1c00-c89c-11eb-9c7f-b9f46093f277.jpg)
Of course, there was initially something wrong in the LS because I had deleted the sensors.
![ls_a](https://user-images.githubusercontent.com/64803366/121241841-2bc95400-c89c-11eb-8426-1c235456314d.jpg)
But the LS can now be adjusted perfectly.
![ls_b](https://user-images.githubusercontent.com/64803366/121241885-37b51600-c89c-11eb-92bb-3377e7b07e55.jpg)
Thank you for the quick help
