### ISSUE TITLE
In light and dark mode , highlight words with the selected colored background

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#4190]
I´ve noticed that when you move through the menus and submenus , depending on the background color you've selected, it would look it is better if the background of the word was always highlighted in the color you have selected and not in the word with a black or white  background depending on the mode selected (light or dark)

In some cases it does happen in the menus, but it should be highlighted in all cases.

I give examples
![IMG_4486](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87758703/7426d0b8-1ad2-4064-b979-607641ea14ea)
![IMG_4487](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87758703/e7b3cbea-4b8f-4ad7-973f-389f79bb8a03)
 In the first image, you can see that "25%" is on a white background and the letters in blue, you can hardly tell that is selected. however, in the second image you can see perfectly what  I have selected because the background is in color and the letters are white.

In dark mode the same things happens

I would like if it is possible for them to improve this.

Thanks

**Comment by strgaltdel** [comment]
... but then you wouldn't have a visual indication wether you're in "select" mode (as above) or in "edit mode" like here:
![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/8e53e0b2-ea75-43a3-95f0-e950d27e66c1)

as far you've only one color ("highlight color") selectable i would not change anything.



i guess you would need a second color (" field selection color"), so you would be able to visualize "select field mode" 

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/f0029b4d-4d6d-4b3f-b61c-fd915df8a3c3)

**Comment by jasalca** [comment]
I had thought of something like that
![IMG_4486 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87758703/eef4b13a-0c12-4922-9972-cb574ef92204)

**Comment by jasalca** [comment]
Although your idea wouldn´t be bad either

**Comment by jasalca** [comment]
There is also another possibility and that is that everything that is in " edit mode ", when clicked appears in a new pop-up window, for parameter modification.

**Comment by bsongis-frsky** [comment]
Honestly it works very well and it simplifies things

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/e3463ebd-858c-4479-8bf4-a73b3d104798)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/85ad1ab6-4a0c-4f9c-9227-9a24bb60da02)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/733b0e49-cfb3-40d0-823b-a7c405dd0f63)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/89e3aa2f-7873-421d-9daf-ae504b883b35)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ecd5b682-fcf1-4a28-8d31-dbf59fd2002a)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1ff85e4f-01c3-4f96-9504-bd41486efe31)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/4a9d5e1b-a86d-42a9-af5f-fca2f6d253e4)
