### ISSUE TITLE
Better documentation for developing to Ethos

### ISSUE THREAD

**Issue by iurycarlos** [FrSkyRC/ETHOS-Feedback-Community#4191]
Hi!

I bought recently my first Ethos powered device, a X20s. As an electrical and software enginner I got very excited to start to programming to it. 
However, i got a little disappointed with the amount of available documentation. How could we help to improve this promissing SO?

Is there more material than Lua Docs at the website?

I know this kind of question is more appropriate to email, but i tried to get in touch using the address at ethos site and it seems to be invalid.

Thanks!

**Comment by philippe-warnotte** [comment]
ETHOS version 1.5.10 will be perfect !

**Comment by bsongis-frsky** [comment]
In addition to the doc, you have a lot of examples there:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5/lua

**Comment by spoke2570** [comment]
[RCGroups has an active thread](https://www.rcgroups.com/forums/showthread.php?4018791-FrSky-ETHOS-Lua-Script-Programming) on this topic that has a ton of info.

**Comment by fdm225** [comment]
Another suggestion is to look in the actual Ethos user manual as it lays out the structure of a script and the required methods to implement.

dave
