### ISSUE TITLE
Add a way to terminate a "Play Track" special function

### ISSUE THREAD

**Issue by geekerator** [FrSkyRC/ETHOS-Feedback-Community#4194]
When playing a long track (for example, music), there is no apparent means to terminate the track other than waiting for it to end or power cycling the transmitter.  I would like to listen music while waiting my turn to fly. This is usually a problem since my plane is running and with music playing, normal voice information is not available until the track is over. Please implement a "kill audio track" special function that would immediately terminate the track currently playing.

**Comment by Wolepo** [comment]
Hello
I have discovered an error in this context. See picture for settings:

![Audioabspielen_rücksetzten](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/6fd03cde-92db-4e4c-8675-08a7eb9a9e97)

The SF67 is activated with SB. If I switch SF to the specified position, the "1x" becomes "continuous". Shouldn't this interrupt playback immediately?

**Comment by Flaperon88** [comment]
Hello,
 Same issue... 
I am transfering slowly my models to my X20, and i have also this kind of issue.

I have a personnal sound timer (audio file) activated  by the Elevator stick for training purpose in speed task. 
Every time stick move down (elevator up ) @ a configurated threshold , sound file must be restarted. 
Unable to set that correctly . Audio file keep playing.
... and more,... if I stick down 3 times, the audio file is repeated 3 times..... and unable to stop it. 
How to configure a 'stop play' audio file easily ?    
--> reinitiallisation of the playback should be done every time the condition is reseted or restarted.

How are configured the audio file playing priority in ethos ?

Will be great to get some info about that.

If tried a lot of way to do it without success.
I tried also with the timer, and don't have good results for this special function.



![SF9](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/dc6f68e2-a954-4191-a1fb-da5af465ea92)
![SF9 2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/1c94e29e-ff55-4b02-ba68-c5f952de2114)
![IL1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/aef238b3-5f79-46f0-b8a9-be4f921a8bbc)
![IL2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/479225d8-3855-4094-92b1-6e321311b717)

**Comment by GiorgioCirelli** [comment]
#3915

**Comment by geekerator** [comment]
There are several attractive ways to do this. For example:
  - Add an option: "Play Track (abort)" that aborts any track currently playing before starting the new one..
  - Add a checkbox somewhere in the model that makes it the default to abort any playing track before starting a new one.
These could both be enabled only when the playing track is NOT from the system directory.

Just saying...

**Comment by X20-3Q** [comment]
it could also be:
starting condition: adequate flight phase and/or SW 

- [ ] Each time the condition is changed, or no longer met, audio playback is reset or stopped.

- [ ]  except when playback is triggered via a stick position : the initial move triggers playback ( for example : stick down @ -20%); returning to neutral has no influence; the next move through the trigger position (for ex -20%) restarts playback.


I think this would allow more flexibility.
that how it work on my current TX, i was looking to do the same on my X20 without success....

**Comment by Flaperon88** [comment]
Not a lot of reaction about this concern....
Hope to see a solution in a very next update.

**Comment by Flaperon88** [comment]
Same issue as #3366 

Audio tracks not cut short #3366
Hope this will be corrected soon...

**Comment by Flaperon88** [comment]
was planned for 1.6.0 .   not resolved.    planned  later for 1.7.0  .    .....saw not palnned anymore ??? .  why ? the issue still remain !

**Comment by bsongis-frsky** [comment]
Implemented in 1.7.0
