### ISSUE TITLE
ETHOS SUITE crash with 1.5.10 in debug mode

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#4195]
As describe with discord to remind you.

DEBUG ON and OFF with SUITE crash suite.

Need to close and open suite to recovered the USB connect with the radio

**Comment by bsongis-frsky** [comment]
@Nicholas-Luoyi To be analysed tomorrow. I am not sure if it is Suite or Ethos, or both ... perhaps a timing issue?

**Comment by Nicholas-Luoyi** [comment]
If I'm not mistaken. It should always crash while START debug. And if you only turn on your radio once. It should become more and more common. After restart your radio and it would be hard to reproduce?

**Comment by bsongis-frsky** [comment]
It seems to me that it is a Suite issue. After restarting Suite, or stop / restart the USB connection, everything works again. It looks like an USB change detection which is missed.

**Comment by bsongis-frsky** [comment]
Confirmed. We will have a new release for Suite soon.

**Comment by aviat40** [comment]
Good job, the new version available is working fine
