### ISSUE TITLE
Incorrect result in DIY sensors

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4196]
Hello,
As I need the GPS altitude above sea level for further processing, I have to use a DIY sensor for this. It provides me with a precision of 2 digits after the decimal point.
 
![Präzision GAlt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/dac9ca9c-3444-428c-a967-3e548ac57e93)

However, the simple metres = 0m are sufficient for me. If I set it this way, only the comma is shifted one place to the right and an altitude of 435.26m becomes 43526m in the display and in the log. This is of course wrong.
Please correct it. Thank you very much
Wolfgang
*** Translated with www.DeepL.com/Translator (free version) ***

**Comment by bsongis-frsky** [comment]
Which version? Have you tried 1.5.10 which is about to be released?

**Comment by bsongis-frsky** [comment]
Protocol should have 2 digits. Then you may adjust display to 0 digit.

**Comment by Wolepo** [comment]
No, everything with 1.5.9

"Protocol should have 2 digits. Then you may adjust display to 0 digit."
How does that work?

**Comment by Wolepo** [comment]
Here are the settings:
![GAlt Präzision 0](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/8df1b4d0-ae1f-4547-abba-267ded378153)

And this is the result:
![GAlt Präzision 1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/48dad8f1-0eed-44f5-817a-5bc3d9e4e39b)

**Comment by Wolepo** [comment]
I now have 1.5.10 on the transmitter. The display works correctly in the DIY sensor. But the wrong values remain in the log.
![Protokoll_0 000](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/48eb4eca-656d-4aed-bb74-a8de9e712358)
![Protokoll_0 00](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/eb6336c8-6260-4443-88d0-bd6b9c725aa6)
![Protokoll_0 0](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/36bec848-0a24-4e1e-bde9-42245aae2634)
![Protokoll_0](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/5e033d3e-e48d-485d-849a-443e4c9d0700)

**Comment by bsongis-frsky** [comment]
Why do you show screenshots with all possible values. Altitude should have always the same protocol precision as it depends on the sensor itself. Then you may choose the precision displayed.

Once it is working, you can enable the logs and check that the values is right (with the right number of digits).

I have done the test here, I see no problem

**Comment by Wolepo** [comment]
It is correct that screen and protocol precision should have the same setting. I have therefore illustrated all 4 possibilities because this makes the result visible as a value in the header of the widget. Depending on the precision setting, this results in a value of 44m, 439m, 4389m and 43890m. However, I am of the opinion that the precision must correspond to the number of decimal places. 
I assume that the sensor delivers 4 numbers (4389 in the example), but certainly not 43.890km altitude. 
In the screen precision, the values in the Sensor menu are displayed correctly. Should I still make comparisons?
Wolfgang
PS:
I will then make a log depending on the precision setting. Let's see what value is then output.

**Comment by bsongis** [comment]
> It is correct that screen and protocol precision should have the same setting

No. If your sensor sends data with 2 decimals, you cannot decide to use 1 decimal in Ethos. This is DIY sensor, so you have the choice. But your choice must be inline with the actual data sent by your sensor.

**Comment by Wolepo** [comment]
OK. I quickly created 4 short logs with the possible precision settings. They only reflect the correct value at 0.00. There is never a comma.
[Thermy-3KLW-2024-06-27-11-22-12.csv](https://github.com/user-attachments/files/16012067/Thermy-3KLW-2024-06-27-11-22-12.csv)
[Thermy-3KLW-2024-06-27-11-22-58.csv](https://github.com/user-attachments/files/16012068/Thermy-3KLW-2024-06-27-11-22-58.csv)
[Thermy-3KLW-2024-06-27-11-23-20.csv](https://github.com/user-attachments/files/16012069/Thermy-3KLW-2024-06-27-11-23-20.csv)
[Thermy-3KLW-2024-06-27-11-24-55.csv](https://github.com/user-attachments/files/16012070/Thermy-3KLW-2024-06-27-11-24-55.csv)
Addendum: a different setting in the Screen precision line is not noticeable at all.

**Comment by bsongis** [comment]
Which precision have you selected for those files (protocol / display)?

**Comment by Wolepo** [comment]
I have finally understood the connections.
The terms Protocol Decimals and Protocol Display are wrong. But what does Protocol Display mean? How many characters does the sensor supply? If 5 characters are taken as a basis. 0.0 means that the character string is shifted one place to the left with the same number of decimal places. Missing characters are filled with zeros. Here are 2 examples:
Example 1
![Beispiel 1_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/2a852724-9312-4552-be71-ff26b45f5844)
![Beispiel 1_2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/7bd223c8-a9f7-4dca-8c9c-7b4c91e127f9)

Example 2
![Beispiel2_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/3f75c0d1-67e9-420d-ab12-0dad6e9fcb92)
![Beispiel 2_2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/918a2dec-64cc-42b9-bd97-86a6ca99d9e6)

**Comment by Wolepo** [comment]
I have finally understood the connections.
The terms Protocol Decimals and Protocol Display are wrong. But what does Protocol Display mean? How many characters does the sensor supply? Are 5 characters taken as a basis? 0.0 means that the character string is shifted one place to the left with the same number of decimal places. Missing characters are filled with zeros? Here are 2 examples:
Example 1:
![Beispiel 1_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/593cf79b-53c6-4eac-99f3-f0ea76754f4c)
![Beispiel 1_2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/76ae3b76-5968-444e-94fd-b2484b531284)

Example 2:
![Beispiel2_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/05e3b475-614a-4da3-9755-5f3ec6b7492b)
![Beispiel 2_2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/30b40efd-3aad-44d3-8457-f625f7a9fffa)

**Comment by bsongis** [comment]
> The terms Protocol Decimals and Protocol Display are wrong

I don't know where you have seen "Protocol Display" on this page.

It would be nice if someone else could help to explain to @Wolepo?

**Comment by Wolepo** [comment]
Well, let's close this topic. I have now found the settings that give the right result (e.g. 442m). But can another pilot handle it?
![GAlt Einstellungen](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/29c489b8-9b36-436b-8280-72c0e2dcbab3)
The correct value is displayed without decimal places.
