### ISSUE TITLE
The tool "Configuration Tool (Webpage Ver.)" only works with a lot of luck

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4197]
Hello 
1. tool does not work with Firefox.
2. to update the Neuron II controllers you need the tool "Configuration Tool (Webpage Ver.)". However, this can only be used with a lot of luck. Once you have connected the controller on the STK to the tool (press the [Connect] button), you must immediately supply it with power. According to the instructions, you should have 5 seconds to do this. If this does not work immediately, a message will appear after the progress bar has elapsed stating that the controller has not been found. So you have to try several times before it works. It should be almost impossible in the installed state.
 We ask for correction. Thank you for your help

Wolfgang

*** Translated with www.DeepL.com/Translator (free version) ***

**Comment by doloebig** [comment]
full agreement. The process of updating via the web tool is not handy and ist difficult to use

**Comment by Target0815** [comment]
For the configuration via webpage you need a Chromium based browser, e.g. Chrome or Edge. This is therefore not an error, but system-related (due to the browser).

**Comment by doloebig** [comment]
> For the configuration via webpage you need a Chromium based browser, e.g. Chrome or Edge. This is therefore not an error, but system-related (due to the browser).

the Firefox Browser is only one part of this issuw ,off course it the security from Firefox.

pls read the hole text from Wolfgang.
