### ISSUE TITLE
LUA NeuronIIESC_Scripts_ETHOS_v1.00 does not work with S.Port

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4198]
Hello.
If I set the telemetry transmission protocol to S.Port, I cannot configure the controller with the LUA. There is no connection, although this is stated in the description of the FW: 
       2023-08-11 11_3 1. added the support of using the LUA script to do the configuration in S.Port mode.
2. improved the response time of ESC telemetry
       Even an update to 11_5 does not help. The LUA still only works under FBUS.
What is not working here?
Thank you for your interest
Wolfgang

**Comment by mawzthefinn** [comment]
Which receiver? 

There is a known issue with the Archer R6/GR6 and using SPort with the Neuron II script , but it's been tested on other receivers and works fine.

**Comment by Wolepo** [comment]
Archer SR8Pro, Archer Plus SR8, Archer Plus SR6

**Comment by Wolepo** [comment]
This is output to an SR8 Pro with S.Port.
![Reglerinhalt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/9d968271-b6c1-4f70-b5a9-07b4969e554f)

**Comment by Wolepo** [comment]
Addendum: 3 more sensors are connected to the S.Port.
