### ISSUE TITLE
Not a problem - but a request Nightly Tandem XE EU

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4199]
Hello Bertrand, I have a small request.
I like to test the nightlys on the simulator and on the remote control, as some functions do not work in the simulator.

I would like to ask whether the Tandem XE can also be made available as an EU Nighty.
I think that the XE is particularly widespread in Europe (Germany).

Thank you, Eugen

**Comment by bsongis-frsky** [comment]
Done. It will be available in the next nightlies
