### ISSUE TITLE
Feature request: move ‘add screen’ tab to ‘Settings’

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#420]
In 1.0.8 “add model” option was moved to under the “model” tab. This make much more sense now. 

However, I also think the “add screen” option (currently in the main screen as [+]) should now be moved to inside the “settings” tab.

this would keep the interface much more organized. 

Not sure if I’m the only one, but I’m always accidentally inside that menu when and it drives me crazy….

**Comment by bsongis-frsky** [comment]
What do you mean by the "Settings" Tab?

**Comment by jreis1** [comment]
> What do you mean by the "Settings" Tab?
I meant to move inside System menu:


![Capture](https://user-images.githubusercontent.com/25162166/121161520-fd6c5a00-c844-11eb-8a30-145d7483d230.PNG)

**Comment by jreis1** [comment]
> The whole screen menu (including mentioned 'Add screen' option (in form of '+' button would be better a part of Model tab menus.

This is also a good idea

**Comment by jreis1** [comment]
> Placing into 'System' menu is not correct. The system menu is 'system wide', common for all models.
> The screen definitions are model based, each model can have differents screen, based for example on number of telemetric values.
> Therefore, only movement to Model menu is logicall

Agreed ! This is more logic! I’m happy as soon as it moves way from the main screen

**Comment by MrD-RC** [comment]
What benefit would there be from moving it away from the main toolbar? What would you replace it with? Removing it just leaves wasted space. As it stands, the options mirror those on the left menu button.

**Comment by jreis1** [comment]
> What benefit would there be from moving it away from the main toolbar? What would you replace it with? Removing it just leaves wasted space. As it stands, the options mirror those on the left menu button.

It is a bit non-sense to have an "edit screen" button on a main screen. This should be inside the "model settings" or accessible from elsewhere!  

For instance, I am always accidently touching the [+] button and consequently entering in the "Configure screens" menu. This happens very frequently when I wake up my screen from "sleeping".  I bet this does not happen only to me!

I've been giving some more thought to this, and In alternative the approach give by @IJK-CZ,, (moving [+] to "Model Menu"), I would like to suggest the following:

- Move the "Configure screens" to the most right tab of the display, as illustrated below: 
![ex](https://user-images.githubusercontent.com/25162166/121821533-8cd49b80-cc91-11eb-9a85-9cfc5521fa89.png)

**Comment by MrD-RC** [comment]
I still don’t really see the benefit of this. From the physical buttons, it is a top level menu. If you press the tele button, it goes to the same location. 

Just removing it and not replacing it with other functionality is just wasted space.

The accidentally opening it when you wake your screen is not really a fault of that button. If you tapped the model menu area when you wake, does it enter that? If not, then it is a bug in the wake process. Is your screen off when wake it, as opposed to just dimmed? If it’s off, then the first tap should only bring on the backlight, and not perform any tasks.

**Comment by IJK-CZ** [comment]
You are probably using only OpenTX. In FrSkyOS the TELE button is assigned to switch different telemetry screens, used during fligth. It is a reason, why the button was named TELE. I would prefer to use the HW button for different usage than screen definition, which is not very common task.

**Comment by MrD-RC** [comment]
Yes, I am used to OpenTX. As soon as I got my X10S, I upgraded it to OpenTX. 

I’m used to the page button, paging between the home and telemetry screens. It wouldn’t make any sense to have a button to do this on the screen, as just swiping from home has the same effect.

**Comment by jreis1** [comment]
At the current development stage, I believe this is not a critical request. I'll close the issue myself.
