### ISSUE TITLE
Bug: OTA Flashing with several Receivers online can fail flash process - Receiver dead.

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#4200]
Hi Bertrand,

I have the following configuration in a scale heli:
Receiver 1: Archer R6 Plus
Receiver 2: Archer R9MX connection with S-Bus Out to Receiver 1
Receiver 3: Archer RS (separate supply, no connection to the others) I use it for sound.
Running the last valid Ethos Version 1.5.9 on a X20S

Problem:
If you have a configuration like this, the flashing process is accessing both 2,4 GH receiver and flash something that leads to receiver dead. The process must be to select one receiver of the three for flashing and only this will be touched and flashed than correctly.
The others should not be touched and only the selected should be flashed, even if there are two of the same type in.
Engel Team tried it as well with other configurations. Some worked, others failed as well with partially receiver dead.

What happened:
I wanted to update R1 with my X20S OTA. 
All receivers are in the model somewhere implemented. 
I got the model under power. All R 1-3 are on.
Starting the update process by selecting the R1 in Ethos. R1 and 2 have been offered to select, R3 not.
Flashing starts and finished. 
After flashing, R1 and R3 are dead. No LED was lighting any more. The receivers can't be accessed any more via X20S.

Work around to get the Receivers back: 
Get R1 separately out of the model to the X20S direct and reflash via cable > Up and running again.
Get R3 separately out of the model and soldering new cable for S-Bus In. Reflash again via cable. > Up and running again. 
Unsolder the cable away for S-Bus.
This is a huge effort!

**Comment by MGausGS** [comment]
I have achieved the following results:
Receiver 1+2 (2x Archer PLUS R8) with the same receiver name (R8Plus) each with its own power supply works.
When updating via OTA, the corresponding receiver is de-energized (bound) and then flashed.

Receiver 1+2 (2x Archer PLUS R8) with the same receiver name (R8Plus) connected via SBUS and a power supply for both receivers together does not work. Both receivers are de-energized (bound), SBUS connection is maintained. Flash process runs through, receiver 1 is dead after flashing, only the blue LED lights up. Receiver 2 continues to light up green. Wake-up of receiver 1 only possible via flashing with cable.

Receiver 1+2 (2x Archer PLUS R8) with different receiver names (R8Plus1 + R8Plus2) connected via SBUS and a power supply for both receivers together works. Both receivers are de-energized (bound), SBUS connection remains. The receiver selection appears in ETHOS, where the corresponding receiver can be selected. Flash process runs through. After flashing, both receivers must be de-energized once.

**Comment by hrenz** [comment]
That's normal.
Why don't you think about what you're doing?
That MUST go wrong
You can only update one RX at a time
never all at the same time

Updates via cable are only ever carried out individually on the 
SPORT socket, one after the other, never on the SBUS system.

**Comment by BernhardFe** [comment]
Hi hrenz, yes, it is normal to update one reciver and that was the intention. Updating two at the same time would be a not work. I fully agree. Just select one and then make the update. That what that I expected.
But the Ethos OTA system is not following this process to update only one, even one is selected. Even if you want to update one it updates two accidentally if they are under power and this leads to the errors described above.
The process in easy words must be: Selecting and addressing the receiver (Ethos can distinguish the receiver) that needs to be updated by Ethos. Checking the dedicated receiver by Ethos gives back the actual software version and ask the user if update OTA should be done. If user presses "yes" the selected receiver will be updated, but the others will be not touched. And here is the problem. Under some configurations the others will be touched and then the update crashed. Here might be a bug in the selection and addressing of the receiver via OTA and ETHOS must avoid double updates at the same time. Hopefully it is now more clear.

**Comment by SmartTommy** [comment]
Hi BernhardFe, thanks for your test.
When flash the Rx by OTA, please make sure the two or three Rx has different name. you can rename the Rx when  register.

**Comment by BernhardFe** [comment]
Hi SmartTommy, of cause, they have different names, because the names are taken over from the receiver automatically and thy are all different. They are named as:
1: EMPF.1 R6Plus
2: EMPF.2 R9MINI-O
3: EMPF.3 RS
When I will ask for update 1 the menu in ETHOS ask to choose between R1 and R2. 
R3 is not recognised. Here the bug may start...
