### ISSUE TITLE
Switch off auto offset in GPS Alt sensor

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4201]
Hello,
In order to avoid the uncertainties of a DIY sensor, it would be nice to be able to deactivate the automatic setting of the GPS altitude (above ground) to zero with a checkbox. This would then give the altitude above sea level. Please give this some thought. 
Thank you. 
Wolfgang

**Comment by strgaltdel** [comment]
Wolfgang,
we had these "diy sensor" discussions yesterday in Andreas' forum, and to be honest, i don't feel "uncertainties" .

but nevertheless, i would give full support for this idea of a simple boolean field for automatic-Altitude offset On/Off too
(-;

but maybe you will change the title in "optional deactivation of auto offset in GPS Alt" ?

**Comment by Wolepo** [comment]
Thank you

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/e67e798e-85ea-46ef-a3c2-c7f4e711ff7b)

**Comment by Wolepo** [comment]
Thank you, that's exactly how I imagined it. Good work!
Wolfgang
