### ISSUE TITLE
Spez. Function

### ISSUE THREAD

**Issue by doloebig** [FrSkyRC/ETHOS-Feedback-Community#4203]
Make "write Log" possible to set global in Spez. Functions

**Comment by mawzthefinn** [comment]
Write Logs is a valid global special function and has been since Global SF's were introduced.

If you cannot set it to global, you have picked an Active Condition that is not valid for a Global SF.

**Comment by bsongis-frsky** [comment]
Indeed, all functions can be global if their parameters can be global
