### ISSUE TITLE
V1.5.10  no scripts at Simulator, no Lua-Menüs

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#4206]
the scripts are  at the sub dir of the Simulator but not integrated

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/79096bad-83c2-4c3b-ad44-0bec2de29aea)

 
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/ddcc6c26-27d0-4a53-bbc8-20dbccd0c2a9)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/99de34b1-f5c8-4448-9d86-a977b8872799)

**Comment by yak55** [comment]
Hello Hellmut, copy the scripts into the user directory, i.e. where the radio.bin and the models are.

I already reported the error some time ago in connection with ELRS.

Greetings Eugen

**Comment by hrenz** [comment]
tried all of this,
no one works at Simulator
no lua integreation

**Comment by strgaltdel** [comment]
Just downloaded actual nightlies and can confirm 
(tested by using x20s sim)

Sim tries to open script folder in user environment directory, NOT in regular install directory like usual:

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/dbc02745-3877-41da-85bf-79a65afb0ba6)

regards
Udo

**Comment by Alex00101** [comment]
Correct, I had to adjust my build scripts to copy my luas to that user directory. Works after that.

**Comment by bsongis-frsky** [comment]
It will even be `<user account>/.ethos/<board name>` now.
So that it is the same on all systems.

**Comment by strgaltdel** [comment]
just a comment:

If I understand correctly, all parallel sim installations of one board type, regardless of their releases, would use one scripts directory, right?


At the moment I typically use 4 installations for one HW platform

- "operations", identical revision & scripts like the transmitter 
- "development1", lua main development environment, sometimes more actual ethos then physical tx, use of integrated folder replication via VS Code editor to git
- "development2", sometimes used, for parallel developments, sometimes testing a script running another release, or used for script development / replicate folder to another git project then dev1
- "QSS/Test", Test environment, often used to crosscheck issues, which sometimes demands a specific release


so all these "environments" would use the same "scripts" folder.

if so,
i must think about more VM or container usage, if feasible
