### ISSUE TITLE
Safety feature to stop power to External Module when Tx is turned on to prevent damage if antenna is not installed

### ISSUE THREAD

**Issue by chrisca70** [FrSkyRC/ETHOS-Feedback-Community#4209]
**Ethos 1.5.x: Add Safety feature to stop power to external module when Tx is turned on**

This feature will prevent damaging any external module if the user forgets to install the antenna and the module is set to ON in the RF System menu. Currently if the user has an external module mounted, and enabled (ON) in the RF system menu, without an antenna installed and turns on the transmitter, the ext module may get damaged.

The Power to External Module Safety feature should:

- Detect if an external module is installed when the transmitter is turned on
- If a module is detected, power should not be sent to the module. Instead a message should warn the user to verify if the antenna is installed. Something like "Check if Ext module antenna is installed". If the user decides to hit "OK" power will be sent to the external module.
- This safety feature could be enabled/disabled in the RF system menu

**Comment by mawzthefinn** [comment]
Just add this to your Preflight checklist.

The external RF module is not powered on until the Checklist is cleared.
