### ISSUE TITLE
1.5.10 unable to call form.. mehtods from widget menu handler

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#4212]
Before - working as expected:
local function menu(widget)
    return {
        {"Model Info",
        function()
                local buttons = { {label="Close", action=function() return true end},}
                form.openDialog("Model Info", "Some Text", buttons)
        end},        

In 1.5.10 any attempt to call any form method from menu handler returns
    **Lua::Form::openDialog() error: no form**

**Comment by Alex00101** [comment]
Update, the message is now "forbidden" with the latest build

**Comment by bsongis** [comment]
Perhaps you are calling this method in a `paint` handler?

**Comment by Alex00101** [comment]
Sorry, definitely not. When I call from menu handler (for a simple yes/no confirmation), I'm getting the error above (the same code was working on 1.5.9 and before).
When I call from wakeup() the dialog opens as expected but in about 10 seconds it looses the focus so I cannot close it anymore.
Doesn't work on the radio either. 

I'm yet to try from configure().

Definitely not calling from paint()

**Comment by Alex00101** [comment]
Thanks a lot!

**Comment by bsongis-frsky** [comment]
Fixed. I have still a non regression test to write

**Comment by Alex00101** [comment]
Thank you
