### ISSUE TITLE
1.5.10 preRel Sims: Scripts folder structure changed, but installer still creates "old" scripts folder

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#4213]
Just installed todays X20s & pro Sims.

Both installers created an empty "scripts" folder in the old folder structure (install directory)

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/4cd2e7d2-c96b-4b97-ab61-b09a373c11ed)

1.5.10 introduces a new structure, now this folder belongs into users environment.
"this" folder in the install directory is obsolete

i'm pretty sure, this empty "artefact" will suggest users that there is no change and they will open issues that their scripts won't be able to configure in case they copy their lua files into this folder.

( but as mentioned yesterday in the old issue, the new structure pevents you from working with parallel installations in different ethos/lua script release combinations)

**Comment by bsongis-frsky** [comment]
It will be fixed today, with new simulators

**Comment by strgaltdel** [comment]
Just for info,

even todays pro-nightly (4Juli; 8:11) showed this issue,
but furthermore the installation (admin rights) stopped because simulator.exe couldn't be written
deleting the old simulator.exe worked, 
maybe a singularity, 
maybe file access rights of the last pre-release were to "tightened"

**Comment by bsongis-frsky** [comment]
It is still not good - somebody sent me a gift yesterday and I had to taste it, it is not very good for code quality ;)

**Comment by strgaltdel** [comment]
Oh, maybe there should've been some coffee added !

**Comment by bsongis-frsky** [comment]
Indeed, big mistake ;)
Thanks a lot, it went straight to the heart!

**Comment by strgaltdel** [comment]
"Honor to whom honor is due"
nothing to thanks, it was a pleasure

**Comment by bsongis-frsky** [comment]
It should be good now, someone can confirm? Thanks!
