### ISSUE TITLE
Probleme mit Ethos SIM Vorabversion 1.5.10

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#4214]
Es habe sich einige Fehler in der Sim Version 1.5.10 eingeschlichen: siehe Video
- Falsche Zeichenreihenfolge im Wizard beim Anlegen eines neuen Verzeichnisses
- Löschen eines Verzeichnisses nicht möglich 
- Umbenennen eines Verzeichnisses nicht möglich
- vorherige Verzeichnisstruktur wird nicht gefunden (ist schon als Problem gemeldet worden denke ich)

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68751162/d1497b69-3042-4826-a577-050328c8b3a1

**Comment by strgaltdel** [comment]
..just the q&d  translation (-;

Some errors have crept into the Sim version 1.5.10: see video

    Incorrect character sequence in the wizard when creating a new directory
    Deletion of a directory not possible
    Renaming a directory is not possible
    Previous directory structure is not found (I think this has already been reported as a problem)

**Comment by bsongis-frsky** [comment]
First point is right. I have just fixed it right now. I still miss a non regression test.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/3ae7ffb8-c878-4db4-b9dc-3c644bec624f)

**Comment by bsongis-frsky** [comment]
I can delete a directory, even from Simulator

**Comment by bsongis-frsky** [comment]
Rename is a request, not an issue. It should not be mixed here!

**Comment by bsongis-frsky** [comment]
Fourth issue has been fixed already
