### ISSUE TITLE
Calculates telemetry sensor have min/max/presence wrong

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4217]
Ethos 1.5.9

If a calculated sensor depends on some other sensor, which value is not defined or sensor is lost, following happens:
- calculated sensor has wrong value (I think it either defaults to zero, or uses zero for sensors which are lost)
- min / max is calculated wrong (because of point above)
- it's not visible in any way that sensor value is wrong

Example - I defined a Vcell sensor like this (to have pack voltage displayed as "avg vell voltage")

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/74438bbc-fbdd-4793-b800-a18c306e322e)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/a2a09147-e850-4391-b032-dfb51b9bf4b5)

And this is what I get before connecting the battery:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/d1cdf6cc-5edd-4f9d-9320-5cb163d9d99b)

This after connecting the battery:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/c464d89d-964c-420d-8ff3-061f0fbb8b4d)

This after "Reset Telemetry":
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/672bacae-cc06-40a2-b2dc-4dc9b036ac10)

And this after disconnecting the battery:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/6c331874-b02a-42e4-ad00-1310a558aa1c)

--------
Proposed solution:
- I think it would be best (and also what user would naturally expect) if calculated sensor would have "undefined" (and / or "lost") state, just like normal sensor
- calculated sensor would be in this state, if anything which was used in its calculation is undefined
- then it could behave like all normal sensors
  - widget would show it "red" or as "---"
  - min/max not updated to zero when it has no value
  - etc.

If Ethos differentiates between "undefined" (when widget shows "---") and "lost" (widget shows "red color"), it would make sense to have both of these for calculated sensors too.

On could also wonder, what should be the calculated sensor outcome, when it depends on two different sensors, and one of them is "undefined" while the other is "lost". I think the outcome should be "undefined".

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/68cfdeb7-24ad-4c31-a049-fcb885724786)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0d1c2c6d-1a57-4dcc-911a-267dcfa6755f)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/bb768bfb-cb23-4129-af2c-6a4461cbe769)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9cb93ee9-ce30-4aa1-832f-46bf148216b5)

**Comment by azaz44** [comment]
@bsongis-frsky 
Great to see this coming in 1.5.12, as I use many calculated sensors. But I wonder why on your 3rd screenshot v-cell is not 5.38 divided by 2 but a completly dfferent value?

**Comment by bsongis-frsky** [comment]
I have played with the max value, and 0.05 was the maximum ...
