### ISSUE TITLE
Telemetry min/max is not always usable

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4218]
Ethos 1.5.9

I show statistics like
- min voltage
- min BEC voltage
- max current
- max temp
- etc.

and check them after each flight. But some of them are not usable.
For example min voltage is always zero. I think this is because voltage is growing when connecting the pack.

Min BEC voltage is fine, but only as long as I keep system powered. If I disconnect the pack, sensors become lost, but just before that the BEC value drops and affects the "min" value. So here it works correct, but it could be more usable.

All of this happens because sensors get weird values, growing or rising when connecting and disconnecting the power.

Example situation after filght:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/beaa7b12-e1de-4183-9cbb-1eeeccf943b0)

And after disconnecting power:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/6be6fbff-f26a-43a8-8c27-fb12afd6ac24)

---------
Proposed solution

I wonder if we could have an option:

"Update min/max"     [ !Throttle Cut ]

So we could set a condition when statistics are actually captured. We could then set it to !Throttle_Cut and be happy.
This could be an option per each sensor, or one global per model.

**Comment by pmullen503** [comment]
The solution is to reset telemetry. I use a SF triggered when my throttle is first armed.

**Comment by mawzthefinn** [comment]
> The solution is to reset telemetry. I use a SF triggered when my throttle is first armed.

I do the same.

**Comment by azaz44** [comment]
Hmm I can try, but do you use stickies? I wonder how it will work with resetting flights.
I would need to reset it only on first arming and not subsequent ones.

**Comment by pmullen503** [comment]
I also use one of the function switches for a manual reset, especially on a new model, when I don't necessarily want to arm and disarm the throttle.

**Comment by azaz44** [comment]
This works, I think I will incorporate it into my settings.
But unfortunately it doesn't work with calculated sensors. For example "min cell voltage" (which is "min voltage" divided by numer of cells) does not get reset with "Reset Telemetry". But this is I think a different issue to fix.
