### ISSUE TITLE
Today's simulators are faulty

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4220]
No models or sound files are recognised in the sim just loaded (X10Express and X18). A newly created model cannot be found anywhere, but is loaded again in the sim after a restart. What are the correct paths?
![Sprache](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/227e6c66-cd39-48ab-8768-feff54e5c3e7)

**Comment by Alex00101** [comment]
Please look at #4211 full fix in there. That was the yesterday's version before they've been recompiled about an hour ago, not tested these yet

**Comment by Wolepo** [comment]
I'm talking about today's version!

**Comment by Alex00101** [comment]
Than it looks like it's not fixed. Still try the fix I'm talking about, should work

**Comment by bsongis-frsky** [comment]
Windows simulator?

**Comment by Wolepo** [comment]
Yes, Windows

**Comment by Wolepo** [comment]
It should be published which paths are now correct. Even after moving the files manually, nothing works.

**Comment by bsongis-frsky** [comment]
It's strange, I have tried the X14S simulator right now (it was uploaded 3 hours ago) and I see no problem. I will try to remove everything and install it again

**Comment by Alex00101** [comment]
If I may ask, where should bitmaps folder be placed now, in the
installation directory or in the user directory? Thanks

**Comment by bsongis-frsky** [comment]
I have tried again. The directories are created correctly now.

**Comment by bsongis-frsky** [comment]
> If I may ask, where should bitmaps folder be placed now, in the installation directory or in the user directory? Thanks
> 

Which bitmaps?

**Comment by Alex00101** [comment]
Thanks Bertrand,  let me explain. Currently installer writes all files - i18n, audio, and images (system and models for custom model images) into the installation directory (Program Files x86). Scripts, models and radio.bin is under user directory (.ethos/X10EXPRESS). The version I've tested this morning (10 hours ago or so) did not create ethos/X10EXPRESS (had to do it manually) and was not able to see audio files in the installation directory until I manually copied them into user directory under .ethos/nnnn

Before I test the latest build I'm wondering what is the "right" setup, should audio and bitmaps be under the same root?

Many thanks

**Comment by bsongis-frsky** [comment]
There is indeed something wrong for bitmaps. I am trying to fix it quickly

**Comment by bsongis-frsky** [comment]
But the directory .ethos/X10EXPRESS is created automatically (simulators generated 3 hours ago). That I am sure. 
I only miss the model bitmaps

**Comment by Alex00101** [comment]
Then my apologies for a potentially unnecessary reminder, I know you are
busy

**Comment by Wolepo** [comment]
I have now completely deleted all simulators and only installed the one for X10Express. I have pasted the files from my transmitter into the audio and bitmap folder. Everything remains the same, languages (sound) cannot be selected. See post #1

**Comment by bsongis-frsky** [comment]
Indeed there is a problem with Audio. Nobody should send alcohol to thank for the good work. Coffee is more efficient (but less good)!

**Comment by CodeWorksCZ** [comment]
B

Dne čt 4. 7. 2024 18:58 uživatel Bertrand Songis @ FrSky <
***@***.***> napsal:

**Comment by Wolepo** [comment]
All this has until tomorrow. A break is also necessary.

**Comment by bsongis-frsky** [comment]
The first bins should be ready now:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/efe08e00-ceb8-43c6-a8ef-4a22eed17507)

**Comment by bsongis-frsky** [comment]
I have checked the X20S simulator right now and it seems good again. Everybody agrees?
