### ISSUE TITLE
Ethos Suite 1.5.7 update process stops after downloading updater

### ISSUE THREAD

**Issue by mikedkelly** [FrSkyRC/ETHOS-Feedback-Community#4222]
I opened Ethos Suite 1.5.6 and it prompted me to update to 1.5.7. It then shows the dialog for downloading the updater. When it gets to 100%, it stops with only an option to cancel. There are no other popups or buttons to continue the updating process. Canceling the dialog shows a file error. I restarted Ethos Suite as an administrator and the process completed without errors.

**Comment by LanceGebert** [comment]
I have the same issue. I even downloaded suite straight from github. When downloaded from github models wont load in suite.

**Comment by craigywsm** [comment]
This has already been reported in #3950

**Comment by mikedkelly** [comment]
Thanks - closed as duplicate.
