### ISSUE TITLE
For the future, I ask that the timer' fonts size be proportional to the widgets' size. 

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4226]
For the future, I ask that the timer' fonts size be proportional to the widgets' size.

**Comment by mawzthefinn** [comment]
Duplicate of your #4065

**Comment by philippe-warnotte** [comment]
Ok but you closed this post too. So no one will take my remark. Look
powerbox

Le ven. 5 juil. 2024, 20:58, mawzthefinn ***@***.***> a
écrit :
