### ISSUE TITLE
SWR Warning x20pro

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#4228]
Received an acoustic SWR warning today, even though I'm not using any external antennas and have set RF to internal. 
Any Ideas?

X20 pro in TD mode
1.5.8-EU

**Comment by mawzthefinn** [comment]
Some folks have found the VFR warning callouts sounds like SWR warning if heard unexpectedly

**Comment by WhiskeyGolf** [comment]
Speculating whether it was just misheard is not a professional solution to a potential problem. I think the callouts sound completely different, just because of the distinctive W. Also, there is just a warning for SWR and not a critical or low warning. 
The logs for VFR and RSSI were completely in the green zone on that flight.
So what could the error be? A wrong callout or an actual problem? 
That's always good to know when flying a new system with expensive jets.

**Comment by pmullen503** [comment]
SWR warnings usually involve an antenna. 

Have you ever opened your TX?  We had a club member that had opened his pro to put heavy springs on his gimbals. The 900 mhz antenna in the handle was not seated properly when he reassembled the TX and he got intermittent SWR warnings. Making sure the antenna was properly seated solved the problem.

**Comment by WhiskeyGolf** [comment]
Thank you for the tip! I'll take a look, I haven't had to remove any antenna cables yet. Does this only apply to the 900mhz antenna? The 900mhz antenna on the x20 doesn't seem very solid to me anyway. I've just heard that the SWR warning is only intended for external antennas.

**Comment by pmullen503** [comment]
The 900 antenna in the handle is easy to dislodge if you aren't careful. And sometimes it won't come off completely so it's easy to miss.

**Comment by WhiskeyGolf** [comment]
okay, thank you very much! I'll check it out in the next few days!

**Comment by WhiskeyGolf** [comment]
I think I have found another cause for this error. 
In fact, my RF connection quality was always great. 

If the audio player is overwhelmed, it sometimes plays some inappropriate callouts. 
This sometimes happens when I have airspeed announced every 3s and timer callouts are added. Then the voice output stutters and some random callouts are added.
