### ISSUE TITLE
in 1.0.8 you cannot access the Wireless Menu!!!

### ISSUE THREAD

**Issue by gomitologiallo** [FrSkyRC/ETHOS-Feedback-Community#423]

**Comment by MIKE-DAILEY** [comment]
Works OK with X20S including Bluetooth audio.  On X20 the wireless icon displays the wireless menu intermittently but cannot select options.

**Comment by gomitologiallo** [comment]
In 1.0.7 on x20 it worked. 
In 1.0.8 it didn't work.

**Comment by jfint** [comment]
The X20 does not have that feature, so i think its likely that this is a fixed issue, not an introduced one?
