### ISSUE TITLE
Ethos Suite 1.5.7 no update or modell backup possible

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#4230]
Using a X14, only internal Flash used, no micro sd.

With Ethos Suite 1.5.7 no update options selectable, update with "all components" selected hangs, no backup in model manager possible, no drive eject button.
With Ethos Suite 1.5.6 update to Ethos 1.5.10 works fine as well as all other options. No problems with Ethos Suite 1.5.6.

![Screenshot 2024-07-06 142321](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/9a766397-d2ab-4a62-bb20-809b6d91b907)
![Screenshot 2024-07-06 142428](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/5208b30a-eb45-4b24-83bb-1c62b73c17aa)

**Comment by Alex00101** [comment]
Had the same symptoms. Worked for me eventually but only after multiply attempts on connecting radio in bootloader mode or not and starting the Suite in different order.

Something seems broken.

**Comment by philippe-warnotte** [comment]
Me too with Kavan V20 FW 1.5.9 and Suite ethos 1.5.7.
The models list is not shown with Ethos Suite 1.5.7 and ok with Ethos Suite 1.5.6.

**Comment by Wolepo** [comment]
The connection sequence must be followed: first open the suite, then connect the transmitter to the PC in bootloader mode. Now you can switch and switch to your heart's content.
As soon as you have ejected the drives, this switch disappears and you have to start again from the beginning, see above.
![Backup nach 1 5 10_1](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/91f8d35b-437a-4671-8660-7858df9eb35c)
![Backup nach 1 5 10_2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/90325526/cc3bca26-2948-44db-adf9-326d70170bbc)

**Comment by FlipAirboost** [comment]
> Had the same symptoms. Worked for me eventually but only after multiply attempts on connecting radio in bootloader mode or not and starting the Suite in different order.
> 
> Something seems broken.

Same for me.
Everything is grayed out on first try.
I woke up the screen with a backup which then turned green for upgrades.
Message waiting for disks or disk!?
I ask for everything to be upgraded, it starts with the bootloader and it crashes.
I close the ethos suite program and eject the two drives manually.
The problem of switching the radio to emergency mode when disconnecting the USB cable reappeared.
I restart the ethos suite and set the radio to everything for the USB cable. And chose ethos suite on the radio screen.
Message waiting for disks or disk!?We quibble, moving from one screen to another on ethos suite!!?
I just upgrade ethos as proposed by ethos suite.
It works, everything is green, nothing more to upgrade but I don't have the drive ejection option.
I chose the option to upgrade everything and ethos suite does it.
It works, everything is green, nothing more to upgrade and I have the drive ejection option.

When all the upgrades are green, it is not normal to be able to do it again in my opinion.
It's still a big mess and quite random success for upgrades.

So the upgrade and backup is possible from ethos suite 1.5.7 but not many people understand how when and why it sometimes works or not.

ethos suite 1.5.7
ethos os 1.5.8.eu >1.5.10.eu
fw 2.2.6.eu
win 10 familiale

**Comment by glipski50** [comment]
> The connection sequence must be followed: first open the suite, then connect the transmitter to the PC in bootloader mode. Now you can switch and switch to your heart's content. As soon as you have ejected the drives, this switch disappears and you have to start again from the beginning, see above. ![Backup nach 1 5 10_1](https://private-user-images.githubusercontent.com/90325526/346321105-91f8d35b-437a-4671-8660-7858df9eb35c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDUyNzAsIm5iZiI6MTcyMDM0NDk3MCwicGF0aCI6Ii85MDMyNTUyNi8zNDYzMjExMDUtOTFmOGQzNWItNDM3YS00NjcxLTg2NjAtNzg1OGRmOWViMzVjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA5MzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZjZiYmNmNzEwMzk5OGY2MzdlZDdhZWNlMzUyMDU2NTJkMWE5ZTUyNjI5ZWM3YWY1NDUzMjdkODc4Y2E1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GQA1Ma7W3FVVYuI5cboS6mW0chU9DCvyCLdRxBbNXew) ![Backup nach 1 5 10_2](https://private-user-images.githubusercontent.com/90325526/346321109-cc3bca26-2948-44db-adf9-326d70170bbc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDUyNzAsIm5iZiI6MTcyMDM0NDk3MCwicGF0aCI6Ii85MDMyNTUyNi8zNDYzMjExMDktY2MzYmNhMjYtMjk0OC00NGRiLWFkZjktMzI2ZDcwMTcwYmJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA5MzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NmYzNWJkYTUyYWU1OGYyZTg5YThiMDFhMWEwNmYzMjE4MGMzZWI0ZDUwMDRhMWM2ZjJlNzJlZTBjZjY1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nxFQUT4dVonTUiOTSKwWdNeFKkgAnvhznw6mS4qkhzw)

Does not work either with that procedure. Transmitter is a X14. It works fine with Ethos Suite 1.5.6 and has worked with previous versions as well.

Connecting in boot loader mode Ethos Suite 1.5.7 even does not recognize the X14 although windows does and opens file explorer windows. That problem existed already several month ago and was than fixed. Looks to me like the problem has been re-introduced in Ethos Suite 1.5.7, for X 14 at least.

**Comment by philippe-warnotte** [comment]
Ethos suite 1.5.7: Models do not displayed to make a backup. 
The radio is detected but some updates are not visible. 
EVERYTHING is OK with Ethos suite 1.5.6 !

**Comment by Nicholas-Luoyi** [comment]
Would you please confirm that:
1) You are using Windows.
2) You all don't have the FLASH/RADIO/SD content displayed at the location indicated by the arrow
![1720397198604_d](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/58321103/0aad174a-84e8-4a1b-86ca-47840fda069c)

**Comment by glipski50** [comment]
Can confirm using windows 11. for the displayed content see my first screenshot in my opening post.  In addition to my screenshot the „Eject Drives“ button is not existing. „The Module version“ is in 50 % of my attempts grayed out and has no version info. After clicking „Go to module manager“ and getting the module version the line „Module version“ and version number looks normal.

**Comment by philippe-warnotte** [comment]
1: windows 10. File explorer detect radio, sd and flash
2: Suite 1.5.7 detect flash and sd but not radio
3: All is ok with Suite 1.5.6
![20240708_073912](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165813792/21e29a26-7fb8-4d9c-94e7-dec51ca34344)

**Comment by Nicholas-Luoyi** [comment]
Please try Suite 1.5.8

**Comment by philippe-warnotte** [comment]
It's ok for me with Suite 1.5.8
Thank you Nicholas.
