### ISSUE TITLE
Unable to set warning for Lowest cell voltage reported in #3041 again present in 1.5.9 and 1.5.10

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4231]
Please, note that again the value for LiPo lowest cannot be lower than 21.4 (value set as minimum in the LiPo Telemetry screen)
Exactly the same issue I reported in #3041. 
![#3041 bis](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9392774/1b6793ee-6e3a-45d5-a166-63f66b4bd4f2)

**Comment by bsongis-frsky** [comment]
Cells count has the same kind of issue:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/57090f96-2158-44ef-90d9-ab8025c4b441)

**Comment by bsongis-frsky** [comment]
It will be fixed in 1.5.11
With a non-regression test, so it should never occur again ...

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5e2a21f3-a508-460a-a343-149ddab505a6)

**Comment by Richrfl** [comment]
You are great Bert!
