### ISSUE TITLE
Problem of LUA interpreter in ETHOS 1.5.10

### ISSUE THREAD

**Issue by m-rik-prog** [FrSkyRC/ETHOS-Feedback-Community#4233]
https://www.facebook.com/groups/1595007400772880/posts/3674799979460268?comment_id=3674804946126438

It seems that something has been changed in the event generation of:
KEY_RIGHT_FIRST
KEY_PAGE_UP
KEY_LEFT_FIRST
KEY_PAGE_DOWN

I can try to find a workaround for this new problem, but the doubt and concern is that the change will also work for users who use previous versions of ETHOS and never update the transmitters and especially functions with all the different button arrangements of the various transmitters for which a version of ETHOS has been released, both new with SYS & DISP and older transmitters with PgUp & PgDn (EG: X12S-ISRM, ).
Difficult to verify this as when I tried to downgrade ETHOS last year it was a disaster and I was told from Bertrand that downgrading with ETHOS is not expected.

**Comment by m-rik-prog** [comment]
After some debug:

This code:

**local function event(widget, category, value, x, y)
            print("event(",widget, category, value, x, y,") called")**

Using ETHOS 1.5.10 with a single pression of SYS or DISP keys give:

**event(  nil     0       100     0       0       ) called
event(  nil     0       100     0       0       ) called
event(  nil     0       101     0       0       ) called
event(  nil     0       101     0       0       ) called**

This repletion happen with all “buttons” except rotary dials

Temporarily solved with:

          **if value == PrecedentEvent then
                    if EventRepetion == 1 then
                              EventRepetion = 0
                              return true
                    end
          end
          print("event(",widget, category, value, x, y,") called")
          PrecedentEvent = value
          EventRepetion = 1**

But:
a) Rotary dial must rotate double.
b) maybe that with precedent ETHOS version user must push twice the keys.

**Comment by strgaltdel** [comment]
did you have a look into the documentation/ reference guide ?
i just looked into with my handy and could see that
KEY_PAGE_UP is deprecated.

so i would assume you'll have to use one of the corresponding new constants

i didn't trace these ones, but the old "colors" could be used for several update cycles after they got the status, so there was enough time to implement the changes

**Comment by m-rik-prog** [comment]
Thank you for your intervention.
Unfortunately, the KEY_PAGE_UP & KEY_PAGE_DOWN events need to be maintained in order to have ETHOS version compatibility for the old X12S-ISRM transmitters maintained by FrSky still in the catalogue: and not yet put among the discontinued transmitters:
https://www.frsky-rc.com/product-category/transmitters/horus-series/

However, I received a "tip" from the USA and by removing the comment from "-- return true"  at the end of the "local function event" function ("return" that until now was useless and took up unnecessary memory space), the problem was solved.

**Comment by bsongis-frsky** [comment]
Horus X12S is maintained.
`KEY_PAGE_UP` & `KEY_PAGE_DOWN` have been deprecated for `KEY_PAGE_PREVIOUS` and `KEY_PAGE_NEXT`
Your events should return true when the event is used by your script, and false when not, so that it is passed to the upper window

**Comment by m-rik-prog** [comment]
Thank you Bertrand!
I had not read anything about these two changes / fix either in the release notes of the nightly versions or in the final release notes. Evidently I missed them. Had I seen them I would have checked and fixed them earlier.
Thank again.

**Comment by bsongis-frsky** [comment]
To be honest, events should be sent only one time, even if not acknowledged. But it's still better to acknowledge them.
