### ISSUE TITLE
Erreur suite à la calibration Rb25s FW 1.5.10 Lua v1.1

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#4234]
Bonjour Bertrand,
J'essaie de calibrer mon rb25s,  lorsque la calibration se termine, j'ai un message d'erreur ( photo jointe), et le gyro ne fonctionne pas.
Tout est à jour.
Tandem Xe

![17203463286066727663308093499290](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89158034/6ad5c5bc-a4b0-4c26-906a-6ba4e1624193)

Merci,
Antoine

**Comment by Nicholas-Luoyi** [comment]
The image names didn't match the names in the script. I've fixed the issue and re-uploaded them.

**Comment by Tonio62** [comment]
hello, I just tried and it still reproduces the same error

**Comment by Nicholas-Luoyi** [comment]
Where do you get the scripts?

**Comment by Tonio62** [comment]
directly on the frsky website.
but ok, I'll get it here ;)

**Comment by Nicholas-Luoyi** [comment]
Yes. Please try the scripts in this github repo

**Comment by bsongis-frsky** [comment]
@Tonio62 Problème résolu ?

**Comment by Tonio62** [comment]
> @Tonio62 Problème résolu ?

Je suis au boulot, je teste ce soir ;)

**Comment by Tonio62** [comment]
> @Tonio62 Problème résolu ?

Bonsoir,
Oui, problème résolu !

Par contre impossible d'activer la stabilisation en mode Delta, alors qu'elle fonctionne très bien en mode Normal et Vtail...
J'ouvre un autre sujet ?

Merci

**Comment by bsongis-frsky** [comment]
Oui, cela n'a rien à voir !
