### ISSUE TITLE
local function init()system.registerLayout({key=" ......

### ISSUE THREAD

**Issue by frobert0** [FrSkyRC/ETHOS-Feedback-Community#4235]
Up to 9 fields works perfectly, from 10 fields model file is damaged, after restart or disconnect usb

local function init()system.registerLayout({key="XL+3", widgets={{x=8,y=95,w=256,h=100},{x=8,y=203,w=256,h=70},{x=8,y=281,w=256,h=130},{x=272,y=95,w=256,h=70},{x=272,y=173,w=256,h=70},{x=272,y=251,w=256,h=70},{x=536,y=95,w=256,h=70},{x=536,y=173,w=256,h=70},{x=536,y=251,w=256,h=70}}})end return {init=init}

**Comment by bsongis-frsky** [comment]
Right. 
I will add a protection not to go over the limit
But do you reallly need more than 9 fields?

**Comment by bsongis-frsky** [comment]
Protection added

**Comment by frobert0** [comment]
Siehe Beispiel

Bertrand Songis @ FrSky ***@***.***> schrieb am Mo., 8. Juli
2024, 08:20:

**Comment by frobert0** [comment]
Siehe Beispiel: 

![xxx](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12582649/04f8f98a-4544-4a88-8c27-2cf91fc623dc)

**Comment by frobert0** [comment]
Thank you, you are the best.

15?????

![Screenshot 2024-07-10 151949](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/12582649/8adec675-972f-4de2-a980-eaa97de37f79)

**Comment by Harrykd33** [comment]
frobert, Is it possible for you to send me your lua script for the layout you posted? doverk@ ymail.com

**Comment by philandroid36** [comment]
@frobert0 
are we still limited to 9 or not?
I can't get past 9 with version 1.5.16
I would also like to see your script with 12 widgets :)

**Comment by Harrykd33** [comment]
12 is the limit, but that depends on if your xy positions go into the borders. I can get a max of 11 utilizing most of the screen.
![20240907_101539](https://github.com/user-attachments/assets/bf17f9c8-5dcf-4cfb-80e3-7ba19906f128)

**Comment by frobert0** [comment]
@philandroid36 
please with pleasure

@Harrykd33      
Nice layout,
what limits do you mean, I take 800x316 as screen size at X20 and still have space for 8 pixels space between the widget's
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4235#issuecomment-2220497264


local function init()system.registerLayout({key="XL+3", widgets={{x=8,y=95,w=256,h=100},{x=8,y=203,w=256,h=70},{x=8,y=281,w=256,h=130},{x=272,y=95,w=256,h=70},{x=536,y=95,w=256,h=70},{x=272,y=173,w=124,h=70},{x=404,y=173,w=124,h=70},{x=536,y=173,w=124,h=70},{x=668,y=173,w=124,h=70},{x=272,y=251,w=256,h=70},{x=536,y=251,w=256,h=70},{x=272,y=329,w=520,h=82}}})end  return {init=init}

**Comment by philandroid36** [comment]
@frobert0 
Thank you very much. It made me understand my mistake.
