### ISSUE TITLE
ethos suite1.5.7

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#4236]
Hi,

After installing ES1.5.7, i've tried to update to ETHOS 1.5.10  but it recognized the last version as 1.5.9 instead of 1.5.10.

**Comment by ronron84** [comment]
when i did the upgrade manually i've lost French language...

**Comment by Nicholas-Luoyi** [comment]
> Hi,
> 
> After installing ES1.5.7, i've tried to update to ETHOS 1.5.10 but it recognized the last version as 1.5.9 instead of 1.5.10.

Would you check again please?

**Comment by ronron84** [comment]
Hi, 
ethos update still not working i had to download it from github the one from frsky is not working either.
with the manual download ethos suite work just fine and recognize 1.5.10 as the last version.
the last thing is why i loose the french language for the menu when i installed it manually before.
thanks for your work

**Comment by Nicholas-Luoyi** [comment]
The update issue is metioned in #4230. Please follow the topic. It would be fixed very soon. In this one I just need to check 1.5.10 is the latest version

**Comment by ronron84** [comment]
ok
thanks
