### ISSUE TITLE
Text To Speech-Ethos 1.5.10 E.M. issue

### ISSUE THREAD

**Issue by Bobbysonic** [FrSkyRC/ETHOS-Feedback-Community#4237]
Hello, After downloading the latest firmware 1.5.10 on my Ethos Tandem X20RS transmitter. When I tried to use the text-to-speech function in the special function, when activated caused my radio to go immediately into "Emergency Mode," then, when going back to the special function icon to add another function the screen went blank and flashed, Emergency mode! the only way that I found to turn it off was to reboot the radio! This only happens when I try to use the text-to-speech I did the same test on several different models with the same results.

Thank you for your help.

Bobby

**Comment by Chandrayaan-git** [comment]
I think I have the same issue!
After updating my X20Pro from 1.4.17 to 1.5.10 the transmitter goes into Emergency Mode when trying to enter special functions when the selected model has a function with text-to-speech configured!

Thanks for help!
Martin

**Comment by Bobbysonic** [comment]
I`m sure they can resolve this issue! Frsky is excellent at correcting
bugs...

Bobby

**Comment by Chandrayaan-git** [comment]
I just configured a new Model to verify this problem.
Everything is fine until I set up a special function with the feature text-to-speech.
When I try to enter the special functions again, the transmitter goes into Emergency Mode

**Comment by bsongis-frsky** [comment]
It is strange, I don't remember any modification in this area between 1.5.9 and 1.5.10!

**Comment by Chandrayaan-git** [comment]
Hi Bertrand,
in my case, I never had 1.5.9 on my transmitter. I updated from 1.4.17 to 1.5.10

**Comment by bsongis-frsky** [comment]
Reproduced on simulator. 
1.5.9 is safe. 
And 1.5.10 won't stay longer than one week-end :(
