### ISSUE TITLE
Lua funtion no working

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#4239]
I have defined a Lua function that is implemented with the attached file and gives me the remaining % of the battery, this function worked perfectly in version 1.5.9, in version 1.5.10 it stopped working, it always gives the same value with regardless of the battery voltage received by telemetry.

*****************************************************************************************************************
-- Calculates the lipo percent
--
-- ******************************************-- 
-- to activate the source sript: choose this name in the model / edit / lua-sorce selection of the model (checkbox)
-- after actvating, this name is shown in the category "lua" in source - choice lists of mixers / LSWs / special functions 
-- without activating a source script in the models config, you are not able to see any "lua" category !
-- ******************************************

local translations = {en="Lipo perc"}

local function name(widget)
	local locale = system.getLocale()
	return translations[locale] or translations["en"]
end

-- ******************************************
-- This is the init handler, run once at start
-- ******************************************

local function sourceInit(source)
	source:value(10)												
	-- feel free to use other methods of the source class
	source:decimals(0)
	source:unit(UNIT_PERCENT)
end

local function CalcPercent(Cell_Voltage)
   
     -- the following table of percentages has 121 percentage values ,
     -- starting from 3.0 V to 4.2 V , in steps of 0.01 V     
 
    local Percent_Table = 
    {0  , 1  , 1  ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 , 
     2  , 2  , 2  ,  2 ,  2 ,  2 ,  2 ,  2 ,  2 ,  2 ,  3 ,  3 ,  3 ,  3 ,  3 ,  3 ,  3 ,  3 ,  3 ,  3 , 
     4  , 4  , 4  ,  4 ,  4 ,  4 ,  4 ,  4 ,  5 ,  5 ,  5 ,  5 ,  5 ,  5 ,  6 ,  6 ,  6 ,  6 ,  6 ,  6 , 
     7  , 7  , 7  ,  7 ,  8 ,  8 ,  9 ,  9 , 10 , 12 , 13 , 14 , 17 , 19 , 20 , 22 , 23 , 26 , 28 , 30 , 
     33 , 36 , 39 , 42 , 45 , 48 , 51 , 54 , 57 , 58 , 60 , 62 , 64 , 66 , 67 , 69 , 70 , 72 , 74 , 75 , 
     77 , 78 , 80 , 81 , 82 , 84 , 85 , 86 , 86 , 87 , 88 , 89 , 91 , 92 , 94 , 95 , 96 , 97 , 97 , 99 , 100  }   
     
     
      Cell_Voltage = Cell_Voltage * 100      
      
      local Table_Index       = math.floor(Cell_Voltage - 298 )      

      if Table_Index    > 121 then  Table_Index = 121 end 
      if Table_Index    <   1 then  Table_Index =   1 end 
	  
      local Battery_Percent   = Percent_Table[Table_Index]  
      
      return Battery_Percent    
  
end

-- ***********************************************************************
-- This is the wakeup handler, running periodically
-- in this excample the source value counts up whenever SH is pulled
-- ***********************************************************************
-- Cambiado valor minimo por la media del valor minimo y maximo
--************************************************************************

local function sourceWakeup(source)	
	local newVoltage = nil   
    liposensor = system.getSource("LiPo")    
    if liposensor ~= nil then  
--                 newVoltage = liposensor / liposensor:value(OPTION_CELL_COUNT)
	  newVoltage = (liposensor:value(OPTION_CELL_LOWEST) + liposensor:value(OPTION_CELL_HIGHEST))/2
	  newValue = CalcPercent(newVoltage)
	  source:value(newValue)
    end   
end

local function init()
  system.registerSource({key="batperc", name=name, init=sourceInit, wakeup=sourceWakeup})
end

return {init=init}
***********************************************************************************************************

**Comment by Alex00101** [comment]
This is because there was a change to how source:value works.
Basically supplying an option to source:value() is no longer working, to get cell lowest instead of 
    voltage = liposensor:value(OPTION_CELL_LOWEST)
you need to call
    lowestsrc = system.getSource({category=liposensor:category(), 
                                                    member=liposensor:member(), options=OPTION_CELL_LOWEST})
    voltage = lowestsrc:value()

**Comment by bsongis-frsky** [comment]
`liposensor:value(OPTION_CELL_LOWEST)` won't work as now `value()` can take an argument to set a value
