### ISSUE TITLE
 UGREEN aptX LL Bluetooth Receiver 5.0  Unable to connect to  X20s

### ISSUE THREAD

**Issue by Ashley757** [FrSkyRC/ETHOS-Feedback-Community#424]
I have been unable to connect to my UGREEN aptX LL Bluetooth Receiver 5.0 
everything works with my Bluetooth Anker speakers

**Comment by bsongis-frsky** [comment]
Duplicate of #160 . Not sure your bluetooth receiver is compatible? Please answer in #160
