### ISSUE TITLE
LUA not being readon 1.5.10

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4241]
Hello,
updated 1.5.9 to 1.5.10 and all external LUA scripts are not being read and can not be loaded (they are visible on the file manager).
there are no errors being printed on the sim debugger too.

has there bene any fundamental change in how LUA is handled in 1.5.10? if so where can i read about it?
thanks.

**Comment by bsongis-frsky** [comment]
What do you mean by "External Lua scripts"?

**Comment by i3dm** [comment]
> What do you mean by "External Lua scripts"?

all my zavionix scripts. which all worked great until 1.5.9 including.

**Comment by bsongis-frsky** [comment]
Any error?

**Comment by i3dm** [comment]
> Any error?

no errors are reported, and none of my scripts are shown in the menu. testing on X20S simulator 1.5.10.

**Comment by i3dm** [comment]
im only seeing the OS widgets, none of mine:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/8968780/b2627048-600f-41ed-b667-e3e746393135)

**Comment by bsongis-frsky** [comment]
Simulators Windows / Linux now use the same directory.
It's `<home>/.ethos/<radio>/...`

**Comment by i3dm** [comment]
C:\Program Files (x86)\FrSky\Ethos\X20S>Ethos 1.5.10 @ 08f7ba86 started!
000000 MENUS task started
000000 MIXER task started
000000 AUDIO task started
000000 loadDefaultFont()
000000 REQUESTS task started
000000 storageInit()
000000 Mount  succeeded
000000 Mount SD: succeeded
000000 SystemData::read(/radio.bin)
000002 Translation::load('/i18n/cn.i18n')
000003 Translation::load('/i18n/cs.i18n')
000004 Translation::load('/i18n/de.i18n')
000004 Translation::load('/i18n/es.i18n')
000006 Translation::load('/i18n/fr.i18n')
000007 Translation::load('/i18n/he.i18n')
000009 Translation::load('/i18n/it.i18n')
000010 Translation::load('/i18n/nl.i18n')
000012 Translation::load('/i18n/no.i18n')
000012 Translation::load('/i18n/pb.i18n')
000014 Translation::load('/i18n/pl.i18n')
000015 Translation::load('/i18n/pt.i18n')
001025 loadBitmaps()
001068 loadDefaultFonts()
**001072 f_opendir(C:/Users/User/.ethos/X20S/scripts) = error 2 (No such file or directory)**
001073 WD suspended
001073 ModelData::read('/models/model08.bin')
001074 playHaptic(duration=10)
001075 playFile('/audio/en/default/system/hello.wav', flags=0, id=5)
001075 WD resumed
001075 Home::doPreflightChecks()
001126 playFile('/audio/en/default/system/throttle-warning.wav', flags=0, id=9)
002078 RAM backup ...
002078 RAM backup written (size=435)

whats this path?

**Comment by i3dm** [comment]
> Simulators Windows / Linux now use the same directory. It's `<home>/.ethos/<radio>/...`

what is home? 
i have the sim at: 
C:\Program Files (x86)\FrSky\Ethos\X20S

**Comment by bsongis-frsky** [comment]
Release note updated

**Comment by i3dm** [comment]
Thank you.
one more question about lipo sensor on 1.5.10:
NumOfCells = widget.LipoSensor:stringValue(OPTION_CELL_COUNT)

this used to return 6 for 6 cells and now returns "19.20V".
how do i get the number of cells from the lipo sensor now?

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4208
