### ISSUE TITLE
Kontronik telemetry

### ISSUE THREAD

**Issue by mistermif** [FrSkyRC/ETHOS-Feedback-Community#4243]
Hi everyone, I have a problem, I can't see the telemetry of the kontronik kolibry 90 set to frsky telemetry and set s.port to x and then tried fport and also tried sbusin but nothing doesn't work.

**Comment by mawzthefinn** [comment]
What receiver? How are you wired in?

**Comment by mistermif** [comment]
As a receiver I use sr12 plus and radio xe s.port on channel 1, I've tried them all but it doesn't work

**Comment by mawzthefinn** [comment]
Sounds like possibly a Kontronik issue? The newer receivers with Channel Ports assignable to S.Port/FBus/SBus require strict adherence to the S.port timing spec and a number of older devices have needed firmware updates to adhere correctly to the spec (both 3rd party and FrSKy devices, the MVLSS was one such device to need an update) 

I'd suggest reaching out to Kontronik to see if they've tested against current FrSky receivers.

**Comment by mistermif** [comment]
Thanks for the advice, I contacted kontronik and they confirmed that a firmware update should come out shortly. Too bad, I'm going to have to wait

**Comment by mawzthefinn** [comment]
Good to hear Kontronik is addressing the issue.

I'll close this off as they are addressing it
