### ISSUE TITLE
1.5.10+ lua:  gpsSource:value(OPTION_LATITUDE) not supported any longer ?

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#4249]
A user on RCG has been unable to run the "Hobby4life" GPS map widget after updating to 1.5.10. 
The author has abandoned the hobby and no longer supports the widget. 
I tried to identify the problem and found the following:

"H4L" uses the following method to obtain lat/lon data.

Tthe config handler returns the telemetrySrc as a GPS source using the "form.addSourceField" method.
("Lat/Lon" options shall not be activated)

Then he determines the coordinates via "gps:value(OPTION_LATITUDE)" etc.

Since 1.5.10, these parameters are no longer supported in the src:value() method, resulting in invalid GPS data of the widget.

I also couldn't find an ad hoc way to specifically read the lat/lon data from this SRC return value of the configure handler.
(I always create dedicated lat/lon sources myself)

I assume the changes came from:
"[lua] source can now modify the value / internal unit and decimals of a DIY telemetry sensor"

If the value(OPTION_L..) options are intentionally no longer possible:
is there a short example of how to extract lat & lon from the GPS return value of the configure handler without the need of two separate lat/lon fields?

.. or was it accidentally forgotten?

regards

**Comment by Alex00101** [comment]
Udo, if I understand correctly this is the sane issue I've encountered with voltage sensor when trying to get number of cells.

Instead of providing option as an argument to value() you now call getSource with category and member of your "main" source but also specifying the option you need ie latitude. Then call value() on this 2nd source 

Hope enough is clear or I can post code example.

**Comment by strgaltdel** [comment]
Hi Alex, hmm,

do i understand correct?
you want to create a "child" source, based on on a "parent" one, paramter "member" is the parent ?

```lua
	local gpsSrc = system.getSource({name="GPS", category=CATEGORY_TELEMETRY_SENSOR })	
	local gpsLat = system.getSource({member = gpsSrc, category=CATEGORY_TELEMETRY_SENSOR, options=OPTION_LONGITUDE})	

```


this won't work, member has to be an integer


what generally works and how i did it from my first days is to define dedicated lat/lon sources by using telemetry labels as name (or member number) .
```lua
gpsStd.lat = system.getSource({name="GPS", category=CATEGORY_TELEMETRY_SENSOR, options=OPTION_LATITUDE })
```

But define a lat/lon source, based on a gps source, returned by a form method, i don't get it..? 
Could you give an example, please ?

regards
Udo

**Comment by Alex00101** [comment]
Yes at least this works for the voltage sensor etc. In your code above for the child source it should be gpsSrc:category() and gpsSrc:member(). Then you call value() on new source 

I'll post the code later as I'm not near my pc. In the meantime you can search for closed issues under my name here, in one of them Bertrand explained this to me.

Sorry bit hard to search from the phone, I'll try to find it myself.

**Comment by Alex00101** [comment]
Update #4208

**Comment by strgaltdel** [comment]
Ah, thanks !

got it working (-;

**Comment by bsongis-frsky** [comment]
In 1.5.12 those 2 forms will be allowed

```lua
source:value({options=OPTION_LATITUDE})
source:stringValue({options=OPTION_LATITUDE})
```
