### ISSUE TITLE
XACT servo telemetry.

### ISSUE THREAD

**Issue by mpjf01** [FrSkyRC/ETHOS-Feedback-Community#425]
Some of the telemetry from HV 5101 Servos seems to be incorrect

**Comment by mpjf01** [comment]
Telemetry from HV 5101 servo reports
SRV Current - maximum value that I can see when stalling the servo is 0.4a.
SRV Volt - Value shows 7.0V when Rxbatt shows 6.83V. Both connected to same power source
SRV Temp - Value shown starts at 36 degrees C on power up. Ambient is 18 degrees C.
SRV status  0. 

The most important concerns for the user are current and temperature. 

Some of the problem may lie with the servo. I have two, when both have been connected for the same time both have the same external case temperature (within 1.5 degrees) but one shows a temp of 35 degrees and the other 24 degrees in telemetry. The 24 degrees is close to the external case temperature measured with a separate thermometer. 

Not sure what SRV status means, not mentioned in the manual.

**Comment by bsongis-frsky** [comment]
I just changed the status so that it is comprehensible by an human:
0 is now shown as "OK"
1 is now shown as "Stall"

**Comment by bsongis-frsky** [comment]
I just made the servos names dynamic, SRV1, SRV2 etc.

**Comment by bsongis-frsky** [comment]
For the other problems I can do nothing, it's not Ethos

**Comment by mpjf01** [comment]
Thanks you for dealing with those so quickly. Much appreciated.
I will take the other matters up direct with FRSKY.
