### ISSUE TITLE
Trainer SBUS Emergency mode

### ISSUE THREAD

**Issue by 75Teea** [FrSkyRC/ETHOS-Feedback-Community#4252]
If the external module is active and SBUS is set in the trainer. A message about turning off the external module pops up. After confirmation, the radio goes into Emergency mode. The same thing happens in reverse. Trains SBUS is turned on and after turning on the external module, Emergenc mode again.  Tested on ethos 1.5.9 and 1.5.11.  
Video
https://www.youtube.com/watch?v=tOaEzbQVz2w

Martin

**Comment by bsongis-frsky** [comment]
Reproduced. The problem happens in PPM mode

**Comment by bsongis-frsky** [comment]
I have just found and fixed the issue (both modes). Would you please give a test with the next nightlies, before 1.5.12 is released? Thanks!
