### ISSUE TITLE
X20S HD nightly 1.5.12 usb connect error

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#4256]
Hi @bsongis I'm trying the new hdzero firmware that you gave us in discord. 
first step I have updated to latest 1.5.12 nightly firmware. after that whenever I connect usb it is saying usb device not recognized error. 
I'm using windows and it was working fine before.

**Comment by bsongis-frsky** [comment]
It should be fixed now

**Comment by bsongis-frsky** [comment]
Wrong clock on USB since I modified it for LCD
