### ISSUE TITLE
Proposed enhancement (UI): Indication of reversed channels in Outputs screen

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#4257]
Would it be possible to somehow add an indicator if the channel is reversed or not in the Outputs screen below?
The rational is, I'm migration my models to Ethos and at the same time switching some of my receivers to FrSky stabilized ones, so an ability to check which channels are reversed without clicking on each individual channel would be very convenient.

Thanks

![image](https://github.com/user-attachments/assets/e483e45a-20e0-48ae-9495-a1990d0b5d40)

**Comment by bsongis-frsky** [comment]
An idea how to show it?

**Comment by Alex00101** [comment]
I'd say perhaps a square brackets around the channel name and/or small crossed arrows icon?

**Comment by Skippydi** [comment]
One possibility would also be to display the reversed channel in a different color

**Comment by Alex00101** [comment]
For me personally it would work but would he unusable for people with color blindness?

**Comment by strgaltdel** [comment]
I'm not a friend of a too much "blinky blinky" screen, so i wouldn't change much

just an idea
![image](https://github.com/user-attachments/assets/af55ef22-6b8d-4074-a5df-bf1efa2cf4df)

**Comment by bsongis** [comment]
2 proposals:
- write "Inverted Channel" instead of "Channel"
- write "!Channel" or "Channel-" or "-Channel" instead of "Channel"

**Comment by Alex00101** [comment]
I'd vote for "Inverted" or "[Inv]"

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/ccb8182c-5765-4a50-871b-f76c03b03686)

**Comment by bsongis-frsky** [comment]
Ethos 1.5.16 will have an improved outputs screen with more information displayed!

![image](https://github.com/user-attachments/assets/415fe4ce-7995-4381-8c90-e289e42057be)
