### ISSUE TITLE
Unverified Developer

### ISSUE THREAD

**Issue by pandjarov** [FrSkyRC/ETHOS-Feedback-Community#4258]
Every time I install a new version on MacOS I get the:

**“Ethos Suite.app” cannot be opened because the developer cannot be verified.**

error and I have to manually override this check. A serious company like FrSky should pay attention to these things. Just verify the app with MacOS please. It's pretty lame to have your official software run like a garage hobby project.

**Comment by Nicholas-Luoyi** [comment]
Not easy to take a notarization from Apple. But I will try to learn how to get one...

**Comment by pandjarov** [comment]
Notarizing your macOS application is an important step to ensure it meets Apple's security standards. Here’s a step-by-step guide to notarize your app:

### Prerequisites:
1. **Apple Developer Account:** Ensure you have an active Apple Developer account.
2. **Xcode Installed:** Make sure you have Xcode installed on your Mac.
3. **App-Specific Password:** If you use two-factor authentication with your Apple ID, you will need an app-specific password.

### Steps to Notarize Your App:

#### 1. **Prepare Your App for Notarization:**
   - Ensure your app is code signed. If not, follow the code signing steps mentioned earlier.

#### 2. **Create a Compressed Archive:**
   - Create a `.zip` archive of your app:
     ```sh
     cd /path/to/your/app
     zip -r YourApp.zip YourApp.app
     ```

#### 3. **Submit Your App for Notarization:**
   - Use the `altool` command to submit your app for notarization. Replace the placeholders with your actual information:
     ```sh
     xcrun altool --notarize-app --primary-bundle-id "com.yourcompany.yourapp" --username "your-apple-id" --password "your-app-specific-password" --file /path/to/YourApp.zip
     ```
   - Example:
     ```sh
     xcrun altool --notarize-app --primary-bundle-id "com.example.myapp" --username "developer@example.com" --password "abcd-efgh-ijkl-mnop" --file /path/to/YourApp.zip
     ```

#### 4. **Check the Notarization Status:**
   - After submission, you will receive a Request UUID. Use this UUID to check the status of your notarization request:
     ```sh
     xcrun altool --notarization-info <RequestUUID> --username "your-apple-id" --password "your-app-specific-password"
     ```
   - Example:
     ```sh
     xcrun altool --notarization-info 12345678-1234-1234-1234-123456789abc --username "developer@example.com" --password "abcd-efgh-ijkl-mnop"
     ```

#### 5. **Staple the Notarization Ticket to Your App:**
   - Once your app is successfully notarized, you need to staple the notarization ticket to your app:
     ```sh
     xcrun stapler staple /path/to/YourApp.app
     ```

#### 6. **Verify the Stapling:**
   - Finally, verify that the stapling was successful:
     ```sh
     xcrun stapler validate /path/to/YourApp.app
     ```

### Example Workflow:

1. **Code Sign Your App:**
   ```sh
   codesign --deep --force --verify --verbose --sign "Developer ID Application: Your Name (Team ID)" /path/to/YourApp.app
   ```

2. **Create a ZIP Archive:**
   ```sh
   cd /path/to/your/app
   zip -r YourApp.zip YourApp.app
   ```

3. **Submit for Notarization:**
   ```sh
   xcrun altool --notarize-app --primary-bundle-id "com.example.myapp" --username "developer@example.com" --password "abcd-efgh-ijkl-mnop" --file /path/to/YourApp.zip
   ```

4. **Check Notarization Status:**
   ```sh
   xcrun altool --notarization-info 12345678-1234-1234-1234-123456789abc --username "developer@example.com" --password "abcd-efgh-ijkl-mnop"
   ```

5. **Staple the Notarization Ticket:**
   ```sh
   xcrun stapler staple /path/to/YourApp.app
   ```

6. **Validate the Stapling:**
   ```sh
   xcrun stapler validate /path/to/YourApp.app
   ```

By following these steps, you can ensure that your macOS application is notarized and ready for distribution, providing a smoother experience for your users.

**Comment by Nicholas-Luoyi** [comment]
Oh thanks for that!

**Comment by bsongis-frsky** [comment]
And pay 700$ a year ;)

**Comment by pandjarov** [comment]
FrSky should be able to afford it…

**Comment by spoke2570** [comment]
With the last several releases the Suite has been updating fine when I use the update button from within the app, but when app image is used for installation via the drag and drop method Mac OS makes me go through the rigamarole of manually approving the app. This means that the only time I have to do this is for testing versions of Suite. Unfortunately, it seems that I love to try all the new stuff so I basically have to do this every time. 

As a solution that gets past the bedding up with Apple maybe you could employ an update button that allows selection of the Suite version to install (forward or backward) and has stable and testing paths like the firmware update section.

**Comment by spoke2570** [comment]
Also I agree that paying for the Apple vetting is not worth much as I have gotten some pretty nefarious seeming apps out of the Apple-vetted list. That is to say that Apples stamp of approval means not much besides consumer convenience anymore.

**Comment by pandjarov** [comment]
Customer convenience means a lot.
