### ISSUE TITLE
V20 Kavan Simulator...

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4259]
Will you make a simulator for Kavan V20(HF modul TW-ISRM)? 
If I copy my models,the X20pro simulator works, but the data from the HF module and special functions are not correct.

**Comment by bsongis-frsky** [comment]
V20-EU will be added to the simulators list

**Comment by philippe-warnotte** [comment]
Merci beaucoup. Bonne journée.
