### ISSUE TITLE
LiPo (cells) sensor

### ISSUE THREAD

**Issue by JaroslavFalcon** [FrSkyRC/ETHOS-Feedback-Community#426]
It is possible to display, number of cells, sum of voltages,
but there is no possibility of min voltage value from the cells.
This is the most important parameter and it is missing.

- [x] LiPo sensor should be one sensor, not 8
- [x] Display LiPo value (default) / min / max
- [x] Display Cell1-6 value / min / max
- [x] Display Lowest Cell / Highest Cell / min / max

**Comment by islandflight** [comment]
Yes if you long press enter on the widget it gives you an option to display the min cell voltage. However no option to display only the lowest cell voltage you have to do it for each of the cells. Also come across an issue when using a 4s lipo the first 2 cells display the lowest voltage but the next two just read zero. I have created this as an issue

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121852666-1915ab80-ccf0-11eb-9f9a-b5b3a4b7d090.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121852861-5f6b0a80-ccf0-11eb-83ad-0a0f499402d1.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121852913-76116180-ccf0-11eb-8f77-7ba011f0b345.png)

**Comment by islandflight** [comment]
Will you be able to select this as a logical switch in order to create an alarm/value readout?

**Comment by bsongis-frsky** [comment]
yes with the same options system
