### ISSUE TITLE
FLVSS sensor breaks previous lua scripts in version 1.5.11

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#4262]
When reading the lipo sensor in version 1.5.11 it breaks previous lua scripts, specifcally:

numCells = sensor:value(OPTION_CELL_COUNT)  now returns the total value of the cells
and 
OPTION_CELL_INDEX does not seem to exist anymore.  I understand that changes do happen that can effect backwards compatibility but this seems like a radical change in that the behavior is completely broken with respects to previous code bases.

1. is there a way to pull the individual cells?
2. would it be possible to keep some amount of backwards compatibility?  I get it but this isn't the first issue that has been raised due to changes of api in point releases (this worked perfectly well in 1.5.9).

thanks,
Dave

**Comment by fdm225** [comment]
as a fyi, the script in the repo shows the following which matches my code above.

```
local function paint(widget)
  if widget.sensor ~= nil then
    lcd.font(FONT_L)
    local y = 10
    lcd.drawText(10, y, "Total = " .. widget.sensor:stringValue() .. " (" .. widget.sensor:stringValue(OPTION_CELL_COUNT) .. " cells)")
    y = y + 30
    for i = 1, widget.sensor:value(OPTION_CELL_COUNT) do
      lcd.drawText(10, y, "Cell[" .. i .."] = " .. widget.sensor:stringValue(OPTION_CELL_INDEX(i)))
      y = y + 30
    end
  end
end
```



issue is that when I pull it I am getting the total voltage:

![image](https://github.com/user-attachments/assets/c1b9da3c-c21d-4a44-9ff9-f5ba5d6b3238)

**Comment by Alex00101** [comment]
Same solution as #4249

**Comment by fdm225** [comment]
so as to have a code example (neither the other issues nor the example code actually show how to read this now)

```
                local lipoSensor = system.getSource({name="LiPo", category=CATEGORY_TELEMETRY_SENSOR })
                local numCells = system.getSource({member = lipoSensor:member(), category=CATEGORY_TELEMETRY_SENSOR, options=OPTION_CELL_COUNT})

                -- print("numCells: " .. numCells:value() .. "\n")
                for cell = 1, numCells:value() do
                    local cellSensor = system.getSource({member = lipoSensor:member(), category=CATEGORY_TELEMETRY_SENSOR, options=OPTION_CELL_INDEX(cell)})
                    -- local cellVoltage = sensor:value(OPTION_CELL_INDEX(cell))
                    local cellVoltage = cellSensor:value()
```

**Comment by bsongis-frsky** [comment]
Reminder to fix the example script

**Comment by bsongis-frsky** [comment]
I will add another possibility in 1.5.12

Those 2 portions of code will do the same thing:

```lua
source = system.getSource("LiPo", options=OPTION_CELLS_COUNT)
print(source:value())
```

and

```lua
source = system.getSource("LiPo")
print(source:value({options=OPTION_CELLS_COUNT}))
```

**Comment by Alex00101** [comment]
That would probably the best and saves a lot of getSource calls

**Comment by filduch** [comment]
Is (or will) be possible to get the voltage on an individual cell ?

**Comment by bsongis-frsky** [comment]
Yes it is.
`source:value({options=OPTION_CELL_INDEX(1)})`
