### ISSUE TITLE
Kavan V20 Simulator

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4265]
Kavan V20 Simulator work fine but the news models create are going into a virtual hidden repertory !  
C:\Users\MyName\AppData\Local\VirtualStore\Program Files(x86)\FrSky\Ethos\V20\models
And NOT to C:\Program Files (x86)\FrSky\Ethos\V20\models
(Windows 10)

**Comment by Richrfl** [comment]
Can you share a link for the Kavan V20?

**Comment by philippe-warnotte** [comment]
OK if I execute "simulator.exe" as administrator.
