### ISSUE TITLE
FWTM no power, 1.5.11 X10S-E

### ISSUE THREAD

**Issue by sande005** [FrSkyRC/ETHOS-Feedback-Community#4268]
Horus X10S Express, Ethos 1.5.11  Model in Master/SBUS for trainer.  **Frsky** FWTM module does not get power, so cannot bind to slave radio.

Note that while the power issue was fixed in Edge, and binding happened, on an X10S-E, there was still no recognition of the SBUS signal from the FWTM.  An external patch cord had to be used to the trainer jack.   In Edge, connecting an RX sbus directly to the external bay pins for SBUS does work correctly.  Testing of a direct RX connection in Ethos has not yet been done.

**Comment by bsongis-frsky** [comment]
It is implemented, but today only on Tandem radios (with the small size module bay). I suppose you use an adapter to fit to the Horus module size?

**Comment by mawzthefinn** [comment]
> It is implemented, but today only on Tandem radios (with the small size module bay). I suppose you use an adapter to fit to the Horus module size?

There's a JR bay version of the FWTM module as well as the Lite version, but as far as I'm aware it doesn't work on the X10's for internal Sbus trainer due to internal design limitations on the X10's. They don't support internal SBus trainer on OTX either IIRC.

**Comment by sande005** [comment]
> It is implemented, but today only on Tandem radios (with the small size module bay). I suppose you use an adapter to fit to the Horus module size?

Yes, I have the JR bay version on my X10S-Express. The Edge guys got the lower 3 pins (-,+,s) in the bay to come alive when trainer Master-SBUS was selected (ver 2.10.1).  According to Mike Blandford, and others, this is a change from the regular X10's that was never followed up on in OTX.  I can plug a receiver sbus directly into those pins, and then the bound RX passes along the info from the slave RX.  Used it for the last several months, with an old X8R stuffed in the bay.  Something is up with Edge 2.10.2 for the X10S-E - mine would go into Emergency Mode either right at boot, or after a power cycle or two.  I suspect it due to the trainer Master-Sbus being active for that model, but did not do testing on the different versions.  Just rolled back to 2.10.1 and all is behaving as it did.
The FWTM module does get power with Edge 2.10.1, but does not pass SBUS.  I have to use a jumper from it's jack to the trainer jack to get the input.
I was hoping that being a Frsky module, it would just work with Ethos.  But no power, or anything else.
For me, may be moot - now that I have a second X10S-E, bluetooth may suffice - will know in 2 days, when I go to my clubs weekly training day to teach.  If bluetooth has issues, I'll stuff the trusty X8R back into the module bay and use the TX with Edge as the master.
