### ISSUE TITLE
Add function to assign switches to individual trainer channels

### ISSUE THREAD

**Issue by sande005** [FrSkyRC/ETHOS-Feedback-Community#4269]
In OpenTX/Edge, I am able to turn on/off individual trainer channels.  Helpful for raw beginners to have throttle and/or rudder slave inputs ignored and be controlled by Master only, to be introduced later.

**Comment by mawzthefinn** [comment]
Every trainer channel has a configurable active condition in ETHOS, so this function is available right now.

**Comment by hrenz** [comment]
the PWM parameters for the trainer should be as freely adjustable as with opentx

**Comment by mawzthefinn** [comment]
> the PWM parameters for the trainer should be as freely adjustable as with opentx

What can you do in OpenTX that you can’t in ETHOS?

**Comment by sande005** [comment]
> Every trainer channel has a configurable active condition in ETHOS, so this function is available right now.

Oops - didn't appreciate that function in my initial attempts to replicate a setup from Edge/OpenTX.  Thanks for pointing it out.
