### ISSUE TITLE
Issue Closing

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#427]
Issue 415 has been Closed and flagged as a Bug with a comment of added to 1.0.8 milestone.

1. The fault is not fixed, so can I please ask why the call is closed?
2.  Should the reference to 1.0.8 be 1.0.9?
3. There is no indication as to when the fault will be fixed.

As a glider flying I will have to go back to 1.0.7 untill resolved.
Regards

**Comment by bsongis-frsky** [comment]
I have used the wrong milestone. It's 1.0.9, which will be released later today once all reported bugs have been fixed
