### ISSUE TITLE
[ELRS Lua] Add back button support

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#4273]
I see this new error in 1.5.11 that I do not recall seeing in 1.5.10.
![20240714_142813](https://github.com/user-attachments/assets/ae2c701f-e412-47c5-845c-ce7cc6176b64)

Also related to the ELRS Lua script, the available options in "Switch mode" do not update if you change to a packet rate that has different options until you exit the Lua and go back in, then it updates the options.  

Finally, it would be nice if when you press the Back button when on a Configure page for a device (e.g. TX, RX) it would go back to the list of devices rather than exiting the script entirely.

**Comment by bsongis-frsky** [comment]
You are using an old ELRS script. There is no `beginExpansionPanel` in current one

**Comment by bsongis-frsky** [comment]
I rename the issue. The 2nd part is interesting

**Comment by bsongis-frsky** [comment]
Return to the list of devices is working, even with 1.5.11

**Comment by kakashi2018** [comment]
@bsongis-frsky  pressing back button on screen is working as expected but pressing the physical return button exits out of devices screen.
