### ISSUE TITLE
Brain/Ikon Lua in Ethos 1.5.11 odd pages only in settings.

### ISSUE THREAD

**Issue by RCHeloPilot** [FrSkyRC/ETHOS-Feedback-Community#4274]
With the Brain/Ikon FBL Lua, only the odd settings pages are displayed in Ethos 1.5.11.  The even pages are skipped.
https://www.helifreak.com/showthread.php?t=950891#post8762239

**Comment by bsongis-frsky** [comment]
This one has already been reported. The script didn't ack the key events. It should be fixed now (it's not part of Ethos)
