### ISSUE TITLE
REQUEST: is it possible define the type of operation of each switch on the 6-switch pad of the X20S

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#4275]
hello all
will it be possible to:
define the type of operation of each switch on the 6-switch pad of the X20S
For example
whether or not to associate 2 or 3 switches (for example the 3 on the left) in toggle mode
be able to set this or that switch in unstable mode
be able to define this or that switch in stable mode
in short, do what you want with this block of 6 switches, model by model

best regards

**Comment by mawzthefinn** [comment]
You can set the function of the FSW's in the Edit Model Menu

options are:
2-pos (each switch is a 2-pos on/off switch)
3-pos (each block of 3 switches is a 3-pos on/off, not available on the TWIN X-Lite as it has 4 buttons)
6 pos (4 pos on TWIN X-Lite)
6 pos with off
Momentary (every switch is a momentary)

There's a current request that's not implemented yet to allow each set of 3 switches to have different functionality set.
