### ISSUE TITLE
Ethos X20, PlayTrack option missing fromSpecial Functions menu

### ISSUE THREAD

**Issue by JimHarris64** [FrSkyRC/ETHOS-Feedback-Community#4276]
Trying to set up Spoken Warnings for 'Motor armed' and 'Motor Disabled'. Have copied two .wav files into the Sounds folder but in Special Functions the option to Play Track is not there, only Play Audio, which doesnt seem to request a file name. Am I missing some LUA files or something????

**Comment by mawzthefinn** [comment]
You need to add a Play Track action within Play Audio.

Play Track and Play Value became Actions within Play Audio with 1.5

Note the sound locations changed with 1.5 as well, I'd suggest reviewing the current ETHOS Manual linked on the main Github page.
