### ISSUE TITLE
Error message when I try to update Ethos Suite 1.5.7

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#4277]
Operation system PC: Windows 10
Ethos Suite used: 1.5.6
Ethos suite that I try to Update: 1.5.7

I try to update Ethos Suite inside the version 1.5.6, I have a follow message in the end of the download (100%).

I have update manually Ethos Suite 1.5.7 download the file from the web site

![updateethos](https://github.com/user-attachments/assets/005e5f83-70fc-45ac-b1e8-c8068209ebdc)

![updateethos002](https://github.com/user-attachments/assets/d68f82b1-f39a-4fa9-917b-43a076079154)

![updateethos003](https://github.com/user-attachments/assets/b8562972-d068-4eea-b27c-1291f3355041)

**Comment by mawzthefinn** [comment]
Run Suite as administrator and it should update.

**Comment by Nicholas-Luoyi** [comment]
Yes. Suite has an issue for writing files in 1.5.6. And it should be fixed in 1.5.7. (I hope it won't ask for administrator)
