### ISSUE TITLE
Struggling to Update R9MX

### ISSUE THREAD

**Issue by Toolroom1** [FrSkyRC/ETHOS-Feedback-Community#428]
X20S Ethos FW 1.0.8
TD ISRM FW 2.1.8
I have the R9MX setup as redundancy to an Archer SR6. I have downloaded FW 1.3.2 for R9MX and have copied it to the Firmware folder, Switched on TX and Aircraft, found the new FW update click on OTA then RED leds appear on both receivers and the radio just says BIND. Please advise where I'm going wrong.

Many Thanks

Trevor Bartley

**Comment by OldGazer** [comment]
Do not power up the SR6.

**Comment by Toolroom1** [comment]
R9MX will not work after FW 1.3.2 Update.

My R9MX is normally set as redundancy to my SR6 so I powered the R9 directly and did an OTA update to FW 1.3.2, after it said Success I restarted the system as normal powering the R9 from the SR6 but the R9 stayed red, and would not rebind, so I powered it separately again and tried to REGISTER it but no it will not connect. I have now cut the SBUS wire, which was going to the SR6  and added it to the power wires and plugged into the top of the X20S to flash it again but the TX does not seem to power the R9, please can someone advise where I'm going wrong, does the port on the TX need to be switched on?




Many Thanks 




Trevor Bartley

**Comment by Toolroom1** [comment]
Update, The TX is powering the receiver but TX shows device not responding.  Please advise how to get my RX working again. Note I have downloaded the software again and tried several times but no luck. 

Many Thanks

Trevor Bartley

**Comment by OldGazer** [comment]
An EXTERNAL UPDATE uses S.Port, not S.Bus.

**Comment by Toolroom1** [comment]
OldGazer, "An EXTERNAL UPDATE uses S.Port, not S.Bus" how does this help me?

Trev.

**Comment by FrSky-GX** [comment]
once the OTA procedure crashed, the Rx must updated with the s.port cable

**Comment by Toolroom1** [comment]
I have updated through the S-Port this morning then Rebound and all is
working well once again. Thank you for your help.

Kind Regards

Trevor Bartley
