### ISSUE TITLE
Enhancement: Model ID flow... 

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#4283]
I'd like to suggest an enhancement to ETHOS. When adding a new model, ETHOS should automatically select the next free model ID in the RF section. This would make it easier to add new models without having to manually assign a model ID or accidentally using an existing model ID. If a model ID is already in use and manually selected, a warning should pop up asking if the ID should be kept or made unique.

**Comment by pmullen503** [comment]
This would be welcome addition. That, and a warning if importing a model causes an ID conflict.

Even a text file showing assigned and/or available model IDs would be helpful.
