### ISSUE TITLE
ethos  - no Voice

### ISSUE THREAD

**Issue by JimHarris64** [FrSkyRC/ETHOS-Feedback-Community#4285]
I've a new X20, with all firmware etc up to date according to Ethos Suite. All I want to achieve is to get my models to give me a ''Motor Armed' or 'Motor disabled' message depending on the setting of a switch. The Ethos manual (1.5.7) tells me to use Special Function 'Play Audio', but the entry screen wont allow me to do this. The 'Voice' field is greyed out as is the 'Sequence'. So I'm stumped. Should it reqlly be this difficult? The Manual tells me that there will always be a Voice one.....

**Comment by craigywsm** [comment]
Hi @JimHarris64  in the latest ethos suite (1.5.8)  have you checked to see if you have the latest sound pack?

**Comment by mawzthefinn** [comment]
You do not have the Audio installed correctly. Use ETHOS Suite to update your Audio and you will get a minimum sound pack installed as a default voice.

**Comment by JimHarris64** [comment]
Thanks - but HOW?
On Ethos Suite I can see there is a tool called Audio Manager, which asks for  'List to be transcoded' and 'Radio audio Files'. Where will all that info come from?
Or am I barking up the wrong tree?
Thanks for your patience again!
Jim Harris

**Comment by JimHarris64** [comment]
Hi Craig
Thanks for your reply, but I'm baffled. Ethos suite tells me that 1.5.7 is the latest, and tells me that my radio is up to date.
And what is the 'sound pack', where does it live, and how do I know whether there is a later one? The Audio Manager in Ethos Suite isn't any help.
I'm sure these are all ignorant numpty questions, but how am I to learn?
Thanks for your patience.
Jim Harris

**Comment by craigywsm** [comment]
If you have an audio pack downloaded you can select it in System --> General
![image](https://github.com/user-attachments/assets/cb8e8fbd-3b56-43a3-b75b-d2b335367c1b)

**Comment by OldGazer** [comment]
Craig:
The sound files live in the audio folder on the SD card.
The "sound pack" is a collection of the default sound files in the wav format.
Cliff Hipsher
ICC USN (Ret.)
I.A.M.B.K.
Safety is NO accident.
I Ride.  Therefore I am.... 

    On Wednesday, July 17, 2024 at 11:38:14 AM EDT, JimHarris64 ***@***.***> wrote:  
 
 

Hi Craig
Thanks for your reply, but I'm baffled. Ethos suite tells me that 1.5.7 is the latest, and tells me that my radio is up to date.
And what is the 'sound pack', where does it live, and how do I know whether there is a later one? The Audio Manager in Ethos Suite isn't any help.
I'm sure these are all ignorant numpty questions, but how am I to learn?
Thanks for your patience.
Jim Harris

**Comment by strgaltdel** [comment]
btw.
- choice of language ,
- voice pack &
- folder structure

is also documented in lothar's manual
System Setup / General / audio

**Comment by JimHarris64** [comment]
Thanks for that. How do I access 'lothar's manual'?

**Comment by mgsanna** [comment]
Lothar manual is official manual that you can download from ethos suite or GitHub (latest ethos suite ) give you all languages manualsInviato da iPhoneIl giorno 17 lug 2024, alle ore 23:26, JimHarris64 ***@***.***> ha scritto:﻿
Thanks for that. How do I access 'lothar's manual'?

**Comment by pmullen503** [comment]
Launch Suite, go to "documentation" to download the latest manual.

The audio manager will transcode custom sounds that you make with software to the proper format for the TX to play.

You can also download premade custom sounds packs ("Amber" is a popular one) which has a ton of custom announcements premade. You can make that voice 2 in Settings/general for example.

**Comment by craigywsm** [comment]
Hi @JimHarris64 
The sound files are on your SD card there are a few folders

sdcard:\audio\en\default
sdcard:\audio\en\gb
sdcard:\audio\en\us

I have also added custom audio files mine and selected them in System --> General Language -->Language
![image](https://github.com/user-attachments/assets/05c6594c-7105-482b-8573-e4125f558363)

The folders for this are:
sdcard:\audio\en\Amber
sdcard:\audio\en\Custom
