### ISSUE TITLE
Instant Trim Limitation

### ISSUE THREAD

**Issue by bbdmarch** [FrSkyRC/ETHOS-Feedback-Community#4286]
Hi there

I've been playing with instant trim after a friend had an issue with instant trim, after transferring from Openxt to Ethos

When flying the plane and using instant trim he found that the stick position wasn't transferred to the trims in its entirety, it stopped at the trim limit, which was set to 25%

I have since tested on Ethos 1.5.11, on an x20s and the instant trim will only allow the trim maximum to be the current trim maximum and not the current stick position, so if the trim limit is set to 50% and the stick position is at 100% the trim is set to 50%.

I understand that this is possibly by design as it would prevent over travel of the servo, however it can cause problems when first flying an aircraft, as there may not be enough trim to correct for flight issues, however good the set up of the model is.

I have three ideas as a solution for this,

1. Have the instant trim overrule the current trim maximum on a permanent basis
2. Have a user selectable option that allows for the choice of the trim limit in instant trim
3. Have a user selectable option that allows for instant trim to overrule the trim maximum

Regards

**Comment by mawzthefinn** [comment]
The trim limits are your control over this. 

They are the limits of allowable trim. Instant Trim is just an alternate method of setting your trim positions.

The solution is quite simple, set your Trim Maximums to the range you want to be able to trim to.
