### ISSUE TITLE
Error in the french manual 1.5.8

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4288]
Error in the french manual [FR] Ethos User Manual 1.5.8.pdf 
Page 29: read path: bitmaps/user and not: bitmaps/users 
idem FR Ethos User manual 1.5.10.pdf at page 26.

**Comment by samsab1** [comment]
where can we find this french user manual?

**Comment by mgsanna** [comment]
> where can we find this french user manual?

Simply here in the splash page of this repository, or with the latest version of ethos suite, there is a tab that download it

**Comment by philandroid36** [comment]
Bien vu. Sera corrigé dans la prochaine version.
