### ISSUE TITLE
stick switch polling on ethos pro

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4289]
Small issue when using stick switches on the PRO and PRO AW radios.

The 'button press' does not always get detected if pressed very quickly.   It feels sometimes like you have to press and hold the switch for it to work.

This would not be an issue if using toggle switches - but with a momentary switch the button press can be missed.

Maybe putting in an option that

if button type == momentary then {
    - increasePolRate()
 }

or similar.

**Comment by WhiskeyGolf** [comment]
I also have the problem with momentary switches on sticks.

**Comment by jasalca** [comment]
Where I notice it the most is in the function switches. Sometimes I have to press them several times to make it work. My radio X20 Pro AW

**Comment by jasalca** [comment]
With the latest update 1.15.16-1.15.17 now the radio is faster, I no longer have that problem. I think it is already solved.
