### ISSUE TITLE
Current sensor telemetry issue (X20 - 1.08) 

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#429]
> Hello,

I am using the X20 on latest 1.08 firmware.
I created a "Max Current" screen. But when pushing throttle stick back to zero the max current jumps back to a negative value. This value is between - 0,2A and - 2,1A even though the real max current is for example 52A in my case. 

Live current value works fine. 

I have not changed any settings when entering the current menu. Issue is with Frsky Current Sensor and also non-Frsky products. 

![20210519_181608](https://user-images.githubusercontent.com/39466112/121177646-f30a8a00-c85d-11eb-882f-0b4395c7a17b.jpg)

**Comment by OldGazer** [comment]
What current sensor are you using?  I'm getting current telemetry from an F4 flight controller running BetaFlight that has an onboard current sensor.  The current displayed in my FPV goggles matches the current displayed by the radio...

**Comment by Hobby4life** [comment]
> What current sensor are you using? I'm getting current telemetry from an F4 flight controller running BetaFlight that has an onboard current sensor. The current displayed in my FPV goggles matches the current displayed by the radio...

He created a Max Current sensor widget. It does not hold max value.

**Comment by combat-marcus** [comment]
> > What current sensor are you using? I'm getting current telemetry from an F4 flight controller running BetaFlight that has an onboard current sensor. The current displayed in my FPV goggles matches the current displayed by the radio...
> 
> He created a Max Current sensor widget. It does not hold max value.

How does it hold max value?

**Comment by Hobby4life** [comment]
Long press on the "sensor", you will get options

**Comment by combat-marcus** [comment]
> Long press on the "sensor", you will get options

What settings are needed there?

**Comment by combat-marcus** [comment]
> Long press on the "sensor", you will get options

What settings are needed there?

**Comment by combat-marcus** [comment]
> Long press on the "sensor", you will get options

What settings are needed to See max current? 🤔

**Comment by bsongis-frsky** [comment]
Is it better in 1.0.9 candidate 2?

**Comment by bsongis-frsky** [comment]
Please try with 1.0.9 candidate 3, and discover your sensor again. The limits should be created right now.
Feel free to reopen the issue if needed

**Comment by combat-marcus** [comment]
> Please try with 1.0.9 candidate 3, and discover your sensor again. The limits should be created right now.
> Feel free to reopen the issue if needed

Thank you mate 🙂👍
I am going to test 1.09 candidate 3 today or tomorrow.

**Comment by combat-marcus** [comment]
> Please try with 1.0.9 candidate 3, and discover your sensor again. The limits should be created right now.
> Feel free to reopen the issue if needed

Awesome, all telemetry values work fine now 👍🙂👍 Thank you very very much!
