### ISSUE TITLE
1.5.12n sim: radio path option won't work

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#4291]
First:
I'm not excited about the new sim options,
but  I'm very, very excited (-;
excellent move!

Still, it seems that the radio option doesn't work 
(win)

(1)
the typical win paths seem to be converted (backslash replaced by slash)
(blue)

but not to the radio parameter
(red)

therefore radio.bin is not saved correctly
the radio has to be configured at every start

![image](https://github.com/user-attachments/assets/131aab23-a59e-4b83-833b-16e61c66f472)

(2)
even if I use a slash in the path options, the radio path does not work

the other options seem to be OK,
finally I have separate model files for all my environments 

Thanks a lot! 

Udo

**Comment by bsongis-frsky** [comment]
the --radio-settings must give a file!

**Comment by strgaltdel** [comment]
as we say in germany:
"Once you do it right, it works immediately."


Thanks !
