### ISSUE TITLE
NO VIDEO ON X20HD

### ISSUE THREAD

**Issue by Yoram55** [FrSkyRC/ETHOS-Feedback-Community#4292]
Tried  3 different HDzero TX.
Updated through Ethos Suite 1.5.8.
It shows everything up to date, except for the video component, which is listed but with no status. 
Uprate was successful, but pushing the DSP button shows a flash screen then the channel and frequency on the top right, then a black screen. 
The Ethos Suite does not have the video tab on the top row of the various systems. 
Please advise. 
Thanks

**Comment by bsongis-frsky** [comment]
Which release of Ethos have you flashed? For 1.5.12 you need a new FRSK for the video components.

**Comment by Yoram55** [comment]
Thanks, I will check and post here.

**Comment by Yoram55** [comment]
Here are the components I am using:
F/W 1.5.11. FCC
BOOTLOADER 1.4.15
MODULE VERSION 2.2.6
ETHOS SUTE 1.5.8 

Which one do I need to upgrade, ad can you send a link to the update?
Many thanks
Yoram

**Comment by Yoram55** [comment]
Ad the Suite says they are all up to date.

**Comment by bsongis-frsky** [comment]
Yes, but the FRSK for Video components is still not ready!

**Comment by bsongis-frsky** [comment]
But ... you are using 1.5.11? So it should be working already as nothing has changed!

**Comment by Yoram55** [comment]
I understand, but it does not. Except for the video components, which show no data on version or update, all the rest is up to date. 
Can I find the video component file (ver 2) somewhere and flash it manually?
Thanks
Yoram

**Comment by bsongis-frsky** [comment]
We are not english. When you say a "flash screen", do you mean a "splash screen"?

**Comment by Yoram55** [comment]
Yes, sorry for the typo.
Splash screen definitively, with a logo on it saying "X20HD" then below that " waiting for input signal", staying for several seconds then the screen goes black. on the TX side I have an HDZero TX with antenna connected to a Nano RunCam, which get very hot which i interpret as transmitting.
Thanks
Yoram

**Comment by kakashi2018** [comment]
@Yoram55  can you check if you are able to change channels after the waiting for input signal screen? If yes, it might be an issue on your hdzero tx side. what other hdzero rx do you have other than x20hd radio?  several factors cause the x20hd not to pick up signal from the hdzero tx like 1080p mode, high refresh mode 90 fps. If you have other rx, please put all other settings of camera and tx to default and try with x20hd for now, it should work. Other wise we would have to wait for the new hd(frsk file) component update which will work with all those settings

**Comment by Yoram55** [comment]
Thank you, but I have not other means to see the video signal except for the X20HD, no goggles or other display. I have tried 3 HDZero systems with the same result. I will borrow some goggles and check. But I can  change channels and frequency on the X20HD. I will update here.
Thanks
Yoram

**Comment by MIKE-DAILEY** [comment]
Tested my X20HD upkit (V1 HD) running ETHOS 1.5.11. with my original old HD bench test setup here and I have video https://www.rcgroups.com/forums/showpost.php?p=49484097&postcount=18651

**Comment by Yoram55** [comment]
Thanks, will check it.

**Comment by MIKE-DAILEY** [comment]
Now tested with ETHOS 1.5.12., new video component and newest HDzero VTX Whoop firmware.  https://www.rcgroups.com/forums/showpost.php?p=49484097&postcount=18651

**Comment by Yoram55** [comment]
Problem slved with new update which showed video component package. Works flawlessly now.

**Comment by Yoram55** [comment]
SOLVED
