### ISSUE TITLE
[feature request] add luascript commands to send custom S.Port message over bluetooth

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#4296]
apologize if this is available but I have been unable to get Ethos to send a custom sensor message from the radio to the bluetooth receiver.  I have created a custom sensor in the model using appId=0x5100 but nothing I do gets it to either update the sensor's value on the radio nor bluetooth.  Asking for a new feature as am looking to send info to a ground station that is not included in the telemetry stream (e.g. throttle value and reset switch).

local sensor = sport.getSensor({module=0, band=0, rxIdx=1, physId=0x1F, primId=0x31, appId=0x5100, value=0x80})
if sensor:pushFrame({module=0, band=0, rxIdx=1, physId=0x1F, primId=0x31, appId=0x5100, value=0x80}) == true then
        print("frame pushed")
end

**Comment by RealTadango** [comment]
sensor = sport.getSensor({appIdStart=0x5000, appIdEnd=0x51FF})

frame = sensor:popFrame()

	if frame ~= nil then
		value = frame:value()
		prim = frame:primId()
		app = frame:appId()
       end

This works for me

**Comment by RealTadango** [comment]
And to send data to the receiver:

sensor:pushFrame({physId=0x1B, primId=0x31, appId=0x5000, value=value})

**Comment by fdm225** [comment]
Hi @RealTadango ,
Thank you for the response, my question is will this be sent via bluetooth as well or only to the receiver?  I ask as I don't have an actual sensor in the plane and am looking to send current state (e.g. throttle, switch position, etc) to the ground station via bluetooth.  I'll update my code to test it tonight but again, thank you for the response.

dave

**Comment by fdm225** [comment]
Unfortunately I don't think that sensor:pushFrame will work for my needs here as it was designed for the purpose of sending information to a sensor (as @RealTadango said) and isn't also pushed on to the bluetooth stack as a S.Port telemetry message.  @bsongis any insight if there is currently a way to send a custom value to a ground station using the existing lua api?  if not, is this something that could be added as a feature?

thanks,
Dave
