### ISSUE TITLE
X20RS - Volume sourced from slider does not take affect until the a model has been selected

### ISSUE THREAD

**Issue by Oats87** [FrSkyRC/ETHOS-Feedback-Community#4297]
My radio is configured to source the main volume from Pot3, and in mode "Often"

When I have the option "Select model at power on" set to "ON", and the radio boots, the main volume is very low when it's playing the "hello.wav" but if I am fast enough to select a model, then the option takes effect and the volume is corrected to the corresponding level of my Pot3.

I am running Ethos v1.5.11 and my radio is a X20RS.

**Comment by jasalca** [comment]
The same thing happens to me and I have already opened a bug with another utterance  #4077

**Comment by jasalca** [comment]
The problem is that this failure does not occur in the simulator

**Comment by jasalca** [comment]
The problem is still active. With the updates it has not been corrected.

**Comment by spoke2570** [comment]
@jasalca - Are you running your volume control out of the System/General tab or using a special function, or global special function? 

On my X20S controlling volume from the System/General I use Pot 1 for vario volume and Pot 2 for main volume. The volume is controlled as expected, no oddities during startup. I could see where if it was a special function, even a global one it would need to load the model (or any model for global function) before it recognizes that the volume should not be what is hard set in the System/General tab.

**Comment by Oats87** [comment]
@spoke2570 I'll give it a try again with 1.5.18.

**Comment by spoke2570** [comment]
I regard this one as strange because I have been using that setup on my X20S which I purchased right after they dropped, definitely before 1.5. It has always worked perfect.

**Comment by jasalca** [comment]
Are you running your volume control out of the System/General tab or using a special function, or global special function?

 My answer is no.
 I only have the volume  asigned to a potentiometer.

**Comment by spoke2570** [comment]
Um, so the first of the three options? The question was in regard to where the pot is being applied to the volume.

**Comment by Oats87** [comment]
This is seemingly fixed in Ethos 1.6.0!!!!!

**Comment by bsongis** [comment]
Indeed, last minute fix!
