### ISSUE TITLE
1.5.12n: lua can no longer access user directories at root level

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#4298]
The Sim parameters added with 1.5.12 are a great relief,
However, scripts that needs loading files from user directories can no longer “reach” these if necessary
(at least in the Sim)
Apparently there is no longer direct access to the “root” level of the directory structure

Example:
I used to have images always in an “images” directory on root level (/images/...)
The images contained therein can now no longer be loaded/accessed
(Start of Simulator.exe without parameters)
Error message:
![image](https://github.com/user-attachments/assets/26451372-7964-48ea-98c2-90dad02efc25)

if I copy the folder into the scripts directory and change the path from “/images/..” to “scripts/images..” there are no problems.
![image](https://github.com/user-attachments/assets/3783091c-f7b7-4891-8a81-5e2ac763ac90)

so we have 2 alternatives:

1:  it's by design, leave it as it is, we have to adopt the scripts if affected

2:  will be revised to restore the old status
(would expect them to be accessible in  "users" directory if "rerouted")

regards
Udo

**Comment by Alex00101** [comment]
That (alternative 1) would be a substantial issue for my scripts, I'd much prefer the status quo to be restored.

**Comment by strgaltdel** [comment]
me too....

and just to be more precise:

i tried following locations (win):
%userenvironment%/.ethos/x18s/images (the by now standard user path, sim was started without parameters)
%installdir%/images  (the install directory, here it worked until 1.5.11, sim was started without parameters)
%EthosUserpath%/images (the dedicated user path, set by new parameter during sim start)


always tested with lcd.loadBitmap() method

**Comment by bsongis** [comment]
It should be re-routed to the user path

**Comment by bsongis-frsky** [comment]
Would you please check that the latest nightlies are OK for you?
