### ISSUE TITLE
No model images

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#430]
X10s isrm 2.1.6
Ethos 1.0.8

Model images are no longer displayed.
The image names are there but when you click on the name no image appears.
Thanks
Scott

**Comment by bsongis-frsky** [comment]
Perhaps your bitmap is too big? We need RAM for the UI on the radio, I have set a limitation on those bitmaps

**Comment by Liverboy77** [comment]
I have always used the same bitmaps what is the max size and is it still png format?

**Comment by bsongis-frsky** [comment]
but if you have 10 models with this bitmap, Model Select won't work because it needs more RAM than available ...

**Comment by bsongis-frsky** [comment]
use reasonable size for your bitmaps, there are some default samples in the SD

**Comment by Liverboy77** [comment]
Ok I will have a go at re sizing them.
Thanks

**Comment by Liverboy77** [comment]
I resized the bitmaps to 180 x 160 and they work 
Thanks
