### ISSUE TITLE
 Resolving Random "No Map" Issue on Frsky X20RS and RB30+ Setup

### ISSUE THREAD

**Issue by 3Dholic** [FrSkyRC/ETHOS-Feedback-Community#4302]
A friend of mine asked for help setting up his new Frsky X20RS and RB30+ along with TDMX (Black)...

First, we updated the TX to version 1.5.11 and ISRM to 1.1.13.

![1](https://github.com/user-attachments/assets/89a02785-7549-421b-b103-23639393fa45)

Next, we updated the TDMX to version 1.0.10 via OTA.

![2](https://github.com/user-attachments/assets/e396896b-1525-4315-be52-fb342490704b)

Finally, we updated the RB-30 through the S.Link from the TX.

![3](https://github.com/user-attachments/assets/930cfd8f-348a-429a-9417-64a3a56c2b40)

Here is the TDMX screen:

![4](https://github.com/user-attachments/assets/f840e32c-93f7-4b42-a94c-38921bf4f6d5)

![5](https://github.com/user-attachments/assets/8da528ed-36fd-4365-8f87-ef54bf1956b0)

![5](https://github.com/user-attachments/assets/a35f2d6b-b0d7-4353-9c1c-453eef110cef)
![6](https://github.com/user-attachments/assets/b3275627-4f55-4a00-8c9e-b578e2e90d8c)

Up to this point, everything was fine. I could see the telemetry data through RB-30+ on the TX screen.

However, when I go to Device Config and try to adjust RX1 Map, the screen randomly shows No Map (dull) on some channels.

First trial, 9-10 has issue

![8](https://github.com/user-attachments/assets/76083232-3fb7-42b5-be64-e4cfc2be4f61)
![7](https://github.com/user-attachments/assets/cc6a83ab-08dd-4c38-b76b-c9047a0a9606)

Second trial, 7-8-9-10 has issue
![9](https://github.com/user-attachments/assets/47dbf0ba-4d1a-4bd4-81a9-573f4dffa526)
![10](https://github.com/user-attachments/assets/984adfea-341e-416f-8e3e-0d72c0271900)

Is there a way to overcome this problem ?

**Comment by mawzthefinn** [comment]
Update TDMX to latest firmware (1.0.13), version 1.0.10 is old and will have telemetry issues with TD ISRM Pro 1.1.12 or later

**Comment by 3Dholic** [comment]
@mawzthefinn , good catch... I think we missed to update the TDMx and only updated the other rx, TDR18...

Will give it a try and update about the status...

**Comment by 3Dholic** [comment]
@mawzthefinn , thanks a lot... Issue resolved...
