### ISSUE TITLE
Enhancement request: support Spektrum forward programming via multimodule

### ISSUE THREAD

**Issue by doppleganger53** [FrSkyRC/ETHOS-Feedback-Community#4303]
Now that multimodule telemetry is supported, this should be possible. If not supported via this project, could there be at least a Lua API to make it easier to interface with the two-way communication necessary for forward programming?

### Discussed in https://github.com/FrSkyRC/ETHOS-Feedback-Community/discussions/4164

<div type='discussions-op-text'>

<sup>Originally posted by **Crunch69** June 16, 2024</sup>
please add the Lua for "DSM tools" Spektrum forward programming advanced telemetry.  attached is the lua for edgetx/otx please port it over to ETHOS
this will allow full control and programming for Spektrum smart ESC, RX and Telemetry
[DSMTools-main.zip](https://github.com/user-attachments/files/15856293/DSMTools-main.zip)
</div>

**Comment by mawzthefinn** [comment]
Please continue the discussion under the linked issue rather than opening additional issues for the same request

**Comment by doppleganger53** [comment]
The link was to a discussion, I assumed an issue needed to be created for it to get on the roadmap - just don't want to see this get lost as it would be a huge selling point for spektrum converts.

**Comment by mawzthefinn** [comment]
The discussion is another issue in this GitHub. One issue with an active discussion generates the most visibility.

note the DSM tools are a 3rd party developed Lua script for EdgeTX today, it’s up to the developer or another 3rd party to port them to ETHOS
