### ISSUE TITLE
frsky x20s left navigation control behiavor

### ISSUE THREAD

**Issue by phil65x** [FrSkyRC/ETHOS-Feedback-Community#4305]
Hi
on my new radio I updated firmware with ethos suite to version : 1.5.11, EU
On left navigation control when you press a button should be activated a system, model, display screen or return function.
On my control when you press system or display you activate always SYSTEM menu'.
if you check hardware and press left (system) or right (display) both shape light up simultaneously as visible in the attachment.
I'm not sure if it worked correctly with the old firmware version but I think so.
Is it possible that it is a firmware problem or is it a hardware problem, any suggestions? Thanks
Philip
![IMG_20240724_160349](https://github.com/user-attachments/assets/d0d100e3-fb7e-4347-9b92-75b9e0dcddb3)

**Comment by bsongis-frsky** [comment]
I think it's a hardware issue. Or you flashed a wrong firmware? Would you check that you get the same result with a previous version?

**Comment by phil65x** [comment]
Hi, i tried other firmware version but the problem remain. I sent the radio to the seller for a check, the result was An hardware issue. Now It works ! Thanks for the support

**Comment by phil65x** [comment]
Problem solved, thanks a lot
