### ISSUE TITLE
Ethos 1.5.12. Some special functions do not accept the GLOBAL parameter. Why?

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4307]
Ethos 1.5.12. Some special functions do not accept the GLOBAL parameter. Why?
![image](https://github.com/user-attachments/assets/435ca964-544a-4f31-9261-7caa5075e634)

![image](https://github.com/user-attachments/assets/3ded173d-09c6-4679-b9df-a4732cb9ab9b)

**Comment by mawzthefinn** [comment]
ANy Special Function that depends on a model specific item cannot be global.

This can be a logic switch as an active condition or an Action that reads out a telemetry value for example

**Comment by philippe-warnotte** [comment]
Ok thank you
