### ISSUE TITLE
Can't select model pictures in 1.5.12 Simulators

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#4308]
Can't assign pictures to models in latest 1.5.12 simulators. Tried in X20S, X20Pro, and X18 and no pictures are shown in Picture menu.
Pictures are all present in C:\Program Files (x86)\FrSky\Ethos\X20S\bitmaps\models folder.
![No pictures](https://github.com/user-attachments/assets/4c6ffba7-1c66-465c-8095-54e9bbae3fd0)

**Comment by strgaltdel** [comment]
there are changes in the path-structure of the sim.

in case you started the sim without path parameters, try following folder :

`//WIN-USERENVIRONMENT/.ethos/X20S/bitmaps/models`

like
c://users/USERNAME/.ethos....
<br/><br/>



The bitmaps path now is part of the user directory, you could even change the path  by starting the sim 

in case you want the same user path structure as before, create a batch file like

`"C:\Program Files (x86)\FrSky\Ethos\X20S\simulator.exe" --user-directory "C:\Program Files (x86)\FrSky\Ethos\X20S"`

<br/><br/>

in addition, there is the possibility to use several sim instances / user directories simultaneously using one installation

`simulator.exe "D:\Programs\Ethos\X20 beta\simulator.exe"  --user-directory "D:\Programs\Ethos\X20 beta\user01 ..."`

Of course, you then must copy all related folders into ..\user01  (-;

**Comment by dwheeld** [comment]
Thanks! I thought the folder may have been moved, but didn't see anything in the 1.5.12 notes about it :( . Would be really helpful if they would include this information when the changes are made.

**Comment by bsongis-frsky** [comment]
The simulator could check if the repository exists, if not it goes to the system directory (as before)
