### ISSUE TITLE
Text overlap in special functions menu

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#431]
X10s isrm 2.1.6 
Ethos 1.0.8

Top menu in special functions
Action  state  active condition  value
The words active condition and value overlap.
I would add a photo but when I click on attach photo icon nothing happens.

Thanks
Scott

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121219774-55768100-c884-11eb-9281-2afa91f5f59d.png)
