### ISSUE TITLE
ETHOS 1.5.11 - FrSky built in altimeters initialize to some random altitude that makes no sense and is annoying

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#4314]
Please pause the telemetry functions for a few seconds at least when the receiver connects to the radio, and give the Altitude and VSpeed sensors initial values of ZERO (not nil). If we wanted to get fancy there could be a user specified value there. 

It would be nice to fire up my radio, turn on my plane and not have my vario screaming at me because the sensors are in a state of flux, and the altitude showing the plane at some random altitude. This throws off my maximum altitude readings and can impact preflight operations as Altitude and VSpeed are the primary sources for my is flying vs is not flying logic.

**Comment by aalain8** [comment]
Perhaps identical to: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4146 .
I don't find this logical, especially since the sensors alone work normally.
An update of the receiver firmware or Ethos? would be great!

**Comment by spoke2570** [comment]
Yes, it appears to be same as that issue. It is also notable that this receiver was originally on an OTX (1st gen Taranis X9D) platform and did not do this on that radio. All of my receivers with built in altimeters are doing this on my ETHOS radio.

**Comment by pmullen503** [comment]
OTX probably sent a telemetry reset automatically. I use a telemetry reset special function. That zeros barometric altimeters.

**Comment by Wolepo** [comment]
I don't quite understand. 
Yes, in OTX you can activate Autooffset or set an offset. This is only possible to a limited extent in Ethos. But you should think a bit and reset the telemetry sensors before starting. This way you always have a start altitude of 0m regardless of the receiver type. I do this at the same time as activating the engine enable switch, for example.

**Comment by spoke2570** [comment]
@Wolepo  I do have those things in place, but it seems that if OTX could bake it in these guys could, too. It throws off my per Rx battery maximum altitude stats when I am flying DLGs, if I turn off to take a beak.
