### ISSUE TITLE
error after last update 

### ISSUE THREAD

**Issue by Hill2** [FrSkyRC/ETHOS-Feedback-Community#4316]
After the last update to 1.5.11 a message marker appears in the top bar. When I press this the message marker it shows at the errors: attempt to add a 'string' with a number.

Anyone familiar with this, and knows the solution?

**Comment by Nicholas-Luoyi** [comment]
Which version did you update from? It should be an error in the scripts

**Comment by bsongis-frsky** [comment]
Remove all the scripts in your /scripts folder
One of those scripts is faulty

**Comment by Richrfl** [comment]
Another reason I found this error was that I was missing one script in the TX, but I did not copy it into the simulator's scripts folder.

**Comment by Hill2** [comment]
Removed all scripts which makes the initial message about this threat disappear. But another came up. Its not allowed to have empty screen widgets. This causes also red triangle alerts in the top bar. This is also solved.
