### ISSUE TITLE
Simulator X18S different from real Tx

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#4317]
Using the following: -

lcd.loadFont("xxxl.fnt")

There is a difference between the simulator and real transmitter. Please see pictures below. I require the large fonts.

The blue border line can give you a hint of the differences.

![Simulator ](https://github.com/user-attachments/assets/9eeb65c6-05bf-48af-b757-e3ca960ca20c)
![Actuall Tx ](https://github.com/user-attachments/assets/f5055877-321a-47bc-846d-025516f1999e)

**Comment by bsongis** [comment]
I am doing a big refactoring on fonts these days. To allow the whole UTF-8 set to be used (or only parts of it to save RAM)
