### ISSUE TITLE
Connections télémètrie 

### ISSUE THREAD

**Issue by Vincent70700** [FrSkyRC/ETHOS-Feedback-Community#4319]
Bonjour, 
Nous sommes plusieurs dans le mêmes cas de figures
Le montage : 
Un rx TD R18. 
un rx TD MX 
Un capteur télémètrie ADV fas 150 et 300 pour l'ampérage.

Les radios sont : 
X20s 
X20 pro 
Le problème : il faut parfois allumer et éteindre l'avion 5 fois de suite pour que la télémétrie ce connecte et apparaisse a l'écran.
C'est dangereux parceque mon alarme de fin de vol sonne avec les mha consommé.
Si quelqu'un a une idée 
Merci

**Comment by mawzthefinn** [comment]
What firmware on the TD ISRM's and receiver(s)?

**Comment by Vincent70700** [comment]
bonjour sur le module TD ISRM hw:1.4.0 FW 2.2.6 EU LBT
TDMX : 1.0.12
TD R18 : 1.0.12

**Comment by mawzthefinn** [comment]
OK, how are you wired in for the sensors? if they are only connected to one receiver, then the other receiver needs to have telemetry disabled.

The active telemetry sender is picked on start up, so if sensors are not connected in a y-cable to both receivers, any time the receiver the sensors are not connected to is picked as the telemetry sender, the sensors will not show up.

**Comment by Vincent70700** [comment]
Ho super 👍🏼 👍🏼 👍🏼 👍🏼 👍🏼 merci beaucoup
Je n'ai pas encore essayé mais oui les 2 rx ont la télémètrie activité.
Je suis sur que c'est ça mon problème.
Énorme merci je vais partager la solution avec tous ceux qui ont le problème.
Encore merci

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
