### ISSUE TITLE
Mix  you cannot edit the value slow 

### ISSUE THREAD

**Issue by konvice56** [FrSkyRC/ETHOS-Feedback-Community#432]
Function type
Addition -> OK
Multiply -> the slow parameter cannot be modified
Replace ->the slow parameter cannot be modified

![mix Slow](https://user-images.githubusercontent.com/84669311/121214823-c6676a00-c87f-11eb-8c97-032b276a89e6.jpg)

**Comment by konvice56** [comment]
Function type 
  Addition -> OK
  Multiply  -> the slow parameter cannot be modified
  Replace  ->the slow parameter cannot be modified

![mix Slow](https://user-images.githubusercontent.com/84669311/121213771-d3378e00-c87e-11eb-82ad-94fdf0a83313.jpg)

**Comment by mawzthefinn** [comment]
This appears to have been corrected. I just tested on 1.4.2 and slow is always editable on a Free Mix.

**Comment by mawzthefinn** [comment]
Closing as resolved
