### ISSUE TITLE
Archer Plus SR10+

### ISSUE THREAD

**Issue by Bobbysonic** [FrSkyRC/ETHOS-Feedback-Community#4320]
I found a bug in the latest update V1.0.10 firmware for the SR10 Plus receiver. After testing my setup with both a Tandem X20S and my new Tandem X20RS to verify, I had the same results with both radios using the same SR10 Plus receiver. Channel 6 on the receive had no output signal.  Channel 6 works correctly on both radio mapping and output mixing, however, after the update was downloaded to the receiver on V1.0.10 channel 6 on both radios wasn't receiving an output signal on channel 6.  I then flashed back to V1.0.09 firmware and channel 6 was restored to its original function (Gear), and everything worked.

Thank you, Bobby

**Comment by mawzthefinn** [comment]
Bad self-check, flashing the older firmware would reset the self-check data.

Self-check learns channel endpoints, which are enforced by the receiver and persist through binds. If a channel is not cycled during the self-check it will learn +/- 0 as the endpoints

**Comment by Bobbysonic** [comment]
Thank you, MAWZ, it is working now!  Appreciate your help, amazing how FrSky works, best radio on the market!

Bobby

**Comment by mawzthefinn** [comment]
Glad it's sorted
