### ISSUE TITLE
[Lua] Potential issue with widget configure() (empty line)

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#4321]
Not sure if it was there before 1.5.11 (likely not):

configure handler code (note widget title is set for false):

local function configure(widget)
    local line, panel, field
    panel = form.addExpansionPanel("Panel 1")
    line = form.addLine('Line 1', panel)
    field = form.addNumberField(line, nil, 0,1000000, function() return 10 end, function(newValue)  end)
end

The configure screen looks line (note the empty line):

![image](https://github.com/user-attachments/assets/4bdd790a-dfae-4523-8b08-f5d2869c9c0c)

if I change code to say

local function configure(widget)
    local line, panel, field
    line = form.addLine('New Line',nil)
    panel = form.addExpansionPanel("Panel 1")
    line = form.addLine('Line 1', panel)
    field = form.addNumberField(line, nil, 0,1000000, function() return 10 end, function(newValue)  end)
end

![image](https://github.com/user-attachments/assets/5fcf8fb4-ac4a-4317-b065-a94d500e8255)

**Comment by bsongis-frsky** [comment]
Reproduced in 1.5.16. Only if the widget has no title!
