### ISSUE TITLE
"Reciever still On" when reciever is off

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4323]
X20S
ethos 1.5.11
TDISRM 2.2.6
with tandem Rx - Rx switch off, if turning off the radio after it the radio will read "reciever still on" even if Rx is off.
tested yesterday with TD SR6 1.0.11.

**Comment by mawzthefinn** [comment]
Duplicate of FrSkyRC/RF_Feedback_Group#9 

Please continue conversation there
