### ISSUE TITLE
ETHOS Feature request duration of logical switch

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#4326]
hello all
x20 s switch on the back of the radio; is it possible to define a pressing duration required to validate the order: for example when this switch is used as a logic arming switch then a short press (or a programmed duration) validates the arming while a long press is imperative to validate the disarming. on 1.5.11, I do not see a parameter governing the pressing duration required to switch the state of this logic switch
x20 s switch au dos de la radio; est il possible de définir une durée d'appui nécessaire pour valider l'ordre: par exemple quand ce switch est utilisé en switch logique d'armement alors un appui bref (ou d'une durée programmée) valide l'armement alors qu'i faut impérativement un appui d'une durée longue pour valider le désarmement. sur 1.5.11, je ne vois pas de paramètre régissant la durée d'appui nécessaire pour faire basculer d'état cet interrupteur logique

**Comment by Alex00101** [comment]
I may not fully understand your requirement, but this seems close for how I am using the switch at the bottom on X20Pro AW?  Short press reports remaining flight time and battery is sensor is connected,  long press resets the flight timer. 
All the logic is in Ethos logical switches logic.

**Comment by samsab1** [comment]
![2024-08-02_10h14_04](https://github.com/user-attachments/assets/f04fc771-43bf-494e-b9f3-915af14cb24f)
is it more clear with that?

**Comment by Alex00101** [comment]
Yes, I believe the logic is in Ethos. Check logical switches settings (ie duration to become active etc)

**Comment by samsab1** [comment]
yes you are right, it was already possible
thanks
