### ISSUE TITLE
Vario source lost at Tx power-off

### ISSUE THREAD

**Issue by RobinS49** [FrSkyRC/ETHOS-Feedback-Community#4328]
I’m using a Tandem XE-S with Ethos version 1.5.11. When I power off my Tx the source for the vario (vspeed) is lost and I have to set it up again on power-up for all my models using a vario (free standing or built in). I use multiple Rx types ACCST GR8, Archer and Tandem.
Since posting the issue I have found that this issue only occurs when the Vario special function is set to Global.

**Comment by bsongis-frsky** [comment]
The Vario shouldn't be made global if its source cannot be global (i.e. a telemetry source)
This will be fixed in 1.5.13
