### ISSUE TITLE
Son du chrono pas bien calibré .

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#433]
Bonjour,
Ethos X20 1.0.8
Le son du chronos est mal calibré , les minutes sont des HEURES et les secondes sont des MINUTES ...
La petite voix m'annonce de heures au lieux de minutes et des minutes au lieux de secondes.

Bonne journée.

**Comment by Asimos32** [comment]
Correct, time calibration readout is not correct

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.9 already, release candidate 2 is available since tonight
