### ISSUE TITLE
ETHOS Suite 1.5.9 Download Center, Product list

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4330]
Ethos Suite 1.5.9: Download Center, Product list, Transmitters, Kavan V20 is NOT in the Twin Series list.

**Comment by Nicholas-Luoyi** [comment]
You are right. I shall ask for the Marketing Department

**Comment by Nicholas-Luoyi** [comment]
Kavan V20 has been added
