### ISSUE TITLE
FEATURE REQUEST: set the duration of the button presses on the back 

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#4331]
hello everybody
set the duration of the button presses on the back of the X20S radio to validate the order: on a logic switch created with a switch on the back of the radio in arming safety mode, it is prudent to be able to have a longer press duration to disarm the drone, and on the contrary, a simple quick press to arm the drone. I see parameters that manage the duration, but not the duration of the press if I'm not mistaken

**Comment by samsab1** [comment]
![2024-08-02_10h14_04](https://github.com/user-attachments/assets/0457baf6-6b29-4051-aaf3-b40c25749205)

**Comment by pmullen503** [comment]
I use press and hold both back buttons for 2 seconds for throttle cut/arm. If you use "delay before active" in your SF, you could set that to two seconds.

I recommend using a delay for both throttle cut and arm. With electrics, inadvertently turning on your throttle is as much a thing to avoid as inadvertently turning the throttle off.

**Comment by samsab1** [comment]
hello
i m not sure concerning the way it runs.
"delay before active" is for me the delay after **release** of the buttons: i mean you press very shortly the buttons, and time counter is running until duration is achieved, and then the order is activated. in other terms, you press short or long time, no matter, the duration begins after releasing the button.


 if I'm not mistaken......

**Comment by pmullen503** [comment]
The active condition has to be true for the entire "delay before active" before the LS is true.
Try it.

**Comment by mawzthefinn** [comment]
This functionality is already present in the logical switches. Delay before active works as @pmullen503 describes

**Comment by samsab1** [comment]
mawzthefinn, is there a way to have a wiki for each parameter , what ever is the parameter? Ethos becomes more and more complex....
best regards

**Comment by samsab1** [comment]
can you show me via a screen print how you deal with the parameter?
from my side, with ethos1.5.12 and x20s, i m not able to set a long press to achieve what i wish.
i mean 
delay before ON: 0s----> state change is immediate and it's ok
delay before OFF: 2 seconds--> a short press makes state change 2 second **after** release the button, and that's not what i wish.

i wish to necessarly press the button 2 second in order to make state change of the logical switch; it's not the same att all

**Comment by mawzthefinn** [comment]
> mawzthefinn, is there a way to have a wiki for each parameter , what ever is the parameter? Ethos becomes more and more complex.... best regards

These settings are all covered in the very extensive manual linked in the first page of this Github
