### ISSUE TITLE
Better display of time sources / seconds

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4336]
Could we have sources in [s] displayed with time format?
to see "5:00" or "00:05:00" instead of "300s"?

At the moment it looks like this:
![image](https://github.com/user-attachments/assets/c8369c64-62be-4403-bd5c-21fb46bf3382)

My source / sensor is defined like this, although I think all the matters is the unit of [s]:
![image](https://github.com/user-attachments/assets/d9372432-0af8-4e15-bf24-391af5ece11d)
![image](https://github.com/user-attachments/assets/e80719e8-3c97-4f50-8559-13ef2e1e22f8)
![image](https://github.com/user-attachments/assets/e3416191-dadc-4d60-991f-3eace9d1db57)

But I wonder what to do with other units like [h], [min], [ms].

Or maybe another unit "time" is needed to achieve this?

**Comment by bsongis-frsky** [comment]
Agreed that the unit "Time" would be nice.

**Comment by bsongis-frsky** [comment]
I have made it simple: when the sensor unit is 'SECOND', then the value is displayed like a timer :

![image](https://github.com/user-attachments/assets/dfe025d6-b121-4ef3-a011-2f719fab51d1)

**Comment by bsongis-frsky** [comment]
The display is modified everywhere, including Value / Range inside Model / Calculated sensor :

![image](https://github.com/user-attachments/assets/724a0f46-5ae3-4a1b-9ecd-ae8b427db1bd)

**Comment by azaz44** [comment]
This is so great, thank you 🙏
