### ISSUE TITLE
[Request] Separate FrSky Ecosystem to separate GitHub repositories

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#4337]
I think it might be time to separate out the Ethos GitHub into multiple repositories.  

At this point, the list of Assets in each release is getting very long.  The issues list is approaching 400, relating to all sorts of things from Ethos itself to Simulator to Suite to RF issues.  Users get confused trying to find the correct download when Ethos is on 1.5.11 but Ethos Suite is on 1.5.8.  And so on.

It might be wise to separate it out a bit:  
One repository for Ethos
One for Simulator
One for Suite
One for FrSky-Created Lua Scripts
etc as needed.

In addition to making things easier to follow this would also make it possible to make the ReadMe for each thing more useful, as it can be tailored to each related item, rather than just "ethos community feedback".

**Comment by mawzthefinn** [comment]
First one is needed for non-ETHOS issues like RF firmware

**Comment by frskyrc-ben** [comment]
is it possible to migrate out current issues/reassign them to the new repos so users do not have to resubmit them ? For ex. there are already some issues tagged with "RF Issue" label

**Comment by rburrow87** [comment]
Seems like it should be possible for open issues at least: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by strgaltdel** [comment]
in my opinion, it would mean a lot more work to maintain more than 5 or 6 different repos

in addition, sim and luas, for example, are connected to the ethos version

.. opened sim issues are also sometimes ethos issues etc...

What I could imagine is a dedicated suite repo, as there are no direct dependencies to ethos releases.


possibly even only as a pure download repo without issues

**Comment by bsongis-frsky** [comment]
> First one is needed for non-ETHOS issues like RF firmware

Agreed

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/RF_Feedback_Group/issues
