### ISSUE TITLE
Updated translation - Portuguese

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#434]
Please find attached the updated translation to Portuguese (some minor linguistic issues and typos have been corrected).  
[pt_updated08_06.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6618663/pt_updated08_06.txt)

There are one issue that still need to be solved. The 'õ' character is not defined and it is appearing as follows: 
![Capture](https://user-images.githubusercontent.com/25162166/121233881-054eed00-c88b-11eb-967f-f27daa60c7f3.PNG)

**Comment by bsongis-frsky** [comment]
For 1.0.9 I will change this special char by 'o', I cannot add conversions. Please remind me to change before 1.0.10 !

**Comment by bsongis-frsky** [comment]
The new simulator ready for the translations of 1.0.9 :
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release%2F1.0.9-candidate3
