### ISSUE TITLE
Press & Hold Page Acts like Enter Instead of Page Back in Model Select Menu

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#4341]
This only seems to happen in the Model Select menu.  Short press goes to the next page as expected but long press/hold it opens the "Rename folder/Create folder" dialog.

Tested on my TW X-Lite on latest 1.5.12 Pre-Release.  It also happens on my X20 PRO in 1.5.11.  Not sure if this is expected behavior?  Seems odd to have a different press-hold functionality for this button in this particular menu compared to everywhere else.

**Comment by bsongis-frsky** [comment]
In 1.5.14 the 2 menus will be merged into one:

![image](https://github.com/user-attachments/assets/d6ecc23b-b417-4877-8c0d-f2e814f60c2c)

![image](https://github.com/user-attachments/assets/f16706f8-8b39-4284-8e80-e5d49afd8a3e)

**Comment by digitalonkel** [comment]
Updated my X10s ISRM to v1.5.15, but behaviour is still the same: long press opens the context menue
