### ISSUE TITLE
Ethos Suite 1.5.8 Image manager issue.

### ISSUE THREAD

**Issue by BJR981S** [FrSkyRC/ETHOS-Feedback-Community#4342]
Image manager allows for the export to selected directories directly on the radio. If you select the directory /Model it does not copy there it copies to /GPS

**Comment by Nicholas-Luoyi** [comment]
Which output selection did you choose?

**Comment by BJR981S** [comment]
Model.

As advised in the issue description.

I was converting model images.


Cheers.

Sent from my iPhone

On 6 Aug 2024, at 3:42 PM, FrSky-Luo ***@***.***> wrote:

﻿

Which output selection did you choose?

**Comment by Nicholas-Luoyi** [comment]
Ah sorry. You could try Suite 1.5.9 now

**Comment by BJR981S** [comment]
Thanks, 1.5.9 Works a treat. Issue can be closed.
