### ISSUE TITLE
Lua: OPTION_CHANNEL_OUTPUT

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#4344]
With the improved syntax of source:value() and OPTION_CHANNEL_OUTPUT introduced earlier, should

source = system.getSource("Ailerons")
source:value()
source:value({options=OPTION_CHANNEL_OUTPUT})

produce different results if Ailerons is reversed?

Currently getting the same value. For the record, source:value({options=OPTION_CELL_COUNT}) works when the source is LiPo sensor

**Comment by bsongis-frsky** [comment]
Would you please check 1.5.13 pre-release? It should be fixed when the binaries are available

**Comment by Alex00101** [comment]
> Would you please check 1.5.13 pre-release? It should be fixed when the binaries are available

@bsongis-frsky - thanks a lot I have tested using latest X20Pro 1.5.13 binary. It is mostly fixed, before I write down what "mostly" means, the way I test it is I've set up reversed channel, assuming that if mix value is positive than channel value should be negative and vice versa.

So after testing:
source:value() and source:value({options=OPTION_CHANNEL_OUTPUT}) return expected opposite results ie -1024 and 1024
source:stringValue() and source:stringValue({options=OPTION_CHANNEL_OUTPUT}) return expected opposite results ie -100% and 100%

source:rawValue() and source:rawValue({options=OPTION_CHANNEL_OUTPUT}) return same results ie -1024 and -1024
