### ISSUE TITLE
onfocus,offfocus events for lua

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4345]
Please can we get some extra params for form field elements.

Current is as follows
local myField = form.addNumberField(line, nil, minValue, maxValue, function() return value end, function(newValue) value = newValue end)

Extend as follows

local myField = form.addNumberField(line, nil, minValue, maxValue, function() return value end, function(newValue) value = newValue end,function() return value end,function() return value end)

Essentially to do this:

line	(FormLine): the line where the field should be added
rect	(Rect): the coordinates
min	(integer): the min value
max	(integer): the max value
getValue	(function): the function which will return the current value
setValue	(function): the function which will be called on value change
onFocus (function): the function called when the field is selected (runs once)
offFocus(function): the function called when focus is removed from the field (runs once)

**Comment by bsongis-frsky** [comment]
Here will be the new syntax for this:
`field:onFocus(function(state) print("state=" .. state) end)`
Will be available tomorrow
