### ISSUE TITLE
lua - get field co-ordinates

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4346]
Please can we get a feature that returns a fields current x/y/w/h elements.

e.g.

local myField = form.addNumberField(line, nil, minValue, maxValue, function() return value end, function(newValue) value = newValue end)

x,y,w,h = myfield:ordinates()

This returns the current co-ordinates on screen.

Doing this will enable the forms to have some funky stuff where you detect the touch input on a part of the form.

**Comment by bsongis-frsky** [comment]
`rect` function added to all form fields
available in the next nightlies
