### ISSUE TITLE
I've got an apple computer and I cannot copy anything from my old transmitter to my new one suggestions

### ISSUE THREAD

**Issue by titchmarsh** [FrSkyRC/ETHOS-Feedback-Community#4348]

**Comment by mawzthefinn** [comment]
Copy the contents of the SD card or NAND Storage (except radio.bin) to the other radio.

The simplest way is to use ETHOS Suite to backup one radio, then restore the backup to the other radio

**Comment by titchmarsh** [comment]
Thank you very much for your help
Sent from my iPhone

On 6 Aug 2024, at 18:56, mawzthefinn ***@***.***> wrote:

﻿

Copy the contents of the SD card or NAND Storage (except radio.bin) to the other radio.

The simplest way is to use ETHOS Suite to backup one radio, then restore the backup to the other radio
