### ISSUE TITLE
Ethos Suite/Download Centre  - A small improvement suggestion

### ISSUE THREAD

**Issue by CodeWorksCZ** [FrSkyRC/ETHOS-Feedback-Community#4349]
Hello, 
Ethos Suite (1.5.9.) Download Centre 
it would be great if the list of **Product Assets** ( great feature BTW!) in **Ethos Suite Download Center** would be sorted from the latest to the oldest.

For instance TR18  shows this and the latest is  somewhere in the middle. 

Not an issue but better user experience if the latest firmware would be sort of highlighted with suffix - **LATEST** and on top of the list.
 And maybe a **link to URL** with description of changes
![image](https://github.com/user-attachments/assets/4506c20b-037e-4cbd-94fe-0bb25a3bf1dc)

**Comment by Nicholas-Luoyi** [comment]
Your suggestions are great. I'll try to implement them

**Comment by Nicholas-Luoyi** [comment]
I shall move it to the next version
