### ISSUE TITLE
Volt adjust Neuron ESC 60A

### ISSUE THREAD

**Issue by michifpv** [FrSkyRC/ETHOS-Feedback-Community#435]
Can i edit the volts of the Neuron 60A ESC? My lipo has 16.6V. But in the telemetry I see 17.4V. 

Telemetry reset works now. Thanks for that

**Comment by Hobby4life** [comment]
I would really like to see a Ratio/multiplier setting too.

**Comment by bsongis-frsky** [comment]
Yes, this is on the roadmap, in next release

**Comment by bsongis-frsky** [comment]
Duplicate of #290

**Comment by michifpv** [comment]
Currently with 1.0.10 RC3, I cannot set the volt offset with the Neuron 60A ESC. If I change the percentage, the value stays the same.

**Comment by bsongis-frsky** [comment]
Did you try to remove it from the list and rediscover?

**Comment by michifpv** [comment]
Yes. I deleted all sensors and rediscover. But it didn't work in the previous version either.

What else I noticed:

If i delete the sensors and search again, the logical switches that are created are unusable if they are related to a telemetry sensor. Only when you edit the logic switch and reassign the telemetry sensor does it work again. Will it stay that way?

**Comment by bsongis-frsky** [comment]
When you delete one sensor, all references to this sensor are removed, it is normal!
