### ISSUE TITLE
delta absolute logical switch infinite loop

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#4352]
hi,

During a test of a logical switch, delta absolute >X ,  i 've created an infinite loop when i change the X value to -100 and i asked a confirmation before activation. Hoppefully i did that in the simulator. i've to stop the simulator and erase the model in his directory on my pc. I guess this problem is also present on ethos radio.

Thanks

**Comment by ronron84** [comment]
hi,
most generally, i don't  see the inerest to  compared a negative value with an absolute value (I delta I or IAI  logical switch).

Thanks

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/89eb76da-1079-464f-b8df-d2414d642964)

**Comment by ronron84** [comment]
thanks !
