### ISSUE TITLE
Any way to speed up "getSource"

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4355]
Hello.
I have many telemetry items that change very rapidly.
Once I get more than 10 of them via getSource the whole radio starts slowing down.
I'm getting getSource about 5 times per second.
If I slow it down, the radio starts being more responsive.

I'm getting the sources by name currently. I don't know if getting them by appID would make it any faster.

X20Pro
Thanks

**Comment by strgaltdel** [comment]
hmm
i don't fully understand your issue.

lets say you want to read 20 different  sources in one script, you would have to declare the sources only once.
in case you know them by start, you could declare all of your sources by  calling getsource in the create handler.
(i like to put them in an array)

like

local src ={}
src.rssi = system.getSource(....)
src.vfr = ....
........
return {src=src}


then, in wakeup, only read the values:

local rssiValue = widget.src.rssi:value()

i'm running widgets which handles app.20 (mainly telemetry) sources and more
and yes, as soon as the receiver is switched on and transmits telemetry, i can see a "performance penalty",
but not so dramatically as mentioned
(i guess gps was a little bit critical)

maybe its a good idea to attach your coding

**Comment by noamkrief** [comment]
@strgaltdel THANK YOU!
I was doing the whole system.getSource("name"):value() inside the loop of wakeup!
That made things super heavy!
Now I'm doing system.getSource("name") outside of the automatic loops, and when I need the value, I just call it with :value()

That seems WAY WAY more efficient :)
