### ISSUE TITLE
X18 FCC ver 1.5.12 is not working

### ISSUE THREAD

**Issue by grosadilla** [FrSkyRC/ETHOS-Feedback-Community#4358]
I upgraded from 1.5.11 to 1.5.12 FCC X18, and the radio does not boot. The power button blinks in blue

**Comment by Nicholas-Luoyi** [comment]
Can you power on into bootloader mode?

**Comment by grosadilla** [comment]
Yes, I downgraded to 1.5.11 and it is working fine.
I did the process using the ethos suite and manually copying the firmware
file in the root directory

**Comment by mawzthefinn** [comment]
Just tested updating my X18 FCC with no issues. Also updated from 1.5.11 to 1.5.12 using ETHOS SUite 1.5.9

**Comment by bsongis-frsky** [comment]
Need more info about this issue, anyone else can reproduce it? X18 vs X18S?

**Comment by grosadilla** [comment]
What kind of information do you need?

**Comment by grosadilla** [comment]
I am running 1.5.11 right now. But i couldn't make it work with the 1.5.12
FCC

**Comment by bsongis-frsky** [comment]
Your X18 has no gyro, right?

**Comment by mawzthefinn** [comment]
> Your X18 has no gyro, right?

Mine has a gyro

**Comment by pmullen503** [comment]
I upgraded to 1.5.12 (and retrograded back to 1.5.11) an X18 using Ethos Suite a couple times yesterday and it worked OK. 

(My X18 has a gyro.)

**Comment by bsongis-frsky** [comment]
@grosadilla do you have a gyro on your X18?

**Comment by bsongis-frsky** [comment]
There is indeed a problem on radios which don't have a gyro, in case the wrong firmware is flashed (X18S instead of X18 in this issue): it will always raise an I2C error on boot and errors are not initialized at that time!

**Comment by grosadilla** [comment]
I did a format using the suite, and in the first start, after calibration,
it asked to put the radio in 4 different positions l, then you assume it
has l.

**Comment by bsongis-frsky** [comment]
Would you please double check with a prior version? 1.5.11 or so ...
If you have a X18S firmware on a X18 radio, then I understand the issue.

**Comment by grosadilla** [comment]
I am running 1.5.11 now. Cannot upgrade to the latest version.

I don't think the ethos suite can choose the wrong version of the radio

**Comment by zero7six** [comment]
Same problem here, base X18 without gyro, after updating to 1.5.12 it will not turn on, just a flashing blue power button. Downgraded back to 1.5.11 and it works again.

**Comment by AdrielSch** [comment]
> Need more info about this issue, anyone else can reproduce it? X18 vs X18S?

I had the same issue with my x18 yesterday. After updating to 1.5.12 the radio didn't boot. I downgrade to 1.5.10 and now it works fine. I'm using ethos suite 1.5.9.

**Comment by Richrfl** [comment]
I have an additional issue with 1.5.12.
I have one of the first X18 which includes a gyro. I downloaded 1.5.12 X18-FCC and to my dismay, I "lost" several models. To make it clear, in the Select model screen there are models missing. However, in the folder models, those models are there. Now, here is the "coincidence" that makes me think there are change in the process to bring the models to the screen. All missing models are a clone from the original models with some changes, and a minimal difference in the name. For example the original, which shows in the screen is named PC-21 JIM, and the clone not showing is named PC-21 V1.1. Another one, named T-28 RICK is in the screen but its clone T-28 Wayne is in the folder, but not in the screen.
