### ISSUE TITLE
ethos SUITE 1.5.9 not Detecting X20 pro 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#4359]
ethos SUITE 1.5.9 not Detecting X20 pro 
in bootloader or ETHOS mode

![Untitled](https://github.com/user-attachments/assets/ce51253e-3500-4d89-95fa-6b1f61ca0536)

**Comment by Nicholas-Luoyi** [comment]
Even after restarting Suite or running it in administrator mode, it still doesn't work?

**Comment by yak-54** [comment]
yep that is running it as admin

**Comment by Nicholas-Luoyi** [comment]
Please put the attached file into the path "Ethos Suite/resources/". And then open Suite. Connect your radio until the file explorer shows the disks. (Reproduce the phenomenon). There should be something logged which named in file main-XXXXXXX.log.

[settings.json](https://github.com/user-attachments/files/16558931/settings.json)

**Comment by yak-54** [comment]
all done here is the log

[main-20240809.zip](https://github.com/user-attachments/files/16559695/main-20240809.zip)


![1](https://github.com/user-attachments/assets/efd9f326-c04c-440c-be2b-f514d915dc18)

**Comment by Wolepo** [comment]
![Ashampoo_Snap_Freitag, 9  August 2024_14h27m5s_001_Ethos Suite 1 5 9](https://github.com/user-attachments/assets/6ac52afe-de24-4499-8709-ebf7ee2caa32)

**Comment by Wolepo** [comment]
I just wanted to make a backup before 1.5.12. Unfortunately the explorer does not work to select a folder. So I used the specified path and then moved it to the desired folder. The backup worked completely. 
Win 11Pro/64
![Ashampoo_Snap_Freitag, 9  August 2024_14h27m5s_001_Ethos Suite 1 5 9](https://github.com/user-attachments/assets/d5807128-9384-4f66-b562-78be88433f00)

**Comment by Nicholas-Luoyi** [comment]
> I just wanted to make a backup before 1.5.12. Unfortunately the explorer does not work to select a folder. So I used the specified path and then moved it to the desired folder. The backup worked completely. Win 11Pro/64 ![Ashampoo_Snap_Freitag, 9 August 2024_14h27m5s_001_Ethos Suite 1 5 9](https://private-user-images.githubusercontent.com/90325526/356592976-d5807128-9384-4f66-b562-78be88433f00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjE2MjEsIm5iZiI6MTcyMzQyMTMyMSwicGF0aCI6Ii85MDMyNTUyNi8zNTY1OTI5NzYtZDU4MDcxMjgtOTM4NC00ZjY2LWI1NjItNzhiZTg4NDMzZjAwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAwMDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMGU5NGU3MDEyODg1NTliNWE1NzhkNDhjZjg2OTZjZGJiYmZhMzA5ZmU2MGU0YjZiZmIyMDJiZjNjYjFkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzWA1hjmlwamVHWiHxqEg8vcTya0lOU-5xMtRKF6gpk)

It seems not related to this topic. And I don't understand it very well. Would you please open another topic if you think it is truly a bug?
