### ISSUE TITLE
External module update rate

### ISSUE THREAD

**Issue by MikeBland** [FrSkyRC/ETHOS-Feedback-Community#436]
Select external module as XJT lite - update period is 4mS.
Change to PPM - update period is 22.5 (8ch) or 45 mS (16ch).
Change back to XJT lite, update period is now 100mS.
Only a radio power cycle will return the update period to 4mS, turning the module off and on does not.

**Comment by bsongis-frsky** [comment]
What a surprise, an issue by Mike!

**Comment by bsongis-frsky** [comment]
Did you check with the logic analyser? It should be a TX Settings frame which is sent every 100mS.
Then it should be acked and the channels should be sent at a rate of 4mS

**Comment by bsongis-frsky** [comment]
OK then it works as designed. You will see a TX Settings frame coming every 2 seconds.
Back soon on the PlaySequence function, I will open an issue to be sure it will cover all the ideas you gave some time ago

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/441
:)

**Comment by MikeBland** [comment]
OK, I raised the issue as it is a bit inconsistent, at power up it operates at 4mS, but switching from PPM to XJT Lite it operates at 100mS, when no module is present.

**Comment by bsongis-frsky** [comment]
true
