### ISSUE TITLE
upgrade update suite ethos 1.5.8 to 1.5.9 and latest radio firmware incomprehensible!

### ISSUE THREAD

**Issue by FlipAirboost** [FrSkyRC/ETHOS-Feedback-Community#4360]
Hi all,

1. The ethos suite offers me the update from version 1.5.8 to 1.5.9 and it proceeds normally. 
2. Radio on, I plug in the usb and choose ethos suite in the radio menu.
3. Click on "radio ethos" in suite ethos = radio not detected
4. Eject the drives via the windows menu, I unplug the usb, stop and restart the ethos suite.
5. Radio on, I plug in the usb and choose ethos suite in the menu.
6. Now the radio is detected. Everything is green for updates, except radio firmware.
7. I click on write updated components, it starts then I have the message impossible to switch to bootloader mode.
8. Stop and restart the PC
9. Start ethos suite
10. Radio on, I plug in the usb and choose ethos suite in the menu
11. Click on "radio ethos" and radio is detected but now the menus are all gray!? 
![ethos suite 1 5 9 ethos 1 5 12](https://github.com/user-attachments/assets/e5a5e1bc-c179-4292-ab4f-c47aaa91f52b)
12. click on upgrade all the components and my radio is updated.
13.   Eject the drives via the suite ethos menu.

The sequence does not seem at all normal even if the result is there !!?

**Comment by Nicholas-Luoyi** [comment]
This seems to be the network problem of the PC

**Comment by aalain8** [comment]
Hello,
From my side: with suite 1.5.9 my fixed pc under Windows 11 is having problems as you describe. 

I now have USB ports on the motherboard that don't recognize Ethos-suite, while the port on the front of the pc works!

When the message "impossible to switch to bootloader mode" appears, I wait a bit and the update finishes normally.

On my Windows 11 laptop, everything works normally from suite 1.5.6 onwards.

Translated with DeepL.com (free version)

**Comment by Wolepo** [comment]
Why isn't the transmitter put into bootloader mode and then connected to the PC? I have never had any problems with this. The USB cable even runs via a passive USB hub.
Win11 Hom/64

**Comment by aalain8** [comment]
Wrong explanation on my part.
the transmitter is switched on in bootloader mode, then connected to the PC.

I had downloaded the test version.
I've just downloaded the latest version and everything is working normally.

Thanks to the developers.

**Comment by yak-54** [comment]
Hmm Ethos Suite 1.5.8 stops when update firmware X20 pro freezes #4295

**Comment by FlipAirboost** [comment]
> Hmm Ethos Suite 1.5.8 stops when update firmware X20 pro freezes #4295

yes , see step 7 .

**Comment by FlipAirboost** [comment]
> This seems to be the network problem of the PC

Maybe, but for example, my slicer program upgrades and the firmware of the different printer brands update without any problems and the same for edgetx.
Indeed, with the Ethos suite, updates can be unpredictable; sometimes they proceed smoothly, and other times they do not.

**Comment by Nicholas-Luoyi** [comment]
I think this topic mainly involves two issues:
- Switching mode failed => I will try to fix
- Missing remote version for the version tag => I assume it is a network error. But I will check as well

**Comment by FlipAirboost** [comment]
Regardless of whether I plug the radio in one way or another, it only goes into bootloader mode when I ask to write all the components.

![1 5 13 step 1](https://github.com/user-attachments/assets/59b6e185-4773-42b3-bdea-a5ea99ebf8d9)

![1 5 13 step 2 ](https://github.com/user-attachments/assets/29975a57-9db3-4673-95fc-e3a1d0b3abc1)

![1 5 13 step 3](https://github.com/user-attachments/assets/08694c8c-c64b-43cd-bdc3-6891b17f1ec4)

![1 5 13 step 4](https://github.com/user-attachments/assets/8ac26841-ec43-4d85-b29c-e1d3ae210547)

![1 5 13 step 5](https://github.com/user-attachments/assets/c30115ef-43d2-4aa0-8800-4b4c3fcef08d)

![1 5 13 step 6](https://github.com/user-attachments/assets/fd8d058f-ac1c-4566-ba46-741f4f232df4)
