### ISSUE TITLE
TD SR18 Gyro Calibration Failure

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#4361]
Hello, Since I updated the rx. firmware to V 1.0.13. I am not able to calibrate the receiver. Here
![20240809_085006s](https://github.com/user-attachments/assets/73bd2689-caa0-43b4-af7f-d259b4aab897)
 is the error message

**Comment by mawzthefinn** [comment]
DId you install the latest Lua scripts?

That's a very minor error in the previous version of the calibration Lua. It does not affect calibration at all, just fails to load a single image at the end of the process.

**Comment by 4qr1hu9n7** [comment]
Yes. Latest scripts installed. Calibration continues to fail.

**Comment by 4qr1hu9n7** [comment]
Found the problem. Latest firmware (V 1.0.13) will not "enable gyro stabilization.

**Comment by mawzthefinn** [comment]
> Found the problem. Latest firmware (V 1.0.13) will not "enable gyro stabilization.

That sounds like you do not have the v3.0.0 Lua scripts in use, the older scripts cannot configure the new (1.0.13) stabilization system, much like Device Config->SxR can't configure even the older firmware on teh TD SR18.

**Comment by Wolepo** [comment]
Click here for the TD SR18:
![Zum LUA TDSR18](https://github.com/user-attachments/assets/3c93aab1-2c17-4abf-bd17-51f274cecbe5)

**Comment by 4qr1hu9n7** [comment]
Okay. This time I really found the problem. I did not remove the old scripts before adding version 3. All is well.
