### ISSUE TITLE
Problème 1.5.12, tandem Xe, ne reconnaît plus les modèles enregistrés 

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#4364]
Bonjour,
Suite à la mise à jour vers 1.5.12 de ma tandem xe avec la suite 1.5.9.
La majeure partie de mes modèles a disparu....
Il n'en reste qu'un visible et je ne peut pas l'ouvrir: donnees invalides....

Les modèles sont toujours dans les fichiers de la radio mais invisibles sur l'interface, à part un seul.
![IMG_20240810_151619](https://github.com/user-attachments/assets/aede8bc7-61a0-431a-986e-8fb08b0875bc)

Edit: le seul modèle qui restait visible à lui aussi disparu de l'interface.....

**Comment by Tonio62** [comment]
![IMG_20240810_155313](https://github.com/user-attachments/assets/1c5218b8-5908-4fb5-b12a-b35156c7d95b)

**Comment by Tonio62** [comment]
Edit: 
J'arrive à replacer les modèles non corrompus d'une précédente sauvegarde, mais ils finissent par se corromprent une fois la radio allumée .
Si j'ouvre le fichier .bin d'un modèle corrompu avec le bloc notes, il n'y a plus qu'une ligne de code

**Comment by Tonio62** [comment]
Edit:
Solution trouvée, il faut désactiver "choix du modèle au démarrage" pour que ça fonctionne

**Comment by mawzthefinn** [comment]
Duplicate of #4351 please continue conversation there
