### ISSUE TITLE
plantage mise a jour component video

### ISSUE THREAD

**Issue by olivierpo44** [FrSkyRC/ETHOS-Feedback-Community#4365]
depuis  ethos suite 1.5.9 j'ai lance la mise a jour du composant video v2 de ma radio

![radio 2 0](https://github.com/user-attachments/assets/fcd2e179-6bc5-4e15-b447-48c4d1330d9f)

![Capture d'écran 2024-08-10 163801](https://github.com/user-attachments/assets/d31a50c2-04f9-48cb-87cb-23e3e0bf2f1b)
La mise a jour demarre mais plante et la radio se met en echec lors de la mise a jour.
 
![download center](https://github.com/user-attachments/assets/32ae062b-2e4f-4a13-8cd9-ce847a07a577)

![debut update radio](https://github.com/user-attachments/assets/643cc5c8-77b6-4d67-a50f-ed27b846e595)
![echec operation](https://github.com/user-attachments/assets/378c589e-084b-48f7-97d8-71c88d714d03)
L'ecran de la radio s'eteint, puis redemarre en mode usb

ethos suite indique provisoirement que la version du composant est bonne, mais cela n'est pas confirmé au demarrage suivant

![affichage 2 1 0 a jour](https://github.com/user-attachments/assets/826aacb5-1498-4ad1-a72a-60e9ff9d3eb9)

Cependant , impossible de revenir en arrière !! (un reset usine ne change rien de même que le mode recovery sur le rx hdzero).

les frequences affichées maintenant en mode "fpv " ne sont plus les bonnes et le retour video ne remonte plus l'osd et plante (l'afficheur devient mauve !)

![frequence etrange](https://github.com/user-attachments/assets/d65fceae-1c81-4b57-89a9-5a9ed19565e4)

Est il possible de recuperer l'ancienne version du composant logiciel video ou y a t il un bug sur le nouveau ?

Merci

**Comment by olivierpo44** [comment]
apres essais l'osd remonte de manière aléatoire en appuyant sur "disp"

**Comment by bsongis-frsky** [comment]
X20S-HD avec 1.5.12 a vraiment besoin de cette version 2.1.0 de HD-Zero. Donc à priori votre radio est correctement à jour.

Pas de mauvais retour par rapport à cette version pour le moment !

Par contre je pense que vous avez besoin d'une mise à jour côté émetteur video également ?

**Comment by olivierpo44** [comment]
Bonsoir bertrand.

Je pense que d'un point de vue fonctionnel la mise a jour est bonne (j'ai bien l'image du retour video puis l'osd en appuyant sur mdl). (ssule chose génante l'ecran passe en veille au bout du timer prevu alors qu'il restait actif avec l'ancienne version)
il y a cependant un petit bug.
Si je demarre la radio (x20 "non S " HD ) par le boot loader pour la connecter a éthos , la suite ethos me dit que le composant video n'est pas à jour et provoque l'erreur radio pendant la mise a jour.
Par contre si je connecte la radio allumee avec l'usb et demande ethos suite dans le choix de connexion (joystick, ethos suite, serie) ethos me dit que le composant video est a jour !!
j'ai refait plusieurs fois cette manip et ce comportement est systematique.
je n'ai pas encore fait la mlise a jour du vtx (drone flywoo avec carte vtx) hd zero lite. j'attends le cable pour le faire, mais le retour video fonctionne avec la version native
MErci !

**Comment by olivierpo44** [comment]
Bonjour;
Meme probleme avec la version 1.5.13.
J'ai essayé de faire la mise a jour en copiant le fichier frsk dans files et en lançant la commande "Mettre a jour le periphérique video" . au bout de 10--15 secondes (4% du parcours)  j'ai un message d'erreur ID "request failed"

**Comment by olivierpo44** [comment]
Re,
j'ai reussi a faire la mise a jour du composant video en court circuitant les pins a cotés de l'ahdmi AVANT de mettre la radio sous tension. Ensuite en démarrant la radio en bootloader à l'aveugle (l'ecran n'affiche rien tant que les pins sont courcircuités) j'ai lancé ethos suite et la mise a jour du composant video qui est alléee à son terme sans erreur.
Cependant, j'ai toujours le meme affichage sur ethos suite   : démarrage de la radio en boolader puis connection a ethos suite : le systeme m'indique que le composnat video n'est pas à jour par contre si demarrage de la radio puis connection de l'usb et choix de ethos suite : la suite ethos me dit que le composant est à jour....
Merci pour votre aide

**Comment by bsongis-frsky** [comment]
The bootloader needs to be updated. Ready for 1.5.14
