### ISSUE TITLE
1.5.12 timer haptic not working

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4366]
X20S
1.5.12
i have a few timer conditions such as "countdown" with haptic = on.
the countdown is heard but no haptic feedback at all.

**Comment by bsongis-frsky** [comment]
Like this action?

![image](https://github.com/user-attachments/assets/a961f960-7f92-4052-afda-0373a45de79e)

It should work

**Comment by i3dm** [comment]
Yes, like this
There is no vibration felt.

**Comment by i3dm** [comment]
Has this been reproduced by the team?

**Comment by bsongis-frsky** [comment]
There is haptic, but it is indeed too light

**Comment by i3dm** [comment]
Fixed in next fw?

**Comment by bsongis-frsky** [comment]
Haptic will be a little bit stronger in 1.5.16

**Comment by i3dm** [comment]
what is a little bit stronger?
on mine with 1.5.12 i feel 0 haptic basically.
