### ISSUE TITLE
Missing Screens!

### ISSUE THREAD

**Issue by KevinFairgrieve** [FrSkyRC/ETHOS-Feedback-Community#4367]
I have an X20Pro and am X20.

I have just updated both to 1.5.12 with no issues.

I did however notice that in 1.5.11 and now 1.5.12 that some of my screen layouts are missing on my X20PRO. (See screenshots) X20 shows all the screens. I was hoping that updating would cure this. But no.

So I do not have any screens that show the three centre controls.

I first noticed this a few evenings ago when I went to fly my Night Radian which is one of the few models I have that use a pot and the centre slider.

I have been through all the hardware menus and as far as I can tell both are the same.

![1](https://github.com/user-attachments/assets/86e25f57-5bda-4fdc-bfde-74a084bea1a4)
![2](https://github.com/user-attachments/assets/2fadf235-525c-48a6-a10e-961db8fcadb1)
![3](https://github.com/user-attachments/assets/b4c47c70-7704-4ded-a892-0766e3418000)

**Comment by bsongis-frsky** [comment]
Would you share your Lua script which adds those extra layouts?

**Comment by bsongis-frsky** [comment]
X20-PRO has 2 extra trims. They are displayed in the center of the screens (2 vertical bars). Instead X20S has no extra trims and those bars are used for P1/P2/P3 (with no number value in the bottom)
