### ISSUE TITLE
Telemetry error with MLVSS sensor (1.09 RC2)

### ISSUE THREAD

**Issue by NMO81** [FrSkyRC/ETHOS-Feedback-Community#437]
I tested 1.09 RC2 and on 2 different receivers I noticed that the readout of the MLVSS lipo voltage sensors was not ok, the Cells Total voltage was always 0.0V, the individual cell voltages are working fine. I flashed back to 1.0.7 and it is working again.

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.9 candidate 3
