### ISSUE TITLE
Suite 1.5.9: Explorer for backup does not work

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4370]
I just wanted to make a backup before 1.5.12. Unfortunately the explorer does not work to select the appropriate folder. So I used the specified path and then moved the backup to the desired folder. The backup worked completely.
Win 11Pro/64 
Thanks for the interest
Wolfgang
![Suite 1 5 9](https://github.com/user-attachments/assets/bf8015ff-eb7a-4996-82e4-42ef6596393b)

**Comment by Nicholas-Luoyi** [comment]
Could you clarify if the issue is that the directory selection popup didn't appear, or that after selecting a directory, the chosen directory wasn't saved (or didn't take effect)?

**Comment by Wolepo** [comment]
The pop-up window does not open. However, a backup is saved in the specified path.
Wolfgang

**Comment by Nicholas-Luoyi** [comment]
Could you check if the pop up dosen't work neither in image & audio manager? It should be the same when you select a path as the output

**Comment by Wolepo** [comment]
No, the pop-up window does not work there either

**Comment by Nicholas-Luoyi** [comment]
And if you run it as an administrator?

**Comment by Wolepo** [comment]
I have tried both versions, but there is no change. I also uninstalled and reinstalled the suite. The same result.

**Comment by Nicholas-Luoyi** [comment]
What do you mean by both versions? 1.5.8 and 1.5.9?

**Comment by Wolepo** [comment]
No, open Suite normally, or as administrator.

**Comment by Wolepo** [comment]
A major Windows update was released yesterday. Today the Eplorer in the Suite is working again. I was able to make a backup before 1.5.13 as usual. 
If nothing new is found, the topic can be closed.
Thanks for the effort.
Wolfgang
