### ISSUE TITLE
Kavan V20 1.5.12 Mixer % rate setup

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4377]
1.5.12 transmitter and Simulator: Mixers setup: the 3 points no longer appear in the square below on the right.
![image](https://github.com/user-attachments/assets/19f0731f-0d80-4e83-b9f1-c903f00868c2)

**Comment by Wolepo** [comment]
All points are displayed in the curve editing, only the end points are missing in the preview in the mixer.

**Comment by philippe-warnotte** [comment]
I explained myself badly. It's only a question of display. The menu indication is missing.
![image](https://github.com/user-attachments/assets/b80cd432-95c3-4ccc-9c14-1d1c3f600fc9)

**Comment by bsongis-frsky** [comment]
Are you sure that your bitmaps are updated to the latest release?

**Comment by philippe-warnotte** [comment]
Update 1.5.12 kavan v20 with suite 1.5.9 .
![image](https://github.com/user-attachments/assets/965bb6f8-bafb-4315-b3cc-0cc612abddb5)

**Comment by philippe-warnotte** [comment]
File: "mask_more_icon.png" is missing in V20/bitmaps/system
It works if I copy this file from the X20 simulator to my V20.
THANKS
Note:
In April 2024, this file was already missing for kavan V20.

**Comment by philippe-warnotte** [comment]
Ok on 1.5.13 thank.
