### ISSUE TITLE
Lua-script not working (red triangle)

### ISSUE THREAD

**Issue by mastwa** [FrSkyRC/ETHOS-Feedback-Community#4378]
Hello,
that's my first Issue, sorry if something is not as it should...
I have an FrSky Tandem X18SE and get an red triangle by only starting the Spirit-LUA-Script and then closeing the script  again without changeing anything - That works with ETHOS 1.5.11 without any problems, with 1.5.12 this problem occurs -
Here some hardcopies (photos) from the situation -

The fist picture shows the start up (normal), the second picture shows the red triangle after closing the spirit lua script and the third shows under Info the description of the error -

![03_DSC_0191](https://github.com/user-attachments/assets/4b5d5a12-414a-42ad-83a7-83eba1809dba)
![02_DSC_0192](https://github.com/user-attachments/assets/87667184-649b-424b-8a3e-c1bf0d3b1749)
![01_DSC_0193](https://github.com/user-attachments/assets/8a78ab0c-d083-4e5c-ae5e-d94c8ce7cf15)

**Comment by bsongis-frsky** [comment]
This should be reported to Spirit, as their Lua script is closed source, and not owned by FrSky!
