### ISSUE TITLE
Feature request, multi stick mode

### ISSUE THREAD

**Issue by NMO81** [FrSkyRC/ETHOS-Feedback-Community#438]
I would like to have a possibility to change the stick mode per model, I fly heli on mode 2 and plane on mode 4. Now I have to adjust everything with free mixing to setup a heli if I use my transmitter default at mode 4.

**Comment by NMO81** [comment]
Another way to do it, like I use it in my old Hitec Aurora 9, is to make the inputs of the predefined mixers adjustable. This is maybe easier to implement.

**Comment by mawzthefinn** [comment]
Note you can swap outputs readily, so unless you are using the CCPM mixing in the radio, simply swapping your Aileron and Rudder mix output channels will achieve this for the heli.

**Comment by mawzthefinn** [comment]
#1790 is the same issue, and has been assigned, so I'm closing this off as a duplicate despite this being the earlier report

**Comment by NMO81** [comment]
Thx for following up.
