### ISSUE TITLE
1.5.12 Timer problem

### ISSUE THREAD

**Issue by Aizek-jpg** [FrSkyRC/ETHOS-Feedback-Community#4381]
Hi, There is a problem when i set my timer to 8:45 minutes and i want to set the countdown to start from 7:45 and count every 60s. Instead it counts every time it gets to 7:00 or 6:00 and etc. I want it to count every time it gets to 6:45 or 5:45 and etc. Please fix this problem. My radio is FRSKY X20 PRO AW. Thanks !

**Comment by bsongis-frsky** [comment]
Fixed in next 1.5.14 nightlies
