### ISSUE TITLE
X10S ISRM ETHOS 1.5.13 Emergency Mode!

### ISSUE THREAD

**Issue by ETHOSWarrier** [FrSkyRC/ETHOS-Feedback-Community#4382]
Hi,I have just put ETHOS 1.5.13  on my X10S ISRM and noticed an Issue.

It  boots up and works as normal as far as I can see with a model loading ok.But when i paged through the model folders from Indoor planes to  IC planes to ELE planes for example it goes straight into Emergency Mode!

It will turn off with the power button if held for a few seconds.I repeated the process about 3 times ,then flashed 1.5.12 back on and its fine now.Just thought I will let you know before its a proper release...I only do indoor flying with this radio so its not that critical for me ,but for others it could be.....EW

**Comment by bsongis-frsky** [comment]
Thanks for testing & reporting!

I cannot reproduce the problem, but perhaps you have a corrupted model, would you attach to this issue the ZIP of your models folder?

**Comment by bsongis-frsky** [comment]
I have added a sanity check and generated the firmware again. Would you please check if I succeeded to fix this issue on your radio? Thanks in advance!

**Comment by ETHOSWarrier** [comment]
Sorry Bsongis,I assumed as you had marked it "Bug" and "completed" there was nothing left to test and you had found the issue.The Emergency mode was not when loading a model,it was when browsing /paging through the folders which contain models so I could not know which model to send you anyway.
Yes I will test it tomorrow on 1.5.13...EW

**Comment by ETHOSWarrier** [comment]
Ok, tested it now and all is well.The select model on startup works too without losing the model Bin file and no EM on paging through the folders..thanks,..EW
