### ISSUE TITLE
Throttle cut wrong meassage @start screen extremeky

### ISSUE THREAD

**Issue by ilioSS53** [FrSkyRC/ETHOS-Feedback-Community#4384]

**Comment by ilioSS53** [comment]
Good day,
Just installed 1.5.12
Programmed a new model with Archer plus sr8
Programmed throttle cut on my x20s with switch F down is cut.
Power cycle the tx. The start screen gives the message throttle cut not in safe condition. This is extremely dangerous.

**Comment by ETHOSWarrier** [comment]
check your check list ,it could be that its not set to the correct position and warning you for no reason...EW

**Comment by ilioSS53** [comment]
Correct, checklist must also be set.
Sorry my shortcomming.
