### ISSUE TITLE
Models missing in 1.5.12 

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4386]
I have one of the first X18 which includes a gyro. I downloaded 1.5.12 X18-FCC and to my dismay, I "lost" several models. To make it clear, in the Select model screen there are models missing. However, in the folder models, those models are there. Now, here is the "coincidence" that makes me think there are change in the process to bring the models to the screen. All missing models are a clone from the original models with some changes, and a minimal difference in the name. For example the original, which shows in the screen is named PC-21 JIM, and the clone not showing is named PC-21 V1.1. Another one, named T-28 RICK is in the screen but its clone T-28 Wayne is in the folder, but not in the screen.

**Comment by bsongis-frsky** [comment]
Would you please attach here one of those models? It should be possible to load them on all radios

**Comment by Richrfl** [comment]
Here you have two of them> the two that show are PC-21 JIM and T-28 Rick
[ACTIVE.zip](https://github.com/user-attachments/files/16630772/ACTIVE.zip)
All of them are in a Folder named Active, as I also have other folders Backup and Test, with copies of some of the Active folder models.

**Comment by bsongis-frsky** [comment]
Are you sure? I can see & load those models in the X18 simulator!

![image](https://github.com/user-attachments/assets/1bd63a4a-e069-4413-b03e-65eb941c66fd)

![image](https://github.com/user-attachments/assets/1d6f3854-d9e9-46e1-a1a0-40a1e8855bb1)

![image](https://github.com/user-attachments/assets/8f414dd6-a422-48af-b87e-8712e6dab69d)

_I just miss the scripts / bitmap files, but that's normal_

**Comment by bsongis-frsky** [comment]
Also I am on 1.5.13. But nothing should have changed in this area since 1.5.12

**Comment by Wolepo** [comment]
But the Clons, PC-21 V1.1 and T-28 Wayn are not available.
![Modelle fehlen](https://github.com/user-attachments/assets/517bd0bc-e935-4e94-921b-fa8078e57a50)

**Comment by Richrfl** [comment]
Yes, they show in the sun, but not in the radio.

**Comment by Richrfl** [comment]
I just found another thing in the radio folder that can explain the problem. T-28 Wayne (cloned file) is 0B and PC-21 V1.1 is 320B which are not consistent with the size of the other bin files.

**Comment by bsongis-frsky** [comment]
Right. Only the valid models are shown. A 0-byte file won't show and that's normal!

**Comment by bsongis-frsky** [comment]
> But the Clons, PC-21 V1.1 and T-28 Wayn are not available. ![Modelle fehlen](https://private-user-images.githubusercontent.com/90325526/358537620-517bd0bc-e935-4e94-921b-fa8078e57a50.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDgwNTgsIm5iZiI6MTcyMzgwNzc1OCwicGF0aCI6Ii85MDMyNTUyNi8zNTg1Mzc2MjAtNTE3YmQwYmMtZTkzNS00ZTk0LTkyMWItZmE4MDc4ZTU3YTUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDExMjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOWM0ZjQxYzU3YzZkNjVhNWVhNzdjNDFlNzdmMDM1Yjc4YTMwYjhkZDVlZWJmZjE3NWY4MTc4MDg4NzkzMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ohH-0ewFDOfpD9Do1_olCM8j8FpB73FCmhRzegMJcTo)

I see. How those models have been cloned? From the radio?

**Comment by Richrfl** [comment]
Yes, with the clone function. Anyways, as this was done before the update, ( the cloning) I guess that for some reason the files were corrupted on the update process. I'll clone them again and modify as needed.

**Comment by Richrfl** [comment]
Cannot open the link Modelle fehlen. Which issue # is it?

**Comment by Richrfl** [comment]
In view of the impossibility of confirming that specific model files have been corrupted in the update process, I will proceed to close this issue.
