### ISSUE TITLE
Manque entrée analogique sur certain mixages pré définis? 

### ISSUE THREAD

**Issue by simonPaul25** [FrSkyRC/ETHOS-Feedback-Community#4390]
Bonjour,
Pourquoi nous ne pouvons pas avoir la possibilité d'avoir les entrées analogiques sur un certain nombre de mixages pré-défiinis comme ; volets, Aérofrein, papillon par exemple. C'est dommage les mixages sont top mais tout ou rien. On est donc obliger de tout recréer en mixages libres si l'on veut du progressif.

**Comment by bsongis-frsky** [comment]
Les volets ont bien une entrée configurable :
![image](https://github.com/user-attachments/assets/a89f9ebb-c4ac-412f-bccf-995899312f7f)

**Comment by simonPaul25** [comment]
Autant pour moi zapper. Par contre pas les AF.

**Comment by simonPaul25** [comment]
Pour les AF et papillon 
![AF -03](https://github.com/user-attachments/assets/c918eda9-85fd-426e-9004-00f29364e2c2)
![AF-02](https://github.com/user-attachments/assets/e4ca040c-b8b3-4c57-9fc6-7e356c020805)
![AF-01](https://github.com/user-attachments/assets/ae1e57da-648c-4762-b132-ee676922f585)
