### ISSUE TITLE
Sensor Conflict warning on DIY Sensor and 1.5.12

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#4391]
Hi all,
This may be a bit odd but it is what it is, I created a DIY sensor (PHY: 0x12 APPid: 5900) using an Arduino Nano that intercepts the SBUS messages, decodes them, and puts the throttle back in S.Port so as to be able to get the throttle state in the Bluetooth Telemetry stream and am seeing a really odd behavior.  In building the sensor if I just have it periodically send random data (e.g. 0x1234) everything is fine, no SensorConflict Warning but connect the device to the SBUS pin and the S.Port pin I start to get the "Sensor Conflict" Warning ~every 30 seconds.    The interesting thing is that it's sending my data perfectly fine and have the throttle in the bluetooth but like everyone else who has opened a ticket about this it's annoying as all hell.  Any insights?  What are the hazards of having a sensor conflict?  Is this the type of thing that will crash the model or just loose sensor data?  Could we get an option to disable this check making Ethos like O/ETX?

Dave

**Comment by fdm225** [comment]
Update to this issue for the Ethos devs..  First this issue can be closed but I am leaving it open so that you can look at it for the other issues having to do with the Sensor Conflict warning.  In the custom sensor code I had print statements so as to see various values that were read from the SBUS and that were being put out the S.Port, upon removing them the Sensor Conflict error went away.   My theory behind this and as to why I was seeing that particular issue is that the ATmega328 was spending too much time writing to the serial port and therefore loosing sync with the serial communication the S.Port of the receiver (probably not the SBUS as I am using a hardware serial port which is interrupt driven).  Not being 100% familiar with the S.Port protocol or how tight the timing is I am guessing here that an equivalent of buffering was happening in the code and the S.Port messages are being sent in too rapid of a pace causing the reciever to think that there were multiple sensors with the same hardware and app ID.  As I said, I have not done a deep dive on the S.Port protocol to understand what effect that loosing serial sync would have and may be 100% wrong in this but if my theory holds true some of the other issues that people may be seeing is due to similar scenarios with the 3rd party sensors (don't know enough about the Frsky sensors to know if they are using hardware serial).  I can tell you though that removing the print statements has made the system 100% stable leaving it running for ~5 minutes now without a single conflict message.  

Devs, after read this please close this issue and if I can provide any additional information please let me know.  

dave

**Comment by fdm225** [comment]
to be complete I am uploading my code here in the case it is of any value to the devs for debugging other Sensor Conflict issues.

`
#include <sbus.h>
#include <SPort.h>                        //Include the SPort library
#include <SoftwareSerial.h>

SoftwareSerial mySerial(11, 12);

/* SBUS object, reading SBUS */
bfs::SbusRx sbus_rx(&Serial);
/* SBUS object, writing SBUS */
//bfs::SbusTx sbus_tx(&Serial);
/* SBUS data */
bfs::SbusData data;


SPortHub hub(0x12, 4);                    //Hardware ID 0x12, Software serial pin 3
CustomSPortSensor sensor(getSensorData);  //Sensor with a callback function to get the data
int thrVal = 0;

void setup() {
  //Serial.println("hello world");
  /* Serial to display data */
  //mySerial.begin(115200);
  //Serial.begin(9600);
  //while (!Serial) {}
  /* Begin the SBUS communication */
  sbus_rx.Begin();
  //sbus_tx.Begin();


  hub.registerSensor(sensor);             //Add sensor to the hub
  hub.begin();                            //Start listening

  // set the data rate for the SoftwareSerial port
  //mySerial.begin(38400);
  //mySerial.println("Hello, world?");

}

void loop () {
  //Serial.print("hello world");
  //mySerial.print("Hello world\r\n");
  if (sbus_rx.Read()) {
    /* Grab the received data */
    data = sbus_rx.data();
    // if (data.ch[2] != thrVal) {
    //   mySerial.print(data.ch[2]);
    //   mySerial.print("\r\n");
    //   thrVal = data.ch[2];
    // }
    /* Display the received data */


    // for (int8_t i = 0; i < data.NUM_CH; i++) {
    //   mySerial.print(data.ch[i]);
    //   mySerial.print("\t");
    // }
    /* Display lost frames and failsafe data */
    // mySerial.print(data.lost_frame);
    // mySerial.print("\t");
    // mySerial.println(data.failsafe);
    /* Set the SBUS TX data to the received data */
    //sbus_tx.data(data);
    /* Write the data to the servos */
    //sbus_tx.Write();
    thrVal = data.ch[2];
  }
  hub.handle();                           //Handle new data
}

sportData getSensorData(CustomSPortSensor* sensor) {
  sportData data; 
  // mySerial.println("Sending SPort data");
  data.applicationId = 0x5100;            //Set the sensor id for the current data poll. Set to 0 to discard the data, skip to the next sensor
  data.value = thrVal;                      //Set the sensor value 

  return data;
}
`

**Comment by 00steven** [comment]
In1.5.13 it looks to be worse again Twin xlite and tw gr6 receiver. It trows in telemetry lost warning to . every thing keeps working.

Pleas get rid of this bug it is verry anoying and reported allot!

**Comment by robthomson** [comment]
I think that you are blaming ethos for an issue when functionally the problem is probably something to do with the code you have running.

I have numerous sensors that I have DIY'd and none of them have this issue.

I have only looked at your code on my phone - so not 100% clear how/what you are trying to do this - but by all means if you send me a git link to the code I will have a quick once over to see if I can spot anything.

**Comment by fdm225** [comment]
@robthomson I am not, I said that it was in my code as I also said twice to close this issue.  If you read my post I specifically say that I left this open so the devs could get whatever info they can as others are having similar issues that they have been unable to fix.

**Comment by robthomson** [comment]
Ah.. yes.  I see that another person interjected claiming an issue - but was totally unrelated. - essentially a *rant* with no context!

**Comment by bsongis-frsky** [comment]
@00steven there is no bug there in Ethos. Since > 1 year it always finishes with a bug found in the sensor. There is one issue left when using a redundancy box if I am not mistaken, but again it is not Ethos
