### ISSUE TITLE
LUA - ELRS 1.5.0 github module no longer runs

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4392]
I can no longer get my ELRS to run with the current files.  (As of 08/16/2024 new improved LUA script)
Main Lua has only 731 bytes.

How do I get it working again?
Where can I get an executable main.lua for ELRS 1.5?

Thanks for the help 

Greetings Eugen

**Comment by yak55** [comment]
I managed it by trying and testing.

A small manual would have been very useful.

Greetings Eugen

**Comment by antlerhanger** [comment]
I know to download the main.lua but do I download the other files ? Where would the other files be installed ?

**Comment by yak55** [comment]
Hello, create a new folder in the Scripts folder
ELRS.
Please copy the following 3 files into this folder.
Namely: 
compile.lua 
elrs.lua
main.lua.

Important: now create an empty folder in the ELRS folder with the following name: compiled

When you restart your FST, the necessary files are then automatically created in the complied folder.

This is exactly how it worked for me on 3 transmitters and 3 simulators.


I hope I have described it clearly.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
This "compiled" folder should have been added to the repository then?

**Comment by MIKE-DAILEY** [comment]
> Hello, create a new folder in the Scripts folder ELRS. Please copy the following 3 files into this folder. Namely: compile.lua elrs.lua main.lua.
> 
> Important: now create an empty folder in the ELRS folder with the following name: compiled
> 
> When you restart your FST, the necessary files are then automatically created in the complied folder.
> 
> This is exactly how it worked for me on 3 transmitters and 3 simulators.
> 
> I hope I have described it clearly.
> 
> Greetings Eugen

Worked for me too!

**Comment by MIKE-DAILEY** [comment]
> This "compiled" folder should have been added to the repository then?

Yes, it is there but the readme with it could be clearer.

**Comment by robthomson** [comment]
I will see about making the script make the folder.

Tbh.. Probably easier now that we have a lua installer tool in ethos suite for a zip file to be included got people to download.

I will modify the repo to have a src folder, and a zip file for the release.

**Comment by robthomson** [comment]
It's worth noting that the  compile script has some override options on it.

If you create a file:

/scripts/nocompile

The script will not compile anything.

Alternatively you could do a

/scripts/elrs.nocompile

And that will also work.

Handy if debugging issues and you don't want to keep purging the byte cache

Rob

**Comment by robthomson** [comment]
I have adjusted as outlined above.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/1.5/lua/elrs

**Comment by MIKE-DAILEY** [comment]
Thanks, Rob.  Tested again using the ETHOS SUITE Lua installer and all worked well.
