### ISSUE TITLE
X18S Simulator 1.5.11 image path wrong

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4394]
1.5.11 sim X18S still takes model images from program files(X86) / frsky / X18S / bitmaps / models.
instead of c:/users/user/.ethos/X19S/bitmas/models.

**Comment by bsongis-frsky** [comment]
We are at 1.5.13!

**Comment by i3dm** [comment]
Was this bug fixed in 1.5.13? If so you can close the issue.

**Comment by i3dm** [comment]
It still occurs with 1.5.13

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment]
No. If the directory exists in your .ethos/<radio> it will be used properly

![image](https://github.com/user-attachments/assets/f40a269d-70ee-43db-bab0-7a8d49fd1940)

**Comment by i3dm** [comment]
So you need to create the directory when Sim is installed.
Otherwise this makes no sense.
I don't expect the user to know all this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
