### ISSUE TITLE
ETHOS Suite - Force backup before update

### ISSUE THREAD

**Issue by frskyrc-ben** [FrSkyRC/ETHOS-Feedback-Community#4399]
ETHOS Suite really needs to force backup before any update. 

1.5.12 model corruption affected several users.

The ETHOS Suite should force a backup before any update because many users do not think or know how or whete to make a backup.

If possible, it should be added as a core step of the firmware update .bin, so even if a user will download the firmware.bin and manually update, it should create the models backup .zip to the SD card or radio internal memory.

Perhaps it can keep at least three backups but no more than 10, and rotate them accordingly to prevent the internal memory or SD card to become full

**Comment by robthomson** [comment]
I think it should be sufficient to simply prompt a user - would you like to back up first.  This is advice etc etc.

Forcing a backup is great.. But for anybody doing development and firmware testing.. You already have a backup.  Therefore you don't want to redo a lengthly backup for no reason.

**Comment by pmullen503** [comment]
Reminding a user to make a backup is a good idea. Forcing is another. A full backup included sounds an bitmaps takes some time. 

Maybe automatically backing up models.

**Comment by frskyrc-ben** [comment]
Perhaps the option to skip backup can be added if Developer Mode is enabled in ETHOS Suite, or skip backup if there is already a backup created from the firmware version being updated from.

At the very least I think there should be a mandatory backup whenever the model template structure changes significantly. Just backing up the model template files would be fine as it's generally not necessary to backup the model images or audio files since those can be re-downloaded fairly easily. 

It's just the model templates that are hard to recover if you don't have a backup and have several models or very complex programmed models

I'm sure there is a good solution here but often times when I ask if the user has made a backup, the answer is generally "No" even though there is plenty of posts and videos about doing it...

**Comment by strgaltdel** [comment]
my interpretation of the threads in the German forum in recent years is that the clear majority of users are not a particularly computer-oriented group and want the simplest possible operation out of the box

many do not even consider the incompatibility of the model files after updates, even though it has been mentioned several times.

if a downgrade is actually necessary in individual cases, there is a lot of whining

the forced backup of the models folder would imho be an improvement for most users

for “experts”, a system setting can be created that prevents the backup during manual updates.

a checkbox could also be implemented in the suite to suspend the mentioned auto backup via suite.

in addition, as an idea:  
the suite should be able to recognize that local auto-backups exist in the tx-volume and migrate them to the computer to ensure free storage space for small volumes

**Comment by pmullen503** [comment]
> Perhaps the option to skip backup can be added if Developer Mode is enabled in ETHOS Suite, or skip backup if there is already a backup created from the firmware version being updated from.
> 
That would be a good compromise. 

Experienced users know to backup before an upgrade since once you load a model, you can't go back if it's a significant upgrade.
