### ISSUE TITLE
Treatment of null operand in logical switches

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#44]
In Ethos:  

`AND, SH-down, ---`  returns False regardless of SH. 
`OR, SH-down, ---`  returns the state of SH. 

In both cases, Ethos treats '---' as False. This is the opposite of OpenTX which treats it as True.

It would be nice if ETHOS was consistent with OTX as it would aid porting of setups.

**Comment by bsongis-frsky** [comment]
I don't see what is wrong here. 
If in OpenTX "SH-Down OR ---" returns always True, then OpenTX should be fixed.
