### ISSUE TITLE
1.5.13 TIMER Edit: Mode down: No announcement audio for negative values.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4401]
TIMER setup: Audio Actions: 
1) Count down: no audio when the timer goes negative.
2) Play value: Start audio before the start value.
No audio for negative values.

**Comment by mawzthefinn** [comment]
Duplicate of #253 

please continue the discussion there

**Comment by philippe-warnotte** [comment]
Ok for negative time but when you choice "Play value", the audio start  before the "start value"
