### ISSUE TITLE
How do I find out if a source is red or white with lua?

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4403]
I would like to find out if for example "Air speed" (pitot tube) stopped reporting data.

system.getSource("Air speed"):value() will give me the last known reading.

Even if I unplug the air speed sensor after it has been plugged in for a while, it will provide me with last known reading.

Is there a way to know if it's actually active?

Thank you

**Comment by bsongis-frsky** [comment]
`source:state()`
