### ISSUE TITLE
Télémétrie sur recepteur LEMON RX compatible DSMX SPEKTRUM

### ISSUE THREAD

**Issue by jjgracia** [FrSkyRC/ETHOS-Feedback-Community#4404]
Lors de l'appairage toutes les voies  fonctionnent ainsi que la tension RX et tension batterie , mais je n'arrive pas a avoir le RSSI , le Vario
et l'altitude ; lors de l' appairage j'ai essayé plusieurs codages : DSM2 et DSMX tout fonctionne comme décrit ci dessus.
Nota ce RX fonctionne bien (vario RSSI et altitude) sur radio DX9 spektrum en DSMX

**Comment by bsongis-frsky** [comment]
Duplicate of #3546
