### ISSUE TITLE
Butterfly

### ISSUE THREAD

**Issue by 10KPP** [FrSkyRC/ETHOS-Feedback-Community#4405]
Hello, I need your help again. I've been trying to program butterfly delay via the throttle for days.
If throttle is down then butterfly should be 100%, if throttle should be around 30% butterfly should be 0%.

**Comment by ETHOSWarrier** [comment]
https://rc-soar.com/ethos/code/crow/

**Comment by 10KPP** [comment]
Thank you!

**Comment by 10KPP** [comment]
Thank you!
