### ISSUE TITLE
X20S V1.5.12 Simulator no timesetting correktur possible

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#4408]
V1.5.12 Simulator no timesetting  correktur possible

before it was all ok

![image](https://github.com/user-attachments/assets/dde4979e-57d2-466b-ab14-be4ba9c4289e)

**Comment by bsongis-frsky** [comment]
It's not stored in the radio.bin, so the simulator can do nothing with it
