### ISSUE TITLE
1.5.14 Nightly Time and Date Resets on Reboot After a Model Change

### ISSUE THREAD

**Issue by Dfrazier1965** [FrSkyRC/ETHOS-Feedback-Community#4409]
Installed 1.5.14 Nightly on my X20 ProAW. Noticed the Time and Date Resets on Reboot After a Model Change. Looks like it affects the first time any particular model is selected and then Tx is turned off and back on. Doesn't reset on any model that has been previously selected.

**Comment by bsongis-frsky** [comment]
Will be fixed in the next nightlies
