### ISSUE TITLE
Function "Play Sequence"

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#441]
The original idea comes from Mike Blandford. Here are the requirements for this function:

- [x] A sequence will be composed of fragments
- [x] Each fragment is composed of one condition and one Play function (Play Track, Play Value)
- [ ] ~~Each time the sequence is played, for each fragment, the condition is checked ; if it is True, then the Play function is executed~~

**Comment by MikeBland** [comment]
Does each "fragment" need its own condition, or just one condition for all fragments?
The original idea, as used in erskyTx is:
![xvfd9n7p](https://user-images.githubusercontent.com/6413420/121336173-2c510180-c913-11eb-8804-51822d989a7f.png)
Source is the item such as a telemetry item.
Function is one of: -------  v>val  v<val  |v|>val  |v|<val  v~=val v=val  v & val  |d|>val  v.mod.val=0
Value is the val used in the function
Switch is used to enable the alert
Trigger is one of: ON OFF BOTH ALL ONCE or a value from 2 to 30 seconds
On Delay allows for a pause before starting the output, useful when the switch a 6-pos switch.
Play Source is No, Before or After (the voice file specified later)
On no Telemetry allows alerts to be muted hen no telemetry is available

Trigger = ON, means play the alert when both the function and the switch are TRUE.
Trigger = OFF, means play the alert when both the function and the switch were TRUE and one or both become FALSE.
Trigger = BOTH, means play for both ON and OFF, with the last character of the filename having 1 added to it for OFF.
Trigger = ALL is like BOTH, but works for the 6-pos switch with 0,1,2,3,4 or 5 being added to the last character of the filename.
A trigger value of 2 to 30 causes the alert to be repeated periodically at the specified rate (as long as the function and switch are true)

**Comment by mawzthefinn** [comment]
This would be an excellent extension of the Play Value functionality

**Comment by bsongis-frsky** [comment]
Implemented in 1.5.0
