### ISSUE TITLE
Pixel limitation in LUA widgets

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4412]
Very interesting limitation:

At first it seemed like I'm running out of memory.
This test proves I'm not running out of memory because the image is only 2kb!
[noam.zip](https://github.com/user-attachments/files/16676013/noam.zip)

Instructions:
4 screens all full screen without titles
Screen #1 gets noam1
Screen #2 gets noam2 
Screen #3 gets noam3
Screen #4 gets noam4
You will not be able to access 4ths screen. 

Latest X20S simulator.
Also replicated on actual X20pro with latest firmware
Thank you!!!!

PS - I am aware I can make widget #1 image global. Then the problem goes away.
But imagine if all 4 images were different. Then they cannot be shared.

**Comment by bsongis-frsky** [comment]
You have to consider the expanded size of your bitmap, so 800x480x16bits/pixel = 768kBytes!
