### ISSUE TITLE
X10S unable to display voltages when using FLVS and ZAVIONIX CELL lua script.

### ISSUE THREAD

**Issue by Hennyvt** [FrSkyRC/ETHOS-Feedback-Community#4413]
This function operated normally with X10S radio firmware 1.5.6. The radio is now at 1.5.12, the lua script appears to be running but no voltages displayed on the Screen-2. The receiver is an Archer GR8 with FW 2.1.14. I also tried an Archer GR8 plus with the same results.

My X20S under the same conditions works normally so this appears to be an X10S issue.

Connect the FLVS, discover new sensor (Lipo) To configure this add a screen (Screen-2 in my case) Select Zavionix Cells as the wizard, then Lipo as the source. With a lipo connected to the balance input of the FLVS 4cell or 6 cell the lua script automatically configures screen-2 displaying the pack voltage as well as the cell voltages when it's working correctly.

**Comment by bsongis-frsky** [comment]
Please add a screenshot of your screen 2 configuration + result!

**Comment by Hennyvt** [comment]
![GR8-FLVS](https://github.com/user-attachments/assets/3582609a-63a0-41d9-910c-7da0403c29a9)
![GR8-FLVS](https://github.com/user-attachments/assets/b894ea1b-0b12-48e5-97bd-2547a50b0982)

**Comment by Hennyvt** [comment]
I trust the Jpeg is up loaded

**Comment by bsongis-frsky** [comment]
This widget "Zavionix" is not provided by FrSky. And it is closed source. I am afraid I cannot help here!

**Comment by Hennyvt** [comment]
Hi Bertrand.

 

I am not convinced it’s Zavionix cell lua script at fault. It works fine in my X20S FM version 1.5.12 and it worked in the X10S with FM version 1.5.6 why would it fail to work after a FRsky firmware update  on the X10S. The Zavionix lua script is the same for both radios.

 

Is it not possible to see why the cell voltage data is not being presented to this lua script.

 

Thank you

Henny
