### ISSUE TITLE
Spektrum Dsm2 keine/ NO Bindung/ Binding  mit Neuer Lua Script x18 Multiprotocol irx4 lite 

### ISSUE THREAD

**Issue by Robse77** [FrSkyRC/ETHOS-Feedback-Community#4414]
German:
keine Bindung mit Dsm2 mit der neuen lua script .auf Sender x18 firmware 1.5.11 ..Das modul auch auf neuste update gebracht.
Verschiedene empfänger benutz kein erfolg. nur mit im auto binding bindung erfolgreich ,aber servos bewegen sich nur in einer richtung English:
"no binding with Dsm2 with the new lua script on transmitter x18 firmware 1.5.11.. The module also updated to the latest version. Various receivers used without success. Only successful binding in the car, but servos only move in one direction."

**Comment by bsongis-frsky** [comment]
Please try to use english here, or it's difficult to help!
Did it work before?

**Comment by Robse77** [comment]
Yes, it works with the previous lua script. With the new one, only dsmx works but no more dsm2. 
Only when I go to auto bind , the reciver will bind ,but only allows the servos to run at half capacity.
If it helps you, I would make a video and upload it to YouTube and send the link.

**Comment by bsongis-frsky** [comment]
It should be fixed, right?

**Comment by Robse77** [comment]
Yes IT works fine now.
