### ISSUE TITLE
ERLS doesn’t work on X10 express

### ISSUE THREAD

**Issue by chiaradubaldi** [FrSkyRC/ETHOS-Feedback-Community#4415]
X10 express, Ethos 1.5.13, erls lite irx4 (Div ESP32 E28 2.4Ghz) module + adapter lite/ir betafpv tested with both lua versions, the past one and the last one with the "compiled" folder. 

The module turns on, but when I select "configure" on the RF menu, I get a black screen (elrs configuration) making it impossible to see the parameters and use the module. 

The same module works perfectly on x14 (without the adapter, here not necessary). So I thought the problem could be the adapter, but the same module+adapter work fine with an "old" Taranis X9D with OTX 2.3.15 (here it's seen as crossfire). 

Bind and use tests have been done with rx rdiomaster E4R. 

Any idea on why this happens?
![ELRS X10 express _01](https://github.com/user-attachments/assets/39e4e33e-38d4-4297-a137-8a370b4bb90c)
![ELRS X10 express_02](https://github.com/user-attachments/assets/bdec45a4-2c48-4e74-aa24-0dfa7d1794d5)

**Comment by bsongis-frsky** [comment]
Does the Bind / Channels / Telemetry work with this setup?

**Comment by robthomson** [comment]
What version of the ethos lua are you using?

**Comment by robthomson** [comment]
You should be using the most current:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/1.5/lua/modules/elrs/elrs.zip

Can you confirm this is installed? And what version of ethos you have installed?

**Comment by robthomson** [comment]
So I have had a friend test the latest elrs on an x12 (believe same as x10)

All works as expected.

@chiaradubaldi can you please upgrade to latest lua and ethos then report back?

**Comment by chiaradubaldi** [comment]
@bsongis-frsky Yes, the same set up works on the X14 (same module, release firmware and same ethos release). 
Also same bind, telemetry e channels (tested with 3 servos connected).
Same thing with the Taranis 9D... including telemetry (last OTX release and module adaptor), however here it's seen as crossfire (I didn't have the elrs choice in the scripts/tool).

Only the x10 express gives me problems with this set up. 

@robthomson Yes, I'm using the latest lua version, the one with more files and the folder "compiled"  - but also the previous version, the one with just the main.lua file, it gives the same problem. 

![X10_003](https://github.com/user-attachments/assets/a03b48e1-98f7-44bd-9613-22f55fb8e72d)

**Comment by chiaradubaldi** [comment]
@bsongis-frsky here some photos of the set up working on the x14 and on the taranis

![set up_01](https://github.com/user-attachments/assets/345c2a56-2e54-4f96-87f1-dadc487da685)
![set up_02](https://github.com/user-attachments/assets/41c0cfe2-025d-4174-97fe-519977a4b945)
![set up_03](https://github.com/user-attachments/assets/3ee1b938-620a-4ba6-901a-4bc31267e48b)
![set up_04](https://github.com/user-attachments/assets/1d3693eb-edfc-4a95-a210-18a74dd8e6a5)
![set up_05](https://github.com/user-attachments/assets/9ad38604-4530-4c81-9ab9-f0b0079153d0)

**Comment by robthomson** [comment]
OK m so if previous also does not work that would imply that there is something else going on on the radio.

We might need to try find another x10 ethos user to do some testing as it def works on x12!

**Comment by robthomson** [comment]
OK.. I have secured an x10 I borrow on Saturday.  Will try replicate the issue

**Comment by chiaradubaldi** [comment]
@robthomson Thank you! Hoping to receive positive news soon then!

**Comment by ftc2629** [comment]
> X10 express, Ethos 1.5.13, erls lite irx4 (Div ESP32 E28 2.4Ghz) module + adapter lite/ir betafpv tested with both lua versions, the past one and the last one with the "compiled" folder.
> 
> The module turns on, but when I select "configure" on the RF menu, I get a black screen (elrs configuration) making it impossible to see the parameters and use the module.
> 
> The same module works perfectly on x14 (without the adapter, here not necessary). So I thought the problem could be the adapter, but the same module+adapter work fine with an "old" Taranis X9D with OTX 2.3.15 (here it's seen as crossfire).
> 
> Bind and use tests have been done with rx rdiomaster E4R.
> 
> Any idea on why this happens? ![ELRS X10 express _01]

I am using a X10s Express with ELRS too (Ethos 1.5.13). I tried with a RadioMaster ELRS module and a RP3-H receiver.
Newest LUA-Scripts installed.
I can bind the receiver, the LUA works, but the connection is not stable. Connection icon shows 'lost connection', a few seconds later 'connection established' etc.
I think, the baudrate of the CRSF protocol together with the X10s Express might be the culprit.
I found a report of the possible issue here --> https://blog.seidel-philipp.de/fixed-inverter-mod-for-tbs-crossfire-and-frsky-qx7/

**Comment by BladeScraper-Designs** [comment]
Tested on Ethos 1.5.13 on my X10S Express, ELRS module 3.1.2, latest ELRS Lua .zip installed with Ethos Suite.  No issues!
https://photos.app.goo.gl/YdNuxPHb71pRMtA58

The X10S *Express* does not require any mods to the module bay inverter.  That was only the old non-Express version!

**Comment by robthomson** [comment]
Just a quick update.   Not forgotten about this.. Found myself without the right usb lead to get ethos onto the radio.

Hopefully have it running by Friday.

**Comment by chiaradubaldi** [comment]
@robthomson ok, thank you!

**Comment by robthomson** [comment]
So I have installed ethos on the x10.   Used the new lua scripts.

Everything 'just works'.

No idea why yours is not happy.

**Comment by robthomson** [comment]
I kind of think the issue may be that your adapter pins are not making contact.

Maybe using some dupont cables you can jumper from the pins to the module.

This if anything will prove if this is the issue.

**Comment by ftc2629** [comment]
Ok. I will try your proposal.
It seems that only me has the issue.
So from my side you can close here.
Thanks

**Comment by chiaradubaldi** [comment]
@robthomson thank you for testing it! It puzzles me how everything works on the other two transmitters. 
I'll try with the cables as you suggested and let you know as soon as I have news!

**Comment by robthomson** [comment]
Do you know if it worked previously?

Does mind of feel just a tolerance thing with pins not being long enough litterally by like 0.1mm!

**Comment by chiaradubaldi** [comment]
I tested it with connecting it directly with the cables and the problem remains the same. 
Other external modules on the X10 express work, as the multi-protocol 4 in 1 module works perfectly, or a RM9 access, for example.

I did one last test: I disinstalled ethos e installed OTX (the last version, the same I have on the taranis) and... it doesn't work (as crossifire, which it does on the taranis)!

I believe at this point that it's my x10 that has a problem, so at this point i'll give up using elrs on the x10. 

I believe we can close it here, thank you for your support.

**Comment by robthomson** [comment]
Ok.. sorry you have not been able to resolve.

I suspect that your X10 has had an 'invertor mod' on it.  Changes are it was done baddly.

If you are handy with a solder iron.. check this page for clues.

https://www.flyingtech.co.uk/product/taranis-qx7-x10s-x12-inverter-mod-for-tbs-crossfire/
