### ISSUE TITLE
'Additional' Fonts XXXL and XXXXL - are they working?!!

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#4417]
### Discussed in https://github.com/FrSkyRC/ETHOS-Feedback-Community/discussions/4266

<div type='discussions-op-text'>

<sup>Originally posted by **DH106Comet** July 13, 2024</sup>
I've just downloaded Ethos 1.5.11 onto an X20Pro and I'm having a lot of trouble accessing/using these two 'additional' fonts XXXL and XXXXL. I need to use them as I'm porting an older lua script from the Horus which has a lower screen resolution.

What's the current status regarding them? I've read other threads which state that they must be copied from the FLASH drive to the RADIO drive, and that they should be loaded in the 'build' event using lcd.loadFont( ).

I had some partial success in Ethos 1.5.8 - but only ONE of the two fonts would ever be useable (the first one to be loaded), the other would not work. Now that I've upgraded to 1.5.11, nothing I do seems to make them work :-(

</div>

**Comment by bsongis-frsky** [comment]
Would you try the 1.5.14 nightly fonts?
Fonts may be placed anywhere, but in this case you have to load them with a full path
Or they may be placed in FLASH:/fonts and then you will load them as done in the example below (standard way)

**Comment by bsongis-frsky** [comment]
Example of script which will work as it is part of Ethos CI:

```lua

-- XXXXL widget

local function create()
    local font = lcd.loadFont("xxxxl.fnt")
    return {font=font, color=lcd.RGB(255, 0, 0)}
end

local function paint(widget)
    local w, h = lcd.getWindowSize()
    lcd.color(widget.color)
    lcd.font(widget.font)
    lcd.drawText(w / 2, 50, "Land   NOW!", CENTERED)
end

local function init()
    system.registerWidget({key="xxxxl", name="xxxxl", create=create, paint=paint})
end

return {init=init}
```

**Comment by philippe-warnotte** [comment]
Merci, mais on lui donne quel nom à votre fichier script? Où le placer et comment l'exécuter svp?

**Comment by salibaj2** [comment]
I did not tried it yet on a real Tx, however, there is still some compatibility issues between simiulator and real hardware.

FONT_XXXXL = lcd.loadFont("FLASH:/fonts/xxxxl.fnt")

does not work in simulator. 

So if you have multiple instances when to call the FLASH within a LUA could be a problem when transferring LUA to real hardware.

**Comment by bsongis-frsky** [comment]
I have just tried it again:

```lua
-- XXXXL widget

local function create()
    local font = lcd.loadFont("FLASH:/fonts/xxxxl.fnt")
    return {font=font, color=lcd.RGB(255, 0, 0)}
end

local function paint(widget)
    local w, h = lcd.getWindowSize()
    lcd.color(widget.color)
    lcd.font(widget.font)
    lcd.drawText(w / 2, 50, "Land   NOW!", CENTERED)
end

local function init()
    system.registerWidget({key="xxxxl", name="xxxxl", create=create, paint=paint})
end

return {init=init}
```

The fonts are there on my computer (they come from the simulator installer):
![image](https://github.com/user-attachments/assets/ef9f2fbc-3f7c-433a-8437-c89b94d04b37)


This is the result:
![image](https://github.com/user-attachments/assets/5d37343b-f371-48bd-880c-1e76ee766226)

**Comment by philippe-warnotte** [comment]
I think I don't have good files font. Simulator V20 1.5.14  xxxl.fnt and xxxxl.fnt date 24/08/24.
![image](https://github.com/user-attachments/assets/7f6b3231-c81b-42bf-85ef-843d688f319b)

**Comment by philippe-warnotte** [comment]
OK with X20S Simulator 1.5.14
![image](https://github.com/user-attachments/assets/26110547-2417-4dbf-8946-1cef8a7c2e10)

**Comment by philippe-warnotte** [comment]
I copied the  "xxxL.fnt and xxxxL.fnt" files from the X20S simulator to the V20 Simulator but without success !
I'd rather not risk doing that on my radio.

**Comment by bsongis-frsky** [comment]
I jave just tried with V20. The font is installed in its own directory.

**Comment by philippe-warnotte** [comment]
THANKS. I had a problem in my script. It's OK now.
How to integrate this script for a timer?

**Comment by bsongis-frsky** [comment]
I will close the issue then. For a timer, instead of writing a static text, you will have to write the timer value, and refresh it every second
