### ISSUE TITLE
Lua 1.5.14 nightly - source:unit() not working in init() or read() - likely after #4411 enchancement

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#4418]
Thanks a lot for implementing the #4411 enhancement - the logic/sequence works as expected and really well.
One potential side effect from the change is that setting source:unit() seem to be partially broken:

~`source:state()` always return false~

```lua
local function sourceinit(source)      
  source:unit(UNIT_PERCENT)
  print("Init: ",source:unit())
end

local function read(source)      
  source:unit(UNIT_PERCENT)
  print("Read: ",source:unit())
end

local function wakeup(source)      
  source:unit(UNIT_PERCENT)
  print("Wakeup: ",source:unit())
end
```

Before 1.5.14 nightly:
-- Init: 23
-- Read: 23
-- Init: 23               --[[ Fixed with #4411 ]]
-- Wakeup: 23

In 1.5.14 nightly:
-- Init: nil
-- Read: nil
-- Wakeup: 23

Many thanks

**Comment by bsongis-frsky** [comment]
It's strange. The behaviour before 1.5.14 nightly should be:
-- Init: nil
-- Read: nil
-- Init: 23
-- Wakeup: 23

**Comment by Alex00101** [comment]
Apologies, you are correct. I've got versions mixed, on 1.5.13 the output was exactly.
-- Init: nil
-- Read: nil
-- Init: 23
-- Wakeup: 23

So if 1.5.14 can be further improved to allow unit and decimals to be set in init... that would complete the enhancement.

**Comment by bsongis-frsky** [comment]
Yes it will be done today. 
`source:state()` will always return false, there is no state stored in a lua source

**Comment by Alex00101** [comment]
Thanks a lot.
