### ISSUE TITLE
Request: Haptic patterns

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#442]
I Like to request various haptic patterns, short pulses, long pulses or combinations.

**Comment by Hobby4life** [comment]
Something like this?

Pulses
1. [*   *](delay S)[*   *]
2. [* * *](delay S)[* * *]
3. [*****](delay S)[*****]

Long
1. [--   ](delay S)[--   ]
2. [-- --](delay S)[-- --]
3. [-----](delay S)[-----]

Combo
1. [*   -](delay S)[*   -]
2. [* * -](delay S)[* * -]
3. [* - *](delay S)[* - *]

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/135132280-72794f9a-3054-44d6-a9bd-312e92ff8c9a.png)

**Comment by Hobby4life** [comment]
Excellent!
