### ISSUE TITLE
Message ‘Sensor lost’

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4420]
Hello, 
after a long search I have now found a clue to the causes of the ‘Sensor lost’ message. For the sensors distance 2D (source GPS) and distance 3D (source GPS and altitude) you have to use calculating sensors. The message occurs particularly often for distance 2D. If I remove GPS from these sensors, the message disappears. Unfortunately, you cannot set a delay time in the calculating sensors. However, these sensors do not turn red, as the error probably only occurs for a very short time. The VFR sensor and GPS (less frequently) are also lost more often. 
 Transmitter: X10S Express (1.5.13), RX: Archer SR8Pro (SW 2.1.14), GPS AVD, Vari AVD, Neuron II 80, FLVS AVD and speed sensor (because of the two temperatures). Telemetry is connected to the S.Port.
Is there any way to remedy this?
Thank you for your understanding
Wolfgang

**Comment by dap35** [comment]
@Wolepo - In my experience , the GPS Clock sensor is the culprit.   Edit that sensor in your telemetry screen to disable the missing sensor warning delay, and see if that eliminates the issue.

Regards,
Doug

**Comment by bsongis-frsky** [comment]
@Wolepo I am not sure that you have it right, the calculated sensors shouldn't have have any "Sensor lost" warning!

**Comment by bsongis-frsky** [comment]
@dap35 is right. It would be interesting to follow the GPS sensor.

**Comment by Wolepo** [comment]
Yes, the calculating sensors have no delay in the warning message. But the strange thing is that when I re-insert the GPS in the two distance sensors, the warning messages immediately start again. However, if I delete the GPS time sensor from the list, the messages also disappear. How does this connection come about, GPS time > distance?
The VFR sensor also fails irregularly, which can also be seen in the log.
Wolfgang

Translated with www.DeepL.com/Translator (free version)

**Comment by bsongis-frsky** [comment]
@Wolepo There is no delay because there is no warning! The warning comes from another sensor! I want to work on a feature which adds some history to those warnings! So that you will see on first glance that there has been something bad on this sensor

**Comment by Wolepo** [comment]
Thank you, it is urgently necessary to find out which sensor is causing this warning. The calculating sensors do not turn red. Nevertheless, I do not understand the above connection. GPS removed from sensor > no message, GPS reinserted > messages, GPS time deleted > no messages, GPS time found again > messages. You could do without the GPS time if necessary, but then you can't synchronise the system time with it.

**Comment by dap35** [comment]
Disabling the Missing Sensor delay for the GPS Clock sensor does not remove the sensor, it only eliminates the warning for that specific sensor when the data is intermittent.  In my experience, the GPS Clock updates drop out for an update or two, then come back.    You should not have enough clock drift in your system during a flight that causes an issue.    
I would also suggest downloading the telemetry logs from one of these flights and you can see when/how often the GPS clock skips.

**Comment by noamkrief** [comment]
" I want to work on a feature which adds some history to those warnings!"


PLEASE!!! Thank you!
