### ISSUE TITLE
1.5.13 FCC Cloned or new model receiver are grayed in the RF system

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4422]
I have one of the first X18 which includes a gyro. I downloaded 1.5.13 X18-FCC, cloned a model, and when I tried to bind the RX I got this screen, regardless if the RX is on or off. In addition, I can bind the RX to the original model. This is a TD SR10 receiver.

![IMG_20240822_183011916_HDR 1](https://github.com/user-attachments/assets/73f5f321-3acc-43b9-ae6c-793e2fa31940)

**Comment by Richrfl** [comment]
More. The same happens in the 1.5.13 x18S sim. Please, I need instructions on how to downgrade to 1.5.12.

**Comment by pmullen503** [comment]
Use Ethos Suite and select an earlier version of Ethos.

**Comment by bsongis-frsky** [comment]
@pmullen503 why?

**Comment by bsongis-frsky** [comment]
@Richrfl I think that your internal module is OFF. I would see some RSSI bars in the top bar otherwise.

**Comment by Richrfl** [comment]
Bert, once again you hit the nail. My mistake. I forgot there is a setting at the top of the RF window to activate the internal module. However, I do not remember having to enable the internal module in previous clones.

**Comment by Richrfl** [comment]
Thank you Mullen.
