### ISSUE TITLE
GPS Widget only has 2 coordinate fields when Hebrew Language selected

### ISSUE THREAD

**Issue by frskyrc-ben** [FrSkyRC/ETHOS-Feedback-Community#4423]
GPS Widget only has 2 coordinate fields when Hebrew Language selected

![Figure 1](https://github.com/user-attachments/assets/8b84e0de-45f3-4801-986d-ab4fd7673c8b)

Compare vs. English : 

![Attached](https://github.com/user-attachments/assets/9479953c-4a1c-4d39-b81a-62ee6e8a6703)

**Comment by bsongis-frsky** [comment]
Fix ready for next nightlies

![image](https://github.com/user-attachments/assets/df270286-36a6-4199-bf2f-9051d5deb37f)

And alignment (all languages) improved

![image](https://github.com/user-attachments/assets/64b6f7f7-01ac-4306-a246-2d55b10f8717)
