### ISSUE TITLE
Error in the current new ELRS script “Switch Mode” 1.5.13

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4424]
Error in the current new ELRS script “Switch Mode”

Tested with Tandem XE and Vantac 1.5.13
as well as X20S and Radiomaster Ranger Nano 1.5.13

If the switch mode is changed, in my example from 8ch to 12ch Mixed or 16ch Rate /2, the setting is not saved and also not activated.

Greetings Eugen

![Bild 1 + 3](https://github.com/user-attachments/assets/b0a06548-cea3-4567-a5b4-06c46461a41d)

**Begin**

![Bild 2](https://github.com/user-attachments/assets/4cf48236-cd33-4584-ae9c-19945dd816c7)

**Switch Mode changed and saved**

![Bild 1 + 3](https://github.com/user-attachments/assets/e37f3c43-5d45-4473-a8e7-2249a545b5d0)

**configuration called again**

**Comment by robthomson** [comment]
What version of elrs have you got installed?

Nothing has changed lua wise in this regard so trying to see why this would be the case.

**Comment by robthomson** [comment]
I have just tested this and it works perfectly?

https://www.youtube.com/watch?v=6ChyTdvoees

**Comment by robthomson** [comment]
https://www.youtube.com/watch?v=6ChyTdvoees

**Comment by yak55** [comment]
Hello Rob, ELRS Version is 3.4.3.0

**Comment by robthomson** [comment]
Thanks. Will test against that.

**Comment by yak55** [comment]
It is the EU  LBT version Germany

Eugen

**Comment by yak55** [comment]
Hi Rob, now it has worked once.
But then the following display:

Greetings Eugen

![Fehler](https://github.com/user-attachments/assets/fd6a44c6-80f8-4bf1-a236-b3dccf3c552a)

**Comment by robthomson** [comment]
Can you please open the file main.lua

And set the flag to use compiling to false?

**Comment by yak55** [comment]
Hello Rob, now I can reproduce the mistake. NO CONNECTION ! to receiver - script  function ok.

Transmitter connected with receiver -  no function of script.

Maybe it’s helpful for you.

Eugen

**Comment by robthomson** [comment]
I have an x10 now and will test function works as expected.

Worth noting.. bladescraper has tested already and found function works on the x10. 

If I find mine also works,   it will be looking more like a local / hardware issue on your end.

Will find out by early next week.

**Comment by yak55** [comment]
That would be strange, X20S and Tandem XE, Vantac and Radiomaster Ranger Nano would have to be defective at the same time.

That would be a great coincidence.

Please be sure to test with the receiver bound.
This is the reason why I get the errors.

I now simply leave the receiver off, set everything on the transmitter - then supply the receiver with power - this is how it works with both transmitters and with both modules.

Greetings Eugen

**Comment by yak55** [comment]
Hi Rob, thanks for your efforts.
I looked further and just found the solution in the ELRS description.

Your script is ok.

Greetings Eugen

![IMG_6521](https://github.com/user-attachments/assets/baf8258f-526d-4082-95d6-fcbd4b4fcae0)
