### ISSUE TITLE
New model type, flight wing 

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#4429]
Ethos Version: 1.5.13

It will be nice to have a model type "Flight Wing"  in the model creation process with the all the possible configuration, like motor channels, number of ailerons  channels, flaps, break, etc. It will simplify the creation process of the flight wing model. I know that it is possible to create it by set the mix correctly but will be nice to have it  in the creation model process. 

Thanks, Franco

 
![Flight Wing](https://github.com/user-attachments/assets/4d51d15a-a461-4250-a83d-b8461d5f4b97)

**Comment by mgsanna** [comment]
Nel wizard basta specificare che il modello è senza coda….. e ti crea già i mixer x tutta ala…. Senza creare mixer ad hoc da parte dell’utente…

**Comment by fdapport** [comment]
Ottimo,, grazie per l'informazione.... Great.. Thanks for the information.
