### ISSUE TITLE
BUG: Bluetooth Search devices, all radios

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#443]
Now the bluetooth trainer function is active, is it even possible to create a BT Trainer connection between a X10S Express (Ethos) and a X20S?

Until now no luck setting this up.

**Comment by bsongis-frsky** [comment]
I played with an XLite-Pro the whole day yesterday and yes it works, in both directions.

**Comment by Hobby4life** [comment]
Well i could find the x10 and x20 bt adress on both radios in v1.07 but no connection. In v1.09rc2 i can not find them anymore

**Comment by Hobby4life** [comment]
Tried again, but no way both radio's find each other.

Both radios "Waiting for devices" visa versa.

In v1.07 they did see each other.

**Comment by Hobby4life** [comment]
Again confirmed x20 <--> x10 not working.
X10 <--> X10 working!

**Comment by bsongis** [comment]
And X20S / Ethos <--> X-Lite Pro / OpenTX working :)

**Comment by Hobby4life** [comment]
Will try tonight

**Comment by MIKE-DAILEY** [comment]
**Bluetooth Testing**

**#1 X9D Plus SE 2019 connected BT Master to X9 Lite S slave.  Now try with ETHOS.** 
  
#2 X9D Plus SE 2019 Master connects to BT X10S Express and shows its address.  X10S E does not show X9D Address.  

#3 X9D Plus SE 2019 Master connects to BT X20S and shows its address.  X20S shows X9D address. 
 
#4 X9D Plus SE 2019 Master connects to BT X20 and shows its address.  X20 shows X9D address. 

**#5 X9D Plus SE 2019 Slave found OK from X9 Lite S Master**

#6 X9D Plus SE 2019 Slave and X20 cannot find it in search. 

#7 X9D Plus SE 2019 Slave and X20S cannot find it in search.

**Comment by Hobby4life** [comment]
X10S Master can not find X-lite Pro in search
X-lite Master can not find X10S in discover

X20S Master can not find X-lite Pro in search
ditto visa versa

Something is absolutely not right.

**Comment by Hobby4life** [comment]
I have noticed a thing when searching a device on a X10S Express

1. Startup radio + model (master)
2. Start search for other device (slave)
- Radio keeps searching and searching.. nothing found.

Now another procedure.
1. Start up radio + model (master)
2. Start search for other device (slave)
3. Press return directly
4. Start search again
- Now devices are almost directly found within 5 seconds.

**Comment by Hobby4life** [comment]
Another thing in trainer that must be added is more channels.
The 4 channels are fixed to Aileron, Elevator, Throttle and Rudder.
For heli trainer I need Pitch too, now the Trainer throttle is controlling my Throttle channel thats not correct if you want to give your trainee only Pitch.
Make it available for all 8 channels.

**Comment by ssasson5** [comment]
> And X20S / Ethos <--> X-Lite Pro / OpenTX working :)

Hi, I was able to BT Trainer bind between X20S (Ethos) and XLite Pro (OPX). 
I see that salve control the channels on the monitor (including Throttle), all surfaces moving.. but slave not actually changing the Throttle on the plane.. only master controls the motor. 
Any suggestions why? 
Thanks

**Comment by Hobby4life** [comment]
Known problem, will be fixed in v1.10

**Comment by bsongis-frsky** [comment]
Is it fixed in 1.0.10? The Bluetooth pages / process has been completely reviewed

**Comment by Hobby4life** [comment]
Yes,, fixed now.. devices found just after on press on search button

**Comment by dobosatti** [comment]
Dear programmers!
They can solve the problem of having the X20 Tx bluetooth communicate with an external bluetooth module and transfer it via the external bluetooth module  the telemetry data to an antenna tracker?
