### ISSUE TITLE
New telemetry sensor ID`s 2.4GHz VFR and 900MHz

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#4430]
Hello Bertrand,
I hope you had a good rest on vacation.
I make some test on X20Pro, X20S and Tandem XE
Were the S.PORT/FBUS telemetry IDs for VFR changed in the ETHOS 1.5.13 version?
VFR 2.4GHz and VFR 900MHz
ETHOS 1.5.11: PhyID DEC 25 , **HEX 18** , 0xF010 , 0xF010
ETHOS 1.5.13: PhyID DEC 27 , **HEX 1A** , 0xF010 , 0xF010
best regards,
Torsten

**Comment by bsongis-frsky** [comment]
Ethos is not responsible of the sensors ID§
VFR comes from the module, perhaps you have updated it?

**Comment by Satcomix** [comment]
Hello Bertrand, 
Thanks for the quick reply.
I updated the ISRM of the X20S to 2.2.7, the XE still has 2.2.6 installed.
Why are new IDs generated during an ISRM update?
I thought your S.PORT/FBUS sensor ID list was binding.
best regards,
Torsten

**Comment by Satcomix** [comment]
Hello Bertrand,
I just downgraded my X20S from ETHOS 1.5.13 to 1.5.10 and the RF ISRM from 2.2.7 to 2.2.6.
Both VFR values are ID18, update to ETHOS 1.5.13, both VFR Values are ID18,
It's not because of ETHOS 1.5.13!!!
In tandem mode, both VFR values ​​are displayed as ID 18 for version 1.5.13 and ISRM 2.2.6.
When upgrading the X20S to ISRM 2.2.7, both TD VFR values ​​are displayed as ID 1A.
What surprises me is the display on my Tandem XE radio. (ETHOS 1.5.11 and ISRM 2.2.6 but VFR Sensor ID 1A)
Because on my X20 Pro with ETHOS 1.5.11 and ISRM-Pro 1.1.13 both VFR values ​​are displayed as ID18.
I think it's an ISRM firmware problem that changes the telemetry sensor ID.
I also noticed another problem.
When viewing the info display at my Tandem XE, all telemetry sensors on the Archer Plus R12+ are lost.
If I now leave the info display, only the receiver's internal sensors come back and all others are not displayed (values ​​remain red)
Only a power OFF/ON shows all values ​​again.
These problems do not occur when operating with a TD-R10 receiver.
Best regards,
Torsten

**Comment by Satcomix** [comment]
Good morning Bertrand,
Should I close the issue? 
since you entered the RF symbol for similar problems.
best regards,
Torsten

**Comment by Satcomix** [comment]
Hello Bertrand,
I researched further and found that with the new ISRM 2.2.7 firmware, all receivers in the Archer and Tandem series receive the same VFR ID 1A. With ISRM 2.2.6 the Archer receivers had the VFR ID 1A and the tandem receivers had the VFR ID 18.
I make the tests with Tandem XE, X20S, X20Pro with Archer Plus R12+, R6mini, TD-R18, TD-R10, TD-R6, TD-MX receiver.
Thank you.
I will then close the issue.
best regards,
Torsten
