### ISSUE TITLE
F-Port sensor data does not work with the FLVS sensor

### ISSUE THREAD

**Issue by Halfduplex85** [FrSkyRC/ETHOS-Feedback-Community#4435]
Hi I have had the problem for a while that I do not get sensor data with a FLVS voltage sensor over F-port protocol,
if I convert this to S-port in the receiver settings then everything works normally and without problems.

I have this problem with all Frsky Archer receivers and multiple firmware versions on the receiver as the transmitter. I am currently running the new firmware on both the receiver and the transmitter.

Transmitter:
Firmware version: 1.5.13 EU
Bootloader Version: 1.5.0
Module version: 1.1.14
Audio English: 1.5.7
System Bitmaps: 1.5.10

Receiver R6, R8-Pro and R10-Pro
Firmware version: 2.1.14

I had this problem with my previous transmitter X20 and now my current transmitter X20 Pro AW.

**Comment by Satcomix** [comment]
Hello Halfduplex85,
You must set the receiver from S.PORT to FBUS not F.PORT.
The FrSky FLVS is compatible with FBUS/S.Port protocol. Look at the specifikations.
https://www.frsky-rc.com/product/flvs-adv/
With FBUS the FLVS Lipo sensor works fine with my X20Pro or X20S
best regards,
Torsten

**Comment by mawzthefinn** [comment]
F.port is not supported by any FrSky sensor.

older sensors support s.port, ADV sensors support s.port and FBus.

f.port is a deprecated protocol supported only for legacy FC use.
