### ISSUE TITLE
Request: variable value widget

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#444]
I Like to request a widget.

When towing gliders I use my altimeter to determine how high I am towing someone. To do this for everyone at the same height, I made a logical function that gives an alarm when I have reached a certain preset height.

So it would be nice if I could change that value directly from a widget on the fly. a kind of global variable. but in a widget.

**Comment by jreis1** [comment]
Not sure if it would be possible as widgets are just “read only”. you can try to use potentiometer to set the height, within a certain range, and display it in a widget.

**Comment by Hobby4life** [comment]
That would be fine too, even better.

**Comment by mawzthefinn** [comment]
This sounds like an opportunity for a Lua developer.
