### ISSUE TITLE
fonction in emergency mode

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#4440]
Hi,

i add some conditions lines (quite a lot !) in the file below, everything is working on the simulator, so i put the file in my x20r. when i try to select the fonction menu the radio goes into emergency mode. I use ethos 1.5.13.
[mytho s5e.zip](https://github.com/user-attachments/files/16752503/mytho.s5e.zip)

Thanks

**Comment by bsongis-frsky** [comment]
What do you mean by the "fonction menu"?

**Comment by bsongis-frsky** [comment]
It is exactly the issue #4263 which should be fixed since 1.5.12

**Comment by bsongis-frsky** [comment]
Reproduced here

**Comment by bsongis-frsky** [comment]
It will be fixed in 1.5.15

**Comment by ronron84** [comment]
Thanks
