### ISSUE TITLE
Checklist in Horus - newline instead of space

### ISSUE THREAD

**Issue by RA-100** [FrSkyRC/ETHOS-Feedback-Community#4447]
There was some change in text files ("markup") in X12S radios. Now when you type in one line:

One two three

The output on display will be:

One
two
three

So the spacers are working like newline characters. The texts are not readable anymore:
![horus123](https://github.com/user-attachments/assets/fba76ae5-31cc-4dd2-8517-779e17f03a11)

Any idea how to fix it? Thank you very much in advance!

**Comment by bsongis-frsky** [comment]
At least on X20 it is good:

![image](https://github.com/user-attachments/assets/db393708-9bfd-4382-a71e-1315c048157e)

**Comment by bsongis-frsky** [comment]
Text viewer seems good on X10 Express

![image](https://github.com/user-attachments/assets/63e4f299-2ba3-4800-811e-a3deed337a96)

But checklist with TXT files is not good

![image](https://github.com/user-attachments/assets/d701f0da-2763-4ad9-a70a-f8f935ffd9e2)

**Comment by bsongis-frsky** [comment]
The same on X20S

![image](https://github.com/user-attachments/assets/db81aaf1-67ed-4f5c-9127-d91eaa461186)

**Comment by bsongis-frsky** [comment]
Fixed

![image](https://github.com/user-attachments/assets/30fb65ac-e4e9-4e28-a551-3b3bc5f3b3cb)
