### ISSUE TITLE
Updated Norwegian Translation/Audio

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#4449]
Have just done some "polishing" of the Norwegian Audio Translation file  :-)

[no.csv](https://github.com/user-attachments/files/16778130/no.csv)

**Comment by bsongis-frsky** [comment]
I have just added you as collaborator for this repository, so that you may open the Pull request directly (as Janek just did for CS), it's far easier to check the changes (you and me!)

**Comment by bsongis-frsky** [comment]
What do you use to generate the prompts?

**Comment by mmasch** [comment]
I am sorry Bertrand, but I do not understand what you are asking for. 
I have just made some minor adjustments in the Norwegian translation file. 
If you are wondering wich program I have used, it is Notepad on PC.

**Comment by bsongis-frsky** [comment]
No. I meant to generate the audio files from the CSV

**Comment by mmasch** [comment]
It is you guys that have previously generated the wav files. 
I have only translated the csv text-file  ;-)

**Comment by bsongis-frsky** [comment]
I think I did it long time ago then! Do you know which is the voice which has been used? Something like "fr-FR-Neural2-A" for FR

**Comment by bsongis-frsky** [comment]
Here is the page where you can choose a voice:
https://cloud.google.com/text-to-speech

**Comment by mmasch** [comment]
Will have a look at this over the weekend.

**Comment by mmasch** [comment]
Hi Bertrand. 
In https://cloud.google.com/text-to-speech, it looks like previously used voice is:
Language: Norsk Bokmål (Norge)
Voice type: Basic
Voice name: nb-NO-Standard-E

**Comment by bsongis-frsky** [comment]
The audio pack will be ready in the next nightlies
