### ISSUE TITLE
Ethos Suite doesn’t load correct firmware

### ISSUE THREAD

**Issue by RobinS49** [FrSkyRC/ETHOS-Feedback-Community#4450]
I bought a Tandem XE tx and upgraded it to a Tandem XE-S. I can successfully upgrade the firmware if I download the firmware to a local folder but using Ethos Suite’s automatic upgrade tool it always installs XE firmware and not XE-S.

**Comment by mawzthefinn** [comment]
Did you install the XE-S Bootloader manually? If you haven't, you have not completed the XE to XE-S upgrade and Suite will detect your radio as a regular XE.

**Comment by RobinS49** [comment]
I installed the firmware manually after downloading it from the GitHub resources (XES-EU.zip), is the Bootloader found separately?

**Comment by RobinS49** [comment]
When I connect the Tx to Ethos Suite it correctly identified the Tx as a XE-S it just installed the XE version when I did the update.

**Comment by mawzthefinn** [comment]
If it detects as an XE-S, then you have the correct Bootloader and it is indeed a Suite issue.

**Comment by Nicholas-Luoyi** [comment]
If you bought a XE then it is not recommended to flash a XE-S firmware.

**Comment by mgsanna** [comment]
> I installed the firmware manually after downloading it from the GitHub resources (XES-EU.zip), is the Bootloader found separately?

yes you need to flash boot loader the first time manually as per firmware, lack of this op ethos suite recognize normal XE radio instead of XE S (upgraded), you will find it for sure on ethos 1.4.15 release
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.4.15/XES_BOOTLOADER.zip

**Comment by mgsanna** [comment]
> If you bought a XE then it is not recommended to flash a XE-S firmware.

but if he has upgraded all the parts, it's same thing of buying an XES, all the electronics are the same (XE-XES and so on)

**Comment by RobinS49** [comment]
I bought XE because I don’t know there was an XE-S at the time, I then bought the audio module to convert it to a XE-S through T9 and followed their instructions. It shows up as a XE-S when I go into Ethos Suite but then loads XE firmware unless I do a manual upgrade.RobinSent from my iPhoneOn 29 Aug 2024, at 08:19, Marco Gualtiero Sanna ***@***.***> wrote:﻿ If you bought a XE then it is not recommended to flash a XE-S firmware. but if he has upgraded all the parts, it's same thing of buying an XES, all the electronics are the same (XE-XES and so on) —Rep 


If you bought a XE then it is not recommended to flash a XE-S firmware.

but if he has upgraded all the parts, it's same thing of buying an XES, all the electronics are the same (XE-XES and so on)
