### ISSUE TITLE
number/text field with no input actions

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4453]
![flags](https://github.com/user-attachments/assets/c3c40656-55ec-4b1f-8044-e727e54ff45c)

In some cases when doing a form - for example to display a status page...

It would be handy to be able to prevent the field from showing any controls to adjust the values; without the field having to be dimmed by disabling it.

maybe:  field:actons(false)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/5ede9cb5-9ff0-41b7-a67f-0ccb05d7ff33)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/5e6d42b9-0667-477c-999b-0c6e6547276a)

**Comment by bsongis-frsky** [comment]
`field:color()`  and `field:value()` added

**Comment by bsongis-frsky** [comment]
```lua
local field = form.addStaticText(line, nil, "-")
field:color(RED)
field:value("...")
```
