### ISSUE TITLE
EthOS 1.5.15 - DSM2 RPM Sensor corrupted

### ISSUE THREAD

**Issue by jbeard6** [FrSkyRC/ETHOS-Feedback-Community#4455]
I updated my X18 from 1.5.13 to 1.5.15. Prior to flashing, the selected model on the radio was a helicopter that had a Flight Mode mix. After flashing and ejecting the radio, I received an Invalid Data error and it loaded the create model wizard. Selecting another model and then returning to the models list had a "New Model" entry but the original helicopter model was not present.

I had a backup and restored the models from it. I had a different helicopter model selected (no Flight Mode mix defined) and that model stayed fine, but, when I went to select the restored helicopter model that had the Flight Mode mix, I once again received the Invalid Data error and the create model wizard.

I'm currently rebuilding this model from scratch. 😬 I haven't decided whether to try the new "Bank" mix or just leave it as a Free Mix.

Edited to add: I'm not sure it's the presence of the Flight Mode mix that triggered this, but it's notable because one helicopter model with it had the bug and one helicopter model without it did not have the bug and there was already a known issue with this changed feature between these two versions.

**Comment by bsongis-frsky** [comment]
This is not normal. I don't see any good reason, we have just renamed the FlightMode mix ...
Would you please attach your model that you cannot open anymore so that I can check if there is something else?

**Comment by jbeard6** [comment]
Here's the model in question. This is from immediately after the upgrade (before ejecting the TX from Ethos Suite) so it should be in exactly the state that the upgrade left it.
[fusion 180.bin.zip](https://github.com/user-attachments/files/16798475/fusion.180.bin.zip)

**Comment by jbeard6** [comment]
I thought of one other difference between the two helicopter models: the corrupted one is using a multi protocol module while the other is using an ACCESS receiver. Is it possibly something to do with that?

**Comment by doppleganger53** [comment]
> I thought of one other difference between the two helicopter models: the corrupted one is using a multi protocol module while the other is using an ACCESS receiver. Is it possibly something to do with that?

Yes! The problem is not helicopters, its any model using multi module and spektrum protocol. When I upgrade to .14 or .15 all of my spektrum multimodule models come up as invalid data (I've reverted to .13 and restored from backup and all work again).

Multimodule models using other protocols seem to be unaffected. 

@bsongis-frsky

**Comment by bsongis-frsky** [comment]
The issue comes from the DSM2 RPM sensor. It is now possible to configure it like FrSky sensors.

![image](https://github.com/user-attachments/assets/b85e3932-2ddc-4968-9f84-e44f6424b07b)
