### ISSUE TITLE
French translation " inverted Channel"

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4459]
![screenshot-2024-08-29-39613](https://github.com/user-attachments/assets/80ad01cb-bedd-4e93-bef5-063c0de74352)
No French translation for inverted channel (Voie inversée) The translation in the i18n/fr.csv file is correct. I don't understand.

**Comment by bsongis-frsky** [comment]
The translation was not used, the string was hardcoded in code
