### ISSUE TITLE
Devs. Please stop closeing issues so fast!

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#446]
It is noticeable that issues have been closed very quickly lately because the developers think it is not an issue. or whether it will be fixed one day. or that it should just work.

issues should only be closed if users report that it actually works. Until then, issues should just stay open.

If issues are closed every time, people with the same problem will no longer find these issues. and they start the same issues every time.
This makes it very difficult to track bugs.

Only close if something is actually solved.
That something works for a dev, but not for a user (customer). doesn't mean it works! (properly)

Anyways, the Devs do a tremendous job at fixing bugs on the fly, And adding new stuff in this great system. 👍

**Comment by bsongis-frsky** [comment]
No. A bug is marked as fixed:
- if it is fixed, and you have the milestone filled
- if it is not considered as a bug
