### ISSUE TITLE
Lua Task Scheduling

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4460]
Recently I have been working on stuff that is pushing the cpu of the radio hard.

What jumped out is that if running allot of widgets - things get bogged down.  I notice this partiually on my RF2ETHOS system tool where MSP data starts to fail because the cpu is too busy.

I wonder if there is value in adding a flag to a widget initialisation

    system.registerWidget({
    key = config.widgetKey, 
    name = config.widgetName, 
    create = create, 
    paint = paint, 
    wakeup = wakeup, 
    persistent = false
    **background = true|false,
    priority = <1|2|3|4|etc>**
    })

    **background = true|false,
    priority = <1|2|3|4|etc>**

Essentially.. if background=true, then the script runs in the background.  If set to false.. it is 'paused' when in background/not visible;   and of course the priority just acts like a unix cgroups scheduler

**Comment by bsongis-frsky** [comment]
The CRSF will have multiple listeners and a bigger queue to fix this problem
