### ISSUE TITLE
Error telemetry temperature sensor Neuron II 80 with RX SR6

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#4462]
In version 1.5.15 the temperature sensor of the NEURON II 80 speed controller has stopped working via telemetry. I have it in two planes and the same thing happens in both, all the telemetry data works except the temperature sensor.
In version 1.5.13 and earlier it worked correctly, in 1.5.14 I did not get to test it and I do not know if it works.

![Neuron II 80](https://github.com/user-attachments/assets/7af64aab-5775-40ad-8fd5-6452ab398e04)

**Comment by afdofdez** [comment]
I have verified that with the X10S transmitter with OpenTx it works correctly and sends the temperature via telemetry.

**Comment by afdofdez** [comment]
Solved, deleting the sensors and searching again, they all appear.
I had to reconfigure all the widgets but IT WORKS NOW.

**Comment by bsongis-frsky** [comment]
:)
