### ISSUE TITLE
Why can I make local variable in create() ???

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4463]
Is it because the create function is already LOCAL?

local function create()
 	local bg = "hello world"
end

local function paint(widget)
	lcd.drawText(0,0,bg)	
end

local function wakeupnow(widget)
	lcd.invalidate()
end

local function init()
	system.registerWidget({key="noam1", name="noam1", create=create, paint=paint, wakeup=wakeupnow, title = false})
end

return {init=init}

**Comment by bsongis-frsky** [comment]
if `bg` is local to `create()` it cannot be used in `paint()`!
