### ISSUE TITLE
Corrupt Update

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#4466]
The latest release 1.5.15 is now doing this. The last few updates all have some sort of bug in them. Are new releases tested prior release to the public?

https://github.com/user-attachments/assets/53207220-12bc-4871-87f0-6fd87912fede

**Comment by robthomson** [comment]
What exactly are you doing / seeing.

Your video does not really give any context.

Small point.   Posting narky comments generally does not get you good support.   Posting clear descriptions of the issue, with an offer to test and help solve the issue.   Well that generally gets you a much more favourable response.

Kind of a life lesson :)

**Comment by 4qr1hu9n7** [comment]
Never mind. Clearly, I'm not allowed to post issues that I come across! Take a closer look at the 900 MHz telemetry values.  Don't need to be lectured by you. And yes. Performing a field trial would be wise to make sure the new revision does not upset the previous one.

**Comment by 4qr1hu9n7** [comment]
You're the expert !!

**Comment by bsongis-frsky** [comment]
Issue or not issue? It's strange that it is linked to Ethos, perhaps an RF module update?

**Comment by robthomson** [comment]
Agree.  This feels far more likely to be an issue on the rf module side of things.

Ethos simply takes a reading from the rf module.


Have you recently upgraded the firmware on your rf module?  I know there where some new updates for that in the past few weeks.

**Comment by 4qr1hu9n7** [comment]
Everything is currently updated. This problem has shown up on "all" of my programed models. Never seen this before. Screen shot of my X20-PRO as of August 31 2024
![20240831_070721](https://github.com/user-attachments/assets/e68dfc14-a1e1-495e-808f-4e859668e327)

**Comment by 4qr1hu9n7** [comment]
I have now reverted the internal r.f. module back to 1.1.13. 900 MHz telemetry has now been restored.

**Comment by loetefix** [comment]
So its not an Ethos issue.....

**Comment by 4qr1hu9n7** [comment]
No, it is not.

**Comment by bsongis** [comment]
> Are new releases tested prior release to the public?

Thanks a lot for this sort of comments, it's very much appreciated!

**Comment by 4qr1hu9n7** [comment]
You are welcome. I would hope that future releases will not be worse than the version it is replacing.
