### ISSUE TITLE
ESC rpm sensor faulty

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4469]
Hello,
After searching the telemetry sensors again, I realised that the speed sensor is faulty. One line is missing and so the number of poles cannot be set.
Ethos 1.5.14 Horus X10S Express
Greetings 
Wolfgang
![Fehler Drehzahlsensor](https://github.com/user-attachments/assets/98195152-e1ec-41b3-b792-3db04f5223e8)

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/c75a89bc-267c-440d-ad50-fe2a47ba5e48)
