### ISSUE TITLE
Vario not work right

### ISSUE THREAD

**Issue by Boxxxer64** [FrSkyRC/ETHOS-Feedback-Community#447]
Vario tone for climb, beep and sink a continuous tone does not work. Altitude hold keep still not work.
X12s with Ethos 1.09.2

**Comment by bsongis-frsky** [comment]
Would you be more precise? I have tested myself and I have received good feedback with 1.0.9 candidate 2

What do you mean by "Altitude hold keep"?

**Comment by Boxxxer64** [comment]
If the altitude is maintained, it should be quiet. when rising beep with increasing tone. when sinking continuously and getting deeper.

iuse 1.0.9-2 on my x12s

**Comment by bsongis-frsky** [comment]
Did you change the vario settings so that it is quiet when not rising / falling?

**Comment by Boxxxer64** [comment]
I tried but it didn't work. Do I have to delete the sensor and search again?

**Comment by bsongis-frsky** [comment]
no, just change its config

**Comment by bsongis-frsky** [comment]
Center => Silent

**Comment by bsongis-frsky** [comment]
Which is you sensor?

**Comment by Boxxxer64** [comment]
ok, i will test later again. Now working Time!

**Comment by Boxxxer64** [comment]
if you look or look at Frsky-forum.de, the Vario does not work satisfactorily for anyone. I also ask again. Maybe I am expressing myself incorrectly too!

**Comment by Boxxxer64** [comment]
GR8 and Gr6

**Comment by Hobby4life** [comment]
Same as #414 ?

Look at videos

**Comment by bsongis-frsky** [comment]
GR8 and GR6 have both been tested. I see no issue. Feel free to reopen #414 if needed

**Comment by bsongis-frsky** [comment]
Did you check with the latest 1.0.9 candidate 3?

**Comment by NorbertHeli** [comment]
No only 1.0.9 RC2 but I try now

**Comment by Boxxxer64** [comment]
With me the hammer sound is also when sinking. With the center noiseless I have now got there.

**Comment by Hobby4life** [comment]
Can confirm, the stuttering/hammering noise when sinking

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.9 candidate 4

**Comment by NorbertHeli** [comment]
Vario sinking tone is now ok thank you

**Comment by Boxxxer64** [comment]
Working good. Thanks

**Comment by i3dm** [comment]
guys.
i just tried GR8 on X20 V1.0.9 and even w
![Uploading 20210708_215214.jpg…]()
ith sensors discovered - variometer menus are all grayed out.

any ideas how to setup the vario?

**Comment by i3dm** [comment]
![Uploading 20210708_215214.jpg…]()
