### ISSUE TITLE
Lua script location on SD

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#4470]
On GitHub the location of the scripts have changed by moving them to different folders like 'modules'  and 'examples'
Is this also the way they should be put on the SD ?

**Comment by Alex00101** [comment]
All scripts are must be in the scripts folder on the radio.

**Comment by ahvink** [comment]
I thought so, thought they were changing that..
Just making sure.

**Comment by bsongis-frsky** [comment]
Nothing changed on radio! The repository has so many scripts that it starts to need to be sorted a little bit!
