### ISSUE TITLE
Sequencer

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#4471]
Request (Have a internal retract and door sequencer added ).

**Comment by hrenz** [comment]
its very simple to programm one yourself 
with 2-3 mixer and 2-3 log switches
for doors and gears

**Comment by Dsrenger** [comment]
I do it with a time base as described by Mike 
https://rc-soar.com/ethos/code/sequencer/

So, you have everything you need for a gear sequencer

**Comment by mawzthefinn** [comment]
You can do a full single-channel sequencer in a Free Mix in 1.5 now, just by putting a Slow Action before a Curve action (slow sets the speed, Curve is the sequencer). Use the source switch to select between two curves. Multi-channel output is supported, but not per-output channel curves (so the gear doors need to be a second mix from the gear legs)

Or you can use Mike Shellim's method for more power.

**Comment by bsongis-frsky** [comment]
It is possible to do everything, but the "Sequencer" mix will help a lot. It's already in the roadmap!

**Comment by bsongis-frsky** [comment]
Duplicate of #657

**Comment by MikePhillyFlyers** [comment]
Just wanted to add another FYI, (in case you weren't already aware), Graupner MZ radios have a sequencer, I'd say their design can seem a bit clunky, but it does the job!  if anything, this gives you a look a how someone else did it :)

**https://www.youtube.com/watch?v=m-BFHvClkHM**

**https://www.youtube.com/watch?v=qTZYSHtEn14**
