### ISSUE TITLE
Predefined mix Thr To Ele almost unusable - uses Thr source as input, instead of Thr channel (output)

### ISSUE THREAD

**Issue by IJK-CZ** [FrSkyRC/ETHOS-Feedback-Community#448]
All mixes, based on Throttle **must use throttle output** (i.e. CH3), **not Throttle input** as source (input) value. It has many good reasons, and FrOs as well as OpenTx allows it very simple. Using Analog gimbal position without relation to Throttle Hold is absolutelly stupid. It is similar as already reported problems related to Thr% timer control.
Only if Throttle **output** has significant values, may be important impact to Elevator, Rudder or Timer #98

**Comment by Hobby4life** [comment]
That makes no sense if you are using specific throttle curves.. the ELE output or others would be really weird.
Better would be a stage between the throttle input and mixer.

**Comment by IJK-CZ** [comment]
This setting from OpenTX is missing. You can specifi, which value can be used as'logical Throttle' and then it use for timers, mixes etc.
![Thr_Setup](https://user-images.githubusercontent.com/44742963/121500221-66d3a080-c9de-11eb-97c4-dd7b2de12c9c.jpg)

**Comment by IJK-CZ** [comment]
There is a workaround using additional free mix (manually defined before standard trrottle mix) and using additional unused channel, i.e. CH16. 
1) You need to define a free mix, with source Throttle stick and output to CH16. For this channel need to be manually defined and applied all throttle functionality (curves, blocation etc). 
2) In standard Throttle mix change source to the used temporery channel (CH16 in this example).
It is not very user friendly and simple, but working.
