### ISSUE TITLE
LUA: read model id

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4481]
Hello,
i want to read the model ID:
![image](https://github.com/user-attachments/assets/b7795c2a-b5bd-4699-9be5-63b08efd0c7e)

if i use print(model.id()) i get:
table: 0b6416f0
table: 0b641880
table: 0b6418f8
table: 0b6418d0
table: 0b641920
table: 0b641498
table: 0b641808
table: 0b641920
table: 0b641588
table: 0b641600

how can i actually read the model ID (i.e the number of the model memory)? i need it to see if a model memory was changed when my lua is running.
thanks.

**Comment by Alex00101** [comment]
From the documentation:

model::id() 	
Get the model ids (internal and external modules)
Returns
    ids (**table of integers**) 

Example:

local ids = model.id()
print("Internal Id", ids[1], "External Id",  ids[2])

**Comment by i3dm** [comment]
Thank you. 
If there a way to tell the model memory ID and not the RF module ID? 

My purpose is to know if the user switched model memories.

RF module ID is not necessarily unique so won't work.

**Comment by Alex00101** [comment]
Not sure what switched model memories is. If I need to know if someone switched the model, model filename model.path() is unique but it'll also be changed if you rename the current model.

**Comment by i3dm** [comment]
So model path id[1] is surely unique?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alex00101** [comment]
path() gives you the filename with as far as I remember folder name so it's unique.

**Comment by i3dm** [comment]
There can not be 2 files with same name?

**Comment by Alex00101** [comment]
Not in the same folder. Even if you clone the model Ethos add 1 to the filename

**Comment by i3dm** [comment]
Thank you. Closing the issue

**Comment by bsongis** [comment]
Thanks @Alex00101!

**Comment by Alex00101** [comment]
> Thanks @Alex00101!

My pleasure.
