### ISSUE TITLE
Would like to write from widget to calculated sensor...

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4484]
Sort of a feature request since it's not working now.
Create a calculated sensor. Call it "Fuel Used"
I tried source as "---"
I also tried "convert source to value"

In the lua I'm trying to assign a value to that calculated sensor.
system.getSource({name="Fuel Used"}):value(12345)

The end goal is to have my Fuel Used be part of the flight csv file.

The long way is to use a LUA source, but it would be nice if we can just feed a value directly to the calculated sensor. A big shortcut :)

Thank you!!!!

**Comment by strgaltdel** [comment]
i guess it was expained in your last issue:

NEVER EVER declare a source and read/write values in one call

declaration of a source is a "one time task" in a script, could be done in create handler

your request is already functional

in case you have created a diy sensor and declared a source in your script (like "sensor"), this will set the value  (tested in a task script):

```
local function taskWakeup()
  sValue = sValue+1
  sensor:value(sValue)
  print("SensorVal",sensor:value())
end
```

**Comment by strgaltdel** [comment]
... as announced, the "basics of sources" will be covered in the next chapter of my lua tutorial

**Comment by noamkrief** [comment]
@strgaltdel 
please listen,

1) thank you for your tutorial. I have read it before, and it's very nice you make it available (in english too). Very great of you!!!

2) I NEVER EVER do them together. I getource only once. You've told me about this before :) and THANK YOU!!!!

3) the reason I put them together here is just to simplify the example for @bsongis-frsky 

4) if you read my original post carefully, you'll see it's about "Calculated Sensor" that I create and want to change the value of, not a DIY sensor.

**Comment by noamkrief** [comment]
@strgaltdel 
By the way! Doing it with a DYI sensor instead of Calculated Sensor works!!!!!!!!
Thanks so much! closing the ticket.
