### ISSUE TITLE
RX firmware GR6 and GR8, version not in Frsky Web site 

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#4485]
I bought a Archer GR6 Plus  and Archer GR8 Plus receiver, as usual I checked the version in the RX if is updated at last version. This time the  GR6 and GR8 have a version 1.0.11 that is NOT released  in the formal Frsky web site. How is it possible? ONY the SR6 and SR8 have a version 1.0.11... Could be a mistake? Could update both to 1.0.10 or a leave on 1.0.11? please help

![20240906_105345](https://github.com/user-attachments/assets/2fead9ee-8879-44d4-8341-73088d56898f)
![20240906_105436](https://github.com/user-attachments/assets/08c8cb06-c479-48e8-9859-00801af3cf22)

**Comment by mawzthefinn** [comment]
This happens sometimes. There's an internal standard build for production, but if that specific receiver model has no changes from the previous build version the newer version isn't posted.

We saw this with TD ISRM 2.2.4, which added support for newer radios, and shipped on X20/X20S radios, but was not released to users for the X20/X20S as there were no changes for that hardware.

**Comment by fdapport** [comment]
Thanks,
