### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4487]
X20pro latest version

https://www.youtube.com/shorts/kpNzsYZ2DeE

PS - sorry about the quality. It is forcing to upload to youtube shorts and the quality sucks!!!

**Comment by bsongis-frsky** [comment]
I see nothing sorry, would you please explain or make screenshots from Ethos? Or do it with the simulator?

**Comment by noamkrief** [comment]
@bsongis-frsky 
I click on the right side of the wheel, and it moves the cursor to the right. This is correct.
I click on the left side of the wheel, and it's still moving the cursor to the right. It needs to move the cursor to the LEFT.

I can see it clearly in the video I made.

**Comment by bsongis-frsky** [comment]
But there is only one button on the wheel, which we call [Enter]. Do you mean [DISP] and [SYS]?

**Comment by noamkrief** [comment]
@bsongis-frsky I'm so sorry. I feel like an idiot. The right side doesn't have multiple button presses.
I can scroll left and right with the left one "DISP" and "SYS"

Sorry about that. Closing.
