### ISSUE TITLE
1.5.15 SF Function Simulator Crash - X20PRO Emergeny Mode

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4488]
Example: All 8 screens are configured.

![8 Fenster](https://github.com/user-attachments/assets/927726c1-f568-4ce2-a0e7-e3f54619a43b)

An SF function open screen 8 is set up.

![SF Anfang](https://github.com/user-attachments/assets/2ecd79c1-08dd-4262-aae6-75bf613b366d)

A screen smaller than 8 is deleted.

![7 Fenster - 1 Fenster gelöscht](https://github.com/user-attachments/assets/10309c2b-92ea-419c-968d-13671237893b)

Function when flying is correct!

The special function is reactivated for editing.

![SF Aufruf nach gelöscht](https://github.com/user-attachments/assets/73c7dfcf-33d2-44c5-acf0-60dcfb375a52)

Simulator: Crash

X20PRO: Emergeny Mode
or if no Emergeny Mode then only confused characters in the line Screen.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Fixed in next nightlies
