### ISSUE TITLE
Suite 1.5.10 Crash Windows 11

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4489]
When the Download Center is opened:

Modules / ACCST 2.4G Modules / XHT or / XJT

Suite CRASH.

![suite](https://github.com/user-attachments/assets/f698b7a5-95c0-4a37-a9be-17fa31991be6)

/ XJT_Lite is ok.

Windows 11 Notebook

Greetings Eugen

**Comment by Wolepo** [comment]
I can confirm that. It only occurs here
Win11 Hom 64

**Comment by Satcomix** [comment]
The Win11 Pro 23H2 suite version 1.5.10 doesn't crash for me, only the Download Center have a crash.
No firmware versions appear for XHT and XJT, only for XJT_LITE, which are then also displayed for XHT or XJT.
After that you can`t leave the Download Center. By enetring Ethos or Model manager there are no problems anymore.
regards,
Torsten

**Comment by yak55** [comment]
It´s my Notebook crashing.
Greetings Eugen

![PC](https://github.com/user-attachments/assets/40cbeb51-1fc9-4433-b626-89a7ba682b48)

**Comment by Nicholas-Luoyi** [comment]
Would you please provide some crash logs in the log folder?

**Comment by Nicholas-Luoyi** [comment]
Will I have it as well. No need for the crash log now.

**Comment by Nicholas-Luoyi** [comment]
Fixed! And a new installation will be uploaded
