### ISSUE TITLE
Trim mix improvement

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#449]
If you choose custom Trim mode in a Trim-Mixer the maximum is 10 (1%) per step. the "normal" trims have a max range of 32(3,2%) per step.Please expand it to 32 in Trim-Mixer.

Further the original trims can set to Independent  Trim per Flifghtmode.thats missing on trim mixer.

And by editing a trim mixer, the curve on the right dont show the actual position.

**Comment by bsongis-frsky** [comment]
Merged into #577
