### ISSUE TITLE
Ethos Suite 1.5.9 won´t detect my FrSky X20s (Windows 11)

### ISSUE THREAD

**Issue by nivaldin** [FrSkyRC/ETHOS-Feedback-Community#4490]
![Captura de tela 2024-09-07 103534](https://github.com/user-attachments/assets/b964a37d-10c4-4d04-baf2-c5139e3c178e)

**Comment by mawzthefinn** [comment]
You have a usb driver issue of some sort according to Device Manager. Fix the yellow flag there and Suite will work

**Comment by Nicholas-Luoyi** [comment]
And please try with the latest version of Suite

**Comment by nivaldin** [comment]
I just bought a new cable and figured out the problem... thank you guys!
