### ISSUE TITLE
Trim behavior - centre weight

### ISSUE THREAD

**Issue by Zadrob** [FrSkyRC/ETHOS-Feedback-Community#4495]
Hello, I would really appreciate different trim behavior (or posibility to change it). Normally trim behaves lineary - when you add 20% trim, you have 0 point 20% moved, and also minimal and maximal. So when you have very high trim on fligh mode (like elevator for landing flaps) you can have -40% trim, than instead of mix outpur range -100 .. +100  you have -140 ... +60 - you have 40% lower stick dead and you miss 40% of pull on. So I thing that "centre weighted trim" coul be usefull. So you basically shift middle point of curve, but not moving end points. Of course i can have 3 point curve with central point value-based, but then I miss expo, or I must use another mix for that...

**Comment by mawzthefinn** [comment]
You can readily do this with a Free Mix.

You will want a Trim curve, with the centre point set from the trim function in question. That should be the first Action in the Free Mix stack

Then you have a second curve action further down to set expo.

**Comment by Zadrob** [comment]
Hello, thank you for suggestion. 
It works, but I have to use another channel or Variable. I cannot use trim value as direct value for setting of curve point - I can use analog, channel, or Var, not Trim directly. So I can use Var, which uses Trim value. 
Is that correct or do I miss something? 
thank you 
Karel

**Comment by mawzthefinn** [comment]
You're right, you will need to proxy via a VAR right now.

**Comment by mawzthefinn** [comment]
Fixed in 1.5.16 as Trims are now assignable directly as curve adjusters.
