### ISSUE TITLE
Major failsafe bug in TD receivers found

### ISSUE THREAD

**Issue by cje0114** [FrSkyRC/ETHOS-Feedback-Community#4496]
I believe I might have found a major bug in tandem receivers.…I can replicate the issue every time with tdr12, stabilized tdr12, and a tdr10.…all of my regular accst and access 2.4 rx’s are fine.

Here’s what’s going on:

I set the failsafe setting to custom and set all my channels. I test by leaving the rx on and powering off my x20s tx. Failsafe works as it should. I can power on the tx and test again and it still works as it should. Power down the tx and rx, power on, test again and the surfaces hold position and won’t go to where I have them set to in the custom settings.

If I go to the failsafe settings and exit out again the failsafe works as it should until the power to the rx is turned off and back on again.

I’ve tried different firmware on the rx’s and the internal module in my tx with the same result every time.

This could be a major problem and I ask that other people check their failsafe and report back.

Hopefully a fix can be had quickly for this.

**Comment by podpadstudios** [comment]
Agreed, I have found the same issue with all my transmitters, Tandem XE and X20S, receievers TDR18, 12, 10 and 6. I am running all the latest firmware and software updates.

**Comment by mawzthefinn** [comment]
How long are you waiting before testing failsafe after the link comes up?

This is definitely concerning, but you should always let the link sit for at least 30s before testing failsafe due to how failsafe settings are sent to the receiver (every 15s or so). 

(note this is just about getting useful test information, to determine if it's the failsafe behaviour that's an issue, or the failsafe settings update behaviour that's an issue)

**Comment by cje0114** [comment]
> How long are you waiting before testing failsafe after the link comes up?
> 
> This is definitely concerning, but you should always let the link sit for at least 30s before testing failsafe due to how failsafe settings are sent to the receiver (every 15s or so).
> 
> (note this is just about getting useful test information, to determine if it's the failsafe behaviour that's an issue, or the failsafe settings update behaviour that's an issue)

It doesn’t matter how long I wait. I’ve tried it numerous times from not waiting to waiting up to a few minutes with the same results every time.

**Comment by bsongis-frsky** [comment]
> Power down the tx and rx, power on

What is the real use case?
Remember that the TX will send the failsafe positions every ~10 seconds.

**Comment by pstasek** [comment]
I think the main concern here is, that when you accidentally switch on a receiver with the transmitter being off, it can overstress servos or linkages that are sharing a single surface, typically 2 servos per aileron or rudder.

**Comment by RealTadango** [comment]
> I think the main concern here is, that when you accidentally switch on a receiver with the transmitter being off, it can overstress servos or linkages that are sharing a single surface, typically 2 servos per aileron or rudder.

That should not happen because when the RX is powered without a valid signal it will hold pulses until a connection has been established. The RX never drives the servo's without a TX connection, as it should. Using failsafe settings for power up positions is VERY dangerous and should never be an option.

**Comment by RealTadango** [comment]
> I think the main concern here is, that when you accidentally switch on a receiver with the transmitter being off, it can overstress servos or linkages that are sharing a single surface, typically 2 servos per aileron or rudder.

That should not happen because when the RX is powered without a valid signal it will hold pulses until a connection has been established. The RX never drives the servo's without a TX connection, as it should. Using failsafe settings for power up positions is VERY dangerous and should never be an option.

**Comment by mgsanna** [comment]
> > I think the main concern here is, that when you accidentally switch on a receiver with the transmitter being off, it can overstress servos or linkages that are sharing a single surface, typically 2 servos per aileron or rudder.
> 
> That should not happen because when the RX is powered without a valid signal it will hold pulses until a connection has been established. The RX never drives the servo's without a TX connection, as it should. Using failsafe settings for power up positions is VERY dangerous and should never be an option.

Totally agree with you!!!! It’s very dangerous !!!

**Comment by bsongis-frsky** [comment]
Indeed. The RX should never go to failsafe on power on if no TX is found!

@cje0114 has perhaps a better real use case in mind? Why is it written "major failsafe bug"?

**Comment by FireflyJar** [comment]
confirmed here as well,  x18s on fw 1.5.9, TDR10,   plane was on for at least 2 minutes, when I turn off the TX the rudder did not go to neutral as what the RX custom fail safe is set to.

-Cindy Whritenour

**Comment by bsongis-frsky** [comment]
@FireflyJar what do you confirm? Do you also shutdown the TX to test the RX failsafe? It doesn't make any sense to me!

**Comment by cje0114** [comment]
> Indeed. The RX should never go to failsafe on power on if no TX is found!
> 
> @cje0114 has perhaps a better real use case in mind? Why is it written "major failsafe bug"?

Where did I ever say it goes to failsafe on power on?? I initiate a failsafe situation and it doesn’t go to my custom setting but rather holds positions.

**Comment by bsongis-frsky** [comment]
You quote the answer I did to pstatek. We are searching for a real scenario where there is a problem and he did try to explain one!

**Comment by cje0114** [comment]
> I think the main concern here is, that when you accidentally switch on a receiver with the transmitter being off, it can overstress servos or linkages that are sharing a single surface, typically 2 servos per aileron or rudder.

That has nothing to do with topic I posted here. Did you read my post?

**Comment by bsongis-frsky** [comment]
Again the TX sends the failsafe positions every ~10 seconds. Your TX and RX have to be ON during at least this duration so that the RX can remember those positions.

Now if you don't wait those ~10 seconds, please explain the scenario which you are trying to test!

**Comment by FireflyJar** [comment]
> @FireflyJar what do you confirm? Do you also shutdown the TX to test the RX failsafe? It doesn't make any sense to me!

same as original poster,  I will edit my post.

**Comment by cje0114** [comment]
> Again the TX sends the failsafe positions every ~10 seconds. Your TX and RX have to be ON during at least this duration so that the RX can remember those positions.
> 
> Now if you don't wait those ~10 seconds, please explain the scenario which you are trying to test!

I waited well over 10 seconds before trying to test failsafe…up to 5 minutes in some cases and it still didn’t work correctly. I have since reflashed the rx and can get it to work now but in some cases it can take up to two minutes or more before failsaif works. To me that’s still unacceptable since I’m not going to be sure if it works at all before flying.

**Comment by bsongis-frsky** [comment]
In the original post, I miss some information. You say you wait up to 5 minutes, but 5 minutes with TX + RX ON (then yes it makes plenty of time and FS should be sent!), or the TX / RX have a very short time ON (no time to sync the FS) and then you shutdown the TX to test the FS during 5+ minutes (you may wait as much time as you want, the RX doesn't have the FS positions!)

This is also the question from @mawzthefinn above. I think the information of how much time the TX / RX are ON before your tests is very important to see if we have a bug or not!

**Comment by ETHOSWarrier** [comment]
Well i have just tested a TD R6 in my plane.Tx is x20S on EU lbt ETHOS 1.5.13 Rx has latest TD R6 firmware....everything works as it should for info.I counted 15 seconds with the tx and rx on ,then switched off the tx....failsafe kicks in and throttle goes to idle...all good.

One observation i would add is are people actually setting the failsafe correctly.we have had a few ,new to frsky/ethos members  actually think they have set the failsafe  position but when checked they have not hit the shield button with the stick at idle say to set both bars displayed correctly.as the mixer bar sometimes makes it look like the failsafe is set, when it actually isnt ...just a thought ..EW

**Comment by cje0114** [comment]
> In the original post, I miss some information. You say you wait up to 5 minutes, but 5 minutes with TX + RX ON (then yes it makes plenty of time and FS should be sent!), or the TX / RX have a very short time ON (no time to sync the FS) and then you shutdown the TX to test the FS during 5+ minutes (you may wait as much time as you want, the RX doesn't have the FS positions!)
> 
> This is also the question from @mawzthefinn above. I think the information of how much time the TX / RX are ON before your tests is very important to see if we have a bug or not!

Yea I waited up to 5 minutes a couple times with both the tx and rx on and still didn’t have failsafe work. I have since reflashed the rx and it does appear to work now but in my testing there have been a couple instances where it took up to 2 minutes for it to read to the rx before I tested. It’s not very scientific testing on my part but there were a couple times I waited and it still didn’t work. I’m thinking maybe a possibility of rf noise in my neighborhood where I live could possibly be slowing down the time it takes for the tx to write the info to the rx when I power on? I’ll have to test at one of the club fields where I fly in the middle of a farm and see what happens.

**Comment by bsongis-frsky** [comment]
5 minutes with the TX and RX started and then when you shutdown the TX you have no failsafe? Then yes it would be a severe issue.

And you say that after flashing the RX to the previous version it works correctly. Only on TD-R12, "Stabilized TD-R12", and "TD-R10".

Am I correct? Would you please tell us which firmware on those receivers seems wrong to you, and which firmware seems good?

Then I will transfer the issue to the RF team ...

**Comment by pmullen503** [comment]
> >... It’s not very scientific testing on my part but there were a couple times I waited and it still didn’t work. I’m thinking maybe a possibility of rf noise in my neighborhood where I live could possibly be slowing down the time it takes for the tx to write the info to the rx when I power on? I’ll have to test at one of the club fields where I fly in the middle of a farm and see what happens.<<

I was able to recreate this in the shop with a TD SR6 (X20S, 1.5.9 firmware) pretty easily.  It looked like failsafe was more or less permanently disabled/corrupted.

But today at the field it was much harder.  The timing was more critical and If I later started my plane normally (power on TX, connect the battery, Wait several seconds and then shut off the TX to test failsafe) failsafe functioned normally.

This probably hasn't been noticed before because it requires a specific sequence of powering on or off TX and RX and may require a noisy RF environment to see the phenomenon.  It's interesting to be sure.  At the moment, it doesn't seem a danger in the real world.  The sequence and timing of the on/off TX and RX seems unlikely.

**Comment by bsongis-frsky** [comment]
I want to check if the FS are sent on first RSSI paquet received, then I am sure Ethos will do its best to transfer FS as soon as possible

**Comment by cje0114** [comment]
> > > ... It’s not very scientific testing on my part but there were a couple times I waited and it still didn’t work. I’m thinking maybe a possibility of rf noise in my neighborhood where I live could possibly be slowing down the time it takes for the tx to write the info to the rx when I power on? I’ll have to test at one of the club fields where I fly in the middle of a farm and see what happens.<<
> 
> I was able to recreate this in the shop with a TD SR6 (X20S, 1.5.9 firmware) pretty easily. It looked like failsafe was more or less permanently disabled/corrupted.
> 
> But today at the field it was much harder. The timing was more critical and If I later started my plane normally (power on TX, connect the battery, Wait several seconds and then shut off the TX to test failsafe) failsafe functioned normally.
> 
> This probably hasn't been noticed before because it requires a specific sequence of powering on or off TX and RX and may require a noisy RF environment to see the phenomenon. It's interesting to be sure. At the moment, it doesn't seem a danger in the real world. The sequence and timing of the on/off TX and RX seems unlikely.

Thanks for your update. That seems to back up my theory of slower sync time upon powering up in a noisy rf area. I’m going to try the same next time I get to the field.

**Comment by FireflyJar** [comment]
> I want to check if the FS are sent on first RSSI paquet received, then I am sure Ethos will do its best to transfer FS as soon as possible

I have not reflashed or reset FS on mine yet,  let me know what procedure or tests you need me to do to help with trouble shooting ,  plane is grounded for other issues for time being.

**Comment by FireflyJar** [comment]
I  just re-did the failsafe and tested it, did TX power off after 30 seconds and it worked,  so possible user error on initial setup,   I thought I did a running test on this, to make sure throttle goes off and not full,  ALWAYS  do actual test! (on ground).   maybe I need to take a step further and put a label on RX that it was done and not rely on my memory.

**Comment by Richrfl** [comment]
> 5 minutes with the TX and RX started and then when you shutdown the TX you have no failsafe? Then yes it would be a severe issue.
> 
> And you say that after flashing the RX to the previous version it works correctly. Only on TD-R12, "Stabilized TD-R12", and "TD-R10".
> 
> Am I correct? Would you please tell us which firmware on those receivers seems wrong to you, and which firmware seems good?
> 
> Then I will transfer the issue to the RF team ...

Bert, I will check my settings this weekend. I blindly trusted the failsafe would work. However, besides not making weird things with the power on/off of RX and TX, meaning, following the book for power on/off, 15 sec wait time, I have two questions: 1) is it correct to simulate a signal lost by powering off the TX? 2) after the transmitter's signal loss, how long does the RX take to enter failsafe mode?

**Comment by bsongis-frsky** [comment]
New firmware for receivers will store the FS internally, so that they will be used directly in case of RX reboot. The radio continues to send the new FS values every 10s.
