### ISSUE TITLE
Cannot update firmware to 1.5.15 for X-18 FCC

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4497]
I tried both Suite and Manual (from the Suite option) and I got this screen
![image](https://github.com/user-attachments/assets/db586bf3-3482-4203-93a4-d16eb71c675c)
Any suggestion?
My X-18 has a gyro installed. Should I try X-18S FCC?
Thank you

**Comment by strgaltdel** [comment]
enough free space on your tx volumes?

**Comment by Richrfl** [comment]
Good question. Will check it out and get back to you.

**Comment by Richrfl** [comment]
You hit the nail! for some unknown reason, there were folders with audio of 5 extra languages wav's that I don't care about.
Thank you.

**Comment by Richrfl** [comment]
You hit the nail! for some unknown reason, there were folders with audio of 5 extra languages wav's that I don't care about.
Thank you.
