### ISSUE TITLE
true debug on real radio - is it possible?

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4498]
When we run simulator.exe we see all sort of information in the cmd window.

like:
000568 MENUS task started
000568 loadDefaultFont()
000569 MIXER task started
000569 storageInit()
001725 Lua::loadBitmap('/scripts/..........*****.png')
001726 Create bitmap ... RAM used: 35848 bytes

Is there a way to get this on the real radio?
It seems the debug mode or putty serial is only going to display things we print()

Also, is there a way to get the same information on the radio as on simulator.exe instantly from boot up? Because lots of the boot up information especially for the widget is important for some troubleshooting.

Thank you

**Comment by bsongis-frsky** [comment]
No. The firmware is not delivered in DEBUG mode!
