### ISSUE TITLE
Fonction GAZ ne réagit pas dans le mode écolage côté élève

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#450]

**Comment by Mobidick1966** [comment]
Bonjour, 
 Ethos X20 1.0.9 (1.0.8 aussi)... FrSky Horus 12 OTX  dernière mise à jour

En mode écolage , la fonction des GAZ ne réagit pas sur le model via la radio élève .
Dans le graphique de la X20 ... tous les bar graph .bouge même celui des gaz. 

Normal ??? ou Pas ??? 

Bonne soirée ..

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.10
