### ISSUE TITLE
Curve adjustment points should allow all valid sources

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#4500]
Trim Functions are not currently assignable as a source for a curve point, but are one of the most useful potential curve adjusters

**Comment by pstasek** [comment]
Using Vars with repurposed trims is actually very powerfull.

**Comment by mawzthefinn** [comment]
> Using Vars with repurposed trims is actually very powerfull.

While 100% true, that doesn’t affect the request that trimmers be directly assignable. There’s several use cases where proxying a trim function via a var to a curve point is simply pointless complexity (such as using a 3-point curve with the centre point adjustable as a trimmer for a free mix, or implementing low position trim via an adjustable curve point)

**Comment by jasalca** [comment]
I don´t know if this is already implemented but it would be incredible if I have selected the same trim to adjust each point of the curve if I select automatic mode, it would be interesting if with the trim it only affects the point that is selected in the curve. Right now it affects all the points equally even if they are not selected.
In this way , depending on position of the stick the trim would correct ONLY the point affected to that position of the stick, thus correcting all the points of a curve individually.
[Ethos Simulator 2024-09-19 18-49-22.zip](https://github.com/user-attachments/files/17063879/Ethos.Simulator.2024-09-19.18-49-22.zip)

**Comment by spoke2570** [comment]
@jasalca The method for setting up the "crow aware trim" can handle that already by selecting non-overlapping ranges for the logic switches.
