### ISSUE TITLE
Receivers firmware under Download center in Ethos suite 1.5.9

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#4502]
Ethos Suite Version: 1.5.9
PC with Windows 10

In the download center I select Receivers, ACCESS 2.4G Series, GR6
I found  many versions of the GR6 firmware that are NOT in the Frsky download center of the GR6 receiver. See attached images

How it is possible? Is it correct? Can I update my receiver with this  firmware ?
Please let me know, Thanks, Franco

![Firmware003](https://github.com/user-attachments/assets/adec4f52-046a-48b2-8948-1263caea6183)
![Firmware002](https://github.com/user-attachments/assets/f18e182a-7cf2-41f9-be94-8207752c05d5)
![Firmware](https://github.com/user-attachments/assets/c46f9628-5d2c-48e8-a508-86f221e01798)

**Comment by mawzthefinn** [comment]
You're comparing the website listing for the Archer Plus GR6 to the Download Center listing for the Archer GR6. Those are two different receivers with two different sets of firmware available



![Screenshot 2024-09-09 at 1 10 43 PM](https://github.com/user-attachments/assets/7177b89f-d665-4a18-9113-76a440f41cac)

**Comment by pmullen503** [comment]
You have to be careful about the Archer series vs. Archer **Plus** series of receivers.  As stated, they are very different receivers.

**Comment by fdapport** [comment]
You are right!!!  thanks, I close the ticket then.
