### ISSUE TITLE
Unable to update X20Pro Ethos and Flash

### ISSUE THREAD

**Issue by itizmeunderscoreca** [FrSkyRC/ETHOS-Feedback-Community#4508]
X20Pro
attempt to update from 1.5.13 toeither 1.5.14 or 1.5.15, Flash also says it is out of date
Waiting for disk followed by "Missing drive" as the error.

What disk is it waiting for? I have no issues seeing or exploring both Flash and Radio

Debug info
Switch to page: ["/document"]
Switch to page: ["/radio"]
Target disk not found
Switch to page: ["/settings"]
Read i18n from: ["C:\\Program Files\\Ethos Suite\\resources\\app.asar\\..\\..\\i18n"]

**Comment by mawzthefinn** [comment]
Which Suite version?

**Comment by itizmeunderscoreca** [comment]
HI Adam
1.5.2

I had tried the check for update button, nothing happens

Thank you
Steve

**Comment by mawzthefinn** [comment]
Hi Steve,

That version is old and updating is known to be broken.

Please download and install the latest version from here:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/suite1.5.10

**Comment by itizmeunderscoreca** [comment]
Wow, everytime I check updates I check and figured no updates. I thank you for your time, hopeful I don't need to return.
Cheers
