### ISSUE TITLE
ETHOS 1.5.15 Cross Trims Only Work on Left Stick

### ISSUE THREAD

**Issue by hotdogx2** [FrSkyRC/ETHOS-Feedback-Community#4509]
My X18SE is more than a year old.  I just updated it to ETHOS 1.5.15.  Cross trim is now only working on the left stick.  To be specific, I have my cross trims set up so I have elevator and aileron on the left stick assembly, and throttle and rudder on the right stick assembly.  The elevator and aileron trim functions on the left stick work fine, but the throttle and rudder trim functions on the right stick have no effect on the throttle or rudder.

**Comment by mawzthefinn** [comment]
Just tested on my X18 on 1.5.15 FCC, cross-trims are working fine.

I would verify in Trims->Cross trim that it is set to
Stick Elevator->Trim Throttle
Stick Aileron->Trim Rudder

**Comment by hotdogx2** [comment]
I verified the cross trim settings; they are as you show.  When I look at the Outputs page I can see that the right stick trims have no effect.  Also when I power up my model I can see that the right stick trims have no effect.  Perhaps I should update the firmware on my TX again via ETHOS Suite?

**Comment by mawzthefinn** [comment]
What trim function do you have selected in the Throttle Mixer?

In rudder mixer, is Trim set to Off?

**Comment by hotdogx2** [comment]
I changed the trims back to normal positions and discovered that my throttle and rudder trims are still having no effect.  I am puzzled why the throttle and rudder trims have no effect.  In OpenTX one is able to choose whether the trim is on or off for each channel, but ETHOS doesn't have that option as far as I know, so no place to look to see if trims are on/off.

**Comment by hotdogx2** [comment]
In the throttle mixer the trim function is set to default.  My model has two rudders so I am using a free mix for the left rudder and a free mix for the right rudder, neither of which have a Trim function line.

**Comment by hotdogx2** [comment]
I should add that my model is a BTE Delta Vortex which is a delta wing model with two rudders.  so when I created the model I selected no tail and no rudders.  Going back to the Model Edit page I see that I can still select rudders even though I have no tail, so that's probably where I screwed up.  I will edit the model setup and see how that works.

**Comment by hotdogx2** [comment]
I've sorted it out.  I edited the model setup so that I was able to use the specific Rudders mixer instead of the Free mixes I had used before for the two rudders.  After I did that the rudder trim is working.  The reason the throttle trim wasn't working was I had the thottle cut engaged, and I didn't realize the thottle trim will only work when the throttle cut is off.  Thanks for your inputs!

**Comment by mawzthefinn** [comment]
Without an explicit trim assigment, any surface using Free Mixes will not see any trim effect on any version of ETHOS.

You can add an Offset Action to each rudder Free mix with the Rudder Trim function as the source to get rudder trim (this works for any trim function to any Free Mix)

**Comment by hotdogx2** [comment]
Yes that made sense (using free mixes) once I thought about it.  But I didn't know about using the Offset Action with a trim as a source, so thanks very much for that tip.  Still a lot I haven't learned yet about ETHOS.  Things are still easier for me to set up in OpenTX, but I guess that's because I'm used to it.  An example is I'm trying to figure out how to set up a Global Timer that tracks the on time on my X18SE transmitter.  So far I haven't found a way to do it.  I did it in OpenTX, but in that one has direct access to all the Global stuff.
