### ISSUE TITLE
Ethos logic switch system broken!

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#451]
I found a bug in the logic area of the X10S

When moving Logic switch lines up and down, other switch functions wont follow.

Create 2 logic switches
* LSW1 A~X Aileron 0
* LSW2 A~X Rudder 0

Create special function
SF1 Haptic LSW2

Now rudder activates haptic.
When moving LSW2 up, SF2 should also change following LSW1.. but is does not..

**Comment by loetefix** [comment]
I think the moving function of LS makes no sense.

**Comment by loetefix** [comment]
Or the special funtion and all other attached things should use the Name of LSW and not the number. So the Nuber is only an order.

**Comment by Hobby4life** [comment]
> I think the moving function of LS makes no sense.

oh yes, it certainly makes sense. this is actually one of the best features in ethos, having all your switches run with it. in open tx you left lines to put some more in between.

**Comment by loetefix** [comment]
Ok, you mean for a better overview?

**Comment by Hobby4life** [comment]
Also, for example if you have 10 logic switches with AND's and OR's, Stickies, etc.. that all interact with each other. and you move or delete 1 logic switch. normally you have to redo and move all switches in these logic switches up or down by hand.. now ethos does that automaticilly for you.. on the X20 works great.. on the X10 it does not.. dont know for X12

**Comment by loetefix** [comment]
I moved today a logical switch on my x20.and suddenly nothing worked. So i thought ethos doesnt it automaticly. Thats why i say it makes no sense. There is something wrong too on x20 then.

**Comment by loetefix** [comment]
I have 4 SF attached from lsw3 to lsw6. And after moving a logical switch all SF was attached to LSW7

**Comment by Hobby4life** [comment]
> I moved today a logical switch on my x20.and suddenly nothing worked. So i thought ethos doesnt it automaticly. Thats why i say it makes no sense. There is something wrong too on x20 then.

You are correct, whole logic system is broken!

It also does other weid stuff, I made a video.
It is also changing values when moving.

https://youtu.be/0YbkjCURpZ4

**Comment by bsongis-frsky** [comment]
Will be in 1.0.9 milestone 3
