### ISSUE TITLE
form.addTextButton

### ISSUE THREAD

**Issue by frobert0** [FrSkyRC/ETHOS-Feedback-Community#4513]
Hello,

1. can you change the text of a created text button "IN THE WIDGET"??

2. can you create an XVar from a LUA script, I know how to pass the value

3. how do you create a message box with yes / no to react to it in the LUA script

Thanks in advance

**Comment by bsongis-frsky** [comment]
English, french or chinese, please!

**Comment by frobert0** [comment]
Hello,

1. can you change the text of a created text button "IN THE WIDGET"??

2. can you create an XVar from a LUA script, I know how to pass the value

3. how do you create a message box with yes / no to react to it in the LUA script

Thanks in advance

**Comment by frobert0** [comment]
Hello,

can you change the text of a created text button "IN THE WIDGET"??

can you create an XVar from a LUA script, I know how to pass the value

how do you create a message box with yes / no to react to it in the LUA script

Thanks in advance

**Comment by strgaltdel** [comment]
Hi Robert,

i guess i answered your forms related question on friday in engel's Forum, but did not get any feedback....
