### ISSUE TITLE
1.5.15 Mixes: If there are several flight conditions, then the curve graph is smaller!

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4516]
If there are several flight conditions, then the curve graph in "MIXES" is smaller!
![image](https://github.com/user-attachments/assets/bc57722e-792d-494e-a0a1-788f34d44a55)
![image](https://github.com/user-attachments/assets/5e583fcb-be3f-47fc-8b84-46f9508da493)

**Comment by mawzthefinn** [comment]
Yes, because the space is needed to display up to 20 FM’s

**Comment by philippe-warnotte** [comment]
Ok, I understand, but it would be possible to delete the horizontal separation lines which are of no use and thus save space to enlarge the graph.

**Comment by bsongis-frsky** [comment]
Agreed about the horizontal separator

**Comment by bsongis-frsky** [comment]
@Nicholas-Luoyi we could use the small graph only if the description doesn't fit

**Comment by philippe-warnotte** [comment]
What description Nicholas?

**Comment by Nicholas-Luoyi** [comment]
I guess Bertrand just want to:
1) Remove the separator
2) Make use of the rest unused space on the right panel. i.e. If the FMs just take one line. Then we use a big curve graph

**Comment by philippe-warnotte** [comment]
I understood very well what Bertrand means. 
This is what you explain Nicholas about the description that I didn't understand.

**Comment by philippe-warnotte** [comment]
Great, thanks
