### ISSUE TITLE
Lua - additional 'exit state' needed when clicking on the 'clock icon'

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4517]
When you are using a lua that sets variables that very much need to know and retain state of a remote unit (fbl)  

Its possible to place the remote device in an unexpected condition by exiting the lua via an unusual path.

In this case - I can have my lua system too open; but 'exit' by clicking on the 'clock icon'.

Would be good to try capture this event?

**Comment by bsongis-frsky** [comment]
I think you meant the battery icon or the sound icon?

**Comment by bsongis-frsky** [comment]
Ready in the next nightlies: the close event will be fired in those use cases too (and it may be canceled)
