### ISSUE TITLE
stacking FLVS and GPS ADV

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#4518]
I have a small sailplane and would like to stack the FLVS and the GPS on top of each other to save room. Will this create any problems with either sensor? The GPS will be facing the sky.
Thank you,
Bill

**Comment by mawzthefinn** [comment]
So long as the GPS antenna is clear, no issues.

**Comment by lotus1235** [comment]
Thanks Mawz, wasn't sure if there might be an electrical issue between them,
Cheers
