### ISSUE TITLE
Indicator on "long press' menu items

### ISSUE THREAD

**Issue by miksterr** [FrSkyRC/ETHOS-Feedback-Community#453]
Hi. Wondering if an indication (even an *) on any menu item that has secondary, long press setting?

**Comment by bsongis-frsky** [comment]
good idea

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/123097384-64d2fe00-d430-11eb-9762-8b892cc229c1.png)
