### ISSUE TITLE
1.5.16 Mixes: Curve: Flight mode identify.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4530]
It would be nice to identify the active flight mode state for each curve.
 Highlighted FM number or other color.

![image](https://github.com/user-attachments/assets/3021bff0-e703-43eb-810e-7df10a0c640d)

**Comment by bsongis-frsky** [comment]
It displays when your mix is active, not when one of the included parameters is active

**Comment by philippe-warnotte** [comment]
If I have 1 throttle curve for FM 1 and another throttle curve for FM2, in the edit screen Throttle, I can see which flight mode is activated with my switch because it is brighter. This is not the case in the previous menu "Mixes"
![FM-curve](https://github.com/user-attachments/assets/f44574f5-1c91-4efb-82fa-b60567020051)

**Comment by philippe-warnotte** [comment]
It's a small detail of no great importance, no worries.

**Comment by bsongis-frsky** [comment]
The current FM and the Active Condition will be written in BOLD if active:
![image](https://github.com/user-attachments/assets/c23434dd-09b7-4d48-b94f-d15f108cea6a)

**Comment by philippe-warnotte** [comment]
Good job, thank you.
