### ISSUE TITLE
Lua Support for ELRS 3.5

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#4531]
Hi, Can we expect a lua script update to support elrs 3.5 as it is bringing so many new features like the gemini mode?

**Comment by mawzthefinn** [comment]
The current Lua supports Gemini, among other items.

Is it not working with 3.5 RC's? Because for the most part the script is just displaying what the Module/Receiver sends over

**Comment by robthomson** [comment]
I can certainly update this if required.

Maybe a better question would be..

If it stops working.. then why would the elrs team change the spec and not expect issues?

Considering the CRSF protocol is also in use on like of Spectrum.. I suspect that they will keep to spec and it will just work as expected with no changes our end.
