### ISSUE TITLE
1.5.16 X20S file path for documents/user incorrect

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4532]
Simulator is ok, Transmitter is not ok.

No more md files are displayed.
If you open the file selection in the widget program, no md files are available.
They are available in the file manager as usual.

Greetings Eugen

**Comment by yak55** [comment]
The problem with the display of md files in /document/user also occurs with the Tandem XE and X20PRO transmitters.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Which is the length of the filename?

**Comment by bsongis-frsky** [comment]
Max size is 15 today, but I will modify it to 30

**Comment by yak55** [comment]
Hi Bertrand, it works in all 3 simulators.
But in none of the 3 Transmitter X20S, X20PRO und XE.
These are the same md files that worked in 1.5.15.

Enclosed 3 pictures of the transmitters.

Language: German, display and audio


Greetings Eugen

![IMG_4918](https://github.com/user-attachments/assets/8adf7d91-0b81-4e62-8f4c-ec944b4b531a)
![IMG_4917](https://github.com/user-attachments/assets/c637b384-8bb7-4e41-a25f-e777fc85d93e)
![IMG_4916](https://github.com/user-attachments/assets/13292c26-b116-4b5d-b9c4-cc11219180b3)

**Comment by bsongis-frsky** [comment]
Would you please check the next nightlies? I think it opens the files from the bitmaps drive ...

**Comment by yak55** [comment]
Hello Bertrand, Nightly from Saturday 21.09.2024 installed on the X20S.

Error is NOT fixed.
The file path is still not found.

Have a nice weekend, greetings Eugen

**Comment by bsongis-frsky** [comment]
Thanks, I will have a serious look at it on Monday!

**Comment by bsongis-frsky** [comment]
Bug found. It will be solved in the next nightlies

**Comment by bsongis-frsky** [comment]
Fixed now?

**Comment by yak55** [comment]
All right, working again as before.

Thanks for the quick remedy

Greetings Eugen
