### ISSUE TITLE
Simulator 1.5.16 Editing an existing curve don't work correctly.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4537]
Simulator 1.5.16 Editing an existing curve does not work correctly. The points have changed. Ok with version 1.5.15
OK
![image](https://github.com/user-attachments/assets/66262a9c-00a5-42fa-be74-2d87e07d9652)
OK
![image](https://github.com/user-attachments/assets/a54e43e9-186b-4a22-b784-4a142d938ab2)
Curve Flaps Edit is NOT OK
![image](https://github.com/user-attachments/assets/e08eade3-2d87-4f81-8a01-7fbc02f8f608)

**Comment by bsongis** [comment]
It seems that the Offset is not taken into account in Model / Curve, right?

**Comment by philippe-warnotte** [comment]
The offset is well taken into account in model/curve and also in model/Mixer. But  when I want to edit this curve then this curve no longer has the same points. EDIT is to modify and not to start with a new curve.

**Comment by philippe-warnotte** [comment]
Edit curve ok on my radio 1.5.15
![Uploading 17268196017131596128576537755522.jpg…]()

**Comment by philippe-warnotte** [comment]
![image](https://github.com/user-attachments/assets/9ebcaca8-c6df-4a02-8ec7-c554ce336bda)

Edit Curve ok on my radio 1.5.15

**Comment by philippe-warnotte** [comment]
"Edit" works normally if I create a new model with 1.5.16 version.

**Comment by bsongis-frsky** [comment]
Fix ready for the next nightlies

**Comment by philippe-warnotte** [comment]
Wonderful !👍
