### ISSUE TITLE
Blank screen with ELRS script on some models

### ISSUE THREAD

**Issue by BRSS73** [FrSkyRC/ETHOS-Feedback-Community#4542]
Hi,
On two of my models, the ELRS script suddenly started displaying a blank screen, preventing me from configuring the TX or RX.
On my other models, or if I create a new model, the script displays the parameters correctly, so I'm leaning towards a problem linked to the model file.

X20RS - Ethos v1.5.15 - ELRS v3.4.3 LBT
I'm using the latest version of the script with a RadioMaster Ranger nano 2.4GHz.

Here's what I've tried without success:
- use the script uncompiled.
- change the baudrate to all those available
- clone problematic models

I could, of course, redo the models, but I've got a lot of mixers/LS/SF and the lack of a PC editor (or an editable file as with EdgeTX) makes things long and complicated to do.
It wouldn't solve the problem of erratic script behavior anyway.

**Comment by bsongis-frsky** [comment]
Does it work correctly with the previous release of the ELRS script?

**Comment by robthomson** [comment]
So if this is working on a blank model.. But not the new module.. Then it would very much point to a corrupt model or similar.

Especially if you have set it to run as non compiled and have the same issue.

Something worth noting.

The lua will fail very badly if you have something else using the msp code.

Are you using rotorflight with the new elrs telemetry?

**Comment by BRSS73** [comment]
> Does it work correctly with the previous release of the ELRS script?

Nope unfortunately, I've just tried July and mid-August versions.

**Comment by BRSS73** [comment]
> So if this is working on a blank model.. But not the new module.. Then it would very much point to a corrupt model or similar.
> 
> Especially if you have set it to run as non compiled and have the same issue.
> 
> Something worth noting.
> 
> The lua will fail very badly if you have something else using the msp code.
> 
> Are you using rotorflight with the new elrs telemetry?

Not Rotorflight, but Yaapu Telemetry Widget is running on a screen.
However, it also runs on my other models on which the script works flawlessly.

**Comment by robthomson** [comment]
So yapuu script will have a similar issue in that it will conflict.

Essentially with both scripts reading the serial buffer at the same time.

I did tell yaapu to ass in a feature we added to the elrs script that would help prevent this.   No idea if he ever did.

**Comment by BRSS73** [comment]
OK.
After deleting the Yaapu telemetry widget, the script works on all models!
Thanks a lot to both of you.

I'll check if there's a newer and working version of Yaapu's script .
