### ISSUE TITLE
addChoiceField always uses 3rd item as default

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4544]
addChoiceField always uses 3rd option as default.
If there are only 2 options, you get "???" in the choice field.

It would be nice to be able to select a default item.
THANKS!

**Comment by bsongis-frsky** [comment]
Perhaps your `getValue` handler doesn't return something right? Or you wouldn't have "???" in the choice field.

It will be easier to help if you paste your script here!

**Comment by noamkrief** [comment]
@bsongis-frsky 


local function create()
    return {
            battery_alert = false,
            }
end


local function wakeup(widget)

end


local function paint(widget)
	
end

local function configure(widget)
	line = form.addLine("Battery Type")
	form.addChoiceField(line, nil, {{"Lipo", 1}, {"HV Lipo", 2}, {"Lion", 3}, {"LiFe", 4}}, function() return widget.BattType end, function(value) print(value) widget.BattType = value end)
	--widget.BattType_field:default(1)
	
end

local function read(widget)
	widget.BattType 		= storage.read ("BattType")

end

local function write(widget)
	storage.write("BattType"		  , widget.BattType)

end

local function init()
system.registerWidget({key="noam", name="noam", create=create, paint=paint, configure=configure, read=read, write=write, wakeup=wakeup})
Init = false
end

return {init=init}

**Comment by philandroid36** [comment]
begin with 0 (zero) and it's ok
{{"Lipo", 0}, {"HV Lipo", 1}, {"Lion", 2}, {"LiFe", 3}}

**Comment by bsongis-frsky** [comment]
widget.BattType should be initialized in create
