### ISSUE TITLE
Ethos: Add Analog switch for mixes.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4549]
Be able to add analog source in category of "Weight/Rates"
or create an analog switch with values min-max Weight/Rates.
Exemple: Throttle stick changes the values ​​of Weight/rates elevator and ailerons.
The model will be more or less responsive depending on the throttle stick position.
Is it possible to do this with Ethos?

**Comment by mawzthefinn** [comment]
Yes, any Weight can 'Use a Source'. Process via a VAR or Free Mix if you want a range other than normal.

**Comment by bsongis-frsky** [comment]
Indeed

**Comment by philippe-warnotte** [comment]
Could you, as an exception, post the file of a simple plane with this function please?
Example: When throttle stick down, the aileron range(rate) is 100%
               When throttle stick up, the aileron range(rate) is 50%
When you move the throttle stick, the aileron range(rate) varies between 100% and 50% but does not move 
the central position of the aileron servo. This is not a Throttle-Aileron compensation but a kind of variable Dual-rate
assigned to the ailerons depending on the position of the throttle stick.

**Comment by mawzthefinn** [comment]
Add a Free Mix, name it Aileron Rates, source is Throttle. Add a Curve to it, 2 points, with point 1 at 100% and point 2 at 50%. Set the output to a channel above 24 ( I usually start at ch64 and work down for this). We'll say we used Ch64 for this example. Let it name the channel

Now long-press your aileron rates, select Use a source, select Channels->Ch64 (Aileron Rates)

**Comment by philippe-warnotte** [comment]
You are a great man! 
I wouldn't have found this method without your help. 
It works perfectly as I wanted. Thank you very much.
