### ISSUE TITLE
Request: Button for open Output monitor

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#455]
Pressing the DISP button long to bring you directly to the Servomonitor from Homescreen . Is that possible?

**Comment by bsongis-frsky** [comment]
I think it gives me a good idea, the DISP button could be configurable:
- Configure screens (as it is today)
- Outputs Monitor
- Something else?

**Comment by Hobby4life** [comment]
Long Press: Configure Screens

Short Press: browese between outputs and others?

**Comment by loetefix** [comment]
I think these 2 options is enough. Dont make it too heavy.

**Comment by centertrim** [comment]
Short Press:  Outputs menu
… followed by later RTN button press:  Return exactly to where you were before short press of Disp button.

Similar to how long pressing enter in mixer menu takes you to outputs menu, then returning takes you back to that mixer.

**Comment by loetefix** [comment]
So Long press Enter will be free for direct edit a Line.How about that?If you press long enter on a LS / MIXER / CURVE etc. you are in EDIT mode. If you press short Enter, the drop down menu opens like today.or vice versa (long/short)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/122756959-5d2c2180-d297-11eb-9fbc-575e11a63344.png)

**Comment by loetefix** [comment]
Very nice . Thanks!
