### ISSUE TITLE
Mixer channels wrong when choosing stabilized receiver option for "ArcherX"

### ISSUE THREAD

**Issue by frskyrc-ben** [FrSkyRC/ETHOS-Feedback-Community#4552]
The mixer channels are incorrect when choosing stabilized receiver option for "ArcherX" (for ex. Archer SR6, SR8 PRO and SR10 PRO)

The Gain Adj. should be assigned to CH9, Flight Mode 1 to CH10 and Flight Mode 2 to CH11, but they are being assigned to CH13, CH14 and CH15

![image](https://github.com/user-attachments/assets/02c46c32-9cc2-40b2-844c-8e08b47d6eab)

![image](https://github.com/user-attachments/assets/84be0849-9732-49dd-871d-075d73106ea0)

![image](https://github.com/user-attachments/assets/8ff4ec63-f10e-407b-9325-39325b9067ce)

![image](https://github.com/user-attachments/assets/88f0f5f5-9574-465d-9f1b-b5ca256340e9)

**Comment by Nicholas-Luoyi** [comment]
Marked with the incorrect stab channels count in the server JSON file. Have been fixed and pushed. Shall be OK in the next release.
