### ISSUE TITLE
EM when deleting a curve

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4553]
EM when deleting a curve Transmitter X20S - Simulator is Crash!

Nightly from 23.09.2023
Transmitter: X20S

A curve, regardless of whether it is assigned to an output or not, can no longer be deleted.

There is an EM when deleting.
After restarting, the curve is still there.

Greetings Eugen

**Comment by bsongis-frsky** [comment]
Thanks again!
