### ISSUE TITLE
Model copy X20 -> X10S Express, RF system not working

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#456]
I have copied my models from my X20S to my X10S Express.
All works, some pots have to be reassigned.
But the RF system is not working anymore.

I gues the model is configured for the TD-ISRM board..
It shows all tandem settings, not possible on X10 :-)

At least ACCST is not working, can not bind anymore.. creating a new model and bind works.
ACCESS not tested.

v1.09rc3

**Comment by bsongis-frsky** [comment]
Fixed in candidate 4
