### ISSUE TITLE
Oddity in model Checklist with Function Switches Warning

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#4560]
I notice there is a slight oddity in the model Checklist related to Function Switches.

Currently it is possible to set the FS in Edit model to e.g. 6 POS + Off but also then set the Checklist Function Switches to have more than one On. Clearly this will always result in FS being alerted to being wrong so is rather pointless. 

I suspect that the Checklist should have a sanity check in it that the requested FS setup is actually possible with the requested FS checklist setup.

Thanks

**Comment by bsongis-frsky** [comment]
This is right. There is room for improvement. Here is my proposal:
1) If the FS are not persistent, there is no need for any preflight warnings, and the associated configuration is not needed
2) If the FS are Momentary, the "Persistent" is not needed in Edit Model, no need for preflight warnings + configurationn
3) In all other modes, with "Persistent" selected, then the configuration must be adapted

**Comment by Jedsters** [comment]
I'm not sure I agree with that. 

I was thinking that the checklist should always alert to any FS which aren't correct but that it shouldn't be possible to setup a checklist which contradicts the FS definition. 
So:
With 6 Pos with OFF either 0 or 1 FS must be set to ON in the checklist
With 6 Pos, only 1 FS must be set on ON in the checklist
With 2 x 3 Pos,  exactly 2 FS must be set to ON in the checklist
With 6 x 2 Pos any number of FS may be set to ON in the checklist
With Momentary NO FS must be set to ON in the checklist

I would imagine this would be done in the checklist by e.g. with 6 Pos, if FS1 is set to On and you select FS2 to On, it should automatically set FS1 to Off - exactly as the actual FS behave etc..

If #4556 is implemented (please), then there is no need to alert to FS in the checklist as Ethos would automatically set the FS to be as per the checklist so they would always be correct.  

Any extra definition option as per #4556 should be alongside Persistent, so only one or the other can be selected. 
However if Persistent is selected then I think that checklist warnings should still be issued for FS. The checklist is how you want things at the start of the flight, but maybe I'm wrong here?. Or should there be another option of Persistent with no checklist warnings?

I notice there is another little oddity too, when you change the FS definition then all FS are turned off even though this potentially now makes the FS incorrect according the definition. I'm guessing that is intentional (difficult to do anything else). Although what should then happen to the checklist, should all these also be set to off? Is the safe option perhaps a warning message when the FS definition is changed that the checklist may need changing and leave the user to correct it, or perhaps better would be to then navigate the user to the checklist so that it can be forced to be valid - unless they power off the radio! 

Thanks

**Comment by bsongis-frsky** [comment]
I close this one in favor of #4556
