### ISSUE TITLE
form.invalidate() deprecated since Ethos 1.5.10

### ISSUE THREAD

**Issue by twinking92** [FrSkyRC/ETHOS-Feedback-Community#4563]
form.invalidate() is deprecated since Ethos 1.5.10. Is there any new or better option to call?

I'm new to programming lua for ethos. Therefore, I don't realy know what it did before. But in my understanding it was used to update a form. E.g. I would like to use a boolean form to give more or less options in the configure handler when it is clicked.

However, I think the documentation should contain information about what is the new or better option if a function is deprecated.

**Comment by bsongis-frsky** [comment]
You may just use `lcd.invalidate()`, but it forces a full refresh of the widget / tool
