### ISSUE TITLE
Suite 1.5.10 Dowloadcenter FLVSS Error

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4564]
Suite 1.5.10 Dowloadcenter FLVSS Error

Picture of the error message attached

Greetings Eugen

![Suite](https://github.com/user-attachments/assets/dff4d1f1-4c18-4639-9c7e-04f033fff6b0)

**Comment by mawzthefinn** [comment]
That error is correct, it's an old S.Port sensor with a .frk format firmware. Suite cannot flash the firmware as it's not an .frsk file.

**Comment by yak55** [comment]
Hello, I can't confirm that.
The MLVSS sensor can be updated without any problems.

Can you please check this again?
Only the FLVSS does not work for me.

Greetings Eugen

**Comment by mawzthefinn** [comment]
I checked the zip file before I posted that. The latest FVLSS firmware is an frk file

**Comment by yak55** [comment]
The FLVSS is also still on sale on the FrSky website.
It's a pity it can’t be updated via suite.
Translated with DeepL

Greetings Eugen

**Comment by mawzthefinn** [comment]
Rolling this into #4566 as they are the same issue. Need new .frsk format builds of that firmware published.
