### ISSUE TITLE
Suite 1.5.10 Dowloadcenter S6R not correct

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4565]
Suite 1.5.10 Dowloadcenter S6R not correct

Picture of the error message attached

Greetings Eugen

![Suite](https://github.com/user-attachments/assets/09e714aa-57b7-4d76-af1e-2aa122495ea4)

**Comment by Nicholas-Luoyi** [comment]
Can this be reproduced?

**Comment by yak55** [comment]
This is reproducible.
Tried again this morning.
Enclosed is the Windows version.
Greetings Eugen

![Neu](https://github.com/user-attachments/assets/4419d560-2227-4359-bc33-66c1b49c8423)

![Win11](https://github.com/user-attachments/assets/25e88976-b9da-4f27-a454-0d3031c0e5eb)

**Comment by Nicholas-Luoyi** [comment]
![image](https://github.com/user-attachments/assets/ece0928a-2b4f-43c6-9895-c9527b7951fa)

Please open the debug mode and then reproduce this issue. And post the debug traces here by open the debug directory.

**Comment by yak55** [comment]
Hello, when I close the error window, the suite closes automatically.
Please find attached the file, packed.
[Crashpad.zip](https://github.com/user-attachments/files/17162723/Crashpad.zip)


Greetings Eugen

**Comment by yak55** [comment]
Here again the data from call to crash from a single session.

Greetings Eugen
[debug-20240927.zip](https://github.com/user-attachments/files/17163908/debug-20240927.zip)

**Comment by yak55** [comment]
Hello, I have now found a solution.
Uninstalled Suite 1.510 and then reinstalled it.
Now you can download the zip file.
Flashing does not work because no suitable format was found.

Have a nice weekend 
Greetings Eugen

**Comment by Nicholas-Luoyi** [comment]
> Hello, when I close the error window, the suite closes automatically. Please find attached the file, packed. [Crashpad.zip](https://github.com/user-attachments/files/17162723/Crashpad.zip)
> 
> Greetings Eugen

This could help me. Thanks
