### ISSUE TITLE
Gas Suite config

### ISSUE THREAD

**Issue by crossup125** [FrSkyRC/ETHOS-Feedback-Community#4567]
While setting up Gas Suite sensors I see there is a text formatting issue with the sensor lost warning delay on the GAS RPM page.
![screenshot-2024-09-26-38785](https://github.com/user-attachments/assets/49c63084-8bdf-47e0-9074-9de3964e3b6a)

**Comment by bsongis-frsky** [comment]
Not already fixed in 1.5.16 nightlies?

**Comment by Nicholas-Luoyi** [comment]
Well. This is confirmed fixed in the latest nightlies.
