### ISSUE TITLE
Setting / Sensor Config / Power Switch  Heading after opening: GPS 

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4569]
Setting / Sensor Config / Power Switch

Heading after opening: GPS 

![Sensor Power switch Bild 1](https://github.com/user-attachments/assets/4b78f079-22b5-4fae-beaf-d9b20d690eb5)

![Sensor Power switch Bild 2](https://github.com/user-attachments/assets/c518ff91-f6bb-4484-91b1-21c2f08e87a3)

Greetings Eugen

**Comment by bsongis-frsky** [comment]
OOPS

**Comment by bsongis-frsky** [comment]
The title was wrong, but just the title

**Comment by yak55** [comment]
Yes, only the title was wrong.
The function with the power switch works perfectly.
I have tested it as S-Port and FBUS.

I have now deleted the former script.

Have a nice weekend

Greetings Eugen
