### ISSUE TITLE
Frsky Gr8

### ISSUE THREAD

**Issue by gomitologiallo** [FrSkyRC/ETHOS-Feedback-Community#457]
After updating the firmware of the Gr8 receiver, it does not turn on anymore (no LEDs lit).
How can I solve?

**Comment by jfint** [comment]
Update again, but with a wire cable.  Double check that the firmware file is the correct one.

**Comment by Hobby4life** [comment]
Do you have any other radio to upgrade with?

**Comment by bsongis-frsky** [comment]
No, not an Ethos issue, I will close it, we have already enough in our plate!
