### ISSUE TITLE
Slower UI when adding lua widgets

### ISSUE THREAD

**Issue by neuhausj** [FrSkyRC/ETHOS-Feedback-Community#4572]
Hello,
As part of the creation of my F3k template, I made 2 simple widgets to display a status and a nicer battery widget. (available here > https://github.com/neuhausj/Ethos-resources )

However, the whole radio is becoming a lot less responsive with these 6 lua widgets, and for each widget removed, the whole radio is speeding up again.
How can the UI responsiveness be improved? Why the whole system is getting slower? (also the system/model menus)
When loading a new model without any widget, the radio is fast again, so it definetely comes from the lua widgets.

I am using these 2 pages, with each 3 lua widgets on it:
The idea is to keep track of the voltages and radio status easily.

* Flight view: activated after launch
![image](https://github.com/user-attachments/assets/34403a3e-8f2f-459c-9562-549a5991ab98)

* Flight summary: activated after landing
![image](https://github.com/user-attachments/assets/d73097aa-7cdb-4219-a3e5-30b81dfb919d)

What I tried:

* checking if the widget is visible or not in the wakeup call but it doesn't seem to help:
```
local function wakeup(widget)
    if lcd.isVisible() then
        doStuff ...
    end
```
* compiling the lua but I didn't see much performance gain
* trying to only call the refresh function once per second
* loading completely empty widgets (all code in paint and wakeup commented), and the radio is also getting slower

This was tested on both a X18SE and a X20Pro with latest firmware:
<img width="229" alt="image" src="https://github.com/user-attachments/assets/57be57cb-c8a6-4e2b-9afa-7539fefd0cd4">

Thanks in advance for the support.

**Comment by bsongis** [comment]
Do you have any other script than those 2 ones?

**Comment by neuhausj** [comment]
No, only the elrs one.
<img width="187" alt="image" src="https://github.com/user-attachments/assets/00799f90-9247-4aea-81d9-f9ff2aed288e">

I also have a F3K template for 4servos wing where it is even worse (probably due to additional mixes and curves for calibration).
Here is a beta version > [F3K 6s template.bin.zip](https://github.com/user-attachments/files/17155808/F3K.6s.template.bin.zip)

**Comment by bsongis-frsky** [comment]
Please provide a "minimal" ZIP with everything needed to reproduce the problem, I will have a look tomorrow.

**Comment by neuhausj** [comment]
Thanks for your support.
Here a copy from my radio of models + scripts + audio to put in the correct folder.
* `F3K 2s template` (2 servo wing) is a model with 6 lua widgets
* `f3k 4s without` (2 servo wing) is a copy from `F3K 2s template` without 4 lua battery widgets
* `F3K 6s template` is a more complex model (4 servo wing) with the same widget as `F3K 2s template`

You should notice the difference in UI speed between the 3 versions.
I tested this on 2 different radios (X18SE and X20Pro).
Let me know if you need further details.


Setup instructions are available on the repo if needed > https://github.com/neuhausj/Ethos-resources

<img width="194" alt="image" src="https://github.com/user-attachments/assets/52530051-2216-4851-961f-474f4adf70fa">

[Radio extract.zip](https://github.com/user-attachments/files/17156329/Radio.extract.zip)

**Comment by bsongis-frsky** [comment]
Indeed the UI becomes slow. I wonder why there are debug traces such as "wakeup" or "paint".

**Comment by neuhausj** [comment]
I tried to optimize my 2 widgets as much as possible yesterday and used some print to check how quickly those were called. Even calling them slower didn’t help. 

You can replace the 2 widgets with the one from the repository (they don’t have the print active): https://github.com/neuhausj/Ethos-resources

**Comment by bsongis-frsky** [comment]
Are you sure that this compilation chain optimizes speed? I am not so sure. I have removed it here, removed the debug and removed the errors and it is already quicker. I work with the 6S template which you consider as the worst one, right?

**Comment by neuhausj** [comment]
I think it helped, yes. The same approach was used for other scripts (elrs) and on EdgeTX as well iirc. 

My initial approach was to just use a single main function. 

I have it versioned here if you want to check > https://github.com/neuhausj/Ethos-resources/tree/107c7c96de047d1e6dd520ce87a1a36c6e0c3278

**Comment by neuhausj** [comment]
I also tried using completely empty widgets (all code in paint and wakeup commented), and the radio was also getting slower.

**Comment by bsongis-frsky** [comment]
I think I have found the problem: to allow the Lua scripts to access his resources at any time, Ethos does a chdir into the script directory. It does this on each wakeup, on each paint, etc. Then at the end of all those functions, it chdir into the previous directory (you could be navigating inside System / File Manager ...)

And the problem I just discovered is ... it costs 6ms on each call. So 12ms per wakeup. Plus another 12ms in case you need to paint something. You have 6 widgets ... the UI responsiveness will be killed.

I will find another solution before the next nightlies.

**Comment by neuhausj** [comment]
This is very nice hear ! Thank you for the debugging.
I can give a test on the nightlies as well if it can help.

**Comment by strgaltdel** [comment]
> And the problem I just discovered is ... it costs 6ms on each call. So 12ms per wakeup. Plus another 12ms in case you need to paint something

Wow, seems a solution could really improve overall performance in case you 've several widgets active !

... would have thought that the "global declaration" of the class which is used in every handler could have caused a slighty performance penalty, but not so much as mentioned.. 


```
compileStatus = assert(loadfile(config.moduleDir .. "compile.lua"))(config)
myWidget = assert(compile.loadScript(config.moduleDir .. "loadable.lua"))(config, compileStatus)

```

why not declare
local myWidget = .... ?

**Comment by bsongis-frsky** [comment]
The performance gain after my fix seems huge on my X20-PRO. I hope there is no regression with relative paths now!

**Comment by bsongis-frsky** [comment]
Please give it a test when the nightlies are out, thanks a lot!

**Comment by bsongis-frsky** [comment]
I wonder if it could be the same problem than #4374
After USB is disconnected, the file system is mounted again, and the file cache is different ...

**Comment by bsongis-frsky** [comment]
@strgaltdel Don't hesite to give another test with this fix, I would like to close #4374 in the same shot ;)

**Comment by neuhausj** [comment]
Hello,
I just tried the latest nightlies and noticed that the performance seems indeed better. 
However, when enabling the ELRS script with 5.25Mbs baudrate, the performance degrades significantly again. 
When set to 400k (which is fine up to 333Hz full), it is better but still slower.

I also noticed the widget does not behave the same in the nightly vs stable version: in the stable version, the value of an inactive telemetry value (without connection) is 0 vs nil in the nightlies (hence I added a check in the latest version).

And the speed doesn't seem to change when both widgets have an empty paint and wakeup functions.


Also thanks [strgaltdel](https://github.com/strgaltdel) for the tip, I updated both widgets to use a local variable, but it doesn't seem to improve much.

**Comment by bsongis-frsky** [comment]
@neuhausj I have just started the nightly. It cannot be fixed in all firmware compiled before this comment has been written :)

**Comment by neuhausj** [comment]
My bad !!
I am using the X18SE to test and the firmware was indeed not compiled yet.
I'll wait a bit more and redo my testing. 😉

**Comment by neuhausj** [comment]
Just quick update: I tried the latest nightly and the speed is great! You can hardly distinguish this from a model without widgets.
Also no impact from ELRS speed change.
Thanks a lot for this update, 1.5.16 looks promising !
