### ISSUE TITLE
Lua Dialog box - scroller not working

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4574]
When using the lua popup dialog box with long text, you get a scroller.

This scroller works with 'touch', but not with the keypad / right hand scroller.

I imagine the issue is that the scroll wheel moves to the button as thats the focal point.

Might need to think about how to make this work as its broken on non touch radios.

**Comment by bsongis-frsky** [comment]
No example script. Perhaps we could use PAGE for this
