### ISSUE TITLE
New Lua Event - telemetry lost

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4581]
Would be handle to have a lua event id that triggers when telemetry is lost.

Will enable 'quick actions' and now waitng like 5s for the sensor state to change!

**Comment by bsongis-frsky** [comment]
This source should do the job:
```lua
system.getSource( { category=CATEGORY_SYSTEM_EVENT, member=TELEMETRY_ACTIVE } )
```
