### ISSUE TITLE
H4LGPSMAP Stopped working after update to 1.5.14 and 1.5.15

### ISSUE THREAD

**Issue by krokusvej** [FrSkyRC/ETHOS-Feedback-Community#4582]
Hi it seams that the way it get GPS coordinates have changed so it doesn't latitude and logetude right anymore any one who know why?

https://github.com/PD5DJ/H4LGPSMAP V1.06

Is variable changed or is there a setup that I have missed in 1.5.14 and 1.5.15?

I'm running 1.5.15 Ethos on X20S.

**Comment by bsongis-frsky** [comment]
Any error?

**Comment by krokusvej** [comment]
Jut Out of Range it seams that lat and long get the same koordinat if you look down in left corner
![20240930_194153](https://github.com/user-attachments/assets/562a1c17-2ae9-4b12-8865-ba7282d3f0aa)

**Comment by xet303** [comment]
This problem appeared after the upgrade to Ethos 1.5.10. The author of the widget no longer provides support.
A post on RCG exists on this problem, just follow the thread. As the author of the widget no longer provides support, someone should look into it. I had started but not finished & put that aside for now.
https://www.rcgroups.com/forums/showpost.php?p=52685241&postcount=1201
https://www.rcgroups.com/forums/showpost.php?p=52692773&postcount=1212

**Comment by mawzthefinn** [comment]
This change was for Google Maps compatibility

#3881
