### ISSUE TITLE
Under Flap Mix please do ad slow Elevator in combination 

### ISSUE THREAD

**Issue by krokusvej** [FrSkyRC/ETHOS-Feedback-Community#4583]
HI have tried adding slow flaps to my model but the elevator compensation does not inharit the slow time from flaps, so it's not working in kombination. Ethos 1.5.15 X20S

**Comment by mawzthefinn** [comment]
Make sure one of your flaps output channels is the Source for the Flaps to Elevator mix. It will work correctly only when you mix the output of the flaps functional mixer to elevator.

Most users (including me) started using the same input as the Flaps mixer, but that skips the flaps processing and causes the issue you have found.

**Comment by krokusvej** [comment]
Super thanks, that solved it I had my switch for flap as input. It makes sence
