### ISSUE TITLE
Last nightlies, servobalancer, help file in X10S Express

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4584]
Hello, in the X10S Express simulator, nothing is displayed in the help file in the servo balancer. I can't check it with the transmitter as I only have this one. It would also be nice if it were available in German.
Greetings
Wolfgang

**Comment by bsongis-frsky** [comment]
There is no MD support on Horus radios, it's impossible to display help there. You have to use one of the Tandem simulators!

**Comment by bsongis-frsky** [comment]
Help icon removed on Horus for the next nightlies
