### ISSUE TITLE
Several issues with Calculated Sensor (X18SE, Ethos 1.5.15.EU)

### ISSUE THREAD

**Issue by PeterGraz** [FrSkyRC/ETHOS-Feedback-Community#4585]
There are several problems when creating a custom Calculated Sensor (German user interface).
After selecting the Formula Custom you get the following screen:
![ScShot1](https://github.com/user-attachments/assets/aa2e66e9-854c-4ef8-b2af-73d9bcca89a6)
a large black area up to the next menu item
![ScShot2](https://github.com/user-attachments/assets/379308bb-83b3-43fb-8459-cde3a6456b73)
![ScShot3](https://github.com/user-attachments/assets/c9c8c1e5-cb4f-4f2d-a155-61d541293d97)
Then I entered the name of the sensor (DEMO) and 2 decimal places and did not change the range
![ScShot4](https://github.com/user-attachments/assets/25a0ff82-fb32-406d-8900-81ce1e722737)
I selected the receiver voltage as the source, added a division, selected “Convert to value” and I got the following screen
![ScShot7](https://github.com/user-attachments/assets/71e9defc-72a8-41e7-9e1e-b3cc0de1a9c4)
Step size 0?
chose a value of 3: Calculation correct
![ScShot8](https://github.com/user-attachments/assets/0b6d36a7-e111-4e78-b14e-721aac131e70)
then I added the value 431
![ScShot10](https://github.com/user-attachments/assets/d75bc122-2e7f-4680-9276-0b21e9337852)
the value 431 was apparently divided by 100 (2 decimal places?) and the increment?
then I added the receiver voltage again 
![ScShot12](https://github.com/user-attachments/assets/064e9ed0-0d11-4f5a-9997-639f56fef6b8)
Somehow correct result
Finally, I replaced the addition with a multiplication 
![ScShot13](https://github.com/user-attachments/assets/1058fbd1-b44b-431a-89a1-b99c4a936f9f)
![ScShot14](https://github.com/user-attachments/assets/77473115-3314-4732-bfc1-071472985d4a)
Now I'm questioning my primary school education!?

If desired, I can create more funny examples.
Best regards, Peter

**Comment by PeterGraz** [comment]
The first two lines should read:
There are several problems when creating a custom Calculated Sensor (German user interface).
After selecting the Formula Custom you get the following screen:

**Comment by bsongis-frsky** [comment]
Display issue - The problem is fixed since some time in 1.5.16 :

![ScShot1](https://github.com/user-attachments/assets/aa2e66e9-854c-4ef8-b2af-73d9bcca89a6)
![ScShot2](https://github.com/user-attachments/assets/379308bb-83b3-43fb-8459-cde3a6456b73)
![ScShot3](https://github.com/user-attachments/assets/c9c8c1e5-cb4f-4f2d-a155-61d541293d97)

**Comment by bsongis-frsky** [comment]
Step badly displayed - The fix is ready for the next nightlies :

![ScShot7](https://github.com/user-attachments/assets/71e9defc-72a8-41e7-9e1e-b3cc0de1a9c4)
![ScShot8](https://github.com/user-attachments/assets/0b6d36a7-e111-4e78-b14e-721aac131e70)
![ScShot10](https://github.com/user-attachments/assets/d75bc122-2e7f-4680-9276-0b21e9337852)

**Comment by PeterGraz** [comment]
Bertrand, merci pour ta réponse rapide!
Please pay also attention to the calculation. Is this the desired result?
Regards, Peter

**Comment by bsongis-frsky** [comment]
Multiplication & Division - The decimals are not displayed when a fixed value is used :

![image](https://github.com/user-attachments/assets/7af08bde-b04e-4c01-84f0-7eee887d107e)

**Comment by bsongis-frsky** [comment]
Other operations - The decimals are displayed :

![image](https://github.com/user-attachments/assets/a385cd6c-799c-4d80-a72e-fe68fef30373)

**Comment by bsongis-frsky** [comment]
Parenthesis added when a multiplication follows an addition :

![image](https://github.com/user-attachments/assets/c2077b7f-1c43-4cad-a2cc-26be1bb4c429)

![image](https://github.com/user-attachments/assets/c582e6b6-a851-42e7-ac8b-11dcbd938e3d)

**Comment by bsongis-frsky** [comment]
The same sensor, when decimals setup to 1 displayed 108.0V until release 1.5.15. It will now display 10.8V :

![image](https://github.com/user-attachments/assets/f91a84d5-f46c-4969-846e-4c5dcedd1ea6)

**Comment by bsongis-frsky** [comment]
The same sensor will have internal conversions from the calculations unit to the display unit (when possible) :

![image](https://github.com/user-attachments/assets/21bbf940-7778-4e1f-8f31-d5e21c2cc55a)

**Comment by bsongis-frsky** [comment]
Check the multiplication with the previous voltage ....

![image](https://github.com/user-attachments/assets/fa333e10-ff7b-43dc-8a47-4cee667cef5b)

![image](https://github.com/user-attachments/assets/7aba28b0-ad90-494a-8939-7284024c7121)

**Comment by PeterGraz** [comment]
Your examples look perfect! Looking forward to 1.5.16,
Peter
