### ISSUE TITLE
DIY sensors 

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#459]
Hello,

I am using sensors for turbine with different ID, there are not discovered under 1.0.9 RC4.
Working fine with access and OTX 
Need to work for turbine telemetry
thanks

**Comment by Hobby4life** [comment]
Please specify the id's

**Comment by aviat40** [comment]
XICOY Telemetry sensor turbine : ID 27 with sensors from 4400 to 4415 that i usually rename inside a home made LUA widget
@bsongis-frsky Bertrand : LUA ???

**Comment by Helischorsch** [comment]
DIY Powercontrol Sensor with Sensor-ID 8 and Data-ID 0x5101 is not detected. Sensor works fine with OTX

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128308172-1ba3e37a-16a4-4203-852c-77088a677653.png)

**Comment by aviat40** [comment]
Hello Bertrand,

Do you have the list of ID recognized by ETHOS ? Or is there any reason to limit ID for Frsky Sensors ? 

Thank you

**Comment by bsongis-frsky** [comment]
Which limit?

**Comment by aviat40** [comment]
Does the 1.0.11 allow DIY sensors as shown in your picture ? Will be fine. I have a sensor for turbine from 4400 to 4415

If yes, I am waiting for to test .
Thanks
