### ISSUE TITLE
Migration issue between X10s Express and X20RS

### ISSUE THREAD

**Issue by ftc2629** [FrSkyRC/ETHOS-Feedback-Community#4591]
I have a X10s Express and a X20RS. Both radios with the actual ISRM firmware Both radios on Ethos 1.5.15. I use only ACCST and Access receivers with the actual firmware.
When I migrate models from the X10s Express to the X20RS and register/bind the receiver on the X20s, the RSSi value drops directly to 70db or even lower and after going away with the radio a few meters the RSSI is so low that the receiver goes to failsafe. I tried different migrated models with receivers S6R ACCST, Archer RS plus Access, M+ Access, SR8pro Access. Same problem with all receivers.
If I create a new model on the X20RS from scratch, all these receivers have after registering and or binding directly a RSSI of 100db. I flew meanwhile 4 models with these receivers without any warnings of signal quality with the X20RS
So something is going wrong when the models are migrated from the X10s Express. 

I tried different methods of migration:
Backup X10s Express and restore the models to the X20RS.
Send / Receive model from X10 to X20RS
Copy / Paste directly from the file folder.
The receivers show always the same behavior. Low RSSI and failsafe after a distance of appr. 10m.

Can anyone confirm the same issue when models are migrated from a X10s Express to a X20RS?

I have attached to model files of my X10s Express for testing.

 
[Archiv.zip](https://github.com/user-attachments/files/17209321/Archiv.zip)

**Comment by bsongis-frsky** [comment]
The 2 radios have a very different RF in the internal module. During conversion I think the whole RF information for the internal module should be reset
