### ISSUE TITLE
Firmware OTA update TD R12 error

### ISSUE THREAD

**Issue by davebrowne4** [FrSkyRC/ETHOS-Feedback-Community#4592]
Newest 1.0.13 Firmware update for TD R12 will not OTA update. unrecognized RX error. X20S on 1.5.15.
Anyone have a fix. I see there is a beta .13 that is suppose to work but dont know if I can trust it.
Is there a New TD R12 firmware that fixes this BUG that will be posted on FRSKY?
All my other TD receivers updated fine with X20S on 1.5.15

**Comment by Wolepo** [comment]
The best way to do this is via the S.Port connection of the transmitter

**Comment by davebrowne4** [comment]
> The best way to do this is via the S.Port connection of the transmitter

Can you please describe how this is done and what cables I need and where to plug them in.
Thanks

**Comment by Wolepo** [comment]
The RX is supplied with a cable that can be connected to the Upgrade + AIN_ input. The yellow, black and red wires are probably combined in a uniplug. This is plugged into the S.Port connection of the transmitter. The yellow cable points towards the nose.  Then select the corresponding FW in the transmitter and transfer with ‘Flash _**external device**_’

**Comment by mawzthefinn** [comment]
This is fixed with the upcoming RF 3.0.0 firmware release.
