### ISSUE TITLE
Screens are not copied from the radio model to the Sim

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4597]
I am running Ethos 1.5.15 and Sim 1.5.14. When I copy a model (bin file) from the Radio to the PC, the sim does not show the the last screen I created. I tried the clone trick but that doesn't work either.
Here is the bin file. 
[pc-21 v1.1.zip](https://github.com/user-attachments/files/17248843/pc-21.v1.1.zip)
This file was created and copied from the radio itself.

**Comment by bsongis-frsky** [comment]
The simulator should be on the same version!

**Comment by Richrfl** [comment]
Bert, can you please send me a link for X18S sim 1.5.15? Is not in the assets list of the Ethos 1.5.15, and I found a version 1.5.16 in the list of the 1.15 nighties.
Thank you
