### ISSUE TITLE
Model wizzard not creating all mixes and channer assigment is wrong

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#46]
Horus x12s V1.0.1 ethos
When creating model, sometimes it doesn’t create all mixes and channel assigment is wrong. I use AERT channel order, so ailerons should be on ch 1 and 5, ch 2 elevator, ch 3 rudder, ch 4 throttle.

![8991AF73-6406-44E0-8411-8B7D9A798DA8](https://user-images.githubusercontent.com/46519454/114131849-9f360000-9903-11eb-8caf-f9bd0b17e1ba.jpeg)
![92B178F0-3551-426E-89F9-CB7164DDCED1](https://user-images.githubusercontent.com/46519454/114131876-a6f5a480-9903-11eb-928f-57186e5cd6d8.jpeg)
![6A2F7A69-7F6B-46BC-900C-7A9F63E94834](https://user-images.githubusercontent.com/46519454/114131891-abba5880-9903-11eb-976d-1d250337bdca.jpeg)
![A3DCA213-66D5-4A73-9B6E-0245EEDBEC95](https://user-images.githubusercontent.com/46519454/114131999-da383380-9903-11eb-9495-a36b6d3df33a.jpeg)
![93C8D3DA-48A7-45E1-B4B2-A1C99C23068A](https://user-images.githubusercontent.com/46519454/114132015-e3290500-9903-11eb-9756-383d639047fd.jpeg)
![2C4FFED1-0E43-48D0-98FB-0699183687AE](https://user-images.githubusercontent.com/46519454/114132020-e623f580-9903-11eb-946e-59f5e44f8d52.jpeg)
![502967C7-CECB-446A-B85F-204CBF3FED00](https://user-images.githubusercontent.com/46519454/114132030-e9b77c80-9903-11eb-8f86-c0a208505473.jpeg)

**Comment by bsongis-frsky** [comment]
if you have 2 ailerons you will have AAERT
2 ailerons and 2 elevators AAEERT
I don't see what is wrong
If you want that Ethos assigns AERT in the first place, you could just create a model with one aileron, then add more ailerons in Model / Edit

**Comment by KAD370** [comment]
All systems I have used in past have same logic. Talking about futaba, multiplex and radios with opentx. They all have one aileron on 1. channel, in case of 2 ailerons, second is assigned to 5. channel.
I just can’t have throttle and other functions on different channels.

**Comment by bsongis-frsky** [comment]
It makes more sense to me to group the channels. It's a matter of choice. 

We could also offer an option for that (extra channels go to the end), but then what would be order if you have 4 ailerons and 4 elevators? AERTAAAEEE or AERTAEAEAE

**Comment by KAD370** [comment]
Hi,
Please check this:
https://www.multiplex-rc.de/Downloads/Multiplex/Bedienungsanleitungen/1-00096-bedienungsanleitung-royal-sx-16-elegance--en.pdf
pages above 105.
![30934D4A-6451-4A6D-91B9-DBD39A34A357](https://user-images.githubusercontent.com/46519454/114167479-44b29900-992f-11eb-9b93-2a9e0691f03f.png)
