### ISSUE TITLE
Models + bitmaps Copy X20S -> X10S Images not shown.

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#460]
I have copied the following folders from my X20 to my X10s express

> Models
> bitmaps/user

On the X10 all models are there, but no Images are shown.

When editing i see the model image is selected only not shown.

???

**Comment by MIKE-DAILEY** [comment]
I'm using the recommended 300x280 size on the X20 and recommended 180x166 for the Horus system and they work fine.

**Comment by Hobby4life** [comment]
Ok I will resize them., I knew something has changed last week. I thought it was to do with file size..
