### ISSUE TITLE
Progress dialog close button - does not result in a nil

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4600]
When using the lua progress dialog, pressing close will result in the dialog box closing,   but does not actually translate to a check from the main wakeup look receiving a nil state to know when the dialog is closed.

This should either return a nil, or possibly add Close handler to dialog boxes that triggers when they close?

**Comment by bsongis-frsky** [comment]
Already done in latest nightlies. And used there:

https://github.com/robthomson/RFSUITE/commit/d6447b8a4efc0d05670eb51f32c04eff146c1f80
