### ISSUE TITLE
Lua - get transport / protocol version 

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4601]
Would be very usefull to be able to get an additional status from getModule to determine the rf protocol in use.

For example:

Is it elrs
Is it sport
Is it a receiver type D16, twmx, 900 etc

This would allow some usefull functions like tuning msp speeds based on protocol and model.

**Comment by bsongis-frsky** [comment]
Already available: `model.getModule(...)`
