### ISSUE TITLE
X18S-Sim 1.5.15 MIA?

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4602]
Please, where is the X18S-SIM 1.5.15 Asset?

**Comment by Wolepo** [comment]
The Sim of the X18S is available
Greetings

**Comment by Richrfl** [comment]
I specifically want the version 1.5.15. I have all versions from 1 to 14 and that means I know where they normally are, which is not the case for version 15, therefore, if you know where that file is, please, let me know.

**Comment by Wolepo** [comment]
![Sim X18 1 5 15](https://github.com/user-attachments/assets/3e2738cc-cce8-4e70-a4fd-3f598f525423)

**Comment by Wolepo** [comment]
I have to correct myself. There are no simulators at all in 1.5.15. So either stick with 1.5.14 or use the simulators in Nightlies 1.5.16

**Comment by Richrfl** [comment]
Good. Now we are on the same page. Thank you.
I will try the nightlies, and see if the issue persists.
