### ISSUE TITLE
Edit ArduPilot parameters with ELRS LUA?

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#4604]
Hi @robthomson,

can ArduPilot parameters also be edited with the current ELRS LUA script? An entry for this appears in the list with TX and RX. Unfortunately, nothing happens when I click on Setup.

Does a setting have to be made in ArduPilot for this?

**Comment by robthomson** [comment]
I have no idea!

I don't believe this is even possible on the edge tx implications.. So most likely it's a case of the remote system having to enable the functionality.

**Comment by mawzthefinn** [comment]
Closing off as this is functionality that would need to be added in ELRS.
