### ISSUE TITLE
Low RSSI warning 2.4 only using multiple 2.4 receivers

### ISSUE THREAD

**Issue by Bobbysonic** [FrSkyRC/ETHOS-Feedback-Community#4607]
I running the latest firmware update 1.5.15 using Tandem X20rs radio.  I continually lose reception less than 30-50 feet away without being in the range check mode.  When I do a range check, I get a continual warning, VFR low warning, RSSI warning critical on all of my 2.4 receivers.  However, 900 mhz works perfectly with no signal loss even when in range check. I switched radios to make an experiment and used my X20S with the same receiver the problem with lost RSSI and VFR went away.  Is anyone else having the same problem?

**Comment by pmullen503** [comment]
My RS is fine on ACCST and Archer/Archer Plus compared to my X20S.  I'd send it in to be checked. Sounds like a bad 2.4G module or antenna.

**Comment by Bobbysonic** [comment]
I agree, kinda disappointed to have to send my new transmitter in for an examination so soon.

**Comment by Bobbysonic** [comment]
Sent radio in for service.
