### ISSUE TITLE
x20 fr sky transmitter

### ISSUE THREAD

**Issue by abrahamjohnny1069** [FrSkyRC/ETHOS-Feedback-Community#4608]
need help here just bought x20 frsky transmitter and when i go to special function to put example gear sound on a switch i dont c the option platrack or play value all i c is play vlice or vario ....and other stuff but not what i need to asign sounds on my switches ...
can any one tell me why ? i have a horus transmiter and it works just fine .....and know how it works 
my radio is up to date on ethos suit

**Comment by mawzthefinn** [comment]
Play Audio replaced the Play Track and Play Value functions, which are now Play Audio Actions in version 1.5

This is all covered in the current version of the ETHOS manual.

Note the audio file layout also changed for 1.5

**Comment by abrahamjohnny1069** [comment]
Ok if play audio replaced play track how do I get the sounds to play cause I can’t go get the wave file to play it there a link on how to do it ?Sent from my iPhoneOn Oct 7, 2024, at 8:39 PM, mawzthefinn ***@***.***> wrote:﻿
Play Audio replaced the Play Track and Play Value functions, which are now Play Audio Actions in version 1.5
This is all covered in the current version of the ETHOS manual.
Note the audio file layout also changed for 1.5

**Comment by mawzthefinn** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/raw/1.5/doc/%5BEN%5D%20Ethos%20User%20Manual%201.5.15.pdf

**Comment by abrahamjohnny1069** [comment]
I looked at Manual do I have to put my own wave files some where else !! My god so complicated !! In what file do I put the wave files in in order to play them on a google switch ?Sent from my iPhoneOn Oct 7, 2024, at 9:00 PM, mawzthefinn ***@***.***> wrote:﻿
https://github.com/FrSkyRC/ETHOS-Feedback-Community/raw/1.5/doc/%5BEN%5D%20Ethos%20User%20Manual%201.5.15.pdf

**Comment by mawzthefinn** [comment]
See page 41 of the manual for information on where audio files should be located

**Comment by abrahamjohnny1069** [comment]
Thank you you bin great help with what I read last night I figured it out !! 👍👍👍👍👍 super thank your for your the fast feed back 💪💪💪💪Sent from my iPhoneOn Oct 8, 2024, at 10:21 AM, mawzthefinn ***@***.***> wrote:﻿
See page 41 of the manual for information on where audio files should be located
