### ISSUE TITLE
Enhancement: Append Telemetry Name before RT value when using Special function: Play Value as option

### ISSUE THREAD

**Issue by djk817** [FrSkyRC/ETHOS-Feedback-Community#4613]
Telemetry Play value doesn't include the Telemetry Name before RT value under all releases. This would be helpful when playing RT Telemetry values and alarming using logic.

**Comment by mawzthefinn** [comment]
Put a play track action above the play value option and call a track with the name you want to play

**Comment by PeterGraz** [comment]
I agree with Adam on that.

**Comment by djk817** [comment]
Didn't know this was possible using "Play file" before "Play Value". Just tried it and it works great! Thank you! Mawz!  : )
