### ISSUE TITLE
LS stick asignment wrong

### ISSUE THREAD

**Issue by spiky1** [FrSkyRC/ETHOS-Feedback-Community#4617]
X20S with 1.5.16 and mode 2
Wenn setting up a LS and selecting the source by moving the left stick(gas) it selects the right stick(elevator). The other way around the same error selecting the wrong stick. LS uses the stick with the name in the setup screen

**Comment by philippe-warnotte** [comment]
Me too: Simulator V20 (version 1.5.16). Mode 2, Logic switch source, automatic detection, throttle-elevator reversed.

**Comment by spiky1** [comment]
This error is still present in 1.5.17
And not only in the LS but also in the mixers

**Comment by philippe-warnotte** [comment]
You're right, I noticed this in the mixers too. 1.5.17.
It seems we are the only two in the world seeing this problem. ;-)

**Comment by spiky1** [comment]
The German distributer has confirmed this error in the German Frsky Forum, so we are not alone 😅

**Comment by philippe-warnotte** [comment]
1.5.18 V20 Simulator: Bug NOT fixed !

**Comment by philippe-warnotte** [comment]
1.5.18 OK now. THANKS
