### ISSUE TITLE
Phasen abhängiger Offset 

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#462]
Aktuell ist es sehr umständlich einen Phasen abhängigen Offset einzustellen für die Segler Stellung Thermik und Speed.
Alle Klappen entweder etwas hoch oder runter über Offset sowie das Höhenruder entsprechend etwas hoch oder runter stellen.

Hierfür wird lediglich ein Phasenabhängiger Offset wert benötigt.

**Comment by Devil-IdT** [comment]
Hallo, Du kannst doch als Quelle für den Offset einen Kanal auswählen.
Den kannst Du mit beliebigen Kurven an die Flugphasen (nehme mal an diese Phasen meinst Du) anpassen.

**Comment by AlwinHaas** [comment]
Hallo Michael, genau das könnte man, aber das ist sehr umständlich. Einfacher ist es bei der. Bei der Gewichtung noch eine Eingabe mit Offset zu haben wie auch bei allen anderen Sendern. Damit man eine Phasenabhängigen offset Funktion mit Gewichtung hat. Zudem wäre es gut wenn die Gewichtung für jede Richtung einzeln einzustellen wäre ohne Kurve. GrußA. Haas-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 11.06.21, 09:19 schrieb Michael ***@***.***>:

   
  Hallo, Du kannst doch als Quelle für den Offset einen Kanal auswählen. Den kannst Du mit beliebigen Kurven an die Flugphasen (nehme mal an diese Phasen meinst Du) anpassen.

**Comment by Boxxxer64** [comment]
Would it be possible to set the offset andweighting and expo for each flight phase? That would make things a lot easier and clearer.
That you can Set Aileron, Flaps and Elevator in one Mixer.
Switchable via flight phase.

**Comment by Peschi90** [comment]
Why you dont use free mixer for the phases?

**Comment by AlwinHaas** [comment]
Because it where easier with offset in the main mixer. That make 1000 free mixer for every thing..

**Comment by bsongis-frsky** [comment]
Duplicate of #756 which is written in english
