### ISSUE TITLE
Brightness issues with the simulator

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#4623]
Dear Ethos Team, there is a problem with the simulator. If you happen to turn the brightness of the Sim all the way down in General, there is no way to correct this. This cannot be corrected even after a new installation.
Ethos 1.5.16

**Comment by strgaltdel** [comment]
1. in the moment you set brightness to zero, the "slider field" is still active and you can set the brightness "blind" to a value between 50..80%  (app in the vertical centre of the display slightly right)
2. in case you missed the opportunity,  the old IT rule will trigger: "backup is your friend". so you should copy your latest backup of the radio.bin file into the working dir.
3. no backup? then rename radio.bin. this will enforce the sim to built a new standard setting radio.bin on next start. of course, individual system settings will be lost...

maybe a hint in a readme file of the sim, that backups are always a good thing, even for sims, would be a good idea.

**Comment by Wolepo** [comment]
Or you can switch off the light in the room. Then you can recognise the controller. If you assign a potentiometer, it has often happened to me that the display goes dark. This is annoying because you then face the same problem.

**Comment by Skippydi** [comment]
> 1. In dem Moment, in dem du die Helligkeit auf Null stellst, ist das "Schiebereglerfeld" noch aktiv und du kannst die Helligkeit "blind" auf einen Wert zwischen 50..80% einstellen (App in der vertikalen Mitte des Displays leicht rechts)
> 2. Falls Sie die Gelegenheit verpasst haben, wird die alte IT-Regel ausgelöst: "Backup ist Ihr Freund". Sie sollten also Ihr letztes Backup der radio.bin Datei in das Arbeitsverzeichnis kopieren.
> 3. Kein Backup? Benennen Sie radio.bin dann um. Dadurch wird erzwungen, dass die SIM-Karte beim nächsten Start eine neue Standardeinstellung erstellt radio.bin. Natürlich gehen einzelne Systemeinstellungen verloren...
> 
> Vielleicht wäre ein Hinweis in einer Readme-Datei der SIM, dass Backups immer eine gute Sache sind, auch für Sims, eine gute Idee.

OK, backup is a good argument, but who backs up a simulator?
Renaming the Radio.bin has no effect because no new Radio.bin is created.
The problem is that uninstalling and reinstalling doesn't make any difference. If I use the SIM immediately after reinstalling it, everything is ok. But after quitting and restarting the SIM is dark again. Even if I readjusted the brightness beforehand.
See video

https://github.com/user-attachments/assets/6e883f17-090e-427b-a71b-dd6f34c598d8
