### ISSUE TITLE
Editing via "Balance channels" is inconsistent and can end with crash

### ISSUE THREAD

**Issue by MiRe-CZ** [FrSkyRC/ETHOS-Feedback-Community#4624]
**Last Sim 1.5.16**

Case 1: any channel (here CH4) is included by mistake into set of channels for balancing and selection is saved: 
<img width="269" alt="image" src="https://github.com/user-attachments/assets/5f4083c5-1e09-49ed-80a8-8cd62302481c">

Then the selection is edited and mistakenly selected channel is unselected, however the balance icon stays there and also information in the Balance curve row shows the channel is balanced:
![image](https://github.com/user-attachments/assets/d8dc5377-0a3c-4a72-918f-72693423367c)

Case 2: Intention is to delete the balancing function completely -> unselect all channels previously selected for balancing. This leads to crash. 

Clearing via Clear button in the Balance curve row runs w/o issue for both cases above.

Case 3: Previously configured balancing curves need change, however "Balance channels" shows only selected channel:
<img width="125" alt="image" src="https://github.com/user-attachments/assets/e59f13e5-576d-4713-9a1c-8588df58f6dc">
<img width="269" alt="image" src="https://github.com/user-attachments/assets/6668eb3e-f1e2-413c-9bae-ebdee8e3f0cf">

It is possible to select missing channel and curves for both channels are then shown, however after sim restart the issue is back

**Comment by bsongis-frsky** [comment]
> Case 2: Intention is to delete the balancing function completely -> unselect all channels previously selected for balancing. This leads to crash.

How do you do? I don't succed!

**Comment by bsongis-frsky** [comment]
I have understood and reproduced it. Corner case!

**Comment by bsongis-frsky** [comment]
The OK button will be disabled if no channel is selected for balance!

![image](https://github.com/user-attachments/assets/d1e58766-4183-4e82-a5ec-f367cf03e6dd)
