### ISSUE TITLE
X14 scroll issue in curves 

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4625]
![image-9](https://github.com/user-attachments/assets/36183097-e0c4-489c-912d-df743afab9ec)

Iin 1.5.16 it's not possible to scroll down in the curves page on the x14

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/d6e2dfac-6310-4502-9de1-6189b302bbf1)
