### ISSUE TITLE
Logical switch | ∆ | > X function

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#463]
Logical switch | ∆ | > X function

THE function | ∆ | > X used in the Telemetry / Altitude category always remains inactive, even if the condition is actively fulfilled.

Example: Detection of height difference 50m

**Comment by bsongis-frsky** [comment]
What is the interval?

**Comment by yak55** [comment]
Sensor is telemetry altitude 
If altitude changes up or low logical switch becomes high special function valve is announced
In open TX function is correct, not so with Ethos
Reason: one logical function with special function, every 50 meters information about altitude is announced, no matter if higher or lower


Von meinem iPhone gesendet

**Comment by yak55** [comment]
Foto logische Schalter


------ Originalnachricht ------
Von: "Bertrand Songis @ FrSky" ***@***.***>
An: "FrSkyRC/ETHOS-Feedback-Community" 
***@***.***>
Cc: "yak55" ***@***.***>; "Author" ***@***.***>
Gesendet: 14.06.2021 15:35:46
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Logical switch | ∆ | > X 
function (#463)

**Comment by yak55** [comment]
![screenshot-2020-06-15-21607](https://user-images.githubusercontent.com/85737356/121991753-9ac51200-cda0-11eb-8560-e01538b894a6.jpg)

**Comment by yak55** [comment]
![screenshot-2020-06-15-21607](https://user-images.githubusercontent.com/85737356/121991902-d9f36300-cda0-11eb-98ca-071019614688.jpg)

**Comment by bsongis-frsky** [comment]
Implemented in 1.0.10
