### ISSUE TITLE
1.5.17 pre-release behavior change in telemetry sensor getvalue()

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#4634]
It seems like in 1.5.15, if your Rx wasn't on yet,  You could still get the value of RxBatt.  The new behavior in 1.5.17 pre-release returns nil now.  Is that expected behavior and we need to now somehow check that we are getting telemetry the first time before getting a value of a valid sensor?

I noticed that my script is broken in 1.5.17 when it tries to get the RxBatt before telemetry has been received yet.

```
/scripts/F3K_TRAINING/472x191/viewbase.lua:42: bad argument #3 to 'drawNumber' (number expected, got nil)

42: lcd.drawNumber( f3kTextOffset + 4 + text_w*6 -3, text_h*4+4, widget.sensor_battery:value(), UNIT_VOLT, 2, RIGHT)
```

This behavior only happens (getting nil) if you haven't got telemetry the first time for the model.  If you get telemetry and then later lose it with telemetry lost, you can still query the getvalue() without it returning nil.

**Comment by bsongis-frsky** [comment]
Yes it has been done on purpose. It is not good to return a value, when none is available!

**Comment by agibson2** [comment]
Thanks for the confirmation of behavior.
