### ISSUE TITLE
Sensor lost at regular intervals on FrSky GPS module

### ISSUE THREAD

**Issue by crazybiker84** [FrSkyRC/ETHOS-Feedback-Community#464]
When using the FrSky GPS module (firmware GPS_V20201113) the Tandem X20s (Ethos 1.0.9 c4) loses the date and time sensors at regular intervals (approx. 5 seconds apart).

The error occurs with the Archer R10 Pro (FW-Archer-2.1.7).

**Comment by islandflight** [comment]
Yes noted the same too using the R8 Pro

**Comment by MichaelETHOS** [comment]
Yes the same with...s8r

**Comment by MIKE-DAILEY** [comment]
As  test try disabling the lost sensor alerts on the GPS time and date.

**Comment by crazybiker84** [comment]
In my case I deactivated the warnings for the date and time sensor because the regularly occurring warning bothered me. Other sensors (2x FLVSS, 1x VariH & 1x FAS150S) do not seem to be affected by the problem.

If I use the same model on my Horus X10s Express (firmware OTX 2.3.11) then there is no "sensor lost" warning.

**Comment by crazybiker84** [comment]
Seems to be OK with 1.0.10. Closed!
