### ISSUE TITLE
Bug in 1.5.17 : source selection is bugged on all new widgets

### ISSUE THREAD

**Issue by neuhausj** [FrSkyRC/ETHOS-Feedback-Community#4641]
When adding a new value widget, the source selection is bugged.
On an empty value, it only displays the categories "Special", "---" and "Analogs". 
When choosing one of these 2, all categories are then correctly displayed

After selection of one category, the display is correct.

This issue is reproductible in the simulator 1.5.17, with a standard Value or Line chart widget.

Here a video to demonstrate the issue:
https://github.com/user-attachments/assets/a6af1cd1-4cf9-44cb-ac20-f5d20710f5ba

The issue is worse with a Lua script (method "form.addSourceField") : 
https://github.com/user-attachments/assets/37894066-95e6-43d1-8928-2b0bd29b9006

**Comment by bsongis-frsky** [comment]
It's a roller, you have all choices available

**Comment by neuhausj** [comment]
I double checked against 1.5.15 and it is the same behaviour: 
* the scroll wheel is not working (only --- is selected)
* using the finger allow scrolling the list
* whenever it is first selected, the correct categories are displayed.

However, there is still a display bug when using the lua "form.addSourceField" method (duplicate "---", Timer and Telemetry categories): 
![image](https://github.com/user-attachments/assets/1be1f055-6dba-4025-8b39-3202f80795eb)
![image](https://github.com/user-attachments/assets/525e5395-2ae0-4ba3-a48d-7574156393a0)
![image](https://github.com/user-attachments/assets/62f31b38-4927-4d95-8330-153ba8310ea6)
