### ISSUE TITLE
Ethos Suite 1.5.10 does not find Ethos 1.5.18.

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4649]
I have the two latest releases of Suite (1.5.10) and Ethos (1.5.15). when I open the suite and connect the radio, does not indicate that there is a new release. Suite 1.5.11 is not fully released yet. Should I wait for the Suite to be released?

**Comment by mawzthefinn** [comment]
It will indicate the latest stable release. You can use pre-release versions, but they must be manually installed.

**Comment by Richrfl** [comment]
Well, apparently, Ethos 1.5.18 was released today, which is supposed to be a stable release. That is why I am confused.

**Comment by mawzthefinn** [comment]
1.5.18 is now showing in Suite 1.5.10

Suite 1.5.11 is still not showing

**Comment by Richrfl** [comment]
Well, I think I have a local problem because it doesn't show here.
![image](https://github.com/user-attachments/assets/cab248d7-9956-4a9a-8ac6-718c7572ded5)
![image](https://github.com/user-attachments/assets/5c5cb11b-3cf9-49f0-a6df-da2933174e34)

**Comment by mawzthefinn** [comment]
Have you completely closed Suite then relaunched it?

**Comment by Richrfl** [comment]
Yes, several times. Also, just in case the suite was not having access to the internet I checked that I could reach the web page and the latest manual from the Suite.

**Comment by Richrfl** [comment]
Would it make any sense to delete the Suite and re-install it from square one?

**Comment by mawzthefinn** [comment]
> Would it make any sense to delete the Suite and re-install it from square one?

Yes, that might help. I've now tried Suite 1.5.10 on both Windows and MacOS and it correctly showed 1.5.18 as available (tested on X18 and TWIN X-Lite)

**Comment by Richrfl** [comment]
Ok. I'll go for it

**Comment by Richrfl** [comment]
Did not work. May be it is related to the TX model???? I have one of the first versions of X18.

**Comment by mawzthefinn** [comment]
> Did not work. May be it is related to the TX model???? I have one of the first versions of X18.

So do I (first run with the gyro), and it's what I initially tested with so that's not it. 

Only thing I can think of is that it's a CDN node that hasn't synced yet with the latest version info. I'm pretty sure Git uses a CDN for worldwide distribution.

**Comment by Richrfl** [comment]
I do not have a clue of what CDN is, but I think you may be right. I think it happened before when I tried to update a new version too soon after the release. I'll try back tomorrow. Thank you for your suggestions.

**Comment by mawzthefinn** [comment]
CDN is a Content Delivery Network. It's a globally distributed front-end for websites to enable better performance in local regions. Very heavily used by sites that offer content downloads like Github. But the downside is that the content has to sync to all the regional nodes before it's available in those regions.

**Comment by Richrfl** [comment]
Thank you for the free education. I love to learn something new every day, regardless of how old I am.
