### ISSUE TITLE
LUA error after update to 1.5.18

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#4650]
The title says it all.

I am pretty sure that my code is being halted because of the following line and similar. Practically, the code was checking if there is any sensor available: -

if sensor.source ~= nil and sensor.optional == nil then

Used to work with 1.5.15.

Any ideas how to workaround please?

![Screenshot 2024-10-22 171317](https://github.com/user-attachments/assets/3eab0885-6ce7-4b97-8c87-db38bf8d0e86)

**Comment by i3dm** [comment]
All my Zavionix widgets are now broken on 1.5.18 as well because a sensor with no value now returns nil instead of 0.
why is this modification needed? this makes it so much harder for us lua devs to do our free unpaid job for the public :)

**Comment by RealTadango** [comment]
nil is better technically but it is a real shame this breaks all scripts.....

**Comment by robthomsonb4b** [comment]
I can see why this is done.  Nil is what the value is.

0 implies a value.

So problem is that if you get a 0..   then you can assume the sensor is valid.. and returning 0.  which is bad.

**Comment by i3dm** [comment]
> nil is better technically but it is a real shame this breaks all scripts.....

i agree, technically it makes sense, but its a huge burdon to handle, for practically nothing.
if i wanted to check the sensor state there are other ways to do it.

**Comment by bsongis-frsky** [comment]
I think that this change has been done on purpose because someone asked for it and it made sense at that time! Once that's said, display something or even doing maths with an invalid value is not really good!

**Comment by i3dm** [comment]
why go through all this trouble to ruin something that worked perfectly well before? what was so bad with a default value of 0 for an inactive sensor? in the old method anybody could poll sensor.state() !
this makes absolutely no sense to me @bsongis-frsky it ruined a perfectly good mechnism.
i would like to request going back to the old way pre 1.5.18. it was much better in my opinion.

**Comment by noamkrief** [comment]
> I can see why this is done. Nil is what the value is.
> 
> 0 implies a value.
> 
> So problem is that if you get a 0.. then you can assume the sensor is valid.. and returning 0. which is bad.


Respectfully disagree. Here are my reasons:

If we get a 0 we don't assume the sensor is live.
Even if I get a value of 1,000 (lets say for RPM) I also don't assume it's live.

We never assume a sensor is valid by reading its value.
Especially since the behavior of ethos is to keep the last value if it has been lost - even 10 minutes ago.

If we need to know if the data is valid, we are given a function for it. State()

not showing 0 for value() on a non live sensor just broke stuff and forcing of adding of unnecessary lines of code.

Again - we have been given state()

**Comment by robthomson** [comment]
So this is great to assume until you get a sensor that delivers a 0 or 1 or 2.

Takenfor example a sensor from a fbl that says.

Profile:  0
Profile:  1


So using my sensor I can determine if I am in profile 0 or profile 1.

But what if I am on profile 1... But getting a 0 because the sensor is invalid?

What I have seen is that the state command is slow. 


Very slow. 

State takes up to 5s to change.  Completely useless for checking if you are live or not. 

Why the delay... 

Because state says.. You where there.. But after some time.. You where not there..

**Comment by noamkrief** [comment]
@robthomson 
Yes in your example you are right. Then for the future this new behavior is better. More logical.

by the way - state() should return how many ms have passed since the last report.

**Comment by robthomson** [comment]
That would be nice if it did that.  Or does it?

**Comment by noamkrief** [comment]
@robthomson I think state() just returns true or false. Doesn't tell us how fresh the data is.

**Comment by salibaj2** [comment]
So, it looks that this is not going to change, and I am now stuck with a LUA that with the help of others have been building for months, as I am very new to all this.

How can I replace the: - 

if sensor.source ~= nil and sensor.optional == nil then

to get things going again please? 

I think that there is another issue, but have to fix this first.

As Lior said, I cannot understand why something working has been broken.

**Comment by robthomson** [comment]
Can you send a link to your code?

**Comment by noamkrief** [comment]
@salibaj2 
No, it's going to stay this way.

So wakeup is a big infinite loop right?
Split it into 2.
Step #2 inside the loop is the stuff you're doing now.
Step #1 is waiting for some telemetry source to come alive. Like RSSI.

Only when RSSI comes alive, then you can stop with loop #1 and resume forever with loop #2.

I see now @robthomson is offering to help you. He's a WIZ!

We will help you get through this. Don't worry :)

**Comment by Alex00101** [comment]
Happy to help as well. In the line "_if sensor.source ~= nil and sensor.optional == nil then_" I'm not sure what sensor.optional is and how is it related to the change in what source:value() now returns.

**Comment by EngelMT** [comment]
I can't say anything about the technical side of things.

As a dealer, I'm just pointing out that the many freely available Luas are some of the reasons to buy a FrSky transmitter. Those who write these Luas do it in their free time and don't get paid for it.

If these people are forced to invest many more hours in fixing the Luas because of changes like this, they will soon stop their work. That can't be in FrSky's interest.

**Comment by robthomson** [comment]
Lol.. I could spin that as..

If they where not happy to do code updates in lua.. Then they prob had already lost interest.     Code updates and regression are quite normal with development.

**Comment by bsongis-frsky** [comment]
A sensor could already return `nil` in 1.5.15 and before. Just try to remove the sensor which you are referencing in your Lua script and you will get EXACTLY the same error. `nil` should have been checked in previous version and should be checked in the current version. I just have fixed a bug which has been reported by a user, and I think that it is right.

**Comment by noamkrief** [comment]
@EngelMT It's a good change.
We are just bitching and moaning, because that's why us programmers are really best at doing :)

**Comment by i3dm** [comment]
> A sensor could already return `nil` in 1.5.15 and before. Just try to remove the sensor which you are referencing in your Lua script and you will get EXACTLY the same error. `nil` should have been checked in previous version and should be checked in the current version. I just have fixed a bug which has been reported by a user, and I think that it is right.

This approach is exactly the problem.
For you it's a bug fix.
For the community is a disaster.
And you are disregarding this matter.

Making a bug fix that impacts all the huge community just because it's technically correct without taking the impact to consideration is a big deal.

I already got 20 emails asking why frsky broke all Luas in their latest update.

**Comment by robthomson** [comment]
@i3dm .. its a 5 - 10 minute fix for you to do with a wrapper function.   Write the function.. search and replace.  job done.  you could push all your sensor checks into a single point that returns stuff as you want.

Fully appreciate that this has caused you some difficulty - but it is still better to fix the code in the long term.

Did you do any testing on your lua's while in the testing branch?   There have been multiple itterations from 1.5 -> 1.8.    

I have tested every one of my luas on each release.  Its an opportunity for end developers to test and feedback.

**Comment by i3dm** [comment]
Sorry but I'm not as proficient in Lua as you. It's my hobby. it took me 4 hours yesterday to fix 1 widget out of my 10.

Regardkess, no body is giving any meaning to the huge negative impact a change like this causes for end users. It's 
 terrible practice.

**Comment by robthomsonb4b** [comment]
@i3dm 

Feel free to reach out to me on discord and I can try assist you with your script. 

I am on the rotorflight & frsky discords.

**Comment by i3dm** [comment]
> @i3dm
> 
> Feel free to reach out to me on discord and I can try assist you with your script.
> 
> I am on the rotorflight & frsky discords.

Thank you
Is fb messenger ok?

**Comment by strgaltdel** [comment]
i'm with rob.

don't know right wording, in german language we have something like
"better to cut out dead wood" ("es ist besser alte Zöpfe abzuschneiden")

checked one of my largest widgets, several 1000 lines, a lot of telemetry.
Only one line had to be adopted, so no big deal.

only one thing to admit,
It might have been better to have a little bit more time for code adjustments
(propagate the change and wait for a revision).
At least I haven’t seen any indication of this in the last few weeks,
and unfortunately had no time to test the .18 nightlies, so i wasn't aware of the "issue"

**Comment by noamkrief** [comment]
Yes. I agree with @robthomson and @strgaltdel that ultimately we need to look towards future not the past.

BUT - there may have been a more elegant solution?
Imagine if they still allowed RPM:value() to spit out a zero (without RPM ever been initialized in telemetry).
But for the next 2-3 months of ethos updates, this would also spit out a lua error on the radio.

This way, people like @i3dm would get emails of people saying "Hey! my widget is working, but I got lua errors popping up"

This way @i3dm doesn't have to cancel dinner plans with the wife, play time with the kids etc to QUICKLY fix the widget that at least several hundred people use and rely on.

These has to be a phase of backwards compatibility. This was not a "normal bug" that can just get "fixed".

**Comment by i3dm** [comment]
Agreed. Pushing this change violently out the door without a build up period is just bad practice. 
First, It makes no sense to obligate  me do 50 hours of work to fix prior perfectly fine codes written for hundreds of hours in my own free time. 
And above all, it makes no sense to abuse YOUR USERS and kill all their widgets without allowing some adaptation period.

If you must return a nil value then at least make it print an error but continue running. And not crash the entire widget.

**Comment by bsongis** [comment]
I am very sorry for the dinner with the wife and the 50 hours extra work! I didn't know it would take so much time! 
Again, this check against `nil` should have been added before. The function may return `nil` since the very beginning!

**Comment by i3dm** [comment]
What it may have done is not the issue.
Don't you. See the problem this causes for the users who don't care at all about nil values?

You are killing existing functionality for hundreds or maybe thousands of users.
How is this not an issue being considered?

**Comment by RealTadango** [comment]
The main issue is that people with very good intensions but limited programming skills build awesome stuff that get's adopted by many users. This is good and bad at the same time. Any code that is wrong but works might be impacted by an update that corrects a bug. How breaking this update is, is very hard to estimate by the FrSky team. Also nobody has reported this issue before the .18 update got released right? Maybe another testing / validating / releasing strategy could help...... And dev's of widely used Lua's should test with pre-releases more often i guess.

**Comment by bsongis** [comment]
1.5.16 hasn't been released thanks to the Lua devs who reported issues
Then the same for 1.5.17!
And no-one reported anything for 1.5.18 after some time. I didn't even imagine there would a breaking change (which really is not!)

**Comment by i3dm** [comment]
Then we have to agree to disagree.
As an amatuer developer who invested hundreds of hours for free Lua scripts for the community, it's a disaster move for me and for the end users who now broke their perfectly fine radios upon updating their fw. 

If you don't get it by now I guess there isn't a lot more that I can add.

**Comment by salibaj2** [comment]
> Can you send a link to your code?

[robthomson](https://github.com/robthomson)

Trying to find your email address to no avail.

**Comment by robthomson** [comment]
You can find me on frsky discord..   Or maybe Facebook frsky groups.

**Comment by robthomson** [comment]
All up.. It's a change that has an impact.

Maybe @bsongis frsky should look towards a developer announcement / mailing list.

I suspect however that people will not subscribe..    Not follow. New release announcements etc etc.

99% bet that even if this point had been listed on the release notes - the same issue would occur.

Hobby developers don't bother too look and test there stuff - over a release cycle of 1.5.16-1.5.18.    This cycle was over a month.

I new about it.  Because I test my stuff all the time.   Joe average..  He will wait for it to break the complain.

**Comment by i3dm** [comment]
With that I agree.
People like me who don't work in this industry don't test all the time. I have a full time job aside of modeling and it's my hobby. did what I did with a huge effort in favor of the frsky community. And the pilots love it and use it vastly. 

Whenever frsky takes a decision to make a change they should consider the public impact and in this case it is obviously huge.
Therefore it should be done better. And much more cautiously.
I'm positive the average Joe pilot who couldn't care less about nil values will become very upset once he finds frsky fw just broke his awesome Lua. And each and every one of them will find out the hard way, as soon as they load 1.5.18 and it stops working. I know I'd be pissed. 

I'm sure frsky likes happy users of their system. Therefore it's unimaginable that such a change will be done in a way that will surprise the masses.

**Comment by robthomson** [comment]
This wrapper likely will resolvce stuff:

```
local function getValue(sensor)

	-- catch no sensor provided
	if sensor == nil then
		return 0
	end

	local v = sensor:value()
	if v == nil then
		return 0
	end

	return v

end
```

**Comment by i3dm** [comment]
Rob your wrapper works great! Thank you! You saved the day. 

Of course all users will still have to update their widgets.
