### ISSUE TITLE
Issue with lua 1.5.18

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#4652]
Hi, new issue with Lua script with 1.5.18 Tandem xe
![IMG_20241023_090306](https://github.com/user-attachments/assets/2688bbcb-d613-4be1-b009-62cdfed29117)
![IMG_20241023_090142](https://github.com/user-attachments/assets/6f6ae124-e1c8-45dc-93e7-48ac02a926e8)

**Comment by bsongis-frsky** [comment]
This widget should test the `nil` value.

**Comment by robthomson** [comment]
This is a simple wrapper for those who are not able to work out how to test nil and what the old method

```
local function getValue(sensor)

	-- catch no sensor provided
	if sensor == nil then
		return 0
	end

	local v = sensor:value()
	if v == nil then
		return 0
	end

	return v

end
```

All up.. test for nil.  Its the right thing to do!
