### ISSUE TITLE
Small localization issue with "telemetry active"

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4659]
(1.5.18)

This looks not correct to me. It should probably say "Telemetry":

![image](https://github.com/user-attachments/assets/7ccadb5d-e827-4636-bf99-a13da743014b)

The reason is that it probably shares the same resources with this one:

![image](https://github.com/user-attachments/assets/c872fa9d-5528-451d-b152-07e6cc5397e1)

**Comment by bsongis** [comment]
Not exactly. When used it Category it works as switches: when the sensor receives the Telemetry it returns True and when not it returns False (like any logic switch)

**Comment by Wolepo** [comment]
Here is just one example: if you use the telemerie as a source in an LS, you have to enter a value under which circumstances it becomes TRUE. However, if you use this as a category, it becomes active immediately if RSSI is present, i.e. not ‘---’, but e.g. 67
![Telemetrie aktiv](https://github.com/user-attachments/assets/8314ceef-92db-4d9d-9845-5d4872e448b1)

**Comment by azaz44** [comment]
Thanks guys, I didn't know such functionality exists. It's actually pretty cool 👍
Closing the issue then
