### ISSUE TITLE
INActivity Warning

### ISSUE THREAD

**Issue by Beastyboy80** [FrSkyRC/ETHOS-Feedback-Community#466]
During  flying , the Transmitter InActivity Warning switch on .

**Comment by MIKE-DAILEY** [comment]
This is caused by not having "sticks" selected in Wake Up for the Display.  Without "sticks" selected they cannot reset the inactivity timer.  There is another issue open on this but cannot find it now.

**Comment by jfint** [comment]
woops and I just created a duplicate also, and guessed they cause as well.

**Comment by jfint** [comment]
The subject of this report should be something along the lines of  "Separate inactivity warning from display wake-up for stick input."  Is that correct @MIKE-DAILEY ?

**Comment by MIKE-DAILEY** [comment]
Something like that.  I'm pretty sure there is already an issue open on it.

**Comment by TWSreviews** [comment]
It is embarrassing, 
I was flying today and my radio started alarming informing me the system has been idle, while I am flying. Much to the amusement of all my colleagues. This needs to be resolved.
Screen dimming is great but should know you are fling before alarming idle. As said above it should be linked to the sticks for idle alarming.
