### ISSUE TITLE
Ethos 1.6.0 system/stick mode formatting error

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4660]
Ethos 1.6.0 system/stick mode formatting error

Formatting error see photo

Greetings Eugen

![IMG_6578](https://github.com/user-attachments/assets/3a4070d7-005f-4a87-a258-b9e7330fc63c)

**Comment by bsongis** [comment]
Already !

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/2529bf39-37d4-46bc-822c-d5b5a91d4738)
