### ISSUE TITLE
1.5.18 - lua file path error

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4661]
X20RS
ethos v1.5.18

local imagePath = "/scripts/RDT/img"
if (wallpaper_mask == nil) then wallpaper_mask = lcd.loadBitmap(imagePath.."/wallpaper_mask.png") end

if the script is in the radio memory (and system menu set to scripts - Radio), the image doesnt load.
if the script is in the SD card (and system menu set to scripts - SD) the image loads fine.

**Comment by bsongis** [comment]
You shouldn't use absolute paths

**Comment by i3dm** [comment]
> You shouldn't use absolute paths

Sorry I'm not sure what that means.
And these worked great for 3 years up to 1.5.18.

What is a non absolute path and how do you suggest to implement  it?

**Comment by bsongis** [comment]
If your script is inside "/scripts/RDT/" then just load "img/wallpaper_mask.png"
It worked great for 3 years, but at the price of these issues #4374 #4572

**Comment by bsongis** [comment]
Also BMP files are better than PNG, but that's a minor issue.

**Comment by i3dm** [comment]
> If your script is inside "/scripts/RDT/" then just load "img/wallpaper_mask.png" It worked great for 3 years, but at the price of these issues #4374 #4572

Just tried this and it fails as well.

**Comment by i3dm** [comment]
if (wallpaper_mask == nil) then wallpaper_mask = lcd.loadBitmap("/img/wallpaper_mask.png") end

002865 main.lua:1341: bad argument #3 to 'drawBitmap' (Bitmap expected, got nil)

**Comment by i3dm** [comment]
if (wallpaper_mask == nil) then wallpaper_mask = lcd.loadBitmap("img/wallpaper_mask.png") end

works.
but dont know if it will fix the issue on the X20RS internal memory as i dont have it here.

**Comment by bsongis-frsky** [comment]
No reason.

**Comment by i3dm** [comment]
No reason for what?
