### ISSUE TITLE
AP plus sr10+  not possible to upgrade to 1.0.11 from 1.0.9

### ISSUE THREAD

**Issue by ilioSS53** [FrSkyRC/ETHOS-Feedback-Community#4663]
Hello,

My x20s updated to 1.5.18 eu
all is up to date.

Now I can,t update my Archer Plus SR10+   from 1.0.9  to 1.0.11
The receiver Stab LUA is not able to switch on/reset/stabilising/quick mode
Update the 3.0.0 LUA stab version uploaded to the TX.
On info screen  archer plus sr10+  version 1.0.9  this is not possible to upgrade to 1.0.11  which to my understanding is nessesary.
A complete new model is programmed  resister is possible BUT the binding not.

The only way to have the Archer plus SR10+ working is with script AP_8CH_1.0.10.frsk  
OTA AP_SR10+_R10+_1.0.19.frsk   fails  the red led on rx came on.

Where am I going wrong.
The manual gives TD/TW SRX stab  on stab screen   this I have not seen  only Archer SRX stab

Any help is very much apreciated.

**Comment by Wolepo** [comment]
Hello,
You can only update to 1.0.11 directly via cable using the S.POT connection on the transmitter. You will then also need the LUA 3.0.0
Greetings from
Wolfgang

**Comment by ilioSS53** [comment]
Hello again Wolfgang,
I prepared the cable and update strait away.
Many thanks.
Kind regards,
Theo

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ilioSS53** [comment]
Hi Wolfgang,
Thanks for your swift reply.
I will follow your recommendation.
Greetz

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ilioSS53** [comment]
Solved.
By exelent help from Wolfgang.
