### ISSUE TITLE
900 Mhz RSSI signal bar keeps flickering on X20 pro radio

### ISSUE THREAD

**Issue by BoltTed** [FrSkyRC/ETHOS-Feedback-Community#4665]
My setup is a 2.4GHz SR8 Pro as main receiver, with 900Mhz receiver R9Sx as redundancy backup. After connecting the battery to my plane, everything is fine, all surface working correctly, accept the 900Mhz RSSI bar on my X20 Pro radio keep flickering going from no signal to full strength signals ( from 0 bar then 4 bars then 0 bar... on and on).  The 2.4 RSSI bar signal is stable. I didnot see this in earlier release of 1.5.13.

My setup as follow on my EDF Jet:
X20 Pro Firmware ver. 1.5.18 FCC
TD-ISRM Pro Hw: 1.0.3  FW:1.1.14
Archer SR8 Pro -  HW:2.2.0 FW:2.1.14
R9SX -  HW:1.1.1 FW:1.3.3

Thanks.

**Comment by 4qr1hu9n7** [comment]
I had the same issue. To correct it.I rolled back the firmware.

**Comment by doppleganger53** [comment]
This is a bug in the 1.1.14 pro module firmware, see here: https://github.com/FrSkyRC/RF_Feedback_Group/issues/43

Fixed in beta module firmware, but not in stable release yet. I rolled the module firmware back to 1.1.13 but run 1.5.18 ethos with no issues.

**Comment by mawzthefinn** [comment]
Closing off here as a duplicate, please continue discussion over in the RF Feedback Group
