### ISSUE TITLE
Suite 1.5.11 does not find Ethos 1.5.18 for TX update

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4666]
I had this issue before when Ethos 1.5.18 was released and following a suggestion from mawzthefinn, I decided to wait for the CDN to synch. To my surprise, when I opened the new Suite 1.5.11, I found the same problem. Suite is still telling me that my TX X18 1.5.15 is the last version . Can someone check it out please?

**Comment by Dsrenger** [comment]
It worked fine for me yesterday. 

Suite showed automatically the update to suite version 1.5.11 and afterwards (did not check before) it showed as well 1.5.18 without issues.

**Comment by Richrfl** [comment]
Well, it looks like I am the only one having this issue. I will have to update 1.5.18 manually. I was not able to make this right by doing some tricks like disabling the firewall protection or re-booting the pc. It is like my Suites (10 and 11) do not want to access the internet for unknown reasons.

**Comment by Richrfl** [comment]
Not surprisingly, Suite is telling me that my FW is greater than the latest release. Can someone give me a lead on why my #### pc is blocking the communication between the Suite and the internet? I am running Windows 11

**Comment by mawzthefinn** [comment]
Hmm, try running Suite as Administrator.

It could be that it's not writing the components.json file (the file that tells it what versions are current) when it downloads them. That could be because Administrator owns the previous version of the file.

I know of at least one other user with the same issue, but we've not been able to duplicate it on any test system.

**Comment by mawzthefinn** [comment]
Question - Are you running WIndows 10?

The other use I know of had the issue only on Windows 10, it worked correctly on his Windows 11 system, and Suite 1.5.9 worked correctly on his Windows 10 system after he rolled back to that version (1.5.10 and 1.5.11 didn't work).

**Comment by Richrfl** [comment]
I am running W 11. Also, I tried running it as an administrator and am still getting the same results. I concur Suite 1.5.9 did not present this problem.

**Comment by Nicholas-Luoyi** [comment]
> I had this issue before when Ethos 1.5.18 was released and following a suggestion from mawzthefinn, I decided to wait for the CDN to synch. To my surprise, when I opened the new Suite 1.5.11, I found the same problem. Suite is still telling me that my TX X18 1.5.15 is the last version . Can someone check it out please?

You should choose Github as the update server in the Suite settings page.

**Comment by Richrfl** [comment]
This seems to be a good idea to try. Can you tell me where do I find Suite's settings page? I don't see anywhere in the Suite screen where there is a settings option. May that be in a config file or something alike?

**Comment by mawzthefinn** [comment]
Suite Settings is the second last option on the left menu. You likely will have to scroll the left-side menu down to find it.

**Comment by Richrfl** [comment]
You guys hit right on the nail!!
Thank you very much.
