### ISSUE TITLE
Problem with Bluetooth trainer 

### ISSUE THREAD

**Issue by ianda217** [FrSkyRC/ETHOS-Feedback-Community#467]
I was setting up a headtracking unit on my X20S  running release 1.09 candidate 2 using the PARA Bluetooth trainer and found that the aileron stick input was being ignored by the Tx.   I checked on other models and on almost all of them (excluding only flying wings), the same situation existed.   On many of them, the elevator stick was also ignored.

I switched everything off and then back on and everything was working again - until I reconnected Bluetooth at which point I lost input from the right stick again.   This time, I turned only Bluetooth off and then back on and the stick worked correctly.

This was not a one off as it is repeatable (and scary).

**Comment by Hobby4life** [comment]
How did you configured the respective trainer channel? ADD or REPLACE?

**Comment by ianda217** [comment]
With great difficulty.

First of all, the model is operated through a Matek flight controller 
via an R9 Slim+OTA receiver.   I set the head tracker up to use channel 
5 for pan and channel 6 for tilt.   Both channels were set as active 
condition to be switch B "not up" and function type Addition.

There seems to be no access to channels 5 through 8 in the trainer 
section so I could only get the head tracker to work by reassigning 
trainer channels 1 and 2 to be 5 and 6.   This worked ok except that 
when I operated the head tracker, the rudder and elevator also operated 
so I had to set the mode for these two channels to OFF in the trainer 
section to stop these controls.

Having written this, I can see areas where there are conflicts but I 
welcome your advice.

Regards,

Ian Dawson

------ Original Message ------
From: "Hobby4Life" ***@***.***>
To: "FrSkyRC/ETHOS-Feedback-Community" 
***@***.***>
Cc: "ianda217" ***@***.***>; "Author" 
***@***.***>
Sent: Friday, 11 Jun, 21 At 19:38
Subject: Re: [FrSkyRC/ETHOS-Feedback-Community] Problem with Bluetooth 
trainer (#467)


How did you configured the respective trainer channel? ADD or REPLACE?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/467#issuecomment-859769054> 
, or unsubscribe

**Comment by Hobby4life** [comment]
I see, I also adressed the the lack of only 4 channels can be a real problem.
We have to get more channels available. 

#issuecomment-859770614

**Comment by ianda217** [comment]
Excellent.   I was out today to try flying with the head tracker for the first time and when I activated the switch, the ailerons stopped working.   I got the model back by doing return to home and then cutting the throttle on the way back and gliding it in.   Hopefully, activating the additional channels will resolve all this.
