### ISSUE TITLE
1.5.18 lua:  probable changes in handler processing can crash widgets (or their configs)

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#4670]
To put this issue into perspective right from the start:
I'm sure this only affects a very small percentage of users.
The user would have to be using a Lua script that takes a lot of runtime in the create handler, and in read or write handlers, he uses variables or methods/functions that are only initialized in the create handler.

**rough description:**

today, i finally found time to migrate from 1.5.13 to 1.5.18.
as mentioned before, the "nil" issue in my case was more a no-brainer, on sim all  looked good without any error after minor changes.

after updating tx, identical setup as on sim caused a sequence of lua errors (and wiped out widget configs).

**background info:**

- 1: until now i was under the impression that on very start of a widget, at first the create handler is executed, only after completion other handler were accessible

- 2: so i'm used to load several lib-files in create handler
(some graphics functions, io functions, some classes etc.. which are used in several of my widgets)
these methods and functions can be used in other handlers later on 

- 3: the read(widget)  handler is dependent on / processes some variables of the typical "widget"-variable structure initiated in create handler

this was operational since first days.

**Problem details:**

- on very first start i could see several errors, because the widget-variable structure seemed to be nil on 1st loop of read(widget) handler
- several errors because functions declared in create-handler loaded libs were nil, not initialized on first read loop

This led me to assume that something in the behavior (due to new performance, dependencies, triggering handlers, or startup order) must have changed compared to before. (remember: 1.5.18 sim doesn't show this behavior)

To verify, I used the following quick & dirty workaround:

The libraries previously loaded in the create handler are now initialized in the widget's header section.
To allow enough time for this initialization when the transmitter starts, I created a quasi-empty model template to start the transmitter.
If the transmitter starts with an initial "dummy" template and thus can process all the header sections of the detected Lua scripts, switching to a second template works without issues. The Lua scripts used there (and their read/write handlers) run without problems, 
Create handler now is "more lean" and so widget variables defined in the create handler are initialized on first read loop.
However, if the transmitter starts directly with this second template, the above-mentioned issues arise again. Since the read handler is not processed correctly, it leads to subsequent issues (in this specific case, entries in the widget configuration are lost).

**Suggestion:**
Whatever the root cause, in my opinion, the behavior would be improved if, when a template is called, all other handlers can only become active once the create handler has successfully completed.

If the current behavior is intended or necessary for technical reasons, please let me know, and I’ll need to revise the concept. It’ll be a lot of work, but that’s just my own misfortune.

**Addendum:**
Well, after reaching a usable state with the workaround, I was able to experiment a bit with an active/switched on model (with a lot of telemetry used in widgets).

**i'm speechless - This is exactly the speed I had hoped for.**
Thank you, and great job on finally identifying the root cause (apparently related to the chDir issue) that was causing the performance slowdown.
This is the same performance gain I observed when switching to dev mode in several releases ago!

regards
udo

**Comment by Alex00101** [comment]
Thanks,  I'm going to test this.  My main widget has a very similar structure and logic to what you describe except that my wakeup handler explicitly checks for the create to successfully finish and read/write do not use storage (I have a reason to use filesystem instead) so I'm manually triggering read at the end of create. I'll retest on the TX

**Comment by strgaltdel** [comment]
OK,

It turned out that the error messages and the functional workaround had led me down the wrong path.

It wasn’t a problem with the create handler itself but rather with absolute pathnames in my libraries, which prevented them from being fully loaded during create, but no error was displayed.
As a result, the create handler probably stopped, leading to subsequent issues.

This could likely only happen because I use an SD card on the X18—so now one has to be more careful with pathnames!
