### ISSUE TITLE
Independent gyro bank switch

### ISSUE THREAD

**Issue by mgs192** [FrSkyRC/ETHOS-Feedback-Community#4674]
I´m using the rudder output on bank 2 as a steering gyro.  This is turnned on/off from my gear switch (ch14).  Would it be possible to have a separate channel(switch) for bank 1 so I can turn stabilization on/off during flight for this bank only?  A channel selection on the lua script bank page would be great, (ch14 as default, but give user the option to select a diffrent channel for each bank)

**Comment by mawzthefinn** [comment]
This should be posted over at the RF Feedback group, as this is a receiver firmware limitation:

https://github.com/FrSkyRC/RF_Feedback_Group/issues

Please post this issue there and continue discussion under that issue.

**Comment by noamkrief** [comment]
@mawzthefinn 
Bertrand has the ability to move them to the RF section. I assumed you do too?

**Comment by mawzthefinn** [comment]
@noamkrief I do not, I'm a regular user over in the RF Feedback group, unlike here. Otherwise I'd just move them.

**Comment by mawzthefinn** [comment]
Closing this off as it's been created in teh RF Feedback group
