### ISSUE TITLE
Add Ability to move/organize/re-arrange Models in Model Manager

### ISSUE THREAD

**Issue by plesogor** [FrSkyRC/ETHOS-Feedback-Community#4677]
Add Ability to move/organize/re-arrange Models in ETHOS Model Manager

**Comment by plesogor** [comment]
some drag and drop move models, or right touch hold / up\down left/right move models, or move mostly recently used top 5 models to the first row for examples.

Add some nesting structure for model types / folder structure. Airplanes / Helicopters / Drones / Other ..  

Main page shows a "Model Type" and then Models which are able to be re-arranged and/or allow top 5 recent models on first row.

Just some ideas that I think might be useful.

**Comment by mawzthefinn** [comment]
Duplicate of #3060 

Please continue discussion there
