### ISSUE TITLE
no slave output of throttle from master on wired trainer connection

### ISSUE THREAD

**Issue by oOEvoRobOo** [FrSkyRC/ETHOS-Feedback-Community#468]
I have setup a wired trainer setup, with X20 being the master and other transmitter being the slave(student). On the trainer screen all inputs are coming through from the students box. They are all set to 'Replace' & 100%. However on the outputs, when in student mode, there is no throttle output. Elevator, Aileron and Rudder are all fine, but the throttle output, stays with the master box (X20). Firmware 1.0.8

**Comment by darkernoise** [comment]
I was coming her to log the same defect. I can confirm that even as of 1.0.9 RC4 that this issue persists.The "Slave" signal is visible and registering on the X20S (as master) display bar at the bottom of the Trainer setup.   However, the throttle channel is never transferred to the slave controller.  Thus, no matter what you do, the throttle remains under X20S control, which makes the trainer function basically useless. Please rate this with a high priority as trainer functionality is critical.

**Comment by oOEvoRobOo** [comment]
This is still an issue on 1.0.9 RC5. 
This bug has basically rendered the transmitter useless to me. As I am learning to fly and require the buddy feature working at the moment to be able to fly.

**Comment by Hobby4life** [comment]
Correct same here.

Also more channels are needed: #493

**Comment by Erazotropa** [comment]
I Noticed the same problem too
.
Would be nice if really important things that already exist are fixed first, instead of "funny" unnecessary things are added like bye.wav's and Splash screens etc. 👎

**Comment by oOEvoRobOo** [comment]
Still an issue in the official release 1.0.9. 

https://user-images.githubusercontent.com/85752475/122182244-029f5980-ce82-11eb-9969-7b355d899ed7.mp4

**Comment by Hobby4life** [comment]
Correct still not fixed.. I gues the whole trainer system has to be re-done for many reasons.
As It is now it is not useable in any way.
