### ISSUE TITLE
LUA: retrive more information about the model

### ISSUE THREAD

**Issue by frankiearzu** [FrSkyRC/ETHOS-Feedback-Community#4684]
I need to retrive more information about the current model.

**1.  info about the output channels.**
- Channel name
- Direction: Normal/Reverse
- Min/Max percent
- Center/Subtrim
- PWM center

Propose API:   model.getOutput(i)   where "i" is the channel number..  similar API to model.getCurve(i)

![image](https://github.com/user-attachments/assets/0d9657be-b758-48ff-bc61-7f5550995cd4)

**2.  Current module Information** 
- Module type (Multi-Module, CRFS, etc)  .. i think is already there by model.getModule()
- Need to get the "options" for a module..  specially for me if the External multi-module is doing channel mapping or not.
![image](https://github.com/user-attachments/assets/17cece0d-0f30-4bfe-ac11-f22feafe7b37)
![image](https://github.com/user-attachments/assets/14172b9a-5ba1-4db0-859b-f58d2db587e3)

The Options comming from the /scripts/multi/main.lua:
![image](https://github.com/user-attachments/assets/f667297e-f82a-4fc7-a586-7fd360e067b9)
![image](https://github.com/user-attachments/assets/cafa9e5f-8499-4a88-989c-8903a41bc556)

**Comment by mawzthefinn** [comment]
One thing to note, like Spektrum (and unlike OTX/ETX), you should be able to get the core surface mapping from the function mixers. You still obviously need the Outputs portion as well for Forward Programming.

**Comment by frankiearzu** [comment]
@mawzthefinn You are correct... at minimum i need the outputs so that i can display the name to make it easy to select channels in Forward Prog..  Specially if the MM is mapping from AETR->TAER.    Ail:Ch1->Ch2,  Ele:Ch2->Ch3,  Thr: Ch3->Ch1
My plan is still to port the UI where you set the what Ch is use for each surface (Wing and Tail settings/mix)..     Later on, if i can get all that info from the Radio will be great.  Still could be dificult to understand the intent of a mix, specually the not usual ones..VTail, Taileron, Delta, two Ail, Canard, Canard-Aileron, etc.

**Comment by bsongis-frsky** [comment]
Ready for the next 1.6.0 nightlies!

**Comment by frankiearzu** [comment]
Verified and working as expected.
The only thing is that "module" class is not documented in the LUA doc, but was able to inspect its methods/functions via code.

**Comment by bsongis** [comment]
The doc should be fixed now. Also I have improved it a little bit, see the release notes!
