### ISSUE TITLE
X20rs encoder

### ISSUE THREAD

**Issue by stubugs** [FrSkyRC/ETHOS-Feedback-Community#4687]
When adjusting a setting with encoder wheel say sound file as I move thumb across to press centre button it's too sensitive  on encoder wheel and easily goes to next item as I press center button moving thumb across even carefully 
This is not a problem with x20s

**Comment by pmullen503** [comment]
Yes! I stuck a 1.5 mm disk on the button to raise it up above the encoder wheel. It helps but the encoder wheel spins much easier than an X20S or X18.

**Comment by stubugs** [comment]
its not just me then im glad maybe make disk less sensitive on x20rs

**Comment by RealTadango** [comment]
The X20RS has a TERRIBLE encoder compared to the X20S... a very big mistake. Sadly i cannot swap them because the design is very differently. This almost made me sell the X20RS and buy a X20S again.....

**Comment by pmullen503** [comment]
> The X20RS has a TERRIBLE encoder compared to the X20S... a very big mistake. Sadly i cannot swap them because the design is very differently. This almost made me sell the X20RS and buy a X20S again.....

Did you want to swap the entire keyboard or just the encoder? If I could get the specs, I'd attempt to solder in a new component.

**Comment by stubugs** [comment]
I'd solder a new one in if I knew what spec they were

**Comment by ftc2629** [comment]
I am with you. This is indeed a big issue. I would say 8 of 10 times I choose the wrong item of a list!

**Comment by stubugs** [comment]
Or if the sensitivity could be altered with firmware so you have to spin more than just a touch to get it to move what ever on the screen like a dead area before it starts to move

**Comment by RealTadango** [comment]
> > The X20RS has a TERRIBLE encoder compared to the X20S... a very big mistake. Sadly i cannot swap them because the design is very differently. This almost made me sell the X20RS and buy a X20S again.....
> 
> Did you want to swap the entire keyboard or just the encoder? If I could get the specs, I'd attempt to solder in a new component.

I removed the one from my X20S but it is very different and wont fit.

**Comment by stubugs** [comment]
I've ordered a x20 key board so I can solder encoder of that onto x20rs

**Comment by RealTadango** [comment]
> I've ordered a x20 key board so I can solder encoder of that onto x20rs

That is what i tried, does not work.

**Comment by stubugs** [comment]
Not the whole board just encoder

**Comment by RealTadango** [comment]
Yes, that is what i tried! It does not work, totally different design in height ect. There is a reason the new encoder is crap, it is smaller.

**Comment by stubugs** [comment]
It needs the firmware adjusting so it's  not so sensitive then when not being spun then

**Comment by pmullen503** [comment]
> Yes, that is what i tried! It does not work, totally different design in height ect. There is a reason the new encoder is crap, it is smaller.

Did you get the dimensions by chance?

**Comment by doppleganger53** [comment]
X20s was way better, hopefully a software filtering fix can be made.

**Comment by stubugs** [comment]
How can this problem be closed when it has not been addressed in any way or form

**Comment by RealTadango** [comment]
> How can this problem be closed when it has not been addressed in any way or form

Because it is an duplicate, see the linked issue from strgaltdel. This item is still open

**Comment by bsongis** [comment]
I have just received the X20RS, indeed the rotary encoder is very light, I hope I can add some filtering

**Comment by stubugs** [comment]
Thankyou if you need me to test it on my x20rs I'd gladly do so

**Comment by pmullen503** [comment]
> Thankyou if you need me to test it on my x20rs I'd gladly do so

Me too. Flying season is pretty much over here so I'd be happy to test any software fix as well.

**Comment by bsongis-frsky** [comment]
Who can contact me on Discord to try a different firmware for X20RS?

**Comment by stubugs** [comment]
I would be willing to try 
My email 
Stubugs@gmail.com

**Comment by bsongis-frsky** [comment]
@stubugs are we good / better?

**Comment by stubugs** [comment]
10 times better /good
Thankyou
Stuart

**Comment by stubugs** [comment]
Its 10 times better no accidentally movement of encoder wheel 
Thankyou

**Comment by bsongis-frsky** [comment]
OK. I will pre-release 1.5.20 with almost nothing but this.

**Comment by pmullen503** [comment]
> Who can contact me on Discord to try a different firmware for X20RS?

Can you send it to pmullen503@gmail.com?

**Comment by BladeScraper-Designs** [comment]
If possible please add this to the 1.6 nightly?  I'm using my RS for 1.6 testing and could use this fix as well as I can't revert back to 1.5 right now.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/fc4cf1d4-8486-4130-81a3-a8faf33100b7)

**Comment by bsongis-frsky** [comment]
It will be there in the next nightlies

**Comment by RealTadango** [comment]
@bsongis-frsky Why is the 1.5.20 milestone deleted?

**Comment by robthomson** [comment]
The functionality is going into the 1.6 release

**Comment by RealTadango** [comment]
Why not just a small 1.5 update?

**Comment by stubugs** [comment]
I've a flex firmware  1 5 19 with it i can send you bsongis sent me for test ing works great

**Comment by azaz44** [comment]
I updated to 1.6 but can't find any option, where would it be? I'm on x20s. I know it was mainly developed for RS, but on x20s I also have encoder rotate just before pressing the button and select wrong option. It's probably better than on RS but far from perfect. Is there a way to change sensitivity on x20s?

**Comment by RealTadango** [comment]
Still no update for 1.5.x Updating to 1.6 is not an option for now. @bsongis-frsky please create 1.5.20 with the encoder update like you mentioned earlier.......

**Comment by stubugs** [comment]
I've a flex firmware  for x20rs if you like it with encoder fix 1.5.19

**Comment by RealTadango** [comment]
> I've a flex firmware for x20rs if you like it with encoder fix 1.5.19

Thank you, that is helpfull. I don't get it why FrSky does not release it. 1.6 is to beta for me to try....

**Comment by i3dm** [comment]
i have to agree this is another feature great to have in 1.6.
not sure why it went to 1.7.

**Comment by RealTadango** [comment]
It was promised in 1.5 also and they never did it :(

**Comment by bsongis** [comment]
It is in 1.6, no?

**Comment by azaz44** [comment]
On x20s and 1.6.2 I don't have this option. Not sure if it isn't there in this version or it isn't here because of x20s, but I'd love to have it.

**Comment by RealTadango** [comment]
> On x20s and 1.6.2 I don't have this option. Not sure if it isn't there in this version or it isn't here because of x20s, but I'd love to have it.

It is only for the RS

**Comment by azaz44** [comment]
Ok. But there are several requests to bring it to other radios as well, please let's have it

**Comment by stubugs** [comment]
I have the new encoder wheel on my x20rs it works great without needing the encoder half steps and the button has been slightly raised to

**Comment by azaz44** [comment]
> I have the new encoder wheel on my x20rs it works great without needing the encoder half steps and the button has been slightly raised to

Is it newer x20rs version or your own modification?
Wondering as this is what stops me from getting x20rs.

**Comment by stubugs** [comment]
I think the new ones come with it but I got it from 
https://www.horusrc.com/en/frsky-encoder-for-tandem-x20pro-aw-x20r-rs.html
I wouldn't let it stop you getting the x20rs 
I had I x20s and the rs alot better
Glad I bought it 
Even if the encoder cost me 10 dollars
