### ISSUE TITLE
sensor mute

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#4688]
Can we please get a lua feature to mute a sensor for a certain duration

system.mute(sensorLost)

Specifically we have an issue - when msp data is sent - we often get sensor timeouts due to them being paused on sending during msp transfer.

it would be nice to mute these for a duration

**Comment by mawzthefinn** [comment]
Yes, this should also be used for system->info which causes the same issue

**Comment by bsongis-frsky** [comment]
```lua
local module = model.getModule(0)
module:muteSensorLost(5.0) -- mute during 5 seconds
```
