### ISSUE TITLE
RSSI Min always 0

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#469]
Tandem X20
Ethos 1.0.9 RC 3
TD-ISRM 2.1.7
Archer R8 Pro on 2.1.7

I have a display widget for RSSI Min on my home screen (this was mainly for X20 testing to see how low it got in flight).  It now always reads 0.

I tried resetting the telemetry, it stayed 0, I tried reseting the item with the widget interface, it still stayed 0.

I believe this worked in 1.0.7, I am not sure about 1.0.8

**Comment by MIKE-DAILEY** [comment]
It is working OK on a X20S with RC4 including the reset function.

**Comment by jfint** [comment]
I'll try again with RC 4 tonight and close this accordingly.

**Comment by jfint** [comment]
Yep, fixed in 1.0.9- RC4
