### ISSUE TITLE
Local audio is placed in wrong folder from Suite 1.5.11?

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#4690]
Ethos Suite 1.5.11
Ethos OS 1.5.18 EU
FrSky X20S

I have found that Ethos Suite installs localised audio (norwegian) in the following path:
audio (folder) ->no (folder) -> default (folder) -> system (folder) -> WAV-files.

If I select a audio file to play in Special Functions, the dialogbox is empty  :-/

If I move the system (folder) to no (folder) like this, the WAV-files is available:
audio (folder) ->no (folder) -> system (folder) -> WAV-files. (Deleting the "default" folder)

If I try to install the sound-files (Norwegian) via Ethos Suite 1.5.11, Suite tells me:
The following system Audio folder(s) are no longer used by the firmware due to a system version upgrade.
It is recommended to remove the folder. Is it OK to do so?

If I select Yes, the folder structure reverts to: audio (folder) ->no (folder) -> default (folder) -> system (folder) -> WAV-files.

Is this a bug?
If so, it may allso apply to other languages?

**Comment by mawzthefinn** [comment]
This is not a bug. This is behaving correctly.

ETHOS ships with system audio files, which are by default located in /audio/(language code)/default/System/

They are not selected  in the Play Audio special functions, as they are used for the system callouts (teh standard ones plus any Play Value action)

For languages where a default set of custom audio files are published, they will be located in /audio/(language code)/default/ and will be selectable in the Play Audio special functions

You can also install custom audio to 3 additional folders in /audio/(language code)/mycustomfolder/ with custom system audio in /audio/(language code)/mycustomfolder/system/ and then map those to your 3 voices in System->General
