### ISSUE TITLE
Access to Audio files in 1.5.18

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4693]
When I try to Play File in the Special Functions, I only have access to the default folder. I need access to my audio files. Should I add them to the default folder, or the Play File pull down is missing a folder selection?

**Comment by mawzthefinn** [comment]
You need to map your custom folder to a voice in system->general

that custom folder must be in /audio/en/ or your language equivalent

**Comment by Richrfl** [comment]
Got it mawz. I have to set it on this screen:
![image](https://github.com/user-attachments/assets/e58521a2-6224-41d9-9c90-bc5e8b9d24b4)
To avoid not getting access to the default wav's I will need to add my customs wavs to the default folder. Is that correct?

**Comment by mawzthefinn** [comment]
You can pick voices independently in each callout, so no need to put your custom files in the default folder unless you want to (it will work, but results in more options to scroll through)

**Comment by Richrfl** [comment]
That is an excellent idea. Thank you
