### ISSUE TITLE
Unable to add variometer sound on spektrum telemetry

### ISSUE THREAD

**Issue by amaury10** [FrSkyRC/ETHOS-Feedback-Community#4695]
Hello,

As it works now, I try the AR6610T variometer with the MPM in a glider.
Unfortunately I don't find how to configure the sound on it.

Is it possible ?

Cheers,

Amaury.

**Comment by mawzthefinn** [comment]
Vario sound is a Special Function now in ETHOS 1.5

**Comment by amaury10** [comment]
Ok found it.

Thanks a lot. May it be possible to ass a shortcut from the telemetry menu ?

**Comment by amaury10** [comment]
In addition, is it possible to zero the altitude ? I bound reset function to a switch, but it doesn't zero the altitude value.

**Comment by bsongis-frsky** [comment]
Auto Offset on Spektrum Altitude will be available in the next nightlies

**Comment by amaury10** [comment]
Hi Bertrand, 

Thank you for the good news.
