### ISSUE TITLE
error Message: unknown image type

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#4696]
Hello Bertrand,
I have a script that displays some images, all PNGs.
It works for a while, but then I get the following message.

019334 Lua::loadBitmap('/scripts/farbwert/bitmap/white/0.png')
019335 Bitmap::load(/scripts/farbwert/bitmap/white/0.png) failed: unknown image type

`for nr=0,9,1 do
       widget.fnt_nr[nr] = lcd.loadBitmap(path..nr..".png")	
end`

Thank you

Kind regards
Benno

**Comment by bsongis-frsky** [comment]
Just a first comment: you should rather use relative paths, i.e. if your script is installed in `/scripts/farbwert`, I suggest you change
`'/scripts/farbwert/bitmap/white/0.png'` to `'./bitmap/white/0.png'` or even `'bitmap/white/0.png'`

**Comment by bsongis-frsky** [comment]
I think the comment above will even solve your issue. Because `/scripts` doesn't tell to Ethos which is the drive where the bitmap is stored

**Comment by Benno00** [comment]
Hello Bertrand,

Unfortunately that doesn't help. After about 12-15 seconds this error message keeps coming up

032310 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/0.png')
032311 Create bitmap ... RAM used: 1213054 bytes
032311 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/1.png')
032311 Create bitmap ... RAM used: 1218654 bytes
032312 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/2.png')
032312 Create bitmap ... RAM used: 1224254 bytes
032312 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/3.png') 032313 Create bitmap ... RAM used: 1229854 bytes 032314 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/4.png') 032316 Create bitmap ... RAM used: 1235454 bytes 032316 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/5.png') 032317 Create bitmap ... RAM used: 1241054 bytes 032317 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/6.png') 032317 Create bitmap ... RAM used: 1246654 bytes 032317 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/7.png') 032318 Create bitmap ... RAM used: 1252254 bytes 032318 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/8.png') 032318. Bitmap::load(SCRIPTS:/farbwert/bitmap/red/8.p ng) failed: unknown image type ←[31m032319 Load bitmap SCRIPTS:/farbwert/bitmap/red/8.png failed!←[0m 032319 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/9.png') 032319 Bitmap::load(SCRIPTS:/farbwert/bitmap/red/9.png) unknown image type
←[31m032320 Load bitmap SCRIPTS:/farbwert/bitmap/red/9.png failed!←[0m
032320 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/D.png')
032320 Bitmap::load(SCRIPTS:/farbwert/bitmap/red/D.png) failed: unknown image type
←[31m032320 Load bitmap SCRIPTS:/farbwert/bitmap/red/D.png failed!←[0m
032321 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/p.png')
032321 Bitmap::load(SCRIPTS:/farbwert/bitmap/red/p.png) failed: unknown image type
←[31m032322 Load bitmap SCRIPTS:/farbwert/bitmap/red/p.png failed!←[0m 032322 Lua::loadBitmap('SCRIPTS:/farbwert/bitmap/red/m.png') 032322 Bitmap::load(SCRIPTS:/farbwert/bitmap/red/m.png) failed: unknown image type ←[31m032323 Load SCRIP TS:/farbwert/bitmap/red/m.png failed!←[0m

**Comment by bsongis-frsky** [comment]
It seems you are running your script on simulator, would you attach a zip to the issue?

**Comment by Benno00** [comment]
Hello Bertrand,
I was able to solve the problem by specifying a fixed path, thank you very much

Kind regards
Benno

**Comment by bsongis** [comment]
Don't forget that the simulator allows custom paths for audio / scripts / bitmaps etc.

**Comment by Benno00** [comment]
Hello Bertrand,

 

I don't think it's the paths fault, it looks to me as if ETHOS simply doesn't load the PNG

 

Kind regards

Benno Jurisch

 

Von: Bertrand Songis ***@***.***> 
Gesendet: Montag, 4. November 2024 18:17
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; State change ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] error Message: unknown image type (Issue #4696)

 

Don't forget that the simulator allows custom paths for audio / scripts / bitmaps etc.

**Comment by bsongis** [comment]
PNG may be complex!

**Comment by Benno00** [comment]
Hi Bertrand,
i have now solved it as follows: when starting, I read in all the required PNGs and note the header address from lcd.loadBidmap() in a table. If the PNG needs to be changed, I just change the header address and it works perfectly.

I no longer get any error messages 

![image](https://github.com/user-attachments/assets/89ef20db-260d-4038-b0c1-f0ba23f240ce)

**Comment by Benno00** [comment]
Hello Bertrand,

 

Sorry, i have to ask you something again.

 

How can i update the Configuration(Widget) form under Configuration(widget)

after selecting a sensor/channel…

 

My problem: I am writing a widget, in which the colors, etc. for a source can be set.
When Configuration(Widget) is called and a sensor/channel... has been selected, the configuration(widget) should be updated, such as the function paint(widget) with lcd.invalidate() in function wakeup(widget). 

But how can i call this?

 

Many thanks

 

Best Regards

Benno Jurisch
