### ISSUE TITLE
New Path prefixes like "AUDIO:" in Lua scripts

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#4697]
`system.playFile('./test.wav')` -- play test.wav in the current directory
`system.playFile('SD:/audio/en/test.wav')` -- play a file defined by its absolute path
`system.playFile('AUDIO:/default/test.wav')` -- play a file using the prefix "AUDIO:" (the file can be on SD or eMMC / Nand)
`system.playFile('VOICE1:/test.wav')` -- play a file from the VOICE 1 directory which has been setup in Radio / General

- [X] AUDIO:
- [X] VOICEx:
- [X] BITMAPS:
- [X] SCRIPTS:
- [X] SCREENSHOTS:
- [X] LOGS:

**Comment by Benno00** [comment]
Hello Bertrand,
in ETHOS 1.6.0 this works
```
local path ="./"
local modellpath="./modelle/"
local libpath="./lib/"
local bitmappath="./bitmaps/"

```
but in ETHOS 1.6.1 it doesn't work
however if I encode everything works again

```
local path ="./"
local modellpath="SCRIPTS:swmap/modelle/"
local libpath="./lib/"
local bitmappath="./bitmaps/"

```
But here only the model path is set, so why do the remaining connections work correctly?

**Comment by robthomson** [comment]
This info for paths does not appear to be anywhere in the lua-docs.

**Comment by bsongis** [comment]
The information will be added in 1.6.1

**Comment by Benno00** [comment]
thank you,
