### ISSUE TITLE
Spektrum: Improvement/fixes of Sensors (Part 2)

### ISSUE THREAD

**Issue by frankiearzu** [FrSkyRC/ETHOS-Feedback-Community#4702]
Tested with latest nightly 1.6  (Nov 4)
Issues in **BOLD** for each frame type.

Using an AR637TA Smart RX + Avian ESC to get ESC/Batt telemetry,
as well as an FC6250HX (heli) with Smart ESC and Smart Bat.

Just a bit of background.. most of the Spektrum Telemetry frames carry many sensors, and are grupped based on what is needed in a single telemetry screen.. the frame data match the screen data. For example, the ESC frame has all the different data related to ESC telemetry screen.
In OpenTX/EdgeTX/Ethos the philosophi is to have this individual sensors, and let the use group them as needed with widgets.

This difference creates a challenges in our side: Sometimes, the same sensor data is sent of different frames types, creating duplicates sensors. For example, Batt V can come in the Flight Pack Frame and ESC frame.. What we did in EdgeTX is to detect if we are getting an ESC frame, and ignore the BattV comming from the Flight Pack sensor. Otherwise you end up with two "A3" sensors with the same value. Another example is with the Vario Frame and Altitude Frame.. Vario has "Alt" and "VSpd", and the Frame ALT only have altitude.. but the RX sends both frames, so you end up with two "Alt" sensors. LemonRX G2 receivers do send a lot of the same data on multiple frames when you have their Current or Voltage sensor attached, creating many duplicates.. but the same thing happen with genuine Spektrum when you have the Smart ESC and the Flight Pack monitor sensor connected (Current, Volts, Temperature, Battery Usage mAh).

There are some frames who has unrelated data, just to match the data on a screen.. for example, there is a frame who has RPM, Temp, and Batt Volage.. The Batt Voltage is populated, but the if you don't have the RPM or Temp sensor, it will come with NoData constant.

### General comment:

Should the ID of the Sensor be the same for all the sensors comming in the same Frame?? In OpenTX/EdgeTX is the FrameId concatenated with the ByteOffset to make them unique.
Spektrum sends NoData (like 0xFFFF or 0x7FFF) when the sensor is not connected, should we populate the screen during "Discover sensors" with non-existing sensors? OpenTX/EdgeTX ignore them, so they will not show up on the screen.
Summary of my Test:

- [x] **TX RSSI (0-31).. populating the Radio/Power strenght graph with very low RSSI and warnings... the internal RSSI in OpenTX/EdgeTX is this RAW value * 3 to get it 93 that is close to 100.. Ideally should be multiplied by 3.22.
OpenTX/EdgeTX TRSS is this sensor, and RSSI is populated with TRSS * 3** 

### Frame 0x7E (126) RPM/V/Temp

- [X] RPM is showing 65535 that is NoData (0xFFFF).. probably should be ignored.**
- [X] A3 showing as ---, coming with NoData. probably should be ignored.
- [X] Temp2 showing as ---, coming with NoData probably should be ignored.

### Frame 0x7F (127) QOS
I think the range for Fades is not correct 0-100 and 0-200.. Antena fades/losses can be in the 1000s in a bad connection.**

RxA fades is OK
RxB,
- [x] RxL. this was showing 100... but the RAW value is 6250 (0x186A) on the Heli FC model# (with Heli RX).. Probably due to the Range 0-100**
- [x] RxR fades shows with "---" (NoData), this RX don't have the extra antennas, proably should be ignored when NoData.
RxBatt is OK

Frame losses and Holds is OK. NOTE: is a UINT16, so NoData is 0xFFFF, but some receivers also send 0x7FFF (no-data for signed).. so in EdgeTX, ignoring both.

### Frame 0x20 (32) ESC

- [X] ESC RPMs is showing values who are too small.. It needs the x 10 in the documentation ("RPM, 10RPM (0-655340 RPM)")**
ESC Voltage OK
ESC Temp OK
ESC Current OK
- [X] BEC temp, current, volatage has NoData.. Probably should be ignored.
Throttle % and Power Out is OK

### Frame 0x14 (20) GForce
All seems OK

### 0x1A (26) Gyro
- [X] Seems OK, but i think we have the same problem as in OpenTX/EdgeTX.. the value is in Deg/sec, not degress.. but we dont have that Unit.

### Frame 0x42 Smart Battery (Not documented)

- [X] **Battery Capacity: WRONG Name (Is not Capacity, but instant current) in mA, PREC0. Should be very close to the ESC Current (that is in A, PREC2)**
Battery Used 0
Min Cell ---
Max Cell 0.0V
Batt temp 0
- [X] Cel1-Cel6 ---looks good, was testing with a 3-cell, cell4-6 show "---", should we hide unused ones??

The Smart battery frame is tricky, since the same frame can be populated with different data.
The first byte on the data tells you what type of data is encoded in the next bytes.

0x00. Status of the Battery (that seems to be populated OK)
0x10. Cells 1-6 -- Seems to be working fine
0x20. Cells 7-12
0x30. Cells 13-18
0x80. Manufacturer Info
0x90. Battery Limits

In EdgeTX we did a trick to add this value/16 and add it to the 0x42 base address, so in the sensor definition, Cells 1-6 is treated as Frame 0x43, etc. Seems that the frame ID range is not used in spektrum, so seems ok this hack. This is to continue using the table definition to help decode the message.

Here is the decoding in LUA:
https://github.com/frankiearzu/DSMTools/blob/main/DSMTools-src/ethos/src/scripts/dsm-smart-tel/main.lua#L679

### Frame 0x05 AS3X Flight Controller info (Not documented)
- [X] This has current flight mode information and the configurable gains/angle limits for each axis (Roll,Pitch,Yaw).
But the valuable data here is the flight mode info.. it tells you the Flight Mode #, if AS3X/Gyro is On/Off, and if SAFE is on Auto-Level, Bank Envelope, or Heading Mode.

Have the code for the decoding of the info in EdgeTX, what we are doing is populating the text "FM" sensor with the FM# + As3x + Safe Mode, so it looks like (FM = 1 As3x Auto-Level)

Note: Original RAW frame was moved to a Zero index array.. Byte pos 0 is where the I2C ID is...
Decoding on my Lua script: https://github.com/frankiearzu/DSMTools/blob/main/DSMTools-src/ethos/src/scripts/dsm-smart-tel/main.lua#L524
Data example: https://github.com/frankiearzu/DSMTools/blob/main/DSMTools-src/ethos/src/scripts/dsm-smart-tel/main.lua#L200

### Other Frames  who could be usefull
Also have the GPS and SkyId/Remote ID (undocumented) reversed enginered if you want to add the processing for those frames. On previous version of the RX firmware, the SkyID populated the documented GPS frames, but on the latest version (AS3X+), they stop sending it on those frames, and the same GPS data was added to the SkyID Frame.

- [X] **Binary GPS**  
Spektrum use the BCD encoding in two frames, but openXsensor use the binary encoding:
Binary encoding:
https://github.com/frankiearzu/DSMTools/blob/main/DSMTools-src/ethos/src/scripts/dsm-smart-tel/main.lua#L1066

**Comment by bsongis-frsky** [comment]
I have implemented everything here. It's a ~100% rewrite for the Spektrum telemetry. Now I need a serious test!

**Comment by bsongis-frsky** [comment]
I propose I close this issue and you open a new one with the result of your tests - with the checkboxes ;)

**Comment by frankiearzu** [comment]
Validated with 1.6 nightly of Nov 10.   All is working as expected...
RSSI show Antenna Icon with Full bars (as expected), the new value of 0-99 will make it that the Low/Critical RSSI Alarms settings will stay in aceptable range with default values.

Tested with a few Smart Bats and Different AVIAN ESC. Also charging them with Smart Charger.

The Min/Max Cell comming from the Smart battery Frame (0x42) are always NoData or 0.  I recomend not using this sensors. The Min/Max can be extracted from the LIPO1 sensor.
Batt Used seems to be always 0,

The following screenshots comes from a Blade 230s Smart:

![image](https://github.com/user-attachments/assets/f3d6c424-b6e5-4da2-9d91-f56320f0ef59)
![image](https://github.com/user-attachments/assets/244a56a6-7339-4154-8fed-7ba437d41cd9)
![image](https://github.com/user-attachments/assets/300e0d1a-6be1-4cd3-823b-d887948896f9)
![image](https://github.com/user-attachments/assets/08f86b26-1b89-4ed0-a991-d2c400a36d39)
![image](https://github.com/user-attachments/assets/12d28a63-807b-4e22-827e-12c471c4d7bb)
![image](https://github.com/user-attachments/assets/af533876-5338-4833-b040-eaf7479c0cf7)

**Comment by bsongis** [comment]
It has been a pleasure to work with you, thanks for that. I am ready for the next sensors if you need!
