### ISSUE TITLE
LUA addFileField not showing anything else "---"

### ISSUE THREAD

**Issue by amaury10** [FrSkyRC/ETHOS-Feedback-Community#4703]
Hello,

I'm trying to build a small widget which aim to play sound alerts in certain conditions.
I used a FileField in the configuration form but I can browse for files using it, both on Simulator and physical radio.

Here is my piece of code :
line = form.addLine("Alerte audio")
form.addFileField(line, nil, "/audio/fr", "audio", function() return widget.alert_file end, function(value) widget.alert_file = value end)

and here is the result :
![image](https://github.com/user-attachments/assets/ba1b85bb-c44c-49c3-84a6-33b35ed08145)

Is there anything I miss or is there a problem witj the FileField ?

Chhers,

Amaury.

**Comment by bsongis-frsky** [comment]
Which files do you have in /audio/fr?

**Comment by amaury10** [comment]
Hi,

Normally I should have the full language pack, but I just see that simulator is not looking where I think it was:
![image](https://github.com/user-attachments/assets/0a9e1db0-3e80-483c-a058-95b1f0d406c1)
Instead I thought it was looking in the default audio directory in Program Files. Is there the same trick on the radio ?

BTW, is there special paths we can use to access audio files?
and is there a way to play a language file in the configured radio language (using something like an alias) ?

**Comment by bsongis-frsky** [comment]
Inside FR, normally you should have voices (like "homme" or "femme"), and nothing else. Also you are on the simulator. You may use command line args to change the directory if you need. If not, the simulator will try to find automatically where the audio files are stored (user or system directories).

Ethos 1.6.0 introduces some prefixes:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4697
