### ISSUE TITLE
system.playNumber(...) ignores decimal precision > 1

### ISSUE THREAD

**Issue by bob01** [FrSkyRC/ETHOS-Feedback-Community#4708]
system.playNumber(...) reports numbers rounded to 0.1 regardless of precision specified

e.g. system.playNumber(3.45, UNIT_VOLT, 2) will report "3.5 volts" (expected to hear "3.45 volts")

**Comment by tmcallahan** [comment]
Yes, This has been an open issue for a while.  Back in feb, someone opened up #3491.  Though I think your looking at the programming side of it, but someone opened it up for ethos to have this fixed.   Add me to the list of people who want this fixed so Ethos can play the cell correct voltage, and not a rounded inaccurate value.

**Comment by mawzthefinn** [comment]
Please continue discussion under #3491 It is certainly needed
