### ISSUE TITLE
Feature Request:  Play  "bye.wav" track during system shutdown.

### ISSUE THREAD

**Issue by OldGazer** [FrSkyRC/ETHOS-Feedback-Community#471]
My five OpenTx radios have this feature.

[bye.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6640104/bye.zip)

**Comment by TWSreviews** [comment]
Would be good 
"thank you for flying FrSky airwaves"
lol

**Comment by higheronnitro** [comment]
Yes please from me as well..
