### ISSUE TITLE
Ethos Suite MacOS Sequoia Model List stays empty

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#4711]
The screenshot says it all 

![Bildschirmfoto 2024-11-08 um 17 44 15](https://github.com/user-attachments/assets/ad3e575a-bb6e-4a3f-ac0a-57def49d2d98)

**Comment by T16-Pilot** [comment]
Already reported [#4704](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4704)

**Comment by Nicholas-Luoyi** [comment]
Please continue in #4704
