### ISSUE TITLE
ETHOS simulator and Tx inconsistency `nil' argument

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#4714]
There is an inconsistency between the hardware, Tx, and the simulator.

Running both simulator and Tx on 1.5.18.

The nil changes done to ETHOS are still haunting me and I cannot finish a nearly finished code.

To catch the nil I use the following: -

I have the following to get sensor data from a GPS Speed: -

`widget.Speed = system.getSource({category=CATEGORY_TELEMETRY, appId = 0x0830})
		widget.Speed = getValue(widget.Speed)
			
		if widget.Speed ~= 2001 and widget.Speed.value ~= 2001 then
			lcd.color(widget.colorText)
						
			if (widget.Speed:unit() >= 18) and (widget.Speed:unit() <= 20) then
				lcd.drawText(widget.pGPS_Spd[1], widget.pGPS_Spd[2], math.floor(widget.Speed:value())..S_Unit(widget.Speed:unit()), CENTERED)
			else	--lcd.drawText(widget.pGPS_Spd[1], widget.pGPS_Spd[2], math.floor(widget.Speed:value()).."Km/h", CENTERED)
				lcd.color(RED)
				lcd.drawText(widget.pGPS_Msg1[1], widget.pGPS_Msg1[2], "ONLY Km/h,", widget.pGPS_Msg1[3], CENTERED)
				lcd.drawText(widget.pGPS_Msg2[1], widget.pGPS_Msg2[2], "mph, or Knot", widget.pGPS_Msg1[3], CENTERED)
			end
				
		else
			lcd.color(RED)
			lcd.drawText(widget.pGPS_Spd[1], widget.pGPS_Spd[2], "-----", CENTERED)
		end`

And this to catch the nil: -

`local function getValue(sens)

	if sens == nil then
		return 2001
	end

	local SensVal = 0
 
	SensVal = sens
	return SensVal

end`

If there is no sensor, on simulator it works ok, but on real Tx, it returns the image below.

How can I work around this please? I have been stuck on this since update of 1.5.18.

![IMG_20241109_201458](https://github.com/user-attachments/assets/2332b40a-8acd-4b0d-b454-d0aa16176ee6)

**Comment by strgaltdel** [comment]
Take a look at your code.

You’re checking if the sensor exists (getvalue), but you’re not verifying if it’s actually returning any values before immediately performing an operation on a sensor value (math.floor).
If the receiver isn’t switched on, no values are provided (nil), and math.floor will generate an error.

```lua
if (widget.Speed:unit() >= 18) and (widget.Speed:unit() <= 20) then
  local sensorVal=widget.Speed:value()
  if sensorVal then
     	lcd.drawText(widget.pGPS_Spd[1], widget.pGPS_Spd[2], math.floor(sensorVal)..S_Unit(widget.Speed:unit()), CENTERED)
```


The sim IS consistent.
let him search for a speed sensor, so that the sensor does exist in the template.
disable RF on Sim, so that he can't read sensor values and look what happens...

regards
udo

**Comment by salibaj2** [comment]
I disabled the RF as suggested and instead it throws another error in SIM, not related to this one.

It  snot an issue if receiver is ON or OFF, it is an issue if the sensor has been discovered at all.

In simulator, when I have GPS sensor, there is a default value of 38KMh, and that is shown correctly.

Now, I delete the GPS and because I am trying to catch the NIL, because there is no GPS, the text: - "-----" is displayed, because I am returning 2001 from the NIL trap. 

All this is CORRECT in the simulator.

In real hardware, I have not yet discovered the GPS sensor, same as I deleted in simulator, there is no sensor, and while the simulator trap it as NIL because there is no sensor, for some reason the real hardware is throwing the error as per image in my first post.

Now my question: -

Without a sensor, the value for the sensor I am trying to get is still a NIL?

The following is with RF OFF, GPS deleted.

![RF OFF GPS deleted 1](https://github.com/user-attachments/assets/c6cc6785-9e2e-422e-b46a-7781209cae27)

As you can see, GPS is deleted but "-----" has been displayed. On real hardware, there is the error mentioned in my first post of this thread.

Also note that Gear Batt. box is empty, because this is the new error when RF is OFF, and all telemetry is NIL.

In both cases, one with telemetry OFF and GPS deleted are acting differently. RF OFF apparently is not returning a NIL when suppose it should, and that part, because I am trapping it it should be skipped.  

![RF OFF GPS deleted 2](https://github.com/user-attachments/assets/3f7eff40-3b57-4b4b-a922-a9d1ca11acb7)

Code for both: -

`
-- GPS Speed
						
		widget.Speed = system.getSource({category=CATEGORY_TELEMETRY, appId = 0x0830})
		widget.Speed = getValue(widget.Speed)
			
		if widget.Speed ~= 2001 and widget.Speed.value ~= 2001 then
			lcd.color(widget.colorText)
						
			if (widget.Speed:unit() >= 18) and (widget.Speed:unit() <= 20) then
				lcd.drawText(widget.pGPS_Spd[1], widget.pGPS_Spd[2], math.floor(widget.Speed:value())..S_Unit(widget.Speed:unit()), CENTERED)
			else	--lcd.drawText(widget.pGPS_Spd[1], widget.pGPS_Spd[2], math.floor(widget.Speed:value()).."Km/h", CENTERED)
				lcd.color(RED)
				lcd.drawText(widget.pGPS_Msg1[1], widget.pGPS_Msg1[2], "ONLY Km/h,", widget.pGPS_Msg1[3], CENTERED)
				lcd.drawText(widget.pGPS_Msg2[1], widget.pGPS_Msg2[2], "mph, or Knot", widget.pGPS_Msg1[3], CENTERED)
			end
				
		else
			lcd.color(RED)
			lcd.drawText(widget.pGPS_Spd[1], widget.pGPS_Spd[2], "-----", CENTERED)
		end
		
		------------------------------------------------------------------------------------------------------------------------------
		-- Gear Battery

		widget.Gear_Batt = system.getSource({category=CATEGORY_TELEMETRY, appId = 0xF103})
		widget.Gear_Batt = getValue(widget.Gear_Batt)
	
		if widget.Gear_Batt ~= 2001 and widget.Gear_Batt.value ~= 2001 then
			lcd.color(widget.colorText)
			lcd.drawText(widget.pGBatt[1], widget.pGBatt[2], widget.Gear_Batt:value().."v", CENTERED)
		else 
			lcd.color(RED)
			lcd.drawText(widget.pGBatt[1], widget.pGBatt[2], "-----", CENTERED)	
		end

		------------------------------------------------------------------------------------------------------------------------------
`  

Do you have an email address to send you the full code? 

Certainly this should be a kids play, but for me, in my infants steps it is a real headache. For others 10 minutes work, for me already 15 days stuck.

Thank you

**Comment by strgaltdel** [comment]
do you've an account on rcg?
you can pm me then (strgaltdel) and i would give you my email  
would need code & template

**Comment by salibaj2** [comment]
Yes, got your email already. Will do later today.

Thank you.

**Comment by salibaj2** [comment]
Email sent!

Thank you

**Comment by robthomson** [comment]
You need to check variables before you use them.

math.floor(widget.Speed:value())..S_Unit(widget.Speed:unit())


could be.

If type(widget.Speed:value()) == 'number' then
math.floor(widget.Speed:value())..S_Unit(widget.Speed:unit())
end

**Comment by salibaj2** [comment]
Thanks all for the hints I somehow managed to trap the nil. Cross finger that it works.
