### ISSUE TITLE
problema segnale 90mhz su tandem x20r con firmware 1.1.14

### ISSUE THREAD

**Issue by mineieio** [FrSkyRC/ETHOS-Feedback-Community#4716]
Buonasera ho notato che con il firmware 1.1.14 per la trasmittente x20r  il segnale 900mhz indicato dalla trasmittente sembra impazzito, continua a passare da 0 a 100db .....
invece col firmware precedente 1.1.13 non succede potete verificare ? attualmente sto utilizzando il firmware 1.1.13 ho effettuato il downgrade per sicurezza.
buona giornata Eugenio

**Comment by rickisound** [comment]
ciao, dovresti almeno scrivere in inglese qui, comunque intanto ti consiglierei di aggiornare la radio all'ultima versione 1.5.18
saluti Riccardo

**Comment by yellowbird911** [comment]
My x20pro v1 is updated to 1.5.18 and I have the same issue with 1.1.14.  Even tried 1.6 nightly but didn't correct.  Switching back to 1.1.14 did.  By the way this is using sr8pro and r9mini.

**Comment by mineieio** [comment]
The radio is updated to the latest ethos available, the only thing I have downgraded is the module firmware of my x20r. Doing so seems to work without any problems. But the question remains... Why does this happen with firmware 1.1.14?

**Comment by yellowbird911** [comment]
Same here.

**Comment by mawzthefinn** [comment]
This is not an ETHOS issue, so updating ETHOS won't fix it. 

KNown issue in RSSI reporting with 1.1.14, it is fixed in the upcoming 3.0.0 and rolling back to 1.1.13 also addresses.

RF issues like this should be reported here:

https://github.com/FrSkyRC/RF_Feedback_Group/issues
