### ISSUE TITLE
Ethos 1.5.18 module 2.2.7 broke Telemetry for Spektrum

### ISSUE THREAD

**Issue by blue68camaro-git** [FrSkyRC/ETHOS-Feedback-Community#4718]
After the upgrade all my Spektrum receivers report RSSI signal low or loss. Also reports batter voltage low. RSSI signal reads 31db and no battery voltages anywhere are low. FrSky recovers work fine, no issues.

**Comment by RealTadango** [comment]
So adjust the alarms..... RSSI from Spektrum is new and needs some finetuning.

**Comment by blue68camaro-git** [comment]
How? AND it worked before the upgrade. Did not need to adjust anything!!

**Comment by RealTadango** [comment]
RSSI wasn't working before the 1.5.18 update. You can adjust the alerts under telemetry and edit the RSSI sensor.

**Comment by blue68camaro-git** [comment]
There is no adjustment. Only adjustments are Range, Logs, Reset, Critical Value, low value warning, sensor lost warning delay. Before it read a steady 31db and the alarm wouldn't go off. Now it jumps all over the place, from @ 25 to 35. AND now the low voltage alarm constantly goes off as well. Before it was steady.
