### ISSUE TITLE
Differential Expo (Different Expo Rates Based on Stick Position)

### ISSUE THREAD

**Issue by 4PNTRLL** [FrSkyRC/ETHOS-Feedback-Community#4720]
Precision aerobatics fliers spend a great deal of time tuning their aircraft and radios to take the work load off the pilot and to make their aircraft fly flawlessly through simple and complex maneuvering. 

A staple of any setup is the "feel" of the elevator response in both upright and inverted attitudes. With the help of other pilots I've been able to mimic the feel of the elevator as if there were the ability to program different exponential rates for up and/or down elevator. (Or any other control surface). 

All other radio brands have the option to input different exponential rates dependent on stick input. It seems to me that for the wonderfully advanced radio system that Ethos/FrSky is, we too, should have that option. 

Thank you in advance.

**Comment by strgaltdel** [comment]
I’m not sure if I understood the task correctly,

but different expo values/curves depending on a stick position can already be implemented very easily.
In my opinion, the current implementation offers much more flexibility than most competitors

The 'straightforward' & simple approach is, for example, like this:
(two expo curves, dep.on Stick position)
![image](https://github.com/user-attachments/assets/cd81b267-4d50-4af5-bd55-62675afe9477)



but a much smarter approach would be via 'var'

Mixer: (Expo setting via Var Xpo)
![image](https://github.com/user-attachments/assets/f7d45aae-8ac3-4f87-a7de-ed86ab48c855)

Var (value depend. on stick Position, FM, "Action support etc..)
![image](https://github.com/user-attachments/assets/85ddeb5f-7e6f-4173-ab74-464e11cc1f65)

By using vars, you can distinguish dozens of different situations through the use of logics, flight modes, actions, and corresponding dependencies, and utilize appropriate values.
Additionally, it allows for easy adjustments to the values in-flight in a straightforward way.

**Comment by 4PNTRLL** [comment]
Good Morning, 
I'm impressed with the timely reply. This was my first time inputing an "issue" which really wasn't an issue. 
I appreciate the insight and examples. I look forward to trying them in the near future. 
Great job,
Mike
    On Monday, November 11, 2024 at 03:48:54 AM CST, Udo ***@***.***> wrote:  
 
 


I’m not sure if I understood the task correctly,

but different expo values/curves depending on a stick position can already be implemented very easily.
In my opinion, the current implementation offers much more flexibility than most competitors

The 'straightforward' & simple approach is, for example, like this:
(two expo curves, dep.on Stick position)
image.png (view on web)

but a much smarter approach would be via 'var'

Mixer: (Expo setting via Var Xpo)
image.png (view on web)

Var (value depend. on stick Position, FM, "Action support etc..)
image.png (view on web)

By using vars, you can distinguish dozens of different situations through the use of logics, flight modes, actions, and corresponding dependencies, and utilize appropriate values.
Additionally, it allows for easy adjustments to the values in-flight in a straightforward way.

**Comment by mawzthefinn** [comment]
Closing this off as answer provided
