### ISSUE TITLE
X20Pro V1 900 RSSI telemetry bounding around/ FW 1.5.18 and Module FW 1.1.14

### ISSUE THREAD

**Issue by yellowbird911** [FrSkyRC/ETHOS-Feedback-Community#4723]
After updating to 1.5.18 and 1.1.14 the 900 RSSI telemetry was bounding around from high to low, VFR however looked normal as did all the other telemetry items I was receiving.  Switched back from 1.5.18 to 1.5.11 which didn't correct it and also tried 1.6 nightly.  Switched back to module 1.1.13 and the issue went away. Tried to switch back to 1.1.14 to verify but 1.1.14 would not load from the internet so maybe this is already being addressed.  

Tested with three different planes.  One with SR8+ and R9min, one with SR8Pro and R9mini and lastly with SR10Pro and R9mm or mini, can't remember.  

Thanks for the work you guys do!

**Comment by RealTadango** [comment]
Bouncing?

**Comment by yellowbird911** [comment]
Bouncing from as low at 5 or 10 to a high of 95-100.  Numbers are moving so fast you can't read them....so bouncing. 😁

**Comment by mawzthefinn** [comment]
It's a known issue with 1.1.14, roll back to 1.1.13 for now, it's also fixed in 3.0.0 beta. Not an ETHOS issue. 

1.1.14 was pulled due to this issue.

Note, RF issues like this belong in https://github.com/FrSkyRC/RF_Feedback_Group/issues so I'm closing it off here.
