### ISSUE TITLE
Text to Speech not working

### ISSUE THREAD

**Issue by cdasso** [FrSkyRC/ETHOS-Feedback-Community#4726]
So I got a x20RS a few weeks ago. It’s great but one of the things I was looking forward to was the text to speech function. I haven’t found anything been trying to use it but it’s a train wreck for me. The biggest issue is that it is spelling out very simple words like “hold” or “cut” instead of speaking them. Basically useless. Is there a trick that I am missing?

**Comment by pmullen503** [comment]
If you use all caps, it spells the word. Lower case it says the word.
HOLD is H-O-L-D
hold is HOLD.

**Comment by cdasso** [comment]
That’s very helpful. Thanks much

**Comment by bsongis-frsky** [comment]
Closing as the solution has been given, thanks @pmullen503

**Comment by DomoMKT** [comment]
you can actually find a more reliable and user-friendly text-to-speech solution at [www.nemesyslabs.com](https://www.nemesyslabs.com), which offers high-quality speech with extremely low latency, no accounts needed!

**Comment by bsongis** [comment]
The discussion is about the internal TTS chip of the radio, not an external web service!

**Comment by bsongis** [comment]
FYI the demo from your website in french is just very very bad!

**Comment by DomoMKT** [comment]
Thanks for the feedback, should have been generated by our first monotonic
model, will update that!
Try to generate one for yourself and let me know ;)
