### ISSUE TITLE
Throttle cut extra option

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#473]
Would it be possible to add an option, so that to enable the throttle, the switch must be disarmed when the throttle is low. 

Just for clarity, the current operation is:
- The throttle is not low
- Switch put in arm position
- Throttle does not work
- Throttle is lowered, which unlocks it
- Throttle now works

The option I would like to see would just add an extra safety feature so that just lowering the throttle is not enough to unlock the throttle. The switch must be in the disarmed position and the the throttle low to unlock the throttle when the switch is moved to the arm position. 

A checkbox for “switch lock” or something like that would be great. As I appreciate that not everyone wants to use this extra security.

**Comment by skyfly74** [comment]
It is ever possible to do it. This the utility of logic switch. One logical switch to see when throtlle is low ans second one with the sticky  function with your first logical switch and your usual throttle cut switch.

**Comment by Hobby4life** [comment]
Correct you should do that in logic. There you are free to create your own idea of safety switch.

**Comment by MrD-RC** [comment]
Of course it is possible to do it with logic. I have been doing it with OpenTX. 

But, if there is already a throttle cut feature, and other people also use this functionality, why not add the option to the throttle cut? Rather than have to completely ignore the functionality that is there, just to add on a last little part. 

It’s just a suggestion, as I figured other people could find that functionally useful.

**Comment by Hobby4life** [comment]
I like your suggestion for sure. Thats how I programmed my safety also.
But many have their ideas of how to add safety.. and for now Adding the throttle cut is in my opinion the borderline between freedom of programming, and pre-definition.
And we must beware Ethos becomes a new Pre-defined system as Futaba, Spektrum etc.

**Comment by MrD-RC** [comment]
@Hobby4life I agree, which is why I suggested to make it a checkbox option. So that people can decide which they would like to use. It could even be a system wide setting, that you change in one place, then all throttle cuts act the same. That would lose some flexibility though. 

But look at it this way, there are 3 people replying to this post. All of them programmed their safety’s in the way that’s being requested in this issue. To me that shows there is fair grounds to add the option.

**Comment by bsongis-frsky** [comment]
"Sticky" throttle cut added to 1.0.10 RC4
