### ISSUE TITLE
SDcard does not appear on my X20R

### ISSUE THREAD

**Issue by Joelec1009** [FrSkyRC/ETHOS-Feedback-Community#4733]
when I turn on my radio, only radio and flash appear. Ethos does not tell me the presence of my SDcard even though it appears in Windows Explorer. Is there a problem with my radio? Attached are photos of the screens. The sdcard is a new card Scandisk ultra 64GB

![20241112_194615](https://github.com/user-attachments/assets/4256c243-fb96-47a7-984c-5367e1b3b1be)
![20241112_194714](https://github.com/user-attachments/assets/12fbb65d-93dd-4153-b5b3-083cd72a8138)
![20241112_202528](https://github.com/user-attachments/assets/c0921065-b453-402c-bfee-4e1c88d49c1d)

thx a lot for your ### help

**Comment by bsongis-frsky** [comment]
Is your SD Card formatted? NTFS? FAT32?

**Comment by strgaltdel** [comment]
i'm pretty sure sd cards are specified up to 32GB for Ethos. i would try a smaller one, not the 64GB type

edit,
found it, lothars manual states:
The X20/S/HD series requires an SD card that is 32gig or less formatted fat32

**Comment by mawzthefinn** [comment]
SD cards of greater than 32GB capacity are formated in ExFAT, which ETHOS cannot read. ETHOS supports FAT16 and FAT32 cards only. 

@Joelec1009 - Your 64GB card is not formatted in a way ETHOS can read it, please use a 32GB or smaller card which will solve your issue.

**Comment by Joelec1009** [comment]
Thx à lot for your answers. 
I've tried à 16gb card and it's OK.
👍
