### ISSUE TITLE
is form.onWakeup deprecated?

### ISSUE THREAD

**Issue by st157322** [FrSkyRC/ETHOS-Feedback-Community#4735]
I used form.onWakeup as introduced in #1349 to update a form within the configure function of a widget. I needed it to perform some Tasks only when in the configure function after a Button was pressed. And it worked till 1.5.18

How should i do it now, does the onWakeup comes back or do i have to find another workaround?

**Comment by st157322** [comment]
nevermind, got it to work by using the normal Wakeup Function. But would be nice when you mention a removal of the corresponding functions within the changelog and also keep the Lua examples consistent and working.

**Comment by bsongis-frsky** [comment]
It has been marked as deprecated since some time if I am not mistaken. I will add it to the release note. I try to do my best, but sometimes I forget changes!

**Comment by bsongis-frsky** [comment]
Release note updated
