### ISSUE TITLE
ERROR Lua Stab Tools 3.0.0 (for TD_TW Stab receivers)

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4736]
ERROR Lua Stab Tools 3.0.0 (for TD_TW Stab receivers) Officiel FRSK
Ethos 1.5.18. LUA error in TD/TW SRX cali : Receiver Images png Not Displaying.
![ERROR-Lua Stab Tools 3 0 0 (for TD_TW Stab receivers)](https://github.com/user-attachments/assets/0fe504f7-bda8-4b3c-86c0-a71dd3be63fc)

**Comment by Nicholas-Luoyi** [comment]
It is a known issue. Where do you get the test version scripts?

**Comment by philippe-warnotte** [comment]
I don't know of a test version. here, it's the official FR Sky version Rx twin sr8. Lua 3.0.0 for SR8 firmware 1.09. Is there a test version?
The problem exists only in the LUA calibration because the figures of the receiver do not appear.

**Comment by Nicholas-Luoyi** [comment]
I'm just curious. Never mind. It will be fixed in the next version.

**Comment by philippe-warnotte** [comment]
The next version it must be completed. it's good to want to make improvements but it's unfortunate to break the basic functions such as the calibration of stabilized receivers and also the OTA function. If you use another method of script reading, why don't you modify its official script FRSky?

**Comment by bsongis** [comment]
Where did you get the Lua script?

@Nicholas-Luoyi all our scripts could be stored in ETHOS-Feedback-Community, it would allow us to automatically test them all in our non regression tests!

**Comment by philippe-warnotte** [comment]
Ethos suite 1.5.11, download center, receivers, Tw series, Tw sr8, lua stab tools 3.0.0.zip. My receiver FW 1.0.9.zip

**Comment by Nicholas-Luoyi** [comment]
Yes. That's the correct place

**Comment by philippe-warnotte** [comment]
Can you test this calibration script for me please. Receiver images do not appear to indicate positions. And a error is displayed on the top
![20241115_065625](https://github.com/user-attachments/assets/2a3d39b0-7b66-4da2-abc8-a319ec728af5)

![20241115_065642](https://github.com/user-attachments/assets/0eb5ace2-dc07-4730-8ea7-df940fca5e1b)

NB:A receiver is not required for this test since the error appears on the first screen.

**Comment by bsongis** [comment]
Absolute paths for bitmaps are not good. Here the bitmaps are inside the script directory, it's just needed to load the bitmaps with its name, without any path!

**Comment by philippe-warnotte** [comment]
thank you but I don't understand exactly whether we should move the bitmaps .png to another folder but which one? or should I modify the script to him but then I'm not able

**Comment by bsongis** [comment]
We are working on it. Those scripts are ours, we have to fix them :)

**Comment by philippe-warnotte** [comment]
Absolute paths for bitmaps are not good. Here the bitmaps are inside the script directory, it's just needed to load the bitmaps with its name, without any path!
@bsongis: I just understood. I removed the Path from the bitmaps in the script and it work perfectly  now.
 Thanks for your help.

**Comment by philippe-warnotte** [comment]
@Nicholas-Luoyi: There is also a Bug in the previous script: LUA STAB TOOL: FrSky_STAB_RX_v2.06. 
(Ethos suite, download center, receivers, tw series, tw SR8)
In SRX_cali, the bitmap file name: "calibration_ok.png" is not correct.
We can't see the end bitmap at the end of calibration process. In the script, the name is: "cali_ok.png"

**Comment by Nicholas-Luoyi** [comment]
Would you please check that scripts are good now?

**Comment by philippe-warnotte** [comment]
Since the scripts (Lua Stab Tools 3.0.0 (for TD_TW Stab receivers)) 
have not been changed(Frsky or Suite), I guess I have to try with the latest Ethos version 1.5.19?  Or Ethos 1.6.0 nighlies

I'm still on version 1.5.18.

**Comment by philippe-warnotte** [comment]
The scripts are OK with Ethos 1.5.19. Thanks. You can close Nicholas.
