### ISSUE TITLE
[1.6 nightly] Emergency mode opening ELRS module config

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#4738]
1.6 nightly #2ce9808b
X20RS

Without an RX connected, opening the configure menu for ELRS results in emergency mode.

With an RX connected, it freezes the UI and the power button is unresponsive.

**Comment by bsongis-frsky** [comment]
Reproduced on simulator too

**Comment by bsongis-frsky** [comment]
Fixed in the next nightlies
