### ISSUE TITLE
Add System events

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#474]
I was thinking, it would nice to have events that could be used with logical switches or special functions for some system events. 

One that springs to mind at the moment is the throttle cut. If the throttle is high and you try to arm the throttle, it would be great to have a system trigger for arming failure. I know this could be created with logical switches. But where it’s a system based function. It would be good if there were system based events to go with it. 

I’m sure there are other areas that could benefit too. I think I may have seen a system menu in the select box, but don’t recall seeing things like this. Unfortunately I can’t check at the moment. But wanted to get the idea in writing. 

__edit__ I did check ETHOS, and this functionality doesn’t appear to be present.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/127904527-f873e2aa-ba54-4ad6-93b4-af36a67242d1.png)
