### ISSUE TITLE
Tandem XE Switch assignments

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#4749]
XE-S radio, Ethos 1.5.18
Converting to XE tray radio I discovered that all the switch assignments on the XE can be changed around to my preference. As I have quite a number of models including full house gliders with multiple flight modes, logic and SF etc I thought this would be good, as I would not then have to change all the model configurations to suit the new switch layout of the XE as compared to the X20Pro.  Indeed it physically worked.  But on radio startup, when you are taken to the checklist, the switches you move to set the Safe start positions, change the indication of the original switch position and not the changed switch assignments.
It's not a show stopper of course, but if it is possible to make the checklist indicate the updated switch positions, that would be really good.
Many thanks.   Mark

**Comment by kramgrand** [comment]
No one seems interested in this bug

**Comment by Dsrenger** [comment]
Dude, you opened the issue 2-3 workdays ago.

I don't know, but at my job I am not able to answer everything within 2-3 workdays...

**Comment by bsongis** [comment]
I am not able as well. Too much to do on all fronts!

**Comment by kramgrand** [comment]
Apologies, I made and assumption that what I reported was too minor to be looked at.

**Comment by kramgrand** [comment]
Thought to close this case as raising a new one with a better description of the issue.  4781

**Comment by kramgrand** [comment]
Am closing as have raised a new case with a better description of issue.  Case 4781

**Comment by kramgrand** [comment]
Hello FrSkyRC/ETHOS

I wondered if there is any chance someone could look at this. 
I know it is minor and it does not seem to effect any other modellers,  but as I switch between a X20Pro and EX-S and smart share models for instruction purposes it would really help me out.

Regards

Mark
