### ISSUE TITLE
ELRS script LUA error when „Enable WiFi“

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4751]
It is not possible to activate LUA WiFi with the new ELRS.
Consequence LUA error
Wifi remains off.
Tested with X20S and Radiomaster Nano 1.6 nightly
Tandem XE Happy Model slimline 1.5.18
X20 Pro Vantac 2,4   1.5.19

Greetings Eugen

![IMG_6621](https://github.com/user-attachments/assets/5d2d4600-a034-442b-8292-bfc631b56b0f)

![IMG_6622](https://github.com/user-attachments/assets/e1acf1af-903f-4138-bd38-122be6504050)

**Comment by bsongis-frsky** [comment]
Would you please confirm that my last commit fixes the problem? Thanks in advance!

**Comment by ahfynjj** [comment]
刚刚测试，没有解决

**Comment by yak55** [comment]
Hello Bertrand, I have just tested the new script.
It does NOT work on all 3 remote controls!!!

X20S 1.6 nightly
![S](https://github.com/user-attachments/assets/5593911b-e471-4e06-a837-c629604fea60)

X20PRO 1.5.19
![PRO](https://github.com/user-attachments/assets/4622837b-9249-44c4-b2ca-2ab04f1cef80)

XE 1.5.18
![XE](https://github.com/user-attachments/assets/f3b49ac0-f3df-406a-8529-eca8e00247c4)

Greetings Eugen

**Comment by Roemer-GER** [comment]
I am new to this forum. Therefore I hope, the post here is fine. I have a radiomaster nano ranger and like to use it with FrSky 18SE. 
I do have the same the challanges. Getting the error main.lua.226 as in the picture above. I tried to install the lua from expresslrs.org. This is not working on a Frsky system. On my Radiomaster 16S it works fine. I was thinking both systems are running OPENTX in the base. Firmware on Frsky 18SE is 1.5.18. EU on the Radiomaster Nano i have the stabel build 3.5.2 CE_LBT. Will be still worked on this problem?

**Comment by bsongis-frsky** [comment]
I am on it, give me one hour

**Comment by yak55** [comment]
Hello Bertrand,
At 9:50 pm  I just tested the script you uploaded 2 hours ago.
The transmitter was the X20S with 1.6 nightly.
The error is STILL PRESENT for me with this new script.
But it is a different new error.

Greetings Eugen

![IMG_6631](https://github.com/user-attachments/assets/bb363af1-1781-4d8d-b029-ace025a4c757)

**Comment by bsongis** [comment]
Rob nailed it. I added a typo, it was not my day ;)

**Comment by yak55** [comment]
Hello Bertrand,

Just tested on the X20.
Now it works .

Many thanks for your efforts on a "48 hour day".

Thank you, regards Eugen

**Comment by Roemer-GER** [comment]
Thank you for your efforts. It is working for me as well. Thanks for your fast support!
