### ISSUE TITLE
Feature Request: Trims Enhancement

### ISSUE THREAD

**Issue by Dfrazier1965** [FrSkyRC/ETHOS-Feedback-Community#4756]
Is it possible to add a feature to the trims to be more like the old OpenTx trims? If trims per FM is used, I would like the option to have it like it is now plus the ability to choose FM + Default FM trim or FM + previous FM trim.

**Comment by mawzthefinn** [comment]
That was added in 1.5 along with some additional features.

**Comment by Dfrazier1965** [comment]
I'm aware of the per flight mode trim but if it's there, I can't figure out how to have the default trim(FM0) added to (FM1) and so on like it was on OpenTx. Now, I haven't checked to see if the choice menu scrolls down farther than per FM. I'm not near my Tx to check. If it is there, please delete this request.

**Comment by mawzthefinn** [comment]
Set the trim mode to Custom, how to configure is covered starting on Page 132 in the current manual.

It's wildly more capable than OpenTX (since you are not limited to Flight Modes as selectors)

**Comment by Dfrazier1965** [comment]
Awesome, thank you. When I get back in town tonight I'll check it out.

If you can, please delete or close this thread unless I need to do it.
