### ISSUE TITLE
How do I find the right directory in LUA for transmitter with Flash

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#4758]
Hello Bertrand,
Version ETHOS 1.5.18 and 1.6
I wrote a LUA script "Farbwert" which runs smoothly on the X20S, but causes problems on the X20PRO and the XES if the scripts are in the flash memory.
Also on the XES in the upper display, are there any special features here?
How do I assign the correct path to Lua.
So far I have tried scripts/farbwert/lib/, ./lib/
./libWorks on the X20S, but not on the X14s, TWXLITES, there seem to be differences here?

/scripts/farbwert/ seems to work correctly on the transmitters without flash, but only to a limited extent on transmitters with flash. How do I do this correctly?
And yes, everything works perfectly in the sim.

**Comment by bsongis-frsky** [comment]
You should not use `/scripts/xxxx` in your script, but rather use relative paths, like `./lib/mybitmap.bmp`

Also 1.5.19 introduces the prefix `SCRIPTS:` which could be useful, but I will rather recommend the relative paths.

**Comment by Benno00** [comment]
Hello Bertrand,
how can I use SCRIPTS: with lua, 
print("SCRIPTS:",SCRIPTS) ? returns nil

**Comment by bsongis** [comment]
It may be used as prefix in paths, like `lcd.loadBitmap("SCRIPTS:/myscript/mybitmap.bmp")`
