### ISSUE TITLE
Tandem XE 1.5.19 Suite Update Error

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4760]
An error occurs when flashing firmware and system files with the Suite.

Manual download and installation of the file xe.Flash.zip is possible and ok.
Firmware 1.5.19 is correctly installed by suite.

Greetings Eugen

**Comment by Dsrenger** [comment]
"An error"

What's the error? 
Have a XE as well

**Comment by pmullen503** [comment]
I had a warning on a X18 in Suite (1.6 nightly) that the software could not be downloaded.  This was after downloading and successfully flashing new firmware.  So the warning was not correct. The info page confirmed new firmware was installed.

**Comment by yak55** [comment]
Hello, this is the Error.
Load XE.Flash.zip Manuale, unzip the file and copy in the Flash Drive on the Transmitter.
All is correct.
Eugen

![IMG_6630](https://github.com/user-attachments/assets/e1915458-4c15-4b8a-be90-a2c600547cbb)

**Comment by bsongis-frsky** [comment]
It should be good now
