### ISSUE TITLE
"Too many open files" error after lots of 'system.listFiles' calls in the Simulator.

### ISSUE THREAD

**Issue by Tedesc0** [FrSkyRC/ETHOS-Feedback-Community#4761]
I'm building a widget for Ethos and, at each wakeup cycle, it needs to check if a file has been created by another widget. After a little over 890 calls to 'system.listFiles' the Ethos starts to return the "**error 24 (Too many open files)**" error and the widget can no longer continue to run normally.

Since the widget needs to run the entire flight time this number of calls is reached after a few seconds.

Is this behavior by design?

Ethos information is in one of the screenshots below.
The Simulator is running on "Linux Mint 22 Wilma", kernel "Linux 6.8.0-48-generic".

Steps to reproduce the problem:
1) copy the attached widget to the scripts folder in the Ethos Simulator;
2) start the simulator;
3) add a page to any model and select the 'Stress Test' widget;
4) wait some seconds;
5) the error is shown in the debug window.

[main.lua.zip](https://github.com/user-attachments/files/17804755/main.lua.zip)
![Screenshot from 2024-11-18 15-27-08](https://github.com/user-attachments/assets/dc9f06d4-d001-45ff-b16a-1fadb5af9fbb)

://github.com/user-attachments/assets/bb481102-6107-4acb-bc12-2b2042c2cd02)
![Screenshot from 2024-11-18 15-29-46](https://github.com/user-attachments/assets/b1668a37-f4fb-4dab-839d-c1d83d77668d)

**Comment by bsongis** [comment]
I would recommend using `os.stat` to check if a file exists!

**Comment by Tedesc0** [comment]
OK.  I'll change to that.

**Comment by bsongis-frsky** [comment]
Fixed in the next release or in the next 1.6.0 nightlies

**Comment by Tedesc0** [comment]
But os.stat does not exist in the version of Ethos that I am using. I could only find the functions below in the os library.

_G["os"]=table: 0x757c380b8440
  ["mkdir"]=function: 0x555ab5aedcce
  ["time"]=function: 0x555ab5aee407
  ["difftime"]=function: 0x555ab5aee5a9
  ["rmtree"]=function: 0x555ab5aedc8b
  ["rename"]=function: 0x555ab5aedc33
  ["date"]=function: 0x555ab5aee1ba
  ["remove"]=function: 0x555ab5aedbf1
  ["clock"]=function: 0x555ab5aedd11


Please help me a little more on how to use os.stat().

**Comment by Tedesc0** [comment]
And by the way, this same error occurs if you try to "system.compile()" lots of LUA files.
