### ISSUE TITLE
X18RS ISSUES

### ISSUE THREAD

**Issue by alb1661** [FrSkyRC/ETHOS-Feedback-Community#4763]
No update information on ethos suite for any RS transmitter (i have the x18rs) also FSK and LORA not LIT ( on the tx display)but are in the ON postion and the tx is transmiting

**Comment by mawzthefinn** [comment]
No new firmware has been posted yet for the RS transmitters, so there's nothing to update. Only ETHOS 1.6 nightlies and ETHOS 1.5.19 Pre-release are currently available for the X18RS.

FSK and LORA would only be lit if there is telemetry being returned, not if the TX is transmitting.

**Comment by bsongis-frsky** [comment]
Right, X18RS 1.5.19 bins are available, they should be marked as official release soon!
