### ISSUE TITLE
Manuale in italiano della frsky x 20

### ISSUE THREAD

**Issue by Lukyluciano56** [FrSkyRC/ETHOS-Feedback-Community#4768]

**Comment by mgsanna** [comment]
> _No description provided._

https://github.com/FrSkyRC/ETHOS-Feedback-Community/raw/1.5/doc/%5BIT%5D%20Ethos%20User%20Manual%201.5.8.pdf

Aprire Issue per domande mi sembra inutile.... cmq ecco il link del manuale, in seconda battuta a breve verrà rilasciata l'ultima versione del manuale aggiornato sicuramente alla 1.5.19 o appena successive, in ogni caso questo manuale attuale è aggiornato alla 1.5.8 di ethos... Ultima cosa: su github e in questa repository si usa l'inglese.

It's not a good idea to open issue only for asking info, in any case here is the link to italian manual, other thing as soon as possible it will be released a new manual updated to 1.5.19 or even newer version, the last is updated to 1.5.8 of ethos...
Last but not least please use english  here in github.......

**Comment by mgsanna** [comment]
Closing as solution provided.....
