### ISSUE TITLE
1.5.19   XE-S   check_background.png    incorrect image

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#4769]
XE-S   Just updated to 1.5.19  this morning.
Check background .ping file in   XE-S    update is incorrect.

To Fix, I downloaded the 1.5.19  XE_FLASH.zip file, extracted it locally and copied the  check_background.png   to my TX Flash drive.

**Comment by bsongis** [comment]
Perhaps you had not updated the system bitmaps from Ethos Suite?

**Comment by Tonio62** [comment]
Même problème avec ma Xe, mise à jour effectuée  sur ethos suite incluant les bitmaps

**Comment by Tonio62** [comment]
![IMG_20241120_143215](https://github.com/user-attachments/assets/927bf2e3-d007-48e8-8459-f08238ecf6ff)

**Comment by kramgrand** [comment]
I performed update with by Ethos Suite same as Tonio62

**Comment by bsongis-frsky** [comment]
@Nicholas-Luoyi XE / V20 / X20-HD now have a dedicated xxx_FLASH.zip file!

**Comment by 3wintro** [comment]
Hello,
there is still a wrong image in the XE_FLASH.zip. It is not from the XE but from the X20.

**Comment by bsongis** [comment]
@3wintro Even using Ethos Suite 1.5.12?

**Comment by bsongis** [comment]
Ah there is a problem in the ZIP itself ?

**Comment by bsongis-frsky** [comment]
I just checked, inside XE_FLASH.zip, the bitmap named "check_background.png" seems OK, am I wrong?

**Comment by 3wintro** [comment]
![screenshot-2024-11-21-68880](https://github.com/user-attachments/assets/d0ca82bb-2b2b-4a10-92b9-524b80f1d40c)
I have just redone the firmware 1.5.19 via the Suite 1.5.12.

**Comment by bsongis-frsky** [comment]
OK. But it's not the zip I think, because I have checked it just now. Have you used Ethos 1.5.12?

**Comment by 3wintro** [comment]
Yes 1.5.12

**Comment by Nicholas-Luoyi** [comment]
Ah I just found the issue. This change was originally planned to be implemented in version 1.6.0, so Suite has a check for 1.6.0. However, we temporarily released version 1.5.19. In Suite 1.5.12, which was released yesterday, I forgot to modify the check from 1.6.0 to 1.5.19, so the fix didn’t take effect. I will re-upload a fixed version shortly.

**Comment by MIKE-DAILEY** [comment]
Thanks, the version of SUITE 1.5.12. you just uploaded fixed the issue with the XE Flash files.

**Comment by 3wintro** [comment]
Thanks for the effort, I'll give it a try tonight.

**Comment by bsongis** [comment]
> Ah I just found the issue. This change was originally planned to be implemented in version 1.6.0, so Suite has a check for 1.6.0. However, we temporarily released version 1.5.19. In Suite 1.5.12, which was released yesterday, I forgot to modify the check from 1.6.0 to 1.5.19, so the fix didn’t take effect. I will re-upload a fixed version shortly.

My mistake. Agreed that it should have been modified only in 1.5.19. Merge are always difficult!
