### ISSUE TITLE
Feature Request: is it possible to use the servo output as a servo tester.

### ISSUE THREAD

**Issue by Asimos32** [FrSkyRC/ETHOS-Feedback-Community#477]
if it is possible to use the servo output as a servo tester.
it could be a nice function for set up.

**Comment by MIKE-DAILEY** [comment]
If you look in the Mixer Library there is a test mix.

**Comment by loetefix** [comment]
i think he means the updateport or am i wrong

**Comment by Asimos32** [comment]
yes, the update port it can be very useful  if it can be used as a servo tester.

**Comment by MrD-RC** [comment]
You mean the SmartPort socket on the transmitter. That would be a useful feature. With how great the X20 pots are, the centre position would be easy to get.

**Comment by loetefix** [comment]
The idea is great. But the proplem i see is that the port isnt resilient enough to supply a servo.

**Comment by MrD-RC** [comment]
@loetefix as in the internal traces aren’t strong enough for the amp draw?

**Comment by loetefix** [comment]
I don´t realy know it, but usualy there are small FET´s that can drive only small current. I also don´t know if there is a protection for overload if a servo blocked and takes relative high current.

**Comment by Asimos32** [comment]
i have worked with this function on 'PowerBox Core' and i liked it. so if its possible why not...

**Comment by bsongis-frsky** [comment]
On a PowerBox it's possible to do this, because it is able to provide enough current, but not this port which is there only for updates, not power!

**Comment by MrD-RC** [comment]
Maybe this is something that could be passed on to FrSky as an idea for future transmitters? It sounds like a useful feature to have.
