### ISSUE TITLE
RB25S and Xact Servo Incompatibility

### ISSUE THREAD

**Issue by BJR981S** [FrSkyRC/ETHOS-Feedback-Community#4770]
I have found this issue with the RB25S.

The servos once configured will operate on the RB25S but unreliably.

Once configured, means you cannot configure them on the RB25S you need to use a TD or RW Rx to do that.

The process to configure an Xact servo is to capture it with add sensors in the telemetry menu.
You then select one of the telemetry lines associated with that servo and select device config.

With Device config you can then set the Phy ID and the Software group ID. and the Servo Channel number. Then save to flash.

You have to do this one servo at a time as the all default to the same channel 1 settings. (After you upgrade the FM)

The device config on the RB25S will not display the settings and they are greyed out. So no setup possible.

Normally on startup the Xact Servos are interrogated and there settings become available. (TD/TW Rxs)

The does not happen on the RB25S.

This warning relates to, as these settings are not loaded, there is a probability that the Servo will not react to its previously programmed centre  or end points correctly.

These can randomly wander.

**Comment by mawzthefinn** [comment]
https://github.com/FrSkyRC/RF_Feedback_Group/issues/66 is where the action is
