### ISSUE TITLE
Missing components updating Ethos 1.6.o Nightlies

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#4771]
I think this is caused by the name of the file of  Flash contents, (i.e.: X20_Flash.zip) is on github X20_FLASH.zip.zip
This I think can cause an error on the suite....

![Screenshot 2024-11-21 094842](https://github.com/user-attachments/assets/a451f128-02f4-4b9b-a932-d53811f3a017)
![Screenshot 2024-11-21 095425](https://github.com/user-attachments/assets/7d4a8f84-0bc5-41f1-a055-5bee64724682)

**Comment by bsongis** [comment]
zip.zip files are not good!

**Comment by mgsanna** [comment]
> zip.zip files are not good!

All the Flash content files are zip.zip

**Comment by bsongis-frsky** [comment]
Fixed

**Comment by mgsanna** [comment]
ThanksInviato da iPhoneIl giorno 21 nov 2024, alle ore 12:38, Bertrand Songis @ FrSky ***@***.***> ha scritto:﻿
Fixed
