### ISSUE TITLE
need model.setOutput(index, value) api

### ISSUE THREAD

**Issue by ZyonMo** [FrSkyRC/ETHOS-Feedback-Community#4772]
This api is the edgeTX system. I now want an api that can directly control the output value of any channel through a widget script, and restore the original control of TX if it is closed.

model.setOutput(index, value)
Set servo parameters

@status current Introduced in 2.0.0

Parameters
index (unsigned number) channel number (use 0 for CH1)

value (table) servo parameters, see [model.getOutput()](https://luadoc.edgetx.org/part_iii_-_opentx_lua_api_reference/model-functions-less-than-greater-than-luadoc-begin-model/getoutput) for table format

Return value
none

**Comment by mawzthefinn** [comment]
What's the use case?

On the face, this appears to be another case of unsafe output handling in EdgeTX (like the Override Special Function) that should not be duplicated.

**Comment by bsongis** [comment]
I prefer the use a Free Mix with a Lua Source as input, I wouldn't consider that Lua changes a channel value in the back of the user!

**Comment by mawzthefinn** [comment]
> I prefer the use a Free Mix with a Lua Source as input, I wouldn't consider that Lua changes a channel value in the back of the user!

Agreed, and use the Lock mixer type if you need to force the output to the desired value.

**Comment by Jiki-Mo** [comment]
At present, I don't know which method is appropriate, my use case is to do an autopilot, after the user turns on the enable switch, the script will control the joystick channel output according to the telemetry data of the helicopter FC, and take over the helicopter, so as to achieve the purpose of automatic flight, until the user turns off the switch.

**Comment by ZyonMo** [comment]
> What's the use case?
> 
> On the face, this appears to be another case of unsafe output handling in EdgeTX (like the Override Special Function) that should not be duplicated.

At present, I don't know which method is appropriate, my use case is to do an autopilot, after the user turns on the enable switch, the script will control the joystick channel output according to the telemetry data of the helicopter FC, and take over the helicopter, so as to achieve the purpose of automatic flight, until the user turns off the switch.

**Comment by mawzthefinn** [comment]
> > What's the use case?
> > On the face, this appears to be another case of unsafe output handling in EdgeTX (like the Override Special Function) that should not be duplicated.
> 
> At present, I don't know which method is appropriate, my use case is to do an autopilot, after the user turns on the enable switch, the script will control the joystick channel output according to the telemetry data of the helicopter FC, and take over the helicopter, so as to achieve the purpose of automatic flight, until the user turns off the switch.

That is not a safe way to implement an autopilot. You have FAR too much lag time in the telemetry connection to achieve controlled flight in a practical manner, combined with relatively slow executing Lua. 

Also Lua sources to a Free mix will work fine for outputting values in this case (it's just everything else in the link that's a bad idea)

Autonomous systems MUST be implemented at the FC level, not down a potentially laggy telemetry link. This goes doubly for a helicopter which is the least stable type of RC aircraft. 

I'd suggest looking at Ardupilot, which supports traditional helis.

**Comment by bsongis-frsky** [comment]
Agreed. The auto-pilot must be calculated on the model, not the radio. Unless a very slow response is OK of course. In this case a FreeMix + Lua source will be OK.

Ethos 1.6.0 will support `model.createMix(...)`

**Comment by ZyonMo** [comment]
> Agreed. The auto-pilot must be calculated on the model, not the radio. Unless a very slow response is OK of course. In this case a FreeMix + Lua source will be OK.
> 
> Ethos 1.6.0 will support `model.createMix(...)`

Yes, it is best to implement it on FC. The remote control can only be controlled slowly. Of course, this is just an idea. It needs to be tested experimentally. If Lua can support this, I still want to give it a try.

**Comment by ZyonMo** [comment]
Ethos 1.6.0 will support model.createMix(...)，Waiting for the update, I'll try it then.
