### ISSUE TITLE
Ethos 1.6.0 Nightlies - Updated 3.0 Stab Config doesn't show

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#4774]
Installing on my "beta nightly radio" ethos 1.6.0, updated to 3.0 td isrm and updated also beta scripts from RF beta firmware... but there is a problem I cannot see nor config the new Stab script..

Only in simulator show up but as obvious i cannot test it in real life application

everthing is else is showed. any suggestion?

Simulator
![Screenshot 2024-11-21 213213](https://github.com/user-attachments/assets/e31fb6c4-cc8d-46bf-9530-4ea51ef8a3e7)

RealRadio
![IMG_8952](https://github.com/user-attachments/assets/ab5487b9-6df2-4cbf-af06-de6325815e54)

**Comment by Nicholas-Luoyi** [comment]
Do you have a Suite 1.6.0?

**Comment by mgsanna** [comment]
No, where I can find 1.6 ethos suite?
@Nicholas-Luoyi

**Comment by Nicholas-Luoyi** [comment]
Now you can see it as a pre-release

**Comment by mgsanna** [comment]
Installed Ethos suite 1.6.0, reflash of everything from scratch on radio, suite say that config stab scripts are installed but the situation remain the same on radio..... it install and work as a charm other scripts... 
@Nicholas-Luoyi  any advice?

**Comment by Nicholas-Luoyi** [comment]
So you install the script through the Lua lib?

**Comment by Wolepo** [comment]
Both work. The LUA is called up directly in an X10S Express.
![Sensor konfig Sim](https://github.com/user-attachments/assets/d49b949f-f366-4f4b-b473-7d4bc0db8fe2)
Here in the sim of the X20S
![Sensor konfig TX](https://github.com/user-attachments/assets/c05feea5-4acf-461c-97a6-d5cfa693e18c)
And here in the transmitter X10S Express

**Comment by Nicholas-Luoyi** [comment]
Just uploaded the 3.0.0.18. And it should work now

**Comment by Nicholas-Luoyi** [comment]
You could help to check the update feature for Lua in the same time. Thanks!

**Comment by mgsanna** [comment]
> You could help to check the update feature for Lua in the same time. Thanks!

Yeahhh It works!!!!
![IMG_8953](https://github.com/user-attachments/assets/41280b8b-88be-42e0-a794-de92d12fda0f)


Thanks !!!!

**Comment by mgsanna** [comment]
> Both work. The LUA is called up directly in an X10S Express. ![Sensor konfig Sim](https://private-user-images.githubusercontent.com/90325526/388882406-d49b949f-f366-4f4b-b473-7d4bc0db8fe2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjk0MjUsIm5iZiI6MTczMjI2OTEyNSwicGF0aCI6Ii85MDMyNTUyNi8zODg4ODI0MDYtZDQ5Yjk0OWYtZjM2Ni00ZjRiLWI0NzMtN2Q0YmMwZGI4ZmUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5NTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MTliYzEzNzExMDRkZGNmZWQ3MmVmYzBmYzAwYWIwMzQ2NGM3Yzg2YTI0YjEzNGNiNmRiNmUzMmUyZDNkNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eSo72YWqUPxQMh4_oAYKXjdLRvMgqyAGbpEujih3nL0) Here in the sim of the X20S ![Sensor konfig TX](https://private-user-images.githubusercontent.com/90325526/388882659-c05feea5-4acf-461c-97a6-d5cfa693e18c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjk0MjUsIm5iZiI6MTczMjI2OTEyNSwicGF0aCI6Ii85MDMyNTUyNi8zODg4ODI2NTktYzA1ZmVlYTUtNGFjZi00NjFjLTk3YTYtZDVjZmE2OTNlMThjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5NTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YjUyOWRmMzUwMDcyM2Q4NjM5ODBjZDhmOWI0MTEwMjRiZjY5MGQxNTlhYmQyYzQyOTQyNjc2ZmVhOWU1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kjBItU3A9n69dpVEPdpI1paWc_3o0k98dCPHt2MgNEA) And here in the transmitter X10S Express

Yes normal SXR works, but with 3.0.0.15 version of the ADV stabilizer, doesn't show up in real radio instead of simulator that was already showing up and working..... in any case with the new version of the scripts everything works as expected!!!!
