### ISSUE TITLE
how refresh configure screen

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#4776]
Hello Bertrand,

if I select a source in the configuration selection with
line = form.addLine("Source:") form.addSourceField(line, nil, function() return widget.source end, function(newValue) widget.source = newValue end) 
the widget.source is still not known in the current configuration, how can I update the current configuration after selecting the widget.source without leaving it?

Thank you very much

**Comment by bsongis-frsky** [comment]
Why don't you setup a default widget.source before creating the form? You may also clear the form and populate again the fields.
