### ISSUE TITLE
CSV file delimiter choice

### ISSUE THREAD

**Issue by phaedradg** [FrSkyRC/ETHOS-Feedback-Community#4778]
It would be interesting to have more choice in which delimiter is being used in the log files.  Now it seems to be a comma.
I encountered a problem when trying to visualize a csv log file in an external tool, because the RB (Redundancy Bus) state field contained a string with multiple status messages, separated by commas.  This makes a comma-delimited csv file invalid.  If I could select a semicolon for instance, this problem would be solved.
The "RB State" field has this value in the erroneous csv file:
"RX3 Failsafe, RX3 Lost Frame, RX3 Connection Lost, RX3 No Signal"
I end up with 3 less data columns than indicated by the header.

**Comment by mawzthefinn** [comment]
By definition any CSV file can only use a comma separator. CSV actually has meaning, standing for Comma Separated Values

Looks like the header needs expansion any time the field has multiple values in one telemetry field, or ETHOS needs to rewrite any delimiters included in the data (ie rewrite commas to semi-colons if there's commas in the data being written to the CSV file)

**Comment by noamkrief** [comment]
@mawzthefinn 
Perhaps when it originated, the technique matched the acronym. 
These days, we don't take the acronym too literally :)

We should separate the fields with ","  (double quote comma double quote)

In my line of work we deal with so called CSVs all the time from various data sources. Sometimes they are separated by  ||| or ~~~ just to be a more unlikely case those exist as part of the data.

**Comment by robthomson** [comment]
Just needs quotes and \ in any field quotes contained withing a field.

Simples

**Comment by bsongis-frsky** [comment]
Keeping the simple comma makes our files compliant with all CSV decoders. We have to escape the comma inside fields.
