### ISSUE TITLE
use Font XXXL anx XXXXL at the same time

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#4779]
FW 1.5.19 with XE or Simulator.
If i use only one of the big fonts (XXXL od XXXXL) my lua works fine.
But if i try to use both fonts one of the big fonts do not work.

I get the two fonts with 
FONT_XXXXL = lcd.loadFont("FLASH:/fonts/xxxxl.fnt") 
FONT_XXXL = lcd.loadFont("FLASH:/fonts/xxxl.fnt") 
the return values are for the first loaded font FONT_XXXXL = 0xF00 and for the second FONT_XXXL = **0x1000**

if i use lcd.font(FONT_XXXL) it loads the font FONT_STD. Font STD== 0x0000.
I have looked an all predifined base FONT variables, they are all less than 0x1000
So i think there is a little problem in lcd.font(value). I think the parameter will be masked to value &0xFFF.

is that intentional or  a bug.
Thanks for your help.

Bye 
Jörg

**Comment by Storchy1** [comment]
Can someone confirm this or is it just me

**Comment by bsongis-frsky** [comment]
Ethos 1.7 will allow 32 fonts

**Comment by Storchy1** [comment]
Thanks a lot
