### ISSUE TITLE
Feature Request: Tastatur oder Textvorschläge

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#478]
Es wäre eine deutliche Erleichterung, wenn man eine kleine Tastatur oder Textvorschläge zur Auswahl hätte.
Da es mit dem Scrolrad sehr lange dauert und recht umständlich ist. 

Textvorschläge:
Wie z. B. Flugphase Akro, Thermik, Telemetrie, Motor An, Motor Aus....

**Comment by loetefix** [comment]
has already been suggested here https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/189

**Comment by bsongis-frsky** [comment]
I am sorry, but I cannot speak German.
I will mark it as a duplicate of #189 as loetefix suggests
