### ISSUE TITLE
Missing remote version on bootloader

### ISSUE THREAD

**Issue by nivaldin** [FrSkyRC/ETHOS-Feedback-Community#4780]
Hi folks, can someone help me? I can't update my radio, cuz ethos suite won't enter bootloader to do it.

![Captura de tela 2024-11-22 171054](https://github.com/user-attachments/assets/0a3f2117-a227-4ba6-97d0-9e9820a82d9e)

**Comment by mawzthefinn** [comment]
INstall ETHOS Suite 1.5.12 or 1.6.0 Preview. Both resolve this issue.
