### ISSUE TITLE
ADC2 wrong scaling

### ISSUE THREAD

**Issue by Didier-L** [FrSkyRC/ETHOS-Feedback-Community#4783]
On all the new rx series, A2 (ADC2) allows voltage measurement from 0 to 35v. But whereas all telemetry values are directly usable, ADC2 value must be scaled up. Whereas it made sense on "old" rx where max voltage was 3.3v then resistor divider was mandatory, it is no more the case.
I made some measurements with a lab power supply (5v to 30v) in order to get the right ratio on all my rx.
The result:
Archer Plus: 7 rx (GR6+, R10+ and SR10+): min value = 141.1%, max value = 142.8%, average = 141.8%
TW: 5 rx (GR6, GR8 and SR12): min value = 141.2%, max value = 144.9%, average = 143.1%
Global average = 142.4%
So, would it be possible to upscale ADC2 in the coding by this average value (or a close one) in order to have something directly usable like all other telemetry items?

Didier

**Comment by Didier-L** [comment]
Thank you Bertrand for taking into account my comment.

One question : what correction factor did you take : 142.4% or another number ?

It is to avoid me to reperform the whole calibartion with a power suply.
Didier

**Comment by bsongis** [comment]
(16 / 4096) * 3300 (Ref) * 11 = 141.796%

**Comment by Didier-L** [comment]
Thank you !

**Comment by Didier-L** [comment]
If i may make a comment on the 1.7 release description concerning this topic : 

"ADC2 sensor default scaling set to 141.8% to match the ration on non ACCST receivers"

It may be misleading. The main reason is to have the correct voltage directly from telemetry sensor like "Tension Rx" without any post scaling to be done.

I would propose : "ADC2 sensor default scaling set to 141.8% to get directly the right voltage value"

**Comment by i3dm** [comment]
can this fix be implemented in 1.6? its very useful to the users
