### ISSUE TITLE
Ethos suite 1.5.11

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#4785]
as always crash's on ethos suite 1.5.3 up   
![suit](https://github.com/user-attachments/assets/9a9b3ab5-d962-4c03-a858-651c1fe40890)

[Ethos1.5.11-crash-logs.zip](https://github.com/user-attachments/files/17893064/Ethos1.5.11-crash-logs.zip)

**Comment by robthomson** [comment]
Odd.  Never happens for me.

**Comment by yak-54** [comment]
2 pc and laptop all the same

**Comment by FlipAirboost** [comment]
> Odd. Never happens for me.

@robthomson 
We are all very happy for you.

Best regards Phil

**Comment by FlipAirboost** [comment]
#4678
Same for me. 
Only the special version of 1.5.11 (2) from @Nicholas-Luoyi  works for me.
Regards Philippe

**Comment by mawzthefinn** [comment]
Does suite 1.5.12 or 1.6.0 work?

**Comment by yak-54** [comment]
> Does suite 1.5.12 or 1.6.0 work?

this all started 1.5xx 
Its got to the stage now it wont disconnect drives  and when it does it corpus the radio bin i get asked to do a radio calibration  the next power on
its at the stage now i using my X12S on  1.4.17 to fly big stuff and only use X20 pro on my foamies

i think all my issues are related to ethos suite and windows and the way it ejects the drives 

yesterday i formatted the nad drive copied and pasted all the file manually and did the update as well without  ethos suite

**Comment by Nicholas-Luoyi** [comment]
This should be fixed in the 1.5.12. We have a long release list which is fetched from github and now github won't reply the whole list. So you can see "Missing remote version" for the bootloader

**Comment by yak-54** [comment]
1.5.12  installed will not detect radio in bootloader mode
![Untitled2](https://github.com/user-attachments/assets/f070d4f4-ec45-4862-b813-664e0e62813d)

**Comment by yak-54** [comment]
yes i do run it as admin

**Comment by Gordoni-Racing** [comment]
Is this related to my issue of missing remote bootloader & FW update hangs (Windows & MacOS, X18 & X20S)?

EDIT: Never mind I found the revised Suite on pre-release which fixed all my issues.
