### ISSUE TITLE
Ethos Version

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#4786]
Hello.
I'm currently running on Ethos 1.5.15. May I choose which release I install such as, 1.5.18 or1.5.19 or 1.6.0 (when available). Or must the update be in release order?

thanks

**Comment by Dsrenger** [comment]
You can choose and skip versions.

No order necessary.

**Comment by mgsanna** [comment]
no order is necessary

**Comment by RealTadango** [comment]
Don't skipt a major version, so no upgrade from 1.4.x to 1.6.x for example. Always go to the next major or you can damage you models.

**Comment by bsongis-frsky** [comment]
Answer provided, thanks!
