### ISSUE TITLE
X14S Mixer icon missing

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#4788]
Pls see screenshot below. Not sure if a missing icon file, or it's not loading for some reason. 

The only unusual aspect is that I flashed 1.5.19 (over 1.4.17) directly from the .bin file on github, rather than through the Ethos Suite update process. (Reason being that Suite was repeatedly failing with "Start uploading" message).

![IMG_4134](https://github.com/user-attachments/assets/286b7b5c-59a9-4d48-b69b-c37c21825fbe)

**Comment by Nicholas-Luoyi** [comment]
Are you using Sutie 1.5.12?

**Comment by RC-SOAR** [comment]
Thanks for quick response. I'm using Suite 1.5.12 - should I downgrade?

**Comment by Nicholas-Luoyi** [comment]
It should work fine. Do you have an error message or a crash log

**Comment by RC-SOAR** [comment]
I had problems with flashes freezing on 'Start updating', with both 1.5.11 and 1.5.12.  Attached is a screenshot. No other messages. I tried updating just the firmware on its own, and that failed as well. Where should I look for logs?

![2024-11-24_231747](https://github.com/user-attachments/assets/e671941f-fc2d-4cde-bbc3-e6c69e7735c6)

**Comment by Nicholas-Luoyi** [comment]
Well. I think your 1.5.12 may be outdated? Would you please try to download the 1.5.12 agian. It was updated last Friday.

**Comment by RC-SOAR** [comment]
My copy of Ethos Suite 1.5.12 must be the latest version as I only downloaded it a couple of hours ago.  It's for a review sample of the X14S which I received last week. It arrived with Ethos 1.4.17 installed.

Managed to flash the RF firmware successfully, it's the Ethos firmware which is failing to flash, and the bootloader says 'missing remote version' - I presume that's referring to the server.

**Comment by Nicholas-Luoyi** [comment]
I will check. I specifically targeted this issue for a fix.

**Comment by RC-SOAR** [comment]
Thanks! It's getting late here so I'll get some sleep.

**Comment by Nicholas-Luoyi** [comment]
A new version is uploaded. Will check your feedback tomorrow

**Comment by RC-SOAR** [comment]
I can confirm it's fixed in the latest Suite 1.5.12 - the firmware flashes and the mixer icon appears correctly. Thanks!
