### ISSUE TITLE
Request - When I select clone a special function, auto select the new one ready for editing?

### ISSUE THREAD

**Issue by TWSreviews** [FrSkyRC/ETHOS-Feedback-Community#479]
Recommendation for improvement 
I create a lot of special functions. Every time I clone a special function it goes to the bottom of the list.
However, it would be nice if it was auto selected ready to edit. 
It would be a more logical flow of programming.

**Comment by Hobby4life** [comment]
That is really a great idea!

**Comment by bsongis-frsky** [comment]
If it is done, it must be changed everywhere the same:
- Special Functions
- Logic Switches
- Mixer
- Timers
- Curves

**Comment by TWSreviews** [comment]
> If it is done, it must be changed everywhere the same:
> 
> * Special Functions
> * Logic Switches
> * Mixer
> * Timers
> * Curves

Absolutely 
It’s should be the same for all.
You create a clone then logically you need to amend it as the next step. 
Makes perfect sense.

When you have a big list you then have to scroll down to find the clone. You then overshoot and it’s back to the beginning of the list. 
more logic to have the clone selected

**Comment by Nicholas-Luoyi** [comment]
I have checked. We just miss it in Special Functions. Please  see Logic Switches, Mixers, Timers, Curves if it has been done already.

**Comment by bsongis-frsky** [comment]
@Nicholas-Luoyi would you please prepare a PR for 1.0.9? Thanks!
