### ISSUE TITLE
Updated translation Ethos OS Norwegian

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#4790]
Updated translation Ethos OS Norwegian

[no.csv](https://github.com/user-attachments/files/17901268/no.csv)

**Comment by bsongis-frsky** [comment]
Hi @mmasch I would like to have 1.6.0 RC2 tonight, would you have time to check the translations in this branch? They are public and in this repository now. Feel free to ask if you need help!

**Comment by mmasch** [comment]
Hello Bertrand. I find Ethos 1.6.0 RC1 in Github/Code/Released,  but not RC2. I also find Ethos Suite 1.6.0 RC2 in the same place. I am not sure where else to look?B.r. Morten. Sendt fra min iPhone30. nov. 2024 kl. 13:01 skrev Bertrand Songis @ FrSky ***@***.***>:﻿
Hi @mmasch I would like to have 1.6.0 RC2 tonight, would you have time to check the translations in this branch? They are public and in this repository now. Feel free to ask if you need help!

**Comment by mmasch** [comment]
Hello Bertrand.

I have successfully gotten the norwegian .csv file from 1.6.0 RC2, and corrected the missing translation.
The file is attached here.

Best regards, Morten Masch, Norway.

**Comment by bsongis-frsky** [comment]
Hi mmasch, the files cannot be attached from emails to github, you have to use this interface directly!
