### ISSUE TITLE
V 20 bootloader

### ISSUE THREAD

**Issue by robb1364** [FrSkyRC/ETHOS-Feedback-Community#4794]
Can anyone help me to find bootloader for Kavan V20. This is the only component which I was not able to update with Ethos suite.
Thank you

**Comment by mawzthefinn** [comment]
Pretty sure latest is 1.4.15 like most other radios

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.4.15/V20_BOOTLOADER.zip

**Comment by Nicholas-Luoyi** [comment]
You could now update it with Suite 1.5.12. And yes, manual update is OK

**Comment by robb1364** [comment]
Thank you very much for very fast reply!! Do you know what version of the FrSky X20 Kavan V20 is?

**Comment by robb1364** [comment]
Thank you both for great support!!!

**Comment by mgsanna** [comment]
> Thank you very much for very fast reply!! Do you know what version of the FrSky X20 Kavan V20 is?

Here is the bootloader for the V20 .... 
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.4.16/V20_BOOTLOADER.zip

The release was Ethos 1.4.16 just like 1.4.15 for the X20/X20S the last booloader updated

Have a nice day

**Comment by robb1364** [comment]
Hello Marco,

Thank you once again!

Robert

**Comment by mawzthefinn** [comment]
Closing as solution has been provided
