### ISSUE TITLE
[Suite 1.6] Need a "Dismiss" or "Close" button on the popup about updating

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#4796]
I get the idea of wanting to have the popup, and I think it's good, but "Go To Update" should not be the only button.  You should be able to dismiss it and go about what you're doing without being forced to go to the Update page first.
![image](https://github.com/user-attachments/assets/4f9872de-40ee-42b5-87dd-2af2f4a8fa6c)

**Comment by spoke2570** [comment]
Really this is true for any pop-up. Should be able to just close them in case the selection was made erroneously.

**Comment by Wolepo** [comment]
You can simply select a different category in the overview column on the left. The open window is then closed.
