### ISSUE TITLE
X14 (1.5.19) - Device Config - SxR - not scrolling 

### ISSUE THREAD

**Issue by adibbins** [FrSkyRC/ETHOS-Feedback-Community#4798]
Hi All,

Tx: X14
Ethos: 1.5.19

I hope I haven't missed something, I'm trying to configure a TW S8R, it's calibrated, and now I'm trying to configure it, set parameters like sxr enabled, or Aileron inverted, quick mode etc. but I can't scroll off the first option "Module - both module/Internal module/external module/S.Port connector" to the next options, the scroll wheel is moving through the options? Thanks

**Comment by Dsrenger** [comment]
It is a TW SR8 not a TW S8R (which is not existing)

You configurate SRx receiver via a LUA.
in 1.5.19 the device config SxR menu is just for old SxR receivers. 

You can find the latest Lua scripts here:
https://www.frsky-rc.com/tw-sr8/

**Comment by mawzthefinn** [comment]
Closing as answer provided
