### ISSUE TITLE
X18RS No Module in Ethos Suite 1.5.12 potential Bug

### ISSUE THREAD

**Issue by Joetrin** [FrSkyRC/ETHOS-Feedback-Community#4799]
Hi All,

A friend of mine has purchased a brand new X18RS FCC Version in Canada.
Unit works and binds to models but when he connects it to Ethos suite, the following screens are shown.

Note:
Suite 1.5.12
Ethos 1.5.19 on X18RS

![Ethos Screen 1](https://github.com/user-attachments/assets/79335a66-01fd-4686-a8c8-c8661fe8bd4c)
![Ethos Screen 2](https://github.com/user-attachments/assets/5206ca53-d754-488b-af20-06d79fd2eadf)

**Comment by Nicholas-Luoyi** [comment]
RF 3.0.0 has been uploaded
