### ISSUE TITLE
Replace funcion limited

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#48]
When using replace it can only be selectet min,0, max value. We need free selection. Example: when setting headtracker, I need to tur it off by replacing value with center value, but since all servos are not same, I need to set some offset to get camera in right position.

**Comment by bsongis-frsky** [comment]
Are we discussing about the free mixer?
You can configure it with:
- source = 0
- offset = -10%
I think it's exactly what you ask, feel free to reopen if needed

**Comment by KAD370** [comment]
No, pre-set mix on bottom of mixes
