### ISSUE TITLE
improve moving lines (mixer/logical switch ect.)

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#480]
It is not realy nice to move lines. It is possible to move a line up or down step by step. It would be great if there is only a general move option. So you select move and the line inverts. Then you scroll the wheel and move the line to its new position. Hit enter again to close the action.

**Comment by MrD-RC** [comment]
Thank you for posting this. I thought this on Friday while editing a model, but forgot to post. 

- Press enter for menu
- Select **move**
- turn the jog wheel to find the new position
- Press enter to confirm the new location

That would be awesome.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/124313058-a2423480-db70-11eb-8424-beac03f1a272.png)

**Comment by loetefix** [comment]
Nice
