### ISSUE TITLE
Receiver TD-R10 S.Port on small 4 Pin connector on the side of the receiver

### ISSUE THREAD

**Issue by Dietsch1** [FrSkyRC/ETHOS-Feedback-Community#4802]
This comment is from an old post in Nov 2022
"FrSky confirmed a long time ago that the 4-pin connector is only for updates and AIN2."
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1619

Is this still the case?

Regards Dieter

**Comment by mawzthefinn** [comment]
Yes, newer receivers correctly label this port as Upgrade/AIN
