### ISSUE TITLE
Removing Pre-Release tags without note

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#4803]
Hi Bertrand,

With the updates for the Suite, I have noticed again that the pre-release tag is simply removed without it being clear which file version was the last one. For the Suite 1.5.12, the release date is last week, which is completely wrong for the release ...

Can you please generally omit the misleading "pre-release" and work with release candidates (RCx) as usual? And above all, don't simply overwrite the files of an already released RC version. If several release candidates are required, then that's the way it is and the process is transparent for everyone.

**Comment by bsongis** [comment]
@Nicholas-Luoyi

**Comment by Nicholas-Luoyi** [comment]
Well. We will have Release RC later...
