### ISSUE TITLE
Smal issue in Suite 1.6.0 RC1 (Missing remote version)

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#4805]
Please have a look.
![image](https://github.com/user-attachments/assets/172246b5-f86f-4593-b595-922b6f5563a8)

**Comment by mawzthefinn** [comment]
1.6.0 RC1 is still building, so the latest remote version for the X20 is in fact missing (the X20S just became available 15 minutes ago)

**Comment by mawzthefinn** [comment]
And with all assets built now, it does look like there indeed is an issue only on the Radio Information page. The ETHOS page is reporting normally.

**Comment by mszulen** [comment]
Yep, having same issue, 
<img width="636" alt="Screenshot 2024-11-29 at 21 17 01" src="https://github.com/user-attachments/assets/c1592196-7b36-4e8c-946e-c2c2fda0c897">

plus, after update I'm getting his message:
<img width="960" alt="Screenshot 2024-11-29 at 21 15 02" src="https://github.com/user-attachments/assets/aefb0fb8-e9b7-4b31-b43b-08e9d70a1bc0">

**Comment by Nicholas-Luoyi** [comment]
Yes. It's a known issue
