### ISSUE TITLE
Ethos 1.6.0 RC1 X20S is missing!

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#4807]
Ethos 1.6.0 RC1 X20S is missing!

Hello Bertrand, I would like to test with my test transmitter X20S.
Can you please add the firmware?

Thanks Greetings Eugen

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/90b81718-b9d4-4e75-8c7d-e61b58405626)
