### ISSUE TITLE
X20S Summery Test when and why "Sensor Lost"appears

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#481]
Summery after 2 Days Test and all combinations of TX, RX, Sensors

Telemetry Test "Sensor Lost" 
4 TX  X20S, X9D+SE 2019, X9E, TX16S  all LBT, no FCC, with  HF-Modul TD, ISRM, XJT, 4in1 MPM
4 RX, X6R, S6R, G-X8, GR8
4 Sensors  FLVSS, GPS, Vario, Neuron60
All RX, Tx ACCST, ACCESS,  with latest V2.1.x at TX and RX

X20S with  V1.0.9.C4 TD V2.1.8  LBT
X20S works with all 4 RX,  with all internal Values, NO "Sensor  Lost", all fine
X20S works with all 4 RX and a FLVSS with internal and external Values, NO "Sensor Lost", all fine
X20S works NOT  if other Sensors or more as one Sensor in Chain, "Sensor Lost" 
Sensor Lost starts after 30s ....60s  then allways every 10....20s

All other combinations of Tx and Rx work flawlessly, no sensor lost, never, not one, works since years
its a Problem of ETHOS  or TD-HF- Modul 

Test detail see link

_Originally posted by @hrenz in https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/357#issuecomment-860001978_

**Comment by WismyYao** [comment]
Thanks for your tests

**Comment by NMO81** [comment]
I have noticed that on SR6-10 receivers only 1 MLVSS is enough to generate this ''Sensor Lost", you can see in the telemetry menu that the update dots are blinking very irregular.

**Comment by hrenz** [comment]
think they have a big Problem with telemetry-sensors RX, TX,  ETHOS, ACCESS, ISRM, TD, LBT,
But not with ACCST,XJT, IXJT, LBT, FCC

**Comment by bsongis-frsky** [comment]
What do you mean by telemetry-sensors TX, ACCESS, ISRM, TD, LBT, I don't know them

**Comment by Hobby4life** [comment]
I think he means there is an issue with telemetry transmission between TD-ISRM module and receivers.
TD-ISRM doesnt handle smartport telemetry that well.

**Comment by bsongis-frsky** [comment]
@Hobby4life Thanks for helping at translating the issue so that I can understand it :)

**Comment by bsongis-frsky** [comment]
Please give me an example (as simple as possible) of something which doesn't work correctly.

X20(S) + TD-ISRM in ACCESS 2.4 only + Which receiver + Which sensors

**Comment by hrenz** [comment]
Tx: X20S with TD V2.1.8, ETHOS V1.0.9.C4 all in LBT, no FCC
Rx: GR8 ACCESS
Sensors: FLVSS, GPS, Neuron60, Vario

with only FLVSS its ok, no sensor lost
if more then one sensor in chain then sensor lost
-------------------------------------------
with all other Tx, Rx, Sensors,  singel or in combination, never a sensor lost
TX: X9D+2019, X9E, TX16S,  ACCST, ACCESS,  XJT, IXJT, 4in1 MPM,  all in LBT
RX: X6R, S6R, G-X8, GR8
Sensors FLVSS, GPS, Neuron60, Vario
------------------------------

![IMG_2204](https://user-images.githubusercontent.com/6217896/122571187-c2400700-d04c-11eb-8538-f7cb97a88fbe.JPG)

**Comment by hrenz** [comment]
Test today test  X20S with latest ETHOS 1.0.9  all with LBT
Sensor lost now is only with GPS single or in chain
With no GPS in chain no sensor lost 

I allway test with delete all sensors, then search sensors

GPS has the latest fimrware 20201113

-------------------
Think you have a problem with GPS-Sensor at ETHOS, Tandem 
Because all other Combinations are ok with my Test Tx, Rx, Sensors,  in ACCST, ACCES, 4in1 MPM, XJT, IXJT
No sensor lost with GPS single or in Chain

**Comment by hrenz** [comment]
Next Test
Tx: X20S,  V1.0.9  ACCST
Rx: X8R, S6R, ACCST
Sensors: FLVSS, GPS, Neuron60, Vario

Sensor Lost starts after 30s ....60s then allways every 10....20s

Summery:  
Frsky has big problem with their Telemetry Software, with X20, or ETHOS, or TD, or RX-Firmware, or ACCST

-----------------
Never one ensor lost with ACCST at  X9D+2019, X9E, TX16S with one or all 4 sensors in chain

**Comment by NMO81** [comment]
> 
> 
> With my X20 I have noticed that on SR6 receivers only 1 MLVSS is enough to generate this ''Sensor Lost", you can see in the telemetry menu that the update dots are blinking very irregular.

Ok, I had some time to test this out and can confirm that in my case that updating the MLVSS to the latest firmware (dates already from 2017) solved the issue. I can now daisy-chain 3 sensors without sensor lost warnings. Also the status dots in the telemetry screen blink now more steady. Of course I have no other sensors available now to test more.
![IMG_20210618_214246](https://user-images.githubusercontent.com/85587485/122610522-1adcc780-d080-11eb-9411-181253d17fbb.jpg)

**Comment by bsongis-frsky** [comment]
Will be fixed by new RF firmware

**Comment by Adelaxie** [comment]
2.1.8 for Archer updated.

**Comment by RealTadango** [comment]
I had lots of Sensor lost messages today. X20S with Ethos 1.4.7 FLEX, TD MX with 1.0.7 connected to a FAS150 and a RB 10. About 5 sensor lost warnings during the flight. Setting telemetry to 100mW (and rebinding) increased the warnings to about 15. Only a short test of 3 flights of about 7 minutes in close range (error occurred about 200m - 400m away). Feels like this issue is still appearing. Same TX with ACCST D16 receivers works flwelessly.
