### ISSUE TITLE
Ethos Suite 1.6.0 RC2 and X10S Express (X12 ISRM)

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4813]
Hello, if you want to update the transmitter to 1.6.0 using the Suite, this does not work because FW 3.0.0 is required for the RF module. However, only v2.1.10 is available and therefore an update fails. So should I continue to update manually?
Thanks Wolfgang

**Comment by Nicholas-Luoyi** [comment]
I forgot to exclude X10S Express and X12 ISRM when checking RF 3.0.

**Comment by Wolepo** [comment]
So let's wait for 1.6.0 RC3

**Comment by Nicholas-Luoyi** [comment]
RC3 uploaded

**Comment by Wolepo** [comment]
Thank you, it works now.
