### ISSUE TITLE
Updated translation for Ethos 1.6.0 RC2, Norwegian

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#4818]
Updated translation for Ethos 1.6.0 RC2, Norwegian

[no.csv](https://github.com/user-attachments/files/17969228/no.csv)

**Comment by bsongis-frsky** [comment]
It seems to me a 1.5 file, no?

**Comment by bsongis-frsky** [comment]
The latest file is there:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/1.6/translations/display/no.csv

**Comment by mmasch** [comment]
The csv file was from the 1.6.0 RC2 installer, but thank you for your link to 1.6.
I now understand how to find 1.6 files  ;-)
Will look into the translations ASAP.

**Comment by bsongis** [comment]
I can give you WRITE access here, it will be easier!

**Comment by bsongis-frsky** [comment]
In fact you have WRITE authorization to this directory already :)

**Comment by mmasch** [comment]
So it ts possible/preferable to edit right in the GitHub translation page?
I thought you had to download the file, edit and upload...

**Comment by mmasch** [comment]
Translation complete for Ethos + Suite in the 1.6 thread.
Hope everything looks OK. :-)

Best regards, Morten.

**Comment by bsongis-frsky** [comment]
Everything perfect, thanks!
