### ISSUE TITLE
Model Wizard "Multi" setup defaults to TREA even though AETR is set as system default

### ISSUE THREAD

**Issue by frskyrc-ben** [FrSkyRC/ETHOS-Feedback-Community#4819]
When selecting "Multi" type model in the Model Wizard / Create Model screen, the channel order defaults to TREA even though AETR is set as the system default.

![image](https://github.com/user-attachments/assets/ec8d4587-9f5b-4072-9e26-0fa03d934d44)
![image](https://github.com/user-attachments/assets/cfbdc32a-54da-47e5-9cc0-6aefee2f7b54)
![image](https://github.com/user-attachments/assets/d3f06b4b-cfed-42a2-8da5-5f2c27fd6a2a)

Please update the Multi model type to default to the correct channel order as set by the System - Sticks default setting.

Thank you!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/d1aa0040-1ab1-4dd9-ab91-284ebf51d13c)

![image](https://github.com/user-attachments/assets/beeb1951-c401-4465-b712-43aa0fe33e63)

![image](https://github.com/user-attachments/assets/175a1200-39ea-4b16-8888-6826287adc62)

**Comment by bsongis-frsky** [comment]
It will be fixed in 1.6.0 RC3
