### ISSUE TITLE
Enhancement: Naming the flash drive

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#482]
Is there any way the flash drive can be given a name? I think this would make the update process much easier. Some RC pilots aren’t very computer literate, and may not understand the less than 8Mb instruction. 

This question has 2 parts really:

1. Can the firmware/bootloader/whatever automatically name the flash drive something like **E FLASH**, which is shown automatically in Windows explorer or Finder? I think this would be the best option as it would not need setup by the RC pilot. 
2. If not, would naming the Flash drive manually with Windows explorer (Finder, etc) cause any issues for ETHOS?

The same could also be asked for the MicroSD card. But as these are replaceable, I think the flash would be nice to have named by default.

**Comment by OldGazer** [comment]
Just give the SD card a volume label.  You really don't want to go messing with the other "drive".

**Comment by MrD-RC** [comment]
@OldGazer which is why I asked if it's possible for the flash drive to already be named. I think it would be a lot more user friendly from the get go. I have named my SD card, and that's fine. But as I mentioned, there are a lot of RC pilots who aren't computer savvy.

**Comment by ahvink** [comment]
I named both my flash and SD and haven’t noticed any issues yet…..

**Comment by MrD-RC** [comment]
Good to know @ahvink 

If it could be named from the factory, it would make updating a lot simpler.

**Comment by mawzthefinn** [comment]
@MrD-RC I agree, would be nice to have the radio name included on the flash volume name.

**Comment by MrD-RC** [comment]
I believe this one has been fixed. I’m sure on my X20 Pro. The drives had better names by default.
