### ISSUE TITLE
Ethos 1.6.0 RC2 V20 Simulator: LUA Script Stabilizerconfig

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4820]
The script (Stabilizerconfig) downloaded from the LUA library (Suite 1.6.0 RC2)
no longer appears in the System menu even though it is copied into the script folder.
It was good with Ethos 1.6.0 RC1

**Comment by Nicholas-Luoyi** [comment]
![screenshot-2024-11-15-37442](https://github.com/user-attachments/assets/263f7b70-6869-45cd-be25-7b69a8658eab)

It has been moved to the device config menu (The image is outdated since the script version should be 3.0.1)

**Comment by philippe-warnotte** [comment]
Oh okay, I found it. THANKS

**Comment by philippe-warnotte** [comment]
Le menu "Device config" a été traduit en français par "Capteurs".  "Config périph" aurait été plus judicieux.

**Comment by bsongis** [comment]
> Le menu "Device config" a été traduit en français par "Capteurs". "Config périph" aurait été plus judicieux.

Will be modified in 1.6.0 RC3

**Comment by EngelMT** [comment]
@philippe-warnotte

The reason is simple. This point used to be called "Sensor Config" and was only changed with the last 1.6.0 versions.

**Comment by philippe-warnotte** [comment]
@EngelIMT, I know that very well and I didn't say it was a mistake!
Since several different devices have been added to this menu, I simply made this suggestion.
This should not be taken as a criticism, but just as a request for improvement.

**Comment by bsongis** [comment]
The french translation has been modified. It should be right now.

**Comment by philippe-warnotte** [comment]
Yes, thank you Bertrand, I  saw the modification this morning with RC3.
