### ISSUE TITLE
request : Creating own Model templates

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#483]
It would be nice if we have a function to  make a template from an existing model  that can be used when creating a Model.
I know i can simply copy a Model and change name , id , picture etc.
the template should not contain any individual data like model id , binded rx , tx modul selection ect.

I imagine it this way:

- when you select creating a new model, now you can choose heli , glider , airplane , other and the new entry template.
- when select template you get the list of your created templates.
- then you select a template.
- then the system asked for name and picture.

**Comment by MrD-RC** [comment]
What about if when you clone a model, there is an option box that you can choose to copy the receiver settings or not?

**Comment by loetefix** [comment]
Thats also a good idea. But with templates it is smarter:)

**Comment by mawzthefinn** [comment]
Yes, more advanced templating would be excellent. 

I'd actually love to see the option to make a template of a batch of settings, not just full model templates, so you could potentially apply multiple sets of templates.

For example, I could apply a base 'Glow' template than configures core mixers for a glow-powered aircraft, including callouts for rates and throttle cut, then apply a 'Stabilizer' template that adds all my stab mixing and callouts on top of that.
