### ISSUE TITLE
menu français disparu sur RC3

### ISSUE THREAD

**Issue by Chamou-76** [FrSkyRC/ETHOS-Feedback-Community#4830]
Sur x20S les menus en français sont désactivés après la mise à jour en 1.6.0 RC3

**Comment by bsongis-frsky** [comment]
Il faut bien utiliser Ethos Suite 1.6.0
Testé encore hier avec la RC3, aucun problème !

**Comment by Chamou-76** [comment]
j'ai bien utilisé ethos suite 1.6.0 RC3 pourtant. Je vais retenter pour voir.

**Comment by Chamou-76** [comment]
> J'ai bien utilisé ethos suite 1.6.0 RC3 pourtant. Je vais retenter pour voir.

ok, fonctionne en RC4.
Merci
