### ISSUE TITLE
Newbie needs a little more help

### ISSUE THREAD

**Issue by dean5378** [FrSkyRC/ETHOS-Feedback-Community#4833]
What would be the latest for the ETHOS Suite for Mac?

**Comment by mawzthefinn** [comment]
Latest version of Suite posted here without RCx in the name:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases

**Comment by dean5378** [comment]
But those versions are not released as yet...correct?

**Comment by mawzthefinn** [comment]
> But those versions are not released as yet...correct?

If the release has the 'release' tag on it and does not include RCx in the name, it's a released version. I linked to the primary release page.

**Comment by dean5378** [comment]
ok. thanks!

**Comment by dean5378** [comment]
Looks to me like this: Ethos Suite 1.5.12 is the latest?
I hope that I am not being "thick."

**Comment by mawzthefinn** [comment]
That's correct at this time.

**Comment by dean5378** [comment]
Thanks again!
