### ISSUE TITLE
Ethos 1.6 Express LRS bug

### ISSUE THREAD

**Issue by stevemccormack** [FrSkyRC/ETHOS-Feedback-Community#4834]
trying to open expresslrs lua script and i get met with this message. happens with RC1, 2 and 3.
![FB_IMG_1733258820995](https://github.com/user-attachments/assets/aa3b7593-18f8-41c3-84c1-3e5549769c2f)

**Comment by bsongis-frsky** [comment]
You need the Lua scripts for Ethos 1.6

Le mar. 3 déc. 2024 à 21:48, stevemccormack ***@***.***> a
écrit :
