### ISSUE TITLE
No customised images

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4835]
Hello,
No user-defined images can be selected in the sim. This is probably also the case in the channels.
Thank you Wolfgang
![Benutzerdefinierte Bilder](https://github.com/user-attachments/assets/e2d7e92f-2ea7-4d6b-b011-e8cc4dfbe10f)
![Flash-Speicher](https://github.com/user-attachments/assets/39fde256-5368-4233-a320-37c79b437c62)

**Comment by bsongis** [comment]
They should be inside `bitmaps/user`!

**Comment by bsongis** [comment]
And not on flash, it will be in the disk you have chosen for bitmaps

**Comment by Wolepo** [comment]
Ok, renamed the folder in the sim to ‘user’ and it works.
 But where should the folder be in the transmitter, on Flash?
![Screen](https://github.com/user-attachments/assets/b235cc48-1902-430c-86dc-58d1b1cdb973)
