### ISSUE TITLE
irx4 Multiprotokoll Modul

### ISSUE THREAD

**Issue by Franz-Royer** [FrSkyRC/ETHOS-Feedback-Community#4838]
Is it possible to bind a Frsky X20 with Ethos and an IRX4 lite multiprotocol, Futaba Fasst, FasstTest or FHSS receiver? Maybe also a Jeti receiver?

**Comment by mawzthefinn** [comment]
FASST, FASSTest and Jeti are not supported by the Multi-protocol. 

SOme variations of Futaba FHSS are, you should refer to the Multiprotocol documentation for details:

https://www.multi-module.org
