### ISSUE TITLE
Audio Spanish translation V1

### ISSUE THREAD

**Issue by iulius-esp** [FrSkyRC/ETHOS-Feedback-Community#484]
I have created this sound pack from the English sound pack. I am using it by renaming the folder to "en" but it would be convenient to create the option "Español" in the audio menu.

[ES_TRANSLATION_V1.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6643685/ES_TRANSLATION_V1.zip)

**Comment by bsongis-frsky** [comment]
Is it possible first to have the spanish display translations?

**Comment by iulius-esp** [comment]
Yes, I have the translation almost finished, I am using the file of the French translation as a template.

**Comment by bsongis-frsky** [comment]
very good, I will release a simulator if you need

**Comment by iulius-esp** [comment]
Here is the file with the Spanish translation. A simulator would be interesting to check and correct the errors.

[es.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6648851/es.txt)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/121905786-c9a0a100-cd2a-11eb-9908-f1c4ef8d3032.png)

**Comment by bsongis-frsky** [comment]
AUDIO is automatically generated from those files, using Google Cloud Text To Speech:
[audio_en.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6648931/audio_en.txt)
[audio_fr (2).txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6648932/audio_fr.2.txt)

**Comment by iulius-esp** [comment]
perfect, I will use those files to generate the audios
