### ISSUE TITLE
Bootloader

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#4840]
not sure where I go to update bootloader, on 1.5.15, Frsky x18se. Directions would be great,
Thank you.

**Comment by mawzthefinn** [comment]
Connect to Suite, see if it says your Bootloader is up to date. Suite will update it for you when it's needed. 

Bootloader for the X18SE hasn't changed in a long time, 1.4.15 is still current.

**Comment by mawzthefinn** [comment]
Closing as answers are provided
