### ISSUE TITLE
Ethos Suite 1.6.0RC4

### ISSUE THREAD

**Issue by jhammann13** [FrSkyRC/ETHOS-Feedback-Community#4843]
it is not possible to install Ethos 1.6.0RC with this Suite on X10S ISRM
![Suitefail](https://github.com/user-attachments/assets/c7a2ce20-7cd0-440f-a3c6-d44a76a3fcba)
.

**Comment by mgsanna** [comment]
![Screenshot 2024-12-05 152418](https://github.com/user-attachments/assets/98d95199-ecb8-44db-8a35-18aeb7d43757)
You have to select the right server, on ethos suite preferences, for the latest release candidate you must select github.com instead of Frsky.....
simply but not so easy to discover

**Comment by Wolepo** [comment]
But beware, this setting is not saved. The next time the suite is started, GitHub must be set again.

**Comment by mgsanna** [comment]
@Wolepo right observation!!

**Comment by jhammann13** [comment]
It is written in the changelog:
_Server location selection will no longer be saved, and each time the app is opened, it will default to the FrSky server_
