### ISSUE TITLE
Expo using VAR as a source issue

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#4845]
I'm using a VAR as a source to set an Expo.  I'm also using a VAR to set the Weight.  If I change the order of the VAR list, then the source that I had chosen for Expo changes.  The VAR's that I had selected for the Weight remains the same. This issue happens with the canned mixes and when using a Freemix

**_Plane File:_**
[var test.txt](https://github.com/user-attachments/files/18027918/var.test.txt)

**_Radio Info:_**
![Radio Info](https://github.com/user-attachments/assets/d1d98a14-4f9d-41b6-af8c-f9d18a359322)

**_Set Up:_**
![Test Plane](https://github.com/user-attachments/assets/9a43f5f3-40eb-42d9-bd0d-0bf1106d951e)

**_Aileron Mix Detail:_**
![Ail Mix](https://github.com/user-attachments/assets/7ee8af75-63a6-4232-92af-f3773c7290f0)

**_VAR list before the order  change:_**
![Change List Order1](https://github.com/user-attachments/assets/ff79e06a-1d1e-4575-a0ae-e63fb96929a6)

**_VAR list after the order change:_**
![Change List Order2](https://github.com/user-attachments/assets/d10028e8-3bad-471b-972b-fa3f82eacdb8)

**_Aileron Mix Results:_**
![Ail Result](https://github.com/user-attachments/assets/03074f9d-330b-45a0-b88c-5931933b8498)

**_Elevator Mix Results:_**
![Elevator Result](https://github.com/user-attachments/assets/1c4680be-256f-4347-8ed4-bd239b381341)

If I change the order back to the original then everything lines up.

**Comment by strgaltdel** [comment]
curious,
could replicate the malfunction even on 1.5.18 sim

- create simple glider by using wizzard
- create several Vars
- let 2.nd Var the ail/expo value
- let 3rd Var the ail-weighting
- move 1st var to the end of var-List

>> ail Expo gets the weighting var 
(weighting is still correct with "same" var)

**Comment by df7320** [comment]
I just rolled my X20S back to 1.5.0 and got the same results.

**Comment by bsongis-frsky** [comment]
It seems to me that this bug is at least 3 years old!
It is fixed in 1.6.0 RC7
