### ISSUE TITLE
Ethos 1.6 RC5 Hott telemetry issue: no vario sensor

### ISSUE THREAD

**Issue by klaustms** [FrSkyRC/ETHOS-Feedback-Community#4846]
Basically, Hott telemetry works with the multimodule, but external sensors such as vario or the
sensors from SM-elekronik or the internal vario from the GR18 receiver are not yet recognized

**Comment by bsongis-frsky** [comment]
Which is the ID of this vario?

**Comment by bsongis-frsky** [comment]
Which sensors are you missing, except the Vario (which will be introduced in the next nightlies)?

**Comment by klaustms** [comment]
Here are the IDs for Unisense-e and Graupner Varios:
Unisense-E
Data Type		Unit		Graupner EAM UID 
			
Vario/Altitude	m		0XE07		
Vario/Vspeed	        m/s		0XE0B		
Current		        A		0XE08		
Voltage		        V		0XE09		
RPM		     U/min	0XE0C		
Comsumtion	      mAh		0XE0A		
Speed		      kmh		0XE0D		

Graupner orig. Vario	
Vario/Altitude	m		0X901		
Vario/Vspeed	      m/s		0X902

**Comment by klaustms** [comment]
sorry for closing - wrong click :-)

**Comment by bsongis-frsky** [comment]
All the sensors above will be there in the next 1.7 nighlies
