### ISSUE TITLE
1.6.0-RC5 V20 and 1.6.0-RC6 X20S Simulator Telemetry lost

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4848]
1.6.0-RC5 V20 and 1.6.0-RC6 X20S Simulator
Voice alert "telemetry lost" when opening a LOG file

**Comment by bsongis-frsky** [comment]
Strange indeed!

**Comment by philippe-warnotte** [comment]
I haven't installed 1.6 on my radio yet, I'm waiting for RC6. 
My comment concerns only the simulator. 
It's probably not important.

**Comment by bsongis-frsky** [comment]
Indeed there is something bad, only done on simulator, because threads priorities on the computer are not the same than the RTOS. I will find a solution in 1.7 for this.
