### ISSUE TITLE
Disable Ailerons when wings are swept

### ISSUE THREAD

**Issue by dean5378** [FrSkyRC/ETHOS-Feedback-Community#4849]
I need to Disable Ailerons when wings are swept on my F-14.  The Ailerons are also mixed into the "Tailerons."  How can I disable the just the Ail's when wings are swept.  Newbie Alert: Just been working on Ethos for the past couple of days.

**Comment by Dsrenger** [comment]
That's a question for forums like Rcgroups.

This is a developer platform to test software and report bugs ect 

This thread is good for such questions: 
https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-(S-HD)-X20R-(RS)-X20-Pro-(AW)-Tandem-24-Channels-with-ETHOS/page2232

**Comment by mawzthefinn** [comment]
Set the active condition of your aileron mixer to only be true when the wings are forward.
