### ISSUE TITLE
Personalised splash screen

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#485]
It would be great if we could personalise the splash screen. 

I've taken a look on the flash and SD card, but nothing stands out as a file to replace. I've also tried putting a splash.png file in the bitmaps/user folder of both the flash and SD card.

Is there a way to do this?

**Comment by bsongis-frsky** [comment]
The splash is displayed before the SD is ready

**Comment by MrD-RC** [comment]
Awesome. How do you change it, or is it ready for a future update?

**Comment by bsongis-frsky** [comment]
It is still not mounted at this stage

**Comment by MrD-RC** [comment]
Shame. I always customised them with OpenTX. 

Thanks for the response.

**Comment by Ze-baloo** [comment]
> The splash is displayed before the SD is ready

Hello Bertrand,

Thanks for the great work done on Open Tx and now on Ethos.
I'm currently upgrading from my X9d+ Se 2019 to a brand new X18.

I know that it's not vital to have this feature on Ethos, but I still think that having the possibilty of customizing the start screen should be kept in mind ;-)

Happy new year ;-)

Laurent
