### ISSUE TITLE
ETHOS Suite V1.6.0. RC4  no sleection of testverson

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#4850]
Suite V1.6.0. RC4
No selection of correkt testversion V1.6.0 
shows latests Testversion  V1.5.5

Back to V1.6.0.RC 3 all ok
shows latest Testversion V1.6.0 RC5

**Comment by yak55** [comment]
Hi Helmut, you have to select the GitHub server in the settings every time you open it.

Greetings Eugen

**Comment by mawzthefinn** [comment]
This is in the changelog for Suite 1.6.0 RC4

'Server location selection will no longer be saved, and each time the app is opened, it will default to the FrSky server'

**Comment by hrenz** [comment]
very bad solution

**Comment by mawzthefinn** [comment]
I agree. Re-opened.

**Comment by Nicholas-Luoyi** [comment]
The selection will be saved in the next build
