### ISSUE TITLE
Add DEVICE_CATEGORY_DIY on the new 1.6.0

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#4851]
Hello Bertrand,

local function init()
  if system.registerDeviceConfig then
   system.registerDeviceConfig({category = DEVICE_CATEGORY_DIY, name = name, bitmap = icon, version = LUA_VERSION, pages = { {name = name, create = create, wakeup = wakeup} }})
  else
    ssystem.registerSystemTool({name=name, icon=icon, create=create, wakeup=wakeup})
  end
end

Thks

**Comment by bsongis-frsky** [comment]
It will be there in 1.6.0 RC7

**Comment by bsongis-frsky** [comment]
As the other categories, it will be displayed only if one DIY sensor is there!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/cbcccd45-ee4e-4f7a-a842-5dac796fb465)
