### ISSUE TITLE
1.6.0:  Rotary Encoder not reporting events without a "form" with active elements.

### ISSUE THREAD

**Issue by frankiearzu** [FrSkyRC/ETHOS-Feedback-Community#4852]
i think i run into a lua problem with the rotary encoder with some radios who are touch capable.  if the page has no "selectable" form elements (like buttons), the rotary don't report any events to the LUA script, but if there is something that can be "focus" on the form, then the rotary report events when you are trying to move out of the form elements.     Run this tools script.. With X10 it reports rotry events with and without the button.. on the X20S/X18S,  once you remove the button, it stops reporting rotary events.   

Tested on the simulators. 

1. Install in /scripts as a tool.
2. After running it, use the rotary encoder, should display ROTARY_LEFT or ROTARY_RIGHT on the screen.
3. Press on the button to remove the button
4. Now no rotary events are generated for LEFT/RIGHT.. only ENTER works.

Works fine on X10 (Sim and real radio), but does not work on X20S/X18RS.  All were tested with simulations.
Ethos version:  1.6.0 RC5 and RC6. haven't tested earlier versions.

The "Enter" key also  behaves differently on the X10 than the X20. The X20 only generates KEY_ENTER_FIRST and NOT generate KEY_ENTER_BREAK when released, Also does not generate KEY_ENTER_LONG.  The X10 generates all correctly (KEY_ENTER_FIRST, KEY_ENTER_LONG, KEY_ENTER_BREAK). 

Right now as a workaround, I'm creating a small 1x1px button on the lower part of the screen.. in that way, rotary LEFT/RIGHT works, but the KEY_ENTER_BREAK is still not generated.. I prefer to execute action on Release/Break.

LUA TOOL script:
[rotary-bug.zip](https://github.com/user-attachments/files/18049401/rotary-bug.zip)

When the button is displayed, rotary events are sent to lua handler.
![image](https://github.com/user-attachments/assets/c9112b20-09e4-4e7c-9efb-82755c4b4ed0)

After removing the button, the rotary encodes is not reporting events to LUA. Enter generates KEY_ENTER_FIRST (97), but no rotary left/right or release (KEY_ENTER_BREAK) 
![image](https://github.com/user-attachments/assets/211286e3-f401-4d11-bdc8-bbad47b4680d)

**Comment by bsongis-frsky** [comment]
Fixed in the next 1.7.0 nightlies
