### ISSUE TITLE
ETHOS Suite V1.6.0. RC4 does not show Multimodule version

### ISSUE THREAD

**Issue by electric-2000** [FrSkyRC/ETHOS-Feedback-Community#4854]
Under SYS/Info/ External Module it does not show Multimodule version. It has in earlier builds.

**Comment by electric-2000** [comment]
Also I noticed that when you turn the radio off when using the External Multimodule module there is no longer a warning that the receiver is still on.

**Comment by bsongis-frsky** [comment]
Which is your receiver? Which settings have you chosen in Model / RF for your Multimodule?

**Comment by bsongis-frsky** [comment]
The version should be displayed when available. And "Multimodule" in other cases.
Of course if the module type for the current model is Multimodule

**Comment by electric-2000** [comment]
OK, I did some more digging and it appears that it is working as you mentioned. If the external Module is selected and set to Multimode, I get the firmware displaying 1.3.4 and when the external module is turned off it just displays Multimode.
As for the Radio announcing that the receiver is still on when the radio is turned off was an issue with me relocating my sound files.
Sorry for the confusion…
-Mike
