### ISSUE TITLE
V20 Firmware Update Error using Suite 1.5.12

### ISSUE THREAD

**Issue by st157322** [FrSkyRC/ETHOS-Feedback-Community#4856]
Hi, 

I have had the Problem, trying to Update the Kavan V20 for an Customer. I tried to go from 1.5.18EU to 1.5.19EU using the Suite 1.5.12. Afterwards the Bootloader don't find any Firmware File and the Radio did not boot (exept into Bootloader). Suite then Showed Fimware 0.0.0FCC i could flash other firmware using the Suite but no Bootup.

Putting the Firmware 1.5.19EU directly onto the Flash and Flashing it the old way by turning on into Bootloader it worked.

Maybe you can reproduce it. My V20 now goes back to the Customer.

Cheers, Lukas

**Comment by Nicholas-Luoyi** [comment]
@bsongis-frsky I think this cannot be auto-flashed by Suite because the radio reports firmware version 0.0.0 FCC. This means Suite cannot retrieve the correct information from the radio and, therefore, cannot flash the correct firmware onto it. Although it may show a successful flash, it likely didn't flash the V20 firmware, which explains why it fails to boot properly. However, manually flashing the firmware might resolve the issue.

**Comment by bsongis-frsky** [comment]
I have just flashed my V20 here.

There is different information displayed in "Radio information" and "Ethos"

![image](https://github.com/user-attachments/assets/9558f4ae-2671-4582-ade1-12ccc2b12588)

![image](https://github.com/user-attachments/assets/223e56e0-5883-4c42-8a63-42cd66f73f91)

**Comment by bsongis-frsky** [comment]
I have also tried to flash 1.6.0 and now in Radio Information, the radio is seen as "Up to date", which is not right, 1.6.0 is not marked as stable

![image](https://github.com/user-attachments/assets/e44dbfdd-6384-4691-b561-4db3837e430c)

**Comment by bsongis-frsky** [comment]
But otherwiser I have no flashing issue, this radio seems to work very well. I have also tried to flash the internal module to the RF 3.0 and it worked too.

**Comment by bsongis-frsky** [comment]
I have used Ethos 1.6.0 for all the tests above. Perhaps this is the difference with the original issue!

**Comment by bsongis-frsky** [comment]
@st157322 do you have the opportunity to check with Ethos Suite 1.6.0 ?

**Comment by Nicholas-Luoyi** [comment]
> I have just flashed my V20 here.
> 
> There is different information displayed in "Radio information" and "Ethos"
> 
> ![image](https://private-user-images.githubusercontent.com/50834778/394367844-9558f4ae-2671-4582-ade1-12ccc2b12588.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODAyNzksIm5iZiI6MTczMzg3OTk3OSwicGF0aCI6Ii81MDgzNDc3OC8zOTQzNjc4NDQtOTU1OGY0YWUtMjY3MS00NTgyLWFkZTEtMTJjY2MyYjEyNTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAxMTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZjUwYTQzOTZhNTI1M2NjZGViYTg3MGYxMWJlNmY3MzA2ZWQ0ODVlOTA0NjIyMDMyOGU0OTFjYmRhN2MzOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PyfU9UsFnH4kQRpF0GHvvDtgL9KPdLJ7Ti5r_qAoiWo)
> 
> ![image](https://private-user-images.githubusercontent.com/50834778/394367935-223e56e0-5883-4c42-8a63-42cd66f73f91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODAyNzksIm5iZiI6MTczMzg3OTk3OSwicGF0aCI6Ii81MDgzNDc3OC8zOTQzNjc5MzUtMjIzZTU2ZTAtNTg4My00YzQyLThhNjMtNDJjZDY2ZjczZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAxMTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYzAxODBlMGQ0MTE4NWM2MzI3ZDg2NzdmNjIwNTFkNTkzY2E3MjgyMTU4OGU5YjEzNDA4NjIwNDA5NGFjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t7biGlrJNikOo7cjovHZYcw2NKgDwb0dDGHY8QuFUig)

This is indeed a problem. It will be fixed
