### ISSUE TITLE
Ethos suite 1.6.0-RC4: Image Manager, Choosing Output path not work

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4859]
Ethos suite 1.6.0-RC4: Image Manager, Choosing Output path not work

**Comment by mawzthefinn** [comment]
Just tested, it's working correctly on MacOS 15.1.1 and Suite 1.6.0 RC4

**Comment by mgsanna** [comment]
Just Tested on Windows 11 -24H2- & Ethos suite 1.6.0 RC4 working as expected and correctly

**Comment by philippe-warnotte** [comment]
Ok, it's not really important. 
Note: My 1.6RC6 update worked perfectly. 
Stabilization is much easier now. Nice work guys!
You can close.

**Comment by mawzthefinn** [comment]
What OS version are you on? I'd rather identify the issue you are having than close an issue because we are unable to duplicate

**Comment by philippe-warnotte** [comment]
I have 1 pc Windows 10 Home and 1 PC on Windows 10 Pro. I have the problem on both. 
I tried uninstalling but it still keeps the old path which I don't know how to modify.

**Comment by philippe-warnotte** [comment]
Sorry in french...
![image](https://github.com/user-attachments/assets/8ff94eb0-9746-42f2-afb6-20a246d8b151)

**Comment by philippe-warnotte** [comment]
I think I shouldn't have uninstalled Ethos suite before installing the latest version. 
I restored my PC before the day when I uninstalled Ethos suite. 
Now I install the new Ethos suite versions without uninstalling and it works fine.;-)

**Comment by mawzthefinn** [comment]
@philippe-warnotte - Is the issue resolved for you?

**Comment by philippe-warnotte** [comment]
Yes, thank you
