### ISSUE TITLE
Tandem X20S Telemetrie GPS Sensor Problem Speed km/h wrong #363

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#486]
Hallo Mr bsongis,

even with ethos 1.09 / 4 the GPS speed is not correct. meters per second and kilometers per hour are still interchanged in my opinion

**Comment by MichaelETHOS** [comment]
yes I can confirm that.  just as you can not set the height to zero when the model is bound.  you can switch for a sec and the altitude comes above the waterline

**Comment by islandflight** [comment]
The reset altitude issue with the GPS has been fixed in the 1.010 milestone

**Comment by bsongis-frsky** [comment]
@bluelex73 did you remove / discover again your sensor?
The default unit of this sensor is knots. It can be converted to km/h if you change the sensor unit

**Comment by bluelex73** [comment]
No, I have not deleted the sensor and searched again. Only the new firmware1.09 / 4 . i delete the sensor and try again.

**Comment by bsongis-frsky** [comment]
Feel free to reopen once 1.0.9 final will be released!
