### ISSUE TITLE
Ethos suite rc5 - documentation issue

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#4866]
Hello @Nicholas-Luoyi, I’ve uploaded last week the last 1.5.18 ethos italian manual, but in the suite  documentation section does not List…. May I made some mistake? Can you check it? Thanks in advance….
Marco G Sanna

**Comment by Nicholas-Luoyi** [comment]
Should be OK now. You can see it by restarting Suite. There are two spaces between [IT] and Ethos.

**Comment by mgsanna** [comment]
> Should be OK now. You can see it by restarting Suite. There are two spaces between [IT] and Ethos.

As supposed It was my fault... sorry and thanks
