### ISSUE TITLE
X20S manually updated to Ethos 1.6.0 RC7 , but only english

### ISSUE THREAD

**Issue by samsab1** [FrSkyRC/ETHOS-Feedback-Community#4868]
hello
where is my french language? 
on Flash i18n directory, i  see my new fr.i18n file, but the x20s offers only English.
why? how to correct that?
best regards from...........france

**Comment by mszulen** [comment]
Why don't you just use the Ethos Suite? Select French and flash.

**Comment by samsab1** [comment]
because the **last ethos suite** does not offer prerelease version, even you activate the option; the option is not effective

**Comment by mawzthefinn** [comment]
> because the **last ethos suite** does not offer prerelease version, even you activate the option; the option is not effective

Set your server to Github Suite settings and the pre-release will be available. I do recommend using the latest Suite 1.6.0 RC release for use with pre-release ETHOS.

Language packs are installed from Suite.

**Comment by samsab1** [comment]
thanks so much
i did not see this option before you tell me. thanks again
