### ISSUE TITLE
have 1.5.15 will not update firmware

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#4872]
I'm on 1.5.15 and i cant get it to update to the current firmware.  X18 radio

**Comment by mawzthefinn** [comment]
What version of ETHOS Suite?

**Comment by lotus1235** [comment]
My radio is on 1.5.15 version

**Comment by mawzthefinn** [comment]
But what version of ETHOS Suite are you using to update the firmware on the radio? I'm assuming your issue is that you can't update the radio based to latest ETHOS based on your first post.

**Comment by lotus1235** [comment]
Sorry, 1.5.2

**Comment by mawzthefinn** [comment]
Please update to Suite 1.5.12 from here:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/suite1.5.12

Suite 1.5.2 is quite old and has issues with newer releases.

**Comment by lotus1235** [comment]
Got it, its working. I didn't know about the update.
Thank you.
