### ISSUE TITLE
Which LUA script to configure SR10 Pro in Ethos

### ISSUE THREAD

**Issue by dean5378** [FrSkyRC/ETHOS-Feedback-Community#4877]
I tried to configure the SR10 Pro with LUA 3.0 on my TD20R but it would not open it.

Do I use the LUA 2022-03-23	v2.03 in the TD20R to Open the "STAB CONFIG?"

**Comment by mawzthefinn** [comment]
SR10 Pro is setup with Device Config->SxR

the newer SR10+ uses the Lua.
