### ISSUE TITLE
X 20  not working properly on mac

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#4878]
X20, ethos suite and mac book M2 all up to date at 15/12/2024

I encounter the following problems:
- impossible to read the SD card, I see that the problem is known... but still does not work whereas it worked before sequoia it seems to me.
- impossible to make updates from ethos suite, the process starts but never finishes.
- impossible to use the radio in joystick mode. Once the option is chosen it does not appear anywhere.
-impossible to use a frsky xsr sim dongle to connect the radio, the dongle is paired with the radio but the same no recognition on the mac, I saw that it was requested to install HID drivers on the frsky site but no link to know where and which drivers installed...

Thank you in advance if anyone can help me... This makes me regret my time on Mac a little...

**Comment by mawzthefinn** [comment]
Known MacOS 15 issues, 15.2 has solved it for some users. See #4526 for more info

**Comment by skyfly74** [comment]
Ok that i see, and for others problems with ethos suite, sd card, joystick ... there is no compatibilty avaible for mac os???

**Comment by mawzthefinn** [comment]
Suite & SD card are the same issue with Mac OS. 15.2 seems to be resolving it for most users. 

No idea why your joystick wouldn't be working unless you have a bad or charge-only cable as well, it's a standard USB HID joystick.
