### ISSUE TITLE
Sensor lost G-RX8  with M+ as redun.

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#488]
Hello,
Both RX updated to lastest access 2.1.7

Stand alone G-RX8 : alti and vario works fine 
Than connect M+ on SBUS in  as redunduncy RX ------> still works fine

Switch off both RX but still connected. Start again :: No more ALTI / VArio sensors are working
need to disconnect M+ and connect again to solve the Pb

**Comment by bsongis-frsky** [comment]
Ethos or RF? It needs more investigation

**Comment by aviat40** [comment]
Hello, Bertrand,
What do you want as investigation ? I can test with my X12S with ISRM on OTX to define if it is a RX firmware pb or
ETHOS

**Comment by aviat40** [comment]
HI,
Tested with X12 . The Pb is with the G-RX8 firmware. it does the same.
How to report with this to Frsky ?

**Comment by Hobby4life** [comment]
You just did

**Comment by aviat40** [comment]
Hi,

The solution is to disable the telemetry in the M+. Bug or not ?

**Comment by WismyYao** [comment]
The working mechanism of the current receiver is like this.
You can power on G-RX8 first, then power on M+, the telemetry will work

Of course, we don’t recommend using M+ as redundancy because its range.
