### ISSUE TITLE
"hello" Sound is extremely quiet

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#4880]
One customer complained that the "hello" sound is extremely quiet when the X20ProAW is switched on. All other announcements are normally loud or at the set volume.

We have tried many things today. The problem occurs when "Select model at power on" is activated under <General>. I have tried a different wave file and I have tried everything on a new radio. We have also tested with ETHOS 1.5.09 and 1.5.19.

I have also deleted all models from the customer and deleted the radio.bin as well. It occurs with English and German audio files.

Then I tried it with an X20 and an X20S. The error does not occur here.

So it clearly seems to me to be a bug in the firmware of the X20ProAW. Perhaps also in other radio types, but I have not tested this further.

**Comment by bsongis-frsky** [comment]
It will be fixed in the next RC
