### ISSUE TITLE
New version of Ethos does not accept prior sound pack

### ISSUE THREAD

**Issue by rits68** [FrSkyRC/ETHOS-Feedback-Community#4881]
I have recently upgraded my Ethos firmware (ver. 1.5.19) and Ethos suite There were sound files that I had used previously (from Inav Fixed Wing Group)
and which I needed to re-copy into the audio folder of my SD card on my Tandem X20s transmitter.   Although I can see these sound files within file manager, I am unable to assign these sounds to
My switches.  Seems when I assign the sound files thru the special functions menu, the “voice” is greyed out and shows “voice 1 default”.    I believe that it’s pointing to a default file in my sound folder but I can’t seem to change the path.  Does anyone have any idea how to fix this problem?   Thanks

**Comment by mawzthefinn** [comment]
You ned to put the files in the correct folder and then map your voice in System->General. Audio locations and configuration changed significantly with ETHOS 1.5

The correct locations are in the manual here, starting on Page 41:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/raw/1.5/doc/%5BEN%5D%20Ethos%20User%20Manual%201.5.18.pdf

**Comment by bsongis-frsky** [comment]
Exactly

**Comment by rits68** [comment]
So what is the solution?Sent from my iPhoneOn Dec 18, 2024, at 2:30 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Exactly

**Comment by rits68** [comment]
I drilled down into the thread and found the response to my question.    Please disregard my previous message asking for a solution. ThnxSent from my iPhoneOn Dec 18, 2024, at 5:24 PM, Richard Lewczuk ***@***.***> wrote:﻿So what is the solution?Sent from my iPhoneOn Dec 18, 2024, at 2:30 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Exactly

**Comment by rits68** [comment]
Hi.  I followed the instruction and placed the was files into the en/us folder.   However once I restarted the X20s, I received an error message that there is “no SD card”.  I cannot mount the sd card thru Macs disk utility either.  Any thoughts on how to fix?   ThanksSent from my iPhoneOn Dec 17, 2024, at 8:03 PM, mawzthefinn ***@***.***> wrote:﻿
You ned to put the files in the correct folder and then map your voice in System->General. Audio locations and configuration changed significantly with ETHOS 1.5
The correct locations are in the manual here, starting on Page 41:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/raw/1.5/doc/%5BEN%5D%20Ethos%20User%20Manual%201.5.18.pdf
