### ISSUE TITLE
Plus SR10+ receiver--something is wrong!

### ISSUE THREAD

**Issue by dean5378** [FrSkyRC/ETHOS-Feedback-Community#4886]
Set up flying wing config for F-14 WITH TAILERONS.
AILERON spoilers like the full scale version. All is well up to this point.

In the STAB Config LUA: Channels 5&6 set toAUX...NO Bleed-through of aileron stabilization on these channels (1-6)!

If I plugin flaps or anything else to channels: 7,8,9 for example I get AILERON stabilization correction...so if I plugin and mix channel 7 for flaps (in the mixer) I get aileron correction in the FLAPS!!!

WHAT THE HECK?

Bizarre.

**Comment by dean5378** [comment]
I created a video but it is too large to post in here..

**Comment by SmartTommy** [comment]
> Set up flying wing config for F-14 WITH TAILERONS. AILERON spoilers like the full scale version. All is well up to this point.
> 
> In the STAB Config LUA: Channels 5&6 set toAUX...NO Bleed-through of aileron stabilization on these channels (1-6)!
> 
> If I plugin flaps or anything else to channels: 7,8,9 for example I get AILERON stabilization correction...so if I plugin and mix channel 7 for flaps (in the mixer) I get aileron correction in the FLAPS!!!
> 
> WHAT THE HECK?
> 
> Bizarre.
which radio you uesed? and what's the Tx & Rx firmware version?

please check your IMU---> BASIC ---Group1 & Group2. maybe you enabled the group2

**Comment by dean5378** [comment]
@SmartTommy 
Ethos- X20R
1.5.1.9,FCC
Internal module 
TD-ISRM Pro
HW: 1.0.4 FW: 3.0.0

Could you please explain: ****please check your IMU---> BASIC ---Group1 & Group2. maybe you enabled the group2***
I am not sure what you mean..Please tell me how to check IMU not sure what IMU is?

**Comment by dean5378** [comment]
Receiver info:
AP_SR10+_R10+_1.0.11.frsk

**Comment by dean5378** [comment]
"Quick mode" is Enabled in the STAB LUA.

**Comment by mawzthefinn** [comment]
You need to configure or disable Stabilizer group 2, which stabilizes Ch7-11

It's the second page of the setup Lua.

**Comment by dean5378** [comment]
@mawzthefinn  Yes, that was it Mawz..thanks!  I never enabled page 2 items, but I guess it defaults to ENABLE?

**Comment by mawzthefinn** [comment]
Yeah, defaults to Enable except in ACCST mode. 

Closing off since you have it sorted
