### ISSUE TITLE
LUA scripts 1.5.18

### ISSUE THREAD

**Issue by artmeans-sd** [FrSkyRC/ETHOS-Feedback-Community#4887]
X18se radio. All working well on 1.5.12

Updated to 1.5.18 and the previously working LUA widget was no longer available. I can still see the script in the same folder / directory, but cant select it as a widget any longer. 

I see a new section in the manual about selecting LUA on a per model basis – which is a new tab on the model page, circled below

BUT, I don’t have the LUA screen on my TX, just a blank section where the new LUA tab should be. …

Any pointers? Thanks

![image](https://github.com/user-attachments/assets/7c26e8df-98c9-4db9-9726-a7e64632645e)

**Comment by noamkrief** [comment]
you posted in the wrong area:
You need to post this here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues

**Comment by bsongis-frsky** [comment]
As written in the manual above, this Lua icon is displayed if you have either:
- Lua sources
- Lua tasks

But not Lua widgets
