### ISSUE TITLE
Add Differential to elevator mix

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#489]
Many planes want less down than up elevator, the immediate reason that I have is for racing.  Currently this must be done with a custom curve, which is even more complicated if I want to keep my expo.  I would very much like to just have differential on the elevator mix.

**Comment by bsongis-frsky** [comment]
It's not exactly a differential, rather a different Weight Up and Down

**Comment by jfint** [comment]
That would do it indeed.   I also have 3 weights for rates.   So i thoight a single differential number might be better.
