### ISSUE TITLE
Ethos Suite Download Center  Flight-Safe System     - unable to download or flash  RB-10 redundancy Bus switch board module firmware

### ISSUE THREAD

**Issue by BompaBert** [FrSkyRC/ETHOS-Feedback-Community#4890]
Frsky RB-10 redundancy Bus firmware has the (older) .frk extension.
Ethos Suite Down Load Center requires .frsk files so it does not find the RB-10 firmware file when trying a file download or flash.

**Comment by Nicholas-Luoyi** [comment]
Yes. The flash function has a .frsk file header check. But for now you could just DOWNLOAD the zip file. And manually unzip and put into the radio

**Comment by bsongis-frsky** [comment]
Agreed, it would be better to only deliver .frsk files, which allows Ethos / Ethos Suite to check if the firmware is matching the device!

**Comment by mawzthefinn** [comment]
I think there's a need to post updated Frsk files for the older products. This is the 3rd or 4th issue opened and I see the ask elsewhere. Lots of people still using the older s.port sensors, receivers and accessories with their new radios.

**Comment by Nicholas-Luoyi** [comment]
Merged to #4920
