### ISSUE TITLE
ETHOS Suite Download Center - Download firmwares directly to the radio

### ISSUE THREAD

**Issue by frskyrc-ben** [FrSkyRC/ETHOS-Feedback-Community#4891]
Currently, when a user goes to the Download Center of ETHOS Suite, they must select the receiver types and click download which downloads the .zip file locally to their PC.

Then they must extract the .zip file and copy the contents to their radio.

This step is very cumbersome for many users who struggle with extracting the .zip files and copying to their radios.

Quite often, we see the users incorrectly putting the firmware updates onto the "FLASH" drive of their radio, which causes lots of frustration when they then cannot find the update files to update their hardware. Additionally, when the FLASH drive fills up and runs out of space, it results in the radio not booting up anymore causing a soft-brick and further customer support.

It would be nice to have an additional button or option to download (and extract) the firmware .zip file directly to the radio (similar to the Image manager selection option).

My suggestion would be to have an "updates" folder on the radio, and the folder structure for updates should follow the same as in the downloads center.

Ie. radio:\updates\receivers\td series\ < all TD receiver firmwares here >
Ie. radio:\updates\receivers\tw series\ < all TW receiver firmwares here >

![image](https://github.com/user-attachments/assets/21ccc3a6-6132-4b63-8b17-c3cedcb0c578)

**Comment by fdapport** [comment]
it is a great idea, vary useful

**Comment by Nerenye** [comment]
thats an awesome idee. but call the folder "firmware" sometimes we need to downgrade or just reflash. "Update" could be missleading

I realy hope this makes it in 16.1

**Comment by bsongis-frsky** [comment]
Why don't you flash directly from Ethos Suite with the radio connected. It works with all modules / receivers / sensors and it is far more practical!

**Comment by Nerenye** [comment]
Tell me how you Update a reciever in a plane out of Suite? As far as i know you cant

I have a folder for Firmware so i can flash everywhere from my radio via OTA or sport. For example new reciever or ones from a friend etc.

You cant do that from Suite nor do you have a PC With you all the time.

Especialy older Folks often have problems keeping track of fw and having all for every reciever on Hand. A Download diectly on your radio would BE so much more convenient.

**Comment by frskyrc-ben** [comment]
> thats an awesome idee. but call the folder "firmware" sometimes we need to downgrade or just reflash. "Update" could be missleading
> 
> I realy hope this makes it in 16.1

The reason I suggest the folder name "updates" is because we used to put the folder name "firmware" and several users gave feedback that "I didn't realize this was the folder with updates, I thought it was the firmware of the radio". So to avoid this misconception the folder name "updates" is clear and straightforward for the folder contents.



> Why don't you flash directly from Ethos Suite with the radio connected. It works with all modules / receivers / sensors and it is far more practical!

Because many times the receiver is buried into the model and difficult to reach with cable. So it is necessary to do OTA update with the firmware file on the radio.

An alternative solution or additional solution would be an option for the "FLASH" button in Download Center to offer two options : Wired Flash or Flash by Int. OTA

This way you do not need to have the radio wired to the receiver, you could "Flash by Int. OTA" via ETHOS Suite, it would copy the firmware to the radio and then trigger the OTA update process accordingly..

**Comment by Nerenye** [comment]
> An alternative solution or additional solution would be an option for the "FLASH" button in Download Center to offer two options : Wired Flash or Flash by Int. OTA

Thats not realy a good solution. You don´t have your pc at the field and can´t plugin everything as you seid before.
a direct to radio option would be the way to go i guess

**Comment by frskyrc-ben** [comment]
> > An alternative solution or additional solution would be an option for the "FLASH" button in Download Center to offer two options : Wired Flash or Flash by Int. OTA
> 
> Thats not realy a good solution. You don´t have your pc at the field and can´t plugin everything as you seid before. a direct to radio option would be the way to go i guess

I really think it would be a good ADDITIONAL option to have and we need to have both options:

1) Option to download the firmware direct to the radio, for users who wish to perform the (OTA) update at the field / without computer.

2) Option to Flash OTA directly from ETHOS Suite so it will download the firmware direct to radio then trigger the OTA update process. This would save users from having to "go to system, select file manager, find the firmware file, click it, select flash by int. OTA" -- Everytime I explain the OTA update process people are confused about 'Flash by Ext. OTA' and having to guide them through these steps can be challenging for some people..

**Comment by Nerenye** [comment]
> > > An alternative solution or additional solution would be an option for the "FLASH" button in Download Center to offer two options : Wired Flash or Flash by Int. OTA
> > 
> > 
> > Thats not realy a good solution. You don´t have your pc at the field and can´t plugin everything as you seid before. a direct to radio option would be the way to go i guess
> 
> I really think it would be a good ADDITIONAL option to have and we need to have both options:
> 
> 1. Option to download the firmware direct to the radio, for users who wish to perform the (OTA) update at the field / without computer.
> 2. Option to Flash OTA directly from ETHOS Suite so it will download the firmware direct to radio then trigger the OTA update process. This would save users from having to "go to system, select file manager, find the firmware file, click it, select flash by int. OTA" -- Everytime I explain the OTA update process people are confused about 'Flash by Ext. OTA' and having to guide them through these steps can be challenging for some people..

Yes, i agree.

**Comment by Nicholas-Luoyi** [comment]
Merged to #4920
