### ISSUE TITLE
Receivers description in the downloader center

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#4893]
SO PC: Windows 10
Version: Ethos Suite 1.5.12

In the receiver download center is not clear (ad list it could be confusing) the description of the receivers:

Folder: ACCESS 2.4G SERIES
AP SERIES could be change to " ARCHER PLUS Series"
The change could be also in the "ACCST 2.4G Series" folder.

Thanks,
Franco

![image](https://github.com/user-attachments/assets/f7e6591a-ca95-4eda-ad16-5bdd3d89541e)

**Comment by Nicholas-Luoyi** [comment]
Merged to #4920
