### ISSUE TITLE
Why is the RC1 at the top of the suite and the released version below?

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#4894]
![image](https://github.com/user-attachments/assets/2aab480e-3481-4a96-a83f-d4c5a2d2451c)

**Comment by mawzthefinn** [comment]
Probably sorting alphabetically when the version numbers are the same.

Should be by release date.

**Comment by Nicholas-Luoyi** [comment]
Merged to #4920
