### ISSUE TITLE
Missing Differential in Mixes

### ISSUE THREAD

**Issue by MPFlyer** [FrSkyRC/ETHOS-Feedback-Community#490]
Good morning all,

I noticed yesterday that the differential function in the mixers - which was there before - has somehow been lost.
Just now I started the Ethos X20 Sim (also 1.0.9 RC4) again and there it is missing now even if I add an e.g. aileron mixer 
to an existing or newly created model to an existing or newly created model. Strangely enough I find the function Differential in a mixer - at least in the Sim - in an already existing model that I have created at some time. When this function has now fallen out I can not say and whether this is a bug or intentional I do not like to judge.

As of now - 1.0.9 RC4:
![missing](https://user-images.githubusercontent.com/85866142/121854336-524f1b00-ccf2-11eb-91bb-3e34caa3da70.png)

And this is how it used to look in an earlier version:
![working](https://user-images.githubusercontent.com/85866142/121854490-862a4080-ccf2-11eb-9927-9a800f04c7c8.png)

Regards,
Matthias

**Comment by MPFlyer** [comment]
...I have just tried again a bit with the sim:

If I create a model under 1.0.9 RC4 completely new, then Differential is again there,
even if I then add another mixer... the "problem" only occurs with a model already 
created in a previous version...

Regards,
Matthias

**Comment by bsongis-frsky** [comment]
Perhaps the original mix is not an "Ailerons Mix"?

**Comment by bsongis-frsky** [comment]
Please send your model file so that I can check if it's an Ailerons Mix or something else

**Comment by MPFlyer** [comment]
Hi Bertrand,

After switching to another model and then back again, the differential function is now back. Strange but now it works again.
Tested in SIM only...
The original is/was an "original aileron mix" from the mixer library.
Why is the function Differential not included in all mixers - like OTX in the inputs?

**Comment by MPFlyer** [comment]
Hi Bertrand,After switching to another model and then back again, the differential function is now back. Strange but now it works again.Tested in SIM only...The original is/was an "original aileron mix" from the mixer library.Why is the function Differential not included in all mixers - like OTX in the inputs?  Regards,Matthias Von: Bertrand Songis @ FrSkyGesendet: Montag, 14. Juni 2021 11:54An: FrSkyRC/ETHOS-Feedback-CommunityCc: MPFlyer; AuthorBetreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Missing Differential in Mixes (#490) Please send your model file so that I can check if it's an Ailerons Mix or something else—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MPFlyer** [comment]
Hi Bertrand,
back home I tested my X20 again and also created a new model. Unfortunately, the differential function in the aileron mixer has disappeared. Also the update to 1.0.9 RC5 has brought no improvement. Attached my model file.
[model06.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6650979/model06.bin.txt)

Regards,
Matthias

**Comment by Nicholas-Luoyi** [comment]
Thank you for the model file.
I have taken a look into your model. In your model settings. The ailerons are controlled by only one channel. You cannot output two or more values with only one channel right? So the differential is gone.

**Comment by bsongis-frsky** [comment]
Yes of course, differential with only one aileron has very little sense
