### ISSUE TITLE
Suite 1.6.0 macOS 12.7.6 - Download center advertises specific .frsk download for receivers but delivers whole zip file

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#4903]
Not really a problem as getting more than is needed is better than less, but if we are choosing a whole series of products and not a particular product it would be nice for the UI to indicate that. 

Select Particular item in product list (Archer Plus RS for me)
Hit the appropriate download button.
Pop-up window says "Downloading .frsk ..."
Target folder gets a .zip that contains firmwares for all receivers in that family (Archer plus in my case).

**Comment by Nicholas-Luoyi** [comment]
Merged to #4920
