### ISSUE TITLE
Suite reports incorrect model

### ISSUE THREAD

**Issue by blue68camaro-git** [FrSkyRC/ETHOS-Feedback-Community#4905]
I had lost Bluetooth audio capability after an update. Well after spending countless hours and several post on FB I finally figured it out. The update downloaded the X20 files and not the X20s files. As we know X20 does not have Bluetooth hence not having that option available to turn on in audio. Information on radio reports X20s and Suite should also do the same. Would it be nice to also have the picture represent our radio? This is just a reassurance and not critical.

**Comment by Nicholas-Luoyi** [comment]
So your radio is a X20 or a X20S?

**Comment by bsongis-frsky** [comment]
Check what Suite says in bootloader mode. If you have a X20S it should report X20S everywhere, including in bootloader mode.

Ethos 1.7.0 will bring the support for the additional Bluetooth module. On many Tandem radios.

**Comment by blue68camaro-git** [comment]
> So your radio is a X20 or a X20S?

Yes it is an X20s

**Comment by blue68camaro-git** [comment]
> Check what Suite says in bootloader mode. If you have a X20S it should report X20S everywhere, including in bootloader mode.
> 
> Ethos 1.7.0 will bring the support for the additional Bluetooth module. On many Tandem radios.

The radio under System / Info Firmware shows Ethos - X20S. Bluetooth works. FrSky Suite it does not display correctly.

<img width="799" alt="Screenshot 2024-12-23 at 7 15 50 AM" src="https://github.com/user-attachments/assets/a571aa62-f8a5-493f-9fbc-7e2360b609b3" />

**Comment by blue68camaro-git** [comment]
![Info2](https://github.com/user-attachments/assets/ccb46f01-370f-495b-be01-27d7535b1476)

**Comment by Nicholas-Luoyi** [comment]
> > Check what Suite says in bootloader mode. If you have a X20S it should report X20S everywhere, including in bootloader mode.
> > Ethos 1.7.0 will bring the support for the additional Bluetooth module. On many Tandem radios.
> 
> The radio under System / Info Firmware shows Ethos - X20S. Bluetooth works. FrSky Suite it does not display correctly.
> 
> <img alt="Screenshot 2024-12-23 at 7 15 50 AM" width="799" src="https://private-user-images.githubusercontent.com/78920312/398157168-a571aa62-f8a5-493f-9fbc-7e2360b609b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5OTkwMDYsIm5iZiI6MTczNDk5ODcwNiwicGF0aCI6Ii83ODkyMDMxMi8zOTgxNTcxNjgtYTU3MWFhNjItZjhhNS00OTNmLTlmYmMtN2UyMzYwYjYwOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAwMDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MDU2NmFjYWI5MDA3OTYxNDZlMDk4ZjE5MDBiZDViNjkwMDNiNzA2ZmIxNWM1NzBiZmE3ZmZmZTA1MzQwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9r_uFsOA0pJaQ7gPpyyAD0ymakmpIpGyCwDB2IvXNMQ">

Does the radio now connect in bootloader mode?

**Comment by blue68camaro-git** [comment]
It has always connected….. Bluetooth is not the issue….. See pictures!!!!

**Comment by Nicholas-Luoyi** [comment]
I'm not saying the bluetooth but the radio's bootloader mode. I would need your help to investigate the issue of getting the radio information.

**Comment by blue68camaro-git** [comment]
Bootloader is: Version 1.4.15

**Comment by blue68camaro-git** [comment]
<img width="940" alt="Screenshot 2024-12-24 at 7 49 03 AM" src="https://github.com/user-attachments/assets/a638f432-65fd-4aaa-adca-bff10fe89179" />

**Comment by blue68camaro-git** [comment]
Just found this. Start Radio in Bootloader Mode. Connect X20s to Suite. Info shows X20. Then select Ethos in side menu, select: Switch To Ethos. Then the information displayed is correct. SO, in bootloader mode on Suite info is wrong, in Ethos mode it is correct.
<img width="1123" alt="Screenshot 2024-12-24 at 7 57 16 AM" src="https://github.com/user-attachments/assets/0359e613-7aa9-4f30-a88b-113776749a5e" />
<img width="1377" alt="Screenshot 2024-12-24 at 8 01 16 AM" src="https://github.com/user-attachments/assets/01a30ee0-59a5-40dc-931a-7736bce8600f" />

**Comment by Nicholas-Luoyi** [comment]
So I guess the radio was flashed with an incorrect bootloader. You could try to flash the bootloader in Ethos mode with Suite or maually. Once the radio is flashed with the correct bootloader. It should never be incorrect again.

**Comment by blue68camaro-git** [comment]
If that was true that it was flashed with wrong bootloader, say X20,  then I would not have the ability Under General to turn Bluetooth on. X20 does not have bluetooth audio capability, X20s does. 
![IMG_7609](https://github.com/user-attachments/assets/7a63df13-6fc4-44e1-9da3-5573250340e1)

**Comment by Nicholas-Luoyi** [comment]
Your statement is incorrect. Ethos drives Bluetooth audio without requiring support from the bootloader. Just try the ways I metioned above

**Comment by blue68camaro-git** [comment]
I didn't update the boot loader Ethos Suit did. I will do what you are saying. Since I have the wrong boot loader how about  you provide me an exact link to what boot loader I should be using?

**Comment by Nicholas-Luoyi** [comment]
- Just use Suite's bootloader flashing function in the Ethos tab.
- Or manually download the bootloader with the link: https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/download/1.4.15/X20S_BOOTLOADER.zip. Then flash it with the frsk flasher in Download Center tab or with the DFU flasher

**Comment by blue68camaro-git** [comment]
Update with boot loader link you provided using FrSky flasher in Download Center. DFU Flasher keeps reporting DFU device not detected on macOS, does not matter and I don't care.  I am happy to report it now displays correctly. Why did it upload the wrong boot loader? We will never know. Closing this now.
