### ISSUE TITLE
Internal widget "GPS Map" - problem with coordinate entry (1.6.0 EU, X20 Pro AW)

### ISSUE THREAD

**Issue by helitron** [FrSkyRC/ETHOS-Feedback-Community#4908]
Hi, only a maximum of 9° can be entered in the integrated GPS Map widget.

**Comment by bsongis-frsky** [comment]
You are right! We have got one digit precision added in 1.6.0 and this limit should have been updated!

**Comment by helitron** [comment]
Thanks for the quick response !

Kind regards, Erwin

**Comment by bsongis-frsky** [comment]
Too bad that it hasn't been noticed before! It will be fixed in 1.6.1, but not this week. For now 1.6.0 has only few minor issues reported. I prefer keep 15 days minimum before 1.6.1 which will only have fixes
