### ISSUE TITLE
Inactivity alarm bug

### ISSUE THREAD

**Issue by Sigee3** [FrSkyRC/ETHOS-Feedback-Community#491]
Once the inactivity alarm is triggered it doesnt turn off even when flying.

**Comment by loetefix** [comment]
Allready here: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/466

**Comment by Sigee3** [comment]
> 
> 
> Allready here: #466

About time it was fixed then ;)

**Comment by bsongis-frsky** [comment]
Duplicate of #466
