### ISSUE TITLE
Ethos 1.6.0 TD-SR18

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#4913]
Hello. Is it safe to update Ethos to 1.6.0 on models that have the TD-SR18 installed? I have no desire to physically uninstall these receivers and perform the six-axis calibration to have some of the updates that apply to this receiver.

**Comment by bsongis-frsky** [comment]
Ethos is compatible with the previous RF
Except the common VFR. Changes are good in this area, but perhaps you won't need them!
