### ISSUE TITLE
AP stab receiver pins with channels assigned above 16 do not work  -Stab tool 3.0.1 -  firmware 3.0.1

### ISSUE THREAD

**Issue by BompaBert** [FrSkyRC/ETHOS-Feedback-Community#4919]
Assigning mix channels above 16 to any pin ( 1-12) on a SR12+ in the RX settings turns those pins inoperable. Could be valid for other receivers as well.

**Comment by mawzthefinn** [comment]
What's your channel range set to in RF settings? This would occur naturally if the channel range is 1-16 instead of 1-24

**Comment by BompaBert** [comment]
You nailed it - Thx! triple checked RX settings having multiple and totally forgot the RF settings. All good. My apologies for opening this issue as there is none.
