### ISSUE TITLE
Registration / binding of S6R and SR6 do not work

### ISSUE THREAD

**Issue by RayJayVaughn** [FrSkyRC/ETHOS-Feedback-Community#492]
I entered the HF menu and registration mode. I powered up the SR6 while pushing the button down. The green and red LED are on.

The registration menu does not recognize the SR6 being in that mode. Waiting for receiver ist the only remark. Registration and binding do not work.

Same with binding of S6R in accst D16. Binding says - Waiting for receiver (while receiver is in binding mode of cours)

I do use 1.08 version of firmware on my x10s express.

**Comment by Hill2** [comment]
The S6R did register and bind as advertised on my X20.

Firmware used is 1.08

**Comment by RayJayVaughn** [comment]
I just updated the firmware of my SR6 and S6R to 2.17
The X10S Express is on 1.08
The internal module is ISRM-S-X10E HW 1.1.0 FW: 1.1.3 (EU)

Result:

As before. No chance to register nor to bind one of the receivers. With the OTX installed before it was no problem at all.

**Comment by RayJayVaughn** [comment]
I just updated the radio module to FW: 2.1.6 (EU).

Result:
The SR6 is registering and binding
The S6R still does not bind. While pressing the binding button and powering it up red and green are lighting up. Then red goes off and green remains on. Nothing else happens.

**Comment by Hill2** [comment]
You don't have to press the button for binding. Only for register. After register disconnect the battery and back on after pressing bind in the transmitter. The receiver will bind automatically.

**Comment by RayJayVaughn** [comment]
The SR6 is working fine now. And yes, as you described. Healed by FW-Update of the module.
The S6R is an ACCST D16 Receiver LBT EU. Classical binding. And this still does not work.

**Comment by Hill2** [comment]
Also put the internal module on ACCST instead of the standard ACCESS in the X20?

**Comment by RayJayVaughn** [comment]
Yes. Of course. There is a fundamental difference between ACCST and Access-Binding. ACCST is binding immediately (under normal non-incidental cirumstances). With Access you have to register first, then you can bind. 

And, of course, I chose the ACCST for the S6R - this is not binding (no need to register in advance).

**Comment by RayJayVaughn** [comment]
No idea why but now it works :-) Thank you for your comments
