### ISSUE TITLE
Request/Fix/Redo: Trainer system, add channels

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#493]
Now the trainer channels are fixed to the standard 4 input channels, it is not possible for heli training to assing the Trainee Throttle channel to a Pitch mixer.

The Throttle channel at the moment is not working at all also. so that should be fixed.

We should be able to define ourselves where to map the trainee channels to a mixer.
At least add 4 extra channels where we can define the mapping ourselves.

Imposible to do heli training now.

**Comment by DigiDiDoDoo** [comment]
I can confirm these problems too.

Throttle channel is indeed not working.
I also do a lot of heli training.
With this trainer system as it is now it is not possible to do heli training.
I agree with hobby4life you need to control a pitch mixer.

Hope this will be fixed soon.

**Comment by bsongis-frsky** [comment]
16 channels from Trainer now assignable to:
- any stick, pot, slider (it will replace the trainer input)
- any channel (it will replace the trainer channel)

![image](https://user-images.githubusercontent.com/50834778/122571070-a177b180-d04c-11eb-9ca9-6b4b1bfb3dac.png)

**Comment by Hobby4life** [comment]
This looks awesome :-) can I try a nightly version? ;-)
