### ISSUE TITLE
Absolute paths used in ETHOS 1.6.1

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#4935]
Hello Bertrand,
in ETHOS 1.6.0 this works

local path ="./"
local modellpath="./modelle/"
local libpath="./lib/"
local bitmappath="./bitmaps/"

but in ETHOS 1.6.1 it doesn't work
however if I encode everything works again

local path ="./"
local modellpath="SCRIPTS:swmap/modelle/"
local libpath="./lib/"
local bitmappath="./bitmaps/"

But here only the model path is set, so why do the remaining connections work correctly?

**Comment by Alex00101** [comment]
Sorry, where did you get 1.6.1 fom?

**Comment by frankiearzu** [comment]
nightly builds, in releases (Ethos 1.6.1)
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/nightly16

**Comment by Alex00101** [comment]
Thanks, missed that

**Comment by philippe-warnotte** [comment]
Old version from October !
