### ISSUE TITLE
TD SR12 Not getting RXBatt telemetry

### ISSUE THREAD

**Issue by mszulen** [FrSkyRC/ETHOS-Feedback-Community#4938]
Newest firmware on both: X20s and receiver.
This is all telemetry sensors I'm getting from the receiver. No RXBatt being received.
Did I miss something or there's bug?

![sensor1](https://github.com/user-attachments/assets/311a094b-f2d2-4ffc-8c43-883fecf6d0d6)
![sensor 2](https://github.com/user-attachments/assets/e870aebd-6fce-4cb4-af02-fcdac31073b3)
![sensor3](https://github.com/user-attachments/assets/68125a7a-9597-4a70-b4be-a56cabbf6b36)
![sensor4](https://github.com/user-attachments/assets/a4caac64-b211-488b-8569-303e055200f4)

**Comment by Quimb0** [comment]
Hi, I think what happens is that in the srx basic menu you activate the IMU mode function to basic, with this change you get more telemetry data or in the telemetry menu delete the sensors and search to see if they are available

**Comment by airxplore** [comment]
Not sure how up to date your RX firmware is but RC2 was released to address this issue. Might be worth double checking. See below

https://github.com/FrSkyRC/RF_Feedback_Group/issues/78#issuecomment-2559372097

**Comment by mszulen** [comment]
> Not sure how up to date your RX firmware is but RC2 was released to address this issue. Might be worth double checking. See below
> 
> [FrSkyRC/RF_Feedback_Group#78 (comment)](https://github.com/FrSkyRC/RF_Feedback_Group/issues/78#issuecomment-2559372097)

Thank you! This did solve my issue. I was looking on the Frsky product page where RC2 is not mentioned (there's still the old firmware).  I wish the product pages are more up to date (ancient manuals, not up-to date firmware...). Not a big problem for me, since I'm on RCGroups and github, but I can imagine it frustrates majority of customers when they have to search around for the information.
