### ISSUE TITLE
Change model, clone

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#4939]
My 1.6 went perfect, not any issues. I'm trying to keep all the settings on a mobel glider but I'm trying to add ailerons. How can I copy the model and add ailerons? I did go and change the model but, when I look at the output, it doesn't show any output for the ailerons. 
Thanks again.

**Comment by lotus1235** [comment]
I think I figured it out, had to add ailerons in the mixer department.

**Comment by Richrfl** [comment]
Please, check if as the author you can close this issue.
