### ISSUE TITLE
Throttle cut not quite "sticky"

### ISSUE THREAD

**Issue by MikeBland** [FrSkyRC/ETHOS-Feedback-Community#494]
Testing with 1.0.9RC4.
Set Throttle Cut to switch SFv, Trigger -98%, and Output value -100%.
With SFv, the output stays at -100%.
Set the throttle stick above -98% and switch to SF^, throttle stays at -100%.
Move the throttle stick to -100%, then the throttle output follows the stick.
Switch SF to SFv, the throttle remains active following the stick.
Move the throttle stick to -100%, then the throttle output stays at -100%.

For electric power, I would expect switching SF to SFv would cut the throttle to -100% immediately (Sticky throttle cut).
If this mode of operation is not suitable for an I/C engine, then please add an option to the throttle cut to enable "sticky" operation.

With electric power, I believe it is dangerous if there is a mode where the motor may run when throttle cut is supposed to be active.

**Comment by loetefix** [comment]
You have to set trigger value to +100 . Thats the throttle value when the cut goes activ. At 100 it will allways be activ if condition is true.

**Comment by MikeBland** [comment]
Using +100 only gives "Throttle cut", not "Sticky throttle cut".

**Comment by centertrim** [comment]
Is this the easiest way for a user to self-implement a hold that will only activate at low throttle positions, but will disable the instant the hold switch is flipped?  This is with 3 logical switches:

LSW1:  Throttle Hold Switch Active OR !LSW2
LSW2:  Sticky, Trigger On = LSW3, Trigger Off = Throttle Hold Switch Falling Edge
LSW3:  Throttle Stick < -85 AND Throttle Hold Switch Rising Edge

Then set the throttle hold in the throttle mixer to activate on LSW1.  Technically LSW1 isn’t needed (throttle hold active condition could be set to !LSW2), but it gives me a warm fuzzy feeling using it as a “gate” to ensure that if the throttle hold switch is active then there’s absolutely no chance there will be any kind of throttle output even if there’s a problem with the logic in LSW2 or LSW3.

Seems like a bit much for a user to go through to get this important safety functionality.

**Comment by MrD-RC** [comment]
Is this similar to https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/473

**Comment by bsongis-frsky** [comment]
Fixed in RC4
