### ISSUE TITLE
APD Powerdrives ESC protocoll to S.PORT 

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#495]
Hello, 

it would be very awesome if you implement the APD Powerdrives ESC protocoll to Frsky S.PORT. So far the telemetry is not compatible to S.PORT. I or we hope, that it is possible in near feature 👍🙂👍

**Comment by centertrim** [comment]
This would be better directed at APD to implement SPort or FPort telemetry in their ESCs.  FrSky shouldn’t be in the business of cluttering up the receiver firmware with various other manufacturer’s telemetry protocols.

**Comment by bsongis-frsky** [comment]
I think we have enough work with our own business :)
