### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Hill2** [FrSkyRC/ETHOS-Feedback-Community#497]
Possibility to have throttle on a switch and stick at the same time.

For throwing airplanes it can be helpful if you have a throttle slider on the right/left hand when throwing the airplane with the other hand. After throwing you can go back to the stick and fly further as normal.

**Comment by Hobby4life** [comment]
You can do that easily adding a second mixer.. only it reacts to a switch. assign it to ch3 and you are done.

**Comment by Hill2** [comment]
Okay, then this issue can be closed.
