### ISSUE TITLE
1.0.9 RC5 - Feature - Audio file "bye.wav" played on radio shutdown

### ISSUE THREAD

**Issue by MPFlyer** [FrSkyRC/ETHOS-Feedback-Community#498]
how can I turn this option on? 
My X20 does not play this sound when shutting down after updating to 1.0.9 RC5

**Comment by T16-Pilot** [comment]
You need to put the file in your sd card. It is not there by default.
I tok mine from my Otx sound pack, it works great.
Also, there are a lot of sound files "missing" on the sd card. I tok more or less the hole sound pack from Otx and dumped in my sd card. And it works great.

**Comment by MPFlyer** [comment]
YESSS - works !!! Thanx 🥇

**Comment by bsongis-frsky** [comment]
@T16-Pilot which are the "missing" sound files from the SD card?
