### ISSUE TITLE
There is no Spanish translation in the final version 1.0.9.

### ISSUE THREAD

**Issue by marevalor** [FrSkyRC/ETHOS-Feedback-Community#499]
I just loaded version 1.0.9 (FCC # 4fc44c32) and I am surprised that there is no file for the SD with the sounds in Spanish. I go to the menu to change the texts from English to Spanish and it doesn't exist either.

**Comment by bsongis-frsky** [comment]
The person who did the display translations still didn't send the listing of audio files needed for ES
