### ISSUE TITLE
Gyro on x12s

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#50]
Gyro not supported in x12s
X12s ethos V1.0.1

**Comment by jbule1980** [comment]
Gyro and internal GPS still not supported on X12S Ethos V1.0.9

**Comment by KAD370** [comment]
any progress on that?

**Comment by Cyberfrankyboy** [comment]
Gyro not support on 1.1.1

**Comment by KAD370** [comment]
Come on… transmitter is on market since 2015… and no team opentx or team ethos can’t make it work, but it works on rfos…

**Comment by Luznatural** [comment]
Any advance on this issue?
Please, reactivate it.

**Comment by bsongis-frsky** [comment]
Added in 1.4.6
