### ISSUE TITLE
Opportunity of changing curve list order

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#500]
Hello,

it would be good to get the opportunity to change in curve list the order like moving in the list first curve to third position for example.

Thank you

**Comment by centertrim** [comment]
Agreed!

**Comment by bactisme** [comment]
I would like to add something related to curves : 
going to curve edition from mixer, modifying the name of the curve, and going back to mixers, the name is not updated.
