### ISSUE TITLE
Bug in model ID numbers

### ISSUE THREAD

**Issue by NMO81** [FrSkyRC/ETHOS-Feedback-Community#501]
I just noticed in 1.0.9 that in the model selection menu where I have 3 models, the Model ID's for these are 6, 8 and 14. But on the SD card in the models folder they are called model03.bin, model04.bin and model07.bin. 

Somewhere these numbers are doubled.

**Comment by MIKE-DAILEY** [comment]
The model name and model RF ID are two different things.   The model name is created when the model is created and the model RF ID is created or selected on the RF screen when you register and bind a receivers.  If you want the IDs to match change the model RF ID.  Will need to reregister and bind receivers.

**Comment by NMO81** [comment]
Ok my bad Indeed the .bin name is also clearly indicated
