### ISSUE TITLE
Checklist slider 1 and 2 no switch warning

### ISSUE THREAD

**Issue by michifpv** [FrSkyRC/ETHOS-Feedback-Community#502]
In the checklist for slider 1 and 2, only position -95 is reported as a switch warning. For example, if I want position 95, the slider can be in any position without a switch warning when switching on ethos.

AND

i would like to be able to select "play track" at the end points of the slider. Unfortunately, under special functions, the slider is not noticed when I move it. this function would be useful if you have your flaps on the slider.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/122775918-ea2ca600-d2aa-11eb-9040-fd69441dbeee.png)
