### ISSUE TITLE
Vario delay

### ISSUE THREAD

**Issue by Boxxxer64** [FrSkyRC/ETHOS-Feedback-Community#503]
Vario telemetry delayed by about 2 seconds. When I go from climbing into descent, it takes about 2 seconds for the vario to indicate sinking.

X12s Ethos 1.09 Gr8 Access

Otherwise I would like to leave a big thank you. it is impressive how quickly ethos is being developed here. it's really fun

Best Regards Martin

**Comment by aalain8** [comment]
Under OpenTX the GR8 receiver in v2.1.7 has a sound delay of 2S.
The GR8 in v2.1.5 has no sound delay!
On the other hand on a F5J I have frequent telemetry and RSSI alerts in v2.1.5.  
Many months in v2.1.7 and a perfect RSSI and VFR log. 
Is the same with Ethos?

**Comment by Boxxxer64** [comment]
I can't tell you whether it's the same under Opentx. I have the same problem with the gr6 with vario.
All with Ethos 2.1.7 Firmware

**Comment by Hobby4life** [comment]
Looks that the slow update rate of vario values are causing these delays. I personally stepped away from these receivers with build in varios. I now use diy openxsensor vario with ms5611 sensors. This has a very highspeed value update rate to the system that translates in very quick response.

**Comment by bsongis-frsky** [comment]
Receiver issue, depending on the receiver firmware version

**Comment by aalain8** [comment]
I hope Frsky looks at the problems marked RF by Bertrand, it is essential to correct this before releasing a new product.

**Comment by Adelaxie** [comment]
2.1.8 for Archer updated.

**Comment by aalain8** [comment]
Thanks Adelaxie, the 2.1.8 beta version works well on my X10 Ethos 1.0.10rc4.
I will test the official version when I get back from vacation.
Thanks for listening
