### ISSUE TITLE
Spanish audio V2

### ISSUE THREAD

**Issue by iulius-esp** [FrSkyRC/ETHOS-Feedback-Community#504]
This is the txt file for the Spanish audio. I can't use Google Cloud Text to Speech.

[audio_es.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6663983/audio_es.txt)

**Comment by bsongis-frsky** [comment]
And do you speak it (grammar, etc.) the same than english or french?

**Comment by iulius-esp** [comment]
Yes, spanish is my language, in french and english I only have basic knowledge.
Fortunately, in English I know the terminology used in RC, which allows me to translate into Spanish.
