### ISSUE TITLE
Missing Spectrum Analyzer

### ISSUE THREAD

**Issue by darkernoise** [FrSkyRC/ETHOS-Feedback-Community#505]
According to the Access protocol information page, one of the key features in ACCESS over ACCST is that the transmitter now has a spectrum analyzer feature.  Why is this spectrum analyzer missing on the flagship X20S?  When can we expect this feature to be released?

"In addition, new tools like a Spectrum Analyzer are now available on your transmitter."

https://www.frsky-rc.com/frsky-advanced-communication-control-elevated-spread-spectrum-access-protocol-release/

**Comment by bsongis-frsky** [comment]
I think that the TD-ISRM doesn't have enough flash to have 2 bands + the RF analyser

**Comment by darkernoise** [comment]
You say, "I think".  Are you sure?  That is a really disappointing answer and feels like a bait and switch.  There is no disclaimer on the X20S information page indicating that you don't get a spectrum analyzer like the lower models have.  I expected for the high price I paid that the X20S would surpass the features of the lower models.

**Comment by bsongis-frsky** [comment]
Updated my comment

**Comment by Hobby4life** [comment]
> You say, "I think". Are you sure? That is a really disappointing answer and feels like a bait and switch. There is no disclaimer on the X20S information page indicating that you don't get a spectrum analyzer like the lower models have. I expected for the high price I paid that the X20S would surpass the features of the lower models.

No offense :-) but:

Please tell me what the **real functionality** it has for you?

I really can not imagine that there is any real use for the so called spectrum analyzer at all..
It was only build in because it was possible to make a Spectrum Scope, not Spectrum Analyzer folks ;-)

With all the extremely fast frequency hopping systems these days, and the slow refresh rate of the scope (that is why it is called a scope)
You cant get any usefull information at all from it.
Yes you can see something HAS happened on the 2.4ghz band. but it is jumping all arround.

I suggest to preserve flash and ram and coding time for something really usefull stuff.

**Comment by darkernoise** [comment]
Hobby4Life, well, one good example is that my club's flying field is now bracketed by apartments with outside 2.4 Wifi.  The spectrum analyzer feature would allow me to get an idea of the signal congestion in the band at specific locations.  Though, more to the point, a spectrum analyzer is an advertised feature.  Taking away a published feature without advertising the disclaimer crosses fiduciary lines.

**Comment by bsongis-frsky** [comment]
I am not sure it will help you at anything, except show it to impress your friends :)

**Comment by Hobby4life** [comment]
> Hobby4Life, well, one good example is that my club's flying field is now bracketed by apartments with outside 2.4 Wifi. The spectrum analyzer feature would allow me to get an idea of the signal congestion in the band at specific locations. Though, more to the point, a spectrum analyzer is an advertised feature. Taking away a published feature without advertising the disclaimer crosses fiduciary lines.

As far as I know it is only available for Horus X10 and X12 (and its working),, Never seen it advertised for X20

**Comment by OldGazer** [comment]
I agree with Mr. Songis.  In this context, Spectrum Analyzer is a complete misnomer,  The functionality provides no usable output data,
