### ISSUE TITLE
Updated Translation and Sound Pack - Portuguese

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#506]
Find attached latest translations files to Portuguese (of Portugal: PT-pt).

**Text translation (based on the file from Ethos 1.0.9.)** 
File: [pt(Ethos1.09).txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6665073/pt.Ethos1.09.txt)

Known issues for @bsongis-frsky : 
- the char "õ" still needs to be added. 
- Stick modes naming (i.e. AERT,ATER, etc...) can not be changed in the translation document and they are also not dependent on the initials set by the "xxx_LETTER" input string. 
As in Portuguese throttle is "acelerador", we have two change the initials to define both Acelerador (Ac) and Ailerons(Aí).  So "AERT", should be represented as "Ai P D Ac", and so on, which is not the case. 

![image](https://user-images.githubusercontent.com/25162166/122275111-3ce91500-cedb-11eb-9c65-1b24c322de3e.png)

**Sound pack translation (for Ethos 1.0.9.) based on @hobby4life files**  
Files: https://www.dropbox.com/s/cnjh5py16g23sf8/soundFiles.zip?dl=0

**Comment by andika207** [comment]
''As in Portuguese throttle is "acelerador"
é mais facil escrever M de motor... e ''manche'' será na tua terra porque a tradução mais usada é ''manete''

**Comment by jreis1** [comment]
> ''As in Portuguese throttle is "acelerador"
> é mais facil escrever M de motor... e ''manche'' será na tua terra porque a tradução mais usada é ''manete''

Throttle é acelerador. Não convém ser motor pois a este é usado na tradução de “engine” e “motor”.  Aconselharam me a usar “potencia” mas não achei que se encaixa-se. 
 
Relativo aos sticks, tive o cuidado de sondar vários aeromodelistas  e  pilotos de linha aérea, “stick” pode ser traduzido para “manche”.

**Comment by andika207** [comment]
@jreis1 talvez  **V**elocidade ?
não é necessario traduzir tudo ao 100% para ficar perfeito, 'stick' fica melhor do que 'manche'

**Comment by andika207** [comment]
@jreis1 talvez  **V**elocidade ?
não é necessario traduzir tudo ao 100% para ficar perfeito, '**stick**' fica melhor do que '**manche**' e '**direção**' fica melhor do que '**deriva**'

**Comment by jreis1** [comment]
> @jreis1 talvez **V**elocidade ou **G**as ???
> não é necessario traduzir tudo ao 100% para ficar perfeito, '**stick**' fica melhor do que '**manche**' e '**direção**' fica melhor do que '**deriva**'

This is not a question of just sounding better or not. The translation must be done in line with the most used terms in the aeronautics field. 

Throttle should be translated to "Acelerador". We could also use "Motor" as you have previously suggested, but then we would have the issue of having the same word (Motor) to represent both system Inputs and Outputs, since "motor" is also the translation for "Engine" and "Motor". I believe this might represent a critical issue when setting up the radio. If this is not an issue, I will also use the word "Motor" for the "throttle" stick to avoud Ai/Ac representation. Please @bsongis-frsky  advise accordingly. 

"Sticks" could be maintained as in English, but I've confirmed with several people, including airline pilots, and "manche" is also a valid option. You can inclusive see from the Ethos French Translation. where "Sticks" translate to "Manche". Note that most of the Portuguese terms for aeronautics also came from the French (e.g. "profundidade" which translate from the french "profondeur" (elevator in EN)).

The same happens with the word "Deriva", which translates from the french "Dérive" (rudder). This is also in line with the Ethos FR translation. "Direção" as you suggested, doesn't even make sense in the context and it is already being used to translate "direction".

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/123054108-d5fcbc00-d404-11eb-98d7-1e5797641e37.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/123054331-0c3a3b80-d405-11eb-8186-cd4349224d41.png)

**Comment by bsongis-frsky** [comment]
We don't store the sound files that we cannot maintain. Instead we store the CSV file that you will find in the other issue. It allows us to generate automatically all sound files

**Comment by jreis1** [comment]
> We don't store the sound files that we cannot maintain. Instead we store the CSV file that you will find in the other issue. It allows us to generate automatically all sound files

Thanks. Next time I'll just share the the CSV file.

**Comment by bsongis-frsky** [comment]
You didn't attach it, right?

**Comment by jreis1** [comment]
[ETHOS PT + H4L(Ethos1.09).zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6700846/ETHOS.PT.%2B.H4L.Ethos1.09.zip)

Sorry, here it goes (it was inside the sound pack zip)

**Comment by bsongis-frsky** [comment]
I need a CSV file, not a PSV file

**Comment by bsongis-frsky** [comment]
Example for french:
[audio_fr.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6701144/audio_fr.txt)

**Comment by jreis1** [comment]
> I need a CSV file, not a PSV file

ok I see. I've done the sound translation using TTS Automate, so all phonetics are adapted to TTS system. 
Which service do you use then ? Google Text to Speak? 

I could do a "raw" translation based on the file you have shared, but further phonetics review must be done. (e.g RSSI in TTS automate must be set as "ÉrreÉssÉssÌ" to phonetically sound right in PT).

**Comment by jreis1** [comment]
@bsongis-frsky please find attached PT .csv, based on the french file you provided. 
[audio_pt.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6702408/audio_pt.txt)

Please note that the file you provided is only 198 input lines long, whereas the Spanish file is 199 lines long and the EN file available online @Hobby4life is 239 lines long (excluding headers) .  I think French and Spanish sound translations might have been done using an outdated file. 

Can you confirm which file is correct?

**Comment by bsongis-frsky** [comment]
The translations don't use the same audio prompts, so yes it is normal

**Comment by bsongis-frsky** [comment]
prompts generated, audio ES and PT will be part of the 1.0.10

**Comment by andika207** [comment]
> Note that most of the Portuguese terms for aeronautics also came from the French 

@jreis1 Yep, the sound files also came from a french speaking woman because you are using the shitty portuguese from Lisbon
anyway I will always use spanish language as my primary option or even better english as a second alternative.

**Comment by andika207** [comment]
> "Direção" as you suggested, doesn't even make sense in the context and it is already being used to translate "direction".

it makes a lot of sense because NOBODY has ever used ''deriva'' on the heli world, it's always been > tail = ''cauda''

**Comment by andika207** [comment]
> "Direção" as you suggested, doesn't even make sense in the context and it is already being used to translate "direction".

@jreis1 it makes a lot of sense because NOBODY has ever used ''deriva'' on the heli world, it's always been > tail = ''cauda''
