### ISSUE TITLE
request : checkbox for use common output limits 

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#507]
A checkbox to activate common limits / center for all channels would be great (for example on Output 1 ,so all  channels use same limits / center as channel 1).
This would make it more easy to configure a FBL Helikopter.So you can edit the values on output channel 1 and set the checkbox.

usualy fbl-systems use same limits on all channels.

**Comment by loetefix** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/187

**Comment by mawzthefinn** [comment]
Also useful when converting aircraft from different systems, to get default output scaling correct (especially with Spektrum)

**Comment by loetefix** [comment]
any news here?

**Comment by loetefix** [comment]
Is there chance for this feature in the near future. I think its a basic function and a must have for fbl helicopter.

**Comment by loetefix** [comment]
Seems its not needen.
