### ISSUE TITLE
"bye" turning off TX X20 1.09

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#509]
Hi,

does the "bye" work when turning off the radio 1.09 X20? Mine keeps quiet. Not important but interesting.

**Comment by Hobby4life** [comment]
You need to create the bye.wav yourself and place it in audio/en/system

**Comment by combat-marcus** [comment]
> You need to create the bye.wav yourself and place it in audio/en/system

Okay, thank you!
