### ISSUE TITLE
Cross Trims - Trim graphics on Home page is not shown correctly

### ISSUE THREAD

**Issue by AfterburnerRC** [FrSkyRC/ETHOS-Feedback-Community#510]
X20S / 1.0.9 FCC - Cross Trims are working correctly on Outputs page however on the Home page the trim graphics reflect no changes. I have cross trims enabled and I applied 10 clicks of trim to the aileron and elevator but the Home page reflects changes to throttle and rudder trims. I would think the graphics would follow the cross trim settings?

![Capture 1](https://user-images.githubusercontent.com/85705146/122455765-c00d7800-cf7a-11eb-8a46-33771b81a382.JPG)

**Comment by WismyYao** [comment]
The home page shows the percentage of the entity trim value

**Comment by AfterburnerRC** [comment]
No,  it’s shown on the wrong side???  It should be shown on the right side if cross trims are set.  This has been confirmed as a bug by another user and myself.

**Comment by seilfly** [comment]
Hope this is done something about. You get a little confused !

**Comment by mawzthefinn** [comment]
This appears to be corrected now. I just tested and it is behaving correctly on 1.4.3
