### ISSUE TITLE
S8R can not go into stick calibration mode

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#511]
S8R
Works fine on Opentx X10S
with X20S ethos 1,0.9 set to CH1-CH16, toggling CH12 does not send the Rx to stick learning mode (blue light) no matter the throttle position or the switch toggling rate.

any ideas guys?

**Comment by Liverboy77** [comment]
You need to go into SYSTEM then HARDWARE, the switch middle detect delay is set to 100ms by default adjust this to 0ms and it will work. Every time you turn your tx on it goes back to 100ms

**Comment by i3dm** [comment]
changed the delay to 0.
still does not enter self test mode.

**Comment by Liverboy77** [comment]
Is channel 12 on a 3 pos switch?

**Comment by i3dm** [comment]
yes ch12 is 3pos switch.
i can make a video if needed.

**Comment by i3dm** [comment]
im uploading a video of the issue now

**Comment by i3dm** [comment]
https://youtu.be/jHlhFQrVvms

**Comment by tysonfromcanada** [comment]
have a similar problem with S6R on 2.1.1 firmware/opentx.. learn mode enters but doesn't work properly or complete.  Ok on 2.1.0

**Comment by T16-Pilot** [comment]
Try to do this.

1. Program all the channels on your radio.
2. Set the **_Switch middle detect delay_** in the Hardware menu to 0% (This is the key to fix the issue).
3. Bind your S8R.
4. Power on your S8R and flick the switch on channel 12 tree times.

I just tested it, works like a magic.

I also had problems with this on SR6.

For the SR6 the problems was a combination of software and what to do first and last to get it to work. You need to do this i a specific order to get it to work.

This is what i had to do. I am running Archer SR6 in ACCESS mode. Not D16...

A small tip, you need to flick the switch really quick after you power on the rx. Do not wait. I ended up using a rx battery with a power switch to be able to enter "self check mode" as it is called.

1. Role back to V2.1.5 or V2.1.6 on the SR6/SR8
2. Set the **_Switch middle detect delay_** in the Hardware menu to 0%
3. Program all the channels Gain, Mode and Channel 12
4. Register the SR6/SR8
5. Bind SR6/SR8 to the TX.

In that order, then it works.

V2.1.7 might have a bug or some thing that is messing things up.

**Comment by i3dm** [comment]
tried what you said in the S8R, does not work.
reverted firmware now to 2.1.0 and it doesnt want to bind anymore. very odd.

**Comment by i3dm** [comment]
tried your instructions on S8R - doesnt work.
revering Rx back from fw 2.1.1 to 2.1.0 now

**Comment by T16-Pilot** [comment]
It works, you need to power on your X20, the power on your rx and then right away flick the switch. It works, i just did it tree times with a S8R.

**Comment by i3dm** [comment]
Rx can go into self test mode any time it is on, it does not have to be at the beginning.
it works fine any time on X10S Express.

**Comment by i3dm** [comment]
Reverted back to rX FW 2.1.0 - same issue, even if i flick the switch right aay after power up - it does not go to self test.
which version ethos and tdisrm are you running?

**Comment by T16-Pilot** [comment]
I know it works fine on the X10s, it also works fine on my TX16s. But on the X20 it has to be done the way i tell you. Trust me. I just tried now with the rx power on for a minute. It did not work, but if i power on the rx and then right away flick the switch it works. It is a bug in the system, but that is how it works for now. I spent a day figuring out how to get this working on my X20.

**Comment by i3dm** [comment]
i bound back to X10S - orks on the first try.
tried X20 AGAIN as you instructed - does not work.
which versions Ethos and TD-ISRM are you running on X20?

**Comment by T16-Pilot** [comment]
1.0.9 EU and 2.1.8 for the TD-ISRM

**Comment by i3dm** [comment]
im on 1.0.9 FLEX and TD-ISRM 2.1.8 and it does not work under any circumstances

**Comment by i3dm** [comment]
Just flashed Ethos V1.0.9 FCC - still doesnt work.
there is definitely an issue here. perhaps the 0 switch delay isnt implemented correctly?

**Comment by T16-Pilot** [comment]
It is tricky to get to work i know. But it does work.

Firmware for my S8R is 2.1.0 EU LBT

There is a lot that is not working correctly on this X20. I wish it was possible to run otx on it, boy what a radio it will be...!

**Comment by tysonfromcanada** [comment]
> There is a lot that is not working correctly on this X20. I wish it was possible to run otx on it, boy what a radio it will be...!

That is pretty much what's preventing me from buying one... Need the lua support for flybarless controllers for one.

**Comment by T16-Pilot** [comment]
> Just flashed Ethos V1.0.9 FCC - still doesnt work.
> there is definitely an issue here. perhaps the 0 switch delay isnt implemented correctly?

I think it is a bug in Ethos some where. I am not a programmer... :)

I just flashed my S8R again with 2.1.0 EU LBT and bind it to my X20, set the Switch middle detect delay in the Hardware menu to 0%. Switched on my S8R and flicked the switch tree times and the blue led came on and the self check did its think.

Did the same with a SR6 on ACCESS just now, works fine. But you need to flick the switch right after powering on the rx.

**Comment by i3dm** [comment]
tried it 100 times right after power on ;)
no joy.

**Comment by T16-Pilot** [comment]
> tried it 100 times right after power on ;)
> no joy.

Hmm... interesting, it works every time on my end. I got a standard X20 with EU firmware because i live in Norway, not the X20s.

I spent a lot of time two days ago to get this to work. There are a lot of people that got this issue, we are not alone. There is a bug in the system.

**Comment by i3dm** [comment]
i have a x20 too.
can you post a video of how you do it?

**Comment by T16-Pilot** [comment]
> i have a x20 too.
> can you post a video of how you do it?

Here you go

https://www.youtube.com/watch?v=8-MuM9l1o6g

**Comment by i3dm** [comment]
video us private - i cant see it. please change to unlisted.

**Comment by T16-Pilot** [comment]
> video us private - i cant see it. please change to unlisted.

I am sorry about that, just changed it. Please try again.

**Comment by i3dm** [comment]
interesting. definitely the same way doesnt work for me.

**Comment by T16-Pilot** [comment]
Interesting, i just did another video showing my settings and it still worked. Uploading at the moment...

**Comment by T16-Pilot** [comment]
Here is my settings for the test model just for testing the S8R setup.

https://www.youtube.com/watch?v=Oto1aPm1P7E

**Comment by FrSky-GX** [comment]
1.make sure the SXR function is enabled（by device config）；
2.make sure the RF channel range set to CH1-CH16；
3.switch detect delay set to 0ms；
4.throttle must be CH3，and keep it in the lowest position；
5.must assign a 3-pos sw to CH12；
6.move the CH12 switch as quickly as possible for 3 times above；

**Comment by i3dm** [comment]
> 1.make sure the SXR function is enabled（by device config or lua or APP）；
> 2.make sure the RF channel range set to CH1-CH16；
> 3.switch detect delay set to 0ms；
> 4.throttle must be CH3，and keep it in the lowest position；
> 5.must assign a 3-pos sw to CH12；
> 6.move the CH12 switch as quickly as possible for 3 times above；

done all of this.
still no joy. doesnt work.

**Comment by Cipta-de** [comment]
For me it worked when I added a delay of 0,1 to ch12

**Comment by i3dm** [comment]
where did you add this delay? got a photo?

**Comment by Cipta-de** [comment]
Output CH12 Slow Up / Slow Down 0,1s 
and maybe it would be good to change the min / max value to 103% to reach 1000ms to 2000 ms output range

**Comment by i3dm** [comment]
just tried. doesnt work on my S8R.
my buddy has the same setup on access SR8 with no issues.
and my S8R works fine on horus X10S express.

**Comment by hrenz** [comment]
forget the X20, ETHOS, TD, the next half year
lots of errors with telemetry-system

You only get annoyed

**Comment by DaySpeed955i** [comment]
Do you have your throttle ch3 a -100%? it is a must.

**Comment by i3dm** [comment]
> Do you have your throttle ch3 a -100%? it is a must.

yes.

**Comment by DaySpeed955i** [comment]
Just use a servo and/or a sbus decoder to confirm ch3 and ch12 if they really move at the Rx, something's fishy.

AH, just check your video, in output, your thr is on ch1 set at -100% and you ele is at 1500us(0%) that will no work.

You must follow AETR for SxR.

**Comment by i3dm** [comment]
> Just use a servo and/or a sbus decoder to confirm ch3 and ch12 if they really move at the Rx, something's fishy.
> 
> AH, just check your video, in output, your thr is on ch1 set at -100% and you ele ch3 is at 1500us(0%) that will no work.
> 
> You must follow AETR for SxR.

youre right! cant believe i missed that. will recheck. thank you.

**Comment by Hobby4life** [comment]
> Just use a servo and/or a sbus decoder to confirm ch3 and ch12 if they really move at the Rx, something's fishy.
> 
> AH, just check your video, in output, your thr is on ch1 set at -100% and you ele ch3 is at 1500us(0%) that will no work.
> 
> You must follow AETR for SxR.

And this proves again that AETR must be the standard at all in Ethos to comply their own products ;-)

**Comment by i3dm** [comment]
throttle set to CH3 and all is OK :)
issue closed.

**Comment by DaySpeed955i** [comment]
> 
> 
> > Just use a servo and/or a sbus decoder to confirm ch3 and ch12 if they really move at the Rx, something's fishy.
> > AH, just check your video, in output, your thr is on ch1 set at -100% and you ele ch3 is at 1500us(0%) that will no work.
> > You must follow AETR for SxR.
> 
> And this proves again that AETR must be the standard at all in Ethos to even comply their own products ;-)

I believe all their radios come with default to AETR. It is very nice to have fully open system but, it can lead to mistakes by users and spread false information like we saw in this thread.

@i3dm 
I am glad it is now working, now, go fly!

**Comment by pld74** [comment]
Hi all, I am clearly missing something but have been using the SxR for a while and programmed many in OpenTX and no challenges like I am finding in Ethos with this particular Radio. Helping a few friends out with their New X20 and their SR10. When we bind it to the X10S running OpenTX is works flawlessly, when we bind it to the X20, can't get it to Self Check Mode.

Checked all the following:
Radio Channel Order set to AETR
Create New Model
Added 4 Free Mixes and output to Ch 9, 10, 11, 12
Ch 9 50% Offset and 50% Up and 50% Down
Calibrated and Enabled SxR Function from within Ethos Config App
Confirmed Ch 3 is Throttle at -100%
Tried Switch Delay Detect at 0,10,100ms
Tested Ch 12 with a 3-POS and 2-POS switch
All outputs are reporting on the correct channel and correct values

Any suggestions where else to look? 

Thanks in advance :)

**Comment by i3dm** [comment]
> Hi all, I am clearly missing something but have been using the SxR for a while and programmed many in OpenTX and no challenges like I am finding in Ethos with this particular Radio. Helping a few friends out with their New X20 and their SR10. When we bind it to the X10S running OpenTX is works flawlessly, when we bind it to the X20, can't get it to Self Check Mode.
> 
> Checked all the following:
> Radio Channel Order set to AETR
> Create New Model
> Added 4 Free Mixes and output to Ch 9, 10, 11, 12
> Ch 9 50% Offset and 50% Up and 50% Down
> Calibrated and Enabled SxR Function from within Ethos Config App
> Confirmed Ch 3 is Throttle at -100%
> Tried Switch Delay Detect at 0,10,100ms
> Tested Ch 12 with a 3-POS and 2-POS switch
> All outputs are reporting on the correct channel and correct values
> 
> Any suggestions where else to look?
> 
> Thanks in advance :)

verify RF menu channel range: ch1-ch16

**Comment by pld74** [comment]
> > Hi all, I am clearly missing something but have been using the SxR for a while and programmed many in OpenTX and no challenges like I am finding in Ethos with this particular Radio. Helping a few friends out with their New X20 and their SR10. When we bind it to the X10S running OpenTX is works flawlessly, when we bind it to the X20, can't get it to Self Check Mode.
> > Checked all the following:
> > Radio Channel Order set to AETR
> > Create New Model
> > Added 4 Free Mixes and output to Ch 9, 10, 11, 12
> > Ch 9 50% Offset and 50% Up and 50% Down
> > Calibrated and Enabled SxR Function from within Ethos Config App
> > Confirmed Ch 3 is Throttle at -100%
> > Tried Switch Delay Detect at 0,10,100ms
> > Tested Ch 12 with a 3-POS and 2-POS switch
> > All outputs are reporting on the correct channel and correct values
> > Any suggestions where else to look?
> > Thanks in advance :)
> 
> verify RF menu channel range: ch1-ch16

Yes confirmed, I edited the intial post to reflect that, thanks.

**Comment by pld74** [comment]
**Ok so I was able to replicate and test both non-successfully and repeated successful attempts.** 

**Long story short, Ch12 needs to be only outputting 0-100% (same as CH9). To program this in Ethos: CH 12 - 50% Offset, 50% Up, 50% Down**

Note in the manual how it only mentions CH 12 Down? Well to FrSKy 'Down' is +100% Signal Output. I wrote a programming guide long ago to the SxR series (previous 'S' versions) and it applies to the new stabilizing receivers in the same manor. 

**To test without changing any of your existing programming:** 

Confirm if your existing CH12 is outputting -100 to +100 signal output, try to flick (3x) the 3-POS switch from Mid (0%) to Down (+100%). Note that it will now always initiate self-check "Blue LED" repeatedly after the 3rd time. I was able to continously replicate a non-working Self Check and continously working Self Check. I left the middle detect settings at 100ms (default) and changed nothing else in the Radio. This also work in 1.0.11RC3.

Hope this helps everyone out here. 

The FrSky Manual needs to be updated to more clearly indicate this for both CH 9 and CH 12.

Cheers

**Comment by bsongis-frsky** [comment]
1) RF 16 channels
2) no delay on SW mid position

**Comment by i3dm** [comment]
> CH12 works for me 0% to +100% perfectly each and every time! I have confirmed this. Does not work for me -100% to +100% and No Switch Mid Delay.
> 
> I have reported this to a friend having trouble, lets see what happened in his. His challence sparked my own testing.

are you using a 3-position switch on ch12?

**Comment by pld74** [comment]
> > CH12 works for me 0% to +100% perfectly each and every time! I have confirmed this. Does not work for me -100% to +100% and No Switch Mid Delay.
> > I have reported this to a friend having trouble, lets see what happened in his. His challence sparked my own testing.
> 
> are you using a 3-position switch on ch12?

I tried 3-POS, no Dice. I tried 2-POS, -No Dice. I thought... in OpenTX Mid Switch Delay is 250ms so 0ms doesn't make sense as in OpenTX at 250ms it is completely ignoring the middle POS, so, I went back to the drawing board, tested 2 nights in a row and look in the manual carefuly. Yes it says 3-POS but only indicate Ch 12 Down however Ch 10 and Ch 11 Indicate Down and Up. So that got me thinking and I went this direction. As such it works flawlessly with Ch 12 only outputting 0% to 100% on my S6R, S8R and testing it on SR10 today. 

Attached is a programming guide that I published in 2017 for the OpenTX community to activate the flight modes on a 6-POS Dial. It worked on many individuals radios - perfectly all the time. Notice how Ch12 has a 50% Offset and 50% Travel in OpenTX - Hence my decision here to test CH12 in Ethos as such. Now works perfectly here as well in Ethos for me.

[S6R Programming Guide.xlsx](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7098286/S6R.Programming.Guide.xlsx)

**Comment by i3dm** [comment]
ch1-ch16
ch12 3-pos
switch delay 0
throttle -100%

i tested and confirmed working perfectly.

**Comment by pld74** [comment]
> ch1-ch16
> ch12 3-pos (-100,0,+100)
> switch delay 0
> throttle -100%
> 
> i tested and confirmed working perfectly.

Doesn't work for me.

**Comment by i3dm** [comment]
you are definitely missing something then. hard to say what. can you upload a video showing the above config not working?

**Comment by pld74** [comment]
> you are definitely missing something then. hard to say what. can you upload a video showing the above config not working?

So ran a quick test before I head off to work with 0ms Delay and 3-POS.:

If i flick slowly it works sometimes but if I flick fast it does not. Hence why I think CH12 needs to SEE the MID Position. After all, it's why we are making the Middle Detect 0ms. Right?

My Logic is this: By setting the Middle Delay to 0ms we are ensuring that the middle positition is even for a moment detected by Ethos and it sends 0% Value to the RX to initialize Self-Check. So, I went in the direction to use CH12 at 0% and it works, regardless if I flick slow or fast. Next I tested Output @ -100% doesn't do anything on CH12 but +100% is the Emergency Level Mode. So 0% to 100% it is.

The 0ms edit in Ethos doesn't make sense because in OpenTX that value is default something like 250ms or 300ms. With my suggestion, The entire Ethos Community can use Ethos in its Default settings and wether the Middle Detecet is at 0ms, 100ms (default) or 200ms (maximum value for Ethos) and it works perfectly.

PS - What we really need here is the writer of the software code for the SxR and SRx Receiver series and get their feedback on what signal CH12 wants to see in order for it to work at it was intented. 

PSS - I am testing with 3 more X20 Radios and 3 more SxR and SRx RXs. I will only report back if any non-working results based on Default Ethos Settings and my suggested CH12 Value of 0% to +100% doesn't work.

Cheers

**Comment by Hobby4life** [comment]
To be honest. I have never used stick calibration mode. lolz.. 
Just standard configuration of directions and gains, and go!
Not sure what this "stick calibration / selfcheck" actually adds to all this.
I sure gues it fine tunes everything for other modes besides standard stabilisation.
But thats the only mode I use anyway.

**Comment by pld74** [comment]
> To be honest. I have never used stick calibration mode. lolz..
> Just standard configuration of directions and gains, and go!
> Not sure what this "stick calibration / selfcheck" actually adds to all this.
> I sure gues it fine tunes everything for other modes besides standard stabilisation.
> But thats the only mode I use anyway.

As stated in the manual: In the end, Self Check will save the zero points of the gyro, auto level angle, gimbal neutral position and servo channel limits.
