### ISSUE TITLE
Logic Switches delta funktion ??

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#514]
Maybe I don't undestand this funktion so well but in OTX it behaves different. 
I want to have a ESC consumption massage every 100mAh - doesn't work. 
There is a check intervall - but max 500 ms - in that time I have no 100mAh difference - so the switch will never be active. For my understandig it would be more usefull if the first 100 mAh difference  is reached, the switch is active and the monitoring starts again. 
Or is there some trick to realize my wishes?

**Comment by Cipta-de** [comment]
Sorry but I haven't seen that my request is similar to
" Logical switch | ∆ | > X function #463

**Comment by dwheel** [comment]
I agree. There are many uses for the delta function that require a longer check interval. Please offer an option that allows infinite time for this interval.

**Comment by bsongis-frsky** [comment]
Has been fixed in 1.0.10
