### ISSUE TITLE
Request: Variometer play value altitude in alternative units of measure

### ISSUE THREAD

**Issue by darkernoise** [FrSkyRC/ETHOS-Feedback-Community#516]
As of 1.0.9, the Play Value of telemetry Altitude only will speak in meters. In the US, we have a new legal rule from the FCC limiting the flight ceiling to 400 feet.  Thus, it would be really fantastic if we could have altitude alternative units of measure, such as Feet.

**Comment by MIKE-DAILEY** [comment]
The Vario Altitude it does that now.  Edit the Vario Altitude to Feet.  In Special Function program a switch for Play Value Altitude.  If you want you can program a logic switch to monitor Altitude and then use the Logic Switch in Special Function to Play Value.

**Comment by miksterr** [comment]
It is 122 Meters - easy really.

**Comment by darkernoise** [comment]
Thanks for the feedback.  I do see now that the telemetry value can be edited to choose alternative units.  Though, Mike-Daily, please give users a chance to respond before you close their tickets.
