### ISSUE TITLE
Voltage Range bug & clear entry values request

### ISSUE THREAD

**Issue by darkernoise** [FrSkyRC/ETHOS-Feedback-Community#517]
A model created in 1.0.8 had a voltage range defined as 0-14v.  After upgrading to 1.0.9, the upper range is now a crazy large number that is so large it runs off the screen.  I ran the dial to try and turn down this upper range, but the number is so large, this is impossible.  

1. Please correct this voltage range conversion issue (did you change byte size?)
2. Please add a "clear" function to the entry boxes, such as voltage upper range.

**Comment by darkernoise** [comment]
Just to add more information, I see multiple Telemetry range values now corrupted and with unreasonable values.  Something definitely changed between 1.0.8 and 1.0.9.  Either way, we need a clear option to correct these values.

**Comment by bsongis-frsky** [comment]
I am not sure that your limits in 1.0.8 were good (I am even sure they were wrong)!
Please rediscover your sensors to be sure they are good now
