### ISSUE TITLE
download and upload typical model setups and switch assignments for f3b gliders and heli models

### ISSUE THREAD

**Issue by e-trashy** [FrSkyRC/ETHOS-Feedback-Community#519]
I am relatively new to frsky, ethos and or open Tx. Am converting most radio's and my gliders and e-Heli's to the Frsky telemetry system and Ethos. Are there any templates or recommended setup for typical switch assignmnets, model setups with all the most typical mixers for flap to elevator, crow, flight modes, dual rates for full house f3b gliders and e-heli models? Where can these be shared ? or is there any written documentation on this. I seem not to be able to find much on this to get me kick started.

**Comment by jreis1** [comment]
A model setup is almost a personal thing, so i believe you will not find anything preset or even available online :(

**Comment by jbesse262** [comment]
How is this an Ethos issue?

**Comment by higheronnitro** [comment]
The inability to "share" models between ethos is an ethos issue. I don’t see any XXmodel.bin files here or on RC groups or on the aloft forum. Is it technically able to be done and do you know which model is the one you want to share? I have models 02 03 04 06 and have no idea which is which. I am about to wipe all my XXmodel.bin files and see if I can renumber them and then re add. If you can’t make a copy of the models and re add them to the SD card this is a real problem (effectively the SD card becomes the weak link in the whole radio)

**Comment by jbesse262** [comment]
I have had no problem copying models from an X12 to an X20. I still font see how this is an issue with Ethos?

**Comment by higheronnitro** [comment]
Cool there you go e-trashy the answer is yes you can convert your all your current models and setups you just need to go buy a x12 first ( or maybe zip your otx files and send them to a friend with a x12 for conversion ).. I have checked and yes you can copy renumber and paste XXmodel.bin files so it is only a matter of time before someone produces more advanced templates. 
Mike has done one from scratch and when he is happly he will likely release it
https://www.rcgroups.com/forums/showpost.php?p=47214027&postcount=7557
Note his comment 
The Ethos version has 84 mixes v. 55 in the original. Much of the difference is due to the use of VAR mixes to replace the GVARs. Nevertheless, there was a lot of data entry involved (it took me 3 days on and off), and the jog dial on my X20 is starting to feel worryingly loose.  
Maybe he didnt have an X12 at hand to convert the original or the jog wheel was too tight when new..

**Comment by jbesse262** [comment]
> Cool there you go e-trashy the answer is yes you can convert your all your current models and setups you just need to go buy a x12 first ( or maybe zip your otx files and send them to a friend with a x12 for conversion ).. I have checked and yes you can copy renumber and paste XXmodel.bin files so it is only a matter of time before someone produces more advanced templates.
> Mike has done one from scratch and when he is happly he will likely release it
> https://www.rcgroups.com/forums/showpost.php?p=47214027&postcount=7557
> Note his comment
> The Ethos version has 84 mixes v. 55 in the original. Much of the difference is due to the use of VAR mixes to replace the GVARs. Nevertheless, there was a lot of data entry involved (it took me 3 days on and off), and the jog dial on my X20 is starting to feel worryingly loose.
> Maybe he didnt have an X12 at hand to convert the original or the jog wheel was too tight when new..

Hey, GFY! Just because the op cant program his own radio and admittantly has little experience w/ OTX, Frsky and ETHos, doesnt make it an ETHos issue. Period. Dousche

**Comment by e-trashy** [comment]
Thanks for all your input, much appreciated and indeed not an Ethos issue.

**Comment by seilfly** [comment]
A program similar to "Companion" would have been great !

**Comment by mawzthefinn** [comment]
Mike Shellim has posted several excellent templates at RC-Soar.com and others are doing so as well. As ETHOS grows in user base more such templates are being added. I'm closing this off as it is really completed now.

@seilfly - Take a look at the latest ETHOS Suite, while model editing is not available, there is a tease of features to come there.

**Comment by e-trashy** [comment]
Good for me. thxWP MobileOn Nov 25, 2022, at 9:44 PM, mawzthefinn ***@***.***> wrote:﻿
Mike Shellim has posted several excellent templates at RC-Soar.com and others are doing so as well. As ETHOS grows in user base more such templates are being added. I'm closing this off as it is really completed now.
@seilfly - Take a look at the latest ETHOS Suite, while model editing is not available, there is a tease of features to come there.
