### ISSUE TITLE
Request: Timer Active Condition on Logic Switches

### ISSUE THREAD

**Issue by darkernoise** [FrSkyRC/ETHOS-Feedback-Community#521]
Requesting adding the feature to allow Timer Active Condition to be tied to a logic switch.  This will allow setting up functions to only run the timer under specific conditions, such as when throttle cut is disengaged, or while in a specific flight mode.  Today, switch position is there as an option, but just not Logic Switches.

**Comment by jreis1** [comment]
Uhm… this feature might have been lost from 1.0.8 and 1.0.9 then. I already had logic switches to activate a timer. Namely, to count the time I was above a given height threshold.

**Comment by MIKE-DAILEY** [comment]
It is active in 1.0.9.?

**Comment by darkernoise** [comment]
I have 1.0.9 right in front of me.  There is no Logic Switch Option.  If this was there previously, it is not now.  Please re-open this ticket.

**Comment by MIKE-DAILEY** [comment]
I have it with with 1.0.9.  Logic Switch used in Timer. 

![screenshot-2021-06-19-71538](https://user-images.githubusercontent.com/11791852/122658129-9fd6e800-d137-11eb-88a8-e929d7fd4954.jpg)

**Comment by darkernoise** [comment]
Mike, then something broke in 1.0.9.  I invite you to please edit any Timer and select Active condition.  You will see the following options: 

- ----
- Always On
- Throttle absolute
- Throttle percentage
- Throttle Trigger
- Switch Position

Please re-open this ticket.  It is really rude to close tickets without giving the user who submitted it a chance to respond.

**Comment by MIKE-DAILEY** [comment]
Scroll the popup down one more line.  


![WP_20210619_20_01_25_Pro](https://user-images.githubusercontent.com/11791852/122658358-3e644880-d13a-11eb-92f9-c0bfb9483730.jpg)

**Comment by darkernoise** [comment]
My version of 1.0.9 does not that.   I have the official final 1.0.9. Are you sure you do?

**Comment by MIKE-DAILEY** [comment]
Yes I do and it is working on my X20 and X20S.  1.0.9. from here https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release%2F1.0.9

**Comment by darkernoise** [comment]
I figured out the issue.  I was using a model which did not have Logic Switches setup yet.  It seems that the Logic Switch option does not display until a logic switch has been configured.  Thus, user error. Thanks for the help in figuring this out.
