### ISSUE TITLE
Text cut off in trims menu

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#522]
X10s isrm
Ethos 1.0.9
Text should read 
independent trim per flight mode,
But it reads
Independent trim per flight moc

I can't upload pic it won't let me

Thanks 
Scott

**Comment by WismyYao** [comment]
Which language are you using?  I see it's ok with English

**Comment by Hobby4life** [comment]
![2021-06-21 07_41_56-Ethos Simulator](https://user-images.githubusercontent.com/55426642/122712453-3dc7d100-d264-11eb-9457-dad116b19d5c.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/122761517-9fa42d00-d29c-11eb-915c-81e4b26840ed.png)
