### ISSUE TITLE
Request: Function Switch type selection X20

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#523]
I would like to request a Type selection option for the 6 Function switches.

Seperate Configurable Function switches.

- FSW1: Momentary / Toggle / Colaborate (Persistance)
- FSW2: Momentary / Toggle / Colaborate (Persistance)
- FSW3: Momentary / Toggle / Colaborate (Persistance)
- FSW4: Momentary / Toggle / Colaborate (Persistance)
- FSW5: Momentary / Toggle / Colaborate (Persistance)
- FSW6: Momentary / Toggle / Colaborate (Persistance)

This way, it will fullfill everyones needs.

**Comment by MrD-RC** [comment]
Similarities to https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/153

**Comment by bsongis-frsky** [comment]
Good idea

**Comment by mherke** [comment]
Very good idea. This would make the x20 very usefull for multi function modells like ship modells.

**Comment by bsongis-frsky** [comment]
Duplicate of #153
