### ISSUE TITLE
Please add Override function

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#525]
Hello,

Please add "Override Channel XX" special function, it is a very important feature.
Examples:
- deploy landing gear when a sensor alerts of pressure fault.
- override flight modes to go to RTH when a switch is pressed.
and many more cases.
please add this feature to ETHOS.
thanks.

**Comment by bsongis-frsky** [comment]
No. This should be done inside the mixer, not inside functions.

**Comment by i3dm** [comment]
perhaps add this as a simplified "replace" called "override" in the mixer (simply send a channel to predetermined value)?

**Comment by loetefix** [comment]
Please, why put too much things in ethos that can be already done in an other way.

**Comment by i3dm** [comment]
> Please, why put too much things in ethos that can be already done in an other way.

because i want them to be done in a simple way.
i already had several friends complain about how difficult it is to do an override function.

the purpose of ethos to be powerful and user friendly.

**Comment by bsongis-frsky** [comment]
The mixer goes BEFORE the outputs. If I add a "Override" function inside the mixer, then you will go through the limits, invert, channel slow etc. and it is normal.

I will propose something else

**Comment by i3dm** [comment]
we need sonething that wont have slow down ir other limitations, and preferabely in my opinion not enclised in outputa limits too. opentx solved this very nicely with override. it is a very useful and powerful function missing in ethos.

**Comment by bsongis-frsky** [comment]
I am not sure that hiding mixer functions in special function can be called "nice" ;) But I have understood your expectation and I will try to find something better

**Comment by i3dm** [comment]
> I am not sure that hiding mixer functions in special functions can be "nice" ;) But I have understood your expectation and I will try to find something better

ok.
please reopen the issue as an enhancement and report back your idea for review if possible.
