### ISSUE TITLE
PPM period too long with 16 channels, also only 8/16 ch allowed

### ISSUE THREAD

**Issue by MikeBland** [FrSkyRC/ETHOS-Feedback-Community#526]
Configure the external module for PPM, select 8 channels, the period is 22.5mS.
With extended limits each pulse has a maximum width of 2.14mS.
8 channels therefore need 8*2.14 = 17.12mS, leaving 5.38mS for the sync. pulse.
If 16 channels is selected the period is currently 45mS.
16 channels meed 16*2.14 = 34.24mS. This leaves 10.76mS for the sync. pulse.
Since only 5mS is needed for the sync pulse (maybe only 4mS), the period could be reduced to 39.5mS, improving the latency.

It is only possible to select 8 or 16 channels for PPM. Would it be possible to allow for other channel counts?
As low as 4 and up to 16 in steps of 1 or 2 would be good, adjusting the period as required.

Mike

-----

- [ ] Change the period to something more dynamic, depending on the channels count
- [ ] Allow 4 to 16 channels

**Comment by bsongis-frsky** [comment]
In 1.0.10, frame size = 5.5mS + 2.125mS * channelsCount

![image](https://user-images.githubusercontent.com/50834778/122783325-c15bdf00-d2b1-11eb-8c45-797495baf495.png)
