### ISSUE TITLE
Feature request: independant trim for flight mode in each channel

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#527]
X20 on ethos 1.09

Hello i am using a virtual channel to modify value like differential aileron or camber with a trim in a F3K model.
 I use a trim mixer  to adjust the virtual channel but actually it is not possible to have a different trim in each flight mode. Imust create a new mixer and assignate it to only one flight mode.

It will be useful and simple to have the option for independant trim for every channel not only with Aileron, profondeur, rudder, gaz.

Thanks.

**Comment by loetefix** [comment]
I have already suggested here https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/216

**Comment by MrD-RC** [comment]
Also here https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/215

**Comment by loetefix** [comment]
> Also here #215

But this only for the 4 'normal' trims and not for the trim-mixer. Or am i wrong?

**Comment by mawzthefinn** [comment]
As noted above this is a duplicate request. Closing off in favour of #216
