### ISSUE TITLE
digital switches

### ISSUE THREAD

**Issue by Peterbilt84** [FrSkyRC/ETHOS-Feedback-Community#529]
Create icons on the home screen to be able to use them for digital switches.
Actuation of the switches via the touchscreen.

**Comment by IJK-CZ** [comment]
Not usable for X10 /X12 without touchscreen:-(

**Comment by Peterbilt84** [comment]
but on the X20 it would be usable

**Comment by bsongis-frsky** [comment]
Please explain more, I don't get what you mean

**Comment by loetefix** [comment]
I think he means "virtual" switches on the Touchscreen. May be as a widget.

**Comment by Peterbilt84** [comment]
Ioetefix is right.
Icons that can be created via widget would be ideal.
You can use them to switch lights on and off, for example.

**Comment by hrenz** [comment]
there could be 9 or 18 "Widget Virtual Switches"  with free text per screen
like early days with an Multiswitch Modul or Navimodul
and you can do it with touch at X20 or with roller+enter at X10
Switch on, Switch off Funktion

**Comment by AlwinHaas** [comment]
Es wäre Super um das HF Modul zu aktivieren.
Bzw. Dieses über den Digitalen Schalter aus zu schalten.

**Comment by Peterbilt84** [comment]
can now be created through the Lua support the digital switches?

**Comment by mawzthefinn** [comment]
#1411 is the same request and assigned with a milestone. Closing this off as a duplicate despite being the original request for this.
