### ISSUE TITLE
R9pw sensor

### ISSUE THREAD

**Issue by MeniLew** [FrSkyRC/ETHOS-Feedback-Community#530]
In Horus used with r9 when you would set 1000mw the transmitter would skip the transmission power from the lowest to 1000mw. 
 I could tell what power it was transmitting because there was an r9pw sensor that would update on that. 
 It is not clear to me if using x20 it skips between transmission powers because the sensor does not exist.  If it does not skip powers it is really important to fix it.
  If he does skip then i ask to add the sensor to indicat.  Thanks

I use x20s with Athos version 1.0.9 fcc

**Comment by bsongis-frsky** [comment]
Not an Ethos issue

**Comment by MeniLew** [comment]
> Not an Ethos issue

So who should I contact?

**Comment by Adelaxie** [comment]
So to display what the power it is when under 1w adaptive mode,right ?Will discuss on this if it canbe done.

**Comment by Adelaxie** [comment]
like #379 ?

**Comment by MeniLew** [comment]
> So to display what the power it is when under 1w adaptive mode,right ?Will discuss on this.

Yes, both to have a dynamic state at all and to be able to show how powerful it is.  There is never a need to turn on 1w at the beginning of the flight, only when you are very far away, so it is best that it is pre-made dynamically and saves radiation and waste of energy.  Thanks

**Comment by mawzthefinn** [comment]
Yes, power reporting from the module when in an adaptive setting would be a nice addition

**Comment by mawzthefinn** [comment]
This has been added as a sensor for the TANDEM radios

**Comment by i3dm** [comment]
> This has been added as a sensor for the TANDEM radios

To which version? Rf firmware?

**Comment by mawzthefinn** [comment]
The latest RF firmware for TD ISRM's and TD ISRM Pro's.
