### ISSUE TITLE
Instant trim

### ISSUE THREAD

**Issue by MeniLew** [FrSkyRC/ETHOS-Feedback-Community#532]
Is it possible to add an "instant trim" function to the "Special Functions" menu? 
 This function determines the position of all trims except the throttle at the push of a button while flying, according to the position of the sticks while pressing the button.  Thanks

I use x20s with Athos version 1.0.9 fcc

**Comment by Hobby4life** [comment]
Already mentioned: #513

**Comment by MeniLew** [comment]
I could not find an answer there

**Comment by MeniLew** [comment]
> Already mentioned: #513



> Already mentioned: #513

I could not find an answer there

**Comment by bsongis-frsky** [comment]
Duplicate of #295 
Don't open too many issues for the same request, it takes time to sort
