### ISSUE TITLE
Update French Translation

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#533]
Bonsoir,

Some update.
Test with Description

[fr.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6703623/fr.txt)

@+

**Comment by aeroplanebelg** [comment]
bon travail ne pas oublier ... sticky et haptic

**Comment by bsongis-frsky** [comment]
Je viens de mettre à jour le simu dans 1.0.10 RC2
Il reste un peu de travail ;)
