### ISSUE TITLE
Delay function

### ISSUE THREAD

**Issue by MeniLew** [FrSkyRC/ETHOS-Feedback-Community#534]
Hello, The "Delay" function does not exist in Mixer or Output.  In order to make a delay you need to produce another mix with a logical switch.  It will help a lot if you add the option in Output or Mixer. 
 Thanks

**Comment by MIKE-DAILEY** [comment]
Delay is a input function usually related to a switch or some type of input and thus not a Mixer or Output function.  For a input delay to the Mixer use a Logic Switch delay and then that Logic Switch as a Mixer input.

**Comment by MeniLew** [comment]
> Delay is a input function usually related to a switch or some type of input and thus not a Mixer or Output function. For a input delay to the Mixer use a Logic Switch delay and then that Logic Switch as a Mixer input.

I use Delay a lot in output, for example in the case of folding wheels and doors.  A delay should be made on closing the door until the wheel folds.  True, this is possible through a logical switch but it's a long and annoying way to do it.

**Comment by MIKE-DAILEY** [comment]
Gear doors are quite easy with ETHOS.  Here is an example https://www.rcgroups.com/forums/showpost.php?p=46708519&postcount=3621

**Comment by MeniLew** [comment]
> Gear doors are quite easy with ETHOS. Here is an example https://www.rcgroups.com/forums/showpost.php?p=46708519&postcount=3621

This is a great example of what Delay needs in Output.  5 unnecessary steps when you can do everything in one second

**Comment by MeniLew** [comment]
> Gear doors are quite easy with ETHOS. Here is an example https://www.rcgroups.com/forums/showpost.php?p=46708519&postcount=3621

This is a great example why you need a delay in the output.  5 unnecessary steps when you can do everything in one second

**Comment by mawzthefinn** [comment]
After discussion with @bsongis activation logic like Delay will remain consistently in Logic Switches, while mixer functions remain in the mixer.
