### ISSUE TITLE
Bluetooth or USB-C keyboard support

### ISSUE THREAD

**Issue by higheronnitro** [FrSkyRC/ETHOS-Feedback-Community#535]
Just thinking out aloud what is the chance of USB-C or Bluetooth support for an external keyboard? For those of us with 65 logical switches, 40 Special functions, 6 curves per surface and 5 flight modes to enter? It would be nice to have a label on each to help with on the fly changes but too slack to enter them with the scroll wheel...

**Comment by i3dm** [comment]
an external keyboard does not make a lot of sense to me.
an on screen touch keyboard does :)

**Comment by OldGazer** [comment]
There is no need to bloat the firmware with support for an external keyboard.  A "Companion style" software solution is in the works.

Y'All just need to be patient.

**Comment by Hobby4life** [comment]
> There is no need to bloat the firmware with support for an external keyboard. A "Companion style" software solution is in the works.
> 
> Y'All just need to be patient.

I totally agree, the idea is nice,, but a piece of PC/Mac software will do more than fine..

**Comment by poge-st** [comment]
bluetooth keyboard / usb-c keyboard is overkill - guess I wouldn't use it - but totally agree to a virtual keyboard ! 
There is already an open issue for a virtual keyboard ;) #189 
I hope that this is implemented - i would look forward for this a  lot :)

**Comment by higheronnitro** [comment]
I agree what is really needed is a "companion"... I just wanted something in the meantime...
I will leave all my planes bound to my QX7 till then so I can keep flying till then.
