### ISSUE TITLE
BUG:  Rx redundancy config not as described.  Wiped out pin assignments. 

### ISSUE THREAD

**Issue by Droptank** [FrSkyRC/ETHOS-Feedback-Community#536]
Ethos 1.09
Archer SR6 2.17
Redundant rx is Archer RS 2.18

SETUP as per ethos manual rev 10 page 57 item 9.  Indicates BOTH receivers will be listed on the same line RX1 or RX2 etc… this makes sense as a redundancy setup but only the second receiver bound appears.  In my case the SR6 is replaced by RS on the line RX1.  Same is shown in the picture in Manual with R9mini in the example.  In my case the SR6 is still functioning and moving servos.  However when selecting the SET button for receiver options I sometimes get options for the SR6 and sometimes for the RS, and sometimes receiver doesn’t answer at all.  At one point  when in the receiver options for the RS I selected Telemetry off and the motor started!  Investigating further I got into the SR6 options (by trying a few times) and saw all the 6 pins assignments replaced with “???”  That’s why the motor started on its own.  The Chanel assignments had been wiped out by selecting telemetry off for the RS.  

Also when going to Device config for the SR6 it is slow to populate fields but still functions.  

IDEALLY both receivers in redundancy setup would in fact appear on the same line proving they are both functioning as one virtual receiver.  Also we should still be able to select which of the two receivers we want to access in the SET button for receiver options.

**Comment by Droptank** [comment]
Also want to add that I was getting intermittent telemetry on and off warnings.

**Comment by Droptank** [comment]
![0A6B9ECF-FD6A-4BDB-85E2-A481FB401552](https://user-images.githubusercontent.com/85647553/123351566-5d444f80-d52b-11eb-95d5-70fbd0d949dd.jpeg)
![A248C83E-4307-4674-A515-3F870708BA5E](https://user-images.githubusercontent.com/85647553/123351569-5f0e1300-d52b-11eb-8f07-b1a310c9b3a3.jpeg)

first pic shows the “???” But I had already remapped most of them.  They were all “???”

second pic shows just the RS shown even though both SR6 and RS are bound and SR6 is moving servos and stabilizing.

**Comment by MIKE-DAILEY** [comment]
Not sure I understand everything you are doing but if you are using two ACCESS receivers one needs to be bound to the RX1 position and the other to RX2 position.  If not you will have a mess.

**Comment by Droptank** [comment]
> Not sure I understand everything you are doing but if you are using two ACCESS receivers one needs to be bound to the RX1 position and the other to RX2 position. If not you will have a mess.

I thought that initially as well however the manual indicates that what you describe is for trio control and splitting channels among several receivers.  It goes on to state specifically 

“9. Both receivers will now be listed against for RX1 (or whichever receiver you 
are making redundant).” 

this is all after describing a specific procedure to bind the main rx and then the redundant rx on the same line.  Trio control is described differently (and simply) as rx 1,2 etc. I have done it as you described with a R9MX as redundant and everything seemed to be working but then I saw this other procedure in the manual so I figured I was doing it “wrong”.  So is trio control intended to be the method of redundant receivers with Access?  Is so then I think the Ethos manual might need changing to explain this.

Keep in mind I’m new to Frsky and Ethos this not drawing on any old knowledge of how things are done so I tried to follow the manual.

Thanks.

**Comment by MIKE-DAILEY** [comment]
I don't know which manual you are referring to but if you plan on using the SET/OPTIONS feature with both receivers powered one needs to be RX1 and the other RX2.

**Comment by Droptank** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/main/X20%20and%20Ethos%20User%20Manual_1.0.5_rev11.pdf

This one

**Comment by MIKE-DAILEY** [comment]
As I said before if you plan on using the SET/OPTIONS feature with both receivers powered on one needs to be RX1 and the other RX2.  

I've provided the solution to your SET/OPTIONS problem and this is really not ETHOS related so I'm closing this issue.
