### ISSUE TITLE
Receiver firmware upgrade from ACCST to ACCESS not possible with ETHOS

### ISSUE THREAD

**Issue by Testname84** [FrSkyRC/ETHOS-Feedback-Community#538]
Regarding to the fact that ACCST receiver like the G-RX6/8 only assist OTA update when already running with ACCESS there is a option needed where I can still choose "external device" to install the firmware by cable.

Issue occurred on X12S with Ethos 1.0.9

**Comment by jfint** [comment]
this works in ethos, I did two G-rx6 yesterday from ACCST to ACCES with 1.0.9.  when selecting the file "Update external device" was the top option.

**Comment by Testname84** [comment]
that is curious. I can't see this option.

**Comment by i3dm** [comment]
i also used "flash external device" on X20S successfully before

**Comment by eijowk** [comment]
I have exactly the same issue on my X12S on 1.0.9
There is another issue raised with the same topic: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/54
I guess that this is specific for X12S and maybe X10?

**Comment by Nicholas-Luoyi** [comment]
Please notice that G-RX6/8 doesn't support OTA update. Thanks for your feedback.

**Comment by bsongis-frsky** [comment]
And X12S doesn't have an external S.PORT connector

**Comment by bsongis-frsky** [comment]
You will have to flash via "Flash External Module", but take care to the cable, I know one person who burnt his X12S, he didn't take care to the polarity.

**Comment by Testname84** [comment]
bsongis, I connected the cable correctly, but I don't have the option in ethos on X12S to flash external device...

**Comment by bsongis-frsky** [comment]
I said "Flash External Module"

**Comment by Testname84** [comment]
you don't have a option on x12s which says "flash external module" when selecting the file for flash.

**Comment by bsongis-frsky** [comment]
What is the file you are trying to flash?

**Comment by eijowk** [comment]
This is what it looks like at my X12S when trying to update R-XSR to ACCESS.
![IMG_20210629_204901](https://user-images.githubusercontent.com/12411100/123851503-8abe3e00-d91b-11eb-9820-9f2e6c4ee02d.jpg)

**Comment by loetefix** [comment]
Try to rename the ending from .frsk to frk.

**Comment by Testname84** [comment]
> This is what it looks like at my X12S when trying to update R-XSR to ACCESS.
> ![IMG_20210629_204901](https://user-images.githubusercontent.com/12411100/123851503-8abe3e00-d91b-11eb-9820-9f2e6c4ee02d.jpg)

same here

**Comment by loetefix** [comment]
> > This is what it looks like at my X12S when trying to update R-XSR to ACCESS.
> > ![IMG_20210629_204901](https://user-images.githubusercontent.com/12411100/123851503-8abe3e00-d91b-11eb-9820-9f2e6c4ee02d.jpg)
> 
> same here

Did you try againd with raname the extension to .frk

**Comment by eijowk** [comment]
I have already tried to rename the file to frk, and it sort of works. The "Flash to module" alternative is there and the Flash procedure seems to work without errors. However something was strange - I was not able to register and bind the ACCESS flashed R XSR. When flashing ACCST 2.1 everything worked again. Is there something that is different with frsk and frk format and that the R XSR was flashed wrong when changing the ending to frk?

However this is to my understanding a bug in X12S since the "Flash to module" alternative seems to be available for frsk files at X20.

**Comment by bsongis-frsky** [comment]
Right. I just added an option "Flash external device" to X12S. Obviously it will use the external module pins to do so.

**Comment by Testname84** [comment]
Great thanks, is it available within the next version?

**Comment by MIKE-DAILEY** [comment]
> Great thanks, is it available within the next version?

Released now https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release/1.0.10-candidate1

**Comment by Testname84** [comment]
Nice, obviously it works.
