### ISSUE TITLE
bluetooth (audio) module in X20?

### ISSUE THREAD

**Issue by seilfly** [FrSkyRC/ETHOS-Feedback-Community#539]
Hi, has anyone here done any research on mounting a Bluetooth module in the X20? 
There is free space on the motherboard

**Comment by jbesse262** [comment]
Not an ETHos issue.

**Comment by onki69** [comment]
I did that upgrade on my X20.
You need to solder the module and flash the X20s firmware.
https://onki.de/uebermich/bauberichte/362-frsky-x20-und-der-bt-faktor

**Comment by bsongis-frsky** [comment]
There will be an option in System / Hardware to enable the board installed as an option

**Comment by EngelMT** [comment]
@bsongis-frsky Please also consider retrofitting the X20R and X20RS in ETHOS.

**Comment by bsongis** [comment]
Done already
