### ISSUE TITLE
flashing access FW not possible on x12s

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#54]
When trying to flash access FW on receiver, there is no option to flash it, just copy, rename and delete. but when selecting accst fw it shows flash external device. It looks like it only reads files with *.frk
Horus x12s ethos V1.0.1

**Comment by DaySpeed955i** [comment]
X12S ETHOS v1.0.1
I have no problems to flash, this is a SR10 Pro

![Flash-OTA](https://user-images.githubusercontent.com/62478798/114255679-c2ec5b00-9982-11eb-80f3-8911f2efe05f.jpg)
![Flash-OTA-OK](https://user-images.githubusercontent.com/62478798/114255680-c384f180-9982-11eb-9f11-3283c2fb49d3.jpg)

**Comment by KAD370** [comment]
I couldn’t flash g-rx6 with cable

**Comment by eijowk** [comment]
I have exactly the same issue. X12S with ISRM 1.09 - Can't flash Access with cable - Only the OTA Alternative in the menu "Flash External Device" is not there when the file has the ending "frsk". In my case an R-XSR which I want to change to ACCESS.
Still not solved in 1.09

**Comment by bsongis-frsky** [comment]
It has been fixed since. You will have to flash from the external module bay. Take care to the wiring as it's very easy to burn your radio if it is done wrong.
