### ISSUE TITLE
Ethos limitation ? Feature request: Add "slow up/down" to Mixer inputs 

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#540]
**Problem description:** 

I've a Decathlon with flaps, and I want to program a "normal flap mode" and an "extended ailerons mode" for acrobatics, with the following behavior: 

**normal flap mode:** flaps set to 0º,  30º and 45º,  with slow up and down movement of 1 second, using SD switch.  
Straight forward operation: In Mixer menu, add a flap mixer, set SD as input, select flaps servo channels as output. In the Output menu, add slow up and slow down of 1 second, to each individual flap servo. 
This is implemented and working as expected. 

**extended Aileron mode:** flaps follow the same movement as the ailerons.  Using SC switch, I'll deactivate the normal flap mode and activate the extended mode. The SC switch will lose its functionality. 
This is also easy to do:  In mixer, add a Free Mix, set the active condition to "SCdown" (SC position to activate this mode), select Ailerons as Source, select the flaps channels as outputs. 

To avoid both modes working at the same time, in flap mixer line, I have set the active condition to "!SCdown". 
This is working as intended and the issue here is not the programming. However:

**Issue:**
As a "Slow Up" and "Slow Down" have been set to each flap output (in the Output menu), in Extended Aileron mode,  the flaps will not follow the movement of the Ailerons. They will always be delayed by the amount of time set in Slow Up/Down. 
Of course, this will work perfectly if I set the slow down/up to "0". 

Is there any work around I'm not seeing here? or maybe a software limitation?
I believe this would be solved by adding "slow up/down" to Mixer inputs

**Comment by AndyH56** [comment]
I had a similar problem. 
 
My solution was to use a free mix to control the flaps - this has a slow up / down function.  do not add a slow up /  down to the flap outputs.  You can then use the extended aileron mode as normal. 

I think the flap mixer should include a slow up / down function as this is a common requirement for flaps.

**Comment by jreis1** [comment]
> I had a similar problem.
> 
> My solution was to use a free mix to control the flaps - this has a slow up / down function. do not add a slow up / down to the flap outputs. You can then use the extended aileron mode as normal.
> 
> I think the flap mixer should include a slow up / down function as this is a common requirement for flaps.

Yup that is right ! I found it now! It is a limitation of the "Flaps" mix which can be worked around by using "Free Mix". 
I also thing **"Flaps mix" must be improved to add  Slow Up/Down** as this is a common feature for flaps.

**Comment by Hobby4life** [comment]
I agree, in **all** mixers you should have:

- Delay up/down
- Speed up/down

In output there must be only basic channel configuration such as subtrim/travel/reverse nothing more.

**Comment by johnjoeallen** [comment]
I'm using a free mix for my flaps with source as MAX, and weight set appropriately. The slow down works fine but when I add slow up the aileron goes full down before moving to the correct position.

**Comment by danielcaceres1991** [comment]
> I'm using a free mix for my flaps with source as MAX, and weight set appropriately. The slow down works fine but when I add slow up the aileron goes full down before moving to the correct position.

Did you figure out how to solve this issue? I'm running into a similar problem

**Comment by johnjoeallen** [comment]
Updates firmware fixes it

--
John Allen
7 Hunters Leap
Leamore Upper
Newcastle via Greystones
Co. Wicklow
A63 K032
Ireland

**Comment by mawzthefinn** [comment]
This was resolved by the addition of slow up/down to the Flaps mixer.

**Comment by mawzthefinn** [comment]
Delay, like other activation logic, is in the Logic Switches.

This is a deliberate choice to ensure that activation/deactivation logic is always Logic Switches, and mixers are dedicated to mixing.
