### ISSUE TITLE
x20s os 1.0.9 bug in telemetry

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#541]
Hello, in ethos 1.0.9 x20s, inter logic .... lsw .. the value of x is limited to 100m and the alti value read is not correct.
I had encountered the same problem with my x12s !! since solved by master Songis .... (I thought that the bugs corrected in the x12s were also corrected in the other radios running with the same version ... but no? pity)
I received my x20s today and I already fall on it. otherwise very nice radio ..... to be continued .... good luck for the hard work you have left. Thanks to the whole team @ +

**Comment by bsongis-frsky** [comment]
Did you check the limits of your sensor in its settings? If your sensor is configured with a limit of 100m I think it's normal that the LS doesn't allow you to go over it

**Comment by aeroplanebelg** [comment]
Mr Songis,Sorry it s me...in my excitation. (The new toy) hum......l have done a mistake.There is no bug. SorryGood after nonRobert Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : "Bertrand Songis @ FrSky" ***@***.***> Date : 25/06/21  22:20  (GMT+01:00) À : FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc : aeroplanebelg ***@***.***>, Author ***@***.***> Objet : Re: [FrSkyRC/ETHOS-Feedback-Community] x20s os 1.0.9 bug in telemetry
  (#541) 
Did you check the limits of your sensor in its settings? If your sensor is configured with a limit of 100m I think it's normal that the LS doesn't allow you to go over it
