### ISSUE TITLE
Feature request: Improve "Free mix" by adding "add Weigth/rates" option

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#542]
In Elevator / Ailerons / Rudder Mixer, we can set very easily several weights/rates (and also Curve) configurations, and attribute them to a switch position. This is a very good Ethos feature. 

I think this should also be possible in the "Free mix".
As it is at the moment, we can only set one Weight Up /Down, not several weights. 

On the limit, a new "Free mix" function with this functionality should be added to the templates. Basically I'm hereby requesting to have a similar mixing option to Ele / Ail / Rud, but with the "source" available (Note that the "source" of the Ele / Ail / Rud" is not available)

This would be very nice to have for one that would instantly like to set a 3 position switch, to command a servo with 3 physical positions. The alternative to this would be add a "FreeMIx", set a switch as a source and setting up a Curve.

**Comment by AndyH56** [comment]
I completely agree the standard mixes are good, but the free mix would be much better if it included weights/rates and curves as well.  I would also like to see the ability to define the input for all the existing mixers ( with a default of the 'normal' input) .

**Comment by hrenz** [comment]
weight alone ist incomplete für settiing Ranges 
you allways need both Weight and Offset, or a Curve

**Comment by Sigee3** [comment]
I dont know why ALL mixes cant have ALL options.
It would be easier to code and better for the user.

**Comment by mawzthefinn** [comment]
The 3 position switch with arbitrary positions is easiest to do today with a VAR mix.

Free Mixers can have multiple weights assigned if paired with a VAR Mix or two to provide the weights (you can have separate up/down weight sets this way).

Offset is also present in Free Mixes now

**Comment by mawzthefinn** [comment]
As of 1.5.0 you can now directly reference a VAR, without using a mixer channel slot. This allows multiple (and adjustable) settings for weight/rates to be added to a free mix easily
