### ISSUE TITLE
HELI Mix

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#543]
Big bug in the Heli mixer.

v1.09 X10S Express / X20S

My situation HR3 swash setup.
I have setup the heli mixer with the wizard setup.
All control directions are working fine.

Only when using Trim for Elevator and Aileron will trim the whole Cyclic Up or Down..
I can not Trim the Swashplate (Elevator)Forward/Backward or (Aileron)Sideways.

The problem lies in the Mixer itself.. The mixer is listening to the stick inputs, thats wrong the mixer must listen to a Cyclic mixer.
What we are missing is a Stick to Cyclic converter, then use these Converted outputs in the Mixer.

In the mixer you should have to select a sources like CYC1,2,3 not stick inputs.

In Opentx you have a special page for this conversion, where you assign inputs for the cyclic outputs that are further used in the mixer.
Also there is no Ring mixer available this way. impossible to do this now..

The heli mixer should be completly be reviewd.

I mark this as a really serious issue.

Attached is my model (X10S Express)

[model22.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6718616/model22.zip)

**Comment by Hobby4life** [comment]
Heli Mixer

- Swash type selection

Inputs:
- Lateral. control
- Long. control
- Collective

Output (virtual):
- CYC1
- CYC2
- CYC3

Additional:
- Swash Ring limit



The flow must be as followed:

Create a Pitch mixer, on the standard mixer page.
-Source is "Throttle stick"
-Output is "Collective input"  in the Heli mixer (somehow this must be connected)
This is the mixer where you add your pitch curve.

Create a Mixer for Cyc1 servo channel.
-Source is "CYC1 for helimixer"
-Output is "Cyc1 servo channel"

Create a Mixer for Cyc2 servo channel.
-Source is "CYC2 for helimixer"
-Output is "Cyc2 servo channel"

Create a Mixer for Cyc3 servo channel.
Source is "CYC3 for helimixer"
Output is "Cyc3 servo channel"


Now in the Heli mixer

- Stick input "Aileron" must be selected as "Long. control" in the Heli mixer
- Stick input "Elevator" must be selected as "Lateral control" in the Heli mixer
- Collective input "Pitch mixer output"


This is the only way to do a proper HR3 (for most swash types) mixing

**Comment by Hobby4life** [comment]
Any status about this issue?

**Comment by Hobby4life** [comment]
@WismyYao @bsongis-frsky @Nicholas-Luoyi 

Can you tell me if there is any progress on this issue?

**Comment by markymars** [comment]
I am glad I found this issue, I was pointed to github as it seems that I am not the only one that found out the mixer is not working good.
Hope this will be fixed soon as now the ethos is not usable for traditional helicopters. only if you use fbl. :-(

I will stick to my X10 with OTX for now.

**Comment by bsongis-frsky** [comment]
I think we could resolve this issue by having only one Heli mix

This Heli mix would have those parameters:

1) Sources: source for lateral control (Ail by default), source for longitudinal control (Ele by default), source for collective (Thr by default) + their weight (100% by default) and curve (linear by default)

2) Outputs are CYC1, CYC2, CYC3, CYC4 (depending on the swash type) and we can assign them to channels. No need of a channels count, it is not used today

Also I am not an expert, but I notice some clipping algorithm in OpenTX, in case (ele^2 + ail^2) > limit^2

**Comment by bsongis-frsky** [comment]
This one has been fixed in 1.0.10 already.
Unless something else is needed?

**Comment by Hobby4life** [comment]
Mix seems to work correct now tnx!
