### ISSUE TITLE
please change default channel amount to 16

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#544]
RF menu.
please change default channels to ch1-ch16 instead of ch1-ch8 low latency.

many more people use 16 channels than people who need low latency.
anyone running SxR or SRx by default needs at least 12 channels and many people miss out on the channels option.

please correct the default to ch1-ch16.
thank you.

**Comment by jreis1** [comment]
Agreed. 8ch Dont make much these days

**Comment by mherke** [comment]
Disagree! Most entry and mid level flight models dont use more than 6 channels. An expert can change the setting if needed. Butter use low latency if possible.

**Comment by i3dm** [comment]
> Disagree! Most entry and mid level flight models dont use more than 6 channels. An expert can change the setting if needed. Butter use low latency if possible.

because entry and mid levwl flight models require low latency? :)

**Comment by bsongis-frsky** [comment]
8CH = latency divided by 2

**Comment by i3dm** [comment]
why do we need latency devided by 2 as default? 99% of modellers dont need that.

**Comment by Hobby4life** [comment]
- I "gues" 90% of the users dont even know what latency is, let be that going from 16ch to 8ch will cause lower latency.
- In openTX it was standard, and even then we NEVER EVER heard anyone complain about it to be default.
- Frsky own Stabilized receiver requires 16ch operation to control them.

Based on all the above it is obvious to give the client full operation with so there will be no fuzz to get things working,. And let the "few" guys that need the lower latency. Choose for themselves to go to 8ch.
Not the other way arround. that makes no sense at all. Minority decides for the Majority???? hmm

**Comment by i3dm** [comment]
> * I "gues" 90% of the users dont even know what latency is, let be that they know that going from 16ch to 8ch will cause lower latency.
> * In openTX it was standard, and even then we **NEVER EVER** heard anyone complain about it to be default.
> * Frsky own Stabilized receiver requires 16ch operation to control them.
> 
> Based on all the above it is obvious to give the client full operation with so there will be no fuzz to get things working,. And let the "few" guys that need the lower latency. Choose for themselves to go to 8ch.
> Not the other way arround. that makes no sense at all. Minority decides for the Majority???? hmm

agreed

**Comment by bsongis-frsky** [comment]
1) Changed to 16CH in 1.0.10
2) It will be obvious that some channels are not sent to RF in Model / Outputs

**Comment by i3dm** [comment]
> 1. Changed to 16CH in 1.0.10
> 2. It will be obvious that some channels are not sent to RF in Model / Outputs

thanks bertrand
