### ISSUE TITLE
Feature request: Space between line`s on model select.

### ISSUE THREAD

**Issue by KevinFairgrieve** [FrSkyRC/ETHOS-Feedback-Community#546]
Feature Request.

When selecting a model on screen I have on several occasions "cloned" a model without realising. The next time I come to fly that model I select the wrong one, which of course is not bound to the TX.

Can a space or something similar be inserted between "Select" "Clone" and "Delete", so that my fat fingers can do no more damage.

**Comment by Hobby4life** [comment]
A confirmation YES/NO would just be enough to inform you.
this must be for every "critical" action, confirmation popups.

**Comment by KevinFairgrieve** [comment]
That would do it.

Something, anything.

**Comment by Hobby4life** [comment]
Even better would be:

Pressing on model:

- Short press model switch with confirmation yes/no
- Long press model clone / delete with confirmation yes/no

**Comment by bsongis-frsky** [comment]
There is already a confirmation on Model delete!

**Comment by Hobby4life** [comment]
> There is already a confirmation on Model delete!

Correct, but my idea is for faster model switching without misspressing for deleting or cloning.

**Comment by ZeekWorld** [comment]
Agree, hard to use the touchscreen when selecting a mode with average size fingers.

**Comment by bsongis-frsky** [comment]
In all screens (timers, mixes, functions, logic switches, sensors, etc.), [Enter Long] should directly go the Edit page.

**Comment by STC148** [comment]
[Enter Long] don`t work in mixer screen
