### ISSUE TITLE
FLVSS sensor showing "Cells Total" as average voltage?

### ISSUE THREAD

**Issue by ZeekWorld** [FrSkyRC/ETHOS-Feedback-Community#547]
FLVSS sensor on latest FW.
When Telemetry discovered, values are each cell voltage and total voltage doesn't show total voltage.
![IMG_20210627_075831.jpg](https://user-images.githubusercontent.com/16088952/123547319-84627300-d71d-11eb-9754-ed46b57fc7bb.jpg)

**Comment by bsongis-frsky** [comment]
Duplicate. Already fixed in 1.0.10

**Comment by ZeekWorld** [comment]
thanks
