### ISSUE TITLE
X10 Locking on load with Release 1.0.1

### ISSUE THREAD

**Issue by Dads-RC-Hangar** [FrSkyRC/ETHOS-Feedback-Community#55]
Hi, My X10 works fine with Firmware Version 0.0.17, but when i downloaded the latest Release 1.0.1 
It locks the boot screen as picture below. 
The only way to turn it off, is to take out the battery connection then put in bootloader mode and upload the Version 0.0.17 again.

![IMG_8126](https://user-images.githubusercontent.com/80551405/114244026-9d148580-9985-11eb-93eb-8f743f31a625.jpg)

**Comment by MIKE-DAILEY** [comment]
Did you flash the new 1.0.1. bootloader.bin?

**Comment by Dads-RC-Hangar** [comment]
Thank Mike, It's really strange as I must had done this before correct. 
It worked loading the boot loader then the firmware, it says now 1.0.1
But it also shows the timer I made and plane I added. I am wondering if something corrupted it. I will continue playing around to see if I can break it again.

**Comment by MIKE-DAILEY** [comment]
For the 17 to 1.0.1.  I deleted all my models and the radio files so it was a fresh start.

**Comment by Dads-RC-Hangar** [comment]
I left my radio for a week and it is frozen again. I am about to replace the RTC battery, I am hoping this is the issue.

**Comment by bsongis-frsky** [comment]
Models prior to version 1.0.0 are not supported
