### ISSUE TITLE
At the Model Wizzard Putz the Option Gear into it.

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#550]
At the Model Wizzard, i Miss the Numbers of Gear into it. For excample at a Motorplane or a Jet.
That the Wizzard put into the Mixer That i Need for ist. That can Save a lot of Time
Bye Alwin

**Comment by miksterr** [comment]
I agree - either have Simple wizard or advanced. Then maybe have options for retracts, smoke, and more in the wizard.

**Comment by bsongis-frsky** [comment]
Issue #552
