### ISSUE TITLE
Das Programmieren von Segel Flugzeugen schnell und einfacher machen. 

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#551]
Ich glaube es braucht eine Option die beim Wizzard fragt was für Optionen man beim Segler haben möchte. 
Zum Beispiel 2 querruder 2 wölbklappen. Willst du Butterfly? Willst du Stellung Speed?
Willst du Stellung Thermik? 
Dass die Mixer dazu alle schon bereit sind.
Willst du die Wölbklappen zum Querruder mit nehmen usw... 
Oder Sie erstellen einen globalen Mixer, den Man für alle Modelle verwenden können.

**Comment by Beastyboy80** [comment]
Diese Option gibt es doch ?!

**Comment by AlwinHaas** [comment]
Also ich meine dass im Wizzard nach all den Punkten gefragt wird. Nicht dass man selbst die ganzen Mischer einzeln Dazu fügen muss.

**Comment by bsongis-frsky** [comment]
Nobody speaks german here ...

**Comment by bsongis-frsky** [comment]
Issue #552
