### ISSUE TITLE
Batt voltage to percentage 

### ISSUE THREAD

**Issue by hamelsveld** [FrSkyRC/ETHOS-Feedback-Community#554]
Hi, can we get the function to "translate" the battery voltage to a percentage build in? On OpenTX this was possible via a script (see Hobby4life GitHub) but it would be great to have this is a regular function in Ethos.

https://hobby4life.nl/?p=316

**Comment by Hobby4life** [comment]
Good alternative for people that dont use current sensors in their models.
Although it is not that accurate in that way, if you have a bad cell you will not see it.
Anyways I use this method on all my planes. to have quick indication.
It gives you the same reading as a lipo checker.

**Comment by gjvo** [comment]
Percentage is no value.
Voltage you read in Volts, not in percentage so i would like to keep the Voltage indication.

**Comment by loetefix** [comment]
What we realy need is LUA. So you can do all calculation you want. For me as an helipilot who needs Integration the system is more or less useless. I hope it will come soon. If not i will resell the x20 and use my Radiomaster with the x10express access module.

**Comment by hamelsveld** [comment]
Yes on openTX we could do this with LUA but I think this is a "option" most people would like to use so why not build it in directly because the LUA script will give you the same value as the limo checker but without having to open your plane to connect the plug.

**Comment by Hobby4life** [comment]
> Percentage is no value.
> Voltage you read in Volts, not in percentage so i would like to keep the Voltage indication.

It all has to do with the chemical safety of Lithium polymer.
It gets unstable when approaching a certain level of voltage.
Too low you will get cell blowouts, resulting in battery faillure.

The percentage is calculated along a discharche curve. representing some kind of indication from full to a really empty pack in voltage.

Reading mAh's also is very dangerous..
Doing this with an healty pack it will work, but when getting older.. drawing its full capacity will result in very dangerous low cell voltages.
An older pack will deliver much less capacity then a new one.

Better is to read out cell voltages, but people have a hard time in reading decimal numbers.. there fore lipo checkers will give some sort of "readable" indication.
It is not the best, but better then nothing at all.

**Comment by jfint** [comment]
I would advise anyone against this.  The problem is that it only works under no load, batteries will do strange things when not under load, so if you aren't integrating watts consumed and dealing in watt-hours (Coulomb Counting) then its not worthwhile)

here are some lithium no-load equations for an initial State of charge, but like I said, they go to crap as soon as there is a real load.
![image](https://user-images.githubusercontent.com/16928210/124340919-a3be2d80-db6d-11eb-9dd1-5f6b31d21ed0.png)
![image](https://user-images.githubusercontent.com/16928210/124340924-a7ea4b00-db6d-11eb-813b-1b068433abeb.png)

**Comment by Hobby4life** [comment]
It is obvious that you can not use "any" voltage related readouts during heavy loads.
I suggest to wait for lua, and then people decide if they want to use a script like this.

**Comment by mawzthefinn** [comment]
This can be done now with Lua
