### ISSUE TITLE
Problem Sxr configurator. 

### ISSUE THREAD

**Issue by Paolotandemx20s** [FrSkyRC/ETHOS-Feedback-Community#555]
Found problem with Sxr configurator, correct stabilizer and inverted output channels, or inverse result, many tests to solve but without any positive result, my configuration is on flying wing and S6r accst receiver updated to new firmware. Possible bug ?? Forgive my English I am italian.

**Comment by Hobby4life** [comment]
What version / radio?

**Comment by Paolotandemx20s** [comment]
Flex 1.0.9

**Comment by bsongis-frsky** [comment]
I am not sure it's an issue with Ethos, yes?

**Comment by Paolotandemx20s** [comment]
Credo di si, perché la ricevente S6r usata sempre con soddisfazione in opentx

**Comment by FrSky-GX** [comment]
make sure the  stabilizer direction correct with SxR  configurator, then check control direction. If not  right, reverse the channel in the radio mixer or output.
