### ISSUE TITLE
1.0.10 RC1 Telemetry ESC-RPM Range is 0-0 and can't be adjusted

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#556]
X20S / FW 1.0.10 RC1 EU 
with Neuron 60 - no RPM value - always zero - probably because the range ist set to zero

**Comment by bsongis-frsky** [comment]
Please try to rediscover your sensor, the Range should be 0-80000r/m

**Comment by Cipta-de** [comment]
Thanks!!! rediscover - no success - but delete all and rediscover was successful :-)
But ther logical switches which belong to telemetry all lost :-( doesn't matter

**Comment by bsongis-frsky** [comment]
You should have just removed the RPM sensor!

**Comment by Cipta-de** [comment]
That's right - thanks.
 I was also thinking about but decided for "better save than sorry" to delete all sensors.  :-)
