### ISSUE TITLE
1.0.10 RC1 Device Config for SXR and Neuron ESC / BEC doesn't work anymore

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#557]
X20S / 1.0.10 RC1 EU no more connectivity to Neuron and SR8 to config anything 
Telemetry values from Neuron are present and OK (exept the RPM - see issue ...)

**Comment by Hobby4life** [comment]
Confirmed, not working anymore.

X20S

**Comment by pgee63** [comment]
Same problem here with SR6 and X20.

**Comment by Paolotandemx20s** [comment]
Configuratore SxR già male funzionente su versione 1.0.9 su x20s

**Comment by Hobby4life** [comment]
> Configuratore SxR già male funzionente su versione 1.0.9 su x20s

Maybe, but this is another kind of issue.. I hope this will be one of the things that will be fixed first.
As this is the only way for many to calibrate or config their SxR SRx receivers.. :-(

**Comment by bsongis-frsky** [comment]
Fixed for RC2
