### ISSUE TITLE
Slider 1 is not recognized under special functions

### ISSUE THREAD

**Issue by michifpv** [FrSkyRC/ETHOS-Feedback-Community#558]
Slider 1 is not recognized under special functions for play track.  I would like to announce a track for the flaps in the -100 and +100 position.

**Comment by MIKE-DAILEY** [comment]
Need to use a Logic Switch to monitor for Slider 1 to be greater -99 and another for greater than +99 and then use the Logic Swathes in Special Functions to play the wav files.

**Comment by Hobby4life** [comment]
firmware?
radio?

Please specify because things can be radio type and firmware version specific

**Comment by michifpv** [comment]
oh it works. thanks. not the easiest way but it works when you know it
