### ISSUE TITLE
Play value of RX number

### ISSUE THREAD

**Issue by DaySpeed955i** [FrSkyRC/ETHOS-Feedback-Community#56]
I would suggest a simple way to be able to play the RX number value when it change in a redundant system.
Presently, when play value of RX number, only the number is played so zero, one, two.
Would be nice to have "Rx number one" play instead.

It is possible to create this with logical switch and SF but it is not easy for everybody.

Thanks

**Comment by bsongis-frsky** [comment]
Will be solved by the PlaySequence function which is coming

**Comment by bsongis-frsky** [comment]
#441
