### ISSUE TITLE
1.0.10 RC1 Lipo Ratio & offset have no effect MLVSS/FLVSS & Output not visible on adjustment

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#560]
Lipo Ratio & offset have no effect MLVSS/FLVSS sensor ouput

Also

When adjusting ratio and/or offset you can not monitor the output of the calculation.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/124254251-296bba00-db29-11eb-80ff-fedf1d9a9b56.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/124254284-34264f00-db29-11eb-8b14-ff77e5491dd6.png)

**Comment by OB1-OB2** [comment]
I can't seem to make a negative offset. is that a user problem or related to this closed issue?

**Comment by bsongis-frsky** [comment]
Is fixed for 1.0.10RC3
