### ISSUE TITLE
Request: Active conditions for individual trainer inputs.

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#562]
In version 1.0.10 RC1 the trainer system now works as expected. good job!!!!! :-)

I would like to request an addition for each channel.

It would be nice if we could turn on/off every trainer channel with a source input.

Now are channels are controlled on/off at once.
I like to disable some functions during a flight if needed.

**Comment by mawzthefinn** [comment]
This is possible under current firmware. Not sure when it was added.

Each trainer channel/function can have active conditions assigned if desired.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/193921428-64c12a6b-cfb1-4dd0-b676-1afd9bc464e4.png)

Since 2021, december it seems
