### ISSUE TITLE
1.0.10 RC1 X20S Lipo Cell1....6  min/max does not work

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#563]
it shows always the actual voltage

https://user-images.githubusercontent.com/85410070/124025173-71d38c80-d9f0-11eb-857d-8d76f2f42b56.mp4

**Comment by bsongis-frsky** [comment]
Am I right in saying that Min and Max works for no sensor at all?

**Comment by STC148** [comment]
confirmed

https://user-images.githubusercontent.com/85410070/124033087-ca5b5780-d9f9-11eb-9560-b6a8d64fdc41.mp4

**Comment by bsongis-frsky** [comment]
Ok. It was stupid
