### ISSUE TITLE
AIN2 only does 1 decimal place no matter the setting

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#565]
Tandem X20
Ethos 1.0.10 RC 1
TD-ISRM 2.1.8
Archer R8 Pro on 2.1.7

When looking at telemetry for ADC2 and trying to use more than one decimal places, all subsequent decimal places are populated by '0'

**Comment by jfint** [comment]
![Uploading 20210630_171451.jpg…]()

**Comment by jfint** [comment]
![20210630_171451](https://user-images.githubusercontent.com/16928210/124046869-c4e51980-d9c7-11eb-84c6-57efe93e5e47.jpg)

**Comment by bsongis-frsky** [comment]
But the value coming from the Rx has only one decimal!

**Comment by jfint** [comment]
Ahh, didn't think that the rx would be so limited,  that's unfortunate
