### ISSUE TITLE
Ethos 1.0.10 RC1 SR8 config tool not working

### ISSUE THREAD

**Issue by Droptank** [FrSkyRC/ETHOS-Feedback-Community#566]
Calibration tool would not receive response from first step of calibration.  RX would blink YELLOW as normal for a second or two but the tx wouldn’t proceed to next step.  Also SR8 config tool would not populate as if not communicating with Rx.  All options were greyed out.  Roll back to Ethos 1.0.9 and they work perfectly again.

Archer SR8 firmware 2.17 latest
Ethos: 1.0.10 rc1

**Comment by Hobby4life** [comment]
Duplicate: #557
