### ISSUE TITLE
Bug(Enhancement): Decimals in Ethos

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#568]
When having a Altitude sensor.
Standard the decimal output is 2
For example 7.48m

When setting decimal output to 0, you will only have 7m

When going into logic to set a trigger at 7m.
Dialing to 7m takes a long time, cause in the back ground it is still using decimals when incrementing.

Normally we should jump from 6 to 7 within 1 encoder click.

I think this works throughout the whole ethos system.

Anyways these minor problems should again be solved with a virtual keypad ;-)

**Comment by bsongis-frsky** [comment]
Default step is now dynamic
