### ISSUE TITLE
Idea: QR code widget for GPS position

### ISSUE THREAD

**Issue by eijowk** [FrSkyRC/ETHOS-Feedback-Community#569]
Many of us have several times been struggling with entering the GPS position in google maps at the mobile to find your lost quad or wing.

It would be perfect if you cold have a qr code widget in ETHOS which is a complete google maps link with the telemetry GPS position from your model. Then you can just open it with your mobile camera and immediately see the position at google maps 😎

**Comment by mawzthefinn** [comment]
This has been implemented by @strgaltdel as a Lua

https://www.rcgroups.com/forums/showpost.php?p=50133317&postcount=21308
