### ISSUE TITLE
Default Configuration of Ail -> Rud Mixer for V-Tail

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#57]
I am testing ETHOS 1.0.1 on my Horus X10S Express and generally, I am very content with the overall appearance and functionality. However, I would like to offer the following feedback w.r.t. the predefined mixers. I have played with the Ail -> Rud mixer, but analogous considerations apply to the other predefined mixers.

I have generated a new model with a V-Tail and have then added an Ail -> Rud mixer, which has resulted in some anomalies.
First, the outputs for the V-Tail servos are called 'Elevator' and 'Rudder', which is confusing. They should rather be called something like 'V-Tail left' and 'V-Tail right', or 'V-Tail 1' and 'V-Tail 2'.
Secondly, the Elevator stick moves the two V-Tail outputs in the same direction, whilst the Rudder stick moves them into opposite directions, which is fine and as expected. However, the Aileron Stick, with the default settings of the Ail -> Rud mixer, moves these outputs into the same direction, whilst they must move in the same way as through the Rudder Stick. It is necessary to change the sign of one output in the mixer to correct this. (Otherwise the mixer would actually be an Ail -> Ele mixer.)
I believe there should be no need to change the default settings of the predefined Ail -> Rud mixer in order to make it work correctly. In fact, there should not even be the possibility to make such changes, or to specify the affected output channels at all. All of this is implicitely defined by the very nature of an Ail to Rud mixer.

I guess the more generic question behind the above issue is how much flexibility should ETHOS provide. My view is that inherent features of predefined mixers, which are implicitely defined by the nature of the mixer under consideration, should not be editable, e.g. which channels are affected. Otherwise, the principle of predefined mixers is kind of led to absurdity.

**Comment by Hartinger** [comment]
Just as a gentle reminder, the problem with the incorrect default weightings for thr Ail => Rud mix in combination with a v-tail is still present in 1.0.14.

**Comment by bsongis-frsky** [comment]
Now elevons are called "Elevator1" and "Elevator2" instead of "Elevator" and "Rudder".

**Comment by bsongis-frsky** [comment]
Issue confirmed for the weight

**Comment by bsongis-frsky** [comment]
Here is the result after the fix:

**Rudder Mix**
![image](https://user-images.githubusercontent.com/50834778/145559958-39daa7c8-e0e1-44ee-94b9-847e526e936a.png)

**Ail => Rud**
![image](https://user-images.githubusercontent.com/50834778/145560068-4907792b-2db4-4b99-926f-f6253dc7d08e.png)
