### ISSUE TITLE
Butterfly mix for motor planes/jets

### ISSUE THREAD

**Issue by Thoemse** [FrSkyRC/ETHOS-Feedback-Community#572]
Please add this mix for motor powered planes and jets too. It makes no sense to use it for gliders only. I use butterfly to land all my jets. It makes the stall characteristics much better. Same goes for warbirds. Right now you have to add free mixes to achive this. That makes no sense considering you have it readily available for gliders.

**Comment by CliffEvans** [comment]
What is wrong with using the glider mix? Butterfly is butterfly regardless of what type of aircraft it is!

**Comment by Thoemse** [comment]
Having Jets in the glider menu is cluttering it a lot. I got about 25 models to program and it helps if gliders are gliders and jets are jets. If i program jets as gliders it kinda defies the purpose of separating them.

**Comment by jfint** [comment]
I agree,  we've been using this on motor planes for a LONG time.
