### ISSUE TITLE
Butterfly motor combination

### ISSUE THREAD

**Issue by CliffEvans** [FrSkyRC/ETHOS-Feedback-Community#573]
Would it be possible to add to the butterfly mix for motorised gliders so that by the flick of a switch you switch the motor in or out.  When in the butterfly is bypassed.  I have been trying for weeks without success to programme a glider with a motor so that I can use the throttle stick for throttle or butterfly.

**Comment by jfint** [comment]
Just make each mix active based on flight mode and control the flight mode with your switch?

**Comment by CliffEvans** [comment]
Easily said!!  I have tried everything.

**Comment by jfint** [comment]
No i mean it,  mixes cadb be mutually exclusive using flight modes,  i did something very similar with elevator stick.  Only the one the wizrd created will get trim though, but in your case neigther need trim.

**Comment by bsongis-frsky** [comment]
@CliffEvans For your butterfly you have a condition, so you can setup a switch there. Now for the throttle mix, why don't you use the Throttle Cut ?

**Comment by mawzthefinn** [comment]
Two functional answers have been provided, please confirm if this is now a solved issue @jfint

**Comment by jfint** [comment]
sorry, not my issue.

**Comment by mawzthefinn** [comment]
Thanks, closing this off
