### ISSUE TITLE
Bug: stick order in logic not right after model copy to other radio mode1 to mode2

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#574]
The stick order was fixed when sharing a model to another radio. 
X20S Mode1 to X20S Mode 2.
But in system logic it is still swapped. Moving throttle on mode2 will select elevator in mode1

**Comment by bsongis-frsky** [comment]
I the model version 1.0.10 or before
It cannot work correctly with models having an old format

**Comment by Hobby4life** [comment]
V1.0.10rc2 to v1.0.10rc2

**Comment by Hobby4life** [comment]
Still some routine looks for stick position, not stick variable.

**Comment by bsongis-frsky** [comment]
ok, but is the model really converted to 1.0.10? if nothing changed, it is not written in the new format

**Comment by Hobby4life** [comment]
Yes correct, copy from rc2 to rc2

**Comment by bsongis-frsky** [comment]
auto detect is another issue which is fixed for RC3
