### ISSUE TITLE
X20 Simulator trojan

### ISSUE THREAD

**Issue by iulius-esp** [FrSkyRC/ETHOS-Feedback-Community#575]
Windows Defender detects trojan in X20-Simulator.exe.

Trojan:Win32/Emali.A!cl

**Comment by jreis1** [comment]
confirm that. You can work around by allowing the exe in your anti-virus though.

I also confirm that in the simulator 1.0.10RC2, opening the "sticks" menu crashes de app.

**Comment by bsongis-frsky** [comment]
The trojan seems a false positive

![image](https://user-images.githubusercontent.com/50834778/124314761-28f81100-db73-11eb-9925-4a9385b7f8d1.png)

Instead the sticks menu is a very positive bug, fixed in RC3
