### ISSUE TITLE
Trim Mix

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#577]
- [x] Trim mix too slow, the speed should be the same than normal trims
- [X] Custom increment range [1:10] modified to [1:200]
- [ ] Custom increment could be controlled by a Source
- [x] Possibility to have one current value per Flight Mode (checkbox)
- [ ] Curve not drawn

**Comment by loetefix** [comment]
similar to #449 and #216

But it seems they dont care about that.....

**Comment by loetefix** [comment]
Will this improvements come in near future please?

**Comment by loetefix** [comment]
is there any news for --> Possibility to have one current value per Flight Mode (checkbox) for the trim mixer  ?

**Comment by mawzthefinn** [comment]
I would REALLY love to have per-FM values in Trim mixers. That would also make relative/inherited trims super easy (have one trim mixer without per-FM trims and adjusters which are only valid in one flight mode, a second with per-FM trims that isn't Active in the FM that the first can be adjusted in)

**Comment by loetefix** [comment]
> I would REALLY love to have per-FM values in Trim mixers. That would also make relative/inherited trims super easy (have one trim mixer without per-FM trims and adjusters which are only valid in one flight mode, a second with per-FM trims that isn't Active in the FM that the first can be adjusted in)

exactly

**Comment by MrD-RC** [comment]
I figure I'd link this even older issue. This is something that is missing and very much needed. https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/215

**Comment by lightbulbjim** [comment]
Trim mixes still move too slowly. Would love to see this addressed.

**Comment by mawzthefinn** [comment]
Fixed in 1.5.0, they have the same repeat ramping as trims. The change came from the VAR implementation

**Comment by hrenz** [comment]
ok can be closed
