### ISSUE TITLE
min or max value on home screen

### ISSUE THREAD

**Issue by Asimos32** [FrSkyRC/ETHOS-Feedback-Community#578]
in a home screen widget i want to see only Min or Max value of a sensor for all the flight. is that possible?
lets say i want to see only the lowest VFR from all the flight, or the lowest RSSI.
thank you

**Comment by jreis1** [comment]
Yes. You need to add the telemetry value you want. After that, long press enter, and select min or max. 


I know…. It’s not intuitive :/

**Comment by Asimos32** [comment]
thank you
