### ISSUE TITLE
bug: bad auto detection of the analog input in mixers

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#579]
RC 10.02

After installing rc 10.02 i have create a new model and i find this problem:
When editing the source in a mixer, the autodetection fail with analogics input. I am in mode 2, when i move the gaz it selected the profondeur and when i move profondeur it select gaz.
When you select the input manually there is no problem.
I have check if the mode 2 was selected, it is, itry to select mode 1, shut down radio and select mode 2 again, the issue is still here.

**Comment by MIKE-DAILEY** [comment]
To replicate this issue.  With Sticks set as Mode 2 create new Airplane model with defaults.  Add Free Mix to Mixer.  Edit Free Mix.  
Select Source and move Elevator, system displays auto detect Throttle.  Move Throttle and system audio detect Elevator.  Aileron, Rudder, pots and sliders auto detect OK.

**Comment by Hobby4life** [comment]
#574
