### ISSUE TITLE
1.0.10 RC2 X20S RPM do not work

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#580]
The widget shows always 0
in sensor setup the unit is not selectable and the range is not adjustable

https://user-images.githubusercontent.com/85410070/124362035-ebf35380-dc32-11eb-8c29-faa6d60351eb.mp4

**Comment by STC148** [comment]
in the simulator it looks like that:
![Screenshot 2021-07-03 192608](https://user-images.githubusercontent.com/85410070/124362400-d2530b80-dc34-11eb-9377-767e3d34982f.jpg)

**Comment by michifpv** [comment]
Had the same. Delete all sensors and search again. worked for the neuron esc.

**Comment by STC148** [comment]
MY FAULT!
i discoverd new sensors but i forgot to delete first
