### ISSUE TITLE
Viewed from the output menu, the servo values will fluctuate even without moving the controls.

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#582]
https://user-images.githubusercontent.com/84585992/124367314-62ee1380-dc56-11eb-9c2d-8589f628b713.mp4

Why is this?
This is not good. I could say it's unacceptable!

The servos are constantly moving.
Over a very small range, of course, but a completely empty servo, without any load, will fluctuate. 
The fault occurs on all four stick handles.

Design fault or is it just my new transmitter that is bad?
No such fault on my HORUS X10S radio.

Easy to test in other formats.
If you set the screen to go to sleep for 1 second and switch the activation to the stick control, it either can't go to sleep or turns the display on and off.
This is because it senses that the handlebar is moving, even though you are not touching it, not moving it.

**Comment by centertrim** [comment]
The jitter you are seeing just sensor / electrical noise from the stick ADC inputs.  It occurs on every sensor of any type.  Your example is very minor.  The only way to eliminate it is with more filtering, but that brings other trade offs whose magnitude depends on how much filtering is done.  If filtering is added to average out the noise and create the “calm” value that you seem to desire, then an unavoidable delay is added to any real stick movements.  This will show up as added delay in end-to-end latency testing.  Nothing is free.

As far as the display activation goes, they probably already have a center deadband for that, so it could just be increased a point or two.

**Comment by Hobby4life** [comment]
Thats normal ADC jitter. Only it is visible now and noticeble.
As said better filtering needed for visuality and for things that use these ADC values in system, but keep it most unfiltered for controlling outputs.

Just because it isn't visible on a horus or something else, doesn't mean it doesn't happen there either.

**Comment by loetefix** [comment]
Most servo have a deadband that ignores the jittering.but i also want to see a ADC filter that compensates the jitter because it is very annoying.the filter could be only for displaying. So the output to the servos are not affected.

**Comment by jufelap** [comment]
centertrim: thanks for the precise answer!

Hobby4life: thanks, then I would need a software filter for the display only, just for the sake of display and better visibility. 

listefix: exactly what I was thinking. Anyway, it does ignore the servo :-( Xact 5701 servos you put it to your ear and you can hear it trying to track it down. Of course this doesn't make the moving arm bounce, as the dispersion is small, but it's like an internal resonance :-) 

Thanks everyone for your help, I understand the cause of the problem!
