### ISSUE TITLE
Bug: Telemetry calculated sensor

### ISSUE THREAD

**Issue by tadamox** [FrSkyRC/ETHOS-Feedback-Community#583]
Ethos 1.0.10 RC2 Flex
X20
After multiple selecting Consumption Formula name is set to random sting.
Steps to reproduce:
1. Choose "Create calculated sensor" in Telemetry page
2. Choose "Consumption" from Formula drop down at least 2 times.
3. Name changes to random string, Unit changes to ml and Decimals to 208. Also Range changes to random range

**Comment by bsongis-frsky** [comment]
Already fixed
