### ISSUE TITLE
Disarm part of throttle cut not correct

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#584]
I'm certain earlier versions were working correctly. But going back through my videos I haven't been able to confirm. I am using 1.0.10 RC2.

The arming part of the cut works fine. You have to lower the throttle below the trigger value before it will arm.

However, the issue is that flicking the switch to the disarm position does not disarm immediately. To me this is a huge safety issue! You have to lower the throttle below the trigger value before it will disarm. As soon as the switch is flicked, it should disarm.

Please can this be fixed as a high priority, for the sake of fingers everywhere.

**Comment by MIKE-DAILEY** [comment]
I've tested the Throttle cut function with 1.0.12. RC2 and it works as it has from the beginning as a throttle cut for glow and gas power with the Tigger value that is adjustable for a posable EP power cut.  

From what what you describe seems you might be asking for an EP power arm/disarm switch.    

Could it be that you might be looking for this option that is in the 1,0,10, milestone https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/494

**Comment by DJMacGregor** [comment]
Certainly do not want it to disarm when flicking the switch to the disarm position for helicopters. If that switch was flipped by accident while flying that would be very interesting 😏.

**Comment by MIKE-DAILEY** [comment]
> Certainly do not want it to disarm when flicking the switch to the disarm position for helicopters. If that switch was flipped by accident while flying that would be very interesting 😏.

The Trigger value can be used to prevent that.

**Comment by MrD-RC** [comment]
> I've tested the Throttle cut function with 1.0.10. RC2 and it works as it has from the beginning as a throttle cut for glow and gas power with the Tigger value that is adjustable for a possible EP power cut.
> 
> From what what you describe seems you might be asking for an EP power arm/disarm switch.
> 
> Could it be that you might be looking for this option that is in the 1,0,10, milestone? #494

Yes, that is 100% what is needed. The current cut is dangerous as far as I’m concerned. The whole point of a cut should be that it cuts the power immediately, for the safety of people. Preserving the model is secondary to this. 

I’ll close this issue as #494 covers this. I hope it is in the 1.0.10 stable release though. This is very important in my eyes.
