### ISSUE TITLE
Bug: X10S/X20S v1.010RC2 - Current sensor readout stuck at random number after fast current drop to 0 Amp

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#585]
Ethos: v1.010RC2
Radio: X10S Express

I have connected a current sensor (100A).
Readout is fine until real current flow drops instantly to 0 Amps.
Telemetry readout is stuck at a random value for example 7.54amps and consumption keeps flowing.
It does not drop to 0 amps.
This when there is no real load anymore.

Tested this on X20, there it is dropping to 0 amp.. and consumption stops. works ok.

**Comment by bsongis-frsky** [comment]
When you say "Telemetry is stuck", do you see the small point displayed, saying that you receive a sensor value?

**Comment by Hobby4life** [comment]
yes correct.. when resetting telemetry all is 0 and keeps 0, untill we will provide new load.

**Comment by bsongis-frsky** [comment]
it would do this if the received value was not inside the allowed range

**Comment by bsongis-frsky** [comment]
did you recently discover this sensor?

**Comment by Hobby4life** [comment]
No not that I am aware off.

**Comment by bsongis-frsky** [comment]
Please try to discover again your sensor, I am afraid that the limits are not correct

**Comment by Hobby4life** [comment]
Tried several times.. but still same problem..  if the amp is dropping from load to no load instantly, the amp readout just hangs at a random number, and consumption keeps running too.

**Comment by bsongis-frsky** [comment]
because it allows to filter wrong values
also the limits are used when we need to convert the sensor value to percent

**Comment by bsongis-frsky** [comment]
This config has been tested earlier today. Impossible to reproduce:

```
X10express 1.0.10CR2
ISRM 2.1.6
rx  : Archer R4 2.1.7
sensor : FAS40
```

**Comment by bsongis-frsky** [comment]
Please give us your exact config with firmware version.

**Comment by Hobby4life** [comment]
X10S Express
X20S

V1.0.10 rc2

**Comment by bsongis-frsky** [comment]
You said earlier "X10S Express", not "X20S"
I don't think Ethos is involved here. I need your firmware version for your module and RX (with model)

**Comment by Hobby4life** [comment]
> You said earlier "X10S Express", not "X20S"
> I don't think Ethos is involved here. I need your firmware version for your module and RX (with model)

Yes correct, I have seen it today on my X20S too.

Firmware on X20S is v2.18
On X10S Express fw v1.1.0/2.1.0EU

**Comment by bsongis-frsky** [comment]
And which receiver, which firmware on this receiver?

**Comment by bsongis-frsky** [comment]
What are the limits on your sensor?

**Comment by Hobby4life** [comment]
Model 1
0 - 150A for current.
0 - 10000mAh for consumption

Model 2
0 - 655.35A for current
0 - 65535mAh for consumption

Both keep running

**Comment by bsongis-frsky** [comment]
I miss an important information: which receiver and which firmware on this receiver?

**Comment by Hobby4life** [comment]
> I miss an important information: which receiver and which firmware on this receiver?

Sorry
Model 1 = R8 Pro v2.17
Model 2 - SR10 Pro V2.17

**Comment by Hobby4life** [comment]
I have noticed this will not happen if current is dropping slowly. Only happens from full to no load instantly. Maybe because it is noticable with my own currentsensors that have a faster samplerate (openxsensor). I dont know.

**Comment by bsongis-frsky** [comment]
Are you saying this happens with openXsensor and not FrSky sensors???

**Comment by Hobby4life** [comment]
I will test tomorrow

**Comment by bsongis-frsky** [comment]
I need your email, I would send you 1.0.10 RC3 a little bit in advance, with telemetry logs enabled. We would understand easily.

**Comment by Hobby4life** [comment]
> I need your email, I would send you 1.0.10 RC3 a little bit in advance, with telemetry logs enabled. We would understand easily.

Hi, I have just sent you an email.

**Comment by bsongis-frsky** [comment]
This is what I found in your log file:
![image](https://user-images.githubusercontent.com/50834778/125269117-b15f7a00-e308-11eb-8503-b48c1c7b7711.png)
This value is out of the allowed range and is now trashed. So:
- The consumption will stop increasing
- You will get "Sensor lost"
If your sensor is an openXsensor you could open an issue there

**Comment by bsongis-frsky** [comment]
1) we cannot support sensors which don't fullfill the spec, here openXsensor should be fixed
2) if this scenario happens, we filter the bad values (they are trashed, as if they were never received)
3) after 3 seconds of forbidden values, the sensor will be considered as lost
4) if the user is annoyed by the message "Sensor lost", he can deactivate the warning

**Comment by Hobby4life** [comment]
I Agree with Bertrand, OpenXsensor should need a fix on some readouts.
This issue will be continued on the OpenXsensor git.

**Comment by Hobby4life** [comment]
I made a little quick fix in OpenXsensor.. that "solved" the problem in ethos.
It has to do with 0 offset calibration in openxsensor.
