### ISSUE TITLE
Bug: X10S Receiver still connected after power off receiver.

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#586]
Ethos: v1.010RC2
Radio: X10S Express
Test with Receiver: R10 Pro

When powering off receiver, radio tells me "telemetry lost", but signal in top bar is coming back.
Radio thinks there is connection, but receiver is off

Only sensor that is active is: RxBatt ????

![2021-07-05 11 31 42-1](https://user-images.githubusercontent.com/55426642/124450609-e443c400-dd84-11eb-8c27-35524567fc0c.jpg)

**Comment by Hobby4life** [comment]
After ressetting telemetry, Signal indicator is off, and I can turn off radio normal without warning.

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.10 RC4
