### ISSUE TITLE
X20_ETHOS_1.0.10-C2, FRSKY FLVSS Voltage sensor

### ISSUE THREAD

**Issue by Speeedy-U** [FrSkyRC/ETHOS-Feedback-Community#587]
FRSKY FLVSS sensor, no single cell voltage sensor available. ( SUM voltage is available )

**Comment by skyfly74** [comment]
It is available, but it has change of location. There is no more cell 1, cell 2 in the sensor... But go directly to special functions and select read value, take "lipo" in telemetry and after make a long press on lipo, you will have option to select.
Choose lowest or highest and you will have a single cell voltage reading.

**Comment by Speeedy-U** [comment]
Thanks !,   I have found the lowest cell information ( C1,C2,C3...) and defined an alarm (voltage)
