### ISSUE TITLE
Bug?: v1.0.10 RC2 - What does the negative option do in Trainer (Destination)

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#590]
Radio: X20S

What does the negative option do in Trainer (Destination)

I expected it to invert the slave stick input.. but it does nothing.

![2021-07-05 20 07 55](https://user-images.githubusercontent.com/55426642/124507285-c6e71800-ddcd-11eb-9fb7-5c184a23bae0.jpg)

**Comment by Nicholas-Luoyi** [comment]
For example the incoming value is 25%. And if you select the negative option. It will replace/add to the destination with the negative value i.e. -25%.

**Comment by Hobby4life** [comment]
So this is like inverting a the trainer signal? if so then it does not work. I see no difference in direction at master trainer screen or outputs at master transmitter when enabling the negative option.
