### ISSUE TITLE
Display telemetry from previous flights

### ISSUE THREAD

**Issue by michifpv** [FrSkyRC/ETHOS-Feedback-Community#591]
With my Jeti, i'm used to comparing telemetry values ​​with older flights directly at the airfield.

For example, you can easily observe the battery is still healthy and can still generate full amps at start without using the pc at home.

Or you can change the antenna arrangement directly at the airfield and see something has changed from previous flights.

On my jeti i can see all values via a diagram, but the minimal/maximum values from the telemetry sensors that you can select would also nice.

i know you have more important things to do, but that would be a useful addition

![k-20210705_201515](https://user-images.githubusercontent.com/46536891/124507618-6e644a80-ddce-11eb-99b7-66a6443d9101.jpg)
![k-20210705_201530](https://user-images.githubusercontent.com/46536891/124507621-6f957780-ddce-11eb-8f11-f33f171b6085.jpg)

**Comment by STC148** [comment]
there is an open issue
Logs feature enhancements #284

**Comment by Nicholas-Luoyi** [comment]
Yep. Please see 284 for more information.
