### ISSUE TITLE
Request: Graphing widgets / Screens

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#592]
I know there is a lot of other work to do.

But I like to request Graphing widgets.

- [ ] Bar Graph, Horizontal & Vertical : #665 
- [ ] Line Graph : #603

Widget screens

- [ ] Fullscreen / without topbar etc. #707
- [X] Fullscreen / with topbar etc.

**Comment by bsongis-frsky** [comment]
Splitted into many issues

**Comment by pld74** [comment]
@bsongis-frsky Thank you!
