### ISSUE TITLE
Hf-Modul mit einem Widget Ausschalten

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#593]
Schön wäre es wenn man ein Widget hätte um das HF Modul zu deaktivieren. Zum Beispiel wenn man etwas Programmieren will oder was nachsehen möchte finde ich es sinnvoller wenn man das HF Modul deaktivieren kann.

**Comment by Hobby4life** [comment]
I can not imagine in what situation this should be usefull. It can per accident cause dangerous situations. Personally i think we should avoid these functions.

**Comment by bsongis-frsky** [comment]
Agreed, this is not a good idea.
We have added to Ethos a special start mode, without RF: press [PAGE] when starting your radio
