### ISSUE TITLE
Updated PT translation

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#594]
**Text translations (as per 1.0.10RC2):**
[pt.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6769573/pt.txt)

**Audio translation with some phonetics adjustments:** 
[audio_pt.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6769578/audio_pt.txt)

**Comment by andika207** [comment]
it took me 20 seconds to check out the second file.
I scroll down until the RSSI lines and I get to stop reading. 
I found the same stupid mistake as on the english text version
it's not 900, it's 915 or 868 if you use the EU version

**-throttle-warning.wav, Atenção! Stick do acelerador alto**
 
LOL so the proper word for you was ''manche'' but now you want to use ''stick'' which is not even wrriten.... ?

**-rssi-ext-critical-warning.wav,Sinal rádio do módulo externo crítico** 

pfff again.... sometimes ''sinal radio'' sometimes ''sinal'' only and sometimes nothing nada rien......

**Comment by bsongis-frsky** [comment]
@andika207 if you need only 20 seconds, perhaps it would be more efficient to take the file from @jreis1 and propose your changes?

**Comment by jreis1** [comment]
I believe 900mhz is not wrong. It is actually refereed as the generic 900mhz frequency band. There are plenty of people using FCC in Europe. I believe when saying 900mhz fits both proposes (FCC and LBT). For me this is isn’t a question. 

Regarding to the other comments, my education says me to ignore it.

**Comment by andika207** [comment]
@bsongis-frsky j'ai vu un tas de choses bizarres puisque il est incapable de tout traduire, par example: **TRIGER_POSITION = "Position déclenchement"**

vu que c'est un truc perssonel moi je propose d' ajouter plusieurs fichiers .wav alternatifs dans le dossier audio. https://userscloud.com/76v8847s5cma

la version francophone ne me plaît pas nonplus puisque vous gardez l'ordre des mots en anglais et à l'oreille ça sonne pas correct, par example ''**signal radio du module externe critique**''

il serait bien plus simple de dire ''**signale critique du module externe**'' pas besoin de rajouter ''**radio**'' tout le temps et on écoute ''**critique**'' suivit de ''**signal**'' donc le cerveau commence à réflechir sans avoir à écouter le message entier. bref.

un autre example ''**trainer lost**'' ce qui donne ''**radio élève déconectée**'' même chose en espagnol ''**radio alumno desconectada**'' et ce mec traduit avec ceci: ''**connexion à la radio élève perdue**'' aucun sens !!

ensuite il veut me donner des leçons en disant q' il se renseigne sur les terrains pour savoir quels sont les mots utilisés à l'aviation grandeur. MDR

**Comment by bsongis-frsky** [comment]
J'aimerais juste ne pas voir d'agressivité dans ces issues. On peut ne pas être d'accord et débattre en adultes.

**Comment by andika207** [comment]
@bsongis-frsky pas plus agréssif que cela: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/58#issuecomment-817785953 https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3#issuecomment-808505312

**Comment by jreis1** [comment]
@bsongis-frsky I've always tried to use my best judge to translate ethos to PT and, as accurately as possible. From you @andika207 , I've just received criticism and arrogancy, but never a direct contribution.  I'm still waiting for your files!

To be clear:
- I'm doing this translation mostly as a request of people from my local club, that have difficulty understanding English.  Quite frankly, I feel I've done my part. 
- The Text translation was done based on the (provided) French file, so it is possible that sounds a bit "frenchy";
- Audio file was translated from the EN version, 
- When I had doubts in what to use where, I've also looked at the spanish and french files.  
- I always tried to keep the translation near to the originals. 
- Technical terms where confirmed with local club people and sometimes with airline pilots. 

I'm doing this pro bono, I don't have neither the time nor the age to waste with nonsense discussions.
I have also feel that this has gone way beyond a technical contribution and it is now a gossip place. That was not my intension and I apologize in advance.  

As soon as @andika207 releases his/her version, I'll stop supporting PT translation, unless requested. 
I'll continue to contribute to Ethos in all other ways as I'm a frsky fanboy and truly believe in the powerfulness of this system.

**Comment by andika207** [comment]
> From you @andika207 , I've just received criticism and arrogancy, but never a direct contribution. I'm still waiting for your files!

had you not ignored my comments or do you feel the need to reply because I pissed you off ?? 
why on earth would you want me to create a file for you if you don't even hear or take other's suggestions into account ? https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/506#issuecomment-866320711

Yes, in french it's still ''**manche de gaz**'' so keep your personal translation ''**stick de l'accélerateur**'' for your club mates

you won't teach me. I'm done.

**Comment by bsongis-frsky** [comment]
@andika207 I am still waiting for your pt.txt, will you send it before 1.0.10 RC3 (this week-end if everything goes smoothly)?

**Comment by andika207** [comment]
@bsongis-frsky je croyais pas que c'était une vrai proposition.... si vous avez aucun fichier excel officiel je peux prendre son fichier .txt (avec royalties LOL) et écrire en rouge ce que je pense que ça peut aller mieux mais il y a des abréviatures en anglais que moi même suis incapable de les déchiffrer sans un example clair mais je regarderais les autres langues pour voir ce que ça donne et je fais pas du vol planneur nonplus donc il y a des trucs qui m'échappent . Quand il será prêt je le dirais.

 * Copyright (C) FrSky RC, Inc - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * 06.07.2021 - jreis -** joo.trash@gmail.com

**Comment by bsongis-frsky** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/Ethos-localization

**Comment by bsongis-frsky** [comment]
> @bsongis-frsky pas plus agréssif que cela: [#58 (comment)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/58#issuecomment-817785953) [#3 (comment)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3#issuecomment-808505312)

I just see your answer. 
- I see no agressivity in the first comment, cultural difference? 
- I am sorry for the second one. My personal taste makes me feel your picture very horrible, perhaps I am wrong and it is not, I will stick with our designer proposal which I personally do like :)

**Comment by bsongis-frsky** [comment]
@jreis1 perhaps we should go forward, do our best with the comments we have and have some as-good-as-possible PT translation in 1.0.10?

**Comment by jreis1** [comment]
> @jreis1 perhaps we should go forward, do our best with the comments we have and have some as-good-as-possible PT translation in 1.0.10?

Hey @bsongis-frsky 

Please find attached the revised translations based on 1.0.10RC4. 
**text:** [pt.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6841813/pt.txt)
**Audio:** [audio_pt_rssi.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6841817/audio_pt_rssi.txt)

According to some of the comments above, I've replaced "Sinal rádio" with "RSSI", to keep the speech short. However, I'm not sure if your TSS will convert properly the phonetics of "RSSI" in PT.  We will give it a try. It it not sounds right, I'll move back to "sinal rádio" in next RC. 

cheers,

**Comment by jreis1** [comment]
PS: i've also re-write some words with chart "õ", so can you please add it to the system?

**Comment by bsongis-frsky** [comment]
õ is there since long, it was needed for ES translations if I am not mistaken

**Comment by jreis1** [comment]
> õ is there since long, it was needed for ES translations if I am not mistaken

Perfect then :) I have requested this a while ago and I was not sure if it was already implemented.

**Comment by jreis1** [comment]
@bsongis-frsky I've noticed in 1.0.10RC8 the audio files have not been updated to the latest file I made available above. Should I open a new issue?

**Comment by andika207** [comment]
> @andika207 I am still waiting for your pt.txt, will you send it before 1.0.10 RC3 (this week-end if everything goes smoothly)?

je vous ai envoyé les trois fichiers par courriel, le fichier FR n'est pas modifié à fond puisque c'est une perte de temps et un bouleau trop stréssant si vous aimez des abréviations partout.

il y a une mauvaise coordination entre les traductions, dans un même fichier j' ai vu le même mot traduit autrement et d' un fichier à un autre le sens du mot est tout à fait le contraire (antonyme) ou ne correspond pas du tout à la traduction en anglais. du bric-à-brac vraiment....

c'est difficile à traduire puisque je comprends pas la vrai fonction de certains trucs pour planeur, la traduction anglaise est terrible des fois et je sais pas si le logiciel limite le numéro de charactères mais avec les 4 fichiers devant moi j'ai choisi le plus convenable.

faut aussi remarquer que j'ai plusieurs éditeurs de texte mais un seul fonctionne correctement avec ces fichiers et j'ai pas pu changer la couler de mes traductions convenablement.

<a href='https://postimg.cc/64CxvPmF' target='_blank'><img src='https://i.postimg.cc/cCbxVyM1/screenshot-4.png' border='0' alt='screenshot-4'/></a>

**Comment by andika207** [comment]
> õ is there since long, it was needed for ES translations if I am not mistaken

pas du tout, en espagnol il existe uniquement Ñ ce qui correspond en français ou italien à GN ou le portugais NH

**Comment by andika207** [comment]
> * I am sorry for the second one. My personal taste makes me feel your picture very horrible, perhaps I am wrong and it is not, I will stick with our designer proposal which I personally do like :)

le fond noir de Frsky OS était un vrai inconvénient, les chinois avaient promis d' autres couleurs qui ne sont jamais arrivés.
il faut surtout offrir une palette ample de plusieurs couleurs et ne pas s'enfermer dans une bulle avec un style moche
je me suis aperçu que les gens aiment le fond clair pour le soleil mais c'est loin de ce que propose ETX 
https://www.youtube.com/watch?v=0ASoy-YVfmo&feature=youtu.be
