### ISSUE TITLE
Edit model, change model image, it is displayed in the model selection, but no longer in the main display  

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#596]
ETHOS V1.0.10Rc2
Edit model, change model image 
It is displayed in the model selection
But no longer in the main display 
back to the old picture also not

![screenshot-2021-07-06-72677](https://user-images.githubusercontent.com/6217896/124648663-d3d03e00-de97-11eb-9478-21f49316708c.jpg)
![screenshot-2021-07-06-72688](https://user-images.githubusercontent.com/6217896/124648667-d5016b00-de97-11eb-913f-5e2be89f3d04.jpg)
![screenshot-2021-07-06-72700](https://user-images.githubusercontent.com/6217896/124648669-d5016b00-de97-11eb-87cb-707ffb765534.jpg)

remark:
what kind of stupid program is this where you can't
not even the *.bmp of the x20  put in directly

**Comment by Hobby4life** [comment]
> remark:
> what kind of stupid program is this where you can't
> not even the *.bmp of the x20 put in directly

You are always very kind with your answers i noticed. you really expect the devs will run faster this way?

But PNG is pretty a standard nowadays if did not already know that.
Ow for I forget.. BMP does not support transparency.. thats a main reason.

**Comment by hrenz** [comment]
Then you must not create a *.bmp as a screenshot.
Such things are incredibly annoying

and it annoys many people that Frsky does not care about the bugs in their protocols ACCST and ACCESS
the errors always have to prove users

**Comment by bsongis-frsky** [comment]
I am not allowed to paste the internal discussions here, but we do take care of your comments, Wismy spent the whole day trying to replicate your telemetry issue. She succeeded and tomorrow she will try to find which is the part involved in this issue (Module / X20 / Ethos).

This kind of issue is difficult to deal with.

Also please try to understand and respect the people who are working hard to meet users expectations.

**Comment by Hobby4life** [comment]
That they are not responding to some issues, Do not mean they ignore these.
Some may be very complex to fix, some dont.

The problem with all these so called "many people" they dont register at github but issue things on RC-Groups or Facebook or German Frsky forum or whatever. That is not the place to collect these issues.

**Comment by bsongis-frsky** [comment]
Yes it's late here, but he made me return to the computer...

**Comment by bsongis-frsky** [comment]
About the issue itself now. I am afraid you run out of memory. Loading bitmaps use RAM, which can lead to fragmentation. At the end you have not enough RAM to display a big bitmap because it's too much fragmented.

What is the size of your model bitmaps?

**Comment by Hobby4life** [comment]
> About the issue itself now. I am afraid you run out of memory. Loading bitmaps use RAM, which can lead to fragmentation. At the end you have not enough RAM to display a big bitmap because it's too much fragmented.
> 
> What is the size of your model bitmaps?

I gues he means, the simulator saves as BMP, and here in github you can not place BMP files.

**Comment by bsongis-frsky** [comment]
I could work on PNG screenshots, ok.
Also I will delay the keyboard support to 1.0.11, ok everybody?  
I am full time on it, and it's complex to do something nice.
Not sure everyone will be happy if I follow hrenz priorities ;)

**Comment by jreis1** [comment]
> About the issue itself now (model image not displayed after change). (....)
> 

This issue is also happening in 1.0.10RC2 Simulator.

**Comment by MIKE-DAILEY** [comment]
With 1.0.10 RC2 not able to replicate using the X20 standard image size 300x280 PNG.

**Comment by bsongis-frsky** [comment]
@jreis1 please upload your bitmap here, I will check when I can, what is the size of your bitmap? please take into account that a bitmap of 800x600, 4 bytes per pixel is very big compared to the available RAM on all radios.

**Comment by hrenz** [comment]
Hy bertand,
my modellpicture collections are all in same way auto generated 300x280pixel 256colours 

[X20 Modellbilder002.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6778578/X20.Modellbilder002.zip)

![D_Evo](https://user-images.githubusercontent.com/6217896/124791226-2834f580-df4c-11eb-852a-67729f27151a.png)
![M_Edge-540](https://user-images.githubusercontent.com/6217896/124791234-29feb900-df4c-11eb-89cb-170ea25a806f.png)
![M_Edge-541](https://user-images.githubusercontent.com/6217896/124791236-2a974f80-df4c-11eb-9ffc-d8cc7d137e2f.png)
![M_P-47](https://user-images.githubusercontent.com/6217896/124791238-2a974f80-df4c-11eb-9b86-9431c305941b.png)
![M_P-51](https://user-images.githubusercontent.com/6217896/124791239-2b2fe600-df4c-11eb-80a3-9bff06a5b6d7.png)
![N_Me163](https://user-images.githubusercontent.com/6217896/124791241-2b2fe600-df4c-11eb-9b5b-8cd64cb3cb03.png)
![N_Wonder02](https://user-images.githubusercontent.com/6217896/124791244-2bc87c80-df4c-11eb-9e88-e3dedc088407.png)

**Comment by hrenz** [comment]
Hy Bertrand
all icons are from www.air-rc.comgenerated for X20 Ethos  300x280 256 Colours

 We have known each other since the beginning of openTX. open9x 
For your information:
"We" are the group from Germany that searched for the errors in the frsky V1 version for over 1 year 
and had to convince frsky that there are errors there.
Frsky also constantly claimed that there were no errors in the v1 version.
And also now in the V2 version the telemetry errors come from the receiver software.
in the processing of the SPORT sensors, a timing-probelm  
and evaluation in ACCST/ACCESS ISRM 
the reaction of the frsky developers is again like this

mfgH.Renz
 
-----Ursprüngliche Mitteilung-----
Von: Bertrand Songis @ FrSky ***@***.***>
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: hrenz ***@***.***>; Author ***@***.***>
Verschickt: Mi, 7. Jul. 2021 7:13
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Edit model, change model image, it is displayed in the model selection, but no longer in the main display (#596)

@jreis1 please upload your bitmap here, I will check when I can, what is the size of your bitmap? please take into account that a bitmap of 800x600, 4 bytes per pixel is very big compared to the available RAM on all radios.—

**Comment by jreis1** [comment]
> @jreis1 please upload your bitmap here, I will check when I can, what is the size of your bitmap? please take into account that a bitmap of 800x600, 4 bytes per pixel is very big compared to the available RAM on all radios.

forget my comment. Mine is working all right with several custom made PNGs.

**Comment by hrenz** [comment]
Hy,
 my icon display also worked until i wanted to change the icon.
Since then, the icon for this modell is only displayed in the model selection, but no longer in the main screen.
 
-----Ursprüngliche Mitteilung-----
Von: jreis1 ***@***.***>
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: hrenz ***@***.***>; Author ***@***.***>
Verschickt: Mi, 7. Jul. 2021 19:35
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Edit model, change model image, it is displayed in the model selection, but no longer in the main display (#596)


@jreis1 please upload your bitmap here, I will check when I can, what is the size of your bitmap? please take into account that a bitmap of 800x600, 4 bytes per pixel is very big compared to the available RAM on all radios.
forget my comment. Mine is working all right with several custom made PNGs.—

**Comment by MIKE-DAILEY** [comment]
It would be helpful if you could post a screen image of the main screen from Configure Screens.

**Comment by hrenz** [comment]
ok main screen , config screen
not particularly adjusted

![screenshot-2021-07-07-71562](https://user-images.githubusercontent.com/6217896/124806424-f7a98780-df5c-11eb-8b41-9cc166ca0aa6.jpg)

**Comment by MIKE-DAILEY** [comment]
You have the GPS Map selected rather than the Model image.

**Comment by hrenz** [comment]
GPS-Map ?

Ah i see
change widget, back to Modellscreen,

ok

thanks

**Comment by bsongis-frsky** [comment]
Issue on the chair to keyboard connection
:)
