### ISSUE TITLE
Bug in free mixing

### ISSUE THREAD

**Issue by Brianchon76** [FrSkyRC/ETHOS-Feedback-Community#599]
Hello
I have two problems in my X20.
First there is no delay in flight mode, for example in helicopter it is very important to have a smooth transition between hovering and aerobatic mode.(it's better for the mechanics) 
My second problem is on the free mixer , I have set up two delay up and down. When I use flap one, there is a delay only one time and after the delay disappeared.
Please can you help me.

**Comment by Hobby4life** [comment]
Also mentioned here: #125 and #93

Again I agree, a transition delay/speed should be available for flightmodes

**Comment by Brianchon76** [comment]
To  explain, it's a freeixing in flap to elevator.

**Comment by bsongis-frsky** [comment]
1st problem is a feature request
2nd problem, would you please explain what is your mix? There is no delay, just "Slow"

**Comment by Brianchon76** [comment]
Hello 

Thank you for your reply. 
About the mix, I found the problem. 
I made a free mix flap/elev with slow in each flight mode. The slow diseapered because I didn't select in the mix  all the flight mode.
Now I have no problème. 

Best regards 

Pascal 

⁣Pascal Brianchon
Président de la Ligue d'Aeromodelisme de Normandie 
Vice président de L' AMCH 

Télécharger BlueMail pour Android ​

Le 19 juil. 2021 à 13:46, à 13:46, "Bertrand Songis @ FrSky" ***@***.***> a écrit:

**Comment by FBarrao** [comment]
Yes, please, no so important for planes, ( you just have an abrupt change of trim), but yesterday a friend of mine broke the main gear on a helicopter just changing from autorotation to one idle up mode, due to the lack of slow down between flight modes. 
![IMG_20210822_191117](https://user-images.githubusercontent.com/88581380/130405466-d8603409-3be7-42bd-8aad-62f5adfe9ae8.jpg)

**Comment by Hobby4life** [comment]
This is why we still hammer on speed and delay on Flightmode transitions!!. Please implement this.
