### ISSUE TITLE
Willing to test and provide feedback

### ISSUE THREAD

**Issue by ZeekWorld** [FrSkyRC/ETHOS-Feedback-Community#6]
Hello, 
I am willing to test and provide feedback for the Ethos OS on my X10S Express but can't find the Beta application anywhere.
Please let me know how can I apply, thank you in advance.

**Comment by Adelaxie** [comment]
The first version of firmware for X10 will be released in days. Please pay attention to the link below:
http://ethos.frsky-rc.com/

**Comment by ZeekWorld** [comment]
Thanks

**Comment by Adelaxie** [comment]
thanks,donot hesitate to create new issues here if you have found any  .
