### ISSUE TITLE
Using T5 as Volume control - X10S + ISRM

### ISSUE THREAD

**Issue by BobCotsford** [FrSkyRC/ETHOS-Feedback-Community#60]
Using T5 as a control on the System - Sounds volume function gives only a limited range of control.  Could this be set to give a full range 0-100% on volume?

**Comment by bsongis-frsky** [comment]
I just checked if you toggle the "Extended Trims" checkbox, you will get a full range on volume

**Comment by BobCotsford** [comment]
Many thanks for checking that Bertrand. 

Bob Cotsford 

    On Monday, 12 April 2021, 09:49:04 BST, Bertrand Songis @ FrSky ***@***.***> wrote:  
 
 


I just checked if you toggle the "Extended Trims" checkbox, you will get a full range on volume
