### ISSUE TITLE
Live chart widget

### ISSUE THREAD

**Issue by federicobelfi** [FrSkyRC/ETHOS-Feedback-Community#603]
As possible on X10 (openTX), it would be really appreciated the development live chart capable to show one or more variables (as example altimeter)

**Comment by federicobelfi** [comment]
Also requested as part of #592

**Comment by Hobby4life** [comment]
Thats what I meant with: Line Graph

**Comment by bsongis-frsky** [comment]
Duplicate

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128697048-3ed0413c-a03c-450a-a0fe-de159fcbe5d9.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128707697-bf0aa541-75fa-482c-8bb0-4774a7aadab0.png)
