### ISSUE TITLE
Precisions on joystick mode

### ISSUE THREAD

**Issue by CMaillette** [FrSkyRC/ETHOS-Feedback-Community#604]
I have seen mentioned in another issue that controllers using ETHOS can enter a usb joystick mode when connected to a computer via usb while powered on, same as OpenTX, but have not seen any information relating to this in docs or guides. 

I am looking for details on how many axes / buttons this provides, be it always the same for anything running ETHOS, or specific to each transmitter model.

**Comment by bsongis-frsky** [comment]
It is common to Ethos on all radios:
- 8 analog channels
- 24 buttons
