### ISSUE TITLE
Model switches before pushing the "yes" confirmation

### ISSUE THREAD

**Issue by OB1-OB2** [FrSkyRC/ETHOS-Feedback-Community#605]
When selecting a new model, clicking on the new model to select it, brings up a confirmation pop-up. It seems like, even before clicking "yes", the model changes to the new one (i.e. as soon as the pop-up comes up). In fact, pushing "no" does not go back to the old model properly.

I'm using 10.10RC1.

**Comment by Hobby4life** [comment]
Duplicate #581
