### ISSUE TITLE
EDIT - throttle source set to elevator by deafult 1.0.9

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#608]
as title. throttle warning goes away when elevator stick is moved to bottom in mode one
EDIT - mode one not working at all, mixer reports incorrectly as if radio is still in mode 2

**Comment by bsongis-frsky** [comment]
I believe this has been fixed in 1.0.10, no?

**Comment by bsongis-frsky** [comment]
It works correctly in 1.0.10, please check RC3 when released
