### ISSUE TITLE
Foreign (Norwegian) character support

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#609]
Working on a Norwegian language translation, I notice that the following Norwegian characters fail to display correctly i Ethos X20 sim 1.0.10:
Æ (Unicode U+00C6) Latin Capital Letter Ae is displayed as Ú (U+00DA) Capital U With Acute.
Ø (Unicode U+00D8) Latin Capital Letter O With Stroke is displayed as è (U+00E8) Small E with Grave.
Å (Unicode U+00C5) Latin Capital Letter A With Ring Above is displayed as Ü (U+00DC) Capital U With Diaeresis.
æ (Unicode U+00E6) Latin Small Letter Ae is displayed as ó (U+00F3) Small O With Acute.

ø (Unicode U+00F8) Latin Small Letter O With Stroke displays correct.
å (Unicode U+00E5) Latin Small Letter A With Ring Above also displays correct.

**Comment by bsongis-frsky** [comment]
Thanks a lot for this detailed list, I will try to add the missing chars in RC3

**Comment by bsongis-frsky** [comment]
Ready for RC3
