### ISSUE TITLE
OTA update r9 mx doesn't work

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#610]
Wenn i start the update it go to binding.
![Uploading 20210709_163611.jpg…]()

**Comment by MichaelETHOS** [comment]
![20210709_163611](https://user-images.githubusercontent.com/84266308/125116644-5271e900-e0ed-11eb-9e5c-563f2c468bdb.jpg)

**Comment by loetefix** [comment]
Only the "bind" message seems to be wrong. If you turn on the RX and choose the receiver it start updating.

**Comment by bsongis-frsky** [comment]
@WismyYao I think he is right, we need to have another message, it's confusing for the user

**Comment by michifpv** [comment]
I had the same problem.


Another message would be good. Maybe for the update please reconnect the RX.

The update via OTA worked, only after the update the red led was on and the RX was no longer bound.

I tried to register the receiver and to bind what no longer worked. Then I did the update via cable and I was able to register and bind immediately.

**Comment by Joetrin** [comment]
Similar problem happens when trying to update OTA with the R9sx

Turn on TX and rx, go to file manager
Select the firmware you want to update
Then select update by external OTA

The Bind message comes up instead of saying "waiting for RX".
