### ISSUE TITLE
Request: Log widget (as the time log) to store numbers or text 

### ISSUE THREAD

**Issue by federicobelfi** [FrSkyRC/ETHOS-Feedback-Community#611]
It would be very much appreciated if the timer log widget will be proposed also for other variables such as telemetry data only when a trigger is activated.

Use example:
F3K - Live logging of climbing time, reached altitude, flight time. Now I can only log flight time and climbing time.

![screenshot-2021-07-09-70664](https://user-images.githubusercontent.com/13049718/125117417-826dbc00-e0ee-11eb-9e67-2b9f1f73c7b0.png)

Thank you.

**Comment by mawzthefinn** [comment]
This would be another good opportunity for a Lua script
