### ISSUE TITLE
Telemetry Voltage Sensor Mini

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#612]
Tested under several Conditions
-No Cell Voltage readout or 0,0V
-Just Lipo Voltage found if you delete all Sensors

Tested on 2cnd Reciever - same

Discovered after Update to RC- First Startup showed strange lipo cell number count, All Cell Volateges 0,0V
After delete all sensors not possible to find any other values expect "Lipo" which is the total Pack volt.

**Comment by m0p3d** [comment]
Update confirmed this is related to the .10 RC2 flashed back to .9 works

**Comment by bsongis-frsky** [comment]
fixed in RC3

**Comment by m0p3d** [comment]
Please Reopen RC3 - Cells Count still 2147483647

**Comment by bsongis** [comment]
![image](https://user-images.githubusercontent.com/5603504/125740991-682c81a7-cb8f-4b4c-ac79-82cba9729669.png)
![image](https://user-images.githubusercontent.com/5603504/125741004-3f508209-7047-4c2c-ac91-8d2040afed90.png)
