### ISSUE TITLE
Deutsche Übersetzung für Zeiten

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#613]
In der Stoppuhr wird beim Herunterzählen immer noch für z.B. 01:07 "Eins Minute und sieben Sekunde" angesagt.
Richtig wäre doch in diesem Fall "Ein**e** Minute und sieben Sekunde**n**" ?
Vielleicht kann das Jemand auf Englisch besser erklären.

**Comment by loetefix** [comment]
Ok,  On countdown there are played wrong voice files in german.German is a little tricky on that.tomorrow i will create a table how to play the right files in wich case.

**Comment by bsongis-frsky** [comment]
Nobody in the team speaks German, please ask to Andreas @ Engel to help on this issue

**Comment by loetefix** [comment]
Sorry i forgot to explain how to play the right files. Tomorrow i think i can help. I am a little busy at the moment.

**Comment by EngelMT** [comment]
@bsongis-frsky

It is difficult to explain. It is a fault in the wave files. Can be that we have to add a file more. I will check it. Loetefix will make a table about the right files too.

**Comment by loetefix** [comment]
Yes , we need for "one"  an other wav . this evening i will explain it. the easyest way is for one hour , one minute and one second have a own wav. but later this evening i will explain it in detail.

**Comment by EngelMT** [comment]
@bsongis-frsky

I think my sound file was correct and my .txt too. You are probably building this sentence from the "1" and the word "minute". But there is the term "1-minute.wave" which is correct in my language generator. This is position 162 in the text file.

**Comment by Devil-IdT** [comment]
Hallo Andreas, es geht nicht nur um die Minute. 
Auch die Ansage "sieben Sekunde" ist falsch, auch da müsste es "sieben Sekunden" heissen.

**Comment by EngelMT** [comment]
@Devil-IdT O.k. das zeigt, dass Bertrand die Ansagen aus der Zahl und der Übersetzung für Sekunde, Minute etc. zusammenfügt. denn für Sekunden gibt es nicht wie bei Minuten diese Begriffe wie oben beschrieben.

@bsongis-frsky Devil-IdT has found out that the problem does not only occur with minutes, but also with seconds. With seconds, however, we only have the terms item 134 "second" (singular) and item 135 "seconds" (plural). For example, for seven seconds you obviously use the number 7 and the term second. But you should use the number 7 and the term "seconds".

**Comment by loetefix** [comment]
Ok,

the easyest way i think is we adding two wav files: 

1. -->  "eine stunde" --> 1-hour.wav
2. -->  "eine sekunde"--> 1-second.wav

"eine minute"--> 1-minute is allready there.

And then handle like this

IF (hours==1) then
         play 1-hour.wav
  else 
        play value_hour.wav ; // 2.wav ....... 59.wav
        play  hours.wav;
endif;

IF (minutes==1) then
         play 1-minute.wav
  else 
        play value_minute.wav ;
        play  minutes.wav;
endif;

IF (seconds==1) then
         play 1-second.wav
  else 
        play value_second.wav ;
        play  seconds.wav;
endif;

i hope you know what i mean

**Comment by jhammann13** [comment]
Hello Bertram,
the issue in RC6 still exists.
The announcements are still wrong.
When I am told a time it comes:
"Eins Minute und sieben Sekunde"
Correct would be
"**"Eine** Minute und sieben **Sekunden**"

**Comment by Devil-IdT** [comment]
@bsongis-frsky :
Hello Bertrand, what further information do you need to solve the problem?

Greets, Micha

**Comment by bsongis** [comment]
In this list, what are the feminine units?
For now I have setup only "millisekunde", "sekunde", "minute" and "stunde" as feminine

![image](https://user-images.githubusercontent.com/5603504/127434587-25bda289-ade8-4f1f-961e-330dace70141.png)

**Comment by bsongis** [comment]
In this same list:
1) would you please give me the right words, I think they should be translated, i.e. "percent.wav" should be named "prozent.wav"?
2) are there plural filenames missing, i.e. "prozenten.wav"?

Here is the list in text form:
```cpp
const AudioDeTranslation::UnitPrompt AudioDeTranslation::unitsPrompts[UNITS_COUNT] = {
  {nullptr, nullptr, false},
  {"mvolt", "mvolt", false},
  {"volt", "volt", false},
  {"mamp", "mamp", false},
  {"amp", "amp", false},
  {"mah", "mah", false},
  {"ah", "ah", false},
  {"mwatt", "mwatt", false},
  {"watt", "watt", false},
  {"cm", "cm", false},
  {"meter", "meter", false},
  {"foot", "foot", false},
  {"cmps", "cmps", false},
  {"meterps", "meterps", false},
  {"footps", "footps", false},
  {"kph", "kph", false},
  {"mph", "mph", false},
  {"knots", "knots", false},
  {"celsius", "celsius", false},
  {"fahrenheit", "fahrenheit", false},
  {"prozent", "prozent", false},
  {"millisekunde", "millisekunden", true},
  {"sekunde", "sekunden", true},
  {"minute", "minuten", true},
  {"stunde", "stunden", true},
  {"db", "db", false},
  {"g", "g", false},
  {"degree", "degree", false},
  {"ml", "ml", false},
  {"mlpm", "mlpm", false},
};
```

**Comment by bsongis** [comment]
Which numbers need to have a feminine form, i.e. "eine stunde" : are there other numbers than "eine" which have a feminine form auf Deutsch?

**Comment by bsongis-frsky** [comment]
Here is the result for the first fixes:

Play (Timer1 = 01:49)

```
144958 playFile('/audio/de/system/eine.wav', flags=0, id=0)
144958 playFile('/audio/de/system/minute.wav', flags=0, id=0)
144958 playFile('/audio/de/system/und.wav', flags=0, id=0)
144958 playFile('/audio/de/system/49.wav', flags=0, id=0)
144958 playFile('/audio/de/system/sekunden.wav', flags=0, id=0)
```

**Comment by bsongis-frsky** [comment]
For reference here are the units translations:

```
mvolt.wav,milli volt,
volt.wav,volt,
mamp.wav,milli ampere,
amp.wav,ampere,
mah.wav,Milliamperestunden,
ah.wav,Amperestunden,
watt.wav,Watt,
mwatt.wav,Millli Watt,
cm.wav,Zentimeter,
meter.wav,Meter,
km.wav,Kilometer,
foot.wav,Fuß,
mile.wav,Meile,
cmps.wav,Zentimeter pro Sekunde,
meterps.wav,Meter pro Sekunde,
kph.wav,Kilometer pro Stunde,
footps.wav,Fuß pro Sekunde,
mph.wav,Meile pro Stunde,
celsius.wav,Grad Celsius,
fahrenheit.wav,Grad Fahrenheit,
prozent.wav,Prozent,
db.wav,db,
millisekunde.wav,Milli Sekunde,
millisekunden.wav,Milli Sekunden,
sekunde.wav,Sekunde,
sekunden.wav,Sekunden,
minute.wav,Minute,
minuten.wav,Minuten,
stunde.wav,Stunde,
stunden.wav,Stunden,
```

**Comment by EngelMT** [comment]
I think we have to add the following too.

Milliamperestunde (Excample> "zehn Milliamperestunden" but "eine Milliamperestunde")
Amperestunde

I hope that will be all. But let us wait for comments of the other guys.

There is another special form in connection with the units. In German, for example, we say "ein Volt". "ein" means 1, but we say, for example, "eine Milliamperestunde".

**Comment by bsongis-frsky** [comment]
That's why I ask here which unit is feminine...
I understand that milliamperestunde is feminine, but then I guess that amperestunde will be feminine as well?
I need to know all units which are feminine

**Comment by bsongis-frsky** [comment]
```
mah.wav,Milliamperestunde,
mahs.wav,Milliamperestunden,
ah.wav,Amperestunde,
ahs.wav,Amperestunden,
```

**Comment by EngelMT** [comment]
"I understand that milliamperestunde is feminine, but then I guess that amperestunde will be feminine as well?"

You are right it is feminine. But we must also note that, for example, "ampere-hour" is singular and "ampere-hours" plural.

In your list we found "Amperestunden" (Plural) and I add the Singular too. The same with Milliamperestunden.

I check your list and can not find any more units we need in Singular and Plural. But it could be that I can't see the wood for the trees. Maybe the others will find something.

**Comment by bsongis-frsky** [comment]
I have added the singular "ah.wav" and "mah.wav" myself one minute ago :)

**Comment by Devil-IdT** [comment]
> For reference here are the units translations:
> 
> ```
> mvolt.wav,milli volt,
> volt.wav,volt,
> mamp.wav,milli ampere,
> amp.wav,ampere,
> mah.wav,Milliamperestunden,
> ah.wav,Amperestunden,
> watt.wav,Watt,
> mwatt.wav,Millli Watt,
> cm.wav,Zentimeter,
> meter.wav,Meter,
> km.wav,Kilometer,
> foot.wav,Fuß,
> mile.wav,Meile,
> cmps.wav,Zentimeter pro Sekunde,
> meterps.wav,Meter pro Sekunde,
> kph.wav,Kilometer pro Stunde,
> footps.wav,Fuß pro Sekunde,
> mph.wav,Meile pro Stunde,
> celsius.wav,Grad Celsius,
> fahrenheit.wav,Grad Fahrenheit,
> prozent.wav,Prozent,
> db.wav,db,
> millisekunde.wav,Milli Sekunde,
> millisekunden.wav,Milli Sekunden,
> sekunde.wav,Sekunde,
> sekunden.wav,Sekunden,
> minute.wav,Minute,
> minuten.wav,Minuten,
> stunde.wav,Stunde,
> stunden.wav,Stunden,
> ```

Hello Bertrand, there is still missing (for values >1):
miles.wav,Meilen 
msph.wav, Meilen pro Stunde


Greets,Micha

**Comment by bsongis-frsky** [comment]
msph.wav added now
"mile.wav" is still not used, nobody asked for it until now

**Comment by Devil-IdT** [comment]
> "mile.wav" is still not used, nobody asked for it until now

I only put "miles.wav" in because "mile.wav" was on your list

**Comment by EngelMT** [comment]
Sorry, but it seems as th job is not done complete.

Now with 1.0.10 fnal release we get for 1:07 Min ""Eins Minute und sieben Sekunden". It must be "Eine Minute und sieben Sekunden".

If it is the same with other announcements I have not tried yet. But I think so.

**Comment by bsongis-frsky** [comment]
I just checked, here is what should be played:

```
097767 [de] playNumber(1, unit=m, precision=0)
097767 playFile('/audio/de/system/eine.wav', flags=0, id=0)
097767 playFile('/audio/de/system/minute.wav', flags=0, id=0)
097767 playFile('/audio/de/system/und.wav', flags=0, id=0)
097767 [de] playNumber(7, unit=S, precision=0)
097767 playFile('/audio/de/system/7.wav', flags=0, id=0)
097767 playFile('/audio/de/system/sekunden.wav', flags=0, id=0)
```

**Comment by bsongis-frsky** [comment]
On the radio too, it works.
I get "Eine Minute und sieben Sekunden"
So I suppose either your firmware or your SD is not correctly updated

**Comment by EngelMT** [comment]
O.k. will check it. Can it be that I have to delete the radio.bin?

**Comment by EngelMT** [comment]
After flash the card again it works. Thanks!
