### ISSUE TITLE
V 1.0.10 Major ERROR

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#614]
As an F5J type glider flyer, under v 1.0.9 I had created a CROW mix using the left Vertical trim as the input for Elevator trim to the application of Crow. This worked a treat as an easy method to adjust elevator compensation. 
However - Just upgraded to v 1.0.10 and all looked good UNTIL I apllied Crow and the glider stood on it's tail. Luckily I was able to land without Crow (Just). On getting home and comparing the versions the mix was changed by v1.0.10 to have Elevator as the input to (elevator), not the Left Trim (removing ALL compensation). That could have cost me a very expensive model! So have reverted back to v1.0.9 for now. 
The more I now question this issue - I wonder what else has it changed?
Regards,
Ken

**Comment by m0p3d** [comment]
Somelike this happened to ne yesterday and nearly list my nan xplorer. Mit Sure If crow was random triggered or If flaps to aileron Mix didnt Work correctly nur because of the already reported Lupo Vorlage Sensor Problem with .10 rc2 i moved Back to 09 and reprogram all Models. Btw moving Back ends with already Programmed Models are not accessable

**Comment by KenLong51** [comment]
By coincidence, I was also flying a Nan Explorer! Before I installed v1.0.10 I had backed-up everything on SD card, so copied it all back, along with the v 1.0.9 firmware file and re-ran the bootloader. All OK now. (on v 1.0.9)

**Comment by KenLong51** [comment]
This issue is with Candidate 2, I have not tried Candidate 1.

**Comment by bsongis-frsky** [comment]
@KenLong51 Would you please share your model (from 1.0.9) which is badly converted to 1.0.10?

**Comment by KenLong51** [comment]
Hi, I have tried to attach the 2 model files, but this system does not support that file type. Any ideas how I can get them to you please?

**Comment by Hobby4life** [comment]
zip them, and then drop the zip file here

**Comment by KenLong51** [comment]
[Models For GitHub.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6796847/Models.For.GitHub.zip)
Hi, These are the 2 model files you asked for. If you look in the Crow Mix you will see channel 5 is the elevator compensation. In v1.0.9 the input to that is 'Left Vertical Trim' and in v1.0.10 you will see it has been changed to 'Elevator'.
Regards,
Ken

**Comment by bsongis-frsky** [comment]
1.0.9 
![image](https://user-images.githubusercontent.com/50834778/125291807-18d5f380-e322-11eb-8818-b8ccb40464a3.png)

**Comment by bsongis-frsky** [comment]
Imported to 1.0.10RC2 with Stick Mode 2 => BAD (It was Trim Elevator)

Imported to 1.0.10RC3 with Stick Mode 2

![image](https://user-images.githubusercontent.com/50834778/125302020-ddd8bd80-e32b-11eb-9508-aecc7e925870.png)

**Comment by KenLong51** [comment]
Please re-open this, you are not looking at the correct mix! I statedthat it was the CROW mix NOT Mot!

**Comment by bsongis-frsky** [comment]
The CROW mix has Throttle as input, not a Trim!

**Comment by bsongis-frsky** [comment]
The discussion should happen here. CROW mix has Throttle as input, right or wrong?

**Comment by KenLong51** [comment]
Yes the Crow does have the Throttle as input. BUT if you open the Crow mix and go to channel 5 you will see under v1.0.9 channel 5's input is the 'Left Virtical Trim'. When v1.0.10 (2) is loaded that 'Left Vertical Trim changes to 'Elevator'.

**Comment by bsongis-frsky** [comment]
Please look at the first screenshot I posted above. Your mix is named "Mot Elev Comp".

Then read again what I wrote when I fixed the issue:
RC2 => KO
RC3 => OK, look at the screenshot, the Trim should be right as you want to reuse the Throttle Trim for your mix

**Comment by KenLong51** [comment]
Sorry, but why do you keep looking at the Mot Elev Comp mix? That is not the one relating to the problem. That allows me to adjust the Elevator compensation when the motor is turned on (by Switch A).
The CROW mix (channel 5 within) is so that I can adjust the Elevator trim when Crow Brakes are applied by the Throttle stick.
Would you like some screen shots of the mix?

**Comment by bsongis-frsky** [comment]
It's fixed the same way everywhere:

![image](https://user-images.githubusercontent.com/50834778/125317608-6d389d80-e339-11eb-8867-501aae060803.png)

**Comment by KenLong51** [comment]
I have attached 2 screen shots in this zip file.
The problem is also compounded because 'Left Vertical trim' has changed to Throttle Trim.
So I appreciate that I can make v 1.0.10 (2) to work, but but I am going to have to change every model I have that uses what was 'Left Vertical' to 'Throttle Trim'. a. this is annoying and b. could have been very expensive.
[Crow Mix Screen Shots.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6802939/Crow.Mix.Screen.Shots.zip)

**Comment by bsongis-frsky** [comment]
The conversion does everything in your place automatically. It's now converted right in RC3 coming soon.

**Comment by KenLong51** [comment]
Just noticed - How have you got 'Trim Throttle' on your screen and mine on v 1.0.10 just shows 'Throttle'?

**Comment by KenLong51** [comment]
Ah. re RC3, should I stay on v 1.0.9 till it is released please?

**Comment by bsongis-frsky** [comment]
Of course you have to stay on 1.0.9
Please keep in mind that RC means Release Candidate, they are there for tests purpose, nobody is perfect and despite we have automatic non regression tests, it's very possible we introduce new bugs.

**Comment by KenLong51** [comment]
OK , I'll go back to V1.0.9 untill the next one is released.
Many thanks,
Ken

**Comment by bsongis-frsky** [comment]
By opening this issue you helped the team, but it's important not to trust Release Candidates, especially with so many new features!

**Comment by KenLong51** [comment]
That's fine. I worked in IT for some 40 years, so I fully appreciate all that goes into new development and testing and if I can assist that is OK.
Regards,
