### ISSUE TITLE
V 1.010.2 logic switch GPS Speed X value cannot be edited

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#615]
I wanted to program a logic switch for a speed warning. I chose the GPS sensor as source A. Unfortunately the value X cannot be edited. i used ethos 1.010.candidate 2

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/125241690-0fca2f80-e2ec-11eb-9479-5eab0fdcae72.png)

**Comment by bsongis-frsky** [comment]
The value X will keep the precision and unit of the sensor, it allows to change at any moment your precision without reprogramming your logic switch.

With the new keyboard you can change the step of the rotary encoder. I will try to adjust the default step automatically.
