### ISSUE TITLE
German Translation Power of with RX on

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#616]
Hello everybody,
if you want to switch off the transmitter and the receiver is still switched on, the warning message comes in English.
"RX is still ON, turn off the transmitter?"
The transmitter is set to German.
It should then read (suggestion):
"Empfänger noch eingeschaltet, Sender ausschalten?"

Greets, Micha

**Comment by bsongis-frsky** [comment]
It has been translated to "Empfänger noch eingeschaltet, Sender ausschalten?"

**Comment by Devil-IdT** [comment]
Works perfect, thx for the quick work.
