### ISSUE TITLE
1.0.10 candidate 2  Flaw with timer & telemetry 

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#617]
Hi,
Just uploaded the pre release.
Issue straight outta the box for the x20 -

1) Timer is not working. On the main screen when i select one of the widgets as a timer, the timer edit screen has all the details however the  following issues exist -
a) Timer remains deactivated no matter what. 
b) Throttle percentage does not have option to select the level after which timer is to get activated.
c) when the timer activation switch is selected the timer does not turn on.

2) Telemetry -
a) When the Mlvss lipo sensor is connected the lipo cell voltages appear just fine.
b) when the delete sensor button is engaged the values disappear & even if discover new sensor is engaged the cell values do not appear.
c) Issue gets resolved only if the software is reloaded. 

Other than the above everything else looks great.

cheers
Ravi

**Comment by bsongis-frsky** [comment]
Anybody else has seen those issues? Especially the Timer one?

**Comment by bsongis-frsky** [comment]
Is it possible you explain a little bit more your Timer issue?

**Comment by ravikoth** [comment]
Hi,
Just flashed the firmware & the timer works just fine.
have another issue though.
the telemetry screen shows the various recvr related telemetry values.
however when i connect the MLVSS lipo sensor the lipo voltages do not show up.
i’ve tried this with a few access recvrs & the same issue.
if i disconnect the sensor the radio shouts sensor lost, but no lipo voltages show up.
i had the same problem earlier but when i downshifted to 1.07 the values showed up.
any idea whats the issue?
