### ISSUE TITLE
Inaccurate ADC2 sensor in Telemetry

### ISSUE THREAD

**Issue by Paolotandemx20s** [FrSkyRC/ETHOS-Feedback-Community#619]
Run Candidate 1.0.10 rc2 on my x20s, seems to work very well, only one problem seen for adc2 sensor, range  too approximate, my test on 3s lipo, multimeter score 12.26v, adc2 sensor range 11.8 to 13 volts very hopping, even after setting both ratio and offset many times. I also recommend moving the value to a lower position or raising the ratio and offset on the page because now you have to do a blind calibration.

**Comment by bsongis-frsky** [comment]
The sensor value itself, I am afraid it's not related to Ethos
