### ISSUE TITLE
GasSuite Adjust RPM

### ISSUE THREAD

**Issue by ramones75** [FrSkyRC/ETHOS-Feedback-Community#621]
Under OTX there is a multiplier for RPM to adjust the value.
In Ethos I do not find this.

**Comment by bsongis-frsky** [comment]
Duplicate issue, already fixed in 1.0.10
Please try to find already opened issue before opening new ones

**Comment by ramones75** [comment]
it is not fixed in 1.0.10.
there is, for the GasSuite, no possibility to create a
multiplier.
or please tell me where to do it?

**Comment by bsongis-frsky** [comment]
what is your sensor?

**Comment by bsongis-frsky** [comment]
Will be in RC4
