### ISSUE TITLE
Bug: v1.0.10 RC3 X20S, Trip and Distance

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#622]
With the latest v1.0.10 RC3 release.

Calculated sensor Distance is not moving.

And Calculated sensor Trip is very exited, with GPS not moving for 10 minutes. I already have a trip of 70km :-)

**Comment by bsongis-frsky** [comment]
@Nicholas-Luoyi I suspect you forgot that precision is 1/100m/s ...
