### ISSUE TITLE
USB connection

### ISSUE THREAD

**Issue by cperedamas** [FrSkyRC/ETHOS-Feedback-Community#623]
The radio is not recognized by the PC when connecting via a USB hub.  Works fine when connected directly to the PC.  Ethos 1.0.9 FCC, 2.1.8

**Comment by jreis1** [comment]
I'm 90% sure this is related with your UBSB hub, that typically splits the power to all the other ports. I believe this is not an Ethos problem.

**Comment by bsongis-frsky** [comment]
I use a hub myself!
