### ISSUE TITLE
1.0.10 RC3 Neuron S ESC does not display RPM  on X20S

### ISSUE THREAD

**Issue by bob-stan** [FrSkyRC/ETHOS-Feedback-Community#626]

**Comment by bob-stan** [comment]
While it worked in 1.0.9 it doesn't in 1.0.10 RC3. Shows 0.

**Comment by Cipta-de** [comment]
Do you have deleted the rpm sensor and rediscovered?

**Comment by bob-stan** [comment]
I had not.  Doing that has solved my problem. T%hank you.

Bob Stan
 
***@***.*** ***@***.***>
