### ISSUE TITLE
MLVSS lipo sensor doesn’t show up 1.0.10 candidate 3

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#628]
Hi,
Just flashed the firmware & the timer works just fine.
have another issue though.
the telemetry screen shows the various recvr related telemetry values.
however when i connect the MLVSS lipo sensor the lipo voltages do not show up.
i’ve tried this with a few access recvrs & the same issue.
if i disconnect the sensor the radio shouts sensor lost, but no lipo voltages show up.
i had the same problem earlier but when i downshifted to 1.07 the values showed up.
any idea whats the issue?

_Originally posted by @ravikoth in https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/617#issuecomment-879251587_

**Comment by Hobby4life** [comment]
I have tried a MLVSS on a R10 Pro receiver with X20S, and got a readout.
Did you tried to re-discover it?

**Comment by bsongis-frsky** [comment]
Rediscover is needed

**Comment by ravikoth** [comment]
Why is this issue closed.
the same persists.
this is a major bug in 1.0.10 candidate 3

**Comment by ravikoth** [comment]
> Rediscover is needed

sir,
Why is this issue closed.
the same persists.
this is a major bug in 1.0.10 candidate 3
