### ISSUE TITLE
ADC2 and ADC4 fail with 1.0.10RC3

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#629]
Hello, since 1.0.10RC3 the voltage sensor ADC2 (ID 1A F103) of my R6 no longer works.
In 1.0.10RC2 I could still see the voltage there, now the sensor shows ---.
A new binding of the receiver and a new search for sensors remained unsuccessful.
If I write the 1.0.10RC2 back into my X10S, the ADC2 sensor works again.

I have the same problem with an R-XSR on an F722 ZEUS FC.
The ADC4 voltage sensor (ID 00 0910) no longer works there and only delivers red ---.

Can it be the same Issue like #628 ?
Greets Micha

**Comment by bsongis-frsky** [comment]
Did you try to remove this sensor (only this one) and discover again?

**Comment by bsongis-frsky** [comment]
Ah, max voltage has been fixed for RC4

**Comment by Devil-IdT** [comment]
> Did you try to remove this sensor (only this one) and discover again?

Yes, of course. ;)
