### ISSUE TITLE
Feature Request: Temporary assign an output to a pot

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#63]
When setting up a model, I usually start with setting up my PPM centres and endpoints or even balancing servos with curves, starting with assigning each channel to a pot.

It would be very nice, if I could temporarily toggle an output to be fed from a Pot when in the Output Edit menu, just for the moment of setup. Not a critical request, but I think that would make the setup a bit more straightforward, not having to go back and forth between mixer and outputs.

**Comment by bsongis-frsky** [comment]
I think the way to go in Ethos is very quick:
1) You start with a Free Mix, assign your pot to the first channel
2) In the same window, you press [ENTER LONG] (shortcut to outputs)
3) If needed you click on the channel settings to make your changes on channel level
4) You press EXIT to return to the original Free Mix, no need to go through the MODEL Menu, it is very quick
