### ISSUE TITLE
Enhancement: GPS Widget numeric keypad

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#630]
Now the GPS widget is getting shape.
It would be nice to have a Numeric keypad to enter the coordinates.
The scroll rate now is already a great step forwards, but still for this a numeric keypad entry would be nicer.

**Comment by bsongis-frsky** [comment]
Like the date / time

**Comment by Hobby4life** [comment]
Yes like date and time, even better!

Or a file readout,, 
Next to the map file, a file with the exact same name as map image name.
This way you can prepare a bunch of maps, without reentering coordinates everytime in every model.

for example.

amsterdam.png
amstterdam.gps

.gps file contains coordinates

Makes it it really easy for entering. and more important.. backing up.

**Comment by gjvo** [comment]
I tried to use the GPS Widget and put in the coordinates but most of the time if you activate te latitude or longitude input screen and than use the scroll button it goes 1 second back, so 89"59"59"9 and than it just stops.
If i use te min-max or + and - buttons, sometimes it works, most of the time not.
And if i want to go from 51 to 52 degrees, than it jumps from 51 to 53 degree.
So... the problem is not only the numeric keyboard but also an error in the widget i think.

**Comment by Hobby4life** [comment]
For best editting of the coordinates for now. first edit the coordinates themselves before selecting a map.
This speeds up dialing in.
Use the step slider on the bottom to increase/decrease dial speed.

**Comment by Jamest95max** [comment]
> For best editting of the coordinates for now. first edit the coordinates themselves before selecting a map.
> This speeds up dialing in.
> Use the step slider on the bottom to increase/decrease dial speed.

At the moment my slider dial is used for volume and cannot figure how to set it so I can use it for increasing coordinate input step can you or someone help please

**Comment by Hobby4life** [comment]
> > For best editting of the coordinates for now. first edit the coordinates themselves before selecting a map.
> > This speeds up dialing in.
> > Use the step slider on the bottom to increase/decrease dial speed.
> 
> At the moment my slider dial is used for volume and cannot figure how to set it so I can use it for increasing coordinate input step can you or someone help please

The step slider is the slider on the display at the bottom when editting values... not the physical slider on the radio.

**Comment by Jamest95max** [comment]
![16296345823018241568963178427964](https://user-images.githubusercontent.com/76268710/130354848-71af0536-75a6-4850-b32e-f24a5b6c5d43.jpg)
Now I see why I'm struggling, there is no slider on my screen??

**Comment by MIKE-DAILEY** [comment]
Need to update your Flash bitmaps.

**Comment by Jamest95max** [comment]
Thankyou I thought I had done but perhaps not, will report back.

**Comment by Hobby4life** [comment]
> Thankyou I thought I had done but perhaps not, will report back.

Internal flash bitmaps, not the SD flash bitmaps.

The small 8mb drive when connected to usb.

**Comment by Jamest95max** [comment]
Oh that's what I've assumed wrong, thanks hobby4life

**Comment by Jamest95max** [comment]
> > Thankyou I thought I had done but perhaps not, will report back.
> 
> Internal flash bitmaps, not the SD flash bitmaps.
> 
> The small 8mb drive when connected to usb.

That did the trick thankyou, I did however end up doing this on my Linux laptop took no time at all whereas windows took 2 hours and at said another 4.5 hours to go, whereas Linux did this in minutes, could be my windows computer but its spec is good

**Comment by MIKE-DAILEY** [comment]
That is odd.  My Windows 10 laptop updates the Flash bitmaps very fast.

**Comment by Jamest95max** [comment]
> That is odd. My Windows 10 laptop updates the Flash bitmaps very fast.

It's probably my computer, even though the spec is good it does have a lot of number crunching programs probably some running in background

![Uploading IMG_20210822_161750.jpg…]()

**Comment by Jamest95max** [comment]
![Screenshot_20210822_204048_com android gallery3d](https://user-images.githubusercontent.com/76268710/130368011-fba2817b-a425-4e7b-932e-ad52ee3685fe.jpg)

It's probably my computer, even though the spec is good it does have a lot of number crunching programs probably some running in background

**Comment by Jedsters** [comment]
> Yes like date and time, even better!
> 
> Or a file readout,, Next to the map file, a file with the exact same name as map image name. This way you can prepare a bunch of maps, without reentering coordinates everytime in every model.
> 
> for example.
> 
> amsterdam.png amsterdam.gps
> 
> .gps file contains coordinates if the file is there.. it will read it out.,. if not there you have to enter it manually and creates a .gps file.
> 
> Makes it it really easy for entering. and more important.. backing up.

What format is the .GPS in please?
