### ISSUE TITLE
Release 1.0.10 Kandidat 3 hat alle Modelle gelöscht und die Fernsteuerung in den Emerency mode befördert.

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#631]
Vorsicht beim Firmware update auf 1.0.10 Kandidat 3, hier bei sind meine ganzen Einstellungen und Modelle verloren gegangen.
Zum glück hatte ich ein Backup auf dem PC und konnte somit wieder 1.0.10 Kandidat 2 flaschen damit ich die Fernsteuerung wieder nutzen kann.

**Comment by Ceeb182** [comment]
Please write in English so that international teams can understand. Thank you in advance.

**Comment by loetefix** [comment]
i will translate

he wrote:
be carefully if you update to 1.0.10 RC3 . i lost all my settings and models.luckily i had a backup and could return to rc2.

**Comment by Hobby4life** [comment]
I gues this has nothing to do with the firmware update.. but a corruption on the SD card.
I have seen SD corruptions when not properly unmouting SD cards before disconnecting usb from PC.

**Comment by AlwinHaas** [comment]
Hello, my SD Card is OK. With Release 1.0.10 Kandidat 2 the TX work normal with Kandidat 3 it make a lot of Problems. The Models I can't open it. And it came a Problem at the Screen.

**Comment by bsongis-frsky** [comment]
Please share one of your models you cannot open anymore with RC3 so that we can try to reproduce the issue

**Comment by bsongis-frsky** [comment]
I have got no report like this, please help by providing the model(s) you cannot load (you will have to zip, then paste it in the issue)
Thanks

**Comment by bsongis-frsky** [comment]
If no new information I will close this issue tomorrow

**Comment by AlwinHaas** [comment]
Hallo, ok you can close. Bye Alwin-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 19.07.21, 10:27 schrieb "Bertrand Songis @ FrSky" ***@***.***>:

   
  If no new information I will close this issue tomorrow
