### ISSUE TITLE
MLVSS sensor doesn’t work in 1.0.10 candidate 3, works perfectly in 1.0.9

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#633]
Hi,
the mlvss lipo sensor does not show the voltages.
the recvr telemetry shows up just fine.
when i “rediscover “ the sensors its the same thing.
recvr related telemetry shows up but the lipo voltages dont.
same issue with all the archer recvrs i have on hand.

Today i installed the 1.0.9 firmware & everything is working perfectly.

cheers

**Comment by Hobby4life** [comment]
Transmitter?

**Comment by ravikoth** [comment]
Frsky X20

**Comment by NMO81** [comment]
It is working for me but it seems that they now just show only the total voltage, the individual cell voltages are gone, I have read somewhere that they updated it to only one telemetry device but now only total voltage is available, no individual cell voltage or cell count.

**Comment by NMO81** [comment]
I retested the setup with 3 X MLVSS connected to 1 Archer SR6 receiver:

![IMG_20210715_005256](https://user-images.githubusercontent.com/85587485/125703222-382afa26-2ccd-4f1a-8064-7d32aed7e35c.jpg)
![IMG_20210715_005355](https://user-images.githubusercontent.com/85587485/125703223-5a1b5bfc-9444-4cdf-b1dc-422c8fef5086.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/125742210-e5ba9a83-e43d-400d-8b06-c5dac2579e3b.png)
![image](https://user-images.githubusercontent.com/50834778/125742229-db9ff77b-6da4-42f4-aa98-ff93636201f1.png)

**Comment by NMO81** [comment]
Ok, thanks for the tip, it is a LONG PRESS on the Source setting that pop this options menu up.
