### ISSUE TITLE
Cell count and source Lipo sensor

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#638]
Neither the number of cells is displayed nor can a source be selected in the consumption calculation. I think that this already worked with the 1.1.10 C1 or C2!

**Comment by bsongis-frsky** [comment]
I would need to know how you calculate a consumption from a Voltage value

**Comment by Hobby4life** [comment]
He is referring to 2 different issues bertrand.

1. "Neither the number of cells is displayed" 
2. "nor can a source be selected in the consumption calculation"

**Comment by EngelMT** [comment]
You are right. I need a current sensor. My fault. But the Cell count is not displayed too.

**Comment by bsongis-frsky** [comment]
You should be able to display the cells count, it's an option of the source you are trying to display

**Comment by Devil-IdT** [comment]
My cells count since RC3 is 2.147.483.647, connected is a 6S Lipo.
Should i change the Battery? ;)
