### ISSUE TITLE
Can't adjust gains of a S6R receiver

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#639]
X20, 1.0.10 RC3 FCC firmware.

Can't adjust gains of a S6R receiver. It will read the settings, and allows me to edit them, but will not save them back to receiver. Worked fine with release candidate 2. 

See video below.

https://www.dropbox.com/s/e1rrar703svc5g9/IMG_1521.MOV?dl=0

**Comment by bsongis-frsky** [comment]
Fixed in RC4
