### ISSUE TITLE
expo bug

### ISSUE THREAD

**Issue by profilebroken** [FrSkyRC/ETHOS-Feedback-Community#64]
X10S on ETHOS 1.0.1.  The mixer expo curve works correctly when the weight is set to a value.  However, when the expo curve weight is set using a channel output value, the expo curve changes to something different.  I've attached some screenshots.
![screenshot-2021-04-11-36873 (2)](https://user-images.githubusercontent.com/82332139/114314510-02bd5a80-9ac9-11eb-922e-79356a50817e.png)
![screenshot-2021-04-11-36784 (4)](https://user-images.githubusercontent.com/82332139/114314511-0355f100-9ac9-11eb-8e6b-2f3e20413deb.png)

**Comment by DaySpeed955i** [comment]
Same thing here, from what I can see, the output of channel used for expo is multiply by 10.
If you divide by 10 your values for chxx, it will will be fine.

I use Ch16 with replace, offset 5%, weight up 5% and weight down 5% which gives an expo value of 0%, 50% and 100%.
If you apply a fix expo value to your target channel, you will see the same curve.

Bug fix is to divide chxx by 10 for expo input to target channel.

Can you verify?
Thanks

**Comment by bsongis-frsky** [comment]
Fixed in 1.0.2
