### ISSUE TITLE
Swamping S6R receiver.

### ISSUE THREAD

**Issue by dwheel** [FrSkyRC/ETHOS-Feedback-Community#640]
X20, 1.0.10 RC3 FCC firmware causing swamping with S6R receiver. When the transmitter is brought closer than 3 feet of the receiver I get 'Telemetry Lost'. When transmitter is moved away about 4 feet, 'Telemetry Recovered' is announced. Watching telemetry, it appears that RSSI is the only thing lost when this happens. Everything seems to function normally at a distance. The airplane flies fine and all telemetry is received.

Works fine with release candidate 2.

https://www.dropbox.com/s/msj65cgaki91jrd/IMG_1514.MOV?dl=0

**Comment by bsongis** [comment]
Please wait for 3 seconds, all your sensors should become red, I really think you don't get telemetry within a so short distance

**Comment by dwheel** [comment]
Thanks bsongis. I have gone back to RC2 and don't see the issue at all so can't try it. It is only a minor irritation and the only reason I bring it up is because it wasn't present before RC3.

**Comment by ravikoth** [comment]
swamping of frsky recvrs is a known issue.
ignore it, its a small issue

**Comment by dwheel** [comment]
ravikoth Yes, I know. Have been dealing with it for several years and it is only a minor irritation. I repeat:

The only reason I bring it up is because it wasn't present before RC3.

When something different happens with new firmware it may be an indication that something bad has happened and needs attention.

**Comment by Hobby4life** [comment]
@bsongis-frsky Could it be that it is "more" noticable now due the telemetry filtering in RC3?

**Comment by bsongis-frsky** [comment]
I have found it, the RSSI on S6R is sometimes 0x65 or 0x66 which is 101% or 102%. As it is over 100% it was filtered out.
I will accept values from 101% to 127% and limit them to 100% in RC4
