### ISSUE TITLE
RIPRISTINO X20

### ISSUE THREAD

**Issue by plusxstd** [FrSkyRC/ETHOS-Feedback-Community#641]
Buongiorno a tutti , volevo una info in caso di ripristino completo o aggiornamento su X20 dell'SD posso ricaricare su sd solo l'ultimo file di aggiornamento sd e firmware ( 1.10.3 ) oppure devo ricaricare la sequenza partendo dal primo aggiornamento ?

**Comment by Hobby4life** [comment]
Just download the latest

**Comment by bsongis-frsky** [comment]
Why an issue?

**Comment by plusxstd** [comment]
Quindi formattando la scheda sd e caricando l'ultimo aggiornamento 1.10.0 /3 la radio  dovrebbe automaticamente ritornare a funzionare perfettamente senza i  modelli ?

**Comment by plusxstd** [comment]
> Perché un problema?

si , ho aggiornato con l'ultima versione ma non ha digerito qualcosa e accendendo la radio rimane bloccata conl'icona frsky ma non completa l'accensione

**Comment by plusxstd** [comment]
Why closed ?
-------- Messaggio originale --------Da: "Bertrand Songis @ FrSky" ***@***.***> Data: 15/07/21  12:50  (GMT+01:00) A: FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc: plusxstd ***@***.***>, Author ***@***.***> Oggetto: Re: [FrSkyRC/ETHOS-Feedback-Community] RIPRISTINO X20 (#641) 
Closed #641.

**Comment by bsongis-frsky** [comment]
Please try to write in english, nobody speaks italian in the team
