### ISSUE TITLE
MLVSS does not show individual voltages in 1.0.10 v3

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#642]
The individual voltages do not appear (total pack voltage shows) 
but when i roll back to 1.0.9 they show up perfectly.
doesn’t make sense.
defeats the purpose of a voltage sensor.
my issues are closed without redressal.
maybe the architect of ethos can look into this. 
This is a major issue.
everything else works just fine

**Comment by NMO81** [comment]
Yeah not much comment given in post #633 

On your home screen, you must tap twice on the widget that shows the total voltage. In the pop-up menu, you select "Configure Widget" You must now LONG PRESS on the source, then you get the menu with the extra options as highest, lowest, count, ... so no need to get all cell voltages individually.

**Comment by ravikoth** [comment]
> Yeah not much instructions are given in post #633
> 
> On your home screen, you must tap twice on the widget that shows the total voltage. In the pop-up menu, you select "Configure Widget" You must now LONG PRESS on the source, then you get the menu with the extra options as highest, lowest, count, ... so no need to get all cell voltages individually.

thanks for replying
So when you say count, it’s actually the pack voltage?
i want to display the total pack voltage.
eg 3 s lipo pack voltage at 12.6 volts.

**Comment by ravikoth** [comment]
Having said that it’s important to have individual cell voltages also.
its always been a handy feature.
hope bertrand is listening 
@bsongis-frsky

**Comment by bsongis-frsky** [comment]
I have answered to this already 3 times with screenshots, perhaps somebody else will explain with better words?

**Comment by ravikoth** [comment]
> I have answered to this already 3 times with screenshots, perhaps somebody else will explain with better words?

Thats the problem with a single author operating system,
you have to read sarcastic comments on a system which changes the basic structure of the operating system with every update. 
again & for the last time bertrand kindly note that individual voltages which were available all this while are not visible now. 
whats the point of having a lipo sensor if individual voltages are not available.
now for the benefit of all here can you kindly and in one word (yes/no) clarify if the new release is capable of displaying individual cell voltages of a lipo pack using a frsky voltage sensor.
If yes we’ll figure out how to access them.
if no then you’ve just closed an issue with immense ramifications. 
Thank you.

**Comment by ravikoth** [comment]
@bsongis-frsky 
Thanks

**Comment by hrenz** [comment]
The individual cell voltages are already displayed.
To do this, create a screen in the model view
enter the telemetry value Lipo INT.
Then press and hold ENTER, and the following selection appears
Cell1 ... Cell6, Min, Max voltage and so on.

![grafik](https://user-images.githubusercontent.com/6217896/125987816-76aaa531-30bd-43fc-9628-b20b52adee34.png)

**Comment by NMO81** [comment]
One remark for this is that you create your widget AFTER you connected a battery to the MLVSS or the cell voltages are not showing up in the options menu, the correct amount of cells must be detected before this options menu can be made.

**Comment by NMO81** [comment]
Ok I took screenshot of all steps:
![screenshot-2021-07-16-79899](https://user-images.githubusercontent.com/85587485/126004937-2a624517-b0d8-42e3-a85e-6099109305d3.png)
![screenshot-2021-07-16-79923](https://user-images.githubusercontent.com/85587485/126004961-3c820ffd-72dc-4cd5-a3e4-1a1a790d6cb5.png)
![screenshot-2021-07-16-79928](https://user-images.githubusercontent.com/85587485/126004976-3d6f61a3-2e4e-465b-a8ca-c398e3c2b379.png)
![screenshot-2021-07-16-79937](https://user-images.githubusercontent.com/85587485/126005001-76d451bd-4006-4f41-9246-911380bdc8b8.png)
![screenshot-2021-07-16-79947](https://user-images.githubusercontent.com/85587485/126005018-f1826c42-4f35-4f68-8edf-5ba9eb7fcca7.png)
![screenshot-2021-07-16-80051](https://user-images.githubusercontent.com/85587485/126005054-bd8efa9f-048d-4037-8ef6-f8b4c5b3ba4f.png)
![screenshot-2021-07-16-80057](https://user-images.githubusercontent.com/85587485/126005082-d1ea4efb-4f55-46e7-b229-baccb38eea11.png)
![screenshot-2021-07-16-80063](https://user-images.githubusercontent.com/85587485/126005093-6bbb1777-15d5-4667-8f17-b4717c2c982e.png)

**Comment by ravikoth** [comment]
Thank you so much

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
