### ISSUE TITLE
GPS screen selecting shows  files no longer exists at gps subdir

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#644]
V1.0.10 RC4
First 
have testet GPS Screens,
load, test, delete, at SD-Card
but now it shows files no longer exist at SD-Card

Next problem
X20 Screen format for GPS is 784x316 Pixel,  24 bit, *.bmp or *.png
but doesnt show me my screens at the new large homescreen 

but paris.png and paris.bmp works

only my small 300x280 pictures work

**Comment by Hobby4life** [comment]
It is RGB565 format.

I have created a image generator for it to make life easier :-)

https://hobby4life.nl/ethosmap/

**Comment by bsongis-frsky** [comment]
Please avoid PNG format. The RAM is not extensible and there are limitations.

**Comment by Hobby4life** [comment]
@bsongis-frsky

It is BMP now. now worries ;-)

**Comment by MIKE-DAILEY** [comment]
> @bsongis-frsky
> 
> It is BMP now. no worries ;-)

Working well with BMP.  Thanks for all your effort on automating the maps.

**Comment by hrenz** [comment]
X20 filemanader is not ok
At X20 filemanager  sub dir gps shows all the correct files, ok

but at at GPS Widget,  selecting the map, it shows  map no longer exists at gps subdir.
I have deleted my old *.png ones direkt with x20 filemanager
and have copied the new ones RGB565 bmp to gps subdir

think ETHOS does nor read the SD-Card when open the gps subdir
has store the old dir somewhere 

No change  when I delete gps-sub dir and write it new
No change when  I write firmewar.bin again
