### ISSUE TITLE
1.0.10 RC 4 - elements hidden behind keyboard

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#645]
First up, the onscreen keyboard is awesome! I wish is had the symbols too. But this has improved typing massively. 

I’ve not checked everywhere, but this issue popped up for me while editing logical switches. In particular, I was working on an edge switch and adjusting the duration at the bottom. The problem is that the numeric helper that now appears, completely obstructs the value being edited. I can get a screen grab once my battery has charged.

**Comment by bsongis-frsky** [comment]
Reproduced with Edge LS

**Comment by bsongis-frsky** [comment]
Fixed in RC5
