### ISSUE TITLE
ADC4 still fail with 1.0.10RC4

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#646]
Hello, unfortunately issue #629  does not seem to have been solved with the RC4.
I deleted all sensors, rebounded the receiver, and then had the sensors search again.
Everything works so far, unfortunately ADC4 still does not work.
![adc4](https://user-images.githubusercontent.com/64803366/125992806-f183a95a-fd5d-4000-b396-5d028d01eafc.jpg)

Transmitter is X10S 

Greets,Micha

Oh yes, if you already write something like this:
"**Change default bitmaps to BMP format, it uses far less RAM**"
you should maybe also make sure that you can upload BMP here.
By the way, the BMP of this screen is 255 kb, the jpg is not 18 kb.

**Comment by bsongis-frsky** [comment]
We are not allowed to change anything on github allowed files. This is a fact, PNG uses a lot of RAM on radio end, if you have too many model bitmaps, you will quickly reach the limit and bitmaps won't load anymore.

**Comment by bsongis-frsky** [comment]
Fixed in RC5
