### ISSUE TITLE
With 1.0.10RC4 the texts in LS are overlapped.

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#647]
Hello, an old problem has surfaced again.
In the logic switches, the texts on my X10S are overlapped again.
With logic switches in the single-digit range only if the condition is not met (not in bold).
For all others also in bold.

![ls_text](https://user-images.githubusercontent.com/64803366/125993715-4df387ce-ea23-4ced-a604-4bc84dd87794.jpg)

Greets,Micha

**Comment by bsongis-frsky** [comment]
DE translations again
Feel free to give a hand to Andreas @ EngelMT

**Comment by bsongis-frsky** [comment]
I reverted this change from Andreas translations
