### ISSUE TITLE
1.0.10 RC4 [Enter Long] to go directly to Edit page 

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#649]
X20 and X10
[Enter Long] doesn`t work in mixer screen
in timer, logic switch, special functions..... it is OK

**Comment by STC148** [comment]
https://user-images.githubusercontent.com/85410070/126007427-0a698ea1-d7f4-4d63-8a9d-1f1e575f9505.mp4

**Comment by Nicholas-Luoyi** [comment]
In Mixer screen. We use [Enter Long] to enter the outputs page. So we disable the edit page here

**Comment by loetefix** [comment]
It would be better to use (LONG ENTER) only then for showing the OUTPUT, If the OUTPUT is not configured in the Home keymap. For example: if i use DISP LONG for Output, there is no need to use ENTER LONG for OUTPUT and it can be used for "direct edit"

**Comment by bsongis-frsky** [comment]
If I am not mistaken [ENTER LONG] does nothing in Mixer page

**Comment by bsongis-frsky** [comment]
Shortcut added in RC5
