### ISSUE TITLE
1.0.10 candidate 4 timer issue

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#651]
Heres what i’m doing 
1) Edit timer on main screen
2) countdown start 00:04:00
3) Active condition (here’s the problem- no option works except the switch option) 
4) Reset on - … (nothing selected)
5) persistent - off

issue is that throttle absolute/percentage/trigger do not work.
only when i select switch position does the timer start.
If i select anything in the the reset option such as the spring loaded toggle switch then the timer starts when this switch is engaged & resets when this switch is released.

I dont know if this is an issue or i’m just doing the sequence/edit options incorrectly 
Thanks.
btw individual voltages are back.
thank you so much.

**Comment by bsongis-frsky** [comment]
You need an Active Condition, perhaps "Always ON"?

**Comment by ravikoth** [comment]
@bsongis-frsky 
That works. however the following issues persist
1) The Countdown Step doesnt work as i think it should. No matter where i set it (15 sec) the voice announcement is in minutes only. So it announce every 60 seconds.

2) The Active conditions besides “always on” do not work. Throttle absolute/percentage/trigger have absolutely no effect on the timer. 

So to override this issue i have set the active condition on “always on” & reset on switch SG
Although it serves my purpose for the moment.
The timer section needs to be a bit more user friendly in terms of settings.
The jeti timer setup is awesome.
the above is not to deride ethos, but to tap an attribute from a competing system which is clearly better in that area. 

Thanks for the patience & incredible work.
i’d be cursing the “issues” crowd especially on a holiday😬

**Comment by bsongis-frsky** [comment]
Please paste your Timer settings. I just double checked Throtlle Absolute, Throttle Percentage, and it worked perfectly.

So you may have something different in your setup which I don't know

**Comment by aalain8** [comment]
Hello, 
Tested the 1.0.10rc4 this morning, no timer problem.

**Comment by ravikoth** [comment]
@bsongis-frsky 
![E6BD5E98-F306-4F33-929B-79BB89C59EDE](https://user-images.githubusercontent.com/87301909/126034904-934063a2-4cdb-409d-8d66-edf9cf99878f.jpeg)
![97384BAC-7034-40D0-8EDD-5E5932B26567](https://user-images.githubusercontent.com/87301909/126034912-2190fc73-5af2-4c70-bc92-b379a6e9b07e.jpeg)

**Comment by ravikoth** [comment]
@bsongis-frsky ![IMG20210717164100.jpg](https://user-images.githubusercontent.com/87301909/126035060-499e5496-b6c1-4c92-9442-5cbf0c0cd8d9.jpg)

![IMG20210717164048.jpg](https://user-images.githubusercontent.com/87301909/126035066-18a3d1f0-2533-4649-b0ee-cb779b7426d4.jpg)

**Comment by ravikoth** [comment]
@bsongis-frsky 
Apparently it was (i think an issue with the firmware installation)
did a complete format of the card & reinstalled the prerelease c/4
timers work perfectly.

however the countdown announcements are still in 60s steps.
not in the 30 sec i’ve set them at. 
and they continue to go beyond the alarm value.
