### ISSUE TITLE
Request: change screen as a special function

### ISSUE THREAD

**Issue by mshagg** [FrSkyRC/ETHOS-Feedback-Community#652]
It would be useful to have a contextual set of widgets depending on the configuration of the aircraft. 

For example engines armed vs disarmed, gear up/down (i.e. flying versus landing configuration).

This could be achieved by having a special function which allows you to select one of the screens which you have setup (e.g. SF = Display Screen1)

**Comment by hrenz** [comment]
or Reset lot of Values  with a Switch at one point
and select from a list
GPS Alt 
Vario Alt
Timer x
Consumption
and so on

**Comment by MrD-RC** [comment]
This would be a great idea. A practical example would be having GPS coordinates on a screen. If you lose telemetry, it could automatically switch to that screen to display the last known coordinates, and other useful retrieval information.

**Comment by hrenz** [comment]
change screens with up down function, example, SI, SJ
or with the SFW1..SFW6 select a screen

**Comment by mawzthefinn** [comment]
Yes, this would be quite useful, could even allow screen changes with a gyro input.

**Comment by azaz44** [comment]
Adding my comment from duplicate issue #2248 

----
It would be so great to have sth like this:

![image](https://user-images.githubusercontent.com/42830563/209662606-2d23fcaa-27f2-4478-a61e-520a41641fcb.png)

This would allow us to define what we want to see on the screen depending on flight mode or situation (like preflight, flying, post flight checks).

Examples:
- in preflight (throttle cut engaged, timer is at zero) show screen number 1
  - model image
  - battery voltage
  - BEC voltage
- if flying (no throttle cut) show
  - timer
  - RPM
  - current
  - etc.
- after flight (throttle cut engaged, timer > some value)
  -  show flight stats to find out if there were any problems, like
  - max current during flight
  - max ESC temp
  - lowest battery voltage
  - lowest BEC voltage
  - lowest RSSI and VFR
  - etc.

This would be super useful.

**Comment by Tomppy** [comment]
It would be cool to be able to navigate in the differents screens of a model with sliders.
As I d'ont have all information on the same screen because I want few widgets per screen, if I want to have a quick look to check something It would be nice to be easily able to switch screen with the handy sliders

**Comment by craigywsm** [comment]
Great idea. having zavionics on 2nd page and other telemetry items on page 3.
Would be good to increase display page by 1 e.g next page 
Page 1 >> Page 2 >>> Page 3 >>> Page 1  etc

**Comment by ahvink** [comment]
Any progress on this?
It would be really useful!

**Comment by bsongis-frsky** [comment]
Yes, more on this tomorrow ;)

Le mer. 11 oct. 2023 à 22:52, Alfred Vink ***@***.***> a
écrit :

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d5a76d7c-e3bc-48a9-85e3-c6152ae26191)

**Comment by bsongis-frsky** [comment]
Available in next 1.5.0 nightlies
