### ISSUE TITLE
V 1.010.4 logic switch GPS Speed X value can´t go over 118 kmh

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#653]
i want to control a speed warning with a logic switch. The source is the GPS speed sensor. The value cannot be set higher than 118 kmh then it changes back to 0kmh.
after 117 the sign changes from + to - then the value changes to 0
![image](https://user-images.githubusercontent.com/84685639/126033087-d688e998-ff23-46c3-bb9f-6e12de549547.png)

**Comment by hrenz** [comment]
a byte problem 0 to 255 or -117 to +118

**Comment by bsongis-frsky** [comment]
strange range for a byte ;)
fortunately it's not a byte problem

**Comment by bsongis-frsky** [comment]
Fixed in RC5
