### ISSUE TITLE
Enhancement: allow finer adjustments of outputs

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#655]
It would be great if the endpoints and midpoints could be adjusted in 0.1% increments.

The current 1% increments are not accurate enough for some tasks. For example setting the outputs to 1000 uS to 2000 uS, with a 1500 uS midpoint for flight controllers. With my X9D Plus and X10S Express, I was always able to get it dead on 1000 - 2000 uS, at around +/- 97.7%. With the 1% increments of the X20, it is always out.

I’ve also noticed a lot of jitter on the outputs. Re-calibrating does nothing.

**Comment by loetefix** [comment]
Also a copy limits and midpoints to all channels would be great for flight controllers.

**Comment by bsongis-frsky** [comment]
Midpoint has already a 0.1% precision
![image](https://user-images.githubusercontent.com/50834778/126107588-78857659-a45b-4af3-a6a6-706abf97079c.png)

**Comment by MrD-RC** [comment]
Sorry @bsongis-frsky, I missed that (midpoints have 0.1% increments). But on the flight controllers, the endpoints are more critical. I’ve not had to adjust the midpoint for that task. 

@loetefix I really like that idea. Usually they all are set the same. So that would speed things up greatly.

**Comment by loetefix** [comment]
Yes . On helicopter flybarless it is also needed. 
Maybe they could make a checkbox on channel 1 output. If it is activ , the other channels use same limits.
