### ISSUE TITLE
Emergency mode triggered

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#656]
Firmware version: 1.0.10, FCC #da8e2db0
Description of the issue - go to RF System page, click edit icon for the Owner Registration ID and hit the backspace key.
Description of the expected behavior - I would think I was ending the Owner Registration ID.
Description how to reproduce the bug - video here: https://1drv.ms/v/s!AvdNXPgN8JWDzYBWGeTFEll_D1jhHw

**Comment by bsongis-frsky** [comment]
Fixed in RC5
