### ISSUE TITLE
Enhancement: Make Throttle cut status available as source for logic.

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#659]
The Throttle cut sticky function is a very welcome function in RC4.

The same function I always created it in Logic.
Because I created it in logic, I always knew the status of the throttle cut.
This to trigger other things in logic or special functions.

Now with that function implemented I have no source of status for it to trigger something else.

**Comment by bsongis-frsky** [comment]
Duplicate of #528
