### ISSUE TITLE
Telemetry screen need more space for translation

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#66]
I think it would be good to move the column for "Source" as far to the right as possible. On the reight side it is so much space not used. And then value accordingly. Because depending on the sensor, the range for the name is very different in length.

![Screenshot 2021-04-12 120750](https://user-images.githubusercontent.com/16795828/114378214-c8ff5900-9b87-11eb-8af5-ed37cb4b7e12.jpg)

**Comment by bsongis-frsky** [comment]
Done in 1.0.2
