### ISSUE TITLE
Cross Trims mixed together

### ISSUE THREAD

**Issue by commsart** [FrSkyRC/ETHOS-Feedback-Community#660]
I have crossed all trims (LH -> RH, LV -> RV, RV -> LV, RH -> LH). Most work fine but the LV activates RH as well. When I trim Elevator with LV both Elevator and Rudder move (up, right). Used Fine mode.
I tried deactivating/activating RV (Thr) trim, no effect.
I do not have any mixes between Elevator and Rudder. I do have Thr to Rudder mix.

**Comment by commsart** [comment]
Ethos on X20S, 1.0.7, FCC

**Comment by bsongis-frsky** [comment]
This has been rewritten since, you will have to update to 1.0.10
