### ISSUE TITLE
In the German version, the telemetry "min", "max" display are written incorrectly.

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#662]
Hello

If you select a minimum value, it will displayed "Serwoweg min.". But it should only displayed "min".

Thank you

Enzo

![IMG_Ethos1](https://user-images.githubusercontent.com/87656206/126173255-eb895f20-817a-4922-9922-cd7682f79da0.jpg)
![IMG_Ethos2](https://user-images.githubusercontent.com/87656206/126173265-b85d2407-b06e-4377-abcd-306e32c75483.jpg)

**Comment by bsongis-frsky** [comment]
Duplicate
