### ISSUE TITLE
Standard servo value goes to zero

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#663]
Hello

I tested the new Number Values Controls. I noticed that when you select the standard value, the servo travel goes to zero%. Wouldn't it be more logical if it went to 100% or -100%?

If "min" is selected, the servo travel goes to zero. If "max" is selected, the servo travel goes to 150% or -150%. Therefore, in my opinion, when selecting default, the travel should go to 100% or -100%.

Thank you

Enzo

**Comment by bsongis-frsky** [comment]
Default value modified for:
- channels min (-100%) and max (+100%)
- mixes weight (+100%)
- telemetry sensor user limits (depends on the sensor)
- rssi warning and critical thresholds (depends on the ACCST / ACCESS protocol)
- voltage sensors ratio (100%)
- vario ranges
- curve default points count (5)
- trainer slave channel weight (100%)
