### ISSUE TITLE
Bar(s) widget

### ISSUE THREAD

**Issue by OlegStelmakh** [FrSkyRC/ETHOS-Feedback-Community#665]
Is it possible to add a widget that would display value bar for the values of the selected channel and one more widget for several channels at once?

**Comment by bsongis-frsky** [comment]
Duplicate of #592

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128385890-46a504c5-1b47-460d-b39d-697687e6c187.png)

**Comment by OlegStelmakh** [comment]
Goood! Please, link to release candidate? :)
