### ISSUE TITLE
LSW captions in some places

### ISSUE THREAD

**Issue by OlegStelmakh** [FrSkyRC/ETHOS-Feedback-Community#666]
Hello!

Can you add name of LSW for main screen of SF and inside each one SF? I have a lot of LSW and every time I have to look again what the switch is doing.
An example Active Condition: LSW3 (Prearm)
Thanks

![screenshot-2021-07-19-78553](https://user-images.githubusercontent.com/87668472/126214333-60250b74-6a84-4838-a63d-4f0b157aca6e.jpg)
![screenshot-2021-07-19-78542](https://user-images.githubusercontent.com/87668472/126214337-b2a780b9-1601-4344-aee6-bae54bf1fc31.jpg)

**Comment by Hobby4life** [comment]
You have to name the Logic switch functions too.
Then you can select bij function name instead of function number.

**Comment by OlegStelmakh** [comment]
P.S.: LSWs on LSW menu have its own names

![screenshot-2021-07-19-81307](https://user-images.githubusercontent.com/87668472/126217040-05a9974d-2002-47ed-87dd-8e98398ed51b.jpg)
