### ISSUE TITLE
RC5 some Values from RC4 have changed first to 65535 

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#667]
insteed of 100% at RC4 there is 65535 on same fields
some Values from RC4 are changed to 65535

**Comment by bluelex73** [comment]
I also have problems with version 1.010.C5
![after update C5](https://user-images.githubusercontent.com/84685639/126218366-646e45b6-adf7-49e5-a9bb-ca6a7d92f69e.jpg)

**Comment by Devil-IdT** [comment]
Same here:
![gas](https://user-images.githubusercontent.com/64803366/126219535-8649c692-fb29-41e0-8497-3a6f5ef3abf7.jpg)

Go to the value once, press ENTER for a long time, set the value to minimum.

**Comment by Hobby4life** [comment]
Yup RC5 screws everything up..  back to RC4

**Comment by STC148** [comment]
RC5 is unusable

https://user-images.githubusercontent.com/85410070/126223134-7bc7752c-9cd5-4ee8-8457-91d500560ffd.mp4


https://user-images.githubusercontent.com/85410070/126223158-44c751dd-0aae-475b-aba6-6903c82fd7da.mp4

![IMG_20210719_220833668_HDR](https://user-images.githubusercontent.com/85410070/126223199-3f448f4b-4edc-43e0-b571-e6ed0bb66572.jpg)

**Comment by bsongis-frsky** [comment]
I think you had a source there with some options like "Negative". 
I will try to reproduce it tomorrow and release again.

**Comment by bsongis-frsky** [comment]
Someone has a model with such settings which convert to a wrong value?

**Comment by STC148** [comment]
[RC04.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6843877/RC04.zip)
[RC05.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6843878/RC05.zip)

**Comment by bsongis-frsky** [comment]
Thanks, which model should I look at?

**Comment by bsongis-frsky** [comment]
Fixed in RC6
