### ISSUE TITLE
Bug Logik Switch

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#669]
Version: 1.0.10.5

Bug logical switch
Function less than
Value X = -95
Switch works

after model change:
Value X = 16777121
Switch no longer works 

![1DCD50D0-F54E-42B7-85AC-A3F6D8FE5224](https://user-images.githubusercontent.com/85737356/126229415-fe9cbd63-5848-4e49-9c88-705cbea96e55.jpeg)
![75A50D7A-9204-4338-BE3D-6A05C54EA11F](https://user-images.githubusercontent.com/85737356/126229429-3ff854e1-bcad-4232-9ec6-89863143c44c.jpeg)

**Comment by bsongis-frsky** [comment]
Duplicate of #667

**Comment by yak55** [comment]
Sorry, I just found out that it works as long as the values remain positive. Negative values lead to an error. 

E. Bleuel

Diese Nachricht einschließlich aller Anhänge kann vertrauliche und/oder rechtlich geschützte oder sonst relevante Informationen enthalten. Wenn Sie nicht der beabsichtigte Empfänger sind, sind Sie nicht zur Verwendung oder Weitergabe der Informationen befugt. Bitte benachrichtigen Sie uns sofort über den irrtümlichen Empfang und löschen Sie dann die Nachricht.
