### ISSUE TITLE
Helicopter template has weird output channels

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#670]
I created a new helicopter model and the output channels are set as follows:
1:  Throttle
2. Rudder
3.  - 
4. - 
5. Aileron
6. Elevator
7. Pitch
This same set of outputs happens regardless the flybar type (at least I tested with no flybar and H-1).
The default channels for my radio are AETR. 
I could be missing some setting somewhere that I am supposed to setup defaults.

**Comment by Hobby4life** [comment]
I would like to link the following issues as reminder for better Heli implementation in Ethos:

#543

#602

**Comment by OldGazer** [comment]
Repo'd on my X20.  The channel assignments are just plain wrong..

**Comment by m0p3d** [comment]
> I created a new helicopter model and the output channels are set as follows:
> 1: Throttle
> 2. Rudder
> 3. -
> 4. -
> 5. Aileron
> 6. Elevator
> 7. Pitch
> This same set of outputs happens regardless the flybar type (at least I tested with no flybar and H-1).
> The default channels for my radio are AETR.
> I could be missing some setting somewhere that I am supposed to setup defaults.

Agree - I managed to setup for microbeast flybarless via sbus. But you have to manual asign/ redefine channel order. Plus- its confusing to read Elevator instead of Nick , Aileron instead of Roll etc ....

**Comment by Hobby4life** [comment]
Plus- its confusing to read Elevator instead of Nick , Aileron instead of Roll etc ....
Most controllers/software in "Heli World" are using Aileron and Elevator.. so not sure what is to be confused about lolz.
At least I have not seen otherwise in BeastX, Vbar, Brains etc..

But I do agree, channel order should be user defined at creating a new model.
Pre defined is ok.. but user has to be given the choice to change the pre defined channels before ending the wizzard.

**Comment by m0p3d** [comment]
Easiest would be to have a selection for the used flybarless system which asigns the channels like they are expected for the specific flybarless system- there should be not to many variation/types

**Comment by Hobby4life** [comment]
Well you see what comes from all pre defined stuff, lots of confusion,
The one likes this way, the other likes the other way.. and again another likes it better in again another way.|
Sometimes it is better to give the option to config things yourself from the start. No pre defined at all.

**Comment by m0p3d** [comment]
Agree- if the wizard would ask seems to be a good solution which fits for everyone

**Comment by guycnicholas** [comment]
As a simple solution, I would argue it should just follow the default channel lineup for the radio. For example I am AETR, so it could just start at that. Pitch could be added past that.
As a secondary not, I am not sure why their default names also have `(Heli)` appended to them.

**Comment by bsongis-frsky** [comment]
- The Wizard should allow the user to change all channels : #552 
- What should be the default channels order on a Heli?
- What should be the default output names? Today they end with (Heli), do you have a better proposal?

**Comment by m0p3d** [comment]
Why not align to futaba sbus Standard Order which ist 1 ail
2 ele
3 Thr
4 rud
5 gyro gain
6 Pit
7 aux (rescue Trigger)

**Comment by m0p3d** [comment]
Mit Sure what was the Intention to add (Heli) - seems Like Others so mit add and Just use the plane speech - aileron elevator and so on - instead of Heli you could also use the more Heli specific names Aileron(Roll) Elevator(Nick) ...

**Comment by Hobby4life** [comment]
> Why not align to futaba sbus Standard Order which ist 1 ail
> 2 ele
> 3 Thr
> 4 rud
> 5 gyro gain
> 6 Pit
> 7 aux (rescue Trigger)

Agree without aux

**Comment by guycnicholas** [comment]
@bsongis-frsky I am not sure why they have to end with anything? Elevator is fine, I don't need Elevator (Heli).

@m0p3d I don't believe that is the SBus standard as much as it is the Futaba standard. Which is why I suggest the default should pick the default for the transmitter. I started years ago with Futaba so everything I do is set to their AETR setup. I believe that if a user was a JR person, they probably have their radio set to TAER.
Another easy option, rather than choosing each channel, could be to prompt for SBus or Radio default.  If I am setting up an old school flybar heli, I would choose Radio, if I am on one with a controller, then I would choose SBus. 
In fact I would argue, the same logic could be applied to airplanes as well, some will use controllers, and they might want SBus order, others might not.

**Comment by m0p3d** [comment]
Think we joined endless discussion.
For me it would be also ok to just ask if u use the wizard if u want to proceed with the default channel order (wich can be already picked in the radio or if you want to to redefine the (Dropdopwn Menu Channel 1-4 , 1-6, 1-8) -> aftwerwards there is dropdown to asign

**Comment by guycnicholas** [comment]
I think in the long term the better solution would be to have some way to edit the templates, where I would be able to set these sorts of defaults for myself, and you for yourself.
Part of my reason for trying to keep the solution simple is I am a software developer myself and I know that every feature to be worked on will be weighted with a cost/benefit and I know there already exists a lot of important features to be implemented.

**Comment by bsongis-frsky** [comment]
Why do you speak of AETR with such a template, here I see CYC1 / CYC2 / CYC3, not Ail and Ele

**Comment by guycnicholas** [comment]
@bsongis-frsky I would consider two categories of control, direct and indirect. Indirect control or ECCPM and when I was mentioning following the transmitter default I was only speaking of direct control. If I were to template the output channels, I would break it out via direct and indirect.  Direct would essentially map aileron, elevator, and pitch to an output channel, and any of the ECCPM modes would then map CYC1-3 to a set of channels.
