### ISSUE TITLE
Add xxx it not very intuitive when using touch

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#671]
I find the "add a new [flight mode | curve | mixer | logical switch] behavior to be odd. I would not expect to have tap on an existing item to add a new one.  I realize you have to be able to bring up the menu from the keys, however a tap in the empty space in the list should allow me to add.

**Comment by Hobby4life** [comment]
Better is a good indicator like "+" for all add functions.

**Comment by aalain8** [comment]
Very good idea, a + box to add functions is more intuitive.

**Comment by jreis1** [comment]
+1

Yup! I feel your pain :) Specially in the mixer menu, when you have to press "enter" to add a new entry.  a '+' on the screen would be a must

**Comment by i3dm** [comment]
> Better is a good indicator like "+" for all add functions.

agreed

**Comment by bsongis-frsky** [comment]
Done in 1.0.10 (only on X20 and only accessible by touch)
