### ISSUE TITLE
Restoring Functional Switch last state after power cycle

### ISSUE THREAD

**Issue by OlegStelmakh** [FrSkyRC/ETHOS-Feedback-Community#673]
Each time radio enables, FSWs resets to FSW1 = ON. Can we get this changed to last FSW state? Including FSW = not assigned (no leds enabled on any FSW).
Thanks.

**Comment by OB1-OB2** [comment]
+1

Also a check/alarm on the state of the FSWs on model selection is needed: [https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/637](url)

**Comment by Hobby4life** [comment]
#523

**Comment by mawzthefinn** [comment]
Just tested and FSW's are now being remembered. No selected FSW active  is currently only available when FSW's are set to 6 pos + off, 2 pos or momentary.
