### ISSUE TITLE
Free Mix Trims need to be activated & Delta mixing please

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#675]
Hi,
The free mixes have no trim option.
so when i just did a delta (flying wing) mix and used a free mix with the ailerons the trims were not activated in the free mix channel.
This reduces the flexibility of the system

Also kindly incorporate a delta wing mix in model configuration, all radios have this mix preprogrammed ready to be used.
will make Ethos more user friendly.

Cheers

**Comment by jfint** [comment]
when this is implemented, I hope that you will simply add a line to assign and trimmer, and not have it on by default obviously.

**Comment by bsongis-frsky** [comment]
Delta is a plane without a tail!

**Comment by bsongis-frsky** [comment]
Merged into #702
