### ISSUE TITLE
Cosmetics: v1.0.10 RC6 - X20S Curve visible over keyboard layout

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#677]
![2021-07-20 21 04 15](https://user-images.githubusercontent.com/55426642/126384950-2a3d8a15-7254-4226-b600-76dde22392f3.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/126448275-afdec846-4e41-4933-a2ea-05686405e152.png)
