### ISSUE TITLE
The trims and the 6 function switches only work when the screen is on

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#678]
Hello

The trims and the 6 function switches only work when the screen is on.
Is there a way to take the trims and 6 function switches out of the awake process? 

Many thanks and kind regards

Enzo

https://youtu.be/PEZfHC34UyM

**Comment by jfint** [comment]
2nd this, I hate it when the trim does not respond while I have something fast or precise going on. There should be no reason for the screen to need to be on to require something that has direct flight implications to work.
