### ISSUE TITLE
Put SD card contents and Flash files always in the list

### ISSUE THREAD

**Issue by gjvo** [FrSkyRC/ETHOS-Feedback-Community#679]
I was contacted by someone that deleted the flash files from his transmitter.
I found out that the Flash files and SD card contents are not listed in every canditate.
It would be more handy to put the Flash files and SD card contents in every list of every candidate and not only when they are changed in a release.
Saves a lot of searching, makes live so much easier.

**Comment by jreis1** [comment]
Agreed! 
This has already been requested (can't find ticket).

**Comment by jreis1** [comment]
same as #634
