### ISSUE TITLE
In the Curves menu, more letters are possible for the name than can be displayed.

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#68]
It is possible to write 15 letters for a name. But displayed are not more then 13.

Further I think it will be good to add another column with the name "Pos." or No. for the numbering which is added automatically.

![Screenshot 2021-04-12 125125](https://user-images.githubusercontent.com/16795828/114383761-3615ed00-9b8e-11eb-8cd7-dd8f549db0b6.jpg)
![Screenshot 2021-04-12 125049](https://user-images.githubusercontent.com/16795828/114383768-36ae8380-9b8e-11eb-9dfe-40615ca7a1f7.jpg)

**Comment by bsongis-frsky** [comment]
It depends on the letters you use, if you write "iiiiiiii" I think it will be good, you are not forced to write big names, yes?

**Comment by EngelMT** [comment]
Yes I know that the customer are not forced to write long names. But they can. And then 3 pages and 3 different displayed Names.

![Screenshot 2021-04-13 102536](https://user-images.githubusercontent.com/16795828/114523218-64ee9a80-9c44-11eb-822d-bb26358fc901.jpg)
![Screenshot 2021-04-13 102512](https://user-images.githubusercontent.com/16795828/114523220-65873100-9c44-11eb-88b5-68633feeecd3.jpg)
![Screenshot 2021-04-13 102439](https://user-images.githubusercontent.com/16795828/114523225-65873100-9c44-11eb-9faa-0f81a414478a.jpg)
