### ISSUE TITLE
(Reminder) Heli Mixer, Trims not working correct

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#680]
Heli Mixer, Trims not working correct

When moving Aileron left of right.. Swashplate moves left or right accordingly.
But when applying trim left or right, Swashplate moves up or down!, not Left or right!
Same for Elevator.

I am posting this duplicate issue to raise awareness of this issue.
To date there has been no response from the development team, has it been checked? or is being looked at? is it being worked on? a little bit of feedback would be nice :-)

This issue is also a reminder of issue: #543

**Comment by hrenz** [comment]
simple solution for all mixers
for the mixers the trim field must be inserted
with 2 selection:

Trim On
Trim OFF
Trim Invers

and you have what you need with all complex mixers
