### ISSUE TITLE
battery percentage display when charging

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#681]
not sure if this could be done under current sw / hw architecture in X20 or future radios but it sure is useful if a small icon with battery percentage / voltage can be shown while Tx is charging (like cell phones do).

**Comment by Hobby4life** [comment]
That means that the TX/Display must be on to show the %, that makes no sense.
Display consumes the most power.

**Comment by i3dm** [comment]
> That means that the TX/Display must be on to show the %, that makes no sense.
> Display consumes the most power.

and still.. every smart phone on the market handles it quite well :)

**Comment by Hobby4life** [comment]
Yup, but you can not compare the usage of a 24/7/365 phone, with a transmitter.
Also the architecture is completely different.

**Comment by i3dm** [comment]
i did put a note about architecture :)
this is next level stuff...

**Comment by bsongis-frsky** [comment]
Impossible with current hardware
