### ISSUE TITLE
Possibility to expand the size of the telemetry parameters on the screen

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#682]
When you design the widgets on the screen, the telemetry data would be interesting to be able to resize it for people who don't see well.

Thanks

**Comment by bsongis-frsky** [comment]
I don't get your idea

**Comment by jasalca** [comment]
This is now
![IMG_0958](https://user-images.githubusercontent.com/87758703/126766438-53639132-adb9-4d12-b222-fb474e292619.jpg)
This is my idea
![IMG_0961](https://user-images.githubusercontent.com/87758703/126766534-9bfe949e-3cd7-4359-a750-f4024676dbbf.jpg)
![IMG_0960](https://user-images.githubusercontent.com/87758703/126766549-6aabccf0-ba74-4af1-8ca3-92f6f02e7a50.jpg)

Of course according to the size of the witget

**Comment by jasalca** [comment]
My intention is to make the numbers larger in size

**Comment by AndyH56** [comment]
I support this proposal.   The widget numbers can be difficult to see.  I suggest being able to specify the font size of the text/numbers.  Centre the text/numbers in the widget.   To make it more simple, don't bother about limiting the text to fit in the box, leave that up to the user to set the correct size.

**Comment by jasalca** [comment]
Yes , that's the well-explained proposal, thanks.

**Comment by jjwebster** [comment]
In a similar vein, since it seems according to the Fr-sky product page that LUA scripts are supported, would it be possible to replicate a telemetry view similar to what is possible on the Horus running OpenTx/LUA?
![image](https://user-images.githubusercontent.com/3705148/126918867-c3d50326-a675-4f4d-a3f4-a69f8e759fda.png)

**Comment by bsongis-frsky** [comment]
We don't have a font over XXL. So it means doing something special

**Comment by AndyH56** [comment]
Just to be clear, you are using the largest font you have ? XXL.   It would still be good to make them larger if possible.

**Comment by mawzthefinn** [comment]
Yes, that's currently the largest font available
