### ISSUE TITLE
Cosmetic RC6 editing a curve

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#683]
Hello,

Not very easy to have an idea about the curve with this ;-)

![image](https://user-images.githubusercontent.com/27886942/126539400-72e1acaf-9ad9-4984-8262-af75b4c3a535.png)

See you

**Comment by Hobby4life** [comment]
That box below the screen should not be visible in curves.
Not needed in curves.
