### ISSUE TITLE
Slow Down / UP 

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#684]
Hello again,

Settings a curve with a switch 2 POS to control an engine with a curve for a glider as shown and want to add a slow UP for 3S per example and
1 S to Slow down.

The time for the output is clearly something different and don't know what it is ;-)

![image](https://user-images.githubusercontent.com/27886942/126540261-1ce2c879-1046-4568-ac3f-a32261d4008a.png)

**Comment by bsongis-frsky** [comment]
The curve modifies the output, not the delay. Here your input has only 2 states: 100% and -100%
Please use forums to ask for help, this github is for issues only

**Comment by aviat40** [comment]
Hello Bertrand, 

I know the 2 states, 
but set SLOW up from -100% to 100% with 3 S 
and SLOW Down from 100% to -100% with 1S 

and the output is not compliant with these delays 



De: "Bertrand Songis @ FrSky" ***@***.***> 
À: "FrSkyRC/ETHOS-Feedback-Community" ***@***.***> 
Cc: "Thierry" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 23 Juillet 2021 07:32:57 
Objet: Re: [FrSkyRC/ETHOS-Feedback-Community] Slow Down / UP (#684) 





The curve modifies the output, not the delay. Here your input has only 2 states: 100% and -100% 
Please use forums to ask for help, this github is for issues only
