### ISSUE TITLE
1.0.10 RC6 X20S Shortcuts at the Bottom of the List doesn`t work correctly

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#685]
https://user-images.githubusercontent.com/85410070/126549012-a9c55a3a-364e-4750-a3b2-fd0780e7a5a9.mp4

**Comment by Hobby4life** [comment]
To be more precised. This happens with longpress touch only.
With encoder button it behaves normally.
Happensnin **ALl** menus
