### ISSUE TITLE
Power off customisable delay

### ISSUE THREAD

**Issue by OlegStelmakh** [FrSkyRC/ETHOS-Feedback-Community#686]
Hi!

Would be nice to have an option to set up a delay for turn off a transmitter, a.e. 1-4sec.
Thanks!

**Comment by jreis1** [comment]
not sure what you really mean, but would this not be dangerous ?
I agree this could be an option for a large delay, like 1 or 2h without touching the transmitter. (e.g. for people (like me) that store the radio in the case and forget to turn it off)

**Comment by OlegStelmakh** [comment]
> not sure what you really mean, but would this not be dangerous ?
> I agree this could be an option for a large delay, like 1 or 2h without touching the transmitter. (e.g. for people (like me) that store the radio in the case and forget to turn it off)

I mean delay for power button

**Comment by visioneerone** [comment]
Seconded!  Can that timer range extend from -0- seconds?

**Comment by Franjose1984** [comment]
That will be great!!!

**Comment by mawzthefinn** [comment]
This could be useful.

**Comment by mawzthefinn** [comment]
#1499 has some more in depth discussion. Closing this off in favour of the newer issue due to that.
