### ISSUE TITLE
Don't disallow additional mixes based on initial wizard choices

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#687]
For example.  If a person has a flying wing, they select no tail in the wizard, but if a person has a rudder, now they can no longer add a rudder mix and they have to go back and do it manually, either by adding a standard plane and building the delta mixes, like optenTX, or by adding 2 free mixes, one for the stick and one for the rudder.  

It would be better if they were just allowed to add in a rudder mix.

**Comment by aalain8** [comment]
It seems possible to me.
You go into add a mix and choose drift.

**Comment by ravikoth** [comment]
I hope this is incorporated. 
essential in my books

**Comment by bsongis-frsky** [comment]
@aalain8 is right, I just checked it

**Comment by jfint** [comment]
OK, but what about the fact that butterfly is not allowed on a non-glider?  We used to use this all the time on 4 surface wing aerobatic airplanes.

**Comment by bsongis-frsky** [comment]
Yes it is allowed now
