### ISSUE TITLE
Display sleep function not working if wake up condition "sticks" is selected

### ISSUE THREAD

**Issue by OlegStelmakh** [FrSkyRC/ETHOS-Feedback-Community#689]
![screenshot-2021-07-22-83938](https://user-images.githubusercontent.com/87668472/126704399-19d8ae87-9232-49c6-b616-9e3a21eff6a8.jpg)

**Comment by MIKE-DAILEY** [comment]
Sticks wake up test OK here with X20S and 1.0.10. RC7.  In your posted image you do not have Sticks checked.

**Comment by OlegStelmakh** [comment]
Sorry. My mistake, now working fine!

**Comment by Hobby4life** [comment]
Question are you using a X20 or X20S?

If a X20, can you tell me what is showing at the SYS->Info page. "Sticks" PWM or something else?

**Comment by OlegStelmakh** [comment]
> Question are you using a X20 or X20S?
> 
> If a X20, can you tell me what is showing at the SYS->Info page. "Sticks" PWM or something else?

X20**S**

**Comment by OlegStelmakh** [comment]
Shows ADC

**Comment by Hobby4life** [comment]
Ok

**Comment by bsongis-frsky** [comment]
In your posted image you do not have Sticks checked.
