### ISSUE TITLE
Ansage wiederholt zu oft. 

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#692]
Wenn ich meine Flugphase öfters umschalten nervt die Ansage. Denn diese wiederholt alles so oft wie die Schalterstellungen betätigt wird.
Kann dies nicht reduziert werden, wenn helbel auf Position. Nicht noch 5mal ansagen sonder die ansagen ignorieren.

**Comment by miksterr** [comment]
Englisch bitte - da dies die Sprache des Githubs ist.

English please - as this is the language of the github.

**Comment by AlwinHaas** [comment]
Hello, my problem is that the Telemetrie speak repeat 10 times when I make 10 times put a switch on and oft. But I need it only at the last time or two times one for of an one for on. But it tells every speak how oft I put a switch.

**Comment by bsongis-frsky** [comment]
You have to use some logic switch to do this. Please ask for help on forums, this github is for issues only
