### ISSUE TITLE
Step Selection missing RC8

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#693]
Hello,

Something is missing from the simultor in RC9. The bar to select th
![screenshot-2021-07-23-62941](https://user-images.githubusercontent.com/27886942/126802482-0935129f-8bee-4dc7-94fc-8fdc488a1da3.png)
e step
![image](https://user-images.githubusercontent.com/27886942/126802517-3e43f249-147e-4a04-ae5f-bfe4d0f988f4.png)

**Comment by bsongis-frsky** [comment]
You miss the bitmap mask_step.png

**Comment by bsongis-frsky** [comment]
Again before posting issues please ask on forums
