### ISSUE TITLE
#684, you closed to fast

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#694]
![image](https://user-images.githubusercontent.com/27886942/126802840-752914e1-8e9e-4cbb-a87c-0a4d3d8f3c07.png)

3S to SLOW UP / 1S to SLOW DOWN from -100% to 100 %

and check the output screen. The time from -100% to 100% is not reliable from 3S or 1S

**Comment by bsongis-frsky** [comment]
I just measured:
  3S to go from 0 to 100%

Please ask on forums before posting here

**Comment by aviat40** [comment]
Ok Bertrand, but which Forum, the support reported on the Ethos Website is only Github !!
And sorry, as it seems to disturb because many things is changing very fast, it is very difficult to follow all the update.
I will now only post for French translation
