### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#695]
Hello,

Screenshot in radio set BMP files which are not allowed in GITHUB to help you debugging . Need to convert each file.
Why not use PNG directly ?

**Comment by OlegStelmakh** [comment]
PNG is heavy format. JPG would be fine

**Comment by bsongis-frsky** [comment]
JPG is not lossless.
PNG is heavy, even on load it takes too much RAM, we should avoid using PNG format, the radio has not enough RAM and it will reduce the possibilities for Lua scripts when they will be supported
