### ISSUE TITLE
Bug: 1.0.10 rc8 heli trim still wrong

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#696]
See video.

https://youtu.be/TZ78NhCtopc

When trimming Elevator pitch (down) swashplate tilts backwards. (REVERSE)
When trimming Aileron Right, Swash plate moves right/forward.. CYC2 and CYC1 are moving down.
In this case, CYC1 should move down, and CYC3 should move up. CYC2 should do nothing.

**Comment by Hobby4life** [comment]
[model04.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6871090/model04.zip)

**Comment by m0p3d** [comment]
Whoever implements your request - please ensure to not mess up other things.
E.g. Helimix in SJ/Graupner is very advanced and complex.
Many peoples flying flybarless/flightcontrolers in new machines- this works different and would lead to fatal error if those logics appling there.

**Comment by Hobby4life** [comment]
> Whoever implements your request - please ensure to not mess up other things.
> E.g. Helimix in SJ/Graupner is very advanced and complex.
> Many peoples flying flybarless/flightcontrolers in new machines- this works different and would lead to fatal error if those logics appling there.

There is no mixing involved using FBL,. just plain "stick to output" So no worries there.
It is just for the TX heli mixing, its all wrong thought of, you cant create a "good" heli mixer in just the mixer page only.
- How do apply swash ring?
- How do I apply phase correction? for 3, 4 5 or more blade systems?
These things cant be done in the mixer page.. the must already be done before passing it to the normal mixer.

**Comment by markymars** [comment]
Can confirm too not working.
Tested just now on my T-rex 500 trimming does strang things

**Comment by andrewfernie** [comment]
The behaviour seems to depend on the swashplate selected. I am using the "HR3" with the servo labelled CYC2 in the diagram above at the back rather than the front. The elevator trim goes in the proper direction and the three servos behave properly. Roll goes in the proper direction, but as reported above the CYC2 servo is moving and it should not.

**Comment by Hobby4life** [comment]
Correct, and if you look at the Elevator, and Aileron mixers, you see they controll all 3 servo outputs.
So therefore trim will also controll these 3 outputs,, and thats not correct.
So again, creating a Heli mixer is a normal mixer page is not the way it should be done.
All brands have seperate heli mixing pages for that.. and thats for a reason.

**Comment by bsongis-frsky** [comment]
I checked HR3 and it seems to be right!

**Comment by Hobby4life** [comment]
Impossible due the way it is mixed.

**Comment by bsongis-frsky** [comment]
What is the plate type you used?

**Comment by Hobby4life** [comment]
In hr3. At aileron 1 cyclic must never be controlled by trim

**Comment by bsongis-frsky** [comment]
Ok I think I found it, there is something wrong

**Comment by bsongis-frsky** [comment]
I won't add a new Heli page in 1.0.10 as I would like to release it soon, but:
1) I will remove all suffixes "(Heli)"
2) I want that the trims do work correctly

**Comment by bsongis-frsky** [comment]
An email so that you can test what I changed (I am not at all an heli expert)?

**Comment by bsongis-frsky** [comment]
Should be fixed now, firmware for X20S-EU sent by email for tests

**Comment by andrewfernie** [comment]
RC9 fixed my heli trim issue reported above. Merci Bertrand.

**Comment by bsongis-frsky** [comment]
@andrewfernie do you also have a negative weight on ELE ? Which is your swash plate type? A negative weight there is not normal

**Comment by andrewfernie** [comment]
My aileron and elevator mix weights are both +60. The swashplate is HR3,  but with the servo CYC2 at the rear, so different from the diagram at the top of this thread. I am using an X12S-ISRM.
