### ISSUE TITLE
cant turn off radio when playing music file.

### ISSUE THREAD

**Issue by ltdorn** [FrSkyRC/ETHOS-Feedback-Community#697]
i like to fly with music wav files....   Set up special function to play a music wav file..... once playing, cant stop it and you cant turn off radio until song completes playing.  

Need a watchdog timer on power button to allow radio turn off if commanded by operator.

(and if you could add the backgound music function, play, volume and pause would be nice.)

**Comment by OlegStelmakh** [comment]
The same

**Comment by bsongis-frsky** [comment]
Which release?

**Comment by OlegStelmakh** [comment]
> Which release?
1.0.10 RC8

**Comment by ltdorn** [comment]
yes. 1.0.10 RC8
