### ISSUE TITLE
Custom button bug

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#699]
When you have a custom button activated and another activated, the previous one is deactivated. It would be interesting to be able to activate several at the same time

**Comment by bsongis-frsky** [comment]
Perhaps you could elaborate a little bit?

**Comment by jasalca** [comment]
If I push on button nº1 the led is on,  then  it´s activated
![image0](https://user-images.githubusercontent.com/87758703/126883415-2f00397a-382e-4f33-8aea-609efcfd5490.jpeg)


when I push on button nº3 ,the led nº3 is on but the button nº 1 is off, then  it´s nº3 activated BUT the nº 1 is desactivated
![image1](https://user-images.githubusercontent.com/87758703/126883417-7de9bec3-ffd1-4b19-91fd-2dc5cd4e10b8.jpeg)

I can´t have two buttons activated at the same time.

Do you understand me now?

Thanks

**Comment by ltdorn** [comment]
FYI.... the 6 buttons simulate a 6 position switch... that are NOT independent buttons... you can select only one at a time.

**Comment by Hobby4life** [comment]
Duplicate #523

**Comment by hrenz** [comment]
the 6 function keys / custom button should be programmable
as a switch 1 of 6 as they are now
as  push buttons independent
as  normal on/off switch independent
