### ISSUE TITLE
Vantac MPM for ETHOS

### ISSUE THREAD

**Issue by andika207** [FrSkyRC/ETHOS-Feedback-Community#7]
I want to know if the Vantac module is made by Frsky.... if so will it be supported by ETHOS ?

<a href='https://postimg.cc/0rJ2Kphk' target='_blank'><img src='https://i.postimg.cc/0rJ2Kphk/Fr-Sky-Vantac-MPM-Lite-2-4-G-Transmitter-Module-with-antenna-for-X-Lite-jpg-q50.jpg' border='0' alt='Fr-Sky-Vantac-MPM-Lite-2-4-G-Transmitter-Module-with-antenna-for-X-Lite-jpg-q50'/></a>

**Comment by bsongis-frsky** [comment]
As of today there is no support planned for this module
