### ISSUE TITLE
Receiver position in SXR Calibration Lus incorrectly described.

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#70]
If the position is held as shown in the graphic, then the calibration works. Not so if you follow the explanation.

Graphic 1 o.k.
A description like this would be better: "Horizontal, top side up"

![Horizontal, top side up](https://user-images.githubusercontent.com/16795828/114414888-82bdf000-9baf-11eb-86e4-ebe354e6655b.jpg)

Graphic 2 o.k.
A description like this would be better: "Horizontal, top side down"

![Horizontal, top side down](https://user-images.githubusercontent.com/16795828/114415063-a4b77280-9baf-11eb-8cb5-5c51d8359699.jpg)

Graphic 3 not o.k.
A description like this would be better: "Vertical, pins up"

![Vertical, pins up](https://user-images.githubusercontent.com/16795828/114415148-b567e880-9baf-11eb-9a72-d0bce8b04c88.jpg)

Graphic 4 not o.k.
A description like this would be better: "Vertical, pins down"

![Vertical, pins down](https://user-images.githubusercontent.com/16795828/114415457-fd870b00-9baf-11eb-8e2d-cc4edb1bf156.jpg)

Graphic 5 not o.k.
A description like this would be better: "Legible lettering, pins right"

![legible lettering, pins right](https://user-images.githubusercontent.com/16795828/114415602-1ee7f700-9bb0-11eb-9d2b-89737dfbc0c4.jpg)

Graphic 6 not o.k.
A description like this would be better: "Not legible lettering, pins right"

![not legible lettering, pins right](https://user-images.githubusercontent.com/16795828/114415722-3a530200-9bb0-11eb-9bd7-6cced8ff82b6.jpg)

**Comment by Nicholas-Luoyi** [comment]
I remember I have changed this as suggested. Please check

**Comment by EngelMT** [comment]
@Nicholas-Luoyi 

Check it in english and german language. Works perfect for me now!

Thanks!
