### ISSUE TITLE
Feature request.  Sensor reset switch assignment 

### ISSUE THREAD

**Issue by Droptank** [FrSkyRC/ETHOS-Feedback-Community#701]
Would like to be able to reset sensors with simple switch assigned.  
ex: consumption sensor or vibrations max to be reset

**Comment by STC148** [comment]
what do you mean exactly? it's always been possible.
![Screenshot 2021-07-25 080806](https://user-images.githubusercontent.com/85410070/126889519-4d978121-12c6-468c-8049-b9b9addb4448.jpg)

**Comment by Droptank** [comment]
Sorry, I mean it should be option built into the sensor edit area rather than building a Special function.  Streamlined.  Like timers have the reset option in them.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128149853-e4364c61-9dce-472e-9826-b01a3ba09eda.png)

**Comment by Droptank** [comment]
Perfect!
