### ISSUE TITLE
Mixes Trims

### ISSUE THREAD

**Issue by ravikoth** [FrSkyRC/ETHOS-Feedback-Community#702]
- [ ] All mixes should have the possibility to disable the trim (useful for tail wheel)
- [ ] Free mix should have a this trim feature, when the input is a stick

----

Would be great to have trim option on all mixes & please add direction option on the trims. 
Currently the trims follow the direction of the mix in place (which is the way it should be)
however during relatively complex mixing such as a model airplane with canards.
the trims are reversed & need correcting.

**Comment by Hermann62** [comment]
I agree 100%.

**Comment by hrenz** [comment]
trimmers must be just as invertible as the inputs.
this simplifies a lot of things with the mixers
otx has had this deficiency for years

**Comment by hrenz** [comment]
For somewhat more complex mixers you must have the possibility
to invert the weight in the mixer (this is possible), 
but then the associated trim works wrong (OTX has the same error)
because it stays normal

The simplest way would be 
if you can select in the mixer
Trim ON Normal
Trim OFF
Trim ON Inverse

Then the problems would be solved in general
which occur for example with Elevon- Taileron-, Delta-Mix and others

everywhere where 2-4 channels with aileron and elevator
have to be mixed internally at the same time and direction before they go out to the servos

**Comment by Hobby4life** [comment]
> For somewhat more complex mixers you must have the possibility
> to invert the weight in the mixer (this is possible),
> but then the associated trim works wrong (OTX has the same error)
> because it stays normal
> 
> The simplest way would be
> if you can select in the mixer
> Trim ON Normal
> Trim OFF
> Trim ON Inverse
> 
> Then the problems would be solved in general
> which occur for example with Elevon- Taileron-, Delta-Mix and others
> 
> everywhere where 2-4 channels with aileron and elevator
> have to be mixed internally at the same time and direction before they go out to the servos

Correct!! this is a problem i am facing trimming a heli swashplate while i have negative weight.

**Comment by hrenz** [comment]
Trim ON Normal
Trim OFF
Trim ON Inverse

This allows you  first calculate the mixer mathematics correctly, 
Then you only have to adjust the servo direction in the outputs.

You do not need an auxiliary mixer for intermediate calculation and adjustment.

**Comment by bsongis-frsky** [comment]
Yes there is a need, when you want to have flaps with 50% trim from the ailerons

**Comment by hrenz** [comment]
same problem has OTX
in the inputs you should be able to select
Trim On, 
Trtm Off, 
Trim Inverse

**Comment by SBalaa** [comment]
I'm having the problem were on a complex Jet with Elevons, Canards & Thrust Vectoring  I can't disable the Trim Function on my Thrust Vectoring or Canards. The ability to disable the Trim on any mixes would be of immense benefit. I'm reluctant to fly the Jet until this issue is resolved.

**Comment by npirkes** [comment]
In addition, it should be very useful if we can choose to adjust each trim separately or use master trim option to change them all together (choose for all the trims at once to be fine, medium or coarse)
