### ISSUE TITLE
RF configuration problem

### ISSUE THREAD

**Issue by Paolotandemx20s** [FrSkyRC/ETHOS-Feedback-Community#705]
Run firmware 1.0.10 rc8 on my x20s, problem found in configuring new model, make new memory the RF module already active with receivers already assigned to other models in memory. I assume bugs

**Comment by bsongis-frsky** [comment]
How did you create this new model? From the wizard?

**Comment by Paolotandemx20s** [comment]
Yes, use wilzard configurator.

**Comment by Paolotandemx20s** [comment]
After further tests, new memory seems to clone last selected, so if memory has rf active also new memory has rf active with the same receiver as this last one, on the other hand if old memory has rf deactivated also new memory rf off.
