### ISSUE TITLE
mixer slow function don´t folllow the curve, runs only linear

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#706]
Unfortunately, the curve is ignored and the channel value runs linearly

This can be seen very clearly if you specify a staircase function as the curve: e.g. -100%, -75%, -25%, +25%, +75%, +100%.
The output always increases linearly.

**Comment by bsongis-frsky** [comment]
Slow was applied at the very end, I changed it, the order is now:
1) take input value
2) apply slow
3) apply curve
4) apply weight
5) apply offset
