### ISSUE TITLE
Possibility to hide the top bar / bottom bar in some layouts

### ISSUE THREAD

**Issue by bsongis-frsky** [FrSkyRC/ETHOS-Feedback-Community#707]
To be discussed. Will the buttons be displayed when the user taps on screen, no screens count indicator?

**Comment by bsongis-frsky** [comment]
Related to #592 but needs its own issue for discussion

**Comment by pld74** [comment]
Great Idea! More Screen Realestate

**Comment by mawzthefinn** [comment]
There's a Full Screen layout now, do we need more than one?
