### ISSUE TITLE
настройка режимов полета в одном миксе

### ISSUE THREAD

**Issue by Kasper8888** [FrSkyRC/ETHOS-Feedback-Community#708]
сейчас для настройки Weight UP, Weight Down и Offset, приходится создавать микс для каждого режима полета или в случае выбора Var добавлять строки с выбором каждого режима полета. Было бы хорошо чтобы при изменении режима полета в строках Weight UP, Weight Down и Offset менялось значение. Такая настройка используется в передатчиках CORE, Weatronic BAT64, Graupner HOTT MC32. Данная возможность в разы сократит время настройки самолетов с большим количеством режимов полета применяемых в F3B, F3J, F3F, F5J

**Comment by Hobby4life** [comment]
come on people, do your best to ask questions in english. the developers are already busy enough to solve ethos problems. They are not eager to sit down and translate all the questions.

At the very least, use google translate to translate your question:
 https://translate.google.com/?hl=en

**Comment by hrenz** [comment]
Now to set Weight UP, Weight Down and Offset, one has to create a mix for each flight mode or in case of selecting Var add lines with selection of each flight mode. It would be nice if the Weight UP, Weight Down and Offset lines would change value when changing flight mode. This setting is used in the CORE, Weatronic BAT64, Graupner HOTT MC32 transmitters. This feature will dramatically reduce the tuning time for aircraft with many flight modes used in F3B, F3J, F3F, F5J

Translated with www.DeepL.com/Translator (free version)

**Comment by bsongis-frsky** [comment]
You may use a Var like this:

![image](https://user-images.githubusercontent.com/50834778/127231845-96b85429-6b8e-4972-9c3f-a22513a4fd0e.png)
