### ISSUE TITLE
RSSI hangs next link breakdown

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#709]
RSSI values hanging at 35dB - no change in display no change in logging - next u will notice is link breakdown or much much better RSSI reading
Tested with RC8 x20s, newest Firmwares on SR8pro and GR8 and Radiomodule
[XplorerNAN-2021-07-27-20-09-43.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6890167/XplorerNAN-2021-07-27-20-09-43.csv)
[GOBLIN380-2021-07-27-19-29-56.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6890169/GOBLIN380-2021-07-27-19-29-56.csv)

**Comment by bsongis-frsky** [comment]
Will be fixed in next module release

**Comment by m0p3d** [comment]
What's meant by module release - is this hardware , access firmware or both ?

**Comment by bsongis-frsky** [comment]
RF module firmware update

**Comment by m0p3d** [comment]
Is there already some timeline for the release ? (When to expect )

**Comment by NMO81** [comment]
V2.1.9 for the TD-ISRM Module in the X20 and X20S is already released today 28/07/2021

**Comment by m0p3d** [comment]
V2.1.9 doesnt fix the hanging at 35dB Problem confirmed
But somehow it fixed various strange problems for me - previous 2.1.8 on internal and rX had very strange RSSI readings and i suggest very bad range. Very fast dropdown in rssi while increasing range - especially in range check mode

Example:
https://www.rcgroups.com/forums/showpost.php?p=47522937&postcount=9781

Compare attachements
[GOBLIN380-2021-07-28-17-35-54.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6897832/GOBLIN380-2021-07-28-17-35-54.csv)
[XplorerNAN-2021-07-28-17-29-41.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6897833/XplorerNAN-2021-07-28-17-29-41.csv)
[XplorerNAN-2021-07-28-16-34-16.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6897834/XplorerNAN-2021-07-28-16-34-16.csv)
[GOBLIN380-2021-07-28-16-32-31.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6897835/GOBLIN380-2021-07-28-16-32-31.csv)
<img width="1276" alt="1Bildschirmfoto 2021-07-28 um 17 51 56" src="https://user-images.githubusercontent.com/87205694/127429731-e5596901-eb3a-43da-865f-1af6d1853195.png">
<img width="1280" alt="2Bildschirmfoto 2021-07-27 um 21 41 23" src="https://user-images.githubusercontent.com/87205694/127429743-b35eba81-c765-429d-a89b-9d4827e5852c.png">

**Comment by VancouverUmbrella** [comment]
I think it's worth pointing out that the 35dB RSSI 'floor' and very poor range were previously encountered with some Archer receivers _by pilots not using EthOS_. 

The plot included below was first posted [here on RCG](https://www.rcgroups.com/forums/showpost.php?p=46884273&postcount=26). The poor range and strange 35dB RSSI floor were discussed in that thread. FrSky determined that the receiver belonging to the thread OP was defective and replaced it under warranty.

![Screenshot 2021-04-05 233931](https://user-images.githubusercontent.com/56514835/127504783-d78bb4d0-af5a-40b4-9cde-065a345a44b4.jpg)

**Comment by m0p3d** [comment]
[XplorerNAN-2021-07-30-17-45-00.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6909617/XplorerNAN-2021-07-30-17-45-00.csv)
<img width="1141" alt="Bildschirmfoto 2021-07-30 um 21 03 40" src="https://user-images.githubusercontent.com/87205694/127701832-62df3eef-66fd-4deb-ad33-6201df07b9f1.png">

Recorded with newest Ethos release, RF module FW and Receiver FW 
35dB warning results in every 3min one warning
