### ISSUE TITLE
Gas Suite Lua displayed zeros in the front off for excample U/min and others

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#71]
![Screenshot 2021-04-12 174239](https://user-images.githubusercontent.com/16795828/114422452-9587f300-9bb6-11eb-87b8-d697a83adf84.jpg)

**Comment by bsongis-frsky** [comment]
Your translation? 

![image](https://user-images.githubusercontent.com/50834778/114430271-8f961000-9bbe-11eb-8037-93f6b33468b4.png)

**Comment by EngelMT** [comment]
Yes right, my translation. But why we see 0U/min? It looks not o.k. I think the zero is a place holder vor the value we can set. But it looks not normal like this. Could be better to have in instead "0" "..."?

**Comment by EngelMT** [comment]
I changed it like this. Looks now not as a mistake.

![Screenshot 2021-04-12 185331](https://user-images.githubusercontent.com/16795828/114432001-72fad780-9bc0-11eb-9f10-e51ff915df9f.jpg)
