### ISSUE TITLE
Is it possible to operate Flex in EU-LBT mode?

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#711]
Hello

Is it possible to operate Flex in EU-LBT mode? At the moment it is possible to operate Flex in 868mhz mode, but the 2.4Ghz module is in FCC mode. See Attachment.

Thank you

Enzo

![IMG_20210728_165336](https://user-images.githubusercontent.com/87656206/127351424-f40b0c42-935e-47a5-95c4-af3e722373f0.jpg)

**Comment by Adelaxie** [comment]
Are you using the latest update there(updated yesterday)?
https://www.frsky-rc.com/tandem-x20s/
868MHZ selected?

**Comment by Adelaxie** [comment]
Checked, its the issue of display here ,will fix it.  
The mode is already under LBT when 868MHZ choosed.
