### ISSUE TITLE
Error x20 and version 1.0.10 RC9

### ISSUE THREAD

**Issue by marevalor** [FrSkyRC/ETHOS-Feedback-Community#712]
Dear, I just uploaded ethos 1.0.10 and created a basic plane with 2 ailerons, engine, rudder and elevator. But as you will see when accelerating the elevator also moves and does not have a mixture created. What is this error due to? My X20 is one of the first to manufacture, it is number 12 and because of the different version of the motherboard I already had a problem that you corrected.
Attached video of the problem.

Thanks

[ Video](https://youtu.be/u6M9NIE1wW4)

**Comment by Hobby4life** [comment]
Maybe a basic question, Sticks calibrated?

**Comment by marevalor** [comment]
yes and five times !!!! just in case

**Comment by marevalor** [comment]
remove the mixes created by the wizard and create them as free mix and back to normal. And to be sure I created a model per wizard and it looked good. what could have happened? . Some internal variable that got dirty when I once created a mix motor => elevator ???

**Comment by bsongis-frsky** [comment]
Please do a a video of the ADC inspector, you will find this screen by pressing this button:
![image](https://user-images.githubusercontent.com/50834778/127430999-671aeb19-4d7c-4981-8d55-8853e29dbf5b.png)

**Comment by marevalor** [comment]
Bertrand, as I wrote to you above, I thought that the problem was solved since I eliminated the mixes, I created them again and calibrated again and the problem had disappeared, but today I turn on the radio again and there was the same error, I am attaching the video . I remind you that my radio is one of the first and does not have the same motherboard as a production one (you solved the restart problem for me due to a pin mute issue that my motherboard does not have)
Thanks

[video](https://youtu.be/pcF8YVBh1f4)

**Comment by bsongis-frsky** [comment]
It seems to me like a hardware issue now. When you move the throttle stick, its ADC will move, but the ADC from elevator shouldn't move in the same time

**Comment by bsongis-frsky** [comment]
Reported to Adela

**Comment by marevalor** [comment]
what should I do ? , I have practically not used the radio (due to the pendemic), who is Adela?
