### ISSUE TITLE
Support for GPS Triangle software 

### ISSUE THREAD

**Issue by krokusvej** [FrSkyRC/ETHOS-Feedback-Community#713]
Hi We are to in my model club, there are investigating possibilities to get FRSKY to work a bit like JEti transmittere being able to resieve GPS and Vario meter data and send it to a android mobile or tablet running skynavigator https://play.google.com/store/apps/details?id=app.skynavigator.android.skynavigator&hl=da&gl=US or albatros https://play.google.com/store/apps/details?id=org.rc_electronics.albatross&hl=da&gl=US..  We are both looking for a solution eather where we are able so code some translationsoftware to send the data into the programs or a solutions directly from FRSKY binding directly to the software.

Please don´t hacitate to contact me for more information.. The first thing I am interestet in, is it possible to do with ethos or is it only posible in open TX, if it´s a project thats interesting haw can I/We help?

Question is to support such a solution will it be possible on the Ethos radio X20S?

Best Regards
Anders P. Denmark

**Comment by NorbertHeli** [comment]
That would be very interessting also for me and some other GPS Triangle competitior, most with albatross. 
But first must rcelectronics make a SPort translation for his GPS Sensors ( as for Graupner, Jeti and so on) I think.

**Comment by Jackytreehorn** [comment]
Yes, please! It would be so nice to see FrSky supporting this popular class of high performance gliders. Which other competion of planes could better fit for the X20.
As Anders said above, only support is needed on telemetry to work with **Skynavigator or Albatross**. The rest is 3rd party hardware, which shouldn´t matter. Maybe a good chance to come up with some new sensors! ;-)

**Comment by mawzthefinn** [comment]
The X20S has the ability to send an S.port mirror over Bluetooth, like the other BT-capable FrSky radios. This is done by setting the Bluetooth mode to Telemetry in System->Wireless. The data then can be consumed by any BT-capable device.

**Comment by mawzthefinn** [comment]
Confirmed a bug in 1.4.3, 1.4.4 fixes.

Working with iMSB for me for tracking. Should work in the Android apps as well if they support S.Port format telemetry data.

**Comment by mawzthefinn** [comment]
Closing this off as complete, ETHOS fully supports telemetry mirroring via BT.

**Comment by krokusvej** [comment]
Sorry just have seen your message, I havn´t got it working with ether Skynavigator or Albatross are there any one else there have got this working? 
Do anyone know if there are any LUA scripts supporting translation of the telemetri data sets?

**Comment by mawzthefinn** [comment]
You’d need for SkyNavigator to interpret S.Port format telemetry correctly. iMSB does this for example.
