### ISSUE TITLE
No logging of individual cell voltages on 1.0.10

### ISSUE THREAD

**Issue by Jornor68** [FrSkyRC/ETHOS-Feedback-Community#715]
X20-eu 1.0.10  I have a MLVSS sensor whith individual cell voltages showing ok on the radio, but the logfile has only total pack voltage no individual cells.
On 1.0.9 individual cells was logged ok.

**Comment by W4DJW** [comment]
On the FLVSS the value for the previously added cell voltages was constant at 4.2 volts and never changed throughout the whole flight for the on the onscreen display. The logs were missing the individual cell values all together. I deleted all sensors and rediscovered which left me with nothing but the total voltage for the FLVSS sensor now. This is for logging and onscreen display.

**Comment by RoP09** [comment]
Confirm, i have the original FrSky lipo Sensor on X20 and with 1.0.10 only total voltage shows up

**Comment by Mordee** [comment]
Also confirmed, with the MLVSS and the FLVSS, total voltage only shown, I went through all the sensor options and there is not option activate each cell voltage as in previous firmware.
