### ISSUE TITLE
Throttle trim effects idle

### ISSUE THREAD

**Issue by Joey3dee** [FrSkyRC/ETHOS-Feedback-Community#716]
It's really essential for flying gas models that the trim effects the idle not the centre point of the output. I use flight modes for gas models to have a low/high idle and I'm really noticing not having this feature.

**Comment by MIKE-DAILEY** [comment]
Feature included from day one.  In throttle mix select "Low position trim" ON.

**Comment by Joey3dee** [comment]
That's embarrassing. My bad.

________________________________

**Comment by MIKE-DAILEY** [comment]
No problem, we are here to help.  I fly glow so I made sure the idle trim and cut worked well from the beginning and also works for gas too.
