### ISSUE TITLE
V1.0.10  what about subtrim selection classic or symmetric

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#717]
missing 2 things at trim
at subtrim: selecting classic or symmetric
how can we set trim to subtrim

**Comment by AlwinHaas** [comment]
Yes that is a big Problem, when I do Subtrim the End-positions are still the same. I think they should chance their positions with the same way I do sub trim.

**Comment by mawzthefinn** [comment]
PPM Centre adjust has been added which shifts centre point and endpoints at the same time.

**Comment by mawzthefinn** [comment]
Trim to Subtrim is being tracked in issue #368

**Comment by mawzthefinn** [comment]
Closing as item 1 has been addressed and item 2 has another Issue already open for it
