### ISSUE TITLE
No Shutdown Bye.Wav

### ISSUE THREAD

**Issue by Hill2** [FrSkyRC/ETHOS-Feedback-Community#718]
In the new release it's mentioned about: No wait for all prompts played before shutdown (only wait for bye.wav)

This doesn't happen on the X20 LBT. When I look into the files there is no 'bye.wav' file

**Comment by Hobby4life** [comment]
You have to create it yourself. it is implemented to give the user the option to play it.

**Comment by OldGazer** [comment]
[bye.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6911152/bye.txt)

Change the file extension to wav and copy it to /audio/en/system on the SD card.

**Comment by Hill2** [comment]
But how to create?

**Comment by Hobby4life** [comment]
You can use OpenTXSpeaker: https://www.open-tx.org/2014/03/15/opentx-speaker
Or you can use TTS Automate, it has more natural voices.: https://ttsautomate.com

I have made a file you can load into TTS automate:  https://github.com/Hobby4life/ETHOS-OpenTX-Soundpacks-EN-NL
