### ISSUE TITLE
X10S with Neuron 60 esc telemetry

### ISSUE THREAD

**Issue by BobCotsford** [FrSkyRC/ETHOS-Feedback-Community#72]
I'm getting what appear to be displaced telemetry IDs for an FrSky Neuron 60A, SR6 receiver, X10S + ISRM transmitter running Ethos 1.0.1
![20210412_160202](https://user-images.githubusercontent.com/82290592/114423036-b2202d00-9bae-11eb-8d92-8ab1a7d41b60.jpg)
![20210412_160229 1](https://user-images.githubusercontent.com/82290592/114423115-c532fd00-9bae-11eb-87ce-5adf10d8081a.jpg)

**Comment by rburrow87** [comment]
I think I'm seeing the same issue with my X20 running ETHOS 1.0.1, Archer SR6 running 2.1.6, and Neuron 80 running BLHeli32 32.7.

I also notice that if I tap on one of the ESC sensors and tap on Config, it takes me to the RB 30/40 config menu. Possibly related?

**Comment by BobCotsford** [comment]
Good point, you can see mine is registering RBOX A1 even though I don't even own any RBs and I deleted all sensors prior to discovering them again - twice.  I will try it with UniSens and an FrSky 40A sensor later today.

**Comment by bsongis-frsky** [comment]
Issue replicated, just mixed strings, the unit is right (CELSIUS), and it should be named "Temperature"

**Comment by BobCotsford** [comment]
Please note that the field labelled 'SBEC V' is out by a factor of 10 too (50.42v should read 5.04v)

**Comment by bsongis-frsky** [comment]
Right I have fixed it

**Comment by bsongis-frsky** [comment]
But on my Neuron I get no ESC Voltage value, I wonder why, do you have it?
Perhaps I could send another FW for you to check (I have on of the first Neuron, perhaps something doesn't work properly)

**Comment by BobCotsford** [comment]
SBEC V and A were in OTX since iirc v3.9?

**Comment by BobCotsford** [comment]
Not a problem Bertrand, you have my email, I believe.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/114691780-51146880-9d18-11eb-838c-fc91bb87e111.png)

ESC Current / Voltage = 0
S.PORT frames are 0, I don't believe it's an Ethos issue

**Comment by bsongis-frsky** [comment]
I am not sure I have your email, or I have too many, would you please send me an email, I will answer with a firmware (EU / FCC?)

**Comment by BobCotsford** [comment]
I'll double check that my receiver is on v2.16!  Unfortunately I don't have any way to catch the Sport strings, I'll drop you an email.

**Comment by BobCotsford** [comment]
bobcots at sky dot com!
