### ISSUE TITLE
1.0.10 X20S no"critical rssi warning"

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#720]
I noticed that the "critical rssi warning" is not announced when the warning threshold is undershot.
there is only the warning "low rssi warning" followed by "telemetry lost".
the same with the german language.
the warning thresholds are set to 32/35
the correct wav files are in the sound/system folder.

https://user-images.githubusercontent.com/85410070/127739853-acd9cbbf-9d63-40b9-95d7-01cb41db8373.mp4

![Screenshot 2021-07-31 141418](https://user-images.githubusercontent.com/85410070/127739895-d4edf01f-5318-4e66-b3fa-5483d57adbd6.jpg)
![IMG_20210731_142023897_HDR](https://user-images.githubusercontent.com/85410070/127739898-ce0d048d-512a-435e-bda2-5e86d2bed209.jpg)

**Comment by m0p3d** [comment]
Same see: #709

FrSky doing something on the radio link side or at least on the RSSI,VFR Data Collection
Not part of the changelog
Doesnt match to official recommendation for low/crit alerts at 35/32dB (no sense because they freeze rssi on 35 and next thing is link breakdown)

FrSky official needs to comeout with information regarding the issue and what this means for the customers - before they bring possibly a fix
Maybe nobody is aware of some costomers fly very expensive models and the risk to injure others

**Comment by bsongis-frsky** [comment]
RF again, not related to Ethos. I think it is fixed in the RF firmware which is currently under testing

**Comment by m0p3d** [comment]
Sorry to be very direct and harsh - RF is one of the most important parts of the rc system.
There should be 0 questioning if something is wrong or not.

Team did a great job on ethos improvements - many questions in different forum/groups about acsst and access link performance , range and warnings.

Maybe someone thinks about improving communication and hears / responds the community

**Comment by Adelaxie** [comment]
There will be new release with the fix ,please pay close attention to the FrSky webiste . Thanks.

**Comment by jfint** [comment]
@Adelaxie, you mean a version that will come after 2.1.8 correct?  I would not bug Bsongis with this, but you chimed in.  If this is an RF Issue with receivers taht are specifically meant for some of the more expensive Airplanes out there FRSky needs to pony up and admit the issue right now, and effectively ground those receivers and stop your retailers from selling them.  I experienced this this weekend with a GR8 at 2.1.8 firmware.  I can't afford to replace that place for a LONG time worth of saving, so I'm not happy with FRSky at the moment, Spektrum never had range issues after it had passed a range test.  This GR8 did.
