### ISSUE TITLE
save the log.switch after delete sensor

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#722]
you can insert it that after an update of the firmware not everything is deleted from the log.switch.
or if one deletes the telemetry sensors and searches again remain stored. I now have to rework all airplanes and enter the telemery.

**Comment by bsongis-frsky** [comment]
- if you remove a logic switch, all references to this switch will be deleted from your model
- the same applies to curves
- the same applies to sensors
