### ISSUE TITLE
Elevator Mix is affected by ajusting Elevator Trim

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#723]
X10S Express
Ethos 1.0.10

While looking at the Elevator mix of an existing model with the stick at the center position, I noticed the point was off the normal line.  I looked at all associated settings and could not find any reason for this.  I then adjusted the trim for the elevator and the point moved.

I then created a new plane with 1 elevator, 2 ailerons, 1 throttle and 1 rudder.  The results were the same.  This only happens on the elevator mix.  Please view the attached photos.  The first picture is with the trim in the center position.  Second picture is with max trim and the third is with min trim.

![20210731_101541](https://user-images.githubusercontent.com/81670152/127743441-398841a2-a3ae-427d-9f87-9a3b9b27b6d9.jpg)
![20210731_101620](https://user-images.githubusercontent.com/81670152/127743584-acee5c54-d0d3-4efe-afe0-e763ec665e09.jpg)
![20210731_101651](https://user-images.githubusercontent.com/81670152/127744038-55556a70-9e5b-4bf5-873a-92cfd40d6b76.jpg)

**Comment by Hobby4life** [comment]
I dont know, but it is supposed to do so.
Elevator trim controls Elevato mix.

Or what do you think is wrong?

**Comment by df7320** [comment]
I believe adjusting the trim should only change the outputs. What's happening is that both the mixer and outputs are changing. Its acting like an offset. It was working correctly in 1.0.9..

**Comment by Hobby4life** [comment]
Hmm i dont think so, what you want is subtrim to take care of only the outputs.

Normally in opentx your trims where active in the input page,, thats before the mixer.. 
Now input and mixer are 1 part.. so if you look it that way it works correct.

Anyway I dont see anything unusual from my experience.
What you show to me, seems normal to me.

**Comment by df7320** [comment]
After some more testing it appears that this is only affecting the graph displayed on the Elevator Mixer menu. The mixer and channel operation appears to be working correctly but someone else can verify that.

**Comment by Hobby4life** [comment]
Correct, i see the same and it think this is correct. you littarly see what you are programming.

**Comment by aalain8** [comment]
If I understand correctly: google translation.
Why I can reproduce it on the elevator with the elevator trim and can't reproduce it on the rudder with the rudder trim?

**Comment by Hobby4life** [comment]
Ahh so you mean, Trimming is only visible for Elevator in the mixer graph?

**Comment by aalain8** [comment]
Yes

**Comment by Hobby4life** [comment]
Ok, then thats a bug that has to be fixed.

**Comment by aalain8** [comment]
I just checked on a plane.
The trimmers work as they should, and the travels are good.
In my opinion it's a display problem, and the elevator display is good.

**Comment by marevalor** [comment]
It is the same thing that happened to me with the #712  report that they closed me

**Comment by bsongis-frsky** [comment]
Not at all the same than #712 which is an hardware issue (radio is one of the first prototype sent for tests).
This issue is within Ethos and is fixed for next release 1.0.11
