### ISSUE TITLE
Ethos 1.0.10 emergency mode on text change mix or logic switch

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#724]
When the text length is fully utilized. The transmitter goes into emergency mode after pressing the left delete key. Video attached
https://youtu.be/XdBtctFoQ4M

... Please do not pay attention to the sound in the background. Is only my TV😁

**Comment by STC148** [comment]
the same with the simulator, when the text line is full and the cursor is all the way to the right, when the page key is pressed the simulator crashes.

https://user-images.githubusercontent.com/85410070/127761318-8a8c3275-4819-4e62-bbaf-783c6e31fa8a.mp4

**Comment by FLYN-001** [comment]
I’ve had emergency mode in both mixer & logic switch with just messing about with values & settings while learning the OS. 
Even with text length not filled. Seemed to be random interval. Has done it 3-4 times in 24hrs
