### ISSUE TITLE
X20 files

### ISSUE THREAD

**Issue by seilfly** [FrSkyRC/ETHOS-Feedback-Community#729]
Hi, nice with a little explanation about the difference between the X20 and X20s files

**Comment by Joetrin** [comment]
Use the X20 files if you have an X20.  If you have the X20s with blutooth audio and, use the X20S files.

**Comment by seilfly** [comment]
If I mount the missing bluetooth module in an X20, I will use the X20s file. Is that correct?

**Comment by seilfly** [comment]
> Use the X20 files if you have an X20. If you have the X20s with blutooth audio and, use the X20S files.
> 
> What kind of explanation are you looking for, please?

If I mount the missing bluetooth module in an X20, I will use the X20s file. Is that correct?
