### ISSUE TITLE
v1.0.10 - BUG(s) - Trainer + logic functions.

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#730]
In v1.09 I have setup some logic to detect stick movement on the Master transmitter.
I use this when training heli.
If the master moves one of the sticks, trainer function is turned off.

### **MASTER TX:**

CH1: Destination = Catagory Analogs (Ailerons)
CH2: Destination = Catagory Analogs (Elevator)
CH2: Destination = Catagory Analogs (Throttle)
CH4: Destination = Catagory Analogs (Rudder)

**Logic page:**
LSW1: | A| > X, A= Aileron, X= 15
LSW2: STICKY ON=SI, OFF= LSW1
**Trainer page**
Active Condition = LSW2

In v1.09 using this method worked great, only worked with **Master Stick Input**.
Slave stick input did **not** activate anything.

Now in v1.0.10 stick input from slave **also activates** this logic on the Master. ???

I dont know if this is a bug that slipped in v1.010?
But Slave TX may **never** activate (analog input), logic or something else on Master TX.
Slave only must send stick movement, and master has full control over everything.

I really like to see this fixed, as there is no other way to perform this task now.

**Comment by Hobby4life** [comment]
I have also noticed another bug.

### SLAVE TX:

**Mixer:**
Ailerons CH1
Elevator CH2
Throttle CH3
Rudder CH4

### MASTER TX:
**At the trainer page:**

CH1: Destination = Catagory Channel 1 (Ailerons)
CH2: Destination = Catagory Channel 2 (Elevator)
CH2: Destination = Catagory Channel 3 (Throttle)
CH4: Destination = Catagory Channel 4 (Rudder)

At the receiver only channel 2,3 and 4 are working.. **CH1 is not passed thru.**

**Comment by Hobby4life** [comment]
For good understanding, in all circumstances I dont want to use the "Catagory Channel" I want the MASTER TX takes care of all mixing..

**Comment by bsongis-frsky** [comment]
1st part of the issue
=============
It's done like this by design: the whole stick is replaced by the student stick, if we want it's not the case I fee we need some more options

2nd part of the issue
=============
I cannot reproduce it. I just tested it with an X9D+2019 as slave radio

**Comment by Hobby4life** [comment]
> # 1st part of the issue
> It's done like this by design: the whole stick is replaced by the student stick, if we want it's not the case I think we need some more options

 - OFF
 - REPLACE
 - ADD

That is good as it is now.

Only adding a toggle switch, where you can select if if slave must control full master, or not.

**Comment by Hobby4life** [comment]
Tested 2nd part tonight with Xlite Pro, again CH1 will not be passed thru.

**Comment by Hobby4life** [comment]
I like to know if there is some progress on this (Part 1)?

@Nicholas-Luoyi @bsongis-frsky

**Comment by mawzthefinn** [comment]
Are you still having this issue? There were changes to the Trainer implementation in 1.1.0 and later

**Comment by mawzthefinn** [comment]
The first part is resolved, you can set the logic switches to ignore trainer via a long-press. 

Cannot reproduce the second part
