### ISSUE TITLE
Cannot set Expo to number

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#731]
I have a model which has an Expo mix on the elevator that I cannot set the value of. Normally, if you choose Expo, I can set a value for the expo, with this, I have to choose switches, analogs, trim, etc.  I created a second curve for the elevator and if I choose Expo there I can set a value.  I am not sure how this model became hosed.
[model02.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6913635/model02.zip)
The model name in the zip file should be TRex 470, and I mention this because it is a guess which model file is which. It would be nice if the filenames had some sort of correlation to the name of the model. I may create a feature request for a naming change if one does not already exist.

**Comment by Nicholas-Luoyi** [comment]
Hello!
Please notice that the field which marked with a yellow rectangle on the top right will have a secondary menu by long pressing [ENTER] key on it. Then you will see the "Convert to value" selection. :-)
![52d61c8c4eff64b74b6e8029b644698](https://user-images.githubusercontent.com/58321103/127791021-e56ca2b5-179b-437b-bd02-c92b86a4d487.png)
![33a12e5fcd1dcb4324b71d30a32baf2](https://user-images.githubusercontent.com/58321103/127791024-d64ec4ed-e777-4390-a6d0-301b7ec34afc.png)

**Comment by guycnicholas** [comment]
D'OH!  Thanks!
