### ISSUE TITLE
Switch middle detect and SRX receivers

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#732]
I was having trouble getting my SR6 into self check mode when I finally came across the, "switch middle detect delay" functionality. To get the receiver into self check mode, it seemed I had to set the delay to 0.  This made me wonder where the delay should work. In this case the receiver is detecting output values and see a series of transitions between all 3 values. The delay functionality is apparently holding the value at one end or the other if the transition through the center is less than the preset delay value.
I question whether this delay should be applied to the output or instead just tied to logical functions, like flight mode switching, or logical switches, or special functions.
Setting the receiver to self check doesn't happen very often, and as such, I would be fine just setting the delay value to 0 when I need to do a self check. However, I didn't even know about the functionality (probably my fault). What I would say though, is that I wonder what the correct default value should be. Mine was set to 100, but I think perhaps 0 would be a better start.

**Comment by Mordee** [comment]
I reset my delay to 0 when doing the check and control limits, then set it back to 200ms for normal use, in the past, I have had to delete the switch function, in the mixer, to avoid inadvertent activation of the self check function, which would be disastrous in flight.

**Comment by guycnicholas** [comment]
I considered a feature request around this area but after thinking about it I don't really think it is necessary. The main thing about it was that I didn't really know it existed in the beginning, so I was frustrated trying to figure out why the receiver wouldn't work.  I think a note in the receiver manual might be the best thing to do, just to make sure people trying to set it up are aware that the functionality in the transmitter will affect peoples ability to self check.

**Comment by Mordee** [comment]
Yes same here, the only reason I went looking for that setting was from my experience with openTX, so I guess if a user doesn't have an in depth knowledge of OpenTx setting etc, they wouldn't even think about it, a note in the manual would be great, or at least in the FrSky instruction sheet for the SxR type receivers. Okay take it easy :)

**Comment by guycnicholas** [comment]
Oddly, I have been using OpenTx for the past number of years and didn't notice the delay setting until you just mentioned it. So I went to my X9D 2019 and looked at it is set to 150ms, but on it I have no problem getting the Rx into self check, which makes me wonder why there is a problem with Ethos.  To me it seems the functionality is possibly different, where on OpenTx the delay only applies to logical switches/special functions, whereas on Ethos it applies to the output.  I say this because the Rx needs to see a transition between all 3 states, so on my OpenTx radio it seems the output is transitioning regardless how fast I move the switch, whereas on Ethos it seems it skips right from one end to the other.

**Comment by Mordee** [comment]
I hear ya. What Receiver are you using ? for each experiment or test ? The Archer S6R behaves differently to the previous S6R model in self check and setting mode. I have noticed the Archer will only go into SelfCheck with the low to 0 center delay (ACCESS), however the SxR (ACCST) will go into SelfCheck with a higher center delay.

**Comment by bsongis-frsky** [comment]
Default setting for switch mid position delay set to 0 by default. This issue will be avoided.
