### ISSUE TITLE
V1.0.10: when selecting a source and moving the sticks or switches, the screen doesn’t update

### ISSUE THREAD

**Issue by OB1-OB2** [FrSkyRC/ETHOS-Feedback-Community#733]
In mixer or special functions, when selecting an input for a source or condition, the screen doesn’t update so u can’t see any the effect of pushing a new switch/stick, however, after pushing enter, the proper input has been selected.

for example, if I have mixer source set to  SA, and I select the source to change it, a screen pops up that shows SA. If i push SB or any other switch, the screen still shows SA,  however after going back to the mixer screen, the source is changed to SB.

**Comment by Hobby4life** [comment]
X10? X12? X20?

**Comment by OB1-OB2** [comment]
Sorry. My world revolves the X20S only :)

**Comment by OB1-OB2** [comment]
Hmmm…. I’ll try again tomorrow when I wake up. I was switching models back to back over and over and maybe got the software in a weird state.

**Comment by bsongis-frsky** [comment]
We miss details to be able to reproduce the issue

**Comment by OB1-OB2** [comment]
I say we close this issue. I cannot replicate how I got into that state yesterday, but it involved several model changes and many changes to each model. 

After power up, all is good.
