### ISSUE TITLE
Telemetry announcements come when switching on although switch warnings come too

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#734]
It is a small issue. But it does not seem logical to me that telemetry announcements are made when the transmitter is switched on even though the switches or encoders are not in the position set under Warnings. These announcements should only be made when all switches and encoders are in the correct position or the warnings have been skipped with a button.

**Comment by bsongis-frsky** [comment]
You have to tick "Skip on startup"

![image](https://user-images.githubusercontent.com/50834778/127904713-0cba27aa-bb2a-4c56-9e50-7b1cc18cbd24.png)

**Comment by EngelMT** [comment]
O.k. sometimes the solutions are so easy.
