### ISSUE TITLE
Servo Test mixer not perfect

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#735]
In 1.0.10 we can set a channel we will test. It is good. But without the possibility to adjust the servo travel, the tester is almost unusable. Because if the servo is installed in the model and connected to the flap, it can run against "block" and be damaged.

The following functions in the test mixer would be ideal (like in OTX)

Number of channel/channels or the possibility to select the channels individually
Normal, Inverse
Slow Up/Down adjustable
Weighting and offset adjustable
Lock and release

**Comment by Hobby4life** [comment]
I agree, if you implement a servo travel test.. make it a programmable one with speed/travel/delay/steps.

**Comment by hrenz** [comment]
for a normal universal Servotester use a log Switch with ctimer and a free mixer
you don't need more to be able to set everything freely

**Comment by bsongis-frsky** [comment]
@hrenz this is not exactly the philosophy behind Ethos
