### ISSUE TITLE
Use ADC2 value in formula, e.g. to display % battery charge

### ISSUE THREAD

**Issue by martinvanmiddelkoop** [FrSkyRC/ETHOS-Feedback-Community#738]
I have soldered a simple voltage divider like the old frSky module, and with Ethos 1.10.0 I can use the new Ratio percentage setting nicely to show the correct Voltage in my Telemetry screen.

However, I would love to see the percentage of mAh left in my battery, hence do some calculation and show the result in my Telemetry screen, and base my alerts on. Could be a simple "0-100%" linked to a scale of "from Voltage" to "to Voltage".

**Comment by Hobby4life** [comment]
Duplicate (dubbel :-) ) #554
