### ISSUE TITLE
No Vario Tone missing for new models in 1.0.10

### ISSUE THREAD

**Issue by Aerial-Image** [FrSkyRC/ETHOS-Feedback-Community#739]
Sorry updated to the latest firmware 1.0.10 over the weekend (Tandem X20S) - I have a tone vario tone on an old model in the memory assigned into a switch - but tried to create a new model today and can't find the Vario in the special functions switch??

**Comment by enzo-molinari** [comment]
To activate the vario sound:
Go to telemetry / open Vspeed / check the "activate sound" option.
