### ISSUE TITLE
XAct Servo Lua uses "Range" in the same way as the range test. 

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#74]
In German, however, it has different meanings. On the one hand "range test" and on the other "rotation range or angle of rotation".

![Screenshot 2021-04-12 174915](https://user-images.githubusercontent.com/16795828/114423700-b7ce4080-9bb7-11eb-93ae-5d397db273b3.jpg)

**Comment by bsongis-frsky** [comment]
How is it possible we use RANGE_CHECK for Range Check and RANGE for Range

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/114429453-b273f480-9bbd-11eb-9d5d-8c8700dc3e0c.png)

**Comment by bsongis-frsky** [comment]
So the mistake is yours...

**Comment by bsongis-frsky** [comment]
I have fixed for now like this:
![image](https://user-images.githubusercontent.com/50834778/114429623-dd5e4880-9bbd-11eb-961a-cd00333be616.png)

**Comment by EngelMT** [comment]
You are right. My fault out of an older translation.
