### ISSUE TITLE
No motor RPM - Neuron 40 ESC

### ISSUE THREAD

**Issue by Aerial-Image** [FrSkyRC/ETHOS-Feedback-Community#741]
Also after 1.0.10 update I now show show 0 RPM on my Neuron 40 ESC  :( .... all the other telemetry volts - amp etc usage seems ok

**Comment by bsongis-frsky** [comment]
Did you try to remove this sensor and discover again? I think the limits are not correct

**Comment by Hobby4life** [comment]
@bsongis-frsky 

About RPM, you mention Poles in RPM configuration..
The manual talks about Pole **pairs** maybe you can check this if this is correct.

**Comment by Aerial-Image** [comment]
Yes I removed sensors and re added them - all is ok now!
