### ISSUE TITLE
Neuron 60  setting SBEC V not possible with X20 ETHOS

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#742]
X20S, S6R,  binding ok, Neuron60, Sport
Telemete delete, new search, all Telem  values ok

then Konfig SBEC/ESC
SBEC V setting at X20 possible but no change at Neuron60

---------------------
Same test with TX16S, S6R, Lua,  all ok, setting SBEC V works

**Comment by EngelMT** [comment]
Seems to be also a problem with X10 S EXPRESS and ETHOS. Customers reported it.

**Comment by bsongis-frsky** [comment]
I just tested, the SBEC V is correctly sent and re-read. So it's not an Ethos issue. I will forward to the person in charge of RF

**Comment by bsongis-frsky** [comment]
Now if you exit the screen directly, the voltage value which is currently in editing mode will be written correctly. But the original issue is still there, it seems that this value does nothing, the real SBEC voltage is not modified.

**Comment by hrenz** [comment]
Yes the real SBEC Voltage at Neuron itself is not modified

what struck me
At TX16S Phy ID read is 16 (ther it works well)
At Ethos  Phy ID read is 10 

could be dez and hex the same value

**Comment by bsongis-frsky** [comment]
Closed by mistake

**Comment by bsongis-frsky** [comment]
@hrenz Are you saying that the TX16S succeeds to change the real SBEC Voltage?

Ethos works with HEX there, just like on the S.PORT protocol documentation. 0x10 equal 16. Nothing interesting there.

**Comment by hrenz** [comment]
Yes, with TX16S and Lua it works well can set SBEC V at Neuron as I like 
Its my background system for tests

I have X9d+2019 and X9E too for Tests

alreday clear 10hex = 16dez

**Comment by yequhuashiren** [comment]
https://user-images.githubusercontent.com/62365833/128274327-ed34e9a0-0df2-4234-bd65-ec64a2f4923c.mp4

![IMG_8944](https://user-images.githubusercontent.com/62365833/128274857-fa01cf32-0b90-4681-b2ef-1a9a6c958b8c.jpeg)

**Comment by bsongis-frsky** [comment]
It was an issue on Ethos. Fixed in 1.0.11
