### ISSUE TITLE
Function Switches as source for Logic Switch

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#743]
I don't see a way to choose a Function Switch as a source for a Logic Switch, can this be added?

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128152627-4f34dbc3-f9b2-4327-9d13-ab50c0f47779.png)

**Comment by guycnicholas** [comment]
I see that, but I am wondering why I can't use them in all function modes, like = ?   I like to use logical switches rather than physical ones so that it is easier to change my mind about what switch I want to use, or if I give the program to someone else, they can more easily change the switch assignments as they are all in one place. Likewise, in the mixer the Function switches are omitted from the Source property, why?  I guess I expect them to show up in all the places regular switches show up.
