### ISSUE TITLE
Timer bugs after Ethos 1.0.10.

### ISSUE THREAD

**Issue by cperedamas** [FrSkyRC/ETHOS-Feedback-Community#745]
Timers are no longer being started by any of the throttle conditions.  It must be started using a physical or logical switch.

**Comment by cperedamas** [comment]
Is it possible that my firmware update did not proceed properly? I cannot get it work on any model.  I tried deleting the timers and recreating them.  Still the same problem.

**Comment by MIKE-DAILEY** [comment]
Try testing by creating a new simple model.

**Comment by cperedamas** [comment]
Followed your suggestion.  On a new model, the timers will work normally.  But on the ones created before 1.0.10, they will not.  They were working fine on 1.0.9.

**Comment by MIKE-DAILEY** [comment]
The model I'm testing with was created in 1.0.9.

**Comment by bsongis-frsky** [comment]
Perhaps there is something different on your Throttle mix?

**Comment by cperedamas** [comment]
this is the full ethos info if it helps;
1.0.10 FCC #4dbf211b
Storage 0.0.9
Stick ADC
Int mod. HW 1.4.0, FW 2.1.8

I changed all the throttle mixer values on an old model to be the same as the new model, for which the timers work.  I also deleted all logical switches.  The only special functions present are "play track".  The problem persists.  I also cloned an old model.  Timers in the cloned model do not work either.  All three throttle trigger types work on new models, but none work on the ones created under 1.0.9. 

I also recalibrated analog sticks under hardware settings.  This did not change anything.

**Comment by philandroid36** [comment]
Since 1.0.10 I can no longer make timers.
The timers of old models before 1.0.10 continue to work. But not the new timers in a new model.

I also tested a new timer (very simple) in an old model, it doesn't work either.

1.0.10 EUU #4dbf211b
Storage 0.0.9
Stick ADC
Int mod. HW 1.4.0, FW 2.1.9 (EU)

**Comment by cperedamas** [comment]
> Since 1.0.10 I can no longer make timers.
> The timers of old models before 1.0.10 continue to work. But not the new timers in a new model.
> 
> I also tested a new timer (very simple) in an old model, it doesn't work either.
> 
> 1.0.10 EUU #4dbf211b
> Storage 0.0.9
> Stick ADC
> Int mod. HW 1.4.0, FW 2.1.9 (EU)

**Comment by philandroid36** [comment]
it is all very confusing to me. I am sorry.
I did an analysis again this morning:
- I think I have a problem only with the timers of a model created in 1.0.10 candidate 3

I have no problems with the older models.
And I did a test again this morning with a new model and everything is OK.

I will therefore completely recreate the model whose timers no longer work to solve my problem.

**Comment by commsart** [comment]
X20S, 1.0.10 FCC.
Same issue, tried changing names, re-creating timers, cloning Thr mixes. Still, Thr Absolute does not move the timer. Works if activated with a switch.

**Comment by MrD-RC** [comment]
My friend had this happen today. Nee model on 1.0.10. The timer was working, but then stopped. Checking the setup, it was exactly the same as my timer that worked. 

I think half the problem here is not being able to select the throttle source. It was as if the throttle was not picked up at all by the timer. Even a new timer was the same. It was tried with throttle percentage and throttle activation. No throttle cut on the model either. I could not replicate the issue on my 1.0.10 setup.

**Comment by MrD-RC** [comment]
My friend just sent me the model file. But after another look at home, I could see that the reset had not been set correctly. They wanted to use the momentary switch, but just flicked it when setting the switch position. So the timer was resetting constantly. Setting the reset switch correctly, it works fine.
