### ISSUE TITLE
Auto offset gps altitude

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#747]
X10s isrm
Ethos v1.0.10

Hi where can I find the auto offset for the gps sensor?
I have tried resetting senor but after a couple of seconds it starts to rise again.
Thanks

**Comment by bsongis-frsky** [comment]
Rise by how many meters? It could be the GPS Altitude precision...

**Comment by Liverboy77** [comment]
I have just reset altitude and the it dropped to -242ft.
How do I alter the precision.
Thanks

**Comment by mawzthefinn** [comment]
Is this still occurring?

**Comment by mawzthefinn** [comment]
Closing due to no response to request for info
