### ISSUE TITLE
Comment section in logical switch page.

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#749]
Logical switches can be complicated and often I find I really have to think about the point of one of my logical switches. I think it would be nice if there was a text block where I could enter a comment about the item to remind me, or tell someone else, what a particular switch is for, or how it works, or ?

**Comment by bsongis-frsky** [comment]
But which length for this comment?

**Comment by guycnicholas** [comment]
I am not writing the UI so I don't know your space limitations, but I could envision it being a a line item just like source or value. The text in the field could be longer, and it would just add a "..." if it overflowed the container. But a tap to edit, could bring up a longer description.
I do notice on the Logic Switch list page, there is a description item, that shows what the switch is, I could see the comment being appended to that.
![image](https://user-images.githubusercontent.com/5494702/128215369-d8f3ed65-bb7e-4871-962f-45b8ce87a792.png)

**Comment by 00steven** [comment]
A way to group related switches in a map/group, would keep clear what the switch is used for.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/133423722-24123a4c-074a-4638-86bd-c12ad08ed8da.png)

![image](https://user-images.githubusercontent.com/50834778/133423751-53c88796-82fd-4d19-b229-92f9defce8d0.png)
