### ISSUE TITLE
Telemetry 'RBOXV1' and 'RBOXV2' 'Sensor Lost' using RB30 when supply over 10 volts

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#750]
Telemtry sensor RBOX V1 and RBOX V2 is lost whenever supply voltage is over ten volts. Cannot edit sensor range above  ten volts, however the recomended input for the RB30 is 11-24 volts. 

Running latest release 1.0.10 and latest firmware for RB30

**Comment by j-watkiss** [comment]
https://user-images.githubusercontent.com/69600292/128255187-e2fa28ea-6b01-41e9-9d20-076cbf36e1ee.mp4

Cannot move sensor range over 10 volts this seems to be 'max'

**Comment by enzo-molinari** [comment]
You're right. Under 1.0.10 the maximum value is 10 volts!
I had done the configuration under 1.0.9. At that time it was still possible to go higher.

**Comment by bsongis-frsky** [comment]
Protocol limitation changed to 24.0V
