### ISSUE TITLE
Trim function !

### ISSUE THREAD

**Issue by Ybmmc** [FrSkyRC/ETHOS-Feedback-Community#751]
Could the trim function be added to the selective
Center trim, Left end point trim, right end point trim, offset trim,
so that the stroke of the servo will not change,
and all channel have trim control option

**Comment by hrenz** [comment]
its normal trim and symmetrisch trim

**Comment by Ybmmc** [comment]
RE: Hrenz , Propose the trim function work on X20s Ethos not OTX .

**Comment by AlwinHaas** [comment]
Than please just make a update for this Problem.

**Comment by mawzthefinn** [comment]
Bumping this for consideration

**Comment by jasc76** [comment]
Coming from OTX I don’t get this issue? If I set the endpoints, why do you want to shift them? This might drive the servos into the physical limits.

**Comment by mawzthefinn** [comment]
The missing item is asymmetric trim, where trim only affects one end of the channel range. In ETHOS this is only available with the Throttle mixer right now.

**Comment by bsongis-frsky** [comment]
Duplicate of #3455
