### ISSUE TITLE
Norwegian translation for EthOS-menus

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#754]
Here are a Norwegian translation of the menues in EthOS.

[no.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6941227/no.txt)

**Comment by bsongis-frsky** [comment]
All the `*******` and missing `"` fixed

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/128509272-b4252974-1687-490b-8957-89ff0df5ba85.png)

**Comment by mmasch** [comment]
Thank you Bertrand. 
Looking forward to the release  :-)

Morten.
