### ISSUE TITLE
Preflight check

### ISSUE THREAD

**Issue by federicobelfi** [FrSkyRC/ETHOS-Feedback-Community#755]
I will very usefull to have a checklist to be read and checked before start the flight. In very complex models there are so much operation that could be forgotten.

Having the checkbox is an huge plus!

![image](https://user-images.githubusercontent.com/13049718/128426351-373e7b2c-9d3a-4957-9887-4c951de51dfd.png)

**Comment by mawzthefinn** [comment]
This could be a good extension of the Checklist feature
