### ISSUE TITLE
Remember #462 Flight Mode Offset Point. 

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#756]
Hello, I want remember to fall #462.
It is impossible to have at every flight Mode an serperate offset point.

At the Moment you have to make a  curve for every flight Mode to chance the offset point. This need a lot of time.

**Comment by mawzthefinn** [comment]
Addressed in v1.3.0 with the Offset mixer when combined with a VAR mixer.

Note you need to combine a VAR mix (to get a table of offset values selectable by Flight Mode) and the Offset Mixer (which can take the output channel of the Var mixer as a source for the Offset value) to achieve this.
