### ISSUE TITLE
SubTrim setup at output chanal

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#757]
Hello, I thing is was impossible to have an option to chance that the end points ouf the Servos walk with the suptrim . And one option that when I chance the Subtrim position that the end positions of the Servo are still at the same position.

**Comment by centertrim** [comment]
If this is implemented it needs to be an optional mode like in OpenTX.  I personally find it highly annoying on other systems when I change the center/subtrim and then my carefully set endpoints (max throws) also change.

**Comment by centertrim** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/717

**Comment by AlwinHaas** [comment]
@erweiterung wann wird diese umgesetzt?

**Comment by mawzthefinn** [comment]
The addition of PPM center in v1.2.11 addresses this.

Subtrim changes the center point without affecting endpoints.
PPM Centre shifts the currently set range by a designated offset in uS.

Both settings are independent.
