### ISSUE TITLE
Delays to flight modes

### ISSUE THREAD

**Issue by FBarrao** [FrSkyRC/ETHOS-Feedback-Community#761]
It should be ineresting to have delays for changing the flight modes, when using independent trims for diferent flap setings, things are much more smooth using a delay to position the nwe trims.

**Comment by FBarrao** [comment]
Sorry, I don´t meant a delay, but a slow down, so, there is a transition between one flight mode and another..

**Comment by hrenz** [comment]
not now, will and must come

**Comment by bsongis-frsky** [comment]
Duplicate of #768
