### ISSUE TITLE
step mask doesn't work

### ISSUE THREAD

**Issue by thpk69** [FrSkyRC/ETHOS-Feedback-Community#762]
Hi, i've just update my Tandem X20S to 1.0.10 EU. 
![IMG_20210807_192603_2](https://user-images.githubusercontent.com/88592885/128608908-7c1bb3de-a5bf-4b7d-bfd0-4edd3bd93d2b.jpg)
But the gauge doesn't appear.
I have the system bitmap files in bitmap folder with the good png file.
I cannot understand how to fix it.

**Comment by MIKE-DAILEY** [comment]
Try a cell that has numbers.

**Comment by thpk69** [comment]
I tried in GPS coordinate and it doesn't work too

**Comment by Hobby4life** [comment]
Did you update the FLASH contents?

there is a file called **mask_step.png**

**Comment by thpk69** [comment]
Yes, it's the last flash contents. I put in bitmap\system\.
The file you speak is in this folder

**Comment by Hobby4life** [comment]
> Yes, it's the last flash contents. I put in bitmap\system.
> The file you speak is in this folder

Just to check.. you copied/replaced all files to the 8MB flash drive right?

**Comment by thpk69** [comment]
> > Yes, it's the last flash contents. I put in bitmap\system.
> > The file you speak is in this folder
> 
> Just to check.. you copied/replaced all files to the 8MB flash drive right?

Thanks a lot! I didn't understand where copy the files. I putted all int the SD CARD.
 I plug the transmitter in bootloader to have USB connection. I put all of the files in the internal flash and it works.

You're perfect.

I closed the issue.
