### ISSUE TITLE
v1.0.10 - Emergency mode

### ISSUE THREAD

**Issue by mortorp** [FrSkyRC/ETHOS-Feedback-Community#764]
I was editing a model on the X20S and suddenly the screen get black and the only text was "Emergency mode".

**Comment by mortorp** [comment]
Firmware version 1.0.10, EU
Internal module FW:2.1.9

**Comment by Hobby4life** [comment]
You must try to be more specific in what you where edditing, values? text? what value? what text?

**Comment by bsongis** [comment]
If it's a mix name or any other name the bug has been already reported and fixed - 1.0.11

**Comment by mortorp** [comment]
I was in "SpecialFuncs" setting up "Play Track" on switches, when I get the error message.

**Comment by bsongis-frsky** [comment]
Do you succeed to reproduce it? I would like more information

**Comment by mortorp** [comment]
Hi, I have not been able to reproduce it.

**Comment by bsongis-frsky** [comment]
Did you change a name, like the model name or a mix name or a channel name, flight mode name during the same session? This produces a memory corruption in 1.0.10 and it has been fixed since

**Comment by pld74** [comment]
This happened to me twice as I was changing the Output Channel on severals mixes. I tried to repeat it but could not. I'll advise once and if it happens again.

**Comment by helikeith** [comment]
IT HAPPENED TO ME ALSO. same firmware.
i was adding a curve with 2 points. I was fast scrolling to get my value, i think i bumped the enter while scrolling so began scrolling around on the curve screen then EMERGENCY MODE. I have tried to duplicate and after several tries x20 totally locked up, Had to pull the battery. I can not reliably repeat.

**Comment by Jamest95max** [comment]
Hi , I have also had emergency mode but I was in the GPS widget, changing the coordinates to match my field coordinates , I was using the scroll wheel but the coordinates only change once then nothing except beeps but slow as if it's locking up, but then emergency mode, have not been able to reproduce emergency mode but changing coordinates still only moves once and no more, X20S, all latest updates, and ethos is the v1.0.10

**Comment by skyfly74** [comment]
I occur the same emergency mode, X20 EU,  1.0.11.
Editing a new logical switch i press return on the screen and had the emergnecy mode,
Try to reproduce but don't do it again.

**Comment by Hobby4life** [comment]
Duplicates #826

**Comment by pld74** [comment]
I had emergency mode appear 3x in a row this morning. Now I can replicate sometimes and sometimes I cannot. All I was doing was selecting a different model, from one extreme to the other, basically 1st model and last model.

Any logs I can send you to view?

X20S
Ethos 1.0.10

**Comment by Hobby4life** [comment]
There are major fixes coming up in RC4 regarding Emergency mode apearances.
So keep a lookout on v1.0.11 RC4. Hope bertrand will release this one soon.

**Comment by pld74** [comment]
> There are major fixes coming up in RC4 regarding Emergency mode apearances.
> So keep a lookout on v1.0.11 RC4. Hope bertrand will release this one soon.

OK thanks

**Comment by mawzthefinn** [comment]
@mortorp Have you had this issue re-occur after v1.0.11?

**Comment by mawzthefinn** [comment]
closing as stale
