### ISSUE TITLE
Feature Request: Slow up/slow down & offset in Flap>Elevator mix

### ISSUE THREAD

**Issue by DJMacGregor** [FrSkyRC/ETHOS-Feedback-Community#765]
It would be very useful to have offset, slow up and slow down added to the Flap>Elevator mix that is already available.  I can achieve this using a free mix.  I have included a screenshot of my modified flap>elevator mix.
![Modified Flap-Elev mix](https://user-images.githubusercontent.com/86719029/128626909-0a83772b-e1a3-482d-9891-a2d8797f4818.jpg)

**Comment by DJMacGregor** [comment]
Apologies - I see this has already been requested #136

**Comment by mawzthefinn** [comment]
Closing as a duplicate as noted.
