### ISSUE TITLE
x20s os 1.0.10

### ISSUE THREAD

**Issue by aeroplanebelg** [FrSkyRC/ETHOS-Feedback-Community#766]
feature request
Hello, could you please include in models selection, the function moved to .... plane, helicopter, .... for the moment there is, select, duplicate, delete.
Did not know how to change a model of cathegory ...
Thank you for your attention.

**Comment by Hobby4life** [comment]
just swipe the screen when in model select

**Comment by aeroplanebelg** [comment]
thank you for your reply but I think you did not understand ..... when a model exists in drone for example, we should be able to move it in plane or glider for example as in otx or other ...... thank you to the team

**Comment by Hobby4life** [comment]
Why do you want to move a plane to a helicopter catagory? that makes no sense. What's the purpose of those catagories then?

Better is to have a "User" or "Favortite"  catagories.
"User"  a real catagory where you can place all kinds of models.
"Favorite" a catagory where you can place somekind of shortcuts to existing models from other catagories.

**Comment by aeroplanebelg** [comment]
thank you for your answer, yes I agree with you ideally, it is enough to create the model in the right category but ... for the moment, Ethos still has some bugs and sometimes, I found a best solution in another category. This is how some gliders are found in airplanes and vice versa ...... in open tx it's simple we move the model and we talk more about it !!!
Ethos is under construction and I agree to play the game but the goal is still to do better otx isn't it? (who can do the most can do the least)
Thank you for your attention . This was only a proposal.
Under ethos since os 0.17 ..x 20s + x12s and otx since 2014.
Good luck to the team.

**Comment by Hobby4life** [comment]
You say models get mixed up in another catagories?

**Comment by aeroplanebelg** [comment]
no, it s me...I chose to create a model in another category simply because certain mixes did not or did not work well in the right category.
I thought to put them back in the right category after ..... but hey it's not possible for the moment.
As already said, it's new and there are bugs ...... os version 1.0.11 will remove some bugs and create others ..... but everyone knows that. This is why we participate at our level to find out what is wrong.
In resume no bug in this menu just a request ...up.... move model.... That's all ...
