### ISSUE TITLE
Moving logical switches does not work properly

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#767]
Moving logical switches does not work properly

 If you move a logical switch from the end of the list to the beginning, the references of the remaining switches are not updated.
and are therefore shifted by one and consequently, of course, wrong.

Example:
Take the GAS mixer and set a logic switch in the input.  
(e.g. the 3rd of 5).
Now generate a new log. Switch at the very end of the list of log. Switch (up to here everything is OK)
Now move the log. switch from the last to the first position 
(here it happens)
Check in the GAS mixer which log. switch is used. 
Switch is used (it has NOT been moved).

Remark:
- I have not noticed this faulty behaviour with other mixers, but that doesn't mean anything, it's bad enough that it affects the GAS mixer.  Switch is used (it has NOT been moved).

Some works ok, some not, here its a list
https://frsky-forum.de/index.php?thread/5835-verschieben-von-logischen-schaltern-funktioniert-nicht-richtig/&postID=76879#post76879

![Error at log switch moving001](https://user-images.githubusercontent.com/6217896/128639986-93393911-6ee4-4603-8329-d46ed1db3308.jpg)

**Comment by Hobby4life** [comment]
What firmware?

**Comment by Hermann62** [comment]
Firmware is 1.0.10 and X20 radio.

**Comment by Hermann62** [comment]
Unfortunately not fixed with 1.0.11 either !
