### ISSUE TITLE
Slow between flight modes

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#768]
In addition to the slow elevator compensation for flap mixes as previously requested, slow changes/date in and out between flight modes would be good to avoid abrupt changes in trim etc

**Comment by Hobby4life** [comment]
Duplicates of #599 , #93 , #42 and I gues there are many more.

I hope this will be implemented in v1.0.11

**Comment by bsongis-frsky** [comment]
Duplicate of #93
