### ISSUE TITLE
Group mix items.

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#769]
In the below image I have 3 items I needed to create snap flaps. I think it would be nice if I could group the 3 of them into a single row. I am think that if you could end up with it acting like the Hardware page where there are 3 items each containing a title, followed by a set of items. 

![image](https://user-images.githubusercontent.com/5494702/128786798-45cf8967-3f18-4abc-840a-e345e6a3a6e7.png)

![image](https://user-images.githubusercontent.com/5494702/128787148-c751b198-f376-4bc0-9215-20f8dd5efb82.png)

**Comment by Nicholas-Luoyi** [comment]
A new view of mixer table is coming on the way. :-)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/148550729-3c37d1fd-83c3-4d30-90c4-182a7ff2863a.png)

**Comment by bsongis-frsky** [comment]
Work in progress, we still have to unify how we show an "active" line vs a "disabled" like, here it's a green dot, but everywhere we use Bold vs Grayed (and in Flight Modes we use Bold + Yellow vs Grayed)

**Comment by aalain8** [comment]
I'm usually a fan of improvements.
Here I'm not sure what to think.
The feature is under development and doesn't show the full potential, I hope I'm wrong, but from my point of view it makes the overall view of the mix less understandable.
I think a simulator version should be released to ask testers for their opinion before releasing a beta.

**Comment by guycnicholas** [comment]
Visually, the "root" items, "Channel1", "Channel2" etc. should be pushed left so that the sub-items appear indented.  I think the problem with the image above is there is no differentiation between the items.
Second, to your active/disabled issue. Logical switches have very nice highlighting, red vs. green. However, when you get into something like a mix, where the text changes from normal to bold, it is far harder to tell what is going on.  I would personally prefer something more obvious, and perhaps more consistent across the board to indicate active vs. not.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/148740787-8e0502da-274c-48b1-a31c-2165218dab38.png)
