### ISSUE TITLE
Up/Down arrow items seem wrong. 

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#770]
Shouldn't the up/down arrows have arrows in them?
![image](https://user-images.githubusercontent.com/5494702/128787315-cd564536-24dd-47b9-8070-5d2189717043.png)

**Comment by Nicholas-Luoyi** [comment]
Hello! Please confirm that you have updated your X20 flash source with the X20_FLASH.zip file in the release tag. Thanks!

**Comment by guycnicholas** [comment]
Thanks @Nicholas-Luoyi  I copied the bitmaps/system folder from the X20_FLASH.zip into the bitmaps folder on the flash drive. I can't find any other documentation on what should be done with the folder.
