### ISSUE TITLE
Lua-telemetry?

### ISSUE THREAD

**Issue by Aerial-Image** [FrSkyRC/ETHOS-Feedback-Community#772]
Will the script 'lua-telemetry' for iNAV run on Ethos on a X20S?

**Comment by OldGazer** [comment]
Not yet...  Supporting LUA is not as easy as changing a couple of lines of code.  Just be patient.  I'm waiting for LUA support so I can use Yaapu Telemetry.

**Comment by bsongis-frsky** [comment]
Duplicate of #202
