### ISSUE TITLE
Use Var (from mixer library) as a Source

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#774]
Perhaps I am missing something, but it seems the only way for me to use a variable (mix) is to assign an output to a channel.  For example:
I setup a "rate" variable with a few values based on a switch.
Set that rate variable's output to an unused channel.
Have each item that wants to use that rate, set to use the "rate" channel as a source.

What I would rather do is use the variable itself as the source rather than having to go through a channel.

**Comment by bsongis-frsky** [comment]
VARS will be added to the firmware soon
