### ISSUE TITLE
Screen style Black and white , flight modes are not appreciated in green 

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#775]
When  you select the black and white wallpaper ,flight modes are not appreciated in green color. Would it be possible to change the color ? for example in red or dark blue. thanks
![IMG_1142](https://user-images.githubusercontent.com/87758703/128945036-d4b67b26-0f1d-4e61-9ef0-44352d2f08a1.jpg)

**Comment by Hobby4life** [comment]
Same for light grey or white in grey backgrounds. Better contrast would be very welcome. Specially in model select. Catagories are hard to see in daylight.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/129180927-ef2f6560-d494-42ec-b800-7cb5fff02851.png)

![image](https://user-images.githubusercontent.com/50834778/129180944-defd657b-e7c6-4126-9ec4-e4ce17a379da.png)
