### ISSUE TITLE
Wireless trainer + Telemetry on Master

### ISSUE THREAD

**Issue by r1000ru** [FrSkyRC/ETHOS-Feedback-Community#777]
Is it possible to transfer telemetry to the phone on the Master, while it receives data about channels from the Slave? This would be useful to enable control from a computer or tablet, with simultaneous display of telemetry and the ability to immediately intercept control on the transmitter. It would also be possible to display telemetry on the phone, while using a wireless headtracker.

**Comment by bsongis-frsky** [comment]
I don't think it is possible to have a link with both a trainee radio and a phone, on the same radio.
Asking for confirmation...

**Comment by r1000ru** [comment]
You are right that the GAP Peripheral role cannot connect to two GAP Observers. But in this case, two roles are used: GAP Peripheral to connect to the Trainer Slave and GAP Observer so that the phone can connect to the transmitter.
[https://e2e.ti.com/support/wireless-connectivity/bluetooth-group/bluetooth/f/bluetooth-forum/931138/cc2541-cc2541-where-to-get-simpleble_comboroles-example](Link to TI forum)

**Comment by r1000ru** [comment]
It would also be great to make another type of connection - a BLE joystick, for using a wireless connection in simulators. Windows, Mac and Linux support BLE HID devices out of the box.

**Comment by hrenz** [comment]
or SBus Out for wirless trainer and Telemetry on Master
