### ISSUE TITLE
Request: Make the write logs a global function

### ISSUE THREAD

**Issue by npirkes** [FrSkyRC/ETHOS-Feedback-Community#778]
Can you please make an option to set the writing log function from the system menu and it will affect all the models (instead of setting it up for every model separately)

**Comment by hrenz** [comment]
yes, global functions for things we do for all modells
log Data, screenshots and so on

**Comment by pld74** [comment]
Great suggestion. As the moment I don't see a Global Variable/Function Area. Am I correct in this statement?

Glad to see this being implemented in 1.0.11. Looks like a great build!!!

**Comment by Ceeb182** [comment]
Unlike OpenTx where there is an interface for local functions and an interface for global functions, I think it would be interesting to have one single interface with all functions. 
But then how to distinguish global functions from local functions? 
Simply by adding a label to indicate whether it is local or global. 
There are advantages to this proposal:
- it simplifies the user experience with a single user interface
- we can quickly transform a local function into a global function and vice versa
- it allows to see immediately if a function is detrimental to another one
This principle can also be generalized and applied to other Ethos features.

**Comment by pld74** [comment]
> Unlike OpenTx where there is an interface for local functions and an interface for global functions, I think it would be interesting to have one single interface with all functions.
> But then how to distinguish global functions from local functions ?
> Simply by adding a label (tag) to indicate whether it is local or global.
> There are advantages to this proposal :
> 
> * it simplifies the user experience with a single user interface
> * we can quickly transform a local function into a global function and vice versa
> * it allows to see immediately if a function is detrimental to another one
> 
> This principle can also be generalized and applied to other Ethos features.

Great suggestion but the point of Global is that it resides with system setting and logical with models.

**Comment by Ceeb182** [comment]
It is possible to put a shortcut in the system menu which leads to the unique interface of functions management with an active filter on the "*global*" tags.
In the functions interface, the UI has a filter that allows you to quickly sort the functions : *global*, *local*, *global AND local*.

**Comment by pld74** [comment]
> It is possible to put a shortcut in the system menu which leads to the unique interface of functions management with an active filter on the "_global_" tags.
> In the functions interface, the UI has a filter that allows you to quickly sort the functions : _global_, _local_, _global AND local_.

Let's see how they implement it and tweak it from there.

**Comment by Ceeb182** [comment]
> Great suggestion. At the moment I don't see a Global Variable/Function Area. Am I correct in this statement?

See #779 about Global Var, and feel free to comment.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/136040158-be58ffcf-bb84-4867-8916-d90e9e4fdb00.png)

**Comment by Ceeb182** [comment]
Great ! 👍
