### ISSUE TITLE
New X20S and Archer R8 pro not registering or binding

### ISSUE THREAD

**Issue by PeterBeretta** [FrSkyRC/ETHOS-Feedback-Community#780]
I received my new X20S yesterday, created a model and tried to register and bind the Archer R8 pro that came as part of the package. The R8 Pro would not register or bind. I updated the firmware on both the RX and internal ISRM to the latest available but still the same problem. A new Archer GR6 registered and bound with no problem. The radio came with Ethos 1.0.7. I will try updating it to 1.0.10 today. Could this be an issue with Ethos or the receiver?

**Comment by jreis1** [comment]
if you can bind a GR6 with no issue, I would say the problem is in the Archer R8 you got. :/

**Comment by Hobby4life** [comment]
Try to reflash firmware via smartport. Then try registering again.

**Comment by PeterBeretta** [comment]
I could only flash the firmware via the smart port because it was not bound. I re-flashed the R8 Pro twice. It did temporarily register but would not bind. When I tried to register it again, the TX just shows "Waiting for the Receiver". On the RX the green LED stays on but the red LED flashes rapidly.

**Comment by PeterBeretta** [comment]
I also tried deleting the models and starting again but no change. Also changed the "Owner Registration ID" to see if this would make a difference. I re-tested the GR6 and it worked, no matter what value I put in the "Owner Registration ID".

**Comment by jreis1** [comment]
Are you flashing the right firmware on the Archer R8 ?

**Comment by PeterBeretta** [comment]
I downloaded the following from the FrSky Website: Archer-X_2.1.8.frsk

**Comment by PeterBeretta** [comment]
Problem solved, was my bad. I was connecting to the RX with the battery incorrectly. Strange that the RX came on.
