### ISSUE TITLE
Cloning a model does not copy special functions page over to the new model 

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#783]
When you clone a model, the special functions are not cloned. Since most of us use the same switches and tracks in special functions I suggest that this data also gets copied when cloning a model.

**Comment by bsongis-frsky** [comment]
I think it copies the special functions, it's just that if you clone your current model, the very last modifications are not cloned

**Comment by bsongis-frsky** [comment]
Are you sure? I cannot reproduce it

**Comment by dwheeld** [comment]
I use a 'Master Model', which contains everything I need, when adding new models to the transmitter. This is done by cloning it and then editing the cloned copy. I have done this at least 5 times and it has always copied the special functions.

**Comment by pld74** [comment]
Interesting that now it is working. I’ll
Reopen if I encounter this again. My bad. 

@dwheeld That is exactly my methodology. A master model and clones from it.
