### ISSUE TITLE
X20, DSC Socket with SBus in/out, not only CPPM in/out

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#784]
the DSC socket has only CPPM in/out so far
It would be much better if it could also do SBus in/out.
Selection with cable CPPM or SBus

that would make a lot of things easier

**Comment by Hobby4life** [comment]
For what makes this easier??

**Comment by hrenz** [comment]
Think about it
Master/Slave with all SBus receivers possible
with SBus In/Out all receivers can be attached
with CPPM In/Out you always need a special
special receiver 

The internal SBus pin no longer exists.

**Comment by Hobby4life** [comment]
Ok I see, I can see the advantage of connecting a SBUS receiver for wireless trainer system.
DSC must have SBUS-IN then, next to PPM in.

**Comment by hrenz** [comment]
and SBUS-Out next to PPM Out

you can then make Para-In  to  SBus-Out
or SBus-In to Para-Out
or SBus_In from a Receiver

**Comment by hrenz** [comment]
Frsky has no longer ACCESS receiver with CPPM-signal
but all have SBUS-Out

So wie can use the DSC-Socket for SBUS In or SBus Out

**Comment by mawzthefinn** [comment]
I think the solution proposed in #1297 might be even better, putting the functionality in the module bay, which also can power the receiver which the DSC port cannot.

**Comment by jasc76** [comment]
I also vote for a sbus in
I use it for a head tracker. Besides svbus in I also need +/- 5V to power the tracker conveniently. If its the DSC socket then fine :-)
I would also solder to the mainboard and put a socket somewhere ;-)

**Comment by yak-54** [comment]
bad idea it will isolate lot radios if you cant use DSC  as  CPPM-signal in 
i train lot people with other brands as well
what would be good it to have CPPM-signal in the module bay so i dont have to run wires to DSC socket like this plug 
be able to plug receiver in the bay

![213126154-cd3bee12-12cf-4a64-85b1-c61b7c0bedd1 (1)](https://user-images.githubusercontent.com/9161926/213888334-67aa50c9-ee8b-4483-9444-4631f38a5434.jpg)

**Comment by mawzthefinn** [comment]
Nobody is suggesting the removal of PPM support, but the addition of SBus as a selectable protocol for the DSC port.

**Comment by Target0815** [comment]
It makes sense to separate the input or output of protocols:

**Module Bay:** 
Output: previous module types and PPM, SBUS, CRSF, other RC protocols via a new "Generic" module type.
Input: S.Port, S.Port Passthrough 

In the Module Bay, this could be used to connect the previous modules, but also external RF modules like Dragonlink or RFDesign and others, which partially return S.Port or S.Port Passthrough telemetry.

**DSC Plug:**
Input: PPM, SBUS

Here SBUS would be additional to realize wireless trainer applications with receivers that do not have PPM output anymore, which is quite rare now. Likewise, head trackers could provide their output via SBUS.

**S.Port Plug**:
Output: S.Port
Input: S.Port, S.Port Passthrough

If no input is possible in the Bay module, S.Port Plug could be used to read in S.Port and S.Port Passthrough.


The question arises whether an extension at the transmitter is generally useful. SBUS input for wireless trainer or head tracker is certainly interesting for some users. 

SBUS Output for Dragonlink or RFDesign incl. input from S.Port/S.Port Passthrough would alternatively also be possible without any problems via a repeater setup (RX and RF module external) without having to connect anything to the transmitter or make changes in Ethos.

**Comment by mawzthefinn** [comment]
You want S>Bus as an input on the module bay to allow for use of Linker modules (trainer units)

S.Port should have S.Bus out as well, to allow setting of SBus servo channels (like the Servo Channel Changer)

**Comment by Target0815** [comment]
> You want S>Bus as an input on the module bay to allow for use of Linker modules (trainer units)

I would rather suggest the DSC port for this, because it is "traditionally" intended for trainer operation. And for the power supply for an extra battery. A tinkering action it is anyway, or do you know Linker modules for the Lite Bay?

> S.Port should have S.Bus out as well, to allow setting of SBus servo channels (like the Servo Channel Changer)

I can not judge. Isn't it so that with an external Servo Channel Changer also only S.Port for the configuration is used?

**Comment by jasc76** [comment]
Imho the module bay is not a good solution because you would loose the module bay.

**Comment by mawzthefinn** [comment]
> Imho the module bay is not a good solution because you would loose the module bay.

It would support pre-existing hardware on the X12S and X10’s.

**Comment by mawzthefinn** [comment]
> > You want S>Bus as an input on the module bay to allow for use of Linker modules (trainer units)
> 
> I would rather suggest the DSC port for this, because it is "traditionally" intended for trainer operation. And for the power supply for an extra battery. A tinkering action it is anyway, or do you know Linker modules for the Lite Bay?

The Linker modules are designed to use the module interface, they require hardware mods to use the DSC port

> 
> > S.Port should have S.Bus out as well, to allow setting of SBus servo channels (like the Servo Channel Changer)
> 
> I can not judge. Isn't it so that with an external Servo Channel Changer also only S.Port for the configuration is used?

No, Sbus is also supported by the SCC, they also work with Futaba SBus/SBus2 servos, including the newer S-Uxx0 series which have no XACT equivalent.

**Comment by lightbulbjim** [comment]
My vote is for the module bay rather than the DSC socket. Personally I would like to see if I can squeeze an RS or M+ inside the stock module bay cover.

This is just a software change, right? Could we select from both the DSC port _and_ the module bay and keep everybody happy?

**Comment by mawzthefinn** [comment]
PPM and SBus input are already available in the module bay on the 1.5.0 nightlies

**Comment by lightbulbjim** [comment]
Nice, I saw that it's an option in the nightly but didn't know if consensus had been reached on DSC vs module bay.

**Comment by yak-54** [comment]
its only been
 1 year 11 months 5 days
21 hours and 27 minutes

**Comment by jasc76** [comment]
Well the module bay is not optimal because I run Elrs or Crossfire modules and !! want to use my head tracker. If the bluetooth bugs get smoked out so it reconnects easier (last known device) I can live with that

**Comment by bsongis-frsky** [comment]
SBus in/out is now implemented in 1.5.0
Available for tests in nightlies

**Comment by yak-54** [comment]
> SBus in/out is now implemented in 1.5.0 Available for tests in nightlies

 X12S and X10’s. ? or only Tandem radios
