### ISSUE TITLE
When you edit one model and add channels, they are not added in the mixes section

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#785]
![IMG_1148](https://user-images.githubusercontent.com/87758703/129424946-e70704e3-0e8f-4cee-8be8-2ca7c18bef08.jpg)
In this example I have one channel for motor and one motor channel appears on the mix screen
![IMG_1149](https://user-images.githubusercontent.com/87758703/129425179-fa5b3eba-c343-466a-b7d0-eba3955a8c6a.jpg)
All correct at the moment.
But if I edit this model and I add one more channel of motor , and I add flaps for example
![IMG_1152](https://user-images.githubusercontent.com/87758703/129425338-00623000-ce4b-41ca-ba8d-7a2e2bd6b8ac.jpg)
Now the channels I added do not appears on the mix screen
![IMG_1149](https://user-images.githubusercontent.com/87758703/129425512-3aa12a1f-0686-43ed-a811-2c62207e8229.jpg)
No new channel in motor and no new channel in flaps

I think it is a bug because I think the new changes should appear on the new mix screen

**Comment by pld74** [comment]
You must execute the “reset all mixers” after any model changes. It’s at the bottom of the model screen. Hope that clears up your issue. Let us know.

**Comment by jasalca** [comment]
Thanks
