### ISSUE TITLE
Altitude configuration problem

### ISSUE THREAD

**Issue by Paolotandemx20s** [FrSkyRC/ETHOS-Feedback-Community#787]
i run firmware 1.0.10 on x20s, bought an Archer GR8 but fail Vario configuration, do good job on logic switches and special functions, but no vario.
adjusted the volume in sound, checked other parameters but nothing. think i miss Vario menu item in the choice of special function. Or hidden function that I don't know, if to be able to kindly explain. thank you.

**Comment by Hobby4life** [comment]
Go to telemetry, lool for vspeed sensor.
Edit. Then almost at the bottom of the page select a source for vario

**Comment by Paolotandemx20s** [comment]
Thanks, sorry for not thinking about this, wonderful work.
