### ISSUE TITLE
1.0.10 X20/X10 convert bug

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#788]
when a model created on the x20 is transferred to the x10, the right/left slider is converted to ext1/2

![X20](https://user-images.githubusercontent.com/85410070/129461650-b3429938-278e-465b-a9c8-f4a89f31249e.jpg)
![X10](https://user-images.githubusercontent.com/85410070/129461656-8792f8ce-a139-438b-bcdf-52fe8b9c2d44.jpg)

**Comment by STC148** [comment]
and ACCST is converted to ACCESS

![X20](https://user-images.githubusercontent.com/85410070/129462474-67d2d7c7-2f52-4941-a194-9e9fc0e1255e.jpg)
![X10](https://user-images.githubusercontent.com/85410070/129462476-db4e019f-8810-4a8e-bf74-6238d34f7b47.jpg)

**Comment by bsongis-frsky** [comment]
Only models stored with release 1.0.11 (or above) will have these 2 conversions
