### ISSUE TITLE
[X12s] No option available to use internal AND external antenna at the same time

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#79]
When going to Settings => HF-Settings => Options I can only select if I want to use the internal OR the external antenna.
But I am missing an option to use both.

X12s on Ethos 1.0.1
ISRM-S-X10S (HW 1.10.; SW 2.16. (EU)
System language: German

**Comment by WismyYao** [comment]
The internal and external antennas do not support simultaneous use

**Comment by PeterBeretta** [comment]
From the Tandem X20S Manual:
"Choose the INT MODULE. Then turn ON INTERNAL RF, select the OUTSIDE or INSIDE ANTENNA ( Dual internal antennas and external antenna work simultaneously while selecting the OUTSIDE ANTENNA.)"
[TANDEM X20S -Manual.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7143106/TANDEM.X20S.-Manual.pdf)
Is this correct? Or is it only the X12S that cannot have both internal and external antennas active?

**Comment by Hobby4life** [comment]
> From the Tandem X20S Manual:
> "Choose the INT MODULE. Then turn ON INTERNAL RF, select the OUTSIDE or INSIDE ANTENNA ( Dual internal antennas and external antenna work simultaneously while selecting the OUTSIDE ANTENNA.)"
> [TANDEM X20S -Manual.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7143106/TANDEM.X20S.-Manual.pdf)
> Is this correct? Or is it only the X12S that cannot have both internal and external antennas active?

Only with old XJT module, not with ISRM upgrade module.
This is even not possible with OpenTX and FrOs

**Comment by PeterBeretta** [comment]
Hi,

Will it be possible to have both internal and external antennas functioning
on my Tandem X20S?

Kind regards,

Peter Beretta

Cell: +27 82 328 3197
A member of unashamedlyethical.com

**Comment by Hobby4life** [comment]
No, not at the same time
