### ISSUE TITLE
Fullscreen widget  for *.txt file  to read my settings, switches and so  on

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#790]
X20
would be helpfull to have fullscreen widget for a Info  *.txt Textfile
so read my Settings, Switsches, Funktions, ....
a simple txtfile, self written, (or later autogenerated)

*. txt  file name same as Modellname: example Modster2400.txt

because have now lots of div modell-typs with diverent Switches, Funktions, Flightmodes

(nearly OTX has)

**Comment by aalain8** [comment]
+1 for the full screen widget

**Comment by pPRODEVEN** [comment]
Bonjour,
C'est exact, il manque un fichier texte info à l'ouverture de chaque modele (tres tres important . La batterie 3S, 4S ou .....
Un rappel de tel inter pour ex ouverture du train d'atterissage

**Comment by centertrim** [comment]
Similar to the reason for https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/233

**Comment by centertrim** [comment]
Being able to edit this information from the radio itself would be ideal.  Normally I would want to make a note to myself on the radio, and not from a computer.

**Comment by pPRODEVEN** [comment]
Oui meme si c'est un fichier txt ou doc que l'on dépose dans la radio, le principal c'est d'avoir une petite check list des points important concernant le modele que l'on s'apprete à faire voler.

**Comment by mawzthefinn** [comment]
Yes, this would be a nice addition, and a use for the big screen.

**Comment by pPRODEVEN** [comment]
Bonjour,
Surtout maintenant de plus en plus nous avons des fonctions plus ou moins spécifiques pour chaque modèle et quel accu mettre du 3S, du 4S ou 6S aussi suivant le modele.....
Enfin un réel complément indispensable.
merci d'avance Monsieur SONGIS

**Comment by mawzthefinn** [comment]
With 1.5.0 there is now the ability to add a text file for the preflight window. 

It's not fullscreen though.

**Comment by pPRODEVEN** [comment]
Bonjour,

Merci d'avance, et elle est pour quand la version 1.5.0 ?

**Comment by mawzthefinn** [comment]
1.5.0 est due quand c'est fini. Beaucoup de changes en 1.5.0

**Comment by mawzthefinn** [comment]
This change is now in 1.5.0

**Comment by pPRODEVEN** [comment]
Bonjour, 
Alors si j'ai bien compris, c'est pour maintenant la version 1.5.0 ? avec la check list pour chaque modèle ? et bien sur tout plein d'autres choses.
Alors un grand merci à tous ceux qui ont fabriqué cette version et qui ont travaillés sur ce projet.
Merciiiiiiiiii

**Comment by bsongis-frsky** [comment]
On n'a jamais été aussi près, mais il reste du boulot !

**Comment by pPRODEVEN** [comment]
Ok merci pour votre reponseLe 8 nov. 2023 08:59, "Bertrand Songis @ FrSky" ***@***.***> a écrit :
On n'a jamais été aussi près, mais il reste du boulot !
