### ISSUE TITLE
Vario settings,  2 times the same field Range

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#791]
ETHOS X20 Vario
there is the Field Range 2 times ?  -10,0m/s  +10,0m/s
or is it ony a wrong translation text
![screenshot-2021-08-15-41173](https://user-images.githubusercontent.com/6217896/129474223-05f6819c-a9a0-4be6-a7cc-fcc0adc6ce64.jpg)
![screenshot-2021-08-15-37837](https://user-images.githubusercontent.com/6217896/129474224-2a0567b3-a589-4f0d-9a34-4e4c5601df8b.jpg)

**Comment by bsongis-frsky** [comment]
This is a Range for both, but the context is not the same:
- first is the Sensor range
- second is the Vario range
