### ISSUE TITLE
SxR receiver default Channel range

### ISSUE THREAD

**Issue by peterskotte** [FrSkyRC/ETHOS-Feedback-Community#792]
When setting up a sXr receiver on ethos, the default channel range is 1 to 8
However the necessary channels needed is 12. 
If one isn't focused on that, and changes the range, the entire setup doesn't move forward. 
Since channels from 9 onward doesn't work.
Maybe an idea would be to default to 16 channels on the sXr revivers to avoid issues?

**Comment by MIKE-DAILEY** [comment]
The default range was changed to 1 - 16 with 1.0.10.   Are you using 1.0.10.?

**Comment by peterskotte** [comment]
Yes. Mine still defaults to 8ch.

**Comment by MIKE-DAILEY** [comment]
Testing just now again using a X20 with 1.0.10. and creating a new model the channel range defaults to 1 - 16.

**Comment by bsongis-frsky** [comment]
Right, default is 16CH
