### ISSUE TITLE
Enhancement/Feature request GPS Widget

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#793]
The GPS widget works great, but can always be better ;-)

I know there are many more important things to work on at the moment, but I have some suggestions.

**1. Entering and Saving coördinates / togheter with image file.**

- Better input of coördinates. with a numeric keypad or like time and date.
- Use a external text file, name must exactly match the map image filename, that contains all needed coördinates for that particular map.
- If a external file is used, it Ethos will read it, copies this to the meta of the BMP file, and deletes the external file. Or keep file is meta is not used.
- If a user enters coördinates manually, Ethos will copy this to the meta of the BMP.
- If the meta is not possible then create a corresponding text file with the manually entered coördinates.
- This way it is easier and quicker to add a GPS map to a new model.

**2. Full screen GPS Widget**

- I know this feature is in progress, just to summ things up.

**3. Position on map.**

- Make it a triangular shape, and use Telemetry GPS Heading/Bearing to control the triangular shape point towards forward heading.

**4. No Fly zone boundairies.**

- At some clubs there are NO FLY Zones, it would be nice to "draw" these boundairies with the touch screen as overlay on the GPS map.
- Selecting the amount of corners, and user can drag and drop these corners to the correct positions.
- Save these boundairies to the same external text file matching the map image file name, or store in BMP meta.
- Result flying in or outside these boundairies must be available in logic.

**5. Auto Select (zoom) map image function.**

- User must add the desired GPS map widgets, then Ethos will switch between the best matching map image if plane is flown out of a map image.

**Comment by miksterr** [comment]
All great ideas Hobby4life . I setup the map yesterday and entering the coordinates was not ideal.

**Comment by Jamest95max** [comment]
Same here desperate to use GPS with my local field map but inputting coordinates is a nightmare, either it would take forever or it jumps past anywhere near, ie I want example 63,60,0,0n
It'll jump from 61, to 65 so I cannot choose the same coordinates as my map picture
Any suggestions welcome
Thanks in advance
X20S
Ethos 1.0.11

**Comment by Hobby4life** [comment]
> Same here desperate to use GPS with my local field map but inputting coordinates is a nightmare, either it would take forever or it jumps past anywhere near, ie I want example 63,60,0,0n
> It'll jump from 61, to 65 so I cannot choose the same coordinates as my map picture
> Any suggestions welcome
> Thanks in advance
> X20S
> Ethos 1.0.11

When creating a map widget, first edit the coordinates.. then select a map.. this will increase dialing in a coordinate much faster.

**Comment by krokusvej** [comment]
Hi could it be possible to add the features from Sky navigator or Albatros to this ? So we could get more interested in flying GPS triangle contests!

**Comment by mawzthefinn** [comment]
Closing as the bot failed to close this off on March 11
