### ISSUE TITLE
EU Version 900M Power Problem

### ISSUE THREAD

**Issue by H3adsho0ot** [FrSkyRC/ETHOS-Feedback-Community#794]
Hi everybody.

When I switch the 900M output power from 25mW to 200 or 500 (those three are the only that I have) I lose connection to my rx. I can only get it back when switching back to 25mW. How can I fix that?

Thanks for your help!

**Comment by STC148** [comment]
If you change the power, the receiver must be re-bound.
Remember that in the eu version, telemetry is only available at 25 mw.

**Comment by bsongis-frsky** [comment]
Feel free to reopen if needed

**Comment by bsongis-frsky** [comment]
@WismyYao would you please add a popup to warn the user he has to BIND again?

**Comment by H3adsho0ot** [comment]
> If you change the power, the receiver must be re-bound.
> Remember that in the eu version, telemetry is only available at 25 mw.

Is this also true for flex firmware? Or is it possible to change the power on the fly with this version?

**Comment by mortorp** [comment]
Is it also possible to get telemetry when 200 and 500 mw is selected?

**Comment by pld74** [comment]
How about FCC and Power/Bind relationship? Have to 'Bind' after a power change as well?

**Comment by H3adsho0ot** [comment]
> Is it also possible to get telemetry when 200 and 500 mw is selected?

Not with EU Firmware. With Flex and FCC it is possible.

**Comment by pld74** [comment]
If 900Mhz Receiver Broadcasting Power must be pre-selected, it should be implemented as a prompt as follows:

Example: 
Select Register Receiver
Prompt for what Power Setting <select value>
Select Register

or if at bind, change Register to Bind for the above flow...

**Comment by pld74** [comment]
> If you change the power, the receiver must be re-bound.
> Remember that in the eu version, telemetry is only available at 25 mw.

How does the FCC and 900mhz receiver Register/Bind/Power Setting need to be selected, same way? Documentation is unclear.
