### ISSUE TITLE
Request: Offset in Mixer

### ISSUE THREAD

**Issue by align59** [FrSkyRC/ETHOS-Feedback-Community#797]
Would be nice to have the option to set offset points in the mixer which are activated by flight modes. 

For example if i want to put thermal mode and lower down both Ailerons on my glider i could just set an offset i can activate with a flightmode.

At the moment as far as i can tell only in free mix there is the option to setup  an offset and its not connected to flight modes.

**Comment by mawzthefinn** [comment]
This can be done by combining the new Offset Mixer and a Var mixer.

The Var mixer gives you a table of selectable values output to an arbitrary channel, the Offset mixer can use the Var mixer's output channel as the source of its offset values, then output to any number of channels needing the offset applied.
