### ISSUE TITLE
Which version is the latest?

### ISSUE THREAD

**Issue by Sailor-Boy** [FrSkyRC/ETHOS-Feedback-Community#799]
I'm a little confused.
I loaded the new 1.0.10 firmware version onto my X20S about 2 weeks ago.  Everything seems OK but I could not, for the love of gravy, get it to announce any Telemetry Values (ie, RSSI, RX-voltage, Lipo voltage, etc.).  Through the process of elimination I found another x20S owner who had performed the same firmware upgrade and whose X20S would announce values!  We determined that his firmware version was newer than mine by the date but still had the same version number, 1.0.10.  I went to GitHub and downloaded the 1.0.10 firmware again and loaded it. Surprise! now the Play Value functions work!  What the heck?
Now I read in the Issues section there is a problem with RSSI not announcing.  This has lead into a discussion about signal loss.  The author states he is running Internal Module 2.1.9 (FCC).  I have 2.1.7 (FCC).  Do I want the latest 2.1.9? Are there any issues with 2.1.7?  Does this not upgrade when loading the newest firmware?

**Comment by OldGazer** [comment]
There are two separate firmwares involved. 

One firmware is the operating system for the radio electronics.  This is ETHOS 1.0.10.

The second firmware is for the Internal Serial Radio Module (AKA ISRM).  

Updating one does not update the other...

ISRM firmware is here:  https://www.frsky-rc.com/tandem-x20s/

**Comment by bsongis-frsky** [comment]
You have to flash your radio with Ethos, then the TX module with its firmware. Your RX must be using the same release than the TX module.
