### ISSUE TITLE
Modal Dialogues

### ISSUE THREAD

**Issue by mpjf01** [FrSkyRC/ETHOS-Feedback-Community#8]
I'm hesitant to comment on what is now an old simulator so understand that the issue I mention may have already been addressed in V16.

The dialogues that I see are modal, that is they force the operator to press buttons on specific order to go down levels and the the reverse order to back out. 

They should be designed such that a user can press on any visible icon at any time and activate the underlying process, regardless of how he got there. This has been a fundamental requirement of a GUI since they have existed.

**Comment by mpjf01** [comment]
Looking at V16 SIM now it is released the matter is unchanged.

**Comment by bsongis-frsky** [comment]
Which dialog do you have in mind? I don't think we can get rid of modal dialogs here, it's not a technical issue!
