### ISSUE TITLE
[X12s] Possible improvements to navigate through menus

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#80]
I just flashed ETHOS to my X12s tried to set up a plane (glider) and I found three things that massively interrupted my workflow repeatedly:

- when in a scrollable menu (e.g. "HF-System") I can only use the rotary knob to scroll from top to bottom 
=> I would like to jump to the bottom and scroll upwards by turning the rotary knob in the other direction

- when in a scrollable menu (e.g. "HF-System"), having scrolled down a bit and I hit "return" it will take me to the top of the page
=> I would like to return to the previous menu right away; I could use the rotary knob to scroll up if I want to

- when in the "mixer" menu i click on a mixer line and it opens a menu to let me choose what I want to do (edit, add, clone...) 
=> I would like to go directly to the edit mode if I click on a mixer line, instead of getting all the options
=> to get to the options-popup I would like to long-press enter 

X12s on Ethos 1.0.1
ISRM-S-X10S (HW 1.10.; SW 2.16. (EU)
System language: German

**Comment by Target0815** [comment]
This is probably because Ethos is developed for touchscreen displays. This makes the operation much smoother than when only keys or the scroll wheel are used.

The X12S does run Ethos, but with some limitations.

**Comment by mawzthefinn** [comment]
A couple comments on this issue.

For #2 a double-click of RTN gets you to the previous menu
For #3, long-press takes you directly to edit. This is consistent with other UI items where you have one action for the options menu and another action for the default option (in Models, in File Manager, etc)

#1, scroll looping in menus would be nice. It does loop in contextual menus so this is inconsistent right now.

As to the touch-centric design, I find the X12S to work VERY well with ETHOS, although there are a couple cases where the correct input is non-obvious, generally when a ‘+’ button is present on the touch build, but not on the non-touch version. Model creation was the hardest one for me to get sorted. I actually use the physical buttons a lot even on the touch radios.
