### ISSUE TITLE
LiPo sensor lowest cell

### ISSUE THREAD

**Issue by commsart** [FrSkyRC/ETHOS-Feedback-Community#801]
X20s, 1.0.10.

Good movement in the telemetry area. Yet we still need the lowest cell from a LiPo sensor, please. 

There is always one weak cell in a battery and it needs to be monitored, current calculation of average cell voltage hides the issue.

**Comment by bsongis-frsky** [comment]
Did you see this option?

![image](https://user-images.githubusercontent.com/50834778/129672644-c438394a-815c-4645-8f6b-e98179748b6b.png)
