### ISSUE TITLE
Sensor creation wizard

### ISSUE THREAD

**Issue by janekx** [FrSkyRC/ETHOS-Feedback-Community#802]
As Ethos is prety easy to set some parts become not very friendly in sensor settings. Mean settings for Cmin and so. I suggest to make small sensor wizard what help to make sensor in a few steps. 
Sensor wizard will check sensors connected like MLVSS/FLVSS, FAS 40/100/150 and offer selections like Cmin, Cmax, Max, Min and other settings and make the sensor self. 
Right now construct special function for Cmin is not very easy and have many steps.

**Comment by bsongis-frsky** [comment]
What is the purpose of this:
- Automatically create special functions?
- Automatically create logic switches?
- Automatically create Home widgets?
Side note: CMin is not a sensor, just a property

**Comment by janekx** [comment]
Yes it is not sensor, but get result like Cmin is complicated. I think to make Spec function with switch to activate to help set this.

**Comment by bsongis-frsky** [comment]
There are so many options, that I cannot imagine which questions would ask this wizard
