### ISSUE TITLE
Request: Cels script for MLVSS FLVSS widget

### ISSUE THREAD

**Issue by Mordee** [FrSkyRC/ETHOS-Feedback-Community#803]
I really love the widget 'Cels' that takes the telemetry from the MLVSS and FLVSS and displays them as an icon of each cell in the pack along with the combined total. I would really appreciate that in a future release.

**Comment by Ceeb182** [comment]
I didn't understand if this is a request for improvement or a congratulation to the developers ??  

For information, *Jet_Flyer* announced this widget would be integrated in the next version. (see the post: https://www.rcgroups.com/forums/showpost.php?p=47544469&postcount=9901)

![LipoWidget](https://static.rcgroups.net/forums/attachments/3/3/1/6/5/a15205149-12-image_2021_07_30T13_56_12_777Z.png)

**Comment by Mordee** [comment]
Yep that's close enough. Thanks for revealing it to me :)
