### ISSUE TITLE
Filenames for models

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#804]
I think the current filename convention could use a little help. Using names like model01, model02, etc. makes it difficult to share files. Personally, I would rather have the filenames match the model names. I would not care that I cannot have two models with the same name.  I would guess the model naming UI could perhaps use a UI treatment like the logical switch area does where the switch name turns red/green as it turns off/on.

As an example of why the current methodology is undesirable. I just went to Mike Shellim's site to check out his Ethos template and this is a quote from his instructions:

> 3. Copy the model file f3f-ethos_10.bin to the \models folder
> 4. Rename the model file as modelNN.bin, where NN is any unused model number.

That is a little annoying.

**Comment by bsongis-frsky** [comment]
You may use any filename for your models.
Point 4. you mentionned is useless

**Comment by MrD-RC** [comment]
@bsongis-frsky what are the naming conventions for model filenames. As in the character limit. Is it 8.3?
