### ISSUE TITLE
1.0.11 RC1 X10S emergency mode

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#805]
the transmitter goes into "emergency mode" without further operation.
after deleting the models folder and creating a new model, the transmitter works normally. if you now copy any model from the 1.0.10 backup into the models folder, the transmitter goes back into "emergency mode".

example file attached

https://user-images.githubusercontent.com/85410070/129809374-9e4b4e0b-b8eb-4049-b8db-d02dcf79871f.mp4

[model04.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7003374/model04.zip)

**Comment by Devil-IdT** [comment]
Same here, X10S-ISRM

**Comment by Hobby4life** [comment]
Same here,

Even a fresh install, with only fresh Horus SD contents.
Emergency mode.

Radio: X10S - ISRM

**Comment by jbesse262** [comment]
Same on X12s with upgrade isrm

**Comment by spadeadam** [comment]
Same here with X10S Express

**Comment by Malone76** [comment]
Meme probleme HORUS 10 S EXPRESS
