### ISSUE TITLE
1.0.11 RC1 X20S self-created wav files will not be played 

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#807]
self created wav files in the audio folder are not played anymore.

system sounds work normally

example file attached

[fzland.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7003576/fzland.zip)

**Comment by Hobby4life** [comment]
it is 16khz

Must be 32khz

**Comment by STC148** [comment]
I have not changed anything in the files, they have worked all the time.
my system sounds are also in 16 khz and they are still working
but I will try some with 32 khz

**Comment by Mordee** [comment]
It is 16 bit depth and 16kHz sample, so should be good. Is it just that sound that you made that does not work, is that the only sound you have tried (that you made) ?

**Comment by Pilot-Quaxx** [comment]
X20S

Same problem but some of the self created .wav-files still work, others don't. They worked fluently on 1.0.10 .  They are in 16 bit depth with 16 khz sample and their name is not longer than 6 characters. They surely are on the sd-card an can be played direct from there on pc.

**Comment by STC148** [comment]
i have now converted all files from 16 khz to 32 khz, now they work again

**Comment by hrenz** [comment]
same problem with V1.0.11 at X20
Sounds files in V1.0.10 works all  but not in V1.0.11
Mono 16bit 16KHz

The original ETHOS german sound files are verry bad
pronunciation too slow
incomprehensibly bad German
Pauses at the beginning and end too long

We have created our own sounds over the years, with many extensions
and transferred them from the Taranis to the ETHOS.

**Comment by Tonio62** [comment]
STC148 how did you do that ?
Thanks

**Comment by STC148** [comment]
with audacity, 
open the file, change the frequency in the lower left corner to 32000hz and save the file as wav.

unfortunately you have to change every single file.........at least i haven't found any other way yet

**Comment by Hobby4life** [comment]
> with audacity,
> open the file, change the frequency in the lower left corner to 32000hz and save the file as wav.
> 
> unfortunately you have to change every single file.........at least i haven't found any other way yet

Check end of topic: #816
