### ISSUE TITLE
free mixer: add dedicated curves for every single output

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#809]
There are some issues dealing with dedicates curves in mixers like butterfly or camber an so on
#135 
#139 
#177 
#266 ...

One single issue was closed (#135) and should have been solved in 1.0.6, but the implementation lacks the need of the author
(he wanted dedicated curves for every single control surface, in fact you select different situations and switch between curves which control all surfaces in the same manner)
The others are still open.
My testing in sim 1.0.10 didn't show any implementation.

my proposal:

in order to keep predefined mixers as simple as possible and reduce development expenditure, make dedicates curves only accessable in the free mixer.
so the most users which don't need these "fine trims" are not burdened with unnecessary fields/items
These users who wants to fine trim their gear can build the butterfly / camber ..  mixer based on the free mixer design.

regards
udo

**Comment by strgaltdel** [comment]
just for claryfying:

herewith a screenshot where i would expect dedicated curves & weight in a free mixer
"free mixer = "one to rule it all"   (-;

![free01](https://user-images.githubusercontent.com/20392683/129887976-e8f7bc40-7938-4613-aeda-2827fe9ab4c4.png)

**Comment by mawzthefinn** [comment]
I still want per-output curves in mixers

**Comment by strgaltdel** [comment]
hope springs eternal (-;

**Comment by strgaltdel** [comment]
i know its not the "hottest issue in town"
just keep it alive for the future
