### ISSUE TITLE
X12S internal GPS and Timezone

### ISSUE THREAD

**Issue by andytransonic** [FrSkyRC/ETHOS-Feedback-Community#81]
Ethos Timezone setting should be in increments of quarter hour.
Where I come from, the GPS and RTC cannot be matched in OpenTX as my Timezone is offset from UTC by 5Hrs: 30 mins. and current OpenTX only allows integer hours.
In Nepal I believe it's 5Hrs:45 mins.
So, flying in the Himalayan foothills . . .

**Comment by bsongis-frsky** [comment]
Duplicate of #59
