### ISSUE TITLE
When you edit one curve it  doesn't show the position of the stick

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#812]
https://user-images.githubusercontent.com/87758703/129935414-868441b2-ae08-4781-a4a0-81895e25e6b0.mp4

It would be interesting if it showed the position of the stick when we are adjusting a model

**Comment by mawzthefinn** [comment]
Agreed, that would be VERY valuable add. Spektrum has this on their Curve editor and it's really useful.

**Comment by df7320** [comment]
Finally,  a duplicate of issue #24.

**Comment by andreavi90** [comment]
Any news? It's very difficult to setup correctly a servo travel without this function...Thank you

**Comment by jasalca** [comment]
No news yet, I hope they include it soon because setting up a curve for helicopter is more complicated without this function.

**Comment by jasalca** [comment]
It would also be interesting to have direct access to the curves with a long press on the menu buttons

**Comment by andreavi90** [comment]
Please fix this problem...it's impossible to setup correctly a plane/Heli, without the position of the curve...

**Comment by andreavi90** [comment]
Any news?

**Comment by mawzthefinn** [comment]
Duplicate of #24, please continue any discussion on that issue
