### ISSUE TITLE
WAV format ?

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#815]
Hello bertrand

Did you change something with the wav format, homemade wav files don't work anymore ?

Was working fine on 1.0.10 !

Thanks

**Comment by mawzthefinn** [comment]
Check to see if it's 16bit, 32KHz, mono

I know 16KHz wav files were working on 1.0.9, but 1.0.10 seems to require 32KHz.

**Comment by aviat40** [comment]
Same as #807, i will try. 

Thanks

**Comment by hrenz** [comment]
There is no reason to change everything to 32khz that has been running up to now, 
No one needs that.
Good software accepts both 16kHZ und 32khz

**Comment by aviat40** [comment]
I checked, all my files was already in the good format.

**Comment by Hobby4life** [comment]
Please guys more details with your issues.. radio?!???

**Comment by aviat40** [comment]
X20 with 1.0.11 RC1 with SD / FLASH updated

**Comment by bsongis-frsky** [comment]
Duplicate of #816
