### ISSUE TITLE
1.0.11 RC1 X20  wrong default value in the output menu

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#818]
min/max is ok but default is 10.0 instead of 100

https://user-images.githubusercontent.com/85410070/129956034-b283d084-5ecb-4079-9f0e-d35954def0c2.mp4

**Comment by Hobby4life** [comment]
Better change the topic message.

Decimal is at the correct place, only the default value is wrong.

**Comment by STC148** [comment]
in the throttle cut/hold the min and max value is wrong

![1](https://user-images.githubusercontent.com/85410070/129958258-9cee4ce5-479c-4a92-9100-5d8f56a3beb1.jpg)
![2](https://user-images.githubusercontent.com/85410070/129958269-c8fdb4c8-16dd-4981-8038-0338396d26e2.jpg)
![3](https://user-images.githubusercontent.com/85410070/129958289-b9fda6a0-b4d9-484f-9edb-f04250c5a8f4.jpg)
![4](https://user-images.githubusercontent.com/85410070/129958308-307848d9-3c26-4892-a346-8e680d518270.jpg)
