### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#819]
Hello guys,

please add Hebrew translation to ETHOS. i have attaching the txt file i prepared: hb.txt
https://www.jumbomail.me/l/he/gallery/5575774D42574F2B436550464B3342347436653838673D3D?utm_source=jmemail

i tried to run it on the Ethos sim and got all gibberish lettering - perhaps due to missing charset?
thanks.

@bsongis-frsky 
@Adelaxie

**Comment by bsongis-frsky** [comment]
Same answer than #817 
When ready please open a new issue so that we can follow up easily

**Comment by i3dm** [comment]
@bsongis-frsky 
what do you mean?
i am ready. and i attached the ready translated file above already.
