### ISSUE TITLE
Add view for channel microsecond output values (uS)

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#82]
There does not appear to be any way in ETHOS to see the PWM pulse width in microseconds being output to each channel.  

Knowing the microsecond value being sent to each channel is helpful for setting up existing models (to confirm the model setup against previous OpenTX radio setup), checking servo ranges, etc.

This request is specifically to add a view that includes the PWM pulse width microsecond value being output on each channel (or add them to an existing view).

**Comment by hrenz** [comment]
also important for flight controllers to set and see the PWM pulse in us for div functions
