### ISSUE TITLE
Hebrew Translation (txt file attached inside)

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#820]
Hello guys,

This is a duplicate of #819 - @bsongis-frsky asked to open when ready. so we are ready and i have already attached the translated TXT file in the first reply. see under.

please add Hebrew translation to ETHOS. i have attaching the txt file i prepared: hb.txt in the first reply.
i tried to run it on the Ethos sim and got all gibberish lettering - perhaps due to missing charset?
thanks.

**Comment by i3dm** [comment]
[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7012517/hb.txt)

here is the file attached here.

**Comment by i3dm** [comment]
[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7012564/hb.txt)
here is the file

**Comment by i3dm** [comment]
[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7012586/hb.txt)
here is the file

**Comment by bsongis-frsky** [comment]
I didn't think you would be ready so fast :)

**Comment by i3dm** [comment]
> I didn't think you would be ready so fast :)

do your magic.
do we need a new char set for hebrew? i'd like to test it on the sim but no luck with current char set.

**Comment by bsongis-frsky** [comment]
I have tried to do my best in 1.0.11 RC3. But I am sure there are a lot of adjustments remaining.
I understand now why other brands don't care about R2L languages ;)
