### ISSUE TITLE
Feature request : "Timer <n> elapsed"

### ISSUE THREAD

**Issue by visioneerone** [FrSkyRC/ETHOS-Feedback-Community#821]
Regarding flight timers. Is there a feature which I'm not seeing which allows the radio to announce specifically which timer has elapsed? 
I have a couple of model memories in which I'll have multiple timers running simultaneously and am used to the OpenTX "Timer <n> elapsed" voice announcement.  Ethos simply counts down to '0' then I need to look at the screen to see which timer has ended.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/169009710-68982526-3a9e-4e20-a733-2c0cd0616fee.png)
