### ISSUE TITLE
What does it mean and why did the radio get into the emergency mode????

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#826]
Suddenly my radio went into emergency mode, black screen and no control over the receiver.

What and why  happened? If I got to be flying it would have been a disaster.

**Comment by Hobby4life** [comment]
For all issues please provide more info:

Firmware version?
Radio?
What was the last thing you did when it got into Emergency mode?

Very important details.

**Comment by jasalca** [comment]
Firmware 1.0.11 candidate 1 my radio x20 EU.
I was programming a model and click return button then the screen went black with the menssage Emergency mode
Turn off and on the radio and then it went all right

**Comment by skyfly74** [comment]
I have exactly the same issue in this situation with this version X20 EU, 1.0.11 
Editing a new logic switch, i click on the screen the return buton and black screen with emergnecy mode!

**Comment by Hobby4life** [comment]
Please try v1.0.11 RC2

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/release%2F1.0.11-candidate2
