### ISSUE TITLE
EU FCC manual Setup

### ISSUE THREAD

**Issue by DronF999** [FrSkyRC/ETHOS-Feedback-Community#828]
Can you make manual settings for internal RF 2.4ghz Modul? Flex Firmware don’t switch automatically 2.4ghz modul to LBT if i set 868MHz….

**Comment by Adelaxie** [comment]
Please check the latest TD module firmware for the fix.
https://www.frsky-rc.com/tandem-x20s/

**Comment by DronF999** [comment]
Hi, so I have set on flex firmware 868MHz, and now?


Mit freundlichen Grüßen 
Andreas Fischer

**Comment by DronF999** [comment]
﻿Hi, so I have set on flex firmware 868MHz, and now?


Mit freundlichen Grüßen 
Andreas Fischer

**Comment by DronF999** [comment]
It’s don’t work)) if i set 868MHz, so is 2.4GHz Modul in FCC mode and so I don’t have Control about this.

**Comment by DronF999** [comment]
![Uploading image.jpg…]()

**Comment by Adelaxie** [comment]
the image is broken, try to bind to LBT receivers. it works. 
the info of Module mode is wrongly displayed.

**Comment by DronF999** [comment]
On ACCESS receiver set TX module a mode…
