### ISSUE TITLE
Logic Switch Value Limit with Variometer

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#83]
When setting up a logic switch using altitude from a FrSky variometer (normal resolution), I can't set the value higher than 328.08ft / 100m.

This is on my X20 running ETHOS 1.0.2, but I noticed it on 1.0.1 as well before I updated this morning.

**Comment by Liverboy77** [comment]
Can I just add the valve is the same for the gps sensor aswell.
Thanks
Scott

**Comment by rburrow87** [comment]
Looks like this is fixed in 1.0.3, at least for my variometer! I don't have a GPS sensor to check it with.
