### ISSUE TITLE
Bug: v1.0.11 RC2 X20S Still lockups in Homescreen

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#831]
I have still got random lockups in homescreen, sometimes I can turn off the radio, other times not and I have to disconnect the battery.

Util now it only happens when in Homescreen,
Radio still functions, all mixers are working. no logic, no special functions. no telemetry.
It looks like an Emergency mode, but still with homescreen.

I have already sent my SD card contents to Bertrand.
Maybe others also still experience lockups? in v1.0.11 RC2?

**Comment by OldGazer** [comment]
With the exception of the Custom Failsafe issue, my X20 is working just fine.

**Comment by STC148** [comment]
I have played around a lot with the rc2 in the last 2 days, but so far no more lockups for me.

**Comment by WismyYao** [comment]
Sorry that we failed to reproduce this problem. Can you share the video with us?

**Comment by Hobby4life** [comment]
https://youtu.be/gm7mX8P3QCU

**Comment by bsongis-frsky** [comment]
I already spent half an hour on this issue, trying to do 10 times what is in the video. I am on RC3. Please try to reproduce with RC3 when available

**Comment by Hobby4life** [comment]
The lockup is too random and can take some time to happen...
The video is just pure luck i gues.
I have also seen it happen in other pages too now.
The only thing I can think of.. this is one of the 2 models that have GPS maps in them.

**Comment by bsongis-frsky** [comment]
If you add more screens with GPS Map?

**Comment by Hobby4life** [comment]
> If you add more screens with GPS Map?

Will test

**Comment by Hobby4life** [comment]
Crashed right after I added 2 extra GPS maps, and got back to homescreen!

**Comment by bsongis-frsky** [comment]
Is your GPS sensor alive when it locks?

**Comment by Hobby4life** [comment]
It crashed when off the last time. the first time I noticed I dont know if GPS was on.

**Comment by bsongis-frsky** [comment]
Bug confirmed, it's in the GPS Map background load
