### ISSUE TITLE
X20 internal bluetooth telemetry data transfer to an external bluetooth module connected to an antenna tracker.

### ISSUE THREAD

**Issue by dobosatti** [FrSkyRC/ETHOS-Feedback-Community#832]
I welcome the developers!
My request would be for the X20 Tx’s internal bluetooth module to be able to communicate with an external 4.0 bluetooth module at 57600 speeds.
I would like to transfer telemetry data from the controller of the flying model via the internal bluetooth module of the X20 Tx to an external bluetooth module connected to a MyFlyDream mini Crossbow AAT antenna tracker.
(From the flying model, the X20 receives telemetry data from the flight controller via an R9 Mini 868 Mhz. Receiver.)
I would like to transmit this telemetry data to the antenna follower via Bluetooth.
Can this problem be solved?

**Comment by Hobby4life** [comment]
this is not a problem, this is a feature request. big difference ;-)

Anyways, I like the idea though :-)

**Comment by dobosatti** [comment]
In the Rcgroups forum, Jet_Flyer provided this link for me to describe my request here.
If my request is in the wrong place here, please provide a link where I can describe this problem.

**Comment by dobosatti** [comment]
I'm sorry, not a problem, but
Function request.

**Comment by MIKE-DAILEY** [comment]
> In the Rcgroups forum, Jet_Flyer provided this link for me to describe my request here.
> If my request is in the wrong place here, please provide a link where I can describe this problem.

Correct, it is enhancement request.

**Comment by dobosatti** [comment]
Can my repair request be resolved?

**Comment by dobosatti** [comment]
Can anyone answer that they deal with my request?
Is it possible to solve the problem in 1.0.12 Fw?

**Comment by Hobby4life** [comment]
You can also contact Charles from Myflydream to implement smartport telemetry.

**Comment by dobosatti** [comment]
And isn’t it feasible to pair the X20 Tx’s internal bluetooth with an external bluetooth module?
Currently, it is not willing to connect to any bluetooth module.
What is FRSKY afraid of? Why telemetry data can only be handled by your own android program, which is not good for anything!
Is it so complicated to transmit telemetry data via bluetooth?
I want to use an antenna tracker that I can easily use with other radios.
But I can't use it with the X20!
The X20 is an advanced modern radio that makes such a simple task impossible.
With cheaper radios, this task is easy to do!
I bought the X20 because I thought more things could be solved more easily than with cheaper radios.
I was wrong!
I will contact Myflydream in vain if no telemetry data comes out of the X20 Tx !!!

**Comment by Hobby4life** [comment]
> Is it so complicated to transmit telemetry data via bluetooth?

I gues not, but it has totally no priority over other more important things.
Getting basic things to work properly and bug free.
Adding all kind of futuristic new features is not a priority, first get all the current stuff perfectly working.
Then move over to a new features, and get them working properly. etc etc.
Otherwise it will get a mess with half finished stuff.

**Comment by mawzthefinn** [comment]
This should be addressed in 1.4.4, we discovered a bug in telemetry mirroring in 1.4.3 and earlier. It would pair but send no data.

I've confirmed it works with iMSB

**Comment by mawzthefinn** [comment]
This is now working correctly, at least at normal S.Port speeds
