### ISSUE TITLE
How long does a screenshot take to be saved.

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#833]
X20, V1.0.xx
I have noticed for some time that the screenshot function does not work reliably or takes a long time.
The screenshot function is triggered with the button SH. 
The button SH works perfectly.
The SD card also works fine.
I take screenshots of all possible windows and settings, often 4 or 5 step by step
Then there is often only 1 or 2 or even none on the SD card
sometimes I wait 4-5s until the next screenshot

**Comment by bsongis-frsky** [comment]
Only one screenshot can be written at a time and those files are big.
It will depend on your SD card write speed, and if your radio is busy or not.
I will add a small haptic when the screenshot is written

**Comment by hrenz** [comment]
thanks Bertrand

**Comment by Hobby4life** [comment]
@bsongis-frsky can you also assign a wav to this? like shutter.wav ?
So we can assisgn a sound to it ourselves
