### ISSUE TITLE
Bug: v1.0.11 RC1 and 2 X20 do not open the dialogs to be able to assign the potentiometers to adjust the brightness and sound values

### ISSUE THREAD

**Issue by GiorgioCirelli** [FrSkyRC/ETHOS-Feedback-Community#835]
As the title suggests, it is no longer possible to assign a potentiometer, on the contrary, it is not possible to open the dialog box even by clicking, in the edit display and sound menu

**Comment by Hobby4life** [comment]
Still works here

**Comment by STC148** [comment]
Works for me too, with X20S, X10S and simulator

**Comment by bsongis-frsky** [comment]
[Enter Long] doesn't work too?

**Comment by GiorgioCirelli** [comment]
It doesn't even work with that.
Now, however, after returning to the previous version and then again to this one, i was able to set them.
However, the volume of the Vario does not open at all.

![screenshot-2021-08-23-56269](https://user-images.githubusercontent.com/42900080/130457563-39ec43cc-124f-49d4-9c51-e5b306a5c118.jpg)

**Comment by bsongis-frsky** [comment]
Checked, everything seems OK

**Comment by GiorgioCirelli** [comment]
> > But is it possible to return to the starting position where no control is associated with the brightness and volume adjustment anymore?
> > I do not think.
> 
> Yes, select **convert to value**
> 
> I Think a lot of sentences in Ethos should be redone, at least in English there are sentences that have very odd descriptions.

I've searched everywhere but can't find where to selectc **convert to value**
