### ISSUE TITLE
Issues with GPS V2

### ISSUE THREAD

**Issue by andrescuadrosjdc** [FrSkyRC/ETHOS-Feedback-Community#837]
Have very inconsistent readings in my X20S
Speed and altitude inconsistent readings
Also slow refresh (GPS in 10HZ)
Also GPS Sensor lost warnings
Flying a Jet with Archer R8Pro
Flex firmware 1.011

**Comment by PeterBeretta** [comment]
I have had similar problems with my GPS V1 - speed readings way out.
Also my air speed sensor values are completely wrong.

**Comment by FBarrao** [comment]
1.0.11 rc2
Also have problems with telemetry lost with GPS sensor, but only with the "GPS time" data . The other three data don´t report telemetry data issues. 
PeterBeretta, do you have wrong values with speed sensor on 1.0.11? mine worked wrong on 1.0.10, but with 1.0.11 seems to be accurate.

**Comment by PeterBeretta** [comment]
Hi FBarro, my X20S is still running V1.0.10, is it safe to go to 1.0.11?

**Comment by FBarrao** [comment]
it Seems to be an issue programming the custom failsafe, anyway, I already had it  configured from 1.0.10, and seems to work correctly. 
3 flights yesterday on 1.0.11 rc2 no problems. 
Anyway you can wait, the corrected 1.0.11 version will arrive soon, seems to be competed..

**Comment by bsongis-frsky** [comment]
All fixed in 1.0.11 now
For GPS sensor lost, it will depend on your settings, if the refresh rate is too low you will get warnings

**Comment by FBarrao** [comment]
Changed the refresh rate of the gps to 200ms ( 5 Hz), not able to set it to 100ms..
Already having sensor lost warnings from the GPS time sensor. 
GPS speed, GPS and GPS Alt works well and don´t report lost sensor warnings,  only GPS Time..
