### ISSUE TITLE
New Live Chart widget

### ISSUE THREAD

**Issue by GiorgioCirelli** [FrSkyRC/ETHOS-Feedback-Community#840]
The new Live Graph widget present in the adjustment screens, for example when changing a value, has a highlighted scale at the bottom that is not linked to any value adjustment.

![screenshot-2021-08-23-56921](https://user-images.githubusercontent.com/42900080/130460557-cac8d1bd-5414-47bb-acd3-37e2f07dd9b4.jpg)

![screenshot-2021-08-23-56932](https://user-images.githubusercontent.com/42900080/130460576-84847c97-29ed-43c3-8222-b080b4b85b68.jpg)

**Comment by aalain8** [comment]
Hello,
In fact the bottom graph shows the displacement values of the + and - arrows.
I admit that it is a bit confusing at first.
As an improvement I would like to change the value and then use the +/- keys to finish.

**Comment by Hobby4life** [comment]
instead of a adjustable bar.. fixed multiplier buttons would be a better option.

[x1] [x10] [x100]

**Comment by aalain8** [comment]
Good idea:   X1   X5   X10   X50   X100
Or a larger graphic.

**Comment by Hobby4life** [comment]
Best is numeric keypad🙂

**Comment by aalain8** [comment]
On second thought, a longer graph would be more user friendly.

**Comment by loetefix** [comment]
Or some predefined points on on the Bar with values.

**Comment by GiorgioCirelli** [comment]
I would propose these two more intuitive solutions

![Senza titolo-1](https://user-images.githubusercontent.com/42900080/132705912-0363db8e-0e76-43ca-9bfc-388f0dbc3d03.jpg)

![Senza titolo-2](https://user-images.githubusercontent.com/42900080/132705934-67609ac3-7876-44ba-a36f-aade528fd0d0.jpg)

**Comment by mawzthefinn** [comment]
I like the last change below. It's quite clear and maintains the current drag to adjust behaviour.

**Comment by loetefix** [comment]
still needed
