### ISSUE TITLE
Play Track don't play

### ISSUE THREAD

**Issue by GiorgioCirelli** [FrSkyRC/ETHOS-Feedback-Community#841]
I am trying to translate the English to Italian speech by editing the Wav files manually.
I mainly used those from another FrSky model.
I don't know if this is the cause but now the system is no longer able to see the Wav files inserted at the root to make them read through the Play Track command.
However, the same files are visible from file manager and can normally be played, copied, moved or deleted

![screenshot-2021-08-23-57135](https://user-images.githubusercontent.com/42900080/130462506-ad303298-8600-4a34-b76a-793eeb835603.jpg)

![screenshot-2021-08-23-57146](https://user-images.githubusercontent.com/42900080/130462522-37a81472-ec59-46b7-8af8-49cace0c6af3.jpg)

![screenshot-2021-08-23-57184](https://user-images.githubusercontent.com/42900080/130462550-85e910b2-f974-4acf-8699-c5f2b962a6d5.jpg)

**Comment by Hobby4life** [comment]
it needs to be in the root of the Audio folder

**Comment by OldGazer** [comment]
+1 @Hobby4life 

User sound files MUST be in the root of the Audio folder, not in the root of the SD card.

**Comment by GiorgioCirelli** [comment]
Thank you!
