### ISSUE TITLE
1.0.11 RC3 Custom Failsafe function ok, but still little display issue

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#842]
X10

![X10](https://user-images.githubusercontent.com/85410070/130492718-35d2e91a-bedb-45d3-9357-049f42b83368.jpg)

X20

![X20](https://user-images.githubusercontent.com/85410070/130492738-48f5ddcd-fd20-4c84-a784-34c777769c8e.jpg)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/130496413-fd3f2b55-7fbe-43d0-8b5a-7449b839e8f2.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/130497901-2d976ba6-4ef0-497c-a127-cfce9910dcb2.png)
