### ISSUE TITLE
Norwegian System sounds

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#845]
Here are norwegian translation of the system sounds for the SD-card.
I hope they can be used.

[norwegian system sounds.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7035118/norwegian.system.sounds.zip)

**Comment by bsongis-frsky** [comment]
I only need the CSV, like those ones
Then I need to know what is the TTS voice you use
We use the Google TTS engine
[audio_cn.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7036787/audio_cn.csv)
[audio_cz.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7036788/audio_cz.csv)
[audio_de.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7036789/audio_de.csv)
[audio_en.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7036790/audio_en.csv)
[audio_es.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7036791/audio_es.csv)
[audio_fr.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7036792/audio_fr.csv)
[audio_pt.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7036793/audio_pt.csv)

**Comment by mmasch** [comment]
Hello. 
Here are translated csw file to norwegian.
Had a listen to Google TTS voices, and I feel that the voice "nb-no-Standard-E" is the most pleasant. 

[audio_no.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7041799/audio_no.csv)

**Comment by mmasch** [comment]
Csv file uploaded to Github.
Case #845. 

Br. Morten Masch. 

Sendt fra min iPhone

**Comment by bsongis-frsky** [comment]
What is the grammar which is the most

**Comment by mmasch** [comment]
Had a listen to the norwegian language files and I think they are spoken too fast. 
I.e. the user does not get the warning message. 
Any chance that the spoken speed can be reduced somewhat?
