### ISSUE TITLE
In version 1.0.11. RC3, it seems to me that the failsafe is not correct. 

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#846]
Horus X10 + isrm v1.0.10 I am upgrading to v1.0.11 rc3
In version 1.0.11. RC3, it seems to me that the failsafe is not correct. 
The motor setting (channel ch7) on custom -100 is at -10 after the update.
If I set -100 in the window, the text shows .00%.

**Comment by bsongis-frsky** [comment]
The conversion from 1.0.10 was wrong. Fixed in RC4
