### ISSUE TITLE
Ethos telemetry sensor A4 problem?

### ISSUE THREAD

**Issue by STC148** [FrSkyRC/ETHOS-Feedback-Community#848]
In my helicopters I have installed the unisense-e from sm, which sends the used capacity as an A4 sensor, which must be changed from V to mah.
This works without any problems with OpenTX.
 So far so good.
My thought now was that it should also work with Ethos using the DIY sensor function.

With Ethos, the A4 is found in the sensor search, but no data is sent and the message Sensorlost appears. The question now is:  Bug or Feature? Am I missing something?

https://user-images.githubusercontent.com/85410070/130606328-4481878d-4ee1-4a6c-a0da-48c62f6b7a65.mp4

https://user-images.githubusercontent.com/85410070/130606423-41908365-40d4-4475-88b9-350d74d2f924.mp4

**Comment by bsongis-frsky** [comment]
You have to remove it from the list and create it with "DIY Sensor"

**Comment by STC148** [comment]
That's it
I deleted the sensor from the list and searched for it again in DIY via autodetect, and now it works.

Thank you very much

**Comment by Nerenye** [comment]
Can we have maybe a bit more information in how to configure this sensor correctly. Ive deleted and added it via DIY autodetect, but the readings can´t be right. Changed it to mah, but it´s not correctly representing the drain.
It worked before on frOS just fine.

Thanks in advance

**Comment by STC148** [comment]
These settings work for me without any problems:

![Screenshot 2022-05-29 165520](https://user-images.githubusercontent.com/85410070/170876104-5e25f130-d5b3-497f-a232-7682de7969b3.jpg)

But there is a new update for the Unisense since last week, with that the mAh are displayed directly and no DIY sensor is needed anymore.

**Comment by Nerenye** [comment]
Thanks a bunch
I'll try that!
