### ISSUE TITLE
hebrew Language mods

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#849]
hello @bsongis-frsky 
On behalf of all Israeli pilots i would like to say thank you for the Hebrew language!
In this post listed under we will describe the neccessary GUI changes to make the Hebrew support perfect.

**Comment by npirkes** [comment]
Hi, I have found some improvements on the checklist warning window. 
I tried to explain the changes over the attached screenshot. 

![IMG-20210824-WA0039](https://user-images.githubusercontent.com/50323844/130703215-1745707e-fb1e-4487-af63-d78ed3828b57.jpg)

In addition, I would also like to share my gratitude for all the hard work that has been done.

**Comment by i3dm** [comment]
I sugges to align all menus to one column, see attached before and after.
![after](https://user-images.githubusercontent.com/8968780/130751367-9d393305-d48c-4a0b-a3f7-541e4da933b7.jpg)
![before](https://user-images.githubusercontent.com/8968780/130751379-a2aeabeb-7777-433c-a477-d93a82b6d503.jpg)

**Comment by i3dm** [comment]
preflight menu
failsafe check On/Off toggle should move from the blue to Red - it overides the text.
![failsafe](https://user-images.githubusercontent.com/8968780/130772504-cd24d373-edda-4a05-b2c1-35ec4c1453dc.jpg)

**Comment by i3dm** [comment]
hello @bsongis-frsky 
has any of the above been fixed in RC4?
has the uodated hb.txt bedn used in RC4?

**Comment by bsongis-frsky** [comment]
I see no hb.txt here. The simulator is fixed. Some other issues as well.

**Comment by i3dm** [comment]
> I see no hb.txt here. The simulator is fixed. Some other issues as well.

Simulator works better now in Hebrew now :)

top bar is funky though
![tb](https://user-images.githubusercontent.com/8968780/132387799-c432e34a-86ea-4e98-bc62-f44ea675bdee.PNG)

**Comment by i3dm** [comment]
> preflight menu
> failsafe check On/Off toggle should move from the Red to Blue - it overides the text.
> ![failsafe](https://user-images.githubusercontent.com/8968780/130772504-cd24d373-edda-4a05-b2c1-35ec4c1453dc.jpg)
> 
> Probably in general all toggle switches need to be shifted to the left edge.

this issue still exists with current RC4 simulator

**Comment by i3dm** [comment]
Toggle switches need to be shifted to far left to be aligned with everything else in the  menus
![tb1](https://user-images.githubusercontent.com/8968780/132388516-df0ecbeb-e0b0-4cce-a0b7-6ad9838e573e.PNG)

**Comment by i3dm** [comment]
1. mixer names are originally in english rather than hebrew. should be hebrew.
2. when i added a mixer called הגאי כיוון (rudders) the wording got cut off and all i see is אי כיוון/
see attachedment:
![tb3](https://user-images.githubusercontent.com/8968780/132389367-7a767bb1-3166-4d34-862d-f1102fe01a98.PNG)

**Comment by i3dm** [comment]
mixer names are cut off, and some of them appear to be in giberish?
![TB4](https://user-images.githubusercontent.com/8968780/132389611-f67d4301-1d3f-49db-b0bf-6f4239dfee40.PNG)

**Comment by i3dm** [comment]
@bsongis-frsky 
Here is the greatly improved hb.txt file for the next release:
[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7123546/hb.txt)

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132454602-3bb57f08-3f01-4136-9d46-6df1600bdeb6.png)
shift the text to the right

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132454759-da084ad9-cd8f-419d-92c2-b2db5f757b65.png)
inside the folder - shift the text in the red square to the right

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132455371-44978f2e-da46-40d2-a564-331f160ba9b0.png)
the date should be reversed - first the date, then month then year from right to left

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132456817-a303439f-0e7b-4392-ad2d-e68ed14ee39d.png)
different date ? not in hebrew ?

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132457098-b3854990-0206-4e3e-ac75-2ea97e68295d.png)
should be moved to the right side of the window

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132459475-445ed5ce-7cb7-40e8-827a-c43ac9a12e03.png)
Failsaife definition screen - the failsafe on/off toggle should be moved to the left

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132460016-a7c1a3be-09fc-4c85-9a85-0dfcc9303071.png)
trainer - move the section in red square to the right side of the window

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132461309-5a44ac2b-8777-49fe-89e9-2eb5c7014f39.png)
radio settings - antenna settings - move the content of the window to the right

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132465195-b42eae7f-c082-4038-9196-26b58149ded8.png)
Add new screen - move the content of the window to the right

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/132465403-33c1ceaa-dd88-4224-bae1-eaa55a32191d.png)

Edit screen - delete screen - move the content to the right

**Comment by phazeman** [comment]
Mixer add screen has to be reworked in Hebrew:
![image](https://user-images.githubusercontent.com/55709534/132473776-17e11750-b943-4f61-85cd-9499783e47c6.png)

**Comment by i3dm** [comment]
@bsongis-frsky 
i am attaching the greatly improved hb.txt file, after a massive update and review by Michael and Myself.
please include this file in the net version of ETHOS:

[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7127802/hb.txt)

thank you.

**Comment by i3dm** [comment]
@bsongis-frsky 
i am attaching the greatly improved hb.txt file, after a massive update and review by Michael and Myself.
please include this file in the net version of ETHOS:

[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7127831/hb.txt)


thank you.

**Comment by i3dm** [comment]
in english there is a bind and register button, but not in Hebrew ???
![EN1](https://user-images.githubusercontent.com/8968780/132488933-4dbcd209-0eb3-4794-b2e2-53f454b43cfe.PNG)
![HB1](https://user-images.githubusercontent.com/8968780/132489045-5e37a4d1-3606-4ded-8423-f668854398b1.PNG)

**Comment by i3dm** [comment]
@bsongis-frsky 
i am attaching the greatly improved hb.txt file, after a massive update and review by Michael and Myself.
please include this file in the next version of ETHOS:

[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7127916/hb.txt)


thank you.

**Comment by i3dm** [comment]
Keyboard question:
will there be a Hebrew Keyboard added to Ethos Hebrew?

**Comment by i3dm** [comment]
im adding again the hb.txt file, as i do not see the file i added before for some reason
[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7148383/hb.txt)

**Comment by bsongis-frsky** [comment]
Please don't re-add posts that I deleted on purpose, I only keep those which need to be done when I will have time

**Comment by i3dm** [comment]
> Please don't re-add posts that I delete on purpose, I only keep those which need to be done when I have time

got it

**Comment by i3dm** [comment]
@bsongis-frsky  we are also working on a Hebrew voice pack. can this be added to ethos too once ready?

**Comment by bsongis-frsky** [comment]
ok for the voice pack, please push it here when ready

**Comment by bsongis-frsky** [comment]
Today there is no keyboard for CN / HB, this is why many strings are labelled EDIT_RUDDER, EDIT_xxxx
I should have explained before, by adding HB chars there, you have completely broken all the Textedit for mixes, telemetry, etc.
I wonder if it couldn't produce an Emergency Mode easily, these fields cannot display CN / HB

**Comment by i3dm** [comment]
> Today there is no keyboard for CN / HB, this is why many strings are labelled EDIT_RUDDER, EDIT_xxxx
> I should have explained before, by adding HB chars there, you have completely broken all the Textedit for mixes, telemetry, etc.
> I wonder if it couldn't produce an Emergency Mode easily, these fields cannot display CN / HB

so do we have a serious problem with hb.txt as of current?
all the EDIT_XXX are hebrew

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/133793260-9d84b2c4-6e79-48be-b89d-9d7af5851692.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/133799186-57074ff3-91e7-4468-98d7-1022d8dd674b.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/133804624-10012fdb-9169-4b7c-900a-c2738d090dc1.png)

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/133804933-91163f99-d7c6-4b6a-92c6-554070ff1ac7.png)

**Comment by i3dm** [comment]
@bsongis-frsky 
im attaching the latest hebrew voice pack, please incorporate it into the next ethos version.
thanks.
[he.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7194903/he.zip)

**Comment by i3dm** [comment]
![20210920_133720](https://user-images.githubusercontent.com/8968780/134012041-1dab7eb9-0721-4281-9bbf-13d496a55484.jpg)
![20210920_133511](https://user-images.githubusercontent.com/8968780/134012063-b2d489b9-52d6-464f-9ad0-44470b1eb390.jpg)

some giebrish text when giving the alert for switching off with Rx still on

**Comment by bsongis-frsky** [comment]
Font changed to "Arimo" which has the reversed interrrogation mark (the previous font didn't have it!)

![image](https://user-images.githubusercontent.com/50834778/134154795-666a2c6f-45fc-438f-b516-2df25a6845cb.png)

**Comment by i3dm** [comment]
> 1. Font changed to "Arimo" which has the reversed interrrogation mark (the previous font didn't have it!)
> 2. REGISTER button added
> 
> ![image](https://user-images.githubusercontent.com/50834778/134154795-666a2c6f-45fc-438f-b516-2df25a6845cb.png)

what is a reverse interrogation mark? might be a mistake in hb.txt.
2. great - will there be a 12 RC1 to test soon eith these fixes?

**Comment by i3dm** [comment]
> 1. Font changed to "Arimo" which has the reversed interrrogation mark (the previous font didn't have it!)
> 2. REGISTER button added
> 
> ![image](https://user-images.githubusercontent.com/50834778/134154795-666a2c6f-45fc-438f-b516-2df25a6845cb.png)

@bsongis-frsky 
no need to change the font,! it was a bug in hb.txt with the reverse question mark.
here is the corrected hb.txt file:
[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7202422/hb.txt)

**Comment by i3dm** [comment]
1. the reverse question mark was a bug in hb,txt. no need to change the font.
2. attached is a fixed hb.txt based on 11RC5 file. please use this one.
[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7202469/hb.txt)
:

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/134158909-4d2d1800-6f99-49ca-8783-9cf0d8299a23.png)
the first letter is cut off there. should be "הגה כיוון" instead of "גה כיוון"

**Comment by phazeman** [comment]
![image](https://user-images.githubusercontent.com/55709534/134159059-53be0935-9f42-42a8-8eec-1fa4eef86a5e.png)
the top bar is messed because the batt and the radio icons are not being attached to the left side. also, after changing back to english the model name is not placed correctly

**Comment by bsongis-frsky** [comment]
> @bsongis-frsky
> no need to change the font,! it was a bug in hb.txt with the reverse question mark.
> here is the corrected hb.txt file:

ok next time you see wrong chars, please check your translation first, I spent the whole morning to find the right font to display this inverted interrogation mark ... for nothing!

you will take the simulator translations from 1.0.12 RC1 when available, 1.0.11 and 1.0.12 have already too many differences

@phazeman you also have bad translations, those names cannot be written in HB, there is no HB keyboard (nor FR or CN) today

**Comment by i3dm** [comment]
1. will do.
2. ok i can update on V12 file.
3. what about the words that have to stay in ENGLISH which you mentioned before?
4. i saw Phazeman's issue. it looks like a bug to me too.

**Comment by phazeman** [comment]
@bsongis-frsky the screenshots i posted are from the TX and not simulator. anyway i did check in the hb.txt file and the translation seems to be ok there: 
![image](https://user-images.githubusercontent.com/55709534/134169342-308ee26b-ceec-4090-8dd7-f67847bc7344.png)

**Comment by bsongis-frsky** [comment]
EDIT_RUDDER is completely wrong, it shouldn't have any HB chars. The new line in 1.0.12 will be:

`EDIT_RUDDER               "Rudder" // Input name, cannot have HB chars`

**Comment by phazeman** [comment]
@bsongis-frsky OK going to fix all the EDIT_ string back to English now. Thanks for the clarification !

**Comment by bsongis-frsky** [comment]
No, it's already done, you will start from 1.0.12 RC1 when ready (I have promised a lot, translations should only be details), or you will do the work for nothing

**Comment by i3dm** [comment]
> No, it's already done, you will start from 1.0.12 RC1 when ready (I have promised a lot, translations should only be details), or you will do the work for nothing

we will test 1.0.12RC1.

**Comment by bsongis-frsky** [comment]
@phazeman your latest screen is fixed now, the XXS font was missing all HB chars

![image](https://user-images.githubusercontent.com/50834778/134177069-f6355afe-4c9d-4e08-b3c2-381cb96a7ba1.png)

**Comment by bsongis-frsky** [comment]
@all I recommend not using HB at all for flying. There are still too many issues (missing chars in fonts, wrong translations with HB chars when not allowed, etc.).

**Comment by bsongis-frsky** [comment]
@phazeman is the date written right now?

![image](https://user-images.githubusercontent.com/50834778/134178045-4d5003f4-f544-4df7-ba37-3aded9a1168f.png)

**Comment by i3dm** [comment]
> @phazeman is the date written right now?
> 
> ![image](https://user-images.githubusercontent.com/50834778/134178045-4d5003f4-f544-4df7-ba37-3aded9a1168f.png)

yes correct.

**Comment by i3dm** [comment]
> @ALL I recommend not using HB at all for flying. There are still too many issues (missing chars in fonts, wrong translations with HB chars when not allowed, etc.).

ok. i will post on the israeli group

**Comment by i3dm** [comment]
@bsongis-frsky 
im attaching the latest hebrew voice pack, please incorporate it into the next ethos version.
thanks.
[Ethos Voice Pack L - Voice Over.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7206434/Ethos.Voice.Pack.L.-.Voice.Over.zip)

**Comment by bsongis-frsky** [comment]
@npirkes is it good now?

![image](https://user-images.githubusercontent.com/50834778/134639262-1d9d3431-bdf2-4584-8946-e5bd77fd10ae.png)

**Comment by i3dm** [comment]
> @npirkes is it good now?
> 
> ![image](https://user-images.githubusercontent.com/50834778/134639262-1d9d3431-bdf2-4584-8946-e5bd77fd10ae.png)

looka good to me

**Comment by i3dm** [comment]
X20
V1.0.12 RC3:
Simulator shows hebrew fine.
X20 shows all chard giebrish totally unreadable / unuseable.
please revert X20 to the working font ithad before up to RC2.
![20211017_222624](https://user-images.githubusercontent.com/8968780/137642149-9d9538d6-65c0-419b-9859-4e184e8f4b29.jpg)
 
also voice files still read from EN folder and not from HE folder.
@bsongis-frsky

**Comment by i3dm** [comment]
Attached in an updated hb.txt based on V1.0.12RC3 file - please use it for future versions.

[hb.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7360730/hb.txt)


one bug i found is the strings "RX1" "RX2" "RX3" dont use the names from the faile, they should be hebrew but instead see photo:
![1](https://user-images.githubusercontent.com/8968780/137642860-49706806-6345-48b0-a4b6-42eaf493ea29.PNG)

**Comment by bsongis-frsky** [comment]
The file should be named he.txt
Also you didn't start from the file distributed in RC3, so you will miss some translations

**Comment by i3dm** [comment]
> The file should be named he.txt Also you didn't start from the file distributed in RC3, so you will miss some translations

i used the file after instlaling X20 Sim of 1.0.12 RC3 - should i do it differently?

**Comment by i3dm** [comment]
Small bug in Hebrew when picking the date year (does not occur in english), see video:
https://youtu.be/QJa151SuGIA

**Comment by i3dm** [comment]
Went through V1.0.12 RC5 hebrew menus, they look incredible!

found one small display bug so far. in the switch checkist check the wording is revered (left to right, should be right to left):
this is how it looks
![before](https://user-images.githubusercontent.com/8968780/138055567-187c9b2f-972f-4914-af7e-086fc4811494.jpg)


this is how its supposed to look
![after](https://user-images.githubusercontent.com/8968780/138055890-91228a3c-f6e7-49de-b10c-a37310b9a083.jpg)

i also improved the displayed string, attaching new he.txt:
[he.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7379396/he.txt)

**Comment by bsongis-frsky** [comment]
RC6 / final:
![image](https://user-images.githubusercontent.com/50834778/138065911-6dd3cb52-7c9c-416b-90c7-0562f9a6aa8e.png)

**Comment by bsongis-frsky** [comment]
No, only major issues, we have too many requests for now

**Comment by i3dm** [comment]
> date looks good now. will you fix the preflight switch alert text / new he.txt as well?

just a reminder this is still open i believe

**Comment by i3dm** [comment]
small bug report with 1.4.6 hebrew:
when binding TD R10 Rx, under RF menu:
the name "TD R10" overlays on the "Rx1" text. need to shift the name of the bound Rx ("TD R10") left.
