### ISSUE TITLE
Flex version for FCC and EU-LBT

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#854]
Hello

There are currently 3 versions of Ethos:
- FCC
- EU-LBT
- Flex

If I understand correctly, the Flex version is FCC and the 2.4 GHz module is in FCC mode, regardless of whether you select 915 or 868 MHz?

Would it be possible to offer 2 Flex versions? An FCC and an EU-LBT version? In the EU-LBT version, only 868 MHz (10 mW / 100 mW / 500 mW / 1 W) could be selected and the 2.4 GHz module would be in EU-LBT mode.

Many thanks and kind regards

Enzo

**Comment by Adelaxie** [comment]
Check the latest TD module download section for the firmware 
When 868 selected, 2.4g RF is under LBT mode
When 915 selected, 2.4g RF is under FCC mode.
https://www.frsky-rc.com/tandem-x20/

**Comment by floflolapin** [comment]
Hi, is it still the same?

Would it be possible to use 868mhz and 2.4rf under fcc mode?
Thanks

**Comment by Hobby4life** [comment]
You have all power options to both modes.

With Flex you have all power otions for 868mhz and 915mhz.
FCC = 915mhz
LBT = 868mhz

Thats all.

**Comment by floflolapin** [comment]
What I would like to do is use 2.4 in fcc mode and 900mhz in flex mode and 868mhz. That's actually how I use my xlite and x10s, because I have external modules for 900mhz
But I guess that's not possible on the x20s with td module?
