### ISSUE TITLE
Ability to activate a mix with a custom button

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#855]
I wish you could include the custom buttons to be able to activate mixes .Thanks

https://user-images.githubusercontent.com/87758703/130775019-449d3530-97f5-4734-ae3c-1325c63a9802.mp4

**Comment by Hobby4life** [comment]
If you use a button as "Condicion" you can.

**Comment by jasalca** [comment]
Ok thanks
