### ISSUE TITLE
Problem with frsky x20s and RB30 Sensor

### ISSUE THREAD

**Issue by Jetman66** [FrSkyRC/ETHOS-Feedback-Community#857]
Moin, moin from the north,

after 8 years of opentx I made friends with my new X20s and had already given hymns of praise from me, the first damper hit today. I start building a Carf Eurosport with x20s, Archer R8pro, R9 SX and an RB30. The problems start with the sensor configuration. When I use the Tab RB30 / 40, there is no possibility to set the mounting position, the model type, the Quickmode and other parameters, not to mention the impossibility of the current calibration with entering the 78. The gyro calibration is also not available. I made these settings via the tab for the S receivers, but I'm not sure whether this is possible. It is nice to be different because the pictures of the corresponding layers do not show the RB30. If I then do a sensor search, all data is found, but unfortunately the input voltage of the RB30 (11.4V for me) is displayed incorrectly (9.7V) and the sensor for the input voltage is always lost after 2-3 seconds (sensor lost ). If I connect the RB30 to the same RX with my X10s express, everything is fine. Has anyone noticed similar issues?

Thanks in advance and best regards from Rosengarten in Germany, Michael

**Comment by bsongis-frsky** [comment]
Which release of Ethos?

**Comment by Jetman66** [comment]
Ethos 1.0.10. Now the problem is solved with 1.0.11C3. But the RB30 has a problem with a loose NFC Switch socket. Best regards from germany, Michael. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 30.08.21, 17:22 schrieb "Bertrand Songis @ FrSky" ***@***.***>:

   
  Which release of Ethos?

**Comment by mawzthefinn** [comment]
Clsoing as per last comment.
