### ISSUE TITLE
6-pos switch - position not recognized

### ISSUE THREAD

**Issue by Darko-FC** [FrSkyRC/ETHOS-Feedback-Community#86]
radio X10 (without ISRM board)
Ethos 1.0.1 and 1.0.2 (same behaviour)

In ADC value inspector I can read following values (approximately) for 6-pos switch:
- pos 1 - value 510
- pos 2 - 815
- pos 3 - 1015
- pos 4 - 1350
- pos 5 - 2008
- pos 6 - 4094

Values are "gradually" spaced between positions 1 to 5 (510 to 2008) 
- and then there’s the big jump to value 4094 for position 6.

**Problem is** - position 5 is not recognized in "Hardware check" menu (nor else)

When OpenTx 2.3.11 is installed on same radio - all positions are recognized correctly.
(if needed - I can note and report those values)

**Comment by bsongis-frsky** [comment]
Thanks for giving your numbers here, it helps.
Pos 5 should be around 2048, so between 2028 and 2068. 
I just increased the range around the positions to 50 instead of 20
