### ISSUE TITLE
Request for displaying error message/code when emergency mode happens

### ISSUE THREAD

**Issue by OB1-OB2** [FrSkyRC/ETHOS-Feedback-Community#860]
Some kind of a message/code for why the radio went into emergency mode is pretty useful (necessary?) for debug purposes. Can it be added?

**Comment by bsongis-frsky** [comment]
We cannot write a system log and use more CPU resource / SD bandwidth for something which should not happen!

**Comment by bsongis-frsky** [comment]
It would be nice, but it is a watchdog timeout, so the reason will be "watchdog timeout", which is not very useful!

**Comment by Hobby4life** [comment]
> It would be nice, but it is a watchdog timeout, so the reason will be "watchdog timeout", which is not very useful!

Ahh ok I understand, no time to write something.
