### ISSUE TITLE
Ethos Emergency mode and crash

### ISSUE THREAD

**Issue by Caledi** [FrSkyRC/ETHOS-Feedback-Community#864]
Hi!
Yesterday after a few flights, my Tandem X20S went on Emergency mode, I end up losing RC control and crash a 55cc Yak55. I´ve lost the complete airframe, the lipo batteries, and some other accessories. Also some minor damage to the motor muffler.
After I took off, I turn to the right and while flying level the plane made sudden banking, I wasn´t sure what happened at the moment, I checked and I had control over the plane, so I start turning right again, to come back. Then I lost control of the plane, regain control again, and finally lost it. I saw the plane falling down in a straight line, while I have the elevator stick fully down.
The first issue (violent banking) occurred with the plane between 200 and 300m away. And its final crash location was about 600m away.
I understand that during an emergency mode event I should be able to have control over the plane. No mixes, no flight modes, but full control over the main 4 channels. I had intermittent control for a moment and then finally lost control. This really concerns me.
I know emergency mode is a transmitter / Operating system-related issue. And one of the main causes might be SD card problem. So my first thought was that the SD was full, the SO couldn´t write on it, and that caused the emergency mode event. I have a 16Gb SD, and only a few MB used on it. So that was not the case.
I have set up the model to save a log. So I tried to reach it, but it was empty. I then realized the log file is written on the SD card when I turn off the radio (I guess because of the way it is programmed: always on).
During the afternoon, I made 5 flights. I turned on the radio, Setup trainer mode (so a Buddy can fly my plane, as I fly in mode 1 and he flys mode 2). We check control, and everything was OK. Made the first flight OK. Landed, refueling, and took off for the second flight. After landing the second flight I turned off the radio, and I´ve got that log file.
Then turned the radio on again and made 3 more flights. 2 were successfully landed and the 3rd one was the one with the emergency mode event and crash. That took more than 1 hour with the radio on.
There is no log file for those flights. There is a file on the radio, but it is empty.
My second thought was that maybe because the file is written to the SD card when I turned off the radio, some king of RAM or buffer just got full, and that caused the radio to go into emergency mode. I tried to reproduce that this morning, and I left the radio and plane on for more than 2hours, but nothing happened. It all works as it should.
I really don´t know what went wrong, why the radio went into emergency mode, why I lost RC control over the plane in emergency mode, and even more important, what should I do to avoid this in the future. 
I have been flying with a Taranis X9D plus for over 6 years with OTX, and never had an issue. I don´t feel confident to fly again my tandem, The plane I crashed is way more expensive than the radio.
Attached is the log file I got, the bin file of the plane, and a screenshot of the logs written, where you can see the empty one. Also some pictures of the screen with system info.
My gear:
FrSky Tamdem X20s
TD module Firmware: 2.1.9 (FCC)
Ethos version: 1.0.10 FCC final release
RX: R10pro with 2.1.7 firmware

RB30
Temperature and rpm sensor
Lipo sensor

If you need any other information or testing on my side, just let me know

![Ethos Info](https://user-images.githubusercontent.com/85141801/131015927-34f641f2-0d68-4f98-8ca5-e2508f7a5bdf.jpeg)
[model03.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7061925/model03.bin.txt)
![Yak55 Logs](https://user-images.githubusercontent.com/85141801/131015429-eb8e2de5-bf33-4045-b15d-7e7bfd4742c5.jpg)
[Yak55-2021-08-25-15-37-30.csv.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7061926/Yak55-2021-08-25-15-37-30.csv.txt)
[radio.bin.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7061962/radio.bin.txt)

**Comment by dwheeld** [comment]
I ran the model 32 times, for 12 minutes each time. It worked perfectly every time.

**Comment by Caledi** [comment]
> I ran the model 32 times, for 12 minutes each time. It worked perfectly every time.

Thanks for your interest and the testing!

**Comment by Caledi** [comment]
> I can confirm this, when I found the "emergency mode" with the "multi lipo sensor" for the first time yesterday, I am sure that the receiver went into failsafe and the model was no longer controllable.
> When I provoked the emergency mode several times afterwards, the receiver only lost the connection very briefly and the model was controllable again.
> I could no longer reproduce the permanent failsafe.

Did you open an issue on this?

**Comment by Caledi** [comment]
> A few days ago I opened up an issue because the radio went into the emergency mode.I wasn't flying.I was programing.What I can confirm is that the radio stop broadcasting ( no signal to the receiver when the radio is in emergency mode)
> Yesterday the same thing happened to me again while I was programing logic switches and confirmed that it stop broadcasting (no signal to the receiver)
> My radio X20 EU 1.0.11 Rc2

Did you open an issue on this?

**Comment by bsongis-frsky** [comment]
This issue has been a nightmare for us as we couldn't find a way to reproduce it.
This morning Wismy found it, now we are searching for the cause, we have still no clue, but I am sure we will track it down

**Comment by Hobby4life** [comment]
This is awesome news!, glad they found it. :-)

**Comment by bsongis-frsky** [comment]
Now I have fixed it. It will be there in RC4.

**Comment by Caledi** [comment]
> Now I have fixed it. It will be there in RC4.

Excellent news! Witch problem were you able to fix? The issue that causes the EM? Or the radio stops broadcasting while in EM?
