### ISSUE TITLE
Enhancements: Ethos descriptions sometimes have no logical description for their function (English)

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#865]
![image](https://user-images.githubusercontent.com/55426642/131026697-94d0f080-24bb-4e0f-9140-3b960b540ad5.png)

Convert to value -> **Default setting**

![image](https://user-images.githubusercontent.com/55426642/131026858-a6a63085-8418-4983-ba06-66d49fc95b03.png)

Flexible Range -> **Auto Range**

**Comment by bsongis-frsky** [comment]
"Convert to value" means here that we will use the POT1 current value as final value. "Default setting"  would mean that you want the default value, around 50% (factory default)

Agree for "Flexible range".
