### ISSUE TITLE
Request: Line of Sight (LoS) option in Distance Calculated sensor

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#866]
I like to request a Line of Sight (LoS) option in Calculated sensor Distance.

Just a second source for altitude.. if not selected it behaves like normal distance.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/133420697-edf7a879-903d-4229-9581-eb2841048d66.png)
