### ISSUE TITLE
Configuring ports on R9SX receiver through ETHOS fails

### ISSUE THREAD

**Issue by ChrisHMontag** [FrSkyRC/ETHOS-Feedback-Community#867]
I used the "options" feature in the ETHOS 1.0.10 RF menu to configure port/channel 6 on an R9SX receiver as "SBUS" (assuming that means "SBUS OUT"), but when I hooked up the R9SX as a backup to a 2.4GHz receiver it did not send any signals via port 6, only via the multipole port on the receiver. I suspect that configuring receiver ports via ETHOS is not yet actually doing anything.

**Comment by ChrisHMontag** [comment]
Thanks, that's good to know! So it is actually a bug, though not a very severe one because there is a workaround - that one needs to know. Would be nice to get this fixed, though.

**Comment by mawzthefinn** [comment]
Given the same behaviour is in OpenTX, it appears to be a receiver bug, not an ETHOS one. Closing off as such
