### ISSUE TITLE
diy sensor min and max error

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#868]
![image](https://user-images.githubusercontent.com/16739660/131091352-e0cd56b1-33a1-4f34-9a5d-5b0159936634.png)

when you press min

![image](https://user-images.githubusercontent.com/16739660/131091111-9caa6cb8-8f6f-491c-a0a4-57d52d7b4e44.png)
when you press max

you have the same issue in the simulator

**Comment by bsongis-frsky** [comment]
I have changed the limitation to something more understandable by humans. Plus increased the size of the field:

![image](https://user-images.githubusercontent.com/50834778/131340598-a372a1c5-f925-4929-9e71-7910fc38d929.png)
