### ISSUE TITLE
RPM Sensor max. value too small for turbines

### ISSUE THREAD

**Issue by d4g0r3d** [FrSkyRC/ETHOS-Feedback-Community#869]
The Telemetry RPM sensor max. Value wirh 80.000 is too small for a turbine.

**Comment by FBarrao** [comment]
Try to change the upper limits editing the sensor, using a xicoy sensor, mine was at 10.000, but I was able to change to 250.000. Now works fine.

**Comment by d4g0r3d** [comment]
Yeah, thried that but its max value is 80.000rpm right now

**Comment by Hobby4life** [comment]
Did you try to delete the sensor, and discover it again.
Most of the time coming from an old firmware it keeps the old settings.

**Comment by FBarrao** [comment]
Ok, probably then because my sensor send the value to a dyi sensor, and this is fully configurable..
Then if devs are going to change the limit, please, go to 250.000 rpm, since 230.000 as Hrenz proposes is so low for engines like P20, T25, and some small others, that runs at 245.000 rpm.

**Comment by STC148** [comment]
Have you tried deleting the rpm sensor from the list and then recreating it with a DIY sensor? Then it should be possible to extend the range as much as you want.

**Comment by d4g0r3d** [comment]
> Have you tried deleting the rpm sensor from the list and then recreating it with a DIY sensor? Then it should be possible to extend the range as much as you want.

Good point! I will try that and report back 👍

**Comment by bsongis-frsky** [comment]
250.000 in RC4 then
