### ISSUE TITLE
After updating ethos to Firmware to 1.0.11-3, Internal to 2.1.9 S8R will not self check

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#870]

**Comment by guycnicholas** [comment]
I found there is an issue and you need to make sure the "switch middle detect delay" is set to 0.
![image](https://user-images.githubusercontent.com/5494702/131257774-9f0dc28d-e3a1-46af-8140-05fd3a948062.png)

**Comment by bsongis-frsky** [comment]
Starting with RC4, the default setting will be 0
