### ISSUE TITLE
Screen Order

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#872]
Is there a way to change the order of the screens ?

**Comment by jasalca** [comment]
It´s a good idea ,so that when you turn on the radio it shows the screen you want as the main

**Comment by hrenz** [comment]
How can I selecet to show a Screen X by a switch
Example Custom switch or SI SJ to select Screen 1 to Screen X  up down

**Comment by jbesse262** [comment]
Use the page button...

**Comment by jasalca** [comment]
Yes of course, but that's not the purpose.If you have many screens and you want one to come out as the main one, every time you turn on the radio, you should be looking for that screen

**Comment by jreis1** [comment]
same as #277
