### ISSUE TITLE
Consumption calculation a bit off

### ISSUE THREAD

**Issue by timmybeetle** [FrSkyRC/ETHOS-Feedback-Community#873]
Hi

Using this on my X20 I noticed that there is a slight difference in used maH.
See pics bellow.
It's off around 6-9%
![p47 consumption test fass40 1001 maH 1 screenshot-2021-08-27-45989](https://user-images.githubusercontent.com/84274019/131173621-39efeb61-4105-4300-bb7f-427a315bbc1d.jpg)
![IMG_7071](https://user-images.githubusercontent.com/84274019/131173639-60a99693-2ddb-4c64-bb7f-9f7efd166a60.JPG)
![p47 consumption test fass40 1001 maH 2 screenshot-2021-08-27-45989](https://user-images.githubusercontent.com/84274019/131173656-88abeaf4-8ba5-4dbf-8ed6-5db1206258c1.jpg)
![IMG_7073](https://user-images.githubusercontent.com/84274019/131173668-eac981ff-a688-435a-9688-08943b2ecc91.JPG)

Regards Hans

**Comment by FBarrao** [comment]
you should compare it with a amp metter in series, the charger indication is not accurate..

**Comment by timmybeetle** [comment]
Update did check it with my Taranis X9D, using this radio I never had a big difference in consumption and charge readings.
Taranis X9D reading is 1001maH and charging it with my Hyperion 720 reading is 1008mah.
So I rest my case.......
![IMG_7085](https://user-images.githubusercontent.com/84274019/131226309-32723c1c-bcd5-4768-8257-b5d3b73e65e3.JPG)
![IMG_7087](https://user-images.githubusercontent.com/84274019/131226314-38261b02-0370-4045-81fb-c02b0af035f2.JPG)

**Comment by bsongis-frsky** [comment]
I am not sure I understand correctly this issue, do you compare the charge of your battery with the discharge? It's impossible that they are equal, a battery will never return the whole energy you give with your charger, and the difference will be increased by many factors, like the battery age, how you use(d) it, etc.

**Comment by timmybeetle** [comment]
Hi


Test setup:
1, charged LIPO with charger I use during test to 98%
2. test with XMTR and wait till 1000maH is used with consumption.
3. Recharge LIPO with charger used to charge LIPO to 98%
4. see results

I know there will be a small difference, but as you could see I checked it
with my Taranis X9D.
Did test the same way as with X20.
Taranis X9D, results used on X9D is 1001 maH and charger gave 1008 maH so
that's not a great difference.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/873#issuecomment-907661912

X20, results on X20 1001 mah and on charger 1070 maH thats a bigger
difference.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/873#issue-981497884



Thanks for your support.

Greetings Hans

Op ma 30 aug. 2021 om 13:01 schreef Bertrand Songis @ FrSky <
***@***.***>:

**Comment by bsongis-frsky** [comment]
Please would you do the same test with Logs enabled (logging for current)? We will be able to see if the numbers are right or not!

**Comment by timmybeetle** [comment]
Hello

I did log my test so I can give you my log files.

Greetings Hans

Op ma 30 aug. 2021 om 14:20 schreef Bertrand Songis @ FrSky <
***@***.***>:

**Comment by mawzthefinn** [comment]
Bot failed to close as stale on March 7th. Closing
