### ISSUE TITLE
The clock is forward

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#874]
I have observed that the clock is advanced by week about 10 minutes

**Comment by AlwinHaas** [comment]
At my s20x ist the same problem. At tree weeks the run 30 minutes in forward.

**Comment by pld74** [comment]
I have the same experience with both my X20 and X20S radios. Time is off by about 10 mins per week.

**Comment by timmybeetle** [comment]
Hi
already mentioned here

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/549

**Comment by jreis1** [comment]
+1
quite frankly, this needs to be solved as its a bit annoying.

**Comment by bsongis-frsky** [comment]
Duplicate

**Comment by bsongis-frsky** [comment]
I will fix it later with something on settings, because we cannot change the hardware
