### ISSUE TITLE
Model file corrupted

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#875]
Today I’ve had 2 model files corrupted.

The first time, I had edited a logical switch. Returned out and selected a different model. On returning to the new model, the file was corrupted and couldn’t load. However, it could be cloned and had most of the settings still. 

Later in the day, after creating the model again, I was editing a logical switch, and the transmitter entered emergency mode. After rebooting the transmitter, the model file was again corrupted and the new model wizard was opened. Again, the model could be cloned and most of the settings were still there. 

I am using a genuine SanDisk Ultra 16GB MicroSD card. 

![C7195537-943F-45B0-A020-408157FA460C](https://user-images.githubusercontent.com/17590174/131221270-363259eb-6955-4e86-b6b8-6778e4af370e.jpeg)

**Comment by Hobby4life** [comment]
best is do zip the models folder and place it here for debugging

**Comment by MrD-RC** [comment]
I can share the cloned model. But the one that died has been deleted. I can keep them it happens again.

**Comment by Hobby4life** [comment]
Do you have a backup of the sd before it happened?

**Comment by MrD-RC** [comment]
No, this all happened out in the field. I took the plane, then realised it was still set up on my old transmitter, which was at home. 

All other models seem fine. Only that one corrupted. Fortunately I only have 1 other plane that I’m currently flying on that transmitter. I will be making backups all the time now. Still, I can’t see this being the fault of the MicroSD card. I’d understand it if it was a Banggood special. But it’s a decent card.

**Comment by MrD-RC** [comment]
This is the clone of the corrupted model file if it helps.

[model14.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7071139/model14.zip)

**Comment by bsongis-frsky** [comment]
You say you cloned a model file which could not be opened. Please share this file, I see no error on the clone.

**Comment by bsongis-frsky** [comment]
Bad SD are very difficult to detect with the eye, only small details like painting on the SD sides etc. I have a lot of fakes from many brands (Sandisk, Samsung, etc.) and bought from retailers in France!

You have to check your SD with software. It will write content on the whole SD and check that it is read the same.

On a bad SD, only the first blocks will work, others will write OK, but read will return only garbage.

**Comment by MrD-RC** [comment]
> You say you cloned a model file which could not be opened. Please share this file, I see no error on the clone.

As I mentioned above. I’d deleted that file already unfortunately.

**Comment by MrD-RC** [comment]
> Bad SD are very difficult to detect with the eye, only small details like painting on the SD sides etc. I have a lot of fakes from many brands (Sandisk, Samsung, etc.) and bought from retailers in France!
> 
> You have to check your SD with software. It will write content on the whole SD and check that it is read the same.
> 
> On a bad SD, only the first blocks will work, others will write OK, but read will return only garbage.

This is not a bad SD card. I had been using it previously with no errors at all. It was bought directly from SanDisk, so not a clone.

**Comment by bsongis-frsky** [comment]
If you succeeded to clone the file, I think it's not possible that the model is broken, so it must be something else, or perhaps a conversion? Only 1.0.10? Or you tried 1.0.11 RCx?

**Comment by MrD-RC** [comment]
@bsongis-frsky this is only on 1.0.10. The model was new on Saturday, so hadn’t been on an older version. 

The first file that corrupted (not emergency model, just switching models). When I tried to enter the model, a message appeared that it could not be opened, due to invalid data, or something along those lines. 

The second time was the emergency mode. The model would open, but immediately went in to the new model wizard. 

Both times, the corrupted model could be cloned and opened. Some setting were missing, like the mixer, RF, and some of the logic.

**Comment by Hobby4life** [comment]
> @bsongis-frsky this is only on 1.0.10. The model was new on Saturday, so hadn’t been on an older version.
> 
> The first file that corrupted (not emergency mode, just switching models). When I tried to enter the model, a message appeared that it could not be opened, due to invalid data, or something along those lines.
> 
> The second time was the emergency mode. The model would open, but immediately went in to the new model wizard.
> 
> Both times, the corrupted model could be cloned and opened. Some setting were missing, like the mixer, RF, and some of the logic.
> 
> I’m kicking myself that I deleted the bad model files

We have the luck as we have a PC at our club, so with minor gliches I can directly dump my SD card on the field. :-)

**Comment by bsongis-frsky** [comment]
I hope you will succeed to reproduce it then. Take care to the LS name / Mix name, there is a bug there in 1.0.10 which has been fixed since.

**Comment by MrD-RC** [comment]
> 
> We have the luck as we have a PC at our club, so with minor gliches I can directly dump my SD card on the field. :-)

That’s the annoying part. I always have my laptop with me. Especially if I’m planning/hoping to test iNav changes.

**Comment by MrD-RC** [comment]
> I hope you will succeed to reproduce it then. Take care to the LS name / Mix name, there is a bug there in 1.0.10 which has been fixed since.

Perhaps it was naming the LS that caused the issue in that case. It would match up to how the problem happened. Any more and I’ll keep the file. It may happen as I’ll stick with 1.0.10 until the stable of 1.0.11 is released. 

I have a fresh version of the model working now. It flew well. So all is good.
