### ISSUE TITLE
Feature request: Add function type to throttle mixer

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#877]
Today I tried to create a setup with two throttle sources. Basically I want the left slider to work as a progressive throttle. I also wanted the rear button to work as an instant throttle, for F5B type flying. 

Setting both inputs up as a throttle mixes does not work, as it defaults to the **Add** function type. For this, I would like to set it to **Replace**. The reason that I want to use the throttle mixer type is so that both have throttle cut, without having to code my own.

**Comment by bsongis-frsky** [comment]
Why don't you create a virtual input for your Throttle mix?

**Comment by MrD-RC** [comment]
I’ve had to do that in the end as there were other issues: 

- having the throttle source inverted did not invert the function of the timer, so it would count down at zero throttle, but stop at full throttle. This was when I used the throttle input type.
- After converting to free mixes, the timer did not work at all

I ended up having to output the free mix throttles to another channel, and use them as inputs to a throttle mix to get everything to work. Which sort of makes me miss having the inputs page. In OpenTX, I would have set the slider and buttons as inputs. But where ETHOS doesn’t have separate inputs, you tend not to think about using it like that. Having everything in one place just doesn’t seem so intuitive, even though it works.

**Comment by mawzthefinn** [comment]
Now that Throttle supports a selectable input and VAR mixers allow Use a Source for a weight, this is entirely doable using a VAR mix as an input selector.

Create a Var mix
Name it Throttle Picker (or whatever you choose)
Long press the default weight, select Use a Source, wiggle your desired slider to select it as your default.
Add a weight, set the switch to your rear button, set the value to Maximum.
Set the output to a high channel (I used Ch64 in my test).

Then go to the Throttle Mixer, select Channels->CH64 as your Input.

The rest of the Throttle/Timer functions will work normally.

**Comment by mawzthefinn** [comment]
@MrD-RC Did this solution work for you?

**Comment by MrD-RC** [comment]
@mawzthefinn yes that works. The key was getting the selectable throttle source.

This has however highlighted that the Var mix is really badly named. I has assumed it was short for Variable. But it is more Various, or a combiner mixer. It would be handy if that mix had a more meaningful name.

**Comment by mawzthefinn** [comment]
@MrD-RC I agree on the Var mix name. When originally created it was just that, selectable variables. The addition of selectable sources has made it more of the Swiss Army Mix.
