### ISSUE TITLE
reading trace system clock value by function.

### ISSUE THREAD

**Issue by GiorgioCirelli** [FrSkyRC/ETHOS-Feedback-Community#880]
reading trace system clock value by function.
Do you think it is possible to insert this functionality?

**Comment by bsongis-frsky** [comment]
"trace system clock", what do you mean?

**Comment by GiorgioCirelli** [comment]
sorry for the poor English ...
I refer to the current time

**Comment by Hobby4life** [comment]
> sorry for the poor English ...
> I refer to the current time

So you want a **special function** to call out the time?

**Comment by GiorgioCirelli** [comment]
> > scusate il pessimo inglese... 
> > mi riferisco all'ora corrente
> 
> Quindi vuoi una **funzione speciale** per richiamare l'ora?

yes

**Comment by GiorgioCirelli** [comment]
I use the radio for flight on slopes and after a few hours I lose track of time.

**Comment by mawzthefinn** [comment]
System->Clock is now available to call out the time from the Play Value Special Function
