### ISSUE TITLE
Rx R10 Pro telemetry - single batt volt when using 2 batteries

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#881]
Hi all,
Don’t know if this is standard behavior or a bug. I am getting a single battery sensor in telemetry when using 2 different Lipos connected to a R10 receiver. Is there any way to split into bat1 and bat2?
I know RB20 has 2 different telemetry sensors like Bat1 and Bat2, but R10 is showing a single one when I run the procedure “discover new sensors”.

**Comment by bsongis-frsky** [comment]
Did you change the appId or physId of one of your 2 sensors? Otherwise you will have conflicts, and you will only see one sensor

**Comment by Hobby4life** [comment]
To be honest, I have never noticed a second batt sensor on a (S)R10.. have to check it out tonight.
Or is it only available on discover, when a actually a battery is connected to these ports?

**Comment by marciomc-github** [comment]
> To be honest, I have never noticed a second batt sensor on a (S)R10.. have to check it out tonight.
> Or is it only available on discover, when a actually a battery is connected to these ports?

I think there’s no second sensor on R10. 
Only RB20 has bat1 and bat2 sensors.

**Comment by marciomc-github** [comment]
> Did you change the appId or physId of one of your 2 sensors? Otherwise you will have conflicts, and you will only see one sensor

There’s no external sensors in my setup. The issue is with internal sensors on a R10 receiver that have 2 battery input. 
I believe there’s no issue with Ethos, but with the R10 rx itself, that does not provide 2 sensors in the telemetry.

**Comment by bsongis-frsky** [comment]
Understood. Enhancement on R10 Rx then.

**Comment by marciomc-github** [comment]
> Understood. Enhancement on R10 Rx then.

Should I close this issue?

**Comment by NMO81** [comment]
I can confirm that there is only 1 sensor available in my SR10pro. It always shows the bat it uses, it is a constant toggling system.

**Comment by Adelaxie** [comment]
Current hardware does not support two cell measurements but still thanks for your advice which we can consider in later products.
