### ISSUE TITLE
Feature Request: allow set of primary receiver, and/or commanded switch over

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#882]
As noted in #782 some of the multi-RX functionality is less-than-desirable.  

At a minimum the ability to set the primary receiver (the one to favor on power-up is needed).  Preferably though it would switch back to that receiver whenever it is available.  I flew today with a GR8 and an Archer RS as the backup through the SBus, I experienced several switch-overs, with no loss of control, and for this large carbon airframe that makes perfect sense.  The problem is that I would prefer it return to the GR8 when it can, of that I could command it to try and switch?

IS there a way using F.Port and S.Port to run the GR8 telemetry through the RS?  Anyone have the wiring for that drawn out?

**Comment by mawzthefinn** [comment]
Closing off as it is a protocol limitation at this time as per @Adelaxie , not ETHOS.

Note the limitation is for telemetry only, control is evaluated on a per-frame basis and best frame is used.
