### ISSUE TITLE
Audio Distorted with SD Log Running

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#883]
I have realised that with my Horus X10S Express and ETHOS 1.0.10 the audio output is not useable when the SD log is running. The audio is severly slowed down and distorted, and the smaller the recording interval is, the worse it is. Even with 300 or 500ms the effect is noticeable, but with a logging interval of 100ms, which is what I am using, the audio is completely useless.
I use a 16GB Intenso HC Class10 card, which works absolutely fine w.r.t. the audio output when OpenTX is flashed.

**Comment by Hartinger** [comment]
I have updated to ETHOS 1.0.11 RC3, and the problem remains the same, as expected.

**Comment by Hobby4life** [comment]
Strange, as I use logging for all my models.. and have lots of sounds playing back during a flight..
I have not noticed distortion or some sort.

Possible to share a dump of you SD card?

**Comment by MIKE-DAILEY** [comment]
X10S Express with 1.0.11. RC3 and no sound issues with logs running.

**Comment by Hartinger** [comment]
The problem occured both with system and with custom sounds, language is German, by the way.

When I wanted to upload the SD card content I found that the log folder was damaged and could not be accessed or deleted. I then made a backup and fully reformated the card using SD Card Formatter. I restored the backup (except the log folder) and now the problem is gone. So it seems that it was due to a faulty SD card.

I don't know why the SD card was damaged but I beleive this issue can be closed.

**Comment by Hobby4life** [comment]
> The problem occured both with system and with custom sounds, language is German, by the way.
> 
> When I wanted to upload the SD card content I found that the log folder was damaged and could not be accessed or deleted. I then made a backup and fully reformated the card using SD Card Formatter. I restored the backup (except the log folder) and now the problem is gone. So it seems that it was due to a faulty SD card.
> 
> I don't know why the SD card was damaged but I beleive this issue can be closed.

Is this the stock 4gb?? if so ditch it.. these cards **always** have caused problems in the past.
Buy a generic Sandisk SD card, and you are good to go for a looooooooong time :-)

**Comment by Hartinger** [comment]
No it's not the stock one, but if it causes problems again it will go in the bin.
