### ISSUE TITLE
Multiprotocol module support

### ISSUE THREAD

**Issue by sgsracer256** [FrSkyRC/ETHOS-Feedback-Community#885]
it would be very nice to configure a external module in bay from ethos os model setup page like you can do on radiomaster under opentx. it can be done for example on a frsky taranis lite with irx4 lite module so it must be possible with the combination ethos and irx4 lite

**Comment by Hobby4life** [comment]
I also like to see Multiprotocol serial support too.

As for now I have modified my ir4x module to support PPM and manual configuration:
https://hobby4life.nl/?p=626

**Comment by sgsracer256** [comment]
i know your solution but if i pay 4times the price of a opentx (eg radiomaster) hardware and in opentx its possible to configure it, it should also be possible in ethos which is a opentx fork or lets say "new os". i know about the ppm or serial config option but it should be possible like on the frsky taranis lite, the pinout is the same on the module bay

**Comment by bsongis-frsky** [comment]
Don't you think that if Ethos was a fork of OpenTX Lua would be there from day 1?
The multimodule is a lot of work if you don't want just to copy the code which is in public domain

**Comment by sgsracer256** [comment]
thanks for your interest to implement it i know its not easy.

**Comment by jbesse262** [comment]
@sgsracer256  sit down...

**Comment by sgsracer256** [comment]
Im so sorr that i cannot code…

**Comment by sgsracer256** [comment]
I will and spend you a beer if this will work… or 2 or 3… will save my customer projects

**Comment by andika207** [comment]
> it can be done for example on a frsky taranis lite with irx4 lite module so it must be possible with the combination ethos and irx4 lite

@sgsracer256 if you want to make use of MPM keep an eye on the @mikebland ErskyTX

**Comment by jfint** [comment]
Can someone edit the stupid subject of this so its spelled correctly?

**Comment by bsongis-frsky** [comment]
I have added one k :)

**Comment by sgsracer256** [comment]
do you generally think it will be possible to access the multiprotokol module after your work on the lua scripts ? this would be so wonderful.

**Comment by andika207** [comment]
@sgsracer256 I wish I had a clear answer for you.
my issue https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/7 got closed down however this one is still open.... maybe they have just changed their mind  ?

another possibility is, if ErskyTX @MikeBland is able to overcome the MPM barrier then it would be stupid to not support it on ETHOS by default, anyway you can do dual boot so it would not by a major problem if never supported.

**Comment by andika207** [comment]
@sgsracer256 check this out https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/5#issuecomment-1053795094

**Comment by andika207** [comment]
@sgsracer256 check this out https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/5#issuecomment-1053795094

**Comment by Adelaxie** [comment]
Duplicated with #5

**Comment by LaurentCzl** [comment]
Adding my two cents as I am convinced giving ETHOS a serial communication feature with multiprotocol external modules would be a significant value added. I know it's easy to ask, but the dev team already made a great work with ETHOS, so ... keep up the good work !

**Comment by Adelaxie** [comment]
@LaurentCzl closed the duplicated issue and leave the #5 there.
