### ISSUE TITLE
Variolimit  +/-10m/s is to less

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#887]
G-Rx6 G-RX8 Vario Limit  +/-10m/s is too less
please change it to +/-15m/s

Sensor can +/-16.7m/s

**Comment by Hobby4life** [comment]
v1.0.11 rc3
![image](https://user-images.githubusercontent.com/55426642/131508050-f985cfff-4839-4de6-9bf9-1e7fb67d15bd.png)

**Comment by hrenz** [comment]
thanks fine ,ist ok

**Comment by bsongis-frsky** [comment]
Why this issue, 17m/s are already possible!
