### ISSUE TITLE
Feature request: Add function type to throttle mixer

### ISSUE THREAD

**Issue by MPFlyer** [FrSkyRC/ETHOS-Feedback-Community#890]
Proposal for improvement in the gas mixer

I am a helicopter pilot and I use different flight phases, each with a fixed rotor speed (governor). As of today I have to define for each flight phase (RPM) a separate 2-point curve for example 20%, 40% and 75%.It would be nice if the feature "hold throttle" in the throttle mixer would be extended by several values (according to the flight phases).

**Comment by mawzthefinn** [comment]
You can do this today using a VAR mixer as an Input selector.

A VAR mixer can present your selection of sources or fixed values (and covert between the two), so if you create a VAR mixer, set the values you want as the various weights, then use that channel as the Throttle Input, you get exactly what you want.

As a bonus, the selection is priority based (higher is preferred), and use a mix of Flight Modes and other inputs to have an override available on a switch.

**Comment by mawzthefinn** [comment]
Closing off as a solution was provided.
