### ISSUE TITLE
Feature request.  Setting priority RX for telemetry 

### ISSUE THREAD

**Issue by Droptank** [FrSkyRC/ETHOS-Feedback-Community#892]
Using ArcherRS as redundant receiver for my R8pro or SR8pro.  I’m using AIN sensor on pro receivers for battery pack voltage telemetry.  Since the Archer RS boots up faster it always seems to be the first sending telemetry over the pro rx so the AIN sensor doesn’t appear.  I can disable telemetry on the RS to force the pro’s to be the only telemetry senders but then if the rx switches then I lose all data.  

I would like the ability to set a receiver as “master” or “priority” for telemetry data.

**Comment by mpjf01** [comment]
See #882 and others linked there
