### ISSUE TITLE
Volume Control for variometer

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#893]
Hello, first of all I would like to thank you for your great work. I think Ethos is great.
I have a small suggestion regarding the variometer. Is it possible to add an independent volume control for the variometer, which could then be adjusted via a slider during the flight, for example?

**Comment by bsongis-frsky** [comment]
Already available in 1.0.11

**Comment by bluelex73** [comment]
😁👍
