### ISSUE TITLE
New Calculated Sensor in Telemetry screen

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#894]
It does not seem that the Neuron range of ESC's provide the value of Power as in WATT (W) in Telemetry, 
but they provide Amps (A) and Volt (V).
How about a new "CalculatedSensor" in Telemetry that calculate A * V = W?

**Comment by AndyH56** [comment]
This would be very useful, it is something I do in OTX.   To make it more flexible why not just have a 'multiply' calculated sensor ( as in OTX) . Then you could use any two inputs.   This has been previously requested but seems to have  been lost when the MAH calculated sensor was marked as closed.

**Comment by Hobby4life** [comment]
+1

Also add option altitude in calculated sensor Distance. For Line of sight calculation.
