### ISSUE TITLE
Servo telemetry, configuration

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#895]
Errors, comments.

The flying machine is a 1.5 DLG
I chose this system because the new SBUS servos are small, powerful and seemed like the perfect choice.

Hardware configuration:

Radio: TANDEM X20S

Servo: HV5701 (Firmware HV 1.5.5 latest release) 
The old firmware 1.5.4 has incorrect telemetry temperature data. Fixed 130 degrees Celsius. HV 1.5.5 firmware finally shows temperature. Still pretty bad data though. 
In a 22 degree Celsius apartment with 4 servos it shows 12; 17; 28; 17 degrees. After 10 minutes 22; 28; 36; 30

Receiver unit: ARCHER GR6 ( Firmware v2.1.8 latest release)

The four servos are configured:
1) Physical ID: 01; Application ID: 0A; Channel CH1
2) Physical ID: 03; Application ID: 0C; Channel CH3
3) Physical ID: 04; Application ID: 0D; Channel CH4
4.) Physical ID: 05; Application ID: 0E; Channel CH5

The four servos are connected to the receiver unit with F.PORT2.0.
The telemetry sees the four servos (SRV1; SRV2; SRV3; SRV4) and reports their data. 
However, if I want to adjust any of them, it will mix the set data of the servers.
In fact, if I open the same SRV1 several times (Decice Config), the set values (Phy. ID- App. ID - Channel) change 
The same happens for SRV2; SRV3; SRV4.
So it is impossible to set any of them to a different value afterwards (F.PORT2.0)

Works fine when connecting a servo! 
The mix-up only occurs when connecting multiple servos.

Also, the problem is that if the servers are configured, why can't they be updated on F.PORT2.0 and why do they have to be connected one by one?

This would be nice to solve, since they are fixed connected to the SBUS bus. So the upgrade is very difficult and complicated.

My other problem is that in the OTX system ( HORUS X10S) it was perfectly possible to set the servos to the default value and right to left the same deflection was maintained if the 1500 as center value was set and the delta ( triangle) signal was set to = signal.
This is not possible now for Ethos.
By moving the -100 and +100 values up and down, the adjustment is complicated and cumbersome.
Maybe I just don't know where to set the base value to shift the deflections along with it?

Thanks if I get feedback on these problems.

**Comment by mawzthefinn** [comment]
These issues appear to have been addressed in #989 

Closing in favour of the other issue
