### ISSUE TITLE
Still having problems with my GPS

### ISSUE THREAD

**Issue by andrescuadrosjdc** [FrSkyRC/ETHOS-Feedback-Community#898]
GPS Updated to the last FW and X20S in 1.011 c3
Cannot configure it, entering in Device settings it doesnt appears with a ID
Bad readings for altitude and speed
![IMG_0073](https://user-images.githubusercontent.com/89352761/131949089-0d7eb31c-585e-4a86-a2e5-4c584854996d.jpeg)
![IMG_0072](https://user-images.githubusercontent.com/89352761/131949098-8a4b9db6-70bd-43b3-b286-7bd3c97dd42f.jpeg)

Could be possible to config as telemetry windows (Max and min GPS speed) and (max and min GPS ALT) as in OpenTX?

**Comment by mawzthefinn** [comment]
Are you still having the first issue?

The min/max is available via Long-pressing the value after selecting in Widget configuration

**Comment by mawzthefinn** [comment]
Closing off as no additional info have been received.
