### ISSUE TITLE
Change way  Custom Button 

### ISSUE THREAD

**Issue by Paolotandemx20s** [FrSkyRC/ETHOS-Feedback-Community#899]
hi, run 1.0.11 rc3 with x20s, note from firmware 1.0.10 you no longer have on / off system for custom button, but to activate and deactivate a function you have to jump to another custom button, it would be very good to go back to the origin .
![X20S-Blue-1_1](https://user-images.githubusercontent.com/86721010/132008858-669a9a47-2a0b-4037-b503-8a73efc75806.jpg)

**Comment by FBarrao** [comment]
Yes, you can configure the way you want to work for those buttons. 
But yes, on 1.0.11 the default configuration of the button has changed, same happened to me when installed 1.0.11.

**Comment by Paolotandemx20s** [comment]
Thanks for the information, I have tried on hardware configuration and special functions but I have not found a way to change, possible to have more information? Thanks again

**Comment by FBarrao** [comment]
Yes, here you are. Go to hardware.
Function switches.  Here you have several options for them. For your needs, use   6x2-pos option.  ( 6 switches of two positions). 

![f1](https://user-images.githubusercontent.com/88581380/132045483-ed3bae73-d2b6-4e7c-82a7-d99207e1b1d4.jpg)
![f2](https://user-images.githubusercontent.com/88581380/132045487-f9acf80e-d27c-4f6f-84cb-45f80fdc3b4d.jpg)

**Comment by Paolotandemx20s** [comment]
perfect, tried and works great thank you very much again
