### ISSUE TITLE
Issue , Helicopter template

### ISSUE THREAD

**Issue by aaerografixs** [FrSkyRC/ETHOS-Feedback-Community#9]
H1 template in Helicopters,  freezes the radio when trying to make adjustments, also the template is all wrong for FBL

**Comment by andika207** [comment]
@aerografixs just a remark, the HN3 and H-2 modes are missing on the ETHOS software.

**Comment by andika207** [comment]
@aaerografixs just a remark, the HN3 and H-2 modes are missing on the ETHOS software.

**Comment by bsongis-frsky** [comment]
Fixed
