### ISSUE TITLE
X20 ETHOS 1.10 telemetry issues

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#901]
Hello,

I use non-Frsky current sensor. It meassures 44A, I meassured also with a current meter tool, 45A. But Ethos telemetry shows up 34A.

Also hight, real hight 198 m but ETHOS telemetry displayed 125 m. 

What is the problem? 🤔🤔

Thank you 🙂

**Comment by timmybeetle** [comment]
Hi

Maybe you can test it again with 1.0.11 cd3 , but backup yours models and radio.bin first as 1.0.10.
I got an issue with my airspeed sensor in 1.0.10 readings where half and with 1.0.11 cd3 al is fine.

let us know if this worked out fore you.

greetings Hans

**Comment by combat-marcus** [comment]
> Hi
> 
> Maybe you can test it again with 1.0.11 cd3 , but backup yours models and radio.bin first as 1.0.10.
> I got an issue with my airspeed sensor in 1.0.10 readings where half and with 1.0.11 cd3 al is fine.
> 
> let us know if this worked out fore you.
> 
> greetings Hans

Thank you. Is in 1.0.11 cd3 also the current, hight sensors and so fixed?

**Comment by timmybeetle** [comment]
Hi

Maybe it would be a good idea if you also give brand off sensor, I assume you are using UNISENS.
I have UNISENS , but I didn't recall my height values only my airspeed.
Current is working as it should

greetings Hans

**Comment by combat-marcus** [comment]
> Hi
> 
> Maybe it would be a good idea if you also give brand off sensor, I assume you are using UNISENS.
> I have UNISENS , but I didn't recall my height values only my airspeed.
> Current is working as it should
> 
> greetings Hans

SM modellbau current sensor with Uni Log 2, yes.

**Comment by timmybeetle** [comment]
Hi

I suggest that you first test it with ETHOS version 1.0.11cd3( I did and for me it's working fine now) I think that yours problems will be solved doing that.
If not you can come back here and report yours findings.

Regards Hans

**Comment by combat-marcus** [comment]
Thanks mate! I do!

**Comment by timmybeetle** [comment]
Hi

If I look at website and you are using this one
https://www.sm-modellbau.de/UniLog-Stromsensor
but that one only is for amp, consumption and voltage

hans

**Comment by combat-marcus** [comment]
Yes but I use it with Uni Log 2 which includes rest of sensors for hight and so. I can safe all data on it and analyse it on computer

**Comment by combat-marcus** [comment]
But VFAS works fine anyway and mAh (consumption).

**Comment by timmybeetle** [comment]
Hi
Next time would be nice to give more information about setup!

![unilog-2~4 jpg rcvr connection](https://user-images.githubusercontent.com/84274019/132116939-bf296a33-877d-4ffd-bb7e-02757d5b91d2.jpg)

I can't help you with this because I use the UNISENS-E, 
good luck with solving this.

Regards Hans

**Comment by combat-marcus** [comment]
I closed topic guess I figured out Problem.
