### ISSUE TITLE
not possible to write logs from model name with special character like ><

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#904]
I had a model name << Slik >> and I was wondering why no log files were written.
my assumption that it is due to the special characters in the name of the model has been confirmed.
Perhaps it would be possible to replace these special characters with "-" as we do with spaces or the special characters are blocked in the model name.

**Comment by mawzthefinn** [comment]
You can no longer name models with reserved characters, which solves this issues
