### ISSUE TITLE
Tandem X20

### ISSUE THREAD

**Issue by gomitologiallo** [FrSkyRC/ETHOS-Feedback-Community#906]
Greetings,
I cannot turn on the Tandem X20.
I turned it off and now it doesn't work.
Could someone please help me?

**Comment by mawzthefinn** [comment]
I do understand this is an older issue, however it is not one that can be addressed here. 

For issues like this I recommend contacting your FrSky dealer or your local FrSky service center, which can be found here:

https://www.frsky-rc.com/service-center/
