### ISSUE TITLE
X12S ETHOS1.0.2 Function bug & Default voice announcement

### ISSUE THREAD

**Issue by GIB2A** [FrSkyRC/ETHOS-Feedback-Community#91]
Hello
Function bug
In the function menu, then play a sound, it is impossible to select a wav file

Default voice announcement
The welcome announcement in French contains a pronunciation error and indicates zetos and not ethos. 
Cordially .

**Comment by MIKE-DAILEY** [comment]
The Play Track in Special Functions is working here.  X12S ISRM on 1.0.2.  

The user sound files should be in the path "audio".  There are other sub folders in "audio" but the users files are in "audio".

**Comment by bsongis-frsky** [comment]
"Bienvenue sur Ethos" en 1.0.3, cela évitera la liaison
