### ISSUE TITLE
Issue in Log file

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#911]
![image](https://user-images.githubusercontent.com/16795828/132203998-0249f9a6-a307-4652-b8e6-8ca8c7f1b5aa.png)

Customer claimed the space in the front of "DrehG_Re". But I can not find it in my translation. Please check it.

Further the customer claimed that left and right is swapped. But only in the log file!

**Comment by bsongis-frsky** [comment]
He changed the name himself I think, there is not such a translation
