### ISSUE TITLE
Keine Meldung Akkuspannung Sender niedrig

### ISSUE THREAD

**Issue by Piperkre** [FrSkyRC/ETHOS-Feedback-Community#912]
Hallo
Leider habe ich heute meine große Wilga verloren. 
Kurtz nach dem Start ging der Sender ohne Meldung aus und ließ sich nicht wieder einschalten.
Die Wilga total Verlust.

Meine schwellen werte in der Anlage 6,3 Volt

Leider kam keine Meldung Akkuspannung schwach!!!

**Comment by Hobby4life** [comment]
It seems that you running old firmware. :-(
New firmware v1.0.10 has valid default alarm voltages set.
below 7.0v LCD display will shut down, and finaly go into Emergency mode, then shuts off.

**Comment by Piperkre** [comment]
Ich habe diese Firmware v1.0.10 
Es blieb keine Möglichkeit zu reagieren. Sender hat sich ohne Vorwarnung abgeschaltet :-(
