### ISSUE TITLE
Telemetry switch settings removed after a Redicover of sensors

### ISSUE THREAD

**Issue by Aerial-Image** [FrSkyRC/ETHOS-Feedback-Community#913]
X20S on FW 1.1.10

Wouldnt it be better that any Logic switches or Special Fuctions settings be left as they were set before the rediscover?

**Comment by jasalca** [comment]
But if now it´s much better . They have many more configuration variations.

**Comment by Hobby4life** [comment]
There are 2 ways of re-discovering.

1. Adding new sensors
2. Delete all sensors

With adding new sensors it should be obvious that already present sensors should not be deleted, only new ones are added.

By removing the present sensors, you literally indicate that you want to remove them. then it doesn't make sense that they still roam around somewhere in the system.

**Comment by bsongis-frsky** [comment]
Perfect explanation @Hobby4life, thanks!

**Comment by Aerial-Image** [comment]
I only rediscovered any new sensors & it deleted the settings that I had already made for switches etc thats what I am trying to say?!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Hobby4life** [comment]
Hmm another question.

Do upgrade with official firmware releases only?.
Or do you upgrade with every release candidate?

**Comment by Aerial-Image** [comment]
Only with Official relases...

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Hobby4life** [comment]
@bsongis-frsky 

Ok, then there is a clear pattern occurring. why some people have more problems than others.

Clearly here on our side, it can be clearly seen that people who upgrade with each release candidate have significantly less problems than people who only upgrade with official releases.

**Comment by Aerial-Image** [comment]
Ok understand – I will keep updating with your interim releases... & see how it goes.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Hobby4life** [comment]
Before you upgrade, always make a copy of your SD card.
Tip create/name a folder with date and FW release.

![image](https://user-images.githubusercontent.com/55426642/132315305-d1136d05-51ad-4289-b7bb-d198cdce1d02.png)

radio.bin and your models folder are the 2 most important to backup.
