### ISSUE TITLE
Favourite group

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#914]
Models are now grouped based on their model category, I’d like to see more flexibility/control over groups. 

Either the ability to create your own groups and the ability to move models from one group to another.

Or adding a favourites group to the model select page showing 6 or 8 tiles with models you marked as favourite for quick access to your most flown models from the different groups.

**Comment by pld74** [comment]
Great Suggestion!

**Comment by mawzthefinn** [comment]
The first option was added with custom model folders in v1.1.0
