### ISSUE TITLE
Neuron ESC issues

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#915]
I have a Neuron 80 ESC (https://alofthobbies.com/frsky-neuron-series-escs.html) and my X20S is on 1.0.11 rc3. I bound my receiver and discovered telemetry and I end up the set of sensors in the image below. When the receiver is on I of course have blinking dots to the side of the telemetry items, but there are two main problems, first all the values seem "buffered"  For example, I run my throttle to full, let it sit for a bit, then bring back down to off. The ESC RPM value will take maybe 5-7 seconds to actually get to 0.  Technically it seems as if the values coming from the ESC are coming in faster than they can be displayed and rather than grabbing the latest value you are grabbing the value from a queue of sorts.

![image](https://user-images.githubusercontent.com/5494702/132256104-3addf028-2cef-45d3-8257-c6707cecf795.png)

**Comment by islandflight** [comment]
The delayed telemetry was a problem many versions ago and was fixed. I haven't done an update for a while but sounds like the issue may have returned?

**Comment by michifpv** [comment]
Hi. Is your volt reading correct? I still have the problem with my Neutron ESC that 16.8V instead of 17.4V are displayed. Nothing changes in the offset if I want to change it

**Comment by Cipta-de** [comment]
My voltage is right with 4s.
What batt you use? 17,4v?
