### ISSUE TITLE
Neuron ESC rpm telemetry wrong

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#916]
I have a Neuron 80 ESC (https://alofthobbies.com/frsky-neuron-series-escs.html) and my X20S is on 1.0.11 rc3.  In OTX the speed controller rpm sensor allows you to adjust the number of poles on the motor to get the proper engine RPM displayed. I see no such setting here. In the attached picture, you can see both mode and blades. Blades is a divider of sorts, so increasing that number decreases the indicated RPM's. 
The main problem is that my motor is a 487K 14 pole version running on a 6S battery, so the RPM's should be somewhere near 11k, but instead they are around 500-600.  
![image](https://user-images.githubusercontent.com/5494702/132257016-7f48a3b3-3398-4171-af46-8eecfe0b4c87.png)

**Comment by pgee63** [comment]
The same problem with my neuron 40 & 60  (1.0.11 rc3).

**Comment by Mordee** [comment]
Yes also with the Neuron 40s and 60s

**Comment by guycnicholas** [comment]
I am not sure what the "blades" property would even be for unless there are optical rpm sensors being used, and who would do that?

**Comment by Cipta-de** [comment]
Set Mode to gear and motor poles/2 for main gear and 100 for pinion teeth

**Comment by guycnicholas** [comment]
Thanks for the work around. I hope that doesn't end up being the final solution though as it is not a very obvious solution ;)

**Comment by Mordee** [comment]
Thanks also.
