### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#917]
[it.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7119981/it.txt)

**Comment by bsongis-frsky** [comment]
Perfect job!
Only this string has been added in RC4 and is missing in your file:
POWER_HAS_BEEN_CHANGED_PLEASE_REBIND "The power has been changed, please rebind!"

**Comment by mgsanna** [comment]
POWER_HAS_BEEN_CHANGED_PLEASE_REBIND "La Potenza Tx è cambiata, esegui
rebind!"

Il giorno mar 7 set 2021 alle ore 10:46 Bertrand Songis @ FrSky <
***@***.***> ha scritto:
