### ISSUE TITLE
[X12s] For the "AND" function in logical switches there is no option to use inverted switch positions

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#92]
I wanted to create some logical switches to set flightphases and found a problem.

When using the "and" function, which let's me select two stick positions, I can't use inverted/negated switch positions.

For example I want to use "SA_up" AND "!SC_down" to let the logical switch become TRUE.

Could you please implement that?

X12s on Ethos 1.0.2
ISRM-S-X10S (HW 1.10.; SW 2.16. (EU)
System language: German

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/115116812-f2f7b780-9f9b-11eb-9434-acc5da149ddb.png)

**Comment by MrD-RC** [comment]
I can’t access the negative option in the flight mode active condition box.
