### ISSUE TITLE
Wrong alert signal lost with tandem X20 and ethos? or real problem recevier on GRX8?

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#920]
Hello, since i go on ethos and my X20 i have one recceiver who send me alert "radio signal lost" some times but with no control lost and no fail safe activated.
That have been on all version off ethos since the first one for me 1.09. I have try many implantation of antenna that doesnt change. Alarms seems occuring in same position of the model in my flying field. Not really far i have not good eyes! 
The receiver i use is a GRX8 i have already use a long time with open tx and xlite pro, i have never had this issue. I have change one day the antenna because i destruct them when installing in  a glider, actually i have putted dipole antenna. I have try in over model and was about to let this faulty receiver but i wanted to try one last thing to be sure.

I try the receiver with a foam glider Heron both in the same location one time with X20 and come back to open tx and xlite pro and the result is that i have no alert at all with the XLITE pro. Some telemetry lost warning when i go far but never "radio signal lost" and rssi drop down and some times VFR like with ethos???

![GRX8 access tandem X20 ethos](https://user-images.githubusercontent.com/84435561/132387624-ea5092ed-4388-4535-b94d-f5ed61d0f423.png)

![GRX8 access xlite pro](https://user-images.githubusercontent.com/84435561/132387652-83696254-8abd-4c61-94f9-b113e5a114e2.png)

**Comment by mawzthefinn** [comment]
Is this still occurring with latest ETHOS, TD-ISRM and G-RX8 Firmware?

**Comment by mawzthefinn** [comment]
Closing off as no additional information provided
