### ISSUE TITLE
Battery Warning

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#923]
We can read more and more on the networks about crashes due to empty transmitter batteries. Of course, it's not the transmitter's or FrSky's fault, it's clearly the customer's fault.

But we simply have to realise that there are more and more consumers and fewer and fewer of them are concerned with the technology. There is a lack of basic knowledge about batteries etc..

Therefore, we should make sure that the customer can make as few mistakes as possible. Therefore the following suggestions for battery warnings.

1. automate battery calibration
2. define a lower limit for the warning threshold that the customer cannot go below in the setting. For example, 6.7 V for Lipo. With proper batteries, a remaining operating time of 15 minutes until switch-off should always be possible.

If FrSky wants to leave open the possibility that other battery types and capacities can be used, then it must be additionally queried in ETHOS whether Lipo`s, LiIonen etc. are used and what capacity the battery has. Accordingly, the minimum warning threshold must then be specified by ETHOS.

It would probably be easiest to define a lowest warning threshold that cannot be undershot by the customer. From this point on, the transmitter must also warn. The best way to do this is with a loud beep that does not stop until the transmitter is switched off. This warning must also not be allowed to be switched off.

Everything else I mentioned would be gimmicks that would be nice but are not absolutely necessary.

FrSky and Betrand, please think about it.

**Comment by pld74** [comment]
I agree. I also suggest that for emergency call outs such as TX or RX battery low that the users “no volume” setting does not override those call outs. Along the same lines as your post here. 

Maybe a selection of battery type and the default settings of min and max battery auto populate with safe values.

**Comment by jreis1** [comment]
I already crashed a model due to this issue. Actually, it was my first lost plane ever since I fly rc-planes. I've also seen other people complaining in other online sources about the same issue.

In my case, the low battery alarm was set at 7.0V, and few seconds after a single "Tx battery low" alarm, the radio suddenly went off. 
I've never seen anything like this before.  

Off course,  I can't blame anyone besides me as radios should always be fully charged before a flying session. 

Nevertheless, It is clearly to myself that the battery management in X20/Ethos is a sensitive issue and one can't relax regarding this matter.  Some kind extra protection would be very welcomed.

**Comment by pld74** [comment]
I think a Low Battery Voltage of 7.4V is much safer. At 7.4V battery capacity left is only 10%. That’s scary enough and if flying FPV and in Cold Weather, it’ll deplete quickly. Let’s all error on the side of caution and be safe. Keep our models flying and controllable to land them safely.

**Comment by jreis1** [comment]
I think a possible approach would be to find the minimum voltage that will maintain the hardware operating as expected, and set an hard threshold for minimum low battery warning value like 10% or 20%, above such value. 

Example:
- min. required voltage for right hardware operation:  6V (?)
- min. acceptable threshold value in radio config: 6V * 20% = 7.2V.  The user shouldn't be able to set the alarm below 7.2V.

**Comment by pld74** [comment]
I totally agree but we also have to take into account the Lipo technology itself. At 7.2V it is borderline safe and 7.4V is very safe. 

Something is better than nothing so this needs to get rectified quickly.

**Comment by aalain8** [comment]
If automating the calibration is possible, I agree.

**Comment by Joetrin** [comment]
Please don't forget that some radios use LiOn with lower thresholds than Lipo.

**Comment by EngelMT** [comment]
@Joetrin That it is the reason why I think it will be good to offer option Das ist der Grund warum ich die Optionen von verschiedenen Akkutypen oben ins Spiel gebracht habe. Das macht es für die Programmierer zwar komplexer, aber wenn es gut gemacht ist, ist das ein deutlicher Pluspunkt für Frsky und ETHOS.

**Comment by Hobby4life** [comment]
Well the new thresholds have been changed since v1.0.10. I think that is enough.
I dont know if thresholds from older firmwares have been automaticly updated with the new ones after firmware update? I gues not.
And there could be the culprit. 
For this these new values should be forced with a update one time only for safety reasons.

Besides this, X10/X12 (Li-ion) do need other thresholds then a X20 (LiPo)
I think I now have seen the same values for all radio types. that is not correct also.

If the user decides to use other batteries instead, they should change it themselves.

**Comment by Joetrin** [comment]
@EngelMT I completely agree with your original comment.  I have a question, at this point I can only guess what the minimum voltage is for the X20 when it shuts of.  Does anyone know the definitive voltage where the X20 actually shuts down?  Is it 6V, 6.5, 7.0?

**Comment by STC148** [comment]
In my opinion, the transmitter should not switch off to save the battery, at least not as long as it is connected to the receiver. Better a broken battery than a crashed model.

**Comment by timmybeetle** [comment]
EngelMT say
1.automate battery calibration
How is this done?
For me it would be a good thing that I can calibrate this myself, like with my old X9D.
Never had in issue there with battery going low ore XMTR shutting down.

As mentioned (STC148) a LIPO is cheaper than a RC airplane, so keep the XMTR on and we can land the plane safe.

Grts Hans

ps my XMTR is set to 7.7Volts

**Comment by Hobby4life** [comment]
The problem is not the battery, it is the LCD that has a minimum operating voltage.
It is clearly seen that the LCD starts to struggle when the minimum voltage is approaching.
At that point it is like ripping off the LCD display from the data bus.
the CPU goes wacky, and bam emergency mode.

From software perspective I dont know if it is possible to let software shut down LCD only. and keep the transmitter "alive"
I can also understand that people will not accept a Display shutting off at all, even in safety perspective.

**Comment by Joetrin** [comment]
@bsongis-frsky is it possible to have the software turn off the screen when low voltage threashold is met (6.0V) but keep the radio working, and provide an audio warning that tells the user "TX Battery Critical", or if it is connected to the RX?

**Comment by Hobby4life** [comment]
Guys really think about this.. Are you really draining your radios that far???, I am seriously not.
I fly 2 days a week in a row, make about 40 flights... and my radio is still on 7.7-7.8v.
Are you all the way in the outback, unable to recharge?

Do you also drive your car that empty every time? Hoping the engine still keeps running?
Do you really use all your pills to 0, with critical medicines?

This whole story is no longer about real life facts. It is now based on fear that something "could" happen.
But in **normal** use this is not an issue in reality at all.

You can build a million protections in stuff, but at the end, the user is responsible for ignoring just simple warnings that are there already?

With the already built in alarms, proper setup. There is no problem at all.

The only thing that is coming back as an issue.. is inproper information about changes in releases.
A better detailed description would be more than apreciated with every fix or feature addon.

**Comment by Piperkre** [comment]
Hallo
Es gab eben keinerlei Warnungen, bei einen Schwellenwert von 6,6 Volt!!!!

**Comment by pld74** [comment]
Personally I charge the night before flying for peace of mind but unfortunately some do not. 

People have lost models due to TX battery low. All some of us are recommending is to increase the margin of safety for the chemistry of battery that is installed. In the case of the factory installed LiPo a small increase from default 7V to a new default of 7.4V. If they ignore the 7.4V warning clearly they are not listening to the radio and taking their chances. 

Some have mentioned online that at 7V there is not enough battery capacity left to land the plane and lost lost radio control shortly after the low battery warning due to radio shutdown. 

By the way does the low RX battery warning repeat every 30s or is it a One Time Warning? It should be a repeat warning. Just to clarify here.

**Comment by pld74** [comment]
> Hallo
> Es gab eben keinerlei Warnungen, bei einen Wert von 6,6 Volt!!!!

Translation: 

Hello
 There were no warnings at all at a value of 6.6 volts !!

**Comment by Hobby4life** [comment]
> Personally I charge the night before flying for peace of mind but unfortunately some do not.
> 
> People have lost models due to TX battery low. All some of us are recommending is to increase the margin of safety for the chemistry of battery that is installed. In the case of the factory installed LiPo a small increase from default 7V to a new default of 7.4V. If they ignore the 7.4V warning clearly they are not listening to the radio and taking their chances.
> 
> Some have mentioned online that at 7V there is not enough battery capacity left to land the plane and lost lost radio control shortly after the low battery warning due to radio shutdown.
> 
> By the way does the low RX battery warning repeat every 30s or is it a One Time Warning? It should be a repeat warning. Just to clarify here.

Good point, the battery warning never should dissapear from screen when triggerd.
And a audibly sound every 5 - 10 seconds would be enough.
And 7.4v is a excellent safe threshold.

**Comment by Joetrin** [comment]
7.4 if not changeable is too high for LiOn, 7V on LiOn is about 30% or more battery life.  Knowing the chemistry and being able to select it is ideal.

https://images.app.goo.gl/MdwY3cYVhWDpcoDY6

**Comment by pld74** [comment]
I agree with Joe. There should be a prompt, “Battery Type” and that has built in Defaults depending on the selection.

**Comment by pld74** [comment]
FYI - Some Radios did not come with any batteries and because of personal preference some prefer not using LiPo and so install LiON or NiMH. Therefore, Ethos should have coverage for LiPO, LiON and NiMH.

**Comment by Hobby4life** [comment]
That makes no sence because the charger inside the x20 os designed for lipo only.

**Comment by EngelMT** [comment]
@pld74 That it is what I wrote in the top.

We can discuss at length why a transmitter is not charged before flying. But as I wrote at the beginning, there is a new generation of model pilots who don't do that and rely on the technology. We can now say that we are not interested in all this and leave everything as it is. Then posts come up in the networks complaining about FrSky and the transmitter. That doesn't help FrSky. But a fairly reliable voltage monitoring system with predefined values etc. does help.

Example. My Mercedes Sprinter has a fuel gauge and a reserve indicator. Shortly before the tank is real empty, the engine goes into emergency mode. I can then still drive a few kilometres. But only at max. 60 km/h. Mercedes could also say "it's your own fault if you don't refuel". But Mercedes thinks differently and builds in an additional warning threshold.

Therefore, once again the request to the programmers.

1) If the hardware allows it, please enable automatic calibration.
2. ask for a selection of battery types.
3. specify a lowest warning threshold for the possible battery types that the customer cannot and must not fall below and that enables safe operation for at least 15 minutes after the last warning.

**Comment by Hobby4life** [comment]
Number 2 is not possible. (if you want to charge too)

It is a fixed **Lipo** Charger built in.
To avoid confusion, nothing should be able to be modified here at all, because you can't use the full functionality.

**Comment by jreis1** [comment]
Nice example @EngelMT  !

at least we all agree something must be done with some urgency :)
lets give time to the devs to think about it

**Comment by EngelMT** [comment]
My comments are only ideas as a reaction to what I read in forums and Facebook worldwide. FrSky or Bertrand must know what hardware is to be implemented technically and what software is to be implemented technically. It is only an advice from me to do something.

I myself don't need it because I never fly my transmitter and receiver batteries so empty.

**Comment by EngelMT** [comment]
For your info. Yesterday I make the update to 1.0.11. I think that 7.0V is now specified there as the warning threshold. But that is probably still too low. I then programmed a new model and got the warning at 7.0V. So far so good. 

Since I didn't expect the X20S to switch off quite quickly after that, I didn't have a look on a timer. But I felt that it would not have been enough to fetch and land a large or fast model or a glider from a greater distance to the airfield.

I strongly recommend that FrSky do trials to see how long the transmitter will remain operational after the warning threshold has been reached. I would do this with the 2.4 GHz and 900 MHz RF module switched on to generate the maximum possible power consumption.

Attached a typical discharge curve of a LiPo battery. You can see that at the latest at 3.8V per cell the voltage curve becomes almost vertical. This means that the time left to land becomes extremely short.

I assume that we have to set a threshold at 7.4V to make sure we still have enough time to land. Of course, this all depends on the condition of the battery. Older batteries will break down a little earlier than new batteries.

![image](https://user-images.githubusercontent.com/16795828/133562550-33821bec-1d8e-42be-bc49-0235d7f4a292.png)

**Comment by EngelMT** [comment]
What more should we write about this. Either Frsky decides to include the warning or it can be closed. I have written "calibrated ?" after the radio battery voltage in the German menu. This is a small hint for the customers that something has to be done there. Of course, it would be better if this warning came as described above.

**Comment by bsongis-frsky** [comment]
The threshold on X20 radio is 7.2V
It should be enough to avoid any crash, even if the battery is NOT calibrated, the calibration offset should not be that big!

**Comment by EngelMT** [comment]
You are right. Since the default setting is 7.2V, we have had less feedback about dangerous situations due to an empty radio battery. There are still such reports, but significantly less.
