### ISSUE TITLE
Wizzard with the possibility to set SXR receiver

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#924]
I remember that this issue was discussed here or in an other GitHub group before.

Customers and sometimes ourselves are overwhelmed with getting an SXR receiver set up properly when a model has previously been set up via the Wizzard. If you delete all mixers and create new ones via free mixers with the outputs required by the SXR, then everything works. Or after you changed the outputs like required by SXR.

My suggestion is a query at the beginning of the Wizzard. SXR yes or no? If yes, then ETHOS provides the correct channel assignment for the SXR receiver. And ETHOS should then also prevent the customer from selecting V-Tail in ETHOS. Because, as I had to learn, the V-tail is processed in the receiver and if you already select V-tail in ETHOS, then there are problems.

**Comment by aalain8** [comment]
I agree.
The possibility to choose SXR at the end of the creation wizard is a good option.
This would create the output 9/10/12 and (possibly 11) .

**Comment by EngelMT** [comment]
@aalain8 If on the end or to the beginning I do not know. That`s the progammer must decide.

And I would like to go even further. Not only should the standard mixers be created to operate the gyro, but the channel assignments should also be as required by the gyro receivers. In addition, it should not be possible to select a V-tail, as this is done internally in the receiver. If you select V-tail in the Wizzard and then SXR menu again, there will be chaos in the programming.

**Comment by Hobby4life** [comment]
> @aalain8 If on the end or to the beginning I do not know. That`s the progammer must decide.
> 
> And I would like to go even further. Not only should the standard mixers be created to operate the gyro, but the channel assignments should also be as required by the gyro receivers. In addition, it should not be possible to select a V-tail, as this is done internally in the receiver. If you select V-tail in the Wizzard and then SXR menu again, there will be chaos in the programming.

I agree, You should be asked if you are using a stabilzed Frsky Receiver when using the wizard.

**Comment by aalain8** [comment]
**@EngelMT**
>  If you select V-tail in the Wizzard and then SXR menu again, there will be chaos in the programming.

You are right, a person in my club had an unsolvable problem with his v-tail motorglider.
I have redone everything and it works fine.
After carefully rereading your message I realise that this must be the problem.
This has to be corrected.

**Comment by dap35** [comment]
I agree, implementing this configuration option in the new model wizard would prevent a lot of frustration and also create a consistent process for creating a new model.   The wizard should use the actual design of the model (std wing/tail, delta wing (ie elevons) with or without rudders, ailerons with v-tail, etc).    This should set the correct stabilzation options on the RX along with the proper mixes and servo channel assignments on the TX.

**Comment by mawzthefinn** [comment]
This is needed, and while it is the original request, the discussion in #1447 lays out the requirements and is now a milestone. Suggest closing in favour of #1447

**Comment by mawzthefinn** [comment]
This is definitely still on the wish list, but closing off in favour of #1447 as that is better defined and is a listed milestone

**Comment by EngelMT** [comment]
You can close here for all I care. I just hope that the problem will be solved soon. It would be a very big comfort gain.
