### ISSUE TITLE
Wrong format in the log from the GPS

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#926]
In version 1.0.11 RC4 the GPS data layout has been changed. Unfortunately, this does not allow you to view the flight track in Companion using Google Earth.
Companion requires the coordinates to be grouped in one column and separated by a space. The name of the column must be "GPS".
Wrong (in ETHOS):
![Companion und GPS](https://user-images.githubusercontent.com/90325526/132527839-246fe6f9-ba8a-4cc5-af3d-301c90329d30.png)
Correct (in OpenTX):
![GPS-Format richtig](https://user-images.githubusercontent.com/90325526/132528434-5684e31b-0d43-4d9b-8c00-0be0e51605a6.png)
I ask for a change, because the flight track cannot be displayed in DataExplorer either.
Thank you
 Translated from German into English with the help of Deepl

**Comment by bsongis-frsky** [comment]
I don't think OpenTX is the reference here.
2 columns should be used

**Comment by Wolepo** [comment]
How should I then depict the flight track? There is no other possibility at the moment.

**Comment by MIKE-DAILEY** [comment]
Much better to keep the data in sperate columns so it is easer for anyone to manipulate it for their own requirements.  Look up how to use Excel cell merging features.  Very easy to do.

**Comment by Wolepo** [comment]
If it was possible by using Ethos tools to view google earth tracks directly from the logs I would be with you,
but I don't see that happening in the short term.
Forcing the user to perform a workflow, a manual excel conversion, counteracts the ethos paradigm of ease of use and only adds fuel to the fire for the competitors (-;
regards

**Comment by Target0815** [comment]
It is mainly about two things: firstly the evaluation of the logs, here Companion offers itself, because for Ethos no similarly simple possibility exists and secondly the display of a flight path in Google Earth. Google Earth can probably be taken as standard, it would be unwise to ignore the required syntax ...
