### ISSUE TITLE
Slow up no working properly for free mix.

### ISSUE THREAD

**Issue by johnjoeallen** [FrSkyRC/ETHOS-Feedback-Community#928]
I'm using a free mix for my flaps with source as MAX, and weight set appropriately. The slow down works fine but when I add slow up the aileron goes full down before moving to the correct position.

**Comment by bsongis-frsky** [comment]
Already fixed for 1.0.11

**Comment by johnjoeallen** [comment]
@bsongis-frsky I've updated to 1.0.11-RC4, the issue is still there for me.

I've attached a zip of the model, and a video of the issue.

https://user-images.githubusercontent.com/929623/132830692-b551524a-0fb8-4d44-9b17-31f995a6f2c1.MOV

[model01.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7142682/model01.zip)

**Comment by johnjoeallen** [comment]
> @bsongis-frsky I've updated to 1.0.11-RC4, the issue is still there for me.
> 
> I've attached a zip of the model, and a video of the issue.
> 
>  IMG_2785.MOV 
> [model01.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7142682/model01.zip)

@bsongis-frsky Have you been able to verify/validate this issue with 1.0.11-RC4?
