### ISSUE TITLE
Throttle based timers won't count... but will count.

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#929]
I just upgraded an X20 that was running v1.0.9 to v1.0.11 RC4.  I noticed that for one of the models on the radio the timers would not count up or down anymore.  I changed the timers to different conditions (non-throttle based) and they would count.

I tried cloning the model, deleting the throttle mix and adding a new throttle mix, creating a new timer with throttle absolute, etc.  Nothing I could think of that was obvious would get the timers to count again.  So I started poking around in random places and went into the Checklist menu (Preflight Checks).  I noticed that this model had the throttle check function disabled, so on a whim I enabled it with a <95% check.  When I went back to the home screen the throttle timers had started counting again! 
 Bizarre!

I set the throttle check function back to "No Check" and the timers stopped counting again.  After playing around with the different throttle check conditions, it seems that the throttle timers start on !(throttle check).  I assume this was done on purpose, and that's okay I suppose, but how is anyone supposed to know that disabling the startup throttle check will kill all of the throttle timers?  What if I don't want a startup warning but I still want the throttle based timers to work?  Hmm.  Perhaps if the check is disabled then just start throttle based timers when throttle >5% by default?

**Comment by commsart** [comment]
Good one, thanks for chasing it! Same problem here.

**Comment by bsongis-frsky** [comment]
Issue fixed in 1.1.0
