### ISSUE TITLE
[Enhancement] fade-in and fade-out time when switching flight phases

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#93]
Could you please make it possible to give flightphases a fade-in and fade-out time?

If I enter the flight phase "butterfly" I want that it switches over a time of e.g. 2s.

**Comment by hrenz** [comment]
was my question 10 day ago too
Slow movement for flightmodes are missing but importand
Fade in /out
Delay in/out

**Comment by Peschi90** [comment]
yea thats an inportant function. My sailplanes react quite aggressive in some situations when i change the Flightmodes. would nice to get this in one of the next versions

**Comment by Hobby4life** [comment]
Correct, I am really missing this in Ethos,

I am using flightmodes switching between heli throttle and pitch curves.. now it reacts to aggressive. like to have a smooth transition.

**Comment by hrenz** [comment]
"Fade in to a higher flightmode" slow change to a higher priority FP
"Fade out to a lower flightmode" slow change to a lower priority FP

**Comment by Helischorsch** [comment]
Is there a time horizon when this feature, which I think is essential for a heli pilot, will be implemented?

**Comment by seilfly** [comment]
![Flight Mode su_sd](https://user-images.githubusercontent.com/12104820/132814276-53f4d104-0412-4857-84b3-c2b761b70604.gif)
Something like this should be able to be made !

**Comment by theoml** [comment]
Yessss, something like this.

PLEASE!

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/133383420-1c2b20ae-0907-4e08-abed-d1c408c3b597.png)

**Comment by seilfly** [comment]
This is not in 10.0.11          ?           Do you post it in 10.0.12 rc1         ?

**Comment by theoml** [comment]
Well, last night I´ve updated to 10.0.11 Release. There I don´t find what you show.
Where do I get 10.0.12 rc1 ? This I don´t find at the downloadpage.
( https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases )

**Comment by Hobby4life** [comment]
It is not released yet.

**Comment by hrenz** [comment]
<html><body>


Fade In  Fade Out  
What exactly do these 2 times mean now exactly   
Example:  
You are in flight mode 5 and want to go into higher flight mode 6. with 4sec slow transition, 
then set Fade In 4s (Fade into a higher FP with 4s transition)  

or:  
You are in flightmode 5 and want to go out lower flightmode 3 with 4sec slow transition, 
then set Fade Out 4s (Fade out to a lower FP with 4s transition)  

Is this exactly how it is done?   
Fade In x sec:        Transition time to Fade In to a higher Flightmode   
Fade Out x sec:  Transition time to Fade Out to a lower Flightmode  Only that would be a real Fade In / Fade Out funktion


------------------------

one more example: 
we are currently in flightmode5 and have entered this times 
Fade In 4s 
Fade Out 4s  

This must have the following effect wen we aktivate  an other flightmode  
Flightmode3 <---- [Out to lower 4s<--Flightmode5-->4s In to higher] ----> Flightmode6  

Is this exactly how it is done? 
All other solutions would be incorrect

**Comment by seilfly** [comment]
> Fade In Fade Out transition
> 
> What exactly do these 2 times mean now exactly
> 
> Example:
> You are in flight mode 5 and want to go into higher flight mode 6. with 4sec slow transition,
> then set Fade In 4s (Fade In to a higher FP with 4s transition)
> 
> or:
> You are in flightmode 5 and want to go out to a lower flightmode 3 with 4sec slow transition,
> then set Fade Out 4s (Fade Out to a lower FP with 4s transition)
> 
> Is this exactly how it is done?
> Fade In x sec: Transition time to Fade In to a higher Flightmode
> Fade Out x sec: Transition time to Fade Out to a lower Flightmode
> 
> one more example:
> we are currently in flightmode5 and have entered this times
> Fade In 4s (......Up to higher FM)
> Fade Out 4s (......Down to lower FM)
> 
> This must have the following effect wen we aktivate an other flightmode
> Flightmode3 <---- [Out to lower 4s<--Flightmode5-->4s In to higher] ----> Flightmode6
> 
> ## Is this exactly how it is done?
>  
> The other view assumes that the activation of the new flight phase
> settng Fade In Time x sec, lasts until this new FP is stable.
> 
> and the deactivation of this flight phase setting
> Fade Out Time y sec lasts, until this new FP is stable.

_What do you really mean by all that you have written here ?
I can not quite see the point in that !_

**Comment by bsongis-frsky** [comment]
@hrenz please have a look to the OpenTX manual. I implemented myself the flight modes transition in OpenTX and I did something very similar in Ethos

**Comment by hrenz** [comment]
ok is this Fade In, Fade Out correct?

![grafik](https://user-images.githubusercontent.com/6217896/133666789-15091221-1ba2-4ffe-a125-54f187b0321f.png)

**Comment by seilfly** [comment]
The way I want to use this is that I set "fade in" about 0.3 on all flight modes to get a smooth transition instead of a "hectic" movement on the servos !

> ok is this Fade In, Fade Out correct?
> 
> ![grafik](https://user-images.githubusercontent.com/6217896/133666789-15091221-1ba2-4ffe-a125-54f187b0321f.png)

I do not quite understand your thoughts on this other one if you use both fade in and out it will add both fads
The way I want to use this is that I set "fade in" about 0.3 on all flight modes to get a smooth transition instead of a "hectic" movement on the servos!

**Comment by bsongis-frsky** [comment]
@hrenz FM6 => FM5 : max(5s, 4s) = 4 seconds

@seilfly you just set FadeIn = 0.3s in all your flight modes, your scenario is simple :)

**Comment by seilfly** [comment]
> @hrenz FM6 => FM5 : max(5s, 4s) = 4 seconds
> 
> @seilfly you just set FadeIn = 0.3s in all your flight modes, your scenario is simple :)

Bsongis, Yes simple but effective. 0.3 is approx. Thanks !

**Comment by hrenz** [comment]
Fade In Fade out

We have now at V1.0.12 a slow function für FM , but not delay function for FM

FM delay before starts FM slow to an other FM

**Comment by seilfly** [comment]
> Fade In Fade out
> 
> We have now at V1.0.12 a slow function für FM , but not delay function for FM
> 
> FM delay before starts FM slow to an other FM

Looking forward to !
when will it come?
