### ISSUE TITLE
Issue on flex mode under EU mode

### ISSUE THREAD

**Issue by FBarrao** [FrSkyRC/ETHOS-Feedback-Community#930]
Using 1.0.11 RC4 EU firmware into a EU radio the info menu says Internal module firmware 2.1.9 EU   ( as it should).

Using 1.0.11 RC4  Flex firmware on EU radio, in the info menue says Internal model firmware 2.1.9 FCC  ( not EU mode)

So, my question, is my system working on FCC mode  ( no LBT system)  instead of EU mode when I upload the flex firmware? Actually I only know one TD module firmware for the module, and one flex firmware for ethos. 

 I´m concerned about been transmiting on FCC mode under flex firmware, because I have no chance to tell the system that it´s a EU radio.. How the flex firmware knows that the radio is EU? Maybe when I select 868 Mhz in the 900 mhz module, but, what if the 900 Mhz module is off?  How the firmware knows that it´s a EU radio, to transmit the 2,4 signal on LBT mode?
![IMG_20210907_212846](https://user-images.githubusercontent.com/88581380/132645964-d569c091-56d1-4500-8c74-62da716d4563.jpg)
![IMG_20210907_212432](https://user-images.githubusercontent.com/88581380/132646000-2e70ecec-b6f9-411c-bf63-ace7b50dfd90.jpg)

**Comment by Adelaxie** [comment]
FCC is shown there wrong(the second pic, need to fix). 
The mode will be LBT when 868 is selected and FCC when 915 is selected.
No matter the 900M mode ON or OFF.
The options (915 or 868) are there.
