### ISSUE TITLE
Feature request Disable all checks

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#932]
I only want a switch or two to be checked, and since this radio has a plethora of switches, disabling them all takes a bit. I think the addition of a button on this page to set all items to "no check" would be very nice.

![image](https://user-images.githubusercontent.com/5494702/132703107-96a39e4c-b077-46f6-8464-de5fbd57004b.png)

**Comment by Hobby4life** [comment]
Serious? " disabling them all takes a bit."

This is a one time only performance.

**Comment by guycnicholas** [comment]
I could make your argument about the other two buttons, "load all pots positions" and "load all switches positions", if those are there, why not a "disable all" button?

**Comment by mawzthefinn** [comment]
Disable All would be consistent with the other two buttons
