### ISSUE TITLE
emergency mode with lipo widget.

### ISSUE THREAD

**Issue by skyfly74** [FrSkyRC/ETHOS-Feedback-Community#936]
X20 1.0.11 RC4 lipo sensor flvss
I was editing a model after changing the receiver, switch sr8 to grx 8 both.

At the begening nothing happen, I finally make a reboot of all telemetry sensor and then problems begins, go on emergency mode many times. I finally understand when it occurs and can reproduce:
When i arrive at the page with lipo widget it goes on emergency mode. At the opening of the model everithing goes normally and when i slide tp the page with lipo widget it crash. Thats happen only when the receviver is connected.

The problems disapear when i have deleted the lipo widget and editing again... now it work correctly.

Request: it may be very usefull to inform users of tandem X20 of what it is emergency mode! please explain what it is in the manuel or may be or here... Hoppfully i was on the ground and i have all the controls of the plane but it is really scary and not a situation to be confident with a new radio, If it is a protection for avoiding real fail it will be good to know it ;)

**Comment by bsongis-frsky** [comment]
Good catch!
