### ISSUE TITLE
[Model Wizard] Extended list for predefined channel order

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#94]
Right now it is possible to set the channel order for the four main controls:

- 1 => Motor
- 2 => Aileron
- 3 => Elevator
- 4 => Rudder

But since we are able to set the amount of channels per function (e.g. Aileron, Flaps...) it would be great if we could set more default channels in Ethos. For example:

- 1 => Motor
- 2 => Aileron left
- 3 => Elevator
- 4 => Rudder
- 5 => Aileron right
- 6 => Flap left
- 7 => Flap right

That way I would't have to change it on every model when programming a new one. At the moment I don't know how Ethos determines which channel goes where.
For example I changed the settings on a glider to two ailerons and the result was that I got, which differs from the desired list above:

- 1 => Motor
- 2 => Aileron 1
- 3 => Aileron 2
- 4 => Elevator
- 5 => Rudder

In that scenario I had to rearrange nearly all of the assigned channels to get to the default channel order I am using in all of my models.

If we could get the possibility to not just predefine the first four channels/controls that would be great.
If I have to change the arrangement there is not much benefit of the model wizard. And just going with the order that ETHOS defines would result in a different order for nearly every model (depending on how many servos/controls the model has).
It is also much safer to use the same order in every plane.

**Comment by bsongis-frsky** [comment]
Today it will group functions
AETR with 4 Elevators will give you AEEEETR

**Comment by hrenz** [comment]
and what about the fix hardware channel order at a S8R S6R
with AETRAXXX
