### ISSUE TITLE
Lowest lipo voltage is not stored

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#940]
X20S V1.0.11 RC5  LBT EU
Lowest lipo voltage is not saved

Lipo lowest, show me only the lowest current lipo voltage from 1-x cells.
But it does not store the lowest lipo voltage

But when you turn on a motor, the lipo voltage drops and that is the lowest lipo voltage under load, 
this voltage must be stored and displayed and monitored.
So you can prevent that a Lipo battery is deep discharged.

**Comment by Hobby4life** [comment]
It just has to be said again.

If you post an issue.

**ALWAYS** provide:

1. Radio Type (X20(s), X10(s) ISRM, X10(s) Express, X12S
2. Firmware version
3. FCC, EU, IL

There are so many different firmware versions.
And there are 4 types of radios, and functions may work differently in newer and older versions firmware/radio.

**Comment by hrenz** [comment]
X20S with latest V1.2.6

GR8 Vario, GPS,  Lipo with  4cells

Reset Telemetrie all, or Reset  Lipo with log switch works  well
But lowest min Lipo Cell Value ist not stored,  its allways 0,0V
lowest cell is ok

think it read the Value from Cell5 or Cell 6  with 0,0V ans stores it

or after Reset, die lipo values are a lite late and so it reads 0,0V


![screenshot-2022-05-18-17808](https://user-images.githubusercontent.com/6217896/169289544-95b50893-ea72-465d-af92-9fa687154101.jpg)
![screenshot-2022-05-18-59978](https://user-images.githubusercontent.com/6217896/169289547-46452815-1190-4d36-879b-777cfff3b454.jpg)
![screenshot-2022-05-18-60082](https://user-images.githubusercontent.com/6217896/169289549-b1b2c21b-3144-4ff2-956b-3618fa5a3242.jpg)
![screenshot-2022-05-18-60271](https://user-images.githubusercontent.com/6217896/169289551-4144a0dd-94cc-4bf6-8ede-f0289b85c507.jpg)
![screenshot-2022-05-18-60509](https://user-images.githubusercontent.com/6217896/169289553-c6838028-f0f8-4258-a822-e841a0fcb6b5.jpg)
