### ISSUE TITLE
Selecting and displaying homescreens via buttons

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#941]
X20S V1.0.11 RC5  LBT EU
Selecting and displaying homescreens via button

I have created 6 or 7 homescreens.
In flight I have no hand free to display them by swiping on the touchscreen.

But with a button could be the homesreens
forwards or backwards selected
For this you need  one /two special function

**Comment by Hobby4life** [comment]
You use the page button for that..
Short press forward
Long press Backwards

**Comment by hrenz** [comment]
thanks 
ok tested works fine 
but was no documentaion
can be closed
