### ISSUE TITLE
Feature request: adjustable time threshold for RSSI alarms

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#942]
I fly carbon gliders and get a lot of warnings when flying at a distance and when the (carbon)wing drops a shadow on the antenna's. 
I know I can do this myself trough the logic functions but doing something twice is stupid as it can be done right in the first place.

question: Possibillity to put a (X) second threshold on the RSSI low  and/or critical warning.

**how I see it.**
Give the user a choise to setup a threshold time the RSSI value is below RSSI LOW threshold. 
threshold= 3 seconds RSSI has to stay under 38 db for 3 seconds before RSSI low sounds.

**Comment by xvsop** [comment]
Second that! These alarms caused by a very short temp drop are really annoying. RSSI is back on 80+ before you are able to look down on the transmitter screen and there is no loss of control.

**Comment by bsongis-frsky** [comment]
RSSI alarms have been delayed a little bit in 1.1.0, please try it and reopen the issue if really needed, but it should be good from our tests now
