### ISSUE TITLE
Increase size of "Set current model" option in Model Select screen touch interface

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#945]
When using the touch interface to select a model in the Model Select screen the "Set current model" option is the same size as the "Clone" and "Delete model" options below it.  I sometimes accidentally select "Clone" instead of "Set current model" while trying to quickly change models, and this is annoying.

Could the size of the "Set current model" option be made larger than it is now?  At least twice the height it is currently.  This option is used much more often than the "Clone" and "Delete model" options, so in my opinion it should be easier to select.

**Comment by STC148** [comment]
You can select a model by pressing and holding on the item.

**Comment by centertrim** [comment]
> You can select a model by pressing and holding on the item.

I'm not going to lie, you've changed my life with this.  Thanks!
