### ISSUE TITLE
Security: Locking the touch screen during flight  

### ISSUE THREAD

**Issue by aalain8** [FrSkyRC/ETHOS-Feedback-Community#947]
Wouldn't it be safer to be able to lock the touch screen during flight?
X20 Ethos v1.0.11rc5

**Comment by jreis1** [comment]
nice feature to have. 
Screen scroll should still be possible when locked though.

**Comment by aalain8** [comment]
In fact, I wondered what the touchscreen would do with an insect sitting on it when I'm flying with my head in the air!!!

**Comment by guycnicholas** [comment]
I am wondering what your use case is? Mine is this, the screen goes dim, and I then want to see a value on the display so I touch it to make it light up.  I would like the "wake up" touch to not be registered as a touch, but just used to make the screen active.

**Comment by Hobby4life** [comment]
> I am wondering what your use case is? Mine is this, the screen goes dim, and I then want to see a value on the display so I touch it to make it light up.  I would like the "wake up" touch to not be registered as a touch, but just used to make the screen active.

This is a good one 👍

**Comment by jreis1** [comment]
> I am wondering what your use case is? Mine is this, the screen goes dim, and I then want to see a value on the display so I touch it to make it light up. I would like the "wake up" touch to not be registered as a touch, but just used to make the screen active.

same here!

**Comment by aalain8** [comment]
I think this option would be useful to avoid any problems in flight.

![lock display](https://user-images.githubusercontent.com/64332717/133456475-5aa39969-90e4-48c6-b03c-54f8f5f8340b.PNG)

**Comment by guycnicholas** [comment]
The locking might be a good idea, but I also would like the "wake up touch" thing. My reasoning is that I sometimes want to adjust something in flight, like expo or a gyro rate or ? and for that I would want the screen to be unlocked and I need to be able to see it.
Having both options might be ideal.

**Comment by guycnicholas** [comment]
Funny story...I was just testing things out to make sure I know how to get the screen alive safely and it DOES ignore the "wake up" touch.  I am on 1.0.11...so....nothing to see here ;)

**Comment by mawzthefinn** [comment]
The wake up touch would be nice, but I see no risk currently to not having a screen lock for touch.

You have to do two separate touch actions just to get to any menu that could change things. That's enough of an interlock for most uses, especially since the screen location prevents accidental belly-activation for those of us who are on the larger side.

**Comment by Luznatural** [comment]
I think is far better to have the touch screen lock associatied to the position of a switch.
EdgeTX has this option and is very practical.
In that way, you may even add an special function to play a track that says "touch screen locked" when you move the switch to lock the screen, and another voice saying "touch screen unlocked" when you unlock it.
So, you perfectly are aware of when the touch screen is active or inactive.

**Comment by Luznatural** [comment]
I formally propose for Ethos 1.5.0 to include the touch screen lock associated to the position of a switch on the radio, as described in my comment above.
Thanks in advance

**Comment by Dsrenger** [comment]
I second this.

With the XE and the display near the body, I saw, that I had another screen displayed then before the flight.

Obviously the TX is telling me, that I am to fat :D

But as losing weight is not so easy, until then I would like to lock the screen during flight.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9bdbcc81-cf87-4f3c-b691-a8ec6b056bce)

**Comment by bsongis-frsky** [comment]
@Dsrenger as I am not sure you have lost weight I have implemented it :)

Duplicate of #2958

**Comment by Dsrenger** [comment]
Well, let me say it as it is...I still need to use the feature :D

Thanks Bertrand! Very happy with Ethos :)

**Comment by Luznatural** [comment]
Good job Bertrand!!! Many thanks!!!
