### ISSUE TITLE
X12S Hardware screen 6 pos switch not listed- Enhancment?

### ISSUE THREAD

**Issue by BobCotsford** [FrSkyRC/ETHOS-Feedback-Community#95]
On my X12S if I go into the System-Hardware screen the 6 position switch is not listed.  It shows correctly if I select Hardware Check or Analogues Calibration and it can be selected as a control so this is only affecting the Hardware List as far as I can see.

**Comment by bsongis-frsky** [comment]
Why do you need it there?

**Comment by BobCotsford** [comment]
It's just something I noticed when checking 1.0.2 on an X12S.  I doubt that I will be swapping out the 6-pos myself but it seems inconsistent to omit it from the list.  

Bob Cotsford 

    On Saturday, 17 April 2021, 15:55:46 BST, Bertrand Songis @ FrSky ***@***.***> wrote:  
 
 


Why do you need it there?

**Comment by mawzthefinn** [comment]
The 6-pos is now listed as Pot3 on the System->Hardware screen for the X12S.
