### ISSUE TITLE
RC 005 Problem no Pictures

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#951]
Seems like after update something is missing - at least i do not get any "radio" illustration for the Throttle warning. Buttons on the screen too missing.

Flashed several times all files SD, Flash and reflashed Ethos

**Comment by MIKE-DAILEY** [comment]
Update the bitmaps that are provided with the release.

**Comment by m0p3d** [comment]
Already did

**Comment by MIKE-DAILEY** [comment]
1.0.11. RC5 working OK here.  X20S.

**Comment by m0p3d** [comment]
x20s

**Comment by MIKE-DAILEY** [comment]
The bitmaps go on the Flash drive.

**Comment by m0p3d** [comment]
Know - did it again - like the 3 attemps before now working
