### ISSUE TITLE
Mixer graph moves while adjusting the trim controls

### ISSUE THREAD

**Issue by df7320** [FrSkyRC/ETHOS-Feedback-Community#952]
Release 1.0.11 candidate 5
X10S Express

This issue is related to #723.  It's supposed to be corrected in this latest issue but it is still happening not only to the elevator like issue #723 but now occurs also on ailerons, rudder and throttle.  While adjusting the trim tabs for each of these controls the graph will reflect the change in the trim setting.  This is only a display issue.  The outputs seem to be correct.  I went back to 1.0.9 and this display issue does not happen.  If this is the way it's supposed to work now, then disregard this new issue.  It just looks strange to me. Thanks

![20210913_143620](https://user-images.githubusercontent.com/81670152/133140797-29bf83dd-7059-4771-9e3b-88affce393e3.jpg)
![20210913_143600](https://user-images.githubusercontent.com/81670152/133141067-7dec5c37-adb4-4e05-97c8-de86a9adf281.jpg)

**Comment by aalain8** [comment]
Identical with x20s

**Comment by Hobby4life** [comment]
I gues the graph now shows exactly what happens on the output after mixing in correlation with stick input.
Previous versions did not do this.
So I gues actually this is realistic.

**Comment by bsongis-frsky** [comment]
I have made all mixes behaviour consistent, as discussed in #723

**Comment by df7320** [comment]
I understand that it is now consistent on all four controls but just my opinion,  how it worked in 1.0.9 is typical and how it works in OTX currently. Thanks
