### ISSUE TITLE
In Helicopter mode -Hovering pitch trim and throttle hover trim

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#954]
In helicopter mode, I'd like to know how to assign a potentiometer to do hovering pitch trim and throttle hover trim . So be able to modify near the hovering point in throttle and pitch curve in flight.

If this option is not available, it would be interesting to include it.

**Comment by DJMacGregor** [comment]
Hi - this facility has been added, and I have it working.  I also added overall pitch trim to the front slider.  Note this model file is for a flybarred heli.  Model11.bin file zipped.
[model11.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7160656/model11.zip)

**Comment by jasalca** [comment]
It wouldn't have occurred to me to do so. Very good yes sir!!! Thank you very much.
