### ISSUE TITLE
Tandem X20 Sensor properties

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#955]
In the appendix you will find a list of some sensors. Some items are reported as "missing". Please check the list and add these functions. This list is not complete. You will only find sensors that the customer who created this list had in stock. It is possible that other sensors are also missing things like offset and ratio.

[Tandem X20 Sensor properties.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7162970/Tandem.X20.Sensor.properties.pdf)

**Comment by bsongis-frsky** [comment]
Which is the sensor he uses? People asked for offset / ratio on voltage sensors, but it should not be needed on other sensors.

**Comment by EngelMT** [comment]
He use a Lipo Voltage Sensor 6S from FrSky like he wrote in the list. With the RX Bat Sensor you have the options Ratio and Offset.

**Comment by mawzthefinn** [comment]
ratio is normally necessary to support voltage dividers, and offset mostly exists to address component variations in the ADC and divider setups. 

What would be the use case for these settings on non-Voltage sensors?

**Comment by mawzthefinn** [comment]
Ignore the question in my last comment, issue #1535 addresses the need.

**Comment by Andreas-4711** [comment]
I know it is only possible for voltage sensors at this time. But it would be nice to adapt it for other sensors as well to get more accurate values. In my case, another user and I have measured big differences in RB's with external meters.

**Comment by stealdesk** [comment]
Will here be a possibility to adjust sensors that read slightly off? My ASS-100 reads 12MPH siting still. I want to use it for accurate airspeed. AccZ reads .8g sitting still this needs to be adjusted.

**Comment by Satcomix** [comment]
Hello FrSky Ethos Team,
Is it possible for Ethos to add a new function called SCALE / RATIO function to the telemetry sensor interface (above OFFSET), especially for the DIY sensors?
The background is the transmission of the parameters as integers and not as decimals. 
I can choose between mV/mA ​​and V/A, but the result doesn't change.
A function with Scale/Ratio could divide or multiply the values ​​received in Handheld.
For example: 1/1000, 1/100, 1/10, 1 , 10/1, 100/1 to 1000/1
Greetings to the entire development team.

**Comment by ReadyG** [comment]
Hi please add a temp sensor offset. Thank you!

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/bd7ce625-e9cb-4dab-a497-21ca579677fa)

**Comment by lightbulbjim** [comment]
Does this apply to all sensor types? I noticed that I cannot adjust the RxBatt ratio or offset when using an external ExpressLRS module.

I am in favour of allowing these adjustments on all sensor types, to allow for user calibration.
