### ISSUE TITLE
wrong value onscreen with reversed throttle

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#956]
Radio: x20
software: Release 1.0.11 candidate 5
EU

I use reversed throttle
stick value on screen with source : Chanel 7 (Throttle) 
I get 100% when stick is at the top  and -100 bottom ( should be the other way arrond). I get the same value's when I select "Analogs -Throttle"  ( as absolute position of the stick this is right)

**Comment by bsongis-frsky** [comment]
I just checked everything here, I see no issue, please post screenshots of your Throttle mix settings and your wrong value onscreen so that I can understand what is wrong!

**Comment by 00steven** [comment]
I tought it would display Chanel 7 output value
![20210915_150757](https://user-images.githubusercontent.com/12456410/133440895-d40f8e4c-fb23-4267-a724-00fda83577d5.jpg)
![20210915_150802](https://user-images.githubusercontent.com/12456410/133440900-0cf9a129-e1b9-445f-a9cb-f1f739f8d11f.jpg)
![20210915_150936](https://user-images.githubusercontent.com/12456410/133440909-dded37e9-0edb-416a-9023-bb6a7555e672.jpg)
![20210915_151003](https://user-images.githubusercontent.com/12456410/133440916-9b57c468-857d-4996-9211-ab8abaf5dcbe.jpg)

**Comment by mawzthefinn** [comment]
Just tested this out and confirmed that the value denoted by Channels->ChX is the sum total input of the mixers to tha channel, not the value after Output processing is taken into consideration. 

This is expected behaviour as that output is the one used when the Channel is used as an input to another mixer.

**Comment by mawzthefinn** [comment]
This is corrected by reversing the Throttle in the Mixer rather than in outputs.
