### ISSUE TITLE
Temp Sensor max Temp is too low. 

### ISSUE THREAD

**Issue by Thoemse** [FrSkyRC/ETHOS-Feedback-Community#957]
The temperature range has an upper limit of 250 degrees. I added a V-speak ECU converter to my kingtech turbine to get telemetry via sbus. This works but a turbines operating temperature is way above 250 (idles at 500). Could you adjust the range to up to 999 degrees please? Right now the sensor works but once the turbine starts the sensor stops working at 249 deg C and goes red until you shut down the turbine and it cools below 250 deg C.

**Comment by bsongis-frsky** [comment]
Which release? Max is 1100°C in 1.0.11

**Comment by Thoemse** [comment]
Bertrand i am so sorry. I though I read all the changenotes. I hat 1.0.10. Sorry for wasting your time and thnaks for developing a phantastic OS.
