### ISSUE TITLE
ETHOS 1.0.11 final version Again erratic movement of elevator in flap elev mix

### ISSUE THREAD

**Issue by timmybeetle** [FrSkyRC/ETHOS-Feedback-Community#961]
Updated to ETHOS 1.0.11 final
Testing flap-elevator free mix and using slow up/down.
When using different speed for up/down for half an full flaps I get again erratic movement of elevator.
Using same speed for up/down than it seems to be OK? 
But I must be able to choose whatever speed I like!
![flap mix half 1-2021-09-15-52578](https://user-images.githubusercontent.com/84274019/133435364-de45af00-84f3-4d0d-846a-c3ed997045dd.jpg)
![flap mix half 2-2021-09-15-52578](https://user-images.githubusercontent.com/84274019/133435388-58ee2702-d2e8-4922-9489-d25260e5b335.jpg)
![flap mix full 1-2021-09-15-52578](https://user-images.githubusercontent.com/84274019/133435405-e3fa1c1b-0f5e-40ca-b1c5-d7530d8b42b1.jpg)
![flap mix full 2-2021-09-15-52578](https://user-images.githubusercontent.com/84274019/133435422-ad63a1ae-b17b-425c-a7b4-b65fdd0d29f7.jpg)
https://youtu.be/6-k7sq5fg9o

Regards Hans

ps see also
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/891
not solved completely

**Comment by mawzthefinn** [comment]
The delay in Free mix sets the time it takes to go from -100 to 100. So if going for a reduced amount in one direction, they will behave unpredictably depending on weight. Plus you are mixing the flaps switch to elevators, not the flaps output.

Better to use a Flaps->Elevator canned mix and use a Flaps channel as the source so it tracks your flaps correctly.

**Comment by mawzthefinn** [comment]
Closing off old issue as a solution is provided and no action in 6 weeks
