### ISSUE TITLE
Emergency Mode switching models

### ISSUE THREAD

**Issue by Rustychain1** [FrSkyRC/ETHOS-Feedback-Community#964]
X20S just updated from 1.0.10 pr4 to 1.0.11. 
Every time I switch from model A to model B I get Emergency mode. I can go from A to C to B without problem. I can go from C to A to B without problem. If the radio is powered on with model A it will not go to B. Model A is a heli, model B is a sim profile that uses an RF dongle. I updated the SD card. Removed Amber and any other files on there that I had added with the exception on a receiver firmware and some model images I downloaded. I did change the model image for model B to a default one and no change.

**Comment by Hobby4life** [comment]
Can you upload your models folder in a zip file?

**Comment by Rustychain1** [comment]
[Model.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7171154/Model.zip)
Problem is going from "Raw" to "Sim"

**Comment by bsongis-frsky** [comment]
I cannot reproduce it, would you please join your model bitmaps from your SD?

**Comment by bsongis-frsky** [comment]
Which is the language on your radio? English?

**Comment by Rustychain1** [comment]
Yes, English. Here is a copy of the bitmaps folder on the SD card
[bitmaps.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7192101/bitmaps.zip)

**Comment by bsongis-frsky** [comment]
I just have an idea. If the load of the model is too long, more than 500ms, then your radio will go to Emergency Mode. If you have a very slow or bad SD, it will happen!

**Comment by Hobby4life** [comment]
Frsky should stop providing these 4gb cards, they are really bad and have caused more problems overtime.
They should provide a good genuine Sandisk SD card. For those few extra bucks you have more happy customers.

**Comment by bsongis-frsky** [comment]
I am simulating a bad sd card to be sure that the problem is there. If it's the case it's not urgent to release 1.0.12, this Emergency won't happen in flight as the Mixer doesn't access the SD

**Comment by bsongis-frsky** [comment]
Reproduced. By simulating a bad SD card (delays added at each byte read), I get an Emergency watchdog reboot.

**Comment by bsongis-frsky** [comment]
Issue fixed. The watchdog is now stopped when opening a model from SD card as it is not a critical operation. Tested with the delays at each byte read. It's very slow, but there is no emergency watchdog reboot.

**Comment by Rustychain1** [comment]
Nice!!
