### ISSUE TITLE
Restore system settings after firmware upgrade

### ISSUE THREAD

**Issue by ahvink** [FrSkyRC/ETHOS-Feedback-Community#965]
I have most of them on default, but it seems the system settings are not retained during a firmware upgrade.

**Comment by NMO81** [comment]
Did you deleted radio.bin?

**Comment by NMO81** [comment]
Always backup it before updating

**Comment by NMO81** [comment]
Ok, your issue #960 is probably the root cause of a corrupt radio.bin on the SD.

**Comment by ahvink** [comment]
Yes, I deleted radio.bin….
Do I leave it next to firmware.bin while updating?

**Comment by MIKE-DAILEY** [comment]
The radio.bin has all the radio system settings.

**Comment by NMO81** [comment]
radio.bin contains all the settings, so indeed never delete it. just add firmware.bin to the SD. But I do recommend to take backups of it since it contains the data for the old firmware version so without this backup you can not go back if you want to keep the settings.

**Comment by ahvink** [comment]
Well, that explains a lot 🤣
