### ISSUE TITLE
Need confirmation before delete

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#966]
In the mix page both Curve and Weight have a delete icon for anything past the first item. This delete button really needs an "are you sure" dialog as they are too easy to delete.

(I thought I had seen this issue mentioned somewhere, but my searching didn't find me anything.)

**Comment by pld74** [comment]
I Agree. Happened to me many times.

Good Enhancement!

**Comment by loetefix** [comment]
Agree.
Also for delete all sensors for telemetry.

**Comment by Hobby4life** [comment]
A system wide,, Delete confirmation for everything

**Comment by pld74** [comment]
A system wide Delete Confirmation is a great idea!

**Comment by bsongis-frsky** [comment]
Confirmation dialogs added
