### ISSUE TITLE
Slow up/down not working properly, does not take the specified time

### ISSUE THREAD

**Issue by johnjoeallen** [FrSkyRC/ETHOS-Feedback-Community#967]
https://user-images.githubusercontent.com/929623/133682852-98059e20-5fba-4234-8a9c-b1201a1da88b.MOV

1.0.11 has fixed the previous issue of the control surface going to extreme when slow up was set on a mix, but now the slow down/up delay is not as specified.

As can be seen in the video the slow down/up of 1.0s is not happening, the "add" mix is happening much faster.

**Comment by Nicholas-Luoyi** [comment]
I cannot see the video very clearly. Would you please share your model file?

**Comment by bsongis-frsky** [comment]
1s = the time needed to go from 0% to 100%
If you only have 10% then you need to adjust the duration
With other words, the speed is constant

**Comment by johnjoeallen** [comment]
Ok I understand, but I could swear it was 1s to apply the "add" to the mix previously.
