### ISSUE TITLE
SxR and/or ACCST D16 Telemetry Problems

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#97]
X20 with ETHOS 1.0.2
S8R with ACCST 2.1.0

Not sure if this is an ACCST D16 protocol problem or specific to the SxR family. Unfortunately the only ACCST receivers I have are S8Rs.

- With no external sensors connected to the S8R, telemetry is streamed noticeably slower than on my X10S Express or TX16S.

- With external sensors connected to the S8R, telemetry is streamed even slower and the external sensors will sometimes drop out with "Sensor Lost" alerts. The data from external sensors is also sometimes nonsensical.

- The SxR Device Config page populates very slowly with no external sensors connected, and even more slowly with external sensors connected. Sometimes it fills in with nonsensical information if you wait long enough. It's essentially unusable for making gyro adjustments.

I replicated this issue with 3 different S8R receivers, all running the latest ACCST 2.1.0 firmware. They do not have any of these issues on my Horus X10S Express with OpenTX or my Radiomaster TX16S.

**Comment by bsongis-frsky** [comment]
Did you try X10S Express with Ethos?

**Comment by bsongis-frsky** [comment]
Your issue has been reproduced and it seems it is rather a SxR firmware issue

**Comment by bsongis-frsky** [comment]
Try with this firmware to confirm the issue is fixed:
[SxR_ACCST_FCC_2.1.1_BETA.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6390617/SxR_ACCST_FCC_2.1.1_BETA.zip)
Thanks!
