### ISSUE TITLE
Timer starts although the motor OFF switch is set.

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#970]
Timers that are started via the throttle stick also start when the engine safety switch is in the OFF position. In my opinion, this does not make sense. Can be only the % Option. Not sure.

**Comment by pld74** [comment]
I think you're asking for a multi-condition timer. From my understanding Timer has a single condition to enable/disable, if you prioritize which condition you want that should solve your issue.

**Comment by timmybeetle** [comment]
Hi

I did a work around see pics
![Timer count down 1](https://user-images.githubusercontent.com/84274019/133895031-3e9bd994-e2c6-4084-95b3-760ddd0a9d4d.jpg)
![Timer count down 2](https://user-images.githubusercontent.com/84274019/133895035-bfe9cf60-916e-441b-8626-247edcb29ab8.jpg)
![Timer count down 3](https://user-images.githubusercontent.com/84274019/133895039-f67b9452-033e-437a-a9a7-209295bdc315.jpg)
![Timer count down 5](https://user-images.githubusercontent.com/84274019/133895042-63964f30-bfb5-40d6-8ffb-1612ea4958af.jpg)
![Timer edit count down 6](https://user-images.githubusercontent.com/84274019/133895049-689e0e0a-20d5-4e09-b068-1062644495bf.jpg)

works for me 

grts Hans
