### ISSUE TITLE
Emergency fase comes after switching models

### ISSUE THREAD

**Issue by krokusvej** [FrSkyRC/ETHOS-Feedback-Community#973]
Hi I am running 1.0.11 C4 and I added a new model starting setting it up. Then I had to look something up in another model and coppied a logical  switch whent back to the new model I was setting up, pasted the switch in. Then I went back to the model to look up somthing else under the special features, but that I could not copy so went to model select and selected the model I was just setting up. Set it active and UPS Emergency mode was written on my screen.  And from now when I tryed selecting this model when setting it active Emergency mode came on the screen.

To get rid of this I had to delete the model set it um new and then turn off the TX turn it on again. And now I could switch between the models no emergency mode came to the screen more. Both models I was working on was made with glider template.

It looks like when makin a new model you will need to switch off  your S20X before doing anything else.

**Comment by Hobby4life** [comment]
RC5 had major fixes concernig Emergency Mode appearances.
You should upgrade to v1.0.11 official release.

**Comment by krokusvej** [comment]
Super I updated to 1.0.11 C5 EU version and I can't make it happen again so I think it's solved

**Comment by Hobby4life** [comment]
If you have update to RC5, then update to the official v1.0.11
