### ISSUE TITLE
Logs are still problematic with V1.011

### ISSUE THREAD

**Issue by PeterBeretta** [FrSkyRC/ETHOS-Feedback-Community#974]
Hi,

I flew two of my models today with my new X20S radio. Both had logs enabled but only one of the models actually captured data. I dont know why the other model did not capture the logs. When I turned the radio on at home after the flying today it suddenly started capturing logs. I made no changes whatsoever. This model was continually giving me "Telemetry Lost" messages. It has an R9mini and XM+ connected to an RB10. The plane has 4 servos in the wing (flaps+ailerons), rudder, elevator and throttle. I did not get these telemetry warnings before upgrading the R9mini to Access/Flex firmware. Unfortunately due to it not recording the logs, I dont have the information on RSSI/VFR.

I am not sure what the best way is to view the log files, currently I use OpenTX Companion on my MacBook.

[xl-wing-2021-09-18-15-40-40.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7190363/xl-wing-2021-09-18-15-40-40.csv)

The attached log file is for a flying wing using throttle and elevons with no additional sensors. It is using an R9Slim that I upgraded to the latest version of Access using the Flex firmware. The TX transmission power was 100mW. I had no telemetry lost warnings or low RSSI warnings and the RSSI levels were good and VFR was good. What I am concerned about however is that when I load the log file into companion to view it, I get a message "The selected log file contains  11137 invalid lines out of 20306 total lines".

**Comment by EmbededFabrication** [comment]
where do you "enable logs" in the menu?  I've got an X20 maybe I don't have this?

**Comment by bsongis-frsky** [comment]
The CSV files can be open with Excel or LibreOffice. Or many other software.

**Comment by PeterBeretta** [comment]
> where do you "enable logs" in the menu? I've got an X20 maybe I don't have this?
In Special Functions:
![IMG_0804](https://user-images.githubusercontent.com/8342107/133962515-274b464e-42da-4e66-b818-e5396188d173.jpeg)

![IMG_0807](https://user-images.githubusercontent.com/8342107/133962539-4a0d24ef-2144-4e30-9040-f3e0f50213c7.jpeg)

**Comment by bsongis-frsky** [comment]
There is a bug when loading a model, the logs don't start automatically if the condition is "Always"
