### ISSUE TITLE
x8r receiver

### ISSUE THREAD

**Issue by Rem11111** [FrSkyRC/ETHOS-Feedback-Community#976]
frsky x8r receiver connect but no movement.

**Comment by timmybeetle** [comment]
Hi

Well this is to less information for help.
Ethos version?
XMTR type?
Frsky XMTR and RCVR protocol version?
Screen shot of issue?

Grts Hans

**Comment by bsongis-frsky** [comment]
Please give more information when opening an issue. I just checked here, no problem with X8R

**Comment by Rem11111** [comment]
![20210920_124911](https://user-images.githubusercontent.com/90983388/133992367-255421ec-7ea7-49cf-b39a-c85a87766f74.jpg)
![20210920_125104](https://user-images.githubusercontent.com/90983388/133992388-3acbd676-fbb9-4ad8-90aa-f1e7f3b4bdf8.jpg)
![20210920_125128](https://user-images.githubusercontent.com/90983388/133992393-a14f186b-2932-4a86-a1a7-fbba779f0f3a.jpg)
![20210920_125049](https://user-images.githubusercontent.com/90983388/133992407-c77000fa-8413-4300-87aa-b955490228a2.jpg)

![20210920_124859](https://user-images.githubusercontent.com/90983388/133992416-dd3b8979-3075-4be2-aaff-5adef05686c0.jpg)

**Comment by Rem11111** [comment]
![20210920_125104](https://user-images.githubusercontent.com/90983388/133992514-0b635d6a-f106-40d1-a6e5-b51bc16f93e0.jpg)

**Comment by bsongis-frsky** [comment]
Which firmware did you flash on your receiver?

**Comment by Hobby4life** [comment]
Try binding with receiver at least 1m away from the radio

**Comment by Rem11111** [comment]
from frsky the v2.1.0

**Comment by Rem11111** [comment]
oke

**Comment by Rem11111** [comment]
Its not working

**Comment by Rem11111** [comment]
my s6r working no problem?

**Comment by Rem11111** [comment]
All my x6r not

**Comment by Rem11111** [comment]
x8r

**Comment by bsongis-frsky** [comment]
And did you do the REGISTER after flashing your X8R? Did it work?

**Comment by timmybeetle** [comment]
Maybe update this FW TD_2.1.5.frsk to,
TD_2.1.9.frsk 

I have X20 also using X8R and I have no issues with it.
Using latest ETHOS and EU LBT  X8R_ACCST_2.1.0_LBT

grts Hans
