### ISSUE TITLE
No F.Port signal from X20 plug

### ISSUE THREAD

**Issue by EmbededFabrication** [FrSkyRC/ETHOS-Feedback-Community#977]
There is no data available from this plug on the back of the Tx ?
I made up a bluetooth UART adapter only to find there is no signal available to relay to a telemetry app
Other FrSky modules/radios have this functionality don't they?

**Comment by mawzthefinn** [comment]
Why not use the internal BT module in Telemetry mode for this. No need for an additional BT dongle on the S.Port connector.

**Comment by EmbededFabrication** [comment]
It works now?
I haven't updated for a year or so

**Comment by mawzthefinn** [comment]
To my knowledge it does, but the official FrSky Freelink app doesn't like it.

I'd suggest testing on a current version.

**Comment by bsongis-frsky** [comment]
We have found a bug in S.Port mirroring over BT. It will be fixed in 1.4.4
