### ISSUE TITLE
Full update instructions in readme

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#978]
When I first tried to update my radio from here I did it wrong, and after posting a bug here, and being asked if I installed the Flash files I did some more searching and found a YouTube video showing how to update.  It would be much more helpful if the readme file here had explicit directions describing all the files inside the update area and how to install them.
I would like to just point my buddy to https://github.com/FrSkyRC/ETHOS-Feedback-Community and not have to explain everything past that.

**Comment by jreis1** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/ETHOS-File-Storage

I believe there's something here already

**Comment by guycnicholas** [comment]
I hadn't gone to the wiki. I would then suggest a link to or a mention of the wiki page on the readme page.

**Comment by MIKE-DAILEY** [comment]
Links added https://github.com/FrSkyRC/ETHOS-Feedback-Community

**Comment by guycnicholas** [comment]
Awesome...thanks!
