### ISSUE TITLE
Timers run even when throttle cut/hold is active

### ISSUE THREAD

**Issue by centertrim** [FrSkyRC/ETHOS-Feedback-Community#98]
Timers should have a "source" selection to set the source for the timer.  As it is now, the Timers do not respect any active throttle cut/throttle hold and will run if the throttle is high.  Allowing selection of an output channel as the Timer source would solve this problem.

My recommendation for possible Timer throttle source selections would be:

1. Raw Throttle "stick"   (this is what it is now)
2. Any channel output   (default source should be the Throttle channel output, but any should be selectable)

Ideally the throttle source could be selected on a per-Timer basis (instead of one setting for every timer).

Additionally, I recommend adding a user setting for the threshold percentage used to activate the Throttle Absolute and Throttle Trigger active conditions.  Once channel sources are implemented, an advanced user could get around this by making a "virtual throttle channel" with a custom mixer, but it seems silly to require someone to jump through hoops just to configure a timer to start the way they want to.

V1.0.2 pre-release

**Comment by KAD370** [comment]
You should use logical switch for that. Like in opentx.

**Comment by centertrim** [comment]
> You should use logical switch for that. Like in opentx.

Your solution doesn't make any sense to me on a few levels:

1)  You cannot stop or start a timer in Ethos with a logical switch.  It is not an available option.

2)  OpenTX does not have throttle cut and throttle hold functions built into the throttle mixer logic.  Since those functions have been included in the throttle mixer in Ethos to make things easier for the users, why would you then force them to build a logical switch anyway to start and stop a timer associated with the throttle output?

3)  OpenTX includes the ability to select the throttle source from any of the output channels, so it is easy in OpenTX to get the timers to respect any mixing done on the throttle channel.  This problem doesn't exist in OpenTX.

4)  Even if you could select a logical switch to start or stop a timer in Ethos (again, you can't), using a logical switch to toggle a timer on and off would do nothing for users that wish to remap the "throttle %" style timer in order to better match the consumption non-linearity of their power system.  For example, in OpenTX I have used Throttle Percentage timers with the throttle source assigned to a "virtual channel" being fed by a custom mixer curve that remapped the throttle channel output on a gasser to better represent the fuel usage across the throttle range.  With the default linear curve it did not match consumption in any way, but with the custom curve on a virtual channel it closely matched consumption no matter how you fly the plane (low & slow 3D vs. XA).

At the bare minimum, the timer throttle source must be selectable from any of the channel outputs.  Ideally this would be selectable on a per-timer basis (enhancement over OpenTX) rather than for all timers with one setting (current OpenTX functionality).

**Comment by KAD370** [comment]
In opentx you use overide function for throttle cut. Simple as that. Just set walue what you want to be when you hit switch and that’s it. It works same way on other transmitters... I had before multiplex radio for more than 17 years and it had that option, but in ethos is not available...

I was at first very impressed with ethos, but after installing it on my x12s, I was big downgade from what I have in opentx. Some things are great in ethos, but there are so many things that don’t work as they should ore are missing.

**Comment by centertrim** [comment]
> In opentx you use overide function for throttle cut. Simple as that. Just set walue what you want to be when you hit switch and that’s it. It works same way on other transmitters... I had before multiplex radio for more than 17 years and it had that option, but in ethos is not available...
> 
> I was at first very impressed with ethos, but after installing it on my x12s, I was big downgade from what I have in opentx. Some things are great in ethos, but there are so many things that don’t work as they should ore are missing.

I used to use an override special function for throttle cut in OpenTX like you describe, but eventually I moved to using a replace Mixer for throttle cut instead because it allows me to see the throttle cut functionality on the same page as the throttle (and other) mixers.  So that aspect of Ethos doesn't bother me, but I understand that people like doing things in different ways.

As you said, there are many things that are currently missing in Ethos that are sort of deal-breakers.  The timer throttle source selection is one of those things.  I am trying to make sure those items get bubbled up and addressed without requesting too many of the "personal preference" type things right now.  But eventually I would like to see the functionality expanded to allow for personal preference as well as long as they don't clutter up the interface and complicate the codebase badly.

**Comment by KAD370** [comment]
I agree with you. There are so many options how some things can be done.
One way is as you described. Overide function can be little tricky, since when you turn it off, motor can run at full throttle or at any position of throttle stick.

**Comment by centertrim** [comment]
That's true.  I actually considered requesting a threshold setting in Ethos for the throttle hold function in the throttle mixer simply because that is how I have my throttle hold setup with logical switches in OpenTX.  If the throttle is not below 10% then it will not let the throttle hold logical switch disengage, and thus the override mixer rule won't drop off.  But I doubted that many people bother with that extra safety step.  It sounds like you might be one of them that does as well.  :)

**Comment by KAD370** [comment]
I fly mostly electric planes, gliders. Will play with your idea. I’m using opentx 4 years now, but past 3,5 years I was more like basic user, but now I’m trying to update all my models with more complex mixes and functions.
I just hope Ethos will be as good or better than opentx.

**Comment by Hartinger** [comment]
Hi,
I have played a lot with motor  safety switches and timer control in OpenTX, so here are a few remarks around the implementation in ETHOS.

It is not true that you cannot control a timer with a logical switch. You can select this option, provided at least one logical switch is available. This enables an advanced user to build any logic he wants by using a free mixer for the throttle channel and a logical switch to control the timer.
Therefore, I would suggest that regarding the predefined throttle timer control options (absolute, trigger, percentage), it would be sufficient if these considered any throttle cut/hold settings in the throttle mixer. This would do the job for most users, I guess.

**Comment by MrD-RC** [comment]
I just came on here to report the same problem, as in the throttle cut is ignored with a throttle based timer. I agree with @centertrim that the timer should not run if throttle cut is active. Comparing to OpenTX here is not really relevant as OpenTX did not have a throttle cut built in to the throttle mixer, which ETHOS does. So we shouldn't need to create logical switches for inbuilt functionality. It's replication that should not be necessary.

The chat about a curve for the fuel use is interesting. It's the same with electric too. The energy use is not linear to the throttle. Higher throttles will pull more Amps compared. For example, a plane could be pulling 5A on 40% throttle, but 30A on 100%. There is definitely a curve happening on all energy sources.

**Comment by centertrim** [comment]
> The chat about a curve for the fuel use is interesting. It's the same with electric too. The energy use is not linear to the throttle. Higher throttles will pull more Amps compared. For example, a plane could be pulling 5A on 40% throttle, but 30A on 100%. There is definitely a curve happening on all energy sources.

Yep, some planes work really well with the linear relationship, and others not at all (with electrics it really depends a lot on the specific prop & motor combo).  It is very useful to be able to remap the linear percentage timer to a different curve by selecting a virtual channel with a custom “throttle” curve as the timer source.

**Comment by IJK-CZ** [comment]
Did you used FrOs, not only OpenTX? In FrOs, the blocking feature was implemented correctly, without needs of additional user defined mixes. If ETOS should replace FrOs, current stage is worse than in FrOs.

**Comment by poge-st** [comment]
True ... if throttle percentage is used as a active condition in the timer , the throttle cut/ throttle hold is ignored. So either take this in consideration or offer an additional "and condition" field for the throttle percentage option

**Comment by IJK-CZ** [comment]
Yes, to get it working, there is required another temporatory source (i.e. CH16) use as Throttle source and all blocation, curves etc apply on it. Predefined throttle blocation has no impact. Input for temporatory CH16 may be anything (Throttle stick, any switch) and you need additional free mix for it. It works, but not very user friendly.

**Comment by poge-st** [comment]
hmmm i still didnt get it totally but thanks - maybe ill try - or better not because it sounds very - "not user friendly and unnecessarily complicated" - i hope/ wait for a future better implementation :) hehehe 
thanks a lot - maybe ill give it a try - just to have it in place - thanks

**Comment by IJK-CZ** [comment]
It is anyoning, but not critical. 
    
1.  Add a free mix before predefined throttle mix, with source Throttle stick and output to CH16.
2. Create a new simple curve 'Motor Block' (line with -100% all) 
3. Assign this curve to switch position using for Throttle blocking. 
![obrazek](https://user-images.githubusercontent.com/44742963/122909546-988d2580-d355-11eb-823e-bdae28626b52.png) 
3. In standard Throttle mix change source to the used temporery channel (CH16 in this example).

**Comment by poge-st** [comment]
either i am doing something wrong or we talk of different things :D

ill try to explain:
1) i have a timer with active condition: Throttle percentage
![image](https://user-images.githubusercontent.com/37658689/122911363-814f3780-d357-11eb-9845-9cb5285133eb.png)

2) as soon as i move my throttle stick up - this timer starts to count down (allthough my throttle output = -100%) because it just takes the throttle stick position as input and not the output ... thats at least what i think
![image](https://user-images.githubusercontent.com/37658689/122911424-9330da80-d357-11eb-98e8-63d16e795a3a.png)

the other timers work correctly with my manual logics and arming mechanism - all fine - but with throttle % i don't get it to work - i tried your approach too :) , but as i said - either i am doing something wrong or we talk of different things :)

![image](https://user-images.githubusercontent.com/37658689/122911854-04708d80-d358-11eb-9d91-94074813b412.png)
![image](https://user-images.githubusercontent.com/37658689/122911873-089cab00-d358-11eb-8d43-5e99ce00c8c8.png)

**Comment by IJK-CZ** [comment]
You have mistake somewhere, but the idea is correct.
Timer controlled by %
![obrazek](https://user-images.githubusercontent.com/44742963/122929373-2cb5b780-d36b-11eb-8c11-4181ffe88139.png)
Two mixes, using throttle (Plyn), CH 10 used here (first free mix) and CH3 (standard). 
![obrazek](https://user-images.githubusercontent.com/44742963/122929573-67b7eb00-d36b-11eb-8764-5b02f2498942.png)
First (free mix), always active source Throttle stick, Thr blocation by curve 'Blokace' conditioned SF switch UP. Output CH10 here.
![obrazek](https://user-images.githubusercontent.com/44742963/122929876-b82f4880-d36b-11eb-858d-91e038139b04.png)
Original Throttle (Plyn) mix input CH10 (output from first channel), output CH3 (standard Thr channel).
![obrazek](https://user-images.githubusercontent.com/44742963/122930848-9e423580-d36c-11eb-8fef-20810df1f2ba.png)
As CH10 is defined as standard THR mixer source, the timer is really controlled by CH10. It means, timer is stopped, when SF is up, and running when SF is down and Thr stick moved. Speed of timer is based on Thr stick position as expected. 
![obrazek](https://user-images.githubusercontent.com/44742963/122931005-c7fb5c80-d36c-11eb-95c3-35558bcd109b.png)

**Comment by poge-st** [comment]
now it works - thanks 
niiiiceee , thanks for the nice description

its better but still not 100% what i really want - i have my throttle cut / throttle hold in there - so its kind of that "sticky" behaviour - but if i change the active condition to my logic it should work - ill directly give it a try !

**Comment by poge-st** [comment]
oh no - doesn't work - hmmm

**Comment by IJK-CZ** [comment]
Check channel monitor, both used channels. It must work. The THR% functionality must be stricktly related to values in temp. channel output (CH10 in my screenshots).

**Comment by poge-st** [comment]
now i got it - i put my condition wrong or at least in the wrong place/places
![image](https://user-images.githubusercontent.com/37658689/122937699-7786fd80-d372-11eb-9be7-7bb457e06d3a.png)
![image](https://user-images.githubusercontent.com/37658689/122937768-8372bf80-d372-11eb-9fe3-4334262e1eed.png)

i use CH17 now - because this a a channel which i might not need that soon 
and my active condition works now also perfectly ! YES ! many thanks fopr the hiont and your nice help ! thanks a lot !

**Comment by Droptank** [comment]
This should be a basic function of the OS.  Just because it CAN be done with multiple pages of programming for a seasoned OpenTX user doesn’t mean a new Ethos flyer will get it.  Ethos is meant to be intuitive.

**Comment by pstasek** [comment]
I agree with @Droptank here. The throttle related timer should be running only when the throttle mix is active, I canť think of any reason, why it should follow only the stick. A basic timer can be done with any logical switch, but a proportional timer can only follow the throttle stick at the moment, which usually doesn't make sense.

**Comment by MIKE-DAILEY** [comment]
When the Low Position Trim Feature is used the channel cannot be used for the timer control.

**Comment by centertrim** [comment]
Not being able to map the throttle % timer to a custom channel output selection is a continual annoyance for me with Ethos.  My 3D planes require custom fuel consumption curves in order to estimate remaining fuel/battery for the wide variety of flying I do.  As Mike mentioned, I don’t think it’s possible to use the clever remapping trick above if you’re using independent throttle trims per flight mode with the low position trim feature to get different idles.  Even if it is possible, needlessly complicating the throttle logic on a $$$$ and dangerous plane just seems ridiculous.

I just want to be able to select a virtual channel as the throttle timer source so that I can remap the % timer however I like with a curve applied to that virtual channel.

**Comment by centertrim** [comment]
@bsongis-frsky Can we get a throttle timer channel source selection at some point in the near future?

**Comment by mawzthefinn** [comment]
Timers do now respect Throttle Cut, however the channel source selection option would definitely be a nice improvement

**Comment by mawzthefinn** [comment]
Source selection now added in 1.5.0, closing this off.
