### ISSUE TITLE
slider right change Battery Main Voltage and display bar in Battery symbol

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#981]
It's something odd when the right slider is moved clockwise the main voltage increase and counterclockwise the voltage decrease ???
if I remember correctly then there was already an issue about that but cant find anymore

**Comment by STC148** [comment]
I can confirm this behaviour with the X20 and X10.


https://user-images.githubusercontent.com/85410070/134207898-f24f5370-a05d-4955-8306-2caea6b8589c.mp4

**Comment by loetefix** [comment]
Same here with x20 and last release

**Comment by sylricflo** [comment]
same with X20S   1.0.11 release.   in my case,  lipo not fully charged,   value is moving from 7.4v to 7.5v  and when the right slider  is on a middle position, value is flickering very fast between 7.4 and 7.5

**Comment by bsongis-frsky** [comment]
@STC148 I can confirm it on X20, but not X10 Express. Are you sure?

**Comment by Cipta-de** [comment]
Hello and thanks for the reply,
I have observed on X20S
X10 don't know.


Herzliche Grüße und einen schönen Tag noch wünscht


Roland Schäfer



Mobile:+49 17696614767

Mail:    ***@***.***



schau doch mal auf meiner Webseite nach neuen Fotos www.cipta.de


Bertrand Songis @ FrSky ***@***.***> schrieb am Fr., 24. Sep.
2021, 08:09:

**Comment by bsongis-frsky** [comment]
The issue will be fixed in 1.0.12 when released

**Comment by STC148** [comment]
If it still is relevant, yes, the X10 shows the same behaviour but with both sliders.


https://user-images.githubusercontent.com/85410070/134732571-48a28ba4-8ef9-4535-8f74-59c20a49add8.mp4

**Comment by Franjose1984** [comment]
> I can confirm this behaviour with the X20 and X10.
> 
>  Mein.Film.mp4

I have this problem to
