### ISSUE TITLE
switch  F   not available in switch list,  as a source  in several menus

### ISSUE THREAD

**Issue by sylricflo** [FrSkyRC/ETHOS-Feedback-Community#983]
X20S  release 1.011  (mode 1)

"switch F"  is the 2 positions switch , which is on the left side  
i wanted to use this  "F switch"  to switch on or off  the electric engine on a glider. 

for example : 
CHECKLIST menu
you can't define  any action for this  F switch in the "checklist"  because letter F does not appear in the list of available switch
you only find  switches ABCDE GHIJ

SPECIAL FUNCTION menu
Condition  field :  SF  is not listed in Source , however, if you move this switch , it will be taken as a valid condition

**Comment by guycnicholas** [comment]
Do you have the switch defined in the hardware section?  Mine shows as follows. I am on your same model radio in mode 2 and I have the same version of Ethos.
![image](https://user-images.githubusercontent.com/5494702/134281694-3a3f05a1-07ab-4d0e-b969-c41ff3a0d0d0.png)
![image](https://user-images.githubusercontent.com/5494702/134281727-00a29d45-c61c-43cf-ac1c-7face9c88b1e.png)
![image](https://user-images.githubusercontent.com/5494702/134281744-941bc807-4c83-4478-adc8-be30128f8660.png)

**Comment by sylricflo** [comment]
my bad...  issue is fixed
 you  have found the explanation. the switch was not defined in the hardware section.   The switch F is now available again.

thank you guycnicholas for your help
