### ISSUE TITLE
Turbine Telemetry - sensors

### ISSUE THREAD

**Issue by Thoemse** [FrSkyRC/ETHOS-Feedback-Community#984]
With the rather widely known modul V-SPeak it is possible to get telemetry to FrSky Tx for all sorts of Turbine ECUs from most known manufacturers.
This works allready but some sensors get wrong settings and are not usable (Fuel in ml is for example not functional).

I am in contact with the developer and he sent me these values. He thinks that it should be possible to fix it so it shows correct in ETHOS if you have this information. Could have a look at these:

Address       Format                   Data                                         Example
0x0400          S32                     (T1) EGT in °C                          465°C            0x00 00 01 D1
0x0410          S32                     (T2) Status                               Running        0x00 00 00 14     ( = 20°C)          Glow Bad  0xFF FF FF FF  ( = -1°C)
0x0500          U32                     RPM                                         92500rpm     0x00 01 69 54
0x0600          U32                     (FUEL%) Throttle in %             78%              0x00 00 00 4E
0x0900          U32                     (A3) Turbine BATT                   11,72V          0x00 00 04 94
0x0910          U32                     (A4) PUMP                               2,57V           0x00 00 01 01
0x0A10         U32                     FUEL in ml                                2451 ml       0x00 03 BD 6C     (FUEL x 100)

The FUEL Value shows with too many digits. Something that got transfered from OpenTx unchanged.

S32.... integer     signed 32 Bit
U32.... integer unsigned 32 Bit

**Comment by i3dm** [comment]
have you tried any of the Zavionix RDT sensors for FrSky? they work well :)

**Comment by Thoemse** [comment]
> have you tried any of the Zavionix RDT sensors for FrSky? you may like them

That wouldn't help. Zavionix does the same as V-Speak afaik.  The sensors come just right in OpenTx just like Zavionix. The problem is ETHOS interpretating the incomming values.
V-Speak sends it via S-BUS and ETHOS makes something out of it. In case of turbine telemetry it is correct in most cases like Temperature. In case of the FUEL sensor it does not apply the correct value. I believe it shows voltage - not sure yet.
It's not the fault of the ETHOS developers either but with the info I posted above they can hopefully make them show correct.

**Comment by i3dm** [comment]
are you sure thats the case? i know the Zavionix developer and he is very useful with issues like this and firmware updates if theres a need :)

try him.. i guarantee success.

**Comment by Thoemse** [comment]
The V-Speak dev is very nice too. I see no reason to switch. The module works. I only need Ethos to show "ml" instead of another value.

**Comment by i3dm** [comment]
ok my friend :)
if you need any custom work on a turbine sensor let me know.

**Comment by Thoemse** [comment]
Thank you very much!

**Comment by i3dm** [comment]
are you a member of "Frsky Jet Action" group on facebook?

**Comment by Thoemse** [comment]
Nope not jet. Technically I don't fly a jet. I fly a Kingtech KT-800 turbine helicopter. ;-)

**Comment by i3dm** [comment]
im pretty sure thats a jet! do you have facebook? how do i find you?

**Comment by Thoemse** [comment]
I just asked to join the group. I'll make a post once I am in.

**Comment by bsongis-frsky** [comment]
> The FUEL Value shows with too many digits. Something that got transfered from OpenTx unchanged.

Did you try to delete the FUEL sensor and discover again (with 1.0.11 final)? It should work out of the box

**Comment by Thoemse** [comment]
I'll try rediscovering tonight.

**Comment by Thoemse** [comment]
> > The FUEL Value shows with too many digits. Something that got transfered from OpenTx unchanged.
> 
> Did you try to delete the FUEL sensor and discover again (with 1.0.11 final)? It should work out of the box

Latest firmware is installed. I rediscovered all sensors and made a video. As you can see I have a ton of sensors showing. The Temp sensor that shows 20ish degrees is the engine temp sensor and works correctly. "Krafstoff" in % is the throttle and working. Just wrong label but that can be changed. ADC3 is the ECU Voltage (3S LIFE). ADC4,  ADC2, and Temp 2 do nothing for some reason.

https://www.youtube.com/watch?v=vNR0uF19j2A

**Comment by hwa2611** [comment]
Hi there,
I have the same problem with a Jetcat ECU and Vspeak. In the ECU I set the capacity of the tank (3.7 liters). The ECU calculates the remaining capacity based on the flow rate and transmits this to the receiver via the Vspeak. With the X-lite Pro this works without any problems. With the Tandem X20s, this sensor is always only 0%. I can't change the unit either. Firmware is 1.0.11. All sensors have already been deleted several times and searched again. Greetings Heiko

**Comment by bsongis-frsky** [comment]
0x0A10 is a DIY sensor, not part of the S.Port specification
You should be able to configure everything using the DIY Sensor screen
