### ISSUE TITLE
Request : Adding Favourite menu list

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#986]
It would be nice to add a favorite menu list to the home screen. 
For example you touch the Ethos logo or a homekey and get a configureable shortcutlist. ( Mixer , log.switchs, curve ect.)

**Comment by jreis1** [comment]
nice feature to have!

**Comment by mawzthefinn** [comment]
Could be useful, or just allow re-ordering of the Model screen
