### ISSUE TITLE
ExtModule Bay SPORT / MAVLINK output

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#987]
I believe an opportunity exists to enable better integration into products like MFD Crossbow antenna tracker.

An ideal scenario would be to allow the external module bay to have a 'module' plugged into it that was in essence just a bluetooth serial port. 

Think an HC05 module

This module could be configured to connect to a remote BT serial device -in effect allowing the likes of S.PORT or MAVLINK to be relayed to a remote ground station.

This would potentially allows

1. MFD Mini Crossbow antenna Tracker to function while using a PARA head tracker on the internal module.
2. ArduoPilot Ground Station software could in effect receive comprehensive flight stats to be displayed on a PC.

In an ideal word; the transmitter would output MAVLINK; hower S.PORT would suffice.

In this scenario the radio simply uses the external module using a protocol of 'MAVLINK OUTPUT'. or S.PORT OUTPUT'.

The power to the module would power up the device; and the normal pins used for sending a signal to the module in the bay would simply output the serial stream.

I believe that this function alone would tempt many long rangers to use the X20 as they already use mavlink enabled trackers!

**Comment by OldGazer** [comment]
I don't know about the antenna tracker, but I do know that an ArduPilot Ground Control Station (GCS) computer  supports telemetry via 900/800mHz radios.

Full telemetry to  the radio  is possible as well but it all hinges on LUA scripting.  This functionality has existed in OpenTx for quite some time.  https://www.craftandtheoryllc.com/store/flightdeck/  https://ardupilot.org/copter/docs/common-frsky-yaapu.html

**Comment by robthomson** [comment]
> I don't know about the antenna tracker, but I do know that an ArduPilot Ground Control Station (GCS) computer supports telemetry via 900/800mHz radios.
> 
> Full telemetry to the radio is possible as well but it all hinges on LUA scripting. This functionality has existed in OpenTx for quite some time. https://www.craftandtheoryllc.com/store/flightdeck/ https://ardupilot.org/copter/docs/common-frsky-yaapu.html

Hey.. Totally ardupilot can also use a 900mhz radio.

But it can also equally use the existing downlink from your control system.  This is frequently done with crossfire and there Bluetooth mavemu system.

**Comment by mawzthefinn** [comment]
The internal BT module can output S.Port today. There's a bug in 1.4.3 for it, but it's fixed in 1.4.4
