### ISSUE TITLE
Message CRC wrong by set the timer

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#988]
A customer do the following and got the following trouble.

"I set the flight time (stopwatch 2) to ON at "activated". The clock continued to run immediately. As a test, switch the transmitter off and on again. The model cannot be loaded, message: CRC wrong. What now?"

He can use all other planes and after cloning the damaged model memory, the cloned model also works again.

He remembers that he had taken a screenshot of his settings. Since the screenshot was not saved, it can be assumed that it was not saved when the X20 was switched off.

Regardless of whether the screenshot has anything to do with the problem, I would like to suggest preventing the transmitter from being switched off as long as data is still being written to the SD card. Otherwise, in rare cases, damage to the SD card cannot be ruled out.

**Comment by Hobby4life** [comment]
Is he using the stock 4gb SD card?

**Comment by bsongis-frsky** [comment]
I need the damaged model.
The transmitter is switched OFF only when data is completely written (logs files closed, screenshots finished).

**Comment by EngelMT** [comment]
O.k. will ask the customer and let you know.

**Comment by EngelMT** [comment]
Here the answer from the customer. Shit!!

Unfortunately, I deleted it when the cloned model was already in order. Unfortunately, I only thought of this possibility much later. What a pity. Did it disappear completely then and how could I find it? In the editor, one model was completely empty.

**Comment by bsongis-frsky** [comment]
OK. Please next time it happens, he doesn't remove the file. But I wonder if he already opened another issue for the same problem.
