### ISSUE TITLE
SBUS servo, telemetry, setup

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#989]
I would ask the question again.

Errors, comments.

The aircraft is a 1.5 DLG,
I chose this system because the new SBUS servos are small, powerful and seemed the perfect choice.

Hardware configuration:

Radio: TANDEM X20S (Firmware 1.0.11)

Servo: HV5701 (Firmware HV 1.5.5 latest release)
The old firmware 1.5.4 contains incorrect telemetry temperature data. Fixed at 130 degrees Celsius. The HV 1.5.5 firmware finally shows the temperature. Still pretty bad data.
In a 22 degrees Celsius apartment with 4 servos connected temperature readings 12; 17; 28; 17 degrees. After 10 minutes 22; 28; 36; 30

Receiver: ARCHER GR6 (Firmware v2.1.8 latest version)

The four servos are configured:

Physical ID: 01; Application ID: 0A; CH1 channel
Physical ID: 03; Application ID: 0C; CH3 channel
Physical ID: 04; Application ID: 0D; CH4 channel
Physical ID: 05; Application ID: 0E; CH5 channel

The four servos are connected to the receiver via F.PORT2.0.
The telemetry sees the four servos (SRV1; SRV2; SRV3; SRV4) and reports their data.
However, if I want to modify any of them, it mixes the data of the 4 servos. 
In fact, if I open the same SRV1 more than once (Decice Config), the set values (Phy. ID - App. ID - Channel) will change permanently. Merged data.
The same happens for SRV2; SRV3; SRV4.
So it is impossible to set any of them to a different value later (F.PORT2.0)

Another problem.
The SRV1 SRV2, SRV3, SRV4 does not identify the servos as separate units, only apparently.
It would need the channel number or another identifier. E.g. Psyhical ID.
If there are only 4 servos, one can play with it, but where there are 10 and only one should be adjusted for rotation direction?
Of course this is impossible now, since it mixes the IDs.
If by chance the IDs do match and I change the rotation direction or channel assignment, the servo will no longer work during the writeback process because it will write back the data together.
Should I remove the hardwired (soldered) servo? 
If I want to reconfigure all of them, should I remove all of them? 

When one servo is connected, it works fine!
Mixing only happens if you connect more than one servo.

Also, the problem is that if the servers are configured, why can't they be updated on F.PORT2.0 and why do I have to connect them one by one?

This would be nice to solve since they are attached to the SBUS bus.  Since updates come out quite often you can't always take everything apart and update one by one. So the update is very difficult and complicated.

**Comment by bsongis-frsky** [comment]
This is not related to Ethos, right?

**Comment by Hobby4life** [comment]
A little bit as. Xact should be the "thing" in combination with ethos.
I suggest not to close this. But gather the frsky team to follow this too.
Because xact is still a big ? For many. And there are no real places for concentrated direct feedback of frsky.

**Comment by Adelaxie** [comment]
Due to volume limitations, the temperature sensor built into the steering gear is not accurate, so it is recommended to be used only as an alarm indicator.
The ID problem does exist and needs to be fixed.

**Comment by Adelaxie** [comment]
>For example I have 2x HV5611 I want to use for a DLG.
But to have full functionality of Xact I have to connect them to FPORT2.0
But if I want to add a smartport sensor, this is not possible directly.
I have to use the S2F.PORT2.0 unit.. this thing is too big! it wont fit in a DLG!

There will be new sensors with F.PORT2 coming.

**Comment by jufelap** [comment]
> Ez nem kapcsolódik az Ethoshoz, igaz?

Why not an ETHOS problem?
Exactly that.

**Comment by jufelap** [comment]
> > Például van 2x HV5611, amit DLG -hez szeretnék használni. 
> > Ahhoz 
> > azonban, hogy az Xact teljes funkcionalitása elérhető legyen, csatlakoztatnom kell őket az FPORT2.0 -hoz. De ha hozzá akarok adni egy smartport -érzékelőt, ez közvetlenül nem lehetséges. 
> > Az S2F.PORT2.0 egységet kell használnom .. ez a dolog túl nagy! nem fér bele a DLG -be!
> 
> Új érzékelők érkeznek az F.PORT2 -vel.

That's right. You need to connect to FPORT2.0.
The receivers know that.
You don't need anything extra.
It works perfectly and I saved a lot of space and wiring.
So you don't need to use any kind of unit, just an Archer GR6 or RS receiver.
I stripped the GR6 receiver completely and connected all the servos to the SPORT2 via a three wire cable.

**Comment by jufelap** [comment]
> A hangerő korlátozása miatt a kormányműbe épített hőmérséklet -érzékelő nem pontos, ezért csak riasztásjelzőként ajánlott használni.
> Az azonosító probléma létezik, és ki kell javítani.

Thanks for the info. I wrote this problem down a long time ago, but no one has responded.
I hope it will be fixed as soon as possible and that the assembled system can be configured properly.

**Comment by jufelap** [comment]
> @Adelaxie @WismyYao
> Egy kicsit úgy. Az Xact legyen a "dolog" az etosszal kombinálva.
> Javaslom, hogy ezt ne zárjuk be. De gyűjtsd össze az frsky csapatot, hogy ezt is kövessék.
> Mert az xact még mindig nagy? Sokaknak. És nincsenek valódi helyek az frsky koncentrált közvetlen visszajelzésére.
> Van és van még mit fejleszteni, hogy az xact legyen a "dolog".
> 
> Például van 2x HV5611, amit DLG -hez szeretnék használni.
> Ahhoz
> azonban, hogy az Xact teljes funkcionalitása elérhető legyen, csatlakoztatnom kell őket az FPORT2.0 -hoz. De ha hozzá akarok adni egy smartport -érzékelőt, ez közvetlenül nem lehetséges.
> Az S2F.PORT2.0 egységet kell használnom .. ez a dolog túl nagy! nem fér bele a DLG -be!
> 
> Ezt a problémát ki kell javítani .. minden Fport2.0 -kompatibilis vevőnek csak FP2ORT2.0 -t kell kiadnia bármely fizikai csatornán. és hagyja el az intelligens portot az érzékelők számára.

Isn't the point of FPORT 2.0 that you can connect units in parallel? 
I have the four servos on a common rail and connect to the GR6 F.PORT2.0 input. It works.
No need for any other units.
S2F.PORT 2.0 is only needed if the receiver does not support the F.PORT 2.0 protocol.
So it fits perfectly into the DLG because you don't need the S2F.PORT 2.0 unit.
![F Port2_ 0-04](https://user-images.githubusercontent.com/84585992/134662434-a2286825-dc43-4312-bc27-3c1fa75f4ccf.jpg)
![242370320_554876719061696_7186410592391976148_n (1)](https://user-images.githubusercontent.com/84585992/134662877-436d0da0-6837-4a78-b571-23e390e81e97.jpg)


![242377795_542861746797369_8622460941446679629_n](https://user-images.githubusercontent.com/84585992/134663174-684a1aa5-16b1-45e4-9a77-eb27a3acd368.jpg)
![242361626_3096842033880083_3926478634504320755_n](https://user-images.githubusercontent.com/84585992/134663224-2c2bb27b-dba1-4c89-b44c-369d63aa4da9.jpg)
![242385655_616472532681241_4284538842198007004_n](https://user-images.githubusercontent.com/84585992/134663300-7471fdb7-8169-4682-8b4f-cb334c1078eb.jpg)
![242402426_155025663415701_3728972835749839037_n](https://user-images.githubusercontent.com/84585992/134663401-7fc3e818-a54f-452a-a8b6-181a0413d64f.jpg)
![242355047_593733838314174_5814150246303850737_n](https://user-images.githubusercontent.com/84585992/134663421-34a5ca6b-6392-402e-b33c-b891d7789d06.jpg)

**Comment by Hobby4life** [comment]
> S2F.PORT 2.0 is only needed if the receiver does not support the F.PORT 2.0 protocol.

No. You still need it when you want to use smartport sensors in combination with fport2.0 servos to get telemetry from both.

**Comment by jufelap** [comment]
> > Az S2F.PORT 2.0 csak akkor szükséges, ha a vevő nem támogatja az F.PORT 2.0 protokollt.
> 
> Még mindig szüksége van rá, ha az intelligens portérzékelőket az fport2.0 szervókkal együtt szeretné használni, hogy mindkettőből telemetriát kapjon.

What other smartport sensors would I want for DLG aircraft? :) 
Thanks for the info anyway!

**Comment by mawzthefinn** [comment]
Has this issue been resolved? Or is it still occurring.

**Comment by jufelap** [comment]
Since I haven't heard back that this has been fixed, I don't know if it has been fixed or not. I don't want to try, because then I have to reconfigure the servos one by one.
The last feedback was that the bug is live and will only be fixed later.

**Comment by mawzthefinn** [comment]
Just got a pair of HV5701's to test and was able to duplicate, on latest XAct HV57 firmware (2.0.1)

It almost seems like ETHOS is populating the Device Config menu with the first servo to respond for each item, not the requested servo.

Not sure if this is ETHOS polling all servos instead of the selected one or multiple servos responding to a poll intended for one only.

**Comment by yufasa** [comment]
Hopefully this is one of the things that is on the pile of improvements for 1.5.0?
Initial config is one thing but setting up centers etc is not possible with the current firmware unless you disconnect all the other servos and that is just not ideal.
Once the servos are configured I should be able to address them individually for adjusting...

**Comment by ZS-Man** [comment]
I also wonder if this will be fixed in 1.5...
And besides the configuration capability, what about the bulk FW OTA update? Will it also work (I don't have the courage to try it)? What if there will be different types of Xact servos?

Frsky F.Port 2.0 PR says: "All the connected devices can be upgraded and configured by the ACCESS radio over the air."

That's a nice enticement, but in the case of Xact it's more of a trap..... :-(

**Comment by jufelap** [comment]
When will the bug be fixed?

**Comment by bsongis-frsky** [comment]
Fixed in 1.4.10. You have to go to Model / Telemetry and choose the servo you need to setup, then you choose "Sensor Config". Only this servo will answer and you will be able to change its settings.
