### ISSUE TITLE
Status of logical switches not visible

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#99]
It would be helpful if the status of the logical switches could be seen on the home display or some other place.

**Comment by Nicholas-Luoyi** [comment]
In logical switches list. The active LSW will be bold and highlighted now. Isn't it?

**Comment by Skippydi** [comment]
Jepp ok, i saw it :-)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 26. Apr. 2021 um 09:24 Uhr schrieb FrSky-Luo <
***@***.***>:

**Comment by Skippydi** [comment]
OK
