### ISSUE TITLE
Please add trim source

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#992]
In the trims menu, please allow picking a source for each trim.
for exmaple, some jet pilots like to use a knob (or the red linear pot at the bottom of X20) for quick turbine (throttle) trim.
thank you.

**Comment by FrSky-GX** [comment]
You can assign a new mxier with knob to the channel to relize the same function. we will talk about your advice in new versions.

**Comment by mawzthefinn** [comment]
Simplest thing I can think of here is extending the Cross Trim menu to allow any valid input, not just the 4/6 trimmers. Essentially use the Use a Source input, with the respective trimmer as a default setting.

**Comment by mawzthefinn** [comment]
Removed Stale here, still want arbitrary trim inputs in some fashion

**Comment by bsongis-frsky** [comment]
Done in 1.5.0
