### ISSUE TITLE
6 Position Switch as Mix Input

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#994]
Please can we enable the ability to use the 6 position switch as an input to a mix.

If this where done; it would be easy to simply use a curve to apply an offset to each switch postion.

Net result - only one channel is used for 6 individual positions.

This can currently be achieved - but results in 6 individual mixes.

**Comment by Nerenye** [comment]
That´s an pretty overdue request i guess. It´s awful to use the switches at the moment

**Comment by mawzthefinn** [comment]
You can do this with a VAR mix, use the FSW's as Weight selectors on the VAR mix, and its output channel is your source. If you just need to send arbitrary values to a channel (ie flight mode selection or similar) you can control a channel directly with FSW's and a VAR mix

This also lets you do fully-custom values for each position, useful when setting up flight modes with a 6-pos configuration of the FSW's.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/193989202-110e3b01-7fef-4a91-87c2-7685af0bc8b9.png)
