### ISSUE TITLE
GPS to QRCODE

### ISSUE THREAD

**Issue by robthomson** [FrSkyRC/ETHOS-Feedback-Community#996]
This would normally be in the realms of a lua script - however it could potentially be done as an integrated app.

Essentially.. take the GPS co-ordinates on the telemetry input - and generate a QR code that your mobile phone can use to track down your downed model!

**Comment by OlegStelmakh** [comment]
One of most innovating proposal! Like

**Comment by Hobby4life** [comment]
I really like to see this implementation too

**Comment by strgaltdel** [comment]
.. like #569

i'm working on a widget, but it will take some time
based on the speedata lib
https://github.com/speedata/luaqrcode

calculating the QR "array" seems to be very "memory hungry",
don't know how it will behave with several widgets in parallel 

regards



![QR1](https://user-images.githubusercontent.com/20392683/194037946-db5a9952-6e5b-4842-a8ec-a0e079a33deb.png)

**Comment by mawzthefinn** [comment]
Not to steal @strgaltdel's thunder, but the script was posted over at rcgroups

https://www.rcgroups.com/forums/showpost.php?p=50133317&postcount=21308

Looks pretty awesome as a lost aircraft finder.
