### ISSUE TITLE
Gyro Setting Option 

### ISSUE THREAD

**Issue by Ybmmc** [FrSkyRC/ETHOS-Feedback-Community#997]
Would you sperate the Gyro Channel to :
Aileron A Left , Aileron B Right/Vector Ail (twin turbine)
Elevator A Left , Elevator B Right/Vector Elv/Canard
Rudder A Left , Rudder B Right/Steering/Vector Rudd
That would be easy to setting the model with Vector nozzle control and Canard

**Comment by FrSky-GX** [comment]
For new stablization product or firmware, we will take these advise.

**Comment by mawzthefinn** [comment]
The new Advanced Stabilization system recently announced on the TD SR18, RB25S and RB35S is the answer to this requirement.
